### ISSUE TITLE
Author GitHub Workflow Integrations for Moped Test Deployment System

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10000]
This work is blocked by #9996.

The new test deployment system is created as a Prefect Flow. This flow needs to be invoked by a GitHub action, so that we can use our existing pattern of deploying test instances from the same UI (GitHub) with a similar UX (Actions / Workflows). 

This ticket is to track the creation of that flow, including getting feedback from the dev & product teams. It will also include some brief documentation (see #9998) about how to use the deployment system as well.

I envision the results of a flow invocation will be returned to GitHub when complete, providing the user with the URL to visit for the deployment, and ideally, a deep link into Prefect so the user can investigate the deployment execution in detail (see #9999.)

**Comment by johnclary** [comment]
Closing because we have abandoned the prefect-based test deployments.
