### ISSUE TITLE
BCA Attachments

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10012]
During the Sprint Review on 8/12/22, we determined the supporting documentation section should be converted into an attachments button with a list of options for what type of attachment was being included. 

![Screen Shot 2022-08-12 at 11.14.59 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/42c7772b-600b-4875-8b5e-1fe85bda39c3)

Link to [projects details page.](https://atd.knack.com/smart-mobility#p3-portal/p3-projects/p3-project-details/62e03476ed512500211c38fa/)

## Update

**Attachment Feature**
- Created By/Date = (Attached By/Date)
- Modified By/Date 
- Attachment Description
- Attachment Status
  - Approved
  - Rejected
  - Needs Review
  - Uploaded
- Attachment Type: 
  - Project Schedule
  - Communication Plan
  - Budget, Costs and/or Financial Data
  - Brochure, Specs, Testimony
  - Other:

**Comment by patrickm02L** [comment]
@dianamartin 👀

**Comment by patrickm02L** [comment]
From grooming discussion 08/17/22 we decided that this component would be built without vendor logins.

**Comment by KaroEngstrom** [comment]
F 8/19/22 

- [x] Created BCA Attachment object 
![image](https://user-images.githubusercontent.com/100615928/185695764-605ed69b-8474-4da2-94d8-7b80be828b78.png)

- [x] Added table to Project Details page, with option to edit status so the PM can update the attachment status 
- [x] Added buttons and forms to Add and Edit BCA Attachments

![image](https://user-images.githubusercontent.com/100615928/185696490-18d14156-6803-4cdc-a9a3-9122c0956d3b.png)

@dianamartin / @patrickm02L  - We are tracking latest Modified By account and date. 
- Do we need to show that to the user?
- Do we need some additional note field that PM could use to track status change info, or is simply updating the status enough?

**Comment by dianamartin** [comment]
@KaroEngstrom We can show it to the user

**Comment by KaroEngstrom** [comment]
T 8/23/22 

Adding Attached By and Modified By info; the table will look pretty packed.

**Comment by KaroEngstrom** [comment]
W 9/7/22 

- Moved Edit function to the first column 
![image](https://user-images.githubusercontent.com/100615928/188927298-bfd329e3-8165-4e21-acf2-7a357718f92e.png)

- SMO team approved of this functionality. Closing.
