### ISSUE TITLE
[Traffic Register] Configure Friendly Print page for Regulation Doc

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10030]
Possible Solutions:

1. Default Browser/Knack Print page (MVP)
2. PowerBI Report Builder
3. JotForm PDF Builder
4. FormStack Documents

**Comment by ChrispinP** [comment]
Created rough draft for print page for Reg Docs
![image](https://user-images.githubusercontent.com/67915167/203870293-73657e84-7c20-43bf-8054-e99416ceb056.png)

Ready to review before continued implementation

**Comment by ChristinaTremel** [comment]
## 7/11/2023
- Chrispin and I sync'd and are thinking that this will be the next focus for Traffic Register.
- Already anticipate that users will want a document that looks very similar to the existing traffic register document. Thinking that we might want to explore other options for print views:
   - Formstack documents
   - Jotform
- When we build out the print friendly page, that could replace the Quick Views

**Comment by ChrispinP** [comment]
### Solution 2 Prototype is ready to review:
- Was able to successfully build & generate the PBI Paginated Report with the PBI Report Builder. 
- I created a PDF Report page where the the report is embedded and added menu navigation
- Prototype is functional and displays all Reg Doc data that is not currently missing
- Will need to update the historical data so dates & signatures appear
- The data is updated in PBI every hour during business hours
- Users can Save, Download, or Print a PDF or CSV of the report
- Users can filter the documents by year before selecting a document. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/12cbb2de-d7d7-4429-860b-7237b1c485ef)
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/f94dec63-c168-4c6b-939c-23f40d8a5eb6)

Example:
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/cfa71a4f-1a4b-4df3-9a34-f8529c5fb31a)

**Comment by ChristinaTremel** [comment]
Showed the Paginated Report Regulation Documents during the Sprint Review on 12/12 and the users loved it! 

Some feedback we received: 
- [ ] Add the Delete parenthesis when there is something that's retiring
- [ ] For Approved Regs add a date column after the reg text on the Paginated Report.
- [ ] PDF print page of Traffic Regs - remove function that autosaved the PDF and CSV

**Comment by ChristinaTremel** [comment]
- Created #15116 to address the user feedback! Closing this initial issue for configuring the print page ✨
