### ISSUE TITLE
Create Signs & Markings executive dashboard page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10039]
After viewing the Signs and Markings Dashboard meeting, come up with categories of metrics that we can show in the dashboard (single or multiple pages.)

Work with Charlie to bring that into the Dashboard template pages. 

[WIP Executive Dashboard](https://app.powerbigov.us/groups/me/reports/43bfda27-ba5e-4d7b-b523-60789509b2c6/ReportSectioncd2a1301826d41ca79b4?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&chromeless=true)

**Comment by patrickm02L** [comment]
We'll look at this on Tuesday, August 30th during the Ex Dashboard meeting.

**Comment by katelunceford** [comment]
The State of the Division: Signs & Markings 

1. What are our technicians doing?
2. Where is work being done? Are we prioritizing equality? High injury network?
3. How much does it cost? Are we on budget?
4. How are we responding to customers?
5. Do we have enough inventory, staff, resources?
6. SD23 goals tied to this division? [need to look up]

Need to show deficiencies in maintenance abilities

**Comment by patrickm02L** [comment]
Reviewed Strategic Performance [Dashboard](https://data.austintexas.gov/stories/s/Mobility-Dashboard/gzb5-ykym) in relation to what's being represented in the PW Stat Monthly Meeting templates. Started to hash out how we might transfer strategic performance to PW stat in this [Miroboard](https://miro.com/app/board/uXjVOrZDQA8=/).

**Comment by patrickm02L** [comment]
Kate and Patrick are meeting on 9/14/22 to drill down into the details of what this will be.

**Comment by patrickm02L** [comment]
Via @maccallump goal:
get Executives (Jim Dale) to ask questions about what's being represented in the Dashboard.

**Comment by patrickm02L** [comment]
Worked with Kate 9/22/22 to figure out how to approach the Signs & Markings Page(s). Will transfer the drawings to Miro and clean them up a bit before our Ex. Dashboard meeting on 2/27/22. 
![IMG_3460.JPG](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/c3d1f80f-7195-435d-8a5e-9ff49ac6af34)

![IMG_3461.JPG](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/8b9073a6-d34a-4c5c-a793-e284abc7c44d)

**Comment by maccallump** [comment]
[Ramboll_Micro-Mobility_GreenPaper_A4_0320_lowres_v.pdf](https://github.com/cityofaustin/atd-data-tech/files/9862941/Ramboll_Micro-Mobility_GreenPaper_A4_0320_lowres_v.pdf)
Study of Hoboken NJ Micromobility with KPI

**Comment by amenity** [comment]
Per @patrickm02L, we're going to leverage the dashboard they already have rather than try to rebuild something.
