### ISSUE TITLE
[Feature] Project Tags

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#10044]
As a Moped user, I want to tag projects with keywords, phrases, etc. that will help with filtering and identifying sets of projects, surface related projects, enable [unfunded needs matching](https://github.com/cityofaustin/atd-data-tech/issues/#3678)...

<img width="1041" alt="Screen Shot 2022-09-06 at 3 23 11 PM" src="https://user-images.githubusercontent.com/14793120/188721349-25cc7961-46af-4232-97ce-0ca3167804a0.png">

### In scope
- Ability to add a tag to a project from the project summary page
- Ability to view a project's tags in a table on the project summary page
- Ability to remove a tag from a project
- Ability to search for projects by one or more tags

### Out of scope
- Ability to create new tags
- Ability to edit tag names

#### New table - `moped_tags`
Lookup table for all tags.

| column name | column type | constraints 
|-|-|-
| `id` | `serial` |
| `name` | `text` | `unique` 
| `type` | `text` |
| `slug` | `text` | `unique`
| `is_deleted`  | `bool default false`|

#### New table - `moped_proj_tags`
Ttores tag/project relationships.

| column name | column type | constraints 
|-|-|-
|`id` |`serial`|
| `project_id` | `int` |  FK to `moped_project`
| `tag_id` | `int` | FK to `moped_tags`
| `is_deleted` | `bool default false`

#### Initial seed of `moped_tags`
| `name` | `type` | `slug` |
|-|-|-|
| MAP Signals 2023 | Work Plan | map_signals2023 |
| MAP Transit Enhancement 2023 | Work Plan | map_transitenhancement2023 |
| MAP Vision Zero Systemic Safety Curves 2023 | Work Plan | map_vzero_systemicsafety_curves2023 |
| MAP Vision Zero Intersections Potential 2023 | Work Plan | map_vzero_intersectionspotential2023 |
| MAP Vision Zero Intersections 2023 | Work Plan | map_vzero_intersections2023 |
| MAP Vision Zero Speed Management 2023 | Work Plan | map_vzero_speedmanagement2023 |
| MAP TIA Fiscal | Work Plan | map_tiafiscal |

### Background research
- [IMPDB terms-to-be-mapped](https://docs.google.com/spreadsheets/d/1VGO57EL1TtASbLz2yeWyLwcTB1lT9LR8G6_QZ4WSifs/edit#gid=0)
- [Notes](https://docs.google.com/document/d/1xMTBL-uyNH9keUydl7K29liZdIIHBMdiYTJuqaylTpE/edit#heading=h.p56sm2k8jopf)

### Related features
- https://github.com/cityofaustin/atd-data-tech/issues/1962
- https://github.com/cityofaustin/atd-data-tech/issues/3678

**Comment by amenity** [comment]
Would users using hashtags in the "Description" field (a la Twitter) be a good way to start this? #randomidea #folksonomy

**Comment by johnclary** [comment]
One open question is if we want tags to have a name plus a value. If we have a Moped tag called `Bond Corridor`, the user picks that tag, and then picks a value, e.g. `Airport Boulevard`?

We might say "no" to that complexity, and just have "standards" for tags. Like how we hack github, users could prefix their tags like `Bond corridor: Airport Boulevard`.

I think a scoping sesh might be could, where we review our known use cases and talk through potential data models.

**Comment by johnclary** [comment]
Based on a quick conversation with @amenity and @chiaberry, i'm leaning in favor of the simple approach of free-form tags (like our github labels). The interface would entail:
- On the project summary page:
  - An autocomplete form input where you can search existing tags, with an option to create a new one
  - A table below the input with the list of tags, which you can remove, but not edit
- On the project list: an advance search filter for searching by one or multiple tags

We will also need an interface for editing/deleting tags. Do we need to restrict permissions on this, since editing a tag will edit it in all places it is used? Do we soft delete tags?

At the DB level, we would use a many-to-many relationship between projects and tags. The tags table could be extended in the future if we wanted to add additional tag attributes.

**Comment by johnclary** [comment]
I've updated the issue description to match our most recent conversations. @johnclary will get an initial list of project tags from NW.

**Comment by johnclary** [comment]
i've added the initial list of `moped_tags` that Nathan provided. the `slug` column maps to the unique identifier of this tag in the Access DB (except i've made them lowercase)

**Comment by johnclary** [comment]
This has shipped!

**Comment by amenity** [comment]
Beautiful, @chiaberry @johnclary 😊
