### ISSUE TITLE
Ability to Submit Inventory Request from Work Order

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1004]
## Test Script

1. Create a new work order in Data Tracker. Assign it to the CROSS PARK / CAMERON signal.

2. At the bottom of the page, add inventory using the "Under Develop" form. When you add the item, set `Inventory Checkout` to "Yes"

### Expected behavior

- The item will be added to the work order with a status of "Submitted to Warehouse".

- A new inventory request will be created in the finance system with status "Submitted".

- Your requested item will be added to the inventory request with a status of "New Request"

**Comment by johnclary** [comment]
working from `master` in this new repo:
https://github.com/cityofaustin/atd-knack-api

**Comment by johnclary** [comment]
@dianamartin ready for testing.

**Comment by dianamartin** [comment]
Created new WO: `WRK20-073355`
For signal: `952: Cameron Rd/Crosspark Dr`

I chose to do the `12 inch GPL Louver w/Slotted Full Circle Visor w/ Universal | EA` and submitted it as a checked out item. 

The status set to `Submitted to Warehouse`.

**Comment by dianamartin** [comment]
Success!
