### ISSUE TITLE
[MEETING] Artbox Program - Discussion (Inquiry)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10045]
### Objective 
Luke sent a meeting invite this morning 8/17 to have a quick discussion about the [ArtBox Program](https://www.austintexas.gov/page/artbox-program)

### Participants
Luke, Diana

### Agenda
Talk about what SMO needs for this program
High-level Functional requirements

------
- [x] Schedule meeting - 8/17
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
Found the ArtBox Program page
- see that there is an application form - Google [Form](https://docs.google.com/forms/d/1KO_V4adskfK6r5TzXpy1YlTc1F12xM2jCLVcUfjpQVc/viewform?edit_requested=true)

# Placemaking 
6 different programs

## ArtBox Program
Hannah was formerly the contact

## Living Streets Program
- currently managed in AMANDA
- permit?


Approached by SmartSheets by SMO
- don't need to go into a different solution

They are thinking about on boarding more programs into Knack. 

# AIPP
- Submit Application
- 10 in one year
- SMO did 6 artboxes
- Collaborate with them - DAA, Corridor Program
- Switches, Battery Back-ups - coordinate with AMD
- Contract with a studio, with the management
- Pain Point: 16 artboxes, tasked to do about 40
- Program is growing very fast, double, triple
- 3 month process (app, community engagement)
  - Arts Commission, Arts Collection Management
  - Using the artist selection pool for AIPP
- Stakeholder committee, goes through the artist and gets feedback

Asking more for creative crosswalks
8 programs - only 4 staffers 
- all needs 1 and 1.5 people to support

## Living Streets FY2023 (Spring of 2023)
- healthy streets (ATSD fundings - SMO)
- shared streets (PWD)
- place streets 
- neighborhood block parties (OSE,SMO)
- public plaza promenades

## Prioritizing Projects
- Artboxes - similarities with crosswalks
- Creative Crosswalks - similarities with artboxes
- Living Streets - own module (ATSD, interested in AMANDA only)
- Plaza, Promenades and Hubs - stand alone 
  - move forward, scope of 18 mil - no funding
  - downtown station area (4th and Red River)
  - pedestrian friendly - collapsible bollard (revising existing infrastructure)

**Comment by dianamartin** [comment]
@patrickm02L this is the discussion I had with Luke. I had given him a shared link to the Miro board so that he can plot out that workflows for all the programs they manage so we can a better idea when we scope it. He said he's going to get with this other Program Manager, Sandra, to finalize so stuff before they submit a new DTS request.

**Comment by patrickm02L** [comment]
@dianamartin thanks for taking the inquiry meeting. This looks like a fun project!

**Comment by dianamartin** [comment]
Luke said he'd review with his team the workflows and then submit an official DTS request, Closing.
