### ISSUE TITLE
Fix regression associated with down migration in Moped

### ISSUE THREAD

**Issue by tillyw** [cityofaustin/atd-data-tech#10041]
A regression is introduced in [9973](https://github.com/cityofaustin/atd-moped/pull/749) if a user tries to run [this down migration](https://github.com/cityofaustin/atd-moped/pull/749/files#diff-dc8cfd7bcebb9b6e65eb7af781bec1c269b3eb171cbfe9af6ad3eaa7a9022226) when one of the new milestones is in use. Rather than hold up the new release, we decided to break up fixing this 'regression' into a separate issue.

@frankhereford please comment on here and add any tags you feel are necessary!

**Comment by frankhereford** [comment]
I think you've captured this well. I added some labels per your request. I think the links in your comment are helpful, especially to the comments by @john in the PR.

I would be happy to try to help work on this issue if that would be useful to you. Thanks! At the least, I may be helpful in getting a database migrated up to but no further than the up migration that pairs with the down migration in question. Thanks!
