### ISSUE TITLE
Add document buttons to TDS service landing pages

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10051]
### All services have a landing page. Each page should be consistent with the info/document buttons. 

**Already Done:**
- SIF

**Add To:**
- TIA
- Determination 

![Screenshot 2022-11-09 at 1.41.40 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/752a7b75-584d-42d6-9f2b-4ae18957b8ff)

**Comment by ChrispinP** [comment]
This will be completed as a result of [#11154](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/gh/cityofaustin/atd-data-tech/11154)

Closing
