### ISSUE TITLE
Ability to Approve Inventory Request in Data Tracker

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1005]

**Comment by amenity** [comment]
@johnclary can you add an estimate to this? I called it Sprint 13, too... Correct if needed.

**Comment by amenity** [comment]
And assign someone. ;)

**Comment by johnclary** [comment]
Per discussion with Billy, we've removed this requirement. And we're not going back! Leaving the estimate as a 2 because we did actually implement it. And then removed it.
