### ISSUE TITLE
Publish "contractor work logs" knack data in Open Data Portal, relates to "Contractor Work Orders"

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10061]
Synced with Christina and she said that they'd like to have just a a table for the "contractor work logs" going to Open Data Portal. I'll can create a new issue for that.

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/7442#issuecomment-1219841216_

**Comment by dianamartin** [comment]
# To Do
- [ ] Create API table view for `contractor_work_log`
- [ ] Create Open Data Portal empty dataset?
- [ ] Dev: Set up ETL process for this

Reference #7442

**Comment by dianamartin** [comment]
@johnclary are the above steps correct when moving knack data to the Open Data Portal? and not going to AGOL.

**Comment by johnclary** [comment]
@dianamartin yep!

**Comment by dianamartin** [comment]
- Charlie asked to create the ODP dataset on 8/23
- Charlie created the dataset and was testing it 8/26
- Christina reviewed and asked to add 2 more fields to the dataset on 9/1
- Charlie worked on adding these fields 9/8
- Christina confirmed she saw the fields in the dataset and said
>Yes! He was so fast. It looks perfect

Most of the comments on task items is on #10002
