### ISSUE TITLE
Offboard Rebecca B.

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10066]
[Gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/offboarding/off-boarding-checklist)

## IT Permissions and Access

- [x] Slack
- [x] Miro - did not have a license
- [x] GitHub - (reassign issues, too)
- [x] Google Drive
- [x] Remove from [Github](https://github.com/orgs/cityofaustin/teams/transportation/members)
- [x] SERF

## Admin

- [x] DTS email DL
- [x] About Us - Move to Alumni Section
- [x] DTS Team Slide - wasn't added

**Comment by patrickm02L** [comment]
@rebeccabrand provided this [Handoff Doc](https://docs.google.com/document/d/1fxy_181RTypDiNz49adZrvRiwusl0tiStPVE-Q2VULc/edit) for offboarding.

**Comment by patrickm02L** [comment]
Issue #10075 takes care of moving Rebecca to the alumni section.

**Comment by patrickm02L** [comment]
@amenity can you please unassign rebecca from slack.

**Comment by patrickm02L** [comment]
Submitted SERF 08/22/22. Will remove from email, network, and github.

**Comment by patrickm02L** [comment]
MC removed from Slack 8/23/22

**Comment by mateoclarke** [comment]
deactivated from Slack 8/23
