### ISSUE TITLE
Build Transactions Records in Banner Production Apps

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10068]
Set up transaction records in production

**Comment by moorerst** [comment]
@dianamartin do we need to get this completed so we are ready for testing during the build phase with Citybase?

**Comment by dianamartin** [comment]
@moorerst no, because it's already in the Test CITY BASE Street Banners environment. I believe they'll be testing in there first. I do need to do it though. I have it earmarked to do on Friday.

**Comment by dianamartin** [comment]
# Build Out on Prod
- [x] create `invoice_transactions` object table
- [x] Add financial fields - 10/24
- [x] create `Transactions` page 
- [x] Create "Invoice LPB" page/form - 10/24
  - [x] Configure record rules  - 10/24
- [x] Created "Invoice OTS" page/form - 10/24
  - [x] Configure record rules - 10/24

**Comment by dianamartin** [comment]
# Payment - Big Button 
- [ ] Make Payment button

**Comment by dianamartin** [comment]
The last thing to configure was the "Make Payment" button. Added that on 11/16, Chia worked on the rest on 11/16 and 11/17.
