### ISSUE TITLE
Refactor Inventory Request Process in Finance & Purchasing to Handle Non-Work Order Requests

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1006]

**Comment by dianamartin** [comment]
We had a `New Inventory Request` in the F&P system. However it had the `task order` on it, I removed it. But then I started to think who/what user would need this form. It seems like it would be a person like (ex. Joshil) checking out Gridsmart devices or possibly the Signal Engineers. 

The other users that might be utilizing this kind of form is a "Contractor type". Would need to wait until we have our "Contractor work flow" meeting with AMD to determine how to configure this any further.

**Comment by johnclary** [comment]
No longer needed. We're handling all inventory requests in the Data Tracker and have created the "Non-Technician" work order to handle their checkouts.
