### ISSUE TITLE
[Traffic Register] Feature: Populate URL field with URL from browser on Trigger Button press - "Bookmark"

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#10074]
**Scenario:** As a Knack user I want to be able to save the page I am on to return to later.

**Desired Outcome:** Knack user is able to click a Trigger button that "bookmarks" their page without having to copy and paste the URL from their browser. (similar to browser bookmarks or Amanda 7)

**Problems:**
- Users must search and navigate every time they want to view or work on the same page
- Increased time in app, especially larger apps

**Context:**
Object 27, Field 862
![image](https://user-images.githubusercontent.com/67915167/185709542-f651a398-f26d-4f03-8a70-ede770c5a79a.png)

**Comment by ChristinaTremel** [comment]
Iceboxing until users ask for this Traffic Register functionality.
