### ISSUE TITLE
[Traffic Register] Enhancement: Auto Populate Drafted Reg Doc ID

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#10073]
**Desired Outcome:** Simplify the drafting process by auto-populating the Drafted Reg Doc ID to assist with self-connection and connection to all regulations rather than user having to search and set it themselves.

**Problems:**
- User input means a user can enter/select the incorrect ID and mess up the connections
- Increased Drafting time

**Context:**
- **Retire Page:** `Scene 449`, `View 890`, `Field 561` - Self Connection for Approveds set to `Field 936` - Regulation Document ID
- **Retire & Replace Page:** `Scene 450`, `View 892`, `Field 561` - Self Connection for Approveds set to `Field 936` - Regulation Document ID 
- **Save Draft Page:** `Scene 454`, `View 902`, `Field 560` - Self Connection for Drafts set to `Field 936` - Regulation Document ID
![image](https://user-images.githubusercontent.com/67915167/185707285-2a6e7aa9-ec88-424f-9d98-af361ba11b21.png)

Similar to Issue #9052

**Comment by dianamartin** [comment]
Here is the AMD Data Tracker JS code in atd-knack [repo](https://github.com/cityofaustin/atd-knack/blob/master/code/data-tracker/data-tracker.js)

**Comment by amenity** [comment]
Would be great to get in place as soon as possible.

**Comment by dianamartin** [comment]
@chiaberry @amenity I've pushed the meeting back with stakeholders, so we have more time to work on this enhancement. Hoping completion is by 9/14 so we (Apps) have time test before getting it out in front of stakeholders.

**Comment by chiaberry** [comment]
@johnclary did you say you wanted to take this one?

**Comment by johnclary** [comment]
@ChrispinP i've got this working on the "Retire" page. I had to hide the "Match Reg ID" field because manipulating it in a way that will look weird to the user.

Would you give it a try? I'm a _little_ concerned my approach will not work well when there are lots of records in the `regulation_documents` object. The code is basically simulating a search on the connection field, and i'm not sure its 100% reliable....

**Comment by ChrispinP** [comment]
@johnclary hola, tested 3 variations, none populated the `Self Connection for Approveds - Field 561` value with the Draft ID from the Text Formula `Field 950`. Added and switched to the `Reg Doc ID Field 936` and still unsuccessful. I added the 2 fields and their IDs to the page to help out. You may use the test approved reg I created for testing - 59804.
![image](https://user-images.githubusercontent.com/67915167/189417607-1c3c5d01-17f8-4ed1-8661-6adc344d6e66.png)

There are thousands of records which will continue to grow so how the search is done is important. Normal connection searches takes several seconds after entering 3 characters to pull up results. Also when working with inputting values, knack prefers when things are on the same view to add a value or calculate a value in the field input/output before form submit. Since our Reg Doc ID is auto generated and has conditionals it cannot be added to the form so may need alternate method or field to host the Reg Doc ID in order to pull into field 561 possibly.

Lastly the hide method waits for the field to load before hiding and is very abrupt for a user. I believe a better method is necessary and Knack may require the input field to be visible to give it a value.

**Comment by johnclary** [comment]
👍 i tired using the exact same approach as https://github.com/cityofaustin/atd-knack/pull/119, but for some reason the values were not being set correctly. i'll try again next week :/

**Comment by johnclary** [comment]
@ChrispinP would you try the retire reg page again? I've updated the code and it's working for me.

**Comment by ChrispinP** [comment]
The Retire page is successfully populating 👍

Encountered a bug when selecting another drafting page such as Install or Retire & Replace, closing the modal, and then navigating back to the Retire page, the ID does not populate. I have to close the Retire modal and then click Retire a second time for the ID to populate.

Feel free to start working on the other two pages; Retire & Replace and Save Draft 🤠

**Comment by johnclary** [comment]
👍 i'll see if i can fix that and will set up the other pages.

**Comment by johnclary** [comment]
@ChrispinP i've installed this code in all thre places. I could not replicate the bug you mentioned. You want to pair with me or post a video?

**Comment by johnclary** [comment]
@ChrispinP should be all fixed now. I added a `setInterval()` that checks the field every 500ms and populates it if needed.

Please approve PR at your convenience: https://github.com/cityofaustin/atd-knack/pull/121

**Comment by ChrispinP** [comment]
Hey @johnclary sent ya a clip of the new consistency issues/bugs:

1. The ID sets, removes, then re-sets
2. The ID sets, removes, spends extra time to load, does not load ID

**Comment by johnclary** [comment]
@ChrispinP i tweaked the code so that the ID always definitely gets set. That should fix problem #2 ☝️ .

Problem #1 - i believe this is happening because there is a delay when Knack loads the "Reg to Retire (& Replace"). When that value changes, the matching reg ID is going to re-set. I don't have an easy way to fix this without really rolling up my sleeves.

**Comment by johnclary** [comment]
@ChrispinP how's this looking for you?

**Comment by ChrispinP** [comment]
So I'm still running into both of the same issues. On first load it spins for a few seconds and works perfectly. Its whenever you reopen the same button to do 2+ retires for example, that these 2 issues occur.

Users will be drafting multiple regulations so its very likely this interaction will occur for them and will be confused if the ID does not populate like on the first press.

**Comment by dianamartin** [comment]
@johnclary Chrispin is still saying issues persist. See his comment above. Could you take another look at this please, we have a Sprint Review with users this Friday, 10/21.

**Comment by ChrispinP** [comment]
@johnclary Issue is still occurring for me 😥
[Testing Video](https://user-images.githubusercontent.com/67915167/198692091-7dff43d9-1728-4515-98eb-979356ce3316.mp4)

**Comment by johnclary** [comment]
I added a click handler to close the setter loop on modal close. Chrispin reports that this is working better now 😅
