### ISSUE TITLE
Locations Update from Data Tracker

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#1008]
- [ ] Check how often locations - [Signalized Intersections](https://atd.knack.com/amd#home/signals/) and [ School Zone Beacons](https://atd.knack.com/amd#home/school-zone-beacons/) from Data Tracker get updated. 
- [ ] Build a pipeline to update the object in the Knack VZA app.

**Comment by amenity** [comment]
No longer applicable, see #1260.
