### ISSUE TITLE
URGENT: Data Tracker Extremely Slow

### ISSUE THREAD

**Issue by lanceballard** [cityofaustin/atd-data-tech#10083]
**Describe the bug**
Knack does not appear to be loading MMC Issues or MMC Issue details very well or at all. Happening to all of our MMC users across multiple machines, locations and browsers

**URL**
https://atd.knack.com/amd#mmc/

**What steps can we follow to reproduce the bug you are seeing?**
Loading MMC Issues or MMC Issues details isn't working at all really. Sometimes intermittently works but seems very broken

**Screenshots**

**Device**
Desktop

**Browser**
Chrome and Edge

**How would you rate the impact of this issue?**
- [X] Severe — cannot perform work, no workaround

**Additional context**
If i'm not here, coordinate with Kenny Moses & Chris Sherrick

**Comment by dianamartin** [comment]
Dup of #100084
