### ISSUE TITLE
Bus Stop Tool Meeting w/ Nelson Nygaard prep

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10094]
**Via Caitlin D**

Here’s information that I know they’ll be looking for from you/Frank based on what data feeds the [bus stop tool](https://capmetro.atxvisionzero.xyz/) and past conversations I’ve had with them:

- [ ] Activity Generator shapefiles/Geodatabase
- [ ] Activity Generator Auxiliary Data
- [ ] Land Use Data
- [ ] Crash data
- [ ] Stop pattern layers and correlation table that provides stop sequences (I will request this from CapMetro)
- [x] Traffic Signal location shapefile
- [ ] Average daily ridership (I will request this from CapMetro)
 
If we can provide that information ahead of the meeting, perhaps we can focus that time on their follow up questions about the methodology used for developing the tool.

**Comment by patrickm02L** [comment]
@andrewshensky the items in the list above may be related to GIS files we'll need for the Bus Stop app I was telling you about earlier today. No action is needed at this time, just wanted to put this on your radar.

**Comment by patrickm02L** [comment]
Caitlin provided the Traffic Signal Shapefile: https://data.austintexas.gov/dataset/Traffic-Signals-and-Pedestrian-Signals/p53x-x73x

**Comment by frankhereford** [comment]
In terms of the data used in the original incantation of this work, a zip file containing said data and the various scripts was distributed to participants in the "Austin TEP bus stop scoring update" meeting today.

**Comment by patrickm02L** [comment]
As follow-up, Caitlin D. was going to follow up with Joel M. on the Vision Zero team to see if she could get additional ped data and then have Frank extract the proper data that was needed - if that tasks comes up we'll create another issue to capture the work.
