### ISSUE TITLE
V7 Permissions - Print Folder Reports - Darren & Blake

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10091]
### Per Darren & Blake, they are unable to generate folder reports for Traffic Control Inspections (50516, 50568, 50514, 50563). 
_Darren sent this screenshot:_

![image](https://user-images.githubusercontent.com/49930868/186202505-c3e2aeeb-d981-4b99-87f1-23361dbbbf1b.png)

**Comment by TracyLinder** [comment]
I was able to generate all folder reports & emailed them to Darren. We still need to update his permissions or figure out why he's getting this error.

**Comment by TracyLinder** [comment]
Nate is working w/ Anu from CTM on this. Folder report permissions are managed differently, and we need to learn the new way.

**Comment by Nadin-Nader** [comment]
Blake informed me that he is now good to go and is able to access the reports. 
Waiting on Darren's update

**Comment by Nadin-Nader** [comment]
Closing as i have not heard of any issues from Darren
