### ISSUE TITLE
IT Support: User LaTonya A. (ROW) can't access HR TLC Form

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10099]
LaTonya A. 
ROW

Created in ServiceNow - `INC0222565`
Let Diana know how it's resolved and will close it for you. 

Details
>Telework form is on ATD.knack.com
It is a ATD HR page.
User is getting that they don't have access to it.
User doesn't have the access to approve employees Telework form.

**Comment by KaroEngstrom** [comment]
W 8/24/22 
- chatted with the use and they're not having an issue logging in, only not having the rights to approve telework requests 
- checking with Diana on this

**Comment by dianamartin** [comment]
Have updated ServiceNow with resolution code, notes and updated status to "Resolved".
