### ISSUE TITLE
Duplicative AW Reviews on UC Folder (PROD Deployed)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10100]
### "The UC folders cleared off AW reviews coming back to the tasklist and have multiple duplicate AW Reviews inside the folder."
- Submitted by Rashmi w/ AW
- **INC0222275**

**Notes:**
- System is inserting a comment doc for each review, so the comment docs are duplicating. 

----
Q: Are any other folder processes duplicating?
Q: Does the process clear from the task list after it closes?
Q: Need example folders & processes. 
Q: Need user names to work with. 

----
**Screenshots from SN ticket:**
![UC 1](https://user-images.githubusercontent.com/49930868/186462753-40c1ea63-3f34-4e29-8cf6-cbfb91553b90.png)

![UC](https://user-images.githubusercontent.com/49930868/186462777-9174b7a5-24ad-440c-acbe-8ae31e0e9366.PNG)

**Comment by TracyLinder** [comment]
@Nadin-Nader this is ready to be assigned to a DEV for debugging. Thank you.

**Comment by TracyLinder** [comment]
### Answers from Rashmi

Q: Does the process clear from the task list after it closes?
- Ans : Yes , but its creating confusion among the reviewers as in to process which line item, to add to the confusion there are multiple documents added to generate

Q: Need example folders & processes.

- Folder Number : 12890561 Process :AW Infrastructure Management (51406)
- Folder Number :12996754Process :AW Infrastructure Management (51406)

 
Q: Need user names to work with.
- Work with Rashmi directly



----
FYI @SubhaShroff

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  I have been debugging and didn't find any clue in the PROD code. And compared the code on TEST and PROD all in sync. TEST doesn't have any such issue, but it was exhibiting this strange behavior of adding the reviews three times each only on PROD. And also I noticed, it was not happening with external review processes.

But today, I rechecked the latest UC folders on PROD that are 'In Review' status (RSNs: 12997924,  12997926). I noticed these permits were added with review processes on 25th or 26th. And I see there are no duplicate processes in these. I am wondering if the extra processes were deleted or if someone fixed the issue.

However, if the issue still persists, I would like to get on a call with user and record the series of actions. Probably that would help. 
Thanks.

**Comment by Nadin-Nader** [comment]
Spoke to Jaclyn and Subha. Jaclyn is ok with going forward with the changes.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0245356 - DEV deployment request is submitted.

**Comment by SubhaShroff** [comment]
@Nadin-Nader This is tested in DEV and looks good. Please let me know if we can move it to TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0245945 is submitted for TEST deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader The ticket is deployed in TEST and it looks good to me after test. Ready for UAT.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder 
After UAT today(9/12/2022) with Jaclyn/Nadin, The following change is approved for PROD deployment.
- Close the Initial Distribution process with Complete attempt added (the fix that stops duplicate review processes added).

Along with the above change Jaclyn asked to close the Permit Completeness Check process also, with any attempt added to it. I will be working on that and update.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SandBox pull request is created for the merge for the code change on Permit Completeness Check process. - [b65d8048c76d](http://coaamandadevops02.austintexas.gov/R5:b65d8048c76d1d41c8d631e04cb032fa27413d27)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0248573 is submitted for DEV deployment request after SB merge is done.

**Comment by SubhaShroff** [comment]
@Nadin-Nader I am not able to test this ticket on DEV as my login account has limited privileges. So, as you suggested in today's stand up, I raised a TEST promotion request - SCTASK0249286.

**Comment by Nadin-Nader** [comment]
Asked Jaclyn to UAT on TEST. Waiting on Results

**Comment by Nadin-Nader** [comment]
@SubhaShroff Promotion to PROD has been approved by Jaclyn. Please send the request to CTM DevOps when ready

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This ticket is now on PROD.

**Comment by SubhaShroff** [comment]
### Status:
Its deployed in PROD 6 days ago.

**Comment by Nadin-Nader** [comment]
Thus has been fixed and UATd Closing
