### ISSUE TITLE
Hire Design Researcher

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1010]
**Primary role**
- Perform preliminary user research and requirements gathering for new DTS products and features
- Conduct usability testing to inform iterative product development
- Collect and analyze qualitative and quantitative user data to identify pain points and areas for improvement in existing applications
- [Heuristic evaluations](https://www.usability.gov/how-to-and-tools/methods/heuristic-evaluation.html) of in-house, off-the-shelf, and vendor-built software usability

**Nice to have skills**
- Information architecture
- Design thinking and facilitation
- User interface design
- Content strategy

**Specific projects/products**
- Evaluation of the out-of-the-box Knack user interface and DTS' Knack design patterns to recommend areas of improvement, design and document best-practices for Knack UI designs, collaborate with app builders and developers to identify and prioritize opportunities to enhance usability with custom code
- ROWMAN Ph 4, specifically the planned 'My Closures' portal feature that permit holders will utilize to interact with their road closure data.

See: [Past DTS job descriptions](https://drive.google.com/drive/folders/1dObYljT2cJF6kRnqoFTMe9MzpeVIZadE)

**Comment by amenity** [comment]
@TracyLinder @dianamartin @JaceDeloney @mateoclarke @johnclary - would love your eyes on and edits to this quick stab at describing the role and potential projects/products for a UX Researcher.

**Comment by amenity** [comment]
Feedback from Céline:

**Comment by TracyLinder** [comment]
@amenity what is our deadline for providing feedback?
