### ISSUE TITLE
[TDS Portal / TDR] - Allow distribution to multiple members of a vision team

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10109]
### Project Managers need to be able to assign reviews to multiple reviewers in the same vision team. Currently the system only allows one assigned reviewer per Vision Team. 
- Amber is doing a work around for this that eats up time. 

- Requested by TDS during backlog prioritization (Curtis, Amber)

**Comment by TracyLinder** [comment]
**Notes:**
Select vision team
display rule to show 1st & 2nd reviewer
Select reviewers
System inserts that # of records for the vision team.

@ChrispinP will build in test & then we'll show stakeholders.

**Comment by ChrispinP** [comment]
**Review Comment Object updated with new or updated fields:**
![image](https://user-images.githubusercontent.com/67915167/191095922-c022ae40-c5cb-44d8-b16d-6006565cf70b.png)

**Assign Vision Team Reviewers form updated for both Leads & Reviewers to assign up to 3 reviewers:** Only when a Primary Vision Team Reviewer is added or changed is an email sent.
![image](https://user-images.githubusercontent.com/67915167/191101185-09809ba6-1be6-4641-a543-bd1c56a97186.png)


**Boolean fields used as a way to keep track of when someone is assigned. Currently Assigned To and Reassignment are updated on each form submit.**
![image](https://user-images.githubusercontent.com/67915167/191096994-8c15de02-35ef-43cc-b83f-2962ab61902d.png)

The old way of building Review Dashboards doesn't work well with the new setup of multiple reviewers. Repurposed the Vision Team Dashboard as the landing page for Reviewers to view all Review Comments by status and navigate to either their Task Board or Advanced Search.
![image](https://user-images.githubusercontent.com/67915167/191097652-b5a8d7ff-e98b-4d4a-a461-7980bd130d45.png)

**The Currently Assigned To and the Secondary/Tertiary Reviewers added to table. Review Comment Details and Vision Team Review Page updated with the new fields as well.**
![image](https://user-images.githubusercontent.com/67915167/191098540-feeb7d7d-e1f5-41a2-be9e-e4f5bd618b1d.png)

**New Task Board:**
![image](https://user-images.githubusercontent.com/67915167/191098778-d06b66f0-6bf4-415b-97ef-a85fda04325e.png)

**Tasks are broken up into 3 sections, those that are Assigned (Pending Review), those that are Active (In Draft), and those that are Completed (Completed, No Response, or Cancelled).**
![image](https://user-images.githubusercontent.com/67915167/191099132-d57d02de-563f-45ff-9e89-6b38981c90b7.png)

Each Review Comment records allows multiple actions:
1. Navigate to the Review Page
2. Navigate to the Review Comment Details Page
3. Open a Quick View of the Review Comment without navigating away
4. Navigate to the TDR Case Details Page
5. Navigate to the Review Cycle Page
6. Re-Assign to the next Vision Team Reviewer
![image](https://user-images.githubusercontent.com/67915167/191099852-138b3c6f-4f76-41ae-99c2-e09f57fc04a9.png)

**The Quick View modal page:**
![image](https://user-images.githubusercontent.com/67915167/191100666-7e9c710a-d8ed-483e-a1d6-903c939b6aec.png)

**The Re-Assign is a trigger button that selects the next Reviewer and sets them as the Currently Assigned To. This function is repeatable in a loop. Once a Review is Started, this button will appear. Once a Review is Completed, this button will disappear.**
![image](https://user-images.githubusercontent.com/67915167/191100356-bb76cd19-2096-4f98-94f5-afd0ececcbac.png)

Ready to Review @TracyLinder

**Comment by TracyLinder** [comment]
This is in test & ready for UAT w/ business partners.

**Comment by TracyLinder** [comment]
### Next Step:
- Apps builder huddle to discuss methodology. 10/13/22

**Comment by TracyLinder** [comment]
### Huddle Notes:

- There is already a feature for this. The button is 'Add record'. 
- [ ] Tracy will meet w/ Amber to show her the feature and ask if it meets the need.

**Comment by TracyLinder** [comment]
### Outcome

- I showed amber the Add Record feature and it meets the request need. I'm closing this.
