### ISSUE TITLE
Bug: SIF Free-Form Unique ID is not Unique

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10103]
### On the free-form tab, the Unique ID field is duplicating; it's not unique.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP of #10103 submitted. Kindly approve and create task id for the same. 

Commit ID: [f38b1c907343](http://coaamandadevops02.austintexas.gov/R5:f38b1c90734316b6e4aa6ef11f14a747aeb950a7)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST and found an error; fixed the same in Localhost and submitted DEV/TEST dp for the same. Kindly approve and create task id for the same. 

Commit ID: [b5fee6575537](http://coaamandadevops02.austintexas.gov/R5:b5fee65755374e9a534ec4637db82e3c0dda5077)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to **_ Sandbox, DEV and TEST_** under TASK **SCTASK0246636**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV/TEST DP submitted again to make unique id column as Read Only. Please approve and create task id for me. 
Commit ID: [fa55f67e9bd0](http://coaamandadevops02.austintexas.gov/R5:fa55f67e9bd00450624fe7a5018fcb97282517d4)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team for deployment to DEV and TEST under **SCTASK0247747**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV/TEST DP submitted again to make missed json file changes. Kindly approve and create task id for me.
Commit ID: [57c7f79d5fb0](http://coaamandadevops02.austintexas.gov/R5:57c7f79d5fb0d1f1d571a79592dfe6913101d157)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this new commit to the DevOps CM Team to be deployed to DEV and TEST under **SCTASK0248300**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this new commit to the DevOps CM Team to be deployed to **PROD** under **_SCTASK0248923_**
