### ISSUE TITLE
Populate `austin_full_purpose ` & `location_id ` values for all existing EMS/AFD incidents and all incoming incidents for both tables going forward

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#10112]
- [x] Review the process for how `austin_full_purpose` values get populated in the Crash table. I assume we use a SQL function like `find_crash_in_jurisdiction`, but need a refresher. Implement in a similar way to backfill data and ensure new data going forward get processed.
- [x] Same as above but for `location_id`. The SQL function of interest may be `atd_txdot_locations_updates_crash_locations`
- [x] Do this as a backfill with existing data
- [x] And as part of the ongoing ETL process

Continues from https://github.com/cityofaustin/atd-data-tech/issues/9075

**Comment by mateoclarke** [comment]
@frankhereford suggested doing this as a View layer where these two fields are computed with PostGIS function

**Comment by frankhereford** [comment]
Included in recent merge of [PR 1095](https://github.com/cityofaustin/atd-vz-data/pull/1095).
