### ISSUE TITLE
Spike: SD 2023 reporting for visual tracking status logic

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10121]
Reach out Nicole C. to talk about the limitation or opportunities for what the SD 2023 Dashboard can handle. 

[SD 2023 Dashboard](https://data.austintexas.gov/stories/s/Mobility-Dashboard/gzb5-ykym/)

Cap at 4-5 hrs for the spike scoping/research.

**Comment by Charlie-Henry** [comment]
I looked into Socrata's measure features to see what options we have to customize these little widgets.

1. We can add multiple targets, so here I've added one at 27,000 and one at 30,000, the "status" (on-track, off-track) becomes manual-only if you have more than one.
<img width="1050" alt="Screen Shot 2022-08-30 at 11 46 19 AM" src="https://user-images.githubusercontent.com/30810522/187493755-c65bcd1b-51ba-4872-8850-246815a57830.png">

2. We can set a date-aware goal where here I've set goals for three weeks. You can then use the "status" logic to show if it is on-track or off-track or near the goal.
<img width="1027" alt="Screen Shot 2022-08-30 at 11 50 50 AM" src="https://user-images.githubusercontent.com/30810522/187494579-8e63b1a8-8e7f-4d9c-9055-1780e18c1b79.png">

3. Looks like the only options to show up for status are:
<img width="465" alt="Screen Shot 2022-08-30 at 11 52 25 AM" src="https://user-images.githubusercontent.com/30810522/187494905-d320fb97-a954-4aba-be7b-4f5adc890b09.png">

**Comment by patrickm02L** [comment]
Inconsistency in timeframes for current metrics and long-term metrics. 
![Screen Shot 2022-09-08 at 3.33.47 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/c6caa7d3-e4e6-44df-bb44-f249d4dfa848
)

**Comment by patrickm02L** [comment]
Message Nicole C. in Amy S. to figure out what the logic.

**Comment by Charlie-Henry** [comment]
I think this can be closed out? We've completed the spike to see what is possible with the tools socrata provides.

**Comment by patrickm02L** [comment]
It's not possible get the data from Socrata however we are able to grab smaller datasets from the Strategic Measure cards ([example](https://data.austintexas.gov/stories/s/M-A-2-a-Transit-Travel-Time-Reliability-percent-ch/ktzy-fxx3/). We still haven't decided what from the cards we'll want to include in the Executive Dashboard. Once we decide we create another Issue to pull in those datasets.
