### ISSUE TITLE
Remove actions and related CI scripts for the deprecated Heroku-based test platform

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10128]
Moped has various integrations with Heroku which were used to run the old Moped test system. With the changes at Heroku's service with regards to postgres, they are no longer a viable provider of that capability. This issue is to track the work and conversation around the removal of scripts from the Moped codebase which no longer function due to these changes.

**Comment by frankhereford** [comment]
I was faced with updating a version number in a file that would be deleted in this issue so I rolled this change into [Moped PR 781](https://github.com/cityofaustin/atd-moped/pull/781).

**Comment by johnclary** [comment]
@frankhereford closing this one - thank you!
