### ISSUE TITLE
Replace lambda function to make sure AFP is flagged correctly

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10126]
This Issue is meant to act as a place holder to approach to resolving the AFP (`austin_full_purpose`) mis-flagging. We've resolved the current Issues with #9802 and will continue to check it to see if mis-flagging occurs again. If problems persist then we'll pursue action around fixing the lambda function.

@chiaberry will monitor any mis-flagging events in the meantime.

**Comment by patrickm02L** [comment]
> I would be eager to end up in a state where we pull this functionality _out of_ the λ function.
> 
> We ultimately rely on the database to use PostGIS functions to decide what the AFP state is; this could become either a view to dynamically calculate it on access or a trigger to set-it as an on-disk value.

**Comment by frankhereford** [comment]
I removed myself as an assignee on this because that felt like the right thing to do. I'm ultra-happy to support in anyway that I can, or get reassigned even, though!

**Comment by patrickm02L** [comment]
In Refinement 6/21/23
There needs to be another Issue to backfill all the AFP class for the crashes.
