### ISSUE TITLE
Add tag usage for all AWS resources created as part of Moped test deployments

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10132]
While the test infrastructure will be automatically cleaned up after usage, the resources deployed should be properly tagged as part of a test deployment. The tags should include a generic tag that indicates that its part of any test deployment, and another tag that is unique to each deployment. These tags are invaluable in the case that the resources need to be evaluated for cost and / or removed by hand.

**Comment by johnclary** [comment]
We may want to do this alongside https://github.com/cityofaustin/atd-data-tech/issues/9993

**Comment by johnclary** [comment]
Closing because we have abandoned the prefect-based test deployments.
