### ISSUE TITLE
[BUG] Unable to edit status update if created from Dashboard view

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10154]
**Describe the bug**
1. Login to moped staging
2. Follow a project, then navigate to the **Dashboard** tab
3. From the "Following" tab, click into the "Status update" column and add a new status update to a project
4. Navigate to that page's project summary
5. From the project summary, click on the project's status note to edit
6. The status note appears as `[object object]`

<img width="907" alt="Screen Shot 2022-08-31 at 1 45 48 PM" src="https://user-images.githubusercontent.com/14793120/187759220-b124a342-9c18-4ad0-ac7e-678659cace2b.png">

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [X] Major — can only perform work using a workaround
- [ ] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Additional context**

**Comment by chiaberry** [comment]
the reason its coming up as `[object Object]` is that if the text is added from the dashboard view, then it is rich text. We use `react-html-parser` to turn the html into a react object, so we dont see "<p>my status<p>"

question for product: 
- [ ] do we prevent users from editing their rich text statuses in the project summary tab 
- [ ] do we switch the dashboard component that adds statuses away from the quill (removing the capability of rich text)
- [ ] other?

**Comment by amenity** [comment]
Thanks, Chia! 🙏🏻

**Comment by johnclary** [comment]
Agreed—I think we should just remove the rich text functionality from the dashboard status updates.

**Comment by chiaberry** [comment]
@tillyw if you are looking for issues to work on today, it would help me if you took this one off my plate. This may end up being a biggish refactor, we can talk about it

**Comment by johnclary** [comment]
Tilly's suggestion is to implement the status add/edit modal on the project summary page. We agree! @amenity what do you think?

**Comment by amenity** [comment]
Brilliant, @tillyw! 🧠🙏
