### ISSUE TITLE
Create Ready-Only Accounts and Views for ROW Court Case Management

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10173]
**9/1/22 Darren U requested via email:** 
"Could we create accounts that will have read-only permissions? This could be provided to our admin/supervisor staff." 

**@KaroEngstrom responded via email:**
This is possible. I’ll add an issue for that as well.

---

- [x] Create Viewer account
- [x] Create Viewer views or pages, per discussion with the Apps team 

@dianamartin @ChrispinP  - do we have best practice for how to do a read-only? Different pages or more simply non-editable views?

**Comment by dianamartin** [comment]
@KaroEngstrom I think you got it, you could do a new user role and then just ensure "Non-Editable" table views. You can also clarify with the stakeholder what/who needs access to what so that you can determine your course of action.

**Comment by KaroEngstrom** [comment]
# F 9/30/22 

- [x] Checked with Darren on what the read-only ROW Viewer accounts should have access to. He confirmed that these are the appropriate page where need the non-editable views: 
![image](https://user-images.githubusercontent.com/100615928/193341547-9720e63a-f822-4d61-8648-ed190540688a.png)
- [ ] Create ROW Viewer account 
- [ ] Create non-editable view on 
- [ ] - [ ] Create non-editable view on 
- [ ] - [ ] Create non-editable view on 
- [ ] - [ ] Create non-editable view on

**Comment by TracyLinder** [comment]
This is complete.
