### ISSUE TITLE
Clean Up Invoice Details Page

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1017]
Clean up/simplify Invoice Details page based on discussion with AP.

- [x] REMOVE `Amount Due` field (Keep `Amount Paid`)
- [x] Remove `Received Shipment`
- [x] REMOVE `Items` table and `Invoice Items` table (AP and Shipping/Receiving)
- [x] REMOVE `Shipping Receipts` table
- [x] REMOVE add `Items` form

**Comment by johnclary** [comment]
@dianamartin I think we can remove the shipping/receiving info from the invoice details completely, and let warehouse staff just use the attachment form on the purchase request details. They only need to view invoices for reference.

**Comment by dianamartin** [comment]
Invoice Details page now just has the details information, comments table and Items
