### ISSUE TITLE
V7 BUG: DS Activate Upon Payment is not functioning properly (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#10187]
### Folder Issue-By needs to auto-populate with the correct user name when the system issues the folder. 
- Issued by should be the user name who saved the last process attempt on DS Permitting Review 50730. 

----

When the activate upon payment function is yes for DS permits, once they make a payment and the permit gets issued. 
AMANDA reflects that the Portal issued the permit. For AMANDA 6, we had worked DS permits that didn't have a web application process (like the ones pending and attached to BPs) that it would reflect the person who created the invoice. 
However since it doesn't work correctly now AMANDA V7.. to better reflect who issued it, I believe using the person who completed the DS Permitting Review process would work better.

![MicrosoftTeams-image (17).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/81257ba0-46a6-466b-815c-b69d2afe34eb)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This requirement is it restricted to AUP? or any Issue triggered in DS should update the ISSUED USER name with the one who added the attempt to DS Permitting Review 50730 process?

**Comment by TracyLinder** [comment]
> This requirement is it restricted to AUP? or any Issue triggered in DS should update the ISSUED USER name with the one who added the attempt to DS Permitting Review 50730 process?

@SubhaShroff the requirement is only for AUP.

**Comment by SubhaShroff** [comment]
Thank you @TracyLinder. The fix is done and after unit testing submitted SB merge pull request and DEV deployment request - SCTASK0249033.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I am not able to test this ticket on DEV as my login account has limited privileges. So, as you suggested in today's stand up, I raised a TEST promotion request - SCTASK0249274 for this ticket.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The changes are in TEST. As I communicated to you, My login account doesn't have the add attempt privileges.  We need help in UATing this. Thanks.

**Comment by Nadin-Nader** [comment]
Asked Kim to UAT on TEST. Waiting on Response

**Comment by TracyLinder** [comment]
### UAT Passed
- Test RSN 12809775

@SubhaShroff please promote to PROD

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  SCTASK0250763 is PROD deployment request is submitted.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  PROD deployment is done. We can ask the users to UAT on PROD.

**Comment by Nadin-Nader** [comment]
Asked Paloma and Kim to UAT on PROD

**Comment by TracyLinder** [comment]
We don't think this has been tested yet. Keep it open.

**Comment by Nadin-Nader** [comment]
DS is working with no issues but the EX may still be acting wonky #8927. Closing this one
