### ISSUE TITLE
[Purchase Request Details] Add Support for Attachment Types 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1018]
On the purchase request details, add a multiple choice selection for `Attachment Type`:
- Quote
- Purchase Order
- Packing Slip
- Miscellaneous

Need to add this field to the Add Attachment form and display it on the attachments table.

**Comment by dianamartin** [comment]
- [x] `Attachment Type` field has been added to object table
- [x] `Attachment Type` field has been added to `Add Attachment` form
- [x] `Attachment Type` field has been added to `Attachment` table on Purchase Request details page
