### ISSUE TITLE
Create reporting page 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10196]
Build out a reporting page based on the table that Kirk S. provided. We'll reference what we built for MetroBike tracking, and think of other views to include. 

![Screen Shot 2022-09-07 at 9.37.17 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/b0428ade-e316-4fdb-a29d-0fa1dbd07499)

**Comment by KaroEngstrom** [comment]
M 9/12/22 

@dianamartin We need to think about how to do reporting for every project from proposal to approved together, if Kirk wants to see Active | Complete | Declined breakdown (following an EOI all the way through). We have proposal in its own object.

**Comment by dianamartin** [comment]
@KaroEngstrom if we combined it into one object, that would be huge. We can just use a text formula to bring in the EOI status, could we not?

**Comment by KaroEngstrom** [comment]
@dianamartin we can do that once there's a BCA, which I think we shouldn't have until the EOI has Exec Approval. This ties into my questions in #9659 about the EOI Exec Review. It was set to always create a BCA and move to Vetting, regardless of Executive Decision. I made that conditional on Approval. I can think of two solutions:

1. Create a Pending or Cancelled status for BCA and automatically create a BCA for any EOI that makes it through Exec Review, regardless of Exec decision (Pending BCA for anything sent back; Cancelled BCA status for declined items). That way we could report on the Business Case Analysis object and catch almost everything (not  EOIs that are in initial panel review and not yet decided on by Exec). 

2. Automatically create a connected BCA when an EOI comes in, and put it in Pending status. Currently the BCA is created upon EOI Exec Approval. 
Then upon EOI Executive Review, we can push

| EOI Exec Decision        | To BCA Status           | 
| ------------- |:-------------:| 
| Move Forward to Vetting     | Vetting | 
| Return to proposer - additional information     | Pending      |   
| Declined | Cancelled      |   
| Other | Pending      |  

I'm thinking Option 2.

**Comment by KaroEngstrom** [comment]
## M 9/19/22 

Reviewed current reporting visuals: 

![image](https://user-images.githubusercontent.com/100615928/191073001-968b05b9-0fc5-48f4-b9e2-469dd51ea134.png)

![image](https://user-images.githubusercontent.com/100615928/191073025-06e170fc-40a8-4d86-b157-a5ef8049ab83.png)

**Task before meeting with stakeholders:**
- [ ] Add an Advanced Search Table view to allows admins to filter the data per their reporting needs

**Comment by KaroEngstrom** [comment]
Reviewed with stakeholders 9/22/22, all approved. 
Added print option in this application to allow easier printing/export of the data visualizations.
