### ISSUE TITLE
Project: Financial Information Tracking Portal

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10198]
An internal Knack application for tracking financial Task Orders (TKs) and Service Requests (SRs).

### Task Orders #10111

The current process for tracking TKs using an Excel workbook is inefficient and ineffective. 

TKs (Task Orders) are being tracked in an Excel workbook that is stored on a shared drive. However, this process lacks real-time information and requires significant upkeep, making it difficult for staff to access. As a result, the majority of the staff do not have access to this information, and it remains inaccessible to them. Given that TKs are specific numbers, PMs and employees who use them on timesheets should have access to a resource that allows them to validate the TK number they need to use.

### Service Requests #10062

The process begins with an ATD user writing an email to request something. The user provides detailed information in the email and sends it to the relevant recipient. The recipient then puts the email into a mailbox folder.

Since the request has standards, the user requests a form to be used instead of the email. A note is then written, indicating that the request has been completed, and the information is provided to the requester.

Dan marks the email as unread after he approves it, and then approves it. The email is returned to the mailbox folder, indicating that the request has been approved and completed. 

Overall, the process involves email communication, using a mailbox folder to organize requests, requesting a form for standard requests, and approving and returning emails to the mailbox folder once completed.

## Scope & Deliverables

Application for the specific use of the Finance team which combines the TK and SR processess.

## Desired Outcomes

Success would look like a web-based solution that allowed users to search for and see all TKs and SRs used by ATD, the name, number, balance, responsible PM or manager, division name, last use. 

It would also be beneficial to be able to drill down into charges against a particular TK but not a must as eCAPRIS does provide that information if needed.

## Timebox

September 2022-May 2023

## Concepts & References
Task Orders [Miroboard](https://miro.com/app/board/uXjVPZPDoQ8=/)
Service Requests [Miroboard](https://miro.com/app/board/uXjVPaEmIPc=/)

---
![TK-SR prototype platform.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/88f79365-b171-4721-a27d-bef9e1ce5868)

**Comment by ChristinaTremel** [comment]
## Status Update - 8/21/2023

- **Service Requests Process Improvement**
    - Small updates were made to the Service Requests and we were ready to start usability testing with users.
    - Finance helped identify Ronnie, Shelby, Max, and Shelby as users for Usability Testing because they submit Service Requests to Finance often.
    - Met with Testers on 6/21 and walked them through the process for submitting Service Requests. Determined that we would having the testing period go from 6/21-7/14. Set up a check in meeting for 7/6.
    - The week of 7/4 the budget freeze was lifted so we had to extend the testing period through the end of July. Scheduled meetings for 7/25 and 8/1 to discuss feedback from the Usability Testing. Collected a list of Service Request functions that Users and the Finance Division would like to see updated to improve the process of submitting Finance Service Requests.
    - The sprint of 8/23/23-9/5/23 we plan to work on some of the updates requested in the feedback meetings.
    - Will schedule the next meeting with Finance in early September to discuss updated schedule for rolling out the Service Requests.
    
- **Other Enhancements**
    - DTS has been working with eCapri to create a SQL view of `Subprojects` so we can create an ETL script and pull subprojects from data warehouse to the Finance Knack App.
    - Bruce from eCapri has created this view for us and has given us a view of subprojects managed by Transportation and Public Works (TPW), legacy Austin Transportation (ATD), and legacy Public Works (PWD). Dev team has run the integration in the test Knack App.
    - Next steps will be to implement this integration in the prod Finance and Purchasing Knack App

**Comment by ChristinaTremel** [comment]
## Status Update - 9/29
- On 9/20 DTS met with Finance and were able to show them all the updates made to the Finance Service Requests based on the usability testing feedback. We determined at that meeting that the system is ready to be rolled out.

### Finance Service Requests Roll Out Plan:
   - **October:** Sharon and Christina will work on updating help guides to reflect all the changes made on the Finance Service Requests
   - **Beginning of November**: Finance will send communication to TPW that the Service Request process will be changing.
   - **Mid/end of November:** Finance will schedule Lunch & Learns with TPW staff to walk through how to submit service requests.
   - **December 1st:** DTS & finance will roll out the Finance Service Requests and TPW staff will be asked to submit SRs in parallel to their current process of sending requests via email.
   - **January 1st:** New process in the Finance & Purchasing Knack app will be fully implemented.

**Comment by stephaniemoorer** [comment]
Status Update

Improving Task Order Tracking and creating a streamlined Service Requests process using the Finance & Purchasing Knack application were the key goals of this project. The new Service Request application provides TPW staff the ability to submit New Service Requests, track the statuses of requests submitted, and specify the jobs they are requesting from Finance. Other capabilities allow the TPW Finance team to Manage Service Requests, assign requests to Finance staff, and update information that can be seen directly by TPW staff in the Finance & Purchasing Knack application and through automated emails.
The Task Order Tracking component of the project allows users to search all Task Orders used by TPW. Information provided includes task order name, type, balance and status. The Go Live for this project was July 2024.

**Comment by stephaniemoorer** [comment]
This is complete - Closing
