### ISSUE TITLE
Reconfigure EOI system

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10194]
Allow Committee reviewer to be added to the EOI table and emails to be sent to them from this table. Email will have a link to the EOI details for recipient to submit review.

![Screen Shot 2022-09-07 at 10.14.56 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/a9393a32-ad47-4e60-845f-b1d060809bc3)

Need to check with Kat to find out what the email review criteria is. Find out if we need to create a time limit that's hardwired.

**Comment by KaroEngstrom** [comment]
W 9/7/22

Checked in about the email with Kat: 
- Verbiage of the email can be simple and direct, along the lines of: "We have received a new Expression of Interest form form for your review. Please follow the link below to review and provide feedback through an individual evaluation form. Please submit your evaluation by the next Pilot Team meeting."

**Comment by KaroEngstrom** [comment]
## M 9/19/22 

Reviewed items above. 

**Tasks before meeting with stakeholders:** 
- [ ] Add the `p3_expression_of_interest` object a multichoice field **Panel Reviewers** that allows multiple selections
- [ ] Configure Email Panel form to send to the list of Accounts with Panel Reviewer status (see Parking Enforcement as a model)
- [ ] Test

**Comment by KaroEngstrom** [comment]
Reviewed with stakeholders 9/22/22, all approved
