### ISSUE TITLE
Builder Huddle - Finance Task Order

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10199]
For upcoming meeting based on #10111. Date TBD.

[Project Intake Doc](https://docs.google.com/document/d/1AcjxHv6XCEutSAIzNebnxNR9EL8CORiHrVfNlQuChII/edit#heading=h.f4j2i9aovme)
[Project Evaluation](https://atd.knack.com/dts#project-evaluation/)

**Comment by patrickm02L** [comment]
Scheduled for Tuesday 9/20/22.

**Comment by dianamartin** [comment]
# 9/20

Almost impossible for regular staff to get access to task orders
- need to have AIMs access

## Pain Points
Task orders - associated with labor
code their time to a task order
task orders have budget (not to exceed amount)
Not monitoring that balance, go into a suspend bc there's not any $ 
can't charge to it
- Administrative burden 

Takes Denise 2 days to fix problems for each payroll

John was pulling data for AMD data tracker
- working with Eva. S (Finance IT group, w/ Mark C.)

Parking Inventory
Microstrategies -->

**Comment by dianamartin** [comment]
Synced with Patrick & Chia (Charlie out for HBD)

# Notes 
We talked about how the Service Request and Task Orders are related and created a new [workflow ](https://miro.com/app/board/uXjVPZPDoQ8=/)to show it. 

So I got a hold of Erin W. from Finance and she pulled up a task order in AIMS and said they have a field called "Estimator Name" and she was explaining what the definition of it was. I saw on my notes with Dan, Sharon that is what he called it. That's the field that Dan was referring to, apparently equivalent to "Requester Name". That is being entered into AIMS, so looks like we just need to request the data warehouse view to be modified to capture that.

**Comment by chiaberry** [comment]
@dianamartin @patrickm02L Has anyone requested the data warehouse view to be updated?

**Comment by dianamartin** [comment]
@chiaberry I have not, I didn't know who should request it or who to send the request to. I think we can ask @johnclary who his contact is. Maybe Mark or Eva?

**Comment by patrickm02L** [comment]
In planning Tracy let us know it's Eva S. We can reach out to her.

**Comment by patrickm02L** [comment]
> in the past I have worked with Bruce N. but he has told me to use the ecapris help email address for these requests, and they will likely be routed to him. i can share that email in slack.

@johnclary can you share that email with @dianamartin?

**Comment by johnclary** [comment]
https://austininnovation.slack.com/archives/C026ZRP1TH8/p1666194504939339

**Comment by dianamartin** [comment]
Emailed eCapri email 11/2 
- main resource acct, Eva S. 
- Patrick, Chia, Charlie

>Hi, 
I’m requesting the addition of a new field the existing view ATD Data and Technology Services has access to. Our stakeholders would like to see “Task Order Estimator” added as a new field to the SQL view for task orders “DEPT_2400_TK_VW”. (Please do not modify the view name as we rely on this data source to feed a critical dashboard). 

>Let me know if this is the appropriate channel to make this request.

**Comment by dianamartin** [comment]
@Charlie-Henry @chiaberry are we able to confirm that we can see that new field in the SQL query view?

**Comment by Charlie-Henry** [comment]
I confirm I see the `TASK_ORDER_ESTIMATOR` field now!

**Comment by patrickm02L** [comment]
Connected to #10111
