### ISSUE TITLE
Create account management for SMO

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10197]
Create a new dropdown on the home menu for SMO called admin for account management. Allowable only be Program Managers. 

Once this is created make Kirk and Kat admins.

![Screen Shot 2022-09-07 at 10.30.10 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/aae5c163-4c75-4f34-a8ec-3932ee8989fc)

Models:

- Shared Mobility 
- Banners

**Comment by KaroEngstrom** [comment]
### T 9/13/22 

- Added Accounts page and dropdownm with Add Account + edit and remove options
![image](https://user-images.githubusercontent.com/100615928/189981837-8765c3e9-4ab2-48b2-8aaf-3deb0ab6ad23.png)
- Gave Kirk and Kat (and DTS Knack Builders) access to this page

**Comment by KaroEngstrom** [comment]
- Removed the Remove option; best practice to Remove P3 credentials rather than remove entirely

**Comment by KaroEngstrom** [comment]
Reviewed with stakeholders 9/22/22, all approved
