### ISSUE TITLE
Add Edit button for BCA Status & Edit BCA details

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10195]
Make status editable. Users cannot edit status manually. 

Will allow them to also edit the grouping (multi-choice), sponsor (?) and SMO lead (user_name).

![Screen Shot 2022-09-07 at 10.19.57 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/dc091848-f0e4-4259-bfdf-a54dc28b6d2f)

**Comment by KaroEngstrom** [comment]
Fri 9/9/22 

- [x] Add Edit BCA Details button 
![image](https://user-images.githubusercontent.com/100615928/189449916-a317cc8a-fa8c-4763-9792-57592bd427ed.png)
- [ ] Add fields for the following (Karo checked with Kat on the field type needs): 
- Grouping (multi-choice dropdown:  Adv. Aerial Mobility; Application; Curb Management; Connected & Autonomous; Data Management; Parking Services; Sensors & Detection; Shared-Use Mobility; Smart Infrastructure; Smart O&M)
- Sponsor (short text field) 
- SMO Lead (Account connection)

**Comment by KaroEngstrom** [comment]
Reviewed with stakeholders 9/22/22, all approved
