### ISSUE TITLE
V7 BUG: Users are unable to click the Red invoice amount and it show them the fees and violations for any related folders (Waiting on CTM)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#10191]
##  Users are unable to click the red invoice amount and it show them the fees and violations for any related folders

On the Folder and People Tab, when an applicant has an Overdue Fee/Violation red pill/button, users used to be able to click on it and it would show the Overdue fees and/or any violations that user/property has on any folder in AMANDA. AMANDA is not longer showing this.

Power Users had this before the mass permissions change back to Standard but this will be needed for every Reviewer.

This is needed as the reviewers/users need to know if there are any other Overdue fees or Violations that would prevent from Issuing a permit

Example people RSN: 5402549 (User may have paid or corrected their violations)

![Red Pill example.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/bcbd86e6-bd57-47b0-927e-29a112d83621)

**Comment by TracyLinder** [comment]
Sree has been able to duplicate the issue on Local. She may have an update on Monday or Tuesday of next week.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per my analysis it is User Access Permissions issue. Would like to know the UserID's and corresponding folders (if possible) to verify the security groups and their permissions so that the commit can be submitted accordingly.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan you can look at any ROW user. MORRISKI

**Comment by Sreelatha-BlazeKannan** [comment]
@Sreelatha-BlazeKannan - Check/investigate using peoplersn 5014638 from PROD/TEST

**Comment by Nadin-Nader** [comment]
Scheduled cll with Kim and @Sreelatha-BlazeKannan for Nov 11 @2pm

**Comment by Nadin-Nader** [comment]
Jenice asked that we put in a ticket for this and she will get to it next week.
@Sreelatha-BlazeKannan  SCTASK0263473 was created for this

**Comment by Nadin-Nader** [comment]
Had a meeting with Jenice and was able to add the Invoice-Print and View permissions on the following security groups:
Cashier
Streets and Spaces (DS, EX, RW, PSM, SB)
Non Folder fees (SIF, GF)
Kim was able to test this on TEST and PROD. Closing Card
