### ISSUE TITLE
Add Support for Purchase Requests Comments

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1019]
Add a "Comments" table to purchase request details, as well as an "add comments" form. All users should be able to add comments. Should track comment author and comment date. I think it's totally fine if the comments are editable by all users. I really don't think it's worth the complexity of maintaining two tables for this.

**Comment by amenity** [comment]
They want both _invoice_ comments and _general_ comments, but these can be in the same object with a `type` field.

**Comment by dianamartin** [comment]
Created new object table `comments`

Fields: 

- Comment ID
- COMMENT
- Type
- Created Date
- Created By
- Modified Date
- Modified By
- purchase_request _connection_

- [ ] Add Form on PR details
- [ ] Add Table on PR details
- [ ] Add Form on Invoice Details
- [ ] Add Table on Invoice Details

**Comment by dianamartin** [comment]
Updated CSS, need to update code respository

**Comment by dianamartin** [comment]
### Comments on Invoice Details
![image](https://user-images.githubusercontent.com/21112975/70945834-a143c380-201b-11ea-89b1-66e9844a6793.png)

### Comments on Purchase Request details
![image](https://user-images.githubusercontent.com/21112975/70945867-b28cd000-201b-11ea-9c2e-275bffad89c5.png)

**Comment by dianamartin** [comment]
@johnclary Did we want any user to be able to make a comment regardless of PR status? Also, you mentioned you wanted the users to be able to edit their own comments. I've not allowed them to delete comments though.

**Comment by johnclary** [comment]
Looks fantastic. I think it's fine to add/edit comments after the PR is closed. As long as we're using audit fields, which you did. Knack tracks the change history behind the scenes, so we always have that history.
