### ISSUE TITLE
HR Digital SSPR Testing

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10208]
- [ ] From New SSPR/Planning/Details/COA Vision section
will the Change Status and Close SSPR buttons be there in production? (see screenshot)
>Yes, it will be there. Do we not want it to be there?

**Priorities section**
- [ ] There is a lot of space above and below the title. Can some of the space be removed? (see screenshot)
>I would have to remove the "divider" line to make the white space go away

![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/d2f31488-3455-4931-983e-7c57f096fc8e)

- [x] Each section has a line between the sections, there is no line between the Priorities and Review Competencies - but there is the priorities box so that may be enough separation??? Fine with me either way
>This is because the separation is already happening because the Priorities table separates the sections visually

**Review Competencies:**

- [x] Consider entering some of this wording under the title:

Review and discuss the following COA Competencies. Discuss the meaning of each competency and expectations for modeling its application as a City employee. Discuss how each competency impacts the employee’s responsibilities and performance. Identify areas of focus for development and include in the Employee Development Plan page.
**example:**
**PLAN MEETING: For each competency - identify the key actions and discuss your expectations. Discuss how each competency impacts the employee’s responsibilities and performance.** 
>Changed it to this:
![image](https://user-images.githubusercontent.com/21112975/188990145-9a819005-a0ac-4cfc-b6a9-7d944c4300f7.png)

- [ ] I think we discussed adding this information to the view competencies page?

![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/e2a59bc9-7785-498d-a68b-94e00a1b7fc2)

**Additional Comments:**
- [x] Consider adding this wording under the title - replace what is currently there: This is what is on the paper SSPR
> Added new language
**Supervisors and Employees may use this space for additional comments including recognition for achievements outside the employee’s regular assignments, volunteer work, etc.**
![image](https://user-images.githubusercontent.com/21112975/188990495-a1e36aa8-3f06-44d2-bdb3-d8c276affda0.png)

**Planning - Employee Feedback**
- [ ] The Additional Comments section does not display. Is that because the Supervisor did not enter any Additional Comments? What it the employee wants to enter Additional Comments? 
>Yes, the section doesn't show because we hid it because there was no information. We can make it visible if the employee can add comments.

**Mid Year-In Review**
- [ ] Should the Add Priority button be available? Should a Supervisor be able to add New Priorities after Planning??? Not sure

- [x] Consider moving the EDIT button to the left. Once you Edit one priority the Edit button is not visible without scrolling over.
>I moved the buttons, "Edit" to the left, "Copy" buttons to the right

![image](https://user-images.githubusercontent.com/21112975/188991230-95a8516c-b0f9-488b-8355-587b5f1037b9.png)

**COA Competencies**

- [x] remove this from under the title: To view competencies, select the informational icon 

- [x] remove the Delete option from the row

**Mid Year - Employee Feedback**

- [x] Priorities - Employee Comments option not displaying
![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/b6cee89f-abc1-4781-8977-d8cdb54f98fc)

>I added Employee Feedback from the Employee side and can see it on the table. I think it's just hidden if there is none.
![image](https://user-images.githubusercontent.com/21112975/188993227-b685b40e-1b49-4f16-b487-7f2703ca0c25.png)

**COA Competencies** 

- [ ] remove from under the title: To view competencies, select the informational icon 

- [x] SSPR ID 33, I think as the Supervisor I added a comment on the Mid Year Rate Competencies but in Employee Feedback I'm not seeing the comment
![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/3451361f-fc59-43b3-80b4-99a43149a664)
>I see it
![image](https://user-images.githubusercontent.com/21112975/188993788-2ae0bc0e-375e-4ca8-a889-e57800283bc0.png)

**Supporting Documentation**
- [ ] Do we need the Supporting Documentation title twice?
![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/bb8e235a-b4c5-4d7e-825e-1326ff65f91d)

- [x] remove the Delete option from the row
**SSPR Meeting Signatures**

- [ ] No option for Employee signature - **I can't continue testing** 
![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/c12bd8da-4718-4207-9c9a-2d259ad89252)
>You have to go under My forms>SSPR details. I can see it. I moved it under my Employee Name though.
![image](https://user-images.githubusercontent.com/21112975/188994298-5c27c319-62d0-4170-83fc-dcafb71cfd02.png)

**Comment by moorerst** [comment]
@dianamartin thank you for getting those updates done so quickly. I completed a full test today so I could update the document. I have a few more items:
Planning SSPR
**Priorities**

- [ ] Sorry but I think I prefer Copy on the left and Edit on the right

**Review Competencies**

- [ ] remove the Example sentence under Review Competencies (sorry that was my mistake)

**Supporting Documents**

- [ ] Can you add Optional in front of the button like Additional Comments

**Planning - Employee Feedback**

- [ ] Review Competencies is not displaying - employee should be able to Review the Competencies

**Mid year - In Review**

**Supporting Documentation**

- [ ] Can you add Optional in front of the button like Additional Comments

**Start Review**

- [ ] Can there not  be a default option selected - currently by default Mid Year is selected. Prefer they be forced to make a selection

**Year End - In Review**

- [ ] Add the Information Icon next to COA Competencies - to view Competencies
- [ ] Priorities table is displaying twice
![image](https://user-images.githubusercontent.com/56606465/189195216-44dd5672-104d-4424-b49e-f40c8b7c0931.png)

- [ ] Can the Overall Competencies Ratings be colored coded for Mid Year and Year End like they are for the Priorities 
 
![image](https://user-images.githubusercontent.com/56606465/189195941-f2362517-ce3c-41ce-af97-84281ac7f953.png)

- [ ] SSPR Meeting Signatures is displaying twice - we may have discussed this before I can't remember
![image](https://user-images.githubusercontent.com/56606465/189196255-f252126f-9250-41e2-a1c7-87b437e93a8e.png)

Overall I think it is looking and flowing well. You have done a great job with all the complicated logic. Thanks

**Comment by moorerst** [comment]
[Test Document](https://docs.google.com/document/d/1CzcwZn2jYvVHIpA9BcKXaJK54GBInG75_umaybDzc3w/edit#)

**Comment by moorerst** [comment]
@diana Did some quick testing this morning. All the completed updates look good. Just saw these few items that we can discuss when we meet. Thanks

**Planning - Employee Feedback**

- [ ] Supporting Documentation displaying twice

![image](https://user-images.githubusercontent.com/56606465/189693379-e24c3df3-9682-4182-843e-ce78e8a0890c.png)

**Mid year - In Review** **and Year End - In Review**

- [ ] Priorities
No Copy and No Edit button option
![image](https://user-images.githubusercontent.com/56606465/189695270-9c41788a-6493-4a59-8bc8-55f434d8f752.png)

**Mid Year - Employee Feedback** **and Year End - In Review**

- [ ] COA Competencies
Overall Mid Year rating not displaying color coded
 
![image](https://user-images.githubusercontent.com/56606465/189697875-00077a16-5bc2-4839-ba34-0fe668b558b7.png)

**Comment by dianamartin** [comment]
@moorerst We might want to make a User Actions matrix to figure out what HR wants people to be able to edit and when

**Comment by moorerst** [comment]
@dianamartin I think we can close this issue all of these updates have been completed and tested. I'll make a new issue for the User Action matrix. Great idea Thanks
