### ISSUE TITLE
[Traffic Register] Enhancement: Display Rules for Edit Regulation pages based on Reg Types

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#10206]
We show/hide certain fields to ease the regulation editing process for the Regulation Drafting. Will need to do a full ruleset of similar display rules for all the Reg Types for all edit regulation pages in the app.

Will need to confirm with stakeholders which fields should be showing for each Reg Type.

**Comment by ChrispinP** [comment]
- [ ] Toggle field for editable fields for existing regs
- [ ] Show only fields necessary based on what is present in Reg Text
- [ ] Show/hide rules based on Reg Type for new regs

**Comment by ChristinaTremel** [comment]
Additional enhancement following Usability Feedback, Part 1 meeting:

- [ ] Make all fields not editable if “Edit Action” Field prevents it - “Install/Delete”

**Comment by ChristinaTremel** [comment]
Will bring this up in the sprint review on 2/21.

**Comment by ChristinaTremel** [comment]
For this sprint, focus on adding the [display rules](https://miro.com/app/board/uXjVPkkmY_w=/) for "Tow Away Zone" and "Stop Sign" reg types.

**Comment by ChrispinP** [comment]
Display rules have been updated on the [Miro Board](https://miro.com/app/board/uXjVPkkmY_w=/) 

Need to add to:

- [ ] Blank Install (Draft Builder)
- [ ] Regulation Editor (Draft Builder
- [ ] Blank Install (Draft Review)
- [ ] Regulation Editor (Draft Review)
- [ ] New Reg (Reg Backfill)
- [ ] Edit Reg (Reg Backfill)

**Comment by ChrispinP** [comment]
Display Rules have been successfully applied to all pages above. I have notified Joana to let me know if there are any issues.

Pending any further action

**Comment by ChristinaTremel** [comment]
Closing this issue! Chrispin implemented display rules on all pages.
