### ISSUE TITLE
[DEV] Enhancement of follow-up for scheduled work follow-up

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10207]
Will update these screen shots and scene/view numbers.

## Forms
Follow-up form- `scene 644`
Scheduled Followup - `scene 1299`

Field that needs to be populated on form : Work Order ID (`work_order_signals`) - `View 3207` (Short Text)/`Field 4132`

## Object Info
- `work_orders_signals_scheduled_work_actual` - Object 214/ field 4132

## Screenshot of "Scheduled Follow-up Work Order" Form
![image](https://user-images.githubusercontent.com/21112975/188967111-4bd57af8-66e2-4aa3-8d04-a8f6eeea7574.png)

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/9052#issuecomment-1142315949_

**Comment by dianamartin** [comment]
@johnclary I updated the information on the issue description, let me know if you have questions. The test environment: `TEST | Austin Transportation Data Tracker | 27 OCT 2021`

**Comment by johnclary** [comment]
There is a [PR](https://github.com/cityofaustin/atd-knack/pull/119).

**Comment by dianamartin** [comment]
@johnclary Tested it on Scheduled Work Order `WRK22-166310` 
- it created new [WRK22-166315](https://atd.knack.com/amd#work-orders/work-order-details/6340489d238dfd00212b216b/work-order-details/63404909b7b3d800219faf4e), it should have had "communication - upgrades", but it wasn't attached.
 
![image](https://user-images.githubusercontent.com/21112975/194601649-61c83a14-97e4-4686-acb2-1d94fcb1f0b4.png)

**Comment by johnclary** [comment]
@dianamartin i disabled the custom code, and tried to manually fill out the form. i don't think it's working. can you double-check?

**Comment by ChristinaTremel** [comment]
@johnclary @dianamartin found this from a while ago! Are we okay to close this? 😬

**Comment by dianamartin** [comment]
# 8/1
- [ ] `WRK22-166545` - Follow-up
- [ ] `WRK22-162940` - Original (Diana)
  - [ ] creating a follow-up from this
