### ISSUE TITLE
Banner Permits and Payments in Knack Citybase Build Phase Weekly Sync

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10204]
Using this issue to track notes from the Citybase weekly sync:

Recurring weekly sync meetings with Citybase has been scheduled
9/7 - Notes
A couple items from Citybase
- I have a list of IPs to whitelist (saved on google drive)
- I will have a secret key to send; I need to know who to send this info to via secure link - this will be sent to Chia

Citybase Build phase in progress
there will be several stopping points prior to UAT
- connectivity
- data exchange between Citybase and Knack

Timeline
Citybase will complete build phase by end of September
UAT will begin approx mid Oct. 
Citybase will provide test scripts - 1 week testing period

**What ATD needs to be working on**
- Knack front end customer portal
- Restful server to listen for postback
Record transaction in Knack/mark as complete
After successfully received and recorded in Knack respond back to Citybase with a 200??? which is successful
Citybase will make 25 attempts until the successful response is sent back

Need to handle different types of payments (details in the Webhook document provided by Citybase)
- Initial
- VOID
- Refunds

Set up internal meeting to review what was discussed during the weekly sync

**Comment by moorerst** [comment]
Notes from Eva:

Just a few notes from today:

Concurrent build: 
      1.  Citybase builds the payment portal.
      2.  City of Austin 
          a. build their front-end portal.
          b. build restful service to listen for 
                  postbacks
             (1.)  successful - user successfully 
                  completed their payment at Citybase
             (2.)  refunds - ATD staff initiated - will 
                  have a new transaction ID different from 
                  the original transaction ID
             (3.)  voids - ATD staff initiated - uses 
                  original transaction ID
          c.  Once #b. has been saved to your 
                   database and 
              apply status to Knack, send a 200 to 
                   Citybase per transaction
              to stop transmission of the given 
                    postback.

Test scripts:  
Citybase will be send them out close to the start of UAT.  These documents will be Citybase centric.  
You will need to add in any part of Knack you want tested and how you'd like to reconcile the data between Knack and Citybase (Rev Mgmt or
Remittance file.  Be sure you test both the happy path and the not happy path.
UAT:  
2 iterations of a week
      *  City of Austin test and consolidate issues 
      *  written to a document.
      *  Send results back to Citybase.  Citybase meet 
         with you to discuss.
      *  Citybase can take up to a week to fix, 
          meanwhile all testing stops.
      *  Once Citybase applies fix to UAT, will contact 
         City of Austin to re-test
         
PRODUCTION:  
During the middle of UAT, Citybase and ATD will run a couple of penny tests to 
ensure that the money is moving to the right production accounts.  
The minimum amount for money to move is $10.00.
             You will test for every merchant account that 
             was set up:
             1.  credit card - visa/mastercard/discover
             2.  american express - amex
             3.  ach/eCheck

**Comment by moorerst** [comment]
9/12 weekly Citybase sync canceled

**Comment by moorerst** [comment]
Internal update:
Dev - My update is that I have briefly talked with Frank and John about the RESTful client and have given Frank the heads up that I will be asking for his help when it comes to deploying the service. I did some planning last week on how to set it up and will start actually coding it soon. Frank thinks it will be pretty straightforward 

Apps - I plan to work on some functionality for triggering Voids and Refunds in the Knack CityBase environment

**Comment by dianamartin** [comment]
# 9/19

CityBase says:
- Connectivity this week, later this week
- Email once it's ready
- Connect to end point to see if we can get a response back
- Ping and connect to out system

Emails - 10-15 minute call this week (Thu/Fri)
- debug on the phone - optional
- Josh/Taejin

**Comment by moorerst** [comment]
created issue #10280 for connectivity testing.

**Comment by dianamartin** [comment]
Have meetings notes in Notion

# 10/31
Meeting Notes

- Diana to check in with stakeholders on partial refund question
- Diana to follow up on expected UAT start date - DATE
    - Need to know testers ahead of time so we can add them to RMD UAT - WHO
- Chia/Diana to make test transactions to feed into tomorrow's remittance file in order for Eva to review GL codes
- Chia to share updated production postback url
- Taejin to share updated RMD guide - DONE

**Remittance Knack View**

- Set up Oracle Client, MSAccess, and ODBC for Erin Williams
- [**Revenue Mgmt Guide**](https://cityofaustin.sharepoint.com/:b:/r/sites/CitybaseImplementation/Shared%20Documents/General/Revenue%20Management%20Guide%20%E2%80%93%20CityBase%20Client%20Portal.pdf?csf=1&web=1&e=TWtLzd&isSPOFile=1)

Remittance File
Oracle - hitting database

not providing that data, pull from that database

ODBC
Oracle 64bit
MS Access 64 bit

TOAD
SQL Developer

UAT
Name of Testers

# 11/7
**Next week**

Training on Street Banners invoice creation

- Set up MS Access: Eva 11/8
- Set up ODBC

**NEXT STEPS**
(3) invoices - Production
- $10.00
- VISA/MC/AMEX
- ACH

**Refund in Production**
- Make paperwork
- Manually record
- Manually refund in Advantage

- Review UAT Feedback
    - 11/16 - Thursday
- [x]  Schedule 11/14 UAT
- [x]  Schedule 11/15 UAT

# 11/28
Gail flagged an issue in ACH

ACH payment run through

Let Erin know to can refund 3 original transactions

ACH issue has been resolved

- Run another $10 (CityBase ACH account)
- today or tomorrow

Manage Wallet 

- Test this in Test
- Test this in Prod

Run Refund test in TEST environment

- Email group when that is done - Taejin

**Stakeholder Agenda**

- Internal Testing (Schedule Chia & Diana - this week)
- Customer App Details - hide the correct tables
- Final Test UAT (11/29 at 11:00 am)
    - Customer Name  - COMPLETED ☑️
    - Refund process
    - Manage Wallet - COMPLETED ☑️
- Help Guides? - Diana
    - Make Payment (CC/ACH)
    - Set up Wallet outside of payment
        - Before
        - After
- Communication of switch over to customers .
    - On Portal banner, red text
    

Email communication? No.

Website communication - Yes!

Transition Plan - switching over payments to CityBase (SMO to choose a date?) 

- No hurry, calendar year (Jan 2023)

# 12/5
## ACH error issue

- Funds moving for cards
- .55 transaction fee wasn’t coming over into the bank account

Where is help calls going?

## Customers not able to pay for some reason

- CityBase will get one generic error messages
    - Card info entered incorrectly
    - Bank - unauthorized flag that got flagged
    - Limits: maximum spending limit: $25,000 exceed - show CityBase with an invoice that is greater than $25,000
    - Generic Error: being blocked my work organization
        - redirect to customer to security (place of work) to pass that through firewall
    - Manage Wallet questions
    - Not authorized flag, negative file
        - cleared from negative file
        - Error Code: **R10**: Reversal Reason - in Revenue Management
    
    Customer contacts bank, whitelist the account before they re-try
    
    Contact CityBase
    
    Reason code on Revenue Management: ACH returns
    

CityBase to give it to Chase to raise that limit

- Pull invoice at 60k - provide to CityBase (Alex W.) - DIANA TO DO
- Fake reservation - Customer Name “Janet Doe”

Use Teams “**CityBase Implementation**” - General

# 1/6
Browser related
Different machine
Handheld - phone?
Security block, org security

Whitelist Account
- Get it from Gail in Finance
-

Pay through ACH and a problem
- CityBase - Alex to send
- Contacts to Chase
- 1-2

Alex: Highest invoice send to Alex
- Diana to do it
Max Invoice limit

CityBase Account
- Client Portal
support ticket
cc. mark and eva

CityBase ZenHub: [https://support.thecitybase.com/hc/en-us](https://support.thecitybase.com/hc/en-us)

- [x]  Set up CityBase ZenDesk Account

# 1/9
Last UAT Payment 

- Can perform refund $10.55 on 1/3

Alex 

- Will let us know when Chase bumps up our limit
- Will keep stand-ups for the next two weeks

Manual CR - online payment

- Send to Eva’s team, they need to record it
