### ISSUE TITLE
Add Support for Invoice Requests Comments

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1020]
On the Invoice Details page, add a "Comments" table, as well as an "add comments" form. All users should be able to add comments. Should track comment author and comment date. I think it's totally fine if the comments are editable by all users. I really don't think it's worth the complexity of maintaining two table views for this.

**Comment by johnclary** [comment]
@dianamartin i don't like the idea of having an "invoice_comments" and a separate "purchase_request_comments" object.

What if we used the same comments object for both, but had a field behind the scenes (`comment_type`) that was set to `general` or `invoice` based on which form was used. Then we could just filtered for `invoice_comments` on the Invoice Details page.

Does that make sense?

**Comment by dianamartin** [comment]
Comment form and table configured on `Invoice Details` page
![image](https://user-images.githubusercontent.com/21112975/70947390-9d657080-201e-11ea-9443-116423e05ee1.png)
