### ISSUE TITLE
Automate the execution of detecting and flagging failed CR3 downloads

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10228]
As per @patrickm02L's request [here](https://github.com/cityofaustin/atd-data-tech/issues/10158#issuecomment-1238077967), this is intends to track the discussion and execution of cron'ing or otherwise automating the query found in the above linked issue. This will cause failed CR3 downloads to be detected and have the crash record set to a state where it will have the CR3 downloaded when a DTS team member next executes that ETL (and provides it with a set of valid cookie values, post-captcha.)

**Comment by patrickm02L** [comment]
Refer to Rose's [PR 1272]( https://github.com/cityofaustin/atd-vz-data/pull/1272)

**Comment by johnclary** [comment]
Lucky for us, we now get CR3s through the CRIS extract, and we don't have a reason to address how this work while we still rely on this legacy process 👍
