### ISSUE TITLE
Add `(Invoice) Items` table to PR Details

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1022]

**Comment by johnclary** [comment]
@dianamartin highest priority for sprint 14 because it is blocking dev work on the checkboxes interface.

**Comment by dianamartin** [comment]
- [x] I added the `invoice items` table to the PR details page.
- [x] Renamed to `Received items` on the page
- [x] Added a button to `Add Received Items` also

**Comment by dianamartin** [comment]
This was added to the Production environment.
