### ISSUE TITLE
Sunset CRIS .csv's from AWS

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10227]
Frank and I were talking about storage of the CRIS .csv's in AWS and putting a 90-day sunset policy on these records. Once the .csv's are ingested in the VZDB there's no need to continue to host them.

**Comment by patrickm02L** [comment]
The action is to make the AWS configuration to delete any csv's after 90-days.

**Comment by frankhereford** [comment]
This was completed via the installation of a lifecycle rule on the `atd-vision-zero-database` bucket for the prefix `csv-extracts`.

I spent some extra timing going through the VZ buckets looking for other applications of the lifecycle rules that we may want to use. Everything looks good.
