### ISSUE TITLE
HR Application Employees Record -  Verify Division Name

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10231]
Verify HR employee record contains the correct Banner Division name???

**Comment by dianamartin** [comment]
Jennifer emailed 9/20
>New Division Names:
1.	Administration
2.	Enforcement Services
3.	Parking Services (this is taking the place of Parking Meters)
4.	Shared Demand Management
5.	Vision Zero

Revisions to Division Names:
1.	Transportation System Development, change to Systems Development 
2.	Transportation Project Delivery, change to Project Delivery
3.	Corridor Program Implementation, change to Corridor Program Office
4.	Signs, Markings & Banners, change to Signs & Markings

**Comment by dianamartin** [comment]
## New Divisions
- [ ] Administration
- [ ] Enforcement Services
- [ ] Parking Services (this is taking the place of Parking Meters)
- [ ] Shared Demand Management
- [ ] Vision Zero

## Revisions to Division Names:
- [ ] Transportation System Development, change to Systems Development
- [ ] Transportation Project Delivery, change to Project Delivery
- [ ] Corridor Program Implementation, change to Corridor Program Office
- [ ] Signs, Markings & Banners, change to Signs & Markings

**Comment by dianamartin** [comment]
@moorerst I've updated all the divisions per Jennifer's email. I think they might need to review it again, but I think that's the majority of folks.

**Comment by dianamartin** [comment]
This task was completed on 9/23, closing.
