### ISSUE TITLE
[BUG] User can switch between line and point while drawing specific components types

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#10235]
**Describe the bug**
When a user adds a new component to a Moped project that allows drawing, they can draw points, then switch to a component type that uses lines, draw some lines, and then save both points and lines to the project component.

**URL**

**What steps can we follow to reproduce the bug you are seeing?**
1. Create a new Moped project
2. Go to the Map tab
3. Click "+ Add New Component"
4. From the "Type" dropdown, select "Bike Lane"
5. Click the icon to draw a line and draw a line
6. After completing the line, select "Bike Box" from the "Type" dropdown
7. Click the icon to draw a point and draw a point
8. Click "Save" and you will see that both a line and a point have been saved to a new project component that has a "Type" of "Bike Box" (which should only be points) 

**Screenshots**
https://user-images.githubusercontent.com/37249039/189772309-9e0ddfca-b792-4cee-83fa-e15525c8854a.mp4

**Device**

All devices

**Browser**

All browsers

**Comment by johnclary** [comment]
This will be resolved through the [redesigned component interface](https://github.com/cityofaustin/atd-data-tech/issues/10347).
