### ISSUE TITLE
HR Digital SSPR Stakeholder Testing Round 2

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10242]
Testing scheduled 9/13
Communications to stakeholders:
We have updated the testing document and the application based on your comments from round 1 testing. 
We are ready for round 2 of testing.

Please use the link below to access the updated testing document:
https://docs.google.com/document/d/1CzcwZn2jYvVHIpA9BcKXaJK54GBInG75_umaybDzc3w/edit?usp=sharing

You will complete testing as a Supervisor and as an Employee. 
One of you can be the Supervisor role (listed as Supervisor on SSPR) and one can be the Employee role (listed as Employee on SSPR) 
The testing document indicates the Supervisor actions and the Employee actions
I’m available to be online during your testing to answer questions if you think that would be helpful. 

Please take this opportunity to really give the application a good test, this will probably be our last opportunity to make any tweaks before you invite others to participant in testing.

Document any questions/concerns/suggestions you have during testing.

**Comment by dianamartin** [comment]
# Feedback from 9/14
HR SSPR
Planning - Edit button showing

Remove Year-end | Completed & Signed
Remove Start Review

Close button

**Comment by dianamartin** [comment]
## Added informational guidance on the "Add Priority" form
![image](https://user-images.githubusercontent.com/21112975/190274372-e4ab0754-1285-46d7-8356-fad290842263.png)

## Added informational guidance on the Priorities heading
![image](https://user-images.githubusercontent.com/21112975/190274424-fc715222-3d72-45c1-9f39-18a119d7ee0b.png)

## Added icon for "COA Competencies" header
![image](https://user-images.githubusercontent.com/21112975/190274595-72d7054e-5832-4f98-b7b6-f1dca2abe240.png)

**Comment by dianamartin** [comment]
# Feedback from meeting 9/15
- [x]  Bold title and italicize the help text
- [x]  Add Priority, set to Planning type
- [x]  Add Priority, set to Special Review type
- [x]  Add new form in “Add Priority”, “Special Review”
- [x]  Hide “Add Priority”, in Mid-year & Year-end

- [ ]  Remove “Back to SSPRs” on the bottom of the screen?
    - Add JS code
>Looked into this and I don't think this is a concern, it's not redirecting to the "do not use" site.
- Employee Feedback
    - [x] Priorities
    - [X] Employee Competencies - NEED TO ADD
    - [x] Additional Comments - DONE
- [x] Added Employee Commenting Function on Employee Signature section

## Completed on 9/15 (8:30 pm to 1 am)
- [x] Update the SSPR Statuses to be consistent
- [x] Added icons on Mid-year/Year-end Rating on Priorities to alert user that rating must be filled out
- [x] Had to fix a bunch of rules when I changed the SSPR Status names, some rules got broken. Had to do a host of testing and scenarios to catch all weird bugs that happened
- [x] Hide "Supporting Documentation" table on Employee side if no documents were attached
- [x] Added divider lines to Employee side to make details pages consistent
- [x] Added "Competency Feedback" fields as requested by stakeholders
- [x] Testing new "Competency Employee Feedback" fields
- [x] Updated all page rules to hide "Non-Editable Competency" table as one is used for Editing on Employee side

@moorerst Hopefully, I caught all the buggy things. We can breeze through it tomorrow in our 30 min session.

**Comment by dianamartin** [comment]
# 9/19
The Performance Rating page was a little hard to read through, added the matching status colors for each

## Before
![image](https://user-images.githubusercontent.com/21112975/191104544-49129604-a447-481c-a4a9-77172c850a37.png)


## After
![image](https://user-images.githubusercontent.com/21112975/191104493-e1850992-23d0-4c54-a231-f37c3996a2b7.png)

**Comment by dianamartin** [comment]
# 9/12 
From the HR SSPR Review/Next Steps meeting, Peggy suggested to reorder the Rating Matrix from 
- Outstanding -->Unsatisfactory rather than what it was
- Unsatisfactory -->Outstanding
- [x] Reordered the page 
![image](https://user-images.githubusercontent.com/21112975/191115877-ddb1bce7-0d2b-4ef1-b6a9-44a8425a2ee6.png)
- [x] Reordered the page on GitBook too
![image](https://user-images.githubusercontent.com/21112975/191116057-6216187d-8e7c-4960-b018-f3a003e08215.png)
