### ISSUE TITLE
HR Digital SSPR Create User Action Matrix

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10241]
We might want to make a User Actions matrix to figure out what HR wants people to be able to edit and when. I actually made a workflow of this in this
https://miro.com/app/board/uXjVOpEJw6I=/

I also started this but I think it's too complicated 
https://docs.google.com/spreadsheets/d/1fLY5aQligCLg7WkfLRoXKFcvkR5O-d1vs8WSZtyOsME/edit#gid=0

**Comment by dianamartin** [comment]
@moorerst we've also done other Action Matrixes in the past, we can use them as a reference.

**Comment by dianamartin** [comment]
I used your google doc to create the [user role matrix](https://docs.google.com/spreadsheets/d/1fLY5aQligCLg7WkfLRoXKFcvkR5O-d1vs8WSZtyOsME/edit#gid=0)

**Comment by moorerst** [comment]
@dianamartin the matrix is updated for all the different status. Review, if you're ok with it the issue can be closed

**Comment by dianamartin** [comment]
@moorerst I updated the matrix a little bit with some missing action and reformatted the Status headings to see it easier.

**Comment by moorerst** [comment]
@dianamartin I think this looks good

**Comment by dianamartin** [comment]
Closing this
