### ISSUE TITLE
V7 Bug: RW Property & Street Info - Updates to dates aren't saving correctly. (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10246]
### The system won't update the date/time hour (it will update the minutes)

Steps to Recreate:

1. Open folder RSN (test) 12873688 & click on free-form tab
2. Select top row to edit
3. Update the event time & save

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This issue looks like product issue. I have emailed Gita and Jenice about it to see if we there is a way around to fix it. Thanks.

**Comment by Nadin-Nader** [comment]
Still waiting on CTM

**Comment by Nadin-Nader** [comment]
Still waiting on CTM

**Comment by TracyLinder** [comment]
@Nadin-Nader do we have a SN ticket for this?

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  INC0234485 was raised since I see it as a product issue.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  Anu has fixed it on TEST. I verified it. Its ready for UAT. Thanks.

**Comment by TracyLinder** [comment]
**UAT W/ ROW**
- passed on TURP & Film

**Comment by TracyLinder** [comment]
### Approved for PROD

**Comment by SubhaShroff** [comment]
Thanks @TracyLinder. I have been following up with Anu for PROD promotion. She has raised a request and once done, she will let us know.

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder  This is deployed in PROD. Please verify and let me know if its all good. Thanks.

**Comment by TracyLinder** [comment]
### PROD UAT - OK to Close
2022 166773 RW
