### ISSUE TITLE
Write Moped Read Replica Permission Maintainer ETL

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10251]
When a new table is added to the Moped database, a series of `GRANT` commands need to be run for each read-replica user account. There is not MySQL-like `%` wildcard support that I am aware of. 

This is lightly documented in the "Account Management" section of the [read replica page](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/moped-data/moped-read-replica) of the Moped docs. 

I envision a short python script that connects to the DB that has been fed an array of usernames for input. It would iterate over each username and form up the queries found in that documentation link and execute them. I think if it ran daily, that would be more than enough.

The importance of this script will go up dramatically when we get our first, non-DTS, read-replica user.

**Comment by johnclary** [comment]
We discussed in grooming today and agree we need to get this in place ahead of onboarding more read replica consumers.

**Comment by frankhereford** [comment]
Here's a snippit that came from a discussion with John today, giving an example of what needs to happen on the regular:


```
ssh -L 5433:atd-moped.cgq9skxulxcb.us-east-1.rds.amazonaws.com:5432 herefordf@moped-bastion.austinmobility.io # open up a tunnel to the db via the bastion
```

on both staging and production — it’s the 3rd-6th grants that are fixing it
```
GRANT USAGE ON SCHEMA public TO claryj;
GRANT USAGE ON SCHEMA hdb_catalog to claryj;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO claryj;
GRANT SELECT ON ALL TABLES IN SCHEMA hdb_catalog TO claryj;

GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO claryj;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA hdb_catalog TO claryj;
```

**Comment by frankhereford** [comment]
@patrickm02L @johnclary I would like to pull this on-deck and address it today. Is this ok with you?

While creating the replicate-from-production database functionality in the reworked VZ development environment, I've realized that the in the `import` schema for VZ has its tables dropped and recreated every time the ETL process runs each morning. This resets the permissions to access those tables for read replica users, which requires it to be restored by hand now daily. I think the lack of the solution described in this issue is a blocker for the submission of the recent VZ work for review.

While this issue is written for moped, the implementation will be 99% the same for VZ - I can't think of a reason to not knock them both out at the same time.

**Comment by johnclary** [comment]
sounds good to me! cc @chiaberry

**Comment by patrickm02L** [comment]
@frankhereford please do. Two birds one code!

**Comment by frankhereford** [comment]
I'm going to PR in the VZ DB maintainer, but doing the moped one is blocked by the merging of the testing deployment environment into main. We're running that out of the feature branch currently, and I'd need to either branch off that to get access to the moped dockerized agent environment, or do some other shenanigans. 

This feels like smell - this reason to block -  and I think we should pursue the groups' discussions about making the merge for the testing deployment, even in its very imperfect state. 

@chiaberry Would it be OK if we put this testing-merge on the slate for grooming next week? Thanks!! And no worries if not too of course!

**Comment by chiaberry** [comment]
Yeah, we should put it on the slate to discuss it. I think we'd talked about merging the testing deployment, but it would be good to talk about it again just to confirm.

**Comment by johnclary** [comment]
We have found an alternative using default permissions: https://github.com/cityofaustin/atd-data-tech/issues/12532
