### ISSUE TITLE
Project: Placemaking Program

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10258]
Intake and tracking platform that aids evaluation, milestone management, and a directory for Artists and Art Partners.

## Background
The importance and need of developing a management methodology through Placemaking is essential to have a user-friendly interface to manage processes, collaborate seamlessly with team members, automate tasks, and track key milestones. This becomes important as placemaking sub-programs are expanding and becoming more complex with limited resources. Additionally, there have been some complications with the current application form and intake process currently in place. The intake form currently places all submissions together, rather than separating each intake application.

## Scope & Deliverables
EOI intake form, evaluation platform with key milestones for projects, and directory to track 

## Desired Outcomes
A user-friendly platform that can be used by internal and external agencies to track key milestones. The ability to track beyond when applications come in, but the need for lengthy community outreach before installation is scheduled.

## Timebox
November-December 2022

## Concepts and references

[Google form](https://api.knack.com/v1/applications/595d00ebd315cc4cb98daff4/download/asset/630fa509bb94060021f36aa7/austintransportation_smartmobilityofficegoogleforms.pdf)
[Artbox website](https://www.austintexas.gov/page/artbox-program)

![Placemaking.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/3740b13c-f18b-474d-aa27-7a0d84b1bb55)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
@patrickm02L I added `Project:` here so it shows up on the website. If you add a "Project" label [here](https://github.com/cityofaustin/atd-data-tech/labels) that will fix the missing issues. 

cc/ @dianamartin

**Comment by amenity** [comment]
@patrickm02L  - please write a several-sentence update here & delete this reminder comment so it doesn't show up [here](https://austinmobility.io/projects/10258). ✍🏻 🗑️

**Comment by patrickm02L** [comment]
The project was successfully executed and wrapped on 1/23/23. It includes an EOI intake form, evaluation platform with key milestones for projects, a directory to track as well as a selection tool for geo-located coordinates to city signal boxes.
