### ISSUE TITLE
Create new Artbox application form

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10259]
Convert this [google form](https://docs.google.com/forms/d/1KO_V4adskfK6r5TzXpy1YlTc1F12xM2jCLVcUfjpQVc/viewform?edit_requested=true) to a knack form.

Karo notes: 
- [x] Application form (public)
- [x] Applications Table 
- [x] Application Details page

**Comment by patrickm02L** [comment]
Current applicant form
![screencapture-docs-google-forms-d-1KO-V4adskfK6r5TzXpy1YlTc1F12xM2jCLVcUfjpQVc-viewform-2022-09-15-10_02_11.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/151b7d59-b29f-4a7c-b27a-89d49c4f8a6e)

**Comment by KaroEngstrom** [comment]
## T 9/20/22 

- [x] Create `artbox_application` object
- [x] Create public [Artbox Program Application](https://atd.knack.com/smart-mobility#artbox/) webpage
- [x] Create Placemaking portal home page, Artbox home page with Artbox applications table, and Artbox application Details page
![image](https://user-images.githubusercontent.com/100615928/191353954-2e647e59-9556-40f1-8b30-d7983c02ccce.png)

**Comment by patrickm02L** [comment]
I filled out the form as a quick test. It's good!

**Comment by KaroEngstrom** [comment]
## Th 9/22/22

Did a quick demo to Diana who suggested this edit: 
- [ ]  Break Acknowledgements into separate fields to force Yes on each 

PREVIOUS/CURRENT FORM: 
![image](https://user-images.githubusercontent.com/100615928/191862025-de59c0f7-9899-47f7-8c42-80433f5632b4.png)


FIRST DRAFT: 
![image](https://user-images.githubusercontent.com/100615928/191861904-18ac6989-f37d-41f7-a85c-b45d1a505ce6.png)

NEW VERSION: 
![image](https://user-images.githubusercontent.com/100615928/191863399-a89a7324-8289-45c9-a469-433071adbd94.png)

- cannot remove the red asterisks without making the field not required. There may be a custom code solution; will check with the Apps Team.

**Comment by KaroEngstrom** [comment]
Approved in the last sprint review, incl. the header image. Closing.
