### ISSUE TITLE
SD 2023 Community Survey Text Updates

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#10265]
From Nicole C, we have to update the text for the three ATD performance measures which are measured using the Austin Community Survey. Specifically, the **status** and **trending** sections.

Due: Monday, Sept 23 end of day.

ATD | M.B.2 | Percent satisfaction with cost of transportation to get around Austin | https://data.austintexas.gov/stories/s/6ywm-cejy
-- | -- | -- | --
ATD | M.B.3 | Percent of households reducing the number of cars in their household | https://data.austintexas.gov/stories/s/rine-sac9
ATD | M.C.2 | Percent satisfaction with transportation options (aside from personal vehicle) to get around Austin (e.g. ride share, bus/train, bike, walk) | https://data.austintexas.gov/stories/s/p2hz-spmf

**Comment by Charlie-Henry** [comment]
Text updates:

ATD | M.B.2 | Percent satisfaction with cost of transportation to get around Austin | https://data.austintexas.gov/stories/s/6ywm-cejy
-- | -- | -- | --

**Status**: No changes

**Trending**: 

Original text:
In the last two years, this measure has trended down. The City of Austin would like to see the percent satisfaction increase and is prioritizing delivery of infrastructure projects and transportation demand management programs to increase the availability of affordable transportation choices.

New text:
The results of the last three surveys have all been fairly consistent in that one-third of respondents were satisfied with the cost of transportation. All three surveys have met or exceeded the goal of 31% satisfaction. The City of Austin would like to see the percent satisfaction increase and is prioritizing delivery of infrastructure projects and transportation demand management programs to increase the availability of affordable transportation choices.

**Comment by Charlie-Henry** [comment]
ATD | M.B.3 | Percent of households reducing the number of cars in their household | https://data.austintexas.gov/stories/s/rine-sac9
-- | -- | -- | --

**Status**

Original text:
The results of the annual community survey determined that 9% of households have fewer cars in 2019 than they did in 2018. Reducing the number of cars in a household (i.e. going from having two cars to having only one car) often indicates that individuals or families have other options to get around Austin without each driver needing to own a personal vehicle.  The results of this measure, determines the ability of households to choose to reduce the number of privately owned cars.

New Text:
The results of the annual community survey determined that 11% of households have fewer cars in 2021 than they did in 2020. Reducing...

**Trending**

Original text:
The annual community survey has only included this item for one year, creating the baseline for this measure.  This measure calculates the incremental change in the number of cars per household.  Austin Transportation is actively working to increase the speed, reliability, safety, and affordability of other modes of transportation and actively communicating the benefits of telecommute solutions to impact this measure.

New Text:
The percentage of households reducing the number of vehicles year-over-year increased from 9% in 2019 to 11% in 2021.  This is significantly above the goal of 2%. Austin Transportation is actively working to increase the speed, reliability, safety, and affordability of other modes of transportation and actively communicating the benefits of telecommute solutions to impact this measure. Increased telecommuting in part due to the COVID-19 pandemic was likely a factor increasing this measure.

**Comment by Charlie-Henry** [comment]
ATD | M.C.2 | Percent satisfaction with transportation options (aside from personal vehicle) to get around Austin (e.g. ride share, bus/train, bike, walk) | https://data.austintexas.gov/stories/s/p2hz-spmf
-- | -- | -- | --

**Status**:
No Changes

**Trending**:
No Changes

**Comment by Charlie-Henry** [comment]
@katelunceford if you got a chance to take a look at my text changes. Don't think that it matters that it's due Monday, we can make further changes whenever.

**Comment by patrickm02L** [comment]
Kate if you have any changes feel free to edit it yourself. See the links at the top. 

All the date needs to be up to date and fresh by October 1st.

**Comment by patrickm02L** [comment]
Kate schedule 30 min to get reviews on this with @maccallump, @Charlie-Henry, and @patrickm02L.

**Comment by amenity** [comment]
Sounds like y'all are good to go. 👍🏻
