### ISSUE TITLE
V7 Bug: Unable to edit existing people member record

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10268]
On ROW Contractor people records, users are able to add a member record however they are unable to edit an exiting member record. System throws an error message ‘People member permission denied.’ Staff is unable to remove permit access for inactive agents. 

![image](https://user-images.githubusercontent.com/49930868/190713517-73dbe554-ab25-4c90-8b50-fa1d99f693c0.png)

**Comment by TracyLinder** [comment]
@SubhaShroff will talk to Gita about troubleshooting this.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  Spoke to Gita and after some investigation, the users need EDIT privilege given on Members tab and that would sort the issue. I raised a ticket for this [INC0231547](https://atx.servicenowservices.com/incident.do?sys_id=ee53ddc81bd6955091528407624bcb0e&sysparm_record_target=incident&sysparm_record_row=1&sysparm_record_rows=4208&sysparm_record_list=active%3Dtrue%5EORDERBYDESCnumber).

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  Jenice fixed the issue on TEST/PROD and the ROW staff also confirmed that the fix is working that they are able to do the edit on member tab. This ticket is good to close. Thanks.
