### ISSUE TITLE
[Enhancement] Ability to search by Project ID

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10270]
Now that we have project IDs rendering everywhere (#9551), users should easily be able to search by project ID with the non-advanced search features.

<img width="1447" alt="Screen Shot 2022-09-21 at 2 24 23 PM" src="https://user-images.githubusercontent.com/14793120/191582332-2e56aa5e-ea30-46f5-a3b9-940f0a269ff8.png">

**Comment by patrickm02L** [comment]
@johnclary @amenity making this Issue was an action item from Product Sync 9/7/22.

**Comment by johnclary** [comment]
thank you, @patrickm02L! i’ll get this queued up cc @chiaberry
