### ISSUE TITLE
Add Arterial Management & Austin Police Department to the Coordination Partners list

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10271]
Staff would like to add Arterial Management and Austin Police Department as additional options for selections from the Coordination Partners drop down in the Recommendations section. 

Please add them to the `atd__coordination_partners_lkp` table.

![Screen Shot 2022-09-19 at 8.04.52 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/9dc11df8-eead-4227-a8f8-36a4502bbd1b)

**Comment by roseeichelmann** [comment]
The new selections for the Coordination Partners dropdown have been added in staging and are now visible in VZE. We will need to make a note to replicate these additions for production before the release on 10/3. I went ahead and made a note and can add it as a step when the Release PR is created @patrickm02L 

![image](https://user-images.githubusercontent.com/67130963/191834827-c0474d99-c2a0-4085-b908-e74acf1ee1f4.png)

**Comment by patrickm02L** [comment]
Looks good! @roseeichelmann this should be good to close.
