### ISSUE TITLE
[BUG] Moped test instance resources occasionally respond with `net::ERR_NAME_NOT_RESOLVED`

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#10273]
**Describe the bug**
When using a Moped test instance, the API and GraphQL endpoints will sometimes error with`net::ERR_NAME_NOT_RESOLVED` in the browser. This feels like a DNS issue, but it is hard to pinpoint since the endpoints respond most of the time making this hard to reproduce. No request is happening since the browser isn't resolving an IP.

**The workaround for now is to wait until the endpoints respond.**

Moped API
```https://u5juwh4o14.execute-api.us-east-1.amazonaws.com/md-9697-refactor/users/ net::ERR_NAME_NOT_RESOLVED```

Moped GraphQL engine
```https://md-9697-refactor-user-edit-form-graphql.moped-test.austinmobility.io/v1/graphql net::ERR_NAME_NOT_RESOLVED```

**URL**

**What steps can we follow to reproduce the bug you are seeing?**
Not easy to reliably reproduce, but:
1. Go to a Moped test instance
2. Navigate to a view that makes a request to the GraphQL endpoint - or:
3. Navigate to the user management views and try to create/edit/inactivate/activate a user

**Screenshots**
n/a

**Device**

All

**Browser**

All

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [ ] Major — can only perform work using a workaround
- [x] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Additional context**

**Comment by mddilley** [comment]
Just tripped over this, and I think that this occurred because two branches were named very similarly and generated test instance resources with names that collided - `md-9697-refactor-user-activation` and `md-9697-refactor-user-edit-form`. Might help debug this if it comes up again.

**Comment by frankhereford** [comment]
Curious what you think @mddilley -- do you think we should have added a system where we take an md5 of the branch name and just use the first 16 characters of it for our slug all throughout the AWS deployments? Effectively making it impossible to collide with ourselves in the various deployments? Given the relatively small search space of branch names, we can even go back the other way hash=>name via either a little state keeper `redis` machine or just brute forcing it, if needed.

**Comment by mddilley** [comment]
I think that sounds good to me in order to avoid collisions. I can't remember if it is a limitation on what can be used to name some of the resources, but can we use the PR # as an additional parameter? It seems like a straightforward thing to pass in along with the branch name, won't ever collide, and it can be retrieved in a Github Action down the road if we automate this more. I think this came up before so maybe I'm forgetting why we didn't do that in the first place.

The only concern that I have about obscuring the names too much is that we would have a hard time tracing resources in the AWS console to a branch or PR if we need to remove things manually - but that wouldn't be a problem once we get the decommission flow going so maybe it isn't that big of a deal.

**Comment by johnclary** [comment]
Closing because we have abandoned the prefect-based test deployments.
