### ISSUE TITLE
Knack Citybase Integration Connectivity Testing

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10280]
9/19 weekly sync Citybase said

- Connectivity this week, later this week (week of 9/19)
- Email once it's ready
- Connect to end point to see if we can get a response back
- Ping and connect to out system

We've decided to test asynchronously (via email) rather than syncing on the phone

Josh and Taejin Citybase contacts

**Comment by moorerst** [comment]
From vendor: 
- Confirmed that we have completed our tasks related to the build that enables a connectivity test.

Here is the endpoint: [https://invoice-service-austin-tx.uat.cityba.se/invoices/austin_tx_transportation/street_banner](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Finvoice-service-austin-tx.uat.cityba.se%2Finvoices%2Faustin_tx_transportation%2Fstreet_banner&data=05%7C01%7CStephanieC.Moorer%40austintexas.gov%7C6bd5bdd3fc5e4934c61508da9cd39d87%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637994729955335752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=i9lTG0O8M9ABsrXRgShdtr2pwFMMUDvuvmSD24kWH2k%3D&reserved=0)

Let us know the results of this test or if you have any follow up questions.

**Comment by chiaberry** [comment]
yes! I let Josh know that I was able to connect and thanked him for the docs.

**Comment by moorerst** [comment]
Per Chia 
Update -- using fetch instead of ajax/jquery to make the request does successfully return the url once the promise resolves, as well as a 200 status. Thanks!

@chiaberry can we consider this complete/closed?
