### ISSUE TITLE
FY23 Fees: Update ROW Fees for FY23 (On PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#10282]
Stakeholders: Paloma, Kim , Ryan

These are the downloaded ROW fees:
[https://app.zenhub.com/files/140626918/829f1f8e-7649-4569-b780-b4c101f90893/download](https://app.zenhub.com/files/140626918/829f1f8e-7649-4569-b780-b4c101f90893/download
)

**Comment by Nadin-Nader** [comment]
Same updates as #9897

**Comment by TracyLinder** [comment]
@SubhaShroff please update the DS fee 50035 from $195 to $260

**Comment by TracyLinder** [comment]
### UAT Notes

## ASAP

- TURP ROW Usage Fees are not updated
    - Sending to test (except the newly added)
    - I need to document the alley fees & make a card for it - Priya
- Update fee 83494 ATD-TEMP-Valet Application Fee from $60 to $70
    - Done / On the way to TEST
- DS - 50035 Update application fee amount - Subha
- LC -  & update amount to $185
    - Subha has done & on the way TEST

## Next Week

- RW-Valet Operator - Rename (50200) to ‘Valet Renewal Operating Permit Fee’ at $295 AND add to Run fee menu
- 50180 Valet Parking Application Fee (amount correct; surcharge not entered)
- Update name to (5800) Concrete License Fee to Right of Way Contractor License

**Comment by TracyLinder** [comment]
@SubhaShroff please Update fee code 50348 description “ATD - Driveway/Sidewalk Application Fee”

**Comment by SubhaShroff** [comment]
@SCTASK0252465 name and amount changed for 50348, DEV/TEST requst is submitted.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0252466 is requested for PROD deployment

**Comment by SubhaShroff** [comment]
@Nadin-Nader  PROD deployment was done on Friday.

**Comment by SubhaShroff** [comment]
@TracyLinder  I am not sure which fee it is originally. 
RW-Valet Operator - Rename (50200) to ‘Valet Renewal Operating Permit Fee’ at $295 AND add to Run fee menu?

**Comment by SubhaShroff** [comment]
[TURP Fees.csv](https://github.com/cityofaustin/atd-data-tech/files/9748002/TURP.Fees.csv)
@TracyLinder @Nadin-Nader 
This excel sheet has the configured(in lookup table) and suggested fee Names from for the TURP fees. Please review sheet if that is correct mapping of existing and suggested names.

**Comment by SubhaShroff** [comment]
> Valet Renewal Operating Permit Fee

This is done.

> @SubhaShroff please Update fee code 50348 description “ATD - Driveway/Sidewalk Application Fee”

This done.

**Comment by SubhaShroff** [comment]
NOTES: 
1. Update fee code 50348 description “ATD - Driveway/Sidewalk Application Fee” - This was deployed in PROD(SCTASK0252466), but now it looks like reverted in DEV/TEST/PROD. I will make a fresh commit which would help to avoid more conflicts to and fro.
2.  RW-Valet Operator - Rename (50200) to ‘Valet Renewal Operating Permit Fee’ at $295 AND add to Run fee menu? @TracyLinder 
3. Update name to (5800) Concrete License Fee to Right of Way Contractor License - This done on PROD (lookup -50060)
4. 50180 Valet Parking Application Fee (amount correct; surcharge not entered) - Working on it.

**Comment by TracyLinder** [comment]
@SubhaShroff Thanks for the update. My answers are below for 2 & 4. 

2. This fee is for the Valet Operator subtype. Is it on Test?

4. ATD Tech Surcharge, 4%

**Comment by SubhaShroff** [comment]
NOTES for Valet Operator permit fee (50200).
Selecting this fee from the menu it inserts one of the following:
75300	Valet Initial Operating Permit Fee (for workcodes Valet Initial(61100), valent initial Renewal(61105))
75305	Valet Additional Operating Permit Fee(for worktype valet additional (61110)
@TracyLinder I think  you want me to update for 75300 first one. But, is it ok, if it displays as ‘Valet Renewal Operating Permit Fee’ for Valet Initial work type also?

**Comment by TracyLinder** [comment]
Pulling the valet operating fees into another ticket, #10506

**Comment by TracyLinder** [comment]
@SubhaShroff here is the updated TURP excel sheet. [Uploading... TURP.Fees.numbers]

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder On Friday, ROW call Paloma and Tracy asked to hold on with name changing of TURP fees. And also, for extension fees if name has to be changed new fee types should derived and whole fee logic may change. I see it can go bit complicated for name change. Until, I hear from them, we hold this ticket. Thanks.

**Comment by TracyLinder** [comment]
### Closing Ticket
- We will create a new ticket for future bugs/requests.
