### ISSUE TITLE
Update Workflow Docs To Match New User Stories

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1028]
Let's hold off on this until we have a working prototype based on recent changes, e.g.:

- shipping/invoicing process
- work order integration

**Comment by amenity** [comment]
@dianamartin @johnclary - should there be a dependency here? & or should it go in the Blocked pipeline?

**Comment by dianamartin** [comment]
@amenity blocked pipeline is fine

**Comment by johnclary** [comment]
@dianamartin plz make sure all of your workflow docs are [here](https://drive.google.com/drive/u/0/folders/1QcnnSwb46BIZj6cfaIT80DNdH3O4AUXW)

**Comment by dianamartin** [comment]
@johnclary I updated the Warehouse Inventory workflow, it's in the file folder you wanted it to be in. Also, check the Knack Operations GitBook to see what I wrote about the Warehouse Inventory process and status field mapping.
