### ISSUE TITLE
SIF Raw Data ~ Dan H ~ By District Area

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10295]
### Dan needs the following data for all valid invoices on SIF folders

- FolderRSN
- Total amount invoiced _(for the entire folder/fee tab)_
- Total amount paid _(for the entire folder/fee tab)_
- SIF Service District _(from folder info)_

**Criteria/Validations:**
- ALL SIF Folders (all status'), with a valid invoice
    - Valid invoice = Status is not canceled 
- Be sure to exclude voided payments.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder  - Please check this query and excel 

SELECT f.folderrsn, f.foldertype, fi.infovalue, ab.billnumber,ab.PAIDINFULLFLAG, ab.billamount,ab.totalpaid
FROM Folder f JOIN accountbill ab ON f.folderrsn = ab.folderrsn 
JOIN accountbillfee abf ON f.folderrsn = abf.folderrsn AND abf.billnumber = ab.billnumber
JOIN folderinfo fi ON f.folderrsn = fi.folderrsn
AND fi.infocode = 84012
WHERE f.foldertype = 'SIF'   
AND ab.paidinfullflag = 'Y'  
ORDER BY foldertype

[10295 - SIF Data.xlsx](https://github.com/cityofaustin/atd-data-tech/files/9629088/10295.-.SIF.Data.xlsx)

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan thank you. 

I have sent the data link to Dan & Maddie.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Sent unpaid SIF Data with district info
Query - 
SELECT f.folderrsn, f.foldertype, fi.infovalue, ab.billnumber,ab.PAIDINFULLFLAG, ab.billamount,ab.totalpaid
FROM Folder f JOIN accountbill ab ON f.folderrsn = ab.folderrsn 
JOIN accountbillfee abf ON f.folderrsn = abf.folderrsn AND abf.billnumber = ab.billnumber
JOIN folderinfo fi ON f.folderrsn = fi.folderrsn
AND fi.infocode = 84012
WHERE f.foldertype = 'SIF'   --IN ('SIF','TIA')
AND ab.paidinfullflag = 'N'  
ORDER BY foldertype
[10295 - SIF Unpaid Data.xlsx](https://github.com/cityofaustin/atd-data-tech/files/9635373/10295.-.SIF.Unpaid.Data.xlsx)

**Comment by Nadin-Nader** [comment]
Completed
