### ISSUE TITLE
[Spike] Stress test Moped under heavy database load

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10293]
When we migrate the Interim Access DB to Moped, we will add many thousands of projects and their related records.

Once concern that comes to mind is our Project list's performance under this load, since we currently fetch all projects when the app loads.

Todo:
- Generate ~10k projects with team members, phases, milestones, and components
- Test app performance via test deployment
- Bonus points - `ANALYZE` Hasura/Postgres queries for opportunities to add indices.

Also for consideration: https://github.com/cityofaustin/atd-data-tech/issues/10799

**Comment by chiaberry** [comment]
@johnclary is this addressed by https://github.com/cityofaustin/atd-moped/pull/888?
