### ISSUE TITLE
[TDS] Enhancement: Adjust TDS App to be Full Width instead of Max Width (Update Column Widths, Footers, & Big Buttons)

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#10291]
TDS app was originally created with the Max Width setting. Now that the app and its several modules have grown the app and house a lot of data, many tables and views create extra unnecessary scrolling that can be resolved if we change the display setting from Max Width to Full Width. This allows the workspace to expand the full width of one's monitors to maximize screen real estate. By result, this produces more readable tables and makes pages feel less cluttered. Footer and Big Button views will need to be realigned with the new screen space but all other views will not need any adjustments. All pages provide the same functionality with a reduced amount of scrolling. This will make TDS appear similar to our other major apps.

Need to schedule a time to push this update since it may be slightly jarring to app users but the update should only take an hour.

- [x] Set to Full Width
- [x] Column Widths
- [x] Footers
- [x] Big Buttons

**Comment by TracyLinder** [comment]
We need to plan this around user "downtime". They need to be expecting the format change.

**Comment by TracyLinder** [comment]
### TRACY - SEND A USER EMAIL

**Comment by ChrispinP** [comment]
@TracyLinder in-app announcement has been added to notify users:
![image](https://user-images.githubusercontent.com/67915167/193155008-15912a87-8074-4aa4-ae36-d52c4fb20c5e.png)

**Comment by ChrispinP** [comment]
Update complete, pending any issues/closure

**Comment by ChrispinP** [comment]
No issues after update, closing
