### ISSUE TITLE
[TDS-TIA] Tech Debt: Remove Case Log feature from TIA

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#10306]
Justin and Joan mentioned this feature is not currently being utilized enough. The original intent of the Case Log feature was to improve auditability data for when any actions happen in the app. We can increase app performance and decrease app complexity by removing the feature.

- [x] Confirm with stakeholders to remove
- [x] Remove all Case Log rules on buttons and forms
- [x] Remove Case Log pages
- [x] Remove Case Log object
- [x] Remove Case Log code

**Comment by ChrispinP** [comment]
all elements of the Case Log feature have been removed. Will create a PR for the code updates.

Ready to review

**Comment by TracyLinder** [comment]
This is gone. Closing.
