### ISSUE TITLE
[TDS-TIA] Enhancement: Retire the Memo Details page and move the Send Final Memo button to Case Details page

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#10305]
Received word from Justin and Joan that the Memo page is not being utilized and could be removed with us relocating the Send Final Memo button to the Case Details page instead.

- [x] Get confirmation from Nathan
- [x] Remove Memo Details Page code
- [x] Remove Memo Details Page

**Comment by TracyLinder** [comment]
To be scoped w/ Nathan's team when we meet to review #10109, #9574

**Comment by TracyLinder** [comment]
### Conversation w/ Business Partners:
- OK to move
- Don't need send memo feature

**Comment by ChrispinP** [comment]
Removed Memo Details page, button, and code. Will create a PR for the code changes.

Ready to review

**Comment by TracyLinder** [comment]
This is gone. Closing.
