### ISSUE TITLE
Research Signs Tablet Performance

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1030]
@amenity @dianamartin @SurbhiBakshi after talking with Anthony F and Gilbert (sign tech) on Friday, we badly need to research ongoing issues with the signs work order experience.

Anthony is offering any help we need, including moving to a different tablet (higher CPU Android, or iPad).

There's a lot to look into. Based on what I've heard:
- airwatch may be slowing the app down
- there may be slow network speeds in the field 
- apparently the map occasionally unexpectedly pans away from the work location, causing the user to think their locations have "disappeared"
- selecting sign asset types can be really tedious, e.g. there are multiple types of `ped` signs, and you have to scroll a long time to find the one you want to choose

I'm also starting to wonder if there's any point in having technicians capture locations for non-maintenance work, i.e., work that has plans draw up by engineers. Shouldn't we be able to do our GIS QA/QC from the plans? These are the work orders that are most cumbersome for technicians to submit (because they can have 10+ locations). Maybe we can do away with them?

In any case, shadowing Gilbert is definitely the place to start. He welcomed the idea. Let's discuss during sprint planning. I'd like to move this to our highest priority, and make room for it above existing commitments if possible.

**Comment by amenity** [comment]
Would be great to bring a tablet that does not have Airwatch to compare.

**Comment by amenity** [comment]
**_RE: Removing requirement for technicians to capture locations for non-maintenance work, i.e., work that has plans draw up by engineers._**

At the moment, TE is not creating work orders that are precise + accurate enoguh for a GIS tech to add the.

**Comment by dianamartin** [comment]
@amenity currently factory resetting one of the test tablets I have

**Comment by dianamartin** [comment]
Gave Amenity tablet without AirWatch configured on it for testing purposes

**Comment by amenity** [comment]
@johnclary - Christina is going to get me Gilbert, but not sure that we need to wait for a ride along to dive into this. During our Sprint Review just now we're seeing pretty bad performance lags throughout the app. Christina says that results in a forever-spinning wheel throughout the app. She reports that it goes faster if the page is reloaded and occurs even in the afternoon after 3:30pm when engineers are no longer working.😕

**Comment by amenity** [comment]
- Gilbert reports that he is no longer experiencing issues. 
- Diana tested to confirm that Airwatch is not the problem

**Comment by amenity** [comment]
Going to try testing in a private Knack instance. #1376 Will open further issues as necessary.
