### ISSUE TITLE
(TDS) FY23 Updates (On Prod)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10310]
[https://app.zenhub.com/files/140626918/0661d55e-db61-475e-b7ee-dd01d87f5303/download](https://app.zenhub.com/files/140626918/0661d55e-db61-475e-b7ee-dd01d87f5303/download)
Updated fee document on the link above.

**Comment by Nadin-Nader** [comment]
According to Sree and Vish this is all included in cards #10282 #9897 Subha will be doing the date updates

**Comment by TracyLinder** [comment]
### Approved for PROD

**Comment by SubhaShroff** [comment]
Status: I think We are done with this too. Guess, we are waiting on user's feedback.

**Comment by Nadin-Nader** [comment]
No Issues with fees for TDS have been reported. closing
