### ISSUE TITLE
Temporary access for "Inventory Editor" to Adjustment Form for AMD year-end

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10328]
Ronnie
AMD

Asked if it would be better for me to update adjustments or for him/Ray to do it.

**Comment by dianamartin** [comment]
Checked the "Adjustment" page and only the "System Administrator" role. 
- Gave the page "Inventory Editor" rights
- Ronnie - said he'll let me know when to turn it off

**Comment by amenity** [comment]
@dianamartin - please follow up w/ Ronnie to see if this is needed any longer.

**Comment by dianamartin** [comment]
11/2 - Just checked and the page only had "System Administrator" rights, no "Inventory Editor". This is completed.
