### ISSUE TITLE
Connect Contractor to Correct Bid Items in Signs and Markings

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10323]
Christina from SMB messaged that the new Contractor bid items were populating incorrectly in tables and reports. Checked it together and found new big items in the system but it looked like a specific Contractor was getting the wrong (outdated) bid item price associated with their work logs. 

Talked to Diana and implemented plan to update existing items and correct the work log connection as shown below:

**Comment by dianamartin** [comment]
Karo and Diana synced 9/27
- we checked the work logs and filtered for the 885 contract
- 46 records came back
- Had to add Contractor Code to `contractor_big_items`>Display Name 
- Force updated all records in `contractor_big_items` and `contractor_work_log`
- Update the "Add contractor_materials_log" form
![image](https://user-images.githubusercontent.com/21112975/192643025-2e586752-f752-450d-9742-0c3d127fb798.png)

# Steps to Correct
- Go to `contractor_work_log`
- Filter `contractor_vendor` - 885
- Should have `46 records`
- Export list
- Enter `contractor_bid_item` (search by bid item number: ex. (871A-A-24-W) - 885
- Then check that "Contract No" is updated

**Comment by KaroEngstrom** [comment]
W 9/28/22 

Response from requester:   
"Thank you, Karo! It looks like the problem has been fixed. 😊 Really appreciate your help."
