### ISSUE TITLE
[PORTAL] Update Street Event Application Type in Portal

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10332]
### Update Street Event Application Type in Portal
`OSE's # 3 Priority`

**Acceptance Criteria** 

- When user applies for Right of Way Permits in the Portal, under Right of Way application type, rename "Street Event" to "Neighborhood Block Party"
- When user selects Neighborhood Block Party, system must create an RW - Street Event folder with Work type Neighborhood Block Party.
-  All other functionality that exists within this application will remain unchanged. 

**Notes:**
- Street Event has it's own heading now, but it's for the SE folder, not the RW-Street Event folder. 
- When you select the event type under the ROW Heading, the system doesn't prompt the user to select the folder work type. 

**Solution Options:**
1. Remove RW-Street Events from the Right of Way heading, and make it it's own heading. Name it Neighborhood Block Party. 
2. Keep it nested where it is and rename it Neighborhood Block Party. 

- Either way, when the applicant begins the application the system needs to auto-select the Neighborhood Block Party work type if possible. 

### We need to consult Swapna with the solution to get feedback on portal development. Will this break portal?

**Comment by TracyLinder** [comment]
@vschandramouli please work this into your normal scoping cadence as a normal priority. Thank you!

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by TracyLinder** [comment]
### OSE Prioritization Notes 7/18/23

- Sree most likely to be assigned.
- Schedule meeting w/ Swapna, Vish, Sree, Nate optional

**Comment by TracyLinder** [comment]
### Prioritization Update 9/18/23

- **On Hold** we're putting a hold on this development while the Living Streets program permitting gets figured out. We're in a bit of limbo at the moment.

**Comment by TracyLinder** [comment]
### Update

- OSE made updates to the portal language during the portal upgrade. This is OK to close per OSE.
