### ISSUE TITLE
[Traffic Register] Data Enhancement: Generate a new Regulation ID formula

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#10338]
New Regulation ID will be on every record so all records have a searchable ID, even drafts
Old Regulation ID will be maintained and shown in tandem
Hide or show RN?

**Comment by dianamartin** [comment]
# 1/5
Joana had emailed me to let me know that TED folks were asking about new Reg IDs and she wanted to know when the new auto populated REG IDs would come into play. 

We had a meeting 1/5 with Joana, Stephen, Adan, Eric B., Chrispin and me. We discussed that they've issued out `11 REG IDs` so far, so `2023-0011`. 

@ChrispinP can you add a screen shot here please 🙏🏽 
Chrispin showed the workflow he had to the group and 
it was decided they would choose "Option A", which is the spelled out version: 
- `23DOCxxxxxx7` - Reg Doc 
- `23REGxxxxxx7` - Reg line item

It was also decided that Joana and team would continue issuing out `2023` Reg IDs until the Traffic Register application came online and went live.

**Comment by ChrispinP** [comment]
![image.png](https://images.zenhubusercontent.com/5f036c8940760b58210af838/8a84c737-0112-4912-8713-e0c6e72c29f3)
![image.png](https://images.zenhubusercontent.com/5f036c8940760b58210af838/0ab48220-c80d-47cd-ab9d-c396cb2d72df)
![image.png](https://images.zenhubusercontent.com/5f036c8940760b58210af838/3cdb9119-228d-442f-9a61-7ac3c0f346e8)

**Comment by ChrispinP** [comment]
Showing the new IDs to Eric on Monday 02/27 and discuss benefits of retiring the old IDs. @ChrispinP will make sure this is ready to show in Prod

**Comment by ChrispinP** [comment]
New Reg ID working as intended. Will display in tandem with the old Reg ID formula.

Closing
