### ISSUE TITLE
[Traffic Register] Enhancement: Updates for Regulation Advanced Search 

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#10335]
Reviewers need the flexibility to search for regulations that they do not know the details of or know if they exist in a certain area. Need the ability to search for regulations within a certain block ranges or other parameters.

**Comment by ChrispinP** [comment]
Search Directory implemented for both Approved Regulations and Regulation Documents with  Basic Search, Filtered Search, & Power Search. Unconnected/Unassigned search also provided respectively. 
![image](https://user-images.githubusercontent.com/67915167/203870887-88ad2564-1f91-4f3d-a3a2-5ce3df3cbf9b.png)

![image](https://user-images.githubusercontent.com/67915167/203870963-b25dfc78-ed28-43b1-a893-6f9c321ad76e.png)

![image](https://user-images.githubusercontent.com/67915167/203871053-0b68539d-07ed-4fcf-8862-7915742d3bff.png)

Ready to review

**Comment by ChristinaTremel** [comment]
Chrispin has completed the overhaul of the advanced search and is will continue to make edits through hearing from users. Closing this initial issue and will create new issues as we hear feedback.
