### ISSUE TITLE
Update Fee Name - OSE - 50130 - Street Event Inspection Fee (Deploying to PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10345]
### Rename fee to Street Event Safety Inspection Fee

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted DEV/TEST DP for your reference. Kindly approve and create task id for me. 
Commit ID: [5ce0b04ff936](http://coaamandadevops02.austintexas.gov/R5:5ce0b04ff936a978c3ba6a8eb8d983e4c5dd20b1)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been sent to the DevOps CM Team to be deployed to **_DEV_** and **_TEST_** under **SCTASK0257347**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV and TEST. I will ask Maria to UAT

**Comment by Nadin-Nader** [comment]
Waiting on Maria's response

**Comment by Nadin-Nader** [comment]
@SubhaShroff Maria has approved the move to PROD

**Comment by SubhaShroff** [comment]
> @SubhaShroff Maria has approved the move to PROD

CC: @Sreelatha-BlazeKannan

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - PROD DP of #10345submitted. Kindly approve and create task id for me. 


Commit ID: [5ce0b04ff936](http://coaamandadevops02.austintexas.gov/R5:5ce0b04ff936a978c3ba6a8eb8d983e4c5dd20b1)

**Comment by TracyLinder** [comment]
This is working.
