### ISSUE TITLE
[BUG] Dashboard does not display "My projects" or "Following" projects

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10341]
**Describe the bug**
The Moped "Dashboard" tab has a section that displays projects you are "Following" or "My projects" (projects you created, I think?)

This feature is not working ☝️ 

**URL**
https://moped.austinmobility.io/moped

**What steps can we follow to reproduce the bug you are seeing?**
1. Create a project.
2. From the project summary, verify you are following the project - the bookmark icon in the top right should be filled. 
3. Navigate to the Dashboard page
4. Your project should be listed there, but it is not. 

**Screenshots**

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [X] Major — can only perform work using a workaround
- [ ] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Additional context**

**Comment by chiaberry** [comment]
"My projects" is projects you are a team member of

**Comment by mddilley** [comment]
This had to do with me removing the deprecated `status_id` columns from the DB - a couple queries for `project_notes` had that column in them still.

**Comment by mddilley** [comment]
Merged in with https://github.com/cityofaustin/atd-moped/pull/805, https://github.com/cityofaustin/atd-moped/pull/806, and https://github.com/cityofaustin/atd-moped/pull/807. Closing.
