### ISSUE TITLE
Create design prototype for components enhancements

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10347]
The latest design is available in [this branch](https://github.com/cityofaustin/atd-moped/pull/790) and this [deploy preview](https://deploy-preview-790--atd-moped-main.netlify.app/moped/dev/map).

#### Design todos
- Map overlays: draw tools, geocoder, basemap picker
- Render additional component properties in sidebar list
- Map hover states

#### Future
- collapsable sidebar

#### Summary of changes
- use fullscreen map/sidepar outside of the tabbed project context
- render all components on the map at all times
- separates component attribute editing vs map editing 
- adds map feature popups to help navigate b/t overlapping components

Component create - form

<img width="1512" alt="Screen Shot 2022-09-30 at 10 27 38 AM" src="https://user-images.githubusercontent.com/14793120/193292724-87bb1c3f-a4a8-4112-b524-5642a632d390.png">

Component create - line selection. Not pictured: draw tools, basemap picker, geocoder

<img width="1512" alt="Screen Shot 2022-09-30 at 10 28 02 AM" src="https://user-images.githubusercontent.com/14793120/193292742-9324a800-398a-433b-ba83-0bf407afe8b1.png">

Point component create

<img width="1512" alt="Screen Shot 2022-09-30 at 10 29 38 AM" src="https://user-images.githubusercontent.com/14793120/193292739-fd0a2363-2d81-4b1b-bcb8-7739161e2843.png">

Component focus state

<img width="1512" alt="Screen Shot 2022-09-30 at 10 30 20 AM" src="https://user-images.githubusercontent.com/14793120/193292734-7320c3f4-5f2a-4170-905f-8a9c83696416.png">

Popup displayed from feature click

<img width="1512" alt="Screen Shot 2022-09-30 at 10 30 12 AM" src="https://user-images.githubusercontent.com/14793120/193292736-47ec843b-8258-4abf-b12a-74c91e30c3ce.png">

Component delete confirmation

<img width="1512" alt="Screen Shot 2022-09-30 at 10 30 28 AM" src="https://user-images.githubusercontent.com/14793120/193292731-22d36932-3b2e-4e49-b557-76d565b9137c.png">

**Comment by patrickm02L** [comment]
This is looking really nice. I'm loving the functionality and new set up. A few nit-picky spacing and hierarchy things, but I'm pretty okay with 95% of where this is headed!
