### ISSUE TITLE
[Spike] Review and estimate components enhancements

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10359]
Review the proposed changes to project components (#10347), and develop an implementation plan with respect to (1) our existing components codebase, (2) the code in the enhancements prototype (PR [#790](https://github.com/cityofaustin/atd-moped/pull/790)), and (3) the upcoming DB changes (#9930).

**Comment by mddilley** [comment]
- [ ]  Update component form with React Hook Form
- [x]  Combine `ProjectStatusBadge` and `ProjectStatusBadgeFake` (didn’t check to see if there are changes here or not)
- [ ]  Troubleshoot clipped features
    - [ ]  need to grab feature from AGOL not from Mapbox
    - [x]  Find an example and compare ID to source layer
    - [x]  [https://gis.stackexchange.com/questions/232757/mapbox-gl-js-splitting-tileset-polygons](https://gis.stackexchange.com/questions/232757/mapbox-gl-js-splitting-tileset-polygons) One large vector tile?
- [ ]  Draw tools - port over draw tools but build create/edit/save from the ground up to remove all of the leftover pieces from `react-map-gl-draw`
- [ ]  Speed dial base layer select (finish out styling for all viewport sizes)
- [ ]  Add Geocoder (can be pulled straight from existing code)
- [ ]  Consume updated DB data
- [ ]  Manage dynamic interactive layer IDs
    - [ ]  Need to think about serving them up in the right order

**Comment by johnclary** [comment]
thanks @mddilley! i've transferred all of this to individual issues.
