### ISSUE TITLE
Renew TLS certificates for mobility.austin.gov and visionzero.austin.gov

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10363]
The wildcard certs for these subdomains will expire on 10/27/2022:

- `*.mobility.austin.gov`
- `*.visionzero.austin.gov`

This affects the following sites:

- [x] mobile-signals.mobility.austin.gov
- [x] data.mobility.austin.gov
- [x] mobility.austin.gov (moped)
- [x] micro.mobility.austin.gov
- [x] visionzero.austin.gov/viewer
- [x] visionzero.austin.gov/editor

Todo:
- [x] Provide CTM Linux with new CSRs
- [x] Wait to hear back from CTM Linux
- [x] Receive link to download the certs from Entrust
- [x] Install the certificates

**Comment by johnclary** [comment]
I sent the new CSRs to CTM Linux and cc'd @chiaberry and @frankhereford.

**Comment by johnclary** [comment]
Jason G. responded. The certs were missing the common name. I regenerated them and sent them back to Jason.

Next step: Jason submits them to our cert provider (Entrust) and we'll get an email:
> I'll submit them and you'll receive the Entrust emails with the renewal pickup link.

**Comment by johnclary** [comment]
@frankhereford will take on VZ; @johnclary will take on mobility.austin.gov

**Comment by johnclary** [comment]
@johnclary make sure you store the new certs and CSR in 1pass

**Comment by frankhereford** [comment]
PEM Files: When picking up the cert from the link in the email, I chose "other" as my server type. They mean to offer you a list of certificate formats, but they instead offer you a list of web-servers. PEM is super generic, so I went with other. Apache on linux or NGINX would also probably get you the right format.

Netlify: Site → Domain Mgmt → HTTPS → Provide your own certificate

⚠️ But I run into this issue: 

![error](https://user-images.githubusercontent.com/3653206/197234637-35c98633-4529-4363-a5cf-833e1b184a1b.png)

@johnclary Is it possible at all that you generated a second CSR and the key in our password manager is from the first one? I'm grasping at straws at what would cause this. The next thing I'd do is drop the key and cert into a file and spin it up in a haproxy install on a docker container or wherever to see if it parses there. Should I do that?

**Comment by johnclary** [comment]
👍 I've updated the keys in our password manager for these two certs.

**Comment by johnclary** [comment]
I've updated the issue description with the list of sites that are impacted. I have made all of the necessary changes for `*.mobility.austin.gov`. This entailed importing the certs + key to Netlify for all sites, as well as updating the cert manager in AWS for Moped resources. It took ~5 minutes for [Moped prod](https://mobility.austin.gov/moped/projects) to reflect the change ✅ 

<img width="554" alt="Screen Shot 2022-10-21 at 2 27 57 PM" src="https://user-images.githubusercontent.com/14793120/197265079-674c5b4a-98a5-47a5-94f4-b543788c40ac.png">

**Comment by frankhereford** [comment]
Looks like the `VZ[EV]` is cooking with gas now too.

![image](https://user-images.githubusercontent.com/3653206/197270282-590d3ac4-e105-4f51-b02c-9dcbf5aad364.png)


John, I'll let you close this one, but I think we're at the finish line 🏇

**Comment by johnclary** [comment]
gooood stuff. thanks @frankhereford!
