### ISSUE TITLE
Update TURP Row Usage Fees for Alley (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10365]
### RW-TURP ROW Usage Fee for Alleys - Update Amount

<img width="444" alt="Screen Shot 2022-09-30 at 3 45 27 PM" src="https://user-images.githubusercontent.com/49930868/193353594-cee59d96-ee1a-4c8e-913e-78d64ff53756.png">

<img width="1270" alt="Screen Shot 2022-09-30 at 3 43 52 PM" src="https://user-images.githubusercontent.com/49930868/193353456-74e55dc9-5c9d-4894-a988-1b5ccbd2adb5.png">

**Comment by Nadin-Nader** [comment]
This was completed by Priya for FY23

**Comment by TracyLinder** [comment]
This is complete.
