### ISSUE TITLE
[MEETING] DTS App Service Offerings Presentations

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10376]
### Objective 
Get slide [deck](https://docs.google.com/presentation/d/11v3HoSXkWwZFCJBxdwO_XC9UhpGzqmaxsCrYcWWXumg/edit#slide=id.g16011fa1857_0_720) drafted for end of Oct/early Nov presentations for ATD employees

### Participants
Karo, Chrispin, Diana

------
- [x] Schedule meeting
- [x] Optional: Schedule debrief
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by ChrispinP** [comment]
Updated Google Slides for presentation, updated Google Doc, created MS Form for presentation survey, added Poll questions to both meeting invites, and added important links in the meetings as well.

**Comment by KaroEngstrom** [comment]
# Notes F 11/4/22

- Follow-up emails sent as follows: 
     - PM Session general follow-up Th 11/3/22
     - PM Session specific follow-up with Bookings/Power BI resources to two participants Th 11/3/22 
     - AM Session general follow-up F 11/4/22 
- Attendance: 
    - PM Session W 11/2/22: 9 
    - AM Session F 11/4/22: 10

[More details in the planning doc](https://docs.google.com/document/d/1GL4DyQJhvTvsMNgIrZdSSLWokO2ys-4wOHydfekEdAs/edit)

**Comment by ChrispinP** [comment]
closing meeting issue
