### ISSUE TITLE
City Data Hub - Data Clean Up for Migration - Division Review  

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10380]
Earlier issue: #10317

# City Data Hub Data Clean Up - issue 2 

Looking for datasets that we definitely need to keep and flag for script connections, got the following resources from Chia: 
- [ATD Airflow Scripts ](https://github.com/cityofaustin/atd-airflow/tree/master/dags/bash_scripts)
- [knack.py](https://github.com/cityofaustin/atd-knack-services/blob/production/services/config/knack.py)

**W 10/5/22**
- [x] Mark knack.py items as Approved in the tracker 

**F 10/7/22**
- [ ] Look at Deprecated Assets [here](https://cityofaustin.sharepoint.com/:x:/r/sites/CTM/TEAMSITES/WEB/_layouts/15/Doc.aspx?sourcedoc=%7BB668D4FD-5BCB-40F6-8DAC-213B15C9839A%7D&file=Asset%20Audit%20to%20Resolve%20-%20%20Austin%20Transportation.xlsx&action=default&mobileredirect=true) to examine what needs to be updated/what exists elsewhere

**Comment by KaroEngstrom** [comment]
## Sat 10/15/22 

Emailed CTM's City Data Hub project lead with these questions from the week: 

![image](https://user-images.githubusercontent.com/100615928/195991791-973974e2-feca-48fc-91b1-8a154678de0a.png)

**Comment by KaroEngstrom** [comment]
## W 11/19/22 and Th 10/20/22

- [x] Send out emails to 11 workgroups/division with links to worksheets [in SharePoint here](https://cityofaustin.sharepoint.com/sites/atdDTS/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FatdDTS%2FShared%20Documents%2FCity%20Data%20Hub%20Migration%20%2D%20Division%20Worksheets&viewid=2958c37f%2Dbe1b%2D4ca8%2Db045%2Ddc17d145a4ba)
- [ ] Email DTS team members for the small number of data items for Parking and for DTS

**Comment by johnclary** [comment]
@KaroEngstrom as we discussed, [here](https://github.com/cityofaustin/atd-data-tech/files/9890567/atd_open_data.csv) is a list of datasets owned by our admin user.

It looks like CTM overlooked a few of our datasets. For example (there may be more):
- Real-Time Road Conditions
- Shared Mobility Trips
- Mobility Management Center Activities

If CTM needs to know, I queried this data using this endpoint: `http://api.us.socrata.com/api/catalog/v1?for_user=8t3r-wq64`

And here's a script in case someone wants to generate the CSV again

```python
import csv
import requests

keys = ["id", "name", "contact_email", "type", "updatedAt", "createdAt", "page_views", "download_count", "publication_date"]
endpoint = "http://api.us.socrata.com/api/catalog/v1?for_user=8t3r-wq64"

res = requests.get(endpoint)
data = res.json()["results"]
rows = [{key: row["resource"][key] for key in keys} for row in data]

with open("atd_open_data.csv", "w") as fout:
    writer = csv.DictWriter(fout, fieldnames=keys)
    writer.writeheader()
    writer.writerows(rows)
```

**Comment by KaroEngstrom** [comment]
Initial responses gathered from all; following up where needed and moving to #10661
