### ISSUE TITLE
HR Digital SSPR Demo discussion

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10382]
Just checking in with you two, and wanted to give you notice on the status of the executive SSPR buy-in. I know we meet tomorrow but wanted to get this info “out there”. 

Anthony agrees on ATD taking the approach of the SSPR through Knack, however he would like a demo prior to a demo provided to the executive team next week on Monday 10/10. He hopes we can provide the executive demo within a 20-minute timeframe. 

I know the three us discussed possibly having a video of the process, is this still an option? Any way we do it, I’d hope to have a couple practice demos prior to Anthony’s view. 

Let’s discuss this tomorrow at 11.

**Comment by dianamartin** [comment]
# Notes 10/4
- Jennifer said she talked to Anthony and he's on board with the SSPR project on Knack
- He's requested a demo, we scheduled it for 10/6
  - Jennifer & Hannah will demo
  - Stephanie and I attend as support
- On 10/10 Executive Meeting, Jennifer & Hannah will demo
  - Stephanie and I attend as support

## Action Items
- Need to configure the rest of the Division pages #9687 before Monday 10/10

**Comment by moorerst** [comment]
Requested by Jennifer W
Prior to 10:45 a.m. on 10/10. 
- [ ] Remove the following SSPRs: 
ID: 57
ID: 60
ID: 61

- Not sure if this can be done in time, but I noticed a miss. In the Planning meeting I added “Development Plans” that did not copy over to Mid-Year & EOY. 

- [ ] Can we add a copy feature like we have for the priorities? 
- [ ] Or can they just auto pull over? The development plans can be modified throughout the year but mostly will stay the same. 

- These can be done later: 

Help guide: SSPR Statuses 
[https://atd-dts.gitbook.io/human-resources-or-help-guides/sspr-statuses](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fatd-dts.gitbook.io%2Fhuman-resources-or-help-guides%2Fsspr-statuses&data=05%7C01%7CStephanieC.Moorer%40austintexas.gov%7C596a69821e454d1771c908daaacab580%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638010084839578553%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BvYB0Vjr3RyM2Rx0H%2BQYr1D%2BsQ9ul7cYU3mGa9tZYdA%3D&reserved=0)

- [ ] 1st section “Planning”, do you think we should call it “Planning – In Review” to mirror the Mid-Year and EOY sections? 

- [ ] 2nd section says Planning Planning. Need to remove one of the “planning”

I am thinking about real life workflow and feel the system is a bit off when it comes to Mid-Year and Year-End.
Currently at Mid-Year the manager goes in and adds the comments and ratings. Once that is saved, it cannot be edited.  
A manager should have the ability to discuss this with the employee, and possibly alter a rating on the spot. 

Supposing a manager can have the comments and rating on another MS Word doc, then during the employee meeting they can copy and paste it over. But that is kind of defeating the purpose. 

- [ ] Or do we need another status? Maybe: Mid-Year, Work In Progress, where the manager can add the comments and ratings.

1.	After the Planning is Complete & Signed.
2.	Start with a Mid-Year, Work In Progress status.
3.	The Manager can do the work of adding all the notes and ratings.
4.	This should only be visible to the manager. But not have them submit or sign, so they can have the opportunity to view with employee. 
5.	In this Viewing Meeting, the employee can discuss their feedback with the manager and possibly a rating may change. 
6.	Then “Submit” to the Mid-Year Employee Meeting. 

Let me know if you have time to discuss this after the executive meeting.

**Comment by moorerst** [comment]
Questions from Executive demo
What would be the timeline to implement?
How will training be provided?
Will there be recorded training available?
How will support be handled while staff and supervisors are learning the system?
What reporting is available? Will we be able to provide the reporting data what central HR requires?

**Comment by dianamartin** [comment]
@moorerst we don't have anything else to do, right?

**Comment by moorerst** [comment]
This demo with the Executive team was successfully completed and a plan was put in place for moving forward with the rollout.
This issue is complete.
