### ISSUE TITLE
Update Info 'SIF District' (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10381]
### Users should not be able to enter their own value in info 'SIF District' on SIF folder. 

**Requested by:** Tracy

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder -  DEV DP submitted; kindly approve and create task id for me.

Commit ID: [893879efda48](http://coaamandadevops02.austintexas.gov/R5:893879efda48075f10c838bba8b49d08d1e01c29)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to DEV/TEST under **SCTASK0260204**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been deployed to DEV and TEST please UAT

**Comment by TracyLinder** [comment]
### UAT Notes

FYI @Sreelatha-BlazeKannan 

The system technically doesn't allow unique values, but it does allow the user to enter a value, so the system error message doesn't make sense. 

**Here's what's happening:**
1. User inputs unique value into info field & clicks save
2. The system throws error "Info field values required. See mandatory field."
3. The user will be confused because they **did** complete the mandatory fields. 

<img width="991" alt="Screenshot 2022-11-02 at 1 43 39 PM" src="https://user-images.githubusercontent.com/49930868/199576041-90cb5f92-821a-4fe9-b173-a6a49dccb947.png">

**Comment by TracyLinder** [comment]
### OK to promote to PROD

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder This has been sent to the DevOps CM Team to be deployed to **PROD** under **__SCTASK0261162__**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been deployed to PROD. Please have stakeholders UAT.

**Comment by Nadin-Nader** [comment]
Spoke to Nathan and he said that this is fixed:

[3:11 PM] Aubert, Nathan
Hey Nate, I believe both issues are fixed now.
