### ISSUE TITLE
Provide VZ 2022 Traffic Calming Projects Data

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#10394]
This data will need to be pulled from the most recent MOPED extracted data

**Comment by patrickm02L** [comment]
Is this a request from VZ?

**Comment by andrewshensky** [comment]
@patrickm02L it was a request from Joel to receive traffic calming project data that TED had added to MOPED. We had recently pulled an extract from MOPED, so I was able to provide that data in the format they were looking for.
