### ISSUE TITLE
SMO P3 Pilot period

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10398]
Follow up with Kirk and Kat about how the P3 application is working, if they need any assistance, and/or improvements.

**Comment by KaroEngstrom** [comment]
### W 10/5/22 

- Messaged Kat and Kirk to check on any further reporting items or further immediate needs 

- [ ] Check on them during the next sprint to close this out; anything following that would be considered an enhancement request

**Comment by KaroEngstrom** [comment]
## F 10/14/22

- Kat contacted us with concern about notification not coming to reviewer and panelists, and some strange behavior for reviewer functionality 
- I responded via email with screenshots and overview of the process flow after reviewing the test cases (there was confusion between the Send for Review and Submit a Review forms for the Executive Review) 
- there were still issues so I did a full test of the automated steps from EOI submittal to the BCA Approval. No issues were found. 
- I did a short test/review call with Kat and she was able to explain where she was running into issues. We did troubleshooting together and could tell from Knack audit logs that another one of her users had made an error in testing, resulting in her now seeing strange behavior. 
- We decided to include Kat as a CC on the requests going out for now (both for Executive Review and Evaluation Panel) - this was she can "shadow" the process and train her users better as well as see if any edits are needed to the language in those automated emails 
- I reversed the user error in Knack, deleted all test records, added Kat as a CC: and returned all emails from testing back to SMO recipients 
- I emailed Kat with the details of the email flow and other note from our meeting. 
- I doublechecked the page permissions to ensure smooth testing next week
- P3 will be testing starting M 10/17/22
- I will check in with them as planned at the end of the month for any lingering items before official go-live at the end of the pilot period. 

cc: @dianamartin

**Comment by patrickm02L** [comment]
Perhaps the buttons should indicate Panel versus Executive? "Send to Review Panel" "Send for Executive Review"

> I responded via email with screenshots and overview of the process flow after reviewing the test cases (there was confusion between the Send for Review and Submit a Review forms for the Executive Review)

**Comment by patrickm02L** [comment]
Check back in with P3 folks Monday, 10/31/22.

**Comment by KaroEngstrom** [comment]
## M 10/31/22 

- Emailed the stakeholders to see how the pilot period was rounding out

**Comment by KaroEngstrom** [comment]
## T 11/1/22

Response from Kat: 
"Thanks for the follow up! So far everything has been working well. No feedback from the team, which means everything is running smoothly. Will reach out if anything pops up. And as always, thanks so much for putting this application together for us!"
