### ISSUE TITLE
Identify new wiki tool

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1039]
Our documentation needs have outgrown Github wikis, so let's identify a new tool. This is most pressing with regards to consolidating our Knack repos #1038 as they have extensive documentation that would make for either a very unwieldy Github wiki sidebar or a pain-to-maintain table of contents.

**Comment by dianamartin** [comment]
Read articles about: [Comparison of wikis](https://www.perforce.com/blog/vcs/comparison-of-git-powered-wikis-in-cloud-based-scm-tools)
**Helix TeamHub
GitLab
BitBucket**
[Matterwiki](http://matterwiki.com/) - was able to log into a demo environment
[Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) - looks pretty nice, not sure the level of effort in setting up.

**Comment by amenity** [comment]
@sergiogcx shared [this helpful wiki-comparison website](https://www.wikimatrix.org/). It has a cool [wizard](https://www.wikimatrix.org/wizard) you can use to narrow down options by features, programming language, file storage format, etc. 

@johnclary @mateoclarke - do you have any parameters from a technical perspective you'd like to see in a solution? Should we be restricting the options to hosted services given that we've got plenty of software to maintain already? 

As far as requirements, the ones that matter the most to me are:
- Revision history
- Ease of use for an end user
    - Menus and navigation
    - Mobile experience
- Ease of use for editors
    - Basic text formatting
    - Media handling
    - Organization/menus

Also, data exportability... That's why we opted not to use Gitbook. What type of export format would you want to see, @mateoclarke?

**Comment by amenity** [comment]
Also, [here is a relevant thread from our Slack](https://austininnovation.slack.com/archives/CCUPS4GBX/p1573075692008400).

**Comment by amenity** [comment]
@dianamartin thanks for your work on this — great finds. I reviewed them and recommend we try out [MkDocs](https://www.mkdocs.org/) with the sharp [Material theme](https://squidfunk.github.io/mkdocs-material/) that you found:
- Docs maintained as Markdown files so they're very portable
- Static site — loads quickly and can be hosted anywhere including Github pages
- [MKDocs repo](https://github.com/mkdocs/mkdocs/) and [Material for MkDocs repo](https://github.com/squidfunk/mkdocs-material) are actively maintained open source projects
- Built with Python 🐍💚

Spoke with @mateoclarke about possibly doing this on Discovery Day — maybe a project for @sergiogcx or @mddilley.

**Comment by johnclary** [comment]
OK, code for our new MKDocs wiki is here: https://github.com/cityofaustin/atd-wiki

and hosted here: https://wiki.austinmobility.io/

@dianamartin @amenity do we need to do further testing/discussing before we decided to move ahead with this solution?

**Comment by dianamartin** [comment]
@johnclary I thought we needed to test sub nested pages on the left navigation panel.

**Comment by johnclary** [comment]
@dianamartin yes. here's an example: https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml#L16

That's the config for this page: https://www.mkdocs.org/user-guide/writing-your-docs/

**Comment by dianamartin** [comment]
@johnclary Yeah, I ended up reading that in the MK Documentation

**Comment by johnclary** [comment]
@dianamartin I agree we need to make it easier to edit. Serving locally, branching from prod, merging to master, merging to prod... it's a lot of steps.

**Comment by amenity** [comment]
Bummmer... We definitely want a good editor experience, but I could see a self-hosted solution eating up too much precious dev time. I think it's worth revisiting Gitbook and have inquired with them about getting  a free subscription. 

@mateoclarke expressed concern that Gitbook is not pure Markdown and would be hard to export. We definitely don't want to trap our docs somewhere.  

@dianamartin - would you make a few demo pages using [the Github integration](https://docs.gitbook.com/integrations/github) so we can see how much things deviate from standard Markdown and what an export would look like?

**Comment by amenity** [comment]
@mateoclarke @johnclary - also would be great to get your thoughts on [Bookstack](https://www.bookstackapp.com/) — this was @dianamartin's top pick among the open-source options.

**Comment by dianamartin** [comment]
@johnclary @mateoclarke @amenity 

This the test repo I made that is integrated with GitBook and GitHub. I had copied a .md file from data-tech and sync'd it with this new repo i made. 

### [wiki page](https://github.com/dianamartin/DTS-wiki)
This is what the .md file from GitBook looks like, there are differences but not major. 

Edit page of wiki: https://github.com/dianamartin/DTS-wiki/edit/master/README.md

**Comment by amenity** [comment]
Thanks, @dianamartin. How was the editing experience? Would this be a good solution for you?

I started the application for a free "open-source" account yesterday, just need to send them a few more things if we want to move forward.

**Comment by amenity** [comment]
Per @johnclary via Slack:

**Comment by amenity** [comment]
I created a DTS GitBook organization to complete our request for a free account. Waiting to hear back from them on that. 

While I was at it, I imported our ATD Data Tech wiki here: https://atd-data-and-technology-services.gitbook.io/austin-transportation-data-and-technology-services/

With the default Github/Gitbook integration, it saves everything as Markdown files in the repo root, e.g. https://github.com/cityofaustin/atd-data-tech/blob/master/docker.md or, if nested, in a subdirectory like https://github.com/cityofaustin/atd-data-tech/tree/master/knack-application-overview. 

@dianamartin @johnclary @mateoclarke, sent you links to mess around with writing and administration if you'd like to try it out. LMK what y'all think.

**Comment by dianamartin** [comment]
@amenity  overall feedback

- I added a Group page so that we can have sub pages to see what that was like
- Adding a screen shot was pretty painless, you can upload an image. However you can't just copy and paste it. The image has to be saved on the computer. 
- Now I have to track down where GitBook saved this on our GitHub repo. It's saved in the gitbook/assets file path and shows up after you merge your edits. 
- Editing the wiki page seems pretty intuitive as well, there's a nice GUI for users

We're planning on having a separate one for Knack App Wiki's correct?

**Comment by amenity** [comment]
Everyone is on board to move forward with Gitbook and I just got word we have been promoted to a free account. Onward 🚀 📚
