### ISSUE TITLE
V7 FY23 Bug: RW TURP not calculating the TURP 1st (50315) and 2nd Traffic Lane fee (50317) correctly

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#10417]
RW TURP not calculating the TURP 1st (50315) and 2nd Traffic Lane fee (50317) correctly. On the first, It charged $169.40 and it was supposed to be $184.80. LaTonya was able to update the amount manually to reflect the correct amount to be charged.

ROWID: 13024953
User: LaTonya A.
Folder: RW TURP

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/4a7b1703-e6db-41d0-91b0-b70291ee4649)

On the 2nd Traffic Lane,  it was supposed to charge $2,928, but it is charging $2,684
Row ID
13009464
The fee code = 50317

**Comment by SubhaShroff** [comment]
@Nadin-Nader  As you gave me info on 2n Traffic Lane fees also not calculating correctly. LaTonya's info as follows:
Row ID: 13009464 (PROD)
The fee code is 50317; it is supposed to charge $2,928, but it is charging $2,684

Working on it.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  All the TURP ROW usage fees are fixed. It should be good on PROD now.

**Comment by Nadin-Nader** [comment]
According to LaTonya, this has been fixed.
