### ISSUE TITLE
Info Tab Bugs on RW-Parking-Load/Unload (Ready for UAT on PROD in Friday Meeting)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10439]
### Infos Missing / Random infos inserted

**Acceptance Criteria** 

- The Acceptance Criteria mentioned below applies only to RW - Parking folders. 
- When the folder is created, the info field 'Rate if metered (in $ Hourly meter rate); is missing in the Folder Info tab 
- Since this info is needed to calculate fees, this is a major bug that needs fixed immediately. 
- Test folder that was created to verify in A7 Prod - Reference number 2022-151028 RW.

**Comment by TracyLinder** [comment]
@vschandramouli can you please work with Tantanisha on this? Ideally before next Wednesday 10/12/22.

**Comment by vschandramouli** [comment]
Updated AC. Moving to Backlog @TracyLinder @Nadin-Nader

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Prod , info is present in the info tab . Attached screenshot for reference

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/f0f73449-afcd-4329-9635-ac853151ea11)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader The info is not set to be visible for portal folders , will fix and commit.

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/03d9c258-f775-4b0a-9750-3894b795e306)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test, the info is available for portal folders .

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created Prod promotion request - SCTASK0257611

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes are promoted to Prod . Could you please confirm with the User. This info will be available for new folders created through portal.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT lets go ahead and revert the commit to remove the info from Portal

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader The commit has been reverted in Dev , Test and Prod

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes promoted to Prod

**Comment by Nadin-Nader** [comment]
Sent message on TEAMS "on PROD" Chanel to Paloma, Kim, Isabel and LaTonya. Waiting on response

**Comment by Nadin-Nader** [comment]
Paloma is notifying Jonathan that this is on PROD and we are closing
