### ISSUE TITLE
Ability to add infos to Info Tab for ROW Permit Folders (On Prod, Waiting on UAT Results)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10441]
### Update security groups to allow insert of folder infos for Streets & Spaces (DS, RW, EX, PSM, SB)

**Comment by Nadin-Nader** [comment]
Jenice Reach out and said she made the change on DEV, TEST and PROD. I asked Kim to test this and let me know the outcome.

**Comment by Nadin-Nader** [comment]
This has been resolved
