### ISSUE TITLE
Log in issues - Data Tracker: Jamie A. 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1045]
Jamie A.
AMD

Email
>When I try to log on to Data Tracker keeps giving me undefined error.  Is the website down.

John asked me to follow up.

**Comment by dianamartin** [comment]
Undefined error message

![image](https://user-images.githubusercontent.com/21112975/71105099-8f306500-2182-11ea-90ee-e214deefb133.png)

**Comment by dianamartin** [comment]
Sergio said
>After Diana and I spoke to Jamie and checked out his computer, it seems that it is an account-specific issue that only affects Chrome. FireFox logs in just fine.

We tried Chrome with a clear cache with no luck, then we tried incognito with no plugins and no dice. So it seems only his account is affecting chrome for some reason.

**Comment by dianamartin** [comment]
@sergiogcx @johnclary 
I went back with John's suggestion of him trying a different computer. I had Jamie sign into my laptop, access the data.mobility URL and sign in using COACD. That worked. 

I also check his version of Chrome on his desktop, 77, I checked mine on my laptop, 78. We got Scott to update Chrome on the desktop, it was updated to 79. Also tried resetting Chrome settings. Tried the data.mobility URL and sign in using COACD. Back to "undefined" error. 

Not sure what else to do here.

**Comment by dianamartin** [comment]
Scott came up with a few more recommendations:

- [ ] Try going into the credential manager and deleting any saved password in there for Chrome or that web site.
- [ ] We also may need to reinstall Java

**Comment by dianamartin** [comment]
Jamie emailed saying that he tried what Scott suggested and still not working
> I did all that Scott asked me to do but still giving same error.

**Comment by dianamartin** [comment]
Scott emailed
>I logged into your pc and was able to open up the equipment tracker. It appears your profile is corrupt. 
I copied your desktop, documents, downloads, videos, IE favorites and picture folders to my profile to restore to your profile.

>We should delete your profile and see if that corrects the problem.

I also logged into Jamie's computer to see if it was his computer that had the issue. I was able to log in using the COACD button. Scott suspects it to be a profile issue.

**Comment by amenity** [comment]
@dianamartin - do we have any new info on this?

**Comment by dianamartin** [comment]
@amenity I talked to him today, but not about this. He's supposed to get back to me tomorrow, so I'll ask him about this.

**Comment by dianamartin** [comment]
Jamie has confirmed he's still using the link we gave him as a work around. Will need to have him try again to see if this issue still persists.

**Comment by dianamartin** [comment]
Checked with Jamie and he tried the data tracker link in Chrome has is still getting the error "undefined". He is able to open it up in Firefox and when using the direct Knack AMD URL he's able to open it in Chrome. 

Still not sure why he's getting weird issues, but he's able to log in and do his work.
