### ISSUE TITLE
Artbox Program - Create Directory

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10453]
## M 10/10/22 Sprint Review Notes

Directory planning - build out based on Sandra's existing spreadsheet 
- OBJECT - `organization` - connect to contacts
Organization Name
(everything from the application)
- ACCOUNT OBJECT (non-active) - `contact` - connect to organization - TBD
- ACCOUNT OBJECT (non-active) - `artist` - 30+
- foresee a need to have artists to have account
Artist Name
Artist Instagram Account
Access to Knack down the line in some limited way to engage and submit items 

@dianamartin - we have connections listed to projects (`application` in our system). 
- how we want to add these historically? 
- the only identifiers are intersections - do we want to show/connect some kind of location? 

Sandra will send a spreadsheet 

Debrief 

- 'signal ID' object - connect to 'artist'
- pull signal from AMD Data Tracker (borrowing data from DT) 
- also have GIS map in AGOL - pull this from the GIS Team / get tabular data from there 
- locations / signal association and signal / cabinet association but NO location / cabinet connection (cabinets have their own points in Knack)

**Comment by KaroEngstrom** [comment]
## 10/16/22

- Creating a new issue for the Location item since that's a bigger conversation and needs scoping

**Comment by KaroEngstrom** [comment]
# 10/16/22

- [x] Add `placemaking_organization` object and add current art partners/ sponsors
- [ ] Add a Placemaking Contact account object (with dummy accounts for now) - Artist or Art Partner Representative identified by Contact Type [this directory and account type can be used for anything Placemaking in the future]

**Comment by patrickm02L** [comment]
On 11/02/22, we reviewed the directory, and Karo let us know that Sandra is making use of the Directory.
