### ISSUE TITLE
[TDS-TIA] Tech Debt: Remove or Refactor TIA Communication comments feature

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#10456]
After a year this feature is also not being utilized by Reviewers. Need to determine if it needs to be modified or removed.

**Comment by TracyLinder** [comment]
![Screen Shot 2022-10-12 at 1.40.57 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/22b7edfc-20f0-423d-beec-2d036c435713)

**Comment by TracyLinder** [comment]
We need to confirm w/ stakeholders that it's ok to remove this, and then put it on deck.

**Comment by TracyLinder** [comment]
We need to discuss w/ stakeholders

**Comment by TracyLinder** [comment]
Nathan A. thinks this feature would be useful if used. He will discuss with his team.

**Comment by ChrispinP** [comment]
After 2 years, this feature is still not being used. I have removed the feature from maintainability and updated the menu.

Complete, closing
