### ISSUE TITLE
GF Bug: Remove mandatory flag on COS infos (LP) (On Prod)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10467]
### The only COS info that should be mandatory on GF is COS Partner Department. All others shouldn't be. Please remove flag. 

<img width="1133" alt="Screen Shot 2022-10-11 at 12 44 26 PM" src="https://user-images.githubusercontent.com/49930868/195162739-fa695e10-ed4e-40bb-aadd-9d2e80565df7.png">

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/a372c052-3dad-4804-9e66-c9cd0e826829)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test, Mandatory flags are removed. Ready for UAT

**Comment by Nadin-Nader** [comment]
Approved for PROD

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created prod promotion request - SCTASK0270949

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes are deployed to Prod. Verified and it looks good. Ready for Prod UAT.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Paloma verified in Prod and confirmed that it is working as expected
