### ISSUE TITLE
Update VZ dependencies

### ISSUE THREAD

**Issue by roseeichelmann** [cityofaustin/atd-data-tech#10461]
Currently, the VZ platform has 124 dependabot alerts, some of which can be resolved simply with version updates while others may need more specific attention. This issue aims to address some of these vulnerabilities by updating the dependencies.

**Comment by patrickm02L** [comment]
Discussed in planning 10/19, @roseeichelmann to copy the package JSON or link to show what's changed with the dependencies.

**Comment by roseeichelmann** [comment]
We have decided to change our course of action and instead start whittling down the security vulnerabilities with the dependabot alerts that have PRs associated with them and are ready/safe to merge rather than trying to update all of our dependencies in one branch which was causing breaking changes that were difficult to fix. This issue and associated PR will now be closed.
