### ISSUE TITLE
Migrate CCTV Image Thumbnail Service to AWS

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1046]
Migrate the CCTV image publication service from a Kimley-Horn managed server to DTS infrastructure.

Update: it's done.

- Repo: [cityofaustin/atd-cctv-images](https://github.com/cityofaustin/atd-cctv-images)
- Example image: [https://cctv.austinmobility.io/image/739.jpg](https://cctv.austinmobility.io/image/739.jpg).
- [Preview](https://brave-wozniak-4a02f0.netlify.app/traffic-cameras) of the Traffic Camera's dashboard
- [Gitbook docs](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/cctv-image-publishing)

**Comment by johnclary** [comment]
I'm told this actually needs to happen by 1/14. FYI @amenity.

**Comment by amenity** [comment]
@johnclary - gotcha. Should I go ahead and schedule a meeting with Lance &/or Ben in early January?

**Comment by johnclary** [comment]
it's actually the off-site kimley horn engineers (Chris E. and Cole R) that will help.

tasks are:
- get copy of CCTV code from Chris 
- sergio reviews
- ask question to KH if needed
- translate to python
- deploy on aws infrastructure

So i'll reach out to Chris about the script, and we can go from there.

**Comment by johnclary** [comment]
Waiting to hear back from Cole Roberts (Kimley-Horn). I am going to ask Jen if it's acceptable for this service to possibly be down for a few weeks while we stand up the new server. The old server has a hard turn-off date at 1/14.

**Comment by johnclary** [comment]
I have the a copy of Kimley-Horn's code for running this script. We need to prioritize this work. Proposing early October (2021 ;) )

**Comment by johnclary** [comment]
I've deployed the product version of this on our legacy script server. Documentation is in [this repo](https://github.com/cityofaustin/atd-cctv-images). I will be reviewing with the devs during skill share and then asking for a code review.

**Comment by johnclary** [comment]
The camera images have been live for two weeks. The URL path is `https://cctv.austinmobility.io/image/<camera-id>.jpg`. [Example](https://cctv.austinmobility.io/image/739.jpg).

And [here's a preview](https://brave-wozniak-4a02f0.netlify.app/traffic-cameras) of the Traffic Camera's dashboard with the images embedded.

**Comment by johnclary** [comment]
Done. I've added links in this issue description to code, documentation, etc.
