### ISSUE TITLE
Investigate what is capping number of concurrent Moped test instances

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#10472]
When deploying a test instances recently, I noticed that I was receiving an error about free IP addresses in one of the Moped test VPC subnets. Turns out AWS will not create a load balancer if there are not at least 8 free IP addresses in each subnet. This is not urgent since there is a workaround of just decommissioning enough test instances to be below 11 total.

It is the `moped-test-public-B` subnet that is dropping down to 7 free IP addresses when 11 test instances are deployed.

The task that fails in the flow: **Create EC2 Load Balancer**

The error:
>Error during execution of task: InvalidSubnetException('An error occurred (InvalidSubnet) when calling the CreateLoadBalancer operation: Not enough IP space available in subnet-0727661cc80bce49f. ELB requires at least 8 free IP addresses in each subnet.')

Some links:
- [https://stackoverflow.com/questions/55043151/8-free-ip-addresses-in-the-public-subnet-specified-for-aws-elastic-load-balancer](https://stackoverflow.com/questions/55043151/8-free-ip-addresses-in-the-public-subnet-specified-for-aws-elastic-load-balancer)
- [https://aws.amazon.com/premiumsupport/knowledge-center/subnet-insufficient-ips/](https://aws.amazon.com/premiumsupport/knowledge-center/subnet-insufficient-ips/)

**Comment by johnclary** [comment]
Closing because we have abandoned the prefect-based test deployments.
