### ISSUE TITLE
Officers can create VZA App accounts for themselves

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1047]
We need accounts for all the VZA enforcement officers so Randy can assign them shifts and, once officers start using the app, they can log in and record citations. 

After [speaking with Randy](https://docs.google.com/document/d/1En0t4a6yaT1-s5zQkMpR_gkrIELhjo1xEvnkQvNI7Pc/edit#) we learned that officers log into Revolution 911 on a regular basis to show that they are available for extra shifts like VZA enforcement.  We do not need to duplicate this "volunteer" functionality in our app, we just need to make sure that we have accounts for each officer. 

Before Randy starts using v1, he will send out an email to officers instructing them to log in to create accounts if they are planning to do any VZA shifts and as additional officers volunteer they will be sent to do so as well. 

We will need 

- [x] Add the following fields to Officer user accounts:
   - AP number
   - Phone Number
    - Call Sign
    - Unit #

- [x] Configure App so that officers can sign in themselves and create an account

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/b10a3355-c06a-43f5-8a4e-8c9b6198989e) 

Will Randy look at the newly created account and send an email with further instructions (I am not sure what those instructions are).

**Comment by SurbhiBakshi** [comment]
Should the "Need an account? and Sign Up" text be more prominient?

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/74c22350-9a56-4e3f-9b26-f839625b97c9)

**Comment by amenity** [comment]
@SurbhiBakshi - Looks good. I don't think it's a problem the sign up button is not very prominent — if so we can address it down the line. That said, if we can send a link to the Sign Up page directly that would be nice.
