### ISSUE TITLE
Assignments page improvements - Knack builder

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1048]
Since Randy and Lewis are using the app in different ways, we predict that they'll need different designs and functionality on the main Assignments page that they land on when they log in. Assignments page improvements with role-specific page rules.

- [x] Remove second page
- [x] Remove rich text header
- [x] Update Assignments table
     - Keep name "Assignments"
     - "Assignment Label" ---> "Assignment"
     - "No of Officers Required" ---> "Officers Required"
     - "Officer" ---> "Officers"
     - "APD Sector 1" ---> "Location"
     - "Assign Officers" ---> "Assign"
     - Hide Description 
- [x] Table for Assigner
     - Above Calendar
     - Hide "Edit" column
- [x] Calendar
      - Rename - "Assignments Calendar" ---> "Calendar"
      - "All" filter button is default and shows on the left
- [x] Table for Scheduler
     - Below Calendar
     - Hide "Assign" column

**Comment by SurbhiBakshi** [comment]
@amenity , check boxes working great, feel a sense of accomplishment after a very long day!

**Comment by SurbhiBakshi** [comment]
- [ ] Table for Assigner
- Above Calendar
- Hide "Edit" column
