### ISSUE TITLE
RPP Report - renewal notifications

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10494]
Can someone on your team please pull the email addresses for all residents in every zone except Orange? If it’s all one bulk that’s fine as long as there is a way for us to filter it on our end. We are preparing to send out an email notifying residents of the change from Knack to Passport. 
The folks at Passport is wanting us to begin sending the residents notification letters as early as this coming Monday, October 17th, at the latest.
Jacob is reviewing the draft so we are at your mercy with the email addresses. Just wanted to give you a hard deadline that we discussed sending them out. Let me know if there are any questions I can answer.

Report dates: 
Oct 2021 to current date

Zones: 
- [ ] pink
- [ ] green
- [ ] blue
- [ ] purple
- [ ] red
- [ ] teal
- [ ] gold

**Comment by moorerst** [comment]
I can direct them to the Advance Search /Search Permits but the results did not have email address. 
Email address is the primary information they want.
![image](https://user-images.githubusercontent.com/56606465/195659139-1c5cf42e-d3d4-44c7-9cfb-ceece8a6220d.png)

**Comment by moorerst** [comment]
Chrispin when you add your final comments can you include the amount of time spent generating the report. Thanks

**Comment by ChrispinP** [comment]
![image](https://user-images.githubusercontent.com/67915167/195958244-781c3110-2c12-4129-8887-741bb5bd3b1d.png)

Renewal List is ready to be sent, this takes just under 30 minutes to complete. Will email out the Excel file Monday morning.

**Comment by ChrispinP** [comment]
sent email to RPP, pending closure

**Comment by dianamartin** [comment]
Waiting for stakeholders to confirm everything is good, Stephanie will close with complete.

**Comment by moorerst** [comment]
confirmed with requestor that the report provided the information they needed. Closing issue
