### ISSUE TITLE
Configure Artbox Location 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10508]
Goal: add a standardized location identifier for Artbox cabinet in the Smart Mobility app / Artbox Program

### Per Artbox debrief M 10/10/22: 
- Artbox program is not currently tracking the signal location, just the intersection name (ex. Rundberg and North Lamar)
- Diana noted we should be using the 'signal ID' object for the project to connect to 'artist' object, etc. as needed 
- we would need to pull the signal data from AMD Data Tracker (borrowing data from DT)
- there also exists a GIS map in AGOL - could pull this from the GIS Team / get tabular data from there
- note on the data currently mapped in other apps: **locations / signal** association and **signal / cabinet** association but NO location / cabinet connection (cabinets have their own points in Knack)

Adding Diana and Patrick to this issue for next steps

**Comment by patrickm02L** [comment]
Thanks @KaroEngstrom! Let's talk about this at upcoming Sprint planning meeting on 10/19/22.

**Comment by patrickm02L** [comment]
Bring this up in 10/28/22 Placemaking Review.

**Comment by KaroEngstrom** [comment]
### W 11/16/22
- discussed this as our final step for the Artbox MVP 
- at application time, exact location is not confirmed and not always even proposed (just a neighborhood or council district) 
- Sandra as the Knack user can make the connection similarly to how she will connect Artist and Art Sponsor to a Project 
- Karo will check with Jeff at PIO to see what data was used for [the GIS map story shared on the website currently ](https://storymaps.arcgis.com/stories/9996d76ec50b439f967a734fc5ce7ac8)
- need to schedule DTS internal sync to discuss specifics:
   - what to connect to? (signal, location, cabinet?) 
   - download and upload to Knack - how to maintain 
   - other build concerns
 - need to schedule a follow-up with Sandra in a couple of weeks

**Comment by dianamartin** [comment]
## Image of Data Tracker, ArtBox (SMO App), and Public Web Map
- none of these names match at all
![image](https://user-images.githubusercontent.com/21112975/202499410-29e1cf11-ab69-4392-
be55-40b44ea70442.png)

**Comment by patrickm02L** [comment]
Next meeting with Sandra set for 12/5/22.

**Comment by KaroEngstrom** [comment]
## T 1/29/22 
- synced with Diana yesterday: she has discussed this with Brian C/AMD and  the agreement was that this new Artbox solutions should connect to the AMD asset (Signal ID) 
- creating a connected issue here for the dev side to determine if there is a way to automatically push that Signal ID information into the SMO app from AMD

**Comment by KaroEngstrom** [comment]
## T 12/6/22 

Per the connected issue: 
- [x] Add Signals object into Artbox/SMO 
- [ ] Update link to new Signals object in Artbox 
- [ ] Do we need the Cabinets object?

**Comment by dianamartin** [comment]
@patrickm02L Karo has updated the information you requested and it's stored in 1password for safe keeping. 

Next Steps: 
- [ ] Schedule with Devs

**Comment by patrickm02L** [comment]
Email Sandra to find out who she interfaces with about the cabinets. Included Billy B.(who should be the contact) so he chime in.

**Comment by KaroEngstrom** [comment]
**W 12/14/22**
- emailed Sandra

**Comment by KaroEngstrom** [comment]
## W 1/18/23
- apps grooming: Patrick reported dev team has completed dev automation; need to spot-check in the app
- Karo checked multiple records in the `signals` object and saw recent updates by API (= success)

@dianamartin @patrickm02L 
Do you want to do a meeting with the stakeholder or have me add that quick functionality to edit project name and then reach out to her via email about both of these items (automated updates to signal locations and ability to edit project name)?

**Comment by dianamartin** [comment]
@KaroEngstrom cc: @patrickm02L I think that's fine, I don't think it needs a super formal meeting. Thoughts?

**Comment by KaroEngstrom** [comment]
Folding this small item here because it completes our work as far as it's been planned: 
- added Edit Project Name button to a pop-up to modify the project name; this allows the user to correct the intersection name as needed (1/18/23)
![image](https://user-images.githubusercontent.com/100615928/213291481-248e8723-ec0a-4573-8213-20d53d0166f3.png)

**Comment by patrickm02L** [comment]
> @dianamartin @patrickm02L Do you want to do a meeting with the stakeholder or have me add that quick functionality to edit project name and then reach out to her via email about both of these items (automated updates to signal locations and ability to edit project name)?

I think and email or Teams chat would do. 

Does editing the title change the geo-location of the project? If the name of the title is changed, should the location be in another place for reference?

**Comment by KaroEngstrom** [comment]
Agreed, I think an email would work as all the functionality should be familiar to the user. I can draft that up for your review. 
 
 **Editing the title does not change the location**, and I think this will be good to document and explain to the user(s).
 - each `artbox_application` records a **Location Submitted by Applicant** field, and that text pushes into the **Editable Name Field to Display** short text. The applicant submits the information in response to the following question, so the expected input is either that of _street_ and _street_ , _neighborhood name_,  or _council district number_
![image](https://user-images.githubusercontent.com/100615928/213349969-6e9308b0-d691-47e5-b6a7-0f79fa87e199.png)
 - the display name for the project is a text formula that combines an autoincrement project ID (highlighted in yellow in the example) and the editable name field (highlighted in green).
![image](https://user-images.githubusercontent.com/100615928/213349221-7d88fef8-4fe1-4d82-bf56-6c3bf5296d1e.png)
- the user cannot edit the autoincrement project ID number (yellow) but can edit/correct the editable display name (green). This edit will automatically update the non-numeric portion of the project's display name. 
- each project will be manually connected to a `location` object that corresponds to AMD's `signal` and updates automatically from Data Tracker. The user cannot edit the records in the `location` object, only connect or disconnect the Artbox project and its Location/Signal. 
![image](https://user-images.githubusercontent.com/100615928/213349718-746f28ea-5b6d-4879-872b-2c68c980dbb4.png)

**MIRO VISUAL** 

![image](https://user-images.githubusercontent.com/100615928/213352195-4592b571-27aa-46b2-a23a-d35a54d7d7fd.png)

**Comment by KaroEngstrom** [comment]
M 1/23/23 

- [ ] Draft letter to stakeholder about completed initial build for the Artbox application 
- [ ] Ask for clarification on the Signal automation (should be a repeat process, not a one-time upload) #10884
