### ISSUE TITLE
Valet Operating Fees - Update & Bugs (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10506]
### Create a new fee & add to fee run procedure: 'Valet Renewal Operating Permit Fee’ at $295 
- Fee must insert with ATD Tech Surcharge
- GL code 5610 2400 9200 4094

**Comment by TracyLinder** [comment]
**From Paloma:**

Valet Parking Application Fee = 50180 = "Annual Valet Operating Fee" = $295 (FY 22 amount of $250)

**Comment by TracyLinder** [comment]
Subha & I will meet to do further scoping & AC.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  I sent the demo video in email for this ticket. I could add it here in the ticket as well. Please review and let me know your feedback. Thanks.

https://user-images.githubusercontent.com/51680715/196545963-7029e8bc-ec24-4fbb-b450-a88342a8dd4b.mp4

**Comment by Nadin-Nader** [comment]
@SubhaShroff  looks good. send it

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0258847 is raised for DEV deployment request. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This is deployed in DEV and I tested for the following folder, it looks as expected. Please review and let me know if I should raise TEST deployment request. Thanks.
![image](https://user-images.githubusercontent.com/51680715/199336721-25fc3159-14e8-4728-a229-ea5bec242363.png)

**Comment by Nadin-Nader** [comment]
@SubhaShroff this looks good. please promote to TEST

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0260891 Is submitted for TEST deployment. Thanks.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to TEST. Please UAT

**Comment by SubhaShroff** [comment]
Hi @Nadin-Nader  @TracyLinder  this one I tested on TEST for RW Parking spaces. NOTE: It didn't add the fee in the beginning, after I did clear cache on TEST admin, it worked. Ready for UAT.
![image](https://user-images.githubusercontent.com/51680715/199766055-61c24e09-2077-4eb2-b2dc-4bc30e818548.png)

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder it looks good to me to send to PROD

**Comment by TracyLinder** [comment]
### UAT Failed - 12308039
<img width="662" alt="Screenshot 2022-11-04 at 2 18 06 PM" src="https://user-images.githubusercontent.com/49930868/200057842-8c0b0ffe-d188-4b55-9083-e8131da2461d.png">

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0262362- raised for DEV/TEST promotion of commit is - [996468e81329](http://coaamandadevops02.austintexas.gov/R5:996468e81329ac0dc226331de16eab891ae26b80). This commit is done to add GL code.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  The bug is fixed on DEV/TEST. Its ready for UAT.

![image](https://user-images.githubusercontent.com/51680715/201748319-a702e01e-4806-4e1f-87b9-59d4fc9a3593.png)

**Comment by SubhaShroff** [comment]
@Nadin-Nader The above DEV merge is done and I tested it. Looks good and no validations or issue is done with this fee payment. DEV RSN: 12532452 tested.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  With your approval on stand up call, I submitted TEST deployment request for the above fix - SCTASK0267939. Thank you.

**Comment by SubhaShroff** [comment]
Hi @Nadin-Nader  TEST deployment is done and I tested it/ Its ready for UAT.

**Comment by SubhaShroff** [comment]
Thank you @Nadin-Nader. SCTASK0270935 is submitted for PROD deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  PROD deployment is done, the user can verify it. Thanks.

**Comment by TracyLinder** [comment]
### UAT Notes
Created folder & approved all folder processes
System inserted Valet Initial Operating Permit Fee 75300 for $50 (correct)
❌ Tech surcharge was not inserted

Manually insert fee from run procedure Valet Renewal Operating Permit Fee
- System should insert fee 50200
- Fee name should be Valet Renewal Operating Permit Fee
- Fee amount should be 295
- System should insert ATD tech surcharge for $11.80

**Comment by TracyLinder** [comment]
Tracy needs to update AC

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  As the first step to do the change, the previous code revert is requested- SCTASK0272803.
I am working on the new AC.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  When we select 'Valet Operator Permit Fee'(50200) from fee menu it adds:
Valet Initial Operating Permit Fee (with fee code 75300) - fee amount 50$ - for Initial work code types.
Valet Additional Operating Permit Fee(75305) - fee amount 10$ - for Additional work type.

1. So, from the above feecodes (75300, 75305) which one should be renamed and amount should be changed?

**Comment by SubhaShroff** [comment]
> @TracyLinder @Nadin-Nader As the first step to do the change, the previous code revert is requested- SCTASK0272803. I am working on the new AC.

The old code is reverted in all DEV/TEST/PROD.

**Comment by TracyLinder** [comment]
### Discuss w/ Paloma 

- Screenshots below show ROW has been using the same fee code for both initial and renewal fees.
- Do we want 2 separate codes?
- What updates should be made to the existing fee code? 75300



----
![image](https://user-images.githubusercontent.com/49930868/208761411-bddefa33-0109-406b-9a08-d5faf572816c.png)



----
![image](https://user-images.githubusercontent.com/49930868/208761558-7b42babb-3731-4945-ae76-eef3ee1e9e93.png)

**Comment by Nadin-Nader** [comment]
Waiting on Response

**Comment by Nadin-Nader** [comment]
@SubhaShroff Paloma got back to me and said the the Tech surcharge was not inserting.

**Comment by Nadin-Nader** [comment]
Paloma said that the Tech surcharge was not inserting per the last time she saw the demo. I looked at the demo again and found that the tech surcharge was inserted automatically at the 44 seconds as well as at the 2:17 minute mark.

I sent an email asking her to review it again....Waiting on response

@SubhaShroff @TracyLinder

**Comment by Nadin-Nader** [comment]
@SubhaShroff 

From Paloma:

> 
> Hi Nadin,
> 
> My feedback is in reference to the Valet Initial Operating Permit Fee *NOT* the Valet Renewal Operating Permit Fee.  
> 

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/3b919bcb-4262-493f-bdb0-b5c54a74004d)

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder Since localhost is too slow, I took the screenshots instead of video demo. Please review and let me know if it meets the requirements:
### NOTE: This is only on Localhost NOT deployed in DEV/TEST yet.
Now we have two fee items that display on fee tab menu:
![image](https://user-images.githubusercontent.com/51680715/212120886-aa72d6cb-14dc-43ea-bbcf-a8b08dbcc4e1.png)

Selecting 'Valet Operating Permit Fee' will insert the following fees for 'Valet Initial' work type:
![image](https://user-images.githubusercontent.com/51680715/212121204-ca59f28b-3d12-4434-8422-921b09373824.png)


Selecting 'Valet Operating Permit Fee' will insert the following fees for 'Valet Additional' work type:
![image](https://user-images.githubusercontent.com/51680715/212121969-28d7a723-2718-4945-98d7-a4de21bc965d.png)

Approving Valet Operator Review(50585) process, also triggers above fee insertions( took care of that as well based on the existing code).

Selecting 'Valet Renewal Operating Permit Fee' from the Fee tab menu(run procedure) will insert the following fees
 for 'Valet Initial' & Valet Additional work types:
![image](https://user-images.githubusercontent.com/51680715/212122290-cad39111-ade9-401e-91a3-24d1582d5b0f.png)

**Comment by Nadin-Nader** [comment]
@SubhaShroff to me it looks good. I Sent the info to Paloma waiting on her to respond

**Comment by SubhaShroff** [comment]
@Nadin-Nader  As you mentioned on Teams that Paloma approved of the above screenshots demo, I committed the code and submitted for DEV deployment request - SCTASK0278721. Thank you.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The fee name change I missed to commit in couple of places. SCTASK0279416 - this DEV request will do the change that I just submitted. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  I tested it on DEV and looks as I gave demo. So, SCTASK0279660 is submitted for TEST deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  TEST deployment is done and I tested it. 'Valet initial Opertaing fee' (75300) fee procedure is not triggered. In DEV also I saw this issue and George had fixed it by compiling it and restarting the DEV server. I will check up with Martin this time for TEST as he deployed it.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Martin recompiled the initial fee procedure on TEST and now its working. This is ready for UAT.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Today, after UAT, Paloma approved this for PROD. I submitted a servicenow ticket for it - SCTASK0286057. Thank you.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This ticket is deployed in PROD.

**Comment by SubhaShroff** [comment]
### Status:
Two weeks ago it was deployed in PROD. Waiting to close.

**Comment by Nadin-Nader** [comment]
This has been deployed to PROD and we have passed the day (Last Wednesday) that we said we would close this if we had not heard back from ROW with any changes or issues. Closing
