### ISSUE TITLE
Sidewalk inspection is now calculating without receiving an error in PROD, but is calculating the old fees.

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#10501]
Sidewalk inspection is now calculating without receiving an error in PROD, but is calculating the old fees.

The correct fee for the sidewalk inspection for this one should be 246.60. (17 LF x 1.80)+216 = 246.60

![MicrosoftTeams-image (19).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/cc9caf60-99ee-4108-84eb-e73180e1cd50)

StakeHolder: Kimberly P.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  I am not sure if I can fit those figures(given in the description above) into existing code/logic/lookup table values(which was not recently changed atleast. Only thing changed was the FY end date to 2023).
Here is the formula in the code:
         af_feeamount := lf_baseamount +(lf_fee_per_unit * ((af_value - lf_threshold) / lf_divisor));
From the code that points to  lookup table - 50081 (303) :
      lf_baseamount  = 240 (not 216 as given by the user)
      af_value             = 2  (was never 1.8 from what I say from lookup table.)

Adding the lookup table values values through the years:
![image](https://user-images.githubusercontent.com/51680715/195953257-9e2c3862-8048-45c5-bda3-8f64b9187aad.png)


Please advise.

**Comment by Nadin-Nader** [comment]
Spoke to Kensley and she informed and showed us that the fee is $216 and the price per unit is $1.80.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I submitted deployment request for the amount change - SCTASK0256928.

**Comment by SubhaShroff** [comment]
@Nadin-Nader This is deployed in DEV/TEST and its working as expected. Ready for UAT. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0257343 is requested for PROD deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This is deployed in PROD.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Since the users responded that now this fee is calculating correctly, can we close this? Thank you.

**Comment by TracyLinder** [comment]
OK'ed to close by ROW.
