### ISSUE TITLE
Usability Prep Enhancements - 10/14

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10507]
# Notes 10/14

## Draft Builder
- [x]  Reorder tables and updated table names
- [x] Change Approved Regs to be Retired icon
    - Use lighter check box, then use “keyboard” —> then Archive Box
- [x] Hiding attachment and comments tables if no records exist
- [x] Update info text: “pencil” and same wording “Fields with this (pencil icon) are editable within the table”

## Drafting Instructions
- [x] Remove numbering
- [x] Move info message on Draft Details page, show when regulation is copied - “yellow banner”

## Save Draft page
- [x] Approved Regs to be Retired - table
    - Change to details table rather than table (showing **“Approved Reg Doc + Line Item ID**”
    - similar to Regulations to Install and Retire (above it)

## Ask Stakeholders
- Save Draft page
>We added this to the Sprint Review doc

## Build & Review Page
- [x] Make the same changes as "Draft Builder" page

## Public Regulations Document Search
- If we have time.. other wise low hanging fruit 
- [ ] Copy existing structure, but without attachments and comments

# TO DO
- Tech Review feedback #10507
  - Move toward Task Board Dashboard
  - Review all review process rules and test
- Copy App - #10331 
- Help Guides #8338

**Comment by ChrispinP** [comment]
Usability Survey created and linked from Usability sign up page. Usability prep for Drafting and Search complete. Will need to perform a full end to end test next before creating staging environment (copy environment).

**Comment by ChrispinP** [comment]
Public Testing Environment knack app has been created for Usability Testing. MS Form Usability Survey ready for Testing. Documentation to be worked on.

Complete, closing
