### ISSUE TITLE
VZA App Sprint Review  #3

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1051]
[Slides](https://docs.google.com/presentation/d/1gl7dZqUl0Emd5mETZp2MwM74Uw-GrOM-R36mjYmcHB4/edit#slide=id.g6512805fdb_0_198)

Questions:
- Do we need Randy to select "No Volunteer Available" and if so how can we make that easy to remember
- Can we set a biweekly recurring invite for Tuesday (or Monday if necessary) Sprint Reviews going forward

**Comment by dianamartin** [comment]
## Diana's Notes

Pat said that:
Trey Morgan - APD Brazos Contact 
Put in that request to Tyler Tech for that "Secondary Street Full"

Start Time
End Time
is being tracked now

Jen wants to see the time gaps
right now she reviews the log of officers time

10am - 12pm
10
11
12
We suggested a "Note section": to explain the accountability in time.
Periods of inactivity: Weather event, arrest. 
(REQUIRED)

Jen is interested in: 
Pedestrian warning: non-pedestrian crossings
(Worried this information might get lost)

### Suggested Enhancements
Add Notes table - related table
Add Notes form

### Scheduling
Randy assigns officers North section
Sign up 2 North, 2 South

Pat says it would be nice to provide preferred locations. 
ENHANCEMENT: Officer sign up - "Preferred Location" field? N/S/No Preference.

### Updated Locations
New Analysis Vision Zero
- Lewis said he will be creating a lot of new locations
- Would like to add intersections
- Needs to talk to Pat after this meeting

MISSING DATA
"No. of officers" field
Jen said to add "4" 

FUTURE PROCESS
Pat said/suggested. 
Officers to sign up for open slots.

INVOICE WORK PROCESS
No Refusal Program (AMD/APD)
Two different types of programs.

STREAMLINE PROCESS
Should Randy be taken out of the workflow?

Changing the Invoice Process
Compare invoice - Look at log

REPORTING
By Officer
By Warnings/Citations

**Comment by amenity** [comment]
Post-review debrief:

**Reporting**
- Don't need wait on Tyler Tech, can begin building up reporting capabilities in PowerBI. 
    - Lots of reporting needs outside geographic analysis, e.g. unassigned shifts, types of violations, scheduled hours v. citations issued, etc. 
    - Citations without block-level addresses represent a very small minority of the data

**Officer Interface**
- Log in to start shift, end shift, and write notes (to explain any periods with no citations, e.g. "Made an arrest" "Bad weather" "Got gas" etc. or to report patterns of dangerous activity, e.g. "Pedestrians frequently cross at [     ]  without a crosswalk"
- Ability to specify preferred locations — Pat suggested "North" or "South" but being able to select APD Sectors would work with our current Locations data
✨Future State ✨ Officers can sign themselves up for shifts in the app; discussion of in person training required before account is approved

**
Next steps:
- [ ] Amenity schedule Locations meeting with Diana, John, Surbhi, Frank, Lewis, Jen

**Comment by SurbhiBakshi** [comment]
- [ ]  need to make sure I can connect records coming in from Brazos with the assignment in Power BI. so I can tie it with assigned location.

**Comment by amenity** [comment]
@SurbhiBakshi - made [this issue](https://github.com/cityofaustin/atd-data-tech/issues/1235) for that last to-do.
