### ISSUE TITLE
[TDS-TIA] Enhancement: Allow Mitigation Creation for Approved Cases and create Filter for Edited Mitigations

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#10518]
User Story: Nelson is unable to edit Mitigations that do not exist for Approved Cases. This means that mitigations are present on the Final Memo but were not entered into the TDS Portal. In order for Nelson to provide accurate funding information, the ability to add Mitigations is now necessary.

Nathan has tasked Joan with managing this updated process. The TIA team wants to be notified when changes are made to mitigations and we agreed on a daily email that both the TIA team and Nelson's team will receive. Mitigation Editors will only be able to add mitigations to cases if they are approved.

- [x] Mitigation Editors will need a link to a Case's Mitigation Details page.
- [x] Setup editing permissions
- [x] Capture Edited count for last 7 days
- [x] Setup Filter for Edited Mitigations
- [x] Show if Edited on TIA Case Details

**Comment by ChrispinP** [comment]
@TracyLinder Hey Tracy, this issue is a result of an ad hoc meeting with Nelson & Joan. Can be planned during Sprint Planning.

**Comment by TracyLinder** [comment]
Will put this on deck in case Chrispin has time this sprint.

**Comment by ChrispinP** [comment]
- Mitigation Details have been updated with all count & amount fields for the 5 Mitigation Types for Mitigation Editors.
- Turned Fee Info fields into a modal to keep TIA Mitigation table from scrolling, Nelson 😍
- Unable to link existing page with Mitigation Editor permissions, copying pages for Mitigation Editors instead with their own menu.
- Created Mitigation Editor menu for their TIA Mitigations Details page. Moved Edit Project Address button to this menu. Created menu button for adding Missing Improvements
- Menu is hidden to non editors & removed duplicate Details view.
- Copied views from Reviewer Mitigation Details page to create Mitigation Editor Add Missing Improvements page with the ability to add historical records
- Updated code for this new Add Missing Improvements page for the map and back button

WIP

**Comment by ChrispinP** [comment]
Reviewed the changes with Nelson. He was happy with everything and will need time this week to get some hands on experience. We also removed the Edited and Reviewed By dates since they were not important to Nelsons work. Will circle back in a weeks time.

Will confirm with Joan if the email meets their need or not.

**Comment by ChrispinP** [comment]
Will need to reach out to Nelson, Cody, & Joan next week to followup on testing & email.

**Comment by ChrispinP** [comment]
No further adjustments, closing
