### ISSUE TITLE
Confirmation and reminder emails to VZA officers

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1052]
Officers should get two emails regarding a given VZA enforcement assignment:
1-  When they are assigned to a shift
2- The day beforehand

Text will be something similar [to this](https://drive.google.com/drive/folders/1IUXtA0WsDXK5WfFidIZCfuDg5DjkHvOt), but Randy wants to update it

**Comment by SurbhiBakshi** [comment]
@amenity, have set up email functionality. 
- [ ] Need RDavila to provide the text in the email message (preferably as text, and not PDF) 
- [ ] Should email 'From' be RDavila's email address?

**Comment by SurbhiBakshi** [comment]
@amenity You will see an email with the text sent by RDavila (example of what the assigned officers will receive )Please review. Also, looks like two emails were sent out. I am looking into that.
