### ISSUE TITLE
Implement DOLA testing feedback

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10520]
10/15/22 Andrea sent testing notes with improvements to make to the Dockless Online License Application. Improvements include the following. 

- [x] Update Eligibility pop-up to include all forms of dockless transportations vehicles
>Seems simple: `1`
- [ ] Expression of Interest Form: Add "Other" option to "Does the provider have an affordable program open to low-income individual?" question
>Clarify: `Other` (short description)? 
![image](https://user-images.githubusercontent.com/21112975/197229489-a8408dd2-0226-49d1-8074-1e2a4304de54.png)
- Add "Other" as option
- Update display rules
- Test display rules

- [x] Update "Texas Sale Tax ID" to "Sales Tax Number" in the Before You Apply section
>Is simple: `.5` 😃 
- [x] Under Dockless Mobility License Application make "Permit Year" a date range 
>Need to review and check
- this an number field, switch to short text?
- [ ] Make sure Business Information "Company Name" drop down is working correctly 
>Clarify: what's happening that seems incorrect?
- Wait on this until Providers test this function
- [x] Preview attachments that have already been submitted, and get a preview of attachment. 
>This should be available
- [x] Review 04 Required of "Required Attachments" to indicate whether we want to collect data for all devices or moped and carshare. 
>Clarify this
- [x] Required 06 is showing up as a duplicate. Check to see if we can accept Shapefiles.
>This might've happened if user resubmitted a form from a page where it already created the attachment requirement
- [x] Required 07 is a duplicate. 
>This might've happened if user resubmitted a form from a page where it already created the attachment requirement
- [x] Review whether required 13 is applicable to cars. If not, how do we make this not required for cars?
>We'd need to think about this.. not sure yet
- We added a "delete" button and language to direct folks to delete if a Moped/Car
- [x] Make sure confirmation email that applicant has submitted on the city side. 
>I checked and my email is still set to receive emails, might need to change it.

Document with images and feedback: [APPLICATION TESTING NOTES.docx](https://github.com/cityofaustin/atd-data-tech/files/9804015/APPLICATION.TESTING.NOTES.docx)

**Comment by patrickm02L** [comment]
Hi @dianamartin can you do a run through of Andrea's comments to see what we'll need to address in depth on the Friday, 10/21/22 meeting?

**Comment by dianamartin** [comment]
@patrickm02L reviewed Andrea's notes, my notes/responses are above in original comment description.

**Comment by dianamartin** [comment]
We need to create new issues for 
- EOI update 
- Self-led testing form

Closing this issue, we addressed most of the changes during our Sprint Review
