### ISSUE TITLE
Revoke Hasura write permissions on all lookup tables

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10525]
In Moped, the `graphql-engine` is configured such that each table we expose generally has blanket `insert`, `update`, `delete` & `select` on all tables. This works, but we do have a number of tables which could be considered "part of the app", such as `moped_phases`, `moped_organization`, `moped_fund_sources`, (pretty much anything without `_proj_` in its name).

Users of the moped editor application should never be interacting with these tables in a mutation, so we should consider trimming the permissions of the applications permissions down to just what they need. 

It's **very** unlikely, but as it stands, a moped user could empty out the contents of those tables and we'd be scrambling to bring the app back into a workable state.

**Comment by frankhereford** [comment]
I think this would be a rote operation, and probably be a big `1` or a modest `2`.

Also, @patrickm02L, I think this issue could be written word-for-word, just substituting in VZE for Moped, if you'd like to consider a similar pass at VZ's `graphql-engine` endpoint.

**Comment by johnclary** [comment]
thanks @frankhereford — totally agree. Added this to #10549
