### ISSUE TITLE
Let Geo team know that we don't need CTN street vector layer anymore

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10532]
Once we complete https://github.com/cityofaustin/atd-data-tech/issues/10399, we will longer have use for the CTN segments [vector layer](https://austin.maps.arcgis.com/home/item.html?id=a8031f437d104abbb0286f8a14c403b3), since we're switching to the exclusive use of the [feature service](https://austin.maps.arcgis.com/home/item.html?id=24455c781dbd48669c601ede4b365d1f).

**Comment by johnclary** [comment]
@andrewshensky - like it says above, heads-up that we are no longer using this vector layer. Moped relies entirely on feature services.

**Comment by andrewshensky** [comment]
@johnclary Just to confirm, the only data that will be needed from the geo team for MOPED will be the CTN Segments as a feature service? Is the intersection point data being pulled from somewhere else?

**Comment by johnclary** [comment]
@andrewshensky thanks for [publishing the CTN intersections](https://github.com/cityofaustin/atd-data-tech/issues/11305) as well.

We don't need CTN street vector layer anymore ✅
