### ISSUE TITLE
Create RPP Resource for Residents Scoping Meeting

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#10546]
Request #10349

- With our department transitioning to a digital permitting process for our RPP program, residents have requested a resource to be provided to them to assist them with monitoring vehicles parking in their particular zones. 

- Previously we issued physical decals and hangtags, which were visible for all residents to see. In an effort to alleviate their concerns, and assist in mitigating unnecessary calls to 3-1-1, or enforcement. We hope this provides our residents with an easy solution. Our hope is that once a page is created, Passport, the digital permitting program, will be able to add a link to our LP look-up, on the resident's Passport Dashboard.

**Describe the solution you have in mind.**

We are looking to create an RPP-related webpage where the public can go to look up a license plate to see if it is permitted for the RPP zone or not.

**How will we know that our solution is successful?**

Residents are able to enter an LP into a search bar, and the search result will list the LP as either "Permitted" or "Not Permitted"

Meeting scheduled 10/24
Attendees: Paul B, Jacob C, Diana, Chrispin, Stephanie

**Comment by dianamartin** [comment]
participants: Jacob, Chrispin, Diana

# Notes 10/24

Audience/Purpose: for the residents to allow them to know if a vehicle is authorized in their RPP Zone
- Ex. Orange zone residents were calling about permitted vehicles on whether or not the 
- "Look up portal", "RPP Look up portal"

## Proposed set-up
- Dream: User to plug into a field and search for a plate number 
- When query is "not found" = license plate is not in the system, Is not permitted`
  - Status Message: _If vehicle is not permitted, we encourage residents to report any questionable vehicles by calling Austin 3-1-1 or reporting via Austin 3-1-1 App to alert enforcement services_

Jacob's blurb
>Notes: Along with this new digital permitting system, ATD is currently developing a public web portal where residents will be able to check if certain vehicles are permitted in their area or not by simply entering the vehicle’s license plate number. This RPP permit look-up portal is expected to be available on our main RPP webpage (at [https://www.austintexas.gov/page/purchase-permits-residential-parking](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.austintexas.gov%2Fpage%2Fpurchase-permits-residential-parking&data=05%7C01%7CJacob.Culberson%40austintexas.gov%7C99847c026395428addad08dab5dd5031%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638022259377851466%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FFYJn71QrIsgmhT0GgObw0bfyQwksn%2BPEiKehKLr9d0%3D&reserved=0)) by the end of this year’s renewal period. Until then, we encourage residents to report any questionable vehicles by calling Austin 3-1-1 or reporting via Austin 3-1-1 App for our enforcement officers to address. 

- When query find license plate in the system, `Is permitted` - and provides District/Zone/Area Color
  - clear page to refresh 

Enforcement officers look up the license plate and zone information, but only an internal function

physical permit --> digital permit
- Public page with table of license plates w/ status "Permitted", "Not Permitted", "District" (color) 
- Passport API feed? 

## Timeline
- Renewal period
- Early next year - flexible

**Comment by dianamartin** [comment]
@moorerst I've got the recording for you if you're interested in reviewing if my notes need clarity.

**Comment by dianamartin** [comment]
# Follow-up 
- [ ] Ask COA Legal on this?
   - [ ] If we posted a list of license plates and zone numbers on the public internet, would that be bad?
   - [ ] Can you get State?
- [ ] Ask Jacob of API end point from Passport - Y/N?
- [ ] Embed or link to .gov website?

**Comment by patrickm02L** [comment]
@johnclary would you know who in Legal to reach out to about posting license plates on the open data portal?

**Comment by dianamartin** [comment]
# 1/3 
- Reaching out to Joseph A. (PE) to see who at legal he'd talk to.

**Comment by dianamartin** [comment]
# 1/4
- Joseph said to reach out to Angela R. from legal
- Emailed Angela R. from legal and told her about my inquiry
- Recommended to reach out to Elaine from ISO
- Emailed Elaine at ISO and Nancy from ISO replied
- They'd like to have a quick sync about the proposed data solution to figure out if request is viable

**Comment by dianamartin** [comment]
Closing, creating new issue for meeting with Legal and Mobility Services.
