### ISSUE TITLE
DTS website Home Page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10562]
Homepage redux will include updated

- Nav bar
- Updated hero section
- We're here to help
- Featured Projects
- Footer (already updated #4632)

See latest updates to the [Data & Performance Hub](https://data.mobility.austin.gov/) for **featured project** cards.

**Comment by patrickm02L** [comment]
City of Austin Background Image.

![Austin background](https://user-images.githubusercontent.com/5566727/197267827-0aaba881-3d8f-4f4e-88e5-7e035cd7cf5b.png)

**Comment by roseeichelmann** [comment]
Is the new Transportation icon on the navbar supposed to be clickable? When you click on it what link does it redirect to?

@patrickm02L @chiaberry

**Comment by patrickm02L** [comment]
> Is the new Transportation icon on the navbar supposed to be clickable? When you click on it what link does it redirect to?
> 
> @patrickm02L @chiaberry

When on the other pages the logo/icon should redirect to the this home page.

**Comment by patrickm02L** [comment]
Here are the project/products to be "Featured"

[Moped ](https://www.austinmobility.io/products/5086?tab=description)
[Vision Zero Viewer  ](https://www.austinmobility.io/products/5150)
[Online Bike Map](https://www.austinmobility.io/products/9110)
[Data Tracker](https://www.austinmobility.io/products/2068)
[Austin Build + Connect: Amanda Portal](https://www.austinmobility.io/products/4791)
[Data and Performance Hub](https://www.austinmobility.io/products/3019)
[Human Resources Management](https://www.austinmobility.io/products/2863)
[Street Impact Fee Implementation](https://www.austinmobility.io/projects/5078)
[Traffic Analysis Case Management](https://www.austinmobility.io/projects/2526)

**Comment by roseeichelmann** [comment]
@patrickm02L I was wondering if you could provide some more mockups of how you want the carousel to act when clicking through it. For example is there always gonna be 4 projects on the screen, and if so how do we deal with there being 9 projects/products featured? It would be helpful to get a better idea of what exactly the carousel should do/how it should deal with displaying all the projects

**Comment by patrickm02L** [comment]
@roseeichelmann I initially thought that the carousel should slide one card at a time. But looking at the Apple TV+ example I think back to 8 works. Let's nix the last list item [Traffic Analysis Case Management](https://www.austinmobility.io/projects/2526). 

**Example of carousel in action**
_with commentary_

https://user-images.githubusercontent.com/5566727/198619883-e2c15a18-3b6e-4e13-9274-3933026e2958.mp4

**Comment by roseeichelmann** [comment]
@patrickm02L thanks, this is super helpful!
