### ISSUE TITLE
Create dashboard page for end of year performance metrics

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10568]
In Planning 10/20/22, Peggy suggested adding End of Year [performance metrics](https://www.austintexas.gov/budget/eperf/index.cfm?fuseaction=home.SearchResults&DEPT_CD=ATD&KEYWORD=) to the dashboard. 

Also from [data tracker.](https://atd.knack.com/amd#performance-measures/? If you need eCombs it's linked in DT.

**Comment by amenity** [comment]
@maccallump - shall we set up a meeting to discuss this dashboard?

**Comment by maccallump** [comment]
FY21 Year-end Dept survey data.
[2021 - Department Results.pdf](https://github.com/cityofaustin/atd-data-tech/files/10315996/2021.-.Department.Results.pdf)
