### ISSUE TITLE
SD 2023 data snippets

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10567]
From the Spike #10121. we discovered that we would not be able to pull in data from Socrata. However we'll want to grab smaller datasets from the Strategic Measure cards. 

We'll want to pinpoint what metrics we'll want from the cards per each department.

We should also consider the [Austin Community Survey](https://data.austintexas.gov/stories/s/Austin-Community-Survey/wn8p-f4h4/) dashboard.

**Comment by amenity** [comment]
@patrickm02L @Charlie-Henry - should we backlog this and remove it from that closed spike? Or close/icebox?

**Comment by patrickm02L** [comment]
This was an idea early on before we knew what data we wanted to include in the dashboard. We can close it.
