### ISSUE TITLE
Bug: Unable to edit TURP folder tab. 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10575]
### User cannot edit the folder tab on a franchise utility TURP 2022-105157 RW
- ROW thinks this is because of a character limit on the conditions field. User is Russel B. 
<img width="801" alt="Screen Shot 2022-10-21 at 2 14 00 PM" src="https://user-images.githubusercontent.com/49930868/197272257-9fdffdb2-e8ff-4c9c-8621-886a4c7e9953.png">

**Comment by Nadin-Nader** [comment]
Spoke to George over at CTM and asked if he knew the character limit in the conditions field.
He checked the DB and found that it has a character limit of 4000
