### ISSUE TITLE
Add `systemctl` or similar style configurations to start services on boot

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10574]
## Story

On our on-prem servers, in particular `atd-data02`, we run a few services which do not start on boot reliably. This issue intends to track the discovery over why this is the case and the appropriate remediation so that they come up into a fully usable state after booting. 

#### `atd-data02`
* [ ] Airflow docker-compose stack
* [ ] 3X Prefect agents

**Comment by chiaberry** [comment]
Going to close this issue since we no longer run the prefect agents nor airflow stack on 02
