### ISSUE TITLE
Add Financial Fields to Knack and have as custom attributes

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10580]
## To Do
- Add financial fields: FUND, DEPT, UNIT, REVENUE, ACTIVITY - `Diana`
- Add fields to JavaScript - `Chia`

**Comment by dianamartin** [comment]
Added new fields
![image](https://user-images.githubusercontent.com/21112975/197587226-c5812ca9-dcca-470f-9dba-2c30b1907738.png)

Need to set conditional rules

**Comment by chiaberry** [comment]
@dianamartin can I add a column to the messages table (object 181) to track the citybase transaction ID ?

**Comment by dianamartin** [comment]
@chiaberry I'll add it `CityBase Transaction ID`

**Comment by dianamartin** [comment]
@chiaberry have you updated the JS to include these fields yet?

**Comment by chiaberry** [comment]
@dianamartin its updated now. I had to add the columns to the tables on the views as well as updating the javascript. 

I added it the custom_attributes in the line items, I believe this is how Eva said she wanted to receive the data.

**Comment by dianamartin** [comment]
@chiaberry good to close?

**Comment by chiaberry** [comment]
sure, I guess we can reopen if Eva doesnt like how the attributes are being passed over
