### ISSUE TITLE
Document Knack go-live process

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1058]
What are the repeatable steps we take when putting an app into production?

**Comment by dianamartin** [comment]
I found some issues that we created during the Signs Migration

- [ ] Test all buttons (as each user role)
- [ ] Check page permissions (sign in as each user role)
- [ ] Create application banner (see [issue](https://github.com/cityofaustin/atd-data-tech/issues/275))
- [ ] Meeting with stakeholders to talk about go-live, roll out plan to end users
- [ ] Delete all test records from everything (object tables)
- [ ] Provide access to users for new modules/new user roles

**Comment by amenity** [comment]
These are great, @dianamartin. Thanks.

**Comment by dianamartin** [comment]
I decided to make a GitHub issue template for the Go-Live tasks, here's the draft
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/10516162-f562-4344-a4e8-e5a6478b8447)

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/eb0908f6-1773-4dac-9d31-fd2716c02ca3)

**Comment by dianamartin** [comment]
@amenity @johnclary if there's no feedback on this yet, I'd like to close this issue and we can iterate on changes at some other time.

**Comment by amenity** [comment]
@dianamartin - sorry, must not have hit send on my comment before. This looks fantastic. Thanks.
