### ISSUE TITLE
Executive Dashboard meeting with Anthony S.

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10598]
In meeting with Anthony S. on 10/31/22 the team showed off the latest version of the [Executive Dashboard](https://app.powerbigov.us/links/tQAnbdsvMB?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare).

@Charlie-Henry @maccallump @katelunceford @patrickm02L were present.

In the meeting, we talked about the inspiration for Revenue Tabs which comes from an ATD spreadsheet that Crystal maintains. We also walked through the Permit and Street Impact Fees tabs. 

Anthony's reaction was positive. He recommended including data from Javier or Lewis (VZ), wanted to see 311 service requests on a monthly basis, and wanted to know when we could get this in front of the Executive Team.

There was conversation around including SD23 goals, incorporating some VZ and Signs and Marking Data and linking out to what their dashboard, and Peggy looking at how to present this as a package either for the year end, as well as monthly and quarterly reports. 

Thinking about how to scale this, similar to PWStat, it was recommended that we could grab data from the new internal City data hub. Charlie also noted that other than financial information which is typically gathered on a monthly basis, that we would be able to pull in other sources of data in real-time. 

Peggy is setting up a meeting for mid-November to sync back with Anthony S. in preparation for bringing this to the Exec. Team.

**Comment by patrickm02L** [comment]
In a follow-up email Anthony S. asked if we could show a breakdown to help facilitate how each division is doing. He provided the following images.

![image001.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/bb2442d6-03a6-4180-b4cc-4c0d34d69860)


![thumbnail_image006.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/8cd6d5ed-83d7-4e52-bcbb-4cb51799fd5b)

![thumbnail_image007.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/b44b894b-a68d-47d6-a73e-35291ccee0b5)

![thumbnail_image008.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/8031b453-ddd8-498f-a641-8b62f015caf4)

![thumbnail_image009.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/eec43d62-b696-4f5e-baf9-4f20f2ba6ce3)

**Comment by Charlie-Henry** [comment]
I revived our Vision Zero tab we had created to look back at the current calendar year and tried to match the same style we have for the newer tabs:
![image](https://user-images.githubusercontent.com/30810522/199608745-c03dbbe0-873e-4011-9b47-87706812b922.png)

And also created a 3-1-1 tab where we are looking at a sliding 12-month window:
![image](https://user-images.githubusercontent.com/30810522/199608824-5a4b42dc-861f-40c5-b73f-d3fee910b660.png)

Next week when I get back, I'll see what we can pull in from Signs & Markings and rework some of the expenses/revenue tabs to be more like what Anthony shared ☝️
