### ISSUE TITLE
Add banner to VZA App

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1059]

**Comment by SurbhiBakshi** [comment]
scheduled a work session with @dianamartin for this

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/f419f8a5-2d7d-4cdc-b44c-5a810411ae24)

**Comment by amenity** [comment]
Beautiful, @SurbhiBakshi ✨
