### ISSUE TITLE
V7 FY23 Fee Fix: ATD-ZON-Review <10 Acres calculates wrong when inserted into a Zoning case (Ready for UAT on Prod)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#10592]
Zachary W. Put an Incident in stating that the ATD-ZON-Review <10 Acres (83491) is calculating wrong 

Incident INC0236978
ATD-ZON-Review <10 Acres calculates wrong when inserted into a Zoning case
Showing as $2,460 and it should be $2,770 variance of $310

StakeHolder: Zachary W.

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/77ff2836-2fb9-4886-b6c6-b9b598b41a6c)

![2022-10-25_11-20-41.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/93f5a40b-a59c-42c9-8579-1644894286e3)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Commit done to update fee amount . Requested for Dev and Test promotion
SCTASK0259024

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Test. Fee amount is updated t0 $2770. Ready for UAT

**Comment by Nadin-Nader** [comment]
I reached out to Zach but did not hear back from him about this. I verified that the fee is now correct. I also left him a chat message stating that this was fixed but since i had not heard back from him that i would close the request. I also mentioned that if anything comes up with the fee being wrong, to please reach out and we will revisit. Closing
