### ISSUE TITLE
[BUG] The Github > Socrata ETL is failing with a Zenhub SSL error

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10611]
[This DAG](https://github.com/cityofaustin/atd-airflow/blob/master/dags/atd_service_bot_issues_to_socrata.py) is [failing](https://airflow.austinmobility.io/log?task_id=dts_github_to_socrata&dag_id=atd_service_bot_github_to_socrata_production&execution_date=2022-10-26T18%3A21%3A34.000419%2B00%3A00).

```
[2022-10-26 18:24:20,161] {{docker_operator.py:242}} INFO - INFO:root:Fetching zenhub data...
....
ssl.SSLCertVerificationError: ("hostname 'api.zenhub.io' doesn't match 'raptor-admin.zenhub.com'",)
```

According to Zenhub's [legacy REST API docs](https://github.com/ZenHubIO/API#root-endpoint), we may not be using the right endpoint.

**Comment by johnclary** [comment]
@johnclary ask zenhub why this API endpoint doesn't work anymore

**Comment by johnclary** [comment]
Yeah, this endpoint has apparently been deprecated since Jan 2020: https://github.com/ZenHubIO/API/commit/3a5405bc058e64e1c3b79f79e85e121db54012e9

**Comment by johnclary** [comment]
@amenity this is fixed :)

**Comment by amenity** [comment]
Thank you, @johnclary!
