### ISSUE TITLE
DTS website Projects Page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10616]
Projects, formerly known as [Our Work](https://www.austinmobility.io/projects?status=in_progress) updated layout.

**Comment by patrickm02L** [comment]
## Before

![screencapture-austinmobility-io-projects-2022-10-27-10_09_58.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/86581d19-b903-4b88-8d83-073164d7c3e2)

## After

![Home – New – 5.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/202ffa0e-9c91-4127-b557-a724b8ecf2e4)

**Comment by patrickm02L** [comment]
**Project Page "By Workgroup" drop-down menu.**

![Screen Shot 2022-10-28 at 10.06.37 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/aa04d116-1861-4ed2-a00f-8a0f7fb96588)

**Comment by patrickm02L** [comment]
#### iPad View w/ Nav menu

![iPad Pro 10 5in – 5](https://user-images.githubusercontent.com/5566727/198670721-4a8e469e-6960-4b1b-be20-358523c3f26b.png)

**Comment by patrickm02L** [comment]
#### Mobile View with Nav Menu

![iPhone 13, 12 Pro – 1](https://user-images.githubusercontent.com/5566727/198672827-ea472666-beb3-4367-b52a-41bb8977d3b9.png)

**Comment by patrickm02L** [comment]
@amenity this is ready for your feedback.

**Comment by roseeichelmann** [comment]
@patrickm02L How do we address the links in the Projects page description design-wise to show they are clickable?

**Comment by patrickm02L** [comment]
> @patrickm02L How do we address the links in the Projects page description design-wise to show they are clickable?

Let's go ahead and keep the description text black, and highlight the links in blue like it's currently working in the website.

<img width="1105" alt="Screen Shot 2022-11-07 at 1 21 36 PM" src="https://user-images.githubusercontent.com/5566727/200396295-c099ace2-17c8-4b03-95b3-1bd59e0647c1.png">
