### ISSUE TITLE
Project: CityBase Payment Integration

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10621]
We're implementing a new payment processor for the Street Banner Program to provide customer and staff a more streamline process when filling out their application online.

## Background
Currently, when a user fills out a digital Street Banner application online, they have to go through a complex process in order to submit an online payment. ATD staff have to create an AMANDA permit record for the Street Banner event, an invoice. The customer has to register on the AMANDA portal to create and account and alert ATD staff their account is created, then staff have to associate the person to the permit invoice they've created in the the AMANDA permitting system. This process is not streamlined and causes many unnecessary data integrity issues (ex. multiple emails registered by one person). 

We intend to upgrade the way a customer can submit payment by implementing the payment processor CityBase. This platform is used by many other COA departments and has been supported by the Central Finance IT team. 

## Scope & Deliverables
Features and functionality we are hoping to achieve with this implementation
- Easy payment interface for customers
- Invoice tracking 
- Centralized transaction management for financial staff
- Integrated process to apply and perform digital payment

## Desired Outcomes
- Internal staff can review applications, set in a Pending-Payment status
- Customer to be able to access their application details and make payment
- Customer to receive emailed invoice details
- ATD Finance team to be able to reconcile transactions easily

![image](https://user-images.githubusercontent.com/21112975/198355013-3b84074f-07f5-46b6-a7ab-3ffc3c45ef06.png)

![image](https://user-images.githubusercontent.com/21112975/198355278-4be62976-b2df-476d-b964-0b454f59ef53.png)

---

This Github issue represents a project of Austin Transportation's [[Data & Technology Services](https://austinmobility.io/)](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
@patrickm02L - please write a several-sentence update here & delete this reminder comment so it doesn't show up [here](https://austinmobility.io/projects/10621). ✍🏻 🗑️

**Comment by dianamartin** [comment]
The CityBase payment portal <--> Knack integration went live on Jan 2023, with our first online payment on January 20th! Our City of Austin implementation team noted that this was the smoothest integrations they've had, 
>We have watched quite a number of City of Austin teams transition from JPMorgan/Chase to Citybase, plus some departments who did not have any online banking presence come up on Citybase.  I am not one to freely give out compliments and only give it out when it is deserved.  

Now our customers have an super easy way to pay their street banner applications!
