### ISSUE TITLE
Close the loop on editing a component with Attributes and Map buttons

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#10626]
As a Moped user, I'd like to edit a component's attributes and geography after I've created and saved it. Two buttons already exist (see screenshot) so we just need to finish what happens when they are clicked.

- Clicking the **Map** button opens the map edit mode again so selected or drawn lines or points are editable
- Clicking the **Attributes** button opens up the component form (showing **Save** as the action button instead of **Continue**?)
- Edit mutation uses the new DB schema

![Screenshot 2022-10-27 at 2.51.08 PM.png](https://images.zenhubusercontent.com/5cfe7d078509cb6dcbaafdc3/26de0604-32a6-4e90-9639-e16d2f5f8f11)

**Comment by frankhereford** [comment]
@mddilley We touched on this briefly in planning, and I had a thought -

You may have a list of the columns in a given feature table by inspecting the shape of the response from `graphql-engine`, but if you wanted, we could put a view in that inspects the databases system tables and exposes them to be queried. Imagine a view that does something like:

```
SELECT
  *
FROM
  information_schema.columns
WHERE
  table_schema = 'public'
  AND table_name in ('feature_signals', 'feature_intersections', etc);
```
