### ISSUE TITLE
Configure assignment creation process so that assignments are created automatically by Scheduler

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1062]
As is, Randy adds Officers to Assignments. There are a few downsides to this: 
- He can add fewer or more officers than Lewis requests. If he adds more, it creates a negative number in "Unfilled Slots" which is very confusing. 
- We rely on him to select "No Volunteer Available" to get our data on unfilled shifts. 
- His Assignment Details page is a little confusing because he has to edit officers to switch them out. We observed that this wasn't very intuitive in #965.

**Comment by SurbhiBakshi** [comment]
@amenity, @dianamartin I tried this out, and think that I will need some help from @dianamartin. Will schedule a meeting for second week of Jan.

**Comment by SurbhiBakshi** [comment]
- [ ] Need to figure out reporting statistics like unfilled slots, number of officers assigned.
- [ ] Need to figure out what happens if Scheduler has to change the number of officers assigned, a decrease in the number of officers would mean deleting child records.

**Comment by SurbhiBakshi** [comment]
The processing time for the form with child records is  too long (40 + seconds), so going back to the original approach.
