### ISSUE TITLE
Show the street labels from the streets layer conditionally on top of all other layers (instead of the satellite labels)

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#10628]
The labels that are currently always showing on top of all other layers in the components map are optimized for satellite imagery since they come from the Mapbox sat layer. This makes sense for the NearMap aerial tiles, but we should conditionally show the labels from the Mapbox streets layer on top of everything else when showing the streets base map.

See https://github.com/cityofaustin/atd-moped/pull/839#discussion_r1003730202 and https://github.com/cityofaustin/atd-moped/pull/841#pullrequestreview-1160284371

**Comment by mddilley** [comment]
@johnclary Just created this from some PR feedback https://github.com/cityofaustin/atd-moped/pull/839#discussion_r1003730202 I'll focus on other issues until you get a chance to look at this.

**Comment by johnclary** [comment]
thanks @mddilley!

**Comment by johnclary** [comment]
thanks @mddilley! would you care to throw an estimate on this?
