### ISSUE TITLE
Stensland page editing rights

### ISSUE THREAD

**Issue by jeffstensland** [cityofaustin/atd-data-tech#10637]
I sent this request six days ago as a comment to my other Socrata request, but it has not been executed. I need editing rights to: https://data.austintexas.gov/stories/s/sa9q-m9wz

Thank you

_Originally posted by @jeffstensland in https://github.com/cityofaustin/atd-data-tech/issues/10591#issuecomment-1291145235_

**Comment by frankhereford** [comment]
Jeff S. has been granted co-ownership of the above mentioned open data portal resource. CC/ @KaroEngstrom
