### ISSUE TITLE
Update Moped GitHub actions based on `node.js 12`

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10631]
On triggering the `atd_moped_database.yml` action today when merging a branch into `main`, I observed the following pair of Annotations on the [action result page](https://github.com/cityofaustin/atd-moped/actions/runs/3347404920):

### ⚠️ Apply Migrations
* Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/setup-python, actions/checkout, actions/checkout, actions/setup-python
* The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I suspect our actions will break at some point, or at the absolute least, we'll get these warnings until we address this. Node 12 lost its LTS status two years ago, and went fully End-Of-Life April past. 

This issue is to track the discovery and related mitigation of this problem.

**Comment by frankhereford** [comment]
@chiaberry Do you think this would be valuable to bring to grooming or handle in another way?

**Comment by johnclary** [comment]
thanks @frankhereford i added this to https://github.com/cityofaustin/atd-data-tech/issues/10549. we'll turn our attention to these in the not-to-distant future
