### ISSUE TITLE
Gather stakeholder and DTS input

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10649]
### Principles
* No one knows the importance of usability more than the daily users of the database & app

### Acceptance Criteria
* [x] Gather / author specifications to be used to define computed & aggregated fields
* [x] Document specifications
  * This document is an informal contract on what will make a value "right" or "wrong" going forward
* [x] Get sign-off from stakeholders and memorialize the agreement

**Comment by frankhereford** [comment]
🗂️ [vz_ldm.xlsx](https://github.com/cityofaustin/atd-data-tech/files/9924919/vz_ldm.xlsx)

The attached spreadsheet is an inspection of the `crashes`, `units`, `persons` and `primarypersons` tables. It lists the columns provided by CRIS, the columns in place in the VZDB today, and notes on how to handle various fields.

In the morning, I am going to draft an email to the VZ team which focuses on the fields which will become:

* `crashes.apd_human_update`
* `units.trlr_*` (~10 column related to trailer status & damage)
* `(primary_)persons.apd_confirmed_fatality`
* `(primary_)persons.apd_confirmed_death_count`
* `(primary_)persons.atd_fatality_count`

I want to firm up with the VZ stakeholders exactly how these are defined and make clear how they will be aggregated up to parent objects, when applicable. I will share this email with @chiaberry & @patrickm02L prior to sending it off. With the VZ team's input and this work, I believe this issue will be good to close.

**Comment by frankhereford** [comment]
We have a number of "tables" which are delivered to us from CRIS which we do not interact with. Is there value in making an issue to investigate these and consider if we want to start ingesting them into the VZDB? The tables include (but may not be limited to ..)

* charges
* damages
* endorsements
* restrictions

**Comment by patrickm02L** [comment]
> Is there value in making an issue to investigate these and consider if we want to start ingesting them into the VZDB?


Curious if Xavier would have input on this? 

If we haven't ingested them in the past, why start now? My druthers is to leave them be.

That being said, I'm of the mind that documenting things that we may want information on in the future makes sense, and would be interested in creating an Issue that would capture those "tables" that we don't interact with.

**Comment by frankhereford** [comment]
> If we haven't ingested them in the past, why start now? My druthers is to leave them be.

I think is a good framework when considering the urgency around this question and data, but I am inclined to go with your first to have a conversation with the VZ team about the assets when the opportunity presents itself, perhaps at the tail of sprint review coming up. The data may have a new application which was not available in the past, and if it could further the VZ mission, then I think the effort would be more than worth it.
