### ISSUE TITLE
Roll-out

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10657]
* [ ] Enter downtime
* [ ] Turn down all DAGs, flows & `cron` jobs
* [ ] Turn down `graphql-engine`
* [ ] Copy live database into a new database to be used during the rollout
* [ ] Drop & recreate production database
* [ ] Add PostGIS extension
* [ ] ~Add temporal tracking extension~
* [ ] Create schema
* [ ] Import full SQL file for `cris` schema
* [ ] Use `cris_import.py` script to update `cris` schema if SQL file is out of data at all
* [ ] Use script to compute and store `visionzero` schema
* [ ] Turn up `graphql-engine`
* [ ] Apply metadata via `graphql-engine`
* [ ] Deploy VZE
* [ ] Update and enable all DAGs, flows, and `cron` jobs
* [ ] Exit downtime

**Comment by frankhereford** [comment]
I think it's helpful to look at this as a set of deliverables that comes out of all the prior work:

* [ ] 75% done - A series of python scripts and/or SQL scripts that can be used to reliably take a replica of the production VZ database and convert it into an LDM database with all the data intact.
* [ ] Finding the right place in this conversion process to say "everything before this break" can be done prior to the deployment operation itself, and after which, has to be done during the downtime window of deployment.
  * [x] I think this should be right after the year-by-year import of CRIS exports is complete, as this takes ~40 hours of wall-time to complete. 
* [ ] Getting the "prior" part done and producing a `pg_dump` output SQL file that is the starting point for the roll-out.

And finally, a day-of deliverable, which is doing the roll-out itself.
