### ISSUE TITLE
[Feature] Add new temporal table change log support as a "changelog 2.0" like feature

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10656]
### Principles
* This is a major / breaking change, and should cause the VZ Suite to bump to a new major release number
* This may be rolled out as a feature after the rest of this work is completed

### Acceptance Criteria
* [ ] VZE shows a "historic changelog" for changes prior to roll-out
* [ ] VZE shows a "changelog" using the temporal data tracking
* [ ] Indication that the historic changelog will be deprecated at some point in the future, based on stakeholder readiness

**Comment by patrickm02L** [comment]
## 9/20

In an LDM meeting we discussed this as option B+ which is to keep the current change log in VZ as the change log for LDM, but then adding the temporal piece on top of that.

We also discussed how long we'd keep the past change log data with is estimated at 30B, at 6 months or a specified amount of time we could deprecate the changelog data, archive it in an S3 bucket that could be referenced down the line if needed, but that we wouldn't port the historic changelog data because it's a giant beast

**Comment by johnclary** [comment]
This need is covered via the change logging design int he new data model 👍
