### ISSUE TITLE
Prepare environment for work

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10650]
### Related existing issues 
* [7240](https://github.com/cityofaustin/atd-data-tech/issues/7240): Setup Local VZ Dev Environment
* [6988](https://github.com/cityofaustin/atd-data-tech/issues/6988): Upgrade VZdb to `graphql-engine` 2+
### Principles 
* Incorporate `docker-stack` branch found [here](https://github.com/cityofaustin/atd-vz-data/tree/docker-stack)
* Minimize / eliminate use of multipurpose tools
* Orchestrate the stack with `docker-compose`

### Acceptance Criteria
  * [x] The stack spins up with the command `docker-compose up -d` from the root of the repo
  * [x] Update to latest `graphql-engine` version
  * [x] Do dockerize the VZE & VZV applications
    * Standardize the development environment (node version, modules installed, etc)
  * [x] Do memorialize common operations in the `README.md`
  * [x] Do include support for replicating from the read replica
    * [x] Do include a new, small prefect flow to maintain read replica permissions on VZDB
      * This should be an issue in itself, modeled after [10251](https://github.com/cityofaustin/atd-data-tech/issues/10251).

**Comment by patrickm02L** [comment]
Also related

[8240](https://github.com/cityofaustin/atd-data-tech/issues/8240) Wrap the Vision Zero suite into a Docker container

**Comment by frankhereford** [comment]
https://github.com/cityofaustin/atd-data-tech/issues/7240 is another issue that will get closed by this.
