### ISSUE TITLE
Update the VZE to use the schema

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10654]
### Principles
* Ideally, this work is minimized by previous work in creating the `public` schema views
* Do not update the mechanics of the change log, leave that for later

### Acceptance Criteria
* [ ] VZE is operational
* Change log is operational in that it:
  * [ ] Shows "historic" changes from the `atd_txdot_change_log` table
  * [ ] Does not need to show changes from the temporal tracking output

**Comment by frankhereford** [comment]
* ✅ The crash details page was demo'd using LDM tables, but this was prior to the inclusion of the lookup table work
  * [ ] Check if this still works, and make changes to the graphql queries required to restore it
* [ ] Page by page, make the rest of the VZE app use the LDM schema

**Comment by johnclary** [comment]
👍 i'm closing this in favor of creating page-specific issues.
