### ISSUE TITLE
Populate `cris` schema with data from CRIS

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10652]
### Acceptance Criteria
* [x] Branch and modify the CRIS import script / flow found in [cris_import.py](https://github.com/cityofaustin/atd-prefect/blob/main/flows/vision-zero/cris_import/cris_import.py) to populate the `cris` schema
  * This should remove a fair chunk of code related to "important' field handling and change conflict resolution
* [x] `vision-zero` script commands to get data into the database, similar to the "Recreate Environment Path" section [here](https://github.com/cityofaustin/atd-moped/pull/792)
  * [x] Turn down `graphql-engine`
  * [ ] ~Disconnect other PG connections if possible~ 
    * This is unreliable at best; I suggest we rely on the devs to disconnect their SQL clients when populating the DB
  * [x] Pipe SQL files into `psql`
  * [x] Turn up `graphql-engine`

**Comment by frankhereford** [comment]
I am going to take the following out of the acceptance criteria for this task. I'm finding that the replicate-db command of the `vision-zero` script is more useful than this seed data will be, especially considering that it will cache the days data. If we find that we do need seed data, then we can revisit this in a spin off issue. 

* Build "seed" data files
  * [ ] SQL file for both a subset (last 90 days) of data
  * [ ] SQL file for 10 years of data, or as far back as possible
  * [ ] Seed data is not checked into the repo and is ignored via `.gitignore` file(s)
