### ISSUE TITLE
Update Signal Timing > Socrata Publisher to Push a Full Replace Daily

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1065]
Update the signal_retiming ETL to do a full replace (`--replace`) instead of an hourly incremental update of this dataset:
https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Signal-Re-Timing/g8w2-8uap

Reason: 
> i did find an issue with the way we update the signal count values on the retiming dataset. if you add a signal on a corridor that has an existing re-timing. the signal count is not reflected until the re-timing is modified. we can fix that by fulling replacing the dataset on every job run

**Comment by amenity** [comment]
@johnclary any update on this?

**Comment by johnclary** [comment]
Fixed. Thanks :)
