### ISSUE TITLE
Port Airflow DAGs to Prefect

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10665]
### Background
During a recent discussion in a Prefect Huddle, the group came to a consensus that a well scoped set of issues with an agreed upon deadline would be a helpful structure to keep our team's journey towards prefect adoption moving forward. 

This epic is intended to house these issues initially, and to be expanded to include all applicable DAGs and `cron` entries which we wish to port.

### Initial Scope
Initially, we're going to tackle the following issues, all of which have been moved "On Deck."
* @frankhereford will populate this epic with all outstanding DAGs and cron entries, beginning with the following issues
* @roseeichelmann will tackle [10378](https://github.com/cityofaustin/atd-data-tech/issues/10378) and orchestrate the backup of the VZDB to S3
* @Charlie-Henry will migrate the service bot ETLs into prefect flows as described in [10633](https://github.com/cityofaustin/atd-data-tech/issues/10633)
* @johnclary will take on the issue [7168](https://github.com/cityofaustin/atd-data-tech/issues/7168)'s publishing of signal studies so they are orchestrated in prefect

### Timeline
We have agreed that we'd like to frame this work as set of smaller issues chosen to not take a ton of our time. That said, we have also agreed that we'd like to see this work completed over the next 2 upcoming sprints. I have updated the contained issues, listed above, to have their sprint designations reflect that timeline. As we approach the end of the sprint ending on **_Nov 29_**, we discussed setting our next prefect meeting's time so we can reconvene to assess our progress and make subsequent plans.

**Comment by Charlie-Henry** [comment]
Added atd-finance-data to this epic as another airflow ETL that we will sunset 🌆 🔨
