### ISSUE TITLE
LC Folder Permission Update for ATD Finance (CTM Working on Crystals Account)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10666]
### ATD finance needs permissions for the LC folder.

Dan V. 
Crystal T.
Mallonya A.
Monica G.

**Comment by Nadin-Nader** [comment]
@TracyLinder I looked into this and found that all of the users listed have the LC (Licensing -Standard) Permissions. What is it they are trying to do so i can see if the Advanced setting does it?

**Comment by Nadin-Nader** [comment]
Spoke to Crystal and found that they may be going to the Folder menu instead of the License folder to look up Licensees. I also informed her that all of the users listed have permissions to the folder needed and to let me know if they were just in the wrong menu.

**Comment by Nadin-Nader** [comment]
All users Except Crystal are good to go. Sending to CTM as Jenice said they would have to look into why Crystal is the only one that cant access the Licensing menu or make payments to it. I have created **_INC0241911_** and i let Jenice know

**Comment by Nadin-Nader** [comment]
CTM has resolved the issue
