### ISSUE TITLE
Bug: ATD SIF Review Process Attempts

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10672]
### There are a bunch of attempt types on the process that shouldn't be there. 
- _It looks like the entire list of valid attempts._
- This is happening in test also
<img width="576" alt="Screenshot 2022-11-02 at 10 50 19 AM" src="https://user-images.githubusercontent.com/49930868/199537012-c3a0cf7f-9ce5-4d61-82bc-9757def95e2e.png">

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder / @Nadin-Nader - Analysis is in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Attempt results are in Localhost ONLY; it is missing in V7DEV/TEST/PROD environments.


![image](https://user-images.githubusercontent.com/44907715/199831479-1d43cc30-a9d5-4b67-86bb-08765e7bd909.png)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan ok lets get them to the other environments please

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Its looking good in TEST and Martin confirmed that it is in PROD as well. Please UAT in PROD so that this can be closed.

![image](https://user-images.githubusercontent.com/44907715/200407146-ad6f3f13-10c1-4cbb-bd19-81115dd526c6.png)

**Comment by TracyLinder** [comment]
This is fixed. Closing.
