### ISSUE TITLE
Move Over Bond Charts Excel files to Google Sheets

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#10681]
Currently, I have all the excel files that help power the [bond dashboard](https://app.powerbigov.us/links/JEoSaXVmsi?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare) are just inside a OneDrive folder on my personal OneDrive account. We should move these over to a ~~sharepoint OneDrive folder~~ Google sheet that would be more safe incase my account gets deleted or something strange.

**Comment by dianamartin** [comment]
@Charlie-Henry the DTS SharePoint site?

**Comment by Charlie-Henry** [comment]
Does that work? Would Meredith, others be able to edit files that are in there?

**Comment by dianamartin** [comment]
@Charlie-Henry the dashboard is Bond related? Does it make sense for it to live in a separate site or their own Project Delivery SharePoint files?

**Comment by Charlie-Henry** [comment]
It is bond related. I think that makes sense @dianamartin

**Comment by Charlie-Henry** [comment]
Going to close this out. I've moved these files over to google sheets in the DTS drive.
