### ISSUE TITLE
Urgent Cashier Permissions for Isabelle S.

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10686]
### Isabelle S. needs the same AMANDA permissions as Candace C. 
- This is urgent due to staff shortage. 
- Requested by Gilda P.
- Double check that she has LC permissions

**Comment by Nadin-Nader** [comment]
@TracyLinder i verified and her permissions match that of Candace

**Comment by Nadin-Nader** [comment]
@TracyLinder i have made the users cashier rights advanced. Please let me know if they just need Standard. She is also in the Licensing Standard group just like Candace
I will ask them to test out th eAdvanced permissions to see if thats whats needed

**Comment by Nadin-Nader** [comment]
Sent email to Isabelle asking her to test out her new Cashier permissions:

> Good Morning Isabelle,
> 
> Hope you are doing well. I was reaching out to inform you that I have made some changes to your AMANDA V7 account. I have added more Cashier rights to you and Candace’s AMANDA accounts.
> Please go ahead and clear your cache, log out and log back in and test the cashier functions. Once you have tested them please let me know if this works for you or not.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> Product Delivery Manager

**Comment by Nadin-Nader** [comment]
Waiting on a response

**Comment by Nadin-Nader** [comment]
@TracyLinder looks like the permissions change worked, Closing:

> 
> Sent: Thursday, November 3, 2022 3:32 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>; Powers, Gilda <Gilda.Powers@austintexas.gov>; Calderon, Candace <Candace.Calderon@austintexas.gov>
> Subject: RE: Cashier and LC permissions
> 
> Yes this looks like it is all good. 
> 
> 
>  	Isabelle S.
> Administrative Specialist
> Austin Transportation Department
> Main (512) 974-1150

**Comment by Nadin-Nader** [comment]
@TracyLinder looks like the permissions change worked, Closing:

> Sent: Thursday, November 3, 2022 3:32 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>; Powers, Gilda <Gilda.Powers@austintexas.gov>; Calderon, Candace <Candace.Calderon@austintexas.gov>
> Subject: RE: Cashier and LC permissions
> 
> Yes this looks like it is all good. 
> 
> 
>  	Isabelle S.
