### ISSUE TITLE
Document steps to decommission test instance

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10685]
- Manually decommission current outdated test resources
- Create gitbook page to kick off new docs - and document this process 

Outcome: https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/dev-guides/moped-test-system/manual-resource-teardown

**Comment by frankhereford** [comment]
This has been completed and the document has been linked above. Here's a slack thread with a bit more info.
