### ISSUE TITLE
[Enhancement] Ability to track the workgroup responsible for delivery

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10682]
During yesterday's sprint review, we reached agreement that the Project **sponsor** should be the primary funder of a project and generally its biggest champion. This is a pivot from our current definition, which says. that the sponsor is workgroup responsible for delivery.

### In scope

- Add a new autocomplete field called **Lead** to the project summary page. The project lead should be selected from a list of entities in the `moped_entity` table.
- update our documentation related to these fields.

### Out of scope

- ability to search for projects based on this field (will make a separate issue)
- ability to view this field in the project list
- activity log tracking

### Todo

- Add a nullable field called `project_lead_id` to the `moped_project` table. 
- Add a foreign key constraint from `project_lead_id` to the `moped_entity.entity_id` field. `ON UPDATE CASCADE` and `ON DELETE SET NULL`
- Track the object and array relationships in Hasura
- Grant Editor and Viewer permissions to this field
- In the UI, add an Autocomplete input to populate this field. This is the same source data used by the Sponsor field. The input field should be placed below Status Update and above the existing Sponsor field on the project summary page

**Comment by johnclary** [comment]
@johnclary spell out the table name and where on the summary page this needs to go.

**Comment by chiaberry** [comment]
@johnclary did the mug want to make this field required when creating a new project?

**Comment by johnclary** [comment]
there was a bit of support for it, but not enough to rush this - thanks for checking.
