### ISSUE TITLE
AMANDA Portal Typo on rw-street event info (Event Type) (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10692]
### Fix the type on info Event Type

<img width="935" alt="Screenshot 2022-11-03 at 11 09 56 AM" src="https://user-images.githubusercontent.com/49930868/199773870-790a66a2-6bae-4f01-bc55-e6ba92accf1b.png">

**Comment by SubhaShroff** [comment]
@Nadin-Nader I submitted a DEV/TEST merge request to fix this. - SCTASK0263292.

**Comment by Nadin-Nader** [comment]
@SubhaShroff UAT Failed on TEST. There are now 2 options. One, is the old misspelled one and the other is spelled correctly. We only need the correctly spelled option "Neighborhood Block Party"

![2022-11-22_09-12-47.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/38134d78-9384-4ada-b1f6-02c2c2eff6f4)

**Comment by SubhaShroff** [comment]
@Nadin-Nader This looks like cache issue. Now the old value is not there in configurations also. Please ask the user to do clear browsing history and try.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  After your Team Approval, I submitted PROD merge request - [SCTASK0266630](https://atx.servicenowservices.com/sc_task.do?sys_id=0b11520a1b93191091528407624bcbb2&sysparm_record_target=sc_task&sysparm_record_row=1&sysparm_record_rows=1&sysparm_record_list=request_item%3Dfe11520a1b93191091528407624bcb66%5EORDERBYnumber).
Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  PROD deployment is done.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to PROD

**Comment by Nadin-Nader** [comment]
I reached out to Alexis T. since Maria is out and asked her to UAT this on PROD.
Waiting on Response

**Comment by Nadin-Nader** [comment]
Alexis responded saying that it is fixed. Closing card:

> [1:18 PM] Nader, Nadin
> Hi Again. hey when you have a chance, we fixed the Typo on the Info > Event Type for the Neighborhood Block Party can you verify that it is spelled correctly and let me know?
> 
> [2:03 PM] T, Alexis
> Yas! let me check!
> 
> [2:39 PM] T, Alexis
> all fixed
