### ISSUE TITLE
Update OSE Permit Instruction Popup on Portal (SS) (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10693]
**Acceptance Criteria**
- The help text at the URL below needs to be updated:
https://abc.austintexas.gov/web/permit/permit-instruction?reset=true&t_permitInstructionID=31 

- The new help text is provided below. 

Permit Instructions

Right of Way (RW) - Street Event Permit

Special Events that use any part of the right of way (sidewalk, parking space or street) require a permit that is managed by the Austin Transportation,  Office of Special Events.

Please go to the linked Transportation Special Events webpage (https://www.austintexas.gov/department/austin-transportation-department-special-events) for more information on the permit requirements or contact TransportationSpecialEvents@austintexas.gov or call 512-974-6501

**Comment by TracyLinder** [comment]
<img width="674" alt="Screenshot 2022-11-03 at 11 15 39 AM" src="https://user-images.githubusercontent.com/49930868/199775166-4f031dbd-a592-4a5f-8a29-45ad3eb7091f.png">

**Comment by vschandramouli** [comment]
https://www.austintexas.gov/ace-event-planning-guide/ace-event-planning-guide

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0279034 is submitted for DEV deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I tested this on DEV portal and it looks as follows. Please review and let me know to get it deployed on TEST. 
![image](https://user-images.githubusercontent.com/51680715/213013208-0692acd1-4762-48f0-905c-8c71681c2047.png)

**Comment by Nadin-Nader** [comment]
@subha please send to TEST

**Comment by SubhaShroff** [comment]
Thank you @Nadin-Nader.
SCTASK0280142 - is submitted for TEST deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is deployed and I tested it on TEST portal. The instruction text looks as expected and ready for UAT.

**Comment by SubhaShroff** [comment]
### Status:
Since a month, its been up for UAT.

**Comment by SubhaShroff** [comment]
Thanks @Nadin-Nader. 
I submitted PROD promotion request - SCTASK0290433.

**Comment by Nadin-Nader** [comment]
Sent Chat message to Maria informing her that this is on PROD and to let me know if all is well.

**Comment by Nadin-Nader** [comment]
According to Maria during the OSE review 3/7/23, this is good and working well. It can be closed
