### ISSUE TITLE
ATD Finance Special Void Permissions (NN, Waiting for results from Users)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10717]
### ATD finance users need to be able to void payments made prior to the current day. Currently only Dan V. has this permission.

**Users who need permissions:** Erin W. Melissa B. 

----
**Note:** We attempted to do this a few months ago and hit road blocks with corporate finance. See the email thread [here](https://cityofaustin-my.sharepoint.com/:b:/g/personal/tracy_linder_austintexas_gov/ETuv3_rk3SxHi1SaBQtjpzIBnP8DD6HZrqoLiALivNNVsA?e=zAX2Cv) (internal only).

**Comment by TracyLinder** [comment]
### Meeting Scheduled 
- With key stakeholders on 11/17

**Comment by Nadin-Nader** [comment]
I asked Erin again to Verify if she had Void permissions. I also let her know that I also gave the rights to Melissa, Crystal and Jeremy.  Ashlande Evans and Denise Ramirez. Do not have AMANDA PROD accounts.

Waiting on Respose

**Comment by Nadin-Nader** [comment]
No Issues have been reported by Erin or Melissa. closing
