### ISSUE TITLE
Enhancement: Automate Valet Operator Fees

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10712]
### Users are still inserting Valet Operating fees manually. We need to add/update folder processes to automate the various fees. Scoping required. 

After scoping this with the team we determined there is no business need to automate or update valet operating fees. Closing.

**Comment by TracyLinder** [comment]
Valet Operating permits are under Kim's team. Check in with her for scoping.

**Comment by Nadin-Nader** [comment]
@vschandramouli please schedule time with Kyle and Kim to scope

**Comment by TracyLinder** [comment]
- When should the fee insert?
    - Kim isn't sure there's much value in automating this fee
    - Paloma wants it on the insert & run menu 
    - `User will manually insert the fee by using the Insert & Run Menu. `
 
- Is this applied for online? Is 'Pending Payment' before Internet Pending apply in this scenario? 
    - No. Staff manually creates these. Internet Pending solution isn't viable.  

- Which fee(s) are included in the scope of this request? 
    - Valet Operator Initial
    - Valet Operator Renewal
    - ATD Tech Surcharge 

- Which sub & work types are in scope? 
    - It doesn't matter. The fee menu is determined by folder type only. (I think)

**Comment by TracyLinder** [comment]
### Friday ROW Review

- After scoping this with the team we determined there is no business need to automate or update valet operating fees. Closing.
