### ISSUE TITLE
Define the user stories for a MDS per-trip fee Report UI for PE Staff

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#1072]
- With the [new per-trip fee policy](https://www.austinmonitor.com/stories/2019/12/austin-transportation-to-set-per-trip-fee-for-dockless-vehicles/), we need to understand staff needs around data management from the MDS trips endpoint to support accurate billing.
- What would a trips audit log look like? What timeframe would be good for aggregating trip counts?
- How might we publish trips totals by provider to Socrata?

**Comment by JaceDeloney** [comment]
This will be handled through a simple report. Refer to #1414, which is scheduled for Sprint 19
