### ISSUE TITLE
New Batch Report for TCP Payments (Users Reporting a Blank Report) (01/10 Sprint) (SS)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10731]
### Add report to ATD Report library & allow user to query by payment start & end dates. 

(Requested by Tracy as part of TCP Intake upgrades on #9164)

**Acceptance Criteria** 
- A new batch process needs to be created that emails this new report every day (12:01 AM) (both in PDF and Excel format) to the following email addresses: 
Kensley.Inostroza@austintexas.gov
Samson.Negeri@austintexas.gov
Nayelly.Parra@austintexas.gov
Darren.Ujano@austintexas.gov
tcpreview@austintexas.gov
- The emailed report will have the payment details from all payments made the previous day on GF folders with subtype ATD.
- Title of report should be **TCP Payments**
- Report Parameters while generating report from ATD Report Library : Payment Date Range (Start Date and End Date)
- Report fields: Provided in attachment below
[https://app.zenhub.com/files/140626918/b09fbbd0-0058-4378-8f65-5a0ce24e5b4b/download](https://app.zenhub.com/files/140626918/b09fbbd0-0058-4378-8f65-5a0ce24e5b4b/download) 

- Users should be able to generate this report in both PDF and Excel formats from report library
- The report needs to be grouped by Type of Payment.

**Comment by TracyLinder** [comment]
### Scoping scheduled 11/21
at 1pm with Darren & Alyse

**Comment by TracyLinder** [comment]
### Report Scoping Notes

- Yes on the batch. If it's not helpful, we'll turn it off. Run every day
    - tcpreview@austintexas.gov, Alyse, Samsun, Darren, Andrew E.  
- Add the report to ATD Library


**Report Info:**
- Group by payment type with COS at the bottom
- Fields: F.referencenumber, f.foldername, fee name, payment date, Applicant info, payed by info

**Comment by Nadin-Nader** [comment]
@vschandramouli  can you see if this is still a need and/or priority?

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @vschandramouli  Can I get the list of fees and folder types for which the report should run?

**Comment by TracyLinder** [comment]
**Update:**
- The system won't allow a batch job to attach both an excel and PDF to one email; two emails would be needed to accomplish the AC. 
- Tracy suggesting to email only the excel data, and to add the PDF version to the ATD report menu.
- Title of report should be **TCP Payments**
- I removed from the AC that the data should be grouped by payment type with COS sorted at the bottom.

**Comment by SubhaShroff** [comment]
Thank you @TracyLinder.
 I am adding PDF format. Please review this as well.
[99030_TCP_Payments.pdf](https://github.com/cityofaustin/atd-data-tech/files/13441763/99030_TCP_Payments.pdf)
CC: @Nadin-Nader  @vschandramouli

**Comment by vschandramouli** [comment]
Samson N has confirmed that emails will be sufficient in just excel format

CC @TracyLinder @SubhaShroff @Nadin-Nader

**Comment by vschandramouli** [comment]
Samson N has confirmed that emails will be sufficient in just excel format

CC @TracyLinder @SubhaShroff @Nadin-Nader

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has sent to the CTM Team to be deployed to TEST under **SCTASK0375024**

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0375024 looks closed but the report 99030 is not deployed or it disappeared as it sometimes happens. Have asked George to have a look at it as he had worked on it. 
Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader This is on TEST and I tested for it. Ready for UAT. Thanks.

**Comment by Nadin-Nader** [comment]
Response from Kyle:

> [9:18 AM] Kampe, Kyle
>     Thanks Nate. I've asked the designated recipients to follow up with me tomorrow morning to ensure they received the report via email. Standby.


Waiting on response

**Comment by SubhaShroff** [comment]
@Nadin-Nader Based on Kyle's approval on Teams, I am sending this for PROD deployment.  And removed Nayelly Parra's email address from DEV/TEST. 
![image](https://github.com/cityofaustin/atd-data-tech/assets/51680715/a763e8af-1401-41a6-b53e-317b70eeb14c)

@Lpriya-LIT  Please create PROD deployment request.
[10731- PROD Manual Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/13665504/10731-.PROD.Manual.Deployment.Plan.docx)

**Comment by Lpriya-LIT** [comment]
@SubhaShroff Created Prod deployment request , SCTASK0378270

**Comment by SubhaShroff** [comment]
Thank you  @Lpriya-LIT.
@Nadin-Nader This is deployed in PROD.
Batch Job is 204. And the menu report also looks good to me. Its ready for the user on PROD.

**Comment by vschandramouli** [comment]
@SubhaShroff Just FYI, confirmed from Kyle that users have tested both email and menu reports.

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff We need to reopen this card. I received word from the email recipients that the Excel report showing up in their emails each day is blank, even though they know for certain that payments have been made that should show up here. I ran the report in AMANDA and it functions correctly, so the problem must be with the Excel file that gets emailed.

**Comment by KyleErich** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/130776506/0a3744e8-2d92-4b44-b0d7-d2322f8f7fe8)
![image](https://github.com/cityofaustin/atd-data-tech/assets/130776506/c9386f6e-b9f0-49c2-9bf8-23a26dcaa32e)

**Comment by SubhaShroff** [comment]
Thank you @KyleErich.
@Nadin-Nader @KyleErich I tested it on TEST and looks working as expected. And also, verified the query on PROD and it is same as in TEST. I am wondering if there is any way that I can verify the reports on PROD.
Can you forward those empty excel emails as it is or can we verify that on a call?
cc: @vschandramouli

**Comment by KyleErich** [comment]
Email forwarded.

**Comment by SubhaShroff** [comment]
@KyleErich @Nadin-Nader There was an issue in the configuration on PROD. Anu corrected it for me. Now the emails should come with data if there was any previous day payments. Please verify and let me know.
Thanks.

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff An email recipient confirmed for me that this is working now. Thank you.

**Comment by Nadin-Nader** [comment]
This has been approved by Kyle. Closing
