### ISSUE TITLE
Update/Refactor current MDS ETL scripts

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#1074]
- [x] Define the modifications required to the existing Python script that interacts with PostgREST
- [x] Define the modifications required to the existing PostgreSQL DB
- [x] Define the modifications required to export to AWS S3
- [x] Define the modifications required to the existing Python script that publishes to Socrata

With these requirements captured, we can either modify this issue with those task or spin off new issues.

**Comment by sergiogcx** [comment]
The data currently extracts data from providers and uploads to S3, and there is another process that inserts  our data into PostreSQL.

**Comment by sergiogcx** [comment]
Stuff works and publishes to Socrata, closing.
