### ISSUE TITLE
Bug: Error on Curb/Gutter Inspection Fee

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10745]
### Example PROD ROWID 12953903
- I was unable to recreate this bug in test. (Tracy)

----
<img width="580" alt="Screenshot 2022-11-09 at 3 02 25 PM" src="https://user-images.githubusercontent.com/49930868/200941083-d27e1401-106f-475a-ab15-52487826fd78.png">

**Comment by TracyLinder** [comment]
I was unable to recreate this bug in test. Let me know if you need the test RSN.

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader The infovalue for 76614 - Total linear footage of curb/gutters is needed to calculate this fee. In This prod folder (folderrsn - 12953903) , the info value is blank. If there is a value for this info , the fee will get inserted . The info value has to be greater than 0 ( Range 1 - 999999999).

**Comment by TracyLinder** [comment]
### Update

Pending response from Kensley (in Teams). 

<img width="833" alt="Screenshot 2022-11-10 at 3 09 33 PM" src="https://user-images.githubusercontent.com/49930868/201206483-b5be1002-c743-446e-91fc-6d72207a4deb.png">

**Comment by TracyLinder** [comment]
### Resolution

Kensley added a number to the info and that resolved the issue. She said there were others yesterday she knows she added the number on the info tab, but the system didn't save it. Something to keep an eye out for.
