### ISSUE TITLE
Create SIF Data Report & Batch Job (UAT on PROD) 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10759]
### Systems Development needs access to current SIF fee data on the 1st and 15th day of each month. Create a batch job that emails raw SIF data to a distribution list. 

**Customer:** Dan H.

**Batch Job Info:**
- Report output needs to excel file or CSV
- Email the report on the 1st and 15th of each month. 
- Email to Dan H. + Madeleine H. + Van P. + Dan V. + Erin W _(Ask Tracy for emails)_

**Report Info:**
- Query by the bill generated date
- Include all bills generated between 1/1/2022 and Current Date. 

<div ccp_infra_version='3' ccp_infra_timestamp='1672862734426' ccp_infra_user_hash='881534590' ccp_infra_copy_id='a2a4f593-4d9f-4958-ae6c-10a8ab9d54f2' data-ccp-timestamp='1672862734426'><html><head><meta http-equiv=Content-Type content="text/html; charset=utf-8"><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"></head><body link="#0563C1" vlink="#954F72">

S.No | FolderRSN | Folder Indate | FolderName | FolderType | Consumer District | SIF District | Bill Number | Date Generated | Paid in Full Flag | Bill Amount | Total Paid
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 12964428 | 6/23/2022 | 5717 LOST HORIZON DRIVE | SIF | 10 | E | 7661014 | 7/11/2022 | Y | 3621 | 3621
2 | 12964428 | 6/23/2022 | 5717 LOST HORIZON DRIVE | SIF | 10 | E | 7657551 | 7/5/2022 | Y | 3621 | 3621
3 | 12964428 | 6/23/2022 | 5717 LOST HORIZON DRIVE | SIF | 10 | E | 7651926 | 6/27/2022 | C | 3621 | 0
4 | 12964428 | 6/23/2022 | 5717 LOST HORIZON DRIVE | SIF | 10 | E | 7650783 | 6/24/2022 | Y | 3621 | 3621
5 | 12964428 | 6/23/2022 | 5717 LOST HORIZON DRIVE | SIF | 10 | E | 7661324 | 7/11/2022 | Y | 3621 | 3621

</body></html></div>

**Comment by TracyLinder** [comment]
@Nadin-Nader this is a high priority from the executive team. It needs to be in PROD no later than 11/30/22 at the latest, but delivering ASAP in preferable. Thank you!

**Comment by TracyLinder** [comment]
### ATD Finance 
Might be interested in the data. I emailed Van asking who from finance should be included on the distribution list.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Working with Jenice on access for Quick and Simple report in DEV

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps Cm team to be deployed to **DEV** under **_SCTASK0266230_**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Generated batch report using quick and simple report; here is the sample report email generated from DEV. Now I need the From email id and To email id's that the report has to be sent to. 

![image](https://user-images.githubusercontent.com/44907715/203589235-5eff7646-c324-4f0b-9b42-d7419a2d9b7b.png)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Spoke to Tracy to confirm the format and also to get the from and to email addresses; as per review comments, updated the query and submitted DEV DP on 23rd November. 

DEV DP with updated query to add label as well as council districts data; kindly approve and create task id for the same. 

Commit ID: [0eb257a951f6](http://coaamandadevops02.austintexas.gov/R5:0eb257a951f68ac1ec2d20ef37981f9b7aebda2e)

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Waiting on FROM & TO email address to update the batch job in dev and promote to TEST.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan I'm not allowed to type email addresses in github issues; I will send them to you in a teams chat.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - TEST DP’s of #10759 submitted. Kindly approve and create task id for me. Updated the email Id’s as per Tracy.

Valid Batch job created in DEV which also needs to be promoted to TEST and its manual commit.

JOBRSN: 188 - ATD SIF Data Pull (Quick & Simple Report) 

Commit ID’s: 
Order 1 -de8157a3a3eb
Order 2 -0eb257a951f6

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  I have sent this to the DevOps CM Team to be deployed to TEST under **SCTASK0271960**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been deployed to TEST please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - George fixed the manual commit job setup in TEST, and ran once to test the same. The recipients must have received the excel but there is no test data as such. I am not seeing PROD data also when I run the query in PROD, max in date that I see was 11/07/2022. let me know how this can be tested moved to PROD.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted DEV DP for your reference. I have updated the query to pull the data based on payment date. Please approve and create task id for me.

Commit ID: 37b1cb013401

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent gain to the DevOps CM Team to be deployed to DEV under **SCTASK0273563**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - TEST DP submitted for your reference. Query is working as expected upon making changes to check for payment date instead of Folder in date. Kindly approve and create task id for me.

Commit ID: 37b1cb013401

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please move this to PROD.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - PROD DP’s of #10759 submitted. Kindly approve and create task id for me.

Commit Order –
1.	de8157a3a3eb
2.	0eb257a951f6
3.	37b1cb013401

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  @TracyLinder This has been submitted to the DevOps CM Team to be deployed to PROD under **SCTASK0275628**

**Comment by TracyLinder** [comment]
@Nadin-Nader @Sreelatha-BlazeKannan 

The query needs to be updated after reviewing with the stakeholders. I just updated the AC and Sree already has the updated query.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP Submitted with updated query. Kindly approve and create task id for me.

Commit ID: [06015bbff735](http://coaamandadevops02.austintexas.gov/R5:06015bbff735d1f190da6b4c949ed562aa29e4c4)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP Submitted by removing date generated check. Kindly approve and create task id for me.

Commit ID: [d2b5aa92fa90](http://coaamandadevops02.austintexas.gov/R5:d2b5aa92fa9084c602360414e54f44a8e49b2877)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0276479**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder  This has been deployed to DEV please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV, results are as expected and ready for TEST Move. Can I submit TEST DP?

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  I have sent this to the DevOps CM Team to be deployed to TEST under **SCTASK0280028**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to TEST. Please UAT and let me know

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I see, the updated query in Valid adhoc table; I cant run the batch job in TEST, but the existing batch job will run on every Monday and pickup this new query for data pull going forward. Ready for UAT in TEST.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan  since we can't run batch jobs in TEST, go ahead and move to PROD please.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - PROD Commit submitted; kindly approve and create task id for me.

Commit ID Order 1 – 06015bbff735
Commit ID Order 2 – d2b5aa92fa90

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been deployed to PROD

**Comment by TracyLinder** [comment]
### PROD Not Working?

Hi @Sreelatha-BlazeKannan the customer said they didn't get a report emailed to them yesterday. They also get a report from the system every Monday that I think is from Test. I'm going to forward that to you.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Tracy, I see that the excel that you sent me is coming from DEV every Monday; I have reset the active flag to No so, this cant happen going forward. However I see that in TEST Batch Job Output Destination is not set. I will check with CTM Team to make this update in TEST and PROD so that report will come from PROD every Monday as planned.  And also I will set the active flag to NO in TEST as well.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I spoke to George regarding this, TEST Output destinations are set now, but made the Active Flag to 'No' so that it would not run in TEST. Verified in TEST (Not tested), George updated the same Output destination details in PROD and set the Active flag to 'Yes' Going forward job has to run and send the excel data to the recipients without fail. We need to get the confirmation when it runs on Monday then this card can be closed. Thank you!

**Comment by TracyLinder** [comment]
### Prod Confirmed ✅

- Dan H. emailed saying he got the report email and the data is perfect. Closing this. 
Thank you @Sreelatha-BlazeKannan for your great work!
