### ISSUE TITLE
Requery all-time micro mobility data

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#1075]
We have a postgres database of existing data. But we've probably missed some records. We should requery the data and check how big the diff is.

**Comment by sergiogcx** [comment]
Just some quick math on this issue, when we query data from a provider for the past 1 hour it can take between 10 to 60 seconds.

If we are going to gather data for the entire year, there are (24 hrs x 365) = 8760 hrs. in a year, which translates directly into 8760 minutes to gather all data for that year.

For both 2018 and 2019, we are looking at (2 x 8760) = 17520 minutes, in hours (17520 / 60) = 292 hours

292 hours translates into 12.17 days.

So gathering data for two years will take 12-13 days for each provider, if each request stays under a minute.

The plan would be to run 10 concurrent processes total (one for each provider), and let the process run for 10-15 days.

We could speed up the process by multi-threading, but we could end up choking the MDS servers, or our own.

**Comment by sergiogcx** [comment]
This is a project that may take weeks to run, separated from epic so we can close the Epic and begin this process separately. The tools are ready, we just have to decide on how we want to go about making this happen.

**Comment by sergiogcx** [comment]
Moving to in-progress.

**Comment by sergiogcx** [comment]
One of the main challenges in doing this is concurrency. The servers are small and they only handle X amount of requests at the same time. The servers should be able to handle 10 requests per second concurrently, but not entirely sure how well the mds providers will handle the requests.

What I am thinking of doing, is:
- Allow a few seconds between requests (to not overwhelm the MDS endpoints)
- Run only one process per provider (a total of 7 concurrent processes)
- Do not insert to postgres or socrata, first upload the entire dataset to S3, then either process to postgres or download the JSON files and turn them into CSV files for insertion.

**Comment by sergiogcx** [comment]
I am fixing to have this process running over the weekend and request data for two months. See how the process behaves, see if there are any errors and make adjustments. If the process runs well, then we can have more assurance the process will work as expected.

**Comment by sergiogcx** [comment]
I gathered data one month for all providers (except lime and bird which do not respond for January 2018), and the test results were good. I am going to proceed gathering an entire year, Jan 2018 through Jan 2019.

For lime and bird, I will begin from April 15th to January 2019, this is because they both seem to have a limit on how far back you can query data (apparently 2 years).

**Comment by sergiogcx** [comment]
Currently Running

```
Lime:
• Importing from January 2019 to Jan 2020 (7984 blocks left)
Bird:
• Imported from April 15th 2018 to January 2019 (14206 blocks left)
Ojo:
• Running from Jan 2018 to Jan 2020 (16776 hour blocks)
Wheels
• Running from Jan 2018 to Jan 2020 (16776 hour blocks)
Spin
• Running from Jan 2018 to Jan 2020 (16776 hour blocks)
Lyft
• Running from Jan 2018 to Jan 2020 (16776 hour blocks)
Jump:
• Running from Jan 2018 to Jan 2020 (16776 hour blocks)
```

**Comment by sergiogcx** [comment]
All of these tasks completed, it's almost 60gb of data (encrypted). What needs to happen next is:

- [ ] Scan for missing blocks (based on exact dates of operation, as provided by Jace)
- [ ] Download missing blocks
- [ ] Re-gather all data
- [ ] Convert json data to CSV 
- [ ] Insert to database

**Comment by amenity** [comment]
@sergiogcx @JaceDeloney - any updates on this?

**Comment by johnclary** [comment]
Sergio and I reprocessed a bunch data this fall. Beyond that I don't think we need to this. Ride Report can supply older data as needed. Closing.
