### ISSUE TITLE
MDS ETL Error Reporting

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#1076]
- How might we send timely and helpful error logs?
- Potential Airflow to Slack integration

**Comment by sergiogcx** [comment]
Error reporting happens in two places at the moment:

1. It happens in Airflow, whenever there is an error running a script in Airflow, the script will stop and provide the exact cause of the error:

![2020-02-22_12-44-38.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/395e50bf-27fc-4e40-907a-31d472312731)

![2020-02-22_12-46-23.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/7341bfef-91e0-4a48-9fef-2328e76a4d5b)

2. The second place happens in the schedule/tracking system we are implementing, whenever a task fails, the status is updated to the database, with messaging and exact cause of the problem.

![2020-02-22_12-47-23.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/7f8e1360-b450-4944-974f-db4d9b2ada19)

**Comment by sergiogcx** [comment]
The code has been merged to master and it is tested to work, closing.
