### ISSUE TITLE
Bug: Online payment not reflected in back-office

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10763]
### Online payment failed to update backoffice on 
1. RW, ROWID 12942417
2. RW, ROWID 10106661, Bill #7803115

**Resolution: Dan V. manually applied the payment.**

- [Here](https://cityofaustin-my.sharepoint.com/:b:/g/personal/tracy_linder_austintexas_gov/EYEHzRETkp5LqadkDImbaZUBXm3ZtIDn7F_R9Z6uLBA8oA?e=f5KVfW) is they payment confirmation

<img width="762" alt="Screenshot 2022-11-10 at 3 15 25 PM" src="https://user-images.githubusercontent.com/49930868/201207464-ae17d5d7-d321-4ec0-a1b7-5d6f407393fc.png">

**Comment by TracyLinder** [comment]
### Ready for debugging 
- @Nadin-Nader this is ready to be assigned to a dev for debugging. The customer who reported this was LaTonya. I've already sent this to Dan V. (ATD Finance) to ask him to apply the payment.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader I tried to recreate this prod issue in Test . In Test , the payment from portal is reflecting in Backoffice. Not sure why it didnt work in that prod folder.
