### ISSUE TITLE
Set up meeting with CTM to better understand enterprise data structure/standards

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#10785]
# Background
- Re-vamped Parking Inventory data layers
- Jaime had updated the Parking Inventory (AGOL)
- She created new Parking Inventory GISMAINT

GISMAINT | GIS DM
-- | --
Jaime created 5 layers | 
1 layer is Test for the user | 

CTM discovered that ATD wasn't using GISDEV environments. 

## Database Workflow
- GISDEV  to GISMAINT to GISDM to AGOL
![image](https://user-images.githubusercontent.com/21112975/202275805-d22ffd69-3f73-44e6-a01e-be3d18e21e4b.png)

## Ideas
- Use versioning as team expands and grows larger
- Make sure other ATD GISers know the database workflow process
- Figure out which datasets are good candidates for this process

## Action Items
- [ ] Create questions to ask CTM
- [ ] Set up meeting with CTM (include Rajibul, Adrien)

**Comment by dianamartin** [comment]
@andrewshensky put in a CTM Service Now after the holidays and wait to schedule a meeting, to figure out CTM contact person.

**Comment by andrewshensky** [comment]
This meeting was scheduled and took place on 11/30 by Ben V. Rajibul, Zach, and I were able to attend. The meeting covered setting up versioning and the proper use of MaintDev and MaintTest.
