### ISSUE TITLE
Rework SR process for Finance

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10794]
Rework the flow of the Service Requests. 
@dianamartin add new diagram from [Miro](https://miro.com/app/board/uXjVPaEmIPc=/)
![image](https://user-images.githubusercontent.com/21112975/202823516-28f425e8-8f71-47c7-a5da-f464268a2982.png)

Referencing #10111

## Requirements
- [x] Add email notification when submitted request is submitted - atdtaskbudgetrequests?
- [x]  ENHANCEMENT: Ability to have employee self assign 
- [ ]  ENHANCEMENT: Improve Submitted button - Add email notification for manager
- [ ]  ENHANCEMENT: Improve Decision button - Approve or Completed
- [ ] ENHANCEMENT: Add email notification to requester when final decision has been made
- [x] NEW FEATURE: Attachment function - details page for customer
- [x]  NEW FEATURE: Customer Page for Service Request

**Comment by dianamartin** [comment]
# 11/18
- [x] Cleaned up Service Request pages that I was prototyping
- [x] Updated everything to Service Request "Task" to "Job"
- [ ] There are 2 core pages now
- Service Requests | Requester
- Service Request Jobs (Finance Staff) - can see SR Jobs and SR list, can self-assign themselves
- [x] Added email notification for Finance Staff upon submission from requester
![image](https://user-images.githubusercontent.com/21112975/202823472-91d76867-8298-4f04-b05f-9c5c3e835cb9.png)
- [x] Updated Request ID to a normalized ID, `FSR22-11-0025`

## Other Work in App
- [x] Added filter on "Account Administration" - User Status = Active

**Comment by patrickm02L** [comment]
Diana needs to test this to see if it works properly. Also, address Sharon's email of suggestions for this round of updates. Diana will put priority of this on Monday, Dec 5th to deep dive into updates.

**Comment by patrickm02L** [comment]
Talk about [Sharon's spreadsheet.](https://docs.google.com/spreadsheets/d/1krCT42BFNpQdF7n-byglM1CyZBqHfRyb/edit?usp=share_link&ouid=116851567519741176118&rtpof=true&sd=true) in our next meeting.

**Comment by dianamartin** [comment]
# 1/30 -1/31
## Testing
- [x] Tested added a real request example from Sharon's email from Max
- [x] Request had 1 subproject, 2 FDUs, 2 BGEX, 2 TKs
- [x] Confirmed email is sent to Finance team (will change email address when ready)
- [x] Updated email notification by putting "Business Justification" on body of email

## Updated Add SR Job Form
- [x] Added Service Request connection
- [x] Added Service Request job - self connection

## Updated the Service Request Jobs page
- [x] created new menu for "Jobs by Type" - renamed to "All"
  - [x] SR Jobs table grouped by Job Type
- [x] fixed broken filter links
- [x] Grouped main SR Jobs table by SR ID
- [x] enhanced fields, switched out to basic "SR ID", "# Jobs", "Jobs" - on "Service Requests | Admin" table
