### ISSUE TITLE
[Enhancement] Ensure project list view query is cached

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10799]
When navigating back and forth between the project list and project details, it becomes apparent that the data that powers the project list is not cached.

The desired behavior is that previously queried data is always cached so that the project list is not blocked from rendering. The app should also refetch for updated data in the background.

**Comment by mddilley** [comment]
Started looking into this some yesterday (9/11/23), but I'm going to put it on hold until syncing with John and Chia on other work related to the project list view

**Comment by mddilley** [comment]
Going to keep this one's status as-is for now. Met with John and Chia yesterday, and we identified short term fixes like lower the default number of rows and longer term fixes like exploring alternatives to gql abstract. Caching could help us after looking at those solutions.

**Comment by johnclary** [comment]
@mddilley those resources were super helpful! thanks for your research on this!
