### ISSUE TITLE
Update VZ Polygon Editing documentation

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#10803]
We have new editing workflows for the VZ polygon maintenance project. I'm updating the documentation to reflect these changes.

**Comment by dianamartin** [comment]
Alan has been updating the [Vision Zero Polygon Maintenance workflow](https://atd-dts.gitbook.io/atd-geospatial/miscelaneous/vision-zero-polygon-maintenance)
