### ISSUE TITLE
Onboarding GIS Techs - Nov 2022

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10805]
# Day 1/2
## GIS Tech 1 
- [x] Log into computer
- [x] Access email
- [ ] Review On-boarding [Checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/your-first-week)
- [ ] Set up AGOL account
- [ ] Setup DTS Portal account - Apps
- [ ] Review DTS Data Inventory
- [ ] Check out Open Data Portal
- [ ] Review GIS Onboarding GitBook
- [ ] Set up GIS Community Bloomfire KB
- [ ] Set up Signs and Markings GIS QA - Apps
- [x] Set up Slack - ask Amenity/Diana
- [x] Set up GitHub - need to ask Frank for access
- [ ] Set up GitBook - ask Amenity/Diana
- [ ] Download ZenHub extension

## GIS Tech 2 
- Pick up hardware at 9 am
- Cameron at 10 am
- [ ] Log into computer
- [ ] Review On-boarding [Checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/your-first-week)
- [ ] Set up AGOL account
- [ ] Setup DTS Portal account - Apps
- [ ] Review DTS Data Inventory
- [ ] Check out Open Data Portal
- [ ] Review GIS Onboarding GitBook
- [ ] Set up GIS Community Bloomfire KB
- [ ] Set up Signs and Markings GIS QA - Apps
- [ ] Set up Slack - ask Amenity/Diana
- [ ] Set up GitHub - need to ask Frank for access
- [ ] Set up GitBook - ask Amenity/Diana
- [ ] Download ZenHub extension

# Day 2/3
Tuesday afternoon at Cameron
- [ ] Log into computer
- [ ] Review On-boarding [Checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/your-first-week)
- [ ] Set up AGOL account
- [ ] Setup DTS Portal account - Apps
- [ ] Review DTS Data Inventory
- [ ] Check out Open Data Portal
- [ ] Review GIS Onboarding GitBook
- [ ] Set up GIS Community Bloomfire KB
- [ ] Set up Signs and Markings GIS QA - Apps
- [ ] Set up Slack - ask Amenity/Diana
- [ ] Set up GitHub - need to ask Frank for access
- [ ] Set up GitBook - ask Amenity/Diana
- [ ] Download ZenHub extension

# Onboard Boarding Items
- [ ] Set up GIS Maint/Data Mart accounts - dependency on EID
- [] Access to G drive - Office of Special Events 
- [ ] Planning SSPR

**Comment by dianamartin** [comment]
- [x] jfldd
- [x] sfdfdsf
- [ ] sd

**Comment by andrewshensky** [comment]
This is a dup of #10978.
