### ISSUE TITLE
Identify Provider Readiness for MDS 0.4.x

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1080]
We need to reach out to our MDS providers and understand their current/planned support for MDS 0.4.x.

**Comment by amenity** [comment]
@johnclary - Sprint 16?

**Comment by sergiogcx** [comment]
As of today, this is the current testing of the current versions of MDS per provider:


```
"bird": {
    "version": "0.3.0"
  },
  "jump": {
    "version": "0.3.0"
  },
  "lime": {
    "version": "0.3.0"
  },
  "lyft": {
    "version": "0.3.0"
  },
  "spin": {
    "version": "0.2.0"
  },
  "veoride": {
    "version": "0.2.0"
  },
  "ojo": {
    "version": "0.3.0"
  },
  "wheels": {
    "version": "0.3.0"
  }
```

Last time I ran 0.4 for any of the of the providers (not including ojo or wheels), they did not support mds 4. But I will double-check again later today.

**Comment by sergiogcx** [comment]
MDS 0.4.0 is not yet been standardized and not yet published in the OMF specification:
https://github.com/openmobilityfoundation/mobility-data-specification

Closing until we know there is a new MDS version approved and implemented by the OMF
