### ISSUE TITLE
Need Permissions to Delete People Member Records (NN to follow Up)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10817]
### ATD-ROW needs permissions to delete records off the Member tab of the people record. 
- Example people RSN 5742441, we are all unable to delete any records on the member tab. See #10778 - duplicate records creates a system error and users need to be able to delete them.

**Comment by TracyLinder** [comment]
I'm not sure if this feature was available in V6. The absence of this feature however is causing issues for users.

**Comment by Nadin-Nader** [comment]
@TracyLinder  i would need to create a meeting with Jenice (she is now on Vaca) when she gets back or whom ever is taking on most of her workload

**Comment by Nadin-Nader** [comment]
I was able to give Alexia delete permissions by having her permissions mirror that of Kim's permissions (all except Cashier). Asking Alexia or Kim who all needs these permissions

**Comment by Nadin-Nader** [comment]
Paloma would like for all analysts to have the same permissions in order to Delete people records from the people tab in a folder.
![Accounts to Mirror Kim.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/22b84605-5e86-407b-8155-0e93b29457cb)

**Comment by TracyLinder** [comment]
@Nadin-Nader can you provide an update on this one please?

**Comment by Nadin-Nader** [comment]
@TracyLinder This was completed last week. I also reviewed it again to make sure the changes stuck in PROD and TEST.

**Comment by TracyLinder** [comment]
@Nadin-Nader i tried testing in PROD but the delete option isn't available for me on my record 5187477. Is that a bug or do i not have the permissions?

**Comment by Nadin-Nader** [comment]
@TracyLinder i verified your permissions for the LINDERT account and you have the permissions needed per the Permissions mapping:
Your Permissions on PROD:
![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/bcd0a312-d511-44e3-a187-f2b67192b4ca)

Mapping:
![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/ac10344b-7ee3-4728-9903-26c8acc40edf)

**Comment by Nadin-Nader** [comment]
I also mirrored The users on the list to Kim's account last week (She was able to delete), Waiting on Response/issues (if any) from users. I will follow up tomorrow.

**Comment by TracyLinder** [comment]
@Nadin-Nader I can't see a delete option on people ROWID 5187477 (my account). Here's a screenshot of what I'm looking at. Not sure if it's a bug or I'm doing something wrong. 

<img width="1204" alt="Screenshot 2023-01-25 at 2 19 00 PM" src="https://user-images.githubusercontent.com/49930868/214680960-a3578592-6aac-482a-9f03-95859097abbf.png">

**Comment by TracyLinder** [comment]
OK to close.
