### ISSUE TITLE
Refine activity log for `moped_proj_personnel` and add support for `moped_proj_personnel_roles`

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10810]
1. Switch `moped_proj_personnel` activity event to REST connector
2. Create activity event REST connector for `moped_proj_personnel_roles`

Create new team member

```markdown 
Added **<user-full-name>** to the team**
```

Edit team member - if team member name changes:

```markdown 
Replaced **<previous-user-full-name>** with **<new-user-full-name>**
```

Other team member edits

```markdown 
Edited  **<previous-user-full-name>**
```

Removed team member
```markdown 
Removed  **<previous-user-full-name>** from the team
```

Do not render any other team member edits.

Do not render any role edits? We just want to track them.

**Comment by chiaberry** [comment]
We don't have a way yet to prevent rendering activity log entries, could in the meantime it show a generic Team member **name** was edited?

Right now the other changes a person could do besides adding and replacing would be updating the "notes" part of the table or deleting a person from the team.
