### ISSUE TITLE
Write & submit position descriptions

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10829]
Position descriptions help Coding it Forward understand your team’s early-career talent needs and goals for the summer. Please [download a copy of our position description template](https://www.codingitforward.com/2023-partners#:~:text=download%20a%20copy%20of%20our%20position%20description%20template) and answer the included questions.

Note that you should submit one position description for each role you are hiring for—unless the positions are identical. For example, if you are hiring two data scientists with the same responsibilities, you only need to submit one description, but if you are hiring one data scientist and one data analyst, then you should submit two descriptions.

Each description should be representative of the role you are hiring for and does not need to be project specific. This allows for flexibility in the case that your team’s priorities shift between now and June. 

Before you start writing your Position Description, please review the roles that we hire for in our [Role Descriptions Document](https://www.codingitforward.com/s/2023-Role-Descriptions.pdf) and review the following Position Description examples: 

- Example 1 - [Data ](https://www.codingitforward.com/s/2023-PD-Example-1-Data.pdf)
- Example 2 - [Design](https://www.codingitforward.com/s/2023-PD-Example-2-Design.pdf)
- Example 3 - [Product](https://www.codingitforward.com/s/2023-PD-Example-3-Product-Management.pdf)
- Example 4 - [Software](https://www.codingitforward.com/s/2023-PD-Example-4-SWE.pdf)

#### [Submit Position Descriptions](https://airtable.com/shrsmRxn1JXxanpbo)
**Due December 16, 2022**

[CIC Materials in Drive](https://drive.google.com/drive/folders/1scCTduUkI15hqRWVPpG7UTotNkuMl296?usp=share_link)

**Comment by amenity** [comment]
@TracyLinder - let me know if you're interested in mentoring a CIF product person.

**Comment by patrickm02L** [comment]
Draft for the [Designer ](https://docs.google.com/document/d/1y7hhLTMKlhPIQSpIuA6MTAmA3ZJHi0I_/edit)position. It's a rehash of last year's [application](https://docs.google.com/document/d/1KVdAfHjdHgdPshZfymg1Xb8p5zlghzff090xnLi2cNg/edit).

**Comment by patrickm02L** [comment]
[Developer](https://docs.google.com/document/d/1BBHyDUqm2anIfQKclwhVD5WUYi7w1ZJ7/edit) position description.

**Comment by patrickm02L** [comment]
Submitted applications on 12/15/22.
