### ISSUE TITLE
Project Discovery TCP Case Management 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10822]
### Documenting needs, desired outcomes, and project requirements. 

**Three discovery meetings have been scheduled: 12/8, 12/12, 12/12**

**Comment by TracyLinder** [comment]
### Session 1

- Customer should see who performed the TCP review through the portal
- Add the TCP reviewer to the automated emails
- The ability to ‘pause’ a review
- New field ‘PE Firm #’ Mandatory for submittal unless it’s a City Entity
- Feature to manage duplicate review requests
- After approval customer may need revisions or an updated reviewer stamp (stamps can be good for 6 or 12 months) (DAPC is 6 months)
- REVISIONS - re-open the existing case instead of opening a new one. The important thing is to keep the same TCP number.
- Upcoming/strategic: tracking field corrections
- Field Adjustments: When the inspector notes the plan needs to be updated for whatever reason, they
- There’s a difference between small revisions to a plan and a revisions that require a new engineered plan.
- When should plans be in AMANDA? Why use AMANDA over KNACK after the upgrade?

**Comment by ChrispinP** [comment]
@TracyLinder Im not sure if we can close this or not, lets groom this on Wed 06/07
