### ISSUE TITLE
Migrate the MMC's Wiki to a New Host

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1083]
The MMC has a wiki that was built by Kimley-Horn. It's currently hosted on an end-of-life windows server hosted by CTM. We need to migrate it somewhere, ideally by the end of Jan, 2020.

Outstanding questions:
- what level of access control is needed?
- what server environment?
- does anyone use the wiki?

Update: the url is: http://10.71.64.96:8010/wiki/index.php/Main_Page. This traces to atdatmsweb1.coacd.org, which is a public server, but I cannot reach the wiki itself from that server. Looks like they might be restricting access to COA IP addresses.

**Comment by johnclary** [comment]
@mateoclarke can you take the lead on this?

My email to Jen, Brian, and KH folks today:
> Brian, Jen—can you tell us more about how sensitive the wiki information is? Who currently has access to it?
> 
> Cole, what server environment do you need to host the wiki?

**Comment by mateoclarke** [comment]
After catching up IRL with @johnclary, we're not going to need to do this anymore due to some important KITS related programs running on this server.
