### ISSUE TITLE
Create Manage Wallet feature for customer

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10831]
# To Do
## Apps
- [x]  Add rich text, document view number for Chia - for Manage Wallet | BIG BUTTON 
- [x]  Add Manage Wallet | BIG BUTTON JS code
- [x]  Get Manage Wallet URL from Eva
- UAT:   https://austin-tx-austin-tx.uat.cityba.se/login
- PROD:  https://pay.austintexas.gov/login

## Dev
- [x] Configure button? - maybe I can do this in the JS link for the big button

**Comment by patrickm02L** [comment]
Testing has been done in Test. Still need to test in Production.

**Comment by dianamartin** [comment]
# 11/29
We did a UAT follow-up test to test this "Manage Wallet" feature
- We signed in and were able to access wallet information

Will need to re-do this test for Production.

**Comment by patrickm02L** [comment]
Tested with customers. Things are working.
