### ISSUE TITLE
Update moped test deployments to include new environment variables

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#10842]
As part of https://github.com/cityofaustin/atd-data-tech/issues/10600, we are adding a new environment variable to the moped-database side. As a result, the test desployments need to be updated with the new variable.

**Comment by frankhereford** [comment]
@chiaberry 👋  - Dusting off my GitHub Inbox, and this was in here from when you assigned you and I to this issue. Monday last seems like 400 days ago, so please forgive my memory if I've just forgotten what's going on here.

I do seem to recall that we spoke about changes that you wanted to make to the test deployment to update the environment variables there, but I don't see a branch or WIP PR after the quickest of searches. 

Is there anything I can do to help? I have not contributed meaningfully to this issue, but I'm ready to make any changes you would like to see!

**Comment by chiaberry** [comment]
I do have a WIP PR here -- https://github.com/cityofaustin/atd-moped/pull/887

you gave me a tour of how to run the dockerized agent, so you already did the part I needed help with!
