### ISSUE TITLE
[MS Form] Create short survey for division managers after they complete a peer review of APWA Practices

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#10853]
We need to build a short survey that I can ask division managers to complete after they've done a peer review of their assigned APWA Practices. It will probably be 3-5 questions, such as:

1. On average, how long did it take to complete your peer review of each Practice? What was the longest time you spent reviewing one Practice? What was the shortest time you spent reviewing one Practice?
2. Were the instructions on how to complete the peer review clear? Is there anything that could have been explained differently or in more detail?
3. Do you think the APWA accreditation project is valuable for our department? Was it worth the time you spent on it?

@ChrispinP can you help me with this? I think I can build it once I have a quick demo of what my options are. Please forgive my novice Github issue.

**Comment by dianamartin** [comment]
@ChrispinP Can you help Kate with setting up a quick MS forms for a survey?

**Comment by ChrispinP** [comment]
MS Form is ready to review. Created some alternative data points to show comparison between question types to choose whichever meets goals. Kate will schedule time to meetup and review tomorrow.

**Comment by ChrispinP** [comment]
Reviewed & shared MS Form with Kate. No further action, complete
