### ISSUE TITLE
[ROW Portal / TCP] BUG: Submission Status not Rolling Up to Case Status

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10857]
### When a TCP reviewer updates the submission status, the status should rollup to the case status. There are at least 2 examples of this not happening. 

Examples:
- TCP22-162525
- TCP22-162840

**Comment by TracyLinder** [comment]
@ChrispinP i put this on deck.

**Comment by ChrispinP** [comment]
I have resolved these Case Status'. I had to create a couple new conditional rules to capture a couple new specific interactions & combinations of Submission statuses. Additionally there was a bug where the boolean fields were stuck with their original values and I had to set these back to 'In Progress' to reset the value and then restore it back to its final value. All 4 cases: TCP20-043245, TCP22-162525, TCP22-162840, and TCP22-162910 have been corrected.

Will notify Shawn. Complete, closing.
