### ISSUE TITLE
BUG: The "Issued By" section in the Folder Tab has incorrect information. (LP) (Following Up w/User)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#10866]
The "Issued By" section in the Folder Tab has incorrect information. It indicates that Jessica Davis issued the permit, but Alyse Ramirez issued it. Also, the permit is not listed in ROWPACT.

Stakeholder:  LaTonya Adams
##  **ROWID: 12650007**
![MicrosoftTeams-image (32).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/86fe6ad5-fc93-4668-9996-92a71dcee23a)and

![MicrosoftTeams-image (31).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/dbe6fd71-5cf3-44a9-b916-fdc7b8086a8d)

![MicrosoftTeams-image (30).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/09ed9bb2-9bfa-4020-9332-4d5c3b1412c4)

![MicrosoftTeams-image (29).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/ddb0507f-7bd4-48b0-bb40-2286a10ea0a3)

![MicrosoftTeams-image (28).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/650a469b-c731-4fb4-b6d0-1ec8afeb462e)

##  **ROWID: 126176517**

![MicrosoftTeams-image (27).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/8c1b193e-8ede-44b5-a06e-4776a45abd73)

![MicrosoftTeams-image (26).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/b8aaade9-e294-403f-8e9c-599f8aae203e)

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT spoke to LaTonya to verify and she said the following:

> Adams, LaTonya10:59 AM
> Jessica did not issue the permit or review/process the permit. Her name should not be listed as "Issued By" Alyse is the person that issued the permit. She is the person that selected the Issue/approve option. The" Issued by" should show the person that selected the Issue/Approve option.

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/2b0a62da-6d90-44cc-afe0-77bd2374a786)

**Comment by TracyLinder** [comment]
### Feedback from ROW & Resolution

- We can't find a technical issue that would have caused this update
- We're thinking the user manually updated the folder status and the system inserted her as the issued by. This would make this a user training issue. 
- I'm going to close this.
