### ISSUE TITLE
Integrate AMD Signal Asset into SMO Artbox Location

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10884]
Goal: add a standardized location identifier for Artbox cabinet in the Smart Mobility app / Artbox Program

This issue is for the dev side. 
App side documented in **#10508 Configure Artbox Location**  

- We should be using the 'signal ID' object for the project to connect to 'artist' object, etc. as needed
- We would need to pull the signal data from AMD Data Tracker (borrowing data from DT)
- Synced with Diana 11/28/22: she had discussed with Brian C/AMD and agreed this should connect to their Signal ID asset 
- Diana will manage the item to dev product sync to discuss options

**Comment by patrickm02L** [comment]
Ask Billy's group whether we should use the signal ID or cabinet ID.

**Comment by patrickm02L** [comment]
[Code reference](https://github.com/cityofaustin/atd-knack-services/blob/production/services/records_to_knack.py) for integration services.

**Comment by patrickm02L** [comment]
Prior to Devs doing work on this, the apps team can upload the data.

We still need to know what the name of the app is (object ID and Knack configuration details).

**Comment by dianamartin** [comment]
@KaroEngstrom - In order to do this DEV enhancement can you please export this `signals` [object table](https://builder.knack.com/atd/amd/schema/list/objects/object_12/fields)

**Comment by KaroEngstrom** [comment]
M 12/4/22 

- initial artbox-signals object created and imported 
![image](https://user-images.githubusercontent.com/100615928/205712056-4093aeb3-731f-4355-84ca-e760ec8167dd.png)

**Comment by KaroEngstrom** [comment]
## W 12/7/22 

**Required items for dev work**

* New object table [`artbox_signals` in SMO ](https://builder.knack.com/atd/smart-mobility/schema/list/objects/object_26/fields) 
* Application info: 

    Application ID
    618ad3322d11b4002169a6f9
    
    API Key
    15b40096-16be-44ce-a71a-3562443a0243

**Comment by patrickm02L** [comment]
> Prior to Devs doing work on this, the apps team can upload the data.
> 
> We still need to know what the name of the app is (object ID and Knack configuration details).

12/21/22 In Apps Grooming.
Ready for Devs to create automation that pulls in the signals new or updated data daily.

**Comment by patrickm02L** [comment]
> #10508

We still need this.

**Comment by patrickm02L** [comment]
> We still need to know what the name of the app is (object ID and Knack configuration details).

We still need this.

**Comment by KaroEngstrom** [comment]
@patrickm02L I tried to include everything in the 1Password entry - can you indicate what is the missing item?

**Comment by chiaberry** [comment]
This is my take on the ask: 
**data from**: Data Tracker, view_197 (signals data pub view)
**to:** Smart Mobility, scene_146/views/view_396 (artbox locations)
daily/overnight update

I see @dianamartin asked above about "I'm thinking if we should also import/integrate the cabinet data as well?". Moving forward for now with the signals data pub view as requested until we get further instruction.

**Comment by KaroEngstrom** [comment]
@chiaberry We did get confirmation from Billy B./AMD that signals_cabinets is not required. That did not get updated in this sibling issue - sorry. (#10508 )

**Comment by patrickm02L** [comment]
In data planning 1/12/23. Charlie says he needs to test it. Will shoot to be done 1/20/23.

**Comment by patrickm02L** [comment]
1/18/23 Grooming.

@KaroEngstrom will do some spot checking to see if records are up to date. Based on the ETL running the last modified date should have occurred 1/17/23. Diana says to look at 5.

**Comment by KaroEngstrom** [comment]
**W 1/18/23** 

- a relatively new Knack feature allows us to check record history on the objects and I'm seeing successful updates by the API coming through on all the spot-checked records. 
Example: Signal 4141
![image](https://user-images.githubusercontent.com/100615928/213286744-6828a272-9192-4591-91c9-d6678b896abd.png)
- for the dev part, this is complete

**Comment by Charlie-Henry** [comment]
@KaroEngstrom @patrickm02L I can go ahead and refresh the dataset again if there is some missing recently updated records? Possible a couple slipped through during my testing.

**Comment by KaroEngstrom** [comment]
I don't believe anything to be missing but if you want to run a refresh, I can look on the Builder side. Thanks, @Charlie-Henry

**Comment by Charlie-Henry** [comment]
refreshed! @KaroEngstrom

**Comment by KaroEngstrom** [comment]
@Charlie-Henry Looks great, I'm seeing the updated records in Smart Mobility

**Comment by KaroEngstrom** [comment]
@Charlie-Henry @patrickm02L @dianamartin 
 Gm, I know I closed this since it works, but: I'm drafting a note to the stakeholders and I don't know the interval for this one to update. Does this have a regularly scheduled cadence or just as needed? Or, is this something we'll need to ask the stakeholder?

**Comment by patrickm02L** [comment]
@KaroEngstrom we don't have a cadence of check-ins with Sandra anymore. We did at the beginning, but they've become ad hoc since you backfilled the projects.

**Comment by chiaberry** [comment]
@KaroEngstrom It currently is scheduled to run twice a day, everyday. although im inclined to see if we can make it run only once. Would daily be an acceptable cadence?

**Comment by KaroEngstrom** [comment]
@chiaberry thanks! I think daily is plenty

**Comment by Charlie-Henry** [comment]
@KaroEngstrom @chiaberry configured to just run once daily at 6:30PM 👍
