### ISSUE TITLE
[Tech debt] Tear down legacy activity log pipeline

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10897]
Once we finish https://github.com/cityofaustin/atd-data-tech/issues/10896, we should clean up unused code and infrastructure:
- [x] Python API code
- [x] `primary_key_map.json` in the Editor 
- [x] github workflow scripts
- [x] drop `updated_by` and `description` column from `moped_activity_log` table
- [x] Remove special handing of rest/non-rest event trigger data in the Moped Editor js

after merging updates
- [x] Close this issue after code is merged https://github.com/cityofaustin/atd-data-tech/issues/8526 
- [x] AWS resources (SQS, Lambda, secrets, primary key map json/s3 bucket)
- [x]  update the task definitions for prod and staging to not reference the events endpoint

**Comment by chiaberry** [comment]
I've deleted the SQS and lambda functions related to the events activity and deleted the s3 bucket with the primary key map.

**Comment by frankhereford** [comment]
With @chiaberry's help, the task definitions have been updated to remove the `MOPED_API_EVENTS_URL` environment variable, and the values in the parameter store will be removed after release when the dust has settled.
