### ISSUE TITLE
Minor Updates to Signal Preventative Maintenance Map

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1089]
Per Billy B, we need minor updates to this map: http://austin.maps.arcgis.com/apps/webappviewer/index.html?id=ac06705397e44f42bbb401481c010e94

- Only show turned_on signals on the map
- Make 200 grid layer visible by default.

**Comment by johnclary** [comment]
@jaime-mckeown can you help with this and let Billy Bolander know when it's done?

**Comment by jaime-mckeown** [comment]
@johnclary of course, I'll get it done this week.

**Comment by jaime-mckeown** [comment]
- Changed the 200 grid to be visible by default
- The Traffic and Pedestrian Signals layers were both already displaying signals that are turned on. Reconfigured the pop-up to also show the Signal Status for reference.
- Updated the other pop-ups as well to look cleaner, i.e. field names to proper case, etc.
- Emailed Billy that the changes have been made.

**Comment by jaime-mckeown** [comment]
Checked that this Web App was in the Data Inventory.

**Comment by johnclary** [comment]
Thanks @jaime-mckeown !

**Comment by jaime-mckeown** [comment]
Emailed Billy that the Web App was updated, never heard back from him with any other changes.
