### ISSUE TITLE
Signal Observation records - print map 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10902]
Brian G. 
AMD

11/30: Talked to me about creating a print map of the Signal Observation locations. 

Timeline: would like ASAP since they're reliant on it to plan out their work for their Signal Engineering group

**Comment by dianamartin** [comment]
I exported the table of ~70 locations. 

[trafficsignalrequestobservationsneeded.csv](https://github.com/cityofaustin/atd-data-tech/files/10125628/trafficsignalrequestobservationsneeded.csv)

Location data set to join it (it has XY fields)
[locations_20221130.csv](https://github.com/cityofaustin/atd-data-tech/files/10125838/locations_20221130.csv)

He would like a print map that shows the signal observation points and probably an overlay of the Signal Engineer Areas polygon layer (no fill).

**Comment by andrewshensky** [comment]
Likely similar to this - https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=e70694a4f4964623b2ea9bd569a6786b

**Comment by dianamartin** [comment]
@andrewshensky @ATD-ZachB Found out this AGOL layer does not have an automation associated to it, but it may be possible to set one up.

**Comment by andrewshensky** [comment]
The data for this has been prepared. I have followed up with Brian G. about whether a print map is still needed or if the data in the web app just needs to be updated.

**Comment by andrewshensky** [comment]
Brian responded saying only the AGOL map needs to be updated. These updates have now been made. I will leave this issue open until edits are confirmed as complete by AMD.

Layer removed


New Layer (Replace removed layer)
