### ISSUE TITLE
Exec Dashboard - ATD Data Possibilities

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#10913]
_("Low-hanging fruit" data we might add to [ATD Executive Dashboard alpha version](https://app.powerbigov.us/links/tQAnbdsvMB?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare) before meeting with division managers)_

**Comment by amenity** [comment]
@maccallump - please update this issue description and then move it from "Needs Scoping" to "On Deck" and assign to Charlie.

**Comment by maccallump** [comment]
Additional data:
1. AMANDA Active ROW Permits
2. AMANDA TURP (Temporary Use of ROW) Permits
3. SIF Project list (Dan Hennessey) with project costs and available SIF
4. Parking meter space turnover
5. Parking meter space utilization by day, time
6. HR - ATD Vacancy Rate (monthly)
7. HR/Finance ATD Vacancy Savings (Fund, Target, Average)
8. Median # of Days to Fill position
9. Contracts & Encumbrances 
10. Operations - Arterial Management Signal Timing as a % of total?
11. Operations - Signal outage, blinking
12. Sign maintenance as a % of total?
13. Markings maintenance as a % of total?
14. Metrobike ridership
15. Micromobility permits, rides, etc.
16. TNC activity map
17. Transit reliability around major employers
18. Average daily/by time traffic volumes on arterials, corridors
19. EV charging infrastructure maps
20. 
21.
