### ISSUE TITLE
Gather Dash information during "Intro to TPW Stat" meetings with executives & OPM

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#10912]
What compelling, high-quality, data should our first version of the executive dashboard include?

Meet with ATD division managers to identify what would be most useful/meaningful. 
- For each potential data source, document:
  - What time span do these cover, e.g. calendar year, quarterly, fiscal year
  - What frequently-updated data sources can we use to keep eyes on the dashboard
  - What type of visualization & structure will allow viewers to drill down on particular areas of interest

**Strategic Direction metrics**
SD23 through the end of September 2023, as new council takes over, they'll establish SD28 metrics. Many indicators will carry forward, but City Leadership is modifying SD28 Refresh approach. The key/priority metrics; many of these, e.g. transportation cost, will only be available on an annual basis... But there may be areas that require additional research to identify reliable data sources.

**Parking**
- Peak hours
- Average hours of use
- Areas of most/least use
- Turnover rate
- Estimates of lost revenue for ROW closure

**AMANDA**
- ROW permit requests
- Temporary ROW permit requests
- Turnaround time for ROW permits, TCP Reviews
- Average number of re-submissions for TCP Reviews.
- Turnaround time by type of permit and Vendor (City Departments)
- Monthly average of active ROW permits, TCP Reviews

**Comment by amenity** [comment]
@maccallump - please schedule a meeting with the DMs.

**Comment by amenity** [comment]
@katelunceford @maccallump @Charlie-Henry - please add any notes/thoughts here

**Comment by amenity** [comment]
@rebekkabry - maybe this issue belongs in #12427 ...

**Comment by amenity** [comment]
@katelunceford - should we repurpose this as an epic of our upcoming Intro to TPW Stat meetings with ADs and OPM?

**Comment by amenity** [comment]
This upcoming sprint we have 
- 9/8 - Street and Bridge Operations
- 9/15 - Strategic Mobility & Parking
- 9/18 - Civil Engineering Services

**Comment by Charlie-Henry** [comment]
All of the intro meetings were completed I believe, time to close this one out?

**Comment by amenity** [comment]
Notes are all in the [_Reporting > TPW Stat Planning_ section of OPM's One Note](https://cityofaustin.sharepoint.com/sites/PW/PWOPM/_layouts/15/Doc.aspx?sourcedoc={db5f56f6-edce-4a98-be62-6504ec1ff275}&action=edit&wd=target%28Reporting%2FTPWstat%20Planning.one%7C7ea502cf-6dce-47ae-b05d-c3567bd6cf69%2F2023.04.24%20TPWstat%20Strategic%20Thinking%7Cdb36ef85-bfd8-409a-80fb-cb607dd05276%2F%29&wdorigin=NavigationUrl).
