### ISSUE TITLE
City Data Hub Migration - ETL Testing and Preparation

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#10914]
**Purpose**: This issue tracks the ETL preparation and test work related to the development effort of the forthcoming City Data Hub launch which requires the migration of datasets from the current Open Data Portal to the new City Data Hub (an internal data hub using vendor's Enterprise Data Platform, or EDP - City Data Hub and EDP mean the same thing in this context). Once migrated, the dataset will be federated to the Open Data Portal, now flowing through the City Data Hub/EDP to the ODP. 

**Related main dev issue**:  
[City Data Hub Migration - ATD Datasets #10330](https://github.com/cityofaustin/atd-data-tech/issues/10330)

[Related Miro Board](https://miro.com/app/board/uXjVPGdktyM=/)

attn: @chiaberry 

## Th 12/1/22
- received the following request from vendor: 

`In preparation for the move in Jan/Feb I am trying to inventory which datasets are automated on the platform. I have included a list of datasets you have marked you want to keep and I need to know if any of them are automated.
Please let me know if each dataset is:`
`- Automated y/n`
`- If yes, how are they automated – ex: Data Sync, SQL query, etc.`

- synced with @frankhereford to gain further context and notify him of the request; he conveyed this to dev sync
- due date to send the requested ETL Tracking document to vendor is F 12/9/22 

### ETL Tracking Document 
- location: [DTS SharePoint](https://cityofaustin.sharepoint.com/:x:/r/sites/atdDTS/_layouts/15/Doc.aspx?sourcedoc=%7BE94336E7-C547-4D9B-BF70-D641B889AB16%7D&file=Austin%20Transportation%20ETL%20Tracking.xlsx&action=default&mobileredirect=true)
- added "Y" in the Automated? column for items found in the listing [here](https://github.com/cityofaustin/atd-knack-services/blob/production/services/config/knack.py)

- [x] indicate Y/N for each dataset listed 
- [x] indicate ETL method/notes for each dataset marked "Y" for **Automated**

**Comment by KaroEngstrom** [comment]
## T 12/6/22 

- heard back from the vendor with the following questions as they prepare to set us up with the test: 
`I am getting ready to set up this test for you. I am going to give you a user role on the new domain. I want to make sure we understand what this test is for:`
`We want to test what migration will look like for a data set`
`API tokens and keys`
`We will use the data set you supplied and load it to the new platform`
`There you will see how you need to redirect data automation`
`Is that correct?`

@frankhereford - can you review? We've sent [this dataset](https://data.austintexas.gov/dataset/Dynamic-Messaging-Signs-DMS-Hub-Migration-DTS-TEST/igcg-mzv6) as a test (copy) 
- do we want to do anything more it it before the test migration?

**Comment by chiaberry** [comment]
This sounds correct to me, they can load it to the new platform and we will write an ETL (using the test dataset) that mimics our current ones and see what the differences are

**Comment by KaroEngstrom** [comment]
## Th 12/8/22 

- [x] Indicate which datasets have automations and indicate type - completed by @frankhereford 
- [ ] send updated tracking list to vendor

**Comment by KaroEngstrom** [comment]
# M 12/12/22

- have notification from vendor that the test set has been added to the City Data Hub 

NEXT STEPS: 
- [x] Test access - issues authenticating through admin account on the new hub SSO
- [x] Notify Frank - conversation with the dev team
- [x] Follow up with vendor about the possibility of a non-SSO acct to continue to manage dev and automations - email sent M 12/12/22
- [ ] Follow along with his testing 
- [ ] Document steps/new information 
- [ ] Respond to vendor with outcome and any additional questions and concerns 
- [ ]

**Comment by chiaberry** [comment]
I was able to test locally running the `records_to_socrata.py` ETL step with only updating the host in get_client (and resource id), keeping all other API keys and passwords the same.

**Comment by patrickm02L** [comment]
:eyes: @patrickm02L

**Comment by KaroEngstrom** [comment]
## M 12/19/22 

**ETL Tracking Document - Additional Items**

* Location: [DTS SharePoint ](https://cityofaustin.sharepoint.com/:x:/r/sites/atdDTS/Shared%20Documents/City%20Data%20Hub%20-%20ODP%20Migration%202022%20%5BKEEP%5D/Austin%20Transportation%20ETL%20Tracking.xlsx?d=we94336e7c5474d9bbf70d641b889ab16&csf=1&web=1&e=7QVOqn)


added "Y" in the Automated? column for items found in the listing [here](https://github.com/cityofaustin/atd-knack-services/blob/production/services/config/knack.py)

 indicate Y/N for each dataset listed

 indicate ETL method/notes for each dataset marked "Y" for Automated

**Comment by frankhereford** [comment]
I made a note in the spreadsheet above, but I think it's worth mentioning. I propose that datasets which are not yet public and which have not been updated in over a year - we should delete these (or not bring them over to the new system) as they are likely cruft from some development process or an idea that didn't make it into fruition.

**Comment by KaroEngstrom** [comment]
## T 12/20/22 
- synced with Frank after his sweep of the spreadsheet; agree what these items are likely good to delete
- plan of action: request @johnclary 's eyes on this as a second reviewer next week - Karo will reach out to John after the city's Christmas holidays

**Comment by chiaberry** [comment]
I sent the spreadsheet to @Charlie-Henry to see if he had any additional input, some of the datasets fall under his work

**Comment by Charlie-Henry** [comment]
I added some columns in that spreadsheet @KaroEngstrom. I don't recognize a bunch of these datasets but I also don't see the harm in leaving them alone? They're probably not part of some ETL but could be part of someone's work especially the SD23 datasets? We should ask Ken P if we are going to delete the UT Bluetooth datasets.

**Comment by KaroEngstrom** [comment]
Thanks @Charlie-Henry. Our primary concern is recognizing any active ETL that needs to be flagged for migration, so I agree there's no need to clean house urgently for this. As private datasets, these items will not make their way to the ODP from the new City Data Hub until we want to publish them there (or even internally on the City Data Hub).

**Comment by KaroEngstrom** [comment]
## T 12/27/22 

- @johnclary Welcome back! Would you be able to take a look at [this list ](https://cityofaustin.sharepoint.com/:x:/r/sites/atdDTS/_layouts/15/Doc.aspx?sourcedoc=%7B8C7C7D6C-1D08-4C33-8F9A-7A33A1D4200D%7D&file=Austin%20Transportation%20ETL%20Tracking%202.xlsx&action=default&mobileredirect=true) and add any notes? Frank and Charlie already did and I'll send it back to CTM at the end of the week. These are some additional datasets they found, and the specific ask if about any scripts. As a secondary concern, we hope to delete anything that isn't needed, and some of those have been identified already.

**Comment by johnclary** [comment]
@KaroEngstrom i updated the list and flagged one dataset to keep.

**Comment by KaroEngstrom** [comment]
# F 12/30/22 

## ETL Information Request 
- first/original ETL information spreadsheet sent back to vendor 12/8/22 
- this second one contains additional items founds by vendor and checked by DTS team
- send second set to vendor 12/30/22 

##  Testing & Communications
- testing with test dataset uploaded by vendor directly into the City Data Hub was successful with existing API keys and passwords, updating only the get_client and in this test case the resource ID (resource ID will stay the same in migration; the URLs will change otherwise) 
- responding to vendor and CTM with the following questions/breakdown: 
     - MIGRATION: will all metadata, including download and view counts, persist through migration? 
     - EDP/CITY DATA HUB: successful test with the direct upload dataset with the changes outlined above 
     - OPEN DATA PORTAL: per notes, all will flow seamlessly into the ODP. Can we test federate the test case to see this? 
- TO DO - WRITE AND SEND EMAIL

**Note different environments/URLS**

City Data Hub (using Enterprise Data Platform by vendor) - internal COA data portal where data can be private, shared to selected users and/or groups, or "public" to all COA users
![image](https://user-images.githubusercontent.com/100615928/210087825-a0f0d139-9216-419d-bf6b-67f3cc009cfe.png)

Open Data Portal - open to public
![image](https://user-images.githubusercontent.com/100615928/210088094-dd6b6bb0-7018-45cb-8666-aa7a30d1d9cd.png)

**Comment by KaroEngstrom** [comment]
## Testing Plan for M 1/9/23 

Context: checked with CTM F 1/6/23 and the City Data Hub/EDP has been connected to the Open Data Portal. Thus, we can test 'federating'/publishing the data from the EDP to the Open Data Portal. [Our current test dataset here](https://datahub.austintexas.gov/dataset/Dynamic-Messaging-Signs-DMS-Hub-Migration-DTS-TEST/igcg-mzv6) doesn't currently have an active script associated with it. 

**Plan for Monday:** 
1. Work with @chiaberry and @frankhereford to activate the script
2. Federate the dataset from EDP to ODP 
3. Send an automated update of some kind via the script to the EDP dataset
4. Assess the outcome on the Open Data Portal view of the dataset to ensure our ETL work sent to the EDP will appear as desired on the ODP

**Comment by KaroEngstrom** [comment]
## M 1/9/23

- discussed plan with Chia and Frank; we are eager to test
- checking the [City Data Hub ](https://datahub.austintexas.gov/)where our test dataset lives, the federation option required to test is not yet available
- emailed Marbenn at CTM to ask about this
