### ISSUE TITLE
Contact CRIS to identify why crash ID 18877823 is missing

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10911]
12/1/22, in VZ Sprint Planning we continued discussion on the missing CRIS records. [46:53](https://cityofaustin-my.sharepoint.com/:v:/g/personal/patrick_mcdonnell_austintexas_gov/EcOQSGSteqZPhFFvSzHVOisBWSCCo_uKrwF2ETELGufE9Q?email=Frank.Hereford%40austintexas.gov&e=dYzIWd)

The extract from CRIS is not producing crash data for crash ID `18877823`. We identified this in Issue https://github.com/cityofaustin/atd-data-tech/issues/9578#issuecomment-1268894580, and need to follow up with CRIS to find out why we're not able to retrieve that particular crash.

**Comment by patrickm02L** [comment]
Follow up with Xavier and Leslie.

**Comment by frankhereford** [comment]
I've written Lesley @ TxDOT asking about this crash and why it's not being reported in the CSV exports. She requested more data, so I provided an archive containing examples of finding the crash via one search mechanism and not finding via another. I'll provide more information as it's received.

**Comment by frankhereford** [comment]
Sent a follow up email to Lesley yesterday checking in after the holidays.

**Comment by frankhereford** [comment]
Though the help of Lesley at TxDOT, some targeted backfilling, and the restoration of various processing steps to get all the metadata and CR3 derived content ... this crash is now in the VZE.

**Comment by patrickm02L** [comment]
@xavierapostol it's done!
