### ISSUE TITLE
Perform real-time road closure software evaluation

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#10921]
As a key stakeholder in #5154, DTS will participate in the vendor evaluation with an eye toward the data quality, interoperability, security, and usability of each platform.

**Comment by TracyLinder** [comment]
### Sync on RFI Responses 4/25/23

Questions

Q: Can we encumber the money from the budget now? 
- No (PM)
- Do evaluations, choose top solution, put together Ken's info, Ken submit to CP, get it on council agenda, they approve, then TPW can encumber. 

Q: How do we evaluate the responses? We want to avoid RFP.
- G: RFI is informal; up to TPW.
- P: We can set it up our own way.
- Talk to the ones we want to, no response to the others. Evaluate using our own method. 

Q: What are we required to do for purchasing, and are there any deadlines? (What's next.)
- G: RFI is an informal process. Nada

Q: What next if we want to choose one and move forward? 
- We'll do the co-op route. 
- 




### Notes

K: Pulled all DIR vendors and needs clarification.

G: Multi-year needs to be a stand-alone contract. 

K: Using DIR pricing?

PM: If vendor is DIR contractor, we'll use DIR pricing. We can use spending authority from this year's budget, or we may need to go to City Council (and we'd use the DIR for pricing.)

K: Sent me the software vendor list from DIR. 




Overall Next Steps
Do evaluations
choose top solution
put together Ken's info
Ken submit to CP,
get it on council agenda, they
Council approves, 
then TPW can encumber. 


RCA request deadline is and sent to Gil's management by May 26th, for the July 20 council date. 
Council won't meet again until 8/24 (RCA deadline to Gil is 6/30)

**Comment by TracyLinder** [comment]
### Update July 17, 2023

- We have concluded vendor demos.
- We have draft evaluation scores in review by the project team.
- We expect to make a final determination this Wednesday 7/19/23
