### ISSUE TITLE
Create help guides for CityBase Payment

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10928]
- Make Payment
  - Credit Card | CC
  -  Check | ACH
- Set up Wallet outside of payment
    - Before
    - After

**Comment by dianamartin** [comment]
# 12/5
Recorded
- How to make an online payment cc
- How to make an online payment intro
- How to make an online payment check
- How to register enter wallet information

Edit
- How to make an online payment cc
- How to make an online payment intro
- How to make an online payment check
- How to register enter wallet information

**Comment by patrickm02L** [comment]
@dianamartin consider redoing voice overs. Can you add them to the [drive folder](https://drive.google.com/drive/folders/1-jtoElbfiwCuDLW4uWdQ8qHfyKejqpVR?usp=share_link) for future reference.

**Comment by dianamartin** [comment]
Met with stakeholders 1/12 and got feedback on out of the box Knack help guide page. They felt like it was hard to read. I agreed, I was going to move it to [Gitbook ](https://atd-dts.gitbook.io/street-banners-or-payment-portal-help/)and have fewer links. 

![image](https://user-images.githubusercontent.com/21112975/212201356-cd526929-cc95-4d4d-be93-bdbf38a075cb.png)
