### ISSUE TITLE
Track Cable Start/End Footage

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1092]
Per Billy, we need to track footage of cable used, by the reel's start footage and end footage, and the truck number.

Todo:
- add start and end footage on transactions in data tracker
- calculate footage quantity on transactions in data tracker
- conditionally display start/end footage fields in data tracker, as well as truck number selector, filtered for trucks with cable only.

- we do NOT have to update the finance system, we just track transaction quantities  there.

**Comment by johnclary** [comment]
@dianamartin when you're in the office, would you go grab one those cable forms from Billy? We need to track which inventory items are on the cable trucks. Plz hold off on implementing this in Knack.

**Comment by amenity** [comment]
Let's revisit this with Billy and Peggy to make sure this is the direction we want to go.

**Comment by johnclary** [comment]
There is an existing paper form for tracking this, so I'm going to move it out of MVP.

**Comment by johnclary** [comment]
We ultimately decided the way Data Tracker inventory handles cable checkouts is sufficient for now. AMD will work on process changes outside of Knack
