### ISSUE TITLE
Document Costs of Running DTS Services

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1093]
As part of our mandate to use taxpayer money in the most efficient way possible, we would like to investigate how much it is costing DTS for licensing and recurring services fees. With this information, we can make more informed decisions on how to save money in 2020. This information will also help in project prioritization.

Key Tasks:
- Create a comprehensive list of services in use by DTS (e.g., AWS, Hasura, EC2).
- Provide costs for each service
- Audit to see which alternatives we could use

Thanks for the idea @mateoclarke

**Comment by amenity** [comment]
Really like this idea, @JaceDeloney @mateoclarke . @johnclary - have we done something similar in the past?

**Comment by johnclary** [comment]
nope. this would be a first!
