### ISSUE TITLE
Create AMANDA Reports for TDS (SS)  (on PROD, but not working properly)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10949]
### TDS management needs to report on certain data and will need custom reports. Needs scoping. 

**Requesting 2 custom library reports:**
1. Case Load Report
2. Late Case Report

Mock-ups are here:
[https://app.zenhub.com/files/140626918/bfa742b6-bc64-45b4-b33c-8b9d7678b9dd/download](https://app.zenhub.com/files/140626918/bfa742b6-bc64-45b4-b33c-8b9d7678b9dd/download)

TDS Late Case Report: 
- Need to pull data from the following processes when the Process Status is NOT Closed and Process is past Due Date (End by Date is in the Past):
-- ATD Engineering Review
-- ATD SIF Review
-- CC ATD Review
-- Transportation Engineering Process
- Data should be pulled from the Following Folder Type - C, C8, SP, ZC, PR, C814, CC
- Results need to be sorted by Folder type and then by Name of Reviewer
- The report should be in a spreadsheet format. 
- When a user tries to generate this report from the AMANDA reports menu, they should be able to specify Folder type, Reviewer name AND/OR Due date (End By Date) range as parameters for generating the report. 

TDS Case Load Report: 
- Need to pull data from the following processes when the Process Status is NOT Closed:
-- ATD Engineering Review
-- ATD SIF Review
-- CC ATD Review
-- Transportation Engineering Process
- Data should be pulled from the Following Folder Type - C8, SP, ZC, PR, C814, CC
- Results need to be sorted by Reviewer Name,  Folder type and Process Name
- The report should be in a spreadsheet format. 
- When a user tries to generate this report from the AMANDA reports menu, they should be able to specify Folder type, Reviewer name AND/OR Due date (End By Date) range as parameters for generating the report. 

`TDS' # 1 AMANDA priority`
- Created during TDS prioritization 12/6
- For example: How many times have we charged each of our fees? Case load report. Find cases where ATD has reviewed but didn’t charge fees.

**Comment by TracyLinder** [comment]
I'm syncing on this with Amber tomorrow.

**Comment by TracyLinder** [comment]
### Scoping Notes

- Find cases where ATD has reviewed but didn’t charge fees. - We want to know when DSD isn't including our fees. 
    - Look at folders ZC, SP, C8

- Case load report
    - For help with managing case loads and distributing work. Also be used to see where development activity is high. 
    - Looking at on-time performance. (Being done manually by Amber.)

**Comment by TracyLinder** [comment]
Will assign to Priya & meet with her to discuss.

**Comment by TracyLinder** [comment]
Amber asked to add number of late cases grouped by staffer.

**Comment by TracyLinder** [comment]
Will work with Subha on this one.

**Comment by TracyLinder** [comment]
@vschandramouli please schedule a scoping meeting with Amber and Subha to review the current criteria and update as needed to get it backlog ready.

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by SubhaShroff** [comment]
@vschandramouli  

1. I think its 'CC Transportation Engineering Review' - 50030 - which is referred as 'Transportation Engineering Process'. just want to confirm.
2. C814 - I don't find this folder type. Which one is this?

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0331800 is submitted for TEST deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader This is deployed on TEST and tested. Ready for UAT.

**Comment by Nadin-Nader** [comment]
Reached out to Amber, Matiur and Nathan on Teams again, asking them to please UAT this on TEST so we can get approval or work on it some more.
Waiting on Response

**Comment by Nadin-Nader** [comment]
Meeting scheduled with Amber 7/31/23 at 11am

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Had a call with Vishwa about the  questions that Amber asked us on today's call. Vishwa is going to talk to Amber and update the ticket. Thanks.

**Comment by Nadin-Nader** [comment]
@SubhaShroff after speaking with Vish, he informed me that Amber would still like to keep the 2 reports and to continue as planned.

**Comment by SubhaShroff** [comment]
@vschandramouli I just completed verifying the reports again, I just found for Case Load Report, I haven't added 'Volume Builder?'. Which field it would be? Sounds like a info field. If its info field it must be 50922. I see it is associated only with PR. Please let me know.
![image](https://github.com/cityofaustin/atd-data-tech/assets/51680715/613607c8-caa6-4ef1-bfbc-cef148ef249e)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @vschandramouli 
Here are the few points that Amber mentioned in the call, that not in the scope/or need explanation to her Team. Please review my responses for the following Amber's comments and suggest the action.
### Late Case Report: 
Expectations:
1. **_The Late Case Report should Match with the Task Lists count._**  My RESPONSE: This ticket's scope is only for four processes listed, where as Task Lists can have other open processes too.
2. _**The reviewers for few processes is a common name like 'ATD-Reviewers' instead of a Reviewer name.**_ MY RESPONSE: Report only can pull whichever Assigned User it is assigned to, even if its a common group name. 
3. **_Due Date column name didn't sound appropriate._** MY RESPONSE: May be, she wanted a column name like Scheduled Date.? please confirm if we need to changed the name.
4. **_Amber suggested to have a look at 51902 report (DSD)_** - MY RESPONSE: Do we need to rescope the report to mimic the DSD report? She referred to other Case Load report of DSD, but in call we didn't find it to note down the reportcode.
5. **_The From Date and To Date Parameters purpose?_** -  The report pulls the folders with open processes(only the 4 specified processes in this ticket) which have scheduled date between From Date to To Date. For example, if date range is given from August 1st to August 14th 2023, the late case report pulls the data that  for the selected permit, selected reviewer  with the scheduled date between given data range and by how many days late from today.

**Comment by TracyLinder** [comment]
### Feedback from Amber

- **Due Date** column is OK to be named Due Date
- We don't need to mimic the DSD late case report, just suggested as a reference in case it's helpful. 

@SubhaShroff per Nate, you can continue to deploy this.

**Comment by Nadin-Nader** [comment]
Sent request to CTM to Deploy Changes of Report to Dev under: **SCTASK0353294**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Tested the TDS Late case report (99023) on DEV and it looks good. This is deployed in TEST also. Once my TEST login is enabled, I will test in TEST also.

**Comment by Nadin-Nader** [comment]
Sent a message to Amber to UAT this. Waiting on response

**Comment by SubhaShroff** [comment]
@Nadin-Nader  do we have approval to deploy it in PROD?

**Comment by SubhaShroff** [comment]
@Nadin-Nader Here is the PROD deployment plan. Please raise a request. Thank you.
[10949 - Manual PROD Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/12753732/10949.-.Manual.PROD.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to to the CTM Team to be deployed/copied over to PROD under **SCTASK0359273**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Anu has deployed this on PROD today. Please get this reviewed. Thanks.

**Comment by Nadin-Nader** [comment]
Asked Amber to UAT this on PROD. Waiting on response

**Comment by SubhaShroff** [comment]
@Nadin-Nader Got to know from Anu that Jenice is doing some clean up work for reports on all environments. That has caused the reports go missing. Anu will let me know once she gets an update from Jenice or I will follow up with her in the afternoon if I don't hear from.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The following points are fixed on DEV/TEST. I have verified and its ready for UAT.

1.  'All' option is added on PROD that was missing in PROD particularly.
2. 'C' folder is also included in the reports.

**Comment by Nadin-Nader** [comment]
The final changes have been sent to CTM to make the changes under **SCTASK0363782**

**Comment by SubhaShroff** [comment]
Status - Waiting on the PROD deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The reports are deployed in PROD after the UAT feedback and I have verified for the fixes. Its ready again, for UAT on PROD. Thank you.

**Comment by Nadin-Nader** [comment]
All changes and adjustments have been sent to PROD. I sent Amber a message via Teams asking her to reach out to me if there is an issue with the reports and that i was closing the card. if anything we can revisit the card or create a new one to debug.

**Comment by Nadin-Nader** [comment]
Per Amber the report looks good. Closing
