### ISSUE TITLE
Enhancement: Create email notification when Permit Team approves DOLA application

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10956]
Andrea M. 
SMS

Synced with me and let me know there was some workflow stuff that she and Courtney were working through. She'd like to be notified when the permit team approves the application. 

Shared Mobility Program Portal
no-reply-shared-mobility@austintexas.gov

Dockless Mobility License Application | Submitted - Pending Review
<p style="font-family: Roboto,sans-serif;"><br></p>
<p><span style="font-family: Roboto,sans-serif;" rel="font-family: Roboto,sans-serif;">A Shared Mobility License Application was submitted on <strong>{SUBMITTED DATE}</strong>. The application is <strong>Pending - Review. </strong><br></span>
</p>
<ul>
	<li><span style="font-family: Roboto,sans-serif;" rel="font-family: Roboto,sans-serif;"><strong>Provider Name:</strong> {CREATED BY PROVIDER}/<span class="redactor-invisible-space">{BUSINESS NAME/DBA}</span>.<br></span></li>
	<li><span style="font-family: Roboto,sans-serif;" rel="font-family: Roboto,sans-serif;"><strong>Contact Name:</strong> <span class="redactor-invisible-space">{CREATED BY}/{PARENT CONTACT NAME}<span class="redactor-invisible-space"></span></span></span></li>
</ul>
<p><span style="font-family: Roboto,sans-serif;" rel="font-family: Roboto,sans-serif;">View application details on <a href="https://atd.knack.com/smrt#application-dashboard/" target="_blank" rel="">Reviewer Dashboard</a></span>
</p>

**Comment by dianamartin** [comment]
Added email notification on the "Approve" form

![image](https://user-images.githubusercontent.com/21112975/206293795-b07d4db8-02ff-4f86-9f61-1b5ca8a4efca.png)

**Comment by dianamartin** [comment]
Messaged Andrea 12/7
>Hey, I configured the email notification when the Permit Team clicks that "Approval" button.
![image](https://user-images.githubusercontent.com/21112975/206294004-4f34295d-0b03-4865-b770-45745c26af8e.png)

**Comment by patrickm02L** [comment]
Send an email to Andrea and Courtney about whether the new permitting flow is working. Make tweaks as needed.

**Comment by dianamartin** [comment]
@patrickm02L should we reach back out to Andrea, Courtney?

**Comment by patrickm02L** [comment]
> Send an email to Andrea and Courtney about whether the new permitting flow is working. Make tweaks as needed.

@patrickm02L send a follow up email.

**Comment by patrickm02L** [comment]
Reached out to Andrea on Teams about email notifications. She said everything was working fine.
