### ISSUE TITLE
New SIF Info: Remaining Offset Balance (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#10950]
### SIF reviewers need to know how much offset is available. We will create a new folder info that auto-calculates the value. 
`TDS # 2 AMANDA priority`

**Acceptance Criteria** 
- A new folder new info must be added to SIF folders regardless of subtype.
- Info Group: SIF Financials
- Info Description: Remaining Offset
- Info Type: Currency 
- System should automatically insert a value in the Remaining Offset value every time info fields or SIF BuildingInfo Freeform is updated.
- System should insert the value based on this calculation: Remaining Offset = Folder Info Offset Amount - Total of all values in Offset Reduction Dollar Amount Column in SIF building Info freeform. 
- For example, if Folder Info Offset Amount = 1000 and there are 3 rows in SIF Building Info Freeform with Offset Reduction amounts 100, 200 and 300, then Remaining Offset = 1000 - (100+200+300) = 400.

**Comment by TracyLinder** [comment]
Jan Prioritization Update: We are committing to scoping this by next month's prioritization meeting. 
FYI @vschandramouli

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by TracyLinder** [comment]
@vschandramouli the AC looks good. Thank you. 

@Nadin-Nader can we pull this on deck to begin work by 2/20/23?

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed Changes and requested for Dev and Test promotion.
SCTASK0291111

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV and TEST please UAT

**Comment by TracyLinder** [comment]
### TEST UAT - Approved for Prod
- Worked on a new SIF folder
- Worked on existing SIF folder after re-defaulting. 

@Lpriya-LIT this looks ok to go to PROD

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Created request for Prod Deployment - SCTASK0297191

**Comment by TracyLinder** [comment]
### PROD UAT PASSED, 
RSN 12987530
Closing
