### ISSUE TITLE
Write Prefect ETL for Finance task orders

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10960]
Companion to #10111

Update the current [Airflow ETL](https://airflow.austinmobility.io/tree?dag_id=atd_finance_data_to_data_tracker) to Prefect for finance purchasing.

**Comment by patrickm02L** [comment]
@Charlie-Henry can you provide an update on this?

**Comment by Charlie-Henry** [comment]
@patrickm02L ETL is up and we should now be updating the finance purchasing task orders dataset. We have a backlog of data to go through but in 6 hours or so we should be all caught up.

**Comment by Charlie-Henry** [comment]
Here's the [PR](https://github.com/cityofaustin/atd-prefect/pull/47)

**Comment by amenity** [comment]
@patrickm02L - is this ready to close?

**Comment by patrickm02L** [comment]
@amenity, @Charlie-Henry needs to merge.
