### ISSUE TITLE
🚀 Discovery Day for Q4 2022

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#10961]
# Discovery Day 🧑‍🚀

I hope everyone is ready for a day that is dedicated to exploring new technologies, ideas, approaches, and solutions!

## Schedule

* Kick-off, brainstorming session scheduled for Thursday, December 8th.
  * Introduce Discovery Day
    * A day to focus on a new technology or new solution that YOU pick
    * A day that is both fun and productive
      * A surprisingly large number of our current technology stack and organizational practices have come from innovations during Discovery Day
    * I am available to rubber-duck or brainstorm ideas or any speed-bumps that may come up - reach out anytime!
  * Join #atd-discovery-day in slack, or ask me, and I'll be happy to add you
  * [Miro Board](https://miro.com/app/board/o9J_lf9h9eE=/)
    * Consider framing your project as a challenge or as a solution
    * Post-it: Recall what you worked on last time and go around the room (5m)
    * Post-it: Brainstorm ideas for tomorrow & pick one (15m)
      * Go around the room and share it with the group.
        * Changing ideas is fine! Teaming is great! Discovery day is a time for flexible, out-of-the-box thinking and idea generation.
    * Create an issue under this epic. Update it with findings, record your journey.
Tomorrow, Friday the 9th:
* Discovery-Day-Stand-Up in Slack in the #atd-discovery-day. 
    * This will be in place of previous Discovery Day morning stand-ups, so feel free to be detailed about your plans and your project. At the very least, remind the group about what you're working on today.
* I'll check with people individually over slack to see how things are going.
* 🌮 Lunch @ noon. Thank you to Diana and to DTS for providing Taco Deli!
* Discovery Day Debrief
  * Meeting to give everyone a chance to tell the group about their learnings in the form of a brief 5-10m presentation.

**Comment by KaroEngstrom** [comment]
![image](https://user-images.githubusercontent.com/100615928/207070732-6e217603-6672-46c0-b342-e3165fd6b9e3.png)

**Comment by frankhereford** [comment]
Everyone - thank you for making this Discovery Day successful! The creativity and ingenuity of our team was on remarkable display on Friday, and I can't thank you each enough for your great work!

I look forward to building on all the findings and successes from this Discovery Day as we continue our work in the new year!
