### ISSUE TITLE
Onboard New GIS Technicians - Jan 2023

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#10978]
## Daniel
- [x] Submit NERF on 12/12 - `REQ0129999`
- Pick up hardware at 9 am
- Cameron at 10 am
- [x] Log into computer
- [x] Log into email
- [x] Review On-boarding [Checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/your-first-week)
- [x] Set up AGOL account
- [x] Set up DTS Portal account - Apps
- [x] Create google account
- [x] Review DTS Data Inventory
- [x] Check out Open Data Portal
- [x] Review GIS Onboarding GitBook
- [x] Set up GIS Community Bloomfire KB
      - Submitted, awaiting account approval 
- [x] Set up Signs and Markings GIS QA - Apps
- [x] Set up Slack - ask Amenity/Diana
- [x] Set up GitHub - need to ask Frank for access
- [x] Set up GitBook - ask Amenity/Diana
- [x] Download ZenHub extension

## Joshua
- [x] Submit NERF on 12/12 - `REQ0129995` 
- Pick up hardware at 9 am
- Cameron at 10 am
- [x] Log into computer
- [x] Log into email
- [x] Review On-boarding [Checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/your-first-week)
- [x] Set up AGOL account
- [x] Set up DTS Portal account - Apps
- [x] Create google account
- [x] Review DTS Data Inventory
- [x] Check out Open Data Portal
- [x] Review GIS Onboarding GitBook
- [x] Set up GIS Community Bloomfire KB
      - Submitted, awaiting account approval 
- [x] Set up Signs and Markings GIS QA - Apps
- [x] Set up Slack - ask Amenity/Diana
- [x] Set up GitHub - need to ask Frank for access
- [x] Set up GitBook - ask Amenity/Diana
- [x] Download ZenHub extension

# Day 2/3
Tuesday afternoon at Cameron
- [x] Log into computer
- [x] Review On-boarding [Checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/your-first-week)
- [x] Set up AGOL account
- [x] Setup DTS Portal account - Apps
- [x] Review DTS Data Inventory
- [x] Check out Open Data Portal
- [x] Review GIS Onboarding GitBook
- [x] Set up GIS Community Bloomfire KB
- [x] Set up Signs and Markings GIS QA - Apps
- [x] Set up Slack - ask Amenity/Diana
- [x] Set up GitHub - need to ask Frank for access
- [x] Set up GitBook - ask Amenity/Diana
- [x] Download ZenHub extension

# Onboard Boarding Items
- [x] Set up GIS Maint/Data Mart accounts - dependency on EID
- [ ] Access to G drive - Office of Special Events 
- [ ] Planning SSPR

**Comment by dianamartin** [comment]
@andrewshensky Hey, can you confirm that these tasks have been completed for both Daniel and Josh?

**Comment by andrewshensky** [comment]
@dianamartin the only item I am unsure about is the Planning SSPR. Did we decide we were going to do those for Daniel and Josh? If so, what is the process to set that up?

**Comment by andrewshensky** [comment]
@dianamartin Yeah lets set up a time to review the process. I think it would be good to have an SSPR for Josh and Daniel for general goal setting.

**Comment by patrickm02L** [comment]
In planning 2/8/23, we decided to close this and @dianamartin will create another Issue for SSPR meetings.
