### ISSUE TITLE
[Enhancement] Use the MUI date picker for date inputs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10977]
Use the MUI [date picker](https://v4.mui.com/components/pickers/#date-time-pickers) for date inputs.

We have [`DateFieldEditComponent`](https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/views/projects/projectView/DateFieldEditComponent.js) which renders a normal `<input type="date"/>`. That's probably the place to focus this work.

All of Moped's date inputs are on the [timeline](https://moped.austinmobility.io/moped/projects/1767?tab=timeline) tab:
- Phase start
- Phase end
- Milestone completion estimate
- Milestone date completed

**Comment by chiaberry** [comment]
@roseeichelmann another issue to get your feet wet on moped, its sized a 2 but dates are always wonky, so feel free to up the estimate if you get stuck in date weeds
