### ISSUE TITLE
@ausps.org logins not working. 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#10974]
Officer Jason D. has informed us that new users with the @ausps.org domain are having trouble logging into Vision Zero in Action.

> I have three people who have not used the link before and are trying to sign in for the first time, when they sign in it just circles back to the initial sign in page and will not go any further

We need to test why new logins are not working. In the meantime, we should add new officers manually so they can get in the system and start selecting shifts.

**Comment by ChrispinP** [comment]
Reaching out to John & Michael at CTM to see if this issue is Active Directory related to find out if the ausps.org domain is included for our Single Sign On

**Comment by patrickm02L** [comment]
This is what Jason D.'s desktop screen looks like. He is still able to sign in on his mobile without problems. He initially registered a year ago, so there may be issues with folks who are new to the system. 

<img width="960" alt="Screen Shot 2022-12-13 at 1 30 30 PM" src="https://user-images.githubusercontent.com/5566727/207427878-296946e1-d7d7-4191-bfbc-011f1a310f37.png">

In the interim Jason is going to send us the emails of the officer's that are interested in sign up. We'll create temp passwords for them, and direct them to change their password after they've logged in.

**Comment by patrickm02L** [comment]
There are 2 officers we'll need to add manually, and give them temporary passwords

Hector C. 
Ryan S.

**Comment by patrickm02L** [comment]
12/21/22 In Grooming
- Recommended trying to sign into another Knack app with @ausps.org domain to see if it's restricted or not.

**Comment by patrickm02L** [comment]
Reference #993, #1315 for troubles signing in with @ausps.org.

**Comment by patrickm02L** [comment]
Chrispin looked on the backend and realized that we haven't added any @ausps.org emails to to the app, which is why folks couldn't login. 

Next step, is to work with Jason D., test with his @ausps.org domain and then add other officers on the backend who are interested.

**Comment by ChrispinP** [comment]
Reaching out to Jason to begin testing ausps.org domains.

**Comment by ChrispinP** [comment]
Hector & Ryan added to VZA with their austintexas.gov emails.

**Comment by ChrispinP** [comment]
Added second accounts for Hector & Ryan ausps emails to test the domain. According to Jason, they are working.

@patrickm02L I'm wondering if it would be possible to develop/update our SSO to check against both a primary and secondary email when authenticating so that both emails can be added to a single account?

Otherwise this is working, albeit 2 accounts.

**Comment by patrickm02L** [comment]
@ChrispinP I think being able to login with both emails is a nice to have. For the time being I think it's on the officers to remember which email they login with.

**Comment by patrickm02L** [comment]
Let VZ folks know at the Sprint Review 1/5/23 that we would have to add new officer emails on the backend to enable SSO. 

Considering this resolved.
