### ISSUE TITLE
Off-boarding Alan

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#10976]
**Accounts/Access**
- [x] Slack 
>deactivated account
- [x] AGOL
- [x] Knack - set to "Inactive"
  - [x] Signs and Markings - was Supervisor, GIS QA roles
  - [x] Data Tracker - was Viewer
  - [x] DTS Portal - was Admin
  - [x] HR Portal - System already deactivated and deleted his user role
- [x] GitHub
- [x] Miro
>Was a guest, "deleted from team"
- [x] Google Account
>Removed access to the ATD DTS folder
- [x] Separated Employee Request Form (SERF) - Submitted 12/12 - `REQ0129989`
- [ ] Request GIS Database Connections - access removed

**Comment by dianamartin** [comment]
@KaroEngstrom @ChrispinP do you know if there are any other Knack apps we need to check that Alan was in? I've already checked: SMD, Data Tracker, DTS Portal and TDS.

**Comment by KaroEngstrom** [comment]
I checked Parking Enterprise and he was already inactive there.

**Comment by chiaberry** [comment]
@andrewshensky  @dianamartin  would you like me to move him to the alumni section of the website as well?

**Comment by chiaberry** [comment]
https://github.com/cityofaustin/atd-product/pull/58 just say the word and I will merge!
