### ISSUE TITLE
Refine map styles for component editing states

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#10992]
As discussed [here](https://github.com/cityofaustin/atd-moped/pull/895/files#r1046223917), we should refine the map styles when a component is being edited or created, so that it is clear to the user which component is being actively edited.

## Todo
1. When creating or editing a component, the map features should be colored like so:
- Line: `#ffb300`
- Circle stroke color: `#ffb300`
- Circle fill: `#ffc94a`

2. In the left-hand component list, the component list item should have a left border color of `#ffb300`

**Comment by mddilley** [comment]
Going to squeeze this into https://github.com/cityofaustin/atd-moped/pull/908 since I split the create and edit styles there. Will combine and update the colors so it looks ✨-ly
