### ISSUE TITLE
[Enhancement] Stop using "closed duplicate" status in Knack > 311 integration

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#11002]
Per Bill and 311, instead of sending a `closed_duplicate` status when an SR is flagged as a duplicate in Knack, we should send a `closed` activity, and include the SR # of the parent/original SR in the activity details.

**Comment by johnclary** [comment]
@dianamartin what i describe above should solve the issue with duplicate SRs being improperly closed in 311 through the integration. i can pick up this work after the holidays.

**Comment by dianamartin** [comment]
@johnclary Do you want me to assign you to this issue so it doesn't get lost and set the sprint to after the holidays?

**Comment by ChristinaTremel** [comment]
@johnclary can you check if this issue is complete? Diana and I were thinking it might be!

**Comment by johnclary** [comment]
@ChristinaTremel this needs to remain open. we're going to solve this through the ESB interface - https://github.com/cityofaustin/atd-data-tech/issues/8954

**Comment by johnclary** [comment]
We did this as part of the integration upgrades.
