### ISSUE TITLE
Wireframe TDS Customer Home Update

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11008]
@ChrispinP will create simple wireframe of proposed design update. Then review w/ Tracy and go from there. 

- Current proposed design is [here](https://miro.com/app/board/uXjVP2vYvwk=/?moveToWidget=3458764542463742305&cot=14).

**Comment by ChrispinP** [comment]
Wireframing draft complete:
![image.png](https://images.zenhubusercontent.com/5f036c8940760b58210af838/cc3710f6-a47a-43b4-83c8-785a35e82cee)

Created two versions I think would be ideal for our 2023 version of the portal which is more sustainable for the increase of services that may continue to be added.

Ready to review

**Comment by TracyLinder** [comment]
@ChrispinP I like version A the most. I'll pull in some folks to get some more feedback.

**Comment by TracyLinder** [comment]
### Dev/Product Sync Notes

1. Patrick suggested a design similar to [this ](http://bizport.longbeach.gov/)where the drop-down menu stays open, and the choices have subtext. _(See screenshots below.)
2. Tracy & Chrispin will sync on design tomorrow
3. Finalize design & organization with stakeholders
4. Let Chi know we're ready & attend backlog grooming next week 1/4
5. Put On Deck for the next sprint (1/11)

**Comment by TracyLinder** [comment]
### Whiteboard Sesh
- @ChrispinP will update the wire frame
- @TracyLinder will schedule review w/ stakeholders
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/e8da614f-e5b2-4751-8b3b-f68a7af8fa6c)

**Comment by TracyLinder** [comment]
### Meeting w/ Stakeholders
- scheduled for 1/4/23

**Comment by ChrispinP** [comment]
Updated Wireframe:
![image.png](https://images.zenhubusercontent.com/5f036c8940760b58210af838/956737fe-7b74-4b8b-b142-3f8e21128eca)

**Comment by ChrispinP** [comment]
Diana provided feedback and guidance for the Customer Portal updates and wireframe. I have added the 2023 Live Version of the Customer Portal to the Miro board.

Ready to review
