### ISSUE TITLE
Manage Executive Review

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11012]
### Create & deliver an executive presentation
- [x] Compile [executive level review slide deck](https://cityofaustin.sharepoint.com/:p:/r/sites/ATD_APWA_Accreditation/Shared%20Documents/DTS%20Internal/ATD%20APWA%20Review%20Phase%20-%20Executive%20Team.pptx?d=w3c98abac2d724edba0bad4a76fdbd068&csf=1&web=1&e=leyTRc) based on the DM slide deck 
- [x] Kate & Peggy to present in person to Director & ADs (and virtually for those who couldn't make it)

### Create an executive review guide
- [x] Draft a condensed, higher level matrix (from the Peer Review Matrix) for ADs to follow
- [x] Finalize content per Peggy's feedback & save as a [template](https://cityofaustin.sharepoint.com/:w:/r/sites/ATD_APWA_Accreditation/Shared%20Documents/DTS%20Internal/ATD%20APWA%20Executive%20Review%20Guide%20-%20Template.docx?d=w2f9a88af81584151a50e58c077187a08&csf=1&web=1&e=DwJLEt)
- [x] Create & save a version for each Practice (37)
- [x] Upload each version to SharePoint

### Extend the [progress tracker](https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation/Lists/ATD%20APWA%20Progress%20Tracker/AllItems.aspx) with additional columns
- [x] Exec Review Guide - link column to get to the appropriate version of the Executive Review Guide 
- [x] Exec Review By - contact column to assign the AD
- [x] Exec Review Status - choice column to track review status:
     - Not started (red) - starting setting 
     - In progress (yellow)
     - Complete (green) 
     - N/A (blue) - for the few Practices assigned to other city departments 
- [x] Actions from Exec Review - choice column to track updates: 
     - Waiting on exec review (purple) - starting setting
     - Updates not started (red) 
     - Updates in progress (yellow)
     - Updates complete (green) 
     - No updates to do (green) - used if there are no edits identified during the executive review OR for the N/A Practices

### Create an [Executive Review view](https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation/Lists/ATD%20APWA%20Progress%20Tracker/AllItems.aspx?viewid=bfc68d11%2Dd2c3%2D4a95%2D9e81%2D6092753ccc0e&OR=Teams%2DHL&CT=1671138395812&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyOC8yMjExMzAwNDEwMCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D) of the tracker
- [x] Create a condensed view of the tracker with only columns relevant to ADs
- [x] Assign an AD to each Practice using the "Exec Review By" column based on Lead & org chart
     - Upal (9): 16.1-16.7, 35.1, 35.2
     - Jim (7): 34.4, 34.12-34.15, 34.19, 34.24
     - Anna (15): 34.1-34.3, 34.5, 34.6, 34.8-34.11, 34.16-34.18, 34.20, 34.21, 35.10
     - Anthony (5): 35.5-35.9

### Support ADs to ensure they complete exec reviews by **Dec 30th**
- [x] Respond to questions/comments via email/Teams chat 
- [x] Update tracker as ADs complete their reviews. Go through each Practice and check if there are edits identified by the AD. If so, change the "Actions from Exec Review" column to "Updates not started" (red). If not, change that column to "No updates to do" (green).

**Comment by amenity** [comment]
@katelunceford - feel free to edit & add links to the presentations, review guide, etc.

**Comment by maccallump** [comment]
Executive Review is ongoing.  Looks like Anna Martin has completed her assignment.  Upal is working on it.  Jim Dale is in progress and.....

**Comment by katelunceford** [comment]
Here's the list for me to go through each Practice and check if there are edits identified by the AD. If so, I will make sure the "Actions from Exec Review" column on the [tracker ](https://cityofaustin.sharepoint.com/sites/ATD_APWA_Accreditation/Lists/ATD%20APWA%20Progress%20Tracker/AllItems.aspx)is set to "Updates not started" (red). If not, it should be "No updates to do" (green).

### Chapter 16 - ROW Management
- [ ] 16.01 - Upal
- [ ] 16.02 - Upal
- [ ] 16.03 - Upal
- [ ] 16.04 - Upal
- [ ] 16.05 - Upal
- [ ] 16.06 - Upal
- [ ] 16.07 - Upal

### Chapter 34 - Traffic Operations
- [ ] 34.01 - Anna
- [ ] 34.02 - Anna
- [ ] 34.03 - Anna
- [ ] 34.04 - Jim
- [ ] 34.05 - Anna
- [ ] 34.06 - Anna
- [ ] 34.08 - Anna
- [ ] 34.09 - Anna
- [ ] 34.10 - Anna
- [ ] 34.11 - Anna
- [ ] 34.12 - Jim
- [ ] 34.13 - Jim
- [ ] 34.14 - Jim
- [ ] 34.15 - Jim
- [ ] 34.16 - Anna
- [ ] 34.17 - Anna
- [ ] 34.18 - Anna
- [ ] 34.19 - Jim
- [ ] 34.20 - Anna
- [ ] 34.21 - Anna
- [ ] 34.24 - Jim

### Chapter 35 - Parking
- [ ] 35.01 - Upal
- [ ] 35.02 - Upal
- [ ] 35.05 - Anthony 
- [ ] 35.06 - Anthony 
- [ ] 35.07 - Anthony 
- [ ] 35.08 - Anthony
- [ ] 35.09 - Anthony
- [ ] 35.10 - Anna

**Comment by katelunceford** [comment]
Closing this issue as all items have been completed. Moving onto the next (https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/gh/cityofaustin/atd-data-tech/11084)
