### ISSUE TITLE
Merge intersection polygons into #E509E4556E

### ISSUE THREAD

**Issue by adrien-atd** [cityofaustin/atd-data-tech#11014]
Merge 3 polygons into one at  intersection of S Lamar Blvd service road and Sunset Trl

![image.png](https://images.zenhubusercontent.com/636be31df4f74416145e1083/b59babbb-ad9d-402d-bc13-b52c6fcd744c)

**Comment by patrickm02L** [comment]
Going forward VZ GIS staff will be able to make edits in MAINT, which will publish to this public [AGOL map](https://austin.maps.arcgis.com/apps/mapviewer/index.html?layers=f9db1ee0aaa2438284154ccc47302eb5).
