### ISSUE TITLE
SH 71 between Cardinal Loop and FM 973

### ISSUE THREAD

**Issue by adrien-atd** [cityofaustin/atd-data-tech#11010]
Update polygons in this area - construction modified service roads in 2016

![image.png](https://images.zenhubusercontent.com/636be31df4f74416145e1083/a5e7cc70-e057-401e-a303-fb0b0d03e7fc)

**Comment by patrickm02L** [comment]
Going forward VZ GIS staff will be able to make edits in MAINT, which will publish to this public [AGOL map](https://austin.maps.arcgis.com/apps/mapviewer/index.html?layers=f9db1ee0aaa2438284154ccc47302eb5).
