### ISSUE TITLE
Update language on row permit addendum (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11022]
### Update ROW Permit Addendum language in two places

- _Requested by Ryan M. on 8/23/22 by email. No issue was created at that time._

----
# FIRST CHANGE
**At the request of APD, we need to add permit condition #1 (g) to the ROW Permit Conditions that appears on the permit templates for RW, EX, DS. The new condition will need to read:**

- Add to all permit addendums. See #9368 

`g. If police officers employed by agencies other than the City of Austin will be used to assist in directing traffic, applicant must notify APDSpecialevents@austintexas.gov at least three days prior to work with the name(s) and agency of the police officers to be employed, along with the date, time, and location where the officer(s) will be working.`

<img width="789" alt="Screenshot 2022-12-16 at 2 41 33 PM" src="https://user-images.githubusercontent.com/49930868/208185614-1a0179c7-b7c2-4e09-be49-b226f32b1bb9.png">

----
# SECOND CHANGE
 Update phone number on section 1 letter B
- Change number FROM 512-974-1553 TO 512-660-3293

**Comment by TracyLinder** [comment]
@vschandramouli can you please get the AC on this updated and on-deck before the holiday break next week (12/22)? Please let me know if you run into any obstacles.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Done the changes and sent you the updated rpt files to copy in Dev/Test server

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to the DEV path. please UAT

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/f0122511-89f8-46f3-b568-7ebfde37be29)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder Addendum page has been updated in all 10 reports in PSM, RW, DS and EX folders. Ready for UAT in Test

**Comment by Nadin-Nader** [comment]
UAT has been done on this plus Ryan has been informed and has not said anything is wrong. Closing
