### ISSUE TITLE
[ROW-TCP] - Build Access Code Feature for Case Management

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11038]
### Final update w/ the Case Management Upgrade 

- [x] Add access code feature

**Comment by TracyLinder** [comment]
We haven't enabled public visibility yet, but this is working when we're ready to deploy.

**Comment by AdnanTaher** [comment]
I accidentally closed the issue. However, I reopened it.

**Comment by ChrispinP** [comment]
Not implementing in production. Will followup with cleanup issue: #14892 after TCP Case Management Upgrade.
