### ISSUE TITLE
Meet with HRD to Get More Info on PeopleAdmin

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1103]
We need to talk to HRD about potentially unused functionality in the PeopleAdmin solution that can replace existing HR paper processes.

**Comment by amenity** [comment]
_Call with Doron S.  — eCareer SMU, ATD hiring consultant in HRD_
- PeopleAdmin has no onboarding

Could do interview process paperless, but not inside PeopleAdmin. This would be a process that the HR liasion would do outside of eCareer
- Could use whatever software we want to go paperless with interview process 
- No official policy on handwritten notes
- Discouraged to email documents with SSNs
- Must comply with records retention policies and be able to respond to PIRs 
- Low hanging fruit: Application itself is 15 pages
- Doron spoke with Divya about digitizing PDFs with SeamlessDocs
