### ISSUE TITLE
[TDS-TIA] Update: Contact Us Page

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#11047]
- [x] Replace broken image with a new image of the map, hosted on Gitbook
- [x] Have a link for customers to navigate to the web map
- [x] Update North Area from Nathan to Ella

**Comment by ChrispinP** [comment]
Action items completed, Contact Us page updated:
![image.png](https://images.zenhubusercontent.com/5f036c8940760b58210af838/03ae845c-1e2f-490a-9d98-fc1a7a31da0a)

**Comment by TracyLinder** [comment]
Looks good. I'm closing.
