### ISSUE TITLE
Bug: PSM 'In Date' Feature Not Working (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11049]
### User reporting that the PSM folder in-date is not updating when the folders status updates to Internet Pending
- This feature was implemented on #1726

----
Application was started 10/31/22, Fees weren't paid until 12/19/22.. when the status changed to "internet pending". This should have updated the folder in-date from 10/31 to 12/19. 

![image](https://user-images.githubusercontent.com/49930868/208973592-fc6e9e23-5c12-42ca-8249-d5fc9a73be81.png)

**Comment by TracyLinder** [comment]
@Nadin-Nader this is ready for debugging. Please let me know if you want help prioritizing.

**Comment by TracyLinder** [comment]
This has been assigned to @Sreelatha-BlazeKannan for debugging.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder - Identified the missing code in Procedure PAYMENT_PSM from V7 environments. Informed George and incorporated in DEV & TEST. Tested in TEST and informed Tracy/Paloma about how it is working now. Waiting on Paloma updates to promote changes to PROD.

**Comment by TracyLinder** [comment]
Status: Pending UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per the show case on 02/10/2023, It is approved for PROD promotion; Informed George about the promotion as this is missing changes of old code #1726. George will be promoting the changes by EOD 5.30pm. Here is the commit ID: b67e6e377c45

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan has this been deployed to PROD?

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Yes, it went to PROD Last Friday as per George. I have not submitted any commit for this. as it was a missing change and that is the reason we have not created service now ticket for this. thank you!

**Comment by Nadin-Nader** [comment]
On PROD and working. Closing card If anything we can reopen.
