### ISSUE TITLE
Bug: NTA workflow requires traffic count

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11041]
### Matiur was told by customers that they cannot submit a NTA because of a system error to do with the traffic count attachment. 

- [x] Troubleshoot

![image](https://user-images.githubusercontent.com/49930868/208758517-9805f202-d639-4591-863a-8ad2e23798a8.png)

**Comment by TracyLinder** [comment]
### Troubleshooting

✅ Continued w/o attaching counts, system alerted me, i edited attachments, added counts as pdf, saved & submitted. 
✅ Submitted normally - no issue. 


I'll ask Matuir for more info.

**Comment by TracyLinder** [comment]
### Troubleshooting

✅ Continued w/o attaching counts, system alerted me, i edited attachments, added counts as pdf, saved & submitted. 
✅ Submitted normally - no issue. 


I'll ask Matuir for more info.

**Comment by TracyLinder** [comment]
@ChrispinP I'm unable to replicate this bug. Can you please take a look?

**Comment by ChrispinP** [comment]
Good to know this is working again. Maria notified me on Friday so I investigated. Found out one of the Count field settings was incorrect. I also cleaned up the fields and rules (some had broken on the edit pages). All required documents are setup the same way now with their boolean field and their 2 count fields. Made sure table editing rules were also present for completeness.
