### ISSUE TITLE
TCP Submission status to update TCP parent status when TCP submission record is updated (in line)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1104]
John C.
DTS

Asked to have some custom code help update the last knack child record status to the parent record status

Test Environment: `19 DEC 2019 | TEST - Austin Transportation Data Tracker`

Example records that doesn't do this: 
- `TCP18-007825`
- `TCP18-009685`

Would like to make add the feature when the user edits the field `Submission Status` in the "Submissions" table. 
![image](https://user-images.githubusercontent.com/21112975/71734413-90fc5880-2e11-11ea-98ef-4cdda18cc5eb.png) 

Typically in these situations we'd make a record rule to update the parent, but because this status gets changed after it's set we need to make is so when the field is saved, it rolls up to the TCP parent status.

![image](https://user-images.githubusercontent.com/21112975/71734620-f2242c00-2e11-11ea-921c-7e44893a1483.png)

**Comment by johnclary** [comment]
thanks @dianamartin! would you add a note with the object names, object ids, field names, and field ids that are affected?

**Comment by dianamartin** [comment]
@johnclary yep, I was going to do that. I figured that would be helpful for the devs. I just got sidetracked.

**Comment by dianamartin** [comment]
TCP Parent Status: 
TCP Submission Status:

**Comment by dianamartin** [comment]
### Test record in PROD
`TCP20-027950`

**Comment by dianamartin** [comment]
Added `Cancelled` status to TCP Tracking

**Comment by mddilley** [comment]
john is pushing this back another sprint so mike can focus on inventory/mobile app.

**Comment by KyleErich** [comment]
Closing. Appears to be a duplicate of card 449, and is stale.
