### ISSUE TITLE
[Bug] VZV By Population visualization shows NaN for year 2022 data

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#11056]
The By Population visualization depends on data that we add manually to [a config](https://github.com/cityofaustin/atd-vz-data/blob/master/atd-vzv/src/constants/popEsts.js). ~We don't have a figure for 2022 so the front end is showing `NaN` (not a number) in the UI.~ This is now fixed, but we should add a fallback value since there will always be a risk of not having updated figures in this file while the UI automatically updates the years shown. We handle this with a fallback [in the info popup](https://github.com/cityofaustin/atd-vz-data/blob/f21799b2af8739255e73a0fa8cb47ab1c017d29a/atd-vzv/src/Components/Popover/popoverConfig.js#L132-L136).

We should update since 2023 is coming and then there will be ~two parts of this visualization showing~ another `NaN` soon.

**Edit: This bug ended up causing a WSOD after the new year instead of two `NaN` like I expected. This issue should resolve the WSOD that occurs when the population figure is not present since it must be added manually.**

### The bug:
<img width="959" alt="Screenshot 2022-12-23 at 11 29 03 AM" src="https://user-images.githubusercontent.com/37249039/209376985-31fb2a7f-d1b4-44ea-8586-c4e0edbd38fb.png">

### Possible fix (we can discuss what to show instead of `NaN`)
<img width="648" alt="Screenshot 2022-12-23 at 11 29 22 AM" src="https://user-images.githubusercontent.com/37249039/209380472-70293c6f-97f3-453d-a68d-a873aa917784.png">

**Comment by mddilley** [comment]
@patrickm02L Looping you in on this one for any adjustments to the issue

**Comment by frankhereford** [comment]
By dumb luck, I fixed this today by adding data for the population of COA for 2022. [PR 1148](https://github.com/cityofaustin/atd-vz-data/pull/1148).

**Comment by mddilley** [comment]
@frankhereford Thanks for patching the missing year data. 🙏 Going to reopen this and tweak it to fix the underlying bug. I had started https://github.com/cityofaustin/atd-vz-data/pull/1145 for it.

**Comment by frankhereford** [comment]
I take this back - I didn't actually fix anything! I only added data for 2022 - a bandaid if anything - thank you @mddilley!

**Comment by patrickm02L** [comment]
Can you please update the values in the VZV so that they are consistent with the values from the [reference document](https://www.austintexas.gov/sites/default/files/files/Planning/Demographics/austin_forecast_2021_pub.pdf) we're using. 

2019 - 985,504
2020 - 1,006,727
2021 - 1,026,833
2022 - has already been updated
2023 - 1,056,827 (projection)

**Comment by mddilley** [comment]
@patrickm02L I noticed that the figures that are currently up on VZV are from the Austin Full Purpose population column so they weren't as inaccurate as we thought. I updated the rest of the figures to match the Austin Full Purpose figures in https://github.com/cityofaustin/atd-vz-data/pull/1145
