### ISSUE TITLE
Resolve moped-api not building

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11055]
I merged dependabot [PR 902](https://github.com/cityofaustin/atd-moped/pull/902) which failed to build 
https://github.com/cityofaustin/atd-moped/actions/runs/3760517051

```
Invalid endpoint: https://secretsmanager/..amazonaws.com
Running Zappa -- MOPED API: moped_test
Important! A new version of Zappa is available!
Upgrade with: pip install zappa --upgrade
Visit the project page on GitHub to see the latest changes: https://github.com/Zappa/Zappa
Calling update for stage moped_test..
Error: Please define stage 'moped_test' in your Zappa settings.
```

Found this which may be related to the invalid endpoint error: https://bobbyhadz.com/blog/aws-cli-invalid-endpoint

@mddilley theorizes: 

> So what I’m thinking is that export BRANCH_NAME=${GITHUB_REF##*/} isn’t outputting staging like we want it to in this case. I think the fix would be to either PR and push a small change to the API code to main or just wait until the next person merges some work and make sure the API builds

**Comment by mddilley** [comment]
For reference:
https://austininnovation.slack.com/archives/CNUEPKLB1/p1671738379276639

**Comment by chiaberry** [comment]
Dependabot uses different secrets in github than the github actions, To fix this we need to add dependabot secrets

I added the zappa configuration file to the dependabot secrets
