### ISSUE TITLE
[Enhancement] Autogenerate non-recycable number for temporary crashes

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11050]
Companion to #11030.

Going forward we'll want to create a new temp number that has not been used before to prevent any residual data from being borrowed from previous entries. 

Talked about this in grooming 12/21/22.

**Comment by patrickm02L** [comment]
In grooming 1/4/22 it was proposed:

We could have a temporary crash table. 

Add an auto-incrementing ID field, so that we have IDs that are always unique. 
We can put together some views to help with Xavier’s querying.

**Comment by patrickm02L** [comment]
Putting an 8 on this today, and will suss out whether or not we need to break this into separate Issues and resize the individual bullet points listed above.

**Comment by johnclary** [comment]
We have addressed this in the new data model by using custom serial `id` primary key columns in every table
