### ISSUE TITLE
Resolve long trigger name issue to upgrade graphql-engine

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11065]
As a user, I am trying to upgrade the graphql-engine software from version 1.3.1 to the most recent stable version 2.16.1. However, I encountered an issue with long trigger names which is a regression in versions past 2.12.1. To solve this issue, I am proposing to rename the triggers with shorter names so that I can successfully upgrade to the latest version of the software.

---

@frankhereford's explanation from slack

I’ve been trail-and-error searching for an upgrade path for us from `graphql-engine` 1.3.1 to the most recent stable version `(2.16.1) `of the software. 1.3.1 came out Aug 12, 2020, so we’re making a pretty colossal jump.

I started out coming up with the shortest route being from the present state of `1.3.1` → `2.9.0` → `2.12.1`.  Anything past 2.12.1 is a no-go in our current configuration, because we bump into a regression related to long trigger names, which we have. It’s #5786 in their issues which they closed with this PR 5826 where they trap long trigger names greater than 42 chars in length. They trap the problem at creation, so since we have legacy long names, we have to handle it.  They observe in the `CHANGELOG.md` that:

**NOTE:** If you have event triggers with names greater than 42 chars, then you should update their names to avoid running into Postgres identifier limit bug (#5786)

So, next, I find if I start up the closest version that will run on a ARM mac under `qemu`, `1.3.1`, I can remove the 3 triggers, recreate them with shorter names, and then I can make the jump to the latest and greatest version which is  `2.16.1`. Pretty amazing that you can jump 2+ years and have it work, if you stay within the bounds they document. :100:

Action / Next Steps:
I propose that we remake / rename our VZ `graphql-engine `events / triggers with the following name changes:

`update_crash_jurisdiction_on_lat_lon_change` → `jurisdiction_from_latlon
update_crash_location_on_lat_lon_change` → `location_from_latlon
update_noncr3_crash_location_on_lat_long_change` → `blueform_location_from_latlon`

- Does anyone have reservations about this? I’d love to discuss it with anyone. It doesn’t change what the triggers do at all, it just changes the name to be shorter.

- This change does not lend itself to a PR really at all, but I’d be happy to commit an empty commit and “PR” it to give us a place to record agreement, if needed.

**Comment by frankhereford** [comment]
Thanks @patrickm02L for writing up this issue. Your summary is so concise and readable! ✨🤖

@chiaberry & @patrickm02L have both expressed support to move forward with this name change, so I'm going to go ahead and execute it. Thank you both!

**Comment by frankhereford** [comment]
Completed in staging and production - thanks!
