### ISSUE TITLE
Purchase Google Cloud Services

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1108]
We're going to evaluate Google Cloud Services to understand cost/benefit/features vis a vis AWS. I submitted a purchase request for $1200 in credits.

https://atd.knack.com/finance-purchasing#my-purchase-requests/purchase-request-details/5e0bbd64e9fbbb0015079121/

**Comment by johnclary** [comment]
Purchase request has been approved.

@sergiogcx plz close this out once you setup our payment info to Google Cloud. Thanks.

**Comment by sergiogcx** [comment]
The payment info has been set to Google Cloud, closing.
