### ISSUE TITLE
Meet with core stakeholders to kick off version 1

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11080]
Attendees: Dan V., Erin W., Peggy, Charlie, Kate

[Agenda](https://cityofaustin-my.sharepoint.com/:w:/r/personal/peggy_maccallum_austintexas_gov/_layouts/15/doc2.aspx?sourcedoc=%7BDE9634B8-0A64-43CB-8225-75D8930A8DFD%7D&file=Agenda%20-%20Exec%20Dashboard%20-%20Business%20Alignment.docx&action=default&mobileredirect=true)

**Comment by amenity** [comment]
@Charlie-Henry @maccallump @katelunceford  - please add your notes from yesterday's meeting _here_.

**Comment by katelunceford** [comment]
Here are my meeting notes...

Wednesday 12/28 at 2 PM 

Peggy on background / project intro: We want to plan things to collaborate on, starting with the alignment of people’s business functions, services, including new services tied to strategic direction outcomes and associated indicators. We’re finishing up SD23 & queuing up SD28 plan. We’ll use a collaborative document of the agenda 

Resources: PWSTAT reporting (Dan forwarded these via email) – each month certain functional areas present data where the leaders in charge of those things report on them; PWSTAT offers the platform and schedule to do it

**Goal: Dynamic reporting tool (with financial info & other interesting info) that you can dial in for more detailed data; a platform and timeline to report on what ATD is doing; mesh together what we’re already doing with SD28** 

Data to start with: [Catalog of Work](https://apps.gov.powerapps.us/play/543b60d5-c5f9-4a5e-bf51-c5cb8924c619?tenantId=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f) + keep in mind SD23

To do: 

- [ ] Research PWSTAT examples (Dan forwarded via email)
- [ ] Start organizational framework of reporting - what is included where
     - Review catalog of work to see what kind of things are being reported – align that with ATD’s functions – how and when 
     - Think through how to incorporate SD28
- [ ] Brainstorm how to present this to DMs
     - Will need to set up Lunch & Learn (45 minutes)
     - Initiate new DMs & refresh others
     - Go over starting point using the catalog of work
     - Show them what we have now (lots of financial data) + talk about other things we want to do: what drives the services that each division provides, goals associated with each one, etc. 
- [ ] @maccallump set up Teams channel & SharePoint site so we have a central spot for this project 
- [ ] @maccallump will set up another meeting next week
