### ISSUE TITLE
Fix the White Screen of Death (WSOD) for the VZV in 2024

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11093]
Users may experience the White Screen of Death (WSOD) on the Vision Zero Viewer at the beginning of the year.

The WSOD was caused because it was missing a [hard-coded population estimate](https://github.com/cityofaustin/atd-vz-data/blob/master/atd-vzv/src/constants/popEsts.js) for the City from the previous year. 

Write a function that updates the `popEsts` for the new year to prevent the WSOD from persisting. 
_(original approach adjusted based on Frank's recommendation below)._

Reference the [PR from last year.](https://github.com/cityofaustin/atd-vz-data/pull/1148) h/t @frankhereford

**Comment by frankhereford** [comment]
Thanks for making this issue! I think we should adjust the approach here to use a function to estimate the population - something simple and linear, and then use a lookup table to override the estimate with a known value if one is available. This way - if we forget to do the update on time, then we won't go into a WSOD state.

This is a classic problem - I can't tell you how many times i've updated copyright years in footers for folks mid-january.

**Comment by mddilley** [comment]
@patrickm02L Just saw this issue - I reopened https://github.com/cityofaustin/atd-data-tech/issues/11056 after it was closed but that is now a duplicate. Feel free to close that one again. There is a WIP PR https://github.com/cityofaustin/atd-vz-data/pull/1145 for the bug. That fix is to just not show a figure in the visualization if there is no population figure for the year added.

**Comment by patrickm02L** [comment]
Going forward VZ GIS staff will be able to make edits in MAINT, which will publish to this public [AGOL map](https://austin.maps.arcgis.com/apps/mapviewer/index.html?layers=f9db1ee0aaa2438284154ccc47302eb5).
