### ISSUE TITLE
Update Mobile App for New Inventory Worklfow

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1109]
This is an epic of features & enhancements that need to be implement to support the new inventory workflow for signal technicians.

**Comment by johnclary** [comment]
@mddilley this isn't fully spec'd, but could you provide an estimate for this? probably going to ask you to jump on this next sprint, but possibly sooner. cc @mateoclarke

**Comment by mddilley** [comment]
@johnclary Sounds great, the current estimate looks good to me.

**Comment by johnclary** [comment]
awesome—thanks!

**Comment by johnclary** [comment]
@mddilley turning this into an epic and will add related features as separate issues.
