### ISSUE TITLE
Create ATD-AMANDA Fee Documentation (TL)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11106]
### We need current documentation of all fees ATD maintains in AMANDA.

- The document template is [here](https://cityofaustin.sharepoint.com/:x:/s/ATDAMANDASupport/ERbtNXhcKIZLpS6camuEV6ABszKZVqbIhpsyYxRI9-lwpw?e=9HheQL).

**Comment by TracyLinder** [comment]
### Team sync scheduled for 1/5/23 to discuss documentation needs. Then I will assign this to @vschandramouli

**Comment by TracyLinder** [comment]
Tracy & Vish synced today on next steps. Vish will add the FY23 fee data to the fee documentation. We'll sync again next week.

**Comment by vschandramouli** [comment]
Fee document created and updated for FY 24. 

Document can be found [here](https://cityofaustin.sharepoint.com/:x:/r/sites/ATDAMANDASupport/Shared%20Documents/General/Fees/Active%20Fee%20Documentation.xlsx?d=w7835ed16285c4b86a52e9c6a6b8457a0&csf=1&web=1&e=VL6PzY)
