### ISSUE TITLE
[Enhancement] Filter signal autocomplete menu by signal type

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#11115]
When selecting a signal component from the map tab, the autocomplete results should be filtered based on the signal component type selected by the user.

See some discussion [here](https://github.com/cityofaustin/atd-moped/pull/922#discussion_r1061806451).

<img width="606" alt="Screen Shot 2023-01-04 at 2 13 03 PM" src="https://user-images.githubusercontent.com/14793120/210636412-8f533d30-c7c4-47b5-8ea4-f2534dfa2d64.png">

**Comment by mddilley** [comment]
@johnclary I squeezed this one into https://github.com/cityofaustin/atd-moped/pull/936  in because it was super straightforward. Let me know if I jumped the gun on this one, and I can roll back those changes.
