### ISSUE TITLE
Prevent SB folder creation in Amanda

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11119]
Determine cut off date for when we'll stop creating folders in Amanda.

**Comment by patrickm02L** [comment]
We'll need to determine about how many unpaid invoices there are before we turn this off. 

@TracyLinder to provide a list of unpaid invoices.

**Comment by TracyLinder** [comment]
### Outcome

The effort/resources required to stop the system from creating SB folders in AMANDA is too big for value that would be delivered. The SB folder is still in use by DSD so removing a folder sub-type would be intensive work requiring coordination and UAT with DSD, as well as AMANDA-CTM assistance to do this properly. Being that our customers will not be using AMANDA anymore, leaving things as-is shouldn't cause any problems. If problems do arise we will treat it as an AMANDA bug.
