### ISSUE TITLE
Create template for CityBase launch messaging

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11118]
Work with Nick to set up messaging for the launch of CityBase payments.

**Comment by patrickm02L** [comment]
Here's [the doc](https://docs.google.com/document/d/1o_KN9qbn8wHhkLtGYcKrfNYBxuovWG2bE5dxa_B2aHw/edit#) @dianamartin started for the messaging.

**Comment by patrickm02L** [comment]
We'll need to include messaging that Amanda is no longer an option for paying banners.

**Comment by dianamartin** [comment]
Met with stakeholders on 1/12 and provided them the communications.

**Comment by dianamartin** [comment]
It's 1/17/23, go-live for CityBase - looks like the stakeholders haven't mobilized to post anything on their website. We can recommend it again for a month at our next check-in. Closing.
