### ISSUE TITLE
AMANDA SB Payment Data Request

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11117]
### DTS needs a list of people records that have made a payment to ATD on SB folders made in the past 2 years. 
- Email data results to Tracy

**Data Fields**

- First name
- Last name
- email address
- total (count) number of payments
- people rsn

**Parameters:**
- Folder type is SB
- Folder subtype is Banner Permit 50105
- Payment start date is 1/1/2021
- Payment end date is current date

**Comment by TracyLinder** [comment]
@Nadin-Nader this is ready to be assigned. Thank you!

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I am adding the query and data here.

SELECT p.peoplersn, p.namefirst, p.namelast, p.emailaddress, COUNT(ap.paymentdate) PaymentsCount
FROM people p
JOIN accountpayment ap ON ap.billtorsn = p.peoplersn
JOIN folder f ON f.folderrsn = ap.folderrsn AND f.foldertype = 'SB' AND f.subcode = 50105 --Banner Permit subtype
WHERE ap.paymentdate BETWEEN to_date('2021-01-01','yyyy-mm-dd') AND SYSDATE
GROUP BY p.peoplersn, p.namefirst, p.namelast, p.emailaddress
[11117-AMANDA SB Payment Data Request.csv](https://github.com/cityofaustin/atd-data-tech/files/10348188/11117-AMANDA.SB.Payment.Data.Request.csv)

**Comment by Nadin-Nader** [comment]
This has been sent to Tracy and I for review

**Comment by patrickm02L** [comment]
In Planning 1/11/23. Asked @TracyLinder if we could get a count of all the payments for 2022, 2021 would be nice too. 

We're looking to get an estimate of how many banners payments to anticipate year to year.

**Comment by TracyLinder** [comment]
@SubhaShroff we need 2 more data queries for this. I will move this issue back to **On Deck** 

# 1 Bill Count
- Total count of invoices created on SB, banner subtype for each year, 2021 and 2022. 

# 2 Unpaid invoices
- List of unpaid invoices on SB, banner subtype
- Only include valid bills with payment flag **N** (exclude C, Y)
- Columns: folderrsn, bill number, bill amount, bill created date, folder name, billed-to first & last name, billed-to company name, billed-to email address

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader 
### Bill Count Report (For year 2021) with query:
[11117 - SB Payment Data Request for Calendar Year 21.xlsx](https://github.com/cityofaustin/atd-data-tech/files/10405825/11117.-.SB.Payment.Data.Request.for.Calendar.Year.21.xlsx)

SELECT p.peoplersn, p.namefirst, p.namelast, p.emailaddress, COUNT(ap.paymentdate) PaymentsCount
FROM people p
JOIN accountpayment ap ON ap.billtorsn = p.peoplersn
JOIN folder f ON f.folderrsn = ap.folderrsn AND f.foldertype = 'SB'
 AND f.subcode = 50105 --Banner Permit subtype
WHERE ap.paymentdate BETWEEN to_date('2021-01-01','yyyy-mm-dd') AND to_date('2021-12-31','yyyy-mm-dd')
GROUP BY p.peoplersn, p.namefirst, p.namelast, p.emailaddress

### Bill Count Report (For year 2022) with query:
[11117 - SB Payment Data Request for Calendar Year 2022.xlsx](https://github.com/cityofaustin/atd-data-tech/files/10405916/11117.-.SB.Payment.Data.Request.for.Calendar.Year.2022.xlsx)
SELECT p.peoplersn, p.namefirst, p.namelast, p.emailaddress, COUNT(ap.paymentdate) PaymentsCount
FROM people p
JOIN accountpayment ap ON ap.billtorsn = p.peoplersn
JOIN folder f ON f.folderrsn = ap.folderrsn AND f.foldertype = 'SB'
 AND f.subcode = 50105 --Banner Permit subtype
WHERE ap.paymentdate BETWEEN to_date('2022-01-01','yyyy-mm-dd') AND to_date('2022-12-31','yyyy-mm-dd')
GROUP BY p.peoplersn, p.namefirst, p.namelast, p.emailaddress

### Yet working on the Unpaid invoices...................

**Comment by SubhaShroff** [comment]
> @SubhaShroff we need 2 more data queries for this. I will move this issue back to **On Deck**
> 
> ### 1. Bill Count
> * Total count of invoices created on SB, banner subtype for each year, 2021 and 2022.
> 
> ### 2. Unpaid invoices
> * List of unpaid invoices on SB, banner subtype
> * Only include valid bills with payment flag **N** (exclude C, Y)
> * Columns: folderrsn, bill number, bill amount, bill created date, folder name, billed-to first & last name, billed-to company name, billed-to email address

Hi @TracyLinder  For unpaid fees, I am not able to find BillToRSN in any tables. Only with payments there is a way to get to know the BILLTORSN from a ACCOUNTPAYMENT table. Unless, you want me to look for BilltoRSN people type added on People tab.  Please let me know.

**Comment by TracyLinder** [comment]
@SubhaShroff is the billtorsn the same as the bill number? If it is, we can exclude that column. I know the fee tables are hard to work with.

**Comment by TracyLinder** [comment]
@patrickm02L @dianamartin the bill count data is above. We're still working on the unpaid fee data.

**Comment by SubhaShroff** [comment]
> @SubhaShroff is the billtorsn the same as the bill number? If it is, we can exclude that column. I know the fee tables are hard to work with.

@TracyLinder  BillToRSN is the peopleRSN that paid for the billed fee. This is in regard to the columns (billed-to first & last name, billed-to company name, billed-to email address) you have asked for Unpaid invoices. Since the fees are unpaid, there won't be any associated Billed-to people / organization name record, as I understand. I can get the rest of the columns(folderrsn, bill number, bill amount, bill created date, folder name).

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader Here is the data for Unpaid invoices of SB Banner Permits for 2021 and 2022 calendar years based on the Billed date. Please note that, as I mentioned earlier I couldn't get the people/organization details for unpaid bills and that data only exist for paid bills. Please review the data and let me know any more other details to fetch. Thanks.
### For 2021
[SB Banner Permit Unpaid Invoices based on billed Date for 2021.xlsx](https://github.com/cityofaustin/atd-data-tech/files/10427060/SB.Banner.Permit.Unpaid.Invoices.based.on.billed.Date.for.2021.xlsx)

SELECT f.folderrsn, f.foldername, ab.billnumber, ab.dategenerated BilledDate, ab.billamount
FROM  folder f
JOIN accountbill ab ON ab.folderrsn = f.folderrsn AND ab.paidinfullflag = 'N'
    AND ab.dategenerated BETWEEN to_date('2021-01-01','yyyy-mm-dd') AND to_date('2021-12-31','yyyy-mm-dd')
WHERE  f.foldertype = 'SB' AND f.subcode = 50105 --Banner Permit subtype

### For 2022
[SB Banner Permit Unpaid Invoices based on billed Date for 2022.xlsx](https://github.com/cityofaustin/atd-data-tech/files/10427290/SB.Banner.Permit.Unpaid.Invoices.based.on.billed.Date.for.2022.xlsx)

SELECT f.folderrsn, f.foldername, ab.billnumber, ab.dategenerated BilledDate, ab.billamount
FROM  folder f
JOIN accountbill ab ON ab.folderrsn = f.folderrsn AND ab.paidinfullflag = 'N'
    AND ab.dategenerated BETWEEN to_date('2022-01-01','yyyy-mm-dd') AND to_date('2022-12-31','yyyy-mm-dd')
WHERE  f.foldertype = 'SB' AND f.subcode = 50105 --Banner Permit subtype

**Comment by dianamartin** [comment]
@TracyLinder cc @patrickm02L We've shared these reports with the stakeholders as of today. Thank you for aggregating it all!
