### ISSUE TITLE
Duplicate/Triplicate Markings SR Flex Notes

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1111]
John C.
DTS

Hopefully this gets fixed with the new proxy server.

Ex. [20-00006220 - Markings SR](https://atd.knack.com/signs-markings#service-requests-markings/view-csr-markings-details/5e136acc6c8bdf0016bdfa32/view-markings-flex-notes/5e136acc6c8bdf0016bdfa32/)

**Comment by johnclary** [comment]
@dianamartin will check with SMB to see if this is still happening? Hoping it was resolved as of last Thurs (1/17)

**Comment by johnclary** [comment]
Closing per Christina.
