### ISSUE TITLE
TDS Portal Redesign Custom Menu & Toggle Features

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11122]
### Create a services menu allowing the user to toggle through each service type and view service information on the same page.

<img width="1027" alt="Screenshot 2023-01-04 at 2 40 36 PM" src="https://user-images.githubusercontent.com/49930868/210645882-87af058d-a312-4ee4-88e6-a9950b06b12a.png">

**Comment by TracyLinder** [comment]
@ChrispinP @chiaberry here is the Dev issue for the TDS Customer Portal toggle menu.

**Comment by chiaberry** [comment]
@ChrispinP is the scaffolding for this implemented in a test environment already? if not, do you know roughly when it would be, so it could be ready for a dev to poke around at it?

**Comment by ChrispinP** [comment]
Im currently preparing the pages for this still. I will create a test environment once Im done and post another update 🤠

**Comment by ChrispinP** [comment]
The Test app is now ready: TEST | 12 JAN 2023 | TDS | Transportation Development Services Portal

Services Page - Scene 579
Services Menu - View 1865 (7 menu items)
Custom Menu - View 1866 (place the custom dropdown menu here)

**Comment by chiaberry** [comment]
@dianamartin @TracyLinder let me know when this is ready for a dev to pick up and we will get cracking on it

**Comment by TracyLinder** [comment]
**Sprint Planning Note:**
- Diana is concerned the content might be too small. Chrispin said we can adjust that if needed. We'll keep an eye out for this.

**Comment by TracyLinder** [comment]
@chiaberry we're ready for dev team. I'll join the product/dev sync today to discuss.

**Comment by TracyLinder** [comment]
@ChrispinP can you please add the current mockup or a link to it?

**Comment by ChrispinP** [comment]
The Test app: TEST | 12 JAN 2023 | TDS | Transportation Development Services Portal

[Services Page - Scene 579](https://builder.knack.com/atd/tds-test-jan/pages/scene_579) 
Services Menu - View 1865 (7 menu items, content from these pages to be displayed inside custom menu)
Custom Services Menu - View 1866 (render the custom menu here with javascript) if it cant be rendered in the Menu view, feel free to render in the Rich Text view 1922
Example Hover Menu - View 1921 (use this for reference)

[Customer Portal](https://atd.knack.com/tds-test-jan#customer-portal/)

Styling is on lines 11 to 53

```
/* Style the tab */
.tab {
  float: left;
  border: 1px solid #dddddd;
  background-color: #f1f1f1;
  width: 25%;
  height: 300px;
}

/* Style the buttons that are used to open the tab content */
.tab button {
  display: block;
  background-color: inherit;
  color: black;
  padding: 22px 16px;
  width: 100%;
  border: none;
  outline: none;
  text-align: left;
  cursor: pointer;
  font-size: 1.2em;
}

/* Change background color of buttons on hover */
.tab button:hover {
  background-color: #ddd;
}

/* Create an active/current "tab button" class */
.tab button.active {
  background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
  float: left;
  padding: 0px 12px;
  border: 1px solid #ccc;
  width: 75%;
  border-left: none;
  height: 500px;
  display: none;
}
```

**Comment by TracyLinder** [comment]
### Update & Closing

- We decided to update the services page with out-of-the-box KNACK features. This is no longer a need.
