### ISSUE TITLE
Create Task Order page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11120]
Created Task Order page so that users can see task orders and manage them

**Comment by dianamartin** [comment]
I had apparently created a "Task Order" page before the holidays, but no actually added the table
-[x] Added `task_order` table

**Comment by patrickm02L** [comment]
> @patrickm02L the only thing I noticed is that the "Created Date" and "Created By" fields were blank. Not sure if Charlie saw any fields in the Data Warehouse SQL view that would be appropriate in order to populate them.

@Charlie-Henry did you notice any "Created Date" and "Created by" fields in the data warehouse SQL?

**Comment by Charlie-Henry** [comment]
@dianamartin @patrickm02L `Created Date` or `Created by` are not in the SQL view. `CHARGE_LAST_DT` `TK_LAST_DT` are in there though. We are tracking who created the TK in `TASK_ORDER_ESTIMATOR`.

Here's the list of fields we have, just is missing `TASK_ORDER_ESTIMATOR` which they added for us:
https://github.com/cityofaustin/atd-data-tech/issues/10199#issuecomment-1252584980

**Comment by dianamartin** [comment]
@Charlie-Henry @patrickm02L the `TASK_ORDER_ESTIMATOR` is the Requester, not the person who created it in AIMs.. I wish there was a date it was created in AIMs.

**Comment by dianamartin** [comment]
@patrickm02L Have we scheduled a check in with stakeholders yet?

**Comment by patrickm02L** [comment]
This is done, we were keeping it open until the ETL #10960 was complete. It was merged to production on 1/25/23.
