### ISSUE TITLE
Ability to Cancel/Withdraw an Inventory Request from Work Order

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1113]
Ability to cancel/withdraw an inventory item request if it has not been issued.

## Precondition

- the inventory item request must be in a status of `Submitted to Warehouse`

## Test Script

1. Start from a Work Order that has an inventory item in a status of `Submitted to Warehouse`

2. In the rightmost column of the table (`Cancel`), you should see an icon with a `Return` icon. Click the icon, then `Submit` the form that appears.

### Expected behavior

- The item's status will change to `Cancelled`

- An `Edit` button will appear in the `Edit` column of the inventory items table.

- In the Finance System, this inventory item request will have a status of `Cancelled`. The Inventory Request will have a status of `Cancelled`.

**Comment by johnclary** [comment]
@dianamartin ready for testing

**Comment by dianamartin** [comment]
notes to self: 
>you can also play with the Edit ability in Data Tracker, but I haven’t written a test yet. Basically, to edit, you have to Cancel first, then you edit, and when you submit the edit, the update is sent to the finance system

**Comment by dianamartin** [comment]
For WO `WRK20-073355`, I had submitted to warehouse. 
I clicked the `Cancel` button, and a modal pop-up appeared asking to "Cancel Request". 

The status changed from `Submitted to Warehouse` to `Cancelled`.

**Comment by dianamartin** [comment]
Success!
