### ISSUE TITLE
Bug: Adjustments to existing bill doesn't update bill (NN) (Waiting on Victor w/CTM)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11130]
### In V6 when a billed fee was adjusted, the system inserted the adjustment on that existing bill. In V7 the system inserts a new bill with the negative amount. This makes it impossible to pay the adjusted fee on portal. 

- Test RSN where we can't pay the adjusted amount is 12857518
- PROD RSN where this feature worked in V6 is 12794408
- Service Now ticket is INC0249440

**Workaround:**
- OSE will have to cancel the existing bill, then add the fee & adjustment and create a new bill.

**Comment by TracyLinder** [comment]
@Nadin-Nader please discuss w/ Victor when you speak to him about #10221

**Comment by Nadin-Nader** [comment]
Scheduled a meeting for Wednesday 01/25/23 at 11am with Victor, Isabel and Priya

**Comment by Nadin-Nader** [comment]
@TracyLinder according to Victor, this was already resolved. He asked if you can have the UAT again

**Comment by TracyLinder** [comment]
### Update & Closing

- Maria spoke w/ Victor to find the resolution. The only way to pay adjusted fees is to include the fees and adjustment in one bill.
