### ISSUE TITLE
Ability to Issue Requested Items from Finance System

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1114]
As a warehouse admin, I need the ability to issue items to technicians.

## Preconditions

- The inventory request must be in a `Submitted` state with items in a `New Request` state.

## Test Script

1. Start from a  Inventory Request that has a status of `Submitted`.

2. At the top of the page, click the `Issue` button, select the recipient, and click the `Submit` button.

### Expected behavior

- In the Finance System, all items that have a status of `New Request` will now have a status of `Issued`.

- In the Data Tracker, all items that previously had a status of `Submitted to Warehouse` will have a status of `Issued`. The table should also display the technician to whom the items were issued.

- In the Data Tracker, there should be no option to Cancel or Edit the inventory item from the Inventory Items table.

**Comment by johnclary** [comment]
@dianamartin ready for testing.

**Comment by dianamartin** [comment]
Using WO `WRK20-073355`. Inventory Request `72`. 
In a `Submitted` status. 
Saw `Issue` button on the page on the Inventory Item Request table. There is no "Issue" button the top of the page. 
Clicked `Issue`, was able to review the details of the Inventory Item Request. The item status went from `New Request` to `Issued`. 
 
There is no "Cancel" or "Edit" button, but there is a "Return" button available.

**Comment by dianamartin** [comment]
Success!
