### ISSUE TITLE
[TDS] Enhancement: TDS Customer Portal 2023 Update

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#11154]
This is the work for the non-dev portion of prepping the new TDS Customer Portal pages for the re-design.

- [x] Customer Portal & Customer Home (maintain resources dropdown until footer is developed)
- [x] Contact Us Page (updated)
- [x] App Admin Page (to update contact list on Contact Us page, internal to PMs only)
- [x] Access Case Page (linked)
- [x] Services Page (NEW)

Service Pages:
- [x] TIA Determination (updated)
- [x] TIA Compliance (NEW)
- [x] TIA (updated)
- [x] NTA (NEW)
- [x] TA (NEW)
- [x] ZTA (NEW)
- [x] SIF Worksheet (updated)

[Dev Issue #11122 for Custom Dropdown Toggle Menu](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/gh/cityofaustin/atd-data-tech/11122)

**Comment by ChrispinP** [comment]
Met with Nathan & Joan, and showcased the Miro design and the new or updated pages. They are satisfied with the updates to continue pushing forward with our design update.

Notes:
- [ ] Ability to add multiple contacts to each review area (Contact Us page)
- [ ] Remove 'Service Area' language from Map link (Contact Us page)
- [ ] Since it would take some time for us or Knack to add a Footer feature, okay with making the two Resource Links be a dropdown on the home page for now
- [ ] Now that the button language is standardized, remove the first line of the 'How It Works' section since its repetitive and the button is easier to distinguish now
- [ ] Once the 4 New Service pages are prepped, will need another Review to confirm language is correct.

Once I have finished prepping the pages I will make a copy of the environment for Devs to work with for the Custom menu.

**Comment by ChrispinP** [comment]
Customer Portal update is now ready to be reviewed with stakeholders. I am copying the app to prepare for Dev work.

**Comment by TracyLinder** [comment]
### Update
- The apps team is reviewing the redesign before we send it to the DEV team.

**Comment by ChrispinP** [comment]
I have updated the the design according to the wireframe on TDS Jan Test environment.

I made sure to add what the Hover menu and Footer would be like. I also updated the button look based on feedback and the top nav menu.

**Comment by ChrispinP** [comment]
The TDS Customer Portal 2023 Update is now live with the new TA & ZTA applications. 

Notified stakeholders via email. Pending any further feedback.

**Comment by TracyLinder** [comment]
### Update & Closing
- This was delivered on 2/16/23. We will close this issue and leave the epic open for the stabilization period.
