### ISSUE TITLE
[Security] Investigate ATD_VZ_DATA_EVENTS_ROLE CircleCi env var

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#11152]
Figure out what the value of ATD_VZ_DATA_EVENTS_ROLE in CircleCI is, document it, and then remove it since it is only used in the build SQS GH Action.

Edit: Also looks like DOCKER_API_VERSION is not used by any CI and could possibly be removed - _nope, it is used, see below_

**Comment by johnclary** [comment]
@mddilley @patrickm02L fyi

**Comment by mddilley** [comment]
Looked at the CircleCI logs and `DOCKER_API_VERSION` is definitely being used and its value is `1.39` by looking at the version in the build logs. It also matches the two last characters that show in the CircleCI env vars page.

**Comment by mddilley** [comment]
ATD_VZ_DATA_EVENTS_ROLE is the [execution role](https://docs.aws.amazon.com/lambda/latest/dg/lambda-permissions.html#lambda-intro-execution-role) fed to [aws create-function](https://docs.aws.amazon.com/cli/latest/reference/lambda/create-function.html) and its value is atd-vz-data-events-role (this is a role in IAM). It is only needed in the GH Action flows.

**Comment by mddilley** [comment]
Leaving a note that the ATD_VZ_DATA_EVENTS_ROLE needs to be an **ARN** so I updated the doc to reflect that
