### ISSUE TITLE
[City Data Hub] Data Portal ETL Migration

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#11153]
Update Socrata API endpoint to `datahub.austintexas.gov` in these places:
| repo | note | assigned to
|-|-|-
| [atd-knack-services](https://github.com/cityofaustin/atd-knack-services/blob/86a5fc395d5e9fbc804827e18eee9fccae8d4ce2/services/utils/socrata.py#L47)| patching this code will rebuild the docker image and auto-deploy to airflow. Prefect will pull for latest docker image.| john
| atd-data-publishing | config file will need to be updated on atd-data01. Edit: turns out we no longer publish any socrata data from this repo :) :) :)| john
| [atd-road-conditions](https://github.com/cityofaustin/atd-road-conditions/blob/09663bc4aff7bf9ec795b0f68dc32114701fece5/atd-road-conditions/socrata.py#L136)| patch this code and manually pull down the image on the host server| john
| [atd-metrobike](https://github.com/cityofaustin/atd-metrobike/blob/7c24c2082ec9f9cbbdec5e42a9f0845c4775b6c4/publish_trips.py#L97)|patch this code and it will auto-deploy to airflow.| john
| [atd-signal-comms](https://github.com/cityofaustin/atd-signal-comms/blob/827ef3ad96e22757986e69928ce9fd8a42a95165/atd-signal-comms/socrata_pub.py#L27)| patch and will auto-deploy to airflow| john
| [atd-kits](https://github.com/cityofaustin/atd-kits/blob/d858b2b6b8b63f72bb9b42f77b48219f495e7017/atd-kits/signal_status_publisher.py#L149)| patch this code and it will auto-deploy to airflow| 
| [atd-finance-data](https://github.com/cityofaustin/atd-finance-data/blob/61bb72ec3b4b4cf9b2f0e4eeb11feb1ae23f1e0a/s3_to_socrata.py#L20)| [Prefect KV Store](https://cloud.prefect.io/team/kv) - `atd-finance-data` -> 2x`SO_WEB` endpoints that need to be updated in that JSON. Do not need to re-register this flow.| charlie
| atd-service-bot| [Prefect KV Store](https://cloud.prefect.io/team/kv) - `atd-service-bot` -> `SOCRATA_ENDPOINT`. Do not need to re-register this flow. | charlie
| [atd-parking-data](https://github.com/cityofaustin/atd-parking-data/blob/production/meters/parking_socrata.py)| [Prefect KV Store](https://cloud.prefect.io/team/kv) - `atd_parking_data_meters` -> `SO_WEB` [PR to remove the need to re-register this flow](https://github.com/cityofaustin/atd-prefect/pull/52) | charlie
| [Trail Counters](https://github.com/cityofaustin/atd-ped-bike-crash/blob/main/counter_data.py)| [Prefect KV Store](https://cloud.prefect.io/team/kv)  `trail_counters` -> `SO_WEB`. Patch issued, so no re-registering of this flow is necessary | charlie
| [atd-data-lake](https://github.com/cityofaustin/atd-data-lake)| need to update secrets on atd-data01| john
| atd-vz-data |patch master - which is what airflow is running: https://github.com/cityofaustin/atd-vz-data/blob/ab99b64a9e2d04ade320421527157cf44ac613d3/atd-etl/app/process_socrata_export.py#L25| john

Ultimately, we need to make sure every dataset listed [here](https://cityofaustin.sharepoint.com/:x:/r/sites/atdDTS/_layouts/15/Doc.aspx?sourcedoc=%7BDF3AB496-3526-4D37-A7B2-B76D348B96A8%7D&file=ETL_Combined_20230109.xlsx&action=default&mobileredirect=true) has been accounted for.

**Comment by johnclary** [comment]
@Charlie-Henry would you give this look and add anything i may have missed?

**Comment by Charlie-Henry** [comment]
@johnclary will roll these updates to the main comment

> [atd-knack-services](https://github.com/cityofaustin/atd-knack-services/blob/86a5fc395d5e9fbc804827e18eee9fccae8d4ce2/services/utils/socrata.py#L47): patching this code will rebuild the docker image and auto-deploy to airflow. not sure about prefect.

Doing this should work OK as Prefect will pull the latest docker image.

> [atd-metrobike](https://github.com/cityofaustin/atd-metrobike/blob/7c24c2082ec9f9cbbdec5e42a9f0845c4775b6c4/publish_trips.py#L97) - patch this code. need to remember if this is running on airflow or prefect

Airflow: [trips](https://github.com/cityofaustin/atd-airflow/blob/master/dags/atd_metrobike_trips.py) and [kiosks](https://github.com/cityofaustin/atd-airflow/blob/master/dags/atd_knack_metrobike_kiosks.py)

> [atd-finance-data](https://github.com/cityofaustin/atd-finance-data/blob/61bb72ec3b4b4cf9b2f0e4eeb11feb1ae23f1e0a/s3_to_socrata.py#L20) update this env var (on prefect?)

[Prefect KV Store](https://cloud.prefect.io/team/kv) `atd-finance-data` Two `SO_WEB` endpoints that need to be updated in that JSON. 

> atd-service-bot: env var on prefect?

[Prefect KV Store](https://cloud.prefect.io/team/kv) `atd-service-bot` `SOCRATA_ENDPOINT`

**Comment by Charlie-Henry** [comment]
@johnclary it looks like our Prefect CI checks if the flow file[ has changed at all ](https://github.com/cityofaustin/atd-prefect/blob/4d26acdffd01467f71a37a79e9404569e8537b73/.github/workflows/prefect_helper.sh#L70) and if it has it will redeploy it. I've just gone through our ETLs that I'm assigned here and made sure we should not have to re-register any of them Tuesday. Parking has a PR I just opened as well. @chiaberry you mentioned that Knack Banner might need a task to do this as well?

**Comment by Charlie-Henry** [comment]
All `data.austintexas.gov` endpoints have been changed to `datahub.austintexas.gov` in the Prefect KV store
