### ISSUE TITLE
Onboard Christina as DTS Product Manager

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11164]
## Accounts 
~Submit a [CTM New Employee Request Form](https://atx.servicenowservices.com/sp?id=sc_cat_item_guide&sys_id=b714eb12db7a3f0021ccef92ca961972) for a COA network account, eAccess PIN/HR Portal, and phone~ 
- [x] Submit an "Active Directory - Update Existing User Network Account" - change of supervisor/title
>Submitted `REQ0132466`
- [x] Submit a [CTM service request](https://atx.service-now.com/sp) to add to DTS Distribution Email Group:
>Submitted `REQ0132466`
- [x] Add "First Last Name" to email distribution list "ATD Data and Technology Service" ([ATDDataTechnologyServices@austintexas.gov](mailto:ATDDataTechnologyServices@austintexas.gov)) 
- [x] Add to City of Austin Slack - austininnovation.slack.com 
- [x] Add to DTS Google Drive
- [x] Add to [Gitbook](https://app.gitbook.com/@atd-dts/spaces)
>she has a GitBook account already 
- [x] Add to [Austin Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members) 
>asked Frank on 1/9 to invite CT to COA org
- [x] Upload headshot to ["Headshots" Drive folder](https://drive.google.com/drive/u/0/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G)
>headshot scheduled for Thu, 1/12
- [x] Add to group slide and team slides [DTS Presentation Template Team section](https://docs.google.com/presentation/d/1tHKTfUgQ-uAXdRBkEdXqR7ryBo_LTU86IzQxo1gJoeA/edit#slide=id.gfd2da31025_0_6) 
- [x] Update DTS group and team slides in the DTS Orientation presentation to reflect ☝️
- [x] Check w/ Diana/Amenity—if needed; we pay for seats
  - 1password
  - Miro
- [x] Invited Christina to GitBook
- [x] Removed other alumni from team

### Hardware — DTS Systems Admin
- [x] Coordinate with DTS System Admin (Scott), make sure there is enough lead time for equipment to be acquired.
- [x]  Laptop
>Diana issued on 1/10 - `COA57121`
- [x]  Monitors (has 1, might need another)
- [x]  Chair - check availability, ask Amenity/Peggy how we're handling this?
- [x]  Power supply
- [x]  Keyboard
>Diana gave a wired keyboard, waiting on Staples order item
- [x]  Mouse 
>Christina is borrowing Diana's extra wireless mouse until Staples order item
- [x]  Docking station

### Calendar invites
_Schedule or coordinate with the event owner_
- [x] First day: DTS Team Orientation — invite all leads, Peggy optional
- [x] First Week: DTS Product Ops — Coordinate w/ Amenity
- [x] Monthly Team Meeting
>Peggy sent one meeting, Diana sent series 1/10
- [x] Sprints
- [x] Sprint Ceremonies — Planning, Grooming, Sync, Show & Tell
>I sent Show & Tell series, 
- [x] Biweekly 1x1

### New team member 
- [x] Set up Cameron Road wifi: coa-atd-secure-wifi — password in 1password
- [x] [Log in to your City of Austin email](https://outlook.office365.com/)
- [x] [Set up your email signature](https://docs.google.com/document/d/1OAoBll9rIl6XZq2uOShm5HCbHJboOt0SLP_wK6tjkEE/edit)
- [x] [Create a Google account for your Austintexas.gov email address](https://atd-dts.gitbook.io/atd-staff-resources/general/using-google-as-a-city-employee)
- [x] If you don't have one already, [create a Github account](https://github.com/join) 
- [x] Install [Zenhub Browser Extension](https://www.zenhub.com/)
- [x] Post your [daily standup in Slack](https://atd-dts.gitbook.io/wiki/slack#daily-stand-up)
- [x] [Set yourself up for remote work](https://atd-dts.gitbook.io/atd-staff-resources/working-remotely/getting-started)
- [x] [Set up Cameron Road printer](https://app.gitbook.com/@atd-dts/s/dts-service-desk-knowledge-base/onboarding/printer-information) 
- [x] Set up docking station — [Windows](https://www.dell.com/support/home/us/en/04/product-support/product/dell-universal-dock-d6000/drivers) | [Mac](https://www.displaylink.com/downloads/macos) (see [here](https://support.displaylink.com/knowledgebase/articles/1188004-macos-10-13-or-10-14-video-functionality-not-enab) if you're having issues on Mac. If you have an M1, grant screen recording permissions as detailed [here](https://m1displays.com/) )
- [x] Upload a headshot [here](https://drive.google.com/drive/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G) and add your title and preferred pronouns [here](https://docs.google.com/document/d/1gRjTic8FD3s-t0sVZhErAidMIAktU-0Vn2GYPpPcUeg/edit) (Google Drive access must be set up first)
- [x]  [Create a Github issue](https://github.com/cityofaustin/atd-data-tech/issues/new) for adding yourself to the [DTS "About Us" webpage](https://austinmobility.io/about) (labels: Service: Dev, Type: Operations, Product: DTS Website) including the link to your photo and preferred pronouns
- [x] Familiarize yourself with the [DTS Resource Index](https://github.com/wiki/resource-index)

**Comment by amenity** [comment]
@ChristinaTremel - some tasks & box-checking fun for ya! 💃 ✔️

**Comment by ChristinaTremel** [comment]
Completed the tasks on this onboarding issue! 🥳
