### ISSUE TITLE
Ability to Edit an Inventory Item Request on a Work Order

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1116]
As a technician, I want to edit an inventory item request that I submitted.

## Precondition

In order to edit an inventory item request, the request must first be in a `Cancelled` or `Not Requested` status. as described [here](https://github.com/cityofaustin/atd-data-tech/issues/1113).

## Test Script

1. In the Data Tracker, start from a work order that has an inventory item with a status of `Cancelled`.

2. In the inventory items table, the edit button should be visible for the cancelled transaction. Click it.

3. Change the item type and quantity of the item. Make sure that `Inventory Checkout` is `Yes`. Submit the form.

### Expected behavior

- In Data Tracker, the item should update with a status of `Submitted to Warehouse`

- In the Finance System, the updated item should be listed on the corresponding inventory request with a status of `New Request`. The inventory request should have a status of `Submitted`.

**Comment by johnclary** [comment]
@dianamartin ready for testing

**Comment by dianamartin** [comment]
Used WO `WRK20-073355`. This is in a `Cancelled` status.
Clicked edit and changed the quantity. 
After submitting changes, the status changed from `Cancelled` to `Submitted to Warehouse`.

**Comment by dianamartin** [comment]
Confirmed in the Finance system that the status of the Inventory Request is `Submitted`. In the details of the inventory request, the item is in a `New Request` Item status.

Success!
