### ISSUE TITLE
Create MVP front end for FTT Index

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11190]
Build a page with a table that captures the fatalities from car crashes that has the following layout:

- A tab labeled "Fatalities" 
- Title at the top of the page that reads "Fatalities"
- A table in the same style of the crashes index page that takes up the page
  - The table would have the following columns: 
    - Year, Crash ID, Case ID, Law Enforcement #, YTD Fatal Crash, YTD Fatalities, Crash Date, Location, Victim Name, Current FRB Status, and FRB Recommendation
- The table will not be sortable and filterable by each of the columns (at this time)
- Do not include advanced search or date filtering at this time
- Each row in the table represents a single fatality, with the information for that person listed in the corresponding columns
- Reuse the pagination from the crashes index to navigate through the data.

Update 1/30/22: New issues are being created for the unfinished work of this issue due to its complexity ie. backend automation, YTD functions, migrations. This issue is now primarily for the front end and initial creation of the new fatalities table in the DB

----

**Fatalities Tab**

![screencapture-visionzero-staging-austinmobility-io-editor-2023-01-12-09_50_56 (1).png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/b2e3e55c-e33b-4ef2-854e-5bd6c22b9dc9)

**New Schema**
_FTT Index page MVP [spreadsheet](https://cityofaustin-my.sharepoint.com/:x:/g/personal/joel_meyer_austintexas_gov/ESyinv4ESM5Inl-UKNPafssBuevqjqwE84CkHa9D1UGOyg?CID=e4e5a455-ee18-c0b8-deb9-48ba3b743d8b)_

![MVP.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/7868d386-2165-4bd4-bdfd-a1933ecb3d19)

**Comment by chiaberry** [comment]
- [ ] discuss YTD calculations with rest of dev team
- [ ] discuss making a new table or adding the new fields to an existing table

**Comment by roseeichelmann** [comment]
To do:

Backend:

- [ ] Create a Fatalities table in the DB
- [ ] Add new fields to table (name, location, law enforcement #, YTD #s, year)
- [ ] Make relationships between new fatalities table, crashes, primarypersons and persons tables

Front end:

- [ ] Write queries to pull data from the Fatalities table in the db to be displayed in a table on the Fatalities tab
- [ ] Only admin & IT supervisors have permissions to view the Fatalities tab
- [ ] Link to Crash page corresponding to that fatality in the Crash ID column
- [ ] Should be sorted by crash date by default?
- [ ] Reuse pagination from Crashes tab

**Comment by chiaberry** [comment]
Location Field : `rpt_street_nbr rpt_street_prefix rpt_street_name (rpt_sec_street_nbr rpt_sec_street_prefix rpt_sec_street_name)`

**Comment by roseeichelmann** [comment]
Update: New issues are being created for the unfinished work of this issue  due to its complexity ie. backend automation, YTD functions, migrations. This issue is now primarily for the front end and initial creation of the new `fatalities` table in the DB

**Comment by patrickm02L** [comment]
> Update: New issues are being created for the unfinished work of this issue due to its complexity ie. backend automation, YTD functions, migrations. This issue is now primarily for the front end and initial creation of the new `fatalities` table in the DB

Updated the Issue title to reflect the evolution of this Issue into only front end work.
