### ISSUE TITLE
Introduce Susanne (PIO) to DTS

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1119]
We met, today, 1/7, to introduce Susanne to our team, especially public-facing work.

Post-meeting Todo's (all John's):
- follow-up about Charlotte micromobility delegation visiting Austin
- Share PAC MoPed Slides with Susanne
- Send link to [SR form](https://atd.knack.com/dts)
- Send link to [affordable parking program](http://www.austintexas.gov/affordableparking

**Comment by johnclary** [comment]
@mateoclarke feel free to add notes. leaving this open until I do these things.

**Comment by mateoclarke** [comment]
Going to close this since its stale. @johnclary, please reopen if that was a bad move.
