### ISSUE TITLE
Improve Fulcrum integration stability - Fulcrum --> Data Tracker

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1120]
John C. 
DTS

Needs improvement. Error. 

Ex. Fulcrum ID `ebdd8ba2-643a-4f55-a3fd-8232fadedcce`

**Comment by dianamartin** [comment]
![image](https://user-images.githubusercontent.com/21112975/71934338-d7331e00-3169-11ea-9629-035b771039c2.png)

![image](https://user-images.githubusercontent.com/21112975/71934351-dd28ff00-3169-11ea-9fc0-a00813258fe0.png)

**Comment by amenity** [comment]
@johnclary - should we backlog this?

**Comment by johnclary** [comment]
We've stopped using Fulcrum. Closing.
