### ISSUE TITLE
Run script to remove DS expiration dates (LP) (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11203]
### On DS folders, if there is no issue date and an expiration date exists, remove the expiration date. 
- To fix bug on #9688 
- Fix all records created on or after 1/1/2009

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader The script has been run in V7 Dev, have created request to run in Test - SCTASK0283383

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to TEST, What are the next steps?

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test, the expiry date has been removed for all the DS folder with no issue date. We need to wait for 2-3 days to test whether any new DS folder gets updated with expiry date when there is no issue date. If it does then we need to find out the root cause. If not, we can create request to run the script on prod.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Request has been created to run the script in Prod , SCTASK0287352.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Script has been run on prod , there are few folders that were not updated. Analysis in progress

**Comment by TracyLinder** [comment]
Priya is trying to determine why the folders were not updated.

**Comment by Lpriya-LIT** [comment]
Update - Working on a new Script to update the missed folders

**Comment by TracyLinder** [comment]
@Lpriya-LIT can you please provide an update?

**Comment by Lpriya-LIT** [comment]
Update - Created new script and requested to run in Prod. SCTASK0294073

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been deployed to PROD and is ready for UAT

**Comment by TracyLinder** [comment]
### Update - not all folders have been fixed

Kim found more DS folders with an expiration date without an issue date.

**Comment by KyleErich** [comment]
ROW wants the DS folder to stop basing its expiration date on the parent BP, IF the DS hasn't been issued. Once issued, it can and should be based on what is in the parent BP.

**Comment by TracyLinder** [comment]
I am closing this. We are creating the permanent batch job on #16894
