### ISSUE TITLE
Meeting on RPP Resource for Residents w/ Legal and Mobility Srvc. 1/13/23

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11202]
# 1/4
- Joseph said to reach out to Angela R. from legal
- Emailed Angela R. from legal and told her about my inquiry
- Recommended to reach out to Elaine from ISO
- Emailed Elaine at ISO and Nancy from ISO replied
- They'd like to have a quick sync about the proposed data solution to figure out if request is viable

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/10546#issuecomment-1372927428_

**Comment by dianamartin** [comment]
# Meeting Notes
Participants: 
- ISO: Nancy, Kevin I, Darrel L., 
- Mobility Services: Jacob C., Jason R., 
- DTS: Chia B., Diana, Patrick

# Residential Parking Permit Program
- Jacob explaining business need
- Resident to look up in residential zone, permitted/un-permitted
- Passport - permitting system
- License Plate - Tyler Tech (Brazos handheld units)
  - citation writer
- Auto-reading license plate reader (parking enforcement)

Web space - residential permit look-up
- sticker indicates that it's permitting in an authorized zone
- permitted in zone red

**Comment by amenity** [comment]
@DanielStover @Colemonj @ChristinaTremel
