### ISSUE TITLE
Add Josh, Daniel, and Christina to DTS "About Us" Webpage

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11217]
**Josh C.** 
[Link to photo](https://drive.google.com/file/d/1kSENtkXROa5aygAKmOiFZwr0X30LnRAW/view?usp=share_link)
Job Title - GIS Technician
Pronouns - He/Him

**Daniel S.** 
[Link to photo](https://drive.google.com/file/d/18GxvMjd4QrrsY1dodrFgfD4sfnemoYpU/view?usp=share_link)
Job Title - GIS Technician
Pronouns - He/Him

**Christina T.** 
[Link to photo](https://drive.google.com/file/d/17ZmEV2hyZNNqRI2pr1ukZWzyXG876CpQ/view) 
Job Title - Product Manager
Pronouns - She/Her

**Comment by patrickm02L** [comment]
Job Title?

**Comment by patrickm02L** [comment]
Update empty pronoun options with null as specified in John's comment. 

https://github.com/cityofaustin/atd-product/pull/59#discussion_r1060992120
