### ISSUE TITLE
Run metadata analysis on Signs and Markings app

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1121]
John C. 
DTS

@SurbhiBakshi Can you run that metadata tool thing you ran when you discovered all those unnecessary tables on the VZA/Signs and Markings app?

**Comment by amenity** [comment]
Pages to direct Knack support to look at; mostly from the Signs Work Order Details page: 
- Adding locations
- Adding time
- Adding materials
- Adding specifications/assets

**Comment by SurbhiBakshi** [comment]
wrote to Sterling at Knack with the information listed above.

**Comment by SurbhiBakshi** [comment]
ran the metadata analysis tool, have sent the metadata to @johnclary and @dianamartin

**Comment by SurbhiBakshi** [comment]
Knack is taking a closer look at this issue.

**Comment by SurbhiBakshi** [comment]
closing this issue, since there is another issue (batch delete) open for this app, and we are waiting to hear back from Knack.
