### ISSUE TITLE
Test Signs Work Orders on Tablet with and without Airwatch 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1123]

**Comment by dianamartin** [comment]
Able to reach Danny C. from CTM and have him look at the tablet profiles we have. He deleted 1 profile and I'm trying to configure the AirWatch profile back on it. 

I was able to ask him the questions I had about AirWatch's location tracking duration and the installation of AirWatch on the Brazos/Zebra devices. He said he'll do some research with AirWatch and get back to me.

**Comment by dianamartin** [comment]
## Tablet Testing

Using data only, no wifi. Using Chrome browser, signed in as Test Technician. 

Form Name | Desktop| AirWatch | No AirWatch |
| --- | --- | --- | --- |
| Location | `1:09 min` | 000 | 000 | 
| Assets| `1:37 min` | 000 | 000 | 
| Time Log | `25.73 sec` | 000 | 000 | 
| Materials |  `1:30 min` | 000 | 000 | 

### Locations | FORM
- Adding [Location](https://atd.knack.com/signs-markings#my-work-orders/view-work-orders-details-sign/5e163d39f9dd6200189432f8/?view_2640_sort=field_3498|asc) 

### Add Assets | FORM
- Adding [Specifications/assets](https://atd.knack.com/signs-markings#my-work-orders/view-work-orders-details-sign/5e163d39f9dd6200189432f8/view-work-order-signs-location-details/5e163d59bb13e40015d7bb51/) 

### Time Log | FORM
- Adding [Time Log](https://atd.knack.com/signs-markings#my-work-orders/view-work-orders-details-sign/5e163d39f9dd6200189432f8/?view_2640_sort=field_3498|asc) 

### Materials | FORM
- Adding [Materials](https://atd.knack.com/signs-markings#my-work-orders/view-work-orders-details-sign/5e163d39f9dd6200189432f8/?view_2640_sort=field_3498|asc)
