### ISSUE TITLE
Create account or update account to Knack applications that Christina will be PM for

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11238]
**Apps Christina needs access to:**

- Parking Enterprise Portal
- Data Tracker (not sure if I need an elevated level of permission)
- HR (not sure if I need an elevated level of permission)

**Apps Christina would like Builder Access to**  
_(Note: will not edit, but just to understand the back end of the applications I’ll be the PM for)_

- Parking Enterprise Portal
- Data Tracker
- HR 
- Signs & Markings

**Comment by ChristinaTremel** [comment]
@dianamartin there's no rush to this, but just looking to explore some of the apps I'll help support.

**Comment by dianamartin** [comment]
Synced with Christina, and made sure she had the correct accounts
