### ISSUE TITLE
Meet with Steve to Discuss Knack Enterprise

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1124]
- is Knack willing/able to take a deep dive into our slowest performing app (signs & markings) to help us identify the sources of the worst performance issues?
- r.e. Knack “enterprise”: can Knack provide dedicated/upgraded app servers for our larger apps? how confident are we that this would improve performance? what does the pricing look like on that? can we try before we buy?

**Comment by amenity** [comment]
Notes:
