### ISSUE TITLE
Custom Report OSE Fee Data (SS) (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11250]
### OSE requests a custom report in the ATD Report library based on the data we provided on #10925 

- OSE and ATD Finance would both like to generate this report on demand in AMANDA. Maria said she'd speak to finance about incorporating any data they're interested in. 

**Acceptance Criteria**

- The system should allow the user to generate a Crystal Report from the Reports tab for fee information similar to #10925
- The Crystal Report name should be OSE Fee data.
- Report Columns (Similar to #10925) - Folder RSN, Folder Type, Folder subtype, Folder Name, fee code, fee name, fee amount, fee notes, Paid in Full?, GL Account number, Event Start Date, Bill Date. 
- Paid in Full? column needs to be marked yes or no depending on whether the fees in the folder have been paid.
- The report needs to be sorted by fee code, then by folder type, then by folder subtype. 
- At the end of each fee code, there needs to be a total showing total amount of fee amount paid for that fee code.
- At the end of the report, there needs to be a Total revenue field showing total of all fees paid for the date range.
- Users should be able to define Event Start Date Range (Event Start Date From and Event Start Date To) as report parameters before generating the report. The Event start Date is an Info field in the RW Folders. 
- The report should pull data from RW folders of subtype Parking and Street Event, as well as SE folders. 
- The resulting report should be in spreadsheet format.

**Comment by TracyLinder** [comment]
@vschandramouli please work with Maria to define the criteria for this report. Thank you. 
FYI @Nadin-Nader

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by Nadin-Nader** [comment]
Status: Subha has the query ready it just needs to be formatted/created

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0288999 is submitted for TEST deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  TEST deployment is done. I verified. I am not getting the totals on excel. This was the case for previous report that I worked I think 99025 as well. I have attached the TEST output here for verification.

![image](https://user-images.githubusercontent.com/51680715/220775741-e03941e7-a1af-4211-93b4-a12166459fda.png)

[TEST Sample - 99026 OSE Fee Data Report.xlsx](https://github.com/cityofaustin/atd-data-tech/files/10808865/TEST.Sample.-.99026.OSE.Fee.Data.Report.xlsx)

**Comment by SubhaShroff** [comment]
Thanks @Nadin-Nader  
I sent SCTASK0290440 PROD deployment request.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This report is deployed in PROD and looks like working fine. We need to verify that with the user if its working fine for them. Thanks.

**Comment by Nadin-Nader** [comment]
Sent a chat message to Maria informing her that this is on PROD and to let me know if it is good to go.

**Comment by TracyLinder** [comment]
### PROD Accepted & Closing
- Maria approves
