### ISSUE TITLE
SIF Portal Payments Not Applying in BO or the Bill Table

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11254]
### Two bugs with SIF portal payments. 
**INC0277178**

1. Portal payments not updating BO at all. `We think this is resolved`

2. Portal payments update the payment table, but not the accountbill table. 
- Sree wrote a query to find all folders with recorded payments but outstanding bill
- 13089443, 13048155, 13025984, 13052135

----
_(previous)_

### Dan R. with TDS reporting that customers have paid SIF fees online but the system still shows the bills as unpaid.

- 2022 151496 SIF, Bill #7721506, payment confirmation [here](https://cityofaustin-my.sharepoint.com/:b:/g/personal/tracy_linder_austintexas_gov/EQbFyS70GrJNnzgoD9YrAbwBifGhHdoRuQILwImQuVnk3A?e=ze76Jt)
- 2022 151510 SIF, Bill #7721423, payment confirmation [here](https://cityofaustin-my.sharepoint.com/:b:/g/personal/tracy_linder_austintexas_gov/EdhATuOX2MhGq7PpE2n7U3sBdEajfgt4YtY4aJWVHgOjeA?e=0pIVND)
- 2022 151599 SIF, Bill #7727305, payment confirmation [here ](https://cityofaustin-my.sharepoint.com/:b:/g/personal/tracy_linder_austintexas_gov/ERZI8A6F3qtMuo0wdwdzQqwBt8ACoTH_ZvXxZCqU6VKxfw?e=8JblLe)

----
**This has happened before, see issue #10233**

**Comment by TracyLinder** [comment]
**Email Sent to Dan R:**
- Email sent asking for the payment confirmation for the 3 bills in the description.

**Comment by TracyLinder** [comment]
FYI @Nadin-Nader - this is another round of SIF payment failures. All details are in the description and this is ready for debugging. Sree worked on this bug last time.

**Comment by TracyLinder** [comment]
@Nadin-Nader FYI

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I have done analysis and found that one of the commit got over written by some other changes so, our changes lost. Scheduled a meeting with George at 1pm today to go over the details of the commits. And I also tested the same in TEST, TEST is working as expected. 

These are the previous Commit Order as per #10233
committed to PROD.
Commit Order 1: 87f67948354e
Commit Order 2: 8befebcccad5 (This is created by George as per our discussions with CTM team and Swapna)
Commit Order 2: [f13819189a6f] (This commit got overwritten) (http://coaamandadevops02.austintexas.gov/R5:f13819189a6f355334144ed00fe0d1711284c061)

![image](https://user-images.githubusercontent.com/44907715/214648431-798be386-a158-4068-af80-7a23d418d308.png)

**Comment by TracyLinder** [comment]
Thank you @Sreelatha-BlazeKannan 

I forwarded your email to Deanna with CTM so she's aware that code was overwritten again.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - George promoted the changes to PROD. Ready for PROD UAT

**Comment by TracyLinder** [comment]
### PROD UAT

- We can't test online payments in PROD without using a real credit card, so we won't be testing this ourselves. I will ask the customer to let us know the next time an online payment is made and keep this issue open. Thank you Sree!

**Comment by TracyLinder** [comment]
### UPDATE - PROD BUGS
- Online payment made on SIF ROWID 13089443 did not update accountbill table, only accountpayment table. 
![Screenshot 2023-02-13 at 2.34.26 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/1b96dbbf-e9f7-4200-bbd9-ed10fa5c8468)

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please debug

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Verified VALIDFOLDER updated with OverPaymentGlAccountRec Number to "1233343434" like RW and other Foldertypes in PROD and it looks good. All other commit related changes are Looking good. I also tested online payments in TEST for FOLDERRSN: 12875725 and it is working as expected. Here is the screen shot for your reference. I am not able to understand why it is not working in PROD. I request to have a call with Online payments team to verify the log files. 

![image](https://user-images.githubusercontent.com/44907715/219445849-fee8f88e-2f49-478b-84bd-457a8ae47631.png)

**Comment by TracyLinder** [comment]
### Meeting w/ Swapna Notes
- Swapna wants to meet with Sree to go through the SIF payment procedures. Swapna will schedule w/ Sree.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Did some research before meeting; Payment applied on SIF folders from 02/09/2023 to till date are the below 3 folderrsn's
>>13089443 Folderrsn payment applied online had issues on 02/09/2023 (above example record)  
>>13077619 Folderrsn payment applied backoffice had no issues on 02/10/2023
>>13077596 Folderrsn payment applied backoffice had no issues on 03/08/2023

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - After meeting, we found that Payment_SIF procedure in TEST and PROD are not same. George pushed the changes to PROD today Commit ID:7512d251fc05
Hoping that this would resolve the issue of online payments for SIF folder. We will have to keep an eye for future online payments.

**Comment by TracyLinder** [comment]
### Update
- Card has been updated. Next step is to meet with Swapna. 
- Tracy will create SN ticket

**Comment by TracyLinder** [comment]
### Mtg w/ CTM
Swapna, George, Tracy, Sree

- Sree saw a SIF portal payment made yesterday
- The 1st bug fix went to prod on 3/10
- Payment bug that failed to update the bill table; the payments were all made prior to 3/10
- Swapna doesn't advise us to manually update the account bill table; she thinks it would cause downward issues like with refunds. The suggestion is for Dan V with finance to void & reapply payments. 
- Swapna will fix the payment made in March because she still has the post-back.

**Comment by TracyLinder** [comment]
We're scheduled to meet with Dan V, Don P, and Dan R on Monday 4/3.

**Comment by Nadin-Nader** [comment]
Waiting for Dan V's response

**Comment by TracyLinder** [comment]
### Update & Closing
- We believe the bugs that caused this issue have been corrected/resolved. 
- We moved on to #11822
