### ISSUE TITLE
Shadow Sign Tech to Better Understand Pain Points

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1125]

**Comment by amenity** [comment]
Email from Christina this morning:
> I just talked to Gilbert and he has been saying that the past few weeks the Signs and Markings app has actually been running great for him! (yay J) We will have a division meeting next Tuesday and during that time I’ll reach out to other technicians and see if anyone is still having problems. If they are, I will have you schedule a ride-along with that person.

So putting this in the backlog for now.

**Comment by amenity** [comment]
Haven't heard more about performance issues.
