### ISSUE TITLE
Add public process status to activity log tracking

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#11255]
As a companion to https://github.com/cityofaustin/atd-data-tech/issues/10833, we need to update the Moped project activity log event trigger to track this new field. The activity log entries should be similar to how we hand project lead:

1. Changed public process status to **Needed**
2. Removed public process status

**Comment by tillyw** [comment]
fixed with https://github.com/cityofaustin/atd-moped/pull/948
