### ISSUE TITLE
[BUG] Metrobike trips have missing checkout date and time

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#11262]
Our [Metrobike trips dataset](https://data.austintexas.gov/Transportation-and-Mobility/Austin-MetroBike-Trips/tyfh-5r8s) has a bunch of records with a missing checkout date and time.

As [discussed on Slack](https://austininnovation.slack.com/archives/CHZE6BC6L/p1674493363488239), it's because the source data was missing these values.

The problem is that we use the `checkout_date` field to check if the trip data in Socrata is up to date vis a vis the trip record files we source from Dropbox. Having `null` values in this column leads to unexpected behavior.

We should:
- [x] delete all of the December 2022 data from the trip dataset, which is the source of the problem
- [x] Add schema validation to our ETL to prevent this from happening again
- [x] Have the metrobike folks clean up their data

**Comment by johnclary** [comment]
Hunter confirmed that they cleaned up the data. I manually triggered the Airflow DAG. Our trip data is now up to day through Feb. We're done here!

**Comment by patrickm02L** [comment]
Hooray!!!
