### ISSUE TITLE
Edit Local Copies of CTN to Formalize Understanding of Workflow

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#11260]
Daniel and Josh both used extracts of the CTN to better understand the process of applying edits to the CTN

- [x] Create Extracts CTN
- [x] Create individual projects for D and J
- [x] D and J are familiar w/ process

**Comment by DanielStover** [comment]
After making edits in the local copy, I am now familiar with the workflow.

**Comment by Colemonj** [comment]
Once making edits in local copy, I now understand the workflow

**Comment by DanielStover** [comment]
Looks like we completed everything so I will now close this issue.
