### ISSUE TITLE
[Traffic Register] Jan 24 Sprint Review - Usability Feedback, Part 1

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#11278]
We will discuss usability feedback and potential enhancements or pain points of the Traffic Register

Meeting Date: 01/24/23 @ 2pm

**Comment by ChrispinP** [comment]
Usability Feedback Notes:

- Moderate difficulty with updating copied regulations
- Add Side field to Search Results?
- General Location has 3 purposes; ensures street data quality, gives sign installers a better idea of the regulation location, and it also provides a data point that can be searched or reported on
- Connection ID provides us a unique identifier that is searchable for each record in addition to its Historical Regulation ID
- Greater visibility on corrections needed and corrections made
- Drafting option details displayed in Draft Builder

**Comment by dianamartin** [comment]
# Meeting Notes
Participant: Joana, Christina, Ed, Dipti, Stephen, Anthony, Susanne, Eric, Daniel, Ravi, Ryan, Diana, Chrispin

**Comment by dianamartin** [comment]
- [x] Have schedule follow up on Feb 2023
