### ISSUE TITLE
Refine Viewer interface

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1127]
Clicking on officer name prompts modal with officer phone number.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/75f957fb-124d-464b-b7bf-6494a79e1494)

**Comment by SurbhiBakshi** [comment]
@amenity 
I set up the modal for officer contact information, but looks like an email is required for a knack user account, so I can't delete the dummy email for 'No Volunteer Available', which is needed for reporting.
