### ISSUE TITLE
Rotate keys - March 8th

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11287]
Get a key, replace it and invalidate the old one. 

Ideally if possible narrow down the permissions a key has. 

Take notes on the process for rotating keys to help the next time we do this go faster

- [x] open issue to rotate keys 90ish days later
- [x] documentation
   - Ranking priority
      - High: Hasura secrets and AWS access keys and secrets 
      - Lower: Docker tokens stored in Github Action secrets
      - Consider how many places that we have secrets stored
   - Rotation schedule
      - High priority: Every 3 months
      - Lower: Every 6 or 12 months?

**Comment by mddilley** [comment]
Hoping to catalog these as I go through and rotate them. Frank added 2FA to the ATD service bot account so that iwill need to be rotated the next time around https://austininnovation.slack.com/archives/CHZE6BC6L/p1678737568203359

**Comment by mddilley** [comment]
Next issue is https://github.com/cityofaustin/atd-data-tech/issues/11876

**Comment by mddilley** [comment]
Some docs now exist in Gitbook > ATD Dev > Dev Team Security Practices > Rotating Secrets
