### ISSUE TITLE
[Enhancement] Ability to advanced search using multiple filters as "or"/"any" condition

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#11282]
Per Brian C @ AMD, users need the ability to filter projects using multiple filters, where each search result may match only one of the filters.

For example, to search for all projects where Arterial Management is either the Lead, Sponsor, or a Partner.

**Comment by mddilley** [comment]
@johnclary I'll open a PR early next week for this one. Made a lot of assumptions about the UI and how this works so I'll be looking for feedback. I'll plan to demo in dev sync next week too but there is [a branch](https://github.com/cityofaustin/atd-moped/tree/md-11282-plv-or) for now.

**Comment by johnclary** [comment]
sounds great @mddilley! can't wait to see it 🚀
