### ISSUE TITLE
Determine workflow for data updates/changes (create model to process locally, append to local blank schema, and then overwrite existing service)

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#11295]

**Comment by andrewshensky** [comment]
Initial work for this was done to create model for Minor Construction Conflict map (MOPED). That model needs to be revisited and revised for the Major Construction Conflict Map.

**Comment by ATD-ZachB** [comment]
This process has evolved and now is incorporated into a live application used to view conflicts more regularly and is no longer relevant.
This task is no longer needed.
