### ISSUE TITLE
Add CSWZ to ROW Customer Portal Landing Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11301]
### Before rolling out the conflicts shared work-zone, we need to add the service to the ROW Customer Portal home page

**Comment by ChrispinP** [comment]
The service page for the CSWZ application has been added to the customer portal. Reached out to Darren and team to provide a description and review service page language so it can be updated.

**Comment by ChrispinP** [comment]
Karo was able to update the service page language, and is now active with the Customer Portal go live. 

Pending any further changes.

**Comment by KaroEngstrom** [comment]
## Th 3/9/23 

- follow up request from Samson N. 
"To modify a note on our intake portal, can the TCPReview email be changed to TCP intake portal instead see attached screen shot."

<img width="712" alt="image" src="https://user-images.githubusercontent.com/100615928/224101984-9a9a617a-1cbd-4a7a-9ecb-e7a60c040ef3.png">

- [ ] Update link to reflect new process (previous verbiage was from the Smartsheet)
- [ ] Notify requester

**Comment by KaroEngstrom** [comment]
Notified Samson: "I removed that last sentence in the first bullet point about emailing." 
Samson responded: "Thanks, Karo" 
Closing this issue
