### ISSUE TITLE
Review/Update ArcPro and AGOL Training Documentation

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#11300]
**Tasks**

- Verify all links are valid
- Make sure all trainings are relevant
- Review all "Free" and "Requires Maintenance" Trainings in ESRI Academy

**AGOL Training Page (read-only)**
https://atd-dts.gitbook.io/atd-geospatial/arcgis-online/training-page
**ArcPro Training Page (read-only)**
https://atd-dts.gitbook.io/atd-geospatial/arcgis-pro/training-page

**Comment by DanielStover** [comment]
The ArcGIS Online and ArcGIS Pro training pages have been reviewed. Training courses that no longer exist  were noted.

**Comment by DanielStover** [comment]
The ArcGIS Online and ArcGIS Pro training pages have been edited. Training courses that no longer exist on ESRI were removed or replaced with a relevant course.
