### ISSUE TITLE
Stop "reassociate missing locations" script from timing out

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11302]
This dag had a few hiccups and then has been failing consistently for the last few days. 
https://airflow.austinmobility.io/tree?dag_id=atd_visionzero_reassociate_missing_locations_production&root=
![Screen Shot 2023-01-25 at 10 27 37 AM](https://user-images.githubusercontent.com/12474808/214619780-e5497bb7-16d2-4b43-a83d-931e1e45571e.png)

https://github.com/cityofaustin/atd-airflow/blob/master/dags/python_scripts/atd_vzd_update_cr3_locations.py

I ran the sql query from line 33 to to line 67 against the read replica this morning, to see how many crashes need their location updated, and the result was 0.

~~Next step is to run the entire script in prod and see what the error message is.~~

edit -- refactor sql query to be more efficient

**Comment by patrickm02L** [comment]
We still need to find out what the error is. Talk more about this in Dev Planning 1/25/23

**Comment by chiaberry** [comment]
The ETL worked today, without us having to do anything. I'm inclined to keep this open for a few more days in case it fails again. and then we can grab the error message at least.

**Comment by patrickm02L** [comment]
Sounds good. Thanks for flagging this and potentially taking any future action.

**Comment by frankhereford** [comment]
The DAG has started to fail again. I am going to add myself to this issue and give it a once-over to try to replicate and fix the error.

**Comment by chiaberry** [comment]
Frank's intuition this morning was right -- the script is timing out. I propose reframing this issue as fixing the time out (@frankhereford has pointed out that the sql part of the script can be rewritten to be more efficient) I'm opening a PR to hopefully make the error reporting more useful. 

@patrickm02L let us know what priority you want for this issue now that its been triaged a bit more

**Comment by frankhereford** [comment]
The way that this query puts the RR under load is not ideal, so I evaluate this as more urgent. The DB underload impacts other services, and if we get crashes mis-categorized, it's likely that we'll be causing the VZ team to come up with slightly askew analytics -- and really, that last reason is a whole other reason to compel us to get this fixed sooner than later.

As to what we can do - John and I had an interesting discussion on options [here in slack](https://austininnovation.slack.com/archives/CM9MK950S/p1675102762033039).

**Comment by patrickm02L** [comment]
The last time this DAG was run was 9/25/23. Did we replace this or is it being captured by another process? If not, should we turn it back on?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalQyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6e2d6a7287cb4a52546517f8e08eecf14502f194/Screen%20Shot%202023-10-02%20at%209.23.03%20AM.png)

**Comment by chiaberry** [comment]
did not replace this as far as I know, i turned the DAG back on. 🙏🏼 thank you for catching this

**Comment by patrickm02L** [comment]
This DAG was shut down as part of the VZ 1.37.0 Pease Road release. It should remain off.

[See comments](https://github.com/cityofaustin/atd-data-tech/issues/13591#issuecomment-1734519867)
