### ISSUE TITLE
Produce list of planned mobility projects by council district

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11303]
From Karla via Cole in email to @johnclary & @maccallump ...
> _...we have had a request from the Assistant City Manager to provide each council office with a list of ATD projects that are underway in their respective districts. This will be for planned projects – so we do not have to include items such as CSRs and CAFs that involve our staff responding to a call from the community or from a council office._
>
> _We are under a tight deadline on this request from ACM, so please send us back your list of projects by the end of the day Thursday. PIO will work to compile the information from our various ATD divisions and have district-by-district information to ACM’s office by the end of the week. If a project goes into multiple council districts, please include all districts it touches. The template attached includes the basic information we’ll need, including the stage of the project, a brief description, expected timeline, a contact person (assistant director) and the council district. Happy to answer any questions, thanks so much for your help with this._  

 For each project, they'd like: 
- Project Name	
- Description	
- Stage of project (design, construction, etc.)
- Timeline 	
- Contact (Assistant Director) 	
- Council District

**Comment by amenity** [comment]
A couple of ways of approaching this from our email thread:
- Work with GIS team to produce a breakdown of Moped projects by council district - depends on GIS team availability, would need to supplement with a list from Nathan (& CPO?)
- Pull council data from a list of eCAPRIS projects - will only include projects with capital funding

**Comment by amenity** [comment]
Thanks so much, @johnclary for taking this one. 🙏🏻 🗺️  We'll also need some geo support.

**Comment by johnclary** [comment]
I have the Moped project data ready to be processed by the geo folks. Y'all just let me know who to pair up with please.

**Comment by amenity** [comment]
Per Slack, @andrewshensky is taking this one. Thanks!

**Comment by johnclary** [comment]
I ended up doing this by [loading council districts into the Moped DB](https://github.com/cityofaustin/atd-moped/pull/958).  I sent the data to the email thread and am waiting for any feedback.
