### ISSUE TITLE
[BANNERS] Add Total Price to LPB and OTS Banners Tables 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#11311]
**Requester:** 
Rachel C. in Smart Mobility 

**Context:** 
For reporting, Rachel uses the tables for [LPB](https://atd.knack.com/street-banners#lpb-application-dashboard/) and [OTS](https://atd.knack.com/street-banners#ots-application-dashboard/). She exports the data from each table and applies her own filters to narrow down to desired scope. 

**Request:**  
Add Total Cost information for each reservation so that the user doesn't have to look up cost manually for every row.

**Comment by KaroEngstrom** [comment]
@dianamartin This came up when I was talking to Rachel today. Is this feasible? I'd be happy to do it if displaying the **Total** field in the tables for both `banners_reservations_ots` and `banners_reservations_lpb` is okay.

**Comment by dianamartin** [comment]
@KaroEngstrom I just checked this out and I think you could do two things:
## Option 1
- adding the totals on the reservation tables 
>but I don't love this option bc it's exposing all the fields that a user may or may not need
## Option 2
- Add a new report subpage for the totals
>I'm more for this option
- adding LPB and OTS tables and adding the totals OR

**Comment by KaroEngstrom** [comment]
# F 1/27/23 

- added a button to Banners reporting page for **Export Tables** 
- added Export Tables page that contains duplicates of the OTS and LPB Applications (reservations) tables with the the additional of Total (LPB) and Total Fee (OTS) fields
- included the ability to filter and search entire records as well as export for best usability 

- [ ] double-check that the cost fields are the accurate ones
- [ ] reach out to the requester
- [ ] update change log

**Comment by patrickm02L** [comment]
In planning 2/8/23. Karo will check in with Diana to double check the cost field.

**Comment by KaroEngstrom** [comment]
No response, closing this issue
