### ISSUE TITLE
Automate Tech Surcharge on TDS Fees (SS) (Review Scheduled for Tuesday 4/18 10am)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11315]
### When a TDS fee is added by a user or the system, the system should automatically insert the ATD Tech Surcharge fee with it. 
- Related to #10952 and #11314

**Acceptance Criteria** 

- Add a Fee Procedure in the Insert and Run Procedure menu for "ATD Tech Surcharge" that inserts "ATD Tech Surcharge ROW" fees as a line item and 4% of any existing fee as the fee amount.
- Fees for which ATD Tech Surcharge should be calculated are mentioned in #10952 and #11314.
- There only needs to be one ATD Tech surcharge rows inserted with the combined total Tech surcharge for all eligible fees. 

----
### We need to:
1. Compile a list of fees and codes that need the surcharge to insert with (all TDS fees except SIF)
2. Subha needs the fee code and the folder type

**Comment by TracyLinder** [comment]
I emailed Amber & Daniil and asked for the list of active fees they refer to. Then we'll map those to the fee codes and add them to the AC for Subha to pick up.

**Comment by TracyLinder** [comment]
### Current list of fees provided by Amber


![Screenshot 2023-01-27 at 2.14.10 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/0a966002-ae24-4dfc-b013-7491b6205720)



![Screenshot 2023-01-27 at 2.14.33 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/51e9d0e0-8be7-44f5-88cb-b304ba9f52b0)

**Comment by SubhaShroff** [comment]
@vschandramouli  Please let me know when the fee codes and folder types are ready. I can take this or 11314 next. Thanks.

**Comment by vschandramouli** [comment]
@SubhaShroff #11314 is ready with fee codes. Please refer. I will update this one shortly.

**Comment by vschandramouli** [comment]
Updated AC and added reference to #11314. Moving to Backlog.

**Comment by SubhaShroff** [comment]
@vschandramouli Did you check with Daniil if we are doing the auto insert the tech surcharge for all the fees in this ticket?

**Comment by vschandramouli** [comment]
@SubhaShroff Confirmed from Danil that the tech surcharge needs to be automatically inserted along with other fees only.

**Comment by SubhaShroff** [comment]
Thank you @vschandramouli
@Nadin-Nader  Following commits done for 37 procedures. Yet to update the VALIDLOOKup-50064 lookup and have to work on rest of TDS fees. Work in progress..................
[6f2aad4443ce](http://coaamandadevops02.austintexas.gov/R5:6f2aad4443ce1543a8dc6199a1c4b2fb6bfd4041), 
[833b47d03f11](http://coaamandadevops02.austintexas.gov/R5:833b47d03f1185e81e1e78d997961840f0365cb4)

**Comment by Nadin-Nader** [comment]
@SubhaShroff the commits above have been approved

**Comment by SubhaShroff** [comment]
Thanks @Nadin-Nader. I need to do one more commit for VALIDLOOKup table for the fees for which there is no entry, I identified and adding those records.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0292968 - A request is raised to DEV deploy the above six commits. Due to Amanda local limitations(slowness), I couldn't test these fees. Now I am testing on DEV.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0294268 is requested for DEV merge for the failed fees fix after doing DEV test.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @vschandramouli  @TracyLinder Here are the DEV results. For ZC fees that failed I submitted above request - SCTASK0294268. 

1. I have highlighted TIA fees - The issue is fees are not inserting and so tech surcharge is also not inserting. The root cause for the fees not inserting is - the end dates in LOOKUP table for those fees is not updated to Oct 2023. However, this is out of scope for this ticket.
2. There are two fees yellow highlighted, which I couldn't find the feecodes - so not worked on those.
[11315 - DEV Test Results.xlsx](https://github.com/cityofaustin/atd-data-tech/files/10969489/11315.-.DEV.Test.Results.xlsx)
Please advise. Thanks.
Advi

**Comment by Nadin-Nader** [comment]
@subha this is what i got from Daniil:

> [11:04 AM] Kontsevoy, Daniil
> Street Review Completeness check is probably "Transportation Completeness Check"
> 
> [11:04 AM] Kontsevoy, Daniil
> we do not have fee codes, I believe they have to be assigned
> 
> [11:05 AM] Kontsevoy, Daniil
> I found this in the prod: 
> 
> [11:06 AM] Kontsevoy, Daniil
> Transportation Completeness Check will be a new fee, there is no code assigned

@TracyLinder  can you verify with Finance on what Daniil is saying?

**Comment by TracyLinder** [comment]
### Responses
FYI @Nadin-Nader  @SubhaShroff 

- Street impact fee doesn't have the surcharge. (It's highlighted on your spreadsheet.)
- Don't make a fee for the Transportation Completeness Check. (TDS doesn't use it right now.)
- Please make a card for updating the expiration dates. @Nadin-Nader can you do this please? Or ask Vish for help?

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder Above mentioned deployment is done. Tested for the fixed fees. DEV test results attached. Please let me know if I can go for TEST deployment. Thanks. 
[11315 - DEV Test Results.xlsx](https://github.com/cityofaustin/atd-data-tech/files/11002223/11315.-.DEV.Test.Results.xlsx)

**Comment by TracyLinder** [comment]
@vschandramouli can you please review the doc Subha attached in her previous comment & provide feedback? Let me know if you want help.

**Comment by SubhaShroff** [comment]
Thanks @vschandramouli.  I think for those TIA fees, I mentioned somewhere in the ticket thats because the end date is not updated for those. And Tracy has suggested to create a ticket. So, that will be taken care in other ticket, later.
@Nadin-Nader SCTASK0298138 is submitted for TEST deployment. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I tested it on TEST and test results are attached. All fees passed for ATD Tech Surcharge, except for the following one fee failed:
1. 83491 - ATD-ZON-Review <10 Acres - Didn't add surcharge for this fee - I will investigate why its missing. If necessary will do another commit for this. But for rest the users can do UAT.
2. Yellow highlighted rows didn't have right amounts added. Otherwise ATD tech surcharge is added as per the scope of this ticket.
Thanks

**Comment by SubhaShroff** [comment]
> @Nadin-Nader I tested it on TEST and test results are attached. All fees passed for ATD Tech Surcharge, except for the following one fee failed:
> 
> 1. 83491 - ATD-ZON-Review <10 Acres - Didn't add surcharge for this fee - I will investigate why its missing. If necessary will do another commit for this. But for rest the users can do UAT.
> 2. Yellow highlighted rows didn't have right amounts added. Otherwise ATD tech surcharge is added as per the scope of this ticket.
>    [11315 - TEST Test Results.xlsx](https://github.com/cityofaustin/atd-data-tech/files/11127332/11315.-.TEST.Test.Results.xlsx)
> 
> Thanks

@Nadin-Nader  [f6c5b8855fdf](http://coaamandadevops02.austintexas.gov/R5:f6c5b8855fdfa59fc6c75150062d7735ab8e1e1a) is committed for fee 83491 - ATD-ZON-Review <10 Acres. Please audit it.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0300355 is submitted for DEV/TEST deployment of the above mentioned commit. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  83498 | ATD-Transportation Development Assessment - Amount is refixed to 1580 in DEV/TEST. TEST RSN - 12879991.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0302777 is submitted for PROD deployment. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This ticket is also in PROD now.

**Comment by Nadin-Nader** [comment]
Going over this with Amber and Daniil on Tuesday at 10am

**Comment by TracyLinder** [comment]
### Closing
- During UAT only one fee didn't have the surcharge, so I created a new issue for it, #12063
