### ISSUE TITLE
TDS Fee Bug Fixes, Part 2 (SS) (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11314]
### This is a continuance of TDS fees missing or needing updates in AMANDA. 
- Part one is #10952 

**Acceptance Criteria** 

- Fees provided below will need to be updated with the correct amounts
- 83492 ATD-ZON-Review >15 Acres $3,950
- 83493 ATD-ZON-Review <=15 Acres $3,160
- 57030 Planned Area Development (PDA) - $3,160 - Used in ZC Folders
- 83414 Zoning Traffic Impact Analysis (ZTA) Review/Compliance Check (Fee description in Amanda - - ATD-SP-TIA Waiver/Compliance)- $6,320 - Used in SP Folders
- 51712 - Plat/Subdivision Vacation - $1,140 - Used in C and C8 Folders
- 83498 - Transportation Development Assesment - $1,580 - Used in DA and SP folders
- Transportation Completeness Check - (Not Found in Fee Menu) $25.00
- 51022 - Site Plan Corrections (Fee Description in Amanda - Site Plan Correction) - $75.00 - Used in SP, ZC and C8 folders.
----
### We need to...

1. Work with stakeholders to identify any remaining fees that are missing or need updating. Get their confirmation that the list we put together is accurate before we start working. 
2. Update the remaining fees.

**Comment by TracyLinder** [comment]
@Nadin-Nader please comment with the fees Daniil said are missing.

**Comment by TracyLinder** [comment]
Here are the fees Subha needs the fee code and folder types:

Transportation Development Assessment
Transportation Completeness Check
Site Plan Corrections
Plat/Subdivision Vacation

**Comment by Nadin-Nader** [comment]
@vschandramouli @SubhaShroff  Here is the list of Fees that Daniil mentioned were either missing or had the wrong fee amount. @vschandramouli we still need the Fee codes and foldertypes for some):

Planned Area Development (PDA) - (Not Found in Fee Menu) $3,160
Zoning Traffic Impact Analysis (ZTA) Review/Compliance Check - (Not Found in Fee Menu) $6,320
Plat/Subdivision Vacation - (Not Found in Fee Menu) $1,140
Transportation Development Assesment - (Not Found in Fee Menu) $1,580
Transportation Completeness Check - (Not Found in Fee Menu) $25.00
Site Plan Corrections - (Not Found in Fee Menu) $75.00


Wrong fee amounts:
83492 ATD-ZON-Review >15 Acres $3,950
83493 ATD-ZON-Review <=15 Acres $3,160

**Comment by TracyLinder** [comment]
@vschandramouli can you please update the issue description with the list of fees to be updated? Thank you.

**Comment by Nadin-Nader** [comment]
Need to ask Amber if this fee is even being charged because its not in AMANDA and the  proposed budget doc shows it needs to be added:

Transportation Completeness Check - (Not Found in Fee Menu) $25.00

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/59e29cbf-e0b8-4fc7-90a6-8cbcd341f0ea)

**Comment by vschandramouli** [comment]
Updated codes for all fees except Transportation Completeness Check Fee, which needs confirmation from Amber. Moving to Backlog. 

CC @Nadin-Nader @TracyLinder

**Comment by SubhaShroff** [comment]
@Nadin-Nader @vschandramouli  Any update from Amber for Transportation Completeness Check Fee?

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0287556 is submitted for DEV deployment. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I tested the fees on DEV and few fees are not working as expected. I fixed couple of those and will have to reach out to Martin for other fees. I think default procedures need a compilation on DEV.
83492 ATD-ZON-Review >15 Acres $3,950 -------------DONE - no tech surcharge  
83493 ATD-ZON-Review <=15 Acres $3,160   ----------DONE - no tech surcharge  
57030 Planned Area Development (PDA) - $3,160 - Used in ZC Folders  ----------DONE - surcharge added
83414 Zoning Traffic Impact Analysis (ZTA) Review/Compliance Check (Fee description in Amanda - - ATD-SP-TIA Waiver/Compliance)- $6,320 - Used in SP Folders                                 ----------DONE - no tech surcharge  
51712 - Plat/Subdivision Vacation - $1,140 - Used in C8 Folders -----------DONE - no tech surcharge
51022 - Site Plan Corrections (Fee Description in Amanda - Site Plan Correction) - $75.00 - Used in SP. DONE - no tech surcharge

A commit is done with the changes in the procedures:
------------------------------------------------------------
83498 - Transportation Development AssesSment - $1,580 - Used in SP folders   ------------NOT adding the fee
83498 - Transportation Development Assessment - $1,580 - Used in DA folders   ------------NOT adding the fee

For following  I will reach out to Martin:
---------------------------------------
51712 - Plat/Subdivision Vacation - $1,140 - Used in C              ------------NOT adding the fee - working in LOcal not DEV. 
51022 - Site Plan Corrections (Fee Description in Amanda - Site Plan Correction) - $75.00 - Used in ZC.  ------------NOT adding the fee
51022 - Site Plan Corrections (Fee Description in Amanda - Site Plan Correction) - $75.00 - Used in C8.  ------------NOT adding the fee

**Comment by SubhaShroff** [comment]
@Nadin-Nader [SCTASK0288627](https://atx.servicenowservices.com/sc_task.do?sys_id=b52f5a1b870d6510287cb9d8cebb3564&sysparm_record_target=sc_task&sysparm_record_row=1&sysparm_record_rows=1&sysparm_record_list=request_item%3D112f1a1b870d6510287cb9d8cebb35f5%5EORDERBYnumber) is submitted for DEV deployment. Apart from that, other fees that are not working I emailed Martin to do recompile the default procedures.
Yet to hear from him.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Still waiting on [SCTASK0288627](https://atx.servicenowservices.com/sc_task.do?sys_id=b52f5a1b870d6510287cb9d8cebb3564&sysparm_record_target=sc_task&sysparm_record_row=1&sysparm_record_rows=1&sysparm_record_list=request_item%3D112f1a1b870d6510287cb9d8cebb35f5%5EORDERBYnumber) deployment.

The other fees mentioned below that were not adding, now adding as expected.
51712 - Plat/Subdivision Vacation - $1,140 - Used in C Folders               ------------Adding (no surcharge)
51022 - Site Plan Corrections (Fee Description in Amanda - Site Plan Correction) - $75.00 - Used in ZC.  ------------Adding (no surcharge)
51022 - Site Plan Corrections (Fee Description in Amanda - Site Plan Correction) - $75.00 - Used in C8.   ------------Adding (no surcharge)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0289064 is requested for DEV promotion for 
83498 - Transportation Development AssesSment - $1,580 - Used in SP folders ------------NOT adding the fee
83498 - Transportation Development Assessment - $1,580 - Used in DA folders ------------NOT adding the fee

**Comment by SubhaShroff** [comment]
@Nadin-Nader  After you approved on Teams, SCTASK0289395 is raised for TEST promotion. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Tested on TEST:
RSN: DA - 12874176 -  ATD-Transportation Development Assessment(83498)   - $1580
RSN:  SP - 12877649 -  ATD-SP-TIA Waiver/Compliance(83414)                          - $6320
                                     ATD-Transportation Development Assessment(83498)   - $1580
                                     Site Plan Corrections (51022)                                           - $75

RSN: ZC - 12869900 -   Site Plan Corrections (51022)                                           - $75
                                      WPD-Planned Development Area (PDA)(57030)             - $3160
                                      ATD-ZON-Review >15 Acres (83492)                              - $3950
                                      ATD-ZON-Review <=15 Acres (83493)                            - $3160

RSN: C8 - 12869746 -  Site Plan Corrections (51022)                                            - $75
                                    Plat/Subdivision Vacation (51712)                                     - $1140

RSN: C - 12877250  - Plat/Subdivision Vacation (51712)                                      - $1140
                                   ATD-SUB-Construction Plan (83424)                                  - $3160

All looks good with right amounts as in AC. Its ready for review.

**Comment by SubhaShroff** [comment]
Thanks @Nadin-Nader. SCTASK0302750 is submitted for PROD deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder This ticket is  in PROD now.

**Comment by Nadin-Nader** [comment]
Going over this with Amber and Daniil on Tuesday at 10am

**Comment by TracyLinder** [comment]
### DTS Sync
_Nate, Tracy, Subha_

- Priya Departments have their own branches, so things are overwritten. 
- George said commits were pushed, but Subha still sees differences
- George ask for all fee codes, Subha gave him query
- George will create a commit based on what is in test & push it to PROD
- We're still not exactly sure what's happening, only CTM can explain

**Comment by SubhaShroff** [comment]
@Nadin-Nader I had a chat with George and I listed the fees which I worked on in a select statement and gave me the queries, so that he can make a new commit based on what is in TEST and PROD deployment to fix the amounts. I am still looking for other fees that are spread across other validlookup tables. SELECT * FROM validlookup WHERE LOOKUPCODE=90266
AND lookup2 IN (83496, 83423, 83495, 83421, 83420, 83416, 83497, 83475, 83419, 83476,83472,83474,83422);
SELECT * FROM validlookup WHERE LOOKUPCODE=90266
AND lookup2 IN (83418, 51901, 51712, 51022, 83426, 83427, 83424, 83478, 83477, 83499, 83434, 83430, 83479, 83486, 83436)
ORDER BY lookup2;
SELECT * FROM validlookup WHERE LOOKUPCODE=90266
AND lookup2 IN (83435, 83437, 83487, 83488, 83489, 83490, 83491, 83493, 83492, 83433, 83431, 83480, 83432, 83429, 83428)
ORDER BY lookup2;

--------------------------------
All the above fees amounts are checked. 
[ATD fees Amounts different on PROD - verified.xlsx](https://github.com/cityofaustin/atd-data-tech/files/11313335/ATD.fees.Amounts.different.on.PROD.-.verified.xlsx)

--------------------------------
83498(Transportation Development Assesment fee)  fee for SP was deployed through PROD. I can see this procedure in database. But for SP the fee not showing in Amanda configuration that implies the fee not displaying in the fee menu Run Procedure. Sent an email to Martin/George.

**Comment by SubhaShroff** [comment]
@Nadin-Nader   SCTASK0307717 is deployed in DEV/TEST. I have verified it on TEST. Now for SIF fee (50500) it adds ATD tech surcharge 4%. **Ready for UAT**
![image](https://user-images.githubusercontent.com/51680715/234664280-8fcac8c4-1d97-4b2b-b65a-8f55c9de09cf.png)
The rest of the above mentioned issues we can discuss in today's call.

**Comment by SubhaShroff** [comment]
Remove 83425 from SP, C, C8, ZC . Its not used any more.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0308556 is submitted for DEV/TEST deployment of the above first 3 action items. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Tested/verified the below. 
1. .Remove 83425(ATD-SUB-Construction Plan Non-Concurrent) from SP, C, C8, ZC . Its not used any more. - **REMOVED, verified on TEST.**
2. Change the amount on 83426(ATD-SUB-Administrative Non-Environmental Variance) - C to 990 -  **FAILED on TEST(RSN-12877249)  due to old end date** 
3. Change the amount on 83473(ATD-SP-Administrative Conditional Use) SP to 3160 - **Amount is updated, verified on TEST (RSN-12890945)**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  ATD-SUB-Administrative Non-Environmental Variance  83426 amount is updated to 990. RSN-12891777 on TEST.
Now all below are ready for UAT on TEST. If we get a nod I can raise request for PROD promotion for SIF fee also, along with the following ones.
.Remove 83425 from SP, C, C8, ZC . Its not used any more.
Change the amount on 83426 - C to 990
Change the amount on 83473 SP to 3160

**Comment by Nadin-Nader** [comment]
Reached out to Amber and Daniil asking for them to UAT the following on TEST:
ATD-SUB-Administrative Non-Environmental Variance 83426 amount is updated to 990. RSN-12891777 on TEST.
Now all below are ready for UAT on TEST. If we get a nod I can raise request for PROD promotion for SIF fee also, along with the following ones.
.Remove 83425 from SP, C, C8, ZC . Its not used any more.
Change the amount on 83426 - C to 990
Change the amount on 83473 SP to 3160

**Comment by SubhaShroff** [comment]
Thanks @Nadin-Nader. I just submitted SCTASK0313109 for PROD deployment of the following:

1. Remove 83425 from SP, C, C8, ZC . Its not used any more.
2. Change the amount on 83426 - C to 990
3. Change the amount on 83473 SP to 3160
4. SIF fee (50500) - add tech surcharge

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This is in PROD now and I checked by running queries on DB. Ready for the user. Thanks.

**Comment by Nadin-Nader** [comment]
have informed Amber and Daniil that this is on PROD. waiting on response

**Comment by Nadin-Nader** [comment]
@TracyLinder @SubhaShroff Amber and Daniil both are saying that this is Working and Thank you.
Closing
