### ISSUE TITLE
[Bug] Council District layer in VZV does not render

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11327]
On 1/26/23, Mike observed that the Austin City Council Districts layer in the Vision Zero Viewer does not render when one engages the button.

John mentioned that with recent updates to CRIS software, perhaps an endpoint is no longer valid.

![Screen Shot 2023-01-26 at 7.50.25 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/58f5ecd6-ebce-4a50-9eec-ddcc480ce761)

**Comment by johnclary** [comment]
It would seem that COA tore down the Council Districts dataset we were using from the open data portal. I can't find this resource on the Open Data Portal—the request errors with `404`.

```
https://data.austintexas.gov/resource/7yq5-3tm4.geojson?$select=simplify_preserve_topology(the_geom,0.00001),council_district
```
