### ISSUE TITLE
Missing "Make Payment" button

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11323]
The "Make Payment" button is not being displayed  in the Street Banner application portal. 

![Screen Shot 2023-01-26 at 12.38.53 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/96b29ba5-e70d-4739-9b8e-d90823fcebc8)

**Comment by dianamartin** [comment]
I looked into this issue and found that the Application "Add Comment" email notification was referencing the wrong web URL to the "Application Details". 
- Was: `https://atd.knack.com/street-banners#application-details-ots/` (missing `Record ID`). 
- Should be: `https://atd.knack.com/street-banners#ots-applications/application-details-ots/RECORD_ID`

![image](https://user-images.githubusercontent.com/21112975/214953666-9a811f4d-3520-451e-b69c-96b139328626.png)

I’ve resolved the issue that was happening. The “comment email notification” (as seen in screen shot), has the “Application Details” link and it was directing to a bad web URL. I fixed it and tested it, and that link should be directing folks to their application details page.

**Comment by dianamartin** [comment]
Mirna reached out because she came across some other applications that seemed to not work, it was because there were no "invoice transactions". She said she'd review them again to confirm they were added, some of them were before the CityBase migration.
