### ISSUE TITLE
[Bug] Investigate inconsistent counts between VZV and VZE for 2023; resolve inconsistency

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11339]
On 1/27/23, @xavierapostol notified us about the count of the VZV vs. the VZE was off by one. 

The Vision Zero Viewer is showing this:

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/fd51b365-0996-4eee-acec-eb2999da47ce)

The VZE is showing this:

![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/6972a054-210a-4b60-ad00-84a4a6c831f1)

Upon further investigation we recognized that Crash ID [19340147](https://visionzero.austin.gov/editor/#/crashes/19340147) was showing zero for the CRIS Death Count, and the CR3 did not have a fatality listed. It's worth noting that the person in unit 2 was transported to the hospital, but we don't have any information beyond that. If they died the current CR3 has not been updated to show it.

![Screen Shot 2023-01-27 at 3.46.25 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/33b5de34-8a0b-46cc-b786-398fb5c459ba)

We'll continue to keep an eye on this inconsistency and work to resolve it when we get clarity on why the CRIS Death Count is off.

**Comment by patrickm02L** [comment]
Tagging y'all in case we need to continue to investigate and ultimately spend time resolving this. @roseeichelmann @chiaberry @frankhereford @mddilley 

Thanks for your insights in today's Dev Sync on the matter.

**Comment by patrickm02L** [comment]
Wonder if Frank's observation about the 3 schema CR3 extract in [this thread](https://austininnovation.slack.com/archives/CM9MK950S/p1682083241354269?thread_ts=1682029500.809509&cid=CM9MK950S) has something to do with the inconsistencies of the counts in VZ?

**Comment by frankhereford** [comment]
That's an interesting question. The 3 schema thing could / would result in orphaned crashes in the VZ database, but it shouldn't lead to inconsistencies. My rational here is that the VZ database is the "source of record" for itself, the VZE, the VZV, like pretty much everything. The 3 schema problem can lead to our VZ database being out-of-sync with CRIS, but all of our applications should be consistent with each other. The 3 schema thing might make them all wrong compared to CRIS, but they should be consistently wrong in the same way.

**Comment by johnclary** [comment]
Any lingering inconsistencies will be addressed with the new data model 👍
