### ISSUE TITLE
Update CC Transportation Planning Planning Review 51828 and folder Doc

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11332]
### Update process 51828 on SP folder and related folder doc

1. When the system inserts this process, the system should assign it to ATD-Reviewers
2. Update the system generated doc for CC Transportation Planning Review to match the format below:

<img width="913" alt="Screenshot 2023-01-27 at 11 08 12 AM" src="https://user-images.githubusercontent.com/49930868/215153331-3786cacc-5345-443a-8c94-813d891b98ce.png">

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created request to deploy the commit to Dev/Test - SCTASK0285065

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Prod , need to verify and proceed further.

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/abcd1693-923c-410e-a8dd-55ce977263ac)

**Comment by TracyLinder** [comment]
### UAT

- Test folder ID 12878034

- [ ] Folder process assigns to ATD-Reviewers
- [ ] Review doc updated

    - I can't review the doc on MAC, so I can't test the doc. I'll ask Amber to look.

**Comment by TracyLinder** [comment]
I emailed Amber; pending her response.

**Comment by TracyLinder** [comment]
### UAT Passed
- Please promote to PROD @Lpriya-LIT

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Created Prod promotion request - SCTASK0297187

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Ready for UAT on Prod

**Comment by TracyLinder** [comment]
### Update & Closing

TDS staff has been using this doc and reported no issues yet.
