### ISSUE TITLE
Database -- automate insertion into fatalities table

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11337]
Backend companion issue to the FTT index UI work (https://github.com/cityofaustin/atd-data-tech/issues/11190)

Two viable options -- 
1. extend lambda function or write new function 
2. create database function with database trigger

--- 

Going with option 2

- [x] when a crash with a fatality comes in, update fatalities database table 
- [x] Test the function(s) on the local VZ database

**Comment by patrickm02L** [comment]
Reference for how to build the database

<img width="883" alt="Screen Shot 2023-02-07 at 12 36 27 PM" src="https://user-images.githubusercontent.com/5566727/217335326-2a8692d5-b0bf-454d-a771-3780e1614025.png">

**Comment by patrickm02L** [comment]
@frank is going to work on orchestrations locally, so that @roseeichelmann can test the database triggers in a local development setup.
