### ISSUE TITLE
[BUG] TK # required for all markings work orders submitted by Transportation Engineering

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11342]
Bug is happening on Markings Work Orders - if the work order is submitted by **Transportation Engineering** requester, the work order is requiring them to submit a Task Order Number when the "Funding/ Task Order" field is set to No.

https://atd.knack.com/signs-markings#new-work-order-markings/

**What steps can we follow to reproduce the bug you are seeing?**
1. Click **New Work Order** button on Markings Work Order Page
2. Select Transportation Engineering in the **Requester** field
3. Scroll down to **Task Order #** field to see the required field showing up. Also look at how the **Funding (FDU) #** field is hiding (which is what the Task Order # field should be doing)

**Impact of this issue?**
- Major — can only perform work using a workaround
- This issue is causing Transportation Engineering to fill out that field with things like "None" or "Blank" and this causes work orders to show up on the Reimbursable tracking page when the work should not actually be reimbursed.

**Comment by ChristinaTremel** [comment]
Hey @dianamartin, I found this bug that's happening on the markings New Work Order form when walking through the reimbursable process with Johnny. Can your team take a look at this?

**Comment by dianamartin** [comment]
Check Markings New Work Order form
- Requester: TED
- Scroll down to Task Order # field to see the required field showing up. Also look at how the Funding (FDU) # field is hiding (which is what the Task Order # field should be doing)

**Comment by dianamartin** [comment]
@ChristinaTremel cc @johnclary I think there is an underlying bug, I thought these forms auto recognized which Requester group they're with. I'm not seeing that functionality there anymore. I've also been having issues with the New Markings Work Order form.

**Comment by dianamartin** [comment]
# 1/31 
- Figured out the bug 
- Rule 11 was not correct
  - some fields were listed as Hide/show, when they needed to be Hide only

## Corrected
![image](https://user-images.githubusercontent.com/21112975/215893413-55aea435-b9ea-4394-9ac2-93df8cfe0279.png)

**Comment by ChristinaTremel** [comment]
Checked incoming Transportation Engineering work orders and saw that the TK field was working properly. Let Anthony A (Engineering) and Johnny P (Signs & Markings) know that this bug has been fixed.
