### ISSUE TITLE
Move finance data flow to prefect 2.0

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11355]

**Comment by Charlie-Henry** [comment]
I managed to get all of atd-finance-data migrated to Prefect 2.0 in this [WIP PR](https://github.com/cityofaustin/atd-prefect/pull/58).

Eventually I'll need someone to SSH into an atd-data and set us up a Prefect 2 agent.

**Comment by Charlie-Henry** [comment]
Thanks to @chiaberry for setting up the agent on data-03. I've switched off the Prefect 1.0 flow for finance data and migrated this script over to Prefect 2.
