### ISSUE TITLE
Decommission and replace any use of CircleCI for VZ

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11358]
The Vision Zero suite uses CircleCI for its continuous integration & deployment. This choice was made prior to the introduction of GitHub actions, which provide the same capabilities in a more manageable and integrated fashion. 

In light of having the capability "in-house" and [CircleCI's utterly egregious failure in terms of operational security recently](https://thehackernews.com/2023/01/malware-attack-on-circleci-engineers.html), this issue is created to track discussion and replacement of CircleCI with GitHub actions.

**Comment by frankhereford** [comment]
Linking this issue to https://github.com/cityofaustin/atd-data-tech/issues/12900.

**Comment by patrickm02L** [comment]
## 8/16/23

reference: https://github.com/cityofaustin/atd-vz-data/blob/master/.circleci/config.yml

- Circle CI runs 1-2 or bash scripts
- Make Github actions run those same bash scripts

### Notes
- Secrets to think about
- Disable CircleCI pushing anything to github

**Comment by patrickm02L** [comment]
## 09/11/23
Talked about bringing this On Deck

**Comment by mddilley** [comment]
Some discussion about the Docker part of this task in https://austininnovation.slack.com/archives/CM9MK950S/p1694468690017169. We'll cover the rest in the PR review.

**Comment by mddilley** [comment]
Finally merged this code today, and the workflow failed to build. After some debugging ([see thread](https://austininnovation.slack.com/archives/CM9MK950S/p1694794532844279)), [it nows builds](https://github.com/cityofaustin/atd-vz-data/actions/runs/6201164363) so I'm going to close this one. 🚀
