### ISSUE TITLE
VZE λ functions do not build due to malformed JSON in zappa configuration for staging deployment

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11371]
Please see the following build log, as an example: https://github.com/cityofaustin/atd-vz-data/actions/runs/3680516210/jobs/6226204306

In particular:

```
Using stage: 'staging' (Current working stage: 'pr_1137')...
Validating JSON syntax for zappa settings file...
LOCAL_STAGE: staging
parse error: Unmatched '}' at line 1, column 80
Error: Process completed with exit code 4.
```

This will prevent testing of updated builds in staging.

Update (2/6/2022): 

Now that the updated lambda functions have made it into `master`, they did not deploy successfully. This was expected, but the particular error encountered was not. Please see [this log](https://github.com/cityofaustin/atd-vz-data/actions/runs/4108336374/jobs/7088912174) from the staging deployment as part of triaging this issue for, hopefully, more information.

**Comment by chiaberry** [comment]
Going to close because I do not think this is currently happening -- will reopen if we come across it again
