### ISSUE TITLE
[Enhancement] Create a non-editable view of the Sign | Asset Items table for Requesters

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11386]
Mobility Services is wanting to use Signs & Markings work order data to help them manage their parking GIS datasets. To do this, they need to identify all the Sign assets that are currently tracked in the Signs & Markings Work Order system. They need access to a non-editable version of the [Signs | Asset Items table](https://atd.knack.com/signs-markings#work-order-signs/asset-items-signs/) in Knack. This is something that we were going to give Requesters access to while I was working with Signs & Markings.

**Desired Outcome?**
New button on Signs Work Orders Page for "Asset List" linking to a page very similar to the [Signs | Asset Items table](https://atd.knack.com/signs-markings#work-order-signs/asset-items-signs/), but without editing privileges.

**Comment by dianamartin** [comment]
- [x] Created new page "Asset List" 
- [x] Added new menu button on Signs Work Order page
![image](https://user-images.githubusercontent.com/21112975/217618054-f26ccc61-9f45-451a-b967-b19ebcedd0ed.png)
- [x] Removed "inline editing" on table
- [x] Removed "Edit asset" edit form on details page
## Before
![image](https://user-images.githubusercontent.com/21112975/217618518-0eed7346-05e9-4d72-b680-002a68dff9d3.png)

## After
![image](https://user-images.githubusercontent.com/21112975/217618403-152b0043-9593-4231-8edb-eb5d396d7ee7.png)

**Comment by dianamartin** [comment]
@ChristinaTremel ready for review
- [Signs Work Order](https://atd.knack.com/signs-markings#work-order-signs/)
- [Asset list](https://atd.knack.com/signs-markings#work-order-signs/asset-list/)

**Comment by ChristinaTremel** [comment]
Sent the link to the asset list to Rajibul on 2/8 and he confirmed the same day that he can access the list.
