### ISSUE TITLE
Configure moped's read replica RDS instance to be more forgiving when pulling `pg_dump` data

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11380]
During the course of working on the vision zero database read replica, I was more and more frequently bumping into the following error when executing long-running queries, such as one does with `pg_dump`.

```
pg_dump: error: query failed: FATAL:  terminating connection due to conflict with recovery
DETAIL:  User query might have needed to see row versions that must be removed.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
```

This appears to have been successfully resolved by setting `max_standby_archive_delay` and `max_standby_streaming_delay` both to `-1` which instructs the server to allow WAL entries to accumulate indefinitely while the long-running process accumulates.

Doing so is contradictory to maintaining a hot spare, but aligned to keeping a read replica available for long running queries that don't need to be 'up-to-the-second' accurate. 

This change is achieved by ensuring that the read replica has its own configuration in the form of a parameter group and then adjusting the above parameters.

cc @johnclary - I'm going to leave this in 'New' so you can pick where you want to slip it into the work cycle or backlog.

**Comment by johnclary** [comment]
I looked at this a few weeks ago (https://austininnovation.slack.com/archives/CNUEPKLB1/p1704737162849499?thread_ts=1704734985.094879&cid=CNUEPKLB1). both of these settings have a 900 second delay, and as far as I can tell this is working well for us now. I'm closing this!
