### ISSUE TITLE
Meeting: Discuss Migrating Records CSWZ 2/10/23

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11390]
### Meeting with stakeholders to discuss how to transition records from Smartsheet to the new KNACK app. 

- [Miro board from prep chat](https://miro.com/app/board/uXjVO0NNtEk=/)
- all records will have a mismatch to the field breakdown in Knack due to big bucket fields in Smartsheet for both Applicant info and Conflicting Party info (image below of single-field content for these in the current request form):

![image](https://user-images.githubusercontent.com/100615928/219487263-afa040ce-7add-4dc9-b0a0-b4aa595eb439.png)

**Historical records**
- options for importing: 
     - a. import into a historical version of the Knack request record with a matching historical Applicant Info and Conflicting Party info fields 
            - faster and more accurate import of content
            - separate table for searching historical records
     - b. manually break down big bucket fields (no way to parse out automatically because the data is so varied; see Miro board for example) 
            - full match of historical and new records but requires manually copy-pasting over 20,000 fields from the historical records into the new format (can be done on a spreadsheet but cannot be automated) 

**Open records (items in-flight during migration to Knack)** 
- what statuses are considered open? 
- what number of open records are we expecting? 
- options for handling open records: 
     - complete these records in Smartsheet and import them with historical records 
     - transfer to Knack during migration - this would require some downtime as the Smartsheet fields need to be manually broken out into the Knack format and uploaded

**Other**: 
- Assigned Work and Completed Work tables will be added for each reviewer
- General table of Requests to be used for assigning, visible to all (assignment currently from the Request Details page)

**Comment by KaroEngstrom** [comment]
## F 2/17/23
- @TracyLinder  and Karo met with stakeholders 

**Historical records**
- DECISION: create a historical record version of the request to allow "bucket" fields containing applicant and conflicting party information to be imported as they are, not requiring further processing of those fields 
- these historical records will be searchable in their own table and viewable on their detail pages, just as new records
- these historical records can be manually connected to a TCP case if needed by the reviewer/user 

**Open cases during the launch**
- DECISION: work in both environments simultaneously
- requests created before March 1 in Smartsheet will be worked and completed in Smartsheet per the previous process
- from March 1 onwards, new requests will be directed to Knack and worked in Knack 

**Migration and schedule** 
- DECISION: 
     - to avoid having to migrate records twice, we will proceed in two phases (see below)
     - this approach will allow the DTS team to investigate best approach to securing the attachments of historical Smartsheet records 
          - option 1 - download and upload to Knack, associate with parent request records (consult with Apps Team @dianamartin and @ChrispinP on the feasibility of this)
          - option 2 - download and archive in G: drive (some support from stakeholders for this option)
          - Note - many of the attachments are already in the ROW Portal for the associated TCP Project. The users will have the ability to connect TCP Conflict/Shared Request from its Details page to TCP Projects, and be two clicks away from the attachment content for that TCP Project (many of the attachments are the TCP Plans)

**`Phase 1`**
- website and all instructions point applicants to Knack 
- new requests are assigned and completed in Knack 
- open requests in Smartsheet are completed in Smartsheet 
![image](https://user-images.githubusercontent.com/100615928/219772905-b6b0f454-99a7-47d4-aa87-c106532322e7.png)

**`Phase 2`**
- website and all instructions point applicants to Knack 
- new requests are assigned and completed in Knack 
- all requests in Smartsheet have been completed and are now considered historical
- these historical records will be moved to Knack with the "bucket" fields intact 
![image](https://user-images.githubusercontent.com/100615928/219773945-35fad325-f639-45d8-bf33-3c572bd02ec7.png)
