### ISSUE TITLE
Manually update VZV counts By Travel Mode for Fatalities and Serious Injuries

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11391]
Companion Issue to #11340

Via Lewis L. 

> I think we have a discrepancy between our VZ totals for fatalities (118) and what is being shown on VZV right now (117).  It looks like it may be one missing in the “Pedestrian” total so I was hoping you could take a look and confirm with Xavier what fatals are included there versus what we have and see why the one isn’t showing up.  Not sure if it’s because of a scooter-related crash missing from that bucket, or if it is a CRIS v. ATD fatality total issue, or what. 

<img width="583" alt="Screen Shot 2023-02-01 at 12 26 53 PM" src="https://user-images.githubusercontent.com/5566727/216130693-4494018a-6955-4fdb-8923-aea9539650aa.png">

**Comment by xavierapostol** [comment]
Here are the numbers for the totals:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/apostolx/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/apostolx/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Mode | 2019 | 2020 | 2021 | 2022 | 2023
-- | -- | -- | -- | -- | --
Pedestrian | 119 | 82 | 112 | 136 | 8
Motorist | 408 | 346 | 402 | 384 | 35
Motorcyclist | 76 | 56 | 82 | 96 | 5
Bicyclist | 30 | 26 | 30 | 31 | 3
Other | 5 |   | 7 | 8 |  
Grand Total | 638 | 510 | 633 | 655 | 51



</body>

</html>

Here are the fatalities:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/apostolx/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/apostolx/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Mode | 2019 | 2020 | 2021 | 2022 | 2023
-- | -- | -- | -- | -- | --
Pedestrian | 34 | 34 | 42 | 48 | 3
Motorist | 37 | 48 | 55 | 48 | 2
Motorcyclist | 12 | 6 | 14 | 21 |  
Bicyclist | 4 | 4 | 3 | 1 |  
Other | 1 |   | 1 |   |  
Grand Total | 88 | 92 | 115 | 118 | 5



</body>

</html>

Here are the serious injuries:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/apostolx/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/apostolx/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Mode | 2019 | 2020 | 2021 | 2022 | 2023
-- | -- | -- | -- | -- | --
Pedestrian | 85 | 48 | 70 | 88 | 5
Motorist | 371 | 298 | 347 | 336 | 33
Motorcyclist | 64 | 50 | 68 | 75 | 5
Bicyclist | 26 | 22 | 27 | 30 | 3
Other | 4 |   | 6 | 8 |  
Grand Total | 550 | 418 | 518 | 537 | 46



</body>

</html>

**Comment by xavierapostol** [comment]
Please use this query in to get the updated information:
[Issue](https://github.com/cityofaustin/atd-data-tech/issues/11340) > By Travel Mode
