### ISSUE TITLE
Understand and remediate CRIS import failure for crashes processed on Feb 6 & 7 and potentially into the future

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11402]
While working on the enhancements to the CRIS import program for the LDM, it's observed that the CRIS import program has failed for the last two days. I think we may have accidentally let a back-fill file be processed for it, which isn't a problem at all, but more importantly, it appears to be failing due to a regex that expects a column name which may have changed. I have not triaged it beyond looking at the logs quickly in prefect. 

Because of this ETL failure, we've missed a couple of days of crashes, and I suspect we won't capture incoming data until we address this.

**Comment by xavierapostol** [comment]
Just a FYI: The latest crashes have a crash date of January 31st, 2023 and most of them have February 4th, 2023 as the earliest "Record History" on the log (some of them have "updates" that occurred on February 6th, 2023).

**Comment by patrickm02L** [comment]
@frankhereford could you spend an hour triaging this so we can get more clarity on how to proceed with resolving why the CRIS imports are failing.

**Comment by frankhereford** [comment]
@patrickm02L wrote:

> spend an hour triaging this

Sure thing. The script on `atd-data03` is newly flat-out being rejected by the primary RDS instance that backs the VZ suite. It's worth noting that the PG server is accessible (in the TCP/IP sense) to the flow on `atd-data03`, it's not a connectivity issue. The error below is a rejection, not a timeout. 

```
Failed to connect to pgsql at "db.vision-zero.austinmobility.io" (port 5432) as user "vze": Database error 28000: no pg_hba.conf entry for host "162.89.0.58", user "vze", database "atd_vz_data", no encryption
```

The script [mandates](https://github.com/cityofaustin/atd-prefect/blob/atd-data03-dockerized-agent-deployment/flows/vision-zero/cris_import/cris_import.py#L349) encryption be used on connections, `sslmode="require"`, which I believe to be the problem, as that error states no encryption.

I think the solution is going to be a combination adjusting the parameter group which configures our VZ primary instance and the encryption related resources in the docker image. Put another way - figure out how to get them talking again. 

Normally, I would be concerned more with the client in working on an issue like this, but this new breakage does align closely to the day when [I forked the parameter file](https://austininnovation.slack.com/archives/CHZE6BC6L/p1675705406186699) and changed it **for the secondary instance, not the primary**. With no way to verify this, my hunch is that when I did that, I caused AWS to reevaluate the parameter group for all instances that used it, even though it was unchanged, and they may have tightened authentication or otherwise changed something subtle about the environment since it was last worked on, which was when we brought VZ up to PG 14 along with `graphql-engine` 2+.

It's worth pointing out that this remediation will have to be done with care (and backups). The VZ primary instance is, well, production, and that's working on the car as it's going down the highway. The implication of downtime on the VZ team should be considered as well; this may be better done after hours. 

PS: That's what I think is going on. We all know that one doesn't /really/ know what's up until they actually fix it, but if I had to guess, this would be mine.

**Comment by chiaberry** [comment]
@frankhereford where can I find that error message you posted above? I was curious and looking at the flow failures and only saw this: 
```
Task 'Remove trailing carriage returns from imported data': Exception encountered during task execution!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/usr/local/lib/python3.10/dist-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/root/cris_import/./cris_import.py", line 327, in remove_trailing_carriage_returns
    util.trim_trailing_carriage_returns(pg, DB_IMPORT_SCHEMA, column)
  File "/root/cris_import/lib/sql.py", line 417, in trim_trailing_carriage_returns
    cursor.execute(sql)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/extras.py", line 236, in execute
    return super().execute(query, vars)
psycopg2.errors.UndefinedFunction: function regexp_replace(integer, unknown, unknown, unknown) does not exist
LINE 3:     set veh_color_id = regexp_replace(veh_color_id, '[\n\r]*...
                               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

which means I must be looking at the wrong spot.

**Comment by chiaberry** [comment]
thanks for the steps, so the error message that is in prefect is a red herring, the error message is a result of trying to parse the pgsql error message?

**Comment by frankhereford** [comment]
@chiaberry wrote:

> red herring

Yea, you're right on the money that the error message is the result of the script trying to execute commands on a connection that doesn't exist, and the real root of the problem is the error message that `libpg` emits and which python is trapping. I hope i'm answering your question - and please let me know if I can clarify.

I committed the edit-comment-in-place sin just a moment ago, thinking that it had only been a few seconds since I posted it, but you are super quick!

**Comment by patrickm02L** [comment]
Emphasis on after hours

> The implication of downtime on the VZ team should be considered as well; this may be better done after hours.

**Comment by mddilley** [comment]
Copy/paste of [my update in Slack](https://austininnovation.slack.com/archives/CM9MK950S/p1676073171317469)

> When doing some research on the issue with the CRIS import failures, all things about [the error that Frank uncovered](https://github.com/cityofaustin/atd-data-tech/issues/11402#issuecomment-1424416957) pointed to the DB instance parameter group that was only copied and not modified around when the import stopped working. I noticed that `vision-zero` RDS instance showed Pending reboot next to the parameter group in its Configuration tab. Kind of lines up with the theory that something changed that is managed by AWS changed so I:
>    1. Made a snapshot of vision-zero called md-before-pending-reboot-manual-reboot
>    2. Manually rebooted the instance
>
> It now shows In sync for the parameter group so we will see what happens when the flow runs tomorrow morning. :eyes:

**Comment by mddilley** [comment]
Since the reboot didn't work out, I started looking at SSL docs on Postgres RDS instances, and we seem to have everything set up just as suggested. I found a similar error documented by AWS for clients that are not using SSL.
https://aws.amazon.com/premiumsupport/knowledge-center/rds-connect-ssl-connection/

> All the non-SSL connections are rejected with the following message:
`psql: FATAL: no pg_hba.conf entry for host "host.ip", user "testuser", database "testpg", SSL off`

Looks pretty similar to the error surfaced by Frank (except for the very last part (`SSL off` vs `no encryption`):
>`Failed to connect to pgsql at "db.vision-zero.austinmobility.io" (port 5432) as user "vze": Database error 28000: no pg_hba.conf entry for host "162.89.0.58", user "vze", database "atd_vz_data", no encryption`

Going to start looking in the client direction. The docs above also show `SELECT * FROM pg_hba_file_rules;
` as the way to inspect the `pg_hba.conf`.
Also, this:
https://jdbc.postgresql.org/documentation/ssl/#configuring-the-client

Questions that I need to look into more:
- We have `SSL is required to connect to this service, but should not need a special certificate installed.` noted in the password entry for `Vision Zero Database Configuration`. Need to check if that is accurate because we do supply a .pem to connect with `psycopg2` in the import script

**Comment by mddilley** [comment]
Thanks to some help from @frankhereford, the issue came down to adding `sslmode=allow` to the connection string of `pgloader` since our RDS instance will only accept SSL connections. More details in https://github.com/cityofaustin/atd-prefect/pull/61.

**Comment by mddilley** [comment]
Frank ran through the CRIS extract request process this morning and ran the updated script to [backfill](https://github.com/cityofaustin/atd-data-tech/issues/11463). Closing this one out. 🚀
