### ISSUE TITLE
Revise VZ local dev environment script to be Ubuntu-friendly

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11424]
Extending upon #10650 so that @roseeichelmann & other Linux users can run VZ locally.

**Comment by frankhereford** [comment]
I've pushed a handful of changes up to the `ldm_development_environment` branch, and I believe this is working on the latest-n-greatest ubuntu LTS with node from the nodejs ppa and docker from docker's ppa. I've tested this on an intel ec2 instance on my personal AWS account, and then put the environment through its paces back on my mac.
