### ISSUE TITLE
ATD UKG Migration Strategy

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11421]
Participants: 
- Jennifer, Christina, Peggy, Diana
- Gilda?

**Comment by dianamartin** [comment]
# UKG Timeline
June 2021/2022?

**Feb 2022**
Survey?
- How many employees have regular access to a computer
- Exempt/Non-Exempt employees? 

Recently turned in
- How many employees using time clocks?

## 5 Different training groups
(Train the Trainer)
- Gilda
- Hannah
- Timekeeper group
- Manager and Supervisor group

** Timekeepers need to be linked in now - timekeeper expert group (MS teams)

## Time clocks 
- shared computers v. non-shared computers

## Messaging
Citywide timekeeping system
  - Clocks in/Clock out
  - non-exempt (regardless or field or desk personnel)

## Informative Meetings
- Jennifer & PWD 
  - talking to HR PARD
- HR PARDs - Jeff?
- DSD Code - Britoni

**Comment by ChristinaTremel** [comment]
**CTM is going to be training 5 groups:**

- Gilda would be timekeeper expert
- Hannah involved in train the trainer
- Executive group
- Manager/Supervisor group

Jennifer noted that she would like assistance from DTS if we have the bandwidth. Peggy noted that Christina could attend the meetings and Jennifer is determining which training groups we should join.
