### ISSUE TITLE
Create `App` Labels

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1143]
@JaceDeloney @TracyLinder @amenity what am I missing? Critical feedback needed. Is `Vision Zero Editor` better than `VZE`?

- `App: AMANDA`
- `App: AMD Data Tracker`
- `App: Signs & Markings`
- `App: Banners`
- `App: VZA`
- `App: VZE`
- `App: VZV`
- `App: Data & Performance Hub`
- `App: DTS Portal`
- `App: AMD Fulcrum`
- `App: Finance & Inventory`
- `App: RPP`
- `App: Micromobility`
- `App: Mobility Services`
- `App: ATD Forms`
- `Product: MPD`
- `Product: MPV`
- `Product: GIS`
- `Product: ROW Portal`

**Comment by amenity** [comment]
App: ATD Forms -- https://atd.knack.com/atd-forms#home/

**Comment by amenity** [comment]
Will RPP be a single app?

**Comment by johnclary** [comment]
@amenity i added an app label for Mobility Services (which includes RPP) and ATD Forms.

**Comment by amenity** [comment]
https://gist.github.com/MoOx/93c2853fee760f42d97f <-- Script to export yml file of existing labels

**Comment by JaceDeloney** [comment]
@johnclary I would prefer Vision Zero Editor. Too many acronyms flying around the City :)

**Comment by johnclary** [comment]
@amenity @JaceDeloney @TracyLinder please add product descriptions here:
https://docs.google.com/spreadsheets/d/1ExltvjPMEybkkwtnG3q-i75UIKKd1ZIwnlQzBOg3Glg/edit#gid=0

**Comment by johnclary** [comment]
ok,  the `GIS` product label doesn't make sense. geo can just continue to use their `Service` label unless working on a feature for one of our products.

**Comment by TracyLinder** [comment]
@johnclary my products are on the list & good to go

**Comment by TracyLinder** [comment]
@johnclary should we add the TDSD app?

**Comment by johnclary** [comment]
we're going w/ `Product` labels. They're here, on this new sheet:
https://docs.google.com/spreadsheets/d/1pTum5oFfDpIo575zAYDPA_bdsEfoElpCO1-HzAU68wk/edit#gid=651251559

moving this back to in progress because some labels will be created when we run the migration

**Comment by johnclary** [comment]
This was completed during the migration.
