### ISSUE TITLE
Onboard Smart Mobility to Moped

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#11438]

**Comment by amenity** [comment]
Prompted by this fire drill, @johnclary @chiaberry & I met w/ Heather B., David D., and Boniface N today. 

### Misc notes
- Opportunity to **use Moped data to generate 30/60/90 report**
    - “Next Steps” text field for projects?
- Opportunity to **support project file management,** e.g. reduce confusion on authoritative designs/docs—Boni currently has to email everyone CAD files each time they’re updated
    - Learn more about staff’s file sharing pain points
- Heather wants the a**bility to track actual spending that isn’t tied to when the invoice are paid**
    - Helpful that there isn’t a tight integration with eCAPRIS
    - Would be good to have real math / restrictions
- Boni - there’s a big need for a tool like Moped right now, need a centralized place for project information; “huge use for us”
- David “Definitely have a need to consolidate project tracking.” 10-15 concurrent projects at a time w/o dedicated funding
- Boni - Can provide historic data — 150 “Expression of Interest” projects where a company has pitched something to CoA

**Comment by johnclary** [comment]
thanks @amenity!! I added a few items to your notes.

**Comment by amenity** [comment]
#5613 came up as potentially helpful as a way for Smart Mobility to keep files with restricted access organized in Moped.
