### ISSUE TITLE
Update DTS Portal with HR New Hires - March 2023

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#11455]
Check HR new hires for previous month:
https://atd.knack.com/hr#manage-accounts/

Add all regular employees to DTS Portal as Viewer

2/13/23 - added Katie L. because we got an HR update notice/request at the Service Desk

Added 
- Jetal B. 
- Jameel H. 
- Michael L.

**Comment by chiaberry** [comment]
@KaroEngstrom the knack HR ETL is broken and hasn't updated new employees, for the last two weeks, just FYI
