### ISSUE TITLE
Map-Based Interface for Request Work Orders and Traffic Count Requests

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1146]
As a traffic engineer, I should be able to submit a work request using a map interface.

This will alleviate the need for field staff to document location data for planned work, and it will allow GIS staff to easily create/update asset data.

**Comment by amenity** [comment]
@johnclary should this be labeled both `SMB Data Tracker` and `AMD Data Tracker`?

**Comment by johnclary** [comment]
@amenity good catch. done.

**Comment by amenity** [comment]
This is being covered by #3141 ...
