### ISSUE TITLE
Backfill data into VZ database which was missed while import ETL was down

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11463]
@mddilley has proposed a solution for the SSL problems recently encountered in the CRIS import script here: https://github.com/cityofaustin/atd-prefect/pull/61. Upon acceptance of that PR into `main` and then `main` merged into `atd-data03-dockerized-agent-deployment` along with deploying the new solution, a backfill operation needs to occur to populate the VZDB with data that was not ingested. This backfill should go back at least a day or two further into the past then when we last had a successful run up to the latest day available in CRIS, generally "yesterday."

**Comment by patrickm02L** [comment]
Frank showed this during a meeting with on 2/15/23.
