### ISSUE TITLE
Unable to download CR3s 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11481]
Running the CR3 process download script today we received a message that a number of the crashes had been processed, but was unable to download pdfs for a slew of crashes. 

![Screen Shot 2023-02-15 at 8.19.34 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/f7297b30-96a4-4d4a-b016-bcc2243cd0c8) 

What's interesting about this is that the downloading program for crashes is not operational (it's being worked on #11402).

Please spend an hour to triage and investigate what might be causing crashes to appear.

**Comment by frankhereford** [comment]
I ran the script using the normal procedure we've been discussing, and it executed without any issue. CR3s are downloaded for today. Thanks!

**Comment by patrickm02L** [comment]
On 2/16/23. Synced with Frank to see why my computer was not jiving with CRIS. 

We used the Developer Tools to delete any traces of CRIS logins - deleted cookies and emptied cache.

Ran the CR3 download process again and everything worked like a charm.
