### ISSUE TITLE
BUG: Applicants are not able to pay more than $100,000 over the portal . Portal should allow for $800,000 and says it does.

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#11484]
User tried to pay a TURP Permit over or around $800,000 and was not able to. They were only able to pay $100,000. Portal Says they can pay up to $800,000. 

Stakeholders: Kim, Paloma

**This one will need to be consulted with CTM**
This has been sent to CTM to be looked at under SCTASK0288035

**Comment by Nadin-Nader** [comment]
This has been sent to CTM to be looked at under **SCTASK0288035**

**Comment by TracyLinder** [comment]
Swapna said she tested this on test and was able to pay the large invoice. We need to invoice # from ROW of the invoice that the customer couldn't pay.

**Comment by TracyLinder** [comment]
Kim sent an example, it has been sent to Swapna for review & debugging.

**Comment by Nadin-Nader** [comment]
@TracyLinder do we know if this is still the case? Should we put it in Ongoing or close?

**Comment by Nadin-Nader** [comment]
Spoke to Swapna and according to her this has been fixed to allow Portal payments to be a max of $800,000 instead of $100,000. Closing after i let ROW know

**Comment by Nadin-Nader** [comment]
Message sent to ROW:

> [11:25 AM] Nader, NadinImportant!
> $800,000 Portal Payments
>     Kampe, Kyle; Perez, Kimberly So i spoke to Swapna at CTM and she confirmed that the $100,000 dollar payments from Portal has been increased to $800,000. Please let me know if this is not the case when one comes through and we can reopen/revisit the card or create a new one.
