### ISSUE TITLE
Inventory ATD's Internal Paper-based Forms

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1148]
This project seeks to identify  and digitize ATD's internal forms and processes with the goal of eliminating the exchange/retention of paper/PDFs.

We should:
- Inventory all of the paper-based forms used by ATD for internal COA business (non-resident-facing)
- Get clarity on when digital signatures are acceptable
- Prioritize the most painful/heavily used forms for replacement.
- Evaluate whether any of CTM's various enterprise offerings meet our various digital form and document storage needs
     - ~[FormStack](https://www.formstack.com/)~ Per #3087 , Formstack is for public-facing forms.  
     - [Microsoft Forms](https://support.office.com/en-us/article/create-a-form-with-microsoft-forms-4ffb64cc-7d5d-402f-b82e-b1d49418fd9d) or [Microsoft Forms Pro](https://formspro.microsoft.com/en-us/) 
     - Sharepoint - document storage 
     - City Space - the new CoA intranet, built on [Open Cities](https://www.opencities.com/)

## Resources
- [Drive Folder](https://drive.google.com/drive/u/2/folders/1FDtMjJmdrMaF6s5xBg1LwJJX9eqELG8w)

Some preliminary work that's been done:
- Our 2018 Business Needs Assessments captured some of these painpoints
- Doron (HRD) suggested that pretty much all HR forms could be digitized
- There's a cross-dept conversation happening [in this Slack thread](https://austininnovation.slack.com/archives/C04KZA1TX/p1574293886086200)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://data.mobility.austin.gov/about/) team. Project status is documented regularly in the comments below.

**Comment by johnclary** [comment]
@TracyLinder @JaceDeloney @amenity 

After a week of admin hell, I really want to do this. I was thinking this might be a good project for Stephanie, if she has bandwidth. I'll include it in the projects I run through prioritization.

**Comment by amenity** [comment]
Once we decide which forms to move forward with, I'd like to [try out Formstack](https://github.com/cityofaustin/atd-data-tech/issues/1148).

**Comment by amenity** [comment]
Per 5/28 email from Nathan:

**Most critical needs**
- New Hire Forms/Paperwork
- PRF form we use for recruiting and compensation matters
- NEO work Linda and Diana are doing, see #2685 . 
- New telework procedure and forms 

**Less urgent**
- Leave mgmt. forms
- Compensation forms
- ER forms
- Some safety related items.

**Comment by amenity** [comment]
@johnclary - so much was digitized the past few years. It doesn't seem to me like we need this issue anymore...

**Comment by johnclary** [comment]
👍
