### ISSUE TITLE
Harden access control on VZ SFTP lightsail server

### ISSUE THREAD

**Issue by roseeichelmann** [cityofaustin/atd-data-tech#11493]
This issue is part of an [epic](https://github.com/cityofaustin/atd-data-tech/issues/11490) and seeks to address our security concerns for the server by disabling password authentication in favor of ssh keys.

Between Feb 11 10:48:02 CST and Feb 15 16:09:40 CST there have been what seem to be 8415 brute force login attempts to the server according to our security logs (which only date back to Feb 11).

![securitylog](https://user-images.githubusercontent.com/67130963/219223721-0cf952a2-1862-4021-8cf1-2140ab80a847.png)

These were failed password login attempts where attackers often use most "common" usernames and password brute forcing to get into a machine. The best measure to prevent this kind of attack is to disable passwords altogether and only use ssh keys for logging in. 

We currently log into the centos user with a shared RSA ssh key but we should migrate away from that because RSA is no longer recommended for use and instead have everyone use their own **password protected** ED25519 key. ED25519 is the most recommended public-key algorithm at the moment. Having a shared private key isn't best practice because it's sitting on many users machines w/o password protection.

The current sudo configuration allows the centos user to run as root without password authentication, meaning an attacker that gets into this user can easily become root.

I checked the logs and didn't find any successful logins from unknown IPs but it's important to note that an attacker could have easily deleted the log showing their correct authentication since no passwords were required to elevate privileges to root from the centos user.

These are the measures that will be taken in this issue:
- [x] Disable password authentication into the machine
- [x] Add a password to the centos user
- [x] Require password for use of sudo
- [x] Have users create password protected ED25519 ssh keys that I will add to the `authorized_keys` file to use for logging in instead of a shared .pem file RSA pub key (this will be much like how we currently log into `atd-data03`)
    - [x] Once users that want access get their ssh keys added I will delete the current RSA key from the `authorized_keys` file
- [x] Update dev gitbooks instructions for getting on the VZ SFTP server and generating a ED25519 SSH key
- [x] Run an upgrade on the machine

**Comment by frankhereford** [comment]
Thanks Rose. I really appreciate you battening down the hatches on this. I've created an account for myself on there following your ssh key guidelines and added myself to the `wheel` group. I'm squared away. Please let me know if there's anything I can help you with on this.
