### ISSUE TITLE
Address VZ SFTP Endpoint Security Issues

### ISSUE THREAD

**Issue by roseeichelmann** [cityofaustin/atd-data-tech#11490]
This is an epic including issues that serve to harden our VZ SFTP endpoint machine which is a lightsail server. This was originally brought to our attention due to seeing an increased number of failed login attempts to the machine and upon further inspection of the security logs I saw that there are constant and ongoing attempts to brute force password authentication into our server from various IP addresses that can be found in databases that contain reports of abusive/malicious IPs such as https://www.abuseipdb.com/. 

We decided to take immediate action by first disabling password authentication into the server in favor of ssh keys, thus removing the ability for nefarious entities to try to brute force their way in. After this initial measure we want to remove the lightsail server completely and instead host on an EC2 instance that only allows access to a range of IPs.

**Comment by johnclary** [comment]
We're not using the SFTP server anymore. We' using AWS S3! See https://github.com/cityofaustin/atd-data-tech/issues/16953
