### ISSUE TITLE
Project: DTS Branding, Identity, and Standards

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#115]
## Description
Our customers, prospective team members, and potential collaborators should understand who we are, what we do, and why it matters. We want them to know us, trust us and join us in our efforts to empower people with the data and technology they need to improve mobility in Austin.

This is a multifaceted effort, initially involving
 - Strategic direction — [Mission](https://github.com/cityofaustin/atd-data-tech/issues/139) and [values](https://github.com/cityofaustin/atd-data-tech/issues/140) statements 
 - Visual identity — Wordmark, color palette, document templates, UI design system
 - Standards — Documentation and resources that empower staff to deliver high-quality, secure, and accessible technologies. E.g. [Web Publishing Guide](https://github.com/cityofaustin/atd-data-tech/issues/114), Data Privacy Standards ... 

### Resources
- [Drive](https://drive.google.com/open?id=1VbytsDXvz5fiwWo64ZX--IzLkCUHKqT_)

**Comment by amenity** [comment]
*Status update:*
After pitching at Github's Open Source for Good volunteer event, we got a small but mighty team of Hubbers to help move this important work forward. 🙌

**Comment by amenity** [comment]
**Status update**
We've established our [mission and values](https://docs.google.com/document/d/1-8aoG1dNVj-r28d53BqhwtNZmm5YtaEEG8Cpdjl41iM/edit#heading=h.8voddqksq5vm). Next up we're looking to a redesign of our website, [data.mobility.austin.gov](https://data.mobility.austin.gov).

**Comment by johnclary** [comment]
@amenity thanks!

**Comment by amenity** [comment]
**Status update**
While we continue to discuss and fine tune our mission and values statements, we have not had much bandwidth to devote to this project in the past month.

**Comment by amenity** [comment]
**Status update**
This project continues to be back burner, though data.mobility.austin.gov might be a good project for our upcoming DTS Discovery Day.
