### ISSUE TITLE
Email weekly updates to 311 team on upgrades to meet new standards

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11505]
###  Objective
These are the weekly updates we are providing to 311 on the status of #8954 (Upgrade 311 integration to meet new standards)

### Participants

- ATD: Peggy, Diana, John, Christina, Amenity
- 311: Chandra, Patty, Patrick, Bill, Matilda

**Comment by ChristinaTremel** [comment]
# 2/6/2023

Diana emailed these updates: 

These are the updates from ATD’s side.

### Feb

- Diana: Review Control Panel Reports for SMD, check with 311 team to make sure we have field mapping set for Activity Codes - 2/6 – 2/10
     - _Will look at this item this week._
- Diana: set up Paging Activity page in Test for SMD -  2/6 – 2/10
     - This task is probably going to start on 2/8-2/15 (which follows our Sprint cycles)
- John: has sent email message to Robert, asking to coordinate (1/31/23)
     - Waiting for response from Robert to find out availability (probably delayed due to BWT last week)
 - John has requested activity names and codes for all SR types we send through integration – 2/6
     - Diana: will try to help with this.
     - Patrick: might be able to pull this together in a few days.
- Robert: Configure the ESB (next week, 2 weeks?) - 2/10/22?
- John & Robert: Testing session (1-2 weeks?) - 2/13-2/24?
     - _+1 week:  if there are any issues during testing  (Robert)_

**Comment by johnclary** [comment]
Here ya go @ChristinaTremel 
- We met with Robert F. today to review new Knack > 311 interface mappings based on 311 feedback.
- John to provide updated sample message. Robert will work on updated mappings.
- Robert out of town next week. Next meeting scheduled for 3/24.

**Comment by ChristinaTremel** [comment]
No longer sending email updates because we are now complying with the standards for sending over activities and activity outcomes.
