### ISSUE TITLE
Meeting to discuss Knack > ESB > 311

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11504]
### Attendees: 
John, Diana, Patrick, Christina, and Robert

**Comment by dianamartin** [comment]
# Diana's Notes

Participants:
Robert, Patrick, Christina, John, Diana
Patrick says:
ESB is not inserting “Review Interface Request”, it was already like that according to him
311 (Patrick) reached out to Motorola and get the XML file
Patrick is trying to get the XML file to look at it
the XML file is not going to tell us what to do so..
John Allen, might know more about the configuration piece
but he can help figure that out
Patrick can configure it on his side, but not sure what will take place with ESB and Motorola
Patrick will share the XML file once he gets it

**Comment by ChristinaTremel** [comment]
# Christina's Notes

- ESB is not inserting "Review Interface Request", but 311 hasn't configured anything on their side for this status either. 
- Patrick will reach out to Motorola to get the XML file. Not sure if it's going to tell us what we need to find out, but next step to try to determine the configuration. 
- Once we take a look at the XML file, we will meet to figure out next steps.
