### ISSUE TITLE
Meeting to Discuss ATD Project Plan for UKG Timekeeping System Implementation

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11512]
### Participants
Invited: Anthony S, Peggy, Jennifer, Gilda, Adan M, Diana, Christina

### Agenda
Ideas on how we might be able to support Admin and HR teams:

- Testing the UKG environment on the various devices that ATD uses (laptops, iPads, Samsung tablets, etc)
- Conduct research on prior UKG implementations in other Departments (best practices, tips, lessons learned)
- Conduct research with ATD Divisions on functionalities the users need in their timekeeping system (to provide technical documentation on user stories)
- Training strategies for successful user adoption of the UKG system

**Comment by dianamartin** [comment]
# Diana's Notes - 2/16
Participants:
- Anthony S., Jennifer, Gilda, Adan, Christina, Diana

## Showing UKG Implementation Plan Doc
### Potential Support Needed
- Support User Interface and Usability
- Test Environment
- Employee Training
- Get Connectivity (web based)

### Background
eTimesheets program
- `2009/2010` - did away from paper
- was a large scale effort
- first meet with division managers/supervisors, explained what was involved
- rolled out to all employees
- 2 or 3 sessions, employees didn't have a dedicated computer

## Hardware
- Talked about Hardware throughout the department
- laptops, tablets, brazos device,

**Comment by ChristinaTremel** [comment]
# Christina's Notes 2/16
- Could use support on usability testing for hardware devices
    - Parking Meters: iPads
    - Arterial Management: Signal Engineering group uses tablets, inspector tablets, maintenance team is moving from tablets -> laptops
    - Signs & Markings: iPads
    - ROW: Phones
    - Some surface Pros floating around there
    - DTS: Some Mac books
    - Parking Enforcement: Brazos
- Test environment - when Admin and HR gets into that and doing the employee training. Making sure they can get the connectivity. Thinking about the parking enforcement when they are sharing the computers.
    - When this first came up, Gilda was thinking how they rolled out eTimesheets in 2010. What they did is went to every division and met with Division Managers/Supervisors. Then rolled out to employees and did 2-3 sessions.
    - Knowing the equipment that we have and how they need to be trained based on the equipment. 
- There are so many steps and we are going to have employees spend a lot of time on the timekeeping task. 
- Scheduling is aggressive to migrate into the UKG system
    - Gilda was talking to Public Works and they are expecting to extend it, especially when PWD has 700 employees 
    - When ATD meets on the 27th, they are going to ask to extend the schedule
    - Most difficult part will be for the non-exempt employees entering the transfers
    - Gilda would like to remove some of the memo task orders from people timesheet. There are some that people find necessary. Diana feels like the people only use memo task orders because they don’t have spaces to track the work that they are doing so they rely on memo task order numbers. .
        - At one point they had a task order for entering timesheets. 
- Interviews with the Divisions
    - In 2010, Gilda met with Division Managers and Supervisors to talk about their timesheets. 
    - Diana exported list of TKs to determine which memo TKs we can keep and which ones we can get rid of
    - Invite timekeepers that support that division
- Interviews with Departments to capture their lessons learned and tips
    - Gilda said we might be able to get some good information out of Code and Fleet! Fleet has a solid HR and Code has flipped around. 
    - Jennifer thinks meetings with us and an HR manager in these groups could be beneficial.
    - PARD and Convention center are still going through it.
- We have worked with CTM on implementations in the past. They would like us to share some of our lessons learned from working with CTM in the past.
    - Supervisor training is scheduled for Monday, February 27th
    - Training with employees is in April
    - Need Executive and Division Manager support
- Gilda is concerned with not being able to approve timesheets every week, time will only be updated every 2 weeks. 
    - The departments left are the departments with the biggest impact because we have field employees.
- Time-clock issues
    - Timesheets can’t be approved until the employee is clocked out. Deadline is Friday at noon and people are working until the afternoon/evenings on Friday.
- ATD only have one leave management person
- Doing a check in after the Thursday meetings could be really useful.
    - Assign Christina the train the trainer role 
        - We will need to create our own training manual or demo video about getting people on boarded into the system
        - Hannah and Christina can coordinate on technical documentation for the training

### Recap of DTS Support

- Usability testing for hardware devices
- Testing UKG environment
- Interviews with the Divisions
- Interviews with Departments to capture their lessons learned and tips (Jennifer will start those conversations)
- Share lessons learned from working with CTM in the past
- Setting up check in after the Thursday meetings with ATD group
- Christina attend train the trainer meetings and work with Hannah on technical documentation for training
