### ISSUE TITLE
[TDS-TIA] Bug: Mitigation Recommendations

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11519]
### When adding a new recommendation the system inserts it into the historical mitigation table. 
- Customer is Ella R.

![image](https://user-images.githubusercontent.com/49930868/219496310-a0eed740-7466-4b2e-af38-926cdff9f73f.png)

**Comment by TracyLinder** [comment]
@ChrispinP let me know if you have any questions. This is ready for debugging.

**Comment by ChrispinP** [comment]
The Mitigation Construction and Mitigation Recommended tables were hidden if record count was 0. I've removed these page rules so they show & there is no confusion when historical records exist. Updated Mitigation Recommendation buttons to the correct Mitigation Type being created, was still set to Mitigation Fee in Lieu.

This should now be fixed

**Comment by ChrispinP** [comment]
notified Ella of the fix, pending closure
