### ISSUE TITLE
Bug: "Belongs To" Button From V6 is no longer in V7 (Granicus)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#11522]
**Bug: "Belongs To" Button From V6 is no longer in V7 and this is needed as account bills sometimes get mixed**
Stakeholders: Kim P., Paloma A.

> **Update Oct 2024:** ROW found a screenshot of the feature in A6. A new CTM-SN was submitted.

For more Context, the Belongs to button was one of the options in the People tab of Amanda 6. The function of this button, according to the AMANDA Manual is "Displays all People records of which this record is a member. (This record displays in the Member tab of those records)."

It looks like this option may be available in AMANDA 7 as well, but ROW team is not able to see it. Potentially a permissions issue. 

Cause: Sunstar bills were showing in AMLIs account and Joer 's bills was showing on SunStar
Example accounts: AMLI, SunStar
Example folder: 2023 002954 GF, 2022 113419 EX

**Comment by Nadin-Nader** [comment]
@vschandramouli this will need to be scoped before going to CTM

**Comment by vschandramouli** [comment]
@Nadin-Nader Updated the card with some details. This may be a permissions issue. Please let me know how to action this further.

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please speak with Jenice about this next week?

**Comment by Nadin-Nader** [comment]
Appointment Scheduled with Jenice for Monday 7/17/23 @1030 am

**Comment by Nadin-Nader** [comment]
Spoke to Jenice and found that we need more examples of where this is happening before she can troubleshoot

**Comment by Nadin-Nader** [comment]
Putting in OnGoing pipeline as Kim is waiting on more examples and looking for an old training image of this

**Comment by TracyLinder** [comment]
### Prioritization Oct 2024
- We need a solution to pull a people record and see everywhere this record is added as a 'member'
- Be sure to build this into the ECM

**Comment by KyleErich** [comment]
<img width="580" alt="Belongs To" src="https://github.com/user-attachments/assets/8f3c01e7-785a-4479-ac5f-d6d5aaddab6e">

I found a screenshot from AMANDA 6 that contains an image of the Belongs To icon.

**Comment by TracyLinder** [comment]
### CTM-SN Submitted INC0441363

![image](https://github.com/user-attachments/assets/146c6f8b-8ad7-47a9-83d5-f172891b7810)

**Comment by TracyLinder** [comment]
### Update

Kyle & I met with CTM-AMANDA today to discuss this need. They now understand what we're asking for. Jenice said she's going to research to determine if the feature is in A7 and we can't find it, and she'll also discuss it with the vendor.

**Comment by TracyLinder** [comment]
### Update & Closing

Jenice with CTM-AMANDA turned the 'Belongs To' feature on in PROD. 

![image](https://github.com/user-attachments/assets/9deae412-34a6-4be8-853a-e94c4a44b056)
