### ISSUE TITLE
BUG: Update Batch Permit Expiration Notification to Include PSM and subject line update (LP) (On PROD )

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#11523]
### The batch notification job of upcoming permit expiration needs to include PSM folders. Also the subject line should be updated from "RW" to "ROW". 
- Batch job goes out every day. 
- We're not sure if the EX was meant to be a different email or if it was meant to be on the same report. Either way they need the data daily just as they are getting for RW. 

Stakeholders: Paloma A.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in Progress

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan 
Hi ok so I don’t have access to view these on PROD. I asked George and this is what he found:

[2:37 PM] Shirai, George
Batch job 50 is "Send Permit Expiry Email", and it's NOT active in PROD right now
Batch job 72 is "Send Permit Expiry Email" also... this one IS active in PROD
This one last ran yesterday around 7pm. No errors recently
Batch job 143 is "RW Expired Permit", this is active in PROD
Last ran this morning around 12:30 with no recent errors

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder - 
Analysis Findings
1.	Batch Job ’34 – Permit Lapsed and about to expire/PLATE‘ – Report weekly runs on Sunday (report query pulls only RW foldertype) and Job is Active in PROD 
2.	Batch Job ‘50 – Send Permit Expiry email’ - Before Procedure - “PermitExpiry_Notification”  and in Procedure its calling COA_BATCH_PROCESS.f_permit_expiry_email package function and Job is not Active in PROD
3.	Batch Job ‘72 – Send Permit Expiry email’ - Before Procedure - “PermitExpiry_Notification”  and in Procedure its calling COA_BATCH_PROCESS.f_permit_expiry_email package function and Job is Active in PROD (also pulls both RW & EX)
4.	Batch Job ‘143 – RW Expired Permit’ – After Procedure – “RW Expired Permit”  and procedure has both RW & EX foldertype  and Job is Active in PROD

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per Paloma, this email getting generated for both RW and EX as well. So this card can be closed. 

Sample email:

**Comment by Nadin-Nader** [comment]
This is working and providing EX and RW. CLOSING

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan can you check to see if this job is running in Dev or Test? if yes, please disable it. 
Batch is either 72 or 143.

**Comment by TracyLinder** [comment]
**Q: Is ROW still getting this report emailed from dev or test?** 
**A:** Last email was 5/29 & forwarded to Sree. Paloma will have to ask Candice if this has happened since 5/29.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Job #266 from DEV was active, which is turned off now. Job#143 from TEST was not active; however these two jobs are generating the email attached using procedure DEFAULTREPORT_RW_EXPIREDPERMIT. Let's observe for next time if we receive the same email, then need to do further research on this.

**Comment by TracyLinder** [comment]
Sree asked during today's Friday meeting if Paloma or her team is still getting this email. P-lo isn't in the meeting today, we'll need to check again next Friday.

**Comment by TracyLinder** [comment]
### Update

- This email was sent to rightofway@austintexas.gov today at 5am. Paloma will forward the email to us. I'm going to reopen this.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please troubleshoot when you return. Thank you.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan when you get a chance can you give me an update on this one

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Did some more research and again set Active flag No for DEV job id's 39 & 25. Let us observe for our next DEV/TEST Email.

**Comment by TracyLinder** [comment]
The ROW email account received this email today. This is not fixed. FYI @Sreelatha-BlazeKannan 

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/b248b521-0c19-4aa3-90e6-907106e578a9)

**Comment by KyleErich** [comment]
Retitled this card to account for the current AC. We need the EX and PSM folders to send off the notification email, and to do this at the same interval as for the RW folder (10 business days out or any day sooner than that).

I tested this again yesterday on a RW folder an a EX folder, and received a notification email for the expiring RW, but not for the expiring EX.

**Comment by TracyLinder** [comment]
### Batch Job Analysis Notes

Analysis Findings
1.	Batch Job ’34 – Permit Lapsed and about to expire/PLATE‘ – Report weekly runs on Sunday (report query pulls only RW foldertype) and Job is **Active** in PROD 
2.	Batch Job ‘50 – Send Permit Expiry email’ - Before Procedure - “PermitExpiry_Notification”  and in Procedure its calling COA_BATCH_PROCESS.f_permit_expiry_email package function and Job is **not Active** in PROD
3.	Batch Job ‘72 – Send Permit Expiry email’ - Before Procedure - “PermitExpiry_Notification”  and in Procedure its calling COA_BATCH_PROCESS.f_permit_expiry_email package function and Job is **Active** in PROD (also pulls both RW & EX)
4.	Batch Job ‘143 – RW Expired Permit’ – After Procedure – “RW Expired Permit”  and procedure has both RW & EX foldertype  and Job is **Active** in PROD

**Comment by TracyLinder** [comment]
### Conversation With ROW

- Today in PROD this notification doesn't include EX and PSM as it should. 
    - The current AC in the description is accurate. (Screenshot below) 
- Emails coming from DEV/TEST don't seem to be an issue for this card. 


![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/9fc02eb3-f5c4-470f-8347-e0f2dd25b044)

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please find out if EX & PSM notifications were ever deployed please? If yes, this card is a bug. If no, we need to build it.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader I verified the batch procedure , As per the coding email has been sent to RW and Ex folders .
I would like to confirm whether it is working for RW and EX or just RW. 
It would be helpful if i could get a screenshot of the email

**Comment by TracyLinder** [comment]
### Conversation with ROW
- The current batch job does include EX, but the email subject line is confusing.

**Comment by TracyLinder** [comment]
@Lpriya-LIT can you please provide an update?

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder 
Fixed the devOps issue and committed the changes. Created Dev deployment request , SCTASK0403552

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified on Dev, Looks good.
Created Test deployment request , SCTASK0404992

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Test , Ready for UAT

**Comment by Lpriya-LIT** [comment]
@KyleErich @Nadin-Nader The job was not active on Test , I have updated to Active and ran it today. 
Please check whether you received the email.

**Comment by Lpriya-LIT** [comment]
<img width="724" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk1xQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6716cc3af9dfc07941295a90d6f4a10165d84679/image.png" alt="image.png" />

**Comment by KyleErich** [comment]
@Nadin-Nader @Lpriya-LIT Unfortunately it still seems like I haven't received an email, so I'll have to reject UAT on Test. I set 2021-066745 PSM (FolderRSN 12691229) to expire on Apr. 16, so that I would cross the 9 business day timeframe for the email to generate, but this never happened. Applicant people record 5811726.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader I created a test record on Test for PSM folder (13206126) to test the batch email .
Please check with ROW team to check whether they received a email today at 9 am  (email id - rightofway@austintexas.gov)

**Comment by KyleErich** [comment]
@Nadin-Nader @Lpriya-LIT There were no attachments present on the email received at 9am on May 1.

**Comment by TracyLinder** [comment]
### UAT Bug ❌

- Email sent has no attachment. It should attach with a list of the permits. FYI @Lpriya-LIT 
- Paloma is forwarding an email from the past where the attachment worked correctly to help Priya troubleshoot.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT can you update this card or let me know what the status of this is please

**Comment by Lpriya-LIT** [comment]
Update - Paloma con firmed that there wont be any attachments but the email will have list of folders but the email they received on the test record doesnt includee the list of folders . Checking to find the issue

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Done a commit and requested for Dev and Test promotion, SCTASK0441614

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader On last Friday's call ,Kim and kyle confirmed that the Subject line has ben updated and the list of folders were included in the email that was sent to the ROW email id. Done a commit to add PSM to the list . Changes deployed to Test . Ready for UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created prod deployment request , SCTASK0446737

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Ready for UAT on Prod

**Comment by KyleErich** [comment]
@Nadin-Nader @Lpriya-LIT Approving UAT on Prod, thanks.

**Comment by Nadin-Nader** [comment]
Approved, Closing
