### ISSUE TITLE
BUG: Permit Lapsed and About to Expire (PLATE) Report is not populating any information (SR) (Follow Up on PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#11524]
BUG: Permit Lapsed and About to Expire (PLATE) Report (56106) is not populating any information. 
- The attachment has no data on it. 

Stakeholder: Paloma A.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Batch Job ’34 – Permit Lapsed and about to expire/PLATE‘ – Report weekly runs on Sunday (report query pulls only RW foldertype) and Job is Active in PROD. However it is generating empty report as per Paloma. PFA

[Report (3).pdf](https://github.com/cityofaustin/atd-data-tech/files/11005152/Report.3.pdf)

**Comment by Nadin-Nader** [comment]
**Update:** Analyzing in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - There is an issue in query according to my analysis; updated the query and sent the results in an excel for business users to verify; upon verification query can be updated in Report.

**Comment by Nadin-Nader** [comment]
Update: @Sreelatha-BlazeKannan  Per our Friday meeting, Please add EX folder Types and have RW and EX data separate

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV, please UAT

**Comment by TracyLinder** [comment]
@Nadin-Nader ROW wants confirmation that the EX folders will be included on this report. Also, who will be assigned to this during Sree's absence?

**Comment by Nadin-Nader** [comment]
Reached out to Kyle and ROW asking for them to UAT this on TEST. Waiting on Response

**Comment by Nadin-Nader** [comment]
Updating Query for report in Crystal.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - 56106 PLATE Report sample format sent. Kindly review the report layout so, that we can promote to DEV. I have updated the query to have both RW and EX. Since Crystal report issues still persists, I am sending in Pdf format; once all looks good, I can send the DEV DP.

**Comment by TracyLinder** [comment]
### Stakeholder Review Notes 5/19

Update:
- Exclude RW-Street Event
- Add a second grouping for folder subtype

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have uploaded the new copy of the report to the DEV and TEST path. Please UAT and let me know if it is working or not.

**Comment by TracyLinder** [comment]
### Convo w/ ROW during Friday review 6/9

- Sree is working with CTM to resolve issues

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan meeting invite sent to Jenice for 2pm on 6/14/23 at 2pm

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Had a call with Jenice and removed next fire time and last fire time column values and ran the job once which resolved the issue of firing multiple times without stopping issue. Now I will be submitting the PROD DP for the same. thank you for your patience.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder - PROD DP submitted. Kindly approve and create task id for the same.

Note: Please post the report in PROD Report path for the job#34 and this is a manual commit.

**Comment by Nadin-Nader** [comment]
This has been sent to the AMANDA Support team to be deployed to PROD under **SCTASK0325874**

**Comment by TracyLinder** [comment]
This job will run on Sunday; we can verify next Friday that the batch email job is working. 
The report in the menu looks good.

**Comment by Nadin-Nader** [comment]
Sent message to Kyle to see if this is good to close or not

**Comment by TracyLinder** [comment]
### Friday Review Notes 6/30 UAT FAILED ❌
- Paloma said they got the email this past 2 Sundays.
- There is no data in the report
- Kyle thinks it might have something to do with the 'AS-OF' field not being populated. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/41ac3af9-80d4-4faa-b68d-adcc31d8f0a5)

**Comment by TracyLinder** [comment]
Sree is working with Swapna on a fix to do with report names.

**Comment by KyleErich** [comment]
@Sreelatha-BlazeKannan @Nadin-Nader I've confirmed that we received this emailed report and it is correctly populating with data. UAT approved.

**Comment by Nadin-Nader** [comment]
Approved. Closing
