### ISSUE TITLE
Sprint Review 2/21/23 - Traffic Register (Topic: Reg Text formula)

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11533]
### Objective 
Sprint Review for Traffic Register Product & Project

### Attendance
Christina, Dipti, Anthony, Justin, Ed, Ravi, Susanne, Diana, Chrispin, Steven, Ryan

### Slide Deck
[Traffic Register - Sprint Review: 2/21/23](https://docs.google.com/presentation/d/1q4woBQmO6ZsDMhgGtQEW6aFglQ5xVduaQ0RyIeS0WMw/edit#slide=id.g1ebb8a7ebd_0_60)

### Agenda
**Today**
- Working session - build regulation text automation formula
- Feedback & Discussion

**Next Steps**
- Next sprint review we will walk through Regulation review process - start with drafting reg, sending reg for review to Dipti, then sending reg for review to Eric.
- Proposed additional meetings - shadow Area Engineers to document review processes

------
- [x] Schedule meeting
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes
Participants: 
- Diana, Anthony A. , Ed,, Dipti, Ravid, Justin, Susanne, Chrispin, Steven, Ryan R., Christina, 

## Feedback
### Don't need a back and forth process
- User expressed question on back and forth
- Author, Engineer, Author
_99 times out of 100, by the time they've written a reg_
- missed a comma, misspelling

Negotiate back and forth and then write the Reg
- Work all of that out first
- Just need a reg number
- Missing a content

### Requires Too Much Time 
- Josh, type would bay park
- Finished the reg, within 5 minutes
- Site Plan Reviews
- Lots of other work need to be done
- Want to feel efficient, want to be easier

**Comment by ChristinaTremel** [comment]
# Christina's Notes

### Feedback

On the user side, theres some concern about going back and forth between the engineer and the person writing the reg. The back and forth typically happens before the reg is written 

- Typically they have already discussed before it comes to the Area Engineer.
- Nickname doesn’t sense to them, they just need a Reg ID

Dipti also agrees:

- Had a CAF, the reg was written within 5 minutes, put in the measurements and within talking it’s complete
- The back and forth takes a long time
- In TDS, she also has to do reviews
- Would like to do the back and forth outside of the system and just use Knack for submitting the final Reg.

Justin Good:

- I also really like the idea of standardizing the language. as someone relatively new to the traffic regulations, i often miss small formatting things that Eric catches and changes. some primary ones are standardizing street names, how to refer to some of the updates (all-way stop vs multi-way stop), etc.

Seems like everyone is moving through emails, but Diana was thinking that Eric was wanting the history of these communications. Just had a thought that emails could be coordinated through the Traffic Reg system. Diana would defer to Eric.

- Christina should follow up with Eric on what tracking he’s concerned with in the Traffic Register app. 

### Other Notes
Check in with Joana on new template of the golden rod that was given to Ed.
- Did she mean to send this to Ed.

### Follow Up
- Schedule meetings with Area Engineers to shadow the reg review process
- Go through other reg types and clean up the form from what we think. Will review with team in next Sprint Review.
- Look at Traffic Register app and identify how to clean up/simplify the dataset.

**Comment by ChristinaTremel** [comment]
# Action Items

- [ ] Schedule meeting with Eric and Area Engineers to discuss the review process for Traffic Regs and determine how we want to move forward with reviews
   - Meeting scheduled for 2/27 at 1pm

- [ ] Go through other reg types and clean up the form from what we think. Will review with team in next Sprint Review
   - #8738 

- [ ] Look at Traffic Register app and identify how to clean up/simplify the dataset.
   - Christina, Diana, and Chrispin met to discuss how to improve efficiencies in the Traffic Register app and documented proposed changes on a [Miro board](https://miro.com/app/board/uXjVPkou-d4=/). Created separate issues for the changes we're going to make.
