### ISSUE TITLE
Create Viewer for Lane Conversion Data with Enhanced Filtering

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#11546]
Mary V. asked for a viewer with additional filtering capabilities to visualize the lane conversion data. 

The VZ team will review the map and let us know if there are any further changes.

**Comment by patrickm02L** [comment]
[Link to the map](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=18463354786b4492b9dd035331cd1fec)

**Comment by andrewshensky** [comment]
This has been completed
