### ISSUE TITLE
Improve efficiency of Draft Builder  - remove nickname, hide empty fields, update menu

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11549]
To make the Draft Builder more efficient for the users, make the following changes (per our conversation during the "Traffic Register - Improved Efficiency" discussion)

---

**To-Do**
- [x] Remove nickname
- [x] Enable "Hide empty field" on all tables in Draft Builder
- [x] Create new menu (secondary), for + Attachments, + Comments

**Comment by ChrispinP** [comment]
Action items complete, separate menu for comments & attachments created with tables just below.
![image.png](https://images.zenhubusercontent.com/5f036c8940760b58210af838/01498b6e-e4f9-4572-9a03-86d0b21806e2)

**Comment by ChrispinP** [comment]
We showed the updated Draft Builder during our most recent Traffic Register sprint review. No objections.

Closing as complete.
