### ISSUE TITLE
Test VZA App 1.0

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#1154]

**Comment by SurbhiBakshi** [comment]
Location 

- [ ] Add a new street segment location
- [ ] Add a new school location
- [ ] Add a new intersection location
- [ ] Search for an existing location

Add a new location as a scheduler, email should be sent to the GIS group within DTS.
GIS group will match the new location requested to an existing Data Tracker location from the signals or school beacons data set.  GIS person will be able to match the location by either typing in the signal/ school beacon location or referencing it on a mapAn email will be sent to the scheduler when this process is completed.

**Comment by SurbhiBakshi** [comment]
Officer 
 
How will the officer get a link to register for an account in the app?

Test - 
- [ ] Register as a new officer
- [ ] Look at My Assignment Calendar and table
- [ ] Start an assignment (should see a message in the browser window the assignment has started ).
- [ ] End an assignment (should see a message in the browser window that the assignment has ended).

**Comment by SurbhiBakshi** [comment]
Viewer 

- [ ] Be able to see Viewer table with assignment time, location and assigned officers
- [ ] Officer modal with required officer information

**Comment by SurbhiBakshi** [comment]
Scheduler 

- [ ] View Assignments Calendar with assignment details module, able to get to edit assignment from there? Assignment calendar is also visible to Assigner and Viewer
- [ ] Create new assignments
- [ ] View Assignment table and edit assignments
- [ ] View Locations page
- [ ] able to add new location requests (what should the turnaround be for matching new location request to Data Tracker locations?)
- [ ] able to view Reports

**Comment by SurbhiBakshi** [comment]
Assigner 

- [ ] Able to view Assignment Calendar
- [ ] Able to assign officers to assignments
- [ ] Able to edit officer assignments

**Comment by SurbhiBakshi** [comment]
GIS staff

What if a requested location does not have a match in Data Tracker?

- [ ] Able to view Locations page
- [ ] Able to get to edit Locations pages 
- [ ] Able to work with map and locations to match requested location to Data Tracker locations

**Comment by SurbhiBakshi** [comment]
@dianamartin , @amenity Here is the sequence for the testing - 
 Here is the  link to self register https://atd.knack.com/vza#officers/



Sign up as officer with personal email
Then sign in as scheduler
Create assignments
Notify assignents
Sign out
Sign in as assigner
Assign officers -yourself
Sign out
Check email
Sign in as viewer
Sign in as officer
Start assignment
End assignment (edited)

**Comment by SurbhiBakshi** [comment]
The officer self registration page takes some time to process (35 seconds)

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/da89b9fa-d57a-4e78-ae67-64c93ee8f0a5)

**Comment by dianamartin** [comment]
### Location

**Comment by amenity** [comment]
Looks sooooo dang good, @SurbhiBakshi ! 🏆  

I collected refinements [here](https://github.com/cityofaustin/atd-data-tech/issues/1201), and we can add/change to those after Sprint Review. 

Questions:
- Why is there a Council District 1 and a Council District in the `street_segments` object?
- How can the Scheduler delete an assignment?
