### ISSUE TITLE
Improve efficiency of the "My Task Board" page - remove My Contributions and Team Tasks / reorganize My Tasks 

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11556]
"My Task Board" page

- Navigate directly to "My Tasks" page (will determine changes once we have a conversation with Eric/area engineers)
   - My Regulation Documents | Draft
   - My Regulation Documents | Approved
   - Waiting for Review (Eric & Lead Eng)
   - Previously Reviewed (Eric & Lead Eng)

- [x] Remove "My Contributions" page
- [x] Remove "Team Tasks" page

**Comment by ChristinaTremel** [comment]
@ChristinaTremel will add notes from 4/5 discussion on review cycles.

**Comment by ChrispinP** [comment]
Forgot to update this issue. Updates to the Task Board were done prior to the Traffic Register Sprint Review last week. 

Pending any further changes

**Comment by ChristinaTremel** [comment]
Reviewed with users during last Sprint Review. Will create new issues if they have additional feedback moving forward.
