### ISSUE TITLE
Synchronize User Accounts Between Data Tracker and Finance System

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1156]
We need to keep user accounts in sync between the Finance System and Data Tracker so that inventory records can be populated with the created/modified by account fields across systems.

This requires keeping the Knack record ID of the user account stored in both systems so that records can connection fields can be translated/populated correctly. We can use the atd-knack-api to accomplish this.

**Comment by amenity** [comment]
This came up during user testing.

**Comment by johnclary** [comment]
Good news—we don't need to do this anymore. Inventory lives in Data Tracker
