### ISSUE TITLE
Bug - Duplicate ATD Value in Project Sponsor Info (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11571]
### 'ATD Austin Transportation (ATD)' shows twice in the info Project Sponsor. It should only show once. 

![image](https://user-images.githubusercontent.com/49930868/221291240-8da0813d-55f3-4fbe-9af9-334600ddc5f0.png)

**Comment by TracyLinder** [comment]
@Nadin-Nader I put this on deck to be debugged. After the analysis I can update the AC and put it in the backlog or on deck.

**Comment by Nadin-Nader** [comment]
Update:

Priya is Working on a commit to fix the Multi-pick data.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader  - Updated the Pick options it is changed in Amanda backoffice but it is not reflecting in Portal. Will discuss with CTM portal team and proceed further

**Comment by Nadin-Nader** [comment]
**Update:** Still waiting on CTM to deploy

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/337a17af-5251-496f-8d4a-8b20b0a62ee2)

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This was UATd by Kyle on TEST and he approved this to go to PROD

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes are deployed to Prod , ready for UAT
