### ISSUE TITLE
Configure Finance Review for New Transaction-Based Workflow

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1158]
Finance review workflow needs to be reimplemented to flow with the transaction-based request process. Task orders have been integrated. So this needs to be spec'd and implemented

**Comment by dianamartin** [comment]
- Configured `Review Needed` conditional rules status in `Request Status` field.
- Added conditional rules to `FDU REVIEW REQUIRED` field
- Configured `Edit Inventory Request` button/form to include record rules that changed FDU REVIEW COMPLETE to 1.

**Comment by johnclary** [comment]
Thanks @dianamartin kicking this back to Review/QA until I take a look.

**Comment by johnclary** [comment]
Looks great! Closing.
