### ISSUE TITLE
Advanced Search - UI  Improvements

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11580]
# Improvements from usability feedback
### Regulations Document
- [x] Regulations Document page, show (default view: filtered table)
![image](https://user-images.githubusercontent.com/21112975/221684372-32b8552d-748c-4403-9628-e577e347a8b8.png)
- [x] Rename Page Title from: "Regulation Documents: Filtered Search" to `Approved Regulation Documents`
- [x] + Add Search Regulations & Documents menu button - that goes to Power Search page 
- [x] Rename "Power Search" button to `Advanced Search`

### Approved Regulations (default view: filtered table)
![image](https://user-images.githubusercontent.com/21112975/221684285-cf5d3b6a-cf33-4bf8-95cf-f77c563d05c5.png)
- [x] Rename Page Title from: "Approved Regulations: Filtered Search" to `Approved Regulations`
- [x] + Add Search Regulations & Documents menu button - that goes to Power Search page 
- [x] Rename "Power Search" button to `Advanced Search`

## + Add Advanced Search Regulations & Documents menu button
- New Search page (combine both Regulation Documents/Approved Regulations)
- A Toggle menu like this
![image](https://user-images.githubusercontent.com/21112975/221685672-7147c8c7-fd4c-4cf4-9a84-352a63728e2a.png)
- Add New Search page to "Home" page
![image](https://user-images.githubusercontent.com/21112975/221685138-e6ab4672-2ae6-411f-8bee-a7db7021edf4.png)

**Comment by ChrispinP** [comment]
The Home page, Search pages, and Search results have been updated in Prod.

Pending review

**Comment by ChrispinP** [comment]
We reviewed the new Prod environment with stakeholders during our most recent Traffic Register sprint review. No further action needed.

Closing
