### ISSUE TITLE
Establish a regular purge of Moped test deployments and/or one-time clean them up

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11594]
Tilly contacted me last night, and one of the things we discussed was a [failure on deployment](https://cloud.prefect.io/dts/flow-run/31e39d29-19bc-4743-9bf0-f1c7401d427f) of a Moped test instance. During the creation of the EC2 load balancer, the following is reported:

```
Error during execution of task: InvalidSubnetException('An error occurred (InvalidSubnet) 
when calling the CreateLoadBalancer operation: Not enough IP space available in 
subnet-[snip]. ELB requires at least 8 free IP addresses in each subnet.')
```

This is an indication that we have too many stale deployments, and have filled up the subnet's range of IPs. I recommend we establish a regular purge of these with assignments to do that work, or at least, use this ticket to assign out the task of cleaning them up  now so we can deploy new ones.

**Comment by chiaberry** [comment]
https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/dev-guides/moped-test-system/manual-resource-teardown

**Comment by chiaberry** [comment]
@frankhereford  to do a cleanup this sprint, then we will do a skill share so all devs can see where the resources are
@chiaberry to add cleanup reminder to moped release issue
