### ISSUE TITLE
[Reporting] Ability to Report on Purchase Request Items by Payment Type

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1160]
Finance staff need a report of items purchased, by purchase type (DO/CT/PO). See the "CT DO PO-Purchases" tab on the attached example from Van. 

[https://app.zenhub.com/files/140626918/979ce503-51b4-4536-90e5-2c0bdf86de67/download](https://app.zenhub.com/files/140626918/979ce503-51b4-4536-90e5-2c0bdf86de67/download)

**Comment by dianamartin** [comment]
Am trying to replicate reports, but not sure which variety of records would be the best for Van. I will try al the alternative options so she can see the options available to her. It's difficult bc not all the data is related.

**Comment by johnclary** [comment]
Moved to sprint 17 and added a blocker to meet w/ Finance team for clarification.

**Comment by dianamartin** [comment]
There is already an Inventory Report that has a page for `Payment by Type`
