### ISSUE TITLE
[Bug] Edit component attributes form briefly shows previous values on save

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#11612]
When a user edits a component's attributes, the previous values flash for a moment in the form before the modal exits. This has to do with where the initial form values come from in state and also how the initial values are set with React Hook Form.

This also ties into a bug described in https://github.com/cityofaustin/atd-moped/pull/984 where the completion date can't be successfully cleared programatically when the component phase is cleared in the form. The completion date does clear out in the `onSave` handler when there is no phase saved in the form.

**Comment by johnclary** [comment]
As discussed in grooming yesterday, we should upgrade to RHF (https://github.com/cityofaustin/atd-data-tech/issues/12518) v7 while we're at it.

**Comment by mddilley** [comment]
I'm going to split this into two PR: one for the RHF upgrade and a second for the refactor. Hoping that focusing on the library first will reveal better ways to handle the tricky parts of the form (async option loading, field resets, etc.)

I've been keeping track of the refactor with this diagram https://excalidraw.com/#json=-ZjAaHB9yLoPRuDvHfOv5,PplQqUkZ1LYXDP2aCnV9LA

**Components that use RHF**
- `ProfileDetails`
- `ComponentForm`
- `StaffForm`

**Comment by johnclary** [comment]
@mddilley this sounds like a great plan! i'm happy to pair / rubber duck, lmk anytime :)
