### ISSUE TITLE
Create working copy of LDM database on RDS and grant Xavier A. write access

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11616]
As part of the refinement of the VZDB's upgrade to the LDM model, Frank H. and Xavier A. will have iterative conversations about the form and functionality of the database. Frank will publish his latest work NLT March 8th on an isolated RDS instance and share access to that with Xavier. 

This ticket intends to track the progress of that work, and possibly become an epic to capture follow-on tasks which are generated from those conversations.

**Comment by frankhereford** [comment]
I don't recall why I turned this into an epic - it shouldn't have been in retrospect. This task is complete.

**Comment by patrickm02L** [comment]
Turned this back into an Issue.
