### ISSUE TITLE
GEO: Rainey District Segment Pull

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11617]
### ATD-AMANDA needs all street segments inside of the Rainey Street District
- For issue #11610 
- Boundaries shown below

<img width="469" alt="Screenshot 2023-03-02 at 11 31 33 AM" src="https://user-images.githubusercontent.com/49930868/222506722-f49b7d74-d947-4866-ae17-256b24378fe4.png">

----

**The current segments we have for this district were generated a few years ago, below:**

2041228,3691032,2019182,3691034,2019189,2019214,2019235,2014215,2019250,2033286,2019249,2019354,2019466,2019482,2041292,2019481,2019426,2019444,2019341,2019355,2019370,2033292,2041207,2019208

**Comment by andrewshensky** [comment]
The Segment IDs below are representative of the segments shown in the included screenshot.
2019481, 2019369, 2019466, 2019550, 2019370, 2019444, 2043970, 2019381, 2045019, 2019181, 2033292, 2019623, 2019319, 2019377, 2043966, 2033311, 2019182, 2019504, 2019152, 2019250, 2041292, 2019355, 2019647, 2043968, 2041215, 2019189, 5749778, 2019341, 2019612, 2019235, 2019221, 2019443, 2019482, 2019208, 2019214, 2045020, 2019222, 2019487, 2041228, 3691032, 3691034, 5749780, 2019249, 2019426, 2019376, 2041207, 2019259, 2033286, 2019354

![image](https://user-images.githubusercontent.com/80716478/222520522-8df60388-4892-4db2-adcf-a970c7be9e7f.png)

**Comment by TracyLinder** [comment]
@andrewshensky thank you so much!
