### ISSUE TITLE
[Spike] Investigate the geocoder used to locate crashes in the VZ suite

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11628]
Little institutional knowledge remains about how geocoding is done for the crashes we receive from CRIS. 

I believe the process is happening upstream of us at CRIS, but it's been my experience that there is often a lot of room for improvement in the accuracy of this process. In particular, crashes which happen on higher level roads that are identified by a number instead of a name are particularly difficult, as these numbers are not stored in the same fields as street names are. As such, some degree of logic is required to form the address to feed into the geocoder. 

While there is not something that is out-right broken with the geocoding process, if it could be improved, there would be an immediate, large benefit to the VZ team who would have less refining of locations that needed to be done.

This would be a good candidate for a discovery day project, or a "friday afternoon" type task.

**Comment by johnclary** [comment]
I share some concerns about geocoding data quality in the VZD, but I am going to close this because this kind of work just isn't on the horizon
