### ISSUE TITLE
Remove unused or crufty AWS resources

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11625]
In the course of working on #11594, a number of AWS resources were observed to be non-functional or otherwise crufty. Please see [this thread](https://austininnovation.slack.com/archives/CHZE6BC6L/p1677857715533579) for the original discussion. 

Included in the set of potentially removable items include:

* ECS cluster: `atd-cloud-composer`
* ECS Task definition: `atd-task-python`
* ECS Task definition: `atd-vz-data`
* ~31 CNAMES in `austionmobility.io` used for DCV~

Note: The CNAMES used for DCV are /not/ cruft. Per @johnclary's findings [available here](https://austininnovation.slack.com/archives/CHZE6BC6L/p1678119073868729?thread_ts=1677857715.533579&cid=CHZE6BC6L) in slack:

> At 60 days prior to expiration, ACM checks for the following renewal criteria:
> * The certificate is currently in use by an AWS service.
> * ⚠️ All required ACM-provided DNS CNAME records (one for each unique Subject Alternative Name) are present and accessible via public DNS.
> If these criteria are met, ACM considers the domain names validated and renews the certificate.

I'd like to get the group to approve this work and then delete these from our AWS account.

**Comment by frankhereford** [comment]
@johnclary - do any of these ring a bell?

**Comment by johnclary** [comment]
@frankhereford as we discussed, the CNAMEs give me pause but the rest looks like cruft to me.

**Comment by frankhereford** [comment]
Thanks @johnclary  - with @chiaberry's approval, I'll bring this to our next planning sesh, just a couple of days out, to see if we can get it assigned provided we have the bandwidth.

**Comment by frankhereford** [comment]
ECS cluster: atd-cloud-composer
* Already removed
ECS Task definition: atd-task-python
* Deregistered
ECS Task definition: atd-vz-data
* Deregistered
