### ISSUE TITLE
[BUG] Signs > AGOL ETL is failing

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#11636]
The signs > AGOL ETL is failing with the error:

>  File "/app/atd-knack-services/services/utils/agol.py", line 84, in handle_response
[2023-02-28 19:12:01,416] {{docker_operator.py:242}} INFO - raise ValueError(feature_status["error"])
ValueError: {'code': 1000, 'description': 'No mapping exists from object type System.Numerics.BigInteger to a known managed provider native type.'}

[Here's](https://austininnovation.slack.com/archives/C013G4RNJ01/p1678115534257369) an example Airflow error in slack.

**Comment by ChristinaTremel** [comment]
@johnclary - yes, @chiaberry brought this up last week and I saw that she might be working on this today!

**Comment by chiaberry** [comment]
We are going to remove the DIG_TESS_NUMBER from the agol dataset, however I couldn't figure out how to delete it and asked Andrew for help. 
>  I think you are unable to delete that field because we have joined views being created off that service, so I just need to remove those joins prior to deleting the field. 
He is going to help out when he has the bandwidth, hopefully tomorrow.

**Comment by chiaberry** [comment]
Andrew removed the field and the ETL is back in green!
