### ISSUE TITLE
Updates from 3/6/23 Finance meeting

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11639]
Improvements that were discussed or requested from our Sprint meeting with the Finance team.

**Comment by dianamartin** [comment]
## Changes Requested
### Email
- [ ] "Add Task Action" to email 
- for TK

### Add Job form
- [ ] For Task Type = Subproject 
Rename - Parent Project Number not Parent Project 
- [ ] For Task Type = BGEX
- Hide "Subproject" field

### Tab Navigation

New Tab - "Finance Tracking"
- All Service Requests 
- New Service Request form
- All Task Orders 
- All Contracts (future)

Finance & Purchasing Tab - ADMIN
- Manage Service Requests (Admin side) Service Requests

## SR Status 
- [ ] If "Assigned To", set status to "In Progress" for jobs too?
- Do not let user edit once assigned to is no blank

**Comment by dianamartin** [comment]
Created new epic issues for 
- EPIC: Email Notification Updates #11672 
- EPIC: SR Job Form Changes #11673 
- EPIC: General Functionality Changes #11674 
  - Renaming Fields #11683
