### ISSUE TITLE
Set up Knack Services for TCP Review Data to Socrata

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#11637]
Related issue: https://github.com/cityofaustin/atd-data-tech/issues/11457

Set up an ETL for moving data from Knack -> Socrata so it can be accessed by Power BI for:

Knack table: tcp_submission AKA object_3

- Average Review Time by Month
- Total Submissions Submitted by Month: 
- Maybe: Total Submissions by Resubmittal (%)

**Comment by Charlie-Henry** [comment]
@ChrispinP will help me get the view created in Knack for this 🙏 thank you

**Comment by ChrispinP** [comment]
These API pages are ready. I created one for the TCP Projects in addition to TCP Submissions just in case that data is needed as well.

**Record Locations:**
TCP Projects: https://builder.knack.com/atd/row/records/objects/object_2
TCP Submissions: https://builder.knack.com/atd/row/records/objects/object_3

**Builder Locations:**
TCP Projects: https://builder.knack.com/atd/row/pages/scene_222/views/view_484/table
TCP Submissions: https://builder.knack.com/atd/row/pages/scene_221/views/view_483/table

**Front End Locations:**
TCP Projects: https://atd.knack.com/row#api-views/tcp-projects-api/
TCP Submissions: https://atd.knack.com/row#api-views/tcp-submissions-api/

**Comment by Charlie-Henry** [comment]
merged, just need to set up ETL for this
