### ISSUE TITLE
IT Support: Add E-Access to Signs & Markings iPad Launcher Profile 

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11638]
Need to add the [E-Access](https://www.austintexas.gov/eaccess/default.cfm) shortcut link to the Signs & Markings launcher profile for the iPads.

**Comment by ChrispinP** [comment]
A request has been put in with CTM for these tablet profile shortcuts

Pending response.

**Comment by ChrispinP** [comment]
Confirmed eAccess & Service Portal shortcuts have been added to Android & iOS profiles. Shortcuts should install automatically on download/restart

complete, closing
