### ISSUE TITLE
[Bug] Investigate why CityBase payment is not triggering Approved status

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11640]
A customer paid for the same transaction twice. 

Over-the-Street - 2023 Austin Train Show - 04/24/2023 - George Z. INV2023-100265 - Number of Banners: 1 - Locations: # 8: 4199 1/2 N LAMAR BLVD

Diana, Christina, and Patrick evaluated the transaction on Knack and on CityBase to confirm that the customer had paid twice, as well as reviewed activity in Knack and think there's a bug on the backend that is causing a miscommunication that does not allow the status to move from "Approved - Pending Payment" to "Approved."

We'll need backend support @chiaberry to help us figure out where the bug is.

**Comment by dianamartin** [comment]
# 3/6
Patrick, Christina and I synced on this to find out what might've happened
- OTS RSVP: `947`
- Event Name: `2023 Austin Train Show`
- Transaction No: `INV2023-100265`

## Revenue Management
- Confirmed 2 payments were made
![image](https://user-images.githubusercontent.com/21112975/223211004-a8aade4f-716c-496c-9f82-13d5aa004010.png)

**Comment by dianamartin** [comment]
# 3/7
Emailed stakeholders
>Hi Mirna, 
Chia and I met this morning at 10 am for our sync meeting with you, but you didn’t show so we figured you got hung up. We believe we found the bug that was occurring. Chia said that the code wasn’t updating the parent reservation record to update the status to “Approved”. 

>Which leads me to believe you resent George (customer) the app details link so he could pay. He ended up double paying, but we’re resolving that with by you all working with finance to refund him the second payment. Chia and I are not sure why the first payment didn’t produce a confirmation page/email (according to the customer). 

>To alleviate this issue in the future, I added a few more fields on the “Invoice Transactions” table on the Reservation Details page. The “Paid Date” and the “Transaction Status”. You and Nicholas will also want to log into the Revenue Management website to confirm any double payments for times like this. 

![image](https://user-images.githubusercontent.com/21112975/223489664-98e72ecd-abe0-4e34-9c15-29f49c238daa.png)

**Comment by chiaberry** [comment]
I updated the endpoint over lunch to patch the bug where parent records weren't being updated.

**Comment by dianamartin** [comment]
# 3/8
I emailed the stakeholders
>Hey everyone, 

>Chia updated the code during lunch and hopefully things are patched up. Please let us know if you are noticing any weirdness when it comes to paid invoices that are not updating the banner reservation application status.
