### ISSUE TITLE
ROW Smartsheet data ETL for executive dashboard 

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#11651]
Related Issue: #11457 

Paloma shared with me three smartsheets that contain data that will be needed in the executive dashboard for ROW.
The three sheets are:

<img width="300" alt="Screen Shot 2023-03-07 at 1 02 03 PM" src="https://user-images.githubusercontent.com/30810522/223524418-55858dfb-0f6c-4ad8-b729-97621fd87246.png">

Looks like the smartsheet API is pretty good, just need to get us an account with the right access.

**Comment by Charlie-Henry** [comment]
Ryan set me up with an API token but for some reason when I list the sheets he has access to, I don't see the three listed in the image above ☝️

**Comment by Charlie-Henry** [comment]
ETL has been working since last week and the data is being merged with the counts out of AMANDA. Waiting for confirmation from Paloma that things are working.

**Comment by amenity** [comment]
@TracyLinder - another ROW for ya... maybe we can do a meeting to review this with the other two?

**Comment by Charlie-Henry** [comment]
Paloma has said this is working well and is integrated into the dashboard!
