### ISSUE TITLE
Sprint Review 3/7/2023 - Traffic Register

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11654]
### Objective 
Sprint Review for Traffic Register Product & Project. Define required fields for different reg types

### Participants
Christina, Diana, Anthony A, Eric, Dipti, Ravi, Brandon, Justin, Susanne, Joana, Chrispin, Steven, Daniel

------
- [x] Schedule meeting
- [x] Meet and take notes
- [x] Debrief with DTS team members
- [ ] Create resulting issues

**Comment by ChristinaTremel** [comment]
**Limitation of Movement**
- Always at an intersection
- Switch order of Reference Info fields to "Intersection Approach", "Side", and "Lane" (when reading it in a reg, "Side" and "Lane" will be swapped in the order.)

**Yield**
- Same as stop sign

**Time Park**
- Same as no parking

** Parking Meter** 
- Was Pay Station and Parking Meter. And now they use Pay Parking for both. 
- Rename Parking Meter -> Pay Parking
- Need to add "Block" to Primary Street (this is a common need for parking regulations)

** Traffic Signal **
- For an intersection that has street names converting (example Lamar and Barton Skwy/Lightsey Rd). Do we want to have the Barton Skwy/Lightsey streets in the same reg? People might need to add multiple streets to the Street Name (that example would need 2 streets for the cross street). 

** Temporary Construction No Parking **
- Can we add it, but use it for Regular Customer Service Zone and a Temporary, but just note that the Temporary should be deleted within 30 (or however many) days. If we could combine those, have 1 reg and an option to put this in with another reg type it might be helpful. 
- Eric thinking we need to keep the Temporary reg type because this might be used more in the future.

**Comment by ChrispinP** [comment]
Most of the above has now been implemented with the exception of a new Block field. We could possibly rename the From Block > Start Block and To Block > End Block to make them better understood as the block fields and not necessarily always tied to the From & To Streets. 

Thoughts? @ChristinaTremel

**Comment by ChrispinP** [comment]
@dianamartin Wouldnt affect display rules. Would probably create less complexity with the Block fields in the top section with something like so: 
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/b5ce607d-bcb7-4985-b63d-df44ba1d9c63)
