### ISSUE TITLE
Remove folder process Event Billed from RW-Street Event (LP)- (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11652]
### Remove 'Event Billed' process from from RW-Street Event
`OSE's # 1 Priority`

**Acceptance Criteria**

- The "Event Billed" Process needs to be removed(should no longer insert on the Accepted attempt in WAA Process) from RW- Street Event folders. 

More details on the process below. 

**Notes from Investigating Process workflow (Current State)**

- This process was created as part of card #6031
- This Process is inserted when Accepted attempt is made on Web Application Acceptance Process on an RW Folder with subtype Street Event. It is not inserted on any other RW permits. 
- Provided below is the functionalities of this folder. 
-- Event Billed Attempt - Sends email to applicant, changes folder status to Pending. 
-- Reminder attempt - Sends email to applicant. Changes Folder status to Pending. 
-- Paid attempt - - Changes Folder status to Pending, changes Process status to Closed.
-- Waived attempt - Changes Folder status to Pending, changes Process status to Closed. 
-- Cancelled attempt - Attempt comment is mandatory when making this attempt, changes folder status to Cancelled. Changes Process Status to Closed. 
- This feature isn't providing value or efficiencies. 
- Since this process does not insert any new processes in the workflow, if there are other ways to close the Folder or mark it Pending, removing it should not cause any downstream issues. 

----
**Scoping Notes:**
- Identify all dependencies & validations or downstream processes. 
- Document how the folder workflow should work w/o this process.

**Comment by vschandramouli** [comment]
Meeting scheduled with Priya for 4/4/2023 to go over possible dependencies.

**Comment by vschandramouli** [comment]
Documented possible dependencies and features, would like to confirm with SME before moving to Backlog.

**Comment by vschandramouli** [comment]
Discussed folder workflow and dependencies with Maria. Confirmed that removing this process will not impact any part of the workflow downstream. 

Updated AC, moving to Backlog.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Done teh changes in Local. There is a conflict with Subha's commit on the same procedure . Waiting on her commit to be deployed first.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created dev and test deployment request , SCTASK0323625

**Comment by Nadin-Nader** [comment]
Still waiting to be deployed

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been deployed to DEV and TEST. Please UAT and let me know if it is good to go to Stakeholder UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified the changes, Ready for UAT on Test

**Comment by Nadin-Nader** [comment]
Sent Maria a message via TEAMS to UAT this on TEST. Waiting on response

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Maria has UATd this on TEST and approved it to be deployed to PROD

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT can you please add the task number for this

**Comment by Nadin-Nader** [comment]
Sent message to Maria saying this is now on PROD and to please UAT

**Comment by Nadin-Nader** [comment]
This has been UATd by Maria and approved on PROD. Closing
