### ISSUE TITLE
Quarterly Bond Data Breakdown Page

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#11669]
Meredith requested a new page be added to the ATD Bond Dashboard. [Recording of the meeting](https://cityofaustin-my.sharepoint.com/:v:/r/personal/charlie_henry_austintexas_gov/Documents/Recordings/Updates%20to%20the%20Power%20BI-20230302_130206-Meeting%20Recording.mp4?csf=1&web=1&e=8l1vTe).

![image](https://user-images.githubusercontent.com/30810522/223779978-076907a5-f5c9-4bfc-b99d-5d7d84b0bf27.png)

It'll be similar to the past work but now it'll be broken down by FDU.

**Comment by amenity** [comment]
@ChristinaTremel - heads up, since Meredith is at TED
