### ISSUE TITLE
Migrate microstrategy to s3 prefect flow to 2.0

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11678]
1.0 version of flow: https://github.com/cityofaustin/atd-prefect/blob/main/flows/microstrategy/mstro_to_s3.py

**Comment by chiaberry** [comment]
@Charlie-Henry do you think this should be a 5?

**Comment by Charlie-Henry** [comment]
I'm ahead of you! https://github.com/cityofaustin/atd-data-tech/issues/11631

**Comment by chiaberry** [comment]
so far ahead of me!!
closing as duplicate
