### ISSUE TITLE
Create/Update Wiki Page - Github Standards

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1167]
- Labeling standards & requirements
- Issue naming standards
- Pipeline info & expectations
- When to create a Project label

**Comment by amenity** [comment]
@TracyLinder when you get a chance will you review [the updates I've made to the wiki](https://atd-dts.gitbook.io/wiki/product-ops/github-project-management) and see what you think is missing or needs clarity?

**Comment by amenity** [comment]
@TracyLinder @JaceDeloney @johnclary @moorerst anyone wanna give this a looksee so I can close it?

**Comment by TracyLinder** [comment]
@amenity Sorry Amenity! 

It all looks **FANTASTIC!!** 
I made one update:
![image](https://user-images.githubusercontent.com/49930868/84085060-614a1180-a9aa-11ea-9808-2a019e32f923.png)

**Comment by amenity** [comment]
Sweet, thanks, @TracyLinder ! calling this closed. 🌂
