### ISSUE TITLE
SR Job Form Changes

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11673]

**Comment by dianamartin** [comment]
# 4/4
Job ID Table after added a job type 
- [ ] highlight on Requested Service Request Job
Job Type: 
- [ ] Rename "Subproject" to "New Subproject"

**Comment by dianamartin** [comment]
# 4/26
- Finished TK, display rules
>finally hid encumbered FDU
- Finished Other, display rules
- New "Add an attachment" field

**Comment by ChristinaTremel** [comment]
# 5/12 Meeting Notes

Diana and I met this afternoon and thoroughly tested and updated form rules based on the various SR job types. 

Key updates to improve form functionality: 
- Updated radio buttons to drop down formatting
- Added rules for any SR types that have sub selections (TK with new, increase, decrease, close sub-options)
   - Rule saying IF NOT `subtype`, then hide the fields for that SR

**Comment by dianamartin** [comment]
# 5/30
- Met with stakeholders and showed them changes from the last sprint review, no other changes for this. Closing.
