### ISSUE TITLE
Raw Data: All TDS bills made since 10/1/22 (SR)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11670]
### We need a list of all TDS fees billed from 10/1/22 to Current Date.

**Parameters:**

- Fee code is in list below
- Fee is billed
- Paid flag is not C (cancelled)
- Billed date is 10/1/2022 to current date

**Output Columns:**

- F ROWID
- Folder Type
- Folder Name
- Folder Reference # 
- FeeRSN
- Bill # 
- Bill Date
- Paid Flag
- Fee Description
- Fee amount

**Fees Codes to Query:**

83473
83472
83474
83422
83496
83423
83495
83421
83420
83416
83497
83475
50500
83419
83476
83418
83415
83414
83498
51901
51712
51022
83426
83427
83424
83478
83477
83499
83434
83430
83479
83486
83436
83435
83437
83487
83488
83489
83490
83491
83493
83492
83433
83431
83480
83432
83429
83428
84010
84011
84012
84013
84014
84015
84016
84017
84018
84019
84020
84021
84022
84023
84024
84025
84026

**Comment by TracyLinder** [comment]
Thank you @Sreelatha-BlazeKannan. I need this by 11am tomorrow if possible.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Please find attached Raw TDS Bill Data for your reference. 

[TDS Bill Data from 10-01-2022 to current.xlsx](https://github.com/cityofaustin/atd-data-tech/files/11063093/TDS.Bill.Data.from.10-01-2022.to.current.xlsx)

**Comment by Nadin-Nader** [comment]
The Data has been given and no issues with it have been mentioned. Sree and i agreed to close this out and reopen if need be.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Sent updated query data again yesterday; Could not find the old query to verify why and how the $amount mismatch occured. New query saved for future data retrievals.

**Comment by TracyLinder** [comment]
Hi @Sreelatha-BlazeKannan there are still duplicates in the data. I'll respond to your email.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please add a column for FeeRsn and re-send the data. Thank you.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Sent the Queried data by including feersn into excel. Waiting for feedback.
