### ISSUE TITLE
Job Type: SubProject - Display Rules

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11687]
When creating a new SR job, a user selects `Subproject`

Should be visible: 
- [x] field: `Parent Project` - REQUIRED
- [x] field: `Subproject Name` - REQUIRED
- [x] field: `Subproject Description` - REQUIRED
- [x] field: `Detailed Scope` - REQUIRED
- [x] field: `Justification` - REQUIRED
- [x] field: `Subject Location` - REQUIRED
- [x] field: `Subproject Manager` - REQUIRED

Should be hidden: 
- [ ] field:

**Comment by dianamartin** [comment]
# 3/8
Reviewed fields and need to get stakeholder to review

**Comment by dianamartin** [comment]
# 3/21
- Changed all fields requested to "Required"

**Comment by dianamartin** [comment]
# 3/22
- [ ] Copy form to both "New Job" forms

**Comment by ChristinaTremel** [comment]
# 5/16
Diana and I synced 5/12, 5/15, and 5/16 and updated display rules. Yesterday and today I've been testing the job forms thoroughly and found that the display rules were showing the correct fields and the fields were named correctly. The Subproject job type has these updated display rules:
