### ISSUE TITLE
Job Type: JV - Display Rules

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11689]
When creating a new SR job, a user selects `JV/IET` (Internal Exchange Transaction)

Should be visible: 
- [x] Direction: `To` or `From`
- [x] FDU - short text 
>should this be a connection field?
- [x] Amount

Should be hidden: 
- [x] field: `Subproject`
>Updated display rules on 3/8 to hide this field

**Comment by dianamartin** [comment]
# 3/21
- [ ] New field: `From FDU`, {amount}
- [ ] New field: `To FDU`, {amount}
- [ ] Amount - Rename to "Expense Amount"
- [ ] New field: `Transfer Reason` - paragraph text

**Comment by dianamartin** [comment]
# 3/28
- [x] Added display rule for renaming "Amount" to "Expense Amount"
- [x] Added rule to hide "Subproject"

![image](https://user-images.githubusercontent.com/21112975/228374557-0cfe3959-588b-448c-9055-d754b7bd95f0.png)

**Comment by ChristinaTremel** [comment]
# 5/16
Diana and I synced 5/12, 5/15, and 5/16 and updated display rules. Yesterday and today I've been testing the job forms thoroughly and found that the display rules were showing the correct fields and the fields were named correctly. The JV job type has these updated display rules:
