### ISSUE TITLE
AGOL Map embed in VZA app

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#1168]
Weird hanging text over map 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/a5fa50c4-691d-4d71-b50f-39bb53307f70)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/9988eaf8-ca4f-4c33-a568-bc27a815b3c1)

**Comment by SurbhiBakshi** [comment]
need to get ownership back from Jaime and see if I can enable search on the features in addition to an address search

**Comment by amenity** [comment]
@SurbhiBakshi - I don't remember discussing this feature — can you describe it to me?

**Comment by amenity** [comment]
This would be a process for the GIS team to follow if we were going to try to connect to Data Tracker locations.

**Comment by amenity** [comment]
@SurbhiBakshi @dianamartin will we be able to get rid of this functionality now that we're using the CTM Street Segment layer?

**Comment by SurbhiBakshi** [comment]
@yes, the CTM Street segment layer and ATD school zones will replace the existing features in the reference map.

**Comment by amenity** [comment]
@SurbhiBakshi - is this issue representing a bug? Trying to figure out how it relates to #1306.

**Comment by SurbhiBakshi** [comment]
@amenity - this is done, @john helped me out.

**Comment by amenity** [comment]
@SurbhiBakshi - super. Will you add a milestone to show when it was taken care of?
