### ISSUE TITLE
Job Type: Task Orders (TK) - Display Rules

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11685]
When creating a new SR job, a user selects `TK`
- Select "Task Action"

Can choose:
- New
- Increase
- Decrease
- Close

**Comment by dianamartin** [comment]
Task Order Action fields

## New
- [ ] show "FDU Name", "Type"

## Increase
- [ ] hide "FDU Name", "Type"
- [ ] show "Existing
- [ ] show "Task Order No"
- [ ] show "Amount"

## Decrease

- [ ] hide "FDU Name", "Type"
- [ ] show "Existing
- [ ] show "Task Order No"
- [ ] show "Amount"

## Close
- [ ] hide "FDU Name", "Type"
- [ ] show "Existing TK"

**Comment by dianamartin** [comment]
# 3/17
## New

## Increase 
>This is accurate

## Decrease 
>Make this look like the Increase
- show "existing TK
- show Type
- show Amount

**Comment by dianamartin** [comment]
# 4/4
TK:
Still need to hide "Encumbering FDU" for increase/decrease

**Comment by dianamartin** [comment]
# 4/26
- Fixed the Display Rule for the TKs!!!

## job type and TK Task Action is "blank" 
![image](https://user-images.githubusercontent.com/21112975/234698468-f7dd67aa-4997-479c-b6b7-03f064ad64ba.png)

## New & Increase
![image](https://user-images.githubusercontent.com/21112975/234698656-8045b802-9d7a-4f3e-b15e-c77f8c9b24f2.png)

## Decrease & Close
![image](https://user-images.githubusercontent.com/21112975/234698734-6acfed24-3fed-4928-a157-3a1420669bd7.png)

**Comment by ChristinaTremel** [comment]
# 5/16
Diana and I synced 5/12, 5/15, and 5/16 and updated display rules. Yesterday and today I've been testing the job forms thoroughly and found that the display rules were showing the correct fields and the fields were named correctly. The JV job type has these updated display rules:
