### ISSUE TITLE
Service Request - Attachment functionality

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11684]
##  Add ability for user to add attachment and for Finance to also add attachments 
- Ex. when doing a JV/IET (Internal Exchange Transactions)
  - Finance has to send an attachment back to the user

**Comment by dianamartin** [comment]
# 3/21
- Remove old attachment function
- Build out standard Attachment Table/Form feature
- Include Attachment Type: `SeRF, SAs'

**Comment by patrickm02L** [comment]
In grooming 2/29/23 Diana said she incorporated attachments into the IET #11792 and Other #11795 JobTypes. 

In the next Sprint Review meeting we'll demo how to do attachments.

**Comment by patrickm02L** [comment]
Closing because it was accomplished in other JobTypes. See last comment.
