### ISSUE TITLE
Give Miles M Access to Data Tracker Manage Equipment Page

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11695]
Jorge is requesting that Miles M gets access to the [Manage Equipment page](https://atd.knack.com/amd#home/equipment/) to help with issuing out equipment.

**Comment by dianamartin** [comment]
@KaroEngstrom Can you check to see if Miles M. is already in the DTS Portal? or active?

**Comment by KaroEngstrom** [comment]
## Th 3/9/23 
- checked in with Jorge on roles 
- decided to create a new role for this specific task as more users may need access to assist; the role is Equipment Management Assist
- added Miles and notified Jorge 
- added the ability for Jorge to add this role as an Account Admin in Data Tracker
