### ISSUE TITLE
Get feedback on prioritization framework

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1169]
Get preliminary input on framework — possibly from Lewis?

**Comment by amenity** [comment]
@JaceDeloney @johnclary @TracyLinder - revisiting this, I think I'm comfortable presenting to the exec team without running by someone first... Or at least interested in one less meeting. :) Should I scrap this issue?

**Comment by johnclary** [comment]
@amenity fine with me

**Comment by amenity** [comment]
Per 👆, getting rid of this.
