### ISSUE TITLE
Manage Service Request Details page | Admin

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11693]
As a Finance Staff, need the ability to review the Service Request page so that I can work on the SR jobs in the Service Request. 

Before I only had the "Service Request" page, that was a shared page for the requester and finance staff. It was getting complicated, so I decided to have their own area to manage the SRs.

**Comment by dianamartin** [comment]
#11639 
- [x] "Service Requests Jobs | Admin" got renamed to "Manage Service Requests" 
- [x] Created a new details page for the admin
- [x] Copied all the job tables (Subproject, FDU, TK, BGEX, JV/EIT)

# 3/8
- [x] Moved the "admin menu" (to change status) to the new page 
- [x] Added the page rules to hide the job tables if there were no jobs

**Comment by dianamartin** [comment]
# 4/25
- Copy SR Job tables to Admin Details page
`scene_360` to `scene_432`
- [x] BGEX
- [ ] Subprojects
- [ ] FDU
- [ ] JV/EIT (rename to IET, split into another table?
>see Requested Service Request Jobs -  `scene_431/views/view_1018/table`
- [ ] Task Orders

**Comment by KaroEngstrom** [comment]
## Fri 4/28/23

Tables copied from on Customer page to Admin page
Copy SR Job tables to Admin Details page
scene_360 to scene_432
-  BGEX - editable (added by @dianamartin ; shows as Uneditable) 

- [x]  Subprojects table - editable - copied editable table
- [x] FDU table - editable - copied editable table
- [x]  JV/EIT (rename to IET, split into another table? - editable
     - Copied the table twice and changed filters so each table shows only the one type
     - Changed EIT to IET

see Requested Service Request Jobs - scene_431/views/view_1018/table

- [ ] Task Orders table - editable

**Comment by dianamartin** [comment]
# 5/15
Christina and I are reviewing this page. We will update the page rules to get ready for the stakeholder meeting.

**Comment by dianamartin** [comment]
# 5/30
We showed the stakeholders the new changes during our Sprint Review on 5/30 and this is ready to close.
