### ISSUE TITLE
Job Type: FDU - Display Rules

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11694]
When creating a new SR job, a user selects `FDU`

**Reference fields??**
- [ ] field: `? Service Request` - connection
- [ ] field: `? SR Job` - connection
>rename to: `New Subproject ID`
>- make visible
- [ ] field: `? Existing Subproject` - connection

Should be visible: 
- [ ] field: `Subproject Number`
- [ ] field: `FDU Name`
- [ ] field: `Parent FDU` - REQUIRED
>Inquiring on validation format: 4 space 4 space 4
- [ ] field: `Funding Source FDU` - REQUIRED
>Inquiring on validation format: 4 space 4 space 4
- [ ] field: `Amount`

Should be hidden: 
- [x] field: `FDU Number`
> on 3/8, updated display rule to hide this field
- [x] field: `Subproject Number`
>hide this field, 3/17

**Comment by dianamartin** [comment]
# 3/17
- Would like to automate the "Subproject IDs" from data warehouse, so that Finance staff won't duplicate efforts
-

**Comment by dianamartin** [comment]
# 3/21
- [ ] Need to hide "FDU Number" on form

**Comment by patrickm02L** [comment]
Turn the New Subproject Number and Existing Project number for Job Type FDU into a Task Action dropdown menu like in Job Type TK.

<img width="1505" alt="Screen Shot 2023-03-29 at 10 32 09 AM" src="https://user-images.githubusercontent.com/5566727/228591599-d479abf3-d6cd-4a4a-9e5a-3e1120875420.png">

Once Existing Subproject Number is select activate subproject IDs from datawarehouse #11798

**Comment by dianamartin** [comment]
# 4/4
FDU
- Still need new FDU Action field "Using"
  - "New Subproject Number" 
  - "Existing Subproject Number"

**Comment by dianamartin** [comment]
# 4/25
- [ ] Created new "FDU Task Action"

NEW
- show FDU Task Action "New" 
- show "New Subproject Number" 
- show "FDU Name"
- show "Parent FDU"
- show "Funding Source FDU"
- show "Amount"

**Comment by dianamartin** [comment]
#4/25 - Reviewed with users at Sprint Review, seemed to be happy with feature update.

**Comment by ChristinaTremel** [comment]
# 5/16
Diana and I synced 5/12, 5/15, and 5/16 and updated display rules. Yesterday and today I've been testing the job forms thoroughly and found that the display rules were showing the correct fields and the fields were named correctly. The JV job type has these updated display rules:
