### ISSUE TITLE
Review, contemplate, and iterate on values

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#117]
Let's revisit the value statements we compiled at the offsite! 

[Here's a doc to work in](https://docs.google.com/document/d/14IGBLJ5RefZvdqFfCzGp4iIdKcq3Y7aKEUSIe_6NXz4/edit#).

**Comment by johnclary** [comment]
[USDS Values Statement](https://www.usds.gov/mission) << scroll down

[Candian Digital Service](https://digital.canada.ca/what-we-do/)

[18F Values](https://handbook.18f.gov/history-and-values/#our-values)

**Comment by amenity** [comment]
https://playbook.cityofnewyork.us/
https://civicservicedesign.com/tools-tactics/home 
https://www.oneteamgov.uk/principles 
https://www.gov.uk/government/organisations/gover
https://18f.gsa.gov/how-we-worknment-digital-service/about 
https://www.gov.uk/service-manual/service-standard      
https://18f.gsa.gov/how-we-work 
https://www.boston.gov/departments/digital-team#guiding-principles
https://www.phila.gov/programs/open-data-program/

**Comment by amenity** [comment]
Tactics: 
- https://playbook.cityofnewyork.us/
- https://civicservicedesign.com/tools-tactics/home

**Comment by amenity** [comment]
I put together [this table of our fav examples](https://docs.google.com/document/d/1rCPdLlxwjCbFn4J-xtoXB_e7DuxILnVnvSd4H6ag_Ks/edit) (feel free to add) so we can compare the mission, values, and strategies.

**Comment by johnclary** [comment]
...
[Boston](https://www.boston.gov/departments/digital-team)
[Philadelphia](https://www.phila.gov/departments/office-of-open-data-and-digital-transformation/)
