### ISSUE TITLE
Find uses of `& &` in VZ codebase and use `&&` where appropriate

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11701]
`&&` means "has an overlapping bounding box", and I'm not sure what '& &' ends up doing, but I don't think it's what we want. Please see [this slack thread](https://austininnovation.slack.com/archives/CM9MK950S/p1678400239999239?thread_ts=1678398208.097029&cid=CM9MK950S). 

@johnclary pointed out in slack the following definition of a geospatial function, which brought this to light:

```
CREATE
OR REPLACE FUNCTION public.find_crash_jurisdictions(given_crash_id integer) RETURNS SETOF atd_jurisdictions LANGUAGE sql STABLE AS $ function $ (
  SELECT
    aj.*
  FROM
    atd_txdot_crashes AS atc
    INNER JOIN atd_jurisdictions aj ON (
      1 = 1
      AND (aj.geometry & & atc.position)
      AND ST_Contains(aj.geometry, atc.position)
    )
  WHERE
    1 = 1
    AND atc.crash_id = given_crash_id
) $ function $
```

**Comment by patrickm02L** [comment]
in grooming 3/15/22. We need to figure out where this is happening and fix it.

Here is the [lambda function](https://github.com/cityofaustin/atd-vz-data/blob/53ddfccd3c24b81a9a35ed4af766d68ca02cd971/atd-events/crash_update_jurisdiction/app.py#L137-L160) that John referenced.

**Comment by roseeichelmann** [comment]
Looks like this instance was [already fixed](https://github.com/cityofaustin/atd-vz-data/blob/1ab38c9158088a93c357cb4ad5c1ccc218aea6b6/atd-vzd/migrations/default/1692924316671_init/up.sql#L691C25-L691C25) and I can't find any other instances of this, so I'm gonna close out this issue!

**Comment by patrickm02L** [comment]
Thanks @roseeichelmann. Shortest Issue ever!
