### ISSUE TITLE
Assess DTS Use of GitHub TYPE Labels

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1170]
Work to occur after we have migrated to the mono-repo.
- Identify labels that can be removed because of non-use
- Gather insights on the use of the TYPE labels
- Make updates as needed

What information do we want to derive from this label long-term?

**Comment by amenity** [comment]
If there were a `Type: ProductOps` label I'd use it on this 😆

**Comment by amenity** [comment]
Per a [fun #atd-product Slack convo](https://austininnovation.slack.com/archives/CPGC2L4QZ/p1589835325025200) arrived at
