### ISSUE TITLE
Write script to backfill Law enforcement number by crash ID

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11700]
The fatality tracking page has a column titled "Law Enforcement Number"

Joel can provide can provide a spreadsheet with the Law Enforcement number by Crash ID for past crashes. 

New crashes, the number will be input manually.

**Comment by patrickm02L** [comment]
Joel responded to me and Rose with the spreadsheet noting where to find the Law Enforcement Number, that every calendar year the Numbers reset, and there are acronyms in some cells versus numbers.

> Hi Patrick, attached is the latest Fatalities List and Recommendations spreadsheet. 
> Column D, “APD Fatal Crash Number” is the new “Law Enforcement Number”.  
> 
> Since these numbers reset every calendar there are going to be duplicates. I don’t think this is necessarily a problem though since we can also filter by year. 
> 
> You’ll notice some of these say “DPS” or “UTPD” since these crashes were responded to by an entity other than APD. CC’ing Xavier or Mary in case they have anything else to add.
