### ISSUE TITLE
KNACK Bug: Null values are setting a default date to 1/1/1970. 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11707]
### Null values are setting a default date to 1/1/1970. 
<img width="1107" alt="Screenshot 2023-03-10 at 1 43 58 PM" src="https://user-images.githubusercontent.com/49930868/224413047-f4a2b557-8510-4f2d-bad3-6372a3a859fb.png">

**Comment by ChrispinP** [comment]
Tested to see if 0 values work instead, bug still persists for both `null` and `0` values. Sent message to Knack, pending response.

**Comment by ChrispinP** [comment]
@dianamartin @TracyLinder @KaroEngstrom @susannegov 

This is now fixed! Knack made an update sometime in June it seems. Ive updated the affected records in both ROW & TDS so the Auto Due Dates do not show 01/01/1970 if they are supposed to be blank.

To update the affected records you can add a second conditional rule to force them back to blank.
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/cde5c922-8751-43e4-b0ae-560eefaf3aaa)

**Comment by ChrispinP** [comment]
no further action, closing as resolved
