### ISSUE TITLE
Clean-up unused EBS volumes

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11714]
Please see [this conversation](https://austininnovation.slack.com/archives/CHZE6BC6L/p1678740386333659) in slack.

We have 7 volumes in EBS that are not attached to running instances. This issue is to spin up an ec2 instance, mount them in turn, look for data that we need to keep and get that into a less costly storage regime. 

Additionally, volumes which remain in EBS should be bumped up to the `gp3` storage class, as it's both cheaper and faster as these sizes.

**Comment by patrickm02L** [comment]
we touched on this at grooming 3/15/23. Frank said that we could save $20 a month.

**Comment by frankhereford** [comment]
@chiaberry 👋 Would it be cool if we brought this up in the next sprint or two? We have about 100 GB of EBS volumes. They are $35/month and they are almost assuredly not storing data we have any interest in. I'd love to just yolo remove them at this point, but I'd be happy to put eyes on them and see if there is any data work keeping.

**Comment by frankhereford** [comment]
I've removed them. They were all `gp2` volumes created in 2020 or earlier. ~58 GB.

👋 🧹🧹🧹
- vol-0084d51d509ce4d0b
- vol-09e21495e3eac5eaa
- vol-0a7e9ecc7596416ae
- vol-0b06eaa742e676885
- vol-05c31af17f69eaa24
- vol-0fa02846c10dde485
- vol-0a3c34a8c5abde2c6
