### ISSUE TITLE
Enhance VZ local development environment to prefer to download the days VZDB snapshot from S3

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11715]
Currently the VZ local development environment populates the database by first downloading data from the read replica. This is not as reliable as it needs to be for unknown reasons related to the RDS read-replica configuration.

This issue is to enhance the local environment orchestration to pull the daily backup from S3 instead. The ability to pull from the read replica will be turned into an optional argument to the `vision-zero` program.

**Comment by patrickm02L** [comment]
Frank brought this up in grooming 3/15/23 to give us a heads up. Does not block anything but the impetus was the flakiness of being able to replicate from production.

**Comment by frankhereford** [comment]
I think the urgency on this has gone from low to none because the flakiness of replication from production has been resolved with recent work on the RDS clusters. I'm not sure this is worth doing, as It's just a nice-to-have at this point and even could be closed until a stronger use case comes up.

**Comment by patrickm02L** [comment]
Closing. Good that we can reference this documentation if it comes up again.
