### ISSUE TITLE
Install Prefect 2 agent on `rds-bastion`

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11723]
Install Prefect 2 agent on `rds-bastion`. 

Informing this work will be to observe how prefect's API keys expire (or don't) after 30 days. This agent is intended to provide task fulfillment for processes which most benefit from having a low-latency connection to the RDS instances. 

Thanks to @chiaberry for sharing her resources that she used when she did this similar task on `atd-data03`: https://discourse.prefect.io/t/how-to-run-a-prefect-2-agent-as-a-systemd-service-on-linux/1450.

**Comment by chiaberry** [comment]
closing since we are no longer using prefect
