### ISSUE TITLE
Migrate CR3 Narrative OCR to Airflow 2

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11731]
CR3 Narrative OCR
https://github.com/cityofaustin/atd-prefect/tree/main/flows/vision-zero/cr3_ocr_narrative_extract_diagram

**Comment by patrickm02L** [comment]
https://github.com/cityofaustin/atd-data-tech/issues/12087#issuecomment-1587582043

> Just want to note that issue 11731 is to move the script from prefect 1 to airflow 2, I am not sure how much of it needs to be updated to be able to interact with the LDM.
