### ISSUE TITLE
Meet with stakeholders to discuss VZA Locations & geographic data/visualization

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1174]
1/23/2020

[Notes](https://docs.google.com/document/d/1aSBPTF5uqL_wU4mhMewfQ19zdTR3VQQikIk5iiF9KrM/edit#)

**Comment by amenity** [comment]
@SurbhiBakshi @dianamartin @johnclary 
Please add any questions/notes you want to cover [here](https://docs.google.com/document/d/1aSBPTF5uqL_wU4mhMewfQ19zdTR3VQQikIk5iiF9KrM/edit#).

**Comment by amenity** [comment]
@SurbhiBakshi @dianamartin - please add anything I missed to t[he notes](https://docs.google.com/document/d/1aSBPTF5uqL_wU4mhMewfQ19zdTR3VQQikIk5iiF9KrM/edit#)

@johnclary - you should look 👆 over soonish.  👀 🙏

**Comment by johnclary** [comment]
@amenity looks good. added a comment about data tracker signal's:

> note that signals in data tracker are already connected to street segments via their `location` record
