### ISSUE TITLE
Create DTS value presentation for ATD executives

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#11742]
@maccallump needs help putting together a meaningful presentation on our services/solutions to cement the value we provide to the department and the city

The Director, Richard, requested info on "what services DTS provides" to be presented during the Data and Tech Services Budget Review FY24 meeting on Tuesday, April 4 at 2 PM. (All divisions are being asked to do this, not just DTS.) The meeting invite from Richard reads: Setting up this in-person meeting to review the FY24 budget for your Division. Staff should come prepared to **quantitatively explain and discuss what services ATD will provide in the requested budget**.

**[Google slides presentation deck](https://docs.google.com/presentation/d/11rjn6bsAG7TA35c7xXU5opab50a1r4rprw3PcQauo4g/edit#slide=id.p1)**

[Presentation outline](https://docs.google.com/document/d/1CVYWy6UtK0lCAJfH3l7bqKIeRr6GC54TtHdUo59ExDo/edit)

[Folder to gather any other materials](https://drive.google.com/drive/u/0/folders/1PnXYoSlEB6l04m_MNOLaotNEIWy-lIrZ)

[Kudos document](https://docs.google.com/document/d/1AvwimHjGnLVsF2YipG-dtl1g59Q-9_z6NK_0Vcfot0E/edit#) (new, for ongoing collection)

**Challenges to overcome**
- Deliver a compelling presentation/storyline on the value DTS brings to the department in around 20 minutes
- Dispel the perception that we're a traditional/legacy IT group; show how much more we offer than just the niche role of our IT guy (Scott)
- Highlight quantitative info/reporting when possible
- Source testimonials/kudos

**Notes**
- Richard is really focused on field crews so let's highlight how we support them.
   - Christina has photos of technicians from the KNACK presentation. 
- Richard likes visuals so let's use those whenever possible.
- Include testimonials with examples of our work (and throughout is possible) 
- Idea: If a slide focuses on a specific project, include profile pics (and names and titles?) of the DTS team members who worked on it

### Action items
- [x] Brainstorm meeting on 3/23 at 2 PM - @maccallump , @amenity , @dianamartin , @katelunceford 
- [x] Write slide outline draft - [here](https://docs.google.com/document/d/1MIbdkn3_BZ3cr5IDPe1-GizeeRyZJTxE/edit)
- [x] Create slide deck draft - [here](https://docs.google.com/presentation/d/11rjn6bsAG7TA35c7xXU5opab50a1r4rprw3PcQauo4g/edit#slide=id.p1)
- [x] Team meeting on 3/29 at 1 PM - @maccallump , @amenity , @dianamartin , @katelunceford 
- [x] Assign slides to complete
- [x] Create/source imagery - make sure to include some tech in the field
- [ ] Collect testimonials for each item listed below
- [x] Update slide deck with imagery + testimonials
- [x] Dry run on 4/3 at noon
- [ ] Finalize slide deck - see comment below "Ideas to enhance slide deck"
- [ ] Deliver presentation to Director

### Collect testimonials
- [ ] [AMD Data Tracker](https://docs.google.com/presentation/d/11rjn6bsAG7TA35c7xXU5opab50a1r4rprw3PcQauo4g/edit#slide=id.g22a994ac139_0_119) - Brian C. or Ivonne
- [x] Vision Zero - Lewis L.
- [x] Moped - Laura D. 
- [ ] Screencaps of recent praise from users

**Comment by katelunceford** [comment]
### Slide deck outline

**Data + Technology Services
Bringing value to ATD**

1. DTS Solutions: So much more than IT
2. Case Study: Vision Zero
3. Our Team: Curated talent
4. Agile Workflow: Projects in the pipeline

*1. DTS Solutions: So much more than IT*

Myth Busting
- Assumption: DTS is the IT of ATD
- Truth: Yes, but we're also so much more
- We leverage high quality data and modern technologies to support and empower ATD staff to: 
   - Improve operations
   - Track meaningful metrics 
   - Make data-informed decisions
   - Deliver excellent mobility services to the Austin community 
- We solve real problems for real people.
Abracadabra

**Comment by katelunceford** [comment]
Presentation was cancelled last minute by the Director. Waiting to hear if it will be rescheduled.

If/when that happens, we'll be ready.

**Comment by katelunceford** [comment]
###Ideas to enhance slide deck
- [ ] [How We Prioritize slide](https://docs.google.com/presentation/d/11rjn6bsAG7TA35c7xXU5opab50a1r4rprw3PcQauo4g/edit#slide=id.g22a994ac139_0_158) - need better term than "money pit"
- [ ] [DTS Requests slide](https://docs.google.com/presentation/d/11rjn6bsAG7TA35c7xXU5opab50a1r4rprw3PcQauo4g/edit#slide=id.g22b2c720cfd_1_0) - turn "Request Types" into bar graph or pie chart
- [ ] Add date somewhere so we know the content is current 
- [ ] Add captions to all images like on [slide 23](https://docs.google.com/presentation/d/11rjn6bsAG7TA35c7xXU5opab50a1r4rprw3PcQauo4g/edit#slide=id.g22a994ac139_0_134)
- [ ] Add screencaps of recent praise from users
- [ ] Create slides for every major product/project to be able to choose the best examples for specific audience
