### ISSUE TITLE
[DevOps] Bump Hasura Engine to v2.20 in local + staging

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#11749]
As discussed [here](https://austininnovation.slack.com/archives/CNUEPKLB1/p1678984517268649), going forward we will do this every release cycle:
1. Bump our local docker-compose and the moped staging ECS definition to the most recent Hasura version
2. Bump the prod ECS task definition to match the previous local/staging version

Right now we’re on 2.17.1 everywhere, so we need to kick this off by upgrading local to v2.20, and during[ the release](#11661) we can leave prod as-is but bring staging ECS up to match 2.20.

**Comment by frankhereford** [comment]
The service definition for staging to get to 2.20.1 is ready to roll for the release party.

**Comment by johnclary** [comment]
We ended up bumping production to `2.20.1` as well. H/t @frankhereford for catching the [critical vulnerability](https://github.com/hasura/graphql-engine/releases/tag/v2.20.1) this patch addresses. 

I will update our notes to bump staging to `v2.21` as part of the next release.
