### ISSUE TITLE
Onboard Susanne to DTS Apps

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11743]
## Accounts - Team Lead

- [x] Submit a [CTM New Employee Request Form](https://atx.servicenowservices.com/sp?id=sc_cat_item_guide&sys_id=b714eb12db7a3f0021ccef92ca961972) for a COA network account, eAccess PIN/HR Portal, and phone 
>submitted `Active Directory - Update Existing User Network`
- [x] Submit a [CTM service request](https://atx.service-now.com/sp) to add to DTS Distribution Email Group:
  - [x] Add "First Last Name" to email distribution list "ATD Data and Technology Service" ([ATDDataTechnologyServices@austintexas.gov](mailto:ATDDataTechnologyServices@austintexas.gov)) and "ACE ATD DL"
- [x] Add to City of Austin Slack - austininnovation.slack.com 
- [x] Add to DTS Google Drive
>after Susanne creates her account
- [x] Add to [Gitbook](https://app.gitbook.com/@atd-dts/spaces)
- [x] Add to [Austin Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members) 
- [x] Upload headshot to ["Headshots" Drive folder](https://drive.google.com/drive/u/0/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G)
- [x] Add to group slide and team slides [DTS Presentation Template Team section](https://docs.google.com/presentation/d/1tHKTfUgQ-uAXdRBkEdXqR7ryBo_LTU86IzQxo1gJoeA/edit#slide=id.gfd2da31025_0_6) (KE 3/24)
- [x] Update DTS group and team slides in the DTS Orientation presentation to reflect ☝️ (KE 3/24)
- [x] Check w/ Diana/Amenity—if needed; we pay for seats

## Hardware — DTS Systems Admin

- [x] Coordinate with DTS System Admin (Scott), make sure there is enough lead time for equipment to be acquired.
>Scott said that Susanne will need to bring over her laptop and docking station
- [x]  Laptop
- [x]  Docking station
>she's bringing these from SMD
- [x]  Monitors
>Scott set up monitors on the desk assigned to Susanne
- [x]  Chair - check availability, ask Peggy/Amenity/Diana
- [x]  Power supply
- [x]  Keyboard 
- [x]  Mouse 

## Calendar invites - Team Lead 

- [x] Schedule or coordinate with event owner
- [x] First day: DTS Team Orientation — invite all leads, Peggy optional
- [x] First Week: DTS Product Ops — Coordinate w/ Amenity
- [x] Monthly Team Meeting
- [x] Sprints
- [x] Sprint Ceremonies — Planning, Grooming, Sync, Show & Tell
- [x] Biweekly 1x1

**Comment by dianamartin** [comment]
## Employee To-Do List

- [ ] ~[Log in to your City of Austin email](https://outlook.office365.com/)~
- [ ] [Update up your email signature](https://docs.google.com/document/d/1OAoBll9rIl6XZq2uOShm5HCbHJboOt0SLP_wK6tjkEE/edit)
- [ ] [Create a Google account for your austintexas.gov email address](https://atd-dts.gitbook.io/atd-staff-resources/general/using-google-as-a-city-employee)
- [ ] If you don't have one already, [create a Github account](https://github.com/join) 
- [ ] Install [Zenhub Browser Extension](https://www.zenhub.com/)
- [ ] Post your [daily standup in Slack](https://atd-dts.gitbook.io/wiki/slack#daily-stand-up)
- [ ] [Update yourself up for remote work - TLC Form](https://atd-dts.gitbook.io/atd-staff-resources/working-remotely/getting-started)
- [ ] [Set up Cameron Road printer](https://app.gitbook.com/@atd-dts/s/dts-service-desk-knowledge-base/onboarding/printer-information) 
- [ ] Set up docking station — [Windows](https://www.dell.com/support/home/us/en/04/product-support/product/dell-universal-dock-d6000/drivers) | [Mac](https://www.displaylink.com/downloads/macos) (see [here](https://support.displaylink.com/knowledgebase/articles/1188004-macos-10-13-or-10-14-video-functionality-not-enab) if you're having issues on Mac. If you have an M1, grant screen recording permissions as detailed [here](https://m1displays.com/) )
- [ ] Upload a headshot [here](https://drive.google.com/drive/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G) and add your title and preferred pronouns [here](https://docs.google.com/document/d/1gRjTic8FD3s-t0sVZhErAidMIAktU-0Vn2GYPpPcUeg/edit) (Google Drive access must be set up first)
- [ ]  [Create a Github issue](https://github.com/cityofaustin/atd-data-tech/issues/new) for adding yourself to the [DTS "About Us" webpage](https://austinmobility.io/about) (labels: Service: Dev, Type: Operations, Product: DTS Website) including the link to your photo and preferred pronouns
- [ ] Familiarize yourself with the [DTS Resource Index](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/~/changes/195/resource-index)
- [ ] Email Adan S. to to update your supervisor to Diana - Diana should do this?
- [ ] Ask questions! Be a sponge and absorb it all! 🧽💦🌈
- [ ] Bonus: [Update this wiki](https://app.gitbook.com/@atd-dts/s/wiki/) if you find broken links or missing information! 😉

**Comment by susannegov** [comment]
Finally finished the Employee To-do Lists. Thank you Diana for emailing Adan about timesheets (I wasn't sure if I was supposed to do it from the list).

The wiki that I've been working on to update is the Markings QA Documentation since it looks like it was last updated years(?) ago and a lot has changed. See Github Issue [#11812](https://github.com/cityofaustin/atd-data-tech/issues/11812)

**Comment by dianamartin** [comment]
@susannegov did you create your new github account with your work email?

**Comment by susannegov** [comment]
Fixed now! Amenity added me to the organization using zenhub and now can see the workspace.

**Comment by dianamartin** [comment]
@dianamartin Add Susanne to DTS Slide decks, Apps Welcome all slide decks

**Comment by dianamartin** [comment]
We've done all on the on boarding tasks for Susanne, closing
