### ISSUE TITLE
Investigate use of `host.docker.internal` on linux/x86 in VZ local dev

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11761]
Rose contacted me today with an issue she's run into while testing [PR 1174](https://github.com/cityofaustin/atd-vz-data/pull/1174) in VZ.

A part of that PR appears to be connecting to the host machine using the docker-compose provided hostname `host.docker.internal`, which is provided when your host is a mac, but may not when your host is linux.

![image](https://user-images.githubusercontent.com/3653206/226000244-b41abdf0-7b45-48e4-81da-a1dd1f3b2a24.png)

This issue is to track discussion and possible remediation of that. At the very least, it should be evaluated to find out if the problem only affects one-off scripts, or if this is a flaw in the stack as a whole. I'm hoping it's the prior.

**Comment by patrickm02L** [comment]
Discussed in grooming 3/29/23 we decided this was a very low priority. We've icebox-ed incase this comes back up again.

**Comment by frankhereford** [comment]
Rose and I can work together in a sync when it comes time to review this PR, however, I think we may already have end-run this now that I think about it by agreeing to roll up all the LDM work into one testing operation.

**Comment by johnclary** [comment]
The LDM is done, so I'm closing this.
