### ISSUE TITLE
Build Prototype for License Plate Lookup

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11777]
### Prototype

- [x] Build an object
- [x] Build form
  - License Plate
  - Status
  - Color of the Zone
  - Record ID
- [x] Test: use dummy data 5-10 records.

_example image_
![2affa4e3-fc66-410b-850a-f7fc63b16394.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/0d5e0e14-1be5-446f-9dc9-457ae55a09fc)

**Comment by dianamartin** [comment]
# Build Guide
##  License Plate Prototype
- [ ] Build an object: `license_plates
- [ ] Field Headings
  - License Plate - default characters (short text)
  - Status - multi-choice (Active/Inactive)
  - Color of the Zone - 
  - Record ID - auto generated ID 
- [ ] Build form - "License Plate Look up" form
  - License Plate
  - Status
  - Color of the Zone
  - Record ID
- [ ] Test: use dummy data 5-10 records.

**Comment by susannegov** [comment]
I built the license plate lookup form in my sandbox as a test.

**Comment by susannegov** [comment]
Presented build.
- Option 1 - List view
- Option 2- Grid view
![image](https://user-images.githubusercontent.com/31259724/230210486-7aad54a9-e9e5-47be-9282-225fa402a9b7.png)

Someone mentioned (Jacob?) that they preferred Option 2. 

- [ ] Waiting for passport API to retrieve license plate records for search
- [ ] There should be a message for if the license plate lookup is not in the record, the page will print a message along the lines of: `This vehicle is not permitted.`

**Comment by susannegov** [comment]
This is what the message looks like under both options. Note that I moved Status and License Plate column ordering but can be moved as needed.
![image](https://user-images.githubusercontent.com/31259724/230224099-a624f38c-7e33-4f6b-8d79-a38ed16e730c.png)

For Option 1, I went to Search object > Settings > Empty Results Text

`<br /><div style="background-color:#ff9b9c;padding:10px;color:#4a4a4a;border-radius:5px;"> This vehicle is not permitted.</div>`

For Option 2, I went to Search object > Settings > Empty Results Text
`This vehicle is not permitted.` 

If the user puts too many/little characters, the validation rules will not run.

**Comment by susannegov** [comment]
I put the license_plate object in the RPP Portal in Production.

Creating login page with Admin/Viewer permission to see search view

Page view of Search License plate `https://builder.knack.com/atd/parking/pages/scene_388`

## Changes
- Empty Text field: License plate record is not found.
- Used option 2 (grid view)
- Moved sandbox object to prod

**Comment by susannegov** [comment]
## Changes
- Added background color to status
    - Permitted: `#80d07e`
    - Not Permitted: `#ff9b9c`
- Created admin account for myself to see how it looks in front-end

![image](https://user-images.githubusercontent.com/31259724/232142939-8696b887-fca4-40e8-bd57-4c08696f5633.png)

**Comment by johnclary** [comment]
hey y'all—i've got security on the brain and just wanted to make sure we're on the page: putting this license plate data in a public searchable knack app is essentially equivalent to publishing an open data portal dataset of all the license plates that are permitted. it will be possible for a novice hacker/coder to retrieve all the license plate records from this search tool and you'll want to plan for the possible outcome that such a list circulates on twitter, reddit, etc.

**Comment by dianamartin** [comment]
@johnclary We did ask legal their advice before moving forward with this #11202 they said that as long as we didn't have PII information and were okay with us showing the "plate/status/zone color".

**Comment by johnclary** [comment]
cool then we should publish this to the open data portal!

**Comment by susannegov** [comment]
The test app of the LPL has been created named: `TEST | 08 JUNE 2023 | RPP | Residential Parking Permits Portal` @chiaberry

Followed the reference gitbook without any issues, added test environment to [DTS portal listing of applications under RPP](https://atd.knack.com/dts#applications/view-application-details/5e39a98bffb27e0015eeb90c/), and notified service desk primary.

**Comment by susannegov** [comment]
Closing it out

**Comment by patrickm02L** [comment]
This was foundational work to the LPL, we moved from Knack to a custom code build that will integrated into the COA website. reference #11778
