### ISSUE TITLE
Job Type: IET (Internal Exchange Transaction) - Display Rules

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11792]
- Attach IET - User attaching an invoice from another department
- Attach IET 
  - Email and Invoice combined (backup for Controller)
  - send to AIMs transaction (processed) requester

**Comment by dianamartin** [comment]
- [ ] Use new "Attachment" feature
- [ ] With "Attachment Type" 
- [ ] Instructions to enter on Instructions and Comments, enter FDU

**Comment by dianamartin** [comment]
# 3/28
- [x] Added "Attachment" field to `subproject_job` object table
- [x] Added display rule to rename "attachment" to "IET Attachment"
![image](https://user-images.githubusercontent.com/21112975/228379855-fb4bff94-7abb-4eed-93a9-bd82b13398cb.png)

**Comment by dianamartin** [comment]
Closing, showed the stakeholder this job type and no modifications.

**Comment by ChristinaTremel** [comment]
# 5/16
Diana and I synced 5/12, 5/15, and 5/16 and updated display rules. Yesterday and today I've been testing the job forms thoroughly and found that the display rules were showing the correct fields and the fields were named correctly. The JV job type has these updated display rules:
