### ISSUE TITLE
Job Type: Other

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11795]
For an "Other" Job Type
- Attachment Type: "SeRF", "SA"

**Comment by dianamartin** [comment]
# 4/26
- [x] Created new field `Adding an attachment` - Multi-choice
- [ ]

**Comment by ChristinaTremel** [comment]
# 5/16
Diana and I synced 5/12, 5/15, and 5/16 and updated display rules. Yesterday and today I've been testing the job forms thoroughly and found that the display rules were showing the correct fields and the fields were named correctly. The Other job type has these updated display rules:
