### ISSUE TITLE
[Spike] Explore ways to reduce setting redundant values in Zappa settings

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#11797]
In the atd-vz-data Github Actions, we set the same values in multiple places which makes it hard to rotate keys. It opens us up to breaking things more easily if we miss a spot. It would be nice to do a small spike into ways to make this easier on ourselves when we rotate keys.

For example, in these settings we:
- set the Hasura admin secret
- set the S3 role key and secret twice in the staging and production env vars
- set the Auth0 API client and secret twice in the staging and production env vars 

We also reuse these settings to deploy the SQS Lambda handlers so they deploy with more secrets set in their env vars than they need. Having only the secrets that those Lambdas need would make it more obvious what needs rotating when looking at them in the AWS console. This could tie into pulling values out of the Zappa config in the Github Actions secrets and injecting them.

The pain points to work on are:
- Updating values in the `zappa_settings` in the password manager is tricky
   - need to update file each time a single secret is updated
   - need to use jq to make a JSON string that goes in CircleCI or Github Actions env vars
   - some secrets are the same between stages and some are not
- If you forget to update a secret in the settings file, you have to repeat a lot of steps to get our staging and production resources updated

**Comment by johnclary** [comment]
I am closing this in favor of: https://github.com/cityofaustin/atd-data-tech/issues/18154
