### ISSUE TITLE
Automate the "Subproject IDs" from data warehouse for FDU JobType

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11798]
Staff needs to be able to easily access and reference the subproject IDs associated with the FDU job types in the data warehouse.

Automation would involve creating a script or program that pulls data from the data warehouse and filters it based on job type, returning a list of all subproject IDs associated with that job type.

- similar to #10960. 
- The object ID for `financial_subprojects` is 46

**Comment by ChristinaTremel** [comment]
- Created new issue for tracking this #12376 
- Closing out this issue
