### ISSUE TITLE
Define Viewer role/permissions and features/views

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1179]
The Viewer role needs to be able to 
 - See what officers are on shift at any given time
 - Call the officers and redirect them to a higher-priority location (typically emergency redirection at an intersection)

**Considerations**
- We will be using the Viewer role for MMC staff, so do we want to limit the view to day-of assignments?
- Do we enable self-registration or have them request accounts?
- What documentation is necessary for them?

**Comment by SurbhiBakshi** [comment]
- [ ] Added a page for creating a new Viewer account
- [ ] Added a menu to link to the New Viewer account creation page from the Home login.
- [ ] Who will share the weblink?
- [ ] Who will validate new users?

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/263826a0-96c0-4e43-ac80-66ee5c7892bc)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/62be16b0-c2d1-4aad-a126-c970c72fd3a0)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/dedbdfcc-52cd-44e2-ab84-f5e4fa398c3c)

**Comment by amenity** [comment]
@SurbhiBakshi - Since [our wiki situation is up in the air](https://github.com/cityofaustin/atd-data-tech/issues/1039) at the moment, I think it's easiest and fastest to draft in Google Docs.

**Comment by SurbhiBakshi** [comment]
@amenity Google Docs works for me. Also who will share the link with MMC staff and who will validate new users? Think we should have some validation for Viewer accounts ,  they will be able to see some officer information details.

**Comment by amenity** [comment]
@johnclary @dianamartin - wanted to double check that self-registration is what y'all recommend vs. account requests coming to us like the do for Data Tracker...

If so, who (a supervisor-y person in the MMC? Jen? Brian C.?) should "approve" accounts? Do we have an existing pattern for count pending/approval that you like?

**Comment by amenity** [comment]
@SurbhiBakshi, sticking in the backlog for now since there are more pressing items.

**Comment by amenity** [comment]
Will be resuming this based on #2812.

**Comment by amenity** [comment]
This was covered by #2813.
