### ISSUE TITLE
Create Documentation for Using Living Atlas

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#11791]
**Things to include:**
- Created separate documentation for use in AGOL and Pro (Use template in Google documentation folder for reference)
- Include top relevant datasets include links to data in AGOL (Travel time to Work, Transportation to Work, Vehicle Availability, Median Income, Poverty Status, Race and Hispanic Origin, etc.)
- How to view metadata or detailed description of data in Living Atlas
- How to verify that data is Authoritative, officially a part of Living Atlas, Managed by ESRI
- How to verify when data was last updated

**Comment by DanielStover** [comment]
Living Atlas documentation has been created for both ArcPro and AGOL.
