### ISSUE TITLE
Data sets for bike share

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#1180]
When making a visualization for https://data.austintexas.gov/Transportation-and-Mobility/Shared-Micromobility-Vehicle-Trips/7d8e-dm7r/data, Vehicle Type is bicycle works in the dataset, but not in the Pie Chart. Vehicle Type 'contains' or 'starts with' works, but not Vehicle Type 'is'

**Comment by amenity** [comment]
@SurbhiBakshi @johnclary - is this a dev issue?

**Comment by SurbhiBakshi** [comment]
@amenity, this was resolved by Tyler W


Solution recommended by Tyler - This is not an issue with the visualization tool. User needs to select “add hierarchy” on the left hand side and add vehicle type in order for the “bicycle” domain to populate on the right hand side (see screenshot). Here’s a published demo version of the visualization I suggested.

Going to confirm with @tylerwhitson

**Comment by amenity** [comment]
Gotcha. So should this be closed, then?
