### ISSUE TITLE
Inventory VZ lambdas and database triggers

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11810]
Assemble list of all VZ lambda functions and database triggers. 
What do they do?
When do they happen, are they scheduled via cron/airflow/prefect or does an action initiate them?

Break up the lambdas into two groups
* Ones which are database trigger like (These could be turned into future issues to write them as triggers and functions in pg)
* Ones which are micro services, such as the one that handles file uploads for moped into S3 which should stay as lambdas

**Comment by roseeichelmann** [comment]
**atd-vz-data-events-crash_update_noncr3_location_production**
Hasura event trigger
Triggered on insert to atd_apd_blueform or update of columns latitude, longitude
This calculates a new location ID on crash location update if necessary and if the new location id is different from the old location id then it updates it. This seems like it could be converted to a DB trigger.

**atd-vz-data-events-crash_update_location_production**
Hasura event trigger
Triggered on insert to atd_txdot_crashes or update of columns latitude, latitude_primary, latitude_geocoded, longitude, longitude_primary, longitude_geocoded
This calculates a new location ID on crash location update if necessary and if the new location id is different from the old location id then it updates it. If the crash is a mainline crash then it nullifies the new location_id. This seems like it could be converted to a DB trigger.

**atd-vz-data-events-crash_update_noncr3_location_staging**
Hasura event trigger
Triggered on insert to atd_apd_blueform or update of columns latitude, longitude
This calculates a new location ID on crash location update if necessary and if the new location id is different from the old location id then it updates it. This seems like it could be converted to a DB trigger.

**atd-vz-data-events-crash_update_location_staging**
Hasura event trigger
Triggered on insert to atd_txdot_crashes or update of columns latitude, latitude_primary, latitude_geocoded, longitude, longitude_primary, longitude_geocoded
This calculates a new location ID on crash location update if necessary and if the new location id is different from the old location id then it updates it. If the crash is a mainline crash then it nullifies the new location_id. This seems like it could be converted to a DB trigger.

**atd-vz-data-events-crash_update_jurisdiction_staging**
Hasura event trigger
Triggered on insert to atd_txdot_crashes or update of columns latitude, latitude_primary, latitude_geocoded, longitude, longitude_primary, longitude_geocoded
Checks what jurisdiction (AFP or not) the new crash location is in and updates the austin_full_purpose flag if necessary. It also checks if the new location is within  jurisdictions 5,3,7,8,10 and if so updates the crash city_id to 22. This seems like it could  be converted to a DB trigger.

**atd-vz-data-events-crash_update_jurisdiction_production**
Hasura event trigger
Triggered on insert to atd_txdot_crashes or update of columns latitude, latitude_primary, latitude_geocoded, longitude, longitude_primary, longitude_geocoded
Checks what jurisdiction (AFP or not) the new crash location is in and updates the austin_full_purpose flag if necessary. It also checks if the new location is within  jurisdictions 5,3,7,8,10 and if so updates the crash city_id to 22. This seems like it could be converted to a DB trigger.

**atd-cr3-api-production**
Zappa Deployment
An API that securely downloads a private file from S3 deployed in a Lambda function with Zappa

**atd-cr3-api-staging**
Zappa Deployment
An API that securely downloads a private file from S3 deployed in a Lambda function with Zappa
