### ISSUE TITLE
VZD: Implement ETL using FTP dump as the source

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#1181]
The goal of this task is to retire our web scraper for requesting CRIS extracts, forwarding emails and an S3 bucket, and extracting details from that source.

As of 1/7 we're getting nightly imports from CRIS into our SFTP server.

We need to:
- [ ] Verify the extract represents the parameters we have been requesting with Splinter
- [ ] Update our ETL scripts to use this SFTP server as our source
- [ ] Deprecate the Splinter script.

**Comment by johnclary** [comment]
@sergiogcx @mateoclarke would you post your updates here? cc @patrickm02L
