### ISSUE TITLE
New TDS Mitigation Backfill Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11815]
### Build a page for TED to scrub mitigation records and add segment/intersection data. 
- We cannot move forward with this project until the mitigation records can be mapped. 

- [x] New Page
- [x] New menu button [here](https://atd.knack.com/development-services#tia-mitigations/) linking to the page, only can be seen by user role TIA Mitigation Editor. Button should be on the bottom of the table

**Comment by dianamartin** [comment]
@ChrispinP 
Christina and I reprioritized the AMD task for public comment, you can go ahead and grab this and do it since Gilda approved Drew to assist. 

Thanks!
cc: @TracyLinder @ChristinaTremel

**Comment by ChrispinP** [comment]
Created Menu & Page for [Mitigation Location Backfill](https://atd.knack.com/development-services#tia-mitigations/mitigation-location-backfill/). Only Mitigation Editors have access. Added all relevant location/geo fields to the table, grouped by TIA Project, and created filters for geo type and blank records.
![image.png](https://images.zenhubusercontent.com/5f036c8940760b58210af838/8bd0d2c9-2c1d-49bf-884c-71d2d56f182a)
Created Edit Location Information modal for editing all location data
![image.png](https://images.zenhubusercontent.com/5f036c8940760b58210af838/33fd6c18-5919-4ef1-a455-27dbdc1d7a37)

Ready to Review

**Comment by TracyLinder** [comment]
### Review Feedback
- Make X & Y viewable only
- Does drew need to be able to edit the project address? 
- Tracy will schedule training sesh w/ us, Nelson, Drew

**Comment by TracyLinder** [comment]
### Notes from Review w/ Team 4/3/23

- Q: Mitigation location reference: lock it down & move to the top
- Drew doesn't need to add the lat & long. Confirmed by Andrew. 
- Asked Andrew to update lat/long format decimal point, he did it
- Training Drew tomorrow, Chrispin will lead


TIA Mitigation Editors are Nelson, Cody, Drew

**Comment by TracyLinder** [comment]
### Training Notes

- Add column for Improvement Type FYI @ChrispinP 

### Workflow 

1. Log in & click the button **TIA Mitigations**
2. Click on the button **TIA Mitigations Backfill** (top left)
3. Click the **edit button** on the mitigation record
4. In the Primary Mitigation Location field, type in the address or intersection.
5. The system will provide results to choose from in the drop-down. Select one.
6. The system will zoom in on the location in the map.
7. **Click on the segment or intersection**. A mini pop-up window will open with the segment or intersection ID.
8. **Copy the ID and paste it** into the Primary Mitigation Location field
9. Repeat for Additional Mitigation Locations field. You may enter multiple IDs in this field.
10. **Click Save.** The form will close.

**Comment by TracyLinder** [comment]
@ChrispinP please close this issue after you add the Improvement Type Column. I'll create an issue for the data backfill.

**Comment by ChrispinP** [comment]
Both Improvement and Improvement Comment fields added to table and form (read only). These fields provide additional context for a Mitigation's Location.

complete, closing
