### ISSUE TITLE
Data Request for Approved & Released SP folders

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11817]
### Query Info

- Folder type is SP
- Folder status is Approved and Released (14,966 rows)
- ~Expiration must be today or greater~
- Folder people type is Applicant

**Fields we want:**

- ROWID
- f reference # 
- Expiration Date
- folder year
- Folder People: First & Last Name, Org Name, email address

Meeting request by Curtis on 3/23/2023
_A brief discussion about filtering site plan cases for a certain condition, collecting the applicant’s contact info for those cases, and then sending a mass email to those specific applicants to provide info regarding SIF._

**Comment by TracyLinder** [comment]
C: Dealing w/ a case last week made them realize they can do better communicating to a set of applicants. Those applicants are those who have had an SP application sitting around for a while. So as they go for their building permit, they find out about SIF, and they're very surprised. TDS would like to notify those people. 

SP approved in last 5 years, but has not applied for building permit.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Please find query results in attached excel. I have added peoplersn and Phone number for additional information. 

[SIF - SP Folder Data.xlsx](https://github.com/cityofaustin/atd-data-tech/files/11055251/SIF.-.SP.Folder.Data.xlsx)

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan it looks great & i sent data to the customers. Thank you!
