### ISSUE TITLE
Prototype of Mitigation Map

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11816]
### Create a prototype of the web application to view mitigation data. 
- Using the 57 mitigation records that can be mapped
- Soft deadline right now / aim for April 5th sprint.

**Comment by TracyLinder** [comment]
### Notes from Review w/ Team 4/3/23

- Q: Mitigation location reference: lock it down & move to the top
- Drew doesn't need to add the lat & long. Confirmed by Andrew. 
- Asked Andrew to update lat/long format decimal point, he did it
- Training Drew tomorrow, Chrispin will lead


TIA Mitigation Editors are Nelson, Cody, Drew

**Comment by dianamartin** [comment]
@andrewshensky do you have the link to the prototyped map?

**Comment by andrewshensky** [comment]
Below are the two prototypes that were put together about a year ago. Both are pretty vintage at this point but let me know if we need to start back up on this.

Dashboard Prototype:
https://austin.maps.arcgis.com/apps/dashboards/b89c344a9fd54e73a10d2b651c9c928b
Web App Prototype:
https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=14180c8261b04b9abd3c5c1c7a6a1795
