### ISSUE TITLE
Add Susanne to DTS "About Us" page

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#11813]
Add Susanne G to the [DTS "About Us" webpage](https://austinmobility.io/about)

Link to [photo](https://drive.google.com/file/d/1iidCJ6b6pR9_WVIEXlWF1k8y49vsqV2n/view?usp=share_link).
Pronouns: she/her

**Comment by chiaberry** [comment]
I can do this, if no one has been assigned yet -- whats the job title I should put on the website?

**Comment by susannegov** [comment]
Talked to @dianamartin Job title is Application Analyst

**Comment by chiaberry** [comment]
PR opened here: https://github.com/cityofaustin/atd-product/pull/62/files
