### ISSUE TITLE
Add "Work Area" field to the Signs | Advanced Search & Markings | Advanced Search Pages

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11818]
Esteban G is requesting the "Work Area" field to be added to the advanced search pages for [Signs](https://atd.knack.com/signs-markings#work-order-signs/advanced-search-signs/) & [Markings](https://atd.knack.com/signs-markings#work-orders-markings/markings/search-markings-work-orders/). The Work Area field already shows on the table below, but it's not a field that can be filtered.

**Comment by ChristinaTremel** [comment]
@dianamartin could we issue this request to someone on the Apps team? Esteban was needing this for scheduling purposes and it seems like a pretty quick request.

**Comment by dianamartin** [comment]
@susannegov I've assigned you to this, we can pair on this together and do it during your 1:1 or find another time. cc @ChristinaTremel

**Comment by dianamartin** [comment]
# 3/28
Susanne and I synced together and updated this
- [ ] Signs WO Advanced Search - Diana
- [ ] Markings WO Advanced Search - Susanne

**Comment by susannegov** [comment]
@ChristinaTremel Updated the issue.
