### ISSUE TITLE
3 Data Sets for DS Expiration Bugs

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11823]
## Various bugs have created inaccurate data on DS folders on the folder status and folder expiration date. We need to find all effected DS folders and export data about them for analysis. 
- **3 Data queries**

### Columns for each query:

- Folder RSN
- Status
- Issue Date
- Issued By
- Expiration Date

### 1. All active DS, with an expiration date different than the BP (parent RSN) expiration date.

- Folder is DS
- Expiration date is today or greater
- Parent folder expiration date does not match the DS folder expiration date. 

**Extra Data Columns:**

- BP ROW ID
- BP Status
- BP expiration date

 
### 2. Expired DS with an expiration date today or greater. 
- Folder is DS
- Expiration date is today or greater

### 3. All DS folders, active, with an expiration date in the past or no expiration date
- Folder is DS
- Status is Active
- Expiration date is in the past OR is null

**Comment by TracyLinder** [comment]
@Lpriya-LIT i updated the AC. This is On Deck for you. 

FYI @Nadin-Nader - This isn't critical, but if we can have it by next Wednesday that would be great. TY

**Comment by Lpriya-LIT** [comment]
[https://app.zenhub.com/files/140626918/5f199b85-d504-49b4-83dd-2fa88e056ef7/download](https://app.zenhub.com/files/140626918/5f199b85-d504-49b4-83dd-2fa88e056ef7/download)

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader I have sent the data in email. 
There is no folders for Data query 1. All active DS, with an expiration date different than the BP (parent RSN) expiration date.
Have sent data For Data query 2 and 3.

**Comment by Nadin-Nader** [comment]
@TracyLinder is this good to close or does it need more time?

**Comment by Nadin-Nader** [comment]
@TracyLinder Closing for now as data request points 2 and 3 have been given. Point 1 has no folders for the data query.
