### ISSUE TITLE
Bug: SIF Payments Didn't Update Bill Table (Waiting on Swapna and Victor to deploy fix)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11822]
### ROWID 13048155, bills did not update to PAID when the payment was applied. Applicant building permit cannot be approved until the bill shows as paid. 
- **CTM MUST FIX**
- INC0282434 Created

- Folder ROWID's 13089443, 13048155, 13025984, 13052135

![sif bill](https://user-images.githubusercontent.com/49930868/227333910-b211ee94-9440-4245-b4a5-c456c40ac050.jpg)

**Comment by Nadin-Nader** [comment]
Update: Per Sree's conversation with Swapna, she should be able to fix this now. Waiting on more from Swapna

**Comment by Nadin-Nader** [comment]
Asked Swapna for an update Via email. Waiting for response.

email:
From: Nader, Nadin 
Sent: Monday, April 17, 2023 6:04 PM
To: Thatikonda, Swapna <Swapna.Thatikonda@austintexas.gov>
Subject: Status Update on ROWID 13048155, bills did not update to PAID when the payment was applied Card # 11822

Hi Swapna,

Hope you are doing well. Hey I was wondering if you had an update on this issue, INC0282434.

Respectfully,

Nadin A. Nader (He/Him/His)

**Comment by TracyLinder** [comment]
### Sync w/ CTM 4/24

1. 13052135
    - Write a script to update relevant tables to revert values so we are able to cancel the bill. Also update the paid in full flag to C. 
    - Then we can create a new bill and pay it. (ATD)

**Comment by Nadin-Nader** [comment]
The fix has been found and is ready. Waiting on CTM (Victor) To update the DB with newly written Script. Once that is done, Swapna will run it in SOAP and update the DB's and AMANDA data.
Waiting on CTM

**Comment by Nadin-Nader** [comment]
@TracyLinder is this deployed to PROD and fixed? or does it need to go to ongoing pipeline?

**Comment by TracyLinder** [comment]
This is fixed. 
Closing.
