### ISSUE TITLE
Sync with CTM regarding EOL plan for CentOS 7 on-prem servers

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11835]

**Comment by johnclary** [comment]
See also:
- https://github.com/cityofaustin/atd-data-tech/issues/13240
- https://github.com/cityofaustin/atd-data-tech/issues/12804

**Comment by frankhereford** [comment]
I wrote the ctmlinux team this morning. The upgrades on the on-prem servers failed last night due to some of the configured 3rd party repos we'd put on there having been taken down as they hit EOL. We did proactive upgrades manually yesterday, so I let them know that updates had been applied. 

I also inquired about the future plans with regards to the CentOS 7 EOL coming up this summer.

**Comment by frankhereford** [comment]
Jason Glass wrote back with a lot of great information. They are targeting Rocky Linux 9 as the successor to CentOS 7, and they are going to provision 3 new servers for us to transition to. That's really an ideal setup, where we can end up with a switch-over to the new machines and incur no, or nearly no downtime. They detail the firewall systems that they are going to move to as RH has deprecated the use of `iptables` and I'll write up an issue that outlines my proposal for getting ready for this move.
