### ISSUE TITLE
Bug w/ RW Free-Form Tab (On PROD for user verify)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11837]
### Users are getting an error when updating the free-form tab on RW folder. 
![image](https://user-images.githubusercontent.com/49930868/228004390-4b7930a7-825d-4a44-bb84-dd5dd799f96a.png)

![image](https://user-images.githubusercontent.com/49930868/228004468-9db6c769-d1f4-4d4c-9d73-0466ec98f879.png)

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader SCTASK0298303 is submitted for DEV deployment of the fix. Thanks.

**Comment by SubhaShroff** [comment]
Tested on DEV and had to make one more commit - [aa79278d4e1b](http://coaamandadevops02.austintexas.gov/R5:aa79278d4e1b0be577da914e9e3eb87180c6be2d). Waiting for CTM to deploy that too. It should be good.

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder After above commit also promoted, I tested it on DEV and submitted it for TEST promotion. SCTASK0298406.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is in TEST and I tested it.  Ready for UAT.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This must be in PROD by now. Ready for UAT on PROD. Thanks.

**Comment by Nadin-Nader** [comment]
This is now working. Confirmation from users was received. Closing:

> [10:28 AM] Franklin, Tan-Tanisha
> Shroff, Subhashini - VendorAmayo-Ryan, PalomaFranklin, Tan-Tanisha The property Street information issue fix must be in PROD. Any of you can check and confirm. Thanks. Amayo-Ryan, Paloma It's working for me! Shroff, Subhashini - Vendor Thank you!
>
