### ISSUE TITLE
Write script to update account bill table on SIF payments

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11833]
### Manually update accountbill table for bills that were paid but the system didn't update bill to paid. 
- Bug card is #11254 
- INC0282434 Created

KNOWN RSNS: 13052135, 13089443, 13048155, 13025984

**Comment by Nadin-Nader** [comment]
@TracyLinder is this still happening? or can we close?

**Comment by TracyLinder** [comment]
This was resolved on #11182
Closing
