### ISSUE TITLE
Create a spreadsheet to review the columns in LDM to validate and expand the list of computed columns

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11830]
Action item

* Frank sends spreadsheet of all columns in the VZ database, broken out by table, where I color code them as computed or not, with the idea that Xavier will validate these choices and indicate other fields which he thinks are candidate for dynamism.
  * He gave a really good example where crash_sev_id which is in the crashes table should be driven from the persons’ tables, and be dynamic, even though it’s a CRIS provided field. That’s subtle and forward-looking, more bold than I had thought to push the LDM, at least at first blush.

**Comment by frankhereford** [comment]
In grooming today, we discussed this issue and agreed to support this extension of the LDM to include computed fields for lookup values, in a way, restoring the relational database functionality that was in the upstream CRIS database. We additionally covered the idea of having a UI element in the VZE that can reveal the original CRIS value for a computed field used in a lookup.

**Comment by patrickm02L** [comment]
I thought I put it on-deck earlier. It's there now.

**Comment by frankhereford** [comment]
I've created two data input sources for this task:

* ✅ A set of queries that return all the columns and their types out of the `crashes`, `units`, `persons`, & `primarypersons` tables that can be copied into a spreadsheet
* ✅ A set of queries that return all the columns and types out of the same tables, but only looking at the data we receive from CRIS.

✅ Subtracting one set from the other results in a list of columns that are created by our team and can only have data from the VZ side in them.

Using these 3 sets of data listed in a spreadsheet, the task is to research / decide:

* [ ] Which columns can be represented as a computed value that is computed every time the associated record is accessed
* [ ] How making the column a computed, read-only field might impact the VZ team or the app
* [ ] Get VZ approval / buy-in

**Comment by johnclary** [comment]
Using Frank's previous work as a starting point, I compiled this [VZD Inventory](https://docs.google.com/spreadsheets/d/1oHzKt8Cvd1BGpZ7KJl4dfBDHGuSl7gs4yN0OM7AJMBA/edit#gid=0) doc which we're using to track all column and table changes in the data model. Xavier and I together reviewed the hundreds of changes we'll be making to "de-scope" the DB into only the columns we care about. And that includes the list of computed fields/calculated/triggered fields.

It's safe to consider this work done!
