### ISSUE TITLE
Add Crash Table for Level 5 Polygons

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11847]
reference #11735 

We currently query the crashes table to see what crashes are associated with the location in the view and then calculate the totals for these figures. Crash records store what level 1-4 location that they are associated with in the location_id column in atd_txdot_crashes table. Since level 1-4 and level 5 crashes can overlap, we can't store multiple values in that column for a record. 

Possible solutions: create a new column that exclusively stores what level 5 polygon ID that a crash falls under? Or a specific view for level 5s?

**Comment by mddilley** [comment]
See https://github.com/cityofaustin/atd-data-tech/issues/12060
