### ISSUE TITLE
[Traffic Register] Enhancement: Display Rules for Admins Backfill pages based on Reg Types

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11879]
Joana would like to show/hide certain fields to ease the regulation editing process for the admin backfill. Will need to do a full ruleset of similar display rules for all the Reg Types for all edit regulation pages in the app.

[Reg Text Automation Review with Stakeholders](https://miro.com/app/board/uXjVPkkmY_w=/)

**Comment by ChrispinP** [comment]
Completed this as part of issue #10206 

Pending any further changes

**Comment by ChristinaTremel** [comment]
Chrispin also implemented display rules on Admin backfill page so closing this issue as well.
