### ISSUE TITLE
VZD: Harden security for SFTP server

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#1187]
Scope the things that need to be changed for added security for our SFTP server running on Lighstail.

1. To make sure TxDOT only has access to the current folder
2. Make sure the data is deleted once processed
3. Make sure that nothing of value in the SFTP server remains there after an ETL run.

**Comment by sergiogcx** [comment]
I am seeing brute-force login attempts recently, I have to dedicate some time to analize the traffic from txdot and determine if their IP address is static so I can white-list it, otherwise I could generate an IP range.

**Comment by sergiogcx** [comment]
- [x] SSHD : Disabled root login
- [ ] SSHD: Disable Password login (cannot implement yet)
- [ ] Firewall: Whitelist TxDOT
- [ ] Firewall: Whitelist ATD (CTM network)

Ideally, we want to exclude all traffic from this box and leave it only to TxDOT and ATD, in order to do that we need to reach out to TxDOT and find out if they have a network IP range they can provide.

**Comment by JaceDeloney** [comment]
This is outdated. We will need to revisit how we're using the SFTP to access crash records in CRIS.
