### ISSUE TITLE
Investigate Prefect 2 flow runs stuck in Pending status

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#11903]
The service bot intake should only run one at a time. To make sure this happens, we created a Prefect 2 work pool called `atd-service-bot` and limited concurrency in that pool to 1.

An unexpected side effect of this is that a run became stuck in Pending status and blocked future scheduled runs because it never resolved. The same thing happened to Knack Services: Data Tracker SR Assign Signals
flow but it didn’t matter because there is no concurrency limit on the work pool that it runs in. Only manually cancelling that pending run allowed the process to continue.

- What is causing the runs to stick in Pending status?
- Can we force them to proceed/retry?

Pending runs:
https://app.prefect.cloud/account/62be21ad-87d4-4858-bc47-a49e1fd29df7/workspace/4e909dab-3495-4e26-9403-9b633af2c970/flow-runs?flowRuns.state.name=Pending
Cancelling status runs:
https://app.prefect.cloud/account/62be21ad-87d4-4858-bc47-a49e1fd29df7/workspace/4e909dab-3495-4e26-9403-9b633af2c970/flow-runs?flowRuns.state.name=Cancelling

Prefect Community discussion:
https://discourse.prefect.io/t/my-flow-run-in-prefect-2-is-stuck-in-a-pending-state-what-can-i-do/2012

Some suggestions from John:
https://austininnovation.slack.com/archives/CHZE6BC6L/p1680283554727179?thread_ts=1680279965.231409&cid=CHZE6BC6L

**Comment by mddilley** [comment]
As a workaround, Charlie added a third automation in the Prefect 2 console to clean up and runs stuck in Pending status. He also set up a Slack notification so we know when this clean up happens. I've set the concurrency limit back to 1 on the atd-service-bot work queue since this new automation will prevent this from happening. 

Will monitor and I think that we can icebox this if it continues working, and we don't need that third automation slot for anything more important which is unlikely. 🚀

**Comment by mddilley** [comment]
Going to switch back to Prefect 1 flow since this is continuing to affect the flow

Other ideas:
- Alter the Prefect 2 code to make it dry run and observe
- Switch between Prefect 1 and 2 while observing/triaging

**Comment by frankhereford** [comment]
I am going to grow the `/var` partition today on `atd-data03` using the LVM2 tools to add 50G of space so that docker is less likely to fill up and cause intermediate and difficult to diagnose problems.

**Comment by frankhereford** [comment]
I have extended the `/var` partition's XFS filesystem on `atd-data03` by 50 gigabytes. We've got a lot more space on there now:

```
[root@atd-data03]/home/herefordf# df -h | grep 'Filesystem\|vg0-var'
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg0-var    78G   22G   57G  28% /var
```

We have plenty more space to allocate as well, if needed:

```
[root@atd-data03]/home/herefordf# vgdisplay
  --- Volume group ---
  VG Name               vg0
  [snip]
  Alloc PE / Size       25778 / <100.70 GiB
  Free  PE / Size       66125 / 258.30 GiB
```

So much room for activities!

**Comment by chiaberry** [comment]
Closing since we are no longer using prefect
