### ISSUE TITLE
Update DTS Portal with HR New Hires - May 2023 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#11912]
Check HR new hires for previous month:
https://atd.knack.com/hr#manage-accounts/

Add all regular employees to DTS Portal as Viewer 

**For each regular employee on the manage accounts view, for the current month:**
- [ ] Go to DTS Portal Builder side > Accounts 
- [ ] Check to make sure the user isn't already in the system 
- [ ] Add new Account record, making sure the email is correct 
- [ ] Add password (this won't be used since the system uses SSO but Knack requires a password nonetheless for account creation) 
- [ ] Enter division information, checking from Teams or Delve if eneded 
- [ ] Set user role as Viewer
- [ ] Save/create account 
- [ ] List employee first name and initial in your comment to this issue.

Close out this issue when done! 

Susanne will take over this task starting May 2023.

**Comment by susannegov** [comment]
# 4/28
- Added 8 people to the DTS portal ( 1 was temp)
