### ISSUE TITLE
"Unable to Connect" error when Lance and Allyson tried adding EDP "Corridor Retiming" dataset to PowerBI

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11918]
**Describe the bug**
Lance is trying to add the [Corridor Retiming dataset](https://datahub.austintexas.gov/Transportation-and-Mobility/Corridor-Retimings/bp5z-kciq) to PowerBI, but Lance receives an error message in PowerBI: 

![image](https://user-images.githubusercontent.com/61209591/229575967-6da2e7b6-123e-45c1-96ab-86e0ec0342bf.png)

**Screenshots**

**Device**
Desktop/Laptop

**How would you rate the impact of this issue?**
- [x] Severe — cannot perform work, no workaround

**Comment by susannegov** [comment]
Looks like authentication isn't working on PowerBI? Looking at my power BI Data Source settings I used Basic and the **Access this Dataset via OData** as the web link
![PBI image](https://user-images.githubusercontent.com/31259724/229904703-1dfca9c7-3533-4419-9c17-86446ff20cda.png)
![API Key](https://user-images.githubusercontent.com/31259724/229904757-ec38f704-84f5-4cd0-9503-011b6104cdb4.png)

Username is API Key ID
Password is API Key Secret

**Comment by KaroEngstrom** [comment]
**T 4/11/23** 
- Lance sent a message via Teams: he has created the API Key but needs help connecting via Power Query
- I added @susannegov to the conversation and she will help Lance connect

**Comment by susannegov** [comment]
Lance shared his screen with me and I was able to walkthrough connecting to the corridor retiming dataset using the API Key in PowerBI.

**Comment by susannegov** [comment]
# 4/26
Allyson reached out today on Teams about trying to get the key working. Didn't realized she was on the ticket initially so reopening this for a quick troubleshoot

**Comment by susannegov** [comment]
Allyson shared her screen with me and I was able to walkthrough connecting to the corridor retiming dataset using the API Key in PowerBI.
