### ISSUE TITLE
[Enhancement] Add / update milestones for new AMD templates

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#11919]
In order to complete https://github.com/cityofaustin/atd-data-tech/issues/11863, the following changes are needed to the `moped_milestones` table:

### Drop columns
- `milestone_average_length`
- `required_milestone`

### Add a new column:
- `is_deleted` (`not null default false`)

### Update Moped editor to filter milestones 
- User can only select milestones where `is_deleted = false`

### Rename milestones

milestone_id | milestone_name (current) | milestone_name (new)
-- | -- | --
36 | FDU and Task Orders created including Signs and Markings | Financial approval (FDU/TK)
40 | Contractor DO created | Work authorization (DO)
43 | Power has been installed | AE power complete
50 | Verification deficiencies have been addressed | Deficiencies addressed
51 | Signal turn on | Signal turned on / asset updated
44 | Cabinet ready to be set | Cabinet / Battery Backup System terminated

### Soft delete milestones

milestone_id | milestone_name (current)
-- | --
46 | Deficiency list created
45 | Heads installed and tested
48 | Detection has been installed and tested
49 | Communication installed and functional
52 | Burn in period

### Create new milestones

milestone_name (new) | related_phase_id
-- | --
AMD power construction complete | 9
Arms hung / cabinet ready to be set | 9

**Comment by chiaberry** [comment]
@johnclary the second new milestone in the list to add has the same milestone name as the last edit in the rename milestones, (Cabinet / Battery Backup System terminated). Should it be added and leave milestone 44 as is, or skip adding it?

**Comment by johnclary** [comment]
@chiaberry my bad—the new milestone that needs to be created should be called `Arms hung / cabinet ready to be set`. i updated the issue accordingly.
