### ISSUE TITLE
[DTS Gitbook] Update steps Warehouse Inventory - Updating Journal Vouchers (JV) info

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#11921]
https://atd-dts.gitbook.io/atd-knack-operations/warehouse-inventory-updating-journal-vouchers-jv-information

Update step 4 to include: 

Import a CSV values
Import headers

Yes update existing
TXN IN matches Transaction ID

If no matching records found to update?
Skip the row and do nothing

Map columns
Journal Voucher ID
Journal Voucher Date

**Comment by susannegov** [comment]
Made a change request on gitbook. @KaroEngstrom if the changes look good, may I submit "Merge" and close the request?

**Comment by KaroEngstrom** [comment]
Susanne merged the draft.

Great updates @susannegov 🙌
