### ISSUE TITLE
Digitize Confidentiality Agreement 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1193]
Replace [this](https://drive.google.com/open?id=1XdZIoEqpjQNHTNhTS4NiIAt24kC5aGkf) with a simple form in ATD Forms.

**Comment by dianamartin** [comment]
@amenity I did the thing. You're email address to the forms app will allow you to see this page, I gave you the new user role. 



![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/beedc83a-27fe-474b-b371-22cdcbcf0d25)

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/3c2b2397-b97a-49b5-b7bf-56fc73628d06)

**Comment by dianamartin** [comment]
I tested this on the 8" tablet we have and it definitely needs mobile optimization. It fields are so tiny and the signature is impossible to scribble on. 

Will have to show you some time.

**Comment by amenity** [comment]
Beautiful. (https://github.com/cityofaustin/atd-data-tech/issues/1197)
![screencapture-atd-knack-atd-forms-2020-01-15-18_23_15](https://user-images.githubusercontent.com/1463708/72482689-36291080-37c4-11ea-975e-ef9b3e9042bd.png)

Sticking this in the backlog: [Optimize mobile UX for Confidentiality Agreement Knack form]
