### ISSUE TITLE
Investigate and possibly improve address field contents in an open data portal resource

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#11935]
The following question was received in the Service Desk Inbox:

> Good afternoon, 
>
> I'm a student at the University of Texas at Austin and I am working on a group project for one of my courses that involves creating a web API that enables users to query a publicly available dataset. 
>
> While examining the exported traffic incident data from this [link](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.austintexas.gov%2Fapi%2Fviews%2Fdx9v-zd7x%2Frows.xml%3FaccessType%3DDOWNLOAD&data=05%7C01%7Ctransportation.data%40austintexas.gov%7Ca085087f3835420219b608db3534a7e6%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638162272520409549%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=u2U3T37hwUd1JM57o6GZ6uWaEmcJZtxrA0GFprAEFsc%3D&reserved=0) (in xml format) I noticed that some fields show unusual values. For example: 
>  
> Some values under the address field contain links to the [austin.gov](https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Faustin.gov%2F&data=05%7C01%7Ctransportation.data%40austintexas.gov%7Ca085087f3835420219b608db3534a7e6%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638162272520409549%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Pemp46DUA0vI%2FnOJtG%2F5cCMSkPwyzEFDLOpnJqpDPw0%3D&reserved=0) website. Upon clicking, I get an error message "path not found". 
> 
> I was just looking to understand why some addresses are listed this way, and whether I can handle these cases (in other words, still retrieve a human readable address) from my web API.
> 
>Best, 
>Kelechi E

This issue is to track the discovery around what may be wrong with the contents of that field and to fix the data, if possible. The open data portal dataset can be found here: https://data.austintexas.gov/Transportation-and-Mobility/Real-Time-Traffic-Incident-Reports/dx9v-zd7x.

**Comment by frankhereford** [comment]
@KaroEngstrom I've assigned this one to you because of your being the liaison for the open data portal, and if you think it should be reassigned, please do so.

**Comment by frankhereford** [comment]
@chiaberry and I took a quick peek at the dataset in question, and we were not able to find any instances of `austin.gov` in that field or any field, for that matter. I wonder if this citizen may be having trouble parsing the XML feed of the data, but that is nothing more than a guess. I do think that if that is the case though, it is out of our purview to provide that tech-support.

**Comment by KaroEngstrom** [comment]
**M 4/10/23** 
- after checking in with Frank late last week, I responded to the requester with the advice above, to check the way XML is being parsed from the feed.
