### ISSUE TITLE
[BUG] Missing Engineering Area on Annual Signal Retiming page

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11942]
Allyson R. 
AMD

Emailed 3/31
>Christiana and Diana – can y’all show me how to update/is it possible to update the field Engineer Area for the signals in the image below? I looked in both signal details and location details and it doesn’t appear this is an editable field. I’d like to update them from a blank field to Northeast.

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/0c108ee0-0ae1-4f19-8693-183f77da3284)

Signals Missing Engineering Area

- [x] 437
- [x] 438
- [x] 453
- [x] 522
- [x] 624

**Comment by ChristinaTremel** [comment]
Check with Allyson and Brian to determine who manages the ETJ in the Wells Branch Area (currently, no signal engineer is assigned to that area).
![image](https://user-images.githubusercontent.com/61209591/230137096-53d4f50a-722a-4a43-89b0-a988639d8da4.png)

![image](https://user-images.githubusercontent.com/61209591/230137327-78dc516c-7326-4776-9e3b-be44e586f63d.png)

**Comment by ChristinaTremel** [comment]
Need to assign these signals to the NORTHEAST Engineering Area.

**Comment by andrewshensky** [comment]
@dianamartin Does the entire 2mile ETJ need to be used or do adjustments just need to be made for the Signal Engineer Area to include these signals?

**Comment by dianamartin** [comment]
@andrewshensky I don't think the whole 2 mi ETJ is needed, just for that `Northeast` corner

**Comment by andrewshensky** [comment]
I have expanded the Signal Engineering Area in the Northeast corner. This data has been updated in maint and pushed to DM. I will submit a ticket to CTM to see if they can go ahead and pushed that data to AGOL, so it will be reflected prior to the next update cycle

**Comment by ChristinaTremel** [comment]
Checked the [TRANSPROTATION_signal_engineer_areas ](https://austin.maps.arcgis.com/home/item.html?id=a5e9ead2ee7d49cca9bd7d64747730d2) in AGOL and saw the Wells Branch ETJ area added to the polygon. QCed the signal ID's noted in Data Tracker above in Allyson's request and they now have `Engineer Area = NORTHEAST`, as requested.

Messaged Allyson: 
> Hey! Just checked and the Wells Branch Corridor signals are now updated with the NORTHEAST Engineer Area!

She responded: 
> thank you!!
