### ISSUE TITLE
[Bug] VZE Users page only display last 50 users

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#11940]
The Users in VZE show that there are 50 active users with the last person logging in 2/23/23, which was approximately 6-weeks ago. 

Something is preventing Users from showing past 50, as well as any inactive Users. 

This bug was discovered when trying to add a User back on who had failed to login after 3 attempts. See #11939

#### Acceptance criteria
- Find out why only 50 records are showing
- Where inactive Users are
- If there's a correlation between Users who have logged in in the last 6-weeks and if that's why they're showing up in the top 50
- Show all records active or inactive

**Comment by mddilley** [comment]
Here are those notes that I promised. We had a [recording of a skill share on this](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/dev-skillshares/authentication-with-auth0-and-cognito) but that looks like a dead link now. So, I started some documentation [here](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/vision-zero-crash-database/user-management) to start capturing these details again. Happy to pair on any aspect of this one and expand on the documentation as well!
