### ISSUE TITLE
Add "Corridor Name" field to Corridor Retiming EDP

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#11953]
For Lance to build out the PowerBI dashboard, he is needing the "signal corridors" field included on the [Corridor Retiming](https://datahub.austintexas.gov/Transportation-and-Mobility/Corridor-Retimings/bp5z-kciq) EDP dataset.

**Comment by ChristinaTremel** [comment]
@KaroEngstrom to help Lance with the Dashboard he's building with the Corridor Retiming EDP, he's needing this additional field added.

We talked about this in the Sprint Review last week, and you had mentioned that we might not need Dev assistance on this request because we are just adding a field, not modifying.

**Comment by KaroEngstrom** [comment]
## T 4/11/23
- this request is related to #11181 
- locations from that issue: 
    - new page to house this view [in the private API views](https://atd.knack.com/amd#signal-queries/)
    - the new [Corridor Retimings page and table](https://atd.knack.com/amd#signal-queries/corridor-retimings/) are live
    - added new asset in City Data Hub: [Corridor Retimings](https://datahub.austintexas.gov/Transportation-and-Mobility/Corridor-Retimings/bp5z-kciq)
    
- [ ] Add `signal corridors` field

**Comment by KaroEngstrom** [comment]
## W 4/12/23 
- checked in with @chiaberry yesterday and the field doesn't appear on the EDP side 
- we will need dev help to get the field to EDP
- this is the API table [Corridor Retimings] - the new field is populating with corridor name info on Knack side (https://builder.knack.com/atd/amd/pages/scene_1526/views/view_3814/table/columns)
- column/field info: 
![image](https://user-images.githubusercontent.com/100615928/231467936-1a13f607-d6f7-4e34-bb5e-63cc2012a155.png)

@chiaberry 
The dev request is to update the script to push the above newly-added column/field from the table to the [Corridor Retimings EDP dataset](https://datahub.austintexas.gov/Transportation-and-Mobility/Corridor-Retimings/bp5z-kciq).

**Comment by chiaberry** [comment]
I see the new corridor names column on the EDP, let me know if you need anything else from my side of it

**Comment by KaroEngstrom** [comment]
Thanks @chiaberry - looks great. 
Messaged Lance on Teams to let him know. Putting this on QA to await response.

**Comment by KaroEngstrom** [comment]
Closing this!
