### ISSUE TITLE
TPW Re-Organization Initiative 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#11964]
# 4/6 Meeting Notes
- During our "Quick Sync on Re-org" meeting
- Peggy was asked to be on a committee of people to help with the re-org, she has asked Kate and Karo to assist from the DTS team.
- Peggy told Susan D. 
  - will put in Distribution List request through Scott so he can create SN tickets

**Comment by KaroEngstrom** [comment]
## Week of April 3-7, 2023 
- created a new Teams for TPW Reorg T 4/4
- created a new SharePoint site for TPW Reorg T 4/4
- assisted Molly B. with document storage and sharing in SharePoint Th 4/6

**Comment by amenity** [comment]
This has already spawned enough freestanding issues - I don't think we need to keep it open.

**Comment by dianamartin** [comment]
@amenity I have two large epics that this is associated to. Please keep it open.

**Comment by amenity** [comment]
Spoke with @dianamartin, and we agreed it makes sense to remove outstanding issues from this epic and close it.
