### ISSUE TITLE
PSM Portal Help Text on Located in Local or National Historic District? (LP) - (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#11972]
### Add help text so customer can figure out how to answer this info, 

**Acceptance Criteria**

- The new info created in #11932 needs to be displayed in Portal during the application phase. 
- The following help text needs to be displayed below the info field. 
-- Go to the Property Profile map, expand the "Zoning" layers section, and select all layers in the "Historical" subsection
- The "Property Profile" part of the help text needs to be a hyperlink that links to the URL provided below. 
-- https://maps.austintexas.gov/GIS/PropertyProfile/

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Test , but helptext is not visible . Analysis in progress

**Comment by Lpriya-LIT** [comment]
@vschandramouli Could you please check with Kyle whether the helptext looks good, attached screenshot

@Nadin-Nader

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/457b49d4-8b7a-4589-b667-b83a9b0a561e)

**Comment by Nadin-Nader** [comment]
Sent Message via TEAMS Channel to Kyle asking him to UAT this on TEST. Waiting on Response

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder Kyle responded and would like to make 2 minor additions to this:

> [11:23 AM] Kampe, Kyle
>     Two minor comments on this one:
> 
> 
> 
> 	
> Can we either have the newly added text be a smaller font size or indented with a bullet point? Either of these would more clearly identify it as a sub-field of the "Located in Local/National Historic District" field
> 
> Can there be a space in between the words "Profile" and "map"?

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/f0dccd28-6615-46b8-bec6-de110fc1dbf5)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Ready for UAT on Test

**Comment by Nadin-Nader** [comment]
Sent message to Kyle asking him to UAT this on TEST

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Kyle has approved this to go to PROD. Please send to be deployed and let me know the TASK number

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes Promoted to Prod, Ready for UAT

**Comment by Nadin-Nader** [comment]
Sent Message to Kyle asking him to UAT this on PRO. Awaiting Response

**Comment by Nadin-Nader** [comment]
Closing, as Kyle has approved this on PROD
