### ISSUE TITLE
Develop executive sponsor relationship for Dash - Finance

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#11985]
@maccallump scheduled meeting with Anthony S. on 4/26/23
@Charlie-Henry will refresh Dash w/ latest financial data & ask Erin W. to QC
@katelunceford will develop a survey to go through during the meeting w/ Anthony

**Comment by amenity** [comment]
@maccallump - talking with @katelunceford and @Charlie-Henry and proposing we should push back next week's meeting with Anthony since Kate has no capacity to prep. How do you think we can/should keep this moving forward ...
