### ISSUE TITLE
Update the traffic reports publication script

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#11997]
https://github.com/cityofaustin/atd-data-deploy/blob/production/config/scripts.yml#L279

Move it out of the atd-data-deploy legacy orchestration and into prefect. (using the atd-knack-services script perhaps)

**Comment by johnclary** [comment]
https://github.com/cityofaustin/atd-prefect/blob/main/flows/atd-traffic-incident-reports/traffic-incident-reports.py
