### ISSUE TITLE
Add e-scooter-rider to VZV map

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12013]
![Screen Shot 2023-04-12 at 4.02.07 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/1989d738-efc8-432b-a4f3-f62741cd4197)

**Comment by chiaberry** [comment]
i'm watching the most recent vz release recording, and I hear that Xavier wanted the label on the travel mode chart to be "E-Scooter Riders" (https://github.com/cityofaustin/atd-data-tech/issues/12005), should the map also be updated to say "E Scooter Riders" ?
