### ISSUE TITLE
Remove micromobility device flag from Flags table

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12012]
Companion to Issue: Add micromobility device to Units table #11324

Once Xavier has manually updated the flags in VZE, remove the micromobility device flag Flags table.

![Screen Shot 2023-04-12 at 3.41.11 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/9d36f011-6112-48a5-867c-a2e85892bad9)

**Comment by xavierapostol** [comment]
I have updated all of the micromobility crashes to have the correct unit designation. Please move forward with the removal of the `crash` table field `micromobility_device_fl`. Thanks!

**Comment by tillyw** [comment]
thanks @xavierapostol !
