### ISSUE TITLE
Look into performance improvements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1203]
Try removing reporting fields and see if Scheduler interface goes faster.

**Comment by SurbhiBakshi** [comment]
Created a Test environment by making a copy of the Production app, and deleted fields that were created for reporting from the assignment and officer assignment objects. 
Tested the form in both the Production and Test app. https://docs.google.com/spreadsheets/d/12q4fwcAJwhiZcahvUvYh1PPlEblPh346NulCiPBmTXA/edit?usp=sharing

**Comment by amenity** [comment]
@SurbhiBakshi - wow, this is dramatic. Thanks for testing. How do you feel about making these changes in Production?

**Comment by amenity** [comment]
@SurbhiBakshi - maybe we do #1235 before implementing these changes in Production?

**Comment by SurbhiBakshi** [comment]
@amenity , agree with the comment above. Thanks for creating that issue!
