### ISSUE TITLE
[Enhancement] Create database view to associate level 5 polygons with crash records

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#12060]
Currently, we only associated level 1-4 locations with crashes. This group of locations is grouped together by the value `1` in the `location_group` column in the `atd_txdot_locations` table. Level 5 locations are grouped together by having the value `2` in the `location_group` column. 

The crash location association is done in two places (shown in diagram below):
- Hasura trigger that fires on CR3 and non-CR3 crash record insert or update and tries to drop a location ID into the `location_id` field of a crash record
- `atd_visionzero_reassociate_missing_locations_production` ETL that tries to associate crashes without `location_id` with locations nightly

After speaking with Xavier and Frank, we are now looking to open up crash location association to level 5 polygons. This would work by first applying criteria described in https://github.com/cityofaustin/atd-data-tech/issues/11368 but is open to refinement.

A database view should be created that computes what location a crash associates with based on the current latitude/longitude of the crash. This would replace the Hasura triggers and ETL process described above. This could also end up being a materialized view that is refreshed with a daily job. We could also created field that empowers the VZ team to designate a crash belongs in a level 5 polygon that would short circuit the view and force a crash into level 5 (flag editable in VZE). h/t Frank

This view would cover the work that was scoped in the following issues since the existing code looks for crashes associated with a single location view shown in the UI.
https://github.com/cityofaustin/atd-data-tech/issues/11846
https://github.com/cityofaustin/atd-data-tech/issues/11847
https://github.com/cityofaustin/atd-data-tech/issues/11965

<img width="1394" alt="Screenshot 2023-04-19 at 2 41 56 PM" src="https://user-images.githubusercontent.com/37249039/233182734-4f488f40-16fc-40b6-87c8-758ad8442c09.png">

**Comment by patrickm02L** [comment]
@XavierApostol :eyes

**Comment by johnclary** [comment]
i think our process has changed enough where this can be closed. there are some related issues (including ones Mike has linked to here) which will surface whatever shortcomings the process has in a post-new-data-model world 👍
