### ISSUE TITLE
[Enhancement] Implement schema change detection in VZ ETL process

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12069]
## Description

With CRIS updates, new fields get added to the schema. We need to update the VZ ETL to detect a change in the future.

Reference this [mention in PR 71]( https://github.com/cityofaustin/atd-prefect/pull/71/files#r1172747014).

> Curious what your thoughts about having a known list of schemas (2018, 2023) that we check for here, and, if there is a new one, then raise an error? I don't imagine a new one coming along soon, but who knows!? Could be a way to catch a change in the future.
> 
> It also could be good to drop a comment of the known csv filename like extract_2023_20230419092605_crash_20230418_HAYSTRAVISWILLIAMSON.csv somewhere as an example.

## Requirements
- Modification to the existing VZ ETL process to include schema version detection
- Capability to raise alerts or errors when an unknown schema is detected (potentially in Slack)

## Note
- Companion Issue to #15263

**Comment by patrickm02L** [comment]
@frankhereford I remember you claiming this Issue last Sprint Planning, but for some reason you didn't get assigned. I've added you to this Issue.

**Comment by johnclary** [comment]
The new data model addresses this in the following ways:
- It strictly enforces foreign key relationships on lookup tables, so the ETL will fail if CRIS tries to insert an unsupported value. 
- We explicitly define each column in the CRIS extract that we want to import. 

So the situation is that schema changes will either break our ETL or be ignored until requested by VZ staff. So I think we're covered wrt to change detection 🤷
