### ISSUE TITLE
Add Tech Surcharge to Street Impact Fee Contestment 50500 (Added to 11314)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12063]
Fee code 50500 **Street Impact Fee Contestment** should insert with the tech surcharge. 
- Applies to SIF folder
- User will manually insert the fee by using the 'Run Fee Procedure' feature on the fee tab. 
- The tech surcharge should insert with the fee

**Comment by Nadin-Nader** [comment]
This has been added to card #11314

**Comment by Nadin-Nader** [comment]
This was added to #11314 and is approved for PROD deployment. Closing
