### ISSUE TITLE
Enhance views with computed fields

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12082]
Companion to #11762

## Description

This will allow us to state of related records to overide the data received from CRIS based on changes to related records made by VZ.

We'll need to look through the 300+ fields in the VZDB, and identify which fields are candidates for computation (estimate 20).

## Notes

An example would be to compute the is_fatal flag in the crashes table when a related persons injury outcome is changed to fatality.

The `is_fatal flag`, in this case, had become out-of-date, but we can not expect CRIS to send us an updated value because the change happened downstream in our system from the VZ edit.

**Comment by frankhereford** [comment]
This issue is blocked by 11830, and it has a pretty clear deliverable: A combination of scripts or SQL commands that install the computed fields in the `ldm` schema during roll out.
