### ISSUE TITLE
Index the VZ schema

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12088]
We need to add indexes to the data model. A number of indexes have already been defined, and are currently tracked in [this file](https://github.com/cityofaustin/atd-vz-data/blob/73d924e253a78c4f608f22ac28fa58bef13e7f2e/atd-toolbox/data_model/python/sql_templates/indexes.sql).

The remaining task at hand is to evaluate various query and ETL performances and add additional indexes as needed. This includes crash, unit, and people tables, as well as our lookup tables.

**Comment by frankhereford** [comment]
I think this one breaks down into two issues, 1 for the core tables `crashs`, `units`, `persons`, `primarypersons` and then another for the lookup table system indexing / performance evaluation

core tables (must be completed first):

* ✅ Extract the indexing structure out of the existing VZ database as SQL commands
* ✅ Modify the SQL to apply it to the `cris` schema
* [ ] Modify a copy of the SQL for the `vz` schema
* [ ] Evaluate what indexing is no longer useful or is now missing based on the known queries that will be issued on these tables (the views)
* [ ] Write a script to create the indexing during roll out.

lookup tables:
* [ ] evaluate if indexing is required
  * [ ] Write a view for the VZV dataset to test this
* [ ] If required, write a script to create the needed indexing during roll out.

**Comment by johnclary** [comment]
I've updated the issue description and moved this into the backlog. I think it will be best to hold off on further indexing until we have a more complete working version of the VZE as well as our refactored ETLs: because both of these dependencies will allow us to better evaluate what indexes are needed.

**Comment by johnclary** [comment]
This work was completed as part of: https://github.com/cityofaustin/atd-vz-data/pull/1501. The current list of indexes applied during the migration is [here](https://github.com/cityofaustin/atd-vz-data/blob/6d42f51ebe70e078a5ab9fec0fa10ed0eec85264/atd-toolbox/data_model/python/sql_templates/indexes.sql).

There certainly may be more indexing added in the future but this can be closed.
