### ISSUE TITLE
Update ETLS to use LDM

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12087]
Vision Zero ETLs:

* [ ] ~AFD Import ETL~
* [ ] ~CR3 Narrative OCR and Diagram Extraction~
* [x] CRIS Crash Import
* [ ] ~EMS Import ETL~
* [ ] ~Refresh DB Permissions for Read Replica~

**Comment by chiaberry** [comment]
Just want to note that issue 11731 is to move the script from prefect 1 to airflow 2, I am not sure how much of it needs to be updated to be able to interact with the LDM.

**Comment by patrickm02L** [comment]
All but the CRIS crash import requires none of very little LDM compatibility work. For purposes of clarity this Issue will pertain to the PR 1240.
