### ISSUE TITLE
Add new columns from the updates to CRIS since we first created the VZDB

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12084]
- [x] Get new columns added by CRIS
- [x] update all the lookup tables from CRIS 26.0
- [x] check to see if lookup values IDs have changed

Frank will write a script to identify the lookup tables from the 12,000 values that exist.

**Comment by frankhereford** [comment]
# VZDB Lookup Tables

## Overview
There are 307 records in our lookup tables which have an outdated textual description for their record and need to be updated.
There are 415 records which are missing from our lookup tables and need to be added.
There are 9 lookup tables which are entirely missing.

### Missing lookup tables:
atd_txdot__autonomous_level_engaged_lkp
atd_txdot__autonomous_unit_lkp
atd_txdot__e_scooter_lkp
atd_txdot__pbcat_pedalcyclist_lkp
atd_txdot__pbcat_pedestrian_lkp
atd_txdot__pedalcyclist_action_lkp
atd_txdot__pedestrian_action_lkp
atd_txdot__rpt_autonomous_level_engaged_lkp
atd_txdot__rpt_autonomous_unit_lkp

### Record with meaningfully changed descriptions, ie, a reused ID value ☠️

#### Contributing Factors
❌ Id 79 found in atd_txdot__contrib_factr_lkp has a description mismatch:
      CSV Value:  FAILED TO SLOW OR MOVE OVER FOR VEHICLES DISPLAYING EMERGENCY LIGHTS
       DB Value:  DROVE ON IMPROVED SHOULDER

#### Median types
❌ Id 2 found in atd_txdot__median_type_lkp has a description mismatch:
      CSV Value:  UNPROTECTED
       DB Value:  POSITIVE BARRIER

❌ Id 3 found in atd_txdot__median_type_lkp has a description mismatch:
      CSV Value:  CURBED
       DB Value:  UNPROTECTED

❌ Id 4 found in atd_txdot__median_type_lkp has a description mismatch:
      CSV Value:  POSITIVE BARRIER - UNSPECIFIED
       DB Value:  ONE-WAY PAIR

#### Surface Type

❌ Id 1 found in atd_txdot__surf_type_lkp has a description mismatch:
      CSV Value:  CONTINUOUSLY REINFORCED CONCRETE
       DB Value:  ROAD IS UNPAVED

❌ Id 2 found in atd_txdot__surf_type_lkp has a description mismatch:
      CSV Value:  JOINTED REINFORCED CONCRETE
       DB Value:  LOW TYPE BITUMINOUS SURFACE-TREATED

❌ Id 3 found in atd_txdot__surf_type_lkp has a description mismatch:
      CSV Value:  JOINTED PLAIN CONCRETE
       DB Value:  INTERMEDIATE TYPE MIXED

❌ Id 4 found in atd_txdot__surf_type_lkp has a description mismatch:
      CSV Value:  THICK ASPHALTIC CONCRETE, OVER 5.5 INCHES
       DB Value:  HIGH TYPE FLEXIBLE

❌ Id 5 found in atd_txdot__surf_type_lkp has a description mismatch:
      CSV Value:  MEDIUM ASPHALTIC CONCRETE, 2.5 - 5.5 INCHES
       DB Value:  HIGH TYPE RIGID

❌ Id 6 found in atd_txdot__surf_type_lkp has a description mismatch:
      CSV Value:  THIN ASPHALTIC CONCRETE, UNDER 2.5 INCHES
       DB Value:  HIGH TYPE COMPOSITE

**Comment by patrickm02L** [comment]
Showed the changes to Xavier 4/25/23, he gave us sign off. In grooming 4/26/23, we decided that it would be okay to make the updates now. 

@frankhereford you have the green light to go ahead and update the production VZDB with the updated lookup tables.

**Comment by frankhereford** [comment]
The script to do this work is ready, and it's able to execute the required commands. It turns out that we also have varchar fields in the database that are too short for the values that we get off CRIS, so I'm going to alter those columns so we can hold the whole description required.

**Comment by patrickm02L** [comment]
Execute 🚀

**Comment by frankhereford** [comment]
Thanks @patrickm02L!

I just now finally got the file ready after finishing [the lookup table inspector script](https://github.com/cityofaustin/atd-vz-data/blob/refactor-vze-for-ldm/atd-toolbox/materials_from_ldm_conversion/inspect_lookup_table_data.py) just now. 

Here's [the set of changes](https://github.com/cityofaustin/atd-vz-data/blob/refactor-vze-for-ldm/atd-toolbox/materials_from_ldm_conversion/updates_to_production_db.sql) that is going to go into production tomorrow morning 1st thing. Thanks again for your help moving all this forward!
