### ISSUE TITLE
Onboard Adnan T.

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12096]
## Adnan T begins 4/25/23

- [ ] Invite to CTECC Tour

----
## Accounts 
~Submit a [CTM New Employee Request Form](https://atx.servicenowservices.com/sp?id=sc_cat_item_guide&sys_id=b714eb12db7a3f0021ccef92ca961972) for a COA network account, eAccess PIN/HR Portal, and phone~ 
- [x] Submit an "Active Directory - Update Existing User Network Account" - change of supervisor/title

- [ ] Submit a [CTM service request](https://atx.service-now.com/sp) to add to DTS Distribution Email Group:
 -- Add "First Last Name" to email distribution list "ATD Data and Technology Service" ([ATDDataTechnologyServices@austintexas.gov](mailto:ATDDataTechnologyServices@austintexas.gov)) 
- [x] Add to City of Austin Slack - austininnovation.slack.com 
- [x] Add to DTS Google Drive
- [ ] Add to [Gitbook](https://app.gitbook.com/@atd-dts/spaces)

- [ ] Add to [Austin Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members) 

- [ ] Upload headshot to ["Headshots" Drive folder](https://drive.google.com/drive/u/0/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G)

- [ ] Add to group slide and team slides [DTS Presentation Template Team section](https://docs.google.com/presentation/d/1tHKTfUgQ-uAXdRBkEdXqR7ryBo_LTU86IzQxo1gJoeA/edit#slide=id.gfd2da31025_0_6) 
- [ ] Update DTS group and team slides in the DTS Orientation presentation to reflect ☝️
- [x] Check w/ Diana/Amenity—if needed; we pay for seats
  - 1password
  - Miro
- [x] Invited Adnan to GitBook

### Hardware — DTS Systems Admin
- [x] Coordinate with DTS System Admin (Scott), make sure there is enough lead time for equipment to be acquired.
- [x]  Laptop

### Calendar invites
_Schedule or coordinate with the event owner_
- [x] First day: DTS Team Orientation — invite all leads, Peggy optional
- [x] First Week: DTS Product Ops — Coordinate w/ Amenity
- [x] Monthly Team Meeting

- [x] Sprints
- [x] Sprint Ceremonies — Planning, Grooming, Sync, Show & Tell

- [x] Biweekly 1x1

### New team member 
- [ ] Set up Cameron Road wifi: coa-atd-secure-wifi — password in 1password
- [x] [Log in to your City of Austin email](https://outlook.office365.com/)
- [ ] [Set up your email signature](https://docs.google.com/document/d/1OAoBll9rIl6XZq2uOShm5HCbHJboOt0SLP_wK6tjkEE/edit)
- [x] [Create a Google account for your Austintexas.gov email address](https://atd-dts.gitbook.io/atd-staff-resources/general/using-google-as-a-city-employee)
- [x] If you don't have one already, [create a Github account](https://github.com/join) 
- [x] Install [Zenhub Browser Extension](https://www.zenhub.com/)
- [x] Post your [daily standup in Slack](https://atd-dts.gitbook.io/wiki/slack#daily-stand-up)
- [x] [Set yourself up for remote work](https://atd-dts.gitbook.io/atd-staff-resources/working-remotely/getting-started)
- [ ] Upload a headshot [here](https://drive.google.com/drive/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G) and add your title and preferred pronouns [here](https://docs.google.com/document/d/1gRjTic8FD3s-t0sVZhErAidMIAktU-0Vn2GYPpPcUeg/edit) (Google Drive access must be set up first)
- [x] [Create a Github issue](https://github.com/cityofaustin/atd-data-tech/issues/new) for adding yourself to the [DTS "About Us" webpage](https://austinmobility.io/about) (labels: Service: Dev, Type: Operations, Product: DTS Website) including the link to your photo and preferred pronouns
- [x] Familiarize yourself with the [DTS Wiki](https://atd-dts.gitbook.io/atd-staff-resources/)

**Comment by TracyLinder** [comment]
Hi @AdnanTaher can you please update the checklist above and let me know if there's anything else you need assistance with, or if we think we have you fully onboarded.

**Comment by dianamartin** [comment]
@TracyLinder I think we're okay to close this 😉
