### ISSUE TITLE
Configure Service Request Details | Customer page

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12100]
## Adding a page rule, hide menu
When a Service Request is "Completed" we do not want the user to be able to edit/re-submit this SR.
- On the Service Request (Customer) details page - `scene_360`
- [x] Add Page rule
  - When Status is "Completed", Hide "Requester Menu"
- [x] Hide menu: `scene_360/views/view_872/menu`

**Comment by susannegov** [comment]
# 4/28
- Added to existing page rule
    - When Status is "Completed", Hide "Requester Menu"
![image](https://user-images.githubusercontent.com/31259724/235199180-78dde82f-3877-4087-b6f6-126326413763.png)

**Comment by dianamartin** [comment]
5/16
Christina and I reviewing this page to see if all the rules are accurate

**Comment by ChristinaTremel** [comment]
# 5/16 Meeting
Diana and I reviewed the Finance admin service request details page rules and noticed these needed to be added: 

- [ ] BGEX - Editable
- [ ] FDU - Non-Editable
- [ ] IET - Non-Editable
- [ ] JV - Non-Editable
- [ ] TK - Non-Editable
- [ ] TK - Editable
- [ ] Other - Editable
- [ ] Other - Non-Editable

**Comment by dianamartin** [comment]
Closing, this issue because we intend to show this page during our demo with Finance staff. They will most likely need more changes on their Admin page and not the requester one.
