### ISSUE TITLE
Mitigation Map Data Review and Project Sync - 4/25

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12101]
# 4/25
**Participants:** Chrispin, Andrew, Susanne, Nelson, Diana, Drew
Unavailable: Tracy

## Project Status
- Last meeting, quick demo of dashboard
- Mapping side, have the vision for the web map visualization
- Dealing with point and linear data. Make those points and linear in display
  - buffer around the intersection point, on one layer v. having two layers
  - if there was a point, represent it by a line 
  - doing this improves the map query ability for user

## Admin back fill for Street Segments
- Nelson hasn't gotten a status update with Drew
- We called Drew into the meeting (4/25)

### Drew's Admin back fill status
Per page is `25 records`
- 39 pages to back fill - `975 records`
- 33 pages, down to 31 by the end of today
Drew says can get through 25 to 25 records
>Observation: Mitigation Location
>- same cross streets
>- mitigation project number 
>- same location 
>- example: one project, same mitigation location
>- comments, turn lane here.., signal lane here..
Estimated: 2 months more
- End of June for Geospatial work

## Demo Web Map
![image](https://user-images.githubusercontent.com/21112975/234377435-1c1722ae-0908-4147-a2f8-aa5efe6abeb3.png)
- 975 records
- Andrew: estimated 1 week of actual work once data is provided and finalized

## Next Meeting
- Nelson said Cody wants to see the map representation
- Might invite Cody to next meeting
- Suggested date: First week of June

**Comment by TracyLinder** [comment]
Next sync has been scheduled for 6/8
