### ISSUE TITLE
ETL street segment updater

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#12119]
Main issue: https://github.com/cityofaustin/atd-data-tech/issues/10901

ETL our street segment updater in Prefect

**Comment by chiaberry** [comment]
the atd-knack-services issue: https://github.com/cityofaustin/atd-data-tech/issues/11769

**Comment by Charlie-Henry** [comment]
ETL'd in Prefect, running every hour. Will open the mega-knack services PR soon
