### ISSUE TITLE
Implement standardized "DTS Service Request/Bug" button in all DTS apps (Knack)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12116]
This came up recently 4/26
David D.
SMO
>Thank you! Bookmarked for future use. Should I submit this as a ticket so your team can track this issue? 

>Just for feedback, it may be useful to include a link to the DTS Request page in the relevant Knack portals to help funnel these requests. I had no idea that we had a dedicated DTS request portal until now. Very good to know though! 

## Resources
- Pre-populate a form in Knack [article](https://learn.knack.com/article/z36i2it02b-how-to-use-url-variables-to-pre-populate-a-form)

App Name | DTS Form URL
-- | --
Finance and Purchasing | https://atd.knack.com/dts#new-service-request/?view_249_vars=%7B%22field_390%22%3A%22Finance%20%26%20Administration%22%2C%22field_398%22%3A%22Bug%20Report%20%E2%80%94%20Something%20is%20not%20working%22%2C%22field_399%22%3A%22Finance%20%26%20Purchasing%22%7D

- Reference issue #6064
- Reference issue #5735
>Here's what is super frustrating, the encoder link the documentation included was changing spaces to + instead of %20.
`https://www.urlencoder.org/` <-- this link will change the spaces to `%20`
also I didn't include square brackets since the fields didnt appear to be connected fields, but i am not sure it made a difference with or without brackets

_{"field_390":"Finance & Administration","field_398":"Bug Report — Something is not working","field_399":"Finance & Purchasing"}_

[Google Sheet with Encoded URLs](https://docs.google.com/spreadsheets/d/19gEuwHazGUhPh_ve0Ux0EvQPxH1kyaBvEprv9Yw7rls/edit#gid=0)

**Comment by dianamartin** [comment]
# 7/6/2023
## Steps to build custom parameter

1. Produce `{"field_390":"Finance & Administration","field_398":"Bug Report — Something is not working","field_399":"Finance & Purchasing"}` - for every application (BUG REPORT)
2. need to create one for enhancement request
3. https://www.urlencoder.org/ (<-- this link will change the spaces to %20) to drop in 
4. Enter step 1 or step 2 into encoder
5. Add first part of url `https://atd.knack.com/dts#new-service-request/?view_249_vars=` to encoded result
6. Completed [URL](https://atd.knack.com/dts#new-service-request/?view_249_vars=%7B%22field_390%22%3A%22Finance%20%26%20Administration%22%2C%22field_398%22%3A%22Bug%20Report%20%E2%80%94%20Something%20is%20not%20working%22%2C%22field_399%22%3A%22Finance%20%26%20Purchasing%22%7D)
- `https://atd.knack.com/dts#new-service-request/?view_249_vars=%7B%22field_390%22%3A%22Finance%20%26%20Administration%22%2C%22field_398%22%3A%22Bug%20Report%20%E2%80%94%20Something%20is%20not%20working%22%2C%22field_399%22%3A%22Finance%20%26%20Purchasing%22%7D`

**Comment by ChrispinP** [comment]
Spreadsheet with all the URLs can be found in the description. URL tested and working for both Finance & Traffic Register.

I did an initial mockup in the [Traffic Register](https://atd.knack.com/traffic-register#service-request/dts-service-request/)

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/847b6e1f-e2b5-4d79-b52b-28884c3e2f1a)

**Comment by dianamartin** [comment]
# 7/18
Synced with team and we decided to go with this approach
Two menus 
- Bug
- Enhancement

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/18288c2d-b455-474d-af55-72995b470260)

**Comment by ChrispinP** [comment]
Updated Service Request page in Traffic Register
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/ba7c885c-db02-446c-81a9-1b5edbf5eadb)

**Comment by ChrispinP** [comment]
Service Request Page created for the following applications:

- [ ] AMD Data Tracker
- [ ] Finance & Purchasing Portal
- [ ] Human Resources Portal
- [ ] Parking Enterprise Portal
- [ ] Right of Way Portal
- [ ] Shared Mobility Portal
- [ ] Smart Mobility Portal
- [ ] Street Banners Portal
- [ ] SMD
- [ ] Traffic Register
- [ ] TDS Portal
- [ ] VZA

**Comment by ChrispinP** [comment]
Workgroups notified of the new Service Request Page:

- [x] AMD Data Tracker
- [x] Finance & Purchasing Portal
- [x] Human Resources Portal
- [x] Parking Enterprise Portal
- [x] Right of Way Portal
- [x] Shared Mobility Portal
- [x] Smart Mobility Portal
- [x] Street Banners Portal
- [x] SMD
- [x] Traffic Register
- [ ] TDS Portal
- [ ] VZA

**Comment by dianamartin** [comment]
# 9/26
Closing, we created a new issue for the communication part.
