### ISSUE TITLE
Add Engineering Areas to the FTT Index

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12125]
## Description
As a user, I want to be able to filter search results based on specific geographical areas such as Central, North, and South. Currently, the dropdown menu only includes "Search by Crash ID."
<img width="712" alt="Screen Shot 2023-05-09 at 1 16 23 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/5566727/44bb821d-a2ac-49b9-8ef9-3a9a6c514707">

## Objective
The objective is to enhance the search functionality by adding an "Search by Area" option to the field dropdown menu. This will allow users to filter search results based on specific geographical areas.

### UI
   - Add an "Search by Engineering Area" option to the field dropdown menu.
   - The "Search by Engineering Area" option should include the following values: Central, North, and South.
   - When the user selects an "Search by Engineering Area" option from the dropdown menu, the search input should allow the user to type in the desired area.
   - The search functionality should consider the selected "Search by Engineering Area" filter and return results that match the specified geographical area.
#### Mapping
   - Implement a geolocation feature that accurately locates the selected area on the [TRANSPORTATION_engineering_service_areas](https://austin.maps.arcgis.com/home/item.html?id=28c369f7ab534c64a26a646fca3fd6ec) map. 
      - [ArcGIS REST Directory](https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/TRANSPORTATION_engineering_service_areas/FeatureServer/0)
- 2 ways of deciding that the crash is in the area: on the fly, or trigger that assigns value to column when someone edits the crash location.
- Note: example of how we load [Council District into Moped](https://github.com/cityofaustin/atd-moped/tree/main/moped-toolbox/council_districts_load).
#### Export
- Include the engineering areas in the .csv data export.

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/05b3476f-88d1-463e-9dd2-a956a9505cd8)

## Notes

Mary V. sends out an email a week prior to the FRB showing (table below) what fatalities they'll review in their monthly meeting. 

She send it out a week early so that the Engineering Teams can make field visits based on the "Engineering Area" in advance of the meeting so they're ready to chime in with recommendations given their findings. 

![MicrosoftTeams-image (2).png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/bb221836-a8a8-48de-9c12-ff09c7b40b71)

**Comment by chiaberry** [comment]
- spin off another issue to get the polygons into a table
- this issue will tackle the triggers themselves and the fatalities search
