### ISSUE TITLE
Add 'Adnan' to the 'About Us' section

### ISSUE THREAD

**Issue by AdnanTaher** [cityofaustin/atd-data-tech#12131]
Adding Adnan to the DTS Website [About Us](https://www.austinmobility.io/about) section.

**Comment by TracyLinder** [comment]
@patrickm02L should this be assigned to you for the about us update, or is somebody else managing this?

**Comment by patrickm02L** [comment]
@AdnanTaher in order for me to add you to the DTS website About Us page, I need the following information:
- Please add your headshot to this [folder](https://drive.google.com/drive/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G)
- What are your pronouns?
- What is your job title?
