### ISSUE TITLE
Update VZE to use IDs instead of Textual Descriptions for picking injury badge colors

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12135]
Please see https://austininnovation.slack.com/archives/CM9MK950S/p1682696549485749. The recent changes to various lookup table descriptive values breaks the picking of the correct color for the injury severity badge in the people listing on the crash pages in the VZE.

**Comment by roseeichelmann** [comment]
just pasting Xavier's color preferences here:

Killed = Red
Suspected Serious Injury = Orange
Suspected Minor Injury = Orange
Possible Injury = Yellow
All other Injury Types = Gray
