### ISSUE TITLE
Update the "Add Inventory Item" Form for New Technician Workflow

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1214]
We need to source from a new "add item" form for adding inventory items to a work order. This form is very similar to the existing form, except for the `Source` field. Importantly, this form triggers additional Knack API calls upon submission. These triggers are defined in the Knack app.

New form API details:
- Scene: `scene_297`
- View: `view_2661`

## Fields
- `Item`: `field_513`
- `Quantity`: `field_524`
- `Source`: `field_3440` : Choices: { `Warehouse Inventory`, `Working Stock`, `Truck Stock`, `Other` }
- `Comment`: `field_3493`

**Comment by johnclary** [comment]
@mddilley hopefully this one is pretty straightforward, but let me know if you have questions/concerns.

**Comment by mateoclarke** [comment]
Removing MD from this task, is this issue closeable?
