### ISSUE TITLE
Copy ROW to Create a New TEST Environment for Conflict/Shared Request Updates 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#12140]
## M 5/1/23
- [x] Copy ROW as a new TEST environment 
- [x] Update DTS Portal - Applications 
![image](https://user-images.githubusercontent.com/100615928/235484985-3977dd78-2250-4e86-b5e6-86ce1cc7736d.png)
- [ ] Check w/ team on what old test environments are not needed. 
- [ ] Delete any test environments that are not needed and update DTS Portal records

**Comment by susannegov** [comment]
App > Gear > Copy > 
- **Uncheck** Pause Tasks
- **Check** Copy records
- **Check** Copy Tasks

**Comment by KaroEngstrom** [comment]
[Gitbook documentation](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzNSSXajDFpzOv2IhIv/knack/copy-an-application)

**Comment by KaroEngstrom** [comment]
Chrispin cleaned up the TEST environments 7/10/23. Closing.
