### ISSUE TITLE
Update injury severity badgeColor in the VZE People tab

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12145]
Referencing [comment](https://github.com/cityofaustin/atd-data-tech/issues/12135#issuecomment-1528014523) on #12135

Update the injury severity color highlights to provide more differentiate/contrast. 

![Screen Shot 2023-05-01 at 10.28.24 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/b14f12d8-5c77-4dad-8d12-2f6da1048048)

## Current 

- Fatal Injury = Red
- Suspected Serious Injury = Yellow
- Suspected Minor Injury = Yellow
- Not Injured = Blue
- Unknown = No color

## New

- Killed = Red
- Suspected Serious Injury = Yellow
- Suspected Minor Injury = Yellow
- Possible Injury = Blue **
- Unknown = No color
- All other Injury Types = Grey
   - Not reported
   - Not injured
   - Reported invalid

** Discussion in Dev Sync 4/28/23 recommended this status as blue, rather than initial yellow choice.

**Comment by chiaberry** [comment]
use the existing design system's color palette

**Comment by xavierapostol** [comment]
> 

The same color as a "Non-Injury" or "Unknown Injury"
