### ISSUE TITLE
Create an `Edit Inventory Item` Page/Form

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1215]
We need to create a new page/form for editing inventory items. This page should be accessible from the inventory items table, as described [here](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/1212).

## API Info
- Scene: `scene_1068`
- View: `view_2669`

## Fields

- `Item`: `field_513`
- `Quantity`: `field_524`
- `Source`: `field_3440` : Choices: { `Warehouse Inventory`, `Working Stock`, `Truck Stock`, `Other` }
- `Comment`: `field_3493`

Then redirect to work order page on submission.

**Comment by mateoclarke** [comment]
Removing MD from this task, is this issue closeable?

**Comment by amenity** [comment]
@johnclary - should I reassign this to @mddilley? 😉

**Comment by johnclary** [comment]
😆 

These should be good to close I will take a closer look.

**Comment by amenity** [comment]
@johnclary - ping. 🔔
