### ISSUE TITLE
Update UI to make unit description and vehicle body style editable

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12161]
companion to #11324

![Screen Shot 2023-05-02 at 2 18 18 PM](https://user-images.githubusercontent.com/5566727/235766142-872b7fcb-933f-4a60-817b-1f203bd7624f.png)

**Comment by tillyw** [comment]
closed with https://github.com/cityofaustin/atd-vz-data/pull/1223
