### ISSUE TITLE
Create a `Cancel Inventory Item` Page/Form

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1216]
We need to create a new `Cancel Inventory Item` page/form. This form should be accessible from the inventory items table, as described [here](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/1212).

## API Info
- Scene: `scene_1068`
- View: `view_2670`

## Fields

This form has *no* fields, it should display the text: "Are you sure you want to cancel this inventory request?". There are form submission rules in Knack that take care of the appropriate record updates.

The form should display two half-width buttons:
- "Yes"
- "No"

**Comment by mateoclarke** [comment]
Removing MD from this task, is this issue closeable?
