### ISSUE TITLE
IT Support: Delete Flasher ID 219 because it's a duplicate of 220

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12171]
# Karo's notes from 5/2/23
- Flasher ID 219 need to be deleted; created for the wrong location
- Jorge came in with the ask from him and Yvonne

**DETAILS**
LOC# LOC23-022490
Flasher ID 219 is incorrect and should be deleted.
Flasher ID 220 is correct.

**Comment by dianamartin** [comment]
# 5/3
Reviewed Flashing Beacon list and 219 and 220 are identical. No other records are related to this. 
- [ ] Delete `BEACON_ID: 219`

**Comment by dianamartin** [comment]
@ChristinaTremel this has been completed, ready for review. [Filter](https://atd.knack.com/amd#flashing-beacons/?view_1454_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_1642%22%2C%22operator%22%3A%22higher%20than%22%2C%22value%22%3A%22218%22%2C%22field_name%22%3A%22ATD_BEACON_ID%22%7D%2C%7B%22match%22%3A%22and%22%2C%22field%22%3A%22field_1642%22%2C%22operator%22%3A%22lower%20than%22%2C%22value%22%3A%22221%22%2C%22field_name%22%3A%22ATD_BEACON_ID%22%7D%5D%7D&view_1454_page=1)for IDs: 219 and 220.

**Comment by ChristinaTremel** [comment]
Reviewed and saw that 219 was deleted. Let Jorge know that the duplicate beacon was deleted as well.
