### ISSUE TITLE
Move Page Titles to Top Nav

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1218]
To save vertical page space, let's move the page titles to the top of the screen, centered between the nav buttons and the account settings button.

For example, here's the proposed change  to "My Work Orders:
![Screen Shot 2020-01-20 at 12.37.15 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/1d346380-71a1-4a6a-b5b6-a3b0e5aa1bb6)

**Comment by JaceDeloney** [comment]
Ad discussed, please hold off on renaming the page titles at this time. Let's do some testing with users before we make that change. We will create a separate issue to track renaming the titles.
