### ISSUE TITLE
Add new values to folder info Event Type 75160 (SR) (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12187]
### Add two new values to folder info Event Type 75160
`OSE's # 2 Priority`

1. Sporting Event 
2. Concert

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to TEST under **SCTASK0315553**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to TEST, please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Verified in TEST, ready for UAT in TEST

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - #12187 PROD DP Submitted. Kindly review and create task id for me.

Commit ID: 16b77e954255

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have sent this to the DevOps CM Team to deploy to PROD under **SCTASK0319627**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  I Sent a message to Maria informing her that this is on PROD and ready for UAT. Waiting on Response

**Comment by Nadin-Nader** [comment]
Got confirmation from Maria and this is good to close
