### ISSUE TITLE
New Folder Process for ACE TCP Review on RW-Street Event (LP) - (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12186]
**Acceptance Criteria** 

- A new process needs to be added to RW folders of Street Event subtype with work types Arterial/ collector 50535 OR safety closure 50545
- The process should be named ACE TCP Review Process 
- The Default Assigned user for this Process will be 'ACE TPW Reviewer' user account. 
- The process needs to be inserted into the folder ~when Accepted attempt is made in Web Application Acceptance Process.~ during folder insert. 
- The process To Start Date will be the Date the process was inserted into the folder, and the process To End Date will be the Date value provided in Folder Info field 'Event Start Date'. 
- The Process needs to have the following attempts:
-- Approved
-- Returned
-- Withdrawn
-- Cancelled
- The Process needs to have the following Process Statuses: 
-- Approved 
-- Pending
-- Withdrawn 
-- Cancelled 

**The process attempts need to perform the functions provided below:**
•	Approved - Process Closed
o	Folder Status = No change
o	Process Status = Approved
o     Insert Ended Date in the Process

•	Returned - Process Stays Open
o	Folder Status = No change
o	Process Status = Pending

•	Withdrawn – Process Closed
o	Folder Status = No change
o	Process Status = Withdrawn
o     Insert Ended Date in the Process

•	Canceled – Process Closed
o	Folder Status = No change
o	Process Status = Canceled
o     Insert Ended Date in the Process

### OSE needs an additional review process for ACE TCP Review.
    1. To be added to RW-Street Event
    2. OSE has Engineer C who creates the TCPs, then an OCE reviewer reviews the TCP
    3. Sometimes the TCP review does go through ROW’s normal TCP review process, depending on circumstances and staff resources.

**Comment by vschandramouli** [comment]
Notes from scoping meeting with Maria - 

Name it ACE TPW Review Process 
RW- Street Event with work type Arterial/ collector 50535 OR safety closure 50545

Insert process when Approved attempt is made in Web Application Acceptance Process. 

Default Assigned User - ACE ATD Reviewer User

Attempts - 
Approved
Awaiting Update
Rejected
Withdrawn 
Cancelled 

Approved - 
Close the process with status Approved.  

Awaiting Update - 
Change Process status to Awaiting Update 

Rejected - 
TBD, potential email 

Withdrawn - 
Process status to Withdrawn 

Cancelled - 
Process Status to Cancelled.

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Configuration changes promoted to Dev and Test . 
Working on Coding related updates

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed coding changes and requested for Dev and Test Deployment
SCTASK0347871

**Comment by Nadin-Nader** [comment]
Update:

While testing this, Maria realized that the new process should also be inserted when a user (Reviewer) creates a new folder:

And realized it is ready to test. So I played around with it, we also need the process added when we create a new folder. It is not currently adding it... and I imagine its because it says "Insert process when Accepted attempt is made in Web Application Acceptance Process." which it is currently doing. Is it possible to update the code to have it added when we create a new folder please.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and requested for Dev and Test Promotion.
SCTASK0349030

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Dev and Test. ACE TCP Process will be inserted when the new folder is created.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Maria reached out and said this can go to PROD

**Comment by TracyLinder** [comment]
### UAT Approved for PROD
- Per Maria during today's prioritization meeting. 
- FYI @Lpriya-LIT

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader  Created Prod deployment request 
SCTASK0356584

**Comment by Nadin-Nader** [comment]
Sent Maria a message asking for her to UAT this on PROD. Waiting on Response

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Maria approved this on PROD. closing
