### ISSUE TITLE
LC Portal payments failing to update payment table

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12182]
### ROW has reported at least 2 recent examples of portal payments made online on the LC folder that didn't record on the payment tables. The bill remains outstanding. 

**Example 1** 

- Folder ROWID 13128037
- Bill # 7842894 for $192.40
- Payment posted on 4/27/23

----

**Example 2**

- Folder ROWID 11427855
- Bill # 7842858 for $192.40
- Payment posted on `unsure`

**Comment by TracyLinder** [comment]
### Notes

- Both payments are pending manual entry by TPW Finance.
- @Nadin-Nader i think this is ready for debugging. It's going On Deck waiting for assignment. 
- I will inform Kyle with ROW

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Analysis is in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - This issue resolved I believe, There was a recent online payment made on 05-11-2023 for LC Foldertype with a folderrsn's - 11308035, 12695495, 13140106 and 13140140

**Comment by TracyLinder** [comment]
Items have been fixed. When this happens again we will send the info to swapna with CTM for resolution.
