### ISSUE TITLE
Improve our reliability of cleaning the /tmp directory contents

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12206]
## Background

I was looking into modifying our CRIS import script, and I happened to do a `df -h` on `atd-data03`. I observed that we had filled up our `/tmp` directory, which is sized at a totally normal 1 gigabyte.

## Implications

When this happens, our ETLs, which rely on using this space as swap space, are unable to write out files to operate on.

## Caveat

I can't really put a finger on exactly which errors this would be causing, because I don't see anything along the lines of `out of disk space` anywhere, but there's just no way that not having swap disk space wouldn't cause major problems.

I guess it's not impossible that I just happened to catch it when it was < 1% full before it fell apart, so that can't be ruled out. 

## Actions

I cleaned up 90% of the `/tmp` directory yesterday, so that buys us time.

I think we should consider active monitoring of disk space and other machine vitals so we can have some historical information on how this happens.

We should also look closely at our flows (probably when we get on airflow 2) to make sure they don't leak data into /tmp or make sure that we don't pass down `/tmp` into them so it gets cleaned up with the container exists. 

## Urgency

Low, but when this happens again, it's a show stopper for a great many of our DAGs.

**Comment by chiaberry** [comment]
Closing because grafana monitoring is handling keeping eyes on atd-data03. will reopen if /tmp directory starts having issues again
