### ISSUE TITLE
[PEP] Delete Dispatch Resource Tracking logs - August 2023

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#12201]
Received automated reminder to delete dispatch resource tracking logs in Parking Enterprise Portal and reference the Dispatch Resource Tracking Log Archiving wiki

Ran filter on: https://builder.knack.com/atd/parking-enterprise/records/objects/object_12

Filter:
`Status` is `Marked for Deletion`
`CREATED_DATE` is `before` <one months ago>  (ex. if Today's date is 7/8/21, enter 6/8/21)

Total Records: 2557
To Delete: 2020
New Total: 537

**Comment by KaroEngstrom** [comment]
@susannegov Thanks for checking in with me about these yesterday; this one is yours and I don't need to be tagged in the next issue for November
