### ISSUE TITLE
Onboard Rachel W.

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12211]
Complete the onboarding for our CIC Developer Fellow Rachel W. so that she can hit the ground running when she starts June 12, 2023. 

[New Employee Checklist](https://atd-dts.gitbook.io/wiki/onboarding/new-employee-checklist)

## Accounts - Team Lead

- [x] Submit a [CTM Transfer Employee Request Form](https://atx.servicenowservices.com/sp?id=sc_cat_item_guide&sys_id=b714eb12db7a3f0021ccef92ca961972) for a COA network account, eAccess PIN/HR Portal, and phone
- [x] Submit a [CTM service request](https://atx.service-now.com/sp) to add to DTS Distribution Email Group:
  - [x] Add "First Last Name" to email distribution list "ATD Data and Technology Service" ([ATDDataTechnologyServices@austintexas.gov](mailto:ATDDataTechnologyServices@austintexas.gov)) and "ACE ATD DL"
- [x] Add to City of Austin Slack - austininnovation.slack.com
   - [x] Supervisor formally introduces new team member on Slack
- [x] Add to DTS Google Drive
- [x] Add to [Gitbook](https://app.gitbook.com/@atd-dts/spaces)
- [x] Add to [Austin Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members) 
- [x] Upload headshot to ["Headshots" Drive folder](https://drive.google.com/drive/u/0/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G)
- [ ] Add to group slide and team slides [DTS Presentation Template Team section](https://docs.google.com/presentation/d/1tHKTfUgQ-uAXdRBkEdXqR7ryBo_LTU86IzQxo1gJoeA/edit#slide=id.gfd2da31025_0_6) 
- [ ] Update DTS group and team slides in the DTS Orientation presentation to reflect ☝️
- [ ] Check w/ Diana/Amenity—if needed; we pay for seats

## Calendar invites - Team Lead 
Schedule or coordinate with event owner
- [x] DTS Team Orientation — invite all leads, Peggy optional
- [x] First Week: DTS Product Ops — Coordinate w/ Patrick
- [x] Monthly Team Meeting
- [x] Sprints
- [x] Sprint Ceremonies — Planning, Grooming, Syncs
- [ ] Biweekly 1x1

**Comment by chiaberry** [comment]
@amenity

**Comment by amenity** [comment]
*_NERF ServiceNow ticket_*
Submitted: 05-16-2023 23:28:56
ID: RITM0202904

**Comment by amenity** [comment]
@dianamartin There is a field for distribtion list on the NERF now:
<img width="1097" alt="Screenshot 2023-05-16 at 11 39 06 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/def4ae22-da6c-486e-bccd-33127e0296b8">

Can we update our docs to specify how to fill out that field instead of showing it as a second, separate request? 
> For the field "List network access required..." enter the two distribution lists DTS team members should belong to: `"ATD Data and Technology Service" (ATDDataTechnologyServices@austintexas.gov) and "ACE ATD DL"`

**Comment by dianamartin** [comment]
@amenity I updated the GitBook docs

**Comment by patrickm02L** [comment]
Scott has added Rachel to the DTS Distribution Email Group.

**Comment by patrickm02L** [comment]
@dianamartin can you add Rachel to Google Drive and Gitbook?
