### ISSUE TITLE
Onboard Madison F.

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12212]
Complete the onboarding for our CIC Design Fellow Madison F. so that she can hit the ground running when she starts June 12, 2023. 

[New Employee Checklist](https://atd-dts.gitbook.io/wiki/onboarding/new-employee-checklist)

## Accounts - Team Lead

- [x] Submit a [CTM New Employee Request Form](https://atx.servicenowservices.com/sp?id=sc_cat_item_guide&sys_id=b714eb12db7a3f0021ccef92ca961972) for a COA network account, eAccess PIN/HR Portal, and phone
- [x] Submit a [CTM service request](https://atx.service-now.com/sp) to add to DTS Distribution Email Group:
  - [x] Add "First Last Name" to email distribution list "ATD Data and Technology Service" ([ATDDataTechnologyServices@austintexas.gov](mailto:ATDDataTechnologyServices@austintexas.gov)) and "ACE ATD DL"
- [x] Add to City of Austin Slack - austininnovation.slack.com 
   - [x] Supervisor formally introduces new team member on Slack
- [x] Add to DTS Google Drive
- [x] Add to [Gitbook](https://app.gitbook.com/@atd-dts/spaces)
- [x] Add to [Austin Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members) 
- [x] Upload headshot to ["Headshots" Drive folder](https://drive.google.com/drive/u/0/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G)
- [x] Add to group slide and team slides [DTS Presentation Template Team section](https://docs.google.com/presentation/d/1tHKTfUgQ-uAXdRBkEdXqR7ryBo_LTU86IzQxo1gJoeA/edit#slide=id.gfd2da31025_0_6) 
- [x] Update DTS group and team slides in the DTS Orientation presentation to reflect ☝️
- [x] Check w/ Diana/Amenity—if needed; we pay for seats

## Calendar invites - Team Lead 
Schedule or coordinate with event owner
- [x] DTS Team Orientation — invite all leads, Peggy optional
- [x] First Week: DTS Product Ops — Coordinate w/ Patrick
- [x] Monthly Team Meeting
- [x] Sprints
- [x] Sprint Ceremonies — Planning, Grooming, Syncs
- [x] Biweekly 1x1

**Comment by amenity** [comment]
**_NERF Service Now Ticket_** 
Submitted : 05-16-2023 23:18:41
Request Number : REQ0145816

**Comment by patrickm02L** [comment]
Scott has added Madison to the DTS Distribution Email Group.

**Comment by patrickm02L** [comment]
@dianamartin can you add Madison to Google Drive and Gitbook?

**Comment by dianamartin** [comment]
@patrickm02L I've added her to both Google Drive and GitBook
