### ISSUE TITLE
DTS Roadmap Solution - Jan 2020 Discovery Day

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1221]
### Problem
DTS needs tooling to align and communicate how our day-to-day work aligned with our strategic goals. DTS stakeholders need varying levels of information on the work that we are doing. For example:

- Executive Team: What is DTS’ vision and how will they work to achieve it over the next year?
- Division Managers: How will the product features we are working on help achieve the specific outcomes that are important to them?
- Developers: What are we going to be focusing on over the next few sprints?

To be effective, communication needs to be tailored to each stakeholder’s specific needs. Therefore, we need a flexible tool!

The current DTS roadmap options do not address our core needs:

- Zenhub roadmaps do not support externally-accessible views
- Roadmunk is not flexible enough to see varying levels of information

### Requirements for a DTS roadmap solution

**Must have**

- Accessible to stakeholders without Zenhub access
- Flexible views: Ability to view the high-level DTS initiatives (i.e., product and project) and the more granular views (sprint-level themes/epics)
- Ability to display products, features, epics, milestones
- Github integration
- Ability to filter by lane (e.g., filter to show only select products)
- Ability to filter by tag (e.g., see products/features by division impacted)
- Ability to filter by label (e.g., use colors to highlight common themes across products)
- Ability to bulk import and export data
- Affordable per user price

**Nice to have**

- Ability to use time frame other than months/quarters (e.g., Now, Next, Later)
- Product planning features, prioritization 

**Recommendation:**

- Use ProductPlan Roadmaps!

**Highlights include:**

- Github integration
- Flexible roadmap views
- Accessible to anyone
- PDF or embed

**Comment by JaceDeloney** [comment]
Links to the Test DTS ProductPlan Roadmap

**Comment by amenity** [comment]
@JaceDeloney - I added an estimate and milestone to this. We good to close?
