### ISSUE TITLE
[RPP Back Office] Meet with Joseph to learn about current state of RPP back office process

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1222]
Meet with Joseph to learn about current state of RPP back office process

**Comment by amenity** [comment]
@moorerst - Did you get to this in Sprint 16? Should we bump to Sprint 17?

**Comment by moorerst** [comment]
Completed 
[RPP Permit Distribution SOP - Draft 1.27.2020.docx](https://github.com/cityofaustin/atd-data-tech/files/4134961/RPP.Permit.Distribution.SOP.-.Draft.1.27.2020.docx)
