### ISSUE TITLE
Provide access to Cable Management page for Blake D.

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12231]
Billy B. 
AMD

Messaged 5/9
>can you give Blake Durst access to my cable management page?

**Comment by dianamartin** [comment]
@KaroEngstrom can you help Billy with this please, thanks!

**Comment by KaroEngstrom** [comment]
### T 5/9/23 
- Data Tracker
- figure out object: `cable_reels`
- figure out page: 
- figure out permissions needed: 
- does access mean view or edit?

**Comment by dianamartin** [comment]
# 5/10
Karo and I synced and talked about how she should do this.
- Add Blake to existing Page Rule
- [x] Added Blake
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/2a63cf6c-768a-4229-9c8b-b175dffdedc7)
- @KaroEngstrom will reach out to Blake and let him know

**Comment by KaroEngstrom** [comment]
Heard back from Blake: "Yes thats what I needed! Thank you!"
