### ISSUE TITLE
[RPP Back Office] Requirements gathering and user interviews

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1223]

**Comment by moorerst** [comment]
[RPP Permit Distribution SOP - Draft 1.27.2020.docx](https://github.com/cityofaustin/atd-data-tech/files/4205752/RPP.Permit.Distribution.SOP.-.Draft.1.27.2020.docx)
Conducted requirements meeting with PE core team.
Captured user stories for different personas
