### ISSUE TITLE
TDS Mtg 5/9

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12234]
Scoping meeting to discuss #11476 and #10837

**Comment by TracyLinder** [comment]
### Notes

**TIA Determination**
- When status is updated from 'Pending Review' to 'Review Complete' the system should send an automated email to the applicant email on record. 
- The applicant should be able to view their case and attachment via the customer portal using the access code feature.
    - A written disclaimer around the attachments table to inform the customer that the attachment isn't final until the case status is Review Complete.

**Comment by ChrispinP** [comment]
[Spike issue created](https://github.com/cityofaustin/atd-data-tech/issues/12236)
