### ISSUE TITLE
[Spike] Managing a Single Access Code vs Managing Multiple Access Codes for Customer Portal Access

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#12236]
In response the growing Customer Portal needs, this spike is to determine the best method for customers to access their data across multiple objects.

**Solution 1a:** A single access code & manage page with menu navigation with object data displayed on different pages. Will customer data need to be managed or tracked in someway for this to work?
**Solution 1b:** A single access code & manage page with more page rules that show or hide relevant views on the single page.

Benefit: Would be simpler for the customer only having one code and being able to see all their data in one place

**Solution 2:** Multiple access codes (one per object), each with their own manage page, resulting in a unique code & page for each object/module.

**Comment by ChrispinP** [comment]
For the purposes of TIA Determinations and SIF Worksheets, since re-submittals are not necessary, we updated the emails to include their unique link to their finalized documents. 

**In Regards to Solution 1:** To tie multiple different application objects together with one Access Code would likely require a common key of the User. We wouldnt need to manage accounts, but we would need to manage users/emails by having a customer object with a unique Access Code for each customer rather than each application.

**In Regards to Solution 1:** A multiple Access Code solution would work with the current app build but a user managing multiple Access Codes may or may not be confusing depending on if that customer submits multiple application types.

**Comment by TracyLinder** [comment]
This spike is complete and we have a better understanding of when/how to use these features.
