### ISSUE TITLE
[Open Data Portal] Update Vehicle Travel Monthly and Yearly Datasets' Metadata

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#12247]
From Ken P.: 
UTR
Emailed 5/9

**["Strategic Monthly Measures for Vehicle Travel along Major City Corridors"](https://data.austintexas.gov/Transportation-and-Mobility/Strategic-Monthly-Measures-for-Vehicle-Travel-Alon/pwst-h7fe)**
- The phrase "anonymous travel time data provided by INRIX" needs to be changed to "anonymous travel speed data provided by INRIX". ✅ 
- The Update Frequency should be advertised as "Monthly". ✅ 
- Please change the "Fiscal year" column name to "Year". (Please ensure that the token name given for it changes, too). ✅ 
     - Change the description for the field to "Calendar year represented by the metric". 
- Please change the description of "Month" to "Month number, where 1 is January and 12 is December". ✅ 
- Please ensure that the token name given for it changes, too
>[`Concern here re: changing the API field name and its impact on the ETL script`]
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/828436a6-c197-4731-acc2-f55e931a9621)

**["Strategic Yearly Measures for Vehicle Travel along Major City Corridors"](https://data.austintexas.gov/Transportation-and-Mobility/Strategic-Yearly-Measures-for-Vehicle-Travel-Along/58ki-vegs)**
- The phrase "anonymous travel time data provided by INRIX" needs to be changed to "anonymous travel speed data provided by INRIX". ✅ 
- The Update Frequency should be advertised as "Monthly". ✅ 
- Change "Each row is a" entry to: "Metric for given corridor, day type, and hour for each year" ✅ 

**Old version (captured just in case):** 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/48ac2183-4fc8-47e5-8fe9-b196439fc92a)

**Comment by dianamartin** [comment]
@chiaberry @johnclary cc: @ChristinaTremel 
Hey guys, Karo was in the middle of updating for this request from Ken. She stopped at the section when he said, 
>Please ensure that the token name given for it changes, too
I think that this is re: the API script and I believe someone on the DEV side might want to look at this. We believe it's regarding the API field name. 

Let us know if we need to update for APPS

**Comment by KaroEngstrom** [comment]
- emailed Ken and copied all ^ (need to collab w/ dev to ensure the ETL doesn't break)
- Ken responded that he would be the "dev" in this case and that he can make the change as soon as the portal side is updated
- I updated the API fields name from `fiscal_year` to `year` and notified Ken
- waiting on conformation that the ETL is updated

**Comment by KaroEngstrom** [comment]
Nothing from Ken or MMC. Closing this.
