### ISSUE TITLE
[RPP Back Office] User interviews with back office staff

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1224]
- [x] Meet with Alyse
- [x] Upload notes from Alyse's interview [to Drive](https://drive.google.com/drive/folders/1_NzZEfXIVShyYoYpLSJiOXLQRA6O7KBC)
- [x] Meet with Ryan and/or other back office staff and add notes to Drive

**Comment by SurbhiBakshi** [comment]
@dianamartin @moorerst @TracyLinder - here are my notes from the meeting on Feb 3rd, please let me know if you would like these somewhere else. 



**Notes from meeting on Feb 3rd ** 

**1. Permit Process**  

- Application starts - Select if this is a new application or a renewal for an existing permit, form features will depend on this selection.

** Need to know** 
1. Permit location
2. Applicant Name, 
3. Type of vehicle, 
4. Type of permit (hang tag vs decal, each will have a serial number for tracking), 
5. if permit location is eligible, 
6. applicant location in case applicant is a property manager applying for various properties, 
7. applicant contact info - email/ phone number
8. How applicant will pay - check / card/ cash
9. If payment is by check , if check bounced
10. If payment is by card - which card (Mastercard/Visa..)
11. Automated email when status changes to 'Needs Documentation/ Payment'
12. If documentation/ payment request is not fulfilled, permit application will become inactive after a month?
13. Permit expires a year (?) after it is issued - need an automated reminder for the applicant when status is set to expire.
13. Status - Submitted, Under Review, Needs Documentation, Pending Payment, Complete, Approved, Denied / Ineligible, Withdrawn, Cancelled
14. Generate an invoice number at the end of the application that can be referenced for communication regarding documentation/ payment
15. Ability to upload proof/ documentation
16. Digital signature

**Reporting Needs -** 
1. By location
2. By status
3. By time - month, quarter ?
4. By payment method
5. Query how many permits have been issues/ applied for by address
6. New application versus Renewals
7. Ratio of permits issued to permits that could be issues in a geographical area  (Percent of the district that has purchased permits)
8. How was payment received? mail/ phone/ web/ in person
9. How was application received? Web / tablet in office in person
10. Split cost by line item
11.How many permits will be up for renewal in the coming month/ quarter?

**Comment by moorerst** [comment]
copied notes to 
https://drive.google.com/drive/folders/1_NzZEfXIVShyYoYpLSJiOXLQRA6O7KBC
verified each item was included as a line item in the User Stories
