### ISSUE TITLE
[Tech debt] Replace `status_id` column with `is_deleted` on `moped_components` table

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#12248]
We have a lingering instance of a `status_id` column on the `moped_components` table which needs to be replaced with boolean `is_deleted` column. Discussion [here](https://github.com/cityofaustin/atd-moped/pull/1014#discussion_r1189182057).

Todo:
- Create migration to alter table - setting `is_deleted` to `false` where `status_id` is `1`
- Update editor code to use this new column.

**Comment by mddilley** [comment]
Picking this up so I can truly shut the 🚪 on the [status_id epic](https://github.com/cityofaustin/atd-data-tech/issues/9150)! 🚀

**Comment by johnclary** [comment]
Nice—thanks @mddilley!
