### ISSUE TITLE
Calculate comprehensive cost for 55 signalized intersections

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12257]
## Background

Andrew and his team are working on a project where they need to apply the comprehensive cost value from the VZ Polygons to signals at signaled intersections. Out of 1250+ signals, around 50 fall outside of the VZ Polygons and the Austin full purpose jurisdiction. They need to find or generate aggregated comprehensive cost data for these signals. Comprehensive cost data is stored at the crash level, which means it is associated to points, which is problematic when associating them to signals, which are also points, under the constraint that they need to be apples-to-apples comparable to the existing VZ polygon data.

## Preferred Solution

Since there is a relatively small number of signals in question, I suggest manually clicking out polygons around the intersections at a rate of about one per 120 seconds, estimating that it would take a few hours to cover all of them. Both Andrew and I think that this quicker solution may be the best option.

## Alternative Semi-Solution

I suggest using the postGIS database where the crash data is housed as a datasource for ESRI ArcMap, but I find that ESRI's postGIS support is not great. I can export a shapefile of all crashes with the comprehensive cost figures as an attribute, but this still doesn't solve the problem of aggregating the data for meaningful comparisons with existing polygons.

**Comment by patrickm02L** [comment]
Talked about this in grooming 3/10/23. 

We're going to update the GIS on how add a buffer to polygons to capture additional crashes. 
[Here's the docs how to.](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M3vG5OVht6_BV2LYSXk/miscelaneous/vision-zero-polygon-maintenance)

**Comment by frankhereford** [comment]
@patrickm02L If it's helpful, I'd like to clarify the comment above because I worry that it will be misinterpreted by the GIS team. We don't want to buffer existing polygons, but in this case, the task will be to create new polygons following the guidelines in the documentation you linked such that new roads or areas of interest are able to be captured. 

Additionally, it will be important to plan and execute a process to get the changes back into the VZDB, because the more the GIS team's copy of the polygons desync from the VZDB's copy, it will be harder to keep track of the deviations and until the changes make it into the upstream VZDB, the polygons will not be used.

**Comment by andrewshensky** [comment]
Per my discussion with @patrickm02L below or some notes on what we are looking for.

There are about 50 signaled intersections that fall outside the full-purpose jurisdiction that we would like to get comp cost scores for in order to better inform an analysis we doing for Jim D. regarding signal prioritization in the event of power outages. We can provide the 50 locations/intersections we are interested in as a shapefile, csv, etc. We are not anticipating being about to get scores generated for all 50 locations but the more we get the better our result will be. We **do not** need the polygons created, we are just looking for the scores to be generated, which the GIS team can manually apply to the analysis output if needed. Let me know if any further questions or concerns arise.

**Comment by patrickm02L** [comment]
In Grooming 5.24.23 --

the comprehensive cost value can be found in the Vision Zero database in the crashes table

**Comment by chiaberry** [comment]
@Charlie-Henry volunteered to tackle this, should it be this sprint  or next? How many locations do they want scores for?

**Comment by andrewshensky** [comment]
@chiaberry it looks like it will be 55 locations. I will provide those locations to @Charlie-Henry as a shapefile

**Comment by andrewshensky** [comment]
Shapefile of the 55 locations has been provided through email

**Comment by Charlie-Henry** [comment]
Below is the code is the code I used for querying the VZ crash table to get crashes within a buffer radius of 250 feet from the supplied intersection points from @andrewshensky. I slacked him the results. If we need to change this to query polygons we can do that if they end up getting created. 💯 

I am summing all three cost columns I saw, I'm not sure which is the correct one for comprehensive cost?

Query:
```{sql}
SELECT
	SUM(est_comp_cost),
	SUM(est_comp_cost_crash_based),
	SUM(est_econ_cost)
FROM
	atd_txdot_crashes
WHERE
	ST_DistanceSphere (position, ST_MakePoint (location_x, location_y)) <= 250 * 0.3048 
```

ST_DistanceSphere expects meters so that why we're multiplying by 0.3048. 

```{python}
import psycopg2
import os
import geopandas as gpd
import pandas as pd

USER = os.getenv("VZ_USER")
PASSWORD = os.getenv("VZ_PASSWORD")
DATABASE = os.getenv("VZ_DATABASE")
HOST = os.getenv("VZ_HOST")

points = gpd.read_file("SignalsOutsideVZPolys.geojson")
# Re-project into WGS1984
points = points.to_crs("EPSG:4326")
# Establish a connection to the VZ RR database
conn = psycopg2.connect(
    host=HOST,
    database=DATABASE,
    user=USER,
    password=PASSWORD,
)

# Create a cursor object to interact with the database
cursor = conn.cursor()

radius = 250 # in feet
res_names = ["est_comp_cost", "est_comp_cost_crash_based", "est_econ_cost"]
res = []
for p in points["geometry"]:
    cursor.execute(f"SELECT SUM(est_comp_cost), SUM(est_comp_cost_crash_based), SUM(est_econ_cost) FROM atd_txdot_crashes WHERE ST_DistanceSphere(position, ST_MakePoint({p.x}, {p.y})) <= {radius * 0.3048}")

    # Turning result into a dictionary, so we can append it back to the supplied data
    rows = cursor.fetchall()
    result_dict = {}
    for i, name in enumerate(res_names):
        result_dict[name] = float(rows[0][i])
    res.append(result_dict)

data = pd.DataFrame(res)
result = pd.concat([points, data], axis=1, join="inner")
result.to_file("buffered_250ft_result.geojson")
result.to_csv("buffered_250ft_result.csv")

# query for polygons if we need it in the future:
# cursor.execute(f"SELECT SUM(est_comp_cost), SUM(est_comp_cost_crash_based), SUM(est_econ_cost) FROM atd_txdot_crashes WHERE ST_Within(position, ST_GeomFromGeoJSON('{p}'))")
```

**Comment by frankhereford** [comment]
Thanks @Charlie-Henry! 

`est_comp_cost` is the "old" computation of comprehensive cost, where every injury is given a monetary value and they are all added up for the comprehensive cost of the crash.
`est_comp_cost_crash_based` is the newer computation method, where a single instance of the worst crash severity is given a monetary value and it becomes the value of the crash.

It's my understanding that VZ is operating under the new method, but they both are maintained and available in the DB.

**Comment by patrickm02L** [comment]
6.5.23 Chatted with Andrew, he indicated that he would plug the numbers that Charlie provided into the existing data today.

Considering this closed.
