### ISSUE TITLE
[Spike] Generate street polygons for Level 1-4 road intersections with Level 5 roads

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12270]
### Objective

Develop a method or algorithm that generates street polygons for the intersections between Level 1-4 roads and Level 5 roads. The generated polygons should accurately represent the street geometry, including the "legs" extending from the Level 1-4 roads up to the point of intersection with the Level 5 roads.

### Deliverables

- A documented method or algorithm that outlines the process of generating street polygons for the specified intersections.
- Implementation of the method or algorithm as a software component or module that can be integrated into the existing system.
- Visual examples or simulations showcasing the before and after representation of the intersections with the newly generated street polygons.
- Test results and validation reports demonstrating the accuracy and quality of the generated street polygons.

### Identified intersections for testing

via @xavierapostol 

The following polygons intersect with Level 5 polygons for CAPITAL OF TEXAS HIGHWAY "Loop 360". This is the section that starts just south of Lake Austin to just west of US 183

- 47494174A7 [JOLLYVILLE RD]
- 9EB3A416DF [WILDRIDGE DR]
- E3F5E14062 [ARBORETUM BLVD]
- 2709586523 [GREAT HILLS TRL]
- 6CCCF3A983 [BLUFFSTONE LN, SPICEWOOD SPRINGS RD]
- C54718C698 [OLD SPICEWOOD SPRINGS RD]
- 651B2E011F [SPICEWOOD SPRINGS RD]
- 8DDA4E84AD [WINDING RIDGE BLVD
- 2C76117A5D [LAKEWOOD DR]
- 89D6133ECF [WALLACE DR]
- A09910727D [CHAMPION GRANDVIEW WAY]
- 69232FF189 [COURTYARD DR, WEST COURTYARD DR]
- ~AEF4550423 [CAP TX TO PLAZA ON THE LA RAMP, PLAZA ON THE LAKE]~
- 560D9A12DC [CAP TX TO PLAZA ON THE LA RAMP]
- 0E50DAFA27 [CAP TX TO PLAZA ON THE LA RAMP]
- 980D94A918 [PLAZA ON THE LAKE]

### Outcome
The findings and outcomes of this spike will inform the development of a full-scale solution to address this requirement.

**Comment by frankhereford** [comment]
## progress

I have pulled together a number of resources, and compiled them into a QGIS visualization of the task at hand. This map includes:

* The ASMP network
  * Categorized by street level
  * Visualizing each a cold-to-hot palette
  * Vertices drawn when zoomed in close enough
* Polygons
  * The 1-4 set
  * The unworkable 5 set
  * The polygons of interest provided by Xavier
* Nearmap
  * Including a little docker stack proxy to make it work in QGIS ✨
* My OSM tiles from tiles.frankhereford.io.

This work makes proceeding possible, as it's just not plausible to do this sort of task without a reliable and robust way to visualize the progress as you are making it.

Right out of the gate, this has shown that using the level 5 linestrings in the ASMP network is no more viable today than it was back when we did this work. Custom level 5 linestrings will be needed, but they will need to be made such that they share vertices with the 1-4 linestrings, allowing for the polygonizer to find and handle intersections correctly. 

## Next Step

* Draw the level 5 linestring network, described above.

**Comment by patrickm02L** [comment]
This Spike led to Manually redrawing Level 5s Issue, and subsequent MVP QGIS plugin Issue. Issues are referred to in the description and part of the Level 5 Polygons Epic.
