### ISSUE TITLE
Truncate VZ DB tables

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12272]
As a developer working on local development environment, I want to be able to truncate the `hdb_catalog.event_invocation_logs` and `hdb_catalog.event_log` tables so that I can reduce the load on the read replica and improve replication performance.

See slack [thread](https://austininnovation.slack.com/archives/CM9MK950S/p1683736878860929?thread_ts=1683736676.777489&cid=CM9MK950S)

**Comment by frankhereford** [comment]
Forgot to come back and close this earlier. This is completed.
