### ISSUE TITLE
[RPP Back Office] Schedule recurring meetings

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1227]
- [ ] Sprint Reviews: Every two weeks, starting on 1/28 - Parking & Finance stakeholders + core team ( @moorerst, @dianamartin @TracyLinder), @amenity 
- [ ] Sprint Retro + Planning:  Every two weeks, starting on 1/29- Core team (@moorerst, @dianamartin @TracyLinder), @amenity 
- [ ] Backlog Grooming:  Every two weeks, starting on 2/5 - Core team ( @moorerst, @dianamartin @TracyLinder), @amenity

**Comment by amenity** [comment]
@moorerst - can you give an update on these?

**Comment by amenity** [comment]
@moorerst - I believe this is complete, yes?

**Comment by moorerst** [comment]
recurring Sprint meetings have been scheduled
