### ISSUE TITLE
Update DTS website and Data and Performance Hub to align with new TPW branding  

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#12282]
## [DTS website](https://www.austinmobility.io)

Repo: https://github.com/cityofaustin/atd-product

**Footer**
- [x] Remove City of Austin seal
- [x] Change "Austin Transportation" to "Austin Transportation & Public Works"
- [x] If possible, make [this whole div](https://github.com/cityofaustin/atd-data-tech/assets/1463708/94e610d8-277f-4122-9470-713dc94e5008) link to https://austinmobility.io

**Header**
- [x] Update wordmark in the upper left-hand corner of header to [2023 Austin Transportation Public Works Branding Guide_Royal logo hz](https://cityofaustin.sharepoint.com/sites/tpwpio/atd%20department%20branding%20documents/logos/2023%20austin%20transportation%20public%20works%20branding%20guide_royal%20logo%20hz.png?web=1).* 
- [x] Update alt text to "Transportation and Public Works wordmark including the City of Austin seal"

**"About" page**
- [x] Change _"We leverage high quality data and modern tech to empower Austin Transportation staff to improve operations, make data-informed decisions, and deliver excellent mobility services to the Austin community. We solve real problems for real people."_ to 
_"We leverage high-quality data and modern technology to empower Transportation and Public Works staff to improve operations, make data-informed decisions, and deliver excellent mobility services to the Austin community. We solve real problems for real people."_

**"Products" page**
- [x] Change _"We improve and extend our products over time so that they deliver continuous value to Austin Transportation as business needs evolve."_ to
_"We improve and extend our products over time so that they deliver continuous value to Transportation and Public Works staff as business needs evolve."_

**"Projects" page**
- [x] Change "Projects are temporary endeavors..." to "Projects are timeboxed endeavors..."

## [Data and Performance Hub](https://data.mobility.austin.gov)

**Top banner**

- [x] Change _"Dashboards and public datasets curated by the City of Austin Transportation Department"_ to
_"Dashboards and public datasets curated by City of Austin Transportation and Public Works"_

**Footer**
- [x] Remove City of Austin seal
- [x] Change "Austin Transportation" to "Austin Transportation & Public Works"
- [x] If possible, make [this whole div](https://github.com/cityofaustin/atd-data-tech/assets/1463708/94e610d8-277f-4122-9470-713dc94e5008) link to https://austinmobility.io

**Header**
- [x] Update wordmark in the upper left-hand corner of header to [2023 Austin Transportation Public Works Branding Guide_Royal logo hz](https://cityofaustin.sharepoint.com/sites/tpwpio/atd%20department%20branding%20documents/logos/2023%20austin%20transportation%20public%20works%20branding%20guide_royal%20logo%20hz.png?web=1)* 
- [x] Update alt text to "Transportation and Public Works wordmark including the City of Austin seal"

**"Traffic Cameras" page**
- [x] Update text in [info modal](https://github.com/cityofaustin/atd-data-tech/assets/1463708/db2f67f2-1d2c-49be-879a-03587ee7f9f1) from "Austin Transportation Department's traffic cameras" to "Austin Transportation and Public Works' traffic cameras"

**"Signal Evaluations" page**
- [x] Update text in [info modal](https://github.com/cityofaustin/atd-data-tech/assets/1463708/3b16d66d-1267-407d-80cd-3c224cd2f9e0) from "Austin Transportation Department" "Austin Transportation and Public Works"

_*The current wordmark is two SVGs; this is a single PNG. It's not as flexible a format, but it preserves PIO's prescribed font, line weight, spacing, CoA seal version, etc._

**Comment by amenity** [comment]
Good question from @chiaberry: Should individual project pages be updated to say TPW instead of ATD?

Yes, but PMs can take care of this. @johnclary @TracyLinder @patrickm02L @katelunceford @AdnanTaher, please 
- Update references to our department name in your project indexes that are either in progress or in the backlog. 
- Update references to our department name in all of your product indexes

**Comment by johnclary** [comment]
Can we get clarification on the name of the department? Is it:

- Austin Transportation & Public Works
- Austin Transportation and Public Works
- Austin Transportation Public Works

I've seen all three in official communications.

**Comment by amenity** [comment]
@johnclary Based on the first line of the [TPW style guide produced by PIO](https://cityofaustin.sharepoint.com/sites/tpwPIO/ATD%20Department%20Branding%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FtpwPIO%2FATD%20Department%20Branding%20Documents%2FTPW%20Style%20Guide%2004%2E18%2E23%2Epdf&parent=%2Fsites%2FtpwPIO%2FATD%20Department%20Branding%20Documents): **Austin Transportation and Public Works**
