### ISSUE TITLE
Mobility Project Viewer User Research with Austin Residents

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12295]
## Description
The Moped Viewer is a public-facing platform developed by the transportation and public works department. It aims to provide residents with a map showcasing all the projects within the city related to transportation and public works.

## Objective
Conduct user research and gather input from residents of the City of Austin to define the desired interactions and valuable information to be included in the Moped Project Viewer platform.

## Requirements
- Create a user research plan to engage residents of the City of Austin.
- Develop a survey or feedback mechanism to collect residents' preferences.
- Provide clear instructions and prompts to guide residents in expressing their desired interactions and valuable information.
- Ensure the user research covers a diverse range of residents to gather comprehensive insights.
- Analyze the gathered data to identify common patterns, preferences, and priorities.

## Deliverables
- Summary report of user research findings, including residents' desired interactions and valuable information for the Moped Viewer.
- Insights and recommendations for the development team to incorporate into the platform.

## Notes
- It may be beneficial to conduct focus groups or interviews in addition to the survey to gather qualitative insights.
- Consider incorporating interactive prototypes or mockups to help residents visualize their desired interactions.

**Comment by patrickm02L** [comment]
May want to turn this into it's own Project label depending on the scope.

**Comment by patrickm02L** [comment]
We did not get to test with Users. But built the foundation for when we will with the updated mockups, outreach, and testing materials.

**Comment by amenity** [comment]
This epic contained the following work:
- [Create Testing Materials for residents](https://github.com/cityofaustin/atd-data-tech/issues/12703)
- [Create 3 Mockups for Mobility Project Viewer with Different Levels of Complexity](https://github.com/cityofaustin/atd-data-tech/issues/12664)
- [Create Testing Materials for residents](https://github.com/cityofaustin/atd-data-tech/issues/12703)

We are reaching out to ACC to see if any UX students would be interested in picking up this work.
