### ISSUE TITLE
[Tech Debt] Migrate Auth0 rules to actions (deadline 11/18/2024)

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#12300]
On November 18, 2024, Auth0 Rules and Hooks will be deprecated. We have one rule for VZE that makes sure all IT Supervisors have the admin role attached. https://manage.auth0.com/dashboard/us/atd-datatech/rules/rul_rz908hkwOXefv6jf

We need to follow the migration guide to update this rule.

Links:
https://auth0.com/blog/preparing-for-rules-and-hooks-end-of-life/
https://auth0.com/docs/customize/actions/migrate/migrate-from-rules-to-actions

**Comment by mddilley** [comment]
@patrickm02L This change is far in the future but it affects VZE.

**Comment by chiaberry** [comment]
I got this in an email, but I dont see it on their blog. 

> We have updated the original Rules and Hooks' end-of-life plans. On November 18, 2024, Rules and Hooks will remain active and will continue to execute, but will degrade to a read-only mode. As part of this change, we are delaying the complete removal of Rules and Hooks functionality to a future date that is still under review. | We have updated the original Rules and Hooks' end-of-life plans. On November 18, 2024, Rules and Hooks will remain active and will continue to execute, but will degrade to a read-only mode. As part of this change, we are delaying the complete removal of Rules and Hooks functionality to a future date that is still under review.

**Comment by johnclary** [comment]
It's done! I followed these steps:

1. Write the action code based on the Auth0 docs
2. "Deploy" the action
3. Delete the old auth role
4. Create an action "trigger" that makes sure our action runs as part of the login flow.

Here is the action code—which i considered committing to the repo, but Auth0 is the source of truth and also has some kind of version control built-in.


```javascript
exports.onExecutePostLogin = async (event, api) => {
  const namespace = "https://hasura.io/jwt/claims";
  const default_role = "readonly";

  if (event.user) {
    // we expect users to have an app_metadata.roles array
    // this is managed through the VZE UI + user management flask API
    const roles = event.user.app_metadata.roles || [];

    if (roles.includes("itSupervisor")) {
      // Add admin role to IT Supervisors
      if (!roles.includes("vz-admin")) {
        roles.push("vz-admin");
      }
    }

    // Set Hasura claims in the ID token
    api.idToken.setCustomClaim(namespace, {
      "x-hasura-default-role": default_role,
      "x-hasura-allowed-roles": roles,
      "x-hasura-user-id": event.user.user_id,
    });
  }
};

```
