### ISSUE TITLE
Add "Other" toggle to Units Type to crashes advanced search

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12308]
**Related to Issue:** Add scooter-rider involved and motorcycle involved filter to VZE #7081

## Description
Accurately identify and categorize unit types related to crashes, including the option of "Other" to the unit types filters. 

Currently, we have filters for (A) Motor vehicle, (B) Motorcycle, (C) Bicycle, (D) Pedestrian, and (E) Scooter rider. However, there are instances where the unit involved does not fit into any of these predefined categories. We need to create a separate category for "Other" that aligns with the existing conditions and captures those incidents that cannot be classified as A, B, C, D, or E.

See [comment](https://github.com/cityofaustin/atd-data-tech/issues/11324#issuecomment-1533164362) for breakdown of the conditions for each category.

## Requirements
- Ensure that the "Other" category does not overlap or include incidents that should be classified under A, B, C, D, or E.
- Updated filter option for "Other" in the unit type selection related to crashes.
- Accurate categorization of incidents under the new "Other" filter.

![Screen Shot 2023-05-18 at 1.31.18 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/16861fce-59fc-4abf-a531-43e976713ca8)

## Notes
- It is essential to consult Xavier to determine the specific criteria for classifying incidents as "Other" and ensure it aligns with the rest of the conditions.
- The existing filters A, B, C, D, and E will remain intact, with the addition of a separate "Other" filter.
- The ETL process needs to be adjusted to include the new travel mode and accurately calculate the total number of crashes.
- Temporary fluctuations in crash numbers are expected during the transition, but the objective is to maintain accuracy in the long term.

**Comment by patrickm02L** [comment]
cc: @tillyw @frankhereford

**Comment by tillyw** [comment]
original 'other' query:

where: [
    {
        '_and: [ { units: { unit_desc_id: { _neq: 1 } } }, { units: { unit_desc_id: { _neq: 3 } } }, { units: { unit_desc_id: { _neq: 4 } } }, { _and: [ { units: { unit_desc_id: { _eq: 177 } } }, { units: { veh_body_styl_id: { _neq: 177 } } } ] } ]': null,
    },
],

**Comment by patrickm02L** [comment]
@xavierapostol would love to get your eyes on this.

**Comment by xavierapostol** [comment]
Hi y'all, I'm referencing #11324 here. I updated the query to account for Motor Vehicles with a `null` vehicle body style id and updated the e-scooter values.
<html><body><!DOCTYPE html>
<html>
<head>
<style>
table {border: medium solid #6495ed;border-collapse: collapse;width: 100%;} th{font-family: monospace;border: thin solid #6495ed;padding: 5px;background-color: #D0E3FA;}td{font-family: sans-serif;border: thin solid #6495ed;padding: 5px;text-align: center;}.odd{background:#e8edff;}img{padding:5px; border:solid; border-color: #dddddd #aaaaaa #aaaaaa #dddddd; border-width: 1px 2px 2px 1px; background-color:white;}</style>
</head>
<body>


------------------------ For GitHub issue: https://github.com/cityofaustin/atd-vz-data/pull/1225with counts as (select   (select count( distinct unit_id )   from atd_txdot_units   where true    AND unit_desc_id = 1     AND ( veh_body_styl_id NOT IN (71,90)    OR veh_body_styl_id IS NULL ) ) as motor_vehicle,  (select count( distinct unit_id )   from atd_txdot_units   where true    AND unit_desc_id = 1     AND veh_body_styl_id IN (71,90)) as motorcycle,  (select count( distinct unit_id )   from atd_txdot_units   where true    AND unit_desc_id = 3) as bicycle,  (select count( distinct unit_id )   from atd_txdot_units   where true    AND unit_desc_id = 4) as pedestrian,  (select count( distinct unit_id )   from atd_txdot_units   where true    AND unit_desc_id = 177    and veh_body_styl_id = 177) as scooter,  (select count( distinct unit_id )   from atd_txdot_units   where true    AND unit_desc_id NOT IN (1,3,4) AND NOT (unit_desc_id = 177 AND veh_body_styl_id = 177)) as other,  (select count( distinct unit_id ) from atd_txdot_units) as total_units_count)  select *, ( total_units_count - ( motor_vehicle + motorcycle + bicycle + pedestrian + scooter + other ) ) as uncaptured_units from counts
--

733,678 | 9,440 | 4,862 | 7,607 | 285 | 19,797 | 775,669 | 0

</body></html></body></html>

**Comment by tillyw** [comment]
> Hi y'all, I'm referencing #11324 here in response to Frank's [comment ](https://github.com/cityofaustin/atd-data-tech/issues/11324#issuecomment-1533164362)about conditions. I updated the query to account for Motor Vehicles with a `null` vehicle body style id and updated the e-scooter values.
> 
> ```
> with 
>     counts as ( 
>         select 
>             ( select count ( distinct unit_id ) from atd_txdot_units 
>                 where true and unit_desc_id = 1 and ( veh_body_styl_id not in ( 71,90 ) or veh_body_styl_id is null ) ) as motor_vehicle,  
>             ( select count ( distinct unit_id ) from atd_txdot_units 
>                 where true and unit_desc_id = 1 and veh_body_styl_id in ( 71,90 ) ) as motorcycle,  
>             ( select count ( distinct unit_id ) from atd_txdot_units where true and unit_desc_id = 3 ) as bicycle, 
>             ( select count ( distinct unit_id ) from atd_txdot_units where true and unit_desc_id = 4 ) as pedestrian,  
>             ( select count ( distinct unit_id ) from atd_txdot_units 
>                 where true and unit_desc_id = 177 and veh_body_styl_id = 177 ) as scooter,  
>             ( select count ( distinct unit_id ) from atd_txdot_units 
>                 where true and unit_desc_id not in ( 1,3,4 ) and not ( unit_desc_id = 177 and veh_body_styl_id = 177 ) ) as other,  
>             ( select count ( distinct unit_id ) from atd_txdot_units ) as total_units_count ) 
> select *, ( total_units_count - ( motor_vehicle + motorcycle + bicycle + pedestrian + scooter + other ) ) as uncaptured_units
> from counts
> ;
> ```
> 
> motor_vehicle	motorcycle	bicycle	pedestrian	scooter	other	total_units_count	uncaptured_units
> 733678	9440	4862	7607	285	19797	775669	0

Hi @xavierapostol, thanks for clarifying this query? what time frame are you querying? I only have access to the past 10 years in vze, so if your query includes a longer time frame could you potentially shorten it to the past ten years or so and provide the start and end dates?

this is the 'other' query you provided in our `GridTable` format:

```              "_and: [ { units: { unit_desc_id: { _neq: 1 } } }, { units: { unit_desc_id: { _neq: 3 } } }, { units: { unit_desc_id: { _neq: 4 } } }, { units: { unit_desc_id: { _neq: 177 } } }, { units: { veh_body_styl_id: { _neq: 177 } } } ]": null,
```

i simplified it so it basically just sums any records that do not have `unit_desc_id` of 1,3,4 and 177 and does not have a `unit_desc_id` of 177. please let me know if that doesn't capture your query!

**Comment by xavierapostol** [comment]
Hi @tillyw ! The query I provided has no timeframe ( it is just looking at what is in our `units` table ). If you'd to coordinate a query to assist with validating your output, I'd be more than happy to help! 

As far as capturing the "other" field, I believe your query would capture the same "other" units in my query.
