### ISSUE TITLE
Manually redraw Level 5 polygons intersecting with 1-4

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12315]
Related Issue: [Spike] Generate street polygons for Level 1-4 road intersections with Level 5 roads #12270

## Description
Manually redraw or update specific level 5 polygons that intersect with 1-4. This task involves redrawing the polygons individually due to changes in road configurations and intersections. The complexity of the polygons is influenced by the number of intersections on the road which are not the result of an on- or offramp.

## Requirements
- Identify the specific level 5 polygons that intersect with 1-4.
- Understand the differences between intersections which are due to on and off ramps as opposed to at-grade intersections.
- Take into account the impact of intersections on polygon complexity, particularly as they might impact crash patterns.
- Redraw or update the polygons to accurately represent the road geometry and such that they are able to isolate crash patterns which result from intersections.

## Deliverables
- Updated level 5 polygons that reflect the revised road configurations and at-grade intersections.
- Clear documentation of the changes made to each polygon, when a polygon falls into a particularly challenging geometry. The bulk of polygons will speak for themselves and require no additional notation.

## Notes
- It is important to ensure the accuracy of the redrawn polygons to maintain data integrity.
  - This will be achieved though ensuring that overlap in polygons is only utilized in appropriate locations and that abutting polygons appropriately share common vertex locations.
- Collaboration with other team members may be necessary to clarify any ambiguities or uncertainties related to the road configurations and intersections.
- Consider any potential challenges or constraints in redrawing the polygons, such as overlapping features or limited access to certain areas.

## Time Estimate
Based on initial discussions, it is estimated that manually redrawing or updating the polygons could require approximately two weeks of full-time work, assuming each polygon takes about a minute to complete.

**Comment by patrickm02L** [comment]
@frankhereford please review this Issue and add details as needed.

**Comment by frankhereford** [comment]
@patrickm02L Sure thing, I made a handful of changes. In particular, I found that my usage of the term-of-art "grade" needed revision from our conversation, so I did that. 

Good idea on the screenshots. Here they are.

Before:
![image](https://github.com/cityofaustin/atd-data-tech/assets/3653206/4ee63164-2b4f-412b-9eea-0154ca89ded1)

After:
![image](https://github.com/cityofaustin/atd-data-tech/assets/3653206/0495b17b-8c7b-4fcc-a9b3-b3a9de7bd2b2)

**Comment by patrickm02L** [comment]
DTS is talking with Milad 6/26/23 about how to approach this. Working on #12636 in advance of Milad's updates.

**Comment by patrickm02L** [comment]
Now that Milad undertaking the redrawing on his end, this is no longer relevant. 

However this Issue speaks to the larger action of what to do about the former polygons in #8388, which we're addressing in #11003
