### ISSUE TITLE
Add Cancel new item request button

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1234]
Add a Cancel new item request button

User Flow: 

1. User taps Cancel button
2. User confirms cancelation by clicking yes
3. System submits a form to knack to cancel request

This button should be styled like the edit button. It should also be placed side-by-side to the edit button

**Comment by mddilley** [comment]
Duplicate of https://github.com/cityofaustin/atd-data-tech/issues/1216. Closing.
