### ISSUE TITLE
Test matching Brazos data to Knack data in Power BI

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1235]
Before we remove the apps reporting objects in production, we need to ensure that we are on the right path using Power BI for analysis. Let's work on connecting records pulled in with the Brazos exports with the Knack assignment data in Power BI.

**Comment by SurbhiBakshi** [comment]
Also test creating joins between objects from Knack in Power BI.

**Comment by SurbhiBakshi** [comment]
@dianamartin will test 
sharing and QAQC

**Comment by amenity** [comment]
@SurbhiBakshi @dianamartin - do we feel confident that we can move forward using PowerBI?

**Comment by SurbhiBakshi** [comment]
@amenity, I  haven't gotten to a point where  I can be confident, and Diana hasn't tested it as yet.

**Comment by amenity** [comment]
@dianamartin - are you able to test this in Sprint 17?

**Comment by dianamartin** [comment]
@amenity @SurbhiBakshi it depends on how far Surbhi gets and if it's ready for me to test in Sprint 17.

**Comment by SurbhiBakshi** [comment]
- [ ] Pull data from object in Knack
- [ ] Derive fields 
     - [ ] Assignment Date from Assignment Date and Time
      - [ ] Assignment Time
     - [ ] Assignment Start Time
     - [ ] Assignment End Time
     - [ ] Assignment Day of Week 
     - [ ] Assignment Day of Week Name
      - [ ] Assignment Month 
      - [ ] Assignment Month Name
      - [ ] Assignment Duration 
      - [ ]

**Comment by SurbhiBakshi** [comment]
Anomalies - 
- [ ] the 12 am to 3 am assignment throws of Day of Week calculations

**Comment by amenity** [comment]
@SurbhiBakshi - moving this to In Progress since it's great to get taken care of while we nail down specifics on the new location model.

**Comment by amenity** [comment]
@SurbhiBakshi - are you going to try to match Brazos citations to a specific assignment+officer in Power BI?

**Comment by SurbhiBakshi** [comment]
@amenity - yes, I have a theory that I need to test and check if it works. Will keep you updated on what I find out.

**Comment by SurbhiBakshi** [comment]
@amenity - much easier to connect citations to assignments if officers note down citation numbers, citation numbers should be able to connect to multiple citations with the same number. Connecting without this functionality is possible, but laborious - [Connecting Knack data to Brazos data](https://docs.google.com/document/d/1XrhsgYDJlDK86QhFJYEVIj5Qoh4xrKL-QU0Fr0Yk72Q/edit?usp=sharing)

**Comment by amenity** [comment]
@SurbhiBakshi - great, thanks for the work on that. This documentation will be invaluable if we decide to script this in the future, but I agree that it's best to play it safe and have officers record the data directly for now.
