### ISSUE TITLE
[Enhancement] Refine map default zoom/fit behavior

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#12353]
Refine the the way the summary and component map zooms/fits project features on the map when the map is first rendered.

1. On both maps, always fit all features on the map, including any features from related projects
2. On both maps, reduce the project bounds padding so that when a project covers a large area it isn't zoomed out too far.

<img width="1512" alt="one" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/95a5c717-5ffc-4e51-b6f7-18526a290c7a">
<img width="1512" alt="two" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/55867194-fb92-4d59-885f-0a5244030825">
<img width="1457" alt="3" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/ebc5ec1f-38f4-481f-b5a2-1cc2f7994e8e">

**Comment by mddilley** [comment]
@johnclary Tagging you so I remember to ask you about whether we should show parent and sibling components in the project summary map. We currently do that on the Map tab component map. I keep forgetting to bring this up. 🙃
