### ISSUE TITLE
Report (99016) Finance Fee Waiver is not in ATD Report Menu (NN) 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12354]
### Is this a permissions issue, or is the report missing from the library? 

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/84c964e9-5b4e-48d8-b6e5-b328fb4ebf28)

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please check my permissions to see if I'm allowed to see this report? If not I'll ask @Sreelatha-BlazeKannan to debug.

**Comment by Nadin-Nader** [comment]
I sent this over to CTM as i also cannot find the report or it is not displaying for me either

**Comment by Nadin-Nader** [comment]
This is now in the menu. I wasnt configured in AMANDA properly, Anu fixed that. Closing but creating a new card for the fact that its not pulling the correct data (query might be wrong)
