### ISSUE TITLE
Enhancement: Add "QA Complete" work orders to the Markings GIS QA (in-house) page

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12364]
## Allow People to see work orders where GIS QA is Complete
- GIS Technicians need to be able to go back to work orders that they've completed GIS QA for

**Desired Outcome?** 
- See Contractor GIS QA page for the example of what we would like to see on the Markings GIS QA page
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/1a9f860d-6964-46e9-b426-282e5b084f6a)

**Comment by dianamartin** [comment]
@ChristinaTremel I think this is fine, will you be pairing together?

**Comment by ChristinaTremel** [comment]
We can pair on it!

**Comment by susannegov** [comment]
# 5/25
- [x] Added `GIS QA | Complete` button to menu view

- [x] Link it to New Page `GIS QA | Complete`
- [x] Copy Grid
   - [x] Source: 
      - Show records that match all of `GIS_QA_COMPLETE is Yes` 
      - Sort `MODIFIED_DATE` chronologically from newest to oldest
      - Limit: Use all available records
   - [x] Settings
      - Keyword Search - The fields being used by this view
      - Record exporting
      - Pagination: Display 25 records at a time. Let the user change the amount. Repear pagination controls below the view
      - Filters: Allow user to add custom filter
         - Which fields can be filters?
            - The fields being used by this view

**Comment by ChristinaTremel** [comment]
# 5/26
Susanne and I reviewed the Markings GIS QA Complete page and it looks good. 

Closing this out and will communicate to the GIS QA team that this page can be used as a resource.
