### ISSUE TITLE
 Urgent Issue for our Transportation department: 2 of 3 ATD Developers are not able to work in, make changes to or create Crystal reports. (Launch IT is working on this) (NN)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#12360]
Urgent Issue for our Transportation department: 2 of 3 ATD Developers are not able to work in, make changes to or create Crystal reports. They have worked with CTM on this to no avail. CTM found that it is likely a configuration issue and a VPN access issue. Crystal needs to be uninstalled and re-installed onto the 2 developers workstations remotely. The VPN access will also have to be looked at to make sure that they are able to connect to, extract, modify and read the Crystal Reports database and its data. Someone will have to remote in to verify the reinstall and config as well as the VPN access.

The two developers emails are (They can also be reached via TEAMS):
Sreelatha B. : ex-Sreelatha.BlazeKannan@austintexas.gov    Her other email is: Sreelatha.b@launchitcorp.com
LakshmiPriya S. : ex-Lakshmipriya.Sureshkumar@austintexas.gov    Her other email is: Lakshmipriya.S@launchitcorp.com

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader 
Update - The connection issue has been fixed , I could connect to Prod database now

**Comment by Nadin-Nader** [comment]
Created a level 2 incident for Sree and sent it to the NIO_INTERNETEDGE team to resolve **INC0301976**
The old incident ** INC0292116**was closed

**Comment by Nadin-Nader** [comment]
This is the error Sree is getting when trying to access Crystal reports. This is config issue and not a network access issue. I asked Paul if we can get Sree a Virtual PC to use Remote Desktop in, waiting on his response. I also asked Sree to have Launch IT install and configure Crystal on a different PC to see if it works. If it does, then that means a not completely deleted Crystal file on Srees PC or soething on her PC is not allowing the correct config of Crystal reports.

![MicrosoftTeams-image (47).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/86b5c8b3-dff0-4bf0-87a2-f3f24086ff23)

**Comment by Nadin-Nader** [comment]
Spoke to Jenice about the error and she gave me her config file to review with Sree to see if it matches up. Sree will also have Launch IT install and configure a different PC with Crystal to see if it works on a different PC other than hers.

@TracyLinder Here is what Paul F. from the network team said:

> [4:06 PM] Nader, Nadin
> 
> Is there anyway we can get her a virtual remote desktop?
> 
> [4:13 PM] Fiero, Paul
> 
> So I have no way to assist with any sort of application installation/configuration.  I don't have rights to servers and I'm not an application person to be honest.
> 
> [4:13 PM] Fiero, Paul
> 
> As for a virtual desktop a Citrix desktop could be set up but that is a whole other approval/deployment process.

**Comment by Nadin-Nader** [comment]
Sree was able to get LIT IT to fix this by reinstalling the OS on her desktop and laptop. Closing
