### ISSUE TITLE
[Enhancement] Add a "Curve Warning" flashing beacon type

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#12369]
As discussed [here](https://github.com/cityofaustin/atd-data-tech/issues/11860#issuecomment-1553595900), we are adding a "Curve Warning" beacon to Moped.

Currently, the Data Tracker captures this beacon generically as type as "Hazard". It would be good to add the "Curve Warning" beacon type to capture this detail. In the future, we may want to link Moped data to these records. These assets are also important for Vision Zero-related safety improvements, so we really should track them.

**Comment by johnclary** [comment]
@ChristinaTremel @dianamartin I'd be happy to make this change since I'm doing #11860. Let me know!

**Comment by ChristinaTremel** [comment]
@johnclary that would be great, thank you! 🙏🏼

**Comment by johnclary** [comment]
as it turns out: "Curve warning" is already an option! I will let the AMD folks know via teams that they might want to switch a few of the "Hazard" type beacons to this type.

<img width="748" alt="Screenshot 2023-06-06 at 11 53 38 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/fbcb7039-aa1e-4abc-a4bc-f3844316bd7d">
