### ISSUE TITLE
Remove reporting fields from Production

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1236]
Per #1203, the  date calculation fields are causing significant performance delays. If we are confident that we can perform reporting in an external tool (Power BI, Insights, etc.) we should remove them from the Knack app before our first work sessions with the Scheduler and Assigner.

**Comment by amenity** [comment]
@SurbhiBakshi - will you estimate this, please?

**Comment by amenity** [comment]
Will this mess with our ability to do basic reporting in Knack, e.g. how many assignments assigned to which schools?

**Comment by SurbhiBakshi** [comment]
@amenity , the (e.g. 'Calculated' number of officers required', Sum of Assigned Officers) in the assignment and officer_assignments objects are causing significant performance delays.  will have to stay for the fields to populate in the app. We won't be removing all the calculated fields. The fields I have looked into and removed in the test instance are the date calculation fields  that were used for reporting. Also the benefit of Power BI is that we will not have to import Brazos records into Knack for reporting.

**Comment by amenity** [comment]
@SurbhiBakshi Okay, have updated the issue description.

**Comment by amenity** [comment]
@SurbhiBakshi - is this still relevant?

**Comment by SurbhiBakshi** [comment]
@amenity - done with this issue, going to close this issue.
