### ISSUE TITLE
Enhancement: Create ETL script to pull financial_subprojects from data warehouse to Finance Knack App

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12376]
Similar to the process for pulling Task Orders into the Finance Knack App, we are now needing to do the same thing for Subprojects. We need to pull financial subprojects information from the data warehouse and push it into the Finance App

## Apps
- Created Subproject table/page - `[financial_subprojects]`
   - [object 45](https://builder.knack.com/atd/finance-purchasing/records/objects/object_45)

## Devs To Do (pulled from issue #10199)
- Pull data from Data Warehouse s3 - Prefect?
- s3 to knack object - Airflow?
  - dependent on date mapping
- frequency - nightly

**Comment by ChristinaTremel** [comment]
Related [Task Order PR](https://github.com/cityofaustin/atd-finance-data/pull/17) for reference.

@dianamartin and I will bring this issue up during Dev + Product Sync to capture any additional details and for scheduling on a future sprint.

**Comment by ChristinaTremel** [comment]
Emailed Bruce on 6/15 and let him know which fields we would like added to the view. He followed up asking some questions and Diana was able to provide answer:
1.  Is there a reason why you are not using MicroStrategy to develop your reports/dashboards?
> We are not utilizing PowerBI or Microstrategy because we are not building a report or a dashboard. We are building a custom feature in our enterprise Knack application platform to reference financial subprojects.
2.  If you are using PowerBI, is there a reason why you are not using the PowerBI plugin to MicroStrategy?
> For this effort, we are not utilizing PowerBI or Microstrategy.
3.  What are you doing with the data
> We are needing a SQL view to bring data into a financial data application we are using to enhance financial service requests for our Finance team.

Followed up with Bruce on 7/12 and he responded:
> Sorry. Budget has been keeping me hopping with lots of changes.  Good news is that it is done.  I hade done it on July 4th.  I failed to send an email though.  The view DEPT_2400_SUBPRJ_VW has been created and can get to the same way as your others.  Let me know if you cannot get to it the same way.

This issue is ready for the Dev team.

**Comment by Charlie-Henry** [comment]
Hey @ChristinaTremel sorry I didn't review Bruce's table earlier but when I access the DB at `MSTR_IA_DEV.DEPT_2400_SUBPRJ_VW` it is only showing data for things involving public health? Not sure if we have selected the wrong department or not?

Here's one row, redacted:
```
  {
    "PROJECT_NUMBER": 6013,
    "PROJECT_NAME": "Building Improvements - Austin Public Health",
    "SUB_PROJECT_ID": 458257287,
    "SP_NUMBER_TXT": 6013.023,
    "SP_NAME": "HHSD Building Renovations",
    "SP_STATUS": "Closed",
    "CREATED_DATE": "09-10-2012 00:00:00",
    "CLOSED_DATE": null,
    "SP_DESCRIPTION": null,
    "SP_JUSTIFICATION": null,
    "SUB_PROJECT_MANAGER": "person, name,
    "SUB_PROJECT_MANAGING_DEPT": "Austin Public Health",
    "PROJECT_TYPE_NAME": "Building Renovation",
    "SP_TYPE_CAT_NAME": null,
    "SUB_PROJECT_LAST_UPDATE_BY": "person, name",
    "SUB_PROJECT_LAST_UPDATE_DATE": "09-10-2012 00:00:00",
    "SP_SUBPROJECT_LOCATION": null,
    "SUBPROJECT_DISTRICTS": null,
    "BUDGET": 6474628
  }
```

**Comment by ChristinaTremel** [comment]
@Charlie-Henry no worries! It definitely seems like it's pulling the wrong department so I'll reach out to him and let him know. 🙃

**Comment by Charlie-Henry** [comment]
Yes looks good now!

```
  {
    "PROJECT_NUMBER": 5771,
    "PROJECT_NAME": "Bikeway Improvements",
    "SUB_PROJECT_ID": 195384908,
    "SP_NUMBER_TXT": 5771.063,
    "SP_NAME": "Trans Enhancement Bicycle Infrastructure Citywide",
    "SP_STATUS": "Closed",
    "CREATED_DATE": "15-12-2010 00:00:00",
    "CLOSED_DATE": "23-12-2015 00:00:00",
    "SP_DESCRIPTION": "To accelerate bicycle infrastructure installation by working with the Street and Bridge Division to efficiently stripe bicycle lanes when roadways are up for routine maintenance.",
    "SP_JUSTIFICATION": "CSJ-0914-04-265",
    "SUB_PROJECT_MANAGER": "last, first",
    "SUB_PROJECT_MANAGING_DEPT": "Austin Transportation",
    "PROJECT_TYPE_NAME": "Bicycle Projects",
    "SP_TYPE_CAT_NAME": "Mobility Infrastructure",
    "SUB_PROJECT_LAST_UPDATE_BY": "last, first",
    "SUB_PROJECT_LAST_UPDATE_DATE": "23-12-2015 09:57:27",
    "SP_SUBPROJECT_LOCATION": null,
    "SUBPROJECT_DISTRICTS": null,
    "BUDGET": 247379
  }
```

**Comment by Charlie-Henry** [comment]
@ChristinaTremel looking at the data in the DB vs whats in Knack there's quite a few that aren't in the DB. We have 388 in the DB and 675 in Knack. Here are the columns I could map between the DB->Knack

```
{
	"PROJECT_NUMBER": "PROJ ID",
	"SP_NUMBER_TXT": "ID"
	"SP_NAME": "Subproject Name",
	"SP_DESCRIPTION": "Subproject Description"
	"SUB_PROJECT_MANAGER": "Subproject Manager",
	"SUB_PROJECT_MANAGING_DEPT": "Dept"
	"ST_STATUS": "Status",
}
```

Missing/not sure what they mean:
- ATD_INTERNAL_SUBPROJECT_ID
- service_request_line_item
- Detail Scope
- FORCEFIELD

**Comment by ChristinaTremel** [comment]
Interesting! I know the `service_request_line_item` and `FORCEFIELD` fields are specific to Knack and wouldn't be in the DB. @dianamartin can you confirm if `ATD_INTERNAL_SUBPROJECT_ID` and `Detail Scope` should also only be in Knack? Or should these fields be coming from eCapri? 

And I'm not sure why there are way less subprojects in the DB vs Knack.. @Charlie-Henry are you able export the data from the DB to a csv or something? So I can try to compare it to the Knack records?

**Comment by Charlie-Henry** [comment]
[Here's the CSV output of the table](https://cityofaustin-my.sharepoint.com/:x:/g/personal/charlie_henry_austintexas_gov/EVyN8CVGeQ5CjSIpOkqQoM4Bdfd2HtECWNcvlcqPVr4yIA?e=XO1ceD)

**Comment by dianamartin** [comment]
@ChristinaTremel cc @Charlie-Henry 
In the knack object table
- `ATD_INTERNAL_SUBPROJECT_ID` - is the auto-incremented ID we came up with
- `Detail Scope` - I believe this field came from eCapri, we should be getting this
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b86e4d44-4bb6-49f8-9836-526bf74f5402)

**Comment by ChristinaTremel** [comment]
@Charlie-Henry Diana and I looked into the 11 rows with blank IDs and these were created accidentally when importing the spreadsheet initially. The `financial_subprojects` records should be completely replaced by the subprojects that you're bringing in from eCapri because the previous records are from fall 2022. 

Also just a heads up I am going to be requesting that Bruce adds Public Works subprojects to the view because legacy Public Works will start using the Finance & Purchasing System soon!

The records in the `TEST | JUL 25 2023 - Finance and Purchasing System` knack app look great. 👏

**Comment by ChristinaTremel** [comment]
Bruce with eCapri has updated the view to include Public Works sub-projects as well!

**Comment by Charlie-Henry** [comment]
I think we should be good to close this one out @ChristinaTremel ?

**Comment by ChristinaTremel** [comment]
Yesss, I agree! Closing this now.
