### ISSUE TITLE
[Power BI] Monthly 311 Reporting in SMD dashboard using ODP 

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#12379]
From Charlie: 
> 
> If you know the SR descriptions you need we can filter this dataset potentially? I see things like
> 
> > ATD - Road Markings/Striping - Maintenance
> > ATD - Road Markings/Striping - New
> > ATD - Traffic Sign Emergency
> > ATD - Traffic Sign Maintenance
> > ATD - Traffic Sign New
> > Sign - New
> > Sign - Parking Sign Maintenance
> > Sign - School Zone Sign Maintenance
> > Sign - Street Name
> > Sign - Traffic Sign Emergency
> > Sign - Traffic Sign Maintenance
> 
> https://data.austintexas.gov/Utilities-and-City-Services/Austin-311-Public-Data/xwdj-i9he
> 

From ODP: [Austin 311 Public Data](https://data.austintexas.gov/Utilities-and-City-Services/Austin-311-Public-Data/xwdj-i9he)

Test trying to get monthly report using this dataset

Reference issue: #11806

**Comment by susannegov** [comment]
# 5/24 
In Power BI > Get Data > From Web I did
`https://data.austintexas.gov/resource/xwdj-i9he.json?$select=sr_type_desc,sr_created_date, sr_closed_date, sr_status_desc&$where=sr_created_date >='2018-10-01T12:00:00' AND sr_type_desc in('Road Markings/Striping - Maintenance','Sign - Parking Sign Maintenance','Sign - School Zone Sign Maintenance','Sign - Street Name','Sign - Traffic Sign Emergency','Sign - Traffic Sign Maintenance','ATD - Parking Sign Maintenance','ATD - Road Markings/Striping - Maintenance','ATD - School Zone Sign Maintenance','ATD - Street Name Sign Maintenance','ATD - Traffic Sign Emergency','ATD - Traffic Sign Maintenance') AND sr_status_desc='Closed'&$limit=100000`

Filters CSRs that were created after `10/01/2018`, that are `Closed` status, and the following CSR Description Types:
- 'Road Markings/Striping - Maintenance'
- 'Sign - Parking Sign Maintenance'
- 'Sign - School Zone Sign Maintenance','Sign - Street Name'
- 'Sign - Traffic Sign Emergency','Sign - Traffic Sign Maintenance'
- 'ATD - Parking Sign Maintenance'
- 'ATD - Road Markings/Striping - Maintenance'
- 'ATD - School Zone Sign Maintenance'
- 'ATD - Street Name Sign Maintenance'
- 'ATD - Traffic Sign Emergency','ATD - Traffic Sign Maintenance'

I set the limit to 100000 and around 22000 records returned

**Comment by susannegov** [comment]
From the 311 Monthly Report 
Report Date and Time: | Jul   1, 2021
-- | --
Open SRs: | Service Request  Currently not in any Closed Statuses:
Closed SRs: | Service Request  Currently in a Closed Status.
Closed Late: | Service Request  that have been completed passed the   deadline
Closed On   Time: | Service Request  that have been completed before or on the   deadline.
Overdue Not   Closed: | Overdue service requests   that are currently not closed.
AVG Response Time   (Days): | Average time it takes to   complete a service request from OPEN status to CLOSED status.

**Comment by Charlie-Henry** [comment]
Fields I got from 3-1-1's sample report. I sent @susannegov the excel file they shared with me. There will be one report for ATD, one for PWD.

- Group Description
- Service Request (SR) Number
- SR Description
- Method Received
- SR Status
- Is Duplicate? (1/0)
- Status Change Date
- Created Date
- Overdue On Date
- Last Update Date
- SR Age (days)
- Response Days
- Close Date
- Open Count
- Closed Count
- Overdue Count
- Closed on Time
- Closed Late
- # of Days Late
- SR Location
- State Plane X Coordinate
- State Plane Y Coordinate

**Comment by susannegov** [comment]
Meeting on 7/17 w/ Christina and Rebekka to do a work session on this

**Comment by susannegov** [comment]
I was able to add the 311 SR to the dashboard from the `austin-csrprod` link to do performance measures.

Some next steps:
- [ ] Have this stored in ODP instead of `austin-csrprod` since if defaults to loading 60k records but would like to filter to only specific workgroups/departments for faster load times on PBI
- [ ] reconnect to ODP

**Comment by susannegov** [comment]
Charlie shared with me the updated 311 SR link that is filtered to this fiscal year. Have a meeting with SMD on 8/3 to do the reconnect and check if the numbers match the 311 SR monthly report

**Comment by susannegov** [comment]
The new 311 SR link was done successfully without issues

**Comment by susannegov** [comment]
On 10/24 from Charlie:

> This dataset should contain CSRs for TPW from the last three fiscal years, you should be able to use this with the SMD dashboard I believe:
https://datahub.austintexas.gov/Transportation-and-Mobility/Transportation-and-Public-Works-311-Service-Reques/38mr-dwji

**Comment by susannegov** [comment]
The Performance Measures report has been connected to the 311 CSR dataset since mid December. Closing issue
