### ISSUE TITLE
Set up docking station — Windows | Mac (see here if you're having issues on Mac. If you have an M1, grant screen recording permissions as detailed here )

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#12374]

**Comment by rebekkabry** [comment]
I didn't have admin access on my computer. Reached out to Scott, who informed I didn't need it now and that my docks were working fine without. Placing item on hold, pending feedback from management.

**Comment by dianamartin** [comment]
@rebekkabry did you need do do anything else for this? If not, you can close this issue.

**Comment by rebekkabry** [comment]
Awaiting confirmation on the following: 
+ Does the wiki for new hires need to be updated? 
+ Once I am placed at my cubicle, does my docking station function? Currently the monitors are going black/static. 

However I can close...as I don't believe I will actually need to download.
