### ISSUE TITLE
[BUG] Corridor Retimings EDP Dataset is creating duplicate records for corridors

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12381]
### Describe the bug

- On the [EDP dataset](https://datahub.austintexas.gov/Transportation-and-Mobility/Corridor-Retimings/bp5z-kciq), there are 153 rows of records for Corridor Retimings. 

- On the Data Tracker [corridor retiming API view](https://atd.knack.com/amd#signal-queries/corridor-retimings/), there are only 24 records.

It seems like data is duplicating and creating new rows when updating the EDP instead of updating existing records. Lance has requested that the existing records are updated instead of new rows being created.

**Comment by ChristinaTremel** [comment]
@chiaberry could you take a look at this? The original request for this EDP dataset is on issue #11181!

**Comment by chiaberry** [comment]
@ChristinaTremel the dataset was missing the ID column, i replaced all the data so there is now only 26 records in it. now that it has and ID column, the upserts should be working. 🤞🏼

**Comment by ChristinaTremel** [comment]
@chiaberry I just happened to check this (and was going to close it out), but noticed the records might be getting duplicated again! :(

**Comment by ChristinaTremel** [comment]
Records are no longer duplicating! Closing this issue.
