### ISSUE TITLE
UC Fee Raw Data Request 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12383]
### The UC Review Fee has been mapping to the wrong funding code but we're not sure for how long. We need to analyze fee data. 

- Related to 12382; don't pull data until the FAO code is updated
- Email data to Tracy & Kyle when done

**Query parameters:**
- Folder is UC
- Fee is `Utility Coordination Review Fee` _(code?)_
- Fee is paid

**Query output columns:**
<div ccp_infra_version='3' ccp_infra_timestamp='1684957438217' ccp_infra_user_hash='881534590' ccp_infra_copy_id='dfac1e92-6dc2-4466-aeb6-32e3b7d3dde2' data-ccp-timestamp='1684957438217'><html><head><meta http-equiv=Content-Type content="text/html; charset=utf-8"><meta name=ProgId content=Excel.Sheet><meta name=Generator content="Microsoft Excel 15"></head><body link="#0563C1" vlink="#954F72">

f.ROWID | Fee Code | Fee Name | Fee Amount | Paidinfull | Paid Date | FAO Code
-- | -- | -- | -- | -- | -- | --

</body></html></div>

**Comment by TracyLinder** [comment]
AC is ready

**Comment by Lpriya-LIT** [comment]
[https://app.zenhub.com/files/140626918/377f4be0-cbd2-43e9-afcf-0b1a09d0bba6/download](https://app.zenhub.com/files/140626918/377f4be0-cbd2-43e9-afcf-0b1a09d0bba6/download)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder Shared the Utility Coordination Review Fee data in email. Attached the file to the card as well

**Comment by TracyLinder** [comment]
### Data Analysis & Closing
- All UC Review fees collected to-date have been applied to code 4098. 
- TPW-Finance should transfer $709,650.00 from 4098 to the correct code.

**Comment by TracyLinder** [comment]
@Lpriya-LIT we want to re-run the query after the prod promotion on #12382

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader #12382 has been promoted to Prod.
The query has been re-run , FAC code is updated. Have share the data in email , attached it in the card as well.
@KyleErich

**Comment by Lpriya-LIT** [comment]
[https://app.zenhub.com/files/140626918/1b8d6919-f532-4734-9898-6878d5addc2b/download](https://app.zenhub.com/files/140626918/1b8d6919-f532-4734-9898-6878d5addc2b/download)

**Comment by Nadin-Nader** [comment]
Sent message to Kyle via TEAMS to let me know if the data was sufficient. Waiting on response

**Comment by Nadin-Nader** [comment]
@TracyLinder is this good to go?

**Comment by Nadin-Nader** [comment]
Got a response from Kyle and he approved that this should be closed.

**Comment by TracyLinder** [comment]
We need to re-run the query now that #12382 is in  PROD
FYI @Lpriya-LIT can you please re-run and email us the data? Thank you

**Comment by Lpriya-LIT** [comment]
@TracyLinder I have re-run the query in Prod and shared data in email.
