### ISSUE TITLE
Meeting 5/24/23: Esri | Government Content Syndication - Pilot Community

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12380]
### ESRI Pilot Demo Meeting & Internal Debrief on 5/24/23
- Mtg recording for ESRI demo is [here](https://cityofaustin-my.sharepoint.com/:v:/g/personal/jacqueline_hrncir_austintexas_gov/ERJfIZCOF2RFkTL2qwf1YZABm8U0UcHhYGiLnsen163Pog)

Original CTM email 3/29/23
>Esri has been developing a new content syndication strategy that would advance our current Community Maps program and position aggregated government content managed in ArcGIS as a source for consumer mapping platforms.   The goal is to help our government customers syndicate their near real-time content (ex. road closures, emergency notices, etc.) to consumer mapping applications so residents in their community have access to this information on the devices they typically use.  
 
>This spring, we are assembling a small group of ArcGIS users to pilot this new initiative and I was hoping the City of Austin might be interested in participating.  If so, I’d be glad to schedule a short call to brief you further and discuss what the pilot will entail.  

Marna said 4/27/23
>Scott Oppmann at Esri reached out to Jacquie/myself a couple weeks ago asking if the City of Austin would like to be a part of a pilot with “consumer mapping platforms” and local data from cities.  The example Esri used was – What if our street closure data was able to be consumed by Waze or Google Maps and presented nearly real-time.
 
>Since Scott used street closures specifically, I wanted to reach out to ATD to see if y’all would be interested in participating or at least having a meeting with Scott to go over his ask.  Let me know!

- Diana emailed to DTS folks 4/27 and 5/3

Tracy said 5/3
>Howdy, this has a bit of crossover with RC3DP so I'm definitely interested and want to be included in the initial discussions. 

Andrew said 5/3
>Yeah this sounds interesting and I would definitely like to learn more about it.

**Comment by TracyLinder** [comment]
### Notes

- Residents want easier access to authoritative data in the apps their already using like apple/google maps (consumer mapping platforms)
-

**Comment by ChristinaTremel** [comment]
### Presentation - Conceptual Design Slide

![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/b441e4c3-c956-4c2e-b029-e1f54fe71341)

**Comment by TracyLinder** [comment]
### Debrief Notes
(Same day, 4pm)


**Do we want to participate in this pilot?**
- Approach this as a project? 
- Who in DTS will be assigned to manage/lead?
- Who will/should comprise the pilot team?



**Thoughts/Discussion:**

**Comment by TracyLinder** [comment]
### Email to Scott (ESRI) & Closing

Hi Scott, 

Our teams met internally to discuss participating in the pilot. TPW would like to participate insomuch as we have existing data sets that would be good candidates for the pilot. Currently we have street event data that Andrew S. thinks is a great candidate. He will be your SPOC for the event data moving forward. 

We discussed road closure data and determined we don't have any qualifying data to provide at this time. As mentioned we have an active project to purchase and implement a [road closure data platform](https://www.austinmobility.io/projects/5154). This project will produce public closure data that would be useful for the content syndication. I'd like to get your feedback on the data schema when we get to that part of the project and I'll followup with you separately about that.  

Please send us all the followup information we discussed; we're looking forward to it. 

All the Best,

Tracy Linder, Product Manager
