### ISSUE TITLE
Develop an MVP QGIS Plug-in for Polygonizing Data

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12399]
Related Issue #12315 - Develop an MVP QGIS Plug-In for Polygonizing Data

## Description
As an analyst/technician, I want to have a Minimum Viable Product (MVP) QGIS plug-in that can efficiently polygonize data. Currently, we have level 5 and 1-4 data, but there is room for improvement, especially in terms of geometry and centerline. The objective is to create new level 5 polygons by addressing intersections, updating IDs, and regenerating the centerlines of level 5 polygons. This tool will greatly assist in maintaining and updating the data.

## Requirements:
- Ability to use the existing level 5 and 1-4 data, with minimal changes to the level 5 polygons.
- Handling of ID updates, allowing for ID reuse and renaming.
- Automatic process for updating or creating new polygons, pushing changes back through QGIS to the database.
- Secure connection to the production database via the bastion host, using appropriate privileges for publishing the updated data.

## Notes
- QGIS is preferred due to its compatibility with postgresql and postGIS, despite being an ESRI shop.
- This project provides an opportunity for the team to expand their knowledge in QGIS.
- Andrew supports the use of QGIS for this specific use case.
- Milad is responsible for updating or creating new polygons, and he finds QGIS to be faster and more efficient for this task.

**Comment by frankhereford** [comment]
I was thinking about this some over the long weekend, and I started trying out different things. I'm excited to show you all what I came up with today in dev sync. ✨

It's not quite MVP quality, but it's a good ways down the path to it.

**Comment by frankhereford** [comment]
An experimental QGIS plugin has been written and accepted into the official [QGIS plugin repository](https://plugins.qgis.org/plugins/qgis-polygonizer/). The source code for the plugin is available under a open source, but personal repo [here](https://github.com/frankhereford/qgis-polygonizer). I have [asked the development team](https://austininnovation.slack.com/archives/CHZE6BC6L/p1685665320407779) for their input on how we should transfer this code to the COA github team, but we have not had a discussion about it yet.

[Here](https://github.com/frankhereford/qgis-polygonizer#features-to-implement) are a few things that will need to be finished for it to become truly useful to whomever is going to be updating the polygons. None of them are particularly big lifts, but if anyone is tasked with using this to make actual polygons that are ready to be put into the existing dataset, they will be asking for these features very quickly.

As it stands, it implements the really hard stuff, namely the making of the polygon geometry. These remaining enhancements are edge cases and helpful functionality, but they have to be handled either by hand or with the plugin, and the latter is really the only way to get fully consistent and useful data out of it.

**Comment by frankhereford** [comment]
This project is going to be superseded by a custom solution being developed internally by the VZ team.
