### ISSUE TITLE
[Enhancement] Add existing "Modified By" and "Modified Date" column to Contractor work orders page table view

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#12393]
> I forgot to count how many contractor work orders I completed yesterday, is there a way for me to see the ones I've closed?

Solution: Add Modified By and Modified Date column to Contractor | GIS QA page in `contractor_work_orders` grid view
`pages/scene_1347`. The `Modified Date` and `Modified By` columns already exists in the `contractor_work_order` object table but the column is not viewable in the GIS QA | Page currently. [Contractor | QA Complete](https://atd.knack.com/signs-markings#work-orders-contractor/contractor-gis-qa/?view_3358_filters=%5B%7B%22text%22%3A%22QA%20Complete%22%2C%22field%22%3A%22field_3831%22%2C%22operator%22%3A%22is%22%2C%22value%22%3Atrue%2C%22key%22%3A%224%22%7D%5D&view_3358_page=1)

![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/f9c93e57-2093-4546-aca9-b49f02b37a00)

@dianamartin I think this is small enough that I can tackle this on my own or pair with @ChristinaTremel if that is okay? I also think this will be a need by the end of this week.

**Comment by ChristinaTremel** [comment]
# 5/26 
Met with Susanne to update the Contractor Work Order table and add Modified By and Modified Date, but realized that they are not able to filter the table the way they need to for reporting GIS QA work orders they've completed.

Need to create new page for GIS QA Complete work orders so we can give them the ability to add filters to the table.

**Comment by ChristinaTremel** [comment]
Sent message to GIS QA team: 
> Hi y'all! Susanne and I made a couple changes to the Markings GIS QA page and to the Contractor GIS QA page. On both pages, there's now a separate button at the top to see the work orders that GIS QA have already been completed on! The table has the ability for you to filter based on Modified By (your name) and Modified Date (if you wanted to see everything you modified for a certain week or something like that). In that completed QA list, you can also go back to work orders that you had previously QA'd! Let us know if you have any questions.

**Comment by susannegov** [comment]
# 5/26
Created the new Contractor | GIS QA page w/ Christina in `https://atd.knack.com/signs-markings#work-orders-contractor/contractor-gis-qa/`

`pages/scene_1533` is the page sorted by newest Modified Date filtered to `GIS QA is Yes`
