### ISSUE TITLE
Developer On-Boarding

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#124]
We've got three (!) new developers starting in June:

- Full-time temp web developer (Mike D)
- Part-time web developer (Tyler W)
- Full time contract data engineer (TBD)

We need to configure accounts, workspaces
- [ ] user accounts
- [x] office workspace
- [ ] more stuff

**Comment by johnclary** [comment]
Onboarding docs:
https://teams.microsoft.com/_#/tab::71ff8061-51bf-42df-9dfd-66e95ff733b9/General?threadId=19:6125816a2bd34142a9b23fc916a968b8@thread.skype&ctx=channel

**Comment by johnclary** [comment]
TODOs

## Mike

### Accounts
- [ ] Network account request
- [ ] Phone request
- [ ] 1Password
- [ ] Slack
- [ ] Google Drive
- [ ] Github Team

### Software
- [ ] VPN Client
- [ ] Zenhub Extension
- [ ] Docking station drive

### Hardware
- [ ] Computer
- [ ] monitors
- [ ] docking station
- [ ] chair
- [ ] power supply
- [ ] keyboard
- [ ] mouse

## Sergio

### Accounts
- [ ] Network account request
- [ ] Phone request
- [ ] 1Password
- [ ] Slack
- [ ] Google Drive
- [ ] Github Team

### Software
- [ ] VPN Client
- [ ] Zenhub Extension
- [ ] Docking station drive

### Hardware
- [ ] Computer
- [ ] monitors
- [ ] docking station
- [ ] chair
- [ ] power supply
- [ ] keyboard
- [ ] mouse

## Tyler

### Accounts
- [ ] Network account request
- [ ] Phone request
- [ ] 1Password
- [ ] Slack
- [ ] Google Drive
- [ ] Github Team

### Software
- [ ] VPN Client
- [ ] Zenhub Extension
- [ ] Docking station drive

### Hardware
- [ ] Computer
- [ ] monitors
- [ ] docking station
- [ ] chair
- [ ] power supply
- [ ] keyboard
- [ ] mouse

**Comment by mateoclarke** [comment]
Connected with SR about hardware. He's going to move your old BO office monitors @johnclary to the overflow desks in the hall.

We're going to move Alan's computer and put Mike there. Sergio also in that row with Matt. If Tyler came in a day other than Monday, he can share a space with Tracy.

Good on universal docks

**Comment by johnclary** [comment]
Beautiful plan! Thanks.

On May 31, 2019, at 13:36, Mateo Clarke <notifications@github.com<mailto:notifications@github.com>> wrote:


Connected with SR about hardware. He's going to move your old BO office monitors @johnclary<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohnclary&data=02%7C01%7CJohn.Clary%40austintexas.gov%7Cfc8830c479df41e41a8508d6e607ac62%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C636949317965018136&sdata=SoXoyi8V%2FfDkJIcYi0DEUZrxUb7uh8dO1KnTKJpf8zA%3D&reserved=0> to the overflow desks in the hall.

We're going to move Alan's computer and put Mike there. Sergio also in that row with Matt. If Tyler came in a day other than Monday, he can share a space with Tracy.

Good on universal docks

**Comment by johnclary** [comment]
@mateoclarke would you get joey's old laptop ready for mike? sergio is going to use his own machine.

**Comment by mateoclarke** [comment]
Getting VPN request forms submitted and figured out is the last task here. I've emailed SR about Citrix vs Cisco...
