### ISSUE TITLE
Sprint Review for Traffic Register 5/30

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12423]
### Participants
Christina, Ed, Dipti, Joshua, Ravi, Karo, Susanne, Diana, Joana, Chrispin, Daniel

------
- [x] Schedule meeting
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [x] Create resulting issues

**Comment by ChrispinP** [comment]
@ChristinaTremel Ive completed most of the action items above. Do we know the Traffic Engineers by Area? Additionally, from experience working with TDS & ROW, we need to determine if they want emails going to an individual person or to an Area inbox. One of the downsides of emailing individuals is if they leave their position, they will continue to receive emails until we update. With an Area inbox we wouldnt have to update and would be more sustainable.

We can also have Eric set the Traffic Engineer for each area himself and he would update accordingly as needed.

**Comment by ChristinaTremel** [comment]
@ChrispinP the Area Engineers don't change super frequently, but I think it's a great idea to set it up where Eric can update Area Engineer!

The Area Engineers are:
- **North**: Dipti 
- **Central**: Lee 
- **South**: Justin
