### ISSUE TITLE
AMANDA TLS1.0 Removal

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12439]
### DTS needs to test any AMANDA integrations to be sure they're not affected. 
- Organized by CTM Information Security, Michael G
- Initial meeting held on 5/31/23

**Comment by TracyLinder** [comment]
**Email sent** to Michael G and Jenice to ask that Frank and I are invited to the actual test meeting that will be scheduled.

**Comment by TracyLinder** [comment]
### Meeting Notes by Michael G.

Team, thanks for coming together.  Notes from our working session are below.  Please advise of any necessary changes.  Best foot forward as we improve our security posture.  Thanks.  –Michael G.

 

 

TLS1.0:  Removal in Amanda Test
 

 

Date:  05/31/2023

Time:  1300hrs

 

Attendees

Michael Goin, Heath Taylor, Jared Rapp, Deanna Davidson, Jenice McKissick, Christopher Dolph, Yinghong Li, Sean McClurkan, Nadin Nader, Victor Cortes, David Rodriguez, Cliff Phillips, Richard Russell, Charles Kirwan, Cliff Phillips, Shawn Lincoln, Jeff Libby, Tonia Tompkins, Frank Hereford, Swapna Thatikonda, George Shirai, Robert Ferris, Aubrey Drescher, Garrett Jaynes, Rashmi Reddy, Anthony Stokes

 

 

Simple Test with ESB

Change profile on F5 for ESB test to no longer use TLS1.0.
Test Amanda client to communicate with ESB test.
Jeff Libby and Swapna Thatikonda will test clients.
Someone from Amanda team would then test clients per their established testing practices.
Do we need SRs from CSRs for testing?  - Yes
They should originate from within the test environment.
After testing the removal of TLS 1.0, we’d like to repeat with the removal of TLS1.1
Testing apps outside of the ESB is additional work.
ESB connects to web services in Amanda.
Endpoint sending messages to is:  [https://coaamdtest.austintexas.gov/axis/services/WSAmandaService.WSAmandaServiceHttpSoap11Endpoint/](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcoaamdtest.austintexas.gov%2Faxis%2Fservices%2FWSAmandaService.WSAmandaServiceHttpSoap11Endpoint%2F&data=05%7C01%7CTracy.Linder%40austintexas.gov%7C93958005c782423f62bc08db620d8a74%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638211582525480369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Lv5wNDml2MiMNsEbq5hiwRKQRnvSL8PlN6Bq8vjzqy8%3D&reserved=0)
[https://coaamdtest.austintexas.gov/axis/services/WSAmandaSecurityService.WSAmandaSecurityServiceHttpSoap11Endpoint/](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcoaamdtest.austintexas.gov%2Faxis%2Fservices%2FWSAmandaSecurityService.WSAmandaSecurityServiceHttpSoap11Endpoint%2F&data=05%7C01%7CTracy.Linder%40austintexas.gov%7C93958005c782423f62bc08db620d8a74%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638211582525480369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NCQknsby7GbRBtcWINX%2BbStuzY16hT0GYixN3WlNHFM%3D&reserved=0)
Two Changes
One for messages out the ESB
One for incoming
 

Change Management

Do test first, then submit change request including the test results.
 

Date for Work

06/01/2023 @ 0900hrs
Michael will set up Teams meeting for collaboration.

**Comment by TracyLinder** [comment]
### Test Followup Email from Michael G:

Team, thank you so much for coming together today.  Notes from our working session are below.  Our findings today indicate Amanda continues to have a dependency on TLS 1.0.  George Shirai, I’ll be reaching out to you discuss potential troubleshooting avenues to steer Amanda away from this old protocol.  Again…thanks, everybody.  –Michael G. 

 

 

 

Amanda Test:  Drop TLS1.0
 

 

Date:  06/01/2023

Time:  0900hrs

 

Attendees

Michael Goin, Charles Kirwan, Robert Ferris, Jared Rapp, Heath Taylor, Rashmi Reddy, Anthony Stokes, Christopher Dolph, Joseph Esquivel, Swapna Thatikonda, George Shirai, Yinghong Li, Victor Cortes, Jeff Libby, Jenice McKissick, Kevin Smith, Debra Sustaita

 

 

Change Two VIPs Over

ESB Test:  10.66.54.8
Amanda Test:  10.66.54.243
 

Tests

Joseph Esquivel – good, no issues.
Swapna Thatikonda – good no issues.
Login worked
Payments worked
Public search worked
Applied permit 23 013754
W worked
GIS worked
Anthony Stokes – FME testing succeeded.
Robert Ferris – No SRs from CSRs came through
Jeff Libby sent them.
Robert can see them in the queue, but ESB is not processing them for some reason.
Robert restarted ESB service (took a while).
He was able to see other items pass through the queue, so not thinking it’s a TLS issue.
Turned on debugger when ESB started back up.
Not properly pulling the lid for Amanda.
Jeff tried sending a message from Amanda to the ESB.
This process worked on 05/30.
Robert saw the messages, so Amanda to ESB seems to be working.
CSR saw that message, too.
ESB to Amanda is not.
Heath rolled back the Amanda Test VIP to let is use TLS 1.0.
Still didn’t work.
Heath rolled back the ESB Test VIP to let is use TLS 1.0.
The process (ESB to Amanda) appears to have started working.
It pulled a lid.
It created a folder for a newer SR and generated them for the previous test messages.
This appears to be the culprit.
 

Findings

Changing the ESB Test VIP back to allow TLS1.0 fixed the issue.
This means Amanda is unable to communicate to/thru the F5 unless it uses TLS1.0.
 

Data Flow:  Amanda to ESB – what is the function:

We’ll need to discuss with Amanda development team.
ESB translates XML from CSR, sends JSON message to Amanda.
Possible SME:  George Shirai
Michael will discuss troubleshooting with George to resolve dependency on TLS1.0.

**Comment by frankhereford** [comment]
I've spun up the docker image which we use for our ETLs to connect to AMANDA, and have tested its ability to connect to both the production read only endpoint that we use for our ETLs and to the test IP provided today during the testing meeting hosted by Michael G.

The test is successful, and we're able to connect via TLS 1.2, and I believe that we have been connecting via TLS 1.2 in the past. While I am able to initiate a connection for TLS 1.3, the server does not present its certificate so it would not be usable. This is a configuration on their end that they have chosen, and is fine really. TLS 1.2 is secure and this information about TLS 1.3 is really an FYI.

I believe that unless anything is changed on the server to affect how TLS 1.2 is handled, we are good to go. Changes to TLS 1.2 have not been discussed. I think we should expect no interruptions on our end with no changes required.

I will continue to track this meeting & email thread, and I expect this TLS 1.0 & 1.1 process to go on for a bit, as there are other systems outside of ours which appear to have dependencies on TLS 1.0 when connecting to AMANDA, namely the Enterprise Service Bus among others.
