### ISSUE TITLE
Add new fields to reimbursable object table and create new "Reimbursable Reporting" page - in Test environment

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12435]
### New Fields to add to the `reimbursable_tracking` object table:
- [ ] New field `Contractor Labor Vendor No.`
>Renamed originally proposed field from "Contractor ID" to "Contractor Labor Vendor No." to match the other related field "Contractor Labor Vendor (Name)"
- [ ] New field `Send to Requester` - yes/no field
- [ ] New field `Invoice Approved` - yes/no field

### New “Reimbursable Reporting” Page: that reflects the fields that Ramona reports on
- [ ] See [fy23_invoicebatches.xlsx](https://github.com/cityofaustin/atd-data-tech/files/11616943/fy23_invoicebatches.xlsx) spreadsheet for details
- [ ] Add advanced search features to search by Batch No

**Comment by ChristinaTremel** [comment]
[fy23_invoicebatches.xlsx](https://github.com/cityofaustin/atd-data-tech/files/11616943/fy23_invoicebatches.xlsx)

**Comment by dianamartin** [comment]
# 6/2 - Build Notes
## New field creation on "reimburseable_tracking" object table
- [ ] New field `Contractor Labor Vendor No.`
- [ ] New field `Send to Requester` - yes/no field
- [ ] New field `Invoice Approved` - yes/no field

## Building the page "Reimbursable Reporting"
- [ ] Create new log-in page (settings similar to Reimbursable pages)
- [ ] Add view "Search" to have advanced search feature abilities to search by `Batch No`
- [ ]

**Comment by susannegov** [comment]
# 6/5 Notes
This is done in TEST
- Added most of the fields. See notes above.
- Need to verify the fields:
   - [ ] What is defined as "Too Small"?
   - [ ] Is the "Approver" tracked in knack or is this an edit coming from SMD staff?
       - If SMD staff is edit, it should pull from list of requester names?
   - [ ] `Approved by Requester` field where is it located?
   - [ ] `CIP` field where is it located/tracked?
   - [ ] `Submitted_to_finance` and `Reimbursement_Processed_by_Finance` are short text fields but they should be date fields?
- Added Advanced Search page view `pages/scene_1481`
   - Filtered by Batch #, Bond, Labor Invoice Date, and FM if it hit budget
      - TK and FDU can be searched by keyword but TK and FDU live in seperate connections
         - Should the Requester ID, Work Order ID, TK and FDU field be a text formula populated by the connection `signs_work_orders` and `markings_work_orders` instead of adding additional columns?

**Comment by susannegov** [comment]
# 6/6 Notes
To make advance search easier for user and make table less cluttered add fields using text formula and conditional rules in the TEST environment.
![Signs   Markings Operations - Reimburseables](https://github.com/cityofaustin/atd-data-tech/assets/31259724/91ceda16-3784-40b8-8024-f95f811a1860)

**Comment by dianamartin** [comment]
# 6/6
- Scheduled time to discuss this with Susanne on 6/7 at 3 pm

**Comment by dianamartin** [comment]
# 6/7
Susanne and I synced and were able to review the prototype build.
## New field creation on "reimburseable_tracking" object table `/object_188/fields`
- [ ] New field `Contractor Labor Vendor No` short text
- [ ] New field `Send to Requester` - yes/no field
   - On spreadsheet it is called `Sent to Requester` as in it was sent not to send?
   - Default No
   - Input Drop-down
- [ ] New field `Invoice Approved` - yes/no field
   - Default No
   - Input Drop-down
 >We decided to wait to ask the SMD stakeholders about the other fields we can add like "CIP Y/N?". We'll wait to get that feedback from the stakeholders when we show the prototype. 
>- Ask about the "too small"?

# Decision
- [ ] You can make the `Work Order ID`, `Requester`, `TK` and `FDU` as text formulas on the `reimburseable_tracking` object

**Comment by susannegov** [comment]
# 6/7 Notes
- Removed the components
- Added empty `CIP` yes/no field as a placeholder in the grid view and the search results view
- `Hide empty columns` for the grid view
- `Hide columns that don't have values` for the Search view

**Comment by dianamartin** [comment]
# 6/16
We met with stakeholders at the SMD Prioritization meeting and show them the updated pages. They are happy with it and gave more feedback re: reimbursable invoice process. 

We compared the spreadsheet that Kati provided that it matches with what Susanne built. 

- Kati was going to sync with Ramona to check that all the fields are being used
- We are going to have Susanne built this out in PROD
- Will close this ticket
