### ISSUE TITLE
New SIF Building Data Batch Job (SR) (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12438]
### New SIF Building Data Report & Batch Job

- **Due no later than 8/11/23**
- - _Similar to #10759_
- Batch job should email on the same cadence as 10759, to the same distribution list. 

FolderRSN | ATD Building # | Building Status | Invoice # | Standard SIF Amount | Existing Land Use Reduction | Affordability SIF Reduction | Trip Capture Reduction | Transit Proximity Reduction | Parking Reduction
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

- FolderRSN
- ATD Building #
- Building Status
- Invoice #
- Standard SIF Amount
- Existing Land Use Reduction
- Affordability SIF Reduction
- Trip Capture Reduction
- Transit Proximity Reduction
- Parking Reduction

----
### Original Submittal from Email request from customer Dan H.

This report is perfect – now I want more 😊. We had shown a report template to the Executive Committee that included some more information, and now I’m wondering if it’s possible to add those to this report. I just had a call with Nate Aubert about a few other things and he showed me where they are. I’ll list them out here, and you can let me know if this makes sense or if I’m speaking gibberish.

 

**From “Fee” tab:**

- Payment Date (I want to be able to show when money was collected, not invoiced. I also want to be able to show how long it took to pay. I believe the “DATEGENERATED” tab shows the date the invoice was created, so with payment date I could calculate duration it was outstanding).

**From “SIF Building Info” tab:**

- Standard SIF Amount – SIF amount straight from the worksheet without any reductions
- Existing Land Use Reduction
- Affordability SIF Reduction
- Trip Capture Reduction
- Transit Proximity Reduction
- Parking Reduction

For these we need to explain the impacts of the policy on the projected collection amounts. I hope these are pretty easy to add as columns. I can use the bill amount column to make sure I get the right number for reductions.

 

Let me know if we should have a call to discuss, or if this is clean and easy. We wouldn’t really need this until our next update in October. If the end of August would be an appropriate goal to get a draft completed, that would give me time to do the calculations I need.

**Comment by TracyLinder** [comment]
### Meeting Scheduled 6/12/23
_To discuss criteria_

**Comment by TracyLinder** [comment]
### Scoping Mtg Notes

**Q's**

- [ ] Update existing report or create new?
- Both? Add payment date to existing, and create new report for the extra data. 
- [ ] Output type?

**Comment by TracyLinder** [comment]
### Question for Sree

- Can we add this report to the existing batch job, or is it better to create a new job?

**Comment by TracyLinder** [comment]
### Update to Customer (Dan) 
Hi Dan, this has been pending my review for a few weeks (along with other work) as I worked on a priority budget encumbrance for a huge purchase. I'm playing catchup now and just reviewed the updated data results with Sree this morning. I asked her to rearrange a couple of columns and investigate the few duplicates that are happening.

Ideally we'll start promoting the updates to AMANDA PROD by early next week. 

Thank you for your patience!

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in Progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - 
New Batch Report Creation is required. And SIF Building info Raw data has been sent for your review, so that I can create a batch job. Since it is similar to #10759 batch job; can I schedule this also for every week Monday. 
[12438 - 08302023 SIF Building Info.xlsx](https://github.com/cityofaustin/atd-data-tech/files/12479131/12438.-.08302023.SIF.Building.Info.xlsx)

**Comment by TracyLinder** [comment]
### Review Notes for @Sreelatha-BlazeKannan 
- On Building status, it should display the status description instead of the code
- Remove the duplicate column for Parking Reduction
- Add a new column for Total SIF Collection Amount. Place it in the 6th column, after Standard Sif Amount
- Send me the data again for review

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Updated query data attached. Please review and let me know your thoughts.
[12438 - 08302023 SIF Building Info.xlsx](https://github.com/cityofaustin/atd-data-tech/files/12480162/12438.-.08302023.SIF.Building.Info.xlsx)

**Comment by TracyLinder** [comment]
I emailed the data to Dan and asked for his review feedback. 
FYI @Sreelatha-BlazeKannan the data looks great. Thank you.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan Dan approves; please move to PROD.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP Submitted to create a query for quick and simple report. Kindly review and approve the same. Once it goes to DEV, need to create the batch job in DEV for manual promotion.

Commit ID: [7d0000072aee](http://coaamandadevops02.austintexas.gov/R5:7d0000072aeeaffaf78c67a93603105f14604c94)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team and the CTM team to be deployed to TEST under the following requests:

**SCTASK0357033 DevOps
SCTASK0357037 Manual**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - This is deployed to TEST; both New SIF job creation and Batch job creation on Friday itself. It should have run in TEST today Monday; If everything looks good in TEST, this can be promoted to PROD. Need confirmation from Tracy. thank you!

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team and CTM to be deployed to PROD under the following TASKS

**Manual	- SCTASK0360677
DevOps	- SCTASK0360679**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Verified in PROD & all looks good in Batch job; this should have run last night for the first time in PROD. Please confirm and if all looks good, this can be closed.

**Comment by TracyLinder** [comment]
Sent Dan a message asking for PROD confirmation

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Updated DEV & TEST Email addresses as test/my email address; Both in DEV & TEST jobs Active Flag was already set to 'N' and verified in Job instances no indication of it job running this week. So this can be closed.

**Comment by Nadin-Nader** [comment]
User received accurate PROD reports. Closing
