### ISSUE TITLE
Add data to SP Query

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12431]
### Stakeholder asked us to add the mailing address to existing data pull.

Add 4 columns:

1. House Number + Prefix + Street Name + Street Type
2. City
3. State
4. Zipcode

<img width="1228" alt="Screenshot 2023-05-31 at 11 08 04 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/49930868/2ccbb144-8a5e-44af-bab0-261356196e7a">

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Sent an email with Data by adding the People address column as per AC.

**Comment by TracyLinder** [comment]
Sent [data](https://cityofaustin-my.sharepoint.com/:x:/g/personal/tracy_linder_austintexas_gov/ESoahFWDaMtCi1hu5Ujmyi0BdiN5mOjWUOU-8Jx_npDpmg?e=CE7q9K) to Nathan. **Closing**
