### ISSUE TITLE
BUG: Bills Associated with some Voided payments cant be Cancelled (INC0296337) (On PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#12440]
**There are a number of bills that are associated with VOIDED payments that cannot be cancelled. **

**RSNs**: 13139216, 13139340, 13138631,  13138650,  13138663,  13140385, 13139130, 13139144, 13143853,  13144695,  13144514, 13145460,  13147009

**Service Now Ticket:** INC0296337

**StakeHolder:** Isabel P.

**Comment by TracyLinder** [comment]
### Troubleshooting
_I think this is related to the $0 bill issue we've encountered before and has to be fixed by CTM._

- I looked at 2 examples, both have a $0 balance. Both displayed this error when attempting to cancel the bill:
![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/6ff96589-2102-47f8-8c5a-9082a5278f07)

**Comment by Nadin-Nader** [comment]
@TracyLinder i have sent this over to CTM and mentioned it should be reviewed by Swapna and Victor. I also made it a Level 2 issue

**Comment by TracyLinder** [comment]
**Test Case (Could Help)**

2023 013538 000 00 GF
1. Created the folder as COS
2. System paid w/ COS payment
3. Voided the payment
4. ❌ The system didn't update the bill table - bill shows as outstanding with a $0 balance. It should been $442.00

**Comment by Nadin-Nader** [comment]
Victor is assigned to the Incident

**Comment by TracyLinder** [comment]
### We need to followup with CTM.

**Comment by Nadin-Nader** [comment]
@TracyLinder Looks like Victor closed the ticket. Do we have more examples of Voided Payments that cant be cancelled?

**Comment by KyleErich** [comment]
@Nadin-Nader Was there a rationale provided for Victor's closing of the ticket?

**Comment by Nadin-Nader** [comment]
Per The ticket comments by Victor:

Resolution steps:  Yuan ran the script, informed Isabell that the bills can now be cancelled.

**Comment by Nadin-Nader** [comment]
Sent TEAMS message to Kyle to UAT this. Waiting on response

**Comment by Nadin-Nader** [comment]
This has been UATd and approved by Kyle and Isabel. Closing
