### ISSUE TITLE
Meeting: Status of ROW Permitting Metrics Project

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12455]
### Determine the need, priority, and next steps for this project.
- 6/5/23
- Tracy, Charlie, Ryan, Paloma, Darren

**Comment by KyleErich** [comment]
@TracyLinder, you can add my name to this since I'm now involved with ROW's metrics. Thanks

**Comment by amenity** [comment]
@TracyLinder notes if you want
