### ISSUE TITLE
Bug: Report (99016) Finance Fee Waiver is not pulling the correct data on TEST and PROD (LP) 

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#12466]
Report (99016) Finance Fee Waiver is not pulling the correct data on TEST and PROD, it's showing only 2 adjustments for the last year.

![99016 Finance Fee waiver report.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/ce88ac3b-409f-43da-9f09-3fa5e68da031)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Test, Ready for UAT

**Comment by Nadin-Nader** [comment]
Sent Kyle a message on TEAMS asking him to UAT this on TEST. Waiting on response

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Kyle cant really see on TEST the data it not pulling but has approved the move to PROD. 
I think if we get it to PROD he can UAT this better but if it doesnt work we will have to roll this back
Kyles Message:

> [4:27 PM] K, Kyle
>     
> 12466: Approved, I think? I'm not sure exactly if this is UAT'able since I can't check for what the report might not be pulling.

**Comment by TracyLinder** [comment]
### Friday ROW Review 6/30

- Kyle needs raw adjustment data to determine if the numbers on the report are correct / all things are showing. The report format looks good, there is a lot of data in it, **but we can't validate the data, we don't have data to validate it against.**
- Tracy is asking for the report query to get an understanding of what this report is pulling. We need to confirm it's checking all the things it needs to check. Then pull the data for validation. 

- [ ] Tracy will email the list of GL Codes to ROW, TDS, OSE, Finance to gather input. Do we have all the codes, do any need to be removed? 



**Report Query:**

SELECT 
  vl.lookup3 AS WaiverGroupCode
, vl.LOOKUPSTRING AS WaiverName 
, count(abf.feeamount) AS CountofFee
, sum(abf.feeamount) AS SumofFee
, sum(abfp.Parmunit) AS SumofParmUnit
, abfp.parmresult AS Parmresult
, vl.lookup1 AS LookupParmresult
FROM accountbillfee abf
JOIN  accountbillfeeparameter abfp 
ON abf.accountbillfeersn = abfp.accountbillfeersn
AND TRUNC(abf.STAMPDATE) BETWEEN  {?FromDate} AND {?ToDate}
JOIN validlookup vl ON vl.lookup1 = abfp.parmresult
AND vl.lookupcode = 70000
JOIN accountgl ag ON abf.accountbillfeersn = ag.accountbillfeersn
AND ag.GLACCOUNTNUMBER IN (
'5090-5300-9300-4163-0000-0000-0000-0000-0000',
'5125-2400-8790-8500-0000-0000-0000-0000-0000',
'5125-2400-9100-4057-0000-0000-0000-0000-0000',
'5125-2400-9100-4059-0000-0000-0000-0000-0000',
'5125-2400-9100-4062-0000-0000-0000-0000-0000',
'5125-2400-9100-4082-0000-0000-0000-0000-0000',
'5125-2400-9100-4087-0000-0000-0000-0000-0000',
'5125-2400-9100-4089-0000-0000-0000-0000-0000',
'5125-2400-9100-4098-0000-0000-0000-0000-0000',
'5125-2400-9100-4138-0000-0000-0000-0000-0000',
'5125-2400-9100-4163-0000-0000-0000-0000-0000',
'5125-2400-9100-4163-0000-0000-0000-0000-0000',
'5125-2400-9100-4176-0000-0000-0000-0000-0000',
'5125-2400-9100-4187-0000-0000-0000-0000-0000',
'5125-2400-9100-4233-0000-0000-0000-0000-0000',
'5125-2400-9100-4477-0000-0000-0000-0000-0000',
'5125-2400-9100-4502-0000-0000-0000-0000-0000',
'5125-2400-9100-4874-0000-0000-0000-0000-0000',
'5125-2400-9770-4502-0000-0000-0000-0000-0000',
'5126-2400-9100-4062-0000-0000-0000-0000-0000',
'5126-2400-9100-4176-0000-0000-0000-0000-0000',
'5127-2400-9100-4062-0000-0000-0000-0000-0000',
'5127-2400-9100-4176-0000-0000-0000-0000-0000',
'5128-2400-9100-4062-0000-0000-0000-0000-0000',
'5128-2400-9100-4176-0000-0000-0000-0000-0000',
'5129-2400-9100-4176-0000-0000-0000-0000-0000',
'5130-2400-9100-4176-0000-0000-0000-0000-0000',
'5610-2400-9200-4094-0000-0000-0000-0000-0000',
'5610-2400-9200-4874-0000-0000-0000-0000-0000') 
GROUP BY abfp.parmresult, vl.lookup1, vl.lookupstring, vl.lookup3

**Comment by TracyLinder** [comment]
Pending ROW, TDS, OSE, and finance review of GL codes in the report query.

**Comment by TracyLinder** [comment]
### Method for Validating the Data


Raw Data Query:
- For these fee codes 5090, 5000, any negative fee amount, and fee was inserted between 6/1 and 6/30. 
- Email report data to Tracy, Kyle, Paloma, Nate

Ideally we only get 6 results. 




![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/6b52401e-14bb-4e0d-936f-5a93ec9d6aa6)

**Comment by TracyLinder** [comment]
<img width="849" alt="Screenshot 2023-06-30 at 3 33 00 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/49930868/3eca1559-ffa5-484c-b91b-8d2fd0514b95">

**Comment by TracyLinder** [comment]
### Email to TPW Finance on 7/7/23

Hello, 

My team is debugging [an issue](https://github.com/cityofaustin/atd-data-tech/issues/12466) with AMANDA's Finance Fee Waiver report not pulling in the correct data. The report queries the fee waivers using a list of TPW funding codes. Ask: Can TPW finance review the list of funding codes below for completeness? Specifically, are there any codes for TPW AMANDA fees missing? 

Side note: I need to send a different email regarding updating these codes for the merger. 

'5090-5300-9300-4163-0000-0000-0000-0000-0000',
'5125-2400-8790-8500-0000-0000-0000-0000-0000',
'5125-2400-9100-4057-0000-0000-0000-0000-0000',
'5125-2400-9100-4059-0000-0000-0000-0000-0000',
'5125-2400-9100-4062-0000-0000-0000-0000-0000',
'5125-2400-9100-4082-0000-0000-0000-0000-0000',
'5125-2400-9100-4087-0000-0000-0000-0000-0000',
'5125-2400-9100-4089-0000-0000-0000-0000-0000',
'5125-2400-9100-4098-0000-0000-0000-0000-0000',
'5125-2400-9100-4138-0000-0000-0000-0000-0000',
'5125-2400-9100-4163-0000-0000-0000-0000-0000',
'5125-2400-9100-4163-0000-0000-0000-0000-0000',
'5125-2400-9100-4176-0000-0000-0000-0000-0000',
'5125-2400-9100-4187-0000-0000-0000-0000-0000',
'5125-2400-9100-4233-0000-0000-0000-0000-0000',
'5125-2400-9100-4477-0000-0000-0000-0000-0000',
'5125-2400-9100-4502-0000-0000-0000-0000-0000',
'5125-2400-9100-4874-0000-0000-0000-0000-0000',
'5125-2400-9770-4502-0000-0000-0000-0000-0000',
'5126-2400-9100-4062-0000-0000-0000-0000-0000',
'5126-2400-9100-4176-0000-0000-0000-0000-0000',
'5127-2400-9100-4062-0000-0000-0000-0000-0000',
'5127-2400-9100-4176-0000-0000-0000-0000-0000',
'5128-2400-9100-4062-0000-0000-0000-0000-0000',
'5128-2400-9100-4176-0000-0000-0000-0000-0000',
'5129-2400-9100-4176-0000-0000-0000-0000-0000',
'5130-2400-9100-4176-0000-0000-0000-0000-0000',
'5610-2400-9200-4094-0000-0000-0000-0000-0000',
'5610-2400-9200-4874-0000-0000-0000-0000-0000')

Thank You,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
I will followup with finance. I think they responded to my previous email and I haven't updated this yet.

**Comment by TracyLinder** [comment]
### Email sent to finance
Reminded Van that this is pending her review of the funding codes.

**Comment by TracyLinder** [comment]
### Update
- Van responded with her review of GL codes `I need to add that info to this card.`
- Priya says we can improve the way we have this report configured so it's easier to maintain. She suggests moving all the GLs to a lookup code, and have the report query fetch the codes from the lookup instead of hard-coding.

**Comment by TracyLinder** [comment]
The active fee documentation has not been updated, so I can't add the list of GL codes just yet. I'm adding #14113 as a blocker. 
FYI @vschandramouli

**Comment by Nadin-Nader** [comment]
@vschandramouli is this good to go?

**Comment by Nadin-Nader** [comment]
Per Vish, all documentation is complete. closing
