### ISSUE TITLE
Export AMANDA TIA location for mitigation backfill (LP)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12479]
### Export location records for the 110 remaining historical mitigation records that don't have any location reference. 
`The export was unsuccessful; historic case ID's don't map to a singular field in AMANDA `

- [x]     - [ ] @ChrispinP will export case ID's for the blank records & add to the issue 
- [x]     - [ ] AMANDA dev will export AMANDA location data using the case ID's & add to issue & email to team
- Drew will use the data to backfill the remaining records

----
**AMANDA Data Pull Info:**

- Query on TIA folders
- Query by the `TIA Sequence ID` in the [KNACK export](https://github.com/cityofaustin/atd-data-tech/issues/12479#issuecomment-1577284955)
- For each ID grab the following fields:
    - Sequence#
    - Folder ROWID
    - Primary Folder Property fields: 
        - House Number + Prefix + Street Name + Street Type 
        - City + State + Zip code

**Comment by ChrispinP** [comment]
[TIA_Mitigations_Missing_Project_Locations_06.2023.csv](https://github.com/cityofaustin/atd-data-tech/files/11655640/TIA_Mitigations_Missing_Project_Locations_06.2023.csv)

111 Mitigation Records with Missing Project Locations attached. I included any important identifying fields. Additionally the Project Address field is present to be filled in.

**Comment by TracyLinder** [comment]
Meeting w/ Priya today at 4 to discuss the data pull requirements.

**Comment by TracyLinder** [comment]
### Update/Blocker

- Priya queried by the sequence number and it returned no results. 
- The sequence number must be KNACK generated. I'll sync up with @ChrispinP to discuss possible alternatives.

**Comment by TracyLinder** [comment]
### Outcome & Closing

- The KNACK data available couldn't be mapped to a singular field in AMANDA. 
- Remaining locations can be manually searched by AMANDA users. I scheduled a training. #12951
