### ISSUE TITLE
Try geocoding Brazos data that we can currently access

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1248]
@SurbhiBakshi please explain what you did with this and link to/screenshot results. 🙏

**Comment by SurbhiBakshi** [comment]
![image](https://user-images.githubusercontent.com/13035849/72936671-49406100-3d2d-11ea-8c64-daacf7b13888.png)

**Comment by SurbhiBakshi** [comment]
Manchaca records need to be Menchaca

**Comment by SurbhiBakshi** [comment]
Reasons for Unmatched records 
-  no street number 
- Manchaca records
- No Prefix direction (700 Oltorf instead of 700 E / W Oltorf) 
- I35 instead of IH 35

**Comment by SurbhiBakshi** [comment]
![image](https://user-images.githubusercontent.com/13035849/72937162-337f6b80-3d2e-11ea-8eda-4dde459b624c.png)

**Comment by SurbhiBakshi** [comment]
340 out of 2306 records don't have street numbers, possible intersections

**Comment by amenity** [comment]
Brazos Export: APD Citations from 2019-09-03 through 2019-10-31


  |   | Percent
-- | -- | --
Total records | 2305 | 100.00%
Successfully geocoded | 1765 | 76.57%
No Block Number | 340 | 14.75%
"I35" instead of "IH 35" | 2 | 0.09%
"Manchaca" instead of "Menchaca" | 9 | 0.39%
Tied | 6 | 0.26%
Other | 183 | 10.37%
