### ISSUE TITLE
Launch Knack, atd-service-bot, and Github updates

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#12481]
The launch party is scheduled for 7/10 at 3pm. 

**Apps**
- [x] Add a banner on [DTS Service Request](https://atd.knack.com/dts#new-service-request/) page with an outage message
- [x] Hide form
- [x] Update choice values for "Workgroup" with revised [TPW divisions](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=968067157)
- [x]  Update choice values for "What application are you using?" with revised [list of applications](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=1546625311)

**Dev**
- [x] Pause service bot DAGs in Airflow v2 and give a heads up to the service desk primary (so they don't expect service requests to be coming in) and devs (so no one turns the DAGs back on)
- [x] Mike merge [PR](https://github.com/cityofaustin/atd-service-bot/pull/57)
- [x] Re-run issues to Socrata DAG 

**Product**
- [x] Update ["Workgroup" Github labels](https://github.com/cityofaustin/atd-data-tech/labels?q=workgroup) to match revised [TPW Divisions](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=968067157)
- [x]  Update ["Product" Github labels](https://github.com/cityofaustin/atd-data-tech/labels?q=product%3A+) to match revised list of [Applications](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=1546625311)

**Next Day**
- [x] Check [Socrata dataset](https://data.austintexas.gov/Transportation-and-Mobility/ATD-Data-Tech-Services-Issues/rzwg-fyv8/explore/query/SELECT%0A%20%20%60id%60%2C%0A%20%20%60number%60%2C%0A%20%20%60state%60%2C%0A%20%20%60pipeline%60%2C%0A%20%20%60title%60%2C%0A%20%20%60workgroups%60%2C%0A%20%20%60body%60%2C%0A%20%20%60labels%60%2C%0A%20%20%60estimate%60%2C%0A%20%20%60milestone%60%2C%0A%20%20%60created_at%60%2C%0A%20%20%60closed_at%60%2C%0A%20%20%60updated_at%60%2C%0A%20%20%60url%60%2C%0A%20%20%60is_epic%60%2C%0A%20%20%60position%60/page/filter) to make sure labels are updated there
- [x] Update ["Workgroup" Github labels](https://github.com/cityofaustin/atd-data-tech/labels?q=workgroup)
- [x] Update ["Product" Github labels](https://github.com/cityofaustin/atd-data-tech/labels?q=product%3A+)

**Comment by mddilley** [comment]
The PR for the code updates is approved and ready for Monday! I added a link to it above.

**Comment by mddilley** [comment]
I checked on the ETLs this morning, and:
- the intake script that runs every 3 minutes hasn't failed once since the launch ✅
- the issues to Socrata script ran successfully last night ✅
- the update "Project Index" labeled issues script (GitHub -> Knack) also ran successfully last night ✅

That matches up with what we expect to see if nothing broke on the code side. 🚀

**Comment by amenity** [comment]
I checked Socrata and all the Github labels. Everything is looking good! Thanks, @mddilley @dianamartin
