### ISSUE TITLE
Meeting: Review mitigation data to publish on web map

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12480]
### Internal DTS meeting to review available data that will be published on the Mitigation WebMap 
- Tracy, Chrispin, Andrew
- 6/6/23
- Recording [here](https://cityofaustin-my.sharepoint.com/:v:/g/personal/tracy_linder_austintexas_gov/Ectmoo0FaYlGsWZmlsuqIRoB7SCJALqCMUxxPQw7tiej5A)

**Comment by ChrispinP** [comment]
Sent Andrew the TIA Mitigation Data in preparation for this

**Comment by TracyLinder** [comment]
### Mtg Notes:


What info does the end-user need to see? 

- Historical TIA cases will be missing most of the case-level data. Perhaps a disclaimer. 

### Two Categories/Levels of Map Data
1. Project level data (Case details)
2. Individual mitigation data
    - Only include mitigation types that represent money we collected and need to disperse (Fee-in-Lieu, Fiscal, & Unidentified)
3. ;lskdjf



**Filter By:**
- Mitigation Type (M)
- Case Type (C)
- Improvement (M)



No standard list of discovery questions for new web map requests?
Fields needed for visualization
Filter by? 
Layers? 



Fields:
Mitigation Type

**Comment by TracyLinder** [comment]
@ChrispinP create a miro board for this project.

**Comment by TracyLinder** [comment]
## Notes


- We still need to identify the data we publish for each mitigation layer (case / mitigation)
- @ChrispinP will create a miro board for the project

- Historical TIA cases will be missing most of the case-level data. Perhaps a disclaimer. 
- What are the user needs? 
    - User research needed

**Fiscal**
- There are at least 2 mitigation page views; via [TIA Case](https://atd.knack.com/development-services#tia-reviews/tia-case-details/64823754151a710028cd6189/tia-mitigation-details/64823754151a710028cd6189/) or via the [TIA Mitigations ](https://atd.knack.com/development-services#tia-mitigations/tia-case-mitigation-details/6470f4b45844a60029b5397d/)
    - Why? Do we still need 2 views?  
- Tia Case Mitigation details page details doesn't have a field for mitigation fee total; it has one for construction totals
- Do we want to publish fiscal data?




----
## Map Details


**Map View:**

- Map highlights all mitigation segment/intersection ID's in the mitigation records.
- Each dot = 1 TIA Case
- User clicks the TIA Case to view details and related mitigation records. 


### Two Categories/Levels of Map Data
1. Project level data (Case details)
2. Mitigation level data (Mitigation details)
    - ❓Should we only include mitigation types that represent money we collected and need to disperse (Fee-in-Lieu, Fiscal, & Unidentified) ❓ _User research needed_

### Data to Publish by Category/Level

**Project Level / Case Details**
- Project Name
- Status
- ???


**Mitigation Details**
- Number of Mitigation Recommendations
- Improvement
- ???

**Filter By:**
- Case Type (C)
- Improvement (M) `Map label should say Improvement Type`
- Council District (C)
- TIA Need ❓_(There are 2 fields w/ this data currently. Tracy doesn't recommend; data integrity issues.)_
- Review Area
- SIF District (GEO would need to generate the data in the map; not currently in TIA datasets. Relatively easy lift.)
