### ISSUE TITLE
Create new report for "Assigned" Promo codes for export to vendor

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12492]
Diego/Eliza
SMO

for Metrobike Employee Benefit Program
- Create new report 
- table that shows "Assigned" codes for previous month
- function: exportable
- Field Names, same as "Manage Codes" fields
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/43155810-2703-450a-8606-2cae9a06f3f8)

**Comment by KaroEngstrom** [comment]
I can do this, thanks! 🙏

**Comment by KaroEngstrom** [comment]
## T 6/6/23
- built [page](https://github.com/cityofaustin/atd-data-tech/issues/12492) from the existing Reporting page 
- added grid for last month's assigned codes; modeled after the Manage Codes page
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/fa51c8ac-e8e3-4962-a566-5372327a7a58) 
- let Eliza know via Teams; she responded that "This looks great!"
- Eliza will report if any other column is needed; she cannot think of any right now
- updated change log
