### ISSUE TITLE
Procure Business Consulting Services for Zappfy

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#125]
DTS needs to put in a PR for business consultation services. 

Business Justification: 
>Data and Technology Services needs business consulting services from a Knack software web development company, Zappfy to assist in the development of project requirements for the Mobility Project Enterprise Database technology project. 

>Amenity Applewhite is seeking out these services. She would like to walk through the process with the Zappfy consultant and get a general recommendation on implementation in our Knack system.

**Comment by amenity** [comment]
Sat in purchasing for six weeks but... done!
