### ISSUE TITLE
Scheduler should be able to delete assignments

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1252]

**Comment by amenity** [comment]
@SurbhiBakshi, estimate please. :)

**Comment by SurbhiBakshi** [comment]
Only assignments in the future  (after today) can be deleted. 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/26ae48a9-7e93-438f-9f77-99f44878213e)

**Comment by amenity** [comment]
Looks good, @SurbhiBakshi !
