### ISSUE TITLE
Create ROW Dashboard for Paloma's Reporting

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#12528]
Paloma from Right of Way management division wanted us to create a separate dashboard just for her weekly reporting. We have the ETL completed and it is pushing weekly totals into [this open data portal dataset](https://data.austintexas.gov/Transportation-and-Mobility/ATD-Right-of-Way-Permit-Totals-by-Week/ij2v-mrv3). Each row in this dataset should be what she's looking for in the table she reports out each week.

Here's a snippet of her report:

Week Ending | Number of Applications Received (* = holiday dips) | Extension Requests | Driveway/Sidewalk Requests (*number now includes SmartSheet and online requests) | Total | Time Before Application is Reviewed (days) | Active Permits (does not include Special Events permits nor License Agreements)
-- | -- | -- | -- | -- | -- | --
September 5th | 364 | 148 | 123 | 635 | 8 | 2,895
September 12th | 285* | 228 | 96 | 609 | 10 | 2,942
September 19th | 344 | 186 | 74 | 604 | 9 | 3,023
September 26th | 417 | 217 | 28 | 662 | 9 | 3,044
October 3rd | 311 | 161 | 70 | 542 | 10 | 3,008

TODO:
1. Connect to the dataset in Power BI
2. Rename the columns (we can just convert them to regular text like: ds_permits_issued to DS Permits Issued).
3. Clean up the data, looks like we have some weeks that are in the future in the dataset. Add a filter so we can just look up to the current week.
4. Create a table visual with dataset's columns
5. See if you can match the columns in Paloma's report (we don't have data for time for review or active permits (yet))
6. Publish it up to Power BI Premium workspace and set up automated refresh

**Comment by rebekkabry** [comment]
Getting clarity on definitions for dataset columns, currently not able to regenerate Paloma's results based on current details. 


![Palomas Inquiry _ 12528](https://github.com/cityofaustin/atd-data-tech/assets/134445095/0c7745f3-d6d9-4680-867e-c1ae7af85a77)

**Comment by Charlie-Henry** [comment]
@rebekkabry 

I updated the column metadata here:
<img width="1058" alt="Screenshot 2023-06-12 at 1 30 31 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/30810522/914bcb8d-7971-44f6-b255-8faa7c4e0cbd">

- `ex_applications_recieved` is for excavation permits. We have an `extension_requests` column for extension requests.
- `date` should match the week ending dates used in Paloma's report.
- Number of applications is the sum of RW + EX permits received.
- `ds_applications_received` is driveway/sidewalk, correct.
- Total looks to be the sum of all permit type requests + extension requests.
- Ignore time before application review
- Ignore active permits for now, I have a separate dataset we can pull in for that

**Comment by Charlie-Henry** [comment]
I should also note we will not match Paloma's report since things change with this data quite frequently after she send out an update. We just need to be in the ball park.

**Comment by rebekkabry** [comment]
Current Draft of Dashboard. 

+ Phase 1

- [ ] Remove Type of Request Slicer (add to phase 2, include WOW/YOY metrics)
- [ ] Add current and/or previous week filter in time slicer 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/f23b7012-7388-4ca6-a62e-03def0e66ebd)

**Comment by rebekkabry** [comment]
Updated draft per Phase 1 edit needs: 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/9de07d1c-5044-4f8c-b268-838b21cf480b)

**Comment by rebekkabry** [comment]
Update draft, addressing date filtering issues and clarity. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/a2149dd5-da51-4e6a-a14b-198860549c7b)

**Comment by rebekkabry** [comment]
Updated draft; addressing date filtering for clarity, removed future dates from drop down. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/fb825476-ab80-49d8-8915-e015eb0f1ef6)

**Comment by Charlie-Henry** [comment]
email Paloma, will wait to hear back if she has any requested changes

**Comment by amenity** [comment]
@TracyLinder - same here... Can you stand in for Paloma?

**Comment by rebekkabry** [comment]
Last week Charlie, Tracy and Rebekka met with Palamo for Q/A on ROW Dashboard. Feedback below: 

> Paloma advised the current report is about 0-8+- differential from  her current report. We will follow up next week to ensure the differences are  minute and we have proper disclaimers or understanding of variation. (Week of 8/1 example: 56/50; 331/328; 197/199. 
>> Paloma has Ex and RW as one sum, not broken down. 
> The team is pleased with the report. 
> ROW requested validation testing, scheduled 8/7
> Jim Dale requested insight into these metrics. 

- [ ] Performance Review of Dashboard scheduled for 8/7/2023 AM. With Charlie, Rebekka and Paloma. 

**Dashboard Updates Requested.** 
- [ ] Paloma requested to have the "Number of Applications Received" removed. 
- [ ] Update performance metric title to RW instead of ROW
- [ ] Add in Oldest permits in Que and Number of Active Permits.

**Comment by rebekkabry** [comment]
- [ ] Work on visual framework options for dashboard. 
- [ ] Include: YOY (possibly by WOY) 
- [ ] Consider framework to match current email structure (easy to read, clean)

**Comment by rebekkabry** [comment]
### Version 2 - MVP Edits - working progress

- Considering: 
   -  including line graphs with the bar graphs 
   -  sorting bar graph by week of year, currently out of order 
   -  include total data/or restructure the totals currently visible 

***View
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/9addf715-e25f-4b54-be50-891be5d9a582)

***another grouping/view option**
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/163c93c5-207d-4ab1-85cf-f9d71a798f59)


***another grouping/view option by multi week per year***
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/0ac770e6-0e13-44d8-9fb4-e0d483bbf8f3)


***another view***
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/49f73edf-b111-4a90-9ce4-02101ece3a3b)

**Comment by rebekkabry** [comment]
Pros: MOM/YOY view of activity in line graph form. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/b25d99d5-46ef-4784-b652-a4895eb2c1ef)

**Comment by amenity** [comment]
@Charlie-Henry touched base with Paloma on this; they're finding everything lines up with their process as expected for the time being, but still reviewing as time allows.

**Comment by rebekkabry** [comment]
Tracy has a few meetings with ROW scheduled to review. 

•	10/31 - Meet with DTS Data Science team to map available data and document the metrics we think we can compile as well as those we can't due to missing data points.
•	11/6- Sync with ROW to discuss our findings and next steps

**Comment by rebekkabry** [comment]
Meeting with Paloma. 
- Introduced demo for exec Dash board. 
- [Meeting notes included. ](https://cityofaustin-my.sharepoint.com/personal/rebekka_bryant_austintexas_gov/_layouts/OneNote.aspx?id=%2Fpersonal%2Frebekka_bryant_austintexas_gov%2FDocuments%2FRebekka%20%40%20City%20of%20Austin&wd=target%28Right%20of%20Way%2FRight-of-Way%20Paloma%27s%20Request%202023.one%7C097F5AEF-2A7A-4051-8510-8E4A0E9D7B1E%2F1.4.24%20ROW%20Dashboard%7CD8773BEE-98FC-4CF0-B561-581F22FA2B27%2F%29
onenote:https://cityofaustin-my.sharepoint.com/personal/rebekka_bryant_austintexas_gov/Documents/Rebekka%20@%20City%20of%20Austin/Right%20of%20Way/Right-of-Way%20Paloma's%20Request%202023.one#1.4.24%20ROW%20Dashboard&section-id={097F5AEF-2A7A-4051-8510-8E4A0E9D7B1E}&page-id={D8773BEE-98FC-4CF0-B561-581F22FA2B27}&end)
- Follow up with Paloma pending Charlie's update
