### ISSUE TITLE
Banners Payment Follow up 6/8/23

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12525]
### Description
Diana and I met with Nick M to discuss the updates from the payments bug which was resolved in #12422.

### Action Items
- Check payment statuses and update any missing statuses
- Verify payments with the Convention Center and Visit Austin
- Update the automated email templates to remove timeline references
- Nick to confirm access to the CityBase system and use invoice numbers to navigate the transaction tab
- Backdate missing transaction statuses and ensure data accuracy
- Consult with Tracy for assistance with Amanda-related tasks

**Comment by dianamartin** [comment]
# 6/8
## On the fly enhancement request

Nick asked if we could remove the delivery dates on the submission messages when a user submits their application

## Old language

You have successfully submitted your application!
- You will receive an email confirmation of your submitted application.
- Please allow 5 business days for Austin Transportation Department (ATD) staff to review your application.
- The review may include requesting additional information (ex. design attachment, alternate dates or banner locations)
- Once your application has been Approved, you will receive an email within 5 business days along with payment instructions.
- You will need to navigate to the CityBase payment portal from your Street Banner account page to make a payment

## New language
You have successfully submitted your application!
- You will receive an email confirmation of your submitted application.
- Transportation and Public Works Department (TPW) staff will review your application.
>removed ` Please allow 5 business days`
- The review may include requesting additional information (ex. design attachment, alternate dates or banner locations)
- Once your application has been Approved, you will receive an email days along with payment instructions.
>removed `within 5 business days`
- You will need to navigate to the CityBase payment portal from your Street Banner account page to make a payment

Changes made on these forms:
-
