### ISSUE TITLE
[Enhancement] Ability to edit a component type

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#12534]
Users need the ability to change a project component's type, e.g. from "Bike Lane - Protected One-Way" to "Bike Lane - Protected Two-Way". 

It should be possible for a user to edit a component's type, so long as the two types have the same geometry type (line representation or no).

Because of the complexity around the signal component autocomplete, users should not be able to switch component type of signal components. We will revisit this as part of #12998 and #10719.

**Comment by johnclary** [comment]
@mddilley would you mind offering an estimate for this one?

**Comment by mddilley** [comment]
This one looks like we could remove the field disable when `isEditingExistingComponent` = true and then use that same boolean to determine what filter to apply to options to present in the dropdown (line representation or not)

**Comment by johnclary** [comment]
I updated the issue description to exclude signal components based on Discussion with Mike.
