### ISSUE TITLE
Write script to remove SIF parent connections to PRs (one time) (LP)  (On Prod)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12533]
TDS has connected SIF cases and it needs to be removed ASAP as it's causing issues with BP & trade permits. 

- Folder is PR
- PR folder has a parent ID
- The parent ID folder is SIF
- THEN delete parent ID from PR folder

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Prepared the script and requested CTM dba to run in prod database 
SCTASK0324963

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader The script has been run on Prod. The SIF parent connections has been removed from PR .

**Comment by TracyLinder** [comment]
ROW is aware this is fixed. I need to inform DSD. Closing.
