### ISSUE TITLE
Basic refinements to officer account creation

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1253]
- [x] Remove "Unit Number"
- [x] Change "Phone" to "Phone Number" and make required
- [x] Add required field for "Badge Number"; should begin with `AP` followed by 4-5 numbers 
- [x] Make "Call Sign" required

**Comment by amenity** [comment]
@SurbhiBakshi - estimate please. 👕🙏

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/7a2caea0-c635-49a0-9344-8e5191cc6c79)
