### ISSUE TITLE
Project: DTS GIS QC Support for SMD

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#12543]
This project is an effort to coordinate skills sharing and QC support between DTS GIS staff and the Signs and Markings Division.

## Background

This project has been established to track work completed by DTS GIS Staff to support the Signs and Markings GIS data QC effort.

## Scope & Deliverables

- Provide SMD staff with training and support for GIS QC related work
- Utilize DTS GIS resources to help reduce the current backlog of QC related work
- Establish channels of knowledge sharing between Markings and GIS staff
- Established a process to coordinate future work between DTS and SMD to prevent a future backlog of QC work

## Desired Outcomes

The goal of this project is to utilize DTS GIS resources to help train and support SMD staff and to reduce the current backlog of work in the GIS QC queue. The goal is to reduce the GIS QC backlog and maintain a queue of 10 work orders or less at a given time.

## Timebox

The initial scope of this support was established for a 4-week period and will likely be ongoing is some capacity to prevent any build up of backlog work.

![image](https://github.com/cityofaustin/atd-data-tech/assets/80716478/b0bb2452-d9ee-440f-a6dc-64199ad9518d)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by ChristinaTremel** [comment]
## Status Update - 9/29
- DTS was able to successfully reduce the SMD GIS QC backlog to below 10 in June 2023. 
- We continue to provide GIS QC support to ensure a minimal backlog by managing the following GIS QC categories:
   - In House Work Orders from ATSD
   - In House Work Orders from TED
   - In House Work Orders from AMD
   -  Contractor Work Orders for DIJ
