### ISSUE TITLE
Escape double-quotes and ensure properly formed CSV exports in VZE

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12541]
While testing @roseeichelmann's recent [VZ PR #1239](https://github.com/cityofaustin/atd-vz-data/pull/1239#discussion_r1224643534), I downloaded a CSV export from the Fatalities listing page. 

The `rec_text` column is a has double quotes which come through in the data unescaped and cause Excel and VSCode's CSV parsers to split the data into multiple columns. I would include a screenshot or example data, however, due to the nature of the data in this report, I'd prefer to keep it off GitHub.

To replicate this, please export a CSV from the fatalities page that contains crash ID 18988572. I would also be happy to `wormhole` you a copy of a CSV which I pulled this morning.

I believe the fix here is to either determine which columns have potential to include double-quotes and escape them or to see if a more content-aware CSV export library is available.

I suspect both the crash listing and the fatality listing pages exhibit this problem, however, it's flown under the radar on the crash listing page because it contains columns where we have not accepted user input or the use of quotations has not occurred. If this is true, it'd be nice to fix this problem in both places.

**Comment by johnclary** [comment]
FWIW i've used [paparse](https://www.papaparse.com/) in the past and it has been fine/good.

**Comment by patrickm02L** [comment]
In Planning 6/28/23, discussed doing discovery on this Issue at a (2)

Ideas about how to approach a solution:
- Maybe able to see if we could plug in a CSV library
- May be related to GridTable
