### ISSUE TITLE
Implement Workflow for Working Stock Replenishment

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1254]
Periodically, Billy will need to submit an inventory request to replace working stock.

Possible workflow:
- technician adds "working stock" items to work order
- an inventory request is created in the finance system, and the items immediately have a status of "issued"
- there is no AIMs entry for these requests
- periodically, billy comes to get new working stock from warehouse staff, and warehouse staff submit an inventory "Move" form to move inventory items to working stock.

????

**Comment by amenity** [comment]
@dianamartin has worked with Billy on this & will document how it works.

**Comment by dianamartin** [comment]
## Documentation
John and I talked to Billy about moving the inventory requests to be related to only 1 task order. Billy said that if that was the case, he could just add the working stock that he had given out to technicians on the work order. He would be able to recoup the working stock inventory by showing that he "used" it in the "working stock" transaction type.

**Comment by johnclary** [comment]
@dianamartin What about technicians who take working stock while on callback? I think we may need to send these working stock transactions from work  orders to a special working stock queue, from which warehouse staff can issue the replacement materials in bulk. not sure. but it seems like we need to discuss further.
