### ISSUE TITLE
Cleanup Airflow stack's Docker compose file

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#12557]
See https://github.com/cityofaustin/atd-airflow/blob/airflow-v2/docker-compose.yaml

- [x] Remove unused settings
- [ ] Document where the original file came from

From backlog refinement on 6/07/2023: Could diff the original file against the current file to help with this

**Comment by mddilley** [comment]
@johnclary @frankhereford I added the idea about using a diff that Frank mentioned in the refinement meeting, but I can't remember if there was anything else to add here. Do y'all?

**Comment by frankhereford** [comment]
Mike - thank you - I think you captured the ideas here really well. 

I was curious about the size of this task, and I looked at the [docker-compose.yaml](https://github.com/cityofaustin/atd-airflow/blob/airflow-v2/docker-compose.yaml) we have now, and I don't see a lot of unused code in there that can be removed. I'm really curious what y'all think. Less is more for sure.

The original file that this is based on can be found here: https://github.com/apache/airflow/blob/2.5.3/docs/apache-airflow/howto/docker-compose/docker-compose.yaml. When we started, the current version was 2.5.3, and now they are up to 2.6.1, and the compose file has not changed at all, so I'm hopeful it's pretty stable.

Here's a diff I took this morning to show the modifications that have been made to make the stack our own. You can find it [here in a gist](https://gist.github.com/frankhereford/377441d13c96a298973c1c243305b5da). I think it's not too bad at < 100 lines.

**Comment by mddilley** [comment]
@frankhereford Thanks for linking the diff, that also does feel like a lot to me. Going to throw a 1 on here and assign to you since you did the comparison on this. I'm thinking that we throw a link to the original docker compose in the readme along with a note to diff them to see the additional config?

Curious to see if I'm leaving anything out that @johnclary was thinking about.

**Comment by frankhereford** [comment]
Assigning John since he's picked this up via discussion in slack - thank you @johnclary!
