### ISSUE TITLE
Meeting: Finance Service Request Feedback Sync

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12565]
### Objective 
Review Feedback from Finance Testing SRs

### Participants
Christina, Diana, Tim, Jenny, Sharon

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# TO DOs LEFT OVER
#### Where is the Job ID within the Subproject information for the requestor after creating a new subproject # while requesting a new FDU? We created a new Subproject but there was no job ID to choose even if submitted the new subproject request (maybe not set up yet?!?)
- DONE: Missing “Job ID” field on Subproject table of Add SR Job page. Added to all tables
- [ ]  NEED TO TEST filters on “New Subproject No.” (to only be associated with the one the user created with SR)

#### BUG
  - [ ] NEED TO TEST: SR Statuses and tables, “Waiting for Approval” – Details page, tables are “editable”, should be “non-editable”
Page filter
