### ISSUE TITLE
Give Officers the ability to specify their preferred sectors

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1256]
Currently, many officers are reticent to sign up early because that means they'll be assigned to shifts in North Austin. It would be great if officers could specify their preferred locations.

**Comment by amenity** [comment]
@SurbhiBakshi - estimate please 🙏👕

**Comment by amenity** [comment]
Also, the way you implemented looks great on the officer end. ✨

Going to make a new issue for the way the Assigner sees/looks this up as there are various approaches I can think of.

**Comment by amenity** [comment]
@SurbhiBakshi would you please add help text for preferred sector question above the checkboxes:
"What sectors are would you prefer to work in for VZA Enforcement?"

**Comment by SurbhiBakshi** [comment]
I have changed the text, however I don't see any options to put the text above the check boxes. I would prefer that myself. ![image](https://user-images.githubusercontent.com/13035849/73092098-8463a100-3ea1-11ea-8fe5-d690b918c98f.png)
![image](https://user-images.githubusercontent.com/13035849/73092146-a3fac980-3ea1-11ea-925b-3365c2b9c5ae.png)

**Comment by amenity** [comment]
Ah — I remember: Knack by default puts help text after fields. 🙄

We should make Sectors required. 

Also will they be able to log in and edit this information?

**Comment by SurbhiBakshi** [comment]
@amenity, place to put an edit form - their My Assignments page? don't think the Account Administration page would be a good location to direct officers to, unless there is a way to limit account table to only logged in user.

**Comment by amenity** [comment]
@dianamartin How do y'all typically set up a "My account" page where a user can see/edit only their account information? Could we just add the fields to the _Account Settings_ page?
![Screen Shot 2020-01-29 at 6 38 05 PM](https://user-images.githubusercontent.com/1463708/73409996-8628cc80-42c6-11ea-8731-b33ab3028dff.png)

**Comment by dianamartin** [comment]
@amenity that is the page where a user changes their profile information. It looks like the fields already exist there.

**Comment by amenity** [comment]
@dianamartin that's not in production; I changed it in my test app b/c @SurbhiBakshi was concerned about how to limit access and it seemed like this would work.

**Comment by SurbhiBakshi** [comment]
@amenity so do you want to include a link on he Page Menu when the officers sign in? Right now they would be redirected to My Assignments.

**Comment by amenity** [comment]
@SurbhiBakshi - I don't think we need to do that. The Knack default (_Account Settings_ link in the upper right) is a standard UI pattern. If officers have trouble finding it we can troubleshoot it then. :)

**Comment by SurbhiBakshi** [comment]
@amenity , my concern is that you are signed in as Scheduler and can see all the officer related form fields  like Sectors, and Badge Number when you look at Account Settings. Wondering if a dedicated place that only the officers can reach would be easier to manage, and not confuse other users. I am also trying to see if there is a way to hide fields using Display Rules or Page Rule to hide the form on Account Settings.

**Comment by amenity** [comment]
@SurbhiBakshi - Yeah, I considered that. 😕I don't think it's the end of the world if Lewis & Randy see some fields that don't apply to them — worth it to be able to rely on defaults for basic account management. 

@johnclary @dianamartin - double checking:
- Can we have role-specific account fields (e.g. only Officers have _Preferred Sectors_
- Is there a way to hide/expose account settings fields based on role, either a Knack configuration or an role-specific HTML attribute we could wield for a [CSS workaround](https://support.knack.com/hc/en-us/community/posts/220702668/comments/223460148)?

**Comment by SurbhiBakshi** [comment]
@amenity - so tried this out in the test instance - 


1. Menu on My Assignments page for Officers with link to account information - 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/50c633ce-f6ac-41ad-8b16-a1881df7ea70)

2. Account Information

**Comment by dianamartin** [comment]
@SurbhiBakshi will the "Account Settings" not do the same thing or there is more information they are can edit on that page? 

![image](https://user-images.githubusercontent.com/21112975/73560531-c69a5e80-441c-11ea-9f4a-a676f26c0152.png)

**Comment by SurbhiBakshi** [comment]
Wanted to restrict access to only Officers for fields like Badge Number and Sectors, trying out the Display Rules for an edit form right now.

**Comment by SurbhiBakshi** [comment]
@amenity @dianamartin @johnclary 

Approach 2
Used some display rules and page rules to get to this point, took away the default password reset form. 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/b860732b-b9f2-430d-bcca-11574f807dd0)

**Comment by dianamartin** [comment]
@SurbhiBakshi my only comment would be to change the "Submit button" at the top to say "Update Name/Email" perhaps so that "Submit" isn't duplicated on the page.

**Comment by amenity** [comment]
Agree with Diana if we really need to do it in such a convoluted way, but it would be far better just to have one button on that page. 

As I said earlier, I don't think it's the end of the world if Lewis & Randy see some fields that don't apply to them.

I would really prefer not to make this more complex than it needs to be. [This configuration](https://builder.knack.com/atd/vision-zero-in-action--amenity-test#pages/scene_2/views/view_1) I shared last week took two minutes and relies on default access, settings, and views.  
![Screen Shot 2020-02-03 at 9 51 56 AM](https://user-images.githubusercontent.com/1463708/73668445-7a912900-466b-11ea-927c-e7eb004d8e9c.png)

Why can't we go with that?

**Comment by amenity** [comment]
Also agree with Diana that the "Account Settings" button is sufficient.  Having "My Account" on one side of the page as a button and "Account Settings" on the other side of the page as a link is confusing.

**Comment by SurbhiBakshi** [comment]
@amenity, @dianamartin I tried two different approaches, and was able to use Page Rules to hide what Randy and Lewis don't need to see. I think you may have gotten a little confused with the two approaches. I am ok with going ahead with Account Settings (and taking away the My Account button) but think the Page Rules should be retained.

**Comment by amenity** [comment]
@SurbhiBakshi - sounds good: 
- Use the out-of-the-box Account Settings for everyone, no additional menu items
- Change button text from "Submit" to "Update" on Account Settings page

--

As far as long as the Account Settings page for Scheduler, Assigner, or Viewer
- Hide fields that apply only to officers
- Remove access to page & hide link (since we're using ADFS credentials, there is nothing anyone in these roles can actually accomplish on their Account Settings page, right?)

**Comment by SurbhiBakshi** [comment]
@amenity , agree we don't need the Password or Email update options since users will be using ADFS. 

Only officers will be able to see Account Settings, and then only the Edit Account with options to edit Phone Number, Badge Number, Call Sign, and preferred APD Sectors. 

Please ignore the tabs at the top, that should be resolved soon.

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/411ddcf1-5a11-4eef-a0e7-631187ce55e6)

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/b808d90d-89e8-4dbf-99ab-1107d93e9eb8)

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/8bfb03b9-53ed-4a60-a718-be99a210cdec)

**Comment by amenity** [comment]
Looks beautiful, @SurbhiBakshi! 🌺
