### ISSUE TITLE
[SharePoint] Request More Storage Space for APWA Site (PW Legacy)

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#12571]
## T 6/13/23 
- request via @dianamartin  from Stephanie F. during a meeting: "We're having issue with our APWA SharePoint site space, it's saying we need to delete files, are you able to help us? Can we get more space for this site?"
- checked with Stephanie to get [the specific site address](https://cityofaustin.sharepoint.com/sites/PW/PWOPM/APWA/2023%20APWA%20Accreditation/Forms/AllItems.aspx)
- put in request with CTM/ Danny C. for more space to complete the APWA process (Incident INC0300562)

**Comment by dianamartin** [comment]
# 6/14
>The request has been submitted, it is out of our control. The CTM team will be the ones to provide space. We just have to be patient and we can continue to reach out to them. 

# 6/22
- Followed up on `INC0300562`
-

**Comment by dianamartin** [comment]
Adriana M. on 6/22
>Thank you all!
