### ISSUE TITLE
Give a Moped overview and demo to CIF fellows and new TPW teammates

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#12574]
Let's show Moped off to some of our new collaborators and provide a refresher for folks on our team: 

**DTS**
- Rebekka, Amenity (required)
- Kate, Charlie (optional)
- Dipa, Matt, Rene, Adriana (optional)
- Diana, Tracy, Nate, Patrick, Christina, Peggy, Amenity (optional)

**CIF Fellows**
- Madison (required)
- Rachel (required)

**Previously-Public-Works staff**
- Dave A., Grace B., Street & Bridge (required) 
- Michael S., Paige W., Office of Performance Management (required)

**Comment by amenity** [comment]
@maccallump @paigewarner - anyone else who should be in these meetings?

**Comment by johnclary** [comment]
Scheduled for Weds, 6/28.
