### ISSUE TITLE
Review and document existing Knack --> Socrata --> Github service bot system

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#12580]
**Code:**
1. Update divisions - [config](https://github.com/cityofaustin/atd-service-bot/blob/78f047bb5695e0ca09936ab6e34e759255e737f7/config/config.py#L93-L120)
4. Update and rename applications - [config](https://github.com/cityofaustin/atd-service-bot/blob/78f047bb5695e0ca09936ab6e34e759255e737f7/config/config.py#L172-L193)
5. ~Update urgent email recipients - [config](https://github.com/cityofaustin/atd-service-bot/blob/78f047bb5695e0ca09936ab6e34e759255e737f7/config/config.py#L221-L234)~ The email recipients are configured in the Knack app

**Docs should cover:**
- diagrams of the three scripts and the tech they use
   - Intake (Knack service request records created through SR form -> Github issues)
   - Issues to Socrata (GitHub & Zenhub -> Socrata)
   - Create or update Index issues (GitHub -> Knack)
- coordinating updates

**Updates from June 5 meeting:**
- ~make config linked earlier compatible with new and old labels to avoid downtime?~ Going to have an outage and launch party

**Comment by mddilley** [comment]
I added the rough outline of the process and scripts in [Gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/service-bot-process). Will pick back up on this Monday to create the diagrams, clean these steps up, and come up with a plan for coordinating the updates.

**Comment by mddilley** [comment]
The documentation is [here in Gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/service-bot-process). Going to close this one out since the code updates are covered in https://github.com/cityofaustin/atd-data-tech/issues/12752.
