### ISSUE TITLE
Assign Traffic Engineers to Regs Submitted for Review based on their area and Assign Eric as the City Traffic Engineer

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12584]
### Request
- For the Traffic Register, users have asked that we auto assign Regulations that are submitted for review to Traffic Area Engineers.
- Auto assign Eric as the City Traffic Engineer.
- Provide option for Eric to assign new Area Engineers as needed and a way for Area Engineers to cover for Eric as the City Traffic Engineer as needed.

### The Area Engineers are:
- **North**: Dipti 
- **Central**: Lee 
- **South**: Justin

**Comment by ChrispinP** [comment]
When a Draft is set to an Area, a connection is made to the new Review Area object that has an App Admin page to Manage Review Areas.
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/a39bf22a-4ec6-4ef4-826a-800fbc53667d)
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/5e2c7329-9f7b-4c22-9417-5e589a4c9303)

Each Review Area has the option to be set to a specific area email if wanted. Emails can either be sent to the assigned Traffic Engineer account, the Review Area Email, or both.
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/9418bf69-42c8-4ad1-a94d-3b2970540b70)

When a Draft is now Saved, the Traffic Engineer and City Traffic Engineer are assigned. Additionally the connection to the Review Area is set.
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/dfb63b2c-3006-440c-a0ad-46084e8fd5ae)

Draft Authors & Traffic Engineers still have the ability to re-assign during the Draft Submittal or Draft Review process. Currently Eric is the only City Traffic Engineer. If we want to allow for replacement we would need to open up the filter to allow both Traffic Engineers & City Traffic Engineers to be selected as the City Traffic Engineer for the Reg Doc.

Complete, Ready to Review

**Comment by ChrispinP** [comment]
Since we now auto-assign the Traffic Engineers by area I have updated the rules so that the Currently Assigned To is also autopopulated.

**Comment by ChrispinP** [comment]
Updated Central Area with Lee, complete closing
