### ISSUE TITLE
Housekeeping and strategy for new wiki(s)

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1258]
We've got a Gitbook organization for the team and I [sloppily imported our wiki there](https://atd-data-and-technology-services.gitbook.io/austin-transportation-data-and-technology-services/). Now what?

Questions: 
- Can we store pages not in [the root of the repo](https://github.com/cityofaustin/atd-data-tech)? So messy 😱
- Where do we want our wikis? E.g. does have `atd-knack` Knack builder docs and user guides? `atd-amanda`?

To do:
- [x] Make sure everyone on the team can edit and add any instructions about this to onboarding checklist
- [ ] Delete Github wiki and direct to Gitbook
- [ ] ...
   

What else?

**Comment by dianamartin** [comment]
@amenity I found this for you: https://docs.gitbook.com/integrations/github/content-configuration to help cut down on the clutter

**Comment by dianamartin** [comment]
I figured a way to create a folder at the root so that GitBook will create .md files in there and create sub folders for grouped wiki pages. 

[

- GitBook Viewer](https://atd-data-and-technology-services.gitbook.io/austin-transportation-knack-guides/)
- [atd-knack-repo folders](https://github.com/cityofaustin/atd-knack/tree/master/gitbook) - shows the group pages
- [Pages per grouped folder](https://github.com/cityofaustin/atd-knack/tree/master/gitbook/data-tracker)

**Comment by amenity** [comment]
Made sure that @dianamartin is an admin. @mateoclarke is as well. @johnclary - sent you the link via Slack DM. Added a link to sign up as a writer to the Github internal Team discussion with other sensitive info.

**Comment by dianamartin** [comment]
I can try to work on migrating anything else over (this friday) that I haven't yet into the new wiki

**Comment by amenity** [comment]
I think it makes sense to have [separate "spaces" for different topics](https://app.gitbook.com/@atd-data-and-technology-services/spaces), rather than a giant wiki. Gonna start by breaking Project Management into its own space.  
cc/ @mateoclarke @johnclary @dianamartin

**Comment by amenity** [comment]
Or maybe not. Just as I say that I question myself.... but it's easy enough to go back and forth. ;)

**Comment by dianamartin** [comment]
Just make a group in the GitBook, that can help keep it together

**Comment by amenity** [comment]
I think you're right, @dianamartin. Oh well, here's what it would look like on its own: https://app.gitbook.com/@atd-data-and-technology-services/s/product-ops/

**Comment by amenity** [comment]
@dianamartin - can we delete [all of these](https://app.gitbook.com/@atd-data-and-technology-services/s/austin-transportation-data-and-technology-services/knack) since there is a separate Knack Guides space now?

**Comment by amenity** [comment]
Okay, I double-checked to make sure all the content that was in the data-tech wiki is in Gitbook and nothing had been edited in the interim. SO: Deleted all those pages and did a tad of tidying. 

@dianamartin I think the Knack pages now exist in three places:
- ATD DTS Github wiki, e.g. [Knack Style Guide](https://github.com/cityofaustin/atd-data-tech/wiki/Knack:-Style-Guide) 
- _Austin Transportation Data & Technology Services_ Gitbook, e.g. [Knack Style Guide](https://app.gitbook.com/@atd-dts/s/wiki/knack/knack-style-guide)
- _Austin Transportation | Knack Guides_ Gitbook, e.g. [Knack Style Guide](https://app.gitbook.com/@atd-dts/s/austin-transportation-knack-guides/knack/style-guide)

Delete those that you don't want and then we can call this issue closed. 😎

**Comment by amenity** [comment]
Deleted:
- ATD DTS Github wiki, e.g. [Knack Style Guide](https://github.com/cityofaustin/atd-data-tech/wiki/Knack:-Style-Guide) 

Duplicates:
- _Austin Transportation Data & Technology Services_ Gitbook, e.g. [Knack Style Guide](https://app.gitbook.com/@atd-dts/s/wiki/knack/knack-style-guide)
- _Austin Transportation | Knack Guides_ Gitbook, e.g. [Knack Style Guide](https://app.gitbook.com/@atd-dts/s/austin-transportation-knack-guides/knack/style-guide)

@dianamartin @johnclary - I think y'all were recently discussing which of these we should keep. Can you delete the other? Do we have any other wikis in Github we should move to Gitbook?

**Comment by dianamartin** [comment]
@amenity I'll delete the one in the `Austin Transportation Data & Technology Services Gitbook`

**Comment by dianamartin** [comment]
All the knack wiki pages were deleted from the `Austin Transportation Data & Technology Services Gitbook` as they exist in the `Knack Guides GitBook`

**Comment by amenity** [comment]
I think this is going to be covered by issues you create for Level I Support Knowledge Base work, @dianamartin. Please close if so!
