### ISSUE TITLE
[SharePoint] Request More Storage Space for SBO Site (PW Legacy)

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#12581]
## W 6/14/23 

- Grace B. from Street & Bridge Operations wrote in having gotten a low storage warning on the SBO SharePoint. 
- I submitted a SN ticket for Danny C. to upgrade storage. INC0300704
- Adding Diana to the issue in case this take a few days. 
---
Your Incident `INC0300704` has been opened.
 
Submitted By: Karo Engstrom
Impacted User: Karo Engstrom
Priority: 3 - Medium (4 Days)
Due Date: 06-20-2023 17:00:00 CDT
 
Request for Upgraded Storage for SharePoint - Please Direct to Danny C.
Description: Hi Danny, Street and Bridge Ops is running out of space as well (see attached also):
https://cityofaustin.sharepoint.com/sites/PW/SBODivision/Pages/default.aspx
 
I appreciate your help on these legacy PW sites. Thank you.

**Comment by dianamartin** [comment]
I may reach out to SBO and talk to them about a TPWSBO initiative, but i'll wait to do that

**Comment by dianamartin** [comment]
# 6/22
- Checked on the `INC0300704` status
- Notes state Danny C. on 6/15
>Increased site storage from 2TB to 3TB

**Comment by dianamartin** [comment]
users replied
>DA: Thanks, Diana!  Great news!
>GB: that's great!! 
Thanks for letting us know 

I said
>So it sounds like we all just found out the good news  I'll close the issue we had open for this
