### ISSUE TITLE
[BUG] Jenniffer is unable to see the buttons on Markings Work Orders and can't add attachments

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12595]
### Describe the bug
Got on a Teams call with Jenniffer and noticed that she's having issues with viewing Markings Work Orders. I checked work orders to see what my view was looking like and noticed that I'm also having some weird issues.

### Jenniffer's view:
- Can see Attachment, Comment, and Jobs table, but don't see any buttons
- ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/71d5123e-367b-417b-98b5-e06eb3e9ca53)

### Christina's view:
- Can see buttons and Attachments table, but can't see the Jobs or Comments table
- ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/1539c963-57fa-4712-9b2c-b78e9f67d457)

Susanne and I did add the GIS QA user role to both Jenniffer and my accounts, so I'm wondering if this is why we aren't seeing work orders normally.

**Comment by dianamartin** [comment]
# 6/15
Checked user roles for both Jenniffer and Christina
**jenniffer**

- Supervisor
- GIS QA
- Training User

**christina**

- Supervisor
- GIS QA
- Training User
- System Administrator

- [x] changed user roles for Test-Technician to figure out the page rule issue
