### ISSUE TITLE
IT Support: Give Access to Cable Management page to Andrew C

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12593]
Billy B. 
AMD

Spoke with Christina on 6/14.
Christina said
>Billy is requesting that we give Andrew C  access to the AMD Cable Management page.

**Comment by dianamartin** [comment]
# 6/15
Checked the page's - page rules
- `Tech Supervisor`, `Inventory Editor`

Andrew C.'s - user roles
- Asset Editor
- Technician | AMD
- Viewer
- Tech Supervisor | AMD
- Contractor Transfers User

Messaged Billy 6/15
>Hey, the Cable Mgmt page has two user roles: Tech Supervisor, Inventory Editor which one do you want him to have?
>- He seems to already have the "Tech Supervisor | AMD" in his profile, so he should be able to access it. Is it that special table you and Blake can edit?

**Comment by dianamartin** [comment]
# 6/15
Messaged with Billy, he is requesting Andrew take the place of Blake. 
>But he (Blake) is no longer watching this. I’ve moved that responsibility over to Andrew.
- Overriding this [issue](https://github.com/cityofaustin/atd-data-tech/issues/12231)
- [ ] Change Blake's email to Andrew C.'s
