### ISSUE TITLE
Enhancement: Add Agency Column to Real-Time Traffic Incident Reports Dataset 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#12590]
Backstory #10688  
- CTM retired their RSS feed/widget that we used to pull the data for this dataset. 
- The widget used to show the responding agency: 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/2077b0bd-41c0-4505-b129-42df58f4c0db)

- citizen user has requested that column be added to the dataset 
- @chiaberry 's note: "we can get agency type from the database, there needs to be a few extra steps to get it into the dataset
@johnclary am I right that we need to update the postgrest metadata to save that information, then add the column to socrata and the payload in the ETL?"

Submitting to the dev team for scoping.

**Comment by chiaberry** [comment]
the column in the oracle database is titled "AGENCY_TYPE"

**Comment by chiaberry** [comment]
done!
