### ISSUE TITLE
Inactivate Tracy H. TDS account on Fri, 8/11/23

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12592]
# 6/12
- Checked the system, Colleen G. is not in the sytem
- [x] Reviewed Tracy's credentials
  - `TDS Reviewer`
  - `TDR Reviewer`
  - Urban Trails (PWD)
  - Public Works
- [x] Created account for Colleen G.
- [x] Emailed Coleen
>Hi Coleen, 
I’ve given you access to the TDS Portal with the same credentials as Tracy. Just let us know when we should deactivate Tracy’s account. I have it ear marked it for 6/19.
- [x] Inactivate Tracy's account on ~Mon, 6/19 (her last day is Fri 6/16)~ **Fri, August 11th**
>update: Thank you so much! It looks like Tracy's end date is getting pushed out to August to account for her 5.5 week vacation, so can you please change her deactivate date to August 11? That will be her last day in PWD.

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/12558#issuecomment-1588421580_

**Comment by TracyLinder** [comment]
Hi @dianamartin is this one ok to close?

**Comment by dianamartin** [comment]
@TracyLinder we need to assign someone on Apps to reach out to Coleen to confirm Tracy H's departure an remove her from the TDS Portal.

**Comment by ChrispinP** [comment]
I have inactivated the user account, complete
