### ISSUE TITLE
Prevent submission of signal work order until QC Detectors has been completed

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1259]
Brian VDW
AMD

Came by and asked if there was a way to prevent the signal technicians from submitting a WO until they've checked the detectors at that signal.

**Comment by dianamartin** [comment]
I looked at the possibilities of adding an error message on the `Submit Work Order` button. I was able to add one that said to look at the signal's `DETECTION STATUS DATE`. 

Brian had suggested that if the `DETECTION STATUS DATE` was before today's date that the `Submit` form would not allow the user to submit. 

I configured a new page called `Signal Detector` that is a quick link to the Edit Detector page where the user can just add a new detection event to the detector. However, I reviewed the script `detection_status_signals` happens nightly and that would prevent the signal technician from submitting a WO the same day. They've have to wait the following day, so I'm not sure if that's what Brian/Billy would want.

**Comment by dianamartin** [comment]
Need to have Brian review and see if this would work for them. I think it's too restrictive right now and perhaps we should just remove the error message on the submit button. Now that the other link is there and it's easier to get to that page, perhaps the technicians will do the QC now.

**Comment by amenity** [comment]
@dianamartin any updates on this?

**Comment by dianamartin** [comment]
Moved these elements to the `17 JAN 2020 | TEST - Austin Transportation Data Tracker` bc John wanted to delete the `9 DEC 2019 | TEST - Austin Transportation Data Tracker` environment. 

I didn't show Brian VDW, but we discussed it and it may not work for them because the technicians don't close their work orders the same day they might check a detector so the page rule won't work.

**Comment by dianamartin** [comment]
Reached out to Brian VDW, 
>just following up on some older AMD requests. Are you still having issues with technicians not checking/updating the detectors when they're at a signal before closing out a work order? I'm trying to gauge if this is still needed. 

Brian VDW
>I haven't been tracking this very closely. Let me do a little digging. Need to compare work orders to the Detection page to see if the dates match up.

This may still be needed depending on how the Detector Reports that Brian will be reviewing match up.

**Comment by ChristinaTremel** [comment]
For Billy's team it would be problematic if we made this a need for every work order at this time.

**Comment by ChristinaTremel** [comment]
This hasn't been brought up as a need since 2020 and when I checked in with Billy, he said this would be problematic for Technicians. Closing this as not planned and will address if a new request for this comes through.
