### ISSUE TITLE
CC generating user on ROW Deficiency Emails (SR) (Deploying to PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12605]
### See #12104 - we need to copy the user who generates the email on both reports. 
![CC Line](https://github.com/cityofaustin/atd-data-tech/assets/130776506/84cb0a87-f57b-4e69-a37e-33c6b4853858)

### Change the email subject line for 50563, 50568 reports (deficiency reports)
- Change 'ROW Permit' to 'Investigation Report'
![Subject Line](https://github.com/cityofaustin/atd-data-tech/assets/130776506/a379ae1d-743a-425b-8473-766b1d8a5cf7)

**Comment by TracyLinder** [comment]
@vschandramouli can you update the AC please? It's ugly - I'm sorry.

**Comment by KyleErich** [comment]
Added screenshots from emails reports 50563 and 50568 showing each line that requires updating as part of this card.

**Comment by TracyLinder** [comment]
### Status Requested by ROW

@Nadin-Nader @Sreelatha-BlazeKannan please add an update comment and tag @KyleErich

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Development is in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Manual DEV DP Submitted. Please approve and create task id for the same.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the AMANDA Support group to be deployed to DEV under **SCTASK0338350**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV, please UAT

**Comment by TracyLinder** [comment]
### Friday ROW Review Clarifications 

**For the subject line:** Create a new email template.
**For the CC:** Good to go

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - #12605 TEST commit submitted. Kindly approve and create task id for the same.

**Comment by Nadin-Nader** [comment]
This has been sent to the CTM Team to be deployed to TEST under  **SCTASK0343521**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Its in TEST; Tested with new template verified subject/CC/BCC and all looks good. Ready for UAT

**Comment by TracyLinder** [comment]
### UAT PASSED - PROMOTE TO PROD 🎉

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - PROD Manual Commit submitted. Kindly approve and create task id for the same. 

Note: It is a manual commit.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0344384**

**Comment by Nadin-Nader** [comment]
Still waiting on CTM

**Comment by Nadin-Nader** [comment]
Anu is still working on this

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Promoted in PROD, Verified the same. All looking good and ready for PROD UAT.

**Comment by TracyLinder** [comment]
### PROD UAT PASSED - CLOSING
