### ISSUE TITLE
Add Madison F. to DTS "About Us" Webpage

### ISSUE THREAD

**Issue by madifan** [cityofaustin/atd-data-tech#12604]
[Headshot link](https://drive.google.com/file/d/1eXVaNemUWtMRbIFvJE47xkeHrqWdcsTR/view?usp=drive_link)
[Preferred pronouns link](https://docs.google.com/document/d/1gRjTic8FD3s-t0sVZhErAidMIAktU-0Vn2GYPpPcUeg/edit?usp=sharing)

**Comment by madifan** [comment]
@chiaberry Hi Chia I filled out my "About us" info for the website!

**Comment by chiaberry** [comment]
@madifan thank you!
