### ISSUE TITLE
Modify triggers installed directly into the PG database

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12615]
## Description

This issue focuses on modifying triggers that are installed directly into the PG (PostgreSQL) database. The existing triggers, which are currently operating on a single table, need to be translated into a dual table representation in the Layer Data Model (LDM). The LDM represents data across multiple related tables, providing a more scalable and flexible approach.

The work involved in this issue includes identifying each trigger, understanding the events that cause it to fire, and determining the input required by the trigger. Additionally, the triggers need to be moved from the public schema to the appropriate schema within the LDM. To facilitate deployment, scripts or metadata should be created to populate the revised triggers during the deployment process.

## Deliverables

**1. Identification of triggers**
   - Identify each trigger and what events cause it to fire and what input the trigger needs

**2. Translation to LDM representation**
- Move the trigger from the `public` schema into the appropriate LDM schema

**3. Deployment scripts or metadata**
- Create scripts / metadata that can be used to populate the revised triggers during the deployment process

## Notes
- There may be some difference between the way the CRIS layer gets treated versus the way that Vision Zero schema gets treated.

**Comment by johnclary** [comment]
I'm closing this epic but leaving https://github.com/cityofaustin/atd-data-tech/issues/13706 open for now since we do need to revisit the crash notes and recommendations tables 👍
