### ISSUE TITLE
Modify triggers managed by the graphql-engine

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12617]
## Description

This issue focuses on modifying triggers that are managed by the graphql-engine and are backed by a lambda function. The graphql-engine allows the definition of custom triggers within the GraphQL schema, which are executed when specific GraphQL operations are performed.

The goal is to translate these existing triggers from their current single-table scope into the dual table representation in the Layer Data Model (LDM). This translation ensures that the triggers align with the LDM model, which represents data across multiple related tables.

## Deliverables

**1. Identification of triggers**
   - Identify each trigger and what events cause it to fire and what input the trigger needs

**2. Translation to LDM representation**
- Move the trigger from the `public` schema into the appropriate LDM schema

**3. Deployment scripts or metadata**
- Create scripts / metadata that can be used to populate the revised triggers during the deployment process

## Note
- There may be some difference between the way the CRIS layer gets treated versus the way that Vision Zero schema gets treated.

**Comment by patrickm02L** [comment]
@roseeichelmann please take a look at the epic Issues #12644, #12645, #12646 to add additional scoping based on your recent work from #10126.

**Comment by johnclary** [comment]
i think we can safely close this. the issues references throughout here will be updated accordingly if they're not already.
