### ISSUE TITLE
Give Assigner ability to see officers' preferred sectors when doing assignments

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1261]
Options I can think of, in descending order of desirability:
_If Jen and Lewis are okay assigning officers only to assignments in sectors they want, recognizing that may result in shifts unfilled assignments:_
- Limit drop down to only shows officers who have specified the sector for that assignment as one of their preferred sectors

_If ☝️is too complex OR if we want to be able to fill all shifts, even if it means assigning an officer who doesn't want to be in that sector:_
- Checkbox to limit drop down to only shows officers who have specified the sector for that assignment as one of their preferred sectors (only if this is easy to implement and doesn't impact performance much, otherwise:
- Rename "Account Administration" to "Available Officers" and turn this in to a reference page for Randy to have open in a separate window while he does assignments. Add a filter that lets him narrow down list by preferred sector

~- Concatenate [Officer Name] and the letter for each section they prefer so that's visible in the drop down, e.g. 
    -`Surbhi Bakshi — B, C, D, E`
    -`Major Applewhite — A, B`~ This sounds like a mess. 😝

**Comment by SurbhiBakshi** [comment]
@amenity - "Rename "Account Administration" to "Available Officers" and turn this in to a reference page for Randy to have open in a separate window while he does assignments. Add a filter that lets him narrow down list by preferred sector" is my preferred option, this will be the fastest to implement, and also think this will not impact the workflow when Mike implements batch officer assignments.

**Comment by SurbhiBakshi** [comment]
@amenity related to Officer's self registration, doesn't look we don't need RDavila to add accounts, so going to take away that button on the Admin page.

**Comment by SurbhiBakshi** [comment]
The button could be bigger and text bolder - 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/f2886b2b-7fcf-450a-85f4-90bc0d1ca1ae)

**Comment by SurbhiBakshi** [comment]
So the button and table name has changed to Available Officers, should the page Menu Name and Page link also change?

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/fe1e5962-9197-4d8d-a208-8fd6214176f3)

**Comment by amenity** [comment]
@SurbhiBakshi this looks great.
