### ISSUE TITLE
[BUG] The Knack-Banner script is failing to connect to the G drive

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#12622]
The Knack-Banner integration ([repo](https://github.com/cityofaustin/atd-knack-banner)) failed today ([slack thread](https://austininnovation.slack.com/archives/C02PDUGQFQX/p1687269363536099)) because it was unable to reach a network directory.

Per @dianamartin, this may be an issue affecting all G drive users. She's going to reach out to Scott.

If this is a long-term problem, we could potentially disable the part of the script that compares email addresses against the CTM email CSV on the G drive.

Update: after discovering that the CSV file on the G drive has not been updated in 1 year, we have decided to remove this logic from the script.

**Comment by chiaberry** [comment]
@ChristinaTremel just letting you know, in case anyone from HR has questions. Until the script runs successfully, any changes in Banner won't be automatically reflected in the knack app.

**Comment by dianamartin** [comment]
@Matthew-M-TPW see notes here

**Comment by johnclary** [comment]
@dianamartin @ChristinaTremel as discussed, i removed the CTM email address handler from the integration and re-ran the script successfully.

The script's [README](https://github.com/cityofaustin/atd-knack-banner#banner-and-knack) has a few more details about how this works, but the gist of it is that it's important the HR staff keep Banner current with employee names and emails, because most changes made in Knack will be overwritten by the data we have in Banner.

**Comment by dianamartin** [comment]
@johnclary I found this!!
https://github.com/cityofaustin/atd-data-tech/issues/6649#issuecomment-878501765
- we have a name, Jeffrey from CTM. Do you happen to know who you talked to..

**Comment by dianamartin** [comment]
# 6/26
I pinged John D. (CTM) to ask
>Hey John, 
I've got kind of a random question. I know you've helped TPW (ATD) with our SSO Active Directory work before, but my question is. Can someone access the Azure AD programmatically? Like if they needed to check email addresses against Banner email addresses.

>because currently we had a process where someone at CTM updated a file with the information, but it was stored on the G drive and our script can't access it anymore due to some network path issues AND whoever we had at CTM stopped updating 
the file as of 7/2022.. 

he replied
>Is it possible whoever was doing it before left and didn't pass that job on to someone else in their group? They should be able to do it still as far as I know
