### ISSUE TITLE
Perform Administration hand-off meeting

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#12626]
Create agenda for hand-off meeting between TPW & CDS Administration division.

[Working doc](https://docs.google.com/document/d/1AUPA5QZ9VblEnGg5gA1se6KQ0i1Yfge3pSrPDa5r1gg/edit?usp=sharing).

**Comment by michael-santulli** [comment]
@amenity I made a draft agenda for the Admin hand-off meeting (linked above)
