### ISSUE TITLE
VZA 2.0 Officer workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1263]
Workflow for APD officers to use VZA App.

**Comment by amenity** [comment]
@SurbhiBakshi - you've already started building this sans specs, yes?

**Comment by SurbhiBakshi** [comment]
@amenity , yes, this is almost done. Not sure if the reasons for inactivity and report area of concern can be bundled into one object as Notes. You can sign in as officer and take a look at the page. The assignment is on March 1st, 12 am to 3 am. Lewis is adding some early morning and late night assignments, have changed the calendar windows to reflect that.

**Comment by SurbhiBakshi** [comment]
- [ ] Need some CSS help to make Start and End Assignments look like links. 

- [ ] Reason for no violation observed combined with report area of concern? Perhaps add one more field to group/ categorize the notes?


![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/b5e129a3-d2f0-42b4-94ae-3988074b0856)

**Comment by amenity** [comment]
@SurbhiBakshi - okay, there are some changes I would like to make here. Please pause on this until specs are complete.

**Comment by amenity** [comment]
This is great for now. Will revisit when we think more throughly about officer workflow in VZA App 1.0.

**Comment by amenity** [comment]
Going to retire this and use the _VZA 2.0_ release instead
