### ISSUE TITLE
Replace locations_polygons with vision_zero_polygons in MAINT

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12636]
## Description
Take a cut of the Vision Zero database polygons to replace the existing locations_polygons in the MAINT system - Replace the outdated locations_polygons with the updated vision_zero_polygons. This change is necessary to ensure alignment of the Vision Zero polygons before VZ GIS staff starts to make edits in MAINT.

## Notes: 
- Ensure ensure that the new vision_zero_polygons are properly transformed and aligned with the projection at 2277
- Documentation should be updated to reflect the changes made, including any necessary instructions or guidelines for future maintenance

**Comment by frankhereford** [comment]
An email has been sent with this dataset to @andrewshensky. The dataset is a GeoPackage in SRID 2277 of the polygons and a list of the attributes which I propose we persist into MAINT.

**Comment by frankhereford** [comment]
Andrew, I'm going to add you to this issue since you have really the larger job in this issue - thanks! I appreciate your help, and please let me know if there's anything I can do to assist.

**Comment by andrewshensky** [comment]
"ATD_ADMIN.vision_zero_polygons" has now been added to maint. This data is also in AGOL at the location below and shared out to the Vision Zero group.

https://austin.maps.arcgis.com/home/item.html?id=64c4509d548547ceb079455f3e5be896

**Next Tasks:** (I can track in seperate issues)

- Connect with Milad to set up a version in maint for him to edit 
- Publish the process in FME server to have the AGOL data updated daily
- Add AGOL service to Backup Manager

**Comment by patrickm02L** [comment]
Made an Issue to capture Andrew's follow up. Considering this complete.
