### ISSUE TITLE
Meeting: Finance Service Requests Usability Testing 

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12633]
### Objective 
Have Requesters start testing the Service Requests

### Participants
Christina, Diana, Sharon, Ronnie, Shelby, Max, Jenny, and Van

------
- [x] Schedule meeting
- [x] Meet and take notes

**Comment by ChristinaTremel** [comment]
### Timeline of Testing 
- Deadline for testing is July 14th!
- Set up check in for July 6th
- Will set up another check in on July 14th at the end of the testing period

### Timeline of Roll Out
- Usability testing through July 14th
- Set up lunch & learns throughout the last 2 weeks of July
- Implement new Service Request process beginning of August 

### Notes and Feedback from Meeting
- Need to remove "Date Needed By" and "Request Type" on Service Request Details page
- Add instructions on the Service Request Details page that the tables are editable.
- Rename in FDUs to "New Subproject SR No."
- Add IDs to the tables on the SR Details Page
- For Task Orders, the Encumbering FDU No. might be a new one that they are creating

**Comment by dianamartin** [comment]
# Diana's Notes
- Need to add "FDU connection" on TK job type
