### ISSUE TITLE
Port event trigger/lambda function postgres database trigger blueform_location_from_latlon

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12644]
The hasura event is called `blueform_location_from_latlon`. When this event is triggered, it triggers the following Lambda functions in AWS:
`atd-vz-data-events-crash_update_noncr3_location_staging` and `atd-vz-data-events-crash_update_noncr3_location_staging`.

We want to stop using these lambda functions/hasura events in the LDM and instead carry out their functions directly through our Postgres DB, whether through DB triggers, generated columns, or whatever the dev assigned thinks is the best route.

Past notes on what this lambda function does:
_Triggered on insert to atd_apd_blueform or update of columns latitude, longitude
This calculates a new location ID on crash location update if necessary and if the new location id is different from the old location id then it updates it. This seems like it could be converted to a DB trigger._

Source code can be found in AWS Lambda or https://github.com/cityofaustin/atd-vz-data/tree/master/atd-events/crash_update_noncr3_location

**Comment by frankhereford** [comment]
This issue was closed by merging 1305 into the LDM collector branch. Thanks to @mddilley for keeping track of everything up in the air and bringing this to our attention!!
