### ISSUE TITLE
Port event trigger/lambda function postgres database trigger jurisdiction_from_latlon

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12645]
Roses work in https://github.com/cityofaustin/atd-data-tech/issues/10126 will address how this is going to be done, when that issue is done this issue just consists of copying that work over into the LDM database.

**Comment by patrickm02L** [comment]
All that's left for this is migrating it to LDM

**Comment by johnclary** [comment]
We have this covered in the new data model 👍

**Comment by johnclary** [comment]
I re-assigned Rose and left the estimate on this since the work was done!
