### ISSUE TITLE
Meet with Randy to learn about his current workflow workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1265]
2/11/20

[Notes here](https://docs.google.com/document/d/14wveW5NieBU27cw1kTMgxxDlwiu8luNQdI3yvHnFBZE/edit#)

**Comment by amenity** [comment]
@SurbhiBakshi - I'd say let's hold off on meeting with Randy until he's actually going to be recording assignments in the app. I think he should be able to do next Monday's work without you.

**Comment by amenity** [comment]
@SurbhiBakshi - if you have any questions for Randy, stick 'em [here](https://docs.google.com/document/d/14wveW5NieBU27cw1kTMgxxDlwiu8luNQdI3yvHnFBZE/edit#) 🙏❓✍️

**Comment by SurbhiBakshi** [comment]
@amenity - added some questions for Randy. Questions related to invoicing, could be asked on Thursday, but I am not sure if he will attend that meeting.

**Comment by amenity** [comment]
Perfect, thank you, @SurbhiBakshi. Will also explicitly ask if he can call in on Thursday.

**Comment by amenity** [comment]
Notes from meeting with Randy for you to review, @SurbhiBakshi: https://docs.google.com/document/d/14wveW5NieBU27cw1kTMgxxDlwiu8luNQdI3yvHnFBZE/edit#

**Comment by SurbhiBakshi** [comment]
thanks! @amenity
