### ISSUE TITLE
Bug with DS Web Acceptance Email (SR) (Ready for deployment to PROD or closure)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12663]
### Bug related to work done on #11025 
Kim has an example of a DS where the Web Acceptance email didn't go to the applicant, it only went to the contact. Email was sent 6/15, the folder RSN is 13146062.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please proceed with debugging. Let @vschandramouli know if you need help.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP submitted; As this is portal related one, I need to test only when it is in DEV. Kindly approve and create task id for the same.

Commit ID: [2891ff1f231a](http://coaamandadevops02.austintexas.gov/R5:2891ff1f231a02fad2cdca3ef87b79e3cee297d8)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to DEV under** SCTASK0339907**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV, Please UAT

**Comment by Nadin-Nader** [comment]
UAT on DEV/TEST failed, Sree is analyzing

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Need to get in touch with Jenice on SMTP Email Servers in DEV & TEST.

**Comment by TracyLinder** [comment]
**Blocker:** Sree needs more examples of this happening in PROD, but that's something only external customers can identify. We'll have to move forward as best as possible without more examples. 

Sree will continue working with Jenice.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Spoke to Jenice and sent an email to Guru & Sri.  Guru replied to contact George, And got in touch with George! George mentioned that From address has strict restrictions that is only Austintexas.gov email id's can be used to send any emails.
		After updating the from user address We were able to test DEV & TEST and it is working as expected. The email delivered to all recipients (Applicant/Contact/Co-Applicant/Rightofway Contractor). Hence this can be closed until further issue occurs.
DEV & TEST RSN's - 
12898221 - TEST RSN  
12535679 - DEV RSN

**Comment by Nadin-Nader** [comment]
Asked kyle via Teams to UAT this on TEST and PROD

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan Kyle has UATd this and approved to move to PROD and/or Close

**Comment by Nadin-Nader** [comment]
This was UATd and approved By Kyle. Closing
