### ISSUE TITLE
Synchronize User Accounts Between Finance System and Data Tracker

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1266]

**Comment by johnclary** [comment]
@dianamartin i am working on a script to keep the data tracker and finance system accounts in place. 

in the meantime, would you import all of the AMD Technician accounts from Data Tracker into the finance system? You can make them "inventory viewer" user roles, and status `inactive`.

**Comment by dianamartin** [comment]
@johnclary I've added the technicians into the Finance and Purchasing system. I'll wait for Billy's response to clean up the list, but they're in there.

**Comment by johnclary** [comment]
thanks!

**Comment by amenity** [comment]
@johnclary @dianamartin - are we still waiting on Billy here?

**Comment by dianamartin** [comment]
@amenity No, I think we got Billy's response. The AMD technicians accounts were imported into the Finance system a while back. I guess I wasn't assigned to this and didn't know it was still open.

**Comment by amenity** [comment]
@dianamartin - cool. Can it be closed, then?

**Comment by dianamartin** [comment]
@amenity I defer to John to know for sure this is done and nothing else needs to be done.

**Comment by johnclary** [comment]
This one needs to stay open. This is the last piece of the inventory I've been meaning to get to.

**Comment by johnclary** [comment]
(Moving from in progress to on deck)
