### ISSUE TITLE
Create outreach materials for residents

### ISSUE THREAD

**Issue by madifan** [cityofaustin/atd-data-tech#12665]
## As a resident in Austin I want to see what construction projects there are in the city so I know how the constructions may impact my daily life (commute, travel, residence, business, etc.).

**Related to a problem?**
We are going to conduct usability testing on the Mobility Project Viewer to investigate the needs of external users, which requires creating outreach materials to the residents. 

**Desired Outcome?**
Outreach materials should comply with City of Austin's standards for outreach material towards residents. Materials should include a screener to understand which stakeholder group the participant is in, and an email that (1)introduces the purpose of the usability test, (2)explains compensation, and (3) includes a scheduling link. 

**Additional Context?**
Review the Innovations Office's research on compensating residents.
- [draft research report](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F11AO0H_b14oza5gvSmLVmPiU6HC7iX261k4hSqtx6qz4%2Fedit%23heading%3Dh.h5hsw4rbm6wg&data=05%7C01%7CMadison.Fan%40austintexas.gov%7C3dafa4f3c8ee4193245508db72a3e518%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638229820463666653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DjM06twZRXYa4tdBtp2nO5kaYX6xNwHypWMDHdttgeE%3D&reserved=0)
- [admin bulletin](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1GrlLHaSz0uHjAdADKwUYQp4yj2Juvl9XmUPj5makXHs%2Fedit&data=05%7C01%7CMadison.Fan%40austintexas.gov%7C3dafa4f3c8ee4193245508db72a3e518%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638229820463821997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3xs5IOeYGjVVUTc9lLXUdJJXbRbU1NLP7EsyWbqh8u4%3D&reserved=0)
- [draft guidelines website](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsites.google.com%2Fview%2Fcommunitycompensation%2Fhome&data=05%7C01%7CMadison.Fan%40austintexas.gov%7C3dafa4f3c8ee4193245508db72a3e518%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638229820463821997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n4xzuBsZeEHFGWaJsJ86enKayJwn8uBtn%2Fds%2B3GomTg%3D&reserved=0)
- [tremendous.com](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.tremendous.com%2F&data=05%7C01%7CMadison.Fan%40austintexas.gov%7C3dafa4f3c8ee4193245508db72a3e518%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638229820463821997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I8DnVoMQGEDcnR0lX7J7xxhZp0jGSGIJkS%2F%2F%2F4IXL34%3D&reserved=0)
---
**Acceptance criteria**

- [x] Screener: understand which external stakeholder group the participant belongs to. Refer to existing screeners in additional context section for questions to include. 
- [ ] Outreach email should include: introduction of usability testing, compensation, scheduling link.

**Comment by madifan** [comment]
@patrickm02L

**Comment by patrickm02L** [comment]
@amenity this is the place where we're talking about compensation. We'll need to sign up for Tremendous

**Comment by patrickm02L** [comment]
Use this example as a draft template for the screener
https://docs.google.com/forms/d/108evQUxGjse_ehwTqubZe92kdgMda2H9-mWLr0D6ZQQ/edit

Create by 7/7/23

**Comment by madifan** [comment]
Initial screener draft [link](https://forms.gle/FB3P8fUDyNNDiXsu7)

**Comment by patrickm02L** [comment]
> Initial screener draft [link](https://forms.gle/FB3P8fUDyNNDiXsu7)

Good start

# Feedback

## Information

- Change Title: 'Screener' to 'Interest Form'
- Edit to description text
   - The City of Austin Transportation Public Works Department is currently developing a publicly accessible map to update residents on ongoing projects. We invite Austin residents to provide valuable feedback on the most recent design iterations of our Mobility Project Viewer. For your participation, we are offering a $25 gift card as compensation. This form takes approximately 5 minutes to complete.

- Rearrange questions and group into categories


## User Testing
- How would you like to participate in Mobility Project Viewer usability testing?
- Do you have any constraints that might impact your ability to participate in a usability test? Please share any details or reflections that you think are pertinent to your involvement in this session.  

## Background
- Are you an Austin resident?
- What is your zipcode?
- In which neighborhood of Austin do you reside? (Optional)
- Which of the following represents you?
  - remove "Please check all that apply"
- Are you a part of any City of Austin groups...
   - change to city of Austin
- Have you attended a Council Meeting in Austin? 
   - could be deleted, let's run it by others first

## Contact
- Email
- Phone number
- First Name
- Last Name
- Hours of availability
   - 9am-12pm
   - 12-4pm
   - 4-7pm

**Comment by madifan** [comment]
Hi Patrick, I've implemented your feedback in the google form. The link is [here](https://forms.gle/C4y2zSjBfT4EwqSG7).

**Comment by madifan** [comment]
# 7/11
Received internal feedback on MPV usability test interest form. Form updates include:

1. add data.technology@austintexas.gov as contact
2. add timeframe for testing
3. link project page
4. add usability test description
5. add descriptions for why we want homeowner/renter and zipcode, and clarify the information won’t be used for anything else
6. make homeowner/renter question optional

**Comment by patrickm02L** [comment]
Usability Test plan and screener form can be found [in this folder](https://drive.google.com/drive/u/0/folders/1xEotbXmR_QtmNQ4YOswCiS1zeaVVzi73).
