### ISSUE TITLE
Update Existing SIF Bill Data Report Batch Job (SR) (Deploying to PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12683]
### Add two columns to existing SIF Data Report and update distribution list. 
- _See #10759_

- Email should only go to Dan H. Remove all others. 
- Add 2 columns to existing data:
- Exclude voided payments

> - Payment Date
> - Fee note/comment

**Comment by Nadin-Nader** [comment]
@TracyLinder Sree needs to get with you on this one

**Comment by TracyLinder** [comment]
Hi @Sreelatha-BlazeKannan please do the following:
 
Rearrange a few columns at the end
Analyze the duplicate data, as an example bill # 7701356 is showing 3 times in the data. Why? 

1. Bill Number 
2. Paid in Full Flag 
3.  Fee Comment 
4. Date Generated 
5. Payment Date
6. Bill Amount
7. Total Paid

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I verified the duplicate data and those are all voided bills/records. So adding another voidflag column to the excel and sending the data for your review.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Since we are adding fee comment and payment Date from two different tables it may feel like its pulling duplicates, but it is not. Highlighted the Duplicates for your verification. And for better understanding, added few other columns.

[Query - Result 08242023.xlsx](https://github.com/cityofaustin/atd-data-tech/files/12432708/Query.-.Result.08242023.xlsx)

Payment Number
Payment Comment 
VOID Flag
Payment Amount

**Comment by TracyLinder** [comment]
Sent to Dan for review.

**Comment by TracyLinder** [comment]
### Approved for PROD

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Need confirmation on distribution list, because here is the existing list
Dan.Hennessey@austintexas.gov, 
Madeleine.Hirsch@austintexas.gov, 
Van.Pham@austintexas.gov, 
Dan.Valbracht@austintexas.gov, 
[Erin.Williams@austintexas.gov](mailto:Erin.Williams@austintexas.gov)
And AC says remove all except Dan H.

Can I remove all others???

**Comment by Nadin-Nader** [comment]
Remove:
Madeline H.

Keep:
Van P
Dan H

Add:
Tomci A.
Jessica D.
Cary C.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0357040**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder -  TEST DP of #12683 submitted. Kindly approve and create task id for me.

Note: There is a manual commit DP also attached here which needs to be updated along with Dev Ops commit as such.

Commit ID: 29403976f817

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team and CTM to be deployed to TEST under two different TASKS:
**Manual	- SCTASK0360664
DevOps	- SCTASK0360665**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Both the above commits are in TEST and tested the same and looks good. Lets wait for our next run in TEST so, that this can be promoted to PROD if all looks good in TEST. Verified New email id's as well

**Comment by TracyLinder** [comment]
**BUG** - Dan received 2 emailed reports to him today with different data on each. This needs to be debugged. I forwarded the email to @Sreelatha-BlazeKannan

**Comment by TracyLinder** [comment]
- Sree explained one email was PROD, the other was the test report for this card
- I looked at the test data and it looks good
- I've asked Dan for approval to promote to PROD

**Comment by Nadin-Nader** [comment]
@TracyLinder have you heard back from Dan on if we can send to PROD?

**Comment by TracyLinder** [comment]
### UAT Results - Update needed

- Dan requested that we exclude payments that have been voided. 
- I will update the AC and put this On Deck for Sree to make the update.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV & TEST DP submitted with updated query. Got approval from Dan/Tracy upon verifying the data that I sent yesterday. Kindly approve and create task id for the same.

Commit ID: [3c70e2da8e4f](http://coaamandadevops02.austintexas.gov/R5:3c70e2da8e4fe409487ad1e9ac77575aaa6c7923)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to DEV and TEST under **SCTASK0367096**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - New updated query as per Dan is promoted to DEV & TEST; Test job schedule is on and it will run this Monday morning as per schedule. Let us verify this week before promoting to PROD.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Test run ran on 10/30/2023; trying to check with Dan on review and approval to promote it PROD.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan this is good to promote to PROD

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder -  PROD DP submitted. Kindly approve and create task id’s for the same. Need to create 2 tickets as one is for batch job manual update for email addresses and other one is for Devops update. 

Commit ID: 3c70e2da8e4f

**Comment by Nadin-Nader** [comment]
This has bee sent to the DevOps CM Team and the CTM CM Team to be deployed to PROD under 2 Deployment plans
DevOps Deployment = SCTASK0368295
Manual Deployment = SCTASK0368299

**Comment by Nadin-Nader** [comment]
The DevOps portion of this has been done. Waiting on the Manual Deployment for CTM:

Manual Deployment = SCTASK0368299

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Manual commit also done and verified as per Anu. And verified DevOps commit changes also. All looks good; we can wait until this Monday run in PROD for PROD Confirmation.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - TEST RUN & PROD RUN Executed this week; and Dan Confirmed that PROD Looks good in teams. I have deactivated the TEST job now. And Dan also confirmed that this can be Closed. Thank you!
