### ISSUE TITLE
Meeting & Follow-up Issues from Traffic Register Sprint Review 6/27/23

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12693]
### Objective 
Demo entire process for creating a Traffic Regulation 
Author -> Area Engineer -> City Traffic Engineer

### Participants
Christina, Eric, Dipti, Justin, Susanne, Joana, Anthony A, Ravi, Joshua, Daniel, Chrispin, Diana

### Agenda
- Used Traffic Reg 2023-0088 as an example to Author a new Traffic Regulation
------
- [x] Schedule meeting
- [x] Huddle with Chrispin to prepare
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [x] Create resulting issues

**Comment by ChristinaTremel** [comment]
## Feedback Notes

### City Traffic Engineer
- Add Anna Martin to the CTE drop down list (if Eric is out and a Regulation needs to be signed, she would sign as the CTE)

### Creating Reg line items
- Rename to “Current Reg Line Item #” on retire, retire and replace, install, and blank install
- `From Block` and `To Block` should be associated to Primary Street (so move these fields on form)
- Add `From Block` and `To Block` to Tow Away Zone sign type

### Add Regulation Detail Page
- Allow option to edit remarks for an entire regulation during the process of building the regulation. Typically, authors would add remarks at the end before submitting for review.
- Add the "Powers and Duties of Traffic Engineer” to the table view for all users (authors, TE, and CTE)

**Comment by ChrispinP** [comment]
All action items from the Sprint Review meeting are now completed.

Ready to review

**Comment by ChrispinP** [comment]
Reviewed with Christina last week, complete, closing
