### ISSUE TITLE
Auto Refresh Finance "Add Service Request Job" Page

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12697]
Needing to find a solution to an issue that's happening when adding Service Request Jobs. When submitted job transactions – the jobs are showing under all of the Service Request type tables (Subproj, FDU, TK, etc). Once a user refreshes the page, the issue is corrected. Would like to see a feature added when a new job is added.

[Example](https://atd.knack.com/finance-purchasing#new-service-request/add-jobs/649c85cff539470027c2c443/)

**Comment by johnclary** [comment]
i don't think this is quite what you're looking for, but wanted to point out [this custom refresh button](https://github.com/cityofaustin/atd-knack/blob/8f0e6be5df6a336c58317b846d30bda3605ff3b4/code/data-tracker/data-tracker.js#L667) we have in data tracker inventory.

**Comment by ChristinaTremel** [comment]
- this is a duplicate of #12589
