### ISSUE TITLE
Yearly OS Maintenance of all tablet devices

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#12694]
Next Apple iOS update: Estimated September 2023
Next Android Q3 update: Estimated Quarter 3 of this year

Set it as a yearly update of the latest version

Around 109 tablets will need to be updated.

**Comment by ChrispinP** [comment]
Going to close this for now after discussing. Since our internal testing of pushing updates did not work, it may be necessary to physically touch out of date devices to update their OS. This would be logistically difficult for the Apps team to do.
