### ISSUE TITLE
Follow up to vision_zero_polygons MAINT update

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12692]
Companion to #12636

## Deliverables

- [x] New AGOL map set up with a version in maint for Milad to edit
- [x] FME server process published to update AGOL data daily
- [x] AGOL service added to Backup Manager for data backup and recovery

**Comment by andrewshensky** [comment]
- [ ] Created version in Maint for Milad to edit in
- [ ] Sync'd up with Milad to demo update process using versioning
- [ ] FME work bench process has been created to add data from Maint to AGOL
- [ ] Added AGOL service to backup manager: Back ups captured weekly, Saturday's at 3am

Still to do:

- [ ] Publish/Test FME workbench process in FME Server

**Comment by andrewshensky** [comment]
The FME process to has been published to FME server and scheduled to update the AGOL data daily at 3am. I will move this issue to Review/QA until I can verify the process is running properly on its own

**Comment by andrewshensky** [comment]
FME Server process has been confirmed as running successfully. This issue will now be closed
