### ISSUE TITLE
Add Payment Types to UC Folder (10/18 Sprint) (SS) (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12706]
### Update valid payment types on the UC folder so cashier can manually apply the payment types from BO.

**UC valid payment types should be the following:**

- ACHO	Online - ACH
- AE	American Express
- AEO	Online - American Express
- CC	Credit Card (Unspecified)
- CH	Check
- COS	Cost of Service
- Cash	Cash
- DC	Debit Card
- DI	Discover
- DIO	Online - Discover
- FI	Finance
- JV	Journal Voucher
- MC	MasterCard
- MCO	Online - MasterCard
- MO	Money Order
- PO	Purchase Order
- Refund	Refund
- VI	Visa
- VIO	Online - Visa

**These are the current valid UC payment types:**

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/6522b492-58f5-47ed-a44e-36763620e606)

----

_INC0304721 assigned to ATD_AMANDA on 6/29/23_

**System Error:**`Invalid payment method for this folder type. `

Cashier w/ DSD is LeiLonnie L.

<img width="709" alt="Screenshot 2023-06-29 at 1 42 24 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/49930868/4c5202b8-3f1f-45e5-83fe-401272e64ac0">

**Comment by TracyLinder** [comment]
I'm going to close the SN and refer to this git issue.

**Comment by TracyLinder** [comment]
### Update
- I asked @Nadin-Nader to have a dev pull the valid payment types on UC
- I emailed the customer
- I closed the SN ticket. 


Hi Lei Lonnie, 

Your CTM service request was routed to my department for resolution. I closed the CTM request as we have our own issue tracking system; you can access your request [here](https://github.com/cityofaustin/atd-data-tech/issues/12706). 

We are troubleshooting this bug and will update you ASAP. Can you tell me if there has been a workaround to pay the invoice, or if the customer is waiting on this bug to be resolved?

Thank You,


Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
**Email to Lei Lonnie w/ Anthony T copied:**


Hi Lei Lonnie,

You will be unable to manually make a payment on the UC folder with American Express. We will update the UC folder to accept this payment type however this will take multiple weeks. Please advise your customer to go online to make the payment; American Express is a valid online payment option. 

If you need anymore assistance please let us know.

Thanks,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
AC is ready, moving to backlog.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to DEV and TEST under **SCTASK0366774**

**Comment by SubhaShroff** [comment]
Thanks @Nadin-Nader. This is in DEV/TEST and I have verified and tested on TEST. Its ready for UAT.

**Comment by Nadin-Nader** [comment]
Sent Kyle a message via Teams that this is ready for UAT on TEST. Waiting on Response

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been approved by Kyle, Please promote to PROD

**Comment by SubhaShroff** [comment]
Thank you @Nadin-Nader , Kyle.
Here is the PROD deployment request - SCTASK0368757.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to PROD

**Comment by SubhaShroff** [comment]
Thanks @Nadin-Nader.
I verified it on PROD DB. Ready for UAT on PROD.

**Comment by Nadin-Nader** [comment]
Sent ROW a message to UAT it. Waiting on response

**Comment by Nadin-Nader** [comment]
Approved by Kyle and possibly Jaclyn on PROD. Closing
