### ISSUE TITLE
Add Council District Areas to the VZ database

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12701]
In service of #12503, adding the Council District Areas to the FTT search, the areas need to be added to the database.

**Comment by frankhereford** [comment]
I'm not sure if this should get wrapped into this issue or not, but it might be an interesting consideration to bundle the script that comes out of this into an ETL that runs weekly. @patrickm02L

**Comment by patrickm02L** [comment]
> I'm not sure if this should get wrapped into this issue or not, but it might be an interesting consideration to bundle the script that comes out of this into an ETL that runs weekly. @patrickm02L

@roseeichelmann did we add the script from Engineering Areas to the weekly ETL?

**Comment by roseeichelmann** [comment]
@patrickm02L No, i didnt realize that was something that we wanted to do. Currently if updates are made to the engineering area ArcGIS Online polygons, we will need to manually run the script again (which might be fine if they rarely change?). Im down to wrap these both into ETLs that run weekly if we think its worth it.
