### ISSUE TITLE
Prevent System Emails from going to same address multiple times (SS) (on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12728]
### As per #11025 , we need to add a feature that will prevent the system from sending the same email multiple times to the same email address. This happens when the same email address is associated with all 4 people types:
-- Applicant
-- Right of Way Contractor (if listed)
-- Contact (if listed)
-- Billed To (if listed)

**Automated Emails to Update:**
    - Web Acceptance, Department Comments
    - Web Acceptance, Approved
    - Web Acceptance, Rejected
    - Options-> Email Bill from a generated bill in the Fee tab. (May not be happening per Subha, please verify.)
    - Options-> Print -> Email/Print Permit from the Folder tab. (May not be happening per Subha, please verify.)

**AC/Testing Criteria:**
1. Add the same people to the folder 4 times (one for each type)
2. Test each web acceptance attempt. The notification should only send one email. 
3. Test the invoice
4. Test the Email Permit from folder tab

**Comment by TracyLinder** [comment]
@Nadin-Nader This can be assigned for anlysis, but let's hold off on development until we review the results with ROW.

**Comment by TracyLinder** [comment]
### ROW Review Notes 7/7/23

- La Tonya asked for an update. Still in Needs Scoping. 
- We updated the AC
- Updated the need from 3 to 2
- Put in backlog

**Comment by TracyLinder** [comment]
FYI @Nadin-Nader this is ready to go on-deck

**Comment by SubhaShroff** [comment]
Analysis:
Tested this on TEST.
### PSM rsn - 13200938:
Though, there are people Applicant/Contact are same people with same email id - only one email was sent with each WAA accepted, Department Comments, Rejected.
NOTE: Rejected email was sent, but noticed no email body content. Need to retest and investigave.

### RW rsn - 13200946
Duplicate emails sent here, for Rejected. NEED TO FIX this.

TEST Testing/Analysis is in progress........................................................

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps Team to be deployed to DEV under **SCTASK0355924**

**Comment by SubhaShroff** [comment]
Thanks for sending it for Promotion @Nadin-Nader. 
I tested it on DEV. Its ready for TEST deployment. Thanks.
### DEV Testing
EX RSN - 13199813  - Single emails sent for - Department Comments, Accepted, Rejected.
RW RSN - 13199814 - Single emails sent for - Department Comments, Accepted, Rejected.
[12728-7a429a2dc8fe - TEST Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/12677075/12728-7a429a2dc8fe.-.TEST.Deployment.Plan.docx)
Please send this for TEST promotion.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to TEST under **SCTASK0357396**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Thank you for raising the request. I tested it on TEST for RW, EX.
RW RSN- 13200946. -- Single emails sent for - Department Comments, Accepted, Rejected.
Yet to test for EX............

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Kyle had given a feedback on Friday that its partially approved on TEST as its not working on Folder Tab emails. It still adds duplication ids on CC. I am looking into it.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @KyleErich  As I debugged I realized what shows up on CC is logged in AMANDA user email id. In the below screenshot, it shows my email id. Since Kyle was logged in to test it shows Kyle's email id and applicant also has the same email id. I also, tested it for multiple permits and confirm that it doesn't add duplicate emails.
Even as if it adds same email-id on TO, CC, BCC the system still sends only one email but not multiples.
Please let me know if still have any concerns. Thanks.

**Comment by KyleErich** [comment]
@SubhaShroff Okay thanks Subha. This UAT is approved then.
CC @Nadin-Nader

**Comment by SubhaShroff** [comment]
Thank you @KyleErich. Sorry forgot to add the screenshot I mentioned above comment.  @Nadin-Nader  I will send you the PROD deployment plan soon.
![image](https://github.com/cityofaustin/atd-data-tech/assets/51680715/45506f7b-7ec2-4228-90f3-7e8364117fd9)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  please send this to PROD. Thanks.
[12728-7a429a2dc8fe - PROD Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/12819621/12728-7a429a2dc8fe.-.PROD.Deployment.Plan.docx)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @KyleErich This is deployed on PROD as priority. I verified the code on PROD database for the changes. Please review on PROD. Thank you.

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff UAT approved on PROD. Thanks.

**Comment by Nadin-Nader** [comment]
Closing as this was approved by Kyle
