### ISSUE TITLE
PSM Needs People Types Added

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#12729]
### PSM people types should allow users to select any valid people type; currently the list of types is very small. 

- Users should be able to choose any valid people type to the PSM folder.

**Comment by TracyLinder** [comment]
This is ready for development.

**Comment by TracyLinder** [comment]
### Backlog Refinement notes 8/29/23

- This looks to be fixed. I see all people types in the people type drop-down. 
- Priya checked the config - there are no default people types anymore, so now users can see all types.

**Comment by Nadin-Nader** [comment]
This is no longer needed as all the people types are available
