### ISSUE TITLE
Upgrade the RDS database `atd-postgrest`

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12731]
AWS intends to retire M4, R4 & T2 class instances by April, 2024. `ATD-postgrest` currently uses a `T2` class instance and will need to be upgraded, likely to a T3. I imagine that the route will be something like this:

* Announce downtime
* Snap backup
* Shutdown instance
* Boot a new one off the backup
* Configure the postgrest service to point to the new RDS endpoint

**Comment by frankhereford** [comment]
@chiaberry I'll bring this to grooming & planning at some point closer to the due date or anytime that you'd like me to. If there is any other way you'd prefer for this to be handled or prioritized, of course, please just let me know. Thanks!

**Comment by johnclary** [comment]
this instance will be upgraded to a `T3` during the upcoming maintenance window at ~11pm on Friday 7/21.

**Comment by frankhereford** [comment]
<img width="206" alt="image" src="https://github.com/cityofaustin/atd-data-tech/assets/3653206/032ef51c-87fb-4044-b083-d071c00c574e">

Looks like this went off as planned - thank you John!

**Comment by johnclary** [comment]
🎉 ✅
