### ISSUE TITLE
Upgrade Moped's primary RDS server to a T3 class server NLT April, 2024

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12730]
AWS intends to retire `M4`, `R4` & `T2` class instances by April, 2024. Moped currently uses a T2 class instance and will need to be upgraded, likely to a T3. I imagine that the route will be something like this:

* Announce downtime
* Snap a backup of the database
* Shut the old one down
  * Including its read replica
* Boot up a new one off that snapshot
* Setup the new read replica
* Restart or reconfigure services which point at the DB, because the RDS endpoint will have changed
  * graphql-engine
  * Entries in 1PW

**Comment by frankhereford** [comment]
@johnclary I'm going to assign you on this so you can include it in grooming or planning whenever you think is best. Thanks!

**Comment by johnclary** [comment]
Scheduled for tomorrow (9/7) at 12:50am CDT.

**Comment by johnclary** [comment]
It's done; the Moped DB is now on a `db.t3.medium` instance!
