### ISSUE TITLE
Integrate `logrotated` into Airflow V2 stack

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12736]
Airflow stores the output of DAG runs and other stateful information in the form of many, many text files in a rich hierarchy of directories. Presently, on our data03 stack in the `logs` folder, the following is reported:

```
# find | wc
 125956  125956 12917878
# du -sch *
7.2M	dag_id=atd_service_bot_issue_intake_production
20K	dag_id=test_slack_notifier_production
386M	dag_id=weather-checker
73M	dag_processor_manager
111M	scheduler
576M	total
```

This indicates 125K or so files & directories totaling a half gig of data. This is a non-trivial amount, and we can expect this size to grow rapidly. 

This issue is to track the configuration of `logrotated` to daily archive these and ultimately remove the archives after a configured amount of storage time. 

- [ ] add documentation to readme

CC @mddilley & @johnclary

**Comment by frankhereford** [comment]
@johnclary @mddilley 

We discussed different options including using logrotate with its straight-forward configuration syntax to do this, using wildcard designations for the files we want to remove. This can be kicked off, it sounds like, using a logrotate command or by configuring the logrotate system to do this on a schedule.

An other option would be to use a combination of the `find` and `xargs` commands to find directories of a certain age and pipe them into `xargs` to delete them.

We're going to pick this back up in an airflow check-in meeting to groom, assign and get these remaining items wrapped up.

**Comment by chiaberry** [comment]
set up a mini skill share in the place of a formal PR review
