### ISSUE TITLE
[Spike] Investigate and propose resolution for issues with Conflict Resolution System

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12748]
## Description
This Issue allows us to do some discovery before trying to resolve on #10509: 
- The excessive number of records in the Conflict Resolution System (Changes Tab)
- We also want to ensure that relevant conflicts are displayed to the VZ team while protecting important fields from overwrite edits

## Objective

- Analyze the excessive records (over 10,000) in the Changes Tab and determine the cause of the issue
- The system should filter and display conflicts relevant to Xavier while protecting important fields
- [Per Xavier](https://github.com/cityofaustin/atd-data-tech/issues/10509#issuecomment-1594627037), The following fields should be considered as important fields: 
  - `crashes` `private_dr_fl`
  - `crashes` `on_sys_fl`
  - `persons` `prsn_injry_sev_id`
  - `primarypersons` `prsn_injry_sev_id`
- The approval process should only be required for crashes with `crashes` `austin_full_purpose` set to 'Y'.
- Latitude and longitude pairs should be investigated to prevent overwriting
   - Figure out what all the pairs are (there are four)
   - on insert take CRIS lat_long, don't overwrite lat_long_primary
   - investigate other lat_long pairs
- Review the ETL to identify potential conflicts caused by turning off updates

## Deliverables
1. Summary outlining the causes of excessive records in the Changes Tab
3. Proposal for an updated Conflict Resolution System that filters and displays relevant conflicts to Xavier while protecting important fields

## Notes
- We'll need to look at the CR3 updates prior to 6/1/23, with the intention of backfilling with the enhanced ETL
- Determine ways to help Xavier in the short-term (next 2-weeks) 
- This discovery is limited to 2-3 hours and will help us determine how to move forward on #10509
Collaboration with Xavier will be required throughout the process

**Comment by patrickm02L** [comment]
@patrickm02L move the PDF related content to #12748

**Comment by patrickm02L** [comment]
## 11/13
Was reviewing this with @xavierapostol this Issue started in April 2023 with a TXDOT update, and has since halted with the promise of delivering the LDM which will resolve this. 

Because LDM is taking longer than expected, we may need to pick this up Issue before the LDM competition.

**Comment by johnclary** [comment]
We're going to completely remove the conflict resolution system as part of the new data model 👍
