### ISSUE TITLE
Expenses and Revenue Financial Data data pipeline for Power BI

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#12775]
Set up an ETL that will automate the process of updating the revenue and expenses tabs of dash. The data is accessible through microstrategy and we will have to pull the data at least monthly. I've already done some of the leg work on this and have an idea on how to use the microstrategy API on how to accomplish this.

**Comment by amenity** [comment]
@Charlie-Henry - set up a meeting with Peggy & Erin to review work so far.

**Comment by Charlie-Henry** [comment]
Erin viewed the dashboard and I supplied some changes based on her requests, I think we're good unless she has more comments!
