### ISSUE TITLE
[Spike] Perform secondary research on municipal data tracking and management models

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#12783]
- [The CitiStat Model](https://www.americanprogress.org/article/the-citistat-model-how-data-driven-government-can-increase-efficiency-and-effectiveness/): How Data-Driven Government Can Increase Efficiency & Effectiveness
   - https://ash.harvard.edu/news/citistat 
   - [The Varieties of CitiStat](https://www.jstor.org/stable/pdf/3843915.pdf?refreqid=excelsior%3Ad1d6063cbabc304d471f5d5890e468f0&ab_segments=&origin=&initiator=&acceptTC=1) (https://www.jstor.org/stable/3843915?seq=4)
- CompStat - NYC
   - [CompStat 2.0](https://compstat.nypdonline.org/2e5c3f4b-85c1-4635-83c6-22b27fe7c75c/view/89) 
   - [CompStat wikipedia page](https://en.wikipedia.org/wiki/CompStat)
   - [NYPD and CompStat](https://ccnmtl.columbia.edu/projects/caseconsortium/casestudies/127/casestudy/www/layout/case_id_127_id_886.html)
   - [NYPD's Compstat: Compare Statistics or Compose Statistics?](https://www.ojp.gov/ncjrs/virtual-library/abstracts/nypds-compstat-compare-statistics-or-compose-statistics) 
   - [The Controversial Crime-Fighting Program That Changed Big-City Policing Forever](https://nymag.com/intelligencer/2018/03/the-crime-fighting-program-that-changed-new-york-forever.html)
   - [Metrics Management and Bureaucratic Accountability: Evidence from Policing](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ajps.12661)
- [Baltimore Stat](https://www.businessofgovernment.org/sites/default/files/CitiStat.pdf) 
   - [CitiStat: Mapping Municipal Performance](https://proceedings.esri.com/library/userconf/proc02/abstracts/a1012.html)
   - https://www.esri.com/about/newsroom/arcuser/map-it-believe-it-see-it/

**Comment by amenity** [comment]
@katelunceford - former CIF fellow Janet found Miro to be a good tool for [her secondary research](https://miro.com/app/board/o9J_l_y7IaA=/?moveToWidget=3074457360219369326&cot=14) for #1106. Shall we start a Dash Miro board?

**Comment by katelunceford** [comment]
@amenity this is a fabulous resource, thank you! I will most definitely start a Dash miro board
