### ISSUE TITLE
MDS: ATD-Client: Test with providers: Razor

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#1279]
We need to test Razor with all versions of MDS, it should be compatible with version 2,3 or 4:
https://github.com/openmobilityfoundation/mobility-data-specification/blob/master/providers.csv

**Comment by sergiogcx** [comment]
John mentioned we do not have credentials for Razor, while the MDS library is ready we need to get access and an endpoint. Postponing for next sprint.

**Comment by JaceDeloney** [comment]
This provider is not on the official micromobility operator list that was sent from shared mobility services. Closing
