### ISSUE TITLE
Remove HTML comments, which often hide email addresses, from DTS GitHub issue dataset on the Open Data Portal

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12802]
Please see [this conversation](https://austininnovation.slack.com/archives/CHZE6BC6L/p1689024141852599?thread_ts=1689023466.111509&cid=CHZE6BC6L), beginning with @dianamartin's observation about email addresses being published. Thanks for bringing this up!

This issue is to track the removal of those, potentially though parsing the contents as HTML and removing comments. This transformation may belong in the ETL scripts which maintain these datasets. 

Note:  This task is to hide HTML comments, not email addresses. The intent here is to empower the service desk operator to hide or not hide details found in a GitHub issue before it is sent on to our [open data portal](https://data.austintexas.gov/Transportation-and-Mobility/ATD-Data-Tech-Services-Issues/rzwg-fyv8). Additionally, this is to confirm that the data set is truncated on the ODP and all past and present issues are processed with this new eye to hide comments.

**Comment by frankhereford** [comment]
I'll bring this to grooming / planning to see when we want to pick this up. Thanks!

**Comment by frankhereford** [comment]
Here's the dataset in question: https://data.austintexas.gov/Transportation-and-Mobility/ATD-Data-Tech-Services-Issues/rzwg-fyv8

**Comment by chiaberry** [comment]
https://github.com/cityofaustin/atd-service-bot/blob/production/issues_to_socrata.py

**Comment by chiaberry** [comment]
we have a TEST dataset: https://datahub.austintexas.gov/Transportation-and-Mobility/TEST-ATD-Data-Tech-Services-Issues/93ru-6p6e
