### ISSUE TITLE
[Open Data Portal] Change Markings Dates datasets from internal to public in ODP

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#12807]
Meeting on 7/14 w/ Andrew to make markings dates table public. Collect metadata from GISDM to publish.
- [x] Markings_short_line_dates
- [x] Markings_specialty_line_dates
- [x] Markings_specialty_points_dates

## Possible To Do
- [ ] Remove `CREATED_BY`, `CREATED_DATE`, `MODIFIED_BY`, and `MODIFIED_DATE`
    - They are set to the refresh date from GISMAINT -> GISDM so it is not accurate
- [ ] Should `OBJECTID` and `GLOBALID` be removed as well?
- [ ] Humanize column names from ODP if possible?
- [ ] Markings_Specialty_point_dates is missing metadata in GISDM but is populated in GISMAINT?

Below is metadata from GISDM. Added line of related layer link from ODP

**Comment by susannegov** [comment]
# Markings Short Line Dates
## Description
Related table of short line markings dates. The work order ID originated from the roadway markings work orders and the contractor work order dataset that pulls from the Signs and Markings Operations Work Order tracking system. The work dates originate from data tracker or were collected in GIS prior to the association of work order IDs to short line markings assets. Short line includes crosswalks, stop lines, school zone lines, and yield lines.

This dataset contains related records for the TRANSPORTATION.markings_short_line layer: https://data.austintexas.gov/Transportation-and-Mobility/TRANSPORTATION-markings_short_line/9hak-anfp
## About this Dataset
- **Update Frequency:** Daily
- **Department Name:** Austin Transportation
- **Category:** Transportation and Mobility
- **Tags:** atd, austin, transportation, short line, crosswalk, stop bar, stop line, school zone line, transverse, continental, yield line, signs and markings, pavement markings, roadway markings, markings, dates

| Column Name | Description | Type |
|----|----|----|
|OBJECTID|The object ID| Number|
|MARKINGS_SHORT_LINE_ID|The related markings short line ID| Number|
|ATD_WORK_ORDER_ID|The related markings work order ID|Plain Text|
|TYPE_WORK| The type of work done|Plain Text|
|WORK_DATE|
|DATE_SOURCE|
|WORK_ORIGIN|
|ASSET_CONDITION|The asset condition from the type work field|Plain Text|
|GLOBALID| The global ID|Plain Text|

**Comment by susannegov** [comment]
# [Markings Specialty Line Dates](https://datahub.austintexas.gov/dataset/TRANSPORTATION-markings_specialty_line_dates/him5-nbts)
## Description
Related table of specialty line markings dates. The work order ID originated from the roadway markings work orders and the contractor work order dataset that pulls from the Signs and Markings Operations Work Order tracking system. The work dates originate from data tracker or were collected in GIS prior to the association of work order IDs to specialty markings assets. Specialty markings include delineators, curbs, raised pavement marking lane separators, and concrete domes.

This dataset contains related records for the TRANSPORTATION.markings_specialty_line layer: https://data.austintexas.gov/Transportation-and-Mobility/TRANSPORTATION_markings_specialty_line/rczx-h2ey
## About this Dataset
- **Update Frequency:** Daily
- **Department Name:** Austin Transportation
- **Category:** Transportation and Mobility
- **Tags:** atd, legends, marking, parking, pavement marking, line, roadway markings, raised pavement marking, rpm, delineators, channelizers, curbs, dates, concrete domes
- **Dataset Owner:** Austin Transportation
- **Data Provided by:** City of Austin, Texas - data.austintexas.gov

| Column Name | Description | Type |
|----|----|----|
|OBJECTID|The object ID| Number|
|MARKINGS_SPECIALTY_LINE_ID|The related markings specialty line ID| Number|
|ATD_WORK_ORDER_ID|The related markings work order ID|Plain Text|
|TYPE_WORK| The type of work done|Plain Text|
|WORK_DATE| The datetime work was done|Date & Time|
|DATE_SOURCE|Origin of markings date record. All records created prior to 2019 did not record work order IDs|Plain Text|
|WORK_ORIGIN|Whether the work was done in-house or by contractor|Plain Text|
|ASSET_CONDITION|The asset condition from the type work field|Plain Text|
|GLOBALID| The global ID|Plain Text|

**Comment by susannegov** [comment]
# [Markings Specialty Point Dates](https://datahub.austintexas.gov/dataset/TRANSPORTATION-markings_specialty_point_dates/p5hm-ra6d)
## Description
Related table of specialty markings dates. The work order ID originated from the roadway markings work orders and the contractor work order dataset that pulls from the Signs and Markings Operations Work Order tracking system. The work dates originate from data tracker or were collected in GIS prior to the association of work order IDs to specialty markings assets. Specialty markings are separated into types that include arrows, word legends, parking space boundaries, raised pavement markings (RPM), symbols, and other pavement markings.

This dataset contains related records for the TRANSPORTATION.markings_specialty_point layer: https://data.austintexas.gov/Transportation-and-Mobility/TRANSPORTATION_markings_specialty_point/53jy-y8pj
## About this Dataset
- **Update Frequency:** Daily
- **Department Name:** Austin Transportation
- **Category:** Transportation and Mobility
- **Tags:** arrows, atd, legends, marking, parking, pavement marking, point, raised pavement marking, rpm, specialty markings, symbols, word, dates
- **Dataset Owner:** Austin Transportation
- **Data Provided by:** City of Austin, Texas - data.austintexas.gov

| Column Name | Description | Type |
|----|----|----|
|OBJECTID|The object ID| Number|
|MARKINGS_SPECIALTY_POINT_ID|The related markings specialty point ID| Number|
|ATD_WORK_ORDER_ID|The related markings work order ID|Plain Text|
|TYPE_WORK| The type of work done|Plain Text|
|WORK_DATE| The datetime work was done|Date & Time|
|DATE_SOURCE|Origin of markings date record. All records created prior to 2019 did not record work order IDs|Plain Text|
|WORK_ORIGIN|Whether the work was done in-house or by contractor|Plain Text|
|ASSET_CONDITION|The asset condition from the type work field|Plain Text|
|GLOBALID| The global ID|Plain Text|

**Comment by andrewshensky** [comment]
@susannegov metadata has been added in the open data portal for all three dates tables. All three are now public. I was able to rerun the workspace with all three processes together locally and in FME Server successfully. I have overwritten the previously used workspace in FME Server so it should run daily around 2am

**Comment by susannegov** [comment]
I see them listed as public on the ODP. Will check again next week to make sure FME server is doing it correctly. if looks good will close it out

- [ ] Check the datasets next week
- [ ] Update data source on PBI
