### ISSUE TITLE
Generate Arcade Expression to Auto-Calculate Sign Sub Categories

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#12818]
Sample expression below:

```
var StopYield = ['R1-1', 
'R1-2', 
'R1-2aP', 
'R1-2bTP', 
'R1-2cTP', 
'R1-3P' 
]; 

var Speed = ['R2-1', 
'R2-4a', 
'ATDR-216' 
]; 

when(Includes(StopYield, MUTCDCode), "Stop/Yield", $feature.ASSET_SUB_CATEGORY) 
when(Includes(Speed, MUTCDCode), "Speed", $feature.ASSET_SUB_CATEGORY)

**Comment by Colemonj** [comment]
I was able to successfully create an expression for calculating the asset sub-category field. The expression is posted below:

var MUTCDCode = $feature.MUTCD_CODE

var StopYield = ['R1-1', 
'R1-2', 
'R1-2aP', 
'R1-2bTP', 
'R1-2cTP', 
'R1-3P' 
];

var SpeedLimit = ['R2-1', 
'R2-4a', 
'ATDR-216' 
];

var Pedestrian = ['R1-5R',
'R1-5L',
'R1-5aR',
'R1-5aL',
'R1-5bR',
'R1-5bL',
'R1-5cR',
'R1-5cL',
'R1-6',
'R1-6a',
'R5-10a',
'R9-3bP',
'R10-1',
'R10-3b',
'R10-3e',
'R10-15R',
'R10-15L',
'W11-2',
'W11-15',
'W11-9',
'ATDW-103',
'ATDW-107',
'ATDR-215',
'ATDW-110'
];

var MovementProhibition = ['R3-1R',
'R3-2L',
'R3-3',
'R3-4',
'R3-18',
'R10-11',
'R10-11d'
];

var StreetName = ['W16-8aP',
'D3-1'
];

var RailRoad = ['R3-1aR',
'R3-2aL',
'R8-8',
'R8-9',
'R8-10',
'R8-10a',
'R15-6a',
'R15-8',
'W10-1',
'W10-1aP',
'W10-2',
'W10-3',
'W10-4',
'W10-5',
'W10-5P',
'W10-9',
'W10-9P',
'W10-11',
'W10-12',
'W10-13P',
'W10-14P',
'W10-14aP',
'W10-1'
];

var Bicycle = ['R3-17',
'R4-4',
'R4-11',
'R9-5',
'R9-6',
'W7-5',
'W8-10',
'D11-1',
'D11-1c',
'D11-1bP',
'R923-aL',
'ATD-5',
'R1-6b',
'ATDR-208',
'R9-5 Mod',
'ATDR-211',
'ATDR-213',
'ATDR-214',
'ATDR-218'
];

var SupplementalPlaque = ['R3-17aP',
'R3-17bP',
'W16-1P',
'W16-2P',
'W16-2aP',
'W16-3P',
'W16-3aP',
'W16-4P',
'W16-5PR',
'W16-5PL',
'W16-6PR',
'W16-6PL',
'W16-7PR',
'W16-7PL',
'W16-9P',
'W16-11P',
'W16-13P',
'ATDR-210'
];

var LaneControl = ['R3-5',
'R3-5fP',
'R3-5gP',
'R3-7R',
'R3-7L',
'R3-9a',
'R3-9b',
'R3-9cP',
'R3-9dP',
'R3-20R',
'R3-20L',
'R3-23',
'R3-23a',
'ATDR-204',
'ATDR-205',
'ATDR-206',
'ATDR-207',
'ATDR-209',
'R3-8',
'ATDR-212'
];

var TrafficFlow = ['R4-1',
'R4-2',
'R4-3bT',
'R4-7R',
'R4-7aR',
'R4-7bR',
'R4-8L',
'R4-8aL',
'R4-8bL',
'R4-8cL',
'W4-1',
'W4-2R',
'W4-2L',
'W4-3R',
'W4-3L',
'W4-5',
'W4-5P',
'W4-6',
'W6-3',
'W9-1R',
'W9-1L',
'W9-2R',
'W9-2L',
'W6-3 Mod'
];

var SelectiveExclusion = ['R5-1',
'R5-1a',
'R5-2',
'R5-3',
'R5-6',
'R9-3',
'R9-13',
'R9-14'
];

var OneWay = ['R6-1R',
'R6-1L'
];

var Roundabout = ['R6-4',
'R6-4a',
'R6-4b',
'R6-5P',
'W2-6',
'W16-12P'
];

var Parking = ['R7-2',
'R7-4',
'R7-1',
'R7-22R',
'R7-22L',
'R7-8T',
'R7-8P',
'R7-11Ta',
'R7-11Tb',
'R7-11Tc',
'R7-11Td',
'R7-11Td',
'R7-20',
'R7-23',
'R7-108',
'R7-201P',
'R8-7',
'D4-4T',
'ATD-4',
'ATDR-201',
'ATDR-202',
'ATDR-203',
'R7-22'
];

var TrafficSignal = ['R10-5',
'R10-6',
'R10-6a',
'R10-7',
'R10-7T',
'R10-8',
'R10-10',
'R10-11a',
'R10-11Ta',
'R10-11b',
'R10-11c',
'R10-12',
'R10-13',
'R10-16',
'R10-17T',
'R10-17a',
'R10-20aP',
'R10-23',
'R10-27',
'R10-30',
'R10-31P',
'ATDR-217'
];

var RoadClosed = ['R11-1',
'R11-2',
'R11-2aT',
'R11-2cT',
'R11-4'
];

var School = ['S4-1P',
'S4-2P',
'S4-4P',
'S4-6P',
'S4-7P',
'S5-1',
'S5-2',
'S5-3',
'S1-1',
'S3-1',
'S4-3P',
'S7-1T'
];

var HorizontalAlignment = ['W1-1R',
'W1-1L',
'W1-1aR',
'W1-1aL',
'W1-2R',
'W1-2L',
'W1-2aR',
'W1-2aL',
'W1-3R',
'W1-3L',
'W1-4R',
'W1-4L',
'W1-5L',
'W1-5R',
'W1-6R',
'W1-6L',
'W1-8R',
'W1-8L',
'W1-10R',
'W1-10aR',
'W1-10bR',
'W1-10cR',
'W1-10dR',
'W1-10eR',
'W1-11R',
'W1-11L',
'W1-15L',
'W13-1P'
];

var Intersections = ['W1-7',
'W2-1',
'W2-2R',
'W2-2L',
'W2-3R',
'W2-3L',
'W2-4',
'W2-5',
'W2-7L',
'W2-7R',
'W2-8',
'W4-4P',
'W4-4aPR',
'W4-4aPL',
'W4-4bP'
];

var AdvancedTrafficControl = ['W3-1',
'W3-2',
'W3-3',
'W3-4',
'W17-1 Mod'
];

var CrossSection = ['W5-1',
'W5-2',
'W5-3',
'W6-1',
'W6-2',
'W12-1',
'W12-2',
'W14-1',
'W14-2',
'W14-1aR',
'W14-1aL',
'W14-2aR',
'W14-2aL',
'W14-1T'
];

var VerticalAlignment = ['W7-1',
'W7-1a',
'W7-2P',
'W7-2bP',
'W7-3P',
'W7-3aP',
'W7-3bP',
'W7-6',
'ATDW-104'
];

var SurfaceCondition = ['W8-1',
'W8-2',
'W8-3',
'W8-4',
'W8-7',
'W8-8',
'W8-9',
'W8-11',
'W8-12',
'W8-14',
'W8-15',
'W8-15P',
'W8-17',
'W8-17P',
'W8-23',
'W8-25',
'W17-1'
];

var Weather = ['W8-5',
'W8-5P',
'W8-10P',
'W8-13',
'W8-18',
'W8-19'
];

var Vehicular = ['W8-6',
'W11-1',
'W11-8',
'W11-10',
'W11-11',
'W11-12P',
'W11-15a'
];

var NonVehicular = ['W11-3',
'W11-22',
'W11-7',
'W15-1',
'ATDW-102',
'ATDW-101'
];

var ObjectMarker = ['OM3-L',
'OM3-C',
'OM3-R',
'OM4-3',
'OM2-2V',
'OM4-1'
];

var DirectionalAuxiliary = ['M5-4',
'M5-5',
'M5-6',
'M6-1R',
'M6-1L',
'M6-2R',
'M6-2L',
'M6-2aR',
'M6-2aL',
'M6-3'
];

var GeneralServiceSign = ['D9-2'];

var GeneralInformation = ['I-5',
'ATD-1',
'ATDG-101',
'ATDG-102',
'ATDG-103',
'ATDG-104',
'ATDG-105'
];


if(Includes(StopYield, MUTCDCode)){
    return "Stop/Yield"
}else if(Includes(SpeedLimit, MUTCDCode)){
    return "Speed Limit"
}else if(Includes(Pedestrian, MUTCDCode)){
    return "Pedestrian"
}else if(Includes(MovementProhibition, MUTCDCode)){
    return "Movement Prohibition"
}else if(Includes(StreetName, MUTCDCode)){
    return "Street Name"
}else if(Includes(RailRoad, MUTCDCode)){
    return "Rail Road"
}else if(Includes(Bicycle, MUTCDCode)){
    return "Bicycle"
}else if(Includes(SupplementalPlaque, MUTCDCode)){
    return "Supplemental Plaque"
}else if(Includes(LaneControl, MUTCDCode)){
    return "Lane Control"
}else if(Includes(TrafficFlow, MUTCDCode)){
    return "Traffic Flow"
}else if(Includes(SelectiveExclusion, MUTCDCode)){
    return "Selective Exclusion"
}else if(Includes(OneWay, MUTCDCode)){
    return "One Way"
}else if(Includes(Roundabout, MUTCDCode)){
    return "Roundabout"
}else if(Includes(Parking, MUTCDCode)){
    return "Parking"
}else if(Includes(TrafficSignal, MUTCDCode)){
    return "Traffic Signal"
}else if(Includes(RoadClosed, MUTCDCode)){
    return "Road Closed"
}else if(Includes(School, MUTCDCode)){
    return "School"
}else if(Includes(HorizontalAlignment, MUTCDCode)){
    return "Horizontal Alignment"
}else if(Includes(Intersections, MUTCDCode)){
    return "Intersections"
}else if(Includes(AdvancedTrafficControl, MUTCDCode)){
    return "Advanced Traffic Control"
}else if(Includes(CrossSection, MUTCDCode)){
    return "Cross Section"
}else if(Includes(VerticalAlignment, MUTCDCode)){
    return "Vertical Alignment"
}else if(Includes(SurfaceCondition, MUTCDCode)){
    return "Surface Condition"
}else if(Includes(Weather, MUTCDCode)){
    return "Weather"
}else if(Includes(Vehicular, MUTCDCode)){
    return "Vehicular"
}else if(Includes(NonVehicular, MUTCDCode)){
    return "Non-Vehicular"
}else if(Includes(ObjectMarker, MUTCDCode)){
    return "Object Marker"
}else if(Includes(DirectionalAuxiliary, MUTCDCode)){
    return "Directional Auxiliary"
}else if(Includes(GeneralServiceSign, MUTCDCode)){
    return "General Service Sign"
}else if(Includes(GeneralInformation, MUTCDCode)){
    return "General Information"


}else{
    return 'Error'
}
