### ISSUE TITLE
IT Purchase Request for more computers - July 2023

### ISSUE THREAD

**Issue by scottreedy** [cityofaustin/atd-data-tech#12829]
CTM Request  REQ0153122 07/12/2023 
PR0015798 - REQ0153122 07/12/2023    ATD-07-5963 07/12/2023

**Comment by scottreedy** [comment]
Dell Precision's and the Latitude 9440's have shipped as of 08/01/2023

**Comment by scottreedy** [comment]
The following order has arrived at the TDC and is now available for pickup: 
 
02 - Dell EcoLoop Urban Backpack (Gray) 
20 - Dell Essential Backpack 15 
02 - Dell Performance Dock- WD19DCS 
22 - Dell Pro Wireless Keyboard and Mouse 
20 - Dell Dock 
02 - Mobile Precision 7670 
04 - Dell Latitude 9440 
20 - Dell Latitude 5540 
 
Service Now PR#: PR0015798 
DO#: 5600 23072010712
  Please remember to provide/present the referencing information at the time of pickup
Please pick-up by: 8/22/2023

**Comment by scottreedy** [comment]
CTM will pickup and deliver this week 08/09/2023

**Comment by scottreedy** [comment]
All computers received into HW DB, imaged and ready to deploy

**Comment by JBStrangenew** [comment]
Do Not Delete:
CTM Request  REQ0153122 07/12/2023 
PR0015798 - REQ0153122 07/12/2023    ATD-07-5963 07/12/2023
