### ISSUE TITLE
[SharePoint - 0365] Migrate SMO SharePoint Site from Teams to a Standalone Site

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#12823]
## Context: 
Smart Mobility Office (SMO) has a Teams-based SharePoint website (storage upgraded to 100GB 7/11/2023). In addition to the storage limit issues, CTM does not recommend basing division SharePoint sites in Teams due to permissions and access issue if Teams owners depart. 

## Goal: 
Migrate [the current Teams-based SMO SharePoint](https://cityofaustin.sharepoint.com/sites/SmartMobilityOffice) to a [standalone SharePoint page](https://cityofaustin.sharepoint.com/sites/atd_SMO). This includes the SharePoint site, storage, and permissions. 

## Steps: 
- SMO has been notified of our plans to migrate this site and its content later in 2023 (Kirk S.; Kat A.; Rachel C.) 
- We need to check with CTM on the easiest route (Sharegate?) to perform the migration. 
- Since the exact method is unknown, this will require some scoping as well as collaboration from the division stakeholders.

**Comment by dianamartin** [comment]
@KaroEngstrom should we follow-up with Rachel?

**Comment by KaroEngstrom** [comment]
I'll follow up with Rachel this week. 
The Teams site is ok to link from the TPWHub in terms of neutral (non-ATD) name. I'll add the atdSMO to the list of items to rename so we have a standalone target site ready when the migration happens. We might also update the SP Site first and then migrate the document library content w/ the help of CTM.

**Comment by KaroEngstrom** [comment]
Mon 10/2/23 
- with the new fiscal year, SMO is done with their big project ending at the end of September
- Kat wrote in asking about what's next
- I scheduled a sync for Tue 10/10/23 🗓️ 
- Plan to use ShareGate #14067

**Comment by dianamartin** [comment]
# 10/31
🎉 Kat finished migration and rebuilt site. 
- Karo updated the permissions
- Rachel and Kat are informing the division
- Karo will redirect the old site to the new one

**Comment by KaroEngstrom** [comment]
Site redirected 10/31/23. Closing!
