### ISSUE TITLE
Add Link to SMD Data Tracker to the MMC Page in AMD Data Tracker

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#12836]
MMC is wanting to improve coordinator with SMD. Requesting to add a link to the MMC Page that directs them to the SMD Data Tracker
- Add the link to the SMD Data Tracker within the MMC Work Order Details

Also requesting accounts for all MMC Operator staff. Allyson will follow up with a full list.
- Allyson R
- Lance B
- Samir S

## Proposed Location of new button
- MMC Details page
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/7a0071fd-d237-45b5-a14a-a76fd32be941)

**Comment by dianamartin** [comment]
# 7/12 - Action Items
- SMD: to add new accounts
- DTS: to add new button to form

**Comment by ChristinaTremel** [comment]
Created SMD Data Tracker Accounts for: 

- Allyson Richey
- Lance Ballard
- Samir Slee
- Chris Sherrick
- Chris Reyes
- Kenny Moses
- William Howland

Let Allyson know:
> Accounts have been created all the MMC staff! 🙂 You should receive an email notification with the link for logging in.

**Comment by dianamartin** [comment]
@ChristinaTremel this is ready to review and let the stakeholder know it's complete

**Comment by ChristinaTremel** [comment]
Emailed stakeholders: 
> Hi everyone, 
> Accounts for all MMC staff have been created for the SMD Data Tracker!
> And MMC team - y'all now have a button on the SR details page to navigate to the signs work order form. 
> Have a great weekend! 🙂
