### ISSUE TITLE
ACH check return research

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12831]
### Description

Look into returned payments from CityBase in the amount $13,400 from the SA Spurs. We'll need to find out if that amount needs to get repaid

### Deliverable
* Determine if amount needs to get repaid. Talk with Eva
* Decide whether we need to delete old transaction invoice and create a new one

### Notes
- Amount $13,400 was paid on 3/30, and returned on 4/6. was logged as successful
- This is the only ACH return we've had

**Comment by dianamartin** [comment]
# 7/12
Posted on the CityBase Implementation teams channel for ATD and Eva S. (FSD), pointed out where I could see the ACH Returns. I poked around in there to figure out if I could gather any more information. Was able to find out that the ACH Return reason: 
>R10 - Customer Advises Originator is Not Known to Receiver and/or Originator is Not Authorized by Receiver to Debit Receiver’s Account

I followed up with Eva on
>I still have a question on whether or not I need to create a new invoice transaction for a new re-payment ?

She replied
>That would be your call and how it affects your source system.  I recommend that you loop in your finance people to give you guidance because they will be the ones who are affected.  Your finance team will have to manually post the reversal of funds in Advantage.  FSD IT will not post any negatives for any departments because reversal of monies require a manual workflow approval.

- Need to follow-up with Finance team on how we should proceed.

**Comment by dianamartin** [comment]
@patrickm02L I think we might need to reach out to SMO and Finance to see if this has been settled or how we should proceed. I'm afraid if I delete the record it won't show up on the financials and that the finance team would need that. It's possible I generate a new invoice on the back end and then have Nick point the customers to CityBase again, but after the customer has talked to their banking institution on giving CityBase the green light to receive funds. 

@chiaberry 
Eva confirmed that
>You will not receive a postback for ACH Returns nor for Credit Card Chargebacks because those transactions are not initiated at Citybase.  They are issued by the underlying merchant processor. 
and 

>The only postbacks that you will receive from Citybase are payment types:
>- successful
>- voided
>- refunded

**Comment by dianamartin** [comment]
# 8/14
>Diana,
Are we going to be able to reset the pay portal link? 

>Crystal/ Erin,
Is there anything that I could have done to prevent this beforehand or was solely on them? 
I would appreciate any feedback to keep this from happening again.
