### ISSUE TITLE
Mtg: AMANDA Solutions Discussion w/ DSD - 1/27/2020

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1283]
**Attendees:** John C, Tracy L, Terri P
**Date/Time/Location:** 1/27/2020 | 12:30pm | Conf. Call
    - 512-974-9300 357891#

**Comment by amenity** [comment]
@TracyLinder @johnclary - is this taken care of?

**Comment by TracyLinder** [comment]
Mtg was held on 1/31/2020 w/ Teri, Tracy, Deana.
