### ISSUE TITLE
[Bug] Vision Zero Viewer charts and map are not rendering

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12845]
## Description
The VZV is not showing select charts, metrics or map. The problem seems to be with the ETL. Investigate and fix the issue causing the Vision Zero Viewer to fail in rendering.

## Requirements
- Analyze the ETL process to identify any errors or issues that may be causing the failure to render
- Debug and fix any coding or configuration problems in the ETL pipeline
- Verify that the corrected ETL process successfully populates the VZV necessary for rendering

## Deliverables
- The Vision Zero Viewer should display metrics, charts, and map correctly once the issue is resolved

## Notes

![Screen Shot 2023-07-13 at 7.16.56 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/65ebac1f-0a77-48ed-aa2e-eadd69f07802)

![Screen Shot 2023-07-13 at 7.49.45 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/b5793609-c141-40a1-bc3a-fc995e39bb96)

**Comment by chiaberry** [comment]
@frankhereford  discovered the ETL failed due to invalid access key, keys were rotated last night and the airflow 1 values were not updated

ValueError: {'errors': [{'extensions': {'path': '$', 'code': 'access-denied'}, 'message': 'invalid x-hasura-admin-secret/x-hasura-access-key'}]}
