### ISSUE TITLE
Update CRIS downloader to use One Password API

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12849]
Scoping is in the title.

Edit: we have discussed this some in slack [here](https://austininnovation.slack.com/archives/CM9MK950S/p1689259786874409), and as part of this work, we should:

* make a new IAM user strictly for this one script, with its own key. ✅
* make a new 1PW API entry just for this one script with that API key in it. ✅
* update the script to pull from that (and other needed entries) so it no longer has reliance on the `.env` file.

Stretch goal - put this script back into airflow 2, but without a schedule. The CR3 downloader each day would login to airflow 2 and trigger the DAG with an argument that has the cookies string in it.

**Comment by mddilley** [comment]
@patrickm02L I bumped this up to a 3 since [we decided on some extra refactoring](https://austininnovation.slack.com/archives/CHZE6BC6L/p1689715614031839) for better long-term maintainability.

**Comment by mddilley** [comment]
Went for the stretch goal of turning this into an Airflow v2 DAG 🏆 but we ran into an issue with the cookie retrieved from CRIS not working across machines. 💥 See https://austininnovation.slack.com/archives/CHZE6BC6L/p1690293882087109. 

Going to open PRs to remove the DAG from Airflow and revert the VZ script to an earlier version of mine that has the 1PW retrieval built into the script.
