### ISSUE TITLE
Set up work session for Dash project planning

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#12858]
- [x] Schedule 2-hour meeting - Rebekka, Charlie, Andrew, Kate, Susanne, Peggy, Chia & Amenity (optional)
- [ ] Compile findings for group review and discussion

**Comment by amenity** [comment]
@katelunceford @amenity

**Comment by katelunceford** [comment]
Closing this because it's scheduled! Issue [#13530](https://github.com/cityofaustin/atd-data-tech/issues/13530) is for actual meeting

**Comment by katelunceford** [comment]
Closing this because it's scheduled! Issue [#13530](https://github.com/cityofaustin/atd-data-tech/issues/13530) is for actual meeting
