### ISSUE TITLE
UC Voided Payment didn't updated Bill Table Payment Status (LP) (NN)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#12867]
### Bill# 7891743 was paid, then the payment voided, but system didn't update the payment flag on the bill so staff can't move forward with applying a new payment. 

Incident # INC0307488
UC ROWID 13172229

UC Folder payment entries are currently not posting correctly to the Customer Account. Bill#7891743 requires a Backend adjustment to reverse a Voided payment and allow for a payment by Cashier , who received a payment over the phone by the customer. The original payment was entered as an On-line payment by the cashier (ONLY PAYMENT OPTION!!) and was then Voided by manager. The void did not take and there is a Billed Balance of zero. The Customer is in IMMEDIATE NEED of a receipt for the credit card payment and one cannot be generated due to the void and the inability of a payment to be applied via Cashier (visa payment).

**Comment by Nadin-Nader** [comment]
Spoke to Jaclyn and she is going to get with Samson to see if this is still an issue or what happened she believes this may be a user created issue. She will get more info and ask Samson the following:

[7:14 PM] Lozano, Jaclyn

I show that this fee was paid by the customer 7/10/23? But then there is a note that the fee was voided because the applicant paid again by the phone? I'm showing a balance of $2158?? 
In the notes on the ticket, sounds like an error by the cashier or only option is the bug. I'm not sure what happened. 
I think Samson might know. He may have told me to ignore the fee because the applicant paid the fee already.

**Comment by Nadin-Nader** [comment]
I asked Anthony T to reach out to Jaclyn and Vice Versa as this may be an issue they can resolve. if they cannot i asked Jaclyn to let me know.

Waiting on response

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT  here is what Jaclyn said when she tried to reach out to Anthony T:

> [5:13 PM] Lozano, Jaclyn
> Here is what he originally said: 
> 
> Hi Jaclyn, who performs the Utility Coordination Reviews? I have a folder where a payment was applied and then voided and I wanted to see whether the reviews will still take place where the folder shows a zero "Billed Balance" but, reflects a void? See below? We cannot generate a receipt for the customer and have referred this to IT to resolve. The customer is requesting a receipt and is asking whether the Review services will be performed? Please advise? thx
> 
> So first can the bug of not being able to produce a receipt be fixed? Maybe he wants voided fees/bills to just be deleted or the folder not show a balance. 
> 
> I really try and know as little as possible about these fees. He looks like he's out for the day. I'll try and reach out but I'm not in finance so I won't be able to explain it any better than he can. Maybe his supervisor. 

Can you look into a possible bug in printing the receipt......may not be a bug if others are currently printing them

**Comment by TracyLinder** [comment]
### Solutions to Try

1. Cancel existing bill, re-insert new fees, apply new payment. (if that doesn't work then # 2)
2. Priya write script to update the bill table payment flag from yes to no? 

@Nadin-Nader please ask Jaclyn to try # 1

**Comment by Nadin-Nader** [comment]
I have let Anthony and Jaclyn know what to try via TEAMS chat and asked them to let me know the outcome. Waiting on response from either

**Comment by Nadin-Nader** [comment]
Closing as i have not heard back from the UC Team and the only solutions were to either Cancel existing bill, re-insert new fees, apply new payment. I relayed this and didnt get a response back. Or a script will need to be written in order to change/fix the bill then sent to the DBA team to run.
