### ISSUE TITLE
Meeting: ROW Updates & Backlog Review 2/23/2020

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1286]
### Objective 
Meet with our stakeholders in the Right of Way division to update them on current work, and to review their backlog. 

### Participants
Tracy L, John C, Ryan W, Ryan M, Paloma A, Mani K

### Agenda
TBD

------
- [x] Schedule meeting
- [ ] Meet and take notes in agenda doc
- [ ] Create resulting issues

**Comment by KyleErich** [comment]
Closing this, as it is old and we have since established a better system for backlog review.
