### ISSUE TITLE
Create slides for Dash to add to executive ppt proposal for TPWstat

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#12865]
- [ ] Document proposed framework
- [ ] Present to executive team week of 7/24

[2023.07.13 TPWstat Project Plan](https://cityofaustin.sharepoint.com/:x:/r/sites/TPWReorg/Shared%20Documents/General/PERFORMANCE%20MANAGEMENT%20PROGRAM/TPWstat%20Development/2023.07.13%20TPWstat%20Project%20Plan.xlsx?d=wb0d388e2651f40f69dd97c24b90c1f3e&csf=1&web=1&e=LiTVdb)

**Comment by amenity** [comment]
@katelunceford - do we still need this?

**Comment by katelunceford** [comment]
@amenity yes, during yesterday's TPWstat meeting we discussed adding content for Dash to Paige's next executive proposal. I thought it'd be good to get Dash in front of executives. Plus we were a little sad that Dash wasn't mentioned more in the TPWstat pitch to Richard - this is our opportunity to add it in for the next round.

**Comment by amenity** [comment]
@katelunceford - sorry! I could have gleaned that if I'd paid attention to the dates 🤦🏻‍♀️

**Comment by katelunceford** [comment]
@amenity no worries, I definitely could've added more to this issue (and plan to)!
