### ISSUE TITLE
Add headshot to DTS Webpage - Vaishnav Y.

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#12875]
I added my headshot to the folder

**Comment by Vaishnav1397** [comment]
@chiaberry The Job Title: IT Support Analyst and i think so the Headshot name is Vaishnav1397

**Comment by dianamartin** [comment]
@Vaishnav1397 I don't see the headshot either, you might want to check on it

**Comment by Vaishnav1397** [comment]
The picture has now been uploaded.
