### ISSUE TITLE
Map Request - Church of Scientology Austin Grand Opening

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#12884]
I will need a site map for the Church of Scientology Grand Opening on August 5th. I am in a holding pattern to get approval on updates to the TCP’s and Street Closure documents. I hope to have updates by Monday July 10th. I have attached the drafts of what I currently have. Will you be able to have a map created later this month?

**Comment by Colemonj** [comment]
Date of the event was changed to Aug. 25th, I updated the dates in the attribute table and in the callouts of the static map.
