### ISSUE TITLE
UAT for Temporary Valet Permit Fee update

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1291]
- This was Magic HD #  HD#1988890, now it's Service Now RITM0021262
- Currently undergoing UAT and waiting approval before promoting from TEST to PROD.

**Comment by SurbhiBakshi** [comment]
@johnclary , @amenity - just received word from George S that CTM is waiting for UAT on this issue for push to PROD, going to schedule UAT.

**Comment by SurbhiBakshi** [comment]
- [ ] Paloma will send me a list of staff who would do UAT. 
- [ ] I will schedule UAT for next week.

**Comment by SurbhiBakshi** [comment]
UAT for this issue was successful for Amanda Test. Kim would like to see that the fields needed to calculate the fees be made mandatory in Portal. Going to ask that this work be deployed to Prod, and will send in a seperate ticket to make the Portal fields mandatory.

**Comment by SurbhiBakshi** [comment]
REQ0046228

**Comment by SurbhiBakshi** [comment]
Your Request REQ0046228 has been opened. If you are the Requested For, you can view status from My Open Requests on the COA ServiceNow Portal
 
Submitted By: George S
Requested For: Surbhi B
Item: Ad Hoc Request Form
 
DEVOPS - Promote from TEST to PROD - RW Valet Parking Fee - commit ba7be95a8667
Description: Change Management team, please promote the following commit (which is a squashed commit) from the TEST branch to PROD:
 
ba7be95a8667
 
It comes from two commits originally on the TEAM_MONGOOSE branch (3a4a596debdd and 153458317bf3)

**Comment by SurbhiBakshi** [comment]
Your Request REQ0046226 has been closed.
 
Submitted By: George S
Requested For: Surbhi B
Item: Ad Hoc Request Form
 
DEVOPS - Promote to PROD - RW Temporary Valet Permit Fee - commits 4a2f09b34787 and 8388b85224bf
Description: Change Management Team, please promote the following commits from the AMANDA_TEAM_MONGOOSE branch to PROD in this order:
 
4a2f09b34787
8388b85224bf
