### ISSUE TITLE
Move away from `devicemapper` as underlying storage provider in atd-data03's docker service

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#12924]
Please see the recurring issue here: https://github.com/cityofaustin/atd-data-tech/issues/11593.

We need to move to our docker installation off the storage provider `devicemapper` onto `overlay2` or other provider. 

I'm not sure how hard this is going to be and save our data, but if we're willing to take a fresh-start with our airflow install and loose state (not DAGs, just state of the DB), I imagine this will become a very easy task.

On that note, I'd like to surface this as an issue with potentially high priority, before we accumulate state in our docker install that we really care about. I would like to break sprint and deal with this and get the underlying CTM v. Docker problem on data03 squared up.

**Comment by johnclary** [comment]
These [migration docs](https://docs.docker.com/storage/storagedriver/overlayfs-driver/) may be helpful.

**Comment by frankhereford** [comment]
We will visit this issue on Wednesday next for assignment. We discussed as a group that we are comfortable nuking the state stored in the docker's storage system, but we also agreed that we may reevaluate that choice on Wednesday. 

Our primary goal here is to get this wrapped up before the next CTM update.

Thanks!

**Comment by frankhereford** [comment]
I created a test fixture for this this morning on a throw-away EC2 machine. I was able to upgrade a postgres database created on devicemapper to overlay2 using the instructions that John linked above. Thank you for those. I am going to seek consensus from the dev team today in our dev sync to do this work today at 5PM.

**Comment by frankhereford** [comment]
This worked out after ironing out another wrinkle. Please see this slack thread: https://austininnovation.slack.com/archives/CHZE6BC6L/p1691070699411729

Short story:
> Turns out that the /var XFS filesystem wasn’t created with d_type support which is required.
> I’m spinning back up airflow on devicemapper and am going to allocate a new logical volume using the lvm2 system. I’m putting ext4 on there which I will mount at /var/lib/docker.
> From there, I’ll move the old contents of our docker directory to that new volume (excluding the devicemapper sparse storage file) and it should spin up.
> This is all a non-destructive operation, so it’s not risky, which is helpful.

> This all worked out fine, and we’ve been running on `overlay2` backed docker for about an hour now. When I made this new volume, I gave it 128G of space, so it’s got plenty of room for activities. I’m going to restart airflow one more time to get it detached from my terminal, but everything seems to be spinning along. No data loss either, which is nice.
