### ISSUE TITLE
UAT for New Fee Procedure - Valet Parking Space Fee

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1292]
Transfer from Magic HD#1988886 - Valet Parking Space Fee - New fee proc awaiting UAT

**Comment by SurbhiBakshi** [comment]
@johnclary , @amenity - just received word from George S that CTM is waiting for UAT on this issue for push to PROD, going to schedule UAT.

**Comment by SurbhiBakshi** [comment]
- [ ] Paloma will send me a list of staff who would do UAT. 
- [ ] I will schedule UAT for next week.

**Comment by amenity** [comment]
Scheduled for Sprint 22.

**Comment by SurbhiBakshi** [comment]
@johnclary @amenity this is not an LIT item, we need a UAT from ROW. Had to reschedule the UAT today due to scheduling conflicts.

**Comment by SurbhiBakshi** [comment]
- Testing during UAT was successful.
- This work will be deployed to Prod.

**Comment by SurbhiBakshi** [comment]
REQ0046228

**Comment by SurbhiBakshi** [comment]
Your Request REQ0046228 has been opened. If you are the Requested For, you can view status from My Open Requests on the COA ServiceNow Portal
 
Submitted By: George S
Requested For: Surbhi B
Item: Ad Hoc Request Form
 
DEVOPS - Promote from TEST to PROD - RW Valet Parking Fee - commit ba7be95a8667
Description: Change Management team, please promote the following commit (which is a squashed commit) from the TEST branch to PROD:
 
ba7be95a8667
 
It comes from two commits originally on the TEAM_MONGOOSE branch (3a4a596debdd and 153458317bf3)

**Comment by SurbhiBakshi** [comment]
Your Request REQ0046228 has been closed.
 
Submitted By: George S
Requested For: Surbhi B
Item: Ad Hoc Request Form
 
DEVOPS - Promote from TEST to PROD - RW Valet Parking Fee - commit ba7be95a8667
Description: Change Management team, please promote the following commit (which is a squashed commit) from the TEST branch to PROD:
 
ba7be95a8667
 
It comes from two commits originally on the TEAM_MONGOOSE branch (3a4a596debdd and 153458317bf3)
