### ISSUE TITLE
[Design] Improve UI for Crash Pages

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12938]
## Notes

**Comment by patrickm02L** [comment]
## Current layout
![rsz_4screencapture-visionzero-austin-gov-editor-2022-12-29-14_09_07.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/91efd7fd-f593-4218-b9cb-72d32eb3b3a8)

**Comment by johnclary** [comment]
Now that we have the [ACC designs](https://github.com/cityofaustin/atd-data-tech/issues/17630) I will go ahead and close this.
