### ISSUE TITLE
Compile attendee information

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#12932]
@NCruzCruz Please use the attached file to come make potential attendee lists for the workshops listed below. The file is a copy downloaded from Sharepoint so feel free to add new tabs in the file for each workshop.

- Use Column B to filter for the divisions in each workshop (don't use column A, I think the labels are outdated)
- Use Column R and make sure you are only counting Executives, Managers, and Supervisors for the initial lists
- You can include positions listed as Vacant for now, many of them may have been filled since this was last updated so we can use them in the estimate
-  Some of the division names have changed in the last couple months so if there's any you're having trouble finding let me know.

[ALL TPW EMPLOYEES.xlsx](https://docs.google.com/spreadsheets/d/1ZsSlHuVB87v-brHRIksToJApuAuLq_q_/edit#gid=349415421)

**Workshop 1 divisions:** Infrastructure Operations, District Maintenance, Pavement Operations, Utilities and Structures, Urban Forestry, Vision Zero, Signs and Markings, Arterial Management, Office of Special Events, Right of Way

**Workshop 2 divisions:** Active Transportation, Capital Services/Project Delivery, Transportation Engineering, Office of the City Engineer, Sidewalks, Community Services, Logistics

**Workshop 3 divisions:** Strategic Projects, Strategic Communications & Outreach, Smart Mobility/TDM, Transportation Development Services, Land Development Engineering, Long Range Planning, Program and Project Development

**Workshop 4 divisions:** Finance, Human Resources, Data & Technology Services, Office of Performance Management, Parking Enterprise, Public Information Office, Administration, Legislative Affairs

**Comment by NCruzCruz** [comment]
Hello! I finished compiling the workshops attendees lists.
Workshop 1: 54 attendees
Workshop 2: 27 attendees 
Workshop 3: 17 attendees 
Workshop 4: 32 attendees

**I attached the lists here:** 
[TPW Transition Workshop Attendance List.xlsx](https://github.com/cityofaustin/atd-data-tech/files/12111534/TPW.Transition.Workshop.Attendance.List.xlsx)

Let me know if you need anything else!
