### ISSUE TITLE
CIC Fellows Final Presentation

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#12940]
## Description

Madison & Rachel will present their fellowship work to the team on  **Thursday, August 17th.** 

- [x] Madison presentation complete
- [x] Rachel presentation complete

## Notes
- See Issue #9828 for example of final presentations

**Comment by madifan** [comment]
Madison's [offboarding folder](https://drive.google.com/drive/folders/1pSSrBrbszNviFfAe8VBocJum5UaBgHUU?usp=drive_link)

**Comment by RR216** [comment]
CIC'23 Software Engineering Fellow Rachel W.'s [presentation slide](https://docs.google.com/presentation/d/1SGvPNupAue-f9XNUZe0W9LrGIV36xKtmvW2XAgzUArs/edit?usp=sharing)

**Comment by patrickm02L** [comment]
Good to go!
