### ISSUE TITLE
Create Read-Only Application for Viewing LATM Data

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#12943]
Create read-only web application with the data included below:
https://austin.maps.arcgis.com/home/item.html?id=37cda4749d264a8ea9676e2965018a02

**Features to Add:**
- [ ] Filtering Widget

**Comment by Colemonj** [comment]
Created read only web application with built-in filtering functionality. 

Link to web app:

https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=ca2826a8182b4283888e038b41c31c6d
