### ISSUE TITLE
[Spike] Review "Project" pages and explore design possibilities

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#12945]
## Description

As a user visiting our "Project" pages, I want the content from atd-data-tech Github issues to be presented in a more legible and visually compelling manner. 

Our "Project" pages [render content from `atd-data-tech` Github issues](https://atd-dts.gitbook.io/wiki/product-ops/dts-website) using the Github and Zenhub APIs. The integration works beautifully, and in the past year, PMs have improved the content and adopted a more reliable cadence for updates. 

## Objective

The main goal is to elevate the "Project" pages' visual appeal and make the content more easily digestible for users. We aim to achieve this by implementing some of the following improvements:

- Refine font styles, especially relative heading sizes. [This WIP issue](https://github.com/cityofaustin/atd-data-tech/assets/1463708/e38800a1-215e-43b7-9d12-46fbc28df180) shows how large and close in size the various headings are. 
- Do we need all those tabs? (And should they be tabs?) Maybe show the image and prioritization chart in a sidebar on the right with ➕ to view in a large modal...
- Show the project team (using photos from the "About" page). We’d need to modify our current practice of usually only having the PM assigned to the issue index and instead adding everyone involved.

![screencapture-austinmobility-io-projects-4937-2023-07-19-17_11_34](https://github.com/cityofaustin/atd-data-tech/assets/1463708/c0f9748a-1605-4f6b-9802-48b3b64718d9)

## Deliverables
- List of proposed updates to make "Project" pages more legible
- Lightweight wireframes of proposed solutions
- Get feedback from team to ensure that changes resonate with their preferences and needs, do user testing or shadowing as necessary

## Note
- A subset of these design changes will also apply to "Product" pages

**Comment by amenity** [comment]
@TracyLinder @katelunceford @ChristinaTremel @patrickm02L @maccallump - feel free to add/edit ideas for Madison to explore here.

**Comment by patrickm02L** [comment]
Made a few updates to the layout of the Issue and added objective and deliverables section. 
I think this Spike could be a 5

**Comment by patrickm02L** [comment]
Synced with @madifan to go over use cases, context, and potential ways to approach the spike

Update the DTS website Issue #4199
Updated Project Pages #10773

**Comment by madifan** [comment]
Figma [link](https://www.figma.com/file/r6pqXyeOZsZtOq4mF9o2BG/DTS-Project-Details-Page-Wireframes?type=design&node-id=0%3A1&mode=design&t=2riMXncKKul4bhsV-1) to prototypes
Google docs [link](https://docs.google.com/document/d/1jRFRehE2tFyzPDIQ98d7op3WIcxCJOYt0BJbUihHpC0/edit?usp=sharing) to list of design and content suggestions

**Comment by madifan** [comment]
@johnclary @amenity  Hi John and Amenity, would you two be able to leave some feedback on the designs when you're able? You can find the list of design suggestions organized by tab on the linked google doc and see the design on Figma. Thank you!

**Comment by johnclary** [comment]
@madifan i left my comments on the Figma prototypes before i realized i should have used the google doc. sorry about that! i did leave a few comments in the doc as well. i love your work!

**Comment by madifan** [comment]
Updated Figma design based on feedback from John
# What changed
1. removed dividers in sidebar
2. changed formatting for evaluations tab: changed the headers of each table for effort and value into "effort" and "value", added indent to each factor to separate from the total score, remove bolding of "total"
![Evaluation.png](https://images.zenhubusercontent.com/648c89820b59c091d36c8cc0/36c5724f-f9b1-4f55-a4a9-89753084a494)

**Comment by madifan** [comment]
# Final designs
Description tab
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaElWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--902b5af8bb0c3d902d5acab0f03693238367ce3a/Description.png)
Evaluations Tab
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFFWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--317b230ee50604ed691753d557090a12ad435997/Evaluation.png)
Activity Tab
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEVWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c052696fbc6ff26e90f6a2a211f809d41bdaa077/Activity.png)
Issues tab
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFlWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--18aff068e99ebc152196ac2afc6248ac0f717edd/Issues.png)

**Comment by madifan** [comment]
# Final designs
Description tab
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaElWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--902b5af8bb0c3d902d5acab0f03693238367ce3a/Description.png)
Evaluations Tab
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFFWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--317b230ee50604ed691753d557090a12ad435997/Evaluation.png)
Activity Tab
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEVWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c052696fbc6ff26e90f6a2a211f809d41bdaa077/Activity.png)
Issues tab
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFlWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--18aff068e99ebc152196ac2afc6248ac0f717edd/Issues.png)

**Comment by madifan** [comment]
Closed [#12945](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/gh/cityofaustin/atd-data-tech/12945) as finished
