### ISSUE TITLE
IT Support: map the PWD OCE

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#12973]
## Device & User Information (no last names)
Veena
## What's the problem?
"Matt, I need to map the PWD OCE waiver folder on Outlook. The same has added me to this account. Could you help me with this please?
Thanks,
Veena"

## What did you do to resolve the issue

related to this issue #12966 (this is the original issue that was submitted by the user, it's a DUP)

**Comment by Vaishnav1397** [comment]
Reached the user and see that she already has the account folder added but couldn't be able to access it as it says the account to Microsoft exchange has been failed.  Raised a Ticket to CTM

**Comment by Vaishnav1397** [comment]
Troubleshooted few steps by the CTM team and the team has forwarded the ticket and been assigned Micheal is looking into it

**Comment by Matthew-M-TPW** [comment]
I attempted to reach the user she did not answer

**Comment by Vaishnav1397** [comment]
Reached out to the user through teams and remotely made the required setting profile updates in outlook. Removed and added back the OCE Folder, made advance settings and restarted.
