### ISSUE TITLE
Digital Interview Packet Meeting with HR

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1297]
Schedule 1/30 at Barton Oaks

**Comment by dianamartin** [comment]
We received our DTS Google Chromebook. I started playing with it to see how we can use it for the HR Digital Interview packet solution.

## Things I learned
- Guest Mode: doesn't allow you to save book marks
  - Users that want to save bookmarks have to log in/create a Google Account
  - You can create one using your City email address [Using Google as a city employee guide](https://atd-data-and-technology-services.gitbook.io/austin-transportation-data-and-technology-services/using-google-as-a-city-employee)

## Testing
- When I logged in as my city google account, I was able to save the book mark to the SharePoint ATD Interviews documents page.
- I tested using the Guest mode, I had to go to my city email: outlook.office365.com and log in. From there I clicked the waffle and go to the SharePoint page for ATD Interviews>document folder>OneNote file. _(Several more clicks, but do-able)_

## Recommendations
- Have HR staff create city google account so they can log into their hardware _(future Google Chromebook)_
- Create bookmarks for specific interview panel OneNotes
- If purchasing a Google Chromebook, invest in the touch screen version so you can capture interview panel participant signatures easier.
- have USB mice for users

**Comment by amenity** [comment]
1/30/2020
_Adan, Diana, Jennifer, Diana_

### Panelist workflow
Diana demoed our recommended workflow process. Discussion points:
- If everyone is logged in as Jennifer, panelists will have access to HR everything, which is concerning. 
- Near future we will likely want panelists to take notes digitally during the interview, so they should be signed in as themselves. 
- Wireless connectivity is critical (we saw lags when demoing from the Chromebook) will be need to get 3 Mifi hot spots.
- The tablet OneNote experience is really nice, but we want hardware that can be an end-to-end solution.  

**Modified recommendation** 
   - Panelists are notified before the interview that they need to be prepared to sign in with their ADFS creds. 
   - HR emails everyone a link to the specific OneNote (or folder, or PDF) in Sharepoint
   - HR staff person signs in to Chromebooks using their [City Google account] (https://github.com/cityofaustin/atd-data-tech/wiki/Using-Google-as-a-City-employee) 
   - When panelists arrive, sign confidentiality agreement on tablet?*
   - Panelists can log in to their O365 email and click link to materials
  - Some panelists might not be comfortable typing notes, will probably always have to have a paper option available and scan it afterward

### HR preparation workflow
Diana demoed recommended preparation workflow. Discussion points:
- Issues syncing OneNote on Jennifer's laptop...  possibly from a Sharepoint permissions issue 
- Have to embed each document individually, but these will be different for each interview; will take a lot of time to replace
- Skipping OneNote and just using Sharepoint is easier, can just drag over entire folder. BUT not as user-friendly for panelists.
- Experimented using AcrobatPro: Right click on the main folder in Windows and create a PDF. Automatically creates table of contents. This might be easier to navigate than Sharepoint?

### Next steps:
- Adan will order Chromebooks with touch screen
- Adan and Jennifer will try out OneNote, Sharepoint, and Acrobat methods
- Will try out ☝️methods with different interviews. DTS (Diana or Amenity) can come to the beginning or end of the interview to get everyone set up or collect user feedback. 
- @Diana look into digital signature options for confidentiality agreement

### Notes about the confidentiality agreement. 
Typically we get PIRs for the entire Hiring Package, and the Confidentiality Forms are part of the package. Confidentiality Forms do require a signature. The other form that has a signature line currently, the Panel Member Score Sheet, is actually not required to have it by HRD.
