### ISSUE TITLE
IT Support: Assistance with setting up computer

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#12985]
## What's the problem?
Good afternoon Matthew, my name is  Ceballo. L and I just attained a Supervisor position at . I work for Krik B and was told that you would come and fix my laptop to add the necessary apps that I need for the Supervisor position, if you have any question please call me at , thank you

**Comment by Vaishnav1397** [comment]
Computer setup has been completed and the system is working pretty well. Display drivers has been downloaded to fix the display issue and docking internet ports been changed and everything works fine.
