### ISSUE TITLE
Update Maximo display rule for DTS New Service Request form

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12983]
Maximo Team
DTS

They would like to add similar to the "AMANDA" selection to show the various types on the form
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/8a8d4cb8-103f-49a4-89d3-dea7a0605ead)

**Comment by dianamartin** [comment]
# 7/24
- [x] Added a new field `Maximo confirmation statement`
- [x] Added display rule to show/hide when Application "Maximo" was chosen

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/dd5bff2c-6dd1-42f3-9b1e-20ed0b479181)

@YakshDipa @adry-martinez @ReneVarg25 - I've added this new feature in the DTS Service Request, let me know if this works as you expect.

**Comment by adry-martinez** [comment]
@dianamartin everything looks great, is it possible that we could add **EzMaxMobile** to the application drop-down and remove the statement in **_Troubleshooting_** "_...and if is MAXIMO desktop or with EzMaxMobile_"?

**Comment by dianamartin** [comment]
@adry-martinez adding "EzMaxMobile" isn't easy as it needs to be associated to a corresponding label. we'd want to include language for the user to add the keyword "EzMaxMobile".
