### ISSUE TITLE
Build out Vacancy Report page on TPW Interview application

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#12988]
Jennifer W. 
HR

Talked to Jennifer on Wed 7/19 about TPW Employee forecasting so that the Tech Services team could better order hardware for new employees onboarding to TPW. 

- **Short term solution:** Jennifer and team would send Scott and email when final offer letter has been accepted
- **Long term solution:** Build out Vacancy Report

We had prototyped a "Manage PCN" page in the TPW Interview application

**Comment by dianamartin** [comment]
# 7/25
- [x] Added new fields to `pcn_management` object, that matched the TPW Vacancy Report
- [x] Added new columns to "Manage PCN" page/table
- [x] Renamed page to "Vacancy Report"
- [x] Created new page "Division Reports" to match "Division Data" tab on spreadsheet
- [x] Added report widgets to summarize record data

**Comment by dianamartin** [comment]
@ChristinaTremel worked on this for HR as this might be a higher priority than the Digital Interview module

**Comment by dianamartin** [comment]
# 8/21
Syncing with Jennifer, she said there may be changes to the Vacancy Report criteria.

**Comment by dianamartin** [comment]
# 8/21
New Feature
Tracking Dates
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/26ab3dad-1f8c-40f9-97c3-0667626eab7d)

**Comment by dianamartin** [comment]
@ChristinaTremel we're gonna need to sync on this, I'll fill you in tomorrow.

**Comment by dianamartin** [comment]
# 8/22
Jennifer sent a list of milestone choices:

- [ ] Reclassification Request to TPW HR Date
- [ ] Reclassification Request to HRD Date
- [ ] Reclassification Approved Date
- [ ] Posting Open Date
- [ ] Posting Close Date
- [ ] Candidate Screening Matrix (CSM) Distributed Date
- [ ] CSM Return Date
- [ ] Interview Schedule Date
- [ ] Top Candidate Selection Summary Distributed Date
- [ ] Zone Information Provided to Manager Date
- [ ] Reference Distributed Date
- [ ] Reference Return Date
- [ ] File Review Distribution Date
- [ ] File Review Return Date
- [ ] Criminal Background Investigation (CBI) Distribution Date to Candidate
- [ ] CBI Return Date
- [ ] Commercial Driver License (CDL) Testing Distribution Date to Candidate
- [ ] CDL Testing Return Date
- [ ] Motor Vehicle Review Date
- [ ] Final Offer Made to Candidate
- [ ] Effective Start Date of Hire
- [ ] New Employee Name - I think this is just a field to add to the object, bc it's not a date..

Milestones that we will report on Weekly: (these need to roll-up into the parent object)
1.	Reclassification Request to TPW Date
2.	Posting Open Date
3.	Interview Schedule Date
4.	Effective Start Date

**Comment by dianamartin** [comment]
# 8/23
- Updated the "Milestone Categories"
>Do we need to add milestone for "Sending posting language to HM"?

**Comment by dianamartin** [comment]
# 8/25
- [x] Built out "My Job Vacancies | Hiring Manager" tables
- [x] Built out "My Job Vacancies | Manager/Supervisor" tables

**Comment by ChristinaTremel** [comment]
## 8/30 Meeting to Review Vacancy Report

**Attendees**: Jennifer, Tina, Diana, and Christina

- Vacancy Views for everyone to see:
   - Vacancy Report | HR: for HR and Assistant Directors to view
   - My Job Vacancies: can only see if you're the Hiring Manager or Manager/Supervisor
   - Vacancy Report | All: high level view of vacancies without much detail (Rebrand the Vacancy Report | AD/DD)
- Enhancement Requests: 
   - Can we bring in the filled PCNs as well? CMO regularly asks for:
     - Would need to bring in the Banner data from the HR Knack App
     - Total count of vacancies and percentage of vacancies through out TPW
     - Percent of vacancies per division 
   - Add Milestone to tracking when positions are being transferred. This will allow HR to run a report on all the positions that have been transferred.
- Something in Banner that might be able to help us narrow down the actual division: Location Code (use this for timekeeping purposes but also useful for finding positions that need to be moved). Location code is only tied to timekeeping.
   - Need `Location Codes` added to the banner feed
   - ATD has always used `Budgeted Title` but there's another field called `Job Title`. Already have the Job Title on the feed so added it to the employee list, but still would like `Budgeted Title` added to the banner feed.

**Comment by dianamartin** [comment]
# 9/5
- [x] Renamed "Vacancy Report AD/DD" to "Vacancy Report | All Access"
- [x] Updated the page names and page titles
- [x] Re-created new table because previous one was only showing per logged in account
  - [x] removed any sensitive fields for HR only

**Comment by ChristinaTremel** [comment]
## 10/4 Check-In Notes

### Adding Milestones
- Add `Name` to the milestones table

### Vacancy Management
- Add Legacy PWD staff

### Closed Backfill
- Jennifer said we don't need to do a backfill because it's the beginning of the new FY

**Comment by dianamartin** [comment]
# 10/4
- [x] Added new field "Display Name", shows "Category" and "Milestone Category"

# 10/5
- [ ] Add Legacy PWD staff
- [ ]

**Comment by dianamartin** [comment]
# 10/27
We had HR Sprint Review with stakeholders on 10/25 and we went over this page with HR. They said they'd get back to us on feedback bc they were going to show the other HR staff the page and get their reactions.

**Comment by dianamartin** [comment]
## 11/27
Had a sync with Tina, Alex, Christina, & Diana
- [x] Update filters on `Vacancy Report | HR`
- [x] Added Active filter on `Vacancy Report | HR`
- [x] Moved "Fund" field to the end of the table, `Vacancy Report | HR`
- [x] Created CPO Report page 
- [x] Created `Vacancy Report | Tech. Services` for Scott

**Comment by dianamartin** [comment]
# 12/6
Tina emailed on 12/5
>Hi Diana and Christina,
Attached is the report format that we will be sending to Anthony going forward for his report to the CMO. Can we create this report in the KNACK Vacancy Report area to include just these fields/information? It would make it a lot easier for me every Monday morning to be able to pull a report with just this pertinent information for Anthony and not have to manipulate and remove unnecessary columns/info.

>Please let me know if you would like to discuss.

>Many thanks again to both of you for all your help with this dashboard; can’t say thanks enough 😊

## 12/5
I reviewed the spreadsheet she provided me and I updated the "CPO Report"
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/f25c585a-e4b2-4664-844f-bf61182c62ad)

I messaged Tina back
>This is the [CMO Report](https://atd.knack.com/tpw-hire#vacancy-report-hr/cmo-report/?view_121_filters=%5B%5D) now. 
>- I sorted it by Asst. Director, but I think there are some records that don't have any ADs yet
>- and I just added the "Export" button

Tina replied
>Thanks; I'll give it a try
