### ISSUE TITLE
Define Repo Directory Structure

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#13]
Proposing that all repos are named `transportation-<my-app-name>` and follow the following file structure:
```
transporation-knack-app 
+-- README.md
+-- code
|   - knack.js
|   - knack.css
+-- docs
|   - README.md
+-- media
|   - screenshot.jpg
```

**Comment by johnclary** [comment]
@dianamartin @amenity any thoughts? can we close this out?

**Comment by dianamartin** [comment]
@johnclary @amenity I think this is a pretty good start to the Knack directory structure. Let's close it.

**Comment by amenity** [comment]
@johnclary @dianamartin - looks good, but I was wondering about the "builder" docs that Diana puts together for her own future reference, e.g. "This field is used to populate the such and such column on the something page."

**Comment by dianamartin** [comment]
@amenity @johnclary That's what the "ReadMe.md" in the doc folder is for, no?

**Comment by amenity** [comment]
Oh - I thought that was for the end user docs. 🙃 

I was thinking "User docs" and a "Builder docs" or "User guide" and "Builder docs"...

**Comment by amenity** [comment]
But if they're the same thing then obviously one directory is great.

**Comment by johnclary** [comment]
Right, those would be separate from markdown files. E.g. a configuration-notes.md like you suggest. I also wonder what if any of these docs should be managed in a wiki. The wiki would make the user docs easier to navigate, perhaps?

**Comment by dianamartin** [comment]
I think being in a wiki would be easier to create and manage moving forward rather than a .md file.

**Comment by amenity** [comment]
Oh yeah, totally. Docs in the wiki. So then:
atd-knack-app 
+-- README.md
+-- code
|   - knack.js
|   - knack.css
+-- media
|   - screenshot.jpg
```
And the Wiki has two top-level menu items, one for user guides and one for configuration documents? (Though I assume there are times when the later isn't required.)

**Comment by johnclary** [comment]
ship it!


On Apr 26, 2019, at 17:29, Amenity Applewhite <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh yeah, totally. Docs in the wiki. So then:
atd-knack-app
+-- README.md
+-- code
| - knack.js
| - knack.css
+-- media
| - screenshot.jpg

And the Wiki has two top-level menu items, one for user guides and one for configuration documents? (Though I assume there are times when the later isn't required.)
