### ISSUE TITLE
Duplicate initial month of VZA shifts for second round of scheduling

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1300]
Until we implement [the ability for a Scheduler to replicate teams and assignments ](#1295) we can save Lewis' time by duplicating the shifts he provided for 1/27-2/23 to 2/24-3/22.

**Comment by SurbhiBakshi** [comment]
Lewis made some change and wants to copy over the changed schedule to the next few weeks.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/f9e9e4f9-2a62-40b1-aafa-136ddad5bdc6)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/730c5b43-4986-43ae-ad2e-9eb0dfd774f2)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/73ccc0e4-b05b-4408-a122-63b1a8c700b8)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6bc7773b-a7bf-4031-82b2-45b99a7194b7)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/30bf3569-4128-4960-82c2-e6f5019f987b)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6ab18941-5c85-47e0-9452-60fc872ab062)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5b66d03c-389c-42ee-8f34-00c6872a101e)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/cde53125-f07e-4d39-abe1-b240b3367fb1)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/c39d7701-a288-4488-a825-b7bd333a6d9c)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/ce6fd955-3ea8-479d-9f58-3a946d42360c)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6267715d-615c-414c-98ba-f4e8473124fb)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/db0f88c1-efdf-4b3c-a63d-7a33019092f5)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6b0dbe2e-edd2-474e-9ad3-2feeb9f2dfde)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/a5212394-890e-4818-89e9-89c47f231769)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/51f7481b-6fc4-457f-83a2-9208e8311c64)

**Comment by amenity** [comment]
@SurbhiBakshi  - are we good on this?

**Comment by SurbhiBakshi** [comment]
@amenity going to close this issue, since I have not heard from Lewis after I completed work on Tuesday.

**Comment by amenity** [comment]
@SurbhiBakshi 👍🙏
