### ISSUE TITLE
Identify desired refinements VZA locations data model

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1302]
There should be one `locations` object with the following fields:
- Knack ID (auto increment)
- Feature ID (match AGOL; see #1301)
- Name
- Display Name
- Type (Street Segment, Intersection, School)
- Status (Active/Inactive)
- APD Sector 
- Council District

**Comment by amenity** [comment]
@SurbhiBakshi @johnclary @dianamartin I copied these fields from the whiteboard, but [reviewing the location list Lewis initially sent over](https://docs.google.com/spreadsheets/d/1TkYVtSxcL-zwGehHbVzSK6qhHZWCVItfr-f8tZMQc90/edit#gid=672449507), I see that we need to either add a "Limits" field or somehow accommodate that data in another way. I'll defer to y'all on what makes sense.

**Comment by johnclary** [comment]
I think that's fine. So the `Name` field should be either:
- the name of the school (if type is  school)
- the name of the primary street (if type is street segment)
- the name of Primary and Cross St (if type is intersection)

Would like to see some cleanup and consistency in naming. E.g:
- Dobie Middle > Dobie Middle School
- Rundberg and Aberdeen > Rundberg Ln and Aberdeen Rd

**Comment by SurbhiBakshi** [comment]
@johnclary @amenity Lewis specifies streets with schools as well, so would need to add that to the school locations. 
Would need to clarify if he specifies streets near schools as a location reference or as streets that need VZ enforcement.

**Comment by amenity** [comment]
Still some back and forth with Lewis about the ramifications of a single Locations object on his Add Assignment UI. This would remove his ability to filter by Sector and Location Type as he creates assignments, which he likes.

**Comment by amenity** [comment]
Lewis said it's fine to move forward with the predictive-text drop down for his assignments, so that means we're good to go combining locations into a single object. 

[Here's my stab at specifics and trying it out with some data].(https://docs.google.com/spreadsheets/d/11HuTKGz5Lc5v3KVZIKKphZk65XcQJOYaG9tC379133Q/edit#gid=0). 

I really hope that we can provide a URL to a link for each location as it's much easier to see on a map than read.

**Comment by SurbhiBakshi** [comment]
per Lewis's email, he needs a day or two to add new locations, waiting for him to do that before I start on creating the Knack object and associated GIS features.

**Comment by amenity** [comment]
Let's discuss this in the Sprint Review and hopefully get sign-off on the new approach.

**Comment by amenity** [comment]
Lewis confirmed that he is fine with the predictive text option for choosing locations from a list and the [proposed process for location management](https://docs.google.com/presentation/d/1plxqiWqRaVfgEtM0hm51YWYNWKLEQlAokIgSy0yPckA/edit#slide=id.g7d8fa4efb7_0_134), so we are good to go moving forward with #1301 .
