### ISSUE TITLE
Mobile Work Orders - Improve layout and styling on Inventory Items 

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#1304]
There are a few cosmetic issues we could improve on the Mobile work orders

- [x] Edit and Cancel Buttons are cluttered
- [x] Text doesn't wrap on mobile
- [x] Status color-coding doesn't go all the way to the edge of the accordion, has padding
- [x] spinner expands the sizing of the button temporarily 
- [ ] others?

Exs:
![Screen Shot 2020-01-28 at 5 38 14 PM](https://user-images.githubusercontent.com/5697474/73315263-3deda980-41f5-11ea-841b-601ad6b9e566.png)
![Screen Shot 2020-01-28 at 5 39 03 PM](https://user-images.githubusercontent.com/5697474/73315268-42b25d80-41f5-11ea-9ed1-d87e980f4b1c.png)
![Screen Shot 2020-01-28 at 5 39 47 PM](https://user-images.githubusercontent.com/5697474/73315285-4d6cf280-41f5-11ea-9f5c-a5234b9acf4e.png)

**Comment by JaceDeloney** [comment]
More requests:
[ ] Make line item headers bold and 2 pts larger
[ ] Make field titles bold
[ ] Move comment field to far right
[ ] Move status to the far right (first column)
[ ] Make status a badge (see below)
![Screen Shot 2020-02-06 at 4 05 23 PM](https://user-images.githubusercontent.com/10567316/74173683-269cbc00-4bf8-11ea-9d63-8fc33a1b8315.png)

**Comment by JaceDeloney** [comment]
@mateoclarke Let me know if I should make new issues out of the requested changes above ^

**Comment by mateoclarke** [comment]
@JaceDeloney, yes. lets make these into a new issue and prioritize accordingly. The original tasks for this issues are already complete and pending review

**Comment by mateoclarke** [comment]
Made this issue: https://github.com/cityofaustin/atd-data-tech/issues/1418
