### ISSUE TITLE
Replace Lambda function blueform_location_from_latlon

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13057]
The hasura event is called `blueform_location_from_latlon`. When this event is triggered, it triggers the following Lambda functions in AWS:
`atd-vz-data-events-crash_update_noncr3_location_staging` and `atd-vz-data-events-crash_update_noncr3_location_staging`.

Past notes on what this lambda function does:
_Triggered on insert to atd_apd_blueform or update of columns latitude, longitude
This calculates a new location ID on crash location update if necessary and if the new location id is different from the old location id then it updates it. This seems like it could be converted to a DB trigger._

Source code can be found in AWS Lambda or https://github.com/cityofaustin/atd-vz-data/tree/master/atd-events/crash_update_noncr3_location

#12644 is the LDM side of this

**Comment by mddilley** [comment]
Making good progress on this one. I've broken down the steps in the Python code of the Lambda into a SQL trigger that fires on insert and updated of records in the `atd_apd_blueform` table.

Going to seek some feedback about turning this into a generated column much like @roseeichelmann's work on the AFP flag. I think that we could get away with it as long as there isn't something that I'm missing like manual entry from somewhere. Just thinking about data loss. We've talked about making that change for `location_id` in the `atd_txdot_crashes` table in the past too.

For now, I'm creating a separate column in my local DB to compare the results currently in the production database for blueform crash locations against the ones coming out of a simplified function.

**Comment by mddilley** [comment]
Running:
```sql
SELECT case_id FROM atd_apd_blueform
WHERE location_id <> generated_location_id;
```
on the current production data returned some records with differences in the following case IDs:
`141801371, 142201176, 142280655, 142321599, 142360690, 142601531, 150490764, 151580567, 152671685, 152751970, 143210993, 150340435`

I'll take a closer look at those tomorrow.
```

**Comment by mddilley** [comment]
Replacing the `location_id` column in `atd_apd_blueform` affect several views and materialized views that must be dropped and then added again

I've mapped them out in this diagram
https://excalidraw.com/#json=vc2zEGGyIXHCpOGgtCB6c,qxAav_hAT2WBRtLLmdRqxg
![location_id_dependencies.png](https://images.zenhubusercontent.com/5cfe7d078509cb6dcbaafdc3/284e164b-43ba-4cec-9071-704368f64ced)
