### ISSUE TITLE
Update expiry date on all active fees for FY24 (SR) (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13053]
### ROW Fees
List of ROW Fees as confirmed by Kyle K provided below:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0RHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--daecd9268851b159e5be54e6642abf774af77d58/image.png)

### TDS Fees
List of TDS fees as confirmed by Amber H provided below: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajdHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--150c5833328bf4ea7176107cd39bb991905b776b/image.png)

### OSE Fees
List of OSE Fees Confirmed by Maria A provided below: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWErIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6719cb25faf6c4852b9584eb3a3488c998d8ba58/image.png)

**Comment by vschandramouli** [comment]
@TracyLinder @Sreelatha-BlazeKannan @Nadin-Nader Finalized the list of fees from all 3 departments. These fees can be renewed for the new FY. Please review and let me know if there are any questions. 

Thanks !

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please add these SCP fees to your list:

83413                                  SCP Annual ATD Pole Rental Fee               SCP

83445                                  SCP Prorated ROW Usage Fee                    SCP

83446                                  SCP Annual ROW Usage Fee                       SCP

83441                                  SCP Transport Facility ROW Usage Fee    SCP

83443                                  SCP Transport Facility Application Fee     SCP

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV & TEST DP of #13053 submitted. Kindly approve and create tasked for the same to be promoted in both DEV & TEST.

Commit ID: [8cf179d403c6](http://coaamandadevops02.austintexas.gov/R5:8cf179d403c6f1f39ea715b2adb3efdd1bf10994)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been sent to the DevOps Cm Team to be deployed to DEV and TEST under **SCTASK0358872**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - This is promoted to Both DEV & TEST; verified the results and all looks good. Ready for TEST UAT and PROD Promotion.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - PROD DP of #13053 submitted. I verified both DEV & TEST Data and all looks good. Kindly approve and create task id for the same.

Commit ID: 8cf179d403c6

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0359270**

**Comment by Nadin-Nader** [comment]
This has been deployed to PROD

**Comment by Nadin-Nader** [comment]
This has been deployed to PROD and doesnt seem to have any issues. closing
