### ISSUE TITLE
Update all GL codes for TPW FY24 (Ready to UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13050]
Attaching documentation below listing fees needing GL Update for FY 24

[GL update for FY 24.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2JSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c5d13a7941e4a6b59c8c748bc606f6fdba166a6b/GL%20update%20for%20FY%2024.xlsx)

**Comment by TracyLinder** [comment]
@vschandramouli this is ready to add the fee GL code changes to the AC. Then On Deck for @Sreelatha-BlazeKannan

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Updated the GL code for the fees in the attached document (highlighted in green), done a Part 1 commit and requested for Dev and Test promotion- SCTASK0358694

**Comment by Lpriya-LIT** [comment]
@TracyLinder Got clarification from Nadin, have updated the remaining GL codes and committed changes.
@vschandramouli Updated GL codes for the SCP fees 
@Nadin-Nader Created request for Dev and Test promotion - SCTASK0358774

**Comment by Lpriya-LIT** [comment]
[GL update for FY 24 - Updated .xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXJoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3e0750fef56bebfd212246fc3a435a312dd3d8d7/GL%20update%20for%20FY%2024%20-%20Updated%20.xlsx)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created Prod deployment request 
SCTASK0359230

**Comment by Nadin-Nader** [comment]
This has been deployed to PROD

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Prod database , GL codes are updated

**Comment by Nadin-Nader** [comment]
GL Codes seem to be good to go with no issues now. closing
