### ISSUE TITLE
[TCP Conflict/Shared Review Cycles] Builder Updates after Demo on 7/27/23

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13066]
_(From [these](https://github.com/cityofaustin/atd-data-tech/issues/13062#issuecomment-1654008787) meeting notes.)_

- [x] ✍🏻 ~Remember to do the customer portal example update. `Tracy - find the issue and connect it to the epic`~ `Done on #12313 `
- [x] ✍🏻 Landing page - Add column for **In-Date** (Date case is created)
- [x] ✍🏻 Case Details - Change field name **Assigned Reviewer** to **Lead Reviewer**
- [ ] ✍🏻 Case Details - Remove field **Calculated Due Date**
- [x] ✍🏻 Case Details - Display 2 modification fields (Modified, Modified Date)

**Comment by TracyLinder** [comment]
Hi @KaroEngstrom this is ready for you (I think). Would you please add an estimate? I put this On Deck for this sprint; please let me know if this sprint doesn't work so I can discuss with the other PO's who might have work on your plate. Thank you, and seriously awesome job on the demo today! 🎉

**Comment by KaroEngstrom** [comment]
## F 7/28/23 
- [x]  **Conflict/Shared Landing page** - Add column for In-Date (Date case is created)
     - using **Submitted Date** field for this
     ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/bc173b20-55ec-490c-bec6-7ed86ec11d1e)
- [x]  **Request Details** - Change field name Assigned Reviewer to Lead Reviewer
     - changed this already; I don't think it will cause confusion before or during the transition from singles to cycles
- [ ]  **Request Details** - Remove field Calculated Due Date
     - ✋ holding off on implementing this because the request due date is currently the only goal post for the reviews; will remove this after we are in cycles fully as all the date tracking will move to the Submission records at that point
- [x]  **Request Details** - Display 2 modification fields (Modified, Modified Date)
     - added **Modified By** field (shows user account) and **Modified** field (shows timestamp of last modification, completed by the account shown in the previous field)
     ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/3e059338-2aba-4f35-bb04-aca95ab5f455)

**Comment by TracyLinder** [comment]
@KaroEngstrom do you think we should leave this open due to the calculated due date task, or should we move that task somewhere else?

**Comment by KaroEngstrom** [comment]
Let's close this and I'll add that to go-live check list (will have a prep list for go live and then a during go-live list) 🙏
