### ISSUE TITLE
Explore design possibilities for Dash data dashboards

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#13064]
## Description

We're in the early stages of building a new product, Dash, and we need a visual to help communicate the concept to TPW's executive team. 

## Objective

The vision of Dash is to centralize the department's data and reporting in one place so that we can track, compare, analyze, and adjust our work toward important goals. The dashboards will be a visual representation of the overall health of the department, highlighting key metrics and offering a standardized format to represent various data across work groups.

At the department level, it needs to focus on/include: 
- Service delivery to residents - CSRs (customer service request)
- Increasing efficiencies 
- Maps/geo data

At the service area level, it needs to include (refer to the [TPWstat Executive Proposal](https://cityofaustin.sharepoint.com/:p:/r/sites/TPWReorg/Shared%20Documents/General/PERFORMANCE%20MANAGEMENT%20PROGRAM/TPWstat%20Development/2023.08.02%20TPWstat%20Executive%20Proposal.pptx?d=wc560a322d8b14e96a2e2f6d2652fb6da&csf=1&web=1&e=qZf7F1)): 
- Short list of priority projects / initiatives 
- Stakeholder satisfaction score
- Finance data
- Personnel data

The audience for the dashboard includes many people, from TPW staff, managers, and executives to city council members, Austin residents, and anyone who wants to see what TPW is working on.

## Deliverables

- Add research findings on data dashboard designs to [Dash miro board](https://miro.com/app/board/uXjVM1Z5trE=/)
   - One cool site I found: https://nativeland.info/data-dashboards/ 
- Create a visual that we can use to help communicate Dash's concept to stakeholders
   - Hierarchy of data with several levels - department, service area, division, down the rabbit hole
   - Maps in every dashboard if possible
   - Visual indicators for on track / off track toward goal (goal, planned, actual)
   - Standardized format that makes it easier to understand various data

**Comment by patrickm02L** [comment]
@katelunceford will you add Madison and me to TPWstat Executive Proposal doc?

**Comment by katelunceford** [comment]
## Hierarchy / levels

### Department level
1. TPW

### Service area level - 7 service areas
1. Street and Bridge Operations
2. Strategic Mobility Services
3. Engineering & Project Delivery
4. Civil Engineering Services
5. Transportation Services
6. Business Support Services
7. Office of the Director

### Division level - 33 divisions (service area in parentheses)
1. Street & Bridge Operations (Street & Bridge Operations)
2. District Maintenance (Street & Bridge Operations)
3. Utilities & Structures (Street & Bridge Operations)
4. Pavement Operations (Street & Bridge Operations)
5. Urban Forestry (Street & Bridge Operations)
6. Vision Zero (Strategic Mobility Services)
7. Signs & Markings (Strategic Mobility Services)
8. Arterial Management "Signals" (Strategic Mobility Services)
9. Office of Special Events (Strategic Mobility Services)
10. Right of Way (ROW) Management (Strategic Mobility Services)
11. Transportation Engineering (Engineering & Project Delivery)
12. Capital Services/Project Delivery (Engineering & Project Delivery)
13. Active Transportation Engineering Services (Engineering & Project Delivery)
14. Office of the City Engineer (Civil Engineering Services)
15. Sidewalks & Special Projects (Civil Engineering Services)
16. Community Services (Civil Engineering Services)
17. Emergency Management (Civil Engineering Services)
18. Logistics (Civil Engineering Services)
19. Strategic Projects (Transportation Services)
20. Strategic Communications & Outreach (Transportation Services)
21. Smart Mobility / TDM (Transportation Services)
22. Transportation Development Services (SIF) (Transportation Services)
23. Land Development Engineering (Transportation Services)
24. Long Range Planning (Transportation Services)
25. Program & Project Development (Transportation Services)
26. Finance (Business Support Services)
27. Human Resources (Business Support Services)
28. Data & Technology Services (Business Support Services)
29. Performance Management (Business Support Services)
30. Parking Enterprise (Business Support Services)
31. Public Information Office (Office of the Director)
32. Administrative Management (Office of the Director)
33. Legislative Affairs (Office of the Director)

**Comment by amenity** [comment]
Since this was initially written for Madison at the end of her fellowship, this issue is no longer needed. @katelunceford will transfer/link to this information in #14021 and it.

**Comment by katelunceford** [comment]
Closing this since it was initially written for Madison at the end of her fellowship - and now there's a similar issue [#14021](https://github.com/cityofaustin/atd-data-tech/issues/14021) and will be tracked there moving forward. Some of the ideas in this issue were also transferred to the [Dash miro board](https://miro.com/app/board/uXjVM1Z5trE=/).
