### ISSUE TITLE
Ensure consistency of public-facing data in Socrata and the Vision Zero Viewer

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13068]
## Description
As a data administrator for the Vision Zero suite, I want to ensure that the public-facing data available in [Socrata](https://data.austintexas.gov/Transportation-and-Mobility/Vision-Zero-Crash-Report-Data-Crash-Level-Records/y2wy-tgr5) aligns perfectly with the data presented in the Vision Zero Viewer. This is essential to avoid confusion and ensure that users have access to accurate and relevant information.

## Deliverables
- Parity between the Vision Zero Viewer view and data in Socrata (open data portal)

## Notes
- Get feedback from the VZ team (Xavier) to address any challenges during the data synchronization process

**Comment by chiaberry** [comment]
I watched the release party and the discussion around changing the data in socrata (starts around min 54). Xavier says the public should only be able to download a dataset containing only serious injuries and fatalities, i.e. only the data that is represented on the vz viewer. Is the request to have a dataset that is filtered down to serious injuries and fatalities, or is the request to remove the public data of all of the crashes, and *only* provide serious injuries/fatalities? If so, what is the rationale behind removing our open data?

**Comment by patrickm02L** [comment]
## 08/10/23

This is TxDOT with VZ edits. We do not own the data, we are processors of data. If this is being classified as Vision Zero data it needs to be account for by the VZ team.

### Notes
- Remove reference to Vision Zero in the dataset, change to Crash Report Data to reflect that the data is coming from multiple entities.
[Socrata](https://data.austintexas.gov/Transportation-and-Mobility/Vision-Zero-Crash-Report-Data-Crash-Level-Records/y2wy-tgr5)
- Remove the placeholder from the dataset because we don't have the CR3

### Next Steps
- Would like to roll Joel & Lewis into the conversation

**Comment by chiaberry** [comment]
perhaps could be related to https://github.com/cityofaustin/atd-data-tech/issues/6661

**Comment by patrickm02L** [comment]
## 9/12 
Current description text to be edited:

> Crash data is obtained from the Texas Department of Transportation (TXDOT) Crash Record Information System (CRIS) database, which is populated by reports submitted by Texas Peace Officers throughout the state, including Austin Police Department (APD), and maintained by TXDOT.  
>   
> This dataset contains crash-level records for crashes which have occurred in the last ten years. Crash data may take several days or weeks to be initially provided and finalized as it is furnished to the Austin Transportation Department, therefore a two-week delay is implemented to help ensure more accurate and complete results.  
>   
> Please note that the data and information on this website is for informational purposes only. While we seek to provide accurate information, please note that errors may be present and information presented may not be complete. For official inquiries on City of Austin crash data, contact [VisionZero@AustinTexas.gov](mailto:VisionZero@AustinTexas.gov)

**Comment by patrickm02L** [comment]
Updated description so that VZ is not mentioned in the following datasets
- [Austin Crash Report Data - Crash Level Records](https://data.austintexas.gov/Transportation-and-Mobility/Austin-Crash-Report-Data-Crash-Level-Records/y2wy-tgr5)
- [Austin Crash Report Data - Crash Victim Demographic Records](https://data.austintexas.gov/Transportation-and-Mobility/Austin-Crash-Report-Data-Crash-Victim-Demographic-/xecs-rpy9)

**Comment by patrickm02L** [comment]
Considering this closed will address the test data set in it's reference Issue above.
