### ISSUE TITLE
Meet with Finance to Understand Reporting Needs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1308]
Van has provided us with a few sample reports from microstrategy, [here](https://github.com/cityofaustin/atd-data-tech/issues/1160). We need to meet with her to better understand her reporting needs.

This issue is blocking the implementation of inventory reporting for finance.

**Comment by dianamartin** [comment]
Met with Van on 5/27 to discuss her concerns about the Inventory Reporting. Was able to capture other requirements she needed for reconciliation.
