### ISSUE TITLE
Update field length on signs attachment layer

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#13109]
We need assistance adjusting the maximum length of a column on the `Signs_Work_Orders_AGOL` feature service.

On the `attachments` layer, the `regulation_number` column should be increased to `500` characters.

Here is the item details page on AGOL: https://austin.maps.arcgis.com/home/item.html?id=93e29b23c39b4110ab0bbefde79b4063

Please note this item is owned by the `ATD_Scripts_Publisher` account.

**Comment by amenity** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data--Technology-Services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/13109?planning-poker) with Zenhub @ChristinaTremel @TracyLinder

**Comment by amenity** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data--Technology-Services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/13109?planning-poker) with Zenhub @patrickm02L

**Comment by johnclary** [comment]
Andrew republished the feature service with a new column that meets our length requirement. I reprocessed the data and all looks good.

**Comment by andrewshensky** [comment]
The Regulation Number field in the Sign Work Order data has now been replaced with a new field with the same name but given a 500 character length. 

Looks like the new field is being populated correctly.
