### ISSUE TITLE
Ability to Cancel an Unissued Item from the Finance System

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1310]
As a warehouse staff, i need the ability to cancel an item request that has not been issued.

- Add "Cancel" column to inventory items table on the inventory request details page
- This button should open a modal form that allows the user to add a comment
- On submission, this form should set transaction's `CANCELLED` field to `1`.
- On submission, this form should trigger an API call to update the transaction in the Data Tracker

**Comment by dianamartin** [comment]
On the `Inventory Request Details` page
- Added another edit form on the `All Inventory Requests` table
- Renamed it to `Cancel`, url: `cancel`, modal
- Added `Comment` field

Submission Rules:
![image](https://user-images.githubusercontent.com/21112975/73369095-abdab500-4277-11ea-996a-391bacb6b9a0.png)

**Comment by dianamartin** [comment]
- 1. Added display rules to hide the `Cancel` button when status is not `New`. 
- 2. Reviewed and display rule is working as expected

**Comment by johnclary** [comment]
had to make a few minor changes to make this work with the Data Tracker integration:
- change form rule to set CANCELLED to "Yes" (CANCELLED_ITEM field is conditionally set behind the scenes)
- add a form rule to set SUBMITTED_TO_DATA_TRACKER to "No"
- add CANCELLED field to API finance system view!

have tested this an it work!

[Screen Shot 2020-02-06 at 7.24.51 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/cfa8430d-7d31-4d01-aa69-8a6927fbf2ec)
