### ISSUE TITLE
[Enhancement] Ability to view and edit unmapped project components

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#13117]
The interim access DB has ~480 unmapped project components. They have a component type, but no features.

In Moped, it should be possible to view and edit an unmapped component so that it can be mapped and saved. It should remain impossible to save an unmapped component.

**Comment by johnclary** [comment]
@mddilley here's another one for your review. what do you think about the feasibility of this?

**Comment by johnclary** [comment]
fwiw, i am open to the idea that we hold firm on requirement for all components to be mapped, and instead ask the project maintainers to map their projects if they want them migrated.

**Comment by johnclary** [comment]
also fwiw: in my quick experimentation with this it already seems possible to map an unmapped component, but editing the attributes fails. [this project](https://4838-jc-migrate-access-db--atd-moped-main.netlify.app/moped/projects/4592?tab=map) in the access migration has an unmapped component

**Comment by mddilley** [comment]
@johnclary I think this is definitely possible by splitting out the incoming components without features so we treat unmapped components differently until they are mapped. Then, we could build some components (`ListItems`, etc) to exclusively handle unmapped components so we could open the door to differentiating them in the UI (colors, icon, etc) without impacting the mapped components. 

Thanks for testing this a bit and highlighting the broken attributes editing. This will probably take some refactoring/bug squashing like that as well.

**Comment by mddilley** [comment]
@johnclary I've been trying to replicate any issues with editing unmapped projects component, and I can't get the edit form or mapping to break. Maybe we've unknowingly shipped this with other features? I'm using the latest from `main` branch.

To replicate, I inserted a new component directly into the database:
```sql
-- just component type and description didn't break the UI
INSERT INTO moped_proj_components(project_id, component_id, description)
VALUES (227, 8, 'unmapped project component');

-- also tried adding a subcomponent from the beginning and checking the UI
INSERT INTO moped_proj_components_subcomponents (project_component_id, subcomponent_id)
VALUES (6, 38);
```

Can you help me out and see if you can break this? So far, I'm just seeing that the UI allows both adding features to an unmapped component and also editing the unmapped component's attributes (in either order).

**Comment by johnclary** [comment]
Wow—same here: i cannot break the form. I've tested this by creating a few components and then deleting all features:

```sql
delete * from features;
```

Edit: well, i can actually break the form if i try to edit a signal component with no feature. however that is actually a case we are not going to allow to happen via the access migration.

I'm thinking that your fairly recent refactor of the component form state and submit behavior may have cleared this up? 

I'm going to take some more time to test with the Access DB data just to be sure. In any case, I will take this issue back off your hands and add some scoping around (1) preventing the feature zoom if there is no feature and (2) adding some visual feedback if the feature is unmapped.

Thanks Mike!

**Comment by mddilley** [comment]
@johnclary Agreed - I think that some of the recent changes to this area probably fixed this up for us. I like your ideas around UI cues that a feature is unmapped. 👍 I'll grab something else from the backlog!

**Comment by johnclary** [comment]
i have retested this with more real-life examples and it is a non issue. thanks @mddilley!
