### ISSUE TITLE
[Enhancement] Enable "direct select" component drawing

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#13116]
When drawing a line component, it is currently only possible to create, delete, or drag a line segment.

Users need the ability edit line vertices without deleting/drawing a new line. This should be possible by enabling the "[direct select](https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/API.md#direct_select)" draw mode.

This feature has become more important because of the thousands of hand-drawn line segments we will import as part of #4838.

**Comment by johnclary** [comment]
@mddilley what do you think estimate-wise on this one? i seem to remember we had some technical concerns about this when we first set up the draw interface, but i can't recall what exactly.

**Comment by mddilley** [comment]
@johnclary Yes, the direct select mode let's you split line segments with some mouse clicks, and iirc we were worried about users unintentionally activating this mode and making changes that didn't want. That sounds like the level of control that we want now, though. There is probably a little discovery here to see if that matches up with the types of edits needed and if we can fine tune that behavior at all.
