### ISSUE TITLE
[Security] Address security vulnerabilities on web properties

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13128]
Gabriel H., Vulnerability Management Consultant from Information Security Office, notified @scottreedy of the following: 

> So we have been using BitSight to scan public facing assets and report on those vulnerabilities for departments. I have a few items for ATD that when fixed will increase the BitSight score of the city. All of them seem to be on mobility.io. As you can see below ...

Sticking the rest of the info [here](https://docs.google.com/document/d/1g4wPcgyvlkOfgMfbv4Z9yyja6Y-jzMs-hK-TWms43QQ/edit?usp=sharing) in case it's bad form to have it public.

**Comment by johnclary** [comment]
Nice—I'm glad someone is looking at this for us—I added the `Security` type label  as well 😅

**Comment by johnclary** [comment]
Also added it to the grooming doc...

**Comment by johnclary** [comment]
We discussed briefly in grooming and i added it to the planning doc for next sprint

**Comment by chiaberry** [comment]
https://help.bitsighttech.com/hc/en-us/articles/360008632054-How-is-the-Web-Application-Headers-Risk-Vector-Assessed-#required

**Comment by frankhereford** [comment]
The endpoints mentioned in this report have been upgraded to the latest security profile, which mandates the use of TLS 1.3, via the AWS configuration of the application load balancers. I wrote Gabe this morning, and I'm going to close this under the assumption that we don't have any more work to do, but if he comes back with further findings, I'll re-open.

**Comment by amenity** [comment]
Thanks, @frankhereford!

**Comment by johnclary** [comment]
Wow—thanks for upgraded us, Frank!

**Comment by frankhereford** [comment]
Bad break on this issue:

From Gabe at CTM:

```
Hey Frank,
 
Looks like the TLS issues have been resolved successfully! Now it’s just those security headers that need to be set:

Cache-Control
Content-Security-Policy
Strict-Transport-Security
X-Content-Type-Options
 
If you need anything else please let me know!
```

They want these headers set on our graphql-engine endpoints, which isn't clearly possible with our current setup. I'd like to talk about this briefly in grooming today if there is time. Is that cool @chiaberry? Thanks!!

**Comment by frankhereford** [comment]
Here's some brief info on these headers:

**Cache-Control**: This header specifies caching policies for both requests and responses. It controls where, when, and how long a response can be cached. For example, Cache-Control: no-cache tells browsers not to cache the response.

**Content-Security-Policy (CSP)**: This header helps prevent cross-site scripting (XSS), clickjacking, and other code injection attacks. CSP allows you to specify which sources the browser should allow for loading resources like scripts, images, CSS, etc. For instance, Content-Security-Policy: default-src 'self' restricts resource loading to the same origin.

**Strict-Transport-Security (HSTS)**: This header enforces secure (HTTPS) connections to the server. It tells browsers to only access the website using HTTPS for a set period. An example is Strict-Transport-Security: max-age=31536000, which sets this policy for one year.

**X-Content-Type-Options**: This header is used to prevent MIME type sniffing. When set to nosniff, it instructs the browser not to override the response's content type. For example, X-Content-Type-Options: nosniff stops the browser from interpreting files as a different MIME type than what's specified by the content-type header.

**Comment by chiaberry** [comment]
adding it to refinement!

**Comment by chiaberry** [comment]
upped the estimate, just to acknowledge more work around this --

**Comment by frankhereford** [comment]
Thanks Chia! We discussed this in refinement today, and to memorialize our conversation:

* I'm going to compose an email to Gabe stating the amount of work in the context of the benefit, also explaining the infra we're talking about here and the non-impact of not heading these headers is in this situation
  * Email to be reviewed in the dev channel prior to shipping it
* In doing so, I'm going to seek his guidance on if it's worth it to go forward or somehow negotiate dropping this requirement if possible

**Comment by frankhereford** [comment]
It's been a week since I posed the question to Gabe about the implications of not putting those headers in there, and I have not heard back, so I'm going to close this on the assumption that this is squared up. If he does respond, I'll be happy to reopen.
