### ISSUE TITLE
Conduct VZE Observation with Xavier

### ISSUE THREAD

**Issue by madifan** [cityofaustin/atd-data-tech#13125]
## As a design fellow I want to gain an understanding of how VZE users interact with a product to provide valuable insights for improving functionality and usability.

**Is your feature request related to a problem? Please describe.**
We are conducting usability observation sessions with VZE users to get insights for improving the VZE crash and locations page UI. 

**Deliverables**
- [ ] Affinity map from observation transcript on Miro
- [ ] Themes and insights

**Comment by madifan** [comment]
@patrickm02L

**Comment by patrickm02L** [comment]
Decided to roll this Issue into the #13157
