### ISSUE TITLE
Add SSL to CCTV Thumbnail Server

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1313]
The CCTV thumbnail [image server](http://atdatmsweb2.austintexas.gov/CCTVImages/CCTV1.jpg) (`ATDATMSWEB2`) does not support HTTPS. As a result thumbnail image links on the [device status page](http://transportation.austintexas.io/device-status/) are broken in modern internet browsers.

We need to buy an SSL cert via CTM and install it on the server.

**Comment by johnclary** [comment]
I reached out to Kimley-Horn and CTM (Chad) to confirm they support this. 

FYI @amenity this should be something the devs can take care of with minimal effort. Will probably pass it to Mateo once I hear back from Kimley-Horn.

**Comment by amenity** [comment]
Cool. Sticking it in the backlog and you can assign it & move On Deck when you hear back, @johnclary .

**Comment by johnclary** [comment]
KH confirmed that we just need to provide them a cert. next step is to submit a purchase request and a CTM service now request to buy the cert. ideally, we would do move the image hosting to our own script and S3 bucket. let's discuss in sprint 18. i tagged this accordingly.

**Comment by johnclary** [comment]
No longer needed thanks to https://github.com/cityofaustin/atd-data-tech/issues/1046.
