### ISSUE TITLE
[Meeting] Sidewalks & Special Projects Division SharePoint Advisory

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#13158]
# Tue 8/1/23 
From Jeannette: 
I’ve added you both as Owners on the [Sidewalk & Special Projects SharePoint Site](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcityofaustin.sharepoint.com%2Fsites%2FPWDSidewalksSpecialProjects&data=05%7C01%7CKaro.Engstrom%40austintexas.gov%7C07d14876a9224769a00108db9204fb07%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638264322314807451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lo74lD2ycyWdI%2FuFdwGl0v3el8LhQTedjD1DfjCAdXo%3D&reserved=0). It is a new site created to move documents off the Shared G Drive for SSPD. Shelley K. has been the SPOC for content. She has requested a meeting Tuesday, Aug 1st at 1pm for a Q&A session for their SP site. I intend to let them know at the meeting to contact Karo for support going forward.

In the room: 
Karo, Diana, Jeannette, Shelley K., Gabe T. 

Notes: 
- key ask about syncing from SharePoint to OneDrive - Diana modeling this and advising on use

Next step: 
- their entire team needs to be able to sync to SharePoint via OneDrive - we might be able to use that as a follow-up as well to cover other questions; good idea to do a standardized process for all to sync
- their next staff meeting is 8/15 at 10:30am 
- another topic to cover would be sharing files (sharing with named users, groups, might be a way to go) 
- need to do more discovery on this and sync with Diana to map out the items to address

**Comment by KaroEngstrom** [comment]
Next meeting scheduled for T 8/15 at 9am

**Comment by dianamartin** [comment]
# 8/16
We were invited to the SSPD Division Meeting and we were there to explain the best practices from personal OneDrive and SSPR SharePoint Document Library. We had created a Miro board to have a visual explanation of the process.

**Comment by dianamartin** [comment]
@KaroEngstrom any other notes before we close this?
