### ISSUE TITLE
Add new TPW divisions to DTS Portal dropdown

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#13154]
Need to add PW divisions to DTS Portal dropdown

_Originally posted by @susannegov in https://github.com/cityofaustin/atd-data-tech/issues/12725#issuecomment-1660586200_

**Comment by amenity** [comment]
@ChrispinP - can you confirm that between #13155 and other tweaks you've made that this is taken care of?

**Comment by dianamartin** [comment]
# 7/8/24
I believe this was taken care of in this issue #13155
