### ISSUE TITLE
VZE Observation Sessions

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13157]
## Description
Conduct an observation session with members of the Vision Zero team in order to gain a deeper understanding of how the Vision Zero Editor platform is utilized by the team. We aim to gather insights that will inform the design solutions for individual crash and location pages.

### Specific areas of interest include:
- Data Acquisition: How data is obtained and integrated into the platform.
- Data Editing: How the team manages and modifies data within the platform.
- Interactivity with the Open Data portal: How the Vision Zero Editor interacts with the Open Data portal for data sourcing.
- Overall Workflow and Efficiency: The team's workflow within the platform and opportunities for improvement.
- Specific User Use Cases: Understanding how different team members use the platform based on their unique roles and requirements.

## Requirements
- Scheduling an observation session with the Vision Zero team.
- Setting up screen recording to capture the meeting for transcript purposes.
- Facilitating the session to explore the team's interactions with the Vision Zero Editor.
- Creating a framework for gathering feedback and insights on the identified areas of interest.

## Deliverables
The expected outcomes of this user story are as follows:
- Comprehensive insights into how the Vision Zero Editor platform is currently being used.
- Identified pain points and areas of improvement within the platform's functionality.
- Understanding of specific user use cases and requirements for better customization.
- Documentation of the observation session, including the recorded transcript for further analysis.

## Notes
The observation session is expected to last for 1 hour. The DTS team will then analyze the findings and group themes to generate valuable insights. These insights will drive future design solutions to enhance the platform's usability and efficiency.

## Observations
- [x] Xavier 7/31
- [x] Milad 8/3
- [x] Joel 8/4
- [x] Mary 8/7

**Comment by madifan** [comment]
[Interview outline and notes](https://docs.google.com/document/u/0/d/1zDA-FQ_VThe-t7uSZB6ogK3ZXfgf8AOJpr1OkDugadM/edit)
[Miro board](https://miro.com/app/board/uXjVMwUjkGI=/?share_link_id=537790455499) that includes affinity map of interview data
[Observation insights report](https://docs.google.com/document/d/1x2obcl2MB40NbJzjmqgV8eRdtc1l4uVXdycqY5f4HpI/edit?usp=sharing)

**Comment by patrickm02L** [comment]
@patrickm02L nix the individual Issues

**Comment by patrickm02L** [comment]
Video of the observations can be found [here.](https://drive.google.com/drive/folders/1JQLmdVeERr_aAYlgZ2S7eM8id9J2jqa3)
