### ISSUE TITLE
Have Pat try to log in to Banners

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1315]
Since we're waiting on CTM for #993 let's see if AUSPS people can even use our ADFS log in to begin with. 
- [x] Create an account for Pat in the Street Banners application @dianamartin 
- [ ] Email him and ask if he can log in

**Comment by dianamartin** [comment]
I created an account in the Street Banner application.

**Comment by dianamartin** [comment]
Emailed Pat

>We’re in the process of getting the single sign on added to the VZA app, but we’d like to test with you (because you have an AUSPS email) on another application that we have the single sign on configured. If you could navigate [here](https://atd.knack.com/street-banners#home/) and click the “Sign in with COACD” button to try to sign in. I created an account on the application for you, but we’re just wondering if you’ll be able to log in. 

>If you see an error message or anything else, can you please be sure to email a screen shot of it to us.

**Comment by dianamartin** [comment]
Pat emailed back
>I couldn’t get in. 
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/40a3516f-495a-45f3-afa3-0c4e0f76f37d)

**Comment by dianamartin** [comment]
@amenity @SurbhiBakshi 

I tested this morning an changed his email address in the back end to @ausps.org bc that's how it is in the address book. I had a feeling it was his default email and the other one was an alternate email redirect. 

I clicked the "Sign in with COACD" button, entered the @ausps.org email and then I received a redirect to 
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/a6838e1b-ba52-406f-9bc9-c18df214e1c2)

then a sign in for ausps
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/8c9a79bc-aefe-440f-97ba-065725b222a5)

**Comment by johnclary** [comment]
interesting @dianamartin! we should definitely be able to do this, we just need a technical contact at CTM/Public Safety who can configure it for us.

**Comment by dianamartin** [comment]
@johnclary I had emailed Pat to retry it after I made some changes
>I made a couple of changes and put in the ausps email and it seemed to redirect to a sign in page for your organization. Can you please try click the “sign in with COACD” button. 

Pat emailed
>Ok, I clicked on the “sign in with COACD” button and it logged me in automatically without me having to enter any email info or password info. It took me to the “Street Banner Program”.

So success!

**Comment by amenity** [comment]
Thanks for your perseverance, @dianamartin! So much better for our users to have this.

**Comment by SurbhiBakshi** [comment]
yes, thanks @dianamartin! this will make the process much smoother!
