### ISSUE TITLE
DTS Portal Account clean up

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#13165]
Diana 
DTS

Thought that the DTS Portal Accounts need to be reviewed after finding a separated employee. 

## Need
Need to review the DTS Portal Accounts against the HR Employee Accounts

## What we're trying to accomplish
- We want to know what the level of effort is (easy, medium, hard)
- What to establish a frequency of clean up (quarterly, once a year?)

**Comment by dianamartin** [comment]
# Steps
- [ ]  Export inactive employees list in HR app - `accounts` object table
- [ ]  Remove `User permissions` and make status: `Inactive`

**Comment by susannegov** [comment]
# Employee Division QC
Filter though inactive and set `accounts` object in DTS Portal also to `inactive`
- [ ] ATD HR | 9
- [ ] Active Transportation Program | 16
- [ ] Administration | 21
- [ ] Architecture Project Mgt Div. | 26
- [ ] Arterial Management Division | 78
- [ ] Asset Management | 2
- [ ] Austin Transportation | 70
- [ ] Community Services Division | 36
- [ ] Construction Management | 57
- [ ] Corridor Program Office | 24
- [ ] Data & Technology | 13
- [ ] Data and Technology | 5
- [ ] District Maintenance | 60
- [ ] Enforcement Services | 68
- [ ] Engineering Services | 31
- [ ] Finance | 19
- [ ] Finance and Technology | 4
- [ ] Financial Services | 25
- [ ] Human Resources | 1
- [ ] Human Resources Office | 12
- [ ] Mobility Services | 7
- [ ] Office of Special Events | 12
- [ ] Office of the City Engineer | 29
- [ ] Office of the Director | 9
- [ ] Office of the Director, Transp | 10
- [ ] PWD Office of Performance Mgmt | 6
- [ ] Parking Services | 18
- [ ] Pavement & Infrastructure | 65
- [ ] Project Delivery | 11
- [ ] Project Management | 49
- [ ] Public Affairs Office | 6
- [ ] Public Information Office | 19
- [ ] Public Works | 245
- [ ] Quality Management Division | 17
- [ ] Right-of-Way | 51
- [ ] Safety Office | 6
- [ ] Shared Demand Management | 8
- [ ] Sidewalks & Special Projects | 11
- [ ] Signs & Markings | 41
- [ ] Signs and Markings | 9
- [ ] Smart Mobility | 21
- [ ] Systems & Information Mgmt | 13
- [ ] Systems Development | 19
- [ ] Traffic Engineering | 2
- [ ] Transportation Devl Svcs | 15
- [ ] Transportation Engineering | 29
- [ ] Utilities & Structure | 77
- [ ] Vision Zero

**Comment by susannegov** [comment]
# Notes
- Contractors listed as inactive in HR Portal keep active
   - John C
   - Mike D 
- Next time we do this add a "Inactive on DTS Portal" field with Y/N to keep track for next time

**Comment by susannegov** [comment]
@dianamartin This is ready for review/QA

**Comment by dianamartin** [comment]
# 8/23
- Last week started QA/QC'ing
- Today, worked on reviewing Division employees and completed the review.
