### ISSUE TITLE
Determine strategy for school locations

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1316]
We're recommending that we use the [school zone dataset](https://austin.maps.arcgis.com/home/webmap/viewer.html?webmap=f985a3044e254b5bb67425747d4bbc72#) that @alan-deanda maintains for Safe Routes to Schools as a starting point for VZA locations. 

We know we need to figure out what schools lie outside APD's enforcement. @SurbhiBakshi @dianamartin - remind me why we can't do this by overlaying APD sectors?

Other questions:
- Will there be a problem having multiple polygons per record in Knack?
![Screen Shot 2020-02-03 at 7 05 21 PM](https://user-images.githubusercontent.com/1463708/73704675-6aa03600-46b9-11ea-8e64-821ae7f45f6a.png)

- How will officers understand the extents of the schools? 
    - The current tabular descriptions for each feature:
![Screen Shot 2020-02-03 at 7 12 43 PM](https://user-images.githubusercontent.com/1463708/73704634-4ba1a400-46b9-11ea-92bf-bcc7f77f1c55.png)
    - Someone goes in to create a human-readable description (maybe Lewis updates as he uses them?) e.g. "Harris Ave to the east and west of Hampton Rd || Duval St south of Carolyn and north of 33rd || 32nd St west of Liberty St to Fairfax Walk"
   - An image of a map?
![Screen Shot 2020-02-03 at 7 24 09 PM](https://user-images.githubusercontent.com/1463708/73705360-6117cd80-46bb-11ea-8f4e-983ac2a0c0ea.png)
   - A link to the AGOL map, e.g. "[Lee Elementary](https://austin.maps.arcgis.com/home/webmap/viewer.html?webmap=f985a3044e254b5bb67425747d4bbc72&extent=-97.7351,30.2925,-97.7234,30.2982)"

🤞a link/map is possible b/c I don't think the textual descriptions are easy to write or understand.

**Comment by amenity** [comment]
@johnclary - would appreciate your thoughts as well 🧠🗺️

**Comment by SurbhiBakshi** [comment]
@amenity, @dianamartin, @john think this was the example where we are not sure if this location is within  APD juris  ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/ed5468d6-d997-4f7d-bfd1-82e8fa01169d)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5dfbf641-f472-4b3c-9692-532f1486d6ff)

**Comment by amenity** [comment]
Thanks, @SurbhiBakshi - 
Would it be possible to clip the schools polygons to the extent of the APD sectors polygon? If so I'll offer as an option to Jen and Lewis.

**Comment by SurbhiBakshi** [comment]
@amenity technically we can clip the features in the school zones by APD Sectors. The clipped feature might be pretty small though.

**Comment by amenity** [comment]
Sent an email to Jen and Lewis and asked about their preference when it comes to outside-APD-jurisdiction schools. 

"Sketched" my understanding of the data structure [here](https://docs.google.com/spreadsheets/d/11HuTKGz5Lc5v3KVZIKKphZk65XcQJOYaG9tC379133Q/edit#gid=0). 

As @SurbhiBakshi explained, school zones have multiple streets — not always contiguous nor adjacent to the school address. So some type of free text field would be necessary to describe them. [The `Description` field already in the School Zone dataset](https://user-images.githubusercontent.com/1463708/73704634-4ba1a400-46b9-11ea-92bf-bcc7f77f1c55.png) is pretty solid. It would be really idea if we could link users to a zoomed-in map of their specific assignment area.

**Comment by amenity** [comment]
Had a good talk with @johnclary and @SurbhiBakshi about this yesterday and going to follow up ☝️email to check with Lewis about replacing his locations with this new set.

**Comment by amenity** [comment]
During #1417, Pat explained that it would be easiest for officers just to get a school name or address. He feels that seeing the polygons will just cause confusion and have unintended consequences, e.g. an officer doesn't patrol an important nearby intersection because it's excluded from the cell phone zone. 

Lewis reached out to a contact at AISD and got [this list of AISD Schools](https://docs.google.com/spreadsheets/d/1_ktXSWAE6BjqsTPKTKaVV5L_1pYuH4qEn6wXdBl8kwM/edit#gid=2105909394) with school type, school name, address, and closure data through 2023. He'd like to be able to see the closure data in VZA App to avoid scheduling ones that are closed or planned to be closed in coming years.

**Comment by amenity** [comment]
Addendum: @johnclary - how would you feel about defining schools as points instead of polylines?

**Comment by SurbhiBakshi** [comment]
Comparing list from AISD with this article (for my reference) https://communityimpact.com/guides/austin/southwest-austin/news/2019/06/25/austin-isd-bond-construction-projects-advance-this-summer-at-south-austin-schools/

**Comment by johnclary** [comment]
@amenity @SurbhiBakshi i think it be easier to maintain one polyline dataset than both a point and a polyline dataset, especially when it comes to joining the VZA data to the spatial data for visualization. i thought the main purpose of the spatial dataset was visualization/analysis rather than officer instruction. but it sounds like that's not the case?

**Comment by SurbhiBakshi** [comment]
@johnclary @amenity - I think we should be fine with a polyline dataset of what we have right now on our end (school speed zones/ cell phone limits), the officers don't need to see a map. They just want the school name and address. As long as users of the reporting know that the GIS features are representational and not limiting, we should be ok.

**Comment by amenity** [comment]
@SurbhiBakshi @john. Okay, sounds good!
