### ISSUE TITLE
Update folder process name for Transportation Engineering Review (SR) (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13166]
## Process description update & run script for process comment

**There are 2 deliverables for this request:**
1. On process code 51212 update the process description _from_ Transportation Engineering Review to **_Land Development Engineering_**
2. Deploy a script to insert a process comment on all existing processes that says "On MM/DD/2023 this process name changed from Transportation Engineering to Land Review Engineering." This script only needs to run one time, the same day the commit for the name change goes to PROD. _(Let's test the timing on test.)_

----

### There is a Transportation Engineering Review for Site Plan, etc.  I need this group's name changed to Land Review Engineering.  There is no Transportation Engineering in DSD. that group resides in ATD.   This is causing a tremendous amount of confusion and critical reviews are not being routed to the Land Review Engineering Group because of the incorrect name.

INC0268108 submitted to CTM on 2/22/23 and re-assigned to DTS_AMANDA on 7/28/23

**Comment by TracyLinder** [comment]
### Scoping Meeting 7/28/23
_Joelyn, Tracy, Elizabeth, Amber_

- This has been in DSD's backlog for a while. 
- Elizabeth's division has moved to TPW and is no longer with DSD
- I advised Joelyn (DSD) to reassign the SN to me, and I will put this in DTS-AMANDA's backlog. 

**The actual need:** The current folder process name is causing critical land engineering reviews to be missed, and resulting in project delays in the field which have been escalated to Council. We need to identify a solution ASAP.

**Comment by TracyLinder** [comment]
### Email to Stakeholder 8/2/23

Hi Bos, we have data about how this folder process has been used since 10/1/21; [here](https://cityofaustin-my.sharepoint.com/:x:/g/personal/tracy_linder_austintexas_gov/EUg6qu4k76hCg7N32WajfOMBII97MfLmLIiVB_h9VMW2oA?email=Elizabeth.Boswell%40austintexas.gov&e=RO9ocl). We can discuss this on Monday during our scheduled meeting, but I have a couple of questions now if you have time to look at them before then.
1. Are you able to look at the Assigned User names in the data and tell who is who, or who isn't your group? 
2. What year did your group start using this folder process?

Thanks,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
### Data Analysis Notes
- Process was created in 2017 for the C & C8 folders
- Added to SC in 2021
- Added to DA in 2021
- Bos' group began using in 2020
- I'm still asking Bos questions about the data.

**Comment by TracyLinder** [comment]
### AOB Results 8/3/23

- APPROVED to update process description with conditions:
    - Run a one time script to insert a process comment on all existing process code 51212. Comment to be something like _8/20/23 Folder process name changed from Transportation Engineering to Land Review Engineering. 
    - Send Surbhi a link to the data

**Comment by TracyLinder** [comment]
We need to rename the corresponding folder info & review comment doc.

**Comment by TracyLinder** [comment]
### AC Draft

**There are 2 deliverables for this request:**
1. Update the process description _from_ Transportation Engineering Review_ to **_Land Review Engineering_**

**Comment by TracyLinder** [comment]
AC is ready; I'm moving this to ON-Deck. 

@Nadin-Nader I'm putting this on deck for this sprint. I think @Sreelatha-BlazeKannan is already familiar with this request because she did a data pull for it.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP of #13166 submitted. Kindly approve and create task id for the same. 

Commit ID: [5c5c577f80ce](http://coaamandadevops02.austintexas.gov/R5:5c5c577f80ce76f292b6d214593a29d2728f8a1d)

And also, Update scripts to be run against DEV to create a backup for roll back process and update the folderprocess comment as mentioned in card.

Could you please create a Service Now ticket separately for this and assigned to Yuan.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  First part the the DEV deployment had been sent to the DevOps under **SCTASK0351308**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have sent the request for the script to be ran on Dev to the AMANDA DBAs UNDER **SCTASK0351314**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i sent the DB Script TASK (**SCTASK0351314**) to the DevOps team per Jenice

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan got a response from Yuan stating that when he ran the script there were many errors. Please review it. He said the following:

> Please double check the script. It seems that many ';' are missing.

**Comment by Nadin-Nader** [comment]
Update: Waiting on Yuan to re-run the script

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Yuan ran scripts; first DevOps commit also in DEV and Tested the scripts and folderprocess comment update. All looks good. Submitted TEST DP for this. Please review and create task id for the same. And also Need to create a separate service now card to run the scripts in TEST for Yuan. 

DevOps Commit ID: [5c5c577f80ce](http://coaamandadevops02.austintexas.gov/R5:5c5c577f80ce76f292b6d214593a29d2728f8a1d)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has bee sent to the DevOps CM Team and to the CTM DBA teams to be deployed to TEST under the following TASK's:

**DevOps: SCTASK0354638
DBA: SCTASK0354639**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - This request promoted to TEST; and Tested my both DevOps & Database changes and executed the same. All looks good. Ready for UAT

**Comment by Nadin-Nader** [comment]
Tracy will Test with Amanda B's team

**Comment by TracyLinder** [comment]
UAT scheduled for 9/28

**Comment by TracyLinder** [comment]
### UAT with Customers 9/28/23

- [ ] Update the name to Land Development Engineering 
- [ ] Create a ticket for renaming the info tab things
- [ ] Create a ticket to scope Sam's work in residential plan review.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan I updated the AC to reflect the updated process name the customer requested.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV & TEST DP of #13166 submitted. Earlier this was completed and was in test; now the change is to rename again as per user’s request. So, attaching both DEV & TEST DP at a time. Please approve and create task id’s for DEVOPS & DBA to run the scripts as well.

Commit ID: [31461641217a](http://coaamandadevops02.austintexas.gov/R5:31461641217a862fa154ca41869f3c93c3102071)

Note: Need to create a card for Yuan to execute the scripts in DEV & TEST also.

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team and to the DBA Team to be deployed to Dev and TEST under the following TASKS:

**DevOps	- SCTASK0360670
DBA	- SCTASK0360673**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - This is promoted to both DEV & TEST. Tested the same in both DEV & TEST and all looks good. Upon approval this can be promoted to PROD.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been sent to the DevOps Team and to the DBA Team under the following TASKS:
13166 - To PROD
	**DevOps - SCTASK0362220
	DBA - SCTASK0362222**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - All changes are in PROD now; However to run the Update folder process comment script, Yuan requires a service now card#; @Nadin-Nader Could you please create one to execute the below script/procedure in PROD 
CALL AMANDA.FOLDERPROCESS_51212_UPDATE(
);

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have sent this to Yuan again under **SCTASK0363318**

**Comment by Nadin-Nader** [comment]
Still waiting on DBA to deploy scripts

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Completed script execution in PROD. All looks good; Ready for PROD UAT

**Comment by TracyLinder** [comment]
### Update & Closing
- I informed BOZ this is done and asked her to inform the reviewer Patrick.
