### ISSUE TITLE
Finalize executive approval for  transition workshops

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13179]
Present updated TPW merger transition workshop proposal to executives for feedback and approval.

**Detailed workshop description:**
https://docs.google.com/document/d/12CIqIJSUK6L4Px2hCfeNMhUaIScM0pIb1iUU0Dyj-I0/edit?usp=drive_link

**Workshop run of show and activity description**
https://docs.google.com/drawings/d/1GDLrg2O1TD0y3-mNIhMcnkjfEKEFSEzReSVofJk8D1s/edit?usp=drive_link

**Comment by michael-santulli** [comment]
Presented the attached documents to the executive team on Monday, 8/7. Richard and the team liked the workshop agenda and proposed timeline of late September - early October.
