### ISSUE TITLE
Fix workgroup params navigation

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#13189]
[`https://austinmobility.io/projects?status=in_progress&workgroup=Finance`](https://austinmobility.io/projects?status=in_progress&workgroup=Finance) shows all of the projects, not just the projects belonging to the finance Workgroup. 

Expectation: to navigate to this URL and see only the Finance projects in progress

> The DTS Website ["Projects" page](https://austinmobility.io/projects) already uses multiple URL parameters: When you select a workgroup using the dropdown, it updates the URL and shows a subset of projects. 
> 
> _But_ if you go to that workgroup-specific URL, e.g. [`https://austinmobility.io/projects?status=in_progress&workgroup=Finance`](https://austinmobility.io/projects?status=in_progress&workgroup=Finance), it loads all projects. 
> 
> 

_Originally posted by @amenity in https://github.com/cityofaustin/atd-data-tech/issues/5581#issuecomment-1650279545_

**Comment by johnclary** [comment]
at a glance, it seems it seems that there are two problems going on.

the first problem is that the router's search query is `undefined`  [here](https://github.com/cityofaustin/atd-product/blob/611719597ac3fd9e44e8e2fc3606425054866d78/components/projectsView/ProjectsList.js#L77) the first few times the component renders. so the effect that fires to set filter state based on the URL params is always falling back to the default state. it would be best to turn to the nextjs docs on this, but i'm pretty sure the next `router` has can be configured with a loading state that we could use to block rendering of the proejct list component until we know for certain if the URL has a query string or not. 


the second problem (i think( is that [this effect ](https://github.com/cityofaustin/atd-product/blob/611719597ac3fd9e44e8e2fc3606425054866d78/components/projectsView/ProjectFilters.js#L69) is overwriting the URL search params in conflict with whatever needs to be initially parsed when the page loads. my suggestion to fix this is probably to stop using `useEffect` to keep the current URL params in sync with filter state, and instead do this via event handlers that fire when buttons are clicked.
