### ISSUE TITLE
[Signs and Markings] Changing Contractor "GIS QA" page to see "Approved" status rather than "Closed"

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#13194]
Kati 
SMD

Emailed me 8/2
>While Christina is out I wanted to check in about the contractor work order GIS. We chatted in the last DTS/SMD meeting about how the APPROVED status wasn’t needed and how it’s holding up the GIS QA process. There are currently 121 work orders in an approved status that need GIS but GIS can’t see them since that page only sees CLOSED. 

>I had been going in and manually changing the status of each one but I was out for 4 days for a funeral and I really don’t want to do 121+ manually now haha. Is there a better way we can address this need as your team is working on the discussed changes?

>Between now and the end of the FY, our contractors are going to be doing a ton of work and I don’t want the GIS to get more backlogged as these numbers need to be reflected in our performance measures for end of year reporting.

## Last SMD Prioritization meeting
We talked about removing the status "Approved" and having it go from "Final Review" to "Closed". GIS QA could then perform QA on "Closed" work orders. 

Situation: 
Kati has been manually closing tickets bc no one else was. She would out of town for a few days and the "Approved" queue went up to `121 records`. 

### Temporary Fix
- Changed GIS QA page to see "Approved" rather than "Closed" work orders

### Permanent Fix
- Remove "Approved Status" all together.

**Comment by dianamartin** [comment]
# 8/2

Changed this filter
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/355070ac-927d-4e41-8eaa-6f335a6b2138)

**Comment by susannegov** [comment]
# To do
- [ ] Change Record Rule 
   - [ ] `/pages/scene_1323/views/view_3321/form/rules/record`

**Comment by susannegov** [comment]
Confirmed with SMD that the emails are being sent and can close this issue out

**Comment by ChristinaTremel** [comment]
## 8/17

- Susanne showed these changes during the SMD Sprint Review
- Showed that `Approved` status doesn't exist and instead JM will click `Approve/Close` button to close out the work order
- JM has used this process and it's working as it should
- Also showed the GIS QA page and how it's filtered by work orders in `CLOSED` status with GIS QA `No`
