### ISSUE TITLE
Backfill Supervisor & Division fields for HR Banner Employee Information

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#13201]
Jennifer W.
HR

- On 7/27 we received from HRD IT an updated version of the Legacy ATD & PWD Employee API.
- Confirmed on 8/2 that the data feed was working as expected
- Showed Jennifer that we have the data in the HR application

## Backfilling Data 
- Data from Banner ETL doesn't have supervisor information  - `761 records` created from `7/28/2023`
  - assuming this is from the new update

### Filters
- Blank Supervisors - `800 records`
- Blank Divisions - `763 records`
 
### New Divisions (legacy PWD)
  - [ ] Banner Division Name - keyword: `Pavement` - `64 records`
  - [ ] Banner Division Name - keyword: `District` - `59 records`
  - [ ] Banner Division Name - keyword: `Sidewalk` - `11 records`
  - [ ] Banner Division Name - keyword: `Community` - `35 records`
  - [ ] Banner Division Name - keyword: `City` - `29 records`  
  - [ ] Banner Division Name - keyword: `Utilities` - `76 records`

### Non TPW Divisions (legacy PWD)
- [ ] Banner Division Name - keyword: `Construction Management` 
- [ ] Banner Division Name - keyword: `Project Management`
- [ ] Banner Division Name - keyword: `Engineering Services` (ESD) 
- [ ] Banner Division Name - keyword: `Project Delivery`?

**Comment by dianamartin** [comment]
# 8/3
- [ ] Check on CDS Department after Banner updates occur
- [ ] [Spreadsheet file path](\coacd.org\dfs\ATD\ATD\ATD_GIS\02_ENT_APPLICATIONS\app_Human_Resources_Manager)

**Comment by dianamartin** [comment]
# 8/24
- Started working through this and doing QA/QC while doing safety training and ethics training

## Backfilling Data 
- Data from Banner ETL doesn't have supervisor information  - `761 records` created from `7/28/2023`
  - assuming this is from the new update

### Filters
- Blank Supervisors - ~`800 records`~ - is `453 records` = QC'd `347 records` on 8/24
- Blank Divisions - ~`763 records`~ - is `434 records` =  QC'd `329 records` on 8/24
 
### New Divisions (legacy PWD)
  - [ ] Banner Division Name - keyword: `Pavement` - `64 records`
    - [ ] Division blank - `62 records`
    - [ ] Supervisor is blank - `65 records`
  - [ ] Banner Division Name - keyword: `District` - `59 records`
    - [ ] Division is blank - `0 records`
    - [ ] Supervisor is blank - `0 records`
  - [ ] Banner Division Name - keyword: `Sidewalk` - `11 records`
    - [ ] Division is blank - `11 records`
    - [ ] Supervisor is blank - `11 records`
  - [ ] Banner Division Name - keyword: `Community` - `35 records`
    - [ ] Division is blank - `0 records`
    - [ ] Supervisor is blank  - `0 records`
  - [ ] Banner Division Name - keyword: `City` - `29 records`  
    - [ ] Division is blank  - `0 records`
    - [ ] Supervisor is blank - `0 records`
  - [ ] Banner Division Name - keyword: `Utilities` - `76 records`
    - [ ] Division is blank - `81 records`
    - [ ] Supervisor is blank - `81 records`

### Non TPW Divisions (legacy PWD)
- [ ] Banner Division Name - keyword: `Construction Management` 
- [ ] Banner Division Name - keyword: `Project Management`
- [ ] Banner Division Name - keyword: `Engineering Services` (ESD) 
- [ ] Banner Division Name - keyword: `Project Delivery`?

**Comment by dianamartin** [comment]
# 8/24
@ChristinaTremel FYI - half way there, hope it doesn't revert..

**Comment by ChristinaTremel** [comment]
### New Divisions (legacy PWD)
  - [x] Banner Division Name - keyword: `Pavement` - `66 records`
    - [ ] QA/QCed and filled in Supervisor & Division for 64 out of 66 records
    - [ ] Still remaining: Division and Supervisor is blank - `2 records`
  - [x] Banner Division Name - keyword: `Sidewalk` - `11 records`
    - QA/QCed and filled in Supervisor & Division for 10 out of 11 records
    - Still remaining: Division and Supervisor is blank - `1 records`
  - [x] Banner Division Name - keyword: `Utilities` - `82 records`
    - QA/QCed and filled in Supervisor & Division for 82 out of 82 records
    - Still remaining: Division and Supervisor is blank - `0 records`

**Comment by ChristinaTremel** [comment]
@dianamartin are we okay to close this issue out?

**Comment by dianamartin** [comment]
@ChristinaTremel I think it's been done, but maybe new ones need to be backfilled by HR

**Comment by dianamartin** [comment]
Closing this issues since Jennifer's team has been handling the Supervisor -- Direct Report assignments.
