### ISSUE TITLE
IT Support:  Jim D issues with finding the H drive on PC.

### ISSUE THREAD

**Issue by JBStrange** [cityofaustin/atd-data-tech#13206]
ATD-C5V3YY2-N1 Jim D Need help finding the H drive on their PC.

Needed help finding the H drive on their PC.

Explained that there is no more H drive that it is now in the onedrive on all government PC so setup on the End Users PC
and in a folder called Home.

**Comment by scottreedy** [comment]
Mapped drive from batch file
