### ISSUE TITLE
IT Support: Kyalin T iphone was not working properly.

### ISSUE THREAD

**Issue by JBStrange** [cityofaustin/atd-data-tech#13204]
Apple Phone Kaylin T needed help getting phone to sync.

The phone app was not syncing so deleted and readded the account 

After deleting and readding to the Iphone outlook started to sync once again.

**Comment by scottreedy** [comment]
Apple Phone Kaylin T needed help getting phone to sync.

The phone app was not syncing so deleted and readded the account

After deleting and readding to the Iphone outlook started to sync once again.
