### ISSUE TITLE
Mitigation Location Data Export

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13228]
@ChrispinP export data related to the 22 records without a mitigation location

**Comment by TracyLinder** [comment]
@ChrispinP If you want to pull this into the current sprint since it's so small, you can. I'm ok with it waiting until the next sprint.

**Comment by ChrispinP** [comment]
Exported date, cleaned up spreadsheet and emailed. Complete, pending any further action.

**Comment by ChrispinP** [comment]
closing
