### ISSUE TITLE
[DevOps] Terminate Airflow v1

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#13239]
We [no longer have DAGs running](https://github.com/cityofaustin/atd-data-tech/issues/12860) on Airflow v1. It's time to shut it down.

**Comment by frankhereford** [comment]
* [x] On data02, make sure compose file is set to `restart: never` 
* [x] `docker-compose -f docker-compose-localexecutor.yml stop`
* [x] Comment out airflow related cronjobs on data02
* [x] Remove CNAME route53 record for `airflow-v1.austinmobility.io`

I think that's it! We can call Airflow V2 just "Airflow" now. 🎉
