### ISSUE TITLE
Understand and fix the VZ ETL `update_cr3_location` which fails @ 3:00 AM Central regularly

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#13249]
Please see these airflow events for `vz_reassociate_missing_locations`:

* [Aug 4, 2023](https://airflow.austinmobility.io/log?execution_date=2023-08-03T08%3A00%3A00%2B00%3A00&task_id=update_cr3_locations&dag_id=vz_reassociate_missing_locations&map_index=-1)
* [Aug 5, 2023](https://airflow.austinmobility.io/log?execution_date=2023-08-04T08%3A00%3A00%2B00%3A00&task_id=update_cr3_locations&dag_id=vz_reassociate_missing_locations&map_index=-1)
* [Aug 6, 2023](https://airflow.austinmobility.io/log?execution_date=2023-08-05T08%3A00%3A00%2B00%3A00&task_id=update_cr3_locations&dag_id=vz_reassociate_missing_locations&map_index=-1)
* [Aug 7, 2023](https://airflow.austinmobility.io/log?execution_date=2023-08-06T08%3A00%3A00%2B00%3A00&task_id=update_cr3_locations&dag_id=vz_reassociate_missing_locations&map_index=-1)

This issue is to track the discovery and work to fix the cause of this issue.

While the fact this ETL fails at this time isn't itself a huge problem, there is an underlying cause which is not understood. It's far from ideal for our service to go down without us understanding why and deciding to do that, so I'd like to use this regularly, self-reproducing problem to gain insight and control over what is happening, if possible.

Initial work could be to figure out how to log what's going on on the `postgres` & `graphql-engine` side of things, which will align nicely to working on #13248 at the same time

**Comment by frankhereford** [comment]
This is one of the new airflow ETLs. You can see when I installed it on airflow 2 in green and then it failing since.

<img width="333" alt="image" src="https://github.com/cityofaustin/atd-data-tech/assets/3653206/3c9573da-a672-46fc-b402-7e40e2ba7838">

**Comment by patrickm02L** [comment]
This ETLs has been failing for a while - Reference #11302

**Comment by patrickm02L** [comment]
This DAG has been turned off #11302 and will be deleted with #13190
