### ISSUE TITLE
Configure AWS RDS postgres databases to log long running queries

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#13248]
This is very helpful information to have when profiling an application or debugging performance of the RDS cluster.

These instructions seem like the likely best route: https://catalog.us-east-1.prod.workshops.aws/workshops/31babd91-aa9a-4415-8ebf-ce0a6556a216/en-US/postgresql-logs/enable-slow-query-log

This behavior should be configured for the VZ & Moped RDS clusters.

**Comment by patrickm02L** [comment]
part of #11895

**Comment by frankhereford** [comment]
This issue will be completed as part of the transition to the AWS Aurora solution for the VZDB. Enhanced monitoring is going to be enabled on that service, which enables the AWS dashboard providing insight into the performance of the database, including the logging of long running queries.

**Comment by frankhereford** [comment]
Closed as part of #11895.
