### ISSUE TITLE
[TCP Conflict/Shared Review Cycles] Launch Prep and Go-Live Checklists

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#13246]
# Prep Steps 
## Coordination
- [x]  Plan notice of downtime on the [New Request page](https://builder.knack.com/atd/row/pages/scene_173), to be shown during the launch window 
**`Monday, August 14, 3pm -`**
- [x] Coordinate with Tracy (and ROW) on the above message 

## Intake Setup
- [x] **Build** Shadow Views (new intake views to be hidden until launch) where possible and make a detailed list of launch build**
     - [x] **New CSWZ Request Landing page**
          🚀 Change verbiage and hide start button during launch
          - [x] Record Rules 📁  - ✅  Created and Modified Timestamps
          ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/89e66f52-26e5-4299-a84f-8f70d8a4cd99)
     - [x] **CSWZ Applicant Information page**
          - [x] Add new record rule items now (minimal) | ✅  Modified Timestamp 
          ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/db8d0bc2-0738-471a-8981-06cd122afe28)
     - [x] 🚀 **CSWZ Conflicting Party Information page**
          - [ ] ~~Build a new hidden view to upgrade - the Submission is created here~~
          - [ ] ~~Created [a new form](https://builder.knack.com/atd/row/pages/scene_184/views/view_576/form) (hidden for now with page rule)~~ ➡️ Need to create this during launch to avoid duplication of subsequent pages
               - Configure rules model to be completed during launch window 
               ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/71c00544-0074-455c-9afa-371f0a8ce179)
     - [x] **CSWZ Attachments page**
          - [x] New Add Attachment form (hidden until launch)
               - existing [Add Attachment form ](https://builder.knack.com/atd/row/pages/scene_185/views/view_398/form) View 398
               - [x] Create a new Add Attachment form and hide (View 595) 
          - [x] New Attachments Table grid (hidden until launch; View 597)
          🚀  Unhide these and move them up; hide the previous Add Attachment and Attachments Table views
     - [x] **Finalize CSWZ Request** 
          - [x] Add new hidden Attachments table (previous table View 403); new table View 
          🚀 Unhide new Attachments table at launch and hide previous Attachments table 
     - [x] **Edit Information** 
          - [x] No changes - make sure Modified details are captured  
     - [x] **Edit Attachments**  
          - [x] Add new hidden Add Attachment form [Add to Submission] (View 598)
          - existing form View 411
          - [x] Add new hidden Attachments table (View 599)
          - existing table View 
          🚀 Unhide new form and table and hide previous versions 
     - [x] **CSWZ Submittal Confirmation** - no changes

## Back Office Setup 
- [x] Add filters to Cycle Reviews table 
- [x] Add info to Cycle Reviews table
- [x] Build [Advanced Search for Submissions ](https://atd.knack.com/row#tcp-cswz/advanced-search/submissions-advanced-search/advanced-search/submissions-advanced-search)

**Comment by KaroEngstrom** [comment]
## Launch List 
- [New CSWZ Request Landing page](https://builder.knack.com/atd/row/pages/scene_173)
     - Can't hide a view
     - [ ] Add notice of downtime in the rich text view above the form 
     - [ ] Add Submit Rule to cycle back to this initial page with a note (grey)    
     ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/db48bc9e-5781-419b-b26d-c6a98afaf331)

     
     
     
### Final Step 
- [New CSWZ Request Landing page](https://builder.knack.com/atd/row/pages/scene_173)
     - [ ] Remove downtime information from the rich text view 
     - [ ] Remove blocker submit rule to enable updated Request intake

**Comment by TracyLinder** [comment]
### Customer Portal Down-Time Verbiage

`The TCP Conflict Review and Shared TCP Request is currently down for maintenance. Please try again in a few hours.`

**Place verbiage in 2 places:**
1. [Here](https://atd.knack.com/row#customer-portal/services/conflict-shared-request/), the 'landing page'
2. [Here](https://atd.knack.com/row#new-cswz/), the 'start page'

**Comment by KaroEngstrom** [comment]
## Mon 8/14/23 CSWZ Update Go-Live
- steps in the launch list above completed successfully
- submission form for CSWZ was unavailable to the public 3:03pm-3:54pm 
- I ran a test record in the new portal and it passed; I deleted the record 
FYI @TracyLinder
