### ISSUE TITLE
Static page for ATD internal support resources

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1326]
Build a simple static page at **help.austinmobility.io** to serve as a landing page for internal ATD service resources. 

Once approved, the page can match [this doc](https://docs.google.com/document/d/1RBde15-e5X_dIGYq6Eqtx6DuhJJvzY7dc44NWIAZoiA/edit).

**Comment by amenity** [comment]
@TracyLinder @johnclary, can you give approval/feedback on 
- [This proposed content](https://docs.google.com/document/d/1RBde15-e5X_dIGYq6Eqtx6DuhJJvzY7dc44NWIAZoiA/edit#) 
- The URL `help.austinmobility.io`

**Comment by johnclary** [comment]
@TracyLinder @amenity @JaceDeloney @mateoclarke I think we need a link to a CTM/Service Now form, with an explanation of why you would reach out to them vs DTS.

I don't really understand why we're linking to the Finance & Purchasing System. Should we include a full catalog of ATD business apps? AMD, Signs & Markings, VZA, VZE, E-Capris, Controller's Office, etc? This feels v similar to the ATD sharepoint site(s) Diana has created.

I think it's fine to go with the content we have now, with the addition of a link to Service Now, and then continue to discuss and refine how we direct ATD staff to support resources.

**Comment by amenity** [comment]
> This feels v similar to the ATD sharepoint site(s) Diana has created.
Yup. 😬That's why I ended up taking ServiceNow off of the list and calling it "ATD **Internal** Support Resources."

My understanding is that we were creating a one-stop page for forms that ATD staff should use to ask for support from other ATD divisions. Since Finance, PIO, and DTS would (I'm assuming) all benefit from the dept following these processes rather than adhoc phone calls and emails?

**Comment by mateoclarke** [comment]
https://help.austinmobility.io/ is live. May we close this issue and take discussions about enhancements/edit and new requests to new issues?
