### ISSUE TITLE
IT Support: Roy F. need help setting up Adobe Pro.

### ISSUE THREAD

**Issue by JBStrange** [cityofaustin/atd-data-tech#13263]
ATD-J6TZN13-N1 Roy F. need to have Adobe Pro loaded for his job.

After speaking with the manager helped End User load the software 

Showed the End User how to login and create password and find it on the PC.

**Comment by scottreedy** [comment]
TD-J6TZN13-N1 Roy F. need to have Adobe Pro loaded for his job.

After speaking with the manager helped End User load the software

Showed the End User how to login and create password and find it on the PC.
