### ISSUE TITLE
Missing UC Report in the ATD Report menu; Report 99020 - AULCC Report is not in the ATD Menu (LP) - (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#13272]
Missing UC Report in the ATD Report menu; Report 99020 - AULCC Report is not in the ATD Menu

The AULCC Report is not in the AMANDA ATD report menu (Menu> Report> ATD). 

Name of Report: AULCC Repot (99020)
Name of the report file: 99020_AULCC_Report

(Could not attach report )

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/fcd5d338-90fc-4081-b97e-436902e6ecaa)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader The report is available under ATD menu , Ready for UAT on Test

**Comment by Nadin-Nader** [comment]
Asked Jaclyn to UAT this on TEST. Waiting on Response

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been approved for PROD deployment

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Prod, Ready for UAT

**Comment by Nadin-Nader** [comment]
I have let Jaclyn know that this is on PROD. Waiting on UAT response

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Jaclyn said it is approved but the Parameters are backwards. She needs the start date to be first and the End date to be second

**Comment by Nadin-Nader** [comment]
Asked Jaclyn to UAT this on PROD. Waiting on Response

**Comment by Nadin-Nader** [comment]
Report is on PROD. closing
