### ISSUE TITLE
BUG: EX Folder - Portal Attachment Feature

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1328]
### Reported by Paloma on 1/30/2020:

Hey Tracy,

We just realized that several EX subtypes are not able to add attachments after they’ve submitted their AB+C Portal application.

Here’s the list of the EX subtypes that are NOT working:
Austin Energy Chilled Water, Austin Energy Electric, Austin Transportation, Watershed Protection Storm Drain

We previously thought this was only an issue with ATD subtypes but it turns out AE is impacted as well and they’re a high-volume customer.  We tried to figure out when this might have broken but it’s hard to say.  The incident email that’s attached could have been the trigger or perhaps it’s been broken since we first identified the ATD issue (see the AB+C Portal attachment).

Let me know if I should submit this as an AMANDA help ticket!

**Comment by TracyLinder** [comment]
# Troubleshooting 

**Test Folders:**
- 2020-000218 EX | Internet Pending
    - Private Contractor |  ✅
    - AE Chilled Water | ❌
    - AE Electric | ❌
    - ATD | ❌
    - City Utility AWU/Storm | ✅
    - Franchised Utility | ✅
    - Public Works | ✅
    - Street/Bridge | ✅
    - Watershed Protection | ❌

**Comment by amenity** [comment]
Paloma has now submitted a help ticket to the CTM service desk.
