### ISSUE TITLE
Release VZ v1.36.0 - Onion Creek Parkway

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13292]
### Prior to Release
- [x] Schedule release party - @patrickm02L 
- [ ] Advise users of downtime - @patrickm02L
- [ ] Do testing - we'll set this up for next release
- [x] Propose + vote on release names - @patrickm02L 
- [x] Create a [release](https://github.com/cityofaustin/atd-vz-data/pull/1278) - @mddilley
- [x] Refine [release notes](https://github.com/cityofaustin/atd-vz-data/releases) @patrickm02L 

### Release/Deployment Steps
- [x] Check with Rose about migrations for [#1267](https://github.com/cityofaustin/atd-vz-data/pull/1267) - @mddilley 
- [x] [snap database in RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_CreateSnapshot.html) - @mddilley 
- [x] graphql-engine version bumps (releases & tags) - @mddilley 
  - [x] Local dev to v2.32.0 [release notes](https://github.com/hasura/graphql-engine/releases) (done when upgrading Hasura instance)
  - [x] staging task definition to v2.32.0 with T.D. 22 (done when upgrading Hasura instance)
  - [x] production ECS task definition to v2.32.0 with T.D. 17 (done when upgrading Hasura instance)
- [x] merge to prod - @patrickm02L 

### Post Release
- [x] Bump VZ **staging** version to `v1.37.0` and VZ production to `v1.36.0`- @mddilley 
- [x] Send out release notes - @patrickm02L 

[Release Management Process gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/product-ops/release-management-process)

**Comment by patrickm02L** [comment]
VZ v.1.35.0 [Debrief Doc](https://docs.google.com/document/d/1Bz-lhmaqOGutw341JGTx3TX4qhLuxVz_UH1rMBAugqc/edit#heading=h.hhbe0gdj2sxf)

**Comment by mddilley** [comment]
For next time around, if there are any migrations, someone manually:
- Prior to the release party:
    - Checks out the release branch locally
    - Runs `hasura migrate status` on the staging Hasura instance to make sure all migrations are applied
- During the release party:
    - Runs `hasura migrate status` on the production Hasura instance to check where we are at there
    - Runs `hasura migrate apply` and then `hasura metadata apply` on the production endpoint

If we have time in the launch party, we could discuss the process that a dev would go through when merging an approvaed PR with a migration to `master` branch (staging). That might go like:
- Pull `master` branch to make sure you have the latest migrations
- Replicate using the latest production data dump
- Run `hasura migrate apply` and then `hasura metadata apply` on the local endpoint to check for any errors or conflicts
- Merge PR branch and then run `hasura migrate apply` and `hasura metadata apply` on the staging endpoint

**Comment by patrickm02L** [comment]
For this release, after we hit merge we discovered that the webhooks in github were degraded, so manually trigger CircleCI and Netlify (VZV and VZE) to get the code into production. All of the other deploy steps went well, which means we'll be in good shape for the next release.

**Comment by johnclary** [comment]
@mddilley your proposed flow for the next release looks great to me. 

and the plan is to manually apply migrations + metadata to staging whenever a PR is merged? one thing to consider there is that when developers `hasura migrate status` they can also check visually to make sure that the migrations they are going to apply are chronologically after the existing migrations already applied on the staging DB.  if not, that's an opportunity to re-number the migrations to ensure the migrations will be applied in the same order in prod.

**Comment by mddilley** [comment]
@johnclary thanks for the feedback! yes, the plan is to manually apply migrations whenever a PR is merged (and eventually have CI handle that like it does in Moped). That is a really good point, and TIL that the Hasura CLI will always list migrations in chronological order no matter what the status is. 🙏 Did a quick test on my local DB.

<img width="969" alt="Screenshot 2023-08-29 at 4 40 05 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/37249039/9a23a630-99aa-4a67-afbc-dc83ebad2bde">

**Comment by johnclary** [comment]
Nice!
