### ISSUE TITLE
Iterate on digital Confidentiality Form

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1330]
@dianamartin has [already digitized the confidentiality agreement using Knack](https://github.com/cityofaustin/atd-data-tech/issues/1193). If we move forward with Knack, we need to optimize the signing experience #1197. 

HR likes the idea of having a dedicated tablet for each HR staff person to collect signatures on. 

We learned, however, that we get PIRs that would require us to produce a PDF of a signed confidentiality form. Jennifer says that they would want to have these automatically collected in the Hiring Package rather than produced on-demand if there is a PIR. 

Given this, is Knack still the best solution? We would need a way for HR to easily get all forms as PDFs. Is there possibly an Acrobat or O365 option we should consider?

**Comment by dianamartin** [comment]
@amenity This is done.

I created a details page and then copied over the form elements and inserted the form details back in and added a print link and have it open in a modal pop-up so it looks like a print preview. 

![image](https://user-images.githubusercontent.com/21112975/73569497-2cdcac80-4430-11ea-9c0c-eb65987c42cf.png)

**Comment by amenity** [comment]
Beautiful. ✨
<img width="985" alt="Screen Shot 2020-01-31 at 3 52 40 PM" src="https://user-images.githubusercontent.com/1463708/73617866-a3bca580-45e8-11ea-88a2-9b87bb7470f6.png">
