### ISSUE TITLE
[ROW / AMANDA] Investigate Voided COS Fees that did not update to Voided in Knack

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#13332]
Melissa from Finance mentions there are a couple ROW COS fees that show as voided in AMANDA but have not updated in Knack to also be voided.

Need to determine what may have caused this issue / data discrepancy for fees: 13245695 and 13245694

Is there something unique about these records that caused a failure with the integration sync?

**Comment by TracyLinder** [comment]
Tracy & Chrispin will meet on Monday 8/21 to begin troubleshooting.

**Comment by TracyLinder** [comment]
### Convo w/ Dev/Prod Sync 8/16/23

- John suggests DEV check the ETL - it could be broken. FYI @chiaberry 
- I'll let Chia know after/during troubleshooting if we need DEV help.

**Comment by TracyLinder** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/0421b68d-cb01-4ff4-a05e-d13162c3b166)

**Comment by TracyLinder** [comment]
### Notes 8/21/23

- Chia said this has failed twice now, on 8/9 and 8/11 for 'timed out' and 'service unavailable'
- The AMANDA data looks fine 

**COS Data Info:**
The common ID is the permit # column and in data it is record serial number. For this example it is 12685780
- There are two voids on this common permit# - one is showing the void status and the other isn't
    - Working: payment# 7542345
    - Not Working: payment# 7542348 


@chiaberry will investigate.

**Comment by TracyLinder** [comment]
### Dev & Product Sync

- We need to identify a better unique key. It will have to be a combo of accountbillfee.feersn & payment number. 
- Chia will remove the duplicate  accountpayment.paymentnumber from [this query](https://github.com/cityofaustin/atd-cost-of-service-reporting/blob/production/queries/fees.sql)
- Tracy will ask AMANDA dev to review the query for any potential issues 
- DTS DEV will need to @johnclary will finish this below.

**Comment by TracyLinder** [comment]
I'm meeting with Priya (AMANDA DEV) tomorrow 8/31 to review the query.

**Comment by TracyLinder** [comment]
@chiaberry after you remove the duplicate accountpayment.paymentnumber from the query, can you run it again to see if we get less than 4 rows?

**Comment by chiaberry** [comment]
@TracyLinder I removed the duplicate from the query, but am still getting 4 rows, two of each

**Comment by TracyLinder** [comment]
### AMANDA-DEV Query Feedback

@chiaberry Our dev was able to remove the duplicates. See updated query below. There's also a short recording of her explanation [here](https://cityofaustin-my.sharepoint.com/:v:/g/personal/tracy_linder_austintexas_gov/EXSyN9rIGE5KhHXfvO0O5awB7LJdCHpGAjwusISi2i2eqw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0RpcmVjdCJ9fQ&e=euZy8w). 




----

SELECT DISTINCT folder.folderrsn,
       folder.foldername,
       folder.folderdescription,
       folder.folderyear || ' ' || folder.foldersequence || ' ' || folder.foldertype as folder_id,
       To_char(folder.indate, 'YYYY-MM-DD')              AS INDATE,
       folder.foldertype,
       validsub.subdesc,
       validwork.workcode,
       validwork.workdesc,
       (SELECT infovalue
        FROM   folderinfo
        WHERE  folderinfo.folderrsn = accountbillfee.folderrsn
               AND folderinfo.infocode = 90005)          work_order,
       (SELECT infovalue
        FROM   folderinfo
        WHERE  folderinfo.folderrsn = accountbillfee.folderrsn
               AND folderinfo.infocode = 75072)          subproject_id,
       (SELECT infovalue
        FROM   folderinfo
        WHERE  folderinfo.folderrsn = accountbillfee.folderrsn
               AND folderinfo.infocode = 76350)          cip_id_number,
       (SELECT infovalue
        FROM   folderinfo
        WHERE  folderinfo.folderrsn = accountbillfee.folderrsn
               AND folderinfo.infocode = 76360)          cip_project_manager,
        (SELECT infovalue
        FROM   folderinfo
        WHERE  folderinfo.folderrsn = accountbillfee.folderrsn
               AND folderinfo.infocode = 75074)          partner_dept_name,
       people.namefirst,
       people.namelast,
       people.organizationname,
       people.emailaddress,
       folderpeople.folderrsn,
       people.peoplersn,
       validaccountfee.glaccountnumber,
       validaccountfee.feedesc,
       accountbillfee.accountbillfeersn,
       accountbillfee.feecode,
       accountbillfee.feeamount,
       accountbillfee.billnumber,
       accountbillfee.feecomment,
       accountbill.billamount,
       accountpayment.paymentnumber,
       accountpayment.paymentamount,
       accountpayment.paymenttype,
       --accountpayment.paymentnumber,
       To_char(accountpayment.paymentdate, 'YYYY-MM-DD') AS paymentdate,
       (SELECT infovalue
        FROM   folderinfo
        WHERE  folderinfo.folderrsn = folder.folderrsn
               AND folderinfo.infocode = 90001)          fund,
       (SELECT infovalue
        FROM   folderinfo
        WHERE  folderinfo.folderrsn = folder.folderrsn
               AND folderinfo.infocode = 90002)          dept,
       (SELECT infovalue
        FROM   folderinfo
        WHERE  folderinfo.folderrsn = folder.folderrsn
               AND folderinfo.infocode = 90003)          unit,
       (SELECT infovalue
        FROM   folderinfo
        WHERE  folderinfo.folderrsn = folder.folderrsn
               AND folderinfo.infocode = 90004)          object,
       accountpayment.locationcode,
       accountpayment.stampuser
       FROM   accountbillfee
       JOIN validaccountfee
         ON ( accountbillfee.feecode = validaccountfee.feecode )
       JOIN folder
         ON ( accountbillfee.folderrsn = folder.folderrsn )
       JOIN accountbill
         ON ( accountbillfee.billnumber = accountbill.billnumber )
       JOIN accountpaymentdetail
         ON ( accountpaymentdetail.billnumber = accountbill.billnumber )
       JOIN accountpayment
         ON ( accountpayment.paymentnumber =
            accountpaymentdetail.paymentnumber )
       left outer JOIN validsub
         ON ( folder.subcode = validsub.subcode )
       left outer JOIN validwork
         ON ( folder.workcode = validwork.workcode )
       left outer JOIN folderpeople
         ON ( folder.folderrsn = folderpeople.folderrsn
              AND folderpeople.peoplecode = 1 )
       left outer JOIN people
         ON ( folderpeople.peoplersn = people.peoplersn )
WHERE  accountpayment.voidflag = 'N'
       AND accountpayment.paymenttype = 'COS'
       AND accountpayment.paymentdate > To_date('09/30/2021', 'mm/dd/yyyy')

**Comment by chiaberry** [comment]
@TracyLinder that's great! thank you

**Comment by TracyLinder** [comment]
### Dev/Prod Syn 9/6/23
- PR in branch... que?
- How to update the script for unique key/ID
    - It's the combination of feersn and paymentrsn. 
- KNACK updates necessary? --- Apps need to be aware they'll be mapping the imports to the Combined ID instead of the feersn
    - Create a new column for **Combined ID**

**Comment by TracyLinder** [comment]
### Resolution

The unique ID we were using for each row (feersn) is not unique when multiple payments are applied to the fee. This was causing duplicate results and the script couldn't apply the data updates. We will be adding a new unique id which will be a combination of the feersn and payment number. Work will be performed on #13712.

**Comment by johnclary** [comment]
@TracyLinder plz tell your colleague their updated script is faster / better / harder / stronger 🙌 

@ChrispinP thanks for setting up the combined ID field. heads up i replaced the `-` with `_` and removed the text formula + rules. we will set this ID via the Python script.

**Comment by ChrispinP** [comment]
@johnclary Thanks John. Should we have a process on what to do if records ever come into Knack without a Combined ID?

**Comment by johnclary** [comment]
@ChrispinP good call. I updated the Combined ID field settings so that it is required and must be unique. The script will fail and the dev team will get an error alert we try to create a row that fails that validation.


So I think y'all are clear to resume your normal export import process—but @TracyLinder we need to make sure whoever in finance who does the export is aware that this new column is required/precious.

And @ChrispinP obvi y'all will need to match on the combined ID column now when you do your import.
