### ISSUE TITLE
Explore how to bring together lots of data from different places

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#13330]
## Description

We need examples of a good data system that: 
- Brings together lots of different data from different places
- Standardizes the data so that it can be sorted, tracked, compared, and analyzed
- Has levels of data or a reporting hierarchy
- Uses data dashboards to make large, complex datasets easier to visualize, sort, compare, and analyze
- Communicates data so it's easy to understand and act upon

## Objective

The vision of Dash is to centralize the department's data and reporting in one place so that we can track, compare, analyze, and adjust our work toward important goals. The dashboards will be a visual representation of the overall health of the department, highlighting key metrics and offering a standardized format to represent various data across work groups. 

Dash will present data in various levels. The highest level is across the entire department and should focus on:
- Service delivery to residents - CSRs (customer service request)
- Increasing efficiencies 
- Maps/geo data

Another level to the data might be service area focused or it might be more focused on goals. And then even deeper is data at the division level. We want to link to data so the viewer can go down the rabbit hole wherever it allows.

The audience for the dashboard includes many people, from TPW staff, managers, and executives to city council members, Austin residents, and anyone who wants to see what TPW is working on.

## Deliverable

- Add good examples of data dashboards to the [Dash miro board](https://miro.com/app/board/uXjVM1Z5trE=/)

**Comment by amenity** [comment]
This is covered by the approaches we're taking, e.g. https://github.com/cityofaustin/atd-data-tech/issues/15228
