### ISSUE TITLE
Using Knack objects in Power BI to publish embedded reports

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#13331]
# How To Connect to Knack Records from Excel & Power BI
Article from 2017 describing how to accomplish this: https://mgr.medium.com/querying-a-knack-object-from-excel-8f2b7163d81b
- [x] Work with @ChrispinP on defining what objects in knack need to be used for regulation PDF
- [x] After knack object is connected, publish in Power Bi Service (Online) and setup automatic refresh daily (every hour?)
- [ ] Embed Power BI content (report or paginated report) on a knack page and see how it looks

Useful for Reporting pages since the Knack reports view is somewhat limited and requires a lot of backend fields to act as workarounds to do customization which is not ideal

**Comment by ChrispinP** [comment]
I've created the API Views to pull the data for the two objects:

- Object 7 : Regulation Documents
- Object 6 : Approved Regulations

API Views can be found here: https://atd.knack.com/traffic-register#api-views/

You can publish the datasource to the 'DTS Paginated Reports' Workspace

**Comment by susannegov** [comment]
# Process
- Get the table view you wish to get it from
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/cb0e9487-2219-4187-b3d9-d5909de723de)
- Set rows limit 
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/79a83c09-1f9c-4024-a226-bd94da2d0b1a)

**Comment by susannegov** [comment]
# Notes
- Loading 10000 records can take up to 5 minutes in Power BI
