### ISSUE TITLE
[Spike] Configure Power BI Deployment Pipeline with Existing PowerBI Dashboard

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#13335]
Overview of Deployment pipelines: https://learn.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-overview

Below are two methods to deploying Power BI pipelines. Option 1 is how it is currently done and is the only way to do it for government PowerBI accounts. Option 2 is using Microsoft Fabric (preview) and cannot be trialed on government PowerBI accounts (I tried).

**Option 1 will be deprecated once Microsoft Fabric becomes Generally Available and no longer in preview. Current estimate is fall/winter 2023.**

Option 1 documentation: [link](https://learn.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-get-started)
Option 2 documentation: [link](https://learn.microsoft.com/en-us/fabric/cicd/deployment-pipelines/get-started-with-deployment-pipelines)

> The deployment pipelines tool enables BI creators to manage the lifecycle of organizational content. It's an efficient and reusable tool for creators in an enterprise with Premium capacity. Deployment pipelines **_enable creators to develop and test Power BI content in the Power BI service, before the content is consumed by users_**. The content types include reports, paginated reports, dashboards, datasets and dataflows.

Course on Power BI pipelines (45 min): https://learn.microsoft.com/en-us/training/modules/power-bi-deployment-pipelines/
Best Practices (for option 1 but some can apply to option 2): https://learn.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-best-practices

## Development
This stage is used to design, build, and upload new content with fellow creators. This is the first stage in deployment pipelines.
## Test
You're ready to enter the test stage after you've made all the needed changes to your content. You upload the modified content so it can be moved to this test stage. Here are three examples of what can be done in the test environment:
- Share content with testers and reviewers
- Load and run tests with larger volumes of data
- Test your app to see how it will look for your end users
## Production
After testing the content, use the production stage to share the final version of your content with business users across the organization.

# Requirements
If you're using [centralized datasets](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-across-workspaces) that are used across the organization, we recommend that you create two types of workspaces:
- Modeling and data workspaces - Workspaces that contain all the centralized datasets
- Reporting workspaces - Workspaces that contain all dependent reports and dashboards
## To do
- [x] Create four (or more?) separate premium workspace for:
   - [x] Deployment
   - [x] Test
   - [x] Production - modeling and data
   - [x] Production - Reporting

> You must be an admin of the workspace. The workspace isn't assigned to any other pipeline. The workspace must reside on a [Premium capacity](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is). To assign a workspace, you need at least [workspace member](https://learn.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-process#permissions-table) permissions for the workspaces in its adjacent stages. For more information, see [Why am I getting the 'workspace member permissions needed' error message when I try to assign a workspace?](https://learn.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-troubleshooting#why-am-i-getting-the--workspace-member-permissions-needed--error-message-when-i-try-to-assign-a-workspace-). You can't assign a workspace with [Power BI samples](https://learn.microsoft.com/en-us/power-bi/create-reports/sample-datasets) to a pipeline stage. You can't assign a [template app](https://learn.microsoft.com/en-us/power-bi/connect-data/service-template-apps-create#create-the-template-workspace) workspace.

# Why we must have this
- Process that prevents dashboard/datasets from becoming stale
- Avoids duplicating of datasets
- Allows collaboration between multiple users
- Version Control
- Tracks historical changes

**Comment by amenity** [comment]
Need version control for Dash & future PowerBI work. Microsoft seems to be offering multiple options for this — there's the GitHub Actions / Git ... 

A little weary about obtaining all the necessary permissions for this configuration from CTM et al. Maybe we could start with a subset of TPW data to see how it works?

**Comment by amenity** [comment]
@susannegov suggests starting this with Signs & Markings since we have existing data and familiarity with the users who would view/edit data at different points in the pipeline.

**Comment by susannegov** [comment]
# To do
- [ ] Course on Power BI pipelines: https://learn.microsoft.com/en-us/training/modules/power-bi-deployment-pipelines/
- [ ] Add or Move `Signs_Markings_Performance_Measures` Reports and Datasets to `TPW - Development Premium Workspace`

**Comment by susannegov** [comment]
- [x] Added Kati C. and Jordan G. to premium workspaces (Members permissions)
- [x] Added @ChrispinP to premium workspace for Paginated Reports test (Member permissions)

## Notes
- Deployment Rules: https://learn.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-create-rules
    - Can customize your dataset URL to a specific test data point in a pipeline between Test and Production 
       - Possible use case is when working with test data instead of sensitive/internal data 
    - https://youtu.be/q96anVwaw8E?t=649
    - Can customize an API call to a specific URL in the deployment using Parameters in the original .pbix file in Power Query
- Compare changes features in deployment history
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/f7fb8f0d-9f90-4fad-a5de-83f1201dcd0a)
   - Can look at deployment changes in Test or Production
   -  Green is new changes, yellow is changes to existing, red is removed, and blue is no changes
