### ISSUE TITLE
IT Support: Please track down LNR-4SK38G3-N1 and rename it to PWD-4SK38G3-N1

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#13342]
## Device & User Information (first name and last initial, no last names)
Matt M
## What's the problem?
Please track down LNR-4SK38G3-N1 and rename it to PWD-4SK38G3-N1

It might belong to the new department CDS

**Comment by Vaishnav1397** [comment]
Tracked the system to check from hardware inventory and Intune. It was a Latitude 7560, and we see that it is already under PWD and is assigned to CSD. No action was needed.
