### ISSUE TITLE
On-Boarding David G.

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#13348]
## Supervisor

- [ ] ~Submit a [CTM New Employee Request Form](https://atx.servicenowservices.com/sp?id=sc_cat_item_guide&sys_id=b714eb12db7a3f0021ccef92ca961972) for a COA network account, eAccess PIN/HR Portal, and phone. Under "Network Account Information," write Shared mailbox: transportation.data@austintexas.gov; Distribution lists: ATDDataTechnologyServices@austintexas.gov and TPWEmployees@austintexas.gov~
>Diana submitted CTM ticket (last week) to change Azure Directory information to change title, location and supervisor - `REQ0156561`
- [x] Check to see if David is on the `ATDDataTechnologyServices@austintexas.gov` DL
- [x] Coordinate hardware needs with Scott as soon as possible to ensure enough lead time to acquire equipment.
>Scott was made aware of the hardware needs when we were in the post-interview
- [x] After the network account is created:
- [x] Ask Amenity or Diana to add the new team member to [City of Austin Slack](https://austininnovation.slack.com/admin)
- [x] Add them to all relevant Slack channels and introduce the new team member to everyone in the main DTS channel
- [ ] Schedule time to give them their computer and show them around the office.
>This is supposed to happen today, Wed, 8/16 but tour guide Christina is out sick. I might give him a tour right before lunch. 
- [x] Add "Welcome (name)" to the [agenda for the next team meeting](https://docs.google.com/document/d/1s8rl928FM0fKPEvsgkVSmkUghPgUmEgMEhZr4bmsJWc/edit). 
- [x] Schedule a one-hour DTS Team Orientation. It should include Peggy and all team leads.
>Scheduled for Wed, 8/16 at 1 pm
- [x] Ask Amenity to schedule DTS Product Ops training.
- [x] Schedule Biweekly 1x1s.
- [ ] Ask Peggy to add the new team member to DTS Team Meetings
- [x] Forward biweekly Sprint calendar events
- [x] Invite new team member to relevant agile ceremonies — Planning, Grooming, Retro
- [x] Invite new team member to other regular meetings — Syncs, Show & Tell
- [x] After they've created their Google and Github accounts: 
- [x] Share the [DTS Google Drive](https://drive.google.com/drive/u/0/folders/1fNmU-czryk5wJsn1gmb4WYUJJdut8Me7) with the new team member. 
- [x] Add the new team member to the City of Austin [Transportation Github team](https://github.com/orgs/cityofaustin/teams/transportation/members). This should automatically add them to the [City of Austin Github organization](https://github.com/orgs/cityofaustin/people).
- [x] Invite the new team member to the [City of Austin Zenhub organization](https://app.zenhub.com/settings/o/cityofaustin/users). 
- [x] Add the new team member to [Gitbook](https://app.gitbook.com/@atd-dts/spaces).
- [ ] Ask Amenity or Diana to [add the new team member to 1Password](https://my.1password.com/people).
>We need to wait on this to free up more licenses, we have 25 person limit. When the fellows leave, we'll have enough. 
- [x] Once they've uploaded their [headshot](https://drive.google.com/drive/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G): 
- [x] Add them to the [DTS Orientation presentation team slide](https://docs.google.com/presentation/d/1ByRWXmjHut88cTiPVOTgkwTJ2V5_m1Y_0j46FP_kdYw/edit#slide=id.gfd25a7f266_1_173) and the slide for the team they are joining.
- [ ] Open an issue to add the team member to the team website. The issue should include link to the headshot, new employee's title for the site and pronouns. Assign the issue to Chia.
- [x] Once they've received notice from CTM that their Miro account was created:
- [x] Add them to [the Austin Transportation Miro Team](https://miro.com/app/settings/team/3074457347846964301/users/). 
- [x] Once HR has added them to the UKG timekeeping system:
>checked on 8/16, he shows as a direct report for me - Diana
- [ ] Set up their schedule plan. 

## Hardware
Coordinate with Scott.

- [x] Laptop
>Fri, 8/11 - Had computer, Monday/Tuesday was given new laptop since old one was not performant. 
- [x] Power supply
- [x] Monitors
>he's going to try to get 3rd monitor going with current docking station
- [x] Keyboard
- [x] Mouse
- [x] Docking station
- [ ] Phone, if necessary

## Office
Coordinate with Diana. 
- [ ] Cameron Badge Access
>picking up badge today, @dianamartin will give access in the afternoon
- [x] Chair
>David is going to bring in his own chair from home that he prefers
- [x] Desk
 
# Employee
- [ ] Review On-boarding [Checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/your-first-week)
- [ ] Reconfigure AGOL account
- [ ] Set up DTS Portal account - Apps
- [ ] Review DTS Data Inventory
- [ ] Check out Open Data Portal
- [ ] Review GIS Onboarding GitBook
- [ ] Set up Signs and Markings GIS QA - Apps

**Comment by johnclary** [comment]
👋 i think y'all should add "introduce new team member on Slack" to this issue template 😅 cc @amenity @chiaberry

**Comment by amenity** [comment]
@johnclary -Thanks! I'm not sure where this checklist came from, but @andrewshensky is going to update this issue to include our [full onboarding checklist](https://atd-dts.gitbook.io/wiki/onboarding/new-employee-checklist).

**Comment by johnclary** [comment]
🙌 thanks y'all!
