### ISSUE TITLE
Replace laptop charger for Jameel H.

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#13367]
Jameel H.  stopped by the Apps/Dev room today at 8700 Cameron and inquired about getting a laptop charger to replace the one he was given. He stated that he had wrong that was the wrong time for his laptop. I didn't have an opportunity to verify that it was working or not, and offered to create this ticket for him. I asked if it had been given to him by CTM or by DTS, and he mentioned that @scottreedy may have been the person who delivered it to him.

**Comment by frankhereford** [comment]
Scott - please let me know if you'd like this assigned to someone else. I didn't know what the right process is for these - if I can help at all, please let me know!! Thank you!

**Comment by dianamartin** [comment]
@scottreedy did you see this one by chance?

**Comment by scottreedy** [comment]
Have not been able to get together. He said he was not in a hurry.
