### ISSUE TITLE
IT Support: OTC Tablet Reset

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#13376]
## Device & User Information (first name and last initial, no last names)
Laticia R
## What's the problem?
" Hi, Matt, it's  with a safe route for Crossing Guard manager. I was calling because I'm hoping that you're available tomorrow. I have my niece you provided supervisor that just started his name is  and he's going to need the tablet that was a rodeo part of those tablets. He's going to need it to be like reset for him to be able to do the time clock for the U K G for his people. So if you're available sometime tomorrow, I guess between 839 o'clock, he's going to need or 830 to 930. I don't know just sometime between there to get his thing reset I'm calling you from my cellphone. So if you don't recognize the number and that's fine but anyway, yeah that would be great because he'll be there tomorrow after his morning shift and he'll need that so that he can be able to use this time clock and all that for the U K G and if you could show me how to use that and the mifi that was given to him. So he'll know how to connect everything. Yeah, anyway, you could  either email me. Let me know if you can come I'm not going to be on my laptop. Right now cause I'm having to go to Houston. I'm going to be out of town, but I am going to have my laptop with me and I'll check in on that every now and then because I'm going over there to take care of my parents because they both got sick but yes, so if you can do that or give me a call back to let me know or text my phone number. This is my phone number  that's my cellphone number or mobile number anyway. Now I'm talking a lot but yeah anyway, if you could do that for me that would be awesome to help him out and get him set up. Alright, thanks bye."

**Comment by Vaishnav1397** [comment]
Couldn't find the passcode and matt tried to swap that with another iPad from a user from BTC and headed to OTC but user was not available.

**Comment by Vaishnav1397** [comment]
Swapped the tablet by matt and updated.
