### ISSUE TITLE
Upgrade VZ production database to graphql-engine 2+

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#13392]
Vision Zero local development is already on graphql-engine 2+

> - Do a code sweep to see what breaking changes could exist between version 1 and 2.
> make sure to focus on breaking changes that were introduced between GraphQL engine
> - Update task definition for staging and test the following days after.
> - Barring any changes we could update in Production.

database cloned
test ecs cluster spun up
go through the process and make sure the jumps you want to make are makeable

**Comment by frankhereford** [comment]
Chia found this slack conversation with some helpful information that came out of the spike to upgrade graphql-engine. Thank you Chia! They were repurposed later to become the PR comments to get this merged.

https://austininnovation.slack.com/archives/CNUEPKLB1/p1654287743257939

**Comment by chiaberry** [comment]
@frankhereford's work on https://github.com/cityofaustin/atd-data-tech/issues/11895 has resulted in a quick trial run of upgrading

**Comment by frankhereford** [comment]
Thanks @chiaberry - it was a welcome side effect for sure. I wanted to link our slack conversation here too for some more info - https://austininnovation.slack.com/archives/CM9MK950S/p1692390232340659.

**Comment by patrickm02L** [comment]
## 8/23

### Steps to upgrade
- back up VZ database
- jump to 2.2
- update by 10s to get to the latest version of graphQL

**Comment by frankhereford** [comment]
This work has been completed. Here's my note in [slack](https://austininnovation.slack.com/archives/CM9MK950S/p1692834587741439).

> The graphql-engine upgrade on both production and staging VZ stacks is complete. We’re now running v2.32.1 for both, which is the latest, stable version. Everything went as expected with no apparent downtime to users. This took the time it did because I was moving very deliberately and just double checking everything I was doing because it’s much easier to not make a mistake than have to unravel it. :face_with_spiral_eyes:

> I’m looking forward to running my profiling script tomorrow to get a handle on the newest round of performance improvements we’ve brought to the VZE application. I’ll also update the issue with these notes and close this one out. Thanks everyone!
