### ISSUE TITLE
Updates to UC Franchise Processes

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13396]
### Some existing processes should be renamed, and create new franchise processes. 

List of Franchise Utility processes & their codes in the UC folder:
•	51139 Alpheus (El Paso Global)
•	51142 AT&T (SWBT)
•	51143 AT&T Legacy
•	51144 AT&T Metro
•	51146 CenturyLink (Qwest)
•	51147 CyrusOne
•	51148 Chevron Pipeline
•	51149 Blue Bonnet Electric
•	51172 Crown Castle (NextG)
•	51183 FiberLight
•	51184 FiberNet
•	51214 Kinder Morgan Pipeline
•	51216 Grande Communications
•	51217 Google Fiber Texas
•	51218 Level3 Communications
•	51219 LCRA
•	51248 ONCOR
•	51249 Pedernales Electric
•	51279 Sprint
•	51306 TelePacific (Telwest)
•	51307 Time Warner Cable
•	51308 TW Telecom
•	51309 Texas Gas Service
•	51336 XO Communications
•	51337 Verizon (MCI)
•	51338 Zayo
•	51339 ZNET (Duct system)

**Comment by TracyLinder** [comment]
@vschandramouli I think the list in the description is what is current. We need to identify which updates are needed.

**Comment by TracyLinder** [comment]
### UC Team Sync 9/6/23

- We haven't established what updates to the existing list need to be made.

**Comment by TracyLinder** [comment]
### UC Team Sync 10/30/23

Jacyln is tracking this on a spreadsheet; she's looking for it.

**Comment by vschandramouli** [comment]
Attaching document provided by Jaclyn. Currently analyzing requirements. [AULCC Contacts_External_Franchise Update Names_copy 1.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGVUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a592abfe9f2b735cf17306097edd5b6602580fc0/AULCC%20Contacts_External_Franchise%20Update%20Names_copy%201.xlsx)

**Comment by TracyLinder** [comment]
OK TO CLOSE
