### ISSUE TITLE
Update Geospatial section of DTS Service Request workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13406]
The Geo team would like to update their DTS service requests to provide more clarity for their users. The following updates will need to be done simultaneously-ish in a Dev+Apps+Product work session

## Knack (Apps)
- [x] In the "What do you need help with?" field, replace `GIS or Maps` with `Geospatial Services (GIS, Maps, etc.)`
- [x] Add dropdown field conditional on the "Geospatial..." selection: 

> What do you need? 
> - Map
> - GIS Data
> - ArcGIS Training
> - ArcGIS Online Access
> - ArcGIS Online Support
> - ArcGIS Pro Support
> - ArcGIS Pro Installation 

## ATD Service Bot (Dev)
- [x] For the "What do you need help with?" field mapping, replace `GIS or Maps` with `Geospatial Services (GIS, Maps, etc.)`
- [x] Map the new "What do you need?" field to the following labels:

What do you need? | "Service" label | "Type" label
-- | -- | --
Map | Service: Geo | Type: Map Request
GIS Data | Service: Geo | Type: Data
ArcGIS Training | Service: Geo | Type: Training
ArcGIS Online Access | Service: Geo | Type: IT Support
ArcGIS Online Support | Service: Geo | Type: Data
ArcGIS Pro Support | Service: Geo | Type: Data
ArcGIS Pro Installation | Service: Tech Services | Type: IT Support

- [x] Update label mapping from `"Transportation Development Services Portal": "Product: Transportation Development Services Portal",` to `"Transportation Development Services Portal": "Product: TDS Portal",`

## Product tasks
- [x] Schedule work session
- [x] Attend work session to provide support and testing

**Comment by amenity** [comment]
@andrewshensky - after you add specs above, assign this to me and I can fill out the Github+Knack+Service Bot task lists based on the process we used [here](https://github.com/cityofaustin/atd-data-tech/issues/12481). Thanks!

**Comment by andrewshensky** [comment]
@amenity below are some recommendations and ideas that came up during our geo sync:

**Workgroup** 
May be clearer to requestor by asking "What is your workgroup?"

**What do you need help with?**
"GIS or Maps" - Replace with Geospatial Services (GIS, Maps, etc.)
 
**What Application are you using?**
It would be nice to have more options included for the type of GIS request being submitted. Recommendations are below:
ArcGIS - Map Request
ArcGIS - Data Request
ArcGIS - Training
ArcGIS Online - Access
ArcGIS Online - Support
ArcGIS Pro - Installation
ArcGIS Pro - Support
 
**How soon do you need this?**
Add category between Urgent and Soon to reduce abuse of urgency
Potential to add deadline date that requestor could select from identifying when requested item is needed
Mirror ServiceNow Impact/Urgency Dropdown
If both Impact and Urgency are high notify requestor emails will be sent

**Comment by amenity** [comment]
Thanks, @andrewshensky. 👍🏻 🌍 

We can replace the "What application are you using?" field with a just-for-Geo "What do you need?" field rather than adding all those options to the existing application drop-down. Will you please specify what labels you want to be applied for each option [here](https://docs.google.com/spreadsheets/d/1BsOklJsJiIIqdlmtNtr9peL3URS7Hdu9RVj4D97701k/edit#gid=1233068109)? 

I made a separate issue for the urgency/impact changes since those could be a significant refactor for everyone: #13479

**Comment by mddilley** [comment]
Quick update here - I checked the box for the dev TDS mapping update above because the service bot script broke with a Knack change. It was a quick fix. 🙌 https://github.com/cityofaustin/atd-service-bot/pull/59

**Comment by amenity** [comment]
Thanks so much, @mddilley!

**Comment by mddilley** [comment]
[Here is the PR](https://github.com/cityofaustin/atd-service-bot/pull/60) for the code changes for the dev part of this. I'll request reviews from the dev team. I left out the field number for "What do you need?" since it doesn't exist in the Knack app yet, but I can add that before merging the code in the meeting on Monday.

**Comment by dianamartin** [comment]
# 9/25
- [x] Added new object `What did you need?`
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b6db4668-d441-4a09-9a17-b072961410cb)
- [x] Add field to form
- [x] Add display rule 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/5d5edbd4-7614-49c7-8630-33e956df0f70)

**Comment by amenity** [comment]
@mddilley @dianamartin and I did this yesterday, cc/ @andrewshensky @ATD-ZachB 

A couple notes for future reference: 
- New Knack fields can be created beforehand to get the field ID# for Dev to include in their PR. The field is hidden until it's added to the form during go-live. 
- When a new field is added to the form we also need to add it to the [API view that powers the service bot](https://builder.knack.com/atd/dts/pages/scene_127).

**Comment by andrewshensky** [comment]
NEW Proposal:

What do you need? | "Service" label | "Type" label
-- | -- | --
Map | Service: Geo | Type: Map Request
GIS Data | Service: Geo | Type: Data
ArcGIS Training | Service: Geo | Type: Training
ArcGIS ~~Online~~ Access | Service: Geo | Type: ~~IT Support~~ ArcGIS Access
ArcGIS ~~Online~~ Support | Service: Geo | Type: ~~Data~~ ArcGIS Support
~~ArcGIS Pro Support~~ | ~~Service: Geo~~ | ~~Type: Data~~
ArcGIS Pro Installation | Service: Tech Services | Type: IT Support

**Comment by dianamartin** [comment]
@amenity how do you want @andrewshensky to handle this new proposal?

**Comment by amenity** [comment]
@andrewshensky - please open a new "Update Geospatial section of DTS Service Request workflow" issue with the updated chart you added above. 

Assign it to me, and I'll write the step-by-step and schedule an Apps + Dev + Product work session to roll this out.
