### ISSUE TITLE
[Enhancement] Advanced Search for Lamppost and Over-the-Street tabs

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13407]
## Description

Companion to #10725

Smart Mobility wants to create an "Advanced Search" page, where they could search by keyword, date ranges, and status.

## Objective
- We currently have advanced capabilities but they're not built out, continue building them

## Note
- Lampost example

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcndNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1aecbb8e22760cee83fdee9716fc098cabf29e2d/Screen%20Shot%202023-08-16%20at%2010.42.34%20AM.png)

**Comment by patrickm02L** [comment]
@dianamartin do you think this Issues was addressed with #14680?

**Comment by dianamartin** [comment]
@patrickm02L Yes, I think the other issue #14680 does address this. Closing.
