### ISSUE TITLE
[Enhancement] Add a confirmation modal before syncing a project w/ Data Tracker

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#13411]
Every once in a while a user syncs a project with Data Tracker by accident. There is no way to undo this in the Moped UI or Data Tracker UI. We should prompt users to confirm they want to sync a project w/ Data Tracker to let them abort this action if the button was clicked by accident.

### Dialog title
_Synchronize Project with Data Tracker_

### Dialog body

_This project's data will be copied to the Arterial Management Data Tracker so that the project can be associated with work orders and asset management._

### Button labels:
- Cancel
- Continue

Please use the same styling as the delete project dialog:

<img width="1512" alt="Screenshot 2023-08-29 at 12 42 14 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/27044d1c-17ab-4c4d-994f-7cd849ac21d8">

**Comment by chiaberry** [comment]
feedback in moped user group meeting was that modal was not needed
