### ISSUE TITLE
Obtain and integrate eCAPRIS and Maximo data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13434]

**Comment by rebekkabry** [comment]
**Objective**: To obtain applicable and access eCAPRIS's metadata. 

- [ ] Request Access to Database or Request Exported Metadata 
- [ ] Review Metadata collected 
- [ ] Review interface and export options within Database 
- [ ] Link or Access Point: 
- [ ] **Question**: Is the list provided a complete view or limited view? 
- [ ] **Next**: Are follow-ups needed to get complete view or gain access to data? 
- [ ] Integrate data into the [Excel Mapping](https://cityofaustin-my.sharepoint.com/:x:/g/personal/rebekka_bryant_austintexas_gov/EfdqV8-zl9dGurtk6WoWq_UBGac0A9y-QteQpkHyNrHOiw?email=Rebekka.Bryant%40austintexas.gov&e=oe0Oiy) 
- [ ] Integrate data into the Key file 
-----

**Comment by rebekkabry** [comment]
[Previous Visual from Miro](https://miro.com/app/board/uXjVO7FizDw=/?share_link_id=524010102310)

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/1da06953-e673-4f25-86ca-9f8ed0a57986)

**Comment by rebekkabry** [comment]
- [ ] Maximo integrated into the ecosystem maps.
