### ISSUE TITLE
Add relevant Microstrategy data and outputs to map

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13437]

**Comment by rebekkabry** [comment]
**Objective**: To obtain applicable and access MicroStrategy metadata. 

- [ ] Request Access to Database or Request Exported Metadata 
- [ ] Review Metadata collected 
- [ ] Review interface and export options within Database 
- [ ] Link or Access Point: 
- [ ] **Question**: Is the list provided a complete view or limited view? 
- [ ] **Next**: Are follow-ups needed to get complete view or gain access to data? 
- [ ] Integrate data into the [Excel Mapping](https://cityofaustin-my.sharepoint.com/:x:/g/personal/rebekka_bryant_austintexas_gov/EfdqV8-zl9dGurtk6WoWq_UBGac0A9y-QteQpkHyNrHOiw?email=Rebekka.Bryant%40austintexas.gov&e=oe0Oiy) 
- [ ] Integrate data into the Key file

**Comment by rebekkabry** [comment]
Adding to [Placeholder ](https://github.com/cityofaustin/atd-data-tech/issues/13598)to decide how to handle specific data included. Currently has an ID, manually added.
