### ISSUE TITLE
Obtain and integrate eCOMBS data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13433]

**Comment by rebekkabry** [comment]
**Objective**: To obtain applicable and access eCOMBS metadata. 

- [ ] Request Access to Database or Request Exported Metadata 
- [ ] Review Metadata collected 
- [ ] Review interface and export options within Database 
- [ ] Link or Access Point: 
- [ ] **Question**: Is the list provided a complete view or limited view? 
- [ ] **Next**: Are follow-ups needed to get complete view or gain access to data? 
- [ ] Integrate data into the [Excel Mapping](https://cityofaustin-my.sharepoint.com/:x:/g/personal/rebekka_bryant_austintexas_gov/EfdqV8-zl9dGurtk6WoWq_UBGac0A9y-QteQpkHyNrHOiw?email=Rebekka.Bryant%40austintexas.gov&e=oe0Oiy) 
- [ ] Integrate data into the Key file

**Comment by rebekkabry** [comment]
Additional Notes

**Main Function of eCOMBS**: budget and finance performance measures
+ Serves as a city wide performance measure tool
+ There are different views for levels 
+ sd23 created across departments, within each department they came up with goals to help acheive city wide. 
+ This is more of an internal department goals, not really connected to sd23. Here each department set their own goals and measures. Represented in the PERFORMANCE MEASURES OUTPUT LINK. 
+ Ecombs gets updated and the performance measures outputs were updated. It was up to each department to set each goals...regardless of whether they aligned with sd23 goals. 
+ Not sure how data gets into ecombs at the moment > data entry interface. the data is manually entered it appears??? 
Q: When go to measures, who is the "responsbile employees" for updating? Was Transportation department automatically updated or manually entering data into eCOMBS? 
+ What are IDs and how are they tied into the overall system? Only IDs within ecombs. We will prob use them for the performance measure inventory report. 
SD MA5.1 etc are assocaited
