### ISSUE TITLE
Obtain and integrate Knack data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13432]

**Comment by rebekkabry** [comment]
Objective: To obtain applicable and access Knack's metadata. 

- [ ] Request Access to Database or Request Exported Metadata 
- [ ] Review Metadata collected 
- [ ] Review interface and export options within Database 
- [ ] Link or Access Point: 
- [ ] **Question**: Is the list provided a complete view or limited view? 
- [ ] **Next**: Are follow-ups needed to get complete view or gain access to data? 

- [ ] Integrate data into the Eco-Mapping Master file
- [ ] Integrate data into the Key file

**Comment by rebekkabry** [comment]
- [ ]  Knack Outputs 
- [ ] Knack DBs/Applications/Servers/Storage references have been integrated into the ecosystem assets 
- [ ]  Knack DB DS - included 

+ All knack assets will be used a master vlookup table to ensure proper assets are linked into Knack, per data records standards desired by DTS.
