### ISSUE TITLE
Offboard Madison F & Rachel W

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13448]
[Gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/offboarding/off-boarding-checklist)

## IT Permissions and Access

- [x] One Password
- [x] Slack
- [x] Miro - did not have a license
- [x] GitHub - (reassign issues, too)
- [x] Gitbook
- [x] Google Drive
- [x] Remove from [Github](https://github.com/orgs/cityofaustin/teams/transportation/members)
- [x] SERF

## Admin

- [x] About Us - Move to Alumni Section
- [x] DTS Team Slide

**Comment by chiaberry** [comment]
I've also removed them both from gitbook access

**Comment by patrickm02L** [comment]
Submitted the SERF for Madison and Rachel today.

**Comment by patrickm02L** [comment]
SERFs have been completed
