### ISSUE TITLE
Perform follow-up tasks from Agile training 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13440]
- Debrief [notes doc](https://docs.google.com/document/d/1FKeh74j1cvz6NRFJ5zXu_CLuBGyiy2CE4GyMDeYFGb8/edit?usp=sharing)

## Maximo
@TracyLinder 
- [x] Meet with the team to discuss and document desired changes 

## Data Science
@katelunceford 
- [x] Meet with the team to discuss and document desired changes
- [ ] Update meeting invite to include the purpose of each Sprint Planning & Backlog Refinement

## Geo
@ATD-ZachB 
- [x] Meet with the team to discuss and document desired changes
- [x] #14035

## Apps
@ChrispinP 
- [x] Meet with the team to discuss and document desired changes

## Dev
@chiaberry  
- [x] Meet with the team to discuss and document desired changes 

## General
- [x] @TracyLinder - schedule meetings and assign tasks
- [x] @TracyLinder - update everyone on follow up plan at 8/8 DTS team meeting
- [x] @patrickm02L - compile results into Miro board
- [x] Present results & facilitate discussion at DTS team meeting
- [x] @amenity Update Gitbook [product-ops docs](https://atd-dts.gitbook.io/wiki/product-ops/github-project-management) and [Product Ops slide deck](https://docs.google.com/presentation/d/1UNPfbZtdBRr5jLMobRvZPv5BrJDPY6OX4dlRcffHdE4/edit#slide=id.g27445f4bd2e_0_123)

**Comment by ChrispinP** [comment]
Met with Apps Team yesterday to gather ideas & improvements.

**Comment by TracyLinder** [comment]
### Debrief Team Mtg No. 3

- Notes are [here.](https://docs.google.com/document/d/1FKeh74j1cvz6NRFJ5zXu_CLuBGyiy2CE4GyMDeYFGb8/edit?usp=sharing)
- @patrickm02L will draft the miro board to be used at the DTS Monthly Meeting on 9/12. 
- This team is meeting on 8/7 to discuss

**Comment by patrickm02L** [comment]
Here's the [Miroboard](https://miro.com/app/board/uXjVMoRWYH8=/?share_link_id=61926558088) consolidating the notes and grouping them by themes

**Comment by amenity** [comment]
@amenity - please close this out for everyone else and make your outstanding tasks into their own issue(s).

**Comment by ChrispinP** [comment]
@amenity ping 😎

**Comment by amenity** [comment]
Thanks, @ChrispinP !!
