### ISSUE TITLE
IT Support: Install Bluebeam

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#13450]
ST. ELMO

## Device & User Information (first name and last initial, no last names)
Anna M
## What's the problem?
Please install Bluebeam on Anna's computer. 

You can install the software from https://support.bluebeam.com/download-archive/

The license info is located here:
\\coacd.org\dfs\ATD\ATD\Misc\Bluebeam_Revu\CPO

**Comment by Vaishnav1397** [comment]
IM the user through teams and waiting for response.

**Comment by Vaishnav1397** [comment]
Downloaded the Bluebeam latest version with the ST number as per the license and launched it.
