### ISSUE TITLE
Fork FH repo to City of Austin repos

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13466]
## Description:
Successfully transfer (fork) QGIS polygonizer plugin repository from FH's personal GitHub to the City of Austin GitHub

## Notes
- Forking allows all code, documentation, issues, and pull requests are maintained during the transfer process
- Documentation should be updated to reflect the new repository ownership and location

**Comment by frankhereford** [comment]
https://github.com/cityofaustin/dts-qgis-polygon-plugin
