### ISSUE TITLE
Enhance QGIS Polygonizer plugin to handle overlapping polygons

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13468]
## Description

reference [repo](https://github.com/frankhereford/qgis-polygonizer)

Ensure that polygons created do not overlap with each other by finding overlapping areas between them and trimming polygon area where needed

- There's a reference implementation of algorithm in Perl using the postGIS library and will be recreated using the QGIS library   
 - Algorithm to be implemented: Iterate through overlapping polygons in pairs and subtract the polygon which has the smaller of it's area being overlapped from the overlapping polygon; repeat until no more overlapping pairs exist

**Comment by frankhereford** [comment]
Hey @patrickm02L 👋 

I got trucking on the QGIS stuff today, and I have a PR ready for this issue too. I'm going to drag this to in-progress briefly and then put it in QA when I submit the PR for review here shortly. Thanks!

**Comment by patrickm02L** [comment]
@frankhereford cool, glad things were flowing!

**Comment by frankhereford** [comment]
This project is going to be superseded by a custom solution being developed internally by the VZ team.
