### ISSUE TITLE
Update DTS Service Request - Requester email confirmation information - Add Matt M.

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#13478]
Currently, we have this going out to folks:
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/26242f66-6471-4298-9805-086349db36c4)

Scott had mentioned in a Tech Services sync that a legacy PWD employee submitted a request and was thrown off when they saw Scott's name and not Matt's. His suggestion was to add Matt's contact information to the requester email confirmation after they've submitted a DTS request. 

I thought I submitted an issue for this, but I can't seem to find it.

**Comment by amenity** [comment]
Looks good, @dianamartin - I'll ask the devs to do it next sprint.

**Comment by dianamartin** [comment]
# 8/24
- [x] Updated DTS confirmation email to requester to include Matt M's information, updated a few parts of the message
- [x] Changed "IT Support to "Technology Services Support"
- [x] Changed "GIS and Maps" to "Geospatial Services (GIS, Maps, etc.)"
- [x] Updated font to roboto so it looks more polished like the Metrobike emails
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b40e527f-a4c0-44d0-8c54-c48dcc15c824)
