### ISSUE TITLE
Grow the VZ RDS Cluster

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#13489]
https://github.com/cityofaustin/atd-data-tech/issues/11895 was originally opened to grow the VZ RDS cluster to t3.medium, but that issue was changed to capture the work of changing the VZ db stack to use the new Aurora service. 

This issue is to track the status of growing the RDS cluster to t3.medium.

**Comment by frankhereford** [comment]
I've written Joel to let him and his team know that we intend to do the upgrade on the main DB today at 5PM. I'll let the team know if he indicates that this is going to be problematic, otherwise, I think we've checked the box on letting them know. Thanks again @chiaberry for observing that we needed to do this!

**Comment by chiaberry** [comment]
fyi @patrickm02L, i opened this issue to keep track of this work for this sprint

**Comment by frankhereford** [comment]
The vision zero editor service has been restored after updating to t3.medium. It was down for about 8 minutes while the DB was unavailable and while the ECS cluster started up its graphql-engine instances.

The crash listing page is more performant for sure. Queries that were taking 12 seconds are now in the 6 second range. 

The locations listing page query is still in the 30 second range, but it rendered which it frequently did not previously.
Fatalities came up faster as well, at about half the time that it normally does if not better. It is the big winner on this update, it looks like. This upgrade concerned adding RAM, but not CPU, to the DB server, and the joins under the view that powers this page clearly were starving for it.

This went really well - the update didn’t have any hitches to speak of, and it’s clearly faster.

I will evaluate it against the Aurora DB tomorrow and present findings, but at first blush, I’m still seeing Aurora answering queries in < 1 second where this is coming in at 5+ seconds, however, there’s no questioning that this is a huge improvement from this morning.
