### ISSUE TITLE
Mobile Device Support Meeting

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#13486]
participants: Karo, Diana, Scott, Vaishnav, Matt, Chrispin, Susanne

# Meeting Notes
- Introduced the DTS Hardware Asset Inventory
- Chrispin suggested some improvements in the inventory
- Reviewed legacy PWD tablet inventory - ~`70 devices`
- Change management process for tracking tablet devices

## Action Items
- [x] Create SN ticket - @ChrispinP 
  - legacy PWD - need access to ATD AirWatch
  - legacy ATD - need to access PWD AirWatch
- [x] Follow-up pairing session with Matt, Chrispin, Susanne - @Matthew-M-TPW 

### Decisions:
- Chrispin and Susanne will enter Tablet Info for SMD and AMD into DTS Hardware
- Enhance SMD Manage Devices - @susannegov 
  - compare the SMD Manage Devices to the DTS Inventory and make suggestions on aligning the data/fields for easier management

**Comment by ChrispinP** [comment]
Matt, Susanne, and I plan to meet up on Thursday. Danny was able to complete the ServiceNow request for updated AirWatch permissions.

Pending any further action

**Comment by ChristinaTremel** [comment]
- Updates to the process will be captured on #13487 
- Closing this issue!
