### ISSUE TITLE
TDS Reporting Initial Build

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13508]
### Build Notes
- Time range for default: Quarterly at minimum, common is 6 months, 1 year (the past 365 days, Current Fiscal, Year to date

- [x] Scrap current reporting pages & menu placement
- [x] Create new top nav page for reporting 
- [x] Mirror style after available services on customer portal, toggle for each service type w/ reporting specific to that type
- [x] Need review duration for multiple areas:
- For scopes & submissions (start is submitted date, end is Review Complete Date)
- For SIF & Determination (submitted is start, review completed is end)
- TIA Case (created is start, approved is end)
- Duration of waiting on applicant to respond to staff (duration between submittal review complete date and the submittal of the next review)

**Comment by TracyLinder** [comment]
Hi @ChrispinP - this is On Deck for you for the sprint beginning today. Currently the estimate is a 3. TY

**Comment by ChrispinP** [comment]
- Top Nav Reporting Menu now visible while build is in progress
- New page framework setup
- Old reports moved to their new pages
- TIA_reporting_ytd object built
- TIA_request records updated

- [ ] Scope and Submission Cycles need to be connected to new ytd reporting object
- [ ] Build requested reports

**Comment by ChrispinP** [comment]
Initial build with navigation, pages, rules, code, fields, and reports is ready. Notified stakeholders

**Comment by ChrispinP** [comment]
**On Calculating Customer Time vs Staff Time**

- Target Time for 1st Cycle for each Request Type
- Target Time for Resubmittal Cycles for each Request Type
- Target Number of Cycles (multiplier)
- Actual Times & Counts
- Difference between Actuals & Targets
- Show status colors
- Warning colors/notification for those above Target
- Filtered on City Wide & Area
- Filtered Time Periods including last 3 years/quarters
- Displayed in a Table on Dashboard & Line/Bar Chart

**Additional Modifications:**
- [ ] Remove Month filters
- [ ] Will determine which reports should have both predefined & custom filters
- [ ] Open to the idea of a custom dropdown menu
- [ ] Ability to drill-down into reports (not mvp)
- [ ] Might want to hide Idle Time & Days Under Review metrics if not important

**Comment by ChrispinP** [comment]
I have been meeting with Matiur & Kaylie to gather additional feedback and requirements for reporting needed by Executives. Curtis was pleased with the direction of the updates. Critical reports desired before EOW.

We recently enhanced the reporting to also include the Fiscal data for Completed Dates in addition to Submitted Dates. This will allow TDS to perform analysis quarterly and either view or filter data by Fiscal Year or Quarter. All completed work is checked above. Remaining work still necessary for the upcoming sprint.

**Comment by TracyLinder** [comment]
### Apps Planning 10/18/23

- Chrispin will continue with the unfinished items above
- We should have a builder huddle about this, Tracy will schedule
    - Review design, maintenance, necessary fields to meet reporting needs, can we replicate this across apps?

**Comment by ChrispinP** [comment]
Action items above have been completed but some additional needs cropped up as a result of the implementation.

- [ ] Add remaining On Time % metrics to the Transportation Study: Actual vs Target table on Reporting Dashboard
- [ ] Updated Metric definitions
- [ ] The ability to adjust On Time Reporting Targets for all records
- [ ] Ability to filter Transportation Study: Actual vs Target table by fiscal years/quarters

For the initial build, we:
- [ ] Need to propagate the updated fiscal reports for the overall Transportation Study for each 
 of the service types
- [ ] Full TIA
- [ ] TIA Compliance
- [ ] NTA
- [ ] TA
- [ ] ZTA

**Comment by ChrispinP** [comment]
I also updated the back buttons to be direct links to the Transportation Study Reports page since the default knack page links append to the url instead or correctly replacing the url.

**Initial Build complete**.

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/50f566cc-16ca-4a96-96c9-977353cb3444)

**Comment by ChrispinP** [comment]
Issue #14609 created for followup work on TDS Reporting

this is considered complete, closing
