### ISSUE TITLE
AMD Data Tracker Roadmap Meeting

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1350]
_2/3/20
Attendees: Brian VdW, Billy B, Fanta, Surbhi, Diana, Lance, Amenity, John, Jen_

[Slides & notes](https://docs.google.com/presentation/d/1XX6q0J_zWE1DQfG5qz9Pelasp0Ef-eLmATtCkULqyIw/edit#slide=id.p)

Resulting issues: 
- https://github.com/cityofaustin/atd-data-tech/issues/1351
- https://github.com/cityofaustin/atd-data-tech/issues/1352

**Comment by amenity** [comment]
@SurbhiBakshi @dianamartin @johnclary - add any notes/thoughts I missed plz

**Comment by SurbhiBakshi** [comment]
@amenity I am still learning about the app and different work groups myself, don't have anything to add.
