### ISSUE TITLE
[Enhancement] Optimize VZE Page performance

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13522]
## Description

As we're having discussion about upgrading the AWS RDS cluster #11895, we've come across performances issue on some of our pages that need to be addressed. We'll need to improve the performance of VZE's core views on the current database.

## Requirements
- Conduct an analysis of the slow queries affecting VZE's core views
- Optimize the relevant queries
- Implement any other mechanism that will further the speed up of core views

## Note
- reference slack [conversation ](https://austininnovation.slack.com/archives/CM9MK950S/p1692747285738689?thread_ts=1692735490.927069&cid=CM9MK950S)

**Comment by johnclary** [comment]
We've reworking all the query endpoints as part of the new data model 👍
