### ISSUE TITLE
Identify inconsistencies in CRIS data schemas between 2018 and 2023

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13532]
## Description
Identify inconsistencies in the CRIS data schemas between the years 2018 and 2023. This task involves writing a Python script that will compare the data structures of these two years' CRIS schemas.

## Deliverables
- A report listing the names of lookup tables affected by inconsistencies between the two years
- If feasible, a visualization that illustrates the relationships and structural differences between affected lookup tables, highlighting the changes

## Notes
- This Issue affects #12577
- Time block to 2 hours

**Comment by frankhereford** [comment]
## Update
[Here’s a program](https://github.com/cityofaustin/atd-vz-data/blob/cris_schema_analysis/atd-toolbox/cris_schema_analysis/compare_cris_schemata.py) which can compare two “lookup” CSV files from one schema to another. Based on the three lookup tables that I have compared so far, it's not clear that we have a complete understanding of how these CRIS schemas are handled upstream of us. I'm going to reach out to CRIS to get more information.

More details in Slack thread: https://austininnovation.slack.com/archives/CM9MK950S/p1692915358298629

**Comment by frankhereford** [comment]
I called the CRIS help desk, and the question was well received, but the representative I spoke to had to escalate this up to their supervisor. They are going to call me back when they are able, and I'll pick this up from them then. Until then, I'm going to keep hacking on the import script and do it with a 2023 schema.

**Comment by frankhereford** [comment]
I exchanged a short series of emails with the CRIS team, and it turns out that each schema is only consistent of additional columns without meaningful changes to the lookup values they may point to. We can handle the schemata entirely in the CRIS import, as a result. 😅
