### ISSUE TITLE
Invoice number

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1353]
# As a RPP staff want to reference bills/invoices by a unique invoice number

**Describe the outcome you'd like to see when this feature is implemented.**
Unique invoice number that can be used for reporting/auditing

## Acceptance Criteria
- [ ] When RPP staff are on the `Issue` page, they will click the `Issue` button on the permit issue form
- [ ] The Issued Permit table will show the permit and the `Transaction ID` will automatically appear as it is auto-generated by the system.

** `Transaction ID` and `Invoice number` are same

**Comment by dianamartin** [comment]
I have a table created `transactions` and have an auto-incremental field called `Transaction_ID`. If we need a more specific ID format I can build that in.

**Comment by dianamartin** [comment]
I want to clarify if this is still needed or if we can use the `Application ID` as a unique number

**Comment by dianamartin** [comment]
This was clarified by the Finance team, they are fine with using a unique ID such as the `Application ID`
