### ISSUE TITLE
Publish Short Line HIN on Open Data Portal

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13531]

**Comment by susannegov** [comment]
HIN is on the short line dataset in ODP now: https://data.austintexas.gov/Transportation-and-Mobility/TRANSPORTATION-markings_short_line/9hak-anfp

Good to close

**Comment by andrewshensky** [comment]
The marking short line relationship class has now been restored by CTM in DM as well. Closing issue
