### ISSUE TITLE
Payment details

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1354]
# As a Finance staff - I need detailed payment information captured: payment type, check number, payee info

**Describe the outcome you'd like to see when this feature is implemented.**
Payment type - check, cash, credit
Check #
Payee info - name, address, phone 
To be used for reporting/auditing

Must have

## Acceptance Criteria
- [ ] There is a page called `Permits & Transactions`
- [ ] It has `Payment Type`
- [ ] Has `Payee Name`
- [ ] `Payee Address`
- [ ] `Payee Phone`
- [ ] If Payment Type is - Check, it will have a field `Check #`

**Comment by dianamartin** [comment]
I created a page called `Permits & Transactions`. The permits and the transactions were a 1:1 relationship, so we just added the transaction fields on the permit table. 

![image](https://user-images.githubusercontent.com/21112975/74284206-e49f7300-4ce8-11ea-8c4d-ccea447fdc22.png)

**Comment by dianamartin** [comment]
I moved the transaction fields from the permit object to the permit application object. 
- `Payment Type`
- `Check Number`
- `Transaction Date`
- `Payment Status`
