### ISSUE TITLE
Enhancements to Finance Service Requests Following Usability Feedback Sessions

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13547]
### Requests for Existing Feature Enhancements
- [x] The TK drop downs should filter out any TKs where Status is `Inactive`
   - `Add Job` page - added filter for Status is `Active`
   - `New SR Job | Admin` page - added filter for Status is `Active`
   - `New SR Job | Requester` page - added filter for Status is `Active`
- [x] `financial_subprojects` object has been updated with the data from eCapri so we just need to confirm that all the subprojects drop downs can only include subprojects in an `Open` status
   - `Add Job` page - added filter for Status is `Open`
   - `New SR Job | Admin` page  - added filter for Status is `Open`
   - `New SR Job | Requester` page - added filter for Status is `Open`
- [x] Job Type Other needs to have `Other` option added to the “Attachment Type” drop down field
- [x] Need to add `Document ID` field as one of the fields that Finance fills out for the **New FDU** Job Type
   - `Manage SR Details` page - Added `Document ID` and highlight
   - `SR Details` page - Added `Document ID` and highlight
- [x] For `New Object Code` job action under BGEX, add instructions to “Provide FDU and Object Code"
   - `Add Job` page - updated Instructions/Comments field to say "Instructions/Comments - Provide FDU and Object Code"
   - `New SR Job | Admin` page - updated Instructions/Comments field to say "Instructions/Comments - Provide FDU and Object Code"
   - `New SR Job | Requester` page - updated Instructions/Comments field to say "Instructions/Comments - Provide FDU and Object Code"
- [x] Can remove the filter option on the various SR Jobs tables in the SR Details pages
   - `Manage SR Details` page - removed filter option 
   - `SR Details` page - removed filter option 
- [x] Allow in-line editing in the initial `Add Jobs` page and take away inline editing from the review page
    - Took away editing on the `SR Details` page and added it to the `Add Jobs` page
    - `New SR Job | Requester` - copied over the editable fields from the SR Details page and deleted the non-editable tables
    -  `Add Job` page - deleted the non-editable tables and copied the editable tables from the `New SR Job | Requester` page
    - Updated instructions on the SR Details page for Requesters

### Renaming Fields and Buttons 
- [x] Ronnie feels like New SR and New SR Job are very familiar
    - Change `New SR Job` to `Add/Edit SR Job`
- [x] Naming of `Add Job` button is confusing to Ronnie because it makes him think that he’s adding something else. Would like to change the language to `Save Job`.
   - `Add Job` page - updated to "Save Job"
   - `New SR Job | Admin` page - updated to "Save Job"
   - `New SR Job | Requester` page - updated to "Save Job"
- [x] On New Service Request page, Sharon would like to rename `Service Request Subject` to `Service Request Title` and remove the details below that. She wants this field to be filled out with the shortened description of what the SR is asking for. Then she would like to add the “*Provide brief description of request”* to the `Notes to Finance` section.

### Need to follow up with Shelby: 
- [ ] Shelby said the notification email should be adjusted because it was somewhat confusing - need more context
   - Read first few lines and saw it was completed. Realized later that by completed it had been done and the transfer had been done. Failed to go to the bottom. 
   - Shelby was asking if we could move the bottom info up to the top!

**Comment by dianamartin** [comment]
@ChristinaTremel is this okay to close?

**Comment by ChristinaTremel** [comment]
All enhancements on this issue have been made or follow up issues have been created. Closing this.
