### ISSUE TITLE
Raw Data to calculate ROW's total customer base (AMANDA and KNACK) (LP)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13540]
### What’s our customer base? (total annual number of unique permit and TCP customers) 

Query to extract all people RSN's on all ROW's folders created in the last calendar year:
- DS, EX, RW, UC, LC, PSM
- Include every people record on the folder
- Give us a count of the number of unique records

**Comment by Nadin-Nader** [comment]
Priya will do today

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader 
Please find the count of distinct peoplersn for foldertypes DS, RW, PSM, EX, UC , LC for the calander year 22-23 below

DS - 2175
RW - 3036
PSM - 57
EX - 1813
LC - 378
UC - 1120

**Comment by TracyLinder** [comment]
We'll discuss this with ROW this week on 10/27

**Comment by TracyLinder** [comment]
This is good to close.
