### ISSUE TITLE
Update DTS Service Request application values to match new Product Label schema

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#13551]
Reference: DTS Products tab on DTS Product Manager Assignments spreadsheet on google drive.

Will add task list for those updated.

**Comment by ChrispinP** [comment]
- [ ] Right-of-Way (ROW) Portal `updated to` Right of Way Portal
- [ ] Transportation Development Services (TDS) `updated to` Transportation Development Services Portal
- [ ] Updated all service request records with corrected values of all new values to remove data discrepancies

- [ ] Script will also need to be updated from Product: Transportation Development Services Portal `to` Product: TDS Portal

**Comment by amenity** [comment]
Added that last task to an [existing dev-assigned issue ](https://github.com/cityofaustin/atd-data-tech/issues/13406).

**Comment by ChrispinP** [comment]
Pending any further action.

**Comment by ChrispinP** [comment]
Mike updated the ServiceBot script. complete, closing
