### ISSUE TITLE
Query by address

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1355]
# As a RPP Reviewer I need to be able to query an address an see an RPP activity overview.

**Describe the outcome you'd like to see when this feature is implemented.**
RPP history by address

Must have

## Acceptance Criteria
- [ ] Page has table with `Resident Address` and is grouped by the `RPP Address - display name`.

**Comment by dianamartin** [comment]
Created a page called `Addresses` that shows the permit applications grouped by RPP Address. Need more details on what user would like to see on this page.

**Comment by moorerst** [comment]
@dianamartin  just curious, in the name column what does the 2 in front of the name represent?

**Comment by dianamartin** [comment]
@moorerst It's the auto-generated customer ID because we're not asking for other unique ID information like a drivers license number. It's just another way to keep the customers unique when they apply in case we have people with the same name in the system. (ex. Bill Smith)

**Comment by dianamartin** [comment]
During demo there weren't requests for modifications on this. Seemed to be accepted by the users.
