### ISSUE TITLE
IT Support: Chris N. much turn in old PC

### ISSUE THREAD

**Issue by JBStrange** [cityofaustin/atd-data-tech#13554]
Chris N. much turn in old PC to pickup new 2 in 1.

End User return old PC Dell 7560 Dell 81127.

Changed out the PC out for the new 2 in 1 with the blutooth pen.

**Comment by scottreedy** [comment]
Changed out the PC out for the new 2 in 1 with the blutooth pen.
New and old computers are documented in the HW db
