### ISSUE TITLE
New or renewal identifier

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1356]
# As a RPP staff need the ability to identify a request as new, or renewal

**Describe the outcome you'd like to see when this feature is implemented.**
Checkbox for New or Renewal

Could have

## Acceptance criteria

- [ ] When the user submits their application
- [ ] There is a form record rule that defaults the application to a `Permit Application Type` that is `New`

_We will have to discuss whether to create a `Renewal` application to trigger the `Renewal` type_

**Comment by dianamartin** [comment]
Created `Permit Application Type` which has the choices: 
- New 
- Renewal

I think going forward we would want to make a short renewal form for customers that already have a permit in the system.

**Comment by dianamartin** [comment]
During demo there were requests for modifications on this. Seemed to be accepted by the users.

- We decided that we would tackle RPP Renewals in the next roll out. Phase 2.
