### ISSUE TITLE
Scope out solution for addressing FDU / BGEX Job Type issues for Finance Service Requests

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13560]
[Miro Board ](https://miro.com/app/board/uXjVPaEmIPc=/)we're working on to brain storm this
- FDU Job Type is actually just creating a `New FDU`. The other FDU requests are under the BGEX job. Realized that this is confusing to users and Sharon said if she could change it, she would really want to move the items under BGEX to the FDU job type.
- **Shelby**: When closing FDUs I went here, but that is incorrect and had to go to other. Somewhat confusing.
    - Need to add Task Action added to `Close FDU` and `Modify FDU`
        - Enter FDU to close
        - Required Notes field: Where do you want to move the funds
    - Add to Job Type `FDU`
- Need to add an option for `Close FDU` to the Job Action drop down for the **FDU Job Type**
    - Would need the FDU field for the Requester to provide which FDU they are requesting to close
    - Need some sort of comments field or FDU field with instructions like “Default will send the FDU balance back to the parent. If you want the balance to be moved to another FDU, please list below”
- Also need to add an option for `Create New FDU` and if this is selected, the user would then choose `Using new Subproject` or `Existing Subproject`

**Comment by ChristinaTremel** [comment]
## Decision
**Discussed 9/6 during the Updates to Finance SR Following Usability Testing meeting**
- Eliminate BGEX
- Move Actions under BGEX -> FDU
- FDU Task Action Options:
   - New FDU with New Subproject Number
   - New FDU with Existing Subproject Number
   - FDU Fund Transfer 
   - New Object Code

**Comment by dianamartin** [comment]
# 9/15
## Display Rules
New SR Request
- Rule 4, 5, 6, 7

**Comment by ChristinaTremel** [comment]
Showed this to the Finance team last week on 9/20 and they were happy with the changes!
