### ISSUE TITLE
Responsible Party People Type - Add Bond + Ins Infos (PROD UAT Approved, need to Run Batch)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13576]
### Add 2 info types to the Responsible Party people record

** Acceptance Criteria **

- The info fields provided below need to be added as People Info to all Responsible Party People Type records.  
1. Bond Expiration Date 58085
2. Insurance Expiration Date 75350
- These infos already exist in AMANDA, and currently no other validation is necessary.

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/19bb1966-718f-4db8-bcb6-235741135b23)

**Comment by TracyLinder** [comment]
We will assign this to Subha when she gets back from VCU

**Comment by Nadin-Nader** [comment]
Bond status doesnt change when it expires on the License record, it doesnt update. If it is not updating the status then the Expiry date is needed/ just fine. But ideally they would like both to work

**Comment by TracyLinder** [comment]
### Not creating status fields
1. We'd have to create new functionality to have the system auto-update the status fields based on the expiration date. This will be another ECM feature we'd have to replicate and we're trying to cut back on unnecessary new functionality for this reason.

**Comment by TracyLinder** [comment]
@vschandramouli please confirm with Kyle and update AC as necessary.

**Comment by vschandramouli** [comment]
Confirmed from Kyle that no other functionality is needed at the moment except for adding these infos to the People record. Updated AC, moving to Backlog.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Please raise a DEV/TEST promotion request for the completed work. Thanks.
[13576-01debdf9387d- DEV TEST Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/12823143/13576-01debdf9387d-.DEV.TEST.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to DEV and TEST under **SCTASK0361016**

**Comment by Nadin-Nader** [comment]
Kyle has approved this to go to PROD.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0364488**

**Comment by SubhaShroff** [comment]
Thank you for creating a dep request Nadin.
@Nadin-Nader  @KyleErich This is in PROD. Please review.

**Comment by Nadin-Nader** [comment]
Sent Kyle a message via Teams that this is ready for UAT on PROD. Waiting on Response

**Comment by TracyLinder** [comment]
Closing - Delivered
