### ISSUE TITLE
Query by zone

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1358]
# As a RPP staff I need to be able to query RPP cases by the zone #

**Describe the outcome you'd like to see when this feature is implemented.**
Address associated with zone 

Must have

## Acceptance Criteria
- [ ] On the page `Advanced Search`, a user can search by various keywords. One is `District` (this is District Zone)
- [ ] Results show the `District` that the permit was issued

**Comment by dianamartin** [comment]
During demo there weren't requests for modifications on this. Seemed to be accepted by the users.
