### ISSUE TITLE
Release VZ v1.37.0 - Pease Road

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13591]
### Prior to Release
- [x] Schedule release party - @patrickm02L 
- [ ] Advise users of downtime - @patrickm02L
- [x] Do testing
- [x] Propose + vote on release names - @patrickm02L 
- [x] Create a [release](https://github.com/cityofaustin/atd-vz-data/pull/1278) - @mddilley
- [x] Test migrations and metadata using release branch code and local DB restored from production DB data dump
- [x] Refine [release notes](https://github.com/cityofaustin/atd-vz-data/releases/tag/v1.37.0) @patrickm02L 

### Release/Deployment Steps 
- [x] [snap database in RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_CreateSnapshot.html) - @mddilley 
- [x] Apply migrations and metadata - @mddilley 
- [x] graphql-engine version bumps (releases & tags) - @mddilley 
  - [x] Local dev to v2.33.4 [release notes](https://github.com/hasura/graphql-engine/releases)
  - [x] staging task definition to v2.33.4 with T.D. 24
  - [x] production ECS task definition to v2.33.4 with T.D. 19
- [x] merge to prod - @patrickm02L 

### Post Release
- [x] Bump VZ **staging** version to `v1.38.0` and VZ production to `v1.37.0`- @mddilley 
- [x] Send out release notes - @patrickm02L 

[Release Management Process gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/product-ops/release-management-process)

**Comment by patrickm02L** [comment]
## 9/22
Need to Merge
- Get Rose to merge PR 1290 - lambda
- And PR 1291 - 404 page
- Tilly's copy email PR #1294

Migrations
- 1269 - migration blueform
- 1284 - remove micromobility flag

**Comment by mddilley** [comment]
Dropping a note that we need to turn off the DAG named `vz_reassociate_missing_locations` after release tomorrow. The new CR-3 and non-CR3 location triggers replace the process that is cleaned up by that DAG. Eventually removing that code for the DAG is captured in https://github.com/cityofaustin/atd-data-tech/issues/13190.

**Comment by patrickm02L** [comment]
One more pease of the puzzle complete
