### ISSUE TITLE
Identify customer - Applicant Type

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1359]
# As a RPP staff need to be able to identify if the customer is an owner, a tenant, or a property manager

**Describe the outcome you'd like to see when this feature is implemented.**

Must have

## Acceptance Criteria

- [ ] When the customer starts their RPP application Part 1 of the form shows customer fields
- [ ] The fields they are required to fill out are:
- Name of Applicant
- `Applicant Type` - this identifies the customer as a `Homeowner`/`Renter`/`Property Manager`
- Phone
- Email

**Comment by dianamartin** [comment]
In the `customer` object table, there is a field for `Applicant_Type`. 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/fd7ae46f-946e-4081-9351-3f8c08f6320a)

**Comment by dianamartin** [comment]
During demo there were requests for modifications on this. Seemed to be accepted by the users.

- We decided not to add `Property Managers` as a type.
