### ISSUE TITLE
Investigate VZ polygon inconsistencies for Milad K's workflow

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#13596]
Milad has outlined a data inconstancy which he is observing in his polygon maintenance workflow. His request for information is available below. 

[polygon_question.pdf](https://github.com/cityofaustin/atd-data-tech/files/12477402/polygon_question.pdf)

**Comment by patrickm02L** [comment]
## 8/31 
- Let Milad know that QGIS can connect to the read replica VZDB

**Comment by patrickm02L** [comment]
Milad initially approached us seeking assistance with his issues, and we aimed to address them using the Polygonizer tool. However, as Milad has opted to explore other methods for managing polygon data, our involvement is no longer aligned with his chosen direction.

Once Milad publishes his polygons to the `vision_zero_polygon` layer in MAINT, the geo team will be able to evaluate any inconsistencies within the polygons.
