### ISSUE TITLE
Maximo, Austin 3-1-1 Standardization Project

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#13611]
To address 311 audit 

## Background
311 was audited and they were asked to make citywide changes and had to go through this large effort.

## Scope & Deliverables
The Maximo team was going to update all the SBO Service Requests to be in compliance with 311's standardization request. This would involve lots of training and reconfiguration of the system. 

## Desired Outcomes
311 was asking the stakeholders to standardize their 311 outcomes in Maximo so that citizens could see the actual work completed by staff.  

## Timebox
9 months - 1 year

## Concepts and references

Helpful links; e.g. other solutions, screenshots of Slack convos, customer’s original request, anything too long for the one-pager that can exist as a separate doc. Folder in Drive where project assets are stored.

## Request details
- Executive sponsor:
- Date:

https://atd-dts.gitbook.io/wiki/product-ops/dts-website#images
The first image will be used as the project's thumbnail image on the website.

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by ChristinaTremel** [comment]
We discussed this at the Maximo sync and Adriana noted that the standardization project has been completed. We are in the phase of performing data quality reviews.
