### ISSUE TITLE
Process Updates & Training Efforts

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#13615]

**Comment by adry-martinez** [comment]
Duplicate to https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/gh/cityofaustin/atd-data-tech/13771

**Comment by adry-martinez** [comment]
Duplicate to https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/gh/cityofaustin/atd-data-tech/13563
