### ISSUE TITLE
Record serial # for each permit

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1361]
# As a RPP Reviewer needs to record the serial numbers for the decals and hang tangs issued to customers

**Describe the outcome you'd like to see when this feature is implemented.**

Must have

## Acceptance Criteria
- [ ]  When RPP staff are on the Issue page, they will see a form that allows them to choose several fields before they click the `Issue` button 
- [ ] If the Permit Type is `hang tag` the `Serial #` field will appear, otherwise it will be hidden from the form

**Comment by dianamartin** [comment]
On the `permits` object table, I have a field for the `Serial Numbers`. It is on the permit form that the RPP Staff fills out.

**Comment by dianamartin** [comment]
During demo there was a request to have the `Serial #` appear when issuing Day Passes as they are issued out by number range. The display rule was modified to show this.
