### ISSUE TITLE
Digital application

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1362]
# As a RPP Customer needs to submit applications and support documents online, from anywhere

**Describe the outcome you'd like to see when this feature is implemented.**
Digital application

Must have

## Acceptance Criteria
- [ ] When the user fills out the application there is a page Part 2 of the application that shows the `Required Documents`
- [ ] The user is able to attach `Proof of Residency` and `Driver License/ID card` as part of the Required Documents
- [ ] This form is available via a web browser, only internet is required to access the application.

**Comment by dianamartin** [comment]
Applicants can access the RPP Application form via web browser and attach their `Required Documents` all online. 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/99a1f639-7497-485c-9bc9-59ce090e2090)

**Comment by dianamartin** [comment]
During demo there were requests for modifications on this. 

- May be modifying due to combining the Day Pass and Permit applications.

**Comment by dianamartin** [comment]
This application was modified and now permits and day passes are combined on one application

**Comment by dianamartin** [comment]
Need to show stakeholders at 3/5 Sprint Review

**Comment by dianamartin** [comment]
RPP Staff confirmed forms are working as they expected.
