### ISSUE TITLE
Application status dashboard

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1363]
# As a RPP Reviewer need to have an RPP staff dashboard to help us identify what work needs to be done next

**Describe the outcome you'd like to see when this feature is implemented.**
Dashboard view of application status

Should have

## Acceptance Criteria
- [ ] When the RPP Staff user logs into the home page, they will be redirected to the `Permit Management` page
- [ ] That page will show a table of the permit applications that have been submitted 
- [ ] That page will have various filters based by Application Status so that a worker can toggle back and forth from different status queues

**Comment by dianamartin** [comment]
This may change slightly when we combine Day Pass and Permit applications into one

**Comment by dianamartin** [comment]
We removed the column for Permits and Day Passes, we just have the one column `Application ID`.

**Comment by dianamartin** [comment]
Steve was happy with the changes we have made, not modification comments were made in our last Sprint Review.
