### ISSUE TITLE
Identify application status

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1364]
# As a RPP Reviewer Need to identify the status of an application. 
#### (Needs Review, Reviewed - Pending Payment, Reviewed - Needs Documentation, Complete - Permits Issued, Ineligible, Withdrawn/Cancelled

**Describe the outcome you'd like to see when this feature is implemented.**
Assign status to application during process

Must have

## Acceptance Criteria
- [ ] When the application is submitted and the RPP Staff click on an application record it will bring them to the application details page
- [ ] They will see a menu on the top of the page (especially for RPP Staff Use) 
- [ ] There is a 'Change Status' button on the menu
- [ ] This button open a modal form that allows the user to change the `Application Status`.
- [ ] The default status should be when the application is initially submitted is `Needs Review`

**Comment by dianamartin** [comment]
On the `permit_application` object table, we have a field for `Application Status`. The drop down choices are: 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/cece6e87-5350-4b43-9203-a68e6a3cc114)

**Comment by dianamartin** [comment]
During demo there weren't requests for modifications on this. Seemed to be accepted by the users.
