### ISSUE TITLE
Complete Safety SharePoint Migration after TPWHub Launch

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#13651]
There are two existing Safety SharePoint sites - Diana checked with Jennifer W. and we will rebuild from [the PWD-originating site](https://cityofaustin.sharepoint.com/sites/PW/Safety/SitePages/Home.aspx). 

Set up a meeting for us to to discuss on Fri 9/15 with Jennifer W., Chris W., and Mike B.

**Comment by KaroEngstrom** [comment]
## Meeting 9/20/23 

In the room: Mike B, Jennifer W, Christopher W, Diana, and Karo

Looking at existing legacy sites: 
- [ATD Safety](https://cityofaustin.sharepoint.com/sites/atdSafety/ )
     - Less material here; likely will not have content to move over (to be determined) 
- [PWD Safety](https://cityofaustin.sharepoint.com/sites/PW/Safety/SitePages/Home.aspx) 
     - The main site where items will be migrating from, both as tiles/sections and some actual file content  

### The Plan 
- new site will be built out as tpwSafety (not yet published) - the team in the room will get access as well as Robert C. 
- the initial build will feature the basic pieces identified by Mike (see list below)
- MIke's team will assess the content and determine what else needs to be moved over 
- Note: Mike expressed the interest in hosting training videos and routine safety presentations from his team on the site; Karo mentioned using Stream and embedding video to SharePoint pages as one option to offer training content seamlessly in SharePoint 

**Specific Items for Migration**
- Newsletter - NO
- Project Mgmt CID - NO
- Safety Recon - NO 
- Safety Procedures - NO for now, need to look at against what ATD had so this is a longer term project 
- Calendar - YES 
- Checklists - YES
- Training - YES (Mike will have to assess content but can built a placeholder because this section will stay for sure) 
- Other items in buttons - YES

## Next Steps: 
- [ ] Create tpwSafety team site
- [ ] Add basics from above 
- [ ] Add users
- [ ] Notify Mike of the draft build 
- [ ] Follow up with Mike's team in a few weeks to assess the plan and situation

**Comment by dianamartin** [comment]
# 7/30/24
Messaged Jennifer
>Hi Jennifer, 
Was wondering what your plans are for moving the old legacy Safety content to a new space? the CDS IT team is telling us we need to migrate it because it's on the former legacy PWD SharePoint site still. 
 
>Let me know who Karo and I need to collaborate with on this.
 
She replied
>Chris W. is the Acting Manager, but he is out for 2 weeks sigh. Can we just move all formatting over to a TPW site, then start picking it apart? Does it not work like that?

I replied
>We can create a separate tpwSafety SharePoint site if we think we'll use it in the future. We can also move the legacy files over there too and then rebuild it when ready. Is that what you're thinking?

She said
>Yes, I think we are on the same page. Most of the content should be COA standard stuff, but there may need to be some rebranding. Plus I would love to see them modernize the content and actually build a program to communicate through the SP site. Big dreams. But for now, i would hate to not have the data available for staff to view.  

I checked this issue and site and saw that we had already built it ([tpwSafety SharePoint site](https://cityofaustin.sharepoint.com/sites/tpwSafety/SitePages/Home.aspx)) 

- I let Jennifer know and that we'd work on it

**Comment by dianamartin** [comment]
# 7/30/24
- Created new workflow to QA if all files had been moved in [SharePoint Planning miro](https://miro.com/app/board/uXjVOlklr5k=/)
- [x] Created folder for "Project Management and CID Resources"
- [x] Moved legacy files to that new folder
- [x] Created folder for "Safety Procedures"
- [x] Created folder for "Safety Recognition Program" 
- [x] Download the PDF and put it in the folder

**Comment by dianamartin** [comment]
# 7/30/24
- Updated the tpwSafety Sharepoint Home page a little incase Jennifer wants to take a peak
![image](https://github.com/user-attachments/assets/2ed20c72-1c55-4c27-893f-dbbec1b2c5e7)

Reached out to Katherine H. 
>Hi Katherine, 
 You're with our TPW Safety work group, correct? If so, do you know who on your team might know about any plans for updating the TPW Safety SharePoint page? I know Chris Williams is acting and out for 2 weeks, but didn't know if the team knew of any plans. I'm with the Data and Technology Services team for TPW and just trying to update the SharePoint websites.
