### ISSUE TITLE
Assist Joel M. with access to the read replica via DBeaver

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#13657]
Joel wrote me on Friday asking if I could help him with DBeaver and the VZDB read replica. This ticket is to track the preparation of his credentials and a call to get him setup. @patrickm02L, since he wrote me directly, I hope you don't mind if I self assign and get this squared up. Let me know if there's another way you'd like to handle this. Thanks!

**Comment by frankhereford** [comment]
I wrote Joel and invited him to a meeting to get this ready. Our first common open time slot is on Friday - he has a busy week this week!

**Comment by patrickm02L** [comment]
@frankhereford this is SO cool, do it! :evil-kermit

**Comment by frankhereford** [comment]
I spoke with Joel this morning, and we got this taken care of.
