### ISSUE TITLE
[Enhancement] Add parent and child project names to project list view

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#13675]
Add a column to the project list view that shows the name of a project's parent project, if it exists.

Add a column to the project list view that shows the name of the project's child projects, if they exist.

☝️ should we combine those into one column, since. a project cannot have both a parent and children?

**Comment by chiaberry** [comment]
wrt to combining: As long as its not confusing if the project listed is a parent or a child

Can a project be a grandchild of another project?

Actually now im leaning more towards keeping them separate columns, so you could sort the columns by only parents or childrens
