### ISSUE TITLE
Identify how application was received

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1367]
# As a RPP Reviewer Need to identify how an application was received (in person, online)

**Describe the outcome you'd like to see when this feature is implemented.**

Could have

## Acceptance Criteria
- [ ] When the application is submitted and the RPP Staff click on an application record it will bring them to the application details page
- [ ] They will see a menu on the top of the page (especially for RPP Staff Use) 
- [ ] There is a 'Change Status' button on the menu
- [ ] This button open a modal form that allows the user to change the `Application - Received Type`.
- [ ] The default status should be when the application is initially submitted is `Online`

**Comment by dianamartin** [comment]
Added field `Received Type` on the `permit_application` object table. Updated the `Edit Application` form for the RPP Staff so they can change it.

**Comment by dianamartin** [comment]
During demo we decided we didn't need to have this field anymore. This was deleted.
