### ISSUE TITLE
Prototype Survey123 form

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13697]
@andrewshensky or @ATD-ZachB as part of the Living Streets app, we'll need create a prototype of the mapping part of the app to include in the initial application

This Issue is coming out of the Apps 9/6/23 planning meeting

**Comment by dianamartin** [comment]
# 9/6
- [Article: embed a survey using an iframe](https://developers.arcgis.com/survey123/guide/embed-a-survey-using-an-iframe)
- Amenity brought up another idea if we need to pivot:

### Option 2.5
  - embed the survey123 form in Knack (captures geo points and application ID)
  - complete the application in Knack 
    - email notifications
    - record management

**Comment by andrewshensky** [comment]
Suvery123 is no longer being consider for use in this project.

The prototype created for this did show strong potential for integrating survey123 with experience builder to be able to generate related records to existing features on the fly. 

https://experience.arcgis.com/builder/?id=26cf81087746420b97f639e338351a1d
