### ISSUE TITLE
Communication w/ Executives on Living Streets initiative

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13695]
## Description
- Reminder to be cognizant that upper leadership will be interested to hear about how this project is progressing, especially because it's a MPT Ellis driven initiative

**Comment by dianamartin** [comment]
@patrickm02L Should we check in with SMO to see if they've done this communication already?

**Comment by patrickm02L** [comment]
## 11/14
Peggy mentioned reaching out to Lewis L. in our monthly meeting to let him know of our success. 

I was also thinking that as the project rolls out and there's more publicity around it that would be an opportune moment to check in with the Execs.

cc @dianamartin

**Comment by patrickm02L** [comment]
## 11/17 
Living Streets application was announced as being ready to accept applications. [See X post](https://twitter.com/safestreetsatx/status/1725174670213652543?s=20).

Now that it's rolling out, we should connect with the Living Streams program to see if they've talked to Execs and make sure that we're talking about DTS contribution with them.

**Comment by patrickm02L** [comment]
## 12/14
In our check-in meeting with Matt and Jonathan 12/11 we talked about how we could communicate our Apps work to Executives. Matt said he was putting together a thank you letter to all involved in launching the program, and was making sure leadership knew about it.

**Comment by patrickm02L** [comment]
We've asked Matt about this several times in Reviews. By now the Executives know. Considering this closed.

**Comment by patrickm02L** [comment]
## 4/4/24
Sent via Matt M.

> All,
> 
> Living Streets Program team would like to extend our appreciation and gratitude to all who worked with us to create the program and continue its development. 
> 
> On Friday, January 5th Living Streets had its first application deadline.  The Living Streets team met Friday January 12th and confirmed we could fund and lift 10 Healthy Streets and 7 Play Streets. We officially had our ribbon cutting ceremony at Wooten Healthy Street on March 19th.  This has been no small feat and our team in Smart Mobility Office wants to acknowledge those who have worked on this effort.
> 
> We would like to recognize our predecessors in Smart Mobility for taking on this task.  We want to recognize Laura Dierenfield and the rest of the Active Transportation team, Office of Special Events (then under the direction of Frances Hargrove and now with Annette Martinez at the helm) for developing the concept of the Living Streets Program and its three activations:  Neighborhood Block Parties, Play Streets, and Healthy Streets with our team.
> 
> As the program developed and went through the planning phase, we worked closely with DTS on viability, mapping and the application process.  We partnered with Transportation Engineering on developing the street typologies and their geometries and closures.  And PIO on the marketing, outreach, communications and collateral for the program.  These three teams provided critical support and met regularly with us to develop the program.  Additionally, we worked with divisions and programs that provided direction, guidance and support along the way.  Right of Way Management worked with us on conflict management and supported TED and the Living Streets staff on the closures.  TPW operations teams provide equipment for demonstrations and outreach opportunities on numerous occasions.
> 
> The program is only in its first 6 months of installations (seen here in the map), and we are continuing to receive expressions of interest.  We are working with Joel Meyer and the Vision Zero Team to determine impact of Living Streets on safety.  John Eastman and Ming are working closely with us on how to transition, test and share outreach as a Living Street moves from a temporary activation to permanent infrastructure under Shared Streets.  We will continue to improve the program and look forward to continuing our efforts with your teams.
> 
> Best,
>
