### ISSUE TITLE
Spike: Create ETL from AGOL to Knack

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13690]
## Description
Devs to look into the feasibility of porting data from AGOL through the survey123 tool to the Knack Living Streets app.

## Deliverables
- Review the fields that we're anticipating collecting

**Comment by johnclary** [comment]
I did some quick snooping and found [this AGOL layer](https://austin.maps.arcgis.com/home/item.html?id=32ff894159294337a5378bba31445933&view=list&sortOrder=desc&sortField=defaultFSOrder#data) which i believe is a Survey123 layer. the short answer is that the layer looks normal we should be able to create an ETL using normal AGOL REST Api operations or the `arcgis` for Python library.

i don't think a dev can investigate this any further without having concrete sample data from a Survey123 layer that contains all of the data types we anticipate will be used in the app. E.g., if there will be multiple choice fields in the survey123, the dev needs to see how that data is stored in AGOL, and what data type will be needed in Knack. another example: do we need to support related tables between AGOL and Knack? what is the structure of relationships?

lastly: are you sure that the app does not will be a one way flow from AGOL to Knack? the level of complexity is much higher when data is being pushed in both directions.

**Comment by patrickm02L** [comment]
We will not be using Survey123 as explained in #13697, which means we will not need Dev support
