### ISSUE TITLE
Living Streets email notifications

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13691]
## Description
- Survey123
- Knack

## Notes
@dianamartin please fill out/refine this Issue

## Option 1
- This is our current plan, using Survey123 form for a customer application intake
  - Once customer submits application, system should submit an email confirmation
- Survey123 has the ability to send custom emails with web hooks
  - Under `Settings> Webhooks`
  - [Documentation](https://doc.arcgis.com/en/survey123/browser/create-surveys/webhooks.htm)

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/fc77b36b-aec1-481f-8223-a43fcb2af4f0)

#### Add Webhook Options
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b8961a4a-d3ff-4f84-87e6-5efd6c5e85af)

## Option 2
- If we have to pivot for any reason to have a knack form application intake
- We can set up email notification emails in the system

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b2bce0bf-ea32-4fd1-8146-3530f3ce4113)

**Comment by susannegov** [comment]
# Some notes on Survey 123
- The user is able to select an existing line segment from an ESRI web map with a side bar to fill out a form with email and data record functionality.
     - It requires the desktop version called Survey123 Connect (not web version) in 2019. Not sure now.
- Webhooks in Survey123 does connect in Make without any permission issues if we needed to customize email capabilities for any reason
- I made a somewhat similar app using Survey123 Connect (desktop version) and ArcGIS Dashboard. It was for long line inspections back in Nov 2019.
   - Not familiar with Experience Builder, but there's an article on it that might be better suited than using ArcGIS Dashboards fyi: https://www.esri.com/arcgis-blog/products/experience-builder/real-time/using-experience-builder-and-survey123-to-pass-attributes-and-geometry-from-one-layer-to-another/
   - Link to dashboard w/ form as an example: https://www.arcgis.com/apps/dashboards/3bff70e960ee46089a172a5a1a342a35
      - This is no longer used. Since it was made in 2019 and the way AGOL data is parsed has changed so a lot of the views are broken. The functionality was also slightly more limited back then.

**Comment by KaroEngstrom** [comment]
9/19/23 - this should just come from Knack.

**Comment by KaroEngstrom** [comment]
Showed this to stakeholders last week and they were pleased with the Knack functionality. There are more emails that need to be added to the process but I think this issue would be closed.
