### ISSUE TITLE
Migrate atd_txdot_locations triggers

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#13702]
Triggers:
- atd_txdot_location_audit_log (insert)
    - Populates description column by trimming and also splitting the string by the '@' character and sort them into alphabetical order
    - Populates scale_factor column
    - Populates latitude and longitude fields with the centroid of the shape
    - Updates last_update column 
- atd_txdot_location_audit_log (update)
    - Same as insert trigger
- atd_txdot_locations_updates_crash_locations
    - Updates location_id column in atd_txdot_locations table

**Note: `atd_txdot_locations` and related triggers were brought over into the LDM collector branch migrations in https://github.com/cityofaustin/atd-vz-data/pull/1305. These triggers can be edited in place in the LDM instead of needing to be migrated from non-LDM to LDM.**

See more details in https://docs.google.com/spreadsheets/d/1Gxl-d56n89LlM9n99weCMKZz9oQCxkcqhHgkDHBgRmQ/edit#gid=0

**Comment by patrickm02L** [comment]
## 9/13
- as part of this Issue we should look at what's in the locations table and drop the crufty columns from this table that are no longer relevant
