### ISSUE TITLE
Migrate crash_notes triggers

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#13706]
Triggers:
- set_public_notes_updated_at
    - Populates updated_at column 

See more details in https://docs.google.com/spreadsheets/d/1Gxl-d56n89LlM9n99weCMKZz9oQCxkcqhHgkDHBgRmQ/edit#gid=0

**Comment by johnclary** [comment]
These triggers do not need to modified as part of the layer data model project 👍
