### ISSUE TITLE
Explore Cognos reporting options

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1370]
Objective: Determine whether we can use custom Cognos reports to get Brazos data into PowerBI reliably and efficiently. 

Reported fields:
- Can we add Secondary Street to the report that we generate so that we can roughly geolocate citations? 
- Are there any other fields that would be useful?

Report delivery: 
- Is there a way to access reports via FTP so that we could have a programmatic integration? 
- Can we schedule automatic emails? 

... @johnclary @SurbhiBakshi - what else?

**Comment by SurbhiBakshi** [comment]
@johnclary @amenity I will also look to see if automatic downloads on the network drive are possible.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/f42ea2c8-d2c2-4a03-a386-52e2b1b71149)

**Comment by SurbhiBakshi** [comment]
@johnclary @amenity -  I looked at the documentation on the site, realized it was sparse and dated. I went through the list of existing reports to see if we could cross reference another report with better location information.  I looked for the report we were referencing earlier. It looks like a Cross Street Full field has been added in the report.

**Comment by amenity** [comment]
😆 🤦‍♂ Classic, Tyler. 

I guess the other thing to check for in Cognos would be the ability to configure automatic downloads, ftp access, etc.

**Comment by SurbhiBakshi** [comment]
@amenity will look into that

**Comment by SurbhiBakshi** [comment]
@amenity - looked around and I don't see any clear way to configure automated downloads.

**Comment by johnclary** [comment]
@SurbhiBakshi can you test out the option to have the report sent via email? if that works, we could automate that process.

**Comment by SurbhiBakshi** [comment]
@johnclary will do!

**Comment by SurbhiBakshi** [comment]
@johnclary  I was able to email the report to myself.
