### ISSUE TITLE
Migrate atd_txdot_crashes triggers

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#13701]
Triggers:
- atd_txdot_crashes_audit_log (insert)
    - Inserts change log record into atd_txdot_change_log for crashes table changes
    - Populates lat/lon primary columns from geocoded coordinates first or CRIS coordinates second and then updates the position column from the primary lati/lon columns
    - Initializes atd_fatality_count from death_cnt; initializes apd_confirmed_death_count from death_cnt
    - Initializes the Y/N apd_confirmed_fatality field from death_cnt and sets apd_human_update based on if there has been an edit 
    - Populates est_comp_cost, est_comp_cost_crash_based and est_econ_cost fields using injury or death counts and cost tables data
    - Calculates speed_mgmt_points using injury or death counts and atd_txdot__speed_mgmt_lkp table data
    - Populate atd_mode_category_metadata using get_crash_modes()
    - Updates last_update column
- atd_txdot_crashes_audit_log (update)
    - Same as insert trigger

See more details in https://docs.google.com/spreadsheets/d/1Gxl-d56n89LlM9n99weCMKZz9oQCxkcqhHgkDHBgRmQ/edit#gid=0

Is affected by the `changelog`

**Comment by patrickm02L** [comment]
## 9/13
- We'll need to break this down into smaller triggers

**Comment by patrickm02L** [comment]
## 9/27
- The initial break down is proposed in the main description
- Part of whoever takes this on responsibility will be to help create individual Issues, @patrickm02L to help coordinate
- reference Crash [audit log gist](https://gist.github.com/frankhereford/b51a87924bc069fb4a1237a6d9104615)

**Comment by johnclary** [comment]
this looks like it will be fun! fwiw, it might ideal to split this into multiple triggers and chain them together.

**Comment by mddilley** [comment]
Closing since we are moving the VZ data model in a different direction. See https://github.com/cityofaustin/atd-data-tech/issues/15976
