### ISSUE TITLE
Added 8741 and 4730 fund options to AMD Data Tracker

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13711]
Ronnie needed 2 additional Fund options on the drop down for work orders. The Funding numbers were:
- 4730 | Parking CIP 
- 8741 | GGCIP - Parks and Recreation

**Comment by dianamartin** [comment]
# 9/6
- [x] Added new "Funding" numbers per Ronnie B.
  - [x] `4730`
  - [x] `8741`
