### ISSUE TITLE
Update DTS Website to clarify our division and department names

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13710]
@chiaberry pointed out that the footer is the only place on our homepage that actually says "Data & Technology Services" ... 🙃 

Let's replace the current H1 text, `Digital Services for ATX Mobility` with `Data & Technology Services`. 
<img width="1595" alt="Screenshot 2023-09-05 at 4 44 56 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/6a830dd3-6f42-4a39-b796-b2629b0571cb">

Also, can we update this metadata? 

<img width="1479" alt="Screenshot 2023-09-05 at 4 43 08 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/349d7a3a-227a-41c7-8de6-ce1f26da4c78">

**Comment by patrickm02L** [comment]
What should the meta data say?

**Comment by chiaberry** [comment]
@patrickm02L Transportation Public Works instead of ATD
