### ISSUE TITLE
[Enhancement] Configure all Airflow tasks to use the docker connection

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#13726]
See https://github.com/cityofaustin/atd-airflow/pull/165

**Comment by mddilley** [comment]
@johnclary I just tripped over this one when looking at devops tagged issue, and this looks done. I think that you can cash in these points? 💰

**Comment by mddilley** [comment]
Take a peek at https://github.com/apache/airflow/releases/tag/2.9.3 but we will figure out an upgrade schedule.

**Comment by Charlie-Henry** [comment]
We should be up to date!
