### ISSUE TITLE
Maximo, SBO/SMD Striping Requests Project

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#13721]
Maximo report will be used to request restriping from Signs and Marking Division. Project Coordinator will fetch this report every 2 weeks and communicate to Signs and Marking Supervisors. 

## Background

Project coordinators team used  a form to request restriping from  Signs and Marking division.

## Scope & Deliverables
Specifications will added for each classification, crew will update these specs and Maximo report will track these restriping requests. Project Coordinators will update specifications once these requests are communicated to SMD team.

## Desired Outcomes

Maximo Start Center and Report that will be used to communicate to SMD team

## Timebox

How long should this take to build; optional section w/ caveats for more complex projects.

## Concepts and references

Helpful links; e.g. other solutions, screenshots of Slack convos, customer’s original request, anything too long for the one-pager that can exist as a separate doc. Folder in Drive where project assets are stored.

## Request details
- Executive sponsor:
- Date:

https://atd-dts.gitbook.io/wiki/product-ops/dts-website#images
The first image will be used as the project's thumbnail image on the website.

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by adry-martinez** [comment]
sent document to Dipa for review and approval to begin collecting signatures on SOP 10/5

**Comment by adry-martinez** [comment]
remind PCs to update Specs once report is sent.

**Comment by adry-martinez** [comment]
sent e-mail to UER DM 10/20 and 10/25, pending signature.

**Comment by adry-martinez** [comment]
Signatures collected. Pending final signature from Ryan Harding. Requested to meet to review PCs responsibilities again. PC Chagoya has been OOO. Planned to discuss this topic during PC meeting 11/28, Harding requested to be cancelled since not all staff members are in the office.

**Comment by adry-martinez** [comment]
Met with PC team, all agreed on proposed document. Pending final signature from PM Ryan Harding.

**Comment by adry-martinez** [comment]
All signatures collected. 
SOP published on Maximo Sharepoint.
Project completed.

**Comment by adry-martinez** [comment]
@dianamartin I updated this project. Let me know if there's anything you need me to change on this. Thanks!
