### ISSUE TITLE
[BUG] DTS Service Request display rules issues

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13746]
**Describe the bug**
- Zach received an `IT Support` issue that didn't have the "What application are you using?" field filled out. 
- Kate and I were looking into what might have happened and noticed a bug in some of the display rules between the "what do you need help with" options

**[URL](https://atd.knack.com/dts#new-service-request/)**

**What steps can we follow to reproduce the bug you are seeing?**
1. Click on `New Project` option in the "what do you need help with" field
2. Click on `Something Else` option
3. Then click on `IT Support` option
4. The "what application are you using" field stays hidden

**Screenshots**
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/f092aa0e-7cba-4c21-9538-f9237c434094)

**Comment by dianamartin** [comment]
# 9/7
- Added rule on # 3
- Show `What application are you using?`
@ChristinaTremel can you test this?

**Comment by ChristinaTremel** [comment]
Tested using the steps above and the rules on `IT Support` are working. 👏🏼 

@dianamartin the only thing I wasn't sure about is should the `Something Else` option show the "what application are you using"? It's showing it now and wasn't yesterday!

**Comment by dianamartin** [comment]
# 9/15
- Going to review the Miro [board](https://miro.com/app/board/o9J_l_98Nc8=/?share_link_id=367469448125) to see if there should be any further display rules changes when we update the new "Geo" fields

**Comment by dianamartin** [comment]
# 10/27
Had tested this out in Miro and found that DTS Service Request was working, fixed any kinks in the issue.
