### ISSUE TITLE
Pavement Data Reconciliation

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#13756]
Pavement Data Reconciliation

**Comment by adry-martinez** [comment]
Received data from Ron K. for crack seal, fog seal, and overlay. Sealcoat pending.

**Comment by adry-martinez** [comment]
Reached out to OCE to review data reconciliation, pending response.

**Comment by adry-martinez** [comment]
Discussed with OCE Ron K. last Thursday regarding discrepancies. Sent out spreadsheets for crack seal, overlay, and sealcoat for his review. Pending response.

**Comment by adry-martinez** [comment]
Reviewed data from Ron K. There are discrepancies in width in his Report vs Maximo. Several widths are being recorded for one project through different days whereas Maximo is recording one width. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmNiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4fe1feaf7689d241400a9d04860cf255d48fafbb/image.png)

**Comment by adry-martinez** [comment]
advised Overlay Superintendent to review discrepancies and correct the area to reflect TOTAL repairs conducted over a series of several days.

**Comment by adry-martinez** [comment]
spoke with OCE Koehn and PC Ewing regarding recording different widths. PC Ewing wants to maintain one work order to reflect all lane miles for that project and use the log notes for multi-day projects. Pending confirmation of process.

**Comment by adry-martinez** [comment]
sent e-mail to Pavement Ops management and OCE to confirm data reconciliation. Pending confirmation from DM Bunton regarding data used for TPW Stat.

**Comment by adry-martinez** [comment]
10/26 sent e-mail to Pavement Ops management and OCE to confirm data reconciliation.

**Comment by adry-martinez** [comment]
No response received from OCE. Issue closed.
