### ISSUE TITLE
Try out private Knack server to see if it fixes performance issues

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1376]
After #1124, Steve agreed to have the Signs and Markings app stood up on a dedicated server to determine whether this resolves the issue.

**Comment by amenity** [comment]
Email update from Steve:

> Looks like we can have the private infrastructure in place toward the end of next week. Unfortunately, takes a bit of time to setup, test, and deploy before moving your app into the environment for testing. We really didn't have the opportunity last week due to our retreat.
> 
> Sounds like complexity is the theme in terms of the issues you are seeking with your app, but not sure any new information has been garnished as that was the assessment a few months ago as well.
> 
> So, I think testing private is the way to go. I can get a quote started just so it is in the pipeline. I'll also update you as we near the point in which we can schedule a migration, which is probably going to be the week after the infra is ready.
> 
> I believe you will see quickly if that will be a difference make or not and allow a decision to be made about upgrading permanently or not.

**Comment by dianamartin** [comment]
We decided to migrate to new Knack server 2/21. 
Migration started 2 pm CT, we sent out Maintenance completed emails to all users by 3:57 pm.
