### ISSUE TITLE
Enhancement: Update Knack Banners with TPW formatting

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#13766]
- [x] Submit a PIO Request and work with PIO on Banner Design
- [x] Update Banners temporarily if we do not have PIO Banners by EOW
- [x] Establish a Template for future Banners (AI file and fonts)
- [x] Update all apps to Modern Design Settings
- [x] Upload Production Banners

Applications Updated:

- [x] AMD Data Tracker
- [x] Data & Technology Services Portal
- [x] Forms
- [x] Finance & Purchasing Portal
- [x] HIRE
- [x] Human Resources Portal
- [x] Knack Demo App
- [x] Parking Enterprise Portal
- [x] Public Testing Environment
- [x] Right of Way Portal
- [x] RPP
- [x] Shared Mobility Portal
- [x] Smart Mobility Portal
- [x] Street Banners Portal
- [x] SMD Operations
- [x] Street and Bridge Operations
- [x] Traffic Register
- [x] TDS Portal
- [x] VZA

**Comment by dianamartin** [comment]
# 10/3
- [x] Submitted PIO request about having them help us with standardizing knack application banners
-  Reference: [SharePoint folder](https://cityofaustin.sharepoint.com/sites/tpwDTS/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FtpwDTS%2FShared%20Documents%2FProjects%5FKnack%2FKnack%20Banner%20Reference&viewid=2958c37f%2Dbe1b%2D4ca8%2Db045%2Ddc17d145a4ba)

**Comment by ChrispinP** [comment]
Modern Design Settings applied to all production apps. New TPW Branded Banners uploaded for all production apps.

Need to determine process for storing, maintaining, and updating banners as well as updating the banner for Test Apps.

**Comment by ChrispinP** [comment]
Discussed process with team during sync. Created #14563 for followup documentation.

Complete, closing
