### ISSUE TITLE
Update Division Site Descriptions and Hub Site Association

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#13773]
We need to update division site descriptions from ATD to TPW and update the hub site association from the ATDHub to the TPWHub. 

### Sites under the new TPWHub already
TED
Project Delivery 
Systems Development

### Phase 1 Sites  where I don’t have permissions to update the description (ATD > TPW) or update hub association:   
Equity 
OSE 
AMD   SMD 
ROW 
Finance
HR
DTS 
Parking 
Administration
PIO
SSPD
SMO (their current site is private so should we even be linking to it?) 
ATSD (site is private)
TDS (site is private)

### Phase 2 sites to add: 
OCE new
Safety new
OPM 

### Phase 3
Emergency Management

**Comment by KaroEngstrom** [comment]
@dianamartin I don't have permissions to update the existing sites' description or hub association. I tried all of the Phase 1 groups above this morning.

**Comment by dianamartin** [comment]
# 9/11
Need to update Site Information to go from `ATDHub` to `TPWHub`
- [x] Equity 
- [ ] OSE 
- [ ] AMD   SMD 
- [ ] ROW 
- [ ] Finance
- [ ] HR
- [ ] DTS 
- [ ] Parking 
- [ ] Administration
- [ ] PIO
- [ ] SSPD
- [ ] SMO (their current site is private so should we even be linking to it?) ATSD (site is private)
- [ ] TDS (site is private)

**Comment by dianamartin** [comment]
@KaroEngstrom I associated the renamed sites to TPWHub!

**Comment by dianamartin** [comment]
# 9/10
@KaroEngstrom Are we also switching out Finance to TPWHub?

**Comment by KaroEngstrom** [comment]
@dianamartin Yes; they're in Phase 2 for a new site so they will roll into TPWHub with that existing Teams site.

**Comment by dianamartin** [comment]
@KaroEngstrom where are we on this? Phase 3, done?

**Comment by KaroEngstrom** [comment]
@dianamartin 
I need to email Safety #13651  about their new site and we're migrating the active collaborative records in Community Services #13652  this Friday. Their page content will follow from the workgroup. 

Phase 3 - Emergency Mgmt has been handed over and Rachel C. is currently maintaining that site with support as needed. A folder is linked from that site to the TPWHub to provide a link to main documentation needed by TPW Employees. 

I think this issue could be closed we still have the epic. CSD and Safety will be updated on hub when those sites are ready to go (pending on workgroups).
