### ISSUE TITLE
Online signature on application

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1377]
# As a RPP Reviewer Need the customer to provide a signature on the application, regardless of how it is submitted

**Describe the outcome you'd like to see when this feature is implemented.**
Online signature verifying information is accurate

Should have

---
## Acceptance criteria

- [ ] When the user is on the Review & Submit page of their application they will see the application disclaimer language
- [ ] There will be a field for the user to digitally sign the application, which also means they have read and agree to the application disclaimer.

**Comment by dianamartin** [comment]
On the `permit_application` object table, we have field for `signature`. Below is a preview of the form that has it: 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/6bce1da1-f6d8-42f5-8d13-cbb4b69b6a51)

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/66bb74f5-e9eb-431d-b292-39f47fe2d9d3)

**Comment by dianamartin** [comment]
During demo there were requests for modifications on this. Seemed to be accepted by the users.
