### ISSUE TITLE
Update fee amounts for Temp Valet (Not needed/built)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13781]
### Update fee amounts for temporary valet application fee and temp valet parking space fees
- [ ] Fee code 83494 ATD-TEMP-Valet Application Fee - update amount from $130 to $145
- [ ] Fee code 50205 Temporary Valet Space Rental Fee - update amount from $60 to $70

**Comment by KyleErich** [comment]
Sree and Nate discussed this on 9/29,

This needs to be fleshed out by Kyle, Paloma and Tracy prior to assignment.

**Comment by TracyLinder** [comment]
### Discussion w/ Stakeholders 10/2/23
_Tracy, Kyle, Paloma, Sree, Nate_

- Amounts may not be correct.
