### ISSUE TITLE
Acknowledge application disclaimers

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1378]
# As a RPP Reviewer Need the customer to read & agree to application disclaimers

**Describe the outcome you'd like to see when this feature is implemented.**
Acknowledgement that application disclaimers were read and agreed

Must have

---
## Acceptance criteria

- [ ] When the user is on the Review & Submit page of their application (just before the signature field) is the application disclaimer
- [ ] When the user signs the signature field, it also means they have read and agree to the application disclaimer

**Comment by dianamartin** [comment]
On the application form that the applicant submits, there is a section that they have a digital signature section. The disclaimer is above that 
>By signing, I hereby acknowledge that I have read and agree to abide by the rules and guidelines set forth for purchasing and using Residential Parking Permits. Visit the Residential Permit Parking (RPP) website www.austintexas.gov/rpp for the rules and guidelines 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/56830f2c-82cb-4d62-b6d8-47f7c550f43c)

**Comment by dianamartin** [comment]
During demo there were requests for modifications on this. Seemed to be accepted by the users.
