### ISSUE TITLE
Automatically capture application submitted date

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1379]
# As a RPP Reviewer Would like the system to automatically capture the application submitted date

**Describe the outcome you'd like to see when this feature is implemented.**
Date application was submitted in mm/dd/yyyy format

Must have

---
## Acceptance criteria

- [ ] When the user is on the `Review & Submit` page of their application they must fill out the signature field
- [ ] When the `Submit` button is clicked, there is a form record rule that captures the Submitted Date.
- [ ] The `application status` will change to `Needs Review`

**Comment by dianamartin** [comment]
The `permit_application` object table already has this field `Submitted Date`. The form that the applicant submits to system automatically captures the date they submit to COA.

**Comment by dianamartin** [comment]
During demo there were requests for modifications on this. Seemed to be accepted by the users.
