### ISSUE TITLE
Debug SIF Info on VBMR (SR) (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#13796]
### SIF Required 84034 info isn't inserting on VBM folder by default
- The system should insert the info at folder creation.

**PROD EXAMPLE**
- RSN 13014763

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/b84362e7-b5be-429c-ba07-6f31a042c8d9)

**Comment by Nadin-Nader** [comment]
Meeting Scheduled w/Debra F. for today @ 2:30pm

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in progress

**Comment by Nadin-Nader** [comment]
Email from Sree10/16/23:
Hi Nadin,

Please find attached DEV & TEST DP for your reference. This can be tested only in TEST; so sending both DEV & TEST DP’s together. Kindly approve and crate task id for the same.

Commit ID: 349cf515ec7f

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this to the DevOps CM Team to be deployed to PROD under **SCTASK0364090**

**Comment by Nadin-Nader** [comment]
Sree Reached out to Myra to troubleshoot error...waiting on response. If not response @Nadin-Nader will follow up with Myra

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Had a meeting with @Mayra and tested Volume builder VBMPR & RVPR folders and all are working as expected. This is ready for PROD promotion.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please add your testing notes in more detail and move this to PROD. Thank you!

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested this in TEST along with @Mayra Rivera; Verified complete flow, that is Getting added SIF Required info field in VBM Folders while creation of the folder. And adding as a mandatory info field. When distribute reviews added then ATD SIF Review process added as the info field was "Yes" and tested the review flow with one cycle as rejected and re-insertion and process of Cycle 2 with a comment etc., And it is tested for both VBMPR & RVPR folders as such. here are the folderrsn's for your reference. 13203676 - VBMPR  13203677- RVPR

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - PROD DP submitted. Kindly approve and create task id for the same.

Commit ID: 349cf515ec7f

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0368301**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder  This has been deployed to PROD. Ready for UAT on PROD

**Comment by TracyLinder** [comment]
### Closing

Per Sree, she had to update a lookup table. She worked with Myra and confirmed this is now working correctly.
