### ISSUE TITLE
Move Code & Wikis from Knack Code Repo/Data Tech Wiki into specific repos

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#138]
Per John asking to: 
- [x] move Code from Knack Code Repo into specific repos
- [x] move wikis from Data Tech Wiki into specific repos
___________________________

- [x] bike_share
> created repo `atd_knack-forms`
moved code to new repo 
requested .js and .css deletions, created PR for john to review.

- [X] data_tracker
> moved code to `atd-knack-data-tracker`
requested .js and .css deletions, created PR for john to review.

- [x] dts_portal
> Does this need it own repo? 
created repo `atd-knack-dts-portal`
requested .js and .css deletions, created PR for john to review.

- [X] finance_admin_portal
> moved code to `atd-knack-finance-purchasing`
requested .js and .css deletions, created PR for john to review.

- [x] visitor_sign_in
> created repo "atd-knack-visitor-log"
moved code to new repo
requested .js and .css deletions, created PR for john to review.

- [X] street_banner
> moved code to `atd-knack-street-banner`
requested .js and .css deletions, created PR for john to review.

**Comment by amenity** [comment]
@dianamartin - anything left to do on this?

**Comment by dianamartin** [comment]
I think I moved everything over already. I just checked the data-tech-wiki page and don't see any that need to be relocated.
