### ISSUE TITLE
BUG: Batch Process 149 for ROW Excavation Report (50510) Is not running and erroring out (SS) (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#13805]
##  BUG: Batch Process 149 for ROW Excavation Report (50510) Is not running and erroring out old card # was #8794

Jenice M. from CTM asked if we could look into this as it is erroring out and possibly helping with server slowness. See images below:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2FRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--570823c45d2ad9927f5796428aec1f6690f05c1d/MicrosoftTeams-image%20%2849%29.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1dRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d3b551f007bb2aff78296512eae9ac7778607629/MicrosoftTeams-image%20%2850%29.png)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  As we discussed this morning, I prepared PROD DP. Please create a PROD deployment request for this. Thanks.
[13805 - Manual PROD Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/12895195/13805.-.Manual.PROD.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
@SubhaShroff i sent this to the CTM team to deploy to PROD under **SCTASK0363313**

**Comment by SubhaShroff** [comment]
@Nadin-Nader I wonder if this batch job ever worked. As I mentioned in the call, the package call to insert job instance when EX is issued. But the package procedure call is not adding any from, to or cc email to the job instance. So it was not sending the email. 
Another thing is, the email subject is always sent as '[Subtype], [PermitNumber] Permit Approved and Attached'. Actually, [Subtype], [PermitNumber] key words are supposed to be replaced with the permit subtype and its permit number. That part is also fixed with this code change. - [b6ee4ecce05b](http://coaamandadevops02.austintexas.gov/R5:b6ee4ecce05b10355027164e96dac8219942763f). Will soon send a DP for DEV deployment. Thanks.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps C Team to be deployed to DEV and TEST under **SCTASK0364486**

**Comment by SubhaShroff** [comment]
> @Nadin-Nader I wonder if this batch job ever worked. As I mentioned in the call, the package call to insert job instance when EX is issued. But the package procedure call is not adding any from, to or cc email to the job instance. So it was not sending the email. Another thing is, the email subject is always sent as '[Subtype], [PermitNumber] Permit Approved and Attached'. Actually, [Subtype], [PermitNumber] key words are supposed to be replaced with the permit subtype and its permit number. That part is also fixed with this code change. - [b6ee4ecce05b](http://coaamandadevops02.austintexas.gov/R5:b6ee4ecce05b10355027164e96dac8219942763f). Will soon send a DP for DEV deployment. Thanks.

@Nadin-Nader  @KyleErich  This is deployed in DEV/TEST and I have tested it. Looks working. Along with the [Subtype], [PermitNumber] error earlier I noticed. Please UAT. Thank you.

**Comment by Nadin-Nader** [comment]
Waiting on UAT response from Kyle

**Comment by SubhaShroff** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/51680715/dc8d2dfc-e49b-41bd-b333-d65d81c6a303)

@KyleErich  @Nadin-Nader  No need to run the batch job manually. When an EX permit is issued, the batch job triggers automatically and that sends the EX permit report to specific email ids - sitesubpermits@austintexas.gov, AMANDATestMB@austintexas.gov. I could verify by sending the emails to my email ID, when I tested. Need to verify the other email inboxes.

**Comment by TracyLinder** [comment]
Discussed at Friday's ROW review; 
- @SubhaShroff will add Kyle's email to the test distribution list
- Kyle will issue an EX permit in test and verify he got the email
FYI @KyleErich

**Comment by SubhaShroff** [comment]
@KyleErich  On TEST, I have added your email id Kyle.Kampe@austintexas.gov  to the batch 149. So, when you issue an EX, you should be getting an email with permit report in your inbox. I can verify the batch job for you and post the screenshot with issue.

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff UAT approved on Test. Thanks!

**Comment by SubhaShroff** [comment]
Thank you Kyle.
@Nadin-Nader  Please send this to PROD. 
[13805- b6ee4ecce05b - PROD Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/13208994/13805-.b6ee4ecce05b.-.PROD.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0367646**

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to PROD. I will send ROW  a message letting Kyle know

**Comment by Nadin-Nader** [comment]
Sent Kyle a message via Teams that this is ready for UAT on PROD. Waiting on Response

**Comment by Nadin-Nader** [comment]
Sent Kyle a message via Teams that this is ready for UAT on PROD. Waiting on Response

**Comment by Nadin-Nader** [comment]
Sent Kyle a message via Teams that this is ready for UAT on PROD. Waiting on Response

**Comment by Nadin-Nader** [comment]
Kyle has approved this on PROD. CLOSING
