### ISSUE TITLE
Capture permit issue date

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1380]
# As a RPP Reviewer Permit issue date is captured in mm/dd/yyyy format

**Describe the outcome you'd like to see when this is implemented.**
Permit issue date will be a key field for reporting, performance measures and dashboard queries. 

Must have

---
## Acceptance criteria

- [ ] When RPP staff are on the `Issue` page, they will click the `Issue` button on the `permit issue` form
- [ ] The `Issued Permit` table will show the permit and the `Issued Date` because the form has a record rule that captures the date when the `Issue` button is clicked.

**Comment by dianamartin** [comment]
Already have a `permit` object table built out. Has the field `Issued Date` and the form when the RPP Staff issues it captures the `Issued Date`.

**Comment by dianamartin** [comment]
During demo there weren't requests for modifications on this. Seemed to be accepted by the users.
