### ISSUE TITLE
Phase 5: Form Review for Eco-System MetaData Automated Support and Best Practice Documentation 

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#13802]
### Background 
The ecosystem map has been built from a combination of pre-existing tools and processes. As a result the ability to edit these forms to support the automated connections and relationships built in the ecosystem mapping, will serve as the primary adjustments derived to aid in this project. 

### Objective Outcomes: 
- [x]    Review current forms 
  - [x] Which fields are connected to the data we are looking to capture? For example: 
    - [x]  For **Application Request**: Form Accessed? Fields In Form? Which Fields correspond to the metadata and hierarchy needs? 
    - [x] For **DataSet Additions To Open Data Porta**l? Form Accessed? Fields In Form? Which Fields correspond to the metadata and hierarchy needs? 
    - [ ] For **Sharepoint Additions or Main Hub**? (see Karo) Form Accessed? Fields In Form? Which Fields correspond to the metadata and hierarchy needs? 
    - [ ] For **Scripts and ETL process**? Form Accessed? Fields In Form? Which Fields correspond to the metadata and hierarchy needs? 
    - [x] For **Reports/Dashboards?** Form Accessed? Fields In Form? Which Fields correspond to the metadata and hierarchy needs? 
    - [ ] For **new**ly used **3rd party  or City Wide Databases**?
  - [x] What **adjusts to current forms** can be used to support metadata needs and relationship connections? Are **new forms** needed, or additional metadata requirements when creating? 
  - [ ] What database or records is used to **keep track of the City Wide Databases and tools** being used, those outside of Knack, how do we have visibility? Only manual and by word-of-mouth?
- [ ]   Document data standards, best department practice recommendations, desired goals (example: eliminate manual imports, etc) 

**For example**: When an internal stakeholder is **requesting a new dashboard or application?** 
+ What forms are currently being utilized to make that request? > This would be an ideal area to review and possibly implement required information. Such as >
    + Which division(s) will be supported? 
    + Who is requesting? 
    + What tool or database is providing the information? 
         + How do we receive the information being collected? 
         + Is it true in its raw form or manually manipulated before being storage in house or used for reporting? 
  + What answer or information is being desired from the report requested? What is the question being answered or asked? DO we currently have report or solution that provides this insight? 
  
+ **Where in the current forms with edits or new forms**, can we ensure each node might have:
   + division/manager/developer(s)/org chart
   + ETL in (how data gets there)
   + ETL out (how data gets to the next node)
   + other data like vendor/db type etc
   + the child node(s) in the data flow
   + the parent node(s) in the data flow

[Schema to Single Line Draw Out](https://excalidraw.com/#json=Qo_1KVtRwN2yeUnAGhtUD,oRSYjiR6JRLN6musYOly-A)
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/29f95e22-7f8d-493f-a38e-225930d8747b)

**Comment by rebekkabry** [comment]
Would like to work with Charlie on this. Pending further discussion.

**Comment by rebekkabry** [comment]
Beginning TO DO:

- [ ] Speak with DTS executives 
- [ ] Schedule meeting with work-session team members 
- [ ] Review current requesting tools and products forms 
      - [ ] Knack applications 
      - [ ] Knack datasets 
      - [ ] Airflow and FME 
      - [ ] etc. 
 - [ ] Decide best moving forward to 1) adjust forms or 2)current new form/link framework? 
      - [ ] Consider auto status features available in Knack to set status on all applicable portions of the ecosystem map? 
      - [ ] Can responsible teams be alerting when sections they own fail?

**Comment by rebekkabry** [comment]
### Meeting Notes 9/14/23
+ Attendees Karo, Charlie, Rebekka
   + Need to find a way to merge the 2...then import from spreadsheet. 
   + Set alerts for new records, much like the scripts .  

### Next Steps: 
Objective:
+ Test environment with group that is not currently in Knack (ones with ETLs?)

Steps: 
+ What are the additional fields that have been added to the process that need to be added into Knack 
+ Build out and test
+ Automation for maintenance moving forward, dynamic livable.
+ Match column/objects in fields as much as possible OR consider another ETL
+ Investigate instances/applications/dataset connections in Knack 

Objects List?
+ Applications 
+ DB
+ DS
+ Outputs

**Comment by KaroEngstrom** [comment]
### Karo Note 9/14/23 

I mapped out the DTS Portal objects set-up: 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/b1baf8a5-ff94-4232-a490-e6383ba615eb)

Will also look at the primary sources/secondary sources model before our next meeting.

**Comment by KaroEngstrom** [comment]
Adding this test template for adding your new items for the `dataset` object @rebekkabry 
[Dataset_TestTemplate.csv](https://github.com/cityofaustin/atd-data-tech/files/12651451/Dataset_TestTemplate.csv)

**Comment by rebekkabry** [comment]
In regards to the DTS Portal objects set-up: 
- What’s the difference between “applications” and “environments”? 
- What is the definition of “instance”? 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/ce0e18ae-147a-469e-9cd3-682bef36e7fc)


In reference to the [Github](https://github.com/cityofaustin/atd-data-tech/issues/13802) Comments:
- I am wondering if each “Instance”/”Application” should be also tagged with an hierarchy lookup table to assign each “Instance” mention a level and connected data references (such as dev, division, etc). Example below.
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/e9620ebf-9a8b-4ef3-abb3-5fcb32308941)
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/0c420982-e3d1-4f69-88a5-fe4f305681ae)


### Current to Considering
Here is my understanding of what we have compared to what we are considering…
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/8023176a-a2e7-482d-b349-daa7e8602ce9)

What we are considering? (rough draft mock up)  Not sure if multiple templates are needed to capture it all, of if we can condense
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/3fd1c42e-a15c-4149-8f3e-a0a803a166c9)

**Comment by KaroEngstrom** [comment]
A thought after Friday's meeting: if you want to label the instances per their hierarchy level, assuming they are in a relatively clear hierarchy like Charlie's mapping above (primary parent > non-primary child > multiple non-primary grandchildren), we could use another column for levels to indicate primary, secondary, tertiary, quartenary, etc). The instances could be sorted by this level in Knack which would make it visually easier on that Dataset page to see the hierarchy. I realize Knack won't be the primary visualization platform.

**Comment by rebekkabry** [comment]
> A thought after Friday's meeting: if you want to label the instances per their hierarchy level, assuming they are in a relatively clear hierarchy like Charlie's mapping above (primary parent > non-primary child > multiple non-primary grandchildren), we could use another column for levels to indicate primary, secondary, tertiary, quartenary, etc. The instances could be sorted by this level in Knack which would make it visually easier on that Dataset page to see the hierarchy. I realize Knack won't be the primary visualization platform.

I think that would be a great approach, ideal actually. The mock/model table will be ready this week.

**Comment by Charlie-Henry** [comment]
Makes sense! Thanks y'all!

**Comment by rebekkabry** [comment]
DTS | Data and Technology Services Portal Knack review and model build out - in progress. 

- [ ] Follow up meeting with Karo set after model, tentative 10/11/23

**Comment by rebekkabry** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/8a360309-1835-4fc3-8a20-77c692e70c75)

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/865b75af-4445-4882-bd85-6eace638b334)

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/1f8bb51b-c541-4e86-81f9-e62341d8d9ff)

**Comment by rebekkabry** [comment]
**Applications Insight**s - based on the current "applications form"...  
-	Currently it contains more than “hosting ops applications.” (currently 79 records)
-	Find a way to group the current applications. (Source: Knack Applications, Storage, 3rd party Server, Not in Production, Outputs: Online Web Application, Map) 
-	Primary Source does not mean origin of source data, it means the start of the data process In Knacks records. 
-	Applications ideally should only contain active in use data collecting or storage applications

**Comment by rebekkabry** [comment]
- [ ] MVP Build Out in Work Session Progress in Knack TEST | 07 SEP 2023 | DTS | Data and Technology Services Portal > current focus on Applications Form 
- [ ] Next meeting will focus on Environments insights and Datasets Node.

**Comment by rebekkabry** [comment]
- [ ] Datasets - investigate use of FME to pull from open data sources. Goal: automate new entry alerts, automate data collection, sync data, provide single reference point for each dataset reference, ability to link by 4x4 ID. 
- [ ] Meeting scheduled with Andrew to investigate week of 11/14

**Comment by rebekkabry** [comment]
In Progress 
[ ] create CTM form to Knack Mapping (Charlie has a script already in place for the ETL) updates to confirm what is needed for the Knack EcoSystem ETL

**Comment by rebekkabry** [comment]
- [ ] Current implementation of ETL process CTM dataset into Knack (adding in test = red, black = production current, purple = current feature in test)

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/e6e30849-b943-4056-a515-ab87d3c2cb00)

**Comment by rebekkabry** [comment]
- [ ] [Migrate Datasets into Knack ](**url**)
- [ ] Master List Consideration
