### ISSUE TITLE
IT Support: GIS install

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#13811]
ST. ELMO

## Device & User Information (first name and last initial, no last names)
Anna M
## What's the problem?
Hi Matt! Binaya told me I need to get ArcGIS installed on my computer so I can get started on some upcoming assignments. Is there a specific ArcGIS person I should contact about that or do I go through you?

**Comment by Vaishnav1397** [comment]
Successfully installed the ArcGIS to the user device.
