### ISSUE TITLE
Advanced search of application/permit data

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1381]
# As a RPP Reviewer I'd like to be able to do an advanced search, and for the results to include all available data about the matching permits/applications

**Describe the outcome you'd like to see when this feature is implemented.**
Customized reports 

Should have

---
## Acceptance criteria

- [ ] There is a page `Search Permits & Transactions`, it is an advanced search page
- [ ] It allows a user to use various fields to filter the records by

**Comment by dianamartin** [comment]
Created a page called `Search Permit & Transactions`. This allows a user to search using various fields to find permit and transaction records.

**Comment by dianamartin** [comment]
During demo there weren't requests for modifications on this. Seemed to be accepted by the users.

- John will schedule additional meeting with Finance team to clarify any more needs

**Comment by dianamartin** [comment]
A new page `Transactions` was created as a record of the transactions that can be queried by RPP staff or Finance.

**Comment by dianamartin** [comment]
Need stakeholders acceptance of new `Transactions` page

**Comment by dianamartin** [comment]
Van confirmed that this Advanced Search for transactions works for Finance's needs.
