### ISSUE TITLE
Automate quarterly performance reports

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1382]
# As a RPP Reviewer I'd like the system to automate the quarterly reports that we're doing manually right now. (See signs & markings reports page)

**Describe the outcome you'd like to see when this feature is implemented.**
Historical performance reports available for management to review. 

Should have
---
## Acceptance criteria

- [ ] There is a page shows various widgets about RPP
- [ ] `Permits Issued - by permit type` (pie chart)
- [ ] `Monthly Permit Issuance` (line chart)
- [ ] `Monthly Permit Issuance Trends` (pivot table) - monthly, see how many permits by type are issued per month
- [ ] `Total Revenue - All Districts` (pivot table) - monthly, see how many permits by type are issued per month and the total cost of revenue gained.
- [ ] `Total Revenue - Per District Zone` (pivot table)
- [ ] `Transactions by Payment Type` (pie chart)
- [ ] `Transactions by Payment Type` (pivot table) - monthly, see how many transactions by payment type and revenue gained.

**Comment by dianamartin** [comment]
Emailed Ryan R. to see if he had some examples of the reports or numbers he puts together.

**Comment by dianamartin** [comment]
Was able to replicate most of the widgets and reporting table that Ryan would prepare for the RPP program.

**Comment by dianamartin** [comment]
During demo there weren't requests for modifications on this. Seemed to be accepted by the users.

- Need to determine if the quarterly management reports need to be available in excel format
  - This would entail creating a new page that has a table that can be exported
