### ISSUE TITLE
Validate property eligibility 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1383]
# As a RPP Reviewer I'd like the system to validate that the property is eligible for RPP

**Describe the outcome you'd like to see when this feature is implemented.**
Ineligible properties will not have ability to submit application for permit
 
Could have

---
## Acceptance criteria

- [ ] On the `Permit Management` page, you can click on the `Application ID`
- [ ] In the `View Permit Application Details` page, you can click a button `Verify RPP Address`
- [ ] On this page, you can use the `Verify by Map`, can enter an address in the search field
- [ ] On this page, you can used the `Verify by Address`, can enter an address in the Resident Address fields and receive a notification of:
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/eb39d0d6-3a48-4387-b58c-4da82c5ffd8e)
or 
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/416e123a-bc60-4ddc-9c8e-b8ed32c7f99e)

**Comment by dianamartin** [comment]
@johnclary I tried moving over the JS code you had in the `City of Austin Parking Permits` app to the new RPP application and I think I got most of it set-up. I'm sure I'm missing some stuff so it would be cool if you could get 👀 on it some time to see what I don't have figured out.

**Comment by johnclary** [comment]
@dianamartin got it working. just had to replace the field id of the address field, and enable geocoding on that field.

**Comment by dianamartin** [comment]
I tested it this morning when I was showing Mary V. a sneak, peek of the RPP system (showing her Knack features/functionality)

**Comment by dianamartin** [comment]
During demo there weren't requests for modifications on this. Seemed to be accepted by the users.
