### ISSUE TITLE
Customer information

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1384]
# As a RPP Reviewer I need to gather information about the customer (phone number, address, e-mail address, 

**Describe the outcome you'd like to see when this feature is implemented.**
Will allow for reporting on various customer and property related fields

Must have

## Acceptance criteria

- [ ] When the customer starts their RPP application Part 1 of the form shows customer fields
- [ ] The fields they are required to fill out are: 
- `Name of Applicant`
- `Applicant Type`
- `Phone` 
- `Email`

**Comment by dianamartin** [comment]
Build out a table for `Customers`, and have fields:
- Name
- Applicant Type
- Phone Number
- Email Address
- Address - _(is currently on the `permit_applications` table)_

If I need to store the customer address on file per customer, I can do that too.

**Comment by dianamartin** [comment]
During demo there were requests for modifications on this. Seemed to be accepted by the users.
