### ISSUE TITLE
Workshop Dash interface design

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#13841]
Kate's prep
- [x] Schedule 1 hour w/ Charlie & Rebekka, optional: Susanne, Amenity, Andrew, Chia
- [x] Review the product vision board and determine the features
- [x] Review TPW branding standards 
- [x] Provide parameters for "homework" design brainstorming

**Comment by katelunceford** [comment]
Held a productive meeting ([recording here](https://cityofaustin-my.sharepoint.com/personal/kate_lunceford_austintexas_gov/_layouts/15/stream.aspx?id=%2Fpersonal%2Fkate%5Flunceford%5Faustintexas%5Fgov%2FDocuments%2FRecordings%2FDash%20design%20kick%2Doff%2D20230927%5F130300%2DMeeting%20Recording%2Emp4&ga=1)) and assigned the homework. Issue [#14021](https://github.com/cityofaustin/atd-data-tech/issues/14021) captures the next steps.
