### ISSUE TITLE
Maximo - Colony Park Project - Report Updates

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#13848]
- [x] Remove Duration
- [x] Labor Hours need to be accurate since TK was not used for this project
- [x] Remove dollar amounts in Labor and Tool
- [x] Add problem code
- [x] Add report to South Report List
====================================================
- Isaac will update work orders with OT.
- Eli will verify with Brenda regarding material cost.
- Isaac will update priority as they go from 4 to 2.

**Comment by YakshDipa** [comment]
Updated the report and start center

**Comment by YakshDipa** [comment]
Updated the report and start center
