### ISSUE TITLE
Retain customer information

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1385]
# As a RPP Reviewer I would like the system to remember customer information, so I don't have to type it in multiple times

**Describe the outcome you'd like to see when this feature is implemented.**
Historical customer information will ease the customer experience when renewing or requesting additional permits

Should have

---
## Acceptance criteria

- [ ] [Criteria]
- [ ] [Criteria]

**Comment by dianamartin** [comment]
Planning on building out a `Customer` page so that RPP Staff can reference customer information. We may nee to discuss how RPP staff want to use this for filling out various applications.

**Comment by dianamartin** [comment]
@johnclary I might need to bounce this idea of how this will work. I don't know why I can't figure this out. I might need to sleep on it and remember if we have an app that does something similar already.

**Comment by dianamartin** [comment]
We have a page called `Customers`. It tracks: 
- Customer ID (auto generated)
- Name 
- Phone
- Email
- Address applicant used to apply for permit
- Applicant Type
- Associated Applications
- Requested Permits

**Comment by dianamartin** [comment]
During demo there weren't requests for modifications on this. Seemed to be accepted by the users.
