### ISSUE TITLE
Add additional options to `Other` finance service request job type

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#13856]
Going to add `Job Subtype`:
- Name Change | FDU, TK, or Subproject
- Change FDU Subproject Number
- SA | Service Agreement
- SeRF | Service Requisition Form
- Other

**Comment by dianamartin** [comment]
# 9/15
- Synced with Christina and we mocked up in Finance and Purchasing TEST, then made the changes in PROD
- Ready for stakeholder review

**Comment by ChristinaTremel** [comment]
Showed this to the Finance team last week on 9/20 and they were happy with the changes!
