### ISSUE TITLE
Maximo Report Request [Modification] Update District Maintenance Data Quality Report

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#13858]
Request to add:

- [x] Missing Crew

**- [ ] District Maintenance crew/work group on other classification work orders i,e. seal coat, overlay**
       Pull: PERSONGROUP: SBODIST%, open status (1, 2, 3, 4COMPs), Classification that is NOT District_Maintenance
       View: WONUM, DESCRIPTION, STATUS, STATUSDATE PERSONGROUP, SUPERINTENDENT, SUPERVISOR, CLASSIFICATION, PROBLEM CODE

**- [ ] Missing asset for work orders that have materials added**
       Pull: PERSONGROUP: SBODIST%, open status, Classification: DISTRICT_MAINTENANCE, has MATTRANS, assets that are BLANK
       View: WONUM, DESCRIPTION, STATUS, STATUSDATE, PERSONGROUP, SUPERINTENDENT, SUPERVISOR, PROBLEMCODE, ASSET (to show that it is blank), MATERIAL USED

**- [ ] missing Length and Width on surface repairs**
       Pull: PERSONGROUP: SBODIST%, open status, Classification: DISTRICT_MAINTENANCE, has MATTRANS, Specifications: missing ACTUAL LENGTH and ACTUAL WIDTH
       View: see screenshot

<img width="1533" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVE5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f7c1d2892307b4751f368e7f452135c10b93011/image.png" alt="image.png" />

Once items are added to DQR:
- [ ] add report to all district start centers

**Comment by adry-martinez** [comment]
Submitted request to CTM for report update. Pending response.

**Comment by adry-martinez** [comment]
### 1/31/24
Discussed with CTM Nick O. He will provide information on this report within the next two weeks.

**Comment by adry-martinez** [comment]
**2/11/24**

DTS Maximo has a scheduled meeting with CTM for status updates.

**Comment by adry-martinez** [comment]
**2/24/24**

CTM confirmed still in progress.

**Comment by rebekkabry** [comment]
# 5/20/24 Notes with CTM 

- CTM still working on.

**Comment by rebekkabry** [comment]
@GaneshKamarapu has taken ownership.

**Comment by GaneshKamarapu** [comment]
Deployed and is ready for QA @rebekkabry 

![image](https://github.com/cityofaustin/atd-data-tech/assets/169071970/de14bdd7-7f43-47b7-8d4c-71d73aeb07d9)

**Comment by rebekkabry** [comment]
Report specs have been addressed, will review with stakeholders during upcoming sync.
