### ISSUE TITLE
EzMaxMobile, Quick Reference Guides

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#13851]
Develop a QRG for the EZMaxMobile application for new users. Document all steps in detail and include photos for each step. Should be written for new users who will using the application for resolving WOs and CSRs.

**Comment by ReneVarg25** [comment]
Currently on hold due to Maps and other functions not currently available.

**Comment by ReneVarg25** [comment]
Instructions may change due to changes with Auto-Fill for work logs. Will hold until further updates.

**Comment by ReneVarg25** [comment]
Issues with Map function still being resolved by CTM.

**Comment by adry-martinez** [comment]
@ReneVarg25 please review, and place a placeholder in the guide for future map steps. Then share final draft so we can publish. Thanks.

**Comment by adry-martinez** [comment]
@ReneVarg25 please review, and place a placeholder in the guide for future map steps. Then share final draft so we can publish. Thanks.

**Comment by dianamartin** [comment]
# 2/26/2024
- Rene uploaded the EzMax User Docs to [Maximo SharePoint](https://cityofaustin.sharepoint.com/sites/MaximoResources/EzMaxMobile%20Resources/Forms/Compact.aspx?id=%2Fsites%2FMaximoResources%2FEzMaxMobile%20Resources%2FEZMaxMobile%20QRG%2FEZMaxMobile%20Application%20Training%20Doc%20V1%2Epdf&parent=%2Fsites%2FMaximoResources%2FEzMaxMobile%20Resources%2FEZMaxMobile%20QRG)
