### ISSUE TITLE
Maximo, Reporting Items: Austin 3-1-1 Consolidation and Reconciliation Document

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#13850]
Create a document for the 311 Consolidation and Reconciliation utilizing the SBO Bi-Weekly Report and the Maximo report. Document all steps taken in detail and include photos per step. This document will be connected to a base document that will be utilized for all reports, and should be written from the perspective of a new employee who will be performing the consolidation.

**Comment by ReneVarg25** [comment]
1st phase of document has been completed. Adriana is now reviewing document and will send back notes for adjustments.

**Comment by ReneVarg25** [comment]
2nd Phase Done reduced to 11 pages from 20, Awaiting Adriana's review.

**Comment by ReneVarg25** [comment]
Still In Progress - Do Not Close

**Comment by adry-martinez** [comment]
Draft reviewed, returned to @ReneVarg25 for edits.

**Comment by ReneVarg25** [comment]
Edits have been applied, returned to @adry-martinez for review

**Comment by ReneVarg25** [comment]
Applied final edits to document. Purpose, Scope, and Reference Section.

**Comment by ReneVarg25** [comment]
Instructions may change due to changes with Auto-Fill for work logs. Will hold until further updates.

**Comment by adry-martinez** [comment]
@ReneVarg25 indicated to disregard previous comment, document ready to be published.

**Comment by adry-martinez** [comment]
@ReneVarg25 any idea on when we are publishing this document on our SharePoint?

**Comment by ReneVarg25** [comment]
### 2/13/2024
Document has been uploaded to the Sharepoint site. New Folder created "Site Admin Use Only" for future Admin QRGs in future.

https://cityofaustin.sharepoint.com/:f:/r/sites/MaximoResources/Shared%20Documents/Site%20Admin%20Use%20Only?csf=1&web=1&e=GLPCIf
