### ISSUE TITLE
Maximo Resources SharePoint Design

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#13864]
Re-designing the SharePoint so that each workgroup within SBO has their own dedicated SharePoint page with relevant resources to their work groups:

- Maintain Library to contain ALL documents.

Create pages for each workgroup and tailor the page to the workgroups guides videos and presentation for quick access:
## Create Site pages

- [x] District Maintenance
- [x] Pavement Operations
- [x] Forestry
- [x] Utilities and Structures
- [ ] Dispatch

## Future Enhancements
Consider asking DTS for a shortcut to MAXIMO RESOURCES on all SBO desktops. - #14862

**Comment by dianamartin** [comment]
# 3/5/2024
Create Site Pages & Configure
- [x]  Pavement Operations
- [ ]  Utilities and Structures
- [ ]  Forestry
- [ ]  Dispatch

**Comment by dianamartin** [comment]
# 5/13/2024
- [x] Created new workgroup page "Bridges" 
- [x] Created new workgroup page "Concrete Repair & Construction" 
- [ ]  Created new workgroup page "Dispatch" 
- [ ]  Created new workgroup page "Office of the City Engineer"
