### ISSUE TITLE
Maximo Training: How-To Videos

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#13866]
- [x] Parent-Child creation from CSR-WO
- [x] Resolving duplicate WOs
- [x] Work Group Notification - How to notify a work group
- [x] Work Group Notification - How to acknowledge a notification

**Comment by rebekkabry** [comment]
@ReneVarg25 do you think we have these covered in the gitbook training? I was thinking maybe not the how to acknowledge a notifcation one?

**Comment by rebekkabry** [comment]
[Maximo Stakeholder Training Gitbook](https://atd-dts.gitbook.io/maximo-help-guides/)
