### ISSUE TITLE
Maximo, Track Hauling efforts in Maximo

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#13873]
PC Ewing is inquiring a Maximo process to document Pavement team efforts when it comes to hauling material and debris. 

PC will collect who, what, where, when, and why for these requests so it can be tracked:

- Vehicle
- Material (measured by tons)
- Personnel

Consider Parent WO for Child WO hierarchy to track frequency.

**Comment by maccallump** [comment]
@adry-martinez and @ReneVarg25 have you met with the stakeholder yet?  Is there a need to identify location or GIS coordinates for this request?

**Comment by adry-martinez** [comment]
@maccallump we have met with the stakeholder but at this time, they requested to hold off on working this request. This issue will be moved to blocked until we're advised by the stakeholder to commence our work on this.

**Comment by adry-martinez** [comment]
Andre E. asked if we could update storeroom for debris, landfilled materials as drop off points or consider using Specifications. May need to create a new classification for hauling but will discuss this further at a later time.

**Comment by adry-martinez** [comment]
**2-14-24**
Per requestor, table indefinitely. Issue closed.
