### ISSUE TITLE
Discuss APD's policy/process for VZA assignment + invoicing 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1387]
_Call 2/6/2019: Surbhi, Amenity, Jen, Pat, Randy, possibly Stacey (APD invoicing)_

Learn about APD's policy and process needs in terms of invoicing and employee timekeeping for VZA enforcement shifts. 

Questions: 
- Would it be possible for APD officers to sign themselves up for shifts directly using the VZA App? This would allow officers to get shifts they want and save Randy the trouble of assigning them. It might also increase participation since officers currently don't sign up b/c they want to work north and they know those are assigned first. 
- What needs to be recorded in Revolution 911, and when? E.g. could Randy add everything after a shift is completed? This would save him the time of assigning officers and updating everything when assignments change. 

@SurbhiBakshi - what else?

**Comment by SurbhiBakshi** [comment]
@amenity looks good!

**Comment by amenity** [comment]
Randy says that a report after the fact might be fine, it's just important for him to get everything into Revolution 911. Will discuss during #1265.
