### ISSUE TITLE
Maximo Newsletter January 2024

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#13874]
Write articles related to Maximo updates and distribute via SharePoint with the updated Mailing List

**Comment by adry-martinez** [comment]
Items to add to next month's newsletter
Work Group can be audited

**Comment by adry-martinez** [comment]
Article for October 2023: 
https://cityofaustin.sharepoint.com/:u:/r/sites/MaximoResources/SitePages/Using-full-department-names-instead-of-acronyms.aspx?csf=1&web=1&e=qHT8QN

**Comment by adry-martinez** [comment]
Assigned to @ReneVarg25 to complete December Newsletter to include:

Reminder to close out unmetered water WOs
3-1-1 Standardization Update to QRGs
Training during slow season

**Comment by adry-martinez** [comment]
March Newsletter to include:

- [ ] Update to [SBO CAF Lifecycle document](https://cityofaustin.sharepoint.com/:b:/r/sites/MaximoResources/Shared%20Documents/Quick%20Reference%20Sheets%20(QRS)/4%20-%20Office%20of%20the%20City%20Engineer%20Maximo/SBO%20Maximo%20QRS%20CAF%20Lifecycle.pdf?csf=1&web=1&e=q5UhmJ)

**Comment by ReneVarg25** [comment]
Updating January newsletter to include the following:
Auto Fill Work Logs
EzMax Feedback
Discovery Day Meetings
Future Training Oportunities

**Comment by adry-martinez** [comment]
@ReneVarg25  add to January Newsletter:

- [ ] Add calendar of training opportunities
- [ ] Add video demo of autofill feature for work logs
- [ ] Remove quote and replace with video demo ^
- [ ] Indicate Report List = Bookmark Bar for Maximo Reports
- [ ] List commonly used reports
- [ ] 311 (overdue, all SRs)
- [ ] Data Quality (list them)
- [ ] Striping
- [ ] CAFs
- [ ] Unmetered Water Usage Log CY24, add link to guide
