### ISSUE TITLE
Maximo Training Policy - Internal to SBO Site Admin

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#13878]
This will be a document that our team can use to reinforce attendance for our training sessions. Steps for escalation will be included and how to proceed.

**Comment by maccallump** [comment]
@adry-martinez how do you currently track attendance?

**Comment by adry-martinez** [comment]
@maccallump at this time, we are utilizing TEAMS to track attendance. Outside of that, there hasn't been a _formal_ training session where we needed to track attendance but we would like to initiate a process for us to better keep track in the event leadership team wants to know where each person is when it comes to Maximo training.

**Comment by rebekkabry** [comment]
@adry-martinez can you link your recent attendance resources here. 

- There are conversations in place currently around Training Tracking via SBO Career Progression.

**Comment by adry-martinez** [comment]
[Maximo Training Course Plan](https://docs.google.com/document/d/1sjIe65y-4xmldouPgWqsGaaA65I7wgBJ1AZVYGo7XRk/edit?usp=sharing)

**Comment by adry-martinez** [comment]
[Maximo Training Sign In - Knack](https://atd.knack.com/sbo#training-enrollment/training-sign-in/664d598e27430200286bcff8/)

[Maximo Training Tracker - Knack](https://atd.knack.com/sbo#training-tracker/)

**Comment by adry-martinez** [comment]
[Maximo Training Sign In - Knack](https://atd.knack.com/sbo#training-enrollment/training-sign-in/664d598e27430200286bcff8/)

[Maximo Training Tracker - Knack](https://atd.knack.com/sbo#training-tracker/)
