### ISSUE TITLE
Maximo, Colony Park Sidewalk Maintenance Project

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#13888]
South District Maintenance team will repair sidewalks that pose hazards in District 1.

## Scope & Deliverables

Sidewalk work orders will be loaded in Maximo along with schedule dates and project will be tracked using start center portlet and reports.  Report will track labor and tool hours as well as material used for each project. Crew will work 3 days every month. 

## Desired Outcomes

SBO team will use labor and tool hours and material quantity to calculate the cost and track it against budget.

## Timebox

South District Maintenance team planned to work approximately 11 month.  After initial data load, start center and report, Maximo team will be in support mode. 

## Concepts and references

Helpful links; e.g. other solutions, screenshots of Slack convos, customer’s original request, anything too long for the one-pager that can exist as a separate doc. Folder in Drive where project assets are stored.

## Request details
- Executive sponsor:
- Date:

https://atd-dts.gitbook.io/wiki/product-ops/dts-website#images
The first image will be used as the project's thumbnail image on the website.

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by adry-martinez** [comment]
Maximo team designed and implemented queries and reporting as requested by Assistant Dir. Reiner Hershaw and District Maintenance Division Manager Michael Girod. 

Project completed.

**Comment by adry-martinez** [comment]
Project Coordinator Areli C. has been given a directive to re-open this project and requested Maximo team to shift work group responsibility from South District to UER. 

Project re-opened.

**Comment by adry-martinez** [comment]
PC Areli C. requested for COLONY PARK Portlet to be moved from South to Project Coordinator Start Center. Complete.
