### ISSUE TITLE
Requesting access to SMD and AMD Systems

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#13893]
Please grant read-only prod access to Adriana, Rene and Dipa. Let us know if you need any info.

**Comment by dianamartin** [comment]
# 9/18
The Maximo team is asking to have access to the following: 
- AMD Data Tracker
  -  [ ] Create account for Dipa, Rene, Adry (Viewer) 
  - mirror account: Michael S.  - `viewer` role
  - We'll do an Apps walk through for them and then we can change their user roles
- SMD Data Tracker
  -  [ ] Create account for Dipa, Rene, Adry (Viewer) 
  - mirror account: Allyson R.  - `viewer` role
  - @ChristinaTremel can you do the app intro training for them or give them your recorded video?

**Comment by KaroEngstrom** [comment]
## Mon 9/18/23 - accounts created
