### ISSUE TITLE
Living Streets Getting Started Page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13895]
## Description
Create a splash page for residents similar to the Street Banner Program [portal](https://atd.knack.com/street-banners#portal/).

## Deliverables
- Information about the Living Streets Program
- Costs breakdown, if necessary
- Button Section
   - Eligibility (modal)
   - Get Started (Application page)
   - About the Program (link directs back to Living Street page)
   - Help (modal)
 
## Notes
- [Reference get started page](https://atd.knack.com/street-banners#get-started/) from Banners

**Comment by KaroEngstrom** [comment]
## Th 9/21/23 
- initial Getting Started draft page modeled after Banners: https://atd.knack.com/smart-mobility#living-streets-getting-started/

**Comment by KaroEngstrom** [comment]
## Fri 10/6/23 
- we need to get the details for this page from the Living Street team to update this page
- I want to close this initial build issue and create different issues for the follow-up items:
     - Update Living Streets Getting Started Page 
     - Update Living Streets Program Selection Buttons for All Three Programs 
          - We'll do this as part of 2.0 version down the line; I'm placing this in the icebox
