### ISSUE TITLE
[Enhancement] Ability to advanced search for projects which have/don't have children 👨‍👩‍👧‍👦

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#13904]

**Comment by johnclary** [comment]
Since "we" did https://github.com/cityofaustin/atd-moped/pull/1134 - add the ability to use an advanced search filter that returns only projects that have child projects, aka subprojects. The field of concern is called `children_project_ids` in the project list view. I guess we could allow operators `is blank`, `is not blank`, and `contains`?

**Comment by chiaberry** [comment]
as for contains -- should a user be able to search by subproject id, or is the expectation by subproject name?

**Comment by johnclary** [comment]
i am in favor of the smallest possible scope. it doesn't really make sense to search by subproject IDs—you could easily just open the subproject to find the parent, right?

i guess the ideal would be to search for "Has subrojects" as "Yes" or "No". At least that's the concrete use case we have.

If it is easier to search by "Subproject IDs" are blank/are not blank that would be fine, too. i don't want to ask for anything that is going to require a lot of GQLAbstract work. and it would be ok if it makes sense to shelve this for now. having the two new columns you added @chiaberry make it possible to use use at least export all projects and sort them at way.


oh wait—do we need to add those new columns to the CSV export?
