### ISSUE TITLE
Move Polygonizer QGIS plugin to City of Austin account

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13909]
## Description
Currently the Polygonizer QGIS plugin is published under Frank H's personal account. This issue is to move it to a City of Austin account for ownership and maintenance.

## Deliverables
- Create City of Austin account on QGIS plugin repository
- Publish code to QGIS plugin repository under City of Austin account
- Document process for future maintenance

## Notes
- Frank has agreed to help with documentation and transition. This will protect the plugin in case of any changes to Frank's involvement.

**Comment by frankhereford** [comment]
This project is going to be superseded by a custom solution being developed internally by the VZ team.
