### ISSUE TITLE
Curb/Gutter Initiated by District - Acknowledge WOs

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#13921]
This request is to update all work orders up to 07/01/23 as ACKNOWLEDGED, irrespective of their statuses. Start Center is SBO IMG.

- [ ] Update work orders to ACKNOWLEDGED in Flex Field 2, cut-off date 06/30/23
- [ ] E-mail William Espey and Samuel West of the Portlet and to have them review those requests

**Comment by ReneVarg25** [comment]
Acknowledged Work Orders up to 07/01/23 and emails William Espey and Samuel West.
