### ISSUE TITLE
Data Request: AMANDA Export For SXSW Map App

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1392]
**Scope:** Export SXSW 2020 data from AMANDA that in previous years was exported from SharePoint. 

Requested by Diana on 2/6/2020. 

[temp_permits_fields.xlsx](https://github.com/cityofaustin/atd-data-tech/files/4167228/temp_permits_fields.xlsx)

**Comment by dianamartin** [comment]
![image](https://user-images.githubusercontent.com/21112975/73968854-fdbab500-48df-11ea-8177-eb4bcb80b100.png)

![image](https://user-images.githubusercontent.com/21112975/73968894-0e6b2b00-48e0-11ea-9f5f-d138e808bf36.png)

**Comment by dianamartin** [comment]
@TracyLinder I added some things for you to look at. I guess, I'd like to see what AMANDA looks like and how they have the data, bc I'm sure it's different.

**Comment by TracyLinder** [comment]
@dianamartin and I met about this briefly today. I've got enough info to get started.

@dianamartin I set up a mtg with Maria on Monday, so I'll clarify the dates we should use for the query.

**Comment by TracyLinder** [comment]
Notes re: attachments:
- Attachments
    - Name (attachmentdesc)
    - URL = DOSPATH
    - tablersn = folderrsn

Here's a query:
>Select a.attachmentrsn, a.tablersn as folderrsn, a.attachmentdesc, a.dospath
From attachment a
Where a.tablersn = 12355838

**Comment by SurbhiBakshi** [comment]
I can't locate Amanda.FolderPriority - 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/9defd6ed-0609-40d9-a110-feb8548a3a29)

**Comment by SurbhiBakshi** [comment]
Mtg Date/Time/Location: 2/10/2020 / 3pm / Skype
Attendees: Tracy L, Maria A, Diana M

Objective: Use this doc to map data elements from the 2019 SXSW app to the current data that lives in AMANDA.

Agenda

 Note - AMANDA SXSW 2020 Folder, here
 What date range to use for the query?
 Which folder types to include in the query?
SE, RW-Street Event, RW-Parking
 Walk through the spreadsheet & map the elements
