### ISSUE TITLE
Maximo, Pavement Ops & District Maintenance: Sweeping Requests

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#13939]
Pavement Operations and District Maintenance have agreed to provide dual-support when it comes to 311 sweeping requests that are related to Sealcoat projects and requested the Maximo team to provide support to track such support in the work order tracking system.

**Comment by adry-martinez** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBalhFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6133ddb50671a5f1a2fd52805e5a6813b10f2de7/image.png)

**Comment by adry-martinez** [comment]
- [ ] add SBO SEALCOAT to Flex Field 2 - Work Group to Notify
- [ ] add Sealcoat Requests initiated by District Maintenance
- [ ] write SOP on 
- how to capture labor and tool efforts for Sealcoat (update Sweeping WOs with updated actuals)
- CSRs inquiring on ETA for Sealcoat projects
- CSRs concerning condition of street after a sealcoat (inquiries, not sweeping requests), assign to Sealcoat Team

- [ ] discuss document with Pavement and District DMs

**Comment by adry-martinez** [comment]
Flex Field 2 updated and portlet added to SBO Pavement Ops on 9/21
SOP draft in progress

**Comment by adry-martinez** [comment]
how to capture labor and tool efforts for Sealcoat (update Sweeping WOs with updated actuals)
- Create Parent for Sweeping Request and Complete Child CSR-WO if District Maintenance does not have the capacity to respond.
- Discuss if ARR gets any sweeping requests.

**Comment by adry-martinez** [comment]
Update to include all CSRs goes to OCE regarding inquiries, if it is a sweeping request, send to District Maintenance, they will use Flex Field 2 to notify Sealcoat of Sweeping requests.

**Comment by dianamartin** [comment]
# 1/24/24
- Meeting schedule 1/24 for Maximo Bi-weekly Project Coordinator meeting
- Have follow up on what the roles and responsibilities are for the agreed upon process

**Comment by adry-martinez** [comment]
- Schedule meeting with OCE staff and PCs to discuss new process

**Comment by adry-martinez** [comment]
## 2/9/24
Meeting scheduled for 2/21 

## Agenda for 2/21

- Maximo facilitating the meeting for SBO and OCE to have discussions on new triaging efforts for sweeping responses.
- _Update to include all CSRs goes to OCE regarding inquiries, if it is a sweeping request, send to District Maintenance, they will use Flex Field 2 to notify Sealcoat of Sweeping requests._

**Comment by adry-martinez** [comment]
### 2/14/24 

Send follow-up e-mails

**Comment by adry-martinez** [comment]
### 2/26/2024
Create portlet for Sealcoat notification from District Maintenance 
![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/4d4e458b-9b08-4396-ab73-7241564561cd)

Users notified.

**Comment by adry-martinez** [comment]
### Mar. 1. 2024
Pending review by DTS team for feedback before receiving signatures from DMs.
[Maximo Standard Operation Procedures, Triaging Debris in Street Requests](https://docs.google.com/document/d/1YQyK4FTqafe4Hl7hlJrVFc1LSoQHvF0k4KOA19jdyFM/edit?usp=sharing)

**Comment by adry-martinez** [comment]
@dianamartin could I share this with the DMs for approval? do you have any feedback on this document before I share this with staff? thank you!

**Comment by dianamartin** [comment]
@adry-martinez the document looks good. Where would this document permanently live? The GitBook wiki where we think everything else will live?

**Comment by adry-martinez** [comment]
@dianamartin Yes, we can have it added to the GitBook wiki!

**Comment by adry-martinez** [comment]
### Apr. 8, 2024

E-mail sent to Jermaine B. for signature, pending response.

**Comment by adry-martinez** [comment]
### April 16, 2024 

Document completed, and uploaded to [GitBook Wiki](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/QMuMrK3UWgrwcodLRmTg/part-8-standard-operating-procedures)
