### ISSUE TITLE
[Enhancement] Update Fatalities Tracking Tool views query for performance

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13932]
## Description

This will be necessary to address after we switch to Aurora #11895

(12/28/23) Now that we've updated to AWS Aurora the VZ team has noticed that the FTT is taking longer to load on each page load. We'll need to see if the query is causing this delay. 

## Notes
- Make sure to document well and see if we can update performance 
   - View recent Moped performance updates Issue ##13857

**Comment by johnclary** [comment]
This work is being addressed in the layer data model. We can safely close this 👍
