### ISSUE TITLE
Setup ATD / Launch IT Workflows & Trello Board

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1394]

**Comment by TracyLinder** [comment]
https://trello.com/b/2MZ7yNTv/atd-lit

**Comment by johnclary** [comment]
@dianamartin is going to take a first pass at this today.

**Comment by TracyLinder** [comment]
@johnclary this is a duplicate; I pointed Diana to the correct issue and I'm closing this now.
