### ISSUE TITLE
Coding It Forward Fellowship 2024

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#13940]
Partnership with [Coding It Forward](https://www.codingitforward.com/) from June 10-August 16 where recent graduates or current university students work on projects with DTS over the course of summer.

### Timeline

**Summer 2023**
Host offices assess their internal finances and begin the contracting process with Coding it Forward. 

**October 16, 2023**
Applications open for prospective Fellows. 

**October 27, 2023**
Submit your position descriptions to the Coding it Forward team by this date.

**October 29, 2023**
Applications close for prospective Fellows. 

**January 2024**
Host offices interview candidates. 

**Late January/Early February**
Offers are extended to candidates. Once offers are accepted, the onboarding process begins. 

**June 10, 2024**
First day of Fellowship.

**August 16, 2024**
Last day of the Fellowship. 

#### Links
- [Partnership website](https://www.codingitforward.com/2024-partners) Password protected, contact Patrick

**Comment by amenity** [comment]
Moving to In Progress pipeline
