### ISSUE TITLE
Feature: Permit # on RTPC Payment Failure Template

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1395]
Request to CTM: Update the RTPC payment failure email to include the permit number, so staff can see the permit type without having to open AMANDA.

**Comment by TracyLinder** [comment]
### UAT Feedback to Swapna Today:

Hi Swapna,

Thank you for following up with me about this. I just forced a payment error and received the email attached. It doesn’t have any indication of the folder type. In the first thread of this email, the error message includes the permit number. That is missing in the test I just did (see email).

**Comment by TracyLinder** [comment]
Tested again, UAT successful. 
I asked Swapna to promote to PROD

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/d9a61a76-5d87-4714-a3d9-3870bc28d21f)

**Comment by amenity** [comment]
@Nadin-Nader @SurbhiBakshi - it looks like this was a request that went to CTM. Is there a way to look it up in ServiceNow?

**Comment by SurbhiBakshi** [comment]
@amenity @Nadin-Nader I can't find anything, I suggest asking Swapna or George. What does RTPC mean?

Also, it looks like Tracy asked for this to be promoted this to Prod, and it was for DS permits? the ticket might have been closed already.

**Comment by amenity** [comment]
This has been deployed.
