### ISSUE TITLE
[Tech Debt] Cleanup the `atd-vzd` triggers and views folders

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#13950]
We haven't come to a solid decision on whether to keep folders for version-controlling triggers and views similar to the [Moped views folder](https://github.com/cityofaustin/atd-moped/tree/main/moped-database/views). That folder has been helpful for tracking changes in the project list view over time.

If we decide to keep the folders around:
- clean up the folders to reflect triggers and views that are in use (some of these files could be crufty and/or out of date)

If we decide to part ways with them:
- remove the `atd-vzd/triggers` and `atd-vzd/views` folders and rely on searching through migrations and inspecting the DB

**Comment by chiaberry** [comment]
I find the files helpful in moped, so my vote is to keep the folders but clean them up.

**Comment by johnclary** [comment]
Tagging this with layer data model — let's take advantage of the fresh start 🧹

**Comment by johnclary** [comment]
This got done somewhere along the way to releasing v2.0
