### ISSUE TITLE
[Enhancement] Add "On Hold" Status for Artbox Projects

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#13961]
From primary user Sandra C.: 

As I use KNACK more now, I am finding that a lot of projects need to be put on hold status.  Is there a way to add “On Hold” to the Project Status?  I know that I can add a non-milestone entry which will add a note to the bottom of the list, however, it would be extremely helpful to be able to see which projects are active and which projects are on hold.

![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/e9cbd069-aaa2-4cba-97cd-2d9d45a726ae)

**Comment by KaroEngstrom** [comment]
## 10/05/23 
- Sandra asked me about this again via email. I think this is possibly a quick build but there is a complex setup in place with wanting to use the milestones in a table (like a spreadsheet) and have them transfer into the milestone dates details above. I'd need to look at the set of rules to be sure how to incorporate the On Hold status.

**Comment by patrickm02L** [comment]
On the agenda for 10/11/23 Refinement

**Comment by KaroEngstrom** [comment]
### Tue 10/10/23 
- Investigated this in TEST and I need to review/update the milestone dates and status pushes in PROD and then just add this status and the button for Sandra to be able to place the projects on hold
- with that testing already completed + ^ the work described there, this is a 2
