### ISSUE TITLE
MDS | Back fill MDS historical data

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1397]
We need to backfill the historical MDS data for each of our providers onto the new system that Sergio built. We should begin with this month's data (February 2020) and work backwards.

**Comment by sergiogcx** [comment]
Working on this now, this issue will require that:

- [ ] All schedule blocks are reset to status 0 (*new*)
- [ ] DAGs for production are up and running

- The creation of a script that will:
- [ ] Run production docker containers with necessary parameters
- [ ] Utilizes time deltas to add 1 hour from current schedule
- [ ] Gathers the current schedule hour block, and allows to force-reset.
- [ ] Works with time-min, time-max and provider fields as other scripts.

**Comment by sergiogcx** [comment]
The data has been back-filled, ready for review.

**Comment by sergiogcx** [comment]
The back-fill is done for YTD and reported on, closing.
