### ISSUE TITLE
[Enhancement] Ability to hyperlink to a component

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#13977]
Moped users need the ability to hyperlink to a project component. For example, a user may want to navigate from a project component on an ArcGIS Online map to the component edit UI in Moped.

Proposed behavior:
1. When a component list item is focused/expanded, the window URL should update with a parameter that includes the `project_component_id` id. e.g. `https://mobility.austin.gov/moped/projects/225?tab=map&project_component_id=1230`
2. If the user navigates to a URL that contains the `project_component_id`, the component should be focused when the page loads (ie the component list item should be expanded), and the component list should be scrolled so that the focused component's list item is visible on the screen.
3. Add a link icon button to the component list item action buttons so that a user can click to copy a link to the component.
4. If the component ID is not found to be associated with the current project (either because it was deleted, moved, or an unknown ID), we should display a dismissable [error snackbar](https://mui.com/material-ui/react-snackbar/) in the top-right corner of the page. it should say "Component ID `#<component-id>` could not be found. The component may have been moved to another project or deleted. Please check this project's activity log for more details".
5. This out of scope, but note that a future request my ask to be able to hyperlink directly to the component **with the edit form/modal open**

Worth noting that we have fairly similar behavior enabled on the [data dictionary](https://mobility.austin.gov/moped/dev/lookups) page.

**Comment by mddilley** [comment]
@johnclary I was thinking about this one over lunch, and I think we will end up with broken links if someone saves a link, they or someone else moves the component to another project, and then they try to access the original link.
Example:
- `https://mobility.austin.gov/moped/projects/225?tab=map&project_component_id=1230`
- component `1230` is moved from project `225` to project `325`
- new links is `https://mobility.austin.gov/moped/projects/325?tab=map&project_component_id=1230` and the old link is no longer accurate

I can think of a few ways to handle this but wanted to get your thoughts too.
- handle when a link doesn't arrive at a the correct project for the linked component
- create a route that only contains a component id that then fetches the correct project and forwards to the right project's map view (this might get awkward but maybe not). Something like `https://mobility.austin.gov/moped/components/1230`

**Comment by johnclary** [comment]
@mddilley thanks flagging that. we discussed this in slack and agreed that in the near term, it would be good to display a dismissible snackbar message if the component ID is not found. i will update the issue description accordingly.
