### ISSUE TITLE
Maximo, Pavement Ops, Requesting Restrictions

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#13982]
requesting to add restriction to SEALCOAT_WORK work orders that requires Length and Width to be required before 4COMP, will need to include CTM in the discussion.

**Comment by adry-martinez** [comment]
Will need to clarify if this will also be required for Overlay.

**Comment by YakshDipa** [comment]
Sent email to Andre

**Comment by adry-martinez** [comment]
Closed, see 14392
