### ISSUE TITLE
Maximo, Pavement Ops, Update to Completed Lane Miles Report

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#13981]
PC Ewing requesting for Pavement Reports to:

- [x] remove contractor
- [ ] move total of lane miles and # of projects completed to the first page @YakshDipa

**Comment by adry-martinez** [comment]
**Remove Contractor from Completed Lane Miles Report:**

Completed Lane Miles Report is used by OCE as they are tracking CONWK on their end. Data loaded includes contractor projects, which goes to SBOIMG workgroup. We will not be able to remove

**Comment by YakshDipa** [comment]
Update the report
