### ISSUE TITLE
MDS | Onboard Ojo

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1398]
We need to onboard Ojo as a new MDS provider. 

- Use the credentials provided by their team to access their MDS provider API
- Verify that their API meets MDS specs
- Begin pulling their data into the system that Sergio has built

We are currently awaiting their credentials.

**Comment by sergiogcx** [comment]
I've onboarded OJO to our ETL process, I am able to extract data from their system.

![2020-02-18_13-39-31.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/323e530a-1088-4371-9dcc-fdb3af10dd1f)

Trips Data (as downloaded from S3):

![2020-02-18_13-40-05.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/20c91a08-3c93-42ad-89d5-7462abb71de7)

**Comment by sergiogcx** [comment]
OjO is fully onboarded and reported on, closing.
