### ISSUE TITLE
MDS | Onboard Wheels

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1399]
We need to onboard Wheels as a new MDS provider.

- Use the credentials provided by their team to access their MDS provider API
- Verify that their API meets MDS specs
- Begin pulling their data into the system that Sergio has built

Contact @JaceDeloney for credentials

**Comment by JaceDeloney** [comment]
I have the credentials for the Wheels provider API. Please reach out to me when you are ready for it!

**Comment by sergiogcx** [comment]
Wheels has also been onboarded, we can extract data from their endpoint. The data gets automatically saved to S3, where it can be later processed (sample data downloaded from S3):

Picture of the ETL process extracted the data and saved it to S3:
![2020-02-18_13-47-18.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/f8b98af7-76f3-4b50-85c8-907005b00935)

![2020-02-18_13-44-44.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/51212119-f56c-4a51-9b68-b14442ef05d8)

This is the picture of the file in S3:
![2020-02-18_13-46-23.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/3898add4-7320-4cad-b1d0-3a1c95236966)

**Comment by sergiogcx** [comment]
Wheels is fully onboarded, closing.
