### ISSUE TITLE
Renew wildcard SSL/TLS cert for `*.visionzero.austin.gov`

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#13994]
A wildcard cert used in one or more of our vision zero applications is set to expire on October 26, 2023. It is imperative that this be renewed on time. Because this is issued from a commercial provider, there may be a cost involved. 

Here's a starting-point on action items to consider:

 * [ ] Find all places this is used. Likely spots include netlify & AWS.
   * [ ] Are any services or redirects served by CTM machines? Coordinate with them?
* [ ] Renew the certificate
  * [ ] Create a CSR using the same metadata as used in the previous cert
  * [ ] Apply for the certificate to be signed
  * [ ] Pay for it, including whatever backend paperwork required
* [ ] Install the new certificate
* [ ] Create a calendar invite for the expiration of the cert

**Comment by johnclary** [comment]
just confirming what Mike mentioned in planning: we have a CloudFront distribution where this cert needs to be installed. (in addition to Netlify and potentially other places).

**Comment by frankhereford** [comment]
Thanks John for adding that note and also thank you Mike for that helpful information. I was in the AWS certificate manager today, and we had, at one time, imported both of these certificates, but we have not kept them up to date, so they are expired in AWS. I didn't pull that thread anymore to investigate because I was working on a graphql-engine setup, but that's something to look into as well.

**Comment by frankhereford** [comment]
I got an email out to Jason G. at CTM as well as to the wider linux group with our CSRs. I'll report back anything I hear from them to y'all of course.

**Comment by frankhereford** [comment]
This was installed and tested. A zip file containing the key, certificate and other artifacts of the renewal process have been placed in 1Password.
