### ISSUE TITLE
Define Knack App Readme Template

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#14]
All knack app repositories should have a readme that follows the same structure.

Proposing:

```
# App Name
<description>

#### Login
<login url>

#### Stakholder Divisions
- <stakeholder 1>
- <stakeholder 2>

**[Read the docs](<documentation url>)**

![screenshot](screenshot.png)
```

For example:
https://github.com/cityofaustin/transportation-data-tracker/blob/master/README.md

**Comment by johnclary** [comment]
@amenity @dianamartin any feedback? can we close this out?

**Comment by dianamartin** [comment]
@johnclary @amenity It like this and have already followed the template. Let's close this.
