### ISSUE TITLE
MDS | Onboard Revel

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1400]
We need to onboard Revel as a new MDS provider.

- Use the credentials provided by their team to access their MDS provider API
- Verify that their API meets MDS specs
- Begin pulling their data into the system that Sergio has built

We are still awaiting their credentials

**Comment by sergiogcx** [comment]
Removed Revel from being part of the Epic, we need more details as far as how soon they can provide an MDS endpoint we can gather data from.

**Comment by sergiogcx** [comment]
It looks like revel will provide data monthly, since they do not have an API.

Closing for now.
