### ISSUE TITLE
"Special case" columns in fact tables in LDM

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#14008]
Please see the conversation around these comments: 
* https://github.com/cityofaustin/atd-vz-data/pull/1288#discussion_r1337431741
* https://github.com/cityofaustin/atd-vz-data/pull/1288#discussion_r1337459479

At present, the LDM has only a handful of columns which get special handling in how they are coalesced between the CRIS/VZ fact tables, and all the rest are handled generically.  There's nothing wrong with this per se, but there are opportunities to leverage the unifying view in such a way as to do dynamic computation of some data and to make considerations in how that unification goes. For example, consider the `last_update` field in each fact table pair. It is defined in a non-generic way, like this:

```
            case
                when 
                    vz_facts.atd_txdot_crashes.last_update is not null
                    and cris_facts.atd_txdot_crashes.last_update is not null
                    and vz_facts.atd_txdot_crashes.last_update > cris_facts.atd_txdot_crashes.last_update 
                        then vz_facts.atd_txdot_crashes.last_update
                when
                    vz_facts.atd_txdot_crashes.last_update is not null
                    and cris_facts.atd_txdot_crashes.last_update is not null
                    and vz_facts.atd_txdot_crashes.last_update < cris_facts.atd_txdot_crashes.last_update 
                        then cris_facts.atd_txdot_crashes.last_update
                else 
                    coalesce(vz_facts.atd_txdot_crashes.last_update, cris_facts.atd_txdot_crashes.last_update)
            end as last_update
```

In this case, the thinking goes like so:

* We're always going to have a `last_update` value in both fact tables because, well, if the records exists, it's been updated. 
* Therefore, it's not helpful to just always return the VZ one which is the generic behavior, because the CRIS one can be updated too by CRIS. 
* Therefore, the way to "unify" this particular column is to check both values and end up returning the one that is more recent, because that is the "intent" of a `last_update` field.

It's important to note that there is not a formula or really a pattern that is going to jump out to be followed. It takes careful consideration of the columns, what they contain, what that information is based on, how it interacts with other columns and other factors to decide if a non-generic way of handling a column is needed. 

This is art and not a science and it's arguable that this is at the absolute core of what makes the LDM tick.

**Comment by patrickm02L** [comment]
## 9/27
- We'll need to break this down into separate Issues
   - Do analysis to look through the tables and compile in the list in a spreadsheet where the "special cases" exist
   - FH estimates 20 columns will need special handling
   - Facts tables: crashes, unit, persons, primary persons

**Comment by johnclary** [comment]
We have this covered by other data model work—closing.
