### ISSUE TITLE
IT Support: Inventory for DEOC

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#14007]
CAMERON

## What's the problem?
V can you do an inventory of the current equipment stored at Cameron? 

Please create an Excel sheet and place it in the SharePoint

**Comment by Matthew-M-TPW** [comment]
Sending this to strange since he will be at Cameron on Friday

**Comment by Vaishnav1397** [comment]
Updated received that we total 12 monitors, 2 printers and a bunch of keyboards, mice and cables in the closet at 8700 Cameron.

**Comment by Matthew-M-TPW** [comment]
This was completed a in October
