### ISSUE TITLE
Update SLA Document and Maximo

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#14005]
We have recently discovered that the SLAs in Maximo and in our documentation are incorrect. We will need to update both to reflect the correct SLAs and prevent further issues from occurring. The changes are listed below.

 
                    SR Type	                                    Current SLA	              Proposed SLA
             Pothole Repair	                                  4 business days	     7 calendar days
Alley and Unpaved Street Maintenance                	90 days           	    90 calendar days
                S&B Gen	                                                30 days	            30 calendar days
           Debris In Street	                                 1 business day	     2 calendar days
          Roadway Spillage	                                 1 business day	     2 calendar days
          Utility Cut Repair	                                 3 business days	     7 calendar days
          Pavement Failure	                               14 business days	    21 calendar days
         Street Resurfacing 	                               14 business days	    21 calendar days
           Tree Issue ROW	                               14 business days	    21 calendar days
 
Debris in Street has an overall SLA of 30 days.  Changed to 30 calendar days.

Roadway Spillage has an overall SLA of 1 day.  Changed to 2 calendar days.

Utility Cut Repair has an overall SLA of 90 days.  Changed to 90 calendar days. 

Street Resurfacing has an overall SLA of 30 days.  Changed to 21 calendar days. 

Tree Issue Right of Way has an overall SLA of 90 days.  Changed to 21 calendar days.

**Comment by adry-martinez** [comment]
[Document ](https://cityofaustin.sharepoint.com/:b:/r/sites/MaximoResources/Shared%20Documents/Quick%20Reference%20Sheets%20(QRS)/3%20-%20Austin%203-1-1%20and%20Maximo/SBO%20Maximo%20and%203-1-1%20Service%20Level%20Agreements.pdf?csf=1&web=1&e=3VndA9)updated on SharePoint
