### ISSUE TITLE
Access Maximo Enterprise Database data in PowerBI

### ISSUE THREAD

**Issue by michael-santulli** [cityofaustin/atd-data-tech#14019]
Many data visualizations used SBO for tracking performance come from the list of work orders stored in Maximo.
On 9/20/2023 we looked into the Maximo enterprise database and were able to filter the data down to the department level which may be enough to begin working with the data in PowerBI if it is possible to connect.

Full meeting recording [here](https://cityofaustin-my.sharepoint.com/personal/kate_lunceford_austintexas_gov/_layouts/15/stream.aspx?id=%2Fpersonal%2Fkate%5Flunceford%5Faustintexas%5Fgov%2FDocuments%2FRecordings%2FTPWstat%20Maximo%20and%20Open%20Data%20Portal%20Discussion%2D20230920%5F090613%2DMeeting%20Recording%2Emp4&ga=1). 

The table we looked at was MAXIMO_DM.FCT_WORKORDER
**Some of the fields we noticed that may be useful for filtering:**

- To filter by department use the field SITEID
- To filter by division within TPW use the field PERSONGROUP.
- To filter by data source use the field COA_SOURCESYSTEM. "AW-HANSEN" should be the work orders handled by the UER workgroup. This field could also tell us which work orders come from 311

The Utility Cut Backlog is one key performance measure that might be a good candidate to try and automate first. Below are all the filters I think would need to be applied (either in PowerBI or in the query to the original database). The ones in bold I think we have figured out, for the others we might need to explore the database more to know what fields/values to filter.
- **Department:** `SITEID = "SBO"` for Street and Bridge Operations
- **Division:** `PERSONGROUP = "SBOUTIL"` for Utilities and Structures Division
- **Data source to Maximo:** `COA_SOURCESYSTEM = "AW-HANSEN"` for work orders coming from Austin Water
- Workgroup: More specific than division, this would be the Utility Excavation Repair group in the Utilities and Structure division. Data source (above) might be sufficient to capture their work though.
- Status: Open or in progress (may include several different status codes)
- Age of utility cut: Usually report total as well as > 90 days old
- Start date (?): May want to exclude very recent work orders if we want to report the status as of the end of the last month

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXZrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c2e7cab8209ad6c88fad632cabb72b625db95131/image.png)

**Comment by amenity** [comment]
Per refinement discussion today, @Charlie-Henry is going to use a CSV for this initial deliverable so that he can focus on the PowerBI part of the implementation rather than stepping through the data warehouse.

**Comment by Charlie-Henry** [comment]
Sent @michael-santulli an export of the Maximo data in Slack. Michael should open a service now ticket with CTM to get an account created for the Maximo data warehouse if he wants to connect directly to it in Power BI.

**Comment by katelunceford** [comment]
This is almost done. Just waiting on Michael's computer to download (he doesn't have admin rights)

**Comment by Charlie-Henry** [comment]
Michael is connected!

**Comment by michael-santulli** [comment]
For future reference, here are the steps to connect PowerBI to the Maximo Data Warehouse:
(Note - Request a username and password from CTM first)

1. Download the Oracle client tool here: https://www.oracle.com/database/technologies/appdev/ocmt.html

2. Run the Notepad app as an admin

3. Navigate to the folder below to open the `tnsnames` ORA file 
C:\Program Files (x86)\Oracle Client for Microsoft Tools\network\admin\sample

Add this configuration in place of the sample:
MAXIMO = 
  (DESCRIPTION = 
    (ADDRESS = (PROTOCOL = TCP)(HOST = ctmdwdbp.austintexas.gov)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = dwhprdpdb) 
    ) 
  )

4. In PowerBI, connect to an Oracle database and enter MAXIMO for the server, along with your CTM provided credentials. You can also enter a SQL query at this step to pre-select what data you want, or you can do all the filtering in PowerBI.

**Comment by amenity** [comment]
Thanks, @michael-santulli !

**Comment by rebekkabry** [comment]
# 5/6/24

- Work session with Michael with connect
- Added additional screenshots to capture details of process 
- Received SQL process from Michael
- 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/ffbc3006-1a18-427d-a281-8a89139cddae)
