### ISSUE TITLE
Identify Special Case columns

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14018]
## Description
   - Based on 9/27 refinement of #14008
   - Do analysis to look through the tables and compile in the list in a spreadsheet where the "special cases" exist
      - take inspiration from #12647 for pg triggers for the spreadsheet
   - Break down individual Issues by the following Facts tables: crashes, unit, persons, primary persons

## Notes
 - FH estimates 20 columns will need special handling

**Comment by mddilley** [comment]
I added some tabs to the same trigger sheet and added some logic to highlight columns that come from CRIS in green. The other columns should be the ones that we focus on.
https://docs.google.com/spreadsheets/d/1Gxl-d56n89LlM9n99weCMKZz9oQCxkcqhHgkDHBgRmQ/edit#gid=395451846

**Comment by mddilley** [comment]
Closing since we are moving the VZ data model in a different direction. See https://github.com/cityofaustin/atd-data-tech/issues/15976

**Comment by johnclary** [comment]
👍 we have this covered by other data model work. Closing.
