### ISSUE TITLE
Micromobility Per-Trip Fees

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1401]
The City of Austin has approved a per-trip fee structure for shared micromobility services. In order to support a per-trip fee structure, DTS needs to backfill all of the MDS data to the new database. We also need to onboard 3 new operators. Finally, we need to create a report whereby ATD Shared Mobility Division staff can charge micromobility operators after each month of operation.

**Comment by sergiogcx** [comment]
This Epic is done, separated Revel because we don't know when we are going to hear back from them.
