### ISSUE TITLE
Update Transportation Engineering Review Infos + Comment Docs (LP) (On PROD with No Bugs, Waiting on LDE Team for UAT)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14028]
### Updates to the distribution infos used by Land Use Review and to the comment docs they use.
_Customers are Elizabeth B. and Samuel W._
**DSD Dependency**

**1. Transportation Engineering Review? (51982)**
- [x] Update info description to **Land Development Engineering**

**2. Transportation Engineering Reviewer (51983)**
- [x] Update info description to **Land Development Engineering Reviewer**
- [ ] Remove all existing info values
- [ ] Add new value _Land Development Engineering_
- [ ] Default info to _Land Development Engineering_

**3. Create User Group**
- [ ] Create new user group called **Land Development Engineering**

**4. Update Review Comment Document(s)**
- Document ID is 28524389 is configured on SP, C8 folders
- I'm not sure if it's the same doc on all folders, or a unique doc for each. I also don't know the document name. _(Tracy)_
Updates to make:
- [ ] Update the document name to **Land Development Engineering**
- [ ] Update the heading from **Transportation Engineering** to **Land Development Engineering**

**5. Update auto-insert of Review Comment Doc**
- The user states that on C8 folders, the review document doesn't insert automatically by the system. They have to insert it themselves. 
- [ ] When the system inserts process 51212 Land Development Engineering, it should also insert the related review comment document.

**Comment by TracyLinder** [comment]
Scoping scheduled for 10/2/23

**Comment by TracyLinder** [comment]
### Scoping 10/2/23


**Review Comment Doc**

What folders is this programmed on? 


Residential - all being done by email
Sites - Assigned via KNACK 
Attached things to DS permits, PR folders

**Comment by TracyLinder** [comment]
### Scoping with Patrick & Boz 10/3/23

- This review is currently being used on SP, C8, SC
- On C8 and SC the comment doc doesn't insert by system. The user inserts it manually. `we need to fix this`
- Comment doc ID is 28524389. The title of the doc needs to be updated
- I told BOZ we'd put this on deck for the sprint beginning 10/18


<img width="643" alt="Screenshot 2023-10-03 at 2 46 25 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/49930868/8eee80ce-084c-4688-be27-f9fda0d661b7">

**Comment by TracyLinder** [comment]
FYI @Nadin-Nader this is ready for development. I'll put it at the top of the backlog.

**Comment by TracyLinder** [comment]
@Lpriya-LIT please perform your analysis and let me know if you have any questions.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created Manual deployment request - SCTASK0372920

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Done commit, Ready for Dev deployment

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0373987**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV please UAT

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been deployed to TEST please UAT and let me know if it is ready for the Stakeholders to UAT

**Comment by Nadin-Nader** [comment]
@TracyLinder who can we get to UAT this on TEST?

**Comment by TracyLinder** [comment]
UAT meeting scheduled for 12/22

**Comment by TracyLinder** [comment]
### UAT Notes

- On SP, all of the drop-downs were defaulting to Jennifer Back. Her name should not be in the drop-down; only the resource account. The info should default to Land Development Engineering
![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/bed10536-6e4c-42c8-b6a0-ca319b35450e)

**Comment by TracyLinder** [comment]
I have scheduled another group UAT session with a SPOC from DSD (zach W) to assist with testing the workflows correctly, for **1/8/24**

**Comment by TracyLinder** [comment]
### UAT Session 1/8/24

Zach: Be sure the info list is alphabetized 



submittal intake: case assigned --- inserts initial distribution
initial distribution: complete --- does the distribution
awaiting update --- formal update recieved, inserts update distribtuion
update distribution - complete --- does the distribution



The doc isn't titled:

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/ff318c0a-3694-48dc-876f-bf49df7fd14a)

**Comment by TracyLinder** [comment]
### UAT Results - Bugs Found

1. ✅ On some cases the info still had Jennifer Beck listed in the drop-down values. I think that's leftover stuff; not a bug. But just FYI. 

2. ❌ On C8, the comment document did not insert with the process. RSN is 13073726. The comment doc should insert when the process inserts. 

3. ❌ On SP, the comment doc is missing the heading. The heading should say Land Development Engineering, and it should be in the box at the top of the page. 


FYI @Lpriya-LIT this is ready to pick up again. I will put it On Deck. FYI @Nadin-Nader

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT is still working on this one

**Comment by Lpriya-LIT** [comment]
<img width="962" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e6e5773810928af0a6bad4930e068ada47bdfa3/image.png" alt="image.png" />

**Comment by Nadin-Nader** [comment]
DSD is going ahead with their changes for this first Since DSD has to mess with the infos, we will push the name change to PROD on Monday. According to Christopher M. at DSD should be done with their changes by next week Wednesday, Thursday if CTM can get the name change to PROD.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created request to promote devops commit to Prod, SCTASK0405590

**Comment by Nadin-Nader** [comment]
George will be deploying the name change today. Once done i will let Christopher know so that DSD can make their changes.

**Comment by Nadin-Nader** [comment]
George will be deploying the name change today. Once done i will let Christopher know so that DSD can make their changes.

**Comment by TracyLinder** [comment]
### Bug Found ❌

FYI @Lpriya-LIT @Nadin-Nader this needs to be fixed urgently

**In both test and prod, the system is not assigning the folder process to anyone.** 
PROD RSN: 13302153
TEST RSN: 13208669


<img width="1210" alt="Screenshot 2024-03-25 at 2 25 30 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/49930868/df619de9-0f78-4412-bc9a-fceb8db61a91">

**Comment by TracyLinder** [comment]
I let Zach W. know the processes aren't being assigned.

**Comment by TracyLinder** [comment]
### BUGS ❌
- System did not insert the corresponding review comment doc. RSN 13073726. C8

**Comment by TracyLinder** [comment]
### BUG ❌
- This process and process doc was not added to SC folder

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT just fyi

**Comment by Lpriya-LIT** [comment]
Update - Assigned user issue has been fixed on SP, Please refer screenshot

**Comment by Lpriya-LIT** [comment]
<img width="1527" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzRPQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd95e29ac515cc0b947bd594a6d6d8dc730d0137/image.png" alt="image.png" />

**Comment by TracyLinder** [comment]
### Update on Bugs:
1. Process assigned to bug has been fixed
2. The fix for review comment doc not inserting on C8 is going to prod soon
3. We will remove SC from the scope of this request as it doesn't function in the same way and may not be a requirement. We need to talk to the stakeholders about this.

**Comment by TracyLinder** [comment]
Regarding the SC folder, I added the topic to next month's LDE prioritization meeting, and I am removing it from the scope of this ticket.

**Comment by Lpriya-LIT** [comment]
<img width="1394" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW9WQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83406ef2e9a8ba4ffd8bc1dfd017b77808e6ad37/image.png" alt="image.png" />

**Comment by Lpriya-LIT** [comment]
Update - C8 document insert issue has been fixed in both Test and Prod, Please refer screenshot

**Comment by TracyLinder** [comment]
### Update

- All changes/updates are made and in PROD. We haven't received any bug reports yet.
