### ISSUE TITLE
Analyze TIA Mitigation Payment Data

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14034]
### Apps will perform an analysis of the mitigation payment data provided by Van with TPW Finance. 
- Data can be viewed by COA employees [here](https://cityofaustin-my.sharepoint.com/:x:/g/personal/tracy_linder_austintexas_gov/EdghbS_yeVRAhthnT4cQLxQBYL2-BeyN0gnpOHINDOu7Qw?e=uXaK6R).

**Comment by TracyLinder** [comment]
@ChrispinP FYI this has been created and assigned to you. I can't remember if you said you wanted to do this during the current sprint or the next, but I did put it On Deck. It also needs an estimate.

**Comment by ChrispinP** [comment]
During the Mitigation update for #14842 a fund verification field was add to capture missing or irregular fund data. Depending on acceptance of those enhancements, Van & Kat should have the tools necessary to analyze and edit fund information for all Mitigation records. 

Pending any further action.

**Comment by ChrispinP** [comment]
Initial and followup updates/analysis were completed for TED so they have the tools necessary to update TIA Mitigations. Template Google Sheet was created in TDS Portal > TIA Mitigations folder so Kat can import missing Case data and then add missing Mitigation data thereafter. Responsibility for updating data falls on TED as they should now have all the tools to complete their work.

Unblocking, Closing as no further action. Will continue to support as needed.
