### ISSUE TITLE
Enhancement: Create ETL script to pull `units` from data warehouse to Finance Knack App

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14030]
Similar to this issue [Enhancement: Create ETL script to pull financial_subprojects from data warehouse to Finance Knack App](https://github.com/cityofaustin/atd-data-tech/issues/12376), we are now needing to do the same thing for Units. 

**Related to a problem?**
- The [units object](https://builder.knack.com/atd/finance-purchasing/records/objects/object_7) already exists in the Finance and Purchasing Knack app with the fields that we need from the `units` dataset from the data warehouse.
- This is related to issue #13999. We will need to create the ETL for the `units` and then expand the units to include 6200. 

**Additional Context?**
- This is a higher priority issue because on October 1st, TPW will be under a new Fund and Department code and legacy Public Works staff will need to be able to find their units in the Finance and Purchasing Knack app for purchase requests.

**Comment by Charlie-Henry** [comment]
This should be populating in the finance-purchasing knack app!
