### ISSUE TITLE
[Enhancement] Implement SchemaSpy for Vision Zero

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14059]
## Description
Original Issue #3406

The goal is to implement SchemaSpy, a tool for visualizing database relationships, for the Vision Zero database, allowing users to have a quick and visual reference to the tables and their relationships, similar to how it is utilized in [Moped](https://db-docs.austinmobility.io/).

## Requirements
- Install and configure SchemaSpy to connect to the Vision Zero database
- Create documentation that outlines process and any regular updates needed

## Notes
- Makes sense to do this post LDM implementation

**Comment by patrickm02L** [comment]
This is something that I proposed having for quick reference. As I've gotten more familiar with DBeaver I'm able to see the relationship with the table through their visualization tools. While I think it would be nice to have a public facing version of this like Moped. Our ability to satisfy this request is available internally, therefore, I'm closing it out.

**Comment by johnclary** [comment]
this seems like a vanity project at this point, but i'm going to optimistically revive this
