### ISSUE TITLE
Update the fee amount for Initial Valet Operator fee to $295 (11/29) (LP) - (Ready to UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14075]
### Update the fee amount for Initial Valet Operator fee to $295

**Acceptance Criteria**

- Update the fee amount of Fee Code 75300 (Initial Valet Operator Fee) to $295

**Comment by TracyLinder** [comment]
Previously:
initial operating fee $50
Renewal fee $295

Now:
Both will be $295

**Comment by vschandramouli** [comment]
Moving to Backlog

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and sent you the dev deployment plan. Please request for Dev deployment

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0375210**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created Test deployment request , SCTASK0375817

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified on Test , Ready for UAT

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Please deploy to PROD

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created Prod Deployment request , SCTASK0378074

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder Changes deployed to Prod , Ready for UAT

**Comment by KyleErich** [comment]
@Nadin-Nader UAT approved on Prod. Thanks!
