### ISSUE TITLE
[BUG] Markings Work Order > AGOL Publisher is Failing

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1407]
The [markings work order publisher](https://github.com/cityofaustin/atd-data-publishing/blob/master/transportation-data-publishing/data_tracker/markings_agol.py) is failing with the error:

`This SqlTransaction has completed; it is no longer usable. Unable to delete features. (Error Code: 405)`

**Comment by johnclary** [comment]
Strange issue. The jobs dataset was somehow corrupted with an invalid "REQUESTER" fieldname. I was able to surface their error message by using the `rollback_on_failure` param of [FeatureLayer module](https://developers.arcgis.com/python/api-reference/arcgis.features.toc.html#featurelayer). 

I deleted the "REQUESTER" field and added a "REQUESTOR" field to match what's in the Knack application. I also added logic to apply the feature deletes in chunks, because large deletes occasionally fail if Esri's server is in a bad mood.

Ready to deploy.

**Comment by amenity** [comment]
@johnclary - was this ever deployed?

**Comment by amenity** [comment]
@johnclary 👆;)

**Comment by amenity** [comment]
Suzanne said that the information tables are showing but now the geometries are not. :(

**Comment by johnclary** [comment]
this issue is a dupe. this was deployed and running good as far as I knew. will try to find the more recent issue.

**Comment by johnclary** [comment]
Closing and moving this convo to #4985.
