### ISSUE TITLE
Show Venues: 1300 ft buffer of property

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#14094]

**Comment by ATD-ZachB** [comment]
G:\ATD\ATD_GIS\DTS_GIS_Workgroup_Support\DTS_Smart_Mobility_Office\Living_Streets_Program\Downloaded_Data|
Save data here

**Comment by Colemonj** [comment]
We are attempting to use the Comptroller.texas.gov websites [open data portal ](https://comptroller.texas.gov/transparency/open-data/search-datasets/)to identify specific businesses. There is a dataset for businesses that sell mixed drinks that we are thinking to use to identify show venues and bars/clubs in Austin ( https://data.texas.gov/dataset/Mixed-Beverage-Gross-Receipts/naix-2893 ). There is also a dataset for all [active sales tax permit holders](https://data.texas.gov/Government-and-Taxes/Active-Sales-Tax-Permit-Holders/jrea-zgmq) (all legal businesses) in the state that we could use to filter from to identify a wide range of businesses.

**Comment by Colemonj** [comment]
I was able to find a [dataset](https://gov.texas.gov/Apps/Music/Directory/results/venues/region/austin/p1) of venues in Austin that host live music events. Many of the venues are small bars or coffee shops that may need to be removed depending on the feedback the people at SMO provide. 

I created an excel sheet of these location and geocoded them in the Prioritizations ArcPro project located here, G:\ATD\ATD_GIS\DTS_GIS_Workgroup_Support\DTS_Smart_Mobility_Office\Living_Streets_Program\Prioritization_Mapping_JC
