### ISSUE TITLE
Museums: 2000 ft buffer of property

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#14095]
Museums: 2000 ft buffer of property

**Comment by ATD-ZachB** [comment]
G:\ATD\ATD_GIS\DTS_GIS_Workgroup_Support\DTS_Smart_Mobility_Office\Living_Streets_Program\Downloaded_Data|
Save data here

**Comment by Colemonj** [comment]
Website I referenced for finding museum locations,

https://do512.com/museumsinaustin/venues
