### ISSUE TITLE
Movie theaters	Want to connect people to other modes: 1300 ft buffer of property

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#14093]
Movie theaters Want to connect people to other modes: 1300 ft buffer of property

**Comment by ATD-ZachB** [comment]
G:\ATD\ATD_GIS\DTS_GIS_Workgroup_Support\DTS_Smart_Mobility_Office\Living_Streets_Program\Downloaded_Data|
Save data here

**Comment by Colemonj** [comment]
List of local movie theaters:

https://cinematreasures.org/theaters/united-states/texas/austin
