### ISSUE TITLE
DTS Newsletter: 3rd Quarter Issue

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#141]
- Update team table
     - @amenity + @TracyLinder are "Product Manger"
     - @mateoclarke is "Senior Software Developer"
     - @dianamartin is "Solutions Architect"
     - @mstevens-atx @alan-deanda @jaime-mckeown - you good with your official City titles?
 - Farewell Joey & Garry
 - Maybe the "Did you know" could be about Jaimie being the new awesome GIS SPOC

**Comment by alan-deanda** [comment]
my title seems fine.

**Comment by jaime-mckeown** [comment]
My title is fine as well, thank you.

**Comment by dianamartin** [comment]
Suggestion for **"Did you know?**:

_All employees requesting access for a GIS Account or Installation of ArcGIS Desktop must fill this **"GIS Software Installation/Account Request Form"** prior to gaining access._

>Insert **GIS_Software_Account_Req_Form_PREFILLED.pdf**

_Users need to fill out the following fields on the GIS Software Installation/Account Request Form and email: Jaime McKeown (ATD GIS SPOC)_
