### ISSUE TITLE
[BUG] Phantom "Name" field pops up when requesting a "New Project"

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#14102]
**Describe the bug**
When submitting a project request in the DTS Portal, a "Name" field appears at the top of the form if user selects "New Project" from the "What do you need help with?" options

**Screenshots**
![Screenshot 2023-10-03 at 4 03 29 PM](https://github.com/cityofaustin/atd-data-tech/assets/1463708/e4971670-c607-446c-8903-bca83ac8e1b2)

**URL**
https://atd.knack.com/dts#new-service-request/

**Device**
Macbook Pro running OSX 14.0

**Browser**
Chrome

**Comment by amenity** [comment]
@dianamartin I don't think this is urgent, just awkward. And also a regression? 🤔

**Comment by dianamartin** [comment]
@amenity I fixed the display rule on this one

**Comment by amenity** [comment]
Thanks!

**Comment by amenity** [comment]
Confirmed that this is resolved, 🙏🏻 @dianamartin
