### ISSUE TITLE
Update Active Fee Documentation w FY24 Updates (VC)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14113]
### Make sure our active fee documentation reflects all the recent updates we did that rolled out for FY24. 
- Active fee documentation is [here](https://cityofaustin.sharepoint.com/:x:/s/ATDAMANDASupport/ERbtNXhcKIZLpS6camuEV6ABszKZVqbIhpsyYxRI9-lwpw?e=KwiSUJ)

**Comment by TracyLinder** [comment]
@vschandramouli I think this one is straight forward - but let me know if you'd like to discuss. I put this On Deck; do you think you can have the fee documentation updated by Nov 1st?

**Comment by TracyLinder** [comment]
@vschandramouli can I please get an update on this?

**Comment by vschandramouli** [comment]
Items still needing an update in fee document: 

1. Updates to GL Account based on FY 24 Fee schedule
2. Updates to ROW Fee names based on #8687
3. Updates to Lookup table values based on developer findings. 
4.

**Comment by vschandramouli** [comment]
Updated New GL Account, new Fee descriptions and Lookup table values in the fee document on ROW AMANDA Teams channel. 

Document can be found here [https://cityofaustin.sharepoint.com/:x:/r/sites/ATDAMANDASupport/Shared%20Documents/General/Fees/Active%20Fee%20Documentation.xlsx?d=w7835ed16285c4b86a52e9c6a6b8457a0&csf=1&web=1&e=VL6PzY](here)

**Comment by TracyLinder** [comment]
@vschandramouli the active fee document is not in the ROW channel, it's in the ATD AMANDA Support Channel, [here](https://cityofaustin.sharepoint.com/:x:/r/sites/ATDAMANDASupport/Shared%20Documents/General/Fees/Active%20Fee%20Documentation.xlsx?d=w7835ed16285c4b86a52e9c6a6b8457a0&csf=1&web=1&e=OZGY33).
