### ISSUE TITLE
Add `Backplates` and `Backplate Installation` fields to the Signals ODP

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14111]
- Will also need to add `Backplates` field to [Open Data Portal](https://datahub.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-and-Pedestrian-Signals/p53x-x73x) and to [ArcGIS Online](https://austin.maps.arcgis.com/home/item.html?id=e6eb94d1e7cc45c2ac452af6ae6aa534)
   - Update Knack API table
   - Then update ETL

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/14006#issuecomment-1745143367_

**Comment by susannegov** [comment]
The following fields need to be added:
- `Backplate Installed` - `field 4589` type Yes/No
- `Backplate Type` - `field 4590` type multiple choice text
- `Intersection Backplate Status` - `field 4591` type multiple choice text

**Comment by KaroEngstrom** [comment]
📆 meeting F 10/13/23 to do the adds and review the Gitbook instructions for adding fields to existing datasets with active ETLs

**Comment by KaroEngstrom** [comment]
## Tue 10/17/23 

- checking with dev on what is going wrong here

**Comment by KaroEngstrom** [comment]
@ChristinaTremel This seems ready for the AGOL piece mentioned in the description

**Comment by KaroEngstrom** [comment]
Flagging this for backlog 10/25/23 @ChristinaTremel

**Comment by andrewshensky** [comment]
The requested fields have now been added to the feature service in AGOL. Let me know if any additional changes or modifications are needed.
![image](https://github.com/cityofaustin/atd-data-tech/assets/80716478/05658b8b-dea4-4109-86f9-d866c904aa5f)

**Comment by KaroEngstrom** [comment]
Do we need anything else from Apps for this? @ChristinaTremel

**Comment by ChristinaTremel** [comment]
@KaroEngstrom nothing else is needed from apps for this! 🙏🏼 And looking at the AGOL map, it looks like these fields are populating as they should.

Closing this issue!
