### ISSUE TITLE
Maximo Enhancement: Cancel SR if all related work orders are canceled

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#14110]
Cancel SR if all related work orders (Follow up and Related) are canceled.

**Comment by YakshDipa** [comment]
Nick from CTM is looking into it

**Comment by adry-martinez** [comment]
**12-11**

Per CTM - Works 1:1, not multiple WOs

**Comment by dianamartin** [comment]
# 1/24/24
- Run a report to pull "Closed" work orders that are related to at least one service request
- Use Data Quality report - to give us SRs related to multiple WOs.
- Once we've identified the SRs that are still open, circle back with CTM on what was discussed.

**Comment by adry-martinez** [comment]
## February 5, 2024

CTM designed script and is now live on Test.

**Comment by adry-martinez** [comment]
### Feb. 21, 2024

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/a16862a9-9ecc-488b-bf37-800cf716ba02)

Tested script, script was unsuccessful.

**Comment by adry-martinez** [comment]
### May 6, 2024

This will be moved to PROD.
The script applies to multiple SRs to 1 work order.
If stakeholders request for multiple WOs to 1 SR, we will revisit.

**Comment by adry-martinez** [comment]
### May 13, 2024 
It is in PROD. Issue closed.
