### ISSUE TITLE
Use Field Rule to Set Memo vs Back-Chargeable Task Orders 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1411]
@dianamartin would you remind me how we determine if a task order is memo vs back-chargeable? We need to create a field rule that sets this automatically, since we will be continuously adding new task orders from the controller's office integration.

**Comment by dianamartin** [comment]
@johnclary I think what we did initially was we exported the table of task orders from eCapris or Advantage and it had a field for memo/backchargeable and that's how we set it. 
Remind me which page we're going to pull from at the controller's office? This [one] (http://finance.austintexas.gov/web/controller/afs3/acctlookup/taskorderlookup.cfm)

**Comment by johnclary** [comment]
Not needed as we have this info in the source data from the controller's office database
