### ISSUE TITLE
Hospitals and urgent care: 1300 ft buffer of property

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#14123]
We may have this data set somewhere already. Check DM first, if we have this in DM track down the AGOL feature service and provide the URL link to feature service. If only in DM then the feature class name. 

If not use the same method as previous data sets of providing list in excel/csv format that can be geocoded.

**Comment by Colemonj** [comment]
There is a Hospital feature class in DM called, LOCATIONS.hospitals

There is also a feature layer on AGOL that may be more up to date linked below,

https://austin.maps.arcgis.com/home/item.html?id=a450b5a495f041bc904ffddab17933e4

**Comment by Colemonj** [comment]
Linked below is an Excel sheet of urgent care locations in Austin. To acquire these locations I did a google search and compiled a list of my findings. 

[Urgent_Care_Locations.xlsx](https://github.com/cityofaustin/atd-data-tech/files/12883778/Urgent_Care_Locations.xlsx)
