### ISSUE TITLE
Maximo SBO Winter Weather: Job Plans, Tools, Materials Set Up

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#14125]
Winter Exercise Planning : Review need for job plans, tools and materials in Maximo

**Comment by adry-martinez** [comment]
pending data from Dave Anderson

**Comment by adry-martinez** [comment]
Pending to collect feedback from OPM and District Maintenance team this week (11/27 - 12/1)

No information provided prior to the exercise.

**Comment by adry-martinez** [comment]
See [14128](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/gh/cityofaustin/atd-data-tech/14128)
