### ISSUE TITLE
Maximo SBO Winter Weather: Start Center Design

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#14126]
Winter Weather Planning : Start Center Design

**Comment by adry-martinez** [comment]
pending data from Dave Anderson

**Comment by adry-martinez** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjNWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27f5fa5ec04b767e7a7b0bf524208f6d239124bd/image.png)

**Access given to:** 
Hershaw, Reiner
Andersen, David
Ramirez, Baldomero
Mendoza, Eladio
Collier, Michael
Vargas, Rene

**Comment by adry-martinez** [comment]
Pending to collect feedback from OPM and District Maintenance team this week (11/27 - 12/1)

**Comment by adry-martinez** [comment]
See [14128](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/gh/cityofaustin/atd-data-tech/14128)
