### ISSUE TITLE
Split total cost

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1412]
## As a Finance Staff Need Total Cost split by line item - Total Permit Cost/Total Taxes

**Describe the outcome you'd like to see when this feature is implemented.**
For finance reconciliation and auditing need permit cost and taxes as separate fields 

---
## Acceptance criteria

- [ ] On `Permit & Transactions` table we have the fields for split cost
- [ ] `Permit Cost` and `Tax`

**Comment by dianamartin** [comment]
On the `Permit & Transactions` table we have separate fields for `Permit Cost` and `Tax`. These actually belong on the application table. 

![image](https://user-images.githubusercontent.com/21112975/74284309-10225d80-4ce9-11ea-8ae4-ea6b5fe34318.png)

**Comment by dianamartin** [comment]
During demo there weren't requests for modifications on this. Seemed to be accepted by the users.
