### ISSUE TITLE
Remove Non-CR3s from VZDB

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14136]
## Description
@xavierapostol reach out on Teams 10/5/23 letting us know he would like to update the non-CR3s in the VZE and has created a new file to make those updates. Identify and remove all non-CR3 records from the database and inform Xavier so that he can submit the new file.

**Comment by patrickm02L** [comment]
## 10/23
Teams'ed Xavier

> Hi, can you refresh my memory about removing all the Non-CR3s? Do you want us to delete them from the database?

> Yes. Then I will import them using the Upload Non-CR3 tool on the VZE after that is completed

![MicrosoftTeams-image](https://github.com/cityofaustin/atd-data-tech/assets/5566727/ce27da18-bcad-4974-a8a1-22bbe86179b3)

He confirmed that Non-CR3s means the atd_apd_blueform table.

**Comment by patrickm02L** [comment]
## 10/11
In Refinement - Make a backup, do a test run on staging.

**Comment by frankhereford** [comment]
Please see https://austininnovation.slack.com/archives/CM9MK950S/p1698063137656059.

> H/T to @mddilley for suggesting that we do some testing for #[14136](https://github.com/cityofaustin/atd-data-tech/issues/14136) before `truncate atd_apd_blueform` to remove all the non-cr3 crashes from the VZDB. Doing so has surfaced a bug in [the view](https://github.com/cityofaustin/atd-vz-data/blob/master/atd-vzd/views/locations_with_crash_injury_counts.sql) that drives the locations table. I’ll include details about the bug in the thread, but we do have two options here.

>In short, the portion of the query that polls the number of crashes per location from the non-cr3 data returns `null`s, because it’s empty, of course. That `null`, when added to the count from the CR3 table is a number + a `null` which is `null`.

>We need to fix this. This bug makes the list show zeros for the crash/injury counts for locations where there is one type of crash (cr3 / non-cr3) and not the other. This has slipped by unnoticed because it is exceptionally rare for a location of interest to have either no CR3 or no non-CR3 crashes, as having lots of crashes is what makes a location interesting.
So, we can go ahead with the truncating as long as we are comfortable that this bug is suddenly VERY evident on the locations until Xavier fills the data back in, which it sounds like he’s ready to do.

**Comment by frankhereford** [comment]
This table was truncated today at 1:30 while in a teams chat with XA and PM.
