### ISSUE TITLE
Automated reminder of permit expiration

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1413]
## As a RPP Reviewer need an automated reminder for the applicant when permit status is set to expire. Permit expires after one year.

**Describe the outcome you'd like to see when this feature is implemented.**
Email notification reminder to applicant that permit is nearing expiration.

---
## Acceptance criteria

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/91a5d4b4-a9af-4132-b1e3-9cd7ef4c8c16)
- [ ] Customer will see an email
- [ ] Include language to say that this permit will expire in 30 days
- [ ] Includes `Expiration Date`

**Comment by dianamartin** [comment]
@moorerst I think we need to find out at our Sprint demo how early we'd want the user to get notice or if they don't want to email the user bc they plan on notifying in a different way.

**Comment by dianamartin** [comment]
Created fields: 
- `Issued Date`
- `Expiration Date Formula`
-`Expiration Date`
- `30 Day Reminder Formula`
- `30 Day Reminder Date`

Configured task to send email if `Expiration Date` is `today` to send to customer.

**Comment by dianamartin** [comment]
Currently testing to see if it's working

**Comment by dianamartin** [comment]
It worked. Email message needs refinement.

![image](https://user-images.githubusercontent.com/21112975/74284750-0baa7480-4cea-11ea-90c1-e5cd3e78e3bd.png)

**Comment by dianamartin** [comment]
During demo there weren't requests for modifications on this. Seemed to be accepted by the users.

- 30 days seemed like a reasonable time frame.
