### ISSUE TITLE
MDS | Monthly Per-Trip Report

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#1414]
We need to create a report for Shared Mobility's new per-trip micromobility fee structure

Required report fields:

- Provider
- Total Number of Trips
- Number of Trips (filter applied)
- Total Trip Miles
- Average Trip Length
- Average Trip Duration

**Comment by JaceDeloney** [comment]
Example Shared Mobility Monthly Per-Trip Report
https://docs.google.com/spreadsheets/d/1dyLSAXIfIrIcj7e4pKH0w1JUTFgymln_EJBfvVh1VZs/edit?usp=sharing

**Comment by sergiogcx** [comment]
The data is ready in the database, and I have created a couple SQL scripts to output the report in this format. This is actually very easy to do and it can also be done through Hasura, which means we should be able to spin up our own website that can provide these numbers.

I have some questions about the delivery method, I believe we need to work on this as soon as possible to have it ready in the next couple days.

**Comment by sergiogcx** [comment]
The report has been provided, there is a conversation happening on next steps on how to handle zero-length trips, and very-long distance trips.

Closing,
