### ISSUE TITLE
Get ROW permit-review-time data for OPM & Lewis L.

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#14143]
@TracyLinder - Can you help @Charlie-Henry access the permit review time data that we talked about earlier? OPM would like to include it the first TPW Stat presentation in two weeks, so we'll need to provide it for them. 

**References**
- [Slide deck](https://docs.google.com/presentation/d/1xVsLxbG2oou_4KYW8YfZaR9u9pT0hHuabiU2rZmd0dE/edit?usp=sharing) for ROW's review of the data we can capture (meeting on 11/6/23)

**Comment by amenity** [comment]
@TracyLinder's notes  from refinement today: 
- 9 queries & not directly stored
- Will need Tracy’s help with the business logic to construct the queries
- Lewis hasn’t replied to Tracy’s 9/21 email offering to work on that

**Comment by amenity** [comment]
@paigewarner adds: 
- this will help with OPM's Lean review of permitting process & TPW Stat

**Comment by Charlie-Henry** [comment]
We had a discussion with ROW and they were interested in tracking this. I looked into building a query that would join from processes table and get the start/end dates from those processes. I did notice a few permits had multiple Web Application Acceptance processes attached, so we might need to figure out how to use those?

**Comment by TracyLinder** [comment]
**Initial Response (Waiting on ROW to begin review)**
Start = Folder In Date
End = Started date on Web Application Acceptance 

**Average Customer Response Time for initial review** 

1. Date that 'Department Comments' attempt is saved on the Web Application Acceptance Process
2. Date is the 'Accepted' attempt is saved on the Web Application Acceptance Process

End Date = Folder Issued Date

**Total Review Time** from submittal, for the initial permitting
Start = Folder in date
End = Folder Issue Date

**Idle**
- Decided not to track this

**Extension Request & Review**
Start = Smartsheet extension request date
End = Permit Extension (AMANDA process) start or end time.

**Comment by Charlie-Henry** [comment]
@TracyLinder based on what we talked about yesterday, it sounded like we had two options. One where we try to track that customer response time using that "Department Comments" date or one without. What do you think?
![image](https://github.com/cityofaustin/atd-data-tech/assets/30810522/b9643e92-af74-4b69-b4fa-caec7ed97bdb)

**Comment by maccallump** [comment]
Can you update this request?  Has ROW provided input on the query,, resulting data etc.?

**Comment by TracyLinder** [comment]
@Charlie-Henry this is a reminder to myself to tell you that ROW wants DS review time on the dashboard. They'd like to see an average review length and also add the review time for each row if there is an itemized view of the data.

**Comment by TracyLinder** [comment]
### Update & Closing

Charlie created a performance data dashboard for ROW that was accepted by end users on 1/18/24. 
- The dashboard can be viewed [here](https://app.powerbigov.us/links/Mg-BtdxjEb?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=aa36fbd7-14be-43cd-80c6-8c4b4f8a3798).
