### ISSUE TITLE
Test new EZMax Build

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#14148]
Test new EZMax Build

**Comment by ReneVarg25** [comment]
Unable to test EZMaxMobile due to latest build preventing mobile users from using test environment. CTM has been notified and is currently working on issues.

**Comment by ReneVarg25** [comment]
New build released, able to launch into EZMaxMobile, will be testing new build (10/16)

**Comment by ReneVarg25** [comment]
New build released, able to launch into EZMaxMobile, will be testing new build (10/16)

**Comment by ReneVarg25** [comment]
1 pass, 1 fail

**Comment by adry-martinez** [comment]
See https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/gh/cityofaustin/atd-data-tech/13886
