### ISSUE TITLE
Parking Technology Procurement - Weekly work session

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#1415]
### Agenda
Review and modify line items in requirements document as needed. Highlight line items that have been modified
Completed review of line items in Testing/Documentation/Reports, Training and Fees tab
Started review of Permit Management tab
This is currently a revenue based contract. Discussed funding the future contract with 30K annually to be used to pay for future enhancements/upgrades
Action items:
- review funding contract with the Finance team to understand if there are any issues with this
- follow up with Ken Bragdon on the status of PR 2020-01-1317
- Ryan & Joseph to continue review of the Permit Management tab
------
- [ ] Schedule meeting
- [ ] Meet and take notes in agenda doc
- [ ] Create resulting issues

**Comment by moorerst** [comment]
Meeting 2/13/20
Ken Bragdon/ATD Finance communicated that the RFP was submitted to Central Purchasing 2/11. Requested confirmation from Ken on when the final versions need to be completed
Completed line by line review of the Permit Management tab of the requirements spreadsheet
Updated the Category on several line items from Front Facing to Back Office
Added requirements for:
Customer ability to view purchase history
Customer ability to review application status
Need for automated email notifications based on various scenarios

**Comment by johnclary** [comment]
@moorerst are these meetings still happening?

**Comment by moorerst** [comment]
@johnclary we decided to suspend these meetings once the SOW was submitted to ATD Finance (Ken). Joseph and I continue to chat/meet periodically. I will close this issue and open a new issue when there is a need to have recurring meetings again.
