### ISSUE TITLE
Update Living Streets Getting Started Page

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#14152]
Based on the page created in #13895 , update this page with information from the Living Streets Team.

**Comment by patrickm02L** [comment]
## 10/26
DTS met with the Living Streets team and PIO to discuss an alternative approach to their current webpage layout, we proposed an accordion approach to consolidate content, making the call-to-action of applying more clear, and to work through the instructional content on the Getting Started page. Based on the conversation and feedback, we sent them mock-ups of what the COA webpage could look like, and worked with Jonathan to improve the instruction on their content on the Getting Started page.

**Comment by KaroEngstrom** [comment]
Completed final updates for go-live on 10/31/23 per testing notes from Jonathan and Manuela. Putting this in QA as we launch.
