### ISSUE TITLE
VZA App Sprint Review #4 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1417]
2/13/2020

[Deck](https://docs.google.com/presentation/d/1plxqiWqRaVfgEtM0hm51YWYNWKLEQlAokIgSy0yPckA/edit#slide=id.g7c7dc3643d_1_9)

**Comment by amenity** [comment]
@SurbhiBakshi - [here's the deck](https://docs.google.com/presentation/d/1plxqiWqRaVfgEtM0hm51YWYNWKLEQlAokIgSy0yPckA/edit#slide=id.g7c7dc3643d_1_9). Feel free to add or make comments throughout and stick questions at the end.

**Comment by SurbhiBakshi** [comment]
@amenity - should I put my notes here?

**Comment by dianamartin** [comment]
## Diana's Notes

1. Location Data
Have GIS feature class, would be 1:1 
Won't have sector or location drop down like before
Start typing and filter by Sector and 
	Ex. "Henry – St"    

Location Data Model
Would make street segments and intersections that we have
Could edit "Description"
Archive locations, but not edit
Could add "Location" and GIS Staff to create location

School Zones
Link to school and address
Work around the school 
Use the COA Schools – have Pat review it

APD Sectors (independent from 10-1) 
Just updated Charlie, George

How does MMC communicate with VZA 
Emailed and recommended to add things to the schedule
Usually through Jen

Log-ins for MMC Staff
Can get phone numbers for officers
To reassign officers if anything comes up

	2. Assignment Approach
Spreadsheet workflows

We would have Randy to do assignments in the app. Officers could sign themselves up and save Randy time. The current process is time consuming for Randy. 

Frequency of invoicing – every month
Currently every week


	3. Reporting
Reporting in Power BI

Alternative 
Officers to put Citation ID in the VZA App

Timeline
Self sign-up workflow

VZA Training & Demo
Enter them in the system

Pilot
Officer self-assignment

Officer self sign-up, would we want them to have ability to reassign?

MMC Question
Large intersection in flash
Would MMC reassign VZA? No. Call dispatch.

Intersection is dark?
Call dispatch.

Vehicles blocking bike line?
If Urgent, call dispatch. Patrol. 

Observer unsafe behavior?
If Urgent, call dispatch. Patrol. 

VZA officer schedule - see this as an additional resource for MMC

Reassignment is very rare. Jen usually calls dispatch/patrol. 

Mobility related can call VZA officer
Safety related call dispatch

Cancellation of shift: 
Substitute

**Comment by amenity** [comment]
Yes please, @SurbhiBakshi! Thanks, @dianamartin !

**Comment by SurbhiBakshi** [comment]
Adding to Diana's Notes - 
1. Location
  a. MMC viewers should be able to see assignment location so if they do need to call officers, they can 
      look for officers close by. 
   b. APD sectors get updated at the most once a year. 


![Sprint Review 4.jpg](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/ff213505-9b77-4a90-9182-b0836b09ff43)

**Comment by SurbhiBakshi** [comment]
![Sprint Review 4.jpg](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/8cfc6646-d08b-4075-a90a-289e9ed28615)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/08b84a62-ade9-42cf-a29c-5d1886643691)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/95cff191-f9fb-486c-a960-504d98f5c296)
