### ISSUE TITLE
3 iPads and 4 nan0-sims

### ISSUE THREAD

**Issue by scottreedy** [cityofaustin/atd-data-tech#14172]
3 iPad 9th generations ordered via Wireless Shop and 4 sims from Control Center

**Comment by scottreedy** [comment]
4 sims received. These are for Street and Bridge

**Comment by scottreedy** [comment]
Gave to Matt to install in November

**Comment by JBStrangenew** [comment]
Do Not Delete:

3 iPad 9th generations ordered via Wireless Shop and 4 sims from Control Center
