### ISSUE TITLE
Enhance the `vision-zero` orchestration program to use LDM endpoints and credentials when approrpiate

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#14181]
@mddilley observed that `vision-zero` orchestration program can be extended to make it much easier to jump back and forth from working on the LDM to the trunk VZ Suite in his initial review of https://github.com/cityofaustin/atd-vz-data/pull/1303.

I believe these changes will be minor, and likely will include adding a `--ldm` switch to the application which will then toggle over to an alternative RDS endpoint and set of credentials. 

This change may end up being temporary while the LDM is being developed or it may persist as a way to download the staging database, should we find it helpful to have a shared staging DB as a more core part of workflow. We do have a staging DB .. so it does seem like being able to specify your upstream data source is a pretty good fit.

**Comment by frankhereford** [comment]
@patrickm02L 👋 Mike identified this as a helpful enhancement to the `vision-zero` orchestration program we use in our local VZ dev stack while he initially reviewing https://github.com/cityofaustin/atd-vz-data/pull/1303. I think this would save a lot of developer time when working on the LDM to make this enhancement. Would it be possible to fit this in for refinement and assignment soon? Maybe we can touch on it tomorrow in the LDM meeting. Thanks!!

**Comment by frankhereford** [comment]
See https://austininnovation.slack.com/archives/C05F2052S67/p1696971425708809

I have a bash script that provides the functionality as a tide-us-over until we do this more properly. LMK if you need a copy.

**Comment by patrickm02L** [comment]
## 10/11
Frank and Mike have found work arounds, this could be more beneficial for LDM production and VZE production. 

Functionality: check out the LDM branch and you can immediately replicate.
Thought have: LDM_ then in collector branch you could have the env variables, you could edit wherever the underscores are.

We could also give the VZ program a --LDM or --staging
