### ISSUE TITLE
Ability for single sign on (SSO) into the SBO Knack App

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14188]
We would like to implement Single Sign On for the SBO Knack application.

Gitbook: https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzNSSXajDFpzOv2IhIv/knack/single-sign-on

**Comment by dianamartin** [comment]
# 12/7
**Participants:** Reiner, Ryan, Jermaine, Michael Collier, Michael Durham, Andre, Areli, Christina, Diana

## Escalation
Route to Ryan H. first then send to Reiner
- Ryan H. - have ability for Ryan to escalate to Reiner
- Reiner

## Configure emails
- Request “Assigned To”
- Change Assignments
- Approve
- Deny

## Other features
- Display Name
    - Vehicle ID
- Attachments?
    - Equipment
        - Photos? Pre-Trip
- Similar equipment
    - Type

## Feedback
- Have feedback, rating system

**Comment by susannegov** [comment]
- [x] Added COACD provider
- [x] Submitted Service Now ticket `INC0372232 Created`
- [ ] Setup SSO through MS Entra
- [ ] Enable SSO in new knack app
- [ ] Save certs in 1password

**Comment by susannegov** [comment]
Have added SSO and tested by signing in using SSO on my account.

**Comment by susannegov** [comment]
- [x] Added js/css to knack app

Tested on home page: https://atd.knack.com/sbo#home/

Need to add the code to knack repo

**Comment by ChristinaTremel** [comment]
The single sign on is successfully working! @susannegov are we good to close out this issue? I see the note about adding the code to the Knack repo!

**Comment by susannegov** [comment]
@ChristinaTremel Looks like Diana already added the code in the knack SBO repo on github! You may close this issue out.

**Comment by susannegov** [comment]
- [x] Removed `https://` in `Issuer` of SAML SSO field which was giving the SSO error
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/a8aff9c1-63e6-4ef8-928e-1fce9fcdace5)

![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/e2894b8d-bbf1-42fa-824c-35e3365dc4fb)

- [x] Tested sign-in in app and was able to SSO
