### ISSUE TITLE
Give Erick A Data Tracker Access

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#14191]
App: data tracker
role: viewer

Full user details in slack: https://austininnovation.slack.com/archives/C026ZRP1TH8/p1696946540295499

**Comment by KaroEngstrom** [comment]
## T 10/10/23 🎉 

- added user as Viewer 
- notified user via Teams with login instructions

**Comment by Charlie-Henry** [comment]
thank you @KaroEngstrom!!
