### ISSUE TITLE
Update Austin B-Cycle Trips dataset

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#1419]
It looks like the last Checkout Date for this dataset is Nov 30, 2019. As per David Orr, we get their report by the 10th of each month, so it looks like Dec, Jan are missing. Mary Vo wanted to know when the dataset will be updated.

**Comment by SurbhiBakshi** [comment]
@johnclary - wrote to David to see if we have received data through May.

**Comment by JaceDeloney** [comment]
@johnclary Let's chat about this to see when we can fit this work into your schedule.
