### ISSUE TITLE
TDS AMANDA Data Needed (SS) (Done)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14196]
### TDS Needs raw performance data by Friday 10/13/23

_The query from #10949 Case Load Report could probably be used/updated for this data request._

Date range = 10/1/21 to current date
Output: Raw CSV

Start date = process To-Start date

**Processes to include in query:**
-- ATD Engineering Review
-- ATD SIF Review
-- CC ATD Review

**Data Columns:**

- FOLDERTYPE
- FOLDERRSN
- REFERENCEFILE
- FOLDERNAME 
- REVIEWER 
- PROCESSNAME 
- Start Date
- DUEDATE
- End date

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder here is the data in CSV file.
Query:
SELECT f.foldertype, f.folderrsn, f.referencefile,f.foldername, vu.username Reviewer,
vp.PROCESSDESC ProcessName, fp.scheduleEndDate DueDate, fp.startdate, fp.enddate EndDate
FROM folder f 
JOIN folderprocess fp ON fp.folderrsn = f.folderrsn AND fp.processcode IN (51132,51834,84102) 
AND fp.enddate IS NULL
JOIN validprocess vp ON vp.processcode = fp.processcode 
JOIN validuser vu ON vu.userid = fp.assigneduser
WHERE f.foldertype IN ('C8','SP','ZC','PR','CC') 
AND TRUNC(fp.scheduleEndDate) >= TO_DATE('10-01-2021','MM-DD-YYYY') AND TRUNC(fp.scheduleEndDate) <= TRUNC(SYSDATE)
ORDER BY vu.username,  f.foldertype, vp.processdesc;

DATA till Date(10/10/2023):
[14196 - TDS AMANDA Data from 10-1-2023.csv](https://github.com/cityofaustin/atd-data-tech/files/12861526/14196.-.TDS.AMANDA.Data.from.10-1-2023.csv)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder Here is the updated query and data file dated as on today:
### **Query**
SELECT f.foldertype, f.folderrsn, f.referencefile,f.foldername, vu.username Reviewer,
vp.PROCESSDESC ProcessName, fp.scheduleEndDate DueDate, fp.startdate, fp.enddate EndDate
FROM folder f
JOIN folderprocess fp ON fp.folderrsn = f.folderrsn AND fp.processcode IN (51132,51834,84102)
JOIN validprocess vp ON vp.processcode = fp.processcode
JOIN validuser vu ON vu.userid = fp.assigneduser
WHERE f.foldertype IN ('C8','SP','ZC','PR','CC')
AND TRUNC(fp.startdate) >= TO_DATE('10-01-2021','MM-DD-YYYY') AND TRUNC(fp.startdate) <= TRUNC(SYSDATE)
ORDER BY vu.username, f.foldertype, vp.processdesc;

### **DATA:**
[14196 - TDS AMANDA Data as on 10-11-2023.csv](https://github.com/cityofaustin/atd-data-tech/files/12874304/14196.-.TDS.AMANDA.Data.as.on.10-11-2023.csv)

**Comment by TracyLinder** [comment]
Hi @SubhaShroff the data looks great. After reviewing the data I think it would help to know the day the process was assigned to the reviewer, but I'm not sure which field that would be. Which field tells us the day the review showed up on the user's task list - so we can tell how long the reviewer had been given to perform the task.

**Comment by SubhaShroff** [comment]
@TracyLinder  I just tested it on a SP, assigned this process to myself with just leaving those TO START, TO END dates as is. And again tried to with the default assigned user (AW Benchmarking). It adds TO START date the moment the process is added, usually, as I have observed. The moment its assigned to the user, its showing up on task list. So, I can say its TO START date field tells us the day it gets on user's task list.
![image](https://github.com/cityofaustin/atd-data-tech/assets/51680715/1cf58fac-16da-480b-9c14-e13a6c66c4e0)

**Comment by SubhaShroff** [comment]
> @Nadin-Nader @TracyLinder Here is the updated query and data file dated as on today. Please review:
> 
> ### **Query**
> SELECT f.foldertype, f.folderrsn, f.referencefile,f.foldername, vu.username Reviewer, vp.PROCESSDESC ProcessName, fp.scheduledate ToStart_Date, fp.scheduleEndDate DueDate, fp.startdate Started_Date, fp.enddate Ended_Date FROM folder f JOIN folderprocess fp ON fp.folderrsn = f.folderrsn AND fp.processcode IN (51132,51834,84102) JOIN validprocess vp ON vp.processcode = fp.processcode JOIN validuser vu ON vu.userid = fp.assigneduser WHERE f.foldertype IN ('C8','SP','ZC','PR','CC') AND TRUNC(fp.startdate) >= TO_DATE('10-01-2021','MM-DD-YYYY') AND TRUNC(fp.startdate) <= TRUNC(SYSDATE) ORDER BY vu.username, f.foldertype, vp.processdesc;
> 
> ### **DATA:**
> [14196 - TDS AMANDA Data as on 10-11-2023.xls](https://github.com/cityofaustin/atd-data-tech/files/12874868/14196.-.TDS.AMANDA.Data.as.on.10-11-2023.xls)

@TracyLinder  @Nadin-Nader  Updated the query to add TO START date as well.

**Comment by TracyLinder** [comment]
The data looks great. I sent it to the customer Matiur and will leave this open a few days in case he requests edits.

**Comment by TracyLinder** [comment]
Matuir likes the data - we'll open a new ticket if something else is requested. Thanks Sree!

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader 
[TDS Amanda Data as on  Jan 1st 2024.xlsx](https://github.com/cityofaustin/atd-data-tech/files/13879920/TDS.Amanda.Data.as.on.Jan.1st.2024.xlsx)
Thanks.

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader  After confirming with Tracy I am putting the updated query here. The change is the data is fetched based on TO - START date of process.

SELECT f.foldertype, f.folderrsn, f.referencefile,f.foldername, vu.username Reviewer, vp.PROCESSDESC ProcessName, fp.scheduledate ToStart_Date,
fp.scheduleEndDate DueDate, fp.startdate Started_Date, fp.enddate Ended_Date 
FROM folder f 
JOIN folderprocess fp ON fp.folderrsn = f.folderrsn AND fp.processcode IN (51132,51834,84102) 
JOIN validprocess vp ON vp.processcode = fp.processcode 
JOIN validuser vu ON vu.userid = fp.assigneduser 
WHERE f.foldertype IN ('C8','SP','ZC','PR','CC') 
AND TRUNC(fp.scheduledate) >= TO_DATE('10-01-2021','MM-DD-YYYY') AND TRUNC(fp.scheduledate) <= TRUNC(SYSDATE)  
ORDER BY vu.username, f.foldertype, vp.processdesc; 
[TDS Performance Data - 1-26-2024.xlsx](https://github.com/cityofaustin/atd-data-tech/files/14068547/TDS.Performance.Data.-.1-26-2024.xlsx)
