### ISSUE TITLE
Update VZA shifts 10/09/23-12/31/23

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14192]
## Description
Add the next 12-weeks of assignments by copying the previous 12-weeks of assignments.

## Notes
- documentation: https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzNSSXajDFpzOv2IhIv/vision-zero-in-action/batch-copy-process-for-vza-assignments

**Comment by patrickm02L** [comment]
looks great! Good to close

**Comment by ChrispinP** [comment]
closing as complete
