### ISSUE TITLE
Add Financial/Non-Financial field to SMD Materials object

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14200]
## Improved inventory tracking
- For improved tracking of inventory, SMD would like to add a field to track the Financial/Non-Financial materials. 
- We would then want to filter `Cycle Counts` page for materials that is financial.

**Comment by dianamartin** [comment]
# 10/10
@ChristinaTremel 
On the backend of SMD, the field "Inventory Tracking" already exists 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/1196cdb0-d6d0-4212-bcdd-d098cbca43ea)

**Comment by dianamartin** [comment]
# 11/2
Is this a DUP of #14321 ?

**Comment by ChristinaTremel** [comment]
Closing because this is dup.
