### ISSUE TITLE
Prototype Sesh for OCE Inventory tracking system

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14205]
### Internal DTS prototype work session. 10/10/23
_Diana, Tracy_

- Prototype a solution for #12553

**Comment by TracyLinder** [comment]
### Notes

- D was going to prototype something yesterday but decided against it 
- T asked to D to onboard me to the ask/need
- Where would we build this? -- We'd have to build a new KNACK app for this group. They seem to be a good candidate for their own KNACK app based on Diana's review of their current services that could benefit from KNACK options.

**Comment by dianamartin** [comment]
# Build Notes
- [x] Create new application "OCE | Office of City Engineering"
- [ ] Home
- [ ] Menu - "Mixes"
- [ ] "Producer" page
- [ ] "Pre-Approved Mixes" table (expiration dates)
  - ## Field Headings
  - Producer
  - Class
  - Mix ID Number
  - Expiration Date
  - Status: Expired, Active
  - Comments
  - Cement Type
  - Fly Ash Type
  - Editable - Mixed table
  
## Other Issues
- [1] Read Only - Mixes table
  - Need to reference this page: 
    - SBO staff
    - Producers (external)
    - TPW Staff 
    - Q: Any of this need to be hidden from the public?
- [1-2] Renewal task - notification __ days before expiration, sends an email to OCE staff
  - Q: how many days do we need to set notification date? 30, 60, 90 days?
- [2] Renewal steps
  - Q: do producers need accounts?
  - Q: do we anticipate a produce submitted more than one mix for review?
  - Q; would they be renewing each mix individually or a batch? (we notice it expires on the same day)

## Future Enhancements
- Ability for Producer to submit mixes for approvals
