### ISSUE TITLE
Meeting OCE Inventory Prototype Review 11/28/23

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14207]
### We will demo the prototype, gather feedback, and ask refining questions. 
- https://atd.knack.com/oce#home/

**Comment by TracyLinder** [comment]
### Questions from Prototype Session (#14205)

- [1] Read Only - Mixes table
  - Need to reference this page: 
    - SBO staff
    - Producers (external)
    - TPW Staff 
    - Q: Any of this need to be hidden from the public?
- [1-2] Renewal task - notification __ days before expiration, sends an email to OCE staff
  - Q: how many days do we need to set notification date? 30, 60, 90 days?
- [2] Renewal steps
  - Q: do producers need accounts?
  - Q: do we anticipate a produce submitted more than one mix for review?
  - Q; would they be renewing each mix individually or a batch? (we notice it expires on the same day)

**Comment by TracyLinder** [comment]
### Notes from DTS Prototype Review on 10/23/23 (#14206)

### Notes from Internal Prototype Overview 10/23/23
_Diana, Suzanne, Tracy_

**To-Do**
- [ ] Add SSO
- [ ] Add new banner
- [ ] 


**Producers Page**
Q: Inline editing or form for each? 
Q: Does Plant and Plant Location belong with the Producers table, or with the Approved Mixes table? 
Q: Do they want contact info? 


**Approved Mixes - Admin**
OCE had a lot of comment fields, so Diana did the best she could based on how they're using them right now. 
Should we add a field for Mix type (mix, flex base, HMAC)

**Approved Mixes - Public**
- No sign-in required to view this data 
- Do users need to be able to filter themselves?
- Does the public need to be able to see the mix attachment? 

**Auto Expiration Alert**
- Discuss when, content, to whom
- 

**Miro Workflow**
- Try to capture the workflow steps 
- How are renewals managed? 



**Sharepoint**
- What else are they using SharePoint for mixes that we can/should move to KNACK?
- How to manage the PDFs? 
- Who creates and maintains the PDFs? 
- Who needs to have access to the PDFs? 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFZnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10c212af43bf7e06d5ce53b39cb1a80e7e5f891d/image.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEpoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--736593e4cbd9814f79e52f5047acd7599ba14927/image.png)

**Comment by dianamartin** [comment]
# 11/28
Diana's Meeting Notes

**Comment by TracyLinder** [comment]
## Tracy's Notes

**Comment by TracyLinder** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/339bf497-6c37-4ae6-adf0-30dc7f117f0d)

**Comment by TracyLinder** [comment]
I'm closing this one.
