### ISSUE TITLE
Sprint Review #1

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1420]
_Scheduled for 2/20/20_

Agenda: 
- Review [Product Brief](https://docs.google.com/document/d/1wmZQabKNgkrBgiMcxRQbp2NstqWeJcwBRd00-JcuaRg/edit#) with stakeholders
- Diana demo
- Discussion

@moorerst [Here is a presentation](https://docs.google.com/presentation/d/1tHKTfUgQ-uAXdRBkEdXqR7ryBo_LTU86IzQxo1gJoeA/edit#slide=id.g1ec5e23c79_2_9) you can use as a starting point for the meeting.

**Comment by moorerst** [comment]
Sprint Review #1 Task list
@dianamartin these are the task I captured from the Sprint Reivew meeting
- [ ] There should be a 1 to 1 relationship between vehicle and permit, each permit should be 
       associated to a vehicle 
- [ ] Update the slash page to reflect the total permit cost not rounded down
- [ ] FAQ for temporary plates indicating it needs to be updated when permanent plate is issued
- [ ] Include footer on the invoice page indicating payment options
- [ ] Include slash page with Day Pass information
- [ ] Day Pass serial #’s need to be captured
- [ ] Customer report - include vehicle information
- [ ] Access to test environment for Finance team to review reports (Dan, Peggy)
- [ ] Field Application - Received Type (Online - In Person) not needed 
- [ ] Note on splash page with link to Spanish form 
- [ ] Make delete attachments/documents available for RPP Staff only after application has been in 
       Complete Status or Ineligible Status for x days
- [ ] Review Attachment storage/security settings in Knack
- [ ] Link back to purchase Day Passes or combine purchase of both passes

**Comment by moorerst** [comment]
Sprint Review meeting notes 2/20/2020
Attendees: Stephanie, Diana, John, Surbhi, Ryan, Steve, Dan
Spanish version in later release
Renewal process in later release
Coordinate end user training for later Sprint
Follow up with Ryan on the following:
- [ ] Need to determine if the quarterly management reports need to be available in excel format
- [ ] Provide number of property manager applications
- [ ] Provide suggestions of end users who may want to participate in end user testing

**Comment by SurbhiBakshi** [comment]
@dianamartin think @moorerst captured most of my notes in her notes above. 
Adding a bit more - 
- [ ] Think the modal for editing RPP zone was still 'edit rpp_zone'. You might have already changed this.
- [ ] enable ADFS
- [ ] in case applicant is a property manager, documentation needed is Proof of Lease and not Proof of Residence.
- [ ] People get confused if they need a day pass or construction pass, need education and awareness. Some language in FAQ? Follow up with Ryan.

**Comment by amenity** [comment]
These are accounted for in #1498 and #1500.
