### ISSUE TITLE
Create new `Austin Traffic Waze Signal Status` ODP dataset to push to Waze Datafeed

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14201]
### Objective 
- Help AMD push signal statuses to Waze, so citizens know when signals are on flash. 

### Participants
Christina, Diana, Frank, Chia, Lance, Samir, Allyson

### Meeting Notes
- Dataset on the ODP was sent to Waze to update signal statuses in the Waze app
- Shared a parter feed for the `Austin Traffic Signal Status` feed on the Waze partner hub site. 
   - Wanting Waze users to be able to see hazard signals (when signals are in flash)
- Overall, we might need to create a different open data portal dataset specifically for Waze use only. 
   - Would be easy lift on the dev side by looking at the [existing code](https://github.com/cityofaustin/atd-kits/blob/production/atd-kits/signal_status_publisher.py). 
      - The JSON url could be crafted with only pulling in the statuses we care about: `Unscheduled Flash` (operation code 2) 
- [Waze Requirements](https://developers.google.com/waze/data-feed/cifs-specification#incident-subtypes) 
- Refresh Rate: every 5 minutes

## Waze requirements that were missing 
- Update the polyline coordinates (lat/lon for the closure path)
   - We notice that you provided a single pair of coordinates for your polyline, we suggest to at least have 2 sets of unique coordinates. Though we still don't know the type and nature of the events you currently share, please know that in case the feed includes closures, there is a high probability that the closures will fail because the feed includes no direction and an ideal polyline. We highly recommend sharing polylines which include pairs of coordinates that resemble the geometry of the road.
      - Ex: <polyline>51.510090 -0.006902 51.509142 -0.006564 51.506291 -0.003640 51.503796 0.001051 51.499218 0.001687 51.497365 0.002020</polyline>
      - Decision: Split the Location (lat/long) field into 2 separate fields for latitude and longitude 

- Description for each alert.
   - May we ask the exact description for every alert? We cannot identify the exact description. 
   - This description should be less than 40 characters. A description that is more than 40 characters will be accepted, but may not display properly in the Waze app.
      - Ex: <description>I-95 All NB lanes closed btwn Exits 184 and 186.</description>
      - Requested Description: Traffic Signal Fault at [Primary Street] and [Cross Street]

- Type for the alerts.
   - The type will determine the way your event will be consumed by the Waze app. ROAD_CLOSED will result in a full closure.
   - All other types will be shown in the Waze map and will trigger a popup notification for nearby Wazers, but will have no direct impact on routing.
      - Add Type field: HAZARD
      - Add Subtype field: HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT

- Subtype and direction.
   - These fields are necessary even though it is a requested field only, The same with the description field, these are also going to be in the notification of the alerts in the Waze map. We suggest to also include these fields in your partner data feed.
      - Ex: <Subtype>ROAD_CLOSED_HAZARD</Subtype> & <direction>BOTH_DIRECTIONS</direction>
      - Add Subtype field: HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT
      - Direction: leave out direction for the time being, but if Waze needs it it would be both.

### Timeline
- Jim and team would love to point to this as being accomplished in Waze in the next couple months.

**Comment by chiaberry** [comment]
here is the script that handles kits to ODP https://github.com/cityofaustin/atd-kits/blob/production/atd-kits/signal_status_publisher.py

**Comment by ChristinaTremel** [comment]
## Action Items: 
- Create new ODP dataset using [this existing code](https://github.com/cityofaustin/atd-kits/blob/production/atd-kits/signal_status_publisher.py) (same code used for [Austin Traffic Signal Status ODP dataset](https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html))
   - Filter dataset and only pull in  `Operation Code` = 2 (Unscheduled Flash)
   
- Update code to provide additional fields needed by Waze:
   - Add `Type` field: HAZARD
   - Add `Subtype` field: HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT
   - Add `Latitude` and `Longitude` separated fields. 
      - Need to split the `Location` field into 2 separate fields for latitude and longitude
   - Add `Description` field: Traffic Signal Fault at [Primary Street] and [Cross Street]

- More ODP Dataset Details:
   - ODP dataset (open to the public so Waze can pull the data)
   - Refresh Rate: every 5 minutes

**Comment by ChristinaTremel** [comment]
## Dev & Product Sync
- @johnclary can prep a sample to send to Waze and confirm that the format works. 
- Could possibly try to make these changes and use the existing dataset.

**Comment by johnclary** [comment]
@ChristinaTremel @chiaberry—here is a query that gets us pretty close. We need to add another condition to it so that it only includes the oepration_state = 2 records. I have exclude that only for demo purposes:

```
https://data.austintexas.gov/resource/5zpr-dehc.json?$query=select primary_st, cross_st, 'HAZARD' as type, 'HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT' as subtype, 'Traffic Signal Fault at ' || primary_st || ' and ' || cross_st as description, location.latitude as latitude, location.longitude as longitude
```

The one issue is that it returns the latitude and longitude as strings. I don't _think_ there's a workaround for that so we probably will need to just add those separate columns to the existing dataset.


Christina here is the sample payload you/MMC can send to Waze an example. 

```json
[
  {
    "type": "HAZARD",
    "subtype": "HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT",
    "description": "Traffic Signal Fault at MOPAC EXPY SVRD and BEE CAVE RD",
    "latitude": 30.265333,
    "longitude": -97.782313
  }
]
```

**Comment by Charlie-Henry** [comment]
I put John's query as a dataset "view" so now we can see it in the ODP. Also added the polyline field they wanted (although signals are a point asset so idk why they want polylines?). I've have not included the signals on flash filter yet because it would likely return nothing unless we actually had a signal on flash at the time.

https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-on-Flash/hejg-whp6/about_data

json endpoint:
https://data.austintexas.gov/resource/hejg-whp6.json?$query=SELECT%20primary_st%2C%20cross_st%2C%20type%2C%20subtype%2C%20description%2C%20direction%2C%20polyline

**Comment by ChristinaTremel** [comment]
Lance responded on 12/14:
> Yay! I'll share this with them.

Closing this issue.

**Comment by Charlie-Henry** [comment]
Was just thinking, should we include dark signals in the waze feed as well?
