### ISSUE TITLE
Create a Batch to remind contractors of upcoming license expiry (SS) (11/15 Sprint) (SR) - (Approved on PROD)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#14213]
Related to #4070, #10849, #10850

**Acceptance Criteria**
- System should run a daily batch that checks to find LC folders that are 30 days away from expiry, and send an email to 'Right-Of-Way Contractor' of those LC folders  
- Only one email should be sent to each contractor
- Text for the email is below

Subject: ROW Permit Expiration Notice
Dear [Right-Of-Way Contractor People record First Name and Last Name],

This email is to advise you that your Right of Way Contractor License will expire on [LC folder Expiry date].

All Driveway/Sidewalk and Excavation permits associated with your Right of Way Contractor License will expire on [LC folder Expiry date] if the license is not renewed. A list of those permits is provided below. To renew your Right of Way Contractor License, look for the "How is a Right of Way Contractor License renewed?" Section at this URL - https://austintexas.gov/page/right-way-contractors

Your DS/EX Permits That Will Expire:

- [Folder Number of DS or EX folder, for example, 2022-012345 DS]

**Comment by vschandramouli** [comment]
AC is updated. Moving to Backlog.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in Progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Reverted and recommitted DEV DP of #14213. Kindly create task id for the same.

Commit ID: 59214faf7e8a1be537c2ccad3691c6aad37c5fa9

![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/69265a76-a470-43f0-8841-3c74eb5d6036)

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Created Dev Deployment request - SCTASK0377836

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - 84000 lookup table changes updated in Package and committed with order 2. DEV DP Submitted. 

Commit ID: 8e50f3d8e607e5089e8f7861d14fb4da80142ab0

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Created Dev deployment request - SCTASK0378776

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Changes deployed to Dev , Please verify

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Created Dev deployment request , SCTASK0380712

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP of #14213 submitted. Kindly create task id for the same.

Commit ID: 6af8d549e6eee9c787b0be594321baceadaf1464

![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/be02f724-e9dc-4c41-8e67-b35df3a6ba93)

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Created Dev deployment request, SCTASK0381157

**Comment by Nadin-Nader** [comment]
Waiting on CTM To deploy

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan apparently this has been deployed to DEV. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV; looks good, if you can confirm the email format in below screen shot; this can be promoted to TEST.

![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/8c9a6df7-bfe4-48d4-ab84-6d59dd537032)

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan you're good to promote

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP of #14213 submitted; as per new AC Update, made changes to pull 30 calendar days instead of 9 days. Kindly approve and create task id for the same.

Commit ID: 088194365c23cf8b1a7b6072e7f3afaca527c578

![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/a2119659-2707-4077-9968-2128fcb5dad2)

**Comment by Sreelatha-BlazeKannan** [comment]
Lakshmi Priya created Service Now task id for me. Request Number - SCTASK0387280

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - TEST DP submitted. Tested the bach job as per updated AC and received emails accordingly. Kindly approve and create task id for the same.

Commit ID & Order – Please promote as per the below order

Order 1 – 59214faf7e8a1be537c2ccad3691c6aad37c5fa9
Order 2 – 8e50f3d8e607e5089e8f7861d14fb4da80142ab0
Order 3 – 6af8d549e6eee9c787b0be594321baceadaf1464
Order 4 – 088194365c23cf8b1a7b6072e7f3afaca527c578

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Email after updating the AC.

![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/d5da5ee9-ca16-44dc-9135-342638dd988d)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent tot the DevOps CM Team to be deployed to TEST under **SCTASK0388539**

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please add an updated comment.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please setup test cases in TEST to prepare for UAT.

**Comment by Sreelatha-BlazeKannan** [comment]
> @Sreelatha-BlazeKannan please setup test cases in TEST to prepare for UAT.

Run - Query to get the FolderRSN/PeopleRSN for whom we are sending the Notification to

SELECT DISTINCT fp.peoplersn, f.folderrsn LC_rsn
	 FROM folder f
	 JOIN FOLDERPEOPLE fp ON f.folderrsn = fp.folderrsn AND fp.PEOPLECODE = 50065--Right-Of-Way Contractor
	 WHERE f.foldertype = 'LC' AND f.statuscode = 50010 
	    AND CAST(f.expirydate AS varchar(10)) = CAST(sysdate + 30 AS varchar(10))

2. Take the peoplersn and update the email address as Tester email address
3. Run Query below to get the DS/EX expire details by giving the above peoplersn
4.  SELECT DISTINCT dsf.folderrsn DSorEX_rsn
	 FROM folder dsf
     JOIN folderpeople dsp ON dsf.folderrsn = dsp.folderrsn AND dsp.PEOPLECODE = 50065--Right-Of-Way Contractor 
	 WHERE  dsf.statuscode = 50010 -- Active  
       AND dsf.foldertype IN ('EX','DS') 
	   AND dsp.peoplersn = XXXXXXX

5. From the above results we will know how many records the email has to show when we receive it; if it matches then it is accurate. 
6. Email format verification.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DRAFT PROD Commit of #14213 email sent. When we get UAT Approval in TEST this can be submitted and create a Task id accordingly. And promote changes as per the below order.

Commit ID – 
1.	59214faf7e8a1be537c2ccad3691c6aad37c5fa9
2.	8e50f3d8e607e5089e8f7861d14fb4da80142ab0
3.	8ead78b5ca1b54730bf4df255f84b492902c4f42
4.	6af8d549e6eee9c787b0be594321baceadaf1464
5.	088194365c23cf8b1a7b6072e7f3afaca527c578

**Comment by KyleErich** [comment]
Hi all. I UAT'd this and my only piece of feedback is that the URL doesn't seem to be clickable -- it appears as a blue link, as one would expect, and the cursor identifies it as a link, but when it gets clicked nothing happens.

If it helps, we could embed the URL as a hyperlink within some of the wording of the email body. I'd like to propose the following for the last sentence:

To renew your Right of Way Contractor License, please see the "How is a Right of Way Contractor License renewed?" section at [this linked webpage](https://www.austintexas.gov/page/right-way-contractors).

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0401163**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is tested in DEV and TEST deployment request was sent - SCTASK0401919. 
Thanks.

**Comment by SubhaShroff** [comment]
Thank you Kyle.
@Nadin-Nader  Please create a PROD deployment request. Deployment plan is attached. Thank you.
[14213-6bebe6a621a0828839cb64935fabe6968bc32606- PROD Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/14637527/14213-6bebe6a621a0828839cb64935fabe6968bc32606-.PROD.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0404843**

**Comment by SubhaShroff** [comment]
> @Nadin-Nader , @TracyLinder - DRAFT PROD Commit of #14213 email sent. When we get UAT Approval in TEST this can be submitted and create a Task id accordingly. And promote changes as per the below order.
> 
> Commit ID –
> 
> 1. 59214faf7e8a1be537c2ccad3691c6aad37c5fa9
> 2. 8e50f3d8e607e5089e8f7861d14fb4da80142ab0
> 3. 8ead78b5ca1b54730bf4df255f84b492902c4f42
> 4. 6af8d549e6eee9c787b0be594321baceadaf1464
> 5. 088194365c23cf8b1a7b6072e7f3afaca527c578



> @Nadin-Nader , @TracyLinder - DRAFT PROD Commit of #14213 email sent. When we get UAT Approval in TEST this can be submitted and create a Task id accordingly. And promote changes as per the below order.
> 
> Commit ID –
> 
> 1. 59214faf7e8a1be537c2ccad3691c6aad37c5fa9
> 2. 8e50f3d8e607e5089e8f7861d14fb4da80142ab0
> 3. 8ead78b5ca1b54730bf4df255f84b492902c4f42
> 4. 6af8d549e6eee9c787b0be594321baceadaf1464
> 5. 088194365c23cf8b1a7b6072e7f3afaca527c578

@Nadin-Nader are these all sent to PROD, already?

**Comment by Nadin-Nader** [comment]
@SubhaShroff  this has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0405496*

**Comment by Nadin-Nader** [comment]
@SubhaShroff The batch creation request has been sent to the CTM Team to create on PROD under **SCTASK0407057**

**Comment by SubhaShroff** [comment]
@Nadin-Nader The batch job is deployed in PROD. Checked it in DB and it looks good. Will wait till tomorrow to verify if it autotriggers, successfully, before marking it ready for UAT. Thank you.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The batch job auto-triggered and completed without any errors. This is ready for UAT on PROD.
Thanks.

**Comment by KyleErich** [comment]
@SubhaShroff @Nadin-Nader UAT approved on PROD. Thank you.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Kyle approved this ticket on PROD. Its ready to close. 
Thank you.

**Comment by Nadin-Nader** [comment]
Closing Per Kyle's approval
