### ISSUE TITLE
Expire DS and EX folder based on Insurance Dates

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#14214]
Related to #10849 , #10850 , #4070 , #14213

It was suggested that the insurance dates can be considered to expire DS and EX folders.

**Comment by vschandramouli** [comment]
Questions:

- Where do we check for Insurance dates? Folder info or People Info?
- What folder statuses do the folders get changed to if Insurance is expired? Is LC folder involved in status change?
- Any email to be sent on expiry?
- How do the folders get re-instated?
- Any reminder emails to be sent a few days before expiry?

**Comment by vschandramouli** [comment]
Questions:

- Where do we check for Insurance dates? Folder info or People Info?
- What folder statuses do the folders get changed to if Insurance is expired? Is LC folder involved in status change?
- Any email to be sent on expiry?
- How do the folders get re-instated?
- Any reminder emails to be sent a few days before expiry?

**Comment by TracyLinder** [comment]
### Outcome

We decided to meet this need another way, see #14545
