### ISSUE TITLE
Maximo, Report Request: Alley-related 311 requests

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#14216]
OCE would like to show PWD needs better alley  management – and funding – to meet the increasing number of alley calls .
We need  1 chart ( not  6 charts  ) that shows the number of alley calls per month as a line graph since MAXIMO started (  Dec 2015?) …
Like this : (except extended to Oct 1 2023 ) 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmttQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--664924ae60373a66dc3819ec8b645d26061708ff/image.png)

OCE wants to show that alleys calls maybe  related to monthly rainfall ( more potholes and tree issues ) and/or storm events …but the overall number is trending upward.

And the number is not going down as alleys  traffic is increasing as back yards are  turned into apartments and as the number of AAR collection routes increase ..

**Comment by ReneVarg25** [comment]
Cutoff date for responding to WOs?
- Last year was 650, many were not their work but were sent anyways
- Most were not needing to be sent, had a meeting to limit ones being sent
- Many are now 5CLOSED since time passed
- Do they want to keep 19s? No, there's not point in keeping them if they're that old
- Does not delete, but remove them from bucket
- Bucket is combination of everything, not based on fiscal year
- Did they want to keep full calendar 2023? Yes, maybe a little bit older
	- Will remove 2019-2022 from the bucket, will cut bucket by half
	- Will leave 2023, and notify when done
- What does this do? Does it make it easier to update?
	- Since they are being removed, they will not been in bucket, but can still be accessed

- Message from Art regarding report from Dipa
	- Requesting report from Ron for reference
         	- Yes, but how quick
	- Sent Maximo WOs with anything Alley in it, from beginning of Maximo
	- Options in Maximo do not have layout that Ron wants or displays information needed
	- Need to ask CTM will assist with reporting
	- Requesting line chart to show increase in calls and to show # of dupes
	- Want to get set up by Feb for budget discussions

**Comment by maccallump** [comment]
@ReneVarg25 is there a Maximo query that produces this information?  Or do we need to build one?

**Comment by ReneVarg25** [comment]
> @ReneVarg25 is there a Maximo query that produces this information? Or do we need to build one?

This report is existing, we would be enhancing it to meet the request. We also clarified the notes since a large part of it was pertaining to a different issue.

**Comment by adry-martinez** [comment]
## Feb. 11, 2024

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/1c40ad49-9549-4a84-86f8-74e3e0858dbb)

Current SBO Alley Response Report provides this data. 
Working with CTM to add all incoming Alley requests.

**Comment by adry-martinez** [comment]
### Feb. 12, 2024
Met with Ron K., reviewed the Alley Response Report, states that this satisfies his request. This request has been rescinded and CTM has been notified.
