### ISSUE TITLE
Bug: SCP Split Fees Fix

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1425]
**Status as of May 26: ATD testing found no issues to report. Stakeholders have been updated. Next DSD & Finance need to test their portion of this fix.**

### Overview:
- Dec 2018: SCP Phase 2 went live
    **- Included in this release was an update to SCP fees, instructing the system to calculate the % of fee breakdown to each FDU**
- March 2019: DSD reported a bug with their FDU report caused by the update to SCP fees 
- Spring 2019: Controller's Office reported a massive backlog of AMANDA fees collected that were unable to be deposited due to the SCP fee bug(s). 
    **- Basically the way the SCP fees were configured makes it impossible for the related FDU code to populate on any of the reports that finance staff & other finance systems depend on.** 
- 6/13/19: All SCP stakeholder departments met @ Barton Oaks to discuss this issue & solutions
    - An interim solution was implemented; DSD agreed to manually populate FDU codes for the controller's office. This will allow the money to be deposited while the fee fixes were being developed. 
- Summer 2019: CTM engaged Unisys to perform the development needed 
- 8/5/19 - George w/ CTM promoted Unisys' dev to TEST
- Late Aug 2019 - DSD & ATD provided UAT feedback
- 11/8/19 - Tracy L, Deanna D, & Mark C synced on the project & identified next steps
    - CTM committed to performing the necessary development to get this to PROD
- Dec 2019 - George performed development & promoted to TEST
- Pending UAT from ATD & DSD

**Comment by TracyLinder** [comment]
April Sellars w/ TARA should be able to perform UAT for these fees.

**Comment by SurbhiBakshi** [comment]
Scheduled a UAT session with April on Monday Feb 24th.

**Comment by amenity** [comment]
@SurbhiBakshi - looks like this might belong in #1198. Do you agree?

**Comment by SurbhiBakshi** [comment]
@amenity I am not sure, think this was an issue that got caught after Phase 2 was implemented.  Think #1198 is Phase 3. I don't know enough about Phase 3, so will verify.

**Comment by amenity** [comment]
@SurbhiBakshi - any more info on where this goes?

**Comment by SurbhiBakshi** [comment]
@amenity - so from my understanding, this is a bit of a straggler issue, April S conducted UAT again, and will let me know of the results.  I shall move it to Blocked, we are waiting for her to report back to us on UAT results.

**Comment by amenity** [comment]
@SurbhiBakshi - great. Thank you!!

**Comment by SurbhiBakshi** [comment]
second in-person UAT session set up for 9/12 with April and George.

**Comment by SurbhiBakshi** [comment]
@johnclary @amenity - April S would like George S to attend the UAT, I have scheduled an in person UAT on 03/12

**Comment by SurbhiBakshi** [comment]
Notes from UAT with George and April - 
There are 5  subtypes associated with Small Cell Permits, each with an Application fee and an Approval/ Usage Fee that get distributed to AE, ATD, DSD, PAZ, and PARD in predetermined ratios (percentage) - 

1. Node -AE Pole (working except for percentage distribution)
a. Application Fee
b. Usage/ Approval Fee

2. Node - ATD Pole (working except for percentage distribution)
a. Application Fee
b. Usage/ Approval Fee

3. Node - Lode (working except for percentage distribution)
a. Application Fee
b. Usage/ Approval Fee

4. Node - Other
a. Application Fee (are added automatically)
b. Usage Fee are not added automatically.  April added these manually. This needs to be corrected.

5. Fiber 
a. Application Fee
b. Usage Fee -is multiplied by the number of street segments/ or propertyRSN records associated with the permit.

**Comment by SurbhiBakshi** [comment]
**Additional Requests from April -** 
- Clean up of fees - wants to remove the SCP prefix, and duplicates in the fee list. She will send me the list.April - how does applicant get an invoice emailed to them? April creates invoice, downloads and then emails it to them. Would like an automatic process where a created invoice is emailed to applicant. Applicant can pay and that notifies/ changes status for folder.

**Comment by SurbhiBakshi** [comment]
Sent an email to April to see how fees from April's handout are associated with fees in Van's email.

**Comment by SurbhiBakshi** [comment]
have checked twice with April in the last couple of weeks and have not heard back.  (could be Covid-19  related remote work set up )

**Comment by amenity** [comment]
@johnclary - FYI: This is blocked...Comptroller's office will be asking for this soon, yeah?

**Comment by SurbhiBakshi** [comment]
Checked in with April S to see if she can make it to the Thursday meeting. Yet to hear back.
@johnclary - will slack you her supervisor's name.

**Comment by SurbhiBakshi** [comment]
@johnclary - have not heard back from April. We will need to ask John G for someone else from his team for UAT work.

**Comment by SurbhiBakshi** [comment]
Email from Kim - I am so overloaded right now. This teleworking is so slow and is causing me to get behind in my daily work. I have not been able to do any testing or even focus on the fees. I apologize, but can we push this out?

**Comment by SurbhiBakshi** [comment]
I asked April who else could do UAT, she suggested Tracy L.

**Comment by SurbhiBakshi** [comment]
@Nadin-Nader contacted George S and has got  information on testing.

**Comment by amenity** [comment]
@TracyLinder - pull @Nadin-Nader in to test with you, please. :)

**Comment by TracyLinder** [comment]
Will be testing w/ April and Nate on Monday 5/4

**Comment by TracyLinder** [comment]
**George w/ CTM emailed some feedback regarding the 2 active bugs/issues. This was my final response:**

George,

Great work, thank you! My response:

1.	Application fees are billed separately: Please update the autobill to ‘No’ as suggested. The fees should all bill together as a single invoice. 
2.	Attempt is saved even with unpaid fees: Your procedure fix sounds great, let’s do it. 

Thanks,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
Round 3 of UAT (for ATD & TARA) are complete. Stakeholders were updated today. Next DSD & Finance need to test on their side, before this goes to PROD.

**Comment by TracyLinder** [comment]
**Email today, to stakeholders:**

Ram, 

Thanks again for stepping up to help us push this through. Do you know who in CTM will be tasked with resolving the issues identified by DSD (Deborah), and if they have yet been tasked with it? 

Thanks, 

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
**Status:** As of 7/9/20, this is pending UAT from COA Finance office (Mark C. & Eva S.)

**Comment by TracyLinder** [comment]
**Email to Stakeholders:**

Hi Team,

It seems this issue has gone stagnant. Do we know where we are with this and what the next steps are?

Thanks,

**Comment by johnclary** [comment]
@TracyLinder start from scratch. hopefully it won't take too long.

**Comment by TracyLinder** [comment]
New test data has been sent to the team. I'm attaching it here also. [https://app.zenhub.com/files/140626918/601c7ffd-b1a2-43fd-8097-18e159f56767/download](https://app.zenhub.com/files/140626918/601c7ffd-b1a2-43fd-8097-18e159f56767/download)

**Comment by TracyLinder** [comment]
### Email from George:

Hi all,

I took Tracy’s spreadsheet and matched the fee descriptions with the fee codes and GL codes in the TEST environment. I also checked the same fee codes in PROD and found that some were either missing the GL code or completely missing.

Tomorrow I can work on promoting all these SCP-related fees from TEST to PROD. Also, if anyone has any other fee codes that are missing GL codes or other information, I can put those through for promotion as well.


Thanks,

George Shirai
