### ISSUE TITLE
Support initial TPWstat meeting

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#14251]
First meeting is October 25th. 

Rebekka and Charlie will help create data visuals in Excel to be pasted into the TPWstat power point.

Will also provide other support to get things ready for the first meeting.

**Comment by rebekkabry** [comment]
Initial Meetings in Progress  - with DTS assistance and attendance 

[TPWStat Presentation Example](https://cityofaustin-my.sharepoint.com/:p:/g/personal/rebekka_bryant_austintexas_gov/EXjjUiE05XxOgOVHzq0KWCwBsuIZJ28O7JB0p_xDJWWQGQ?e=ZxKoMQ)
