### ISSUE TITLE
Living Street Testing 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#14259]
### Thu 10/12/23 
- [x] Create accounts if needed for testers (Matt M., Jonathan S., and Manuela F.) and assign role Living Streets Review Staff 
- [x] Update Living Streets Program Home permissions to allow tester access 
- [x] Update email settings and content going out of Living Streets account creation 
- [x] Test account creation path to correct views in the Applicant Portal 
- [x] Draft invite letter to testers, including links to all relevant pages
- [x] Review in debrief on F 10/13/23 and send out

**Comment by KaroEngstrom** [comment]
## F 10/13/23 
- sent out invitation to test and put this issue in Review/QA for us to capture notes on testing

**Comment by KaroEngstrom** [comment]
## F 10/13/23 
- updated submitter confirmation emails to send to submitter email address
- updated reviewer notification to send to Living Streets service account email address

**Comment by dianamartin** [comment]
@KaroEngstrom @patrickm02L I think we can close this, right?

**Comment by dianamartin** [comment]
# 10/27
Have met with stakeholders
- 10/18 Living Streets Review v0.5
- 10/24 Living Streets Review v0.6
Have been making improvements from each feedback session.
