### ISSUE TITLE
User Support: Permissions Issue for Sangeeta J

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1427]
### Overview:
- Sangeeta is unable to create bills on the SP folder.

**Comment by TracyLinder** [comment]
### Update
- 1/28/20: I attempted to update Sangeeta's permissions however she already appeared to have all the permissions needed for this request. 
- 1/28/20: I emailed Mike D, Nadin N, and Andrea G w/ CTM Support
    - No response as of today, 2/13/2020
    - Email Content:
> Hello y'all. I am going to submit a ticket for this but actually need some feedback from y'all first please.  
Sangeeta needs permissions to bill fees on SP, C8, and ZC folders. I checked her permissions and she seems to have the right button permissions. What needs to be updated on her user profile so she can create those bills? 
Thanks, 
Tracy 
- 2/12/20: Sangeeta emailed me asking for an update

**Comment by TracyLinder** [comment]
### CALL0019536 Created in COA Service Now

**Description:**
- Sangeeta needs AMANDA user permissions to create bills on the following folders: SP, ZC, C8
- I (Tracy Linder) attempted to update her user profile in AMANDA TEST however it appears to me that she already has the button permissions required to create bills on these folders
- I (Tracy) sent an email to AMANDA Tier Support on 1/28/2020 requesting feedback; no response received

**Please update Sangeeta's user permissions so she is able to create bills on these folders. I (Tracy) will likely be out on extended SCK leave for the next few weeks, so please don't reassign this back to me. Thank You.)**

**Comment by TracyLinder** [comment]
### Customer Update Email
Sent 2/13/20 @ 3:11pm

Hi Sangeeta,

Thanks for reaching out about this. I’m really sorry this hasn’t been resolved yet.
On 1/28/20 I emailed a few people in CTM AMANDA Support requesting assistance with this, but have not received a response. I just opened a Service Now ticket for this; you should be getting some automated emails about it soon. CTM should be contacting us about this in the next 2 or 3 days. 

All The Best,
Tracy

**Comment by TracyLinder** [comment]
### Emails/Communications Update

From: Linder, Tracy <Tracy.Linder@austintexas.gov> 
Sent: Tuesday, February 18, 2020 3:33 PM
To: Jain, Sangeeta <Sangeeta.Jain@austintexas.gov>
Cc: Applewhite, Amenity <Amenity.Applewhite@austintexas.gov>
Subject: AMANDA User Permissions Issue

Hi Sangeeta,

Have your user permissions been fixed yet? 

Thanks,

Tracy Linder
IT Business Systems Analyst Sr.
Data and Technology Services 
Austin Transportation Department 

- - - - 

From: Jain, Sangeeta 
Sent: Wednesday, February 19, 2020 8:47 AM
To: Linder, Tracy <Tracy.Linder@austintexas.gov>
Cc: Applewhite, Amenity <Amenity.Applewhite@austintexas.gov>
Subject: RE: AMANDA User Permissions Issue

Not yet!

Sangeeta

- - - - 

Hi Deanna, 

Can you please assist us with this user permissions request submitted last Thursday? The Service Now reference number I have is CALL0019536 and the request description is:

CALL0019536 Created in COA Service Now
Description:

Sangeeta needs AMANDA user permissions to create bills on the following folders: SP, ZC, C8
I (Tracy Linder) attempted to update her user profile in AMANDA TEST however it appears to me that she already has the button permissions required to create bills on these folders
I (Tracy) sent an email to AMANDA Tier Support on 1/28/2020 requesting feedback; no response received
Please update Sangeeta's user permissions so she is able to create bills on these folders. I (Tracy) will likely be out on extended SCK leave for the next few weeks, so please don't reassign this back to me. Thank You.)

Our internal issue is here with all the info I have on this issue. 

Thank You,
Tracy 


Tracy Linder
IT Business Systems Analyst Sr.
Data and Technology Services 
Austin Transportation Department

**Comment by amenity** [comment]
Per an email thread from 2/24:

@johnclary 
> Hey all—AMANDA support is taking care of this request, but they did raise a concern around the permissions that Bryan and Sangeeta have, which is that they have the ability to both add a fee to folder and create the invoice. Apparently this has been flagged by the auditor in the past.

Ryan M. 
> Yes, the auditors raised that as an issue and we had to change permissions for permit analysts as a result.

Sangeeta J.
> Clarification:
> We at TDS division need to be able to insert fees and create bill.  We do not collect any payments.  Payments are only made with the cashier, OTC or online on AMANDA portal.  Nate A., Nazlie S., Amber M., Justin G., Bryan G.,…… all have such permissions.

Paloma A.
>This is in line with our PLA permissions.  To be exact, the Analysts are able to insert fees and create bills but cannot process any payments. 
> We weren’t actually processing payments but we had the ability to which is what the Auditors found fault with.

**Comment by amenity** [comment]
@johnclary - I think this can be closed, correct?

**Comment by johnclary** [comment]
Yes! Closed.
