### ISSUE TITLE
Complete PRF - AMANDA BSA

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1428]
### Overview:
**Position Responsible For:** Triage, basic user support, account management, fulfill requests for reports or data, and simple user research/ requirements analysis

**Comment by amenity** [comment]
@johnclary, assigning this to you -

**Comment by johnclary** [comment]
Thanks. This is done and on Peggy's desk. Moving to Review/QA

**Comment by johnclary** [comment]
Leave in review QA until I confirm with Peggy that all signatures have bene collected. Per Peggy, we can proceed with the hire.
