### ISSUE TITLE
Automate access to high-level SMD data points for TPWstat

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#14288]
**Monthly if possible**
- [x] Percent of unstriped streets striped within 30 days (time to apply markings after SBO resurfaces) - [view](https://datahub.austintexas.gov/Transportation-and-Mobility/TPWstat-Percent-of-unstriped-streets-striped-withi/hukg-ea95/about_data)
- [ ] Signs in fair or better condition
- [x] HIN markings in fair or better condition

[Semantic Model](https://app.powerbigov.us/groups/b73ea40f-8b44-4aa9-9794-7a87b43e5246/datasets/44c726e9-9732-4d23-9c8d-d6aed17d026e/details)

**Comment by amenity** [comment]
@katelunceford - touch base w/ Michael & Jewlee to see if this will cover what they

**Comment by katelunceford** [comment]
Per [Data Science Backlog Refinement (DSBR)](https://docs.google.com/document/d/16RBJStu65lHTQa_MVYde7jmortp1ako1P1-A6mPcNOg/edit) on 4/24/24

DTS is handing off the SMD dashboard to SMD so we won't control or change it anymore. It's possible/probable that they'll ask for our help to make bigger changes, especially at first. But it's not up to us to ask for changes. So we're going to remove this part of the issue for now:

> Add monthly reporting to the SMD Performance Measure Dashboard
> 
> Three performance measures were identified to add to SMD's TPWstat meetings. It looks like we are currently reporting on these in the SMD Performance Measure Dashboard report but only for the full fiscal year. Can we report on these but by month as well?
> 
> - Percent of unstriped streets striped within 30 days (time to apply markings after SBO resurfaces)
> - Signs in fair or better condition
> - HIN markings in fair or better condition

Let's wait to automate anything for now because we get a sense that SMD might change a few things (ex: remove specialty markings from markings metric). They're having conversations with OPM about a new measure.

**Comment by Charlie-Henry** [comment]
@katelunceford, @susannegov and I met with @michael-santulli and Jewlee today

- Percent of unstriped streets striped within 30 days 
   - We're close on this one but Susanne and I will review my query during our 1:1 next week
- Signs in fair or better condition
- HIN markings in fair or better condition
  -  Will need to write a python script for these two asset conditions measures

**Comment by katelunceford** [comment]
@Charlie-Henry sounds good - I assigned you, moved this to in progress, and added this sprint. Is that all accurate? Could you add a size estimate?

**Comment by Charlie-Henry** [comment]
Yup sounds good!

**Comment by Charlie-Henry** [comment]
@michael-santulli Susanne and I confirmed this afternoon that this [view](https://datahub.austintexas.gov/Transportation-and-Mobility/TPWstat-Percent-of-unstriped-streets-striped-withi/hukg-ea95/about_data) of the percent of unstriped streets striped within 30 days is correct

**Comment by katelunceford** [comment]
@Charlie-Henry will email Michael the pbx file for HIN markings in fair or better condition

**Comment by Charlie-Henry** [comment]
Sent!

**Comment by Charlie-Henry** [comment]
@michael-santulli, it doesn't look like sign condition data is being tracked month-to-month like markings are. TBD when their work order process changes but currently there's no history of signs and their condition.

**Comment by Charlie-Henry** [comment]
I believe we're good to close this out. I'm not sure how this is getting pulled into TPWstat currently, but Michael set up a process to handle it.
