### ISSUE TITLE
Spike: Communication Management Software for ROW (TL)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14289]
### As part of the ROW-AMANDA Withdrawal & Mitigation Analysis, stakeholders would like to explore a tech solution for the lack of communication management features in AMANDA. 

**Information we plan to gather includes:**
1. CRM vs CM (Customer relationship manager vs Communication management)
2. Are there are CRM/CM software in use by the COA? Can we leverage them? 
3. What solutions are in the marketplace? 
4. Is there a tool that could sit on top of AMANDA (like a widget) as a supplemental feature rather than using a stand-alone software?

**Comment by TracyLinder** [comment]
I added this to the product sync agenda on 10/25

**Comment by TracyLinder** [comment]
### Update 10/24

1. Homer will be doing user research with a ROW permit analyst to gather:
- Where is the gap for communication features?
- How is the PLA mitigating the gap? How long does this take? What tools are they using?
- What problem(s) is the lack of a communication feature in AMANDA causing the PLA or related stakeholders?

2. Tracy will discuss at the Product Sync tomorrow 10/25
- Difference between CRM & CM? 
- How to find out what CRM type of software is in use by city departments?

3. Homer will do market research.

**Comment by TracyLinder** [comment]
**Posted in the Continuous Improvement Network Teams channel:**
Hi all 👋🏼 - What software do you or your department use to manage communications and customer interactions with external customers (other than Outlook or MS products)? I’ve been tasked by an AD to compile a list of Customer Relationship/Communications Management software in use by various city departments.

**Comment by HomerArizpe** [comment]
### Update 10/31

Scheduled 3 ROW Permitting Observation Exercises for 11/1, 11/2, and 11/3, to identify AMANDA communication gaps for 3 different processes.

**Comment by TracyLinder** [comment]
### Fresh Desk / Freshworks Conversation with Cliff P. at DSD

- Surbhi is the product manager, I should meet with her to discuss how they are using the product
- [Freshworks](https://www.freshworks.com/) is the parent company; they are no longer on the DIR or have any corporative agreements. For this reason DSD will have to either find a replacement product or get a master agreement for Freshworks.
- Freshworks is often non-responsive to DSD. 
- DSD does not recommend working with the vendor and are actively searching for a replacement product. We should definitely meet with Surbhi, who is managing most of this. They may be shopping for something similar; TPW & DSD could join efforts if it makes sense.

**Comment by TracyLinder** [comment]
Meeting scheduled with Surbhi at DSD on 11/7/23. 

Hi Surbhi,

We're doing some research on potential software solutions that could help mitigate the lack of communication management features in AMANDA. I spoke briefly with Cliff about how you're currently using Freshworks products and he pointed me in your direction. Some of the questions I have are below.

- What Freshworks products is DSD using and what are the basic use cases (why)? 
- Do the users still have to use Outlook to communicate with applicants and stakeholders, or are they using a different app for this purpose? 
- What replacement products are you looking at? 

Thank You,
Tracy

**Comment by HomerArizpe** [comment]
All 3 Observation Exercises completed. Analysis is ongoing.

**Comment by TracyLinder** [comment]
### Sync with Homer:Tracy 11/6/23

- Public Website confusing causing staff to spend extra time explaining things to customers and assisting with website navigation
- Possible AMANDA Solution: Make the department comments feature work better.
