### ISSUE TITLE
Austin 3-1-1 CRM Service Requests Standards - Public Works - Quality Review

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#14285]
Austin 3-1-1 CRM Service Requests Standards - Public Works - Quality Review

- Remove acronym from work logs.
AWD is not an apporved acronym
No outcome is selected on the first activity.  ADA is not an approved acronym.
ETJ is not an approved acronym
UER is not an approved acronym
AWD is not an approved acronym

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWc4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b191724022313e12c78935f6301b2060db4506c/image.png)

Update Maximo documents and guide users

**Comment by adry-martinez** [comment]
Updated the following documents with full department names instead of acronyms. Updated Commonly Used document with acronym cheat sheet. 
Sent newsletter article to @YakshDipa for review.

**Comment by adry-martinez** [comment]
Article approved and published. Issue closed.
