### ISSUE TITLE
Maximo, User Account - Duplicated

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#14303]
User contacted me with the following request:

I'm having an issue with Maximo using my name in two ways: FAYLES_TYLER and FAYLEST. Is there a way to remove one?

The user is requesting to maintain FAYLEST. 
Please verify which user name has work orders assigned as that would be the default for the account.

**Comment by ReneVarg25** [comment]
Requested name format has been made the default for requestor's labor record. Other person ID has been set to inactive.
