### ISSUE TITLE
Create EDP & ODP dataset of Sign Specifications in City Datahub

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14319]
SMD needs the sign specifications/assets added to the City Datahub for their PowerBI dashboard reporting purposes. 

- Met with SMD to work on the dashboard and we identified that there is a need to bring the sign specification/assets into the City Datahub. Going to create a new issue for adding that dataset to the EDP since it's the highest priority.

Fields to include are identified in this spreadsheet: [smb_specs_materials_updated.xlsx](https://github.com/cityofaustin/atd-data-tech/files/10396783/smb_specs_materials_updated.xlsx) 

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/11312#issuecomment-1747218726_

**Comment by ChristinaTremel** [comment]
Fields to Add:
--
- ATD_WORK_ORDER_ID
- ATD_SPECIFICATION_ID
- ASSET_ID
- ASSET_NAME
- ASSET_CATEGORY
- ASSET_MESSAGE
- ASSET_MOUNT
- ASSET_SIZE
- MUTCD_CODE
- SPECIFICATION_NAME
- UNIT_COST
- QUANTITY
- TOTAL_COST
- ASSET_CONDITION
- ASSET_DIRECTION_FACING
- ADDITIONAL_MESSAGE_INPUT
- MESSAGE_REQUIRED
- SR_NUMBER
- TASK_ORDER_NUMBER
- FUNDING_NUMBER
- LOCATION_ID
- MODIFIED_DATE

**Comment by KaroEngstrom** [comment]
### Scheduled a working session for Thu 11/9/23

**Comment by KaroEngstrom** [comment]
@ChristinaTremel  Ready for the dev portion 🥧  The Socrata asset is currently EDP - Internal audience; once we have the ETL and the metadata sorted, we'll open up to ODP - Public audience. 

@chiaberry 

- [source API table](https://builder.knack.com/atd/signs-markings/pages/scene_1249/views/view_3106/table) in Knack (sharing with ArcGIS) 
- target Socrata table [jji9-2k5d](https://datahub.austintexas.gov/Transportation-and-Mobility/Street-Sign-Specifications/jji9-2k5d)

**Columns to use for Socrata**
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/5d11a947-7e71-4a63-9fd8-5863a64d1add)

**Comment by KaroEngstrom** [comment]
- Susanne updated the column metadata 

**Apps Steps** 
- once the ETL is running, check the dataset and publish to ODP

**Comment by chiaberry** [comment]
I ran into an issue with the column definition for the Location field in socrata. It was defined as text, when it needs to be either point or multipoint for our script to work. I didnt want to lose the column information, so I temporarily added a new column named Location New and changed the old location's column to be skipped over when the script runs. 

I want to check if the point location is okay, or if it needs to be a text field.

**Comment by chiaberry** [comment]
@KaroEngstrom @susannegov @ChristinaTremel 
see the comment above, I had to change the columns in the EDP by changing the location column type. I can explain more tomorrow if thats helpful

**Comment by KaroEngstrom** [comment]
I did see your comment. Susanne is the expert and original requester; she's back Monday. 
Can we table this for the rest of the week and get back next week? I thought I saw a potential dupe/overlapping dataset (at least a record of one) and would love to investigate briefly.

**Comment by KaroEngstrom** [comment]
The suspected dupe DTS portal record was an old Maximo dataset so not a concern. 
@susannegov - can you comment on the Location column issue a above?

**Comment by ChristinaTremel** [comment]
@chiaberry Susanne, Karo, and I discussed this in the apps sprint planning and we're okay with changing the `Location` to the `Location New` format (where it's showing the point location and latitude and longitude). So we're okay to delete the initial Location type. 

One thing Susanne was wondering - could we still populate the `Latitude` and `Longitude` fields by parsing out the data from the `Location New` field?

**Comment by chiaberry** [comment]
@Charlie-Henry & John told me about https://support.socrata.com/hc/en-us/articles/360034530954-Data-Transformation-Examples, and Charlie showed me where to find it, so now the lat and long are parsed by socrata!
