### ISSUE TITLE
Add Leading Pedestrian Indicator Field to ArcGIS Online

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1431]
Add fields:

- [x] `LEADING_PEDESTRIAN_INTERVAL`
- [x] `DATE_LPI_INSTALLED`
- [x] `N_S_PED`
- [x] `E_W_PED`
- [x] `LPI_COMMENTS`

**Comment by alan-deanda** [comment]
@johnclary  the fields have been added.
