### ISSUE TITLE
Update Signals Knack API view to include LPI Field

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1432]
[This is the view](https://builder.knack.com/atd/amd#pages/scene_73/views/view_197) that needs to be updated.

Object table: `API Views`>`Signals`

**Comment by johnclary** [comment]
@alan-deanda please hold off until we provide you with the field names/types.

**Comment by dianamartin** [comment]
@johnclary Do we want to add the other fields too? 
![image](https://user-images.githubusercontent.com/21112975/74769854-c1c50f80-5250-11ea-93a3-5c317d70d3c1.png)

**Comment by johnclary** [comment]
yes—good catch. would you add all of these fieldnames to the related issues in this epic? thank you!

**Comment by dianamartin** [comment]
Added: 
- `N_S_PED`
- `E_W_PED`
- `LPI_COMMENTS`
