### ISSUE TITLE
Fee Bug ATD-SUB-Final Plat on C, C8 (SR) (REWORK) (Deployed to Prod)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14323]
### Bug when using the Insert + Run Fee Procedure feature to insert ATD-SUB-Final Plat on C and C8 folders. 

**Issue:** 
- "Error calculating flat fee" is displayed when attempting to insert the fee using Run Procedure. The specific fee that's causing the issue has been identified as " ATD-SUB-Final Plat ".

**Details and Steps to Reproduce:**

1. Navigate to C8 folder in AMANDA.
2. Go to fee Tab.
3. Run Procedure 83478	ATD-SUB-Final Plat
4. Error "Error calculating flat fee" is received related to the "83478 ATD-SUB-Final Plat" fee.

----
_(Submitted via sn INC0334282 by DSD, and reassigned to TPW.)_

 

 

**Additional Information:**
- The issue is present on other C and C8 folders as well.
- Multiple users have reported facing the same issue.
- The procedure was successful before 10/2/23.
- The system has transitioned to a new fiscal year.
- A screenshot of the error has been attached.
- The error is consistent and can be reproduced regularly.

**Temporary Workaround:**  
To bypass this issue currently, fees are being inserted.

**Comment by TracyLinder** [comment]
### Meeting with Zach at DSD 11/2/23
_Tracy, Zach, Vish_

Zach reported 2 issues recently; this one and confusion on #14112

**Comment by TracyLinder** [comment]
Hi @Nadin-Nader this is ready to debug. @Vaishnav1397 will be the contact for this bug moving forward. Thank you both.

**Comment by TracyLinder** [comment]
Per Sree's analysis the fee expiration date is outdated in PROD only; the other environments are correct. @Nadin-Nader will speak to jenice about updating prod only because of the Phabricator issues.

**Comment by Nadin-Nader** [comment]
This has been sent to the CTM Team to be deployed on PROD under **SCTASK0372201**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Verified in PROD and it looks good. Ready for PROD UAT.

**Comment by TracyLinder** [comment]
Hi Zach, regarding the bug with the fee ATD-SUB-Final Plat, we have pushed a fix to production. I'm not sure if you're able to confirm that the fix works in PROD, but please do let us know ASAP if it misbehaves. 

Thank you,

**Comment by TracyLinder** [comment]
Hi @Nadin-Nader and @Sreelatha-BlazeKannan I have re-opened this issue because the user informed me that the fee is inserting the wrong amount. The correct amount is $2370.

- On folderID 13233060, the system inserted the amount $2,110 instead of $2,370.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I see that the fee amount is updated in below folders as 2370
C - 2370
SP - 2370
ZC - 2370
C8 - 2110
TIA - 1310
So, I need to update only for C8 and TIA, need confirmation to proceed about this.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please update the amount everywhere it exists

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP of #14323 submitted. Kindly approve and create task id for the same.

Commit ID: 206bc0c1606bbc01ee2dbc9647beeb427d8e4dc9

![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/6a1ec086-ba7f-4586-a4af-15c787593cab)

**Comment by Nadin-Nader** [comment]
This has been sent to CTM DevOps to be deployed to TEST under **SCTASK0377523**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Changes are in TEST; tested and all working as expected. ready for TEST UAT

**Comment by TracyLinder** [comment]
### UAT - Approved
@Sreelatha-BlazeKannan please promote to PROD

- TIA ✅
- C8 ✅

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - PROD DP of #14323 submitted. Kindly create task id for the same.

Commit ID: 206bc0c1606bbc01ee2dbc9647beeb427d8e4dc9

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Created Prod Deployment request , SCTASK0377743

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Changes are deployed to Prod , Please verify

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Verified in PROD and looks good. Ready for PROD UAT.
