### ISSUE TITLE
Add `Tracking Type` field to SMD inventory_items object and to both the signs and markings manage materials pages

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14321]
Need to add `Tracking Type` field to the SMD Data Tracker `inventory_items` object. 
- Multi-choice field with these options:
   - FINANCIAL
   - NON-FINANCIAL

**Comment by ChristinaTremel** [comment]
@dianamartin this might already be done!

**Comment by dianamartin** [comment]
# 10/18
- I forgot that I had looked at this in the SMD Tracker
- the object table `inventory_items` has a field `INVENTORY_TRACKING` (FINANCIAL, NON - FINANCIAL)
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b2e464b7-1d8e-4427-9786-6d144f7440cb)

**Comment by dianamartin** [comment]
Closing this issue bc Christina has to follow-up with Johnny on it when he sends the inventory list.
