### ISSUE TITLE
Builder Huddle: TCP/CSWZ Upgrade 10.18.23

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14337]

**Comment by TracyLinder** [comment]
## Tracy's Notes

- [ ] Requirements documentation expectations
- [ ] User accounts?
- [ ] Workflows
- [ ] Statuses 


K: She can't begin development until 11/1 due to Living Streets project. (This was discussed at apps planning today.)

**Comment by HomerArizpe** [comment]
Builder Huddle #2 is scheduled for Thursday, Oct. 26.
