### ISSUE TITLE
[Tech Debt] Optimize VZA Batch Import functionality

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#14339]
Importing `Assignment Date Time` field with the calendar option enabled introduce discrepancies when importing new VZA records and risks chance of errors occuring. Increases lift in batch data import.
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/383c4e42-c81e-4f79-86ea-4287aa27617e)

# Suggestions
1) Create Assignment Start Date as simple date field with time format (military) and Assignment End Date as simple date field with time format (military)
   - Will create assignment time formula
   - Data standard consistency even if rebuilding in backend
   - Does it affect the calendar view?
2) If option 1 doesn't work, option 2 use the existing FME and modify it to generate the CSV

**Comment by ChrispinP** [comment]
Imports are no longer required, closing as no action
