### ISSUE TITLE
Rename LPI Fields in Data Tracker to Comply with ETL Process

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1434]
We need to rename:

- `Leading Pedestrian Interval` 
- `Date LPI Installed` 
- `N_S_ped`
- `E_W_ped`
- `LPI_Comments`

to be uppercase with underscores instead of spaces.

Object table: `signals`

**Comment by dianamartin** [comment]
Renamed: 
- [X] Field: `Leading Pedestrian Interval` to `LEADING_PEDESTRIAN_INTERVAL`
- [X] Field: `Date LPI Installed` to `DATE_LPI_INSTALLED`

**Comment by dianamartin** [comment]
Renamed:

- Field: `N_S_ped` to `N_S_PED`
- Field: E_W_ped to `E_W_PED`
- Field: LPI_Comments to `LPI_COMMENTS`
