### ISSUE TITLE
[Enhancement] Handle phase date confirmation events in activity log

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#14351]
Let's do this after https://github.com/cityofaustin/atd-data-tech/issues/14350...

**Comment by chiaberry** [comment]
<img width="1224" alt="Screenshot 2023-10-24 at 2 15 50 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/12474808/748af03a-3812-4357-88c5-07509f3e1a8f">
What should it say? something like this, or something better? @johnclary
