### ISSUE TITLE
Mtg: Scoping w/ Paloma & Kim @ ROW | Feb 19, 2020

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#1436]
### Objective 
**Scope requests & add acceptance criteria related to #1423 :**
- Unpaid fee check & flag on permit issuance
- Update parking permit fee rate

### Meeting Info
**Participants:** Tracy L, Diana M, Paloma A, Kim P
**Date/Time/Location:** Feb 19 | 3pm | Skype

------
- [x] Schedule meeting
- [x] Meet and take notes in agenda doc
- [ ] Create resulting issues

**Comment by TracyLinder** [comment]
# Meeting Notes:
_Participants: Tracy L, Surbhi B, Kim P_

- Overview of The ATD AMANDA backlog 'Priority 1's' initiative with Launch IT (LIT)
- Discussed the methodology used to rank the items in this list, which is an export of DTS GitHub issues

**Please Note: The ATD AMANDA backlog is a living thing with priorities constantly changing, and requests consistently being updated with new information. The order in which these items are developed is largely determined by stakeholder input.** 


**ROW's Highest Priority:** All fees the ROW cashier accepts (at Toomey, usually Brandi) be added to AMANDA before their move to PDC this summer. 
- This need is already captured as a Priority 1 item. See [#49](https://github.com/cityofaustin/atd-amanda/issues/49)

## Update Parking Permit Fee Rate
_#[207](https://github.com/cityofaustin/atd-amanda/issues/207)_
**Decided this issue should remain in the backlog until ROWMAN Phase 5 goes live.**
> Due to the complexity of parking rates, this request is actually project sized work, and outside of the scope of the ATD/LIT Priority 1 Initiative. Another high ranking request will take it's place. 
- Note: The infrastructure required for this request has been largely developed as part of the ROWMAN Project, Advanced Click Map Features AKA Phase 5. After this phase is complete, the infratructure needed to automate calculation of parking fees will be in place, making this item a sprint sized request. 

Here is an example of the info ROW staffers use to manually calculate parking fees:
![image](https://user-images.githubusercontent.com/49930868/74903460-99333780-536e-11ea-92eb-e300781b7268.png)

## Out-of-System Fees
_AKA # 49 Out of Process TCP Fees, # 211 New GF Subtype, ROW's #1 Priority, Outstanding Audit Request_

**Note:** We discovered that both these issues are part of the same user story.
    - #211 will be closed 

**Stakeholders:** Paloma, Kim, Mooney

**User Story:** As the ATD Cashier at Toomey, I need to record all fees i accept in one system of record. The few remaining fees not in AMANDA should be added ASAP. 

**User Story:** As the person paying an 'out of process' fee, I need to be able to pay those fees online.

**Future State:**
_When ROW staff need to collect an 'out of process' fee_
1. In AMANDA, create a new GF folder, choose subtype ATD
2. Add the project location (site address) to the folder property tab
3. Add people record types Applicant, and Billed-To to the people tab
4. **Need SME Input** Complete required info fields on the info tab
    - Kim was unsure if TCP Review staff will want any info tab fields. Perhaps the TCP #? 
5. Insert & bill the fee(s), provide customer with the invoice
    - The folder status will be 'Pending Payment'
6. The customer pays the fee
7. The folder status updates to 'Payment Complete' -End Process-

- Brandi is best to ask for a list of fees collected outside of AMANDA
- The General Fees (GF) folder in AMANDA is what other departments are using to record fees outside of a specific case folder
- TCP Review Fee is being collected manually
    - **Need SME Input**
    - Amount? Flat Fee - no logic
    - Name of Fee?
    - ATD Surcharge?

## Unpaid Fee Flag
_AKA # 46 Unpaid Fee Flag on Permit Issuance (Audit Request)_

**Stakeholders:** Paloma, Kim, Mooney

**User Story:** As a ROW permit analyst (PLA), I need to know if any of the folder people have unpaid ROW fees BEFORE the permit is issued, so I can place the permit on hold and attempt to collect the outstanding fee(s).

**Current State:**
1. The PLA, prior to permit approval, performs manual research to identify any unpaid ROW fees for ALL people listed on the people tab (Contractor, applicant, contact, whoever). 
    - They do not collect fees billed before 10/1/2013.
2. If no outstanding fees are identified, the permit is issued. End process. 
3. If outstanding ATD fees are identified, the PLA provides the outstanding fee information to the person/entity responsible for payment. 
    - So if there are 3 unique people/entities on the permit, each entity will be provided with their unique fee information. 
    - The people/entities are provided with instructions for paying, all outstanding bill numbers, and the total for each bill number. 
4. The PLA adds a note to the folder description: "Pending Outstanding Fee Payment **TL"
5. The customer will pay the fees, either online or in person. 
6. The customer notifies PLA of payment
    - When this step is missed, it leads to customers working in the ROW without an approved permit
7. PLA issues the permit. End Process. 

**Future State:**
1. Folder issuance is attempted, either by a user from the folder tab, or by a system procedure like post payment.
    - We need to be sure any new procedure doesn't cause payment update failures when the fees are paid online. (Put simply, lets learn from the issues caused by the Post Payment upgrade.)
    - This feature may have to be split into 2 features, one for running this procedure when issuance is initiated by the user from the folder tab, and another for running this procedure when issuance is initiated by a post payment procedure. **Will need LIT feedback on this.**
2. The system performs the unpaid fee verification
    - See # 1 in Current State; the system needs to do this instead of the PLA
    - Query all unpaid fees for each people record on the people tab. Of those fees, exclude any not in folder types RW, EX, LC, ECV, GF, or DS. Of those fees, exclude any created prior to 10/1/2013. **Now you have a list of qualifying fees.** 
3. If **qualifying fees** are found, an alert window opens informing the PLA that unpaid fees were found. 
    - The window will display this text: A people record related to this permit has unpaid ROW fees!
        - **Stakeholder input needed.** Please provide feedback on the proposed content of the alert window:    
![image](https://user-images.githubusercontent.com/49930868/74903386-60935e00-536e-11ea-9440-7aa50dc414c4.png)
    - The window will facilitate the following actions:
        - Allow the user to click a button to continue with permit issuance
        - Allow the user to click a button to abort the permit issuance, and view information related to the qualifying fees
        - The people invoice list view is an example of how we might provide the user with data about the qualifying fees:
![image](https://user-images.githubusercontent.com/49930868/74903558-e0212d00-536e-11ea-968f-a603023fc067.png)
4. PLA will provide the unpaid fee information (see list view above) to the customer, and note 'Pending Outstanding Fee Payment**' in the folder description.
    - If it's possible to email the 'list view' of unpaid fees to the customer from the window in AMANDA, that would be ideal **Will need LIT feedback on this.**
5. Customer pays
    - Jump to # 8 if customer does not pay
6. AMANDA notifies the PLA (or perhaps a resource task list?) that the permit needs to be issued **Stakeholder input needed. How would they most like to be notified?**
7. PLA issues the permit. End Process.
8. **Stakeholder input needed.** Will ROW need/want to know that these fees are still unpaid after a certain amount of time? For example, a monthly report emailed by the system with info about all 'fee flag alerts' that occurred in the previous month; only include info for fees that are still unpaid.
    - This would be another story/feature however LIT needs to be aware of the reporting requirement when developing the fee flag feature.

**Comment by TracyLinder** [comment]
[Email to Stakeholders](https://github.com/cityofaustin/atd-data-tech/files/4229203/Email.to.Stakeholders.pdf) with:
- meeting notes 
- request for stakeholder feedback
- next steps

**Comment by SurbhiBakshi** [comment]
-  Paloma has added to the notes from the last meeting. 
- Meeting to finalize feedback has been scheduled for Thursday Feb 27th.
