### ISSUE TITLE
Emails for SIF Appeals process (LP) (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#14377]
## Build four (4) automated emails for the SIF Appeals process #12918 
- Each email should be sent to the folder applicant, and from streetimpactfee@austintexas.gov

### 1. Appeal Packet received attempt:  
**Subject:** SIF Appeal Packet Received: `SIF Appeal Related PR# [process info]`

 **Content:** 

Dear `[Applicant first & last name]`, 

A SIF Appeals Packet has been received for the development located at `[primary folder address?]`. We will review your packet on or before `[process end date]`. We will contact you if more information is required or to schedule a meeting with TPW management. 

 Respectfully, 

Transportation Development Services – [streetimpactfee@austintexas.gov](mailto:streetimpactfee@austintexas.gov)  

 

### 2. Appeal Packet Incomplete attempt:  .  

**Subject:** SIF Appeal Packet INCOMPLETE: `[SIF Appeal Related PR#] `

**Content:** 

Dear `[Applicant first & last name] `

The SIF appeals packet received on `[date of most recent received attempt]` is incomplete for the reasons listed below: 

> [Incomplete attempt comments] 
 

Respectfully, 

Transportation Development Services – [streetimpactfee@austintexas.gov](mailto:streetimpactfee@austintexas.gov) 

 

### 3. Appeal Packet Complete attempt:  

**Subject:** SIF Appeal Packet COMPLETE:` [SIF Appeal Related PR#]` 

**Content:** 

Dear `[Applicant first & last name] `

The SIF appeals packet received on `[date of most recent received attempt]` is complete and will be sent to Transportation and Public Works Department management for review. We will contact you to schedule a meeting. 

Respectfully, 

Transportation Development Services – [streetimpactfee@austintexas.gov](mailto:streetimpactfee@austintexas.gov) 

 

### 4. Director Determination Approved attempt:  

**Subject:** SIF Appeal Packet DETERMINATION: `[SIF Appeal Related PR#] `

**Content:** 

Dear `[Applicant first & last name] `

Transportation and Public Works Department has made a determination regarding the SIF Appeal. Staff has initiated the refund process; the funds will be returned using the same payment method to the entity that made the payment. 

 

Respectfully, 

Transportation Development Services – [streetimpactfee@austintexas.gov](mailto:streetimpactfee@austintexas.gov)

**Comment by TracyLinder** [comment]
**Meeting w/ Amber & Nate & Vish scheduled for 11/7**

**Comment by TracyLinder** [comment]
The AC is updated with all the email content and this ticket is ready to go on-deck. 

FYI @Sreelatha-BlazeKannan @vschandramouli @Nadin-Nader

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in Progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Development is in Progress

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0374437**

**Comment by Nadin-Nader** [comment]
Waiting to be deployed

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  This has been deployed to DEV Please UAT when you get back

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0376884**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Verified in DEV and now tested for format changes and submitting another DEV Commit by updating the required formatting changes as per AC. 
Kindly approve and create task id for the same.


Commit ID: 73d0ba3fd2b2e2f74724fac8b0404bcce99f71f8
![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/a9e58738-5a0c-46e5-83ed-8829a0140a88)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0377530**

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Created Dev deployment request , SCTASK0378194

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Changes deployed to Dev, Please verify

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Created Dev deployment request , SCTASK0379595

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Changes prompted to Dev , Please verify

**Comment by Lpriya-LIT** [comment]
@SubhaShroff Changes deployed to Dev, please verify

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Created Dev Deployment request , SCTASK0380638

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV and conditions are working as expected. TEST DP will be submitted today.

**Comment by Lpriya-LIT** [comment]
@Sreelatha-BlazeKannan Created Test Deployment request, SCTASK0381153

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST and all looks good. Ready for TEST UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Email formats references - 

1. Appeal Packet received attempt:
![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/742f8350-d027-4800-a249-72441a90d4f7)

2. Appeal Packet Complete attempt:
![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/f0e14857-7c8d-4e47-b734-f49c44256e4e)

3. Appeal Packet Incomplete attempt:
![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/1af45842-a09a-4191-aff0-2ef0cae3470e)

4. Director Determination Approved attempt:
![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/b4d0c840-4353-41b0-8cd7-de14c5ece1f8)

**Comment by Nadin-Nader** [comment]
[Yesterday 3:53 PM] Aubert, Nathan
I'm getting an error with UAT on the SIF Appeal folder in AMANDA Test
[Yesterday 3:53 PM] Aubert, Nathan
 <img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW4zQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4700f6ce71ae1d6863136fbd8960303e37a793e/MicrosoftTeams-image%20%282%29.png" alt="MicrosoftTeams-image (2).png" />

 
[Yesterday 3:53 PM] Aubert, Nathan
 
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXYzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8baba8742ccf99b10a47233611b9a6aaed442d53/MicrosoftTeams-image%20%283%29.png" alt="MicrosoftTeams-image (3).png" />
 

[Yesterday 3:54 PM] Aubert, Nathan
Multiple Application Received Attempts not allowed. If there is an incomplete application, we get stuck in a loop

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - This is tested in both DEV & TEST with AC Changes for Incomplete conditions/validations.
All working as expected.
DEV FolderRSN - 13203141
TEST FolderRSNs - 13206341, 13206343
**Email Formats -**

**Appeal Packet Received**
![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/19c73589-e54c-4b57-9f52-c56c2cfcb010)

**Appeal Packet Complete**
![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/154ba0de-12e7-424b-9461-5e3eac705f12)

**Appeal Packet Incomplete**
![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/bc7a4521-5125-4add-8d11-4803a77e1878)

**Director Determination Approved**
![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/88910063-d56c-4664-b190-b771449b0b7f)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DRAFT PROD DP’s of https://github.com/cityofaustin/atd-data-tech/issues/12918 & https://github.com/cityofaustin/atd-data-tech/issues/14377 sent. There will be a conflict that’s why these 2 cards commit must be done together to get all our AC changes.

Please find the Commit ID’s and its Order for promotion.

![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/79f827c0-f29e-4082-ba5e-2aabb4b46f48)

**Comment by Nadin-Nader** [comment]
Waiting on UAT from TDS team. I sent an email asking for UAT on 2/7/24

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created prod deployment request , SCTASK0411259

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Changes deployed to Prod , Ready for UAT

**Comment by Nadin-Nader** [comment]
Sent Teams messages to Amber and Nathan to see if this is good to go or if it needs re-work. Awaiting response
