### ISSUE TITLE
IT Support: [Spade Printer issue]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#14389]
St Elmo
## Device & User Information (first name and last initial, no last names)
Printer & Spade
## What's the problem?
Trouble to get a print and seems the cartridge needs to be refiled. 
## What did you do to resolve the issue
Have contacted the xerox team in order to place the cartridge request. Have provided the details as requested for the order and the ticket number by xerox team is: IU804452.

**Comment by Vaishnav1397** [comment]
Order placed and waiting on the shipment to be delivered.

**Comment by Matthew-M-TPW** [comment]
Printer operating correctly 

Replaced cartages
