### ISSUE TITLE
RAW Data - EX fees on TPW Subtype (SS) (Waiting on Review and Approval)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14393]
### RAW data export for fees related to EX - Transportation and Public Works (TPW)

- Output CSV
- Data columns below

**Parameters:**
- Folder type is EX
- Subtype is Transportation and Public Works (TPW)
- Include all bills created since 10/1/23

Folderrsn | Billed Date | Bill # | Bill Amount | Paid Flag | Payment# | Payment Type | Payment Voided?
-- | -- | -- | -- | -- | -- | -- | --

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder 
### Here is the query  to get the required data:
SELECT ap.folderrsn, dategenerated BillGenerated, BillNumber, BillAmount, PaidinFullFlag PaidFlag
,ap.paymentnumber, vp.paymenttypedesc Paymenttype, ap.voidflag
FROM accountbill ab 
JOIN accountpayment ap ON ap.folderrsn = ab.folderrsn
JOIN validaccountpayment vp ON vp.paymenttype = ap.paymenttype
WHERE ab.folderrsn IN (SELECT folderrsn FROM folder WHERE foldertype = 'EX' AND subcode =50710) --13202747, 13203137
AND dategenerated >= TO_DATE('2023-10-01','YYYY-MM-DD')
ORDER BY ap.folderrsn;

### Here is the data as on 10/26/2023:-
[14393 - RAW Data - EX fees on TPW Subtype.xls](https://github.com/cityofaustin/atd-data-tech/files/13182992/14393.-.RAW.Data.-.EX.fees.on.TPW.Subtype.xls)

**Comment by TracyLinder** [comment]
I had Subha look for any unbilled fees for TPW subtype and she didn't find any. Closing this ticket.
