### ISSUE TITLE
Project: TxDOT Center-to-Center Data Sharing

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#144]
This project is an effort to establish traffic center-to-center (C2C) data sharing between the City of Austin and TxDOT by identifying existing open data feeds and ingesting them into each party's respective transportation management system. The goal is to enhance regional awareness of traffic conditions and promote better coordination among agencies managing traffic in central Texas.

### Resources
- [Project docs](https://drive.google.com/drive/u/1/folders/1USe__6Rh_tYHSaKNzJ_Ojh67G6qmDqBU)

**Comment by johnclary** [comment]
Notes from 21 May Meeting:

C2C (Center to Center)

===== 20 May 2019 meeting with TxDOT =====

API Feed for Drive Texas
- All of our road condition data that we supply out to waze
    - JSON feed live!
        - Cassie to request data feed. It was meant to share with DPS, DHS. Full road closures only
        - App Geo built API
        - HRCS road conditions > closures > (Highway Roads Conditions System)
            - The people that are actually entering it are in their local offices so in so many words the data is maybe bad or unreliable vs lonestar, which is “manned” properly to do the data management
        - limited set of data from lonesetar
        - HRCS and Lonestar have different “event” definitions so that’s why there is a limited set of data from lonestar
    - There’s also the C2C feed, which has all the lonestar information (incidents, maybe not lat/lon, )
        - “A direct response to tie traffic systems together” e.g. DFW and NCTCOGS
        - “Lonestar is just the metros”
        - All incident data
        - Including lane closures. Coded in lonestar and has a field in the feed
        - DMS messages are in C2C feed as well
        - “You just need to sign  a data sharing agreement” if you want the C2C feed
        - TxDOT webpage docs on the feed. #TODO: Ross is going to share a link
    - There’s a separate for sharing video (you have to be on network)
    - Travel Time data does not get exposed in any feeds (currently)


John N
> Use case for us is to have travel times from multiple sources for travel times
> Signal Timing, Operations info, in  standardized way would be good

**John C: #TODO: Share with TxDOT what we have on the open data portal. Aka data inventory
**#TODO: Jen to share Kelly Rula’s workzone data standard

R.e. funding:
- Brian: at  end of the project we need to be sharing some sort of data
- Cassie: We have a list of things we want to do for Drive Texas
- Jen: We’re exploring solutions to make video more accessible

Cassie: Going to talk to someone named Alex about getting ATX access for the C2C feed

**Comment by johnclary** [comment]
Next steps:
- John to update scope of work based on CTRMA template
- Waiting for C2C feed info from TxDOT

**Comment by amenity** [comment]
@johnclary - it sounds like this is an ongoing effort. Can you create sub-issues for the work you foresee? 

Going to unassign @mateoclarke from this Epic, but assign him and/or @sergiogcx as needed.

**Comment by johnclary** [comment]
Let's just close this out.
