### ISSUE TITLE
Add PCN and Employee ID fields to Employees Table on the HR Knack App

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14413]
Add PCN and Employee ID fields to the `Employee - Status: Active` list on this [page](https://atd.knack.com/hr#employees/).

**Comment by dianamartin** [comment]
# 4/16/2024
cc: @ChristinaTremel 
- Added fields on this "Employees" [page](https://atd.knack.com/hr#employees/).
- [x] `PCN`
- [x] `Employee ID`
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/d273f2a9-1ddb-46b4-962f-5e1290aed204)

**Comment by stephaniemoorer** [comment]
This looks to be complete. Can it be closed or does it need to be reviewed with HR team at sprint review?

**Comment by dianamartin** [comment]
# 6/26/24
Yes, I think this is okay to close.
