### ISSUE TITLE
Transit Stops: Want to connect people to other modes 1300 ft buffer

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#14423]

**Comment by Colemonj** [comment]
We already have access to transit stop data. It is a feature class located in the gisdm database named EXTERNAL.cmta_stops. 

There is a field within the data named STOP_TYPE that we can filter off of to identify whether it is a Bus Stop, Bus Bay, Rapid Station (Bust Rapid Transit Station), or Rail Station.
