### ISSUE TITLE
Discuss officers putting citation numbers in the app

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#1442]
@amenity -  I spoke to @johnclary in my 1:1 today about officers putting citations numbers in the app. I told John we are not sure if Jen and Lewis think it is essential to match citations to assignments,  and also my approach to link the two datasets in Power BI using the temporal grid. We thought we could do a 3 month trial where we did not ask officers to put citation numbers in the app, and try matching the two datasets in Power BI. Based on the quality of the data we see at the end of 3 months, we could either stay with that approach or ask officers to put citation numbers in the app. 
Creating this issue so we can talk about this next week.

**Comment by amenity** [comment]
@SurbhiBakshi @johnclary - Okay, sounds like a plan.

**Comment by amenity** [comment]
Backlog issue here: https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/1461
