### ISSUE TITLE
AISD Bus Stops	Want to connect people to other modes 500 ft buffer

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#14422]

**Comment by ATD-ZachB** [comment]
https://www.austinisd.org/planning-asset-management/school-maps-gis

**Comment by Colemonj** [comment]
I submitted an open data request for AISD school bus stop data, which the provided for us in the form of a shapefile. I saved the data in the following location,

G:\ATD\ATD_GIS\DTS_GIS_Workgroup_Support\DTS_Smart_Mobility_Office\Living_Streets_Program\Downloaded_Data\AISD Bus Stops\AllRegedRoutedStops
