### ISSUE TITLE
Create process to maintain Equity Analysis Zones (EAZs)

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#14439]
https://github.com/cityofaustin/vulnerability_weighting_map/tree/main

Involves us porting an ETL over to python with the predefined weights determined from the committee:
- Percent People of Color-5 
- Percent Black/Indigenous/Latinx-5 
- Median Household Income (low to high)-4 
- Percent receiving Food Stamps-2 
- Percent of people paying over 35% of monthly income on rent-2 
- Percent of people without broadband-2 
- Percent of households with fewer than one vehicle for working occupants 16 and older-1 
- Percent of people with a any type of disability-4 -Percent of people aged 65 or older-1

Update to new ACS and make it easier for our team to do this yearly.

**Comment by katelunceford** [comment]
@Charlie-Henry will follow up with Preston; Rebekka remembered he was going to follow up with Cole about several items on the list above

**Comment by Charlie-Henry** [comment]
emailed Preston and cc'd Cole

**Comment by katelunceford** [comment]
There are still questions around who uses the EAZ. Also, should we use the same parameters for new census data?
