### ISSUE TITLE
SD 2023 | M.D.1 - Number of people and number per 100,000 residents who are killed or sustain serious injuries in traffic crashes

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#1444]

**Comment by SurbhiBakshi** [comment]
Need to ask OPM to change language from 'per capita' to 'per 1,000 residents' to reflect industry standards, and as per Lewis's request.

**Comment by SurbhiBakshi** [comment]
Emailed Nicole and Dorr at OPM.

**Comment by SurbhiBakshi** [comment]
Meeting with Lewis and Xavier on 02/227

**Comment by SurbhiBakshi** [comment]
- [ ] email Lewis and Xavier a brief overview of OPM requirements and dataset standards
- [ ] look into the Number reqirement from OPM and let Lewis and Xavier know what I find out
- [ ] Lewis will email me reason why we want the metric language changed from per capita to per 100,000
- [ ] document reason for change in OPM Teams Channel
- [ ] Lewis and Xavier will send me a sample dataset with projected schema end of next week - March 6th?
- [ ] create a TEST dataset on the Open Data Portal with sample dataset
- [ ] check and test process to create performace card, segmentation with the sample dataset
- [ ] ask Lewis and Xavier to help with filling out metadata
- [ ] ask Lewis and Xavier for Story content
- [ ] Lewis and Xavier will send me the final dataset in mid-March
- [ ] create  Performance Card
- [ ] create  segmentation
- [ ] create Story
-
-

**Comment by SurbhiBakshi** [comment]
- [ ] Date field does not transform to Date and Time in Socrata
- [ ] Time field doe not transform to Date and Time
- [ ] Add Year field
- [ ] Add Month field
- [ ] 2 places after decimal enough for reporting metric?

**Comment by SurbhiBakshi** [comment]
Check in meeting scheduled for 03/16

**Comment by SurbhiBakshi** [comment]
Need feedback from Lewis and Xavier - 
- [ ] Method and Analysis for Performance Measure

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/045911e2-2052-47c8-ad37-86d728df7281)

**Comment by SurbhiBakshi** [comment]
Crash ID is no longer the main identifier.

**Comment by SurbhiBakshi** [comment]
Strategic Measure_Vision Zero

**Comment by SurbhiBakshi** [comment]
![Screen Shot 2020-04-02 at 3.02.45 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/9d379cf2-b1fe-46a1-a8d0-6ddd86b0d9fa)

**Comment by SurbhiBakshi** [comment]
![Screen Shot 2020-04-02 at 6.10.36 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5c91c03e-49c3-4e70-acc6-5b420b76b2cb)

**Comment by SurbhiBakshi** [comment]
(((to_text(`crash_year`) || '-') || to_text(`crash_month`)) || '-') || to_text(`crash_day_of_month`)))

**Comment by SurbhiBakshi** [comment]
![Screen Shot 2020-04-02 at 6.36.30 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/d5799fc2-4ace-451c-9748-784ac4905fb0)

**Comment by SurbhiBakshi** [comment]
to_floating_timestamp(
  (((to_text(`crash_year`) || '-') || to_text(`crash_month`)) || '-') || to_text(`crash_day_of_month`)
)

**Comment by mateoclarke** [comment]
Hey @SurbhiBakshi, can we circle up on this? It looks like we might be publishing duplicative datasets. Let me know when you have time to talk.

**Comment by SurbhiBakshi** [comment]
@mateoclarke, sure, will schedule some time on your calendar.

**Comment by SurbhiBakshi** [comment]
- All three main assets - dataset, performance measure, and story as listed in comment above are shared with OPM and made public. I have asked Nicole and Dorr at OPM to review. Will address changes as needed. 

- @johnclary , @mateoclarke and I discussed setting up an ETL process to update OPM dataset from the original VZE dataset. 

- Will include a link to the VZE viewer under the Additional Measure Insights when it is ready to go public.
