### ISSUE TITLE
M.C.1.a -  Number and percentage of residential permits within a half-mile of the Transit and  Bicycle Priority Networks

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#1445]
**Full Description** - Percent of population (housing units) and employment (commercial square footage) within a quarter-mile and half-mile of a high-frequency transit stop, within a half-mile of the All Ages and Abilities Bicycle Network

[IACC Reporting #121 and #122](https://data.austintexas.gov/stories/s/Compact-and-Connected/jqwk-xf8g)

 **[Document](https://docs.google.com/spreadsheets/d/1Acu6vASavayOxmwLNWbQKo08P1OGW12ozC7v1f4QQXY/edit?usp=sharing)**

All assets are due Sept 21, 2020

- [ ]  Upload Dataset
- [ ]  Measure Card
- [ ]  Segmentation
- [ ]  Story page

**Comment by SurbhiBakshi** [comment]
**Population** 
- [ ] Percent of population (housing units) within a quarter mile of high frequency transit stops
- [ ] Percent of population (housing units)  within a half mile of high frequency transit stops
- [ ] Percent of population (housing units) within a half mile of All Ages and Abilities Bicycle Network

**Employment**
- [ ] Percentage of employment (commercial square footage) within a quarter mile of high frequency transit stops
- [ ] Percentage of employment (commercial square footage) within a half mile of high frequency transit stops
- [ ] Percentage of employment (commercial square footage)  within a half mile of All Ages and Abilities Bicycle Network

**Comment by SurbhiBakshi** [comment]
Question - 
- [ ] Are we looking at a few years or just 2019 as a base year?

**Comment by amenity** [comment]
This is potentially a replacement for #1443 .

**Comment by SurbhiBakshi** [comment]
Align with DSD on methodology for work - especially - 1/2 mile or 1/4 mile for corridor

**Comment by SurbhiBakshi** [comment]
From Nicole's email - 

- M.C.1 - Split approved – PLEASE NOTE NEW MEASURE IDs
- M.C.1.a -  Number and percentage of residential permits within a half-mile of the Transit and  Bicycle Priority Networks
- M.C.1.b - Number and percentage of non-residential commercial permits within a half mile of the Transit and Bicycle Priority Network
- Both reported in Wave 2
- Nicole will update language in measure edit request to reflect this wording
- Data will reflect what is measured as part of IA - See #121: https://data.austintexas.gov/stories/s/Compact-and-Connected/jqwk-xf8g
- ATD will review methodology with DSD who is reporting EOA.C.4
