### ISSUE TITLE
Vacancy Report Feedback - 10/30/23

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#14460]
Jennifer W.
HR

Emailed us with feedback comments.

```
Hello you two. I have a couple wish list items for the VR in Knack. 
Any chance any of these can be tweaked before 1 when I meet with the team? Otherwise no worries at all!!! 

1.	Under “PCN Status” Column:
Add “Offer Accepted – Upcoming Effective Date”

2.	Under “Filled” Column:
Remove JW & one of the External 
                Should be just two options:  
•	Internal
•	External

3.	Any way we can “freeze pane” on the first row? 

4.	I see the “current Date” Column isn’t updating to current date.
Can we add an option for this to be a rolling live current date? 

5.	What is up with the “Vacant Temp” Column? 

6.	When adding a new PCN (New recruitment/vacancy) to the log:
Have space for “Previous Employee”
Have space for “Assigned To” 

7.	I think we can eliminate the following Columns
Fund
Vacant TEMP
Notes TEMP
Type

8.	How do we add a hiring manager? I am finding a few that I cannot select. 
John F.
Susan D.

**Comment by dianamartin** [comment]
# 10/30
I replied

1.	Under “PCN Status” Column:
Add “Offer Accepted – Upcoming Effective Date”  - `Updated`

2.	Under “Filled” Column:
Remove JW & one of the External - `Updated`
                Should be just two options:  
•	Internal
•	External

3.	Any way we can “freeze pane” on the first row? 
`Unfortunately, it’s not like Excel. There’s not function for that. We can always improve the table view you’re on.`

4.	I see the “current Date” Column isn’t updating to current date.
Can we add an option for this to be a rolling live current date? 
`This is an automatic feature. You’ll see it has yesterday’s date. It runs overnight and is updated the following day.`

5.	What is up with the “Vacant Temp” Column? 
`These were fields for me while I was backfilling information I think`

6.	When adding a new PCN (New recruitment/vacancy) to the log:
Have space for “Previous Employee”- `Added the “Previous PCN Employee”`
Have space for “Assigned To” – `Added the “HR Assigned to”``

7.	I think we can eliminate the following Columns
Fund - Removed from table view
Vacant TEMP – `Removed from table view`
Notes TEMP - `Removed from table view`
Type - `Removed from table view`
`From which view the HR view or the All View ?`

8.	How do we add a hiring manager? I am finding a few that I cannot select. 
John F.
Susan D. 
>A quick way is to click
>- Add PCN
>- Click “Add a new option” and then add the Hiring Manager’s information there. Then you’ll be able to select them without filling out a new PCN form.

**Comment by ChristinaTremel** [comment]
Added `Modified Date` and `Modified By` record rules to the following fields on the **"Vacancy Report | HR"** page
- AssistantDirectorDeputy
- Division
- Budgeted Title
- Budgeted FTE
- Vacant Date
- PCN Status
- HR Notes
- Previous Employee

![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/1a0c8359-ebe3-45a7-bd8f-ea7fddd01e7e)

**Comment by dianamartin** [comment]
# 10/30
Jennifer replied
>Y’all are rock stars. Thanks for jumping on this. I will bug you at our next meeting on the follow ups. 
Thanks again, I couldn’t do this without ya!!
