### ISSUE TITLE
Create a single AGOL layer of all Moped components

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#14477]
Create an AGOL feature service which combines Moped component points and lines form [these layers](https://austin.maps.arcgis.com/home/item.html?id=1c084c8756a84e6db7e2796c98c850a2) into a single layer of line geometries.

**Comment by andrewshensky** [comment]
Below is a link to the current test output from FME.
https://austin.maps.arcgis.com/home/item.html?id=a89666b7cef94aa3bac03da68d3af8a4

**Comment by johnclary** [comment]
@andrewshensky i was able able to update our ETL pretty easily by adding a `line_geometry` column to our DB view. right now i just pushed all the combined line data to our existing line layer (although this will get overwritten by the production ETL later tonight):
https://austin.maps.arcgis.com/home/item.html?id=1c084c8756a84e6db7e2796c98c850a2

would you be able add another polyline layer to our existing feature service? it's fine if you need to overwrite that existing feature service, or even make a new one. the goal is to have three layers:
- points (multipoint geomtery)
- lines (polyline - line features only)
- combined (polyline - line + lineified points)

**Comment by johnclary** [comment]
i sent this to NW as well. this is a 5 meter radius which is quite a bit smaller than the interim viewer:

<img width="810" alt="Screenshot 2023-11-02 at 4 25 14 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/d0b1939a-ebb1-45d9-a728-8de022316a1a">
<img width="707" alt="Screenshot 2023-11-02 at 4 25 09 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/4f25bebb-6fe7-4a5a-a9c0-a895d6f8edd5">
