### ISSUE TITLE
Define Data Science options for DTS Service Request

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#14499]
How might we 
- formalize how data science work is requested
- increase visibility of the DTS Data Science services

@Charlie-Henry ☝🏻 please extend/re-write to your heart's content!

**Comment by Charlie-Henry** [comment]
Love it <3!

**Comment by amenity** [comment]
We want to encourage that something new as opposed to doing more IT support. 

- [ ] Add "Data Analysis or Visualization" as a "What do you need help with" radio button 

Conditional fields: 
**Option 1*
_Leave everything open-ended to see_
- "Describe your request" - long text

**Option 2**
_Learn why_
- "What questions/metrics do you want to answer/track?", or
- "Who will use this analysis or visualization, and how will it impact their work?" 

_Learn what_
- "What data source(s) would you like to use?"

_Learn when_
- Something about how often the data changes or how frequently the analysis will need to be rerun or updated

_Assess urgency_
- "If you need this by a certain time, when and why?"

In the future, we may want to consider 
- Troubleshooting (currently submit as a bug report; maybe would continue - this works)
- Access to Premium PowerBI workspace
- Add a "Data Source" field - dropdown or URL

**Comment by amenity** [comment]
- [ ] Add "Data Analysis or Visualization" as a "What do you need help with" radio button 

Conditional fields: 
"Describe your request" - long text
Help text: 
_Consider questions you'd like to answer or metrics you'd like to track. What audiences do you have in mind, and how would this impact their decisions or workflows?

**Comment by Charlie-Henry** [comment]
@amenity @katelunceford might be good when this work is done to put something about it in the DTS newsletter?

**Comment by amenity** [comment]
I like that idea, @Charlie-Henry! Do y'all have any tweaks on the wording before I add it to the implementation issue?

**Comment by Charlie-Henry** [comment]
Looks excellent thank you!!

**Comment by katelunceford** [comment]
Looks good to me, @amenity! Also love your idea to add it to the newsletter @Charlie-Henry!
