### ISSUE TITLE
Create page to manage SSPR Template Priorities

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14504]
- Create page for HR staff to manage SSPR Template Priorities

**Comment by dianamartin** [comment]
# 11/1
During our HR Sprint Review meeting

## Created Pages
- [x] Created new page `Priority Templates`
- [x] Added `sspr_priority_templates` table
- [x] Added a "new Priority Template" form
- [x] Added an "Edit Priority Template" form

## Created Links
- [x] Created a link to "Priority Templates" from the HR Forms>SSPR Details page, called it `Manage Priority Templates`
- [x] Added a link back to "HR Forms>SSPR Details page" from `SSPR Management | Admin`
- [x] Updated icon to `SSPR Management | Admin`
- [x] Added a link back to "HR Forms>SSPR Details page" from `Manage Priority Templates`
- [x] Updated icon to `Manage Priority Templates`

## Improved User Experience
- [x] Updated Staff Forms - Keyes talked about how new users didn't know the "Details icon" we normally use is a link
- [x] Added new link descriptions
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/cc16a65c-2c44-433b-bc02-8fbd79349481)
- [x] Updated context language
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/22c352ef-0e0e-434f-abdf-715673148efc)
