### ISSUE TITLE
Testing Scenarios | RPP Portal

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1450]
### Reviewing FAQs

- [ ] Go to [Main page](https://atd.knack.com/parking#rpp/) 
- [ ] Click `Help`

### RPP Permit

- [ ] Go to [Main page](https://atd.knack.com/parking#rpp/) 
- [ ] Click `Apply for a New Permit`
- [ ] Click `Start Application`
- [ ] Fill out Part 1| Applicant Information (as customer you should receive an email, so make sure it's your email you use)
- [ ] Fill out Part 2 | Required Documents & Permit Information
- [ ] Fill out Part 3 | Vehicle Information 
- [ ] Review Application
- [ ] Review Invoice page
- [ ] Review Payment Options page

### Day Pass

- [ ] Go to [Main page](https://atd.knack.com/parking#rpp/) 
- [ ] Click `Request Day Passes`
- [ ] Fill out Part 1| Applicant Information 
- [ ] Fill out Part 2 | Permit Information
- [ ] Review Application

## RPP Staff Workflow

- [ ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [ ] Click `All Permit Applications`
- [ ] Review application you created as customer
- [ ] Add `RPP Zone` closest to address selected (yellow highlighted box)
- [ ] Add `Name`, select the customer you created to associate them to their application (yellow highlighted box)
- [ ] Click the `Permits/Day Passes` field to see more details of the application
- [ ] Change `Status` to REVIEWED | NEEDS PAYMENT (as customer you should receive an email, so make sure it's your email you use)
- [ ] Click `Issue` button to add permits and make test transactions

## Review Permits & Transactions 
- [ ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [ ] Click `Permits & Transactions`

## Review Advanced Search
- [ ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [ ] Click `Advanced Search`

## Review Customer page
- [ ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [ ] Click `Customers`

## Review Addresses page
- [ ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [ ] Click `Addresses`

## Review RPP Zones
- [ ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [ ] Click `RPP Zones`

## Review Reports
- [ ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [ ] Click `Reports`

**Comment by dianamartin** [comment]
@moorerst @SurbhiBakshi Please leave any comments on weird things you notice or suggested changes.

**Comment by SurbhiBakshi** [comment]
## Customer Workflow

### Reviewing FAQs

- [x] Go to [Main page](https://atd.knack.com/parking#rpp/) 
- [x ] Click `Help`

### RPP Permit

- [x] Go to [Main page](https://atd.knack.com/parking#rpp/)  - an embedded web map would be a good addition, 
- [x] Click `Apply for a New Permit`
- [X ] Click `Start Application`
- [X ] Fill out Part 1| Applicant Information (as customer you should receive an email, so make sure it's your email you use) - not sure if this is on purpose, my name is always All Caps.
- [x] Fill out Part 2 | Required Documents & Permit Information
- [x] Fill out Part 3 | Vehicle Information 
- [x] Review Application
- [x] Review Invoice page - Not sure why the drivers license is an image, and the proof of address is a link. 
- [ ] Review Payment Options page
The Home button on the Payment Options page takes me to a login page for RPP, and not the main application page. 


### Day Pass 

- [ ] Go to [Main page](https://atd.knack.com/parking#rpp/) 
- [ ] Click `Request Day Passes`
- [ ] Fill out Part 1| Applicant Information 
- [ ] Fill out Part 2 | Permit Information
- [ ] Review Application

## RPP Staff Workflow

- [x ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [x ] Click `All Permit Applications`
- [ x] Review application you created as customer
- [x ] Add `RPP Zone` closest to address selected (yellow highlighted box)
- [ ] Add `Name`, select the customer you created to associate them to their application (yellow highlighted box)
- [x ] Click the `Permits/Day Passes` field to see more details of the application
- [x ] Change `Status` to REVIEWED | NEEDS PAYMENT (as customer you should receive an email, so make sure it's your email you use)
- [ ] Click `Issue` button to add permits and make test transactions - An Issued date which gets filled when permit status gets changed to Completed - Permits Issued would be useful later. Is expiry date getting calculated from submitted date or completed date?
When I am on the Issue page for day pass, the cost is 15$
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/7850db42-a8c1-4d7f-8abc-9036df16f5e9)
 Modal Title should be Issue Day Passes 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/e5d8764b-d3d6-4431-8f24-549ff8c698fa)


## Review Permits & Transactions 
- [x ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [x] Click `Permits & Transactions`

## Review Advanced Search
- [x ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [x ] Click `Advanced Search` - Could you include Customer Name ? see that it is in the next page.

## Review Customer page
- [x ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [x ] Click `Customers`

## Review Addresses page
- [x ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [x ] Click `Addresses`

## Review RPP Zones
- [x] Go to [Main page](https://atd.knack.com/parking#home/) 
- [ x] Click `RPP Zones` - Reduce field width for 'Maz Resident Decals per household' of possible. Same for Max Visitor Hang Tag per Household.
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/2980665f-2409-4c79-a919-76f75ee185cf) 

## Review Reports
- [x ] Go to [Main page](https://atd.knack.com/parking#home/) 
- [x] Click `Reports`

A bar graph showing how many permits and passes were issued by District would be cool to see.

**Comment by dianamartin** [comment]
@SurbhiBakshi I think I'd need help on that bar graph..

**Comment by moorerst** [comment]
Customer Workflow

Reviewing FAQs
 
- [ ] Go to Main page
- [ ]  Click Help

RPP Permit
 
- [ ] Go to Main page
- [ ]  Click Apply for a New Permit
- [ ]  Click Start Application

 

- [ ] Fill out Part 1| Applicant Information (as customer you should receive an email, so make sure it's your email you use)

- [ ]  Fill out Part 2 | Required Documents & Permit Information
- [ ]  Fill out Part 3 | Vehicle Information
- [ ]  Review Application
- [ ]  Review Invoice page

 Review Payment Options page

Day Pass

- [ ]  Go to Main page
- [ ]  Click Request Day Passes

 

- [ ] Fill out Part 1| Applicant Information
- [ ]  Fill out Part 2 | Permit Information
- [ ]  Review Application

RPP Staff Workflow

 

- [ ] Go to Main page
- [ ]  Click All Permit Applications
- [ ]  Review application you created as customer
- [ ]  Add RPP Zone closest to address selected (yellow highlighted box)

 

- [ ] Add Name, select the customer you created to associate them to their application (yellow highlighted box)
- [ ]  Click the Permits/Day Passes field to see more details of the application
- [ ]  Change Status to REVIEWED | NEEDS PAYMENT (as customer you should receive an email, so make sure it's your email you use)
- [ ]  Click Issue button to add permits and make test transactions

Review Permits & Transactions

 

- [ ] Go to Main page
- [ ]  Click Permits & Transactions

Review Advanced Search

 

- [ ] Go to Main page
- [ ]  Click Advanced Search

Review Customer page

 

- [ ] Go to Main page
- [ ]  Click Customers

Review Addresses page

 

- [ ] Go to Main page
- [ ]  Click Addresses

Review RPP Zones

 

- [ ] Go to Main page
- [ ]  Click RPP Zones

Review Reports

 

- [ ] Go to Main page
- [ ]  Click Reports

**Comment by moorerst** [comment]
@dianamartin when testing purchasing Day Passes only no RPP decals or hang tags I get an error that Number of Hang Tags and Number of Decals is required.

**Comment by dianamartin** [comment]
@moorerst I just changed the whole application process. I haven't gone and testing only purchasing day passes yet. So it's probably not configured properly yet. Did you just test it now (where the Required Documents) are on a separate form?

**Comment by moorerst** [comment]
@dianamartin tested just now with them all on one form. Let me know when the new configuration is ready for testing. Thanks

**Comment by moorerst** [comment]
@dianamartin when testing purchasing Day Passes only on the Submit and Review page the totals are not consistent. For 18 day passes total shows $19.49 (18x1.08 = $19.44). T he Final Total shows $19.48

**Comment by moorerst** [comment]
@dianamartin 
![image](https://user-images.githubusercontent.com/56606465/75275222-cf871180-57c9-11ea-9f8a-c517d3adfae3.png)

**Comment by moorerst** [comment]
@dianamartin For Payment Options/Phone Payment can the phone number be included?

**Comment by moorerst** [comment]
@dianamartin I'm confused by the Required field Total Day Passes in the Add Permit section
![image](https://user-images.githubusercontent.com/56606465/75279842-f5b0af80-57d1-11ea-9302-3c99b4a19c27.png)

**Comment by dianamartin** [comment]
@moorerst You need to enter in the "# of Day Passes" requested on the application, so in your screen shot it should be: `18`.

**Comment by dianamartin** [comment]
@moorerst I'm addressing the payment discrepancy on the day passes. I think it might have some back end stuff with the tax amount.

**Comment by dianamartin** [comment]
@moorerst For Payment Options/Phone Payment can the phone number be included?

For this one, are you meaning the footer area or the actual Payment Options page?

**Comment by moorerst** [comment]
@dianamartin Both the footer and the actual Payment Options page. 
Per Steve: Right now the # is 512-974-2891. It may change in the near future though

**Comment by dianamartin** [comment]
@moorerst The use of a phone number is not anywhere on the RPP public pages, I think we'd need to get clarity on how they want to be contacted before we put it on the payment page.

**Comment by moorerst** [comment]
@dianamartin on the By Address page Completed is the only status option. Should all status options be available?

**Comment by moorerst** [comment]
@dianamartin I completed the testing scenarios

**Comment by dianamartin** [comment]
@moorerst I just put "All" and "Completed". I think I needed more information from the RPP group on what they want to see here.

I'll close this issue though, thanks for testing!
