### ISSUE TITLE
Maximo, Pavement Ops: PMIS segments missing

### ISSUE THREAD

**Issue by YakshDipa** [cityofaustin/atd-data-tech#14512]

**Comment by YakshDipa** [comment]
Sent email.

**Comment by adry-martinez** [comment]
[Segments Missing Maximo ID.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2NXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b80f733bb7d504afd13edee1e0015679bcda6d3f/Segments%20Missing%20Maximo%20ID.xlsx)

**Comment by adry-martinez** [comment]
Last correspondence sent to Anna Maijala, Bryan Thompson, @andrewshensky regarding loading segments in Maximo sent on 11/13.

**Comment by andrewshensky** [comment]
Bryan and I have a meeting scheduled with Reza to discuss this on 11/30

**Comment by dianamartin** [comment]
@andrewshensky What's the status of this effort?

**Comment by andrewshensky** [comment]
@dianamartin I believe this one can be closed out. If I remember correctly I worked with Bryan on this one to reprocess some of the segments to get them populated with the proper IDs from Maximo
