### ISSUE TITLE
Bulk Import of SSPR Priority Templates and Goals/Program/Activities

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#14521]
This ask is to assist the SBO divisions that are coming from legacy PWD. They have about 230 staff and would like to assist the supervisors, superintendents and Division Managers with this task. 

# Plan
- Hannah to email SBO instructions on how to build out the Goals & Priorities
- SBO to confirm their reporting structure for accuracy
- SBO to provide data
- DTS to test load in the information
- SBO to finish all the entries for Priorities per position and division area
- DTS to load in the rest of the records

**Comment by dianamartin** [comment]
# 11/2
Reiner said they've gotten one area completed and we can use that to test load into the system. 
>We've created a V.1 for the UER team. Rows 14-24 would be identical for all SBO Tech I-III and rows 1-8 would be per work group.

>Here is the link with only the first tab completed to save us if there are major issues/concerns before building for each of the 8 groups
- 4 priorities for Tech I; 5 priorities for Tech II and III

**Comment by dianamartin** [comment]
# 11/8
Had a meeting with "SBO SSPR standardization workshop" 
>they were This will be a workshop to review and finalize standardized SSPRs for SBO titles (likely Tech I-III)

>Goal is to have a final product to HR + DTS by COB on 11/08 so they can upload templates and save our supervisors hours of individual entry. More details to come!

Dave emailed me
>Diana & Christina:
The following SBO SSPR priority templates are attached:
>- `Priorities_SBO - All`: These priorities apply to all SBO personnel, from Tech I through Supervisor.
>- `Priorities_SBO - Tech 2` – Heavy Equipment Commercial Vehicle Operation – This workbook contains one priority (Priority 5) for SBO Tech II personnel.
>- `Priorities_SBO - Tech 3` – Heavy Equipment Commercial Vehicle Operation – This workbook contains one priority (Priority 5) for SBO Tech III personnel.
>- `Priorities_SBO - Crew Lead`: This workbook contains two priorities specific to SBO Crew Leads.
>- `Priorities_SBO - Supervisor`: This workbook contains three priorities specific to SBO Supervisors.
I will send workgroup goals, programs, and activities under a separate cover.

**Comment by dianamartin** [comment]
# 11/8
- Loading templates into the system
- [x] `Priorities_SBO - All`
- [ ]  `Priorities_SBO - Tech 2` – Heavy Equipment Commercial Vehicle Operation 
- [ ] `Priorities_SBO - Tech 3` – Heavy Equipment Commercial Vehicle Operation 
- [ ]  `Priorities_SBO - Crew Lead`
- [x]  `Priorities_SBO - Supervisor`

**Comment by dianamartin** [comment]
# 11/13

On 11/9, Met with HR team to help them with the steps on how to bulk create SSPRs for the SBO divisions. They completed the task. 

Hannah said on 11/13
>HR has finished the creation and priority sections for SBO SSPRs. Do you think we are still on track for SBO to start their meetings tomorrow?

**Comment by dianamartin** [comment]
# 11/13
The spreadsheet `SBO Employee Census Report 11-8-2023 with Workgroup` shows the various work groups

The spreadsheet `SBO workgroup goal programs activities` shows the
- Department/Division Goals related to position
- Department/Division Program(s) related to position
- Department/Division Activity(s) related to position

Divisions:
Division Name | Workgroup | # of Employees | Status
-- | -- | -- | -- | 
Utilities and Structures | Utility Excavation Repair | 46 | 
Utilities and Structures | Concrete Repair and Construction | 34 | 
Utilities and Structures | Bridge Inspection and Repair | 6 | 
Pavement and Infrastructure | Mill and Overlay | 29 
Pavement and Infrastructure | Seal Coat | 21 | 
Pavement and Infrastructure | Fog Seal | 18 
District Maintenance | District Maintenance | 70 | 
District Maintenance | Downtown Enhancement | 5 | 

## Other Imports
- [ ] Jermaine B.
- [ ] Michael G.
- [ ] Clay R. 
- [ ] Lisa K.

**Comment by ChristinaTremel** [comment]
@dianamartin are we good to close this? I think we can with SSPRs being due last Friday! 🥳

**Comment by dianamartin** [comment]
@ChristinaTremel I think so, but we can ask Hannah too.

**Comment by dianamartin** [comment]
# 1/17/24
Christina and I agree this can be closed.
