### ISSUE TITLE
License Agreements & Encroachments – ATP

### ISSUE THREAD

**Issue by GimnichD** [cityofaustin/atd-data-tech#14539]
License Agreements & Encroachments – ATP is looking for a GIS layer or spreadsheet identifying license agreements and encroachments (private owners use of the ROW) along the Light Rail route. The updated route can be found here in ATP’s data portal. I believe this information is handled by the Land Management division.

**Comment by GimnichD** [comment]
[Parcels_Adjacent_to_Light_Rail.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK09nQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe9fafc81e8117a5ab50dbaebd11dd234564c8ff/Parcels_Adjacent_to_Light_Rail.xlsx)

**Comment by GimnichD** [comment]
Here is the spreadsheet with the adjacent TCAD parcels, but with ALL the data, including joined address info.

[Parcels_Adjacent_to_Light_Rail_full_data.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUt4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e72c6ab53645020cabaedd98e14df61cea2fc376/Parcels_Adjacent_to_Light_Rail_full_data.xlsx)

**Comment by TracyLinder** [comment]
I took a look at this data and it's not quite what is needed. I scheduled a meeting with David to discuss on Monday on 11/13

**Comment by TracyLinder** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/2b4ef688-d8f5-4f0a-bc03-97bc732c4658)

**Comment by TracyLinder** [comment]
https://stage.travis.prodigycad.com/property-detail/262751/2023

**Comment by GimnichD** [comment]
This was assigned to Bryan Thompson at Capital Delivery Services who has fulfilled the request.
