### ISSUE TITLE
Expire LC when Insurance Expires (LP) - (Ready for UAT on Prod) 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14545]
### When the bond expiration date or insurance expiration date (folder info) expires/lapses, the system should update the LC folder status to Expired. 
- Related to #4070, #10849, #10850

**Acceptance Criteria** 

- System should run a daily batch to check if Bond Expiration Date or Insurance Expiration Date Folder info in LC folders have dates in the past. 
- If they do, system should change the folder status of those LC folders to Expired.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @vschandramouli In the AC it is mentioned that "In the batch that expires LC folders (changes folder status to Expired based on Bond Dates), a new functionality needs to be added", I'm not able to find the existing batch job that expires LC based on bond dates. There is one job that expires LC but it is based on the folder expiration date. Please let me know whether I need add the new functionality in that job or create a new one to expire LC based on insurance expiration date

**Comment by TracyLinder** [comment]
Update: We can't find an existing job or procedure that expires LC based on the bond expiration date. We're going to create a new job that looks for both the insurance and bond expiration dates. @vschandramouli will update the AC

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified on Dev and created Test deployment request , SCTASK0387951

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified by running the job on Test , There were 191 records. The Job ran sucessfully and updated all the folders

**Comment by TracyLinder** [comment]
### UAT - Pending
We added an expiration date to folder 10021515. We can check on Monday if it expired the folder.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Devops changes deployed to prod, created request for manual deployment, SCTASK0391579

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Ready for UAT on Prod

**Comment by KyleErich** [comment]
@Nadin-Nader @Lpriya-LIT UAT approved in Prod. Thank you!

**Comment by Nadin-Nader** [comment]
Closing as this was approved on PROD
