### ISSUE TITLE
Deploy script to batch Redefault Responsible Party people type (SS) (on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14544]
### After implementing #13576, all existing Responsible Party people type records need to redefault to add the new People Info fields

**Comment by TracyLinder** [comment]
Nate is speaking with CTM to discuss a solution for this. It needs to happen ASAP.

**Comment by Nadin-Nader** [comment]
@SubhaShroff Spoke to Jenice and she said that the script would have to be created by us and ran by the DBAs. Please go ahead and create the redefault script for this and i can send it to Yuan

**Comment by KyleErich** [comment]
In the meantime while we wait for this, does anyone know how to redefault an individual one of these people records? I searched for a Redefault icon on a Responsible Party people record in AMANDA and could not find it.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Here are the scripts.
[ATD-14544 INSERT Script.txt](https://github.com/cityofaustin/atd-data-tech/files/13323283/ATD-14544.INSERT.Script.txt)
[ATD-14544 Rollback Script.txt](https://github.com/cityofaustin/atd-data-tech/files/13323279/ATD-14544.Rollback.Script.txt)

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the CTM DBA Team to be ran on DEV under **SCTASK0371211**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I verified the script execution on DEV, few Responsible Party were left. I had to update the script with Right join to include those people records also. Please create another DEV deployment with these latest scripts.
[ATD-14544 INSERT Script.txt](https://github.com/cityofaustin/atd-data-tech/files/13358011/ATD-14544.INSERT.Script.txt)
[ATD-14544 Rollback Script.txt](https://github.com/cityofaustin/atd-data-tech/files/13358012/ATD-14544.Rollback.Script.txt)

**Comment by Nadin-Nader** [comment]
@SubhaShroff the new deployment has been sent to the CTM DBA Team to be deployed to DEV under **SCTASK0371872**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I verified it on DEV and now it looks good. 
Please send the script for TEST promotion. Thnk you.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the CTM DBA Team to be ran on TEST under **SCTASK0372191**

**Comment by SubhaShroff** [comment]
@Nadin-Nader I verified it on TEST. Its ready for UAT on TEST.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the CTM DBA Team to be deployed on PROD under **SCTASK0374761**

**Comment by SubhaShroff** [comment]
@Nadin-Nader Since Kyle approved this ticket on Teams, Please send these scripts to run on PROD.
![image](https://github.com/cityofaustin/atd-data-tech/assets/51680715/b56bdaf7-cc3f-41b3-b747-7dc5263d42f3)

[ATD-14544 INSERT Script.txt](https://github.com/cityofaustin/atd-data-tech/files/13504766/ATD-14544.INSERT.Script.txt)
[ATD-14544 Rollback Script.txt](https://github.com/cityofaustin/atd-data-tech/files/13504767/ATD-14544.Rollback.Script.txt)

Thank you.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This script is executed on PROD and I have verified it with my SQL query. This is up for UAT on PROD. Thank you.

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff UAT approved. Thank you.

**Comment by Nadin-Nader** [comment]
Closing as it has been approved by Kyle
