### ISSUE TITLE
Maximo Report Request [New] Overlay Prep Reporting Data (sealcoat scoping included)

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#14546]
End game: Build out a series of dashboard to update for Pavement Ops DM and Asst Dir. on how pavement is doing with their prep and service plan work. Update every month, but ideally every week. Maximo data sync'd to Power BI to pull dashboards in one fell swoop. AD Hershaw wants to track prep work.

Requesting a report to view Crack Seal and Level-Ups (prep work):

- [ ] total lane miles of prep work was completed by week and month
- [ ] count of street segments of prep work
- [ ] Looking at parent work order in 4COMP status to count as work completed.
4COMP with LEVEL UP spec entered = completed
4COMP with LEVEL UP spec zeroed = no level up required

Raw data to include:
- [ ] segments, 
- [ ] days, based off of most recent prep date status
- [ ] status,
- [ ] lane miles

Sealcoat - Parent
Prep, LU - Child
Prep, CS - Child
Prep, SW - Child

### DTS Maximo
<img width="1060" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmM5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5e3c2c0c8586a75a3e46198ecd88e97bd7be5b3/image.png" alt="image.png" />

**Page 1 - Level Up Prep**
day, statusdate, WONUM, Description, CRACKSEALPROGRAM PREP-LU, persongroup, STATUS, # OF ASSETS, # of level-ups, lane miles (actual length x actual width) **see completed lane miles report for calculation as needed**
<img width="1281" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMms5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e82d5b5cf0dfa8f19d3fa6dc29841d80a232158/image.png" alt="image.png" />

**Page 2 - Crack Seal Prep**
day, statusdate, WONUM, Description, CRACKSEALPROGRAM PREP-CS, persongroup, STATUS, # OF ASSETS, # of boxes used based on MATTRANS
<img width="863" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnc5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--857da135c5da78cf9b2d3fb316b932437cdbcbd6/image.png" alt="image.png" />

**Comment by dianamartin** [comment]
# 1/24/24
- Adry is compiling all the data from Pavement Ops stakeholders
- Will sent data over to CTM to request report

**Comment by adry-martinez** [comment]
### 1/31/24
Discussed with CTM Nick O. on data requirements for creating BIRT report, currently in progress.

**Comment by adry-martinez** [comment]
### 2/5/24 A couple of Maximo report/data needs

<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWdyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db7e1c18dd0b88761978d7bec1fd43549f437f57/image.png" alt="image.png" />

Crack seal only WOs done 
Level up only done
No prep done
Prep completed (both crack seal and level-up done)

**Comment by rebekkabry** [comment]
**Reporting Insights**
_Meeting with Adry and Rene_

- Currently using SBO tracking screen to find data. 
- Currently maybe issues with the workgroup assignments 
- We already have a report on PM crack seal (type 2 see below) 
- Concern: Changing hierarchy of the work order that they have right now 
- Current Process: all the children need to be 4 status before they can close their seal coat project. (see hierarchy) 
  - Andre E: investigate plans on the hierarchy and work order plans. assumed they no longer want connected because different groups will be responding. There will be new groups for each task, ie. level up, fog group, seal coat group, etc. 

Adry is working on what data is needed on the report 
- We currently only have crack seal. 
- There are two type: 
  - 1. prep for the seal coat (includes the level up) 
  - 2. PM crack seal (only crack seal effort) 

**Look Ahead and Plan**
- get with Andre to understand new process (should be an issue already addressed for this) 
- training may need to be put on hold for field crew until Andre has signed off

**Comment by rebekkabry** [comment]
@rebekkabry Follow up with Adry on the needs on this.

**Comment by adry-martinez** [comment]
@ganesh-kamarapu 

please update **SBO Crack Seal Lane Miles Progress Report** to reflect ONLY PREP work orders as specified in CRACK SEAL PROGRAM field in Specs., and update Report Title to **SBO PREP Crack Seal Lane Miles Progress Report**

**Comment by adry-martinez** [comment]
@rebekkahbry

we will need to recommend to SBO if it makes sense to consolidate all PREP reports to ONE report (if it does not slow down Maximo) and all PM reports to ONE report or if they want to consolidate by Work Groups instead, meaning:

**SBO OVL Performance Measure Report**
- Page 1: Overlay Whereabouts (Work Orders in 2, 3, and 4COMP status in the last 48 hours)
- Page 2: Completed Lane Miles
- Page 3: Completed Milling
- Page 4: Completed Paving

**SBO SLCT Performance Measure Report**
- Page 1: SLCT Whereabouts (Work Orders in 2, 3, and 4COMP status in the last 48 hours)
- Page 2: Completed PREP Crack Seal Lane Miles
- Page 3: Completed LEVEL UP Lane Miles
- Page 4: Completed SWEEPING

**SBO PM Performance Measure Report**
- Page 1: Fog Seal and Crack Seal PM Whereabouts
- Page 2: Completed PM Crack Seal Lane Miles (see SBO PM Crack Seal Lane Miles Report)
- Page 3: Completed PM Fog Seal Lane Miles

**Comment by rebekkabry** [comment]
Discuss performance measure report options during next stakeholder meeting

**Comment by rebekkabry** [comment]
- [ ] @rebekkabry  Discuss with Dave. A to get approval of change, Pavement stakeholders do not have any recommendations as they do not use for reporting....Dave handles the reporting.

**Comment by rebekkabry** [comment]
# 10/14/24 

- Holding on Hierarchy revamp pending Andre E. return 
- To support reporting needs from (OCE/Ron/etc) we will create Overlay Performance Pull. 
- NOTE: [SBOPVMT Overlay Lane Miles Progress Report (Monthly Operational Performance Measures)](javascript:sendEvent('openreport','m87a38418-content','sbo_overlay_lane_miles.rptdesign$SBO_WOTRK$1354')) report is active in maximo, but it does not have completed dates or reference the MILL portion of the projects. 
- Build out a query and report of the following: (noting that -MILL currently does not seem to track any specifications or materials) 
- Will tie to a Start Center (previous conversations of building for team) 
![image](https://github.com/user-attachments/assets/7aead717-35ef-41df-bbad-6a6d67be3660)

**Comment by GaneshKamarapu** [comment]
@rebekkabry  can you please qa this report in Prod.

![image](https://github.com/user-attachments/assets/b4e3d4e2-5104-4234-87d4-4a0507cc1277)

**Comment by rebekkabry** [comment]
# 10/24/24 

- reviewed screenshot with stakeholders 10/23/24, good feedback. @GaneshKamarapu 
- Moved to PROD and reviewed (SBO Overlay and Milling - Report Name) 
- Report ready to use 
![image](https://github.com/user-attachments/assets/698b1d79-c60a-46fc-8f1c-99c1af5cc6bd)

**Builder Notes for MVP2 Modifications:**  
- [ ] add comparison view of status work orders 
- [ ] add totals of qualities of all records (days, materials, etc) 
![image](https://github.com/user-attachments/assets/0d9fab95-e849-4dce-a198-8c2da404cebc)

**Comment by rebekkabry** [comment]
# Builder Notes 10/29/24 

@GaneshKamarapu. Great progress with the report. Below are a few notes regarding edits: 
- This report will be grouped by status primarily, then should in subgroups by the Work Order name. sub groups will be anything labeled "sp25-###--mill" and "sp25-###". For now, person groups do not need to be considered. 
- side note: person groups may become the third level (sub-sub) of the report. Meaning: workgroups of the "sp25-###-mill" and "sp25-###" can be showned in a layered column of the first graph.


![image](https://github.com/user-attachments/assets/3e7efeb7-3fb8-401a-9d20-383acd7946e6)

**Comment by rebekkabry** [comment]
# 11/8/24 
- scoping with Ganesh, after Q/A from stakeholders 

**Build Notes** 
+ Overlay and Milling 
- update the report to only include WorkType CW, should not include SBOIMG with that filter.
-  remove 1NEW from area, width
- find the "difference work orders"(ganesh recommends possible table view

**Comment by rebekkabry** [comment]
# 12/6/24

- provided stakeholders updates to the overlay report 
- closing until further confirmation of expanded scope. 
[SBO_OverlayandMilling (1).pdf](https://github.com/user-attachments/files/18044966/SBO_OverlayandMilling.1.pdf)
![image](https://github.com/user-attachments/assets/675eb6d4-3d2c-4c14-aeb0-f4abf52ef414)
