### ISSUE TITLE
Feature for multiple attachments with SIF submittal

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14583]
### SIF applicants need to be able to submit multiple attachments during initial submittal. 

- [x] New attachment object with attachment type "Supporting Documentation" 
- [x] Keep mapping the sif worksheet to the case object so the email keeps working. Or move it to the attachments table and update the email rules. Builder's choice. 
- [x] Update the application page w/ new attachment feature
- [x] Update the case details page w/ new table

**Comment by ChrispinP** [comment]
The new Content object for Supporting Document attachments and updated SIF Worksheet application is now available for the Testing Only in production. Once tested and approved by Stakeholders, we can push to the Live/Real application in production.

**Comment by TracyLinder** [comment]
### Review Notes

- The current design would require the customer to submit attachments twice; it's not a good experience. 
- For this reason I asked Chrispin to move the SIF Worksheet to the attachments object.
    - SIF Worksheet must be required
    - Customer email with link must continue to work

**Comment by ChrispinP** [comment]
- SIF Worksheet is now an Attachment Type to be included with other attachments
- As a result, the adding attachments is moved to the second page of the submittal process and the applicant/project information is now on the first page (since the parent record must be created first like other applications)
- Added text that A SIF Worksheet is Required
- Added validation on the Finalize & Submit page for the SIF Worksheet attachment type

Ready for Testing

**Comment by ChrispinP** [comment]
Informed stakeholders of the Testing Only version being available, I also did some backend cleanup of fields and rules.

**Comment by TracyLinder** [comment]
@ChrispinP I found another bug when processing the SIF worksheet. To reproduce:

1. Click Review SIF Worksheet
2. Add attachment & save

The bug is that the system placed the attachment on the SIF Worksheet field instead of the attachments object. Please fix.

**Comment by TracyLinder** [comment]
I moved this back to On Deck

**Comment by TracyLinder** [comment]
More testing feedback ... I think staff is going to need to be able to edit attachments in the attachment table. I think eventually they will ask us for this feature. See my test record [here](https://atd.knack.com/development-services#sif-worksheets/sif-worksheet-details/659585b65d714900272a8387/). I attached supporting documentation but tagged it as a SIF Worksheet. Now as a reviewer i need to correct the applicant's mistake and can't.

**Comment by ChrispinP** [comment]
I created a new field to distinguish historical from new records that will be created with the content object. The original SIF Worksheet will hide for non-historical records.

It must remain on the Edit Information page until all historical records have been reviewed.

Reviewers now have the ability to edit attachments from the table.

Can confirm that the new Knack error messages are very muted and no longer standout.
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/7b1dee13-6d74-4934-a9f7-6d0d9b8af90f)
Will reach out to Knack to see if this can inherently be fixed or if we need to code the color now

**Comment by ChrispinP** [comment]
Was able to update our CSS classes for these Form validations and I also updated the validation message.
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/e9483f46-76ac-4630-8b6c-4a81c1157308)

This should complete all action items above. Ready again for Testing & Deployment

**Comment by TracyLinder** [comment]
Reminder to remove this when we go live

<img width="631" alt="Screenshot 2024-02-06 at 3 33 54 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/49930868/466b99d2-07c0-4bb4-8a55-912779790796">

**Comment by TracyLinder** [comment]
### Review Notes 

Rename this button to Complete Review
![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/5c32b4c8-cec3-47ef-86f2-9745aabde322)


Add new field on attachment table; Reviewed?
- Boolean 
- Not required

**Comment by TracyLinder** [comment]
### Next Steps

1. Chrispin to make updates
2. TDS to test
3. Roll out

**Comment by ChrispinP** [comment]
I have updated the display rules for the old attachment field on both the Edit and Complete Review pages. If the record is historical or if the field is left blank it will now hide.

Review SIF Worksheet button updated to Complete Review. A column for a Reviewed? checkbox has been added for reviewers.
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/38978280-5be2-4aee-9d5c-c4a7e4b2eb5f)

**Comment by TracyLinder** [comment]
This still needs stakeholder approval to build in PROD.

**Comment by TracyLinder** [comment]
UAT scheduled for 3/11

**Comment by TracyLinder** [comment]
### Final review with Matiur

- Looks good to go
- Do we need downtime? --- Yes to prevent open applications from being submitted during the update. 
- Matiur ok with after hours and wants to update his team this week so we can roll out next week
- Chrispin will do it on 3/18 (next monday)

**Comment by TracyLinder** [comment]
### Go-live planned for 3/18 after 5pm

**Comment by ChrispinP** [comment]
The Feature Update for the SIF Worksheet Submittal service is now live in production.

Removed all test records. Pending closure.

**Comment by TracyLinder** [comment]
Ok to close. ✅
