### ISSUE TITLE
[TDS] Update Reporting Dashboard Tables & Pie Charts for On Time Metric

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#14609]
This is followup work for TDS Reporting Initial Build.

- [x] Update On Time Pie Charts for Scopes & Submissions to have custom filters like Cases
- [x] Have 2 On Time Pie Charts, one for 1st submittal and another for resubmittals
- [x] Move top table on Reporting Dashboard to the bottom of the page
- [x] Add an Actuals Table to the Reporting Dashboard that excludes Targets & On Time % so it can be filtered
- [x] Duplicate the Actual vs Target table to create a Target & On Time % only table

**Comment by ChrispinP** [comment]
Completed all task items. Scheduled a meeting on 11/27 to review with stakeholders.

**Comment by ChrispinP** [comment]
Updating estimate to 5 since there is a bit more work to do:

- [ ] Add On Time % Pie Charts for SIF & Determinations
- [ ] Update TS_Service data to also house Scope & Submission Time & Count Targets
- [ ] Scrap 2nd "Actual vs Target" Reporting Grid on Reporting Dashboard
- [ ] Add missing columns from 2nd "Actual vs Target" Reporting Grid to 1st pivot report
- [ ] Breakup 1st pivot report into 3 separate reports; Actuals, Targets, & On Time (stakeholders will send mockup)

**Comment by ChrispinP** [comment]
Second phase of reporting updates complete. Pending acceptance & closure

**Comment by TracyLinder** [comment]
### Update / Status

Chrispin is working on a few minor updates. Then this will be closed.
