### ISSUE TITLE
Test existing Inspector Prioritization Scripts

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14633]
### For the inspector prioritization project, determine if DTS can utilize any of the current scripts to begin producing a weighted list of data as was being done in 2019. 

- [Config info](https://github.com/cityofaustin/atd-amanda/tree/master/inspector-dash)
- [Previous data output lists](https://cityofaustin.sharepoint.com/sites/ATD/ROW/Reports%20and%20Data/Forms/AllItems.aspx?RootFolder=%2Fsites%2FATD%2FROW%2FReports%20and%20Data%2FTTC%20Inspection%20Priority%20Lists%2F2019&FolderCTID=0x012000E8D893E23C59694F8DB9FCE7C815FD48&View=%7B3861DD1C%2DEBA6%2D450C%2D80F0%2D32D1A1A55533%7D#InplviewHash3861dd1c-eba6-450c-80f0-32d1a1a55533=FolderCTID%3D0x012000E8D893E23C59694F8DB9FCE7C815FD48-SortField%3DModified-SortDir%3DAsc-)

**Comment by Charlie-Henry** [comment]
Hi @TracyLinder I was able to rerun this old prioritize script. Here's the summary of how the scoring works:

## Scoring Summary:

### Street segment count
- if more than one segment then score += 10
- if one segment, then score += 5

### Duration
- if less than 7 days, score += 10
- 7 to 15 days then score += 5
- 16 to 30 days then score += 3
- longer than 30 days += 1

### Road class

- Critical += 10
- Arterial += 7
- Collector += 5
- Residential += 3

It appears that frontage roads are the labeled the lowest classed road

### DAPCZ
If the permit's segment(s) is in the Downtown Area Project Cooridnation Zone (DAPCZ) score += 10

**Comment by Charlie-Henry** [comment]
There's some refactoring I'd like to do on this if we were to start this back up and ideally be able to query the AMANDA database directly in order to get the permits/segment data (right now the script uses two CSV files provided to it manually).

**Comment by Charlie-Henry** [comment]
@TracyLinder I was able to run this code so I'm gonna close this issue out
