### ISSUE TITLE
AFD Daily Crash Data not connected

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14630]
## Description

> Good morning y'all! Could someone take a look at the afd__incidents ETL process? I noticed that the file provided by AFD did not include any data after November 8th, 2023

## Notes
- Once we get a response add process and contacts documentation to DTS gitbook for future reference.

**Comment by patrickm02L** [comment]
## 11/13

Followed up with @XavierApostol's slack message and decide to email Celeste K, and Albert L took over and was able to troubleshoot with us. He sent us an excel file `ATD Daily Crash DataMM-DD-YYYY.xlsx` to confirm this is the right data we want. 

Xavier verified that this excel is good to go.

**Comment by xavierapostol** [comment]
Hello?

**Comment by patrickm02L** [comment]
We documented the contact info in [DTS gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ve3sp7qA5cPXha0B4/external-data-sources). When this happens again we can refer back to this resource.

**Comment by patrickm02L** [comment]
Will close out when it's confirmed that we're receiving this data in the database again.

**Comment by xavierapostol** [comment]
The AFD file that was submitted this morning is in the database. Thank you.

**Comment by patrickm02L** [comment]
Excellent!
