### ISSUE TITLE
Knack<>MS Outlook emails failing to reach inbox - `INC0343149`

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#14647]
Diana M. 
DTS

## Report # 1
HR reported that people were not receiving emails to sign their SSPRs
Hannah said 11/13 at 12:33 pm
>just a heads up I am hearing from Clay and John Padilla that their employees are not receiving notification emails for signatures from the HR application
> Brad K., Patricia M., John P., Joe H., Johnny C., Oscar C. R
>none of them received an email 

## Report # 2
Christina said that Jenny K. told her that people were not receiving emails from the Finance & Purchasing portal

## Report # 3
Karo was showcasing SMO Living Streets and noticed that emails weren't been received during a demo in the Smart Mobility Office application

**Comment by dianamartin** [comment]
# 11/14
- Created a CTM ServiceNow ticket
- Call CTM phone line, gave them my `INC0343149`
- I had explained the situation about critical system email notifications were not being delivered to their intended recipients
- They transferred ticket to ISO

### Screen Shot of the Email Log in Knack
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/5599eeb8-6394-46f2-beab-0a235b6770a4)

**Comment by dianamartin** [comment]
# 11/14
Messaged Hannah to see if she submitted a ticket and if so, what her ticket number was. Also said
>I wasn't sure if you had created a ticket so I ended up creating one: `INC0343149`. I also called CTM and they were able to transfer it to the Information Security Office "Cybersecurity group". Hoping that's something.

**Comment by patrickm02L** [comment]
## 11/15/23
In Planning we discussed potentially letting the department know that we're having Issues with notifications coming from our Knack apps. 

We'll need to check:
- HR
- Signs and Markings
- add as we find them

**Comment by dianamartin** [comment]
## 11/15
- KB Article: https://atx.servicenowservices.com/nav_to.do?uri=%2Fkb_view.do%3Fsysparm_article%3DKB0014145

**Comment by dianamartin** [comment]
# 12/11
Documenting correspondence

## 11/30
Hi Everyone, 

Sorry for the delay! Our system emails seemed to be flowing again after we had our meeting on 11/15. 

>To follow our plan, I’m emailing the resource accounts that are being used in our system generated emails. To ensure that our resource accounts aren’t blacklisted here are the ones that need to be mapped to their actual MS email accounts: 

- TMC
- tcpreview
- sharedmobility
- mobilityservices
- livingstreets
- datatrackersam
- transportationreview
- residentialparking

>Please let me know if there is anything else you need me to provide.

CTM replied
>Diana,
the emails need to come from [something@tpw.austintexas.gov] which will then map to an @austintexas.gov address as outlined in the initial email from Michael G. below. 

>One you have that list for ESA to create the mappings, then you can update the sender addresses in your application.

I replied
>Here are the field mappings: `tpw.austintexas` --> `austintexas`
- TMC
- tcpreview
- sharedmobility
- mobilityservices
- livingstreets
- datatrackersam
- transportationreview
- residentialparking
