### ISSUE TITLE
Convert Signal Work Order  "Problem Details" field from free text to list

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#1465]
Replace free-text work order entry with discrete data capture of maintenance work at traffic signals. 

E.g.,
- Battery Back-UP (UPS) maintenance
- Detection
...

See [Brian's lists of input categories](https://drive.google.com/drive/u/2/folders/1SieSTJf-hQShibgFU_fjagje50soTiuB).

**Comment by amenity** [comment]
This is a duplicate of #1880.
