### ISSUE TITLE
CIF Fellows Finance Purchasing 2024

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14653]
## Description
reference from last year's Fellowship #11529

The CIC 2024 Fellowship will require us to fill out a [finance purchasing request](https://atd.knack.com/finance-purchasing#purchasing-budget-review/purchase-request-details/5c89362eb25eea2ea69daed7/) because we're responsible for covering part of the costs of the Fellowship. 

We will not be able to use the previous agreement from past years because the collaboration with Coding It Forward did not have a financial obligation for the City. (See Note Below)

----

With a financial component, we will have to complete this process:

1. Process a purchasing contract between the City of Austin and Coding it Forward
2. The first requirement to begin this process is to obtain a formal quote for 50% of the costs from Coding it Forward.
3. An additional requirement is a document from Coding it Forward describing the program and its benefits to the City.  The document should  provide specific information about how Coding it Forward provides a specialized program for new technologists.
4. Austin Transportation will begin the purchasing process which involves multiple levels of approval within City leadership. This can take up to 30 days.
5. The City of Austin purchasing team will work with Coding it Forward’s legal team to negotiate any contract changes.
6. Once an agreement is signed, Austin Transportation will issue a purchase order to Coding it Forward.
7. Any invoices from Coding it Forward will have to reference the purchase order and follow the specifications in the signed agreement.

 

The City of Austin is bound by regulatory requirements for competitive purchasing at the federal, state, and local level.  Therefore, the agreement between the City and Coding it Forward will be based on the City’s contract language which incorporates those regulatory requirements. 

## Note
Ariana sent us a Service Agreement again this year 11/14/23. DTS does not fill it out, it goes through the financing process, and will be handled through the Finance Team. 

[City of Austin - 2024 Services Agreement.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHpZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ad7a5d279e09e1457c2393debd53bf523bdf73c/City%20of%20Austin%20-%202024%20Services%20Agreement.docx)

**Comment by patrickm02L** [comment]
## 11/29 
- Sent Ariana an email 11/16 outlining the purchasing process from last year, and asked her to update the program description and quote for 2024. 
- She sent the updated PDFs back 11/28

Now that we have the updated documents we need to start the purchase request process

**Comment by patrickm02L** [comment]
## 11/30 
Chatted with @amenity, she said she was going to duplicate the purchase request from last year to submit for this year. She messaged myself and Peggy on slack to confirm

**Comment by amenity** [comment]
[Purchase Request 2023-11-6877](https://atd.knack.com/finance-purchasing#purchase-requests/purchase-request-details/6568ec939d4fda0029fc2dbc/) submitted to @maccallump for review.

**Comment by patrickm02L** [comment]
## 12/1 
Sent Ariana an email letting her know that we've submitted the purchase request - the ball is rolling.

**Comment by patrickm02L** [comment]
## 12/15
Jon C from finance sent us a Certificate of Exemption to review, have signed by Peggy, and returned

**Comment by patrickm02L** [comment]
## 3/4/24
Peggy submitted all of the paperwork for the Fellows contract on 2/23/24

**Comment by maccallump** [comment]
The certificate of exemption was signed by Department Director on Friday.

**Comment by patrickm02L** [comment]
## 3/27/24
Sent message to Jon C asking about status, will notify Ariana from CIF when we hear back

**Comment by patrickm02L** [comment]
## 5/23/24

Checked in with Jon C yesterday regarding the status of the contract sent to CIF. He mentioned that it was sent out on 5/17/24 and again on 5/22/24, but the email was bounced back. I provided him with Ariana's email and the CIF fellowship general email for resending.

Also, I updated Ariana that the CTM buyer was trying to send them the contract, and she confirmed that she had not received anything.

**Comment by patrickm02L** [comment]
## 6/13/24
Contract was executed on 6/12/24 allowing Fellows to start on Thursday, June 13th.
