### ISSUE TITLE
Data Request: Prioritization Features in Excel Table

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#14669]
Export the following Feature Classes as Excel Tables and Email to Matt M. at SMO

- [x] Recreation Centers List w/ Addresses
- [x] Libraries w/ Addresses
- [x] Equity_Analysis_Zones_2021
- [x] ACS_Total_Population_Boundaries - Percent of Population in Dependent Age Groups (under 18 and 65+)

Pro Project already created here:
G:\ATD\ATD_GIS\DTS_GIS_Workgroup_Support\DTS_Smart_Mobility_Office\Living_Streets_Program\Prioritization_Mapping.aprx

Use the Export Data to Excel Tables Map

Exported can be saved to the local FGDB.

**Comment by Colemonj** [comment]
I sent the Excel tables to Matt M. and saved them at the following location,

G:\ATD\ATD_GIS\DTS_GIS_Workgroup_Support\DTS_Smart_Mobility_Office\Living_Streets_Program\Excel_Tables
