### ISSUE TITLE
Small Banners portal enhancements

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14678]
## Description
[Banners home page](https://atd.knack.com/street-banners#home/)

Breaking off smaller issues from #14013. After meeting with the Chandra and Matilda we settled on pulling the smaller tasks into one Issue and making additional Issue for what remains.

For this Issue please complete the following:

### Request 1: **Add Title to Banner Applications** - `Estimate 1`

- When clicking on either lamppost or OTS application from the Banners page, the application itself doesn’t state which application is being submitted. 
- Update application to read: 
  - Over-the-street application information - `Over-the-Street Application`
  - Lamppost application information - `Lamppost Application`

#### Note
Since the current process automatically takes the user directly to the application, it removes important context about which application they are submitting. It was suggested that reverting back to using the original portal design could help provide that missing context and clarity for the user upfront.

### Request 2: Make field required - `Estimate 1`
Event Information 
- Make this flex note a required field. `Will you be picking up your banners?`

#### Note
Currently it is not required, but banners program wants it to be required so they have confirmation from the customer that they will indeed be picking up their banners after they are removed.
	
### Request 4: Add "# of Banners Requested to Install" - `Estimate 1`
- Remove "REQUIRED"
  - Set rule to "Number of Poles Week 1" to set "Number of Banners" to set a form creation
- Reservation Information 
  - `# of Banners Requested to Install`
_This is a required field in knack when I click edit to update the application status, however it’s not asked on the customer view._ 
- Please include flex note to customer view as well. 
- Place it under the flex note, requesting # of poles  

#### Note
Currently the number of poles is required on the customer's application, but the number of banners is not required. This causes issues when trying to determine how many banners the customer actually wants, since some poles can hold double banners. It was suggested to make the number of banners automatically populate based on the number of poles entered, and then it could be manually updated if needed for double poles.

### Request 6: Update Application Statuses  - `Estimate 1`
Application Status
Remove the following statuses:
- Reservation Input 
- To Pickup 
- To Dispose 
- Removed

#### Note
Banners program wanted to keep this "Not Submitted" status for situations where a customer may have started an application but didn't actually submit it yet, so they wouldn't automatically consider it a reservation.

**Comment by patrickm02L** [comment]
@dianamartin would you take a look at this consolidated list of banners enhancements to make sure they have the information they need?

**Comment by dianamartin** [comment]
# Builder To Do Tasks

### Request 1: **Add Title to Banner Applications** - `Estimate 1`
- When clicking on either lamppost or OTS application from the Banners page, the application itself doesn’t state which application is being submitted. 
- Add Title on page: 
  - [ ] Over-the-street application information - `Over-the-Street Application`
  - [ ] Lamppost application information - `Lamppost Application`

### Request 2: Make field required - `Estimate 1`
Event Information 
- [ ] Make this field `Will you be picking up your banners?` - required field
	
### Request 4: Add "# of Banners Requested to Install" - `Estimate 1`
- Remove "REQUIRED"
  - Set rule to "Number of Poles Week 1" to set "Number of Banners" to set a form creation
- Reservation Information 
  - `# of Banners Requested to Install`
_This is a required field in knack when I click edit to update the application status, however it’s not asked on the customer view._ 
- Please include flex note to customer view as well. 
- Place it under the flex note, requesting # of poles  

### Request 6: Update Application Statuses  - `Estimate 1`
Application Status
Remove the following statuses from drop down
- [ ] Reservation Input 
- [ ] To Pickup 
- [ ] To Dispose 
- [ ] Removed

**Comment by dianamartin** [comment]
# 11/27
Messaged stakeholders
>Hey Ladies, 
 I was reviewing the statuses to delete them but, found two more that I might've forgotten to add to your list.  
LPB reservation in "Removed" status - `448`
OTS reservation in "Removed" status - `822`

>I've deleted
>- `Reservation Input` - from both 
>- `To Pickup` - from both
>- `To Dispose` - from both
>- `Installed` - from both

>I'm just waiting on deleting "Removed" until you guys have checked those last two records.

**Comment by dianamartin** [comment]
# 11/27
## Outstanding - work on 11/28
- Need to turn "Will Pick Up" into multi-choice not "Yes/No".
