### ISSUE TITLE
Create ROW Fee Payments Report and Batch Email Job

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14673]
### Create a report that is emailed to a distribution list daily, that will summarize the ROW fees paid the previous business day. 

Permit analysts do not know when a customer has paid their permitting fee; this has been expressed to DTS by multiple stakeholders over the last month. We need to sync with ROW to be sure a daily report is their preferred solution.

**Comment by TracyLinder** [comment]
@KyleErich should we close this ticket considering ROW feedback that this isn't wanted by staff?

**Comment by KyleErich** [comment]
@TracyLinder Indeed, I'm closing it. This was put to a vote in one of the permit analyst weekly meetings and the results indicated that a large majority did not desire such a solution.
