### ISSUE TITLE
Download Bike Facilities from Open Data Portal as a shapefile

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#1467]
This is another shapefile download request for the bicycle facilities. I think we need to change how this data be being shared on Socrata. Is there an automated way that the CTM Published TRANSPORATION.Bicycle_Facilities can be published to Socrata? I’m not sure how the Urban Trails dataset is published, but we need to covert this from an external link to a geospatial dataset that people can download themselves instead of us having our GIS staff download and email the requesters.

**Comment by johnclary** [comment]
TODO:

1. Ask CTM to change layer settings to allow downloads.
2. Post this link on the data portal dataset: https://www.arcgis.com/home/item.html?id=1142011559ab4f00add7fbba783847ed

Longer term
3. Use Esri > Socrata connector

**Comment by SurbhiBakshi** [comment]
1. [Transportation.Bicycle
_Facilties](https://www.arcgis.com/home/item.html?id=1142011559ab4f00add7fbba783847ed)is published on AGOL by CTM Publisher.
2.[Austin Bicycle Facilities](https://data.austintexas.gov/dataset/Austin-Bicycle-Facilities/kfe9-st9c) is published by ATD . This has a link to the AGOL Rest service and the AGOL download page. However the AGOL page needs a sign in, and doesn't offer a download option on the public page. 
3. This problem could be resolved if CTM publishes the AGOL feature service to the Open Data Portal using Socrata Connector, the data could be downloaded as a geospatial dataset from Socrata. 
4. Sent in a ticket to CTM-GIS to start process described above.

**Comment by SurbhiBakshi** [comment]
REQ0044420 in Service Now

**Comment by SurbhiBakshi** [comment]
Email from Dwayne - I forwarded this on to Collaboration Services.  They will be able to connect the AGOL layer to Socrata.

**Comment by amenity** [comment]
@SurbhiBakshi - please follow up on this

**Comment by SurbhiBakshi** [comment]
asked for a status update on this ticket.

**Comment by johnclary** [comment]
@SurbhiBakshi any update on this?

**Comment by SurbhiBakshi** [comment]
@johnclary - haven't heard back after I requested a status update, will ask again.

**Comment by SurbhiBakshi** [comment]
Asked for an update again.
Also checked the Open Data Portal in case work has been done, but the ticket did not get closed. Doesn't look like that has happened.

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/afd53b75-00ae-4bd6-b0f1-867a05d9627a)

**Comment by SurbhiBakshi** [comment]
wrote to Brad M and Marbenn C for an update.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/22f81a6e-e8f9-41d7-9e3b-72db87c0c01e)
