### ISSUE TITLE
Don't issue or extend TURP permits if Responsible Party bond or insurance is expired. (11/29) (SS) (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14684]
### The validation rules we built for the approved attempt on web application acceptance needs to be applied to the TURP issuance procedure and the extension granted attempt on Permit Extension process. 
Linked to #13578

**Acceptance Criteria - Permit Extension** 

- When user makes Extension Granted attempt in Permit Extension Process on the RW- TURP folders, system must perform the following tasks:
- Check to see if the folder has a Responsible Party people record added to it. 
    - If Responsible Party people record doesn't exist on the folder, do not run the validation, just allow the attempt to save. 
- If there is a Responsible Party on the folder, check the People Info of the Responsible Party People Record for infos 'Bond Expiration Date'  (58085) and 'Insurance Expiration Date' (75350)
- If either of these People Infos have a date that is in the past, or a blank value, system must display a hard stop message stating Bond and/or Insurance information is out of date.

**Acceptance Criteria - Issue Procedure**

- When user selects the Issue/Approve option from Folder Tab of RW-TURP folders, system must perform the following tasks:
- Check to see if the folder has a Responsible Party people record added to it. 
    - If Responsible Party people record doesn't exist on the folder, do not run the validation, allow issuance procedure to proceed. 
- If there is a Responsible Party on the folder, check the People Info of the Responsible Party People Record for infos 'Bond Expiration Date'  (58085) and 'Insurance Expiration Date' (75350)
- If either of these People Infos have a date that is in the past, or a blank value, system must display a hard stop message stating Bond and/or Insurance information is out of date.

**Comment by TracyLinder** [comment]
@vschandramouli can you please write the ac for this?

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by SubhaShroff** [comment]
@Nadin-Nader The code changes are done and due to limitations on localhost I couldn't test it, completely. Please submit a DEV promotion request. It can be tested on DEV. Here is the commit - b483c67bc4a7b538b2c532ef7aa4ca04b002f477.

Thanks.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0375214**

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to DEV please UAT

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to TEST under **SCTASK0377534**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I tested this on TEST, its ready for UAT. Thanks.

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff UAT on TEST approved. Thanks.

**Comment by SubhaShroff** [comment]
Thank for UAT Kyle.
@Lpriya-LIT  Please raise PROD deployment request.  Thank you.
[14684- b483c67bc4a7b538b2c532ef7aa4ca04b002f477- PROD Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/13781578/14684-.b483c67bc4a7b538b2c532ef7aa4ca04b002f477-.PROD.Deployment.Plan.docx)

**Comment by Lpriya-LIT** [comment]
@SubhaShroff Created Prod deployment request , SCTASK0381508

**Comment by Nadin-Nader** [comment]
Still Waiting on CTM to deploy

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is in PROD now. Up for UAT.

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff UAT approved on Prod. Thank you!

**Comment by SubhaShroff** [comment]
Thanks Kyle.
@Nadin-Nader This is good to close. Thank you.

**Comment by Nadin-Nader** [comment]
closing
