### ISSUE TITLE
Duplicate February schedules in March 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1468]
Please copy over the previous three weeks of the schedule, starting with week of 2/10, but note the following:
 - The week of 2/10 would populate the week of March starting with 3/2,
- The week of 2/17 would be copied over for the week of March starting with 3/9, but you can leave the schedule blank starting from 3/13 to 3/22 (SXSW!)
 - The week of 2/24 would be copied over for the week starting of 3/23.

**Comment by amenity** [comment]
@SurbhiBakshi will you estimate, please?

**Comment by SurbhiBakshi** [comment]
thanks for creating this issue @amenity !

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/cd5d4bf7-3631-4eae-9354-294c6f2886e4)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/7e789f54-8023-4ba1-b334-680fb8ff078c)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/396a72a1-207a-46f3-a334-12ea7c60f9b2)

**Comment by amenity** [comment]
Thanks, @SurbhiBakshi . 🙏
