### ISSUE TITLE
RAW Data on LM Folder Fees (LP)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14699]
### Raw Data for billed fees on the LM folder

**Export the columns below for these parameters:**

- Folder type is LM
- Fee has been billed
- Billed/Invoiced date is 10/1/2021 to current

FolderRSN | Subtype | Worktype | Fee Code | Fee name | Invoice # | Invoice Date
-- | -- | -- | -- | -- | -- | --

**Comment by TracyLinder** [comment]
I'm asking for this data so we can analyze the fees being used for any necessary updates due to the LM team migrating from DSD to TPW.

**Comment by Lpriya-LIT** [comment]
[ATD #14699 - LM Fee Data.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU1QQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35573ab660f99fac00db680d4d34ac10e34af3aa/ATD%20%2314699%20-%20LM%20Fee%20Data.xlsx)

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Please find the Fee data attached herewith. I have sent it in email as well. 
@vschandramouli

**Comment by TracyLinder** [comment]
@Lpriya-LIT thank you. When you have a moment can you please pull the GL codes for the following fees?


Code | Name
-- | --
50151 | License Agreement Processing Fee
50152 | License Agreement 1st Annual Payment
50156 | License Agreement Application Fee
50157 | Permanent Encroachment Application Fee
50158 | Street/Alley Vacation Application Fee
50159 | Easement Release Application Fee
50202 | Major Project
50203 | Recording Fee
50228 | Land Management - Public Notification
50229 | Land Management - Real Estate Appraisals
50231 | Land Management - Cancellation/Transfer of Property
50340 | Application Fee
51835 | Travis County Subdivision Fees
51846 | County Recordation Fee

**Comment by TracyLinder** [comment]
Hi @Lpriya-LIT could you add a column to the data you pulled for fee amount please?

**Comment by Lpriya-LIT** [comment]
@TracyLinder Please find the GL codes below,

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVlQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9927c152a52b7fcda71b9cd03f19006c5cacad4b/image.png)

**Comment by Lpriya-LIT** [comment]
@TracyLinder Added fee amount to the fee data

**Comment by Lpriya-LIT** [comment]
[ATD #14699 - LM Fee Data.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW9QQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b80a1faa482f745625b2028e055f5098ffee8014/ATD%20%2314699%20-%20LM%20Fee%20Data.xlsx)
