### ISSUE TITLE
IT Support: RETIRE OLD MACHINES FROM ST. ELMO

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#14692]
ST. ELMO,

## Device & User Information (first name and last initial, no last names)
Scott R
## What's the problem?
Hey Scott I just took a bunch of machines that need to be retired to BOP. 
 

Here is the list 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1B2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9f62a607de0072d4212f6eeb6e89176e00ac979/image.png)

**Comment by Matthew-M-TPW** [comment]
Delivered 2 additional computers to BOP

**Comment by dianamartin** [comment]
@Matthew-M-TPW what's the status of this?

**Comment by scottreedy** [comment]
Retired

**Comment by scottreedy** [comment]
REQ0168048 - SCTASK0375677 - 12/04/2023 18 computers
