### ISSUE TITLE
[AMD Data Tracker] Manage Vehicles page - Set default 100 per page and add "Ready for Pickup" status in log window

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#14709]
For the Manage Vehicles page in the AMD Data Tracker:

On 11/20:
> is it possible to default to 100 per page?
> is it possible to add 'ready for pickup" to the vehicle status in the vehicle log window?

**Comment by ChristinaTremel** [comment]
Need to reach out to Billy to clarify the second ask before this is ready to work on.

**Comment by ChristinaTremel** [comment]
### Susanne, Billy, and I met on 12/11 and made the following updates:
- Updated default table view to 100 records per page
- Added these new `Status` options to `fleet_vehicles` object:
   - In Service - Requested by Fleet
   - Out of Service - Ready for Pick Up
- Added these new `Status` options to `fleet_vehicle_tracking` object:
   - In Service - Requested by Fleet
   - Out of Service - Ready for Pick Up
- Added new `Action` to `fleet_vehicle_tracking` object:
   - Notification from Fleet
- Updated `Add Log` form rules to update the fleet_vehicles status when adding a log with the new status options
- Tested new statuses and everything was working as expected. 
- Billy will test this out over the next few days and let us know if something is not working as expected!

**Comment by susannegov** [comment]
Billy said this ticket is good to close as of 12/13
