### ISSUE TITLE
ATD AMANDA Backlog — LIT

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1470]
Work on the [ATD AMANDA Backlog](https://github.com/cityofaustin/atd-data-tech/issues/432) delivered by Launch IT. 

Delivery work is managed [on this Trello Board.](https://trello.com/b/2MZ7yNTv/atd-lit)

**Comment by amenity** [comment]
@SurbhiBakshi @johnclary - this epic has everything with 1.* Priority in the [AMANDA Open Requests spreadsheet](https://docs.google.com/spreadsheets/d/1ix5X-cQSW2ZRhlwtBemRkJP5vjF3cKT2ovGuX9hT7C4/edit#gid=462314407), plus #1423 ad #1436 which appear to be connected. Correct as needed!

**Comment by SurbhiBakshi** [comment]
scheduled a meeting with Raj and @john for 3//5

**Comment by SurbhiBakshi** [comment]
Notes from meeting - 
1. Schedule next meeting - 03/10
2. Share Trello board with Raj
3. Raj will take a look at documentation and get back to us.
4. LIT will commit a BSA, developer, tester
5. Would like to get a 2-day in person meeting to do system studies and capture requirements, Raj and BSA will travel to Austin.
6. primary stakeholder functional requirements?
7. will send a project plan afterwards
8. do work on Dev
9. couple of working sessions
10. UAT on Test
11. I will continue to attend 1 pm afternoon call with DSD for reporting

**Comment by SurbhiBakshi** [comment]
Set up a weekly update call with Paloma and Ryan - 4 meetings to begin with, can add if needed.

**Comment by amenity** [comment]
This epic isn't being maintained; using the `Provider` label now.
