### ISSUE TITLE
[Enhancement] Denormalize location storage in the crashes table

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14719]
## Description
reference [PR 1293](https://github.com/cityofaustin/atd-vz-data/pull/1293)

Deprecate the lat and long columns in a crash table and modify the CRIS import scripts. 

## Parts
- Plan for denormalizing
- Execution of the plan

@patrickm02L  break down the parts into separate Issues.

**Comment by johnclary** [comment]
We've launched the LDM, and we still do have lat/lon columns as well as a `position` column that is set as part of the trigger that updates crash spatial attributes. i'm closing this because i don't think we need to address this anymore.
