### ISSUE TITLE
Signal Fiber Mapping Meeting

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#14727]
Edgar M  was last to map in 2019
May have done about 50% of total fiber locations
Used fiber drawings and added to ArcPro
Not much if any fiber has been added 
Would be a full time job to QC existing and Update based on drawings
90% of drawings are digital format
Edgar worked with Jaime
Harrell, fiber is not particularly useful for him, more information the better
Pole data that were currently maintain is more useful for him
Started by Jim D a while back
Unless Bryan or someone higher is pushing this, Harrell doesn't see a need for this to be maintained

Data location:

**Comment by maccallump** [comment]
Mapping underground fiber optic cables offers several benefits, including:

Maintenance and Repairs: Accurate mapping helps in quickly locating and identifying cable faults or damages. It facilitates timely repairs, reducing downtime and minimizing service disruptions for customers.

Efficient Expansion and Planning: Knowing the exact locations of existing underground fiber optic cables aids in planning new installations or expansions. It prevents accidental damage during construction or excavation activities.

Safety: Accurate mapping enhances safety by preventing accidental cable cuts during digging or construction work. This protects both the infrastructure and the individuals involved in such activities.

Cost Savings: Detailed mapping reduces the need for extensive exploratory digging or surveys to locate cables, resulting in cost savings in both time and resources.

Compliance and Regulations: It helps organizations comply with regulations regarding the installation, maintenance, and safety of underground utilities, avoiding potential fines or legal issues.

Network Efficiency: Understanding the layout of the underground fiber optic network allows for better optimization of routes, improving network efficiency and reducing signal loss or degradation.

Emergency Response: Quick access to mapped cable locations enables faster response times during emergencies such as natural disasters or accidents, allowing for efficient restoration of services.

Documentation and Record-Keeping: Maintaining accurate maps serves as essential documentation for network infrastructure. It provides valuable information for future maintenance, upgrades, or expansions.

Overall, mapping underground fiber optic cables is crucial for efficient operations, timely maintenance, and ensuring the reliability of telecommunications and internet services.

**Comment by maccallump** [comment]
Mapping underground fiber optic cables involves several steps to ensure accuracy and reliability:

Obtain Existing Records: Gather any available records, blueprints, or diagrams from the organization responsible for the fiber optic network. These documents might provide initial information about cable routes and locations.

Use Specialized Equipment: Employ specialized tools and equipment such as cable locators, ground-penetrating radar (GPR), or electromagnetic locators. These tools help detect and trace buried cables without physically exposing them.

Ground Surveys: Conduct ground surveys to physically locate access points, manholes, or handholes that provide entry to the underground network. This step involves careful observation and documentation of visible infrastructure.

Utilize Mapping Technologies: Employ Geographic Information Systems (GIS) software or other mapping technologies to record and plot the locations of identified cables, access points, and any relevant landmarks accurately. GPS-enabled devices can assist in pinpointing locations.

Documentation and Labeling: Document all findings systematically, including cable types, depths, and routes. Proper labeling and categorization of cables ensure clarity and ease of future reference.

Collaboration and Verification: Collaborate with network engineers, technicians, or experts who are familiar with the network infrastructure to validate collected data and ensure accuracy.

Field Verification: Perform on-site verification to confirm the accuracy of the mapped data. This step involves physically verifying the locations of cables and cross-referencing with the mapped information.

Regular Updates: Maintain the mapping database regularly. As changes or expansions occur within the network, update the maps accordingly to reflect the current infrastructure layout.

Security Measures: Ensure the security and confidentiality of the mapped data as it might contain sensitive information about the network infrastructure.

Remember, mapping underground fiber optic cables requires careful planning, specialized equipment, collaboration among experts, and adherence to safety protocols to ensure accurate and reliable results while avoiding damage to the existing infrastructure. Professional expertise and adherence to best practices are crucial for successful mapping.
