### ISSUE TITLE
[Data] Provide Prairie View A&M VZDB read replica access and aws key for CR3s

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14724]
## Description
The VZ team is partnering with Prairie View A&M to do an AI project looking at the location data provide on the crash reports and the crash narrative. As part of the project DTS has been asked to provide access to the VZDB as well as an AWS key for accessing CR3s.

### Deliverables
- [ ] Read replica access granted to VZDB
- [ ] AWS key provided to VZDB for accessing CR3 crash narratives

### Notes
- Assistance may be required to help VZDB set up and utilize the read replica and AWS access
- It's important to clarify and document how the CR3s are integrated with the VZDB data
- This data sharing is in line with our agreement with TxDOT, which permits data sharing strictly for local government purposes

**Comment by johnclary** [comment]
Based on additional discussion with the Information Security Office, we will not be sharing CR3 PDFs externally. Closed 👍
