### ISSUE TITLE
PM + Builder work session on VZA Officer workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1472]
Meet to discuss best approach to Officer workflow in VZA app. 

Preliminary outline [here](https://docs.google.com/document/d/1PBtoOPWAwLMduMZs9jJhMu-YX213UgxbOuNnVBAumko/edit#).

**Comment by amenity** [comment]
@SurbhiBakshi - are you comfortable with me inviting Pat to this work session? I could see it expediting things to get his feedback on the spot.

**Comment by SurbhiBakshi** [comment]
@amenity - absolutely
