### ISSUE TITLE
Implement changes based on Pat's feedback

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1474]

**Comment by SurbhiBakshi** [comment]
![IMG_4104.jpg](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/085d56fc-b4c9-4bd0-8c04-8a194abfd6f1)![IMG_4105.jpg](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/39415c4a-da1b-41c6-8fd2-efc3256f43b9)![IMG_4106.jpg](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/2a6b7ddf-0716-4129-94d7-699631be9e06)![IMG_4107.jpg](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/69b2d6c1-c0ff-46ec-b4d5-e50fbdcc5c49)
