### ISSUE TITLE
Migrate backfill records to the Regulation Item and Reg Doc objects

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14758]
When meeting with Joana in her team, Chrispin and I were told that they are ready to migrate backfill records as Approved Regulations because staff were starting to use the Traffic Register Knack App to search for regulations. 

Have been asked to only import records with:
- `Install Date` if the action is `Install` 
- `Uninstall Date` if the action is `Delete`.

**Comment by ChristinaTremel** [comment]
### Notes 
- [x] Imported `381` retire documents from backfill -> Approved Reg Doc object

### Next Steps
- [ ] Import `693` install documents from backfill -> Approved Reg Doc object
- [ ] Export records and review spreadsheet to find duplicates
- [ ] Remove duplicates from Approved Reg Doc object
- [ ] Then we can start import of Canvas Regulations
- [ ] Then we can start import of Approved Regulations (line items)

**Comment by ChristinaTremel** [comment]
## Notes from 2/13
- Manually flagged `82 records` that were added in both the Access database and as a Traffic Register backfill record. Marked these for deletion 
- Updated `232 records` Remarks and Uninstall Date from duplicate records
- Flagged `232 records` to update with Mark for Deletion = `Yes` (the duplicate records we need to remove)
- Filtered the `Regulation_Documents` object for Mark for Deletion = `Yes`
   - 314 records were marked for deletion
   - Deleted `314 records`
- Re-exported the Regulation Document records and checked for duplicates
  - ☑️ Duplicates no longer existed
- Let Chrispin know that we are ready to import the regulation line items

**Comment by ChristinaTremel** [comment]
@ChrispinP - you finished the migration of the backfill records to the `regulation_items` object right? I think I see them all!

**Comment by ChrispinP** [comment]
yes, all 3529 backfill items have been successfully imported into the regulation_item object

Complete, closing
