### ISSUE TITLE
Create a draft version of the Traffic Regulation Paginated Report for Canvas Regs (`Draft` Regs)

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14757]
Similar to the PDF Report for Approved Regs, we would like to create a similar thing for Canvas Regs to be viewable in the Task Board `Draft Review` details page. 
     ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/f34098b5-ac50-49e8-bb05-4b84eb3d5a5e)
 
- [x] Create API View of `Canvas Regs` where `Draft Status` is **Draft** or **Submitted for Review** and `Record Type` is not **Approved Reg**
- [x] Build Paginated Report
- [x] Create the links on the details page that go directly to the Reg in the Paginated Report

**Comment by ChrispinP** [comment]
- Source Data updated in PBI and on the Test pipeline
- Draft Traffic Register dataset set to refresh every minute with Power Automate
- Draft Regulation Document published
- URL links generated for Draft Documents
- Draft Documents linked on My Tasks table and Draft Review page

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/1fbd6208-3b39-4f84-b1e1-97f33018a9e4)
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/acdf462d-15c8-43e4-87ab-b666bf6a4669)

**Comment by ChristinaTremel** [comment]
We showed users the draft version during the Traffic Register Sprint Review and this solution seems to work for them!
