### ISSUE TITLE
OCE Mixes Post prototype scoping/documentation

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14766]
- High level roadmapping of OCE KNACK APP
- Map MVP's from the roadmap
- Review current workflow and better understand the needs and how that relates to the roadmap

**Comment by TracyLinder** [comment]
### Recap
_I didn't take notes._

- This was a very helpful meeting and i think we all understand the program and scope of work much better. 
- Diana mapped out the objects in a way that makes a lot of sense.
- We identified what's MVP for this request, and what we think we can build on. 
- I'm really interested in the related inspection piece of the OCE Mix program and will attempt to learn more. 
- I'm meeting with Michael K. on Thursday to learn more.

**Comment by dianamartin** [comment]
# 12/4
I updated the Miro [board](https://miro.com/app/board/uXjVNXFdd5A=/)
