### ISSUE TITLE
Resolve ESB → Knack issue related to `CSR_ACTIVITY_ID` `591141223`

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#14774]
CTM's ESB has been attempting to (re)insert a record into the `tmc_activites` table in Data Tracker, however the record already exists. @johnclary has communicated with Robert at CTM, saying:

> Ferris, Robert we have been getting an error from prod related to an attempt to insert an activity record in knack:
`{"errors":[{"field":"field_4583","type":"unique","message":"CSR_ACTIVITY_ID must be unique. \"591141223\" is already being used."}]}`
we tried deleting the record in Knack and letting the ESB insert the record anew, but that did not resolve the issue. i think we're hitting a weird edge case that might be easier to explain via phone call, but in the short term i'm wondering if you can clear out whatever messages are queued related to this SR?

Robert replied:

> I checked and the code should have blocked any duplicate messages. I made some adjustments to change the order it makes its checks. Let me know if you are still getting the same errors.

However, the ESB continues to attempt this insert every five minutes and continues to email out the above error that John included.

**Comment by chiaberry** [comment]
adding myself to the issue to help keep an eye on it. @ChristinaTremel do you want to be added as well?

**Comment by chiaberry** [comment]
this was (eventually) resolved
