### ISSUE TITLE
[Bug] Fix CR3 diagram rotate button in top right of Crash page

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#14772]
On the crash page, there is a rotate button in the top right of the interactive CR3 diagram viewer. This button does not appear to be working. We could fix it or remove it if we no longer need that specific button.

[Example of crash](https://visionzero.austin.gov/editor/#/crashes/19583527) in Production that's not rotating.

### Crash page
<img width="935" alt="Screenshot 2023-11-29 at 12 37 44 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/37249039/b81d09d0-6969-4779-ba11-a5b7f8462029">

**Comment by mddilley** [comment]
@patrickm02L I forgot to mention that I figured out what this button does while testing this morning. It isn't broken, and it resets the zoom to default after zooming in or out.

So, there are two buttons that reset the image to the default state:
1. the rotate icon in the top right that resets the zoom to default
2. the "Reset" button in the bottom right that resets the rotation of the image

Do you think that we should leave it as-is or make an update? I can take the points off this one and close it if we are good with the existing functionality.

**Comment by patrickm02L** [comment]
@mddilley how about we put a tool tip on the rotate button, that says "Reset zoom"? It makes sense to me to keep that functionality separate from the overall reset.

**Comment by mddilley** [comment]
Cool, tooltip it is, thanks!
