### ISSUE TITLE
Maximo Learning Cohort

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#14787]
With the loss of a Maximo resource, it's more critical than ever to regroup and support each other. I know there are a lot of upcoming projects that may use Maximo data in some fashion and rather than all of us reaching out to the Maximo team. I propose that we establish a Maximo Learning cohort. 

This group will walk through learning Maximo together in a structured way so that we can all document and learn what we need to learn together. 

**Maximo Knowledge leads**: Adriana & Rene
#### Maximo Learners: 
- Peggy
- Diana
- Christina
- Rebekka
- Andrew

### Resources
- Maximo [SharePoint site](https://cityofaustin.sharepoint.com/sites/MaximoResources)
- Maximo [Library](https://cityofaustin.sharepoint.com/sites/MaximoResources/SitePages/End-User-Documentation.aspx) - reference sheets, courses, video demonstrations
- Maximo Miro workflow - In Progress, coming soon!

# Learning Phases 
>these learning phases may change and vary
## What is Maximo?
- Jump into the existing Maximo resources - in [Library](https://cityofaustin.sharepoint.com/sites/MaximoResources/SitePages/End-User-Documentation.aspx)
- Building Maximo Data Dictionary
- Building Maximo Workflows (in Miro)
## How does SBO use Maximo
- District Maintenance
- Pavement Operations
- Utilities & Structures
- Urban Forestry
## Maximo Spatial
- How is Maximo mapping things, assets & work orders
## Maximo Reporting
- What are the existing reports - see [Scheduled Reports](https://docs.google.com/spreadsheets/d/1VfZJl14EvbiWn1xAq424ASi4wG8gKxmp/edit#gid=798040824)

**Comment by rebekkabry** [comment]
[Maximo Insights from Ecosystem Discovery Meetings ](https://github.com/cityofaustin/atd-data-tech/issues/15165)

**Comment by dianamartin** [comment]
# 1/8/2024
- Went over `Maximo Training - Introduction to Maximo - District Maintenance` [slide deck ](https://cityofaustin.sharepoint.com/sites/MaximoResources/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FMaximoResources%2FShared%20Documents%2FPresentations%2FMaximo%20Training%20%2D%20Introduction%20to%20Maximo%20%2D%20District%20Maintenance%2Epdf&parent=%2Fsites%2FMaximoResources%2FShared%20Documents%2FPresentations)

## Next Session
- Dive deeper into District Maintenance Subgroups (North, Central, South)

**Comment by rebekkabry** [comment]
# 6/13/24 Adyrs Recommended
 _if we continue_ 
- Erin to understand Maximo 
- Coordinators to review their process 
- Ganesh report review: how reports are being created and developed within MAXIMO (if we were not using another system like Power BI)

**Comment by rebekkabry** [comment]
@dianamartin Can we attach the Assessment, new Sharepoint and Gitbook here to complete? 

https://atd-dts.gitbook.io/maximo-help-guides/introduction-to-maximo

**Comment by dianamartin** [comment]
@rebekkabry you can add the GitBook and Sharepoint site here. I'll add the assessment when I can. I moved it to our DTS SharePoint folder for easy sharing.

**Comment by dianamartin** [comment]
# 10/21/2024
•	[Maximo Discovery: Findings](https://cityofaustin.sharepoint.com/:w:/r/sites/tpwDTS/Shared%20Documents/Projects/Maximo%20Assessment/Maximo%20Discovery%20Report/Maximo%20Discovery%20-%20Findings.docx?d=w74ffad402fc14a5aacf3e61cdaa11621&csf=1&web=1&e=vbjyWa)
•	[Maximo Discovery: Strategic Proposal (Draft)](https://cityofaustin.sharepoint.com/:w:/r/sites/tpwDTS/Shared%20Documents/Projects/Maximo%20Assessment/Maximo%20Discovery%20Report/Maximo%20Discover%20-%20Strategic%20Proposal.docx?d=w848f6b9bb8104455bcf6e0c8af5b86de&csf=1&web=1&e=AsytZ9)
>We're still working on this one, to polish it and get it final by 10/23.
