### ISSUE TITLE
Offboard Dipa

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#14780]
## IT Permissions and Access

- [x] 1password - Diana - _12/12, Dipa did not have an account_
- [x] Miro - Diana - _12/12, Dipa was not part of the Austin Transportation team_
- [x] DTS Portal - inactivate account  - _made inactive 12/12 (Diana)_
- [x] Signs and Markings - inactivate account - _made inactive 12/12 (Diana)_
- [x] AMD Data Tracker - inactivate account  - _made inactive 12/12 (Diana)_
- [x] Maximo - @adry-martinez can you do this next week please
- [x] Maximo Sharepoint site - Adry
- [x] Maximo Teams - Adry
- [x] Google Drive - _removed permissions from ATS DTS 12/12 (Diana)_
- [x] Slack - _deactivated 12/12 (Diana)_
- [x] Github team - @frankhereford 
- [x] SERF 
>Created SERF on 11/28 - `REQ0167661`
- [x] DTS email DL
- [x] DTS email distribution

## Admin
- [x] Update [Service Desk Knowledge Base](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/dts-service-desk/triaging-emails-non-service-request)
- [ ] Update "About Us" page on the DTS website
- [x] Remove from DTS Slide decks
- [x] DTS SharePoint team lists - references the "About Us" page on austinmobility.io

## Recover organization assets
- [x] Badge - Remove access
>~Diana or Billy to do that, Tues 12/5~
>Messaged Billy, 12/12 "Can I ask you for a quick favor? Can you remove badge access for Dipa?"
- [x] Laptop - asking Tech Services - _Dipa returned on 12/6_
>keys are sticky, deprecate?
- [x] Tablet - asking Tech Services _Dipa returned on 12/6_
- [x] Headset - return to Diana _Dipa returned on 12/6_
>Update: Matt picked up items on 12/7
>Scott said we need the laptop turned in
- [ ] ~Docking Station~
- [ ] ~Monitors~
- [ ] ~Desk Riser - at Cameron~
- [ ] ~Chair - at Cameron~

**Comment by adry-martinez** [comment]
Dipa removed from MS Teams Maximo 12/4 and Maximo Resource SharePoint 12/4

**Comment by dianamartin** [comment]
# 12/12
## Updated tasks for 
- [x]  1password - Diana - 12/12, Dipa did not have an account
- [x]  Miro - Diana - 12/12, Dipa was not part of the Austin Transportation team
- [x]  DTS Portal - inactivate account - made inactive 12/12 (Diana)
- [x]  Signs and Markings - inactivate account - made inactive 12/12 (Diana)
- [x]  AMD Data Tracker - inactivate account - made inactive 12/12 (Diana)
- [x]  Google Drive - removed permissions from ATS DTS 12/12 (Diana)
- [x]  Slack - deactivated 12/12 (Diana)

**Comment by dianamartin** [comment]
- [ ] Update "About Us" page on the DTS website
