### ISSUE TITLE
IT Support: Expand Signal Engineering Area GIS features to include additional signal IDs

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14816]
- The MMC has requested to expand the Signal Engineer GIS polygons to include the following signals: 

Signal ID | Jurisdiction | Signal Eng. Area to Assign To | FY 2024 DATE | Location | Owner | Status | Anticipated Completion Date
-- | -- | -- | -- | -- | -- | -- | --
75 | AUSTIN 2 MILE ETJ | SOUTHWEST |   | US 290 HWY / HUDSON LOOP | COA | Not Complete | Near Most Adjacent Area
101 | AUSTIN 2 MILE ETJ | SOUTHEAST |   | PEARCE LN / KELLAM RD | COA | Not Complete | Near Most Adjacent Area
373 | AUSTIN 2 MILE ETJ | SOUTHWEST |   | BRODIE LN / CAPISTRANO TRL | Travis County | Not Complete | Near Most Adjacent Area
375 | AUSTIN 2 MILE ETJ | SOUTHWEST |   | BRODIE LN / ACCOMAC DR | Travis County | Not Complete | Near Most Adjacent Area
423 | SUNSET VALLEY FULL PURPOSE | SOUTHWEST |   | BRODIE LN / ERNEST ROBLES WAY | Sunset Valley | Not Complete | Near Most Adjacent Area
454 | AUSTIN 2 MILE ETJ | NORTHEAST |   | WELLS BRANCH PKWY / KILLINGSWORTH LN | Travis County | Not Complete | Near Most Adjacent Area
670 | AUSTIN 2 MILE ETJ | NORTHEAST |   | SPRINGDALE RD / PECAN BROOK DR | Travis County | Not Complete | Near Most Adjacent Area
795 | SUNSET VALLEY FULL PURPOSE | SOUTHWEST |   | BRODIE LN / HOME DEPOT BLVD | Sunset Valley | Not Complete | Near Most Adjacent Area
822 | WEST LAKE HILLS ETJ | SOUTHWEST |   | WESTBANK DR / ALLEN RD | Travis County | Not Complete | Near Most Adjacent Area
887 | AUSTIN 2 MILE ETJ | SOUTHEAST |   | 4601 BLK MC KINNEY FALLS PKWY (TX Parks and Wildlife) | COA | Not Complete | Near Most Adjacent Area
914 | AUSTIN 2 MILE ETJ | NORTHWEST |   | QUINLAN PARK RD / STEINER RANCH BLVD | Travis County | Not Complete | Near Most Adjacent Area
918 | AUSTIN 2 MILE ETJ | SOUTHWEST |   | BRODIE LN / INDIAN POINT DR | Travis County | Not Complete | Near Most Adjacent Area
923 | AUSTIN 2 MILE ETJ | NORTHWEST |   | QUINLAN PARK RD / COUNTRY TRAILS LN | Travis County | Not Complete | Near Most Adjacent Area
948 | AUSTIN 2 MILE ETJ | NORTHWEST |   | QUINLAN PARK RD / STEINER RANCH BLVD (University Club Dr) | Travis County | Not Complete | Near Most Adjacent Area
949 | AUSTIN 2 MILE ETJ | NORTHEAST |   | DESSAU RD / CRYSTAL BEND DR | Travis County | Not Complete | Near Most Adjacent Area
1026 | HUTTO ETJ | NORTHEAST |   | GATTIS SCHOOL RD / PRIEM LN | Travis County | Not Complete | Near Most Adjacent Area
1027 | HUTTO ETJ | NORTHEAST |   | GATTIS SCHOOL RD / LINKS LN | Travis County | Not Complete | Near Most Adjacent Area
1057 | AUSTIN 2 MILE ETJ | SOUTHEAST |   | BLUFF SPRINGS RD / BRANDT RD | COA | Not Complete | Near Most Adjacent Area
1106 | AUSTIN 2 MILE ETJ | SOUTHEAST |   | SLAUGHTER LN / BLUFF SPRINGS RD | Travis County | Not Complete | Near Most Adjacent Area
1127 | AUSTIN 2 MILE ETJ | SOUTHEAST |   | SLAUGHTER LN / THAXTON RD | COA | Not Complete | Near Most Adjacent Area
1149 | AUSTIN 2 MILE ETJ | NORTHEAST |   | DECKER LAKE RD / BLUE BLUFF RD | COA | Not Complete | Near Most Adjacent Area
1151 | AUSTIN 2 MILE ETJ | NORTHEAST |   | JOHNNY MORRIS RD / DAFFAN LN (Walnut Creek Trail) | COA | Not Complete | Near Most Adjacent Area
1152 | AUSTIN 2 MILE ETJ | SOUTHEAST |   | OLD SAN ANTONIO RD / PURYEAR RD | Travis County | Not Complete | Near Most Adjacent Area
1153 | AUSTIN 2 MILE ETJ | SOUTHEAST |   | 7200 BLK ELROY RD | Travis County | Not Complete | Near Most Adjacent Area
1154 | AUSTIN 2 MILE ETJ | SOUTHEAST |   | 7200 BLK ELROY RD | Travis County | Not Complete | Near Most Adjacent Area
1158 | AUSTIN 2 MILE ETJ | NORTHEAST |   | CRYSTAL BEND DR / IMMANUEL RD | Travis County | Not Complete | Near Most Adjacent Area
4050 | AUSTIN 2 MILE ETJ | NORTHWEST |   | QUINLAN PARK RD / CANYON GLEN DR | Travis County | Not Complete | Near Most Adjacent Area
4060 | WEST LAKE HILLS ETJ | SOUTHWEST |   | 1310 BLK WESTBANK DR (Westlake High School, East of Camp Craft Dr) | Travis County | Not Complete | Near Most Adjacent Area
4061 | AUSTIN 2 MILE ETJ | SOUTHEAST |   | SLAUGHTER LN / ORCHARD RIDGE  (IDEA School) | Travis County | Not Complete | Near Most Adjacent Area
4081 | AUSTIN 2 MILE ETJ | NORTHWEST | 10/6/2023 0:00 | STEINER RANCH BLVD / GRIMES RANCH RD | COA | Complete | Near Most Adjacent Area
4083 | AUSTIN 2 MILE ETJ | SOUTHEAST | 10/6/2023 0:00 | 4500 BLK ROSS RD | COA | Complete | Near Most Adjacent Area

**Comment by andrewshensky** [comment]
The Signal Engineering Areas data has been updated in Maint and pushed to DM. Since the AGOL dataset is owned by CTM we can't make that update on our own. I have submitted a CTM request to the get the DM data pushed to AGOL prior to standard automated updates that would update the AGOL dataset in early February.

**Comment by andrewshensky** [comment]
The updated data has now been pushed to AGOL. All 31 locations provided above should now fall within a signal engineering area polygon
