### ISSUE TITLE
Job posting for App Analyst

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1482]
We've got something to work with already! [Here's the last posting for this position](https://docs.google.com/document/d/163hLhAyZogRUgWsHcFWnt8N0IQWuglJiySJCH8grnx4/edit)

Post to:
- COA website
- Slack
- ACC
- Bloomfire
- Open Austin
- UT / Geo-society

**Comment by johnclary** [comment]
Sent to Jennifer for review.

**Comment by johnclary** [comment]
[Posted](https://medium.com/@coaatddts/job-application-analyst-austin-transportation-data-technology-services-f1bb644b2f6)!
