### ISSUE TITLE
Meeting with TreePlotter on 12/6

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14826]
## Agenda
- Overview of Work Order Process with TreePlotter
- API Capabilities:
   - Integration with ArcGIS Online
   - There is a work around that Urban Forestry uses currently that is fine to continue going

**Comment by ChristinaTremel** [comment]
## Notes from 12/6
- Work Order -> Work Tasks
- Work Orders can be categorized for reporting purposes
- Contractor Work Orders:
   - Can be filtered down based on Assigned To?
- Recommend using Chrome, but the web application has Mobile, iPad, or laptop devices
- Types of layers
   - Shapefiles
   - wfs
   - wms
- **License and Administration Management:**
   - Can add however many users that we need. There's no limit. 
- Contract pays for Reference Layers. Alan provided reference layers that they'd collected as needs from users:
   - Parks boundaries 
   - Creek lines
   - Parcel boundaries & COA-owned parcels
   - Streets
   - Sidewalks
   - Address points
   - ROW
- [API Article](https://support.treeplotter.com/knowledge-base/api/)
    - API key does not exist but can be added at any time
    - It's already in the contract and they will figure out invoicing with Emily.
    - Still considering whether we need to read or write to TreePlotter
    - Get, Post, Put calls and post calls for pushing data back into TreePlotter
- **Offline**
   - Can update work records
   - Can create and edit points
   - Can't add inspections
   - Have to set the location while still online
   - Dev team is working on revamping the offline application
   - Saved in your cache so you can't refresh or clear your cache
- **Clients backing up data automatically**
   - Yes, driven by API or wfs
   - Several customers use Arcpy to publish on ArcGIS Online
   - TreePlotter protects all their customers data and your data is yours
      - Pull back ups on a nightly basis and keep backups on the service for 3 days and then keeps it stored for longer
- **Contract Line Items:** 
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/90ebc358-89ff-40f9-8092-b1263b58f715)

**Comment by dianamartin** [comment]
# 12/6 - Diana's Notes
Participants: Maggie, Beth 

COA: Alan H., Christina, Diana, Andrew

Map - spatial view (terrain basemap)

- has two layers
- Service Requests and Work Orders
- Work Category: PHC

## Observations

- Photos attached
    - multiple?
- Work Order>Work Tasks
    - Location
        - Specifications
- Schedule button
    - repeat these tasks
    - once a year
- Offline
    - simple
    - limiting system
    - no inspections
- check out data - save to your cache
- 

## Questions

- User Experience?
    - Log In
    
- **What other cities, government agencies using this?**
    - City of Houston - Community - Customer Facing?
        - City of Houston: https://pg-cloud.com/HoustonTX/
    - PARD
    - WPD - not using TreePlotter for WO (Tree Inventories)
        - Floodplain buyouts
    - 
- **Multiple assets per work order?**
    - Location
        - Asset 1
        - Asset 2
- **License administration?**
    - unlimited users
    - staff & contractors
- **Mobile capability? responsiveness?**
    - iPad
    - mobile device
    - chrome
    - Offline capabilities
- **Custom basemaps?**
- Using API End point for NearMap
- Reference Layers (DSD Contract pays for it)
    - Shapefile/CAD files import
    - WMS/WPS layer
        - Charge to do that… $$$
- **REST EndPoint - API Integration**
    - Pull data out of
    - Charge - provide API key
    - no more than 30 per minute
    - Resource: https://support.treeplotter.com/knowledge-base/api/
    - Developer Documentation: https://app.swaggerhub.com/apis-docs/Plan-IT-Geo/planitgeo_pub_3/0.4.0
- Backing up Tree Data
    - WMS/WFS into ArcPro
    - Make data into 6 pages
    - Merge and publish to ArcGIS Online
    - Scripting this with ArcPy
- GetCall
    - getTree data
    - transform to systems
    - We can use Python
    - PowerBI
- TreePlotter
    - Your data belongs to you
    - Backed up nightly
    - 1 am
    - 3 day - long term storage
        - Can pull it back up
        - Revert to day before
    - Revert data and update data
    - After 3 days, TreePlotter will charge

**Comment by andrewshensky** [comment]
**Not as pretty but my notes are below:**
Additional reference layers seemingly need to be passed through Alan
Emily is still contact for invoicing 
API end point to pull data out and add data in
Houston uses treeplotter for community tree map
WFS into PRO - separate data into pages then merge data and publish to AGOL
Best to merge with ArcPy
Get call using API can get all features
Post can be used to add feature in from AGOL
TreePlotter rep recommend new trees to just be added direct
