### ISSUE TITLE
Maximo Report Request [Modification] Sidewalk Asphalt WOs not displayed for December 2023 in Surface Repair Report

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#14828]
WONUM 23-166707 is not updating in Surface Repair Report

SBODISTN Superintendent shares that work orders completed for the month of December is not displaying in Surface Repair Report.

**Comment by adry-martinez** [comment]
23-166707 - This was assigned to SBOCONC. PersonGroup updated to SBODISTN
23-164929 - This is a sidewalk failure.. the surface report collects on STREET SURFACE.

**Comment by adry-martinez** [comment]
Will need to schedule some time with CTM to review what is being collected on this report and to include ALL work groups

**Comment by adry-martinez** [comment]
Sent e-mail to CTM for support, pending response.

**Comment by adry-martinez** [comment]
### 1/31/24
Discussed with CTM Nick O. He will provide information on this report within the next two weeks.

**Comment by adry-martinez** [comment]
**2/11/24**

DTS Maximo has a scheduled meeting with CTM for status updates.

**Comment by adry-martinez** [comment]
### Mar. 1, 2024
![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/eb9ae432-aee2-410e-9084-bad4744b69bb)

Requirements indicate it will only read Street Surface assets, not Sidewalk. Will need to confer with CTM on how to add SIDEWALK in this report.

**Comment by GaneshKamarapu** [comment]
@adry-martinez @rebekkabry I have made the change and deployed this. The two workorders mentioned above will appear in 2024 fiscal year since they are completed post Oct 2023. report shows data from Oct previous year to Oct Current Year(Fiscal Year selected).

**Comment by adry-martinez** [comment]
6/4/24
Requestor notified
