### ISSUE TITLE
OCE Expiration Notification Features

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14821]
We'd like to be able to show this feature to the customers on Monday 12/11/23

**Comment by TracyLinder** [comment]
@dianamartin will add build notes

**Comment by dianamartin** [comment]
#  Build Notes
- [ ] Create new object `notifications`
- [ ] Add Field Headings
  - [ ] Notification_ID - auto increment
  - [ ] connection - producer
  - [ ] Expiration Date - Date/Time
  - [ ] 30 day CALC - Equation
  - [ ] 30 day Reminder - Date/Time
    - [ ] Add conditional rule when `30 day - is not blank - set to 30 day CALC`
  - [ ] 30 day CALC - Equation  
  - [ ] 60 day Reminder - Date/Time
    - [ ] Add conditional rule when `30 day - is not blank - set to 60 day CALC`
  - [ ] 60 day CALC - Equation
  - [ ] 90 day Reminder  - Date/Time
    - [ ] Add conditional rule when `30 day - is not blank - set to 90 day CALC`

**Comment by dianamartin** [comment]
# 1/17/24
@TracyLinder Susanne completed this, correct?

**Comment by TracyLinder** [comment]
Good to close.
