### ISSUE TITLE
Maximo, District Maintenance: Job Plan Update

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#14835]
Update SBODISTC to remove 10138004. See WONUM 23-166708

**Comment by ReneVarg25** [comment]
Added materials and users to job plan available.
Issues with adding tools: No ID for tools available, cannot add exact item names from list to job plan as field is not available to add exact item names. Added generic item titles to represent tools being used.

**Comment by adry-martinez** [comment]
@ReneVarg25  has this been completed?
