### ISSUE TITLE
Maximo, Austin 3-1-1: Update Work Log QRG to remove acronyms

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#14837]
Update Standardization QRG to expand on acronyms as acronyms must be approved by Austin 3-1-1 per their audit.

**Comment by adry-martinez** [comment]
- [ ] add table to other documents (see Teams Channel)
- [ ] update documents to replace acronyms
- [ ] update sharepoint with updated documents
- [ ] send e-mail to TPW Maximo Users re: new updated document (add the link to the sharepoint document, don't attach)

**Comment by ReneVarg25** [comment]
Combed and ensured non-approved acronyms have been removed
Added Table with Department Acronyms
Saved to PDFs

**Comment by ReneVarg25** [comment]
Uploaded PDFs to Sharepoint site

**Comment by adry-martinez** [comment]
@ReneVarg25 Is this complete?

**Comment by ReneVarg25** [comment]
Updates sent out to all users!
