### ISSUE TITLE
EzMaxMobile, Training: Update Quick Reference Guides

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#14836]
CSR Response Team requested updated version for EzMaxMobile copy & paste. 

Adjust Work Log templates for EZMax usage

**Comment by ReneVarg25** [comment]
Ask Matt M. about Airwatch on Legacy PWD Ipads/Tablets for EZMax users.

**Comment by ReneVarg25** [comment]
Instructions may change due to changes with Auto-Fill for work logs. Will hold until further updates.

**Comment by adry-martinez** [comment]
No updates to the QRG is necessary as the selection of the worklog will be auto-filled.
