### ISSUE TITLE
Missing Child WOs in Austin Water WO - Michael D.

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#14847]
Michael D. was reporting an issue with an Austin Water WO that he was working with. He reported that the WO came in without any child WOs, which was unusual for those to come in without any. Requested the Maximo Team take a look.

**Comment by ReneVarg25** [comment]
Reported Issues to Casey C., Casey escalated issues to CTM.

**Comment by adry-martinez** [comment]
@ReneVarg25  any updates on this?

**Comment by ReneVarg25** [comment]
CTM Resolved issues, Child WOs flowing into Maximo. Michael Durham notified.
