### ISSUE TITLE
Discovery Day: Experience Builder re-training / review / transitioning old web apps

### ISSUE THREAD

**Issue by GimnichD** [cityofaustin/atd-data-tech#14877]

**Comment by ATD-ZachB** [comment]
If anyone has questions please do not hesitate to dm me on Teams!

Here is an example of a Story Map that has already been transitioned to Experience Builder.
 https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fexperience.arcgis.com%2Fexperience%2F35b29e96ec7349159deea8d9cd99945e%2F&data=05%7C01%7CZachary.Berry%40austintexas.gov%7C32e920b355d5460ee26a08dbf2abc82b%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638370591825028102%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JyPU1S3GNtWrBeajTsDJw4yhzxVmHxZ7ss2ZDvlnkyY%3D&reserved=0

**Comment by Colemonj** [comment]
Here's the unfinished dashboard I worked on today, I hope to find some time next week to tinker with it a bit more. Have a great week end yall!

https://experience.arcgis.com/experience/0aa60075d37e48c9a79b8402f716457d/?draft=true

**Comment by andrewshensky** [comment]
Closing this out to get it off our in progress list
