### ISSUE TITLE
Create Design Brief for ACC UX/UI Lab

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14876]
## Description
We're partnering with ACC in their upcoming Sprint Semester starting January 22nd.

**Comment by patrickm02L** [comment]
Design Brief can be found [here](https://docs.google.com/document/d/1L63fkQTNEVPgrUtpl0fyJ-hCobrjqTCXFZbw3rkx2LY/edit#heading=h.5ckvybozamw6).

@amenity would you please take a look at this brief. I'd love to get your eyes on it to see what can be include/excluded, and any questions you might have before I send this off to David.

**Comment by amenity** [comment]
@patrickm02L - this looks great!

A couple points we should keep in mind that don't necessarily belong in the doc: 
- The Dev team is unlikely to have the time to _implement_ any of these recommendations during the fellowship
- We should be biased toward designs that _simplify_ the codebase or make it easier to maintain
