### ISSUE TITLE
Maximo workflow organization & translation services for MS outlook

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#14888]
# 1. Maximo Workflow Organization
- Create workflow for Urban Forestry in Miro
- Create placeholders frames & workflows for other SBO groups in Maximo in Miro
  - [`SBO Maximo Workflows`](https://miro.com/app/board/uXjVNJbfmVE=/)
- Work with Christina, Rebekka, Adry?

# 2. Translation Services for MS Outlook
related to #14846 - `Spike: Add Google Translate widget to Knack Living Street App`
- SMO is wondering how to communicate with community members if various languages that the City supports
- Have tested MS Outlook translation, right now only translates incoming emails not outgoing
- Trying to find a better way than to copy & paste from MS Outlook into Google Translate for example

**Comment by maccallump** [comment]
@dianamartin do you know what 311 uses?  Does Maximo have this capability?

**Comment by dianamartin** [comment]
@maccallump This was for Discovery Day. I had hoped to work on two different things and they aren't related. 

I don't know what 311 uses. They probably get translation services for the intake of their app (I think). We could ask Carrie/Patty, but not sure if that's a priority.
