### ISSUE TITLE
Initial Progress and Prioritization Meeting with HR

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#1488]
### Objective 
There are a number of ways that DTS can support HR's operations:
- What are the most urgent needs?
- What belongs in the HR Knack app? 
- What can we offload to Formstack or a similar tool?

_**Current products/projects for HR**_
- [COVID-19 Time Tracking](https://github.com/cityofaustin/atd-data-tech/issues/2863)
- [Paperless Hiring](https://github.com/cityofaustin/atd-data-tech/issues/428)
- [PPE Inventory Tracking](https://github.com/cityofaustin/atd-data-tech/issues/2351); see also [Create Prototype for Uniform Tracking](https://github.com/cityofaustin/atd-data-tech/issues/500)
- [NEO Video](https://github.com/cityofaustin/atd-data-tech/issues/2862)

**_HR's most critical backlog items_**
- New Hire Forms/Paperwork
- [NEO Signature Page](https://github.com/cityofaustin/atd-data-tech/issues/2701) 
- PRF form used for recruiting and compensation matters
- New telework procedure and forms

**_Less urgent backlog items_**
- Leave mgmt. forms
- Compensation forms
- ER forms
- Some safety related items. 

### Participants
HR: Linda, Debbie, Adan, Jennifer, Emma, Chris & Nathan
DTS: John, Diana, Stephanie, Amenity, Surbhi

### Agenda
Create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and save as a publicly-visible file in Google Drive.

------
- [ ] Schedule meeting
- [ ] Meet and take notes in agenda doc
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
@dianamartin - would you schedule this please 🙏

**Comment by amenity** [comment]
@amenity please follow up with Jennifer, Nathan, & Adan.

**Comment by amenity** [comment]
Moving this to _Blocked_ until we get more info from Nate.

**Comment by amenity** [comment]
Per email from Nathan: 

**Most critical needs**
- New Hire Forms/Paperwork
- PRF form we use for recruiting and compensation matters
- NEO work Linda and Diana are doing, see #2685 . 
- New telework procedure and forms 

**Less urgent**
- Leave mgmt. forms
- Compensation forms
- ER forms
- Some safety related items. 

This meeting should include the entire HR team: Linda, Debbie, Adan, Jennifer, Emma, Chris & Nathan

**Comment by amenity** [comment]
Unblocked and updated accordingly. @moorerst will be leading this work. 
@SurbhiBakshi - roping you in on this too for good measure. ;)

**Comment by amenity** [comment]
@moorerst - please schedule for Sprint 27🙏

**Comment by moorerst** [comment]
Intake meeting will be scheduled after the current HR project for digital Telework Forms is complete.

**Comment by amenity** [comment]
_**Current products/projects for HR**_
- [COVID-19 Time Tracking](https://github.com/cityofaustin/atd-data-tech/issues/2863)
- [Paperless Hiring](https://github.com/cityofaustin/atd-data-tech/issues/428)
- [PPE Inventory Tracking](https://github.com/cityofaustin/atd-data-tech/issues/2351); see also [Create Prototype for Uniform Tracking](https://github.com/cityofaustin/atd-data-tech/issues/500)
- [NEO Video](https://github.com/cityofaustin/atd-data-tech/issues/2862)

**_HR's most critical backlog items_**
- New Hire Forms/Paperwork
- [NEO Signature Page](https://github.com/cityofaustin/atd-data-tech/issues/2701) 
- PRF form used for recruiting and compensation matters
- New telework procedure and forms

**_Less urgent backlog items_**
- Leave mgmt. forms
- Compensation forms
- ER forms
- Some safety related items.

**Comment by johnclary** [comment]
I see some good note in here and it looks like this can be closed. Feel free to re-open....
