### ISSUE TITLE
Attachments & Review Details (vehicles)

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14895]
- [x] Add an `Attachment` functionality for them to attach PDFs, Photos
- [x] For vehicles drop down during review process, Michael asked if we could add the vehicle list and have vehicle numbers as options
- [x] Need to add additional support types that Ryan sent to new sbo_support_types object
- [x] Add status for decision ` Request Approved`

**Comment by dianamartin** [comment]
# 12/12
- Realized I already started creating an object
- [x] Object created `sbo_attachments` table
- Field Headings
  - Attachment ID
  - Attachment - file
  - Description
  - Attachment Type
  - Created By
  - Created Date
  - sbo_coordination_request - connection
- [ ] Add menu
- [ ] Add page/form
- [ ] Add table

**Comment by dianamartin** [comment]
# 12/12
- Asked around about SBO vehicle list
- Ryan said to ask Tyler (Logistics)
- I asked Adry and she gave me what was in Maximo

**Comment by ChristinaTremel** [comment]
This was completed and was in a Review/QA status. Closing this issue!
