### ISSUE TITLE
TCP Upgrade: Organization Structure and Account Management Initial Build

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14891]
1. Data Objects and Fields 
2. Customer Portal menu & pages (now named ROW Portal)
3. Customer Dashboard menu & pages

**Comment by KaroEngstrom** [comment]
## Back Office Object Tables and Fields 

- `ROW_organization` object created 
<img width="1004" alt="image" src="https://github.com/cityofa stin/atd-data-tech/assets/100615928/de8185bf-5b49-47ac-8771-410aa1f79e24">
 
- 🚨 once a user is logged in with org account, applicant/requester address details will autofill from their account - they just need to application fields 

- **Account type** field on the account objects
     - Primary Account toggle Y/N
     - will show on the organization if a primary user exists for that organization 
     - each user should be connected to an org; each org should have a primary user 
     
- 🚨 Primary User has two extra abilities: 
     - manage accounts and their associations 
         - invitation to login - account is created already, user sets their password 
     - manage organization information 
         - updating address, etc. 
 
 - Customer account role added

**Comment by KaroEngstrom** [comment]
## Customer Portal Builder Session 🏗️  12/13/23 
- @ChrispinP and @KaroEngstrom co-building; Chrispin driving Builder 

### Notes
- ✅  Copied the Customer Portal to allow building side by side (cannot hide views from a public page) 
- ✅  New: Customer Portal: 
    - Not Signed In - will be the new portal before people log in 
    - Sign In - will be the signed in version once the user is logged in 
    - Copying the pages over
- ✅ Log-In ability from the Customer Portal 
    - Added Customer Home page where Log In and Sign Up views will be housed 
    - Need to recreate the rest of the welcome page because we cannot copy them over to a Login page 
    - Rich text views and Login view created on the Services (Available Services) page
    ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/3443ef6d-9181-4acf-9df7-88c04ea9c65b)

- 💥 Problem - hiding dropdown from logged in users - how do we manage not signed in and signed in side by side as they'll have separate dropdown items accessible and we don't want duplication once a user is logged in? 
    - 💡 Solution: turn each of the Services pages into a login page where we copy the current Service views (Customer Home/Welcome already done; need to do TCP and CSWZ) 
    - Need to rebuild the service pages as login pages - Services menu has to be rebuilt fresh from every login page 
    - Customer can go to service page to log I
- Creating an Account - need to create a sign up for account page, show as a modal (via default menu) x 3 
- Everything below Contact Us on Miro should be in a different menu, name TBD, calling it "My Cases" for now
- Solution for public/logged in - create two separate menus
    1. Customer Portal - Services pages with login/sign up options + Contact Us page (all public) 
    2. “My Cases” menu - all of the pages connected to the logged in account, not visible until the user has logged in 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/199e4a18-b9e0-4daa-aa01-5fee47194031)

**Comment by ChrispinP** [comment]
Discovered some complications:
- Redirects cannot occur for the scene beneath a login page
- Enabling the Sign Up option for a login view prevents it from being viewable in a dropdown menu
- All Child pages are not viewable from login pages (includes modals) which means our Services, TCP, CSWZ, and Contact Us pages in the Customer Portal menu cannot be put behind a login or all modals will ask for a login

Actions:
- Copied necessary pages/views to replicate menu
- Created blank customer User Pages
- Created customer_announcement object
- Added Menu Button to a login page for each Dropdown menu page
- Enabled and Updated the Signup page, Accounts object, confirmation page

**Comment by KaroEngstrom** [comment]
## Fri 12/15/23 
- @ChrispinP  and @KaroEngstrom  met with @TracyLinder  and @HomerArizpe to review progress and issues so far
- looked over the structural issue of not logged in/logged in items 
- agreed on solution to use dual dropdowns: 
     - ROW Portal (not signed in, public pages) and 
     - Customer Dashboard (logged-in user, secure private pages) 
- to resolve for the sign in/sign-up issue, we are using a separate login page where each of the main public pages directs to: 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/a0276e00-f558-41ec-a1dd-3e34a6f59e34)

- the post-login page for that login will serve as the Overview page for the logged-in user

**Completed Work:** 
- [x] Updated the dropdowns
- [x] Created new login pages for each of the Customer Dashboard sections 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/42b31eb5-93c4-449f-8264-676a6fed8528)
- [x] Quickly tested the dropdown visibility in portal 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/47cf7c32-044e-407b-8180-2d8858772271)

**Next Steps:** 
- Start building the first version of Customer Dashboard component pages: 
     - Overview 
     - My Projects 
     - Messages
     - Profile 
     - (Documents in a placeholder page for eventual, non-MVP feature discussed for a later enhancement)

**Comment by KaroEngstrom** [comment]
## Mon 12/18/23 
- Under My Projects, got started on pages for TCP and CSWZ 
❓ about structure 
     - do we want to use the faux-tab structure or separate buttons (won't inherit to child pages)
