### ISSUE TITLE
Resolve missing crash diagram and narratives on the crash pages

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14899]
fill out details, refer to [thread](https://austininnovation.slack.com/archives/CM9MK950S/p1702038323069209)

**Comment by chiaberry** [comment]
assigning Frank since he has been working on the issue

**Comment by frankhereford** [comment]
Thanks @chiaberry for this assignment.  🙏  I'm not sure if y'all talked about this yesterday, but today in dev sync if needed, I'll use my time to really quickly go over what my proposed fix is for this problem to make sure everyone likes the scope and then adjust my PR if needed to implement the group's plan. Thanks again!

**Comment by chiaberry** [comment]
@frankhereford we didn't talk about it in planning, looking forward to hearing about it today in dev sync!
