### ISSUE TITLE
Email notifications for SBO Coordination

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#14894]
- [x] Email notifications for when `Assigned To` changes on coordination request
   - Language Template: 

         Hello,

         A coordination request has been assigned to you. 

         Request ID: {SBO_CR_ID}
         Requested Support: {Requested Support}
         Estimated Support Start Date: {Estimated Support Start Date}
         See Coordination Request [Details](link to details page)

- [x] Email notifications for when a review decision has been made, send email to `Created By` 
   - Language Template:

          Hello,

         A review decision has been made from your coordination request.

         Request ID: {SBO_CR_ID}
         Requested Support: {Requested Support}
         Status: {Status}
         See Coordination Request [Details](link to details page)

**Comment by KaroEngstrom** [comment]
## Fri 1/26/24
-
