### ISSUE TITLE
[Enhancement] Update Data Tracker MMC issues to support `Traffic Signal - Modification`

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#14920]
1. Add `Traffic Signal - Modification` as a select option on the `ISSUE_TYPE` and `ISSUE_TYPE_MANUAL_CREATE` fields
2. Create record rule to set the `ISSUE_TYPE` field to `Traffic Signal - Modification` when the `PRC_CODE` field is `ATTRSIMO`.

**Comment by johnclary** [comment]
@ChristinaTremel @dianamartin FYI this is what is needed when adding a new SR type to Data Tracker. This is the first time this has happened like maybe ever.

**Comment by ChristinaTremel** [comment]
Thanks for documenting it! 🙏🏼
