### ISSUE TITLE
Bulk Update TLC forms before 10/1/2023 to "Approved"

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#14922]
Jennifer W
HR

Messaged with Jennifer on 12/8

I said
>We still have a lot of outstanding TLC forms that didn't have a signature from the Department Head/Designee, would you like to clear them out?

She replied
>Yeah, let's clear out the old. 

I replied
>Should I just batch update them all to "Approve"?

she replied
>If the managers have approved, yeah lets just batch approve them. Sounds good

**Comment by dianamartin** [comment]
# 12/12
- `197 records` in "Department Head/Designee" status
- `15 records` created after 9/30/2023
- `182 records` need to be batch updated to "Approved"

**Comment by ChristinaTremel** [comment]
Let Jennifer know this during the HR sprint review in December.
