### ISSUE TITLE
ETL MDS: Sync with Knack

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#1492]
We are going to need to integrate with Knack from the MDS ETL, this issue is in relation to implementing that functionality. We will need to:

- [ ] Create entries for the knack configuration in S3
- [ ] Retrieve the Knack configuration from S3.
- [ ] Map the knack table 
- [ ] Test retrieving monthly data.

- [ ] Implement DAG in Airflow to run every 1st or 2nd of every month

**Comment by sergiogcx** [comment]
In progress, there is a PR:
https://github.com/cityofaustin/atd-mds/pull/13

**Comment by sergiogcx** [comment]
I need more details as far as what the final tables in knack look like, I will be creating a small table to start implementing and testing functionality.

**Comment by JaceDeloney** [comment]
@sergiogcx  I'm not sure that I understand what this work enables. Is this related to per-trip fees or is this for another request?

**Comment by sergiogcx** [comment]
This is long done, closing.
