### ISSUE TITLE
Knack Finance & Purchasing | Invoice items (created from inventory items) not connecting to purchase requests

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#1493]
Invoice items created from purchase requests items in the Purchase Request details view are failing to connect. The following fields are mapped to each other and used to create a new invoice item record through  a POST to an API Form view (`scene_123` and `view_698`).

```
   invoiceItem["field_409"] = [{ id: record.id, identifier: record.field_15 }]; // Item id and description  
   => Invoice item description 
   invoiceItem["field_773"] = record.field_20_raw; // Purchase request => purchase request
   invoiceItem["field_422"] = record.field_38_raw; // Total Cost => Amount Due
   invoiceItem["field_733"] = "Yes"; // Mark Received as "Yes"
```

### Knack objects and field IDs for `purchase_request`
**purchase_request_items** (`object_4`) `field_20`
**invoice_items** (`object_20`) `field_773`

### From Slack DM with John and Diana:
>She was trying to create an invoice item on this record, https://atd.knack.com/finance-purchasing#purchase-requests/purchase-request-details/5cc8c1f8ebec8f000978f7b1/ and it didn’t show up for her in the invoice item table.

>I looked at the code and network req’s and a record is POSTing to Knack with the correct purchase request ID to make the connection, but the response comes back from Knack with that field as an empty string. I’m a little stumped on this and could use some help.

>Here are some screenshots of the payload and response.

### Data sent in POST to Knack
![Screen Shot 2020-02-26 at 5 05 33 PM](https://user-images.githubusercontent.com/37249039/75461453-71346d00-5948-11ea-8eec-395e1851136c.png)

### Response received back
![Screen Shot 2020-02-26 at 5 22 29 PM](https://user-images.githubusercontent.com/37249039/75461460-742f5d80-5948-11ea-9db6-7124b57fbeb8.png)

**Comment by dianamartin** [comment]
### Purchase Request IDs that didn't have their received items connected
Rosie B.
- [x] `2019-0564` - manually associated 2/26
- [x] `2019-0610` - manually associated 2/26

Denise R. 
- [x] `2020-01-1341`  - manually associated 2/27
- [x] `2020-01-1385` - manually associated 2/27
- [x] `2020-01-1387` - manually associated 2/27
- [x] `2020-01-1380` - manually associated 2/27

**Comment by dianamartin** [comment]
Called and emailed user to let her know that the PRs have been fixed and the correct received items are now showing up. Mike said he and John were able to troubleshoot and fix the issue. The API view we had was missing the `purchase request ID` field.

**Comment by mddilley** [comment]
Issue was traced to the `purchase_request` field missing from the Create Invoice Item API Form view (https://builder.knack.com/atd/finance-purchasing#pages/scene_123/views/view_698). 

Field was added and invoice item record creation was tested in the PROD app to confirm that new records were associating to purchase requests (and showing in the Invoice Items table of the Purchase Request details view). Closing.
