### ISSUE TITLE
ETL MDS: Use random ids and round to the nearest  

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#1494]
We must change: 

- [x] Use random id instead of current identifier
- [x] Round start/end times to the nearest 15th minute

**Comment by sergiogcx** [comment]
PR: https://github.com/cityofaustin/atd-mds/pull/14

**Comment by amenity** [comment]
@sergiogcx - should I move this to In Progress and mark for Sprint 19?

**Comment by sergiogcx** [comment]
Ah, this is in progress. Done in fact in staging, but we need to discuss for production.

**Comment by sergiogcx** [comment]
The YTD data is now good to go in staging, https://data.austintexas.gov/dataset/-UNDER-CONSTRUCTION-Shared-Micromobility-Vehicle-T/aaxm-wc67


Closing this issue and opening a new one for production.

**Comment by sergiogcx** [comment]
New issue:
https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/1509
