### ISSUE TITLE
[Enhancement] Subphase additions for Smart Mobility Office

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#14942]
Smart Mobility would like to request the following subphase enhancements. Below you will find a list of all the subphases we would like to have included within the existing phases:

These records will be added to the [`moped_subphases`](https://db-docs.austinmobility.io/atd-moped-production/tables/moped_subphases.html) table. Please check and see what the subphase "description" column is used for and let me know if you need additional details about what values to use for these columns.

> Potential
> 
> - Add Subphase: Discovery
>  
> Scoping
> - Add Subphase: Vetting
>  
> Pre-Construction
> - Add Subphase: Commissioning
>  
> Construction
> - Add Subphase: In-Service
>  
> Complete
> - Add Subphase: Close-Out

**Comment by roseeichelmann** [comment]
All but 3 of the current subphases have `null` for their "description" column, so i dont think its necessary to add anything unless we want to for our future reference? seems like its just used for the devs to see what the row means?
