### ISSUE TITLE
Maximo Sync - Training and Resources Discovery Notes

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#14962]
### Background
**Objective**: 
- Support the MAXIMO training initiatives and aid in implementing MaxMobile into utilization among crew. 

**Current**: 
- Tablets have been provided to crew members. There is not a requirement to use app, crew are still able to determine solution. 
- Team not currently utilizing the support resources available. (like Sharepoint resource page) 

**Challenges**: Different solutions, aim to maximize resources and new solution and align support expectations. 

### Shareholders 
- Maximo Support Team (Adrianna/Rene) 
- DTS Support Team (Diana, Rebekka, Christina, Peggy) 
- MAXIMO Users (all users for feedback and alignment discovery)

**Comment by rebekkabry** [comment]
[Sharepoint ](https://cityofaustin-my.sharepoint.com/personal/rebekka_bryant_austintexas_gov/_layouts/15/onedrive.aspx?id=%2Fsites%2FDTSTraining%2DTEST%2FShared%20Documents&listurl=https%3A%2F%2Fcityofaustin%2Esharepoint%2Ecom%2Fsites%2FDTSTraining%2DTEST%2FShared%20Documents&view=0)Test Drive for Form and Quizzes into Stream

**Comment by rebekkabry** [comment]
- [ ] Get a baseline of the current field crew mobile app usage 
- [ ] Get insight into the challenges around not using 
- [ ] Consider solutions to aid in increasing usage and minimizing errors/fears around implementing 
- [ ] How can we support MAXIMO support team?

**Comment by rebekkabry** [comment]
### 12/2023 In Person Mobile App Training Notes 

- Everything on desktop is on the mobile app. Nothing is different 

**Usage Processing and Steps** 
- Find SBO district group: Swipe to the left. 
- Bulletin board: linked to Maximo notes 
- SBO work order tracking = buckets 
	-  Q: groups pick their bucket by? 
	- Ex: newly created work orders 
- Advised don't use start button - due to the way the app processes the request
- Attachments Features (newly added) 
	- Nice functionality 
	- picture add, and edit 
	- search options 
 
@@@failure reporting links to assets health and maps. 
 
@@@log notes/ speech to text 
 
@@@training documents, quizzes, start date to implement across team, expert or team leads to help. Add quizzes to the videos and documents that she is creating. Passing scores and participation allows you Tobe able to use. Add implementation of support when
 
@@@domt allow to get off screen without entering manual parts in failure, labor, etc. 
 
@@@@maximo shortcut 
 
 


---------------------------
### Recommendations 
- Baseline Status
What 
+ Answer: Do we want to encourage usage of the mobile app in most or all cases, role dependent? 

- Groups/Buckets determined by role and have a specific view, not all or requiring filtering when logging in.
_Thoughts: `APPS `is there a way to provide the advanced search scene automatically without the search process. - Workgroup_
 
- Can statuses be linked in on the appropriate group? 
_Thoughts: Some groups don’t use all same. Status codes dictionary._ 

- Auto naming standardization of picture attachments.
_Thoughts: In additional to being able to add specific notes and tags, all attachments could be auto coded with the WO# and other identifying information of its Parent or Work ticket._  

+ Currently no videos, could create videos focusing on mobile app instead of desktop version.

**Comment by rebekkabry** [comment]
Emailed @adry-martinez to get insight of value of EzMaxMobile training material. Pending updates and DTS leadership further insights.

**Comment by rebekkabry** [comment]
### Sample Proposed Condensed Outline of Considerations: 
-	Get baseline survey of usage / attitude around app. 
-       Begin recording and using Syncs as Tutorial Report pulling, etc 
-	Using Scribe to create new EzMaxmobile training material. 
-	Work with BI to develop Q/A for training retention.
-	Develop training and implementation process for EzMaxMobile. 
-       Work with top down with training initiatives, roles and expectations, training, etc. 
-	Get status of usage/attitude around app, after initial Q/A training efforts.

**Comment by rebekkabry** [comment]
Example: 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/1582820a-1b97-4e73-a92e-6d72f32baa0a)

**Comment by rebekkabry** [comment]
[PDF Training Doc](https://teams.microsoft.com/l/message/19:meeting_ODY2NWE0NzUtZDViZS00NmNmLTk2MDEtZTIwZjhmN2E3OWYz@thread.v2/1706900586356?context=%7B%22contextType%22%3A%22chat%22%7D) created by @adry-martinez

**Comment by rebekkabry** [comment]
### Sharepoint Usability Focus scheduled 2/21/24
- [ ] Set up mock up workshop
- [ ] Get videos on Github
- [ ] Update calendar to show training sessions coming up

**Comment by dianamartin** [comment]
# 2/12/2024
## STEPS
- Create GitBook Maximo Resources - @dianamartin 
  - To improve Maximo user's UX for Maximo training/reference information
- To improve Maximo Account Requests - @dianamartin 
  - provide Maximo team "Employee List" view to see Employee ID
  - to improve Maximo team's process
- NEW issue: Improve Maximo Resources SharePoint - Karo/Diana
  - to improve the self service process for any TPW employee that needs Maximo information
- Training Education Form
- IDEA: Process Change
   - Require quiz before account creation?

**Comment by rebekkabry** [comment]
### Apps Sync Insights 2/13/24
- @KaroEngstrom buttons, use icons. 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/f9176247-5050-4a9c-b75e-96dae43493e9)
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/672d9f74-d055-42df-a106-6ce23c040852)

**Comment by rebekkabry** [comment]
### Feedback with MAXIMO Team - Sharepoint Usability Workshop 2/21/24

@adry-martinez - Looks great so far! 
- would like to see the newsletter or link to newsletter. Scrolling view on the front page, ideal. 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/052c049e-653b-4830-b67e-857a7a780422)

@dianamartin 
Reviewing the mock up page that she created with apps team. \
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/86868bce-3353-4e31-b956-8a3836cbcb7f)
- Where to put the document? Okay with hiding the document library. 
- QRG Pages Questions - PDF vs Back-end version. Why is there both? Not sure why they are located in multiple places. We can leave in the back, but still bring it forward. Deciding to keep it. 
- Few that didn't seem completed? Example: FAQ/Contact Page. There are some things we need to omit, that is still there from prior revamping and updates. 
- Booking and Time to Chat - ready for booking when team ready to accept. 
- Form - updated to pre-select MAXIMO, mentioned enhancement from Apps meeting. Would like to have implemented. @dianamartin

**Comment by rebekkabry** [comment]
**Projects / Epics Supporting Efforts** 
Sharepoint / MAXIMO User Resources Redesign #15944
MAXIMO Mock Training Series #16061 
Model Work Orders 
Scribe Work sessions

**Comment by rebekkabry** [comment]
# Updates 

- Revamped Gitbook/Sharepoint 
![image](https://github.com/user-attachments/assets/0f451102-0905-48d3-bcbf-8c2f517646e5)
- Multiple projects and ititatives started and completed as a result of this assessment. 
- Start Center Project
