### ISSUE TITLE
[BUG] Clicking the advanced search menu button resets the advanced search filters

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#14961]
**Steps to reproduce**
1. Add some advanced search filters and click the "Search" button to apply them
2. Open the advanced search menu by clicking the settings icon button inside the generic search bar
3. Click the the settings icon button again to close the search bar
4. Now, once again, open the advanced search menu by clicking the settings icon button inside the generic search bar
5. Observe that the search settings have been reset 💥

**Comment by mddilley** [comment]
See [discussion here](https://austininnovation.slack.com/archives/CNUEPKLB1/p1703781748548999)

**Comment by tillyw** [comment]
closing out this bug as it was addressed with [Mike's pr](https://github.com/cityofaustin/atd-moped/pull/1236/files#diff-8f036d1f27531f5d072277146fa5bc1bdbb11ae2e6260b9e443249a0fbcd9065L123)
