### ISSUE TITLE
Restore airflow docker image building by addressing changed key in mysql's apt repo.

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#14975]
Please see the first note regarding the expired key and the replacement here: https://dev.mysql.com/doc/refman/8.0/en/checking-gpg-signature.html.

It appears that mysql is handling a key reissue in such a way that it has not made it into downstream key servers or other chains of trust such that apt commands in docker image builds fail due to authentication failures. 

This issue is to track the installation of the correct key in this docker build process so that it can complete normally, or perhaps more likely, this gets sorted out by mysql.com and the various key servers that `gpg` relies on. The key only expired today, and this may resolve itself after approximately 92837492873 downstream build processes all start failing today and the mysql crew gets this sorted.

I am able to reproduce this with a multi-arch build locally, which makes testing a solution available to us without having to push it up to GH.

**Comment by chiaberry** [comment]
I believe this fixed itself, closing since the github actions are back in the green
