### ISSUE TITLE
IT Support: Simulator DOWN!

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#14972]
DALTON

## Device & User Information (first name and last initial, no last names)
Jesse B
## What's the problem?
Simulator went down
Hi Mike, 

Jesse and I shopped around found some awesome TVs. this is the perfect time to purchase a TV since it’s the holidays.  Would it be possible for us to purchase 3 of these so that we can replace all the TVs in the simulators? They are all in need of replacement. 

The TV we have in mind is priced at $240. When you consider that, for the cost of a single TV, we can secure three. Plus we do not need a top of the line TV. 

https://www.bestbuy.com/site/insignia-55-class-f30-series-led-4k-uhd-smart-fire-tv/6450247.p?skuId=6450247&extStoreId=1153&utm_source=feed&ref=212&loc=20752544040&gad_source=1&gclid=Cj0KCQiA7OqrBhD9ARIsAK3UXh2Sw7643nRdVPuyb0G77JI69GjK09KV2K80oYPdI0jfz0vmIQscAzIaAuw2EALw_wcB&gclsrc=aw.ds

Also Jesse has a DVD to show to the people being trained. I recently had to replace the machines computer. The new computer does not have a DVD player. Can we purchase him a DVD player?

https://www.bestbuy.com/site/lg-8x-external-usb-double-layer-dvdrw-cd-rw-drive-black/5852919.p?skuId=5852919 

Cheers,

Matt Martinez
Austin Transportation Public Works
 
512.974.9718 Direct line

**Comment by Matthew-M-TPW** [comment]
Grader Simulator went down

**Comment by dianamartin** [comment]
# 12/19
On 12/15, Matt put together an email for the stakeholder, Mike B, (see thread above)

I had asked Matt to check out Staples to price compare. Mike B, said he'd purchase items on his procard. 
>Matt send me the info on what is needed in a PDF I will use my procard. Include DVD  
thanks Mike

**Comment by Matthew-M-TPW** [comment]
waiting on TVs to arrive

**Comment by dianamartin** [comment]
# 1/4/24
Matt is going to ask Mike B. to submit a PR for the tv for the simulator

**Comment by Matthew-M-TPW** [comment]
Swapped the screens out the simulator is now working
