### ISSUE TITLE
[Tablet Support] 6 tablets ordered for AMD - waiting for 6th user late Jan

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#14986]
Below are the tablets assigned to Scott F. They are for inspectors

These are the 6 tablets
J0JRXYCXPC | iPad Mini 6 GEN wifi+cellular |   | COAW79594
HFC637R2M1 | iPad Mini 6 GEN wifi+cellular |   | COAW79595
L206Y23CVQ | iPad Mini 6 GEN wifi+cellular |   | COAW79596
HPVGY173RP | iPad Mini 6 GEN wifi+cellular |   | COAW79597
G9YRYYN4MT | iPad Mini 6 GEN wifi+cellular |   | COAW79598
G0Q1JPJVY | iPad Mini 6 GEN wifi+cellular |   | COAW79599

# To do
- [x] Label tablets
- [x] Add Screen protectors
- [x] Setup 5 Airwatch Users tablet and add device
- [ ] Track tablet re-assignment in DTS Portal
- [ ] Add 6th user to Airwatch after early January

**Comment by susannegov** [comment]
Messaged Scott on Teams at 12/18:

> Hello Scott, I was informed that AMD ordered 6 iPads for inspectors. The iPads are at Cameron currently, but we need to register the users to the iPads on AirWatch before they can be used.
>  
> Could you give us the first and last names of the people assigned to the tablets?

**Comment by scottreedy** [comment]
Please get with Scott Feldman as to who will receive these iPads

**Comment by susannegov** [comment]
Added 4 users to Airwatch and added devices 

Created INC0351477 service ticket for Ben H. to move from CTM to ATD group on Airwatch.

6th person unknown until early January

**Comment by susannegov** [comment]
Added 5th user (Ben H.) to Airwatch Group
All 6 tablets are labeled: (COA Tag, Serial Number, IMEI)

Scott F. said he would like to have them at early January.

**Comment by susannegov** [comment]
I gave Scott F. the 6 tablets, 6 chargers, as well as the iPad deployment PDF.

Also informed him to let us know when the 6th person available to provide credentials into Airwatch

**Comment by susannegov** [comment]
Talked to Scott F. yesterday. He said the 6th user name will be available in late Jan.

**Comment by ChrispinP** [comment]
@susannegov Were you able to speak with Scott for this 6th tablet? If we need to wait longer, I would advise we close this issue out and create a new issue for that 6th tablet when the need arises.

**Comment by susannegov** [comment]
@ChrispinP Talked to Scott just now. He said the 6th iPad is unassigned for now since the 6th user already has a device. Closing this issue.
