### ISSUE TITLE
LM: Performance Data 2019-Current

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#14988]
### 1 - Itemized Data
**Parameters**

- Foldertype is LM
- Subtypes: Easement Release (50681) and License Agreement (50687)
- Folder Status is Approved
- 1st Payment Date must be 1-1-2019 to current date

FolderRSN | Subtype | 1st Payment Date | Folder Issue Date | Total Duration
-- | -- | -- | -- | --
12318867 | Easement Release | 11/13/2019 | 12/5/2019 | 22

### 2 - Average issued per month
 
**Parameters**

- Foldertype is LM
- Subtypes: Easement Release (50681) and License Agreement (50687)
- Folder Status is Approved
- Folder issue date must be 1-1-2019 to current date

**Output:**
- Average # of folders issued per month, grouped by the subtype

Type | Average Per Month
-- | --
Easement: | 5
License Agreement: | 5

**Comment by Lpriya-LIT** [comment]
@TracyLinder Please find the data attached herewith for the 1 - Itemized Data and 2 - Average issued per month

**Comment by Lpriya-LIT** [comment]
[LM - Itemized Data.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemh1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a214ad32cccf26c1b5616c18c336b5c4bd35750/LM%20-%20Itemized%20Data.xlsx)

**Comment by Lpriya-LIT** [comment]
[LM - Average Issued per month.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejV1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a425d693b5ff97974a56de5f58ad7169c6b30cbf/LM%20-%20Average%20Issued%20per%20month.xlsx)

**Comment by TracyLinder** [comment]
Customer is happy with the data. Closing.
