### ISSUE TITLE
[Bug] Diagnose and fix connection I/O errors for VZ read replica

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#14987]
Both Xavier & Milad have reported a transient error related to their connection to the VZ read replica. I have not been able to replicate it, but I also have not tried from a windows machine, which is what they have experienced the problem on. I have a suspicion that i's related to the VPN as well.

Xavier provided this screenshot, and indicated that he was working remotely:

<img width="478" alt="image" src="https://github.com/cityofaustin/atd-data-tech/assets/3653206/6b74c3e7-92d2-4638-9152-bb21e8602902">

Milad wrote:

> I also had a few connection failures but everything seemed to be working after a few attempts. I have not changed anything in the process. Could it be coming from the server?

**Comment by patrickm02L** [comment]
## 12/20 
Chatted with @xavierapostol who said that the read replica works, but not optimally. There's a weird error (see above) that he gets when he opens certain queries. When he reconnects from the db, everything works great. 

I asked if he was on VPN, and he said yes and no, but revealed that his Issues happened primarily on VPN.

**Comment by xavierapostol** [comment]
And just to clarify, I have a workaround (just disconnect and reconnect from the server), but it is not ideal.

**Comment by frankhereford** [comment]
i suspect this is actually something internal to Windows in combination with the way the Cisco VPN works. When you get on or off the VPN, the network subsystem has to handle that switch over, and there may not be a way for the OS to communicate those state changes to applications. 

Put another way - i've not been able to replicate this on a mac, and i don't have access to a windows machine at this time to test this theory in any substantive way.

**Comment by frankhereford** [comment]
@xavierapostol I think we finally figured this one out. 

I have extended the idle timeout to 10 minutes up from 50 seconds. The changes are in place, I hope this fixes this problem for you! (For me too - I switched to linux at the house for my main computer, and I was getting this same behavior there.

**Comment by frankhereford** [comment]
I self assigned this and gave it a `0` size. I had inadvertently created a duplicate of this after a recent discovery around what was the issue, here: https://github.com/cityofaustin/atd-data-tech/issues/16226.
