### ISSUE TITLE
PM action items after Sprint Review

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1499]
- [x] Access to test environment for Finance team to review reports (Dan, Peggy)
- [ ] Need to determine if the quarterly management reports need to be available in excel format
- [ ] Provide number of property manager applications
- [x] Provide suggestions of end users who may want to participate in end user testing
- [x] People get confused if they need a day pass or construction pass, need education and awareness. Some language in FAQ? Follow up with Ryan.

**Comment by moorerst** [comment]
Need to follow up with PE staff

**Comment by moorerst** [comment]
sent follow email to RPP staff requesting responses to outstanding questions on quarterly reports and possible end user tester recommendations

**Comment by amenity** [comment]
@moorerst - is this ready to be closed?
