### ISSUE TITLE
[Enhancement] Change date selection to 'start date' and 'end date'

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14991]
## Description
broken out of #14514

> 2. Can we make the date selections be ‘start date and end date’ instead of ‘start date and duration’? PLAY STREET [also now wanting to adjust the timing of Play Streets]

**Comment by KaroEngstrom** [comment]
### 1. Start and End Date
- what restrictions are needed here? Assuming 3-6 month durations again? 

### 2. Adjusting Play Streets Schedule 
- what are the details on this?  
-

**Comment by patrickm02L** [comment]
## 1/12 in LS Sync
We can refer to the pop-up of definitions before applicants start to inform where in the application we need to add (info) pop-ups.

**Comment by patrickm02L** [comment]
## 5/7/24
This request is not viable and would take a considerable customize effort to complete. The start date with duration selection is the current model and is working as initially requested allowing for the reviewer to adjust the end date. We've had many discussions about the complications of making the start and end date adjustable, and do not recommend pursuing this request any further.
