### ISSUE TITLE
[Enhancement] New isolated status trigger button 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#14993]
## Description
broken out of #14514

> 5. Provide an option for reviewer to change status without having to click “Edit Application”

**Comment by patrickm02L** [comment]
## 1/12
Helped scope in LS Sync meeting, minor improvement.

**Comment by KaroEngstrom** [comment]
This got folded into the Activation Cycle rebuild of the system. 
Covered in #15537 and detailed in the [roadmap](https://docs.google.com/document/d/1iVMenicL6ulXnSJD7Ls6UoJbd2IfckelahYAUA3UlaM/edit).
