### ISSUE TITLE
Create issue templates for Knack apps

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15]
Let's define common issue templates that we will adopt across all of our knack applications.

I imagine at least four common issue types worth templating:
- Bug Report
- Feature Request
- GIS Request
- Reporting / Data Request

**Comment by johnclary** [comment]
Putting this in the icebox until we're sure it's needed. This may be redundant to the Knack (DTS) form integration.

**Comment by ChrispinP** [comment]
Our existing issue templates are pretty good. Should they be more exhaustive so we have more issue templates for each Knack app that we have and for different types of issues? This wouldnt be too difficult to build out.

**Comment by ChrispinP** [comment]
Amenity linked the page to update issue templates in the future so I dont have to do it in the repository. I was able to update several templates for several apps and will add new ones as needed.

https://github.com/cityofaustin/atd-data-tech/issues/templates/edit

Closing
