### ISSUE TITLE
Add Comments Section for Signals

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#150]
On signal details page. Mirror functionality from markings work orders.

- Do not need inline editing
- Do not allow to delete. We will revisit later if need to delete every often

**Comment by amenity** [comment]
@dianamartin - will you size this, 🙏 ?

**Comment by johnclary** [comment]
Issue moved to [cityofaustin/atd-knack-data-tracker #122](https://github.com/cityofaustin/atd-knack-data-tracker/issues/122) via [**ZenHub**](https://www.zenhub.com/)
