### ISSUE TITLE
Enable ADFS - RPP

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1500]

**Comment by amenity** [comment]
@moorerst @dianamartin - can you check the milestone on this?

**Comment by dianamartin** [comment]
@amenity I updated the milestone

**Comment by dianamartin** [comment]
I turned in a CTM HD ticket
- `CALL0029675`
- `REQ0044709`

**Comment by dianamartin** [comment]
- John D.  sent back metadata file. 
- [ ] Configure RPP ADFS

**Comment by dianamartin** [comment]
I was able to sit down and concentrate on getting the certificate's squared away. I tried logging in an I was getting an error, then I realized I didn't have an account set up (_my bad_). Added my account and logged in flawlessly. 

Success!
