### ISSUE TITLE
Unmetered Water Usage CY23

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15025]
This report is collected through unmetered water usage as entered in the Maximo Work Order Tracking system. 
This is to notify Austin Water Utility of Street and Bridges' unmetered water usage for the calendar year. 

The Maximo team will generate work orders at the beginning of each calendar year for each work group who will be responsible of updating these work orders on a monthly basis. 

Monthly, CY and FY e-mail reminders will be sent to users to ensure up-to-date data collection for accurate reporting.

**Comment by adry-martinez** [comment]
First reminder e-mail sent on 12/12/23 
Second reminder e-mail will be sent on 12/20/23
Final reminder e-mail will be sent on 12/29/23 

Unmetered Water Usage WOs for CY23 and CY24 WOs will be generated on 1/2/24

**Comment by maccallump** [comment]
Is this captured in each Maximo Work Order?

**Comment by adry-martinez** [comment]
> Is this captured in each Maximo Work Order?

It is tracked in two different ways:

1. using the unmetered water usage work orders created by Site Admins and
2. entering unmetered water usage in individual work orders

regardless of the method, it is tracked by the asset number of the equipment using the water item # (SBO1124).

**Comment by adry-martinez** [comment]
* Jan. 30, 2024 *
CY23/FY23 Unmetered Water Usage WOs closed.
<img width="1743" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUVVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--464737b4e3bdf2fdcfe1ef630090efe216582384/image.png" alt="image.png" />

**Comment by adry-martinez** [comment]
**Jan. 30, 2024**
CY24/FY24 Unmetered Water Usage WOs created.
<img width="1261" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVVVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5607e5bc34db8ef41feb8ecf8b788cc0c1c5cab1/image.png" alt="image.png" />

Users notified of new created WOs and how to track unmetered water usage on WOs.
