### ISSUE TITLE
[Enhancement] Unify various logins for Moped testing and development

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15039]
In order to address the [ongoing quirks](https://github.com/cityofaustin/atd-moped/pull/1227#issuecomment-1864780676) of user IDs + login in our seed data, user data, and the activity log. i would like to propose the following:
- [x] in prod, re-assign our “Data and Tech Admin” user from ID `29` to ID `1`.  (there is no ID 1 currently) Also update the row in the DynamoDB so the encrypted claims and other fields reflect the correct user id.
   - [x] In DynamoDB, update encrypted claims so `x-hasura-user-db-id` = 1
   - [x] In DynamoDB, update `database_id` = 1
   - [x] In production DB, update `user_id` = 1
- [x] in staging, create an identical “Data and Tech Admin” user and re-assign their ID to `1`. (there is no ID 1 currently)
- [x] in the seed data, rename the JD Maccombs user/email to “Data and Tech Admin”. they are already ID 1
- [x]  update the 1pw item for **Moped Local Editor User Login** to point to the Data and Tech Admin credentials in staging.
- [x]  add the [staging user](https://moped.austinmobility.io/moped/staff/edit/34) to our seed data with the same user ID - 34

in additional to unifying all of these logins, this also has the benefit of making sure that [the fallback user ID](https://github.com/cityofaustin/atd-moped/blob/72be9c69ff096176c328d1ab1d9e49419523d82e/moped-database/metadata/tables.yaml#L531) we use for Hasura events (1) is always available in the DB.

**Comment by mddilley** [comment]
Adding some notes to track what I've done:
- Updated the local seed data with the Data and Tech Admin user (db id 1)
- JD was db id 1 in staging so I updated that email, first & last name, and password to the Data and Tech admin credentials
- Updated the **Moped Local Editor User Login** and tested. No foreign key error happens locally with the new seed data.

**Comment by mddilley** [comment]
I made the updates to the **Data and Tech Admin** user described above this morning. I logged in as this user and checked the JWT and local storage, and I'm seeing id `1` for the database id for this user in both. Closing!
