### ISSUE TITLE
OCE Updates from 12/11 meeting

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15035]
- [x] Emails should copy the OCE Resource email and Michael K directly. 
- [x] User doesn't need to see the expired mixes on the notification popup - remove it
- [x] Email should include either a list of the mixes or a link to a table of their mixes 
    - Likely will need to create a public view to link from the email
    - Might be possible in task email for grids/lists
- [x] When creating a new mix record, only show the related plant field when the mix type is hotmix.

We will meet again with the stakeholders on 1/8/24

**Comment by susannegov** [comment]
# Add Notification Form - Remove Expired Mixes
https://builder.knack.com/atd/oce/pages/scene_23
- Filter to 'Status is ACTIVE'
- Remove `Status` field in table

**Comment by susannegov** [comment]
@TracyLinder I was able to get the emails to list the approved mixes. However, it is currently set to where the OCE staff has to input which mixes to include in the email notification.

**Comment by susannegov** [comment]
# 1/08
- [x] Added test notification and paused official notifications
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/ed23b6a9-9449-4d0f-bedf-66732dd422af)

**Comment by TracyLinder** [comment]
Hi @susannegov feel free to close this out when you feel you've completed all tasks. I think we covered everything today.
