### ISSUE TITLE
[RPP Back Office] Usability testing with residents

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1503]
[Testing Notes](https://docs.google.com/document/d/11bbt0MmH5lkKo1ZrlcZu_53hAl18uGRjUg_ldt5JJKA/edit)
[Qualitative Metrics](https://docs.google.com/spreadsheets/d/1OabfI1HysST848RBxLunph2-ohefQvqXNubAuvAbyGA/edit#gid=0)

**Comment by moorerst** [comment]
Discussed with RPP Staff in Sprint Review meeting on 3/5/20. RPP Staff will think of possible ATD staff that are in RPP zones that we could ask to do end user testing.

**Comment by dianamartin** [comment]
@moorerst I just messaged Ryan to ask him 
> do we know any ATD Staff that would be good testers for the RPP application? I remember we had folks that lived/live in RPP areas. Maybe Cole, Tien-Tien..I remember you mentioning them.

Waiting to hear back now.

**Comment by moorerst** [comment]
RPP staff sent email to some ATD employees asking for participation in end user training. Received 3 responses so far.

**Comment by moorerst** [comment]
Met with 5 usability testers during the RPP Sprint Review meeting
Reviewed Usability Test Plan

**Comment by moorerst** [comment]
@dianamartin can you review the testing script document when you have a chancehttps://docs.google.com/document/d/1guL_IxbfYD6lSAFX67M5cYIM9lIouMeMpOOH6asgZ3U/edit

**Comment by moorerst** [comment]
Testing with 5 participates scheduled during the week of April 6th.
Testing will include several per test questions and 5 task to complete. Testing will be observed and scoredhttps://docs.google.com/document/d/1guL_IxbfYD6lSAFX67M5cYIM9lIouMeMpOOH6asgZ3U/edit.

**Comment by dianamartin** [comment]
Completed Usability testing 4/13!
