### ISSUE TITLE
Develop Intial Dashboard Containing Filters and Dynamic Charts/Graphs

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#15045]
A goal of this project will be to create a dashboard allowing the end user to filter data on the fly to update visualizations of the data by council district and SIF Area. This will allow the data to viewed dynamically through maps, graphs, and other visuals

**Comment by DanielStover** [comment]
Dashboard link: https://www.arcgis.com/apps/dashboards/56e843cb87a3415f939dd0154745f5a7

**Comment by andrewshensky** [comment]
Other Sample Dashboard Link: https://austin.maps.arcgis.com/apps/dashboards/75519e1a71004265ac468c833859f9b4

**Comment by andrewshensky** [comment]
Dashboard below has been provided to requestors. Feature enhancements and updates will be tracked in separate issues
https://austin.maps.arcgis.com/apps/dashboards/75519e1a71004265ac468c833859f9b4
