### ISSUE TITLE
User acceptance testing and feedback with RPP staff

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1504]
- Give Steve, Ryan, and anyone else an account 

Questions:
- Reports 
- General functionality

**Comment by moorerst** [comment]
Feedback for Steve
On the back end user side:
- [ ] Under application details there is not permit ID/serial #’s listed
- [ ]	Can we do a range of permit #’s under permit tab/permit ID, & also show zone & color   district
- [ ]	Day passes not listing any kind of number range?
- [ ] 	Noticed there is a renewal period listed for the permits but not a renewal year? Not sure if 
necessary?
-	

- [ ] Color coded/listed by district but did not see a place with the zone#’s 
- [ ]	Comments section. Any way to edit or delete? 

Applicant side: 
- [ ] Can they edit the info, # of permits etc. right before and/or once they submitted the application. before giving payment? 
- [ ] Can customers move forward without attaching documents? 
- [ ]	If residents visit the office, will they use an iPad? Info will be added same as online process? 
- [ ] 	Hours listed on payment screen show till 3p but I’ve been taking up to 330p if we wanted 
to change?

**Comment by moorerst** [comment]
Feedback from Finance Team (VP)

- [ ] Under Advanced Search, can you add the option: “Transaction Date From” and “Transaction Date To”?
I would like to input the dates: from and to, then I want to download the list of transactions for a specific period of time.
- [ ] Can I have a button “Download”?
- [ ] The report section doesn’t help me at all because I need a complete list of all these fields shown here
![image](https://user-images.githubusercontent.com/56606465/77345700-fff79800-6d02-11ea-8f82-1a43720b4cb6.png)

**Comment by dianamartin** [comment]
I added the fields


![image](https://user-images.githubusercontent.com/21112975/77355602-b2832700-6d12-11ea-9cd4-ba0d9927bbb5.png)

**Comment by moorerst** [comment]
Fowarded email to RPP core team
Hi all, we have some received some feedback from RPP user testing. 
Below is a link that details the feedback we received and the actions taken to address the recommendations. Please review the details.  
The modifications have been made in the prototype and need to be tested and approved by Friday 3/27.

https://github.com/cityofaustin/atd-data-tech/issues/1504#issuecomment-602749833
https://atd.knack.com/parking#home/

Let me know if you have any questions/concerns.

**Comment by moorerst** [comment]
Approval from RPP staff 
Hope everyone is staying safe out there. Just wanted to let you all know I’ve been looking over the site on my end, & the changes that were implemented after the feedback and everything overall looks great. Thanks so much for everything, it’s much appreciated!

**Comment by moorerst** [comment]
Approval from Finance staff
I just did the test on Advanced Search and download the Excel report which has all the information that I need to prepare my monthly entries.
