### ISSUE TITLE
[Bug] Searching with double quotes  (`"`) breaks the UI

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#15050]
When using normal advanced search on text fields, we receive a GraphQL error when a search is made for `"` (double quote). Other characters may break the query in the same way, but I couldn't replicate with any other special characters.

**The search**
<img width="1177" alt="Screenshot 2023-12-20 at 2 36 25 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/37249039/7ababa6d-95eb-47c9-a7d8-6b562949e213">

**The 🐛**
<img width="1177" alt="Screenshot 2023-12-20 at 2 35 44 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/37249039/286ed170-d3e6-41ff-9369-89da838cf064">

**Comment by tillyw** [comment]
closed via https://github.com/cityofaustin/atd-moped/pull/1289
