### ISSUE TITLE
Technical review of application

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#1506]
Tentatively scheduled 3/2 @ 2:30 pm.

**Comment by dianamartin** [comment]
## Technical Review Notes

### WORKFLOW SCENARIOS
decals and vehicles
what if you add decal at review page. 
No validation on vehicle numbers. 
No add vehicle button either.

### CHECK PAGE RULES
- Require Documents after submission. Continue button still shows. 
- Vehicle banner still shows along with "This application has already been submitted" 

### BUG/CODE ISSUE
Home button - remove from JS
removed lines 159-160

### BACKLOG ISSUE
Edit Button for bread crumb trail
