### ISSUE TITLE
[Operations] Conduct Data Fellow Interview

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15071]
Conduct Design candidate interviews between Monday, January 8 - Thursday, January 18.

[Data Interview folder 2024](https://drive.google.com/drive/folders/1445BNn2QrTraf-jxREYzH2BhFgH3omZ0?usp=drive_link)

- [x] Send emails to set up interview
- [x] Schedule candidate interviews
- [x] Conduct interviews
- [x] Fill out Interview evaluation 
- [x] Submit ranking of interview candidates to CIF by Friday, January 19

**Comment by patrickm02L** [comment]
@Charlie-Henry I've copied the design templates from last year's interviews into your interview folder for this year's candidates for reference. Please feel free to alter as need be. 

In general, you can search the drive CIF Fellows 2024 to get all the materials for this year - CIF Fellows 2023 for last year.

**Comment by Charlie-Henry** [comment]
Meeting with Susanne and Amenity tomorrow to refine interview questions/goals. Emails were sent out to candidates just now.

**Comment by Charlie-Henry** [comment]
Completed everything ✅ thank you @patrickm02L for being so organized!

**Comment by patrickm02L** [comment]
YW!
