### ISSUE TITLE
[Bug] Deleting an advanced search filter causes project list to update

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15074]
When using the advanced search filters on the project list, deleting a filter causes the project search to update immediately. The desired behavior is that any changes to the project filters are only applied after the user clicks the **Search** button.

Steps to reproduce:
1. On the project list, use the advanced search filters to search for a project by **Name**
2. Open the advanced search filters again, and delete the **Name** filter you created.

**Comment by mddilley** [comment]
@johnclary I'll verify for sure on Monday, but it looks like the work for https://github.com/cityofaustin/atd-data-tech/issues/15049 fixes this one too. Freebies!

**Comment by johnclary** [comment]
Nice!

**Comment by mddilley** [comment]
thanks for bringing this one back into my focus, @johnclary 🙏 - i just added it to the open PR description ✅
