### ISSUE TITLE
[Data] Update VZA shifts 1/2/24-3/24/24

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15073]
## Description
Add the next 12-weeks of assignments by copying the previous 12-weeks of assignments.

## Notes
- documentation: https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzNSSXajDFpzOv2IhIv/vision-zero-in-action/batch-copy-process-for-vza-assignments

**Comment by ChrispinP** [comment]
I updated the process again for doing these VZA imports after some difficulties during last batch. I created additional fields in the object to capture dates and times separately to make it easier to add 84 days to them and concatenate them moving forward.

Assignments imported, complete

**Comment by patrickm02L** [comment]
Thanks, looks good!
