### ISSUE TITLE
[Data] Backfill EMS data to resolve gap between 9/9/23 and 10/25/23

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15077]
## Description

@xavierapostol reached out on slack to let us know that EMS data was missing

> Hello y'all. I need some assistance with the EMS table. It seems to be missing data ( specifically around the 9th of September, 2023 ). The reason for this ask is because there was an autonomous vehicle crash that prompted an investigation and there is no CR3 for it ( none was ever generated ), but there was and AFD and EMS incident. I found the incident on the AFD side in our database, but not on the EMS side.
> 
> Also, I verified with our EMS contact ( Lynn Cohee ) that they did send over that data and double-checked the most recent data set as well.

@mddilley took a look at the ETL and the data and confirmed that there was indeed a gap where the ETL didn't capture data. 

> i took a closer look, and it looks like our [ETL processes records from the past 15 days](https://github.com/cityofaustin/atd-vz-data/blob/01ed35e47e47ec58487074866fc7900962602e6c/atd-etl/afd_ems_import/ems_incident_upload.py#L148). The attachments we receive from EMS have a gap between 9/9/23 and 10/25/23, and 15 days before 10/25/23 is ~10/11/2023. So, I think we need to backfill? Seems like our ETL missed some data.

#### Example
![Screenshot 2023-12-27 at 2 29 25 PM](https://github.com/cityofaustin/atd-data-tech/assets/5566727/f67f2bb0-ac84-4044-9fb4-1546426d621a)

## Deliverable

- [x] Do a backfill to capture the missing data between between 9/9/23 and 10/25/23

**Comment by mddilley** [comment]
The backfill is done, and I made some small code changes in case this comes up again in the past. Putting this in review.

**Comment by patrickm02L** [comment]
Thanks for updating the code, I bumped this task up to a 2 to reflect the work.
