### ISSUE TITLE
Configure DB triggers for `moped_proj_funding` audit fields

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15086]
As part of the audit field overhaul, the task is to add, rename, and configure missing audit fields on the [`moped_proj_funding`](https://db-docs.austinmobility.io/atd-moped-production/tables/moped_proj_funding.html) table.

- rename `date_added` to `created_at`
- rename `added_by` to `created_by_user_id`
- add `updated_at` timestamptz column
- add `updated_by_user_id` column
- configure Hasura to `set` the `created_by_user_id` and `updated_by_user_id` column using permission rules. [here](https://github.com/cityofaustin/atd-moped/blob/2e109cea3b3da6f3572a2fac37c33d38a12fdce4/moped-database/metadata/tables.yaml#L402-L404) is an existing example
- configure a DB trigger which updates the `updated_at` timestamp, and also sets the `updated_at` and `updated_by_user_id` columns on the `moped_project` table
- remove the part of the existing Hasura event trigger that mutates related `moped_project` record.
- update Moped editor code as needed to update column names

### Other considerations

We should try minimize the number of functions we maintain in the DB which update audit fields. 

For reference, we have [this existing trigger](https://github.com/cityofaustin/atd-moped/blob/2e109cea3b3da6f3572a2fac37c33d38a12fdce4/moped-database/migrations/1700515731001_parent_audit_values/up.sql#L6C28-L28) which is used by feature tables to update a related component record and it's parent project, and we also have [this function](https://github.com/cityofaustin/atd-moped/blob/2e109cea3b3da6f3572a2fac37c33d38a12fdce4/moped-database/migrations/1686243614837_create_work_auth_table/up.sql#L88-L93) which updates a record's `updated_at` timestamp.

**Comment by frankhereford** [comment]
I sync'd with @johnclary real quick on slack and he gave me the 👍 to grab this. Thanks!
