### ISSUE TITLE
[BUG] City seal is broken on a few pages in SMD Data Tracker

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15092]
**Describe the bug**
Cathy forwarded me an email from Ramona letting me know that some of the City Seals are broken for invoices and cost estimates. 

**URL & Screenshots**
- [Signs Invoice Example](https://atd.knack.com/signs-markings#reimbursements/signs-reimbursements/invoice-details-signs/656f9bafa960740027fe4b0b/invoice-signs/656f9bafa960740027fe4b0b/)
   <img src="https://github.com/cityofaustin/atd-data-tech/assets/61209591/1aa71d97-bfde-4160-9467-99f4dc96b039" width="500">

- [Markings Invoice Example](https://atd.knack.com/signs-markings#reimbursements/markings-reimbursements/invoice-details-markings/63571978302ee90720e00a1a/invoice-markings/63571978302ee90720e00a1a/)
   <img src="https://github.com/cityofaustin/atd-data-tech/assets/61209591/53696d68-c439-42c4-9948-beefa47751d7" width="500">

- [Cost Estimate Example](https://atd.knack.com/signs-markings#project-cost-estimate/cost-estimate-details/65819f2f3451700028631e80/cost-estimate/65819f2f3451700028631e80/)
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/c5bd5b1d-7bb7-4445-ae39-4d6e6209927a)

**How would you rate the impact of this issue?**
- [x] Minor  — can perform work, but could be easier or faster

**Additional context**

**Comment by ChristinaTremel** [comment]
[Github Media Files](https://github.com/cityofaustin/atd-knack/tree/master/media)

[Gitbook Banners](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/CqNGfEc0WO4ar1y6yBB3/)

**Comment by dianamartin** [comment]
# 1/3/2024
- I think GitHub changed their URLs and it broke the image links
- [x] Corrected the images in the three locations in the SMD Tracker

**Comment by ChristinaTremel** [comment]
Let Cathy and Lauren know that this has been fixed.
