### ISSUE TITLE
Signal Mods & Upgrades Tracking

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#151]
- Used by Signal Engineers
- Track Modifications
- Attach drawings
- Attach a permit
- Able to create a signal work order from it

**Comment by amenity** [comment]
Issue moved to [cityofaustin/atd-knack-data-tracker #161](https://github.com/cityofaustin/atd-knack-data-tracker/issues/161) via [**ZenHub**](https://www.zenhub.com/)
