### ISSUE TITLE
[Bug] Identify why version number 1.40.0 release number did not render with the latest release

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15102]
## Description

During the release party on 01/02/24, we noticed that the code successfully merged but the version number did not. 

In the meeting it was speculated that the release candidate was pulled from master when it still had version 1.39.1, before the version number bump commit was merged, so the commits that update the version numbers in the package.json files never got pulled into the release candidate branch.

Identify why the version number didn't update to 1.40.0, and propose the fix to production back in order.

**Comment by patrickm02L** [comment]
via @frankhereford in slack

#### Findings

:wave: Thank you all for the chance to look at this closely. If anything, I think doing this has taught me a better-practice when doing point releases. Here’s what I’ve found, and I think this will align with y’all’s assertions during the launch party.

If you look at the spreadsheet below, you can see what commits are showing up in what branches for the two `package.json` files. These are the only files in play for us, which I believe Chia pointed out on our call by comparing `production` → `master`. As we’d expect, we have accumulated Xavier’s PDF updates which he does directly into production as well as the merge commits from us merging stuff into `production` during past release parties. It’s helpful to note that GH is reporting that production is 15 commits ahead of master which are those Xavier and merge commits and it’s 0 commits behind, meaning, we don’t have anything hanging out in master that we have failed to get into production.

So, with the understanding that this is really just a thing about version numbers, you can look at that spreadsheet and piece together how we got here. I believe I caused this by pushing directly onto `production` with the patch’s version number instead of pushing onto `master` and then merging that into `production`. Doing so made a commit, `65bcc3a`,  which was more recent than the bump of version number that Mike did during our last release party in commit `705c0e6`. Had I taken the longer route of working that patch release up through `master` into `production`, I would have been forced to come back to `master` afterwords and restore Mike’s `1.40` version, and would have made a commit with that change which would then have been the most recent.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXlTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ceb1b0bc1882678f78c89091268c53d7c302514/image%20%282%29.png" alt="image (2).png" />


I believe Mike called out the importance of merging up through `master` for patch releases during this meeting, and now having looked at this, it’s become clear to me exactly why. Thanks Mike for pointing that out!

#### Solution

In terms of fixing it, I think the right thing to do is to commit directly onto `production` with `1.40.0` as the version number and /after that/ updating the master copy to `1.41.0.` I know this flies in the face of the advice i gave myself above, but master is already at 1`.40.0`, and we don’t have a more recent commit to override the `1.39.1` version in production.

**Comment by frankhereford** [comment]
This got all sorted out - [here's the thread in slack](https://austininnovation.slack.com/archives/CM9MK950S/p1704217899045419). Thanks everyone!
