### ISSUE TITLE
[Bug] Download CR3 (disk) icon does not work for Read Only and Editor permissions

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15103]
## Description

During testing for the 1.40.0 Release (1/2/24), we discovered when Read Only and Editor permissions try to export a .csv of CR3s from the Locations page that in the pop-up there's an infinite spinning wheel of death that doesn't allow for you to complete the action. Downloading CR3s from the Locations page does work for the Admin permission.

Furthermore, when you X-out of the pop-up and try to click on the export (disk) icon again the page goes blank. After refreshing the locations page data returns.

We need to ascertain why this is happening and figure out how to make downloads of the CR3s on the Location page for Read Only and Editor permissions possible.

## Note
Video (:42) walks through of the problem

https://github.com/cityofaustin/atd-data-tech/assets/5566727/bd0095a7-e41c-44e2-b819-ff0b28fb609d

## Error
<img width="878" alt="Screenshot 2024-01-02 at 11 58 28 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/37249039/8f7bee01-2984-4770-8c40-c68745957a5a">

**Comment by patrickm02L** [comment]
@mddilley is there anything we should add?

**Comment by mddilley** [comment]
@patrickm02L I added a screenshot of the error that returns from the request, but this all looks great to me. 🙏
