### ISSUE TITLE
Feature: Creating a pool of 500 reg doc records in advance of regs being created

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15115]
- While Chrispin was working on #14758, it was brought to our attention that there have been some errors while manually entering reg numbers. 
   - Example: leaving a number out, extra number, extra spaces/punctuations
   - These errors needed to be fixed for data accuracy, so Chrispin had to do some data clean up
   - This data accuracy is super important because it's how we're connecting reg docs and regulation line items
- To ensure that this doesn't happen in the future, Chrispin proposed that we create a pool of ~500 reg docs so the Admin team can select the reg number in a drop down instead of manually typing the reg number.

**Comment by ChrispinP** [comment]
New Document Template object that houses the pool of 500 records
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/ea6b71dc-c617-497c-81d9-835c4a9f5e12)


Pages and Views for Manage Reg Backfill updated to the Canvas & Approved Regulation objects
- Admin will be able to enter & edit Canvas Regs directly into the table
- Admin will also be able to view Regs they have entered once they have transitioned to Approved
- Updated Rules accordingly
- Backfill records, once imported, will also appear in these tables.
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/c2267985-2d9a-41a1-93b7-983166d599d8)

**Comment by ChrispinP** [comment]
- [ ] Document Template object fields updated
- [ ] Records imported for years 1971 to 2024
- [ ] Connect Template Records to their Document Records

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/502b4c67-2e6a-4d6a-ad7d-6d74fe751dff)

**Comment by ChristinaTremel** [comment]
Document Templates have been created and connected to Regulation Documents! 🎉
