### ISSUE TITLE
Enhancement: Rebuild backfill form and backfill table to show fields from `regulation_items` object

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15113]
- As Chrispin was working on #14758, we realized that we could improve our process by replacing the regulation backfill form (with fields from the regulation backfill object) with the canvas reg fields/object so the data that the Admin team populates is directly related to the canvas regs.
- These records that the Admin team creates will need to be flagged by an existing field `Admin Entry` (yes/no field)
   - Record rule for when the backfill form is submitted, `Admin Entry` field is `Yes`
- When the Admin team is backfilling, we want to create a draft regulation doc with canvas regs. Once there is an install/uninstall date added, we will want the approved regulation doc and approved regs to be created. 
   - Want to do this so we can use this to do some usability testing on the process that will also take place once engineers are creating regs through Knack.
- Will also need to rebuild the backfill table to point to the flagged records in the canvas object
- Once this has been completed, we can work #12817

**Comment by ChrispinP** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/1031aa77-7cf4-4066-8fdc-4fee5812db19)

**Comment by ChristinaTremel** [comment]
## 3/1/24
- Will need to rebuild this pointing to the approved reg object

**Comment by ChristinaTremel** [comment]
### 3/7/2024
- Rebuilt the backfill form and table using the `approved_regulations` object

**Comment by ChristinaTremel** [comment]
All of the backfill forms and tables have been restructured and now point to the `regulation_item` (previously named `approved_regulations`) object as the source!

**Comment by ChristinaTremel** [comment]
## 3/25 - Testing Backfill Form
- Modified `2021-0052` because the there was an error in the approved date (2202 instead of 2022)
   - Modified this field and confirmed on the back end that it populated the modified by and modified date. 
   - All the fields were populated correctly on the back end and this was associated to a regulation template
- Created test backfill record using `2024-0001-06`. Almost everything populated as expected, but here's a few things I found (cc: @ChrispinP)
   - `Regulation Item` field on backfill front-end table didn't populate even though I selected the template `2024-0001-06`
   - `Connected Reg Doc`, `Document Display`, `Reg Doc Key`, `Reg Doc Item ID` fields are blank on the back end table:
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/2ba2b770-df8c-4ec4-8539-2c90ebfc275c)
   - `Created By` and `Created Timestamp` didn't populate
   - `Reg Doc Submitted Date` didn't populate, but the `Submitted Date` did instead (and is the field showing on the regulation backfill form). Which field should that be?
