### ISSUE TITLE
Bug on LM Web Application Acceptance (SS)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15124]
### When the user attempts to save 'Accepted' on Web Application Acceptance, the system throws an error and cannot move forward in the process. This is a hard stop with no workarounds. RSN 13190725

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/0fdf3e27-72af-4762-a448-4c0a9ddeee0f)

**Comment by TracyLinder** [comment]
Per the customer, Incident INC0354147 has been opened. We'll need to close it.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder There is something not right about the Applicant (people RSN-5803801) record. It has parent record with rsn - 5807221.  And surprisingly that parent people record has another parent which is its child (RSN-5803801). This causing the loop never end.
Luckily I found the same folder/people record on DEV and tested it by updating people record(RSN-5803801). I updated its ParentRSN to NULL. That resolved the issue on DEV.
The same solution should work on PROD as well.

-------------------------------------------------------------
### DEV notes:
 Attempt_LM_00070000 ==> COA_MISC_PKG.f_send_template_email ==> coa_misc_pkg.f_get_email_addresses
  ............................................
 ..............................................
  CURSOR cur_people_email IS
      --  GR    4/13/2012 Updated to verify email address for people records HD# 1090854
      -- GR  6/19/2013 Updated to allow ' in email ID for HD# 1304532
      -- GR 7/1/2013 Updated to allow for . and - in email for HD 1307737
         SELECT DISTINCT regexp_substr(p.emailaddress
                                      ,'[a-zA-Z0-9._%-''-]+@[a-zA-Z0-9._%-]+\.[a-zA-Z]{2,4}') email_id
           FROM people p
          WHERE p.emailaddress IS NOT NULL
            AND (p.statuscode IN (1, 4) OR
                p.statuscode IS NULL)
          START WITH p.peoplersn IN
                     (SELECT fp.peoplersn
                        FROM folderpeople fp
                        JOIN folder f
                          ON (f.folderrsn = fp.folderrsn)
                       WHERE f.folderrsn = 13190725
                         AND fp.peoplecode IN
                             (SELECT vlp.lookupfee
                                FROM validlookup vlp
                               WHERE vlp.lookupstring = f.foldertype
                                 AND vlp.lookupcode = 90248))
         CONNECT BY peoplersn = PRIOR parentrsn;

**Comment by TracyLinder** [comment]
Hi @SubhaShroff good work. We can't remove the parent id from an internet user record because it will make it impossible for the applicant to submit applications; or at least that used to be the case. Instead I removed the parent ID from 5807221 and have asked the user to attempt the process attempt again.

**Comment by SubhaShroff** [comment]
Thanks @TracyLinder. That way also it should work. 
I might be wrong, but, my observation is Internet User is a parent record and other people types like Applicant are Internet User's child records. Very few Internet Users have a parent record on PROD.
![image](https://github.com/cityofaustin/atd-data-tech/assets/51680715/3a005425-680e-401c-9783-637b3893ff29)

**Comment by TracyLinder** [comment]
The user verified she was able to save the attempt after we removed the looping parent/child RSN issue. 
Thank you @SubhaShroff I will close this.
