### ISSUE TITLE
5CANCEL SBODTM Work Orders

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15125]
Please 5CANCEL the following work orders as the scope of the Downtown Enhancement Project has changed:

<img width="81" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN21XQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ccb5a0075519bc1b00bd209ded80d35dfa75db9/image.png" alt="image.png" />

**Comment by ReneVarg25** [comment]
Reached out to CTM to address these.

**Comment by ReneVarg25** [comment]
1/24/2024
CTM (Erin A.) was able to get child WOs deleted that could be deleted, and 5CANCEL'd that were in other statuses. Parent WOS were able cancelled as anything linked to a Parent WO could not be deleted. All should be clear.
