### ISSUE TITLE
[Bug] Fix WSOD in VZE when interacting with data widgets on crash listing page

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#15130]
If you go to the VZE's crash listing page, and empty out a date as if you were going to type a new one in, and it's a WSOD.

https://github.com/cityofaustin/atd-data-tech/assets/3653206/e9e75513-be2a-4687-b4a1-804dc03ad517

In this video, the WSOD happens the moment I hit the backspace key.

**Comment by patrickm02L** [comment]
## 01/03/24 Refinement.

We test on Editor permissions as well and the same things happened.
