### ISSUE TITLE
Merger Storage Standards

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#15159]
Prompted by TPW stat inquiries around where and how data resources are stored: 

1.  Power BI Premium Workspaces 
   - Currently PW does not have a lot of reports on the PBI, would be open to sharing a workspace with TPW. Pending conversations with DTS for feedback.   What is on the PBI?
2.  Open Data Portal 

- [ ] Scheduled to discuss during next TPW Stat Weekly 
- [ ] Discuss with DTS Data Science team during upcoming Sync

**Comment by katelunceford** [comment]
There's another issue ( @katelunceford will find) to transition everyone into one same place
