### ISSUE TITLE
TDS-AMANDA Performance Data Pull (01/10 Sprint) (SS)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15153]
### Run the data pull from #14196 and provide updated data set.

Date range = 10/1/21 to current date
Output: Raw CSV

Start date = process To-Start date

**Processes to include in query:**
-- ATD Engineering Review
-- ATD SIF Review
-- CC ATD Review

**Data Columns:**

- FOLDERTYPE
- FOLDERRSN
- REFERENCEFILE
- FOLDERNAME 
- REVIEWER 
- PROCESSNAME 
- Start Date
- DUEDATE
- End date

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Here is the data as on today. Thanks.
[TDS Amanda Data as on  Jan 1st 2024.xlsx](https://github.com/cityofaustin/atd-data-tech/files/13881017/TDS.Amanda.Data.as.on.Jan.1st.2024.xlsx)

**Comment by TracyLinder** [comment]
This was sent to Matiur last week. I am closing.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  I am uploading the latest data with the updated query. Thank you
[TDS Performance Data - 1-26-2024.xlsx](https://github.com/cityofaustin/atd-data-tech/files/14068645/TDS.Performance.Data.-.1-26-2024.xlsx)
