### ISSUE TITLE
IT Support: Please order a mifi for the following users

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#15158]
TOWNVIEW

## Device & User Information (first name and last initial, no last names)
Jermaine B
Jonathan G
## What's the problem?
Please order two Mifis for these users

**Comment by scottreedy** [comment]
Request Number : REQ0171058
Submitted : 01-05-2024 14:01:14
Requestor : Scott Reedy
2 ATT Mifi's with unlimited data ordered.

**Comment by Matthew-M-TPW** [comment]
Deployed Mi-Fis
