### ISSUE TITLE
[Enhancement] Create a recurring export, for 2024, of CRIS data to be sent to the SFTP endpoint

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15164]
## Description
We realized on 1/8/24 that CR3s have not been downloading since 12/28/23. We'll need to update the export for 2024, and backfill the missing records.

## Note
Frank recommended as future action that we may want to create an alert in Slack if we don't get more than 10 records to download, so that we can catch these kinds of Issues.

## Note 2

@dianamartin suggested that we calendar an invite for the expiration of the query we put back in place, and I'm going to do that.

**Comment by frankhereford** [comment]
I'm co-assigning Chia on this issue since she is having to do a bunch of stuff to restore our CRIS access to even allow this issue to go forward.
