### ISSUE TITLE
OCE Mix Review 1/8/24

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15172]
We reviewed the app with our stakeholders and gathered a list of improvements.

**Comment by TracyLinder** [comment]
# Notes


- Michael still needs to work on the content for the notification email. What we have now is OK, but could be better. 
- There are cement and ash types. `Potential improvement`
- [ ] New task to update mixes from active to expired status. It should update the same calendar day as the expiration date. 



### Plant Updates
- [ ] Build a plant specific page to view plants and manage plant data
- [ ] Field on plant table: Plant Type -- Each plant only produces one type of mix; the same as mix types.  
- [ ] Field on plant table: Plant Certification Date
- [ ] Only Concrete mix plant types should show the certification date field


- [ ] Add a plant notification feature on the producers page. Allow users to create plant notifications for 30 days and same day.

**Comment by TracyLinder** [comment]
We're going to debrief on this internally today 1/9/24

**Comment by TracyLinder** [comment]
### Debrief

**Approved Mix:**
- Choose which add new mix form to use and move forward with just that form


**Producer Details:**
Q: Should users be allowed to modify or add plant or mix data from this page? --- 


**Plant Data Features**
- Create a space for plant management, only allow editing there
- On the producer's details page, show the plant info



**Plan Notification Features:**
-  This is not in scope; would need to be placed in the backlog.

**Comment by susannegov** [comment]
# 2/05
- [ ] Deprecate the PDF columns on the `producer` and the `approved_mixes` tables
- [ ] Add `attachment` table to producer details view
- [ ] We need to ask if they prefer editing approved mix in the `producer` details and that they do not need approved mixes in the Approved Mixes | Inventory page

**Comment by susannegov** [comment]
> @susannegov are you ok if I close this one?

Yes this is good to close out

**Comment by dianamartin** [comment]
# 10/1/2023
Susanne said it was good to close on May 30, 2024
