### ISSUE TITLE
Maximo User Process Discovery Meeting - OCE Right of Way

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15188]
## Objective 
The Data & Technology Services Division is initiating a series of meetings to learn more about Maximo user experiences and processes in TPW. In this meeting we'll be asking questions about how individual teams use Maximo and how it fits into their work processes.

## Goals:  
- Maximo system performance and functionality 
- User experience and interface experiences 
- Current processes within and related to Maximo 
- User feedback and improvement  
- Future roadmap and upgrades 

### User experience and interface experiences 
- Explain your process on how you use Maximo? 

### PROCESS - Planning
- Who plans the work? How do you get work to do? 
- How is work scheduled and issued out 
 
### PROCESS - Implementation
- How is work scheduled and issued out?
- Who is executing the implementation? 
 

### PROCESS - Field Work
- Who is executing the work - implementation? 
- Who is reporting on the work and what are they tracking? 

#### Maximo system performance and functionality 
- How long is it taking to do a Maximo work order in the field? 

### PROCESS - Review & Reporting
- What is your final review, QC process? 
- What reporting do you care about? How are you pulling that information out? 
- What are you reporting? 

### User feedback and improvement  
- What challenges are you having with Maximo? 

### Future roadmap and upgrades 
- What would you like your work order management system to do that you’re not getting right now? What’s missing? 

### Points of Contacts 

------
- [x] Schedule meeting - 1/24/24
- [ ] Meet and take notes
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# 2/5/2024
## Diana's Notes

**Sam W.  - 22 years**

- Project Coordinator, help them with Maximo WOs

**William “Will” E. **

- ROW investigations
- Maximo Work Order, Citizen Requests

## Will uses it on a daily basis

- Citizen Requests (CSR), or just phone calls
- Administrative assistants, create Maximo Work Orders
- His Process
    - He gets assigned a Work order and investigates them
    - Receive notification from admin assistant
    - Notice that one has been assigned to him (daily)
- Investigate the issue
- Choose the work order
    - Enter in Actuals, Work Log
    - Resolved it - communicate by to customers
        - dumpsters in the ROW - hauler companies, fences with citizens
    - Resolve or Close the work in Maximo
    - Circle back to check back and try to close out work orders
- What SR Types are you handling?
    - Obstructions in ROW
    - Curb damage
    - ROW: sometimes pavement failures
- How is entering work orders in?
    - I asked: do you use a laptop and or mobile device?
    - Taking computer with him
    - enter in the field
    - enter at the end of the day the work orders he’s has done
- Rene: tells him about EzMaxMobile

## Schedule out work?

- He schedules out his work
    - He spends 1-2 hours on Maximo
    - Tracks backlog of work orders
- He also does plan review task as well

## ROW Team in Maximo

- Rudy L. on the team
    - He also helps a lot
    - He’s busier, in charge of homeless encampment clean up
        - Some SRs doe come in through Maximo
        - Those are usually other requests
    - He runs city contract, and does set schedule to do maintenance on homeless encampments
        - # number of cleanups tracked on Excel spreadsheet
- Will is the main person that does it

## Quantity of work orders

- varies pretty wildly
    - can get 20 work orders and low as 2 work orders
    - On average 6-7 weekly
    - Completing 6-7 a week
        - Some times it can be hours and months

## Maximo Report

- he does get a Maximo Report - “SBO Backlog for IMG Group”
- but primarily does use his Start Center portlet
- Performance Measure:
    - Track how many they get and how many they have in backlog?

## User feedback

- clear and useful, works well

## What kind of data do you enter?

- Enter data
- Actuals
    - Labor, Tools
    - Work Log - what he’s done, planning to
    - Does not use Specifications
    - Failure Codes
        - ROW obstruction
            - Owner removal or District removal
        - Attachments
            - upload pictures to the attachments
- Assets
    - basketball goals, retaining walls, dumpster - owner actions (usually)

Interested in Maximo Mobile?

- He has a city issued phone and IBM Maximo Mobile is loaded on there
- On COA App Catalog
    - IBM Maximo Mobile
- sent [[EzMaxMobile Resources](https://cityofaustin.sharepoint.com/sites/MaximoResources/EzMaxMobile%20Resources/Forms/Compact.aspx)](https://cityofaustin.sharepoint.com/sites/MaximoResources/EzMaxMobile%20Resources/Forms/Compact.aspx)
- Seems like some other app is on his phone

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/c17a5416-e1c1-4f02-8e2e-feceb5e2a7a8/7bb65fe0-4661-4356-aba3-55ffc6cb6b98/Untitled.png)

Sam does review the work order details

- Final QA: 4COMPQA

Get occasional requests about “ponding” issues

- Street Repair requests - but send to District Maintenance
    - Are you assigning a different work group?
    - Sending work other to email
        - they don’t know the process, they ask the admin team

## Additional Questions

- Non-emergencies in ROW
- They don’t create additional tickets, in the original ticket
- Sidewalk, Curb and gutter
    - District Maintenance - will create a child work order to ROW

Investigation group

- District will be the first to take the lead
- Obstructions in ROW - they send that over to ROW group

They fall under the IMG Management group 

- OCE related falls under “IMG”

Usually by the work group, not by the problem code

**Comment by dianamartin** [comment]
# 2/23/24
We had a work session `Work Session: Synthesizing Maximo Assessments for OCE` to aggregate the information we collected from OCE Pavement Operations and ROW. We still have to interview OCE Bridge group and UER Bridge group. @ChristinaTremel have we schedule this yet?

**Comment by ChristinaTremel** [comment]
Notes were added to the miro board ✅
