### ISSUE TITLE
[Bug] Street/satellite layer toggle doesn't work in Crash location edit map

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#15193]
When using the street/satellite layer toggle, the map stays on the satellite layer. This could have been a regression that happened when we adding the NearMap tiles. It can be replicated in production on a crash like https://visionzero.austin.gov/editor/#/crashes/19270880.

### Recording
https://github.com/cityofaustin/atd-data-tech/assets/37249039/7d563122-4cc3-4c5f-b8d4-139a4c0f0c9e

@patrickm02L I wrote this up real quick, and it could use some polish. Could also be a feature that is used very little like the geocoder because no one has reported it as broken afaik.

**Comment by patrickm02L** [comment]
## 1/17
Potential to remove the street view. Follow up with Xavier to see if at all it's being used or would provide value.

**Comment by patrickm02L** [comment]
## 1/23
Chatted with Xavier 1/19/23, he said that he uses google maps if he needs to get the street view. Confirmed that we could deprecate the street view.
