### ISSUE TITLE
Work Orders for Signal Inspections and Signal Timing

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#152]

**Comment by amenity** [comment]
@johnclary - is this a project that needs scoping? Or a feature in an existing application?

**Comment by johnclary** [comment]
Issue moved to [cityofaustin/atd-knack-data-tracker #124](https://github.com/cityofaustin/atd-knack-data-tracker/issues/124) via [**ZenHub**](https://www.zenhub.com/)
