### ISSUE TITLE
Conducting Training for TPW on Emails & Phishing

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#15207]
Diana M. 
DTS

Since ISO approached us (the department) on 11/28/23 about introducing a Phishing simulation training. Some of the action items from our discussion were to give our TPW employees the tools necessary to know how to alert the appropriate people. We (Apps team) decided that it would be a good opportunity to schedule a training for our department employees. 

- Reference: ISO has said that in a newsletter 10/25/23 "[Reporting Suspicious Email Messages in MS Outlook](https://cityspace.austintexas.gov/News-articles/Reporting-Suspicious-Email-Messages-in-Microsoft-Outlook)"
- Slide deck: [You've Got Mail](https://docs.google.com/presentation/d/1JbBwTUW-lPwC4kGyphjsA-qnf1Yb8EZfcIOZcJS9o44/edit#slide=id.p)
- [Miro board](https://miro.com/app/board/uXjVNJ5adWA=/) - not much on here, just for brainstorming

**Comment by dianamartin** [comment]
# 1/10/24
Originally scheduled training for 1/24/24, moved it to 1/31/24. Peggy wanted to announce something at the upcoming Supervisor's meeting so that will give us some time to market the training.

**Comment by dianamartin** [comment]
# 1/11/2024
- [ ] Need to draft email for meeting invite

**Comment by ChrispinP** [comment]
@dianamartin any other action items for this?

**Comment by dianamartin** [comment]
I think we're good to close this
