### ISSUE TITLE
[Tech debt] Update Moped Editor NPM packages

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15204]
Run `npm update --save` and test the app.

**Comment by frankhereford** [comment]
I finally got the time to sit down and do this testing today with the care I wanted to. There is a new tab in the testing worksheet called 'npm update' from my run through, and there are no show stoppers or really any bugs that I think are fallout from this testing. FWIW, I have been testing locally with the following browser:

```

Arc | 120.0.6099.216 (Official Build) (arm64)
-- | --
Revision | c89e9d30198bc4e9e7711e2b90b9602cdd50e448-refs/branch-heads/6099@{#1720}
OS | macOS Version 14.2.1 (Build 23C71)
JavaScript | V8 12.0.267.14
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Command Line | /Applications/Arc.app/Contents/MacOS/Arc --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=WebGPU
Executable Path | /Applications/Arc.app/Contents/MacOS/Arc
Profile Path | /Users/frank/Library/Application Support/Arc/User Data/Profile 1
Linker | lld
Variations Seed Type | Null
```

This is the Arc browser, but it's just another chromium deal under the hood. 

I'll follow up with a PR with the updates and some more notes right after lunch on this.

**Comment by frankhereford** [comment]
I created new issues for the bugs I found. I figured it's right to spin them off because they were existing, not new from this update, bugs.

https://github.com/cityofaustin/atd-data-tech/issues/15283
https://github.com/cityofaustin/atd-data-tech/issues/15288
