### ISSUE TITLE
IT Support: Confernace Room monitor needs to have the cables cleaned up. 

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#15232]
ST. ELMO

## Device & User Information (first name and last initial, no last names)
Matt M. 

## What's the problem?
V can you do cable management on the rolling cart computer in room 1.07. 
Make the cables look neat

**Comment by Vaishnav1397** [comment]
Have fixed the cables down by moving the power box and made the cables get below the roller.
