### ISSUE TITLE
Update symbology/wording of dark traffic signals

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#15250]
A few ideas on wording/symbology on dark traffic signals in the signal monitor here: https://github.com/cityofaustin/atd-data-and-performance/pull/413 

Would like to make it more clear, could require some refactoring.

**Comment by ChristinaTremel** [comment]
Will check in with AMD about this at our sprint review next week.

**Comment by ChristinaTremel** [comment]
### Notes from Meeting with MMC & Brian
- Brian was asking if we could make the symbology of the dark signal the X symbol (<ImCross />)
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/9e97ccf3-2874-40e7-97b6-dc22305a63c1)
- Will bring this up in Dev backlog refinement

**Comment by tillyw** [comment]
<img width="1915" alt="Screenshot 2024-02-16 at 5 12 44 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/35410637/fe36ac28-f2f6-4b1c-adc6-610273f01d04">
hi! how would this look to y'all?

**Comment by ChristinaTremel** [comment]
This looks great! My only note is that AMD wants the symbology on the map to be black instead of the blue color.
