### ISSUE TITLE
[Enhancement] Update VZDB & CRIS import system to collect new data being provided in CRIS exports, post V27

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#15263]
## Description

With the release of CRIS 27, a small number of additional fields have been added to the export. The exact list of what has been added can be found in the below CRIS release notes. 

This issue is to track the adoption of these fields into the VZDB via the CRIS import script.

## Requirements
- Identify new fields from the CRIS 27
  - [get from the CSVs in S3](https://s3.console.aws.amazon.com/s3/buckets/atd-vision-zero-database?region=us-east-1&bucketType=general&prefix=csv-extracts/&showversions=false)
- Update the VZDB to include these new fields
- Update the CRIS import script to include these new fields (we might get this already, it dynamically updates)

## Note
[27.0.CRIS.Software.Release.Notes.Final.pdf](https://github.com/cityofaustin/atd-data-tech/files/14043984/27.0.CRIS.Software.Release.Notes.Final.pdf)

**Comment by patrickm02L** [comment]
## 1/17 
Check to see if there's an Issue for an ETL that would notify us for changes in Slack. 
@patrickm02L

**Comment by patrickm02L** [comment]
## 1/18
There is an Issue, it's #12069. Looking to get this on the 1/24/24 Sprint cycle.

**Comment by roseeichelmann** [comment]
I compared CSVs from November, before this release, to the most recent CSVs. There were no more column additions to the crashes, units, primarypersons, persons, or charges tables other than the `near_trauma_center id` and `near_trauma_center_distance` additions in the crashes table that was captured in https://github.com/cityofaustin/atd-vz-data/pull/1348. However, there have been 480 additions in the lookup table csv we get from them. Most of these additions (293 of them) are from the new trauma_center_id lookups they have added.

So we will need to create a trauma_center_lkp table for these new lookup values, correct? We are now tracking the `near_trauma_center_id` in the crashes table but they mean nothing unless we create a lookup table for the ids. 

The other additions are in the veh_make_id, veh_mod_id, rpt_road_type_id, inv_da_id, agency_id lkp tables. Do I go ahead and add these additions?

I don't know much about what our process has been in the past for adding new lookup tables or additions to lookup table values, so thats why I'm asking first.

**Comment by roseeichelmann** [comment]
Update:

I just did a diff check on the 2018 lkp extract and the 2023 lkp extracts, the only diffs between them is that the 2023 lkp extract contains two additional lookup tables called `RPT_AUTONOMOUS_LEVEL_ENGAGED` and `AUTONOMOUS_LEVEL_ENGAGED` with the following values.
![image](https://github.com/cityofaustin/atd-data-tech/assets/67130963/9314de27-83f6-4261-800d-1cc07480b95a)
Other than that, the lkp tables and their contents are the same from the two different schemas (2018 & 2023). This is comforting news and makes me feel a lot better that we only track the 2023 schema in our database, its not really making any of our data wrong.

That being said we currently don't have the `autonomous_level_engaged` lookup table in our database nor do we have a column for it in the units table. Is this something we should add as well? We also dont have an `autonomous_unit` lookup table though we do have an `autonomous_unit_id` column in the units table.
