### ISSUE TITLE
Add TCI Reports to PSM (LP) (01/24 Sprint) - (Ready for UAT on PROD) 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15266]
### Adding two folder menu reports to PSM: ROW Investigation (50514), and ROW Open Investigation (50516)
- Must be done after #14997
- These reports should function identically to how they are functioning on DS, EX, RW

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Test , Ready for UAT

**Comment by KyleErich** [comment]
@Nadin-Nader @Lpriya-LIT UAT on TEST approved. Thank you.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Prod , waiting on 14997 to be deployed. Will update once that is done

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT 14997 has been deployed to PROD

**Comment by KyleErich** [comment]
@Nadin-Nader @Lpriya-LIT UAT on PROD approved. Thanks!
