### ISSUE TITLE
Offboarding Homer

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15261]
- [x] Separated Employee SN: REQ0171871
- [x] 1password - ✔️ asked Chia & Frank
- [x] Slack
- [x] Miro - ✔️ asked D & A
- [x] KNACK Apps
- [x] Github
- [x] Google drive - Somebody already did this
- [x] DTS Team & Orientation Slides
- [x] Knowledge base for triage

**Comment by frankhereford** [comment]
1PW and GitHub are taken care of. I have a slack reminder to fully remove the 1PW account after a week. Right now it's a suspended state, so it can't be used, but just on the way off case there's something in there we don't want to loose, i'm going to give us a little time to discover that. Thanks!

**Comment by TracyLinder** [comment]
I will wait for CTM to close the SERF before closing this issue.

**Comment by frankhereford** [comment]
@TracyLinder 👋 Hi Tracy - If it'd be helpful, I'd be happy to move Homer from [our staff listing](https://austinmobility.io/about) to our alumni listing - pls let me know if you'd like that. Thanks!

**Comment by TracyLinder** [comment]
Hi @frankhereford that's kind to offer. I created an issue for this, #15262. 
I'll assign it to you. Thank you.

**Comment by TracyLinder** [comment]
The service now issue is resolved. I'm closing this.
