### ISSUE TITLE
TPW 3-1-1 Backlog visualization

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#15273]
Update our existing 3-1-1 [Power BI dashboard](https://app.powerbigov.us/links/Mg-BtdxjEb?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare).

- Show the backlog of open SRs over time (monthly increments). 
- Show the count of SRs opened grouped by month and fiscal year

**Comment by maccallump** [comment]
@Charlie-Henry there is an anomaly with October 1 data. 
![image](https://github.com/cityofaustin/atd-data-tech/assets/53838164/9c752824-2e38-410b-a067-444ac5491ead)

**Comment by Charlie-Henry** [comment]
@maccallump can you provide more details on the anomaly? Only 73% completed on time but that's what the data says

**Comment by dianamartin** [comment]
# 1/25/24
Peggy and I were talking and checking out the dashboard. It looks like the graph looks better now because you changed the y-axis to 50 and 100 rather than 80 and 100. It now doesn't look as dramatic.

**Comment by Charlie-Henry** [comment]
This was submitted with the report from OPM to ACM Goode 👍
