### ISSUE TITLE
New GISMAINT feature class needs FME process to push to an AGOL Feature Service.

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#15278]
- [ ] Create a feature service for the new special_event_road_cloasures feature class.
- [ ] Set up an FME script task to regularly update new feature service from GISMAINT feature class.

**Comment by andrewshensky** [comment]
This has been completed. Data is being pushed daily from Maint to AGOL

https://austin.maps.arcgis.com/home/item.html?id=8c3cbe42c0e040478729803239cd2c7f
