### ISSUE TITLE
SBOIMG FLEX FIELD 2 Portlet Update

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#15272]
IMG Group is requesting and update to their portlet "Pavement Work Initiated by District". Notes from meeting are below.

Cutoff date for responding to WOs?
- Last year was 650, many were not their work but were sent anyways
- Most were not needing to be sent, had a meeting to limit ones being sent
- Many are now 5CLOSED since time passed
- Do they want to keep 19s? No, there's not point in keeping them if they're that old
- Does not delete, but remove them from bucket
- Bucket is combination of everything, not based on fiscal year
- Did they want to keep full calendar 2023? Yes, maybe a little bit older
	- Will remove 2019-2022 from the bucket, will cut bucket by half
	- Will leave 2023, and notify when done
- What does this do? Does it make it easier to update?
	- Since they are being removed, they will not been in bucket, but can still be accessed

**Comment by ReneVarg25** [comment]
Changed Flex Field 2 section to Acknowledge on WOs older than 2023.

**Comment by adry-martinez** [comment]
**Feb. 12, 2024**

Request for 2022 and older to be cleared from this bucket as it shows they are still displayed without acknolwedgement.

**Comment by ReneVarg25** [comment]
### 2/13/2024
Cleared remaining WOs from bucket.

**Comment by adry-martinez** [comment]
### Feb. 14, 2024
@ReneVarg25 please clear these work orders from the portlet. 

[SBO IMG Pavement Flex FIeld 2.xlsx](https://github.com/cityofaustin/atd-data-tech/files/14284637/SBO.IMG.Pavement.Flex.FIeld.2.xlsx)

**Comment by ReneVarg25** [comment]
All WOs have been acknowledged.
