### ISSUE TITLE
[Bug] Unable to delete project website

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#15283]
As shown in the below screencast, it is not possible to delete/clear a project's website after creating it. This appears to be an issue with the variable type in the graphql mutation.

https://github.com/cityofaustin/atd-data-tech/assets/3653206/031ba8f7-74bd-47d3-8989-586ed4420022

**Comment by johnclary** [comment]
thanks @frankhereford!

**Comment by frankhereford** [comment]
I'm downgrading this to a 1; it was a one-byte change.
