### ISSUE TITLE
First Prototype for Knack Directory

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#15291]
The First Prototype for the Knack Directory will utilize the default Knack Menus and Redirects

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/ee7c926c-cc5d-4aad-a1d5-fab81b81610e)

**Comment by dianamartin** [comment]
# 12/9/24
We are using the Knack Directory and sharing it with TPW employees.
