### ISSUE TITLE
Requirements Gathering

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#153]
[Requirements spreadsheet](https://docs.google.com/spreadsheets/d/1r2l_KFgjygCCp1E4oaBa5lyK2QzkVcP5qCu2u85UwcY/edit#gid=179231394)

**Comment by amenity** [comment]
@johnclary @dianamartin - where did the requirement "type" come from? It seems like we need one for "asset tracking"... 
 - Assign inventory item to warehouse location (shelf, bay, etc)
 - Manage multiple warehouse locations 
 - Scan barcode 
 - Track items by serial numbers
 - Tracking where an item was installed

Can I add a type? Do you have a better way of bucketing these? 

I think having these grouped will be helpful for taking notes and asking questions during the demos. 💁

**Comment by johnclary** [comment]
Yep, I think we just made up the types as way to group similar tasks. Add/change as you want.
