### ISSUE TITLE
Update DTS Portal and atd-data-tech Github label to reflect renamed "Sidewalks and Urban Trails Division"

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#15341]
Sidewalk and Special Projects Division was renamed Sidewalks and Urban Trails Division. 

### Prep
- [x] @amenity schedule launch
- [x] @amenity create PR to update https://github.com/cityofaustin/atd-service-bot/blob/production/config/config.py#L123 to 
`"Sidewalks & Special Projects": "Workgroup: SSPD"` to `"Sidewalks & Urban Trails": "Workgroup: SUTD"` and assign for review

### Launch
**Apps**
- [x] Add a banner on [DTS Service Request](https://atd.knack.com/dts#new-service-request/) page with an outage message
- [x] Hide form by moving it to the staging page
- [x] Move Under Constriction rich text view from staging to SR
- [x] Update "Sidewalks & Special Projects" to "Sidewalks & Urban Trails" as an option for the "Workgroup" field
- [x] Move form back to SR page
- [x] Move rich text view back to staging

**Dev**
- [x] Pause service bot DAGs in Airflow v2 and give a heads up to the service desk primary (so they don't expect service requests to be coming in) and devs (so no one turns the DAGs back on)
- [x] Merge PR 
- [x] Re-run issues to Socrata DAG 

**Product**
- [x] Inform Service Desk primary that the SR form will be temporarily offline. 
- [x] Update [Workgroup: SSPD Github label](https://github.com/cityofaustin/atd-data-tech/labels?q=SSPD) to "Workgroup: SUTD"

**Next Day**
- [x] Check [Socrata dataset](https://data.austintexas.gov/Transportation-and-Mobility/ATD-Data-Tech-Services-Issues/rzwg-fyv8/explore/query/SELECT%0A%20%20%60id%60%2C%0A%20%20%60number%60%2C%0A%20%20%60state%60%2C%0A%20%20%60pipeline%60%2C%0A%20%20%60title%60%2C%0A%20%20%60workgroups%60%2C%0A%20%20%60body%60%2C%0A%20%20%60labels%60%2C%0A%20%20%60estimate%60%2C%0A%20%20%60milestone%60%2C%0A%20%20%60created_at%60%2C%0A%20%20%60closed_at%60%2C%0A%20%20%60updated_at%60%2C%0A%20%20%60url%60%2C%0A%20%20%60is_epic%60%2C%0A%20%20%60position%60/page/filter) to make sure labels are updated there

---
**_Original issue_**
I noticed that this label has the old name SSPD (Sidewalk and Special Projects Division): 

![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/a02d6dc5-52de-48c0-9f94-d1079037a4e5)

The new name of this group is Sidewalks and Urban Trails Division. 

Beyond the label, there are likely implications for SR bot categories and Knack workflows  that I'm not aware of. Creating an issue to start the update process.

**Comment by amenity** [comment]
@KaroEngstrom - would you be up for handling the Apps tasks on this one?

**Comment by KaroEngstrom** [comment]
@amenity Yes, I can see we're thinking next sprint so just need to schedule

**Comment by amenity** [comment]
Scheduled for 3pm on Friday, 2/23

**Comment by KaroEngstrom** [comment]
I would have added the remove step but I don't know when it will need to happen. After dev work? We can work it all out 2/23 🙏

**Comment by KaroEngstrom** [comment]
Do we have the message ready for however long the form will need to be down? If not, will we be asking folks to email Transportation Data directly?

**Comment by amenity** [comment]
"Service requests are offline for an upgrade. Please try back in 30 minutes." will work.

**Comment by dianamartin** [comment]
# 2/22/2024
- Karo pinged me on how to do this since the "New SR" page doesn't have page rules. I suggested creating a new log-in page called "STAGING AREA for DTS SR updates". 
- Create the banner for maintenance in effect 
- Move the New SR form to that page
- She's going to test another form to ensure the form views remain the same before she does this for real

**Comment by KaroEngstrom** [comment]
- tested in ROW TEST; form view retains its view number and rules when moved back and forth
- updated the steps in the original description

**Comment by amenity** [comment]
We actually redid this during our live session because we wanted to capture SUTD's (recently reported) preference for "Sidewalk", no "s", in their name. Here's the [second PR](https://github.com/cityofaustin/atd-service-bot/pull/62). 

Thanks, @KaroEngstrom @Charlie-Henry -- and @chiaberry for the last-minute PR review. ✨
