### ISSUE TITLE
Issues with Jahvien F.'s Account - Ryan H.

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#15343]
Ryan H. reached out to me to request I look into an issue with Jahvien's account. It could not be found within Maximo's Labor reporting and could not be added to any WO.

**Comment by ReneVarg25** [comment]
User's account was not created within Labor. Created user's account in labor and user was able to be found by Ryan.

**Comment by adry-martinez** [comment]
@ReneVarg25 have the new accounts been added to the mailing list?
