### ISSUE TITLE
[TCP Upgrade] Customer Page Messages Functionality 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#15357]
From earlier huddle notes for backlog: 
## Issue 2: Messages Customer Pages and Functionality 
◀️ 🧱 Return to this when Reviewer side is set up
 - Send Message option from Manage Project (specific case details) page 
 - View Messages from Manage Project page - automatically connects to that page's case
 - View Messages from Messages hub page - how to connect to a specific case since we do not want allow unassociated messages? 
      -  Messages hub - can only reply to existing message threads 
      - To launch a new message thread, go to Manage Case initiate a case-associated thread
      - Messages associated on the Case level and Send Message button is on the Manage Case page
      - View Customer Actions from Messages hub page - how do messages play together with the new Customer Action object? 
           - Message can create an action but not necessarily  
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/f61eb60c-ca04-45b6-a18f-a4fbc8358ece)

 **TASKS**
 - When creating an email, we need a record rule to create a message to replicate the content here in the portal 
      - existing: application confirmation email 
      - new items: all communications out of the portal

**Comment by ChrispinP** [comment]
#16634 & #16637 accomplish notes and tasks above

closing as no action
