### ISSUE TITLE
[Enhancement] Refine project list layout

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15353]
Refine the project list view layout to provide a number of usability improvements:

- [ ] - Maximize screen real estate
- [ ] - Make column headers visible when scrolling
- [ ] #16144
- [ ] - Searchable column visibility picker
- [ ] - Consistent row height

This work includes upgrading the list from [Material Table](https://github.com/material-table-core/core) to the [MUI X Data Grid](https://mui.com/x/react-data-grid/).

<img width="1512" alt="Screenshot 2024-01-22 at 3 03 07 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/98ee9b92-d9a6-4e7c-a4cc-1f2c21e5b6fa">

**Comment by chiaberry** [comment]
All of the improvements were addressed, except pinning columns to the left, i opened a new issue for that
