### ISSUE TITLE
TCP Upgrade Builder Huddles | Jan 24th - Feb 6th

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#15352]
## 🗓️ Schedule for this sprint 

| Date      | Session | Work |
| ----------- | ----------- | ----------- |
| Thu 1/25  1-3    | Builder Session       | Application Reconfiguration https://github.com/cityofaustin/atd-data-tech/issues/15417 |
| Fri 1/26 10-12; 2-3   | Builder Session        | Application Reconfiguration https://github.com/cityofaustin/atd-data-tech/issues/15417 |
| Mon 1/28 10-12 | Builder Session | Days Under Review/Total Days Issue + Staff Side Updates Mapping #15445  |
| Tue 1/29 11:30-12 | Project Standup | 
| Thu 2/1 2-4 | Builder Session | Solving Total Days Issue + CSWZ Submissions table #15513  ✅  |
| Fri 2/2 2-3 | Weekly Huddle | Finalize Total Days Issue | 
| Mon 2/5 10-11:30 | Builder Session | TCP Submissions Table #15625  ✅  +Submission Details page planned |
| Mon 2/5 11:30 | Project Standup | Update on Total Days; Staffside Updates  |

**Comment by KaroEngstrom** [comment]
Closed this as no more standups or collabs for this sprint.
