### ISSUE TITLE
[Enhancement] Payment Admin Override Reason

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15382]
companion to #15381

Add two new fields that displays when
- Payment Override
- Payment Override Reason

**Comment by patrickm02L** [comment]
## 3/19 Sync
Payment overides should only be done for the payments that are processed through the city, not when payments are coming through CityBase.

Manual Override
- Make sure to add a timestamp and who changed
- Add a column in the Transactions page that says "Payment Received" connected `banner_reservation`

**Comment by dianamartin** [comment]
# 3/22/2024
## Build Notes
@susannegov @patrickm02L 
### Object Table - `banners_reservations_lpb`
- [ ] Add field on table `Override By` - Connection to Account
- [ ] Add field on table `Override Date` - Date/Time
On Edit LPB Application form - [scene_1273](https://builder.knack.com/atd/street-banners/pages/scene_1273)
- [ ] Update record rule # 2 
  -  Add on Values section
  - [ ] Override By - logged in account
  - [ ] Override Date - Current date
- was going to ask you to add a record rule to update the `transaction` table, but it looks like the rule is already there
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/f1a03b75-ab9a-40f2-93ab-fa4465d4065c)
- [ ] Make sure that the table 'LPB Application Dashboard` - [scene_1270](https://builder.knack.com/atd/street-banners/pages/scene_1270) that the "Payment Received" column's record rules are updated to be the same as the rules above. 

### Object Table - `banners_reservations_ots`
- [ ] Add field on table `Override By` - Connection to Account
- [ ] Add field on table `Override Date` - Date/Time
On Edit OTS Application form - [scene_1265](https://builder.knack.com/atd/street-banners/pages/scene_1265)
- [ ] Update record rule # 2 
  -  Add on Values section
  - [ ] Override By - logged in account
  - [ ] Override Date - Current date
- was going to ask you to add a record rule to update the `transaction` table, but it looks like the rule is already there
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/f1a03b75-ab9a-40f2-93ab-fa4465d4065c)
- [ ] Make sure that the table 'LPB Application Dashboard` - [scene_1262](https://builder.knack.com/atd/street-banners/pages/scene_1262) that the "Payment Received" column's record rules are updated to be the same as the rules above.

**Comment by susannegov** [comment]
# Notes
- Did the changes - see comment above
- The `LPB application dashboard` did not have record rules for payment received
   - [view_3217](https://builder.knack.com/atd/street-banners/pages/scene_1270/views/view_3217/table/columns/13)
- Updated the `OTS application dashboard` record rules

**Comment by patrickm02L** [comment]
@susannegov I went to a record where the `Payment Received?` was `Yes` to try to test the new functionality, but I'm not seeing the new fields under payment received: `Overidden Date`, `Overidden By` in the Administrative Information section - I believe because this is a new enhancement. 

Can you point me to a record that's been manually changed to 'Yes' that would show those fields in the Administrative Information section?

<img width="470" alt="Screenshot 2024-03-19 at 11 54 39 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/5566727/4daed79d-4bc5-4981-8929-d1ad9d438132">

**Comment by susannegov** [comment]
@patrickm02L Thank ou for checking. It was on the OTS APp Details page but not on the LPB App Details page. It should show LPB App Details page now.

See here: https://atd.knack.com/street-banners#lpb-application-dashboard/lpb-app-details/65bab462f138690027c86416/

**Comment by patrickm02L** [comment]
@susannegov thanks, looks good!

**Comment by susannegov** [comment]
Closing issue!
