### ISSUE TITLE
[Enhancement] Update Street Banner .gov site

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15390]
broken out of #14330

### Request 7: Street Banner.gov site (PIO request)

- Change the language in this passage to “lamppost banners are installed and removed on Tuesdays.”
- Change the language in this passage to “over-the-street banners installed and removed on Mondays.”
- Get rid of the option to select any date they want.

**Comment by patrickm02L** [comment]
Review Designs from the original update mock ups
[miroboard](https://miro.com/app/board/o9J_lmlGol0=/)

<img width="1079" alt="Screen Shot 2024-01-31 at 10 25 55 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/5566727/5b769c69-f02a-4fd2-8f29-3396335f1dae">

**Comment by patrickm02L** [comment]
## 2/27/24
- Matilda is going to review the Street Banner Program Policies PDF, which we'll update and make sure that PIO has it when we update the flow.

**Comment by patrickm02L** [comment]
## 3/4/24
Sent PIO request to update the Banners COA web page flow.

**Comment by patrickm02L** [comment]
## 3/4/24
Matilda sent the content that needs to be updated on the Street Banner Program Policy PDF. To edit we'll need Adobe Acrobat Pro.

**Comment by dianamartin** [comment]
# 3/4/24
- [x] Downloaded the "COA_STREET_BANNER_Policies_11-2022" 
- [x] Updated the contact information and added a new section about West Lake Hills banner process
- [x] Emailed stakeholders
>Hi everyone, 
I’ve updated the Banner Policies document. I just wanted to send it over to make sure it looks good before we work with PIO to put it on the website. 

>FYI, the link to the West Lake Hills was weird. I fixed it. 
>- Originally, you  had: https://www.mgoconnect.org/cp/portal
>- Updated, https://www.mgoconnect.org/cp?JID=253 (but really this is the correct link, 253 sets it to “City of West Lake Hills”)
>o	I also found their Banner Application - http://westlakehills.org/documentcenter/view/1469
>o	As a person who has never seen this, I’m not exactly sure of their process. I see that they reference City of Austin’s process on their application. 
>o	They probably have the wrong “Vendor List” now that we’ve updated ours recently.

>Did we want to update our Banner Policies doc to include their Street Banner Application as well?

**Comment by dianamartin** [comment]
# 3/19/2024
Updated `COA Street Banner Policies 3-2024` document - [COA_STREET_BANNER_Policies_03-2024.pdf](https://github.com/cityofaustin/atd-data-tech/files/14653958/COA_STREET_BANNER_Policies_03-2024.pdf)
@patrickm02L this is for PIO to upload

**Comment by patrickm02L** [comment]
## 3/28/24 
We met with Chandra and Matilda to go over the COA web page updates. 

Main takeaways:
- Slimmed down Application Process section
- Accordions will help with the step-by-step process
- Consolidate Determine Street Banners Type into one section
- Consolidate Technical Review, Design Requirements, and Policies into one section
- Links to PDFs will still be available on .gov site, work to make them non-time specific

Follow up:
- @dianamartin to make updates to the mock-ups in miro to Banners team for review
- Review banner policy document

**Comment by dianamartin** [comment]
# 3/28/2024
Emailed Chandra and Matilda, cc @patrickm02L 
>Hi Chandra/Matilda, 

>I put the updated   COA Street Banner Polices document in our DTS SharePoint site so we can collaborate on the document. 
>- We talked about cleaning up this document to only keeping the relevant policy type information in there and then publishing the other information like drop off and pick up in a different area. 

>This is the mockup we talked about this morning. I mocked up the “Determine what Street Banner Type” accordion that we thought about. 

>Let me know if this looks like the vision, we all agreed on. 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/ac04df2c-23a3-4a5c-a331-e1a06c81ff7e)

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/f385f488-6847-464e-861d-19b8bf63054b)

Chandra replied on 3/29
>Hi Diana, 
The mockup looks great, exactly how we discussed and envisioned it. We will review the street banners policies document and continue to make updates.

**Comment by patrickm02L** [comment]
# 4/1/24 
Meeting with Dana H, Chandra P, Diana M, and Patrick M to go over the updates for the Banners web page. 
- Gave miro access to Dana to copy content from mock-ups
- Shared images from the mock-ups in the Teams meeting chat
- Showed updated program policies doc, which Banners team will send to Dana

Dana is planning to make updates this week. Further coorespondence will happen in the `Banners .gov updates` Teams meeting chat

**Comment by patrickm02L** [comment]
## 4/18/24
Jack F. completed the final text bolding and updating the policy PDF.
