### ISSUE TITLE
FME to push data from Long Line GISMAINT to Socrata / EDP

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15401]
- FME to push data from Long Line GISMAINT -> Socrata
   - Keep as internal, EDP dataset until QC is complete

**Comment by ChristinaTremel** [comment]
### SMD GIS Check-In 2/20 Notes
- Kati and Jordan are going to review the schema of the long line dataset and we will follow up on 2/27

**Comment by susannegov** [comment]
# SMD GIS QA Meeting
- Tables added to Socrata:
   - Flagged as Private to: Christina, Susanne, Jordan, Kati
Long Line: https://datahub.austintexas.gov/dataset/TRANSPORTATION_markings_long_line/nxkm-x3yr/about_data
Long Line Dates: https://datahub.austintexas.gov/dataset/TRANSPORTATION_marking_long_line_dates/m49j-isdy/about_data

**Comment by ChristinaTremel** [comment]
@andrewshensky do we still have work to do on this issue?

**Comment by andrewshensky** [comment]
@ChristinaTremel I think this should be complete both the Long Line and Long Line Dates data is being pushed daily

https://datahub.austintexas.gov/dataset/TRANSPORTATION_markings_long_line/nxkm-x3yr/about_data

https://datahub.austintexas.gov/dataset/TRANSPORTATION_marking_long_line_dates/m49j-isdy/about_data

**Comment by ChristinaTremel** [comment]
Perfect! Closing this!
