### ISSUE TITLE
Incorporate Dark Signal status in Waze datafeed

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15402]
- Now that we completed #15212, AMD would like to incorporate the new dark signal status into their [Traffic Signals On Flash](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-on-Flash/hejg-whp6/about_data) Socrata dataset for Waze to use. 
- Use the same `Type` = HAZARD and `Subtype` = HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT as what's already showing on this dataset

**Comment by Charlie-Henry** [comment]
We should be good, I will double check if we ever get a dark signal that it's populating in here.

<img width="761" alt="Screenshot 2024-01-24 at 2 18 52 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/30810522/49a24176-c640-4f31-8aad-c0ede6114dfa">

```
SELECT
  `primary_st`,
  `cross_st`,
  "HAZARD" AS `type`,
  "HAZARD_ON_ROAD_TRAFFIC_LIGHT_FAULT" AS `subtype`,
  (("Traffic Signal Fault at " || `primary_st`) || " and ")
    || `cross_st` AS `description`,
  "BOTH_DIRECTIONS" AS `direction`,
  ((`location`["latitude"]) || " ")
    || (`location`["longitude"]) AS `polyline`
WHERE (`operation_state` == 2) OR (`operation_state` == 4)
```
