### ISSUE TITLE
[ODP] Data Visualization Requested for Real-Time Traffic Incidents Dataset

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#15411]
## Audit Requirement Notice from CTM 
_As you may already be aware, in July 2023, the Office of the City Auditor released an [audit report](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.austintexas.gov%2Fsites%2Fdefault%2Ffiles%2Ffiles%2FAuditor%2FAudit_Reports%2FData_Reliability_July_2023.pdf&data=05%7C02%7CKaro.Engstrom%40austintexas.gov%7C75539e7c4657458fadca08dc16c14df5%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638410266706428382%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Xtu%2F4%2FT%2Fgn1oYQg76LZ4BMFH0BemxrF8oNnCobiKgBw%3D&reserved=0) addressing data reliability on the City’s Open Data Portal._
 
_In the report, it was recommended to the City Manager that departments interpret the most desired data with visualizations and/or data stories, in addition to providing the raw data. Therefore, departments are required to provide stories and visualizations for the most-accessed datasets._
 
_In response to their recommendations, CTM is responsible for identifying the top three (3) most-accessed datasets on the portal on an annual basis and can assist departments with data visualizations of the top three datasets, if requested._
 
_We have identified your dataset, “[Real-Time Traffic Incident Reports](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.austintexas.gov%2Fd%2Fdx9v-zd7x%2F&data=05%7C02%7CKaro.Engstrom%40austintexas.gov%7C75539e7c4657458fadca08dc16c14df5%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638410266706437429%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eYNdjpbT%2BRm95fdgz9jBaHI2ecPzmWIiYRYg6%2BiZ%2FNk%3D&reserved=0)” (UID: dx9v-zd7x) as the most accessed dataset for 2023._
 
_Here are some site statistics for the dataset:
41,310 Primer pageviews (overview page)
6,987 Grid pageviews (data table or tabular view page)
1,059,706 Downloads
Time period: 01/01/2023 thru 01/16/2024
To see additional web performance metrics, you can visit the portal’s [web analytics dashboard](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.austintexas.gov%2Fstories%2Fs%2F6tzi-5xt6&data=05%7C02%7CKaro.Engstrom%40austintexas.gov%7C75539e7c4657458fadca08dc16c14df5%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638410266706444708%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vx2U0%2F25lDRHiSeAuMLdJYGmue6LIcxyxH44Yk9G%2BXc%3D&reserved=0)._
 
_I noticed that a [story page](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.austintexas.gov%2Fstories%2Fs%2FAustin-Travis-County-Traffic-Report-Page%2F9qfg-4swh%2F&data=05%7C02%7CKaro.Engstrom%40austintexas.gov%7C75539e7c4657458fadca08dc16c14df5%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638410266706450523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z%2Fdoq9BURqMNE5Jiz2zLDd5uPrW4OCuvHeITHKrA7NU%3D&reserved=0) related to the dataset already exists but is incomplete and does not interpret the data with visualizations and/or data stories. The good news is that you’re not starting from scratch. Please complete the story page with the required data visualizations/storytelling by Fri. March 1, 2024._

## History of the Dataset 
- the dataset was based on an RSS feed published by CTM from the Oracle db until spring 2023; at that point we began to pull the data from the CTM Oracle dc directly 
- this dataset was audited while CTM published a story page for it (now deprecated) with the same content as our current one, with the exception of them using a 5 minute RSS feed widget over our data table at the top of the page
`Previous CTM page`:
![199761925-701a69eb-34e9-4dc4-b633-684d73c5d343](https://github.com/cityofaustin/atd-data-tech/assets/100615928/5aa4970d-6886-47c3-a39e-3a2189bc19fb)

- previous issue https://github.com/cityofaustin/atd-data-tech/issues/10688 
      - we set up ETL directly from CTM Oracle database and went live with the story page to replace the CTM site (May 2023)

**Comment by KaroEngstrom** [comment]
## Thu 1/25/24 - meeting with Apps and Data Science

**Comment by Charlie-Henry** [comment]
@KaroEngstrom, I added a map to our active incidents story page. Cool if I deploy this draft?

<img width="1189" alt="Screenshot 2024-01-26 at 3 47 54 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/30810522/d3399623-a504-48ba-9cfb-9e8adbc1be98">

https://datahub.austintexas.gov/stories/s/Austin-Travis-County-Traffic-Report-Page/9qfg-4swh/preview

I think for the other visuals I could make a "trends" story page which could look over a longer scale.

**Comment by KaroEngstrom** [comment]
Yes, excellent. Both sound good to me!

**Comment by Charlie-Henry** [comment]
Made a draft [trends story page](https://datahub.austintexas.gov/stories/s/48n7-m3me) showing the data by day of week, hour, month, and the most frequent types.

**Comment by Charlie-Henry** [comment]
Would y'all mind reviewing what I wrote? If we're good I say we publish it and add a link on the main story

**Comment by dianamartin** [comment]
@Charlie-Henry Looking at your content, this part looks weird. 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/0b002ecc-c771-4ebc-b894-a08f16a091a9)

This should have an "an" instead of an "a"
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/bb5b1c65-77f1-4c9a-95ae-f462348aa75f)

I would maybe suggest sending a screen shot of this draft page to AMD (Ally, Lance) to help with the content. They're used to drafting traffic content for PIO.

**Comment by KaroEngstrom** [comment]
Made small edits (amount > number) and cleaned up the first sentence. This is a great page!
