### ISSUE TITLE
Add Single Sign On feature in TPW Hire

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#15435]
Jennifer W.
HR

Ran into Jennifer at TPW Supervisor Meeting, she said she's not quite ready to go-live with TPW Hire Vacancy report. She had originally asked about why it was in a separate application and I told her because we didn't want real external panelists to have access to our TPW HR app. We realized that we hadn't configured the SSO feature in this application.

**Comment by ChristinaTremel** [comment]
- Gitbook Instructions for [Single Sign On](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzNSSXajDFpzOv2IhIv/knack/single-sign-on)

**Comment by dianamartin** [comment]
# 2/20/24
- Checked in with Michael S., he said to assign him the ticket [INC0365909](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fatx.servicenowservices.com%2Fnav_to.do%3Furi%3Dincident.do%253Fsys_id%3Df387a58e1b140a1491528407624bcb76%2526sysparm_stack%3Dincident_list.do%253Fsysparm_query%3Dactive%3Dtrue&data=05%7C02%7CDiana.Martin%40austintexas.gov%7C7b62b21e562545e6e78708dc2c929dad%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638434255425695326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=nLAjTp6QydxxzYn1Thtzyo0paVYUQ5VXw3PGmGz%2FqZU%3D&reserved=0). He's on an interview panel today, but has time tomorrow to get it done.

**Comment by dianamartin** [comment]
# 2/20/204
- Michael messaged me the MS Entra admin console so that I can enable the "Assignment Required" to `Yes`. 
- He's going to send me the URL/XML file

**Comment by dianamartin** [comment]
# 2/20/204
I let HR staff know this was configured
>the single sign on is working for TPW Hire! [attached a GIF of process]

Tina said
>Wohoo! Thanks for getting that set up

I said
>you're welcome! It'll make it a lot faster for y'all
