### ISSUE TITLE
[Enhancement] Advanced filter tags shift the UI when the first filter is applied

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#15453]
In the Crash list page, the advanced filter toggles produce UI tags to show which filters are applied. The UI shifts when the first filter is applied and removed.

**Screengrab:**

https://github.com/cityofaustin/atd-data-tech/assets/37249039/bc66cf24-6590-4664-9525-1a1efae12b9a

**Comment by mddilley** [comment]
@patrickm02L This is super tiny and not high priority. Never really noticed until I was testing this view with multiple roles in a small amount of time.

**Comment by patrickm02L** [comment]
## 1/31
Leave the space where the filter would show blank, so that when the filter is activated the components don't shift down to accomodate.
