### ISSUE TITLE
IT Support: Call Dell to replace power supply

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#15458]
## Device & User Information (first name and last initial, no last names)
Matt M
## What's the problem?
Contact Dell to replace the power supply sitting on your desk 
 User serial number: 1FRPGW3

**Comment by Vaishnav1397** [comment]
Reached out to the customer service but says the Serial number and the number with the adapter is not matching. However, provided the details for replacement. A case with Case Number: 184379357 has been created.

**Comment by Vaishnav1397** [comment]
Response received and mentioned that "Unfortunately, they are unable to create a dispatch without out correct PPID number for the AC adapter".
