### ISSUE TITLE
[Spike] Build Paper Prototypes

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15464]
## Description
In advance of our prototyping meeting on 2/6/24, we are going to craft "paper prototypes" of a data model. These solutions are meant to be light and can be handed out or projected for others to see. 

Proposals can include: diagrams, flows, code examples but should not go into fully baked solutions.

In the meeting, we'll share our proposals and work together to critique and test assumptions we have about how the model would work.

Proposals should include the following:

#### Requirements
- Data model integrations with the existing locations dataset
- Single source of truth
- Change Log
- View that can be facilitate BI reporting
- Identify sources of data
- Public Schema matches the "real-life" schema
- Use known patterns (best practices)
- Reflects multiple schemas that the data source (org/agency) provides
- Normalize database
- Efficient geospatial aggregation
- Have means in place to protect sensitive data
- Schema Design to reflect Real Life

## Note

[miroboard](https://miro.com/app/board/uXjVNUyWNeY=/)

![Screen Shot 2024-01-30 at 10 38 12 AM](https://github.com/cityofaustin/atd-data-tech/assets/5566727/793269e2-4d72-4fa0-8874-32eb8dea32cc)

**Comment by patrickm02L** [comment]
@xavierapostol couldn't assign this to you, but would love for you to join too!

**Comment by xavierapostol** [comment]
> @xavierapostol couldn't assign this to you, but would love for you to join too!

I'd be more than happy to join y'all!

**Comment by frankhereford** [comment]
Any opposition to closing this issue?
