### ISSUE TITLE
IT Support: Set up the inventory at your new desk.

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#15468]
ST. ELMO

## Device & User Information (first name and last initial, no last names)
Matt M
## What's the problem?
Set up the inventory at your new desk. 

Take the keyboards and docking stations from my desk and place them in the cabinets near your new desks

**Comment by Vaishnav1397** [comment]
Now have moved up the left side desk part of the keyboards and few mice with extensions to the other desk and cleaned up the desk.
