### ISSUE TITLE
Update `Manage Dark Signal` page to include a link to the Emergency Sign Deployment page

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15472]
-  [x] Add link to the `Emergency Sign Deployment` page on the top of the `Manage Dark Signals` page 
   - [Link to Emergency Sign Deployment](https://atd.knack.com/signs-markings#work-order-signs/emergency-sign-deployment/?view_3901_0_filters=%5B%7B%22value%22%3A%22Complete%22%2C%22operator%22%3A%22is%20not%22%2C%22field%22%3A%22field_4343%22%7D%5D)
   - Show on this [Manage Dark Signals Page as button](https://atd.knack.com/amd#dark-signal-management/) (similar to back to MMC button)
- [x] Update background color for `Dark Signal` field in Knack
   - Update colors and make DARK SIGNAL = no, no color
   - DARK SIGNAL = yes, use red

**Comment by susannegov** [comment]
Added button and changed display rule
