### ISSUE TITLE
Update Moped layers with new fields names

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15473]
As a follow-up to https://github.com/cityofaustin/atd-data-tech/issues/15349, update the AGOL layers to match these schema changes.

John will provide a list of field changes and sample data.

**Comment by andrewshensky** [comment]
Response to John in slack:

> "Hey John, I have the updated Moped schema pretty much in place locally. I was curious if you wanted to coordinate a time to overwrite the existing service and then rerun the dev process to populate the records after. With the scope of changes made, there may be some impacts to the web application as well so it may be good to loop in Nathan."

**Comment by andrewshensky** [comment]
This data has now been published and fields truncated during publishing process have been fixed. Data appears to be populating

**Comment by johnclary** [comment]
Thanks @andrewshensky! 🎉
