### ISSUE TITLE
[Enhancement] Enhance Zappa deployment tooling and testing

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15480]
## Description: 
The current Zappa deployment process is fragile and difficult to test locally. This work will make the Zappa deployment more robust and help prevent future deployment issues. It will also get us in the habit of more regularly merging dependent bot updates.

@mddilley @frankhereford would you please help articulate these requirements

- [ ] Make the same updates to the VZ API made in the [original dependabot PR](https://github.com/cityofaustin/atd-vz-data/pull/1338)
- [ ] [Test deployment locally](https://github.com/cityofaustin/atd-vz-data/blob/master/atd-cr3-api/README.md#deploy) and figure out what is preventing a successful deployment
- [ ] Maybe add a check for failed GH actions to the [QA testing sheet](https://docs.google.com/spreadsheets/d/1yALLfU0AKoIQskFp7It4PoDh47NpKWGhKmZ_AF7IZl8/edit#gid=200872708). I could use some input here but it could help us catch other issues before release. 🤷

**Comment by mddilley** [comment]
@frankhereford I added some steps above, but they could definitely use another pass. I also noticed that the GH workflow [sneakily recycles the `requirements.txt` from the Flask app](https://github.com/cityofaustin/atd-vz-data/blob/61869d6f920b359a7d8aad3302c4699e973d1c2d/.github/workflows/aws-vz-api-helper.sh#L40) to install zappa before deployment. Makes total sense how none of us noticed that removing removing that dependency would derail the deployment workflow! 🙃

**Comment by frankhereford** [comment]
@mddilley I think the three items you added in the checkbox list make a lot of sense and are certainly in scope of this issue. I don't have any ideas right not to add, but I think that's a reflection on my lack of experience with zappa and lambda more broadly. If I am able to help work on this issue, getting that experience is going to be really valuable to me. Thanks again, and I'll come back and add anything that comes to mind. 🙏

**Comment by johnclary** [comment]
We are thinking that we can minimize the scope of this by borrowing from a [similar Moped github action](https://github.com/cityofaustin/atd-moped/blob/324bf9806d1bf2eb993fd9b60b1161be85f015d6/.github/workflows/atd_moped_api.yml#L29-L31) to bring the deployment up to support a more current version of Python.

**Comment by johnclary** [comment]
I am going to move this into the icebox in favor moving the whole API from lambda to ECS: https://github.com/cityofaustin/atd-data-tech/issues/18154
