### ISSUE TITLE
IT Support: Clean up duplicate signal cabinet records

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15492]
- As I was prepping the spreadsheet to import data for new signal cabinet fields from #15216, I noticed that there were a couple signal IDs that had multiple cabinet IDs associated
- Synced with Allyson and showed her these records and we realized that these were dups

### Actions:
- Signal ID: 966
   - Cabinet IDs: 1365 and 663
   - Cabinet ID 663 is the correct record
   - Cabinet ID 1365 is a dup and can be deleted

- Signal ID: 4141
   - Cabinet IDs: 1366 and 1367
   - Cabinet ID 1366 is the correct record
   - Cabinet ID 1367 is a dup and can be deleted

**Comment by susannegov** [comment]
Deleted Signal IDs `1365` and `1367`

**Comment by susannegov** [comment]
Reviewed in sprint. Closing issue
