### ISSUE TITLE
Create AWS based email → attachment parsing → s3 solution to support Geo/Maximo/Emergency Mgmt

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#15496]
<img width="1227" alt="image" src="https://github.com/cityofaustin/atd-data-tech/assets/3653206/0f535fa3-55c3-44f9-8eb4-ac324f72c1e3">

Through a conversation and subsequent meeting, it's been requested that the dev team setup the system depicted in the above diagram's top solid box, but not the bottom solid box, which is in the domain of the geo team's FME ETL process / server. This is a solution aimed to be quick to setup and may be replaced with a more real-time solution down the road.

The goal is to:

* provide an email address via the AWS SES service
* ~receive messages at that address and file them in a SQS queue~
* ~parse said email out of that queue with a λ function~
* ~save attachment in a s3 bucket with a fixed name~
* have raw emails be saved into S3 by the SES service
* compose a python script, modeled after existing AFD/EMS ETLs, to parse that email object and decode the email attachment
* save the CSV attachment into S3
* provide geo team support & credentials to access the file from FME

Reference solutions:

* A solution is in place for the VZ AFD/EMS data receipt,  and we decided in the Jan-31 refinement meeting that we'd like to follow that pattern closely because it's known territory and we have the ability to turn up or down the frequency of the ETL as needed in advance of oncoming WX events.

Timing:

While no hard deadlines have been set, it would be ideal to deliver this in the upcoming sprint, starting Feb 7.

**Comment by chiaberry** [comment]
3 - if we copied the AFD/EMS pattern
5 - lambda because of unknowns (error reporting/cloudwatch, troubleshooting)

**Comment by frankhereford** [comment]
The issue's description has been updated to reflect the team's agreed upon approach with regards to how we want to  closely follow the existing AFD/EMS patterns.
