### ISSUE TITLE
Automate access to high-level VZ data points for TPWstat

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#15505]
- [x] Fatalities and serious injuries YTD
- [x] Fatalities and serious injuries by mode

[link](https://datahub.austintexas.gov/Transportation-and-Mobility/TPWstat-Vision-Zero-Statistics-by-Year-and-Mode/d3zy-twyf/data)

**Comment by Charlie-Henry** [comment]
Created a query of the dataset that matches what is shown on the year/mode [VZ viewer table](https://visionzero.austin.gov/viewer/).

https://datahub.austintexas.gov/Transportation-and-Mobility/TPWstat-Vision-Zero-Statistics-by-Year-and-Mode/d3zy-twyf/data

**Comment by katelunceford** [comment]
Notes from OPM Sprint Review on 4/30/24

- Put this one on pause because Richard already meets with Joel to review VZ data, and he wants to reserve TPWstat time to look at the build out of safety projects

**Comment by katelunceford** [comment]
Notes from [Data Science Sprint Planning](https://docs.google.com/document/d/16RBJStu65lHTQa_MVYde7jmortp1ako1P1-A6mPcNOg/edit) on 5/1/24

- We can close this out because the work was done (even if it's no longer needed)
