### ISSUE TITLE
IT Support: gather new employees computer info and place it in inventory

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#15524]
ST. ELMO

## Device & User Information (first name and last initial, no last names)
Oluwayimika A
## What's the problem?
V please track down Oluwayimika laptop information and place it in the inventory. 

I misspoke when I told you i put it in the inventory. I put the first employee in the inventory not this one.

**Comment by Vaishnav1397** [comment]
Sure, will look into it.
