### ISSUE TITLE
[Security] Set up Guest Access to VZE for ACC

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15536]
## Description
We would like to give access to the ACC students who are working on a project to update the UX/UI for the VZE. Guest Access would allow them to login to the VZE with Read-Only access, but not have access to CR3s or any PII sensitive data. 

## Deliverable
- Limit access to students with an ACC email address

## Note
- We don't actually have a Guest Access option in the VZE right now, but are considering adding it. We've come up with this light weight solution for the purposes of allowing the ACC students to complete work on the VZE.

**Comment by johnclary** [comment]
Patrick restored guest access after reviewing the student agreement and discussing our best practices for dealing with PII in the app.
