### ISSUE TITLE
Monthly Maximo Data Quality, 3-1-1 Report

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15570]
This Epic consists of ongoing data quality between TPW Maximo and Austin 3-1-1

**Comment by rebekkabry** [comment]
We were asked to stop sending via email and they would access directly via the reports in MAXIMO. This was a temporary effort during Adry's absence. 
In their start centers, they access the quality report
_SBO[workgroup] Data Quality_
