### ISSUE TITLE
Maximo Work Order Tracking, Enhancements

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15586]
This Epic includes enhancements to the Work Order Tracking screen which includes:

modifications to the Specifications tabs
requesting restrictions on Work Order status changes
requesting fields to be added on any tab within the Work Order tracking screen

**Comment by ChristinaTremel** [comment]
Ensured that all of the existing issues in this epic were tagged with the `Enhancement` label. Closing this epic as part of an effort to clean-up/reorganize Maximo epics.
