### ISSUE TITLE
Maximo Newsletter January 2024

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15602]

**Comment by adry-martinez** [comment]
@ReneVarg25  please update and close this issue with the copy of January 2024 newsletter attached. 
Thanks!

**Comment by ReneVarg25** [comment]
https://cityofaustin.sharepoint.com/:u:/r/sites/MaximoResources/SitePages/J.aspx?csf=1&web=1&e=e2jlP9
