### ISSUE TITLE
Maximo Newsletter - March 2024

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15606]
Write articles related to Maximo updates and distribute via SharePoint with the updated Mailing List

**Comment by adry-martinez** [comment]
Please add: 

- [ ] WO created BEFORE SR is received in Maximo throws off comms between Maximo and 311 when work log Close SR is selected. 

- [ ] SR log note throws off comms between Maximo and 311 as WO log note close sr is selected AFTER.

**Comment by adry-martinez** [comment]
@ReneVarg25 Please close when you publish the newsletter.

**Comment by ReneVarg25** [comment]
### 4/8/2024
March Newsletter posted.
https://cityofaustin.sharepoint.com/:u:/r/sites/MaximoResources/SitePages/Maximo-News.aspx?csf=1&web=1&e=fTSZgP
