### ISSUE TITLE
Maximo Monthly Refresher - February 2024

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15605]
This series will be used for the monthly refresher for Maximo. This is a training effort designed to give users a chance to join once a month to ask questions, re-learn certain processes, and gain information regarding any updates that may be occurring.

**Comment by ReneVarg25** [comment]
### 2/22/2024
Here’s a quick rundown of the topics covered in today’s meeting:
Meetings with different groups for reports discussions
-	We are planning and scheduling times to meet with the different work groups to discuss the various Maximo Reports that are sent out via email or accessed via Maximo directly. We are looking to gain feedback on the effectiveness of these reports and if any changes need to be made to information of these reports or to how they are accessed/received.
Updates to the SharePoint coming
-	We have been working to update the SharePoint page to provide an easier viewing experience and improve accessibility to the information available. We will let you know when those changes go live!
EZMaxMobile Feedback
-	We are still gathering and wanting to receive EZMax feedback, if you have any complaints or concerns regarding the application, or if there are any changes that you would like to see, please let us know! We want to ensure that the application EZ to use and your feedback helps make that possible!
New bookings page for trainings
-	We have launched a new bookings page to schedule trainings with the Maximo team! You can now use this link [Maximo Bookings page](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Foutlook.office365.com%2Fowa%2Fcalendar%2FMaximoSupport%40cityofaustin.onmicrosoft.com%2Fbookings%2F&data=05%7C02%7CRene.Vargas%40austintexas.gov%7C40fb46bc67c14fe1bf5008dc2d86a251%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638435303467199025%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=MlCN5X2bmlCZJZc04MYaORy%2FoDfQf2bZ8gNvtukvRB8%3D&reserved=0) to schedule a date and time, select a specific person to train with, and provide what you like to learn!
 
Continued use of the DTS service request page
-	We do want to encourage the use of the DTS Service request page for all Maximo requests you may have for us. It helps us out greatly by being able to track all relevant information to the requests in one place. Here is the link to the [DTS New Service Request](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fatd.knack.com%2Fdts%23new-service-request%2F&data=05%7C02%7CRene.Vargas%40austintexas.gov%7C5fe47577466a4340bf0408dbffef5f5b%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638385175778186674%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kv32%2B2D6dmoGrwOGHU1nCmA0N2rX2NUxP3lDPrxDJjc%3D&reserved=0) page.

Here is the recording below!

 [ Maximo Monthly Refresher-20240222_100608-Meeting Recording.mp4](https://cityofaustin-my.sharepoint.com/:v:/r/personal/rene_vargas_austintexas_gov/Documents/Recordings/Maximo%20Monthly%20Refresher-20240222_100608-Meeting%20Recording.mp4?csf=1&web=1&e=UZ2Ial&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)
