### ISSUE TITLE
Austin 3-1-1 and SBO February 2024

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15610]
3-1-1 Weekly Consolidation Report

**Comment by ReneVarg25** [comment]
### Week of 2/12/2024
94 - Marked as 'Not in Maximo'
15 - Duplicates
54 - Wrong log
     48 - Addressed (emails)
     6 - Review
10 - Logs did not transfer to 311 (Notified via email)
4 - Tree WOs (May be INPROG)

**Comment by ReneVarg25** [comment]
### 2/23/2024
113 - Marked as 'Not in Maximo'
16 - Duplicates
55 - Wrong Log
15 - Logs Did Not Transfer
23 - Closed
2 - No logs
2 - Tree WOs
