### ISSUE TITLE
Austin 3-1-1/SBO Overdue CSRs - February 2024

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15616]
Overdue CSRs FY23 Reports
Reminder Emails sent out to staff to resolve/close out CSRs.

**Comment by ReneVarg25** [comment]
### 2/7/24### 
Overdue SBO count: 61 [OVERDUE SERVICE REQUEST SUMMARY REPORT_BPS 2-7-24.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0E4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b373b37c1cf4b087042213efe90a42b816c4252/OVERDUE%20SERVICE%20REQUEST%20SUMMARY%20REPORT_BPS%202-7-24.xlsx)

**Comment by adry-martinez** [comment]
## February 7, 2024
### FY23 Overdue SRs

Number of FY23 Overdue SRs: 20
Reminder e-mail with Maximo WONUMs sent to stakeholders, including 3-1-1 Carrie F. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/c2aa7e4d-0be6-4a51-9eaa-0bf7720a16bc)

**Comment by adry-martinez** [comment]
### Feb. 21, 2024
Need to review how e-mail report will look from Maximo. If all is OK, then will set up a weekly scheduled report of users involved in the report to update Overdue requests. This will be done on a weekly basis. 

Review the report
See who the users are
E-mail the affected users ONLY

**Comment by adry-martinez** [comment]
### Mar. 1, 2024 
Follow-up with CTM re: Overdue Report, see #16008
