### ISSUE TITLE
Insert process ended dates for 2 folder processes (LP) (02/21 Sprint) - (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15643]
### We must manually insert process ended dates. The system won't allow the user to add the ended dates. 

1. Process RSN 55883273; insert ended date May 27, 2022
2. Proces RSN 57179465; insert ended date Oct 24, 2022

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created request to run the update script in Prod database , SCTASK0399889

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader End date has been added , Ready for UAT on Prod
