### ISSUE TITLE
Add Transportation Mitigation Fee In Lieu to Active Fee Documentation

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15641]
### Add Transportation Mitigation Fee In Lieu to our active fee documentation. 
- [ ] The GL code should be 8401-2507-1103-4163
- [ ] The division is TDS
- [ ] Fee code is 51294
- [ ] Be sure the GL code is correct in the system

**Comment by TracyLinder** [comment]
Hi @vschandramouli I just assigned this to you. It should be fairly easy; we do need confirmation that the system has the correct GL code for this fee. Thank you!

**Comment by vschandramouli** [comment]
@TracyLinder I have added the fee in our Active Fee documentation. 

Per Priya, the current GL account number is 5120-6200-9400-4163-0000-0000-0000-0000-0000. It was changed this year, should we change it back to the previous GL? (The previous GL is the one mentioned in the ticket description).

**Comment by TracyLinder** [comment]
I created card #15655 to update the GL code. Closing this.
