### ISSUE TITLE
IT Support: Replace the damaged monitor in the Crossing Guards training room 

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#15667]
OTC

## Device & User Information (first name and last initial, no last names)
Matt M
## What's the problem?
Replace the damaged monitor in the Crossing Gaurd room

**Comment by Matthew-M-TPW** [comment]
@Vaishnav1397 Please take care of this ticket

**Comment by Vaishnav1397** [comment]
Have replaced the monitor that got damaged and showing error at conference room.
