### ISSUE TITLE
Grant user access to Moped map on AGOL

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15666]
Please grant Michael J. access to the [Moped map](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=404d31d56b57491abe53ccfd718fcaee). I will post the user's full name in slack.

**Comment by andrewshensky** [comment]
Michael J. has been given access to the MOPED map in AGOL by being added to the COA_ATD group
