### ISSUE TITLE
IT Support: Monitor at Station HS-8751 needs to be replaced

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#15670]
OTC

## What's the problem?
Please replace the monitor at  HS-8751. There are lines across the screen.

**Comment by Vaishnav1397** [comment]
2 of them needs to be replaced one at the meeting room as well.

**Comment by Vaishnav1397** [comment]
Swapped out old one and hooked up the monitors and setup of network connectivity.
