### ISSUE TITLE
Add Status field to TDS Performance Data menu report (TDS Amanda Review Data (99028))

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15675]
### Add a new data column to the report # 99028 TDS AMANDA Review Data
_Report created on #15152_ 

- Add a new column "Status"
- The data maps to the folder process status
- Report name is TDS Amanda Review Data (99028)

**Comment by Nadin-Nader** [comment]
@vschandramouli this only needs to have where they want the status field, which status field and how they want report to end up looking

**Comment by TracyLinder** [comment]
@Nadin-Nader I put this on deck for the sprint beginning tomorrow.

**Comment by TracyLinder** [comment]
### Closing

- We added this AC to the AC on #15647 and are closing this ticket
