### ISSUE TITLE
Follow-up work order form for Communications Work Orders

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15696]
Need to create a Follow-Up Work Order form on the `Communications Work Order Details` page similar to what's on the Technician Work Orders:
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/56080341-69ff-4701-8c54-dcc5fe6df7fa)
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/82aa3c5c-28d7-4c63-9ef4-b28ab77a7ce3)

**Comment by KaroEngstrom** [comment]
## Tue 2/13/24
**Pre-work:** 
- Technician Follow-Up Work Order - model 
     - [Technician Work Order Details](https://builder.knack.com/atd/amd/pages/scene_255)
     - [Follow-Up Work Order](https://builder.knack.com/atd/amd/pages/scene_644)
- Communications Work Order Details - where to add
    - [Communications Work Order Details](https://builder.knack.com/atd/amd/pages/scene_1508)
    - Add to this menu? 
    ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/e6d6f13e-bcc4-4963-b99f-3379e1904d1c)
 
@ChristinaTremel Can you confirm that you want this form added to the existing menu? Will it confuse users before the dev work is done?

**Comment by KaroEngstrom** [comment]
## Wed 2/14/23
@ChristinaTremel - This is built, with some placeholder items for the fields that will be populated by the dev work. I put in a static text field to show that spot. 

Can you check if [Communications Follow-Up Work Order](https://builder.knack.com/atd/amd/pages/scene_1607) looks right, including the follow-up page? I had it redirect at the very end to the Communications Work Order page to mirror the Technical Work Order model.

**Comment by ChristinaTremel** [comment]
Compared the `Communications Follow-Up Work Order` to the `Technician Follow-Up Work Order` and everything looks great!

**Comment by mddilley** [comment]
hey y'all - i have a really good handle on how to get the dev side of this done, but I'm wondering how y'all would like me to get feedback without deploying code directly into production. I might have missed if this is in a test instance app somewhere. Very cool to get back into Data Tracker and see shiny new things! ✨

**Comment by ChristinaTremel** [comment]
@mddilley we're going to make a new test copy of AMD Data Tracker so we have a test instance with all these views! Then we can deploy the code in that test environment. 🙌

**Comment by mddilley** [comment]
Y'all are awesome! That should make quick work out of this. Thanks!!!

**Comment by KaroEngstrom** [comment]
## Thu 2/29/24
- after checking in with Christina and realizing this still needs some rules added, added the following: 

### Follow-Up Work Orders Form
#### Display Rules for the [Edit Work Order form in Follow-Up Work Orders](https://builder.knack.com/atd/amd/pages/scene_1607/views/view_4022/form/rules/display)
- as discussed with Christina, there are some blank fields on the model - I'm not sure if something was removed from the form and the display rules were not updated; documented below
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/8e82ee6c-08d4-49e0-98bd-21c16b20a1a7)

#### Record Rules for the Edit Work Order form in Follow-Up Work Orders (same view as above) 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/d33e11da-f582-44a7-9b23-11affa5ea5af)

### Email - asking Christina if email notifications are needed 

### Follow-Up Scheduled Page
#### [Details view ](https://builder.knack.com/atd/amd/pages/scene_1608/views/view_4023/details)
- not finding a child work order connection to link to; left the text reminder in place 
<img width="692" alt="image" src="https://github.com/cityofaustin/atd-data-tech/assets/100615928/fcbe63cb-75b1-4519-b39a-151749f795e7">

**Comment by ChristinaTremel** [comment]
## 3/13 Notes
- Yesterday I showed Harrell the follow up work order and was able to compare the `Communications Work Order Details` to the `Technician Work Order Details` page and added the `PARENT_WORK_ORDER` and `CHILD_WORK_ORDER` fields that link to the original work order and follow up work order
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/f567fcd1-b0af-4b9d-8024-a6d4c727ca31)
- Synced with Karo this morning and showed her the fields we added but noticed that the fields aren't hiding when the work order is not a follow up
   - Found that a design setting needed to be updated to hide fields that don't have values
- Links to the original work order and follow up work orders are showing/hiding how we would expect them to 🙌
