### ISSUE TITLE
[Power BI] Virtual Conference

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#15706]
Agenda: https://powerbisummitapp.azurewebsites.net/SingleAgendaApp
Monday - Feb 12-Feb 16
- Monday
    - 2:20-3:20
        - Intro to Power BI
        - Introduction to M
        - Lessons Learned from my Power BI Journey
        - What it takes to be Visual MacGuyver
        - Designing Efficient Architectures: Best Practices for Governance, Security, and Sharing Policies
    - 3:40-4:40
        - Getting Started with the SQL Language
        - Data Modeling and DAX with Power BI product team (Ask PBI team product managers)
        - **Advanced Tabular Model Management of the Data Gods**
        - Power BI Azure Map - Are You Ready?
        - Don't Panic I'm Power BI Admin
    - 5:00-6:00
        - **Getting started with Calculation Groups in Power BI Desktop**
        - Approaches for analyzing Budget vs Actual in Power BI
        - Conditional Formatting Two Ways: Easy Recipes for Conditional Formatting
        - Scalable Power BI XMLA Reporting From Excel
- Tuesday
    - 1:00-2:00
        - What are we doing to achieve greater visibility of female talent in technology?
        - Writing DAX queries with DAX Query View
        - Dimensional Data Modeling in Power BI for the Beginner
        - We don’t need another dashboard, be the hero
        - Implementing DataOps practices in Power BI and Fabric
    - 2:20-3:20
        - **Visual Calculations: Making DAX easier**
        - Time Intelligence in Power BI: Easy Wins and What to Watch Out For
        - Unlocking Power BI REST API: Exploring amazing requests with Python
    - 3:40-4:40
        - Introducing Explore - a new way to explore data right within Power BI.
        - **Level up your Power BI game with Field parameters!**
        - Your report looks boring and nobody cares
        - Using Dynamic Management Views (DMV) to create an automated Power BI glossary dashboard
    - 5:00-6:00
        - Modern Power Query User Interface in Power BI Desktop
        - **Leveraging DAX for Advanced Data Storytelling in Power BI**
        - Mastering Mobile Reports Design: Best Practices and Special Cases
- Wednesday
    - 1:00-2:00
        - Create a Star Schema from One Annoyingly-Wide Flat File
        - Double Power: Power BI and Power Apps Integration
        - My Perfect Date (Table)
        - Prepare for Power BI Data Analyst Associate using free resources
        - Continuous deployment
    - 2:20-3:20
        - Mastering Rapid Power BI Development with ChatGPT: A Deep Dive
        - CALCULATE evaluation order
        - From Vega-Lite to Vega in Power BI
        - Advanced data security implementation for Power BI
    - 3:40-4:40
        - Tales from a Power BI rookie: How I learned enough to create engaging reports for front-line workers
        - DAX is Easy….until it isn’t DAX basics for beginners
        - 12 things I wish I knew when I started using Power BI
        - Become Power BI Analyst in 30 minutes!
    - 5:00-6:00
        - Unlocking the Power of the Power BI Community: A conversation with Super Users
        - **Callbacks in Your DAX: Key to Measuring Performance in Power BI**
        - Developing Custom Visuals for Power BI
        - Easy Ways to Understand the Existing Power BI Pr
- Thursday
    - 1:00-2:00
        - Licensing for Microsoft Fabric - An Ultimate Guide
        - From Excel Enthusiast to Power BI Pro: Navigating Data Analysis Tool
        - NotebookEverything: Tips, Tricks to Boost Your Development Using Notebooks
        - Data Modeling in Power BI
        - Make your Power BI Reports Pop
        - Building a Sustainable Data Culture
    - 2:20-3:20
        - Creating Real-Time Analytics Experiences with Power BI Reports
        - Fuzzy Wuzzy Was a Bear. Or a Beer?
        - **Personalization - Help users to help themselves!**
        - Power BI - Time to Git CI/CD
    - 3:40-4:40
        - Semantic Link, where Power BI meets Spark
        - **Advanced Use Case for DAX**
        - Power BI Top 10 tips and tricks
        - Power BI Developer Mode - is it for me?
    - 5:00-6:00
        - **Avoiding Common Pitfalls in Models and Reports: Lessons in the Trenches**
        - Optimizing Power BI: a holistic View
        - Native Kernal Density Estimation in Power BI with DAX and SVG
        - Power BI Datamart: Democratizing data warehousing
- Friday
    - 1:00-2:00
        - **Ask the Microsoft Fabric and PBI Team anything**
    - 2:20-3:20
        - Inventory Management
        - SQL for Power BI Developer
        - Turning Data into Influence: Lessons from Disney+ Imported Visual Storytelling in Power BI
        - **Mastering Paginated Reports: Cascading Parameters and Performance Optimization**
    - 3:40-4:40
        - Sensitivity labels - Fabric, Power BI and Purview
        - HR Reports: DAXing Your Way to Insights
        - Making Power BI Run Faster!!!
        - **Storytelling and Power BI report that connect to different audiences**
        - Powershell Hacks for Power BI
    - 5:00-6:00
        - How to track KPI with Power BI Metric and Charticulator
        - **A complete guide to user-defined aggregations in Power BI**
        - I have always asked for export in Excel. What can you do to avoid this request?
        - Power Query Custom Functions 101
        - Unleash full power of built-in Power BI visuals create custom IBCS-styled charts using DAX only!
        - Modernizing Power BI: Bridging the Feature Gaps in the transition from SAP BO to Power BI

**Comment by maccallump** [comment]
If I am interested will you share?

**Comment by susannegov** [comment]
# Monday
- Lessons Learn in Power BI Journey
   - Only bring what is necessary
   - Transform upstream as possible
   - Check datatypes 
   - Use Views over Tables 
   - Don't Ignore Query Folding
   - Organize folders in Power Query Editor
   - Go for Star Schema Data
   - Create bridge table instead of many:many
- Go

**Comment by susannegov** [comment]
# Thursday
## Building a Sustainable Data Culture
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/a62cb825-53da-42c4-bb05-44c71e34c61b)

**Comment by susannegov** [comment]
# Friday
## Ask the Microsoft PBI and Fabric team anything
- Chat GPT has a business platform where the data is supposedly secure and not used for training. Normal personal ChatGPT isn't.
- Microsoft product team will be working on Microsoft Fabric to be available on the GCC Government tenant around the Summer. Not sure if it mean s it will be available per se, but they said they will be working on it that semester.
- From comment about what PBI resource to use for data model:
> I use these... 
>  
> https://data-goblins.com/dataset-checklist  
>  
> https://exceleratorbi.com.au/new-power-bi-reports-golden-dataset/
>  
> https://www.withum.com/resources/power-bi-data-model-governance-with-power-bi-golden-dataset-and-thin-reports/#:~:text=A%20Golden%20Dataset%20or%20Golden,without%20affecting%20the%20model%20itself.
- About Git integration in Microsoft Fabric:
> Fabric GIT integration doesn't currently support GitLab.
> Git enablement i.e. using downloading files and saving as PBIP you can put those files in source control and use api's etc to do automation of deployments. [Git integration with Power BI Desktop projects - Power BI | Microsoft Learn](https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-git)
>  
> Roadmap item is (trying to find the roadmap item on the other source control platforms as there is one with GitHub and Github enterprise i beleive)

**Comment by susannegov** [comment]
Posted my thoughts in SharePoint: https://cityofaustin.sharepoint.com/sites/PowerBIUsersInternalOnly/SitePages/I-attended-the-Power-Virtual-Summit---What-I-learned-and-Was-it-worth-it-.aspx
