### ISSUE TITLE
Write title & explainer text for each Dash MVP item

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#15701]
- [x] Charlie writes draft
- [x] Kate reviews & applies formula

Use this loose formula when writing the Dash tile explainer text:

**This [app/platform type] [dashboard, report, map, or dataset] [does x, y, and z]**

When describing what it does, use a data and reporting perspective.

**Comment by Charlie-Henry** [comment]
@katelunceford if we're keeping the data and performance hub around, it might be a good idea to update that with a link to Dash and maybe remove some of the old references there like SD 2023 stuff as well?

**Comment by katelunceford** [comment]
We got the first 6 items uploaded so considering this issue closed. I will add the rest from the list above (tracked in [#15433](https://github.com/cityofaustin/atd-data-tech/issues/15433)) and we will continue to upload more Dash items as they're identified.

<img width="1081" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWk3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--437f707e7c6eb66a5f3f1b7145f618e5aa13399b/Dash%20mmMVP%20screen%20capture.png" alt="Dash mmMVP screen capture.png" />
