### ISSUE TITLE
Reorganize PBI Dash prototype into separate dashboards & remove Dash branding

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#15714]

**Comment by Charlie-Henry** [comment]
Moved finance over to it's own dashboard without the dash branding:
https://app.powerbigov.us/links/o2i3wd8oWe?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare

**Comment by Charlie-Henry** [comment]
311 Response:
https://app.powerbigov.us/links/GRNjd1MFk3?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare

**Comment by Charlie-Henry** [comment]
I think we can close this out @katelunceford, everything has been migrated over to the DTS production workspace and out of the mono-dashboard
- [Parking revenue](https://app.powerbigov.us/links/rxpXAezXWr?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=66756e9a-e975-4f9b-8c5b-eaf080b4189b)
- [right of way](https://app.powerbigov.us/links/K9Eh8_p2e5?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=bb3fa765-7adb-432a-9799-e9a7b3fcccd1)
- [311 CSRs](https://app.powerbigov.us/links/KE-WWrAvxo?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=d9a897ca-d593-4e02-a9cd-d760f329d056)
- [Finance](https://app.powerbigov.us/links/EMDcWW0L55?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=c4fbf8d6-d493-4957-99f7-5760c4ddb710)

**Comment by katelunceford** [comment]
These look great, thanks @Charlie-Henry :)

**Comment by katelunceford** [comment]
This is done, just need to make sure we're using the right links in Dash v1.0
