### ISSUE TITLE
Maximo Site Admin Documentation

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#15710]
This issue is to create documentation and flowchart for the Maximo GitHub.

**Comment by adry-martinez** [comment]
### February 7, 2024
- [ ] Create Miro flowchart
- [ ] Write out epic definitions
- [ ] Ask Diana how to add Maximo info. on GitBook/wiki

**Comment by adry-martinez** [comment]
See [Maximo Github Document](https://docs.google.com/document/d/19MKrZJE33PHL2RXxEQITF3sLL0EWc1J-NTtMBeBG8sw/edit#heading=h.e87kv7jvy9vs)
