### ISSUE TITLE
Maximo User Process Discovery - District Maintenance

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15726]
## Objective 
The Data & Technology Services Division is initiating a series of meetings to learn more about Maximo user experiences and processes in TPW. In this meeting we'll be asking questions about how individual teams use Maximo and how it fits into their work processes.

## Goals:  
- Maximo system performance and functionality 
- User experience and interface experiences 
- Current processes within and related to Maximo 
- User feedback and improvement  
- Future roadmap and upgrades 

### User experience and interface experiences 
- Explain your process on how you use Maximo? 

### PROCESS - Planning
- Who plans the work? How do you get work to do? 
- How is work scheduled and issued out 
 
### PROCESS - Implementation
- How is work scheduled and issued out?
- Who is executing the implementation? 
 

### PROCESS - Field Work
- Who is executing the work - implementation? 
- Who is reporting on the work and what are they tracking? 

#### Maximo system performance and functionality 
- How long is it taking to do a Maximo work order in the field? 

### PROCESS - Review & Reporting
- What is your final review, QC process? 
- What reporting do you care about? How are you pulling that information out? 
- What are you reporting? 

### User feedback and improvement  
- What challenges are you having with Maximo? 

### Future roadmap and upgrades 
- What would you like your work order management system to do that you’re not getting right now? What’s missing? 

### Points of Contacts 

------
- [x] Schedule meeting - 2/8/24
- [x] Meet and take notes
- [x] Process notes on Miro [Maximo Assessment Plan](https://miro.com/app/board/uXjVN7sxj9I=/)

**Comment by adry-martinez** [comment]
**Feb. 8. 2024**
Users requested 

- [ ] Auditing Flex Field 2 attribute in Specifications
- [ ] Create 2APRHOLD portlet with hold reason PERMIT to be added on Project Coordinator Start Center for PC to track permit requests
- [ ] create 4-status portlets for each district (South already completed)
- [ ] Remove duplicated Flex Field 2 North District Portlet

**Comment by adry-martinez** [comment]
- [ ] test

**Comment by ChristinaTremel** [comment]
# Christina's Notes

### User experience and interface experiences

- Explain your process on how you use Maximo?

### **Scheduled Work**

- Work comes from the follow up on CSR for permanent work
- Looks at Flex 2 and if work is needed, creates a parent work order
- Then wait for the permit process - Areli is responsible for setting up the work order
    - Submits request through the ROW Portal
    - Sometimes does emergency permitting
    - South
        - Looks at spreadsheet
    - Guardrail
        - Email of work orders
    - Central
        - 2APRHOLD status, permit is the reason
    - North
        - Supervisors send the work orders
            - 1NEW
- Is easier for Areli to have the status in 2APRHOLD and Adriana suggested that if they use 2APRHOLD, that she could make a portlet for Areli to track permitting
- Permits Timeline
    - Arterial is 2-3 months, especially if they need a traffic control
    - Collector/Residential take 1-2 days
- When permit is received, change the status to 2OKTS (ok to schedule)
- Come up with a weekly schedule tracked in SharePoint. Try to stick to a schedule, but it usually doesn’t stay that way. (find link)
- Work is scheduled by superintendents (supervisors sometimes)
- Work order is assigned to the Supervisor
    - Responsibility Field
        - Lead is the Owner
        - Superintendent
        - Supervisor
    - Supervisors go into the field sometimes but not all the time
- Luis and Lara does pavement repair and if it needs markings to be repaired, there’s a spec for `ATD Markings` , `MARKINGS_TYPE` , `TABS PLACED`
    - These reports are run and the Project Coordinator sends a report every 2 weeks
        - PDF of list of work order
    - Go back to the work orders once the report is sent and add a spec that the work order has been sent
- Other groups in the District Maintenance have laptops and Mifis
    - Leads and Tech 3s have tablets, but quite a few people don’t use them
    - Problem is when they promote, they take laptops with them and they don’t always get replacement
- District Maintenance (not CSRs) doing it in the field is about 1% (not very common)
    - They use the `Daily Activities Report` to remember what they did in the field (on the sheet of paper)
    - Bring the `Daily Activities Report` into the office and fill out the Maximo ticket at the shop
    - They don’t use the laptops because these are not easy to do in the field
- District Maintenance does the `Daily Activities Report` and take photo on their phone
- Bring the `Daily Activities Report` into the office and fill out the Maximo ticket at the shop
    - Leads or Tech 3 will fill out the work order
        - Supervisor does it sometimes if the lead is out
    - Email photo to themselves and attach to the Maximo ticket
        - They prefer having photos before and after
    - Fill labor, tools, and materials
    - Use the desktops at the office or laptops assigned
        - Sometimes there’s a wait because not all of the computers work
    - Review that it has pictures and a log and put it into `4COMP`  (as long as the work order is done at the end of that day)
- If it takes multiple days to complete a log, they enter a log for each day
    - Different dates on material, labor and tools
    - Expected to do it daily

### **Reactive Work**

**CSR Work**

- Phone call comes into 311 or a direct call to dispatch
- SR is created in 311
- Sent through interface and a Maximo work order is created by dispatch during regular business hours (7am to 5pm). OCE is dispatch.
    - Standby creates it after hours (Emergency SRs)
- District comes in at 6am and starts looking at work
- Work order in Maximo, there are 3 districts
- Shon would help if it needs extra support, but once the work order is created the Techs manage their own work
- Improvement to the process last year - Supervisors of each district would assign CSRs to particular crews. Now the groups are set in place and there are 2 guys per district. They see exactly what needs to be done and they can pull their own calls live
    - 1 Crew Leads over CSRs look at all 3 districts (Cory is the lead over this)
        - Reviews `Newly Screened District Work Orders` widget on Maximo start center
    - 2 guys are assigned to each area per district and pull their own CSRs (Tech 1-3s)
        - Once the lead takes ownership, it moves into an in progress type status and goes into bucket `Active Work Orders Owned By Me`
        - Fill out the `Owner/Lead` and change the status to `In Progress`
        - At first they are doing this in the beginning of the morning, but throughout the day they also have iPads that they can continue finding work
            - 7 iPads total in the group
            - CSR team has enough iPads, but they took iPads from other work groups in District Maintenance (need iPads)
    - Most CSR calls take about 15 minutes
- Monday morning might have 15 calls ready to respond to
    - North district doesn’t get as many as Central and South
- CSRs can have multiple priorities
    - 2 - only have 48 hours to respond
    - 4 - only have 24 hours to respond, but it usually takes them 1-2 hours to respond
- Once the ticket is assigned, they go do the work
    - If it’s a pothole, they assess it:
        - Go to Problem Code and if it wasn’t a pothole, change it to `Alligator Cracking` - this is a failure that the subgrade is not compacted properly, water seeped through, and it starts failing
        - Will use `Pavement Failure` some times and `Damaged Pavement`
    - If they can fix it, they’ll make it safe, but if it’s beyond repair they add a `FLEX FIELD 2` (this is a temporary repair)
        - Internal notification using this work order to send it to another Group
        - The group will get the completed work order and they determine if follow up work is needed
        - If follow up work is needed, they create another work order
    - Work order fields that are filled out when completing:
        - Actuals: Labors, Materials, Tools
        - Filled out in the field
        - Using EzMax Mobile
        - Entered in the In Progress status
    - Then the field staff `4COMP` (Completed), Supervisors `4COMP-NFR` (Needs Final Review), and Superintendents do `4QACOMP` (Closed)
        - Sometimes the 4COMP is missed and the Supervisor does the work order
    - Have to select work log, `Type` field and select status to close out CSR
        - This is problematic to the team because it’s easy to forget this and that will cause the SR to be open
        - Also this change happened with the 311 standardization and only the CSR crew got trained
            - This means that standby crews don’t always complete the work order/CSR correctly
    - Then send a follow up work order that a permanent repair is needed. That will go to north/south/central district (not the CSR group)
        - Other District team receives that work order
    - Completed work order to determine follow up
        - North: Junior, Bardo
        - Central:
        - South:
    - An enhancement they would like to see if who acknowledged the completed work order
        - They acknowledge it by changing `Flex Field 2` to `Acknowledged By Receiving Group`
            - This just overrides that field and there’s no history that that was sent to be reviewed by the District
        - They don’t log if a follow up work order was created
    - How long do queues last for the Superintendents doing the last review:
        - Queues are long for North Central South. Noted having ~500 in queue, ~1300 in queue, ~900 in queue
    - Spends an 1-2 hours a day looking at Maximo and some

**Standby**

- Only difference is they create work orders that they’re going to respond to
- Supervisor is the one on standby
    - They monitor Maximo and determine what needs a work order
    - Crew under that supervisor is also on standby
        - Monthly rotation - on call (North/Central/South)
        - Standby rotated within that district weekly
        - Some people would like to see it more simplified
- When a work order is created, they call the techs to do the work (2-3 people)
- Are expected to review it overnight and that is a challenge and does get missed
- They have phones that they receive texts from but it’s not used that often
- They do have a 24 hour window to respond so it’s usually okay to wait overnight
- If it’s an actual emergency, Division Manager receives a call
- **Coordination between groups**
    - They coordinate with OCE and flex field work orders back and forth between them if they have question
        - Work is supposed to get reviewed by OCE
    - Sometimes work gets sent to Sidewalks (some groups have stopped using it, but not everyone has had this communicated so there are still some people that are sending these)
        - Tripping hazards end with District Maintenance
        - If it’s ADA, it still needs to be sent to Sidewalk

**Other ways to receive work**

- Sometimes work orders are created internally by `Supervisors` if they see an issue
- Special Projects from other division
    - Transportation - build guardrails
- Help with Service Plan Work
    - District maintenance doesn’t have their own service plan work orders, but help with service plan work orders occasionally
- UER - help asphalt work

### PROCESS - Planning

- Who plans the work? How do you get work to do?
- How is work scheduled and issued out

### PROCESS - Implementation

- How is work scheduled and issued out?
- Who is executing the implementation?

### PROCESS - Field Work

- Who is executing the work - implementation?
- Who is reporting on the work and what are they tracking?

### Maximo system performance and functionality

- How long is it taking to do a Maximo work order in the field?

### PROCESS - Review & Reporting

- What is your final review, QC process?
- What reporting do you care about? How are you pulling that information out?
    - Reporting is determined by Dave Anderson’s team
    - There’s a lot of reporting they do
- What are you reporting?

### User feedback and improvement

- What challenges are you having with Maximo?
    - Flex Field 2 happens - need to make sure nothings getting missed during that transfer period
        - It can just easily be erased
    - Everyone uses Maximo different and ideas of how things are passed on are different
    - Trouble with photos
        - Need the photos to have some context of where things are located
    - Onboarding to Maximo is done by Superintendent, Supervisors, or Leads
        - If there’s questions, they go to Adriana and Rene

### Future roadmap and upgrades

- What would you like your work order management system to do that you’re not getting right now? What’s missing?

### Findings:

- Overriding Flex field 2 causes issues
    - Could we just capture “Acknowledged” as a secondary step in `Flex Field 2`
    - Can we audit `Flex Field 2`?
        - Auditing one specification would audit all specifications and that would be over 1000

**Comment by dianamartin** [comment]
# 4/3/2024
## Diana Notes
Reactive Work

Comes in as a SR 

Mike, Shon, Corey

- Mike - superintendent
    - Has a reactive and scheduled

Start

- 311 Phone Call SR
- Or direct call to dispatch]

SR Created

Sent to interface 

OCE Dispatch will convert (regular business hours, M-F)

- Dispatch team *(we’ll need to talk to him)* - Lisa
    - SBO crew starts at 6 am
    - Start at 7 am
    - End at 5 pm

“Stand by crew” - On Call

- Emergency SRs

North - “Junior”

Central - Mike/Shon/Corey (one lead for that crew)

South - Eli

Superintendent looks at it, Shon (supervisor) looks at it

- 7 Tablets - they access work group bucket
    - Get 9 more for the rest of the
- New work is reviewed in these buckets
    - “SBO 311 SRs”
    - “NEWLY Screened District Work Orders”
    - “Active Work Orders Owned By Me”
    - Shon only steps in when a call is needed if it’s more complex or different type of emergency
    - Tech 1-3
- Crew lead is looking at all three geographic area queues
- Using automated prioritization

Monday (CSRS from the weekend)

- Corey might have 15 work tickets - routine response

Most calls are about 15 minutes within one district

- Priority 4: more of an emergency (24 hrs)
- Priority 2: less of any emergency (48 hrs)
- Routine - 30 to an 1 hour

District Maintenance - other groups investigate (AE, AW)

- Investigation: over 550 (2.5 month period)

        Start responding on work

- Self assignment - “Owner/Lead” field
- Manually change status - 2INP IN PROGRESS

In the Field

- Do the work in the field
- Change to “**Problem Code**” if it wasn’t a pothole, “alligator cracking”
    - North: never used “alligator cracking”, “damaged pavement”
- Go to “Specifications”, go to “Flex2”
    - Makes requires follow up work - (ex. N/C/S - investigate for future work)
    - Dropdown of various groups list
    - “Acknowledged by Receiving Group” - final state of “Flex 2”
        - Do you add a log note? No
            - They don’t do this right now, but probably should
- Go to **Actuals**
    - Labor
    - Materials
    - Tools
- They do this on the tablet, EzMaxMobile
    - Bookmarking their work for entry later
        - Using a paper form “Daily Activities Report”
- NEW - 1NEW
- 3FR - Final Review
- Field Staff 4COMP
- Supervisor 4COMP-NFR (Submitted but needs QA/QC)
- Supervisor 4QACOMP

Superintendents creates new parent work

- N: Junior -
- C: Bobby/Mike -
- S: Eli/Luis -

Queues - lots of tickets to review (1800)

- Junior - 1 to 2 hours

Every person should be Maximo everyday

So you have to select work log in Work Order to close out SR  

- “Type” field
- Select statuses close out SR
- Manual status close out Work Order

### Stand by crew

- N/C/S - Districts take turns (monthly rotation)
    - Supervisor rotation is weekly
    - Supervisor is reviewing Maximo
- Create work orders that they’re going to respond to
- Call out the technicians to do the work
    - 1 techs - day time
    - 2 -3 techs - in the evening

**Overnight emergency**

- Cave in road, blocks the road

## Permanent Work

- Flex field -
- To send to OCE for review, get their recommendations

## Sidewalks

- Send to Sidewalks?
- Send to Austin Adams, Justin Norvell in Maximo
    - Intersections, ADA

## Scheduled Work

- Still coming from CSR —> Work Order
- Investigation, if work needs to be done -
- Create a parent follow-up
- Send to Areli C.
    - Permit process
    - Asphalt - based on spreadsheet
    - Guardrails - email from work order
    - Center - 2APRHOLD
        - Hold Status: `permit`
    - North - send work order
        - 1NEW Status?
    - Process Change: New portlet “Work Orders - Needs Permit”
- Arterial permit - 2-3 months
- Collector/Residential permit - 1 or 2 days
- Change status for North/Central
    - 2OKTS - “Planning completed, OK to Schedule”

## Scheduling

- Supervisors/Superintendents create a weekly schedule
- In SharePoint
    - in SharePoint List - share link with it

## Work Needs Markings

- Pavement repairs
- Updates Specifications
    - ATD_MARKINGS
    - MARKINGS_TYPE
    - TAB_PLACED
- Project Coordinators, Areli pull the report
- Send report - PDF
    - When it was completed
    - Work Order #
    - Classification
    - Problem Description
    - Service Address
    - Marking Type
    - Tab Placed
- Project Coordinator - updates Specs
    - Secondary subtype on “ATD_MARKINGS”
- SMD creates whereabouts work orders

## Hardware

Mi-Fi’s

- Tech 3s

Only 1% of techs doing work in the field

- normal work, non-CSR
- using the Daily Activities report, enter ticket in yard or desktop

Laptops

- Leads, Tech 3s
- Photos
    - email to self
    - convert format from HEIC
    - creating work orders
- Junior - have convert Dell 2N1 - Lenovo
    - replace computer
    - give his to a tech

## Multi-day Work

- Adding daily -  Labor, Materials, Tools
- pretty consistent!!
- Before and After Pictures
    - they try to but sometimes CSR don’t have anything to observe

## Field Observation

- Dispatcher creates work order if citizen calls

## Service Plan Related Work

- these are already loaded by Maximo team
- they help with those kinds of work orders
- they go to work order and they enter their Actuals

## Reporting

- team: Dave, Richard gather information to OPM

## Feedback/Challenging

- Making sure we keep track of Flex field
    - See who is sending it
    - Who received it
- Don’t know who acknowledged
- Maximo trainer - used it
    - 2 day training

## Training

- Standards - taking photos
- Standard Training
    - Onboarding
- EzMaxMobile App Training
- Onboarding
    - right now - Supervisors/Leads
- 

Maximo job description

- for Tech 1, 2, 3

## Next Steps

- Meeting with technicians N/C/S

# Debrief Meeting

- Adry, Rebekka, Diana, Christina

## Insights

### Process Improvement

- “Flex” field” - (basically a follow-up action)
    - They don’t know which group gets the “transfer”
    - It gets overridden when it’s “acknowledged”
- ENHANCEMENT: Users want an audit field (to know who submitted the transfer)
- ENHANCEMENT: Think acknowledgement should be a separate subtype spec
    - Option 1: Add field in specs for “**Transfer Requested By**”
    - Option 2: Add subtype field in “**Flex**” for “**Acknowledgements**”
    - Option 3: Add field in work order “**Acknowledgement**”
    - Option 4: Specs get audit logs turned on
- ENHANCEMENT: Set REQUIRED “Material” entry
    - at least one record
    - “No Material” selection

### Hardware Updates

- Need more tablets 9 minimum
- More 2n1 laptops (Lenovo & Dell)
    - 
- More usage of EzMax
- Expand lab space in TownView

### Training

- Onboarding Maximo training
- EzMaxMobile

**Comment by ChristinaTremel** [comment]
Notes have been added to the miro board! Closing this. ✅
