### ISSUE TITLE
Provide classification example for requirements prior to 4-status

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15731]
DTS inquired which attributes need to be required for a classification (example: SEALCOAT_WORK)

**Comment by adry-martinez** [comment]
**Feb. 12, 2024**

Issue has resolved with SBO Site Admin. F/U will be needed with User.

**Comment by adry-martinez** [comment]
### Feb. 8, 2024

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/133d00f0-935f-4f14-831a-c8482b0f5b63)

**Comment by rebekkabry** [comment]
# 9/12/24 
Reopening as CTM has completed testing and ready to move to PROD. 
@ReneVarg25 will draft to send email to stakeholders notifying of process change and will advise CTM ready for PROD push.

**Comment by rebekkabry** [comment]
# 9/17/24 

- Rene provided email template 
- Rebekka created document from template https://docs.google.com/document/d/1iQfNMbgzKqRydURl4PLnuT2uhweeEoEOWnzktDgak74/edit?usp=sharing 
- Reviewing internally before sending to DM/SI/SV for approval of document, push to PROD, email send out to stakeholders.

**Comment by ReneVarg25** [comment]
### 9/18/24
CTM implemented changes

**Comment by rebekkabry** [comment]
- Created PDF and shared with management. 
- PROD in effect. 
- Closing ticket.  
[Maximo Change Notification_Sealcoat Specifications Required (2).pdf](https://github.com/user-attachments/files/17065534/Maximo.Change.Notification_Sealcoat.Specifications.Required.2.pdf)
