### ISSUE TITLE
EzMaxMobile Training - Will E.

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15752]
- [x] Verify EzMaxMobile access for users
- [x] Send video of app Installation
- [x] Schedule in-person meeting for basic navigation training
- [x] Collect current process (portlets used, how WOs are searched, etc) prior to in-person meeting
- [x] In-Person Training

@ReneVarg25 please follow this checklist and add dates when each task is completed and any notes.

See list of names in edit mode.

**Comment by adry-martinez** [comment]
#### Feb. 12, 2024
Include Ron K. and Reza K. in the training.

**Comment by ReneVarg25** [comment]
### 2/15 /2024
Sent email with information on what EZMax is and what it can do based on users responses to sent questions (listed below). Provided users with links to videos and QRG (listed below) and prompted for possible in person training.


Questions asked in email:
Do you use EZMaxMobile currently?
How often?
What processes do you normally use it for? (i.e. filling actuals, adding attachments, etc.)
Is there something you wish to learn about EZMaxMobile?
If so, what is it?

Links sent:
1.2 Navigating and Viewing Work Orders.mp4
 [ 2. How to update actuals](https://cityofaustin.sharepoint.com/:f:/r/sites/MaximoResources/EzMaxMobile%20Resources/2.%20How%20to%20update%20actuals?csf=1&web=1&e=2D6RYT) – a collection of 4 videos
 [ 3. How to update other work order tabs](https://cityofaustin.sharepoint.com/:f:/r/sites/MaximoResources/EzMaxMobile%20Resources/3.%20How%20to%20update%20other%20work%20order%20tabs?csf=1&web=1&e=CisX1Z) – a collection of 4 videos
 [ EZMaxMobile Application Training Doc V1.pdf](https://cityofaustin.sharepoint.com/:b:/r/sites/MaximoResources/EzMaxMobile%20Resources/EZMaxMobile%20QRG/EZMaxMobile%20Application%20Training%20Doc%20V1.pdf?csf=1&web=1&e=MRSbIU)

**Comment by ReneVarg25** [comment]
### 2/20/24
Reached out to users provided link to bookings page for assistance in scheduling in person training.

**Comment by ReneVarg25** [comment]
### 2/29/2024
Reza and Ron showed up for meeting. 
Will requested to schedule for another day.

**Comment by ReneVarg25** [comment]
### 3/4/2024
Will E. scheduled training day for Thursday 3/7

**Comment by ReneVarg25** [comment]
### 3/11/2024
Performed training. User will use EZMax on a "test run" to see if they wish to continue using.
