### ISSUE TITLE
SBO 311 Reports

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15768]
Discuss and review the usefulness of the following 311 reports:

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/10355dd8-8feb-47b4-b9ea-7cd72d4f485d)

**Please meet with staff to discuss their usage. Click on Edit to view the full names.** 

- [x] OCE: Floyd B., Lisa G., Art G., Ron K., Robert F., Arielle., Angela J., Tyler S.

- [x] Other: Johnny C. (UER), Justin N. (Sidewalk), Jonathan G. (SLCT)

- [x] Forestry (SD23): Shane K., Gumecindo L., Lisa K.

- [x] District Maintenance: Baldomero R., Bardo M., Eladio M., Shon J., Michael C., Areli C.

- [x] #16750

Dipa Y., Khalil B., John R.

**Comment by adry-martinez** [comment]
Added to #15804

**Comment by ReneVarg25** [comment]
### 2/14/2024
Removed Dipa, John, and Khalil from reports

**Comment by ReneVarg25** [comment]
### 2/23/24
Forestry Meeting Notes:
Reports to keep sending via: MD5 & MD6 (Data Quality) - viewed and used daily
MD5 & MD6 (Vegetation 2 Weeks) - Not used as frequently, but need to discuss with district maintenance (add to agenda)

To be completed in #15992 
311 Dash Board, 311 Open Requests, 311 Weekly Data and Open Requests - To be added to Maximo report list
Standardization - not part of mailing and does not use

**Comment by ReneVarg25** [comment]
### 2/29/2024
Ron: Only uses SBO 311 Dash Board, requested no changes.

**Comment by adry-martinez** [comment]
### March 26, 2024 
**Participants**
Floyd B., Peggy M.

**Meeting Notes**
Not all members attended the meeting. 
Peggy advised to send e-mail to stakeholders if they would like to maintain a part of the mailing list. 

**Action Items**
Maximo team sent e-mail on 3/26 to users to confirm their request. Pending response.

**Comment by ReneVarg25** [comment]
### 4/11/2024
Users Tyler, Lisa, and Johnathan have been removed from 311 reports
Waiting on responses from Johnny and Justin for responses, will remove on Tuesday 4/16

**Comment by ReneVarg25** [comment]
### 4/15/2024
Updated to remove the following users from reports:
- 2nd Michael C. email
- Lisa G.
- Tyler S.
- Jonathan G.

**Comment by ReneVarg25** [comment]
@adry-martinez is #16750 in relation to removing Dipa, Khalil, and and John?

**Comment by adry-martinez** [comment]
@ReneVarg25  I closed 16750 as a duplicate.

**Comment by adry-martinez** [comment]
Will be closed by EOD today.

**Comment by ReneVarg25** [comment]
### 4/17/2024
Justin and Johnny have been removed from 311 reports list, closing request.
