### ISSUE TITLE
SBO Utilities and Structures Reports

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15769]
Discuss and review the usefulness of the following Utilities and Structures reports:
![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/f12dc88f-f2af-45fc-8210-a0f5786f42ce)

SPOCs:
Clay R. - Division Manager, Pavement Ops
Mike D. - Project Coordinator
Ryan H. - Program Manager III
John P. - Superintendent

**Comment by ReneVarg25** [comment]
### 2/20/2024
Reached out to SPOCs to schedule a date and time for discussion.

**Comment by ReneVarg25** [comment]
### 2/21/2024

Questions to be asked:
- Are you looking at the reports? If so, how (via email or Maximo)?
- Which do you prefer (Maximo or email)?
- Do you want to continue receiving via email? Or are you more comfortable with Maximo?
- Is there anything you want us to add to these reports?

Notes from meeting:
**Are you looking at the reports? If so, how (via email or Maximo)?**
John P. (executive report/91 day older or under)
Michael D. - executive(Maximo), quality concerns(email), permit(email), not supervisor or dashboard
Clay - executive, but still has need to review at any given time on Maximo
**Which do you prefer (Maximo or email)?**
Clay - Maximo
Michael D. - for concerns, email, others Maximo
**Do you want to continue receiving via email? Or are you more comfortable with Maximo?**
Prefers current set up for receiving and accessing through Maximo
**Is there anything you want us to add to these reports?**
Update frequency of Concerns report to be more often

**Comment by adry-martinez** [comment]
@ReneVarg25  can you clarify which are the ones that need to be on their Report List? and which reports need to have their scheduled modified?

**Comment by ReneVarg25** [comment]
@adry-martinez 
Yes, they stated that they are fine with the way they are currently receiving the reports as it is. Some check via email while others go in through Maximo to obtain them. They requested that no changes be made to either the method they receive or the information within the reports.

They only requested that the SBO Utilities and Structures Data Quality Concerns Report be increased to daily which has been taken care of.
