### ISSUE TITLE
Automate access to Bond Spending data points for TPWstat

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#15766]
This view should cover all of these categories: [view](https://datahub.austintexas.gov/Transportation-and-Mobility/TPWstat-Mobility-Bonds-Expenses-Summary/x9ef-t4wh/about_data)

- 2016 Bond Spending by Category
- 2018 Bond Spending by Category
- 2020 Bond Spending by Category
- Community Services bond spending
- Sidewalks bond spending (2016, 2018, 2020)
- Urban Trails bond spending (2016, 2018, 2020)

**Comment by katelunceford** [comment]
Data Science Sprint Planning 5/1/24

- We'll need to publish the target to the ODP. Right now it's a spreadsheet.
- Or if it doesn't change, maybe we can hard code it.

**Comment by Charlie-Henry** [comment]
I saw Michael added this to his TPWstat Power BI report.
