### ISSUE TITLE
SBO Pavement Operations Reports

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15770]
Discuss and review the usefulness of the following Pavement Operations reports:
![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/6a1ac1fa-8447-4bc3-970f-ce89a1ad32cc)

SPOCs:
Jermaine B. - Division Manager, Pavement Ops
Andre E. - Project Coordinator

**Comment by adry-martinez** [comment]
@ReneVarg25 any updates on this?

**Comment by ReneVarg25** [comment]
### 4/11/2024
Andre: Maintain the current list for both him and Jermaine, and add Johnathan G. (SLCT) to these reports.
- Johnathan has been added to lists.
