### ISSUE TITLE
[Maximo] Deactivate L. Trevino

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#15791]
**Please remove L. Trevino from PWD Mailing List and Maximo. They are no longer with TPW.**

### Activating/Deactivating Maximo Account ###
 - [ ] Click on **Administration** > **Resources** > **People**
 - [ ] Search the person by **User ID** or by name
 - [ ] Update the person's information
 - [ ] Add **SBO** as the Person's Site under Employee Information
 - [ ] Click on the Status icon and update the profile to ACTIVE 

To **deactivate**, click on the **Status** icon and update the profile to **INACTIVE**
- [x] Remove the profile/user from the PWD Maximo User mailing list.

**Comment by adry-martinez** [comment]
> L. Trevino has been removed from PWD Maximo User mailing list and is not part of any scheduled reports.
> 
> @adry-martinez do we set their account to inactive as well?

@ReneVarg25  yes, please.

**Comment by ReneVarg25** [comment]
@adry-martinez Account set to inactive. Would it be possible to do the following to the template for clarity:

- Under Activate/Deactivate title heading, add "To Activate: "
- Separate the title heading for deactivate steps leaving "To Deactivate: "
- Changing set status to Inactive as part of the check list to reflect the activate steps

**Comment by adry-martinez** [comment]
@ReneVarg25  done!
