### ISSUE TITLE
IT Support: Please make sure that the projector is “ready to go” for this meeting next week.

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#15798]
St Elmo
## Device & User Information (first name and last initial, no last names)
Projector/ Tv & Jenny, K
## What's the problem?
"Please make sure that the projector is “ready to go” for this meeting next week.  Maybe we can offer Jenny the option of either the projector OR the front monitor.

Thanks."

Meeting is February 14 from 9:30 to 3:30 

## What did you do to resolve the issue
Need to make sure everything is working good until the meeting.

**Comment by Matthew-M-TPW** [comment]
@Vaishnav1397 can you cover this meeting while I head to OTC?

**Comment by Vaishnav1397** [comment]
Yes, I will make sure to check this if everything is working well and will be here if user is facing any issues.

**Comment by dianamartin** [comment]
@Matthew-M-TPW who was the requester for this?

**Comment by Vaishnav1397** [comment]
I think so it should be for King, Jenny. I have now added the username above.

**Comment by Vaishnav1397** [comment]
Have setup the meeting room, applications have been setup at the bottom and informed the users. Mention to let us know if they are facing any issues during the meet with vendors.

**Comment by dianamartin** [comment]
@Vaishnav1397 what meeting location was this conference room?

**Comment by Vaishnav1397** [comment]
It's at St Elmo Meeting Room B.

**Comment by Vaishnav1397** [comment]
Meeting has been successfully completed and taking care on the issues.
