### ISSUE TITLE
Remove ATD and PWD from Folder Fees - (LP) (On PROD)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#15818]
The keywords ATD and PWD need to be removed from Folder fees in AMANDA and replaced with TPW. 

Fee documentation has been updated to reflect new names for Active fees only.  

List of fees to be changed is provided below. All instances of ATD need to be changed to TPW, except for fees 83451, 452 and 453. Those can be left unchanged.

<img width="324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1NTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9421a6dda6c1807fd070967441bb413b12129867/image.png" alt="image.png" />

**Comment by vschandramouli** [comment]
Updated Active Fee documentation. Need to confirm with @TracyLinder  and @Nadin-Nader if fees 83451, 452 and 453 need to be added to our doc and updated in the system. 

Moving to backlog.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and created dev deployment request

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT whats the SN request # for this Dev deployment?

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader  Verified in Dev, Looks good.
Craeted Test Deloyment plan, SCTASK0405909

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been approved by Kyle to go to PROD

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created Prod deployment request - SCTASK0408771

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Prod , Ready for UAT

**Comment by Nadin-Nader** [comment]
Approved by Kyle, closing
