### ISSUE TITLE
Feature to `Re-Open` SMD contractor work orders 

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15816]
- SMD requests that Contractor work orders be rolled back to the `ISSUED` status often
- We've identified the need to create `Re-Open` button that would allow SMD to move work orders that are `CLOSED` back into the `ISSUED` status. 
- When doing this for individual requests I typically update the following `contractor_work_order` object fields: 
   - `Work Order Status` = ISSUED
   - `Contractor Signature` is blank
   - `Contractor Submitted Date` is blank
   - `Contractor Submitted By` is blank
   - `ATD Owners Representative Signature` is blank
   - `ATD Approved Date` is blank
   - `ATD Owner Rep Name` is blank

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/15459#issuecomment-1917750858_

**Comment by ChristinaTremel** [comment]
@dianamartin could you add additional build notes to this issue?

**Comment by dianamartin** [comment]
# 2/23/2024
- Looking into the process of "Re-Opening" a Contractor Work Order
- Testing record `458` - `GEOFFS DR | GARBACZ DR | MARSHITAHS WAY` - No inspection records

## Follow steps that Christina has:
- When doing this for individual requests I typically update the following `contractor_work_order` object fields:
  - `Work Order Status` = ISSUED
     - going from "CLOSED" to "ISSUED"
   - `Contractor Signature` is blank
       - setting to `blank`
   - `Contractor Submitted Date` is blank
     - setting to `blank`
   - `Contractor Submitted By` is blank
     - setting to `blank`
   - `ATD Owners Representative Signature` is blank
     - renamed to `TPW`
   - `ATD Approved Date` is blank
     - renamed to `TPW`
   - `ATD Owner Rep Name` is blank
     - renamed to `TPW`

**Comment by dianamartin** [comment]
# 2/23/2024 
Messaged Kati
>I fixed the "Re-Open" button in the Contractor Work Order details page. The page rule was broken and it wasn't showing up on "Closed" Work Orders. 

She said
>Oh awesome! I shouldn’t have to bug y'all to reopen anymore then!
