### ISSUE TITLE
Test Rocky Linux 9 as the planned replacement OS for our on-prem servers

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#15829]
As part of https://github.com/cityofaustin/atd-data-tech/issues/11835, I opened up a dialog with the CTM linux team and Jason G. provided some really helpful information for us as we plan to transition away from these CentOS 7 machines. The CTM team is aiming to adopt Rocky Linux 9, which is a "bug for bug" compatible system to RHEL. 

Jason wrote:

> There are some other changes that we've had to figure out too, like having to migrate to `firewalld`. I know y'all leverage Docker so there may be some things to figure out with using a new `firewalld` backend instead of the traditional `iptables`. The reason for `firewalld`, even though I'm not very fond of using it, is that Red Hat has fully deprecated `iptables` on version 9 in favor of `nftables`. And unfortunately, many other open source projects like Docker, `libvirt`, and others don't directly support using `nftables` yet, but they have introduced `firewalld` compatibility layers. So that's what we went with.

The route that Jason proposes here with local testing of the OS and how it works with our stack is sound advice, and I'd like to start this testing and configuration process when we have time. I absolutely see a world where, if we give ourselves enough time to do it, we can make this switch-over a no-downtime event.

As he suggests, I'd like to install this OS as a VM on my machine, or perhaps in a throw-away, cheap, EC2 machine so it's not local to my laptop and matches the chip architecture that the servers will ultimately reside on. This will make them available to the whole team as well -- using ec2. Then it's a matter of getting our airflow and other installations installed on it, working out any compatibility issues, and then being ready to deploy to our future machines when they are provisioned. In an ideal world, this feels like a `8` to me, but there's a lot of uncertainty in that because it's easy if it goes easy and real gnarly if it doesn't. I'm optimistic though.

At the appropriate time, I propose we make this issue an epic and give it children along these lines:

### In sequence

* Install and test out Rocky Linux 9 WRT `docker`/`firewalld`.
* Inventory /all/ scripts, stacks, etc of anything we've put on any of these machines and decide what we want to bring over.
  * This includes software dependencies .. system libraries and the like
* Package up the stuff we're going to bring with us, including configurations and put them on a fresh RL9 install
  * Debug everything until it works just the way we want, and document the process to get there
* When we get the new servers from CTM in advance of the switch-over, repeat this installation process and when we're good, ask CTM to switch off the old machines and put the new ones in service
  * The idea here is to cause whatever havoc we're going to cause figuring out how to operate in this similar-but-different environment on throw away machines and take only the lessons learned, not the havoc, to the actual servers we're going to inhabit.

### In parallel

* Discuss and decide on any changes we want to make to our policies and procedures regarding operating our servers. We're getting that rare "fresh start," so it's an ideal time to make our server-future the one we want to live in.

**Comment by chiaberry** [comment]
a comment in slack about rocky linux futures
> maybe we can be intentional about where we store our logs and get them off /

**Comment by chiaberry** [comment]
Chia will invite everyone to a meeting, Frank will prepare an agenda

**Comment by frankhereford** [comment]
I have spun up an EC2 machine with RHEL to investigate the compatibility of podman instead of docker, as that is what is distributed with RHEL. I am doing it on this throw-away instance because I am not interested in polluting our production machines with it if we don't want to use it.

**Comment by frankhereford** [comment]
I have terminated my throw-away RHEL machine in EC2 that i used to test out and learn how to wrangle RHEL. Very helpful.
