### ISSUE TITLE
[Meeting] Parking Enterprise Service Request process

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15849]
## Description 

Meeting with SMS to talk about 311 Service Request improvements.

[Recording](https://cityofaustin-my.sharepoint.com/:v:/r/personal/diana_martin_austintexas_gov/Documents/Recordings/Parking%20Enterprise%20Service%20Request%20process-20240215_083613-Meeting%20Recording.mp4?csf=1&web=1&e=FPN3nN&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

**Comment by patrickm02L** [comment]
In debrief Diana and I talked about different options for SR improvements and 311 integration. 
[miroboard](https://miro.com/app/board/o9J_l4LSuvE=/)

<img width="740" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzVoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--225b34309e54c689000215d8fc504a72bfb86a8e/Screen%20Shot%202024-02-15%20at%2011.05.42%20AM.png" alt="Screen Shot 2024-02-15 at 11.05.42 AM.png" />

**Comment by patrickm02L** [comment]
# 2/19/24

## Action Items
- [ ] Update workflow process flows for parking enforcement and shared mobility integration
- [ ] Create agenda to present integration options to parking enforcement team
- [ ] Add integration options brainstorming notes to meeting issue for parking enforcement discussion
- [ ] Schedule follow-up meeting with parking enforcement for Thursday 3/29 at 8:30am

**Comment by dianamartin** [comment]
# 2/20/24
@patrickm02L I updated the workflows in [Miro](https://miro.com/app/board/o9J_l4LSuvE=/), can you review them to make sure they look okay to show the stakeholders please. 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/646978b7-b749-4c30-a5c3-7cbc404d84ee)

**Comment by patrickm02L** [comment]
@dianamartin added my comments to the miroboard. Thanks for knocking this out!

**Comment by patrickm02L** [comment]
# 2/29/24
Follow up [meeting](https://docs.google.com/document/d/1yfS9VIdkw3d4zSTHk1rWNRqqEJtX6t1Y--d_tUcwLd0/edit?usp=sharing) with Andrea, Michael K, Michael M, Shavyvonne, Diana and Patrick. 

## Note
- Resulted in epic to streamline micromobility serivce requests #16072
- Future meeting agendas will be kept in DTS drive
