### ISSUE TITLE
[Bug] Handle activity log entry when a project's parent project is removed

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15855]
## Steps to reproduce
1. Add a subproject to a project
2. Remove the subproject from the project
3. Look at the subproject's activity log 👀 

<img width="1438" alt="Screenshot 2024-02-15 at 1 58 49 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/9ba0b2df-9c8b-4467-99af-4626631ff6cc">

**Comment by tillyw** [comment]
@johnclary @chiaberry how do we want to handle this? Should it say something like 'Removed parent project with id 1997' or just 'Removed parent project' ? Should we render the name of the parent project in both cases?

**Comment by chiaberry** [comment]
I like the idea of showing the name of the parent project instead of the id when someone adds or removes a parent project

Changed parent project to **AMD Signal Work**
Removed parent project **AMD Signal Work**

**Comment by johnclary** [comment]
just assuming you'd have to fuss with fetching the parent project name, i think it'd be fine to just show the ID. with bonus points if it's a hyperlink? 😇
