### ISSUE TITLE
[Enhancement] Upgrade to react-map-gl v7 and prevent scroll capture on the crash and location maps

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15867]
It can be challenging to scroll the Crash and Location details pages, because the map captures the page scrolling by zooming the map.

It should be possible to configure the maps to require a `cmd` to zoom. 

See the Moped project summary map for reference (although Moped uses a different version of react-map-gl):
<img width="874" alt="Screenshot 2024-02-15 at 9 56 54 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/5f436a33-8a25-4b72-a72a-e4b7c89c3ae2">

**Comment by mddilley** [comment]
@johnclary It looks like we would have to upgrade react-map-gl to v7.0 like we have in Moped Editor to support add this. https://github.com/visgl/react-map-gl/issues/1640

What do you think about turning this issue into an upgrade one? We have three maps: `LocationMap`, `CrashMap`, and `CrashEditCoordsMap`. Could create a path to fixing the buggy geocoder while we are at it. https://github.com/cityofaustin/atd-vz-data/pull/1337#issuecomment-1899288057

**Comment by johnclary** [comment]
> What do you think about turning this issue into an upgrade one? 

💯 thanks @mddilley i will update this issue. will be good to update a few `class` components as well 🚀
