### ISSUE TITLE
Transition Moped product management

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15865]
### Documentation
- [x] How to: user communications ([Gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/~/changes/283/product-management/user-communication))
- [x] How to: user analytics ([Gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/~/changes/283/product-management/user-analytics))
- [x] Release process ([Gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/product-management/release-process))
- [x] Update QA testing docs 😬 
- [ ] Clean up WIP data dictionary
- [ ] Share AGOL view link w/ Amenity
- Would be nice to catch up on some dev documentation
  - DB triggers for council districts
  - DB triggers for audit fields
  -  ArcGIS Online integration

### Issue scoping and roadmap
- Review where we're at
- Sequence near-term issues

### Misc
- Reschedule meetings: MUG and release parties

**Comment by amenity** [comment]
@johnclary @chiaberry how are you feeling about this one? Anything to add? close?

**Comment by chiaberry** [comment]
I feel like we can close it! In fact, I will close it with this comment
