### ISSUE TITLE
Add `Pipeline` (status) field to Project Evaluations

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15878]
To prioritize current projects needing Project Evaluations, we would like to add the `Pipeline` field from the [ATD Data Tech Services Issues](https://datahub.austintexas.gov/Transportation-and-Mobility/ATD-Data-Tech-Services-Issues/rzwg-fyv8/about_data). 

Modify [script](https://github.com/cityofaustin/atd-service-bot/blob/production/gh_index_issues_to_dts_portal.py) to pull from Socrata or use the Zenhub API directly. 

Data source options:
   - [ATD Data Tech Services Issues](https://datahub.austintexas.gov/Transportation-and-Mobility/ATD-Data-Tech-Services-Issues/rzwg-fyv8/about_data)
   - Github atd-data-tech repo via the Zenhub API, a la [the ATD Service Bot](https://github.com/cityofaustin/atd-service-bot/blob/production/issues_to_socrata.py)

Target: [Project Evaluations](https://atd.knack.com/dts#project-evaluation/) page

**Comment by ChristinaTremel** [comment]
### Notes 
- Karo added `Pipeline` field to the Project Evaluations object

**Comment by amenity** [comment]
Per @johnclary in Dev + Product Sync today, the script that pulls index issues into the DTS Portal doesn't use the Zenhub API (needed to access "Pipeline" data) nor the Socrata dataset that has that field in it.

**Comment by johnclary** [comment]
[This](https://github.com/cityofaustin/atd-service-bot/blob/production/gh_index_issues_to_dts_portal.py) is the script in question. It will need to be updated to interact with the Zenhub API (or Socrata) to get pipeline info. 

[This script](https://github.com/cityofaustin/atd-service-bot/blob/production/issues_to_socrata.py) does interact with the Zenhub API, for example :)

**Comment by amenity** [comment]
(Sorry for all the Zenhub/Github noise! I am breaking up this issue so that each builder team's respective points are separate.)

**Comment by frankhereford** [comment]
👋 @ChristinaTremel & @KaroEngstrom 

I think I have [the changes](https://github.com/cityofaustin/atd-service-bot/blob/a4e48fbcfe24eae9a8161b5347356c25a961963c/gh_index_issues_to_dts_portal.py) to this ETL ready to go so it will populate the knack app's list of issues with their pipeline status.

I have run into a snag, and I wanted to check with you all and see what you thought. There is the field that Karo added recently to the production Knack app called [Pipeline](https://knack-explorer.austinmobility.io/595d00ebd315cc4cb98daff4/fields/field_649), but I don't seem able to update it via the knack API. Does it need to be added to this "page" as well?

![image](https://github.com/cityofaustin/atd-data-tech/assets/3653206/d5ed5f16-6fa4-416d-a399-b9bc0f11708f)

I appreciate y'all's help -- I'll catch up with you on slack tomorrow. Thanks!!

**Comment by KaroEngstrom** [comment]
## Tue 2/27/24
- adding `pipeline` to the API table in DT PROD as well
