### ISSUE TITLE
IT Support: New Hire for SBO will need New laptop

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#15879]
TOWNVIEW
## Device & User Information (first name and last initial, no last names)
: Greg G
## What's the problem?
Ryan,

Will you please submit a NERF to establish Greg’s accounts. Sooner the better please. Make sure to enter the PCN and EEID on the ticket to avoid UKG nightmares. 

Also, make sure you get ahold of Matt to get a computer set up. 

New Hire for SBO
Start Date 26th

**Comment by Matthew-M-TPW** [comment]
@Vaishnav1397 Please prep a computer for new hire Starting March 26th

**Comment by Vaishnav1397** [comment]
Prepped a laptop and kept it ready.

**Comment by Matthew-M-TPW** [comment]
@Vaishnav1397 
The User will pick the laptop up from St. Elmo 
Time unknown 

"We're going to do a road trip on Monday and hit all the service centers, so I was thinking we can pick up his gear while we're doing that, if that works for you."

**Comment by Vaishnav1397** [comment]
Okay! thank you for the update.

**Comment by Vaishnav1397** [comment]
As discussed with Matt, user mentioned he is going to arrive by 2pm.

**Comment by Matthew-M-TPW** [comment]
User picked latop up
