### ISSUE TITLE
IT Support: [Outlook Issues]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#15873]
St Elmo
## Device & User Information (first name and last initial, no last names)
Laptop & Samuel, W <! -- Samuel West-->
## What's the problem?
User cannot load the outlook for a while and tried multiple times, but still seems to be the same. User wanted to check over it at time when he is login early in the morning.

**Comment by Vaishnav1397** [comment]
@Matthew-M-TPW Can you please relook into the issue?

**Comment by Matthew-M-TPW** [comment]
Scheduled time with user on Tuesday to look at it

**Comment by Vaishnav1397** [comment]
Checked with user even on the laptop issue which he is been facing. @Matthew-M-TPW can you please hook up his system sometime next week.

**Comment by Vaishnav1397** [comment]
User moved over to other department and later we might be looking over if still the issue persists.
