### ISSUE TITLE
[TCP Upgrade] Add Submission-Level Messaging and Include Attachments

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#15887]
## Fri 2/16/24
- these updates were requested during the 1st review with stakeholders 
- [x] ON DECK --  **Add Submission-level Messaging ONLY FOR THE REVIEWER**  -- @KaroEngstrom for week of 2/20/24
      - Ability to send message from Submissions Details
      - Shows a table in this view
      - Associates those messages with a specific Submission
      - All messages will show on Project Details page

     **TASKS** 
     - [x] Add connections from Messages table to the Submissions in both TCP and CSWZ
     - [ ] ~~Create Send Messages button~~ 
          - Add Anytime MENU for Reviewers: include Add Attachment and Send Message 
               - [x] Turn AFTER REVIEW Menu into an Anytime MENU - TCP
                    - [x]  Turn AFTER REVIEW Menu into an Anytime MENU - CSWZ
               - [x] Add Send Message button + [page](https://builder.knack.com/atd/row/pages/scene_425/views/view_956/form?confirmNewView=view_956) and include association to parent project in record rules - TCP
          ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/5bf90965-11b1-4238-9712-ce8ecfa9c9d0)
                    - [x]  Add Send Message button + page and include association to parent project in record rules - CSWZ
           ![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/e66b106f-4303-4a96-827b-d5ded04aabbf)
          - Remove Add Attachment from Status-Specific MENUs  
               - [x] TCP 
               - [x] CSWZ 
          - **Ask about Customer Side Send later; the customer could reference a specific cycle** 
     - Add Messages table on the Submission Details page and filter down to that Submission's messages
          - [x] [TCP ](https://builder.knack.com/atd/row/pages/scene_26/views/view_959/table)
          - [x] [CSWZ](https://builder.knack.com/atd/row/pages/scene_251/views/view_958/table) 

- [ ] ON HOLD -- **Add Attachment field to Messages** | 🚨 Return to this piece after Messaging/ Customer Actions are sorted out
     - Anytime attachments library on the project was discussed
     - Option: a single attachment field with workaround to attach a zip file if multiple need to be sent
          - Would the requirement to enable messaging that not bound to a submission; can be sent any time

**Comment by KaroEngstrom** [comment]
### Add Message Inbox to Reviewer Taskboard

**Comment by ChrispinP** [comment]
Message Inbox added to the bottom of the Task Board viewable to Admin only right now. An inline Modal allows a user to see all Message Data and then navigate to Case or Submission data. Not sure but we may also want to link them to the review page if it exists.

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/19530868-fe31-492c-912c-6aad17dd378b)
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/8a0a5454-8cd0-44ea-89b4-aefcd28efe74)

**Comment by TracyLinder** [comment]
The initial build is done.

**Comment by TracyLinder** [comment]
Note that we did not build attachment features for messaging. Attachments should be added directly to the case.
