### ISSUE TITLE
Project: Coordinate Software Implementation 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15885]
We are implementing a new software called COORDINATE. This will be used by both internal and external entities to coordinate activities in the right-of-way.

## Background 

In October 2023, TPW purchased a new software called [Coordinate](https://gocoordinate.com/) to bridge the current gaps we face in managing and coordinating activities in the Right of Way. This application will serve as a comprehensive repository, gathering crucial data on planned roadway closures and current road conditions. It will streamline how Right of Way Management (ROW) and the Office of Special Events (OSE) coordinate planned activities, offering much-needed communication management tools with robust notification features.

Implementing this software will be a significant project for TPW; we anticipate it will take 10-12 months to prepare the initial release. Our core project team currently consists of members from ROW, OSE and DTS. We are still identifying project stakeholders who should be consulted as part of the implementation plan, as well as those who should be advised of project updates. If you or someone you know should be included, please reach out to Tracy.Linder@austintexas.gov.

![Screenshot 2024-05-14 at 4 28 03 PM Cropped](https://github.com/cityofaustin/atd-data-tech/assets/49930868/0a0e9a74-f631-4dba-a39d-4d3b7d3e4450)

---
This Github issue represents a project of Transportation Public Work's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
@TracyLinder - I realized we have two project indices for this project. Retiring this one in favor of #14585 since that's the epic you're using for work.
