### ISSUE TITLE
IT Support: Training on use of Epics

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#15882]
## Device & User Information (first name and last initial, no last names)
DTS Tech Services team

## What's the problem?
Diana we need training on the use of Epics

## What did you do to resolve the issue
- Scheduled a Github refresher covering the topic of Epics on 2/23/24

**Comment by Matthew-M-TPW** [comment]
JB wants to create an epic for Monitor Deployment,

**Comment by dianamartin** [comment]
# 2/23/2024
I had a meeting to discuss the ways the Tech Services team can create Epics in GitHub for their type of work. 

## Example of EPIC usage
### One Epic, 2 Issues - (Ongoing Tasks) 
- EPICS - IT Support: Reimaging computers
  - ISSUE - WEEKLY 2/12-2/16 - 40
  - ISSUE - WEEKLY 2/19-2/23 - 15

### One Epic, 2 Issues - (Large Projects like Ex. Conference Room Improvements) 
- (Large Projects) EPICS - Conference Upgrade Project
  - ISSUE - Meeting with stakeholders
  - ISSUE - Meeting with vendor to assess room
  - ISSUE - Set up meeting with vendor

### One Epic, Epic inside of Epic, 2 Issues - (Large Efforts Ex. Annual TPW PC Refreshes) 
Broken down by TPW location
- (Large Initiative) EPICS - FY 2024 PC refresh
  - (Large Projects) EPICS - Cameron
    - ISSUE - completed 10 PC refresh
    - ISSUE - completed 10 PC refresh
  - (Large Projects) EPICS - BOP
    - ISSUE - completed 10 PC refresh
    - ISSUE - completed 10 PC refresh
  - (Large Projects) EPICS - Ben White
    - ISSUE - completed 10 PC refresh
    - ISSUE - completed 10 PC refresh
### One Epic, Epic inside Epic, 1 Issues - (Ex. New Hire Onboarding 
- (Large Projects) EPICS - New hire
  - ISSUE - So and So is getting hired on Monday 
    - TPW Supervisor submitted a ticket
    - Can create this as an Epic
      - ISSUE - NEW HIRE ONBOARDING CHECKLIST (Create New Issue and add Epic to it)
