### ISSUE TITLE
Research PWD AMANDA Fees (TL) (RB)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#15905]
## Pull fee specific data so we can learn about these fees and manage them appropriately. 

**Parameters:**
- Fee code in (see screenshot) 
- Fee has been billed since 10/1/2020

**Data to extract:**
- Folder type
- Folder RSN
- Bill#
- Payment status
- Bill created date

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/4b7b5aed-7f64-441f-bbd8-a0f0b9e78008)

**Comment by TracyLinder** [comment]
@Nadin-Nader this is ready to be pulled as tech debt

**Comment by rajeshlaunch** [comment]
@Nadin-Nader If you have access to PROD DB, please execute the below query and attach the results, if I need to reach out to someone, kindly let me know the contact and I will coordinate.

SELECT
FOLDERTYPE,
account.FOLDERRSN , 
account.BILLNUMBER , 
PAIDINFULLFLAG , 
DATEGENERATED  
FROM ACCOUNTBILL account
INNER JOIN FOLDER f 
ON f.FOLDERRSN  = ACCOUNT.FOLDERRSN 
INNER JOIN ACCOUNTBILLFEE ABF
ON ABF.BILLNUMBER  = ACCOUNT.BILLNUMBER
AND abf.FEECODE IN (51441, 51442, 51443, 51444)
WHERE DATEGENERATED >= TO_DATE('10/1/2020','mm/dd/yyyy')
ORDER BY DATEGENERATED;

**Comment by rajeshlaunch** [comment]
[Data.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUpmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c260c9c805afd57c63e97dcaf8b1803a0aa4400/Data.xlsx)

@TracyLinder Please find attached the spreadsheet with the data requested in this ticket. Kindly let me know the next steps on this card.

**Comment by TracyLinder** [comment]
@rajeshlaunch can you please add 2 columns to the data output?
- Fee Name
- Fee code

**Comment by rajeshlaunch** [comment]
@TracyLinder Please find the spreadsheet with additional columns added. 

[Data - Updated.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejF6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac81961f95a6f116fdac63086fe6b51f39aee124/Data%20-%20Updated.xlsx)

**Comment by TracyLinder** [comment]
This can be closed since the research is complete.
