### ISSUE TITLE
Create new `Arterial Management Inventory Items` Socrata Dataset

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15911]
## Background
- AMD has ben trying to use the [Arterial Management Materials Warehouse Inventory Socrata Dataset](https://datahub.austintexas.gov/Transportation-and-Mobility/Arterial-Management-Materials-Warehouse-Inventory/hcaw-evi2) to build an inventory dashboard for Cesar and team
   - This dataset inserts new rows daily so Ronnie can refer back to inventory counts
   - Building the dashboard based on this dataset with ~197k records, it was complicated and Cesar wasn't finding it useful. 

## Request
- Requesting a new, internal Inventory Items Socrata Dataset with the same source as the current dataset, but just updating the dataset on a daily basis instead of inserting new records daily
   - API Source: https://builder.knack.com/atd/amd/pages/scene_1170
   - New Target Name: `Arterial Management Inventory Items`

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/13587#issuecomment-1698080796_

**Comment by ChristinaTremel** [comment]
### Notes from Sprint Planning
- Discussed this during apps Sprint Planning and we think we could have a simpler solution.
- Could we create a derived view based on grouping by record ID and showing data from the most current Published Date - only want the `284` records

**Comment by Charlie-Henry** [comment]
Think I figured the query out @ChristinaTremel @KaroEngstrom 
✨ https://data.austintexas.gov/Transportation-and-Mobility/Current-Arterial-Management-Materials-Warehouse-In/etm9-t3cx/about_data 💖

**Comment by KaroEngstrom** [comment]
I think this looks great and I can see it's already published so easy for her to pull into Power BI. Do we need to keep the draft?

**Comment by ChristinaTremel** [comment]
Yesss, it looks great! 🚀  I'll send this to Allyson and MJ!

**Comment by ChristinaTremel** [comment]
2/21 messaged Allyson and MJ:
> Heeey! I brought up creating the new dataset with the team and they found an even easier way of doing it 🎉
 https://data.austintexas.gov/Transportation-and-Mobility/Current-Arterial-Management-Materials-Warehouse-In/etm9-t3cx/about_data
