### ISSUE TITLE
Feature: SSPR End of Year Printing Page

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15930]
### Background
- Needs copy of SSPR in each persons personnel file
- Just interested in year end, everything else can live in Knack

### Build Requirements:
- Page that filters by FY
- Modal pop-up of SSPR form that mirrors old SSPR form
   - Keyes sent old form to Diana
   - Information on the SSPR should be filtered to End of Year
- Field to track progress of saving SSPRs at the end of the year

**Comment by dianamartin** [comment]
# 2/22/2024
## Background
- Needs copy of SSPR in each persons personnel file
- Just interested in year end, everything else can live in Knack

## Build Requirements:
- Keyes need to be able to access the page (set up designated page for this task?)
  - `HR Admin` & `HR Staff`
- Page that filters by FY
- Modal pop-up of SSPR form that mirrors old SSPR form
- Keyes sent old form to Diana
- Information on the SSPR should be filtered to End of Year
- Field to track progress of saving SSPRs at the end of the year

**Comment by ChristinaTremel** [comment]
### Notes 2/22
- Copied `SSPR Details` page to `Year-End Reporting Details` page
   - [x] Remove multiple filters for priorities
   - [x] Only set filter to Type is `Year-End` for priorities
   - [x] Remove multiple filters for COA Competencies 
   - [x] Only set filter to Type is `Year-End` for COA Competencies
   - [x] Hide Supporting Documents if COUNT is less than 1
   - [x] Configure to allow printing

**Comment by dianamartin** [comment]
# 2/23/24
This is ready to show stakeholders

**Comment by ChristinaTremel** [comment]
### Sprint Review 2/26
- Showed Jennifer and she asked if we could add `Mid Year competencies` and `Mid Year Priorities` and that seems to work. 
- [ ] Submit a Knack bug report about the formatting between priorities and competencies

**Comment by ChristinaTremel** [comment]
I submitted a bug report to Knack on 3/10 and when I checked in last month they sent a message 4/18: 
> We do not have an update yet, as other issues have taken priority over this. This is not to say that this is not important, but our teams have worked on larger impact improvements.
We have requested an update on this request. Once we have a fix we will let you know!

@dianamartin do you think we should try rebuilding the table that's causing the print pages to look weird?

**Comment by dianamartin** [comment]
# 5/24/24
- I think we could ask Susanne if we could look at it bc she's been doing page breaks in MSP app.

**Comment by stephaniemoorer** [comment]
7/15/24
Discussed in HR Sprint Review stakeholders agreed this is complete
