### ISSUE TITLE
Enhancement: Update `Days Vacant` calculation

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#15931]
### Context
- In the TPW HiRe App, the `Days Vacant` calculation continues even when the position has been filled
- HR will be backfilling “Vacant Date” and the “Effective Start Date” fields so the `Days Vacant` is up to date

### To-Do
- [ ] Update calculation: `Days Vacant` should stop once the `Effective Start Date` field is populated

**Comment by dianamartin** [comment]
# 2/26/24
Christina and I worked on this for a little bit and had to take meetings and then came back to it. We figured it out finally: 
`{Effective Start Date} == 0 ? {Current Date} - {Vacant Date} :{Effective Start Date} - {Vacant Date}`

## Result
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/569d32e8-4ba1-4c70-8ecb-950a4ce692c8)
