### ISSUE TITLE
[Bug] Deleting a current phase does not render correctly in the activity log

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#15932]
As seen in project [534](https://mobility.austin.gov/moped/projects/534?tab=activity_log), if you delete a phase that is the current phase, the activity log gets a little confused:

<img width="1406" alt="Screenshot 2024-02-21 at 9 52 30 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/8f17eba2-a079-4aa4-b58b-a6be0fe195c8">

Compare that ☝️ to when we delete a non-current phase. This is what we want 👇

<img width="1405" alt="Screenshot 2024-02-21 at 9 56 01 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/3100f72a-094f-4c96-af8f-bebbc2d5d738">

**Comment by johnclary** [comment]
@chiaberry @amenity FYI. i added this to our snackoo epic.

**Comment by tillyw** [comment]
closed with https://github.com/cityofaustin/atd-moped/pull/1287
