### ISSUE TITLE
[Feature] Ability to archive a Dash item so it doesn't appear on the UI

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#15941]
We need a way (button or dropdown?) to archive a dashboard in [Knack](https://atd.knack.com/test--07-sep-2023--data-and-technology-services-portal#tpw-data-visualizations/) so that it’s no longer visible on the [UI](https://deploy-preview-415--austin-transportation.netlify.app/).

We don't want people to be able to delete dashboards entirely, but we want a place to put Dash items that could be a test, outdated, no longer relevant, etc. Archiving an item would remove it from the Dash UI.

**Comment by chiaberry** [comment]
@katelunceford this is updated in the test dts knack app!

**Comment by katelunceford** [comment]
@chia this functions just as I asked. Thank you!
