### ISSUE TITLE
Create Amenity Airflow account

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#15945]
I'd like to be able to, on demand, run the script that rebuilds Austinmobility.io with fresh content from the DTS Portal (project evaluation scores) and the [ATD Data & Tech Services Issues dataset](https://data.austintexas.gov/Transportation-and-Mobility/ATD-Data-Tech-Services-Issues/rzwg-fyv8/about_data).

The Product Team is planning to do an 🪅 Index Bash 🪅 to clean all the cruft and empty space out of our project and product indices, so this will help us check our changes on the website as we work.

**Comment by chiaberry** [comment]
created a User account for Amenity, and shared password with her

Here is the service bot to dts portal dag: 
https://airflow.austinmobility.io/dags/atd_service_bot_issues_to_dts_portal_production/grid

**Comment by amenity** [comment]
I added it to my ATD 1P account and verified it works. Thanks, @chiaberry !
