### ISSUE TITLE
Project: Living Streets 2.0

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#15950]
When Healthy Streets and Play Streets were introduced to the City’s [Living Streets Program](https://www.austintexas.gov/LivingStreets) in the fall of 2023, we worked with the Smart Mobility Office to to extend the [Smart Mobility Portal](https://austinmobility.io/products/13810) with a [public-facing application](https://atd.knack.com/smart-mobility#living-streets-getting-started/) for the new activations. The team also built an internal interface for SMO staff to review, vet, and respond to expressions of interest and applications.

## Background

During the COVID-19 pandemic, the necessity for outdoor public spaces where people could safely gather and socialize became increasingly evident. Austin responded by initiating pilot programs such as the Healthy Streets Initiative and Shop The Block, which successfully transformed public spaces for communal activities. These initiatives are now transitioning into permanent programs to continue building community and enhancing the quality of life through innovative use of public spaces.

Based on ​Resolution no. 20211021-027

## Scope & Deliverables

The resolution focuses on revamping Austin's existing Neighborhood Block Party Program with the goal of making it more accessible and equitable for all residents. In addition to this, the City Council plans to develop new community-centric programs, namely Play Streets and Resident-Led Healthy Streets, to further activate residential areas for communal use. To facilitate easy access to these initiatives, a single, public-facing webpage called "Living Streets" will be created, serving as a centralized hub for information and resources related to these street programs.

## Desired Outcomes

A publicly available "Living Streets" webpage will serve as a one-stop resource for residents to learn about and access all available street programs. To streamline the application process for these programs, an internal Knack platform will be developed to intake resident applications, allowing staff to efficiently review, vet, and respond to them.

## Timebox

February 2024-July 2024
November 1st launch

## Concepts and references

- Living Streets Intro [Powerpoint](https://cityofaustin.sharepoint.com/:p:/s/ATDLivingStreetsProgram/Ebfa0Actxb5BtfOq2E3mHuIB75oqzSTLnnHP3b_02nWfEg)
- City of Austin Living Streets [website](https://www.austintexas.gov/LivingStreets)
- Council Resolution [20211021-027](https://services.austintexas.gov/edims/document.cfm?id=370647)

## Request details
- Executive sponsor: Matthew M.
- Date: July 2024

![1140x665-walk-austin-slow-street](https://github.com/cityofaustin/atd-data-tech/assets/5566727/932ce003-a5bf-4cea-981e-cb428eae14f9)

📷 [image reference](https://www.aarp.org/livable-communities/getting-around/info-2023/healthy-streets-austin-texas.html)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by patrickm02L** [comment]
# 8/28/24
All of the Issues have been completed. Any outstanding Issues have been moved to [Living Streets 3.0](https://github.com/cityofaustin/atd-data-tech/issues/18315)

**Comment by KaroEngstrom** [comment]
[heart]         Engstrom, Karo reacted to your message:
________________________________
