### ISSUE TITLE
Labor Reporting Issues EzMaxMobile - Ronnie H.

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#15959]
Ronnie called in reporting an issues with their labor reporting when inputting time. When they are entering the work time, it is reflecting as an much earlier time on Maximo than what was entered in EZMax, but it is showing as normal within EZMax.

Issue has occurred on the following WOs:
24-169881
24-169887
24-169890

**Comment by adry-martinez** [comment]
@ReneVarg25 please research this issue as soon as possible. This would've been a good topic to add to our bi-weekly discussion with CTM. Moving forward, please add any issues that may require CTM's support to #15723

**Comment by ReneVarg25** [comment]
### 2/27/2024
Reached out to CTM for assistance and possible causes.
Reached out to user if issue is still occurring?

**Comment by ReneVarg25** [comment]
### 2/27/2024
CTM confirmed that the time zone for the user had been blank due to the username conversion. Time zone has been corrected. Notified user, waiting for confirmation that issue has been resolved.
