### ISSUE TITLE
IT Support: End User PC is do for a refresh over a 3 year 10 month mark(Anthony A)

### ISSUE THREAD

**Issue by JBStrange** [cityofaustin/atd-data-tech#15974]
End User showed up with alot of issues from there PC. Looking at dell website notice that it was time for a refresh on the laptop that EU currently had.

**Comment by scottreedy** [comment]
This computer was replaced on 01/23/2024
Latitude 5440 | 61DLQV3 | TPW-61DLQV3-N1 | DELL83509 | 01/23/2024




</body>
</html>
