### ISSUE TITLE
IT Support: Assist with screen views on SharePoint sites

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#15971]
BOP

## Device & User Information (first name and last initial, no last names)
Karla T
## What's the problem?

I could use your help to right size my computer screen views on some Sharepoint sites.  My problem is when I open the Admin Sharepoint site, the images are too large and I cant reduce the size, nor scroll down.  Lemme know when you can help.
 
Thanks, Karla

**Comment by Matthew-M-TPW** [comment]
Reached out to user and will be there later today

**Comment by dianamartin** [comment]
@Matthew-M-TPW you should ask Karo to see if this is a Sharepoint glitch or a hardware one.

**Comment by KaroEngstrom** [comment]
@Matthew-M-TPW - If this is about the preview mode of PDFs will not allow zoom or scroll.

To be able to scroll or zoom, the user can: 
- refresh the screen where PDF is being previewed, **or** 
- from the folder view, click the three dots options and Open in Browser

**Comment by Matthew-M-TPW** [comment]
JB ran updates on users computer. It needed some updates.

Once I arrived at BOP me and JB sat down with the user

I pressed Control and scrolled to zoom out 

Set up users MFA since I saw it was not working
