### ISSUE TITLE
IT Support: Anthony A needing a phone add to his workstation when in the office.

### ISSUE THREAD

**Issue by JBStrange** [cityofaustin/atd-data-tech#15973]
End User ask for a Avaya phone to be setup for when he is in the office.

**Comment by scottreedy** [comment]
Your Request REQ0176668 has been opened. If you are the Requested For, you can view status from My Tickets on the [COA IT Service Portal]
 
Submitted By: Scott Reedy
Requested For: Manuel Arriola
