### ISSUE TITLE
TCP Upgrade Builder Minor Tasks 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#15993]
#### Karo

Customer
- [x] ACTION - On the customer side, create a Rich Text that explain the lack of functionality in this status - @KaroEngstrom (can be placeholder text for now)
     -  ~~ACTION - Add second menu for Initial Submission that is shown with Submission = 0 - add to both TCP and CSWZ~~ Same as above
- [x] ACTION - Hide New Submission menus when there’s an open submission record - @KaroEngstrom 
     - [x] Page rules for No New Submission rich text view on Manage TCP and Manage CSWZ (Customer Side)
     - [x] Talk to @ChrispinP - should we do this using TCP or Submission Status, or possibly TCP State? 

Reviewer
- [x] ACTION - Update pop-up on Submission table Edit Due Date and Reviewer on CSWZ to reflect TCP model ⭐ - @KaroEngstrom 
- [x] Build display rules for Reviewer side buttons menus on the Submission Details pages - @KaroEngstrom 
     - [x] TCP Submission Details 
     - [x] CSWZ Submission Details  
- [x] Consolidate Add New Submission button to Reviewer Menu on CSWZ Case Details page - @KaroEngstrom 

#### Chrispin
- [x] Add Messages table headers: TCP Project level and Submission level; CSWZ Case level and Submission level  @ChrispinP 
- [x] ACTION - Turn back links into buttons on relevant pages @ChrispinP 
- [x] Make Edit Project button large to guide applicant to the next steps after project creation

#### Other
- [x] ACTION - Set up pending approval page to show accounts in Pending Approval (another option would be automatic approval of new accounts) - We will automatically approve New Accounts
- [x] ACTION - Figure out a temporary display name for unsubmitted projects/cases (Confirm for CSWZ)
- [x] ACTION - Add ability to create submitter (ROW_contact) in Edit Project 🗓️ later
- [x] ACTION - Add ability to create submitter (ROW_contact) in Account (Profile) 🗓️ later
- [x] ACTION - Project Details TCP not showing Designs Sheets and Attachments # s  🗓️ later
- [x] ACTION - When creating attachments, add record rules for setting Archive Status - do this on TCP and CSWZ (once the proper status has been figured out)  🗓️ later
- [x] Create validation for New Submission Cycle when an open Submission Cycle already exists 
    - [x] TCP Create New Submission form
    - [x] CSWZ Create New Submission form
- [x] Rebuild Edit TCP form
- [x] Update CSWZ Request Menu
- [x] Setup Page Rules for Knack Tester role to only see new views for demo - added Knack Admin to ROW Tester roles to allow showing in-progress views
     - [x] Traffic Control Plans landing page - I only hid the old grid; did we want to hide Announcements and the current menu? 
     - [x] TCP Details
     - [x] CSWZ Requests Landing page - kept Announcements and current menu
     - [x] CSWZ Details
     - [x] Checked the above pages

**Comment by ChrispinP** [comment]
Completed some of the tasks above plus a few other related tasks from our Sprint Review feedback.

- Updated the Default Display name for unsubmitted TCP Cases
- New Submission Cycles will auto-submit and added help text
- Cleaned up some of the Headers & spacing for Customer pages
- Added the ability to create new Submitters/Contact Users from the Account page and from both of the Edit Project forms
- Added missing fields to Edit TCP form and updated Display Rule for Funding fields

**Comment by ChrispinP** [comment]
Updated record rules for adding attachments. Also fixed the Sum and Count fields for Attachments and Design Sheets. Added the Archive Status filter for all Sum & Count fields.

**Comment by ChrispinP** [comment]
Validation / Page Rules added for Creating Submission Cycles both for Staff and Customer sides

This completes all minor tasks above, closing.
