### ISSUE TITLE
Update Report List - SBO Tree Group

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#15992]
Move the following reports from scheduled reports into the "Reports" section of the start center for the Tree Group:
- [x] SBO 311 Dash Board
- [x] SBO 311 Open Requests
- [x] SBO 311 Weekly Data and Open Requests

Remove from the following report:
- [x] SBO 311 Standardization Work - Resolving CSRs in 311 System

**Comment by ReneVarg25** [comment]
### 2/27/2024
Removed Tree Group from the mailing lists

**Comment by ReneVarg25** [comment]
### 2/29/2024
Added SBO 311 Dash Board, SBO 311 Open Requests, and SBO 311 Weekly Data and Open Requests to report lists in Tree Group Start Center.

**Comment by adry-martinez** [comment]
### Mar. 1, 2024

Forestry Start Center updated with requested reports.
Added to #15804

**Comment by adry-martinez** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/991d2d80-8a9b-4d71-82dd-f1620ddf5ddc)
