### ISSUE TITLE
Update parameters in SBO 311 CSRs Overdue Report

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16008]
Requesting CTM to update the report to reflect ONLY work order numbers (excluding CSRs)

Add a new default result set to parameter of SBO 311 CSRs Overdue Report to:
a.	AGE, 
b.	WONUM, 
c.	WODESCRIPTION, 
d.	MAP_PAGE, 
e.	WOSTATUS, 
f.	WOOWNER, 
g.	WOSUPERVISOR, 
h.	WOSUPERINTENDENT, 
i.	WOWORKGROUP, 
j.	WLDESCRIPTION

**Comment by adry-martinez** [comment]
### Feb. 24, 2024

updated in PROD. need to verify.

**Comment by adry-martinez** [comment]
### Feb. 26, 2024

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/bd45e6e3-c660-47ae-8ddf-171c611c4989)

Requested CTM to walk me through on updating the report to reflect the Problem Code and remove SR #. 

Parameters have been added:

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/d0408b2e-e090-46ee-89f7-de06fd350259)

**Comment by adry-martinez** [comment]
### Mar. 1, 2024
Need to follow-up with Nick re: the problem code column not displaying and remove the SR# column from the report as well.

**Comment by ReneVarg25** [comment]
### 3/11/2024
Nick reported that problem code is showing and SR column has been hidden from table list.

![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/c4f29e47-9d89-4378-b24c-1d2a3801baf2)
