### ISSUE TITLE
[ Power BI] Setup data sources tab in SMD Performance Measures dashboard

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#16009]
Data sources for the data in the Power BI report

Would be good to see the origin of the visuals

**Comment by susannegov** [comment]
Published "About page" tab

https://app.powerbigov.us/groups/b73ea40f-8b44-4aa9-9794-7a87b43e5246/reports/42584f87-6367-46d6-88d4-f4bb62c8db88/ReportSectiond91e06a896586ad10744

![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/c8d9d651-af65-4b68-b21c-4a233b2dc893)

**Comment by katelunceford** [comment]
Susanne said we can close this one :) There's a similar issue #15009
