### ISSUE TITLE
[Enhancement] Persist sidebar visibility between sessions

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#16006]
In the Vision Zero Editor, we should persist the sidebar visibility between a user's session. In other words, the sidebar should remain hidden if you hide it and refresh your page.

We can use `localstorage` for this. We do not need to save this setting anywhere in the db.

**Comment by mddilley** [comment]
@johnclary I took a quick look at this, and the sidebar state is actually controlled by adding/removing the class `sidebar-lg-show` on the main body tag of the app. It is even higher up in the tree than where the React app is rendered. 🤯 Not exactly what I would have predicted.

Here is the code from the library:
https://github.com/coreui/coreui-react/blob/2dc4521d7e43dd5cc48d0ed184dfb03ca765207a/src/AsideToggler.js#L37-L44

I could see us writing some code to observe the adding and removing of this class and tying that into a local storage entry, but I wanted to check in with you on priority here before I moved on.

**Comment by johnclary** [comment]
Oof—thanks for digging into this. my initial reaction is to file this enhancement into the backlog under a "stop using coreui" epic 👿 

but i'm curious to know what size would estimate if you were to pursue the solution suggested?

**Comment by mddilley** [comment]
@johnclary honestly, it is still probably a 2 or 3. Probably could make a pretty general hook to observe css classes/copy what core-ui does to be ready for any other snackoos like this. Let me know if you want to pursue this or not - i'm good either way!

Also, that epic sounds like fun! 😈

**Comment by johnclary** [comment]
if you want to noodle on this—it's all yours!
