### ISSUE TITLE
Add `Parking "X"` option to the D_ATD_SPEC_PNT_PARKING_SUB domain

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16034]
During the Markings QA, we found a new type of marking that was requested to be installed:
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/df8b5823-4fbe-468e-b612-ec68cf46b58b)

- [x] Add `Parking "X"` option to the D_ATD_SPEC_PNT_PARKING_SUB domain in the Specialty Points dataset
   - Code: 9
   - Description: Parking "X"

**Comment by andrewshensky** [comment]
Parking "X" domain has now been added

![image](https://github.com/cityofaustin/atd-data-tech/assets/80716478/285db51d-d8e3-4da8-83f9-67b05266f035)
