### ISSUE TITLE
[Enhancement] Remove traffic signal street segments from viability map

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#16059]
Broken out of #15900 

We got an application from 5707 Marilyn Drive. Marilyn is showing as viable on the map but it shouldn't be, because there is a traffic signal at Marilyn/Northland. Is there a way to exclude all roadway segments that have an endpoint at a signal from the viability map?

**Comment by ATD-ZachB** [comment]
Selected all Viable Streets within a 100ft Buffer of traffic signal intersections.
Published new service with new field TRAFFIC_SIGNALS ( Field contain Yes or No values).
Filtered "TRAFFIC_SIGNALS = Yes" out of the new viable streets feature layer.
