### ISSUE TITLE
Migrate PR copier to airflow

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#16060]
We [have a python script](https://github.com/cityofaustin/atd-data-publishing/blob/production/transportation-data-publishing/finance_admin/pr_copier.py) that checks the Finance & Purchasing Knack app every two minutes for purchase requests that need to be copied.

Here is the old issue to convert it to client side JS
https://github.com/cityofaustin/atd-data-tech/issues/8036

This issue is to move it off of data-deploy and move it to airflow. 
https://github.com/cityofaustin/atd-data-deploy/blob/production/config/scripts.yml#L77

**Comment by Charlie-Henry** [comment]
@chiaberry should I mirgrate the script over to atd-knack-services?

**Comment by chiaberry** [comment]
@Charlie-Henry yeah I think so. I thought maybe it could just run in airflow, but looking at the script again, it needs cleaning up

like I cant find where `records` is defined and yet
https://github.com/cityofaustin/atd-data-publishing/blob/c4f79fc28d6aa437d103e835ead58915d89cb5cf/transportation-data-publishing/finance_admin/pr_copier.py#L182

**Comment by Charlie-Henry** [comment]
deployed !
