### ISSUE TITLE
Create New COS Field Payment Memo

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16064]
### Create a new column in the COS Dataset for Payment Memo

- [x] New field created named Payment Memo
- [x] Add column to COS data view [here](https://atd.knack.com/row#cost-of-service-data/pre-filtered-cos/)
- [x] Add the KNACK Field ID to #15372

**Comment by ChrispinP** [comment]
- Payment Memo: field_1095 added to object
- Field added to both data tables for Finance
- Field added to API View 59

Complete, closing
