### ISSUE TITLE
Testing `SBO Coordination` before stakeholder review

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16067]
### Email Notifications:
- Receiving a Coordination Request as the "Assigned To"
- Receiving updates when a decision has been made as the "Created By"
### Testing Decisions:
- Approved
- Return to Requester
- Assign to Reviewer 
- Deny

**Comment by dianamartin** [comment]
# 2/28/2024
## Testing Components
- [ ] Creation of Request
- [ ] Email notification
- [ ] Status changes
- [ ] Review Decisions 
  - [ ] Approved
  - [ ] Return to Requester
  - [ ] Assign to Reviewer
  - [ ] Deny

**Comment by ChristinaTremel** [comment]
This was completed before the training that was held on 4/30/24!
