### ISSUE TITLE
Rebuild regulation draft builder using the `Regulation Item` object

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16101]
Needed to rebuild the "Draft Builder" to point to the `approved_regulations` object instead of the `canvas_regulations` because we will be completely deleting the `canvas_regulation` object

Completed this rebuild within a series of work sessions with Chrispin.

**Comment by ChristinaTremel** [comment]
# 3/1/24
## Changes Made
- Added `Year` field to the "document_template" object
   - Updated ` Year with 2024 
- Deleted "Retire & Replace" form on the Draft Builder 

## Future Action Items
- [ ] Will need to populate year field for other records
- [ ] On the `Retire` page within the Drafting builder, we will need to replace the "New Retire Line Item #" with the connection to the regulation
- [ ] Delete "Retire & Replace" form on the Task Board


### Stopped work session while rebuilding the "Install". Will start here during the next work session!

**Comment by ChristinaTremel** [comment]
Chrispin and I were able to meet on 2/29, 3/1, 3/4 and 3/7 and completed the rebuild of the "Draft Builder" ✅  Will want to test, but this is ready for review

**Comment by ChrispinP** [comment]
I have completed action items above. All template records should now have years.
