### ISSUE TITLE
Utilities and Structures Data Quality Review - March 2024

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16109]
**SPOCs to notify:**
Mike D.
John P. 
Clay R.

**Comment by ReneVarg25** [comment]
### 3/7/2024
Notified SPOCS of the Following:

Notified Shon J. to update the following to gain credit:
![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/69749e27-59ed-4f10-be86-8ff87853f601)

![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/4bae7e30-d1fb-48fc-9e6a-ed31c627430c)

Notified Michael D. to address the following:
![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/0a608448-289f-4e61-b030-c82d7c45a412)

**Comment by ReneVarg25** [comment]
### 3/12/2024
Notified SPOCS of the following:
![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/8af864e5-c453-4fd8-9941-dc0d391d85e7)

Remainder of report was clear.
