### ISSUE TITLE
Austin 3-1-1 and SBO March 2024

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16111]
3-1-1 Weekly Consolidation Report

**Comment by ReneVarg25** [comment]
### 3/8/2024
118 - Listed as not in Maximo
16 - Duplicate
67 - Wrong log (Notified users, reached out to Diana regarding long standing issues)
18 - Transmission Issues
13 - Closed
4 - Tree Group

**Comment by adry-martinez** [comment]
@ReneVarg25 please update and close if possible.

**Comment by ReneVarg25** [comment]
### 3/11/2024
142 - Not in Maximo
18 - Duplicate
20 - Closed
22 - Log Did Not Transfer
3 - Tree Group InProg
79 - Wrong Log (Addressed/Notified)
