### ISSUE TITLE
Pavement Operations Data Quality Review - March 2024

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16110]
**SPOCs to notify:**
- Andre E.
- Jonathan G.
- John F.
- Stephen R.
- Alfred L.
- Jermaine B.

**Comment by ReneVarg25** [comment]
### 3/7/2024
![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/f158556b-e565-4e50-ab40-1acae4b56103)
See #15689

**Comment by ReneVarg25** [comment]
### 3/14/2024
![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/f05fdfc9-2be7-4b2f-93ab-69dc79128945)

See #15689

**Comment by adry-martinez** [comment]
Data is clean as of April 10, 2024. 
Modifying frequency of quality check from monthly to quarterly. 
Next assessment will be conducted by July 2024.
