### ISSUE TITLE
3-1-1 Data Quality Review - March 2024

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16114]
District Maintenance Quality Report - Pages 1-4
Ensuring maintaining and review of WOs for proper user of Work Logs

**Comment by ReneVarg25** [comment]
### 3/5/2024
![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/b22e7837-ecbc-4373-b398-605cc097b74c)

Notified District Maintenance to resolve work order discrepancies.

![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/923e34f4-bdb8-4dcf-9f02-5b827e82af3c)

![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/6d351970-b2d5-4055-bfcb-73ad16a424f3)

**Comment by ReneVarg25** [comment]
### 3/14/2024

Notified Tree Group of the following:
![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/d87ec3af-b793-48f5-8a72-e715d3505f6d)


![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/708647fc-e207-452e-b818-8150d0f91083)


![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/6224840f-18ed-42bf-aaa7-f147d8c7d91c)

Cannot check for Surface Repairs Without Length and Width Specified as it has been removed from  SBO Surface Repair Completed (Monthly Operational Performance Measures) Report, and has not been added to District Maintenance Data Quality Report yet per Issue #13858
