### ISSUE TITLE
Maximo User Process Discovery - Utilities & Structures/OCE Bridges

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16121]
## Objective 
The Data & Technology Services Division is initiating a series of meetings to learn more about Maximo user experiences and processes in TPW. In this meeting we'll be asking questions about how individual teams use Maximo and how it fits into their work processes.

## Goals:  
- Maximo system performance and functionality 
- User experience and interface experiences 
- Current processes within and related to Maximo 
- User feedback and improvement  
- Future roadmap and upgrades 

### User experience and interface experiences 
- Explain your process on how you use Maximo? 

### PROCESS - Planning
- Who plans the work? How do you get work to do? 
- How is work scheduled and issued out 
 
### PROCESS - Implementation
- How is work scheduled and issued out?
- Who is executing the implementation? 
 

### PROCESS - Field Work
- Who is executing the work - implementation? 
- Who is reporting on the work and what are they tracking? 

#### Maximo system performance and functionality 
- How long is it taking to do a Maximo work order in the field? 

### PROCESS - Review & Reporting
- What is your final review, QC process? 
- What reporting do you care about? How are you pulling that information out? 
- What are you reporting? 

### User feedback and improvement  
- What challenges are you having with Maximo? 

### Future roadmap and upgrades 
- What would you like your work order management system to do that you’re not getting right now? What’s missing? 

### Points of Contacts 

------
- [x] Schedule meeting - 2/8/24
- [x] Meet and take notes
- [x] Process notes on the [Maximo Assessment Plan Miro Board](https://miro.com/app/board/uXjVN7sxj9I=/)

**Comment by rebekkabry** [comment]
https://github.com/cityofaustin/atd-data-tech/issues/12893#issuecomment-1977142499

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/7b8d3143-7adc-496d-9a35-cfb0bd1f6b99)

**Comment by maccallump** [comment]
@ChristinaTremel and @rebekkabry are documented processes for this work, in other words, do they SOP's?

Are the bridge assets that OCE manages/maintains in Maximo?

**Comment by ChristinaTremel** [comment]
# Christina's Notes
#### Explain your process on how you use Maximo?
- Keep track of all bridge assets and their condition
- Don’t have a system for that so they use a GIS database for this work
- Mostly use Maximo for in house work order tracking
- Don’t create work orders for Contractor work
- Work is super rigorous on bridge assets
- They only give 2-3 bridge work orders to contractors each year
- They used to not have bridge support dedicated crew and would use other crews
- Work order could be from guardrail, sidewalk, handrail, etc
- Depending upon the need, they create a work order for the in house work
- Sometimes with 311 calls, the in house work will be created by the internal Utilities and Structures crew
- Every two years they have follow up actions from TxDOT. TxDOT gives a spreadsheet of 100-200 items. It’s better for the team to create work orders in Maximo. These work orders are bulk created
   - Can’t create bulk work orders for bridge work orders yet
   - Do have that process identified with pavement side
   - Problem: Unlike pavement, assets are not identified by asset IDs on the bridge class. Pavement has unique asset IDs for assets, but bridges don’t have unique asset IDs (bridge components are guardrails, markings, handrails, etc)
- Bridge team has annual maintenance plan
   - Limited number of bridges are on the maintenance plan
      - Contractor: 2-3 bridges
      - In-House could be about the same for maintenance plan
   - Based on OCEs own findings from doing field visits
   - Depending upon the work type, they will give it to Contractor or In-House
- Contractor on In-House
   - Complexity
      - More complex work goes to the contractor
   - Type of Work
   - Resource
      - In-house crew has only been around 2 years so we don’t have all the tools required
      - As we train the in-house crew, some of the work going to contractor might go to in-house
- There is definitely way more reactive work
- Charles: Creates work order from the TxDOT list
   - Number of work orders: 10 per week
   - Steps
      - Drives out and checks the work first
      - Checks the action item
      - Checks if the work order has been created
      - Photo before
      - Follow up action photo
- Ah Young: Contractor and Project Manager is on the Capital Delivery Services side and they have an assigned inspector
   - Uses Geodatabase to track this work
   - Don’t have a bridge management system so they have to use GIS. Haven’t been able to find a good product.
   - IDIQ Contract, each assignment is a DO
   - Give them type of work, specific specifications, and the standard CCO
   - They give OCE a cost estimate
   - Issue DO using eCapri with the amount, scope, type of work
   - Inspector verifies the project throughout the process and signs off at the end
   - Spreadsheet
   - If the work is small, it’s clear cut. If it’s a larger project, there are more issues but overall it’s working within the system and process

### PROCESS - Planning
#### Who plans the work? How do you get work to do?

#### How is work scheduled and issued out

### PROCESS - Implementation
#### How is work scheduled and issued out?
- Lots of work orders are from Charles, they find stuff in the field and create work orders, TxDOT reports things directly to Patty via email, and 311 requests which are emergency type repairs
- Create Maximo work order
- The team does an inspection to determine materials and tools required. Identifies the level of difficulty and if a permit is needed.
- Based on how large it is, it goes into the queue and they prioritize.
- Prioritize:
   - difficulty
   - equipment (share equipment with other teams)
   - permitting process
   - location
- Permitting process: extremely difficult to get a permit to do any type of work
   - Most of her work is emergency and it’s dangerous to pedestrians, drivers, bicyclist
   - In those situation, she’s been able to get an emergency permit
   - She has not been able to successfully get a permit with the regular permitting process
      - Ex: project with transportation. Old Red River, it was realigned but the s curve is still their ROW. Transportation wanted to make adjustments. Patty submitted the permit for the project and they denied it because they couldn’t find the road on the map
   - Issues ROW has: engineer traffic control plan, don’t like their traffic control plans, OCE doesn’t have a traffic engineer, every situation for every street - they want an engineered traffic control plan. Overlay crew is working on getting engineered traffic control plans and if the street changes and the condition changes, they have to get a new traffic control plan. Contractor creating a traffic control plan costs $3500-$5000.
      - Patty tries to file and typically just had to request an emergency traffic control plan.
   - Patty buys material, equipment, gets her staff everything they need to do the job and the Supervisor enters everything into Maximo.
   - Supervisor fills out the Maximo work order ticket
   - Supervise is over 1 crew and the crew is 4 people
   - They also want to use Maximo for Urban Trails which has pedestrian bridges
   - They also want to use Maximo for work orders for lighting on bridges
      - Have a parent for each bridge and create children for each of the individual repairs
      - Lighting on the bridges are assets that they are responsible for maintaining
      
#### Who is executing the implementation?
- Patty, Supervisor (Acting: Joe Ellison), and 4 crew members
- Bridge work orders stay open longer than most other work orders
- Sometimes there is work that will never get done because getting a permit is impossible or they don’t have the material / equipment needed.
- When running the report, there are typically lots in progress
- Number of work orders:
   - Number of work orders depends on the size
      - Over Christmas, her team had a traffic railing on Riverside replaced. District Maintenance also needed guardrail replaced so they helped each other. Usually that work would take 3 weeks. Because of the extra support, they completed that project in 1 week.
       - Some jobs take a day
   - 4 or 5 311 SRs per month (less than a quarter of the work comes from here)
- Supervisor does work order in the field and in the office. He has a tablet that he takes out to the field and he comes back and talks through what he needs to add on the work order with Patty
   - Uses EzMax Mobile
- Tablet: Has an android tablet. Had an iPad previously, but it doesn’t work.
   - The app he uses to take before and after photos and the photo type is the issue with the iPad.
   - If the iPad took the photos, he wouldn’t care.
   - There’s something wrong with his specific tablet.

### PROCESS - Field Work
#### Who is executing the work - implementation?

#### Who is reporting on the work and what are they tracking?

### Maximo system performance and functionality
#### How long is it taking to do a Maximo work order in the field?

### PROCESS - Review & Reporting
#### What is your final review, QC process?
- Ensuring vehicles are on there, equipment, personnel
   - Someone told Patty they want to attach materials so they are being as accurate as they can be but it’s a learning process
- Patty typically orders material per project unless she knows she’ll use a lot of it (limestone boulder, reclaimed material off of projects, construction sites and repurpose for stockpile - located in stockpile)
- Supervisor closes for final review and Patty does the review QA and closes out the Maximo work order
- After the work order is closed, OCE looks back at the photos and the specifications filled out by Patty’s team.
   - Sometimes the specification doesn’t exist and she will use the “Other” specification and add special items. Adriana can add stuff to the specification
   
#### What reporting do you care about? How are you pulling that information out?
- Really important to track specification part of it. OCE can open specs and find out specifically what they did
- Patty runs a report once a month for the stat meeting and the bridge report is really helpful in that way
   - Pulls it up by the bridge category and she can see how many repairs they did
   - Sometimes the numbers look really low or wrong and she’ll go through work orders on paper?
      - Technicians fill out a daily log so they can keep track of where the technicians go. Patty will have them split into 2, 2 person crews so she has them fill out a daily log. Fill that out because of the vehicles they drive and she can see all the sites they go to and the jobs they did.
      - Daily Log: location, how long they were there, and basic address. Doesn’t go into detail about what they did while they were there
   - When they were doing the stat meeting last week, Dave was talking about running a report by specification number and Patty was going to talk to the Maximo team to see if they could build a report
   
#### What are you reporting?

### User feedback and improvement
#### What challenges are you having with Maximo?
- Binaya would want notifications when a work order is completed and closed so they know when to check it
   - They can go through the spreadsheet but the numbers might grow and that would be a challenge
- Rene and Adriana have been great helping with changes

### Future roadmap and upgrades
#### What would you like your work order management system to do that you’re not getting right now? What’s missing?

### Points of Contacts
    
### Action Items:
- DTS works on giving Binaya notifications for when work has been closed
   - There’s a report called “SBO Bridge Repair Completed” that we could send out if it would be helpful
- DTS research the permitting issue   
- Patty - sends daily work log
- Binaya - ask to send AGOL map or the datasets they currently manage for bridge assets

**Comment by ChristinaTremel** [comment]
Notes have been added to the Maximo Assessment Plan Miro Board!
