### ISSUE TITLE
[DevOps] Monitor CRIS import ETL for potential mass update

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#16157]
As discussed [in Slack](https://austininnovation.slack.com/archives/CM9MK950S/p1709737581291149), today's CRIS import was suspiciously large. We're going to pause the import and double-check tomorrow's import files in order to get a better understanding of what's going on.

**Comment by frankhereford** [comment]
Thanks @johnclary - I have disabled the Airflow ETL that imports CRIS data like we discussed on slack. Thanks to @chiaberry for the heads up that something was different when [she observed](https://austininnovation.slack.com/archives/CM9MK950S/p1709737581291149) that the CR3 download was taking a lot longer than normal. 

I did peek the CSV exports we got today, and the 2023 schema export today was about 10X the normal size. Inside that payload, I observed an even smattering of crashes with a crash date between the first of the year and today, as if they were going back over those. But there was a hard cut-off at January 1st, which maybe means it's a temporally isolated thing? 

No telling 'till we get some more data, so I am going to look at what they send us tomorrow before letting it be processed or we decide to take another action. 

Thanks y'all!

**Comment by frankhereford** [comment]
It appears likely that CRIS is doing a mass reprocessing of crashes, making edits, at least, to the `road_type_id` and back-filling in the newly populated `investigator_narrative` field. The team meet this morning and discussed the implications of this, we decided to do the following:

* [ ] make sure the ETL is handling important fields as we understand it to do
* [ ] cross check that list against the VZE editable fields
* [ ] look into the new person name fields and make them important
* [ ] check the code that goes into the "affected" columns column, look for big disconnects there

**Comment by frankhereford** [comment]
# Notes

## General notes

* Running the ETL locally against a replication of the production DB yields about 2K new entries into the `atd_txdot_changes` table. 
  * This is about the expected amount, given our designation of 'road_type_id' as being "important." 
    * As expected, the bulk of the updates concern the `road_type_id` and the new narrative field. I observed a fair number of updates to the `units.rpt_autonomous_level_engaged_id` field too.
    * I am hopeful maybe that because we're seeing these new fields being populated, then maybe, just maybe, 
    the reprocessing is going to be limited to 2023 schema crashes, which means this will go for 12 days, not multiple months.
    * Our situation gets a lot better if `road_type_id` were not important. So many fewer crashes into the conflict resolution system.
  * It takes about an hour to run on my computer, but keep in mind there's no internet between the ETL and the DB when running locally. I'm thinking 2-3 hours in production. Every day for 3 months.. + 1-2 hours of CR3 downloads. 
    * When I was solo'ing the CR3 downloads back when, we got CRIS reprocessed at some point and every crash's 
    CR3 got flagged to redownload. It took a week, maybe a few weeks, of keeping that script going all work day and often into the evening if I was at my computer, 2K crashes at a throw. Not great.

## Item 1: ETL `important` field handling


* The ETL does appear to accurate in picking out changed columns, both important and non-important. 
  * Like the rest of the ETL, it's drawing out the list of columns it needs to operate on from the PG
  metadata, so there's not really a list of expected columns to verify; it's all dynamic.
    * Each column gets a `SELECT` clause built up for it to see if it's changed like this:
```
select array_remove(array[
                case when not coalesce(
                    public.atd_txdot_crashes.crash_id = import_c87982f5f763.crash.crash_id
                    or
                    (public.atd_txdot_crashes.crash_id is null and import_c87982f5f763.crash.crash_id is null)
                , false) then 'crash_id' else null end
            ,
                case when not coalesce(
                    public.atd_txdot_crashes.private_dr_fl = import_c87982f5f763.crash.private_dr_fl
                    or
                    (public.atd_txdot_crashes.private_dr_fl is null and import_c87982f5f763.crash.private_dr_fl is null)
                , false) then 'private_dr_fl' else null end
            , ....
            ], null) as changed_columns 
from public.atd_txdot_crashes 
left join import_c87982f5f763.crash on (public.atd_txdot_crashes.crash_id = import_c87982f5f763.crash.crash_id)
where public.atd_txdot_crashes.crash_id = 19954071
```

* The mutations look like they should, and that code has been unchanged ages. You can read it here: https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/cris_import/lib/helpers_import.py

## Item 2: Cross check important fields with VZE

VZE Editable Fields (* denoting a match):

Crash:
  * Location via (Latitude / Longitude) *
  * Severity *
  * ATD Fatality Count *
  * APD Death Count *
  * Law Enforcement Number
  * City *
  * Speed Limit *
  * Roadway Type *
  * Traffic Control *
  * Suspected Serious Injury Count
  * Total Injury Count *
  * Primary Address *
  * Secondary Address *
  * Intersection-Relation Flag
  * Private Drive Flag *
  * Road Construction Flag *
  * Outside City Limit Flag

Unit:
  * Type
  * Bodystyle
  * Direction *
  * Movement *
  * Fatalities *
  * Suspected Serious Injuries *

Persons:
  * Injury Severity *
  * Age *
  * Sex
  * Race / Ethnicity
  * Suspected Unhoused Flag


ETL Important Fields (* denoting a match)
```
"atd_txdot_crashes": {
    "longitude_primary", # *
    "latitude_primary", # *
    "city_id", # *
    "crash_speed_limit", # *
    "road_type_id", # *
    "traffic_cntl_id", # *
    "crash_sev_id", # *
    "atd_fatality_count", # *
    "apd_confirmed_death_count", # *
    "tot_injry_cnt", # *
    "atd_txdot_crashes.sus_serious_injry_cnt", # *
    "address_confirmed_primary", # *
    "address_confirmed_secondary", # *
    "private_dr_fl", # *
    "road_constr_zone_fl", # *
},
"atd_txdot_units": {
    "travel_direction", # *
    "movement_id", # *
    "death_cnt",
    "sus_serious_injry_cnt", # *
},
"atd_txdot_person": {
    "injury_severity", # *
    "prsn_age", # *
},
"atd_txdot_primaryperson": {
    "injury_severity", # *
    "prsn_age", # *
},
```
## Item 3: Make name fields important 

Person name fields have been marked as important:
https://github.com/cityofaustin/atd-vz-data/pull/1393/files

## Item 3: Eyes on the affected columns code

On checking out the code that makes the affected columns list, it's here:

```
# build an comma delimited list of changed columns
all_changed_columns = ", ".join(important_changed_columns["changed_columns"] + changed_columns["changed_columns"])

```

It's the set of columns which have a value in the DB that differs from what we've received from CRIS, both important and not.
