### ISSUE TITLE
[BUG] Amenity's followed projects don't show on her "Dashboard" page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#16166]
When I was demoing to PIO this morning, I followed these two projects and they don't appear on the "Following" tab of my "Dashboard" page. 
- https://mobility.austin.gov/moped/projects/221
- https://mobility.austin.gov/moped/projects/2312

@chiaberry suspects it may have to do with messed up permissions on my account.

**Comment by amenity** [comment]
[like]  Applewhite, Amenity reacted to your message:
________________________________

**Comment by chiaberry** [comment]
This may be solved by https://github.com/cityofaustin/atd-moped/pull/1295, let me know @amenity if you can see your projects again and then this can be closed!

**Comment by amenity** [comment]
Looks great, thanks @chiaberry 🕵🏻‍♀️
