### ISSUE TITLE
[Enhancement] Prototype Vehicle Checkout module

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#16174]
# 3/7/2024
Met with stakeholder and got scoping notes

### Approved Driver - feature
- [x] Create `vehicle_drivers` table
- [x] Create `vehicle_driver_request` table
- [x] Created "Approved Driver" form

### Vehicle Checkout - feature
- [x] Create `vehicle_checkout` table
- Fields
- [x] Created Date - Date/Time
- [x] Created By - connection (accounts)
- [x] RSVP Date & Time - Date/Time
- [x] Driver - connection
- [x] Purpose of Trip - Short Text
- [x] Start Mileage - Number
- [x] End Mileage - Number
- [x] Refuel - Multi-choice, radio
- [x] Photo/Image
- [ ] Checklist
- [x] Status
  - [x] Checked out
  - [x] Checked in

### Create Checkout form
- Date & Time of Usage
- Driver
- Purpose of Trip
- Starting Mileage

## After Check out
- Edit Check out record 
  - End Mileage
  - Refuel? - Y/N
  - Status: "Checked In"

_Optional_
- Photo Attachment 
- Vehicle Inspection Photos?
  - [ ] I verify I inspected the vehicles
  - [ ] Checklist 
  - [ ] Photo if an issue is present

## Create Reservation Calendar
- Ability to see reservations on the books

**Comment by patrickm02L** [comment]
@dianamartin can you share me a link to the prototype front and backend?

**Comment by dianamartin** [comment]
# 3/19/2024
- Vehicle Checkout front end [link](https://atd.knack.com/smart-mobility#vehicle-checkout/)

## Update "vehicle_driver_request"
- [x] Create field "Request ID" - auto increment
- [x] Create field "Created By" - connection
- [ ]

**Comment by dianamartin** [comment]
# 4/3/24
Patrick and I huddled to get the Vehicle Check out Prototype in a better place. (Don't remember the day..)
- [x] Updated the "New Driver Request" Page with better language for "D. Security/ Risk of Loss/ Care of Equipment. " (taken from AMD vehicle page)
- [x] Added Availability Calendar
- [x] Added "New Vehicle Checkout" form
- [x] Configured Availability Calendar
- [x] Added "Edit Vehicle Checkout" form

## Today's Updates
- [x] Reviewed pages
- [x] Renamed "Approve Driver Request" page to "New Driver Request" page
- [x] Clean up title on "Vehicle Availability" page
- [x] Added icon on "New Vehicle Checkout" button
- [x] Tested functionality
- [x] Deleted dup "Edit vehicle checkout" page

**Comment by dianamartin** [comment]
# 4/4/2024
Before the meeting we updated
- [x] Added page, My Checkouts

Synced with user and some enhancements were asked for
- [x] Added edit button on My Checkouts
- [ ] display rule: Checked In - edit button not visible
- [x] Added, Manage Checkouts page
- [x] Added edit button on Manage Checkouts
- [x] Set up email notification when requester edited record
- [x] Cleaned up details pages to be uniformed

**Comment by dianamartin** [comment]
Synced in the afternoon and saw 1 real record, we'll close for now and add more if there are other enhancements to the epic.

**Comment by dianamartin** [comment]
# 4/10/2024
Made a few updates to help correct the multiple "Checked Out" records in the main table of "Vehicle Checkouts"
- [x] Added new field `RSVP Status` - "Reserved" 
- [x] Added new field `ACTIVELY_CHECKED_OUT`
  - Conditional Rule: 
    - RSVP Status - is not - Reserved
    - Status - is not - Checked Out
    - Set to `1`
    AND
    - Status - Checked In
    - Set to `0`
- [x] Updated the record rule in on`New Vehicle Checkout` form
  - [x] From **Status** = Checked Out, to **RSVP Status** = Reserved
- [x] Add task to `vehicle_checkout` 
  - "Checkout Day"
  - Update record:
     - Check Out/In - is today
     - Status - Checked Out
     - RSVP Status - blank
- [x] On "Vehicle Checkout" table add "Reserved" filter
- [x] On "My Checkouts" table add "Reserved" filter
- [x] On "Manage Checkout" table add "Reserved" filter
- [x] On "Manage Checkout" table add "RSVP Status" field
- [x] On all details page of Availability table add "RSVP Status" field
