### ISSUE TITLE
Update and re-run the script that checks for lookup table changes

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#16176]
We discovered today that CRIS renamed a lookup table during the last schema update. The table `atd_txdot__road_type_lkp` was changed to `atd_txdot__rpt_road_type_lkp`.

We should:

1. Update [this toolbox script](https://github.com/cityofaustin/atd-vz-data/tree/master/atd-toolbox/get_lookup_table_changes) to detect when a table is dropped and also update it to detect when a lookup value is deleted from a table.
2. Re-run the script and see if missed any schema changes.

**Comment by johnclary** [comment]
@roseeichelmann do you have a WIP branch pushed up for this? i just want to capture your work before moving this back to the backlog.

**Comment by roseeichelmann** [comment]
@johnclary yep here it is! https://github.com/cityofaustin/atd-vz-data/pull/1395

**Comment by johnclary** [comment]
This work has moved as far along as it needs to. the rest will be covered by the [new data model](https://github.com/cityofaustin/atd-data-tech/issues/10430)
