### ISSUE TITLE
Josh Off-boarding

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#16193]
**Off Boarding Items**
- [x] 1Password
>Suspended account - DM, 3/11/2024
- [x] Slack
>Deactivate account - DM, 3/11/2024
- [x] Miro
>Delete from "Transportation team" - DM, 3/11/2024
- [x] Knack Applications
  - SMD Tracker - Susanne
- [x] SMD SharePoint - Diana
>The way permissions was allowed folks to access it, not by individual accounts
- [x] GitHub - Diana
>Removed user from "Transportation" team
- [ ] ~Zenhub~
>This does not require removal of user
- [x] Google Drive
>Checked this and it he was no longer on the list
- [x] SERF - Andrew submitted one `REQ0177646`, closed today 3/11/24
- [x] DTS Email Distribution List - check on this, Diana
- [x] Remove from About Us page - Andrew #16284
- [x] DTS Team Slide - Diana
>Removed - Diana, 3/11/24
- [x] DTS Orientation Slides - Diana
>Removed - Diana, 3/11/24 
- [x] AGOL Deactivate account - Andrew
- [x] AGOL Data Transfer - Andrew

**Comment by dianamartin** [comment]
# 3/11/2024
@andrewshensky I've updated most of these tasks, I think you just have the couple we talked about today at our 1:1.
