### ISSUE TITLE
TED Mitigation Updates for Mitigation Maps

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16202]
### Updates to TIA Mitigation features for TED Mitigation Map Project

**Rename 2 Fields**

- [x] Update Spend Funds to Obligated/Spent
- [x] Update Remaining funds to Balance

**Mitigation Details Page:**
Remove the following:
- [x] Mitigation Fees Required
- [x] Mitigation Fees Sent
- [x] Mitigation fees sent timestamp
- [x] Mitigation fees paid
- [x] Allocatable Funds
- [x] Historical Amount
- [x] Unidentified Amount

**Mitigation Table on the Mitigation Details Page:**
Remove:
- [x] Cost
- [x] Cost Paid
- [x] Share $
- [x] Share Paid

**Landing Page View:**
Remove these columns:

- [x] Fee info
- [x] Allocatable funds
- [x] Historical Amount
- [x] Unidentified Amount

**Edit Mitigation Status Form:**
- [x] Mitigation Fees Paid Date - don't show when 'Mitigation Fees Paid' is No

**Comment by TracyLinder** [comment]
**Rename 2 Fields**

- [ ] Update Spend Funds to Obligated/Spent
- [ ] Update Remaining funds to Balance

**Mitigation Details Page:**
Remove the following:
- [ ] Mitigation Fees Required
- [ ] Mitigation Fees Sent
- [ ] Mitigation fees sent timestamp
- [ ] Mitigation fees paid
- [ ] Allocatable Funds
- [ ] Historical Amount
- [ ] Unidentified Amount

**Mitigation Table on the Mitigation Details Page:**
Remove:
- [ ] Cost
- [ ] Cost Paid
- [ ] Share $
- [ ] Share Paid



**Landing Page View:**
Only show these columns: 

- [ ] Mitigation Status 
- [ ] Mitigation Fee Types 
- [ ] Available Funds 
- [ ] Obligated/Spent 
- [ ] Balance 
- [ ] Expiration Date 
- [ ] Recommendation Amount 
- [ ] Construction Amount 
- [ ] Fee in Lieu Amount 
- [ ] Fiscal Amount

**Comment by TracyLinder** [comment]
**Review notes from Kat:**

For the Landing Page View, please also keep columns 1-7: View, Project, Primary Project Address, Council District, Review Area, Case Approved Date, Mitigations.

All other columns look good. May wish to add a notation about the Map as that is a key component we’d like to see soon.

**Comment by ChrispinP** [comment]
All action items completed above. 

Additionally:
- Updated the View & Edit buttons we are using for new apps and enhancements.
- Since we removed a couple fields the table filters depended on, I updated the filters to the 3 Mitigation Statuses
