### ISSUE TITLE
IT Support: iPad minis for SMD

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#16209]
CAMERON - 8700/8900

## Device & User Information (first name and last initial, no last names)
Matt M
## What's the problem?
We just received 6 iPad Minis for SMD and I will be bringing them up to Cameron today

**Comment by susannegov** [comment]
Jordan G. is out for the week. Holding tablets until then.

Messaged Cathy
> The tablets are ready. Jordan is out for the ESRI dev summit this week. Do you want me to hand them off to you tomorrow?

**Comment by susannegov** [comment]
Closing this. Handed off tablets to Jordan H.
