### ISSUE TITLE
Prototype SBO Overtime requests

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#16213]
_Notes from 3/6/2024 meeting_
### Features
- Superintendent & Supervisor submits
    - Subgroup work groups
    - Crew (group of employees)
    - Same date & time
    - Approval: Division Managers (up to 8 hours)
        - Emergency OT
    - Beyond 8 hours (Assistant Director)
        - Fri: some overtime requests
    - WORK ORDER ID (Required)
    - PROJECT LOCATION (Required)
    - TYPES
        - Carryover overtime: need to complete work assignments, stay late (non-emergency)
        - Scheduled overtime: if work group anticipates need, beyond
        - Emergency overtime
- WPD has several Task Order Codes (would use this for "Tasks")
  - Planned High Priority Work
  - Community Engagement
  - In-house Projects
  - Executive Direction Work
  - Unplanned Emergency Work
  - Emergency Storm Recovery Work

- Ideas for Task Code Categories:
    - High risk projects
    - High Priority, Executive
    - Safety Concerns

- Reference HR - Work Logs
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/dcbe2657-3925-452e-ac44-05100ab17902)

**Comment by dianamartin** [comment]
# 3/12/24
## Build Notes
- [ ] Create new table `form_overtime_requests`
  - [ ] Create connection to `sbo_reviews`

### Add Fields
  - [ ] Requester - Connection - logged in user
  - [ ] Requested Date - Date/Time
  - [ ] Modified By - Connection - logged in user
  - [ ] Modified Date - Date/Time
  - [ ] `Work Order ID` - Short Text
  -  `Work Type` - Multi-choice
     - [ ] Planned High Priority Work
     - [ ] Community Engagement
     - [ ] In-house Projects
     - [ ] Executive Direction Work
     - [ ] Unplanned Emergency Work
     - [ ] Emergency Storm Recovery Work
  - [ ] `Project Location` - Short Text
  - [ ] `Work Date` - Duration?
  - [ ] Start Time? - Date/Time
  - [ ] End Time? - Date/Time
  - [ ] `Crew` - Rich text
  - Status
    - [ ] Not Reviewed
    - [ ] Approved
    - [ ] Denied

**Comment by ChristinaTremel** [comment]
- Showed the stakeholders the prototype and received feedback in #16213. Closing this because the prototype is complete!
