### ISSUE TITLE
Create and Publish 311 CSR dataflow in Power BI service

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#16244]
Currently we have the TPW 311 CSR dataflow in DTS - Dev

Link: https://app.powerbigov.us/groups/c78e625c-c676-4727-9d5b-b5f0565ee975/dataflows/75ba5df3-2e90-42d2-931c-6f72d3f06c6f

# To do
- [x] Setup Power Query fields for internal use
- [x] Write metadata and proper descriptions
- [x] Publish in TPW Premium Workspace and TPW Premium Workspace - Test

**Comment by katelunceford** [comment]
Synthesizing notes from [Data Science Backlog Refinement](https://docs.google.com/document/d/16RBJStu65lHTQa_MVYde7jmortp1ako1P1-A6mPcNOg/edit) on 3/13:
- You can access dataflow if you have access to the premium workspace
- Dataflows are tied to the user so it's easier to identify the data owner
- Idea came from last month's COA PBI User Group - Ben mentioned it for calendar date field / time analysis 
- This is a good chance to test out the PBI deployment pipeline
- [x] Susanne will schedule a work session with Charlie & Kate to accomplish items in To Do above
- [ ] Let's check with @amenity /others if there's a desire to do something similar with Moped where users like to build their own reports - we could make it easier for them to access Moped data

**Comment by susannegov** [comment]
311 CSRs are in TPW workspace environment as a linked table.

>     * [ ]  Let's check with @amenity /others if there's a desire to do something similar with Moped where users like to build their own reports - we could make it easier for them to access Moped data
Can put this as a seperate github issue. The 311 CSRs issue I think are good to close out

**Comment by Charlie-Henry** [comment]
I made a new issue for us to build a dataflow for TPW unified work orders.
https://github.com/cityofaustin/atd-data-tech/issues/16656

**Comment by Charlie-Henry** [comment]
@katelunceford I wonder if it would be worth our time to investigate us building a dataflow with maximo, vision zero, or moped databases? Could lower the barrier to entry for folks. Maybe @susannegov could look into it as she has experience with using the gateway connection which I think is needed for these

**Comment by amenity** [comment]
@katelunceford @Charlie-Henry - that sounds amazing, especially if we could set up/streamline it enough that we could write a how-to guide for staff to explore on their own.

**Comment by Charlie-Henry** [comment]
I added some docs [here](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M2EDlSmB3f_vryzLEhZ/power-bi/connecting-to-a-dataflow)
I think we're good to close this one out?

**Comment by katelunceford** [comment]
We started an epic to track Dataflow work [#16707 Configure PBI dataflows](https://github.com/cityofaustin/atd-data-tech/issues/16707#top)

I copied the last few comments from this issue into that epic

I'm closing this out as discussed during Data Science Backlog Refinement on 4/10/24
