### ISSUE TITLE
Don’t show issues from the “Icebox” pipeline on the website

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#16252]
Currently, issues from the Zenhub "Icebox" pipeline show in the "Backlog" tab on the "Projects" page. We've been averting this by removing the "Project Index" label, but it would be helpful for us to keep that on all potential projects, whether or not they're currently on the table. 

We don't want to see any Icebox issues on the website anywhere. 

Here's an example: [Project: Material Inventory and Order Tracking](https://github.com/cityofaustin/atd-data-tech/issues/9370)
<img width="1164" alt="Screenshot 2024-03-13 at 1 38 25 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/3ae5b7bd-bc31-403d-8cd0-a9a7c70c3005">

**Comment by johnclary** [comment]
> We don't want to see any Icebox issues on the website anywhere.

It should be possible to exclude all icebox issues by updating our socrata query.
