### ISSUE TITLE
Show a subset of completed projects on the website

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#16258]
We have a slew of completed projects and don't want to hide our most impressive work amidst projects that aren't as interesting to a general audience.  

So we would like to show a subset of our completed projects on the ["Complete" tab on the “Projects" page](https://austinmobility.io/projects?status=completed). 
![screencapture-austinmobility-io-projects-2024-03-13-13_49_55](https://github.com/cityofaustin/atd-data-tech/assets/1463708/87617616-6cb5-40ba-9b66-5978082699fd)

- [ ] Hide projects with the `Archived Project` label from the completed project listing. 
- [ ] Add text at the bottom of the page, "Visit [Github](https://github.com/cityofaustin/atd-data-tech/issues?q=is%3Aissue+label%3A%22Project+Index%22+is%3Aclosed) for a full list of our completed projects."

<img width="1044" alt="Screenshot 2024-03-13 at 2 56 00 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/adcd47bb-30f4-4e8c-8b2b-daa1b4640cbe">

**Comment by frankhereford** [comment]
No problem with the implementation, but I did want to make sure that I'm correct in that I'm seeing that no projects have had the "Archived Project" label applied yet. If that doesn't sound right, please let me know. Thanks!

**Comment by amenity** [comment]
@frankhereford - that's true! I'll check in w/ PMs and get that going.
