### ISSUE TITLE
Update division names on the website

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#16262]
Update the workgroup names hardcoded [here](https://github.com/cityofaustin/atd-product/blob/5f34b19d8e9a20f04845edd43656ed322f9af362/components/projectsView/ProjectFilters.js#L18) to get rid of straggling acronyms on the "Projects" page and individual project pages. 
<img width="616" alt="Screenshot 2024-03-13 at 9 45 27 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/b9b25c20-8d66-46a6-bcf5-807c6663f852">
<img width="439" alt="Screenshot 2024-03-12 at 12 04 50 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/8faabc35-0ea3-4b0a-b8d9-a971f375996c">

**Comment by johnclary** [comment]
looks like this might be a dupe of https://github.com/cityofaustin/atd-data-tech/issues/12349

**Comment by amenity** [comment]
Thanks, @johnclary - you're right.
