### ISSUE TITLE
IT Support: [Issue with the scanner]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#16274]
St Elmo
## Device & User Information (first name and last initial, no last names)
Scanner Epson 50 & Eladio, M
## What's the problem?
User cannot able to scan the documents.
## What did you do to resolve the issue
Have connected over to my laptop and downloaded the drivers for temporary then provided the required document as user was out on field and cannot access the laptop. Need to again re-fix the issue and get him updated with the drivers once he's available.

**Comment by Vaishnav1397** [comment]
Worked out it but drivers couldn't be downloaded need to re-check as the user was unavailable.

**Comment by dianamartin** [comment]
@Vaishnav1397 please put an estimate and if this need to be followed up on you can put it in the "Review QA" status.

**Comment by Vaishnav1397** [comment]
> @Vaishnav1397 please put an estimate and if this need to be followed up on you can put it in the "Review QA" status.

**Comment by Vaishnav1397** [comment]
Checked over with user and mentioned to reach to the company as it was not populating in the system, user mentioned he is good. If in case still, he has any requirement he said he would reach out to us.
