### ISSUE TITLE
Perform DTS onboarding tasks Craig J.

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#16319]
You won't be able to assign this to the new team member until they have a Github username, but in the meantime you can direct them to the [Welcome to DTS](https://github.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/welcome-to-dts) Gitbook page.  Copy and paste the checklist from that page into the issue body.

# Day 1 
These are the high priority tasks. Let your supervisor know if you have any issues completing them on your first day. 
- [x] [Log in to your City of Austin email](https://outlook.office365.com/).
- [x] [Install the Microsoft Authenticator app](https://atx.servicenowservices.com/sp?id=kb_article&sys_id=b46a964d1b5a35d0e8dfc844604bcb01) on your phone. Moving forward, you should only  log in to City of Austin Microsoft services via 2 factor authentication. 
- [x] You should have a 1Password invitation in your email. If not, email/Slack Diana to request one and then accept the invitation. Diana or Amenity will then confirm your account. Then follow [this guide](https://support.1password.com/explore/get-started/) to set up 1Password for use on your City computer and any mobile devices you use for work.

_All your passwords relating to work should be stored 1Password and only in 1Password._

- [x] If you don't have one already, [create a Github account](https://github.com/join) with your CoA email and then ask Amenity or Frank to add you to the City of Austin [Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members).
- [x] Enable [two-factor authentication for your Github account](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa).
- [x] Install Slack desktop client — [Windows](https://slack.com/downloads/windows) | [Mac](https://slack.com/downloads/mac).
- [x] [Set up your email signature](https://docs.google.com/document/d/1OAoBll9rIl6XZq2uOShm5HCbHJboOt0SLP_wK6tjkEE/edit).
- [x] [Update your Slack profile](https://slack.com/help/articles/204092246-Edit-your-profile) with a photo and your title.
- [x] Post your [daily standup in Slack](https://atd-dts.gitbook.io/wiki/slack#daily-stand-up).
- [x] [Create a Google account for your austintexas.gov email address](https://github.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/basics/document-storage/using-google-as-a-city-employee) and verify that you have access to the [DTS Google Drive](https://drive.google.com/drive/u/0/folders/1fNmU-czryk5wJsn1gmb4WYUJJdut8Me7).

**Comment by Craigjacobs-ATX** [comment]
completed are required tasks.
