### ISSUE TITLE
Rename UC Review Processes (LP) (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#16328]
**Acceptance Criteria** 

- The AC provided below is to make changes to the review processes in UC folders. 
- Process 51216 - Grande Communication needs to be renamed to Grande(Astound)
- Process 51139 - Alpheus (El Paso Global) needs to be renamed to Logix(Alpheus)
- Process 51337 - Verizon (MCI) needs to be renamed to Verizon(MCI/XO)
- Process 51307 - Time Warner Cable needs to be renamed to Spectrum/Charted (TWC)
- Process 51306 - TelePacific (Telwest) needs to be renamed to TelePacific(TPx)

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and created Dev deployment request, SCTASK0411266

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and created Dev deployment request, SCTASK0412768

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Update - Changes deployed to Test , Ready for UAT

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Kyle has approved this to go to PROD

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Ready for UAT on Prod

**Comment by KyleErich** [comment]
I'm closing this card, as card #17018 has been created for the misspelling issue.
