### ISSUE TITLE
UC Add/Remove/Rename Project Sponsor Facility Owner Info values (UAT on PROD) (SS)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#16329]
The Acceptance Criteria below applies to UC folders. 
- The following changes need to be made in Project Sponsor (76765) info field in UC folders
-  The drop-down option 'Century Link/Level 3' needs to be renamed to 'Lumen(Brightspeed)'
-  The drop-down option 'Grande' needs to be renamed to 'Grande(Astound)'
-  The drop-down option 'MCI_Metro (Fiber Group)' needs to be renamed to 'Verizon(MCI/XO)'
-  New Drop-down option needs to be added - 'CyrusOne - CYO'. 
-  New Drop-down option needs to be added - 'TelePacific(TPx) - TPX'. 
-  New Drop-down option needs to be added - 'TW Telecom - TWT'. 
-  New Drop-down option needs to be added - 'Unite Private Networks - UPN'
-  New Drop-down option needs to be added - 'SiEnergy LP - SIE'
-  New Drop-down option needs to be added - 'Enterprise Products - ENP'

**Comment by vschandramouli** [comment]
Made slight edits to AC written by @rajeshlaunch 

Moving to backlog @TracyLinder @Nadin-Nader

**Comment by vschandramouli** [comment]
@SubhaShroff Updated AC based on our discussion.

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0409978 - is submitted for DEV deployment. Thank you.

**Comment by SubhaShroff** [comment]
@Nadin-Nader This is also deployed in DEV and I tested it. It looks good. I will be sending the TEST deployment plan for this.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to TEST under **SCTASK0411337**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is in TEST and I tested for. Its ready for UAT on TEST. 
NOTE: The acronyms are preceded the name of the project sponsor to maintain the uniformity with the existing dropdown values, after having a word with @vschandramouli.
Example: 'CYO - CyrusOne'.

Thanks.

**Comment by TracyLinder** [comment]
We need Jaclyn to test this.

**Comment by KyleErich** [comment]
@Nadin-Nader @TracyLinder @SubhaShroff I'm comfortable approving the UAT on Test for this card, as I was able to check the Project Sponsor dropdown and compare against the AC. Thank you.

**Comment by SubhaShroff** [comment]
Thank you Kyle.
@Nadin-Nader  Please raise a PROD deployment. Thanks.
[16329 - 9af61a2b23acce50c - 1dd9f80828406eef  PROD Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/14998934/16329.-.9af61a2b23acce50c.-.1dd9f80828406eef.PROD.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0412919**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @vschandramouli  This ticket is deployed in PROD and verified in database. Ready for UAT on PROD. Thank you.

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff UAT on PROD approved. Thank you!
