### ISSUE TITLE
Add/Remove UC Franchise Processes (LP)  - (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#16330]
The Acceptance Criteria below applies to UC folders:
- Create new review processes under UC folder to match the other Review processes for each of the corresponding Project Sponsor (Info Code 76765) info field drop down values:
•	Abovenet Communications
•	Atmos Energy
•	Apogee
•	ATT Mobility
•	Center Point Energy
•	CITGO Pipeline
•	Enterprise Texas Pipeline
•	Extenet/Tmobile
•	Flint Hills Resources
•      Lumen(Brightspeed) (updated from Century Link as part of #16329)
•	Verizon Wireless (Small Cell/Other Wireless)
-	All the attempts and business logic for the newly created processes can be replicated from the existing review process, ex: 51142 - AT&T (SWBT)
- System should insert Process 51147 (CyrusOne) into the UC folder along with other Review processes 
- System should insert Process 51306 (TelePacific) into the UC folder along with other Review processes
- System should insert Process 51308 (TW Telecom) into the UC folder along with other review processes

**Comment by rajeshlaunch** [comment]
Added AC to the card. @vschandramouli Kindly review the AC and move it to backlog.

**Comment by vschandramouli** [comment]
Reviewed and updated AC, moving to backlog. 

CC @Nadin-Nader @TracyLinder

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Comitted changes and requested for Dev Promotion, SCTASK0414279

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified on Dev and Created Test deployment request , SCTASK0415303

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV and TEST please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and requested for Dev and test promotion

**Comment by KyleErich** [comment]
@Lpriya-LIT @Nadin-Nader UAT on Test approved, thanks!

**Comment by Lpriya-LIT** [comment]
Update - Created Prod deployment request SCTASK0427991

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to PROD, i will let the UC Team and Kyle know

**Comment by KyleErich** [comment]
@Lpriya-LIT @Nadin-Nader UAT on Prod approved, thank you!

**Comment by TracyLinder** [comment]
@Lpriya-LIT it looks like there's a bug with this. See issue #17821. I will tag you on it. 
FYI @Nadin-Nader @rajeshlaunch @vschandramouli
