### ISSUE TITLE
[PBI] SMD datasets Power Query\Calculated Groups Cleanup

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#16339]
# Context
There are currently a bunch of duplicates that can be cleaned and organized
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/f3a47527-6dc4-4622-8311-b58a7a9e5f7e)
Need to improve performance and sustain long term maintenance of queries

# To do
- [x] Change from Duplicate to Reference
- [x] Fix errors
- [x] Put them in appropriate folders

**Comment by katelunceford** [comment]
Synthesized notes from Data Science Sprint Planning on 3/20: 
- This is mostly tech debt that needs to be done in preparation for long line dataset
- Cleaning it up to a readable format
- Doing it on a duplicate dashboard so not affecting the original dashboard
- Will hand off the SMD performance measures to Jordan

**Comment by susannegov** [comment]
# Datasets (performance metrics)
- [x] 311 CSRs
- [ ] Short line
- [ ] Specialty point
- [ ] specialty line
- [ ] in-house work orders

**Comment by susannegov** [comment]
# 3/22
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/8a052c5b-3e18-4ea5-8e81-6e405fdda0ae)
- Added `ALL('Short Line Dates'[Work Origin]), // Ignores work origin filtering for the matrix table` in School Crosswalks `Grand Total` measure
- Calculated `Time condition` in the feature layer through a merge query
   - After merge: 
      - Set Remove duplicated of unique ID
      - Expand aggregate to List.Min of `Months Past Work`

**Comment by susannegov** [comment]
# 3/26
- Cleaned up column names in Specialty Line and Specialty Dates

**Comment by susannegov** [comment]
# 3/27
- Added RPM (non curb and RPM_Lane_seperator as those are not tracked)
- Added HIN and Non-HIN measures/Cards
- Added SBO On Time
- Added Last Refresh date
- Add descriptions for SBO On Time (%)
- Published in `DTS - Development` premium workspace for now.

Link is: https://app.powerbigov.us/groups/c78e625c-c676-4727-9d5b-b5f0565ee975/reports/99160200-abde-4be4-aef5-7e72f4d38a88/ReportSection

@ChristinaTremel @katelunceford This is ready for review/QA I would like to eventual use this to replace the old SMD dashboard and am willing to go over the changes

**Comment by susannegov** [comment]
# Meeting on 3/29
- [x] Verified School Crosswalk numbers
- [x] Verified 311 SR numbers
- [x] Verified SBO On Time Percent
- [ ] Verified Fair or Better %
   - Need to check the 1% discrepancy between Non-HIN in old and new report.

**Comment by susannegov** [comment]
Republished report on: https://app.powerbigov.us/groups/b73ea40f-8b44-4aa9-9794-7a87b43e5246/reports/26c00b76-be44-4f39-9579-65b2ab099121/ReportSection
