### ISSUE TITLE
CSD Network Folder deletion, folder and permissions restoration

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#16346]
# Background 
## Thu, 2/29
`CSD G://Drive folder was deleted`

## Fri, 3/1 
- `INC0370982` - was submitted by Stephanie R. - users noticed CSD G://NPP folders were not showing up
- Email from Nathan G. (Urban Trails), 
>today our team has noticed that the G drive appears to have been updated already without any heads up. The old Urban Trails  folder looks to have been in G:\CSD but that folder doesn’t seem to exist anymore and we can’t find any archive of it anywhere, or any other Urban Trails folders either. 

>Are you aware of this? This is for sure why we are wanting to have everything moved to the SharePoint, but now the originals seem to be (hopefully temporarily) lost. 
- we replied
>Hi Nathan, 
Preston submitted a ticket a few minutes ago asking if that folder moved. I’m having my team investigate it now, I am unaware of a folder move. We wouldn’t do that without prior permission. 
- Matt said
>I started the recovery. It’s a lot of stuff so it will take some time. 

- Preston submitted #16099 - [URGENT] We are working with CTM (Ticket # INC0370982). Community Services Division network drive folder (G:)
- Used CTM ticket `INC0370982` to restore folder 

## Mon, 3/4
- Preston sends follow up issue - #16122 - [URGENT] Issue with permissions. G:\CSD folder was deleted. 
>G:\CSD folder was deleted on Thursday and restored on Friday, however CSD staff were restored with view/read-only access to folder and files. 

- Peggy submitted a CTM Ticket `INC0371425` - research how folder deletion happened 
- CTM replied
>It appears on February 29th the folder was removed by Dawn T-C.  When Matthew was restoring the folder, the permissions were changed.  He has since restored permissions and looks to be working through the permissions issue with a few customers still affected.
 
>He has a detailed spreadsheet he is working on and is putting in service now tickets if needed.

## Wed, 3/6
- DTS continued to research how folder was deleted
  - Had meeting with Amir, Dawn, Peggy and I met to discuss the network drive folder deletion

## Tue, 3/12
- Dawn sent screen shot on meeting teams chat
- This prompted DTS to discuss the security groups that were re-created

## Wed, 3/13
- Diana had a conversation with Preston about security groups to confirm that spreadsheet was accurate
- He provided another updated spreadsheet that had the "Admin" rights

## Thu, 3/14
- Dawn send 3 screen shots on meeting teams chat
- I replied
>The request is in, CTM has not completed it yet
- Matt used spreadsheet to identify which folders Dawn needed. 
  - Submitted CTM ticket `INC0374344` - Restore Admin rights to specific folders (Re-set up folder access for Dawn T. (CSD Network folders))

## Mon, 3/18
- Dawn submitted 2 screen shots saying she still didn't have access
- I replied
>We have reached out to CTM and they have yet to update the security groups. I'm sorry this is taking longer than expected.
- I messaged the team
>Did we hear back from CTM on the security access for Dawn? She just pinged me 
- CTM had not yet worked on it

## Tue, 3/19
- Amir emailed me
>Good morning Diana,
I was wondering if you had an update on when Dawn would have access to the files?

I replied
>I know Dawn has been reaching out on a follow-up on this CTM ticket. I was hoping CTM would have completed this last week, but I’ve asked Matt this morning to please follow up with the CTM contact we believe should be working on the ticket and I asked if we could have CTM resolve it today. 

>These are the CTM tickets:
• INC0374344 this is the one to re-provide her with access (current CTM ticket)
• INC0371576 this is the original ticket we submitted to set up the restricted permissions
- I asked the team to follow up with CTM
- Matt followed up with CTM in the morning
- I followed up with CTM in the afternoon
- CTM replied
>ok i have set the permissions.. it may take an hour or so to replicate throughout the domain controllers. 

I asked
>okay, so would the user have to restart their system or just wait to see if it takes in about an hour?

CTM replied
>no restart needed..  she should just be able to click on the folders and they will open up..  if they tell her access denied its bc replication has not finished..  have her try soon and if theres any issues let me know.. and you are very welcome

- I replied to Amir's email
>Hi Amir, 
We’ve gotten word that the CTM Administrator has “..set the permissions.. it may take an hour or so to replicate throughout the domain controllers.”

>I’ve asked to see if the user would have to restart, but he hasn’t replied. I’d have Dawn check in about hour to see if she’s able to access the folders now. 
- I messaged Dawn in the meeting teams chat
>Hi Dawn, 
The CTM administrators working on the ticket have set permissions, but say that it may take up to an hour for the changes to take affect. 

>You do not need to restart.  You should just be able to click on the folders and they will open up. If you're still seeing any error messages about denied access it's because the folder replication has not finished.

**Comment by dianamartin** [comment]
# 3/19/2024
- [ ] Follow up with Dawn to see if her access has changed

**Comment by maccallump** [comment]
@Matthew-M-TPW and @dianamartin will we just wait to hear from Dawn to morrow morning?

**Comment by dianamartin** [comment]
# 3/20
Closing this as user has folder access again.
