### ISSUE TITLE
Incorporate long line data in the HIN/Non-HIN in fair or better condition metric

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16356]
Once the Long Line dataset and Long Line Dates related table are added to Socrata, we need to incorporate long line data into two metrics on the SMD Performance Measure Dashboard:
- HIN Markings in fair or better condition
- Non-HIN Markings in fair or better condition

**Comment by katelunceford** [comment]
Please include me as an optional attendee to the work session @ChristinaTremel - I'm interested in the reporting needs at this level
