### ISSUE TITLE
Purchase MUI X

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#16368]
- [x] Quote and tax exemption from MUI
- [x] [ TPW purchase request](https://atd.knack.com/finance-purchasing#my-purchase-requests/purchase-request-details/660f0fb004b73d002817fbb1/)
- [x] ServiceNow purchase request
- [x] Coordinate with John & Jenny (Finance) on purchasing process
- [ ] Purchase
- [ ] Upload invoice to PR

**Comment by mddilley** [comment]
@amenity Can I close this one? I know we have this purchased, but I didn't want to close it out if you are using to track any next steps.

**Comment by amenity** [comment]
Yes! Sorry about that. 🧹
