### ISSUE TITLE
Perform various updates to team section of DTS website

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#16375]
- [ ] Change Tracy's title to "Senior Product Manager"
- [ ] Add @Craigjacobs-ATX 
- [ ] Add @grantstatton

**Comment by amenity** [comment]
@Craigjacobs @grantstatton -ATX please upload your headshot [here](https://drive.google.com/drive/u/0/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G) and add a comment to this issue with your title and preferred pronouns when you're done. 

cc/ @dianamartin @andrewshensky

**Comment by grantstatton** [comment]
GIS Analyst

he/him
