### ISSUE TITLE
Meeting Updates (3/21/24)

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#16381]
## Description
Met with PE and SMS to go over the updates to PEP and SMRT for the New Service request workflow. We brainstormed ways to streamline the requests and impoundment process including adding filters and creating reports. 

## Requested updates
- Add an option for impound
  - that choice to auto close "Close (Resolved)
  - email SMS Staff and Provider
- Stand alone device number that we could push to the SMRT app
- Add filters on My Service Requests

**Comment by patrickm02L** [comment]
### Added impoundment fields to New SR | Micro-modal
- Included
  - Impoundment checkbox
  - Number of units
  - Device ID
  - Created by
  - Created date

**Comment by dianamartin** [comment]
# 3/21/2024
## Still need to
- [ ] Add status filters on "My Assigned Service Requests" page
  - New
  - All

**Comment by patrickm02L** [comment]
# 3/22 Meeting at Rio Grande

Notes with PE at Rio Grande

### UPDATES
Make SR micro mobility as NEW
Made RED banner to stop PEO before submitting the SR

### TO DO
Need to mobile optimize the SMRT New Micro Modal SR form
Need to load all PEO officers in ACCOUNTS
Test SSO
Make table for My Assignments PEO (in SMRT)
So they can go back and impound the devices
Need to add Activity “Impoundment” and auto close: Close (Resolved)

**Comment by dianamartin** [comment]
# 3/22/24
We are doing the email notifications on the #16406, closing.
