### ISSUE TITLE
Add "replicate db" type option the hasura cluster orchestration program

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#16386]
nice to have a way to 
- replicate prod data
- choose between spinning up with prod data or local seed data

**Comment by chiaberry** [comment]
@frankhereford if you wanna take this on this sprint, after the issues you already have assigned, I say go for it!

**Comment by frankhereford** [comment]
@chiaberry wrote:
> if you wanna take this on this sprint, after the issues you already have assigned, I say go for it!

Sounds great - I'm excited and motivated get there - thanks Chia!

**Comment by frankhereford** [comment]
I have finished up my assigned issues, so I'm going to grab this one along with 16443. Thanks!
