### ISSUE TITLE
Add `archive` task to SBO overtime requests

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16416]
- Add `Archive` field and set task to update archive to yes every Sunday so starting on Monday there would be a blank slate
- Set validation to only allow form to be submitted for a requested date that's after the current date

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/16414#issuecomment-2018200422_

**Comment by ChristinaTremel** [comment]
## Build Notes
- Add `Archive` yes/no field
- Set task to run every Sunday 
   - If requested date is before current date, run task to change archive to yes
- Add filter tab to the `Overtime Requests` to show Archive
- Update other filter tabs to the `Overtime Requests` to filter out the archived records

**Comment by dianamartin** [comment]
# 3/25/24
- [x] Added `ARCHIVE` field - number
- [x] Set up task `Archive Old Requests`
  - run weekly
  - next run date 3/31/2024
    - Work Date - is before today
    - Set "Archive" to `1`
- [x] Ran test today
- [x] `4 records` were updated to `1` as they had "Work Date" fields that were before 3/25/24.

**Comment by dianamartin** [comment]
@ChristinaTremel Ready for stakeholder review

What page did we want to filter the records out?

**Comment by ChristinaTremel** [comment]
### Sync with Diana
- Checked the overtime requests after the task ran 4/14 and requests were updated as expected

**Comment by ChristinaTremel** [comment]
This was completed when working on the SBO overtime requests in April! We will review that entire feature during the SBO sprint review on 8/1. ✅
