### ISSUE TITLE
UC Folder - Create Expiration Job 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16415]
### The system should update the folder status to expired when the folder expiration date has passed. 

**Acceptance Criteria** 

- System should run a batch daily that checked for folders that are in Active status but with an expiry date in the past. 
- If the expiry date has lapsed, system should update the folder status to Expired and send an email. 
- Specifications for the email are provided below. 
- Email template: 

To: All people records in People tab, except Previous Applicant People type. 

Subject: **UC Permit Number** - **UCC #** - UC Permit Expired
 
Permit Number : 2023-123456 UC
UCC # : Folder Reference #
ROWID : Folder RSN
Project Name : Folder Name
 
Your Utility Coordination case has expired on **Expiry Date**.   
Please use the following link to request a Recertification of your Completeness Letter.
**AULCC Smartsheet** (Link to : https://app.smartsheet.com/b/form/dbdacb600e5a46a9bde80d58af1fcf25)
 
For any questions, reach out to AULCC@austintexas.gov

----
### NOTE: WE MUST RUN THE EXPIRATION BATCH JOB AFTER THIS GOES TO PROD ‼

Notes:
- [ ] Validate the existing expiration date logic
- [ ] Create an expiration batch job that:
    - Updates status to Expired 
    - Sends folder applicant an FYI email

**Comment by TracyLinder** [comment]
### Email content/template needed!

Be sure to include:

1. Your Utility Coordination Completeness Letter/Case expired today: `UC#, Project Name, ROWID, Permit ID#` (come back to this)
2. To request a recertification ... go to a webpage and follow the directions.

**Comment by vschandramouli** [comment]
Assigning to @rajeshlaunch Will work with Raj on coordination and scoping.

**Comment by vschandramouli** [comment]
Notes from meeting with Jaclyn: 
 
- Currently there is no UC expiration automation 
- Expiry date is populated when folder becomes Active 
- Create a new batch job, that checks every night if the expiry date has lapsed
- If yes, then change the folder status to expired and send out an email. 

Email template: 

To: All people records in People tab, except Previous Applicant 

Subject: **UC Permit Number** - **UCC #** - UC Permit Expired
 
Permit Number : 2023-123456 UC
UCC # : Folder Reference #
ROWID : Folder RSN
Project Name : Folder Name
 
Your Utility Coordination case has expired on **Expiry Date**.   
Please use the following link to request a Recertification of your Completeness Letter.
**AULCC Smartsheet** (Link to : https://app.smartsheet.com/b/form/dbdacb600e5a46a9bde80d58af1fcf25)
 
For any questions, reach out to AULCC@austintexas.gov

**Comment by vschandramouli** [comment]
Updated AC after scoping meeting with @rajeshlaunch, moving to Backlog.

**Comment by Nadin-Nader** [comment]
From Fridays UC Team, meeting this was marked as # 1 priority out of the cards discussed and were wanting to put in the next sprint by Greg P

**Comment by SubhaShroff** [comment]
@Nadin-Nader What should be the from Email for the emails that to be sent?

**Comment by TracyLinder** [comment]
@SubhaShroff lets go with the noreply option please.

**Comment by Nadin-Nader** [comment]
@SubhaShroff  this has been deployed to DEV please UAT

**Comment by SubhaShroff** [comment]
Thanks @Nadin-Nader  SCTASK0435296 - is created for Batch procedure deployment in DEV.

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed on DEV under **SCTASK0438760**

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed on TEST under  **SCTASK0439099**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The deployed changes are tested on TEST. The email template values replacement was not correct. SCTASK0440216 is created to promote the fixing changes to DEV. Thank you.

**Comment by SubhaShroff** [comment]
@Nadin-Nader Please create TEST deployment. Thank you.

[16415- 9785065d28785d05767ff289d6b2db1779480d32 TEST Deployment Plan.docx](https://github.com/user-attachments/files/16273428/16415-.9785065d28785d05767ff289d6b2db1779480d32.TEST.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to TEST under **SCTASK0440606**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is deployed in TEST and I tested this Batch on TEST. Ready for UAT. We can turn on the Batch, when the users are ready to test, that's just to avoid the email flooding.
Thank you.

**Comment by TracyLinder** [comment]
**Testing:**

- The batch job works in test
- I sent the notification email to Jacyln and Izzy to request approval to move to prod

**Comment by TracyLinder** [comment]
@SubhaShroff this is approved for PROD

**Comment by SubhaShroff** [comment]
@Nadin-Nader Please create a PROD promotion request. Thank you.
[16415- PROD Deployment Plan.docx](https://github.com/user-attachments/files/16353032/16415-.PROD.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
This has been sent to the CM DevOps Team to be deployed in PROD under **SCTASK0441801*

**Comment by SubhaShroff** [comment]
Thank you @Nadin-Nader. Once This is deployed, we need to get Batch Job Manual deployed in PROD.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I checked that Batch procedure is deployed in PROD. I created a Manual deployment plan for Batch job. Please create a request.
[16415 - PROD Manual Deployment Plan of Batch Job.docx](https://github.com/user-attachments/files/16444101/16415.-.PROD.Manual.Deployment.Plan.of.Batch.Job.docx)

Thank you.

**Comment by Nadin-Nader** [comment]
Manual TASK to for the CTM AMANDA team to run the batch = **SCTASK0443672**

**Comment by SubhaShroff** [comment]
@Nadin-Nader Now the Batch Job: 219 - Expire UC with past Expiry Date is deployed in PROD. 
Ready for UAT. Thank you.

**Comment by TracyLinder** [comment]
This looks to be working. I'm closing it.
