### ISSUE TITLE
Configure email notifications for SBO overtime requests

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16418]
- Configure emails for SBO overtime requests 
- Emails need to be configured for: 
   - [x] When the `Assigned To` is set on the New Overtime Request form
   - [x] When the `Assigned To` changes in the review process
   - [x] Notifying `Created By` when a decision has been made on the overtime request

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/16414#issuecomment-2018200422_

**Comment by dianamartin** [comment]
# 3/25/24
- Christina and I synced and updated the email notifications for the SBO Coordination and SBO Overtime requests so they're consistent.

**Comment by ChristinaTremel** [comment]
## Testing Email Notifications
#### New Overtime Request - Tested Assigned for your Review Emails
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/c149a047-bafc-4e06-83d5-2ef8d5324c75)

#### Review Decision has been made - Approved 
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/451586ef-430d-4993-a986-765e2c60cc1d)


## Still need to test
#### Review Decision has been made - Denied

#### Review Decision has been made - Assign to Reviewer

**Comment by ChristinaTremel** [comment]
Emailed are configured and were tested! This is complete and we will walk through the entire feature with SBO during their sprint review on 8/1. ✅
