### ISSUE TITLE
Create a script to expire all existing UC folders with an expiration in the past (LP) (On Prod)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16417]
### Create script to expire UC folders with an expiration date in the past

For all UC folders that meet the below criteria, update the folder status to EXPIRED
- Current folder status is Active only
- Expiration date is in the past

**Comment by Nadin-Nader** [comment]
Asked Jaclyn about the statuses needed and how far in the past. Awaiting response.

**Comment by Nadin-Nader** [comment]
Response from Jaclyn:

[Friday 1:02 PM] Lozano, Jaclyn
Just active status. Um the entire past

**Comment by Lpriya-LIT** [comment]
Update:
Prod - There are 2217 UC folders with expiration date in the past and folder status Active.
Working on the script to update folder status to Expired

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created request to run the script on Dev and Test , SCTASK0409181

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Script has been run on Dev and Test.
Created a request to run it on Prod database, SCTASK0410643

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader The script has been run on Prod. Folder status has been updated for all UC folders which has exiration date in the past
