### ISSUE TITLE
Help User Shavyvonne W. with New Android Device and Camera Permissions for Knack

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#16429]
Shavyvonne W. reached out with her crew member Arthur having an issue with one of the new Android "Brazos" devices assigned to their team. 

The device throws an error in Knack when using the device camera to take a photo to upload. This works on other devices. Arthur has another device on the field at this time while Shavyvonne is trying to troubleshoot. 

She has updated device and apps, allowed camera permissions to Chrome, and cleared cache.

**Comment by Matthew-M-TPW** [comment]
I called the user she said they might have figured it out. She is waiting for the person to return to the shop.

**Comment by KaroEngstrom** [comment]
[like]  Engstrom, Karo reacted to your message:
________________________________

**Comment by Matthew-M-TPW** [comment]
User responded  "I'll contact you in the morning if we are still experiencing issues with the unit. "

**Comment by Matthew-M-TPW** [comment]
"It's currently working for him. I want to thank you for reaching out to me in this morning to see if the issue had been resolved. "
