### ISSUE TITLE
Update Power BI gitbook docs for TPW - development

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#16437]
After talking to Diana, people will be given the member access automatically when requesting access to the TPW premium workspace through the DTS support ticket.
# To do
- [x] Let owners know
- [x] Update Gitbook docs

**Comment by susannegov** [comment]
Gitbook docs have been updated here: https://atd-dts.gitbook.io/atd-staff-resources/power-bi/access-power-bi-premium-workspace

**Comment by katelunceford** [comment]
Per Susanne, we will likely need to update again once the DTS Service Request is updated, but we can consider this closed for now
