### ISSUE TITLE
Resolve Blocked Dashboard Link

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#16431]
From CTM:

A citizen of the Open Data community (copied on this email) has reported experiencing an error (Access Denied) when attempting to access the interactive dashboard for Traffic and Pedestrian Signals Requests - http://transportation.austintexas.io/signal-requests
 
<img width="674" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1FKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d7334aedf7a09cf400b94f125ef0aa8513c8bd1/image.png" alt="image.png" />

 
The link to the dashboard is noted in the metadata description of the “Traffic and Pedestrian Signals Requests” dataset – https://data.austintexas.gov/d/f6qu-b7zb
 
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/81fee47b-c8f7-4d3f-b046-6197612002db)

**Comment by KaroEngstrom** [comment]
### Mon 3/25/24 
- asking Data Science team for assistance via Slack 
-

**Comment by KaroEngstrom** [comment]
### Mon 3/25/24 
- turns out this is disabled for development per #14534 
- [ ] Remove the link from the ODP dataset for now 
- [ ] Add note to the above issue to re-add the link when the dashboard goes live 
- [ ] Notify resident that this dashboard is unavailable for the time being

**Comment by ChristinaTremel** [comment]
Discussed this during backlog refinement and decided that we need to add language to this [page](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-and-Pedestrian-Signal-Requests/f6qu-b7zb/about_data) about the[ Signal Requests dashboard ](https://transportation.austintexas.io/signal-requests) being down while the program is being restructured.
