### ISSUE TITLE
Update `hasura-cluster` to use `docker compose` instead of `docker-compose`

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#16443]
Original idea: https://austininnovation.slack.com/archives/CHZE6BC6L/p1711400791773499

> We should update our `hasura-cluster` script in moped to use docker compose instead of docker-compose, now that the [compose functionality is part of the main docker project](https://www.docker.com/blog/announcing-compose-v2-general-availability/) and no longer a stand-alone project? I believe they officially stopped any development or maintenance on docker-compose in July last year. It's broken for me on this linux machine since I didn't install any legacy stuff.

**Comment by chiaberry** [comment]
could be addressed along with this https://github.com/cityofaustin/atd-data-tech/issues/16386

**Comment by frankhereford** [comment]
It totally could be wrapped into that, 100%, and I think that is a great idea. 

I am still eyeing picking up that issue as soon as I get to the bottom of my stack, and it would be totally smart to do them together -- I'm going to have to do some form of it here locally anyway, so the sooner the better in my book.
