### ISSUE TITLE
Prioritization Data Gathering: Population Density

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#16454]
Latest U.S. Census data (smallest geographical area) 

- High = 4 pts  
- Med – High = 3 pts 
- Medium = 2 pts  
- Low – Med = 1 pts 
- Low = 0 pts 

Determined based on values

**Comment by ATD-ZachB** [comment]
https://austin.maps.arcgis.com/apps/MapSeries/index.html?appid=ef7807dd9cb34d01879280133de3e7bb
See if David can pull web app and feature service info out of this web app.

**Comment by GravesW1** [comment]
Population_Projections_2040
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/Population_Projections_2040/FeatureServer

When calculating the density based form the population by shape area of each census tract, the number appear to be off by a factor for ~ 100-200ft from the density values mentioned from the previous mentioned web map.

**Comment by GravesW1** [comment]
Census 2020 Redistricting Block Data

https://austin.maps.arcgis.com/home/item.html?id=73bd0faf877548ae85f72825f48ad78c&view=list&sortOrder=desc&sortField=defaultFSOrder#overview

Shows population by block within the Austin area and surrounding counties

**Comment by ATD-ZachB** [comment]
https://austin.maps.arcgis.com/home/item.html?id=8d8fd9786b9e4df8bcbad6394e89b16f

**Comment by ATD-ZachB** [comment]
Census 2020 Redistricting Tract Data
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/TractsJoin/FeatureServer

**Comment by GravesW1** [comment]
The population density was calculated by using the feature layer: https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/TractsJoin/FeatureServer

the arcade expression used is : 2589988 * $feature.P0010001 / $feature.ALAND20
