### ISSUE TITLE
Delete UC Review Processes (LP) - (On PROD)

### ISSUE THREAD

**Issue by rajeshlaunch** [cityofaustin/atd-data-tech#16451]
The Acceptance Criteria below applies to UC folders:

- Remove the following item from both Project Sponsor option and process list:
o	XO Communications/Verizon (Fiber)

**Lumen(Brightspeed)** - Process 51146 and 51218 need to be replaced with new process for Lumen (adding to double-check requirement should be addressed as part of #16330)

**Comment by vschandramouli** [comment]
Reviewed and updated AC, moving to backlog. 

CC @Nadin-Nader @TracyLinder

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Test , Ready for UAT

**Comment by KyleErich** [comment]
@Nadin-Nader @Lpriya-LIT UAT on Prod approved, thanks!

**Comment by Lpriya-LIT** [comment]
Update - Created request for Prod deployment 
SCTASK0427986

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Prod , Ready for UAT

**Comment by KyleErich** [comment]
@Lpriya-LIT @Nadin-Nader UAT on Prod approved. Thanks!

**Comment by Nadin-Nader** [comment]
closing per approval on PROD
