### ISSUE TITLE
Prioritization Data Gathering: Proximity to traffic signal cabinets (power)

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#16460]
Traffic Signal Cabinets 

32.8 ft buffer (10m) 

Within buffer = 1pt 
Outside buffer = 0 pts 

DTS spot check data – can be fixed

**Comment by GravesW1** [comment]
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/cabinet_assets/FeatureServer

**Comment by ATD-ZachB** [comment]
Score field Added and applied to Eco_Counter_Viable_Route_Network
