### ISSUE TITLE
IT Support: Pick up stolen/recovered laptop

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#16467]
## What's the problem?

Hello Matt, Per our conversation Sgt Justin P has recovered a laptop and backpack. His phone number is 

## What did you do to resolve the issue
Talked to Scott and the Sargent is dropping it off at his house

**Comment by scottreedy** [comment]
Picked up Laptop - 7480 
PWD-99VZ5M2-N1
Antonio Mendoza's
Water Damaged - will retire

**Comment by scottreedy** [comment]
Picked up Laptop - 7480

Antonio M
Water Damaged - will retire
