### ISSUE TITLE
 Eco Counter Prioritization Data Gathering: Transit stops

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#16462]
CapMetro Bus, Rapid, Rail, Express system map 

Pull ATP Services first then External COA Cap Metro services for remaining data sets.

Points on map

**Comment by GravesW1** [comment]
Cap Metro Rapid Stops:
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/CapMetroRapidStops/FeatureServer
