### ISSUE TITLE
Prioritization Data Gathering: Proximity to MetroRapid bus stops (power)

### ISSUE THREAD

**Issue by ATD-ZachB** [cityofaustin/atd-data-tech#16461]
CapMetro Rapid stops 

1. 32.8 ft buffer (10m) 
- Within buffer = 1pt 
- Outside buffer = 0 pts 

DTS spot check data

**Comment by GravesW1** [comment]
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/CapMetroRapidStops/FeatureServer
