### ISSUE TITLE
EzMaxMobile Training - Rudy L.

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16470]
Please add the date of when each task has been completed. 

- [x] Give access to Rudy L. to EzMaxMobile
- [ ] Schedule a day to assist with installation and set up of the mobile app 
- [ ] Schedule a day to provide basic navigation

**Comment by ReneVarg25** [comment]
### 4/9/2024
- Granted EZMax Access

**Comment by ReneVarg25** [comment]
### 4/19/2024
No response was given. Scheduled for May 1st at 1:00 PM as that time was available for both of us per Outlook Calendars.

**Comment by ReneVarg25** [comment]
### 4/29/2024
User cancelled training request as they received it via another user, and only needed to learn to upload attachments to Maximo. Informed user to reach out/submit another request should they need more training or need to resolve other issues.
