### ISSUE TITLE
Updates From OCE Stakeholder Review 3/26/24

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16472]
# Feedback/Updates
- [x] For Adding a plant, Plant Type - Keep only Concrete Mix and HMAC Mix. Remove Flexible Base Materials option
- [x] Certification Date is for Concrete Mix and HMAC. Currently it is only for Concrete
- [x] HMAC/Concrete needs Plant when add approved mix (needs required). Flexible Base does not need a plant
- [x] Michael said to keep `Status Comments` to leave comment related to status
- [x] Remove "Add PDF" in approved mix table
- [x] Add pop-up to add attachment in producer ADMIN page

# Non-actionable feedback
- [ ] For HMAC Type, removed fields (Class, Cement Type" and replace with other fields (OCE said will provide those fields)
- [ ] Saroj said can provide text for the email notification for OCE and Producer

**Comment by susannegov** [comment]
Ready for review/QA

**Comment by TracyLinder** [comment]
Good to close.
