### ISSUE TITLE
Create Mitigation Map Schema

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16481]
### All tasks necessary to create the Mitigation Web Map prototype

- Map locations
- Setup schema based on data mapping spreadsheets

**Comment by andrewshensky** [comment]
4/12- The data from Chrispin's spreadsheet has been converted to a geospatial format and is published to AGOL. The geospatial data is available through the link below:

https://austin.maps.arcgis.com/home/item.html?id=a976699b64de4166bc15f653050a609f
