### ISSUE TITLE
Create Mitigation Web Map Dashboard

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16482]

**Comment by andrewshensky** [comment]
The data mapped as part of #16481 has been added to the prototype dashboard with various filtering capabilities included. It will be necessary to review this prototype in our next meeting to define what functionality and capabilities are actually needed. The prototype dashboard in linked below:

https://austin.maps.arcgis.com/apps/dashboards/b89c344a9fd54e73a10d2b651c9c928b

**Comment by TracyLinder** [comment]
### Map Prototype Feedback:

**Filters:**
- [ ] Add council districts
- [ ] Add SIF areas
- [ ] Add Mitigation Fee Types
- [ ] Remove TIA types

**Other:**
- [ ] Able to see council districts and SIF areas on the map
- [ ] Open text search
- [ ] Search by street/address


**Modal:**
- [ ] Should only include case level information

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/3c28bf18-aedd-44eb-b3a3-b51fd316a319)

**Comment by andrewshensky** [comment]
Closing this issue as primary work for the dashboard has been completed. All subsequent modifications can be tracked through separate issues. Link to dashboard is below:
https://austin.maps.arcgis.com/apps/dashboards/b89c344a9fd54e73a10d2b651c9c928b
