### ISSUE TITLE
Create Mitigation Map Data Documentation

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16480]
### Create data mapping spreadsheets to be used by DTS-GEO for the mitigation map

Single spreadsheet on TIA Mitigation Object

- Feature ID (street segments and intersections)
- Project ID will be on each mitigation line item

**Comment by ChrispinP** [comment]
Prepared spreadsheet of 108 sample records and sent via Slack.

Pending any further action
