### ISSUE TITLE
OCE Mixes Construction Inspector Page View

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16502]
### Create page view to be used by Construction Inspections group

**Comment by TracyLinder** [comment]
We want to speak to a construction inspector directly to gather their needs

**Comment by TracyLinder** [comment]
I asked Saroj for a contact with the inspection group. The link i had to the sharepoint list for the inspectors doesn't work anymore.

**Comment by dianamartin** [comment]
# 10/14/24
View Mixes tab
- [ ] Set user roles to `OCE User`
- [ ] Test that all tables are "Read Only"

Update View Producer Details
- [ ]  No Data - Change to “No notification logs added”
- [ ]  No Data - Change to “No attachments added”
- [ ]  No Data - Change to “No plants added”
- [ ]  No Data - Change to “No approve mixes added”

**Comment by susannegov** [comment]
- Did changes for Update View Producer Details for View Mixes and Manage Mixes menu

**Comment by dianamartin** [comment]
# 10/15/2024
- [x] Saw under "View Producers" page changes were made 
- [ ] Saw under "Manage Producers" page changes were made
