### ISSUE TITLE
Update OCE Mixes Attachment Features

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16500]
# Attachment Feedback
- [x] Move Add attachment to above the attachment table in "Producer details"
- [x] Add `Attachment Status` to attachment object table
- [x] Add `Attachment Status` to attachment table in View Producer details
- [x] Michael proposes attachments making the Approved mix for PDF optional (not required) since it could apply to all approved mixes.
- [x] Add `Attachment Type` called "Mix Design Summary Table"
- [x] Add `Attachement Type` "Other"
- [x] Make `Attachment Type` required
- [x] Expressed interest for flagging an attachment as active/inactive.
- [x] Ability to modify attachment as inactive
- [x] Ability to edit Attachment in Attachment table

# 04/09
Added new login page for Admin only - https://atd.knack.com/oce#attachments-inventory/?view_67_filters=%5B%5D
- [x] Add `Attachments | Login` page and button
- [x] Create `Attachments` table grid view
- [x] Add `Archive` button for attachments

**Comment by susannegov** [comment]
Ready for review/qa
