### ISSUE TITLE
OCE Mixes Create Account Management Features

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16501]
# Accounts

**We will have the following roles:**

1. `ESR Editor `(Saroj's team): Can see & edit: All Mix tables/objects
2. `ESR Viewer`: Can view and download mix data and attachments
3. `OCE Portal Admin`: Can manage user accounts for the OCE Portal
4. `KNACK Admin`: Can edit everything that exists in the OCE Portal

 
- [x] Build `Account Administration` page
- [x] Create`Viewer` role for viewing content but not editing it

Check SMD app account management page

**Comment by TracyLinder** [comment]
Per Susanne, the work is done so I'm moving this to Review/QA

**Comment by susannegov** [comment]
# Login Settings
Roles with permissions
- Admin
- Account Admin
- Knack Admin

Admin page link: https://atd.knack.com/oce#account-admin/

**Comment by TracyLinder** [comment]
### Backlog refinement
- It is not possible for KNACK to allow internal only viewing without an account. The only non-account option would make the portal open to the public. 
- Consider a workflow where internal users register for a new account and it self-approves (if the validation rules can be applied) so OCE doesn't have to review access for every city employee who wants to see the mix data. 
    - Validation rule: austintexas.gov is the email domain/ending 
    - This would set the user to `Internal ESR Viewer`

**Comment by TracyLinder** [comment]
I created #16958 for the account automation piece discussed.

**Comment by TracyLinder** [comment]
@susannegov I updated the issue description with the new roles and I'm putting this back on deck. Thank you!

**Comment by susannegov** [comment]
# 5/16 change
- [x] Added ESR Editor (Saroj's team): Can see & edit: All Mix tables/objects
- [x] `ESR Viewer` : Can view and download mix data and attachments
- [x] Renamed to `OCE Portal Admin` : Can manage user accounts for the OCE Portal
- [x] KNACK Admin: Can edit everything that exists in the OCE Portal
   - This selection option is hidden to `OCE Portal Admin` currently

**Comment by susannegov** [comment]
@TracyLinder this is ready for review/QA. I noticed in the next steps that "Michael to discuss with Saroj". Is it about who will have ESR Editor privileges? I think it would be a good opportunity to test letting the OCE Portal Admin set the User role for `ESR Editor`

**Comment by susannegov** [comment]
Changed ESR Viewer to OCE Viewer

**Comment by TracyLinder** [comment]
Looks good to close.
