### ISSUE TITLE
Traffic Count Data Web Application - Migration from WAB to xB

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#16505]
As part of Esri's decommissioning of web app builder in favor of experience builder, the web application below will need to be migrated to experience builder. TED has requested various changes to the current application so this provides a good opportunity to transition the application.

https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=adb9784e11244a59bfa1d4e9a15f6118

**Comment by andrewshensky** [comment]
@DanielStover can you add a link below to the Experience Builder version of this application you are currently working on?

**Comment by DanielStover** [comment]
https://experience.arcgis.com/experience/c197a04a35f949af873dc72d02219745/
