### ISSUE TITLE
Maximo Report Request [Modification] SBO Material Used for Completed Guard Rail Work Orders (Monthly Operational Performance Measures)

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16516]
Report is totaling #s for each line rather than each work order for feet of guardrail.

**Comment by adry-martinez** [comment]
<html>
<body>
<p>Guardrail report - duplicating report lines</p>
<p>Guardrail repair/re-touching data needs to be collected:</p>
<p>base off of labor, specifications - length of repair.</p>

Problem Code | Description | Hierarchy | CSR | Remedy | Situation | Assigned |  
-- | -- | -- | -- | -- | -- | -- | --
DAMAGED | Damaged | Parent/Child | X | Repaired | true damaged guardrail that needs to be repaired | SBODIST | CSR Response team first, then after assessment, use FF2, then re-assessed for future project, if any, by assigned group
INSTALL | Install New | Parent |   |   | new installation | SBOIMG |  
INTLREMV | Intentional Removal |   |   |   |   |   |  
INVWKREQ | Investigate Work Request | Child | X |   |   |   |  
NOCMPBAR | Non-Compliant Barrier | Parent |   |   | whenever an unsafe guardrail that needs to be in compliance per TXDOT standards | SBODISTS |  
REWORK | Rework |   |   |   |   |   |  
SFTYVEG | Guardrail Vegetation |   |   |   | maintain vegetation around the guardrail for visibility | SBODISTS |  
  |   |   |   |   |   |   |  
All CSR-WO for guardrails should come in as INVWKREQ with remedy either no problem found or create repair work order (parent) |   |   |   |   |   |   |  
CSR response team will FF2 to South or to Bridge for assessment |   |   |   |   |   |   |  
All work is done on Parent or standalone WO for SBODISTS |   |   |   |   |   |   |  



</body>
</html>

**Comment by rebekkabry** [comment]
# 5/20/24 Notes with CTM

- The sum is the only thing off on this report. Currently adding the Parent data and not the child data. 
- Currently on list for Nick, could hand over Ganesh? 
- @GaneshKamarapu discuss internally on handover and next step? 
- New assessment of request to access if we have current access to accommodate

**Comment by GaneshKamarapu** [comment]
@rebekkabry @adry-martinez  I have updated the report and uploaded in Prod and is ready for QA.

**Comment by adry-martinez** [comment]
### May 30, 2024
Users confirmed report meets requirements. Issue closed.
