### ISSUE TITLE
Hide inactive users by default on Staff page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#16519]
Right now, one has to set a filter to limit the "Staff" page to active users and see that total number at the bottom. 

We currently have 44 deactivated users, and at a glance I can see that there are more who need to be deactivated.

**Comment by amenity** [comment]
@chiaberry - do non-admins see the staff page?

**Comment by chiaberry** [comment]
they do see the staff page, the difference is they do not see buttons to be able to edit a user

**Comment by amenity** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data--Technology-Services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/16519?planning-poker) with Zenhub @frankhereford @chiaberry @tillyw @roseeichelmann @mddilley

**Comment by roseeichelmann** [comment]
@chiaberry @amenity should we be giving feedback to the user that results are being limited to Active = "Yes", like by adding a default filter like so when you visit the page that users can delete if they want to see all users? Kinda seems clunky. Or i could add like a radio button at the top that is a switch for only showing active users and default it to on?
![image](https://github.com/cityofaustin/atd-data-tech/assets/67130963/2b415b08-c954-4cd2-a9ce-8fb0783640db)
 Bc if i just remove non active users from the list and dont do anything else how would someone show all active and inactive users if thats what they want?

**Comment by amenity** [comment]
@roseeichelmann - they can do that with a filter. 
<img width="1230" alt="Screenshot 2024-04-30 at 2 06 49 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/b1ef27cd-5b17-4b23-97e2-3fcf4d8ef563">

**Comment by amenity** [comment]
@roseeichelmann - sorry, rushing comments. I think showing the filter—so the page looks like your screenshot by default—is fine!
