### ISSUE TITLE
IT Support: Please check the lab computers in the back at St. Elmo

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#16512]
KRAMER, CAMERON - 8700/8900, PDC, TOWNVIEW, RIO, OTC, TOOMEY, BOP, ST. ELMO, DALTON, BEN WHITE

## Device & User Information (first name and last initial, no last names)
Matt M
## What's the problem?

Check the users and storage on the computer 
perform updates

**Comment by Vaishnav1397** [comment]
Will look into and check the status.

**Comment by Vaishnav1397** [comment]
There are different user accounts added in the workstations, as they login for update of timesheets etc. Last time we tried to remove the user's profile and ensure all the systems are working well. I will again check on system updates when the systems are not in use and ensure everything is working well.

**Comment by Vaishnav1397** [comment]
Checked over few systems, deleted the user profiles and made required updated, reimaging of few machines was in need and then moved over to domain, there might be a requirement to swap old 7040's which were not working.

**Comment by Matthew-M-TPW** [comment]
Reimaged 2 desktops

**Comment by Craigjacobs-ATX** [comment]
re imaged 2 lab desktop , replaced one desktop.

**Comment by Matthew-M-TPW** [comment]
Desktop was replaced 

Everything is working properly
