### ISSUE TITLE
Prototype Mobility Services Application

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#16523]
# 3/28 
- [x] Create new `Mobility-Services` [knack app](https://atd.knack.com/mobility-services#home/) 
- [x] Configure theme & colors from other apps
- [ ] Add to DTS App Inventory
- [x] Create splash page for Chauffeur
- [ ] Create initial application form #16565

**Comment by dianamartin** [comment]
# 4/11/2024
- [ ] Finish up splash page
- [ ] Structure like TDS "Available Services [TDS Services](https://atd.knack.com/development-services#customer-portal/services/traffic-impact-analysis-determination/)

**Comment by dianamartin** [comment]
# 4/16/2024
Created new pages
- [x] Portal
- [x] Services
- [x] Available Services
- [x] Chauffeur's Permit
- [x] Commercial Vehicle Loading
- [x] Charter Bus Service Permit
- [x] Operating Authority
- [x] Volunteer Accessible Parking Program

**Comment by patrickm02L** [comment]
Good to go!
