### ISSUE TITLE
Add "Secondary name" column to Projects page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#16521]
- [x] Add a column for "Full name" that displays `project_name` + `-` + `project_name_secondary` as a hyperlink to the project, the same way the "Name" field shows now
- [x] Remove the project url hyperlink from the "Name" data display and make the column hidden by default 
- [x] Add a column for "Secondary name" after "Name" and make the column hidden by default 
- [x] Add advanced search filter for "Full name" 
- [x] Add advanced search filter for "Secondary name"
- [x] Add "Full name" to CSV download
- [x] Add "Secondary name" to CSV download

**Comment by chiaberry** [comment]
Also add secondary name to activity log
- Added new secondary name
- Edited existing secondary name
- removed name?

**Comment by amenity** [comment]
@chiaberry @frankhereford - shall I put the activity log part in a separate issue?

**Comment by chiaberry** [comment]
@amenity I will create the activity log issue!

**Comment by mddilley** [comment]
@amenity @chiaberry When running through test steps on this, I wondered if we want to update the simple search box to use the new full name field or leave it using the `project_name` field?

<img width="629" alt="Screenshot 2024-04-10 at 2 42 16 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/37249039/bd39d30a-aaf7-4607-a406-cb5861b989d9">

**Comment by amenity** [comment]
@mddilley -- oooh, good catch. I'd love to update that as well... I think it's fine to get that in our next release and not hold this up. @chiaberry?

**Comment by mddilley** [comment]
thanks! just caught that i modified this behavior w/o realizing it - i'll fix it to use the full name before i request reviews!
