### ISSUE TITLE
Build a 3-1-1 Flex Note Explorer in PBI

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#16547]
Flex notes provide a deeper layer of information and could be useful for users to identify trends/hot spots. For example: 
- Parking CSR flex notes include the type of violation

[3-1-1 CSR Response PBI dashboard](https://app.powerbigov.us/links/Mg-BtdxjEb?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=4d481687-4801-492e-a40b-30e1c6d8808b)

**Comment by Charlie-Henry** [comment]
I created a separate report just for poking around with the flex notes as they can be pretty confusing
[Report](https://app.powerbigov.us/links/WLJgNa4Icg?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare)

Some examples of use cases:
- [CSRs for parking in the bike lane](https://app.powerbigov.us/links/WLJgNa4Icg?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=69cea5b0-14a3-4e03-a4c6-b945d9bea57e)
- [CSRs for Traffic signals on flash](https://app.powerbigov.us/links/WLJgNa4Icg?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=4e14158b-1119-488f-be9b-a0ba7f2031a2)

**Comment by Charlie-Henry** [comment]
Pushed to our production workspace here:
https://app.powerbigov.us/links/G33XVmB0uF?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare
