### ISSUE TITLE
New UC Folder Info: Managed by CDS? (SS) (UAT on PROD Approved)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16546]
### Create new folder info for UC folder: Managed by CDS?

Requested by: Greg P.
UAT Approval should come from Izzy

- **Create new valid info**
    - Boolean
    - Description "Managed by CDS?" 
    - Info Group: Project Information

- **Add info to UC folder:**
    - Required for setup/issuance: No 
    - Add to portal: No

**Comment by TracyLinder** [comment]
@Vaishnav1397 can facilitate UAT for this; he was with me for discovery.

**Comment by KyleErich** [comment]
Since the acronym "CDS" isn't quite well known yet, I would advise that we have a popup window or some other callout clarifying that this refers to Capital Delivery Services, otherwise this could cause confusion.

**Comment by TracyLinder** [comment]
I agree with Kyle's note above, so I updated the AC.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0409467**

**Comment by SubhaShroff** [comment]
Thank you @Nadin-Nader. I tested this on DEV. Please create a TEST deployment request. 
[16546 - 52065aa1b8872c237eb6c3d84a92b69f5fa18bef TEST Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/14906817/16546.-.52065aa1b8872c237eb6c3d84a92b69f5fa18bef.TEST.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to TEST under **SCTASK0410587**

**Comment by SubhaShroff** [comment]
@Nadin-Nader This is deployed in TEST and tested. Ready for UAT. Thank you.

**Comment by KyleErich** [comment]
@SubhaShroff @Nadin-Nader UAT on Test approved, thank you.

**Comment by SubhaShroff** [comment]
Thank you Kyle.
@Nadin-Nader  please create a PROD deployment request for. Below is the deployment plan. Thanks.
 [16546 - 52065aa1b8872c237eb6c3d84a92b69f5fa18bef PROD Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/14933277/16546.-.52065aa1b8872c237eb6c3d84a92b69f5fa18bef.PROD.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0411338**

**Comment by SubhaShroff** [comment]
Thank you @Nadin-Nader. I see its in PROD now. Ready to review on PROD. 
CC: @KyleErich

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff UAT on PROD approved. Thanks!

**Comment by Nadin-Nader** [comment]
approved on PROD, closing
