### ISSUE TITLE
New UC Folder Info: CIP Project Manager Email (SS) (Deploying to PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16559]
### Create new valid info for "CIP Project Manager Email"

Requested by: Greg P.
UAT Approval should come from Izzy

- **Create new valid info**
    - Alphanumerical 
    - Description "CIP Project Manager Email" 
    - Info Group: Project Information

- **Add info to UC folder:**
    - Required for setup/issuance: No 
    - Add to portal: No

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0409114**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is deployed in DEV and I have tested it. SCTASK0409977 - TEST deployment request is raised. Thank you.

**Comment by TracyLinder** [comment]
Kyle said he can test this.

**Comment by KyleErich** [comment]
@TracyLinder @Nadin-Nader @SubhaShroff UAT approved on TEST.

**Comment by SubhaShroff** [comment]
Thank you Kyle.
@Nadin-Nader  Please raise a PROD deployment request. Thanks.
[16559 - 9893e71fcd219f5f62995255d31ec51a6b52e5ce PROD Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/14998947/16559.-.9893e71fcd219f5f62995255d31ec51a6b52e5ce.PROD.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0412922**

**Comment by SubhaShroff** [comment]
@Nadin-Nader Thank you. This is promoted to PROD. Ready for review. Thanks.
CC: @KyleErich

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff UAT on PROD approved. Thank you!

**Comment by Nadin-Nader** [comment]
approved on PROD, closing
