### ISSUE TITLE
[Feature] Application Form MVP

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#16565]
## Description

Create a digital version of the current [paper application](https://www.austintexas.gov/sites/default/files/files/Transportation/Ground_Transportation/Chauffeur_Permit_Application_112023.pdf)
- page 1 - Checklist, FAQ
- page 2 - Background Info & short answer
- page 3 - short answer continued
- page 4 - short answer continued, signature page

#### `application` table (object)
- Applicant Name: (connect to account table)
- Social Security No: number
- Texas Driver's License #: (connect to account table)
- Email Address: (connect to account table)
- Telephone No: number
- Address: address
- Number of years of residency: number
- States of residence: short text
- Are you a citizen of the US: multiple choice
- Convicted of crimes: multiple choice, conditional short text if `Yes`
- Convicted of other criminal offenses: multiple choice, conditional short text if `Yes`
- Presently under indictment: multiple choice, conditional short text if `Yes`
- Traffic violation: multiple choice, conditional short text if `Yes`
- Describe your experience: paragraph
- Signature: text, date/timestamp
- Digital Notarization (review previous examples of this)

## Note
Review [Miro board](https://miro.com/app/board/uXjVNj7uM5A=/) process workflow as needed to get clarity on what needs to be included in the application

**Comment by dianamartin** [comment]
# 4/11/2024
## Build Notes

#### `application` table (object)
#### SECTION 1: Applicant Information
- Applicant Name: (connect to account table)
- Texas Driver's License #: (connect to account table)
- Email Address: (connect to account table)

- [ ] - Are you a citizen of the US: multiple choice (will need this for Required Documents, counts) (REQUIRED)
  - [ ] Have this be trigger to display "SSN"
- `Social Security No`: number 
  - set validation 3 digits - 2 digits - 4 digits
- Date of Birth
- `Telephone No`: number (REQUIRED)
- Address: address (REQUIRED)
- Number of years of residency: number (REQUIRED)
  - Q: did we want to have months?
- States of residence: Multi-choice
  - Q: do we want to include territories

#### SECTION 2: Background Information
- Convicted of crimes: multiple choice, conditional short text if `Yes`
- Convicted of other criminal offenses: multiple choice, conditional short text if `Yes`
- Presently under indictment: multiple choice, conditional short text if `Yes`
- Traffic violation: multiple choice, conditional short text if `Yes`
- Describe your experience: paragraph

#### SIGNATURE & NOTORIZATION
- Signature: text, date/timestamp
- Digital Notarization (review previous examples of this)

Q: Do we want them to print out the signature page only or the entire application?
- [ ] Feature: Page needs to have print page enabled

- This page requires notarization
- We do not want you to sign your application until you are in front of the notary.  

NOTE: If you would like for our office to notarize your application, there will be a $6.00 service fee added to the cost of the Chauffeur Permit. 

- [ ] "Update Application form"
- [ ] Add field "How do you want to notarize this application?"
CHOICE FIELDS
- [ ] I want to get this notarized on my own 
   - [ ] SUBMITTAL MESSAGE: You must print this page out when you get it this page notarized
- [ ] I want to use the City of Austin notary on site - Multi-choice (REQUIRED)
   - [ ] SUBMITTAL MESSAGE: You can schedule an appointment at the office once your application has been reviewed 
   - Q: How do you want the applicant to do this?

**Comment by dianamartin** [comment]
# 4/16/24
I was working on the splash pages and just built the first section of the application to test functionality
- [x] Created `application` object
- [x] Created audit fields
- [x] Added some fields, stopped at "Texas residency" - Section 2, still needs to be configured
- [x] Configured record rules
- [ ] This should be a cascading application page, need a child page after the first page submission

**Comment by patrickm02L** [comment]
## 4/17 Planning
- Background page, submit rule to add child page

<img width="1743" alt="Screenshot 2024-04-17 at 11 13 18 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/5566727/05d58c04-98aa-4c9d-b3d9-d484c92502ee">

**Comment by patrickm02L** [comment]
## 4/24/24 Refinement. 
The has been completed.
<img width="1131" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkdOQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f789e5ba393520e7668c6ffe773645bc813d055/Screenshot%202024-04-24%20at%2010.44.36%E2%80%AFAM.png" alt="Screenshot 2024-04-24 at 10.44.36 AM.png" />

**Comment by patrickm02L** [comment]
## 4/24/24 Refinement
- Need to create a second page for background
- 3rd page is the details page with a required documents section #16891 (roll this into this Issue)
- button to submit (like a big save button)

**Comment by susannegov** [comment]
# 4/30
## To do:
- [ ] Hide Section 1 details view in section 2 (required attachments) of page

**Comment by susannegov** [comment]
# 5/7
- TX Driving records: https://atd.knack.com/mobility-services#3a-certified-texas-driving-record/
-

**Comment by susannegov** [comment]
## To do
- [ ] Add the last step page form signature ready for review

### Section 3
Add field "How do you want to notarize this application?"
CHOICE FIELDS
 I want to get this notarized on my own
 SUBMITTAL MESSAGE: You must print this page out when you get it this page notarized
 I want to use the City of Austin notary on site - Multi-choice (REQUIRED)
 SUBMITTAL MESSAGE: You can schedule an appointment at the office once your application has been reviewed
Q: How do you want the applicant to do this?

- [ ] Validation of attachments in the following formats:
   - [ ] .png .jpg .jpeg .pdf
   - [ ] 150 MB file limit?
- [ ] Need to figure out how to add connected record when edit application has changed (new issue)

**Comment by patrickm02L** [comment]
## 5/9/24
We reviewed the Application Form with Mobility Services team, and have notes on their feedback including in the meeting notes [here](https://docs.google.com/document/d/1TYY6iDZmwbczXs9fjF_TLzSHzju33NBXd9R8l04VeHU/edit#heading=h.17f38ie03pw2).

_____ is the Issue for follow-up updates.
