### ISSUE TITLE
Help User Chris V. with Accessing ODP Data in ArcGIS Pro

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#16569]
### Fri 3/29/24

From user Christiane V. via CTM: 

"I am having trouble viewing GIS data for the sidewalks and urban trails in the formats available through our Open Data Portal. Bringing the csv into ArcGIS Pro, I can see that the geometry is stored in a single field as a multiline string. The DTS GIS team wrote a script to parse the coordinates, but we couldn’t figure out an easier way to view the data. This method is not accessible or reasonable to expect of the public. Please let me know if I am missing something and if there is an easier way to view this data. Otherwise, I think we need to get a new format available for these layers.
Sidewalks link: https://data.austintexas.gov/dataset/Sidewalks/pc5y-5bpw
Urban Trails link: https://data.austintexas.gov/dataset/TRANSPORTATION_urban_trails_network/bxbe-ndaw”"

**Comment by andrewshensky** [comment]
Followed up with Chris, planning to sync with her on Monday

**Comment by andrewshensky** [comment]
Message from Chris this morning regarding the new ODP url's that were provided

> oh nice! I didn't see that distinction between map and layer, I was going off of the most update date. I'm seeing the same exists for urban trails too. Thanks for showing me, that resolves my issue.
