### ISSUE TITLE
[Feature] Account Creation

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#16564]
## Description

The goal is for anyone to be able to create an account independently without Mobility Services manually setting them up.

#### User Account Considerations

- Set up any required fields for name, contact info, etc.
- Determine if approval is needed after account creation
- Capture the user's driver's license number as a unique identifier
   - Potentially utilizing the driver's license number and state to concatenate as an identifier

## Note
- Mobility Services currently has a list of permitted chauffeurs that they export from their system, which could potentially be imported

**Comment by dianamartin** [comment]
# 4/11/2024
- [x] Create Account object table - created during sync
- [ ] Create drop down menu "Account Details" - like in SMRT 
- [ ] Create page for "My Account" - set user role to "User"
- [ ] Create user roles
  - [ ] Knack Admin (DTS)
  - [ ] Reviewer (TPW Staff)
  - [ ] User (Chauffeur)

**Comment by patrickm02L** [comment]
## 5/8/24 Refinement
This Issue was completed by the work in #16881
