### ISSUE TITLE
Add UC Info to Portal: Managed by CDS? (LP) - (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16568]
- Add to UC portal application
- Not required
- Add help text to define what CDS is `Is Capital Delivery Services managing this Capital Improvement Project?`

Stakeholders: Greg Pepper, Kyle for the help text

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Comitted changes and requested for Dev and Test Deployment, SCTASK0471393

**Comment by Lpriya-LIT** [comment]
<img width="1374" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVBlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ca00e2db5ee2b391a720e1f5e9e29b78e79d5c3/image.png" alt="image.png" />

**Comment by KyleErich** [comment]
@Nadin-Nader @Lpriya-LIT UAT on Test approved. Thanks!

**Comment by Lpriya-LIT** [comment]
Update - Created Prod deployment request , SCTASK0472832

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Prod , Ready for UAT

**Comment by KyleErich** [comment]
@Nadin-Nader @Lpriya-LIT UAT on Prod approved, thank you!

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been approved by Kyle to go to PROD

**Comment by Nadin-Nader** [comment]
Approved. closing
