### ISSUE TITLE
4 iPad order for Meters

### ISSUE THREAD

**Issue by scottreedy** [cityofaustin/atd-data-tech#16604]

**Comment by scottreedy** [comment]
04-04-2024 14:04:19 CDT - Erik Estrada Additional comments
@Scott Reedy These four Ipad minis' are ready for pick-up @ 1006 Smith Road. Please see service desk for devices.
________________________________________

**Comment by scottreedy** [comment]
REQ0179310 - SCTASK0406804 - 4 iPad mini's for Meters 03/26/2024
AT&T Order #: 55-811000008308188
iPad Mini's (6th Gen) entered into Knack Inventory Database
512-435-1844
512-436-2034
512-461-4397
512-460-1152

**Comment by ChrispinP** [comment]
Created https://github.com/cityofaustin/atd-data-tech/issues/17031 to handle the setup for these devices. Thanks Scott.
