### ISSUE TITLE
KNACK Record Counts for ECM (ROW, TDS)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16619]
### The ECM SOW needs to include an estimated number of KNACK records that could be migrated to the new ECM solution. 

- [x] Add counts to [this excel](https://cityofaustin-my.sharepoint.com/:x:/r/personal/tracy_linder_austintexas_gov/Documents/Projects/TPW-ECM%20Folder/KNACK%20Apps%20to%20Migrate.xlsx?d=wb3d22831622e4651ba48154c4bdad7d2&csf=1&web=1&e=SKMuRs).

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/409b8301-ca30-4f28-8ffa-4ccfc98d016f)

**Comment by ChrispinP** [comment]
Added Raw and Submitted counts to the spreadsheet. Pending any further action

**Comment by TracyLinder** [comment]
Looks good. Thanks @ChrispinP
