### ISSUE TITLE
Update paginated report with new data sources

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16628]
The canvas reg object was deprecated in Knack and now draft and approved regs are both in the same object. We also had fields that were renamed. 

- We were able to fix the PowerBI report that sources the paginated report, but now we need to repair both the draft and approved traffic register paginated reports! 

- Once paginated reports are fixed, we will need to turn on the refresh in Power Automate and relink the reports within the Traffic Register knack application.

**Comment by ChrispinP** [comment]
We updated the Paginated Report data sources, updated the report designs, published to PowerBI, deployed to DTS Test, and turned on PowerAutomate refresh.

Complete, pending any followup
