### ISSUE TITLE
Customer Accounts Pre-Fill Data for TCP Case Mgmt Upgrade

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#16632]
### Repeatable application fields that could be stored in the Organization object for TCP 
- ABC Portal email 
- ABC User ID

**Comment by ChrispinP** [comment]
Updated the Edit Organization form & Orgnization Details page to include ABC information & description. Made a connection from the TCP Project to the Org object. Added rules to update connected projects with the ABC information from the Org when updated.

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/905b6ddd-0e75-46c5-84d9-2202db509437)

Adding the Organization & ABC fields as read only to the Edit TCP Project form for visibility

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/04113f7c-1737-47ca-97cc-a14489d41c42)

**Comment by ChrispinP** [comment]
Tested and working, updates all connected projects for the Organization with the updated ABC info.

I also transferred the ABC language from the current application flows with a button link that allows users to register for an ABC account.
![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/661b26b2-f683-4926-9d2b-6e99720243ee)

Ready to Review

**Comment by ChrispinP** [comment]
No further actionables, closing
