### ISSUE TITLE
Set up PBI dataflow for TPW Work Orders

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#16656]
Related to the work completed in creating a Power BI dataflow for CSRs: [#16244](https://github.com/cityofaustin/atd-data-tech/issues/16244)

We identified a new dataflow which might be useful. All of the work orders from TPW's disparate systems. We could roll out a dashboard as well.

Existing Work orders:
- [Road markings work orders](https://data.austintexas.gov/Transportation-and-Mobility/Roadway-Markings-Work-Orders/nyhn-669r/about_data)
- [Street sign work orders](https://data.austintexas.gov/Transportation-and-Mobility/Street-Sign-Work-Orders/ivss-na93/about_data)
- [Road markings contractor work orders](https://data.austintexas.gov/Transportation-and-Mobility/Roadway-Markings-Contractor-Work-Orders/5dex-63ir/about_data)
- [Traffic signal work orders](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Signal-Work-Orders/4qmj-36nv/about_data)
- + anything we can get out of maximo?

**Comment by katelunceford** [comment]
- @Charlie-Henry will identify common fields in Knack, 
- Ask Dave A. if those exist in MAXIMO + query to get them out
- @susannegov check with Lance about the gateway 

If this works, we could explore setting up a DTS gateway

**Comment by katelunceford** [comment]
Notes from DSBR on 4/24/24

- ETL grabs the Maximo work order table + joins it with the segment ID of where the work occurred
- In SBO, location data on work orders seems to be just segments (not intersections) 
- There is a service address for CSRs, which is then tied to a segment
- Different work orders use different geometries to it will be hard to map

**Comment by katelunceford** [comment]
Notes from [Data Science Sprint Planning](https://docs.google.com/document/d/16RBJStu65lHTQa_MVYde7jmortp1ako1P1-A6mPcNOg/edit) on 5/1/24
- Charlie wrote a script for pull requests that sets up Maximo ETL
- This is a good starting point that gets us
   - Work orders
   - Where they happened

**Comment by Charlie-Henry** [comment]
Have our work orders data flow created here: https://app.powerbigov.us/groups/ab42d64d-b1f1-4259-95c8-acede63e7d8c/settings/dataflows/e5da9b63-218d-4777-a02b-e080f1f9fcc6

Just need to merge our airflow PR then we're good to deploy this to production and close this out!
