### ISSUE TITLE
Out-of-date council district layer(s) in ODP

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#16662]
We need a Socrata admin to update a handful of outdate layers in Socrata. The council districts represented there are out of date (were updated for the 2022 election).

The unfortunate thing is these are all part of our [curated regions](https://datahub.austintexas.gov/api/curated_regions) which are super useful for building queries were a dataset has a point datatype in it.
Outdated:
- https://datahub.austintexas.gov/d/qqem-is9k
- https://data.austintexas.gov/dataset/Boundaries-City-of-Austin-Council-Districts/5gse-m7ik/about_data
- https://datahub.austintexas.gov/d/q9nd-rr82/
- https://datahub.austintexas.gov/d/8spj-utxs

Current district boundaries (not part of the curated regions):
- https://datahub.austintexas.gov/dataset/Council-Districts-Fill/dbc4-vv54/about_data

**Comment by Charlie-Henry** [comment]
@KaroEngstrom I created an issue so we can hopefully get CTM to fix these old datasets

**Comment by KaroEngstrom** [comment]
### Wed 5/15/24 

Update (no new news) from CTM Enterprise Data Analytics team: 

_I just wanted to give you an update. I am still waiting for the vendor to get back to us regarding the out-of-date assets as well as information on the Spatial Lens. Once we have the incorrect assets taken care of, I will close this ticket and create a new "Request" for the new Spatial Lens(es). Just know that I've reached out to Tyler Technologies about both items separately, and I will continue to follow up with them until we get it resolved._

**Comment by Charlie-Henry** [comment]
I looked into this again to see if there was a potential workaround but I came across the [curated regions API docs](https://dev.socrata.com/docs/other/curated-regions#?route=overview). I tried to make our more recently updated council districts [dataset](https://datahub.austintexas.gov/dataset/Council-Districts-Fill/dbc4-vv54/about_data) a curated region but I got a 403: Permission denied error. I assume whoever has the CTM admin account can do it. Here's the code:

```{python}
import requests
import os

CREDS = (os.environ["USERNAME"], os.environ["PASSWORD"])
URL = "https://datahub.austintexas.gov/api/"

new_rec = {
    "uid": "dbc4-vv54",
    "name": "Council Districts Updated",
    "geometryLabel": "council_district",
    "featurePk": "the_geom",
    "enabledFlag": False,
    "defaultFlag": False,
}

res = requests.post(URL + "curated_regions", json=new_rec, auth=CREDS)
res


```

**Comment by KaroEngstrom** [comment]
### Thu 5/23/24
* I didn't find anything in the current vendor KB on this so I put in a [request](https://support.socrata.com/hc/en-us/requests/59489) to find out if this is still available
* copied @Charlie-Henry  on that TT request

**Comment by Charlie-Henry** [comment]
@KaroEngstrom thank you!!
