### ISSUE TITLE
Add EM Fields to the CTN

### ISSUE THREAD

**Issue by DanielStover** [cityofaustin/atd-data-tech#16663]
The following fields need to be added to the CTN:

EM_CRITICALITY - Text
- Ice - Arterial
- Ice - Path
- Ice - Optional

SBO_DISTRICT - Text
- North
- Central
- South

BRIDGE - Text
- Yes
- Yes - Ice Critical Arterial
- Yes - Ice Critical Path
- Yes - Ice Critical Optional

SLOPE - Small Integer

**Comment by andrewshensky** [comment]
Fields and domains have been added in Maint. Downstream updates will need to be made in locations listed below:

- [ ] AGOL
- [ ] FME/FME Server
