### ISSUE TITLE
Inventory VZD tables that might not be in use

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#16669]
Using the tables in [this sheet](https://docs.google.com/spreadsheets/d/1oHzKt8Cvd1BGpZ7KJl4dfBDHGuSl7gs4yN0OM7AJMBA/edit#gid=2083828135) on the **tables that need review** tab, do whatever research is needed to determine if these tables are depended on by the VZE, VZV, or ETL.

**Comment by mddilley** [comment]
@johnclary Moving this into review/QA. One notable table is `non_cr3_mainlanes`. We reference this table in the function `update_noncr3_location` to determine what location polygon that blueform crashes fall within. I'm not sure about the history of this table.

**Comment by johnclary** [comment]
thanks @mddilley—looks great. i came across a few more tables that i could use your help with. would you mind looking at these?

- `atd_txdot_cities`
- `atd_txdot_crash_locations`
- `atd_txdot_change_pending`
- `atd_txdot_change_status`

**Comment by mddilley** [comment]
@johnclary definitely - i'll look at those tables today!
