### ISSUE TITLE
Convert Schematic Ready field to an optional attachment on the Infrastructure/Construction Services project review type

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16693]
- `Schematic Ready` is a field that was identified as a need for the `Infrastructure/Construction Services` review type
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/9fda588e-483e-429e-aa10-eb09e2c71187)

- AMD is requesting that this field is instead an optional attachment field for this team to attach schematics

**Comment by dianamartin** [comment]
# 4/11/2024
Christina and I synced, now that that we've added the ability to "Add Attachments" for requesters, do we still need this ability?
- Ask in the next sprint review/meeting

**Comment by ChristinaTremel** [comment]
The reviewers can add attachments from their review page so this is no longer necessary. Closing this as not planned!
