### ISSUE TITLE
Set up PBI dataflow for Moped

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#16708]
Goal: Make it easier for people to get Moped data

**Comment by katelunceford** [comment]
Notes from [Data Science Backlog Refinement](https://docs.google.com/document/d/16RBJStu65lHTQa_MVYde7jmortp1ako1P1-A6mPcNOg/edit) on 4/10/24

@susannegov will 
- [ ] Check with Lance about the PBI gateway since he's the owner (run out of the MMC)

We could also explore setting up a DTS PBI gateway so that we don't have to rely on Lance's

**Comment by katelunceford** [comment]
Notes from Dev + Product Sync on 4/10/24

Amenity would love for Moped to have a dataflow!

**Comment by amenity** [comment]
@michael-santulli, @paigewarner, and Jewlee D. from OPM are working on ways to automate their executive reports on infrastructure projects and would like to use this as soon as it's ready. Let them know once it's in progress and whether you need any outside eyes/guinea pigs!

**Comment by katelunceford** [comment]
Notes from [OPM Sprint Review](https://docs.google.com/document/d/1ZnyRrIshduq80l6eiC05xLMGFWLJOfhA0QOUWFvw6HE/edit) on 4/30/24

- OPM has another request/project developing that requires Moped data - the PHA (Project Health Assessment)
- PHA is a monthly meeting driven by CDS where they want to look at where we’re at with bond spending and output for 2016, 2018, and 2020 bonds
- They want to build a dashboard to track infrastructure build out - the data is out there but they don’t know where/what/who and they’re trying to stand this up on their own 
- Similar to TPWstat but may not be the exact same data points 
- We’re not sure how much visibility CDS has into Moped data
- The PBI dataflow could help
- Kate will schedule a meeting with Nathan, Jewelee, Michael, Kate, Charlie, Susanne, Amenity, Chia

**Comment by katelunceford** [comment]
@Charlie-Henry could you email Lance to make this request sooner than 5/15? 

In the mean time we can also test it on Charlie's PC

**Comment by Charlie-Henry** [comment]
I made a working dataflow using my PC as a gateway, I am just importing the `moped_project` table but should we just import everything? @amenity 

https://app.powerbigov.us/groups/c78e625c-c676-4727-9d5b-b5f0565ee975/dataflows/e5c09db2-21e6-452d-bb93-de70cdcbfaa8?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f

**Comment by katelunceford** [comment]
Notes from Product + Dev Sync on 5/1/24
- We don't have the scope yet because we don't know what everyone wants
- So let's start with current requests, such as #15506 
- Concern: How many people will have free rein over the data? It'd be nice to have reporting views that filter out computed fields, deleted, etc. 
- Start with the ETL for AGOL (already there) to make one for Power BI

**Comment by Charlie-Henry** [comment]
@susannegov got access to the virtual machine that the MMC is using. We've installed ODBC connector but we need admin privileges in order to modify the settings in data source administrator. She's opened another ticket with CTM to get this sorted.

**Comment by susannegov** [comment]
Submitted ticket for account:
- INC0389815 Created resolved user accounts created
- INC0390308 - Request admin rights for ODBC
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/1a6ed825-7e4f-4c5d-a37a-612aa2741243)

**Comment by Charlie-Henry** [comment]
Still waiting for CTM to grant admin access to this PC ⏳

**Comment by amenity** [comment]
@scottreedy @dianamartin - do you know how we might expedite this?

**Comment by dianamartin** [comment]
I think @Charlie-Henry can ping the Tech Services team @Craigjacobs-ATX @Vaishnav1397 (they're currently available) to see if they can grant him "Admin" access to his computer.

**Comment by scottreedy** [comment]
@Charlie-Henry @dianamartin 
What is the computer name? Is it a pc or server?

**Comment by susannegov** [comment]
Lnace gave Charlie and I admin access. Was able to quickly setup the ODBC connection as a test

**Comment by Charlie-Henry** [comment]
Got my test dashboard to successfully refresh using the MMC gateway 🙌 

<img width="442" alt="Screenshot 2024-05-15 at 3 55 51 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/30810522/6e4c2789-e9e7-457f-9974-93b7165387f0">

**Comment by susannegov** [comment]
- [x] Tested pulling moped dataflow to Power BI Desktop with success!
- [x] Charlie added "Moped Dataflow" to "TPW - Production"

**Comment by Charlie-Henry** [comment]
Updated our docs on how to connect to a dataflow:
https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M2EDlSmB3f_vryzLEhZ/power-bi/how-to/connecting-to-a-dataflow

**Comment by amenity** [comment]
Amazing!! 🎉 😊 🙌🏻  Also love these clean, simple docs. Thanks, @Charlie-Henry @susannegov.

**Comment by amenity** [comment]
For posterity, here's the sparkly public link: [Connecting to a Dataflow](https://atd-dts.gitbook.io/atd-staff-resources/power-bi/how-to/connecting-to-a-dataflow)
