### ISSUE TITLE
Data: RAW Data for TPW Tech Surcharge on LM (SS) (April 17 Sprint)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16701]
### We need to know how much we collected of Technology Surcharge-DSD in fiscal 2024. 

**Parameters:**

- Fee code is 50014
- Folder type is LM
- Fee is billed
- Fee was inserted on or after 10/1/24

**Columns for data output:**
- folderrsn
- Fee amount
- fee name
- bill # 
- Billed date
- Paid flag

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  Here is the data fetched as of 4/17/2024 by noon. Please read the below notes and let me know if the data fetch criteria needs a change. Thanks.

[RAW Data for TPW Tech Surcharge on LM.xlsx](https://github.com/cityofaustin/atd-data-tech/files/15013503/RAW.Data.for.TPW.Tech.Surcharge.on.LM.xlsx)

### Query
SELECT abf.indate, abf.folderrsn, abf.feeamount, vaf.feedesc FeeName, abf.billnumber, ab.dategenerated BillDate, ab.paidinfullflag FROM accountbillfee abf
JOIN folder f ON f.folderrsn = abf.folderrsn AND f.foldertype='LM'
JOIN Accountbill ab ON f.folderrsn = ab.folderrsn AND ab.billnumber = abf.billnumber
JOIN validaccountfee vaf ON vaf.feecode = abf.feecode
WHERE abf.feecode =50014 AND (abf.billnumber <> 0 OR abf.billnumber IS NOT NULL )
        AND trunc(abf.INDATE) >= TO_DATE('10-01-2023','MM-DD-YYYY')  
       -- AND abf.folderrsn = 13211738
       ORDER BY abf.folderrsn;

### IMPORTANT NOTES:
While testing and verifying data fetched I came across an LM for which, 50014(DSD Tech surcharge) was inserted before 10/1/2023 but it was cancelled after October 1st, 2023. So when I query the inserted query didn't show up but only cancelled record got fetched.  There can be more such examples.
![image](https://github.com/cityofaustin/atd-data-tech/assets/51680715/0f6757ff-57a9-40e1-a2d1-4c5b0165177c)

**Comment by SubhaShroff** [comment]
[RAW Data for TPW Tech Surcharge on LM.xlsx](https://github.com/cityofaustin/atd-data-tech/files/15045336/RAW.Data.for.TPW.Tech.Surcharge.on.LM.xlsx)

**Comment by TracyLinder** [comment]
This data is good. Thanks Subha.
