### ISSUE TITLE
Austin 3-1-1 and SBO April 2024

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#16710]
3-1-1 Weekly Consolidation Report

**Comment by ReneVarg25** [comment]
### 4/9/2024
170 - Not in Maximo
40 - Closed
10 - Duplicate
38 - Log Transmission Issues (CTM Notified and Working on Issues #)
12 - Tree Group INPROG
 67 - Wrong Log (User Error)
2 - Review

**Comment by ReneVarg25** [comment]
### 4/15/2024
164 - Not in Maximo
49 - Closed
30 - Log Transmission Issues
2 - Currently New CSRs
1 - No Log
11- Tree WOs INPROG
58 - Wrong Log

**Comment by adry-martinez** [comment]
@ReneVarg25 is this ready to be closed out?

**Comment by ReneVarg25** [comment]
### 4/25/2024
177 - Not in Maximo
106 - Closed
7 Duplicates
2 - Open/In progress
14 - Tree Group In progress
48 - Wrong/Missing Log
