### ISSUE TITLE
Moving all install/uninstall dates to the `regulation_items` and remove from `regulation_documents`

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16719]
- Moving all install/uninstall dates to the `regulation_items` and remove from `regulation_documents`
- Add Install/Uninstall dates to the Approved Regulation paginated reports per line item instead of the top of the document

**Comment by ChrispinP** [comment]
Records where the date is empty for both the Reg Doc & Reg Item, By the Numbers:

- 1141 Install Reg Items missing Approved Dates
- 1974 Install Reg Items missing Installed Dates
- 147 uninstalled records missing Uninstalled Dates

I updated data discrepancies between dates and the boolean fields but I did not update any statuses. I think it would be in our best interest to keep the Reg Doc dates for reference in the data but we can start enforcing Reg Item dates visually for the Install/Uninstall.

Pending updates to the Paginated Report

**Comment by ChristinaTremel** [comment]
This was completed! Moving this to review/QA and we will review with the stakeholders.

**Comment by ChristinaTremel** [comment]
Reviewed this during the sprint review with TED! Closing this out.
