### ISSUE TITLE
Fix improperly nested DOM elements in `atd-product` 

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#16729]
Please see the console errors such as:

```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
Warning: validateDOMNesting(...): <h2> cannot appear as a descendant of <p>.
```

Fixing these appears to be a blocker on updating the `next` and `react` versions on the website to the latest and greatest due to hydration issues. I took a quick look into this while working on website issues this sprint while awaiting feedback. Low risk, low urgency, but it is our website, so I'd like to eliminate console errors if we can.

A WIP PR to move this forward is here: https://github.com/cityofaustin/atd-product/pull/89.

**Comment by chiaberry** [comment]
I fixed this in this PR (https://github.com/cityofaustin/atd-product/pull/93) thank you for surfacing this!
