### ISSUE TITLE
IT Support: Keyboard not working

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#16724]
DALTON

## Device & User Information (first name and last initial, no last names)
Gary G
## What's the problem?
Users keyboard is not registering when pressed. 

It is working on and off

**Comment by Matthew-M-TPW** [comment]
@Craigjacobs-ATX swapped out his laptop

Please reach out to dell if the spacebar still does not work

**Comment by Vaishnav1397** [comment]
waiting to hear from dell on a box to be sent.

**Comment by Vaishnav1397** [comment]
Have received the box and handed it at the delivery partner by Matt.

**Comment by Vaishnav1397** [comment]
The work order number is 450352788

**Comment by Vaishnav1397** [comment]
Sent out the box and received the update. Closing this as there another ticket with case number and work order details updated.
