### ISSUE TITLE
SPIKE: Bulk download pics/attachments for Homeless Encampments 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16728]
### The homeless encampment cleanup program managed by OCE need to be able to download inspection picture in bulk for PIR requests. We will research possible solutions to meet this need. 

Possible Tech to research:
- KNACK
- MAXIMO
- DTS-DEV (if needed)

**Comment by TracyLinder** [comment]
**Answers from Robert for the questions above:**

1. Can the public see the inspection pics? Would them being available publicly be an issue?
- For inspection pictures I’m not sure because I know if it’s a 3-1-1 request that the public can see some information, but we would never have any issue with sharing any pictures we take for inspections or for cleanups. For cleanups I don’t believe the public is able to see anything on GIS, but not 100% sure. The intention with the photos is usually just to be able to confirm conditions and what work we are doing if we were ever asked by legal, because we have had instances where people say their personal belongings were thrown away.

2. What do the inspection photos usually consist of?
- For inspections the phots will just usually be of the condition of the issue and if any work is done they will show what they did. For cleanups they take photos of the notices posted at each location so we can document that we provided notice, and then on the clean up day they will do before photos and after photos. For cleanups these are typically really large areas so Adrian is take a lot of photos, maybe 10-20 at each site. Also just to throw it out here, but we had two forms previously, one was for just posting and one was for the encampments, but if we do use knack and can create a file for the cleanup date & then edit to include photos of posting and before and after all in the one spot that would be ideal for when we do have legal request.

3. Who in the public normally requests PIRs for the inspections and inspection photos? Do you know for what purposes?
- For inspections it is usually the property owner or attorney that request photos because they’re usually dealing with an issue related to a sidewalk, curb, or street in front of the property and they may be getting ready to sue or already have. For cleanups we usually get photos as request from activist and they’re trying to use them as a way to show we did something wrong.

**Comment by dianamartin** [comment]
# 4/15/2024
## Possible scenarios to test in Knack
- [x] Signs and Markings "Manage Attachments" page
>attachment showing on table, but in app can view, not sure about when exported
    
  - [x] Add export button to page (.csv, .txt, JSON)
  - [x] Filter for "Image" keyboard, `7452 records`
  - [x] JSON, opened in Notepad
>Was able to use the field "File" and use only the "href" [link](https://api.knack.com/v1/applications/5d13ae5b438091000ac0197d/download/asset/5d3cad64ddcdb300126dab2d/csrimage1800355549.jpg), throw it in the browser and it pulled up the image. 
  - [x] .CSV
>Was able to use the field "File" and use only the "href" [link](https://api.knack.com/v1/applications/5d13ae5b438091000ac0197d/download/asset/5d3caa9c5aac000011be80c9/bp1418lavacacesarchavezto2nddelineatorpostandstripingrefresh.pdf), throw it in the browser and it pulled up the image.
- [ ] Signs work order photo page
- [ ] Add export to file name table
- [ ] Add export to thumbnail table
- [ ] Export to PDF details page

**Comment by adry-martinez** [comment]
### April 23, 2024 

Spoke with Erin A with CTM and inquired on Maximo's capabilities regarding bulk export of images from work orders.

This was her response:

_Looking around on the interwebz there really isn't an easy way to extract all the attachments.  This could possibly be done with a script and through email but I am not sure it would work so well with the cloud system like we have.  Most of the things I found imply you are on premise for this to work.

Not without some heavy scripting and back end work.  We won't be able to do that from the front end, I don't think_

**Comment by TracyLinder** [comment]
### Spike Notes

- We chose to go with KNACK
- We're looking at 1-2 forms and 3-4 tables
- Next step is scoping with OCE to have them explain their 2 Microsoft Forms that we would convert into KNACK.
