### ISSUE TITLE
Maximo Training Plan, Pavement Operations: Video Training Course

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16721]
- [x] Basic Navigation
- [x] How to complete a work order
- [ ] How to troubleshoot
    - [ ] how to correct actuals
    - [ ] missing labor, tools, and materials
    - [ ] specifications is not up-to-date
    - [ ] how to add/delete an attachment
    - [ ] how to add a job plan after a status change
 - [x]  How to send a CSR feedback
 - [x]  How to notify another SBO work group

**Comment by rebekkabry** [comment]
@ReneVarg25 The unchecked how to troubleshoot above, may be good to add into the gitbook. What do you think?

**Comment by rebekkabry** [comment]
Created an SBO version of training. Using https://atd-dts.gitbook.io/maximo-help-guides/introduction-to-maximo. Closing this request.
