### ISSUE TITLE
Pavement Operations, Data Quality Quarterly Review - July 2024

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16737]
SPOCs to notify:

Andre E.
Jonathan G.
John F.
Stephen R.
Alfred L.
Jermaine B.

**Comment by rebekkabry** [comment]
@ReneVarg25 will handle. 

- [ ] Please update once complete and if another quarterly issue should be created.

**Comment by ReneVarg25** [comment]
### 7/17/24
Data Quality has been sent out to SPOCs. Attached report to issue for documentation.
[sbo_pvmtdataquality (1).pdf](https://github.com/user-attachments/files/16266502/sbo_pvmtdataquality.1.pdf)
