### ISSUE TITLE
[Meeting] 4/11 Feedback from Micro-mobility Sprint Review

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#16762]
## Description
During the Micro-mobility Sprint Review we received feedback for immediate improvements and things we still need to refine. 

### In Meeting

- Set up basic reporting page
- CSR_Issues Table updates
  - Group by Provider
  - Configured for by statuses (active/closed)
  - Show the new and oldest first
  - Removed source and received
  - Removed number of images
- Added location field; and map to details page

### To Do

- [ ] Configure Providers to get a notification emails
- [ ] Update Activities in the details page
- [ ] Look into why the impoundment was automatically selected
- [ ] Have providers submit a photo before closing out the SR
- [ ] Do not automatically generate an invoice for impound, that should be done at the end of the month by SMS staff. Add a 'new' status, which can be filtered for easy viewing
- [ ] Create ability in invoice to be able add multiple line items all at once
- [ ] Send an email to Providers when the device is impounded
- [ ] Add a calculated field to show (time) if the SR is over 2 hours?
- [ ] Enable (System Admin power) to allow SMS staff to close out SRs (i.e duplicates)
- [ ] Build out Reporting page

### Follow up meetings

- [ ] Set up work session with Andrea/SMS team to go over some of the improvements to impoundments and additional enhancements
- [x] Work with Shayvyonne to get users to test the new SR flow
- [ ] Work with Michael K. to connect with Providers for demoing/testing

**Comment by patrickm02L** [comment]
@dianamartin Issues for have been created for the sections identified above excluding: 
- ACTIVITIES FORM/DETAILS PAGE
- TROUBLESHOOTING

**Comment by patrickm02L** [comment]
## 4/11
Shayvyonne got us a list of users to add for testing. via Teams:


> Officer that you can grant access to the new Micromobility process:  
>  
> **Tech Savvy:**
> Douglas Boots
> Terance Jones
> Hillary Nichols

> **Not Tech Savvy:**
> Teresa Martinez
> Janet Newell
> Lupe Perez
>  
> Percyna will train Hillary on how to navigate the new process. The list includes officers from different shifts which will allows us different prospective of usage. Let me know if you need anything else or if you have any questions. 
> has context menu
> Compose

**Comment by patrickm02L** [comment]
## 4/12 
Activated PEO Officers from the list the Shavyvonne sent.

**Comment by patrickm02L** [comment]
Individual Issues have been created to accomplish the action items above. Will pursue follow up meetings/scheduling outside of this Issue.

**Comment by patrickm02L** [comment]
## 4/16
Worked with Diana to give individual access to PEO user accounts in PEP. Messaged Shavyvonne to let her know they'll be able to see the micromobility button now.

**Comment by dianamartin** [comment]
# 4/17/2024
Messaged stakeholders
>Hey all, 
 Patrick said people can't see on PEP the new micromobility form for testing, is this still the case?

Percyna said
>Teresa doesn’t have access, it doesn’t even show up on her knack

I replied
>Ohh, I see we also don't have passwords on the backend, I wonder if that's preventing them from logging in. Now their SSO (Single Sign On) should work for them. (I sent over a screen shot, they sent one back saying she didn't have that button)

Christine said
>No she doesn't have that button

I checked again
>okay, i think I found a setting to change. have her refresh one more time
- I changed the Page Rule, from "Officer Name>Email" to "Accounts>Email"
