### ISSUE TITLE
[Feature] Modify Invoice Generation and Management

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#16767]
## Description

_broken out of #16762_

Revamp the invoice processes related to impoundments and general invoicing to increase efficiency and control for the SMS staff.
   
#### Details

- [x] Prevent the system from automatically generating invoices when devices are impounded. Instead, enable manual generation at month-end by SMS staff. (Completed in meeting)
- [x] Introduce a new status field with options 'New' and 'Processed' to help filter and manage impoundments easily.
- [ ] #17116
  - Add trigger button that auto-creates an impoundment record (replacing record rule to auto-create)

**Comment by patrickm02L** [comment]
## 4/17 Planning
Estimate 3, because there might be discovery on the adding multiple records to the invoicing enhancement.

**Comment by dianamartin** [comment]
# 4/19/24
## Impoundment Records that came from auto generated record rule from micro-mobility SR
- [ ] `371`
- [ ] `370`
- [ ] `369`
- [ ] `367`
Let's ask Andrea if she wants these to be deleted

**Comment by dianamartin** [comment]
# 4/19/24
- [x] Added new choices to "Status" field
- New
- Processed

**Comment by patrickm02L** [comment]
## 5/7/24
The Dev component identified as part of this Issues that allows for multiple selection has been captured in #17116 
Closing this Issue
