### ISSUE TITLE
[Feature] Develop Reporting Page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#16766]
## Description
_broken out of #16762_

Build out a new Reporting page to enhance data visualization and access for users

**Comment by patrickm02L** [comment]
## 4/17/24 Planning
If this is something that we're replicating from PEP it's relatively straight forward.

**Comment by dianamartin** [comment]
# 4/24/24
From this [comment](https://github.com/cityofaustin/atd-data-tech/issues/16764#issuecomment-20757950780)
- [ ] Create reporting functionality for SMS to filter activities.
- [ ] Build enforcement services reports to show SRs created and impoundments done by officers.

**Comment by dianamartin** [comment]
# 5/9/2024

# 5/8/24 
Shavyvonne messaged the group chat to Christine to provide what her reporting needs are
>Good afternoon Christine,
 don't forget to let Diana and Patrick know what type of reports you would like to collect from the new Micro-Mobility SR.

Christine emailed us
>Hello,
The following picture is what +we were keeping track of.

Currently we impound based on criteria:

### Immediately
- ADA space/ ramp
- Neighborhoods – On private property
- Travel Lane & Bike Lane
- Broken / Damaged Units
- Completely blocking mobility – includes multiple units from different companies as well.

### After 1 hour
- Partially Blocking Mobility

### After 2 hours
- Tow Away Zone
- Fallen / Knocked Over 
- Unauthorized areas


So looking at the Micro-Modal for the report I would say:
- [ ] Officer #
- [ ] Date / Time / Location
- [ ] Company
- [ ] # of Units
- [ ] Unit ID’s
- [ ] Impound reason

## Reference
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/8d3b3cd7-1d33-40cc-a8fd-dc69a46bbd25)

**Comment by dianamartin** [comment]
# 5/9/2024
- [x] Added `Impound Reason - Activity` to `csr_activity` table
- [x]  Added `Impound Reason` to PEO Activity form on SR Details page
- [x] Update record rule to update CSR Issue if impoundment

**Comment by dianamartin** [comment]
# Issues to address
- "Created By Officer" isn't populating bc we're using the logged in account 
- [ ] Export Officer table
- [ ] Export Accounts table?
- [ ] Will need to import the officer radio numbers into the "accounts" table
- [ ] Create a new display name for "PEO Officer Name"
