### ISSUE TITLE
Update tag styles to display inline and move tags box below subprojects. 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#16778]
Right now, tags inherit the list item `display: list-item` style, so the tag box can get very tall when there are a lot of tags. 
<img width="1421" alt="Screenshot 2024-04-11 at 6 41 34 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/df9f6c38-3ada-492f-a849-667b9125635d">

Let's switch them to `display: inline`. (Or `inline-block`, `inline-flex`, `inline-grid`, `inline-table` — these all seem to work, so whatever matches precedent/MUI.) 
<img width="1420" alt="Screenshot 2024-04-11 at 6 43 07 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/9fa50598-cc7a-46ce-b2d9-5fa60b24c9d8">

**Comment by amenity** [comment]
@amenity - check w/ users to see if moving subprojects above is helpful. Ivonne has indicated that, but might not be everyone.

**Comment by mddilley** [comment]
@amenity @chiaberry I have a PR to make the tags inline that I'll request reviews on. I can switch up the order of the tags and subprojects section too in that PR if we hear back - that part is really straightforward.
