### ISSUE TITLE
Perform Ganesh onboarding tasks [Adry]

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16788]
![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/e2d13707-4eb7-4a2b-a3c3-cbbfc66211fd)
[Maximo New Hire Onboarding](https://docs.google.com/document/d/1PmRq4xgo5GQCijI9e-mG32OLjNL4t7IUMWQvCrEeHmg/edit)

### Hardware & Office

- [x] ~Request necessary hardware from Scott. Do this as soon as possible to ensure he has enough lead time to acquire equipment. Make sure they get a laptop, power supply, monitors, keyboard, mouse, and docking station. Some team members also need a CoA phone.~
>We'll have to ask Elena at Luna and Peggy about this
> @dianamartin when would be a good time to start this portion?

- @adry-martinez  I checked in with Elena on 4/16 and she said 
>Thank you for letting me know. We just spoke with Ganesh and he said he is fine to use his personal laptop! So we’re good there. 

### Network Account 

- [x] ~Under "Network Account Information,"~ write Shared mailbox: transportation.data@austintexas.gov; Distribution lists: ATDDataTechnologyServices@austintexas.gov and TPWEmployees@austintexas.gov.

### Third-Party Equipment
- [x] Submit a [Third-Party Remote Access Request](https://atx.servicenowservices.com/sp?id=sc_cat_item&sys_id=30f9aa09dba4a8106d0171f2399619a2).
   - This will require the vendor to sign a third-party remote access acceptable use agreement. Find the latest version of the agreement form embedded in the service now request. This must be submitted with the ServiceNow request.  
>I'm emailed the form for Elena and Ganesh to fill out. Hoping to submit the CTM request Thu or Fri. 

#### After the network account is created and you have their @austintexas.gov email address:
- [x] #17388
- [x] Ask Amenity or Diana to add the new team member to [City of Austin Slack](https://austininnovation.slack.com/admin).
       - [ ] Add them to all relevant Slack channels and introduce the new team member to everyone in the main DTS channel.
- [x] Add "Welcome Ganesh" to [the agenda for the next team meeting](https://docs.google.com/document/d/1s8rl928FM0fKPEvsgkVSmkUghPgUmEgMEhZr4bmsJWc/edit). 
- [x] Schedule a one-hour DTS Team Orientation. It should include Peggy and all team leads.
- [x] Schedule a one-hour DTS Maximo Team Orientation.
- [x] Ask Amenity to schedule DTS Product Ops training.
- [x] Schedule Biweekly 1x1s.
- [x] Forward biweekly Sprint calendar events.
- [x] Invite new team member to relevant agile ceremonies — Planning, Backlog Refinement, Retro.
- [x] Invite new team member to other regular meetings — DTS Team Meetings, Syncs, Show & Tell.

#### After they've created their Google and Github accounts: 
- [x] Share the [DTS Google Drive](https://drive.google.com/drive/u/0/folders/1fNmU-czryk5wJsn1gmb4WYUJJdut8Me7) with the new team member. 
- [x] Add the new team member to the City of Austin [Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members). This should automatically add them to the [City of Austin Github organization](https://github.com/orgs/cityofaustin/people).
- [x] Invite the new team member to the [City of Austin Zenhub organization](https://app.zenhub.com/settings/o/cityofaustin/users). 
- [x] Add the new team member to [Gitbook](https://app.gitbook.com/@atd-dts/spaces).

### Once they've uploaded their [headshot](https://drive.google.com/drive/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G):

- [x] Add them to the [DTS Orientation presentation team slide](https://docs.google.com/presentation/d/1ByRWXmjHut88cTiPVOTgkwTJ2V5_m1Y_0j46FP_kdYw/edit#slide=id.gfd25a7f266_1_173) and the slide for the team they are joining.
- [x] [Open an issue](https://github.com/cityofaustin/atd-data-tech/issues/new) to add the team member to the team website. The issue should include link to the headshot, new employee's title for the site and pronouns. Assign the issue to Chia.

### Once they've received notice from CTM that their Miro account was created:

- [x] Add them to [the Austin Transportation Miro Team](https://miro.com/app/settings/team/3074457347846964301/users/). 
- [x] ~~Once HR has added them to the UKG timekeeping system, their supervisor—Peggy, Amenity, or Diana— must set up a schedule plan~~

**Comment by dianamartin** [comment]
# 4/17/24
@adry-martinez I imaging we can start doing all of this once we get the financial documents processed. We could then submit the 3rd party vendor form and ask Tech Services about VPN set up.

**Comment by dianamartin** [comment]
# 4/26/2024
- Also take mandatory Cybersecurity training - will email maybe sent out 60 days after enrollment
- [x] Forwarded - DTS Orientation meeting
- [x] Forwarded - Maximo Sync series
- [x] Forwarded - Maximo Learning Cohort Series
- [x]  Forwarded - DTS Monthly Meeting

**Comment by adry-martinez** [comment]
## May 17, 2024

Onboarding completed. Per Diana, issue created for 1PW vault. Issue closed.
