### ISSUE TITLE
Perform DTS onboarding tasks [Ganesh]

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#16789]
# Welcome to DTS!
### Day 1 🐣
These are the **_high priority_** tasks. Let your supervisor know if you have any issues completing them on your first day. 
- [x] [Log into your City of Austin e-mail](https://outlook.office365.com/)
- [x] Install [Microsoft Authenticator app](**url**) on your phone. Moving forward, you should only log in to City of Austin Microsoft services via 2 factor authentication. 

- [x] You should have a 1Password invitation in your email. If not, email/Slack Diana to request one and then accept the invitation. Diana or Amenity will then confirm your account. Then follow [this guide](https://support.1password.com/explore/get-started/) to set up 1Password for use on your City computer and any mobile devices you use for work. 

**All your passwords relating to work should be stored 1Password and only in 1Password.**

- [x] If you don't have one already,  create a [Github](https://github.com/join) account with your CoA email and then ask Amenity or Frank to add you to the City of Austin [Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members)
- [x] Enable [two-factor authentication for your Github account](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa).
- [x] Install Slack desktop client —  [Windows](https://slack.com/downloads/windows) | [Mac](https://slack.com/downloads/mac).
- [x] [Set up your e-mail signature ](https://docs.google.com/document/d/1OAoBll9rIl6XZq2uOShm5HCbHJboOt0SLP_wK6tjkEE/edit)
- [x] [​Update your Slack profile](https://slack.com/help/articles/204092246-Edit-your-profile) with a photo and your title.
- [x] Post your [daily standup in Slack](https://atd-dts.gitbook.io/wiki/slack#daily-stand-up).
- [x] [Create a Google account for your austintexas.gov e-mail address](https://atd-dts.gitbook.io/wiki/basics/document-storage/using-google-as-a-city-employee)​ and verify that you have access to the [DTS Google Drive](https://drive.google.com/drive/u/0/folders/1fNmU-czryk5wJsn1gmb4WYUJJdut8Me7). 
- [x] Complete [CyberSecurity Training](https://training.knowbe4.com/ui/login)

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/e2d13707-4eb7-4a2b-a3c3-cbbfc66211fd)
[Maximo New Hire Onboarding](https://docs.google.com/document/d/1PmRq4xgo5GQCijI9e-mG32OLjNL4t7IUMWQvCrEeHmg/edit)

### Week 1 🐥
Let your supervisor know if you are not able to finish any of these during your first week. 

- [x] Maximo accounts in TEST and PROD
- [x] Eclipse Developer Tools
>gave Eclipe download [link] (https://www.eclipse.org/downloads/)
- [x] Need to get DB and IBM Open VPN accounts created for database querying​
>Get end point to DB from Mark T. (CTM) - Adry

- [x] Upload a headshot here
- [x] Install Zenhub Browser Extension
- [x] Create a github issue to add yourself to the DTS "About Us" webpage:

​ To add yourself to the [team website](https://www.austinmobility.io/about#team), open a [new issue](https://github.com/cityofaustin/atd-data-tech/issues/new)
- Title: Add [First name] [First initial of last name] to DTS website
- Labels: Service: Dev, Type: Communications, Product: DTS Website
- Assignee: Chia B.
- Include: 
     - Link to your photo in [Google Drive](https://drive.google.com/drive/u/0/folders/1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G) 
     - Full preferred name
     - Title
     - Preferred pronouns

- [x] ~Email Adan S. to request a paper timesheet.~

- [x] [​Open a service request](https://atx.servicenowservices.com/sp?id=sc_cat_item&sys_id=02e490c6db7f1300a314e1c2ca9619e6) with Communications and Technology Management (CTM, the City's internal enterprise IT department) to request:
   - [x]  a Miro account.
   - [x]  ~SnagIt tool~ using personal laptop, will have to pay for his own service. not required for his work.
   
- [x] Familiarize yourself with the [DTS Resource Index](https://atd-dts.gitbook.io/wiki/resource-index) and [our document storage policies](https://atd-dts.gitbook.io/wiki/basics/document-storage).

### Week 3 🐓
You made it!
​
Ask questions! Be a sponge and absorb it all! 🧽💦🌈

**Comment by dianamartin** [comment]
# 4/26/2024
- Also take mandatory Cybersecurity training - will email maybe sent out 60 days after enrollment

**Comment by adry-martinez** [comment]
## May 17, 2024
✅ Onboarding completed. Per Diana, issue created for 1PW vault #17388. Issue closed.
