### ISSUE TITLE
Update Street Banners PROD with Total Fee updates

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#16809]
# 4/15/2024
 ## Change in Prod
### Add NEW fields
- [x] Export "banners_reservations_ots"
- [ ] Create new field - `Archive Total Fee YN`
    - [x] Set conditional rule "Archive Total Fee YN" to 
     - [x] Number of Weeks - is blank - Yes
     - [x] Number of Weeks - is blank - No
- [x] Created new field `Archive Fee Total` (number) - currency
   - [x] Set conditional rule "Archive Total Fee YN" - Yes - to set field value "Total"
   >This should set snap shot the old totals in the system

### Update "Total" with NEW Conditional Rule
- [ ] Replace Conditional rule in `Total` field (banner_reservation_ots) 

Conditional Rule | Parameter | Result
-- | -- | --
Discount | Yes | and
Discount Amount | not blank | Total Fee Discount Update 
  |   |  
Discount | No |  and
Discount Amount | is blank | Total Fee Update  

_Originally posted by @dianamartin in https://github.com/cityofaustin/atd-data-tech/issues/15938#issuecomment-2035740489_

**Comment by dianamartin** [comment]
# 4/15/24
- [ ] Review "Active" reservations
  - New - `5 records`
  - Pending Customer Action - `2 records`
    - 1185 - $600
    - 1142 - $1800
  - Completed Customer Action - `0 records`
  - Approved - Pending Payment - `9 records`
    - 1152 - $600
    - 1137 - $1800
    - 1158 - $3600
    - 1136 - $1800
    - 1135 - $1800
    - 1141 - $1200
    - 1068 - $600
    - 1140 - $1200
    - 1139 - $1200

**Comment by dianamartin** [comment]
# 4/15/24
## Spot Check OTS reservation amount

ID | Total | Invoice | Reviewed
-- | -- | -- |  -- | 
1152 | $600 | INV2024-101470 | 
1137 | $1800 | INV2024-101420
1158 | $3600 | INV2024-101490 | Looked good
1136 | $1800 | INV2024-101415
1135 | $1800 | INV2024-101410
1141 | $1200 | INV2024-101455 | Looks correct, but had to go into the "Edit Form" to see the "Number of Weeks" show up. After saving, it showed up on the Details page.
1068 | $600 | INV2023-101140
1140 | $1200 | INV2024-101445
1139 | $1200 | INV2024-101450

**Comment by patrickm02L** [comment]
Reviewed at the 4/30/24 meeting and got sign off as complete.
