### ISSUE TITLE
[Enhancement] Delete test records and add delete ability to LS team

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#16820]
## Description
In the Sprint Review on 4/16/24, Jonathan asked to be able to delete test records so that they don't come through on the records download. We discussed deleting the records on the apps team, but also offered up the functionality for the LS team to be able to delete.

## Criteria

- [x] Delete test records
- [ ] Give Jonathan and Matt access to delete records

**Comment by patrickm02L** [comment]
## 4/17 Planning
- Let's wait on giving delete functionality to the LS team.

**Comment by KaroEngstrom** [comment]
### Wed 4/17/24 
- exported a backup copy of the applications and saved [here](https://drive.google.com/file/d/15PbQUk2yA_DLxvzbAzfXDUwhfvCc48M7/view?usp=drive_link)
- identified and deleted the following test applications: 
   - 117
   - 121
   - 122
   - 125
   - 133
   - 163
   - 191
   - 196
   - 199
   - 220
   - 226
