### ISSUE TITLE
Migrate funding sources table to datagrid

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#16831]
So that it aesthetically and functionally matches the work activities table below it. The actions cell being on the right vs the left. 

![Screenshot 2024-04-16 at 2 50 43 PM](https://github.com/cityofaustin/atd-data-tech/assets/12474808/0f4c6297-9a62-43a9-aec2-ef9e25daf8ee)

Feedback from spike PR:

- [x] Update `handleAddRecordClick` to use uuid for new row
~- [ ] memoize `dataGridColumns`~ Moved to https://github.com/cityofaustin/atd-data-tech/issues/18669
- [x] align font sizes of cells in view mode (DataGrid Pro overrides the 1rem theme size to 0.875rem)
- [x] makes sure inputs in edit mode line up with each other; hoping this is a small change to the **Status** dropdown since it is the only one that seems to be different than the others (screenshot below)
- [x] add space between inputs in edit mode
- [x] make action pencil and trash can icons the same size as in work activities table (i could be convinced to make them all smaller which seems to be the default?) 
- [x] use `DeleteConfirmationModal` with delete action
- [x] add `disableRowSelectionOnClick` prop to table so we don't have the blue row highlighting
~- [ ] any other code improvements - Chia suggested some beyond these~

**Status input is not aligned with others**
<img width="1434" alt="Screenshot 2024-07-11 at 1 58 42 PM" src="https://github.com/user-attachments/assets/bf63a6ab-31f8-4fb1-be60-01112627958e">

**Comment by mddilley** [comment]
@chiaberry I'm going to repurpose this one to capture the post-spike (https://github.com/cityofaustin/atd-data-tech/issues/17681) work needed to release the changes to the funding sources table. Thanks for writing this one up!

**Comment by chiaberry** [comment]
> align font sizes of cells in view mode (DataGrid Pro overrides the 1rem theme size to 0.875rem)
@mddilley do you want the text size to be 1rem across the board, or .875rem? 
and if I change it to be 1rem, should I also update work activity table text size to be 1rem so it visually matches?

**Comment by mddilley** [comment]
@chiaberry Sorry that wasn't super clear. I think that any cell in the view mode should be 0.875rem like in the Work Activities table below it. I was hoping that the cells in the Funding table that are larger have styles that can be removed since the default size in DataGrid is 0.875rem.

**Comment by mddilley** [comment]
@chiaberry just adding that we talked about pinning the icons to the right in dev sync. i like it!!!

**Comment by mddilley** [comment]
@chiaberry I'm closing this one since I moved some items to [this cleanup issue](https://github.com/cityofaustin/atd-data-tech/issues/18669) liked we talked about this morning. Thanks again!
