### ISSUE TITLE
Feature: Add an AVL Procedure form to My Forms in Knack HR Portal

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#16838]
Jennifer W. 
HR

## As a TPW Employee I want the ability to sign off on the mandatory AVL Procedure so that I will be in compliance with our new HR policy.

This item was discussed and requested on Mon, 4/15/24. Jennifer asked that we add a new form to the HR Portal so that TPW employees can sign off on the procedure.

**Comment by dianamartin** [comment]
# 4/16/2024
Did some of the building the on 4/15/24
## Table Buildout
- [x] Created object `form_avl_procedure`
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/f01dfb07-97cf-4c2f-a06e-bc5c47a87e0d)
- [x] Created page "New AVL Procedure" [form](https://atd.knack.com/hr#new-avl-procedure/)
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/2668405d-fab8-446e-8fdc-c256b1525569)
- [x] Created page "[Automatic Vehicle Location (AVL) Procedure](https://atd.knack.com/hr#new-avl-procedure/avl-procedure/)" (where policy is located)

## Backend Updates
- [x] Added new selection on "Form Name" on `form_management` object
- [x] Added new field `Category`
- Benefits
- New Hire Onboarding
- Policy Acknowledgement
- Performance Management
- Evaluations
- [x] We backfilled the existing forms and categorized them
- [x] Added (count) field for "# of AVL Procedures"

## Frontend Updates
- [x] On "HR Forms", added new record "Automatic Vehicle Location (AVL) Procedure"
- [x] Added field "Category" and grouped by that field
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/1510fc1a-9fa7-43b2-a73a-0de73cb2da3e)
- [ ] On "My Forms" added a new menu page "Automatic Vehicle Location (AVL) Procedure"
- [ ] Created a new page "New AVL Procedure"
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/58cd0116-53c9-4ce9-85c9-6da9378fbdb6)

**Comment by dianamartin** [comment]
# 4/16/24
Made a comparison on the same page when we show it to the stakeholders
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/58f2111b-a26c-4ba4-a9ec-e70477adabc2)

**Comment by dianamartin** [comment]
# 4/17/24
Jennifer emailed us the updated language on the "AVL Procedure". 
>Hey there superstars! OPM is asking if we can give any sort of timeline for the policy acknowledgment in Knack at the Supervisor Meeting next week. Once I get the policy approved by the executive team, do you have an estimate on when we can have it ready in Knack for an acknowledgment? 

I replied
>Hi Jennifer, 
We just need you guys to review it. I have the issue with the mock up in there: [https://github.com/cityofaustin/atd-data-tech/issues/16838](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-data-tech%2Fissues%2F16838&data=05%7C02%7CDiana.Martin%40austintexas.gov%7C98423fcb75d443122b9908dc5f8bca8b%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638490301240021148%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=vYK%2FHvdmNFopeEDkY1dqr4Wp44I1IYfiLcwNiVizDUU%3D&reserved=0)
 
>There are two ways to have the form:
>- Version 1
>- Version 2
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/6dd4b92b-f8f8-41b3-8245-502ccc5b789f)

>Looks like this after it’s submitted.
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/9ff2a954-1ab7-43e0-ba5e-bdf132506581)

>I would still need to make an area where the HR staff can review submissions and make the button available under “My Forms” once you give the green light. 
 
>Let me know if you have questions.

She replied
>Looks great! I like **version two** with the larger button to show the policy. Will I be able to pull a completion report that contains employee ID number? Also, we will need a way to “download” the acknowledgement for their personnel file. 

I asked the executive team to send their comments on the policy by end of day Tuesday next week. After that, I only need Richard’s signature, then we will be ready to roll.

**Comment by dianamartin** [comment]
# 4/18/24
## Update Features from feedback
- [ ] Update AVL Procedure language [page](avl-procedure/)
- [ ] Form "version two" with the larger button to show the policy. 
- [ ] HR Reporting: Completion report that contains employee ID number? 
- [ ] Ability to “download” the acknowledgement for their personnel file.

**Comment by dianamartin** [comment]
@ChristinaTremel this is ready to review

**Comment by stephaniemoorer** [comment]
This looks to be complete. Can it be closed or does it need to be reviewed with HR team at sprint review?

**Comment by dianamartin** [comment]
# 6/26/24
We need to circle back with Jennifer, she wasn't ready for this to go live when it was done. I think we need to ask her in our upcoming meeting.

**Comment by stephaniemoorer** [comment]
**7/15/24** 
Discussed in HR Sprint Review
Jennifer will provide the new SOP language that needs to be added. Once that is updated we should be good to go.

**Comment by stephaniemoorer** [comment]
Per Jennifer W. this is ready to go once the current policy is uploaded to Knack. 

- [ ] get updated policy from Nedra
- [ ] upload policy to Knack (Diana)
- [ ] schedule meeting to discuss roll out of new form to TPW employees

**Comment by stephaniemoorer** [comment]
8/6/24
Informed HR team that the updated policy has been updated in Knack.
Will follow up during Sprint Review scheduled for 8/12

**Comment by stephaniemoorer** [comment]
8/12/24
During sprint review stakeholders approved the updated AVL policy/procedure in Knack
Still hidden until they develop a rollout plan/communications
No additional reporting needed, they will use the existing export feature
