### ISSUE TITLE
Update ETL for AMD Preventative Maintenance EDP Dataset

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16840]
Update ETL to refresh the preventative maintenance dataset daily. 

**Knack**
- SOURCE new private API table [here](https://builder.knack.com/atd/amd/pages/scene_1545/views/view_3869/table)

**Socrata**
- TARGET new dataset [here](https://datahub.austintexas.gov/Transportation-and-Mobility/Preventative-Maintenance/mudg-bik3)

**Comment by Charlie-Henry** [comment]
ETL deployed! Data should now be updated daily in that dataset.
