### ISSUE TITLE
[Spike] Explore AWS as a delivery option for CRIS extracts

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#16848]
CRIS offers an AWS-based delivery option as an alternative to SFTP-based delivery. It also offers an option to include CR3 pdfs in the delivery. We should test out both of these options.

**Comment by frankhereford** [comment]
Based on a previous conversation with @mddilley, an extract has been requested to the SFTP site with PDFs included. The dates are March 15th - March 31st, by /crash/ date, not processed date. This should be a few thousand crashes, so big but not huge.

**Comment by frankhereford** [comment]
In pursuit of this spike, I have:

* Created a new S3 bucket named `vision-zero-cris-exports`
  * Supports versioning
* Created a new IAM policy with a single permission of uploading an object: `txdot-upload-exports`
* Created a new IAM user with this policy: `vz-txdot-extracts`
* Configured the AWS delivery method in CRIS under Chia's account to use this

I am waiting for an export to be delivered, and I believe that will conclude this work. I'll report the results in the next comment.

**Comment by frankhereford** [comment]
I have also tested the delivery of PDFs in the export, and it works just like we'd hope. There is a new folder in the zip files that contains all the subject PDFs with the naming scheme: `<crash_id>.pdf`.

For a normal day, these won't be too huge and shouldn't pose an issue. For a reprocessing day however, these will ring in at more than a few GB, so that's something to be cognizant of.

**Comment by frankhereford** [comment]
It works!

I did have to give it `deleteObject` permission as well, which I don't love, but I also don't see a world where CRIS gets on this S3 bucket and somehow remembers all the files its uploaded and starts removing them. They can't list, they can just put and delete. 

But that said - AWS is a viable delivery option and I hope that we move forward on using it and put the SFTP mechanism out to pasture. This is better in every conceivable way in my opinion.

**Comment by johnclary** [comment]
such great news—thanks, Franke!!
