### ISSUE TITLE
[Power BI] Update SBO Complete On Time for SMD Dashboard

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#16856]
**Related to a problem?**
Lauren and Jordan were looking into the SBO completed on time measure and wanted to make a change on the way this is calculated.

**Desired Outcome?**
- If `Whereabouts/SBO` work orders have an Active Date after September 1st and it has not been closed as of October 1st, include on the next FY performance measure for SBO Completed On Time
- If this isn't possible, instead just filter down the SBO Whereabouts with Active Dates after October 1st

**Additional Context?**
- Add Jordan to the work session

**Comment by susannegov** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/1de9f366-0fb2-4a22-a730-47e0e8cf80cc)

**Comment by susannegov** [comment]
We are not going to add September as an exception for now. 

Jordan will talk to Lauren to see if this new metric is okay to have,

**Comment by susannegov** [comment]
As of 4/22, it was agreed that the current measure is okay.
