### ISSUE TITLE
Maximo Reports+Blocked Backlog List Generation

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#16855]
# Background 
- As we prepare for new hire 

## Plan 

- [x] review backlog for reports that are blocked 
- [x] meeting with rene and adry 5/3 to review report

### Process: 
- How to find list: 
  - Github Assignee -> Adriana
  - Search -> CTM
  - Lists under Blocked

**Comment by adry-martinez** [comment]
#13724 
@rebekkabry you can check this issue out.

**Comment by rebekkabry** [comment]
Working through each workgroup issues with the meeting handoffs. Closing issue.
