### ISSUE TITLE
IT Support: Laptop sound not working 

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#16851]
ST. ELMO

## What's the problem?
Laptops speaker are not working 
## What did you do to resolve the issue
Sending machine to dell for repair

**Comment by Matthew-M-TPW** [comment]
submitted a ticket to dell 188957674

They are send a box

**Comment by Vaishnav1397** [comment]
Received box, packed it and matt had taken it over to drop off.

**Comment by Matthew-M-TPW** [comment]
Dell returned the laptop
