### ISSUE TITLE
Issues with IPad not connecting to internet in field - Corey J.

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#16865]
Corey J.   has reached out to the Maximo team due to having issues with connecting to EZMaxMobile while out in the field. During one of the open door trainings with the Maximo team, his issues were addressed, and found that the device was not connecting to any type of internet. Corey stated that his device should have a "chip" that allows him to connect to the internet without the need of a Mi-Fi device. Notified user that the device might be having an issue and that he would need to reach IT services for assistance.

IPad device information: PWD-HQWVVF1-T1, COA57522

**Comment by Matthew-M-TPW** [comment]
Reached out to the user he was responding to an urgent request.

Will reach out next week.

**Comment by Matthew-M-TPW** [comment]
Attempted to contact user

**Comment by Matthew-M-TPW** [comment]
Reseated SIM card and the registered the card
