### ISSUE TITLE
IT Support: [Dell Latitude 5431 Spacebar Service Req. Case no-188973246]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#16862]
St Elmo
## Device & User Information (first name and last initial, no last names)
Laptop & Unknown
## What's the problem?
The space bar for the laptop is not working perfectly and it's getting stuck while entering in between keys.
## What did you do to resolve the issue
Have tried to cross check and see if it's still making the issue and it happened again. Contacted dell support for a box to send for service and will be receiving with in a day or two. Case No:188973246

**Comment by Vaishnav1397** [comment]
Waiting on the box to be delivered

**Comment by Vaishnav1397** [comment]
have received the box and handed it over to delivery partner by Matt.

**Comment by Vaishnav1397** [comment]
Sent it over and waiting to get return from Dell.

**Comment by Vaishnav1397** [comment]
WD Order number 450352788

**Comment by Vaishnav1397** [comment]
Status: Repairs have been started on computer and it's in progress. Estimation completion 04/30.

**Comment by Vaishnav1397** [comment]
Laptop shipped and Track no: 735257422048

**Comment by Matthew-M-TPW** [comment]
Dell returned machine
