### ISSUE TITLE
SPIKE: Allow attachment uploads for SIF after initial submittal

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16873]
### Research needed to determine the best build method for #12717 

Based on the Apps discussion on 4/17/24, there are 2 options to consider:
1. Adding a feature to the existing SIF mod
2. Move SIF to the TIA mod to take advantage of the workflow already in place for this need. 

**Deliverables for Chrispin:**
- High level overview of the basic changes needed for both approaches.
- Summary of your analysis and which solution makes the most sense from a technical perspective.

**Comment by ChrispinP** [comment]
Reached out to Nathan & Matiur, asking: Is it still the case that y'all would like review cycles for SIF so customer can re-submit documents? And if so, do y'all still want to keep SIF data separate from Transportation Study/TIA data?

The TDS team conferred and responded that SIF resubmittals are not needed at this time and that instead, there may be a stronger case for TIA Determinations to have iterative review cycles so they can track customer time for them.

Therefore, we do not need to build iterative review cycles for SIF worksheets at this time and that the multiple attachments enhancement has been a successful improvement for customers.
