### ISSUE TITLE
WZDX Gap Analysis and Roadmap 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16875]
## Analyze gaps and opportunities for ROW's work zone data as it relates to the scope of the WZDX standards.

1. **What gaps are there in release 1.0 (only TURP)**
2. **What gaps are there in ROW's wzdx overall (EX, lack of impact types, travel direction...)**
3. **Capture roadmap items for gap solutions**

**Comment by Charlie-Henry** [comment]
@TracyLinder I tried to apply FOLDERRSN 13263010 to the WZDX format. We have enough columns to output something super bare bones using the format. Assuming that all lanes are closed if AMANDA says its `Closure : Full Road` and direction of traveling being `unknown`. There's a few small things I wonder about like how we are only supposed to output work zones, not just any road closure like for an event like Austin FC, maybe there's something at the folder level that can limit it just to utility work or road maintenance/construction?

[wzdx_test.json](https://github.com/user-attachments/files/15838219/wzdx_test.json)

> 
> [Work Zone](https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/enumerated-types/EventType.md)
> 
> A work zone is an area of a trafficway with highway construction, maintenance, or utility-work activities. A work zone is typically marked by signs, channeling devices, barriers, pavement markings, and/or work vehicles. It extends from the first warning sign or flashing lights on a vehicle to the "End of Road Work" sign or the last traffic control device. A work zone may be for short or long durations and may include stationary or moving activities. Inclusions:
> 
> Long-term stationary highway construction such as building a new bridge, adding travel lanes to the roadway,1 and extending an existing trafficway.2
> Mobile highway maintenance such as striping the roadway, median, and roadside grass mowing/landscaping, and pothole repair.
> Short-term stationary utility work such as repairing electric, gas, or water lines within the trafficway.
> Exclusions:
> 
> Private construction, maintenance, or utility work outside the trafficway.

**Comment by Charlie-Henry** [comment]
Started a spreadsheet here tracking everything we're tracking currently and missing
https://docs.google.com/spreadsheets/d/1IsCcgUqOY6UMkPk9hh1uZZekvrXnqCRGlbwsr9-hP4k/edit?usp=sharing

**Comment by TracyLinder** [comment]
I believe we can close this now. We still need to work towards a roadmap, but that can be tracked on a different ticket if we need to.
