### ISSUE TITLE
[Feature] Applicant - "My Account" section

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#16881]
## As a customer, when I create my account I should have a landing place where I can start applications
Similar to the SMRT "My Accounts Info"
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/2e83628f-3cdd-4c9e-b41a-5899084eb319)

# User roles
- Admin
- User
- Customer

Login button -> Landing page -> start application

## Landing page
- Account Details view
   - Link to edit account (already exists) - see gitbook style guide
   - Account settings
- Customer Portal button menu view
- After Create Account - > link to My account

**Comment by patrickm02L** [comment]
## 4/24/24 Refinement
This has been completed.
<img width="832" alt="Screenshot 2024-04-24 at 10 44 36 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/5566727/159d38cb-2357-432c-9041-e0cbf4c0f5bf">
