### ISSUE TITLE
Required Documents page

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#16891]
See SMRT > Account details
- Required documents grid view ( more information modal pop up)

**Comment by dianamartin** [comment]
# 4/19/2024
## Build Notes
- [ ] Created `attachments` object
- [ ] Fields to include
- Attachment ID - auto-generated
- Attachment Type - multi-choice
  - Driver license 
  - Citizenship status documentation
  - Driving record documentation
  - Defensive driving documentation
  - Residency documentation
  - Other documentation
- Attachment - file
- More Information - this has to be configured on the record rule

## Consider this
- auto-generating a few of the main requirements when the Background Information form is submitted (record rule: that adds new attachment)
- User still also needs the ability to add other attachments, so add a menu button for that

**Comment by patrickm02L** [comment]
## 4/24/24
Rolling into #16565.

**Comment by susannegov** [comment]
Look into this from SMRT for required attachments using conditional rules with HTML

![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/3ac5469a-3388-43ea-861a-54cc35ecd093)

**Comment by susannegov** [comment]
# To do
## Conditional rules
This is based on attachment type. Setup with HTML formatting
- [ ]  Drivers license
```
What if I do not have a Texas Driver’s license? You will be issued one of two different types of Conditional Chauffeur Permits:    For college students, you will be required to show a current year transcript. The permit will need to be renewed annually. You will NOT have to obtain a Texas driver’s license if you are enrolled as a student.    For people who relocated to Texas, you will have a 90-day conditional permit. After 90 days, you must show proof of a Texas Driver’s license and a 3A Certified Texas Driving Record for us to issue you a non-conditional permit. 
```

- [ ] Residency documents
```
Provide your Resident Card or I-90
```
- [ ] Citizen Status Documentation
```
Provide your Naturalization Certificate or USA Passport, and Social Security Card.
```
- [ ] Driving record documentation
```
Can be obtained at www.dps.texas.gov. Note: Please make sure to select "Type 3A - Certified" when prompted Driving records cannot be older than 30 days. Driver’s license is less than 3 years old, you will need to also bring a Certified Driving Record from your previous state of residence or proof of at least 3 years Texas residency by bringing: a copy of your electric bill, bank statement, income tax return, insurance card, or letter from housing that reflects this.
```
- [ ] Defensive driving documentation
```
If you have any moving violations within the past 3 years, you will need proof of taking a Defensive Driving Classdated after the conviction date of the offense regardless of your driver’s license type.
```

**Comment by susannegov** [comment]
# To do
- [  ] Remove record rule for modifying more information since it is being done in conditional rules

**Comment by susannegov** [comment]
- [ ] Yes/no field for `is required citizen` in the application
- [ ] Auto add connected records
- [ ] In edit application, if the US citizen or moving violation field has changed, update is required field

**Comment by susannegov** [comment]
- Added non editable grid for attachments that is viewable when application status is submitted
- After application is submitted, the the editable attachment grid is hidden
- Hide editing buttons in page and show print application button
