### ISSUE TITLE
Map out service delivery workflow 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#169]
Create workflow diagram to document how requests come in and their path to delivery. 

The draft is [here](https://www.draw.io/?state=%7B%22ids%22:%5B%221CAxAypAhB8dve1FnthN4LvIyVfKpTFKA%22%5D,%22action%22:%22open%22,%22userId%22:%22104144569414369680128%22%7D#G1CAxAypAhB8dve1FnthN4LvIyVfKpTFKA).

**Comment by TracyLinder** [comment]
See #685 for updating the workflow draft. Closing this.
