### ISSUE TITLE
[Tech Services] TPW PC Refresh Checklist - Binaya S

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#16944]
## Steps
- [ ] Talking to user about backing up their computers
- [ ] Recommend user to export all bookmarks and store on OneDrive>Documents folder
- [ ] Recommend user to screen shot their ex, Quick Access favorites folder, desktop files layouts, pinned applications on desktop 
- [ ] Store other OneDrive>Documents folder
- [ ] Check their Absolute/NetMotion profile (they need to be in TRN SAML profile)
>Ask if they access AMD traffic cameras?

## Software Checklist
- [ ] Avaya one-X phone 
- [ ] Adobe
- [ ] ArcGIS 
- [ ] AutoCAD/AutoCAD 3D
- [ ] BlueBeam 
>if user wants both (Adobe & BlueBeam), ask why?
- [ ] SketchUp 
- [ ] MS Project
- [ ] MS Visio

## Hardware Checklist
Check these devices for outdated models, change their mobile power adapter (round --> USB-C)
>Does the user need a GIS Modeling computer?
- [ ]  GIS Laptop w/ specialist docking station
- [ ]  Laptop
- [ ]  Power supply
- [ ]  Docking station

**Comment by Matthew-M-TPW** [comment]
@scottreedy this user is going to need a precision machine

**Comment by Vaishnav1397** [comment]
Got the precision machine and will check with user and deploy accordingly.

**Comment by Vaishnav1397** [comment]
Checked with user on deployment. Mentioned that he didn't get the old laptop to return, and he would like to get the new one deployed this week or sometime next week.

**Comment by Vaishnav1397** [comment]
Checked with the user and he is using a desktop at office location. Seems he have a latest 5440 laptop. @Matthew-M-TPW Can you please update your sheet and records accordingly.

**Comment by Vaishnav1397** [comment]
Checked with matt and no need to swap out any laptop to user as he has a new one.
