### ISSUE TITLE
Activity log says updated team member notes when role is updated

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#16950]
I noticed that when I update a personnel's role, the activity log says I updated the notes. I'll open an issue

_Originally posted by @chiaberry in https://github.com/cityofaustin/atd-moped/pull/1320#pullrequestreview-2020541447_

**Comment by mddilley** [comment]
@tillyw I came across this issue today wanted to check in on it. I see #17450 as a higher priority than this one if you feel like pivoting at all. ↩️

**Comment by tillyw** [comment]
closed with https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/gh/cityofaustin/atd-moped/1424
