### ISSUE TITLE
[Bug] Unable to remove Lead or Sponsor in Project summary view

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#16964]
In the project summary, we can't remove the selected lead or sponsor because the graphql mutation definition expects a non-null input. These columns are nullable in the database so we should be able to null them out.

Url: https://moped.austinmobility.io/moped/projects/1909?tab=summary

**App:**
<img width="1161" alt="Screenshot 2024-04-24 at 5 45 57 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/37249039/a97264a7-b489-4081-a524-28010195bd39">

**Payload:**
<img width="633" alt="Screenshot 2024-04-24 at 5 45 33 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/37249039/94ff551c-c9a2-43f7-9375-f6c2f1c3d893">

**Error:**
<img width="633" alt="Screenshot 2024-04-24 at 5 45 19 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/37249039/ff1aabc0-1348-4335-b35f-cf0a7c2bff66">

**Comment by mddilley** [comment]
@chiaberry @amenity I put this in **Needs Scoping** since I wasn't sure if these were required fields. That would change how to fix this, but I don't think that they are required and can be removed from a project.

**Comment by chiaberry** [comment]
@mddilley afaik they are not required, so we should be able to clear the lead or sponsor. thanks for finding the bug and opening an issue!

**Comment by amenity** [comment]
Not required... and this is a kinda icky bug! Thanks for catching. I'd call it high-priority in bug rankings.
