### ISSUE TITLE
Maximo Recurring Meeting Handoff 

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#16988]
# Background 
In support of Maximo Assessment, we are revamping the recurring Maximo meetings. 

# Goals 
- [x] Map all current meetings, [add to document](https://cityofaustin.sharepoint.com/:x:/r/sites/tpwDTS/Shared%20Documents/Projects/Maximo%20Assessment/Maximo%20Support%20-%20DTS%20Overview.xlsx?d=w97a3e743d2dc4644961dcda02012297b&csf=1&web=1&e=dPxDbY) 
- [x] Reschedule all meetings 
- [x] Discuss communicating a hold on project requests for next 30 days, pending new hire and project review for scoping and prioritization. @dianamartin 
- [x] Plan to hand off in the next 2-3 weeks, after all meetings have been introduced

<img width="853" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekthQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8cbd7ea2665295e24f79eb74da487407b29b383/image.png" alt="image.png" />

**Comment by rebekkabry** [comment]
@adry-martinez can you [add the meeting frequencies in the chart](https://cityofaustin.sharepoint.com/:x:/r/sites/tpwDTS/Shared%20Documents/Projects/Maximo%20Assessment/Maximo%20Support%20-%20DTS%20Overview.xlsx?d=w97a3e743d2dc4644961dcda02012297b&csf=1&web=1&e=GZEMbM&nav=MTVfe0RFQTBCNEM1LTg3Q0EtNDg1Ni04NTU3LTg0M0FCMzE2QzIwMX0)  or direct me to where is it already listed? Thank you.

**Comment by adry-martinez** [comment]
@rebekkabry added!

**Comment by rebekkabry** [comment]
# 5/8/24
**To Do List** 

- [ ] + get current list of meetings and invitees 
- [ ] + add to chart
- [ ] + get associated issue for meeting, add as assignee 
- [ ] + reschedule meetings from rebekka account

**Comment by adry-martinez** [comment]
@rebekkabry do we want to mark this as completed?
