### ISSUE TITLE
Prototype KNACK OCE-Encampment

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#16999]
Here are the links to the forms:

- [Site Report](https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&FormId=9hleXKumRUux0L5GCKmmf89QkXwSczlFrmWbY6oM36xUMkpFQzVLRFVOUTRFUkpFSjhXVzY1MU5OSyQlQCN0PWcu&Token=1434c45d78e14f3baf7f15ec98acb565)
- [Posting Report](https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&FormId=9hleXKumRUux0L5GCKmmf89QkXwSczlFrmWbY6oM36xUQ0QyOVRGM1JVU0lVUjJGS1hHS1g4SjFSUyQlQCN0PWcu&Token=cd72805c158d4ed58f1acab2340ae224)

**Comment by dianamartin** [comment]
# Build Notes
## Tables
- [ ] Attachments
- [ ] Underpass Clean up work orders
- Created Date
- Created By 
- Action Taken
  - Completed
  - Skipped
  - Rescheduled
Reschedule Date
Incidents or Injuries
- Yes
- No
Number of Incidents - # number field
Incident Details
Number of Trailers filled to nearest (1/4)
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/2bfc2c58-d1a4-4150-8e86-73d51237a395)
Notes/Comments
- [ ] Ability to attach multiple BEFORE and AFTER pictures
- [ ] Ability to attach multiple POSTING pictures
- [ ] Locations - list of all locations 
- [ ] Supplemental Sites
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/cae3876b-e9ac-402c-9cf9-8b60b7b84b62)

**Comment by dianamartin** [comment]
# 5/3/2024
- [x] Synced with Adry and showed her an app walked through of this OCE Encampment build

## Encampment Work Order Table
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/2b1d8dde-96ac-448a-8439-aafe28d6ffed)

## New Encampment Work Form
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/d9f08917-7ab1-43e0-ba4b-9b158ebebd13)

### Reschedule Validation
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/fb59b369-2b94-4b7f-b318-a2bc49a5055a)

### Incident Validation
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/7aa50a7a-21e4-4d75-9400-5ceb76c13f44)

## Details Page with Attachment Form & Table
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/967a35b6-d0cd-4637-a974-32e2c0cd4a34)

## Attachments Form
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/124e5610-f3e3-4a83-b33d-dcb87d06ce2b)
>Had to change the `attachment` table, Attachment "File" wasn't showing up properly. Switched to the "Photo" type, was able to set up the Photo thumb nail 100x100. Looks way better!

**Comment by TracyLinder** [comment]
### Stakeholder Review (5/16/24)

**Updates Needed:**

- [ ] New feature for users to manage encampment locations
- [ ] New info: Tonnage collected
- [ ] New info: Work order status | Values are: `Need to Inspect, Need to Post, Posted, Skipped, Need To Reschedule, Rescheduled, Completed, In Progress`
- [ ] New info: Estimated Schedule Date
- [ ] New info: Completed Date
- [ ] Create Comments Table with comment types `Safety Note, General Comment`
- [ ] New Advanced Reporting page
- [ ] Feature to edit work order details
- [ ] Implement an ID logic of YY-randomly generated number

**Comment by dianamartin** [comment]
# 5/16/24
## Diana's Meeting Notes
### On the fly edits
- [x] Added "Location" with XY coordinate inputs (not required)
- [x] Added "Manage Programs" drop down tab
  - [ ] Change Page to be called `Underpass Clean Up Program`

### Feature Updates
- [ ] Make entry form shorter & quicker
- Move to details page
  - [ ] "Action Taken" 
  - [ ] Rescheduled
  - [ ] "Incident or Injuries" fields
  - [ ] NEW! "Tonnage collected"
  - [ ] Notes/Comments

### New Enhancements 
- [ ] Add "Work Order Status"
  - Need to Inspect
  - Need to Post
  - Posted, Skipped
  - Need To Reschedule
  - Rescheduled
  - Completed
  - In Progress
- [ ] Unique ID: YY-MM- 4 or 5 digit 
- [ ] Add Comments form & table on details page
- field headings
  - Comment Type:
  - [ ] `General`
  - [ ] `Safety`
- [ ] Report page w/ Advanced Search page

**Comment by dianamartin** [comment]
## New Work Order Form
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/e9a53858-a375-4133-9da8-4c638313154a)

## Edit Form
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/bc486b59-26e0-41e2-9136-447a094d7f68)

## Add Comments Form/Table
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/6fc1ed45-4619-40af-a82f-a388e76f840b)

## Work Order Status
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/581c0f32-d3b1-486d-9bce-c6e4ff50a761)

## Manage Underpass Locations
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/986588b8-5453-4fa6-a616-306ed86ec425)

## Report Page 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/77a8beef-1a23-4764-974f-3ee6b7376231)

 # LEFT TO DO
- [ ] Advanced search page
- [ ] Unique ID

**Comment by TracyLinder** [comment]
I moved the remaining items to a different issue. Closing this.
