### ISSUE TITLE
Maximo Account [Modify] update account to add additional Security Groups

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#16992]
Please update access in production for view of all maximo DTS related work orders.

**Comment by adry-martinez** [comment]
### April 29, 2024
Attempted to add both Diana and Rebekkah to relevant start centers but currently receiving an error: 

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/bf37e5ab-3972-49f0-b09f-8539af21d896)

CTM Maximo is made aware and is working on the issue in PROD.

**Comment by adry-martinez** [comment]
### May 6, 2024

Requestor has been notified that all start centers have been added to her profile. 
@rebekkabry were you able to see all the start centers? Please let me know so that I can close this ticket. Thanks!
