### ISSUE TITLE
RW Unpaid Fee Flag (SS) (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17028]
**Acceptance Criteria**
- System should check to see if any of the People records in the folder have unpaid fees when user makes the following attempts. 

<span><span class="ui-provider ed bdw azt bsd bse bsf bsg bsh bsi bsj bsk bsl bsm bsn bso bsp bsq bsr bss bst bsu bsv bsw bsx bsy bsz bta btb btc btd bte btf btg bth bti" dir="ltr">
Folder Type | SubType | Process | Attempt
-- | -- | -- | --
RW | Street Vendor | Vendor Permitting | Update Issue and Expiry Dates
RW | Valet Operator | Valet Operator Permitting | Update Issue and Expiry Dates
RW | Valet Parking Annual | Annual Valet Permitting | Update Issue and Expiry Dates
RW | Temporary Right of Way Use Permit | Permit Extension | Manual Extension or Extension Granted

</span></span>

- System should check to see if any of the People records in the folder have unpaid fees in any of the following folder types: RW, EX, LC, ECV with ATD subtype, GF with ATD subtype, or DS.
- If there are unpaid fees, system must allow the attempt to complete but throw a warning message "A People record from this folder has UNPAID fees"

**Comment by SubhaShroff** [comment]
@Nadin-Nader please create a DEV deployment request. Thank you.
[17028 - 9550845f044e7d403067208f7b50331d2a5f862d DEV Deployment Plan.docx](https://github.com/cityofaustin/atd-data-tech/files/15358207/17028.-.9550845f044e7d403067208f7b50331d2a5f862d.DEV.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent tp the DevOps Cm Team to be deployed to DEV under **SCTASK0422984**

**Comment by Nadin-Nader** [comment]
Conversation with Kyle about Subha's Question:

> [Yesterday 2:47 PM] Nader, Nadin
> Hi Kyle. Hope you are doing well. Hey do you have a sec for a question on 17028 (RW Unpaid Fee Flag)?
> [Yesterday 2:48 PM] Nader, Nadin
> RW - TURP - Permit Extension Process - Manual Extension attempt already has a warning message.
> 'Please make sure Applicant's Bond, Insurance, Fee and Date Range information are up to date.'
> Now with this ticket, the requirement is to add - "A People record from this folder has UNPAID fees".
>  
> Can we combine both messages as we can't display two warnings with one attempt? 
> If we can, any suggestion to the combined warning message wordings what the users want it as?
> [Yesterday 3:20 PM] Kampe, Kyle
> I don't think we'd want to combine the messages into a single message, because then it would presumably display even in instances where only the existing warning message applies to a scenario but not the new text warning of unpaid fees. We might want to discuss this one more in tomorrow's meeting. I really thought it was possible to have an additional warning message display after okaying an initial one.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this 2nd Dev commit has been sent to the DevOps CM Team to be deployed in DEV under  **SCTASK0426059**

**Comment by SubhaShroff** [comment]
[17028 - 9550845f044e7d403-583e4dc9bb94a3f33f-8122bcaf2f48b0e79f10  TEST Deployment Plan.docx](https://github.com/user-attachments/files/15519091/17028.-.9550845f044e7d403-583e4dc9bb94a3f33f-8122bcaf2f48b0e79f10.TEST.Deployment.Plan.docx)
@Nadin-Nader  Thank you for creating DEV deployment request. I tested and working now as expected. Please create a TEST deployment request.

It has following 3 commits:
1.	**9550845f044e7d403067208f7b50331d2a5f862d**
Process_RW_00050680: PROCESS_RW_00050650: Process_RW_00050590: Process_RW_00050630: Add a warning message, if any associated people have unpaid fees

2.	**583e4dc9bb94a3f33f39990d077a4d07f13f4fec**
Process_RW_00050680: PROCESS_RW_00050650: Process_RW_00050590: Process_RW_00050630: Added a logic to check unpaid billed fees as well, to display the Warning message with the respective attempts in the above process procedures

3.	**8122bcaf2f48b0e79f100bb487ce23cd33829ae3**
PROCESS_RW_00050680.sql: Remove the error display at this point.

Thank you.

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0427118 - TEST deployment request is created with Priya's help. Thank you.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to TEST please UAT

**Comment by SubhaShroff** [comment]
@Nadin-Nader I tested the deployments on TEST. This ticket is ready for UAT. Thank you.

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff UAT on Test approved. Thank you!

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0429097**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is deployed in PROD, though Hari didn't update the status yet on SCTASK0429097. But he confirmed that its deployed.
This is ready for UAT on PROD.
Thank you.

**Comment by KyleErich** [comment]
@Nadin-Nader @SubhaShroff UAT on Prod approved. Thank you!
