### ISSUE TITLE
Maximo Training - SBO Forestry Maximo Overview PPT

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17036]
Google Slides: [Forestry Maximo Introduction](https://docs.google.com/presentation/d/1QwmXNqT93p7RjBugQ0N0Bo9UxMHHkvRxPSN5NwfuSlQ/edit?usp=drive_link)

**Comment by adry-martinez** [comment]
This presentation is complete. 
@Rebekkabry please review this with the forestry team. 

Thank you!

**Comment by rebekkabry** [comment]
This has been reviewed with team. There are details they would like to add. Working within Maximo Assessment Discovery and stakeholder syncs to document additonal points. 

![Uploading image.png…]()
