### ISSUE TITLE
Maximo Training - SBO Utilities and Structures Maximo Overview PPT

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17035]

**Comment by ReneVarg25** [comment]
### 5/8/2024
Presentation created and reviewed with Michael D.
https://docs.google.com/presentation/d/12IMhQfqI9D7vwUFbpOEJgxSavb_jIqVIGe9Bc4tUFLk/edit#slide=id.g2cfd800d4c1_1_1182

**Comment by adry-martinez** [comment]
### May 14, 2024 

Gave Rene feedback. Just needs to update Report slides then schedule Maximo USD presentation 🎉
