### ISSUE TITLE
2024, 03 March

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17042]

**Comment by ReneVarg25** [comment]
### 3/14/24
Subject: MAXIMO - EZMaxMobile - Intermittent Outages

Hello,

The EZMax mobile application on Maximo PROD is experiencing intermittent outages and so you may see an error when attempting to access.

We are working to clear this issue and will send an all-clear as soon as possible.

Thanks,

Mario Villarreal
IT Application Consultant
Enterprise Asset Management & Business Intelligence
