### ISSUE TITLE
2024, 01 January

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17043]

**Comment by ReneVarg25** [comment]
### 1/2/24
What's Happening?
 
There will be a one-hour outage tonight so the Maximo team can apply an update to the system.  
 
Start: Tuesday, January 2, 2024 - 9:00 PM CST

End: Tuesday, January 2, 2024 – 10:00 PM CST

Duration: 1 Hour
 
What is required of me?
Please save your work and log out before the so no progress is lost. It is possible you will be able to login but you may receive errors or strange slowdowns, behavior and hiccups in the system.
 
Who do I call for help?
 
If you experience any errors or problems after the planned outage, please contact the CTM Helpdesk and enter a ServiceNow ticket.

Happy New Year!!

Thank you,
Maximo Team
