### ISSUE TITLE
2023, 12 December

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17044]

**Comment by ReneVarg25** [comment]
### 12/13/23
What's Happening?
 
There will be a three-hour outage on Thursday evening so the Maximo team can apply an update to the system on how we utilize user accounts.  We must take the system offline and take a backup before completing the updates.
 
Start: Wednesday, December 13, 2023 - 9:00 PM CST

End: Wednesday, December 13, 2023 – 12:00 AM CST

Duration: 3 Hours
 
What is required of me?
Please save your work and log out before the so no progress is lost. It is possible you will be able to login but you may receive errors or strange slowdowns, behavior and hiccups in the system.
 
Who do I call for help?
 
If you experience any errors or problems after the planned outage, please contact the CTM Helpdesk and enter a ServiceNow ticket.
 
Thank you,
Maximo Team
