### ISSUE TITLE
2024, 04 April

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17041]

**Comment by ReneVarg25** [comment]
### 4/17/2024
What's Happening?
There will be a 2-hour map outage in Maximo Production while CTM GIS performs upgrades.  Maximo will still be functional although you may experience some slowness during the upgrade window.
Start: Wednesday, April 17, 2024 - 5:00 PM CST

End: Wednesday, April 17, 2024 – 7:00 PM CST

Duration: 2 Hour
What is required of me?
Nothing, the map will not function during the upgrade window and users may experience some slow response from the system.
Who do I call for help?
If you experience any errors or problems after the planned outage, please contact the CTM Helpdesk and enter a ServiceNow ticket.
Thank you,
Maximo Team

**Comment by ReneVarg25** [comment]
### 4/25/2024
What's Happening?
 There will be a 1-hour outage in Maximo Production while we apply an update to the system.  
Start: Thursday, April 25, 2024 - 10:00 PM CST

End: Thursday, April 25, 2024 – 11:00 PM CST

Duration: 1 Hour
 What is required of me?
Please save your work and close/log out of Maximo prior to the outage.
 Who do I call for help?
 If you experience any errors or problems after the planned outage, please contact the CTM Helpdesk and enter a ServiceNow ticket.
Thank you,
Maximo Team
