### ISSUE TITLE
2023, 11 November

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17045]

**Comment by ReneVarg25** [comment]
### 11/16/2023

What's Happening?

There will be a three-hour outage on Thursday evening so the Maximo team can apply an update to the system on how we utilize user accounts.  We must take the system offline and take a backup before completing the updates.

Start: Thursday, November 16, 2023 - 8:00 PM CST

End: Thursday, November 16, 2023 – 11:00 PM CST

Duration: 3 Hours

What is required of me?
Please save your work and log out before the so no progress is lost. It is possible you will be able to login but you may receive errors or strange slowdowns, behavior and hiccups in the system.

Who do I call for help?
 
If you experience any errors or problems after the planned outage, please contact the CTM Helpdesk and enter a ServiceNow ticket.

Thank you,
Maximo Team
