### ISSUE TITLE
2023, 10 October

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17046]

**Comment by ReneVarg25** [comment]
### 10/12/23
What's Happening?

There will be a one-and-a-half-hour outage on Thursday evening so the Maximo team can apply some configurations and reboot the system.  These updates will add functionality for Kurve reporting.

Start: Thursday, October 12, 2023 - 9:00 PM CST

End: Thursday, October 12, 2023 – 10:30 PM CST

Duration: 1.5 Hours

What is required of me?
Please save your work and log out before the so no progress is lost. It is possible you will be able to login but you may receive errors or strange slowdowns, behavior and hiccups in the system.

Who do I call for help?
 
If you experience any errors or problems after the planned outage, please contact the CTM Helpdesk and enter a ServiceNow ticket.

Thank you,
Maximo Team
