### ISSUE TITLE
IT Support: Update Night Hawk conferance room to Windows 11

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17060]
BEN WHITE
## What's the problem?
Updated computer to Windows 11

## What did you do to resolve the issue
Tested the machine out by logging in and updating the drivers

**Comment by JBStrangenew** [comment]
Do Not Delete:
 BEN WHITE
## Device & User Information (first name and last initial, no last names)

## What's the problem?
Updated computer to Windows 11

## What did you do to resolve the issue
Tested the machine out by logging in and updating the drivers
