### ISSUE TITLE
[Enhancement] Update SSN input field

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#17065]
## Description

Modify SSN input in the application form to accept:
See guidelines from US government design standards: https://designsystem.digital.gov/patterns/create-a-user-profile/social-security-number/

## Note
See regex example

<img width="584" alt="Screenshot 2024-04-30 at 4 25 34 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/5566727/9a7ddfad-32d4-4e1f-afdb-1ce16d5e142a">

**Comment by susannegov** [comment]
# Reviewing validation
## User Input
- [ ] Include spaces
- [ ] Without spaces
- [ ] Include dashes
## SSN Validation
TIL there's a few ways SSN can be validated as incorrect
- SSA will not issue SSNs beginning with the number “9”
- SSA will not issue SSNs beginning with the number “666” in positions 1 – 3 (ex. 666-XX-XXXX) 
- SSA will not issue SSNs beginning with the number “000” in positions 1 – 3 (ex. 000-XX-XXXX)
- SSA will not issue SSNs with the number “00” in positions 4 – 5 (ex. XXX-00-XXXX)
- SSA will not issue SSNs with the number “0000” in positions 6 – 9 (ex. XXX-XX-0000)

### Source: 
- https://designsystem.digital.gov/patterns/create-a-user-profile/social-security-number/
- Social Security is changing the way SSNs are issued. (n.d.) Retrieved on July 20, 2022, from https://www.ssa.gov/kc/SSAFactSheet--IssuingSSNs.pdf

**Comment by susannegov** [comment]
# JS code changes
- [ ] Added input masking
   - Includes hyphens
   - Includes no spaces
   - Includes spaces
   - Includes some spaces
- [x] Updated regex from to match USWDS input masking `^(?!(000|666|9))\d{3} (?!00)\d{2} (?!0000)\d{4}$`

**Comment by patrickm02L** [comment]
## 5/16 
Reviewed the functionality of the regex validation and it works well. Feel free to close if there aren't any other improvement.
