### ISSUE TITLE
Update Amenity's AGOL permissions

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#17073]
I was working in AGOL on [Moped Map symbology options](https://github.com/cityofaustin/atd-data-tech/issues/16906). I don't have permissions to create new maps, so wasn't able to save my work as I went. That meant every time I refreshed my browser or clicked into the wrong place in the left sidebar all my edits disappeared. 😞 

I don't have a PC, so can't run ArcGIS locally.

**Comment by andrewshensky** [comment]
ServiceNow request has been submitted to get privledges elevated (INC0388833). Typically takes a day or two for privledges to be updated

**Comment by amenity** [comment]
Thanks, @andrewshensky! 🙏🏻

**Comment by amenity** [comment]
FWIW, they updated my permissions immediately! 😊  🎉
