### ISSUE TITLE
Forestry Support of Pavement Work

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17083]
### 🎯  Objective 
To discuss best method to relay work between Forestry and Pavement Ops.

### 🤝 Participants
**🌳 Forestry Team:**
Shane, Lisa, Cody

**🦺 Pavement Ops:**
Jermaine, Andre, Aaron, Jonathan, John F., Frank, Stephen

**📈 SBO Consulting:**
Dave A., Richard D., Greg G.

**🖥️ DTS Maximo:**
Rene, Adriana

### 📓 Meeting Notes

- Forestry will need 4-6 weeks of notice will be needed to abate private tree issues. 
- Heritage tree are protected by the City.
- Jonathan has been providing great photos for Forestry. 
- Forestry team will make assessments to determine whether this can be abated.
- E-mail currently used. Photos sent out. UFG reviews e-mails and creates work order.  

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/b444da22-e5c7-4273-9aec-7634ee2d542e)

- Proposal to use Maximo as FF2. Add portlet on Forestry's start center. Add portlet to Pavement Ops start center.
   - Preference to communicate is via e-mail.
- Proposal to use Maximo scheduled start. Add portlet with WOs on Hold with Other City and have scheduled start. 
- Issues are with inspections that need to be 2 months ahead of schedule to give Forestry ample time to prepare and respond.
   - Example: May 2024 inspections for October 2024 projects. 
   - Need to assess the growing season
   - Having a schedule for the season would be good. Can prioritize areas in town that traditionally low limb, live oak, pecan situations.
      - Travis Heights neighborhood is notorious. 

- Best solution: Have Pavement Ops to inspect time ahead. No harm to sharing schedule ahead of time.

------

### ✅ Action Items
- None at this time until SBO stakeholders are ready to brainstorm/collaborate a Maximo process of notification.

**Comment by adry-martinez** [comment]
### June 13, 2024

### 🤝 Participants
**🌳 Forestry Team:**
Shane, JR, Cody (Michael)

**🦺 Pavement Ops:**
Andre E., Jonathan G.

**🖥️ DTS Maximo:**
Rene, Adriana

### 📓 Meeting Notes
Purpose of meeting to further integrate Pavement with Tree process. 
Pavement started creating Tree WOs re: Pavement requests.

Added TRANSPORTATION, PAVEMENT OPS under TICKET_TYPE attribute. 
<img width="1073" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1poQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1951867f4f520150699727d123b9703a64eb7546/image.png" alt="image.png" />

<img width="1328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0poQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d897a645cdc98128623b5b8fdb62c8218346f9f/image.png" alt="image.png" />

Created Portlet for Pavement Tree Requests on Forestry Start Center 
Pavement requested to add portlet to Pavement Ops

<img width="767" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0ZoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--268eed0f8ac315d04d2b13312b686a6688bed495/image.png" alt="image.png" />

Hanger Date is in **Description**.
**Scheduled Start** is tentative work start for Pavement Ops. 
Pavement Ops will create work orders for Trees as long as the Specs tab calls for:
1. **Requesting Agency** is SBO
2. **Ticket Type** is Pavement Operations

------

### ✅ Action Items
- [ ] Maximo DTS to create a help guide of fields to complete for Pavement to notify Forestry re: tree requests for Service Plan

**Comment by rebekkabry** [comment]
- Adry created before she left: 
- ATV added to the specs tab. 
- Portel was created, shows 1NEW 
- Processing work, can be closed.
