### ISSUE TITLE
IT Support: Clean Ben white storage Room

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17086]
BEN WHITE 

## What's the problem?
The storage room needs to cleaned and organized

**Comment by Vaishnav1397** [comment]
Will make sure to re-check and organize everything on our side of the racks and ground accordingly.

**Comment by Vaishnav1397** [comment]
Matt and Craig have cleaned up everything last week. But we might need to add up more space over racks, can place monitors accordingly.
