### ISSUE TITLE
[BUG] Crash coordinates render as `NaN` when they should be blank

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#17104]
When a crash does not have a latitude or longitude, the values render as `NaN` in the VZE. For example, see [crash #19389730](https://visionzero.austin.gov/editor/#/crashes/19389730).

Instead, we should render `None`

<img width="683" alt="Screenshot 2024-05-02 at 1 28 30 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/14793120/ce8a8fd2-047d-493e-8122-6fd2fb33a976">

**Comment by mddilley** [comment]
@johnclary I ran into another really gross bug when I was testing the different UI states on this one. I'll bundle the fix in the PR for this one.

<img width="609" alt="Screenshot 2024-05-09 at 10 00 16 AM" src="https://github.com/cityofaustin/atd-data-tech/assets/37249039/fdee691b-f7fe-4c96-bf8d-4176f6c87761">

**Comment by johnclary** [comment]
gross indeed. thanks @mddilley!
