### ISSUE TITLE
[Feature] Allow selecting multiple impoundments to associate with invoices

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17116]
## Description
Currently when creating an invoice, impoundments can only be associated one at a time. Implement a feature that allows selecting multiple impoundments from a list and associating them all at once with an invoice.

## Acceptance Criteria
- On the invoice creation page, show a list of all unpaid impoundments 
- Add a checkbox next to each impoundment to select multiple
- Show the selected impoundments added to the invoice items

## Notes
We've implemented a similar process for the finance app.

**Issues**
- https://github.com/cityofaustin/atd-data-tech/issues/1100
- https://github.com/cityofaustin/atd-knack/pull/2

**Code**
- https://github.com/cityofaustin/atd-knack/pull/2/files

## Prototype
- [Knack App](https://atd.knack.com/test-2024-june-12-smrt--shared-mobility-reporting-tracker#fees-payments/invoice-details/61b8b4a5c198f8001e80c3c2/?view_1044_filters=%5B%7B%22field%22%3A%22field_467%22%2C%22operator%22%3A%22is%20blank%22%2C%22value%22%3A%22%22%7D%5D)

**Comment by patrickm02L** [comment]
## 5/8/24
@dianamartin @ChrispinP to do some background work to get the Apps requirements documented.

**Comment by dianamartin** [comment]
# 5/15/2024
Chrispin and I sync on the Finance and Purchasing Code
SMRT Application 
Invoice Details page - `scene_231`
Impoundments - `scene_78`

Items table - view_60
Invoice Items table - 

// Invoices table

```// Set scenes and views
var scene = "scene_4";

// Items table
var itemsView = "view_60";
var itemsEditableView = "view_16";

// Invoice Items table
var invoiceItemsAdminView = "view_681";
var invoiceItemsNonAdminView = "view_717";

// Invoices table
var invoicesView = "view_282";

// Invoice Items API view form scene and view
var invoicesAPIViewConfig = { scene: "scene_123", view: "view_698" };

// Invoice Items API view form scene and view
var itemsAPIViewConfig = { scene: "scene_336", view: "view_804" };

**Comment by dianamartin** [comment]
# 5/15/2024
Added to the "Invoice Details" (in PROD)
- [x] Impoundments associated to Provider
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/24fa9fa8-2cf7-4178-a538-729f85eb573d)

**Comment by patrickm02L** [comment]
## 6/12/24 Dev + Product Sync
- Diana walked through the Invoice options, we're leaning toward the first solution of adding checkboxes to the on the `Provider Impoundments` table so that staff can choose which of the unpaid impoundments will be added to the invoice.
- Diana's making a test environment for the Devs to start building
- Chia's going to do some initial investigation this sprint with the plan to pick it up on the 6/26 sprint cycle

**Comment by patrickm02L** [comment]
# 7/12/24 Review/QA

I created a new Invoice and two test records for Bird for testing. 

### Review 1
When trying to add impoundments, I was able to select them but when I pushed the button it didn't trigger an association. 

https://github.com/user-attachments/assets/f3d88de9-88a8-40cd-a428-38a37fa8d43e

Chia let me know that when cleaning up the code yesterday she forgot to clean up one part and introduced a bug. And all let me know that when the impoundment gets assigned it would dissapear from the table because it was filtered to show records without an invoice

### Review 2
Now I could select the record and when pushing the `Add selected to invoice` button they dissapeared after I refreshed the page.

https://github.com/user-attachments/assets/18371985-1754-48f9-974f-ae77e5ed194e

Chia recognized that she only refreshed the bottom view, and made it to where both views were refreshed. 

### Review 3
Realized that the impoundments showed up in the impoundments table and had the correct invoice associated with them. Also, realized that I had to `Add invoice items` manually to get them to show up in the Invoice Details page and subsequent PDF. 

https://github.com/user-attachments/assets/8cb9cc8c-f884-42cc-a1d0-21edb0d9ed85

Everything worked as expected. 

## Approved. 
Good to Go! 🚀

**Comment by patrickm02L** [comment]
## 7/16/24 Impoundments Review

Diana, Chia, and I met to discuss the functionality of the multi-select impoundments. The goal of the impoundments is make them selectable and move them from the "Provide Impoundments" table to the "Invoice Items" table. 

### Here are the key takeaways:

#### 1. Description ID 
- Verify and handle the details description to ensure the Invoice Description is the device ID
- Consult Andrea about the Invoice Description

#### 2. Automatic Refresh
- Refresh when submission button is triggered
- Ensure a banner appears after submitting multi-select options

#### 3. Transaction amount should match impoundment fee amount
- Field mapping would need to be implemented when generating invoice items from selected impoundments, so that the transaction amount pulls from the associated impoundment fee

#### 4. Invoice_item table location
- In test the view ID is moving from 1044 to 1059

#### 5. Resize checkboxes
- Look at the finance CSS to see how checkboxes were resized

**Comment by chiaberry** [comment]
Test app ready for re-review

Patrick brought up question of deleting Invoice Items, and if anything should happen when invoice items are removed.

**Comment by patrickm02L** [comment]
## 7/31/24
@dianamartin please make sure to add the trigger to clear out the Invoice ID if it's removed from the Invoice Items table, and can be found in the Provider table.

**Comment by chiaberry** [comment]
I opened this PR, the code is in the test app: https://github.com/cityofaustin/atd-knack/pull/161

I have checked to make sure the fields have the same ids in prod, so in theory nothing should need to be updated when moving it to the SMRT prod app. 

If you need any dev assistance while I'm ooo, devs can help triage.

**Comment by dianamartin** [comment]
# 8/2/24
@patrickm02L 
- in the Test Environment I added a "trigger button" called `Remove connection`. It should blank out the invoice connection. 

## Steps to remove connection
- Click "Remove" icon on Invoice Items" table
- Click "Disconnect" on Impound ID
- Invoice ID connection will become blank

**Comment by patrickm02L** [comment]
## 9/3/24
Before moving the code into production we'd like to test with Andrea first to make sure things are working. Will give the go ahead to transfer the test code to production once we've gotten Andrea's approval.

**Comment by patrickm02L** [comment]
## 9/18
@chiaberry we demoed with Andrea and Michael from SMS and they were okay with the functinality as is. 
@diana can we make sure the trash can in the Impoundments table, and the "disconnect" in the Provider impoundments table are wired up

Chia will add the code, and comment out, comment in once Diana's changed are implemented.

**Comment by dianamartin** [comment]
# 9/18/24
- [x] Added new trigger button on the "Provider Impoundments" table
- [ ] The "Remove" field is hidden when the Invoice is "PAID", so if "UNPAID" the button will appear
- [x] Named "Invoice Connection"
  - [x] Removes connection to invoice field
  - [x] Updates audit fields: Modified By/Date
![image](https://github.com/user-attachments/assets/69623c55-bd4a-40a5-8978-e4bb70674205)
