### ISSUE TITLE
Maximo Enhancement: Updating Downtown Maintenance Classification to capture special projects

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17147]
SBODTE is requesting to capture special projects which DTS recommended to use Specifications to best highlight such work orders in a report.

**Comment by adry-martinez** [comment]
### June 12, 2024 

Special projects is defined as special requests made outside of their PM plan. SBODTE (Vincent S.) is asking to be able to record these "special projects". 

We will have to meet with stakeholders to figure out how they are tracking their special projects now. And where in the Specifications tab we would need to consider adding a new attribute to capture these projects.

**Comment by rebekkabry** [comment]
Sent questions to stakeholders to discuss with Vincent during their team meetings. They wiil provide feedback based off discussed during upcoming DTS discussions.

**Comment by rebekkabry** [comment]
# 10/7/24 

@rebekkabry 
- [ ] look and confirm created, linked to parents/grandparents. 
- [ ] need to cancel out Brazos "all" 
- [ ] added in C Ceazer 9th to Red River, and 9th on Trinity

**Comment by rebekkabry** [comment]
### Notes 11/8/24 
- scheduled meeting with Eli and Vince to review sidewalk report, work order clean up needs and the open/non resolved DTS tickets. for 11/18/24

**Comment by rebekkabry** [comment]
# 12/16/24 

During DIST weekly sync, Eli advised we can close this out.
