### ISSUE TITLE
Maximo Report Request [Modification] - Unmetered Water Usage Report

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17145]
Update unmetered water usage reports (with/without detail) to filter by work group

**Comment by adry-martinez** [comment]
@rebekkabry this was an ask by the team to filter out what they need to see. I guess they changed their ask but I do still want to pursue modifying this report because it is a common ask from pre-merger.

**Comment by GaneshKamarapu** [comment]
@adry-martinez @rebekkabry I have made the changes and deployed . PLease validate.

**Comment by adry-martinez** [comment]
<img width="1298" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3MyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b38e3ede916689386e740de983ef8bf82ca30f74/image.png" alt="image.png" />

@GaneshKamarapu please review the report for the missing parameters.

**Comment by adry-martinez** [comment]
@ganeshkamarapu confirmed parameters added 

<img width="595" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkEyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36f934249b409344f03786536bfdc3718d0f28ca/image.png" alt="image.png" />


Issue closed.
