### ISSUE TITLE
[Bug] No crash extract data received from CRIS 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#17155]
As discussed in [this slack thread](https://austininnovation.slack.com/archives/CM9MK950S/p1715035425167049), we have not received any zip files from CRIS for two days and counting.

We need to:
- Reach out to CRIS to see if they're aware of any issues delivering file extracts
- Prioritize #16953 so that we can rule out issues with our own SFTP server
- Backfill CRIS records, once we're back to normal

**Comment by frankhereford** [comment]
catching up on this - I did a backfill from 5/4/2024 - 5/7/2024 to catch us up for today. No word from CRIS, and I think we may be able to get to S3 sooner than they may get to resolve this, fwiw.

**Comment by frankhereford** [comment]
Never heard back from CRIS, but we end-ran around it by transitioning to a S3 delivery method, and that seems to be working. I'm going to close this one out.
