### ISSUE TITLE
Account Signup/Rejected/Verification Workflow Emails

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17151]
This email is triggered when the reviewer clicks the reject button on the account request. 
- System will send an email to the account holder
- System will incorporate the text in the `Rejection Comment` filed

**Comment by ChrispinP** [comment]
Based on email review with ROW staff, I have update all the prod emails now with updated email signature and language

Complete pending final review

**Comment by ChrispinP** [comment]
After account signup re-design, the verification was updated and is working as expected for new accounts. complete, closing
