### ISSUE TITLE
TCP CMU Legacy Data into Organization Records

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#17158]
Org Fields
- TCP Submitting Org (Submitting Agency)
- TCP Owner Org (Project Owner)
- CSWZ Applicant Org (Applicant Company or City Dept)
- CWZ Conflicting Org (Applicant Company or City Dept)
- CSWZ Owner Org

[Combined Org Records List](https://cityofaustin.sharepoint.com/:x:/r/sites/tpwDTS/Shared%20Documents/Projects/ROW%20Case%20Management%20Upgrade/[TCP_CMU_ConflictShared_Organizations.xlsx](https://cityofaustin.sharepoint.com/:x:/r/sites/tpwDTS/Shared%20Documents/Projects/ROW%20Case%20Management%20Upgrade/TCP_CMU_ConflictShared_Organizations.xlsx?d=wd6d036d5732d4798ba69c16ca5a96888&csf=1&web=1&e=jT2zTh&nav=MTVfezZBQjk0ODU0LTJEOUMtNEQyRS1COTg4LTBEOTEzQTU4RTg4NH0)?d=wd6d036d5732d4798ba69c16ca5a96888&csf=1&web=1&e=jT2zTh&nav=MTVfezZBQjk0ODU0LTJEOUMtNEQyRS1COTg4LTBEOTEzQTU4RTg4NH0)

**Comment by ChrispinP** [comment]
Updated the combined list of orgs, removing duplicates and cleaning up names. We have a total of 179 orgs currently.

Ready to review with ROW Staff before importing into both Test and Prod environments

**Comment by ChrispinP** [comment]
Combined List of Orgs have been imported into both the prelim_organization and organization objects to make initial connections and prepare new test environment.

Pending any further adjustments to the orgs

**Comment by ChrispinP** [comment]
closing no further actions
