### ISSUE TITLE
Maximo Outage - May 9

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#17165]
What's Happening?

There will be a 9 hour outage to the production environment on Thursday, May 9th starting at 9:00 PM.  IBM will be adding more disk space for our attachments. 

Start: Thursday, May 9, 2024 - 9:00 PM CST

End: Thursday, May 10, 2024 – 6:00 AM CST

Duration: 9 Hour

What is required of me?

Please save your work and close/log out of Maximo prior to the outage.

Who do I call for help?

If you experience any errors or problems after the planned outage, please contact the CTM Helpdesk and enter a ServiceNow ticket.

Thank you,
Maximo Team

**Comment by adry-martinez** [comment]
### May 10, 2024 

No issues/disruptions in Maximo as of now. Closing request as COMPLETE.
