### ISSUE TITLE
IT Support: iPad not charging 

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17171]
CAMERON

## Device & User Information
Ben H
## What's the problem?
Ticket came in from Service now INC0390570
"Ipad is not charging"

COA tag: COAW79598
Serial Number: G9YRYYN4MT

**Comment by susannegov** [comment]
Sent message to Ben
> Hello Ben,
Matt let me know that the IT service now ticket got rerouted about having issues with your iPad not charging. 
 Could you drop off the charger and iPad in my office? I'm located at 8700 Cameron Rd. in the bull pen

**Comment by susannegov** [comment]
# 5/9
Ipad was dropped off this morning
- Tested existing charger - it does charge but not to iPad
- Tested new charger - it does charge but not to iPad
- Attempted to force reset using Power off/power on. There is not enough power to turn on the iPAd

**Comment by susannegov** [comment]
Sent Teams message to Scott asking if he can troubleshoot on iPad not charging as departmental cellular SPOC in ServiceNow

**Comment by scottreedy** [comment]
The ipad was replaced by Apple s/n- F09F423W0Q
I gave it to Scott Feldman
