### ISSUE TITLE
Refresh the "suspected unhoused" flag in the DB

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#17191]
Per Xavier, the VZ team is delivering an update to city leadership this week that includes the topic of crashes involving people experiencing homelessness. He has requested that we repeat the steps taken [here](https://github.com/cityofaustin/atd-data-tech/issues/14985#issuecomment-1901071790) in order to make sure that the `peh_fl` field is up-to-date based on the most recent CRIS data covering the year 2019 to present.

**Comment by roseeichelmann** [comment]
I identified 26 primary persons that needed to have their `peh_fl` updated to `true` using extracts from 2019 to current. I believe @johnclary updated them in the production database.

**Comment by johnclary** [comment]
thanks @roseeichelmann—i'm holding off on running the updates because Xavier mentioned that we may override some manual edits the've made to that flag 😅

**Comment by johnclary** [comment]
Per Xavier, I excluded any people records that had `prsn_inj_sev_id` = `4` (fatal). Which resulted in my removing one crash from the result set that Rose provided.

This is done. Thanks again for the quick turnaround, @roseeichelmann!
