### ISSUE TITLE
Work session on DTS service delivery workflow 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#172]
**Objective** 
 - Review work that @TracyLinder has already done on intake, SLAs, etc. 
 - Propose strategy for easy access to comprehensive, high-level project portfolio overview
 - Review👆with @johnclary 
 - Create issues for next steps

**Participants**

**Agenda**

------
- [x] Schedule meeting
- [x] Meet
- [ ] Create resulting issues

**Comment by TracyLinder** [comment]
[Meeting Notes](https://docs.google.com/document/d/1V4XfnfQRsNph2m_OYIQwNNzL33tEERCnxrFwLTdcJnI/edit)
