### ISSUE TITLE
Define OCE Mix Type Fields

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17209]
### Each mix type has unique fields/data to be captured, so we need to document which fields should be collected for each mix type.
_The spreadsheet is [here](https://cityofaustin-my.sharepoint.com/:x:/g/personal/tracy_linder_austintexas_gov/Ed9KdD0PXBxJq-TxMHEFFn8Bz-aIj2Fnt-PKKbvKw-p3tg?e=Kzzn2D)._

**Comment by susannegov** [comment]
Filled out the template based on the notes and color coded the tabs based on multichoice options

![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/ab59d83e-04b2-4448-a318-98953f180518)

**Comment by TracyLinder** [comment]
@susannegov the spreadsheet is done and ready for you to use to update the mix forms.

**Comment by susannegov** [comment]
# Build Notes
- [ ] `approved_mixes`

 - Approved Mix Types: Concrete Asphaltic Mixes and Stockpiles

**Comment by susannegov** [comment]
Made changes ready for review/qa @TracyLinder

**Comment by dianamartin** [comment]
# 10/14/2024
@susannegov 
**Add Approved Mix Form**
Cement Type 
- [ ] Update all "TY" - to “Ty”

**Comment by susannegov** [comment]
Done. Good to close
