### ISSUE TITLE
[Enhancement] Application Form updates 5/9/24

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17215]
## Description
After meeting with Mobility Services to review the MVP for the Application form we got their feedback and have the following updates for the form.

#### Section 2
Moving violation - Jacob said this question is good to have
- [x] Add field `Description of moving violation` paragraph text type
- [x] Provide a paragraph text box drop down if select yes for moving violation in display rule

People make false statements on section 2 are checked for validity of statements and get declined

#### Section 3

- [x] Add text “Please review the required attachments”
- [x] Instead of “Add Attachment” do “Add Supplemental Attachment” button

Paul - It’c called a disposition “Additional court documentation”
For the custom add attachment - how would a user know what else they need?
Jacob - We would inform them of what else they need. If we check their info and it turns out the court system/police department and instruct the applicant to attach additional documents
For citizenship, their is additional documentation in cases where their green card expired

- [x] Add restrictions if not all attachments submitted
- [x] Add “Reviewer Comment” to attachment grid table view
- [x] Truncate attachment name url to “View”
- [x] Attachment Instructions link on the “Please attach file”
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/3e4f881e-1a69-4d66-b83d-047f8f8058e5)

Attachment status
Approved, Declined, Needs Review, Uploaded 
When declining attachments, we can put a disqualification letter explaining why they are declined and what to do which is through an appeal and how to appeal.
When going through an appeal process for the application, we take to consideration for appealing
We want there to be information on the appeal process which will bring it back to their account
Give reviewer ability to kick status to Pending

#### Section 4
Jacob we want to promote ourselves for notarization

- [x] Put COA first option “I want to use COA on site” instead of second option
- [x] make “I want to use COA on site” as a default option
- [x] “notarized on my own” option must specify to be in Travis County

see @dianamartin notes on notarization below

**Comment by patrickm02L** [comment]
## Section 4 - Notarization 

via Diana meeting notes

Advertise notary services
- Update “Review Application”
- Notarize with the city
- Notarize on your own
- Add full steps
  - **Own my own (must print application for applicant)**
     - Print application page
     - Get document notarized within Travis County
     - Go back to Application details and attach notarized document
     - Submit Application
  - **On Site (no printing required for applicant)**
      - Click Submit Button
      - Mobility Services staff will review application and required documents
      - When Application is “Approved - Pending Payment/Notary”
      - Wait for email notification of “Approved” application
      - Call Mobility Services office to schedule test appointment, an get application notarized, pay application fee on site

**Comment by susannegov** [comment]
# Steps to check if all attachment submitted

**Comment by susannegov** [comment]
# To do
- [ ] Add JS/CSS code to github

**Comment by susannegov** [comment]
- [ ] Added `application type` multichoice field to my applications
- [ ] Add status colors from https://atd.knack.com/smrt#status-cheat-sheet/
