### ISSUE TITLE
[Enhancement] Improve Print Application formatting

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17217]
See - Create a digital version of the current [paper application](https://www.austintexas.gov/sites/default/files/files/Transportation/Ground_Transportation/Chauffeur_Permit_Application_112023.pdf)

## Description 
When were testing with Mobility Services team on 5/9/24 we noticed that the formatting for the Print was breaking in weird places, and want to figure out how to make improvements to display the printed form better. 

- [x] Add “Attachment Date” to Section 3
- [x] Put print notarization language blurb needs as page break at the bottom for the page
- [x] Need legal “Must include Add Page X of Max page” in legal printing

## Notes
_via Diana_
- Experiment on longer responses on Background Information
- Notary part on it’s own page (Page 4 of 4)

## Propose
- Set character count for Background Information (paragraph text type) for applicant
   - edit app page - 'view_100'
   - background info page - 'view_83'
   - field IDs of paragraph text  48, 49, 52, 53, 76, 86, 56
   - character limit is currently set to 500 but can be changed
   - HTML changes to bold/red over limit when above char limit
   - Currently no validation rules set (to test how much)
   - Ask stakeholders how long should each section be when first fill out
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/0833176f-7d8e-4c9e-a3d4-e36e854a5b35)

**Comment by dianamartin** [comment]
# 5/14/2024
- Susanne and I synced on the Print Preview page enhancements
- I used the 500 character limit for response entries and was able to make it look pretty good at 100% scale, but we don't think that all users will use a full 500 character. 
- Will need to test with minimal form responses

**Comment by susannegov** [comment]
I found this for forcing page breaks when printing: in the Rich Text view wrap it with `<div style="page-break-before: always;"> YOUR CONTENT </div>`
Source: https://forums.knack.com/t/add-page-break-to-use-in-the-print-link/9724/10
Confirm it works for chrome at least
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/8e8562f0-c912-40fb-b742-675b2632fc29)

**Comment by susannegov** [comment]
- [x] Added Header Rich Text
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/b610ebc4-2930-45e8-af84-1c3b65572919)
- [x] Page break for Section 1
- [x] Broke up Section 2 into two pages
- [x] Page Break Section 3
- [x] Modified table view to custom for print view 
- [x] Page Break for page 4

# To do
- [ ] Must include Add Page X of Max page in legal printing

**Comment by susannegov** [comment]
- [x] Split last question of Section 2 to page 4
- [ ] Forced into format of 5 pages
   - Tested with 500 character limit on all answers: [print link](https://atd.knack.com/mobility-services#permit-applications/view-chauffeur-application-details/664f7d12b831310028ee1c7d/print-application/664f7d12b831310028ee1c7d/)
   - [ ] Tested with all answers selected No in BG Info: [print link](https://atd.knack.com/mobility-services#my-applications/view-chauffeur-application-details/664e6bd32377a30027900e4e/print-application/664e6bd32377a30027900e4e/)

**Comment by susannegov** [comment]
- [x] Modified `Signature Date` and `Signature By` to match PDF
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/8793fc11-ec52-45e9-9d66-e42534ceb734)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/887fade8-e4e4-43dd-b415-d2225c34518c)
- [x] Added print trigger buttons - the button is hidden using CSS
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/834519c2-26fe-42ef-9cb7-6e001fbdccaf)
```
@media print {
  #view_225 {
    display:none;
  }
  #view_226 {
    display:none;
  }
}
```

**Comment by susannegov** [comment]
- Added mobile friendly detail label CSS from [gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzNSSXajDFpzOv2IhIv/knack-code/mobile-optimization/detail-labels)
   - 60% for app information
   - 80% for background info (mostly yes/no) for left label align

**Comment by patrickm02L** [comment]
## 5/31/24
From yesterday's Sprint Review we noticed that the address needs to be updated. Please change to the following then close out.

Mobility Services 
1501 Toomey Road
Austin, TX 78704
512-974-7857

**Comment by susannegov** [comment]
# 06/07
- Added updated text
- Made page counter dynamic and updated html/css
- There was a visual bug where the detail view would get overlay on the 3 page print (4 page print wasn't affected as far as I know)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/db23159e-f300-427f-968b-5ba2d62bbb58)
   - Solved by adding below 
   - `#kn-scene_65 .view-group, #kn-scene_83 .view-group {
  display: block;}`
    - Knack has a built-in css class called `view-group` where the views get grouped up set to flex which is why text overlap happens, but the view-group class I'm not sure what it is determined by.
