### ISSUE TITLE
Maximo User Process Discovery - Sidewalk & Urban Trail Reporting

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17214]
## Objective 
The Data & Technology Services Division is initiating a series of meetings to learn more about Maximo user experiences and processes in TPW. In this meeting we'll be asking questions about how individual teams use Maximo and how it fits into their work processes.

## Goals:  
- Maximo system performance and functionality 
- User experience and interface experiences 
- Current processes within and related to Maximo 
- User feedback and improvement  
- Future roadmap and upgrades 

### User experience and interface experiences 
- Explain your process on how you use Maximo? 

### PROCESS - Planning
- Who plans the work? How do you get work to do? 
- How is work scheduled and issued out 
 
### PROCESS - Implementation
- How is work scheduled and issued out?
- Who is executing the implementation? 
 

### PROCESS - Field Work
- Who is executing the work - implementation? 
- Who is reporting on the work and what are they tracking? 

#### Maximo system performance and functionality 
- How long is it taking to do a Maximo work order in the field? 

### PROCESS - Review & Reporting
- What is your final review, QC process? 
- What reporting do you care about? How are you pulling that information out? 
- What are you reporting? 

### User feedback and improvement  
- What challenges are you having with Maximo? 

### Future roadmap and upgrades 
- What would you like your work order management system to do that you’re not getting right now? What’s missing? 

### Points of Contacts 

------
- [x] Schedule meeting 
- [x] Meet and take notes
- [x] Process notes on Miro [Maximo Assessment Plan](https://miro.com/app/board/uXjVN7sxj9I=/)

**Comment by dianamartin** [comment]
# 5/9/2024
## Diana's Notes
Participants: Adry, Rene, Rebekka, Christina, Peggy, Diana
Sidewalks team: Justin, Austin

## Scope a project 
- They get project ready - for Brad’s crews

## Things they do in Maximo
- Create a new work order in Maximo (Austin)
- Assigns to a supervisor (Dale F.)
- They put in their actuals for this, for their performance measures

Do use performance measures and include their numbers

Sidewalk repair requests - from District Maintenance

- sometimes they get direct CSRs (rare)
- why do you get them?
- Bc citizen wants to talk to engineering staff
- Austin used to do a lot of service requests
    - did QA for district maintenance, they stopped doing that
    - get calls if they get questions about that
    - everything was being sent to Sidewalks
        - 80% wasn’t necessary

## Scoping a project
- Austin, PM for inhouse work
- he will go into the field for repair locations
- Create work orders for the CRC crews
    - Ops staff enters labor records
    - Use some base materials
        - cubic yards of concrete

Need to associate plan sets, or task order?

- have put it in the past
- but not putting it in on the work order
- Use primary TK, sometimes use multiple TKs

## Managing / Scheduling a project
- Identify a whole group of projects at the beginning of the year
- Monthly basis, Austin<>Brad talk about which
- Use MS Project to manage them

Brad’s crew is like a contractor for Sidewalks

- Brad does extra work when he’s doing fire stations an other
- They (SUTD) funds the work
- When are you going to be done with the project, when can you
- Gabe (PM) manages the schedule

New supervisor, Lionel Ceballos (4th crew)

## Actuals
- Driveway
- Width of sidewalks

Austin does create a map for scoping visit, to help Brad scope out the next few weeks

- Estimate the level of effort: 2 months

## Service Plan
- Sidewalks do have a Service Plan..
- Didn’t make an official Service Plan this year
- Part of the Mobility Annual Plan
- Is there a goal? that they’re trying to hit
    - based on a cost per budget, $ 3 million .
- Brad uses operational funding, 3 million assigned to Brad
    - Use it or lost it
    - Assign bond funding if there aren’t enough funds
- Meet 100% of service plan goals
    - Last year, did 115%
    - Usually more

Most of in-house work is 

- rehab

## Sidewalk Contractor Work
- contract, payouts that come in
- Financial system, eCapri
- How do you all issue out to contractors?
    - spreadsheet, work orders?
    - 5-7 other Project Managers
    - Assign the year’s project
    - field engineers, they divide them out
    - so that contractors are aware

## How long does it take you to interact
- Quick process, really quick for Austin
- In there, less than 60 seconds
    - use the “duplicate” function
- Change the title, street information
    - Same the same exact WO, but new number
- Use it for investigative purposes

Average project lasts 1-2

## Reporting functionality
- Justin isn’t use the report
    - Jhermaine/Diane R. (SUTD) - Quarterly Reports “SBO Project Costs” report
        - they get all the numbers together
    - length of sidewalk/curb ramps
- $3 million: report on budget use
- Report on funding gone towards
    - in house
    - contractors
- Report Strategic Measures
- Performance Measures
- Done by field QA
    - Justin said it’s Brad’s role
- Confidence: It’s great as long as the supervisors are putting in data into the system

Clay R:

- Service Address
- Segments

Would that report be affected

- Parent WO
- Child WO

## Shifting
They’re working on multiple segments a day

- consistent reporting

68 Work Orders

- FY19
    - Split up by: Sidewalks, ADA
- FY 21
    - Switched over

Missing service address, they have “memo” fields

## Justin asks, why the change?
- Superintendents/Supervisors: Provide a monthly schedule for what they’re going to be doing
- Maximo should reflect that new monthly schedule
- Breaking down the schedule to weekly, daily schedules in Maximo
    - At any given day
    - Their status
    - How much is being done in the project
- Need to have a “look ahead” to get historical data and building a service plan
- JN asks
    - will this be enough? **Schedule Start** & **Schedule Finish**
- Don’t want changes to negatively impact the stakeholders
- There will be modifications to figure out the best method for DM, AD an executives (at will)
    - without calling people
- Sidewalks
    - Would want to create parent only
    - They suggest CRC would create child WOs

## GIS QA
- How are your assets being updated?
- Project being completed
    - ex. Blue Meadow
- Project Manager notifies Sandra C. (SUTD)
    - Marks them completed in their ArcGIS Online map (Sidewalk Program Projects)
- Existing - dark
- Planned- light blue
- Update the rating of he sidewalk (condition rating)
- Do it internally on the team
- Doesn’t use GIS for reporting

## Moped
- Doesn’t suit their needs in GIS
- They plan to use for reference information

**Comment by ChristinaTremel** [comment]
# 3/9/2024
## Christina's Notes

### User experience and interface experiences

- Explain your process on how you use Maximo?
    - When they scope a project and get it ready for the concrete crews, he’s come into Maximo and create a work order. Example SW Rehab, FY24, Blue Meadow. Austin comes in and fills out the Maximo work ticket and assigns it to a crew.
    - Uses Maximo to report on performance measures. And this is really UER that reports on it and then he just reports on that measure.
    - Sidewalk repair requests come through crews and sometimes 311 SRs
        - Would send it if they want to talk to an engineering staff
        - This process has changed. Austin used to do a lot of CSR requests but they became quality control with all the SRs. So now he gets calls if they have questions about it.

### PROCESS - Planning

- Who plans the work? How do you get work to do?
    - Scoping a project:
        - Austin is the project manager for in house crews
        - Goes out to the field and identified repair locations
        - Creates work order so they can input performance measure
        - Crews input labor records, base actuals (cubic concrete and performance measures)
        - Performance measures are material actuals in Maximo
        - Report with unit 8000 in the title summarizes the actuals
        - Sometimes includes TK on work orders, but the supervisors know which TKs they are using
- How is work scheduled and issued out
    - A service plan is planned as part of the Mobility Annual Plan
    - Planned annually and goal is to keep the crews busy for 3 million dollars per year
    - SUTD typically meets 100% of the service plan goes or exceeds the goals. Last year was 110%
    - Most of in house crews is sidewalk rehab and new sidewalks are built by contractors (and some rehab)
        - Most funding goes to rehab
- Contractor vs In-House
    - Track contractor performance measures through eCapri and payout
    - 7 Project Managers that divvy out the contractor work orders. They’ll work with the contractors and the field engineers so they know what to work on next.

### PROCESS - Implementation

- How is work scheduled and issued out?
    - Austin meets with Brad monthly to decide which projects need to be scheduled.
    - Uses Microsoft Project software
    - Brads crews are mostly funded by Sidewalk & Urban Trails so they are essentially an in house crew for them. Scheduling is mostly checking on timelines to wrap up projects so they can decide what needs to be scheduled next
    - Gabe helps with the schedule mostly at this point, but they use Microsoft Project for building the schedule
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/8ec7d14a-591d-49ec-84b2-0594a1c97f75)- Who is executing the implementation?

### PROCESS - Field Work

- Who is executing the work - implementation?
    - Contractor and In-House crews
    - Do about 40 miles of sidewalks a year
- Who is reporting on the work and what are they tracking?
    - Mesh/Light Reinforcement, Linear feet of sidewalks with different widths
    - Austin creates a map of where to maintenance the sidewalks and then the crews calculate the linear feet while they are out there
    - SUTD does have an estimate
- Project typically takes around a month / month and a half

### Maximo system performance and functionality

- How long is it taking to do a Maximo work order in the field?
    - Quick process to create the work orders. Can take less than 60 seconds to create the work order
    - Austin uses the duplicate function and change the title and remove any info that doesn’t belong in there
    - Uses it for investigative purposes sometimes if he’s not able to find information
        - This is nothing compared to when he first used Maximo and filtered though 800 repair requests

### PROCESS - Review & Reporting

- What is your final review, QC process?
    - QC is done by Brad as a Superintendent and this is mostly for their performance measures. Brads team and SUTD uses it to report out on
    - Currently don’t have GIS spatial components of work orders
- What reporting do you care about? How are you pulling that information out?
    - Finance team within Sidewalks & Urban Trails (Jermaine and Diane Rice) uses the Concrete Work report for performance measures to quantify length of sidewalks and number of curb ramps
    - Confident in the reporting in Maximo as long as the data is inputted correctly
- What are you reporting?
    - Length of sidewalks
    - Number of curb ramps
- GIS QA is done internally on the team
    - High level statuses: planned sidewalk, planned shared street, potential sidewalk, sidewalk, driveway, shared use path, share street

### User feedback and improvement

- What challenges are you having with Maximo?
    - Clay was asking if the process could be changed for work orders by splitting it into child work orders that have the driveways captured.
    - Justin would prefer if the work orders statuses were moved from In Progress, that would be the easiest way to track it in their minds because there should typically only be 3 work orders in progress, but right now there’s 68
    - There are 68 work orders in progress because the data hasn’t been entered into all of these work orders, but there are only about 3 work orders active at one time (one for each crew)

**Comment by ChristinaTremel** [comment]
Added notes to the miro board and will review with the team next week!

**Comment by rebekkabry** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/0763745e-67ad-4b24-936e-4a9ac4a0e675)
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/21fa1fb4-b2bf-4255-bd25-138b6d3e11f9)

**Comment by ChristinaTremel** [comment]
Notes have been added to the Miro board!
