### ISSUE TITLE
[Enhancement] Create a new "Permit" object (table)

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17218]
## Description
In the 5/9/24 Sprint meeting with Mobility Services there was a request to see the statuses of different permits. We determined that we would need to create a `New Permit` table.

**Comment by patrickm02L** [comment]
cc: @susannegov @dianamartin 
please add additional images and build notes for reference

**Comment by dianamartin** [comment]
# 5/10/24
## Build Notes
Field headings
- Permit_ID - `auto-increment`
- MSP Permit ID - We need to find out if the Permits they give out to the user is something they want to track
- Expiration Date
- Permit Type:
  - Chauffer
  - Commercial Vehicle License | CVL

**Comment by patrickm02L** [comment]
## 8/4/24
Check in with Jacob and Paul to make sure this is something they want to add.
We'll also need to backfill any permits numbers that have been issued to date.
