### ISSUE TITLE
IT Support: User is having issues with her computer

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17229]
## Device & User Information (first name and last initial, no last names)
Adriana M
## What's the problem?
The user is having issues with her computer

## What did you do to resolve the issue
Will meet user at 5-14

**Comment by Vaishnav1397** [comment]
User mentioned to schedule sometime next week 5/22.

**Comment by Vaishnav1397** [comment]
Checked with matt and mentioned that JB has updated the drivers. Waiting over to see if still the issue is populating if not, we might need to swap out the system.

**Comment by Matthew-M-TPW** [comment]
Messaged user "how is the computer running?"

**Comment by Matthew-M-TPW** [comment]
User reports that everything is working well 

I also updated her to Windows 11
