### ISSUE TITLE
IT Support: Windows 11 Update

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17245]
PDC, TOWNVIEW ST. ELMO, DALTON
St Elmo
## Device & User Information (first name and last initial, no last names)
Ignacio A
## What's the problem?
Update Computer to Windows 11
PWD-26VCL12-N1
Machine is a 7470 and need to be swapped out
## What did you do to resolve the issue
Yes, user has a pretty old machine and swapped out with 5431. Checked on win 11 and it's already updated.

**Comment by Vaishnav1397** [comment]
Tried reaching out the user through teams but seems to be offline.

**Comment by Matthew-M-TPW** [comment]
User sent me an email.

"Can you come check out or possibly replace my laptop? This is the second time it has crashed with this code and the help desk said the hardware is failing.

I'm at Kramer Ln"

**Comment by Matthew-M-TPW** [comment]
Responded to user 

That was perfect timing. We just put you on the list to have your machine replaced. 

Can you bring it to St. Elmo to have it swapped out?

**Comment by Matthew-M-TPW** [comment]
User responded: 

"possible this afternoon or tomorrow I am at the job site right now."

**Comment by Vaishnav1397** [comment]
User was having a very old 7440 laptop and swapped out with latitude 5431. Deployed and make sure everything is back on the system.
