### ISSUE TITLE
IT Support: [Issue with the network connectivity]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#17244]
St Elmo
## Device & User Information (first name and last initial, no last names)
Laptop/ Ethernet port & Anthony, A 
## What's the problem?
Internet not working from the ethernet port when connected to dock, laptop at the user desk. Done with support assist and required driver updates, but still the same case.
## What did you do to resolve the issue
Checked on interchanging ethernet cables from phone port as well, including the dock. But unfortunately, we couldn't fix the issue even after doing the Wi-Fi network drivers update. @Matthew-M-TPW we need to test the port back sometime next week.

**Comment by Vaishnav1397** [comment]
Ticket was submitted to CTM- INC0393491(Incident number).

**Comment by Vaishnav1397** [comment]
CTM team working on the issue, mentioned that there was a small shot circuit in it and trying to cut the cable and replace it back.

**Comment by Vaishnav1397** [comment]
Team mentioned that there is an issue with the cable and might be if that can be swapped from the top that's fine if not the cable management team would come over and have a check on it.

**Comment by Matthew-M-TPW** [comment]
CTM came to look at the port and there is a problem with a wire in the ceiling. They will get back with us we might have to rewire the cable

**Comment by Matthew-M-TPW** [comment]
Sent email asking for funding

**Comment by Vaishnav1397** [comment]
Team still working on the issue, quotes received and waiting on the update.
