### ISSUE TITLE
IT Support: Outlook running slow

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17251]
ST. ELMO

## Device & User Information (first name and last initial, no last names)
Lisa K
## What's the problem?
Users outlook is running incredibly slow. She was on vacation when I was helping her. So I am creating a ticket for us to follow up.

**Comment by Matthew-M-TPW** [comment]
user is out today

**Comment by Vaishnav1397** [comment]
User cannot be able to send emails through shared mailbox. Need to check on the access and update accordingly.

**Comment by Vaishnav1397** [comment]
Craig and I checked over on the additional folder TPW tree access, but there is a delivery notification failure, then checked with matt and mentioned to reach out the user to CTM for access to the folder.

**Comment by Vaishnav1397** [comment]
@Matthew-M-TPW Did you by any chance receive any update from CTM regarding issuing the access for the folder to user?

**Comment by Matthew-M-TPW** [comment]
REQ0185699 CTM request is still open

**Comment by Matthew-M-TPW** [comment]
CTM closed REQ0185699
