### ISSUE TITLE
IT Support: Move from St. Elmo to Ben White

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17265]
ST. ELMO to BEN WHITE

## What's the problem?
begin moving the stuff at the St. Elmo service desk to our desk at Ben White.

**Comment by Vaishnav1397** [comment]
Few items have already been moved. Still pending items to be moved over.

**Comment by Vaishnav1397** [comment]
If possible, will be moving over some more things tmrw and place it over at Ben white

**Comment by Vaishnav1397** [comment]
Started arranging the desk, tossed the empty boxes backside of building and moved non working equipment.

**Comment by Vaishnav1397** [comment]
Have setup few of the inventory over on all the cables, boxes, keyboards, at one place within the storage, need to move few of them and to be placed at location for further use.

**Comment by Vaishnav1397** [comment]
Matt and me, moved the required equipment and placed it at inventory room in Ben White.
