### ISSUE TITLE
Maximo User Process Discovery - Pavement Ops (Overlay)

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17303]
## Objective 
The Data & Technology Services Division is initiating a series of meetings to learn more about Maximo user experiences and processes in TPW. In this meeting we'll be asking questions about how individual teams use Maximo and how it fits into their work processes.

## Goals:  
- Maximo system performance and functionality 
- User experience and interface experiences 
- Current processes within and related to Maximo 
- User feedback and improvement  
- Future roadmap and upgrades 

### User experience and interface experiences 
- Explain your process on how you use Maximo? 

### PROCESS - Planning
- Who plans the work? How do you get work to do? 
- How is work scheduled and issued out 
 
### PROCESS - Implementation
- How is work scheduled and issued out?
- Who is executing the implementation? 
 

### PROCESS - Field Work
- Who is executing the work - implementation? 
- Who is reporting on the work and what are they tracking? 

#### Maximo system performance and functionality 
- How long is it taking to do a Maximo work order in the field? 

### PROCESS - Review & Reporting
- What is your final review, QC process? 
- What reporting do you care about? How are you pulling that information out? 
- What are you reporting? 

### User feedback and improvement  
- What challenges are you having with Maximo? 

### Future roadmap and upgrades 
- What would you like your work order management system to do that you’re not getting right now? What’s missing? 

### Points of Contacts 

------
- [x] Schedule meeting 
- [x] Meet and take notes
- [x] Process notes on Miro [Maximo Assessment Plan](https://miro.com/app/board/uXjVN7sxj9I=/)

**Comment by dianamartin** [comment]
# 5/15/2024
## Diana's Notes 
Johnathan G.  - Inspector
Aaron E. - Supervisor

>User experience and interface experiences
Explain your process on how you use Maximo?

## PROCESS - Planning
>Who plans the work? How do you get work to do?
How is work scheduled and issued out

- service plan loaded into Maximo
- sequence work N, S
- Capture the data

Aaron says
- Track personnel, equipment, work 
- length, width of project
- keep track of service plan
- put out notifications to alert folks about work
- weather permitting, try to stick to the service plan as close a possible
- unexpected construction
- move street

## PROCESS - Implementation
How is work scheduled and issued out?
Who is executing the implementation?
- Superintendent, Stephen R. 
- Gets service plan from Ron K.  (OCE)
- Put together service plan, pass to Steven
- Coordinate efforts according to service plan
- Sequence that schedule N -->S, S --> N
- Ron has his spreadsheet for OCE
- Andre goes through spreadsheet
  - Shuffle dependent on what's happening on the field
My question: `Why different spreadsheets?`
  - He tracks different information
  - What projects have been completed and total of lane miles
  - He takes the daily reports and puts his spreadsheet
  - OCE is looking at more information

"Old habits", like our spreadsheets
- highlight a spreadsheet quicker than run a report

## PROCESS - Field Work
>Who is executing the work - implementation?
Who is reporting on the work and what are they tracking?
Maximo system performance and functionality
How long is it taking to do a Maximo work order in the field?

`Assigned from the spreadsheet?`
- Steve will give crew daily job assignments
  - Milling & Paving
- Try to stay 2-3 streets ahead of pavement operations
- `When you get certain criteria when they move around the city?`
  -  Try to plan through the city, geographically
  - Easy to locate equipment
  - Safe location to stage equipment (3-4 streets in one area)
    - To keep efficiency
  - `How do you accommodate doing 2-3 streets ahead?`
    - Had issues with equipment, one of the pavers went down
    - Mill for `x` amount of days
    - Equipment is back, start pavement again
    - Personnel: run out of resources, short handed
      - enough street milled, then pave out
      - it's more efficient with both operations
    - Milling process is a faster process
    - `What's a typical size of a crew`
    - Milling: 12-13, just equipment operators
      - 30-33 people milling + paving
      - all of trucks available: 10-11 trucks
        - short on personnel
        - losing personnel constantly, 2-3 months
    - Paving: 13-14 people

## PROCESS - Review & Reporting
>What is your final review, QC process?
What reporting do you care about? How are you pulling that information out?
What are you reporting?
User feedback and improvement
What challenges are you having with Maximo?
Future roadmap and upgrades
What would you like your work order management system to do that you’re not getting right now? What’s missing?

**Comment by ChristinaTremel** [comment]
## Christina's Notes from 5/15
### User experience and interface experiences
- Explain your process on how you use Maximo?
   - Use Maximo after project is done. Track personnel, equipment, track service plan. Work they do is specifically following the service plan, but the service plan is subject to change based on equipment, construction 

### PROCESS - Planning
- Who plans the work? How do you get work to do?
   - There’s a spreadsheet that OCE maintains for overlay and sealcoat projects on the service plan
   - These spreadsheets duplicate the same information that Maximo reports generate, but they complete work orders after projects are completed so there is a delay to seeing those on the report (about 24 hours)

### PROCESS - Implementation
- How is work scheduled and issued out?
   - They use the spreadsheet to track which projects they need to get permitting for on the service plan and determine which projects to schedule next based on geographic location
   - Two spreadsheets: One that Andre tracks and one that Ron tracks
      - Andre tracks projects completed and number of miles completed
      - Ron tracks way more detailed and tracks other things
- Who is executing the implementation?
   - Steve will give out he potential projects for the week
   - Tries to plan work geographically because the it’s more efficient and it’s safer

### PROCESS - Field Work
- Who is executing the work - implementation?
   - They have a milling team and a pavement team and the milling team goes ahead of the overlay team.
   - Sometimes personnel is an issue and they can only send out one crew at a time
   - Milling is a lot faster than paving
   - Crews
      - Milling needs 12-13 people for equipment operators
      - Pavement needs 14-15 people for equipment operators
   - If all trucks are up and running they have 10-11 trucks
   - If everything's running they are still short on personnel - have been losing personnel constantly for the past 2-3 months
   - Staging Equipment: to complete projects, these teams have to stage equipment/materials and then goes out to specific sites to mill and pave. They prefer to not have to go back to the yard every time so this is why they do it - it’s more efficient. 
   - They have specific places that they are able to dump spilling and have to take this into consideration. 
   - Pavement has 3 locations where they pick up material - 2 plants in Buda and 1 plant in Mustang Ridge. What type of material and where they are making it is planned out by OCE. Contract is that they should be allowed to pick up material at the plant closest to their work site.
   - Pick up material (asphalt) everyday
      - Overlay is a year round operation. During the winter months if it’s too cold, they are limited to milling
- Who is reporting on the work and what are they tracking?
   - Andre reports on projects completed and number of miles overlayed to his Division Manager
      - Andre will gather all the data and compare to OCE
   - Division Manager meets with other DMs within SBO and then they report that up to Reiner. Reiner will then raise this and speak to the executives.
   - Also track non-productive and productive days (same with sealcoat). This crew can mill so they can really always stay productive. If there’s inclement weather, fog seal and sealcoat can still operate. 
   - Track bad weather days and equipment failures to tell the story of what’s happening that could impact productivity.
   
### Maximo system performance and functionality
- How long is it taking to do a Maximo work order in the field?
   - Each crew lead for operations do their daily work ticket, send it to Andre and Frank, and the Supervisors submit the data into Maximo
   - Crew lead emails work tickets to Supervisors via email
   - When work has been done, the crews physically measure (length, width, and depth) what’s been done so it’s easy to transfer into Maximo.
   - Service plan has projected lane miles for what’s expected on that street and when he enters it it typically matches that pretty closely
      - There’s nothing in Maximo that shows that the information is correct that’s entered into Maximo and sometimes adjustments happen in the field (they expand the extents of the project so they don’t have to go back the next year or other things based on the field experts) 
      - Aaron enters work orders into Maximo as soon as he receives the email and he’s able to do it super quickly because he’s been doing it for a while. Probably spends about an hour a day in Maximo.
      - Coordination with other crews happen outside of Maximo (knack application). It does slow down operations because typically coordination should just be a phone call.
     
### PROCESS - Review & Reporting
- What is your final review, QC process?
- What reporting do you care about? How are you pulling that information out?
-  What are you reporting?
   - Steve does most of the reporting along with Andre
   - Andre assists with reporting, but the reporting is also done by Dave Anderson
   
### User feedback and improvement
- What challenges are you having with Maximo?
   - For Aaron the process is pretty simple, but he does have to send service requests to add personnel pretty regularly. Adry updated the personnel file which helps.
   - Sometimes they run into glitches when Maximo is acting up so that happens occasionally. 
### Future roadmap and upgrades
- What would you like your work order management system to do that you’re not getting right now? What’s missing?
   - Andre would like to examine why we are tracking certain data because it’s never pulled up when they talk about reporting. Never talk about equipment used, materials used, etc so he just kind of wonders how we can use it (likes the idea of tracking data but don’t want to track it if they aren’t going to use it).
   - Aaron confirmed that they only ever look at specifications

**Comment by ChristinaTremel** [comment]
Notes were added to the Miro board! Closing this ✅
