### ISSUE TITLE
Maximo Report Request [Modify] - Completed Locations by USD, with detail

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17309]
DM Rivers shared that report is requested by AWU:

1. The # of locations completed, monthly (which we currently have)
2. The ask is to view the following: 
    - the # of assets (broken down by assets)
       - dimensions of each asset
       - square yard for each asset
       - materials used
       - Add Task Order
       - Remove Labor Names from report but maintain Title
       - Would like to incorporate **total of square yards completed for the month** on top of the report (see Utility Square Yards Completed by Supervisors report)

### DTS Maximo To-Do:
- [x] Replace labor names with labor titles
- [x] Remove Employee IDs
- [x] Add Task Order column (Work Order tab > Financial Details) 
Field: Task Order 
Table.Column: WORKORDER.TASK_ORDER
Task Order
- [x] Add total of square yards completed for the month at the top of the report (see Utility Square Yards Completed by Supervisors report)
<img width="1015" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTg5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4370c330d9da24de0c6a843ccbbbb5d1376e81bb/image.png" alt="image.png" />

- [ ] ~Add date parameters by month~
- [ ] ~Add to USD Coordination Start Center Report List~

### Deadline is until 7/17/24

![image](https://github.com/cityofaustin/atd-data-tech/assets/132967319/03ef091f-0829-4fcd-966e-875625ee178b)

**Comment by adry-martinez** [comment]
Upon demoing the current report we have, it looks like this is something we can expand as requested by the stakeholder. I will have to put this request on Needs Scoping, just until we can get access to dB2/backend of Maximo.

**Comment by adry-martinez** [comment]
Due date: end of June

**Comment by rebekkabry** [comment]
Scoped and discussed with Ganesh 6/5/24

**Comment by GaneshKamarapu** [comment]
@rebekkabry @adry-martinez this is ready for QA

**Comment by adry-martinez** [comment]
@ganeshkamarapu beautiful work! 
@rebekkabry please follow-up with Clay to confirm this meets his needs.

**Comment by rebekkabry** [comment]
Sending email to Clay advising of status and requesting feedback.
