### ISSUE TITLE
[DevOps] Shut down VZ SFTP lightsail server

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#17311]
Such down the instance we use to host the VZ SFTP. We're not using the SFTP server anymore. We' using AWS S3! See https://github.com/cityofaustin/atd-data-tech/issues/16953.

- 👀  on disk
- shutdown
- DNS
- 1PW entries

**Comment by frankhereford** [comment]
# 👋 ⛵ 

The lightsail machine and the related resources have all been released and archived. This is the last step of a nice upgrade to the import process; thanks everyone!

**Comment by johnclary** [comment]
thanks @frankhereford! 🎉
