### ISSUE TITLE
Request to add report to USD Report List - COW Utility Locations Completed

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17310]
DM Rivers requested to add SBO Utility Locations Completed to the Report List in USD Coordination Start Center

**Comment by ReneVarg25** [comment]
@adry-martinez  Is there another name for the report that it might go by? I cannot find a report with that name

**Comment by ReneVarg25** [comment]
### 5/16/2024
Added the following report to the UER Coordination Start Center Report list.

![image](https://github.com/cityofaustin/atd-data-tech/assets/133040608/3c672451-9362-4f72-b02b-a250f92c5647)

Notified DM Rivers of addition.
