### ISSUE TITLE
IT Support: 2 iPads for Mobility are having issues

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17338]
## Device & User Information (first name and last initial, no last names)
Jasmine L 
## What's the problem?
Mobility has 2 tablets that they are unable to log in. 

JB has the devices right now 

**References:**
☁[AirWatch Management](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/airwatch-management)
🤖[Android Configuration](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/tablet-configuration)
🍎[iOS Configuration](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/ios-tablet-configuration)

**Select Issues:**
- [ ] Purchasing Devices
- [ ] Setting up a New Device
- [ ] Setting up a New User
- [x] Switching Device User
- [x] Remove User & Wipe Device
- [ ] Create or Modify a Device Profile (such as passcode policy)
- [ ] Missing/Lost Device (alarm ping, lock, last location)
- [ ] Deactivate SIM card
- [ ] SIM/Network/Hotspot/WiFi/GPS
- [ ] Workspace One: Intelligent Hub app
- [ ] Launcher profile (such as Home Screen apps/shortcuts)
- [ ] App Catalog: New, Outdated, or Missing app or icon
- [ ] Unable to launch an app
- [ ] Unable to charge/turn on device
- [ ] Device Update/Version
- [ ] Retire a Device (outdated, bricked, no longer used)

**Device Details:**

| User | COA Tag | SN | IMEI | Phone | Brand, OS Version, & Device Type |
| --- | --- | --- | --- | --- | --- |
| Lyndon M  | COAW70049 | VQC2KMQTWM | ###### | 512-927-3200 | Apple iPadOS Mini |
| Lyndon M  | COAW70052 | FH946KV9WJ | ###### | ###-###-#### | Apple iPadOS Mini  |

**Confirmations:**
- [x] User in AirWatch (in TPW group, not CTM)
- [x] Device in AirWatch
- [x] Device Labeled with COA Tag, SN, IMEI, & Phone #
- [x] Device in DTS Inventory

**Comment by susannegov** [comment]
From Jasmine
> Hi, im not sure who made the ticket for the ipads but the issue with the iPads were that they were logged in to a different apple ID than before so that caused us not to be able to use the subscription in the  app Good Notes. I updated the app and it would only allow me to use 3 sheets at a time and I need to be able to access all the sheets since we have our property records and our fleet sheets on there 

> JB said to set it factory reset and set it back to regular resource code for both ipads

Regular resource code - `ATDParkingEnforcement`

**Comment by susannegov** [comment]
Apple ID
> So the current apple ID for both devices is [atdenforcement@austintexas.gov](mailto:atdenforcement@austintexas.gov) currently. What is the apple ID you need it set to so you can login to use the app?
Possible resolution
- [ ] Set apple ID to ATDParkingEnforcement@austintexas.gov on Airwatch

**Comment by susannegov** [comment]
Talked to Diana and JB about the iPads and there's not a lot of information on the previous apple ID or the Good Notes subscription app. Set the tablets to the ATDPESD resource account and handed tablets off to JB.

**Comment by dianamartin** [comment]
# 5/22/24
Talked to Jasmine and she said they used Good Notes for tracking vehicle check-ins and fueling. They also used it for property management stuff. I told her that Shavyvonne had a request for a vehicle tracking solution. I told Jasmine to talk to Shavyvonne about the property management tracking and perhaps we can figure out a resolution or a new free notes app they can use.
