### ISSUE TITLE
Planning service request go live with finance

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17334]
## Roll Out Plans
- [x] Send email notification next week to PMs letting staff know that we are rolling out the Service Requests. Send them the help guide, meeting invites and a link.
   - Sharon will share the updated instructions for us to add to Gitbook
   - Christina will add documentation to Gitbook
   - Sharon, Rochelle, and Tim will work on the email language and will send out next week
   - Go live date is **July 1st**
      - 2 weeks of a soft go live
      - July 15th - no longer accepting email requests and will direct everyone to the service requests
- [x] Christina, Diana, and Stephanie can work on a presentation 
- [x] Christina will send out check-in meeting for next week after we've worked on the presentation - scheduled for 6/18 
   - At check in meeting, have finance give examples that they would like us to demo (2 or 3) 
   - 1 long one, 1 medium, and 1 short
      - Long example: Creating subproject and FDU 
      - Medium example: Increase and decrease of a task order
      - Short example: How to use other
- [x] Clean up the existing test records mid/end of next week (6/21)
- [x] Christina will set up the trainings on various dates to the list of PMs:
   - 1 on the week of June 24th-28th 
   - 2 on the week of July 8th-12th
      - One in the morning
      - One in the afternoon
-  Estimated number of staff using the Service Requests ~ 50 people
- [ ] Once we fix the issue in #17793, filter TK options in service request for only DEPT `6200`

**Comment by ChristinaTremel** [comment]
- [x] Update email notifications sent to Sharon and Rochelle and redirect to the Finance & Purchasing teams email inbox
- [x] New Object Code: 
   - Add field for `FDU Number` and `Object Code`
   - Or easiest update: rename Instructions & Comments to `Provide FDU & New Object Code`
- [x] Added `Submitted Date` to the Service Request Details page
- [ ] For `Change Status/Assignment`, Diana updated rules:
   - `Assigned to` is not blank, `Status` is "In Progress"
   - `Status` has changed to Not Submitted, Assigned to 
   - Tested roling back to the status to **Not Submitted** and the service request was still showing **In Progress**
- [ ] Look into the Job Type `JV` to see if we can include attachments

**Comment by ChristinaTremel** [comment]
## Roll Out Plans
- [ ] Send email notification next week to PMs letting staff know that we are rolling out the Service Requests. Send them the help guide, meeting invites and a link.
   - Sharon will share the updated instructions for us to add to Gitbook
   - Christina will add documentation to Gitbook
   - Sharon, Rochelle, and Tim will work on the email language and will send out next week
   - Go live date is **July 1st**
      - 2 weeks of a soft go live
      - July 15th - no longer accepting email requests and will direct everyone to the service requests
- [ ] Christina, Diana, and Stephanie can work on a presentation 
- [ ] Christina will send out check-in meeting for next week after we've worked on the presentation
- [ ] Clean up the existing test records mid/end of next week (6/21)
- [ ] Christina will set up the trainings on various dates to the list of PMs:
   - 1 on the week of June 24th-28th
   - 2 on the week of July 8th-12th
      - One in the morning
      - One in the afternoon
-  Estimated number of staff using the Service Requests ~ 50 people
- [ ] Once we fix the issue in #17793, filter TK options in service request for only DEPT `6200`

**Comment by ChristinaTremel** [comment]
## Updates 6/17
- Met with Stephanie and Diana and we drafted the presentation for the training sessions
- Scheduled placeholder meeting invites as potential dates and times. Will confirm with everyone tomorrow that these work for all of us!
   - Thursday June 27th from 9-10
   - Wednesday July 10th from 3-4
   - Friday, July 12th from 9-10

**Comment by ChristinaTremel** [comment]
Ask Karo or Diana about sharing the SharePoint folder specifically to all of TPW & CDS (or could be open to everyone as long as it's viewer privileges only: 

SharePoint Folder - [CIP Knack Service Request](https://cityofaustin.sharepoint.com/sites/tpwFinance/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=FueLnh&FolderCTID=0x012000BE9C94D6DC286E47A8D666F5B8E59CFE&id=%2Fsites%2FtpwFinance%2FShared%20Documents%2FCIP%20Finance%2FCIP%20Knack%20Service%20Request&viewid=fbb45346%2Dc89a%2D4dfa%2Db843%2D06ae1ea534ea)

**Comment by dianamartin** [comment]
# 7/1/24
## Test Records to Delete
- [ ] `FSR24-06-0328`
- [ ] `FSR24-06-0329`
- [ ] `FSR24-06-0330`

**Comment by stephaniemoorer** [comment]
@dianamartin can this be closed?

**Comment by dianamartin** [comment]
@stephaniemoorer yes, I think we're good!

**Comment by stephaniemoorer** [comment]
@ChristinaTremel and @dianamartin successfully rolled out the Finance Service Request with no issues. During post rollout meeting stakeholders stated they were very pleased with the rollout.
Closing this issue.
