### ISSUE TITLE
IT Support: BlueBeam License request for Ankush

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#17347]
See https://github.com/cityofaustin/atd-data-tech/issues/17333#issue-2300518117

> What application are you using?

Other / Not sure

> Describe the problem.

I will need Ankush Ashwini P.  to have a BlueBeam license.

> How soon do you need this?

Flexible  — An extended timeline is OK

> Is there anything else we should know?

Ankush starts with the City May 20th so gaining in access in the next 1-3 weeks is fine.
Thank you,
Beth

> Requested By
Elizabeth R.

Request ID: DTS24-114835

**Comment by scottreedy** [comment]
Can't assign a license until the user can accept an email invite from Bluebeam

**Comment by scottreedy** [comment]
The license was assigned and invitation accepted on 05/29, per Teams Chat.
Sure , received it would do as directed , Thank you
