### ISSUE TITLE
Not admin on computer - Rene V.

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#17348]
I am trying to install openVPN on my device, but I cannot as the device is stating that I am not the admin on my device. Could you assist with granting me admin rights?

**Comment by Matthew-M-TPW** [comment]
Reached out to user via teams

**Comment by Craigjacobs-ATX** [comment]
contacted user , found out the the laptop belongs to CDS. Submitted a ticket with CTM to complete this task.

**Comment by Craigjacobs-ATX** [comment]
INC0402535

**Comment by Matthew-M-TPW** [comment]
Machine is connecting to the network
