### ISSUE TITLE
Maximo SBO Site Admin - Escalation Process (Documentation)

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17352]
Write a documentation for SBO Site Admin on escalation process

Sending users to follow-up on any data quality issues, account requests, etc. 
Allow 5 business days. If no response received, escalate to their Supervisor and our Product Manager. 
If no response received, escalate to Superintendent and IT Supervisor Sr.

**Comment by ReneVarg25** [comment]
### 5/23/24
https://docs.google.com/document/d/1-UkSt9qrvuuO22L2md4AruFHPYj_WwLTbmodxdjMbl4/edit

**Comment by rebekkabry** [comment]
# Notes from Rene during Maximo
- DM has requested a process - SV first communication out, and if no response by few days, copy the SI 
- Forestry - any communication should have SI and SV copied (Sean and Lisa)

**Comment by ReneVarg25** [comment]
### 5/30/24
Restructured DM to ALL other Work Groups due to process being similar for others, and Forestry as separate since they have separate process.

Link: https://docs.google.com/document/d/1-UkSt9qrvuuO22L2md4AruFHPYj_WwLTbmodxdjMbl4/edit

**Comment by rebekkabry** [comment]
@ReneVarg25 Reviewed with Rene. Please close when able. Thank you.

**Comment by adry-martinez** [comment]
@ReneVarg25  please be sure you give yourself for the documents you write :)

<img width="763" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzAyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3455a720c0367940a2fd25eea6bd56f43161451/image.png" alt="image.png" />

**Comment by ReneVarg25** [comment]
### 6/4/24
Updated with author and created date
