### ISSUE TITLE
LM Data Pull for PIRc221836 (LP) - Sent data in email

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17353]
### Raw data export is due to customer by 5/20

Parameters: 

- Folder type is LM
- Folder subtype IN (Easement Releases, ROW Vacations)
- Folder issue date > 12/31/2019

**Output 1 (Folder Data):**
- property address
- property ID
- issued date
- folderrsn
- reference #
- sub type description
- work type description

**Output 2 (Fee Data)**
_Same parameters AND fee must be billed._

- folderrsn
- fee code
- fee name
- fee amount
- payment status

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder Send the data in email

**Comment by TracyLinder** [comment]
I emailed the data to Gilbert. Thank you @Lpriya-LIT

**Comment by Nadin-Nader** [comment]
Gilbert has approved the data. closing:

From: Molina, Gilbert <Gilbert.Molina@austintexas.gov> 
Sent: Monday, May 20, 2024 7:29 AM
To: Linder, Tracy <Tracy.Linder@austintexas.gov>
Cc: Nader, Nadin <Nadin.Nader@austintexas.gov>
Subject: RE: 17353 - LM Folder and Fee data 

Looks good, thank you!
