### ISSUE TITLE
Maximo Data Quality -  SBO Completed Work Orders Pending QA

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17351]
<img width="1200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOERxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7178672d6ee7baf5a286c888a32ae4da301c9d9/image.png" alt="image.png" />

Reach out to individual superintendent and verify if they want to mass close WOs prior to 2024. 
Portlet is on the SBO Superintendent Start Center.

**Comment by rebekkabry** [comment]
# 6/3/24 Meeting Updates
_Notes from DTS Retro_

- Discussed as a pain point during Retro 
- Concerned about the outlier amount of WO needed 4COMP status, over 1,000
- Before doing bulk upload to close, need to understand 
    - [ ] is there a process that needs to be discussed, why are there so many?  
    - [ ] are there any reports that could be impacted by the bulk closed numbers? 

# Next Steps 
- [ ] @ReneVarg25  sending an email to get information about state and need of these WOs (please CC' @maccallump and Rebekka)
- [ ] @rebekkabry including this as a discussion point for next Stakeholder meeting, to investigate the above questions (reporting/processes)

**Comment by ReneVarg25** [comment]
### 6/4/24
Sent out emails to Superintendents if they will be working on WOs Prior to FY24. 3 users who appeared on search results no longer are a part of SBO and will have to be closed out on our side.

**Comment by rebekkabry** [comment]
- Notifications have been sent out 
- Each has their own Q/A process. 
- WO in 4COMP, awaiting to be put into QA. 
- Do not recommend mass close, advise QA process. 
- what about 2017-2021? Requested to have them 4COMP? Those 2021 moving forward will be QA. 
    - this has already been completed. 
    - work orders starting at 2021 

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/64b8d03e-a929-46e6-9ebd-6f8ecc549fd5)

**Comment by ReneVarg25** [comment]
### 7/1/24
Cleared queue of users who are no longer part of SBO.

**Comment by rebekkabry** [comment]
### Notes and Concerns 

All the work is completed. 
These are all CSR work orders and parent should already have been created. 
These should only be impacting the workorders that were closed. 
New issue submitted for role updates. 

**Concern:** If they are Service Requests, do they have Parents and Work Logs? Will they come up on other reports...

**Comment by rebekkabry** [comment]
# Updates 
Rene has completed the 4QFR - there were 800, now 65
- there were 5/6 that could not be closed out. 
- sending to x to follow up so we can close them out. 
- View: Superinte / SBO Completed WO Pending QA 
![image](https://github.com/user-attachments/assets/642d5399-e008-482a-8a30-b93ccb86f8a8)
- list: 
Work Order
--
24-175237
24-173702
24-173672
24-173638
24-173605
24-172945
22-144240
21-133668
19-400385

Mendozael has been updated. Will Continue to address in stakeholder meetings.
