### ISSUE TITLE
IT Support: INC0392767 user needs Legistar 

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17358]
BEN WHITE

## Device & User Information (first name and last initial, no last names)
Erin W 

## What's the problem?

INC0392767 ticket came from CTM. Diana asked for me to create it into Github ticket. 

"I need Legistar added to my computer.  I've tried to download but it I get to a point where it wants admin approval and the Finance department said I needed to submit a ticket with CTM."

Location of the software with instructions:
\\coacd.org\dfs\PCIP\Public_Software\Legistar

**Comment by scottreedy** [comment]
installed
