### ISSUE TITLE
[Enhancement] Review Page updates

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#17380]
Update the MSP Review Page
- [x] When option `On Site` selected update all connected records to `Needs Review`
- [x] When `on my own` option selected, add connected record where attachment type is `Notarized Signed Application`
   - [ ] Set `More Information` text - ask stakeholder
- [ ] Add table to upload only the `Notarized Signed Application` or a button form?
- [ ] Allow option of applicant to switch notarize option in My Applications > View application details page after clicking on submit?

**Comment by patrickm02L** [comment]
## 5/31/24
The Action in this Issues is being completed in Issue #17612
