### ISSUE TITLE
Dell Hardware Order - May 2024

### ISSUE THREAD

**Issue by scottreedy** [cityofaustin/atd-data-tech#17396]
REQ0185956 - Submitted to CTM on 05/23/2024 

4 - SI# B1BX26 Dell Latitude 9450 laptops
6 - Dell Premier Rechargeable Active Pen PN7522W

4 - SI# B1BX26 Mobile Precision 7680
6 - Dell Performance Dock- WD19DCS

4 - SI# B1BX26 Precision 3680 Tower
4 - Dell Wired combo KM300C US ENG

30 - Dell 24 Monitor - P2422H, 60.5cm (23.8")
10 – Dell 27 Monitor - P2722H

**Comment by scottreedy** [comment]
Requested quote today

**Comment by scottreedy** [comment]
Received on 06/27/2024. Just lacking the Towers
4 - SI# B1BX26 Dell Latitude 9450 laptops
6 - Dell Premier Rechargeable Active Pen PN7522W

4 - SI# B1BX26 Mobile Precision 7680
6 - Dell Performance Dock- WD19DCS

30 - Dell 24 Monitor - P2422H, 60.5cm (23.8")
10 – Dell 27 Monitor - P2722H

**Comment by scottreedy** [comment]
All items were received.

**Comment by JBStrangenew** [comment]
Do Not Delete:
REQ0185956 - Submitted to CTM on 05/23/2024

4 - SI# B1BX26 Dell Latitude 9450 laptops
6 - Dell Premier Rechargeable Active Pen PN7522W

4 - SI# B1BX26 Mobile Precision 7680
6 - Dell Performance Dock- WD19DCS

4 - SI# B1BX26 Precision 3680 Tower
4 - Dell Wired combo KM300C US ENG

30 - Dell 24 Monitor - P2422H, 60.5cm (23.8")
10 – Dell 27 Monitor - P2722H
