### ISSUE TITLE
Evaluate Wasp InventoryCloud

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#174]
https://atd.waspassetcloud.com/

Please record observations in the [comparison matrix](https://docs.google.com/spreadsheets/d/1r2l_KFgjygCCp1E4oaBa5lyK2QzkVcP5qCu2u85UwcY/edit#gid=2118741241) and compile questions for Steve in the comments below.

**Comment by amenity** [comment]
@dianamartin @johnclary - lmk if you have any issues logging in

**Comment by dianamartin** [comment]
@amenity @johnclary The link to set-up your username redirects you to the new page:  [https://atd.waspassetcloud.com/](https://atd.waspassetcloud.com/) with no ability to set-up a username/password only sign-in.

**Comment by dianamartin** [comment]
Steve was contacted as to the incorrect demo link sent. He has put in another request to get new demo links sent over to ATD.

**Comment by amenity** [comment]
@dianamartin @johnclary - you can now log in [here](https://adt.waspinventorycloud.com/). PW in 1password.

**Comment by amenity** [comment]
@johnclary @dianamartin will you add your thoughts on Wasp here and see what you can fill out in the [requirements matrix](https://docs.google.com/spreadsheets/d/1r2l_KFgjygCCp1E4oaBa5lyK2QzkVcP5qCu2u85UwcY/edit#gid=179231394)?

Then this can be closed.

**Comment by dianamartin** [comment]
I like the WASP interface **Inventory Cloud** myself, I thought it was simple and good for a first time user. It had capability of custom fields and that was nice out of the box. They also have a "staging" or queuing up of requests, which is a check out process in my opinion. 

I'll fill out the matrix for what this system meets.
