### ISSUE TITLE
IT Support: user unable to access the VPN.

### ISSUE THREAD

**Issue by Craigjacobs-ATX** [cityofaustin/atd-data-tech#17403]
Rio Grande

## Device & User Information (first name and last initial, no last names)
Kelsey N , PWD-23XCCK3-N1
## What's the problem?
user gets "quarantine" message every time she tries to access the VPN over the COA0guest network.

**Comment by Matthew-M-TPW** [comment]
Reached out to user via teams. Waiting for their response

**Comment by Craigjacobs-ATX** [comment]
swapped user laptop .
