### ISSUE TITLE
IT Support: User is having issues with her outlook and teams

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17402]
TOWNVIEW BEN WHITE

## Device & User Information (first name and last initial, no last names)
Nadra G
## What's the problem?
Good afternoon,
I'm not sure who I should direct this email to, so if I've missed the mark, please feel free to redirect me. I've been experiencing some issues with my computer lagging. It used to happen occasionally, but it's been occurring more frequently lately. It takes a while to open an app, and there's been an off-and-on delay when I type. Additionally, I'm unable to join Teams meetings from my Outlook calendar, and during a meeting with my supervisor today, our SharePoint Excel spreadsheet wouldn't load. I took a screenshot to show you. After I reloaded the page, it corrected itself, but this is a new issue, so I wanted to report it before it gets worse. Please let me know if you need more information or if this needs to be redirected.

**Comment by Craigjacobs-ATX** [comment]
will follow up with user Wednesday 5/22 to confirm fix.

**Comment by Matthew-M-TPW** [comment]
User called me and was having issues with her mouse. I had the user unplug the mouse and plug it back in she reports that its working now.
