### ISSUE TITLE
Maximo User Request - add two users to Labor and Tools

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17425]
[Copy of New_Employee_Request_Form_v1_070214.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0w4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71cbeb2ae986a6dd656e17f8da51d2cbded63a06/Copy%20of%20New_Employee_Request_Form_v1_070214.xlsx)

Please review attached document for users to be added 
Also add to SBOOVL and SBOMILL job plan.

**Comment by ReneVarg25** [comment]
### 5/23/24
Requests submitted to CTM. Awaiting creation.

**Comment by ReneVarg25** [comment]
### 5//23/24
Accounts created, access granted, and users added to job plans. Notified supervisors.
