### ISSUE TITLE
Missing Marking ID in Long Line dates dataset

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#17427]
Missing the `markings_long_line_id` field in this socrata dataset [here](https://datahub.austintexas.gov/dataset/TRANSPORTATION_marking_long_line_dates/m49j-isdy/about_data). I believe there is a FME workflow keeping this dataset updated.

![image](https://github.com/cityofaustin/atd-data-tech/assets/30810522/0a7f3f88-fe51-47dd-85e1-0e1af31dc37f)

**Comment by ChristinaTremel** [comment]
## Notes from GIS QA Sync
- Andrew and team can look into how many of the long line assets have duplicate CTN segment IDs 
   - `7565` unique values 
   - `7593` total records
- Clean up the ~30 records that have duplicate CTN values
- We could then move forward with using the `CTN_segment_ID` is the unique identifier

**Comment by Charlie-Henry** [comment]
Looks like most of the work is done here. We will be using the CTN segment ID going forward.
