### ISSUE TITLE
Verify users' access in Maximo PROD

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17440]
Verify Users in PROD and TEST for training.

**Comment by adry-martinez** [comment]
Review list via [Google Doc](https://docs.google.com/document/d/1E2UBT17GZkvRwFxZ3d0kYp7CfApKPBWXL6yl-bbBHaU/edit?usp=sharing)

**Comment by adry-martinez** [comment]
Two users were verified and do not have access to PROD, USD notified as they are not able to attend this training. USD acknowledged.

**Comment by ReneVarg25** [comment]
### 5/22/24
Two users were not found within TEST, but are active in PROD. Made arrangements for training.
