### ISSUE TITLE
[BUG] VZE crash map does not run locally on Linux/Ubuntu

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#17447]

**Comment by johnclary** [comment]
@roseeichelmann would you fill in the details of your system/browser and what happens when you try to use the VZE crash details map locally?

**Comment by roseeichelmann** [comment]
Figured it out...embarrassed to say i just needed to npm install which im shocked i hadnt tried before and i swear i did.. so closing this out!! :smile:
