### ISSUE TITLE
IT Support: Set up Monitor in Conference Room A

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17509]
<ST. ELMO

## What's the problem?
Please attach the arm and the monitor to the Computer in the Rack

**Comment by Vaishnav1397** [comment]
@Matthew-M-TPW Forwarding the request, can you check if we have some monitors at location, if not can get one from Ben White.

**Comment by Matthew-M-TPW** [comment]
It cant handle a monitor
