### ISSUE TITLE
Update [PWD-FMP2W2-N1- Laptop status be checked] and to Windows 11

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#17517]
OTC
## Device & User Information (first name and last initial, no last names)
Cheryl P
## What's the problem?
Need to check the status of laptop with user and updated to win 11 as well below fields.
[ ]Check Inventory DTS and add Windows version [If the machine is not in inventory add it]

[ ]Check Intune [If the user is not assigned to the computer, add the user]

[ ]Check CTM Data Base (https://atx.servicenowservices.com/now/nav/ui/classic/params/target/%2Falm_asset_list.do%3Fsysparm_view%3D%26sysparm_first_row%3D1%26sysparm_query%3Dmodel_category%253D81feb9c137101000deeabfc8bcbe5dc4%26sysparm_clear_stack%3Dtrue) [correct and add the info if needed]

[ ]Gather COA tag

[ ]Update Computer to Windows 11
[PWD-FMP2W2-N1]

**Comment by Matthew-M-TPW** [comment]
I was scheduled to update user's computer but they canceled

They rescheduled to Wednesday, June 12, 2024 3:00 PM-3:30 PM

**Comment by Matthew-M-TPW** [comment]
machine was updated
