### ISSUE TITLE
Update [PWD-995TG13-N1- OptiPlex 5070 ] to Windows 11

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#17515]
OTC
## Device & User Information (first name and last initial, no last names)
Stephanie F 

## What's the problem?
Need to check if the system is in use and update the require fields below.
[ ]Check Inventory DTS and add Windows version [If the machine is not in inventory add it]
Added under inventory
[ ]Check Intune [If the user is not assigned to the computer, add the user]
Status-Un assigned
[ ]Check CTM Data Base (https://atx.servicenowservices.com/now/nav/ui/classic/params/target/%2Falm_asset_list.do%3Fsysparm_view%3D%26sysparm_first_row%3D1%26sysparm_query%3Dmodel_category%253D81feb9c137101000deeabfc8bcbe5dc4%26sysparm_clear_stack%3Dtrue) [correct and add the info if needed]

[ ]Gather COA tag

[ ]Update Computer to Windows 11
[ PWD-995TG13-D1]

**Comment by Matthew-M-TPW** [comment]
machine was retired
