### ISSUE TITLE
Update [PWD-BNTJST2-N1- Returned and to be checked-Update to Windows 11

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#17514]
Town view/ Dalton/ St Elmo
## Device & User Information (first name and last initial, no last names)
Frank R
## What's the problem?
[ ]Check Inventory DTS and add Windows version [If the machine is not in inventory add it]
In inventory
[ ]Check Intune [If the user is not assigned to the computer, add the user]
Not available
[ ]Check CTM Data Base (https://atx.servicenowservices.com/now/nav/ui/classic/params/target/%2Falm_asset_list.do%3Fsysparm_view%3D%26sysparm_first_row%3D1%26sysparm_query%3Dmodel_category%253D81feb9c137101000deeabfc8bcbe5dc4%26sysparm_clear_stack%3Dtrue) [correct and add the info if needed]

[ ]Gather COA tag
DELLW71184
[ ]Update Computer to Windows 11
[ADD COMPUTER NAME HERE]
 PWD-BNTJST2-N1

**Comment by Matthew-M-TPW** [comment]
Reached out to user via teams

**Comment by Matthew-M-TPW** [comment]
This machine was replaced
