### ISSUE TITLE
Encampment Features: Advanced search, unique ID

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17551]
### Leftover Items from user review #16999 
- [x] Advanced search page
- [x] Unique ID

**Comment by dianamartin** [comment]
# 5/29/24
## Created Menu button
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/7f5aac9c-7d97-4f05-8fb1-f6ec0767d734)

## Advanced Search page
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/c9d48011-3c73-42e4-9683-e727c387d7c6)

**Comment by dianamartin** [comment]
# 5/29/24
- [ ] Need to work on Unique ID

**Comment by dianamartin** [comment]
# 5/30/24
Unique ID format:  `Unique ID: YY-MM- 4 or 5 digit`
- [x] Added ID fields to generate custom ID
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b60c0b3a-af6e-4bc9-98d4-306f73750cef)

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/c2c816a8-833c-4032-9c22-4b7fe7fd6de8)

**Comment by TracyLinder** [comment]
Looks good!
