### ISSUE TITLE
Stakeholder Review 5/30/24 for KNACK encampment module

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17586]
**Meeting Purpose: Gather user feedback of the updated prototype.**
- Our last review was on [5/16/24](https://github.com/cityofaustin/atd-data-tech/issues/16999#issuecomment-2115578945).
- [OCE Portal link](https://atd.knack.com/oce#home/)

**Agenda:**
- [x] Review app features/content
- [x] Discuss go-live (users, migration?)
- [x] Next steps?

**Comment by TracyLinder** [comment]
## Tracy's Notes

Features:
**Advanced search**


**Reports**
- [ ] View details: reduce number of columns. Users want to see estimated date, completed date, tonnage. 


**Work Order Details:**
- [ ] Add field `Site Cost`

**Comment by dianamartin** [comment]
# 5/30/24
- [x] Finished updating left over work on connecting work order to `underpass_photos`

**Comment by TracyLinder** [comment]
This is good to close.
