### ISSUE TITLE
Maximo Training - How to add Premium (OT) Time on a Work Order

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17580]
Create a help guide on how to add Premium OT time on a WO.

**Comment by adry-martinez** [comment]
@rebekkabry
this document is done for Clay. 
https://docs.google.com/document/d/1Cy9uDifAm5Ee_ZvOGr_S3tP6-OnUH-1YPavgJ_1hSHc/edit?usp=drive_link

**Comment by rebekkabry** [comment]
Emailed a PDF file to Clay. 
[Maximo Quick Reference Handout - How to add Premium Time (OT) to a Work Order.pdf](https://github.com/user-attachments/files/16279078/Maximo.Quick.Reference.Handout.-.How.to.add.Premium.Time.OT.to.a.Work.Order.pdf)


Attached you will find a support document to assist with communicating OT and Premium time entry into MAXIMO. Please confirm which days/times are OT for your groups and we can get it added onto the document, if you would like.  For example: Thursday after 6pm to Monday 6am, Monday through Wednesday 6pm to 6am.
