### ISSUE TITLE
Top Ten Assets Clean-Up | Open Data Quality Review - Spring 2024

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#17588]
## Top 10 Assets for TPW - Our Priority for 6/14/24 Readiness
- while we will get an extension to complete the review for our hundreds of assets, we have agreed with CTM to complete these top 10 assets by the original deadline, June 14, 2024
- the liaisons will also ask SMD and AMD experts for their assistance in reviewing these assets metadata

![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/8db2fae9-a0a5-4a9d-884a-c88a29d46e80)

- Phase 1 - Ownership - Complete - All are DTS datasets ✅ (we will want to note the business contacts internally)
- Phase 2 - Asset Review - Likely short work? 
- Phase 3 - Metadata Review - Need to review and complete 🎯 

<span><span class="ui-provider a b c d e f g h i j k l m n o p q r s t u v w x y z ab ac ae af ag ah ai aj ak" dir="ltr">
Asset UID | Asset Name | Asset Type | Sum of Interactions in 2024
-- | -- | -- | --
dx9v-zd7x | [Real-Time Traffic Incident Reports](https://github.com/cityofaustin/atd-data-tech/issues/17588#issuecomment-2140822076) ✅  | Dataset | 783005
v7vh-gbi6 | [Mobility Management Center Issues](https://github.com/cityofaustin/atd-data-tech/issues/17588#issuecomment-2140826704)✅  | Dataset | 271468
5zpr-dehc | [Traffic Signals Status](https://github.com/cityofaustin/atd-data-tech/issues/17588#issuecomment-2140840877)✅  | Dataset | 136876
4qmj-36nv | [Traffic Signal Work Orders](https://github.com/cityofaustin/atd-data-tech/issues/17588#issuecomment-2140842488)✅ | Filter | 122355
p53x-x73x | [Traffic Signals and Pedestrian Signals ](https://github.com/cityofaustin/atd-data-tech/issues/17588#issuecomment-2140853478) ✅ | Dataset | 98760
ypbq-i42h | [Real-Time Road Conditions](https://github.com/cityofaustin/atd-data-tech/issues/17588#issuecomment-2140855146) ✅  | Dataset | 86191
b4k4-adkb | [Traffic Cameras](https://github.com/cityofaustin/atd-data-tech/issues/17588#issuecomment-2140856699) ✅  | Dataset | 82104
i626-g7ub | [Radar Traffic Counts](https://github.com/cityofaustin/atd-data-tech/issues/17588#issuecomment-2140858476) ✅  | Dataset | 78178
y2wy-tgr5 | [Austin Crash Report Data - Crash Level Records](https://github.com/cityofaustin/atd-data-tech/issues/17588#issuecomment-2140860022)✅   | Dataset | 67739
p7pt-re4k | [Mobility Management Center Activities](https://github.com/cityofaustin/atd-data-tech/issues/17588#issuecomment-2140881721) ✅  | Dataset | 50070

</span></span>

**Comment by KaroEngstrom** [comment]
## Real-Time Traffic Incident Reports ([dx9v-zd7x](https://datahub.austintexas.gov/Transportation-and-Mobility/Real-Time-Traffic-Incident-Reports/dx9v-zd7x/about_data))
- Reviewed as part of the audit top dataset #15411 #15421 
- [ ] Ownership Review 
- [ ] Asset Review
- [ ] Metadata Review

**Comment by KaroEngstrom** [comment]
## Mobility Management Center Issues | [v7vh-gbi6](https://datahub.austintexas.gov/Transportation-and-Mobility/Mobility-Management-Center-Issues/v7vh-gbi6/about_data)

**Comment by KaroEngstrom** [comment]
## Traffic Signals Status | [5zpr-dehc](https://datahub.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-Status/5zpr-dehc/about_data)
- [ ] Ownership Review 
- [ ] Asset Review 
- [ ] Metadata Review

**Comment by KaroEngstrom** [comment]
## Traffic Signal Work Orders | 4qmj-36nv
- [ ] Ownership Review
- [ ] Asset Review 
- [ ] Metadata Review

**Comment by KaroEngstrom** [comment]
## Traffic Signals and Pedestrian Signals | [p53x-x73x](https://datahub.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-and-Pedestrian-Signals/p53x-x73x/about_data)
- [ ] Ownership Review 
- [ ] Asset Review 
- [ ] Metadata Review

**Comment by KaroEngstrom** [comment]
## Real-Time Road Conditions | [ypbq-i42h](https://datahub.austintexas.gov/Transportation-and-Mobility/Real-Time-Road-Conditions/ypbq-i42h/about_data)
- [ ] Ownership Review 
- [ ] Asset Review
- [ ] Metadata Review

**Comment by KaroEngstrom** [comment]
## Traffic Cameras | [b4k4-adkb ](https://datahub.austintexas.gov/Transportation-and-Mobility/Traffic-Cameras/b4k4-adkb/about_data)
- [ ] Ownership Review 
- [ ] Asset Review 
- [ ] Metadata Review

**Comment by KaroEngstrom** [comment]
## Radar Traffic Counts | [i626-g7ub](https://datahub.austintexas.gov/Transportation-and-Mobility/Radar-Traffic-Counts/i626-g7ub/about_data)
- [ ] Ownership Review
- [ ] Asset Review
- [ ] Metadata Review

**Comment by KaroEngstrom** [comment]
## Austin Crash Report Data - Crash Level Records | [y2wy-tgr5](https://datahub.austintexas.gov/Transportation-and-Mobility/Austin-Crash-Report-Data-Crash-Level-Records/y2wy-tgr5/about_data)
- [ ] Ownership Review
- [ ] Asset Review 
- [ ] Metadata Review

**Comment by KaroEngstrom** [comment]
## Mobility Management Center Activities | [p7pt-re4k](https://datahub.austintexas.gov/Transportation-and-Mobility/Mobility-Management-Center-Activities/p7pt-re4k/about_data)
- [ ] Ownership Review 
- [ ] Asset Review 
- [ ] Metadata Review

**Comment by ChristinaTremel** [comment]
Scheduled meeting with the MMC staff for Monday, 6/10!

**Comment by KaroEngstrom** [comment]
## Wed 6/12/24
- noted that these are all done in the [TPW Assets spreadsheet ](https://cityofaustin.sharepoint.com/:x:/r/sites/COAOpenDataLiaisons2of2/_layouts/15/Doc.aspx?sourcedoc=%7BB6E1AD76-11DD-471E-966A-CC66E69177BD%7D&file=TPW%20Assets.xlsx&action=default&mobileredirect=true)
- notified Adrianne that these are all done via Teams
