### ISSUE TITLE
Build Underpass Weekly Reporting Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17590]
### Enhance the Underpass Cleanup program reporting to replace the current weekly report that staff is manually creating.

[Underpass Weekly Update.pdf](https://github.com/cityofaustin/atd-data-tech/files/15505735/Underpass.Weekly.Update.pdf)

**Comment by TracyLinder** [comment]
We will meet with stakeholders on 7/30/24 to continue scoping.

**Comment by dianamartin** [comment]
# 8/2/2024
Working on adding a new "Report Display Name" to use for the calendar list page that we talked about during our OCE Report Sync. 
- [ ] Created `Report Display Name`
-  Messaged Robert
>Hey Robert, I'm working on the Underpass report stuff and was trying to get the Council District in the label. I realized that the Council Districts are blank right now. Do you have your list of locations that have the Council Districts?

He replied and sent me a spreadsheet 
- [ ] Import data records to update Council Districts

**Comment by dianamartin** [comment]
# 8/2/2024
Worked on the Underpass Weekly Report 
![image](https://github.com/user-attachments/assets/6b43593f-5ca5-4093-8181-44d73a3fc8de)

**Comment by TracyLinder** [comment]
Diana sent Robrert a preview. We'd like feedback before we make any updates. I'll ping Robert.

**Comment by dianamartin** [comment]
# 8/15/2024
@TracyLinder I realized we need to make OCE an official Knack Banner header to wrap things up. We also need to finalize the "Underpass Weekly Report" with Robert.

**Comment by dianamartin** [comment]
# 10/15/2024
- on 8/2, Robert replied
>...Thank you for all your hard work on this.
Looks great! Thank you. I will have the team adjust if needed. Have a great weekend
