### ISSUE TITLE
Evaluate Finale Inventory

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#176]
Trial account login: https://app.finaleinventory.com/atd/sc2/?account/info
Credentials in 1Password; expires 6/19.

Please record observations in the [comparison matrix](https://docs.google.com/spreadsheets/d/1r2l_KFgjygCCp1E4oaBa5lyK2QzkVcP5qCu2u85UwcY/edit#gid=2118741241) and compile questions for Chinh in the comments below. 

### Resources
- [API](https://support.finaleinventory.com/hc/en-us/categories/115001160947-API-Documentation)
- [Help documentation](https://support.finaleinventory.com/hc/en-us)
- Training support available during this time; submit a request from the _Help_ menu

**Comment by johnclary** [comment]
- this one was the easiest app for me to grasp and feel comfortable working with right away
- does not appear to have a "customer" facing order/request submission
- api docs look fairly comprehensive with useful examples
- some out-of-the-box integrations: push to FTP, email, ...

**Comment by dianamartin** [comment]
- I like the abundance of training videos and dedicated Help Center
- Some of the buttons aren't that intuitive like the "save" button
- Date filter widgets look smart
- Simple interface, kind of too simple. wish it had better UI 

all my thought so far...

**Comment by amenity** [comment]
Thanks, @dianamartin @johnclary! Does either of you have time to fill out the Finale column of the [requirements matrix](https://docs.google.com/spreadsheets/d/1r2l_KFgjygCCp1E4oaBa5lyK2QzkVcP5qCu2u85UwcY/edit#gid=179231394)?

**Comment by amenity** [comment]
@johnclary Do you mind filling out the Finale column of the [requirements matrix](https://docs.google.com/spreadsheets/d/1r2l_KFgjygCCp1E4oaBa5lyK2QzkVcP5qCu2u85UwcY/edit#gid=179231394) while this is fresh in your mind? 🙏

Once that's done this issue can be closed. 🌂

**Comment by johnclary** [comment]
Done. Closing.
