### ISSUE TITLE
[Enhancement] Feedback Updates from MSP meeting 5/30/24

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17612]
## Description
- [x] Update 1 of 4 to 1 Application Information
<img width="415" alt="Screenshot 2024-05-31 at 2 28 51 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/5566727/75e2000f-8f84-48bf-a0ce-963689c87eff">

- [x] Remove the “print” link on the top right nav
   - Removed in Print Application Long
   - Removed in Print Application Short

- [ ] Expressed interest in a mobile view of the form (60-70% of applicants). They are good with PLA providing the printed version for on-site
   - Added mobile friendly step indicator in CSS

- [x] If Notarize On My own - select “Submitted - Needs Applicant Action” status instead
   - Add title to separate submitted vs need to notarize attachment
   - Filter notarize file on the non-editable table view
      - `Attachment Type is not Notarized Signed document`
   - In more information for notarized sign application attachment type, 
   - Activate a button

<img width="415" alt="Screenshot 2024-05-31 at 2 29 02 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/5566727/d60d9f7e-b8ad-4ef8-b728-769a9d808282">

- [x] Make warning banner appear on “My Applications” when “On My Own”
    - On Site
```
<p>Thank you for selecting to notarize your application on-site.<br>
</p>
<ul><i>
	<li>COA Mobility Services staff will review application and required documents online. This should take about XXX business days.</li>
	<li>Wait for email notification of “Approved” application </li>
	<li>Call Mobility Services office to schedule test appointment, an get application notarized, pay application fee on site</li></i>
</ul>
```
   - On my own
```
<p>Before you can continue, you will need to get your application notarized in Travis County and attach it to your application.<br>
</p>
<ul><i>
	<li>You must print application page below</li>
	<li>Get printed document notarized within Travis County </li>
	<li>Go back to Application details and attach notarized document </li>
	<li>Resubmit Application </li><i>
	<li>COA Mobility Services staff will review application and required documents online. This should take about XXX business days.</li>
	<li>Wait for email notification of “Approved” application</li></i></i>
</ul>
```

- [x] Add “I want to notarize” column in “My Application” page for applicant
   - Named the column `Notarize`
- [x] Move “Notarized” attachment section to the bottom (like the “Reviewer details”)
    - Add reviewer comment to the table view 
- [x] Background information
   - Letter ABCD for Background Information
- [x] More Information - make like “Driver license"
   - Bold “Notarize on site”
   - Bold “Notarize on your own”
- [x] Add Validation field (Notarized Doc attached)
   - Update status and add a trigger button that allows them to complete action

- [x] #17784
   - Submitted - Require Action
   - Pending Payment
   - Pending Action
   - Approved, Declined, Expired, Canceled
 
# Notes
- Application status
   - Submitted - Under Review = means applicant is doing it on site
   - Submitted - Require Action = means applicant is notarizing on their own
   - Pending Approval -
   - “Pending - Needs Payment” = MS PLA will manually change status

**Comment by patrickm02L** [comment]
## 6/12/24
For bolding go here, and make sure to update the record rules

**Comment by susannegov** [comment]
This is done and ready to close
### Some notes
- Couldn't modify the record rules to be on the other shortened notarized field as the conditional rules are applied after the record rules unfortunately.
- I was able to modify the page rules to the shorten field though

**Comment by susannegov** [comment]
- The Default option was set On Site, I changed it back to blank so any **new** applications will not show the banner.
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/03f21800-e62f-48ef-bd7c-9a014b40d10e)
- I moved the equation to be above the count used for validation which fixed the Yes/No Is complete required attachment (it was not the record rule as I thought)
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/bfe7ab83-e78d-4971-a0fb-02f55a993784)
