### ISSUE TITLE
Maximo Account - modifying Tyler S. rights to update Domains for the purpose of Asset Management

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17610]
Tyler S is the Program Manager for SBO Heavy Equipment. He is responsible for updating Maximo with all the required rotating assets. 

From time to time, he requests DTS Maximo to update the HEAVY_EQUIPMENT classification's attributes (HEAVY EQUIPMENT TYPE and EQUIPMENT TYPE ID) to reflect the newly purchased assets. 

@GaneshKamarapu, please see if we are able to allow him rights to modify/update Domains within these classifications so that he can continue updating as needed. These requests are seldom but the guidance and giving him rights will help him move along with updating Maximo accordingly. 

I am working on designing a Scribe to help with the how-to when it comes to updating such Domains.

**Comment by adry-martinez** [comment]
# Updating Attributes for Classifications in Maximo
#### [Made by Adriana Martinez with Scribe](https://scribehow.com/shared/Updating_Attributes_for_Classifications_in_Maximo__ay2UJw9aSlu3RkL80E40DQ)
You will need SBO SITE ADMIN rights to make such changes.

1\. Click "Classifications"

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/30c6cd7d-0059-4643-ab7f-f42872bd1aec/ascreenshot.jpeg?tl_px=0,0&br_px=859,480&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=201,125)


2\. Click this text field.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/d8cdf94f-efcf-4f25-bd06-809f555f7448/ascreenshot.jpeg?tl_px=0,0&br_px=859,480&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=280,178)


3\. Type the Classification you are updating then click on the Classification.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/55f208d2-1bec-429e-9d32-03a282f7fec2/ascreenshot.jpeg?tl_px=0,0&br_px=859,480&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=293,212)


4\. Under Attributes, click "Filter"

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/aed40619-a85c-4c59-9918-23bf248f0bc6/ascreenshot.jpeg?tl_px=0,401&br_px=859,882&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=357,212)


5\. Find the Attribute you are updating.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/36d90e0c-88cc-4ed3-92f6-c8f412eae0dd/ascreenshot.jpeg?tl_px=0,430&br_px=859,911&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=356,234)


6\. Click on the arrow to expand the Attribute.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/7e4d3312-7688-4564-8939-0a2f51f1d82a/ascreenshot.jpeg?tl_px=0,430&br_px=859,911&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=225,376)


7\. Locate, then copy the Domain.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/c4fb2908-fa7b-4da3-b563-0d82d0ea9825/ascreenshot.jpeg?tl_px=0,430&br_px=859,911&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=233,264)


8\. Go to the Applications Menu.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/d0d404dd-c7a4-4cf1-8657-1429132dfa79/ascreenshot.jpeg?tl_px=0,0&br_px=859,480&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=49,-2)


9\. Click on System Configuration &gt; Platform Configuration &gt; Domains

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/e4a51d85-8714-4e47-9df7-9e8c92c61d19/ascreenshot.jpeg?tl_px=61,168&br_px=920,649&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=402,212)


10\. Paste the copied Domain under the Domain column. Then click on Edit Detail.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/47ab4240-7f94-4f57-bf81-c1959726da7b/ascreenshot.jpeg?tl_px=0,0&br_px=859,480&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=244,158)


11\. Navigate to the Domain you are searching for 

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/cb260b6b-7ce4-4d97-a2fe-d7e4de7197bf/ascreenshot.jpeg?tl_px=515,74&br_px=1375,555&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=402,212)


12\. Click "New Row"

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/55dbd4cc-1766-48c0-b4ad-c040dedac7b3/ascreenshot.jpeg?tl_px=357,430&br_px=1217,911&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=402,271)


13\. Click the "Value:" field.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/0c7f5067-5f9a-47a3-81cf-7c5de89f5217/ascreenshot.jpeg?tl_px=282,429&br_px=1142,910&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=402,212)


14\. Mirror the set up to the other values listed and input what is requested by the Requestor.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/9d13675f-4fbb-4745-9ef8-e85339d80be0/ascreenshot.jpeg?tl_px=218,430&br_px=1078,911&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=402,251)


15\. Click "OK"

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/b1209715-9599-47da-9c71-71dfa5934284/user_cropped_screenshot.jpeg?tl_px=118,0&br_px=977,464&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=642,399)


16\. To delete the value, go to Edit Detail

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/bbdd447e-c5ba-41fb-80c5-051ac892ba20/ascreenshot.jpeg?tl_px=0,0&br_px=859,480&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=249,153)


17\. Navigate to the Domain you want to update.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/2d950e87-b041-40c5-b938-5c8c2eebf653/ascreenshot.jpeg?tl_px=718,70&br_px=1578,551&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=402,212)


18\. Click on the Delete icon.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/4e50494c-6c33-4fdc-a1b3-8f2b87a01916/ascreenshot.jpeg?tl_px=889,360&br_px=1749,841&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=402,212)


19\. Click "OK"

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2024-05-31/acc3a653-931e-4f11-b659-fdcb8334b8aa/ascreenshot.jpeg?tl_px=804,430&br_px=1664,911&force_format=png&width=860&wat_scale=76&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=402,266)


20\. The Domain will be updated automatically.
#### [Made with Scribe](https://scribehow.com/shared/Updating_Attributes_for_Classifications_in_Maximo__ay2UJw9aSlu3RkL80E40DQ)

**Comment by adry-martinez** [comment]
Reassigned to Rene to meet with CTM Maximo team to get training on how-to

**Comment by rebekkabry** [comment]
When we speak to CTM 
- will the asset values be edited or just the details on the asset? Considered if changes are made to the foundational asset list.

**Comment by rebekkabry** [comment]
# Updates

sent CTM an email requesting insights into above questions.

**Comment by rebekkabry** [comment]
# per CTM 
`
The SBO Site Admin group has the rights to update domain values.  We don’t usually extend that permission to end users since it is an all or nothing permission.  If you have the permissions to update 1 domain, you have the permissions to update them all.  We have run into problems in the past with domains being updated incorrectly and causing system problems, so we prefer to keep this to the site admins for the departments.`  

Emailed requesting process to address request. 8/8/24

**Comment by rebekkabry** [comment]
# per CTM 
_in response to how we should address or direct requestors_ 

In the past, the users would submit a request to Rene or Adriana and they would be able to modify the domain.  If you need help modifying the domain please let me know and we can do a teams call on how to update it. The user can also submit a SN ticket to our group and we are able to update it as well.

**Comment by rebekkabry** [comment]
# Draft Email to Tyler: 

Thank you for contacting DTS Maximo Support. We have investigated your request regardiing rights to update Domains of Asset Management and how to accomdate a change in asset information. Due to the sensentivity of the data records and connections, we will be unable to update user rights in your MAXIMO start center. However, below are the following methods to submit a request to modify domains. 
1. CTM - Submit a SN ticket 
2. DTS Maximo - Submit a DTS ticket
