### ISSUE TITLE
[Enhancement] Add Reviewer comments to reviewer side of app

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17615]
## Description

Staff would like a place to keep internal comments about interactions they have with applicants. See SMRT comments as an example #8964 and go to [app link](https://atd.knack.com/smrt#application-dashboard/view-application-details-reviewer/62d57180d470c6001e501aef/) to see how it's implemented. 

<img width="900" alt="Screenshot 2024-05-31 at 3 00 14 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/5566727/7c8ca50e-4f56-4d1b-81c9-f8d20d31b5ea">

**Comment by susannegov** [comment]
# SMRT Example Test Provider
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/184e80d5-5132-4ee6-a3ce-6bc9f129c9fe)

## `application_comments` object table
- Comment ID
   -  auto increment
- application
   - connection field 
- Email
   - text formula to applicant email
- Applicant Email
   -  Email field type conditional rule where if Email is not blank set to field value email
- Required Attachment Name
   - Text formula but it looks like the fields were deleted in SMRT? 
- Comment
   - Rich Text 
- Created By
- Created Date
- Modified By
- Modified Date
- Email Confirmation
   - Yes/No checkbox require yes default not Checkbox text "Send Email"

**Comment by susannegov** [comment]
- [x] Added Reviewer Comments grid view
   - [ ] TO DO: Setup Record rules to be similar to SMRT
   - [ ] TO DO: Setup Submit/Email(?)rules to be similar to SMRT
- [x] Added `Add Reviewer Comment` form

**Comment by susannegov** [comment]
Setup record rule and email rules. ready for review/qa
