### ISSUE TITLE
Turn on Email tab feature in test on RW folder - (LP) - (Ready for UAT on TEST)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17611]
**Acceptance Criteria** 

- Email tab needs to be added to RW folder in Test in the AMANDA Tab Mask.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and requested for Dev and Test promotion, SCTASK0446549

**Comment by Lpriya-LIT** [comment]
<img width="1510" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1pqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8ab1927ca2e04717197dc4d176a8a10e0fee688/image.png" alt="image.png" />

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Email tab has been added to RW , Ready for UAT on Test

**Comment by KyleErich** [comment]
@Nadin-Nader @Lpriya-LIT UAT on Test approved. I think that means we can close this card since it doesn't ask for any kind of Prod promotion. I believe we just wanted to play around with this in Teams so I'll bring this up in our 9/13/24 DTS-ROW meeting. Thanks!

**Comment by Nadin-Nader** [comment]
Per our 2pm meeting the concensus with this was a happy one and lead to ultimately deciding to close this as it was just a feature they wanted to see would work intead of the Salesforce solution. Concensus was happy about the email tab function and may visit this in the future. As of right now we decided to close this.
