### ISSUE TITLE
Update metadata and data dictionary for VZV socrata dataset(s)

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#17621]
@KaroEngstrom invited me to a meeting concerning keeping the open data portal up to date and accurate. Two requests came out of it concerning the VZV-driving [crash dataset](https://data.austintexas.gov/Transportation-and-Mobility/Austin-Crash-Report-Data-Crash-Level-Records/y2wy-tgr5):

* Can we add some information to the description copy that links to the VZV, as this data is used to power it? Should we indicate that there is that relationship between the dataset and the VZV, either in this metadata or on the VZV itself?
* Can we review the columns in the dataset and add a per-column descriptive text string where it's missing. We have these on most of the columns, but not all.

While we're looking at the crash dataset, should we go ahead and do the same thing for the [persons/demographics](https://data.austintexas.gov/Transportation-and-Mobility/Austin-Crash-Report-Data-Crash-Victim-Demographic-/xecs-rpy9) dataset as well?

**Comment by KaroEngstrom** [comment]
The deadline to CTM is June 14. Thank you for helping out with this dataset 🙏

**Comment by johnclary** [comment]
I updated both datasets. Nice!
