### ISSUE TITLE
Request Additional TPW HR Data into Knack

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#17642]
# Background 
Recent MAXIMO account creation requests have been delayed due to missing information needed to set up account. The current work around is to look via Outlook profile for data missing in HR. 
     - _Example DTS Requests_: #17591 and #17503 

# Impact 
- They are most likely not seen in Knack because they are new employees and the information hasn't be uploaded yet. 
- 🚨 UGK, Active Directory (outlook) 

# Ask
**Currently Have:** 
Employee ID, Name, Title 

**Needed:** 
Division, Work Group, Supervisor Name

**Comment by rebekkabry** [comment]
@dianamartin can we discuss adding Division, Work Group, Supervisor Name to the Knack HR portal that MAXIMO has access to when creating new accounts. Or if another consideration as needed, as this is most likely only impacting new employees.

**Comment by dianamartin** [comment]
@rebekkabry cc @stephaniemoorer 
We already have a page for the Maximo team to reference TPW Employees for Maximo account creation, it's the "Maximo | SBO User Verification" page. 
- I has the "Division and Supervisor Name". We don't track work groups in the Knack HR Portal so the sub groups (Concrete, Overlay, Seal Coat) would not be tracked. 

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/d1a2272c-231f-46c4-9a7e-624ef67ecdd5)

**Comment by rebekkabry** [comment]
@ReneVarg25 Please see Diana's response and advise if you have the ability to view. Thank you.

**Comment by dianamartin** [comment]
# 7/1/24
There is already a solution created, closing.
