### ISSUE TITLE
Maximo PM: SBODTE June WO creation

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17657]
This issue is to create a bulk of WOs set by a PM for SBODTE on a monthly basis. 

Once created, please notify Vincent S. with SBODTE.

**Comment by rebekkabry** [comment]
@GaneshKamarapu Did Adry discuss an automated email for this WO list? Not sure if was on your list yet and if we need to manaully prepare this for them in June. Thank you.

**Comment by rebekkabry** [comment]
# 6/29/24

- Created Parent work 
- Provided report on Grandparent status
- Files sent to Vincent and DTS Maximo
- Closing issue
