### ISSUE TITLE
Maximo Report - District Maintenance Data Quality Report, error in exporting data to Excel [Issue]

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17662]
Ran report, exported Completed Parent - Open Children report page, excel is not populating any data. See screenshots below. 

<img width="1488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem8zQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8fed2e8c60b0e2e8423f5fbfdcbfa6ba3ba30e12/image.png" alt="image.png" />

<img width="1559" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenMzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4421c49550fdd9b17a864088decfa2ad579bafe8/image.png" alt="image.png" />

**Comment by GaneshKamarapu** [comment]
@adry-martinez @rebekkabry  query is pully data prior to " statusdate < to_timestamp ('2017-03-23 23:59:59.998' , 'YYYY-MM-DD HH24:MI:SS.FF') " based on this there is no data. do we need to change this?

**Comment by adry-martinez** [comment]
Issue's been resolved due to user error.
