### ISSUE TITLE
iPad transfer to Rene V.

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17699]
Adriana M. leaving TPW DTS on 6/14/24. Would like to transfer device responsibility to Rene V.

**Comment by Matthew-M-TPW** [comment]
sent chat to users "[3:00 PM] , Matthew
How do you guys want to handle the ipad swap out? "

**Comment by Matthew-M-TPW** [comment]
User responded 
I have the IPad
