### ISSUE TITLE
Prep Slides for Smart Cities Lab & Texas Innovation Alliance call "Mobility Data Specification (MDS): Part 2" on 6/13

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#177]
> We are putting part two of the deep-dive on MDS together that will focus on implementation.  We have LA, Louisville, and DC cued up to speak about implementation and some of the technical issues.  We wanted to follow up to confirm your availability to present for ten minutes or so on June 13 at 11am.  Also, if you could please send us your slides ahead of the call we can have them uploaded on the Webex.  If you'd like to touch base by phone, we're available towards the end of next week or June 10/11 to talk through as well.

**Comment by johnclary** [comment]
Donezo.
https://docs.google.com/presentation/d/1LbwRVB9tlfXLDqTKN4Ti3V5PzSWmMQzKhBKCCZH1700/edit
