### ISSUE TITLE
Moped User Testing and Design - CIF Fellowship Summer 2024

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#17715]
Olivia L. will join us for 10 weeks through our partnership with [Coding It Forward](https://www.codingitforward.com/) and will conduct Moped user testing and designs. Patrick has planned the following work:

- #### New map feature (4-8 weeks) 
   - User testing
      - Recruiting (1 week - 17 June) #17829
         - Recruit for different divisions and use cases
         - End of June 10th week
      - Testing (2 weeks) - end of June #17830
         - Plan
         - Script for moderated user testing
         - 3-4 staff
   - Synthesis - Summary of finding, themes, insights (1 week) #17831
   - Ideation - come up with solutions (1-2 weeks) #17833
      - Include users, builders, managers
   - Build prototypes (1-2 weeks)
  
- #### Details (Summary) page (2-4 weeks)
   - Discovery
  
- #### Activity/Notes combined (2-4 weeks)
   - Discovery
   - If we have time
   - Reference #6566, #7354

**Comment by patrickm02L** [comment]
This is done.
