### ISSUE TITLE
EzMaxMobile Support - verify LAT/LONG in mobile app

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17712]
## CTM Mike A. requested for DTS Maximo's support

_Due to data integrity, we will not be able to test every record in test, but the next time that we do a complete data move from production to test.  This will be clean up. I have a list of some assets that we were able to add lat/longs int test. Can you verify that the following assets are showing up in EZMax?_

**Safety Barriers**
- [x] 12053569 - INAC-DCM
- [x] 12053570 - INAC-DCM
- [x] 12053571

**Street Surface Assets**
- [x] 12064661
- [x] 12064662
- [x] 12064663
- [x] 12064664
- [x] 12064665
- [x] 12064666
- [x] 12064667
- [x] 12064668
- [x] 12064669
- [x] 12064670
- [x] 12064671
- [x] 12064672
- [x] 12064673

**Amenities**
- [x] 12071537- INAC-DCM
- [x] 401336457 - INAC-DCM
- [x] 401336458 - INAC-DCM
- [x] 401336459 - INAC-DCM
- [x] 401336460 - INAC-DCM
- [x] 401336461 - INAC-DCM

**Sidewalk Segments**
- [x] 12080812- INAC-DCM
- [x] 12090535 - INAC-DCM
- [x] 12132698
- [x] 12132813 - INAC-DCM
- [x] 12133121 - INAC-DCM

**Curb and gutter**
- [x] 401331983
- [x] 401331984 
- [x] 401331985
- [x] 401331986
- [x] 401331987
- [x] 401331988
- [x] 401331989
- [x] 401331990

**Special Structures**
- [x] 401336140
- [x] 401336141
- [x] 401336142
- [x] 401336143
- [x] 401336144

**Row Trees**
- [x] 401337124
- [x] 401337125
- [x] 401337131
- [x] 401337152
- [x] 401337155

**Bridges**
- [x] 401343296 - INAC-DCM
- [x] 401343297 - INAC-DCM
- [x] 401343298 - INAC-DCM
- [x] 401343299 - INAC-DCM
- [x] 401343300 - INAC-DCM

**Traffic Calming Device**
- [x] 401348243 - INAC-DCM
- [x] 401348244 - INAC-DCM
- [x] 401348245 - INAC-DCM
- [x] 401348246 - INAC-DCM
- [x] 401348247 - INAC-DCM
- [x] 401348248 - INAC-DCM
- [x] 401348249 - INAC-DCM
- [x] 401348250 - INAC-DCM

**Curb Ramps**
- [x] 401677551
- [x] 401677553

Thanks,
Mike

**Comment by rebekkabry** [comment]
In CTM queue for investigation/troubleshooting.
