### ISSUE TITLE
Remove auto-insertion of owner people record on ROW permits (RB) (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17726]
**Acceptance Criteria**

- The AC provided applies to RW, EX, DS and PSM folders 
- When a new record is created, system seems to be adding the Owner of the Property record to the folder automatically.
- This functionality needs to be removed for the folders mentioned above.

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed under **INC0424990**

**Comment by Nadin-Nader** [comment]
@rajeshlaunch this has been sent to DEV please UAT

**Comment by Nadin-Nader** [comment]
This was sent to the DevOps CM Team to be deployed to DEV under **SCTASK0453234** on Friday Sep 6th

**Comment by Nadin-Nader** [comment]
@rajeshlaunch this has been deployed to DEV. Please UAT

**Comment by Nadin-Nader** [comment]
@rajeshlaunch this has been sent to the DevOps CM Team to be deployed to TEST under **SCTASK0454030**

**Comment by Nadin-Nader** [comment]
@rajeshlaunch this is ready for your UAT in TEST

**Comment by rajeshlaunch** [comment]
@Nadin-Nader  this is tested and working fine in UAT. Please ask the users to validate the same.

**Comment by TracyLinder** [comment]
Pending UAT by ROW. FYI @KyleErich

**Comment by KyleErich** [comment]
@Nadin-Nader @rajeshlaunch UAT on Test approved, thanks!

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0463190**

**Comment by Nadin-Nader** [comment]
@rajeshlaunch @KyleErich this has been deployed to PROD

**Comment by KyleErich** [comment]
@rajeshlaunch @Nadin-Nader UAT on Prod approved, thanks!

**Comment by TracyLinder** [comment]
Closing
