### ISSUE TITLE
Update Admin Rights for Rebekka

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#17778]
Adry I am unable to add users in MAXIMO Production. Please update rights or advise on what steps I need to take to update on my end. Thank you. 

<img width="673" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2RaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--884987de0296cde7b7325ba8c748039a2905b521/image.png" alt="image.png" />

![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/de800280-03c6-4d67-b823-d524c1256784)

**Comment by adry-martinez** [comment]
@rebekkabry I just reconfigured your profile. Please log out, close browser, and log back in to check. If not, we'll have to follow up with CTM Maximo. Looking at the second screenshot, be sure to check the SITE field so that it displays SBO or else it won't capture SBO users.

**Comment by rebekkabry** [comment]
Resolved. Closing complete. User error 😃
