### ISSUE TITLE
[Enhancement] Update EOI Timeframe reflects cycles

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17774]
## Description
Update the timeframe component on the EOI form so that it defaults to a dropdown for cycles. Currently residents are choosing a specific day that residents are requesting. 

## Note
LS team would like to update the language under the start date as well
Potential lang
- Change Start Date to `Preferred start Date`
- Application are due Oct 4, staff will review and assign to start time
- Add validation to November 1st
- Update the warning to November 1st as well

![image (4)](https://github.com/cityofaustin/atd-data-tech/assets/5566727/a9529085-33e9-4a75-b081-432760d3f095)

**Comment by patrickm02L** [comment]
## 6/11/24 in sprint meeting
Matt provided the following language to be updated:
```
Category name:
Preferred Start Date
Applications are due October 4, 2024.
Earliest install will be November 1, 2024.
```

**Comment by KaroEngstrom** [comment]
![image](https://github.com/cityofaustin/atd-data-tech/assets/100615928/5ef80616-da0b-429e-8bb8-cbb1da61ef03)

**Comment by KaroEngstrom** [comment]
from Jonathan via Teams: 
"Hey please use this as the text for the under the Preferred Start Date "Applications are due October 4, 2024. The earliest install date will be approximately November 1, 2024."

**Comment by KaroEngstrom** [comment]
## Wed 6/12/24
- Update label to Preferred Start Date 
     - [x] EOI HS Timeframe 
     - [x] EOI PS Timeframe 
     - [x] New EOI HS Timeframe
     - [x] New EOI PS Timeframe 
- Update instructions to: Applications are due October 4, 2024. The earliest install date will be approximately November 1, 2024.
     - [x] EOI HS Timeframe 
     - [x] EOI PS Timeframe 
     - [x] New EOI HS Timeframe
     - [x] New EOI PS Timeframe
- [ ] Update validation on the Start Date field to November 1, 2024
