### ISSUE TITLE
Export & Import Mitigation Data for Web-map

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17775]
**Apps:**
- [x] Export all relevant mitigation records
- [x] Send export to Andrew. 

**Geo:**
- [x] Update map data
- [x] inform Kat

**Comment by andrewshensky** [comment]
The Mitigation Dashboard has been updated with the data that Chrispin was able to provide. All records with a valid Mitigation Feature ID have been mapped and are now represented in the dashboard.

https://austin.maps.arcgis.com/apps/dashboards/b89c344a9fd54e73a10d2b651c9c928b
