### ISSUE TITLE
[Feature] SSO for Reviewers

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17786]
## Description
Implement Single Sign On for the MSP Knack application.

Gitbook: https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzNSSXajDFpzOv2IhIv/knack/single-sign-on

## Notes
See #14188 as reference

**Comment by susannegov** [comment]
# 07/10
- Pages that need SSO
   - Cashier Login page
   - Reviewer Login page

**Comment by susannegov** [comment]
Submitted INC0409781 Created service ticket

**Comment by susannegov** [comment]
# 7/15
- Service ticket resolved. I have the metadata file

# 7/16
Added the new federated metadata but forgot to mention adding as user to console for modifying MS entra. Reopened ticket.

**Comment by susannegov** [comment]
@patrickm02L @dianamartin Does the https://atd.knack.com/mobility-services#home/ URL need a Sign Up button similar to the my account page? 
### Home 
![image](https://github.com/user-attachments/assets/b508cbe0-8fe6-46b6-aae1-7759be5384f0)
### My account 
![image](https://github.com/user-attachments/assets/cc6ffc46-ac62-4b0f-b85b-fb2de8d24583)

Also the MSP app currently has four User Roles: `Admin`, `Cashier`, `Customer` and `User`. Should `User` be removed and replaced with `Customer`, or is there a reason for a `User` role?

**Comment by dianamartin** [comment]
@susannegov I don't think we need it on the Home page, bc we're directing them to the "Portal" page and then the "Sign-In" page.

**Comment by patrickm02L** [comment]
## 7/24/24 - In Planning
- User and Customer would be able to do the same things as PLA
- Admin to be able to manage accounts

@susannegov feel free to update this

**Comment by patrickm02L** [comment]
## 7/29/24
@susannegov Added this to the agenda for 8/5/24

> Also the MSP app currently has four User Roles: Admin, Cashier, Customer and User. Should User be removed and replaced with Customer, or is there a reason for a User role?

**Comment by susannegov** [comment]
Created pull request
