### ISSUE TITLE
[Enhancement] Email notification

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17784]
## Description

The reviewers would need to receive emails notifying them when applications changed status or required their review/approval.

#### Email Triggers
- When an application is submitted and moves to a the following statuses:
   - Submitted - Require Action
      - When an applicant selects notarization on their own  
   - Pending Approval - Require Action
      - If a reviewer leaves a comment asking for more information. An email would go to the applicant informing them of this and next steps. 
      - When an applicant uploads a supplemental attachment or documentation in response to a reviewer comment/request. This becomes a completed action, the reviewer would be notified of the update, then they'll manually change status
   -  Pending Approval - Pending Payment 
   - Approved, Declined, Expired, Canceled
      - When approved - email would go to the applicant for payment and scheduling tests.
      - Potentially when an application expires or is cancelled, to close out the process via email.

## Notes
<img width="1394" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGR4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a8bea075a86a8f0395318b2c3b3b0faa9eaecac1/Screenshot%202024-06-18%20at%208.05.58%E2%80%AFAM.png" alt="Screenshot 2024-06-18 at 8.05.58 AM.png" />

**Comment by susannegov** [comment]
# To do
- [ ] Create 2 email notifications in the Review page
  - [ ] On-site - Payment and Notary Required
  - [ ] On my Own - Notary Required
- [ ] Create 1 email in the Cashier page
   - [ ] When is paid, cashier will manually send the email that it is paid and under review
-  [ ] Email notification of application is approved in reviewer page Appove form

**Comment by susannegov** [comment]
# 7/11
Send current email rules listed in Email Notifications word doc to Jacob and Paul to review

**Comment by patrickm02L** [comment]
## 8/13 
Courtney sent us and updated email messages for each trigger.
[Chauffeur Email Notifications-Culberson.docx](https://github.com/user-attachments/files/16604153/Chauffeur.Email.Notifications-Culberson.docx)

**Comment by susannegov** [comment]
# Updated Triggers 8/15
- [ ] Trigger: When the applicant selects “On Site” for notarize option
- [ ] When the applicant selects “On my own” for notarize option.
- [ ]  When the applicant selects “Submit” after “In Progress – Notary Required” has been completed.
- [ ] When the applicant selects “Submit” after “Submit - Require Action” has been completed
- [ ] When the cashier checks “Yes, they have paid the application fee” for the applicant in the cashier web page.
- [ ] When the PLA (Reviewer) check and submits for “Yes, please send email to applicant” for “Send Action Requested” form
- [ ] When the PLA (Reviewer) check and submits for “Yes, please send email to applicant” for “Add Reviewer Comment”
- [ ] When the PLA (Reviewer) clicks submit for the “Approve Application” form
