### ISSUE TITLE
6200 Active TKs in the DEPT_2400_TK_VW are missing in Knack 

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17793]
Active TKs in DEPT 6200 (that were moved from 2400) are not pulling into Knack applications.
- Searched 24ART01073

AMD Data Tracker Search Results
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/05a0fc1a-ea4b-4341-89cd-34a5e3ba36a8)

DEPT_2400_TK_VW Search Results
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/debd5385-0a84-4897-95ff-40cb9d352953)

The SQL view shows the active TK, but that TK is not available in Knack. Need to troubleshoot why that might be happening

**Comment by Charlie-Henry** [comment]
@ChristinaTremel I took a look at the code for this and we made some assumptions about the task orders data that I don't think hold true anymore. This [docstring](https://github.com/cityofaustin/atd-finance-data/blob/37d88f0877fcd97af33a33b2326dc05f265242af/s3_to_knack.py#L144-L161) explains better whats going on.

We're using that `TASK_ORDER_ID` field as the primary key and if there are duplicate TASK_ORDER_ID's we "coalesce" by just commas separating all of the BYR_FDU's into one text field. It looks 24ART01073 has different data all across all of the fields, not just BYR_FDU so we will need to rework this if we want it to behave differently. I hope this helps

**Comment by ChristinaTremel** [comment]
ohhh so is the issue that there are multiple rows of the same `Task_Order_ID` that have differing `BYR_FDUs`?

I think we use the same assumptions as long as we could add an additional factor of using that TASK_ORDER_ID field as the primary key and only coalescing the TKs where DEPT code is the same. Would that be a somewhat easy adjustment to make?

**Comment by Charlie-Henry** [comment]
Ah I see now they're from different departments. Uhh I think it would be fairly easy to do that but I'm a little concerned that it'll break something else. It makes me wonder how many TASK_ORDER_IDS are in multiple departments?

**Comment by ChristinaTremel** [comment]
It should only be between 2400 and 6200! When the departments merged in October, finance deactivated all of the TKs in DEPT 2400 and created these TKs again in 6200 (our new DEPT code). I confirmed this with Sharon and she said: 
> A TK can have 2 FDU's with different funds so yes.  Not sure about those FDU's having diff depts tho -meaning 1 with a 2507 FDU and one with a 6207 FDU? I can't say it will never happen since we are now merged but we don't have any right now!

Diana and I were chatting about this and were thinking for the two Knack apps that we know of that use this view (Data Tracker and the Finance and Purchasing app), we couldn't think of anything that it could potentially break. But before we make the change we could definitely export some of the objects using task orders to have back ups just in case.

**Comment by Charlie-Henry** [comment]
So we still want to be able to view both? I see they have different balances and stuff.

<img width="687" alt="Screenshot 2024-06-17 at 2 02 36 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/30810522/5f346b70-85e7-4580-8de7-5b5bb8dab60f">
<img width="704" alt="Screenshot 2024-06-17 at 2 02 29 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/30810522/235eb947-0d2a-415a-8f64-6de4e61c5506">

**Comment by ChristinaTremel** [comment]
We would want to view both! I showed Finance this information and they said it's normal for them to have different balances - When they transitioned the money to the Task Order under the new department code they only moved the remaining TK balance and then divisions continue to add funding to active task orders!

**Comment by dianamartin** [comment]
# 7/8/24
@ChristinaTremel cc @stephaniemoorer Do we know the status of this? Sharon emailed this passed weekend asking if it's in the system yet.

**Comment by ChristinaTremel** [comment]
- @dianamartin Charlie is going to be working on this issue in #18017! 🙏🏼

**Comment by ChristinaTremel** [comment]
This has been completed. Let finance know last week and will let AMD know during their sprint review today!
