### ISSUE TITLE
Evaluate Asset Panda

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#178]
Trial account login: http://login.assetpanda.com
Credentials in 1Password; expires 6/19. 

Trial account is set up with tool-tracking template. Can download app and try out from phone as well. 

Please record observations in the [comparison matrix](https://docs.google.com/spreadsheets/d/1r2l_KFgjygCCp1E4oaBa5lyK2QzkVcP5qCu2u85UwcY/edit#gid=2118741241) and compile questions for Eric in the comments below. 

### Resources
- API docs *Configuration > API Configuration*
- [Help documentation](https://support.finaleinventory.com/hc/en-us)
- Training support available during this time; submit a request from the _Help_ menu

**Comment by dianamartin** [comment]
- Tools: Couldn't sort table even though option was available, just wasn't changing. 
- UI looks nice and easy to navigate
- Have "Fleet" tab for management
- Looks basic, not as many options as the other systems

**Comment by amenity** [comment]
@dianamartin - thanks for your notes and info in the matrix. 🙏 
@johnclary - closing this out, but feel free to add any thoughts here.
