### ISSUE TITLE
[Enhancement] Create User Roles & limitations for Operations Specialist

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17808]
## Description

Add new user role for Operation Specialist. Limit access for Operations Specialist user types so that they're only able to see Service Requests. 

Do not allow specialists to see any fees or finance information.

**Comment by dianamartin** [comment]
# 6/12/24
- [x] Created a user role `Service Request Editor`
- [x] Made the "Service Request" page accessible to "Provider_Contacts" and "Service Request Editor"
- [x] Created trigger button to allow providers to set people up as "Service Request Editor"
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/9e124afb-b5fe-4f8f-8178-d308b504fc89)

Process to undo a SR Editor is to reach out to SMS team, they can do it in the Account Management module.

**Comment by patrickm02L** [comment]
## 8/30
Additionally [added a "Service Request Editor" button](https://github.com/cityofaustin/atd-data-tech/issues/17809#issuecomment-2321403641) so that staff could add personnel to the Provider Contacts table.
