### ISSUE TITLE
[Phone Purchase Support] EMS group at OCE division and ROW: 2 iPhone Setup

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#17803]
### ServiceNow Ticket Numbers
Scott said two users requested for mobile devices, one is from the Emergency Management Services (EMS) group at the Office of the City Engineer (OCE), and another is from Right of Way.
OCE:  REQ0188539
ROW: REQ0188512

Since it has been several years since new phones have been requested, I think it would be good to scope out how to handle it. I imagine it should be similar to tablets as it is an iPhone device, but just need to confirm.

**References:**
☁[AirWatch Management](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/airwatch-management)
🤖[Android Configuration](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/tablet-configuration)
🍎[iOS Configuration](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/ios-tablet-configuration)

**Select Issues:**
- [x] Purchasing Devices
- [x] Setting up a New Device
- [x] Setting up a New User
- [ ] Switching Device User
- [ ] Remove User & Wipe Device
- [ ] Create or Modify a Device Profile (such as passcode policy)
- [ ] Missing/Lost Device (alarm ping, lock, last location)
- [ ] Deactivate SIM card
- [x] SIM/Network/Hotspot/WiFi/GPS
- [x] Workspace One: Intelligent Hub app
- [ ] Launcher profile (such as Home Screen apps/shortcuts)
- [ ] App Catalog: New, Outdated, or Missing app or icon
- [ ] Unable to launch an app
- [ ] Unable to charge/turn on device
- [ ] Device Update/Version
- [ ] Retire a Device (outdated, bricked, no longer used)

**Device Details:**

| User | COA Tag | SN | IMEI | Phone | Brand, OS Version, & Device Type |
| --- | --- | --- | --- | --- | --- |
| FirstNameOnly | COA###### | ###### | ###### | ###-###-#### | Samsung Android 11.0 Tablet |
| FirstNameOnly | COA###### | ###### | ###### | ###-###-#### | Apple iPadOS 16 Tablet  |
| --- | --- | --- | --- | --- | --- |
| --- | --- | --- | --- | --- | --- |
| --- | --- | --- | --- | --- | --- |
| --- | --- | --- | --- | --- | --- |

**Confirmations:**
- [ ] User in AirWatch (in TPW group, not CTM)
- [ ] Device in AirWatch
- [ ] Device Labeled with COA Tag, SN, IMEI, & Phone #
- [ ] Device in DTS Inventory

**Comment by scottreedy** [comment]
@susannegov @ChrispinP @dianamartin 
I was told by Art Garcia, Air Watch Admin, that the wireless shop enrolls the devices in AirWatch upon arrival. If  you don't buy through the Wireless shop, you have to send Art the Serial Number of the phone or iPad and he will add to AirWatch. 
For the phones, he said they just login with their username and email address and should not have to create an apple id.

**Comment by scottreedy** [comment]
@susannegov @Matthew-M-TPW Didn't we buy these phones already? I know we bought one for the OCE office of emergency management manager.

**Comment by Matthew-M-TPW** [comment]
OCE manager received phone

**Comment by Matthew-M-TPW** [comment]
Both phones were deployed
