### ISSUE TITLE
Prototype Vehicle Reservation for PE

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#17816]
# 6/13/24
Synced with Patrick, Susanne on PEP Build

- Reference [Miro Board](https://miro.com/app/board/o9J_lS0SxME=/)

## Build Notes
- [x] Create object tables
- [x] Create field headings

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/964e5d05-eecb-4a55-843c-88f5bf4b4949)

## Account table
- [x] Add "Approved Driver" -Y/N to `accounts` object table

## Electric Form
- [x] Created Date - Start Time - DATE/TIME
- [x] Created By - "Inspected By"
- [x] Start Mileage - NUMBER
- [x] Type: Pre-trip/Post-trip? NEEDS CLARIFICATION - MULTICHOICE
>Create record & Edit?
>- Track AM Shift Start/End times?
>- Track PM Shift Start/End times?

## Inspection Fields - NEEDS CLARIFICATION
>Efficient? (Multiple choice - Checkboxes)
>- Data Accuracy? (Multiple choice - Radio OR Boolean - Y/N)
>- Do you need a notes section for corrections of issues?

## EXTERIOR INSPECTION
- [x] AUTO BODY REVIEW - MC/Y,N
- Walk around vehicle and inspect for any scratches or damages **Explain damages in detail on back of checklist sheet
- [x] TIRE REVIEW - MC/Y,N
- Check tire tread and make sure all tires are properly inflated

## INTERIOR INSPECTION
- [x] CHARGE LEVEL (ELECTRIC) - NUMBER

### LIGHT INSPECTION
- [x] Check all signal lights (Brakes, turn signals, headlights, safety lights)
- [x] Make sure horn works
- [x] Check and adjust windows, side mirrors, and windshield cleanliness and good visibility
- [x] Steering and accelerator are in good working condition
- [x] Check and listen for strange noises
- [ ] Check all gauges and warning lights on instrument panel
- [ ] Check interior damage in the vehicle (i.e. seat belts, safety equipment)
- [ ] Check for trash

### ESSENTIAL MATERIALS
- [ ] Make sure gas card (Multiple choice - Checkboxes)
- [ ] vehicle collision in proper location -  (Multiple choice - Checkboxes)
- [ ] First Aid Kit, blood borne pathogen kit, and fire extinguisher are in proper location and up to date on safety inspection. (Multiple choice - Checkboxes)
- [ ] Make sure there is one cone in back of vehicle (Multiple choice - Checkboxes)

### FLUID/TIRE/ENGINE CHECK (Multiple choice - Radio)
- [ ] BRAKE FLUID
  - Low
  - Mid
  - Full

- [ ] COOLANT
  - Low
  - Mid
  - Full

- [ ] TIRE PRESSURE CHECK
  - L - FRONT
  - R - FRONT
  - L - BACK
  - R - BACK

- [ ] CONDITION OF WIPER BLADES
  - POOR
  - FAIR
  - GOOD

- [ ] VEHICLE STATUS CHECK (electric only)
  - WARNING
  - NO WARNING

- [ ] LIST WARNING - PARAGRAPH

- [ ] CONCERNS - PARAGRAPH TEXT
- [ ] DRIVER SIGNATURE - NEEDS CLARIFICATION 
- [ ] LEAD SIGNATURE

**Comment by dianamartin** [comment]
# 6/13/2024
- Patrick and I synced with Shavyvonne
- Confirmed that Jasmine uses an ipad mini device
- Use case: need to assess before/after - daily damage tracking
- Vehicles are borrowed

**Comment by patrickm02L** [comment]
## 6/18/24 Review with PE
Feedback
- Drop down signatures/name of driver
- 6 mandatory images (back, front, left side, right side, interior, trunk)
- PE will send LP numbers to be added to app
- Leave `Current Driver` field visible in the Manage Vehicle tables
- Access should be limited to admin and dispatchers for now
- Create Vehicle Status/Vehicle Log
   - Include service types
   - If in an accident include which service center it's at: Hargrove, Service Center 5 
- Create ability to add Additional Vehicles (admin permission only)

**Comment by dianamartin** [comment]
# 6/18/2024
# Diana's Notes 

### Continue Build Out
- [ ] Ability to edit already submitted Vehicle Inspection
- [ ] Create same fields for "Post Trip"

### Modify 
- [ ] Modify `Fuel Level'  - Change from Number to Multiple Choice
- [ ] Leave Current Driver field visible in the Manage Vehicle tables
  - [ ] Make sure that inspection log rolls up to the Vehicle table

### Add New
- [x] Include field for service types (Gas, Electric, Hybrid, Bicycle)
- [ ] Acknowledgement: Drop down signatures/name of driver
- [ ] Mandatory Images: 6 images (back, front, left side, right side, interior, trunk)
- [ ] Create Vehicle Status/Vehicle Log
  - [ ] If in an accident include which service center it's at: Hargrove, Service Center 5
- [ ] Create Vehicle Notes
- [ ] Create ability to "Add Vehicles" (admin permission only) to "Manage Vehicle" page

## Action Items
- [ ] PE (Ramerio and Jasmine) will send LP numbers to be imported into app

**Comment by dianamartin** [comment]
# 6/24/24
- [x] Added `Fuel Level` to form
- [x] Created/Added `PSI Level` to form
- [ ] Created/Added `Lead Signature PM` to form
- [x] Added Display Rules for Vehicle Type to their Electric, Fuel, PSI Levels

**Comment by dianamartin** [comment]
# 6/25/24
- [x] Added a copy of "Vehicle Checkout Inspections" to "View Fleet Vehicle Details" page
- [x] Update the Miro board to figure out best process to do Pre-Trip and Post-Trip
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/85c2b443-b9eb-49f7-881a-ac96d1b26356)

**Comment by dianamartin** [comment]
# 6/27/2024
On 6/26, worked on pivoting the way we had the New Vehicle Inspection form configured. We discussed having all checkouts, AM and PM, no matter which group Enforcement, OSE or SMO checkouts to have their own individual checkout. 

## `vehicle-checkout-inspections` page
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b7e95ea4-33e1-4a40-b646-d1d60f7f9d27)

## Vehicle Details page
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/8f8a0b5b-e452-4daa-b8f7-9978fc50f601)

##  Add Vehicle Inspection form (New version)
- [x] Changed Fluid - Tire - Engine Check fields (from radio buttons to checkboxes)
  - [ ] Second iteration: changed to a "Fluid Tire Engine Verification" (selection box) and added the required checklist to the field as part of an acknowledgement that it was checked.
- [x] Changed Exterior and Interior checklists (from checkboxes to radio buttons). To focus the user on the most important parts of the inspection. From our above notes.
- [x] Added Vehicle Photos section 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/e43b799d-fd03-462f-8e23-551ffe1174df)

## Vehicle Inspection Details
- [x] Configured the details page to account for all the new field types and photos
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/b46adfc1-2a44-40c7-a928-807d91578ca8)

**Comment by dianamartin** [comment]
# 6/27/24
## Ability to compare Pre-trip and Post-trip
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/219bf663-e877-42f5-a713-8fc21000681d)

## Example of when there is an issue during inspection
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/3ab7b935-e52a-498f-bf5b-c11e0e8f91c8)
