### ISSUE TITLE
Prepare batch import of fleet_vehicles

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#17817]
Using the existing fleet vehicle check list provided by Jasmine, create sheet ready for importing fleet_vehicles
PDF of fleet vehicle list provided by jasmine - [FS.pdf](https://github.com/user-attachments/files/15823962/FS.pdf)

Here is AMD's fleet vehicle list (cleaned up without PII/license plate info) that this is based on
[fleet_vehicles_clean.csv](https://github.com/user-attachments/files/15824608/fleet_vehicles_clean.csv)

**Comment by susannegov** [comment]
Here is the link to the [Google Sheet](https://docs.google.com/spreadsheets/d/10OdOSaa3D6rBmOqbLSnDDuirhSHwDzuyi9MCCtQ3UJk/edit?usp=sharing) which lives in the Parking Enterprise Portal folder.

## Some notes
- The fields are left blank for now. I'm not sure if these attributes need to be tracker per-se, but they can be renamed as needed
   - Vehicle Year 
   - In Service Date 
   - License Plate 
   - Current Driver 
   - Location 
     - Called Location in AMD but PEP calls it Beats
     - List of Beats provided by Jasmine in a [Beats.pdf](https://github.com/user-attachments/files/15825145/Beats.pdf)

### Location multichoice
```
Beat 1
Mueller
Beat 2 North
New Meter and 2 South
RPP/ Scottish Woods
Scooter Team
Beat 3 and 4
Beat 5 East and 5 West
Booting
Beat 6 North and 6 South
Commercial
Beat 7 South
Beat 7 North
CSR/ Bike Lane
SOCO Team
```

**Comment by susannegov** [comment]
@dianamartin See above. The import list cleaned up. Can modify the sheet names as needed as you build.

**Comment by dianamartin** [comment]
# 6/13/24
- [x] Imported `fleet_vehicle` list into PEP application - `23 records`
- [x] Manually populated Vehicle Year, the Vehicle ID's first two digits is the last two digit year of the vehicle.
