### ISSUE TITLE
Updated incorrect pricing on a DIJ contractor ticket

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17820]
Cole contacted Diana and I about an issue he was seeing: 
> I have an invoice/materials/Knack question for you. For reference ID 1758, the materials log for Bid Item # 871S-E-4-W is off by one cent... not sure how that happened, but I can't balance the invoice DIJ provided until that entry is fixed. Here's a screenshot of the issue but happy to provide whatever documentation you might need. 
Also, wasn't sure if this was a DTS question or not... so please let me know if I should direct this question elsewhere! 
![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/185a8977-6e4a-43bf-81d7-802231949b24)

- I reviewed this with Diana and we figured out that DIJ was using the new pricing after the increase in #16649

   - This was the pricing and details reflected before adjusting the bid item to the original contract
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/e80e7823-ee9d-4bd8-af20-1b5006c203db)

   - This was the pricing and details reflected after adjusting the bid item to the original contract:
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/e8c2af68-b555-42fa-8f80-5961d4921813)

**Comment by ChristinaTremel** [comment]
Cole requested the same updates for the issue that TRP had: 
- Ref ID `2122`, Bid Item 871S-A-24-W is $6.47 (should be $6.00)
   - This was the pricing and details reflected before adjusting the bid item to the original contract
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/f88fa526-f3a2-4321-9bc0-6c83ee30415c)
   - This was the pricing and details reflected after adjusting the bid item to the original contract:
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/c5b1c337-97af-46fa-9e13-55a6b8a13664)
   - Unit cost has been updated to $6.00 ✅
- Ref ID `2110`, Bid Item 874S-A-12 is $0.75 (should be $0.70)
   - This was the pricing and details reflected before adjusting the bid item to the original contract
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/9978fa37-64a4-4470-8f37-12fc096097c2)
   - This was the pricing and details reflected after adjusting the bid item to the original contract:
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/e447319b-76e1-4f72-8a5a-0e3ec4b483f7)
   - Unit cost has been updated to $0.70 ✅
- Ref ID `2231`, Bid Item 874S-A-24 is $1.35 (should be $1.25)
   - This was the pricing and details reflected before adjusting the bid item to the original contract
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/4cc609d6-e518-4499-8fb1-2e95a061711b)
   - This was the pricing and details reflected after adjusting the bid item to the original contract:
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/8822fd29-ab36-42a8-a6b8-fdb89021b874)
   - Unit cost has been updated to $1.25 ✅

Let Cole know that these have been fixed!

**Comment by dianamartin** [comment]
# 7/1/24
Closing, this has been completed.
