### ISSUE TITLE
Recruiting for Map User Testing

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17829]
## Description

Now that the internal Moped map has been launched we would like to do user testing with different divisions and staff to test for various use case. 

#### Recruiting will entail:
- [x] Make a survey for volunteers
- [x] Vet user testers
- [x] Create acceptance emails

## Desired Outcome
Outreach materials should comply with City of Austin's standards for outreach material towards residents. Materials should include a screener to understand which stakeholder group the participant is in, and an email that 
- 1 - introduces the purpose of the usability test
- 2 - explains compensation
- 3 - includes a scheduling link. 

## Notes
- This [doc](https://docs.google.com/document/d/1KU_gzu0R0yWgpbvwYEnpOnlhKtp0W8K00NzgQoLWU08/edit) has a lot of the materials you'll need
- Refer to mobility testing epic from 2023 #12295
- Create recruiting materials #12665

**Comment by patrickm02L** [comment]
## 6/14/24
When you're ready to review please move to Review/QA, and tag Mike D, and me.

**Comment by patrickm02L** [comment]
## 6/24/24 - Acceptance Email

```
Hello ___, 

Thank you for your interest in volunteering to do Moped User Testing. We would like to invite you to a 30 minute meeting to test at the following options:

- Option 1
- Option 2

 Please let us know which time work best for you and we'll send you a calendar invite. 
 
 Have a great one!
```

**Comment by olivialuk** [comment]
## 6/24/24

@patrickm02L @mddilley here is a new draft of the [survey form](https://docs.google.com/forms/d/e/1FAIpQLSezcgjtu7aYwpdyvEWZv_x6yJIMLaYfT4GmM_t6Kw3gppUBBQ/viewform?usp=sf_link) to recruit user testers for Moped. Let me know if there needs to be any other revisions. Thanks!

**Comment by mddilley** [comment]
@olivialuk Thanks for your work on this! I read through the survey, and it looks so great to me. 🙌 ✨

I have one comment about the role question on the second page. Team members on projects can play different roles from project to project and also can have multiple roles on a single project so it might make sense to change it to roles (plural). I defer to y'all though! It is a super tiny detail.

**Comment by olivialuk** [comment]
##6/25/24

@patrickm02L @mddilley I made the two revisions you guys mentioned (adding times to the AM/PM question + changing the role question to "roles," plural). Here's the [revised survey](https://docs.google.com/forms/d/e/1FAIpQLSezcgjtu7aYwpdyvEWZv_x6yJIMLaYfT4GmM_t6Kw3gppUBBQ/viewform?usp=sf_link) if you'd like to look it over again.

**Comment by mddilley** [comment]
Thanks @olivialuk! Could you add a question mark to the very end of the last question? This is all good to go - thanks! 🚀

**Comment by patrickm02L** [comment]
## 6/27/24
Mike sent out a recruiting email to all the Moped Users (129) that were not included in the MUG group. He'll send out a reminder to the MUG folks on Monday, July 1.
