### ISSUE TITLE
Synthesis of Moped map usability testing

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17831]
## Description
Now that Moped User Testing has been completed, the information gained will be synthesized and articulated into actionable insights. These insights will guide the ideation, and eventual prototyping of design improvements for Moped. 

Moped User Test [Recordings](https://drive.google.com/drive/folders/1Ua-wUmwedAsHOHkLOm95w_kdcB9E2eYX?usp=drive_link) + [Live Notes](https://drive.google.com/drive/folders/1OAu23XaJ8pvGEyMe5Ak1uOHqyZYj_A4E)

## Acceptance Criteria
- [ ] Pull a summary of key testing moments into a [miroboard](https://miro.com/app/board/uXjVK7u2RfY=/) and use affinity diagramming to identify key themes
- [ ] Create an area in the miroboard for takeaways or create a google doc for final takeaways 
- [ ] Review with Patrick (and maybe Mike) what I've learned, and begin discussing next steps for group ideation session or prototyping

## Notes

**Comment by olivialuk** [comment]
Complete Synthesis of Moped Map Usability Testing and presented insights at 7/23 MUG meeting using [this slide deck](https://docs.google.com/presentation/d/1CeX5zoVSWSlWZOtWDPL5G01FXrlAof_cxBbuS61e1ac/edit#slide=id.p). Using Synthesis and Insights to Inform Moped Map Prototyping in Issue #18397.
