### ISSUE TITLE
[Research] Moped Map Think-out-louds

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17830]
## Description

We want to understand how Moped users are using the new project map. In order to get insights we'll need to do testing. 

## Acceptance Criteria

- [x] Create Test Plan
- [x] Set up meetings with users

**Comment by olivialuk** [comment]
## 6/25/24

@patrickm02L & I went over the [test plan](https://docs.google.com/document/d/1AzNfoKs4nksQ_fVIwEFAn6odg6SDr-ujM_Lc92qxhtw/edit) today

**Comment by olivialuk** [comment]
Tested with 9 users over the course of 2 weeks. Gathered insights from users across a spectrum of novice to expert, and users across 4 different TPW divisions. Testing Documentation (Recordings + Live Notes) exists in this [drive folder](https://drive.google.com/drive/folders/1OAu23XaJ8pvGEyMe5Ak1uOHqyZYj_A4E). I will continue on to synthesis in #17831.
