### ISSUE TITLE
Maximo Support - SBO CSR-WO Pending Sealcoat Review (Flex Field 2)

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17843]
Per Proj. Coord. Andre E. 
- [x] Remove all 5CLOSED and 4QACOMP from this portlet.
- [x] Provide rights to Andre E. and John F. to modify 5CLOSED (similar to Reza)

**Comment by rebekkabry** [comment]
Syncing with Maximo team. Scoping in progress.

**Comment by ReneVarg25** [comment]
### 7/17/24
Acknowledged all WOs in 5CLOSED or 4QACOMP status.
Provided users access to the SBOIMG start center which will allow them edit work history and modify 5CLOSED WOs.
