### ISSUE TITLE
Update documentation related to on-prem servers & the software on them

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#17841]
* First order of business is to identify all the pages which we will want to update with new information
* From that list, we'll be able to fill out the rest of this task

https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/on-prem-servers/overview
https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/dts-server-list

- how to get on the server where Airflow is running
- how to pull changes (do we need to update repo docs?)
- GitHub auth
- what is the updated server name? what is the updated Airflow path?
- where are legacy scripts?
- check for links to existing pages to make sure that we don't leave broken links when removing either of these GitBook pages

**Comment by mddilley** [comment]
See also https://github.com/cityofaustin/atd-data-tech/issues/17840

**Comment by frankhereford** [comment]
This documentation has been written. We're reviewing it, and a link to the current version, as well as our discussion, can be found here:

https://austininnovation.slack.com/archives/CHZE6BC6L/p1720807528347389

**Comment by frankhereford** [comment]
These changes have been posted to GitBook, reviewed, and merged.

**Comment by frankhereford** [comment]
Hi John -- those links are to pages that have been removed and replaced with one you can find in the side bar of the dev section, or you can jump right to it here: https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/servers/dts-int-data-p01-on-prem-server.

Chia had put those links in there which was very helpful for context about what she wanted when I started, but I didn't think about them as I went into review because they were "gone" in my mind. Thank you!
