### ISSUE TITLE
[Maximo] Offboarding Adriana M. from Maximo

### ISSUE THREAD

**Issue by adry-martinez** [cityofaustin/atd-data-tech#17842]
## To Deactivate ## 
- [x] Review and update Scheduled Reports from this User @ReneVarg25 
- [ ] Change Owner/Lead of those work orders to another person @rebekkabry 
- [x] click on the **Status** icon and update the profile to **INACTIVE**
- [x] Remove the profile/user from the TPW Maximo User mailing list.
- [ ] Remove user from Security Groups @rebekkabry
- [x] Rescheduled Recurring meetings with stakeholders @rebekkabry 
    - added GIS, Monthly Maximo Refresher, etc.

**Comment by ReneVarg25** [comment]
### 7/24/24
Updated task list with completing 3 of them. Need confirmation on change owner/lead of WOs and removal of Security Groups.

**Comment by dianamartin** [comment]
# 9/30/24
@ReneVarg25 Can we ensure that this has been completed so we can close this?

**Comment by ReneVarg25** [comment]
### 10/1/24
Remaining tasks have been completed. Closing issue.
