### ISSUE TITLE
Contact CTM about getting permission to issue new access tokens for new 1PW connect server

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#17877]
Under the old system, I was able to issue tokens for all of our devs individually. This is an important thing to be able to do, because it allows for a users token - if leaked - to be revoked without breaking all of our ETLs and other users' local airflow setups.

Right now, we're sharing one, and that's not ideal. 

This issue is to do whatever research is needed to be able to reach out to ISO and make the case that we need that permission, or as a second-best alternative solution, get them to issue me 20 of them which I can dole out to team members as needed.

**Comment by frankhereford** [comment]
@dianamartin Hi Diana - I wanted to CC you on this so you're aware that I'll be reaching out to ISO at some point this sprint -- thanks!

**Comment by johnclary** [comment]
@frankhereford were you able to make any progress with CTM on this?

**Comment by frankhereford** [comment]
The ball is in their court, and i have not heard back. I can bug them some more.
