### ISSUE TITLE
Update signal engineering areas GIS polygons

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17878]
Brian G called this morning letting me know that there are changes needed for the Signal Engineering areas and corridor names. We took a look at his spreadsheets and the request includes the following changes needed to the signal engineering areas:

- The signal engineering areas in Data Tracker are populated by the [TRANSPORTATION_signal_engineer_areas](https://austin.maps.arcgis.com/home/item.html?id=a5e9ead2ee7d49cca9bd7d64747730d2) GIS layer.
- We will need the geo team to update the polygons in this layer as requested on the [Traffic_Signals_and_Pedestrian_Signals_20240614.xlsx](https://github.com/user-attachments/files/15874454/Traffic_Signals_and_Pedestrian_Signals_20240614.xlsx) spreadsheet and these should automatically update in Data Tracker once we make this change
- Let Andrew know about the request and he's planning on scoping it out to see what they may be able to do on their end. Once they make proposed updates, we can schedule a sync with Brian to confirm the details.

**Comment by andrewshensky** [comment]
This data has now been updated and pushed to both maint and DM. A service request has been submitted to CTM to push updated DM data to AGOL.
https://austin.maps.arcgis.com/home/item.html?id=a5e9ead2ee7d49cca9bd7d64747730d2
