### ISSUE TITLE
Create temp passwords for UAT test environment accounts

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17884]
- [x] Create temporary password for the existing user accounts. 
- [x] Remove big SSO button from test landing page

**Comment by ChrispinP** [comment]
Reset the passwords for all Knack Admins/PMs, they will need to be individually set. Removed inactive accounts. Set the test password for all ROW Staff accounts to: 

Disabled SSO code and disabled SSO from login pages.

Complete, ready to review
