### ISSUE TITLE
Set up proposed process to write from Maint to AGOL

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17900]
## GIS Request
Set up proposed process to write from Maint to AGOL and bring in the work dates as a first step for the proposed changes we would like to make to the Markings assets

---

#### Proposed Changes
- Create a parallel process to CTM and create our own services to push the markings assets and dates related tables to AGOL. 
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/741cc56f-7ed4-483a-a333-183935b04492)

**Comment by andrewshensky** [comment]
I have set up two FME processes, one to push markings data from maint to AGOL with work date tables included and the other to populate the last work date field in the geometry layers based on the work date tables published to AGOL in the first process. These processes still need to be configured in FME Server but the processes run successfully locally and the data in AGOL for each service can be viewed through the links below:

Markings Short Line
https://austin.maps.arcgis.com/home/item.html?id=bb0231e8506342da84b6c906a42b276a
Markings Specialty Line
https://austin.maps.arcgis.com/home/item.html?id=1742b4acec604f8eb587d303f5c81a31
Markings Specialty Point
https://austin.maps.arcgis.com/home/item.html?id=31d395c7aeec426bbbd223484569ab14

**Comment by ChristinaTremel** [comment]
Will review the dataset more and have Jordan do some reporting to ensure it's working for him, but this is complete!

**Comment by ChristinaTremel** [comment]
Closing this out because this FME process is set up and running! There's a new issue to track requesting ownership from CTM.
