### ISSUE TITLE
SIF - Six new folder Infos - (LP) (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17901]
### Create 6 new folder infos for the SIF folder

- All new infos belong to info group "SIF Financials"
- The sequence/order should be in the same order listed below

1. **"ROW Dedication Amount (sf)"**
- Numerical 
- Required

2. **"ROW Dedication Unit Value ($/sf)"**
- Currency 
- Required

3. **"ROW Dedication Value Calculated"**
- Currency
- System generated calculation (formula = (ROW Dedication Amount (sf)) * (ROW Dedication Unit Value ($/sf)))

4. **"Easement Dedication Amount (sf)"**
- Numerical 
- Required

5. **"Easement Dedication Unit Value ($/sf)"**
- Currency 
- Required

6. **"Easement Dedication Value Calculated"**
- Currency
- System generated calculation (formula = (Easement Dedication Amount (sf)) * (Easement Dedication Unit Value ($/sf))

**Comment by TracyLinder** [comment]
Priority - need this by July 19th.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created request for Dev deployment, SCTASK0436795

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Dev , Verified and Created request for Test deployment, SCTASK0437816

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Found a bug on test , done  fix and requested for Dev and Test promotion. SCTASK0438189

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes are deployed to Test , ready for UAT

**Comment by TracyLinder** [comment]
I let stakeholders know this is ready for testing.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT  Approved for PROD by Kaylie C.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created Prod deployment request , SCTASK0451854

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Prod , Ready for UAT

**Comment by TracyLinder** [comment]
This is stable.
