### ISSUE TITLE
IT Support: Maximo is giving error message "Cookies are blocked"

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#17915]
ST. ELMO

## Device & User Information (first name and last initial, no last names)
Tyler F  
## What's the problem?
The entire forestry team has been having issues with the EZmaxmobile app on the ipad. 

Before their process was to restart the device, but recently that did not work and I  (Matt) Cleared the app data and he was able to get in.

**Comment by Matthew-M-TPW** [comment]
This issue is occurring with only the app

**Comment by ReneVarg25** [comment]
### 7/2/24
Reached out to lisa killander for more information regarding issues

**Comment by ReneVarg25** [comment]
### 7/5/2024
Lisa confirmed that outside of picture uploads, that EZMax is not really used. Did not mention issues with cookies.
