### ISSUE TITLE
Update funding_source_name field to include source and program

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#17921]
In the `component_arcgis_online_view` DB view, we have a column named `funding_source_name` that is a comma-separated list of `moped_proj_funding` records connected to a component's project. It is referenced from the `project_list_view` database view. The source name is obtained from a join to `moped_fund_sources`. ATSD has requested that we also add the funding program to the comma-separated list which would require a join to `moped_fund_programs`. This would be formatted as `<funding source name> - <funding program name>` and have only unique combinations of the source names and program names.

Since the editor app list and advanced filters rely on the existing `funding_source_name`, we should add an additional column in the `project_list_view` to reference in the ArcGIS database view.

- [ ] Add `funding_sources` to the CTE that makes `funding_source_name`
- [ ] Make this new column to be a comma-separated list like `<funding source name> - <funding program name>, <funding source name> - <funding program name>`
- [ ] Make sure this list does not contain duplicate combinations of source name and program name

Note: `funding_sources` has already been added to the AGOL dataset so it is ready to receive this new column name. See https://github.com/cityofaustin/atd-data-tech/issues/17906#issuecomment-2182996294

**Comment by frankhereford** [comment]
As I work this, first I am going to unravel the complexity to where I can clearly show @mddilley the proposed before and after state of these columns and then with his approval, move forward and execute the plan.

**Comment by mddilley** [comment]
Saw I missed an estimate when assigning so I added a 3 for completeness sake. Frank, feel free to adjust. I know this was a while back but it feels like when the team was on our 3 spree 🚀
