### ISSUE TITLE
Embed CIP Finance Bond Dashboard in Sharepoint

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#17939]
Looks like @KaroEngstrom and @dianamartin are admins in the finance [sharepoint](https://cityofaustin.sharepoint.com/sites/tpwFinance). Sharon is asking if we could embed the new [bond spending power BI report](https://app.powerbigov.us/links/SwCvIIdzB-?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare) in it.

@susannegov has said she's done this before so she can help if needed.

**Comment by dianamartin** [comment]
@Charlie-Henry you can have @susannegov work with me and Karo to do this if she needs access to their SharePoint site.

**Comment by Charlie-Henry** [comment]
Do I need to ask Sharon to add her as a member @dianamartin?

**Comment by Charlie-Henry** [comment]
However y'all want to do it. I think all you need is the link to the report?

https://youtu.be/NC3pospVrgU?t=94

**Comment by KaroEngstrom** [comment]
It needs to be [an embed link](https://learn.microsoft.com/en-us/power-apps/maker/canvas-apps/sharepoint-scenario-embed-report), and then we'll be all set to put it in easily.

**Comment by KaroEngstrom** [comment]
## Mon 6/24/24 
- checking with Sharon via Teams on where they'd like to place this

**Comment by KaroEngstrom** [comment]
## Mon 6/24/24
Sharon responded: Perfect, thanks so much we will let you know!

**Comment by dianamartin** [comment]
# 7/1/24
I followed up with the stakeholder
>Hi Sharon, I'm following up on the CIP Finance Bond Dashboard embed in the Finance SharePoint. Have you determined where you'd like this dashboard to live on the site?

**Comment by KaroEngstrom** [comment]
## Tue 8/20/24 
- checked in with Sharon on Teams to see if she needed anything else
- her response: "I like what you have now - where it says Bond Spend Dashboard - PowerBI and when you click on it it opens our Power BI so just delete the Sharepoint one"
- deleted the link to the SharePoint embedded dashboard and retained their direct link to the Power BI dashboard from the [CIP Finance Dashboard folder here](https://cityofaustin.sharepoint.com/sites/tpwFinance/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=FueLnh&FolderCTID=0x012000BE9C94D6DC286E47A8D666F5B8E59CFE&id=%2Fsites%2FtpwFinance%2FShared%20Documents%2FCIP%20Finance%2FCIP%20Finance%20Dashboard&viewid=fbb45346%2Dc89a%2D4dfa%2Db843%2D06ae1ea534ea)
