### ISSUE TITLE
Maximo User Process Discovery - Reporting

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#17945]
## Objective 
The Data & Technology Services Division is initiating a series of meetings to learn more about Maximo user experiences and processes in TPW. In this meeting we'll be asking questions about how individual teams use Maximo and how it fits into their work processes.

## Goals:  
- Maximo system performance and functionality 
- User experience and interface experiences 
- Current processes within and related to Maximo 
- User feedback and improvement  
- Future roadmap and upgrades 

### User experience and interface experiences 
- Explain your process on how you use Maximo? 

### PROCESS - Planning
- Who plans the work? How do you get work to do? 
- How is work scheduled and issued out 
 
### PROCESS - Implementation
- How is work scheduled and issued out?
- Who is executing the implementation? 
 

### PROCESS - Field Work
- Who is executing the work - implementation? 
- Who is reporting on the work and what are they tracking? 

#### Maximo system performance and functionality 
- How long is it taking to do a Maximo work order in the field? 

### PROCESS - Review & Reporting
- What is your final review, QC process? 
- What reporting do you care about? How are you pulling that information out? 
- What are you reporting? 

### User feedback and improvement  
- What challenges are you having with Maximo? 

### Future roadmap and upgrades 
- What would you like your work order management system to do that you’re not getting right now? What’s missing? 

### Points of Contacts 

------
- [ ] Schedule meeting - 6/21/24
- [ ] Meet and take notes
- [ ] Process notes on Miro [Maximo Assessment Plan](https://miro.com/app/board/uXjVN7sxj9I=/)

**Comment by dianamartin** [comment]
# 6/21/24
[SBO Performance Report 2024.05.30.pdf](https://github.com/user-attachments/files/15928713/SBO.Performance.Report.2024.05.30.pdf)

Participants: Dave A. 

- Group he leads Operations Consulting
- Handle the monthly performance report
- continuation of a performance report with TPW Stat
  - separate measures
  - discarded some, adding to them as they go along
  - AD, DMs and SI's

## Goals
- Comprehensive Review of how divisions are doing
- Give everyone in SBO a 
- DMs, SIs, Superintendents present and opening up to supervisors, some project coordinators, some supervisors (most out in the field)

- It's a communication tool, continue to refine it
- Adding/Deleting measures
- End product, in PDF (26 pages)
  - it's as long as it needs to be
- building from a series of Excel workbooks 
- eventually, out of Excel workbooks, into PowerBI dashboards (long term)

## Current Process
- Building them out in Excel (hates it!)
- First page is "Service Plan Completion - Overlay"
  - Overlay and Districts are contributing to overlay construction
  - Pavement Ops - Overlay
- Proposed Number - comes from OCE, Ron K. 
- Comes from Maximo and also collecting by hand
- Started to track "Non-productive" days
  - bad weather days, that overlay can't work on Service Plan
  - Day by day, week by week basis
- Budget information, out of eCombs 
  - early on budget stuff
  - will start tracking OT, in the near future
  - when getting closer to FY25/26
- Personnel costs are their biggest expense
- Commodities don't impact as much as you think
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/71ee0c4e-48b9-4666-bae6-bc494b03b2eb)
 
- Still need to work on documenting these much better
- Does have a "Data Source" for the charts (ex. Maximo Report "Lane Miles Report")

Finance posts eCombs (10th of the month)
- Pull monthly expenses

## Report Building
30 minutes - just for Overlay
26 pages - Takes a couple of days
- undisturbed 12 hours, estimated

### Simplest Report
- Overlay Report & Numbers

### Complex Report
- Other side of Pavement - Thin surface treatments
- Seal Coat, Fog Seal (get from running reports)
  - by Work Orders
  - sometimes by Week
- Crack Seal is pretty easy

Looking at Prep
- "Seal Coat Prep Progress"
- oil coat emulsion, drop rock to protect the emulsion
- seals the asphalt (extends pavement life 6-10 years)
  - trying to seal water out of it
- Get a lot of CAFs
- After 2 years it gets better

#### Prep
- Before they can do two things: Crack Seal
  - Crack Seal: inject rubber substance into big cracks into the street, use squeegee to level out, "sealing the cracks"
    - Cracks are starting to break up. Cut out broken parts, fresh asphalt, seal it - "Level Ups"
  - Sweep, once or twice after it's had a chance to cure
  - Run independently or separately
- Within Maximo, how to track all of this
- Parent Work Order for street to be seal coated
  - Child: Crack seal
  - Child: Level-up
  - Child: Sweep
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/ce4ff5f6-1cf9-4202-a64c-819dee5db251)

Whole inspection piece, working on. Almost have enough personnel to do that. FY25, didn't get new FTEs for inspectors

#### Next Year
- will break up this chart 
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/0740e6b7-f162-47e4-a31b-5b49432536eb)

#### Actual Maximo Process for Seal Coat Chart 
- In Maximo
- Goes to "Work Order Tracking"
  - Work Order: `SP24` - for "Service Plan 24"
  - Classification: `SEALCOAT_WORK` work (one word)
  - Description: `rock` (keyword)
  - ~1363 records (download the Excel export)
  - Go to pre-existing workbooks
  -

**Comment by ChristinaTremel** [comment]
## Reporting responsibilities - what are you reporting
- Operations Consulting is the group he leads

### Manages the SBO Performance Report - monthly report that started with reporting on TPW stat and has been expanded
- Goal is to give Reiner an overview of how the teams are doing
- Second goal is to give everyone in SBO an idea of how they are doing (Division Managers, Project Coordinators, and Superintendents, some Supervisors)
- There are things in Maximo that make it a little challenging
- He builds the report out of a series of excel workbooks. Longterm goal is to get this out of excel and into PowerBI.
- Updating SBO Performance Report takes about 12 hours undisturbed / several days with meetings

### Example: Overlay Service Plan Completion Report
- First tab is what’s exported to PDF for the report
- Overlay and Districts contribute to overlay construction
- Expected Production Curve - comes from Ron Koehn’s service plan in excel
- Maximo:
   - Overlay lane miles
- Not Maximo:
   - Non-Productive Days: manually collected in excel
   - Budget information: pulled from eCombs
- Lane Miles Constructed: table goes back to April 2023
      - Data is from Maximo Report: SBO Lane Miles Progress Report and SBO Overlay Lane Miles Progress Report
- Non Productive Days: enter days into appropriate columns
- Budget: 10th of the Month, Finance posts monthly eCombs and he pulls the monthly expenses
- Overlay is considered one of the easy groups to run reports on
- Timeline to update the workgroup: For overlay takes about 30 minutes to update

### Example: Fog Seal and Sealcoat Service Plan Completion Report
- Prep is being looked at and reported on
- Seal Coat Prep Progress (Work Orders Completed) graph is the most complex to run
- Before Seal Coat they have to do 2 things:
   - Crack seal which is injecting rubber into cracks in street
   - Level up
   - Sweep immediately before the crack seal and once or twice after the crack seal, before sealcoat
   - Within Maximo, they have to figure out how to track all of this. They have a parent work order that’s going to be seal coated and 3 child work orders (crack seal, level up, sweeping). Total of 4 work orders for every street segment to be seal coated
   ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/9817a26c-9f1a-40d4-879b-79d58602f4a8)
   - This graph is the first attempt to track this
- Pulling this is directly from Maximo
   - Go to work order tracking
      - Work Order: SP24
      - Description: rock
      - Classification: sealcoat_work
   - Results are approximately 1300 work orders
   - Download entire report
   - Columns in green are expressions copied into every workbook
       - parent_WO: pull the work order ID and take out the subgroups added to the end (CS, LU, SW)
       - child_type: Pull from work order ID using the last 2 letters to know what kind of work order it is
    - Then created a pivot table that has work order ID, Crack seal (1,0), Level Up (1,0), Sweeping (1,0), Grand Total and calculates prep status using that
      ![image](https://github.com/cityofaustin/atd-data-tech/assets/61209591/7c000786-2df6-4d35-bde7-17beec9a8528)
   - Then creates another pivot table of all the prep statuses and the counts

## User feedback and improvement

### Pain Points
- Sometimes the data quality is bad
   - Data quality of the actuals table is not great. When they rolled out Maximo they didn’t think about setting standards and communicating when to start the clock.
   - Materials is generally pretty good
   - Labor is not great
   - UER is a great group for reporting - they were audited by the City Auditor about the backlog and they had to clean it up
      - Reiner moved over from OPM to Utilities and Structures to help with the backlog and with that work group
      - They had Clay and Eli and worked with Supervisors to get Maximo work flows in place and forcing standards
- Sometimes the reports are way too manual to manipulate for the report
   - Going through reports is a big pain
   - If he could link up the child work orders to the parent work orders by the work order ID, that would be great but he is not able to do that
    - Wants to get out of excel and work groups and get into dashboards that update overnight and are available on SharePoint and are unique for the staff using the report (Reiner, Division Managers, Superintendents, Supervisors)
    - Would love to have a data warehouse that pulls in financial data and operational data and staff data
### What challenges are you having with Maximo?
- CSR reporting as 68 problem codes so this makes CSR reporting challenging

## Future roadmap and upgrades

### What would you like your work order management system to do that you’re not getting right now? What’s missing?
- End goal is to have the data cleaning completed in advance so he can bring it into PowerBI and have it refresh overnight
- When he was with EMS, they created a data warehouse and they would use the models to pull the data he needed and he would love this for Maximo.
- Not all assets are in Maximo: missing Alleys and Urban Trails
- CSRs: would like to know when a CSR triggers more work
   - CSR generates work order
   - District fixes problem or patch repairs
   - Puts that work order in 4COMP and that closes the CSR
   - Creates a follow up work order for permanent repair
- Specifications are a pain because it’s data he has to harvest manually. Using specifications a lot for sealcoat prep and bridges
    - Still figuring out specifications because they might want to turn those into child work orders
- Data quality issue: within surface repairs, were trying to track how many surface repairs they did within one work order and the square footage
   - This year was the first year they paid attention to seal coat prep
- Figuring out what’s in the warehouse is what David needs help with.
   - That’s something that DTS could help with
   - Looks like they are using star schema
   - Schema and data mapping documentation doesn’t really exist
- Develop data governance on Maximo with validations

**Comment by dianamartin** [comment]
@ChristinaTremel do we need to synthesize these notes on to our board?

**Comment by ChristinaTremel** [comment]
@dianamartin yes we do! I have time scheduled for us to synthesize these and the Urban Forestry notes on 7/16. ✅

**Comment by rebekkabry** [comment]
## Continued Discussions and Efforts 

- https://github.com/cityofaustin/atd-data-tech/issues/17796
- https://github.com/cityofaustin/atd-data-tech/issues/18213
- https://github.com/cityofaustin/atd-data-tech/issues/19586
- https://github.com/cityofaustin/atd-data-tech/issues/18080
