### ISSUE TITLE
[Enhancement] Update Applications Statuses

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#17940]
#### Update Statuses
- In Progress - Not Submitted
- ~~Submitted - Under Review~~
- Submitted - Payment Pending (new)
- Pending - Needs Review
- Pending Approval - Require Action
- ~~Pending Approval - Pending Payment~~
- Approved
- Declined
- Expired
- Cancelled

Note: Update the application so that when status moves to "Submitted - Payment Pending" so that they get notification that they need to payment.

**Comment by susannegov** [comment]
```
In Progress - Not Submitted
Submitted - Payment Pending
Pending Approval - Under Review
Pending Approval - Require Action
Approved
Declined
Expired
Cancelled
```
- [ ] Everything below is to be deleted after changing rules
```
Submitted - Under Review
Pending Approval - Pending Payment
Submitted - Require Action
Not Started
```

**Comment by susannegov** [comment]
# Record Rule Changes
Update every record to Submitted- Pending Payment

**Comment by susannegov** [comment]
Synched up with Patrick on 07/01 to discuss to new statuses
```
In Progress - Not Submitted
In Progress - Notary Required
In Progress - Notary and Payment Pending
In Progress - Payment Pending
Submitted - Under Review
Submitted - Require Action
Approved
Declined
Expired
Cancelled
```
Will make changes to record rules

**Comment by susannegov** [comment]
# 07/02
- Added record rule to review page
   - On Site = `In Progress - Notary and Payment Pending`
   - On my own = `In Progress - Notary Required`

**Comment by susannegov** [comment]
# 07/03 
- Removed excess status filter bar in the Manage Application > App. Dashboard page
   - If status is the following below it should be put in a Cashier page instead of the reviewer page?
      - In Progress - Notary Required
      - In Progress - Payment Pending
      - In Progress - Notary and Payment Pending

**Comment by susannegov** [comment]
# 07/05
- Added a "Manage Applications" for Cashier view
- Added a payment form for cashier and notarize app table
- Added fields `Is Payment` and `Payment Date` field to applications object
- Added record rules to the two buttons
   - Attach Notary
   - Pay Application
