### ISSUE TITLE
Provide VZ Shp file of location where speed limits have been changed

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#17953]
VZ is looking for data showing the locations where speed limits have been changed since 2020

**Comment by andrewshensky** [comment]
A subset of data from the TED speed limit dataset was provided showing areas were current and/or final speed limits match the proposed of 25. This is best reflection of recent residential speed limit changes.

**Comment by andrewshensky** [comment]
After further discussion with VZ they would specifically like to identify arterials where speed limits have been changed since 2020. TED was able to provide an excel and pdf with descriptions of these locations. Geo team will create a subset of the CTN showing just segments identified in the TED documents.

**Comment by DanielStover** [comment]
A deliverable was provided to the stakeholders.
