### ISSUE TITLE
Update [CPO-BFZKSQ3-N1] Old laptop to Windows 11

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#17963]
Ben White
## Device & User Information (first name and last initial, no last names)
Laptop & Lauren, R 
## What's the problem?
[ ]Check Inventory DTS and add Windows version [If the machine is not in inventory add it]

[ ]Check Intune [If the user is not assigned to the computer, add the user]

[ ]Check CTM Data Base (https://atx.servicenowservices.com/now/nav/ui/classic/params/target/%2Falm_asset_list.do%3Fsysparm_view%3D%26sysparm_first_row%3D1%26sysparm_query%3Dmodel_category%253D81feb9c137101000deeabfc8bcbe5dc4%26sysparm_clear_stack%3Dtrue) [correct and add the info if needed]

[ ]Gather COA tag
DELL78417
[ ]Update Computer to Windows 11
[CPO-BFZKSQ3-N1]
 
## What did you do to resolve the issue
Have took over the laptop from old user and started updating to win 11, process in progress.

**Comment by Matthew-M-TPW** [comment]
Update complete
