### ISSUE TITLE
Add Zicla as domain in markings_specialty_line TYPE

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#17975]
Ziclas are a new markings_specialty_line and will need to be tracked in GIS similar to concrete domes. In SMD sprint review it was mentioned that concrete domes/delineators might be phased out.

Zicla below 
![image](https://github.com/cityofaustin/atd-data-tech/assets/31259724/c9df6709-0b91-4f7c-bea1-e38931c10418)

**Comment by andrewshensky** [comment]
The Zicla domain has now been added to Specialty Line Type domain
![image](https://github.com/cityofaustin/atd-data-tech/assets/80716478/91d8f8b3-102e-4dbf-a290-474727d17fd1)
