### ISSUE TITLE
Count of unique ROW permit applicants

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#17980]
### Estimated amount of unique ROW permit applicants is needed for the CRM/Salesforce procurement effort. 
- RW, EX, UC, DS, PSM > Indate is 1/1/23 - 1/1/24 > count number of unique folder applicants

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader There are **_1988_** unique ROW permit applicants for the last calendar year (2023-24).
