### ISSUE TITLE
DTS Brand and Identity

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#18]
Mission, values, style guides, branding... While such things can feel superfluous to "real" (customer-driven) work when we're super busy, they have the potential to support our efforts in fundamental ways. They inform decisions from product prioritization, to UI design, to hiring processes. They help show our customers that we are capable and professional. They attract talented people to join our team. 

[WIP verbiage doc](https://docs.google.com/document/d/1PVhLUgdLfUqESp6s68whTDdxM7ySkrIh9QH-LlOcnWs/edit#)

**Comment by mateoclarke** [comment]
Seems like all the issues related to this Epic are closed and related work going forward is being captured under the [Compile DTS Values Statement Epic](https://github.com/cityofaustin/atd-data-tech/issues/115)

Should we close out this Epic @johnclary @amenity?

**Comment by amenity** [comment]
Yes, thanks!

**Comment by amenity** [comment]
Sorry, I take that back...That issue just belongs in this epic. ;)

**Comment by amenity** [comment]
Okay

**Comment by amenity** [comment]
Renaming this since "Branding and Identity" is a general part of DTS communications.
