### ISSUE TITLE
[Traffic Register] Feature: Create `Archive` button when a draft is not going to be approved

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18023]
During the sprint review, we asked about if there will there be scenarios where we need to cancel the regulation and what should that look like:
- Will need the ability because there are times that regulation numbers are checked out and not fully approved or submitted. 
- Chrispin proposed having an `Archive` button so it hold the draft status and information but doesn’t have to be fully approved. Users really liked that method!
- Usually this is super rare, but it does happen.

Create `Archived Draft Regs` button on the [App Admin page](https://atd.knack.com/traffic-register#app-admin/) and show a list of any draft regs that are flagged as archived.

**Comment by ChrispinP** [comment]
Draft Regulation Documents can now be Archived on either the Draft Editor or Draft Review pages from the Task Board. Archiving a Draft Regulation Document will also update any connected Regulation Items. Archived Documents can be accessed from the App Admin menu where they can be restored, or marked for deletion. Archived Documents will be hidden from the Task Board.

![image](https://github.com/user-attachments/assets/c1a247c1-c684-4ae3-be32-e49ed3ec4b25)
![image](https://github.com/user-attachments/assets/4fecd21a-144e-4858-a322-0cf7bf931f67)

Ready to review and test

**Comment by ChristinaTremel** [comment]
Reviewed this during the sprint review with TED! Closing this out.
