### ISSUE TITLE
Broken Moped Dataflow

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#18041]
> The column 'project_name_descriptor' of the table wasn't found

Got this error since yesterday about a missing column in the Moped Components table. We just need to either remove that column or rename it to match what is in the source table.

**Comment by Charlie-Henry** [comment]
Fixed. All I had to do was click "edit" in the TPW Development data flow. Then "edit table" of the one that was broken. After it refreshed in the browser I just clicked "save and close". Redeployed to production and we were fixed 👍 
<img width="712" alt="Screenshot 2024-06-27 at 12 07 40 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/30810522/4c99586b-e591-44d5-9337-04d4c56d9040">
<img width="410" alt="Screenshot 2024-06-27 at 12 07 57 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/30810522/076ba633-a70a-464c-97c6-97878e705428">

**Comment by mddilley** [comment]
@Charlie-Henry I added some info about coordinating with y'all when updating the database view. Feel free to edit! 🙏 https://atd-dts.gitbook.io/moped-documentation/product-management/updating-the-arcgis-online-components-database-view
