### ISSUE TITLE
[Spike] Explore Integration of Vendor and the Knack SR System

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#18049]
## Description
As part of transitioning SMS services from the 311 app to the Knack SR system, we've encountered a roadblock with Bird's adoption of the Knack system. During onboarding, we discovered that Bird has developed an internal system to extract 311 service request information from emails and close out issues through their Bird mobile platform, rather than logging onto Knack.

### Challenges
1. **Attachment Issues**: Uncertainty exists regarding whether the Knack system supports attaching images or other files to emails.
2. **Automated Transaction Capture**: There is no automated process to record when Bird closes out an issue on their end in our system.

### Next Steps
- Explore options for attaching emails within the Knack system.
- Develop a solution to ensure that data from Bird's resolution of service requests and impoundments is captured accurately in our system.

### Knack
[SMRT App Service Requests](https://atd.knack.com/smrt#sms-service-requests/)

### Knack Emails
![thumbnail_image001](https://github.com/cityofaustin/atd-data-tech/assets/5566727/25ac1a7d-5b44-41ae-8959-3212c3f4d2d8)

![thumbnail_image011](https://github.com/cityofaustin/atd-data-tech/assets/5566727/12e9ea4e-b797-49d4-9e45-12adb49630a9)

### Bird App resolution process

![image006](https://github.com/cityofaustin/atd-data-tech/assets/5566727/72c73947-7e93-4237-94cf-78497411d2ed)

![image007](https://github.com/cityofaustin/atd-data-tech/assets/5566727/e78525ce-29f0-420b-be3d-055fe269cfdc)

![image008](https://github.com/cityofaustin/atd-data-tech/assets/5566727/36dea931-ca3e-4502-8a70-3a4461f19b16)

**Comment by patrickm02L** [comment]
## 7/17/24
- If Bird has access to login into Knack then they can pull the information that they, need they would be able to close out through [view based PUT](https://docs.knack.com/docs/view-based-put).

**Comment by johnclary** [comment]
On the email side, the dev team cannot help with the email-based solution. The apps team might be able to put image urls in the email. It sounds like that would be helpful.

It is possible to automate all interactions within our Knack app. They can use the [view-based API](https://docs.knack.com/docs/view-based-requests) to login to Knack, retrieve JSON data and images, and also to close out requests.

Lastly, you all could consider creating an internal 311 SR type so that everyone can continue using 311.

**Comment by patrickm02L** [comment]
## 7/22/24 

Sent the following email message to Bird at the request of Michael from SMS to check in about Knack integration:

> Hi Bird Team, 
> 
> I hope this message finds you well.
> 
> We wanted to inform you that we won't be able to add attachments through emails in our new Knack SR system. However, there is a possibility for you to plug into Knack through the [view-based API](https://docs.knack.com/docs/view-based-requests) to automate interactions.
> 
> If you are interested in exploring this option, please let us know, and we can help identify the right tables to pull from. Bird would be responsible for building the connection on your end and incorporating it into your app.
> 
> Please let us know if you would like to go this route, and provide us with an anticipated timeline to coordinate any technical support between our teams.
> 
> Best regards,

**Comment by patrickm02L** [comment]
## 7/25
Michael K. sent a follow up message to Bird asking them to let us know by COB 7/26/24 how they want to proceed.

> Hi Bird Team,
> 
> Following up on this, please let us know by close of business tomorrow if this is a possible solution on your end. Our team needs to move forward with other projects, and we would like to implement this new process as soon as possible.
> 
> Thanks and let us know if you have any questions.

**Comment by dianamartin** [comment]
# 8/30/24
We can have future discussions about this if we want to accommodate the vendor taking John's recommendations:
>It is possible to automate all interactions within our Knack app. They can use the [view-based API](https://docs.knack.com/docs/view-based-requests) to login to Knack, retrieve JSON data and images, and also to close out requests. We also maintain a [python library](https://github.com/cityofaustin/knackpy) which serves as a Knack API wrapper.

Closing, this as the research has been done.
