### ISSUE TITLE
[Spike] Explore Use Cases for UI interactions

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#18054]
## Description
As part of understanding the context of Moped, we want to set aside some time to do more review on Dashboards, maps, filtering, and general interfaces and interactions that would inform how we respond to user feedback. 

## Challenges 
1. We need to asses if there are some common patterns for interaction that could apply to Moped
2. Inputting data into the map view and continuity between different mapping tools

## Next Steps
- Document uses in miro
- Recommendations for how we could adopt any solutions now

**Comment by patrickm02L** [comment]
@olivialuk please update and close out if finished.

**Comment by olivialuk** [comment]
I observed common UI Patterns to help inform my design solutions. The documentation from this Spike can be found on this [Figma](https://www.figma.com/design/gTKjSG5TDSS1TIofaMKPVh/Moped-Map-Design-Mockups?node-id=3-1936&t=0Eyb7EEq4QoU33S9-0) in the Wireframes/Ideation Page.
