### ISSUE TITLE
[Traffic Register] Create `Graduate Engineer` user role to allow them to review regs

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18058]
- Graduate engineers will need a unique role in the Knack application because they should be able to give comments and reviews. Will not actually be signing off on regulations. Area Engineers are okay with them looking at the North area regs that need to be reviewed.
- Repurpose `QA Reviewers` and rename to `Graduate Engineers`
- Allow this user role to see all regulations for their assigned area

**Comment by ChrispinP** [comment]
QA Reviewer is now the Graduate Engineer role throughout the app. Submit rules have been updated to allow for assignment of Graduate Engineers to a record. Graduate Engineer role also added to Task Board so they can see assigned items.

Complete, ready to review

**Comment by ChristinaTremel** [comment]
Reviewed this during the sprint review with TED! Closing this out.
