### ISSUE TITLE
Review Overlay Milling Hierarchy for Independent Service Plans for Risk

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#18079]
# Background 

Pavement has requested the Overlay and Milling hierarchy be removed to allow for independent work order handling within the Pavement Service Plan 

Reasons for Requests: Overlay and Milling are dependant upon the status of the other workorder before being able to go out and complete the work. They will like to be able to complete the work, regardless if the Parent has been completed. We need to ensure the Parent does not have any required conditions needed for the Child, which is why currently dependant.  

**Desired Completion**: In preparation for FY25 Service Plan Upload

## Stakeholders to Sign Off and Approve Before Any Changes are Made
- Pavement Leadership 
- Data Owners (CTE) 
- Reza and Team 
- DM and Lead Techs (to understand how the change impacts their day to day) 

## Concerns to Investigate 
- Hierarchy Relationship Dependencies 
   - Ops Handling 
   - Reporting 
   - Data Back End for Historically Records 
- Work Order and Investigation Prompts Losts? 
- 
## Scoping Plan 
- work with Reza and team to map out current/proposed/risks states 
- present to requesters 

**CURRENT** 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/4c62d687-570e-4154-bbcf-062175c5cda0)
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/847b0fdf-aedc-4c8f-82d3-48b91c819bd1)

**PROPOSED**
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/625d7b13-008a-4e44-8e0b-1ed85704ef96)
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/0603d7c6-6efd-4163-b506-e3d9cef7fc88)![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/30cb771a-e34a-492c-9a7e-59aff5547f34)

**Comment by rebekkabry** [comment]
# Notes from 7/17/24 
_Attendees: Ron, Reza, Rebekka, Binaya, Ambarish_

**TPW Roles:** 
Reza - planning 
Andre - ops/ specifications and status updates

![image](https://github.com/user-attachments/assets/6ac534fa-bf2f-456c-a13d-518cc28428ab)


**Currently vs Proposed by Stakeholders** 
Concern: lost visibility of complete project completion (MILL and OVER)
![image](https://github.com/user-attachments/assets/fe703733-78a8-4b0f-8239-88dd0f85bccd)


## **Proposed**
### _Considers_: 
- [ ] Should we just change the name of the children workorders? 
- [ ] How will they track what has been milled? 
### _Concerns_: 
- [ ] Adds extra steps for work order handlers. 
![image](https://github.com/user-attachments/assets/f22a0051-f87f-4d0d-8474-526d545ee937)


![image](https://github.com/user-attachments/assets/9da8e937-003a-404d-9a5f-1f6b65684db2)


### **Dependiences:** 
Milling is first. 
Pavement is last. 
Is there other work in between. 

### **Want:** 
MIll and Over separate, not as the dependent child of the work order. 


# ✔️ ACTION ITEMS
- [ ] schedule meeting so Andre can attend and speak to concerns.

**Comment by rebekkabry** [comment]
# Notes 7/18/24 
_Attendees:_ 

- [ ] go through checklist topics above

**Comment by rebekkabry** [comment]
![image](https://github.com/user-attachments/assets/a5fd5bf3-1cc4-4974-9111-a4873bed7671)


Goal: 
split the team into 2: milling and paving team 

Current: the way we have the two crews we cant 

Milling can do more than paving, currenting cant completel milling becuae have to wait for overlay. 



Can you not change the status the parent without the child being complete? we can 4qa the child, but we cant get credit for the overall work order until the pavig is done. 
doesnt show up on completed lane miles report. 

could we run a report on the milling children? as an option. 
---the concern: one report that would show them stand alone. 

paving and milling children of the parent work order = not want they wont. 

if we can report indentpendly doesnt need to change.

**Comment by rebekkabry** [comment]
# Builder Notes 
@GaneshKamarapu - can we discuss the efforts on this? and how much it may align with this request #14546  

- [ ] Service Plans:
```
SP24-SLCT1 
SP24-SLCT2
```

- [ ] Workgroup
```
Overlay
```

- [ ] Separate by Work Order Children 
```
Milling: -MILL
Pavement: -OVL
```

- [ ] Status
```
any 4
```

- [ ] Metrics and Parimeters
```
- by week 
- Count of completed WO by  (MILL, OVL, PROJECT WO)
- Count of miles by (MILL, OVL, PROJECT WO)
```

**Comment by rebekkabry** [comment]
![image](https://github.com/user-attachments/assets/d5ada89e-8d47-4b12-a371-25646616f760)

**Comment by rebekkabry** [comment]
**BUILD followup** 
Pg 1: Total Graph - with data **(current phase)** 
Pg 2: Mill ONLY Graph with data 
Pg 3: OVRLAY ONLY Graph with data 
_* may be best to use the WorkGroup as the Work Orders do not specify the OVL Children Work Orders_

**Comment by rebekkabry** [comment]
@ganesh Lets put this on hold per Ron pending Andre's return and rescoping.

**Comment by rebekkabry** [comment]
## 9/12/24
- worked with team to create a milling portlet in PAVEMENT start center. 
- team will follow up on further report or dashboard needs. 
- https://github.com/cityofaustin/atd-data-tech/issues/19011

**Comment by rebekkabry** [comment]
# 10/14/24 

- Holding on Hierarchy revamp pending Andre E. return 
- To support reporting needs from (OCE/Ron/etc) we will create Overlay Performance Pull. 
- NOTE: [SBOPVMT Overlay Lane Miles Progress Report (Monthly Operational Performance Measures)](javascript:sendEvent('openreport','m87a38418-content','sbo_overlay_lane_miles.rptdesign$SBO_WOTRK$1354')) report is active in maximo, but it does not have completed dates or reference the MILL portion of the projects. 
- Build out a query and report of the following: (noting that -MILL currently does not seem to track any specifications or materials) 
- Will tie to a Start Center (previous conversations of building for team) 
![image](https://github.com/user-attachments/assets/7aead717-35ef-41df-bbad-6a6d67be3660)

**Comment by rebekkabry** [comment]
# 11/8/24 
- scoping with Ganesh, after Q/A from stakeholders 
- 
![image](https://github.com/user-attachments/assets/0c326b96-f339-44fb-b792-b805e92711e8)


**Build Notes** 
+ Overlay and Milling 
- update the report to only include WorkType CW, should not include SBOIMG with that filter.
-  remove 1NEW from area, width
- find the "difference work orders"(ganesh recommends possible table view
-

**Comment by rebekkabry** [comment]
## 11/26/24
- updates from Ganesh - will have updates 11/27 to review 
  - exploring showing the missing or different work order from each group. 
  - Removing 1NEW from area/width/depth @GaneshKamarapu

**Comment by GaneshKamarapu** [comment]
@rebekkabry I have updated the report and deployed in prod

![image](https://github.com/user-attachments/assets/fbab1b16-0a1b-431d-b872-9068da17ef4e)


![image](https://github.com/user-attachments/assets/fc34cb09-e6e0-4e9a-9ec6-83c8ba4d40a1)

**Comment by rebekkabry** [comment]
# 12/6/24 

- Sent email to stakeholders with the latest version of the report modifications. 
- Closing ticket. 

![image](https://github.com/user-attachments/assets/b2f95933-ceb6-45af-85b6-dfcbf2792f9c)

[SBO_OverlayandMilling (1).pdf](https://github.com/user-attachments/files/18044960/SBO_OverlayandMilling.1.pdf)
