### ISSUE TITLE
BUG - EX Web Application Acceptance (Verify on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18073]
![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/144c7525-ee88-43cf-ace7-40baf1f29732)

**Comment by SubhaShroff** [comment]
Reasoning: Process_EX_00070000 has respective variables declared with limited length. Updating the procedure for those lengths would fix this bug.

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0437097**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I tested the DEV deployment. Please sent it to TEST.  Thank you.
[18703 - 79371739e880b18fe124eea132ec304fe69d3af1 TEST Deployment Plan.docx](https://github.com/user-attachments/files/16134853/18703.-.79371739e880b18fe124eea132ec304fe69d3af1.TEST.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to TEST under **SCTASK0438079**

**Comment by SubhaShroff** [comment]
@Nadin-Nader This is deployed in TEST and tested. Its not giving any compilation error. Ready for UAT on TEST. Thank you.

**Comment by TracyLinder** [comment]
@KyleErich FYI this is ready for UAT in test.

**Comment by KyleErich** [comment]
@SubhaShroff @Nadin-Nader UAT on TEST approved. Thanks.

**Comment by TracyLinder** [comment]
@SubhaShroff please promote to prod

**Comment by SubhaShroff** [comment]
Thank you Kyle and Tracy.
@Nadin-Nader Please create a PROD deployment request. Below is the deployment plan attached. Thank you.
[18703 - 79371739e880b18fe124eea132ec304fe69d3af1 PROD Deployment Plan.docx](https://github.com/user-attachments/files/16199223/18703.-.79371739e880b18fe124eea132ec304fe69d3af1.PROD.Deployment.Plan.docx)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0439805**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This ticket is promoted to PROD, today(7/17/2024). Can be effective from tomorrow. Thank you.

**Comment by KyleErich** [comment]
@SubhaShroff @Nadin-Nader UAT on PROD approved, thanks!
