### ISSUE TITLE
Restore CRIS import after export was disabled autonomously upstream

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#18081]
See @chiaberry's thread here: https://austininnovation.slack.com/archives/CM9MK950S/p1719837558692669

It looks like the CRIS export has been disabled for an unknown reason, and this issue is to track getting that restored and the last three days of data to be backfilled. 

Thanks to @chiaberry & @johnclary for observing and triaging this!

**Comment by johnclary** [comment]
Frank was able to restore the CRIS extract delivery by configuring a new scheduled delivery. we do not know why the previous extract was disabled.

**Comment by chiaberry** [comment]
oooh a palindrome issue
