### ISSUE TITLE
Feature: Internal user can replace the org on the case details

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18094]

**Comment by TracyLinder** [comment]
Chrispin will do the initial work on the test site, get feedback, then move it over to the prod site.

**Comment by ChrispinP** [comment]
This feature is ready in both Prod and Test environments for feedback. Staff users can switch to the modern layout to try it out. The modern layout allows for additional functionality to edit Org Info and the Contact Person or change the Contact Person. Buttons now exist in both the menu and the details view itself.
![image](https://github.com/user-attachments/assets/853fa4fb-86f6-426d-936d-9c3ba56c4ea8)

**Comment by ChrispinP** [comment]
When the organization record is updated for the case, it will now update all connected Submission Cycles and Contact records with the new org values.
![image](https://github.com/user-attachments/assets/e83abed9-3e3f-467b-af5a-ebc0b95ebfa8)

**Comment by ChrispinP** [comment]
complete, closing
