### ISSUE TITLE
Underpass Cleanup App User Review 7/2/24

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18111]
OCE began using this app a few weeks ago. We will collect feedback, implement requested updates, and close the epic.

**Comment by TracyLinder** [comment]
Great experience, working well
Takes a while for pages to load or to upload pics
Explore customizing to make more mobile friendly. They are using Iphone 13. 
Pics can take about 1 minute each to load. DTS is discussing this issue with KNACK. 


**Updates**
- [ ] Add status filter buttons
- [ ] Add a feature to auto-insert photo records on the table, to test for possible performance improvement.

**Comment by dianamartin** [comment]
# 7/2/24
## Enhancements
- [ ]  Add status filter buttons to the work order landing page. Also keep the ability for users to add their own filters.
- [ ]  Add a status filter button for Current Month
- [ ]  The default landing page view should be Current Month, All
- [ ]  Add a feature to auto-insert photo records on the table, to test for possible performance improvement.
- [ ]  Add trailer size .125
- [ ]  Add council district field to the work details
- [ ]  Add a report widget for council district
- [x]  Feature to export the schedule
>Added "print" functionality so that staff could export out the schedule and distribute to others
- [ ]  Add council district field to the Add new underpass location form

## Data Clean up
- [ ]  Delete all June records, based on schedule date

**Comment by TracyLinder** [comment]
@dianamartin I created 3 new issues based on your notes, and checked them off. Please close this when you're done. Thank you!
