### ISSUE TITLE
Enhancement - HR Digital Interview Prototype

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#18110]
HR Sprint Review 7/1/24 - Jennifer was out of office so Diana and I used the time as a work session. We reviewed and completed some of the enhancements. HR team will be to respond to some of other recommendations: 

**Interview Details**

- [x]  Move the Edit (Edit Interview) button to the Interview Details section
- [ ] Interview Status - Active, Inactive, Cancelled - Should Completed be a status option
- [ ]  If a Interview Status is Inactive or Cancelled should a reason be provided
- [x]  Does Facilitator Name represent the Hiring Manager? If no is Hiring Manager needed?

**Attachment:**

- [x] When Adding Attachments cannot select a candidate because the Candidates have not been added yet
 Move below Add Candidates

**Add Candidates:**

- [ ] Candidate Status - should "Withdraw" be a option
- clarification - Internal means internal to TPW not COA?
 - [ ] should Employee Type "Internal" or "External" be displayed in Candidate table. Is it something you need to report on?
 - [x] When selecting Internal Candidate, name is not populating in Candidates table or Candidates List????
- [x] Internal candidates are displaying Last Name First Name opposite for External Candidates

**Panel members:**

 -Are there requirements for who should be represented on the panel?
- [x] Add Panel member - Type of Panel Member (Internal - External) displays different from Type of Candidate. Pick one.
- [x]  When Internal Panel Member is selected can the Internal Division auto populate?
- [ ]  External Department should it be a selection list - otherwise it's entered different ways. may be difficult to maintain. Do you need to report on this?
- [x] Panel Members names are listed in different formats Last Name, First Name and First Name, last name

**Interview Questions:**

- [x]  Do we need a Edit button to modify an existing Interview Question?

**Add Responses:**
 
- [ ] Can the drop down only display current Interview Candidates (PCN#), Panel Members and Interview Questions related to this interview?
- Interview_Management what is this field for? (Interview_ID)?
- [x]  Internal Candidates name not populating

**Panel Dashboard\Panel member Details**
 
- [x]  Candidate List \ View - attachments are showing up for all candidates but attachments were only added to Simone and Tom

**Comment by dianamartin** [comment]
# 7/11/24
## Updates
### Add `Hiring Manager` field
- [ ] to Edit Interview
>we can't do this bc it's a text formula from the PCN mgmt. table
- [x] Interview Details and 
- [ ] Interview Details | Panel
- [ ] Panel Dashboard

### Add `Candidate Type` field
- Candidate Type - should we capture the Division for Internal Candidates?
>Yes!
- [ ] Add Candidate Type (Internal or External) to Candidate Table on all pages
- [ ] If we capture Division for Internal Candidates add to Candidate table

**Comment by dianamartin** [comment]
# 7/12/24
Synced with Stephanie and worked on polishing the pages for:
- Admin
- Admin - Panel
- Panel Dashboard

Adding "Scoring Criteria"
![image](https://github.com/user-attachments/assets/9774caeb-28eb-4e96-ac6a-fe37c65b89fd)

![image](https://github.com/user-attachments/assets/5673083f-1eb8-4327-902e-b1d1d3d3e471)

**Comment by stephaniemoorer** [comment]
Reviewed enhancements with stakeholders
concluded that we need to have additional workflow sessions before we move forward with any additional enhancements.

https://docs.google.com/document/d/1ZLonGnU0gVA2emEK5zlkWLpKt1zjGzstkDfz3x3Bn4I/edit
