### ISSUE TITLE
Remove June data for Underpass Cleanup

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18127]
Per OCE feedback, please delete all work orders for June, based on the scheduled date.

**Comment by TracyLinder** [comment]
Hi @dianamartin, this is ready for you and on deck. It needs an estimate.

**Comment by dianamartin** [comment]
# 7/8/24
## TABLE `underpass_cleanup_work_order` 
- [x] Assessment of records: `54 records`
- [x] [Filter](https://atd.knack.com/oce#underpass-clean-up/all-work-orders/?view_196_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_172%22%2C%22operator%22%3A%22is%20before%22%2C%22value%22%3A%7B%22date%22%3A%2207%2F01%2F2024%22%2C%22time%22%3A%22%22%7D%2C%22field_name%22%3A%22Estimated%20Schedule%20Date%22%7D%5D%7D&view_196_page=1): `Estimated Schedule Date` is BEFORE `7/1/24` - `41 records` 
- [ ] Batch delete 41 records
## TABLE `underpass_photos` 
- [x] Assessment of records: `508 records`
- [x] [Filter](https://builder.knack.com/atd/oce/records/objects/object_13?builder_table_filters={%22match%22:%22and%22,%22rules%22:[{%22field%22:%22field_138%22,%22operator%22:%22is+before%22,%22value%22:{%22all_day%22:false,%22date%22:%2207/01/2024%22,%22hours%22:%22%22,%22minutes%22:%22%22,%22am_pm%22:%22%22,%22time%22:%22%22}}]}): `Created Date` is BEFORE `7/1/24` - `422 records` 
- [ ] Batch delete 422 records

**Comment by dianamartin** [comment]
@TracyLinder ready to let stakeholders know this has been taken care of

**Comment by TracyLinder** [comment]
Stakeholders have been informed. Closing.
