### ISSUE TITLE
Prototype SIF Internal Review Distribution

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18124]
### Build light prototype of review distribution features on the SIF Assessment mod. The biggest value we can deliver is getting this activity out of Outlook and into KNACK. 

**Development Overview:**

- [x] Duplicate the TDA module
- [x] Keep same SIF project detail fields
- [x] Replace any text "TDA" with "SIF"
- [ ] Add access code feature with external viewing page
- [ ] On the attachment table, add 'show to customer' feature
- [ ] Rebuild existing SIF emails
- [ ] Build new emails for reviewer assignment and customer access code email

**MVP Features:** 

- Can assign a review task to internal employees.
-  Send automated emails.
- The SIF applicant can access case attachments
- Review due date (manual input by user; no automation yet)
- Review Status (Needs Review, In Review, Review Complete)
- Review Assigned To
- Notes
- Attachments (and ability to modify attachments)

**Potential User Workflow**
1. Case Manager (CM) creates a review distribution task
2. CM inputs reviewer assigned, due date, attachments, notes. 
3. CM clicks "Distribute"
4. KNACK emails the assigned reviewer
5. Reviewer clicks begin review
6. Reviewer adds a review comment, adds/modifies attachments
7. Reviewer clicks end review.

**For future discussion:**
- Task board?
- Any case status automation needed?

**Comment by TracyLinder** [comment]
**Demo scheduled** for 7/24/2024

**Comment by TracyLinder** [comment]
The prototype demo has been rescheduled to 9/6/24

**Comment by TracyLinder** [comment]
Duplicate the TDA module
- Keep same SIF infos
- Add access code feature
- On the attachment table, add 'show to customer' feature
- Rebuild existing SIF emails
- Build new emails for reviewer assignment and customer access code email

**Comment by ChrispinP** [comment]
Aside from reporting fields, object prep has been completed to convert the 4 TDA objects to Assessment objects to incorporate SWS (SIF Worksheet Submittals). Language & view IDs have been copied and updated. Rules and records have been updated as well.

![image](https://github.com/user-attachments/assets/148fe2c7-45ec-4887-8b42-6598f3710e14)

![image](https://github.com/user-attachments/assets/ec1d9df0-2a92-4429-ae34-d859e7808be6)

**Comment by TracyLinder** [comment]
Prototype Review Notes:

- Let's not forget the task board updates that will be required
- [ ] On the parallel review, add a feature to calculate the number of days of review time `from beginning to end`
- [ ] When a review is complete, send an email to the user who created the SIF case (vs the lead reviewer)
- [ ] Perhaps build a feature that allows users to know if a customer submitted a SIF or if a backend user created it manually. 
- [ ] Create a field for AMANDA reference cases, allow multiple codes to be comma separated 
- [ ] Fix the bug on the meetings object. It didn't show the meeting record Chrispin created.
- [ ] Add a council district field. Unsure if this should be available to the customer during application input.

**Comment by TracyLinder** [comment]
I added the debrief to apps refinement agenda for next week, 9/11.

**Comment by ChrispinP** [comment]
Most Action items above completed. Added missing fields and update Details page with better organization for all the data.

For the Task Board we need to determine which of the 3 options is preferred/best:
1. Merge SIF Worksheets table and TDA Reviews table together into an Assessments table with a child Parallel Reviews table (like how TDA is structured now) combining the data
2. Same as option 1 but separate TDA & SIF data with filter tabs
3. Keep SIF Worksheets separate and replace with 2 new tables for SIF Assessments & SIF Parallel Reviews (this creates an additional table. may be worth creating an additional user role for)

![image](https://github.com/user-attachments/assets/4469ac31-0ba7-44b1-af5d-25e63ae8f3cf)

**Comment by ChrispinP** [comment]
The new Staff & Customer forms are built and available for testing
![image](https://github.com/user-attachments/assets/ecc5628e-9de1-405a-bfb1-7931886271d3)

**Comment by ChrispinP** [comment]
This prototype is considered complete. Met with stakeholders and we determined what improvements need to be made to simplify usability and capture everything they need. Continued work to complete the module will be in #19404
