### ISSUE TITLE
Feature: Auto-insert photo records for the Underpass WO's

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18128]
### Add a feature to auto-insert photo records on the table, to test for possible performance improvement.
- _Identified during a meeting; notes are on #18111_

**Comment by dianamartin** [comment]
# 7/3/24
Referenced TDS and how Chrispin did it. 

- [x] Added a Details area above "Photos" table
- [x] Added Trigger buttons
  - 1 line
  - 3 lines
  - 5 lines
- [x] Moved "Add Photos" button from top navigation to it's own menu, near the new line buttons
- [x] Tested the creation of the new photo lines
- [x] Made table "in-line editable", for "Photo Type" and "Photo" fields
- [x] Added record rules to those fields - to capture "Modify By", "Modify Date"

**Comment by TracyLinder** [comment]
I asked the stakeholders to provide feedback on this feature. Let's check back in next week.

**Comment by dianamartin** [comment]
# 10/15/2024
We met with stakeholders on 8/2/2024 and showed them all the enhancements, closing this issue.
