### ISSUE TITLE
Maximo User Process Discovery - Urban Forestry

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18121]
## Objective 
The Data & Technology Services Division is initiating a series of meetings to learn more about Maximo user experiences and processes in TPW. In this meeting we'll be asking questions about how individual teams use Maximo and how it fits into their work processes.

## Goals:  
- Maximo system performance and functionality 
- User experience and interface experiences 
- Current processes within and related to Maximo 
- User feedback and improvement  
- Future roadmap and upgrades 

### User experience and interface experiences 
- Explain your process on how you use Maximo? 

### PROCESS - Planning
- Who plans the work? How do you get work to do? 
- How is work scheduled and issued out 
 
### PROCESS - Implementation
- How is work scheduled and issued out?
- Who is executing the implementation? 
 

### PROCESS - Field Work
- Who is executing the work - implementation? 
- Who is reporting on the work and what are they tracking? 

#### Maximo system performance and functionality 
- How long is it taking to do a Maximo work order in the field? 

### PROCESS - Review & Reporting
- What is your final review, QC process? 
- What reporting do you care about? How are you pulling that information out? 
- What are you reporting? 

### User feedback and improvement  
- What challenges are you having with Maximo? 

### Future roadmap and upgrades 
- What would you like your work order management system to do that you’re not getting right now? What’s missing? 

### Points of Contacts 

------
- [x] Schedule meeting - 7/3/24
- [x] Meet and take notes
- [ ] Process notes on Miro [Maximo Assessment Plan](https://miro.com/app/board/uXjVN7sxj9I=/)

**Comment by dianamartin** [comment]
# 7/3/24 - Diana's Notes

### User experience and interface experiences
Explain your process on how you use Maximo?

### PROCESS - Planning
Who plans the work? How do you get work to do?
How is work scheduled and issued out

### PROCESS - Implementation
How is work scheduled and issued out?
Who is executing the implementation?

### PROCESS - Field Work
Who is executing the work - implementation?
Who is reporting on the work and what are they tracking?
Maximo system performance and functionality
How long is it taking to do a Maximo work order in the field?

### PROCESS - Review & Reporting
What is your final review, QC process?
What reporting do you care about? How are you pulling that information out?
What are you reporting?

### User feedback and improvement
What challenges are you having with Maximo?

### Future roadmap and upgrades
What would you like your work order management system to do that you’re not getting right now? What’s missing?

**Comment by rebekkabry** [comment]
Continued Conversations around Processing and Solutions 

https://github.com/cityofaustin/atd-data-tech/issues/18612
https://github.com/cityofaustin/atd-data-tech/issues/18078
https://github.com/cityofaustin/atd-data-tech/issues/18918
https://github.com/cityofaustin/atd-data-tech/issues/19880
