### ISSUE TITLE
Register on WZDX Feed Registry

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18134]

**Comment by TracyLinder** [comment]
@Charlie-Henry did this get registered? Are we ok to close this ticket?

**Comment by Charlie-Henry** [comment]
@TracyLinder, no comments from USDOT they are working on adding us now.

**Comment by TracyLinder** [comment]
Hi @Charlie-Henry have you seen any update on this?

**Comment by TracyLinder** [comment]
### Done ✅
- [https://datahub.transportation.gov/Roadways-and-Bridges/Work-Zone-Data-Exchange-WZDx-Feed-Registry/69qe-yiui/about_data](https://datahub.transportation.gov/Roadways-and-Bridges/Work-Zone-Data-Exchange-WZDx-Feed-Registry/69qe-yiui/about_data)
