### ISSUE TITLE
ETL WZDX 1.0 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18132]
- Setup ETL to convert into JSON format
- Turn on the ETL?

**Comment by Charlie-Henry** [comment]
I'll have to go segment-by-segment and at this time and the logic is as follows:

- if `Closure : Full Road` is present, we will set `VehicleImpact` to `all-lanes-closed`
- if `Closure : Full Road` is not present but `Traffic Lane : Dimensions` is we will use the set `VehicleImpact` to `some-lanes-closed`

We are going to have to ignore all parking and sidewalk closures as providing any details on the `lanes` array requires knowing the order of lanes. I started a thread asking the community about it [here](https://github.com/usdot-jpo-ode/wzdx/discussions/372).

**Comment by TracyLinder** [comment]
Charlie is going to send an email to highway-data@dot.gov to confirm his method will work for the registry.

**Comment by Charlie-Henry** [comment]
ETL has been deployed, I'll close this one out!
