### ISSUE TITLE
Add unique ID to each Traffic Signal Status Event

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#18146]
In order to set up the traffic signals on [flash feed for Waze](https://developers.google.com/waze/data-feed/road-closure-information#json-closure). We need to have an incident id that is:

> The incident id field specifies an alphanumeric or numeric identifier. This id must be unique inside your feed and remain stable over an incident’s lifetime.

I think we should be able to accomplish this by hashing the `signal ID` ~~+ `operation_state_datetime`~~?

- [dataset](https://datahub.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-Status/5zpr-dehc/about_data)
- [script](https://github.com/cityofaustin/atd-kits/blob/production/atd-kits/signal_status_publisher.py)

**Comment by johnclary** [comment]
that sounds like it should work! or just signal ID 🤷

**Comment by ChristinaTremel** [comment]
Love the idea of using Signal ID if that works for Waze! 🙌

**Comment by Charlie-Henry** [comment]
It is done!
