### ISSUE TITLE
New Folder Info: ASMP Street Level (LP) - (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18162]
### Create a new folder info for ASMP Street Level, and add the info to EX, TURP, DS. 
- _Risk: The TCM updates might do away with ASMP._ 

### 1. Create new folder info
- **Info Name:** ASMP Street Level
- **Info Group:** Project Information
- **Field Type:** Pick; `Values are: 1, 2, 3, 4, 5` 

### 2. Add info to EX, DS, TURP
- Not mandatory
- Not viewable on portal

**Comment by TracyLinder** [comment]
This is ready

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and requested for Dev and Test promotion, SCTASK0445466

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Ready for UAT on Test

**Comment by Lpriya-LIT** [comment]
<img width="1134" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWxKQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--569b59218a3e487a5b76d17564e616fb172a06b9/image.png" alt="image.png" />

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Ready for UAT on Prod

**Comment by Nadin-Nader** [comment]
Approved, Closing
