### ISSUE TITLE
Vehicle Inspection Testing Feedback - 7/9/24

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#18164]
Shavyvonne 
Enforcement Services

Messaged 
>Good morning it's Me y'all problem child 
....Issues we have encountered this morning with the Manage Vehicles:  We have to select a beat because it's a required field. We will need Moody Center, Zilker Park, and Special Assignment/Other added. The field for Post Check Out can we get an all field verify like the fluids so we don't have to check each one individually. The photos are taking too long to log or wont load at all. Can we adjust to only include pictures if there is an concern or observation instead. Because we currently can't submit it without the photos.

>Jasmine can't submit my vehicle log without the pictures and they won't upload. Only 3 of the 6 pictures uploaded and we tried twice to retake the pictures but they keep timing out.

**Comment by dianamartin** [comment]
# 7/9/24

## Things to Update
- [x] Missing Beats
  - Moody Center, Zilker Park, and Special Assignment/Other added
  >Add this while I was syncing with Shavyvonne
- [ ] Test Post-Check Inspection to make fluids be "I verify.. I have checked"
- [x] Make Photos NOT required
>Did this while I was syncing with Shavyvonne
- [ ] Make the Safety/Gear list like the "fluids - I verify..I have checked"

**Comment by dianamartin** [comment]
# 7/12/24
- [x] Created new field `Gear Safety Checklist Verification` on `fleet_vehicle_checklist` 
- [x] Added to "Add Vehicle Checkout Inspection" form
- [x] Updated display rule
- [x] Updated "Vehicle Checkout Inspection Details" form 
![image](https://github.com/user-attachments/assets/73f2843b-a5a4-4f9b-a260-7e94350e7e12)

**Comment by patrickm02L** [comment]
@dianamartin we reviewed this at the meeting on 7/31/24. You think it's good to close?

**Comment by dianamartin** [comment]
Did we have any outstanding things? I remember there being 2 things.

**Comment by patrickm02L** [comment]
In the notes I have:

Help guides
- Overview
- Submitting a pre and post check for the vehicles
- Adding another vehicle to the Manage Vehicles page

Should this be it's own issue?

**Comment by dianamartin** [comment]
@patrickm02L yes, I think both of those need to be their own issue. I had almost forgot about them!

**Comment by patrickm02L** [comment]
Help Guides Issue can be found here #18534

**Comment by patrickm02L** [comment]
I made New Issues for the new stuff, we can close this out now.
