### ISSUE TITLE
Migrate project team table to DataGridPro

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#18178]
We should migrate the project team table that uses `@material-table/core` to use DataGridPro. See https://moped.austinmobility.io/moped/projects/1909?tab=team for the current table.

**In Scope**
- **ADD TEAM MEMBER** button creates new inline form row on click
- Info icon in in **Role** header links to https://atd-dts.gitbook.io/moped/user-guides/project-team
   - Mike D will update docs in https://github.com/cityofaustin/atd-data-tech/issues/19513
- All columns are sortable 
- See [epic](https://github.com/cityofaustin/atd-data-tech/issues/18174) for patterns and improvements to implement

**Bonus points**
- **Name** sorting appears broken in production. Fix if it isn't a rabbit hole 🐇 🕳️

**Comment by mddilley** [comment]
Chia: here is the PR where I did the files migration https://github.com/cityofaustin/atd-moped/pull/1438

**Comment by chiaberry** [comment]
As Im working on the milestone datagrid issue, I am remembering that the Files table I mentioned last week didnt have the "add a new row to add a record", this PR has that: https://github.com/cityofaustin/atd-moped/pull/1374
