### ISSUE TITLE
Migrate project milestones table to DataGridPro

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#18177]
We should migrate the project milestones table that uses `@material-table/core` to use DataGridPro. See the second table in https://moped.austinmobility.io/moped/projects/1909?tab=timeline for the current table.

**In Scope**
- **ADD MILESTONE** button drops down and still functions to add a new inline form row or insert milestones from the templates
- All columns are sortable 
- See [epic](https://github.com/cityofaustin/atd-data-tech/issues/18174) for patterns and improvements to implement

**Comment by chiaberry** [comment]
The project phases table is on data grid pro, but you cant double click a cell to edit, since the records are edited via pop up modal. Could be cool to see if we could toggle the modal to appear when someone double clicks a cell to edit?
Also pinning the edit/delete column to the right

**Comment by mddilley** [comment]
@chiaberry I love this idea, and I created https://github.com/cityofaustin/atd-data-tech/issues/19499 to capture it. Could you take a glance at it if you have a chance?
