### ISSUE TITLE
Bug on creating TCP project

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18204]
### Customer Portal user cannot create a project submittal.

![image](https://github.com/cityofaustin/atd-data-tech/assets/49930868/b4cb7edc-b1e7-4fba-83c0-361672ca1b88)

**Comment by ChrispinP** [comment]
Updated the rules in both Prod & Test

![image](https://github.com/cityofaustin/atd-data-tech/assets/67915167/58a623ac-be09-424e-aca2-179c3244ba9e)

Cases currently under creation should now allow for Submission Cycle creation. I also double checked that the confirm button will update Case and Submission statuses correctly upon Cycle confirm.

Ready for testing

**Comment by TracyLinder** [comment]
I tested the fix and this has been fixed. Thanks! Closing.
