### ISSUE TITLE
[Enhancement Request] Add Crew Column to Maximo DataHub Dataset

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#18208]
Request to add column CREW into the dataset pull from D. Anderson. We pull persongroup which shows who belongs to, but crew will show who does the actual work. 

[SBO Work Orders Dataset](https://datahub.austintexas.gov/Transportation-and-Mobility/Street-and-Bridge-Operations-Work-Orders/hjym-dxqr/about_data)

- [ ] Add `Crew` value 
![image](https://github.com/cityofaustin/atd-data-tech/assets/134445095/b9a170af-aba7-467e-9825-48847096783e)

**Comment by rebekkabry** [comment]
@Charlie-Henry can we get this into the Data Science Discussion or queue? Please advise on steps needed. Thank you.

**Comment by Charlie-Henry** [comment]
@katelunceford can we scope at DS backlog tomorrow?

**Comment by katelunceford** [comment]
Refinement notes: 

- Straightforward: Edit the existing ETL to add the column

**Comment by rebekkabry** [comment]
@katelunceford there is no date, but it is used to support their measures; so ideally as soon as possible. Thank you.

**Comment by katelunceford** [comment]
@Charlie-Henry I moved this to on deck since Rebekka asked for it ASAP and it's small... Any chance you can do it in the next week? 🤞

**Comment by Charlie-Henry** [comment]
Yup @katelunceford, I'll take a look this afternoon to see if I can find that field real quick

**Comment by Charlie-Henry** [comment]
Yup found it, it'll be a quick fix. `CREWID` is the field.
