### ISSUE TITLE
[Spike] Explore calculating stats for 10 random SMD CSRs

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#18206]
For the random sampling of CSRs, let's start with a group we're familiar with, like Signs & Markings. 

- [x] Pull 10 random closed CSRs from the last 30 days to see if the activity includes 
- [ ] Perform calculations on (how many?) CSRs from the last 30 days 
   - [x] Percent complete on time 
   - [x] Average (or median?) time open
   - [ ] Are the required fields complete? (Y/N)
   - [x] Is an update included to the resident? (Y/N)

CSR descriptions - last 30 days link: https://austin-cwiprod.motorolasolutions.com/cwi/search

**Comment by susannegov** [comment]
# 7/15
- Retrieved 10 random CSRs per SR description (can also be random in SMD)
- Average of Response Days, SR Age, Of days late

## Notes
- For last 30 days, there's only 2 SRs for `ATD - School Zone Sign Maintenance`
- Refreshing resets the random number DAX formula used to calculate... Will have to fix that when pulling in the CSR descriptions manually or do random from outside the DAX formula
- Excluding duplicated for now

**Comment by susannegov** [comment]
@katelunceford @Charlie-Henry 
Have questions on these two:

> Are the required fields complete? (Y/N)

What fields are defined as required and how do I check it?

 > Is an update included to the resident? (Y/N)

In the activites webpage, which one of the 4 would be defined as the update to resident? (See screenshot below)
![image](https://github.com/user-attachments/assets/cca41fc7-f5c4-4e2c-9b13-94aeddd2a3ce)

**Comment by Charlie-Henry** [comment]
> Are the required fields complete? (Y/N)

I'm not sure about this.

@susannegov, is there any data when you click the down arrow on the right of your screenshot? I guess we want to capture everything that is publicly viewable

**Comment by susannegov** [comment]
@Charlie-Henry  Here it is. Every time I expand one, it closes the other one. 😓 
![image](https://github.com/user-attachments/assets/945736a6-1c27-4a9f-bf5b-a94e9be52108)
![image](https://github.com/user-attachments/assets/30a7d7bb-05eb-499f-88a0-77d1a8198f28)
![image](https://github.com/user-attachments/assets/5822a8d4-7812-43f9-a8de-f1974c750278)
![image](https://github.com/user-attachments/assets/30d141bf-d64b-4c96-b410-bee5fd45a57b)

**Comment by susannegov** [comment]
@katelunceford Is there a service level agreement (SLA) for what the response time should be per SR description? I talked to Diana about it and she suggested contacting Carrie F. (see edit)  to get the service level agreement.  And also maybe ask Christina if she would know.

Below is screenshot of work groups and priorities from 2021 I believe.
![image](https://github.com/user-attachments/assets/de9e5642-9980-4e91-91ad-a7cfe2f08034)

**Comment by katelunceford** [comment]
@susannegov I'll reach out to Christina and Carrie to track down the SLAs. Maybe the SLAs have the required fields defined as well. If not, I think we'll need to ask the workgroup directly. But I want to see what we find in the SLAs first.

**Comment by susannegov** [comment]
# 07/19
- [ ] Filled out CSR activities of last 30 days of SR description for 
   - [ ] Parking Sign Maintenance
   - [ ] Road Markings/ Striping Maintenance
   - [ ]  School Zone Sign Maintenance
   - [ ] Street Name Sign Maintenance
   - [ ] Traffic Sign Emergency
   - [ ] Traffic Sign Maintenance

**Comment by katelunceford** [comment]
**Data Science Sprint Planning notes**

- Highlight things that are not available on the public site 
- Emergency SR types (like Traffic sign Emergency) is hidden from the public - citizen who made the request for a traffic sign emergency doesn't have access via this site - do they get email update?
   - downed stop sign = traffic sign emergency 
   - who tags it as traffic sign emergency?
      - It's not in the 311 request options online/app
      - But what if you call in?
- If something is open more than 30 days, the public can't check the status via motorola site

**Comment by susannegov** [comment]
# 07/26
- Created earliest days from created date to min activity date
- Created latest days from created date to max activity date (I believe this is the calculation used for response days)
- Created `Is update` if there is a detail text filled out to notify resident

**Comment by susannegov** [comment]
# 07/29
- Added SLA spreadsheet from OPM
- Added "About this Report" page

**Comment by katelunceford** [comment]
**Data Science Backlog Refinement 7/31/24**
- This is great so far! Go @susannegov 🙌
- Maybe we add calculations for
   - How long it's open
   - How many days late
   - If there's 3-1-1 feedback activity

**Comment by katelunceford** [comment]
Quick check-in with OPM 8/2/24
- We need the top SR type from each division
- For the sample, let's include: 

1. ATD - Bicycle & Pedestrian Issues
   - Active Transportation & Street Design (ATSD)
2. ATD - Traffic Signal Maintenance
   - Arterial Management (AMD)
3. PW - School Issues - Crossing Guard
   - Community Services
4. SBO - Debris in Street
   - District Maintenance
5. SBO - Pothole Repair
   - District Maintenance
6. ATD - Special Event
   - Office of Special Events (OSE)
7. SBO - Street Resurfacing 
   - Office of the City Engineer (OCE)
8. ATD - Parking Violation Enforcement
   - Parking Enterprise
9. ATD - Shared Micromobility
   - Parking Enterprise
10. ATD - Lane/Road Closure Notification
      - Right of Way Management (ROW)
11. SBO - New Sidewalk/Curb/Ramp/Route
      - Sidewalks & Urban Trails
12. ATD - Traffic Sign Maintenance
      - Signs & Markings (SMD)
13. ATD - View Obstruction and Fencing at Intersection
      - Transportation Engineering (TED)
14. PWD - Tree Issue Right of Way
      - Urban Forestry
15. SBO - Curb/Gutter Repair
      - Utilities & Structures

**Comment by katelunceford** [comment]
**Data Science Sprint Planning 8/7/24**

@susannegov let's make a few updates to this while we wait on the Activities Report from 3-1-1:
- Add a dropdown to select the type with the ability to view all
- Play around with how to display the descriptions when you have more than one selected.
- Organize by division first, then type.

**Comment by susannegov** [comment]
# 08/07
- Added `Group Description` slicer
- Removed `Signs and Markings` filter in 311 TPW CSRs in Power Query
- Added `Select All` option in Service Request Type
- Added SR Description title based on first service request type filter the viewer selects
- Removed `Signs and Markings` from title
