### ISSUE TITLE
Delete crash ID 19994593 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#18210]
Crash [#19994593](https://visionzero.austin.gov/editor/#/crashes/19994593) is in our database, but is not in CRIS. It appears the crash report was deleted/rescinded after it was filed. This was an officer-involved collision.

Here is the redacted narrative: 

> Investigator’s Narrative Opinion of What Happened (Attach Additional Sheets if Necessary) On 01/25/2024 at approximately 11:47am I <redacted> responded to a Disturbance Hotshot call at 411 W MLK JR Blvd 7-11 case #: 240250590. I was driving Code 3 (lights and sirens).I was driving on 38th EB in the third lane when I approached 38th St & N Lamar Blvd intersection. Since there was a red light signal for me, I completely stopped and cleared intersection. I looked right and noticed that all three lanes stopped, I looked left and first and third lane stopped. There was a bus on lane 1. There were no vehicles on the second lane of N Lamar Blvd SB. I continued the driving. Unit 1 wasn’t in my view. Then I noticed that Unit 1 is driving into my vehicle from the second lane on N Lamar Blvd SB. I wan’t able to react and then Unit 1 crashed into left rear door of my vehicle and my vehicle turned ninety degrees left because of the hit

**Comment by frankhereford** [comment]
```
-- First, delete from atd_txdot_person and atd_txdot_primaryperson
DELETE FROM atd_txdot_person
WHERE crash_id = 19994593;

DELETE FROM atd_txdot_primaryperson
WHERE crash_id = 19994593;

-- Then, delete from atd_txdot_units
DELETE FROM atd_txdot_units
WHERE crash_id = 19994593;

-- Finally, delete from atd_txdot_crashes
DELETE FROM atd_txdot_crashes
WHERE crash_id = 19994593;
```

The above has been tested locally, approved by a team member, run on staging, and run on production. 🏁
