### ISSUE TITLE
Run script to identify the existing AGOL maps that are utilizing the markings datasets

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18219]
Run script to identify the existing AGOL maps that are utilizing the markings datasets 

Links to the datasets: 
- [TRANSPORTATION_markings_specialty_point](https://austin.maps.arcgis.com/home/item.html?id=569f08da272c4d189b9e3aabef843dd4#)
- [TRANSPORTATION_markings_specialty_line](https://austin.maps.arcgis.com/home/item.html?id=477e92d9cfa54b5f9dd5fc021c17b7a4#)
- [TRANSPORTATION_markings_short_line](https://austin.maps.arcgis.com/home/item.html?id=bb7613cab7d947fa9453bb22115dac6d#)

**Comment by andrewshensky** [comment]
@ChristinaTremel I was able to have CTM pull what we need for this issue. The good news is that all CTM currently owned markings layers are pretty lightly used. This definitely gives us multiple options, I'm thinking we can discuss a path forward on this one during our next signs and markings sync.

[markings_short_line_AGOL_dependencies.csv](https://github.com/user-attachments/files/16639446/markings_short_line_AGOL_dependencies.csv)
[markings_specialty_point_AGOL_export_dependencies.csv](https://github.com/user-attachments/files/16639447/markings_specialty_point_AGOL_export_dependencies.csv)
[markings_specialty_line_AGOL_dependencies.csv](https://github.com/user-attachments/files/16639448/markings_specialty_line_AGOL_dependencies.csv)
