### ISSUE TITLE
Work with CTM to consolidate hardware resources dedicated to DTS on-prem servers into one VM

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#18238]
## Proposal

I want to have a discussion with the group about asking CTM to take the resources allocated to our three machines, destroy machine 2 & 3, and add those resources to machine 1. 

Currently, we're using only the first on-prem machine, with 2 and 3 sitting there idle. To add those compute resources to our airflow stack, for example, would mandate us setup the delegation system for a multi-host ETL cluster, which is unnecessarily complicated when we have the option of simply moving the compute resources to the primary host. Additionally, when running on any given machine, the ETLs will only ever be as fast as 1/3rd of the total resources can make them, as they will be running on a single machine, at any given execution. 

Maintaining one machine is a third of the work of maintaining three, and the effort of keeping three machines working will only increase as they diverge from each other. 

@mddilley - Can we add this to our next refinement meeting to get a group consensus on whether we want to move forward or not? Thanks!!

**In Scope**
- Reach out to CTM to request the three servers be consolidated

**Comment by mddilley** [comment]
@frankhereford yep, thanks for creating this, and I just added this to our doc for next week so we won't forget to talk about it

**Comment by mddilley** [comment]
We decided to move forward with asking CTM to consolidate the three servers during backlog refinement on 10/9/2024.

**Comment by frankhereford** [comment]
Email has been sent, awaiting response. I'm going to put this in on-going because it's a waiting game now.

**Comment by frankhereford** [comment]
This is sort of floating out in the ether now. 

We're not in a immediate jam on server capacity, but I'd say we're right up on where we need to be thinking about either dispersing our ETL load over `02`,`03`, or some AWS based thing -- or purchasing an upgrade for 01 from CTM.

@mddilley, It's my opinion that we will not make it through 2025 without having to take action on this, based on my read of our current status -- but that is a forward looking statement, of course.

Additionally, here's the price list which CTM shared with us in a recent meeting:

* $100 per GB of RAM
* $100 per VCPU (core)
* $6 per GB of disk, which includes a backup service

Changes need to be submitted via the [CTM request form](https://cityofaustin.formstack.com/forms/ctm_server_request_form), and must include a funding code (FDU).

**Comment by frankhereford** [comment]
Based on the scoped work on this issue, this feels completed, and we can open up something new when we decide or are forced into taking an action. Thanks!

**Comment by mddilley** [comment]
@frankhereford Thanks for stashing that info in here1 🙏 I created a new issue from your update comment so we will have the pricing and form at hand when we scope it out.
