### ISSUE TITLE
Living Streets 2.0 Updates from Staff Testing #2 [LSRB]

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#18252]
## Mon 7/15/24 
- met with LS Staff (Jonathan S. and Carmen W.) to assess results from Testing Round 2, with added existing 1.0 records imported into the system

**Comment by KaroEngstrom** [comment]
## Configuration Updates 

1.

**Comment by KaroEngstrom** [comment]
## Non-Testing Items Discussed 
- FYI @patrickm02L 
- staff question: **could the Play Streets hour selection be a dropdown instead of a number field?** 
     - A: this would result in a huge dropdown for each day; from .5 hours to 11.5 hours in 30 min increments; these would also have to be translated back to numbers to do the weekly hours math; this is not ideal so tabled this idea
- staff question: **can we prevent applicants from submitting a Play Street date for the same day, or for overlapping hours?** 
     - A: this is not currently configured and would require a more complex model of counting days used and then configuring blockers based on that; other alternative would be dev work; if this is only an occasional issue, no action is recommended as effort would outweigh the benefit 
- staff had wanted to **control the timing of when the Resubmit button was available**
     - we discussed option and the easiest was to simply hide it until they are ready for resubmittals if that time would be one that applies to all applicants in Approved or Deferred status 
     - if this needs to be individual and apply a specific numbers of days or months from decision, we need to both capture the decision date and configure the trigger for showing the button 
     - LS staff agreed that one date for all will be the way to go for now; for example: we will hide the Resubmit button until a specific date, and then make it available to every application in Approved or Deferred status; we can also similarly hide it again when needed  
- where did we end up on the additional signatures issue last week? 
     - Per our last meeting, LS staff will review their process with Matt and finalize the proposed requirement; we are not changing the build at this point and the reviewer has the option to require a new RAF
     - we discussed the option of maybe adding clarifying language to the resubmitted cycle Invitation to Apply email to explain this change to the resident
- **Outgoing emails from LS Knack** - Karo shared a PDF of the process with emails flagged; Carmen will update emails and write new ones as necessary; the LS staff has time over the next two weeks to create and update emails towards LS 2.0 launch

**Comment by patrickm02L** [comment]
@KaroEngstrom thanks!

Just wanted to recap on a few items:

- Play Streets Hour Selection: Agree, let's keep the manual time entry to avoid data type conversion.
- Scheduling Conflict Warning: It would be nice-to-have a warning for scheduling conflicts. Could be a neat addition. But not a deal breaker.
- Resubmit Button Timing: Will we need to manually hide the button for each cycle? Or will we schedule it based on a date and time frame?
- Additional Signatures: These should be handled through email as discussed. Agree, no changes needed to the current build.
- Outgoing Emails: LS staff are responsible for updating and creating new emails.

**Comment by KaroEngstrom** [comment]
@patrickm02L thank you

re: resubmit button - the current build is to show it based on application status immediately, as discussed. It sounds like manual reveal/hide is what we will do at launch to allow them to control the visibility further. It did not seem like the LS team wants an individually calculated rule for this (ex. three months from approval or install date, or similar). I suspect there's a process decision that needs to be established and maybe budget reasons that will determine the longer-term model for this.
