### ISSUE TITLE
Assist User Margaret R. with Shared Inbox Setup in Outlook 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#18283]
Earlier this week, Margaret R. was added to the livingstreets@austintexas.gov service account. She's been unable to see it in her Outlook and said that the instruction listed [here](https://support.microsoft.com/en-us/office/open-and-use-a-shared-mailbox-in-outlook-d94a8e9e-21f1-4240-808b-de9c9c088afd) also did not work for her. 

She will be available Thu 7/18 and Fri 7/19 and needs someone to help set up the account for her in Outlook. 
Location: Rio Grande?

**Comment by Matthew-M-TPW** [comment]
Reached out to user via teams

**Comment by Matthew-M-TPW** [comment]
Set up Mailbox
