### ISSUE TITLE
[Tablet Support] TPW SBO: Reset/Verify reset of 9 android Samsung tablets

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#18282]
This will be used for SBO timesheets in FY 25. These are old samsung tablets
**References:**
☁[AirWatch Management](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/airwatch-management)
🤖[Android Configuration](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/tablet-configuration)
🍎[iOS Configuration](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/ios-tablet-configuration)

**Select Issues:**
- [ ] Purchasing Devices
- [ ] Setting up a New Device
- [x] Setting up a New User
- [x] Switching Device User
- [x] Remove User & Wipe Device
- [x] Create or Modify a Device Profile (such as passcode policy)
- [ ] Missing/Lost Device (alarm ping, lock, last location)
- [ ] Deactivate SIM card
- [ ] SIM/Network/Hotspot/WiFi/GPS
- [ ] Workspace One: Intelligent Hub app
- [ ] Launcher profile (such as Home Screen apps/shortcuts)
- [ ] App Catalog: New, Outdated, or Missing app or icon
- [ ] Unable to launch an app
- [ ] Unable to charge/turn on device
- [ ] Device Update/Version
- [ ] Retire a Device (outdated, bricked, no longer used)

**Device Details:**

| User | COA Tag | SN | IMEI | Phone | Brand, OS Version, & Device Type | Notes
| --- | --- | --- | --- | --- | --- | --- | 
| FirstNameOnly | COA45810 | R52K70YGW2D | 357166090221258 | 737-704-8902 | Samsung Android Tablet | Require password. Needs resetting. In Airwatch under Rudolph V (AMD). Need to add to tablet inventory. Need screen protector. Needs SN/IMEI labeled. "Enter password to turn off tablet" |
| FirstNameOnly | COAR64142 | R52R5086FDT | 352250117267059 | 512-541-5945 | Samsung SAFE 6 ELM KNOX 3 | Require PIN. Needs Resetting. In Airwatch under Abraham G (AMD). Need screen protector. Needs SN/IMEI labeled. Update DTS tablet inventory record. "Enter PIN to turn off tablet" |
| --- | COA45811 | R52K70YJR4B | 357166090241736 | 737-7048674 | Samsung SAFE 6 ELM KNOX 3 | Need resetting. Require PIN. In Airwatch under Sray W (AMD). Need to add to tablet inventory. Need screen protector. Needs SN/IMEI/Phone No. labeled | 
| --- | COA45804 | --- | 357166090241512 | --- | --- | Not in Airwatch. Already reset. Needs to be assigned in SBO workgroup in airwatch. Not in DTS Portal. Need labeled SN/IMEI/PhoneNo. Need to verify if SIM card. Need charge |
| --- | COA45795 | --- | 357166090221936 | --- | --- | Is reset. Step 8 using google sign-in of airwatch android tablet config (see 1password) kicks back to verify your account page. Not in DTS portal. Not in Airwatch |
| --- | COA45259 | R52M10QF6KW | 355420100273680 | 5129629888 | Samsung SAFE 6 ELM KNOX 3 | Not in DTS Portal Needs reset. Unknown PIN. "Enter PIN to turn off tablet" . In Airwatch under Richard G. |
| --- | COAR64141 | R52R5086EMD | 352250117266804 | 5125410397 | Samsung SAFE 6 ELM KNOX 3 | Needs reset. Not in DTS Portal. In Airwatch under Lance C (AMD). Needs charge. |
| --- | COAW65454 | R52N902BZMY | 352250114629004 | 5126760123 | Brand, OS Version, & Device Type | Need Reset. Not in DTS Portal. "Enter PIN to turn off tablet" In Airwatch under Owen F. (AMD) |
| --- | No COA Tag sticker |  R52M40SJRPW | IMEI | Phone | Samsung Galaxy Tab S5e | Not in airwatch. Not in DTS Portal. Was already reset. Setting up work profile "Something went wrong" |

**Confirmations:**
- [x] Device in DTS Inventory
- [ ] User in AirWatch (in TPW group, not CTM)
- [ ] Device in AirWatch
- [ ] Device Labeled with COA Tag, SN, IMEI, & Phone #

**Comment by susannegov** [comment]
# Notes for 7/17
- Almost all the android tablets I test turned on with now require a PIN or password to turn off. 
- Of the 2 tablets that were already reset, both of them ran into this issue
   - COA45795 - Unable to set up enterprise airwatch account on google
   -  No COA Tag sticker Serial Number  R52M40SJRPW - Unable to set up enterprise airwatch account on google

**Comment by susannegov** [comment]
# 07/23
- [ ] `COAR64141`

**Comment by susannegov** [comment]
# Summary for 07/24
- 4 out of the 9 tablets are usable for tablet deployment.
- 3 out of the 9 tablets are stuck at the "Device wipe pending" in Airwatch console.
   - All of the are purple skin covers and are 
   - 1 start with the `COAW` COA tag and 2 start with  `COAR` COA Tag

**Comment by ChrispinP** [comment]
I was able to complete the reset and device wipes for 64141 and 64142.

65454 I was able to reset and wipe but it didnt go to the Server/QR sign in screen. Might need to be wiped again or just reset.

45795 I was unable to make any progress on, still unable to get past the pattern lock. We probably need to retire this device.

**Comment by susannegov** [comment]
Talked to Diana, we are not deploying these tablets but they are available on hand
