### ISSUE TITLE
Document Process:  Request to change roles in MAXIMO on incoming CSR related Work Orders

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#18293]
Document the process for #18207 and add to Google Drive/Scribe records.

**Comment by ReneVarg25** [comment]
### 7/24/24
https://scribehow.com/shared/Update_Person_Groups_With_Specific_Information__Pf3-ICdMStmI9SRUAO16pQ
Process for changing defaults of default supervisor and superintendent of work groups

**Comment by rebekkabry** [comment]
When the workorders were automatically being assigned to M Collier, the request was to have changed to be automatically assigned to the workgroup. 

Changes have been made. 

This is complete. Closing. No further actions needed.
