### ISSUE TITLE
Decommission remaining traces of `atd-ctr-etl-production`

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#18296]
After decommissioning the data lake collaboration with the CTR @ UT AWS resources, we still have some cleanup tasks to do.

- [x] Remove cron files on p01
- [ ] Archive the repo https://github.com/cityofaustin/atd-data-lake

@frankhereford I created this from the discussion in your skill share, and I missed one of the tasks to clean up the rest of the data lake things. Could you take a look whenever you have time and add anything else that you had in mind so we can get it in the backlog? Thank you!

**Comment by frankhereford** [comment]
During our skill-share, we disabled the data lake cron entries by removing the symlink out of `/etc/cron.d` and I have now removed the target of that symlink as well. 👋 

The `atd-data-lake` repo has been archived. 👋
