### ISSUE TITLE
Investigate funding sources AGOL field not coming across to Moped Database Viewer

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#18308]
We recently added a field called `funding_sources` to the Moped components AGOL dataset and our DB view that is used to populate that field by our ETL. Nathan W has reported that the value of this field is not coming through the Moped Database Viewer **for some projects** when attempting to use it.

Working for https://mobility.austin.gov/moped/projects/3446?tab=funding

Not working for https://mobility.austin.gov/moped/projects/1715?tab=funding

Data returned from AGOL feature service for project 1715 (https://services.arcgis.com/0L95CJ0VTaxqcmED/ArcGIS/rest/services/Moped_Project_Components/FeatureServer/)
<img width="816" alt="Screenshot 2024-07-18 at 6 20 46 PM" src="https://github.com/user-attachments/assets/177d9dbe-1022-4a7e-b134-14ac035b94dc">

Not coming through the AGOL application for project 1715
![image](https://github.com/user-attachments/assets/0962ba8b-b700-431e-8d23-445c5a0c948f)

**Comment by mddilley** [comment]
@andrewshensky I wanted to check if this rings a bell for you at all. We're having an issue with a field value in an AGOL dataset not populating as expect in an AGOL web app (https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=404d31d56b57491abe53ccfd718fcaee). I verified that the dataset contains the data we are expecting, but it isn't showing in the app.

**Comment by andrewshensky** [comment]
@mddilley I am curious if this issue has been remedied? It does appear that those values are being populated in the feature previously identified as not working. Also it appears that 375 of 11,784 features have a value populated in that field within the CombinedGeometries service.

![image](https://github.com/user-attachments/assets/4bb589bf-0c85-4381-aab8-0715378333cc)

**Comment by mddilley** [comment]
@andrewshensky yes this looks like a temporary issue that Nathan was experiencing. I heard from him this morning that all is working as expected now. Thank you for taking a look at this, and I'll continue to monitor but will most likely close this issue out. Thanks again!
