### ISSUE TITLE
IT Support: Rename machine name to proper name

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#18312]
BEN WHITE
Finance

## Device & User Information (first name and last initial, no last names)
John K 

## What's the problem?
This user is 
Please track down the following device and rename it to ATD-8LT1GX3-N1 its currently named  ATD-8LT1**C**X3-N1

So change the C to a G

## What did you do to resolve the issue
Have tracked down the machine and see that the renaming was done correctly. Hence, we are good to go.

**Comment by Vaishnav1397** [comment]
have reached out to the user and mentioned that user would be available sometime tmrw at office. Will make sure to check and rename it.

**Comment by Vaishnav1397** [comment]
Have tracked down the machine and see that the renaming was done correctly. Hence, we are good to go.
