### ISSUE TITLE
Clean up/merge outdated on-prem server documentation

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#18310]
Now that the documentation for the new servers has been created, we have some traces of the old server documentation in GitBook. Searching for atd-data01 (or 03 or 02) and other old servers still turns up results in Gitbook, and we also have some duplicated information now like [the old legacy servers page](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/legacy-scripts-and-services).

We should be reach a state where all information related to the on-prem servers is in [the new GitBook section](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/servers/dts-int-data-p01-on-prem-server), and all references to the server elsewhere are updated with the new server name.

**Comment by frankhereford** [comment]
❌ Route 53: `transportation-data.austinmobility.io` => CNAME => `atd-ctr-alb-production-236583621.us-east-1.elb.amazonaws.com`

Bystanders:
❌ Route 53: `atd-prefect-01.austinmobility.io`j => A => `3.90.149.203`
❌ Route 53: `grafana.austinmobility.io` => CNAME => `atd-data03.austintexas.gov`
❌ Route 53: `ldm-test-graphql.austinmobility.io` => A => `18.207.159.17`
❌ Route 53: `ldm-staging-graphql.austinmobility.io` => A => `dualstack.ldm-staging-load-balancer-405449461.us-east-1.elb.amazonaws.com.`
❌ Route 53: `ldm-test.austinmobility.io` => A `18.207.159.17`
