### ISSUE TITLE
Missing Invoice ID in Flowbird Parking Data

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#18330]
Since June, 6 2024, the finance parking data [dashboard](https://app.powerbigov.us/links/crXPJflRLg?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare) has been showing really low totals for parking. After some investigation, we've found that one vendor, Fiserv, is not getting the invoice ID field from Flowbird anymore (except for some PARD transactions). So, we are unable to join these two datasets using the invoice ID primary key.

Our only solution identified has been us emailing Flowbird/Fiserv until the issue is fixed.

**Comment by maccallump** [comment]
Background:  Flowbird uses Monetra software to gather transaction data from kiosks and meters.  Monetra performed an upgrade in early June.  In addition, Fiserv (COA bank) performed an update at or on the same day.  The field that was used to match bank information with transaction information was eliminated or was null.  This created a black to the reconciliation process in place.  
7/23/2024:  Met with Darren Cusano IT Manager at Flowbird.  Darren has requested and received data files from Fiserv and Monetra befor the updates and after to research what changed.  He is supposed to get an update Wednesday, July 24. He will notify us of the results.

**Comment by Charlie-Henry** [comment]
Looks like this issue was addressed. Sounds like finance was able to process June, July, August totals.
