### ISSUE TITLE
Report Request [New] - CSR-WOs Close SR work log 

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#18331]
Report (for internal use - DTS Maximo) 
Create a report or query that pulls CSR-WOs (missing a work log) QA, Resolved Status
Work log activity (not using dash) ex. (“ — Close SR”)

**Comment by GaneshKamarapu** [comment]
@ReneVarg25 and @rebekkabry request you to review this in Prod.  Report name is "CSR 311s Missing Work Log Closed Sr" deployed in SBO work order tracking

**Comment by rebekkabry** [comment]
Rene reviewed and works as expected, "looks great". Will implement for weekly reports.
