### ISSUE TITLE
Replace TCP CM Upgrade UAT Site

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18342]
**Foundational changes made to the prod environment required us to create a new copy for the test environment.** 

- [x] Import Combined Org Data, set Connections for Submitting & Owner Orgs for TCP
- [x] Copy Environment
- [x] Configure User Testing Feedback Form
- [x] Update Code
- [x] Remove SSO
- [x] Update Big Buttons
- [x] Configure Navigation
- [x] Set Passwords
- [x] Remove Pikachu settings
- [x] Review Emails
- [x] Show/Hide appropriate Views

**Comment by ChrispinP** [comment]
All action items completed above. New Test Environment is ready for testing.
