### ISSUE TITLE
[Spike] Explore eCitations Platform for Impact on TPW

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#18355]
## Description

Objective: Research the eCitations platform that APD is proposing to procure and gather TPW's requirements to ensure the new system meets their needs.

## Tasks
1. Review the RFI and any other available information on the eCitations platform that APD has published.
2. Meet with TPW stakeholders to understand their current processes, pain points, and requirements for an eCitations system, including:
   - Integration with existing TPW systems and data
   - Geospatial reporting and analytics capabilities
   - Performance tracking for parking enforcement officers
   - Privacy and data sharing considerations
3. Identify any gaps or concerns between the proposed eCitations platform and TPW's requirements.
4. Provide recommendations on how to ensure the new eCitations system meets the needs of TPW.

## Deliverables
- Summary of the eCitations platform being proposed by APD
- Detailed requirements gathered from TPW stakeholders
- Analysis of how the proposed platform aligns with TPW's needs
- Recommendations for addressing any gaps or concerns

Timeline: 3 weeks

**Comment by patrickm02L** [comment]
## 7/24
Here is the [contract from Tyler Tech](https://drive.google.com/file/d/1HJrUHTIH2Opmd8NUH7YElQszHP_b7umD/view?usp=drive_link) about the SLA for eCitations and equipment. Related, but potentially out of scope from the software side is that Lyndon reported that PE is having Issues with their Brazos devices. However, perhaps we can leverage our software procurement with the brazos hardware Issues.

cc: @maccallump

**Comment by patrickm02L** [comment]
## 8/7/24
- Check in with Parking Enterprise, Code, ROW, Vision Zero.

**Comment by patrickm02L** [comment]
## 8/12/24
- Met with Xavier from VZ and Shavyvonne from PE 
- Setting up a meeting with Ryan M for ROW

**Comment by maccallump** [comment]
@patrickm02L  Do you have requirements from Parking for parking tickets?

**Comment by patrickm02L** [comment]
> @patrickm02L Do you have requirements from Parking for parking tickets?

@maccallump Yes, PE asked for integrated printer functionality so officers don't have to carry a separate printer

**Comment by patrickm02L** [comment]
## 8/27/24
We met with the eCitation platform APD folks on 8/20/24 and presented findings, talked about in general what those requirements would be. The requirements seem to align with those for APD, but we ensured they also meet TPW's needs. Here's the [document of my findings](https://docs.google.com/document/d/1NENOLq5v9n77N_sNbV_iu2dzi9cU5dTfAex9ay7Q7N0/edit).
