### ISSUE TITLE
Update project list view advanced search with funding  sources

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#18361]
Now that we show a column with both funding source and program (`funding_source_and_program_names`) in the project list view table Funding column, we should update the advanced search to show ~**Funding program** in addition to~ **Funding sources** in the advanced search field options.

Considering the improvements made to the **contains** operator to optionally show dropdown options (see https://github.com/cityofaustin/atd-moped/pull/1373), we should update the source and program field options so that:

- ~they both search on the `funding_source_and_program_names` column in the `project_list_view` DB view~ we modified this to have separate advanced search options for source and program that search on sources only and programs only
- the default operator is **contains** since ~`funding_source_and_program_names`~ `funding_source` is a concatenated list of project funding rows
- **Funding source** presents options from the `moped_fund_sources` table
- ~**Funding program** presents options from the `moped_fund_programs` table~ Moved to https://github.com/cityofaustin/atd-data-tech/issues/18763
- they no longer use the **is** operator

See [this Teams message from MUG](https://teams.microsoft.com/l/message/19:meeting_ZWUwMWViZDItYTNlNy00MTcwLWI1OGUtNTA3Y2I5NmNiYTNi@thread.v2/1721155268837?context=%7B%22contextType%22%3A%22chat%22%7D) for support for this enhancement.

<img width="998" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXBWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2f5017cb34676c04dcd6815fe3e984ccb02c37f/Screenshot%202024-08-13%20at%205.19.38%E2%80%AFPM.png" alt="Screenshot 2024-08-13 at 5.19.38 PM.png" />

<img width="1744" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXhWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--faa56c71f970a2b41c61d319dad6739e5fe17308/Screenshot%202024-08-13%20at%205.19.50%E2%80%AFPM.png" alt="Screenshot 2024-08-13 at 5.19.50 PM.png" />

**Comment by mddilley** [comment]
After Chia found this wouldn't work quite like expected, we agreed to spin off an issue to add a funding programs column to the `project_list_view` and make the advanced search for programs use it in a new issue/PR.

**Comment by mddilley** [comment]
@chiaberry could you estimate this one since we assigned outside planning? my original thought was a 3, naturally. 3️⃣

**Comment by chiaberry** [comment]
agreed! 3

**Comment by mddilley** [comment]
I updated this description with the new direction it took and pointed to the issue that the program part of it ended up in for future reference. Thanks for shipping this one @chiaberry!!! 🙏 🚀
