### ISSUE TITLE
DTS Presentation at 360 Learning

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18393]
### We will present at 360 learning on Nov 21, 2024
- [Here](https://docs.google.com/document/d/1JqjFa3kK_5pPi-NI1DBrxRUTKmNrnSV5dhtMJJJ3nsM/edit?usp=sharing) is our note doc.

CTM PMO has been offering a learning platform called 360 Learning since January 2023. Every third Thursday of the month from 11.30 to 12.30pm, we identify speakers to talk about various topics that helps inform/educate employees. For example, in 2023, we covered topics such as GIS 101, Enterprise Asset Management, Public Safety, Cyber Security, PowerBI, etc. Each session we have seen an attendance of around 130-150 people from across City departments. In 2024 we want to open this forum to departments outside CTM, as an opportunity to learn about what the department does or a particular aspect of the department. 

[360° Learning (sharepoint.com)](https://cityofaustin.sharepoint.com/sites/CTM/TEAMSITES/PMO/Center/SitePages/360-Learning.aspx?xsdata=MDV8MDJ8VHJhY3kuTGluZGVyQGF1c3RpbnRleGFzLmdvdnxiMjRhOTY5ZmFlZGY0Y2E3MmYyNDA4ZGNhODI2ZGZhZnw1YzVlMTlmNmE2YWI0YjQ1YjFkMGJlNDYwOGE5YTY3ZnwwfDB8NjM4NTcwMTMyMTExNDUyNzU4fFVua25vd258VFdGcGJHWnNiM2Q4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazFoYVd3aUxDSlhWQ0k2TW4wPXwwfHx8&sdata=T0Q1SzloVXpzNmJKUkNUbEJ5aWJLODIvTk9sZXdzb09kVzd0VE15UmFIbz0%3d) – this link has the session recordings and presentations/speakers  completed in the past year or so.

**Comment by dianamartin** [comment]
# 8/13/24
- We met as a group and created an [outline](https://docs.google.com/document/d/1JqjFa3kK_5pPi-NI1DBrxRUTKmNrnSV5dhtMJJJ3nsM/edit) and [slide deck](https://docs.google.com/presentation/d/17Qe03qrm7iIVjE9TuhamY0KEOObHpvVJ4w4PTZ1YhiQ/edit#slide=id.g2f29b2c65e9_0_989)

**Comment by TracyLinder** [comment]
### Meeting Notes 10/22/24

- Upcoming Meetings: 11/6, 11/19
- Diana did some slide updates recently
- Tasks Assigned for each service spotlight
- Tracy do enterprise page
- Diana to do closing pages (questions/resources/thank you)
- We need a presentation outline for internal presenters to follow (see below)
- Considered adding a section for ‘Who We Support’

**Run of Show Outline**
- Who We Support - Diana (2 min)
- Who We Are - Diana (3 min)
- What We Do - Diana (7 min)
- Enterprise Support - Tracy (3 min)
- How we work - Christina & Kate (10 min)
- Our Services Spotlight (20 mins) 
- Geo spotlight - Andrew (5 min)
- Apps spotlight - Patrick (5 min)
- Dev spotlight 
- Moped - Mike (5 min)
- Data science - Charlie (5 min)
- Closing, Thank You, Questions, DTS Resources (5 min)
-

**Comment by patrickm02L** [comment]
Can we close this?

**Comment by dianamartin** [comment]
# 12/10/24
 - Presented at the 360 Learning Series on 11/21/24
 - Recording [here](https://cityofaustin.sharepoint.com/sites/tpwDTS/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FtpwDTS%2FShared%20Documents%2FPresentations&viewid=2958c37f%2Dbe1b%2D4ca8%2Db045%2Ddc17d145a4ba)
