### ISSUE TITLE
Add toolbar to Lexical rich text editor

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#18390]
Now that the spike has proven that creating notes, editing notes, and capturing email contents is possible in Lexical, the next step is to add a toolbar with tools that are similar to the ones that we currently have available in react-quill. @tillyw shared the starter [toolbar component](https://github.com/facebook/lexical/blob/5caf9231d456cadeb0f83fb69602b3bc6e433710/packages/lexical-playground/src/plugins/ToolbarPlugin.tsx) that can be used as a starting place.

**Current toolbar**

<img width="309" alt="Screenshot 2024-07-24 at 5 11 21 PM" src="https://github.com/user-attachments/assets/fa27807d-34d7-408c-8481-458b1809bd6a">

**Features to implement:**
- Bold
- Italics
- Underline
- Strikethrough
- Ordered list
- Unordered list
- Hyperlinks
- Clear formatting of selected text (last priority and stretch goal)

**Comment by mddilley** [comment]
@tillyw could you estimate? Also we could look into how to get this from TSX -> JSX

**Comment by tillyw** [comment]
closed with https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/gh/cityofaustin/atd-moped/1404
