### ISSUE TITLE
[Design] Build Prototypes

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#18397]
## Description
Now that we've synthesize themes and insights from the User Testing, we want to create UI design solution to helps solve the issues that users were having with the interactions in Moped. 

## Requirements
- Create [Figma doc](https://www.figma.com/design/gTKjSG5TDSS1TIofaMKPVh/Moped-Map-Design-Mockups?node-id=3-1936&t=QvHbPDFzmtyNUD90-1) for prototypes
- Share with Moped PM Mike and Patrick 
- Schedule regular review with M & P to get feedback and start thinking implementation

**Comment by patrickm02L** [comment]
## 8/1/24
Target deadline is Friday 8/9/24 to finish prototypes.

**Comment by olivialuk** [comment]
Prototypes are built and ready to be cleaned up for handoff and presented at Final Presentations. All documentation from this Issue can be found on this Figma[https://www.figma.com/design/gTKjSG5TDSS1TIofaMKPVh/Moped-Map-Design-Mockups?node-id=3-1936&t=0Eyb7EEq4QoU33S9-0](url). The Final Prototype is Located on the Wireframe/Ideation Page.
