### ISSUE TITLE
Design Documentation

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#18396]
## Description
Collect all artifacts into a single document for easy reference and handoff

## Notes
- See Madison's [Handoff folder](https://docs.google.com/document/d/17GzFQvCVijULwlf9o9hSYZESELwgJ1rc2-aEWSFZZgw/edit?usp=drive_link) from the 2023 Fellowship to see how to organize the documents.
- See Rebecca's [Handoff folder](https://drive.google.com/drive/u/0/folders/1qNkwwkaWeYVY8Ke_BZrwGb4dOipqGO8T) from the 2022 Fellowship to see how to organize.

**Comment by patrickm02L** [comment]
## 8/13
Edit [this document](https://docs.google.com/document/d/1ZPP2x5zybwEMCYERdsJmg2cQs-HlQw0woyIuQsjghQU/edit) to include your materials and resources.

**Comment by olivialuk** [comment]
All artifacts from CIF 24' Design Fellowship have been collected on this document[https://docs.google.com/document/d/1ZPP2x5zybwEMCYERdsJmg2cQs-HlQw0woyIuQsjghQU/edit](url). Final deliverables are at the top, and the rest of the in progress materials are organized by file type.
