### ISSUE TITLE
Scoping: TPW Admin SharePoint

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#18394]
**Scoping TPW Admin SharePoint needs**

https://cityofaustin.sharepoint.com/sites/TPWHub

- What is the Business problem you are trying to solve?
- Where does the content currently reside?
- What is the volume of documents?
- Who will have access to the content?
- How are documents organized right now?
- What other content might be stored on the SharePoint Site? (besides the documents)

**Comment by dianamartin** [comment]
@stephaniemoorer this is done, right?
