### ISSUE TITLE
Labels: Update settings.yml accross DTS repos

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#184]
Note: Most (all?) of these already exist in atd-data-tech. 

So the easiest way to do this might be:
1. [Add all to atd-data-tech](https://github.com/cityofaustin/atd-data-tech/labels). 
2. [Export to yml from the browser console](https://gist.github.com/MoOx/93c2853fee760f42d97f). 
3. Check against [the settings.yml version that we propagated to all repos last time](https://github.com/cityofaustin/atd-data-tech/blob/7a200e1491366e5fdd2530f8be694607195dca0f/.github/settings.yml) and make sure all labels that are being updated have an `oldname`. 
4. Re-run through each repo. 

**Add**
_Don't count on this being comprehensive; refer instead to the yml export from ☝️_
- Type: Operations — description: "Internal DTS planning and administration"
- Project: Mobility Project Database — description: "A comprehensive mobility project tracking platform for Austin, Texas."
- Project: Residential Parking Permits — description: "Online platform for residential parking permit applications, purchases, and renewals"
- Project: Inspector Prioritization Automation — description: "Automated prioritization of Right-of-Way inspections."
- Project: Data Lake 
- `Service: AMANDA`- will have to remove current service label and replace with this one on all of Tracy's stuff 
- 'Type: Product-Ops'

**Update**
- `Service: Apps` to `Service: Knack` (Will need to then filter out Tracy's Amanda stuff and apply👆...)

**Remove**

**Other**
- Remove comments about removing "Project" labels (safer just to propagate these in all the `settings.yml`s

**Comment by amenity** [comment]
Question, @TracyLinder @johnclary @dianamartin --
Would it be helpful to break out `Service: Apps` into Knack and AMANDA? Apps projects are so discretely divided between the two, and the "teams" are different. 

Thinking about this since I just updated our sprint planning invite to show all the relevant issues on the ZenHub board and have to filter out Tracy's issues to see the right stuff on the board. Not so much that this is time-consuming as that it leaves a potential gap for issues to slip through - e.g. an issue comes in, receives the `Service: Apps` label but isn't assigned and therefore isn't surfaced in anyone's sprint planning.

**Comment by dianamartin** [comment]
@amenity this hasn't bothered me, but I can see it being an obstacle when organizing for sprint planning sessions. I like the ease of only having one label, but it others are in consensus then we could change it.

**Comment by amenity** [comment]
Discussed ☝️ in Knack apps sprint planning and it seems like different labels would make sense.

**Comment by amenity** [comment]
@johnclary @dianamartin @TracyLinder to keep them short we could do - `Service: Knack` and `Service: AMANDA`

**Comment by johnclary** [comment]
👍

**Comment by johnclary** [comment]
Just noting here that I've added a few new labels to `atd-data-tech`:
- Project: Micromobility Privacy
- Project: Paperless Hiring
- Workgroup: DR - Development Review

**Comment by amenity** [comment]
Have discussed that we really are using `Service` to translate to `Team`... Whether or not we change the labels to reflect that, we should separate Apps into Knack and AMANDA.

**Comment by dianamartin** [comment]
Why haven't we changed `Service` to `Team`? I'm fine with the change if everyone is too.

**Comment by johnclary** [comment]
Queuing this up for sprint 7. We will need to make a tiny update to the DTS > Github integration.

Also, I our `settings.yml` is out of sync with labels that we've manually created in `atd-data-tech`. We should reconcile that so that we're keeping our production labels in version control.

Also, I'd like to add: `Type: ETL`.

**Comment by johnclary** [comment]
Bumped to Sprint 8. We can do it!

**Comment by amenity** [comment]
Moving to mono-repo, no longer applicable.
