### ISSUE TITLE
REQ0193795 - SCTASK0442307 - 10 iPad mini's (6th Generation) for timeclocks

### ISSUE THREAD

**Issue by scottreedy** [cityofaustin/atd-data-tech#18406]

**Comment by scottreedy** [comment]
9 iPad mini's for timeclocks 07/25/2024 ordered through the wireless shop.

**Comment by scottreedy** [comment]
Received in 07/31/2024
iPad mini (6th Generation)
FirstNet order #55-809000005253724
SCTASK0442307
order\ship date 07/26/2024

737-382-4810  COAW74074	IMEI: 359383683681420  ICCID: 89011003330154950835 s/n: H64WY9356M
512-552-4712  COAW74002 IMEI: 359383683111048  ICCID: 89011003330154950868 s/n: LL69V23TW6
737-382-4804  COAW73999 IMEI: 359383682861197  ICCID: 89011003330154950819 s/n: KFFVW3VJ4K
737-382-4815  COAW74001 IMEI: 359383683294695  ICCID: 89011003330154950884 s/n: DCL4G77Q6V
737-382-4813  COAW74004 IMEI: 359383683638198  ICCID: 89011003330154950801 s/n: FYLWVJG6JY
737-382-4808  COAW74003 IMEI: 359383683522277  ICCID: 89011003330154950827 s/n: JW7H737RMY
737-382-4801  COAW74000 IMEI: 359383682598666  ICCID: 89011003330154950793 s/n: JCYD002QHG
737-382-4814  COAW74073 IMEI: 359383682863060  ICCID: 89011003330154950876 s/n: L9Q36G46FL
737-382-4806  COAW74005 IMEI: 359383682765208  ICCID: 89011003330154950850 s/n: KT06NDHWT4
737-382-4812  COAW74075 IMEI: 359383682573354  ICCID: 89011003330154950843 s/n: H4K6JYD0GK

**Comment by scottreedy** [comment]
@dianamartin I can send this ticket to Susanne, but don't know what to tell her about configs.

**Comment by dianamartin** [comment]
@scottreedy we might need to create a new user group. We can talk to the stakeholders tomorrow, we meet with them at Townview.

**Comment by dianamartin** [comment]
# 7/31/24
Scott and I talked and he's going to put them in the DTS Closet
