### ISSUE TITLE
HR Sprint Review Scoping Pre Interview workflow

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#18405]
### Objective 
Discover workflow completed by HR team prior to the interview to determine if any of the processes can be automated in Knack.

### Agenda
https://docs.google.com/document/d/1ZLonGnU0gVA2emEK5zlkWLpKt1zjGzstkDfz3x3Bn4I/edit#heading=h.am5w5hu92ha
[------](url)
- [ ] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by stephaniemoorer** [comment]
Good workflow discussion. 
Diana documented workflow in Miro
https://miro.com/app/board/uXjVPpGwiwA=/

**Comment by stephaniemoorer** [comment]
@dianamartin attached is a copy of the HR Hiring Packet spreadsheet and Applicant report from eCareer
[Applicant List Report from eCareer.xls](https://github.com/user-attachments/files/16459237/Applicant.List.Report.from.eCareer.xls)
[HR Digital Interview Hiring Packet - Sample 1.xlsx](https://github.com/user-attachments/files/16459239/HR.Digital.Interview.Hiring.Packet.-.Sample.1.xlsx)

For my own understanding I created some data boxes to reference where data was coming from  in the beginning of the workflow.
![image](https://github.com/user-attachments/assets/bdffa75e-e0de-49ce-a633-92a54d26c9b8)

Your calendar is pretty full next week if you find some time I would like to do a quick debrief/work session.

**Comment by dianamartin** [comment]
# 8/6/2024
Did some discovery work to see if we're able to auto-generate an interview when a user creates a Milestone for "INTERVIEW - Schedule Date". 

- [x] Made updates in Test "TEST | 22 MAR 2024 | TPW Hire"
- [x] On `pcn_date_tracking` table, created connection with `interview_management`
- [x] Add Record Rule on "Add Milestone Notes" to create new "interview" record
![image](https://github.com/user-attachments/assets/0f5ac08b-80b9-4e99-8f8a-106bac70b40a)
- Can confirm that it does work, did three attempts in the Test environment
![image](https://github.com/user-attachments/assets/e78848aa-4c66-4905-bda5-27de0b661d27)

When we talk to HR on Monday, we can show them this function and get their confirmation they want this in the Production Environment.

**Comment by stephaniemoorer** [comment]
After much discussion during the Sprint Review stakeholders want to see the entire interview process automated not just the Interview itself. Using their existing excel spreadsheet we will work on automating the pre interview workflow first. 
#18598 
https://miro.com/app/board/uXjVPpGwiwA=/

**Comment by stephaniemoorer** [comment]
**8/26/24** 
HR approved of the auto-generating an interview when a user creates a Milestone for "INTERVIEW - Schedule Date".

We will continue building out the Interview Packet process in other issues.

Closing this issue
