### ISSUE TITLE
LM Folder needs to be added to the Issue Expiry Date Security group in AMANDA (SCTASK0442538)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#18404]
The LDE team needs to be able to update the expiry date on the LM folder in order to complete certain job functions on LM Permits. 
The LM Folder will need to be added to the Issue Expiry Date (60040) Security group in AMANDA. This will need to go to CTM

**Comment by Nadin-Nader** [comment]
This has been sent to the CTM Team to be updated in AMANDA under **SCTASK0442538**

**Comment by Nadin-Nader** [comment]
This has been done and the users are good to go. closing

**Comment by TracyLinder** [comment]
@Nadin-Nader Kathy says this update didn't work for her.
