### ISSUE TITLE
[Enhancement] Add bicycle types to fleet_vehicles table

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#18424]
## Description
Add 8 bicycles to the `fleet_vehicles` table. Jasmine sent a list for us to add.

## Notes
[Bicycle spreadsheet](https://cityofaustin-my.sharepoint.com/:x:/g/personal/jasmine_lara_austintexas_gov/EYFagxDzOMVMnbkNrL9v-R8Btn_mkBArJspRb23bCQsBzA?email=Patrick.McDonnell%40austintexas.gov&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1722278108616&web=1)

**Comment by patrickm02L** [comment]
## 7/29

Met with @susannegov to get some guidance on adding Bicycles types. She walked me through adding them to the table, and I manually added the following bicycle records: 205736, 205737, 205739, 205740, 20541, 205742, 205743, 205744

Edited Fields in `fleet_vehicle` table: 
- Vehicle Make
  - to include Cannondale, Trek options
- Vehilce Model
  - to include N/A option
 
### Note
- Initially tried to add the bicycles through the Knack UI, but the new record didn't populate in the Manage Vehicles table. Realized that the Vehicle Status, which is not in the `Add Vehicle` form needed to be set to "In Service" for it to show up in the table. Recommend when `Service Date` is added the `Vehicle Status` automatically defaults to In Service.
- Should move Category to the top under Vehicle ID, and then create a rule that hides the `Vehicle Model` and `License Plate` fields on the form since they're N/A

**Comment by patrickm02L** [comment]
@dianamartin can you look over this just to make sure it's working like it should be.

**Comment by dianamartin** [comment]
# 8/2/24
@patrickm02L Reviewed the records you entered in the system and they look good to me.
- [x] Updated the "Add Vehicle" to be based on "Category" selection
- [x] Added display rules for "Add Vehicle"
![image](https://github.com/user-attachments/assets/b6e11e81-027c-4f3e-8278-40ffeb931ab8)
- [x] Added display rules for "Edit Vehicle"
![image](https://github.com/user-attachments/assets/16892aff-fe38-40b7-acde-72a5dd789b81)

**Comment by patrickm02L** [comment]
h/t @susannegov for you're help on this!
