### ISSUE TITLE
Deploy EC2 sandbox instance for data model migration tasks

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#18449]
Deploy an EC2 instance that we can use for data migration tasks as we launch the new data model. Ideally it would have the same access and networking as the existing RDS bastion host.

**Comment by frankhereford** [comment]
We're cooking with gas now.

* 32 cores, 64G ram, 256G in `/home`. 
* PG clients installed. 
* `btop` installed. 
* `psql`/`pg_dump` automatically connects to the data model database when run with no arguments.
* static ip + dns
* works to stop and start the machine when not in use via the console.
