### ISSUE TITLE
[Traffic Register] Add two fields for displaying to/from data that's missing offset data

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18471]
Reviewed during a sync and decided we need to add two additional field to account for missing offset data (example when the from and to streets start with "of"
- [x] Add additional field for displaying to and from fields missing the offset data
- [x] Add additional field that chooses between the current display and the new display based on whether the offsets fields are blank

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/17781#issuecomment-2251340542_

**Comment by ChristinaTremel** [comment]
Will be looking at implementing these formulas: 
- New Text Formula: `From Street + Street Prefix (N,S,E,W)`
- New Text Formula: `To Street + Street Prefix (N,S,E,W)`

**Comment by ChrispinP** [comment]
NonOffset and Final Display fields created. Conditonal rules set the Final Display based on if the Offset Distance is blank or not to either the NonOffset or Shorthand Display.
![image](https://github.com/user-attachments/assets/1a7cef2c-facb-4d9f-bd3a-aea330396815)
![image](https://github.com/user-attachments/assets/d99ff04c-c547-4d21-a431-84e024530dbc)


Updated the Advanced Search pages and Regulation Details page so they now show the new Final Display fields. After the records are updated, the new display values will show.

Complete, pending review

**Comment by ChristinaTremel** [comment]
- Added `txt of` text formula field and included that in the existing display formulas
- Added `From Street NonOffset Display` text formula field to exclude offset details and includes `From Street + From Street Direction`
- Added `From Street Final Display` short text field with conditional rules described by Chrispin above 
- Added `To Street NonOffset Display` text formula field to exclude offset details and includes `To Street + To Street Direction`
- Added `To Street Final Display` short text field with conditional rules

**Comment by ChristinaTremel** [comment]
Reviewed this during the sprint review with TED! Closing this out.
