### ISSUE TITLE
IT Support: Remove switch from Lab computers area

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#18494]
ST. ELMO

## Device & User Information (first name and last initial, no last names)
Lab computers at St. Elmo

## What's the problem?
Under the tables there a switch. 

Could you take the ethernet cables out of that switch and connect the two desktops to the ports on the floor? You might need to activate the ports.

**Comment by Vaishnav1397** [comment]
Will make sure to check on it

**Comment by Matthew-M-TPW** [comment]
removed switch activated ports
