### ISSUE TITLE
Tear down Moped test deployment resources

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#18505]
To comply with the BitSight security recommendations, we've been told that we need to add security headers to our Moped test deployment. Since we don't use this deployment anymore, we should tear down the remaining pieces of it so this item will drop off our list from ISO.

See [this doc](https://docs.google.com/document/d/1Mxfro3xBrnlkiBj0Z1OHTARciADlfmBfHkP27eJ2PzQ/edit?usp=sharing) for more details.

- [x] Remove record in Route53
- [x] Remove [CloudFront distribution](https://us-east-1.console.aws.amazon.com/cloudfront/v4/home?region=us-east-1#/distributions/E2MEG0I5E6VQWJ) that it points to
- [x] Remove [secrets entry](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=ATD_MOPED_API_CONFIGURATION_TEST&region=us-east-1) - might be worth checking the repo for references, but this mentions Heroku so it feels very outdated
   - [Another secret that looks outdated and removable](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=ATD_MOPED_EVENT_SQS_ENV_TEST&region=us-east-1) - also has a Heroku endpoint in the secret
- [x] While we are at it, [this prod SQS secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=ATD_MOPED_EVENT_SQS_ENV_PRODUCTION&region=us-east-1) and [this staging SQS secret](https://us-east-1.console.aws.amazon.com/secretsmanager/secret?name=ATD_MOPED_EVENT_SQS_ENV_STAGING&region=us-east-1) are also outdated. We no longer use SQS for any of our applications.
- [ ] Anything else?

**Comment by frankhereford** [comment]
Hey @mddilley 👋 

All of this is done. The four secrets that you identified in the issue have been scheduled for deletion in 7 days. It's kinda cool - the secrets manager makes you have a test period while it won't respond, but still remembers the data.

Thanks for your time today this afternoon. When I called you, I had given myself the wrong understanding that this work was related to when you and i worked on the moped test deployment pipeline. I 100% see now that -- of course -- this is all about the ISO's request. 

Last thing - I'm going to add you to this issue right before I close it because you totally did all the work -- allll of the work -- when you scoped it. It's the perfect check-list, and thanks for letting me do it! 🙏

**Comment by frankhereford** [comment]
There was something else. I just removed (after making a final snapshot) the RDS instance that served as the database for our moped test deployments. 👋 

<img width="572" alt="image" src="https://github.com/user-attachments/assets/5ead8c22-cf93-4302-aebd-df2866ee18dd">

**Comment by frankhereford** [comment]
Found another item -- the VPC itself. `vpc-080460d8b02988e02 / moped-test`. I spoke with @mddilley and I'm going to run this one down next sprint or this one if i get my plate cleared. 😅 Thanks Mike!

**Comment by mddilley** [comment]
@frankhereford I was going through my notes from the week, and it reminded me that we talked about CloudFormation in relation to zappa during refinement the other day. Then, I realized that we used it in the Moped test deployments so I'm linking some more things that could be from the original Heroku test deployment or the newer full stack ones that we worked on.

- [CloudFormation stack](https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/resources?filteringText=&filteringStatus=active&viewNested=true&stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A295525487728%3Astack%2Fatd-moped-api-moped-test%2F17e79000-bff0-11eb-89de-0a8267cebc39)
   - This stack could help point to some resources that it created 
- [API Gateway](https://us-east-1.console.aws.amazon.com/apigateway/main/apis/kckdenznli/resources?api=kckdenznli&region=us-east-1)
- [Lambda](https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/functions/atd-moped-api-moped-test?tab=code)
- [IAM user](https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/users/details/atd-moped-test-instance-deployment?section=permissions)
- Maybe some IAM roles too

**Comment by frankhereford** [comment]
Thanks again @mddilley for the superb list. I got everything you listed. That was very helpful to see the CloudFormation stack. It was also interesting to get into the API gateway, if only to remove things, because there is a lot in there we don't use that looks useful to me. Thanks again!
