### ISSUE TITLE
Create set of redacted crash narratives for intersection visibility research

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#18522]
Michael K. has asked us to provide him a set of 5k-10k crash narratives that can be shared with their contractor who is assisting with research related to pedestrian-involved crashes at intersections. 

This will involve:
- working with the stakeholder to define the correct DB query
- using our narrative redaction tool that Charlie created

**Comment by johnclary** [comment]
I cc'd Xavier on our email thread and asked if could help with the query:

> Xavier, would you be able to help craft a query for this, or translate what's being requested to DB columns so that I can write the query?
> 
> > ten years crashes involving pedestrians at intersections on Level 1 and Level 2 streets

**Comment by xavierapostol** [comment]
@xavierapostol

**Comment by johnclary** [comment]
We've received a set of narratives to redact. @Charlie-Henry will take it from here 🤖

**Comment by johnclary** [comment]
I sent Michael the results of Charlie running the set of narratives through the LLM. TLDR, Michael will need to redact most of the narratives by hand.

> Charlie was able to run our narrative redaction tool on this dataset. The tool works by flagging crashes narratives that may contain any of the kinds of personal data that we itemize in [our privacy policy](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1hxucInTvksv17U8DC5iQz8sjhkwOfjj5INjwQTR0aGI%2Fedit%3Fusp%3Dsharing&data=05%7C02%7CJohn.Clary%40austintexas.gov%7C586e07b58e28407878f208dcbc80a325%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638592507902748004%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=56txZUj2nr7CzRmJIeJuIX1ssjxoi6vvm1OfutYOH0k%3D&reserved=0), which is itself a list copied from Texas state law. 
> 
> Unfortunately, the tool flagged 150 of the 240 narratives for potentially containing personal data. In the past we have been working with much larger datasets, so it wasn't a big deal for us to lazily discard half of the rows in a dataset. In this case, it is unfortunately going to take manual review of those narratives in order to be safe for them to share.
> 
> In the attached CSV, the last five columns indicate if the AI model flagged the narrative for containing some kind of personal data. If the last column, "none of the above", is true, then the narrative is safe to share. 
> 
> As you can see by spot checking the narratives, the model errs on the side of caution in a big way. Many of the narratives it flagged can probably be safely shared, but they will require your manual review. You can choose to either edit the narratives directly by removing sensitive data, or you can exclude them from your dataset. Again, the list of "personal data" in the privacy policy is the kind of information we must weed out.
> 
> I'm sorry that we weren't able to be more helpful in this case! Let me know if I can clarify anything.
