### ISSUE TITLE
[Enhancement] Update vehicle addition form to filter fields based on selected vehicle category

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#18537]
## Description

When adding a new vehicle, the form currently displays all fields even if they are not relevant for the selected vehicle category (e.g. license plate field for a bicycle). 

Update the form so that when a specific vehicle category is selected, the form fields are filtered to only show the relevant fields for that category.

**Comment by patrickm02L** [comment]
@dianamartin please make notes about this completed work

**Comment by dianamartin** [comment]
# 8/14/2024
Work was completed 8/2/24:
- Referenced here: https://github.com/cityofaustin/atd-data-tech/issues/18424#issuecomment-2266202672

On the "Add Vehicle" form/page
- Category was used as a toggle to determine if "non-bicycle" fields would show 
- Added display rule
  - Category - `Bicycle`
  - Show/Hide - `Vehicle Model`
  - Show/Hide - `License Plate`
  - Show/Hide - `Vehicle Year`
- Updated "Edit Vehicle" form/page
  - Added display rules for "Edit Vehicle"
![image](https://github.com/user-attachments/assets/fdeaf6c9-d93c-4015-a2e8-411b7f63e60f)
