### ISSUE TITLE
Feedback MSP App Usability Test 08/08

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#18567]
# Notes as Customer
- "Pretty easy to sign up"
- Didn't receive confirmation email that account was created - Susanne
- SSN input issues for iPhone - Paul
- Users report that they can't click review until docs are attached. Maybe make it clear that they cannot click review until attachment is submitted
- People asking if they can pay online
- Need a confirmation on the site (not just email) that it is submitted
- Desire to see if it is possible to change from on site to in-person
- Chrome - no issues
- When selecting "on my own" it's not clear to the customer that they need to attach notarized documents to the application
- When the form question asks "Are you a US citizen" maybe include a short blurb of docs required
- Make it clear to applicant that it will save their progress when clicking next page
- ~~For a customer, have button for edit and submit before `In-Progress - Payment and Notary`~~ just add it to review page instead and do a final confirmation see next list
- Add a final submit confirmation and very clear language to the customer that edit is disable after submission
- Knack BUG: When hovering submit button for file attachment in table, it shows a "error" icon
![attachfile](https://github.com/user-attachments/assets/65698427-3c78-4361-93a2-31d34e65e657)

# Notes as Reviewer/Cashier
- ~~For the reviewer, they are unable to attach document of notarized page~~ - FIXED
- For cashier, set that they paid for the application 
- Cashier option  to select if they paid application and/or notary fee.
    - app fee - $25.00
    - notary fee $6.00
- For edit, allow reviewers to edit or add attachments
- For a reviewer, allow them to view the application in `Payment Pending` status
- For the cashier, remove filter menu to all instead of by application status
- In progress - Notary Required added to Reviewer menu

# Future Considerations
- Reviewer automates when approved it sets the date of expiration to 2 years after approval date
- For temporary Texas permit (if driver license is only for out of state), we give them 90 day conditional license
- Applicants can renew 30 days before date of expiration
- Scenario - a person applies for 90 day conditional permit every year for special events such as SXSW or ACL
- Do you have a state driver license for "Texas" what ID
- Need to flag a conditional can only reapply (cannot renew). A non-conditional can renew only. The difference between the two is that the non-conditional do not have to retest which is very important for folks.

**Comment by susannegov** [comment]
# 08/08
- [ ] In Permit Application, copied My Account views to Permit Application page for the logged in account

**Comment by susannegov** [comment]
# 08/12
- [x] Added `application_transactions` object table and grid in cashier page
- [x] Removed filter menu in manage payments page and sorted applications by `Submitted date`

**Comment by susannegov** [comment]
# 08/13
- [x] Print Application buttons added for reviewer
- [x] Updated JS code for print buttons for reviewer and CSS code for print formatting

**Comment by patrickm02L** [comment]
## 8/14 Micro-mobility Launch Check-in

### Things that were updated
- Cancel button was added instead of using inline editing
- Notarized Application in Add attachments to the Notarized Section
- Add a yellow banner that instructs user what needs to be done before clicking Review
- Adding yellow background to supplimental documents that have not been modified
### Action Items
- Add editing capabilities
- Once approved no editing
- Social Security last 4 only

**Comment by susannegov** [comment]
Merged PR
