### ISSUE TITLE
Add `is_deleted` column to Moped <> Data Tracker sync

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#18577]
When we synchronize project data between the Moped database and the Data Tracker `projects` table, we don't consider whether projects are deleted or not (`is_deleted = true`). This is limiting the ability of the Data Tracker `projects` table rows to populate tables and dropdowns in Data Tracker with active (non-deleted) projects only. It is also causing links to appear in Data Tracker that point to deleted projects.

To improve this, we should add the `is_deleted` column to the data sync so that deleted projects can be filtered out on the Knack builder side like we do in the Moped UI. 

Examples of links to soft deleted projects can be found through [this link](https://builder.knack.com/atd/amd/records/objects/object_201?builder_table_filters={%22match%22:%22or%22,%22rules%22:[{%22field%22:%22field_4133%22,%22operator%22:%22is%22,%22value%22:%22266%22},{%22field%22:%22field_4133%22,%22operator%22:%22is%22,%22value%22:%22314%22},{%22field%22:%22field_4133%22,%22operator%22:%22is%22,%22value%22:%22373%22},{%22field%22:%22field_4133%22,%22operator%22:%22is%22,%22value%22:%2282%22},{%22field%22:%22field_4133%22,%22operator%22:%22is%22,%22value%22:%228%22}]}
).

We should:
- Coordinate with the Apps team to add the boolean `is_deleted` column to the `projects` table of Data Tracker (`object_201`) **AND** the latest test copy of the app - [Builder link](https://builder.knack.com/atd/amd/schema/list/objects/object_201/fields) - ask Christina
- Update the [Moped <> Data Tracker sync ETL ](https://github.com/cityofaustin/atd-moped/tree/main/moped-etl/data-tracker-sync) to populate this new Knack column with the value from the Moped database
- Backfill the values for projects in the `projects` table of Data Tracker (`object_201`)
   - [Here is the query in the ETL code](https://github.com/cityofaustin/atd-moped/blob/49feca21a2b80ce53d5113735dd08b01725d8f6d/moped-etl/data-tracker-sync/process/queries.py#L35-L51) that is used in combination with the Airflow last successful run date to determine what to update
   - Or, ask someone on the Knack team to import a Moped export with the is_deleted values included

**Comment by mddilley** [comment]
@ChristinaTremel feel free to edit the issue description if there is anything that i missed. thanks for bringing this to the sync the other day! 🙏

**Comment by ChristinaTremel** [comment]
- I just reminded myself about issue #18353 that was submitted by Ivonne a couple weeks ago and is directly tied to this issue! I'm going to close out 18353 and note that you researched and are going to address this issue with the `is_deleted` column. And I already let Ivonne know that we're working on it!

**Comment by ChristinaTremel** [comment]
Added `Is Deleted` boolean field to the [projects](https://builder.knack.com/atd/amd/schema/list/objects/object_201/fields) object in Knack! ✨

**Comment by mddilley** [comment]
@ChristinaTremel Thank you!!!! could this be added to the latest test app as well?

**Comment by ChristinaTremel** [comment]
Added the field to the projects object in the `TEST | Austin Transportation Data Tracker | 29 JUL 2024` app!
