### ISSUE TITLE
Develop - HR Digital Interview Pre Interview Create Posting Analysis

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#18598]
**8/14/24**
After much discussion during the Sprint Review stakeholders want to see the entire interview process automated not just the Interview itself.
During work session with Diana we divided the process into stages 

**- Pre Interview**
Posting Information (posting analysis)
Applicant List
Candidate Screening Matrix
**- Interview**
Variable Schedule
Interview schedule
Interview Guide
Interview
**- Post Interview** 
Minimum Quals
Zone and Offer
Zone Determination

**Focusing first on Pre Interview Create posting**

**Comment by stephaniemoorer** [comment]
**Create Posting Information/Posting Analysis**

![image](https://github.com/user-attachments/assets/3e4cb499-2562-4312-ae8e-fe9651d70ad8)
![image](https://github.com/user-attachments/assets/15b57c75-b507-4307-997b-52f679c017a3)

- Create trigger from PCN Management to Create New Posting
- Create New Posting populating some data from the Vacancy Report (highlighted in blue)
- Pay Scale data populated from Pay Grade spreadsheet - entered manually?
- Separate Minimum Quals and Preferred Quals table - copied manually from eCareer
- Hire Descriptions has standard language 
      - Regular New Hire
      - Temp Hire
      - Promotion

**Comment by dianamartin** [comment]
# 8/20/24
Stephanie and I synced our new plan for building out the interview packet functions/forms. 
- [x] created new table - `job_posting_management` table
- [x] created new table - `job_preferred_qualifciations` table
- [x] created milestone trigger on "Add Milestone" form
  - to create a new job posting record when milestone "POSTING: Open Date" was selected
  - we tested this in PROD, and it worked
- [x] Created new page "Posting Management" 
- [x] Added a table
- [x] Added a details page
- [x] Added an edit form
- [x] Added new form for "Preferred Qualifications"
- [x] Added table for Preferred Qualifications
- [x] Created button/page for Minimum Qualifications (print previewable)

**Comment by stephaniemoorer** [comment]
@dianamartin a few suggestions:

- [ ] the Posting Type in Edit Job Posting should have these values in the drop list

![image](https://github.com/user-attachments/assets/c90d15d3-58e1-46f2-a523-398ba6dba0a4)

- [ ] Should Edit Job Posting button be moved above Pay Scale?

- [ ] In Edit Posting page format the Zone fields so the $ is accepted ex. $36.87
Error message:
Values entered in number and currency fields must be numeric
Zone I (0-4 Yrs Exp)
Zone II (4-7 Yrs Exp)
Zone III (7-10 Yrs Exp)
Zone IV (10+ Yrs Exp)
5% Above
Max

- [ ] Hiring Manager should be added to Job Posting Details and populated from PCN management
- [ ] Change HM to Hiring Manager

![image](https://github.com/user-attachments/assets/4e9f7751-3a00-45d1-a57b-6cd97069a441)

- [ ] After Hiring Manager is added, can this be removed from Edit Job Posting?

![image](https://github.com/user-attachments/assets/b8d6571b-827c-4b3e-90a1-a3c76fd72cc3)

- [ ] In Add Preferred Qualifications after you enter Submit can the window close without having to select the X

**Comment by dianamartin** [comment]
# 8/20/24
- Susanne and I tested all ways to create an Interview Schedule
![image](https://github.com/user-attachments/assets/421ce4f2-265f-4639-91cf-6ae850723cfa)

**Comment by stephaniemoorer** [comment]
8/26/24 
Review with stakeholders during HR Sprint Review

**Comment by stephaniemoorer** [comment]
@dianamartin did some testing on posting 118701. 
Below are some updates

- [ ] Edit Posting Page / Hiring Type - select the Info button, then select the back arrow. All the data on the Edit Posting page is blanked out

- [ ] Job Posting Details - position the buttons to match the workflow:
 Edit Job Posting - Add Preferred Quals  - Edit Applicants - Candidate Screening Matrix

![image](https://github.com/user-attachments/assets/e27465b7-ca60-4287-b999-9412a81c354d)

- [ ] Edit Applicants Page - 
Add Primary Phone
Last name/First Name/Full Name not populating in table
Change Dept Employee In Good Standing (should be on Candidate Screening Matrix) to **Scheduled for Interview Yes/ No**

![image](https://github.com/user-attachments/assets/9fce78c2-e593-40de-93e4-a13f70a4f807)

- [ ] Candidate Screening Matrix - Populate info from Applicants table
Move Forward to Interview
Full Name
Last Name
First Name

**Comment by stephaniemoorer** [comment]
Ready for review in Sprint Review 9/9/24

**Comment by stephaniemoorer** [comment]
@dianamartin I asked Tina about the Milestone: POSTING - Posting analysis sent to Hiring Manager. 
Wanted to know what the process is for this milestone. Below is her reply.

- Sounds like we need the ability to email the posting to the Hiring Manager and have them provide feedback

Tina's Reply:
We used to email hiring managers a posting analysis form that they would complete, and then we would build the posting from there.

 

We don’t use those forms anymore; we typically email the hiring manager the last posting (in WORD format) that was used for that particular title and ask if they have any changes to the following areas; Notes to Applicants, Preferred Qualifications and Posting Questions.

 

We still use that milestone when we first send the hiring manager the previous posting for review and edits. They sometimes send us the edits in an email or will make edits to the posting we sent to them.

**Comment by stephaniemoorer** [comment]
**9/11/24**
Additional information from Jennifer: 
To further this explanation, the Posting Analysis is part of the official hiring package, but HR builds the form on behalf of the hiring manager. We build it from the data Tina mentioned below.

**current process:**

- using the last posting for a particular title create Word doc
- email word doc to Hiring Manager
- ask if they have any changes to the following areas:
Notes to Applicants - **this is on the eCareer job posting / we are not populating this now**
Preferred Qualifications - **we have this on the Min Quals page**
Posting Questions - **Supplemental Questions from eCareer job postng / we are not populating this now**
- Use Vacancy Report Milestone: Posting analysis sent to Hiring Manager 
- Make any edits from the Hiring Manager

Questions:
- Do we add to the Add Preferred Quals page and have space to add the 
Note to Applicants and Supplemental Questions since they are also copy/paste from eCareer?

Do we add the Notes to Applicants and Supplemental Questions to the Minimum Qualifications page?

**Comment by stephaniemoorer** [comment]
@dianamartin 

In Job Posting Details / Edit Job Posting 
- [ ] if I select COA Compensation or Hiring Type info button all the previous fields I put information in gets blanked out
- [ ] Hiring Type should not be Required - we don't know the Hiring Type until post interview

Do you think you can look into this before Monday Sprint Review?

**Comment by stephaniemoorer** [comment]
**9/24/24**
Reviewed with stakeholders during Sprint Review
Stakeholders approved of the Job Posting page with some enhancements. Created new issues for the enhancements issue #19166
