### ISSUE TITLE
Roll out HR AVL Procedure in Knack HR Portal

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#18597]
Stakeholders will discuss roll out plan and let us know.

- [x] Make a new button for the AVL form under "My Forms"

**Comment by dianamartin** [comment]
# 8/19/24
- Nedra emailed and wanted access to the AVL form and the AVL Procedure
- Realized only accessible to "knack admin" roles
- Updated the permissions
- [x] Added new button on "My Forms" to include new button for "AVL Procedure"
![image](https://github.com/user-attachments/assets/78b1d21c-1798-4ac8-9ee7-c6faf3c65b66)
- [x] Added count field in `accounts` to count the number of related AVL forms to an account, named it `# AVL Procedures`
- [x] Added page rule to not show the table if no AVL procedure is filled out
![image](https://github.com/user-attachments/assets/5275b89e-0c40-4caa-9389-6865c68753f1)

**Comment by dianamartin** [comment]
@stephaniemoorer Ready for review. I can email Nedra the update.

**Comment by stephaniemoorer** [comment]
AVL Procedure was successfully rolled out 8/23/24

Closing this issue
