### ISSUE TITLE
Develop HR Digital Interview Post Interview Zoning

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#18635]
![image](https://github.com/user-attachments/assets/1d08e685-28e1-4d91-a786-d9920b623f18)

**Comment by dianamartin** [comment]
# 8/29/24
Stephanie and I worked on the Zone Determination Form. Here is the prototype
![image](https://github.com/user-attachments/assets/e843eb04-3351-4211-acbe-0ddf1c55aeeb)

**Comment by dianamartin** [comment]
# 8/30/2024
- [x] Created new page "Offer Letter"
- [x] Added field `Offer Date`
- [x] Added field `Supervisor Signature Offer Letter` - Paragraph Text
>this is the area where the Supervisor would put their signature and sign it at the bottom of the letter

## Prototype of Offer Letter
![image](https://github.com/user-attachments/assets/3cc187a6-8347-43fc-bf39-0bd0a8a33d3b)

**Comment by stephaniemoorer** [comment]
Ready for review at Sprint Review 9/9/24

**Comment by stephaniemoorer** [comment]
9/24/24
Reviewed with stakeholders during Sprint Review.
Created new issue for enhancement to calculating months for Related Job Experience.
Issue #19167 
Closing this issue
