### ISSUE TITLE
Combine App Admin & Account Management into single Manage App dropdown

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#18630]
Would like to simplify the top navigation for ROW Portal & TDS Portal similar to Traffic Register to combine App Admin tab and Account Management tab into a single dropdown.

![image](https://github.com/user-attachments/assets/08355e87-d2ef-4d80-b63f-791015e8b049)
![image](https://github.com/user-attachments/assets/db9cd433-f84f-4285-8a64-d4f772db7571)

This will free up top navigation space and create a single standardized place to manage app content & accounts

**Comment by TracyLinder** [comment]
Approval from TDS to do this work ✅

**Comment by ChrispinP** [comment]
The updated dropdown menu is now live

Complete, closing
