### ISSUE TITLE
Build 3-1-1 Service Request Activities dashboard

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#18631]
### Start with the 3-1-1 SR Response dashboard as a template
- [Miro board](https://miro.com/app/board/uXjVK1r3GCE=/?moveToWidget=3458764597931285131&cot=14) with dashboard mockup and design notes
   - [Mockup](https://www.figma.com/design/K2A9albkGRJVx3pob3WyFX/Dashboards?node-id=38-154&t=deKY5TtkwOvmbcL1-1) designed in Figma
- Use the [3-1-1 SR Response](https://app.powerbigov.us/groups/me/reports/3ed8a2de-d354-464e-9bb2-af9b1a128fd6/ReportSection688d4a48f7221139d265?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f) Power BI dashboard as the design starting point
- Add the table from the [SR Activities Random Sample](https://app.powerbigov.us/groups/me/reports/7c2b059f-450f-43a1-ab7d-24f2df16a90d/bf9c9a9eb089dd458a03?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f) Power BI dashboard
- Bring in the Socrata [311 Activities](https://datahub.austintexas.gov/Transportation-and-Mobility/311-Service-Request-Activities-Austin-Transportati/cqc3-f6xh/about_data) dataset
- **Instead of pulling 10 random samples (manually) per type within the last 30 days, pull all SRs (with the Activities dataset) per type**

#### Headings
- Use the same heading font, color, and size as the SR Response Dashboard
- Use the text from the design mockup 

#### Filters
- Use dropdown filters like the SR Response dashboard

#### Visual graphs and charts
- Add visuals for
   - Percent of SRs with Detailed Communication 
   - Number of Days Until First SR Activity Completed
   - Average Number of Activities per SR (or would median be better?)
   - Average Time an SR Is Open (or would median be better?)
- Note that the design mockup includes two defined spaces for visuals, but these are just placeholders and you can use whatever size works best for the layout 

#### Activities table
- New order of columns
   - SR #
   - SR Type
   - Days Until First Activity
   - Days Open
   - Total Activities
   - Detail Included 
   - Date Created 
   - Date of First Activity
   - Date Closed
   - Completed On Time 
   - Method Received 
- Use simpler icons for the green checkmark and red x under Detail Included
- Tweak the date/time format to make it simpler 
   - Use 24 for the year in the dates
      - 6/24/2024 --> 6/24/24
   - No seconds in the times
      - 9:34:50 PM -->  9:34 PM
- Note that the table size in the design mockup is not set - use whatever size works best for the layout
- If there's room between the end of this table and the side of the dashboard, add a section with a link to the SR Response dashboard 

#### Descriptions and SLAs
- Move the Description and Service Level Agreements to another resource page and show it as a table

**Comment by katelunceford** [comment]
Another idea for a visual:
- Average (or median?) Number of Activities per SR

**Comment by susannegov** [comment]
# Published Pages
- Stats
- Map
- About
- Found the "Service level agreement" sheet from OPM
- I didn't include Fiscal Year since currently the datasets for SRs and activities are all filtered to relative last 30 days (for performance reasons). I can modify it to changed
- The matrix visual below is filtered to random 10 SRs and changes when the viewer refreshes the report
- Map is based on SR Location
- Missing Council District/EAZ type currently
- I put the # of days for first activity in 4 bins currently.
   - Less than a day
   - 1-5 days
   - 6-10 days
   - Over 10 days

**Comment by susannegov** [comment]
# Changes
- Added `SR Status` to matrix visual
- Added column `Status Colors`
```
Status Colors = 
VAR _s = '311 TPW CSRs'[SR Status]

RETURN
SWITCH(
	TRUE(),
	_s = "Closed","#ADADAD",
	_s = "Duplicate (closed)", "#777777",
	_s ="Open", "#E41A1C",
	_s = "Work In Progress", "#367DB7",
	_s = "Duplicate (open)", "#E41A1C",
	_s = "New", "#E41A1C"
)
```

**Comment by susannegov** [comment]
Went over this in data science backlog refinement. In review/qa
- Changed format of bar charts
- Removed axis labels
- Added data labels
- Added sorting
- Moved title of matric visual to subtitle of dashboard
- Added subscription of PDF to the first of very month.

**Comment by katelunceford** [comment]
@susannegov I thought of more tweaks... 

#### Define the sections more clearly
- Decrease the white area around the top filters so that there’s a beige space between it and the next section below
- Make is super clear that the buttons for [Assigned Group / Method Received / Status] apply to both the 1st and 2nd graphs 
   - Group these 3 things together in the same white space
   - Make the 2nd graph the same height as and align it with the 1st graph
   - If needed to fill out the rectangle, add a white space above the 2nd graph / next to the buttons for [Assigned Group / Method Received / Status]

#### Headings
- Use the same fonts & sizing as the TPWstat PBI dashboard 
- Edit the main subheading so it reads: Sent to the Requester, Available by Phone, and Publicly Listed Online for the Last 30 Days
- Edit the 1st graph heading so it reads: # of SRs by [Assigned Group / Method Received / Status]
- Edit the 3rd graph heading so it reads: Days Until First Activity Is Completed
- The following headings should all be the same font, style & size
   - Assigned Group
   - SR Type
   - `# of SRs by [Assigned Group / Method Received / Status]
   - % of SRs with Detailed Communication 
   - Days Until First Activity Is Completed

#### Graphs
- Can we match the bar graph colors from the 311 SR Response dashboard? 
   - Navy for the 1st graph (is it the same navy? it's hard to tell)
   - Teal for the 2nd graph
   - Keep purple for the 3rd graph
- Delete the X & Y axis labels on the 1st graph
   - Delete "Count SRs" 
   - Delete "[Assigned Group / Method Received / Status]"
   - Keep the number labels on the y axis 
- Delete the X axis label on the 2nd graph
   - Delete "[Assigned Group / Method Received / Status]"
- For the 2nd graph (% of SRs with Detailed Communication), would it be possible to keep the Y axis scale static where the top is always set to 100%? So that it doesn't vary by size according to the content, but rather is always scaled to 100%

**Comment by katelunceford** [comment]
- Update the ABOUT text on the left _(will come back to fill this in)_
- Match the title heading font style to the [SR Response dashboard](https://app.powerbigov.us/groups/me/reports/3ed8a2de-d354-464e-9bb2-af9b1a128fd6/ReportSection688d4a48f7221139d265?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f)
- Add "- Last 30 Days" to the main title

**Comment by katelunceford** [comment]
Moving this to closed since the dashboard is live and already proving useful 🙌

Work continues in 
#19211 Refine Activities dashboard
#18993 Solicit feedback on SR Activities dashboard
