### ISSUE TITLE
[Enhancement] Only show last 4 of SSN

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#18636]
## Description

After reviewing with Jacob and Paul, we decided for security purposes to only show the last four of the social security numbner. Please update with new requirements

## Notes
Reference Issue #17065

**Comment by susannegov** [comment]
# To do
- [ ]  Change label to `Last 4 digits of Social Security Number`
   - scene_32, scene_74, scene_105 to edit
   - See details labels and print application web pages
- [ ] Change Regex Validation
- [ ] Change JS 
- [ ] Create PR request

**Comment by susannegov** [comment]
Merged PR
