### ISSUE TITLE
Develop HR Digital Interview Pre Interview Applicant List & Candidate Screening Matrix

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#18633]
After much discussion during the Sprint Review stakeholders want to see the entire interview process automated not just the Interview itself.
During work session with Diana we divided the process into stages

- Pre Interview
Posting Information (posting analysis)
Applicant List
Candidate Screening Matrix

**Applicant List/Candidate Screen Matrix**

- Will need Dev help with importing Candidate names from eCareer Applicant Report
- Follow up with Chrispen to discuss a possible solution he might have for importing Candidate list

![image](https://github.com/user-attachments/assets/df5503fe-88fe-4ea2-ae23-f3dea38ef69a)

![image](https://github.com/user-attachments/assets/f3c16633-7c9e-4acb-a3dc-5f6890efc3de)

**Comment by stephaniemoorer** [comment]
- [ ] Created Edit Applicant page

- [ ] Added edit fields in table 
Email
Phone
Veteran y/n
Dept Employee y/n
In Good standing y/n

- [ ] Created Candidate Screening Matrix 
- [ ] Added Job Posting details
- [ ] Added Preferred Quals
- [ ] Added Standard Instructions
- [ ] Added table to select applicants moving forward for interview 
- [ ] Added edit field for Meets Preferred Quals y/n
- [ ] Added Print option

**Comment by dianamartin** [comment]
# 9/4/2024
- Worked on "Applicants" page 
![image](https://github.com/user-attachments/assets/9fb435ba-10d7-42c2-bd85-a1c29b87a051)
>split up the menus, intake forms above and PDF documents below
![image](https://github.com/user-attachments/assets/dc731aea-8721-45bb-af45-69825d6ae50d)
- When "Department Employee" is "Yes" - highlights the field background like it would in the spreadsheet
- The "Last Name" and "First Name" fields get populated from an equation in the backend to parse it out
- Table is inline editable
  - Full Name, Email, Phone, U.S. Veteran, Department Employee, Dept. Employee in Good Standing

## Prototype of Candidate Screening Matrix
![image](https://github.com/user-attachments/assets/7ceded61-0c5c-4add-85e5-99cc4255f311)

**Comment by stephaniemoorer** [comment]
**9/24/24**
Stakeholders approved of this page. 
There was one issue with applicant names blanking out, will add that problem to issue #18961

Closing this issue
