### ISSUE TITLE
Maximo Report Request [Modification] Update District Maintenance Data Quality Report remove older FY22

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#18642]
https://github.com/cityofaustin/atd-data-tech/issues/13858

https://github.com/cityofaustin/atd-data-tech/issues/18641

### Scope: 
**SBODIST Data Quality Concerns** Report 
- [ ] for all remove FY22 and older (FY21, FY20, etc) 

@ganesh - is there a way to keep track of the WO that are not being considered or removed? I don;t want to loose track of the ones we can pushing out... 

![image](https://github.com/user-attachments/assets/a6243e11-6733-4f40-a517-8689c7d85c6b)

**Comment by rebekkabry** [comment]
On Deck: 9/3/24

**Comment by ReneVarg25** [comment]
### 9/9/24
Other sections showing similar older than FY22 work orders, may have to extend scope to other sections or entire report.

![image](https://github.com/user-attachments/assets/e7aa0e16-373d-444c-aa54-eecdf4003ffa)

![image](https://github.com/user-attachments/assets/cac31b19-c82d-4f8d-b8f0-a5779988ee50)

![image](https://github.com/user-attachments/assets/bbbe8ffe-d375-423e-a6af-982f2b31f007)

![image](https://github.com/user-attachments/assets/e148f1b2-8f9b-4b4c-a6b6-e8bb4ff4f460)

**Comment by GaneshKamarapu** [comment]
this is deployed and is ready for QA. @ReneVarg25 @rebekkabry

**Comment by rebekkabry** [comment]
Report mets stakeholder ask. 
Creating an impact report to provide to stakeholders. 



Page | Impacted by IBM Errors/CTM | Change Since   Report Mod | 9/18/2024 | 7/18/2024
-- | -- | -- | -- | --
Open SR   with Completed or Canceled or No Work Order | Yes | 21 | 48 | 27
Open SR with all Completed Work Orders | Yes | 20 | 36 | 16
Resolved SR with Open Work Order | Yes | 0 | 0 | 0
SR with multiple Work Orders | Yes | 4 | 20 | 16
Pothole in Non District group or assigned to a wrong   Classification | No | 5 | 7 | 2
Completed Parent - Open Children (Before Restriction implemented   on 3/23) | No | 0 | 0 | 0
Non - Utility - Completed Parent - Open Children | No | -6 | 28 | 34
District Maintenance WO Missing Crew | No | -30 | 99 | 129
District Maintenance crew/work group on other classification   work orders | No | -1 | 4 | 5
Work Orders with missing Assets with Materials added | No | -8 | 5 | 13
Surface Repair Work Order with out Length and Width | No | -62 | 40 | 102
Total |   | -57 | 287 | 344
Total minus IMB Impacted |   | -102 | 183 | 285

**Comment by rebekkabry** [comment]
# Updates: 
- advised stakeholders of report readiness. 
- advised to review and showed the current status. 
- Report is complete. 
- DTS will close ticket. Will continue to support Q/A efforts.
