### ISSUE TITLE
Review Q/A for DM Quality Report 

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#18641]
Originate: https://github.com/cityofaustin/atd-data-tech/issues/13858

Goal: Is to clean up the report and outstanding missing QA WO 
[sbo_dataquality (1) 8.15.24.pdf](https://github.com/user-attachments/files/16626401/sbo_dataquality.1.8.15.24.pdf)

### ✅ Action Item/s from 8/15/24 Meeting 
**DTS Maximo**
- [x] create issue to remove 22 and older from Q/A report @rebekkabry #18642 
- [x] send out weekly q/a reports again @ReneVarg25 
- [ ] schedule q/a work session for 23/24 work orders needed with DM SI and SV @rebekkabry 

**District Maintenance**
- [x] review 24 missing crews and add were needed 
- [x] discuss usage and assisgnment logic of `CREWID`
```
DIS2 csr 
DIS1 maintainence 
norht1 
south1

**Comment by rebekkabry** [comment]
[sbo_dataquality (1) 8.15.24.pdf](https://github.com/user-attachments/files/16626401/sbo_dataquality.1.8.15.24.pdf)

**Comment by ReneVarg25** [comment]
### 9/21/24
CSR Work log issue resolution and removal of FY22 and back from report data needs to take place before proper QA can be sent out.

**Comment by rebekkabry** [comment]
# 10/7/24 

- DTS Maximo advised stakeholders of report status and offered support to work through work orders 
- Stakeholders will meet internally to resolve 
- Junior has informed they will not return to site to update certain` time frame work orders, will close`, and management is aware and approve. 
- Emailing report to stakeholders by Rene. 
- `CrewID`s informed were added by Ops Internally teams, Junior, but not really needed. DTS Maximo advised against cease in included as other groups may rely on that field for reporting.
