### ISSUE TITLE
[Enhancement] Implement mobile optimization for SRs

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#18674]
## Description
During the Micro-modal SR Review meeting with Lime on 8/19/24, we discovered the need for mobile optimization of the SR portal because Lime uses tablets in the field.

## Acceptance Criteria
- Update the code so that all primary buttons and interactive elements are enlarged for easier tapping on touchscreens

**Comment by dianamartin** [comment]
- Created PR [#166](https://github.com/cityofaustin/atd-knack/pull/166) for addition of mobile styling CSS

**Comment by dianamartin** [comment]
# 8/20/24
PR was approved, I merged the code and closing this issue now.
