### ISSUE TITLE
De-Activate Special Events Fees for FY25 (LP) - (On Prod , Ready for UAT)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#18694]
The Following Special Events Fees need to be de-activated since they are no longer used:

- Customized Standard Reusable Plan (1 Block – Partial Closures Only)
- Gates Receipts Payment
- $1.00-$3.00 per person
- $4.00-$6.00 per person
- $6.00 and over per person

These fees do not have any automations, they are manually inserted. There are no validations for these fees as well, so they can be removed without consequences.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and requested for Dev and Test Deployment, SCTASK0456768

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes are deployed , Ready for UAT on Test
