### ISSUE TITLE
De-Activate RW Valet Fees for FY25 (LP) - (On Prod , Ready for UAT)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#18695]
The following Fees need to be de-activated for FY 25 :

- Fee Descriptions: Hoods, Large Meter Hood, Small Meter Hood
-  Used in RW- Temp Valet and RW - Valet Permanent Folders 
-  Fees are usually added manually and no validation logic exists in workflow to check for these fees.
-  Fees are available in Insert & Run Procedure and needs to be removed (All the options under the Valet Annual - Hoods description in the Insert & Run procedure can be removed)

---

- Fee Description: Temporary Valet Parking 
- Used in RW - Temp Valet Folder 
- Fees is inserted when attempt is made in Temporary Valet Review Process. 
- This fee can also be removed from the Insert & Run Procedure
- Note: There seem to be 2 fees with the same description, i.e. Temporary Valet Parking. We need to identify the one that has not been used in a while and de-activate that one.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Done a commit to de-activate the fee codes  - 50190, 50344, 50345, 50205 and requested for Dev and Test promotion . SCTASK0453924

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Test , Ready for UAT 
Note - 1. Valet Annual - Hoods has been inactivaed and removed from RW folder - Fee Insert and run procedure 
2. Temporary Valet Parking fee has been inactivated and fee insert logic has been removed from Temporary Valet Review process

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes are deployed to Prod , Ready for UAT

**Comment by TracyLinder** [comment]
This went to prod. Then we did another update on #19276 
Closing.
