### ISSUE TITLE
Make `moped_proj_funding` table available through the Moped Power BI dataflow

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#18701]
Now that we have made funding data available in FDU format in the `moped_proj_funding` table (https://github.com/cityofaustin/atd-data-tech/issues/18450), we should make this table available through the Power BI dataflow to enable reporting on funding data entered in Moped.

This was requested by Nathan from ATSD.

**Comment by mddilley** [comment]
@Charlie-Henry can you estimate this?

**Comment by Charlie-Henry** [comment]
@mddilley, I've added `moped_proj_funding` to the dataflow, Nathan should now be able to select this table to add it to his report.

**Comment by mddilley** [comment]
@Charlie-Henry yayyyyyy thanks again!
