### ISSUE TITLE
5  Firstnet - Mifi order

### ISSUE THREAD

**Issue by scottreedy** [cityofaustin/atd-data-tech#18718]
5 mifi's for spares while I am out until 9-21-24

**Comment by Matthew-M-TPW** [comment]
@Craigjacobs-ATX went to pick them up on 9-4 and they were not there

I went on 9-6 and they were still not there. I asked them to reach out to the vendor they will get back to me on this

**Comment by Matthew-M-TPW** [comment]
Picked up devices

**Comment by JBStrangenew** [comment]
Do Not Delete:
5 mifi's for spares while I am out until 9-21-24
