### ISSUE TITLE
[Tablet Support] Street and Bridge: Issue 10 iPad devices (Batch 2)

### ISSUE THREAD

**Issue by scottreedy** [cityofaustin/atd-data-tech#18717]
Ordered 10 iPads that can be used for TimeKeeping and spares

**Comment by scottreedy** [comment]
REQ0195272 - SCTASK0445196 - 10 iPad mini's for SBO 08/07/2024
Just received all in and added to Knack:
737-382-5619  COAW74403  IMEI: 359383683561408  ICCID: 89011003330154776438  sn HXYG04Q3GH
737-382-5615  COAW74411  IMEI: 359383683450388  ICCID:                                          sn FQDK0729YL
737-382-5622  COAW74412  IMEI: 359383683689647  ICCID: 89011003330154776255  sn HF23HN423V
737-382-5618  COAW74410  IMEI: 359383683237538  ICCID: 89011003330154776446  sn F500CYYY66
737-382-5621  COAW74409  IMEI: 359383682801102  ICCID: 89011003330154776248  sn MY9NCYYJ9C
737-382-5625  COAW74404  IMEI: 359383682797409  ICCID: 89011003330154776479  sn D4VGC7NF2V
737-382-5626  COAW74408  IMEI: 359383683579368  ICCID: 89011003330154776271  sn C4K3YJN0T6
737-382-5623  COAW74407  IMEI: 359383683724055  ICCID: 89011003330154776263  sn FF7JY6K3JM
737-382-5627  COAW74406 IMEI: 359383683667957   ICCID: 89011003330154776289  sn HGY23MW9Q0
737-382-5620  COAW74405 IMEI: 359383682589749  ICCID: 89011003330154776230   sn D2JY5676LQ

**Comment by scottreedy** [comment]
These can now be sent to Susanne to add Profiles when needed.

**Comment by dianamartin** [comment]
# 8/21/24
cc @maccallump Thanks @scottreedy, glad to know the other 10 tablets came in. I'll have to get with the SBO DMs to figure out who should be receiving them.

**Comment by scottreedy** [comment]
I put the screen protectors on the ipads. 8 looked good and 2 had some small bubbles.

**Comment by susannegov** [comment]
See #18712

**Comment by susannegov** [comment]
# Labeled Tablets
- [ ] COAW74408

**Comment by ChrispinP** [comment]
@susannegov @dianamartin Any further action?

**Comment by dianamartin** [comment]
@ChrispinP you could follow-up with Cathy to confirm that they're not needing us to keep this open due to its status.

**Comment by ChrispinP** [comment]
Have users collected these devices, completed device setup, and are active?

**Comment by scottreedy** [comment]
@Matthew-M-TPW @dianamartin Diana, can we close this ticket?

**Comment by dianamartin** [comment]
@scottreedy We can close this if we have documented it in our hardware inventory and deployed the ones requested for users.

**Comment by JBStrangenew** [comment]
Do Not Delete:

Ordered 10 iPads that can be used for TimeKeeping and spares
