### ISSUE TITLE
[TCP Case Management Upgrade] Add Messaging Features to Applicant Portal and Reviewer Taskboard View 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#18727]
Based on stakeholder requests from sprint review

### Action Item: Capture detail of what project/submission the message is about
* Added an option for the applicant to select the cycle the message is connected to (showing all cycles connected to the current project where messaging)
     * Repeated on CSWZ side
     * Adding the column for Applicant Messages table in TCP and CSWZ project pages
          * What are we showing for the display value? Just the cycle numbe
     *  Adding the column for Applicant Messages table in Messages
          * We don’t want to have separate inboxes based on project type **[Need to solve]**
     * Staff Taskboard side
          * Added direct link to the submissions pages from the message row
    * Staff TCP Details page
        * Added column for TCP Cycle
    * Staff CSWZ Details page
        * Added column for CSWZ Cycle
        
### Action Item: Assignment defaults to lead reviewer
* this was already done
    
### Action Item: Color coding - highlight when critical
* Identified the two critical topics
* Will have a yellow highlighter on the topic column
* Set this to no longer highlight when the message has been reviewed
<img width="432" alt="image" src="https://github.com/user-attachments/assets/c511f4ba-7841-46a1-8407-a45dce82fad6">

### Action Item: Checked Off item
* Adding a boolean to the Message object to use for a checkbox (copying model from TIA)
     * Adding a Message Reviewed timestamp
     * Adding Message Reviewed account info capture
     * Adding trigger button
     * Staff side - My Tasks page
         * Adding an action column
    * Review with Tracy: new filters New, Reviewed, All
         * Checking off New makes it Reviewed and filters it out of the default landing tab
<img width="704" alt="image" src="https://github.com/user-attachments/assets/ec5846ba-c1d6-4cda-b4a1-7d8d363d37b9">

**Comment by KaroEngstrom** [comment]
### Add Reply feature from Taskboard to Respond to Urgent Messages 
- [ ] Add Reply trigger button that generates a new message back to the sender/requester

**Comment by ChrispinP** [comment]
We determined that the reply feature was only possible from a new menu on the Task Board by selecting the customer which we determined was not MVP after adding links to the connected cycles so one can either navigate to the case or cycle to send a new message instead.

In addition to be able to mark a message as reviewed, view conditional coloring & filters, or navigate to its connected cycle, staff now has to the ability to send the message to the customer via email as well.

![image](https://github.com/user-attachments/assets/f1027718-19f3-47f0-96c7-ffeef74ab00a)

This should now be considered complete, pending final review

**Comment by ChrispinP** [comment]
Customer modals have been updated to say "Send ROW Staff a Message"

**Comment by ChrispinP** [comment]
Changes have stuck and everything working as expected. closing
