### ISSUE TITLE
New laptop for Ulfath M.

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18741]
### Ulfath M needs a Dell laptop. She is with DTS.

**Comment by dianamartin** [comment]
# 8/22/24
@Matthew-M-TPW can you take this issue please, thanks!

**Comment by Matthew-M-TPW** [comment]
Computer is being sent to user via Fed Ex

**Comment by dianamartin** [comment]
# 8/30/24
User continues to have issues, we need to escalate to CTM Network/HD. 
- SN Ticket: [INC0425469](https://atx.servicenowservices.com/incident.do?sys_id=97639fa5971cd690d59ab42ad053af2e&sysparm_record_target=incident&sysparm_record_row=1&sysparm_record_rows=4&sysparm_record_list=active%3Dtrue%5Eassignment_groupDYNAMICd6435e965f510100a9ad2572f2b47744%5EORDERBYassignment_group)

**Comment by Matthew-M-TPW** [comment]
Reached out to CTM help desk for advice on creating account

**Comment by Matthew-M-TPW** [comment]
user came down to Austin and had the user log in 

Keeping ticket open until old account is deleted and everything is working with the new account

**Comment by Matthew-M-TPW** [comment]
followed up with the user "how is everything working with your computer?"

**Comment by Matthew-M-TPW** [comment]
user responded "Thanks for asking. Everything is working just fine"
