### ISSUE TITLE
Add fields to DTS Portal and Project updates page

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#18758]
Related Issue: https://github.com/cityofaustin/atd-data-tech/issues/17974

I have made some changes to the test app that need to be recreated in the production app:
https://atd.knack.com/test--26-apr-2024--dts--data-and-technology-services-portal#current-projects/

Three new columns to object_30 Project Evaluation

Most recent comment, type: paragraph text
Comment date, type: date/time
Issue assignees, type: short text

I created a new page to display those columns
https://atd.knack.com/test--26-apr-2024--dts--data-and-technology-services-portal#current-projects/

**Comment by chiaberry** [comment]
@dianamartin @KaroEngstrom  Here is my apps request. Let me know if I need to include more details about the page I have in the test version of the app. 

@amenity add any details or requests, it seems like I got the column width working in test

**Comment by KaroEngstrom** [comment]
## Fri 8/23/24 
- added fields to `project_evaluation`
     - Most recent comment - paragraph text ✅ 
     - Assignee - short text ✅ 
     - Comment date - time/date 
          - ⏸️ checking on this because the Test model was set by default to Current Date, an option we don't use (we set it to None and the date is always populated via record rule from the form/trigger when the record is creating)  
- built the page per the model in Test
