### ISSUE TITLE
Import 4,776 records of missing regulation connections

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18756]
During a work session with Chrispin on 8/22, we went through the process of importing the 4,776 records missing a regulation connection and all the other connected records required.

`document_template`: 
- imported 2,652 records and confirmed successful import by using the `Record Created Date`. This is a record for each regulation document associated to the new connected regulation items

`regulation_document`
- imported 2,652 records and confirmed successful import by using the `Import Date`

`regulation_template`
- imported 4,776 records and confirmed successful import by using the `Record Created Date`

`regulation_items`
- imported `4,852` records and confirmed successful import by using the `Import Date`

**Comment by ChrispinP** [comment]
During the  record audit for soft launch, I established most of the remaining connections if they were blank inclusive of Self Connections and Template Connections. There are still some records missing connections, we will capture that remaining work in #19718 of about 200 records.

complete, closing
