### ISSUE TITLE
Enhancements - HR Digital Interview Hiring Management

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#18792]
- [x]  the Posting Type in Edit Job Posting should have these values in the drop list

![image](https://github.com/user-attachments/assets/a2032974-e0b3-47c1-8dc1-cb711dcf929b)

- [x] Move Edit Job Posting button be moved above Pay Scale?

- [x] In Edit Posting page format the Zone fields so the $ is accepted ex. $36.87

- [x] Display License and Certifications on the Job Posting Details page below Preferred Qualifications
- [x] Edit job Posting - Position Type needs to include the text. Should this field be moved to the Variables Zone & Offier column?
Used on the Variables Zone & Offer form 

- [ ] Do we want to check into auto populating Pay Scale information from Banner Data Warehouse?
- [ ] Do we need to set up the ability to email Posting Information to Hiring Manager?

**Comment by dianamartin** [comment]
# 8/30/24
- Stephanie and I synced on this and we took care of several items. We still have some outstanding things:
- [ ] Do we want to check into auto populating Pay Scale information from Banner Data Warehouse?
- [ ] Do we need to set up the ability to email Posting Information to Hiring Manager

Perhaps we can ask the HR team the next time we have a sprint review.
