### ISSUE TITLE
Create and Share Job Posting

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#188]

**Comment by johnclary** [comment]
Draft is here. Please add comments by 6/11 so that I can share with Jennifer and post to Medium.

**Comment by TracyLinder** [comment]
Amenity went to town on this. :sparkling_heart: It looks good.

**Comment by johnclary** [comment]
Thanks, all, for your input. Incorporating feedback and finalizing w/ jennifer today.

**Comment by johnclary** [comment]
Jennifer is still working on this as of 6/14. Should be posted this week.

**Comment by johnclary** [comment]
We did it! Thanks, all.

**Comment by amenity** [comment]
https://medium.com/@coaatddts/job-application-analyst-austin-transportation-data-technology-services-d9f7b1383ba4
