### ISSUE TITLE
Review CDS' bond dashboard request

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#18807]
Capital Delivery Services is responsible for project management and programmatic bond reporting across many departments (9 for now including Austin Water, DSD, ______ , [all CoA departments who spend bond money?]. Luke S. (BI Consultant @ CDS) has been tasked with replicating #11325 for CDS. 

Luke plans to fork the [atd-bond-reporting](https://github.com/cityofaustin/atd-bond-reporting).  He has already written scripts to meet CDS' needs, but he doesn't have the infrastructure in place to launch the system. He reached out to @Charlie-Henry requesting his own env variables. Charlie [asked the Dev team](https://austininnovation.slack.com/archives/CHZE6BC6L/p1724101507707199) about provisioning some based on this [template](https://github.com/cityofaustin/atd-bond-reporting/blob/main/env_file_template)
- Socrata
- AWS [atd-microstrategy-reports s3 bucket](https://us-east-1.console.aws.amazon.com/s3/buckets/atd-microstrategy-reports?region=us-east-1&bucketType=general&tab=objects)
- Postgrest
- Viewer account for airflow

Concerns were raised about the security risks of opening our systems to external users and lack of clarity around the long-term vision, e.g. Would our team be expected to take on DAGs from other departments?

**Comment by amenity** [comment]
@Charlie-Henry - feel free to add/correct any of ☝🏻.

**Comment by Charlie-Henry** [comment]
I'm going to close this out. I met with Luke last week and it sounds like they're gonna explore using FME. Will reopen if I hear anything additional.
