### ISSUE TITLE
FY25 Add validation to Driveway/Sidewalk Additional Permit Fee

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#18801]
### Add validation to Driveway/Sidewalk Additional Permit Fee

- Fee Description: Application - Driveway/Sidewalk Additional Permit Fee 50790
- Fee Validation in Workflow: Fee needs to be paid before folder is issued (Similar to DS New Permit Fee)
- GL Account number: 5120-6200-9400-4057

**Comment by vschandramouli** [comment]
Moving to Backlog

**Comment by TracyLinder** [comment]
- We created the fees and added them to the DS fee menu on #19236.
- We still need to develop the automation for the fee Application - Driveway/Sidewalk Additional Permit Fee
- I will update the AC

**Comment by TracyLinder** [comment]
Priya says she created this feature as part of #19299
I'm closing this.
