### ISSUE TITLE
Rename `master` branch and subdirectories

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#18825]
- `master` branch  -> `main`
- `./atd-vzd` -> `./database`
- `./atd-vze` -> `./editor`
- `./atd-vzv` -> `./viewer`
- `./atd-toolbox` -> `./toolbox`
- `./atd-etl` -> `./etl`

**Comment by frankhereford** [comment]
* [ ] Work through codebase, making changes in 
  * [ ] github workflows
  * [ ] .gitignore files
* [ ] netlify
