### ISSUE TITLE
[SharePoint] Help User Gabe T. Regain Access to Sidewalks Files

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#18842]
### Thu 8/29/24 
- yesterday afternoon Gabe T. from Sidewalks and Urban Trails division reached and said his File Explorer has stopped syncing
- the specific folders in question seem to be on the old PWDSidewalksSpecialProjects site which I'm unable to get access to because it redirects to the new SUTD side
- I'm reaching out to CTM to request help getting to those folders - INC0425746
- I communicated to Gabe and to Shelley that the files need to be moved for continued access

**Comment by KaroEngstrom** [comment]
### Thu 9/19/24 
-checking in with Gabe to see if he got OneDrive updated and was able to sync again

**Comment by Matthew-M-TPW** [comment]
Reinitatied One drive
