### ISSUE TITLE
Redesign Customer Overview page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18865]
We are redesigning the customer overview page to replicate existing content

**Comment by TracyLinder** [comment]
<img width="1543" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBektoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c3c8c43ed0e463cdc8adc992c2e8bbbc4ed6f14/image.png" alt="image.png" />

**Comment by ChrispinP** [comment]
The overview page has been revised to be an almost exact replica of what a logged out user sees for the ROW Portal featuring a blurb, Available Services, ROW Division link, Announcements, and if unverified, and page message.

The page has been renamed to Customer Home with the url & email links to be updated at a later time

These changes have been applied to both Test & Prod Environments and shown to stakeholders.

Pending acceptance

**Comment by ChrispinP** [comment]
Updated Customer Home 
![image](https://github.com/user-attachments/assets/1e35d896-b541-4538-af20-65a25adaaaab)

Updated Available Services
![image](https://github.com/user-attachments/assets/742adc54-dd0c-4f14-9511-9a3feb45f2bc)

Updated Navigation, Page Name, & URL
![image](https://github.com/user-attachments/assets/cd4e9b8f-e7c4-4b5e-94ab-aa5293d411c3)

These final updates have been made to Prod Environment only

Ready to review

**Comment by ChrispinP** [comment]
Stakeholders are happy with updated Customer Home, closing
