### ISSUE TITLE
[TCP Upgrade] Add Reviewer Comment to Conflict/Shared Cycle, Review Form, Email, and Details Page

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#18886]
**PURPOSE**: Per our meeting with the stakeholders on Tue 9/3/24, the Conflict/Shared request cycles need to include a review comment field.

**Current Use**

When the reviewer completes a review for a Conflict or Shared request, they email the requester to notify them of the review decision. This email includes their review comment. 

**CMU Version So Far**

In the updated system: 
- the reviewer will enter their review result by updating the current cycle status of the appropriate CSWZ case 
- the requester will get an automated email letting them know the status of their request has changed

**Build in Test**

- [x] Add a Review Comment paragraph field to the `tcp_cswz_submission_cycle` object
     - Should this be rich text to enable clickable links?  ✅ 
- [x] Add Review Comment field to the Complete Review Form in the Reviewer Portal 
- [x] Update the outgoing email to requester as follows: 
     - [x] Update the body to include the review comment 
     - Do we want the name of the reviewer included? Date of the decision? Do we want to rely on the requester logging into to view any of these details or try to share as much as possible via email? 
- [x] Add Review Comment to the CSWZ Request Cycle Details page for the Reviewer (above attachments?) 
- [x]  Add Review Comment to the CSWZ Request Cycle Details page in the Applicant Portal (above attachments?) [Manage Conflict/Shared Project > Conflict/Shared Submission Details]
- [x] Review in Test

**Build in Prod**
- [x] Add a Review Comment paragraph field to the `tcp_cswz_submission_cycle` object
- [x] Add Review Comment field to the Complete Review Form in the Reviewer Portal 
- [x] Update the outgoing email to requester as follows: 
     - [x] Update the body to include the review comment  
- [x] Add Review Comment to the CSWZ Request Cycle Details page for the Reviewer (above attachments) 
- [x]  Add Review Comment to the CSWZ Request Cycle Details page in the Applicant Portal (above attachments) [Manage Conflict/Shared Project > Conflict/Shared Submission Details]

**Comment by ChrispinP** [comment]
confirmed working as expected, complete, closing
