### ISSUE TITLE
Batch Job to Re-default SIF Folders (LP) - (UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18885]
### Run job to redefault the folder info tab of all SIF folders so that the 6 new folder infos are inserted onto existing folders. 
_See #17901_ 

- If a value is required to be input, we should use 0.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Done a commit and requested for Dev and Test Promotion
SCTASK0455067

**Comment by Lpriya-LIT** [comment]
Update - The batch job to redefault SIF folders has been promoted to Dev and Test . 
Working on a script to update the infovalue for the newly added mandatory infos to 0.
Once done , will create a request to run the script

**Comment by TracyLinder** [comment]
@Lpriya-LIT please promote to PROD

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created Prod promotion request , SCTASK0463301

**Comment by Lpriya-LIT** [comment]
Update - Created manual deployment request to create the batch job on prod , SCTASK0464002

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Ready for UAT on Prod

**Comment by TracyLinder** [comment]
@Lpriya-LIT @Nadin-Nader this was tested in prod and the first folder we looked at is missing the 6 new infos. Please see rsn 13253410

**Comment by Lpriya-LIT** [comment]
Update - Created manual deployment request to run a script on Prod, SCTASK0472049

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed on PROD

**Comment by TracyLinder** [comment]
I just checked in PROD and this looks like it worked. I will inform the SIF team.

**Comment by TracyLinder** [comment]
I let the stakeholders know and I'm closing this.
