### ISSUE TITLE
INC0426693 - Knack SR system - asking for manager approval for each job versus by Service Request

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#18893]
Sharon M. 
Finance

User created a CTM SN ticket: [INC0426693](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fatx.servicenowservices.com%2Fnav_to.do%3Furi%3Dincident.do%253Fsys_id%3D479129a71b50de907d61a6cbe54bcb82%2526sysparm_stack%3Dincident_list.do%253Fsysparm_query%3Dactive%3Dtrue&data=05%7C02%7CDiana.Martin%40austintexas.gov%7C337b2f9c7eab4718d49e08dccc3c6e15%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C638609807114421624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=1LtLrm6RTVVwlA4XIeZw%2BO%2FgXgf5tfPe6yszY2d1pM8%3D&reserved=0) which I copied here: 

IT (Diana M., Christina T. and Stephanie M.) and TPW Finance recently launched the Knack Service Request application for users to submit CIP requests. 

### Current Process: 
Finance submits each request for approval, which can have multiple jobs. We would like to be able to submit the individual jobs in each request for manager approval since jobs can depend on another job in the same request to be complete. 

### Work Around:
The current methodology is causing us/Finance to message or email our mgr to approve jobs for specific Knack SR's which is breaking the audit trail for the transactions. Thanks so much

**Comment by stephaniemoorer** [comment]
Will schedule meeting with Sharon and Rochelle

**Comment by stephaniemoorer** [comment]
Meeting scheduled 9/9/24

**Comment by stephaniemoorer** [comment]
**9/9/24**
Met with the stakeholder get a better understanding of the request and how this changes their current work flow. 
Will move forward with this has a Enhancement
Opened new issue for this Enhancement issue #18986
Closing this issue
