### ISSUE TITLE
Get Xavier's change log metrics from the old VZ DB

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#18898]
```sql
SELECT COUNT( DISTINCT atcl.record_crash_id ) AS "Crash Count"  
FROM atd_txdot_change_log AS atcl 
WHERE atcl.updated_by = '<xaviers-email-address>' AND atcl.update_timestamp BETWEEN '2023-10-01' AND '2024-09-30' 
;
```

**Comment by frankhereford** [comment]
```
 Crash Count
-------------
       25568
(1 row)
```

This was arrived at by spinning up a throw-away cluster based on the snapshot `[pre-data-model-vz-archive](https://us-east-1.console.aws.amazon.com/rds/home?region=us-east-1#db-snapshot:engine=aurora-postgresql;id=pre-data-model-vz-archive)` and executing the query above. 

FWIW, rehydrating a DB from the snapshots is just as easy as one could hope -- a bright spot in using RDS!

**Comment by johnclary** [comment]
Thank you, Frank!!!
