### ISSUE TITLE
Tech Debt: Remove old fields from `regulation_items` after data restructuring

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#18909]
Chrispin and I created regulation templates that are creating the unique regulation IDs and holding the item IDs. With this restructuring, we now have fields on the `regulation_items` that are no longer necessary. This issue will be used to remove the fields from the object. 

Fields to remove: 
- [x] Line Item ID
- [x] Regulation Key Prefix
- [x] REG Text
- [x] Generated RN
- [x] Line Item Letter (move data to Historical Reference)
- [x] Line Item Reference (move data to Historical Reference)

**Comment by ChrispinP** [comment]
Line Item Letter, Line Item Reference, Automated Regulation Text, and Regulation Text Display fields removed. Data captured in Historical Reference.

Complete closing
