### ISSUE TITLE
Explore CSR reporting ETL weirdness 

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#18912]
We've been having some trouble running the CSR reporting ETL. Maybe it's the IP? Sometimes it works, sometimes it doesn't. Charlie emailed 3-1-1 about it yesterday. Frank also emailed CTM asking about our IPs.

**Comment by katelunceford** [comment]
@Charlie-Henry could you add a size estimate please?

**Comment by chiaberry** [comment]
I tried re-running (around noon) the cur_year_csr_report_to_socrata dag that failed yesterday morning, and it failed. 
But it ran today without any issue, at the normal time.

**Comment by Charlie-Henry** [comment]
Been bugging Patrick W. over at 3-1-1 about this issue for over 2 weeks now.

**Comment by Charlie-Henry** [comment]
311 has fixed the IP ranges for the city!
