### ISSUE TITLE
Add "Completed Date" to Projects and display column on "Current Projects" page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#18927]
As a DTS Product Manager, I would like to easily see when a project was completed and pull up a list of projects completed within a certain time span. 

- [ ] Add a new date field "Completed Date" to the Projects table in the DTS Portal. 
- [ ] Add a new column, "Project Completion Date" on the far right of the table on the [Project Updates](https://atd.knack.com/dts#current-projects) page. The date should be editable in the table.

**Comment by dianamartin** [comment]
# 9/5/24
@amenity 
- [x] Create new field "Completed Date"
- [x] Add new field to far right of "Current Projects" table (and editable)
![image](https://github.com/user-attachments/assets/08f77e45-90d3-4ee6-9858-7eb1bc390622)
