### ISSUE TITLE
Strengthen Password Security for Mobility Services App

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#18936]
## Description

The current password configuration for the Mobility Services app does not enforce strong password policies, leaving the system vulnerable to security risks. To enhance the security of user accounts and safeguard sensitive data, we need to implement stronger password requirements and user lockout mechanisms.

Recommend maxing out following requirements:

![Screenshot 2024-09-04 at 10 03 50 AM](https://github.com/user-attachments/assets/c9a5c006-f9a1-4c12-b439-5daba4e54d01)

**Comment by susannegov** [comment]
### Turned on password settings: 
![image](https://github.com/user-attachments/assets/02faf946-bac7-4528-9ef3-9bd950f79c94)
### Expiration after 60 days
"Your user account's password has expired and must be changed. To login, please reset your password."
### Can't use last three password settings
"Your new password must not be the same as one of your three previous ones."
### Expiration Settings
- Lockout after...
   - [ ]  3 failed logins
   - [ ] 5 failed logins
   - [ ] 10 failed logins
   - after....
   - [ ] 1 minute time period
   - [ ] 5 minute time period
   - [ ] 15 minute time period
   - [ ] 60 minute time period
   - for...
   - [ ] 5 minute lockout
   - [ ] 15 minute lockout
   - [ ] 60 minute lockout
   - [ ] 1 day
   - [ ] forever
### Lockout Email Options
Currently turned off
- [ ] Allow user to request password reset to unlock account
- [ ] Send user an email when locked out

**Comment by susannegov** [comment]
@patrickm02L Could you review if these settings for **expiration settings** and **lockout email options** are correct?

**Comment by susannegov** [comment]
@patrickm02L 
> I think we should allow users to request a password reset and send them an email when logged out, no?

Added password reset and send an email when locked out.
![image](https://github.com/user-attachments/assets/26668b49-6db8-4a70-9504-f6fc7d4aa4d7)

**Comment by patrickm02L** [comment]
Perf, good to close!
