### ISSUE TITLE
FY 25 Fee amount updates (LP) - (On Prod , Ready for UAT)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#18943]
The fees marked in Blue and Green in column M of the attached document need to have their fee amounts updated for FY 25. 

Document is [here](https://cityofaustin.sharepoint.com/:x:/s/ATDAMANDASupport/EdUEQj9390RMlB8JgUyM2swBuzEfcMo6DoAUkXYKYfZabg?e=dzFIJv)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and requested for Dev and Test promotion, SCTASK0456768

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes are deployed , Ready for UAT on Test

**Comment by TracyLinder** [comment]
### Group UAT
- 2 New DS fees aren't on the insert & run.

**Comment by Lpriya-LIT** [comment]
<img width="959" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3dPQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7db8cef7290a29de8fe5b1ce85cb8a55e61a0981/image.png" alt="image.png" />

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes are deployed , Ready for UAT on Test

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes are deployed to Prod , Ready for UAT

**Comment by TracyLinder** [comment]
Changes have been delivered. Any bugs will need a new issue created.
