### ISSUE TITLE
FY 25 Inactive fee updates (LP) - (On Prod , Ready for UAT)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#18941]
fees mentioned in the Inactive Fee tab of the document below need to be made inactive for FY25

Document is [here](https://cityofaustin.sharepoint.com/:x:/s/ATDAMANDASupport/EdUEQj9390RMlB8JgUyM2swBuzEfcMo6DoAUkXYKYfZabg?e=dzFIJv)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Done a commit and requested for Dev and Test promotion , SCTASK0454353

**Comment by TracyLinder** [comment]
@Lpriya-LIT ok to promote to PROD
FYI @Nadin-Nader

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes are deployed to Prod , Ready for UAT

**Comment by TracyLinder** [comment]
Changes have been delivered. Any bugs will need a new issue created.
