### ISSUE TITLE
Test Asset Tables in EZMax Production

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#18969]
Mike A. is testing the asset tables within EZMaxMobile and requires the following asset tables to be tested and found.

**Comment by ReneVarg25** [comment]
### 9/9/24
Tables Tested to date:
Amenities
Bridges
Mobility Trails
ROW Vegetation
Safety Barries
Special Structures
Traffic Calming Devices
curb_and_gutter
curb_ramps

**Comment by ReneVarg25** [comment]
### 9/18/24
Tested Sidewalk segments.

**Comment by rebekkabry** [comment]
Updated CTM.  Closing until further notice.
