### ISSUE TITLE
IT Support: [SERF Request- SCTASK0453822]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#18976]
Ben White
## Device & User Information (first name and last initial, no last names)
Laptop & Sean, M
## What's the problem?
Supervisor Eric Bollich- raised a request to collect back the laptop for user

**Comment by Vaishnav1397** [comment]
Supervisor is located in Ben White and forwarding the req to craig. @Craigjacobs-ATX Can you please take the laptop?

**Comment by Craigjacobs-ATX** [comment]
laptop has been returned by user.
