### ISSUE TITLE
Cycle number bug on TDS Amanda Review Data Report (SS)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#18980]
### The cycle number count isn't calculating correctly on report 99028
- See #15647

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder The report is fixed for Cycle Number column. Please UAT on TEST. Thank you.
[99028_TDS_Amanda_Review_Data.xlsx](https://github.com/user-attachments/files/16968976/99028_TDS_Amanda_Review_Data.xlsx)

**Comment by TracyLinder** [comment]
Hey @SubhaShroff go ahead and send to prod

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the CTM CM Team to be copied over to PROD under **SCTASK0457154**

**Comment by Nadin-Nader** [comment]
This has been on PROD for a while and Tracy has approved to close
