### ISSUE TITLE
IT Support: [SERF- SCTASK0451876]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#18988]
St Elmo
## Device & User Information (first name and last initial, no last names)
Laptop & Reyes, C
## What's the problem?
Need to pick the laptop from Lisa, K supervisor for the separated employee
## What did you do to resolve the issue
Tried reaching the supervisor but seems to be out of office, need to re-follow-up once back.

**Comment by Vaishnav1397** [comment]
Still out of office will reach out once available.

**Comment by Matthew-M-TPW** [comment]
@Vaishnav1397 can you check the area for TPW-9Y96VW3-N1 

Lisa might have kept the machine

**Comment by Vaishnav1397** [comment]
Walked over and checked but the room is locked. Will make sure to check once she is back.

**Comment by Matthew-M-TPW** [comment]
Laptop is with the supervisor they will deploy it when the user starts
