### ISSUE TITLE
[Tablet Support] AMD: Add Toby T to airwatch and add device

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#19007]
Request from AMD Scott F
**References:**
☁[AirWatch Management](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/airwatch-management)
🤖[Android Configuration](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/tablet-configuration)
🍎[iOS Configuration](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/ios-tablet-configuration)

**Select Issues:**
- [ ] Purchasing Devices
- [ ] Setting up a New Device
- [x] Setting up a New User
- [ ] Switching Device User
- [ ] Remove User & Wipe Device
- [ ] Create or Modify a Device Profile (such as passcode policy)
- [ ] Missing/Lost Device (alarm ping, lock, last location)
- [ ] Deactivate SIM card
- [ ] SIM/Network/Hotspot/WiFi/GPS
- [ ] Workspace One: Intelligent Hub app
- [ ] Launcher profile (such as Home Screen apps/shortcuts)
- [ ] App Catalog: New, Outdated, or Missing app or icon
- [ ] Unable to launch an app
- [ ] Unable to charge/turn on device
- [ ] Device Update/Version
- [ ] Retire a Device (outdated, bricked, no longer used)

**Device Details:**

| User | COA Tag | SN | IMEI | Phone | Brand, OS Version, & Device Type |
| --- | --- | --- | --- | --- | --- |
| Tobby T. | COA###### | ###### | ###### | ###-###-#### | Samsung Android 11.0 Tablet |
| FirstNameOnly | COA###### | ###### | ###### | ###-###-#### | Apple iPadOS 16 Tablet  |
| --- | --- | --- | --- | --- | --- |
| --- | --- | --- | --- | --- | --- |
| --- | --- | --- | --- | --- | --- |
| --- | --- | --- | --- | --- | --- |

**Confirmations:**
- [x] User in AirWatch (in TPW group, not CTM)
- [ ] Device in AirWatch
- [x] Device Labeled with COA Tag, SN, IMEI, & Phone #
- [ ] Device in DTS Inventory

**Comment by susannegov** [comment]
INC0429558 Created to move Toby T. to TPW in airwatch

**Comment by susannegov** [comment]
Added device in airwatch

**Comment by susannegov** [comment]
Notified scott on teams

**Comment by ChrispinP** [comment]
closing, no further action
