### ISSUE TITLE
Create and Send Job Plan Template

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#19012]
[Sharepoing Link to File ](https://cityofaustin.sharepoint.com/:x:/s/MaximoResources/EYY2nHslsPFNq9XBosXfQzwBMkpbDrytj8FtW6waujqsjg?e=IcQfB9)

**Comment by rebekkabry** [comment]
SBO Bridges mentioned wanting a job plan but not familiar with the information set up needed to submit. 
Creating a template to be used for entry and submission. 
Draft done. 
Making updates will send.

**Comment by ReneVarg25** [comment]
@rebekkabry Trying to open links, but getting error 404 instead

**Comment by rebekkabry** [comment]
Linked to Maximo References page 
Sent to Patti. 
Closing ticket. 
Pending Patti submission to create Job Plan for SBO Bridges.
