### ISSUE TITLE
Comment feature on the SBO overtime request details page

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19079]
Comment feature will be used to track if the crew changes after the request is approved.

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/18890#issuecomment-2356986286_

**Comment by ChristinaTremel** [comment]
#### Created an `sbo_comments` object: 
   ![image](https://github.com/user-attachments/assets/49485cee-1e51-440d-a827-2b92ef33efd2)

#### Added comments table and button to add comments and mirrored the structure from Signs & Markings
   ![image](https://github.com/user-attachments/assets/54e4eb05-dc50-4209-97f8-564b959bde16)

#### Comments form uses modal pop-up and updated the `Created By` and `Created Date`
   ![image](https://github.com/user-attachments/assets/3910c744-1b13-4053-996b-377bff7a6f2a)

**Comment by dianamartin** [comment]
# 10/8/2024
Showed stakeholders at 9/27/24 - "OT Form Prep for Training and Roll Out". No modifications required.
