### ISSUE TITLE
Update overtime review process to include 2 levels of review for superintendents and DMs

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19081]
Updated overtime review process
   - Permissions: Should be limited to Supervisors, Superintendents, and Division Managers (as back ups) - based on user authority
   - Supervisor > Superintendent > Division Managers
      - Structure requests to be reviewed by Superintendents first
      - After Superintendent reviews, requests should be reviewed by Division Managers 

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/18890#issuecomment-2356986286_

**Comment by ChristinaTremel** [comment]
### Inspirational Apps
- Finance App
- TCP/ROW
- Signs & Markings

**Comment by dianamartin** [comment]
# 9/18/24 
- [x] Added `SUPERINTENDENT Review?` to the OT Details page
- [x] Added `DIVISION MANAGER Review?` to the OT Details page 
- [x] Removed the long name on the "Start Time" and "End Time" to more simple - was `Start Time - check with Diana`
- Created a review as the Test Superintendent, but I didn't think there was a way to capture that Requester's level.. I'm a little 🧱 on it. Might need to pick some Apps 🧠 and work sesh it out with @ChristinaTremel

**Comment by dianamartin** [comment]
# 9/25/24
Tried some things on the `sbo_review` level, but didn't seem to work well, pivoted and created a new connected field for `Assigned to DM`. 
- [x] Duplicated the New OT Request form
- [x] Created one for Supervisors and the other for Superintendents
- [x] Created a page rule to hide the one form if a Superintendent

**Comment by dianamartin** [comment]
# 9/25/24
- [x] Added "Current Reviewer" field
- [x] Moved "Assigned to Superintendent" to right above "Reviews" table for easier visibility
- [x] Moved "Assigned to Division Manager" to right above "Reviews" table for easier visibility
![image](https://github.com/user-attachments/assets/e955db61-f165-4409-9612-5281d82b1bc0)

- [x] Created a new page "My Reviews" (under "Manage Requests")
  - Has 2 tables:
  - [x] Waiting for Review - like Finance and Purchasing - filtered by "Current Reviewer" (SBO OT Requests)
  - [x] Previously Reviewed - like Finance and Purchasing - filtered by "logged in account" (SBO review records)
![image](https://github.com/user-attachments/assets/d9fc05e0-5321-4caf-b15b-08e60aa73bf8)

**Comment by dianamartin** [comment]
# 10/8/2024
Dave mentioned after a meeting a few user feedback updates:
- [ ] Filter Superintendents to just show superintendents
- [ ] Filter Division Managers to show only show Division Managers

- [ ] Add new "Overtime Type"
- Unscheduled Overtime - New!
- Emergency Overtime - New!

- [ ] Convert "Crew" - rich text to connection to accounts (like superintendent/dm)
- Crew - connections

**Comment by dianamartin** [comment]
# 11/5/24
@ChristinaTremel Is this okay to close?
