### ISSUE TITLE
IT Support: [Excel in COA App iPad]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#19084]
St Elmo
## Device & User Information (first name and last initial, no last names)
iPad & Jonathan, G
## What's the problem?
User says that he cannot download the excel from coa app catalog provided by ctm and need to guide him over.
## What did you do to resolve the issue
Have checked the app through entering the full name and then it didn't work. Later tried to download through Microsoft 365 but still it didn't work. Tried multiple times by individual download through app it couldn't be done as the email id need to be synced to apple. Later informed user to reach Ctm then updated matt on the issue, raised a ticket to ctm on the issue, waiting on the update and permissions to be granted.

**Comment by Vaishnav1397** [comment]
Followed up with matt and the ticket has already been raised.

**Comment by Vaishnav1397** [comment]
checked with matt and mentioned that a request was sent to ctm.

**Comment by Vaishnav1397** [comment]
@Matthew-M-TPW Did we hear anything from CTM on this issue?

**Comment by Matthew-M-TPW** [comment]
Excel App added to the COAapp Catalog notified user
