### ISSUE TITLE
Add `Project Sponsor` field to the SBO overtime request form

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19082]
Add new `Project Sponsor` field to request form to designate project sponsors (typically this should be the one who submits it as well but not always)
      - Add instructions to field on form that notes: `The project sponsor will be acknowledged as the point of contact for this OT request`
      
_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/18890#issuecomment-2356986286_

**Comment by ChristinaTremel** [comment]
- [x] Added `Project Sponsor' field connected to accounts
- [x] Added `Project Sponsor` field to the Overtime Request form with instructions _"The project sponsor will be acknowledged as the point of contact for this OT request"_
- [x] Added `Project Sponsor` to the overtime details page

**Comment by dianamartin** [comment]
# 10/8/2024
Showed stakeholders at 9/27/24 - "OT Form Prep for Training and Roll Out". No modifications required.
