### ISSUE TITLE
Create reporting page for management to track overtime requests 

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19083]
### Reporting Needs
   - Dashboard of number submitted and number approved by week
      - Allow data to be filterable by Division
   - Dashboard of number submitted and number approved by day of week, one column for Friday and one for Saturday with the statuses of those requests broken down by row
   - Dave noted we'll also need a report that Greg can use for auditing. The table is a good start - being able to filter date range based on work date would be good.

_Originally posted by @ChristinaTremel in https://github.com/cityofaustin/atd-data-tech/issues/18890#issuecomment-2356986286_

**Comment by ChristinaTremel** [comment]
Created a reporting page to capture the requested reports: 
![image](https://github.com/user-attachments/assets/54e1b764-c11d-4f4b-aee4-e4b0b0fa0ba8)

![image](https://github.com/user-attachments/assets/808f99f7-0a54-411e-a083-49c3c99e6140)

**Comment by dianamartin** [comment]
# 10/8/2024
- Showed stakeholders at 9/27/24 - "OT Form Prep for Training and Roll Out". No modifications required.
