### ISSUE TITLE
Install hardware for attendance tracker at Kramer

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19091]
Install 1 tablet with mount, barcode scanner, and barcode scanner mount at Kramer location. Configure tablet for user and add shortcut to navigate to the Time & Attendance page on the HR Portal application
 - [x] North District Maintenance

Installation is scheduled for Thursday

**Comment by dianamartin** [comment]
# 9/23/24
- On 9/19/24, went to Kramer location to install tablet mount & bar coding system. 
- Worked with Jorge L.. Greg, Christina were on site to prep hardware and oversee project
- Identified that we need a outlet extensions 4 to 6 outlet to have the tablet charging cable and the key box plugs plugged in on the same outlet. 
- [ ] outlet extension - need to be purchased

**Comment by dianamartin** [comment]
# 10/16/24
- On 9/19/24, Christina, Greg and I went to Kramer service center to install the mounts and issue out the hardware to Jorge L. Forgot to close this!
