### ISSUE TITLE
Install hardware for attendance tracker at Dalton

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19090]
Install 2 tablets with mounts, barcode scanner, and barcode scanner mount at Dalton location. Configure tablet for user and add shortcut to navigate to the Time & Attendance page on the HR Portal application

 - [x] Utilities & Structures: Bridge Repair / Maintenance
 - [x] Utilities & Structures: Concrete Repair and Construction

Installation is scheduled for Friday

**Comment by dianamartin** [comment]
# 9/25/24
- Went on site to Dalton on 9/20, installed at both Concrete and Bridge buildings
