### ISSUE TITLE
Replace transportation-data-utils library with smaller modules

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#191]
We have a monolothic python library that contains a bunch of different utilities: https://github.com/cityofaustin/atd-data-utils.

Lots of problems with this, including that we want to version-control them independently.

**Comment by johnclary** [comment]
Have new modules created and published on PyPi:
- [email](https://github.com/cityofaustin/atd-utils-email)
- [data](https://github.com/cityofaustin/atd-utils-data)
- [args](https://github.com/cityofaustin/atd-utils-args)
- [jobs](https://github.com/cityofaustin/atd-utils-jobs)
- [logging](https://github.com/cityofaustin/atd-utils-log)
- [knack](https://github.com/cityofaustin/atd-utils-knack) 
- [agol](https://github.com/cityofaustin/atd-utils-agol) 
- [socratal](https://github.com/cityofaustin/atd-utils-socrata) 
- [kits](https://github.com/cityofaustin/atd-utils-kits) 
- Still need to create the `cctv` module.

Running into an issue where some modules won't import after they're installed. I get a not found error. I think it's an issue with `__init__.py`. Will work on it with Sergio.

**Comment by johnclary** [comment]
Talked with @sergiogcx about this yesterday's. He's setting up a pipeline and creating sub-modules.

**Comment by sergiogcx** [comment]
Great, I was just creating a new work issue for this request. Will be closing the other and use this instead.

**Comment by sergiogcx** [comment]
@johnclary I am working on the CI pipeline, these are my thoughts on manual/automatic version changes:

```
Automated:
	- Pros:
		- Version numbers will be automatically updated (ie. 0.0.4 to 0.0.5)
		- Allows to easily maintain multiple environments
	- Cons:
		- Semantic versioning could become a problem if no process is implemented:
			- Example:
				- We make 100 commits to master, the version increases to: 0.0.105
			- Solutions:
				- Manually update the setup.py major or minor version to: 1.0.0, or 0.1.0
				- Automatic versioning would add on top of that 1.0.1, or 0.1.1 (etc...)

Manual:
	- Cons:
		- It becomes a tedious process of going back and forth checking in pypi
		- Room for human error
		- Having other environments gives us more manual labor.
	- Pros:
		- More control over each package and semantic versioning.
```

**Comment by sergiogcx** [comment]
Also, I am thinking of implementing different package environments based on two or three branches:

master
prod (this one probably not, just an example)
dev


- A package would be built into pypi as:

```
atd-agolutils-master 
atd-agolutils-prod (this one probably not, just an example)
atd-agolutils-dev
```

The last part based on the name of the branch, this could allow us to test the packages before they are merged to master.


Another option is to make master build into our regular `atd-agolutils` package, and make dev build into `atd-agolutils-dev`.


This has basically no cost in time or complexity, it's pretty straight forward.

**Comment by sergiogcx** [comment]
@johnclary all subtasks are completed, this epic is now moved to Review/QA. Let me know if you find any problems with any of these libraries:

https://github.com/cityofaustin/atd-data-utilities/

**Comment by johnclary** [comment]
@sergiogcx based on our testing; everything is good to go. This and dependencies can be closed, yes?

**Comment by sergiogcx** [comment]
I have closed them, I am going to go ahead and close this epic.
