### ISSUE TITLE
Feature - Digital Interview New Hiring Manager Page

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19165]
New Hiring Manager page to be used for Hiring Manager to manage:

**Job Posting** - ability to edit the following
- Supplemental Questions
- Posting Notes
- Preferred Quals
- should not be able to edit Minimum Quals or Zone information

**Candidate Screening Matrix**
- select Candidates to Move Forward for Interview

**Offer Letter**

**Comment by dianamartin** [comment]
# 9/24/24
- [x] Created new page called `Posting Management` (I added "| HM" at the end to indicate Hiring Manager)
- [x] Added banner on the page "Page for Hiring Manager Review"
![image](https://github.com/user-attachments/assets/a0e2f003-4c6d-416b-beb2-bc265c8fbef9)
- [x] Copied Posting Information details to this new page
- [x] Added a new embedded form to capture "Minimum Qualifications" & "License and Certifications Required"
- [x] Add new field `Posting Notes` (rich text)
- [x] Add Supplemental Questions
![image](https://github.com/user-attachments/assets/e1041220-15fb-43ad-8822-8a82fecb712d)

**Comment by dianamartin** [comment]
# 9/24/24
- [x] Created new menu button "Candidate Screening Matrix" 
- [x] Added "Candidate Screening Matrix" components to this new page
- [x] Renamed recruiter page to "Screening Matrix"
- [x] Changed URL slug to `screening-matrix`

**Comment by stephaniemoorer** [comment]
This really looks good! Everything populates great!

This is how I used the Posting Management/HM page:
**As the HR Recruiter** 
- complete Edit Posting page
- selected Posting Management/HR page
- completed each tab by copy/paste from previous job posting (except candidate screening matrix)
- Now it's ready for HM review

Is this how you envisioned it would be used?
- I would like for the HR Recruiter to enter everything from the Job Posting Details page
- On the Job Posting Details page if we could have button called 
**Posting Management/HR** under that button would be all the items for the HR recruiter to complete (like you showed me in another app)
Edit Job Posting
Preferred Quals
Min Quals
Notes to Applicant
Supplemental Questions

**As Hiring Manager**
- HM would review and make edits from Posting Management/HM page
- should not be able to edit Min Quals
- need Edit button to edit each of the Preferred Quals

**Comment by dianamartin** [comment]
# 9/25/24
I'm glad you tested it to see your initial thoughts. 

## HR Recruiter
- goes to Job Posting Details
- Fills out `Edit Job Posting` form

## Hiring Manager
- [ ] HR Recruiter maybe sends Hiring Manager link to the Posting Management Details page they need to fill out
 >I'll have to create a page
- They go to "Posting Management Details page" 
- Fill out `Preferred Qualifications`
- Fill out `Minimum Qualifications, License & Certifications`
- Fill out `Posting Notes`
- Fill out `Supplemental Questions`
- Fill out `Hiring Manager Information`
>I imagine they might need to have a "Status" field so we can open and lock the "
Posting Management details"

**Comment by stephaniemoorer** [comment]
10/7/24
Reviewed with stakeholders during Sprint Review

- Made Preferred Qualifications editable for HM
- Remove ability for HM to edit Minimum Qualifications and License/Certification

Closing this issue
