### ISSUE TITLE
Feature - Digital Interview Create PCN and Pay Zone Connection

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19166]
Ability to populate Zone information based on PCN - database with PCN and zone information that will be maintained by HR

**Comment by dianamartin** [comment]
# 9/24/24
- [x] Created new table `pcn_database` 
- [x] Imported `pay-scale-sept-2024` - `1352 records`

**Comment by stephaniemoorer** [comment]
Can the Pay Scale information be in a single line like it appears on the spreadsheet so it's not taking up so much space?

![image](https://github.com/user-attachments/assets/4f8d5693-3a05-456c-a18c-7b9f367103f3)

We discussed grouping the buttons:
**Manage Posting**
Edit Job Posting
Add Preferred Qualifications
Add Notes to Applicate
Add Supplemental Questions

**Manage Applicants**
Edit Applicants
Candidate Screening Matrix

**Comment by dianamartin** [comment]
# 9/24/24
Reviewed Stephanie's note to consolidate the Zone Information 
- [x] Tried concatenated fields and it looked kind of messy 
![image](https://github.com/user-attachments/assets/d2a86a2d-cf33-407d-8016-99390e777984)
- [x] Tried adding a table and it looked much cleaner
![image](https://github.com/user-attachments/assets/1c2ffc9c-9a88-4dc9-8f65-56169b9a8d53)

**Comment by stephaniemoorer** [comment]
This is working great. I love the way it looks on the page.

**Comment by stephaniemoorer** [comment]
10/7/24
Reviewed with stakeholders during Sprint Review

- Added the Exempt Status field back
- Updated the link PCN Compensation field to connect to the new FY25 Pay Scales https://cityspace.austintexas.gov/Departments/Departments/Human-Resources/Divisions/Compensation/Documents - Pay Scales

Closing this issue
