### ISSUE TITLE
Feature - Digital Interview New Approval Process for Hiring Managers

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19178]
From the New Hiring Managers page the HM will need the ability to edit and approve different parts of the interview process.

Possible Workflow:

**Job Posting**

- once the Job Posting is ready for review
- Using a Vacancy Report Milestone - HM Approve Job Posting??? will trigger a email notification to Hiring Manager to access Knack to review/edit/approve Job Posting.
- HM needs to edit or approve Pre Quals, Supplemental Questions and Notes to Applicant
- Cannot edit Min Quals and Zoning Compensation 
- How will the HM notify HR that is Job Posting is ready?

**Candidate Screening Matrix**

- using a Vacancy Report Milestone - HM Approve Candidate Screening Matrix??? will trigger a email notification to HM to access Knack to review/edit/approve Candidate Screening Matrix
- HM select which Applicants will Move Forward to Interview

**Offer Letter**
Not sure what actions the Hiring Manager takes for the Offer Letter

**Comment by dianamartin** [comment]
# 11/7/24
- Had added a Hiring Manager view for recruiters by not a way for Hiring Managers to view and work on a Posting

## Possible Workflow
### Job Posting
- once the Job Posting is ready for review
- Using a Vacancy Report Milestone - HM Approve Job Posting??? will trigger a email notification to Hiring Manager to access Knack to review/edit/approve Job Posting.
- HM needs to edit or approve Pre Quals, Supplemental Questions and Notes to Applicant
- Cannot edit Min Quals and Zoning Compensation
- How will the HM notify HR that is Job Posting is ready?

### Candidate Screening Matrix
- using a Vacancy Report Milestone - HM Approve Candidate Screening Matrix??? will trigger a email notification to HM to access Knack to review/edit/approve Candidate Screening Matrix
- HM select which Applicants will Move Forward to Interview

### Offer Letter
Not sure what actions the Hiring Manager takes for the Offer Letter

**Comment by stephaniemoorer** [comment]
11/7/24
Diana and I had a work session. 
Diana created a awesome table in Miro to map out the pre interview work flow between HR Recruiter and Hiring Manager / Action / Status/ Notification

[work flow and status table](https://miro.com/app/board/uXjVPpGwiwA=/)

**Comment by dianamartin** [comment]
# 11/8/2024
- [x] Moved the page elements from the "Postings Login - HIDDEN" to the "My Postings Details"
- [x] Added new Posting Status choices
  - [x] `In Progress | Needs Action - Candidate Matrix`
![image](https://github.com/user-attachments/assets/1a162ff4-6079-4f6c-82d6-f741dda8f11e)
  - [x] `In Progress | Completed Action - Candidate Matrix`
![image](https://github.com/user-attachments/assets/5634b00d-132e-447f-8697-826c9b3c307c)
- [x] Updated Hiring Manager Menus

**Comment by stephaniemoorer** [comment]
There are a few issues with the My Posting page not being locked down when the Hiring Manger Status is Inactive. Documented the issues in Test Notes issues.

closing this issue
