### ISSUE TITLE
Backfill permits records of approved chauffeur permit

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#19190]
Check in with Jacob and Paul to make sure this is something they want to add.
We'll also need to backfill any permits numbers that have been issued to date.

_Originally posted by @patrickm02L in https://github.com/cityofaustin/atd-data-tech/issues/17218#issuecomment-2329395670_

**Comment by susannegov** [comment]
# Notes from 9/25

- Are permits being tracked by applicants? Do they know they’re active
- When is the permit active?
- How many conditional permits are issued?
   - When they need to take the test to get another conditional?
- In meeting notes
   - How to break down regular permits and conditional?
   - Make a space for permits for applications that are “Approved” and specify regular and conditional permits
   - Conditionals expire in 90 days
   - Permit will have an Issue date
   - Not conditional are a year long
   - Approved date and Permit Issued the same day
      - Chauffeur permits do not have a number or badge number
   - In order to determine conditional permit - Create an option for applicant to signify it’s a conditional permit.
      - Applicant determines
      - PLA determines
- Conditional criteria
   - Students and out of state
      - If Texas is not listed in as state of residence then conditional 
      - Anything under 3 years

**Comment by susannegov** [comment]
# 09/25
- [x] Created Manage Permits web page
- [x] Added the following fields:
   - [x] In applications 
      - [x] Is Texas Residence
      - [x] Is Texas Residence 3 Years
      - [x] Application Row Name (used as a label)
  - [x] In permits
     - [ ] CALCULATE Active Date
     - [ ] Active Date
     - [ ] Is Not Conditional Permit
     - [ ] CALCULATE 2 Year Expiration Date
     - [ ] CALCULATE 90 day Expiration Date
     - [ ] Custom Expiration Date
     - [ ] Custom Active Date

**Comment by susannegov** [comment]
# 09/26
- Backfill all permit records where application is in approved status (91 records)
- Added insert connected record when reviewer selects "Approve application" and "Change status" modal page
![image](https://github.com/user-attachments/assets/40fb05f2-e867-4d83-adba-a0a858e4548b)
- Add ability for reviewer to set custom active date and expiration date for permits

**Comment by patrickm02L** [comment]
Can you check on the doubling of dates in the permit for record 135?
<img width="665" alt="Screenshot 2024-10-02 at 10 26 00 AM" src="https://github.com/user-attachments/assets/ef1f907b-fb40-4ab4-81e8-e8f188ff4ae6">

**Comment by patrickm02L** [comment]
> Can you check on the doubling of dates in the permit for record 135? <img alt="Screenshot 2024-10-02 at 10 26 00 AM" width="665" src="https://private-user-images.githubusercontent.com/5566727/372925427-ef1f907b-fb40-4ab4-81e8-e8f188ff4ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODMyOTEsIm5iZiI6MTcyNzg4Mjk5MSwicGF0aCI6Ii81NTY2NzI3LzM3MjkyNTQyNy1lZjFmOTA3Yi1mYjQwLTRhYjQtODFlOC1lOGYxODhmZjRhZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTUyOTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZkOWJkNTYzY2Q1MTliNmUzMjgyNWQyMjEzNzBlMTQxNjA1MzQ4MDVmNDY1ZmMyYjg4MjcxNmE1MzlmY2MwOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ORxLbzt98va1EC27ywV5XLKHrEblx8oAx6jDSQCLp34">

Can you also look into the duplication of the permits
<img width="276" alt="Screenshot 2024-10-02 at 10 29 42 AM" src="https://github.com/user-attachments/assets/b9f2dd7e-0f18-4bc1-91ec-3af33e0b0dcf">

**Comment by susannegov** [comment]
- Deleted duplicate records
- Added applicant name groupy by for manager pemits in grid
- manage permit page now includes reviewers

**Comment by susannegov** [comment]
- Added `Go to view Application details` link for permit when editing permit

**Comment by patrickm02L** [comment]
Notified Paul that some of the older permits that were backfilled didn't have an Active Date, and that he would need to add them to make sure he was getting accurate counts.

**Comment by susannegov** [comment]
Deleted permit ID 250 as a blank record. Reviewed it on friday 10/25 and is good to close.
