### ISSUE TITLE
Migrate onboarding docs from Microsoft Teams

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#192]
@johnclary has decided we should use Github for as much of our docs as possible.

We have some docs currently in [Microsoft Teams Wiki](https://teams.microsoft.com/_#/tab::71ff8061-51bf-42df-9dfd-66e95ff733b9/General?threadId=19:6125816a2bd34142a9b23fc916a968b8@thread.skype&ctx=channel). We liked this because we could put sensitive logins/etc behind a password protected login. Turns out we can do this same thing in Github Teams using their "Discussions" feature, which are basically markdown wikis.

- [x] Migrate sensitive MSFT Teams wiki content to Github Teams
- [x] Migrate rest of MSFT Teams wiki content to atd-data-tech onboarding wiki page.

**Comment by amenity** [comment]
I _think_ the only sensitive information are the IP addresses; one for the printer, one for the VPN. @dianamartin @johnclary

**Comment by amenity** [comment]
@mddilley Would you take a stab at this and let me know if you have questions? 

Feel free to reorganize/add/edit as you see fit. 

Thanks!

**Comment by dianamartin** [comment]
Sensitive Info: 
- conference bridge line
- VPN/IP address - as Amenity mentioned
- Printer IP - as Amenity mentioned

**Comment by mateoclarke** [comment]
room request email addresses don't need to be public either

**Comment by mddilley** [comment]
Thanks @amenity @dianamartin @mateoclarke for listing the sensitive items. I will began working on this tomorrow.

**Comment by mddilley** [comment]
Finished merging the MSFT doc with the atd-data-tech onboarding wiki. Unsure if the link to the DTS Sharepoint/Teams drive is still relevant. Sensitive info is now in a pinned private discussion in @cityofaustin/transportation.

@mateoclarke - are there any specifics from https://cityofaustin.sharepoint.com/sites/APH/SitePages/Helpful%20Links.aspx that you would like added to the Github wiki?

**Comment by amenity** [comment]
Looks great, thanks @mddilley!

Closing this guy. @mateoclarke @johnclary - if there's something in APH's Sharepoint site you want in our onboarding docs, just open a new issue! 🙏
