### ISSUE TITLE
[Enhancement] Update Chauffeur Fees

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#19209]
## Description
Update the record rule to reflect the new Chauffeur permit rates. 

Previous Fees
  - Application - $25
  - Renew - $25
  - Notary - $6 

New Fees
  - Application - $36
  - Renew - $24
  - Notary - $10
  
## Note
- Must be done on or before October 1.

**Comment by susannegov** [comment]
Go to the following web pages, and update the fees
- [ ] https://builder.knack.com/atd/mobility-services/pages/scene_31
- [ ] https://builder.knack.com/atd/mobility-services/pages/scene_39
- [ ] https://builder.knack.com/atd/mobility-services/pages/scene_72
- [ ] https://builder.knack.com/atd/mobility-services/pages/scene_99
- [ ] https://builder.knack.com/atd/mobility-services/pages/scene_98

Update Email rule language
- [ ] https://builder.knack.com/atd/mobility-services/pages/scene_85
- [ ] https://builder.knack.com/atd/mobility-services/pages/scene_95

**Comment by patrickm02L** [comment]
## 10/1/24
Got a note from Paul saying that the Cashier's didn't have the option to select a renewal fee. We'll need to add it - $24, and update the $36 fee they set for the Molla record.

**Comment by susannegov** [comment]
# 10/1
- [x] Added renewal fee transaction type
- [x] Updated record rule for `Renewal Only`
- [x] Update cashier text
