### ISSUE TITLE
FY25 TDS Fee Updates (LP) - (On Prod , Ready for UAT)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#19207]
### Updates to existing TDS-AMANDA fees for FY25
- Excel documentation file is [here](https://cityofaustin.sharepoint.com/:x:/s/ATDAMANDASupport/EYaqBtSQK2hLnde0A3YVtrcBaeDrnpmy6ZBaVyMxU4G1Xg?e=0ZeSep)

### Update Amount

AMANDA Fee Description | Fee Code | FY24 Amount | New Amount FY25 | GL Account # | Lookup Table(s)
-- | -- | -- | -- | -- | --
TPW-SP-TIA Review 40,001+ trips per day | 83476 | $59,270.00 | $70,510.00 | 5120-6200-9400-4163 |  
TPW-SP-TIA Review 15,001- 40,000 trips per day | 83419 | $35,560.00 | $42,300.00 | 5120-6200-9400-4163 |  
TPW-SP-TIA Review 5,001-15,000 trips per day | 83418 | $23,710.00 | $28,200.00 | 5120-6200-9400-4163 |  
TPW-ZON-PUD >250 acres | 83479 | $16,600.00 | $19,740.00 | 5120-6200-9400-4163 |  
TPW-SP-TIA Review 2,000-5,000 trips per day | 83417 | $15,810.00 | $18,800.00 | 5120-6200-9400-4163 |  
TPW-ZON-PUD 50-250 acres | 83437 | $13,040.00 | $15,510.00 | 5120-6200-9400-4163 |  
TPW-ZON-PUD 10-50 acres | 83436 | $9,480.00 | $11,280.00 | 5120-6200-9400-4163 |  
TPW-ZON-PUD <10 acres | 83435 | $7,900.00 | $9,400.00 | 5120-6200-9400-4163 |  
TIA Waiver Fee | 51288 | $6,320.00 | $7,520.00 | 5120-6200-9400-4163-0000-0000-0000-0000-0000 | 51060
TPW-SP-TIA Waiver/Compliance | 83414 | $6,320.00 | $7,520.00 | 5120-6200-9400-4163 |  
TPW-ZON-TIA Waiver / Compliance `Update fee name to TPW ZTA Review/Waiver/Compliance` | 83428 | $6,320.00 | $7,520.00 | 5120-6200-9400-4163 |
TPW-SP-Site Plan Consolidated | 83475 | $6,320.00 | $7,520.00 | 5120-6200-9400-4163 |  
TPW-SP-NTA | 83420 | $3,160.00 | $4,700.00 | 5120-6200-9400-4163 |  
TPW-ZON-NTA | 83434 | $3,950.00 | $4,700.00 | 5120-6200-9400-4163 |  
TPW-SUB-Preliminary Plan | 83477 | $3,950.00 | $4,700.00 | 5120-6200-9400-4163 |  
TPW-ZON-Review >15 Acres | 83492 | $3,950.00 | $4,700.00 | 5120-6200-9400-4163 |  
TPW-SP-MUD Consent Agreement | 83421 | $3,160.00 | $3,760.00 | 5120-6200-9400-4163 |  
TPW-SUB-Construction Plan | 83424 | $3,160.00 | $3,760.00 | 5120-6200-9400-4163 |  
TPW-ZON-PUD Amendment | 83486 | $3,160.00 | $3,760.00 | 5120-6200-9400-4163 |  
TPW-ZON-Review <=15 Acres | 83493 | $3,160.00 | $3,760.00 | 5120-6200-9400-4163 |  
TPW-SP-Commission Conditional Use | 83495 | $3,160.00 | $3,760.00 | 5120-6200-9400-4163 |  
TPW-SP-Commission Extension | 83496 | $3,160.00 | $3,760.00 | 5120-6200-9400-4163 |  
TPW-SP-Other-Revision,D,A,B,CD,DS,BS,T,W/R,Concept\ | 83497 | $3,160.00 | $3,760.00 | 5120-6200-9400-4163 |  
TPW-ZON-Review <10 Acres | 83491 | $2,770.00 | $3,290.00 | 5120-6200-9400-4163 |  
TIA Scoping Fee | 51287 | $2,370.00 | $2,820.00 | 5120-6200-9400-4163-0000-0000-0000-0000-0000 | 51060
TPW-SP-TIA Scoping Fee | 83415 | $2,370.00 | $2,820.00 | 5120-6200-9400-4163 |  
TPW-SP-Commission Waiver/Variance | 83423 | $2,370.00 | $2,820.00 | 5120-6200-9400-4163 |  
TPW-SUB-Commission Approved Non-Enviromental Variance | 83427 | $2,370.00 | $2,820.00 | 5120-6200-9400-4163 |  
TPW-SP-Administrative Small Site Plan Review | 83474 | $2,190.00 | $2,820.00 | 5120-6200-9400-4163 |  
TPW-SUB-Final Plat | 83478 | $2,370.00 | $2,820.00 | 5120-6200-9400-4163 |  
TPW-ZON-TDM Plan Review | 83487 | $1,980.00 | $2,350.00 | 5120-6200-9400-4163 |  
Street Impact Fee Contestment | 50500 | $790.00 | $1,880.00 | 5120-6200-9400-4163 |  
TPW-ZON Review <.25 Acres | 83488 | $1,580.00 | $1,880.00 | 5120-6200-9400-4163 |  
TPW-ZON-Review <.5 Acres | 83489 | $1,580.00 | $1,880.00 | 5120-6200-9400-4163 |  
TPW-ZON-Review <1 Acres | 83490 | $1,580.00 | $1,880.00 | 5120-6200-9400-4163 |  
TPW-Transportation Development Assessment | 83498 | $1,580.00 | $1,880.00 | 5120-6200-9400-4163 |  
TPW-SUB-Project Assessment | 83499 | $1,580.00 | $1,880.00 | 5120-6200-9400-4163 |  
Plat/Subdivision Vacation | 51712 | $1,140.00 | $1,610.00 | 5120-6200-9400-4163 |  
TPW-SP-Administrative Waiver/Variance | 83422 | $990.00 | $1,175.00 | 5120-6200-9400-4163 |  
TPW-SUB-Administrative Non-Environmental Variance | 83426 | $990.00 | $1,175.00 | 5120-6200-9400-4163 |  
TPW-SP-Administrative Extension | 83472 | $790.00 | $940.00 | 5120-6200-9400-4163 |  

### Inactivate These Fees

AMANDA Fee Description | Fee Schedule Name | TPW Division | Fee Code
-- | -- | -- | --
Site Plan Corrections | Site Plan Corrections | TDS | 51022
Traffic Impact Analysis (TIA) Review | ? | TDS | 51286
Development Assistance Center Fees (Residential/Sidewalk Waivers) | Development Assistance Center Fees (Residential/Sidewalk Waivers) | TDS | 51901
TPW-SP-Non-TIA Mitigaton Fee <2,000 trips per day | Site/Plan Reviews - Non-TIA Mitigation Fee < 2,000 trips per day | TDS | 83416
TPW-SUB-Construction Plan Non-Concurrent |   | TDS | 83425
TPW-ZON-TIA Scoping Fee | Zoning Traffic Analysis Scoping Fee | TDS | 83429
TPW-ZON-Non-TIA Mitigation Fee < 2,000 trips per day | Zoning - Non-TIA Mitigation Fee < 2,000 trips per day | TDS | 83430
TPW-ZON-TIA Review 2,000-5,000 trips per day | Zoning Traffic Analysis Review 2,000-5,000 trips per day | TDS | 83431
TPW-ZON-TIA Review 5,001-15,000 trips per day | Zoning Traffic Analysis Review 5,001-15,000 trips per day | TDS | 83432
TPW-ZON-TIA Review 15,001-40,000 trips per day | Zoning Traffic Analysis Review 15,001-40,000 trips per day | TDS | 83433
TPW-SP-Administrative Conditional Use | Site/Plan Reviews - Administrative Conditional Use | TDS | 83473
TPW-ZON-TIA Review 40,001+ trips per day | Zoning Traffic Analysis Review 40,001+ trips per day | TDS | 83480
TPW-ZON-Zoning Case Review <5 acres |   | TDS | 83481
TPW-ZON-Zoning Case Review 5-10 acres |   | TDS | 83482
TPW-ZON-Zoning Case Review 11-50 acres |   | TDS | 83483
TPW-ZON-Zoning Case Review 51-100 acres |   | TDS | 83484
TPW-ZON-Zoning Case Review >101 acres |   | TDS | 83485

**Comment by TracyLinder** [comment]
The reference PDF that Curtis gave me isn't matching the fee amounts in the data Erin gave me. I'm waiting for a response from Curtis.

**Comment by Lpriya-LIT** [comment]
@TracyLinder I have 2 questions in this card 
1. There is a new fee that needs to be added "TPW Restrictive Covenant Amendment/Termination Review". Could you please let me know in which foldertype that it needs to be added . Also please confirm whether it has to be made available in insert and run menu.
2.  There is a fee name update for "TPW-ZON-TIA Waiver / Compliance" . Please confirm what is the new fee name.
@Nadin-Nader

**Comment by TracyLinder** [comment]
HI @Lpriya-LIT 
1. We won't be creating new fees on this card so no need.
2. Good catch. I updated the line item in the description above.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and requested for Dev and Test promotion, SCTASK0455273

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Test , Ready for UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes are deployed to Prod , Ready for UAT

**Comment by TracyLinder** [comment]
Changes have been delivered. Any bugs will need a new issue created.
