### ISSUE TITLE
Finance Service Request - Modify Email Notifications

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19206]
Can you please cancel the emails when an SR is submitted that currently is sent to the TPW Finance mailbox?  
Rochelle and I are in the habit of working straight from Knack so we kind of ignore those emails and they build up.  

We want to KEEP the completion emails that go to us (assignee) when the the SR is complete just not the original submitted one.

**Comment by dianamartin** [comment]
# 9/25/24
- [x] Remove email when user submits a new Service Request
  - Service Request>Service Request Details>Submit

**Comment by dianamartin** [comment]
@stephaniemoorer ready for review, the email notification was removed upon submission

**Comment by stephaniemoorer** [comment]
Informed Rochelle and Sharon this is complete.
