### ISSUE TITLE
Renew TLS certificates for mobility.austin.gov and visionzero.austin.gov

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#19214]
Current certificates expire **Oct 24, 2024**

TODO:
- [ ] Generate CSRs for the hostname patterns
   - See [docs](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/ssh-certificates-and-renewals-and-domains)
- [ ] Get in touch to securely deliver those to Jason G. at CTM in their linux group
- [ ] Update in AWS Certificate Manager
   - [ ] Moped (*.mobility.austin.gov - [link](https://us-east-1.console.aws.amazon.com/acm/home?region=us-east-1#/certificates/897c4900-3a77-4754-a636-2a79d1335b84))
   - [ ] VZ (*.visionzero.austin.gov - [link](https://us-east-1.console.aws.amazon.com/acm/home?region=us-east-1#/certificates/59e50d26-7841-4fe1-970e-31b76a37fc3a))
- [ ] Install in CloudFront distributions
   - [ ] VZ prod - [link](https://us-east-1.console.aws.amazon.com/cloudfront/v4/home?region=us-east-1#/distributions/E4BGD5YHOIPWK)
   - [ ] Moped prod - [link](https://us-east-1.console.aws.amazon.com/cloudfront/v4/home?region=us-east-1#/distributions/E2RD6MK63VOUI)
- [ ] Import certs + key in Netlify (data.mobility.austin.gov deployment)
- [ ] Make sure you store the new certs and CSR in 1pass
- [ ] Create calendar reminder for 2025
- [ ] Copy/paste this into [docs](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/ssh-certificates-and-renewals-and-domains) to use as an issue template next year

Sites affected
- data.mobility.austin.gov (Netlify)
- mobility.austin.gov (AWS ACM)
- visionzero.austin.gov/viewer (AWS ACM)
- visionzero.austin.gov/editor (AWS ACM)
- mobile-signals.mobility.austin.gov

--- 
Issues from 2023: https://github.com/cityofaustin/atd-data-tech/issues/13995, https://github.com/cityofaustin/atd-data-tech/issues/13994
Issue from 2022: https://github.com/cityofaustin/atd-data-tech/issues/10363

**Comment by frankhereford** [comment]
Going through my email from last week, I just came across these two as well. Thanks for creating this issue! 🙏

**Comment by mddilley** [comment]
@chiaberry and @frankhereford - i made a sweep through this today, and I put it on the sprint planning doc for this sprint. I'm going to move it to the backlog but y'all feel free to take a look and edit if needed. Thanks!

**Comment by frankhereford** [comment]
CSRs have been shipped to CTM, and I'll follow up with the NLT Friday of this week due to the somewhat short fuse we have. Thanks.

**Comment by frankhereford** [comment]
Done and dusted - the new certs are in and saved in 1PW. See you next year!

**Comment by frankhereford** [comment]
Thanks again to @mddilley who caught that I had failed to install this in netlify in addition to the cloudfront distros. The cert I think of as the "moped" cert is actually broader in scope, it also is used for the data and performance hub site. Thank you Mike!
