### ISSUE TITLE
FY25 New LDE Fees (SS) (Ready for UAT in PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#19223]
### We are creating new fees and adding them to the insert + run fee menus on specific folders. Each fee should insert with the TPW Tech Surcharge. 

Folder | AMANDA Fee Name | FEE AMOUNT TYPE | AMOUNT
-- | -- | -- | --
SP | TPW-LDE Administrative Site Plan Review | Fixed Amount | $1,310.00
SP | TPW-LDE Commission Site Plan Review | Fixed Amount | $1,310.00
SP | TPW-LDE Completeness Check Site Plan Review | Fixed Amount | $80.00
SC | TPW-LDE Correction Site Plan Review | Fixed Amount | $160.00
DA | TPW-LDE Development Exemption Review | Fixed Amount | $160.00
SP | TPW-LDE Revision Site Plan Review | Fixed Amount | $650.00
C8 | TPW-LDE Completeness Check Subdivision Review | Fixed Amount | $40.00
C8 | TPW-LDE Construction Subdivision Review | Fixed Amount | $1,310.00
C8 | TPW-LDE Plat Subdivision Review | Fixed Amount | $650.00
C8 | TPW-LDE Preliminary Subdivision Review | Fixed Amount | $650.00

</body></html></div>

**Comment by TracyLinder** [comment]
I will add the GL codes ASAP.

**Comment by SubhaShroff** [comment]
Dev Notes:
Feecode FolderType Fee Name                                                                Lookup Table(Lookup1)
50740    SP               TPW-LDE Administrative Site Plan Review               60005(42)
50745    SP               TPW-LDE Commission Site Plan Review                   60005(43)
50750    SP               TPW-LDE Completeness Check Site Plan Review     60005( 44)
50755     SC              TPW-LDE Correction Site Plan Review                      60005(45)
50760     DA             TPW-LDE Development Exemption Review              60005(46)
50765     SP              TPW-LDE Revision Site Plan Review                         60005(47)
50770     C8              TPW-LDE Completeness Check Subdivision Review  60005(48)
50775     C8              TPW-LDE Construction Subdivision Review               60005(49)
50780     C8              TPW-LDE Plat Subdivision Review                              60005(50)
50785     C8              TPW-LDE Preliminary Subdivision Review                 60005(51)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0458593 - is created for DEV/TEST deployment. Thank you.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0459245**

**Comment by TracyLinder** [comment]
@SubhaShroff @Nadin-Nader none of these fees are inserting when you click on them from the fee menu.

**Comment by SubhaShroff** [comment]
@TracyLinder  There is an issue with Amanda for the default procedures. All good with logic and data but just fee procedures don't go off. I am working with CTM about this issue. Thank you.
@Nadin-Nader

**Comment by SubhaShroff** [comment]
73061d27372b9665e07ef975a9b096c41afbed37 - Waiting CTM to deploy this in DEV for the above mentioned fix.

**Comment by SubhaShroff** [comment]
@Nadin-Nader There seems to be an issue with DEFAULTACCOUNTBILLFEE/default fee procedures missing on DEV amanda. Once CTM fixes the missing procedures on DEV, they can promote this commit. 
Thank you.

**Comment by SubhaShroff** [comment]
@Nadin-Nader 
Since there is an issue on DEV with some procedures missing, I requested CTM to get it deployed in TEST so that we can move ahead - SCTASK0460203.
Thank you.

**Comment by Nadin-Nader** [comment]
@SubhaShroff This has been sent to the DEVOPS CM Team to be deployed to DEV under **SCTASK0460692**

**Comment by Nadin-Nader** [comment]
@SubhaShroff This has been sent to the DevOps CM Team to be deployed to TEST under **SCTASK0461021**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is good on TEST. Ready for UAT on TEST. Thank you.

**Comment by TracyLinder** [comment]
This is still in TEST and needs to be UAT'd.

**Comment by TracyLinder** [comment]
I did light UAT and found no bugs. @SubhaShroff please promote this to prod.

**Comment by SubhaShroff** [comment]
Thank you @TracyLinder.
@Nadin-Nader  Please create promotion request. Thanks.
[19223 - PRODDeployment Plan - II.docx](https://github.com/user-attachments/files/17330610/19223.-.PRODDeployment.Plan.-.II.docx)

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been sent tot he DevOps CM Team to be deployed in PROD under **SCTASK0462091**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This ticket is deployed in PROD. Thank you.

**Comment by TracyLinder** [comment]
I let beth know these are in prod without automation.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  can we close this?

**Comment by Nadin-Nader** [comment]
As we have not heard back or about issues with these fee, i am closing the request. If need be we can reopen
