### ISSUE TITLE
Bug - HR Digital Interview Candidate Screening Matrix Name Field Blanks Out

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19225]
Candidate Screening Matrix / Applicant Table

- [ ] when you make a selection Yes/No on the field **Meets All Preferred Qualifications** the Last Name First Name field blanks out

**Comment by dianamartin** [comment]
# 9/26/24
On the "Hiring Management>View Hiring Details>Applicants" page
- [x] Added New Applicant
- [x] Shows up on table
- [x] Mark "Y" - "U.S. Veteran" - no changes
- [x] Mark "N" - "U.S. Veteran" - no changes
- [x] Mark "Y" for Department Employee - fields begin to highlight
- [x] Mark "N" for Department Employee - fields unhighlight
- [x] Mark "Y" for Department Employee in Good Standing - no changes
- [x] Mark "N" for Department Employee in Good Standing - no changes
Seems like it was a fluke the other day when we were demoing. Unable to recreate the bug.

**Comment by stephaniemoorer** [comment]
@dianamartin 
the bug happens on the Candidate Screen Matrix page when you make a selection Yes/No on the field Meets All Preferred Qualifications

**Comment by dianamartin** [comment]
# 9/27/24
- Re-checked that page and saw there was an additional rule that looked like it was "blanking" out the name field. I think I found it! I deleted it.
