### ISSUE TITLE
Meeting on SBO overtime form and training roll out

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19232]
### Objective 
Review the overtime form and make slight changes with Dave and Greg to prepare for roll out in SBO. 

### Participants
Christina, Diana, Greg, and Dave

### Actions taken
- Renamed `Project Sponsor` to  `Onsite point of contact`
- Renamed `Assigned to Superintendent` to `Who is your Superintendent`
- Renamed `Assigned to Superintendent` to `Who is your Division Manager`
- Renamed `Crew` to `List the people working that day`
- Reworked the `Review Overtime Request` form to match similarly to the finance PR reviews

### Next Steps: 
- Dave and Greg will be showing the overtime form to Supervisors on Monday. He will bring in Frank, Steve, and Jermaine and show them the form process/let them trial run the process and give their initial feedback.

**Comment by dianamartin** [comment]
# 10/8/2024
Was in a meeting with Dave A. for "Career Progress and Alignment with Maximo Assessment" and he said they can roll out after Christina has her nuptials. Mid Oct - early November.
