### ISSUE TITLE
[Living Streets] Build Neighborhood Block Prototype MVP

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#19249]
## Description 

Focus on building the Application intake and Application review portion of the Block Party flow. 

#### Application intake
- Account creation
- Contact Info
- Location for Block Party
- Details about BP
- Attached required documents

#### Application review
- Statuses for approval/rejection
- Triggers to notification applications

## Notes
- [BP miroboard](https://miro.com/app/board/uXjVMtdn2NM=/?moveToWidget=3458764601552287477&cot=14)
- need to verify application statuses

**Comment by KaroEngstrom** [comment]
## Sun 9/29/24

### Initial Build Pieces 
- `ls_nbp_application`- application table + drafted fields
- `ls_nbp_application_content`- attachments and notes table + drafted fields
- account role for Living Streets Applicant (External) already exists

**Comment by KaroEngstrom** [comment]
## Wed 10/2/24

### Applicant Portal 
- added [a new view](https://builder.knack.com/atd/smart-mobility/pages/scene_176/views/view_737/table) (visible only to Builders) for Neighborhood Block Party applications on the existing Living Streets Applicant Portal 
- 
### Staff Portal

**Comment by KaroEngstrom** [comment]
## Thu 10/17/24

### Walkthrough Plan

**1. APPLICANT** 
* Directed to the Applicant Portal from the Getting Started Page
* Create an account 
    * Question - Same type of Living Streets External User ok here? 
* Log in 
* Create a new application 
    * Pulling named and email from the logged-in account
        * Question - Anything missing? 
        * Save
    * Reminder at the top of the page to indicate status 
    * Attachments dropdown
        * Question - Anything missing?  
    * Can still edit and add
    * Applicant submits and can no longer edit
    * Emails

**2. REVIEWER** 
* Logging into Knack via SSO 
* NBP page exists, not visible to users yet
* Similar navigation as other programs
* Shows a table of all applications 
    * Question - Anything missing in columns? 
    * Status filters 
        * Question - Are these statuses ok? 
    * Details Page to view 
    * Info up top
    * Attachments to review
    * Menu buttons 
* Happy Path
    * All good - update status
    * Send over to payment, however that will be handled
* Unhappy Path
    * Documents missing 
    * Write a note
    * Update status 
    * Send an email 

**3. APPLICANT** 
* Got an email and came back to the portal 
* Happy Path 
    * Doing the payment 
* Unhappy Path 
    * Adding new documents 
    * Question - We want to hide the Edit Application here, right? 
    * Resubmits application 
    * Email confirmation again and notification to reviewer

**4. REVIEWER** 
* Payment is done - issue permit
* Update status 
    * This is a final status and the applicant can no longer edit; the reviewer can no longer edit or change status
    * Can still add notes or attachments
* Send email to applicant 

**5. APPLICANT** 
* can now see the button for the Applicant to print out the permit
    * Permit not configured yet
    * Question - What need to be included in the permit? Do we need to generate a permit number? 

**Additional Questions**
* Rejected Status 
    * Email
    * Reviewer Note

[Emails added here](https://cityofaustin.sharepoint.com/sites/tpwSMOPlacemaking/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FtpwSMOPlacemaking%2FShared%20Documents%2FLiving%20Streets%2FNBP%5FKnackApplication%2FEmails)

**Comment by KaroEngstrom** [comment]
## Fri 10/18/24
- at the sprint review yesterday 📆 Thu 10/17/24, we only had a limited time to review the build but we were able to capture a few changes
- [ ]  Remove Document Name altogether from the Attachments 
- [ ] Remove the Link options altogether 
- [ ] Add Other Document type option 
- [ ] Location field - add block information if known. 
^ This final items is a sticking point and still under conversation as to how it will be built out in the system.
