### ISSUE TITLE
IT Support: [SERF Req- SN-SCTASK0458796]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#19246]
Ben White
## Device & User Information (first name and last initial, no last names)
Laptop & Merrick, B
## What's the problem?
Need to take over the laptop, serf req raised by Laura, D
## What did you do to resolve the issue
Forwarded the ticket to craig and mention to follow up the laptop take over.

**Comment by Vaishnav1397** [comment]
@Craigjacobs-ATX Can you please collect the laptop if the supervisor is in office today?

**Comment by Craigjacobs-ATX** [comment]
laptop received back from user's manager (Laura D.)
