### ISSUE TITLE
FY25 Fix: Put DS inspection fees back on fee menu - (Ready for UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#19266]
### These 4 fees should be added back to the fee insert + run 

- 50036 Driveway Inspection Fee DSD
- 50368 Addt Driveway Inspection Fee DSD
- 50037 Sidewalk inspection fee DSD
- 50038 Curb Gutter inspection fee DSD

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Done a commit and requested for Dev and Test Promotion, SCTASK0459492

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Test , Ready for UAT . The 4 fees are added back to DS folder Run rocedure menu

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Created Prod Deployment request , SCTASK0459670

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Prod , Ready for UAT

**Comment by KyleErich** [comment]
@Lpriya-LIT @Nadin-Nader UAT on Prod approved, thank you!
