### ISSUE TITLE
Daniel Offboarding

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#19262]
- [x] 1password
>Removed Daniel from DTS DL on 9/30/24. Which updates the 1password list.
- [x] DTS distribution list
>Removed Daniel from DTS DL on 9/30/24
- [x] Slack 
>deactivated on 10/1/24
- [x] Google drive
>removed access on 10/1/24
- [x] GitBook
>removed as a "member" on 10/1/24

**Comment by dianamartin** [comment]
# 10/1/24
@andrewshensky have you gone through your GitHub issues and reassigned ones assigned to Daniel?
- [ ] Need to create new issue to move Daniel to "Alumni section" in About Us page

I can do these:
- [ ] Update Team Slide
- [ ] DTS Orientation Slide
