### ISSUE TITLE
Three TDS Fees Missing (Awaiting Response from TDS)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#19267]
### Debug - why can't users find these fees on the folders?

- Folder ZC: Planned Area Development (PDA) $3,760 (still looking for fee code)
    - This may have administrative issues. DTS can hold off on debugging until we hear back from Amber.  
- Folder ZC: Zoning Case Review < 10 Acres $3,290 (83482)
    - Inactivated per tickets (#18941) 
- Folders C, C8: Plat/Subdivision Vacation $1,610 (51712)
    - Subha found this in PROD, in the menu.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  
### Possible ZC PDA fees (findings from the existing fee procedurs):
1. **WPD-Planned Development Area (PDA) - (code 57030)**:  But it is inserting $9699 in ZC. In localhost I found a entry for $3290 Lookuptable-51800(57)
2. **51967 - PDA Creation-DSD**.  Lookuptable-51800(63):   This fee looks variable and does NOT  match the amount. 
3. **51433 PDA Arborist Review**  Lookuptable-51800(45):  $6424.47
4. 51460	$1621	PDA Commission Approval-Dev - OLD FY 2016-2017
5. 51460	$2407	PDA Commission Approval-Dev - OLD   FY2017-2018
6. 51415	$1351	PDA Commission Approval-Zoning -OLD FY2016-2017
7. 51415	$5508	PDA Commission Approval-Zoning - OLD FY2017-2018
8. 

IN PROGRESS....................

**Comment by SubhaShroff** [comment]
@Nadin-Nader  As I checked, plat/subdivision Vacation fee is showing up in PROD Run procedure Menu for C, C8 permits. Below are the screenshots form PROD. 
![image](https://github.com/user-attachments/assets/cd6350cf-1d10-403e-a2a1-a7fb9c51ed75)
![image](https://github.com/user-attachments/assets/8bd89715-d40a-4b6e-b53b-295318d77513)

i was testing to insert this fee on TEST environment, today I found issue with COA_FEES package not working on TEST, so couldn't continue..
Please let me know if any issues inserting this fee.
Thank you

**Comment by TracyLinder** [comment]
![image](https://github.com/user-attachments/assets/7eaf0463-283a-4a54-884b-47de06079332)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  As Tracy updated in AC:

1. Folder ZC: Planned Area Development (PDA) $3,760 (still looking for fee code)
          This may have administrative issues. DTS can hold off on debugging until we hear back from Amber.

2. Folder ZC: Zoning Case Review < 10 Acres $3,290 (83482)
          Inactivated per tickets (FY 25 Inactive fee updates  #18941)

3. Folders C, C8: Plat/Subdivision Vacation $1,610 (51712)
         Subha found this in PROD, in the menu. Tracy also tried this fee and looks working (screenshot is posted in the previous comment.)

Once we talk to users can we close this?

Thank you.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Can we close this?

**Comment by Nadin-Nader** [comment]
Waiting on response from Matiur since Amber is out

**Comment by TracyLinder** [comment]
I communicated with Amber about this one a couple of times, so I'm going to close this one.
