### ISSUE TITLE
Remove "Data & Technology Services Portal" from service request form

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#19286]
[Users are selecting “DTS Portal”](https://github.com/cityofaustin/atd-data-tech/issues/19281) as the application bc that’s literally what they’re using. @dianamartin, @patrickm02L, & I decided that staff don't need that option to begin with.

**Comment by dianamartin** [comment]
# 10/2/24
- [x] Remove `Data & Technology Services Portal` as a choice for "What application are you using?"
- Let Apps team know in App Sprint Planning, in case they were looking for it later 😉
