### ISSUE TITLE
Create service delivery workflow issue/form templates

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#193]
WIP https://docs.google.com/document/d/1hYIp2gMbeukzTsu7GF--mLwwKyQIE5FLtrKQZI0A5gY/edit#heading=h.larkkrhvbqt4

**Comment by TracyLinder** [comment]
**A note from today's meeting regarding this task:**

Decided we should condense the customer forms as much as possible. We are proposing forms for the following:

- Maps / GIS
- IT Support & Hardware
- Everything Else - (Data, Reports, New Features, Projects)

**Comment by amenity** [comment]
@TracyLinder -
Rethinking this, I think New Project makes sense to have on it's own.

@johnclary, what do you think about handling Bug Reports, Data and Reports, Features and Enhancements into one general request form? Will our customers know which to choose if we have them all separately? 

[This is what I was imagining in terms of links and help text](https://docs.google.com/presentation/d/1xlkXrsygvql9YOi_DVKldWdUB2Dm8sYmTure9glm6Bg/edit#slide=id.g1ec5950f90_0_13).

**Comment by johnclary** [comment]
@amenity are you suggesting a single form with conditionally-displayed inputs, or a simple general form for all requests, and we sort out the specifics after intake?

**Comment by amenity** [comment]
I was suggesting a single, very general form. But I really defer to y'all as far as knowing what your customers can tell you at the outset that is useful. 

I am also fine with there being only one "submit a request" link and it breaking off into IT Support, Maps & GIS, New Projects, etc.

**Comment by johnclary** [comment]
Well, I'm ready to build some forms and ask some users what they think!

**Comment by amenity** [comment]
<img src="https://media.giphy.com/media/3o7WIva13237Dnwi7S/giphy.gif" alt="Neil De Grasse Tyson saying, `Duuudddde let's do this.'"></img>

**Comment by amenity** [comment]
We'll be iterating on these for sure, but I'm going to call the first drafts done.
