### ISSUE TITLE
Feature: RCA Approval System Set Up Single Sign On

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19319]
Set up SSO for RCA Approval System 

Not sure what the steps are for getting this set up

**Comment by dianamartin** [comment]
# 10/8/2024
- [x] Followed GitBook [Help Guide SSO](https://atd-dts.gitbook.io/atd-knack-operations/knack/single-sign-on/single-sign-on)
- [x] Created CTM SN ticket: [`INC0437705`](https://atx.servicenowservices.com/now/nav/ui/classic/params/target/incident.do%3Fsys_id%3Db52e327e9741d2540eacb247f053aff7%26sysparm_stack%3D%26sysparm_view%3D)
- [x] Pinged Michael S. to let him know per Chrispin's suggestion

**Comment by ChrispinP** [comment]
The Office of the Director app is now live with SSO.

IP Cert saved in 1Password, certificate expiry matches all other Knack apps

JS & CSS added for big SSO button

Tested and working, complete

**Comment by dianamartin** [comment]
# 10/9/24
- [x] Tested the SSO 
![image](https://github.com/user-attachments/assets/1ed57c3b-9b19-4094-ade2-d8cbd8e84e63)

**Comment by stephaniemoorer** [comment]
Confirmed SSO for OOD app works great. 
Tested from approval email link
Could log in and make Decision on RCA.

Closing this issue
