### ISSUE TITLE
IT Support: Adobe crashing

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#19321]
BEN WHITE

## Device & User Information (first name and last initial, no last names)
Alexandra B 

## What's the problem?
Adobe crashing and needs

**Comment by Vaishnav1397** [comment]
Reached out to user and user mentioned that there was a long update taken place few days before. After the updates there is no issues related to adobe. mentioned user to reach out to team if there is any further issues.
