### ISSUE TITLE
TCP-CMU End-to-end testing configuration

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#19345]
Rebuild customer accounts in test, or figure out another way for us to do end-to-end testing.

**Comment by ChrispinP** [comment]
- [ ] Create links to the New Customer Portal (for customer testing)
- [ ] Allow anyone with the Knack Tester role to view the new views
- [ ] Any record whether case or cycle created as a Test record when opened will only be able to see new views

**Comment by ChrispinP** [comment]
complete, closing

staff users will need to be given Knack Tester role if they want to see some of the new views such as Messages
