### ISSUE TITLE
HR Digital Interview Adding Posting Details

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19369]
There is one area that seems disjointed

When the Recruiter is adding information for the Posting some of the information is entered from Edit Hiring Information page and some is entered from the Posting Management page

Steps I used as a Recruiter

- Edit Hiring Information
- Enter Minimum Quals
- Enter License/Certifications

To complete the Posting Information I have to use the Posting Management page

- Enter Preferred Quals
- Enter Notes to Applicant
- Enter Supplemental Questions

If the Recruiter could enter all of the Posting Information from the Edit Hiring Information page it could be cleaner.
The Posting Management | HM page could then be just for HM to edit/approve items specific to them

- [ ] To accomplish this we would need to add the fields from **Posting Management** page to the **Edit Hiring Information** page:

Preferred Quals
Notes to Applicant
Supplemental Questions

- [ ] Remove Preferred Qualifications button from Posting Management | HM page

**Comment by stephaniemoorer** [comment]
@dianamartin Oh Ok... Let me check I think I have a email from Tina.
Forwarded email to Diana

**Comment by dianamartin** [comment]
# 10/9/24
- [x] Updated "Edit Hiring Information" (Recruiter)
![image](https://github.com/user-attachments/assets/c06c9116-c659-46bc-b4cc-4daf63a1a2b6)

**Comment by stephaniemoorer** [comment]
this will be reviewed as part of usability testing with the stakeholders
closing this issue
