### ISSUE TITLE
Testing - HR Digital Interview Usability Testing Pre Interview & Interview Details

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19363]
We are at a good point where we need the stakeholders to do some hands on Usability Testing for Pre Interview and Interview Details

Modules to test:

- Posting Details
- Adding Applicants
- Candidate Screening Matrix
- Connecting Candidates to Interview
- Interview Details
- Interview Schedule
- Interview Times

**Comment by stephaniemoorer** [comment]
https://docs.google.com/document/d/1l01ORoHg6hLEMfMph99sjGJbzxwAjJQhQ7rHo81tXTw/edit#heading=h.vd7jwgdjck8a

**Comment by stephaniemoorer** [comment]
primary HR recruiter was not available for testing during the scheduled Sprint Review meeting. 
Could not coordinate any other time with her for testing. 
Will do testing during the next Sprint Review meeting Nov 4th.

**Comment by dianamartin** [comment]
# 11/4/2024
Participants: Jennifer, Stephanie and Diana

- She thinks she on the Vacancy Report; she’s on the “Hiring Management”
    - Maybe we call it “Posting Analysis”
- [ ] Remove "Add Posting"
- [ ] Rename "View" to "Edit" (with icon, like Vacancy Mgmt)
- She noticed the “Requisition #”, she realized it pulled from the Vacancy Report
- She clicked “Edit Hiring Information”
    - Reviewing stuff from Vacancy Report
    - Added Tina to “HR Assigned To”
    - Added her Phone Number
    - Pasted Qualifications
    - Pasted License and Certifications
    - “PCN Compensation” - she wasn’t sure what it is here
        - we told her enter job name
    - She mentioned “Hiring Type” they can do later (it’s not required already)
    - Would prefer Hiring Managers to populate: **Preferred Quals, Notes to Applicants, Supplemental Questions**

Stephanie demoed Hiring Manager part
- Added Preferred Quals
- Edit Posting Information
- Min & License - not editable (on purpose)
    - [ ]  Change the Submit Rule, doesn’t redirect to parent - MODIFY
- [ ]  Need to build out Status Button for HM to kick back to recruiter
- [ ]  Add more questions:
    - [ ]  **How long for posting up?** - NEW!
        - [ ]  Min: 7 days
        - [ ]  Max: 45 days
    - [ ]  **Rounds of Interviews? ** - Rounds 1 to 2  - NEW!
    - [ ]  **Assessment?** HRD leave  - NEW!
        - [ ]  Yes/No
    - [ ]  **Who they interview panel members to be** - Paragraph Text  - NEW!
        - [ ]  Panel Member 1 - (default Hiring Manager)
        - min: 3, max: 5
        - FTE/Temp can be panel members

Back to Recruiter 

## Review Posting Information from HM

- Add to Vacancy Report
    - Posted Status
    - Closed Date
- She added a milestone to 100964!!!
- [ ]  Remove milestone to 100964!!! - DELETE TEST MILESTONE
- She added candidates (using the manual entry)
- Inline edited the candidate information on the table (maybe include instructions?)
- [ ] Add Instructions
- [ ] Send to HM - notify by email?
- [ ] HM updates Candidate Matrix  - notify by email?
- [ ] **Future Enhancement**: Candidate Screening - no highlights - REPORT for PIR

## Set up Interview
- Connect Interview
- Added Applicants, clicked Add to add them as candidates
- Interview hyperlink can take them to Interview Mgmt. page
- Clicked Add Attachment
- Add Panel Members 
- [ ] check the filter - "Active" - MODIFY
- [ ]  Update Submit Rule - Interview Times, doesn’t redirect to parent - MODIFY

## Overall Feedback
- good feel
- got lost a little bit, took notes and guided her

# To Do

**Comment by dianamartin** [comment]
## User Feedback Updates from meeting
- [x]  Change the Submit Rule, Hiring Manager (Edit Posting) doesn’t redirect to parent - MODIFY
- [x]  Check the Interview Panel, Employee selection filter - "Active" - MODIFY
>This is connection to the "Employees" table. Might need to get Charlie to bring in "User Status". Seeing inactive users on the drop down list.
- [x]  Update Submit Rule - Interview Times, doesn’t redirect to parent - MODIFY
- [x]  "PCN Compensation" field - include context for recruiter on what to do - DO AS PART OF THIS ISSUE
![image](https://github.com/user-attachments/assets/8ab96dbb-4843-417f-b7fb-67cc3b7a07d7)

**Comment by stephaniemoorer** [comment]
@dianamartin just moving these to the To Do List

- [ ] Remove "New Posting" from Hiring Management dashboard
- [ ]  Rename "View" to "Edit" (with icon, like Vacancy Mgmt) on Hiring Management dashboard
- [ ] On the PCN Compensation context you added. 
Can you change "Position Name" to "Job Title" to match the wording on the page and remove the space between the wording and the box

![image](https://github.com/user-attachments/assets/1f429b4f-5d1d-424c-8e97-12477b553833)

**Comment by dianamartin** [comment]
# 11/7/24 
- [x] Remove "New Posting" from Hiring Management dashboard
- [x] Rename "View" to "Edit" (with icon, like Vacancy Mgmt) on Hiring Management dashboard
- On the PCN Compensation context you added.
  - [x] Can you change "Position Name" to "Job Title" to match the wording on the page and remove the space between the wording and the box

## Hiring Management page
![image](https://github.com/user-attachments/assets/bc557c37-40c6-4ded-83d3-493847412977)

## Edit Hiring Information form
![image](https://github.com/user-attachments/assets/50c4d156-beb1-4f52-aaca-f7ee2a4d2f22)

**Comment by stephaniemoorer** [comment]
Completed the items identified during usability testing with Jennifer.
Closing this issue.
