### ISSUE TITLE
[Living Streets] Configure Resubmittal Button Visibility for Healthy and Play Streets

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#19376]
## Tue 10/8/24 
* from Jonathan via Teams: 
"we want the resubmittal button to go live 2 months before the activation is over. So for the 2024-1 activations that were approved that would be november 1"

- I mentioned this is a busy time and he noted that there is "no huge rush on this" 
- ❗ BUT there is a November 1 deadline looming

- we had a slightly different note from the previous meeting Fri 9/27/24 (focused primarily on NBP): 
"Two months before the end of an activation - we should open up the renewal process button for folks. At the start of the next overlapping cohort, we can open up the previous cohort for renewals." 

- There are a number of things to scope out: 
     - What this looks like with the current 2024 -1 activations
     - What would this mean for any non-Approved applications
     - How to work from the end date, and the end dates for activations reliable

**Comment by patrickm02L** [comment]
## 10/9/24 - Refinement
There are two options
- DTS will manually activate the renewal button for previous cohorts (easy)
- Automate this activation for rolling cohorts (more complex)

**Comment by KaroEngstrom** [comment]
## Wed 10/23/24
- Jonathan noted via Teams that it's time to think about turning this feature on
- details: 
    - **Deferred status**: "we want to display it for any application in the Deferred status"
    - **Approved status**: "For the the Approved status, we want only want to do it for the ones where the activation is coming to an end. So we don't want to display it for the applications that were just approved. Can we display it based on some sort of cohort and status combo?"
    
**Prep for Thu 10/24/24 meeting**
- [ ] Check cohort from the initial renewal records 
- [ ] Assess lift for configuring renewal button 
- [ ] Write out plan for longer-term maintenance of this model

**Comment by KaroEngstrom** [comment]
## Thu 10/24/24 
- met with Jonathan to assess options 
- for the short term (rest of the calendar year 2024), we will go with: 
    - IF Status = Deferred, show Resubmittal button 
    - IF Status = Approved AND Activation Count = 2, show Resubmittal button (this will show the button to the original Approved cohorts that renewed their application over the summer)
 - we discussed that this is not a long-term solution in the new year, we will need to determine the longer-term conditionals for the Approved standard to allow resubmittals 
     - this needs to be based on Application = Approved PLUS some other condition

![image](https://github.com/user-attachments/assets/78962731-54d5-46ad-b5e4-ee9475128fb0)

Steps
- [ ] Update page rules in TEST
- [ ] Test views as Applicant
- [ ] Update the page rules in PROD
