### ISSUE TITLE
Research ways to identify manual lat/lon edits to historical records

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#19388]
When we populated the `crashes_edits` table via https://github.com/cityofaustin/atd-data-tech/issues/17207, we had not reliable way to determine if the edit was the result of a manual user edit, or if CRIS had updated values that never propagated to the old DB.

This resulted in many thousands of crashes having latitude and/or longitude "edits" that may or may not be the result of manual QA by the VZ team.

Xavier has asked for our help trying to correctly attribute these changes to CRIS vs VZ staff, so that they can have more confidence in various analyses they undertake.

**Comment by johnclary** [comment]
i asked @frankhereford to spin up an RDS snapshot for this task. once that's done i will work on a few queries to see if we can come up with any quick answers.

**Comment by johnclary** [comment]
i sent Xavier this query and attached a spreadsheet of about 28k crashes. he reports that no additional action is needed on our side.

```sql
with crashes as (
    select
        crash_id,
        latitude,
        longitude,
        latitude_primary,
        longitude_primary,
        LENGTH(SPLIT_PART(CAST(latitude_primary as TEXT), '.', 2)) as lat_length
    from
        atd_txdot_crashes
    where
        latitude_primary is not null
        and latitude_primary != latitude
)

select * from crashes where exists (
    select 1
    from atd_txdot_change_log as log
    where log.record_crash_id = crashes.crash_id
    and log.record_type = 'crashes'
    and log.updated_by is not null
    and log.updated_by !='SYSTEM'
    and log.updated_by != 'System'
) and lat_length > 13;
```

**Comment by johnclary** [comment]
@frankhereford you are free to spin down that `pre-data-model-vz-cluster` RDS instance anytime—thank you for your help on this!

**Comment by frankhereford** [comment]
@johnclary wrote:

> you are free to spin down

You bet - I'll zap it right now. Thanks!
