### ISSUE TITLE
Update the postgrest EC2 to use ubuntu

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#19397]
We identified an opportunity to update our OS on the EC2 that runs our postgrest services using Docker to use ubuntu instead. We use ubuntu on our other EC2 machines, and we are all more familiar with it than the current OS.

Here are the steps that we identified for testing the upgrade to postgrest itself to make sure everything continues to run as expected:
- https://github.com/cityofaustin/atd-postgrest and https://github.com/cityofaustin/atd-postgrest/blob/main/docker-compose.yaml
- pg_dump database and make sure it can be restored
- if so, yolo upgrade postgrest and make sure it works
- there are multiple containers so we could pick one to upgrade and observe without affecting others (fyi version are not pinned)
- involve Charlie

**Comment by mddilley** [comment]
Marking this as blocked by the PostgREST upgrade so we have a better idea of how those services run.

**Comment by frankhereford** [comment]
Got this knocked out - this is now running ubuntu 24.04 LTS and will keep itself up to date with security patches that are released. We should still swing through on the regular to reboot it for new kernels and the like, but all in all, this is a big upgrade.
