### ISSUE TITLE
IT Support: [Move over and setup of meeting rooms A and B]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#19419]
St Elmo
## Device & User Information (first name and last initial, no last names)
Cables/ TV, Tables & Floyd, B
## What's the problem?
User requested us helping to move the stuff for making the meeting room have space to setup for Ctm
## What did you do to resolve the issue
Have informed matt and probably will start working it in the noon.

**Comment by Matthew-M-TPW** [comment]
Moved equipment
