### ISSUE TITLE
Cleanup Look & Feel for Customer Portal, Task Board, and Navigation

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#19424]
Cleanup the design for CMU to prepare for launch/UAT

- [x] Customer Portal
- [x] Task Board
- [x] Task Board info views
- [x] Big Buttons
- [x] Back Links
- [x] Back Buttons
- [x] Account Management / Profile
- [x] Customer/Org Management
- [x] Case Details views (CSWZ & TCP)
- [x] Page/Nav Menus

**Comment by KyleErich** [comment]
This appears to be identical to #19423. Closing due to duplication.

**Comment by ChrispinP** [comment]
Removed Action buttons from TCP Details

**Comment by ChrispinP** [comment]
I have completed cleanup of menu navigation, details views & pages, and some record rules. As part of this work, we also addressed any action items from our previous meeting that were minor fixes.

Complete, ready to close and begin UAT

**Comment by ChrispinP** [comment]
Any new UAT enhancements or bug fixes will be captured in #20379 

complete closing
