### ISSUE TITLE
Update TCP Case Management Emails and Pop-ups Per Feedback 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#19422]
- Samson submitted four documents of their reviewed items 
- [x] Compare these to the existing verbiage and update as needed 

**1. TCP Conflict-Shared Modal Pop-Up Information - Cycle Status**
     * User is asking for further functionality (combine statuses for Applicant views): 
     ![image](https://github.com/user-attachments/assets/ace06c53-37c9-4a26-b798-50f58ecfbe55)
 
**2. TCP Modal Pop-Up Information - Cycle Status**
     * Not seeing any changes here...

**3. Current - New Conflict Shared Request Confirmation to Submitter**
     * User question from Samson: "Are we going to use Knack to respond to customers or do the reviewers need to email the customers?"
     
**4. TCP and Conflict-Shared Modal Pop-Up Information - Due Date**
     * User comment: 
     ![image](https://github.com/user-attachments/assets/c8cbaea5-e8f5-418c-b3bf-dd2d9de3d1aa)
 

@KaroEngstrom planning to do week of 10/14/24
FYI @ChrispinP

**Comment by ChrispinP** [comment]
Actionable items on this ticket have been resolved. closing
