### ISSUE TITLE
Meeting RCA Approval System Prototype Demo

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19457]
Meeting scheduled 10/29/24

[Agenda](https://docs.google.com/document/d/13-EN9kLKBDO6VJJ5SEmwbCZ5cO9B-fXap_kfPHi6Cec/edit?tab=t.0#heading=h.3n23h0binlm4)

- Discuss CDS demo 
what did you like about the process
what concerns you may have about the process
- Demo RCA Approval Prototype developed in Knack
- Next Steps

**Comment by stephaniemoorer** [comment]
Discussion items:
Just pointing out the difference in their approval steps:
If you review the recording at time 7:05 to 9:50 it shows the approval steps

- they track edits to any of the documents

- when they first create the RCA they assign the PM, RCA SPOC, Dept SPOC, AD, DD, Director
so when it gets approved it automatically gets assigned to the next person
From PM to RCA SPOC to Dept SPOC to AD to DD to Director

I like the automatic assignment to next approver.

**Comment by dianamartin** [comment]
# 10/29/24
## Diana's Notes
Participants: Gilda, Rey, Karla, Gilda, Natalie? Stephanie, Diana

## Demo
Financial Process - Submitted one on Friday for Dec 12th. 

Enhancement 
- Announcement to remind users about early submittal

Changes
- Renaming - "Edit RCA" to "Edit Cover Page" 
- Renaming - "+Posting Language" to "+ RCA"
