### ISSUE TITLE
IT Support: [Battery and Charging Issue-INC0439172]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#19462]
Ben White
## Device & User Information (first name and last initial, no last names)
Laptop/ Battery & Choate, C 
## What's the problem?
Have problems with the laptop charging and need to look into it
## What did you do to resolve the issue
Forwarded the request to matt as he is in ben white and can have a look into it.

**Comment by Matthew-M-TPW** [comment]
user is bringing it to Ben White on Friday. He is going on vacation. 

When he bring it in test the battery and call Dell if needed

**Comment by Matthew-M-TPW** [comment]
machine was swapped out
