### ISSUE TITLE
IT Support: user coming in to pick up loaner laptop

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#19487]
BEN WHITE 

## Device & User Information (first name and last initial, no last names)
Laura D
## What's the problem?
Willie
Matt & Craig will have the laptop, HDMI cable and charging cable for you tomorrow morning. Stop by my office for the extension cord. 
Thanks,
Laura

**Comment by Craigjacobs-ATX** [comment]
duplicate ticket , please refer to #19486
