### ISSUE TITLE
IT Support: [Ipad profile reset, No login poasscode]

### ISSUE THREAD

**Issue by Vaishnav1397** [cityofaustin/atd-data-tech#19491]
St Elmo
## Device & User Information (first name and last initial, no last names)
iPad & Jay, C
## What's the problem?
Supervisor got the iPad returned by old user and need to rest that back, no passcode is available.
## What did you do to resolve the issue
Have checked to reset it but it might need the passcode, which is setup by the user, trying to get it reset but cannot be able to, @Matthew-M-TPW Can you please check and see by any chance we can recover the passcode for this iPad?

**Comment by Matthew-M-TPW** [comment]
sent ticket to have device moved to TPW domain INC0441936

**Comment by Matthew-M-TPW** [comment]
reset ipad and deployed it to forestry
