### ISSUE TITLE
Fulcrum Subscription for Signs Work Orders

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#195]
We currently have a Fulcrum subscription for two users that will need to be expanded for named user accounts for all signs technicians (~12 people). We need to subscribe to the "Professional" plan, which supports full record history. We do need the next level, enterprise, which is a value for 100+ users.

$30/user/month * 12 users * 12 months = $4320/year.

**Comment by amenity** [comment]
@johnclary will submit PR by the end of this sprint (end of June)...

**Comment by johnclary** [comment]
Moving to backlog as we are not moving forward with Fulcrum until TBD.

**Comment by johnclary** [comment]
Closing because we built this in Knack.
