### ISSUE TITLE
Help User Cathy K. with SMD Knack Permissions

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#19518]
From Daniel S. via email: 

"Cathy K. was unable to give me editing rights for the Signs Asset List in Knack this morning. Is there a way to give her the permissions to do that? Furthermore, both Cole H. and I need to be able to update the Signs Asset List in Knack?"

**Comment by susannegov** [comment]
- [ ] Rename `Signs | Asset Items` to `Manage Signs | Asset Items` for https://atd.knack.com/signs-markings#work-order-signs/asset-items-signs/ to make it more clear

**Comment by susannegov** [comment]
Sent Teams message to Cathy

> We looked into the sign asset list. https://github.com/cityofaustin/atd-data-tech/issues/19518
> - This is the URL for manage/edit/add signs https://atd.knack.com/signs-markings#work-order-signs/asset-items-signs/ 
> - This is the URL for viewing sign asset list only (Read-only) https://atd.knack.com/signs-markings#work-order-signs/asset-list/
>
> We renamed the tables/buttons and added a redirect to edit button to better differentiate between read only/edit access. The button is only viewable to those with supervisor/inventory viewer role. I looked at both Cole and Daniel's role so they should both have edit access from the first link for managing sign assets, but let me know if they are still running into issues using this URL to edit the sign assets https://atd.knack.com/signs-markings#work-order-signs/asset-items-signs/

**Comment by susannegov** [comment]
Response 
> Thank you for keeping me in the loop!
