### ISSUE TITLE
Update Moped Power BI dataflow to refresh data hourly

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#19512]
Nathan W. has requested to increase the update frequency of the Power BI dataflow refreshes to every hour from once per day. He is looking to see edits in Moped projects reflected more frequently in the data available through this integration to see those edits reflected in the Power BI dashboards that he is building. You can see an example of a dashboard [here](https://app.powerbigov.us/groups/me/reports/067a71a2-2a19-4f5b-b6ba-d889b123daec/e7bb6f0fd0a2fd0cd43a?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f). If you have trouble seeing the dashboard, let me know, and I can help you get access.

**In Scope**
- Update dataflows to refresh every hour

**Comment by Charlie-Henry** [comment]
<img width="1280" alt="Screenshot 2024-10-17 at 10 06 42 AM" src="https://github.com/user-attachments/assets/284e1e67-6cf6-4739-99c3-f189c5e0cc54">

@mddilley I set up the hourly refresh. I've shared the power automate flow with Susanne and the service desk email. I hope that means it'll stick around if my account is ever deleted.

**Comment by mddilley** [comment]
Awesome - thank you @Charlie-Henry 🙏 🙌

Since you went with the Power Automate (less tedious option iirc), does this mean that it could be even more frequent in the future?

**Comment by Charlie-Henry** [comment]
yeah looks like we can do pretty much any frequency!
<img width="624" alt="Screenshot 2024-10-17 at 11 29 19 AM" src="https://github.com/user-attachments/assets/1f172717-0050-491d-9fbf-2bb5b8bd9150">
