### ISSUE TITLE
Enhancement RCA Approval 

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19540]
New RCA

- [x] Add Division with a drop list of TPW Divisions
![image](https://github.com/user-attachments/assets/142a631a-1355-48d3-8ef8-0d15a4f10379)

**Comment by stephaniemoorer** [comment]
@dianamartin 

Questions:

1. Should New RCA be available without signing in?

![image](https://github.com/user-attachments/assets/2eec80d4-2e39-44c1-8a91-95666c16a74a)

2.View RCA Details/Posting Language
Are we assuming they will be completing the RCA template outside of Knack (like they do now) then copy/paste into the Posting Language section?

3. How does the Status get updated? 
Is this still to be developed when we better understand the approval routing process?

**Comment by dianamartin** [comment]
# 10/24/24
@stephaniemoorer 
- [x] Added `Division` to `request_for_council_action` object table
  - took majority of list from HR Accounts>Division list
- [x] Renamed URL slug "Request for Council Action" to "RCA Dashboard", changed icon
- [x] Renamed "Request for Council Action" to "RCA Dashboard" on page, changed icon

## New RCA
I would say, we'd like to get have it where the user who is requesting a new RCA is logged in. 
- I can change that so it's not available if they're not logged in

## Working on Posting Language
I imagined them working on the language inside the system, but that's dependent on how the users feel. We developed it so they can work on it in the system.

## Status Changes
- We'll learn more once we show the users the process

**Comment by stephaniemoorer** [comment]
@dianamartin 

These updates look great!!! Thanks
Closing this issue
