### ISSUE TITLE
Enhancement TPW Hire HR Vacancy Report

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19543]
Tina and Alex were discussing how helpful it would be to add more milestones for Vacant Reclassifications.  Highlighted is what we would like added for Reclassification Milestones:

- [x] Add these new Reclassifications Milestones to the TPW Vacancy Report

**RECLASS-FAS requested from Finance
RECLASS-PRF/FAS sent to AD
RECLASS-PAQ requested from Manager
RECLASS-Request HR Manager to review PAQ**

**Comment by dianamartin** [comment]
# 10/21/24
- [x] Updated `Milestone Type` field on `pcn_date_tracking`
- [x] Added Choices
  - `RECLASS-FAS requested from Finance`
  - `RECLASS-PRF/FAS sent to AD`
  - `RECLASS-PAQ requested from Manager`
  - `RECLASS-Request HR Manager to review PAQ`
![image](https://github.com/user-attachments/assets/1bdec4c2-8cd2-4e11-9fed-385cdd09c091)

**Comment by stephaniemoorer** [comment]
Notified HR the new RECLASS milestones have been added as requested,
