### ISSUE TITLE
Add Maximo DTS Ticket Submission Message to Knack

### ISSUE THREAD

**Issue by rebekkabry** [cityofaustin/atd-data-tech#19594]
# Background 
- When submitting tickets for account creation stakeholders do not remember the eta. We would like to add a message when they have submitted a MAXIMO DTS support ticket. 

https://github.com/cityofaustin/atd-data-tech/issues/19484

Discussed with Diana, 10/22. 
- Email portion 
- Create a rule for - when application "Maximo" selected. 
- add the following message to the confirmation of submission page. 

>Please be advised: For account creation, there is a minimum of 3 day waiting period from the time of submission (given that all information is provided, even if "Urgent" is selected)

**Comment by dianamartin** [comment]
# 10/25/24
@amenity @patrickm02L did you guys need to know about this prior to me proceeding? 

Essentially, it's creating a 2nd email when a user submits a DTS Request that has submitted for the application "Maximo". The Maximo team wanted to give a communication to their users that the "account creation" process can't be turned around urgently as they're dependent on CTM to perform a task first.

**Comment by patrickm02L** [comment]
@dianamartin I don't have any qualms about this update when Maximo is selected. Also, I think that disclaimer (please be advised...) that is in the description of the Issue works. 

Does it make sense to add a note that account creation can take up to 3 days in the SR form too?
<img width="682" alt="Screenshot 2024-10-25 at 1 09 08 PM" src="https://github.com/user-attachments/assets/750d0de5-f403-4dde-bb0f-e6605db00a41">

**Comment by dianamartin** [comment]
Yeah, that's also a good alternative. I can let the team know the options.

**Comment by rebekkabry** [comment]
@patrickm02L @dianamartin 

I agree, think that is a great option to add to the SR form (in the least amount of words as possible). Could we still also have it on the confirmation page of the email when "maximo" is selected? 

Maybe: Please be advised, may take at least 3 days....or something along those lines as you mentioned.

**Comment by dianamartin** [comment]
@rebekkabry 
For the Account Creation expectation issue we're trying to address, the think the solution Patrick mentioned is reasonable. 

The email can be done, but I'd rather not because it's another thing we'll being maintaining and I don't know if adding it will end up sending 2 emails for when a user is selecting that request type. We are planning to change the DTS service request process soon 🤞🏽. Hopefully, we can address the additional notices/reminders with the email we're already planning on sending out to Maximo users.

**Comment by rebekkabry** [comment]
@dianamartin thank you for the updates. I agree @patrickm02L is a good solution.

Is there anything further from the Maximo team needed?

**Comment by dianamartin** [comment]
# 10/28/24
During Maximo Sync, we updated the language on the "Maximo" section. 

![image](https://github.com/user-attachments/assets/eb1aeee0-7fcd-4c8c-be52-e345497f888d)
