### ISSUE TITLE
Fee Update FY 25 - Need to reinstate the Street Damage Recovery (50160) - (On Prod)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#19600]
**Acceptance Criteria**

- Per ROW group, the Street Damage Recovery Cost (50160) and Valet Sign Installation (50195) needs to be reinstated in the Insert & Run Procedure menu since this inserts other fees as well.

**Comment by vschandramouli** [comment]
CC @Nadin-Nader

**Comment by Lpriya-LIT** [comment]
Update - Committed changes and requested for Dev and Test promotion , SCTASK0466892

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Ready for UAT on Test

**Comment by KyleErich** [comment]
@Nadin-Nader @Lpriya-LIT @vschandramouli I'm a little confused on this ticket. The AC includes an additional item not listed in the title (reinstating Valet Sign Installation). And there is no mention of which specific folder types this reinstation applies to, so I'm not exactly sure the parameters for a successful UAT.

**Comment by Lpriya-LIT** [comment]
Update:

1. Valet Sign Installation (50195)  - This fee is for RW folder , it has been reactivated and added back to RW folder insert and run procedure menu 
 
2. Street Damage Recovery Cost (50160) - There is no fee procedure for this fee , it has been re-activated , can be inserted manually . This is for EX folder

**Comment by Lpriya-LIT** [comment]
<img width="1124" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0R0Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d96703cdf3c9a589015bd0a532249fd61bdb6f21/image.png" alt="image.png" />

**Comment by Lpriya-LIT** [comment]
<img width="1459" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2J0Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efa393e1e04dee6ecf66c0315c5bf3f5cdac436f/image.png" alt="image.png" />

**Comment by KyleErich** [comment]
@Lpriya-LIT @Nadin-Nader UAT on Test approved, thanks.

**Comment by Lpriya-LIT** [comment]
Update - Created Prod deployment request , SCTASK0475466

**Comment by Lpriya-LIT** [comment]
Update - Changes deployed to Prod , Ready for UAT

**Comment by KyleErich** [comment]
@Lpriya-LIT @Nadin-Nader UAT on Prod approved, thank you.

**Comment by Nadin-Nader** [comment]
Approved, closing
