### ISSUE TITLE
Create Prototype of OA application

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#19617]
## Description
Create a multi-page application flow for Operating Authority applications with proper data structure and user interface.

## Success Criteria
- Complete applications can be submitted
- Documents can be uploaded and verified
- PLAs can review and approve/deny applications
- Status updates are communicated to applicants
- Reports can be generated for tracking

## Notes
- City of Austin [webpage](https://www.austintexas.gov/services/apply-operating-authority-license) for Operating Authority applications
- [Miroboard](https://miro.com/app/board/uXjVNj7uM5A=/)
<br>
<img width="1030" alt="Screenshot 2024-10-25 at 1 49 00 PM" src="https://github.com/user-attachments/assets/1dc7cf10-6354-4402-bb41-f410a737b172">

**Comment by patrickm02L** [comment]
# Build Notes

## Data Structure

### Objects/Tables Required

#### 1. Service_Type
   - Fields:
     - Limosine Service
     - Shuttle Service
     - Charter Van
     - Pedicab Service
     - Electric Assist Pedicab Service
     - Touring/Sightseeing
     - Taxicab Service  

#### 2. **Business_Information**
   - Fields:
     - Company Name* (text)
     - Phone Number* (phone)
     - Fax Number (phone)
     - Email* (email)
     - Business Address*
     - Created Date (auto-timestamp)
     - Status (multiple choice: Active, Pending, Inactive)
     - Operating Authority Number (auto-generated)
     - Operating Authority Expiration (date)

#### 3. **Authorized_Persons**
   - Fields:
     - Full Name* (text)
     - Driver's License Number* (text)
     - Phone Number* (phone)
     - Years of Texas Residency* (number)
     - Address* (address)
     - Criminal History Disclosure (paragraph text)
 
     + Add Another Person

#### 4. **Vehicle_Information**
   - Fields:
     - Year* (number)
     - Make* (text)
     - Model* (text)
     - VIN Number* (text)
     - License Plate* (text)
     - Passenger Capacity* (number)
     - Connection to Companies (many-to-one)
    
#### 6. **Insurance**
   - Fields:
      - Insurance Company Name* (text)
      - Agent Name* (text)
      - Agent Phone Number* (phone)
      - Agent Insurance License Number* (text)

#### 7. **Required_Documents**
   - Fields:
     - File Upload (file)
     - Upload Date (auto-timestamp)
     - Connection to Applications (many-to-one)
 
#### 8. **Applications**
   - Fields:
     - Application Number (auto-generated)
     - Submission Date (auto-timestamp)
     - Status (multiple choice: Draft, Submitted, Under Review, Approved, Denied)
     - Review Notes (paragraph text)
     - Payment Status (multiple choice)
     - Connection to Companies (many-to-one)
     
     + Add another Service Type

## Page Structure

### Public Pages

#### **Landing Page**
   - Welcome message
   - Application requirements
   - Start application button
   - Login for existing companies
   
#### **Application Pages**

#### **Application Review Page**
   - Summary of all entered information
   - Edit buttons for each section
   - Terms and conditions
   - Submit and pay button

#### **Confirmation Page**
   - Application reference number
   - Next steps
   - Download application copy

### Admin Pages

#### **Application Review Dashboard**
   - List of pending applications
   - Quick status updates
   - Search and filter options

#### **Detailed Application Review**
   - All application details
   - Document verification interface
   - Approval/denial workflow
   - Notes and communication log

#### **Company Management**
   - List of all companies
   - Operating authority status
   - Renewal tracking
   - Compliance monitoring

### Required Features

#### **Form Validation**
   - Required field validation
   - Format validation for:
      - Phone numbers
      - Email addresses
      - VIN numbers
      - Driver's license numbers
   - Minimum vehicle requirements
   - Document type restrictions

#### **Application Flow**
   - Save progress functionality
   - Section completion tracking
   - Previous/Next navigation
   - Edit capabilities before final submission

#### **Document Management**
   - File type restrictions
   - File size limits
   - Multiple file uploads
   - Document status tracking

#### **Payment**
   - $159 application fee processing
   - Payment confirmation
   - Receipt generation

#### **Notification System**
   - Application status updates
   - Document verification results
   - Payment confirmations
   - Additional information requests

**Comment by susannegov** [comment]
# 11/05
- Created Company Account
- My Account and My Application separated by user role
   - Details view
- Added JS for "Start Operating Authority Application" big button

**Comment by susannegov** [comment]
# 11/06
- Created `Companies_Authorized_Person`

**Comment by susannegov** [comment]
# 11/07
- Added `Authorized Person` form
- Added audit fields for Company_Authorized_Person
- Add `application_vehicles` object table

**Comment by susannegov** [comment]
# 11/08
- Added insurance fields to `application_operating_field` object

**Comment by susannegov** [comment]
# 11/12
- Created test record and it passes

# To do
- Update forms and naming
- Add step indicator
- Add a print page function

**Comment by susannegov** [comment]
# 11/13 
- Added list of vehicle grid
- Add inline editing for vehicles
   - inline grid editing versus edit form from authorized person (which one prefer?)

**Comment by susannegov** [comment]
# 11/14
- Add Business Autofill form
- Add notarize web page - need to fill info

**Comment by susannegov** [comment]
# 11/15
- Modify CSS for step indicator

**Comment by susannegov** [comment]
# Attachment Types
- Background
- Insurance
- Authorized Person
- Vehicle Information
- Notarize Document

**Comment by susannegov** [comment]
#11/20
- Added `Horse-Drawn Carriage` as Service Type
- Fixed `Limousine` misspelling as a Service Type

**Comment by susannegov** [comment]
# 11/25
- Added Connected Record of attachment file for
   - Business Documentation
      - Proof of Business
      - Texas Secretary of State Certification
      - Independent Contractor Agreement
      - Proposed Routes/Stops/Schedules
![image](https://github.com/user-attachments/assets/1d559736-8b1e-4453-a87c-cf874ea063ea)
      - Org Chart (taxicab only)

**Comment by susannegov** [comment]
# From sprint planning - apps
## To do
- Remove the 150 MB descriptions 
- Update the button fonts

**Comment by susannegov** [comment]
#12/3
- Added Vehicle photos
- Added Is the vehicle lease/rented
- Added connected records of attachments
- Added vehicle photos
- Added vehicle photo view similar to PEP

**Comment by susannegov** [comment]
# 13/04
- Added conditional rule if Attachment Vehicle Name is not Vehicle Photo, set to field value Attachment Vehicle Name for Attachment Vehicle Description

**Comment by patrickm02L** [comment]
Considering the Prototype in a stable state after the 12/5/24 meeting at the last MSP(Paul) Review. 

Continuing improvements on #20219
