### ISSUE TITLE
[TCP CMU] Mini Re-Design of Organization Management 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#19619]
Notes from Testing 10/25/24 for the App Administration page
- [x] Add tab to menu to house Manage Organizations functionality 
- [x] Move over Search Organizations view to Manage Organizations 
- [x] Update Edit Contacts button to just View
- [x] Update View page with additional fields to edit
- [x] Add menu to include Edit Organization button to a pop-up Edit form 
- [x] Populate edit form with appropriate fields 
- [x] Update code for backlinks

**Comment by ChrispinP** [comment]
Completed all items above. Updated design:
![image](https://github.com/user-attachments/assets/435b0422-b11d-4ac2-a573-ad64369ecfcb)

complete, closing
