### ISSUE TITLE
IT Support: Provide 2 additional tablets for SBO Time & Attendance project

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#19626]
Greg G. 
SBO

Emailed 10/21/24

>Concrete and Bridges are now using the time clocks as of this morning.
That just leaves Seal Coat, South District, and North District left.

>Can we get another iPad mounted soon at Dalton in the Concrete area? The tight corridor where the iPad currently is mounted makes it quite challenging for the whole Concrete crew to punch in.
A long line forms and I think it’s just too many people for one time clock.

**Comment by dianamartin** [comment]
# 10/28/24
I asked Greg to identify the two users that we would be assigning the tablets to
- Brad says either he or **Richard B.** can take ownership of the Concrete iPad, 
- and **Bardo M.**  will take the North District/Kramer iPad.

@susannegov can we see if the users are already in AirWatch? Richard B. and Bardo M.

**Comment by susannegov** [comment]
Submitted INC0443287 Created messaged Art
> Description - Description - The following 2 users need to be moved from the CTM/PWD organization group in AirWatch to TPW console organization group

**Comment by susannegov** [comment]
- Ticket from Service Now closed. I added device to both users on Airwatch

@dianamartin Tablets are ready to be issued out

**Comment by dianamartin** [comment]
# 11/4/2024
Greg, Christina and I messaged last week 10/30/24
>Hi Greg, 
 I did inventory of what we need for the 2 additional tablets to add to Kramer & Dalton. We have: 
>- 2 barcode scanners
>- 1 USB-C splitter
>- 1 barcode scanner mount
>- 2 tablets are ready to assign, 

>However, was wondering if SBO wanted to purchase the additional items:
>- 2 tablet mounts 
>- 1 USB-C splitter
>- 1 barcode scanner mount

He initially said
>That will probably be fine. I typically only purchase through Staples, but I believe I have an Amazon account as well

I said
>I can also purchase if you need us to, I just have to wait until Peggy returns next week

Greg said
>If you don't mind, I can wait for y'all to purchase it. Brad and Jorge are aware that it might take a while.
 
## TO DO
- [ ] Submit TPW PR
- [ ] Purchase Amazon Items
>- 2 tablet mounts 
>- 1 USB-C splitter
>- 1 barcode scanner mount

**Comment by dianamartin** [comment]
# 11/4/24
- [x] Created PR [2024-11-9700](https://atd.knack.com/finance-purchasing#purchase-requests/purchase-request-details/672951bd453d3b02a8764e20/)

**Comment by dianamartin** [comment]
# 11/7/2024
- [x] TPW PR was approve on 11/6
- [x] Ordered Amazon items on 11/7
- Expected delivery is 11/8

**Comment by dianamartin** [comment]
# 11/8/24
- All Items delivered to office
- Gathering all items to take with me so that I can bring to Townview next week, 11/13
@scottreedy FYI
- Took 2 of the 7 tablets from the DTS closet
  - `COAW74403`
  - `COAW74406`
When I deploy them, I'll update the Hardware asset inventory

**Comment by dianamartin** [comment]
# 11/8/24
Emailed stakeholder Greg G., Christina
>I have all the supplies needed for adding the 2 additional time clock locations. The items were delivered today at Cameron. I was planning on bringing the items with me on Wed, 11/13/24 to Townview. Also, I didn’t know how we wanted to handle implementing it. Did you want to lead on coordinating with the installations or did you want to have me and Christina around to deploy the tablets with Richard and Bardo the following week, the week of Nov 18-22nd. I’m looking at our calendars and Mon, 11/18 from 8 -11 am is looking open or Fri, Nov 22nd in the afternoon looks open. 

>Let me know what you guys think about how to coordinate these last two installs.

**Comment by dianamartin** [comment]
# 11/13/24
Reached out to Greg to see if today was a good day to drop off the tablets to him. 
>FYI - we're rescheduling the Maximo meeting, for next Friday but I can go to Townview today and drop off the tablet installation supplies. Unless you want me and Christina to schedule installations like we have in the past
 
He said
>Thank you for reaching out! I am out of office this Thursday and Friday (11/14-11/15) and I'm in NEO next Monday and Tuesday (11/18-11/19), but am free Wed-Fri next week. >Would you mind scheduling the installations like in the past? I'm not familiar with how y'all set up the iPads with the superintendents. It would also give us some time to catch up face to face on the status of the program.

**Comment by dianamartin** [comment]
# 11/21/24
Schedule installations
- [ ] Kramer: Thu, 11/21 at 1:15 pm - 2:00 pm

**Comment by dianamartin** [comment]
# 11/22/24
Schedule installations
- [ ] Dalton: Fri, 11/22 at 11:00 am - 12 pm
