### ISSUE TITLE
IT Support: Computer camera not working 

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#19637]
BEN WHITE

## Device & User Information (first name and last initial, no last names)
Tina S

## What's the problem?
Hi Matt, my camera is still not working on Teams. I have interviews right now, but will try and catch you after them early this afternoon. If I need to reach out to someone else, please let me know.

**Comment by Vaishnav1397** [comment]
Reached out to the user and mentioned that user is currently not in office and wanted to get it check when she is back to Cameron.

**Comment by Vaishnav1397** [comment]
Tried to resolve the issue, but the user is currently at home and busy with interviews. Informed us that she would get it checked on Wednesday at Cameron.

**Comment by scottreedy** [comment]
Updated bios and that fixed the problem.
