### ISSUE TITLE
Research: CIP Unique Key (SS)(Answered Qs)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#19634]
### Why was CIP Unique Key added to the UC folder? 

- When was info 76351 added to UC?
- Why and by whom?
- What other folders is this info coded on? 

If we can't get answers on this, TPW will remove it from the UC folder.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder 

1. CIP Unique Key (76351) info was created by Tom Leatherman(LEATHERMANT) on 04-23-**2019**(stampdate on VALIDINFO table).
2. It was configured to UC folder by Swapna on **12-18-2018** (stampdate on DEFAULTINFO table).
3. It is assigned to UC only.

### NOTE: The above stampdates are not meaningful to me. Usually, first info field is created on VALIDinfo table and then assigned to a folder type(DEFAULTINFO). But from the above stampdates it seems a record was created in DEFAULTINFO table and then VALIDINFO table. 

Thank you

**Comment by SubhaShroff** [comment]
@Nadin-Nader This ticket is updated with findings in the above comment. Thanks.

**Comment by TracyLinder** [comment]
ROW would like to remove this info from the UC folder. I will create a ticket.
