### ISSUE TITLE
[Tablet Support] AMD:  Assign existing tablet to David H

### ISSUE THREAD

**Issue by susannegov** [cityofaustin/atd-data-tech#19642]
Scott F. informed be Toby T returned his tablet and to reassign it to David H 

See [#19007](https://github.com/cityofaustin/atd-data-tech/issues/19007) - [Tablet Support] AMD: Add Toby T to airwatch and add device

**References:**
☁[AirWatch Management](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/airwatch-management)
🤖[Android Configuration](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/tablet-configuration)
🍎[iOS Configuration](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4LYhVrPWLmbRD1Xv0p/tablet-management/ios-tablet-configuration)

**Select Issues:**
- [ ] Purchasing Devices
- [ ] Setting up a New Device
- [ ] Setting up a New User
- [x] Switching Device User
- [x] Remove User & Wipe Device
- [ ] Create or Modify a Device Profile (such as passcode policy)
- [ ] Missing/Lost Device (alarm ping, lock, last location)
- [ ] Deactivate SIM card
- [ ] SIM/Network/Hotspot/WiFi/GPS
- [ ] Workspace One: Intelligent Hub app
- [ ] Launcher profile (such as Home Screen apps/shortcuts)
- [ ] App Catalog: New, Outdated, or Missing app or icon
- [ ] Unable to launch an app
- [ ] Unable to charge/turn on device
- [ ] Device Update/Version
- [ ] Retire a Device (outdated, bricked, no longer used)

**Device Details:**

| User | COA Tag | SN | IMEI | Phone | Brand, OS Version, & Device Type |
| --- | --- | --- | --- | --- | --- |
| FirstNameOnly | COA###### | ###### | ###### | ###-###-#### | Samsung Android 11.0 Tablet |
| David  | COAW79597 | HPVGY173RP | ###### | 737-270-3811 | Apple iPadOS 16 Tablet  |

**Confirmations:**
- [x] User in AirWatch (in TPW group, not CTM)
- [x] Device in AirWatch
- [x] Device Labeled with COA Tag, SN, IMEI, & Phone #
- [x] Device in DTS Inventory

**Comment by susannegov** [comment]
Messaged Scott
> Okay I made a new ticket and added David Hernandez on Airwatch https://github.com/cityofaustin/atd-data-tech/issues/19642. Good to issue it

**Comment by ChrispinP** [comment]
User Device still not in AirWatch, need to confirm if David completed setup.

**Comment by susannegov** [comment]
I have the physical tablet currently

I added the wrong David H in Airwatch (same name, different username) on airwatch and am going to submit another ticket on Service Now

**Comment by susannegov** [comment]
Handed off tablet to David H.
