### ISSUE TITLE
IT Support: unable to edit in Bluebeam and Adobe

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#19666]
BEN WHITE

## Device & User Information (first name and last initial, no last names)
Justin N
## What's the problem?

I've got a problem with my Adobe license and my BlueBeam license.  I don't seem to have the abilities to edit PDFs in Adobe (had Acrobat 2017 with old computer).  I also cannot comment or measure most BlueBeam documents that others in the City can edit... this all seems to have started after getting my new computer.  Spoke with V earlier and he said you're the one that has access to look at my license

**Comment by Vaishnav1397** [comment]
Bluebeam has been installed and laptop ready to go. User is out of office will reach out to him once he is back.

**Comment by Matthew-M-TPW** [comment]
provided user access to Bluebeam
