### ISSUE TITLE
TCP-CMU SPIKE: Auto-populate Applicant field for logged in user

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#19674]
### Spike: Auto-populate Applicant field for logged in user
- _Deadline is 11/5/24_

**GOALS:**
1. Provide the user a good experience by not requiring them to tell us who they are after they have logged in. 
2. Identify possible solutions for allowing the user to create a new project without having to re-select themselves as the submitter. 
    - For each solution, who would build/implement/maintain it? 
 
**Description:** 
When setting up a new project user is currently required to manually select themselves as "Applicant" even though they're already logged in.
 
**Acceptance Criteria:**
- "Applicant" fiedl should be automatically populated with current logged in user details
- "Applicant" field should not be displayed
- User should be able to review pre-populated applicant information before submitting the new project
 
**Research technical approach or current solution:**
- Investigate existing code implementation from the Traffic Register application that handled a similar auto-population of user info
- If code is not suitable, explore alternative solutions to auto-populated the applicant field.
- Determine if the solution requires custom code or can be implemented using existing functionality (e.g. record rules)
- Provide feedback and if needed further technical approach that may require additional Dev support

**Comment by ChrispinP** [comment]
Spike completed, solution implemented and tested as working in #19346 

closing
