### ISSUE TITLE
Add `moped_user_saved_views` table to database

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#19686]
As a user, I want a quick way to see and share a list of Moped projects relevant to a particular project, team, or task. I want to be able to save a view to a table in the Dashboard and add a description so I know what a view shows.

## Use cases
- Give field technicians an easy view of their work without needing to adjust filters and navigate Moped from their iPads 
- Enable all individuals in a workgroup to have easy and immediate (e.g. as soon as they're hired/onboarded) access to key project lists (we could populate default views for users based on their workgroup)

## In Scope
- Database 
   - Table contains:
      - `id` (auto-incremented)
      - `description` (~nullable~ not nullable) <- updated after scoping UI to require description on creation
      - `url` (not nullable)
      - `url_json` (jsonb of filters for future debugging) Also open to renaming if having json in the name is redundant - `url_blob`?
      - `created_by_user_id` (not nullable)
      - `updated_by_user_id` (not nullable)
      - `is_deleted`
      - `created_at` (not nullable)
      - `updated_at` (not nullable)
         - use existing trigger function (see audit field PRs/issues)

**Comment by tillyw** [comment]
what if we called the json field something like `filters` or `query_filters` ?

**Comment by mddilley** [comment]
@tillyw `query_filters` sounds like a much better fit for the data in the column - let's give it a spin!
