### ISSUE TITLE
Add filter for council district and/or month to CSR dashboard

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#19715]
Action item from TPWstat 10/28
> Data and Technology Services: Add filter for council district and/or month to CSR dashboard

I think we can just add this to the filter pane on the right side of the dashboard.

**Comment by katelunceford** [comment]
OPM Sprint Review notes: 
- Side filter would probably work for internal users
   - Demo with Karla, see if it fits her needs
- Council & the public would need a more intuitive user interface 
- Could explore more ways to make this more intuitive / user friendly 
   - About - this is a dynamic dashboard where you can click on a bar
   - Tool tips

**Comment by Charlie-Henry** [comment]
Added council district to the filter pane along with a few other useful ones:
![image](https://github.com/user-attachments/assets/38eb027c-9dd6-4e74-84cb-ee0110ae8927)

**Comment by Charlie-Henry** [comment]
Dan asked about this request and this was his response when I shared how it worked:
> Couldn’t ask for a better update! Thank you!
