### ISSUE TITLE
Updates RCA Approval System

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19712]
Since stakeholders wanted to renamed Posting Language to RCA we need to make those updates on different pages

**My Review / View RCA Details**

- [ ] change Final Posting Language to **Final RCA**
- [x] change Posting button to **RCA**
@stephaniemoorer I did some changes in this issue: https://github.com/cityofaustin/atd-data-tech/issues/19457#issuecomment-2444647819

**New RCA**

- [ ] change Posting Language New to **New RCA**

**RCA Dashboard**

- [ ] change Column heading from Posting Language New to **RCA**

**RCA Dashboard/ View**

- [ ] remove the Posting Language New heading so it looks like My Review /View / View RCA Details

![image](https://github.com/user-attachments/assets/485bf4d6-c9c8-458c-b51d-dc58a3466330)

![image](https://github.com/user-attachments/assets/2498acab-b3fe-4072-9ca7-b1d3c4b04582)

**Email Notification**

- [ ] can we remove the Approval Level and just display First Name Last Name

![image](https://github.com/user-attachments/assets/1a84c947-b734-47e5-995d-ab1c0fe25273)

**Comment by dianamartin** [comment]
# 11/1/24
**My Review / View RCA Details**

- [x] change Final Posting Language to **Final RCA**
![image](https://github.com/user-attachments/assets/2f846e3c-ada7-4f7e-be37-193514188071)
- [x] change Posting button to **RCA**
@stephaniemoorer I did some changes in this issue: https://github.com/cityofaustin/atd-data-tech/issues/19457#issuecomment-2444647819

**New RCA**
- [x] change Posting Language New to **New RCA**
  - [x] changed on object table - renamed from "Posting Language New"
  - [x] changed on form
![image](https://github.com/user-attachments/assets/5ebe465c-0566-44f6-bd10-b88d0437a616)

**RCA Dashboard**
- [x] change Column heading from Posting Language New to **RCA**
![image](https://github.com/user-attachments/assets/d36b99c9-66c8-4f39-8dff-c51f259c3d3a)

**RCA Dashboard/ View**
- [x] remove the Posting Language New heading so it looks like My Review /View / View RCA Details
![image](https://github.com/user-attachments/assets/b65cb709-999b-4a40-a38f-87a628f237b2)

**Email Notification**
- [x] can we remove the Approval Level and just display First Name Last Name
- [x] Added text formula for Created By and Current Reviewer to only bring in their name
- [ ] Updated the email body
![image](https://github.com/user-attachments/assets/e9153001-e27f-4c60-95ce-b6ebdbadb42b)

**Comment by stephaniemoorer** [comment]
@dianamartin the updates look great.

One update is missing on the My Reviews / View Review Details page:

![image](https://github.com/user-attachments/assets/9f003c03-5c47-4d54-8cb8-1d6768309b9b)

![image](https://github.com/user-attachments/assets/9a63619e-da95-4742-8da9-9f0a2d03f447)

- [ ] Change Final Posting Language to Final RCA
- [ ] change button from Posting to RCA

After this update everything will be consistent.
Thanks

**Comment by dianamartin** [comment]
# 11/4/24
- [x] Updated in "My Reviews>Details page" - "Final Posting Language" to "Final RCA"
- [x] Change button from "Posting" to "RCA" (URL slug is `rca-posting`

![image](https://github.com/user-attachments/assets/30831f1e-e37a-4b91-aa38-7c07d92a6260)

**Comment by stephaniemoorer** [comment]
All the headings are consistent with what the stakeholders wanted.
Closing this issue
