### ISSUE TITLE
Roberto S. Cannot Download EZMax Mobile

### ISSUE THREAD

**Issue by ReneVarg25** [cityofaustin/atd-data-tech#19741]
Roberto S.  with District Maintenance is having issues with trying to download EZMax onto his Ipad after another issue forced him to uninstall the application.  He has been unable to install the application since Friday.

<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTJTQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f79b8b7ee7103af82ec1d73e4b95b958a863be2/image.png" alt="image.png" />

<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTZTQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a874484181728a5fec4e3539117b027ba444c3a3/image.png" alt="image.png" />

<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXlTQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b5743a7534e0405b7fb5f3c478c4de37036be71/image.png" alt="image.png" />

**Comment by scottreedy** [comment]
@Matthew-M-TPW Probably needs to use wifi, he is using LTE from the pictures I see.

**Comment by scottreedy** [comment]
Matt did this
