### ISSUE TITLE
IT Support: Employee returning

### ISSUE THREAD

**Issue by Matthew-M-TPW** [cityofaustin/atd-data-tech#19758]
ST. ELMO, 

## Device & User Information (first name and last initial, no last names)
Reza K
## What's the problem?
Hi Matt,

Hope you are doing well. I tried to login to my laptop today, however, the laptop does not start up. I left my laptop on your desk. I'd appreciate it if you can look into it.

Thanks,
Reza

## What did you do to resolve the issue
Have tried to fix the user computer, but it keeps on running into error, says to do a repair which I tried. Did a bit locker recovery key repair but that doesn't work. Tried to get a new precision deployed at ben white as he was over there for orientation and team helped him out. But there are still few accesses on Arc-Gis and several other old data which might be in need off. As his old account was deleted, we need to figure how to fetch the information.

**Comment by Vaishnav1397** [comment]
User got a new laptop deployed with all the required Software installation, waiting on some data transfer.
