### ISSUE TITLE
Scoping RCA Approval System Approval Workflow

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#19796]
Meeting scheduled 11/7/24

Agenda: 
* RCA Approval workflow 
* RCA statuses 
* Feedback from user testing - if you have documented feedback prior to the meeting you can email it to me issue #19819 

[RCA Process](https://miro.com/app/board/uXjVKl8pOJs=/)

**Comment by stephaniemoorer** [comment]
11/7/24 - Gilda, Reynaldo, Andrei

Notes from work session

- While PM is drafting the RCA - Status Not Submitted
- Assign to Division Manager for Approval - Status Waiting for DM Review - Email Notification to RCA team email
- Assign to Assistant Director - Status Waiting for AD Review
- Assign to Director - Status Waiting for Director Review
- Status - Ready to Submit - email Notification to RCA team email
- Status - Submitted to Legistar
- Gilda gets email notifications from Legistar when the RCA is approved

- Fiscal Notes from Finance can be added as Attachment

- [ ] Need a Comments section
- [ ] Edits with option to email PM with changes (Banners app as an example)

- Resolutions will be added as an attachment

Reviewed feedback items Gilda provided.
Agreed to have a work session within a week. The stakeholders will create RCA's using actual data.

**Comment by dianamartin** [comment]
# 11/7/2024
I'll create a new issue for the actual RCA Status Approval Process
