### ISSUE TITLE
Set up redirect for `visionzero.austin.gov`

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#19801]
We need to make `https://visionzero.austin.gov/` resolve to `https://www.austintexas.gov/department/vision-zero`.

 It is currently pointing to the bucket `atd-vision-zero-website`, which does not exist.

To fix this:
- Option 1: Use cloudfront to the desired page on austintexas.gov. We're not 100% this is easy to do with the cloudfront configuration.
- Option 2: Set up a static html file in the existing vision zero bucket, and update the cloudfront distribution to point to it.

**Comment by frankhereford** [comment]
This was completed by using the preferred method discovered doing research. A lambda function has been created which returns a result object containing a 302 and that is hooked up to respond to an origin request in the VZ cloudfront distributions. The lambda function is named `
vz-redirect-to-coa-website`.
