### ISSUE TITLE
[BUG] Estimates missing from ATD Data & Tech Services Issue Socrata dataset

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#19893]
**Describe the bug**
Using the ATD Data & Tech Services Issues for reporting on the work accomplished last FY, I noticed that the `Estimate` field is not populating or is removing the estimates value once the service request moves to a Closed State

**URL**
[ATD Data & Tech Services Issues](https://datahub.austintexas.gov/Transportation-and-Mobility/ATD-Data-Tech-Services-Issues/rzwg-fyv8/about_data)

Link filtering records where `Estimate` is not null and `Pipeline` is Closed there are no closed issues with estimate. 
- Compared some issues in Github vs the ODP and confirmed that some of the issues do have estimates on Github
   - Example: #7681 vs [Link to ODP record](https://datahub.austintexas.gov/Transportation-and-Mobility/ATD-Data-Tech-Services-Issues/rzwg-fyv8/explore/query/SELECT%0A%20%20%60id%60%2C%0A%20%20%60number%60%2C%0A%20%20%60state%60%2C%0A%20%20%60pipeline%60%2C%0A%20%20%60title%60%2C%0A%20%20%60workgroups%60%2C%0A%20%20%60body%60%2C%0A%20%20%60labels%60%2C%0A%20%20%60estimate%60%2C%0A%20%20%60milestone%60%2C%0A%20%20%60created_at%60%2C%0A%20%20%60closed_at%60%2C%0A%20%20%60updated_at%60%2C%0A%20%20%60url%60%2C%0A%20%20%60is_epic%60%2C%0A%20%20%60position%60%2C%0A%20%20%60latest_comment%60%0AWHERE%0A%20%20caseless_one_of%28%60pipeline%60%2C%20%22Closed%22%29%0A%20%20AND%20%28caseless_contains%28%60labels%60%2C%20%22Apps%22%29%20AND%20%28%60number%60%20IN%20%28%227681%22%29%29%29%0AORDER%20BY%20%60id%60%20DESC%20NULL%20LAST%2C%20%60number%60%20DESC%20NULL%20LAST/page/filter) 

**How would you rate the impact of this issue?**
- [x] Minor  — can perform work, but could be easier or faster

**Comment by chiaberry** [comment]
The script goes through all the pipelines and gets issues with their estimates per pipeline. The problem is, "Closed" isnt considered a pipeline. 

The endpoint we were using to get estimates from zenhub has been deprecated, and there's a new graphql endpoint we can use, I checked and we can get the estimates from there.
