### ISSUE TITLE
[Documentation] Update CR3 & User management API docs in gitbook

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#19926]
As discussed in slack, [here](https://austininnovation.slack.com/archives/CM9MK950S/p1731613316597779), update the 
[cr3 and user management api docs](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/vision-zero-crash-database/user-management-through-the-cr3-api) in gitbook so that they are current with the new ECS + api gateway setup (https://github.com/cityofaustin/atd-data-tech/issues/18154).

**Comment by frankhereford** [comment]
This has been updated and revised for clarity and to reflect the current deployment mechanism. Thanks!
