### ISSUE TITLE
Update RDS instance for postgrest from postgres 12 to 16

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#19956]
Similar to the [moped update recently](https://github.com/cityofaustin/atd-data-tech/issues/17924), the postgrest database is also at EOL at version 12. We need to either get it up to date via RDS upgrades, either in one jump or stepwise, depending on what works. @frankhereford mentioned that this one has no postgis dependency 🎉 There is also no read replica to consider for this instance.

We also have seen some issues with [queries timing out](https://austininnovation.slack.com/archives/CHZE6BC6L/p1732642299568489) that could be improved by this upgrade.

**In Scope**
- Snapshot the DB prior to upgrade
- In major version steps, upgrade the existing RDS to PG 16

This is what we face if we do not update. h/t Frank

> Your PostgreSQL 12 databases are approaching end of standard support, and will be charged for RDS Extended Support starting March 1, 2025. To avoid the additional charges due to RDS Extended Support, we recommend upgrading your databases to a newer major engine version before February 28, 2025. To learn more about the RDS Extended Support pricing, refer to the pricing page.

**Comment by mddilley** [comment]
@frankhereford Yep! Thanks for creating this. 🙏

**Comment by frankhereford** [comment]
one-shot 12 → 16 upgrade, no issues. no errors in airflow and the traffic incidents DAG is back on and runs without barking. 🏁
