### ISSUE TITLE
VZV/VZD | null Mode metadata | Missing mode fatalities 

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#2001]
In the VZV Summary view, there is a mismatch between fatality counts in the Summary count widget (12 fatalities) and the "Fatality By Mode" visualization (11 fatalities). After taking a look at the TEST crash [dataset](https://data.austintexas.gov/Transportation-and-Mobility/-UNDER-CONSTRUCTION-TEST-Crash-Report-Data/3aut-fhzp/data), I noticed that `atd_mode_category_metadata` is missing for crash ID# 17574580.

Need to find out why the `atd_mode_category_metadata` is null for this record and how to fix so the fatality can be represented in the mode visualization (or any others that depend on the mode metadata).

@rgreinho also mentioned these two records in the #atd-vision-zero channel with a similar issue.
>3. 2 entries don’t have a “atd_mode_category_metadata” column, causing my parser to skip the entry, with the result that the fatality count is now incorrect:
https://data.austintexas.gov/resource/y2wy-tgr5.json?crash_fatal_fl=Y&crash_id=17574580
https://data.austintexas.gov/resource/y2wy-tgr5.json?crash_fatal_fl=Y&crash_id=180290542

### Crash record #17574580 (1 fatality but no metadata)
![Screen Shot 2020-03-03 at 10 40 52 AM](https://user-images.githubusercontent.com/37249039/75798664-82acb900-5d3c-11ea-8014-0389e2f8a29d.png)

**Comment by sergiogcx** [comment]
So this is related to old records not being present:

|year|count of null metadata|
|------|----|
|2019|2|
|2018|1|
|2014|13656|
|2013|14832|
|2012|14887|
|2011|13058|
|2010|12867|

**Comment by sergiogcx** [comment]
In production, there are only three crashes that do not have related unit records:

|crash_id|crash_date|
|------|----|
|17451702|2019-12-03|
|17541179|2019-11-08|
|180290542|2018-01-29|

17451702 - Not in the database or in the CSV files. It shows no case number and I could not find it in CRIS or Brazos. The only place I could find it was in the manifest file in the XML group called `<DeletedCrashes>` which makes me believe this crash has been removed from CRIS.

17541179 - This one appears only in production, I cannot find it in the CSV files. What I will try to do is request all of 2019 one more time, and see if I can find it there.

180290542 - Seems to be a case number, not a crash_id. I can't seem to find it in either CRIS or in Brazos. The record shows the case_id and the crash_id to be the same.

**Comment by mateoclarke** [comment]
@sergiogcx The 180290542 Teri Rd/Copperbend Blvd crash looked like it might have been one of the fatal crashes that was missing from our DB and was created manually by request from Lewis and team. So, I went back and looked in an [old QA spreadsheet](https://docs.google.com/spreadsheets/d/1GKJgBj3Q8WxXU2R2JWSm6291OFmTNKZ4FRH1CloSMpE/edit?usp=sharing) and found some notes for that crash: 

> "No CR3 due to unique circumstances but this is a traffic fatality - bicyclist but no auto parts - how do we deal with this one?  New mostly blank record?"

I also went back to check the other two, adding case numbers below for easier reference. But neither of those records had fatalities so my guess is its unlikely that we created them manually like we did for 180290542 with the missing CR3.

|crash_id|case_id|crash_date|
|------|----|--|
|17451702|NONE|2019-12-03|
|17541179| 193121376 |2019-11-08|
|180290542| 18-0290542 |2018-01-29|

**Comment by sergiogcx** [comment]
Thanks @mateoclarke that shines new light on the last one (180290542).

I am now receiving the 2010->2014 + 2019 data dumps. I will look for the two other records. Otherwise, it may be wise to ask the Vision Zero what to do about them.

Also, I've just spoken with @JaceDeloney, we are going to try to fill-in all units from that time range. It should be non-consequential to the crashes table and existing dashboards.

**Comment by sergiogcx** [comment]
I did not get the extracts until yesterday evening, I began the download and sorting the units files for insertion. 

Fixing to let it insert overnight, along with the person and primary person tables.

**Comment by sergiogcx** [comment]
After downloading and sorting only the units data for 2010->2014, I decided to let the process run overnight. 

The process was finished last night, and I just made the update that fixed all but 4 records:

```
crash_id,crash_date
17451702,2019-12-03
17541179,2019-11-08
180290542,2018-01-29
14720068,2014-03-13
```

![2020-03-26_10-49-32.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/d03ac237-f920-4ae7-b43f-7cede98771f6)
