### ISSUE TITLE
Create service account for our EC2 machines

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#20059]
To prevent us from accidental lockout of our EC2 servers, we should create service accounts to store in our secret store as a backup method of entry. 

Also, I captured the addition of this service account to servers in the [future launch checklist](https://github.com/cityofaustin/atd-data-tech/issues/20055).

This should cover:
- Citybase
- postgREST
- RDS bastion host
- EAZ tool
- On-prem server
- Anything else?

**In Scope**
- Propose a name in Slack
- Create a single SSH key, store private key in 1Password
- Add key rotation of the service account to [off-boarding checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/offboarding/off-boarding-checklist)
- Document in our server documentation with link to 1PW entry

**Out of scope**
- Creating individual service accounts for each server

**Comment by frankhereford** [comment]
This is complete. I have opted to use a generic name for the account, but I will opt to not mention it here. PM me if needed, or just look on any of the machines. Everything required to access the 7 machines in question has been stored in a new entry in the Administration 1PW vault.
