### ISSUE TITLE
Write newsletter spotlight for WZDx

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#20086]
- [x] Draft blurb [here](https://docs.google.com/document/d/10W-HLwOKhPg-X4pEd593x2wiKdNkNga88dOjrTLvC88/edit?tab=t.0#heading=h.ajh638ezhgnc); scroll down for examples
   - Describe the who, what, how, why, and/or impact
   - Use links when possible, like to the project index, website, tool, etc.
- [x] Source optional image, crop/resize it to 16:9, and save [here](https://drive.google.com/drive/folders/1CKyjWJs-gJtyLI6jkjJV0UML669wusTc)
- [x] Edit/wordsmith draft and finalize content - @katelunceford is happy to help

**Due 12/3** so that we can finalize the content, coordinate with PIO, and send on 12/10

**Comment by Charlie-Henry** [comment]
I started something. Feel like I am struggling writing this morning sorry for the word vomit.

**Comment by TracyLinder** [comment]
@Charlie-Henry you can punt it to me if you'd like. My brain is mostly functional today. 🤓

**Comment by Charlie-Henry** [comment]
punting to you @TracyLinder 🏈 !

**Comment by katelunceford** [comment]
@TracyLinder I edited [the content](https://docs.google.com/document/d/10W-HLwOKhPg-X4pEd593x2wiKdNkNga88dOjrTLvC88/edit?tab=t.0#heading=h.7i2k21or7hq7). Can you give it a final read-through and then we'll call it finished?
