### ISSUE TITLE
Meeting - Review of AMANDA data pull and next steps

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2008]

**Comment by SurbhiBakshi** [comment]
@dianamartin @jaime-mckeown @sergiogcx 

please add notes if I missed something.

Met with @dianamartin @jaime-mckeown @sergiogcx 

Showed them results of the Amanda query so far

- [ ] RW permits separately all sub types
- [ ] SE permits separately
- [ ] ask Maria how AFD comments are filtered - latest? by status? work on this after handing attachments dataset to Sergio
- [ ] Diana showed Sergio Python from last year
- [ ] give Sergio attachment records from AMANDA by tomorrow end of day

**Comment by sergiogcx** [comment]
Looking forward to this!

**Comment by jaime-mckeown** [comment]
Thank you @dianamartin @SurbhiBakshi @sergiogcx for your help!
