### ISSUE TITLE
Update Work Order Status Colors

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#20119]
# Build Out Notes
Goal: Update this [page](https://atd.knack.com/urban-forestry#contractor-work-orders/) and have Status with background colors

## Steps
- [x] Go to [Builder page](https://builder.knack.com/atd/urban-forestry/pages/scene_3)
- [x] Click "Status" field
- [x] Add Display Rules
- [x] Choose Status = Statuses below
- [x] Select "Background Color" or "Text Color"
- [x] Save when all done
- [x] Check page [front end](https://atd.knack.com/urban-forestry#contractor-work-orders/)
  - may need to refresh
### Status Colors to reference
NEED TO BE ISSUED - #ff0000
- text color
ISSUED - #377eb8
FINAL REVIEW - `#4daf4a`
READY TO INVOICE - #984ea3
CLOSED - `#777777`
- display icon: `fa-check-circle`

**Comment by ReneVarg25** [comment]
### 12/5/24
Added Display rules and updated the background colors and text colors to requested colors and icons.
Changed Text Color to white for easier visibility.

**Comment by dianamartin** [comment]
# 12/5/24
@ReneVarg25 The only thing I'm seeing is the check mark is "green" for CLOSED. 
![image](https://github.com/user-attachments/assets/c78699d1-c776-44d1-bf80-f55489d8722f)
- can you make the text - White
- [ ] `#ffffff`

**Comment by ReneVarg25** [comment]
### 12/5/24
![image](https://github.com/user-attachments/assets/a8f9c2b4-2857-4eea-8807-a3d220ff1915)
Check mark changed to white #ffffff

**Comment by ReneVarg25** [comment]
### 12/5/24
![image](https://github.com/user-attachments/assets/22bcb929-c1dc-4d01-8ce1-67276c4c9d0f)
added change to check mark to match request from Diana M.
