### ISSUE TITLE
Write newsletter spotlight for 360 Learning presentation

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#20118]
- [x] Draft blurb [here](https://docs.google.com/document/d/10W-HLwOKhPg-X4pEd593x2wiKdNkNga88dOjrTLvC88/edit?tab=t.0#heading=h.m7vfkpg4blzc); scroll down for examples
   - Describe the who, what, how, why, and/or impact
   - Use links when possible, like to the project index, website, tool, etc.
- [x] Source optional image, crop/resize it to 16:9, and save [here](https://drive.google.com/drive/folders/1CKyjWJs-gJtyLI6jkjJV0UML669wusTc)
- [x] Edit/wordsmith draft and finalize content

**Due 12/3** so that we can finalize the content, coordinate with PIO, and send on 12/10

**Comment by katelunceford** [comment]
@amenity could you edit [the blurb](https://docs.google.com/document/d/10W-HLwOKhPg-X4pEd593x2wiKdNkNga88dOjrTLvC88/edit?tab=t.0#heading=h.m7vfkpg4blzc) I wrote?

**Comment by amenity** [comment]
@katelunceford - looks great!
