### ISSUE TITLE
10 iPad Mini order

### ISSUE THREAD

**Issue by scottreedy** [cityofaustin/atd-data-tech#20132]
REQ0207744 - SCTASK0471100- 10 iPad mini's 11/18/2024
2 for Lisa's group
4 for Brian's group - , Sean M, Shahanaz S, Richard G and maybe Brian C
4 for others

[names hidden]

**Comment by scottreedy** [comment]
Received in 10 iPad mini (A17 Pro)
ATT FirstNet Service
ATT order NO 55-811000009043562
Ship 11/20/2024
COA Tag		Cell	     IMEI
COAW78496  737-231-3154  357153139408252
COAW78497  737-230-7744  357153130265230
COAW78498  737-230-8128  357153139918151
COAW78499  737-231-4005  357153130373471
COAW78500  737-230-8977  357153137501934
COAW78501  737-230-6037  357153139106633
COAW78502  737-239-3997  357153139455162
COAW78503  737-230-7074  357153134571450
COAW78505  737-230-9688  357153135871263
COAW78504  737-231-5484  357153135591424

**Comment by scottreedy** [comment]
@ChrispinP airwatch profile is individual for Brian Goldberg, Sean MacLeod, Shahanaz Sultana, Richard Guerra

**Comment by ChrispinP** [comment]
Submitted INC0452278 for moving Sean to TPW OG. 

The other 3 are already in the TPW OG and I have added devices for each. These 3 are ready for device setup.

**Comment by scottreedy** [comment]
@ChrispinP Closing this purchase ticket. 
#19994 is the working ticket for deployment now.

**Comment by JBStrangenew** [comment]
D Not Delete:
REQ0207744 - SCTASK0471100- 10 iPad mini's 11/18/2024
2 for Lisa's group
4 for Brian's group - , Sean M, Shahanaz S, Richard G and maybe Brian C
4 for others

[names hidden]
