### ISSUE TITLE
Add other dashboards to the Power BI app

### ISSUE THREAD

**Issue by katelunceford** [cityofaustin/atd-data-tech#20161]
[Power BI app](https://app.powerbigov.us/groups/me/apps/8b3b3a24-0d86-4879-8b4c-002167f3c311/reports/3ed8a2de-d354-464e-9bb2-af9b1a128fd6/ReportSection688d4a48f7221139d265?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f)

Dashboards to test adding:
- [x] SMD Performance Measures
- [x] [Vision Zero Viewer](https://visionzero.austin.gov/viewer/)
- [x] [Traffic Signal Monitor](https://data.mobility.austin.gov/signal-monitor)
- [x] [ArcGIS Hub](https://transportation-public-works-austin.hub.arcgis.com/)

**Comment by susannegov** [comment]
Added all. SMD PErformance Measures is on a different workspace so had to open in a new tab
