### ISSUE TITLE
Update on-prem server in advance of CTM update on December 10th and 11th

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#20183]
Frank had the idea to get ahead of these CTM updates since we haven't had CTM-scheduled maintenance since migrating to the RedHat on-prem servers. The goal being to uncover an unexpected outcomes before they happen during the maintenance windows.

> What’s Happening:
During our regularly scheduled weekly maintenance window, ALL SYSTEM PACKAGES (i.e. yum/dnf update) will be updated for your team's servers.
Note: all servers will be rebooted for kernel updates. Once all servers have been rebooted for the maintenance window, a notice will be sent out.

> When:
Linux OS patching windows: December 10th & 11th, Tuesday & Wednesday – 5am to 8am
Please check the date & time above as the update time might have shifted.

> What’s required of me?
To ensure system stability and avoid disrupting critical applications, please identify any installed packages that could cause issues if updated to their newest version. This allows us to temporarily exclude them from updates until compatibility is confirmed.
Use `dnf list installed` to view all packages currently installed on the system(s).
Check if any of these packages are known to be incompatible with a running application due to:
Vendor advisories.
Other sources of incompatibility information.
Send information about the identified incompatible packages, including:
Package name(s).
Reason for incompatibility.
 
> Additionally, if any third-party repositories besides the core defaults of RHEL need to be disabled during the update, please let us know.
We may proactively disable some third-party repos if they are causing problems with the update process.
For servers clustered behind a load balancer, we will do a rolling update where we only update and reboot one system at a time.

**In Scope**
- Update the on-prem servers ahead of the CTM schedule

**Comment by frankhereford** [comment]
@mddilley @chiaberry This is happening in the morning. I've gotten ahead of this by doing a system upgrade on 01, and it's been a solid disaster. The upgrade has (and would have) disabled IP forwarding for IPV4. RHEL is in a transitionary period between using `iptables` and `nfttables` making this that much more interesting / confounding. It's a drag that CTM is using this commercial linux when there are free, stable, secure and well-known options. 

This update did, and would have, cut off the airflow stack from incoming and outgoing TCP connections. Dead in the water. I'm mostly confident that we would have been able to SSH into the machine in the morning, and that's about it -- one couldn't even SSH port forward their way into getting an airflow web console. Again, this was a mess -- Airflow was unable to make /outgoing/ TCP connections prior to fixing this.

This is going to need some more time to figure out how to make these changes persist between reboots and even more, persist between RHEF `dnf` updates. Given the schedule that DTS has given us for on-going updates, I think we have a week to get this figured out. I can do it - it's new territory for me, but I was able to get it straightened out tonight, at least to some degree, to keep the lights on tomorrow.

**Comment by frankhereford** [comment]
This was completed with two notable outcomes:

* Docker community edition is being shipped from RHEL COA package server
* The networking issues from the first update are resolved
* The machine comes up with expected services on reboot
