### ISSUE TITLE
[DT] Delete CSR Flex Notes - January 2025

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#20188]
Received automated reminder to delete flex notes in AMD Data Tracker PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/amd/records/objects/object_95

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 11/1/2024 (2 months prior)

Total Records: {value}
To Delete: {value}
New Total: {value}

**Comment by ReneVarg25** [comment]
### 12/31/24
Total Records: 29975
To Delete: 9859
New Total: {value}
