### ISSUE TITLE
New SIF AMANDA Data Set for Assets, SIF & Mitigations Map (LP) - (Sent data in Email to Tracy)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#20218]
## We are creating 3 data sets for the Assets, SIF & Mitigations Map 
**_Folder Data, Fee Data, Building Info Data_**

- **All SIF folders are in scope for now.**

### Folder Data

> We are gathering certain data from the folder table, and all folder infos.

- FOLDERRSN
- PARENTRSN
- SUBDESC
- FOLDERNAME
- FOLDERINDATE
- FolderStatus
- Primary Folder Property Address
- Primary Folder Property PROPID
- 84010, Related Case #
- 84011, Council Districts
- 84012, SIF District
- 84013, Zoning Land Use
- 84014, TIA Reference #
- 84015, Date of Final Plat Approval
- 84016, Transportation Land Use
- 84017, # of Buildings
- 84018, Offset Agreement?
- 84019, Offset Type(s)
- 84020, Offset Details
- 84021, Offset Amount
- 84022, Offset Expiration
- 84023, Offset Constructed Amount
- 84024, Allocation Agreement?
- 84025, Allocation Type
- 84026, Allocation Details
- 84027, SIF Reduction?
- 84028, Total Reduction Amount
- 84029, Total Standard Amount
- 84030, TIA Approval Prior to Ordinance Adoption?
- 84031, Redevlopment Project?
- 84032, University Neighborhood Overlay?
- 84033, Mitigation Offset?
- 84036, Mitigations Assessed?
- 84037, Remaining Offset
- 84038, ROW Dedication Amount (sf)
- 84039, ROW Dedication Unit Value ($/sf)
- 84040, ROW Dedication Value Calculated
- 84041, Easement Dedication Amount (sf)
- 84042, Easement Dedication Unit Value ($/sf)
- 84043, Easement Dedication Value Calculated

### Fee Data

> We are gathering data from the fee tables

**Parameters:**
_Do not include fees that exist but have not been billed_
_Do not include cancelled bills._
_Do include all payments regardless of the payment status._ 

- FolderRSN
- BILLNUMBER
- BILLAMOUNT
- Bill Generated Date
- PAIDINFULLFLAG
- (Bill) FEECOMMENT
- PAYMENTNUMBER
- PAYMENTCOMMENT
- Payment VOIDED?
- PAYMENTDATE
- PAYMENTAMOUNT
- TOTALPAID

### Building Info Data

> We are gathering all data from the SIF free-form tab

- FolderRSN
- ROWID for the record?
- ATD Building #
- Unique ID
- Status
- Transportation Land Use
- Intensity
- Standard SIF Amount
- Existing Land Use Reduction
- Potential SIF Amount
- Affordability Units
- Affordability SIF Reduction %
- SIF After Affordability
- Trip Capture %
- Transit Proximity %
- Parking Reduction %
- Total Reduction % Amount
- Total Reduction Dollar Amount
- Pre-Offset SIF Amount
- offset?
- Offset Reduction %
- Offset Reduction Dollar Amount
- Total Reduction Amount
- Total SIF Collection Amount
- Ready to Charge?
- PR Folder #
- Invoice #
- Paid?
- comments

**Comment by TracyLinder** [comment]
This is ready for a dev.

**Comment by Lpriya-LIT** [comment]
[SIF Buiding Info data.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEllQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8ffab488b6d577bc953c305e0156d7bc1b139de/SIF%20Buiding%20Info%20data.xlsx)

**Comment by Lpriya-LIT** [comment]
[SIF - Fee data.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFlQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84d121c53a9bb1db568451cfcdb2dc41ddb017a6/SIF%20-%20Fee%20data.xlsx)

**Comment by Lpriya-LIT** [comment]
[SIF - Folder Details Data.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFllQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4361b66d0f64588069017e40f34a20496792fb15/SIF%20-%20Folder%20Details%20Data.xlsx)

**Comment by TracyLinder** [comment]
### Review w/ Andrew

- Not all SIF folders have a parentrsn and we won't be able to show a relationship between that and the SP.
- Not all SIF relate to a site plan, some of them relate to plats and subdivisions. This may complicate things.
