### ISSUE TITLE
RCA Approval System Usability Testing - Sprint Review Meeting

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#20220]
Stephanie M.  - out sick 
Christina and Diana ran meeting
### Participants
- Gilda, Rey, Natalie, Dan
- Diana, Christina

# Notes
### On New RCA form
- [x] Make “TPW” - default Originator
- [x] Change globally “Coordinator” to “Originator”

### RCA Status
- [x] Decision to use `Waiting for Review`
>Talked about using only “Waiting for Review”

### Enhancements
- [x] Add "Change Status" button to RCA Details

## Decision Status - for AD and Director
- Approved
- Rejected

## RCA Calendar Dates
- Deadline Dates
- Council Meeting Dates
![image](https://github.com/user-attachments/assets/1d8ff9f7-1ce8-4d35-982e-90ae9faa566b)

## Prepare Sneak Peek
Christina agreed to prepare a preview for RCA users to so they know what is coming. We don't have to do full demo, but high level.
- Wed, December 18th
- To show: 
    - New RCA form
    - Edit/Fill out RCA (using template)
    - RCA Process Details
      - Assigning a Reviewer
    - My Reviews
        - How to Review RCA
    - RCA Calendar

## Christina’s Notes
- If email is “yes” require the email
- Change “Coordinator” to “Originator”
- Fix bug of moving RCA out of the “Waiting for Review”
- Project Delivery and SUTD are the only ones that use the FSD RCA Dates (RCAs that go through finance)

**Comment by dianamartin** [comment]
# 12/9/2024
- [x] Make “TPW” - default Originator
- [x] Change globally “Coordinator” to “Originator”

RCA Status
- [ ] Decision to use Waiting for Review
>Talked about using only “Waiting for Review”

Enhancements
- [x]  Add "Change Status" button to RCA Details

RCA Calendar
- [x] Created new

**Comment by stephaniemoorer** [comment]
@dianamartin 
can you look at the problem with moving the RCA from Waiting To Review to Previously Reviewed

**Comment by dianamartin** [comment]
# 12/11/214
Updated "Reviews"
- [x] Changed review "Approval Level" from "Coordinator" to "Originator"
- [x] Added new field "Decision Executive" 
- [x] Added new field "Approval Level Executive"
- [x] Tested Decisions
- [x] Updated Display Rules
- [x] Updated Record Rules
- [x] Configured Test Emails (as placeholder email)
- [x] Added new user "TPW RCA Admin"

**Comment by dianamartin** [comment]
# 12/11/24
- Stephanie and I synced about the email notifications, we were having issues with providing a direct link to the "My Review" page to launch directly in the parent RCA. 
- We brainstormed on how we could accomplish this

## IDEA
- Add the review fields to the RCA
![image](https://github.com/user-attachments/assets/9eaa6abc-89f3-4bd0-b463-0b0bded5f01d)
- Add update form on "My Review" details page
- Have the same fields show up for decision process
- Create record rules to generate a new review record (as audit log) - can be searchable later
- This should allow us to point to the parent RCA in the email for the user (which is important for the Director approval level)
- Reminder: hide new form so that only Knack Admin can see it
