### ISSUE TITLE
MDS Security Upgrades

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2022]
- [Encryption at rest](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html#Overview.Encryption.Overview)
- IP Whitelisting
- [AWS Web App Firewall (WAF)](https://aws.amazon.com/waf/)

**Comment by johnclary** [comment]
@sergiogcx Ideally, we implement all of these, but we can pause to discuss after you do some research. 

cc @mateoclarke @JaceDeloney

**Comment by sergiogcx** [comment]
All tasks completed, moving to ready for Review

**Comment by sergiogcx** [comment]
Closing, this is long done :)
