### ISSUE TITLE
Look into how to persist IP forwarding on dts-int-data-p01 between automated updates

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#20230]
Frank recently [performed updates on atd-int-data-p01](https://github.com/cityofaustin/atd-data-tech/issues/20183) ahead of CTM's automated update and encountered the issues quoted below. We need to dedicate some time to figuring out how to keep Airflow up and running when these automated updates and/or reboots occur in the future.

> I've gotten ahead of this by doing a system upgrade on 01, and it's been a solid disaster. The upgrade has (and would have) disabled IP forwarding for IPV4. RHEL is in a transitionary period between using `iptables` and `nftables` making this that much more interesting / confounding. 

> This update did, and would have if left unattended, cut off the airflow stack from incoming and outgoing TCP connections, leaving it dead in the water. I'm mostly confident that we would have been able to SSH into the machine in the morning, and that's about it -- one couldn't even SSH port forward their way into getting an airflow web console. Again, this was a mess -- Airflow was unable to make /outgoing/ TCP connections prior to fixing this.

> This is going to need some more time to figure out how to make these changes persist between reboots and even more, persist between RHEL `dnf` updates. Given the schedule that CTM has given us for on-going updates, I think we have a week to get this figured out. I can do it - it's new territory for me, but I was able to get it straightened out tonight, at least for now, to keep the lights on tomorrow for our ETLs.

_Originally posted by @frankhereford in https://github.com/cityofaustin/atd-data-tech/issues/20183#issuecomment-2530793453_

**In Scope**
- Research and implement a way to keep IP forwarding for IPV4 alive when CTM automated updates occur
- Add how this was done to our server documentation

**Comment by mddilley** [comment]
The updates went better than expected, and this does not seem necessary at this time. See [this thread](https://austininnovation.slack.com/archives/CHZE6BC6L/p1733917613580939)

**Comment by frankhereford** [comment]
CTM did not apply updates today, it does not appear that any were released from the COA RHEL package repo nor from upstream. All that to say, no meaningful change in the status of this request, but FWIW, I am 99.9% comfortable that we're cool with this. It's my opinion that the inclusion of the community docker package from CTM last week did us a world of good and included the solution to all of this.

I'm good to close this if you want, and we can reopen on the long-shot that something goes sideways. I'll continue to monitor this server WRT CTM updates per usual too.

**Comment by mddilley** [comment]
Sounds great - I'm good with closing this out and reopening if needed. Thanks!
