### ISSUE TITLE
Import RCA contacts into Office of the Director Portal

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#20242]
Gilda emailed the RCA Distribution list so we can import those users.

**Comment by dianamartin** [comment]
# 12/10/24
- Gilda emailed the RCA Distribution list
- Created spreadsheet `RCA Users` to capture users first, last and email addresses
- [x] imported `72 records`
- [x] Set users to "inactive" (for now, during testing)
- [ ] Need to change approval levels

**Comment by dianamartin** [comment]
@stephaniemoorer ready for review
- I updated the filters for the "Assign Reviewer" drop down to "User Status is Active" - so it will only show our test contacts for now.

**Comment by stephaniemoorer** [comment]
@dianamartin 
I think this is complete. 
Can this issue be closed?
