### ISSUE TITLE
Whitelist COA / DTS IP Addresses 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2024]
Sergio has to create a load balancer because it doesn't exist for the Hasura endpoint.

**Comment by sergiogcx** [comment]
This has been implemented, and the code merged to master. I have added notes in relation to the CTM range in the readme under *Security Considerations*:
https://github.com/cityofaustin/atd-infrastructure/tree/master/configuration/atd_mds
