### ISSUE TITLE
Post-migration housekeeping in the mono-repo mansion 🧹🧼 🏰

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2026]
For each product/project: 
- (If migrated) review all issues on board & make sure nothing looks too amiss in terms of pipelines
- (If migrated) recompose open epics:
   - Open the epic & follow link to original issue
   - Open all issues in original issue and assign to new `atd-data-tech` epic
- Add a `Product` label to projects if applicable, e.g. `Project: SMB 311 Module` gets `Product: SMB Data Tracker` 
- Consolidate labels, if necessary, e.g. `Product: VZA`, `Project: VZA App`
   - Make sure there is 100% overlap between issues assigned to each label (I use the Zenhub board view for this bulk counting/filtering/editing) 
   - Delete the one we don’t want from the [labels](https://github.com/cityofaustin/atd-data-tech/labels) page.  
   - Make sure the label what’s left has a nice description and the correct hex code: 
       - Product: #3D3D3D
       - Project: #86B1C6

Jace
- [x] Product: Vision Zero Crash Data System, Project: Vision Zero Crash Data System
- [x] Product: Vision Zero Editor, Product: VZE
- [x] Product: Vision Zero Viewer, Project: Vision Zero Viewer, Product: VZV
- [x] Product: Mobile Signal Work Orders, Project: Mobile Signal Work Order 
- [x] Product: Signs Mobile Work Orders, Project: Signs Mobile Work Orders
- [x] Product: Dockless Dataviz
- [ ] Product: Dockless Licensing
- [ ] Product: Micromobility
- [ ] Product: Mobility Services
- [x] Project: MDS Upgrades
- [x] Project: Micromobility Dashboard Updates
- [ ] Project: Mobility Data Privacy & Security
- [ ] Project: BI Discovery

Amenity
- [x] Product: Vision Zero in Action, Project: VZA App, Project: VZA Citation App, Product: VZA App, Product: VZA
- [x] Product: SMB Data Tracker, Product: Signs & Markings, 
- [x] Product: AMD Data Tracker, Product: AMD Tracker, 
- [x] Product: AMD Fulcrum
- [x] Product: ATD Forms 
- [x] Product: Banners, Product: Signs & Markings, Project: Signs Migration, Project: SMB 311 Module
- [x] Product: Mobility Project Database, Product: MPD, Project: Mobility Project Database, Project: Mobility Project Database
- [x] Product: MPV, Product: Mobility Project Explorer
- [x] Product: Mobility Project Editor
- [x] Product: Finance & Inventory
- [x] Product: Residential Parking Permit Digitization, Project: Residential Parking Permits, Product: RPP
- [x] Product: Visitor Log
- [x] Project: Beacon Data Tracking
- [x] Project: Work Order Extension
- [ ] Project: Warehouse Inventory
- [x] Project: Paperless Hiring
- [x] Project: Branding and Identity
- [x] Project: Job Calendar Work Schedule
- [x] Project: DTS Service Delivery

Jaime
- [x] Project: Online Bike Map
- [x] Project: AGOL Audit
- [x] Project: CTN
- [x] Project: Parking Inventory
- [x] Project: Print Bike Map
- [x] Project: Data Driven PHB Ranking
- [x] Project: Bike Rack Data Inventory
- [x] Project: OSM Bicycle Data Update

John (or reassign)
- [x] Project: Development Review Workflow
- [x] Project: TDSD Phase 2
- [x] Product: Data Lake, Project: Data Lake
- [x] Product: ROW Portal
- [x] Project: AWS Migration
- [x] Project: DAPCZ Agenda Tool
- [x] Project: AULCC Utility Mapping
- [x] Project: B-Cycle Station Planning
- [x] Project: Inspector Prioritization Automation
- [ ] Project: Parking Enterprise Work Order System
- [x] Project: Parking Technology Procurement
- [x] Project: Sign Data Collection
- [x] Project: Traffic Counts
- [x] Project: Traffic Registry Digitization
- [x] Project: TxDOT Center-to-Center
- [x] Product: DTS Portal, Product: Service Requests
- [ ] Product: Data & Performance Hub

Tracy
- [x] Project: ATD AMANDA Backlog 
- [x] Project: ROW Activity Dashboard
- [x] Project: ROW Attendance Tracker
- [x] Project: ROW Wishlist
- [x] Project: ROWMAN Ph 2
- [x] Project: ROWMAN Ph 3
- [x] Project: ROWMAN Ph 4
- [x] Project: ROWMAN Ph 5
- [x] Project: ROWMAN Ph 6
- [x] Project: SCP3
- [x] Product: Transportation Development Services

**Comment by amenity** [comment]
@johnclary - can we delete the `migrated` label on a per-project/product basis as part of this process?

**Comment by amenity** [comment]
Tracking other changes here, @JaceDeloney @johnclary 
- Changed `Service: PM` to  `Service: Product`
- Added `Workgroup: ATD`

**Comment by amenity** [comment]
@jaime-mckeown - forgot to add you to this.

**Comment by jaime-mckeown** [comment]
@amenity I need a little clarification on exactly what it is you want me to do for the Geo Projects listed.

**Comment by amenity** [comment]
(Jaime and I caught up on this offline. Removed the `Product: GIS` label and walked through the epic-updating process.)

**Comment by jaime-mckeown** [comment]
@amenity Geo Projects are updated, I did all including Alan's to get it done. I also updated the Sign Data Collection under John as it was partially Geo. I have removed all migrated labels from the Geo Issues.

**Comment by amenity** [comment]
Awesome, @jaime-mckeown ! Thank you for staying on this.

**Comment by amenity** [comment]
I knocked out a bunch of this last night. 

Some Product-Op-y thoughts, /cc @moorerst @JaceDeloney @johnclary @TracyLinder: 
- Creating labels before activation implies a bit of solution-ing, e.g. `Project: Parking Enterprise Work Order System` issues might be a freestanding Knack app or actually be a part of a Parking Enterprise Reporting Portal product. Maybe we don't create a label until activation?
- "Project" labels are currently used for features, enhancements, and more project-y things like data-driven PHB ranking. I wondered about whether "Feature" labels would be a good idea. Downside: yet another label category... Upside: Easier to implement a rule like every "Feature" issue also needs a "Product" label, where "Projects" don't necessarily... TBH, I think we should be using Releases to designate work on a feature/enhancement, I just currently find labels easier. I am down to make this shift if y'all are!

I would also like to [discuss DTS App Suite product strategy](https://github.com/cityofaustin/atd-data-tech/issues/2374). :)

**Comment by jaime-mckeown** [comment]
@amenity @johnclary I just noticed that all of my old issues from atd-geospatial that I linked to the new Epics in atd-data-tech are no longer there. If I go to the old Epic in atd-geospatial they are not there either..... :(

**Comment by amenity** [comment]
@jaime-mckeown - oh man - I'm guessing that the epics were for some reason undone when we removed repos from the main workspace. 😢

**Comment by amenity** [comment]
@JaceDeloney @johnclary, another round of scouring for remnants from mono-repo-ing and have a few questions:
 - Can we delete the [`Product: Dockless Licensing` label](https://github.com/cityofaustin/atd-data-tech/labels/Product%3A%20Dockless%20Licensing)? 
- Can we delete [`Product: Micromobility`](https://github.com/cityofaustin/atd-data-tech/labels?q=micromobility) label
- [`Product: MDS Upgrades`](https://github.com/cityofaustin/atd-data-tech/issues?q=label%3A%22Product%3A+MDS+Upgrades%22+) sounds more like a project 
- Do we want Data Lake to be a [project](https://github.com/cityofaustin/atd-data-tech/issues?q=label%3A%22Project%3A+Data+Lake%22+is%3Aclosed) or [product](https://github.com/cityofaustin/atd-data-tech/labels/Product%3A%20Data%20Lake)? Plz label [the Index](https://github.com/cityofaustin/atd-data-tech/issues/132) accordingly. 
- Is there overlap between [`Product: TIA Module`](https://github.com/cityofaustin/atd-data-tech/issues?q=label%3A%22Product%3A+TIA+Module%22+) and [`Product: ROW Portal`](https://github.com/cityofaustin/atd-data-tech/issues? q=label%3A%22Product%3A+ROW+Portal%22+)

### Need indices* 
- [ ] [Banners](https://github.com/cityofaustin/atd-data-tech/labels/Product%3A%20Banners); also needs a PM assigned
- [ ] [Data and Performance Hub](https://github.com/cityofaustin/atd-data-tech/labels/Product%3A%20Data%20%26%20Performance%20Hub); also needs a PM assigned
- [ ] [COVID-19 Time Tracking](https://github.com/cityofaustin/atd-data-tech/labels/Product%3A%20COVID-19%20Time%20Tracking%20App) @JaceDeloney 
- [ ] [Development Review](https://github.com/cityofaustin/atd-data-tech/issues?q=label%3A%22Product%3A+Development+Review%22) - or maybe https://github.com/cityofaustin/atd-data-tech/issues/460 can be reopened and changed to a `Product` @TracyLinder 
- [ ] [Finance and Invoicing](https://github.com/cityofaustin/atd-data-tech/issues?q=label%3A%22Product%3A+Finance+%26+Inventory%22); also needs a PM assigned
- [ ] [MDS Upgrades](https://github.com/cityofaustin/atd-data-tech/issues?q=label%3A%22Product%3A+MDS+Upgrades%22+) @JaceDeloney, right?
- [ ] [Visitor Log](https://github.com/cityofaustin/atd-data-tech/labels/Product%3A%20Visitor%20Log) - @johnclary 

*[Template here](https://github.com/cityofaustin/atd-data-tech/issues/new?assignees=&labels=Index&template=-all-purpose--project-product-index.md&title=Project%2FProduct%3A+%5BYour+Project+Name+in+Title+Case%5D). Just a description and a link to a Drive folder for future use is great.

**Comment by amenity** [comment]
More to come, still need to check [all Project labels](https://github.com/cityofaustin/atd-data-tech/labels?page=2&sort=name-asc) for redundancy and indices.

**Comment by johnclary** [comment]
- deleted Product: Micromobility label
- changed Product: MDS Upgrades to a `Project`
- Do we want Data Lake to be a project or product? Product—done.

**Comment by dianamartin** [comment]
@amenity @TracyLinder TIA module label is not related to the ROW Portal. The TIA Module is related to the TDSD Tracker.
