### ISSUE TITLE
HR Portal Update Supervisor Name on Existing AVL forms

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#20262]
- In order to have existing AVL forms display on Staff Forms we need to update the Supervisor Name 

- From My Forms/View Time and Attendance Details the Supervisor field is not displaying

![image](https://github.com/user-attachments/assets/bab2eb84-fa70-4ab4-bcb1-7b0268b06445)

**Comment by dianamartin** [comment]
# 12/12/24
- Added "Supervisor" field to AVL form the other day, need to set Supervisor for submitted records
- Backfill supervisor for AVL form entries - `998 records`
- [x] Aaron E. 
- [x] Adam B. 
- [x] Adam S.
- [x] Alex B.
- [x] Alfred L.
- [x] Ali M. 
- [x] Amenity A.

**Comment by dianamartin** [comment]
# 12/12/24
- Synced with Chrispin because my imports weren't working and other people were showing up as Supervisors
- He told me I was using the wrong field to field map when importing
- Reimported using my subset and that worked properly
- [x] Imported `998 records` successfully
