### ISSUE TITLE
Create February trip reports with 15, 30, and 45 mile trip_distance filters

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2027]
Shared Mobility has requested reports with trip_distance filters of 15 miles, 30 miles, and 45 miles to better understand the distribution of trips within certain distance thresholds. The original long trip_distance filter that we used was 60 miles. To use the same comparisons as they previous reports that we sent them, we also need to use these filters with and without the 0-distrance trips filter.

**Create 6 reports that:** 
- feb raw data with trips_long_distance column set to 45 miles (72k meters)
- excludes trips > 45 mile (72k meters) trip_distance
- excludes trips > 45 mile (72k meters) trip_distance AND trips = 0 trip_distance
- feb raw data with trips_long_distance column set to 30 miles (48k meters)
- excludes trips > 30 mile (48k meters) trip_distance
- excludes trips > 30 mile (48k meters) trip_distance AND trips = 0 trip_distance
- feb raw data with trips_long_distance column set to 15 miles (24k meters)
- excludes trips > 15 mile (24k meters) trip_distance
- excludes trips > 15 mile (24k meters) trip_distance AND trips = 0 trip_distance

**Comment by sergiogcx** [comment]
After discussing things with @jace, we determined we in fact needed a total of 9 reports, one for each:
- The raw data (that shows all counts with zero and x mile distance trips)
- The data that excludes x miles
- The data that excludes both x miles and zero-distance trips.

**Comment by sergiogcx** [comment]
It looks like it works, closing this issue.
