### ISSUE TITLE
IT Support: Laptop keeps freezing

### ISSUE THREAD

**Issue by Craigjacobs-ATX** [cityofaustin/atd-data-tech#20278]
## Device & User Information (first name and last initial, no last names)
 Rahman M.
## What's the problem?
Message sent from User via Teams : 

Im reaching out again because I’ve been experiencing significant issues with my laptop since installing Windows 11. It frequently freezes and becomes unresponsive, which has disrupted several important meetings with executives.
Additionally, the connected monitor screens often go completely black. These problems have been persistent, and they’re severely limiting my working capacity and efficiency.

# What did you do to resolve the issue

**Comment by scottreedy** [comment]
Sent Teams chat - Laptop keeps freezing (Issue #20278) - Matiur, I can go by and take a look at your laptop tomorrow if you will be at the TMC. I am teleworking today

**Comment by scottreedy** [comment]
ai

**Comment by scottreedy** [comment]
He replied 
Thank you so much, Scott, for all the help. Hope the updates will the fix the problems I’m experiencing but I’ll keep monitoring and let you know if I face the same issues.
