### ISSUE TITLE
GIS Request to do a full replacement of the 811 signal service area

### ISSUE THREAD

**Issue by ChristinaTremel** [cityofaustin/atd-data-tech#20274]
## GIS Service Request ##

**Requester:** Brian C.

**Issue Description:**
- Need to do a full replacement of data in 811. Instructions in issue #20273 
   - [811 GeoCall Editor ](https://txgc.texas811.org/ui/map/editor/sa)
- Assets to add with a 300 ft buffer and could be in one Shapefile
   - Signals
   - School Zone Beacons
   - Flashing Beacons
   - Fiber Optic Cable
- WGS84 projection for the dataset

### Future plans (after first iteration) 
- Brian needs one of the comm folks for aerial/underground fiber. Only need to track underground fiber optic cable
- In the future, could get another code in 811. 
   - One layer should have the underground fiber
   - One layer should have signals, school zone beacons, and flashing beacons

**Comment by ChristinaTremel** [comment]
Andrew created layers of these assets: 
- Signals
   - 300 ft buffer
- School Zone Beacons
   - 300 ft buffer
- Flashing Beacons
   - 300 ft buffer
- Fiber Optic Cable
   - 100 ft buffer
- Buffer merge dissolve
- Confirm projection WGS84
- Export as Shapefile

**Comment by andrewshensky** [comment]
Data processing was completed to have a single layer of all buffers merged and dissolved into a single feature. The output was uploaded to 811 and changes have now been accepted.
