### ISSUE TITLE
Test github integration

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#203]
Perform a survey of all repositories and their purpose.

- [x] Find all ATD repos.
- [x] Define its purpose and content.
- [x] Allow slack read-access permissions.
- [x] Test slack notifications by creating test issues.

**Comment by sergiogcx** [comment]
I will be testing `atd-dockless-processing` first, by making a tiny change in .gitignore for my IDE. That should be reflected in #atd-dev-updates and NOT in #atd-data-tech-updates.

Then I will create a test issue in #atd-data-tech-updates, and see it only in data-tech-updates.

**Comment by sergiogcx** [comment]
This is test comment, should be caught by slack.

**Comment by amenity** [comment]
@sergiogcx - is this done? Also, can you size it? 
1️⃣ = minutes
2️⃣ = hours
3️⃣ = days

**Comment by sergiogcx** [comment]
It should take a few hours, just not priority at the moment. Will get to this during the weekend.

**Comment by sergiogcx** [comment]
I've used this issue as a credit for creating the slack channel. I have set up another issue #232 to specify configuration and write some docs for anyone to add/modify settings.
