### ISSUE TITLE
HR Digital Interview - Testing Notes Job Posting

### ISSUE THREAD

**Issue by stephaniemoorer** [cityofaustin/atd-data-tech#20345]
12/18/24 - Testing Notes - focus on Job Posting

1. **Edit Hiring Details - PCN Compensation**
Move instructions under the title

2. ***Job Posting Details - Pay Scale**
Pay Scale is not displaying 2025 Compensation amounts. Zone amount for zone 1 - 4 is not correct

3. **Posting Status** 
When Status is Posting In Development and Hiring Manager Status is Inactive
From My Posting I could see buttons and could edit Posting Information.
As Inactive I should not have access to edit

4. **Change Status**
- Set Hiring Manager Status Default to Inactive????
- Change In Progress | Needs Action to In Progress | Needs Action - Job Posting
- Remove the , from end of In Progress | Needs Action - Candidate Screening Matrix
- Change Status Posted to Posting Open to match Posting Closed

5. **My Posting / Add Preferred Qualifications**
Add note under title - Enter one at a time, select ADD after each entry

6. **My Posting / Edit Job Posting Information**
move instructions under the title OR change the title to Posting Duration Notes to HR (optional)

7. **My Posting / Edit Posting Information**
Supplemental Questions - the example is at the end, should be moved to the top

8. **My Posting - Complete Action**
Selected Complete Action the page did not refresh

9. **Consider adding a Tracking History button**
area to track the date when the status changes happened

10.  **Job Posting Details / Hiring Manger View**
The Posting Information Posting Duration and Skills Assessment is not displaying

**Comment by stephaniemoorer** [comment]
12/31/24
Testing status

- Posting - In Development / HM not Inactive
Should be: 
HM Status = Inactive
No Posting or Candidate Matrix menu displayed

- In Progress | Need Action - Job Posting
seems to be working correctly

- **From My Posting** - this is where the HM would select Complete Action after updating Posting Information
The Complete Action status for Job Posting is not displaying the correct status 
![image](https://github.com/user-attachments/assets/077a4a5c-3ba2-4ea5-95e2-fefd14e65ec4)

![image](https://github.com/user-attachments/assets/f345f148-94f7-42b0-b254-cc4bce27240c)

** Status should be In Progress | Completed Action - Job Posting**

This is working correctly for Complete Action - Candidate Screening Matrix

![image](https://github.com/user-attachments/assets/f5922645-6d34-4672-884b-d4a39b4879ea)

- In Progress | Completed Action - Job Posting and 
In Progress | Completes Action - Candidate Screening Matrix 

The HM Status is Inactive 
The MY Posting page is not locked down from Editing

![image](https://github.com/user-attachments/assets/9429c048-75f2-4f4c-b97d-4171d0c520e0)

- Posting Open and Posting Closed

HM is Inactive
MY Posting page is not locked down from editing

**Comment by dianamartin** [comment]
# 12/31/2024
Stephanie and I synced and made a table in Miro to help use with reviewing the page rules.
