### ISSUE TITLE
SXSW Events API AGOL Feature Layer

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#2036]

**Comment by jaime-mckeown** [comment]
@mateoclarke verified the API Feed yesterday and downloaded csv and json files so I could see the data.

**Comment by jaime-mckeown** [comment]
Created a new Feature Service using the fields from the API Feed.

**Comment by johnclary** [comment]
The scripts and docs live [here](https://github.com/cityofaustin/atd-sxsw/tree/master/sxsw_events).

Script is ready. Just needs to be deployed. Will open a separate issue for that. Closing this one.

**Comment by johnclary** [comment]
@jaime-mckeown moved to Review/QA in case you want to do some QA on this layer.

**Comment by jaime-mckeown** [comment]
Thanks @johnclary! I will take a look at this.

**Comment by jaime-mckeown** [comment]
Layer drawing as expected, SXSW cancelled, didn't get to use the API this year.
