### ISSUE TITLE
Call  with Steve & Nic from Knack

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#204]
**Feature requests**
- **Usage analytics for end users**, e.g. view page usage and user activity
- **Logging for app builders and end users**, e.g. logging record creation/modification, app change log
- **Developer documentation within the app builder**, e.g. ability for us to record the business logic behind a particular configuration and have that visible for future reference from within the builder
- **Version control** to support roll-backs and documentation
- **Ability to promote code and sync data between servers/environments** rather than repeat entire configuration process in production environment
- **Share tables between multiple apps** to allow for a more scalable modular architecture
- **Ability to pull data out of Knack dynamically from external non-Knack APIs** e.g., ingest and display related data from a an external database 
- **Built-in webhooks** to enable real-time integration with our databases without third party integrations would also help us simplify our pipelines (avoid cron jobs or any complex sync jobs). This may be planned functionality with the "Knack bots". Here are some 3rd party integrations:
https://zapier.com/apps/knack/integrations/webhook
https://zapier.com/apps/knack/integrations/postgresql

---
- [x] Schedule meeting
- [x] Collect questions
- [x] Email questions to Steve
- [ ] Meet
- [ ] Attach notes

**Comment by amenity** [comment]
@mateoclarke @sergiogcx @johnclary @dianamartin - can you add/elaborate to these when you get a sec? I'd like to send them to Steve tomorrow if possible.

**Comment by sergiogcx** [comment]
Yes, so I tried looking up a webhooks functionality in knack, so that whenever a new record is created, we can post that data automatically (in real time) to any other data endpoints we need (one or many). 

Currently we are relying on querying knack periodically, this creates complexity on our end because we have to create, test and maintain apps and infrastructure for that purpose alone.

For webhooks, rather than relying on a 3rd party (zapier) it would be nice to know if there is anything we can do to implement our own automated hooks.

**Comment by johnclary** [comment]
Copying my comment from #202:
I've talked to knack about this before, and they did mention a webhook-like functionality coming in the next major release. They described it as being able to create HTTP-request triggers attached to form submissions.

**Comment by sergiogcx** [comment]
@johnclary made an interesting comment on webhooks on issue #202 :
https://github.com/cityofaustin/atd-data-tech/issues/202#issuecomment-501374464

**Comment by johnclary** [comment]
Seems like we could possibly write our own javascript hooks as well:
https://www.knack.com/developer-documentation/#record-create

**Comment by amenity** [comment]
Thanks, y'all! Please just go ahead and edit the issue description if you think of anything else.

**Comment by johnclary** [comment]
- V3: pending release
    - 3.0 Release
        - primary focus at the moment
        - Ability add up to 3 views side-by-side
        - Other layout options

        - New building paradigms
            - introduce three views side-by-side
            - Flex bar with context on left hand side > it will be live preview while building
        - We can join beta planning
        - Handful of fixes
	
    - In the works prioritizing those and intend to share product roadmap

	- Much more flexible infrastructure after release
		- being able to use a filters and let users add their own filters

    - No way to tell when they’re coming
        - Built-in webhooks << is web 3
            - Shortly after v3 release
            - Definitely custom HTTP request
            - Target specific services, e.g., Slack. Action buttons in Slack to go two ways
            - Quickbooks and zeroes integration

    - Promotion and version control
        - In-between 
            - Add a record a rule to a view that no one in production has access to
            - Copy that data in the production
            - They’re still exploring it
            - Huge common request

    - Share Information Between Apps
        - Comes up quite often
        - During Vegas retreat they discussed shared object
        - Leverage a single object

- Usage analytics and usage
    - Comes up a lot
    - Unprioritied

- Logging
    - Nearer term after V3
        - logging section in the builder
        - Tasks have run

- Developer Documentation
    - Considering some version of it

- Ability to pull data out of Knack dynamically from external non-Knack APIs
    - Knack Bots
    - Make it possible to make a plugin that anyone could write

Steve will share a customer to install the little javascript in the Knack app

“Knack Models”
- Documented/supported features will not change without notice
- V3 is going to change

KnackCon
- Day 1: Organizing workshops
- Day 2: workshops

**Comment by amenity** [comment]
6/17/19

*DTS: Amenity, John*

*Knack: Steve, Nic*



### Reviewing our feature requests

In general, DTS'S requests are in line with others

- **Usage analytics for end users**
  - Very common need; comes up more when there is an external (e.g. consumer-facing) user
- **Logging for app builders and end users**
  - Not in v3 mvp, but subsequent version will have an activity log
- **Developer documentation within the app builder**
  - Are considering a version of this to support knowledge-transfer
- **Version control**
  - Most common request
- **Ability to promote code and sync data between servers/environments**
  - Adding new views, pages, submodules is okay to do in production
  - Making changes to field rules is iff-ier 
  - Nic's suggestion: Copy view into page in production no one has access to, can send link over; record rules can be restricted to a particular view
- **Share tables between multiple apps** 
  - Comes up a lot, people also ask for shared users
  - Will be able to designate one object between apps
  - Not in v3 release
- **Ability to pull data out of Knack dynamically from external non-Knack APIs** 
  - Not common
- **Built-in webhooks** - We currently do a lot of Python scripting with data download and pushing
  - Will be handled with new with Knack bots
  - Upcoming work is basic; form rules on submit - custom http request
  - Slack integration - button can be clicked in Slack and prompt action in app



### V3: Builder launch

Initial release: 

- New infrastructure, unified codebase, more flexible
- Ability to have three-column view layouts side by side
- When you open a view, you won't have a new modal take over - will have live preview in the app
- Bug fixes

Subsequently will be extending, more public roadmap will be available soon 



### General

**Has anyone built integrations?** 

- Yes, there is one company in particlar that does "plugin" stuff
- There is no formal workflow between vendors and Knack team, so no guarantee that these plugins won't break when there's a new release - but vendors will be involved in beta testing to prep



**Knack object**

Knack object is largely for internal use; totally subject to change. Exception is what is documented in  docs.Knack.com — these will be supported in future.  



**DTS priorities**

1. Promote from staging to production
2. Shared tables
