### ISSUE TITLE
Resolve Conflicting North Area Regs

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#2043]
QA Traffic Registry data and send questions to area engineers.

**Comment by alan-deanda** [comment]
I've sent the South and North Area Engineers the questions from AECOM. Once festival season is over I'll get in touch with Central Area Engineer Lee Austin, as festival season is taking up of all her time at the moment.

**Comment by johnclary** [comment]
AECOMM is going to deliver the data with the questions they have, as-is.

**Comment by johnclary** [comment]
@alan-deanda please attached emails with engineers

**Comment by johnclary** [comment]
@alan-deanda please re-orient yourself to this work and update this issue

**Comment by johnclary** [comment]
We're not doing this.
