### ISSUE TITLE
Setup ADFS Logins - ROW>TCP

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2049]

**Comment by johnclary** [comment]
i sent @dianamartin the email template for John D

**Comment by dianamartin** [comment]
I turned in a CTM HD ticket `CALL0029675`

**Comment by dianamartin** [comment]
Turned in a CTM HD ticket
- `CALL0029734`

**Comment by dianamartin** [comment]
John and I worked on getting this done. I had originally sent John D. the wrong metadata file without our keys. John D. had to resend me his metadata file. 

I was having problems configuring the apps. So John took a look and configured the ROW app. I still have the RPP app to do.
