### ISSUE TITLE
Wall / Privacy Screen for DTS Overflow

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#205]
Put shelving on hold. Need procard. Need help from truck-driving ATD staff to load/move stuff.

Should we just order whiteboards?

**Comment by amenity** [comment]
@alan-deanda and I prefer no shelves for our end. 

[Here's the Stanford d-school DIY version of white boards that we had at ODD](https://www.instructables.com/id/Build-a-Z-Rack-Whiteboard/).

**Comment by johnclary** [comment]
That is to say you prefer no screen? e.g whiteboard?

On Jun 11, 2019, at 18:04, Amenity Applewhite <notifications@github.com<mailto:notifications@github.com>> wrote:


@alan-deanda<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falan-deanda&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C20827369d742439ca60708d6eec12c91%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C636958910778826645&sdata=CW2P1aJgeAE0UAZiXJh%2BMeZT0ABiIkizZmiQBcoGMXk%3D&reserved=0> and I prefer no shelves for our end.

Here's the Stanford d-school DIY version of white boards that we had at ODD<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.instructables.com%2Fid%2FBuild-a-Z-Rack-Whiteboard%2F&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C20827369d742439ca60708d6eec12c91%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C636958910778836659&sdata=CVFW%2FbFWZAuO7FlqcuIoSx9EXu8DpE6DPad1yQFIUhc%3D&reserved=0>.

**Comment by amenity** [comment]
I would take a white board, but not a big deal if they’re expensive. I don’t want shelves. ;)

**Comment by johnclary** [comment]
Asked David to price these mobile whiteboards. I think they'd look better than the shelving, and will be more useful.

6' x 3'

https://www.staplesadvantage.com/shop/StplShowItem?catalogId=4&item_id=198380900&langId=-1&currentSKUNbr=24393547&storeId=10101&itemType=1&addWE1ToCart=true&documentID=4af09a78b884bff89e2592b05f3a44b7c0202430

6' x 4'

https://www.staplesadvantage.com/shop/StplShowItem?catalogId=4&item_id=164622281&langId=-1&currentSKUNbr=24011229&storeId=10101&itemType=1&addWE1ToCart=true&documentID=98029737f03d05ae4e20784b5578c77e37ec84d1

6' x 4' (Platinum!)

https://www.staplesadvantage.com/shop/StplShowItem?catalogId=4&item_id=52377170&langId=-1&currentSKUNbr=891214&storeId=10101&itemType=1&addWE1ToCart=true&documentID=43051063a06a315df93853de3f08ae92a4348d63

**Comment by johnclary** [comment]
Submitted a PR for two [of these](https://www.amazon.com/Whiteboard-Aluminum-Rolling-Accessories-Stickers/dp/B07FPDQ8S8/ref=sr_1_32?crid=BY6ZQ5F5UBDF&keywords=white+board&qid=1560356950&s=gateway&sprefix=white%2Caps%2C176&sr=8-32), which are significantly cheaper on Amazon ($170) vs $360 at staples.

And I reached out to Peggy to let her know our need.
https://atd.knack.com/finance-purchasing#reviews/purchase-request-details/5d01318dea5f24000cc463c2/

**Comment by johnclary** [comment]
Request had been approved, so we’re going with whiteboard instead of shelving. Two of em

**Comment by mateoclarke** [comment]
![bart_whiteboard](https://user-images.githubusercontent.com/5697474/59450162-372d3600-8dce-11e9-8a47-191e4a764a05.gif)

**Comment by johnclary** [comment]
Have my procard but had to request an tax-exempt amazon account from central purchasing. Just did that.

**Comment by johnclary** [comment]
Ordered from Amazon. Arriving Monday.

**Comment by amenity** [comment]
Thanks, @jaime-mckeown for assembling! They look great.
