### ISSUE TITLE
TCP Data Migration Automation

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2050]

**Comment by johnclary** [comment]
@dianamartin lmk if you want to discuss

**Comment by dianamartin** [comment]
Scheduled work session for 6/22

**Comment by johnclary** [comment]
Script is in progress. Aiming for Sprint 29

**Comment by johnclary** [comment]
@johnclary finish this in sprint 30!

**Comment by johnclary** [comment]
This is done and ready.
