### ISSUE TITLE
Migrate TCP Reviews Out of AMD Data Tracker

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2052]
The TCP Tracking module does not belong in the AMD Data Tracker—it is solely a ROW tool. Let's move it to a new ROW app. There's an old "ROW Portal" that Tracy created, but unclear if anyone's using it. If so, we can migrate those modules as well. TBD.

**Comment by johnclary** [comment]
@amenity FYI, some non-urgent tech-debt here. I suggested Diana take this as a back-burner project.

**Comment by amenity** [comment]
@johnclary @dianamartin should we move this to the backlog?

**Comment by dianamartin** [comment]
@amenity I wanted to schedule time with John to do the migration with his guidance. I didn't know if he had any time on Friday, but that's when I was planning to do some TCP stuff.

**Comment by johnclary** [comment]
@dianamartin happy to help just get it on my calendar.

**Comment by dianamartin** [comment]
@johnclary Scheduled for next Monday 6/22, you are quite busy this week

**Comment by johnclary** [comment]
Scripts are ready!

**Comment by TracyLinder** [comment]
@ChrispinP can you update this epic please. Specifically check out the backlog items and see if they're still applicable.
