### ISSUE TITLE
VZD | ETL | Fix person table mode assignment or remove columns from people dataset in Socrata

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#2056]
With updates to include data about mode counts for fatalities and serious injuries in the Crash dataset, the script no longer populates the people mode flags, `mode_id`, or `mode_desc` columns in the People dataset. The visualization in VZV that previously used the People dataset mode data now uses the Crash dataset so these columns may not be necessary at all. The code affected is linked below.

Need to either:
- [ ] Remove mode flags, `mode_id`, and `mode_desc` columns from the People dataset
- [ ] Remove the code that populates these columns

Or:
- [ ] Update the ETL to populate these fields correctly

https://github.com/cityofaustin/atd-vz-data/blob/366e5105351d3a2daae18377b0c56988072834ed/atd-etl/app/process/helpers_socrata.py#L229-L264

**Comment by JaceDeloney** [comment]
Close this out and create an issue to revisit our VZ public datasets to determine which fields we feel confident in providing the public.
