### ISSUE TITLE
Bug | Missing VZD crash data

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2059]
**Issue #1**
Xavier found some disparity in the data coming out of the VZE database. It appears as though there is an issue with crashes that are not in the database. In November of 2019, it looks like we are missing over 1k crashes.

See attached file of the analysis (missing crash list and the count differentials) and the method of validationhe used is to emulate a data extract out of MicroStrategy (APD crash data only). This data is what APD uses for their reports and we should be off by no more than ~1% (because we are also identifying non-APD crashes that occurred within Austin city limits).

[https://app.zenhub.com/files/140626918/4704da82-fbcd-4f7b-8d9f-c10f7a0a7d5b/download](https://app.zenhub.com/files/140626918/4704da82-fbcd-4f7b-8d9f-c10f7a0a7d5b/download)

![thumbnail_image002.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/0d6d4914-b8df-47a9-9c7b-e0203545381d)

**Issue #2**
Also, Xavier is concerned that he is not looking at a mirror of what is in the VZD and if I will need to source the data a different way.

Attached is the query he used to find these “missing” persons and the list of the crash_id’s that are not in the atd_txdot_person table. Below is a screenshot of one of the crashes in the “missing” list, but it shows people in the VZE production site.

![download.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/c2102dd8-eaf1-4245-85cd-3f171b92bdbb)

**Comment by JaceDeloney** [comment]
Reach out to me for access to the csv file.

**Comment by sergiogcx** [comment]
Hi @JaceDeloney I will swing by your desk, or PM you

**Comment by sergiogcx** [comment]
I've checked with Mateo and his ETL process is finished, I have let a day run by so the backups are created automatically.

I am fixing to get this started today, I am inserting all of 2019 to begin with. I expect this to take a few days, there may be some performance degradation in VZE.

**Comment by sergiogcx** [comment]
The process was started about an hour ago, will let it run overnight.

**Comment by sergiogcx** [comment]
The 2018 and 2019 data has been inserted, will continue the process for  2015, 2016, and 2017.
