### ISSUE TITLE
Wiki page on teleworking technologies

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2064]
### In light of the COVID-19 outbreak, how might we empower ATD staff to work and collaborate remotely?

[Wiki documentation](https://atd-dts.gitbook.io/wiki/resources-for-atd-staff/working-remotely):
 - Teleworking software (AnyConnect (Cisco), GoToMyPC, Citrix, etc.)* 
 - Phone forwarding*
 - Online meetings
    - Teams
    - Skype

- [x] @dianamartin - ask Scott if he has anything to add
- [ ]  @SurbhiBakshi - add GoToMyPC info as you do that 
- [ ] Everybody add best practices
- [ ] Support section, e.g. who to reach out for for different stuff including atd help page

* Probably/hopefully existing docs on this from CTM or HR?

**Comment by amenity** [comment]
@johnclary @dianamartin - I think it would be awesome if Diana is able to prioritize this... Perhaps also set aside time to train people and/or troubleshoot?

**Comment by dianamartin** [comment]
## Teleworking Software
- This would need to be installed by Scott Reedy and teleworking approved your supervisor. 
- Some of these licenses cost money (ex. GoToMyPC).

## Phone Forwarding 
- [Instructions on how to request phone forwarding in Service Portal link](https://atx.service-now.com/sp?id=kb_article&sys_id=14a79820dbbfb3005b03f482ba961972)
- [Instructions on how to setup and use phone forwarding](https://atx.service-now.com/sp?id=kb_article&sys_id=c918d420dbbfb3005b03f482ba9619fc)

## Online Meetings
According to Scott, most if not all of you should already have Skype on your computer.

First thing is first, check if your computer has it already installed. Click on the start button on the bottom left of your screen and begin typing “Skype”. You may see Skype, but we want to make sure “Skype for Business” is installed as well. 

**Step 1: Search if Skype is already installed**
Microsoft Skype
![image](https://user-images.githubusercontent.com/21112975/76347032-f0745a00-62d3-11ea-9643-2185e08c6121.png)

**Step 2: Log in**
You will want to enter in your work email, it may also take you to the city’s log in page where you’ll need to enter your email address and network (computer password). 
![image](https://user-images.githubusercontent.com/21112975/76347085-0550ed80-62d4-11ea-9288-e9429e474a97.png)

If you didn’t know, you can create a meeting that has remote access to Ms Skype or Ms Teams.

**Step 3: (Optional)** Open Outlook and go to the calendar tab and you’ll see on the menu bar these options. It will add a remote meeting link to your meeting invite and a phone number for users to call. You can choose to call in using the phone line or using your computer to be on the call (headphones may be required). When using laptops some can allow you talk through your computer’s microphone. 
![image](https://user-images.githubusercontent.com/21112975/76347107-0f72ec00-62d4-11ea-86e1-adffa586474b.png)

_NOTE: Skype for Business is being retired by Microsoft. CTM staff have ceased use of Skype in their Department, they are solely using MS Teams. A lot of other departments are also slowly transitioning from Skype to Teams._ 
[Read more information here](https://docs.microsoft.com/en-us/microsoftteams/faq-journey)

Another alternative is Microsoft Teams (MS Teams). I think some of you are using this application already. This has the same functionality as Skype allowing you to chat/connect remotely to a meeting and screen share. 

**Step 1: Search if Teams is already installed**
Microsoft Teams
![image](https://user-images.githubusercontent.com/21112975/76347125-17329080-62d4-11ea-9dcd-c5ec2b54ad4d.png)
**Step 2: It will have a similar log in page to Skype.** _(You’ll need your city email and network password.)_

**Comment by dianamartin** [comment]
@amenity which wiki would we put it into?

**Comment by amenity** [comment]
[Aquí, por favor](https://atd-dts.gitbook.io/wiki/resources-for-atd-staff/working-remotely). 🙏

**Comment by dianamartin** [comment]
@amenity I added it to the GitBook, can you review

**Comment by amenity** [comment]
@johnclary - when/how do you want to share this with the department?

**Comment by johnclary** [comment]
@amenity @dianamartin awesome work! will review and discuss w/ peggy

**Comment by dianamartin** [comment]
@johnclary @amenity I need to add the couple other things that Jen mentioned:
- Instructions for checking voicemail remotely
- Change password from work now, so you don’t have a password change required when you’re working remotely

**Comment by SurbhiBakshi** [comment]
@johnclary @dianamartin @amenity - as per Scott, GoToMyPC is not an option unless you are grandfathered in from three years back. Citrix is the way to go for Remote Desktop.

**Comment by amenity** [comment]
Got our MVP wiki out.  🙌
