### ISSUE TITLE
Migrate AMD Data Tracker to Dedicated Server 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2069]
Move AMD Data Tracker to our dedicated Knack server. Asses performance imrprovements:

- Signals list page
- Signal pages (each individual signal)
- Map loading on individual signal pages
- TMC Issues pages (each individual CSR)
- Flex note reliability
- Loading time from 311 (don’t know if we can speed up the amount of time it takes to load a CSR into Data Tracker from the 311, currently ~7 minutes)

Compare to #2066

**Comment by amenity** [comment]
cc @dianamartin @johnclary

**Comment by dianamartin** [comment]
I created an issue for this already, it’s in progress and has the time tests I did.

**Comment by dianamartin** [comment]
@amenity, do we close this out as a DUP?

**Comment by amenity** [comment]
Yup, JINX! 👯‍♀️

**Comment by amenity** [comment]
Lol

**Comment by johnclary** [comment]
@dianamartin would you coordinate with Steve and AMD to schedule this migration?

**Comment by amenity** [comment]
As far as migration windows, from Lance:

> Our current hours of operation have and should continue to remain the same.
> 
> M-F 6am-8pm
> Sat 9am-6pm
> Sun 10am-6pm
>  
> Afternoons are typically a bit slower for us since we typically have less scheduled technician work that we are coordinating. Obviously we’d prefer a weekend for that reason, but we can do an afternoon if that works. Just let us know when we think this will occur and we’ll be able to work around it.

**Comment by dianamartin** [comment]
Migration happened on 4/13.

Knack response 4/14 in the morning
> Just to update you, appears the migration went just fine, it finished just after 12:30am EST last night. Take a look around, make sure things are working properly and let me know if you have questions or issues.

>The migration is all complete and you are able to continue as normal.

John said
>Thanks, Steve! All looks good. Really appreciate your help. Thanks. 

>Everything looks good to me. It's definitely faster, but not as noticeable as Signs and Markings was.
