### ISSUE TITLE
Meet with AMD to discuss requirements for general work order

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2071]
Scheduled meeting 3/24/2020.

[See meeting minutes for more context.](https://docs.google.com/document/d/1Pe9Fh81OcN7Vtm7WplQVO4QNOjP2vIw2omE7DeWSiqM/edit#) 

[AMD Meeting notes from 3/31](https://docs.google.com/document/d/1U5m4fgEir_atcRwKgmvxc87iJ6OondnMj2KvbPcvuFo/edit#)

**Comment by dianamartin** [comment]
Meeting was rescheduled to 3/31 (following Tuesday) due to meeting conflict on 3/24.
