### ISSUE TITLE
Debrief on process used and document for future reference

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2074]
### Objective 
Debrief from Meeting - Review of AMANDA data pull and next steps so that we are prepared for next year. 

### Agenda
Create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and save as a publicly-visible file in Google Drive.

------
- [x] Schedule meeting
- [x] Meet and take notes in agenda doc
- [ ] Create resulting issues

**Comment by amenity** [comment]
@SurbhiBakshi - schedule, please!

**Comment by SurbhiBakshi** [comment]
Meeting on 3/26

**Comment by dianamartin** [comment]
@SurbhiBakshi does this need to be closed?

**Comment by johnclary** [comment]
[New issue](https://github.com/cityofaustin/atd-data-tech/issues/2244) to document process.
