### ISSUE TITLE
Meet with Randy and Pat to discuss VZA app

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#208]
### Objective 
APD scheduler and citation officer user research

### Participants
DTS: John, Amenity
APD: 
 - Randy Davila -  from Special Events schedules overtime shifts
 - Pat Oborski - VZA point of contact for all sorts of stuff and also works these shifts
Maybe Lewis?

### Agenda
- Introductions
- Walk us through process
- Specific questions
        - How many unique officers sign up?
        - How do they sign up?
        - How is it promoted?
        - What devices/software used?
        - Location captured anywhere? (GPS on car...are these shifts always covered from within a car?)
- Set up user observation and/or interviews

------
- [x] Schedule meeting
- [x] Meet
- [ ] Attach meeting notes to this issue
- [ ] Create resulting issues

**Comment by johnclary** [comment]
*June 19th Notes w/ Amenity, Randy, Pat, Lewis*

- Revolution 911 software for scheduling for special event overtime. It invoices and everything
    - austin911.com
- Goals:
    - Randy or Pat: need to standardize and digitize. “Everything is a little bit different” when done on paper
    - Randy or Pat: be able to track metrics on how officers are performing
    - Randy or Pat: User friendly as much as possible
    - Know if the shifts are getting filled
    - Need to count Horus spent

PC:
- Windows 7 system
- Uses CITRIX
- Mobiel cad
- PTU is admin
- E-Cite is an android phone
- Every officer is an iPhone, have email access
- iPhone 10R
- Wireless connectivity all the time
- Every officer has an iPhone

Process
- Randy creates shifts in revolution
- Officer signs up
- Randy approves signup
- Randy sends an email reminder to people who have signed up
    - Email has citation logs attached, could be replace with link
- Q: Officer are accustomed to accessing email in vehicle? A: Yes
- Two contacts per hour


Possible Solution:
- Lewis does schedule online in Knack
- Randy references Knack schedule + shift number when creating schedules in Revolution 911
- Randy gives officers their shift number and link to Knack form in reminder email
- On shift, officer follows link using iPhone, enters shift number, which auto-completes and links back to a scheduled shift.
- This creates a “shift” record and redirects to shift “details” page
- the officer can repeatedly submit citation form from shift details
- Citation form automatically captures location
- When finished, officer hits “end shift” button to finalize


Todo:
- Contact Sgt Cardier at PTU for possibly getting a dev phone
- Prototype by mid July

**Comment by amenity** [comment]
### Goals

- Quantify program's ROI
  - Officer performance
  - Geographic "hot spots"
  - Types of citations
- Maximize efficacy 
  - Leverage 👆metrics to have the best officer + best place + right time with the right vehicle
  - Streamline officer workflow
    - User-friendly as much as possible 
    - Work with their existing technology

### Workflow

1. Lewis compiles schedule in Excel and emails to Randy
2. Randy puts shifts into [Revolution 911](http://austin911.com/) 
3. Officer logs in to Revolution 911, selects desired shift
4. Randy approves and sends email reminder with Excel doc attached
5. Officer checks email to see what assignment is  - _Opportunity: include link in email to the form they'll use_
6. Officer gets on shift, log into their account on the car laptop, goes to assigned location
7. Officer records citations
   - Some download doc and edit in Excel as they make citations
   - Some print the PDF at the station and at the end of their shift use Brazos tablets to look up all the citations and write them in; Brazos does not make this easy, lots of clicking
   - Records which block/intersection in the stretch of assigned road; sometimes stay, sometimes move around - depends on location
   - Supposed to update spreadsheet every 20 minutes or at least 2x/hour; if no citations record that that there haven't been any
8. Officer emails PDF as attachment to Randy
9. Randy compiles PDFs and sends to Lewis 





### Hardware

- Citrix laptop 
  - VPNed to the City network
  - Windows 8  
  - Touch screen
  - Not carried on motorcycle
  - Police Technology Unit is admin - James Cartier is sergeant 
  - Good connectivity - planned outages
  - Software updates in hot spots

- City-issued iPhone 10R

  - [Firstnet](https://www.firstnet.com/marketing/index.html#/marketing/index/home) - priority ATT network for first-responder; solid connectivity
  - Locked down catalog of apps
  - Use e-cite on phone
  - Safari - can visit any site
  - Officers have email on phones
  - Carried by all officers at all times

  

### Applications

- [Revolution 911](http://austin911.com/) - comprehensive event scheduling software
  - Special Events uses for all overtime scheduling, e.g. ACL
  - Could potentially specify skill requirement 
- [Visitinet](https://www.officer.com/command-hq/technology/communications/dispatch-technology/product/10047173/tritech-software-systems-visinet-mobile) 
  - Always open on laptop
  - See locations of all active calls on a map
  - Drill down 



### Next steps

- Prototype

- Set up user observation and/or interviews



### Notes

- Officer has autonomy to change locations if nothing is happening 

- Potentially 8 officers per shift - less than 100 unique officers doing this 
- Randy needs to know the number of officers for billing purposes, but doesn't use the forms for anything
- A



**Is location captured by GPS anywhere?** 

- All cars have GPS
- Body-worn cameras have GPS - *Would need to use this for officers on motorcycle, bike, foot*

**Comment by amenity** [comment]
![IMG_1932](https://user-images.githubusercontent.com/1463708/60307813-c75d9600-990b-11e9-94d9-4b4c8e93db22.jpg)
![IMG_1929](https://user-images.githubusercontent.com/1463708/60307814-c7f62c80-990b-11e9-81bd-636c10160f98.jpg)
![IMG_1927](https://user-images.githubusercontent.com/1463708/60307815-c7f62c80-990b-11e9-9797-1424f164b28a.jpg)
![IMG_1926](https://user-images.githubusercontent.com/1463708/60307816-c7f62c80-990b-11e9-8d7c-c4af8d09cb1b.jpg)
![IMG_1934](https://user-images.githubusercontent.com/1463708/60307817-c7f62c80-990b-11e9-999b-b553498cec4e.jpg)
![IMG_1938](https://user-images.githubusercontent.com/1463708/60307818-c7f62c80-990b-11e9-9ee3-195c143e1966.jpg)
![IMG_1937](https://user-images.githubusercontent.com/1463708/60307819-caf11d00-990b-11e9-8056-2f6fe80e9c92.jpg)
![Screen Shot 2019-06-27 at 3 47 22 PM](https://user-images.githubusercontent.com/1463708/60307820-cb89b380-990b-11e9-9b0c-2b3b7dc3b352.png)
![IMG_1936](https://user-images.githubusercontent.com/1463708/60307821-cb89b380-990b-11e9-8cfe-963dd302ae97.jpg)
![Screen Shot 2019-06-27 at 3 41 18 PM](https://user-images.githubusercontent.com/1463708/60307822-cb89b380-990b-11e9-9500-a4cb68d57166.png)
![IMG_1935](https://user-images.githubusercontent.com/1463708/60307823-cb89b380-990b-11e9-8a01-2926947751a4.jpg)
