### ISSUE TITLE
User research  in field for VZA app

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#209]
Connect with Pat to see about doing a ride-along to see current process.

**Comment by amenity** [comment]
@SurbhiBakshi - were you able to take any photos when you were there?

**Comment by SurbhiBakshi** [comment]
@amenity I did get some photos, and some of the documentation used in the current process.

**Comment by amenity** [comment]
@SurbhiBakshi - Yay! Would you please stick them here: https://drive.google.com/drive/folders/1IUXtA0WsDXK5WfFidIZCfuDg5DjkHvOt
And if you have any notes, please attach here as comments or link to a Google Doc.

**Comment by amenity** [comment]
@SurbhiBakshi - bump ☝️ 😉

**Comment by SurbhiBakshi** [comment]
[https://drive.google.com/open?id=1I-nWVbpAV6OA90CC_AKr_O1obDh7HKgr(url)

**Comment by SurbhiBakshi** [comment]
@amenity - Added a handwritten log, LLewis's schedule of shifts, and RDavila's assignments.
