### ISSUE TITLE
Grainger demo

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#210]
### Objective 
See what Grainger can offer for warehouse inventory management. 

### Participants
Amenity, Diana

------
- [x] Schedule meeting
- [x] Meet
- [x] Attach meeting notes to this issue
- [x] Create resulting issues

**Comment by amenity** [comment]
Grainger serves a lot of departments in the City as supplier
- Water, Convention, Energy are top users
- Have free services available to customers — training, configuration, consulting looking at process, figure out where SAP system can tie in 

- Also provide resources - e.g. a person who can be onsite doing inventory management for a few hours a day

There was a point where they were trying to develop an inventory management solution but realized that wasn't really their business and couldn't support it, now Now simplified to KeepStock, simple tech on Grainger.com: 
- Labels on products, print, scan with iPhone or similar
- Set minimum and maximum for each item
- Doesn't have ability to see current stock
- Can finagle system to count unopened ship packs (Grainger only) for financial audits
- 90% Grainger and 10% Vending Machine

Recommends [FacilityDude](https://www.dudesolutions.com/industries/government/work-asset) for low-cost web-based app 

City of Austin contacts
- Long Lee at Austin Fire Department -  manages similar amount of inventory at ATD
- William (Bill) Aldereti with EMS - -  manages similar amount of inventory at ATD; was on AIMS, switched to Maximo
- Rick Harland - Division Mgr. Supply Chain / Fleet Management figured out how to set up thresholds so that the PRs go through AIMS

**Comment by dianamartin** [comment]
### Diana's Notes

Dane Williams 
Grainger Government Contract Rep 

Supplier of Goods 
Services that compliment  
Platform developed 

Purchasing background 
Citywide master agreement 
Not a blanket PO 
Quoting process – Finance getting a DO 
$200 - $8,000 order 
ATD is the 10th largest department 

Inventory Services 
 
Program Users 
- Austin Water  
- Fleet  
- Building Services 
- Convention Center 
- Aviation – buildings 
- AFD 

Generally free 
Require a resource (ex. 2 to 4 pm) to do stuff – Reorder services in warehouse, counts

Played with having an inventory system – technology updates were happening so fast 
Simple platform – Grainger.com  - KeepStock 

Process 
- Label on the product 
- Mobile device to scan the label 
- Doesn't tell you current on hand quantity 
- Useful for reorder 

API (application program interface) Integration. Tie it into an inhouse system? No, not available 
Does a cycle count on what's on site? 

Blank signage – won't be captured in the program (only the Grainger products) 
Bring in consulting team  
Evaluate purchasing process 
Give recommendations to ATD 

SAP system can integrate with Purchasing System 
Shopping in their in-house system 

 Other Inventory Programs – web based applications 
- School Dude 
- Facility Dude 

City of Austin Contacts 
- Long Lee – Finance AFD (Maximo SaAs) 
- William Aldaretti – EMS (Maximo SaAs) 

Grainger Vending Machine  
80-90% of Grainger products 
Ability to print labels from the system 

Fleet's $5 rule – less than $5 don't have to inventory 

Central Purchasing – isn't giving up on AIMs 

Austin Water comment about – using AIMs (delays in syncing) 
So not real time 

How much of our ATD inventory are Grainger products? What percentage? 
AMD: 
>None of our AIMS managed warehouse inventory comes from Grainger though we do purchase small tools/minor equipment from them.

SMB:  
>For Signs, Markings and Banners, our majority of inventory stock “materials” and/or supplies are not purchased from Grainger however general supplies, small tools and minimal equipment are roughly 10 - 15% of these could be inventory items. I can see where a software system would allow us to add additional items, supplies, materials and/or equipment to the system for accountability and tracking thus resulting in potentially 85% of all items there in.

Work flow Discussed 
Knack --> AIMS --> SAP (Grainger)

**Comment by dianamartin** [comment]
Added my notes, closing issue.
