### ISSUE TITLE
Live Teams training for department - 3/16/20

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2103]
@dianamartin is going to curate WPD presentation decks to compile a training for staff on Monday 3/16.

**Comment by dianamartin** [comment]
@amenity this should be closed, no?

**Comment by amenity** [comment]
Yes! Can you add a link to the recording?

Sent from my phone

On Mar 17, 2020, at 1:22 PM, Diana <notifications@github.com> wrote:

﻿
*** External Email - Exercise Caution ***

@amenity<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famenity&data=02%7C01%7CAmenity.Applewhite%40austintexas.gov%7C214ef26b07754514494f08d7caa028f1%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637200661536800397&sdata=jIOP%2B0P1Zc1LZnIqoMugyCQsnL4PGsHWq3fHSqJQmaY%3D&reserved=0> this should be closed, no?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-data-tech%2Fissues%2F2103%23issuecomment-600226006&data=02%7C01%7CAmenity.Applewhite%40austintexas.gov%7C214ef26b07754514494f08d7caa028f1%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637200661536800397&sdata=AuLJSyZD2oGwDvjxyee381Nrf5m%2Bjr1itEAN5HldP2Y%3D&reserved=0>, or unsubscribe<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAALFLHGBIXEKXTGJZ5AKHLDRH65WPANCNFSM4LHHMA2A&data=02%7C01%7CAmenity.Applewhite%40austintexas.gov%7C214ef26b07754514494f08d7caa028f1%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637200661536810350&sdata=EEUB2UCn61UOqCTqyDGQq5Fy5%2B5jt6Puu1fZ71tPUXo%3D&reserved=0>.

CAUTION:This email was received at the City of Austin, from an EXTERNAL source. Please use caution when clicking links or opening attachments. If you believe this to be a malicious and/or phishing email, please forward this email to CSIRT@austintexas.gov.

**Comment by dianamartin** [comment]
@amenity its on the wiki

**Comment by amenity** [comment]
Recording [here](https://web.microsoftstream.com/video/4f4d18e9-5241-4d6b-8752-2e57eb0df844).
