### ISSUE TITLE
Best practices and agile methodologies for remote work

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2113]
**Objective: Help ATD staff work productively as remote, distributed teams** 
   - [Remote meeting best practices](https://agileintheether.co.uk/remote-meeting-tips/)
   - Agile methods, e.g. daily standups, retros
   - etc. etc. 
There is a *ton* already written on this stuff and more every day, so lots of compiling and simplifying existing resources

Format:
  - Section in the ATD Staff Resources wiki
  - Live Teams training

**Comment by johnclary** [comment]
We did it, right? Closed
