### ISSUE TITLE
[ATD Teleworking Guide] GoToMyPC documentation 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2115]
Add GoToMyPC page to the Working Remotely section of the [ATD Staff Resources wiki](https://atd-dts.gitbook.io/atd-staff-resources/). 

[Here is the PDF CTM created](https://cityofaustin.sharepoint.com/sites/COATeleworkInstructions/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCOATeleworkInstructions%2FShared%20Documents%2FCOA%20Go%20to%20My%20PC%20Set%20Up%20Information%2Epdf&parent=%2Fsites%2FCOATeleworkInstructions%2FShared%20Documents&p=true&originalPath=aHR0cHM6Ly9jaXR5b2ZhdXN0aW4uc2hhcmVwb2ludC5jb20vOmI6L3MvQ09BVGVsZXdvcmtJbnN0cnVjdGlvbnMvRVdzeTRnTmhSQXhQdWtEUlF2dHRZRklCTjdNb1ZvblJ0dFJ3d3M3Y3dpTEZodz9ydGltZT1wVkp4UlkzSzEwZw). 
- [x] Verify that the CTM guide provides all the instructions staff needs by performing a fresh install on a PC.
- [ ] Check with CTM to see if they are going to make this available as text in their help docs so that employees can reference without needing Microsoft Word or being on a desktop device. 

If not:
- [x] Add _GoToMyPC_ page to the _Working Remotely_ section of the [ATD Staff Resources wiki](https://atd-dts.gitbook.io/atd-staff-resources/). 
- [x] Add step by step instructions with any helpful screenshots to wiki
- [x] Update _Getting Started_ page to explain who should be using GoToMyPC

**Comment by moorerst** [comment]
Need a GTMPC account so I can test the documentation. Added my name to the spread sheet to request account.

**Comment by amenity** [comment]
@moorerst - would it be possible to start this without a GTMPC license? Add link to the PDF to the docs, update info on who should use GTMPC, etc.

**Comment by moorerst** [comment]
Added GOTOMYPC documentation to the Connect To Computer on the Google Doc outline also added a link to the ServiceNow Service Request to request a GTMPC account.
https://docs.google.com/document/d/1A-z1F2EzNdU5T8nX_6jAIroswL70kXzYnZFtE9JMkGY/edit#

**Comment by amenity** [comment]
I checked with CTM - they do not have plans to convert documentation from PDFs to HTML.😞
