### ISSUE TITLE
Feature request: New Parking Enforcement Dispatch System

### ISSUE THREAD

**Issue by teripennington** [cityofaustin/atd-data-tech#212]
Lyndon Meris would like a system that is easy to use and would allow metrics to be pulled from it.  Data and Tech would like a system that is easy to setup and maintain.

Typing is difficult and dispatchers are using the system differently from each other.  Management would like to know how well parking enforcement is doing and without metrics this is difficult.  Matching CSRs with the 311 system, understanding how often a call turns into a citation, the frequency of booting and towing of cars, the problems with enforcing the residential parking program are all questions that can't be answered currently.

The outcome would be an easy to use system whose data could be exported and excel or a data analytics package could analyze the data.  

Currently Dispatch is using Trello

**How would you rate the impact of this issue?**
- [ ] Unsure
- [ ] Severe impact to ATD services
- X Major impact to ATD services
- [ ] Minor impact to ATD services
- [ ] Does not affect ATD services

There is no known due date.

Solution:  A sharepoint list (see attached mock up)
[mock up dispatch.pptx](https://github.com/cityofaustin/atd-data-tech/files/3292167/mock.up.dispatch.pptx)

**Comment by teripennington** [comment]
basic site completed, instructions completed.  I need to setup a time with Lyndon and see if there is anything else needed on the site.

**Comment by amenity** [comment]
Email update from @teripennington on 6/27
>>>Dispatch is using the sharepoint list for dispatch successfully.  I trained Arthur Acuna and made some small changes in the solution.  It is [here](https://cityofaustin.sharepoint.com/sites/ATD/dispatch/Lists/Dispatch/Dispatch%20mode.aspx?CT=1565295136497&OR=OWA-NT&CID=f61a2843-2bf4-4800-8720-01528c2adb73).  I created a how to document for the dispatchers and for Lyndon so he can make small changes himself.  It took me about 3 hours total (req, sharepoint site, and training).
