### ISSUE TITLE
Write Interview Questions

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2124]
[Doc](https://drive.google.com/drive/u/1/folders/1XaLnBwghKLTvQ_m5Wk50q3nKp-Ljkvw6)

- [ ] @dianamartin @johnclary @amenity - add any interview questions you suggest
- [ ] @SurbhiBakshi write up TIA fees in AMANDA information to use as a hypothetical scenario for the interview.

**Comment by amenity** [comment]
Done!
