### ISSUE TITLE
Transfer AGOL SmartTrips Account

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2127]
Ashley let me know that they needed to reset the password, but weren't getting the email. I decided to change the Smart Trips account to be linked to my email so I can administer it.

**Comment by jaime-mckeown** [comment]
Emailed Ben about this request, then submitted CTM Request for the change.

**Comment by jaime-mckeown** [comment]
Received the email to create a new password. Sent Ashley the login info.
