### ISSUE TITLE
Parking Datasets Technical Discussion with Francesco Z.

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2128]
Need to work with new Parking GIS Analyst to get him familiar with what we have done for the Parking data migration to SDE, schema changes, relationship classes, Pro and attribute rules, etc.

**Comment by johnclary** [comment]
Jaime sent the docs to Yunuen. Waiting to hear back from her to schedule training.

**Comment by jaime-mckeown** [comment]
Meeting with Francesco this afternoon to go over the more technical details of the parking data before meeting with Francesco and Ryan on Wed.

- [ ] Enterprise GDBs, versioning, CTM's weekly updates to GDB

- [ ] Feature Dataset, Topology, Relationship Classes

- [ ] Feature Classes and Table

- [ ] Attribute Rules

**Comment by jaime-mckeown** [comment]
Meeting with Francesco and Ryan to discuss the data setup

- [ ] Overall data, how it differs from current setup in AGOL

- [ ] Relationship Classes and how they work for editing the data (select related data option)

- [ ] Active / Retired records, process to correctly retire restrictions, zones, etc.

Add more topics after discussion with Francesco.

**Comment by jaime-mckeown** [comment]
Went over a lot of things with Francesco today. Will talk more about the data setup and schema on Wednesday when Ryan can attend as well.
