### ISSUE TITLE
Meet w/ AMD to Review Ranking v0.1 3/19/20

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2129]
Include Andres, Renee, Jen, Brian, John C.

**Comment by jaime-mckeown** [comment]
Sent out an email to see if Jen and Brian would like to be included in the next meeting, or if they would like us to meet first since schedules are pretty busy at the moment.

**Comment by jaime-mckeown** [comment]
@johnclary Renee would like to meet with myself and Andres to get back on track first, then schedule with managers. We will be meeting tomorrow, then I will schedule another meeting with Jen, Brian, and you. Thanks!

**Comment by jaime-mckeown** [comment]
Renee's email to Jen & Brian after meeting:

> Just wanted to provide you with a brief update from our meeting today (Jaime & Andres, please jump in with anything I have missed).
> 
> - We reached out to Joel to coordinate with the ATD Pedestrian Crossing Guidelines Tool.
>    - He commented that there are a number of 2 lane locations that this tool identified as being appropriate for a PHB. Currently our criteria only considers major and minor arterials. Jaime will run our criteria against the previously excluded road classes (basically excluding arterials and highways) to see what shows up as high ranking. We can then consider if we include streets on a case by case basis or change how we run the criteria.
>    - It is our observation that the Pedestrian Crossing Guidelines tool is dependent on data that may not always be available (85th %ile speed, traffic volumes, ped volumes) and makes assumptions when data is missing. We think we may be able to identify available data from the PHB Evaluation criteria to serve as a proxy for this data (for instance, find a way to use land uses or other data to replace pedestrian crossing volume, etc). In addition we could look at tweaking the scoring on the PHB evaluations to create lower tiers to identify where other crossing improvements might be more appropriate. After we’ve looked at this in greater detail, we’ll reach out to Joel to get his input.
> - We decided to convert the pedestrian crash data set from CRIS to Vision Zero data; with the understanding that the VZ data is cleaner and more accurate than CRIS.
> - We discussed some of the challenges with using street segments for this evaluation. Jaime will check with VZ to see if they have polygons created for every street. If so, we may consider using the polygons instead of street segments.
> - Jaime thinks VZ has mapped speed limits but did not map to our street layer. She will follow up on this and may offer to assist in the conversion of this data.
> Continuing issues:
> Still looking for an accurate way to identify medians and number of lanes. May follow up with Signs & Markings data to see if this works.
> - Sidewalk data is still missing as well. We will continue to investigate what is available.
> 
> We will meet again in the next week or two to discuss progress.
