### ISSUE TITLE
Create Prototype Fulcrum App for Signs Work Orders

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#213]

**Comment by johnclary** [comment]
Created three linked apps which comprise the prototype:

[Sign Work Orders[(https://web.fulcrumapp.com/apps/020a51a4-08b4-4d6d-a8b3-)a8e658e71171 (End-user app)

[Sign Locations](https://web.fulcrumapp.com/apps/07edb394-a590-452e-85c6-c63d09c91de8) (linked within Sign Work Orders; many locations to one work order)

[Sign Assets](https://web.fulcrumapp.com/apps/7c10cf6c-9ed4-4381-854f-38cf7e71e36d)
(linked within Sign Locations; many assets to one location)

**Comment by sergiogcx** [comment]
This is huge help, I will be duplicating those apps (without data).  Then pull data from knack into them from knack, currently mapping fields in python. Will report later today or tomorrow.

**Comment by johnclary** [comment]
Great. Happy to help sort out field mapping. Just let me know.
