### ISSUE TITLE
Schedule UAT for Traffic Impact Analysis fees in AMANDA

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2130]
ATD should be getting flat fees for all submission - subdivisions, site plans, and zoning cases.

George S at CTM reached out to me regarding UAT for this issue. 

This will be with DSD users since they are the ones adding fees.

**Comment by amenity** [comment]
@johnclary - Surbhi has scheduled two UATs, but DSD is too occupied to get to it at the moment.

**Comment by amenity** [comment]
This is a big problem; stalling other things that TIA needs. Needs to be done by Roderick but they are very busy... Not sure who else could do. Sangeeta is concerned since there is a lot of money ATD is not collecting right now.

**Comment by amenity** [comment]
@SurbhiBakshi - can you add documentation to this?

**Comment by amenity** [comment]
@johnclary - please follow up with Teri on this.

**Comment by johnclary** [comment]
Sent to Teri today:

> Hoping you can help us with an issue we're blocked on. We have some AMANDA work that needs UAT, it's related to the collection of traffic impact analysis fees (TIA) from zoning cases.
> 
> Because it's a DSD folder(s), Surbhi has tried to schedule time to discuss some DSD folks for UAT testing, but it sounds like they're very busy and have been unable to commit time. The specific person that we believe to be capable of testing is named Roderick, but we're not sure if there may be other DSD staff who could help with the UAT.
> 
> To be honest I'm not entirely clear on what the UAT entails, or if we could leverage external help (LIT) for this. Don't want to ask something of your group if we can manage ourselves, but we could use your/DSD's feedback on this issue.
> 
> Thanks and let us know what other info we can provide!
> John
>

**Comment by johnclary** [comment]
@SurbhiBakshi can you get some more detail from Sangeeta about what the impact is if this is delayed? Do you  know if the fees eventually be able to be collected? Any idea how many cases we're missing/what the loss in revenue is? I need to discuss with Peggy.

**Comment by SurbhiBakshi** [comment]
@johnclary yes, doing so

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5e6ef170-c15b-421a-aeef-4ea327829fbc)

**Comment by johnclary** [comment]
@SurbhiBakshi please add notes and close.

**Comment by SurbhiBakshi** [comment]
Documented in #2292, #2293, #2294
