### ISSUE TITLE
Follow up on CTM request for LC folder online payments

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2131]
Paloma has a CTM Service Request in for this: REQ 0040077 - submitted 3/17/20
Follow up with George at CTM.

**Comment by SurbhiBakshi** [comment]
@johnclary , @amenity  - CTM Service Request is currently in Work in Progress. Amanda Support Team.

**Comment by SurbhiBakshi** [comment]
Email from Paloma -


The ticket has been closed (see attached) as of earlier this afternoon.  Swapna T was working the request.  She and I last communicated on Thursday.  The last of those exchanges is attached.

 

My guess is that the function is now working so I will advise my team to let our customers know.  We’ll see how it goes!
