### ISSUE TITLE
Work with Lewis to do upcoming round of VZA assignments

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2135]
Current assignments end on 3/29
- [ ] Export CSV of current round (Remove Location data?)
- [ ] Import next round
- [ ] Work with Lewis to make sure he is good to go updating schedule.

**Comment by SurbhiBakshi** [comment]
Wrote to Lewis, he is OOO and will be back next week.

**Comment by amenity** [comment]
Going to put in assignments without locations.

**Comment by SurbhiBakshi** [comment]
Assignments are on hold right now as per Lewis.

**Comment by amenity** [comment]
@SurbhiBakshi - I think this ended up being a dupe of #2680 - correct?

**Comment by SurbhiBakshi** [comment]
Guess this was the March one, and we didn't have to do this in March. Going to close this issue.
