### ISSUE TITLE
Add "Add Signal Cabinet" form to Data Tracker

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2136]
[UPS tracking fields have now been added](https://github.com/cityofaustin/atd-data-tech/issues/2082), but there is no form to add a new cabinet. 

"Add Signal Cabinet"

**Comment by dianamartin** [comment]
Comment from #2082  
>I created an `Add Cabinet` form to that page. I did a little rearranging of the fields so that the Details, `Edit` Form and `Add` Forms were consistent.
