### ISSUE TITLE
Meet with LIT, new BSA and Stakeholders

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2138]
### Objective 
Consensus and clarity about the AMANDA Backlog — priority, level of effort, logical "release" bundles 

### Participants
DTS: Nate, Surbhi, Tracy, Amenity, John 
ROW: Paloma, Ryan, Kim P.(?)
LIT: Raj

- Assign level of effort to backlog items
- Determine what order/groups make sense fo delivery

**Comment by amenity** [comment]
Assume this is going to be a series of work sessions.

**Comment by SurbhiBakshi** [comment]
@johnclary @amenity - I think we need to loop in the TIA group as well. The last two cards on the Trello Board are for the TIA team, and there are a couple of more issues in the backlog.  A separate shorter meeting or include them with ROW? I prefer the first. Anyone else?

**Comment by amenity** [comment]
Now covered by other issues including #2353 #2355 #2356
