### ISSUE TITLE
Update Teams pages in wiki

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2139]
Update [Microsoft Teams page](https://atd-dts.gitbook.io/atd-staff-resources/o365/teams) in ATD Staff Resources Wiki as needed.
 
Potential items to include: 
- Check if you have E5 access, Use Skype if not, you can still join Teams meetings, just not organize, talk to your manager if you need a license upgrade 

Creating a Team
- What it means, when it makes sense and when it doesn't
- DTS guidelines on when/how to create/request a Team (Service Request?)
- Alternatives to "a Team"
    - Group Chat
    - Private channel

**Comment by dianamartin** [comment]
- [x] Added info about how to determine if you have E5/G5 license
- [x] Difference between teams (channel) and group chat
