### ISSUE TITLE
Fulcrum Signs Work Order Discovery

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#214]
Evaluate Fulcrum mobile app for use with signs work orders.

**Comment by johnclary** [comment]
have decided to push on with the custom map interface that mateo and mike started, and we'll table fulcrum for now. after running tests in fulcrum on android, it's fine, but not great. not enough to warrant a mad dash to implement it, when we haven't event tested the prototype with end-users...we can revisit mobile solution down the road and ideally solve with knack-react.

@sergiogcx would you add a link to your slide deck here?

**Comment by sergiogcx** [comment]
Definitely, this is the report on the discovery process:

https://docs.google.com/presentation/d/15h9NxTDyy22livoE9tg4CgnISa90ZvUxsFFjtbVOfSA/edit?usp=sharing

(Taken from issue #140, since it might be related)
