### ISSUE TITLE
VZE | Locations columns business rules

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2140]
**Location columns business rules ( which are all counts/summed values):**

- [x] Should be based on the past 5 years
- [x] Should represent CR3s & non-CR3 values summed
- [x] Should use CRIS for death counts

**Comment by mateoclarke** [comment]
@JaceDeloney I've updated the business rules to include non-CR3 values to be summed for Comp. Cost.
