### ISSUE TITLE
VZE | Exclude Locations outside of CoA

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2146]
The Table View that populates the sums on the Locations index page does not check if the crashes were inside the CoA when summing values, but the query on the Details page does. 

After talking to Frank and Mateo, locations outside of CoA were unintentionally included in the locations polygon layer. We need to:

- Make the Table View that sums values exclude crashes outside CoA
- Hide Locations outside CoA

**Comment by mateoclarke** [comment]
Closed with https://github.com/cityofaustin/atd-vz-data/pull/726
