### ISSUE TITLE
HDMI + USB-C Adapter for Allandale Conf Room

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#215]

**Comment by johnclary** [comment]
Reached out to Scott today.

**Comment by johnclary** [comment]
Will add to staples order.

**Comment by johnclary** [comment]
Sent Staples order to David this AM.

**Comment by johnclary** [comment]
And the adapter we bought didn't work. Submitted a PR for a new adapter.
https://atd.knack.com/finance-purchasing#reviews/purchase-request-details/5d2d2b05dee15600106e7eed/

**Comment by johnclary** [comment]
Adapter will arrive tomorrow :)

**Comment by johnclary** [comment]
Received and installed.

**Comment by johnclary** [comment]
adapter is not working. need to test :(

**Comment by johnclary** [comment]
Scott is ordering a new. PR submitted. https://atd.knack.com/finance-purchasing#purchase-requests/purchase-request-details/5d497401860a9e00113f9588/

**Comment by johnclary** [comment]
Ordered and arriving tomorrow.

**Comment by amenity** [comment]
@johnclary - update on this?

**Comment by johnclary** [comment]
Turns out the issue is with the projector. I'm closing this and opening a new issue to get a new projector for Allandale.
