### ISSUE TITLE
Create COVID-19 Spend Report (Rptg Code 1012)

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2151]
Dan V. needs a report of all purchase requests that are using reporting code 1012. Work with Dan to get the exact requirements.

**Comment by johnclary** [comment]
@dianamartin please reach out to Dan on Monday (3/23). They need this set up right away.

FYI @amenity

**Comment by dianamartin** [comment]
I added the `Report Code` to the `Advanced Search` page and also added it to the search results table. I messaged Dan to have him review and he said that would work for them.
