### ISSUE TITLE
Remove Type from time submittal form

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2168]
As a manager, I do not want employees to have to choose between Regular hours and Overtime hours when submitting their time into the COVID-19 Time Tracking app. This information will be calculated by comparing time submitted in this app to the employees' timesheets.

Acceptance criteria:
`Type` is no longer displayed in the COVID-19 Time Log form

![Screen Shot 2020-03-25 at 8.40.22 AM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/0183479c-2cc7-49d1-bbaa-28ba271896e0)

**Comment by dianamartin** [comment]
I removed `Type` from the form. It's still there in the back-end.
