### ISSUE TITLE
Screenshots of demo apps

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#217]
- [x] Kits functionality on Wasp
- [x] Wasp

**Comment by dianamartin** [comment]
created document with the WASP screen shots.
[WASP_Screenshots.docx](https://github.com/cityofaustin/atd-data-tech/files/3298388/WASP_Screenshots.docx)

**Comment by amenity** [comment]
Moved these into the project folder along with higher res screen captures: https://drive.google.com/open?id=1Xo5evHZoz957akMYM5zVEZDY4Rhe2NDJ
