### ISSUE TITLE
Add big login buttons 

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2179]
Add the custom CSS for the Knack big login button. 

![Screen Shot 2020-03-25 at 4.59.52 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/e83c84f4-bb03-4903-81f7-065315506e5c)

**Comment by johnclary** [comment]
@dianamartin plz test and close :)

![Screen Shot 2020-03-26 at 9.25.27 AM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/547cac88-9025-4c41-95c5-9d8606788843)

**Comment by dianamartin** [comment]
@johnclary I tested log in page, it gives me same error. It's working when i right click on button and open in new tab.

**Comment by dianamartin** [comment]
Talking to Jaime about it to see what her log-in experience was.

**Comment by dianamartin** [comment]
So I talked to Jaime and she got the error too, but then she refreshed and then it logged her in. She said he got the error another time, it sounds intermittent. I've now been able to log in after i got the error once and now i'm logging in fine..

Update: I'm got the error again.

**Comment by dianamartin** [comment]
Big button is on the application and working for most, but there are still Chrome log in errors.
