### ISSUE TITLE
Adhere COVID-19 Time Tracking export to HSEM template

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2180]
Modify the export of COVID-19 time tracking logs to adhere to the HSEM template. @dianamartin already modified the export. @johnclary and I will review the current state with @dianamartin and determine any changes.

**Comment by dianamartin** [comment]
The the COVID-19 tracker we have a HSEM export page that matches the original spreadsheet

![Uploading image.png…]()
