### ISSUE TITLE
Explore child records to limit/clarify maximum slots for Assignments

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2183]

**Comment by SurbhiBakshi** [comment]
- created Test copy - 17 April | TEST| Vision Zero in Action
- documented in DTS Inventory

**Comment by SurbhiBakshi** [comment]
Lewis prefers to schedule assignments through the Calendar Interface. However there is no Form Rule functionality in the Calendar Event Form to create child records. 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/cb192284-baa3-4bb9-9eb1-34a29232b530)

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/8dc9be80-70da-437f-b5be-c2c03839caa3)

**Comment by SurbhiBakshi** [comment]
- [ ] Will a change in location/ team/ assignment time be reflected in the child records?
- [ ] Check if a form linked to the Assignments Details within the calendar could help with creating child records?
- [ ] Check if a batch of assignments copied over to the calendar, with LL having to only change assignment location/ time/ number of required officers without having to create new assignments would help in creating child records. 
- [ ] Self assignment for officers on Officers page reflected accurately in My Assignments page?

**Comment by SurbhiBakshi** [comment]
Notes - 

- [ ] Create an issue to copy assignments in monthly batches. Assign to John.

- [ ] Include a field in the Assignments (Officer interface) with either badge number or officer name to show that officers signed up for that assignment.

- [ ] For school closures in AISD, create a field in the Locations object to show if school closure is in the current year. Calculate that field once a year, and then filter out the location drop down based on that.
