### ISSUE TITLE
Manage call forwarding for ATD staff

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2185]

**Comment by dianamartin** [comment]
Reviewed Ashley's spreadsheet of our ATD request. 284 records! I updated the SharePoint spreadsheet we had and updated everyone's status. 

Drafted email to let users know how to access their call forwarding. Was going to send it to Austin Transportation Employees, but I'd like someone to review it before I send it out. 

@amenity @johnclary: any volunteers? I wanted to send it out 3/25, but i'll wait til the morning.

**Comment by dianamartin** [comment]
@johnclary Did you get a chance to send out to managers/supervisors yet? I've had a couple of people ask if they can enable call forwarding remotely. So I just emailed them the instructions that CTM gave me.

**Comment by johnclary** [comment]
@dianamartin plz update and close
