### ISSUE TITLE
Help Section

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2187]
Create step-by-step instructions on how to use the COVID-19 Time Tracking App. We need separate instructions for employees and managers.

**Comment by JaceDeloney** [comment]
@dianamartin created a help tab: https://atd.knack.com/hr#help/

Help Guide
Time Log Entry
1. Navigate to Home page

2. Select Name from the drop down list and fill out fields:

Task
Work Description
Work Date - set to current date
Start Time - set to default at 8 am (can be changed)
End Time - set to default at 4:30 pm (can be changed)
3. Click Add Time Log
4. Review submitted time logs table below Add Time Log form (Can click edit button and edit record before status is changed to Approved - Yes)

Approving Time Logs
1. Navigate to Home page

2. Click on COVID-19 Log page

3. Click Add filters

4. Select Supervisor

5. Select your Name on the drop down field

6. Click Submit to search for your employee time logs

7. Click Approve after reviewing time log entry (Can click edit button to edit record before status is Approved - Yes)

8. Time Log entry will be moved to the Approved | COVID-19 Time Logs table below Needs Approval | COVID-19 Time Log

**Comment by dianamartin** [comment]
Once we finalized what the information we wanted to include on our `Help` page we considered adding the Teams meeting recording. I felt like there was to much lag and the meeting wasn't clear for other users on how to do things. 

I created step-by-step videos in Loom and linked them to the help [guide](https://atd.knack.com/hr#help/).
