### ISSUE TITLE
Ability to Revoke Approvals

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2193]
If an approver approves a time log on accident, they have no way to revoke approval. To revoke an approved time log, the approver would need to submit a support ticket to DTS.

As an approver, I want the ability to revoke approval if a report has not been sent to HSEM.

**Comment by dianamartin** [comment]
@JaceDeloney We don't know when the HSEM export goes out or is submitted. I could have the ability for approvers to edit the record or revert the status back to `Needs Approval`, but that stipulation of before the HSEM report has been submitted is not nailed down.

**Comment by amenity** [comment]
Will need more clarity on this before we work on it. @JaceDeloney - have you heard this requested by any users yet?

**Comment by JaceDeloney** [comment]
I was told by @johnclary that this was a requirement. I assume this came in as a request from managers and timekeepers.

**Comment by amenity** [comment]
@johnclary - what are your thoughts here?

**Comment by johnclary** [comment]
Closing. The feature has not been requested by our users.
