### ISSUE TITLE
VZD vs MicroStrategy Records Q/A 

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#2194]
### Action Items from 2020-03-26 meting:

- Reinsert all time data for following tables:

  - [x] person
  - [x] primary person
  - [x] charges
  - [x] units

- [x] Update ETLs for these tables to process all edits from CRIS (if necessary) 

- Xavier to investigate discrepancies for Nov 16 and March 18 and share details

**Comment by sergiogcx** [comment]
Backups for the production and staging database have been created, and the tables have been truncated. The ETL's have also been temporarily stopped to help the Hasura servers have less load.

**Comment by sergiogcx** [comment]
The above data is being inserted as we speak, please do not touch process id `4642.pts-0.atd-data02` in the following days.

**Comment by sergiogcx** [comment]
Note to self:

In Hasura unique indexes and unique constraints behave the same, but constraints are more performant:
https://medium.com/flatiron-engineering/uniqueness-in-postgresql-constraints-versus-indexes-4cf957a472fd

**Comment by sergiogcx** [comment]
Pull request created:
https://github.com/cityofaustin/atd-vz-data/pull/723

**Comment by sergiogcx** [comment]
The data has been inserted, the rest of the ETL modifications will be taken care of #1959
