### ISSUE TITLE
Follow up on outstanding customer request for DSD

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2195]
Per [long email thread](https://github.com/cityofaustin/atd-data-tech/files/4390395/TIA-Fees-Email.pdf), a developer is confused by not being able to pay TIA fees online.

**Comment by amenity** [comment]
This is a long confusing mess. Slack convo w/ @SurbhiBakshi 

> [Amenity Applewhite][1 hour ago]
> K, got another email from Johna asking about this. I'm finding lots of info in Trello/Lit, but it's kinda contradictory:
> 
> 
> [Amenity Applewhite][1 hour ago]
> **Scenario 1:**\
> [TIA Fees Payable Online](https://trello.com/c/pNmgfhfF) is a feature request at the bottom of the LIT backlog, which is itself blocked by another backlog feature, [Create TIA Mitigation Fees](https://trello.com/c/0doAvXdE)The response I had written to Johna:\
> *The ability to pay TIA fees online is a feature request currently in the backlog of a vendor DSD and ATD is currently engaged with, Launch IT.*  (edited) 
> 
> 
> [Amenity Applewhite] [1 hour ago]
> **Scenario 2:**\
> This is what we were talking about [here](https://github.com/cityofaustin/atd-data-tech/issues/2130) yesterday. The work has been completed but is in UAT. Teri promises someone can do that tomorrow or Monday. (edited) 
>
>
> [Amenity Applewhite]  [1 hour ago]
> Haven't written a response yet, but basically would say that it should be ready in [____] days/weeks and that [_____} will follow up with the customer and/or DSD.
> 
> [Surbhi Bakshi][35 minutes ago]
> I reached the same conclusion, but was waiting for Sangeeta to confirm that.
>
>
> [Surbhi Bakshi][34 minutes ago]
> Don't think the fees can be paid online yet, have to be paid in person at OTC, but the fact that Roderick directed this to Johna confuses me. I would have thought he would know.
> 
> 
> [Amenity Applewhite] [20 minutes ago]
> Exactly - isn't he the one you've been emailing?
> 
> 
> [Surbhi Bakshi]  [16 minutes ago]
> exactly, wrote to Sangeeta today morning, hoping she can confirm before tomorrow morning so I can reply to the customers.

**Comment by SurbhiBakshi** [comment]
Email from Sangeeta - All,

I will contact the applicant directly and figure out the issues.  Thanks
