### ISSUE TITLE
Speed Management (LATM) Update to GISMAINT / GISDM

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#2196]
Mario is working on updating the LATM layer in GISDM. I sent him a table export of the GISDM version. I also created a AGOL feature layer for him / interns to edit to create a current layer. He has requested to change some of the schema during this process.

Saving this Issue to my Backlog until I receive new data from Mario.

Let Veena P. at PW know when the data has been updated on GISDM

**Comment by jaime-mckeown** [comment]
Max and I spoke about this last week. He is taking over this project from Mario. I forwarded him the original spreadsheet that I had sent to Mario, and got him setup in GIS so he can access the geospatial data as well.

**Comment by jaime-mckeown** [comment]
@andrewshensky I'm passing this request on to you. Please let Max know to work directly with you as they move forward with the data update. After they get the data updated, we will need to come up with a process to keep this data current.

**Comment by andrewshensky** [comment]
I met with Max today and was able to push their attribute updates to Maint. There were a few new records added during their clean up process. Max will be adding those new records directly to Maint.

Future meeting will be set to discuss maintenance of this data and integration into ROWPACT.
