### ISSUE TITLE
[ETL] Update CR3 PDFs for a crash when a record updates

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#2201]
Right now we're only saving the raw PDF CR3 on crash record **creation**. 

When a record updates from CRIS (via ETL) or by the user (via the Conflict Management UI), we need to fetch a new PDF.

--- 

From @sergiogcx:

Any changes done by the ETL will include the "System" value in the updated_by  column. We can safely make the trigger assume:

```SQL
IF new.updated_by = "System" THEN
   new.cr3_stored_flag = 'N'
END
```

![2020-03-26_17-21-21](https://user-images.githubusercontent.com/5697474/77801788-884da400-7047-11ea-8636-31559b6cf302.png)

**Comment by sergiogcx** [comment]
Picking this up for tomorrow Friday 10th, the tasks involve:
- [ ] Change the ETL process so that it inserts the new.cr3_stored_flag = 'N'
- [ ] Change the trigger and add a few lines like this:

```
IF NEW.cr3_stored_flag != 'N' AND new.updated_by = "System" THEN
   new.cr3_stored_flag = 'N'
END
```

Basically, the logic is: If the stored flag is not Yes and it was updated by System, then change flag to N.

**Comment by sergiogcx** [comment]
In terms of testing:
1. I will be running the ETL process repeatedly to purposely update the cr3_stored_flag to N
2. Test the trigger logic (in staging) and find ways it could fail.

**Comment by sergiogcx** [comment]
For now the SQL trigger idea seems to be a bit of an overkill, one in the sense that any changes done in the UI do not mean that the CR3 has been updated, and secondly in the fact that the only time we really know the CR3 is updated is whenever a CRIS record comes through and it is an existing crash record.

Given these conditions, I think it is best to signal the change using Python code in the ETL.

There is a PR: https://github.com/cityofaustin/atd-vz-data/pull/741
