### ISSUE TITLE
Update Spin Configuration

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#2203]
The endpoint for spin has changed, the new endpoint for MDS is `https://mds.spin.pm` the old one `https://web.spin.pm` will be discontinued soon.

To Do:
- [x] Test new MDS endpoint with v0.2
- [x] Test new MDS endpoint with v0.3

Update configuration and upload to S3

**Comment by sergiogcx** [comment]
@JaceDeloney I can't get a token out of spin using the new host name.

This works (the old host name):
`https://web.spin.pm/api/v1/auth_tokens`

This does not:
`https://mds.spin.pm/api/v1/auth_tokens`

Once I do get a token (from the old endpoint), then the new endpoint works. 

From what endpoint are we to get the token from?

**Comment by JaceDeloney** [comment]
I followed up with them. Awaiting a response.

**Comment by sergiogcx** [comment]
From response:

> Please note that currently you must still request your authentication token from the old web.spin.pm address. > Use web.spin.pm to obtain the authentication and then use that token to access MDS.


This confirms that we are going to use both endpoints, one for authentication (web.spin.pm) and another as the mds endpoint (mds.spin.pm).

**Comment by sergiogcx** [comment]
Configuration updated
