### ISSUE TITLE
TURP Payment online issue

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2204]
Please bring this to the attention of the Amanda group.  

I am temporarily filling in for Tracy Linder, the Amanda SPOC for Austin Transportation who is on medical leave. 

Please copy John Carr on related communication. John, please correct me if I have missed any of the details. 

Issue - 

Matthew Doughty of Cadence McShane is facing issues with pay for a TURP online.

The payment screen shows “Online payment being processed” but they have not tried to previously make the online payment.

They started to try and pay this late last Friday afternoon a couple times.

Their office also tried this morning before contacting John Carr. 

Please look at the image below to see details for this payment.

thanks,

**Comment by SurbhiBakshi** [comment]
INC0033926

**Comment by johnclary** [comment]
User was locked out when using portal. This has been resolved per Surbhi.

**Comment by SurbhiBakshi** [comment]
as per Swapna T - In general we get ‘online payment being processed’ error message is, when user try to initiate the payment and not complete the transaction and if he comes back again and try to pay it, we will lock the payment for 70 minutes to avoid duplicate payments. May be user  tried before 70minutes to pay it again, that’s why he saw that error message.
