### ISSUE TITLE
Discuss Intake and Level I Support

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2218]
### Agenda 
_[Google Doc](https://docs.google.com/document/d/1-6IhtCMfOoACwAANIiMnlLosBlHBl_R2Lqh6y3h4hKM/edit#heading=h.9y2xzfo6m7nc)_
- Service Request intake & triage
- End-to-end Level I support workflow
- Coordination with CTM Help Desk
- Roles & responsibilities (e.g. who is involved, shift rotation, etc.)

### Participants
John, Surbhi, Amenity, Diana

------
- [x] Schedule meeting
- [x] Meet and take notes
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
Related to #2161

**Comment by dianamartin** [comment]
@SurbhiBakshi @johnclary we need to create GitHub issues for our action items we tasked ourselves yesterday.

**Comment by SurbhiBakshi** [comment]
@johnclary , @dianamartin  - #2280
