### ISSUE TITLE
Update Lamppost Banner Mxds / PDFs

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#2221]
- An update was requested for the Convention Center District Map. When I started looking closely at the data, I realized that many of the maps were still connected to the old FGDB instead of GISDM for the data.
- There is no correlation between the PDF maps and the Web Maps (i.e. only showing only the Active locations).

- Will fix all Mxd data connections and create FGDB Annotation for the banner support Pole labels so the visibility can be controlled through a definition query, making it much easier to maintain in the future (Active, Inactive).
- Only Active banner supports will be visible on all the Mxds / PDFs.

- After all the PDFs have been verified by Lauren, I will then update the Web Maps to make sure they are only showing the Active banner supports as well.
- Update the Web App to make sure all the text is correct for each District.

**Comment by jaime-mckeown** [comment]
- Created Lamppost_Banner_Anno GDB for all new annotation.
- Updated Barton Springs Rd Mxd data connections, created new banner support annotation.

**Comment by jaime-mckeown** [comment]
- Verified with Lauren that the Pole #s should match the AE Pole layer. There are many poles that have updated numbers or have been removed.
- Edited the banner support layer in MAINT today going through each district and updating the pole numbers and changing the status to removed for poles that don't exist in the AE Pole layer anymore. Pushed updates to GISDM.

**Comment by jaime-mckeown** [comment]
Finally finished updating all the Mxds / PDFs
- All data connections for banner data have been updated to GISDM
- Broken data has been removed 
- All lamppost support Anno has been created, a new field added Banner Status so anno doesn't have to be deleted when supports are Inactive
- All lamppost supports are now only showing active banners, inactive are filtered out
- Need to create a single PDF to send to Lauren for her to look over

**Comment by jaime-mckeown** [comment]
- Forgot about the Cesar Chavez District, updated Mxd and PDF
- Updated All Lamppost Map and created new PDF
- Created merged PDF of all districts with the overall map and sent to Lauren.

**Comment by johnclary** [comment]
@jaime-mckeown plz create new issue for app updates.

**Comment by jaime-mckeown** [comment]
Yesterday, I created new Web Maps for all current maps in AGOL and configured to must current data.
Will create new Issue for working on Web App and last MAINT edits.
