### ISSUE TITLE
Update Vision Zero Logo on VZV

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2228]
Previously we used the official Vision Zero logo and colors for the header. After looking at the Vision Zero yard sign page, we (@amenity) realized that the colors used on the Vision Zero yard signs look better. The colors on the yard signs are brighter and pop more. 

I need someone to look on the G Drive for a file that we can use. I don't have access. The location of VZ files on the G Drive is G:\ATD\ACTIVE TRANS\Vision Zero\Graphics

**Previous file:**
![download.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/1de03f35-a683-4f8f-9a01-9925781d2f5a)

**New file (this is a screenshot, need actual svg or png file):**
![Screen Shot 2020-03-31 at 7.39.04 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/55cd3dbf-3ea7-4532-bf55-c551278fcaa8)

**Comment by amenity** [comment]
I can access the G Drive... Unfortunately there aren't any .svgs. One might be able to extract a vector logo out of the .psd files but my Creative Cloud license has expired. @tylerwhitson - does anyone in PIO have Photoshop? If not, we could at least get a higher resolution image of the current logo.

**Comment by tylerwhitson** [comment]
@amenity @JaceDeloney I've reached out to our graphic designer for a vector or high-res file of this image. She should be able to obtain it - I'll send it over to y'all once I received it.

**Comment by amenity** [comment]
Regrouping on this since Lewis wants to keep the OG palette and preserve the tagline. @tylerwhitson, can you get us a vector (svg) version of this one? 
![download.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/1de03f35-a683-4f8f-9a01-9925781d2f5a)

We can always

**Comment by tylerwhitson** [comment]
This is complete. Closing this issue.
