### ISSUE TITLE
Markings time table for work performed

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#2231]
Create a related table per markings asset to track work performed over time, instead of merely updated the `INSTALL_DATE` field.
The proposed schema is as follows:

### Sample Table ###
| Field | Values | Description |
| --------------------- | ----------------- | ------------------------------- |
| x_MARKING_ID | 123456 | Relate will be based on this field |
| WORK_DATE | mm/dd/yyyy | date field to be edited instead of `Install Date` |
| WORK_PERFORMED | Installed, Maintained, Removed | Type of work performed |

**Comment by johnclary** [comment]
Dupe
