### ISSUE TITLE
Test Barcode Reader w/ Knack

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#225]
Test whether or not a barcode reader when it scans a barcode entered into a field if Knack will search for the entry.

**Comment by dianamartin** [comment]
Tested this with Dell laptop and the Adesso scanner (connected by USB). Opened up Knack in TEST and created a new AMD Work Order. The barcode was entered into the "signal" field and it looked up the connected signal records. It works! :fireworks: 

John said he'd continue testing the other scanner that is (connected by blue tooth)

**Comment by johnclary** [comment]
Diana showed me how the barcode reader works with Knack. It works as expected. Yay.
