### ISSUE TITLE
Hardware, Accounts, etc.

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2250]
### Accounts

- [x] Employee Transfer form _submitted 4/6_
@johnclary Has this been filled out already?
- [x] Network account request
- [ ] Phone request - _Will set up with Avaya oneX Communicator, once we set-up a phone extension..._
- [x] 1Password _sent invite_
- [x] Slack - _John set-up_
- [x] Google Drive _shared with work email, needs to create an account first_
- [x] Github Team _had one with CTM. Had to create a new one_
- [x] DTS Email Group _created ticket ` CALL0029441` to add Nate_
- [x] LIT Trello

### Software

- [x] Zenhub Extension
- [x] Docking station driver
- [ ] PL-SQL - note that @SurbhiBakshi has a license she's not using frequently right now that can be transferred if necessary

### Hardware

- [ ] Desk/Office Space - _next to Surbhi/Diana's desk, open desk island_
- [x] Computer - _Meeting Scott at 1:30 pm, 4/6_
- [x] (1) Monitor - _Meeting Scott at 1:30 pm, 4/6_
- [x] Docking station - __Meeting Scott at 1:30 pm, 4/6_
- [ ] Chair
@johnclary what are we doing for chair options? that warehouse again?
- [x] Power supply - _Meeting Scott at 1:30 pm, 4/6_
- [ ] Keyboard
- [ ] Mouse
- [ ] Badge - _emailed David M about it. He wants to wait until we return to the office to configure it_

### Meetings

- [x] Introduction to DTS
- [x] Service Delivery Training

### Communications

- [ ] newsletter announcement
- [ ] email to Cameron Rd employees

**Comment by johnclary** [comment]
@dianamartin would you take the lead on software/accounts and hardware?

@amenity including here so you can track when we have accounts setup.

**Comment by johnclary** [comment]
@SurbhiBakshi would you work with Nate and LIT to get his Trello username added to their Trello board?

**Comment by SurbhiBakshi** [comment]
@johnclary added Nate to the LIT-ATD Trello board.

**Comment by amenity** [comment]
@Nadin-Nader @johnclary @TracyLinder Sticking the rest of these in #2499
