### ISSUE TITLE
ROW AMANDA Business Process Training

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2252]
In-depth (possibly a series of meetings) screensharing with ROW permit analyst to learn about their processes.
- [x] TIA Folder and Mitigation Fees
- [x] DSD Training
- [x] ROW Basics

**Comment by johnclary** [comment]
@SurbhiBakshi would you schedule time with Nate and Kimberly (ROW) for this? You probably don't need to be present in the training unless you want to be. FYI @dianamartin

**Comment by SurbhiBakshi** [comment]
@johnclary , @dianamartin - scheduled Introduction + Training (first meeting) for April 7th
