### ISSUE TITLE
Get access to Access IPD 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2265]
Having access to the Interim Project Database Access interface will be very informative for #2263. Amenity and JD both need access, Sergio has set up a version for himself on a Windows VM.

**Comment by amenity** [comment]
Confirmed that my Citrix/Cisco combo works fine. 
<img width="1080" alt="Screen Shot 2020-04-28 at 1 04 55 AM" src="https://user-images.githubusercontent.com/1463708/80452713-6e280f80-88ec-11ea-9c05-4e04eab3ccba.png">
@zappfyllc - lmk if you need any help with this.

**Comment by zappfyllc** [comment]
Discussed with Amenity on 5/8; will close this and reopen it if I run into any issues accessing Access
