### ISSUE TITLE
Create related tables to track work dates for Markings

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#2269]
Create tables to track when markings are installed, maintained, or removed. Table to use asset and work order IDs.

**Comment by alan-deanda** [comment]
Tables have been created, existing markings IDs have been loaded
- [ ] Test editing
- [ ] Test compatibility with versioning

**Comment by alan-deanda** [comment]
@johnclary @dianamartin ,

I spoke with Susanne at length on Friday. We've been having issues with our current plan of connecting dates of installation, maintenance, and removal to the asset feature classes in MAINT. The original idea was to create a related table with a one-to-many relationship class that links assets to Work Orders, and this table would relate to the Jobs table. However, due to all the known MAINT issues, this is not really going to be sustainable.

As an alternative, I suggested a change in workflow to the GIS QA process in Knack. We currently have a field where we input the street segment IDs that the markings touch. Would it be possible to add a field to the Jobs table/page in Knack where GIS QA staff enter the markings IDs? This may need to be a separate table with a one to many from jobs to assets, but it might be a better solution than the one we've been pursuing. 

Should I close this issue out and open a new one to look at alternate solutions? I'm happy to go into more details with the request and issues via email, or a meeting/whatever else is more convenient. 

Thanks!

**Comment by dianamartin** [comment]
@alan-deanda @johnclary I think we definitely need to talk more about this and what you and Susanne would like to do so we can help you determine a solution. This is the first time I've heard about this so I think setting up some time to talk would be best. Check our calendars and we can discuss in detail.
