### ISSUE TITLE
Time of day color updates

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2275]
Tyler had a good idea to change the colors on the time of day chart to match the viridis color palette. Below are the updated colors. The [google doc](https://docs.google.com/document/d/1Oi6RcAa4-Z47u7CQkasSZc_ufU1GDxItIqlkqDHJVz8/edit?usp=sharing) has also been updated.

![Vision Zero Viewer_ Web (1).png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/8a577f5e-b0ab-4800-8b25-8624c6aa2085)

.color-1 {
    color:#f3f4ff;
}
.color-2 {
    color:#c6c8e1;
}
.color-3 {
    color:#9a9cc2;
}
.color-4 {
    color:#6d6fa4;
}
.color-5 {
    color:#404385;
}
.color-6 {
    color:#2a788d;
}
.color-7 {
    color:#26a785;
}
.color-8 {
    color:#7bd15a;
}
.color-9 {
    color:#fde740;
}
.color-10 {
    color:#fe9f3e;
}
.color-11 {
    color:#ff343b;
}
.color-12 {
    color:#2aa0c9;
}
.color-13 {
    color:#febc3f;
}
.color-14 {
    color:#37af7c;
}
.color-15 {
    color:#fe671a;
}
.color-16 {
    color:#459f94;
}

**Comment by tylerwhitson** [comment]
Thanks, @JaceDeloney! I have to credit Arielle for the idea, though :)
