### ISSUE TITLE
Give applicants ability to pay Transportation Mitigation Fees in ABC Portal

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2277]
Upal and Sangeeta from the ATD TIA group would like to make TIA Mitigation Fees payable online. 

These fees are paid after a TIA Review is completed and in lieu of TIA mitigations. The amounts can be from $500,000 to $1,000,000. These used to be paid in person by check at Barton Oaks and went to ATD directly. Enabling these fees to be paid online would prevent applicants from going to pay these fees at Barton Oaks in person.

Right now fees above $100,000 cannot be paid online through Portal.

**Comment by SurbhiBakshi** [comment]
Reached out to Dan V to ask about an EFT account. He directed me to Rose M at DSD. Meredith Q answered my email - We do take payments for fiscal through wire transfers, but it’s a City process, not a DSD process, so please talk to Gail R in the Treasury Office if you would like to do wire or ACH transfers.

Have asked Dan to reach out to Gail

**Comment by SurbhiBakshi** [comment]
- [ ] Need to check with Dan or contact someone else at Finance.

**Comment by SurbhiBakshi** [comment]
- [ ] in person 
 - [ ] in person at Toomey
- [ ] mail in check

applicants have trouble getting checks, 

issue invoice in Amanda , put fund code, so money can be mapped, in SP folder, but with TIA mitigation fund code. 

bank transfers can be used instead for an EFT, which would be possible because the fee is coming from SP (owned by DSD), which has this set up. ATD Review Fee - create mitigation fee code, 
already attached to SP

**Comment by TracyLinder** [comment]
**Status:** Sree to begin working on this during sprint 30.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - #1729 Testing in TEST environment is in progress, Upon successful test will begin to work on this.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan I just did a sucessful test of paying mitigation fee on TIA folder. I'll do ZC next. 

![image](https://user-images.githubusercontent.com/49930868/89690630-956b8100-d8cc-11ea-9495-ddb16e7bffef.png)

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan I was able to pay mitigation fee online for ZC.

![image](https://user-images.githubusercontent.com/49930868/89691078-aa94df80-d8cd-11ea-943b-c9601b5714c5.png)

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder  - Thank you so much :-)

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Completed, Tested and given Demo. Ready for Users UAT.

**Comment by TracyLinder** [comment]
### Approved to promote to Prod! 🎉

@Sreelatha-BlazeKannan

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - PROD Deployment request submitted on 08/17/2020

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  @TracyLinder  The DevOps Deployment TASK is SCTASK0090582. The Deployment for the LookUp is going to CTM Tango as it is a LookUp on PROD and i cant add it to PROD. I have submitted the task for this and it is SCTASK0090583.

**Comment by TracyLinder** [comment]
### This is in PROD ✨🎉
- SCTASK0090582 was promoted on 8/18
- SCTASK0090583 was promoted on 9/3

I will inform Sangeeta; I'm also going to schedule time with her to do a smoke test of these features in PROD. Closing this ticket.
