### ISSUE TITLE
Draft Level 1 Support Rotation Schedule

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2278]

**Comment by dianamartin** [comment]
@johnclary Added all DTS members to the `ATD DTS Knowledge Base` MS group that has the shared calendar

**Comment by amenity** [comment]
This is in progress, @johnclary is following up on it with Peggy.

**Comment by johnclary** [comment]
ok, we've got approval. bumped to sprint 25!

**Comment by johnclary** [comment]
@dianamartin would you go ahead and do this on the shared outlook calendar you made? here's the order:

- nate (alternate: Diana)
- alan (alternate: Surbhi)
- jaime (alternate: Diana)
- amenity (alternate: Surbhi)
- jace (alternate: Diana)
- tracy (alternate: Surbhi)
- mike (alternate: Diana)
- mateo (alternate: Surbhi)

That get's us through eight weeks. After that, I would suggest this schedule repeats forever:

- nate (alternate: Alan)
- alan (alternate: nate)
- jaime (alternate: alan)
- amenity (alternate: jaime)
- jace (alternate: amenity)
- tracy (alternate: jace)
- mike (alternate: tracy)
- mateo (alternate: mike)
- diana (alternate: mateo)
- surbhi (alternate: diana)

**Comment by dianamartin** [comment]
Added to the Shared Calendar

**Comment by amenity** [comment]
@johnclary @dianamartin - we can close this, si?

**Comment by dianamartin** [comment]
@amenity I think so, I defer to John

**Comment by johnclary** [comment]
yeah! closed :)
