### ISSUE TITLE
Wiki for Open Data FAQ

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2280]

**Comment by SurbhiBakshi** [comment]
Planning to organize by 

1. Dataset Name
2. Links (other pages which have the information requested)
3. Department  Contact - group in department that manages operations related to dataset
4. Common Questions  (break those into sub categories by grouping questions asked frequently)

**Comment by SurbhiBakshi** [comment]
not sure if we should include contact information (contact email) for Department Contact here. Would be helpful to have that available quickly, but would need to update in case of staff turnover.

**Comment by SurbhiBakshi** [comment]
Dataset Issues - 
- [ ][Traffic Studies: Vehicle Classification Reports:](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Studies-Vehicle-Classification-Reports/2hke-by7g) - does not have field definitions filled out

**Comment by SurbhiBakshi** [comment]
Need to make sure this is still accurate - ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/fc28bdf4-c00e-4179-b258-14fc4e9ece27)

**Comment by SurbhiBakshi** [comment]
Need to make sure this is still accurate - ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/45202b30-1605-4e6d-9fa5-df8a97c4d0f3)

**Comment by amenity** [comment]
@dianamartin please take a look at this

**Comment by dianamartin** [comment]
@SurbhiBakshi Do you think we should include some of the email template responses we send to a user?

**Comment by SurbhiBakshi** [comment]
@dianamartin - Sounds like a good idea to me, do you mean the System wide outage issues? Not sure if the Open Data wiki is the right place, perhaps in the resource guide for the primary responder?

**Comment by SurbhiBakshi** [comment]
@dianamartin  - on a related note, we also need to list who on the team gets forwarded emails based on the subject. Probably need to discuss that.

**Comment by dianamartin** [comment]
@SurbhiBakshi Not the system wide outage email template, the canned responses for Open Data stuff.

**Comment by SurbhiBakshi** [comment]
@dianamartin - So an email template sounds good, but most responses would be a mix and match based on the question asked.

**Comment by dianamartin** [comment]
exactly, so maybe just a snippet of a particular response.

**Comment by amenity** [comment]
Love this idea. Email snippets would be very helpful.

**Comment by SurbhiBakshi** [comment]
Meeting to discuss email snippets -  #2585
