### ISSUE TITLE
Geoprocessing for micromobility O/D monthly usage data

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2284]
The city is conducting analysis to determine how people are getting around central Austin using micromobility. We are going to receive custom neighborhood/district polygons and will need to associate O/D coordinates to them. 

Attributes:
- Month
- Lat
- Long
- Polygon ID
- Anything else?

**Comment by johnclary** [comment]
@alan-deanda let's discuss

**Comment by JaceDeloney** [comment]
@alan-deanda  Attached is the zipped shapefile of the downtown polygons that Nelson Nygaard wants to use. Let me know if you have any questions about how the data is set up.[https://app.zenhub.com/files/140626918/29939506-dd50-4551-a14d-f37bec6d4c25/download](https://app.zenhub.com/files/140626918/29939506-dd50-4551-a14d-f37bec6d4c25/download)
