### ISSUE TITLE
Generate PIR micromobility report

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2289]
### This report needs to be finalized by Friday, April 10
We received a PIR requesting micromobility trip data on a per provider basis.

Create a report that includes the following information for the month of August/2019, September/2019, October/2019, November/2019, December/2019, January/2020 and February/2020:
- Number of Total Rides
- Average Number of Rides per Scooter per day
- Average Number of Scooters per provider per day

**Comment by sergiogcx** [comment]
@JaceDeloney For the total number of rides per provider per day? or monthly? or total for all those months combined?

**Comment by JaceDeloney** [comment]
It should be total number of rides for that specific month.

Clarifying information below. I would create a separate doc or worksheet for each provider.

**Columns would be:**
- Number of Total Rides for that month
- Average Number of Rides per Scooter per day for that month
- Average Number of Scooters per day for that month

**Rows would be:**
- August 2019
- September 2019
- October 2019
- November 2019
- December 2019
- January 2019
- February 2019

**Comment by sergiogcx** [comment]
I've download the historic data from the old RDS instance, and inserted into the new RDS instance in a separate table. I've also managed to modify the table to get the report per provider.

**Comment by sergiogcx** [comment]
Reports submitted, let me know if there is anything else I can do for you @JaceDeloney 

If this works, would you close the issue for me?

Many thanks!
