### ISSUE TITLE
Ensure TIA folders are visible on the ABC Portal. 

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2290]
TIA folder needs to be visible on Portal, as well as the invoice, so the applicant can pay online.

**Comment by SurbhiBakshi** [comment]
Zach W from DSD has put in a request with Amanda support on 3/27.

 Swapna T is working this issue, and has asked for more details. Need to check if she has all the information she needs.

This has been logged as a medium priority issue, might need to escalate this to a higher priority so she can concentrate on this task.

Update after UAT on 04/01/2020 - TIA folder was visible on Production instance of ABC Portal, invoice had correct amount for TIA.

**Comment by amenity** [comment]
Would like to verify that an applicant can confirm this.
