### ISSUE TITLE
Total on review screen is not accurate when individual fees are selected in the ABC Portal

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2291]
Applicants should be able to select separate ATD Review fees on ABC Portal.

ATD Review fees are getting bundled with other fees, the sum can be more than $100,000 which cannot be paid by credit card. These fees then need to be paid by check, which has to be done in person right now. ATD Review fees are paid to DSD which then transfers these fees to ATD.

**Comment by SurbhiBakshi** [comment]
Need to put in a CTM ticket to enable paying separate fees on Portal by clicking check-boxes for those fees. 

Check with ROW to see how they are dealing with payments above $100,000 - Checked with Paloma, she has asked her team to break up fees more than $100,000 into smaller amounts and issue separate invoices, so the applicant can pay those online. 

Check if there is a way ROW is accepting checks in a socially distant acceptable method for the immediate future - don’t think staff is accepting checks at Toomey.

Update after UAT on 04/01/2020 - Check boxes are visible in the Production instance of ABC Portal due to some work done by DSD IT. Applicants can select one particular fee, and the correct amount shows up in the invoice.  This is helpful since applicants can select different fees that will not add up to more than $100,000.  There is an issue that the total fee is either zero or the sum of all fees, and applicants have to move to the invoice to see the change. This step will need to be communicated to applicants to clear any confusion till this issue is fixed.

**Comment by SurbhiBakshi** [comment]
**Update after UAT on 04/01/2020** 

- Check boxes are visible in the Production instance of ABC Portal due to some work done by DSD IT. Applicants can select one particular fee, and the correct amount shows up in the invoice.  This is helpful since applicants can select different fees that will not add up to more than $100,000.  

- There is an issue that the total fee is either zero or the sum of all fees, and applicants have to move to the invoice to see the change. This step will need to be communicated to applicants to clear any confusion till this issue is fixed.

**Comment by SurbhiBakshi** [comment]
- [ ] Will need to put in a CTM ticket to resolve the issue that the total fee is either zero or the sum of all fees.  Need to do some more testing to document this error.

**Comment by amenity** [comment]
@SurbhiBakshi - is this being handled by CTM?

**Comment by SurbhiBakshi** [comment]
@amenity - yes, I have sent in a request, will include the Help Desk ticket here.

**Comment by SurbhiBakshi** [comment]
REQ0046059

**Comment by amenity** [comment]
TIA folders are configured in AMANDA and in use by TDSD to assess fees - typically linked as a child folder to the SP folder or zoning folder. Invoices are visible there, but this folder was/is not visible to applicants on the ABC portal. 

Looks like this is in the CTM backlog.

**Comment by amenity** [comment]
If it has already been coded, it is a low level of effort. Will need more information on how this currently configured to estimate accurately.

**Comment by SurbhiBakshi** [comment]
![Checkbox_selection_sum_0.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/1ef51f1c-71a1-42c9-b946-6b0c5cd26d12)

**Comment by SurbhiBakshi** [comment]
![Screen Shot 2020-04-23 at 1.59.43 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/df193afc-9936-42b7-8991-469a56386dc7)

**Comment by Nadin-Nader** [comment]
@amenity @SurbhiBakshi  The task number for this is SCTASK0063293. I verified and it is in AMANDA Tango's Backlog (Servicenow group is AMANDA Support Services) and 12th on the list.

**Comment by SurbhiBakshi** [comment]
![Checbox_select_all_sum.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/03ab705a-c5b2-4572-b1ec-a7091ed4e168)

**Comment by SurbhiBakshi** [comment]
[Uploading... Checkbox_selection_invoice.png ]

**Comment by amenity** [comment]
Looks like it would be a relatively low level of effort - 3-4 days.

**Comment by SurbhiBakshi** [comment]
Swapna emailed to say this bug has been fixed. Will move this to QA/Review just in case @Nadin-Nader or Sangeeta want to check.

**Comment by Nadin-Nader** [comment]
@SurbhiBakshi 
Sangeeta replied to Swapna's email saying that this is verified with Intake and it is now working properly.
email:

> From: Jain, Sangeeta <Sangeeta.Jain@austintexas.gov> 
> Sent: Monday, April 27, 2020 4:14 PM
> To: Bakshi, Surbhi <Surbhi.Bakshi@austintexas.gov>
> Cc: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Subject: RE: Catalog Task SCTASK0063293 has been assigned to group AMANDA_SUPP
> 
> Yes, I checked it out with Intake, and looks like its done.  Thanks
> 
> Sangeeta
> *Out of an abundance of caution, the Transportation Development Services Division is working remotely. We are committed to completing reviews and projects in a timely manner and will remain available to the public and development community. Please continue to reach out to us via email (preferable) or our desk lines with any development related questions. In order to ensure health and safety of the citizens of Austin, we are moving from in-person-meeting setting to online meetings for the next few weeks.
>

**Comment by SurbhiBakshi** [comment]
This is done, closing this issue.
