### ISSUE TITLE
TDSD review fees in Amanda for Site Plan Cases

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2293]
When Rodrick's group does intake, they should charge the applicant these ATD fees along with the other fees they charge for DSD and PAZ, based on the type of case application.
Rodrick's team will provide the customer with the bill/ invoice.
Based on the type of case application - C8,C814, SP , ZC, and the subtypes, the fees should be automatically calculated for ATD.
Applicant pays these fees at OTC/ Highland Center (when that happens), ATD will get these fees.
As per George (CTM), Tracy had emailed a request in Jan, the work is in Test, and needs a UAT before it can be moved to Production.
as per Sangeeta, Zoning cases would be the most urgent.
Sangeeta tried to do some testing on March 20th, but was not successful. We need to know if it works on the DSD side.
https://app.zenhub.com/files/140626918/8f9d32d4-6092-4c84-bcf6-c98b151e721a/download
image.png

**Comment by SurbhiBakshi** [comment]
Update after UAT on 04/01/2020 -  For Site Plan cases, fee amount is automatically calculated and inserted when a user from the Intake team selects the correct fee from the pick-list using the Insert + Run procedure in the Fee tab after Completeness Check is done.

**Comment by SurbhiBakshi** [comment]
Some of the fees Sangeeta refers to are not included in the spreadsheet I got from George. I have asked Sangeeta to identify which ones

**Comment by SurbhiBakshi** [comment]
REQ0046072

**Comment by SurbhiBakshi** [comment]
Missing fees covered in #2401

**Comment by amenity** [comment]
@SurbhiBakshi will work with Sangeeta to verify.

**Comment by SurbhiBakshi** [comment]
Your Request REQ0046156 has been opened. If you are the Requested For, you can view status from My Open Requests on the COA ServiceNow Portal
 
Submitted By: George Shirai
Requested For: Surbhi Bakshi
Item: Ad Hoc Request Form
 
DEVOPS - Promote from TEST to PROD - TIA fees on DSD folders - commit 82e03a020d15
Description: UAT was conducted by Surbhi and approved for promotion to PROD. Please promote from TEST to PROD.
 
Commit on TEST branch is: 82e03a020d15
 
(It consists of two squashed commits from Team Mongoose branch: 370a7b026d04 and b45f6d945ad1)

**Comment by SurbhiBakshi** [comment]
- Reached out to Sangeeta to check if she can see the fees in Prod, 
- she cannot see the fees in the Insert and Run procedure, which is used by DSD (Zachary W and Roderick B) to get the fees in the case. 
- Have reached out to George S at CTM to see the deployment took place last week.

**Comment by SurbhiBakshi** [comment]
Email from George - Thanks for checking up on this. It turns out it was held up due to a requirement that it gets a signoff from the financial person of the affected department. I will prepare an e-mail and have you CC’d on it.

**Comment by SurbhiBakshi** [comment]
Email from George -

**Comment by SurbhiBakshi** [comment]
As per Meredith Q, ATD Finance will need to look at the fee GL codes and confirm before CTM can move forward with deployment.  The technical work is done, but this is blocked by FInance for right now.

**Comment by amenity** [comment]
@TracyLinder - when you check with Van to review these, might make sense for her to also look at [the additional fees we have asked LaunchIT to add](https://github.com/cityofaustin/atd-data-tech/issues/2401#issuecomment-616796344).

**Comment by TracyLinder** [comment]
### Email to Sangeeta, asking for status, 6/6/20:

Hi Sangeeta,

I hope you are doing well. I'm writing because I see we have two stagnant tickets for your group related to fees in AMANDA. It looks like they were close to done, and then got lost in the shuffle when I came back to work from my medical leave. See the ticket info below; can you please tell me if either of these have been resolved for your team? 

#2293 TDS Fees in AMANDA - Opened on April 8th, your team asked us to make sure Roderick's group with DSD could add ATD review fees, using their normal process to add fees, to these folders: C8, C14, SP, ZC. 
#2401 Three Missing ATD Review Fees - I'm not sure what the scope of this request is. It looks like it covers fees that were missed for ticket 2293.

All the Best,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
I'm closing this. I'm not sure what the ask here was, or how it may have been resolved. I have been working closely with these stakeholders the past few months and am confident that all of their AMANDA needs are captured in our backlog, or have already been delivered.
