### ISSUE TITLE
PPE Tracking in COVID-19 Time Tracking App

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2295]
Set up workflows to track the quantities of personal protective equipment (PPE) on hand at all of our facilities. 

Finance and HR have been doing most of the purchases for PPE. Finance is approving purchases in Knack. New purchases are happening almost every day.  Each of the divisions is managing or distributing their supplies on an as needed basis.

Currently there is a spreadsheet that staff have been using to keep track of deliveries. That spreadsheet does not provide information on how much is left, only what the department has received and distributed to each facility since March 16th.

**Features and requirements:**
- [ ]
- [ ]

**Future features:** 
- [ ] Connect to purchase, replenishment, etc

**Comment by dianamartin** [comment]
Reference #500

**Comment by JaceDeloney** [comment]
@JaceDeloney  See #500 for any overlap

**Comment by JaceDeloney** [comment]
Forgot about this issue and created a new issue. Tracking this work in #2351 now. Closing out.
