### ISSUE TITLE
Create work order signs assets table

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#230]

**Comment by amenity** [comment]
Ask Christina to reformat table and resend to @dianamartin and @johnclary

**Comment by dianamartin** [comment]
![image](https://user-images.githubusercontent.com/21112975/59628739-f7848800-9106-11e9-8690-33ad0c1ef6f4.png)

Create concatenated field for "Asset label"

**Comment by dianamartin** [comment]
Addings "Specification" fields now
