### ISSUE TITLE
Make ROW permits available to applicants on Portal

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2304]
## Request Status:
**This will be ice boxed until after the portal upgrade. At that time we should reassess the complexity of this request based on portal constraints.** 

### As a COA citizen, I want to be able to view ROW permits on the public portal 

**Stakeholders:** Paloma, Kim, Ryan
**DTS Manager:** Tracy

**Notes:**
- Per Ryan M. on 8/17/20, this should be the lowest priority ticket in ROW's backlog, until further notice. 

**Acceptance Criteria:**
- Applies to folder types: EX, RW, DS, PSM
- Applies to folders only if there is a value in folder.issuedate
- Internet Users will be able to open their permit on portal, and download a copy of their permit
- The public will be able to open a permit folder, and download a copy of the permit
- The permit is up-to-date

**Comment by SurbhiBakshi** [comment]
please refer to #1528 for more details.

**Comment by SurbhiBakshi** [comment]
This is a pretty complex issue, due to the differences between Amanda and Portal. RW has different templates based on sub types. Portal allows only one template per folder type. 
Either the RW templates will have to be reworked to allow for only one template for all the sub types, or there will have to be a change to Portal . Either way is not a simple fix. Iceboxing this issue for now.

**Comment by Nadin-Nader** [comment]
@SurbhiBakshi Spoke to Surya and asked her more about this. She informed me that currently the permit that can be printed via Portal is only linked to the folder type and not by sub/work.
If it requires to be different templates by Sub/Work for RW the the Portal will need to be modified. 

I also asked how much of an effort that would be, from a scale of 1-5 (5 being huge), Surya said that they would have to look at the current set up to determine how big and to make sure it does not affect other folders, but it would be a pretty big effort. 

She also mentioned that there are a lot of Portal issues and enhancements right now and that they would take a bot to get to this request so if work can be done to have only one template, then to please try that route first.

Let me know how you would like to proceed or next steps if we aren't Iceboxing it

**Comment by SurbhiBakshi** [comment]
@Nadin-Nader thanks for reaching out to Surya! Let's bring this up in backlog grooming today if possible. I am not sure ROW wants to go the route of having one template, or how much effort would be needed from them for this purpose.

**Comment by TracyLinder** [comment]
### Update 

This work has been delivered on another ticket.
