### ISSUE TITLE
Add approved by column

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2309]
As a timekeeper and COVID-19 Time Tracking approver, I want to be able to see what I have previously approved. 

Add an approved by column to the Approved table in the Review Time Logs tab.

**Comment by amenity** [comment]
@dianamartin is coordinating with Peggy on this.

**Comment by dianamartin** [comment]
I added column on 4/14 during the `Time log` meeting.

**Comment by dianamartin** [comment]
I told Peggy that I'd update at EOC type logs with the `COVID Response` - Yes. Accidentally updated the wrong fields for Modified Date/By and overrode the Reviewed Date/By fields. I had to correct them and I said I'd resend the data export to her.

**Comment by dianamartin** [comment]
Emailed Peggy
>Per our conversation yesterday, I updated all time log task type “Emergency Operations Center (EOC) Staffing” to the COVID Response – Yes. I re-exporting the records from yesterday with this updated one.

>So now you can review 350 records/467 records instead of the full 467
