### ISSUE TITLE
Point TCP Business Days Script to New App

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2317]
[This script](https://github.com/cityofaustin/atd-data-publishing/blob/master/transportation-data-publishing/data_tracker/tcp_business_days.py) needs [this config](https://github.com/cityofaustin/atd-data-publishing/blob/8162a7f044cede93e109ffaa629ffb334c803f55/transportation-data-publishing/config/knack/config.py#L699) updated.

We'll have to update `secrets.py` with the new credentials as well.

**Comment by johnclary** [comment]
@dianamartin in Data Tracker, the API view is:
-    scene: `scene_754`
-    view: `view_1987`

And the object is `object_147`.

Would you make sure the API view is configured to match what's in Data Tracker, and provide me the scene, view, and object IDs?

Thanks.

**Comment by dianamartin** [comment]
@johnclary this is the ROW Portal API View information.

API View
- scene: `scene_22`
- view: `view_26`
- object: `object_2`

**Comment by amenity** [comment]
ROW has a 9 day turnaround so there's a Python script that calculates business days. Need to get this into the new app.

**Comment by amenity** [comment]
Sprint 33, @johnclary?

**Comment by ChrispinP** [comment]
@johnclary can this be closed? should this script be retired since we use a Knack equation to calculate business days?
