### ISSUE TITLE
Spike: eCapris integration

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#2320]
We know the subproject ID is the unique ID that links between the eCapris and the Access DB, but there is also various financial information pulled in. We need to know the nature of the current integration (one-time write into the Access DB, or is the financial information updated on a regular basis?).

**Questions**

1. How will we retrieve information from eCapris (API, web hook, scraping, etc.)?

2a. What data is currently pulled from eCapris into the Access DB (JD will work with Nathan to identify 3this)?

2b. How often can/should we retrieve information from eCapris? One-time? Synchronization?

3. What data is necessary to pull for finance-related requirements?
Initial hunch is that a light connection to eCapris via subproject ID, where one can click a button from within a project context in the Mobility Project Editor and open up eCapris based on the same subproject ID (if the project isn't tracked via eCapris, the button won't display).

**Comment by zappfyllc** [comment]
1. We still need to look into the solution approach here: Nathan simply downloads a CSV/XLS from eCapris.

2a. Subproject ID is pulled as the unique ID associated with a project in eCapris, along with all FDU information for a subproject. This information is pulled via the "Microstrategy Reports" CSV/XLS download.

2b. Consuming daily should be fine for FDU updates, but we may be able to "fake" an integration/synchronization via subproject ID and dropping users onto eCapris in the given subproject and all of the FDUs associated with a subproject.

3. Initial hunch appears to be correct, although referencing FDUs in other MoPeD data entities may be necessary.

**Comment by amenity** [comment]
Emailed Brian L. and Bruce N. about getting programmatic access to eCapris.

**Comment by amenity** [comment]
Per Slack:

@zappfyllc 
re: eCAPRIS email @amenity @sergio
I think it’s promising news that the report Nathan currently downloads for Access DB/eCAPRIS is in MicroStrategy, as they appear to have REST APIs well documented. At a glance it looks like we would be most interested in the Authentication API and the Reports API.
https://lw.microstrategy.com/msdz/MSDL/GARelease_Current/docs/projects/RESTSDK/Content/topics/REST_API/REST_API_API_families.htm

Looks like they have specific ReactJS examples too: https://lw.microstrategy.com/msdz/MSDL/GARelease_Current/docs/projects/RESTSDK/Content/topics/REST_API/REST_API_Samples_intro.htm

@johnclary   
niiiice. our Microstrategy is on-prem, but that should be doable

**Comment by zappfyllc** [comment]
@johnclary Per our conversation on 6/10, is this information (subproject ID, FDUs [tbd on whether we need these], etc.) available to be pulled from the City Controller's office? I believe you said Knack apps pull in other information, and that eCapris' data isn't accessed from eCapris directly. Please advise.

**Comment by johnclary** [comment]
The complete, authoritative list of funding codes (FDUs) should be sourced from the controller's office (for reference, [here's](https://github.com/cityofaustin/atd-finance-scraper) a script that does that). E.g., if Moped needs a feature that allows users to pick FDUs, we would want to source the pick list from the controller's office.

Subproject ID's only live in eCapris, and if we want to fetch which FDUs are associated with with a subproject ID, we will have to pull that data from eCapris.

make sense?

**Comment by zappfyllc** [comment]
Closing this and referencing it in our project financials and eCapris integration features for future reference
