### ISSUE TITLE
Spike: Analytics Integration/Standalone Solution

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#2323]
_Context_: Several stakeholders would like the ability to run reports and create dashboards with MoPeD's data to inform business decisions and/or present information to the public. Currently, the Vision Zero Viewer works with Power BI as its analytics solution (Xavier uses this?), so that may dictate the requirements for MoPeD. Additionally, a quick or easy way to extract data from MoPeD into a CSV would be great.

**Questions**

1. What is the current implementation of Power BI for the Vision Zero Viewer?

Read-replica of the VZD. Xavier uses this endpoint for different BI-powered dashboards. Currently Xavier interfaces with devs whenever needing something from the read replica. Do we have a similar data owner for Power BI for Moped? (Is there a BI analyst who would be owning this?)

**Comment by zappfyllc** [comment]
Leave this spike in conversation for later. @zappfyllc, add this under the Power BI feature epic.

**Comment by amenity** [comment]
This is now covered by other features, see 
- #3794 (Socrata data can feed users' BI platform of choice)
- #3680
