### ISSUE TITLE
Spike: Foreign Key Identification

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#2325]
_Context_: FKs haven't been used in Vision Zero Viewer's development, but they are going to be integral to MoPeD's success. We know the obvious need to track a Project ID across related entities, but there are many other areas where a foreign key could be enforced because of the many relationships existing in the data model. With that said, there may be some areas where a foreign key should not be used because we want to easily create records without the need for specific IDs all of the time. The goal of this spike is to analyze entity attributes and relationships and whether a foreign key should be used.

Spreadsheet: https://docs.google.com/spreadsheets/d/1LX_7Dt6sWtXh-uf0tPj0Ljq2ZG8RkGZwnaQ_waZnnv8/edit?usp=sharing

**Comment by zappfyllc** [comment]
Moved to backlog until the ERD is finished and we have a clearer direction on dotMaps

**Comment by zappfyllc** [comment]
Moved to Sprint 30 for now and will use this to document foreign key decisions while standing up initial Postgres schema and the database.

**Comment by amenity** [comment]
@zappfyllc — backlog, maybe?

**Comment by zappfyllc** [comment]
@amenity This is happening on the fly within Hasura. I think instead of having a bunch of documentation around foreign key decisions we made, I can simply walk through the schema with @sergiogcx and we can discuss why the decisions were made, modifications we may want to make, etc. I'm going to ditch the waterfall-ish documentation as much as I can as we have tangible pieces of Moped like Hasura stood up. I'll close this for now and once #2326 is completed, I'll spring up a meeting for walking through Hasura decisions.
