### ISSUE TITLE
[RPP Back Office] Refinements after RPP Usability Testing/MAP Enhancements

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2331]
**Map Splash page**
Ignore the splash screen. 

**Address Search**
Entered address in the search, circle loading. 

**Loading time/performance**

- Expectations are high, seems to be taking a long time.  Still spinning, finally got it. Took a long time. 
- Taking a long time to load, is annoyed by how long. Seems too long. Would normally, click out of the app and try again. 
- 2nd time: Typed in 2100 Oxford Ave. Still frustrating. No further instruction on how street is being entered, so can be confusing. 
- Searching is taking a long time. Instinct to take out the address number and put in street name only.
- Loading is taking a long time. Like the spinning arrow to know it’s still loading. Don’t know why it’s moving faster, not sure it’s working. 

**Map Functions**
Legend isn’t automatically showing. 
Would be nice that legend shows up immediately. 

**Symbology**

- Don’t know the importance of symbology, don’t need to know the importance. 
- Doesn’t know what that means after it centers on address. Doesn’t mean it’s eligible. The map doesn’t seem clear on what is eligible. Surrounded by a red border, included in RPP Properties layer list. Colors are similar so hard to tell. 
-  Parking Zones are confusing bc of the colors, color blind. 
- Concerns over color blind residents now seeing the differences 
- So assuming they are eligible bc you’re outlined in Red. Don’t know what the yellow coloring is. 
- Don’t know what the Orange District means. 

**User Questions/Comments**

- Process is confusing after this part
- After use determines eligibility status, the user isn’t sure what the next steps are.
- User questioning, do they need to know what zone or district color they’re in? 
- Map doesn’t really give users confidence that they’re eligible

**Comment by moorerst** [comment]
@dianamartin on the New Verfiy Address Page
Why do we need the **NOTE: Fill in "City", "State"** both of those fields auto filled
The **Contact Us if you need help** – this takes me back to the Home page is that by design?
Think we decided this is one of the places the main phone number would be displayed.

**Comment by dianamartin** [comment]
- [x] I removed the `Note: for City/State`
- [x] Updated the Contact us for both eligible and ineligible results to redirect to the correct `contact us` pop-up

**Comment by dianamartin** [comment]
- [ ] Get with Yunuen/Jaime to update the RPP map
- [ ] Need to ask Jaime what the proposed Parking Zones GIS workflow is going to look like
- [ ] Need to ask John about the other fields to bring in, update the JS code
