### ISSUE TITLE
[RPP Back Office] Refinements after RPP Usability Testing/Splash Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2332]
- Eligibility is large enough for user to see
- Wanted to click on the first link, bc it’s so much larger. First line seems more important because it’s big.

Permit Cost, the “must” is weird. 

- [x] Take out “must”. 

- Was too much text, suggested making buttons or sections clickable for users that want to find more information. 
- Skimming through it, but feels like it’s a lot of information.  A lot of text.
- Have the splash page info readily available

- [x] Button or hyperlink - Permit Costs, Day Pass Cost
- [x] Questions: Should be at the top under requirements (Rearrange information)
- [x] Start application button at the top (moves towards the top)

**Comment by dianamartin** [comment]
## Before
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/7f2c8c35-a86b-426b-80a6-1c37fb662b46)

**Comment by dianamartin** [comment]
## After (Some changes)
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/19ce3c3c-51d1-4c0a-bf55-162bc3e14901)

**Comment by dianamartin** [comment]
@moorerst Check out the changes!

**Comment by moorerst** [comment]
@dianamartin I really like the changes it looks so much cleaner and it's all on one page not a lot of scrolling

**Comment by moorerst** [comment]
@dianamartin I like the addition of About The Program on the Home page

**Comment by moorerst** [comment]
@dianamartin could we move Learn more about RPP Program as a bullet under What you should know before applying?

**Comment by dianamartin** [comment]
@moorerst this is true
