### ISSUE TITLE
[RPP Back Office] Refinements after RPP Usability Testing / VEHICLE (Part 4)

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2335]
Part 4: VEHICLES

- Why is this the banner in red”. Have to add vehicles in. Placement of that message good? 
- Suggested test: “Please add your vehicles below”. The number of ‘residential” vehicles. 

- [ ] Assume that it would turn green once criteria is met. (auto refresh?)
- [x] “Add Vehicle”, change to “Save” 

- User feels like it shouldn’t allow user to move forward, it should stop you at the other page. 

- [x] (Make required, submit/continue button doesn’t show up until completed)

- Adding vehicles, noticed the banner. Don’t want to add vehicle information. Thought was going to be stopped on this page to make them put in the second vehicle. 

- [x]  Banner wasn’t eye catching enough for user on the Add Vehicle page

- [ ] License plate: make TX default the top
- [x] Better if it would be better if Add Vehicle form defaulted to reloaded. (change to automatically reload form)

- Assume to move forward, hopefully good to click the Review Application form.

**Comment by dianamartin** [comment]
I have having a refresh issue with the banner not going away, so I decided to create a the `Add Vehicle` form as a modal pop-up that redirects to the parent page, which pushes a refresh to the page.

**Comment by dianamartin** [comment]
@johnclary I have implemented a work around, but i'm not super happy about it. Would like your eyes and brain on if this is the best way going about this.

**Comment by johnclary** [comment]
@dianamartin happy to take a look at it w/ you

**Comment by dianamartin** [comment]
Scheduled time with John on Monday, 4/20

**Comment by dianamartin** [comment]
RPP Process meeting and 1:1 with John. The proposed plan is to combine the permits/vehicle forms so we won't have this issue anymore. Created new issue #2446
