### ISSUE TITLE
[RPP Back Office] Refinements after RPP Usability Testing / Review Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2337]
- Didn’t notice the banner on the Review page. The banner wasn’t eye catching. (Pop-up banner).
- [x] Banner larger?

**Permit Costs**

Subtotal and then Subtotal tax, then have total. Day passes cost: $1.08. User thinks it’s weird math. 

**Vehicle Information - Edit button**

Clicked back to Vehicle Information. There is an edit button to edit the vehicle. Page title is clear. Maybe add language “Not yet submitted, please review”. Visually hierarchy to see what 

**Permit Information - Edit button**

Change permit numbers. Changed permit information. Preferred seeing the “maximum 2”, “maximum 4”, instead of the add permit form language.
 
- [x] So user chose less decals, but we don’t ask the user to remove a vehicle. 

- [x] Have a requirement to make user remove vehicle

**Signature Area**

- [x] Rules and Guidelines at splash page, pop-up instead of navigating away. (Have Rules & Guidelines a pop-up or put in Splash page)

- [ ] Test this with trackball users, how would they feel about signature field? 

- [ ] Adding guidance for users: 

Might need to initial. 
Touch screen to see if it works. 
Might need support on how to sign the document.

**Comment by dianamartin** [comment]
I asked Jaime
>If you were using your track ball mouse and had to do a digital signature, what would you do? how would you feel?

response
>My mouse is different then most trackballs as the ball is controlled by 4 fingers, not one or just my thumb so it's probably easier to do something like signing.

**Comment by dianamartin** [comment]
@moorerst I had Jaime test the RPP form with her trackball and I posted the feedback and results in the comment above.
