### ISSUE TITLE
[RPP Back Office] Refinements after RPP Usability Testing / Invoice - Payment Options

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2338]
## Invoice Page: 
- Is math right? Question is in the tax permits? Tax cost per permit, instead assumed it was the total tax. 
- Payment Options on invoice were small (as designed)

## Payment Options Page: 

- Payment Options Banner

This button give the impression that you can pay online. Scrolled to the bottom read couldn’t pay online, then scrolled up to the top and thought could pay online because they saw that button. But was let down bc the information reiterated still couldn’t pay online. 

- [x] Remove banner?
>Removed banner, but screen shot in case we need it.

### Payments in General

“Please bring exact cash, check. Credit also accepted.”

- [x] Check Payment info. Why is there an address? (Look into why address is needed?)

- [x] Clarity that mailed payments are not accepted. For historical users to let them know. (Add a notice or note)
- [x] User suggested including transit options. 

### Hours of Operation

- [x] Hours of Operation, listed weird. Don’t care what the hours of operation are for the business. Update the language “No permit applications will be accepted from 12-1 pm and after 3 pm”, change to 3:30 pm. “Payments Accepted” instead of “Hours of Operation”

### Phone Payments

- [x] Under “Phone Payment” on Options. Would need to add “Payments Accepted” and hours of operation. 

- [x] ATD Staff will contact you”, but not “can contact you”.

- [x] Phone instructions. “Staff will contact them for payment or have user to call phone call”.

**Comment by dianamartin** [comment]
@moorerst I've updated the [Payment Options](https://atd.knack.com/parking#payment-options/) page too, if you wanna look

**Comment by moorerst** [comment]
@dianamartin looks great. Suggested language for In Person Payment
Pay In Person at the Parking and Mobility Services Permitting Office during payment hours
Exact cash, check or credit card accepted

**Comment by dianamartin** [comment]
### Note if we need Payment Options banner back
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/6f4749df-5aca-4946-bf1d-9028182409f0)

**Comment by dianamartin** [comment]
@moorerst I updated the `In-Person payment` information

**Comment by dianamartin** [comment]
## OLD LAYOUT
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/f71a852e-70ae-4e30-869d-c24083297ad6)

## NEW LAYOUT
[Uploading... image.png ]

**Comment by moorerst** [comment]
@dianamartin new layout looks good
Should there be a title over Permit Information in section one like Application Information?
