### ISSUE TITLE
[RPP Back Office] Refinements after RPP Usability Testing / Application Configuration

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2340]
- [x] Home of RPP - include which browsers are compatible with the application.

- [x] Try not to make the user leave your application to see other information in another website

- [x] Help phone/email should be on all pages of the site no matter what so if user has issues they can ask for help.

**Comment by dianamartin** [comment]
@moorerst 
- [x] Added the browser foot note on the front page (RPP)
- [x] Added email footer to all application pages
