### ISSUE TITLE
[RPP Back Office] Refinements after RPP Usability Testing / Recommended Process Changes

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2341]
- Users thought they could pay online

Realized that has to pay in-person or over the phone. 

- The user did not realize that their application needs to be reviewed before payment can be processed. 

- [ ] Expectations set to customers: 
- submit application expectations. How long will it take? To see the customer’s expectations. Need to say putting in application, payment. Don’t think they should be separate. 
- Doesn’t say how long that takes to review. Expectations aren’t outlined for customer for when a staff person is going to reach out to them. 

Realized later they could pay over the phone. No expectations for user. Language should be clear, timeframe review. Will be contacted with a number to make a payment once  it’s reviewed and approved. 

- Clarity that mailed payments are not accepted. For historical users to let them know. 

- Set users expectations so they’re not trying to call the office. Hours to call in payment of instructions when to call customer. Better for customer to choose how they want to pay.

**Comment by dianamartin** [comment]
Had a process meeting with RPP Staff and they clarified these questions we had.
