### ISSUE TITLE
Meeting for ROW Out of System Fees in Portal 

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2345]
Meeting to discuss getting  ROW Out of System fees in Portal. Put fees from #1951 in Portal once fees are in Amanda.

**Comment by SurbhiBakshi** [comment]
We looked at the issue on 04/21/2020 as a follow up to # 1951 with Paloma, Ryan, Raj, and Sreelatha.

**Comment by SurbhiBakshi** [comment]
1. When logged into Portal, applicant associated with Out of System fees should be able to see the fees when they click on My Fees.
2. Applicant should be able to pay those fees.

**Comment by Nadin-Nader** [comment]
Logged into Portal and AMANDA TEST and used one of my old cases on test that had a fee (2020-002463 DS) of $46.80 for Excavation/Concrete Permit Fee - Transportation $45.00 and ATD Tech Surcharge ROW $1.80.
I was able to see this when i went to the "MY PERMIT/CASES" menu but when i went to the "My Bills" menu, i had zero fees to pay.
Need to:
- [ ] Create Request to have Portal team add or make visible all of the AMANDA ATD fees on Portal for users to Pay online
- [ ] or Create a CTM request to have the specific fees needed, show up on the portal in order for users pay online (For this one we will need to get the specific fees from the stakeholders
- [ ] UAT on TEST and deploy to PROD if changes are correct

**Comment by amenity** [comment]
Launch IT will implement this in #1951
