### ISSUE TITLE
ATD (ROW) - LIT Meeting | April 20th, 2020

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2353]

**Comment by amenity** [comment]
My (few) notes are in [the agenda doc](https://docs.google.com/document/d/1QPhLVSu2aZqGC7VMkyF_39yOC_ufULcKRfZTo8Tg9Mw/edit#). 
@Nadin-Nader @johnclary @SurbhiBakshi - will you add yours there or as comments here?
