### ISSUE TITLE
ATD (TDSD) - LIT Meeting | April 27th, 2020

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2356]
[Agenda](https://docs.google.com/document/d/12OvgzaroeGL-DkZ86mq7d-P6FZtq1XGTBP0Mp1qJJwU/edit#)

**Comment by amenity** [comment]
Meeting went well. Current state of TDSD issues:
![2020-04-27 ATD-LIT-TDSD AMANDA Backlog](https://user-images.githubusercontent.com/1463708/80398785-caa01600-887d-11ea-86af-28365372ec92.png)

@SurbhiBakshi @Nadin-Nader - please add any notes to [the Google Doc](https://docs.google.com/document/d/12OvgzaroeGL-DkZ86mq7d-P6FZtq1XGTBP0Mp1qJJwU/edit#)
