### ISSUE TITLE
Set up DTS Support Knowledge Base in Gitbook

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2364]

**Comment by dianamartin** [comment]
- [x] Created ATD DTS Service Desk Knowledge Base wiki (private)
- [x] Connected all ATD Wikis 
- [x] Started Training page for Service Desk
- [x] Manage Inbox page
- [x] Add tech events to shared calendar page
- [ ] Triage issues while on service desk assignment
