### ISSUE TITLE
Prep for AMANDA / Launch IT meetings

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2365]
### Objective 
@SurbhiBakshi is going to reach out to Raj to see what his plans are for facilitating next week's meetings with Launch IT. Let's sync up on what we need to do to prep. 

### Participants
Amenity, Surbhi, Nate
Optional: John

### Agenda
What cleanup do we need to do so that we can refer directly to the Zenhub board in the meeting? 
![Screen Shot 2020-04-15 at 3.31.04 PM.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/10f42e4a-a444-465d-bbf6-4c8fa2366601)

Can we confidently retire the [glorious Google spreadsheet](https://docs.google.com/spreadsheets/d/1ix5X-cQSW2ZRhlwtBemRkJP5vjF3cKT2ovGuX9hT7C4/edit#gid=462314407)?

------
- [ ] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by SurbhiBakshi** [comment]
@amenity @johnclary @Nadin-Nader - wrote to Raj, will update when I hear back
