### ISSUE TITLE
Document process used to create new set of assignments

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2369]
While we're not sure whether we'll get tp #1295, manually duplicating sets (one month, so far) of assignments for Lewis expedites his workflow. We'll document this so it's easy to repeat moving forward.

**Comment by SurbhiBakshi** [comment]
- [ ] clean up one week's worth of assignments with locations all filled out in new format.
- [ ] Clean up fields from old format.
- [ ] export out assignments from Knack for that week 
- [ ] Replace dates with appropriate dates
- [ ] Change Assignment ID
- [ ] Import assignments back to Knack
- [ ] Document each step

**Comment by SurbhiBakshi** [comment]
Here is the [Documentation](https://docs.google.com/document/d/1ViqKPKDry-EDL7DASL2mFYpZ-M1sFxy9VyJOCGloGr4/edit?usp=sharing)

**Comment by amenity** [comment]
@SurbhiBakshi It's beautiful! ✨🙏📚
@johnclary @dianamartin - where do we want to keep this type of documentation?

**Comment by dianamartin** [comment]
@amenity it looks like it should be on an external user guide for VZA, new gitbook space?

**Comment by SurbhiBakshi** [comment]
@dianamartin @amenity don't think an external user would copy batch assignments.  If there is only going to be one guide, it's fine because it requires access as a builder to be able to carry out the process.

**Comment by dianamartin** [comment]
@SurbhiBakshi @amenity Oh...my bad. This belongs in the Knack Operations GitBook under a new group called VZA.

**Comment by SurbhiBakshi** [comment]
thanks @dianamartin! 
@amenity thanks for reviewing! 
will put the document- Knack Operations GitBook under a new group called VZA.

**Comment by amenity** [comment]
@SurbhiBakshi - sounds good. Go ahead and close this when you've done that.

**Comment by SurbhiBakshi** [comment]
@dianamartin @amenity - having some issues with keeping the numbering from the Google doc in the wiki.  Might have to rework that in the wiki.
