### ISSUE TITLE
Review existing VZA Citation App prototype

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#238]
Create a prototype Knack app for VZA citation tracking.

Here's the workflow I'm envisioning:
- Lewis does schedule online in Knack
- Randy references Knack schedule + shift number when creating schedules in Revolution 911
- Randy gives officers their shift number and link to Knack form in reminder email
On shift, officer follows link using iPhone, enters shift number, which auto-completes and links back to - a scheduled shift.
- This activates a “shift” record and redirects to shift “details” page
- the officer can repeatedly submit citation form from shift details
- Citation form automatically captures location
- When finished, officer hits “end shift” button to finalize

In Knack, this boils down to:

##### Objects
1. shifts < one to many relationship to citations
- shift_date
- shift_id
- assigned_to_badge_number
- status (scheduled, in progress, closed)
- planned_activities (types of enforcement to be conducted)
- locations (general area where shift is to take place)

2. citations (or, actions?)
- activity_type (citation, warning, no problems found)
- date
- location (captured automatically via location services)
- other stuff i'm forgetting

##### Pages
1. Schedule (object = shifts)
- Create, Edit, Search Schedule in calendar view

2. Shift Details (object = shifts + citations)
- start shift, add citation, edit citation, end shift

**Comment by johnclary** [comment]
In progress, here:
https://atd.knack.com/vza

**Comment by johnclary** [comment]
In progress, here:
https://atd.knack.com/vza

**Comment by amenity** [comment]
@johnclary - the link above isn't working for me. 😕

**Comment by johnclary** [comment]
@amenity fixed ^^^

**Comment by amenity** [comment]
@johnclary is going to hand this off to @dianamartin.
