### ISSUE TITLE
AMANDA Reports: Fee Waivers Epic (TL)

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2388]
### As an ATD manager; I'd like a report that I can pull whenever I need to answer questions about fees we have waived in AMANDA.

**See child issues for specific report requirements.**
**DTS Manager:**
Tracy Linder

**Comment by TracyLinder** [comment]
We'll need to do some user research to learn how waivers are being used currently, and which waiver reasons should be reported on.

**Comment by TracyLinder** [comment]
Convo w/ Paloma & Kim:

This is still a need, yes. ACE even more than ROW.

**Comment by TracyLinder** [comment]
**(Project Specific) Report Info:**
- Make it exportable to excel
- Query by Fee Comment
- Fee amount waived
- Fee Comment 
- Fee waiver reason
- Folder RSN
- Folder Name
- Total
- Only include our folder types in this query (see folders below)

**(General) Report Info:**
- Make it exportable for data analysis

Report Parameters:   Adjustment Start Date, Adjustment End Date 
Folder Type
EX, RW, DS, LC, ECV (transportation   subtype), PSM, GF (transportation subtype)

**Comment by TracyLinder** [comment]
### OSE

**Parameters:** Start Date, End Date [Info: Event Start Date]

**Folders to Include:** RW, Street Event

**Report Info:** Folder RSN, Work Type, Folder Status, Folder Name, Fee Date, Fee Name, Fee Amount, Adjustment Amount, Adjustment Reason, Adjustment Comment, Billed To (First Name, Last Name, Org Name)

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - 

#2647 ATD Fee Waiver Reasons Update - Completed by Sreelatha
#3167 ROW Project Specific Fee Waiver Report (TL) - Completed by Subha and sent the reports for review
#3168 ROW General Fee Waiver Report (TL) - Is in Progress by Subha
#3302  Finance Fee Waiver Report (TL) - Is in Progress by Sreelatha

**Comment by Nadin-Nader** [comment]
Per our Stand-Up
**Status:**
Aish is currently working on this

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Subha Completed 3167 & 3168 Reports and sent on August 27th for review.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder ,@Nadin-Nader - Completed the Epic 
#3167, #3168, #3169, #2647 & #3302 Are completed and sent for review. #3169 needs a clarification that when multiple "Billed To" People records exists which one to consider in the Report?

**Comment by Nadin-Nader** [comment]
**Status:**
Responded to the question stating to choose whoever is listed first. It is now being worked on.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder ,@Nadin-Nader - Completed the Epic
#3167, #3168, #3169, #2647 & #3302 Are completed and sent for review. If the Format looks good then this can be moved to DEV for further testing.

**Comment by Nadin-Nader** [comment]
I was able to review the printouts for this epic and it looks to be in order and good to go to DEV.

**Comment by shroffjs** [comment]
Custom Report Configuration is done for #3167, #3168 & #3169 in Back Office. **SCTASK0096074** is submitted to copy the crystal reports to the respective DEV target path.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder @Nadin-Nader - DEP Deployment plan submitted for this EPIC on 09/22/2020.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff  I have deployed 99010 and 99016 to dev. I also Sent the deployment to CM DevOps to add the LookUp for #2647.  
Deployment is under **SCTASK0097466**

I was able to run both reports on DEV successfully, Please let me know if i need to cancel **SCTASK0097466**

**Comment by shroffjs** [comment]
@Sreelatha-BlazeKannan @Nadin-Nader @TracyLinder 
I tested #3167, #3168 & #3169 in DEV. These are ready for your testing.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder UATd this on DEV and 3167, 3168 and 3169 Passed DEV UAT (3168 card is closed)

They have the date range parameters, exports to Excel, columns are correct and correctly named. Report pulls correct info and calculations.

### I Approve for move to TEST🎉 💯!!

**Comment by Nadin-Nader** [comment]
**Status Update:**
#3169 has been approved for PROD; Waiting on Deployment Plan

**Comment by Nadin-Nader** [comment]
Deployment has been sent to CTM Tango to move the report from TEST to PROD. Task for CTM Tango is SCTASK0099052

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder - #3169 Moved to PROD and Closed.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder - 
#3167 - ROW Project Specific Fee Waiver Report (99012) - Received updated Acceptance criteria to pull another 2 columns.
#3302 - Received queries from Tracy to do Analysis further 
#3169 - OSE Fee Waiver Report (99015) - Approved and Moved to PROD (CLOSED)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder -
#3167 - ROW Project Specific Fee Waiver Report (99012) - Received updated Acceptance criteria to pull another 2 columns. Subha has sent the updated excel sheet on 10/14/2020.
#3302 - Received queries from Tracy to do Analysis further - Sree started to work on this from 10/19/2020.
#2647 - Waiting on PROD Move.
#3169 - OSE Fee Waiver Report (99015) - Approved and Moved to PROD (CLOSED)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder -
#3167 - ROW Project Specific Fee Waiver Report (99012) - Received updated Acceptance criteria to pull another 2 columns. Subha has sent the updated excel sheet on 10/14/2020.
#3302 - Received queries from Tracy to do Analysis further - Sree started to work on this from 10/19/2020. Sree has questions regarding this which needs to be discussed with Tracy.
#2647 - PROD Move completed (CLOSED).
#3169 - OSE Fee Waiver Report (99015) - Approved and Moved to PROD (CLOSED)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder -
#3167 - PROD Move Request submitted on 10/26/2020
#3302 - Further analysis and changes must be done by Sree as per 10/23/2020 Review meeting with Tracy.
#2647 - PROD Move completed (CLOSED).
#3169 - OSE Fee Waiver Report (99015) - Approved and Moved to PROD (CLOSED)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder -
#3167 - PROD Move Request submitted on 10/26/2020; Waiting on CTM Deployment. 
#3302 - Further analysis and changes must be done by Sree as per 10/23/2020 Review meeting with Tracy.
#2647 - PROD Move completed (CLOSED).
#3169 - OSE Fee Waiver Report (99015) - Approved and Moved to PROD (CLOSED)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder -
#3167 - PROD Move completed (CLOSED - 11/03/2020)
#3302 - Report Changes are in progress
#2647 - PROD Move completed (CLOSED).
#3169 - OSE Fee Waiver Report (99015) - Approved and Moved to PROD (CLOSED)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder -
#3167 - PROD Move completed (CLOSED - 11/03/2020)
#3302 - Sent the Report on 11/5/2020 and sent DP for DEV & TEST also
#2647 - PROD Move completed (CLOSED).
#3169 - OSE Fee Waiver Report (99015) - Approved and Moved to PROD (CLOSED)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder -
#3167 - PROD Move completed (CLOSED - 11/03/2020)
#3302 - Depoyed in DEV & TEST and tested the same. Waiting for PROD approval
#2647 - PROD Move completed (CLOSED).
#3169 - OSE Fee Waiver Report (99015) - Approved and Moved to PROD (CLOSED)
