### ISSUE TITLE
AMANDA Report: Metered Parking Fees for Parking Benefit Districts

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2389]
### TPW would like a menu report for the Parking Benefit Districts

**Comment by amenity** [comment]
This is something ROW is doing manually this for Parking and Finance for now. @TracyLinder has done work on it already.

**Comment by TracyLinder** [comment]
**Status: I'm debating on putting this in the icebox until ROWMAN 5 is active, as this is a deliverable of that phase.**

**Comment by TracyLinder** [comment]
Kyle will ask ROW if this is still a need and confirm the need on Friday's ROW Review meeting.

**Comment by TracyLinder** [comment]
### ROW Review

- ROW isn't involved much in the maintenance of PBD programs.
- The PBD programs are managed by finance and Parking Enterprise. 
- I'm going to close this; if either finance or parking enterprise requests this report we will work on it then. 
- We have queries to pull one-off requests.
