### ISSUE TITLE
Issues paying adjusted fees 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2390]
See [Email : Question - Portal Payment of Adjusted Fees](https://app.zenhub.com/files/140626918/5a3175dd-0496-49bb-8e4f-1b57d7901e2b/download)

Sounds like this issue may have already been addressed, would need to confirm with Kim P. Per email from Paloma, see #2381

**Comment by TracyLinder** [comment]
ROW believes this has been fixed. Will create a new issue if it pops back up.
