### ISSUE TITLE
Conditions Pick fields for EX, DS, RW (NN)

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2391]
### As a ROW permit analyst, I'd like the folder conditions pick field to help speed up my workflow, by making commonly used verbiage available. 

**Stakeholders:** Paloma, Kim
**DTS Manager:** Nate

**Acceptance Criteria:**
- Update the conditions pick values on DS, EX, RW
    - See [this](https://github.com/cityofaustin/atd-data-tech/issues/2391#issuecomment-652431743) comment

**Comment by TracyLinder** [comment]
@Nadin-Nader let's pull this into your next sprint; we need to collect the verbiage for each permit type.

**Comment by Nadin-Nader** [comment]
@Nadin-Nader get list from Tracy to start going through it (sent on May 14th).

**Comment by Nadin-Nader** [comment]
Found the email:

From: Amayo-Ryan, Paloma 
Sent: Wednesday, July 17, 2019 6:02 PM
To: Linder, Tracy <Tracy.Linder@austintexas.gov>
Subject: FW: ACTION REQUESTED: Pick Fields for EX, DS, RW

Hey Tracy,

It just occurred to me that this is still sitting on the back burner.  

If it’s easy/quick to do then the ask is to edit the Folder Tab (Conditions Field) pick fields for the EX, DS, and RW folder types.  

Here it goes:
We would like to make the following changes to our Folder Tab “Conditions” section, pick fields:
-	Remove all RW pick fields
-	Change DS as follows:
o	10 FOLLOW PUBLIC WORKS STANDARDS AND SPECS. CALL AUTOMATED LINE 512-480-0623 FOR INSPECTION 24 HOURS PRIOR TO SWLK PRE-POUR (201), SWLK FINAL (202), DRWY PRE-POUR (203), DRWY FINAL (204), C&G PRE-POUR (205), C&G FINAL (206). CALL 512-974-7161 FOR CONSULTATION***
o	20 remove
o	30 remove
-	Change EX as follows and renumber accordingly:
o	10 WORK BEHIND CURB ONLY, NO STRUCTURE CUTS REQUESTED*** 
o	20 FOLLOW PUBLIC WORKS STANDARDS AND SPECS. PROVIDE DATE OF FINAL BACKFILL TO STREET & BRIDGE FOR PERMANENT REPAIR***
o	30 PROTECTED STREET, FOLLOW PUBLIC WORKS NEW STREET/ENHANCED REPAIR STANDARDS AND SPECS. PROVIDE DATE OF FINAL BACKFILL TO STREET & BRIDGE FOR PERMANENT REPAIR***
o	40 remove
o	50 FOLLOW PUBLIC WORKS STANDARDS AND SPECS, SERIES 1100. CALL 512-974-7161 FOR INSPECTION 1 HOUR PRIOR TO BACKFILL, CONCRETE POUR, PAVING***
o	60 PROTECTED STREET, FOLLOW PUBLIC WORKS NEW STREET/ENHANCED REPAIR STANDARDS AND SPECS, SERIES 1100. CALL 512-974-7161 FOR INSPECTION 1 HOUR PRIOR TO BACKFILL, CONCRETE POUR, PAVING***
o	70 remove
o	80 INSTALL POLE, ANCHOR, BASE IN CITY ROW ONLY, NO STRUCTURE CUTS REQUESTED. MUST MAINTAIN A MINIMUM OF 36” SIDEWALK CLEARANCE FOR ADA/WHEELCHAIR TRAVEL. IF SIDEWALK IS AFFECTED, CALL 512-974-7161 FOR INSPECTION***
o	90 remove
o	100 BORE ONLY, NO STRUCTURE CUTS EXCEPT AS NOTED. MUST CALL FOR PREBORE INSPECTION. CALL 512-974-7161 FOR INSPECTION 1 HOUR PRIOR TO BACKFILL, BORE PITS AT STREET CROSSINGS, CONCRETE POUR, PAVING*** 
o	110 FOLLOW PUBLIC WORKS STANDARDS AND SPECS, SERIES 1100. CALL FOR INSPECTION 1 HOUR PRIOR TO EXCAVATION, BACKFILL, CONCRETE POUR, PAVING. ROW USAGE FEES OF $5.50/DAY/SWLK/DRWY/C&G AND $9/DAY/LANE ACCURE DAILY UNTIL FINAL RESTORATION***
o	120 PROTECTED STREET, FOLLOW PUBLIC WORKS NEW STREET/ENHANCED REPAIR STANDARDS AND SPECS, SERIES 1100. CALL FOR INSPECTION 1 HOUR PRIOR TO EXCAVATION, BACKFILL, CONCRETE POUR, PAVING. ROW USAGE FEES OF $5.50/DAY/SWLK/DRWY/C&G AND $9/DAY/LANE ACCURE DAILY UNTIL FINAL RESTORATION. SDRC IS DETERMINED BY STREET & BRIDGE***
o	130 remove
o	140 remove
o	150 remove
o	160 remove

Thx!
Paloma Amayo-Ryan
Transportation Supervisor
(512) 974-2841

 
Austin Transportation Department 
Right of Way Management Division
Mail: P.O. Box 1088, Austin, TX 78767
Office: 1501 Toomey Rd, Austin, TX 78704
Join our Mailing List
Call 3-1-1 to report your right of way closure
Read our new Mobility Guidelines and new Permit Conditions



From: Amayo-Ryan, Paloma 
Sent: Friday, July 6, 2018 5:11 PM
To: Linder, Tracy <Tracy.Linder@austintexas.gov>
Subject: ACTION REQUESTED: Pick Fields for EX, DS, RW

Hi again,

Here are the pick field changes we discussed.  Hooray for an easy win!

Paloma Amayo-Ryan
Transportation Supervisor
512-974-2841

 
Austin Transportation Department 
Right of Way Management Division
Mail: P.O. Box 1088, Austin, TX 78767
Office: 3701 Lake Austin Blvd., Austin, TX 78703
Join our Mailing List
Call 3-1-1 to report your right of way closure
Read our new Mobility Guidelines and new Permit Conditions



From: Amayo-Ryan, Paloma 
Sent: Tuesday, April 03, 2018 8:54 AM
To: Linder, Tracy <Tracy.Linder@austintexas.gov>
Subject: ACTION REQUESTED: Pick Fields for EX, DS, RW

Hey Tracy,

We would like to make the following changes to our Folder Tab “Conditions” section, pick fields:
-	Remove all RW pick fields
-	Change DS as follows:
o	10 FOLLOW PUBLIC WORKS STANDARDS AND SPECS. CALL AUTOMATED LINE 512-480-0623 FOR INSPECTION 24 HOURS PRIOR TO SWLK PRE-POUR (201), SWLK FINAL (202), DRWY PRE-POUR (203), DRWY FINAL (204), C&G PRE-POUR (205), C&G FINAL (206). CALL 512-974-7161 FOR CONSULTATION***
o	20 remove
o	30 remove
-	Change EX as follows and renumber accordingly:
o	10 WORK BEHIND CURB ONLY, NO STRUCTURE CUTS REQUESTED*** 
o	20 FOLLOW PUBLIC WORKS STANDARDS AND SPECS. PROVIDE DATE OF FINAL BACKFILL TO STREET & BRIDGE FOR PERMANENT REPAIR***
o	30 PROTECTED STREET, FOLLOW PUBLIC WORKS NEW STREET/ENHANCED REPAIR STANDARDS AND SPECS. PROVIDE DATE OF FINAL BACKFILL TO STREET & BRIDGE FOR PERMANENT REPAIR***
o	40 remove
o	50 FOLLOW PUBLIC WORKS STANDARDS AND SPECS, SERIES 1100. CALL 512-974-7161 FOR INSPECTION 1 HOUR PRIOR TO BACKFILL, CONCRETE POUR, PAVING***
o	60 PROTECTED STREET, FOLLOW PUBLIC WORKS NEW STREET/ENHANCED REPAIR STANDARDS AND SPECS, SERIES 1100. CALL 512-974-7161 FOR INSPECTION 1 HOUR PRIOR TO BACKFILL, CONCRETE POUR, PAVING***
o	70 remove
o	80 INSTALL POLE, ANCHOR, BASE IN CITY ROW ONLY, NO STRUCTURE CUTS REQUESTED. MUST MAINTAIN A MINIMUM OF 36” SIDEWALK CLEARANCE FOR ADA/WHEELCHAIR TRAVEL. IF SIDEWALK IS AFFECTED, CALL 512-974-7161 FOR INSPECTION***
o	90 remove
o	100 BORE ONLY, NO STRUCTURE CUTS EXCEPT AS NOTED. MUST CALL FOR PREBORE INSPECTION. CALL 512-974-7161 FOR INSPECTION 1 HOUR PRIOR TO BACKFILL, BORE PITS AT STREET CROSSINGS, CONCRETE POUR, PAVING*** 
o	110 FOLLOW PUBLIC WORKS STANDARDS AND SPECS, SERIES 1100. CALL FOR INSPECTION 1 HOUR PRIOR TO EXCAVATION, BACKFILL, CONCRETE POUR, PAVING. ROW USAGE FEES OF $5.50/DAY/SWLK/DRWY/C&G AND $9/DAY/LANE ACCURE DAILY UNTIL FINAL RESTORATION***
o	120 PROTECTED STREET, FOLLOW PUBLIC WORKS NEW STREET/ENHANCED REPAIR STANDARDS AND SPECS, SERIES 1100. CALL FOR INSPECTION 1 HOUR PRIOR TO EXCAVATION, BACKFILL, CONCRETE POUR, PAVING. ROW USAGE FEES OF $5.50/DAY/SWLK/DRWY/C&G AND $9/DAY/LANE ACCURE DAILY UNTIL FINAL RESTORATION. SDRC IS DETERMINED BY STREET & BRIDGE***
o	130 remove
o	140 remove
o	150 remove
o	160 remove

Thank you!
Paloma Amayo-Ryan
Acting Transportation Supervisor/Training Specialist
512-974-2841

 
Austin Transportation Department 
Right of Way Management Division
Mail: P.O. Box 1088, Austin, TX 78767
Office: 3701 Lake Austin Blvd., Austin, TX 78703
Join our Mailing List
Call 3-1-1 to report your right of way closure
Read our new Mobility Guidelines and new Permit Conditions

**Comment by TracyLinder** [comment]
### Status

Should be ready for LIT development for Sprint 28.

**Comment by TracyLinder** [comment]
**Status:** Further analysis needed, and work to be performed during sprint 28.

**Comment by TracyLinder** [comment]
@Nadin-Nader I'm going to un-assign myself from this one & let you take lead on it. 🙏

**Comment by TracyLinder** [comment]
**Status:** Ready for development

**Comment by TracyLinder** [comment]
@Nadin-Nader I just added you as DTS Manager for this one.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Demo sent for Review on 07/27/2020

**Comment by TracyLinder** [comment]
Status: Pending review of demo sent by LIT, then promote to DEV. Updating milestone to Sprint 30.

**Comment by Nadin-Nader** [comment]
@TracyLinder @Sreelatha-BlazeKannan @SubhaShroff . I have gone over the demo and everything seems to be working and updated to what the acceptance criteria mentioned/required. 
Ready to promote to DEV.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Aishwarya having conflicts in committing the changes to DEV and tried to re-commit the same. Once this is completed will update the ticket.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder 

Created the task for CTM DevOps to commit this to DEV. Task number is SCTASK0087433

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder @aishwarya2505  Per Martin This (#1709 SCTASK0087448) has been deployed along with #2391 SCTASK0087433

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 We just tested this with the customer, and it looks great. 

### Approved to promote to Test

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Test Deployment plan to Move from DEV to TEST is been sent by AIshwarya on 08/10/2020.

**Comment by Nadin-Nader** [comment]
Deployment to TEST sent to DEVOPS CM Team to Promote from DEV to TEST (SCTASK0088971)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder @aishwarya2505 Per Martin this (SCTASK0088971) has been promoted to TEST

**Comment by TracyLinder** [comment]
Just put UAT for this on my to-do list.

**Comment by TracyLinder** [comment]
Sree will confirm if this is truly in test, then let me know when UAT can begin.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder i looked as well and found that this is on TEST:

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/06a4ffa3-b3d8-4034-9870-d3fe228cf59d)

**Comment by TracyLinder** [comment]
Per Palmoa, DTS can perform UAT on this when it's in test. Let them know when it hits prod.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan Per Martin, he will deploy this to TEST in about 5 min.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  @TracyLinder @aishwarya2505 I have tested this on TEST for the same RSN, for each folder type (EX, RW, DS) and found that the changes are correct. I approve the move to PROD @TracyLinder what do you think?

**Comment by Nadin-Nader** [comment]
@TracyLinder @Sreelatha-BlazeKannan @aishwarya2505  Per Martin, this has been deployed to PROD. I will send Paloma and Kim an email informing them that this is on PROD and that we are closing the card.

> From: Nader, Nadin 
> Sent: Wednesday, August 26, 2020 9:38 AM
> To: Perez, Kimberly <Kimberly.Perez@austintexas.gov>; Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: Conditions Pick fields for EX, DS, RW #2391
> 
> Good Morning,
> 
> Hope you are both doing well. I am reaching out to you in regards to card #2391 Conditions Pick fields for EX, DS, RW. I wanted to inform you that this has been completed and has been deployed to PROD.
> 
> If you have any questions or concerns, please feel free to email us.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services 
> Austin Transportation Department
