### ISSUE TITLE
AMANDA Report: Unpaid fees (TL)

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2392]
## **As a user i'd like the system to pull up the list of unpaid fees when i submit a query.**

**Stakeholders:** Paloma, Kim P., Ryan M.
**DTS Manager:** Tracy

**Acceptance Criteria:**
1. System should send an email to rightofway@austintexas.gov on the 1st of every month containing the ATD Unpaid Fees Report for the previous month as an attachment. This needs to be done through batch process.
2. User should be able to generate the ATD Unpaid Fees Report manually from the Reports tab in AMANDA.
3. When a user manually generates the ATD Unpaid Fees Report, they should be able to provide From and To date ranges as a parameter.
4. The report should contain any unpaid fee, billed or unbilled from the following folders:
               - DS
               - EX
               - LC
               - PSM 
               - PSM
               - ECV Folder type with subtype ATD (ONLY)
               - GF folder type with subtype ATD (ONLY)
5. The report should primarily be sorted by Folder type and secondarily be sorted by subtype and by Bill number, with unbilled fees at the end of each of folder type
6. The report needs to contain the following columns in the defined order below: 
              - Folder type
              - Subtype 
              - FolderRSN 
              - Bill Number
              - Fee amount
7. The report should also contain totals by folder type, total billed fees by folder type and total unbilled fees by folder type
8. The generated report must be of .csv format
9. The report format should look like this: 
![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/50047297-b821-4437-b529-13dacbe71796)

**Notes:**
- There is an existing report in the ATD library (56110). This query probably needs to be updated.
- If the existing fee report can't be updated to match the requirements, then once the new report has been created, the previous one (56110) needs to be removed. 
 
- Tracy has a lot of unpaid fee queries that may be useful

Per email from Paloma, see #2381

**Comment by TracyLinder** [comment]
I've got a few unpaid fee queries that can help with this.

**Comment by TracyLinder** [comment]
Is the existing report sufficient? (56110) - Analysis needed.

**Comment by TracyLinder** [comment]
### Useful query:

--V3 8/31/18 Update Unpaid Fee
select distinct  f.FolderRSN
     , abf.accountbillfeersn
     , vs.StatusDesc
     , f.indate
     , vf.FolderType 
     , vsb.SubDesc
     , vaf.FeeDesc
     , abf.BillNumber
     , (select ab.DateGenerated
        from Accountbill ab
        where abf.BillNumber = ab.BillNumber
          and rownum = 1) InvoiceDate
   , abf.FeeAmount
from Folder f
   , AccountBill ab
   , AccountBillFee abf
   , ValidStatus vs
   , Validfolder vf
   , ValidSub vsb
   , ValidAccountFee vaf
where vf.FolderType in ('DS','EX','RW', 'SCP')
  --and f.statuscode != 50005 -- Pending
  and vaf.feecode not in (50014, 50035, 50036, 50037, 50038, 50092, 50145, 50147, 50148) --DSD fees
  and f.subcode not in (50510, 50515, 50535) --street event, valet operator, parking
  and abf.feeamount > 0 
  and f.FolderRSN = ab.FolderRSN
  and f.FolderRSN = abf.FolderRSN
  and abf.BillNumber = ab.BillNumber
  and abf.BillNumber <> 0
  and vs.statuscode = f.statuscode 
  and vf.FolderType = f.FolderType
  and f.Subcode = vsb.Subcode
  and abf.FeeCode = vaf.FeeCode
  and ab.PaidInFullFlag = 'N'
  and ab.DateGenerated >= to_date ('&StartDate')
  and ab.DateGenerated < to_date('&EndDate') + 1
order by f.folderrsn;

--Unpaid Parking Fees Minus SE
select distinct  f.FolderRSN
     , abf.accountbillfeersn
     , vs.StatusDesc
     , f.indate
     , vf.FolderType 
     , vsb.SubDesc
     , vaf.FeeDesc
     , abf.BillNumber
     , (select ab.DateGenerated
        from Accountbill ab
        where abf.BillNumber = ab.BillNumber
          and rownum = 1) InvoiceDate
   , abf.FeeAmount
from Folder f
   , AccountBill ab
   , AccountBillFee abf
   , ValidStatus vs
   , Validfolder vf
   , ValidSub vsb
   , ValidAccountFee vaf
   , folderinfo fi
where vf.FolderType = 'RW'
  and f.subcode = 50535
  and fi.infocode = 83622
  and (fi.infovalue = 'No' or fi.infovalue is null)
  and abf.feeamount > 0 
  and f.FolderRSN = ab.FolderRSN
  and f.FolderRSN = abf.FolderRSN
  and abf.BillNumber = ab.BillNumber
  and abf.BillNumber <> 0
  and vs.statuscode = f.statuscode 
  and vf.FolderType = f.FolderType
  and f.Subcode = vsb.Subcode
  and abf.FeeCode = vaf.FeeCode
  and ab.PaidInFullFlag = 'N'
  and ab.DateGenerated >= to_date ('&StartDate')
  and ab.DateGenerated < to_date('&EndDate') + 1
order by f.folderrsn;

**Comment by TracyLinder** [comment]
### Another Useful Query:
--V3 8/31/18 Update Unpaid Fee
select distinct  f.FolderRSN
     , abf.accountbillfeersn
     , vs.StatusDesc
     , f.indate
     , vf.FolderType 
     , vsb.SubDesc
     , vaf.FeeDesc
     , abf.BillNumber
     , (select ab.DateGenerated
        from Accountbill ab
        where abf.BillNumber = ab.BillNumber
          and rownum = 1) InvoiceDate
   , abf.FeeAmount
   , P.OrganizationName
   , P.NameFirst ||' '|| P.NameLast custname
   , p.addrhouse ||' '|| p.addrprefix ||' '|| p.addrstreet ||' '|| p.addrstreettype ||' '|| p.addrstreetdirection
     ||' '|| p.addrunittype ||' '|| p.addrunit
   , p.addrcity ||' '|| p.addrprovince ||' '|| p.addrpostal
   , p.emailaddress 
   , p.phone1
   , fp.peoplersn
   , vp.peopledesc  
from Folder f 
   , AccountBill ab
   , AccountBillFee abf
   , ValidStatus vs
   , Validfolder vf
   , ValidSub vsb
   , ValidAccountFee vaf
   , Folderpeople fp
   , People p
   , validpeople vp
where vf.FolderType in ('DS','EX','RW', 'SCP')
  --and f.statuscode != 50005 -- Pending
  and vaf.feecode not in (50014, 50035, 50036, 50037, 50038, 50092, 50145, 50147, 50148) --DSD fees
  and f.subcode not in (50510, 50515, 50535) --street event, valet operator, parking
  and abf.feeamount > 0 
  and f.FolderRSN = ab.FolderRSN
  and f.FolderRSN = abf.FolderRSN
  and abf.BillNumber = ab.BillNumber
  and abf.BillNumber <> 0
  and vs.statuscode = f.statuscode 
  and vf.FolderType = f.FolderType
  and f.Subcode = vsb.Subcode
  and abf.FeeCode = vaf.FeeCode
    --added these two relations
  and f.folderrsn= fp.folderrsn
  and fp.peoplersn = p.peoplersn
  and fp.peoplecode = vp.peoplecode
  --added peoplecode below
  and fp.peoplecode = 1
  --and vp.peoplecode = p.peoplecode (mine pre CTM help)  
  and ab.PaidInFullFlag = 'N'
  and ab.DateGenerated >= to_date ('&StartDate')
  and ab.DateGenerated < to_date('&EndDate') + 1
order by abf.accountbillfeersn;

--Unpaid Parking Fees Minus SE
select distinct  f.FolderRSN
     , abf.accountbillfeersn
     , vs.StatusDesc
     , f.indate
     , vf.FolderType 
     , vsb.SubDesc
     , vaf.FeeDesc
     , abf.BillNumber
     , (select ab.DateGenerated
        from Accountbill ab
        where abf.BillNumber = ab.BillNumber
          and rownum = 1) InvoiceDate
   , abf.FeeAmount
   , P.OrganizationName
   , P.NameFirst ||' '|| P.NameLast custname
   , p.addrhouse ||' '|| p.addrprefix ||' '|| p.addrstreet ||' '|| p.addrstreettype ||' '|| p.addrstreetdirection
     ||' '|| p.addrunittype ||' '|| p.addrunit
   , p.addrcity ||' '|| p.addrprovince ||' '|| p.addrpostal
   , p.emailaddress 
   , p.phone1
   , fp.peoplersn
   , vp.peopledesc 
    --added these below
from Folder f
   , AccountBill ab
   , AccountBillFee abf
   , ValidStatus vs
   , Validfolder vf
   , ValidSub vsb
   , ValidAccountFee vaf
   , folderinfo fi
   --added these below
   , Folderpeople fp
   , People p
   , validpeople vp   
where vf.FolderType = 'RW'
  and f.subcode = 50535
  and fi.infocode = 83622
  and (fi.infovalue = 'No' or fi.infovalue is null)
  and abf.feeamount > 0 
  and f.FolderRSN = ab.FolderRSN
  and f.FolderRSN = abf.FolderRSN
  and abf.BillNumber = ab.BillNumber
  and abf.BillNumber <> 0
  and vs.statuscode = f.statuscode 
  and vf.FolderType = f.FolderType
  and f.Subcode = vsb.Subcode
  and abf.FeeCode = vaf.FeeCode
    --added these two relations
  and f.folderrsn= fp.folderrsn
  and fp.peoplersn = p.peoplersn
  and fp.peoplecode = vp.peoplecode
  --added peoplecode below
  and fp.peoplecode = 1
  --and vp.peoplecode = p.peoplecode (mine pre CTM help)  
  and ab.PaidInFullFlag = 'N'
  and ab.DateGenerated >= to_date ('&StartDate')
  and ab.DateGenerated < to_date('&EndDate') + 1
order by abf.accountbillfeersn;

**Comment by TracyLinder** [comment]
**Status & Next Steps:** I need to add user stories & acceptance criteria to this during sprint 26.

**Comment by TracyLinder** [comment]
**Status:** Kaarthy will finish refining this during Sprint 28

**Comment by TracyLinder** [comment]
Kaarthy, please update the acceptance criteria.

**Comment by TracyLinder** [comment]
**Status:** Still needs to be scoped. Will pull this into scoping work for Kaarthy at a later date.

**Comment by vschandramouli** [comment]
Completed acceptance criteria. Added report output type as suggested by Nadin. Ready for Backlog.

**Comment by Nadin-Nader** [comment]
@vschandramouli @TracyLinder Looked over it and its ready for Backlog. Moving to Backlog

**Comment by TracyLinder** [comment]
**Status / Convo w/ Paloma:**

- We still need a smart way to identify unpaid ROW permit fees. Not sure if the current request is what we need, but we do need a solution for this.

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader 
In the old report RW is also considered for the query. But here RW is not seen. Just want to get  the given foldertype list confirmed.

**Comment by TracyLinder** [comment]
@SubhaShroff I think this needs to be better scoped before we do anything with it.

**Comment by TracyLinder** [comment]
**Update:** V7 has made it harder to locate unpaid fees. This is still a need, though the AC will need to be revisited.

**Comment by TracyLinder** [comment]
### Priority Review w/ ROW

- Still a need for billed & unpaid
- Less important is fee added but not billed, but would be a good practice to review these fees occasionally. Staff may only want to see certain fees unbilled, for example unbilled fees on a permit that has been issued. It would help ROW catch fees that staff forgot to bill.

**Comment by TracyLinder** [comment]
@vschandramouli the AC needs to be reviewed and approved by ROW before moving to the backlog.

**Comment by TracyLinder** [comment]
This is replaced by the report created for #15434
