### ISSUE TITLE
Publish ROW data to Socrata

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2393]
See [Email : Re- ROW Permit Dataset](https://app.zenhub.com/files/140626918/b144039b-f3e0-454b-b4d8-984aa22b3ad5/download)

Per email from Paloma, see #2381

**Comment by TracyLinder** [comment]
DTS will work this one; not LIT or Jets. (Until further notice)

**Comment by TracyLinder** [comment]
This is old and will be replaced by the WZDX registry data that we are working on.
