### ISSUE TITLE
Updating AMANDA Permissions 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2394]
Per email from Paloma, see #2381 

Here’s what we need:
- Matched user rights across the different staff functions, e.g. all Permit Analysts now have the exact same rights.
- Identified six power users, which includes four staff across four separate functions and two supervisors.
- Identified users who needed to have their rights removed either because they are no longer with ATD or no longer with the City.
- We also tried to be forward-thinking and include folders such as GF and PSM.

**Comment by TracyLinder** [comment]
Changes needed docs provided by Paloma today:
[ATD Current User Righs 4-6-2020.xlsx](https://github.com/cityofaustin/atd-data-tech/files/4611378/ATD.Current.User.Righs.4-6-2020.xlsx)
[Copy of ATD Current User Rights - 5-11-2020.xlsx](https://github.com/cityofaustin/atd-data-tech/files/4611379/Copy.of.ATD.Current.User.Rights.-.5-11-2020.xlsx)

**Comment by TracyLinder** [comment]
@Nadin-Nader lets look at moving this to on-deck during the next sprint planning.

**Comment by TracyLinder** [comment]
**Status:** Pending Kim to test permissions. Then promote to PROD.

**Comment by Nadin-Nader** [comment]
Email to Kim:

> Hi Kim,
> 
> Hope you are doing well. I ma reaching out to see if you were able to test your AMANDA TEST permissions and make sure that those permissions will allow you to do all functions you need in PROD.
> 
> Please let me know when you have completed this so we can move them to PROD or make the necessary changes. 
> In the mean time I will be adding the permissions you had on TEST to DEV in order for future UAT sessions.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services 
> Austin Transportation Department

**Comment by TracyLinder** [comment]
**Status:** Next: Promote to prod

**Comment by TracyLinder** [comment]
**Status:** Get final approval from Paloma & Kim, then promote to Prod.

**Comment by Nadin-Nader** [comment]
Waiting for final approval from Kim and Paloma to move the permissions changes to PROD.

**Comment by Nadin-Nader** [comment]
Hi Kim/Paloma,

Hope you are staying safe and had a great 4th of July weekend.  I was reaching out again to see if I have your go ahead to update the user permissions on TEST and PROD. 
Paloma, I also wanted to ask you if the permissions you have on TEST are the ones you want on PROD? If so let me know and I will update PROD  for you as well.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**STATUS:** Still waiting for UAT/final approval on TEST from Kim and Paloma to move the permissions changes to PROD.

**Comment by Nadin-Nader** [comment]
From: Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov> 
Sent: Tuesday, July 7, 2020 11:42 AM
To: Perez, Kimberly <Kimberly.Perez@austintexas.gov>; Nader, Nadin <Nadin.Nader@austintexas.gov>
Subject: RE: Updated Permissions UAT #2394

Hi Nate,

Yes, please update permissions.  The permissions for TEST and PROD are slightly different (TEST is a bit more expansive in order to allow us to manipulate related folders).  Mine should mirror Kim’s.

Thanks!

**Comment by Nadin-Nader** [comment]
All Power user account have been updated on TEST and PROD will be automatically updated today after 6pm. Once that is done i will email Paloma and Kim and close the card.

**Comment by TracyLinder** [comment]
Closing this ticket. All other user permissions requests will be worked on new issues.
