### ISSUE TITLE
Ability to override DS expiration date

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2396]
### As a ROW Power User, I need the ability to manually override the DS folder expiration date. The DS parent folder may get extended 90 to 180 days and the BP Expiration Date is expiring the DS folder and it shouldnt.  

**Stakeholders:** Kim, Paloma
**DTS Manager:** Nate

**Acceptance Criteria**

- Power Users need to have the ability to manually override DS expiration date
- The DS Expiration date should be disassociated from the BP Expiration date 
- Any DS folder that is a child of a BP shouldnt follow the BP Expiration date
- When the DS Folder Expiration date is changed, it shouldnt affect the DS folder's information or status.
- If the DS folder is a child of a BP Folder, any other changes to the BP Expiration date should not affect the DS folder expiration date

**Comment by TracyLinder** [comment]
@licarir can you add a comment with your analysis of this from today's meeting please?

**Comment by licarir** [comment]
A patch to the AMANDA servers caused a JavaScript file on the server to no longer be recognized. JavaScript needs to be replace through the Admin console on the Web Interface of AMANDA. Custom features which no longer work include locking down fields on the Folder screen, the Process screen, and the Process Attempt screen. Work is being done to return those customizations. 

To include this change, we will need the Role which needs to be allowed to make this change and the folder types to allow this change on for the given role.

**Comment by licarir** [comment]
Apparently the Provider: The Jets label got removed for some reason so I wasn't seeing this on ZenBoard.

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please find out if this is still a need?

**Comment by Nadin-Nader** [comment]
Had a meeting with Kim, Ryan and Paloma and we went over the acceptance criteria for this. I explained to them that this will have to be researched to see how much the DS folder Expiration date affects the BP or the BP Expiration date. Moving to Backlog

Power Users need to have the ability to manually override DS expiration date
The DS Expiration date should be disassociated from the BP Expiration date
Any DS folder that is a child of a BP shouldnt follow the BP Expiration date
When the DS Folder Expiration date is changed, it shouldnt affect the DS folder's information or status.
If the DS folder is a child of a BP Folder, any other changes to the BP Expiration date should not affect the DS folder expiration date

**Comment by Nadin-Nader** [comment]
@TracyLinder 
**Status:**
Due to V7 Code Lockdown for this. Tracy will need to discuss with Deanna

**Comment by TracyLinder** [comment]
**Putting this back to the backlog to reprioritize on FY22 fee updates.

**Comment by TracyLinder** [comment]
This is now possible with the V7 permissions groups. Closing.
