### ISSUE TITLE
[RPP Back Office] RPP Online Application Process Follow up

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2399]
This meeting will be a follow up to clarify/review the following processes:

- [x] Ineligibility Process
What happens when a customer has submitted a application but back end review determines the address is not eligible 

- [x] Phone number? 
needs to be an email not a phone payment. Old RPP email has so much going on in it, suggesting making a new email. 
Vanessa’s phone → new admin/cashier phone. (second phone) timeline for new phone #, possible message on phone

- [x] NEW! Confirmation Status Look-up: (receive in email)
•	referencing invoice user can check status on application. 
•	New page

- [x] Clarity that mailed payments are not accepted. For historical users to let them know.

**Comment by dianamartin** [comment]
## Diana' Notes

### Ineligible Reason
- Email tell user that they are not 
- Phone, Email, In-Person

**Suggestion**: 
- Generic message, for additional information email residential parting email
- "Sorry you're ineligible", haven't updated your information properly, new resident. 
- [ ] Create new Ineligible email message to user

**Comment by moorerst** [comment]
@dianamartin on the Review Requirements page under How It Works suggest language change:

- Austin Transportation staff will review and issue applications within 10 business days or less.

 Should it say Austin Transportation staff will r**eview applications and issue permits** within 10 business days or less?

- Once your application has been reviewed, you will receive an email with payment instructions

Should it say Once your application has been **approved**, you will receive an email with payment instructions

- At the time of payment you will be able to choose your permits mailed to you or being picked
 up
Should it say At the time of payment you can choose to have your permits sent by mail or  picked up at the Parking Office.

- Button Review Requirements should have a different name because it's also where you apply.
Maybe Requirements & Apply or Requirements/Apply

- For consistency capitalize first letter on Learn **more about** and Ready **to begin**?

**Comment by dianamartin** [comment]
Created new issue for these refinements #2446

**Comment by dianamartin** [comment]
@moorerst I updated the page with your suggestions
