### ISSUE TITLE
ROW Out of System fees in Portal

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2406]
### After the out of system fees are added to AMANDA (#1951), make them payable online via portal.

**Comment by SurbhiBakshi** [comment]
Video shared with LIT and also in Google Drive.

**Comment by SurbhiBakshi** [comment]
Meeting notes in #2345

**Comment by TracyLinder** [comment]
Per Sree: Ready to move to production. Sree has sent an email w/ status and a demo.

Next Step(s): Watch demo; get stakeholder approval to move to PROD.

**Comment by TracyLinder** [comment]
@Nadin-Nader do you have time to review this demo & provide feedback to Sree on Friday, or Monday?

**Comment by Nadin-Nader** [comment]
@TracyLinder  #1951 is currently waiting for go ahead to PROD. Once the confirmation is received, this will get pulled in to add the fees and make them payable online

**Comment by Nadin-Nader** [comment]
@TracyLinder  Per Sree This issue will also be done at the same time as #1951, moving this card to Ready to Deploy pipeline

**Comment by Nadin-Nader** [comment]
Deployment has been split into two requests:

One is currently with the AMANDA CM Team in their "To-Do Pipeline" (SCTASK0073676). Waiting for the deployment and confirmation to PROD
The manual deployment was to add a lookup to PROD from DEV and TEST (51060 Lookup2=48). I was able to have Andrea from Team Tango add the lookup. SCTASK0074245 she will close this task out as it has been completed.
Copying these notes to #1951 as well

Waiting on CM Team to deploy

**Comment by Nadin-Nader** [comment]
Paloma will have users test and get back to us next week to give an update.

**Comment by Sreelatha-BlazeKannan** [comment]
It is in PROD Now.

**Comment by Nadin-Nader** [comment]
Hi Paloma/Kim,

Hope you are both doing well and staying safe. I was reaching out to you regarding the Out of System Fees #2406 and #1951 to see if you were able to gather enough information from your users UAT’ing the Out of system fees changes. Please let me know the outcome as soon as you can.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by TracyLinder** [comment]
@Nadin-Nader the comments say this is already in PROD. Wasn't UAT done before moving to PROD?

**Comment by TracyLinder** [comment]
Laura Roy is the primary user of this feature, she may not begin using it until next week (7/13)
