### ISSUE TITLE
RPP Verify Page/Form Changes

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2411]
### Eligible results:
- Show the address entered: `BLOCK_NO` - `STREET_NAME` or Knack field `ADDRESS`

"Add Max Decal" - `MAX_RESIDENTS`
"Add Max Hang" - `MAX_VISITOR_HANG_TAG_HOUSEHOLD`
"RPP Renewal Period" - `RENEWAL - PERIOD`

### Not Eligible results
-  Add language in results banner "_If you think this may be in error please email: [RPP email]_"
- [x] Made modal pop-up page for `Contact Us` that show up when you click the Contact Us hyperlink

### Additional Functionality
- [x] Have results also pull up an AGOL map that center on the address listed, showing the RPP Zones on the street.

### Phase 2 Functionality
- [ ] Have map find address and also notates if address has permits purchased on it or not

**Comment by moorerst** [comment]
@dianamartin really like the changes you have made so far on the eligibility look up

**Comment by dianamartin** [comment]
## Map Embed
Got the map url to show up on results, can't figure out how to transfer information into iframe.

### iframe code
iframe src="" id="map_url" name="map_url" scrolling="no" marginheight="0px" marginwidth="0px" allowfullscreen="" width="750px" height="500px" frameborder="0">
</iframe

add `<` and `>` at the beginning and end of this line of code

**Comment by dianamartin** [comment]
John and I sync'd up and he got it working yesterday, 5/5/2020.
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/1f723bb8-2f86-4ee8-908a-34e0b555c563)

Yunuen is updating a more simplified web map/app.

**Comment by moorerst** [comment]
@dianamartin this is cool!!!

**Comment by dianamartin** [comment]
- [Test Web Map](https://austin.maps.arcgis.com/home/webmap/viewer.html?webmap=f4db543205b14437a88c4d997e3fccfa)
