### ISSUE TITLE
[RPP Back Office] Eligibility Lookup Verification Process

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2412]
We’re going to meet with stakeholders to discuss the existing RPP Eligibility look up process and see how we can streamline the process for users so there is better clarity on determining RPP eligibility.

**Comment by dianamartin** [comment]
## Diana's Notes
How often do you create new zones/add new address?

UPDATE: 
update pretty regularly (Ryan R.)
Built of an existing area, add additional blocks. 

DECISION: 
Verify by Address
- Show the address entered: BLOCK_NO - STREET_NAME
"Add Max Decal" - MAX_RESIDENTS
"Add Max Hang" - MAX_VISITOR_HANG_TAG_HOUSEHOLD
"RPP Renewal Period" - RENEWAL - PERIOD

Non eligible: 
Add language: Email the RPP staff to 

Map zooms into area showing address

Phase 2: Permits at the address
Purchased for this address

Estimate the level of effort
- off the bat

Historical data in the spreadsheet?
