### ISSUE TITLE
Document Parking Data Migration Method

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2421]
Need to document the new schema, how the layers/table relationships work, editing in Pro, etc. to prepare for handing this off to Yunuen.

**Comment by johnclary** [comment]
Bumping to Sprint 25 :)

**Comment by johnclary** [comment]
Moved data to maint. @jaime-mckeown please put your parking schema documentation on gitbook. thanks :)

**Comment by jaime-mckeown** [comment]
Created some documentation for Parking Project on GitBook. 
https://app.gitbook.com/@atd-dts/s/atd-geospatial/parking-inventory

**Comment by jaime-mckeown** [comment]
- After moving the data to maint, I needed to get it setup with the relationships, privileges, etc. Finally got everything working and figured out how to do admin via Pro as it's kind of different.
- Sent Yunuen an email with a link to the documentation and to the Project so she can get familiar with it before we start talking about the project in great details so she can take it over.
