### ISSUE TITLE
Add Hourly Rates to COVID-19 Tracking App Employee Object

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2424]
We have been requested to add employee hourly rates to the COVID-19 Time Tracking app. This information should display in the Review Time Logs section, the Employees section, and the actual HSEM export.

This information should be available via Banner.

**Comment by JaceDeloney** [comment]
@dianamartin Can you start on this using fake data until the actual data is pulled in?

**Comment by amenity** [comment]
@johnclary has a script that will put this into a CSV.

**Comment by amenity** [comment]
- Pull in the data
- Add column to Employee object

(Will be a one-time data pull - won't be dynamic)

**Comment by dianamartin** [comment]
@johnclary I'll wait on you to tell me the name of the Field Headings if you're able to get the data from Raul.

**Comment by dianamartin** [comment]
@johnclary what's the status on this? Did you get a response from Raul about the new field we were needing?

**Comment by amenity** [comment]
Got pushback on this... @johnclary - will you ask Peggy for a response on this?

**Comment by johnclary** [comment]
Spoke with Peggy and followed up with Raul (HRD). Waiting to  hear back. Bumping to  Sprint 25.

**Comment by amenity** [comment]
@JaceDeloney is going to ask about this when he emails Gilda about some other items. Might go to the backlog...

**Comment by johnclary** [comment]
We're not doing this.
