### ISSUE TITLE
Meet to discuss child record workflow implications/approach

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2426]

**Comment by SurbhiBakshi** [comment]
Notes from meeting on 04/27 - 

- [ ] Create an issue to copy assignments in monthly batches by script. Assign to John.

- [ ] Include a field in the Assignments (Officer interface) with either badge number or officer name to show that officers signed up for that assignment. Also include that information in the details link, in the form of a table? 

- [ ] For school closures in AISD, create a field in the Locations object to show if school closure is in the current year. Calculate that field once a year, and then filter out the location drop down based on that.

**Comment by SurbhiBakshi** [comment]
@amenity - l can update you on the discussion from this meeting when you get a chance.
