### ISSUE TITLE
Create "ATD Acronyms" in Staff Resources wiki

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2427]

**Comment by amenity** [comment]
Create a new top-level page in the ATD Staff Resources with what you have and follow up with Susanne H. about any she might include.

**Comment by SurbhiBakshi** [comment]
Wrote to Susanne H

**Comment by SurbhiBakshi** [comment]
[List](https://atd-dts.gitbook.io/atd-staff-resources/) is in Wiki

**Comment by SurbhiBakshi** [comment]
@dianamartin can you review this please before I close it? link above

**Comment by dianamartin** [comment]
@SurbhiBakshi The acronym page looks good! Maybe we should great a group section called `Other Resources` or something?

**Comment by SurbhiBakshi** [comment]
thanks @dianamartin, the group section sounds good to me.
