### ISSUE TITLE
Document where to check statuses of the various tech we depend on 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2428]
E.g. AMANDA, Github, Knack

**Comment by amenity** [comment]
Add to Knowledge Base so that Level I support has it handy when they're on rotation.

**Comment by dianamartin** [comment]
@SurbhiBakshi I created a [page](https://app.gitbook.com/@atd-dts/s/dts-service-desk-knowledge-base/~/drafts/-M66I9qyihw4mSgBLzLh/dts-service-desk/application-status-page) in the service desk wiki

**Comment by SurbhiBakshi** [comment]
@dianamartin thanks!
