### ISSUE TITLE
Service Request: GIS and Maps 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#244]
@jaime-mckeown - @TracyLinder and I are working on the DTS service request process. Would you add the information you want to get for any map [request to the Google doc](https://docs.google.com/document/d/1hYIp2gMbeukzTsu7GF--mLwwKyQIE5FLtrKQZI0A5gY/edit#heading=h.velkvky0qrcf)?

**Comment by amenity** [comment]
@jaime-mckeown - @johnclary got your form set up [here](https://atd.knack.com/dts#new-service-request) (click "GIS or Maps"). Please check and let us know if you need changes.

**Comment by jaime-mckeown** [comment]
@amenity the form looks good, I think that should cover what we need. Giving users space to describe what they need usually works best with GIS requests as they are all different.

**Comment by amenity** [comment]
Great, thanks! /cc @johnclary
