### ISSUE TITLE
VZD: Changes to comprehensive cost calculations

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#2441]
These changes have to be tested and applied to both production and staging:

- Crashes Trigger `atd_txdot_crashes_updates_audit_log` has been updated to run an updated formula that accounts for unknown injuries.

- In the lookup table `atd_txdot__est_comp_cost` the value for `None` has been update from `0` to `51000`

- The trigger was also updated to count from `death_cnt` from CRIS as opposed to using the `apd_confirmed_death_count` field, namely for the two columns: `est_econ_cost` and  `speed_mgmt_points`

Two scenarios that need testing:
- If there are two possible injuries, the totals should be $466k
- If there are two unknown injuries, the total should be $102k

**Comment by sergiogcx** [comment]
Made an initial implementation, and I've run a series of tests. Will double check with Xavier and see if these are the numbers he is looking for to confirm the formula is now correct.

![2020-04-22_17-08-35.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/098bb5ad-9e9a-42c2-96b9-f3fb8964b5ef)

![2020-04-22_16-39-28.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/25e13126-f921-476f-9894-5566de1a3682)

![2020-04-22_17-18-30.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/1157522e-a71e-441d-8620-d4afb4808238)

**Comment by xavierapostol** [comment]
@sergiogcx Yes, these calculations look correct for Comprehensive costs (you're title says economic cost)

**Comment by sergiogcx** [comment]
There is a pull request to document the changes in the database:
https://github.com/cityofaustin/atd-vz-data/pull/769

Pending:
- [ ] Disable all triggers for the crashes table
- [ ] Update production trigger
- [ ] Update cost values
- [ ] Verify cost values
- [ ] Re-enable triggers

**Comment by sergiogcx** [comment]
The costs have been tested, and all updated in production and staging @xavierapostol 

![2020-04-28_21-09-57](https://user-images.githubusercontent.com/5282430/80555090-d16d7c80-8994-11ea-9ed2-d9d53cac19f4.png)

Closing this issue for now
