### ISSUE TITLE
 Meeting | ROW -DTS - LIT Permit Templates

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2453]
Meeting to go over ROW templates that need some changes.

**Comment by SurbhiBakshi** [comment]
Sree still has issues with not being able to see data and can't test.

**Comment by SurbhiBakshi** [comment]
[Meeting notes ](https://docs.google.com/document/d/1QHF0_UmMQ2sFm6UL8wMnL1vZTMLZ-YOR4WV5e3K2irk/edit?usp=sharing)

**Comment by SurbhiBakshi** [comment]
@Nadin-Nader - if you want to add meeting notes, here is the issue.

**Comment by Nadin-Nader** [comment]
----Permit Templates Meeting 4/24/2020---- LIT IS WORKING ON THIS ----
Sreelatha, Surbhi, Paloma

DS Folder, year 20 Random folder
Residential or Commercial
Print Button > select 50506
DS: 
- [ ] No issues with Header, Legal description field (needs to verify to see if needed or what its for) 
- [ ] Proposed Occupancy should say Description;
- [ ] Needs Wording changed to something more structured
- [ ] Comments renamed to Conditions
- [ ] Canned verbiage at the bottom needs of template changing
- [ ] Page to be added as last page with the outline of all Standard Permit Conditions (link takes you to document with Standard Conditions; remove link)

EX Permit - 
All changes on EX template, Sree confirmed that with Paloma. EX template has been shared by Paloma with us and Launch IT.

- [ ] Add a page to EX permit to show conditions. Like DS Permit??
- [ ] Also make sure Est Completion date pulls from the Expiration Date.

RW Folder, year 20 Random folder
TURP Private Long Term SubType
Print Button > select 50511
RW: 
- [ ] Header is different on screen vs print out (one has COA and department) need to make it, add box frame to all of the fields, 
- [ ] Remove ROW Seal, Change Original End Date to Original Expiration Date, 
- [ ] Change Extension End Date to Extension Expiration Date, Abbreviate Extension to "Extn", 
- [ ] Add a comments field at the end of the Permit Details table

RW Folder, year 20 Random Folder
Film Parking 
Print Button > select(50509) 
- [ ] Need Start and End date

RW Folder, year 20 Random Folder
Parking Spaces 
Print Button > select(50512)
- [ ] Make uniform and neat, Comments Column is not populating, , Change End Date to Expiration Date
- [ ] EX and RW DO NOT HAVE FEE Description section on DS Permit
- [ ] Alignment issues on RW TURP and some DS

**Comment by amenity** [comment]
Sree started working on this. 
There is also a video for this issue.

**Comment by amenity** [comment]
#1893 for next steps.
