### ISSUE TITLE
B-Cycle dataset update frequency - check

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2457]
From #2280
 Need to check on the update frequency for the B-Cycle dataset.

**Comment by SurbhiBakshi** [comment]
[Austin B-Cycle Trips ](https://data.austintexas.gov/Transportation-and-Mobility/Austin-B-Cycle-Trips/tyfh-5r8s) how often is the data updated, as per email it's every 60 min, not sure this is accurate at this point. ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/f8661306-76a8-4aec-8d45-aa5f687519ba)
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/eb5ffbf5-c17a-4c0c-8b1f-b657ff5281c9)

**Comment by johnclary** [comment]
@SurbhiBakshi the B-Cycle publishing script attempts to update the dataset on a nightly basis. However, the source data files are only updated on a monthly basis. Whenever a new data file is uploaded to Dropbox by B-Cycle, our script will pick it up. However, B-Cycle staff do not consistently provide the new data files in a timely manner, and our program staff must reach out to them and ask them to upload the latest data. 

Closing. See also: https://github.com/cityofaustin/atd-data-tech/issues/1419

**Comment by SurbhiBakshi** [comment]
thanks @johnclary! will update the Wiki to reflect that.
