### ISSUE TITLE
Service Request: Data or Report

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#246]
@jaime-mckeown @johnclary @dianamartin @TracyLinder 
@TracyLinder and I are working on the DTS service request process. Would you add the information you want to get for any map request to [the Google doc](https://docs.google.com/document/d/1hYIp2gMbeukzTsu7GF--mLwwKyQIE5FLtrKQZI0A5gY/edit#)?

**Comment by johnclary** [comment]
This is handled by the "Something Else" category now. Closing.
