### ISSUE TITLE
Various updates to AMANDA TIA folder 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2462]
These aren't critical, but now that TDSD has been working in this folder we have gathered a list of refinements:
- [ ] Update AMANDA TIA folder with more meaningful and defined folder statuses. 
- [ ] Update the TIA folder to have issue & expiration
functionality.

**Comment by TracyLinder** [comment]
These needs have been captured as user stories, and each have an issue in the backlog. Closing this issue.
