### ISSUE TITLE
RPP UI enhancements

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2467]
## Show permit error message before user has to click `submit`
- [ ] have banner pop-up once information is entered, so user doesn't have to submit for the error banner to be triggered

We'll need to create client side form validation similar to what currently occurs on submit. Those rules are attached in a screeenshot below, thanks @dianamartin. 

The intent is that:
- if `hang_tag_count + resident_decal <= 4`:
   -  no banner
- if `hang_tag_count + resident_decal > 4`:
  -  show banner with text "The total amount of decals and hang tags cannot exceed 4"

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/773e48f5-d9eb-4230-b752-908d468e5344)

**Comment by dianamartin** [comment]
@mateoclarke 

## Form Validation
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/fb531ddb-d2a1-46e2-8c42-45a44639a53d)

**Comment by JaceDeloney** [comment]
@dianamartin Just wanting to verify that requirements are still being finalized for this?

**Comment by dianamartin** [comment]
@JaceDeloney @mateoclarke I think we agreed that we'd move forward with "Show permit error message before user has to click submit". 
@johnclary : correct me if I'm wrong here.

**Comment by johnclary** [comment]
Yes. the description looks correct. @dianamartin would you move the address validation piece of this to a separate issue? it's a bit more complex than i initially thought because it will need to use the permit application object rather than the "verify" object that we use for the other lookup interface.

**Comment by dianamartin** [comment]
@johnclary Created new issue #2711

**Comment by ChrispinP** [comment]
i have added page and field validation for number of permits. Is having a warning message appear based on selection rather than submission something we still want?
