### ISSUE TITLE
Re-pull CRIS crash data for 5 records

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2468]
We need to update the crash tables for a few records because we're not reflecting the latest injury severity status. Currently updates do not get reflected in the crash table, but the secondary tables do get updated. This will change once the crash change process is implemented.

Re-pull the CRIS data for the following records:

**Crash ID             Case Number**
16991949          190930132
17168802          191880028
17309090          192650413
17351089          192830834
17343328          192861035

**Comment by sergiogcx** [comment]
I may need to do this for more records than these, marking now as in-progress.

**Comment by sergiogcx** [comment]
The records have been re-inserted. I also found a piece of code that was preventing death_cnt from being updated on upsert, changed it and fixed the bug here:

https://github.com/cityofaustin/atd-vz-data/pull/786
