### ISSUE TITLE
Uploading or taking an image in Work Order Details view is broken

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#2474]
When uploading or taking an image from the Work Order Details view in the Images tab, the image uploads to Knack successfully, but it does not associate with the Work Order record properly. The image record in Knack does exist.

@dianamartin - feel free to add any details from Toby.

#### Knack image record (should be associated with WRK20-082190)
<img width="1204" alt="Screen Shot 2020-04-27 at 6 13 24 PM" src="https://user-images.githubusercontent.com/37249039/80429916-cb9f6a80-88b2-11ea-9c37-8d867258a2d7.png">

**Comment by dianamartin** [comment]
## 4/28 Yesterday's observations

Toby called in the afternoon saying that he'd been trying to use the AMD mobile data tracker UI. Then proceeds to say he's been trying to upload a photo from something he took in the field. Every time he browsed, selected the file and clicked the `upload` button. The image wouldn't show up on the work order he was trying to attach it to. 

It didn't occur to me to check the back end until after I got off the phone with him. When I talked to Mike he said the files were attaching to Knack. I checked the object table and then I saw all the attempted photos Toby had tried, plus my 2 attempts. All of them had images, but the `Work Order ID` was blank. This was the reason why the photos weren't showing up. 

I deleted the images that were testing and duplicates and associated the WO ID number that he was trying to work on an related the image to it. 

Mike is still looking into why this behavior happened. I noticed that it only started on 4/27. 
![image](https://user-images.githubusercontent.com/21112975/80499948-32646880-8933-11ea-8330-1e4bd89e1b71.png)

**Comment by mddilley** [comment]
After taking a look at the application code, the app was found to be POSTing the new image record association to `scene_255` and `view_2234`. When looking at this API view in the test instance of Data Tracker, the column for `work_order` (`field_1045`) was missing so Knack was ignoring the record ID in the POST request. 

After adding this column (`field_1045`) to the test and production instance API views, the image upload feature was tested and images associated with their records successfully.
