### ISSUE TITLE
Disable Knack breadcrumbs & back button link

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2477]
### Disable breadcrumbs 
When a user is filling out an application Knack creates breadcrumbs to those pages. It the user click on the breadcrumb hyperlinks without reaching the `review` page, the information they entered will be cleared out. 

If we can disable the user from being able to navigate back to those pages and keep moving forward that will help. 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/de361aa2-899d-445e-999a-34b312414bea)

We have edit buttons for users to edit their information from the review page

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/5797bc08-f2f9-4911-8dc5-7e84bc150ec9)

### Disable back button links
When a user is filling out an application Knack, Knack automatically creates link to return to previous form pages. Problem is if user clicks on the breadcrumb hyperlinks without reaching the `review` page, the information they entered will be cleared out. 

If we can disable the user from being able to navigate back to those pages and keep moving forward that will help and or hiding it (similar to what we did for Signs and Markings) that would be fantastic.

**Comment by dianamartin** [comment]
App Name: [Residential Parking Permits](https://atd.knack.com/parking#rpp/)
Start Application [Here](https://atd.knack.com/parking#apply/)
`Apply`: scene_3
`Permit Information`: scene_13
`Required Docs`: scene_123
`Review`: scene_176


**Test**
Go through application before submitting, click on breadcrumb and it'll wipe our form information out. Ultimately, we want the user to continue forward because at the `Review` page the user has the opportunity to edit their information.

**Comment by mateoclarke** [comment]
@dianamartin, I've updated the scenes. Can you check to make sure I covered it as expected?

Breadcrumb links only work for admins. I used CSS to disable the backlinks in the footer so they are removed regardless of the user type.

Where does RPP code versioning live?

**Comment by dianamartin** [comment]
@mateoclarke The code live [here](https://github.com/cityofaustin/atd-knack/blob/master/code/residential-parking-permits/rpp.js). I just updated the version in GitHub this morning bc I had forgotten to add it since I added the map embed js. Is your code already in the PROD Knack environment?

**Comment by dianamartin** [comment]
@mateoclarke Just testing the Resident application and I see it's working as intended, the breadcrumbs are disabled and the back button on the bottom is gone. ::thumbs up::

**Comment by mateoclarke** [comment]
Thanks @dianamartin. The code has been merged to atd-knack.
