### ISSUE TITLE
Make fields (in Portal)  needed to calculate Temporary Valet Permit Fees mandatory.

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2478]
From #1291 - Kim would like to see that the fields needed to calculate the fees be made mandatory in Portal.

**Comment by SurbhiBakshi** [comment]
When applicants fill out an application in Portal for a Temporary Valet Permit, fields needed to calculate fees are not mandatory. These need to be mandatory.

**Comment by TracyLinder** [comment]
Infos to make mandatory: Number of Days Requested, Number of Spaces

**Comment by TracyLinder** [comment]
Per @Nadin-Nader related issues: #1946 and #1525 
This might be a duplicate. 
@TracyLinder - Look at dupes.

**Comment by TracyLinder** [comment]
This is a duplicate. Closing.
