### ISSUE TITLE
Automate monthly micromobility trip reports

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2488]
We need to automate the creation of the monthly micromobility trip reports. 

All providers should be included in the report. The fields included in the report should be:
- provider name
- total trips
- total trip miles
- trip length avg
- trip duration avg
- trips zero distance
- trips long distance

These reports will need to be pulled into the Reports section of the Dockless Mobility Operations [prototype](https://atd.knack.com/dockless#home/) in Knack. We will need to talk to @SurbhiBakshi about the best format and process for getting these reports automatically updated in Knack.

**Comment by sergiogcx** [comment]
We are going to be discussing this on Thursday, will put on-deck.

**Comment by sergiogcx** [comment]
As a few ideas:
- [ ] E-Mail report via Airflow
- [ ] Create a mini-website that can provide such reporting.

**Comment by sergiogcx** [comment]
I have created the view that will feed the data into the ETL, and in turn the ETL will insert records automatically into Knack.

I have all the details I need to start making insertions from the ETL into knack in terms of the object name and field names. Work will begin in the ETL shortly.

**Comment by sergiogcx** [comment]
The code has been merged to Airflow, and it should post data go knack every 3rd day of every month:
https://github.com/cityofaustin/atd-airflow/blob/master/dags/atd_mds_monthlyreport_production.py
