### ISSUE TITLE
Implement Google Analytics

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2489]
As an admin, I want to know how many people are visiting the Vision Zero Viewer. We should implement web analytics so that we can see usage patterns.

Add Google Analytics to Vision Zero Viewer.

Provide a list of views and events that we want to track:
- Number of visitors to VZV
- Number of users that select the Summary button
- Number of users that select the Map button
- Number of uses that select the fatalities filter
- Number of uses that select the serious injuries filter
...

**Comment by mddilley** [comment]
https://github.com/segmentio/analytics-react

**Comment by mddilley** [comment]
https://medium.com/javascript-in-plain-english/google-analytics-with-react-router-and-hooks-16d403ddc528
