### ISSUE TITLE
VZV | Map | Crash point popup does not always render its full width within the viewport

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#2491]
When a crash point is tapped on a mobile viewport, the popup with the info box does not always render with its width 100% viewable in the viewport. Although this is the expected behavior for Mapbox GL popups (see http://visgl.github.io/react-map-gl/examples/controls), it would be nice to have the info immediately viewable instead of the user needing to dragging the map towards the popup.

#### Popup in VZV Map mobile view
![image](https://user-images.githubusercontent.com/37249039/80618367-e71c8980-8a08-11ea-8f5e-e02645184f82.png)

#### Problems to avoid (static info box covering map controls and popup not rendering within viewport)
![image](https://user-images.githubusercontent.com/37249039/80618776-7033c080-8a09-11ea-8bbb-c28190d0ba76.png)

**Comment by mateoclarke** [comment]
An alternative approach could be to have a summary box positioned in the bottom in a fixed position. Similar to the way it behaves on desktop in the top left.
