### ISSUE TITLE
DTS Discovery Day v3 🚀

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2493]
This epic compiles projects for [DTS' Discovery Day on May 1, 2020](https://docs.google.com/presentation/d/1aSqnnvi3XG2njeU7Zbsc23ZEe96VSHUDyxPjrB6O5D0/edit?usp=sharing). Please add a Github issue to capture what you plan to work on!

Here's a template you can start from if you'd like: 
### Challenge or Solution
What is the problem you want to solve or solution you want to explore? 

### Prerequisites
Software, data, getting a local dev environment set up, etc. 

### Deliverable
Everyone will have three minutes to present their work (with the option to save the recording) and a slide in the Discovery Day presentation deck. Are there any other artifacts you want to walk away with? Wiki pages, a prototype, etc.

**Comment by mateoclarke** [comment]
[Retro Notes here](https://docs.google.com/document/d/1gv6569KdS3t37zpd2op8byXKA0NA9KbMXs3oOQWBXXo/edit?usp=sharing)
