### ISSUE TITLE
Monthly Trips Reporting Table in Knack

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2494]
Add a new section to the Dockless Mobility Operations [prototype](https://atd.knack.com/dockless#home/) that allows users to view reports. The first report that needs to be displayed is the monthly trip report. The data from the monthly trip reports will come from the work completed in [2488](https://github.com/cityofaustin/atd-data-tech/issues/2488).

**Comment by amenity** [comment]
They want a CSV since numbers on these reports are not always correct; have to reconcile data from various sources.

**Comment by amenity** [comment]
Typically we handle this as a Python script being pulled into Knack; can start by building the report UI in Knack with uploaded data.

**Comment by JaceDeloney** [comment]
I have shared example trip reports with @SurbhiBakshi. Each monthly trip report entry should include data for each active provider for the following fields:
- total trips
- total trip miles
- trip length avg
- trip duration avg
- trips zero distance
- trips long distance

Zero values should be included for providers without any trips for that respective month.
