### ISSUE TITLE
Round 2 of usability testing

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2495]

**Comment by moorerst** [comment]
Testing scheduled with the 5 original testers
Cari Buetow 5/12 4:00
Andrea Martinez 5/13 10:00
Daniel Brooks 5/14 10:30

Will be using the same testing plan as round 1 of testing

Kelsey Vizzard 5/14/ 1:00
Tien Tien Chan 5/14 3:30

**Comment by moorerst** [comment]
Updating the testing documents for round 2 of usability testing
Test Script
Scoring Matrix
Testing Notes document

**Comment by dianamartin** [comment]
Dan couldn't make his usability testing on 5/15. He offered to reschedule, but we had a lot of feedback. We asked if he could take a look on his own and provide feedback by mid week next week.
