### ISSUE TITLE
"Getting Started" page for Level I Support

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2498]
Basics of what to do when you get on shift, sign off, etc.

**Comment by dianamartin** [comment]
Page has been created

**Comment by dianamartin** [comment]
@SurbhiBakshi Can you review this [page](https://app.gitbook.com/@atd-dts/s/dts-service-desk-knowledge-base/dts-service-desk/getting-started) and see if I'm missing anything else.

**Comment by SurbhiBakshi** [comment]
@dianamartin the 'Getting Started' page looks good. Did not really get into the links from the Getting Started page. Did you want me to look at those as well? A little hesitant about putting Skype in there, since it will go away by the end of this year.

**Comment by dianamartin** [comment]
@SurbhiBakshi yeah, we can always pull it out when it sunsets.
