### ISSUE TITLE
To KnackCon or Not to KnackCon

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#250]
[KnackCon](https://www.knack.com/Knackcon/chicago2019) is October 2-4. 

Main event tickets cost $550. Buy two get two free, per Steve:

> Conference: If you are interested in purchasing 2 main event tickets and are willing to help in a panel discussion or similar session during the conference, we would be happy to offer you 2 additional free main event tickets. (For reference, Main Event includes full day Thursday and first part of the day Friday).

**Comment by amenity** [comment]
Buy one, get one free. See #388
