### ISSUE TITLE
VZV performance audit

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2505]
Use Google lighthouse to perform a performance audit. High performance improves search ranking. Also could use: https://www.webpagetest.org/

Timeblock audit and fix to 4 hours

**Comment by sergiogcx** [comment]
Initial Observations:
https://docs.google.com/document/d/18dh-HlDCfpHk_dJG6vBN5GDMXlAhAWC5bMRZjh9Ghcg/edit?usp=sharing

**Comment by sergiogcx** [comment]
Closing.
