### ISSUE TITLE
Applicant paid TDSD Review fee missing in Amanda

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2510]
Sangeeta had an applicant contact her with a receipt for a TDSD fee. She can't find the fee in Amanda as paid. She has put in a ticket, but would like to get that prioritized so it is addressed quickly.

**Comment by SurbhiBakshi** [comment]
@Nadin-Nader has contacted CTM regarding this issue.

**Comment by Nadin-Nader** [comment]
Sent an email to Team TANGO at CTM asking them to Expedite INC0037350 that Sangeeta sent to their Queue. 
Deb (Scrum Master) informed me via email that Swapna will be looking into this. Swapna is hoping to get to it today, if not she will get to it Tomorrow.

**Comment by TracyLinder** [comment]
Per Nate, the fist payment confirmed failed by Swapna. The customer tried a second time and was successful.

**Comment by TracyLinder** [comment]
The customer followed up today to clarify that this issue was not resolved. More info about final resolution can be found in this [email correspondence.](https://github.com/cityofaustin/atd-data-tech/files/4577234/INC0037350.Resolution.pdf)
.

**Comment by amenity** [comment]
Helpful context from @TracyLinder:

>Some background on this will be useful for you. Sometimes when a customer makes a payment online via the AMANDA portal, a situation can arise where the payment is successful but the fee in back office doesn’t ever update as paid.
> 
> This scenario is referred to as an RPTC payment failure. When it happens the system does catch it, captures information about the failure, and emails a distribution list with the info. I am on that list however I get anywhere from 20-200 of those notifications daily, the bulk of the failures are DSD fees, and many days I don’t find time to comb through the emails looking for ATD specific failures.
> 
> Dan V. with ATD finance is one of the few people capable of resolving these issues as they pop up, and he’s usually very responsive. It also usually requires some action from the person who created the fee; they first need to go into the folder and clear up whatever issue is causing the payment to fail. Then Dan is able to back-date a payment manually.
> 
> Last, but certainly not least, I have made some progress with getting other portal participating departments to agree to assign a finance SPOC to portal finance issues, and to streamline how the city responds to these failures as much as possible, so this is a developing issue._

**Comment by TracyLinder** [comment]
Thank you @amenity for pasting that. I have good intentions to add it to the DTS wiki, since it's a reoccurring issue for us.
