### ISSUE TITLE
Add REQUEST SOURCE Field to Traffic Signal and Pedestrian Signal Requests Feature Layer on AGOL from Knack

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#2513]
I asked John how I would get a field from Knack added to the feature layer, his response:

> yeah, so, work with surbhi or diana to identify the knack database field names that you want to add. once they give you the real database fieldnnames, you can edit the feature layer on AGOL and add the columns. once you do that, diana/surbhi will need to update the Knack API endpoint to include those fields. and then ping me and i’ll refresh the data

Thanks!

**Comment by amenity** [comment]
@jaime-mckeown - @dianamartin and @SurbhiBakshi an help you out with this. Will sync up with you shortly.

**Comment by dianamartin** [comment]
Got with Jaime and confirmed which table `Signal to add the `Resource Source` to. She added the field to the AGOL `Traffic Signal and Pedestrian Signal Requests` data set.

**Comment by dianamartin** [comment]
@johnclary Do you need to refresh the data set then? [Wiki](https://app.gitbook.com/@atd-dts/s/atd-knack-operations/~/drafts/-M7P9BOtWa27v-F8hiMj/knack/arcgis-online-integration)

**Comment by johnclary** [comment]
@dianamartin you can just do a batch update in the Knack builder to set the modified date to the current datetime. I updated the documentation accordingly, [here](https://app.gitbook.com/@atd-dts/s/atd-knack-operations/knack/open-data-portal-socrata-integration)

**Comment by dianamartin** [comment]
@johnclary If I update the Modified Date, won't we loose the last time a user has last modified a record? It'll be buried under the audit field history.

**Comment by johnclary** [comment]
would double-check with renee that this won't be an issue? if it is, we can run it manually, but it's actually a little tedious to do this and would be nice to have a non-dev option available to us.

**Comment by dianamartin** [comment]
Renee said that she was fine with use batch updating it. I'm going to download a copy so we have a back up of the last time they modified the records and email it to Renee and Andres.

**Comment by dianamartin** [comment]
- I batch updated the `signal_requests` object table and updated the `MODIFIED_DATE` to 5/21/2020, all 788 records. 
- Emailed users the backup copy of the signal requests records

**Comment by jaime-mckeown** [comment]
Does that mean all records have a modified date of today?

**Comment by dianamartin** [comment]
@jaime-mckeown Yes, this was just updated. I have a back up of he Modified Dates in case we needed it for some reason.

**Comment by jaime-mckeown** [comment]
I was using that field to filter out PHB requests that have been modified in the past 12 months for the Data Driven PHBs. I won’t be able to see which records to filter out.

**Comment by dianamartin** [comment]
@jaime-mckeown Here's the [back up copy of the Signal Request records](https://app.zenhub.com/files/140626918/95d8fd5c-773d-429e-9580-ee9a957f5989/download) so you can filter them out by `Request ID`.

**Comment by jaime-mckeown** [comment]
That doesn’t help me in the future when we update the data to run the process again. I will ask Renee if they want to change the parameters and just select all records with a specific status, disregarding the modified date.

**Comment by johnclary** [comment]
Yes, the modified date is probably not the best field to use for that filtering. Hopefully Renee suggests some combination of status and request date. Let us know what you hear.

**Comment by jaime-mckeown** [comment]
@johnclary I'm glad we found out now that the modified date field can be modified for other reasons then AMD updating a record. I will work with Renee to change this selection. Thanks
