### ISSUE TITLE
Discovery Day v3 | Setup an Enterprise GIS Server Environment for ATD

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2519]
### Challenge or Solution

ATD is unhappy with the performance of CTM's enterprise GIS servers; we would like our own dedicated editing environment for our GIS data. I will explore the possibility of using our favorite database tech, PostgreSQL, in combination with our favorite cloud service, AWS, to host our necessary evil, Esri's ArcGIS Server and ArcSDE. 

I will start by using Amazon EC2 and RDS, but time permitting will explore a Docker instance of ArcGIS Server.

### Prerequisites
- [x] ArcGIS Server License
- PostgreSQL instance on AWS
- AWS Virtual Private Cloud
- AWS EC2 Instance and/or Docker w/ AWS Fargate

### Are there any hurdles you foresee? How might we address them?
- Esri says they support PostgreSQL for ArcSDE, but I suspect the configuration and installation may be challenging.

### Deliverable

If successful, we will be able to demo how data in our database can be edited in ArcMap on a desktop computer.

**Comment by amenity** [comment]
@johnclary - do you want to close this guy?
