### ISSUE TITLE
transportation-data-utils: Test deployed packages

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#252]
We will need to test all packages once deployed, both dev or master (production). See epic #191 to find out which packages need testing (all in that list).

- [x] atd-agol-util
- [x] atd-args-util
- [x] atd-data-util
- [x] atd-email-util
- [x] atd-jobs-util
- [x] atd-kits-util
- [x] atd-knack-util
- [x] atd-log-util
- [x] atd-socrata-util

**Comment by sergiogcx** [comment]
✓ atd-agol-util

![Screen Shot 2019-06-21 at 2.36.03 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/eb1c6bb0-5b86-497c-813e-4a6cf39f5bed)

**Comment by sergiogcx** [comment]
✓ `pip install atd-args-util`

![Screen Shot 2019-06-21 at 2.37.54 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/c6ed5d51-268f-483d-a6d1-6eb744f8f8d5)

**Comment by sergiogcx** [comment]
✓ `pip install atd-data-util`

![Screen Shot 2019-06-21 at 2.40.53 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/e493913e-2e2c-40c0-8056-a2a2e8171cde)

**Comment by sergiogcx** [comment]
✓ `pip install atd-email-util`

![Screen Shot 2019-06-21 at 2.42.24 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/20ea6698-641b-4ce6-bb10-960db1db4a3f)

**Comment by sergiogcx** [comment]
✓ `pip install atd-jobs-util`

![Screen Shot 2019-06-21 at 2.44.13 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/e5a5f4ac-06fe-43ff-806b-377988456cbc)

**Comment by sergiogcx** [comment]
✓ `pip install atd-kits-util`

![kitsutil.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/23f47ea9-d46f-4050-ad96-37c92c0fbbe7)

**Comment by sergiogcx** [comment]
✓ `pip install atd-knack-util`

![Screen Shot 2019-06-21 at 2.46.57 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/bf7d866f-8ffe-48c2-afc1-e15a1040d6a3)

**Comment by sergiogcx** [comment]
✓ `pip install atd-log-util `

![Screen Shot 2019-06-21 at 2.47.57 PM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/a06fc150-5fab-44d7-ae1e-91dda2ac4153)

**Comment by sergiogcx** [comment]
✓ `pip install atd-socrata-util`

![socratautil.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/69f99857-162c-4417-8581-3c1fef849d8f)

**Comment by sergiogcx** [comment]
All libraries tested in production environment, moving to Review/QA

**Comment by johnclary** [comment]
Done. Closing and moving on to #260.
