### ISSUE TITLE
Discovery Day v3 | Explore Svelte JS framework

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#2522]
### Challenge or Solution
Svelte claims that development with this framework is faster, more performant, and provides a better user experience than other modern JS frameworks like React and Vue. It also has built-in cues for building accessible apps and provides a development process that is more accessible to non-developers. I will explore development with Svelte vs. React (using CRA) and hope to cover state management, event handling, forms, and using a GraphQL API.

### Prerequisites
- https://github.com/sveltejs/svelte
- https://github.com/facebook/create-react-app
- https://github.com/timhall/svelte-apollo
- https://hasura.io/blog/build-and-deploy-svelte-js-3-apps-using-graphql/

### Are there any hurdles you foresee? How might we address them?
I anticipate running into hurdles with using Svelte with Apollo and Hasura. I plan to address these by shifting focus to other Svelte features like built-in CSS transitions (https://svelte.dev/tutorial/in-and-out).

### Deliverable
At minimum, I aim to have a code example comparing lines of code for a small form with click handlers written in both Svelte and React. I am hoping to be able to fetch data as well and see how setting up `svelte-apollo` with Hasura compares to an implementation in React.

**Comment by amenity** [comment]
@mddilley - should we close this out?

**Comment by mddilley** [comment]
#### Code
https://github.com/mddilley/discover-svelte

#### Slides
https://github.com/mddilley/react_vs_svelte

#### Screenshots
Crashes view
<img width="1499" alt="Screen Shot 2020-05-04 at 11 00 45 AM" src="https://user-images.githubusercontent.com/37249039/81308651-a4316600-9047-11ea-955c-a5a4dd875392.png">

Crash Details and Edit view
<img width="1580" alt="Screen Shot 2020-05-04 at 3 16 29 PM" src="https://user-images.githubusercontent.com/37249039/81308658-a693c000-9047-11ea-90c1-d67ee6d17114.png">
