### ISSUE TITLE
Requirements Gathering #1 & 2

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2527]
**Dates/Times:** 5/7 @ 2pm, 5/13 @ 2pm, 5/21 @ 2pm
**Attendees:** Tracy, Diana, Joan, Nathan

**Comment by TracyLinder** [comment]
My notes from today were captured as user stores, [here](https://docs.google.com/spreadsheets/d/1PhV35tZiGzTKeHvyOM5CP8AOBG_jzGaeyfYB6hGjIvM/edit#gid=179231394).

**Comment by dianamartin** [comment]
My meeting [notes](https://docs.google.com/document/d/1T6H9mzXfQhzH8T0sQtAbF0FORvvcuXeQEYGVga_ZkjQ/edit#)

**Comment by TracyLinder** [comment]
### Meeting 5/13, Tracy's Notes:

**Prototype:**
- Page: Request TIA Review
    - TIA Needs Field: The value descriptions may need to be different.
    - TIA Needs Field: The field should accept selecting multiple types/values
    - TIA Needs Field: In italics under the heading add this text: Select all that apply
    - Case Type: The field should only accept 1 type/value
- Review Request Page: Allow the user to edit info from this page, instead of going back to each section to make changes
- TIA Submissions Section: Change to be more like a TIA Activity feature. Similar to the data tracker service requests activity. 

**Non-TIA Mitigations:**
- A scope is not required.
- Size & Intensity of the site (2 fields)
    - This should be included on all case types; it's been added as a user story
- Schematic site plan if available 
- Require the TIA Determination Worksheet as an attachment

- Amanda feature: Auto create TIA folders from the SP or ZC so staff doesn't have to manually insert folders as often
- AMANDA feature: Ability to collect Non-TIA mitigations in AMANDA; they're currently being processed manually. 

- [ ] Tracy: Send Diana the fee schedule
- [ ] Tracy: Setup time w/ Diana to sync the day before our next requirements meeting

**Comment by dianamartin** [comment]
Diana's [Notes](https://docs.google.com/document/d/1fUubYTAs0XdVltX1RPwTttgAXyZRyV7_lpI588sLTkA/edit?usp=drive_open&ouid=0)
