### ISSUE TITLE
Discovery Day v3 | Explore Google Vision API & Standardized Knack Apps Style Guide

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2528]

**Comment by dianamartin** [comment]
## Google Vision API
Reference [Susanne's GitHub page](https://github.com/susannegov/Signs-and-Markings-Projects/blob/master/Guide/UsingGoogleVisionAI.ipynb)

**Comment by dianamartin** [comment]
@amenity feel free to attach the resources you've been saving here: 
## Knack Application Style Guide - Standards

**Comment by amenity** [comment]
- https://www.gov.uk/guidance/content-design/writing-for-gov-uk
- https://cityofaustin.gitbook.io/digital-style-guide
- https://www.nngroup.com/articles/web-form-design
- https://content-guide.18f.gov/
- https://developers.google.com/style - style guide for documentation

There are also a gazillion resources specifically on best practices for digital forms [here](https://docs.google.com/spreadsheets/d/1ov27dpfaFW9nk0mVIpshj5Sj5mxoKaQafk8W4oyvqws/edit#gid=895936753).
