### ISSUE TITLE
ArcGIS Online (AGOL) Audit

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#253]
## Description
The purpose of this project is to clean-up Austin Transportation's ArcGIS Online Content and to form a strategy to keep the Content current moving forward. This will ensure only relevant and accurate data is available via internal and external facing Feature Services, Web Maps, and Web Applications. 

### Resources
https://github.com/cityofaustin/atd-geospatial/issues/15

**Comment by jaime-mckeown** [comment]
The initial run through of the data has been completed and documented. The status is currently on hold until I can connect with Diana so we can spend some time going through the data together.

**Comment by johnclary** [comment]
Possible project for GIS technician

**Comment by johnclary** [comment]
@jaime-mckeown i'm removing the `Project` label from this and will stick it in ongoing. If you would please post updates on your incremental progress here. Thanks.

**Comment by jaime-mckeown** [comment]
Closing this Issue, will add new Issues under Epic #1864.
