### ISSUE TITLE
Work session on Moped spatial data schema

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2530]
### Objective 
[Agenda/notes](https://docs.google.com/document/d/1C8ApbrT8EE1oajgjb9KmL_d34Qd2XwZ-y6Z485RAgsU/edit)

### Participants
Jaime, John, Nathan, Amenity

------
- [x] Schedule meeting - 5/26/20
- [x] Meet and take notes
- [x] Create resulting issues

**Comment by amenity** [comment]
- [Recording](https://web.microsoftstream.com/video/d859714e-9e0e-4f6b-9795-09c1958de3a2)
- [Notes](https://docs.google.com/document/d/1C8ApbrT8EE1oajgjb9KmL_d34Qd2XwZ-y6Z485RAgsU/edit#) 

tl;dr 
- All Moped projects should have a _Project Geography_; will be hand-drawn at first, hopefully in AGOL
- Moped must also accommodate spatially-referenced facilities where that level of detail is required; both length and count are used for analysis and reporting but not to the level of precision that a desktop GIS would be required
- @zappfyllc work with Nathan to design model + workflow for tracking a project's facilities  with goal of “parsing” [facility type list](https://docs.google.com/spreadsheets/d/1rgw3KL9fQ0xS49LLyzexHMPbV58WsWcr2jYaC2oSmKM/edit#gid=1948602978) down to a smaller set of choices and identifying where a facility should actually be an attribute of a project.

**Comment by amenity** [comment]
@zappfyllc please close this after you've reviewed  🙏

**Comment by zappfyllc** [comment]
Reviewed and added comments to Google Docs 5/27. Will follow-up with Nathan.
