### ISSUE TITLE
Build a Simple CRUD App with Python, Flask, and React

### ISSUE THREAD

**Issue by tylerwhitson** [cityofaustin/atd-data-tech#2532]
### Challenge or Solution
I want to learn how to build a database application using Python, React and Flask so that I can learn Python and Flask while using a JavaScript library with which I'm familiar (React). Ultimately, I'd like to take what I learn from this project and apply it to DTS frameworks and processes. 

### Prerequisites
Python 3
React
Flask
MongoDB or Docker toolbox
Okta account

### Are there any hurdles you foresee? How might we address them?
This could be a larger project than I will be able to complete in a day. If that is the case, I'll report on what I learned as I worked on it and how I'd like to incorporate it into my future work. Also, some of the frameworks, such as MongoDB are different from what we generally use (SQL-based), so I may want to try to tailor this project to more closely reflect the types of frameworks we would normally use.

### Deliverable
I hope to be able to demo a working prototype of a database application, but if not I will put together a presentation on what I've learned and how I can begin to apply it to existing applications.

**Comment by amenity** [comment]
@tylerwhitson - would you like to close this out?
