### ISSUE TITLE
Micromobility April Trip Report

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2551]
We need to provide Shared Mobility with the trip totals for April so that they can submit per-trip fees to the providers. Please provide an April trip report for the following providers:
- bird
- jump
- lime
- lyft
- ojo
- spin
- wheels

The following fields should be included:
- total trips
- total trip miles
- trip length avg
- trip duration avg
- trips zero distance
- trips long distance

**Comment by sergiogcx** [comment]
Done, provided to @JaceDeloney via file sharing.

**Comment by sergiogcx** [comment]
This is done, closing.
