### ISSUE TITLE
Implement reusable Bootstrap popover component

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2552]
Implement popovers in the following locations in VZV:
- Years of Life Lost widget information icon
- Traffic Crashes Information icon
- Overlay title information icon
- ~Austin City Council Districts overlay~ Moved to https://github.com/cityofaustin/atd-data-tech/issues/2558 to integrate with new overlay layer

These popups should use a reusable component with the Bootstrap popover that could be applied to any buttons, text, etc. The component could be used for both hovers and clicks:
https://reactstrap.github.io/components/popovers/
 
For the text/content that should display for these popovers, reference #1637

**Comment by mddilley** [comment]
Going with https://github.com/atomiks/tippyjs-react which is powered by the same underlying library as the `reactstrap` Popover component (Popper.js) but allows a bit more customization. 

It also solves a problem with `overflow` and `z-index` encountered when rendering `reactstrap` Popovers within the mobile/map sidebar.
