### ISSUE TITLE
Open Data Portal updates to VZ datasets

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2553]
In preparation for the official external release of the Vision Zero Viewer, we should go through the open data portal's Vision Zero datasets to update the titles, text descriptions, metadata, and disclaimers. We may also find some data fields/sets that no longer need to be published. If data fields/sets like this are found, please record them in this issue so that we can create tasks to take those down.

**Comment by JaceDeloney** [comment]
Reference #2895 for changes to dataset titles

**Comment by patrickm02L** [comment]
Remaining work is captured in #6661.
