### ISSUE TITLE
Remove VZV alert banner & pop up

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2554]
Before we release VZV to the public, we need to remove the alert banner and the popup from the summary page and map page

![Screen Shot 2020-07-01 at 12.35.23 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/fff75dfc-f02c-47d4-bc0e-83a36c897481)

![Screen Shot 2020-05-26 at 9.21.22 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/0d3fe322-4e71-4c9f-aa7f-9b34f86f6819)

**Comment by mddilley** [comment]
https://github.com/cityofaustin/atd-vz-data/pull/858 makes updates to the margin above the gray banner in `Summary.js` to make sure top margin will be correct without the chunk below.

```
<Row className="px-xs-0 mx-xs-0 px-lg-3 mx-lg-4 mt-4 mb-0">
        <Col>
          <Alert color="danger">
            <FontAwesomeIcon icon={faExclamationTriangle} />
            <span className="ml-2">
              This is a beta version of the Vision Zero Viewer, published to
              gather user feedback. Crash data displayed may be outdated or
              inaccurate, and will be updated for the first public release
              version.
            </span>
          </Alert>
        </Col>
      </Row>
```
