### ISSUE TITLE
Update Austin City Council Districts Overlay 

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2558]
Change the council district symbology on VZV from colors to a fill pattern and/or a dotted outline. e.g.: https://docs.mapbox.com/ios/maps/examples/fill-pattern/

Austin City Council Districts geofile can be found here:
https://data.austintexas.gov/Locations-and-Maps/Council-Districts-Fill/hdpc-ysmz

- [x] Add info popover component to Austin City Council Districts overlay

**Comment by mddilley** [comment]
From @john: https://docs.google.com/presentation/d/1Fxtt7K10B7jYXszU-lMoffbJRB0ys9SSM1srbg9WQuA/edit?usp=sharing

- [ ] Use `mapshaper` to reduce layer complexity
- [ ] Prune fields in API request
