### ISSUE TITLE
Project: Micromobility Dashboard Updates

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#256]
We are focusing on making enhancements to our public facing dashboard of dockless mobility data and statistics. Some enhancements relate to site and query performance. Other tasks include feature requests from Parking Enterprise Division.  

### Resources
- [Site link](https://transportation.austintexas.io/dockless-data/)
- [Github](https://github.com/cityofaustin/transportation.austintexas.io)

**Comment by amenity** [comment]
@mateoclarke @tcwcodes - we're renaming it to "Micromobility Dashboard," right?

**Comment by mateoclarke** [comment]
@amenity yup

**Comment by mateoclarke** [comment]
I think we've effectively finished this epic. The other issues we can put into the backlog and group as needed.
