### ISSUE TITLE
Builder Huddle: AMD Work Order refactor/New Service Requests

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2563]
### Objective 
Evaluate the project requirements, technical feasibility of modifications/enhancements, determine left of effort, determine estimated timeline and scheduling of this project
- Creation of Technical Approach
  - Develop AMD Internal SR Creation/Refactoring Work Order and Service Requests 

### Participants
- John
- Amenity
- Surbhi

**Comment by dianamartin** [comment]
@amenity I actually already had an issue for this meeting

**Comment by amenity** [comment]
Notes from this meeting [here](https://docs.google.com/document/d/1Q6HvFHGqUruBI6ccdljscPUfrIGNJ2VSvyW8KHVrNwc/edit#heading=h.2dpn7q735twr).
