### ISSUE TITLE
Refine Officer sign up UI based on builder huddle discussion

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2565]
Also refer to notes from our last work session with Pat.

**Comment by SurbhiBakshi** [comment]
**Table of available assignments for officers to signup**
1. Fields
- [ ] Assignment Date

- [ ] Assignment Time

- [ ] Shift

- [ ] Assignment Location

- [ ] Officers Required

- [ ] Unfilled Slots

- [ ] Officer Badge No / Officer Name - if officers have already signed up for the assignment.

- [ ] Details ???

**Comment by SurbhiBakshi** [comment]
Object - officer_assignments

- [ ] Add a field - Add to My Assignments (Yes / No) which will create an officer assignment record when Yes is selected.

**Comment by SurbhiBakshi** [comment]
Closing this issue - this was meant to be a refinement of the Officer UI if we had taken a non-child record approach. Based on #2562, and discussion on Friday 05.15.2020, we are going to take a child record approach. Will open a new issue for that.
