### ISSUE TITLE
VZA Sprint Review #5

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2566]
[Agenda & notes](https://docs.google.com/document/d/1-HMc9-CR345JZHNcLe5EVPGHMtTCA5qwAd0Y_W8nQYY/edit#)

**Comment by amenity** [comment]
@SurbhiBakshi - feel free to add to this w/ questions for the review. 
@amenity - schedule plz

**Comment by johnclary** [comment]
@amenity plz schedule this.
