### ISSUE TITLE
Follow-up demo with dotMaps

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2576]
dotMaps is a compelling solution for many of the project-coordination use cases currently scoped for the Mobility Project Database. #2557 was attended mostly by Right-of-Way users, so this follow up meeting will give the DTS team and other stakeholders an opportunity to see the solution and gather more information. 

Scheduled for Thursday, May 14th.  
- [Agenda/Notes](https://docs.google.com/document/d/1FKad-9QccXiow3HGthiPGcoDozNr1GILAmeROmfTWQ8/edit#heading=h.kh5fg8yegi3l) 

---
To do:
- [x] Review pricing information - @johnclary has discussed with Peggy
- [x] Review [API docs](https://drive.google.com/open?id=1unJEiJ8wKlcjQysY1gY91coC1nVx39iH) - #2624 
- [x] Schedule meeting - include Nathan 
- [x] Schedule debrief
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes

dotMaps - John Biesek

ROW mgmt, conflict resolution, event coordination
Capital Improvement projects, 


Sada Systems - Google/Apple
Google Basemap
bring maps into gov't space

6-8 mo onboarding process
trained 7-8 power users, 12,000-15,000 users

Support GIS & ESRI
different shapefiles bring in from GIS DB
marker clustering

Highlights segments
point, lines
High level information
- Overlaps (Conflicts/Opportunities)

City of Seattle/City of Chicago
Internal Coordination
- Street Paving
Cities are seeing savings
Coordination with public

Competitors: charge outside utility groups
not coordinating outside utility groups
if software isn't mandated, utilities aren't usually involved bc they need to buy license

Unlimited user licenses
Integrate dotmaps with existing asset mgmt software

Has been doing research and look up AMANDA stuff
Looking for permitting solution
Not looking to do permitting
Partnership with AMANDA (Isn't COA is moving away from AMANDA?)

Highly configurable, not customizable
Works initially and isn't updated

**Comment by amenity** [comment]
[Recording](https://www.youtube.com/watch?v=2Ogl_d6Tasw&feature=youtu.be). 

The DTS team debriefed afterward and agrees that while we really like the slick dotMaps user interface, there isn't any significant overlap with the core functionality we'll be building out in the Mobility Project Database. 

Have reached out to Ryan and Paloma to see how we can support them if they want to move forward looking at the solution.
