### ISSUE TITLE
Bug: Time of day component Firefox styling

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2577]
There is a styling issue with the time of day component on the Firefox browser. We should go through VZV on desktop and mobile using the Firefox browser to ensure there are no other styling issues.

Screenshots below:

![Screen Shot 2020-05-06 at 2.28.34 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/1d7cf060-214a-4cb8-aa09-57f9c5d07c48)

**Comment by tylerwhitson** [comment]
The Time of Day styling issue is a bug in the library, and someone recently submitted a [bug report](https://github.com/jask-oss/reaviz/issues/121) for it. I'll see if there's a workaround.

**Comment by amcdnl** [comment]
What's the issue? Can you submit it to reaviz/reaviz ?
