### ISSUE TITLE
Reference Page - Triage Emails (Non Service Requests)

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2579]
Create a reference page for emails that need to be forwarded to DTS team members.

**Comment by SurbhiBakshi** [comment]
Reference page created [here](https://atd-dts.gitbook.io/dts-service-desk-knowledge-base/-M66PWJ3zJRK1UBoU47T/).

**Comment by SurbhiBakshi** [comment]
@dianamartin  - please review - not so sure about the Amanda one, how does the GIS team handle GIS outage emails right now? I have always forwarded GIS outage emails to staff.

**Comment by dianamartin** [comment]
@SurbhiBakshi I guess we can ask Jaime. I haven't ever seen her sent out emails to the ATD GIS users. I think we have a distribution list someplace.

**Comment by SurbhiBakshi** [comment]
@dianamartin - I have the ATD DL. We can ask Jaime. Think you also have Knack app specific DLs right?

**Comment by dianamartin** [comment]
@SurbhiBakshi I kind of have distribution lists, I've only created one for the SMB Data Tracker folks, but it's probably outdated already.
