### ISSUE TITLE
Meeting | Email Snippets for Open Data Responses

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2585]
@dianamartin lets discuss email snippets. Related to #2280

**Comment by dianamartin** [comment]
@SurbhiBakshi didn't we do some of these?

**Comment by SurbhiBakshi** [comment]
@dianamartin - yes, we have the most common answers in the Gitbook.

**Comment by dianamartin** [comment]
@SurbhiBakshi feel free to close this if tasks are completed
