### ISSUE TITLE
Feature request: TIA Folder Auto-Creation

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2593]
## As a TIA reviewer, I'd like AMANDA to auto-create TIA folders during the site plan or zoning case review. This will allow us to stop having to enter them manually. 

**Stakeholders:** Joan M., Nazlie S, Nathan A, Sangeeta, Amber

**Acceptance Criteria:**
- TBD

**Notes for Scoping:**
- Which folders need this feature? (Zoning, Site Plan, any others?)
- What logic will the folder use to know when to create a child permit? 
- What status should the TIA folder be created in?
- What task/process will be used to assign review to TIA reviewer? 
       - Who should it assign to?
- What information, if any, will be copied from parent folders into TIA folder?
- What actions need to be done in the parent folder when a child TIA is created? (folder status change, etc.)

-----

**Describe the outcome you'd like to see when this feature is implemented.**
New TIA folders will show up on my AMANDA task list for review. 

**Describe any workarounds you currently have in place or alternative solutions you've considered.**
Currently we manually insert the folder ourselves, then we enter the info again in our TIA Primary List spreadsheet.

**What else should we know?**
This feature request came about during a requirements meeting for the TIA Module project. The requester is Joan M with the TIA group. 

**Acceptance criteria**
- TBD
<!-- Each feature should have at least one acceptance criteria. Acceptance criteria should have a clear Pass/Fail outcome and specify the result (what) rather than approach (how).

**Comment by TracyLinder** [comment]
@vschandramouli please schedule a meeting with stakeholders, copy Nate & me as optional, and include the questions for stakeholders in the meeting body.

**Comment by vschandramouli** [comment]
After scoping with Sangeeta and Nazlie, it looked like this requirement was not a very common occurrence and may not need to be addressed as a Use case. 

@TracyLinder Please advise on closing this ticket. 

CC @Nadin-Nader

**Comment by TracyLinder** [comment]
@vschandramouli I agree we can close this. I'll update the description to reflect what we've learned and close this out.
