### ISSUE TITLE
CRIS SFTP documentation & Manual bulk upload documentation

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#2595]
- [x] Now that we've switch up our data ingest process to use the SFTP server instead of the bot, we need to update our READMEs or potentially add to the Gitbook Wiki new docs about how this process works, how to update it, contact info for partners at TxDOT, etc.

- [x] We also should document a strategy/process for ad-hoc request data uploads. For example, we may need to download a month of data from CRIS and upsert if we're worried about missing records or ETL process failure backfills. This may require us to implement a new process/write new code to go along with this manual upload strategy.

**Comment by sergiogcx** [comment]
This is done:
https://app.gitbook.com/@atd-dts/s/atd-dev/visionzero-sftp-etl
