### ISSUE TITLE
VZV: Improve Mobile Performance (summary page)

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#2597]
While we are passing most benchmarks, Google is giving the viewer a very low grade performance in the summary page:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fvisionzero.austin.gov%2Fviewer%2F

![2020-05-08_12-47-44.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/def79870-8d68-4560-8cd2-26fce1b4958b)

![2020-05-08_12-45-54.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/8d9cb1d2-e64a-4be3-a7dc-645811527747)

This is apparently due to an oversize of the javascript bundle as created by react, they recomend reducing the size of the javascript bundle to get a better grade:

![2020-05-08_12-46-36.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/95582377-be43-4e42-8ee1-2b8eb2683cb9)

![2020-05-08_12-50-59.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/4723a38a-4d80-46b3-a4f8-474b8d68c082)

![2020-05-08_12-51-17.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/7a6909f7-0366-499e-993e-03c6b478d6b8)

**Comment by sergiogcx** [comment]
The things we did well:

![2020-05-08_12-52-21.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/8c7869d3-d007-4376-94af-ba1683fcec38)

**Comment by sergiogcx** [comment]
This is the result for the map, it's the same issue plus the large payloads problem, but this is to be expected:

![2020-05-08_13-01-56.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/51f9fb3e-183f-4c1b-b7ea-359413a7baba)

**Comment by sergiogcx** [comment]
Some suggestions:
- Use a static site generator such as react-static or Next.js
- Use react for the map, and something else for the summary page (ie: plain jquery and chart.js and bootstrap)

**Comment by JaceDeloney** [comment]
This has not come up as an issue with users or VZ Team.
