### ISSUE TITLE
VZV: Mobile Layout Issues

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#2598]
The VZV Viewer presents issues when browsing in a Samsung Galaxy S7, as tested with BrowserStack:

This error is not present using the samsung mobile web browser (the default), but only in Google Chrome in this specific device:

![2020-05-06_13-24-00.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/bdd59b1a-ff0d-468e-8507-076a7c907fcc)

![2020-05-08_12-28-06.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ecffee63-ccd4-46b3-ab2d-db2d0ca0f2cf)

![2020-05-08_12-25-30.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/c54085f3-67c6-4ca7-bdaa-06e48554bf1a)

![2020-05-06_13-24-37.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/abc439e3-762d-4fad-8c94-208a402013e4)

**Comment by JaceDeloney** [comment]
This was addressed during the launch of VZV
