### ISSUE TITLE
Zenhub subscription

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#26]
Find out about pricing and send PR

**Comment by dianamartin** [comment]
Scott's approved PR for Technical Review, assigned to @johnclary now

**Comment by johnclary** [comment]
@dianamartin reminder to follow up with purchasing folks on this

**Comment by dianamartin** [comment]
mailed Ramona today to find out what the status of the PR was. 
>I was asked to follow-up with you to see what the status of this PR# 2019-0571.

**Comment by dianamartin** [comment]
Talked to Ramona and Joann this Thursday. I believe they were moving forward with the subscription payment. Just pinged John to see if they've already done it.

**Comment by amenity** [comment]
@johnclary - we can close this, right?

**Comment by johnclary** [comment]
Well, it seems we're getting the benefits of a paid subscription thanks to the licenses that CTM has purchased, but our team's users are still unlicensed and there's a warning message about that in the Zenhub account admin. I'd prefer we pay for ourselves if possible. Would you poke around on Zenhub and see if it's possible to buy licenses just for our team? If that's not feasible, I think we can close this wait until our licensing situation becomes an issue.
