### ISSUE TITLE
Deploy atd-data-utilities

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#260]
TODO

### On the `atd-data01` server:

- [x] clear root crontab

- [x] pull and checkout `atd-data-utilities` branch of `atd-dockless-processing` repo

- [x] pull and checkout `atd-data-utils` branch of `atd-data-deploy` repo

- [x] pull and checkout `atd-utils` branch of `atd-finance-scraper`

- [x] pull and checkout `utils` branch of `atd-data-publishing` repo

- [x] pull latest `atd-data-publishing` image with atd-utilities: `atddocker/tdp:1.11.1`

- [x] pull latest `dockless-processing` docker image with new utils (`v0.1.12`) 

- [x] re-deploy crontab

- [x] Let cron run normally and see if these branches work ok

- [x] merge branches from above to master and checkout.

**Comment by johnclary** [comment]
@sergiogcx i'm going to run through this tonight after the TMC closes @ 8pm.

**Comment by sergiogcx** [comment]
Amazing!, it might be a good idea to use a custom tag when pushing to docker hub (as opposed to the default `latest` tag), that way we can retain both the current image in production (latest) and a new test image, probably tag it with the same name of the branch (`atd-data-utils`):

```
docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]
```

**Comment by johnclary** [comment]
thanks for that syntax. will update the tag names and follow this going forward.

**Comment by johnclary** [comment]
Kicking to sprint 2. So close ;)
