### ISSUE TITLE
VZV: Not working on Internet Explorer (bug)

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#2601]
Unsure if Internet Explorer is an audience we need to look after; nevertheless, the viewer does not work in IE 11:

Tested on Windows 10, and Windows 8.1 (Windows 7 is no longer supported by Microsoft)

![bs_win10_IE_11.0.jpg](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/4b98d3c9-dd25-42bd-89fe-77eabc3a6dc0)

**Comment by mateoclarke** [comment]
Yeah, this is documented with create-react-app. There's a standard polyfill.

https://create-react-app.dev/docs/supported-browsers-features/

https://www.npmjs.com/package/react-app-polyfill
