### ISSUE TITLE
DTS Discovery Day v4

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#2602]
This epic compiles projects for DTS' Discovery Day on June 19, 2020. Please add a Github issue to capture what you decide to work on!

Here's a template you can start from if you'd like: 
### Challenge or Solution
What is the problem you want to solve or solution you want to explore? 

### Prerequisites
Software, data, getting a local dev environment set up, etc. 

### Deliverable
Everyone will have three minutes to present their work (with the option to save the recording) and a slide in the Discovery Day presentation deck. Are there any other artifacts you want to walk away with? Wiki pages, a prototype, etc.

**Comment by johnclary** [comment]
moving this to review/qa
