### ISSUE TITLE
Publish Bike Rack data to Socrata

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#2608]
- [x] QA Data
- [x] Settle on which data to publish - either the entire dataset, or only field-checked data
- [ ] Publish data to Socrata

**Comment by johnclary** [comment]
@alan-deanda would you link to this layer on AGOL?

**Comment by johnclary** [comment]
Alan will reach out to Ben V. for an update

**Comment by johnclary** [comment]
Please also find out how we can change dataset titles and descriptions, e.g.:https://data.austintexas.gov/dataset/TRANSPORTATION_bicycle_facilities/uwbq-ycek/data

**Comment by johnclary** [comment]
Has been assigned to Socrata / Open Data Team @ CTM

**Comment by alan-deanda** [comment]
I've followed up on my service now ticket, waiting on response.

**Comment by johnclary** [comment]
@alan-deanda would you follow up on this?

**Comment by alan-deanda** [comment]
Submitted a followup, waiting for a response.

In the meantime, it seems that both of these bike facilities datasets point to the same data: [TRANSPORTATION_bicycle_facilities](https://data.austintexas.gov/dataset/TRANSPORTATION_bicycle_facilities/uwbq-ycek) [and Austin Bicycle Facilities](https://data.austintexas.gov/dataset/Austin-Bicycle-Facilities/kfe9-st9c)

Each of these links is a separate result when you search for "bike facilities" in the open data portal. TRANSPORTATION_bicycle_facilities is classified as a map, and one can export in several formats from that link. 
Austin Bicycle Facilities is listed as an external link, and it contains links to the REST end point and the AGOL download page.

**Comment by amenity** [comment]
We'll pull this up when we've solidified the bike rack data structure. We expect #9080 to inform it.

**Comment by alan-deanda** [comment]
@andrewshensky  I'm thinking of zero-ing out this issue and closing it, since we're going to put this data on our hub instead of going through the  MAINT>CTM>DM>open data portal route. what do you think?

**Comment by andrewshensky** [comment]
@alan-deanda I agree, I'll go ahead and close this issue. I think this dataset is perfect for presenting in the hub.

**Comment by emaland** [comment]
@amenity @alan-deanda hi folks, i'm new to austin and looking for data on bike rack locations around town (working to build an app around that and other bike/gis data). did this data ever end up being collected and is it published somewhere? i'd love to help out anyway i can if it's still in progress!

**Comment by amenity** [comment]
@andrewshensky - is the [Austin Bicycle Facilities](https://data.austintexas.gov/dataset/TRANSPORTATION_bicycle_facilities/uwbq-ycek) [and Austin Bicycle Facilities](https://data.austintexas.gov/dataset/Austin-Bicycle-Facilities/kfe9-st9c) dataset linked to above still the best bike rack data?

**Comment by andrewshensky** [comment]
@amenity Below are some of our updated public facing bike related AGOL datasets. We are hoping to have the bike facilities data below updating the ODP data in the coming months:

Bike Facilities
https://austin.maps.arcgis.com/home/item.html?id=f1e3436404a34f18a33a0decc489f16c
Bike Level of Comfort (data used to symbolize routes in Online Bike Map)
https://austin.maps.arcgis.com/home/item.html?id=3c99d527e8a04fb4976573c7934ef9ef
Bike Parking
https://austin.maps.arcgis.com/home/item.html?id=ab979c3501c1453c94e46872d254cbee

**Comment by amenity** [comment]
Thanks so much, @andrewshensky! 

@emaland ☝️hope that helps!
