### ISSUE TITLE
Install Python 3 on `atd-data01`

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#261]
Need to install Python 3 on our prod server and set to the default `python` environment.

@sergiogcx once you test on `atd-data02` we should coordinate the update on `atd-data01`.

**Comment by sergiogcx** [comment]
@johnclary I set up `python3.7` on `atd-data02` and made an alias to run it using the `python3` command in the terminal.

I checked the `atd-data01` server and `python3.7` was installed except for pip, so what I did was to install a dependency that was causing problems and re-installed, pip worked fine. I also set up an alias in `/etc/profile`

**Comment by sergiogcx** [comment]
Also, I have not made python3 the default version yet, not until we make sure it does not affect any of the scripts running in `atd-data01`.

**Comment by sergiogcx** [comment]
Closing, as it turns out it wasn't needed.
