### ISSUE TITLE
Meeting: OSE AMANDA Backlog Review 5/15/20

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2618]
### Meeting Info:
**Date/Time:** 5/15/20 / 3pm
**Attendees:** Tracy L, Maria A
**Purpose:** Document unmet AMANDA needs/requests and add acceptance criteria if possible.

**Comment by Nadin-Nader** [comment]
Recording of meeting can be found at https://web.microsoftstream.com/video/602a4228-836a-4914-b2ef-fb8fee7c9e34

Items we went over:

-(1709) New Processes For Neighborhood Block Party Folder*Add 3 default folder processes. The processes should insert when an attempt result of 'Accepted' is saved on the Web Application Acceptance process (code 7000).* Work type is there, they need it to insert the process they already have*APD, AFD, Trash and Recycling Review** Once it comes from Web Acceptance status should change** Put in Backlog
-(1733) Refund report**Ice box as it can wait**
-(2311) Document Process used to get SE data form AMANDA for SXSW (SXSW Got cancelled)**Ice Boxed**

New Items created:
-(2262) RW, OSE Info clean up* Needs infos on info tab removed
-(2663) Would like system to Auto create in the RW Street Event folder when ####### info is selected "Yes" on ACE folder and common details/info to copy down*
-(2664) OSE Reviewer Process Default initial status is Pending Payment, need it to be Pending*Procedure update
-(2665) OSE FEE Insert change When issuing the permit the last process "event permitting" inserts 2 fees but doesnt bill them *Work around is to cancel them* 
-(2666) only Web Acceptance/Intake process works as supposed to, others have no value to OSE Reviewers*Needs Processes to inform them of Status
-(2667) OSE Portal Updates *See whats on permit page on portal and what public sees
