### ISSUE TITLE
Support Systemic Safety Analysis data needs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2620]
Vision Zero has engaged with Toole Design Group to perform systemic mobility safety analysis of Austin. Traditional safety analysis entails finding hot spots based upon historic crash data and identifying counter measures from there. This is a more proactive approach: We have a collection of demonstrably effective counter-measures, so let's identify where we can apply these across the system. Where we can achieve the greatest impact at the lowest cost?

"You can’t predict where the next serious crash will occur. This will help us look beyond historic crash data in a more proactive approach."

Desired datasets are documented [here](https://docs.google.com/spreadsheets/d/1nGMuvtJohqF9YOWHP3KgTDMSBHgu19_h/edit#gid=1522990773). 
 
**To do:**
- [x] @johnclary general review
- [ ] @jaime-mckeown general review
- [ ] @dianamartin general review
- [x] @alan-deanda assist Joel with CTN
- [ ] @amenity create issues for any outstanding data needs

---
Contact: Joel M., Vision Zero

**Comment by alan-deanda** [comment]
Just met with Joel over the phone, and I will be helping him with data needs that the CTN can fulfill as well as providing them with Toole with the [CTN Data Dictionary](https://github.com/cityofaustin/atd-geospatial/wiki/CTN-Data-Dictionary).

**Comment by amenity** [comment]
Thanks, @alan-deanda. @johnclary @dianamartin @jaime-mckeown - please review and comment in the spreadsheet when you get a chance.

**Comment by johnclary** [comment]
@amenity i've updated the spreadsheet and posted links to open data where available. can this be closed until they reach out to us again?

**Comment by amenity** [comment]
@johnclary - yup, gracias🙏
