### ISSUE TITLE
Review dotMaps API documentation

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2624]
During our initial dotMaps demo, great emphasis was placed on the utility of their API for integration purposes. 

If y'all have time to review [this API documenation](https://drive.google.com/open?id=1unJEiJ8wKlcjQysY1gY91coC1nVx39iH) before our follow-up meeting, #2576, that would be super... 

Feel free to add questions/comments to the [agenda/notes for Thursday's meeting](https://docs.google.com/document/d/1FKad-9QccXiow3HGthiPGcoDozNr1GILAmeROmfTWQ8/edit#).

**Comment by sergiogcx** [comment]
Should we close this issue?

**Comment by amenity** [comment]
Yup!

**Comment by amenity** [comment]
Consensus: This API is weak — not a lot of capabilities — focused mainly on the "Projects" table, & the fact that it's a typo-ridden PDF are cause for concern...
