### ISSUE TITLE
Instance for testing ETL update

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2625]
- [x] Create an instance of the Dockless Mobility application for Sergio to test ETL process.
- [x] Give Sergio builder access to that instance
- [x] Document instance in DTS Inventory

**Comment by SurbhiBakshi** [comment]
- @JaceDeloney @sergiogcx - as discussed in our meeting on 05/08 I have created an instance of the application to test ETL for the monthly data uploads. 
- @sergiogcx - you will have received an email giving you access to the application. 
- I also mocked a table for viewers to look at the data as a first pass. Will slack you the details on that.

**Comment by sergiogcx** [comment]
Thank you @SurbhiBakshi

**Comment by SurbhiBakshi** [comment]
Some preliminary research based on documents sent by Joseph is [here.](https://drive.google.com/open?id=1KKVt3F7xP2vtAXwVDO83K84DV6HcpUwysIhVwKq05fk)
