### ISSUE TITLE
Feature request: Update TIA Folder Info Tab (TL)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2632]
### As a TIA reviewer, I want the folder info tab to only contain fields that are useful to me. At the moment it is cluttered with required fields that I am inserting dummy info for

**Stakeholders:** Nazlie, Sangeeta
**DTS Manager:** Tracy

**Info Tab Acceptance Criteria:**
- All infos are removed except: Proposed trips per dy, Fee required, Type of analysis, TIA Case Manager, Application Date
    - TIA Case Manager Values: Nathan Aubert, Nazlie Saeedi, Justin Good, Other
    - Type Of Analysis: Site Plan, Zoning, Subdivision, Other
        - Field Type: Pick (so users can input unique value)
    - Proposed Trips Per Day: 2,000-5,000 trips per day, 5,001-15,000 trips per day, 15,001-40,000 trips per day, 40,000+ trips per day, other (ordered smallest to largest)
        - Field Type: Pick (so users can input unique value)

_The Acceptance Criteria was gathered during the meeting captured on #2616._

**Ready for Development?:** Yes

**Comment by TracyLinder** [comment]
Prioritization From Customer:


![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/6eaf1d7c-5309-4c66-b48a-8fde34db33aa)

**Comment by Sreelatha-BlazeKannan** [comment]
Submitted the Demo on 06/19/2020. Waiting for feedback.

**Comment by TracyLinder** [comment]
Will watch demos #3216

**Comment by TracyLinder** [comment]
**Status:**
- Pending Tracy's approval to move to DEV
- Updating to Sprint 29

**Comment by Sreelatha-BlazeKannan** [comment]
@aishwarya2505 , @Nadin-Nader  - As per Nadin this is already in DEV. Martin Deployed it today morning!

**Comment by TracyLinder** [comment]
### DEV UAT Results

**Result: Failed**
- Folder ROW ID: 11891625
- Info fields I expected: Proposed trips per day, Fee required, Type of analysis
- Actual folder info fields: TIA Case Manager, Application Date, Proposed Trips per Day, Fee Required, Type of Analysis

**Sree or Ash, please also remove these infos: TIA Case Manager & Application Date**

@Sreelatha-BlazeKannan @aishwarya2505

**Comment by TracyLinder** [comment]
**Status:** In DEV. Doing a demo w/ stakeholders on 7/31. Updating milestone to Sprint 30.

**Comment by TracyLinder** [comment]
**Notes from Mtg w/ Nazlie & Sangeeta:**
- Sangeeta asked if drop-down values can be in order from smallest to largest
- Type of Analysis: Add 'subdivision' and 'other'

**Comment by TracyLinder** [comment]
This acceptance criteria may need to be updated to include fee-based info dependencies.

**Comment by TracyLinder** [comment]
Per Nalzie, remove fees that are inserted during folder creation process.

**Comment by TracyLinder** [comment]
'Calculate Fees' attempt should not close the Initial intake process.

**Comment by TracyLinder** [comment]
Initial Intake Process, assigned user - Default to null (empty)

**Comment by TracyLinder** [comment]
Proposed Trips Per Day: Add value: 'Other'
TIA Case Manager: Add value 'Other'

**Comment by TracyLinder** [comment]
Acceptance criteria has been updated.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Aishwarya is working on the changes

**Comment by TracyLinder** [comment]
**Clarification Email Sent**

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/8383e839-06ef-46f4-a44c-13f970c9dd9a)

**Comment by TracyLinder** [comment]
### Email Convo Continued: 

**From Nazlie:**

Hi Tracy,

Thanks for asking us. We are fine with having the letters but we also would like to have another blank category in case we need to write in a different answer than the options listed in the drop down. Does that make sense?

**My Response:**

Hi Nazlie,

That makes perfect sense. Unfortunately this type of info field (drop-down) does not allow a user to input a unique value. Sree – can you please confirm that this is not possible?

My suggestion for a solutions: 
•	Let’s add an option in the drop-down ‘E- Other’. 
•	We can also add a new field that will allow you to clarify why ‘E- Other’ was selected. It would be a free-text field so you could input whatever text you need to. The field name could be something like ‘Trips Per Day Other Info’ (or whatever you’d like to call it). 
•	Following that thought, ‘Type of Analysis’ also has an ‘Other’ option. We could add a text field allowing you to explain why other was chosen for this also. 

I look forward to your feedback on these ideas.

**Comment by aishwarya2505** [comment]
@TracyLinder  The Info field is currently of type "Choose". This doesn't allow the user to input a unique value. If we change the type of info field to "Pick",We can include the existing options as well as allow the user to  input a unique value.

**Comment by TracyLinder** [comment]
@aishwarya2505 That's a great suggestion. I'll followup with Nazlie w/ this option.

**Comment by TracyLinder** [comment]
### Email to Nazlie:

Nazlie,

I just learned that we can change this field type to one that will allow unique values to be entered! This would be an easier solution, though I’ll need to iron out the details with Sree. Please disregard my suggested solutions below. 

Sree, I’ll send a teams invite to discuss changing these 2 fields from a ‘choose’ type to a ‘pick’ type.

Thanks Everyone!

**Comment by TracyLinder** [comment]
Acceptance Criteria has been updated. 

![image](https://user-images.githubusercontent.com/49930868/90155591-1f926a00-dd51-11ea-865d-879ae7f76d87.png)

**Comment by Nadin-Nader** [comment]
@TracyLinder @Sreelatha-BlazeKannan @aishwarya2505 I reviewed the demo and saw that the user can input their own unique values in the Field Type, meeting the update acceptance criteria.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 please promote this up. Thank you!

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 the demo looks great. Please promote to DEV.

**Comment by Nadin-Nader** [comment]
@aishwarya2505 Aish i sent you an email asking if these are missing commits or if this was needing to go to CTM Tango to deploy as i dont have permissions to do. If these have commits then i will get it to the CM Team. Let me know so we can get this to one of the teams. 


From: Nader, Nadin 
Sent: Thursday, August 20, 2020 3:28 PM
To: Aishwarya Ramesh <Aishwarya.r@launchitcorp.com>
Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
Subject: RE: Request for DEV Deployment - #2632,#2634

Hi Aish,

Hey I was trying to reach out to you earlier this week to ask you about the deployment plans. Do these have commits? If not and these are regular deployments, the its going to have to go to CTM Tango to perform since I don’t have permissions to do these. Please let me know as soon as you can so we can get this done on DEV.

**Comment by aishwarya2505** [comment]
@Nadin-Nader : This is the commit ID : d411da944535 .

**Comment by Nadin-Nader** [comment]
Hello Nadin, 

Yes, you got it. That one commit d411da944535 ,covers both the tickets. 

Also, each time my VPN goes through the password reset process I am unable to access Teams. You can e-mail me if you need me to look at something real quick. 🙂 

Best Regards,
Aishwarya Ramesh

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @TracyLinder @Sreelatha-BlazeKannan I have submitted the request for deployment to DEV to the CM DevOps Team:
Task fo CM DevOps team is SCTASK0091486.

**Status:**

Waiting on CM DevOps team to deploy to DEV (SCTASK0091486)

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @TracyLinder @Sreelatha-BlazeKannan This has been deployed to DEV by George at CTM

**Comment by aishwarya2505** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan Tested this in DEV , FolderRSN 11894774 and the changes work as expected.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Commited changes in DEV on 08/19 and submitted DEV deployment plan and tested the same in DEV Ready for UAT in DEV

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder @aishwarya2505 
I have looked over the changes on DEV and found that all acceptance criteria has been met. I also verified the infos had the correct options.

**Comment by TracyLinder** [comment]
### This is approved for test. 🎉

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder I have sent this to the CM DevOps Team to deploy to TEST under TASK SCTASK0101403.

**Status:**

Waiting on CTM to deploy to TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder this has been deployed to TEST.

**Status and Next Steps:**

UAT on TEST

**Comment by aishwarya2505** [comment]
Tested this on TEST 12396002. @Nadin-Nader @TracyLinder @Sreelatha-BlazeKannan

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder I have UATd this on TEST (RSN:12396019) and it met all of the acceptance criteria below:

- [ ] All infos are removed except: Proposed trips per dy, Fee required, Type of analysis, TIA Case Manager, Application Date
- [ ] TIA Case Manager Values: Nathan Aubert, Nazlie Saeedi, Justin Good, Other
- [ ] Type Of Analysis: Site Plan, Zoning, Subdivision, Other
- [ ] Field Type: Pick (so users can input unique value)
- [ ] Proposed Trips Per Day: 2,000-5,000 trips per day, 5,001-15,000 trips per day, 15,001-40,000 trips per day, 40,000+ trips per day, other (ordered smallest to largest)
- [ ] Field Type: Pick (so users can input unique value)

**Comment by TracyLinder** [comment]
UAT with stakeholders scheduled for 10/29

**Comment by TracyLinder** [comment]
### UAT Results: Passed

**Comment by TracyLinder** [comment]
**Question for LaunchIT:** Can the info tab updates promote to prod without #2634 and #2631 ?

**Comment by aishwarya2505** [comment]
I am afraid not. Since these commits were made together, some info updates share commit ids with process and procedure updates.

**Comment by TracyLinder** [comment]
@aishwarya2505 thank you for the info. This will stay in ready to deploy, pending the approval of the other 2 tickets.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 

## **Approved and ready for Deployment to PROD🎉🎉🎉!!**

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @Sreelatha-BlazeKannan @TracyLinder I have sent this to the DevOps CM Team for PROD deployment under **SCTASK0105644**

## **Status:**
Waiting on Promotion to PROD by the DevOps CM Team

**Comment by TracyLinder** [comment]
This is done; closing issue;
