### ISSUE TITLE
Feature request: TIA Folder Process Cleanup(TL) 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2634]
### As a TIA reviewer, I need the folder processes to be useful. Currently none of the folder processes provide any value to us. We only need 1 process that allows us to document final TIA approval. 
_This looks ready for development._

**Stakeholders:**
Nazlie, Sangeeta

**DTS Manager:**
Tracy Linder

**Acceptance Criteria:**
- At initial folder creation, process 'Initial Intake' process is inserted
    - Process is not assigned to a user
    - 'Calculate Fees' attempt will delete any existing fees, and inserts the correct fees according to the folder info values, and updates folder status to 'Pending Payment'
    - Saving 'Calculate Fees' attempt will not close the process
    - No fees are inserted if info 'Type of Analysis' value is Subdivision or Other
    - No fees are inserted if info 'Proposed Trips Per Day' value is Other
    - 'Entered' attempt will not save if there are unpaid/unbilled folder fees
    - 'Entered' attempt when saved will close the process and insert Submittal Intake' process
- When folder fees are paid, the folder status updates to 'Paid'
-  Submittal Intake' process, on 'Complete' attempt will update folder status to 'Approved', insert folder Issue Date, and close the process.

**Comment by TracyLinder** [comment]
Prioritization From Customer:

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/284e82ce-c125-4578-b452-bf297cfbb368)

**Comment by Sreelatha-BlazeKannan** [comment]
Submitted the Demo on 06/19/2020. Waiting for feedback.

**Comment by TracyLinder** [comment]
Will watch demos #3216

**Comment by TracyLinder** [comment]
**Status:**
- Pending Tracy's approval to move to DEV
- Updating to Sprint 29

**Comment by Sreelatha-BlazeKannan** [comment]
@aishwarya2505 , @Nadin-Nader - As per Nadin this is already in DEV. Martin Deployed it today morning!

**Comment by TracyLinder** [comment]
Acceptance Criteria needs to be updated

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Aishwarya is working on the changes

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 The demo looks great. Please promote to DEV.

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @TracyLinder @Sreelatha-BlazeKannan I have submitted the request for deployment to DEV to the CM DevOps Team:
Task fo CM DevOps team is SCTASK0091486.

**Status:**

Waiting on CM DevOps team to deploy to DEV (SCTASK0091486)

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @TracyLinder @Sreelatha-BlazeKannan This has been deployed to DEV by George at CTM

**Comment by aishwarya2505** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan Tested this in DEV , FolderRSN 11894774 and the changes work as expected.

**Comment by Nadin-Nader** [comment]
**Status:**
Ready for UAT on DEV

**Comment by TracyLinder** [comment]
### DEV UAT Feedback

- We encountered one issue with the calculate fees attempt. See feedback in [this](https://web.microsoftstream.com/video/e6b2b864-41ca-4d18-96a1-09decb2fea26) video.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Aishwarya will start looking into this.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader  Aishwarya tested and updated the same. Need more info from Tracy on Folderrsns to do further review.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder I have sent this to the CM DevOps Team to deploy to TEST under TASK SCTASK0101403.

**Status:**

Waiting on CTM to deploy to TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder this has been deployed to TEST.

**Status and Next Steps:**

UAT on TEST

**Comment by aishwarya2505** [comment]
Tested this on TEST 12396002. @Nadin-Nader @TracyLinder @Sreelatha-BlazeKannan

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder I have UATd this on TEST (RSN:**12396019**) and it met all of the acceptance criteria below:

- [x] At initial folder creation, process 'Initial Intake' process is inserted
- [x] Process is not assigned to a user
- [x] 'Calculate Fees' attempt will delete any existing fees, and inserts the correct fees according to the folder info values, and updates folder status to 'Pending Payment'
- [x] Saving 'Calculate Fees' attempt will not close the Initial intake process
- [x] No fees are inserted if info 'Type of Analysis' value is Subdivision or Other
- [x] No fees are inserted if info 'Proposed Trips Per Day' value is Other
- [x] 'Entered' attempt will not save if there are unpaid/unbilled folder fees
- [x] 'Entered' attempt when saved will close the process and insert Submittal Intake' process
- [x] When folder fees are paid, the folder status updates to 'Paid'
- [x] Submittal Intake' process, on 'Complete' attempt will update folder status to 'Approved', insert folder Issue Date, and close the process.

**Comment by TracyLinder** [comment]
UAT with stakeholders scheduled for 10/29

**Comment by TracyLinder** [comment]
### UAT Results (Passed, With Note)
- The AC has been met however there are proposed changes documented on issue #2631 ; in [this comment](https://github.com/cityofaustin/atd-data-tech/issues/2631#issuecomment-719008702)

**Comment by TracyLinder** [comment]
### UAT IN DEV PASSED, PLEASE PROMOTE TO TEST

**Comment by aishwarya2505** [comment]
Tested 12396584 in TEST. Changes work as expected

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @Sreelatha-BlazeKannan @TracyLinder 

## **Approved and ready for Deployment to PROD🎉🎉🎉!!**

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @Sreelatha-BlazeKannan @TracyLinder I have sent this to the DevOps CM Team for PROD deployment under **SCTASK0105644**

## **Status:**
Waiting on Promotion to PROD by the DevOps CM Team

**Comment by TracyLinder** [comment]
This is done; closing issue;
