### ISSUE TITLE
COVID-19 Time Tracking App Demo

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2635]
Run a COVID-19 Time Tracking app demo for HR on 5/20/2020.

**Comment by dianamartin** [comment]
## Diana's Notes

### Participants: 
- **ATD:** Dan, Peggy, Jace, Diana, John
- **External ATD:** Demtrise H., Zachary O., Dibona M., Ludwig B., Taylor K., Andrew P.

**Comment by JaceDeloney** [comment]
**Highlights:**

- Interested in the employee-to-supervisor mapping, asked how that was done
- Asked about integrations with Teams or other widely-used software like Sharepoint
- Asked multiple times about how Knack supports the use of locations (either by list or by lat/long)
- Curious about how to support volunteers and other people that did not have a CoA login

The vibe was that it is a bit too late for this tool to be adopted citywide. But they were all very interesting in using a similar solution for future emergency events.
