### ISSUE TITLE
Feature: Wipe information when vehicle field is hidden in RPP application

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2637]
## User Story
As a RPP resident when I reduce the amount of decals it should only show my vehicle fields for my vehicle. 

### Example
Ex. If number of decals is 2 then these fields show up
- License 1
- State 1
- License 2
- State 2

### What happens
If number of decals is reduced to 1 then these already populated License/State fields show up
- License 1
- State 1

This field is hidden, but is still populated
- License 2
- State 2

I have to use a display rule to hide if from the Review page and Invoices, but that `License 2` and `State 2` are still populated and in the database. 

### What we'd like to happen
I'd like for the hidden vehicle fields to be `wiped` out when the form is submitted from an `Edit` form.

**Comment by JaceDeloney** [comment]
@dianamartin can you remind us when this is due? Trying to prioritize other work and want to understand what our committed-to deadlines are.

**Comment by dianamartin** [comment]
@JaceDeloney Would like this by June 1st, planned soft-launch for RPP Staff to start using the back end.

**Comment by amenity** [comment]
@mateoclarke @moorerst @dianamartin - any updates on this issue?

**Comment by dianamartin** [comment]
I thought this needed to be scheduled on the Dev side. This hasn't been done yet to my knowledge.

**Comment by moorerst** [comment]
@mateoclarke any update on when this can be scheduled? We are currently in the soft launch phase. The earliest customer go live date is July 1st. Can this be scheduled prior to customer go live? Are there any outstanding questions regarding the issue? Thanks

**Comment by mateoclarke** [comment]
Hey y'all, my apologies for missing the `@mentions`. As I mentioned via Slack, we have this prioritized for Sprint 27 so we will be able to delivery by 7/1. I'll reach out to @dianamartin if I run into any questions during implementation.

**Comment by mateoclarke** [comment]
- scene_179
- scene_142
- scene_189

**Comment by johnclary** [comment]
@mateoclarke do you need more info from `Apps` team on this? if so, please slack me/Diana/Stephanie. Thanks

**Comment by amenity** [comment]
@moorerst is going to follow up on this and update pipeline/milestone.

**Comment by amenity** [comment]
@moorerst @mateoclarke — any updates on this?

**Comment by ChrispinP** [comment]
I dont think this is needed any longer. I have rules in place to set the license plate fields to blank on application submission if number of decals does not match. Since state fields default to Texas, these will show if application is not submitted but when submitted are also set blank if its corresponding license plate is blank.
