### ISSUE TITLE
Meeting: Sync w/ Launch IT on Backlog Initiative

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2639]
### Meeting Info:
**Date/Time:** 5/13/20 , 1:30pm
**Attendees:** Tracy, Raj
**Agenda:**
- Update on The Jets
- ATD AMANDA Devops Branch
- Scrum of Scrums
- Trello vs Github/Zenhub

**Comment by TracyLinder** [comment]
- Update regarding The Jets
- ATD AMANDA branch
    - He thinks this is great, and will ask his team to use this branch for ATD work
    - [ ] Sree has the devops credentials. Make sure she can access the branch. 
    - He requested 3 more resources to do dev ops (needs Gita approval). 
- Scrum of Scrums vs daily standups
    - He talks to DSD daily in the morning, for an update (separate from the 1pm standup)
    - He's suggesting a daily standup, at least at first. 1:30 daily should work - this is for high level (he's calling it a leadership meeting)
    - [ ] Tracy to setup daily standup: Raj, Tracy, Deb
- Trello vs Github/Zenhub
    - Sree is comfortable using Zenhub. 
    - [ ] Make sure she's got her own credentials. 
    - Raj will send me a list of people who should have access to our boards

**Comment by TracyLinder** [comment]
@Nadin-Nader as you get the ATD devops branch setup, can you be sure that Sree and Robert L have the credentials they need to work in it? Thanks!

**Comment by TracyLinder** [comment]
**Email to Deb & Kaarthy:**

Hi Deb and Kaarthy,

I’d like to schedule a daily scrum of scrums meeting (thanks for the suggestion Deb). Raj will attend for LaunchIT, and I’ll attend for ATD. Who will be attending for The Jets? 
Will 1:30 daily work? 

Thanks!

Tracy Linder, Product Manager

**Comment by Nadin-Nader** [comment]
@TracyLinder I did not know Sree needed access to our DevOps Branch. She shouldnt need access to ours if she has access to LIT to make changes. I have no issues with Sree having access to it but it usually causes less confusion if a user only works out of one DevOps Branch. Robert should be getting access to it as he is in the ATD project team and i believe will only be working out of our Branch for changes. I will reach out to Sree and ask her for her USERID.
