### ISSUE TITLE
AMANDA Backlog Funding Update

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2643]
Check in w/ ATD Finance to determine funding streams and budget amounts for:
- LIT engagement
    - 5125-2400-7781-6203 confirmed by Peggy M. today via email
    - Erin W. (DSD) to perform monthly JVD
- The Jets engagement

**Comment by TracyLinder** [comment]
@johnclary any update on this?

**Comment by johnclary** [comment]
@TracyLinder just spoke w/ about it Peggy today. we have $250k this year and next for amanda work. let's plan on checking in quarterly to review our total spend but i think we're covered for the work we've identified, right?
