### ISSUE TITLE
Access to Safe Street Web Map - Kaz W.

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#2645]
Kaz emailed asking about getting access to the Safe Street Web Map. When he tried to open it he got an error about the Urban Trails layer and not having permission.

**Comment by jaime-mckeown** [comment]
I checked the map and ATD Publisher could not open the Web Map either. The map is owned by Nathan W., so I emailed to ask him about the sharing of the urban trails. He said he is working with PW regarding that issue and hopes to have it fixed soon.

**Comment by jaime-mckeown** [comment]
- Nathan got the urban trails layer fixed as the map now opens.
- Laura D. just emailed asking how her/Kaz can download the data in the Web Map. Nathan will need to update the settings, if he can't change that then ATD Publisher will need to take ownership to allow the data to be exported by others.

**Comment by jaime-mckeown** [comment]
Alan has been helping ATSD out with these maps. Re-assigning to him.

**Comment by alan-deanda** [comment]
I've added the ability to download data from the webmap and notified/sent instructions to Laura D. on how to do it.
