### ISSUE TITLE
ATD Fee Waiver Reasons Update (TL)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2647]
### As an ATD manager, I need those waiver reasons to make sense for reporting purposes, and better align to our business workflow. 

**Stakeholders:** Kim, Paloma, Maria, Van, Dan
**DTS Manager:** Tracy

**Acceptance Criteria:**
- Add 2 Fee Adjustment Reasons
    - Council Approved Waiver
    - Ordinance Mandated Waiver
- Both fees map to waiver group 5090 (other)

**Comment by TracyLinder** [comment]
**ROW Waiver (Adjustment) Reasons:**

- Smart Housing (already on list)
- Council Approved Waiver 
- Ordinance Required Waiver

**Using:**

- SMART Housing
- City Department (will stop using)
- Other
- General Adjustments

**Comment by TracyLinder** [comment]
### OSE

**Currently Using**
- Events

**Needs**
- None, Events is working

**Comment by TracyLinder** [comment]
Acceptance criteria has been updated; this is ready for development.

**Comment by TracyLinder** [comment]
Council Approved Waiver - Map to 5090 (Other)
Ordinance Mandated Waiver - Map to 5090 (Other)

**Comment by TracyLinder** [comment]
**Status:** Development done and in Local. Pending promote when @Sreelatha-BlazeKannan  is ready. Updating to sprint 29.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Changes are completed however waiting on #2388 epic to move from Localhost to Dev

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - DEV depoyment plan submitted on 09/22/2020

**Comment by Nadin-Nader** [comment]
Passed Dev UAT.
@Sreelatha-BlazeKannan I have sent the deployment plan for the deployment to TEST. It is with the CM Team under **SCTASK0098516**

**Status:**
Waiting on deployment to TEST from DevOps CM Team

**Comment by Nadin-Nader** [comment]
**Next Step:**
UAT in TEST

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - TEST UAT Pending

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have tested this on TEST with RW folder 12389050 and saw the new adjustment reasons that were in the acceptance criteria. Looks good to me for Stakeholder UAT/Approval

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Need feedback so that this can be moved to PROD.

**Comment by TracyLinder** [comment]
### Approved for PROD 🎉

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have sent the deployment request over to the CM DevOps team under SCTASK0100692.

## **Status:**
Waiting on CM DevOps to deploy to PROD under4 SCTASK0100692

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder  this has been deployed to PROD. I will send an email to the stakeholders and move to closed

**Comment by Nadin-Nader** [comment]
Emailed the stakeholders (Kim, Paloma, Van, Maria) and will now close the card:

> Good Afternoon Everyone,
> 
> Hope you are all doing well. I am reaching out regarding the request to update the ATD Fee Waiver reasons. I wanted to inform you that the changes are now in PROD and ready for you to use. 
> 
> I will go ahead and update the ZenHub card and close it out but if you have any questions or concerns, please feel free to email me or Tracy.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services
> Austin Transportation Department
