### ISSUE TITLE
Explore 'Tasks' as a way to create child records for VZA.

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2652]
explore the possibility of the  Tasks function to insert child records instead of Record Rules.

**Comment by SurbhiBakshi** [comment]
1. Lewis prefers to schedule via calendar, this does not have the 'Record Rule' functionality needed to create child records via form submission.
2. Batch copying process of assignments on a month to month basis also cannot take advantage of the Record Rules functionality available in the standalone form submission.
3. My hesitation with a scripted approach is not knowing how much I can support that process.
4. Moving away from 'Record Rules' to 'Tasks' and shifting the triggers from Pages to Data removes reliance on the Stand Alone Form triggers which are not available for Calendar Event Creation and batch creation of records.
5. I could run the tasks manually after batch creating assignment records for the next month. Would not want to rely on a scheduled job till logic is all refined and ironed out.
6. Need to fine tune and test.

**Comment by SurbhiBakshi** [comment]
Test - 

- [ ] Create an assignment using a stand alone form - Created Date - Task to insert child record

**Comment by SurbhiBakshi** [comment]
- The Tasks functions need filter parameters that will narrow down which assignments (parent records) will need to have child records. 
- A assignment (parent record) which already has child records associated with it should not be targeted by the Task since this could result in the creation of duplicate child records. 
- One way to do this would be to check the number of child records created with the number of officers required by each assignment since the number of child records per assignment should be equal to the number of officers for that assignment as per the Scheduler. 

Parent Records - Assignments set by the scheduler with information regarding date, time, location, and number of officers required for that assignment.

Child records - Officer Assignments as defined by the Number of Officers Required field.
Refine Filter parameters for Tasks to create child records - 

- [ ] A Count of Child Records field that counts the number of child assignments associated with the parent assignment. 

- [ ] A equation field which compares the Count of Child Records field with the Number of Officers Required. 

- [ ] Depending on the comparision, the Task will not process any records which

**Comment by SurbhiBakshi** [comment]
Tasks take a fairly long time to run especially with some filter parameters. Looks like the task literally runs through each record to see if it needs to be processed. I am not sure there is a way to narrow down the records to be processed before the task can start. It takes about half an hour for one task to go through 660 records. Tasks should be run after hours. It might slow the whole app down.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/acc90bbf-85c7-4112-92a5-d96cb8ed8421)

**Comment by SurbhiBakshi** [comment]
If tasks take too long to run, debating if there is potential in archiving assignments records from previous months (for example anything before May 1st at the beginning of June) to make Tasks process faster. Don't think we ever need to relate back to older assignments, especially if reporting will be done outside Knack. Will need to check with Lewis if he ever goes back to particular months to replicate schedules.

**Comment by SurbhiBakshi** [comment]
This is better than yesterday so perhaps no need to worry about time taken to process tasks - ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/16598467-08b5-43fa-89b3-ea6fbeda7297)

**Comment by amenity** [comment]
@SurbhiBakshi - is there anything else you want to explore here or can this be closed?

**Comment by amenity** [comment]
Oh, just saw we put this in _Ready to Deploy_... 🤔 

The exploration is done though, right?

**Comment by SurbhiBakshi** [comment]
@amenity - right now all the work is in a Test instance, and changes still need to be made in Prod, so we put this in Ready to Deploy.
