### ISSUE TITLE
atd-dockless-processing: Design automated Docker-hub pipeline in CircleCI

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#266]
[Backlog] [No Milestone] We should have an automated pipeline to deploy the `atd-dockless-processing` container to Docker hub using CircleCI in a way that:

- [x] Re-builds image on commit
- [x] Uses the branch name as the tag for environments/versioning 
- [x] Use the master branch as the default (latest) or create a production branch for that purpose.

**Comment by johnclary** [comment]
@sergiogcx I believe this is done, yes?

**Comment by sergiogcx** [comment]
Ah, yes. Moved to Review Q/A (for tomorrow)

**Comment by sergiogcx** [comment]
So the pipeline was implemented for `atd-data-publishing` and not for `atd-dockless-processing`, since I created a new issue for this specific purpose, I will be closing this one.
