### ISSUE TITLE
RPP Design Review 5/15

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2660]
### Objective 
Review RPP Application

### Participants
John, Mateo, Amenity, Surbhi, Stephanie and Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes

CLOSE X
Rename Review Requirements "Get Started"
Home Button - normal link
Remove header - "Ready to Begin"
- Make more Bold: "You will not be able to pay online at this time"

Permit Costs - put in Google Docs
Applicant Type: change to radio buttons
Change permit banner: "Combination of resident decals and visitor hang-tags may equal up to 4."
All hyper links - "underline"
Look up address (remove icon)
info button - pop-up 

Recommend it to them - remove "RPP Eligibility Listing"

Remove the text underneath Permit Fields
Create a new 

Remove all "Numbers in Title"
Part 2.1 - Permit and Vehicle Information
Remove "Part 2.2 Vehicle Information" 

My drivers license matches current address
Proof of Residency - conditional display
Match to "Vehicle(s) Added" Permits and Day Passes

**Comment by moorerst** [comment]
@dianamartin  a few observations:

- [ ] On the Am I Eligible page - can the red star for Required be removed or moved
- [ ] On the results page for Am I Eligible - can the Instructions be removed from the top

 when it's displaying the results of the lookup

- [ ] Permit Information/Cost page - capitalize Permits for Resident Decal and Hang Tag headings
- [ ] Permit Information page - are we keeping the Resident Address title that is above the address?
- [ ] Review Page Banner - remove the period from bullet # 3

- [ ] Review Page Green Banner - should that information be in 1, 2, 3, format like the other banner
Wording change - Please enter the number of residential vehicles in the form below that will be receiving a decal sticker. If no vehicle fields appear, you do not need to enter a vehicle.
**Please enter the number of residential vehicles that will be receiving a decal sticker.** 
Love the radio buttons for Applicant Type and the Info buttons for Permit Cost/Info

**Comment by dianamartin** [comment]
> 
> 
> @dianamartin a few observations:
> 
>     * [x]  On the Am I Eligible page - can the red star for Required be removed or moved
> 
> 
> > I can't move it, but I added `Residential Address` to give it a label.
> 
>     * [ ]  On the results page for Am I Eligible - can the Instructions be removed from the top when it's displaying the results of the lookup
>       @moorerst This might be a dev thing
> 
>     * [ ]  Permit Information/Cost page - capitalize Permits for Resident Decal and Hang Tag headings
>       @moorerst I don't know what part this needs to be changed on
> 
>     * [x]  Permit Information page - are we keeping the Resident Address title that is above the address?
> 
> 
> > I changed this to `Address`
> 
>     * [x]  Review Page Banner - remove the period from bullet # 3
> 
>     * [ ]  Review Page Green Banner - should that information be in 1, 2, 3, format like the other banner
> 
>     * @moorerst Not sure which banner you're referring to
> 
>     * [x]  Wording change - Please enter the number of residential vehicles in the form below that will be receiving a decal sticker. If no vehicle fields appear, you do not need to enter a vehicle.
>       **Please enter the number of residential vehicles that will be receiving a decal sticker.**
>       Love the radio buttons for Applicant Type and the Info buttons for Permit Cost/Info
