### ISSUE TITLE
RW, OSE - Info Tab Cleanup (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2662]
### As a OSE reviewer, I need the some of the RW, OSE folder infos removed that are not useful to the workflow. I also need to make change the requirement for some of the infos.

**Stakeholder:** Maria A
**DTS Manager:** Nate

**Acceptance Criteria:**
- Infos that are listed as not needed on the spreadsheet will be removed
- Make changes to infos as needed from the Spreadsheet (changes to descriptions or being required)
- Exclusions will be on the RW SubType = Street Event; not all folders
- Infos will be the same across all work-types for the Street Event Subtype of RW

**Comment by Nadin-Nader** [comment]
Hi Maria,

Hope you are doing well. I am reaching out to you regarding #2662 RW, OSE - Info Tab Cleanup and #2664 OSE Folder Status Bug. I was wondering if we could set up a meeting for a quick overview on what is going on and what the goal of the request is. I also want to go ahead and define the acceptance criteria for the requests that we have so far.

I have time tomorrow Tuesday 6/9/2020 from 1-2pm or 3-4pm and I also have Wednesday 6/10/2020 from 10-11am or 1-2pm. Please let me know what time works best for you and we can schedule a call.

Once we have the information for this, we will be able to move this along and start getting it looked at further or worked.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by Nadin-Nader** [comment]
Waiting on response from Maria

**Comment by Nadin-Nader** [comment]
Hi  Maria,

Sorry for the second email but I also wanted to include  #1709 OSE New Process for NPH. We can have a quick conversation on this one to get it started as it may require  lots of details to go over a new process.

Please let me know what day works for you from my previous email (tomorrow Tuesday 6/9/2020 from 1-2pm or 3-4pm and I also have Wednesday 6/10/2020 from 10-11am or 1-2pm)

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by Nadin-Nader** [comment]
After meeting with Mari she informed me that she will need to go through the info list and we will need to scrub them and clean it up. Waiting on List from Maria

**Comment by Nadin-Nader** [comment]
Maria sent the initial list of info that need to be cleaned up but the spreadsheet has extra tabs on it with notes that may note be associated with the request.
The info tab list also has questions and comments in the Notes columns (along with who needs to be deleted) that we will need clarification on.

**Next Step**

- Schedule clarification meeting with Maria
- Mark the infos properly with what needs to happen
- Delete the infos ourselves or give to the Jets. Either way it need to go through DevOps


[https://app.zenhub.com/files/140626918/90aead7b-501d-43ad-9796-9b3edf7ca495/download](https://app.zenhub.com/files/140626918/90aead7b-501d-43ad-9796-9b3edf7ca495/download)

**Comment by TracyLinder** [comment]
**Status: A bit more analysis needing to be done before this is ready for dev. Hope to be dev-ready by sprint 28.

**Comment by Nadin-Nader** [comment]
@TracyLinder  I have looked over the info list and determined that this will need to go to one of our Dev teams for completion. There are a little over 50 changes to be made to the infos. Changes such as making some required and removing infos. The majority is removing infos. They also have a couple of questions for the Developers for some of the infos which may require a small meeting to iron it out.

[https://app.zenhub.com/files/140626918/8de0f188-fdbd-4447-a54b-ad361308c674/download](https://app.zenhub.com/files/140626918/8de0f188-fdbd-4447-a54b-ad361308c674/download)

**Comment by TracyLinder** [comment]
@Nadin-Nader please add acceptance criteria to this issue, get it backlog ready, and update the pipeline. Thank you!!

**Comment by licarir** [comment]
@Nadin-Nader Where is the Excel spreadsheet? Is it one of the links that say app.github.whatever/download above? I am working from this for now.

https://app.zenhub.com/files/140626918/8de0f188-fdbd-4447-a54b-ad361308c674/download

**Comment by licarir** [comment]
@Nadin-Nader There are 63 records, not 40. I guess 40 say remove, some say no action and some are highlighted. Are the highlighted ones ones that need to be changed?

**Comment by licarir** [comment]
@Nadin-Nader Do you have any update for me?

**Comment by Nadin-Nader** [comment]
@licarir Yes the highlighted ones need changes made to them and they would like the exclusion to RW and not just Sub but i am still waiting on Marias response. Lastly, Maria's last name is Alonso.

**Comment by Nadin-Nader** [comment]
@licarir I was wrong, Maria would only like the exclusions to be for the SubType Street Event and not all RW

**Comment by Nadin-Nader** [comment]
Sent message to Robert asking to see if he received my info:

[9:59 AM] Nader, Nadin
    Morning. Hope you and your fam are doing well. Hey just wanted to make sure you got my response for 2662

**Comment by Nadin-Nader** [comment]
From Robert on 7/22:

> [7/22 12:58 PM] Licari, Robert
>     Hey Nate, sorry for the delay. Yes, I got your response and am working on getting the exclusions entered. I went through and added 20 and then clicked save but some of them already existed so it wouldn't let me save and I had to start over. I am in the process of verifying the excel sheet to see what actually needs to be changed now.

**Status:**
Robert is still working on the exclusions and verifying the worksheet info

**Comment by TracyLinder** [comment]
**Status:** Robert working to incorporate feedback from Maria. Work to continue in sprint 30. Currenlty in branch.

**Comment by TracyLinder** [comment]
**From Maria:**

Hi, 

Thanks for looking into that! Please remove the code Amplified Sound fee, we no longer charge that fee. Please keep the Safety Inspection Fee as that one is still part of the ordinance.

Thanks and let me know if I can help with anything else!

**Comment by Nadin-Nader** [comment]
@licarir just wanted to make sure that you got the message posted by Tracy from Maria:

From Maria:

Hi,

Thanks for looking into that! Please remove the code Amplified Sound fee, we no longer charge that fee. Please keep the Safety Inspection Fee as that one is still part of the ordinance.

Thanks and let me know if I can help with anything else!

**Comment by licarir** [comment]
@Nadin-Nader I got the note. The changes made it to Dev. I unit tested there and found an issue. I have fixed the issue and resubmitted to Dev again. Somehow that info that I had taken out of the exclusions did not save properly and caused the same error. I removed it again on Branch and retested and it shows up properly in the export so it should work fine this time. Will retest on Dev and promote to Test as soon as it is ready, hopefully by tomorrow.

**Comment by licarir** [comment]
@Nadin-Nader @TracyLinder This change has made it to TEST. Please UAT and hopefully we can get this to PROD this week/early next week. Thank you.

**Comment by Nadin-Nader** [comment]
@licarir I will UAT today

**Comment by licarir** [comment]
@Nadin-Nader Did you have a chance to UAT change 2662 yet? Thank you.

**Comment by Nadin-Nader** [comment]
@licarir Currently reviewing

**Comment by Nadin-Nader** [comment]
@licarir Hey i UAT'd this on TEST and found that there were no changes. I checked on DEV again and the changes were there.
![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/36d55bae-06de-4a76-98c3-6be4ae427180)

Do the changes need to be promoted to TEST from DEV again?

**Comment by Nadin-Nader** [comment]
@licarir @TracyLinder 

After creating a new folder instead of looking at ones already created, the change is on TEST now and looks good. I will let Maria know and ask her to TEST before moving to PROD. 

Once approved by Maria. we can get this promoted to PROD.

**Comment by Nadin-Nader** [comment]
Sent email email to Maria asking her to test on TEST.

**Comment by Nadin-Nader** [comment]
@licarir Went over this with Maria and Tracy and found that there were several things that werent done and/or were removed by mistake. We also noticed that the Event type Pick list does not have the new options. Please go ahead and complete the changes needed and let me know when its done so i can UAT.

Safety Inspection Fee - Remove
Parking Reservation - Make Mandatory
Event Type - Update pick list w/ values provided by Maria
Date notification mailed? - Was removed but shouldn't have been
Reason for Request - Was removed but shouldn't have been
Activate Upon Payment - Was removed but shouldn't have been
Traffic Control Plan Submitted - Was removed but shouldn't have been
Date notification mailed? - Was removed but shouldn't have been

**Comment by licarir** [comment]
@Nadin-Nader 
Maria said keep Safety Inspection fee (75040) as there is code in another fee procedure that requires that exist. That email is in the notes above.

79275 Date Notification Mailed is not in the exclusion table for RW so I didn't take it off, it may not be defaulted on the folder.
75001 Activate upon payment is also not in the exclusion table for RW.
75940 Reason for Request was already in the exclusion table  for RW before I did this change
75075 Traffic Control Plan Submitted not in the exclusion table for RW
79275 Date Notification Mailed is on the list twice above.

**Comment by TracyLinder** [comment]
**Status:** Robert has made the updates, currently in audit review. Hope to be ready for UAT ASAP. Updating to sprint 31.

**Comment by Nadin-Nader** [comment]
Sent email asking for clarification:

Maria,

Hope you are doing well. I am reaching out to you about 2662. Robert looked over the corrections that were needed and made some updates. He also added the following comment:

Maria said keep Safety Inspection fee (75040) as there is code in another fee procedure that requires that exist. That email is in the notes above.
79275 Date Notification Mailed is not in the exclusion table for RW so I didn't take it off, it may not be defaulted on the folder.
75001 Activate upon payment is also not in the exclusion table for RW.
75940 Reason for Request was already in the exclusion table for RW before I did this change
75075 Traffic Control Plan Submitted not in the exclusion table for RW
79275 Date Notification Mailed is on the list twice above.
Can you please let me know how you would like to Proceed with these as it is the only thing left until this goes to PROD.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by Nadin-Nader** [comment]
@licarir Here is Maria's response:

Hi, 

Thanks for  sending this over. 

Here are more questions than answers. 
Maria said keep Safety Inspection fee (75040) as there is code in another fee procedure that requires that exist. That email is in the notes above. 
Sounds good. I assume this means the auto add of the fee per day? Shouldn’t be a big deal to keep it as is. As it doesn’t bill it and we can still edit. 
79275 Date Notification Mailed is not in the exclusion table for RW so I didn't take it off, it may not be defaulted on the folder.
What does this mean? That it can’t be removed because it would affect other RW folders?

75001 Activate upon payment is also not in the exclusion table for RW.
As long as this is defaulted to ‘No’ it is fine to keep if needed. 

75940 Reason for Request was already in the exclusion table for RW before I did this change
So this one was already removed is what I’m gathering? Sounds good.

75075 Traffic Control Plan Submitted not in the exclusion table for RW
Not sure what this means. 

79275 Date Notification Mailed is on the list twice above.
Guess I really don’t want that on there. HA! 
I hope that helps.

**Comment by TracyLinder** [comment]
**Further Work:**
- Parking Reservation - Make Mandatory
- Event Type - Update pick list w/ values provided by Maria
Food Truck
Sidewalk Closure
Display Vehicle
Alley Closure
Escort
Festival
Parade
Run
Safety
Walk
Other

This work has been done in branch. @licarir will work on getting it promoted to Test.

**Comment by licarir** [comment]
![image.png](https://images.zenhubusercontent.com/5ebae52ece896d5e6d9acd69/89ca2470-2958-4ff3-bb19-5a59d2501726)

**Comment by licarir** [comment]
@TracyLinder @Nadin-Nader These last two changes have made it to TEST for UAT now.

**Comment by TracyLinder** [comment]
@Nadin-Nader do you think you'll be able to do the first pass of UAT this week?

**Comment by Nadin-Nader** [comment]
@licarir I was able to UAT this on TEST and it looks like the changes and new work are all there. This is ready for PROD deployment

**Comment by Nadin-Nader** [comment]
**Status:**
This on PROD now per Robert. I will email Maria and let her know

**Comment by Nadin-Nader** [comment]
Hi Maria,

Hope you are doing well. I am reaching out to you regarding Request 2662 RW, OSE - Info Tab Cleanup. I has been completed and the changes deployed to PROD. I will now close the card.

Please let me know if you have any issues with it.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department
