### ISSUE TITLE
OSE Folder Status Bug

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2664]
### As an OSE reviewer, when we copy RW Street folder, the default initial status is 'Pending Payment'. It should be 'Pending'. 

**Acceptance Criteria:**
- After initial copying of RW folder (SUB = Street Event), the default folder status needs to be "Pending" and NOT "Pending Payment". 
- Changes only apply to RW, Subtype Street Event

**Note:**
Fees are assessed later

**Comment by TracyLinder** [comment]
**Status:** Was not able to pull in to Sprint 25. Updating to 26.**

**Comment by Nadin-Nader** [comment]
Hi Maria,

Hope you are doing well. I am reaching out to you regarding #2662 RW, OSE - Info Tab Cleanup and #2664 OSE Folder Status Bug. I was wondering if we could set up a meeting for a quick overview on what is going on and what the goal of the request is. I also want to go ahead and define the acceptance criteria for the requests that we have so far.

I have time tomorrow Tuesday 6/9/2020 from 1-2pm or 3-4pm and I also have Wednesday 6/10/2020 from 10-11am or 1-2pm. Please let me know what time works best for you and we can schedule a call.

Once we have the information for this, we will be able to move this along and start getting it looked at further or worked.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by Nadin-Nader** [comment]
Waiting on response for meeting request to go over

**Comment by Nadin-Nader** [comment]
Hi  Maria,

Sorry for the second email but I also wanted to include  #1709 OSE New Process for NPH. We can have a quick conversation on this one to get it started as it may require  lots of details to go over a new process.

Please let me know what day works for you from my previous email (tomorrow Tuesday 6/9/2020 from 1-2pm or 3-4pm and I also have Wednesday 6/10/2020 from 10-11am or 1-2pm)

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by Nadin-Nader** [comment]
After speaking to Maria about this she informed me that when they copy over from the RW folder with the SubType Street Event, the folder status used to be "Pending" when they first got copied over. Now the folder goes into a "Pending Payment" and it shouldnt. Th fees are worried about later.

**Comment by licarir** [comment]
I found this code in DefaultFee_RW_NEW which appears to be the problem. When it runs F_UPDATE_STATUSCODE to 50600 'Pending Payment', that is where we need to change it to 50005 (Pending) status.

-- Start Mathi 06/06/2018 -- TN989:Folder Created via BO, Update folder stauts into Pending Paymnet
SELECT COUNT(*) INTO ln_FeeCount
FROM   AccountBillFee
WHERE  AccountBillFee.FolderRSN = argFolderRSN AND AccountBillFee.FeeAmount > 0;

IF (NOT (DUserID LIKE '%@%' OR DUserID = 'INTERNET'))  AND (ln_FeeCount > 0) THEN
  lv_error := COA_FOLDER.f_update_statuscode(argFolderRSN,50600);
  IF lv_error IS NOT NULL THEN
     raise_application_error(-20001, lv_error);
  END IF;
END IF;
-- End Mathi 06/05/2018

**Comment by licarir** [comment]
@TracyLinder @Nadin-Nader 
Does any other department use these folders? Does this type of folder and status combination ever need to go into Pending Payment status by default? If not, this is a very easy change to one line of code if I am correct.

**Comment by TracyLinder** [comment]
@licarir I don't think any other department uses RW-Street Event. It doesn't ever need to go into pending payment by default, from what I understand.

**Comment by Nadin-Nader** [comment]
@TracyLinder Had the meeting/Demo with Maria, Kaarthy, Robert and Deb to show that the status of the RW SE folder doesnt go to Pending Payment anymore when copied. It also did not pick up the fee that was on the original. Maria was happy about it.

**Next Steps**
Robert will send to CM Team to promote the changes
Maria will UAT  
Should be in PROD by end of week if UAT Bandwidth is open  (Maria said it should be)

**Comment by TracyLinder** [comment]
**Status:** Currently in DEV, needs to be tested before moving to Test for customer UAT
- Nate will do the DEV test

**Comment by Nadin-Nader** [comment]
@TracyLinder @licarir  I have Tested this on DEV and the folder does not go into a Pending Payment status when copied. It goes to a Pending as it should.

**Next Step:** Move to TEST

**Comment by TracyLinder** [comment]
**Status:** In Test as of today; next Nate or Tracy to test and approve promote to Prod.

**Comment by TracyLinder** [comment]
**Status:** Pending promote to Prod

**Comment by licarir** [comment]
@TracyLinder @Nadin-Nader  Submitted to PROD.

SCTASK0081392

**Comment by TracyLinder** [comment]
This went to prod on 7/27. Maria has been informed by Robert & Nate. Closing issue.
