### ISSUE TITLE
(Duplicate) OSE Fee Insert Change (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2665]
### Will be developed as part of #2666

**As an OSE Reviewer, I'd like to manually add all folder fees to the RW-Street Event folder.**
**Currently the 'Event Permitting' process inserts 2 folder fees that we have to delete. Please make this stop.**
**Currently a fee is inserted a folder creation. Users delete this.**

**Stakeholder:** Maria A
**DTS Manager:** Nate

**Acceptance Criteria:**
- From start to finish, the RW-Street Event folder does not automatically insert any folder fees.

**Comment by TracyLinder** [comment]
This should be ready for development.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Aishewarya sent the Demo for review on 09/03/2020. Waiting for your feedback.

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @Sreelatha-BlazeKannan Reviewed the demo and it looks good, no Fees were automatically added during both scenarios. I approve

**Comment by aishwarya2505** [comment]
This is ready for test in DEV. This can be moved to TEST post testing #1709 in DEV as the changes overlap one another. @Nadin-Nader @TracyLinder

**Comment by TracyLinder** [comment]
**Status:** Currently in DEV; it cannot be moved to TEST until #1709 is complete.
