### ISSUE TITLE
(EPIC) OSE Folder Process Cleanup (On PROD🎉🎉) (Waiting a Week to close)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2666]
## As an OSE reviewer, I need the folder processes updated to add more value and efficiency to our AMANDA usage. I would like to have the Processes, their attempt results and what those processes and attempts do to the folder reviewed to better fit our workflow.

**Stakeholder:** Maria A.
**DTS Manager:** Nate

**Acceptance Criteria:**
**This will apply to the RW SubType: Street Event (50510)**

- Customer applies online/submits
- System inserts process 7000 Web Acceptance (Same; no changes)
- Upon saving 'Accepted' attempt on Web Acceptance the system will:
  -  Update the folder status to ‘Pending’
  -  Insert processes Event Review (50560), Event Intake (50555), Activity Log (80115) and Event Billed (new)
- Event Review (50560) should **not** add any fees when inserted
- **Remove** the "Event Intake" Process (50555)
- **Remove** the "Activity Log" Process (80115)
----

- **(50560) ‘Event Review’** - Attempts: Approved, Awaiting Update, Expired, Rejected, Send Notification Letter, Withdrawn, Cancelled (new)
    -  Is assigned to ‘**_ACE ATD Reviewer_**’ group
    -  ‘Cancelled’ (new) will close the ‘Event Review’ process, update the process status to **_‘Closed’_**, and updates the folder status to **_‘Cancelled’_**
    -  ‘Approved’ changes the folder status to **_‘Pending’_** and closes the process. **_Inserts_** ‘Event Billed’ and ‘Event Permitting’ processes
    -  ‘Awaiting Update’ = **_Please remove_**
    -  ‘Expired’ = **_Please remove_**
    -  ‘Rejected’ changes the folder status to **_‘Rejected’_** and closes the process. **Requires a comment.**
    -  ‘Send Notification Letter’ = **_Please remove_**
    -  ‘Withdrawn’ changes the folder status to **_‘Withdrawn’_** and closes the process. **Requires a comment.**
    -  ‘Cancelled’ changes folder status to **_'Cancelled'_** and closes the process. **Requires a comment.**
-  The Process Date fields should work in the following way:
    -  In Date = The date the process was inserted
    -  Start Date = The date the process was closed
    -  End Date = The date of the start date of the event
## 

- **‘Event Billed’ (New)** is inserted in a **_‘Pending’_** status - Attempts: Billed, Reminder, Cancelled, Paid, Waived
    -  The ‘assigned to’ should be the assigned user
    -  ‘Billed’ will send the customer an email with bill information
        -  Email goes to folder applicant’s Internet User, parent record’s email address
        -  Keeps folder in **_‘Pending’_** status
        - The email verbiage sent to the applicant should be:
          - From Email: 
               - (assigned user, aka whoever created the attempt)
          - To Email: 
               - (applicant email)
          - Subject Line:
              - ACE App. Update: Austin Transportation Special Events Fees Invoiced for [FOLDERNAME]
          - Message Intro:
              - Hello,  
          -  Project Details (Message):
             -  Street Event fees for event [FOLDERNAME] have been billed.  
             -  You can pay online by Check or Credit Card by visiting https://abc.austintexas.gov. Go to 'My Bills' to view and pay your pending invoices.   
             -  Please reach out if you have any additional questions. 
             - Austin Transportation 
             - Austin Center for Events

- ‘Reminder’ will send the customer an email with bill information
    -  Email goes to folder applicant's Internet User, parent record's email address
    -  Keeps folder in **_‘Pending’_** status
    -  The email verbiage sent to the applicant should be:
          - From Email: 
               - (assigned user, aka whoever created the attempt)
          - To Email: 
               - (applicant email)
          - Subject Line:
              - ACE App. Update: Austin Transportation Special Events Fees Invoiced for [FOLDERNAME]
          - Message Intro:
              - Hello,  
          -  Project Details (Message):
             -  ** Street Event fees for event [FOLDERNAME] have already been billed. ** 
             -  You can pay online by Check or Credit Card by visiting https://abc.austintexas.gov. Go to 'My Bills' to view and pay your pending invoices.   
             -  Please reach out if you have any additional questions. 
             - Austin Transportation 
             - Austin Center for Events
-  ‘Cancelled’ will **_close_** the process ("Event Billed") and update the folder status to **_‘Cancelled’_**
-  ‘Waived’ will: **_close_** the process ("Event Billed") and update the folder status to **_‘Pending’_** and** insert process (50560) ‘Event Permitting’
-  ‘Paid’ will **close** the process ("Event Billed") update folder status to **_'Pending'_, and** insert process (50560) ‘Event Permitting’
-  The Process Date fields should work in the following way:
    -  In Date = The date the process was inserted
    -  Start Date = The date the process was closed
    -  End Date = The date of the start date of the event
##

-  **  (50560) ‘Event Permitting**’– Attempts: Approved, Rejected, Cancelled, Withdrawn
    -  This process **is mandatory for permit issuance** (process must be closed before permit issues)
    -  Folder status should stay as **_“Pending”_** until an attempt is entered
    -  The ‘assigned to’ should be the assigned user
    -  Attempts:
        -  'Approved' will: **close** the Process and update the folder status to **_'Pending Permit'_**
        -  'Rejected' will: **close** the Process and update the folder status to **_'Rejected'_**
        -  'Cancelled' will: **close** the Process and update the folder status to **_'Cancelled'_**
        -  'Withdrawn' will: **close** the Process and update the folder status to **_'Withdrawn'_**
    -  **Remove** **_‘Customer Contacted’_** attempt
-  The Process Date fields should work in the following way:
    -  In Date = The date the process was inserted
    -  Start Date = The date the process was closed
    -  End Date = The date of the start date of the event

**Notes on current workflow (Just Informational):**
Once a RW SE Folder gets created in AMANDA or via Portal, it goes into an Event Intake process as "Pending"
Once an attempt of "Accepted"/"Approved" gets placed in the Event Intake Process (Assigned to the ROW Intake Group) the status becomes "Pending ", Cancelled , Withdrawn, Rejected closes the process and folder.
It then creates a new Process called "Event Review" (50560) and inserts a fee that they delete anyways because it is paid by the time they have reviewed the folder.
Then the Permit is issued.

**Link to meeting recording:**
https://web.microsoftstream.com/video/a73eadba-f746-4d23-b1bf-9afd2d7e2de2

**Comment by TracyLinder** [comment]
Hoping to have this backlog ready by sprint 26.

**Comment by TracyLinder** [comment]
**Status: I need to further define the requirements during sprint 26.**

**Comment by TracyLinder** [comment]
Backlog Review w/ Maria: These folder processes are more of a pain than anything else. Some add fees that have to be deleted, another prevents folder issuance until complete. 

**Good First Step:** Document current workflow & identify requirements.

**Comment by TracyLinder** [comment]
Meeting scheduled no 8/18 to begin scoping.

**Comment by Nadin-Nader** [comment]
Sent email to Maria asking for a time toi meet tomorrow to has out the acceptance criteria for this:

> Hi Maria,
> 
> Hope you and your family are doing well. I was reaching out to you regarding the OSE Folder Process Clean Up. I was wondering if you had time to go over this with me so that we can finish scoping it out. 
> 
> I have tomorrow from 10-11, and 330-4 open. It looks like Tracy scheduled a meeting with you to go over this on 8/18, if you have notes from that meeting, please bring them with you if you have them. We will need to document the current work flow and then Identify what changes you are wanting and what it is you are needing the folders to do for you.
> 
> Please let me know if those times work for you. If not, please let me know what are good times to meet and hash out the Requirements for this.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services 
> Austin Transportation Department

**Comment by Nadin-Nader** [comment]
@TracyLinder had the meeting with Maria and came up with a good amount of Acceptance criteria for this issue. Let me know if it looks good or if im missing anything. Sending it to Backlog for now.

Acceptance Criteria:
This will apply to the RW SubType: Street Event (50510)
Remove The "Event Intake" Process (50555) and the "Activity Log" (80115) Process for RW SE folder, they don't use it
Event Traffic Inspection may get changed or deleted at a later date

"Event Review Process"
Keep "Event Review" Process (50555)
Needs to have the "Event Review" (50560) Process first (After Right of Way Process and like the Event Intake Process) instead of the "Event Intake" Process (50555)
Folder should be in a "Pending" status when it first gets created with the "Event Review" Process
"Event Review" should not add any fees as they are usually paid by the time they are reviewing the folder
Folder should stay in a "Pending" and not "Pending Permit" status until an attempt result is entered to change the status of the folder
"Event Review" Process should be assigned to the "ACE ATD Reviewer" group and not "ROW Intake User"
Add "Cancelled" attempt result on Process tab for "Event Review" (50560)
"Cancelled" attempt should close the process and the folder and change the status to "Cancelled"

New Process and Attempts
Create new Process Called "Event Billed" that starts in a "Pending" status
Add new attempts to New "Event Billed" Process, Attempts are: "Billed", "Reminder", "Cancelled" and "Paid"
-"Billed" and "Reminder" Attempts will keep the folder and process open and the folder in a "Pending" status
-"Cancelled" Would close out the folder and place the folder status as "Cancelled"
-"Paid" Would close out the process ("Event Billed"), Keep the folder open and keep the status as "Pending"
New "Event Billed" Process should have a way to send notification to applicant saying that bill has been added to their folder when an attempt of "Billed" or "Reminder" is set

"Event Permitting Process"
Make the "Event Permitting" Process a Mandatory process
Modify "Event Permitting" Process (50565) to be added only once the "Event Billed" Process has a status of "Paid"
Status should stay as "Paid" until an attempt is added to the "Event Permitting" Process (50565)
Add New attempt Results for "Event Permitting" Process:
-"Approved" - will close the Process and set the status to "Pending Permitting"
-"Rejected" - will close the and Folder and set the status as "Rejected"
-"Cancelled" - will close the Process and Folder and set status as "Cancelled"
-"Withdrawn" - Will close the Process and Folder and set status to "Withdrawn"

**Comment by Nadin-Nader** [comment]
## **Updated Acceptance criteria:**

Add additional attempt to new the Process Called "Event Billed" along with the other 3 new attempts listed:
-"Waived" Would close out the Process ("Event Billed"), Keep the folder open in a "Pending" status

**Comment by TracyLinder** [comment]
We will be having a team meeting to scope this request on 11/24/20.

**Comment by TracyLinder** [comment]
### Tracy's Notes on the Acceptance Criteria
FYI @Nadin-Nader 

1. **Customer applies online/submits**
2. **System inserts process 7000 Web Acceptance** (Same; no changes) 
3. **Upon saving Accepted attempt on Web Acceptance the system will:**
- Update the folder status to ‘Pending’
- Insert processes Event Review (50560), and Event Billed (new)
4. **(50555) ‘Event Review’ - Attempts: Approved, Awaiting Update, Expired, Rejected, Send Notification Letter, Withdrawn, Cancelled (new)**
- Is assigned to ‘ACE ATD Reviewer’ group
- ‘Cancelled’ will close the Event Review process, update the process status to ‘Closed’, and update the folder status to ‘Cancelled’
    - `What will the other attempts do?`
5. **(New) ‘Event Billed’ - Attempts: Billed, Reminder, Cancelled, Paid, Waived**
- ‘Billed’ and ‘Reminder’ will send the customer an email with bill information
    - `Why have two attempts that do the same thing?`
    - `Should this email go to the internet user on record for the permit?`
- ‘Cancelled’ will close the process ("Event Billed") and update the folder status to ‘Cancelled’ 
- ‘Paid’ and ‘Waived’ will close the process ("Event Billed") and insert process (50560) ‘Event Permitting’
6. **(50560) ‘Event Permitting’– Attempts: Approved, Rejected, Cancelled, Withdrawn**
- This process is mandatory for permit issuance (process must be closed before permit issues)
- Status should stay as "Paid" until an attempt is added to the "Event Permitting" Process (50565)
    - `I don’t understand this. (Tracy)`
- "Approved" - will close the Process and update the folder status to "Pending Permitting"
- "Rejected" - will close the Process and update the folder status to "Rejected"
- "Cancelled" - will close the Process and update the folder status to "Cancelled"
- "Withdrawn" - will close the Process and update the folder status to "Withdrawn"
- Remove ‘Customer Contacted’ attempt


**Misc. Notes:**
- `What work types do these changes apply to?` 
- `We recently updated the Neighborhood Block Party processes & workflow. Will this work type need to be updated to accommodate these changes?`
- `We've only identified who the process should be assigned to for Event Review. Do the others need to be assigned to somebody, or unassigned? Either way we need to specify.`

**Comment by TracyLinder** [comment]
@Nadin-Nader please update the acceptance criteria this sprint. Thank you!

**Comment by Nadin-Nader** [comment]
@TracyLinder i Updated the criteria. Please review and let me know. I will send the questions on it to Maria to see what she says and update the criteria with her answers once i hear back.

**Comment by Nadin-Nader** [comment]
Email sent to Maria:

> > Hi Maria,
> > 
> > Hope you are doing well. I am reaching out to inform you that the Scoping and researching has begun again. I was going over Card 2666 OSE Process Clean Up And refined the acceptance criteria a bit more with Tracy. We came up with a few more questions to ask you (in red text below). I also wanted to see if you could go over how we laid out the process and let us know if that is the correct way it should work.
> > 
> > Once we get this back we should be good to put this in our On Deck or Backlog column for the developers to look at.
> > 
> **Acceptance Criteria:**
> **This will apply to the RW SubType: Street Event (50510)**
> 
> - Customer applies online/submits
> - System inserts process 7000 Web Acceptance **(Same; no changes)**
> - Upon saving 'Accepted' attempt on Web Acceptance the system will:
>     - Update the folder status to ‘Pending’
>     - Insert processes Event Review (50560), Event Intake (50555), Activity Log (80115) and Event Billed (new)
>         - ‘Event Review’ (50560)  should not add any fees when inserted
>         - **Remove** the "Event Intake" Process (50555) 
>         - **Remove** the "Activity Log" (80115) Process (they don't use it)
> 
> - (50555) ‘Event Review’ - Attempts: Approved, Awaiting Update, Expired, Rejected, Send Notification Letter, Withdrawn, Cancelled (new)
>      - Is assigned to ‘ACE ATD Reviewer’ group
>      -  ‘Cancelled’ (new) will close the ‘Event Review’ process, update the process status to ‘Closed’, and update the folder status to ‘Cancelled’
> 
> **_'What will the other attempts do? Approved, Awaiting Update, Expired, Rejected, Send Notification Letter, Withdrawn’?’ ‘Will they stay the same?’, Do the In, Start, End Dates need to be populated?’_**
> 
> - ‘Event Billed’ (New) is inserted in a ‘Pending’ status - Attempts: Billed, Reminder, Cancelled, Paid, Waived
>     - ‘Billed’ will send the customer an email with bill information
>         - Content TBD: (Something like: This is your bill, this is how you pay it...)'
>         - Email goes to folder applicant’s Internet User, parent record’s email address
>         - Keeps folder in ‘Pending’ status
>     - ‘Reminder’ will send the customer an email with bill information
>         - Content TBD: (Something like: You still haven't paid your bill...)'
>         - Email goes to folder applicant's Internet User, parent record's email address
>         - Keeps folder in ‘Pending’ status
>     - ‘Cancelled’ will close the process ("Event Billed") and update the folder status to ‘Cancelled’
>     - ‘Waived’ will: close the process ("Event Billed") and update the folder status to ‘Pending’
>     - ‘Paid’ will close the process ("Event Billed") update folder status to 'Paid', and insert process (50560) ‘Event Permitting’
> 
> **_‘What group should the (New) ‘Event Billed’ be assigned to?’ ‘Will the ‘Waived’ attempt insert the ‘Event Permitting’ (50560) process?’ ‘Do the In, Start, End Dates need to be populated in ‘Event Billed’ (New) process?’_**
> 
> - (50560) ‘Event Permitting’– Attempts: Approved, Rejected, Cancelled, Withdrawn
>     - This process is mandatory for permit issuance (process must be closed before permit issues)
>     - Folder status should stay as “Paid” until an attempt is entered
>     - Attempts:
>         - 'Approved' will: close the Process and update the folder status to 'Pending Permitting'
>         - 'Rejected' will: close the Process and update the folder status to 'Rejected'
>         - 'Cancelled' will: close the Process and update the folder status to 'Cancelled'
>         - 'Withdrawn' will: close the Process and update the folder status to 'Withdrawn'
>     - **Remove** attempt ‘Customer Contacted’ attempt
> 
> **_‘In what status will the (50560) ‘Event Permitting’ process be inserted as?’ ‘What group should the (50560) ‘Event Permitting’ be assigned to?’  ‘Do the In, Start, End Dates need to be populated in (50560) ‘Event Permitting’?’_**
> > 
> > Respectfully,
> > 
> > Nadin A. Nader (He/Him/His)
> > IT Business Systems Analyst
> > Data and Technology Services



## **Status:**
Waiting on Maria's Response

**Comment by Nadin-Nader** [comment]
@TracyLinder i have update the AC based off of the email from Maria (see below). Please review and see if it is ready to go or if come up with more questions.

Email from Maria:

> So Friday turned to Tuesday… I imagine yall are super busy with all the AMANDA / Portal stuff!
> 
> Below are my answers in blue. Let me know if you want to schedule something to go over it. 
> 
> Hope you are well! 
> 
> Maria Alonso (she/her/hers)
> Office of Special Events
> Austin Transportation Department
> O: 512-974-7275 | M: 512-698-8061
> 
> From: Alonso, Maria 
> Sent: Wednesday, April 14, 2021 3:20 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Subject: Re: OSE Process Clean Up #2666
> 
> Hi!
> 
> I haven't forgotten about you! 
> 
> I'm just working on a deadline for tomorrow and haven't had a chance to take a look at this. 
> 
> I will get back to you on Friday. 
> 
> Thank you for sending these over!
> 
> Maria 
> ________________________________________
> From: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Sent: Friday, April 9, 2021 1:21 PM
> To: Alonso, Maria <Maria.Alonso@austintexas.gov>
> Subject: OSE Process Clean Up #2666 
>  
> Hi Maria,
>  
> Hope you are doing well. I am reaching out to inform you that the Scoping and researching has begun again. I was going over Card 2666 OSE Process Clean Up And refined the acceptance criteria a bit more with Tracy. We came up with a few more questions to ask you (in red text below). I also wanted to see if you could go over how we laid out the process and let us know if that is the correct way it should work.
>  
> Once we get this back we should be good to put this in our On Deck or Backlog column for the developers to look at.
>  
> Acceptance Criteria:
> •	This will apply to the RW SubType: Street Event (50510)
> •	Customer applies online/submits
> •	System inserts process 7000 Web Acceptance (Same; no changes)
> •	Upon saving Accepted attempt on Web Acceptance the system will:
> o	Update the folder status to ‘Pending’
> o	Insert processes Event Review (50560), Event Intake (50555), Activity Log (80115) and Event Billed (new)
> 	‘Event Review’(50560)  should not add any fees when inserted
> 	Remove the "Event Intake" Process (50555) 
> 	Remove the "Activity Log" (80115) Process (they don't use it)
> •	(50555) ‘Event Review’ - Attempts: Approved, Awaiting Update, Expired, Rejected, Send Notification Letter, Withdrawn, Cancelled (new)
> 	Is assigned to ‘ACE ATD Reviewer’ group
> 	‘Cancelled’ (new) will close the ‘Event Review’ process, update the process status to ‘Closed’, and update the folder status to ‘Cancelled’
> 'What will the other attempts do? Approved, Awaiting Update, Expired, Rejected, Send Notification Letter, Withdrawn’?’ ‘Will they stay the same?’, Do the In, Start, End Dates need to be populated?’
> -	Approved = ‘Pending’ folder status and closes the process. Inserts ‘Event Billed’ and ‘Event Permitting’ processes
> -	Awaiting Update – we don’t need and can be removed
> -	Expired – we don’t need and can be removed
> -	Rejected = ‘Rejected’ folder status and closes the process. Should require a comment.
> -	Send Notification Letter – we don’t need and can be removed
> -	Withdrawn = ‘Withdrawn’ folder status and closes the process. Should require a comment.
> -	 Cancelled = ‘Cancelled’ folder status and closes the process. Should require a comment.
> -	As for the dates, this is kind of how we use them in the SE folder right now. Let me know if this will work for the RW folder. 
> o	In Date = date the process was inserted
> o	Start Date = date the process was closed
> o	End Date = date of the start date of the event
> 
>  
> •	‘Event Billed’ (New) is inserted in a ‘Pending’ status - Attempts: Billed, Reminder, Cancelled, Paid, Waived
> o	‘Billed’ will send the customer an email with bill information
> 	Content TBD: (Something like: This is your bill, this is how you pay it...)'
> 	Email goes to folder applicant’s Internet User, parent record’s email address
> 	Keeps folder in ‘Pending’ status
> o	‘Reminder’ will send the customer an email with bill information
> 	Content TBD: (Something like: You still haven't paid your bill...)'
> 	Email goes to folder applicant's Internet User, parent record's email address
> 	Keeps folder in ‘Pending’ status
> o	‘Cancelled’ will close the process ("Event Billed") and update the folder status to ‘Cancelled’
> o	‘Waived’ will: close the process ("Event Billed") and update the folder status to ‘Pending’
> o	‘Paid’ will close the process ("Event Billed") update folder status to 'Paid', and insert process (50560) ‘Event Permitting’
> ’ ‘What group should the (New) ‘Event Billed’ be assigned to?’ ‘Will the ‘Waived’ attempt insert the ‘Event Permitting’ (50560) process?’ ‘Do the In, Start, End Dates need to be populated in ‘Event Billed’ (New) process?’
> -	The ‘assigned to’ should be the assigned user. Since they would be the ones working the events/folder
> -	The dates same as above:
> o	In Date = date the process was inserted
> o	Start Date = date the process was closed
> o	End Date = date of the start date of the event
> 
> We also finalized the message language (YAY!): 
> 
> From Email: (assigned user, aka whoever created the attempt)
> 
> To Email: (applicant email)
> 
> Subject Line:
> 
> ACE App. Update: Austin Transportation Special Events Fees Invoiced for [FOLDERNAME]
> 
> Message Intro:
> 
> Hello, 
>  
> Project Details (Message):
> 
> Street Event fees for event [FOLDERNAME] have been billed. 
>  
> You can pay online  by Check or Credit Card by visiting https://abc.austintexas.gov. Go to 'My Bills' to view and pay your pending invoices.  
>  
> Please reach out if you have any additional questions. 
>  
> Austin Transportation 
> Austin Center for Events
> 
> •	(50560) ‘Event Permitting’– Attempts: Approved, Rejected, Cancelled, Withdrawn
> o	This process is mandatory for permit issuance (process must be closed before permit issues)
> o	Folder status should stay as “Paid” until an attempt is entered
> o	Attempts:
> 	`Approved` will: close the Process and update the folder status to "Pending Permitting"
> 	`Rejected` will: close the Process and update the folder status to "Rejected"
> 	`Cancelled` will: close the Process and update the folder status to "Cancelled"
> 	`Withdrawn will: close the Process and update the folder status to "Withdrawn"
> o	Remove ‘Customer Contacted’ attempt
>  
> ‘In what status will the (50560) ‘Event Permitting’ process be inserted as?’ ‘What group should the (50560) ‘Event Permitting’ be assigned to?’  ‘Do the In, Start, End Dates need to be populated in (50560) ‘Event Permitting’?’
>  
> -	The ‘assigned to’ should be the assigned user. Since they would be the ones working the events/folder
> -	The dates same as above:
> o	In Date = date the process was inserted
> o	Start Date = date the process was closed
> o	End Date = date of the start date of the event
>

**Comment by TracyLinder** [comment]
### Status Update

I moved all work for epic #2666 from On Deck to the Backlog until our higher priority issues are complete (ROW Cost of Service reports, FY 22 fee scoping.)

**Comment by TracyLinder** [comment]
Lets get this to PROD before the code freeze in December.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - TEST DP’s submitted. This will move the entire epic to test. So, that complete flow can be tested in TEST Environment. Kindly approve and create task id for me.


#2666 EPIC Commit ID’s
-------------------------------

**1.	#6030 Commit ID’s**
a.	Order 1 - b1c225dce3bb & 5a290ad50351 – Already in TEST
b.	Order 2 - [cb3c789415cd](http://coaamandadevops01.austintexas.gov/R3:cb3c789415cdb8800786354b8e5a6cbd570a674b)

**2.	#6031 Commit ID’s** 
a.	Order 1 - d896d8858596
b.	Order 2 - ad554c8c117d
c.	Order 3 - 6f7ee477b54a
d.	Order 4 - 6eef99981bf5

**3.	#6032 Commit ID’s** 
a.	Order 1 - 355395df49a2

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST Environment; all working as expected and ready for UAT.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per Maria’s approval, PROD DP’s of Epic #2666 (Cards #6030, #6031 & #6032) submitted. Kindly approve and create task id for same.

**Please find the order below to promote to PROD -** 

1. #6030 Commit ID’s
a. Order 1 - b1c225dce3bb & 5a290ad50351 
b. Order 2 - cb3c789415cd

2. #6031 Commit ID’s
a. Order 1 - d896d8858596
b. Order 2 - ad554c8c117d
c. Order 3 - 6f7ee477b54a
d. Order 4 - 6eef99981bf5
e. Order 5 - 2792c4969685

3. #6032 Commit ID’s
a. Order 1 - 355395df49a2

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan the whole epic (6030, 6031, 6032) been sent to the DevOps cm Team to be deployed to **_PROD_** under **SCTASK0215849**

**Comment by Nadin-Nader** [comment]
Maria has been informed that #6030, #6031, #6032 are all on PROD. I have closed the other card but will keep this open for a week to see if any issues arise. If no issues are reported, i will close it on Monday or Tuesday (5/10 or 5/11)

**Comment by Nadin-Nader** [comment]
Closing as no issues have been reported
