### ISSUE TITLE
Review request to extend application to include signal work assignment 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2668]
Jen and Lewis have been talking about merging how we schedule officers for signal work and for Vision Zero enforcement. Will show them the latest tool for scheduling Vision Zero enforcement, and talk through how we schedule officers for signal work, and what effort would be needed to merge the two.

---
- [x] Scheduled for 5/19
- [x] Meet and take notes
- [ ] Create resulting issues

**Comment by SurbhiBakshi** [comment]
@amenity don't see your notes, though I got the email. Is this not the right issue?

Here is my take from the meeting - 
1. Billy and group could schedule a lot of assignments ahead of time, though not all. 
2. Frequency - seems to be about 1 to 2 assignments a week, 2 hours to 8 hours, 
3. Number of Officers (this will affect child records) - could require 2 to 5 officers. 
3. Location - would use Data Tracker signal location and intersections for the most part, but could add some new locations. Sometimes officers have to trail a team on a particular route.
4. Signal Enforcement assignments are rarely cancelled, but assignments are sometimes postponed if officers do not sign up (would need the edit functionality to change the date and time, also notification in case some officers signed up, but more officers were needed. Officers who signed up would need to be notified.

**Comment by SurbhiBakshi** [comment]
Questions -

**Comment by amenity** [comment]
5/19
Attendees
- AMD: Jen, Billy, Brian VdW, Willard, Frank
- VZ: Lewis
- DTS: Surbhi, Amenity

Signals group schedules APD to provide traffic control
- Both go through Randy at APD
- Timelines are different
    - VZ is a month in advance
    - AMD varies; see below
- Work itself is different: VZA work is relatively easy while signals might require standing in an intersection for hours in 100˚ heat
- Sometimes VZA assigned officers are redirected to signal shifts; probably not psyched 
- Would it be easier to hire officers in signals group if we could incorporate it into the VZA tool

**Demo of VZA Scheduler interface**
    - B VdW: This looks like a full schedule already; LL: There are lots of officers; this would just show as another shift... There are always going to be more desirable shifts e.g. standing at the Food and Wine festival... Can't change the fact that there is a "pecking" order
    - B VdW: This could also be used for job scheduling for technicians working for AMD, see #875 

**Current AMD process for scheduling APD officers for signal work**
    - Average ~1x a week, depends on the size of the job… sometimes 2 officers x 2 hours, sometimes 4 officers (which will automatically include a sergeant) and an 8 hour shift; don’t ever need more than one team a day, but the number of officers and length changes
    - Typically send Randy schedule on a Thursday/Friday. 
    - Monday/Tuesday shifts rarely get filled; Wed/Thursday/Friday was okay but not always
    - Haven’t been successful trying to book earlier even when they know in advance, e.g. 3-4 weeks in advance never get anyone
    - If no one signs up for shifts, reach out to Randy and he tries again. If he can’t, they have to cancel the job
    - Contractors and crews rarely cancel (Jen suggests that if they did they could be moved to a cush VZA shift)
    - Billy: The messy part of the schedule is when things are thrown off by contractors, but when we need APD officers it’s usually for mods and upgrades, or D4 conversions, cabinet knockdown - anything we can have complete control over. There is no reason we shouldn't be able to schedule this work 3-4 weeks in advance though that's not currently the process
    - Willard used to send the schedule to Randy, now Billy does. It's good for him to see where there are requests for officers; helps anticipate situations where Billy needs to have a technician on call
    - What if officers sign up for a VZA shift but no one signs up for the signal shift?
        - Lewis: I could work with AMD, maybe cancel one of my shifts

**Locations + descriptions**
    - 99% of time, assignment is at a signalized intersection (not PHB, beacon)
    - 99% of time, description is “Traffic control in intersection while light is dark” 

**Builder questions**
    - As far as locations, would this be a one-time import of AMD locations? 
    - New Location type for intersections?
    - LL concerned about too many people seeing his schedule; could we hide from other Schedulers?
    - Need to consider how to handle how long it takes to run batch process before opening the application to another Scheduler: https://github.com/cityofaustin/atd-data-tech/issues/2652#issuecomment-630395366
