### ISSUE TITLE
Collaborate with UT CTR on a 2016 Mobility Bond Viewer

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2673]
A public-facing summary dashboard that captures key mobility metrics about the 2016 Mobility Bond Corridors.

![Austin-Map-Blue](https://github.com/cityofaustin/atd-data-tech/assets/1463708/7e86f2b8-a859-4b1c-b0c8-fd9aaab06bec)

### Roles
- AMD: Definition of metrics
- UT CTR: Data pipeline and computation of metrics
- DTS: Public viewer

[Information from New Application request ticket]

### Resources

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://data.mobility.austin.gov/about/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
@johnclary @JaceDeloney - why is this blocked?

**Comment by JaceDeloney** [comment]
I don't remember having a conversation about this one, @johnclary. Can you help me understand the context, urgency, and why it's blocked?

**Comment by johnclary** [comment]
Status: CTR is working with AMD to setup ETLs between INRIX and Socrata. That will open up the door for viewer development....this fall?

@johnclary please loop jace in on CTR meetings.

**Comment by JaceDeloney** [comment]
Talked to @johnclary. Since the metrics for this viewer are focused on traffic metrics from INRIX, this does not fit into MOPED in the near term.

It would be good to understand AMD's needs priority-wise. We can talk about this at the next AMD meeting.

**Comment by amenity** [comment]
@JaceDeloney @johnclary - do you want to talk about this in [our AMD meeting on Monday](https://docs.google.com/document/d/17vQoiQy1lbUOmgTltshxiquVWL95Yf-wMtktV29RjXc/edit#heading=h.9kialbik2pcj)?

**Comment by johnclary** [comment]
We've met with AMD and UTCTR several times as they continue to refine their methodology and metrics. There continues to be uncertainty around the intended audience for these metrics—whether that is ATD staff for the general public. We will scope and prioritize this product once the basic requirements have been defined.

**Comment by johnclary** [comment]
UTCTR is developing the data pipeline which will provide monthly metrics which match what AMD is reporting for SD23. We can leverage this data to refine the SD23 metrics, and/or produce additional indicators as needed. Further scoping is required to define if a dedicated bond viewer dashboard is needed and what data, besides the SD23 metrics, it will display.

**Comment by johnclary** [comment]
UTCTR is continuing to work on the data pipeline as described in my previous update. We're in a holding patter until UTCTR completes their work.

**Comment by johnclary** [comment]
Natalia has sent INRIX performance metric data based on the calculations we're using for SD23 indicators. AMD will review and confirm it's acceptable.

#### Next Steps
- AMD to review data
- Create new SD23 datasets for the performance metrics, which are in monthly rather than yearly format
- Update SD23 measure cards to use new datasets
- Coordinate with CTR to automate data publication to these datasets

**Comment by johnclary** [comment]
We continue to be focused on #4999 and #5003.

**Comment by amenity** [comment]
@ChristinaTremel - Have you heard anything about this request from AMD lately? @Charlie-Henry built Meredith [a dashboard](https://github.com/cityofaustin/atd-data-tech/issues/11325) to track bond project expenditures and might have ideas about how this could evolve if it's still a need.

**Comment by ChristinaTremel** [comment]
Assigning this to myself so I can check in with AMD to determine if this is still a need.

**Comment by amenity** [comment]
Closing in favor of #15108.
