### ISSUE TITLE
VZV | Document data queries sources and review data quality

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#2687]
Specifically Lewis mentioned reviewing data issues/counts in the demographics and mode visualizations and the years of life lost count. 

We can check counts against X's dashboard for March or April

[VZ Dashboard 2020-04.pdf](https://github.com/cityofaustin/atd-data-tech/files/4652602/VZ.Dashboard.2020-04.pdf)
[VZ Dashboard 2020-03.pdf](https://github.com/cityofaustin/atd-data-tech/files/4652603/VZ.Dashboard.2020-03.pdf)

**Comment by sergiogcx** [comment]
As requested by Mateo, I have created a series of issues after a preliminary check and discovered a few inconsistencies:

Fatalities:
https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/2789
Years of Life Lost:
https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/2790
By Time of Day:
https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/2791

**Comment by sergiogcx** [comment]
### By month/year

This graph appears to work correctly, the numbers add up in the database as they show up on here, in terms of year-end totals:
![2020-05-26_12-17-10.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/2ed10268-02d5-4ee8-9fc0-fdeaa04c43f7)

Per month (2019, 2018, 2017)

For instance if we look at 2019 we see not only the numbers match, but that the numbers add up each month as expected.
![2020-05-26_12-11-28.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/5e529ca9-6da7-4298-9752-23bee1e73bba)

**Comment by sergiogcx** [comment]
### Demographics: Fatalities by Age

The data seems off, to begin with the total number of fatalities in 2016 is 91, and the year 2016 in the graph shows a total of 182 (exactly twice the actual amount):

![2020-05-26_13-13-40.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/8d99324a-8644-44b4-a5ad-b308e16754b8)

2017: 79 total deaths, 158 shown in the graph.

![2020-05-26_13-16-26.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/7b6c3ef9-d240-4026-9576-015f143ebe35)

2018: 74 total, 146
![2020-05-26_13-17-49.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/b97c2cca-bfed-48aa-979a-279848c971e9)

**Comment by sergiogcx** [comment]
### By Mode 

This graph is looking good
