### ISSUE TITLE
Create Permits Tab

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2691]
### Create a Permits tab that includes the permits object

**The permits tab should have the following two tables:**
- A table with a list of `Active Permits`
- A table with the history of `Expired Permits`

**Each table should include the following fields:**
- Provider
- Permit Start Date 
- Amount Paid
- Number of Devices
- Device Type
- Zone
- Permit Expiration Date

**Each table should have the following functionality:**
- Ability to add notes while creating a new permit record
- Ability to add notes to an existing permit record
- Ability to add notes to an expired permit record

**Comment by SurbhiBakshi** [comment]
- [ ] Create a Permits tab that includes the permits object

The permits tab should have the following two tables:

- [ ] A table with a list of Active Permits
- [ ] A table with the history of Expired Permits
- [ ] Each table should include the following fields:

- [ ] Provider
- [ ] Permit Start Date
- [ ] Amount Paid
- [ ] Number of Devices
- [ ] Device Type
- [ ] Zone
- [ ] Permit Expiration Date

Each table should have the following functionality:

- [ ] Ability to add notes while creating a new permit record
- [ ] Ability to add notes to an existing permit record
- [ ] Ability to add notes to an expired permit record
