### ISSUE TITLE
[Feature] Enable ADFS Login

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2694]
- Configure active directory (ADFS) login so that users can login with their COA email/password.

- Use custom js and css to create pretty sign-in buttons.

For example, the Finance & Purchasing system login page:
<img width="1039" alt="Screen Shot 2020-05-20 at 4 18 01 PM" src="https://user-images.githubusercontent.com/14793120/82498391-83d8c100-9ab5-11ea-8ce7-409ce443cee6.png">

**Comment by SurbhiBakshi** [comment]
Sent in a ticket to CTM .

**Comment by SurbhiBakshi** [comment]
Request REQ0050451

**Comment by SurbhiBakshi** [comment]
@JaceDeloney - can you try logging in? I was able to log in today morning on Chrome and Firefox.

**Comment by SurbhiBakshi** [comment]
@JaceDeloney ADFS has been enabled, you should be able to get in using your COACD login.
