### ISSUE TITLE
Knack App Environment Cleanup

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2695]
Please clear out any unneeded apps from the builder.

- RPP
- VZA
- Dockless
- Others?

**Comment by dianamartin** [comment]
Had to move `[DEPRECATED] City of Austin Parking Permits \| PROTOTYPE` to new application under RPP in the Application Inventory table, then added the Delete Date.

**Comment by dianamartin** [comment]
Asked Surbhi and Amenity about the VZA environments and Surbhi about the two Dockless apps we have. 

The only other one I can think of is maybe the HR app. @johnclary should we keep that around since HR wants to do a few things paperless, it might come in handy as a reference.

**Comment by SurbhiBakshi** [comment]
- Dockless cleanup, documented [here ](https://atd.knack.com/dts#applications/view-application-details/5ebb04f8f0614a001913a02f/)
- Vision Zero in Action cleanup, documented [here](https://atd.knack.com/dts#applications/view-application-details/5da9dd053520560015f0cc6f/)
@amenity do you still need that Sandbox for VZA?

**Comment by amenity** [comment]
@SurbhiBakshi No m'am.🙏

**Comment by SurbhiBakshi** [comment]
@dianamartin @amenity - deleted the sandbox.

**Comment by amenity** [comment]
Thanks, @dianamartin - gonna call this closed.
