### ISSUE TITLE
Remove Unneeded Tables

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#270]

**Comment by johnclary** [comment]
### Keep these Tables
- [ ] `csr_signs_markings_activities`
- [ ] `csr_signs_issues`
- [ ] `csr_signs_flex_notes`
- [ ] `inventory_items`  << need to remove AMD items
- [ ] `street_names`
- [ ] `work_orders_markings`
- [ ] `work_orders_signs`
- [ ] `work_order_signs_locations`
- [ ] `work_orders_signs_asset_spec`
- [ ] `work_orders_signs_asset_spec_actual`
- [ ] `work_orders_signs_markings_attachments`
- [ ] `work_orders_signs_markings_comments`
- [ ] `work_orders_markings_specification`
- [ ] `work_orders_signs_markings_specification_actual`
- [ ] `work_orders_signs_markings_jobs`
- [ ] `work_orders_signs_markings_time_log`

### Remove These Tables
- [ ] `admin_field_meta`
- [ ] `admin_objects_meta`
- [ ] `aps_button_requests`
- [ ] `bcycle_kiosk_locations`
- [ ] `cameras`
- [ ] `construction_cost_estimate_report`
- [ ] `construction_cost_items`
- [ ] `cost_estimate_log`
- [ ] `contract_solicitation_vendor`
- [ ] `csr_flex_notes`
- [ ] `damage_items`
- [ ] `damage_report`
- [ ] `device_status_log`
- [ ] `dms`
- [ ] `fleet_vehicles`
- [ ] `hazard_flashers`
- [ ] `inventory_transactions`
- [ ] `ip_switches`
- [ ] `locations`
- [ ] `locations_traffic_counts`
- [ ] `performance_measures`
- [ ] `performance_measures_fiscal`
- [ ] `performance_measure_monthly`
- [ ] `performance_measure_quarterly`
- [ ] `performance_measure_annually`
- [ ] `pole_attachments`
- [ ] `quote_of_the_week`
- [ ] `school_beacons`
- [ ] `school_beacon_zones`
- [ ] `signals`
- [ ] `signal_id_generator`
- [ ] `signals_cabinet`
- [ ] `signals_cad`
- [ ] `signals_corridors`
- [ ] `signals_corridor_retiming`
- [ ] `signals_corridor_retiming_special`
- [ ] `signals_corridors_signals`
- [ ] `signals_detectors`
- [ ] `signals_detection_status_log`
- [ ] `signal_file_attachments`
- [ ] `signals_preventative_maintenance`
- [ ] `signal_priority`
- [ ] `signal_requests`
- [ ] `signal_requests_phb_evals`
- [ ] `signal_requests_traffic_eval`
- [ ] `signal_requests_traffic_study`
- [ ] `signal_requests_phb_study`
- [ ] `street_segments`
- [ ] `task_orders`
- [ ] `tcp_tracking`
- [ ] `tcp_tracking_submissions`
- [ ] `technician_equipment`
- [ ] `technician_equipment_log`
- [ ] `tmc_activities`
- [ ] `tmc_call_log`
- [ ] `tmc_issues`
- [ ] `traffic_counts`
- [ ] `traffic_count_attachments`
- [ ] `traffic_count_comments`
- [ ] `travel_sensors`
- [ ] `vision_zero_enforcement`
- [ ] `vision_zero_enforcement_activities`
- [ ] `vision_zero_enforcement_shifts`
- [ ] `vision_zero_enforcement_actions`
- [ ] `work_orders_signals`
- [ ] `work_orders_signals_images`
- [ ] `work_orders_signals_time_log`
- [ ] `work_schedule_signals_engineers`

**Comment by johnclary** [comment]
@dianamartin i put a dent in the delete list while watching the debates

**Comment by johnclary** [comment]
@dianamartin ok, it's done.

**Comment by dianamartin** [comment]
You deleted `fleet_vehicles` object and we needed that for the Time Log form. you got delete happy..haha. I re-imported it.
