### ISSUE TITLE
Migrate Documents to new ATD Development Review Services Sharepoint.

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2704]
See #2442. Schedule for 5/22.

**Comment by dianamartin** [comment]
Nazlie was out today, but coordinated with Nathan A. 
- I started the migration at 2:30 pm and wrapped up around 4:45 pm. 
- Emailed users
>I’ve successfully moved the TDS files that were in your old teams SharePoint site, to your new TDS SharePoint site. 

>I’ve also updated the tabs in the “ATD Development Services Division” Teams. 
Under “Files” this points to the Teams SharePoint folder, which I recommend folks not to use. I added a .txt file in there saying to use the other tab “Documents” and link to the new Document Library. 

>- Under “Files” this points to the Teams SharePoint folder, which I recommend folks not to use. I added a .txt file in there saying to use the other tab “Documents” and link to the new Document Library. 
- Under “Home”, I updated the link to point to the new TDS SharePoint site: 
- Under “Documents”, is a quick link to all the folders in the Document Library (the new document storage folder).
