### ISSUE TITLE
Create TIA Module User Story Issues

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2705]
[Here](https://drive.google.com/file/d/1dmtJSWlhtiVC6w_XTjhTHfz-5WL0d7vx/view?usp=sharing) is the CSV you need.

**Comment by TracyLinder** [comment]
@johnclary this is good to close right? Also, you asked me to delete labels that were created as part of this right? Which labels need to go?

**Comment by johnclary** [comment]
@TracyLinder yes; closing. I dropped the unneeded labels at some point last week. We're all set.
