### ISSUE TITLE
Bug: Map page button styling issue on Firefox 

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2706]
There is an issue on FF where the map page button elements get moved to the next line. You can see this on the crash type buttons and on the date range picker button. See below:

![Screen Shot 2020-05-06 at 2.28.46 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/1864b814-8d43-4221-9850-b599f1920407)

**Comment by sergiogcx** [comment]
It appears the buttons have `col` and `col-row` classes; when removed, the behavior is as expected. However, the width of the text makes the last button `Serious Injury` to break into the next line. When we reduce the text down to `Serious Injry.` it works.

![2020-05-20_18-24-12.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/3ed78192-42d7-4a61-99f6-17527746da02)

currently in firefox the size of the text is 14px for those buttons, when reduced to 13px it appears to work as expected without changing the text in the button:

![2020-05-20_18-32-42.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/fa36c499-00fe-41a7-9ecd-3cb95254e14b)

**Comment by sergiogcx** [comment]
It looks like the width is off by a few pixels, if i reduce 99px down to 94 the component works as expected (this may require overriding the class `_le62miv` hopefully it is a normal class and not automatically generated):

![2020-05-20_18-28-48.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/9a2b14f5-a806-492e-8480-457e2f0ea088)

**Comment by sergiogcx** [comment]
Got it to work now:
https://github.com/cityofaustin/atd-vz-data/pull/788

![2020-05-20_19-41-15.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/773a4cd6-c73c-4798-9821-fa7d12126874)

**Comment by sergiogcx** [comment]
Well, came back from a walk and realized I had not checked how this looks like in Chrome, as it turns out, it is broken there too:

![2020-05-20_22-28-56.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/a37da3ed-0563-47c6-9758-1844a86dad8a)

**Comment by sergiogcx** [comment]
Ok, got it fixed in chrome too, but it ain't pretty:

![2020-05-20_22-39-11.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/a017e346-264c-46f5-9ace-9a5a0938bdd1)
