### ISSUE TITLE
Healthy Streets - AMANDA Data Needed

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2709]
**Customer:** Kaz W. 

Teams Mtg scheduled 5/27 @ 3:30 to define the request/need.

**Comment by johnclary** [comment]
@alan-deanda and @TracyLinder perhaps y'all should touch base on this

**Comment by TracyLinder** [comment]
The healthy streets initiative requires ROW conflict coordination. Specifically, Kaz needs email addresses for all permits that conflict with the affected streets. I've reached out to Nathan & Alan to discuss how they could help produce a list of street segments that can be used in an AMANDA query, so we can auto-generate a list of emails.
