### ISSUE TITLE
Remove Unneeded Custom CSS and JS

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#271]

**Comment by johnclary** [comment]
Putting this in backlog. We're still making updates to the JS; so let's hold off on this until we can test in a copy of the prod app after release.

**Comment by dianamartin** [comment]
@johnclary We've made 2 copies of Data Tracker Production, one with records and one without. I think you're free to review the JS and CSS and update the code. [sign-markings code repo](https://github.com/cityofaustin/atd-knack-signs-markings/tree/master/knack)

**Comment by amenity** [comment]
@johnclary - does this need more review? If so, what/who?

**Comment by amenity** [comment]
@johnclary ☝️

**Comment by amenity** [comment]
@johnclary - this has been holding up us closing #406. Should we remove it from the epic and stick it in the backlog?

**Comment by amenity** [comment]
@johnclary Sprint 13!

**Comment by johnclary** [comment]
It's done!

**Comment by amenity** [comment]
😱🙌
