### ISSUE TITLE
Include Obfuscated User Name in Body of DTS Service Requests

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2710]
Add firstname & last initial to the body of new DTS service requests. See discussion in [this comment](https://github.com/cityofaustin/atd-data-tech/issues/2638#issuecomment-628222156).

**Comment by johnclary** [comment]
Currently running this patch on prod. [PR](https://github.com/cityofaustin/atd-service-bot/pull/18)

**Comment by johnclary** [comment]
@amenity @TracyLinder here's what the "Requested By" looks like now. It's too hard to put the workgroup name in that same line, but the Workgroup label gives you that info.

![Screen Shot 2020-05-20 at 6.08.12 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/a13b0237-d18d-4d66-8603-fe099a94d8be)

**Comment by johnclary** [comment]
derp i see that the quote text is flipped. boo will fix.

**Comment by johnclary** [comment]
OK—fixed. please let me know how this is going once you get a few new issues.

**Comment by amenity** [comment]
@johnclary, working great. Thanks.
