### ISSUE TITLE
remove unneeded views

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#272]
Removed views under "Page" tab

**Comment by dianamartin** [comment]
I removed most of them, need to still delete these: 

- [ ] My Work Orders Signals
- [ ] Work Orders Signals
- [ ] New Work Order Signals
- [ ] Work Schedule
- [ ] Signals
- [ ] TMC

**Comment by dianamartin** [comment]
I added "delete_after_migration" to these tables so we can delete them later.

**Comment by dianamartin** [comment]
I deleted these because they were causing URL duplicates.
