### ISSUE TITLE
Knack Attachment Migration Automation

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#277]
@sergiogcx we are going to be migrating data from our [Data Tracker](https://builder.knack.com/atd/amd) app to our new [signs & markings](https://builder.knack.com/atd/signs-markings) app.

The table structure, field names, and objects are going to be identical in both apps.

The object with attachments is [`work_orders_signs_markings_attachment`](https://builder.knack.com/atd/signs-markings#data/object_153/fields). The attachment field is field `field_2405`.

When we do the mgiration, Diana and I will migrate all of the attachment records from the Data Tracker to the new app, except for the attachments. Once that's done, we need a script that will download all of the attachment files from Data Tracker, and upload them to the `work_orders_signs_markings_attachment` object in the new app.

**Comment by johnclary** [comment]
You are free to delete/create records in the [new signs & markings app](https://builder.knack.com/atd/signs-markings), so long as you are **only reading data** from the [Data Tracker app](https://builder.knack.com/atd/amd)

**Comment by johnclary** [comment]
oh, and since the app and tables are the same, you could really just do all your development in the [new signs & markings app](https://builder.knack.com/atd/signs-markings). And when we are ready to do the migration we can point to the source data in the Data Tracker

**Comment by sergiogcx** [comment]
Got it, the Data Tracker app is sacred no writing only reading. I may create a table within the new signs & markings app identical to `work_orders_signs_markings_attachment ` so I could just read and write within the app.

**Comment by sergiogcx** [comment]
Turned into an epic, I will need to create a few subtasks.
