### ISSUE TITLE
Initial Feedback Data Processing

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#2771]
Now that the public feedback map apps are live, processing the data is the next step in managing Healthy Streets.
Coordinating with SDD and ATSD to create dashboards and analyze data.

**Comment by alan-deanda** [comment]
GIS Support involves creating workflows for analyzing public feedback in the most user-friendly and accessible way possible.
While it may not be possible to analyze the data as desired within AGOL alone, it would be possible to analyze the data in ArcPro and publish the results with the organization in AGOL. The analysis is being tested and refined using data from the first week since launching the feedback apps.

**Comment by johnclary** [comment]
@alan-deanda please document links to layers or derived datasets created from this.

May revisit this data again soon.

**Comment by alan-deanda** [comment]
Data lives in G Drive, under ATD_GIS/Active_Transportation/Healthy_Streets in an analysis file geodatabase containing data from week 1. The folder also contains excel docs with pivot tables.
After our meeting yesterday, it seems SDD might take over analyzing the data and preparing reports, given that they've been able solve their google survey data analysis hurdles, and are monitoring public activity more closely. 

@johnclary  this may be ready to close, if you agree.

**Comment by johnclary** [comment]
@alan-deanda yes, thanks. Closing.
