### ISSUE TITLE
Requirements Gathering: TIA Module - Submissions

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2773]
### Objective 
Review prototype and dig into requirements

### Participants
Tracy, Diana, Nathan, Joan

### Agenda
Go over prototype progress
- TIA Submissions
- TIA Submission Attachments
- TIA Submission Comments
- TIA Comments

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [x] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes

## Action Items
- Work on content for TIA splash page
- Send TIA Determination Form
- transportationreview@austintexas.gov

## Feature Notes 
- **TIA Location Name** - change to "Project Address"
- **Trip Count**: Fee sheet? Get from Nate, Joan or Tracy " - **Trips Per Day**"
- **Land Use**

### REMOVE THESE FIELDS ON THE FORM
- **Size of Site:** square footage, acre? - **Land Use**
  - Ability to add multiple lines (related record to the TIA Review)
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/b91f9810-2d69-4853-8429-39f1389bfde4)
- **Intensity of Site:** How many dwelling units, sq footage, land use

**Review form** - Hide Attachment URL - edit empty fields
**TIA Review Status** - Needs Review
   - [ ] Color Code the status

- [ ] Rename Attachments | TIA Request Review`  to `TIA Scope Review`
- Add Fields - `Scope Status` - TIA Review
- Add Fields - `TIA Status`
- Add Submission Process - email user user after Scope `Approved`
  - Review Status Details, so they can add a new submission
- Submission Review are 28 days, not 10 days
- TIA Review - is 10 day review cycles

### Submission Details
Add `Fee Paid Date`:  Date
  - 28 days - Due Date

- Comment Attachment
  - Add new field: `Comment Memo` or `Approval Memo`

Request Status 
Scope Status - `Approved` - change TIA Review Status - `Pending Submittal`
Submission Status - `Approved` - change TIA Review Status - `Approved`

**Comment by amenity** [comment]
@TracyLinder @dianamartin - Adding some labels to this issue. Is it ready to close?

**Comment by dianamartin** [comment]
@amenity Yes, it can be closed.  I'll close it.
