### ISSUE TITLE
Update VZV alert banner

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2777]
Please update the following in the VZV alert banner:

- [x] Change alert banner color to [reactstrap danger alert](https://reactstrap.github.io/components/alerts/#)
- [x] Add the [Font Awesome](https://fontawesome.com/icons) `exclamation-triangle` icon to the front of the banner text
- [x] Change text to 
> This is a beta version of the Vision Zero Viewer, published to gather user feedback. Crash data displayed may be outdated or inaccurate, and will be updated for the first public release version.

Please update this in production

**Comment by mateoclarke** [comment]
Also update version number in VZE as noted by @sergiogcx 

![2020-05-21_15-27-29](https://user-images.githubusercontent.com/5697474/82603625-9d8f0c80-9b78-11ea-948f-11b803c2df00.png)
