### ISSUE TITLE
Size Level of Effort for Citywide HR requests

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2778]
Can we scope the feasibility and level of effort to make the following updates to the COVID-19 Time Tracking app?

- To put in a field to require supervisor email, that would then generate and email to the supervisor to notify them that there is a file for review?
- If we were to make it optional for use Citywide and did not use the prefill feature how long would it take to roll out?
- I am including an excel document (waiting for an updated csv with formatting) with fields that would need to be added in yellow and fields to be removed highlighted in blue, are these changes possible?

**Comment by dianamartin** [comment]
@JaceDeloney 

**Response to Demi:** 
- To put in a field to require supervisor email, that would then generate and email to the supervisor to notify them that there is a file for review?
>This is easy, but this will be a lot of emails coming to a manager/supervisor. User may be littered with email.
-  If we were to make it optional for use Citywide and did not use the prefill feature how long would it take to roll out?
>We just need to import the list of city employees and their supervisors to get this going
-  I am including an excel document (waiting for an updated csv with formatting) with fields that would need to be added in yellow and fields to be removed highlighted in blue, are these changes possible?
>Dan suggested we get an updated spreadsheet from Demi, none of her formatting changes were saved when she saved the .csv. Might need to follow up with her.

**Comment by amenity** [comment]
@JaceDeloney - ask for clarification on these as they're not in Banner:
- Taskforce
- Reassigned Title

We can import from a spreadsheet and give them an interface to keep up to date.
