### ISSUE TITLE
TIA Modules Refinements - After TIA Requirements Gathering (5/21)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2780]
## TIA Request Form
- [x] Rename **Trip Count** to **Trips Per Day**"
  - Get Fee sheet? Get from Nate, Joan or Tracy
- [x] Rename **Size of Site** to **Land Use**
- [x] Add TDSD email as footer
- [x] Change Preferred **Meeting Date** from `Date/Time` to `Short Text`
- [x] Add field - `Describe your availability?` 
- [x] Add field `Phone` - make it optional 

### REMOVE THESE FIELDS ON THE FORM
- **Size of Site:** square footage, acre? - **Land Use**
  - Ability to add multiple lines (related record to the TIA Review)
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/b91f9810-2d69-4853-8429-39f1389bfde4)
- **Intensity of Site:** How many dwelling units, sq footage, land use

### TIA Review form
- [x] Hide Attachment URL - hide empty fields

## TIA Review Table
**TIA Review Status** - Needs Review
   - [x] Color Code the status (see Knack Style guide - SMB Tracker)

## TIA Review object table
- [x] Add Field - `Project Name`
- [x] Rename Field - `TIA Location Name` to `Project Address`
  - Make related record? - Multiple addresses
- [x] Add Fields - `Scope Status` - TIA Review
- [x] Add Fields - `TIA Status`

## TIA Review Details 
- [x] Add Attachment Form - TIA Attachment
- [x] Rename Attachments | TIA Request Review`  to `TIA Scope Review Attachments`
  - [x] Banner: TIA Review Fees have not been paid

### Request Status 
- [x] Conditional Rule: Scope Status - `Approved` - change `TIA Review Status` - `Pending Submittal`
- [x] Conditional Rule?: Submission Status - `Approved` - change `TIA Review Status` - `Approved`
- [x] Add `TIA Review Status` - `Closed` to `Inactive`

## Submission Details
[ ] Add fields `Fee Paid Date`:  Date
  - 28 days - Due Date

- [x] Submission Process - email user user after Scope `Approved`
  - [x] link to `Review Status Details` page, so they can add a new submission
- [x] Submission Review are 28 days, not 10 days
- TIA Scope review - is 10 day review cycles

### Submission Comment
- [x] Add new field `Comment Submission Attachment`
- [x] Add new field `Attachment Type`: `Comment Memo` or `Approval Memo`

## Review Status Details
- [x] Project Name
- [x] Project Address
- [x] Scope Status: Approved?
  - [x] Hide Add Submission button until Fee Paid! 
- [x] Fee Paid  - Y/N?
  - [x] Banner to reminder: TIA Review Fees have not been paid

**Comment by dianamartin** [comment]
@TracyLinder This is the new issue for the refinement tasks I plan to do. You can add your meeting notes to the other issue and any actionable things I missed here. Just review what I've already noted.

**Comment by TracyLinder** [comment]
@dianamartin it looks great. I just emailed you their full list of fees.
