### ISSUE TITLE
Restaurants Data / Web Map / App (COVID-19) - Parking GIS Analyst

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#2781]
Parking started updating the restaurants data again for the Web App to help people find restaurants and what services they are offering.

This will be a recurring update a couple times / week until they stop updating.

**Comment by jaime-mckeown** [comment]
Updated on 5/22, 5/29.

**Comment by jaime-mckeown** [comment]
Updated on 6/12, removed 5 minute passenger zones as they are no longer valid.

**Comment by johnclary** [comment]
@jaime-mckeown check with Joseph to see if there are updates needed.

**Comment by jaime-mckeown** [comment]
Joseph never responded. There hasn't been an update in a month, closing Issue. Will create new Issue if they decide to update this data again in the future.
