### ISSUE TITLE
DTS Security Updates & Enhancements

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2783]
Schedule a meeting to create a list of security updates and enhancements that need to happen to ensure our security measures are up-to-date.

**Question to answer during the meeting:** 
If we were to get locked out/ransomed out of these services, what is the plan?

See issues in [ATD Infrastructure](https://github.com/cityofaustin/atd-infrastructure/issues?q=label%3A%22Project%3A+Security%22)

Topics:
- First priority: AWS
- Gitbook and documentation
- 1Password
- Github Teams governance

**Comment by mateoclarke** [comment]
@JaceDeloney we didn't talk about this one during planning yesterday, maybe we push this back into Sprint 32?

**Comment by mateoclarke** [comment]
Scheduled for Wed 9/30

**Comment by mateoclarke** [comment]
[Notes](https://docs.google.com/document/d/1abg62gCHXAL9bkUjs1F9EQSFdAmebcvRJ0OyoL5g9J4/edit?usp=sharing)

Next Steps
- [ ] Convert these to private issues
- [ ] Schedule a Cyber Security day (October Cybersecurity awareness month)
- [ ] Size issues in another grooming session and prioritize for a future sprint
