### ISSUE TITLE
Create Executive Team Proposal

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2786]
Rob's asked us to deliver a proposal to the executive team that includes our recommendations and next steps to improve project & task management across the department.

Working from [these slides](https://docs.google.com/presentation/d/1DgN525GtPcvaHChqzM1pRVKqOdV6Al2Nbp0Po-CWMV4/edit)

ETA is 6/11.

**Comment by johnclary** [comment]
June 2nd seems really soon, so I’ll probably push back against that after consultation w/ Peggy.

**Comment by amenity** [comment]
@johnclary - are we still on to present this next Tuesday? If so, let's meet? If we have more time, I think it might make sense to send out a brief survey/email to managers to collect some direct quotes and better define our problem... 

In theory, might this look like a regular import/update from each manager into a single application ([Miro, perhaps?](https://help.miro.com/hc/en-us/articles/360022846473-Kanban)) for the executive team? We'll get a better idea of this if we take a look at how team's are currently tracking their work.

**Comment by johnclary** [comment]
Still waiting to hear back about the presentation date, but let's plan for next Tuesday.

I love the survey idea, but am also trying to avoid up-front work on this, and we might want to refine/expand that survey based on feedback from the e-team. I think in the proposal we can just explain that we're considering a dept wide app for the executive team, but that we would want to do survey/research before making a recommendation. 

I'll schedule something with ya so we can discuss more.

**Comment by johnclary** [comment]
Just followed up again w/ Gilda on getting us a date to present.

**Comment by amenity** [comment]
@johnclary sticking this in Review/QA.  🙌
