### ISSUE TITLE
VZV: Fatalities

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#2789]
The fatality numbers in the From Fatality Review Board worksheet of [this document](https://cityofaustin-my.sharepoint.com/:x:/r/personal/lewis_leff_austintexas_gov/_layouts/15/doc2.aspx?sourcedoc=%7Beeca586a-0a14-4989-834e-1b731b3c6676%7D&action=edit&activeCell=%27Fatal%20List%27!F421&wdInitialSession=9f3ff444-b647-4f36-9364-2f9dbaca2113&wdRldC=1&cid=16b96aae-90c9-4604-b385-187d92c7264d) are what we should be trying to get to in VZV.

Currently, the count of fatalities is 18 in the viewer (Jan, Feb and March), even after re-running the script with Airflow:

![2020-05-22_20-46-14.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/f2511858-4e58-4d48-a8dd-97ddb9ed635a)

Both the crashes table, and the sum of death counts of person and primary person shows a count of 21.

![2020-05-22_18-05-29.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/a119da5c-9e85-4563-a5d1-597412c30cc8)

Primary Person (18):
![2020-05-22_20-45-31.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/154b84fb-5c94-432f-8deb-0600552b6378)

Person:
![2020-05-22_20-45-18.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/55e6e3cf-605c-4320-8a64-602a1c373d85)

**Comment by sergiogcx** [comment]
It may be worth looking into serious injuries, the difference isn't much, but it could be if the numbers start to add up:

SI Primary Person: 23
SI Person: 84

![2020-05-22_21-10-56.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ed615c2e-2998-4c76-9a86-12bc33e71d70)

**Comment by JaceDeloney** [comment]
The new jurisdictional view will inform how we make changes to the ETL so that Socrata is serving the right crash data.

**Comment by JaceDeloney** [comment]
This is outdated now that all VZV tables are aligned based on last week's work before the public release.
