### ISSUE TITLE
VZV: Years of Life Lost Bug

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#2790]
The fatality numbers in the From Fatality Review Board worksheet of [this document](https://cityofaustin-my.sharepoint.com/:x:/r/personal/lewis_leff_austintexas_gov/_layouts/15/doc2.aspx?sourcedoc=%7Beeca586a-0a14-4989-834e-1b731b3c6676%7D&action=edit&activeCell=%27Fatal%20List%27!F421&wdInitialSession=9f3ff444-b647-4f36-9364-2f9dbaca2113&wdRldC=1&cid=16b96aae-90c9-4604-b385-187d92c7264d) are what we should be trying to get to in VZV.

Gathering all deaths for Jan, Feb and March, I have used SQL and Excel to calculate the total years of life lost as of 2020 (Jan, Feb, March) and my numbers show at most 739 years.

CSV DOWNLOAD LINK:
[https://app.zenhub.com/files/140626918/678eea3a-f3b2-4273-b36c-8525459721a1/download](https://app.zenhub.com/files/140626918/678eea3a-f3b2-4273-b36c-8525459721a1/download)

![2020-05-22_18-00-25.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/563d2902-77e1-4a72-90c7-23b07ad30d71)

**Comment by mddilley** [comment]
Adding some notes condensed from [Slack convo](https://austininnovation.slack.com/archives/CHZE6BC6L/p1590503747001900?thread_ts=1590188772.414000&cid=CHZE6BC6L):

When filtering the [demographics Socrata](https://data.austintexas.gov/Transportation-and-Mobility/-UNDER-CONSTRUCTION-Vision-Zero-Demographic-Statis/xecs-rpy9/data) to crash dates from 1/1/2020 to 3/31/2020 with injury type 4 (fatality), the dataset shows 37 records. When looking closer, there is at least one duplicate record with a different person_id - P428582 and P787549. Same crash date, age, gender, etc. This would explain the Years of Life Lost calculation being much larger than the actual number in VZV.

After running the Socrata ETL script locally without pushing to Socrata, P428582 is not present when printing fatality record IDs after all of the transformations. A possible solution is clearing the Socrata dataset and running the ETL to fill the dataset. We would need to check for duplicates afterwards to ensure the ETL script is not creating duplicate records.

**Comment by mddilley** [comment]
Found a bug in the test demographics dataset (no row identifier set). This bug is not present in the production dataset. After clearing the test dataset and running the ETL twice. No duplicate records were present.

**Comment by mddilley** [comment]
See https://github.com/cityofaustin/atd-data-tech/issues/2794#issuecomment-646222580

**Comment by mddilley** [comment]
After exporting 1/1/2020 - 3/31/2020 date range(after running the updated ETL), years of life lost calculation aligns with Sergio's SQL query for the data currently available - 739 years of life lost.
[Excel of Socrata export](https://app.zenhub.com/files/140626918/19359756-140c-4123-aaa0-8e84c1dd1872/download)
