### ISSUE TITLE
VZV: By Time of Day Bug

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#2791]
The fatality numbers in the From Fatality Review Board worksheet of [this document](https://cityofaustin-my.sharepoint.com/:x:/r/personal/lewis_leff_austintexas_gov/_layouts/15/doc2.aspx?sourcedoc=%7Beeca586a-0a14-4989-834e-1b731b3c6676%7D&action=edit&activeCell=%27Fatal%20List%27!F421&wdInitialSession=9f3ff444-b647-4f36-9364-2f9dbaca2113&wdRldC=1&cid=16b96aae-90c9-4604-b385-187d92c7264d) are what we should be trying to get to in VZV.

It looks like by Time of Day is also showing data that is not present in Jan, Feb and March:

The graph reports 4 deaths on Mondays:

![2020-05-22_21-03-12.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/5bcd4f1c-8f03-4b75-afac-1cacef3fee3e)

The production data only shows two (between Jan, and March):
![2020-05-22_21-02-59.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/5bd6c184-d06c-4fae-a331-04e6b3ed48f0)

CSV DOWNLOAD:
[https://app.zenhub.com/files/140626918/003ddd97-3547-49c0-8d90-c64101e32685/download](https://app.zenhub.com/files/140626918/003ddd97-3547-49c0-8d90-c64101e32685/download)

**Comment by sergiogcx** [comment]
I could have probably re-worked the query to run against the person and primary person table, then join against crashes to get the date of the crash. Will re-factor and try again.

**Comment by JaceDeloney** [comment]
As long as we can ensure the crash numbers are correct, I think we are good for now. If not, it might be something we want to fit into:
https://github.com/cityofaustin/atd-data-tech/issues/2687

**Comment by sergiogcx** [comment]
It looks like prod numbers are consistent across tables. For this particular issue, it appears that the numbers of Monday are graphed on Friday, Tuesday is being graphed on Thursday, Wednesday is mapped correctly, Thursday numbers are mapped as Tuesday, Friday as Monday, and Saturday as Sunday.

![2020-05-26_11-32-26.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/f664f68d-3353-4018-b863-eccd47a04740)

**Comment by JaceDeloney** [comment]
The new jurisdictional view will inform how we make changes to the ETL so that Socrata is serving the right crash data.

**Comment by mddilley** [comment]
GraphQL query to check fatality totals by day of week

```
query getCrashesSocrata {
  atd_txdot_crashes(limit: 100, where: { _and: [{death_cnt: {_gt: 0}}, {crash_date: {_gte: "2020-01-01"}}, {crash_date: {_lte: "2020-05-31"}}, {day_of_week: {_eq: "SUN"}}]}) {
    day_of_week
    crash_id
    crash_date
    crash_time
    death_cnt
  }
  atd_txdot_crashes_aggregate(limit: 100, where: { _and: [{death_cnt: {_gt: 0}}, {crash_date: {_gte: "2020-01-01"}}, {crash_date: {_lte: "2020-05-31"}}, {day_of_week: {_eq: "SUN"}}]}) {
	aggregate {
    count
  } 
  }
}
```
