### ISSUE TITLE
VZV: Demographics: Fatalities by Age (bug)

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#2794]
The fatality numbers in the From Fatality Review Board worksheet of [this document](https://cityofaustin-my.sharepoint.com/:x:/r/personal/lewis_leff_austintexas_gov/_layouts/15/doc2.aspx?sourcedoc=%7Beeca586a-0a14-4989-834e-1b731b3c6676%7D&action=edit&activeCell=%27Fatal%20List%27!F421&wdInitialSession=9f3ff444-b647-4f36-9364-2f9dbaca2113&wdRldC=1&cid=16b96aae-90c9-4604-b385-187d92c7264d) are what we should be trying to get to in VZV.

### Demographics: Fatalities by Age

We know the total deaths from both the graph in the `By Month/Year` graph and from the database:
![2020-05-26_12-17-10.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/2ed10268-02d5-4ee8-9fc0-fdeaa04c43f7)

The data seems off, to begin with the total number of fatalities in 2016 is 91, and the year 2016 in the graph shows a total of 182 (exactly twice the actual amount):

Created an issue:
![2020-05-26_13-13-40.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/8d99324a-8644-44b4-a5ad-b308e16754b8)

2017: 79 total deaths, 158 shown in the graph.

![2020-05-26_13-16-26.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/7b6c3ef9-d240-4026-9576-015f143ebe35)

2018: 74 total, 146
![2020-05-26_13-17-49.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/b97c2cca-bfed-48aa-979a-279848c971e9)

**Comment by mddilley** [comment]
Both the [test demographics dataset](https://data.austintexas.gov/Transportation-and-Mobility/-UNDER-CONSTRUCTION-TEST-Crash-Report-Data/3aut-fhzp/data) and [production dataset](https://data.austintexas.gov/Transportation-and-Mobility/-UNDER-CONSTRUCTION-Vision-Zero-Demographic-Statis/xecs-rpy9/data) have been truncated and populated with all records from our production Hasura instance. The ETL script has been updated to do a full replace on each future run. 

- [ ] Need to check totals against VZ team numbers
