### ISSUE TITLE
IT Support: Weird field in Data Tracker for BBS

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2799]
Joshil B. 
AMD

Emailed
>I noticed a weird case where a “Yes” or “No” option field had both on the signal page for signal 513 and a few other listed below. The “Edit Cabinet” page for it shows it as a “Yes”. Do you know why this error is happening? 513 has no secondary signal which might explain a few of the others. Thanks!

**Comment by dianamartin** [comment]
I looked into this and checked if there was more than one signal cabinet record. This particular signal has 2 records. 

Emailed user
>I looked into this. So there seems to be 2 signal cabinet records under this same signal: 513. 
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/0119a159-bd4d-4df1-ae3c-e183ba050bdc)
>Because there are 2 records under this signal, the UPS field is showing both record instances. Do these records seem incorrect or are they correct?

**Comment by dianamartin** [comment]
Talked to Joshil and go clarity on the cabinet record duplicates. He's going to compile list of cabinet IDs that need to be deleted that are duplicates in the system.

**Comment by dianamartin** [comment]
Joshil send the list of cabinet IDs that need to be deleted
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/d35c29e7-9fca-4356-bcc1-27e9f93cef0b)

**Comment by dianamartin** [comment]
Deleted | Cabinet ID | Signal ID |
-- |-- | -- |
No | 957 | 1023|
No | 961 | 1036
No | 918 | 225
No | 956 | 225
No | 479 | 245
No | 988 | 4066

**Comment by amenity** [comment]
@dianamartin please close after you remove the duplicates

**Comment by dianamartin** [comment]
I forgot that I asked Joshil this back on 6/3. 

**Conversation**
>Hey, remind me for Signal 225, we were deleting the cabinet that was on the SW corner bc the cabinet is actually on the NE corner?

He said
>Yep, that's right!
It's on the N side since it's split between two intersections but I suppose that's just semantics

- [x] Deleted Cabinet with `ID 956` - SW Corner
