### ISSUE TITLE
Discuss VZA Roles and Permissions for ATD Staff

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2812]
### Objective 
Discuss our proposed [VZA roles and permissions schema](https://docs.google.com/spreadsheets/d/19koOVm19TQg861cnB0JKMxYjfd3PyldgPDl8oY-Nukk/edit#gid=0) with Jen and Lewis. 

------
- [x] Schedule meeting - 10am, 6/1/20
- [x] Meet and take notes
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes

Surbhi is showing user role matrix

### 4 roles: Scheduler, Viewer, Admin, Officer
- **Scheduler** - Lewis is this role right now
  - Can create, edit, delete assignments
- **Viewer** - MMC
  - See All and Today's assignments
  - View Locations
  - See officer contact info
- **Admin** - Randy and Pat
  - See all assignments
  - See Today's assignments
  - View Locations
  - See officer contact info
  - List of more officer info
- **Officer**
 
### Comments
- Lewis thinks it's a privilege to share the officer locations and where an APD officer is going to be weeks and weeks in advance
  - Limiting the number of folks to limit the access the enforcement schedules
- Jen says MMC - 5 people: not a large group
  - They have access to information that is privileged and shared. Already operate in degree of confidentiality. 
  - Don't want that group to have restrictions, but really only need to see that day. 
  - Would want Billy to see everything (all assignments)

## Decisions 
- Edit the type of shifts based on their business need (VZA v. AMD Signal work)

**Comment by johnclary** [comment]
Thanks. I agree with Jen :).

Question r.e. schedule vs admin—can they not be the same role? Lewis does not/should not have access officer info?

**Comment by amenity** [comment]
@johnclary - I think part of the reason to separate them would be simplifying the interfaces for Randy & Pat. Having access to all the Scheduler features and views might be excessive for the work that they're doing.

**Comment by amenity** [comment]
Along those same lines, Lewis was wondering why Viewers would need access to the Locations list. I'm unsure about this as well. @SurbhiBakshi - what was your thinking there?
