### ISSUE TITLE
Integrate Banner with COVID-19 Time Tracking App

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2816]

**Comment by amenity** [comment]
@johnclary @JaceDeloney - Should we pull _[Integrate Authoritative Employee Data](https://github.com/cityofaustin/atd-data-tech/issues/2167)_ out of the Icebox and close this one as a duplicate?

**Comment by dianamartin** [comment]
@johnclary @JaceDeloney @moorerst This has been done
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/cb605066-59e5-424d-b510-b93aea94f70a)
