### ISSUE TITLE
Review and refine Feature Map

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2819]
[Feature Map](https://docs.google.com/spreadsheets/d/1gNCz63qFpztiuL_JK4aPNnicjCglmATOW1dbpU0wxWk/edit#gid=793932181)
- Solidify Themes and Capabilities
- As we go, ad hoc definition of: 
    - [Terminology](https://docs.google.com/spreadsheets/d/1gNCz63qFpztiuL_JK4aPNnicjCglmATOW1dbpU0wxWk/edit#gid=1110509577)
    - [Roles](https://docs.google.com/spreadsheets/d/1gNCz63qFpztiuL_JK4aPNnicjCglmATOW1dbpU0wxWk/edit#gid=1693974191)

**Comment by amenity** [comment]
This is looking so great, @SurbhiBakshi 👏 

- Overall everything worked as expected
- When I was testing on Friday afternoon, I encountered some performance issues — blank pages, taking a long time to load when switching between tabs — but seems fine Sunday night. 

Page-specific notes: 
### [Sign Up](https://atd.knack.com/vza#sign-up/)
- [ ]  Make "Shift" a radio button
- [ ]  Date range  dropdowns → Two calendar fields, "From" and "To" that default to "Today" and (blank)

### [My Assignments](https://atd.knack.com/vza#my-assignments/)
*Today's Assignments*
- Folder icon... seems strange but I have no better suggestions... 🙃

*Future Assignments*
- [ ] Remove "Remove From My Assignments" column title and replace "X" in cell with "Remove"
- [ ] Remove availability of "Assigned Officer" filter in table

*Remove Assignment modal*
- Can we hyperlink to the cancellation policy in the modal? If not, let's add a link on the My Assignments page somewhere. 

*Calendar*
- [ ] Remove "____ per page" drop down

### Current Assignment
- Need to [tweak CSS](https://github.com/cityofaustin/atd-data-tech/issues/2990), but buttons and notifications work well
- "Current Assignment" won't make sense if they are looking at a past or future shift; can the breadcrumb be the date and time 
![Screen_Shot_2020-06-14_at_11 58 18_PM](https://user-images.githubusercontent.com/1463708/84621334-e13b1480-ae9f-11ea-9c4a-a0d4329dfa97.png)
    If this is not doable, let's just use "Assignment"
- Does the user need to see the "Status" field? "Future" is confusing. 
- Not sure about the start/stop workflow... Ideas:
    - "Start" and "End" buttons are next to each other at the top of the page.
    - Show a "Start Time" and "End Time" field, these are populated when the respective button is clicked?
   - Buttons could even go in the table itself:
![Screen Shot 2020-06-15 at 12 10 48 AM](https://user-images.githubusercontent.com/1463708/84621378-f9ab2f00-ae9f-11ea-8e99-fc86a88cea8b.png)

**Add Notes**
- [ ]  Update Add Notes text:
    During your shift, please add notes in the following situations:
    - **No Violation Observed** - to explain any period over 20 minutes you do not record violations in Brazos, e.g. "Stopped to get gas" or "Rainstorm — no one out"
    - **Cause for Concern** - to report a dangerous conditions, e.g. "Many pedestrians crossing mid-block on Cesar Chavez between Comal and Chicon"

**Notes**
- Timestamp is one hour fast
- Add "Delete" link/button in Edit Note modal
- I don't think we need the "Back to My Assignments" link at the bottom of the page anymore.

**Comment by SurbhiBakshi** [comment]
Thanks @amenity! Will take a look at the notes and refine. Going to put the notes in the Test issue, this is Moped :-)
