### ISSUE TITLE
Compile list of UI views

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2820]
Documenting these will help us evaluate component libraries and produce initial wireframes:
- [UI Views](https://docs.google.com/spreadsheets/d/1gNCz63qFpztiuL_JK4aPNnicjCglmATOW1dbpU0wxWk/edit#gid=1731506475)
- [UI Components](https://docs.google.com/spreadsheets/d/1gNCz63qFpztiuL_JK4aPNnicjCglmATOW1dbpU0wxWk/edit#gid=241402064)

**Comment by zappfyllc** [comment]
UI Views completed as of 6/29.

**Comment by amenity** [comment]
Jace and I will start to put these together as we divide and own features and compile mocks.
