### ISSUE TITLE
Meeting: RPP Sprint Review #6 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2826]
### Participants
Van, Dan, Steve, Surbhi, Stephanie, Diana, Joseph

### Agenda
- Share Results of Usability Testing Round 2 
- Ask any clarification questions
- Demo
------
- [x] Schedule meeting 5/28/2020
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
@SurbhiBakshi Add any notes you have, thanks for joining us

**Comment by SurbhiBakshi** [comment]
@dianamartin @moorerst - think Diana covered all the notes I had, but wanted to add this comment from Joseph - **It gets better and better, turning out better than expected.  This is awesome, flow is great, information is great. **

**Comment by moorerst** [comment]
Sent invite for Follow up meeting with Steve for Monday June 1st
Sent email with Action Items for myself and RPP team

**Comment by amenity** [comment]
Great job, amigas!! @dianamartin @moorerst 🙌
