### ISSUE TITLE
Update age brackets

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2828]
VZ Team has requested that we rethink how we're displaying crash data based on age. Currently we're using the Census Burueaus guidelines for age brackets. However, Austin residents aged 20-30 are disproportionately represented in crashes with fatalities or serious injuries.

Create 8 age brackets/categories:
- Age range: 0-15 Color: #453781
- Age range: 16-25 Color: #33638D
- Age range: 26-35 Color: #238A8D
- Age range: 36-45 Color: #29AF7F
- Age range: 46-55 Color: #73D055
- Age range: 55-64 Color: #DCE319
- Age range: +64 Color: #FDE725
- Age range: Unknown Color: #FE9F3E

Color palette for this chart only:
#453781
#33638D
#238A8D
#29AF7F
#73D055
#DCE319
#FDE725
#FE9F3E
<img width="137" alt="Screen Shot 2020-08-07 at 11 50 32 AM" src="https://user-images.githubusercontent.com/10567316/89668944-3d208900-d8a4-11ea-839b-f2c91f3fcf00.png">

![Screen Shot 2020-05-28 at 11.37.56 AM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/1f97bff8-f528-4c18-bb0c-83a42e88c1e5)

**Comment by JaceDeloney** [comment]
![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/7af456ce-e60a-4a0d-8976-cf11e814b46d)

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/a1f1fb28-fe20-4276-b443-447998626a8e)

**Comment by johnclary** [comment]
"victim population ratio"—I like this!
