### ISSUE TITLE
Post Payment Bug: Folder issues when paying random fees

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2834]
Paying an inspection fee (or any fee really) will make an expired permit go active. 
- Is this only happening on EX folders?
- Tracy will test this more

**Comment by TracyLinder** [comment]
EX RSN 12384601: Failed
Added & Paid investigation fee, then the folder status updated to Active

**Comment by TracyLinder** [comment]
TURP RSN 12115381: Failed
Added & Paying an investigation fee updated status to Active

**Comment by johnclary** [comment]
Sent to Unisys.
