### ISSUE TITLE
D. Johnstone AGOL account upgrade

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#2841]
Submitted request to CTM to upgrade D. Johnstone's AGOL account to Power User so he can create feature services for upcoming Active Transportation's virtual open houses.

**Comment by johnclary** [comment]
Waiting for Dylan's account to be upgraded. @alan-deanda plz follow-up w/ CTM

**Comment by jaime-mckeown** [comment]
@alan-deanda I need the Request # from Service-Now.

**Comment by jaime-mckeown** [comment]
I searched Service-Now for Alan's request, could not find one anywhere. Submitted the request again, asked for change to be made ASAP since the original request last week never went through.

**Comment by alan-deanda** [comment]
Thanks @jaime-mckeown  I think I may have accidentally submitted it to their training environment, I bookmarked it on accident :\

**Comment by jaime-mckeown** [comment]
Oops! @alan-deanda. I just got a notification that the Request was created so hopefully the request will be completed soon.

**Comment by jaime-mckeown** [comment]
Dylan's account has been upgraded to a COA Power User.
