### ISSUE TITLE
RPP Back Office Go Live Planning Meeting

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2848]
### Objective 
Plan for June 8th Back Office Go Live. Review workflow and answer outstanding questions.

### Participants
- Jacob, Courtney, Steve, Stephanie, Diana, Joseph

### Agenda
•	Ask if we need to transition any data, 60 day worth? (to have Finance see real data)
•	Ask if they plan to continue to use and send spreadsheet for Finance?
•	Ask to see permit payment spreadsheet
•	Review RPP workflow - current state (without cashier) and future state (with cashier)
•	Volunteer help to input data

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by moorerst** [comment]
•	Ask if we need to transition any data, 60 day worth? (to have Finance see real data)
•	Ask if they plan to continue to use and send spreadsheet for Finance?
•	Ask to see permit payment spreadsheet
•	Review RPP workflow - current state (without cashier) and future state (with cashier)
•	Volunteer help to input data

**Comment by dianamartin** [comment]
## Diana's Notes
- Overview of Sprint Review
- Discussion and Concerns for RPP Staff

#### Soft Go Live 
- June 8th - still on for back end staff
- July/August: Public Go Live? With or without payment?

#### Follow-up meeting: Online Payment Discussion - set up ASAP with Jason, Jacob, Joseph, John, Diana, Stephanie
@johnclary We're a green light on having conversation this week, let's sync on this!

#### Transition Data into Database?
- Goes back to at least 2018, 2019
- Oct 2019 - this fiscal year
- [ ] Action: Steve to sent spreadsheet 

#### Financial spreadsheet 
- discontinue use of financial spreadsheet
- Finance signs off on being able to get data out of database

### Current State of Payments?
- Payment Information being handled - Steve
- Cashier position - cash handling training
  - Need new Cashier page 
  - Log in to designated Cashier page 
  - Help guides documents
- Shared Mobility Services - Moving to Toomey? Maybe in August

- Go Live Meeting
  - Walking through RPP backend workflow steps

Actions: 
- Public survey at the end of payment, embed in email
- Updated any Hours of Operation: (Wed- Thurs 9-2:30 pm)

**Comment by dianamartin** [comment]
@moorerst add any notes here if you need to

**Comment by dianamartin** [comment]
Sent email to Courtney asking about the updated Hours of Operation since the external public site doesn't look updated yet.

**Comment by dianamartin** [comment]
- [x] Updated Hours of Operation
