### ISSUE TITLE
Planning Meeting: Teams Training - Round 2

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2865]
**Basics to running a large meeting**
- How to efficiently screen share
- Meeting Notes - recording
- Whiteboarding

**Best Practice**
- Turn off your cameras if you have a lot of participants
- Make sure you’re running teams directly from computer not remoting and then running teams
- Downloading teams on your phone and taking teams call from your phone (crisper audio) 
- Downside: can’t see screen shares very well, small screen real estate
- Can’t screen share from phone

**Look into**
- Teams Live meeting 250 
- Control participant speaking
- Test Live Meeting
- Reference WPD, talk to Jennifer Lash

**Comment by johnclary** [comment]
doc: https://docs.google.com/document/d/1PDYUP7c-mflQNEuLMzlydl9vJnq9_0zhJmRRiZfQl6U/edit

**Comment by dianamartin** [comment]
## Diana Notes

### Large Meeting Best Practices
- Set up meeting that you don't have lobby (allow all people in organization) - (Moderator role)
- Setting up screen share, test beforehand 
- White board functionality in MS Teams: look into this, watch some videos, ask CTM gurus
- Meeting Recording function (presenter, starts recording)
  - Write it in the meeting or notes (reminder)
- Raise hand in meeting (toggle On-Off)
  - lower hand
- Mute All (Mute everyone) - anyone can mute
- Make person attendee status (Viewer)
- One person presenting, (Meeting moderator)
- Set Meeting Ground Rules reminder: to mute and raise their hand - before meeting starts
  - Technical ground rules and manners
  - Ex. Being respectful
  - Ex. Mute yourself when not talking


### Best Practice
- Experiencing bandwidth issues: Turn off incoming video
- Turn off your cameras if you have a lot of participants
- Make sure you’re running teams directly from computer not remote session and then running teams
  - Uses city's shared network resources
- Optional: Downloading teams on your phone and taking teams call from your phone (crisper audio)
  - Downside: can’t see screen shares very well, small screen real estate
  - Can’t screen share from phone
- Call internal people without sharing your cell phone

**Comment by dianamartin** [comment]
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/fa602f8d-8772-4bad-add7-de036fd0ac90)

**Comment by johnclary** [comment]
Closing this :)
