### ISSUE TITLE
Deliver Dry Run of Teams Training 2.0  

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2869]

**Comment by johnclary** [comment]
- rename presentation to "Hosting Meetings Like a Pro" :)
- go slower when demoing features
- pause after each slide and ask for questions
- note that by default, everyone in the meeting is an "organizer" and can share content and mute others. (this may not be the case for Live meetings, right?)
- who can allow people into the lobby? answer: any "organizer"
    - show how you can "make people attendees"
- try creating a teams live event: note that you cannot do this from Outlook
- if you can't create a teams meeting in Outlook, close outlook, open teams, then open outlook again.
- add a slide with a screenshot of the screen-sharing menu. explain the difference between sharing an app and sharing your entire desktop
- how long does the meeting recording last for? does it expire?
- mention that recording creates a transcription of the meeting
- you can join your meeting ahead of time to test it out with a colleague :)
- r.e. moderator: they can also take notes :)
- r.e. ground rules: explain that as a meeting organizer, you should discuss the ground rules at the beginning of the meeting.
- "best practices": Use this wording: "Use MS Teams on the computer that's in front of you, not your remote workstation."
- mention that the meeting chat becomes a chat in Teams, and that you can filter your Teams chat by "meetings"

**Comment by dianamartin** [comment]
@johnclary Added these thing to the [slide deck](https://docs.google.com/presentation/d/105mWd20ZM_ivYhwhUyhlW3xGFd1btcNFer_ik8HiPas/edit)
