### ISSUE TITLE
Create Teams Training Slides

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2870]
Keep it slim!
- agenda
- brief pro-tips
- links to training resources

[Teams Training Slide deck](https://docs.google.com/presentation/d/105mWd20ZM_ivYhwhUyhlW3xGFd1btcNFer_ik8HiPas/edit#slide=id.g863b74f0b5_0_26)

**Comment by dianamartin** [comment]
Large Meeting Best Practices

    Set up meeting that you don't have lobby (allow all people in organization) - (Moderator role)
    Setting up screen share, test beforehand
    White board functionality in MS Teams: look into this, watch some videos, ask CTM gurus
    Teams Live Event v. Reg Meeting: what's the difference? (250 ppl - Jennifer L.)
    Meeting Recording function (presenter, starts recording)
        Write it in the meeting or notes (reminder)
    Raise hand in meeting (toggle On-Off)
        lower hand
    Mute All (Mute everyone) - anyone can mute
    Make person attendee status (Viewer)
    One person presenting, (Meeting moderator)
    Set Meeting Ground Rules reminder: to mute and raise their hand - before meeting starts
        Technical ground rules and manners
        Ex. Being respectful
        Ex. Mute yourself when not talking

Links

    Roles in Teams Meetings
    Power Point slides
    Microsoft Teams video training
    Share Content in a meeting in teams

Best Practice

    Experiencing bandwidth issues: Turn off incoming video
    Turn off your cameras if you have a lot of participants
    Make sure you’re running teams directly from computer not remote session and then running teams
        Uses city's shared network resources
    Optional: Downloading teams on your phone and taking teams call from your phone (crisper audio)
        Downside: can’t see screen shares very well, small screen real estate
        Can’t screen share from phone
    Call internal people without sharing your cell phone
    Video is optional, is encouraged. Personal and communication is more effective!

End Training

    Give Resource Links
    Encourage testing with colleagues

**Comment by dianamartin** [comment]
@amenity I've added the slide deck to this issue and build up an outline.
