### ISSUE TITLE
Meet with Finance to Discuss Stripe

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2872]
Schedule for 6/4 @ 10am.

> Hi Dan—Knack has built-in support for Stripe payments, and we want to use this functionality to enable online payments for residential parking permit customers.
> 
> Stripe charges 2.9% + 30¢ per transaction.
> 
> We need your guidance:
> 
> What are the contractual/procurement considerations around using Knack + Stripe? Stripe is the only "anonymous" payment processor that integrates with Knack. (PayPal is also supported, but it requires a user to have a paypal account)
> What are the considerations around adding a 30¢ fee convenience fee for customers who pay online?

**Comment by johnclary** [comment]
[here's the Stripe service agreement](https://stripe.com/legal).

**Comment by dianamartin** [comment]
## Diana's Notes

**Participants:** 
Jacob, Joseph, Peggy, Dan, John and Diana

### Concerns Generally
- We have licenses for Knack? Yes
- Knack utilizes Stripe as their payment option

**Passport - Park ATX app**
- Contract have a contract for the app
- Process the payments, merchant of record (spelled out in the contract)

**Payment Processor**
- Stripe and Pay Pal
- Merchant processing fees pass to customer

**Proposed Process** 
- Customer gets permits on Knack - transactions are taken through Stripe (2.9% transaction fee)
- Collect transaction fee default

**Master Agreement - Terms and Conditions**
- City Procurement 
- fairly quickly, processed through Central Purchasing
- Letter of exemption, signatures on the contract

John to get with Stripe contract sales, set it up similarly to Passport (merchant processor)
- charge fee of transaction
- set up Stripe with our own bank account and pay fee on top of it
- fees will come from bank account
- Stripe bank account and then money will be sent to ATD, they would take the fees out that customers pay and take off the processing fees

Action Items: 
- John to talk to Stripe
- Dan V. - will do background research to process the Master Agreement (MA)

**Comment by dianamartin** [comment]
@johnclary did you hear back from Controller and Dan? Are we ready to to set-up a follow-up meeting?

**Comment by moorerst** [comment]
John to follow up with Finance on online payment with Stripe.

**Comment by johnclary** [comment]
We're meeting with the Treasury to discuss on 7/15
