### ISSUE TITLE
Add Signal locations to VZA App and VZA AGOL feature class

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2874]
We want the Street Signal locations maintained in Data Tracker to be available in the VZA App so that Billy can schedule APD officers to direct traffic during signal maintenance/repair activities. 

LOCATION_ID | AGOL_FEATURE_ID | Name | Display Name | Description | Location Type | Status | APD Sector | Council District
-- | -- | -- | -- | -- | -- | -- | -- | --
Auto Increment | Short Text | Short Text | Calculated field | Short Text | Multiple Choice? | Multiple Choice | Multiple Choice | Multiple Choice
  |   | Map to `LOCATION_NAME` in Data Tracker | `[APD Sector] - [Type] - [Name]` |  | Set to `Signal` | Set to `Active` | (bulk populate with spatial join) | (bulk populate with spatial join)

**Comment by amenity** [comment]
Per discussions [here](https://github.com/cityofaustin/atd-data-tech/issues/2700), it sounds like a new Signals object would be the way to go.  

### Questions 
How do we want to map AMD Data Tracker fields to VZA fields? Should the Signals object have different fields/columns than the the [Locations object](https://docs.google.com/spreadsheets/d/11HuTKGz5Lc5v3KVZIKKphZk65XcQJOYaG9tC379133Q/edit#gid=0)?

How should we get signal locations into the VZA app?
   - Regular manual import from AMD Data Tracker? We'll be doing annual updates of school locations from an AISD CSV, but this might not be frequent enough for signals. 
   - Email triggers when new signal is added in AMD Data Tracker ---> DTS GIS manually adds signal to VZA App
   - Same as Lewis' workflow for other locations: Billy add signal, automatically set to status of `Needs GIS` and kicks off email to Jaime & Alan, they manually add it to VZA AGOL feature set and add the `AGOL_Feature ID` and set `Status` to `Active` from Knack Builder
   - Script - @SurbhiBakshi suggested Python + Airflow like we're doing with Dockless Mobility

**Comment by johnclary** [comment]
If someone blocks off four hours on my calendar, I will do the integration. Just need to know exactly which fields (field name and field id (`field_xx`) you need from Data Tracker in VZA.

**Comment by amenity** [comment]
@johnclary🙏  😊

**Comment by SurbhiBakshi** [comment]
@johnclary  - Here is a field connection list - [AMD Data Tracker to VZA signal locations](https://docs.google.com/spreadsheets/d/1LBEkx0xK7ohcUuhRnnarSP2WJXntPOQRLRbG9H-1E6M/edit?usp=sharing)

**Comment by SurbhiBakshi** [comment]
@amenity - Blocked time on @johnclary 's calendar on Nov 20th.

**Comment by SurbhiBakshi** [comment]
@johnclary - moved to Jan 8th

**Comment by SurbhiBakshi** [comment]
@johnclary - the field connection list has been updated.

**Comment by johnclary** [comment]
@SurbhiBakshi this is done and and new/modified signals in the Data Tracker will be pushed to VZA on a nightly basis. Because I used an existing API view for this, it's pushing all signals records to VZA except those that are in a "VOID" status. It would be a few more hours of work to further filter the data, so I thought I'd ask if it's too much trouble for you to filter the pick-lists in VZA to exclude signals in statuses you don't won't to show to users.

You can peep this task in Airflow; it's called `atd_knack_data_tracker_signals_to_vza`. Processing failures will be logged to `#atd-airflow` in Slack.

**Comment by SurbhiBakshi** [comment]
Thanks @johnclary! Will not take much time to put in filters for Status.
