### ISSUE TITLE
Healthy Streets Installation-check webapp

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#2886]
This request calls for creating a Crowdsource Polling App for engineers to give their QA/QC check for the traffic control devices that are installed for Healthy Streets. The engineers could take note of the date of install, the condition of the asset, and free-form comments. Photo attachments would be enabled but not required.

**Comment by alan-deanda** [comment]
We will move forward with this app once we have traffic control plans for the next batch of Healthy Streets that will roll out.

**Comment by johnclary** [comment]
@alan-deanda what's the latest?

**Comment by alan-deanda** [comment]
@johnclary  the team expressed interest in such an app for batch 2 at the last meeting, but they likely won't focus on it until the public feedback process is closed and the data has been analyzed.

**Comment by johnclary** [comment]
Thanks. when does the public feedback process close?

**Comment by alan-deanda** [comment]
Removing the estimate and closing, this app was never asked for again.
