### ISSUE TITLE
Mobile Signals | Knack not connecting new time log records with work order records

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#2891]
While testing some bug fixes, I noticed that new time logs were no longer connecting to their associated work order records in either test or production (a similar bug to https://github.com/cityofaustin/atd-data-tech/issues/2474). The POST requests were successful but the returned response contained an empty string for `field_1424` (the ID of the associated work order). Adding `field_1424` to the TEST form in Knack (`scene_297` and `view_1252`) fixed the issue, but this also adds the field to the TEST Knack app form which we do not want.

I contacted Knack support, and they suggested adding `field_1424` to the form and hiding it. I hid the field if `field_1437` (arrive time) is not blank (which is always true since it auto-populates). This resolves the issue in `17 JAN 2020 | TEST - Austin Transportation Data Tracker` when tested from the React app locally.

@johnclary @dianamartin Does this sound like a reasonable solution for production Data Tracker? Let me know if I can provide more info. I will not change anything there until I get a go ahead.

#### Change to form
<img width="1300" alt="Screen Shot 2020-06-03 at 11 37 23 AM" src="https://user-images.githubusercontent.com/37249039/83664160-3d906100-a58f-11ea-992a-8847a4d00632.png">

#### Form rule
<img width="962" alt="Screen Shot 2020-06-03 at 11 36 55 AM" src="https://user-images.githubusercontent.com/37249039/83664163-3ec18e00-a58f-11ea-8e7d-3cdfa792313d.png">

#### Knack support
<img width="249" alt="Screen Shot 2020-06-03 at 11 23 32 AM" src="https://user-images.githubusercontent.com/37249039/83664284-66b0f180-a58f-11ea-9cc4-fd8824fed23e.png">

<img width="242" alt="Screen Shot 2020-06-03 at 11 23 20 AM" src="https://user-images.githubusercontent.com/37249039/83664302-6d3f6900-a58f-11ea-81d4-39733b1bf03d.png">

**Comment by dianamartin** [comment]
@mddilley I think it's a reasonable solution. @johnclary thoughts?

**Comment by mddilley** [comment]
Updated the form to include the hidden `ATD_WORK_ORDER_ID` field (`field_1424`) in production (`Austin Transportation Data Tracker | PRODUCTION`) and tested from the mobile app. Time logs now connect with their associated work order records, and the form in the Knack app remains unchanged from the user perspective.
