### ISSUE TITLE
Modify Vision Zero Crash Dataset Titles in Socrata

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2895]
Right now the titles for the Vision Zero crash datasets are titled:
- [Vision Zero Demographic Statistics](https://data.austintexas.gov/Transportation-and-Mobility/Vision-Zero-Demographic-Statistics/xecs-rpy9/data)
- [Vision Zero Crash Report Data](https://data.austintexas.gov/Transportation-and-Mobility/Vision-Zero-Crash-Report-Data/y2wy-tgr5)

Change the titles for the Vision Zero crash datasets to:
- [x] Vision Zero Crash Report Data
- [x] Vision Zero Crash Report Data - Demographic Statistics

- [ ] The link to the Data section of the VZV footer should be:
https://data.austintexas.gov/browse?q=vision%20zero%20crash%20report%20data&sortBy=relevance

We need to update these for the following reasons:
- They should indicate that they are the authoritative crash datasets for the city
- They should use the same prefix so that we can reference them in the VZV footer data link
- They should indicate that they are part of the Vision Zero program in the description

**Comment by mateoclarke** [comment]
@SurbhiBakshi, once requested by @jgabitto, can you securely share Socrata credentials with him in order to complete this task?

**Comment by mateoclarke** [comment]
Ex link to page to edit title: https://data.austintexas.gov/Transportation-and-Mobility/Vision-Zero-Crash-Report-Data/y2wy-tgr5/revisions/35/metadata/dataset

**Comment by jgabitto** [comment]
Ok dataset titles have been updated:
- ![image](https://user-images.githubusercontent.com/26661521/123682795-16977380-d811-11eb-9274-e4d838bd7d7d.png)
- ![image](https://user-images.githubusercontent.com/26661521/123682816-1e571800-d811-11eb-8039-d4b29e464956.png)
