### ISSUE TITLE
Create PR for headset amplifiers and ac power supply

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#29]
Submitted PR in system, waiting for "Technical Review" by Scott.

**Comment by dianamartin** [comment]
Scott's approved PR for Technical Review, assigned to @johnclary

**Comment by dianamartin** [comment]
waiting for @johnclary to review/approve and send to Finance..

**Comment by amenity** [comment]
@dianamartin @johnclary - didn't we get these already 🎧 🔌 ?

**Comment by dianamartin** [comment]
@amenity no, these are still in the PR system and need approval. These have not been ordered.

**Comment by amenity** [comment]
@john, update PR and approve.

**Comment by dianamartin** [comment]
@johnclary Are we going to cancel this PR?

**Comment by dianamartin** [comment]
@johnclary FYI: You should have this in your review queue.
