### ISSUE TITLE
Product: ATD Visitor Sign-In

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2901]
A web-app that enables visitors to sign in/out of various ATD office locations. 

## Login

Please contact [DTS support](https://atd.knack.com/dts) for instructions to login to this application.

## Background and Context

This application enables visitors to sign in/out of various ATD locations. Per [City rules](http://www.austintexas.gov/edims/document.cfm?id=277562), the sign-in form asks users to indicate whether or not they are visit to the ATD facility consists of lobbying work. The application has special admin tools for the the Right-of-Way division which enables permitting analysts to keep track of how many customers are waiting for specific permit types.

## Technology

Knack application

![cityhall](https://user-images.githubusercontent.com/14793120/102003490-c8d07900-3ccd-11eb-8a0c-ea92fdf46747.jpg)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://data.mobility.austin.gov/about/) team. Project status is documented regularly in the comments below.

**Comment by dianamartin** [comment]
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/64edff71-1623-4db8-8289-2460d075bd17)

**Comment by johnclary** [comment]
@dianamartin @amenity any idea of this app is still being used at BOP? I believe they were the last remaining workgroup.

**Comment by dianamartin** [comment]
@johnclary we'd have to check with Scott

**Comment by amenity** [comment]
@scottreedy - do you know?

**Comment by dianamartin** [comment]
The Apps team planned on deprecating this. Scott told us they no longer use it.

**Comment by scottreedy** [comment]
No site uses it except BOP I believe. Let me check up front

**Comment by amenity** [comment]
I confirmed with Adan S. that it's no longer used.

**Comment by johnclary** [comment]
Heads-up that there is a [public dataset](https://data.austintexas.gov/Transportation-and-Mobility/Austin-Transportation-Department-Visitor-Log-For-O/tkk5-uugs) whose description should be updated or maybe just taken down completely.
