### ISSUE TITLE
Product: ROW Portal

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#2904]
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/32ebbaf1-edf0-408e-8458-619c4bfaf92f)

## Description
Application to manage TCP reviews. Currently migrating from AMD Data Tracker to this application. 

### Stakeholders/Product Manager: 
- Ryan M., Paloma A. 
- Tracy L.

### Resources
- **Network G:// Drive:** `G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\app_ROW_Portal`
 - **exported_tables** folder
 - **import_tables** folder
  - **atd_metadata_row** - text file
  - **atd_metadata_row_CORRECTED** - text file
  - **reviewers_all_time** - text file

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://data.mobility.austin.gov/about/) team. Project status is documented regularly in the comments below.

**Comment by dianamartin** [comment]
Still needing to migrate TCP data into new application. Testing of data migration is On-going.

**Comment by amenity** [comment]
@dianamartin @johnclary - who is the PM for this?

**Comment by dianamartin** [comment]
@amenity undesignated bc it was a back burner project. So unofficially John was PMing..

**Comment by amenity** [comment]
@dianamartin - thanks. 🙏
@TracyLinder - here's a new product for ya. Diana can tell you what it does. 😆

**Comment by TracyLinder** [comment]
I'm closing this. Please see #4699 for the Product Issue for the ROW Portal.
