### ISSUE TITLE
Update the High Injury Network overlay w new shapefile

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2907]
We received a new shapefile for the High Injury Network overlay. This new shapefile includes the “High Injury Roadways” (HIROAD flag = 1).

We need to update the following:
- [x] Import new shapefile into VZV (attached)
- [x] Edit the shapefile color and line elements so that they are easily identifiable (High-Injury Network: #fc9272, High-Injury Roadways #de2d26 & double the width)
- [x] Update description title in the info icon from High-Injury Network to High-Injury Network/High-Injury Roadways
- [x] Update the High Injury Network description in the info icon. Keep what is currently in the description, but add the following:
> More recent analysis applies a comprehensive cost value to all people involved in crashes, which has highlighted 13 segments on the HIN that have a particularly high concentration of high crash locations where Vision Zero is focusing short-term engineering, education, and enforcement initiatives. These 13 [“High-Injury Roadways”](http://austintexas.gov/page/high-injury-roadway-segments) are represented by darker, wider lines on the map.

[HIN_for_VZV.zip](https://github.com/cityofaustin/atd-data-tech/files/4727088/HIN_for_VZV.zip)

**Comment by JaceDeloney** [comment]
Added the following description to the High Injury Network info icon language:

> More recent analysis applies a comprehensive cost value to all people involved in crashes, which has highlighted 13 segments on the HIN that have a particularly high concentration of high crash locations where Vision Zero is focusing short-term engineering, education and enforcement initiatives. These 13 “High-Injury Roadways” [link to HIR page when it’s developed] are represented in [color].

**Comment by alan-deanda** [comment]
@mddilley , @JaceDeloney  the High Injury Network Vector Tiles for the Vision Zero Viewer are available [here](https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/HIN_for_VZV/VectorTileServer). Let me know if y'all need anything else.

**Comment by alan-deanda** [comment]
@JaceDeloney , @mddilley , the updated High Injury Network is saved [here](https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/High_Injury_Network_Vision_Zero_Viewer/VectorTileServer).
