### ISSUE TITLE
VZD | Create “Austin Full Purpose Jurisdiction Flag” column with type Boolean.

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#2909]
- [x] Create `austin_full_purpose` boolean field in VZD staging & prod
- [x] Await @frankhereford's lead on populating this field for the current data going backwards.
- [x] Help/support Frank in creating an automation process for new crash records moving forward within our data infrastructure. Can we use ArcGIS API to reference FPJ shape that is maintained?

**Comment by sergiogcx** [comment]
Step 1 is finished. Applied changes to both production and staging.

Here is the PR that documents the changes done to the database:
https://github.com/cityofaustin/atd-vz-data/pull/806

**Comment by johnclary** [comment]
yes, we should definitely use the Esri-hosted jurisdiction layer for this. [Here's that service](https://services.arcgis.com/0L95CJ0VTaxqcmED/ArcGIS/rest/services/BOUNDARIES_jurisdictions/FeatureServer).

**Comment by sergiogcx** [comment]
There are two PRs open:

From Frank:
https://github.com/cityofaustin/atd-vz-data/pull/820

From Sergio:
https://github.com/cityofaustin/atd-vz-data/pull/821
