### ISSUE TITLE
VZE | ETL | Update VZE displayed global filters

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#2910]
- [x] Update VZE global filter to include crashes where @sergiogcx 
 _(there may be other pages like locations that will also need this this global filter)_
`austin_full_purpose = true OR (city = 22 & lat/lon = null)`

- [ ] Inventory where this impacts ETLs to VZV or other data pipelines @mddilley 
- [ ] Update logic/filters in ETLs and whatever other place we find in data pipelines @mddilley

**Comment by sergiogcx** [comment]
I've created a new issue for this task #3072

I have also created a new PR:
https://github.com/cityofaustin/atd-vz-data/pull/830
