### ISSUE TITLE
VZD | Create two more geo jurisdiction flags and make associations on Crashes Records

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#2914]
- [ ] Create two new flags to create in staging & prod:

1. Austin Limited (LTD): 
  - Field name: `austin_LTD`
  - Data source?
2. Austin Expanded Limited (ETJ)
  - Field name: `austin_ETJ`
  - Data source?

- [ ] Using TBD data sources (hopefully maintained in ArcGIS), update values for all current records going backwards (bulk update)
- [ ] Using TBD data sources, create an automated script to make association on record creation or coordinate update.

**Question:** 
Do we have specific use cases for these polygons in analysis? This will help determine priority.

**Comment by JaceDeloney** [comment]
The team has decided to use joins. Outstanding question: Should these jurisdictions live in VZD or in ESRI?
