### ISSUE TITLE
Refinements to Officer interface

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#2921]
Notes from second session - 

### Search Table 
- [x] Remove Keyword Search
- [x] Date From
- [x] Date To
- [x] Remove Export function
- [x] Sign Up icon same as the one used on the Page Menu

### Unavailable Assignments
- [x] Change Unavailable Assignments to Filled Assignments

## My Assignments 
- [x] Create table "Today's Assignments" 
- [x] Fields same as earlier My Assignments table, except the details on this one will open to let the officer record in the assignment.
- [x] Rename "My Assignments" "Future Assignments"
- [x] "Future Assignments" details will open in a modal and not be editable.

### Calendar
- [x] Show Assignment Location only

## Assignment Details
- [x] "Start Assignment" button becomes bigger, use a triangle as the icon
- [x] Move "End Assignment" to the bottom of the page, use a square as the icon.
- [x] Remove "Team" and "Assignment Number"
- [x] Create note types: will morph into two notes with two types - 
   - "Explain why no violations were observed over a 20 minute period." -- See 
   - "Document cause for concern"
Officer will have to select one of the two options and then record note.
- [x] Change "Submit" to "Add Note"
- [x] Will need to change the Notes table below to show Type of Note.
(Jen would like to see these notes, need to make those available in the Viewer interface)
- [ ] Enlarge "Back to Assignments" button needs to be made bigger." (#2990)

**Comment by amenity** [comment]
@SurbhiBakshi - will you add an estimate to this?

**Comment by SurbhiBakshi** [comment]
@amenity - added estimate

**Comment by SurbhiBakshi** [comment]
@amenity - not too happy with the triggers buttons, Add Note button and Back to My Assignments. I am going to need some CSS help here.
