### ISSUE TITLE
Project: Community of Practice

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2927]
An effort to foster a community of technology practitioners across the City of Austin. We endeavor to create spaces for our colleagues to learn, share, and socialize around our mission to deliver excellent public services through technology. 

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://data.mobility.austin.gov/about/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
🥲

**Comment by johnclary** [comment]
💐

**Comment by mateoclarke** [comment]
🥃
