### ISSUE TITLE
Schedule meetup #1

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2929]

**Comment by mateoclarke** [comment]
Maybe we aim for consistency around last Wednesday of the month. June 24th was the day the ODD people were good with. Does that work for our team @johnclary

**Comment by johnclary** [comment]
yes, it does if it's at noon

**Comment by amenity** [comment]
@mateoclarke @johnclary — like #2930; another 📊 n' 🍩 that needs milestone and/or pipeline updates.
