### ISSUE TITLE
Test all buttons as technician

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#294]
Testing Scenarios

**MAINTENANCE WORK ORDER**
- [x] Create maintenance work order
- [x] Add locations, assets, specs, 
- [x] Enter Actuals (**Time, Material**)
- [x] Click `Submit for Review`

**SERVICE REQUEST>WORK ORDER**
- [x] Open `ISSUED` work order
- [x] Add locations, assets, specs, 
- [x] Enter Actuals (**Time, Material**)
- [x] Click `Submit for Review`

**Comment by dianamartin** [comment]
WO Need To Be Issued
>Technician see all "Non-Editable" tables

WO ISSUED 
>Technician sees all forms

**Comment by dianamartin** [comment]
Added all time and materials. No Location. 
Banner came up "This work order is not complete. Verify that a Location has been added."
Working as expected.

**Comment by dianamartin** [comment]
## Testing FINAL REVIEW as Technician
- [x] Edit - banner shows up **You cannot edit a work order that has been submitted for Final Review.**
- [x] Submit for Review - banner shows up **This work order has already been submitted for Final Review.**

**Tables**
- [x] Flex Notes (non editable)
- [x] Comments & Attachments (non editable)
- [x] Locations (non editable)
- [x] Location map (non editable)
- [x] Time & Materials (non editable)

**Comment by dianamartin** [comment]
## Adding a New Work Order
- [x] New Work Order opens ups
- [x] Instructions & Comments **(required)**
- [x] Location fields appear
- [x] Location Type **(required)**
- [x] Primary Street **(required)** (depending of Location Type selection)
Submitted and created Maintenance work order
