### ISSUE TITLE
Meeting for Feature request: TIA Folder Status Updates#2631

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#2958]
**As a TIA reviewer, I need the folder statuses to make sense, and better align with how we are using the TIA folder.**

Meeting Issue for Feature request: TIA Folder Status Updates #2631
Participants Invited: Sangeeta Jain, Nazlie Saeedi, Nadin Nader, Sreelatha Blaze Kannan
Meeting Date and time: 6/10/2020 at 11am

Purpose of Meeting: To further define and update the TIA folder status to make sure they align with the Business needs, rules and workflow desired.

Link to main issue: https://github.com/cityofaustin/atd-data-tech/issues/2631

**Comment by Nadin-Nader** [comment]
Notes from Parent card #2361:
Notes from #2631 with responses from Nazlie bolded and quoted:


From: Saeedi, Nazlie <Nazlie.Saeedi@austintexas.gov> 
Sent: Tuesday, June 9, 2020 4:30 PM
To: Nader, Nadin <Nadin.Nader@austintexas.gov>
Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>; Jain, Sangeeta <Sangeeta.Jain@austintexas.gov>
Subject: RE: TIA Folder Status Updates #2631 Questions

Hello,

Below are our responses in red.

Let us know if you have any additional questions.

Thanks,

Nazlie Saeedi, P.E.
Transportation Development Engineer – Lead (Central)
Transportation Development Services Division
Austin Transportation Department
901 S. MoPac Expressway, Building 5, Suite 300
Austin, TX  78746
(512) 974-4073
nazlie.saeedi@austintexas.gov
Transportation Development Services Division Website

*Out of an abundance of caution, the Transportation Development Services Division is working remotely. We are committed to completing reviews and projects in a timely manner and will remain available to the public and development community. Please continue to reach out to us via email (preferable) or our desk lines with any development related questions. In order to ensure health and safety of the citizens of Austin, we are moving from in-person-meeting setting to online meetings for the next few weeks.         

From: Nader, Nadin <Nadin.Nader@austintexas.gov> 
Sent: Tuesday, June 9, 2020 1:56 PM
To: Jain, Sangeeta <Sangeeta.Jain@austintexas.gov>; Saeedi, Nazlie <Nazlie.Saeedi@austintexas.gov>
Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
Subject: RE: TIA Folder Status Updates #2631 Questions
Importance: High

Hi Sangeeta and Nazlie,

Hope you both are doing well. I was reaching out again to see if you were able to answer the questions and go over the requirements?

If you have not and would like to set up a meeting to discuss this further, just let me know what day and time works for you this week.  As of right now I have available, 9-10am tomorrow 6/10/2020 , Thursday 6/11/2020, 9am-1230pm open.

Please let me know what works for you. The sooner the better as our developer is waiting for an update to continue working.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department



From: Nader, Nadin 
Sent: Friday, June 5, 2020 3:03 PM
To: Jain, Sangeeta <Sangeeta.Jain@austintexas.gov>; Saeedi, Nazlie <Nazlie.Saeedi@austintexas.gov>
Subject: TIA Folder Status Updates #2631 Questions

Sangeeta/Nazlie,

Hope you are both doing well and staying safe. I was reaching out to you regarding the TIA Folder Status Updates #2631. We were looking over this and scoping it  with Sree and came u with a few questions we needed answers to. If you would please look over them and send us the answers so we can have Sree work on this.

•	Are the fees the system inserts during folder insert providing value, or are they deleting them? 

**> No, they can be deleted**

•	At what point in the real-life TIA workflow are fees collected? How many times are fees collected? 

**> Fees must be paid before or at the time of the first TIA submittal. Once, for two fees: TIA scoping fee and TIA review fee, as they are billed together**

o	For example, many permitting processes have application fees and approval fees which are billed and paid at different times throughout the review.

Also can you please look over the requirements to see if they are correct and what you are looking for. I have pasted them below. Please add any notes you think will help or need to add.

•	At initial folder setup/creation, the status should be Pending
o	This is already happening (per Sree) 

•	After fees have been billed, the status should be Pending Payment
o	Option: Use 'Calculate Fees' attempt on Initial Intake, this would add any missing fees and create one bill for all fees on fee tab. First we'd need to make sure the system isn't adding unnecessary fees. Then folder status would update to Pending Payment **

**> Yes, we want this**

**

o	Currently, "Entered" attempt checks if the completeness check fees have been paid, and closes the attempt.

**> We don’t have a completeness check process or fees for the TIA folder**

**

•After fees have been paid, the status should be Paid. This should not require user action.
•	After the memo is approved, the status should be Approved
o	Saving 'Approved' attempt on TIA Case Manager review process currently issues the folder, and updates status to Approved & Released. 

**> After the TIA has been approved and released, we would like the folder to be removed from our task list in AMANDA**

Once I get that information, we will have a better idea of what will be needed to be done and the time frame to get this completed for you.
Thank you for your time.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please add a link to the meeting recording to this issue please?

**Comment by Nadin-Nader** [comment]
Link to meeting:

https://web.microsoftstream.com/video/1b0e3a1c-77bb-45d9-8f37-4f36b480e672
