### ISSUE TITLE
Test all buttons as requestor/viewer

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#296]
Testing Scenarios

**TRANSPORTATION ENGINEER, ACTIVE TRANS, ARTERIAL MANAGEMENT WORK ORDER**
- [x] Create maintenance work order
- [x] Add locations, assets, specs, (AS A TECHNICIAN)
- [x] Enter Actuals (**Time, Material**) (AS A TECHNICIAN)
- [x] Click `Submit for Review` (AS A TECHNICIAN)

**PUT WORK ORDER - ON HOLD**
- [x] Open `NEEDS TO BE ISSUED` work order
- [x] Put on Hold
- [x] Select Hold Reason
- [x] Remove from Hold
<br>

- [x] Open `ISSUED` work order
- [x] Put on Hold
- [x] Select Hold Reason
- [x] Remove from Hold

**ADD ATTACHMENT**
- [x] Open `NEEDS TO BE ISSUED` work order
- [x] Add attachment
<br>

- [x] Open `ISSUED` work order
- [x] Add attachment
<br>

- [x] Open `FINAL REVIEW` work order
- [x] Add attachment
<br>

- [x] Open `CANCELLED` work order
- [x] Add attachment
<br>

- [x] Open `CLOSED` work order
- [ ] Add attachment
>Can't add attachment, the menu bar is hidden

**ADD COMMENT**
- [x] Open `NEEDS TO BE ISSUED` work order
- [x] Add comment
<br>

- [x] Open `ISSUED` work order
- [x] Add comment
<br>

- [x] Open `FINAL REVIEW` work order
- [x] Add comment
<br>

- [x] Open `CANCELLED` work order
- [x] Add comment
<br>

- [x] Open `CLOSED` work order
- [ ] Add comment
>Can't add comment, the menu bar is hidden

**Comment by dianamartin** [comment]
Testing done, but "Cancelled" button is showing up twice on the Cancel page. It's weird.

**Comment by dianamartin** [comment]
## Testing on ISSUED work order
Logged in as viewer 
Opened an `Issued` WO from `My Work Orders | Created` 

Visible on **Work Order Details**
Viewer Buttons menu
- [x] Add Attachment
>new attachment form doesn't show attachments on table..I think it's because the connection is not being captured..ugh.
>@johnclary Did I rebuild this?
- [x] Add Comment

- [x] Edit Work Order
- [x] Cancel Work Order
- [x] Hold

- [x] Comments (non editable)
- [x] Attachments (non editable)
- [x] Locations (non editable)
- [x] Location map with the locations from the table (non-editable)
