### ISSUE TITLE
Update Shared Mobility Ops Home Page

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2960]
### Updates to the Shared Mobility Ops Home page

Should we keep Providers and Reports buttons?

**Summary**
As a user, I want to see high-level, aggregated summary information so that I can maintain my understanding of the current state of the City of Austin Shared Mobility program.

- [x] View number of permitted vehicles in the City of Austin
- [x] View total number of trips that have occurred in the current year
- [ ] View other summary information, tbd

**Alerts**
As a user, I want to see alerts on the home page so that I can triage my workload and focus on keeping providers in compliance with City of Austin Shared Mobility regulations.

- [x] View information on licenses and permits that are expiring soon
- [x] View information on insurance that are expiring soon
- [x] View fees/payments that are late
- [ ] View other expiration/late payment information, tbd

![Untitled presentation.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/edb0833a-8a26-4bdf-a9cc-b8bc6acb2fae)

**Comment by SurbhiBakshi** [comment]
@JaceDeloney - [here](https://atd.knack.com/smo#home/) is some work that I did for this issue, let's talk about the TBD items later this week?
