### ISSUE TITLE
Create New Role for Partners

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#2973]
We have been requested to open access to a subset of the functionality in the Shared Mobility Operations dashboard. Our third-party partners like Ride Report sometimes need information to help them compare micromobility usage in Austin. 

**Partner Role**
- [x] Create a new `Partner` role
- [x] `Partner` roles should only be able to access and view the Monthly Trips table within the Fees/Payments tab. They should not be able to add, edit, or delete any data within the Monthly Trips table. `Partner` users should be able to view all trip numbers for all providers.

More views and access for this role will be determined at a later date

**Comment by SurbhiBakshi** [comment]
- [ ] Create a new Partner role
- [ ] Create a new Shared Mobility Partner account
- [ ] Set Login permissions so Partner role can access Fees/ Payments tab 
- [ ] Set page rules so Partner account can only see Monthly Trips table within the Fee/ Payments tab.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/61178fca-d111-4064-9e16-39a746933ae3)
