### ISSUE TITLE
Click Map Bug: Adding a Parcel Instead of a Street Segment

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2980]
### Video of this bug can be viewed by city staff [here](https://web.microsoftstream.com/video/56346f6e-1526-4c69-9e5d-06a4e0327abe)

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/71cfd5a1-0d67-4336-9e4f-48001fe52fa8)

**Comment by TracyLinder** [comment]
CTM will start working on this next week. Updating to sprint 27.

**Comment by Nadin-Nader** [comment]
@TracyLinder Paloma mentioned that she doesnt know why this may be needed as they do not add Parcels to permits. Can you please reach out?

**Comment by TracyLinder** [comment]
After talking to Mike w/ CTM GIS, we've decided that this bug may not be worth the effort it would take to fix it. Users would likely need to be trying to break the map to recreate this bug. We will re-open this issue if users provide feedback that this is a true need.
