### ISSUE TITLE
Digital TLC Paperwork Demo 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#2982]
### Objective 
The DTS team was asked to set up a digital process to handle the TLC paperwork. 
In this meeting we will demo the process and provide an opportunity for your feedback.

### Participants
Nathan Brown, Emma Segura, Jennifer Watts, Adan Medina, Stephanie, Diana, John, Peggy (optional)

### Agenda

- Demo
-  Feedback
-  Outstanding questions & Action Items
 ATD Telework Procedure document needs to be converted from Word Doc to PDF
 Level of permissions for HR Staff
 Schedule for email notifications for Supervisors/Department Head (daily, weekly)
-  Next Steps

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana Notes

- Diana to go over demo
  - Show HR Forms Management page
  - Turn in Telework form
  - Show how to approve/not approve telework request form
  - Show email confirmations
  - Show Employee Details (associated forms)

## Changes
### Request Details page - via HR Form>Form Details
- [x] Add `Status`
- [x] Add `Decision Date`
- [x] Add `Reason for Denial`

### Reviewed Table - Approve Forms
- [ ] Add `Division`

### Email Notifications
- [ ] Eventually configured `Dept Head/Designee` email notification
- [x] Suspend any `Signature Required` email notifications, turn on when private view for mangers is configured
- Email submission - form submission confirmation will still be `ACTIVE`

## To Do
- [ ] Change HR banner
- [ ] Make minor changes
- [ ] Write out steps on filling out Telework Request form

**Comment by moorerst** [comment]
Reviewing the HR view
Is this the place where all forms will appear? yes if they are appropriate 
Reviewing the New Request Form
Is the Week 1 Week 2 option necessary - per Nathan they appear on the HR form would like to keep the option in place

- [ ] The ATD Procedure document is a draft. John will forward the final document that will need to be converted to PDF

- [ ] What is a good timeframe to sent email notifications to Managers/Department Heads to inform they have request that need approval - agreed on after each submission a email notification should be sent
The team was ok with one signature for acknowledgement of both COA and ATD guidelines

- [ ] Who will sign for the Department Head approval - Nathan will speak with Rob to determine who will approve these
Will Managers see all department request - lot of discussion and concern on this issue
tranparency issue
perception of fairness
concerned Managers can see all request
Per Nathan need to provide a solution for this even if it means delaying the rollout for 2 to 3 days
Will everyone have access to sign online - yes digital signature is saved as an image. Name and date is captured in electronic record when the form is submitted

- [ ] On the Review Forms Detail page need to add Decision Comment and Status
Will the approved request form need to be printed - normally a copy would be put in the personnel file but having in the system should be ok. Can be printed from the system if needed.

- [ ] What HR staff needs access to the system - per Nathan everyone on his team except Chris W
What is the next step after the employee is approved - per Nathan employee would work directly with their direct Supervisor not a HR issue after the approval is provided
Next Step

- [ ] Provide link to Request Form with instructions to Nathan for email distribution on Monday 
6/15

- [ ] Disable email notifications for Supervisor and Department Heads until transparency solution is resolved. Only employee will receive email after submission 
Temporary work flow link to Request Form will be provided in email to employees on Monday 6/15. Request will remain in backlog for 1 to 2 weeks until the transparency solution is in place.

Version 2 items for consideration

- Workflow for request that are not moving forward 
Ping Supervisor after a period of time goes by and request have not been approved (5 days)
- Add HR email address to receive email notifications send to Supervisors/Managers they will save in a designated folder (ATD.HR@austintexas.gov)
- Set up solution for Managers to only see the request for their direct reports
