### ISSUE TITLE
Epic: TIA Folder Updates: Status, Process, Info Tab

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2983]
### LaunchIT is working on these 3 features together, and this is the epic to connect them all, and to monitor overall progress. 
- Folder info tab update
- Folder status' updates
- Folder process tab updates (to include automated fees)

The future state workflow: [TIA AMANDA Folder Overview.pdf](https://github.com/cityofaustin/atd-data-tech/files/5461657/TIA.AMANDA.Folder.Overview.pdf)
.

**Comment by TracyLinder** [comment]
**Ash sent us a demo, this was my response:**

Hi Ash,

This is really great work! I do have 1 revision due to a missing requirement on our part:
-	When adding fees, be sure to include the ATD Tech Surcharge

Nate I think we should have your feedback before moving forward on this one. I also have a question for you: when the folder status updates to approved, should there be either an issue date or expiration date? 

Thanks,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
### Notes/Update
- We met with stakeholders today to demo work done on all 3 child issues
- Feedback has been incorporated and all acceptance criteria has been updated
- Next Steps: LIT will revert Dev commits, re-do work, and send us a demo

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder @Nadin-Nader  - Since the acceptance criteria changed again on 07/31/2020 , Aishwarya is working on the changes now.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Aishwarya completed the changes and Demo will be sent soon.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Submitted Demo on  08/11/2020 and approved the PickList changes to Promote to DEV. Would like to know whether all changes can be promoted to DEV?

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan, @SubhaShroff, @aishwarya2505  or @TracyLinder i do not have the email with the demo in my inbox anywhere. Can one of you send it to me please?

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Commited changes in DEV on 08/19 and submitted DEV deployment plan and tested the same in DEV Ready for UAT in DEV

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - #2632 Tracy raised a query on Folder status update "Paid" ; Aishwarya has to start working on that.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - If still having issues please send them with folderrsns to check further. thank you.

Here is the reply from Aishwarya -

Hello @TracyLinder @Nadin-Nader , I checked the mentioned folder in DEV 11895327 and the folder status was updated to "Paid" on attempt "Entered" in the Initial Intake Process.
I created another folder in DEV , RSN11895365 and tested the entire work flow for this ticket and it worked as expected.
Let me know if there's an issue in any other environment and I can always fix that for you. Thanks :)

**Comment by TracyLinder** [comment]
Just tested in DEV, folder RSN 11895406. It worked as expected. 

### Approved for TEST

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Aishwarya will be sending the TEST Deployment plan by EOD.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder I have sent this to the CM DevOps Team to deploy to TEST under TASK SCTASK0101403.

**Status:**

Waiting on CTM to deploy to TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder @aishwarya2505 This has been deployed to TEST. Ready for TEST UAT

**Status:**
Ready for TEST UAT

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have tested this in TEST (RSN: **12396019**) and found that all 3 other cards (#2631, #2632, #2634) meet the acceptance criteria

**Comment by TracyLinder** [comment]
Testing with stakeholders scheduled for 10/27

**Comment by TracyLinder** [comment]
I will meet with stakeholders tomorrow 10/30 @11:30 am to request approval to promote to prod. I also updated the ticket description with a future state workflow.

**Comment by TracyLinder** [comment]
I met with Nazlie and Sangeeta this morning about this work and they do not want this work going to production as-is. The biggest concern is that after the customer pays, the folder status will still be ‘Pending Payment’, and this could cause worry and poor customer service. They are aware that this could cause us to have to re-start the development after the V7 upgrade.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder - 
Aishwarya making a change to have the status changed to Paid as soon as the fees are paid in TIA folder

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Completed changes and Aishwarya sent Demo on  11/3/2020

**Comment by TracyLinder** [comment]
### Approved to Promote
@aishwarya2505 @Sreelatha-BlazeKannan the demo looks great as-is. No need to program around the 'entered' attempt result at this time. Thank You!

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder -
Aishwarya sent DEV Deployment Plan on 11/9/2020.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder I have sent this to the CM DevOps Team to deploy to DEV under TASK **SCTASK0104270**

## **Status:**
Waiting on CM DevOps to commit to DEV

**Comment by TracyLinder** [comment]
This was promoted to DEV today.

**Comment by TracyLinder** [comment]
### Approved to promote to Test 🎉

- We just did DEV UAT w/ stakeholders; this looks great!

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @tracy. I have sent this over to the CM Team for TEST deployment under TASK **SCTASK0105131**

## **Status:**
Waiting on CM Team to deploy to TEST

**Comment by Nadin-Nader** [comment]
@TracyLinder @Sreelatha-BlazeKannan @aishwarya2505 the CM DevOps team has deployed this to TEST.

## **Status:**
Ready for TEST UAT and stakeholder approval for PROD.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder 

## **Approved and ready for Deployment to PROD🎉🎉🎉!!**

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @Sreelatha-BlazeKannan @TracyLinder I have sent this to the DevOps CM Team for PROD deployment under **SCTASK0105644**

## **Status:**
Waiting on Promotion to PROD by the DevOps CM Team

**Comment by Nadin-Nader** [comment]
TASK SCTASK0105644 has been completed by CTM
