### ISSUE TITLE
PSM Web Acceptance Email Template

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2984]
### The system generated email that goes to the folder applicant when Web Acceptance is 'Accepted' and 'Department Comments' needs content.

**Stakeholders:**
Paloma, Kim
SME: Evelyn Powers

### Template to Implement 

Dear [Applicant First & Last Name]:  

Your internet request for a [Folder Sub-type] permit [permit number] has been accepted and is being reviewed for approval.  We have not yet issued a Permit.  You will receive another message regarding permit approval when City of Austin staff has completed its review of this request.  

Reviewer Comments (If Available): [Attempt comment text]  

If you have further questions, please reply to this message.

**Comment by TracyLinder** [comment]
This is what it looks like right now:

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/50e20011-920e-449e-93c1-9af74a85ef8c)

**Comment by Nadin-Nader** [comment]
@TracyLinder Paloma asked for you to work with Evelyn as she is SME for this.

**Comment by TracyLinder** [comment]
### Template to Implement 

Dear [Applicant First & Last Name]:  

Your internet request for a [Folder Sub-type] permit has been accepted and is being reviewed for approval.  We have not yet issued a Permit.  You will receive another message regarding permit approval when City of Austin staff has completed its review of this request.  

[Attempt comment text]  

If you have further questions, please reply to this message.

**Comment by TracyLinder** [comment]
Unisys has been updated with template info. Ready for development.

**Comment by johnclary** [comment]
@TracyLinder test it again or find your notes

**Comment by TracyLinder** [comment]
Testing: The 'Accepted' attempt email looks good. Now the 'Department Comments' email is blank.

**Comment by TracyLinder** [comment]
**Email to David:**

Hi David,

I was just testing this and there’s good and bad news. 
•	Good: The ‘Accepted’ attempt email looks good
•	Bad: The ‘Department Comments’ email is blank. (Not sure if this is new or we missed it.)

Can you work on applying the template below for Department Comments attempt on PSM please?

Dear [Applicant First & Last Name]:

Your internet request for a [Folder Sub-type] permit [permit number] is being reviewed for acceptance, and review comments are below. Your request has not yet been accepted. 

Reviewer Comments: [Attempt comment text]

If you have further questions, please reply to this message.

Thanks,

Tracy Linder

**Comment by TracyLinder** [comment]
UAT PASSED
