### ISSUE TITLE
PSM Maintenance Agreement Email Needs Updating

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#2986]
**Stakeholders:**
Paloma, Kim
SME: Evelyn Powers

### Template to Implement:
_(Implement only for 'Awaiting Update' attempt)_

Dear [Applicant First & Last Name]

Your [folder sub-type] permit request [permit #] is pending approval of the Maintenance Agreement, and your action is required. Below are comments from your reviewer, if available. 

[Attempt comment text]

Please respond to this email with any questions. 

-----

**This is what the email currently looks like:**
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/ac9568fd-e43e-44c7-b3bb-ecf259b73ecd)

**Comment by Nadin-Nader** [comment]
@TracyLinder Paloma asked for you to work with Evelyn as she is SME for this.

**Comment by TracyLinder** [comment]
### Template to Implement:
_(Implement only for 'Awaiting Update' attempt)_

Dear [Applicant First & Last Name]

Your [folder sub-type] permit request [permit #] is pending approval of the Maintenance Agreement, and your action is required. Below are comments from your reviewer, if available. 

[Attempt comment text]

Please respond to this email with any questions.

**Comment by TracyLinder** [comment]
Unisys has been updated with template info. Ready for development.

**Comment by johnclary** [comment]
@TracyLinder test it again or find your notes

**Comment by TracyLinder** [comment]
UAT PASSED
