### ISSUE TITLE
Migration Project planning work session

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#299]
- Migration schedule 
- Notify users 
- Workarounds for downtime
- Specify and assign migration tasks
- Identify which data we'll migrate and in what order - sequencing

**Comment by johnclary** [comment]
## Migration Plan

### ASAP
- Heads-up email about migration/outage

### Wednesday COB
- Data Tracker and Signs Work Orders: Set Signs/Markings work order login user permissions to only allow Sys Admin only
- SM WO System: Delete all test records

### Thursday
- Email: Starting Maintenance
- Export all data, import data, load attachments via script

### Friday:
- Test
- implement re-directs
- SM Work Order System: Add user privs back to main logins to signs
- Maintenance complete
- Delete CSRs from agreed date range (probably that day and before)

### Data Imports
- inventory_items << check if there are changes
- inventory_transactions
- work_orders_signs_markings << SPLIT IT!
- work_orders_signs_markings_attachments << SPLIT! two connections now
- work_orders_signs_markings_comments << SPLIT! two connections now
- work_orders_signs_markings_specification_actual
- work_orders_signs_markings_jobs << SPLIT!, map signs job attributes fields to signs work order fields.
- work_orders_signs_markings_time_log

**Comment by dianamartin** [comment]
**NOTIFICATION**
Email notice URL & Bookmark change "What's Happening?" 
Canned email notice (use the ROWPACT email notice) 
Video of steps 
Short steps  

**MIGRATION PREP – WEDNESDAY**
Turn off access Wednesday COB  
Make root pages of [Data Tracker Prod] and [Signs & Marking Operations] only accessible to System Admins User role 
Delete all test records  

**MIGRATION – THURSDAY**
Early next morning 
Email "Starting Maintenance" - ATD Department or list of people in Data Tracker 

Canned email notice 

 

Export tables: 

    "work_order_signs_markings" (Signs | Markings – NEED TO SPLIT) 

        (Signs | Markings – NEED TO SPLIT) (Filter by WORK_TYPE = "Markings", move Signs to new connection field) 

        (Signs | Markings – NEED TO SPLIT) (Filter by WORK_TYPE = "Signs", move Signs to new connection field) 

    "work_order_signs_markings_attachments" (Signs | Markings – NEED TO SPLIT)  

        (Signs | Markings – NEED TO SPLIT) (Filter by WORK_TYPE = "Markings", move Signs to new connection field) 

        (Signs | Markings – NEED TO SPLIT) (Filter by WORK_TYPE = "Signs", move Signs to new connection field) 

    "work_order_signs_markings_comments" (Signs | Markings – NEED TO SPLIT) 

        (Signs | Markings – NEED TO SPLIT) (Filter by WORK_TYPE = "Markings", move Signs to new connection field) 

        (Signs | Markings – NEED TO SPLIT) (Filter by WORK_TYPE = "Signs", move Signs to new connection field) 

    "work_order_signs_markings_jobs" (Markings Jobs) (Signs | Markings – NEED TO SPLIT) 

        (Signs | Markings – NEED TO SPLIT) (Filter by WORK_TYPE = "Markings", move Signs to new connection field) 

        (Signs | Markings – NEED TO SPLIT) (Filter by WORK_TYPE = "Signs", move Signs to new connection field) 

     

    "work_order_signs_markings_time_log" (Markings Time) 

    "work_order_signs_markings_spec_actual" (Markings Specs) 

    "inventory_transactions" (Marking Materials used) 

    "inventory_items" - check if there are changes (POSSIBLY)  

 

 

**MIGRATION - FRIDAY**

Testing of system, data checks 

Kati – System Admin 

Christina – System Admin 

 

Remove System Admin user role [Signs & Marking Operations] 

Email notice "MAINTENANCE COMPLETE" 

Delete CSRs from SPECIFIED DATE RANGE to AGREED UPON DATE with Signs and Markings 

 

 

[COACD for Banners]

**Comment by dianamartin** [comment]
John and I added notes and plan on creating new issues for these tasks so I'm closing this.
