### ISSUE TITLE
Implement custom styling for VZA App 2.0

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#2990]
Potential candidates for custom styling, will validate based on Officer feedback during pilot or usability testing: 
- [ ] Back to Assignments Button
- [ ] Start Assignment Button
- [ ] End Assignment Button

~- [ ] Check boxes that select multiple assignments / header checkbox to select all under a header #986 (or [code](https://www.knack.com/developer-documentation/#add-checkboxes-to-a-table))~ This would be in order to address #3081. Will create a Dev issue for custom Javascript if that's the route we determine to go in #3123.

**Comment by amenity** [comment]
This is redundant now we have #3305.
