### ISSUE TITLE
Meet with Peggy to Discuss Outstanding Questions

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2992]
Scheduled fro 6/16.

- how will we prevent staff from using their "normal" workspace?
- r.e. staff who will be returning to the office in Phase 1 at the end of June: will they all be working in their normal workspaces?
- .... ?

**Comment by dianamartin** [comment]
## Diana's Notes
- PDC - Appointment booking - Tracy/Terry P. with DSD

### Work Space Mgmt/Office Space Mgmt
- conference room reservations
- reserved desk/office to work in

#### Robin - vendor solution
- $3500 - 50 desks
- 110 desks at Barton Oaks
- Not sure how many desks we have at the other locations 
- Chairs purchase? 
- Quoted: $14k, 9 k - 300 desks - Are they are on DIR list? (3 quotes)
  - assigns space and client scheduling
  - did both? 

#### Executive Team meeting - Peggy 
- Informal requirements (John/Amenity)
- Put together a slide of what they think requirements are

- People are going to need to stay in the seat (if possible) - Scott Reedy
- AMANDA users (have to have IE as default, JAVA enabled)
- Need to have the outliers, of wiki 

#### Survey
- John has started a Re-Entry survey
- For mgrs- how many staff going back to office at each phase
  - daily work or occasional?

#### New Staff Moving
- 6 PWD executives moving over to SDD offices at Barton Oaks
- Top floor Rio Grand staff moving to Toomey

#### Conference rooms? 
- limit use
- have extraordinary reason to use a conference room

#### Hotel Spaces - Set-up (End of June/July)
- 8 to 10 hotel spaces already set-up - S.R
- Docking stations to be set-up
- Will need to have a variety
- Should users have wired mouse? Own mouse?

### Things on order
- Ordered 75 of headsets
- 25 web cams/mics
- come in next week
- 5 extra laptops/docking stations
- Aug 8th - Order cut-off
  - Processed by mid-late July

#### Cubicle Assignments
- Barton Oaks: A/B opposite days
- Hasn't heard about barriers

#### Floor plan Mapping
- Alan to start mapping locations?
  - Ask Brian C. for the Cameron floor plan
  - Cameron cubicles don't have power 

#### Policies & Process stuff
- Office Managers create that than IT re-entry

#### Meeting frequency
- Meet after Robin demo
- Meeting again

**Comment by dianamartin** [comment]
@johnclary should we close this issue? I saw you created other ones.

**Comment by amenity** [comment]
@johnclary - do you want to schedule recurring meetings about re-entry?

**Comment by johnclary** [comment]
Done. closing.
