### ISSUE TITLE
Survey division managers to assess their re-entry needs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2994]
We need to know how many staff we expect to remain TLC, and for how long. This will help us figure out how many "hotel" spaces we need to create.

**Comment by dianamartin** [comment]
@johnclary where are we on this?

**Comment by johnclary** [comment]
Based on latest discussion w/ Peggy, and the longer timeline we now have for re-entry, let's postpone this for now.

In the meantime, we are going to purchase Robin software for desk reservations, and configure up to 50 workspaces for hoteling. Let's see how that goes, and determine if we need additional info from managers.

Closing.
