### ISSUE TITLE
Evaluate Customer Reservation System

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2996]
We need to evaluate a customer appt/reservation system so that PDC customers can schedule appointments with ROW staff. DSD is moving forward with [TimeTrade](https://www.timetrade.com/). Our first step is to evaluate that system.

**Comment by TracyLinder** [comment]
@johnclary can you please clarify for me: Will TimeTrade be used by the public to schedule time with ATD staff (per the epic description), or will it be used by PDC staff to schedule time with ROW (per this issue's description)?

**Comment by johnclary** [comment]
Used by the public to schedule time with ATD staff. Sorry about that; I updated the description.

**Comment by johnclary** [comment]
@TracyLinder can this be closed? Do we need to loop-in Upal's group?
