### ISSUE TITLE
[TLC Forms] Reduce columns on main table

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2998]
[This table ](https://atd.knack.com/hr#forms/view-form-details/5ee0fe597e18a50016062565/) has a lot of columns, causing side-scrolling on smaller screens. 

Remove:
- Employee Signature
- Supr/Mgr Signature
- Dept Head Signature
- Decision Date
- Not Approved

![Screen Shot 2020-06-12 at 7.10.37 AM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/055e65fe-ae9c-488c-9b09-44a50b25744d)

**Comment by dianamartin** [comment]
@johnclary - Done
![image](https://user-images.githubusercontent.com/21112975/84502209-888c3180-ac7d-11ea-9525-ca3fe1e2ff15.png)
