### ISSUE TITLE
[TLC Request Form] Prompt employee to confirm any "take-home equipment"

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#2999]
When submitting the TLC form, the user should be prompted to confirm that they have logged any take-home equipment using [this form](https://atd.knack.com/dts#equipment/).

This radio button yes/no placed in the "Telework Access" section of the TLC request form.

**Description**
During the COVID-19 response, employees are allowed to take home office equipment with approval from their supervisor.

**Options**
- "I need to take office equipment home and I have logged this information in the [take-home equipment tracker](https://atd.knack.com/dts#equipment/).
- "I do not need to take home any office equipment.

**Comment by johnclary** [comment]
@dianamartin @moorerst can we include this in the MVP release, please?

**Comment by dianamartin** [comment]
@clary - done 
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/f1a1b7@jc3-19f9-4eff-9545-49e04f7b0b85)

**Comment by johnclary** [comment]
thanks :)
