### ISSUE TITLE
Dry Run of Data Migration

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#300]

**Comment by johnclary** [comment]
Started in this app:
https://builder.knack.com/atd/signs-and-markings-operations--copy-for-migration-test-run-11-july-2019

Will continue updating my notes here.

## Misc TODO

- add an "imported from data tracker" field for tracking old ones?
- look at if/how/when text formulas populate after import. example: ATD_WORK_ORDER_ID on attachments

## Import/Export Mappings

### Exports

#### inventory_transactions

#### work_orders_signs_markings (Split to two)

- filter 1 by signs connection
- filter 2 by markings connection

#### work_orders_signs_markings_attachments << SPLIT! two connections now

- filter 1 by signs connection
- filter 2 by markings connection

#### work_orders_signs_markings_comments << SPLIT! two connections now

#### work_orders_signs_markings_specification_actual

#### work_orders_signs_markings_jobs << SPLIT!, map signs job attributes fields to signs work order fields.

#### work_orders_signs_markings_time_log

## Imports

### work_orders_markings

#### QA

- record count
- connection-mapped fields are complete
- check work order ID generation

#### Field map
- CREATED_BY : CREATED_BY>Name
- MODIFIED_BY : MODIFIED_BY>Name
- ID_GEN_* : don't include any
- WORK_SUB_TYPE : TODO: double check this, looks ok
- WORK_GROUPS_REQUIRED : TODO: double check this, looks ok
- MAXIMO_ID : Don't incluide, delete
- STREET_SEGMENTS : TODO!
- COUNT_STREET_SEGMENTS : don't include
- PRIMARY_STREET_NAME : PRIMARY_STREET_NAME>STREET_NAME
- CROSST_ST_1_NAME : CROSS_ST_1_NAME>STREET_NAME
- CROSS_ST_2_NAME : CROSS_ST_2_NAME>STREET_NAME
- LOCATION_NAME_INTERSECTION : don't include
- LOCATION_NAME_SECTION_OF_ROAD : don't include
- LOCATION_NAME_SPECIFIC_LOCATION : don't include
- LOCATION_NAME : don't include
- SUM_PLANS_ATTACHED : don't include
- SR_NUMBER : TODO: map to connection??
- COUNT_JOBS : don't include
- SUM_ISSUED : don't include
- SUM_COMPLETED : don't include
- SUM_CANCELLED : don't include
- ALL_ISSUED : don't include
- INCOMPLETE_JOBS : don't include
- WORK_ORDER_STATUS : TODO? LET AUTOPOPULATE? Probably
- ISSUED_TO_JOB_TRANSLATOR : ISSUED_TO_JOB_TRANSLATOR>Name  TOOD: how and why does this exist?
- PROJECTED_2_WEEK_DATE : don't include
- PROJECTED_30_DAYS_DATE : don't include
- PROJECTED_60_DAYS_DATE : don't include
- PROJECTED_90_DAYS_DATE : don't include
- work_orders_signs_markings_attachment: wait until attachment import
- Attachment Status: don't include
- SUM_RPM_ACTIVE_ONLY: don't include
- ACTIVE_WO_NO_RPMS: don't include
- RPM_JOBS_ONLY: don't include
- csr_signs_issue: TODO: new connection, right? wait until attachment import?

### work_orders_signs

#### QA
- see markings

#### Note
- SEE ABOVE NOTES FOR MARKINGS AS WELL
- WORK_SUB_TYPE : TODO: delete this field
- WORK_GROUPS_REQUIRED : TODO: delete this field
- HAS__SR_NUMBER : TODO: research
- SR_NUMBER : TODO: research 
- SBO_COMPLETED_DATE : TODO: delete this
- ISSUED_TO_JOB_TRANSLATOR : TODO : delete this
- SUM_RPM_ACTIVE_ONLY : TODO: delete / don't include
- ACTIVE_WO_NO_RPMS : TODO: delete / don't include
- RPM_JOBS_ONLY : TODO: delete / don't include

### signs_signs_attachments

- ATTACHMENT_ID : need to map to new field, check with sergio on script
- ATTACHMENT:URL : TODO: most likely don't include
- ATTACHMENT : don't include
- CREATED_BY
- MODIFIED_BY
- work_orders_marking : work_orders_sign>ATD_WORK_ORDER_ID !! NOTE < Not a typo! inmport date has work_order_markings source column
- ATD_WORK_ORDER_ID : don't include
- PLANS_ATTACHMENT : don't include
- REG_ATTACHMENT : don't include
- WORK_TYPE : don't include
- WORK ORDER STATUS : don't include
- PRINTED DATE : don't include
- Requested : TODO: no field available?
