### ISSUE TITLE
Add Expiration Date to Add a New Permit form

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3005]
Right now, the Shared Mobility Ops dashboard assumed a sixth month span for permits. This isn't always the case. We need to allow users to manually set the expiration date for permits, as well as allow for this date to be edited. 

- [x] Add Expiration Date to Add a New Permit form
- [x] Allow Expiration Date to be edited

**Comment by SurbhiBakshi** [comment]
Add an Expiration Date (not automatically calculated based on Start Date) 
- [ ] Add New Permit
- [ ] Active Permits Table
- [ ] Permit Details related to Active Permit Table
- [ ] Edit Permit related to Active Permit Table
- [ ] Expired Permit Table
- [ ] Permit Details related to Expired Permit Table
- [ ] Edit Permit related to Expired Permit Table
