### ISSUE TITLE
TIA Module: Define What 'Done' Looks Like

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3006]
### What is our definition of done for this project?
- [ ] Create a checklist
- [ ]  Review w/ project team
- [ ] Iterate as needed
- [ ] Finalize checklist
- [ ] Create resulting issues/action items

**Comment by dianamartin** [comment]
We can go over the issues that are in the `Review QA` pipeline, once users get into the system we can `Close` those feature issues.

**Comment by johnclary** [comment]
@TracyLinder add to potential agenda item to product retreat

**Comment by ChrispinP** [comment]
@TracyLinder do we have a rough draft guideline for this ready yet for our upcoming Retreat?
