### ISSUE TITLE
TIA Module: Usability Testing Plan

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3008]
- [x] Create draft plan w/ specific test cases (tasks) 
  - [TIA Usability Testing Plan](https://docs.google.com/document/d/1pPKrtku94KCSmelghY9RIgAOFWvacwbLgjOPIanO7yU/edit#)
  - [TIA Usability Testing - Quantitative Metrics](https://docs.google.com/spreadsheets/d/1t7SZ9XFMw8PsBcKRpmMFPiEuqG1lIvGY3EEi0XLio5U/edit#gid=0)
- [x] Review plan w/ DTS project team (Diana, Surbhi)
- [ ] Iterate as needed & finalize

**Comment by TracyLinder** [comment]
Diana & Tracy will be working on this on 7/1 @ 1pm.

**Comment by dianamartin** [comment]
@TracyLinder I added the links to the plan and the metrics spreadsheet
