### ISSUE TITLE
Create office floor plans

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3009]

**Comment by johnclary** [comment]
@alan-deanda just a heads-up that this is probably coming your way. Nothing needed from you just yet. But [here's the epic](https://app.zenhub.com/workspace/o/cityofaustin/atd-data-tech/issues/3007) for some context.

**Comment by dianamartin** [comment]
@johnclary we got floor plan from Gilda for Barton Oaks. We need to reach out to Brian C. on the Cameron floor plans.

**Comment by johnclary** [comment]
We got these from Gilda. See [https://app.zenhub.com/workspace/o/cityofaustin/atd-data-tech/issues/3322](https://app.zenhub.com/workspace/o/cityofaustin/atd-data-tech/issues/3322)
