### ISSUE TITLE
Identify software solution for desk reservations

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3011]
We need a software service which allows you to reserve an office workspace (.e.g a desk, a cubicle, etc.) online, ideally using a visual map of the office.

I've looked at websites for roughly 15 products in this vertical. Here's what caught my eye:

### Reservation-Oriented
- [Robin](https://robinpowered.com/) 
- [Teem](https://www.teem.com/)
- [Roomzilla](https://www.roomzilla.net/)

### Floor-plan oriented
- [DeskRadar](https://www.deskradar.com)
- [Staffmap](https://staffmap.com/)
- [Floorplanmapper](http://www.floorplanmapper.com/#features)

### O365 Ecosystem
- [AskCody](https://www.askcody.com/pricing) (O365 Plugin)

**Comment by johnclary** [comment]
I've looked at 15 or so websites, and used trial accounts on 3. [Robin](https://robinpowered.com/) is my clear favorite. I'll be setting up a demo for Peggy, @amenity , @dianamartin and @SurbhiBakshi.

**Comment by dianamartin** [comment]
It looks pretty slick

**Comment by johnclary** [comment]
R.e. pricing, we are evaluating at the "Pro" tier given our need for hot-desking/hoteling.
https://robinpowered.com/pricing/

**Comment by johnclary** [comment]
Based on evaluations and demos we would like to go with Robin, pending a quote that meets our budget expectations and is comparable to competing solutions.
