### ISSUE TITLE
Meeting: Digital TLC Paperwork Refinements

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3012]
### Objective 
Discuss additional functionality for TLC app
### Participants
Stephanie, Diana, John, Amenity
### Agenda
Review additional functionality
•	Workflow for request that are not moving forward
Ping Supervisor after a period of time goes by and request have not been approved (5 days)
•	Add HR email address to receive email notifications sent to Supervisors/Managers. They will save in a designated folder (ATD.HR@austintexas.gov)
•	Set up solution for Managers to only see the request for their direct reports

- Configure name to auto populate on request form based on login credentials 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Email: Approval
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/0c5ab376-eff6-4eea-8392-f5be45144b78)

**Comment by moorerst** [comment]
@dianamartin my question was should the employee complete the Equipment Checkout Form after they have been approved for telework? Maybe that link is included in the Approval email like the Remote Access. We can discuss in the meeting tomorrow.

**Comment by moorerst** [comment]
We did not cover these items in the previous meeting. The focus was on immediate updates for release. Rescheduling for June 24th.

**Comment by dianamartin** [comment]
## Diana's Note

### My Employees
- Employees connected to Supervisor
  - Custom

###

**Comment by moorerst** [comment]
Testing the modifications for Supervisors to see and approve only the Telework Request for their direct reports.
