### ISSUE TITLE
TIA Case Management: Batch Field Update on Mitigation Fee Status

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3014]

**Comment by TracyLinder** [comment]
- Putting this in Needs Scoping until we discuss mitigations.

**Comment by ChrispinP** [comment]
Mitigation Fee Status applies to the entire case now and can change between yes and no depending if all mitigation fees have been paid.

complete

**Comment by ChrispinP** [comment]
no further issues, closing
