### ISSUE TITLE
Mitigations: Advanced Search Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3015]

**Comment by TracyLinder** [comment]
- Putting this in Needs Scoping until we discuss mitigations.

**Comment by ChrispinP** [comment]
I took the liberty to update this page to query most of the appropriate fields and updated the search results table. We need to do some requirements gathering and see what else needs to be done so that this is a successful feature.

@TracyLinder we should discuss this with stakeholders during our next meeting

**Comment by TracyLinder** [comment]
@ChrispinP looks good. Will you please remove both pro rata share fields from the search form, and add the fee expiration date. I think stakeholders might want to look at fees that expire in the near future.

**Comment by ChrispinP** [comment]
updated TIA Mitigations Directory page with mitigation fields to search by and mapping information such as street name and segment ID added. Updated Search table fields and display rules.

Currently cases are sorted alphabetically by case.

Ready for review

**Comment by TracyLinder** [comment]
@ChrispinP 

- [ ] Add search field: Case Type
- [ ] Results Header Format: [Project Name] | [Case ID]

**Comment by ChrispinP** [comment]
Added Case Type to searchable fields and updated text formula for the Header display.

Unable to create value links for Headers (Groupings) or for non-parent record fields (i.e. Mitigation fields). So I did some witchcraft, created short text field for the parent Request object that is set by default and I use that field to link the Mitigation Details Page with some link text.

Ready to review

**Comment by TracyLinder** [comment]
Let's review this at the next project meeting 3/29/21.

**Comment by TracyLinder** [comment]
Looks great!
