### ISSUE TITLE
TIA Mitigations: Stand-Alone Mitigations

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3016]

**Comment by TracyLinder** [comment]
This one needs a lot more analysis.

**Comment by TracyLinder** [comment]
- Putting this in Needs Scoping until we discuss mitigations.

**Comment by ChrispinP** [comment]
I am assuming this would be to have Mitigations created for something other than the TIA Request or the ability to add multiple existing or new mitigations to a case. We should confirm if this is still a need.

**Comment by TracyLinder** [comment]
**Not MVP**

Specific Scenarios of this happening? 
- Mitigations must be tied to a development, so they're not really stand-alone. 

Closing this out; will work on it if a need presents itself.
