### ISSUE TITLE
Feature request: Have logged in user populate "Requested Employee Name" for Telework Request Form

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3017]
## As a requester I want for my logged in account name to populate the Telework Request form so I don't have to pick my name from a long drop down list. 

```
$(document).on("knack-view-render.view_32", function(event, page) {
    // Add Time Form: Set "Employee Name" to logged in user name
  var attrs = Knack.getUserAttributes();
  console.log(attrs)
  $('#view_32-field_105').val(attrs.id);
  $('#view_32-field_105').trigger("liszt:updated");
})
```

#### Fields to change
`view_32` to `view_94`
`field_105` to `field_147`

**Comment by johnclary** [comment]
@dianamartin thanks for the helpful documentation. all set! cc @moorerst

**Comment by dianamartin** [comment]
We tested and released the TLC form to HR to distribute
