### ISSUE TITLE
Refinements from VZA Officer Workflow Test

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#3021]

**Comment by SurbhiBakshi** [comment]
This is looking so great, @SurbhiBakshi 👏 

- Overall everything worked as expected
- When I was testing on Friday afternoon, I encountered some performance issues — blank pages, taking a long time to load when switching between tabs — but seems fine Sunday night. 

Page-specific notes: 
### [Sign Up](https://atd.knack.com/vza#sign-up/)
- [ ]  Make "Shift" a radio button
- [ ]  Date range  dropdowns → Two calendar fields, "From" and "To" that default to "Today" and (blank)

### [My Assignments](https://atd.knack.com/vza#my-assignments/)
*Today's Assignments*
- Folder icon... seems strange but I have no better suggestions... 🙃

*Future Assignments*
- [ ] Remove "Remove From My Assignments" column title and replace "X" in cell with "Remove"
- [ ] Remove availability of "Assigned Officer" filter in table

*Remove Assignment modal*
- Can we hyperlink to the cancellation policy in the modal? If not, let's add a link on the My Assignments page somewhere. 

*Calendar*
- [ ] Remove "____ per page" drop down

### Current Assignment
- Need to [tweak CSS](https://github.com/cityofaustin/atd-data-tech/issues/2990), but buttons and notifications work well
- "Current Assignment" won't make sense if they are looking at a past or future shift; can the breadcrumb be the date and time 
![Screen_Shot_2020-06-14_at_11 58 18_PM](https://user-images.githubusercontent.com/1463708/84621334-e13b1480-ae9f-11ea-9c4a-a0d4329dfa97.png)
    If this is not doable, let's just use "Assignment"
- Does the user need to see the "Status" field? "Future" is confusing. 
- Not sure about the start/stop workflow... Ideas:
    - "Start" and "End" buttons are next to each other at the top of the page.
    - Show a "Start Time" and "End Time" field, these are populated when the respective button is clicked?
   - Buttons could even go in the table itself:
![Screen Shot 2020-06-15 at 12 10 48 AM](https://user-images.githubusercontent.com/1463708/84621378-f9ab2f00-ae9f-11ea-8e99-fc86a88cea8b.png)

**Add Notes**
- [ ]  Update Add Notes text:
    During your shift, please add notes in the following situations:
    - **No Violation Observed** - to explain any period over 20 minutes you do not record violations in Brazos, e.g. "Stopped to get gas" or "Rainstorm — no one out"
    - **Cause for Concern** - to report a dangerous conditions, e.g. "Many pedestrians crossing mid-block on Cesar Chavez between Comal and Chicon"

**Notes**
- Timestamp is one hour fast
- Add "Delete" link/button in Edit Note modal
- I don't think we need the "Back to My Assignments" link at the bottom of the page anymore.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/8dd8e7cf-47a1-4356-9685-1763439503a3)

**Comment by SurbhiBakshi** [comment]
The Assigned Officer filter is unexpected/ not intentional. The filter should only show fields used in the table, since there is no field for Assigned Officer, I am not sure why that is showing up. Going to remove the Filter function, and keep only the Keyword Search. Let's see if the officers ask for a Filter in User testing. 


![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/ed0dd2b6-51
bd-4c15-b840-a00b9b606a3d)

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/e0cc6800-f183-40af-8859-2adb304e0a4a)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/80bc0712-7eea-41ee-8fd9-bba153041f22)

Think this remark is for the Future Assignments table, and not the calendar. I removed the function.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/647bcd9c-f9ad-40c1-8f4d-173cafc7d1a8)

What should I rename the Field name?

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/a1313d79-3250-497c-a87d-326cceb78480)

I have incorporated

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5eb243a6-6238-4035-a1f5-dd8a70dc2c41)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/c88e195d-32a7-4d22-b865-0aeafcc22468)

**Comment by SurbhiBakshi** [comment]
[Uploading... image.png ]

**Comment by SurbhiBakshi** [comment]
Notes

Timestamp is one hour fast
Add "Delete" link/button in Edit Note modal
I don't think we need the "Back to My Assignments" link at the bottom of the page anymore.

**Comment by amenity** [comment]
Updates post discussions w/ @SurbhiBakshi:
- Going with a trashcan icon in the "Remove" column instead of an "X"
![image](https://user-images.githubusercontent.com/1463708/84830781-c11a6b00-afef-11ea-9613-f18e5f8de917.png)
- Still trying to figure out "Status"... It is helpful in that it can remove the "Completed" shifts from "Today's Assignments" list, but I am concerned that it will be confusing since the status doesn't change automatically based on time, it has to be changed by the officers. This could lead to a few weird situations Surbhi and I are working through. 
- @johnclary @dianamartin - any tips on getting the timestamp on CST? 
- I didn't realize "Back to My Assignments" is built in... probably b/c back in the day we talked about making in a button. :P Let's just leave it as is for now.

**Comment by amenity** [comment]
@SurbhiBakshi - I realize one of the things that was having the status field on the details page show as "Future" or "Completed" while the breadcrumb said "Current Assignment" was throwing me off. Now that it's "Assignment Details" I think showing status is helpful, especially if we are going to use the status to pull assignments from one table to the other on the "My Assignments" page. 

Let's discuss the "Today's Assignments" table in "person" tomorrow.

**Comment by dianamartin** [comment]
@amenity @SurbhiBakshi the timestamp isn't being collected on the back end? I thought it was automatically set to CST.

**Comment by SurbhiBakshi** [comment]
@amenity @dianamartin figured out the time stamp today morning, it was set to Eastern Time. 
Guess that is the default.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/9632dde7-7882-40bf-b1b1-c3f54f2fa6eb)
