### ISSUE TITLE
Project: COVID-19 Time Tracking

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3041]
We created an application module to to help City of Austin Transportation Department staff track daily time being spent responding to COVID-19. 

To address this need, we created a Knack-based tool that allows for the following:
- Staff to enter their time
- Managers to approve submitted time
- ATD to automate the COVID-19 Daily Log Report

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/03719cf8-51b4-49ec-bec8-76e770ea59b0)

**Comment by JaceDeloney** [comment]
**Status Update**
Over the past month, we have been meeting with citywide HR representatives on the potential to use the COVID-19 Tracking App for all city employees. We have demoed the app, discussed potential changes, and provided timing expectations if another department is interested in adopting this tool. We have not heard back from any new departments at this time.

**Comment by johnclary** [comment]
@amenity @moorerst I'm closing this out. We did it!
