### ISSUE TITLE
Meet with Tracy re valet licensing/permitting in AMANDA

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3043]
Schedule time for Surbhi and Jace to meet with Tracy to review valet permitting UX in AMANDA. At our previous sprint review, Mary and Andrea mentioned that they are interested in setting up licensing/permitting in the Shared Mobility Ops dashboard to look similar to the valet permitting in AMANDA. 

Record takeaways in this issue.

**Comment by SurbhiBakshi** [comment]
Notes - 
1. License record is for operator 
2. Permit (called a license, but essentially a permit) is issued in the name of the business, and applies to a location.
3. Typically, an operator applies for a permit, rarely a business will apply for a permit.
4. Parent record is the license - issued to operator
5.Child records are the permit - issued to the business name, specific to a location.
6. In an ideal world, the expiration date of the license would relate to the permit expiration date.
7. Typically, operators will renew all their permits at the same time, will not get a whole year out of the new one, at this point, all permits will have the same expiration date -out by a year.
6. Tracy recommends we look at simplifying permit renewal process, so all permit scan be renewed at the same time, and  permit analysts don't have to do it one by one.
