### ISSUE TITLE
Dev - OSE Status Bug

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3047]
See Epic description for the info.

**Comment by Nadin-Nader** [comment]
Successful meeting/Demo with Maria, Kaarthy, Robert and Deb to show that the status of the RW SE folder doesnt go to Pending Payment anymore when copied. It also did not pick up the fee that was on the original. Maria was happy about it.

Next Steps
Robert will send to CM Team to promote the changes
Maria will UAT
Should be in PROD by end of week if UAT Bandwidth is open (Maria said it should be)

**Comment by TracyLinder** [comment]
**Status:** See parent issue.

**Comment by Nadin-Nader** [comment]
@TracyLinder @licarir I have Tested this on DEV and the folder does not go into a Pending Payment status when copied. It goes to a Pending as it should.

Next Step: Move to TEST

**Comment by licarir** [comment]
@TracyLinder @Nadin-Nader This has made it to Test. Please UAT and let me know if it is ready for PROD. Thank you.

**Comment by TracyLinder** [comment]
@licarir @Nadin-Nader 
Robert, thanks for letting us know this is ready for test. Since this issue/ticket was meant to capture Robert's development work, I'm going to move it to Ready to Deploy, and leave it on Sprint 28 so it will show work completed for the sprint the work was done in. 

Hopefully one of us will get this tested soon.

**Comment by TracyLinder** [comment]
@Nadin-Nader @licarir 
I tested this in TEST Folder RSN 12389407
It looks great, please move to prod. 

I'll create a DevOps ticket for the promote, and close this ticket. Thanks!

**Comment by licarir** [comment]
@TracyLinder @Nadin-Nader Thank you for testing this and getting it promoted. Good to have an item checked off the board!
