### ISSUE TITLE
Implement Damage Reports reports in Data Tracker

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3048]

**Comment by dianamartin** [comment]
Fields from Scott's spreadsheet: 

- `Incident Date` - every occurrence of an incident
- 7122 `Controllers, Cabinets, CCTV, Electronics`
- 7127 `Electrical/Lighting`
- 7145 `Fiber, signal cable, guy wire`
- 7148 `Poles, Mast Arms, Ped Poles`
- 7155 `Pull Boxes, svc boxes, maintenance holes`
- `Knockdown Equipment Costs`: Sum of all equipment types

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/8dfcb379-cacc-4444-bb51-cae6a6f17d92)

**Comment by dianamartin** [comment]
Talking to Scott about the "Annual Equipment Costs for Knockdowns"
- Referencing Signal Work Down
- Damage Report - linked to Work Orders
- Look at Inventory Items to find the items
- Evaluate all costs from work order 
- `Incident Date` - if knockdown the pole, if foundation is damaged. 3 week to 1 month that damage occurred
  - Date of knockdown

THINGS IN WORK ORDER MOST IMPORTANT
- References `Action Taken` 
- Inventory Items

**Comment by dianamartin** [comment]
Talked to Scott and we modified the existing Damage Reports so they are more useful. 
- [x] Created an `Advanced Search Damage Reports` page so that he and his team can filter easily for things they need.
