### ISSUE TITLE
Nate's OSE  #2662 OSE Info Tab Clean Up Analysis

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3050]
### As a OSE reviewer, I need the infos removed that are not useful to the workflow.
**This is for the Analysis and notes gathering for #2662 OSE Info Tab Clean Up

**StakeHolder:**
Maria Alonso

**Comment by Nadin-Nader** [comment]
Maria will send a spreadsheet that shows which infos to remove.
Infos will be the same across all work-types for the Street Event Subtype of RW
Robert will need to know which subtypes to exclude

Maria sent the initial list of info that need to be cleaned up but the spreadsheet has extra tabs on it with notes that may note be associated with the request.
The info tab list also has questions and comments in the Notes columns (along with who needs to be deleted) that we will need clarification on.

Next Step

Schedule clarification meeting with Maria
Mark the infos properly with what needs to happen
Delete the infos ourselves or give to the Jets. Either way it need to go through DevOps

**Comment by Nadin-Nader** [comment]
Meeting Scheduled for 6/23/2020 at 1130am

**Comment by TracyLinder** [comment]
@Nadin-Nader will update this today, and determine if it needs to be assigned to a dev team, or if he can do it himself.

**Comment by Nadin-Nader** [comment]
@TracyLinder  I have looked over the info list and determined that this will need to go to one of our Dev teams for completion. There are a little over 50 changes to be made to the infos. Changes such as making some required and removing infos. The majority is removing infos. They also have a couple of questions for the Developers for some of the infos which may require a small meeting to iron it out.

[https://app.zenhub.com/files/140626918/8de0f188-fdbd-4447-a54b-ad361308c674/download](https://app.zenhub.com/files/140626918/8de0f188-fdbd-4447-a54b-ad361308c674/download)
