### ISSUE TITLE
Requirements Gathering Meeting - OSE Block Party

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3052]
Nate is meeting w/ Maria on 6/29

**Comment by Nadin-Nader** [comment]
From the meeting it looks like the requirements that we have so far may be enough for LIT to start researching and working on this.

When the work Type Neighborhood (NPH) is used on the RW, SE folder and the reviewer Accepts/Approves, three new processes should be added. 72014 APD Review, 50040 Fire Review, 72008 Trash and Recycling Review.
Once Accepted or Approved, The RW, SE Folder with NPH Work Type should show up in the OSE office of APD tasklist. (This Process is currently being done manually).
The new processes should make their workflow and the folder to function the same as the RW, SE folder when they receive the folder and accept/approve.
Waiting on Sree to look and verify that it is enough info to start.

**Comment by Nadin-Nader** [comment]
Sree got back and said that this is do able but needed to know if this was applicable to Web Applicants or if they can use the one process that is shared "Event Intake". If not then the Web Acceptance process would have to be added and adjusted to others. Sree will work on this and will get back to us if anything on #1709.

New acceptance criteria summary has been added to #1709:

Description Of User's Issue
Add 3 default folder processes. The processes should insert when an attempt result of 'Accepted' is saved on the Event Intake folder process.

Acceptance Criteria

When the work Type Neighborhood (NPH) is used on the RW, SE folder and the reviewer Accepts/Approves on Event Intake process, three new processes should be added. 72014 APD Review, 50040 Fire Review, 72008 Trash and Recycling Review.
The 3 processes should be assigned to the correct groups; APD Review, Trash and Recycling Review, Fire Review
The new processes should make their workflow and the folder to function the same as the RW, SE folder when they receive the folder and accept/approve.
Next Steps

LIT Development
@TracyLinder Closing meeting
