### ISSUE TITLE
Healthy Streets GIS Support

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#3055]
This issue collects broad support for ongoing efforts for upcoming Healthy Streets, including creating, publishing, and analyzing data to help with the planning phase and eventually presenting options to the public.

**Comment by alan-deanda** [comment]
Requested app to collect feedback on top candidates for Healthy Streets is now live. The link to the app will be shared by PIO. Moving this to Ready to Deploy until it's published.

**Comment by johnclary** [comment]
Comment period will end this week.

**Comment by alan-deanda** [comment]
Comment period for Batch 2 is now closed. Batch 2 will be finalized and announced next week.

**Comment by alan-deanda** [comment]
Batch 2 has been announced. I will discuss options for sharing the routes on AGOL with the team this week.

**Comment by alan-deanda** [comment]
Batch 3 has been integrated into the [Review Current Healthy Streets app.](https://austin.maps.arcgis.com/apps/CrowdsourcePolling/index.html?appid=87a64b5983e84cb5a84b9628d84f122d) I'll be closing this issue because it mostly covers batch 2, and GIS support for it is completed. I"ll open a new one for Healthy Streets Batch 3
