### ISSUE TITLE
Move DB Object From Dev to Test & Prod

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3058]

**Comment by Sreelatha-BlazeKannan** [comment]
Sent the PROD Move request on 06/18/2020 to move the View from TEST to PROD

**Comment by Nadin-Nader** [comment]
SCTASK0075453 was created for this and is assigned to AMANDA_SUPP. The CM Team will deploy today by 530pm

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder 
Got a message from Trello saying:

Martin Aponte moved the card #1893 - EX & DS Permit Template Update - PROD View Move Request to Done on DevOps CM Team 
Reply via email 

I will go ahead and close the TASK if hasnt done so already and then send the new task for the reports to Tango to deploy

**Comment by Nadin-Nader** [comment]
Martin has closed the TASK. I will close this issue and create the task for the reports to be deployed to DEV TEST and PROD.
