### ISSUE TITLE
Project: AMANDA v7 Upgrade

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3068]
We're supporting the citywide upgrade to version 7 of our case managements software, AMANDA.

## Background & Context

- DSD hired project manager (Tom C.), reports to Teri, is managing the upgrade for all departments
- v7 upgrade kicked off two weeks ago

**Project Timeline Targets:**

- Nov. 30 Setup all users accounts for testing, IT testing.
- Dec. 4 Perform basic test on the permissions
- Dec. 7 Begin User Acceptance Testing (UAT).
- Jan. 15 Complete UAT.
- Feb. 12 Complete training.
- Feb. 13 Perform system migration.
- Feb. 16 System goes live.

## Nearterm todo's:

- take screen recording to capture all of the ATD AMANDA workflows.
- Tracy is assigned to three or four. Mooney, Paloma, Kim, Maria A. also have a few dozen
- two weeks notice, wanted by 6/19, ATD is aiming for 6/26; will be hard to meet that deadline
- need to find someone (prob Nazli) to join from TDS

[Link to project overview deck](https://cityofaustin.sharepoint.com/:p:/r/sites/AmandaPOVideoExchange/_layouts/15/WopiFrame2.aspx?sourcedoc=%7Bf68d798c-089a-4109-8f29-cd46d6148eaa%7D&action=edit)

![Amanda7-permit](https://user-images.githubusercontent.com/14793120/106366845-2cf1df80-6304-11eb-899a-51e18fedc3ca.png)

**Comment by johnclary** [comment]
@TracyLinder added an image and an "in a nutshell" line so that this looks good on the website. It's a "Featured Project" now. Please add a status update here.

**Comment by TracyLinder** [comment]
### Update

The V7 upgrade timeline has been extended.
![Screen Shot 2022-04-12 at 2.42.08 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/1429e70c-4b01-46b5-bb95-3582c2386260)

**Comment by TracyLinder** [comment]
### Status June 24, 2022

**We are currently** performing end-to-end user acceptance testing on V7 test. We are near completion, having finished testing on 16 of the 23 major workflows ATD is responsible for.

**Upcoming Dates:**
- UAT Ends: July 11
- System goes down for the migration: Friday July 29 - Monday August 1 at 8am
