### ISSUE TITLE
Update Amenity's phone number in automated confirmation emails

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3071]
![Screen Shot 2020-06-18 at 11 30 29 AM](https://user-images.githubusercontent.com/1463708/85047245-29d02780-b157-11ea-9e55-7859352fedc1.png)
If this could be changed to my cell that would be rad. :)

**Comment by amenity** [comment]
I believe it would make sense to do this at the same time: https://github.com/cityofaustin/atd-data-tech/issues/3086

**Comment by amenity** [comment]
@johnclary @dianamartin @SurbhiBakshi will we still need to have everyone's numbers on this email with the new Service Desk set up? 

Don't suppose we could do some magic rollover-to-whoever-is-on-shift business, could we?

**Comment by dianamartin** [comment]
@amenity we can change the email content, but we'll have to talk about taking everyone's contact info down if that's the direction we're going.

**Comment by amenity** [comment]
My phone forwarding is working great. No need for this.
