### ISSUE TITLE
Explore other filter/search options for the "Available Assignments" table

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3079]
Pat had feedback on the [search filters](https://docs.google.com/document/d/1PBtoOPWAwLMduMZs9jJhMu-YX213UgxbOuNnVBAumko/edit#) during https://github.com/cityofaustin/atd-data-tech/issues/1476. The main issue is the [extensive drop down](https://user-images.githubusercontent.com/1463708/85091767-dc32d980-b1ad-11ea-90a0-bdd6654b1d83.png) for the date pickers is overwhelming/confusing. Unfortunately, we're not able to just use a calendar picker (Knack just hangs for hours when we try), so Surbhi is going to look at other options to provide some sort of date filtering; maybe with buttons.

**Comment by amenity** [comment]
@SurbhiBakshi - can you add some notes on what you'd recommend with this? We can discuss during #3123 . 🙏

**Comment by amenity** [comment]
We made the filters buttons instead of the drop down. Unfortunately, we can only filter on one field with that simplified set up. We learned that sectors aren't important and think it's more likely they'll want to sort by "Next Week" "Next Month" etc. over "Morning" "Afternoon" "Evening". We'll start with that and see how it goes in the pilot.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/45735c48-5242-4ba7-89f7-0cac18a9666b)
