### ISSUE TITLE
Explore options to clarify which shifts an Officer is meant to sign up for 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3081]
Ran into some [usability issues](https://docs.google.com/document/d/1PBtoOPWAwLMduMZs9jJhMu-YX213UgxbOuNnVBAumko/edit#) during https://github.com/cityofaustin/atd-data-tech/issues/1476:
- Officers might sign up for only one assignment in a shift
- Officers might sign up for two different assignments at the same time
- Officers might sign up for the same assignment twice

Ideally this would be 
- Grouping individual assignments together so the officer signed up for all three at once. 
- Preventing officers from signing up for the same shift twice (not possible :P )

**Comment by SurbhiBakshi** [comment]
#986 or [code ](https://www.knack.com/developer-documentation/#add-checkboxes-to-a-table)

**Comment by SurbhiBakshi** [comment]
###  **Visual cues** 
(for officers to focus at assignments within a shift, and not get confused by availability of other assignments.)

### Grouping   
so officers can see the assignments grouped together as one defined package.
1. by date, 
2. shift time (morning, afternoon, evening), 
3. team, 
4. officer (1, 2, 3 - depending on the number of officers required for that assignment)

- Use color to show different shifts so officers know which assignments belong to the same shift.



-
