### ISSUE TITLE
Archive atd-utils Repos

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#309]
We opted for the [atd-data-utilities](https://github.com/cityofaustin/atd-data-utilities) mono-repo with Sergio's pypi deployment pipeline, so we can archive the individual package repos:

- atd-util-email
- atd-util-data
- atd-util-args
- atd-util-jobs
- atd-util-log
- atd-util-knack
- atd-util-agol
- atd-util-socrata
- atd-util-kits

**Comment by johnclary** [comment]
It's done.

**Comment by sergiogcx** [comment]
This is great! we should a fewer repos now on here too?
