### ISSUE TITLE
VZ | Updating version # on release

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#3091]
It is easy to miss a version update in the VZ apps when creating a new release. It would be an improvement to find a way to update the version numbers in VZE and VZV other than pulling from `package.json`. 

Slack discussion: https://austininnovation.slack.com/archives/CHZE6BC6L/p1592577894137400

**Comment by JaceDeloney** [comment]
Low priority. Create a global environment variable that each VZ product could reference.

**Comment by JaceDeloney** [comment]
This is now implemented, but the issue was never closed.
