### ISSUE TITLE
Associate City ID 22 to Crash IDs

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3095]
Xavier was able to identify crashes that were occurring outside of the full purpose, but still in the city of Austin. He would like us to update the `city_id` field to `22` for the following `crash_id`s:

> --
> -- THIS QUERY INDENTIFIES THE CRASHES THAT FALL IN jurisdiction_id's OF (3,5,7,8,10), BUT DO NOT HAVE A city_id OF 22
> -- USE THIS QUERY TO FIND ADDITIONAL CRASHES THAT MAY NEED TO FALL UNDER VISION ZERO DATA
> --
> SELECT atc.crash_id
> FROM atd_txdot_crashes AS atc
> INNER JOIN atd_jurisdictions AS aj
> ON ( 1=1
> 	AND aj.id in (3,5,7,8,10)
> 	AND (aj.geometry && atc.position)
> 	AND ST_Contains(aj.geometry, atc.position)
> )
> WHERE 1=1
> 	AND atc.position IS NOT NULL
> 	AND atc.crash_date >= '2014-11-01'
> 	AND atc.city_id <> 22 
> ;

**Comment by sergiogcx** [comment]
So I found out that about 11,000 records do not have the same

**Comment by sergiogcx** [comment]
Before I made changes, I wanted to find if `rpt_city_id` is always identical to `city_id`, as it turns out it isn't, from running this query the result shows that almost 11,000 rows have different values.

```
SELECT COUNT(1)
FROM   atd_txdot_crashes
WHERE  rpt_city_id != city_id;
```

So I think the best way forward to retain the original values is to create a column and extend our trigger logic to copy the original value into the new column.

**Comment by sergiogcx** [comment]
This has been done, the update was made to production (11900 rows affected in 16 s 44 ms) using this SQL query:


```
-- First, disable all triggers
ALTER TABLE atd_txdot_crashes
    DISABLE TRIGGER ALL;

-- Make the update
UPDATE atd_txdot_crashes
SET city_id = 22
WHERE crash_id IN (
    SELECT atc.crash_id
    FROM
        atd_txdot_crashes AS atc
        INNER JOIN atd_jurisdictions AS aj
        ON ( 1=1
            AND aj.id in (3,5,7,8,10)
            AND (aj.geometry && atc.position)
            AND ST_Contains(aj.geometry, atc.position)
        )
    WHERE 1=1
        AND atc.position IS NOT NULL
        AND atc.crash_date >= '2014-11-01'
        AND atc.city_id <> 22
);

-- To re-enable triggers
ALTER TABLE atd_txdot_crashes
 ENABLE TRIGGER ALL;


-- To count results
SELECT COUNT(1) AS count
FROM atd_txdot_crashes AS atc
WHERE 1=1
    AND atc.position IS NOT NULL
    AND atc.crash_date >= '2014-11-01'
    AND atc.city_id <> atc.original_city_id;
```
