### ISSUE TITLE
Healthy Streets on Google Maps part 2

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#3097]
I've submitted a KML of our current Healthy Streets data through the [google partner dashboard](https://partnerdash.google.com/apps/basemap/myuploads). The dashboard will update me once my contribution has been accepted. At this point, we might be able to see Healthy Streets on google maps the same way they show up in Oakland.

**Comment by alan-deanda** [comment]
@johnclary  it seems that our previous look at this issue did not result in Healthy Streets displaying on google maps. I'm waiting to see if my submission has been accepted.

**Comment by alan-deanda** [comment]
I've been informed the data is currently being uploaded.

**Comment by johnclary** [comment]
@alan-deanda what's the latest?

**Comment by alan-deanda** [comment]
@johnclary  The data has not been used, a reviewer marked it as a duplicate. This is likely an error, and they haven't realized that it's a re-submission with re-formatted the data. I've asked them to revisit data upload. Waiting to hear back from them.

**Comment by alan-deanda** [comment]
@johnclary  Google Maps is now marking the data as in use. It doesn't show up by default yet, but it does seem to be affecting routing by car. I've tested this by getting directions by walking, biking and driving. 
I'm still asking Google whether or not the data will show up by default on the basemap as is the case with Oakland and San Francisco. Either way, the closures have an expiration date of 12/31/2020. They've also informed me that they'll include any more changes I request, so adding any subsequent Healthy Streets shouldn't be a problem

**Comment by alan-deanda** [comment]
From now, it's up to Google to decide whether to display Healthy Streets in Austin by default or not. I'm closing this issue.
