### ISSUE TITLE
Update Aerial Imagery on Google Maps

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#3101]
ATD would like Google Maps' aerial imagery to be updated to reflect the new murals Black Austin Matters (Congress Ave) and Black Artists Matter (E. 11th St.), as has been done in Washington DC with their Black Lives Matter.

I've done some research and found that Google Maps does accept aerial imagery from their content partners (I became a partner earlier this morning to upload Street Closure data related to Healthy Streets.) I am working with Jacquie on finding ways to acquire aerial/drone imagery to upload to Google Maps.

**Comment by alan-deanda** [comment]
Although the Google Maps representative I spoke with yesterday indicated that imagery is acceptable to submit, this morning I've received a different response from another representative:

> In case the data is imagery content, please know, imagery content by the 3rd party as well as government organizations were accepted in the past and currently we are prioritizing on other aspects of Google Maps and as a result, this particular feature is having a slight setback. Appreciate your understanding and cooperation on the matter.

It seems they'll accept our data submission, but we may not see it reflected in the map as quickly.

**Comment by johnclary** [comment]
Let's drop this. We've tried but don't have an easy to do this. Will wait for google imagery to update.
