### ISSUE TITLE
Meeting: DTS Service Desk Workflow

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3105]
### Participants 
- Jaime, Scott, Reedy, Diana

### Agenda
- Discuss the service desk workflow

**Comment by dianamartin** [comment]
## Diana's Notes

`ATD_IT queue` - ServiceNow

**Historically** 
+ Added Jaime - fulfiller
+ Add everyone to ServiceNow to manage the ticket?

**GIS SPOCs - Account Request form**
- GIS SPOCs in ServiceNow
- GIS SPOCS could fill out tickets
- They're not fulfillers 

### CURRENT WORKFLOW
- Anything that `ATD_IT`, both Scott and Jaime emails
- Assigned to group, members get notification
- Assign themselves or re-assign
- AMANDA related, forward the email to Tracy so she can review if needs to be re-assigned to AMANDA CTM Support

**Scott preference** 
- Emails and phone calls
- Not tracking work (not documented)
- Slack stand-up
- Service Now (CTM)

**Jaime preference**
- Emails and phone calls
- She create GitHub issues

**Comment by moorerst** [comment]
@johnclary we had a good meeting with Jamie and Scott. These are the meeting notes

**Comment by moorerst** [comment]
@dianamartin @johnclary  here is a report from Service Now of incidents for Department Austin Transportation Closed in the last 6 months by any group Not ATD_IT

[ATD.incidents.closed.by.group.not.ATD_IT.for.last.6.months (1).xlsx](https://github.com/cityofaustin/atd-data-tech/files/4821452/ATD.incidents.closed.by.group.not.ATD_IT.for.last.6.months.1.xlsx)

I put a filter on Sub Category to get an idea of the different incident categories but i have not analyzed the specific details yet

**Comment by dianamartin** [comment]
@moorerst @johnclary 

I put the spreadsheet into a pivot table to extract the `Categories` and `Sub categories`

Categories
--
Business Applications and Services
Communications
Employee Services
Hardware
Hardware Services
IT Infrastructure
IT Infrastructure Services
Security and Access
Software
Software Services

Sub Categories
--
Account Request
Active Directory
Adobe (Other)
Adobe Acrobat
Amanda
Amanda Browser
AMANDA Portal
AnyConnect
Avaya Call Forwarding
AW Application (Other)
Banner
Browser
COACD Citrix
COACD Domain
Conference Bridge
CSR
Data
Desktop Device
Device
eAccess
Email
Fax Hardware
File Services
GIS
GIS-Addressing
GIS-Data Request
GIS-Map Requests
GIS-Web
GoToMyPC
Hard Drive
Hardware (Other)
Internet
Intranet
LAN Access
Laptop Device
Malicious Threat
Microsoft Access
Microsoft Excel
Microsoft Exchange Server
Microsoft Office 365
Microsoft Outlook
Microsoft SharePoint   Enterprise
Microsoft Teams
Microsoft Windows Operating   System
Microsoft Word
Monitor
NetMotion
Network Printer
Password Reset
Phone
PNTS - Public Notification   Tracking System
Printer
ProjectDox
Remote Desktop Connection
Security Requests
ServiceNow
Software (Other)
Spam - Unwanted/Unsolicited   email
Support
System Software
Television
Training
TWS BAM Jobs - Business   Applications Management
Voice Application (Other)
Voicemail
VPN
Web Design/Development
WebEx

**Comment by moorerst** [comment]
Follow up meeting to be scheduled with a week. Giving us time to review the report from Service Now of tickets closed for ATD by CTM so we can create a better list of what customers would contact CTM to handle.

**Comment by moorerst** [comment]
Sample of high level categories for CTM Request

- Account Management (COACD)
Account locked/disabled
Password reset
Folder Permissions (G: drive)

- Amanda
Portal
Browser
Folder
Access
Attachments

- Enterprise Applications
Banner
CSR
ServiceNow
Project Dox
Outlook
eAccess

- Voice/Phone
Voicemail
Conference Bridge
Call Forwarding

- Remote Access
Netmotion
Citrix
GoToMyPC

- GIS
Addressing
Data Request
Map Requests
Web 16

- Security
Spam - Unwanted/Unsolicited email
Malicious Threat

- Hardware
Printer
AV

**Comment by dianamartin** [comment]
@moorerst Should we close this issue now that we have our notes in it? We can create the new issue for our meeting next week and just link it.

**Comment by moorerst** [comment]
@dianamartin yes we can close it. Issue 3127 is for the upcoming meeting and is linked to this issue.
