### ISSUE TITLE
Change Signals Airwatch Admin Password

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#311]
Diana's doing a lot of factory resets on the tablet. We want to understand the Issues and possibly designate a few signal techs to be first-line of support.

**Comment by amenity** [comment]
@dianamartin @johnclary is happening? Backlog? On Deck for Sprint 4?

**Comment by johnclary** [comment]
No, updating this to "Change Signals Airwatch Admin Password" which is what actually needs to be done, based on convo with Diana today.

**Comment by dianamartin** [comment]
Emailed Danny on 8/9, he was able to update the admin pin code. Will update 1password with new code.
