### ISSUE TITLE
Discuss IT Support request intake workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3127]
### Objective 
Scheduled meeting: 6/30

Follow up on https://github.com/cityofaustin/atd-data-tech/issues/3105. 

How can we streamline the IT Support service request process so that it runs smoothly for ATD staff, CTM, and the DTS Service Desk team?

### Participants
John, Jaime, Scott, Stephanie, Surbhi

------
- [x] Schedule meeting
- [ ] Meet and take notes
- [ ] Create resulting issues

**Comment by amenity** [comment]
@moorerst  - please mark @jaime-mckeown, Scott, and @SurbhiBakshi as optional.

**Comment by dianamartin** [comment]
## Diana's Notes
- John said he'd like transportation.data email cc'd
- Thinks that we want to have all DTS members be fullfillers

### Talking about proposed workflow
- Members and transportation.data will receive emails
- When someone opens a ticket and CTM can't open a ticket
- Create KB article to CTM
  - To instruct them to send it to `ATD IT` group
  - We can make it so that if it's not an Enterprise application to route it to `ATD IT`
- Ticket needs to be closed or resolved by someone

Need to work on Service Desk content
- Users to start at our landing page and we direct them on where to go
- Other departments, they have their own IT and hey manage their work through ServiceNow (ex. PWD)
- ATD could do this

**Comment by moorerst** [comment]
DEVELOPMENT SERVICES: What to Assign to DSD IT Group
KB0013659
34 views
Introduction
 

Need to know what to assign to DSD_IT support group.

 

Instructions
 

This KB article is intended as an Internal Reference/Resolution ONLY for CTM Service Desk Staff.

 

Internal
 

DSD IT handles IT functions that are unique to DSD only. CTM Service Desk handles computer issues common to all departments such as with desktops, network, file services and phones.  

 

Steps:


Types of Incidents and Requests that should be assigned to DSD_IT:


Amanda issues for DSD folders (Other department issues/accounts supported by CTM)
Accounts and workflow in ProjectDox for all departments
Note: ProjectDox installations are done by the CTM Service Desk, see KB0013140 (back-end system supported by CTM).
DSD Sharepoint issues
DSD Teams issues
Freshchat software problems
DSD GIS issues
Note: ArcGIS installations are supported by CTM. Service Desk Staff have access to install the Oracle Client as needed, see KB0011371.
Development Tracker
DSD Website
DSD PDF applications hosted on the city's website, see KB0013647.
DSD Bluebeam issues
DSD ePlan issues (Bluebeam or Projectdox)
DSD Fees (Amanda permit fees)
DSD Microstrategy Reports (Amanda Reports for DSD)
Property Profile data, see KB0012431 (back-end supported by CTM).
PDC (permitting and Development Center) IT issues
Qless queuing software accounts and support 
 

Related Articles:

**Comment by moorerst** [comment]
Action Items:

- [ ] Discuss with CTM the option to having the CTM ServiceDesk direct ATD users to the DTS Service Request Form for specific issues
- [ ] Create content for ServiceNow Knowledge Article which defines what should be assigned to the ATD_IT group in ServiceNow (see sample KB article above KB0013659)

**Comment by moorerst** [comment]
One thought is to create a SN Knowledge Article which contains instructions for the CTM ServiceDesk to direct users to complete the DTS Service Request Form for a specific issue. 
This knowledge article would be a link next to specific items in the overall What to Assign to ATD_IT Support document. 
Ex - Residential Parking Permit Application see KB00xxxxxx
KB00xxxxxxx - directs CTM Servicedesk to tell user to complete the DTS Service Request Form

**Comment by moorerst** [comment]
@johnclary @dianamartin @SurbhiBakshi  I spoke with CTM about having the Service Desk direct users to complete the DTS Service Request Form for predetermined issues/request. They agreed that if we don't want to manage incidents in SN the best option would be to create a knowledge article similar to the one above for DSD_IT. In that article have a list for Types of Incidents and Requests that should be assigned to ATD_IT and a list for the Types of Incidents and Requests that should be directed to DTS Service Request.
We would need a second knowledge article like the one below that instructs the Service Desk to direct the user to complete the DTS Service Request Form.

**Sample knowledge article to direct customers to complete a different Service Request Form**

FIRE: Submit/Process Comm Service Request Form
KB0011858  -  Latest Version
3 views
Introduction
Need to submit the Comm Service Request Form to report a problem or request service from Fire Communications.

 

Instructions
This knowledge article is intended as Self Help Reference/Resolution for all FIRE Users.

 

Assumptions:

You are a FIRE User
You know your TXFIR and PIN
You have an issue or a request while at a Fire Station or on a Fire Truck
 

Steps:

Click this link to access the Comm Service Request Form
URL: http://afdweb/COMM/CommServReq_login.cfm
Scroll down to the bottom of the page, you will see the fields for the Comm Service Request Form
Enter your TXFIR and PIN
Click the Continue button
Complete all required information
**We would not include these steps**
**Click the Submit button 
Once submitted, an email will be sent to the CTM Customer Service Desk so an Incident can be created and assigned to FIRE_COMMUNICATIONS**
