### ISSUE TITLE
VZD Events: Automate city_id change

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#3128]
In a recent issue (#3095) Xavier requested that we update the city_id to 22 for some of the records that fall in jurisdiction id 3,5,7,8 and 10. This process can be automated, and it probably should for further analysis. It may be best to do this using the event handler. We would simply have to translate the process into Python and GraphQL

**This will be particularly important for new records coming in with the import.**

Xavier sent us this SQL code:
```
SELECT atc.crash_id
FROM atd_txdot_crashes AS atc
INNER JOIN atd_jurisdictions AS aj
ON ( 1=1
    AND aj.id in (3,5,7,8,10)
    AND (aj.geometry && atc.position)
    AND ST_Contains(aj.geometry, atc.position)
)
WHERE 1=1
    AND atc.position IS NOT NULL
    AND atc.crash_date >= '2014-11-01'
    AND atc.city_id <> 22;
```

In our case for the SQS event handler, we need to take a single crash, identify if the crash belongs in the full purpose jurisdiction, and if it does not have crash_id of 22 and DOES have a position, then update the city_id to 22.

**Comment by JaceDeloney** [comment]
Based on yesterday's discussion, we need to revert the changes requested in #3095. I misunderstood the priority and need for that request. We will revisit the request at a later date. Please do not make the changes outlined above (for now). Moving this back to the backlog.

**Comment by JaceDeloney** [comment]
This is no longer a request from the VZ Team. We implemented a different solution that allows VZ staff to view data based on different jurisdictional filters.
