### ISSUE TITLE
Record NEO - Overview ATD Divisions

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3136]
- [x] Record ATD Divisions

**Comment by amenity** [comment]
@dianamartin - please add information about this work to your offboarding docs. 🙏

**Comment by dianamartin** [comment]
Added NEO links to off boarding document

**Comment by dianamartin** [comment]
- [x] Recorded ATD Divisions Overview on 7/22
- [x] Editing recording
- [x] Exported recording
- [x] Uploaded to HR New Employee Orientation SharePoint page
- [x] Added duration lengths for all videos
- [x] Emailed Linda updated video
