### ISSUE TITLE
Discovery Day v4 | Knack Builder, Lucid Chart/Miro review

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3145]
Here's a template you can start from if you'd like: 
### Challenge or Solution
I want to see how not using the Knack beta environment and trying to recreate an existing knack application in the new builder environment. 
- [x] Recreate the `Trivia/Quiz` application in Surbhi's sandbox
- [ ] Create workflow chart in Miro on Trivia/Quiz
- [ ] Create workflow chart in Lucid Chart on Trivia/Quiz (if time permits)

### Prerequisites
- [x] Enabled Knack beta in main Knack builder account
- saw that you can toggle the new builder environment on any application - Whoa!
- [x] Created a new Knack application called `Trivia/Quiz`
- [x] Signed up for `Miro`
- [x] Signed up for `LucidChart`

### Are there any hurdles you foresee? How might we address them?
- Learning how to navigate and build in a new environment

### Deliverable
Everyone will have three minutes to present their work (with the option to save the recording) and a slide in the Discovery Day presentation deck. Are there any other artifacts you want to walk away with? Wiki pages, a prototype, etc.

**Comment by dianamartin** [comment]
Will pick Surbhi's sandbox - to recreate the the Trivia Application I made using

**Comment by dianamartin** [comment]
# UI Comparisons
## New Builder
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/148c7c9c-0bb2-46e6-a6cb-7e17fd5d8faa)

## Old Builder
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/4a90b53b-4538-4332-814c-982e6c6b7178)

**Comment by dianamartin** [comment]
## UI Menus 
- moved from the top to the left - _feels kind of weird, was looking around for it_

**Comment by amenity** [comment]
@dianamartin - you good to close this?

**Comment by dianamartin** [comment]
@amenity Yeah, even though I didn't really get to play around with Miro or Lucid chart. I might still mess with it when I make some upcoming workflows.
