### ISSUE TITLE
Discovery Day v4 | Google Vision + Github Actions

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3146]
## Challenge or Solution
For discovery day I will work on Google Vision API and GitHub Actions

- [x] Get google vision api to read typed text as well as hand-writing
- [x] See if you can get GitHub actions to delete resources on AWS after closing a PR.
- [x] Investigate GitHub actions as an alternative to CircleCI.

## Prerequisites
Steps for Google Vision:
- [x] Make PR 
- [x] Install google api library
- [x] Download sample PDFs ...or all of them :)

If time allows (GitHub Actions):
- [x] Set up a branch that sets up GitHub Actions
- [x] Set up a python script that deletes resources created by the PR.
- [x] Set up AWS environment variables if possible

## Are there any hurdles you foresee? How might we address them?
- [x] Downloading files from S3 could be a problem, I need a variety of files that have no narrative, narrative written with a machine, and narratives that are hand-written.  

## Deliverable
- [x] GitHub action that deletes resources created by PR.

**Comment by sergiogcx** [comment]
For discovery day I will work on Google Vision API and GitHub Actions

- [ ] Get google vision api to read typed text as well as hand-writing
- [ ] See if you can get GitHub actions to delete resources on AWS after closing a PR.
- [ ] Investigate GitHub actions as an alternative to CircleCI.

Steps for Google Vision:
- [ ] Make PR 
- [ ] Install google api library
- [ ] Download sample PDFs ...or all of them :)


If time allows:
- [ ] Set up a branch that sets up GitHub Actions
- [ ] Set up a python script that deletes resources created by the PR.

**Comment by sergiogcx** [comment]
There is a PR for this issue:
https://github.com/cityofaustin/atd-vz-data/pull/840

So far the Actions work well, the next steps is to test the custom condition on PR close and make sure the PRs are being deleted as expected.

- [ ] Make sure the PRs are created to begin with.
- [ ] Make sure the code handles PR close event and runs action
- [ ] Test the PRs are getting deleted

**Comment by sergiogcx** [comment]
A screenshot from GitHub actions:

![2020-06-29_10-33-20.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/cd86f051-0f00-42d7-b978-859df4d3bf42)

**Comment by sergiogcx** [comment]
Example of Google Vision API:

![2020-06-29_10-55-51.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/3faddd55-1db2-49a7-a187-e5969f53b8b7)
