### ISSUE TITLE
Discovery Day v4 | Push (Bike Facilities & Aerial Imagery) Data to Google Maps

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3148]
## Challenge or Solution
What is the problem you want to solve or solution you want to explore?

## Prerequisites
Software, data, getting a local dev environment set up, etc.

## Deliverable
Everyone will have three minutes to present their work (with the option to save the recording) and a slide in the Discovery Day presentation deck. Are there any other artifacts you want to walk away with? Wiki pages, a prototype, etc.

**Comment by johnclary** [comment]
@alan-deanda can you provide an update here?

**Comment by johnclary** [comment]
nm—i see a separate issue. closing this one.

**Comment by alan-deanda** [comment]
@johnclary  I'm re-opening this issue and placing it in Review/QA. I've just submitted the data. I'll close it once the data is  live in Google Maps
