### ISSUE TITLE
Digitize Daily Operational Safety Analysis (DOSA) Form

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#315]
See [attached announcement](https://app.zenhub.com/files/140626918/abed4ad1-4cd5-4d16-82a6-8142008bfeaa/download).

Needs intake:
https://docs.google.com/document/d/1wN7mwMCF3H4MajOX9JA-PQ8zEzcJ1kfEeGCKv-Us0JA/edit#

**Comment by johnclary** [comment]
Let's hold off on intake until after signs migration (Aug 2019 or later)

**Comment by amenity** [comment]
There is an issue somewhere for meeting to evaluate this need.

**Comment by amenity** [comment]
@johnclary - would this be a freestanding app or part of SMB Data Tracker?

**Comment by dianamartin** [comment]
@amenity I think I added this feature to the SMB tracker... maybe we can find the closed issue that I did..

**Comment by dianamartin** [comment]
@johnclary @amenity I think we can close this

**Comment by amenity** [comment]
@dianamartin cool! Done.
