### ISSUE TITLE
Discovery Day v4 | React Hook Form + Material UI

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3151]
## Challenge or Solution
[react-hook-form](https://react-hook-form.com/get-started) is a React form library that aims to improve both developer experience and performance of forms. It also integrates well with [Material UI](https://material-ui.com/) which provides solutions for more complex form needs (multi-select, autocomplete, validation). Both of these libraries could provide a solution to create complex forms quickly and easily for future DTS apps.

## Prerequisites
[create-react-app](https://github.com/facebook/create-react-app)
[react-hook-form](https://github.com/react-hook-form/react-hook-form)
[material-ui](https://github.com/mui-org/material-ui)
[styled-components](https://github.com/styled-components/styled-components)

### Are there any hurdles you foresee? How might we address them?
Material UI can be hard to style, and the learning curve may present barriers since we have relied on Bootstrap in the past for UI components. Fetching data could also pose a hurdles - especially for form elements that fetch data for Knack to populate options.

## Deliverable
Present the problems that `react-hook-form` is trying to solve and how and demo a prototype using it along with Material UI to clone a form in the Mobile Signals Work Orders app

**Comment by mddilley** [comment]
# What I learned
- It takes time to set up initially
- Fast development after initial work
- Capture this work by creating components built with components
- Less code complexity
- React Hook Form has dev tools and a builder

# Hard and not so great things
- Both react-hook-form and Material UI have a learning curve
- Material UI’s opinions made using it along with react-hook-form difficult at times
- Performance issues with long lists

Overall, I was able to recreate parts of the New Work Order form from the React Mobile Signals Work Orders app. Getting started took some time, but, after watching [this video](https://www.youtube.com/watch?v=0nDGeQKLFjo), I think that a good workflow could be developed and reused easily.
