### ISSUE TITLE
Meet to have initial follow-up discussion

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3165]
### Objective 
Scheduled 6/29

### Participants
- Alison, Joel, Christina, John, Susanne, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [x] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes
Data Collection - Jan 2021

Location data set from Knack

Collecting sign data
Tablet - with points in existing data set
- verification, they're in the spots we are expecting

Measuring street widths
Near map - measuring (not too time consuming)

Couple trips out there.
- Existing signs in spots
- Other signage needed
- QC'ing 


811 - dig tess
30 --> 25 mph

NORMAL OPERATIONAL BUDGET TED/VZ
- Work Order Process
- Location points 
- Sign Data QC field 
- Measuring street widths - Near Map

[AGOL map - Maintenance Areas](https://austin.maps.arcgis.com/home/webmap/viewer.html?layers=c187b224c0cd4bd4bc828578d0f3165d)

**Comment by johnclary** [comment]
My notes:

- whats our timeline? ASAP, but expectation is that this work may take a year.
- Downtown conversion is currently in progress. Possibly being tracked by Lee/Dipti but ??? Need to put a process in place.
- TED expects to drive all/most city streets to find signs
- TED will also need to capture lane widths. will probably do this with Nearmap. PWD street widths are not reliable enough due to inconsistent data capture.
- Many signs will be removed/moved. Strategy is to place signs at entrances to neighborhoods rather than throughout.
- Related, many parking meter signs will soon be removed/replaced to focus on mobile pay. Dropping points is the most time-consuming aspect for technicians. We need requesters to drop points.
- for future meetings we should include Alison M, Joel M, Diana M, Susanne G, Christina T, John C, Dipti, Lee A, Anthony F, Kati A, Jesse R.

**Comment by dianamartin** [comment]
@johnclary Closing, we have a follow-up `DTS Huddle: Citywide Speed Limit Conversion` scheduled 7/7 at 2 pm
