### ISSUE TITLE
ROW Fee Waiver Report (TL)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3167]
### ROW Fee Waiver Report Info

**Stakeholder:** Paloma
**DTS Manager:** Tracy
**Note:** This issue has been updated to include acceptance criteria from #3168 

- Menu Report on ATD Menu option
- Parameters: 
    - User able to query by fee comment (accountbillfee.feecomment)
- Folders to include in query: EX, RW (Exclude Street Event Subtype), DS, LC, ECV (transportation subtype), PSM, GF (transportation subtype)
- Output: Make it exportable to excel

**Report Data:**
- Folder RSN
- Folder Name
- Amount Waived
- Fee Comment 
- Fee adjustment/waiver reason
- Folder Subtype
- Invoice Date

**Comment by TracyLinder** [comment]
Development will begin sprint 29 or 30.

**Comment by TracyLinder** [comment]
### Approved to move to Test

@SubhaShroff @sre

**Comment by TracyLinder** [comment]
**Status:** UAT to take place during sprint 30. Updating milestone.

**Comment by SubhaShroff** [comment]
Status: Deployment plan and the crystal report is sent to @Nadin-Nader for TEST deployment on 7/29/2020.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Waiting on Nadin on TEST Move.

**Comment by TracyLinder** [comment]
**The acceptance criteria has been updated. Changes are highlighted below:**

![image](https://user-images.githubusercontent.com/49930868/89231772-9ab68c00-d5ab-11ea-9d3b-f523ba779e11.png)

**Comment by TracyLinder** [comment]
**The acceptance criteria has been updated. Changes are highlighted below:**

![image](https://user-images.githubusercontent.com/49930868/89231826-bd48a500-d5ab-11ea-8999-ce32cc14d5b2.png)

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Subha is working on this.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Completed the Report and sent for review

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Submitted DEV Deployment plan on 09/22/2020.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder UATD this on DEV and it has the date range parameters, exports to Excel, columns are correct and correctly named. Report pulls correct info and calculations.

### I Approve for move to TEST🎉 💯!!

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff @TracyLinder I have deployed this to TEST. Please log on and let me know if all is well. If it is we can have the stakeholder test it in TEST before the move to PROD.

**Comment by shroffjs** [comment]
Thank you @Nadin-Nader.
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan This ticket is tested in TEST. ROW Project Specific Waiver Report (99012) is ready for your testing on TEST environment.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @Sreelatha-BlazeKannan @TracyLinder I have ran the report on TEST and it looks good to me. I also sent an email to Kim and Paloma asking them to UAT the report and let us know if they approve it to go to PROD.

> From: Nader, Nadin 
> Sent: Tuesday, October 6, 2020 11:01 AM
> To: Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>; Perez, Kimberly <Kimberly.Perez@austintexas.gov>
> Subject: UAT of ROW Fee Waiver Report (99012) #3167
> 
> Good Morning,
> 
> Hope you are both doing well. I am reaching out to you about the ROW Fee Waiver Report (99012) #3167. The report is currently on TEST and has been UATd by the developers and myself. The report seems to be correct and meets the requirements for #3167 and 3168.
> Could one or both of you log onto to TEST and run the report? Once you approve of the report we can get it to CTM  to deploy it to PROD.
> Please let me know the outcome
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services 
> Austin Transportation Department

**Status:**
Waiting  on Kim and Paloma to UAT on TEST and approve the move to PROD.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader,  @TracyLinder -  Waiting on UAT

**Comment by TracyLinder** [comment]
Will look at this w/ stakeholders on Friday 10/9

**Comment by TracyLinder** [comment]
### UAT Results
Acceptance criteria has been met however two new columns have been requested:
- Folder Subtype
- Invoice date

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - Subha will be working on this

**Comment by shroffjs** [comment]
Updated the crystal report and has sent the excelsheet to @TracyLinder @Nadin-Nader for review today(10/12/2020).

**Comment by Nadin-Nader** [comment]
@SubhaShroff @Sreelatha-BlazeKannan @TracyLinder I have looked over the excel sheet sent in the email and found that the new criteria has been added and it is correct. I also tried to run it on TEST and found the new criteria is not there. If it hasnt been deployed to TEST yet, then we are good to make the changes on TEST. If it has, then we need to take another look at adding it.

**Comment by shroffjs** [comment]
Thank you @Nadin-Nader.  The excel sheet sent is executed directly from Crystal Report Tool connected to TEST database, but not from Amanda. I have just emailed you the updated .rpt file to copy in DEV/TEST servers so that we can see the change in AMANDA also.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @Sreelatha-BlazeKannan @TracyLinder I have deployed this to DEV and TEST and is ready for UAT.

**STATUS:**
Ready for UAT on TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff @TracyLinder I ran this on TEST and the two ne columns are in the exported Excel. I will send an email to the stakeholders and aske them to UAT and approved the deployment to PROD.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff @TracyLinder email sent to Paloma below:

> Paloma,
> 
> Hope you are doing well. I am reaching out to you in regards to the ROW Fee Waver report (99012). It is available on TEST for UAT. Please let us know if the report is correct and if it is approved to move to PROD.
> 
> If its approved, we will get it over to CTM for deployment to PROD.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services
> Austin Transportation Department

**STATUS:** 
Waiting on Stakeholder UAT on TEST and Approval to move to PROD

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - Waiting for Stakeholders Approval

**Comment by TracyLinder** [comment]
Let's discuss w/ ROW during Friday's meeting.

**Comment by Nadin-Nader** [comment]
From Paloma:

> Paloma,
> 
> Sorry for the delayed response. I put “Waived” as the Fee comment and it generated the information.
> 
> From: Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov> 
> Sent: Friday, October 16, 2020 4:26 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>; Sreelatha.b@launchitcorp.com
> Subject: RE: UAT ROW Fee Waver Report #3167
> 
> Hey Nate,
> 
> I’m trying to remember what I need to key into the “Fee Comment” field in order to generate the report.  I’m in test right now.
> 
> Paloma Amayo-Ryan
> Program Manager
> (512) 974-2841

**Comment by TracyLinder** [comment]
### Approved for PROD 🎉

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - Subha will be sending the PROD DP Plan.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff @TracyLinder  This has been sent to CTM Tango to Deploy to PROD un der TASK **SCTASK0102613**

## **Status:**

Waiting on CTM to Deploy to PROD

**Comment by shroffjs** [comment]
**Status:** Waiting on CTM to Deploy in PROD. SCTASK0102613: Still shows OPEN status(11/2/2020)

**Comment by Nadin-Nader** [comment]
@SubhaShroff @Sreelatha-BlazeKannan @TracyLinder This has been deployed to PROD by CTM. I will send an email and close

**Comment by Nadin-Nader** [comment]
@TracyLinder @SubhaShroff @TracyLinder  email sent and i am closing:


> Paloma,
> 
> Hope you are doing well. I wanted to let you know that the ROW Fee waiver report (99012)is now available on PROD for you to use. I will go ahead and close out the card but if anything, please feel free to email us.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services
> Austin Transportation Department
