### ISSUE TITLE
OSE Fee Waiver Report (TL)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3169]
### OSE Fee Waiver Report 

**Stakeholder:** Maria A.
**DTS Manager:** Tracy

- Menu Report
- Output: Exportable to Excel
- Parameters: Start Date, End Date [Info: Event Start Date]
- Folders to Include: RW, Street Event
- Include all fee waiver types

**Report Info:** 
- Folder RSN
- Work Type
- Folder Status 
- Folder Name
- Billed To (First Name, Last Name, Org Name)
    - From Folder People; Use 'Billed To' people type, if not exists then use 'Applicant' people type
- Fee Date
- Fee Name
- Fee Amount
- Adjustment Amount
- Adjustment Reason
- Adjustment Comment

**Comment by TracyLinder** [comment]
Development will begin sprint 29 or 30.

**Comment by TracyLinder** [comment]
**Status:** Work to begin in sprint 31.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Subha working on the changes

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder ,@Nadin-Nader - Subha completed and sent the report with a question that When "Billed To" with multiple people record, exists, then which one to consider?

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff @vschandramouli During our standup Tracy said that she believes its ok to go with whoever is listed first and that is how the logic usually is with AMANDA.

**Comment by shroffjs** [comment]
@Nadin-Nader @Sreelatha-BlazeKannan @vschandramouli Report is updated as per the latest response and I have sent the demo email with report spreadsheet(9/17/2020).

**Comment by Nadin-Nader** [comment]
Viewed demo XLSX and found that all of the information displayed were in the columns asked for;

Folder RSN,Work Type,Folder Status,Folder Name,Billed To (First Name, Last Name, Org Name),From Folder People; Use 'Billed To' people type, Fee Date,Fee Name,Fee Amount,Adjustment Amount,Adjustment Reason,Adjustment Comment.

I wasnt able to verify the data

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader  - Tracy's approval on #3166,#3168,#3169,#2647 &#3302 required to Move this to DEV. If the Format looks good, then we can move this to DEV for further Data Testing.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - DEV Deployment request submitted on 09/22/2020

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff @TracyLinder I have moved the new copy of 99015 to DEV. Please log on and verify all is well.

**Comment by shroffjs** [comment]
Thank you @Nadin-Nader.
It is tested and works as expected. Ready for your testing.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder UATd this on DEV and it has the date range parameters, exports to Excel, columns are correct and correctly named. Report pulls correct info and calculations.

### I Approve for move to TEST🎉 💯!!

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff @TracyLinder I have deployed this to TEST. Please log on and let me know if all is well. If it is we can have the stakeholder test it in TEST before the move to PROD.

**Comment by shroffjs** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan Tested in TEST and OSE Fee Waiver Report (99015) report is ready for your testing.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder  @Sreelatha-BlazeKannan This has been Tested by Myself and Maria on TEST. Maria has approved the report be moved to PROD.

### **APPROVED FOR PROD!! 🎉**

**Status:**
Waiting on Deployment to PROD

**Comment by shroffjs** [comment]
Thank @Nadin-Nader.
PROD Deployment Plan is sent in email.

**Comment by Nadin-Nader** [comment]
Deployment has been sent to CTM Tango to move the report from TEST to PROD. Task for CTM Tango is **SCTASK0099052**

**Status:**
Waiting on CTM to put report on PROD

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff @TracyLinder This has made it to PROD. I will send an email to Maria to inform her of the move then i will close the card.

**Comment by Nadin-Nader** [comment]
## **Email Sent**

> From: Nader, Nadin 
> Sent: Wednesday, October 7, 2020 8:01 AM
> To: Alonso, Maria <Maria.Alonso@austintexas.gov>
> Cc: Sreelatha.b@launchitcorp.com; Linder, Tracy <Tracy.Linder@austintexas.gov>; Shroff, Subhashini - Vendor <subhashini.s@launchitcorp.com>
> Subject: OSE Fee Waiver Report #3169 Deployed to PROD
> 
> Maria,
> 
> Hope you are doing well. I am reaching out to you regarding the deployment of the new OSE Fee Waiver report. This report has been deployed to PROD and is ready for use.
> I will now close the card but if you have any issues, please let me know.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services 
> Austin Transportation Department
>
