### ISSUE TITLE
Reach out to Waze About Speed Limit Data

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#317]

**Comment by johnclary** [comment]
I asked Jen for a point of contact at waze.

**Comment by johnclary** [comment]
email set to Waze CCP contact today:

> I'm reaching out to inquire about Waze's speed limit data. We're in the process of overhauling our speed limit data management, and are interested in validating our speed limit records against yours to flag potential issues. Is this something that may be possible through an API endpoint or data export?

**Comment by johnclary** [comment]
From Waze:

**Comment by mateoclarke** [comment]
bummer
