### ISSUE TITLE
Digital RPP Petition

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3171]
### Objective 
Intake meeting for request (https://github.com/cityofaustin/atd-data-tech/issues/2917)

### Participants
PE: Ryan Royal
DTS: Diana, Stephanie, Chrispin

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes

RPP Citizen requested program
- application from a neighborhood block
- property issues on their block
- notify their neighborhood association or HOA for their intent to apply (Required - proof attempt to notify)
  - Some people don't know they have a neighborhood association

Citizen fills out applications
- Neighborhood address
- Contact Info: address, email, phone
- What's required of them (lots of leg work on applicant's part)
- Might already have current parking regulations in place
- Ryan likes to discuss with applicant with them

Ryan to creates the petition packet for applicant

- Address/street name
- Block Name
- Requested Hours
- Weekends included, sometimes it doesn't

- 4 sheets go to applicant (mailed out)
  - Pre-fab letter, change date and sign 
  - Details a sign to put up (Signage font sizes)
  - Neighborhood Endorsement form
  - map: highlight the houses, eligible houses

### Applicant 
The person goes door to door
Applications on hold
Still getting them in, more interest lately.

Digital way to do this, to run program, socially responsible. 

### Requirement
- 60% of neighbors need it
- Applicant calculates the percentage
- RPP Staff will verify the percentage is correct

Petition doesn't have a time frame (months - year to complete)

### Any room from improvement?
- process works well for now
- haven't had any issues thus far
- Currently license plates number for person applying
- House hold license plate numbers
  - `Parking Occupancy Survey` (subtract residents license), not fair to process/program
    - 75% non-resident traffic 

## Digital Process 
- Parent petition - Details (web page)
  - Related table: Residential Streets associated
    - `Street Name`
    - `Beginning Cross Street`
    - `Terminating Cross Street`
    - `Side`
  - Related table: resident to sign electronically, collect license plate
    - `Resident Signature`
    - `Name`
    - `Position` - **Yay/Nay**
    - `Daytime Phone Number`
- Website: put it on a flier, post it on NextDoor

## Approval Process
### Approval  
- Get with the Engineer 
  - Regulation Signed
  - **Letter Approval**
  - Coordinate Signage installation

### Deny
- Traffic Engineer is told about it
- Draft Letter - post it on the actual petition
- Resident needs to distribute to neighborhood

## Vertical Mixed Use Corridors (VMU) Process
- corridors, have incentivized for businesses
- lower onsite parking percentages (ex. SoCo, Lamar, So First)
- RPP mixed used corridors
- Within 600 ft of VMU 
  - expedited process
  - all same steps, except no parking survey
  - 66.7% (2/3rd) of approval residents - with support
 - Neighborhood Associate MUST SIGN the support form
   - If not, then parking is conducted
   -  verify petition
  - Engineer gets final approval 
(2-3 week process)

## Parking Survey - digitized in the future?
- currently based process
- map on it as well
- instructions where to count cars

## Special Functionality - Resident 
If residents refuse to sign, resident is out of town/not home
*** Residents need to be account for, so applicant needs to track this and provide reason for "no answer"
- Produce: record for every address on block that accounted for

**THINGS TO CONSIDER**
- Should applicant have an account? log-in
- Communicate comment/notes: petition phase, Status update to Parking Office

PROPOSED PROCESS 
- Applicant turns in application
- Applicant talks to Ryan
- Ryan creates digital petition
   - Attachments - functionality 
   - Applicant to also add attachments - function
- Email goes to applicant
- Status - **In Review, Petition Phase, Verify Petition, Parking Occupancy Survey, Engineering Review, Approved, Denied, Withdrawn**

**Comment by moorerst** [comment]
Citizen initiates the request by contacting RPP staff 
Intake/Request
RPP staff has discussion with citizen:
to determine the issues with the neighborhood
explain the program and process
Citizen required to do all the leg work, getting the petition signed
Citizen has to notify the HOA or neighborhood association of the intent to apply for a RPP zone
They must show proof of email to HOA or neighborhood association. Sometime they may not know they have a HOA or association. RPP staff will look up that information (this would be an  attachment) 

Petition Packet
RPP staff creates the Petition Packet
Address/street name
Block Name
Requested Hours
4 items get mailed out to the applicant
Letter
Details of signage
Neighborhood Endorsement form
map

Applicant 
goes door to door to collect signatures
needs 60% of residents to agree
No timeframe for petition to be active could be available for months/year

Current process works fairly well
Currently only collecting the license plate # for the person signing the petition. Would like to collect all the license plates for the household

RPP staff Approval Process


Must Haves in digital petition
Applicant should have a login so they can attach documents or add records - advanced permissions - 
Link to provide to neighbors or post on neighborhood apps (since the applicant may not know email address of all residents)
No edit function Notes box for any updates
Attachments - applicant will need to add attachments
Status change In progress, approved, denied, withdrawn, in review, petition phrase, verify, survey, engineer review

Not in scope
The actual intake or request process
Parking survey

**Comment by johnclary** [comment]
My notes from Feb 9 follow-up meeting with Ryan, Joseph, and Jason R.

**Need**
A simple form where people submit their signature, address, feedback, etc. for an RPP petition.
The form must include a link to the digital “Packet” (preferably hosted on COA website) that includes the details of the proposed RPP area.
It is the responsibility of the resident SPOC to distribute the info for the digital petition. 
All active/historical petition information needs to be easily finable on COA website.

**In scope**
Identify a form platform staff can use to create RPP petition surveys and collect responses
Help with testing and training

**Out of scope**
Managing petition requests received from residents
Workflows for managing any back-office aspect of the petition process (engineer review, etc)
Management of parking surveys
Mapping/GIS
Reporting
