### ISSUE TITLE
Document requirements for Project Tracking in AMD's Data Tracker

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#3175]
I will follow DTS' process for tracking requirements (i.e. user stories) for Knack apps, otherwise, I'm happy to get building in a non-production copy of Data Tracker. Will plan to deliver the requirements in the upcoming sprint; ideally, we can do it all (requirements + development) in the same sprint.

See #3042 for initial research/discussion, including proposed spreadsheet to track projects in Data Tracker.

**Comment by amenity** [comment]
@zappfyllc - did you still want to do this, given that we will be taking a non-Knack approach?

**Comment by zappfyllc** [comment]
@amenity This was always a placeholder even with Knack, so I don't see the purpose if the functionality is essentially moped. We can just document the feature requirements that would encompass this work. I'll close for now and we can re-open if anything changes.
