### ISSUE TITLE
Create "Problem Found" and "Action Taken" Pick Lists 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3178]
Per discussion with Brian and Brian today, we'll move forward with adding an autocomplete pick-list for the "problem found" and "action taken" fields on signal work orders. 

TODO
- Brian and Brian are going to send us a list of choices
- We will change out the "problem found" and "action taken" fields from paragraph text to pick lists
- add a "Work Details" paragraph text to capture more notes.
- Need to check all pages and workflows for this.
- Ugh, updates to signals mobile app, too

**Comment by dianamartin** [comment]
Brian emailed asking
>Brian V and I met and we think that if you can do the following, we may be good for the very  shorterm. We are looking into some other changes also.

>In the advance search in the Work Ticket section, please add the following to be searchable:
>
1.	Scheduled Work
2.	Problem Reported
3.	Status
4.	Closed date
>Please add Action Taken to the table.

**Comment by dianamartin** [comment]
## Changes I made

The [Advanced Search Signal Work Orders page](https://atd.knack.com/amd#work-orders/advanced-search-signals)
### Original page layout
 ![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/2e630489-209c-452d-a366-c31f116d57e7)

### New page layout
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/c578d162-e005-4362-b1cc-314238c2ac32)
 

**ADDED TO SEARCH FIELD**
•	Scheduled Work (Work Type): This field has been added to the search fields, just after “Work”
•	Problem Reported: This field has been added to the search fields, just after “Work” field
•	Status: This field has been added to the search fields, just after “Asset ID”
•	Closed Date: This field has been added to the search fields, just after “Updated”

**ADDED TO SEARCH FIELD RESULTS**
•	Scheduled Work (Work Type): This field has been added to the search table, just after “Updated”
•	Problem Reported: This field has been added to the table, just after “Description”
•	Status: Already existed on the Search Results table
•	Action Taken: This field has been added, just after “Problem Reported”

To follow up, have you and Brian made any progress on compiling a short list for the Problem Found or Action Taken fields?

**Comment by amenity** [comment]
Diana emailed the Brians to get feedback on this.

**Comment by dianamartin** [comment]
Last discussion was that Amenity was going to try to get feedback from the Brians about it or we'd wait to hear from them depending on if it's still a priority.

**Comment by johnclary** [comment]
Per discussion with AMD, this is going to be a serious challenge and may not be feasible. Moving to the backlog until it becomes higher priority.

**Comment by amenity** [comment]
Email from Brian VdW today
>  In order to better be able to track assets and maintenance efforts, we will be converting our Work Order system to use “Pick Lists” similar to those used by Signs / Markings. Attached is my first attempt at this list and is based on review of work descriptions from approximately 5,400 work tickets. Please review and comment. I will be setting up a meeting with Diana, Brian Craig, and you to discuss moving forward.

[11-23-21 Work Order Pick Lists.xlsx](https://docs.google.com/spreadsheets/d/1jn0O6lMb63NCwTo8_w62Yh45Fu8bHLAp/edit?usp=sharing&ouid=109109021747362399747&rtpof=true&sd=true)

**Comment by amenity** [comment]
Discussed using [Optimal Sort](https://www.optimalworkshop.com/optimalsort/) to refine these lists with @johnclary and @dianamartin... This would help ensure that the terms we end up with make sense to the end users.

**Comment by amenity** [comment]
We have a work session on December 8th to define new pick lists.

**Comment by dianamartin** [comment]
# Diana's Notes
- Tracking what work was done
- Time & Effort

Keep Materials/Inventory
Keep Actions on a work order
- Separated

Installed - Material 352 Cabinet - Reset (Y/N)

**Action Items** 
Brian will revamp the spreadsheet format 

## CATEGORIES - "Requester"
- Preventative Maintenance
- Scheduled Work
- Trouble Call - "Maintenance"
- 311 SR
- Active Transportation
- Transportation Engineering
- Vision Zero

**Comment by dianamartin** [comment]
# Diana's Notes - 1/5/22
**Participants**:
- Brian VDW
- Jorge
- Renee
- Brian C
- Billy 
- Diana

## Discussion about 
**Cabinet grounding** 
how many intersections for grounding standards - specs
- Annual?
- Not going to do currently
by signal, Senior Technician or Contractor

Contractors typically do it
- Check grounding 
Bring back information

talked more about adding "Grounding"
- Ended up adding it to the "Cabinets" category

## Actions Items
- AMD team will go over the Actions list and Components list
- Diana will mock up the form for it
- We will meet again in 2 weeks, 1/19

**Comment by amenity** [comment]
Thanks, @dianamartin

**Comment by dianamartin** [comment]
I created mock up of pick list draft in `in TEST | Austin Transportation Data Tracker | 27 OCT 2021` environment.

![image](https://user-images.githubusercontent.com/21112975/148463298-6ddd4de5-0d6a-4cd5-abb1-4f858d1bfdfa.png)

## Action List 
![image](https://user-images.githubusercontent.com/21112975/148463371-b031de8b-c8b8-456a-8eec-01d7f120dea6.png)

## Component List 
WORD Search
![image](https://user-images.githubusercontent.com/21112975/148463014-a2c45acf-4f52-4241-b2b8-1734a6fd79d6.png)

NUMBER Search
![image](https://user-images.githubusercontent.com/21112975/148463045-ba8c5abd-7848-46a2-b1da-4922419d40e2.png)

CATEGORY Search
![image](https://user-images.githubusercontent.com/21112975/148463157-730f0d0a-305d-497a-8f61-25f29b35676c.png)

INLINE EDITING FOR QUANTITY - Defaults to `1`
![image](https://user-images.githubusercontent.com/21112975/148463205-c2dac09d-f03e-446e-a218-3841da4248c7.png)

Will demo at next meeting on 1/19 with stakeholders

**Comment by amenity** [comment]
We anticipate iterating on pick lists as they're used, but @dianamartin feels good about where they are now.

**Comment by amenity** [comment]
These are actually still under review.

**Comment by dianamartin** [comment]
Showed the stakeholders what I had done as far as associating an account to a given component. I showed that it was a high maintenance load for an AMD staff person. I suggested I keep looking into the "workgroup" field to see if I could relate it and have it filter the components list. 

Also discussed the need to: 
- Have "Scheduled Work" as a related table and have the users the ability to add every type of work task to a work order
- Still determining the "Work groups" for the AMD Data Tracker
- Continued discussion about work orders for specific work task and work groups
- Showed them more of the Signs and Markings Work Order System and what type of form a requester fills out

**Comment by dianamartin** [comment]
Stakeholders have not reached out and confirmed they've finalized the pick list, but the creating the general structure of the pick list and actions have been done. They just need refinement and direction to implement when stakeholders are ready.
