### ISSUE TITLE
Update Knack <> Active Directory SSL Certs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3181]
TODO
- [x] HR
- [x] VZA
- [x] AMD Data Tracker
- [x] SMB Data Tracker
- [x] DTS Portal
- [x] RPP
- [x] Finance System
- [x] Shared Mobility
- [x] TDS Tracker
- [x] Street Banners Program Portal

- ?

**Comment by SurbhiBakshi** [comment]
@johnclary @dianamartin - finished updating all the apps listed above, if you think of any others that need to be updated, let me know.
