### ISSUE TITLE
Testing: Microsoft 2 Factor Authentication (2FA)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3189]
Get together with volunteers on 2FA
- [Pre-registration of device](https://account.activedirectory.windowsazure.com/proofup.aspx?proofup=1)

**Comment by dianamartin** [comment]
I emailed all volunteers and send instructions on how we can test. Asked that we test on our own and then we can sync up next week to discuss results and issues we had.

**Comment by amenity** [comment]
Sorry, by the time I got your instructions I'd already set it up — so I didn't pay close attention.

I didn't have to do the URL to register a device beforehand. When I opened O365 after getting back from vacation I got a message along the lines of "your organization wants to have more security" and I _**think**_ there was an option to set it up right away or defer? It worked like 2FA works on other apps/websites  - very quick and easy. I chose to have it text the code to my mobile number.

**Comment by dianamartin** [comment]
@amenity thanks for testing it, I'll mark that you set-up the Text to Mobile Number option.

**Comment by dianamartin** [comment]
Scott responded saying he's set his up - MS Authenticator app
Amenity - configured sending security code via text to access MS 2FA

**Comment by SurbhiBakshi** [comment]
@dianamartin - I set up the MS Authenticator App as well.

**Comment by mddilley** [comment]
@dianamartin - I was prompted to set up 2FA through the macOS Outlook app on 06/30/2020, and I set it up with my personal mobile. Very quick and easy.

**Comment by sergiogcx** [comment]
@dianamartin I set up 2FA on my phone with the Windows Authenticator app, it was very easy.

**Comment by johnclary** [comment]
Thanks y'all. I'm closing this.
