### ISSUE TITLE
DTS Team Huddle

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3196]
Scheduled huddle meeting on 7/7

**Comment by dianamartin** [comment]
## Diana's Notes
### Sign Data Capture
- TED: Speed limit signs, mph, point
- Collector easy to use and set-up
- Quick capture: use cases to select a sign
  - collect line data, level of comfort
  - usability better? doesn't allow for 
   - Fine tuning abilities: Collector preferred
- ACTION ITEM: Alan to meet with Lee A & Christina (optional: me)
 
### Work Order Tracking
- group sign locations (multiple sign locations) 
- single work order

### Street Width Data Capture 
- One off, not all streets
- Only in certain situations
