### ISSUE TITLE
Complie existing speed limit data

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#320]
### Background #### 
The speed limit data was gathered by ATD GIS staff from the MUNI code a couple of years ago was added to the CTN about a year ago. Currently, 13% of all on-street segments of the CTN contain a speed limit from the MUNI code audit.

### Next steps ###

Some of the gaps may be easy to fill by look at NULL segments that are adjacent on both sides by segments with speed limit data. This is fairly common on several arterials.

Other easy to fill gaps exist in neighborhoods in which there are streets of the same level (usually 1 or 2) that have speed limit data and others that don't.

Manually filling in these gaps in the data in high priority areas ( streets on the high injury network, streets with near-future bike/ped improvements, neighborhoods surrounding schools) may be feasible while we wait on data purchases and other bulk solutions.

Tasks for Frank could include:

- [x] QA speed limit data found in CTN to the MUNI code
- [x] Fill in missing arterial speed limit data
- [x] Fill in missing speed limit data in neighborhood streets.

**Comment by johnclary** [comment]
We gave Frank a link to the segment data, and we was going to create a dataset with speed limits by segment.

@alan-deanda would you check in with Frank and see where he's at?

**Comment by alan-deanda** [comment]
update from Frank:

1st) Getting the ordinances mapped where there is a feature created for each ordinance. This was done from the latest TIGER line files, because I was unable to find a road network used by the city that didn’t have all streets segmented into individual features at each intersection. Since I had just under 4,000 ordinances to map, being able to select a street in one go was central to being able to get this done in a timely manner. This task is complete, and I have a shapefile with the road being described in the ordinance represented as a MultiLineSegment / Polyline and other related information such as the speed limit and other flags stored in the attribute table for the shapes. 

2nd) Integrating this data with existing ATD maps. This is a tricky problem, and I have been able to write a program that gets almost all the way there, but I have been assigned to work on some other projects in the meantime, so it’s not 100% complete. 
a)	The silver-bullet would be to finish my work that finds the street segments that match up to the feature from the ordinance and collect all the vertices in the same topography as they appear in the target road network, add vertices only where needed (such as where a speed limit starts in between intersections), and creates another 4000 features that are congruent to the target street network. There is some real magic in this – there are inevitably some roads that exist in one network and that do not in the other as well as subtle differences, such as using two lines for a divided roadway or not. It’s these last issues of this type which remain unresolved, but overall, the program has potential in my opinion – but not to say it’s an easy problem, and I do anticipate there will be some work to get it over the finish line. 
b)	The above solution, however, isn’t immediately helpful in doing the analysis that Vision Zero team was seeking. That work involved coming up with certain breakdowns of how many road-miles existed at various street levels inside the city and also inside a particular polygon of the Austin Urban Core. For this, I needed to assign every street segment of an ATD road network a speed, and because some speed limits overlap and other complications, I needed to come up with a way to aggregate the city’s ordinances and apply them to a whole map of the city – producing the original road network with additional data, and not the 4000 ordinances. For this, I iterated over every segment of the target road network and matched it against the lowest, congruent ordinance and gave the segment the appropriate speed limit. I also noted if a speed limit was explicitly assigned or if it was inherited from the prima facie regulation. I have this completed for the ASMP street network.

**Comment by johnclary** [comment]
@alan-deanda would you confirm if Frank has joined his data to the COA street segments?

**Comment by johnclary** [comment]
@JaceDeloney would you let us know where Frank's at with the speed limit data? We're waiting on it for a few projects.

**Comment by JaceDeloney** [comment]
Assigning this to me until we get the dataset from Frank

**Comment by johnclary** [comment]
Done. See here: https://github.com/cityofaustin/atd-vz-data/issues/571
