### ISSUE TITLE
DevOps (Test to Prod) - ROW Performance Measure Report

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3203]
This is the deployment card for #1872

**Comment by Nadin-Nader** [comment]
**STATUS:**
With CTM SCTASK0078266 for deployment to PROD. Waiting for deployment

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  @TracyLinder Gita has deployed this to PROD 7/7/2020. Closing Card
