### ISSUE TITLE
Updates to the monthly trips table

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3207]
The Shared Mobility Services Team and Ride Report would like to view and compare the monthly trip numbers from the following three sources:

- CoA Total Trips 
- Ride Report Total Trips
- Provider-Reported Total Trips

Additionally, the Shared Mobility Services Team would like to record which monthly trip number source was chosen as the official number that is used in the monthly per-trip fee invoices.

Make the following changes to the current monthly trip table:
- [x] Change the title of the monthly trips table from `Monthly Trips` to `CoA Monthly Trip Stats`
- [x] Move the `CoA Total Trips` column to the far right side of the Monthly Trips table (we want to keep this column in the table)

Create a new table:
- [x] Create a new `Monthly Trip Comparison` table. This table should be directly above the existing monthly trips table.
- [x] Add `Provider Name`, `Year`, and `Month` columns
- [x] Add a `CoA Total Trips` column. This column should be populated by the same data in the `CoA Total Trips` column in the `CoA Monthly Trip Stats` table
- [x] Add a new `Ride Report Total Trips` column on the right side of the `CoA Total Trips` column. This column should be editable by Shared Mobility Services Team members. 
- [x] Add a new `Provider-Reported Total Trips` column on the right side of the `Ride Report Total Trips` column. This column should be editable by Shared Mobility Services Team members. 
- [x] Add a new `Official Total Trips` column on the far right side of the Monthly Trips table. Users should be able to select one of the three monthly trip number sources as the official total trip number. It would be nice if this could be selected via a dropdown selector of the three trip sources.

**Comment by SurbhiBakshi** [comment]
@JaceDeloney - these updates are done.
