### ISSUE TITLE
DevOps (DEV to Test) - Mitigation Fees (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3214]
### Sangeeta approved this work to go to Prod on 7/16/20. With #1729

**Comment by TracyLinder** [comment]
@Nadin-Nader I just put this on deck for you.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  CTM Task for this is: SCTASK0084060 its in their To-Do Pipeline
