### ISSUE TITLE
Watch Demos & Provide Feedback - TIA Folder Updates

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3216]
Demos were sent to us on 6/19

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder Demo looks good and meets the acceptance criteria.
Review from Demo:

 At initial folder setup/creation, the status should be Pending
 After fees have been billed, the status should be Pending Payment
- Option: Use 'Calculate Fees' attempt on Initial Intake, this would add any missing fees and create one bill for all fees on fee tab. First we'd need to make sure the system isn't adding unnecessary fees. Then folder status would update to Pending Payment
 Currently, "Entered" attempt checks if the completeness check fees have been paid, and closes the attempt.
 Fees must be paid before or at the time of the first TIA submittal. Once, for two fees: TIA scoping fee and TIA review fee, as they are billed together
 After fees have been paid, the status should be Paid. This should not require user action.
 Any unpaid fees, a Hard stop error will be thrown notifying reviewer that there are unpaid fees.
 After the memo is approved, the status should be Approved
 Saving 'Approved' attempt on TIA Case Manager review process currently issues the folder, and updates status to Approved & Released.

**Comment by Nadin-Nader** [comment]
Reviewed demos. Closing card
