### ISSUE TITLE
VZ Socrata ETL | Remove unused columns from VZ datasets

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#3217]
Unused columns like the mode flags that were replaced with the mode fatal/serious injury count columns remain in the test and production crash and demographics datasets. Removing these columns would make datasets easier to navigate, reduce confusion when developing against them, and remove code that no longer needs to be maintained.

- [ ] Ensure the flags are not used anywhere in VZV
- [ ] Remove the methods in the ETL Python code that transform data to populate these columns 
- [ ] Remove the columns from the test and production datasets

<img width="682" alt="Screen Shot 2020-06-30 at 5 08 40 PM" src="https://user-images.githubusercontent.com/37249039/86266307-a406a000-bb8a-11ea-8060-3e333e81742a.png">

**Comment by patrickm02L** [comment]
After review, we determined that this dataset power VZV. General public may rely on these field, therefore it's not appropriate to remove.
