### ISSUE TITLE
Meet with Linda to Discuss Uniform Tracking Request

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#322]
At Linda's request, we talked briefly regarding a uniform tracking solution. Intake form responses below. 

Based on our conversation, we would want to consider incorporating the tracking of not just uniforms, but also personal protective equipment (PPE), e.g., hard hats, boots, etc. 

It strikes me that this should probably be scoped into a phase of the warehouse inventory project. 

Next steps: email Linda and CC Peggy to confirm we've documented the need. Linda is going to follow-up after gauging feedback/interest from division managers. 

My initial thought is that, yes, we can build a tool for this, but it will be difficult to drive adoption by division managers without a mandate from an executive. Currently lacking sponsorship.

#### Challenge

> Approximately 130 employees receive city-issued uniforms (approximately 4 to 10 items) annually or twice a year through various division methods.  Some items must be returned upon separation from the City or transfer to a different department.  Some items can be replaced based on division requirements.

#### Request
> A database linked to the employee's PIDM that explains issuance and replacement requirements, dates and tracks the transactions, and allows an electronic signature and dating by employee and supervisor.

#### Success measures

> Is used biannually and annual for employee population required to wear uniforms; assists with budget projections; assists with separations, terminations, and transfers of employees;, and tracks trends. 

#### Describe any workarounds currently in place and/or alternative solutions you have considered.

> Spreadsheets

#### How have other divisions/departments/cities addressed similar challenges? *

> Don't know but will explore at meeting next week

#### Users

> ROW, Arterial, Signs & Markings, and Parking Enforcement

#### Stakeholders

> Division Managers or an assigned person from above divisions

#### Executive sponsor

> Don't know but will explore at a meeting next week

#### How would you rate the impact of this application?

> Unsure

#### Would this application affect any of the Strategic Direction 2023 “Mobility” indicators?

> Safety

> Condition of transportation-related infrastructure

#### Would this application support any of the Austin Strategic Mobility Plan goals?

> Sustainability — Promote integrated designs and quality additions to the built environment while 

#### If it is critical that this is delivered by a certain date, when and why?

> Don't know but will explore at meeting next week

#### What else should we know?

> Create a management tool that provides efficiency for division managers

**Comment by johnclary** [comment]
@dianamartin @amenity FYI

**Comment by johnclary** [comment]
@dianamartin @amenity another FYI: i created an index issue under "projects to be scoped" for this: https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/323

**Comment by dianamartin** [comment]
:+1:
