### ISSUE TITLE
Re-estabilish daily process for pulling in CR3 records

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3228]
Restart the daily ETL process for pulling in Crash data into VZD. Reach out to CRIS via email and get the SFTP set up.

**Comment by sergiogcx** [comment]
Closing. This is active as of yesterday:

![2020-07-07_15-33-55.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/dad83d0c-8471-459a-88ee-02c7b97b300a)
