### ISSUE TITLE
IT Service Desk Work Flow

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3238]
### Objective 
Review options for streamlining Service Request
Meeting scheduled 7/13/20

Follow up to #(https://github.com/cityofaustin/atd-data-tech/issues/3127)

### Participants
John, Diana, Surbhi, Jamie, Scott, Stephanie

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [x] Optional: Schedule debrief
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by moorerst** [comment]
Sample knowledge articles for CTM Service Desk  to direct users to other Service Request forms

https://atx.service-now.com/nav_to.do?uri=%2Fkb_view.do%3Fsys_kb_id%3D69c9ce7fdb5488d0c56254f9489619ae%26sysparm_rank%3D1%26sysparm_tsqueryId%3De02e1beb1bb5d490f4da55392a4bcbeb

https://atx.service-now.com/nav_to.do?uri=%2Fkb_view.do%3Fsys_kb_id%3Db425ba651b4f0414a7951f861a4bcb3e%26sysparm_rank%3D1%26sysparm_tsqueryId%3Da6ee13231bf5d490f4da55392a4bcb70


ATD: Submit Service Request Form
KB######  -  Latest Version
14 views
Introduction
Need to submit the ATD Service Request Form to report a problem or request service for ATD Data and Technology Services (DTS)

 
Instructions
This knowledge article is intended as Self Help Reference/Resolution for all ATD Users for specific issues/request.

 

Assumptions:

You are a ATD employee
You need assistance with specific issues and request supported by DTS

Steps:

Click this link to access the ATD Service Request Form
URL: https://atd.knack.com/dts#new-service-request/
Complete all required information
Click the Submit Request button 
Once submitted, **detail next steps and expectations**

**Comment by dianamartin** [comment]
## ATD Knowledge Base Articles
- [Knowledge Article for ATD IT specific issues](https://docs.google.com/document/d/1yJHldeQXgF6G6HWSXq9Ndcx8miZ2SsDYqHd0ei3c7iQ/edit)
- [Knowledge Article to direct customers to complete a different Service Request Form](https://docs.google.com/document/d/1cMh3WHP-cuycv3qeU879BiCRpcYsWHFYLpNQWAUFkYY/edit)

**Comment by moorerst** [comment]
Reviewed the various options for creating knowledge articles using the above 
Goal is for more of the triage to happen within the DTS Service Desk by having CTM Service Desk direct ATD users to the DTS Service Request form for issues that cannot be resolved by CTM

Work Flow
- When the ATD user contacts the CTM SD the SD will review knowledge articles for handling ATD user support
- If the user issue is not a issue that can be resolved by CTM they will direct the user to complete the DTS Service Request form
- When the user completes the DTS Service Request form a email notification will go to the appropriate DTS support person or the data.transporation mailbox based on the Category selected by the user
- If the DTS SD needs assistance from CTM they will open a Service Desk IT Support Form in SN using the Submitted By and Requested For fields

Action Items
- [ ] create knowledge articles - coordinate with CTM KB Admins (Jeff and Adam)
- [ ] provide Surbhi with the SN routing table in excel format

**Comment by moorerst** [comment]
@SurbhiBakshi  here is the Service Now routing chart with SN Group Names and Description
[Service Now Incident Routing Chart.xlsx](https://github.com/cityofaustin/atd-data-tech/files/4919728/Service.Now.Incident.Routing.Chart.xlsx)

**Comment by SurbhiBakshi** [comment]
thanks! @moorerst
