### ISSUE TITLE
Feature request: Supervisor to edit TLC records after making an approval decision

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3245]
## As a Supervisor I want the ability to edit my approval in case I made a mistake so that I don't have to ask DTS to change records for me on the back end. 

Ex. If I approved a staff person and meant to click "Not Approve".

**Comment by dianamartin** [comment]
## Edit Details of record when Supervisor is going to sign form
![image](https://user-images.githubusercontent.com/21112975/86839316-e2a6c980-c066-11ea-8050-8c22f882c6a9.png)

### Example of Edit TLC Request form
![image](https://user-images.githubusercontent.com/21112975/86839482-197cdf80-c067-11ea-8e1c-67b4e916b7e4.png)

## Review Details of record that has been reviewed
- Added `details` page for record that has been "Previously Reviewed"
### Example of Details icon on Previously Reviewed table
![image](https://user-images.githubusercontent.com/21112975/86838499-de2de100-c065-11ea-9093-ecf8c928feb2.png)

### Example of Details Page 
![image](https://user-images.githubusercontent.com/21112975/86838672-12090680-c066-11ea-99a7-dcad423885c5.png)

**Comment by dianamartin** [comment]
John took a look at it and made a few suggestions. Re-working the forms to meet the needs of the user to be able to edit the requested information as well as fix any approve mistakes on their end.

**Comment by amenity** [comment]
@johnclary - would you review, please?

**Comment by johnclary** [comment]
just did. looks great. closing this.
