### ISSUE TITLE
Refinements based on 7/6 Huddle

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3248]
Sign Up 
- [x] Move the full calendar to the bottom
- [x] Replace 👆with a "My Assignments" calendar that only shows the logged in Officer's assignments. Hoping that this will help them quickly correct if they sign up for multiple assignments at the same time. 
- [x] Show only the "Next Week" "Next Month" filters
- [x] [Dev issue to add checkboxes to sign up for all Assignments in a given Shifts](https://github.com/cityofaustin/atd-data-tech/issues/3249)

**Comment by amenity** [comment]
@amenity - create issue for Devs and get on their Backlog Grooming agenda

**Comment by SurbhiBakshi** [comment]
@amenity - made the changes. Still think I need to refine the terminology used for the heading to make them more reader friendly. Using two different shades of blue (section 508 compliant!) to show morning versus afternoon shifts. Going to think about the group headings a little more, but changes listed above are done, if you want to review. 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/204bf52c-1ab4-4cfa-a782-3d75ca542221)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/1bfb57f8-0f02-4103-ab95-bda70adf0ed8)

**Comment by amenity** [comment]
Looking so good, @SurbhiBakshi. A couple things:
- I'm seeing a scroll bar in addition to pagination. Can we do one or the other?
<img width="1197" alt="Screen Shot 2020-07-08 at 1 04 37 AM" src="https://user-images.githubusercontent.com/1463708/86884090-a8661800-c0b8-11ea-8687-d9ec831eb347.png">

- I like the idea of a visual affordance to help officers scan for morning or afternoon shifts, but I don't find the meaning of the different colors intuitive enough to be worth adding complexity to the UI. I'm down to test with the officers and see how it goes, but we will need to replace the darker blue with something lighter so we have more contrast.* 
-

**Comment by SurbhiBakshi** [comment]
@amenity
- I reduced the number of records shown by the table to 10, the scroll bar is not needed, and that should take care of the header flashing as well. 
- Renamed APD Sector to Sector
- For the rest, I am not too set on the colors, but I personally don't like too many colors on a page. Let's see what Mike tells us and based on what is possible with the Sign Up table, move from there. 
- I also wonder if having separate tables for Morning, Afternoon and Evening assignments would work. I wish there was a way to add links to section within a page in Knack and have those links at the top of the page. Think that would help officers look at the time they preferred.

**Comment by amenity** [comment]
@SurbhiBakshi Ooh, that's an interesting idea. I'm sure there's some custom code out there for anchor links... 🤔

Gonna call this closed. Thank you!

**Comment by amenity** [comment]
Here we go: https://support.knack.com/hc/en-us/community/posts/360019057811-Anchor-Links

**Comment by SurbhiBakshi** [comment]
Know this issue is closed, but thanks! @amenity - definitely want to explore the anchor links in the near future!
