### ISSUE TITLE
Customizations to improve Vision Zero in Action Officer workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3249]
We're building the  [Vision Zero in Action](https://github.com/cityofaustin/atd-data-tech/issues/145) app so that ATD staff can efficiently schedule Vision Zero in Action shifts*, APD officers can sign up for shifts and track their activities while on shift, and APD administrative staff can perform invoicing for this work. 
  
Lewis is currently using VZA App 1.0 to schedule Vision Zero in Action shifts* and has happily tossed out his spreadsheets in favor of Knack. 

VZA 2.0 will add an interface for APD officers to sign up for this overtime work. Some terminology:
- An officer signs up in increments of  **Shifts**. These are designated as _Morning_, _Afternoon_, and _Evening_. 
- Multiple (usually 2) officers work on the same shift as a **Team**. We call these "Team 1", "Team 2", and "Team 3".
- In a given Shift, there are 2-3 **Assignments**. Each Assignment is at a different location. 
- Multiple **Teams** can work on Shifts in different areas simultaneously. 

This is how that looks on a calendar:
<img width="992" alt="Screen Shot 2020-07-08 at 4 31 39 AM" src="https://user-images.githubusercontent.com/1463708/86902732-f76d7680-c0d3-11ea-8f26-fb0c17c21222.png">

The data structure that we landed on in Knack should represent each individual officer's Assignment as children of a parent Assignment. The Shift and Team is then stored as a field on the Assignment itself. [@SurbhiBakshi - can you correct/expand upon this?]. By default, that makes for a kind of confusing interface for officers:
<img width="929" alt="Screen Shot 2020-07-08 at 4 14 29 AM" src="https://user-images.githubusercontent.com/1463708/86902495-a78eaf80-c0d3-11ea-8896-7e5555ac9c13.png">

Concerns that came up during our user feedback session:
 - Officers are supposed to sign up for sets of Assignments, e.g. an entire Shift. This makes it look like they are able to do one 2 hour shift by itself. So we need to group the Assignments into Shifts and have the Officer sign up for them all. Surbhi did a lot of customizations to make it easier to see this grouping, but it still relies on training the officers to sign up for everything in a Shift:
<img width="952" alt="Screen Shot 2020-07-08 at 4 40 30 AM" src="https://user-images.githubusercontent.com/1463708/86903596-2c2dfd80-c0d5-11ea-868b-e6728f81a3f5.png">

So we'd like to hide the individual sign up icons on the Assignments, and add a sign up button for the Shift. I've mocked up a few options [here](https://docs.google.com/spreadsheets/d/1obi7JUZzlPpwft7eDD7TkmP2OxZrYOMuY06NJsLkPcA/edit#gid=1738822239). We're not completely attached to a particular solution but hope to work with you to determine which is most feasible. 

Surbhi found [Knack code to add checkboxes to a table](https://www.knack.com/developer-documentation/#add-checkboxes-to-a-table) that might work for this purpose. 

*Officers patrol with a special eye towards dangerous traffic infractions and areas with potential danger.

**Comment by amenity** [comment]
@SurbhiBakshi @johnclary I was having hard time figuring out what we should request in terms of design. Starting with screenshots of what's in Knack and using Figma was not efficient, so I ended up mocking up some ideas in Google Sheets:
- [This is the one we discussed asking for](https://docs.google.com/spreadsheets/d/1obi7JUZzlPpwft7eDD7TkmP2OxZrYOMuY06NJsLkPcA/edit#gid=1738822239)
- Here are a couple I wanted to throw out there in case it's possible to group assignments by Shift and Team so that they only appear once: [Option 1](https://docs.google.com/spreadsheets/d/1obi7JUZzlPpwft7eDD7TkmP2OxZrYOMuY06NJsLkPcA/edit#gid=1477352046), [Option 2](https://docs.google.com/spreadsheets/d/1obi7JUZzlPpwft7eDD7TkmP2OxZrYOMuY06NJsLkPcA/edit#gid=0)
- Finally, I played with some different formatting that _should_ be fairly straightforward to implement with CSS... [Option 1](https://docs.google.com/spreadsheets/d/1obi7JUZzlPpwft7eDD7TkmP2OxZrYOMuY06NJsLkPcA/edit#gid=416560963), [Option 2](https://docs.google.com/spreadsheets/d/1obi7JUZzlPpwft7eDD7TkmP2OxZrYOMuY06NJsLkPcA/edit#gid=1623359487)...

Thoughts?

**Comment by SurbhiBakshi** [comment]
officer_assignments (object)- 12
Sign Up (scene) -  208
Available Assignment (view) - 466

**Comment by johnclary** [comment]
I like the "Reformat 2" tab on the spreadsheet.

**Comment by SurbhiBakshi** [comment]
I prefer the "One sign-up button per shift per officer" option because hopefully that will remove any confusion, by showing the officers that there are two slots for each shifts. Officers won't be thrown by seeing the same shift option again.
