### ISSUE TITLE
LM Click Map - Update LM Map Across All Sub-Types

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3254]
### As an LM applicant, I need to be able to add multiple properties, and have the option to add segments if needed or to skip adding segments. 

**Stakeholders:** Arthur, Melissa

**Acceptance Criteria:**
- The map-viewer that's currently in test for the License Agreement sub-type is applied to all LM folder sub & work types. (7/27/20)

**Comment by TracyLinder** [comment]
Sean M created the correct map view, so now Unisys is getting it promoted to Test.

**Comment by TracyLinder** [comment]
### UAT Results 7/27/20


- License Agreement sub-type still asking for segments, but they liked the updated workflow
- Encroachment not asking for segments
- Easement release & ROW Vacation have **no map at all**

**Customers would like the map that's on the License Agreement sub-type to be applied to all LM application types.**

**Comment by TracyLinder** [comment]
![image](https://user-images.githubusercontent.com/49930868/88567762-8992db80-cffd-11ea-809f-b07e7c2c05ec.png)

**Comment by TracyLinder** [comment]
Acceptance criteria has been updated

**Comment by johnclary** [comment]
@TracyLinder follow up with Sean Mc.

**Comment by TracyLinder** [comment]
Will be meeting w/ Unisys on 10/6 to figure out what's going on with this one.
