### ISSUE TITLE
Feature request: Move Help Guide content from GitHub to Knack

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3259]
Diana 
DTS

Requesting to change the `Help Guide` tab to not the big button that points to a [GitHub](https://github.com/cityofaustin/atd-knack-development-review/wiki/Transportation-Development-Services-Help-Guide) page, but rather the data is embedded into the `Help` page of knack. 

Reference Help pages: 
- [HR help](https://atd.knack.com/hr#help/)
- [RPP help](https://atd.knack.com/parking#help/)

**Comment by dianamartin** [comment]
Sync'd up and we talked about these things: 

- [ ] Need to change some headings
- [ ] Bold Field names
- [ ] Remove "Required" fields and "astrisks"
- [ ] Link anything that need to be linked, don't show the entire URL

**Comment by ChrispinP** [comment]
Completed final Help Guide adjustments listed above. Tested links. Page is active.

Should we 
- [ ] hide, 
- [ ] remove, or 
- [ ] legacy(keep showing for a duration) 
the help guide button that redirects to github?

**Comment by dianamartin** [comment]
@ChrispinP we'll need to:
- [ ] go into GitHub and delete that page
- [ ] remove the "rich text" widget
- [ ] remove the .js for the big button

**Comment by ChrispinP** [comment]
@dianamartin is there a separate location where the javascript file for the button is located?

Github page and rich text widget removed.

**Comment by dianamartin** [comment]
@ChrispinP GitHub Repo for [tds.js](https://github.com/cityofaustin/atd-knack/blob/master/code/transportation-development-services/tds.js)

**Comment by ChrispinP** [comment]
- js and css files copied from TDS Knack Production app to atd-knack repo
- removed 'view_81' js function for Help Guide big button from app
