### ISSUE TITLE
Update Python Scripts: "hazard_flashers_agol" and "hazard_flashers_socrata"

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3260]
Follow up from issue #3172

- knack object was updated from `hazard_flashers` to `flashing_beacons`
- socrata data set was updated from `hazard_flashers` to `flashing_beacons`
- agol feature layer and service definition were updated from `hazard_flashers` to `flashing_beacons`

The scripts broke because the `ATD_FLASHER_ID` was renamed to `ATD_BEACON_ID`. 
- Both scripts need to be updated to reflect the ID name change

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/042b006a-9701-4c50-96f1-2a60d99c0283)

**Comment by ChristinaTremel** [comment]
@johnclary and @dianamartin was this completed? It looks like the ODP Flashing Beacons dataset is functioning.

**Comment by dianamartin** [comment]
@ChristinaTremel It's the AGOL feature data layer

**Comment by ChristinaTremel** [comment]
The AGOL feature data layer is also functioning and I'm able to see the ATD_BEACON_ID on the flashing_beacons layer!

**Comment by dianamartin** [comment]
@ChristinaTremel If this looks right, we can for sure close this

**Comment by ChristinaTremel** [comment]
The flashing beacon datasets in AGOL and ODP are working! Closing this issue.
