### ISSUE TITLE
Coordinate app publishing to Apple App Store for Smart Mobility wayfinding app

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#328]
@johnclary received a request from Kirk S with Smart Mobility to coordinate publishing of a vendor-built iPhone app. 

We need to help deploy the app to the Apple App Store. At this point, we're wondering if it makes sense for us to use the main CoA App Publisher account or for ATD to enroll in the Apple Developer Program as we foresee more situations like this on the horizon. 

First step is to check Apple App Developer requirements and kick off conversation with BS at 311 who manages the CoA account.

**Comment by mateoclarke** [comment]
From BS:

> There were (and probably still are) a couple of reasons the account is set up the way it is currently:
> 
> 1. For “City of Austin, Texas” Apple considers the account we originally set up to be the “main” account for the city. We did not set out to make it the only one – this was something we found when APD came forward to ask for help with their app several years ago. Both the 3-1-1 and APD app have been under the main account for several years.
> 
> 2. Apple is very strict with certain functions and roles, and they required (and still require) an agent with authority to bind the city to agreements with Apple. Our legal review at the time led to this role being filled by a deputy procurement officer
> 
> I believe that if ATD wants to set up a separate account you should be able to pursue this. One thing that may help – do you know what led Passport to the need to migrate the Park ATX app site to the account? I think they noted something about labeling, so it may help to know specifically what they ran into that led to the recent changes.
> 
> Apple will probably want to have the account say something that is different than just City of Austin – hopefully they would go for “City of Austin Transportation” or something similar. The hardest part for us once we got the legal items in the clear was to find someone who was able to satisfy Apple’s guidelines.
> 
> I recommend if you want to pursue this to start with a conversation with Apple from the developer’s website. I usually end up with a senior advisor whenever I ask for help as they only discuss certain items with the “agent” but at the senior level I have been more successful to get enough guidance to assist as needed.
> 
> On the developer website it has a contact us link that prompts for the user to sign into their account or to create one if needed. Apple support will call you (no phone numbers given these days) but the callback is usually within a couple of minutes.
> 
> https://developer.apple.com/programs/
> 
> Please let me know if this helps, and if you want to set up a discussion or need anything either way – thanks.

**Comment by mateoclarke** [comment]
We're going to move forward and try to work w/ BS & the Smart Mobility ppl and their vendor to get the app published via the centralized account. Currently, the ball is in Clay's (from the app dev company) court.

**Comment by mateoclarke** [comment]
Haven't heard anything on this. @johnclary should I poke them? I'd prefer to let them drive this but I don't want something to go wrong with ITE next week and their app not getting published in time.

**Comment by johnclary** [comment]
Thanks for flagging. I let Clay know we're dropping this:

> Clay, since we haven't heard from you, we're going to close this issue. Given the short deadline and our limited bandwidth, we won't be able to have this in place for you in time for the ITE conference next week

**Comment by mateoclarke** [comment]
closing this...
