### ISSUE TITLE
Setup Speed Limit Sign Data Collector App

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3289]

**Comment by amenity** [comment]
@johnclary - I'd like to go through this project with you and SMB before you leave. It sounds like some of the issues aren't obsolete. If you think it's going to need lots of Knack work, we can loop in Chia!

**Comment by dianamartin** [comment]
@alan-deanda @andrewshensky Is this epic good to close?

**Comment by ChristinaTremel** [comment]
Confirmed with Andrew that we're good to close this. A Web Map was built for this project.
