### ISSUE TITLE
Meet with SMB and TED to Define Collector Requirements

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3290]

**Comment by johnclary** [comment]
@alan-deanda please schedule ASAP with Lee A, Dipti B, Allison M, Christina T, and Diana. Thanks!

**Comment by dianamartin** [comment]
## Pre-Meeting Notes 
Scheduled at 7/14/2020

### Participants
Alan, Christina, Diana

### Notes
- [ ] Signs Assets - 
  - Fields to Collect: 
   - `sign_message`: Example: `35 mph`
   - `asset_category`: Default (`Regulatory`)
   - `asset_name`: Example: `Speed Limit`
   - `asset_status`: `proposed`, `active`, `inactive`
   - `asset_condition`:
- [ ] Reference Points: Maximo Signs (Speed limit signs only)
- [ ] Sign Maintenance Areas: QC layer (lives on AGOL)
  - Nelson E. is main contact for QC'ing project

### Questions to TED
- See whether or not they want to collect future sign locations or current sign locations
- Ask about sign status
- What is your proposed process? Collect "current" signs in field? Add "future" signs in the office?

### Proposed Field Data Plan TED
- Set up AGOL Collector Web map
- reference layers
- new layer for sign asset collection
- QC layer for Sign Maintenance Area
- QC point of contact: Nelson E.?
  - How many areas have been checked
  - Training: Nelson (how to manage use QC layer)

**Comment by dianamartin** [comment]
## Diana's Notes 

### Participants
Lee A., Nelson E., Dipti, Christina, Alan and Diana

### Questions for TED
- Lee: Just wants to get it done
- Dipti: Urban arterials 40 --> 35, 35 --> 30 
- Capture of the work order
- Dig Tess

- Obstacles: Don't have all the speed limit signs 

## What is the Process?
- Google Street View
- Drive it, ensure signs still out there
- Each sign and dropping a point

Drop Down
- `Replaced`, `

## Categories 
- Downtown
- Urban Arterials
- Neighborhood Speed Limits

## Sign Inventory - Nice to have, not a priority
- 30 mph - long term goal
- How to get 

## Early January 2021
- Before doing the work for neighborhood
-
