### ISSUE TITLE
Serve as GIS Duty Officer - COVID-19 Response

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3292]
GISERT COVID-19 Duty Officer on 7/9/20.

**Comment by jaime-mckeown** [comment]
The request for my access that Dwayne submitted still has not been completed. Let Dwayne know.

**Comment by jaime-mckeown** [comment]
Got everything working yesterday. Discovered that my position is incorrect for WebEOC Login, waiting to hear back from Cindy W. for how to proceed.

**Comment by jaime-mckeown** [comment]
Cindy was able to fix my position for logging in. Logged in successfully and have been monitoring the different areas for requests.
