### ISSUE TITLE
EX Folder Permit Report Updates (Multiple) 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3293]
### As a ROW permit stakeholder, I need all permit information visible on the permit. Currently contractors with long names are being cut off on the report.

**Stakeholder:** Ryan M, Kim P
**DTS Manager:** TBD

**Acceptance Criteria:**
- Add word wrap to the contractor name fields so the info no longer cuts off. 
- Add word wrap to contact field so info doesn't cut off
- Change word 'House' to 'Block'
- Delete 'Cross Street', 'Between', 'Cross Street 2'
- For all sections, don't take up a lot of room with empty space

**See attached w/ Kim's comments** [Attachment](https://app.zenhub.com/files/140626918/55781962-7aa6-4f08-bfce-6c4028ca7023/download)

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/7167836d-bbf1-49b6-a2f9-9d51600eeb69)

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan I just added this for LaunchIT to work on during the next sprint (29).

**Comment by TracyLinder** [comment]
**Status:** Sree sent DEV deployment this morning. Updating to sprint 30.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder  new reports has been uploaded to DEV (50510_f_Right_of_Way_Excavation_Permit_Dev)

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Testing will be completed by EOD.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Tested in DEV environment. Please review and Approve for TEST move.

**Comment by TracyLinder** [comment]
@TracyLinder will need to add good test data to DEV & finish testing this.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan I've tested this; please see screenshot below. There's still one container that's overflowing:

![image](https://user-images.githubusercontent.com/49930868/89826998-aca0ad80-db1c-11ea-8bb5-b4f4f2b879d4.png)

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - I have tested in DEV. Kindly test it and let me know your views. Thank you!

[50510_f_Right_of_Way_Excavation_Permit_Prod.rpt 08112020.pdf](https://github.com/cityofaustin/atd-data-tech/files/5059314/50510_f_Right_of_Way_Excavation_Permit_Prod.rpt.08112020.pdf)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I tested this on DEV and it looks right

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan that looks good. Please promote up. 
Thanks!

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have deployed this to DEV and TEST.

**Comment by TracyLinder** [comment]
We just tested this in TEST, and it' isn't working as expected, and looks different than the report in DEV. 
TEST RSN 2301353
[https://app.zenhub.com/files/140626918/41b25621-46cd-43b4-83b0-eb13dbb703d2/download](https://app.zenhub.com/files/140626918/41b25621-46cd-43b4-83b0-eb13dbb703d2/download

@Nadin-Nader @Sreelatha-BlazeKannan

**Comment by TracyLinder** [comment]
### Update

- It seems the bug i described in my last comment is only happening with that folder; I can't replicate it.
- The 'Location Description' is still taking up a whole page, see Test RSNs: 12388517, 12394737

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Recreated the issue in DEV and Corrected the same. Sent the updated report and DP to Nadin for DEV & TEST Deployment.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder i have deployed the form to both DEV and TEST.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Tested this in DEV & TEST environments and working as expected. 

![image](https://user-images.githubusercontent.com/44907715/90550976-4e944b80-e156-11ea-951c-8725b3bcef12.png)


![image](https://user-images.githubusercontent.com/44907715/90551029-610e8500-e156-11ea-9f09-1ee1a269c64b.png)

No additional Page in Location Description.  Report is ready for UAT

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan i just tested and it looks great.

### Approved to promote to PROD. 🎉

**Comment by TracyLinder** [comment]
Sree will send Prod plan tomorrow 8/27

**Comment by TracyLinder** [comment]
Status: Nate will submit deployment plan today.

**Comment by Nadin-Nader** [comment]
@TracyLinder @Sreelatha-BlazeKannan This has been sent to CTM Tango to be deployed under TASK SCTASK0093585.

**Status:**
Waiting on CTM Tango to deploy to PROD

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been deployed to PROD per CTM Tango. Sending email to Ryan, Paloma and Kim and close the card

**Comment by Nadin-Nader** [comment]
From: Nader, Nadin 
Sent: Tuesday, September 8, 2020 12:48 PM
To: Mooney, Ryan <Ryan.Mooney@austintexas.gov>; Perez, Kimberly <Kimberly.Perez@austintexas.gov>; Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>
Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>; Sreelatha.b@launchitcorp.com
Subject: EX Folder Permit Report Updates (Multiple) #3293

Hi Everyone,

Hope you are doing well. I am reaching out to you regarding Issues 3293 EX Folder Permit Report Updates (Multiple). The permit is now on PROD. Please go ahead and let us know if anything else is needed. I will now close the card

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department
