### ISSUE TITLE
Meeting | Biweekly Update 

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#3300]
[Document](https://docs.google.com/document/d/1t8bOUNy42AAFpI0aTdVa4htRUgcgBMw4_uyYORSIlVs/edit?usp=sharing)

**Comment by amenity** [comment]
@SurbhiBakshi - removing the Sprint 30 milestone from this one.

**Comment by SurbhiBakshi** [comment]
This issue can be closed.
