### ISSUE TITLE
Assess various implementation options

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3304]
Time-boxed research to determine what approach to take in #3305. 
- [Relevant details on the VZA data model](https://github.com/cityofaustin/atd-data-tech/issues/3249#issuecomment-655680295)
- Knack docs: [Add checkboxes to a table](https://www.knack.com/developer-documentation/#add-checkboxes-to-a-table)
- [Mockups of potential solutions](https://docs.google.com/spreadsheets/d/1obi7JUZzlPpwft7eDD7TkmP2OxZrYOMuY06NJsLkPcA/edit#gid=0)

**Comment by mddilley** [comment]
After doing some research and discussing with @SurbhiBakshi and @amenity, here are some notes on how to proceed.

Goals:
- [ ] Condense duplicate assignments within a shift into Sign Up buttons that represent signing up for multiple `officer_assignments`. For each set of duplicates, a button will render. This button will actually fire off API calls to associate the logged-in officer with the assignment IDs that the button represents.
- [ ] In an `officer_assignment` record, `field_704_raw` either populates with `[{ "id": "5ebef4d0682bfc0015c9e0f4", "identifier": "No Officer Assigned" }] ` or the officer associated with the assignment. This will be used to render either an active or inactive buttons to show availability.
- [ ] Need to overcome limitation of Knack pagination limits (see below) that separates records that need to be associated together (as a button). This can be done by making an API call for the records and replacing the Knack-generated table with one built with jQuery and styled with Knack classes.

#### Page 1 with first half of needed records for 7/24 Morning - Team 1
<img width="400" alt="Screen Shot 2020-07-24 at 3 06 57 PM" src="https://user-images.githubusercontent.com/37249039/88712596-97209200-d0df-11ea-8097-d3f823cd9ba7.png">

#### Page 2 with second half of needed records for 7/24 Morning - Team 1
<img width="400" alt="Screen Shot 2020-07-24 at 3 07 01 PM" src="https://user-images.githubusercontent.com/37249039/88712652-aacbf880-d0df-11ea-9002-edb453c60471.png">

**Comment by amenity** [comment]
Thanks, @mddilley 🙌 🙏
