### ISSUE TITLE
Implement customizations to Officer sign up workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3305]
Before:
<img width="1201" alt="Screen Shot 2020-08-10 at 2 45 46 AM" src="https://user-images.githubusercontent.com/1463708/89761304-b3470a80-dab3-11ea-9ae8-bd535f6137e9.png">
Per a discussion with @SurbhiBakshi and @mddilley, we're going to move forward with something along the lines of this one: 
<img width="474" alt="Screen Shot 2020-07-27 at 3 43 57 PM" src="https://user-images.githubusercontent.com/1463708/88590269-046cee00-d020-11ea-9e43-7f5bd481c6e5.png">

**Comment by mddilley** [comment]
Research notes: https://github.com/cityofaustin/atd-data-tech/issues/3304#issuecomment-665238180
