### ISSUE TITLE
New Info (Traffic Control Co.) - Portal Development

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3309]
See parent issue for details; #1687

**Comment by shroffjs** [comment]
@TracyLinder @Nadin-Nader  @Sreelatha-BlazeKannan This ticket is deployed for DEV Portal changes and ready for your testing.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - DEV UAT Pending
