### ISSUE TITLE
VZD | Reprocess "austin_full_purpose" flags using no buffer AFP Jurisdiction ID = 5

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3310]
- [x] Reprocess `austin_full_purpose` flag for crashes. (Do we also need to do this for non-CR3s?)
- [ ] ~Update `view_atd_crashes_full_purpose` view~
- [ ] ~Update any parameters for ETLs to Socrata to use Jurisdiction ID = 5 instead of ID = 11~
- ~_Other related tasks?_~

**Comment by xavierapostol** [comment]
Please update the title 
"VZD | Update crash universe to use Full Purpose w/ 5ft Buffer instead of Full Purpose w/ 20ft Buffer"
to
"VZD | Update crash universe to use Full Purpose - No Buffer instead of Full Purpose w/ 20ft Buffer"

**Comment by sergiogcx** [comment]
Comment to self:

Once the records are re-processed, run an aggregate count using ST_CONTAINS against jurisdiction no 5 and make sure the numbers match.

**Comment by mateoclarke** [comment]
Updated the scope of this after a sync with Xavier.

**Comment by mateoclarke** [comment]
Adding a note from Xavier that it appears the flag update stopped updating on 2020-05-04

**Comment by sergiogcx** [comment]
This is done:

I first counted the differences between the two:

```
SELECT
   COUNT(1) AS count
FROM atd_jurisdictions AS atj
    INNER JOIN atd_txdot_crashes AS atc ON ST_Contains(atj.geometry, atc.position)
WHERE atj.id = 5;

SELECT
   COUNT(1) AS count
FROM atd_jurisdictions AS atj
    INNER JOIN atd_txdot_crashes AS atc ON ST_Contains(atj.geometry, atc.position)
WHERE atj.id = 11;
```

Also counted the number of full purpose flag records, to track changes:

```
SELECT
    COUNT(1) AS count
FROM atd_txdot_crashes AS atc
    WHERE atc.austin_full_purpose = 'Y';
```

After disabling all triggers on crashes, I proceeded with the update:

```
WITH data AS
  (
  WITH jurisdiction AS (SELECT geometry FROM atd_jurisdictions WHERE id = 5)
    SELECT atc.crash_id,
    CASE WHEN (SELECT ST_Contains(jurisdiction.geometry, atc.position)) THEN 'Y' ELSE 'N' END AS austin_full_purpose
    FROM atd_txdot_crashes atc, jurisdiction
  )
UPDATE atd_txdot_crashes
SET austin_full_purpose = data.austin_full_purpose
FROM data
WHERE data.crash_id = atd_txdot_crashes.crash_id;
```


These are the results:

```
-- Production:
Full purpose count before reprocessing:  155318
Full purpose count after reprocessing:   155139
Final difference: 179 (records excluded)

-- Staging
Full Purpose count before reprocessing:  154482
Full purpose count after reprocessing:   154260
Final difference: 222 (records excluded)
```

After this was done, I re-enabled all triggers for the crashes table.
