### ISSUE TITLE
Create Web Map of Location Polygons

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3317]
MVP: for TIA Module

**Comment by johnclary** [comment]
@dianamartin would you get a copy of the location polygons from the devs?

**Comment by dianamartin** [comment]
@jaime-mckeown I was able to get the vz polygons layer in a geojson format. It's a big file, I'll put it on the network and add the path here: (G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\app_VZA_Vision_Zero_in_Action)

**Comment by jaime-mckeown** [comment]
@dianamartin @johnclary as I clicked between the Issues in the Epic I saw that there's an Issue to put the VZ polygons on MAINT, but I've only been asked to get it onto AGOL. Do you want it to go through the entire process of MAINT, GISDM, AGOL or just straight to AGOL? Thanks

**Comment by dianamartin** [comment]
@jaime-mckeown @johnclary I thought we eventually want to put it onto Maint, but I think the goal is just to get it on AGOL for now.. I defer to John.

**Comment by jaime-mckeown** [comment]
@dianamartin Additionally, the JSON structure does not conform to the Esri-JSON standard, errors out when trying to convert.

**Comment by ChrispinP** [comment]
@TracyLinder Need to determine if this is still a need.

**Comment by TracyLinder** [comment]
I'm not sure if this issue relates to the mitigations map we created for staff to use while they're creating mitigations, or if it relates to the future map to view mitigation data for external stakeholders.

**Comment by jaime-mckeown** [comment]
I thought this Issue was originally created for VZ.

**Comment by TracyLinder** [comment]
Per John, I can remove the TIA label & epic from this issue.

**Comment by alan-deanda** [comment]
@amenity we currently don't have an AGOL version of the VZ Polygons from MAINT. I wasn't aware of this request/it hasn't come up in my conversations with Lewis. We might be okay closing this issue.
