### ISSUE TITLE
Create Maint Dataset of Location Polygons

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3318]

**Comment by dianamartin** [comment]
@jaime-mckeown I talked to John he said the process should be this: 

- VZ polygon JSON to ESRI GeoJSON: https://support.esri.com/en/technical-article/000019108
- VZ polgyon put on Maint
- VZ polygon put on AGOL
- VZ polygon create AGOL web map

**Comment by jaime-mckeown** [comment]
Thanks @dianamartin. John asked me to wait until after Sprint Planning this week before working on this.

**Comment by johnclary** [comment]
per discussion @jaime-mckeown hold off on the maint dataset for now. please focus on getting a prototype AGOL layer up and running. thanks.

**Comment by ChrispinP** [comment]
@TracyLinder Need to determine if this is still a need

**Comment by TracyLinder** [comment]
I'm not sure if this issue relates to the mitigations map we created for staff to use while they're creating mitigations, or if it relates to the future map to view mitigation data for external stakeholders.

**Comment by jaime-mckeown** [comment]
I thought this Issue was originally created for VZ.

**Comment by TracyLinder** [comment]
Per John, I can remove the TIA label & epic from this issue.

**Comment by alan-deanda** [comment]
@amenity , we can close this, the authoritative VZ polygons now live in MAINT
