### ISSUE TITLE
Create AGOL Feature Layer

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3319]
To get a prototype of the VZ Intersection Polygons into AGOL, publish the polygon layer that Frank created.

**Comment by jaime-mckeown** [comment]
@johnclary I forgot to ask what the sharing level needs to be, public?

**Comment by jaime-mckeown** [comment]
@johnclary The Vision Zero Polygons Prototype feature layer has been published, it is currently shared to the Organization. Please let me know if I need to share it publicly.
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/Vision_Zero_Polygons_Prototype/FeatureServer

**Comment by johnclary** [comment]
@jaime-mckeown please share publicly.

**Comment by jaime-mckeown** [comment]
The feature layer has been shared publicly.
