### ISSUE TITLE
Integrate VZD with AGOL Locations Polygons

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3320]

**Comment by patrickm02L** [comment]
The polygons are in various ArcGIS online responses. If GIS folks who were likely to be the people that would want them, they would have an avenue to get them. 

GISMAINT is the server where you can find them.
https://austin.maps.arcgis.com/apps/instant/interactivelegend/index.html?appid=32b276f4e6cd406aa1c2040d2eb26b37
