### ISSUE TITLE
Populate Location Polygon Name from the Polygon Map to replace the "Location" name that is (short text)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3321]
This feature enhancement is to be done as part of TIA module, Phase 2. 

- There is a `Location` field in the `mitigation_recommendations` object that allows the user to enter whatever name they want to
- This field can allow for errors by the user
- To prevent this from being the case a new field would be created that pulls the name of the streets from the Polygon ID that is referenced to the TIA mitigation recommendation record.

**Comment by TracyLinder** [comment]
- Putting this in Needs Scoping until we discuss mitigations.

**Comment by ChrispinP** [comment]
I am able to populate full street name and segment ID now from the mitigation map. If we dont additionally need city, state, and zip for each mitigation (only the project location which already includes city, state, and zip), then I no longer see this as a need.

@TracyLinder Let's review and determine if this is still a need.

**Comment by TracyLinder** [comment]
Closing.
