### ISSUE TITLE
Create AGOL-Hosted Barton Oaks Floor Plan

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3322]
@alan-deanda get the floor plan from @dianamartin.

The map needs to:
- Show which desks in the office are "hotel" spaces, vs non-hotel
- Display labels that identify the hotel spaces by ID (to be determined what the ID's are)
- The spaces may move around over time. So the ability to update that information easily would be nice.

Needed by 7/16.

**Comment by alan-deanda** [comment]
@johnclary where are the plans we got from Gilda mentioned here?

> 
> We got these from Gilda. See [https://app.zenhub.com/workspace/o/cityofaustin/atd-data-tech/issues/3322](https://app.zenhub.com/workspace/o/cityofaustin/atd-data-tech/issues/3322)
> 
> _Originally posted by @johnclary in https://github.com/cityofaustin/atd-data-tech/issues/3009#issuecomment-662622029_

Thanks,

**Comment by dianamartin** [comment]
@johnclary I can't figure out where you put the plans either @alan-deanda this is what Gilda emailed us
- [BO Seating Chart](https://app.zenhub.com/files/140626918/aab43103-f028-4cfb-8118-a63556762a87/download)
- [Coded Floor Plan](https://app.zenhub.com/files/140626918/2619f3ec-01d4-45b3-96ff-57953dd59571/download)

**Comment by johnclary** [comment]
Will need to layers:
1. Simplified floor plan (try to georeference the floor plan if zoom level is acceptable)
2. Hoteling spaces (attributes: name, description)

**Comment by johnclary** [comment]
No longer needing this as we are using Robin. @moorerst FYI there's some info here about our floor plan, which will eventually be needed in some form or fashion for Robin. Let us know when you need more floor plan info.
