### ISSUE TITLE
Create Per-Employee COVID-19 Time Log Reports

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3330]
We need to provide Peggy individual time log reports for each employee. The report should contain the same fields as the "HSEM Export" in the time tracking app. 

I have a script to create these reports as CSVs . @dianamartin will try to convert those to PDFs quickly.

Waiting until Monday, 7/13 to run this.

**Comment by dianamartin** [comment]
@johnclary I think this one is done already.

**Comment by amenity** [comment]
@johnclary - can you confirm this is done?

**Comment by johnclary** [comment]
Yes. closed.
