### ISSUE TITLE
Disable User Editing of Covid-19 Time Logs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3331]
We have temporarily enabled the ability for users to edit their time logs after they have been approved. We've done this so that employees can retroactively add their work location to the time logs. We need to disable this functionality on 7/16.

**Comment by dianamartin** [comment]
@johnclary We haven't heard from Peggy to put back the display rule on a user editing their previously submitted time logs once it's been `Approved`. 

If everyone has updated their time logs to add their locations and equipment information in then this rule can be put back on the table.

**Comment by moorerst** [comment]
@john has fixed this. It can be closed
