### ISSUE TITLE
Document the warehouse inventory procedure

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3333]

**Comment by amenity** [comment]
@johnclary @dianamartin - We missed this during planning. I'll add Finance and Inventory to the agenda

**Comment by dianamartin** [comment]
@amenity thanks for catching, I was already going to work on this issue.

**Comment by dianamartin** [comment]
Went through and tested the warehouse inventory workflow from AMD to Warehouse Inventory module. I had to reacquaint myself to the process. Documented what I could in [GitBook](https://atd-dts.gitbook.io/atd-knack-operations/finance-and-purchasing/warehouse-inventory). 
- Waiting for John's feedback bc I couldn't figure out how to close the Inventory Request
- Need to review Vans's SOP document too

**Comment by johnclary** [comment]
Van has seen this. Closing for now until we need to revise.
