### ISSUE TITLE
Compile starter set of Alpha workflows and wireframes

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3343]
Identify key Alpha features — what AMD needs most — and document the user workflows and wireframes. 

Add to [UI component inventory](https://docs.google.com/spreadsheets/d/1gNCz63qFpztiuL_JK4aPNnicjCglmATOW1dbpU0wxWk/edit#gid=241402064) along the way.

**Comment by zappfyllc** [comment]
@johnclary's brain dump about React components:

**Table/Grid**
- Sortable columns
- Striped rows
- Row highlight on hover
- Advanced filters ( <field name> <operator: equals, contains, is blank, etc> <value> ) E.g.:  Project Name contains "Congress" and Status is "Active".
**Forms**
- Asynchronous auto-complete form field (aka "typeahead"): Dynamically populate a select menu's options based on text input. (p.s., I'm partial to this package)
- Multi-select form field. Pick multiple items from a dropdown menu
- Conditionally display form fields based on input
- Multi-page forms (e.g., step 1, step2, ...)
- "Live" input validation/warnings
**Record Details**
- Ability to click on a field to edit it?
**Feedback, etc:**
- Breadcrumbs
- Progress bars

**Comment by amenity** [comment]
[WIP here](https://balsamiq.cloud/senhupm/p9y6tuy)...

I got through some basics but didn't get to the project timeline parts that I was hoping to have ready for #2475. 😞
 @JaceDeloney @zappfyllc - feel free to take a stab at that. The budget part of the financials is also at large.... 🙈 📆 🙈 💰

@johnclary — I would 💛 some sketches of your fancy table visions... (Needs Matching isn't MVP, but could be a pretty complex sorty/edity tabular interface if you want a prompt.)

@sergiogcx @mateoclarke @mddilley — I also invited you to our Balsamiq account in case that's helpful. 

And all y'all, I am 100% _not_ tied to any of these, so if you have alternatives/improvements, go for it. 💪

**Comment by johnclary** [comment]
@amenity looks like a wrecked by fancy filter material ui code. attached a sketch (and added to balsimq).
<img width="499" alt="Screen Shot 2020-08-19 at 2 14 51 PM" src="https://user-images.githubusercontent.com/14793120/90679868-6fc46d00-e226-11ea-85fe-654f1acf2bf9.png">

**Comment by amenity** [comment]
Closing this and adding individual wireframe issues.
