### ISSUE TITLE
Test Meeting

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#3346]
### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by ChrispinP** [comment]
This meeting requires #3249 to be in progress to initiate

**Comment by amenity** [comment]
This was really fun but it's over.
