### ISSUE TITLE
Import Pink Zone RPP Customer list for FY2020

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3349]

**Comment by dianamartin** [comment]
- Reference the **ATD Knack Operations GitBook>RPP Migration wiki**
- [ ] clean up/QC Pink Zone RPP list 
- [ ] create Pink Zone customer list for import
- [ ] Sync up with Diana
- [ ] import Pink Zone customer list

**Comment by ChrispinP** [comment]
Customers_PINK file uploaded to "import_tables" folder and is ready for import

**Comment by dianamartin** [comment]
- Chrispin and I sync'd up
- Showed him the import steps of Pink Zone
- Confirmed 328 customers were imported
- Went over how to format Permit Applications
