### ISSUE TITLE
Renew Zappfy Contract

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3353]
- get quote from @zappfyllc 
- work with Ken B to get paperwork submitted
- continue building Moped

**Comment by amenity** [comment]
- [2020-07 Zappfy LLC Sole Source Justification.pdf](https://drive.google.com/file/d/1t7tp4lPp9BiREf_XJSsV4egAeaiVQQmX/view?usp=sharing)

**Comment by amenity** [comment]
@johnclary - do you want me to follow up with Ken B?

**Comment by amenity** [comment]
[Purchase request here](https://atd.knack.com/finance-purchasing#my-purchase-requests/purchase-request-details/5f1b8d523792c30015b040ca/) — opened 7/24/20. 

@johnclary is there anything else I should be doing with this?

**Comment by johnclary** [comment]
Nope—I pinged Peggy about it this AM. We're waiting for her approval.

**Comment by amenity** [comment]
Assistant Director and Budget reviews are completed, currently in Purchasing | Processing.

**Comment by amenity** [comment]
Still in Purchasing | Processing. @johnclary — anything I should do here?

**Comment by amenity** [comment]
Update from Dan:
> CTM recently reopened their queue for Purchase Requests under FY21, I believe this occurred on 10/5.  If it’s been put into their workflow through ServiceNow we can follow up and see how it’s progressing and occasionally bring a little more attention to it.  I’ve copied Ken so he can look into it.

**Comment by zappfyllc** [comment]
Contract signed and submitted on Wednesday, January 13th to Gil.Zilkha@austintexas.gov
