### ISSUE TITLE
Implement more accessibility improvements

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3355]
There are still some remaining accessibility improvements that can be made to VZV. @mateoclarke implemented react-axe, which shows different issues than WAVE. Reference #3131

- [ ] Fix the errors that are showing up in react-axe on the Summary and Map views
- [ ] Fix the errors that are showing up in WAVE on the Map view

Screenshot of the react-axe issues on the Summary view
<img width="248" alt="Screen Shot 2020-07-13 at 4 32 29 PM" src="https://user-images.githubusercontent.com/10567316/87355756-84765c80-c526-11ea-835f-675f0f164d8e.png">

**Comment by amenity** [comment]
@tillyw @JaceDeloney - Are we still doing this? Sprint 42?

**Comment by tillyw** [comment]
@amenity yes, though it's not a priority at the moment

**Comment by amenity** [comment]
@tillyw - thanks. Updating the milestone, then. 👍🏻

**Comment by JaceDeloney** [comment]
@amenity  Thanks! I missed the milestone on this one.

**Comment by patrickm02L** [comment]
@patrickm02L will bring this up for the August 11 Sprint. 

After consulting with Mateo he recommended that we focus on the react-axe on the Summary and Map page, and let's tackle the Map View separately because the maps are tricky to do an accessible way because of their visual nature.

**Comment by patrickm02L** [comment]
@patrickm02L break this into 2 issues. WAVE will be separate.
