### ISSUE TITLE
GridSmart: Apply single-camera code into batch code that connects with Knack

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#336]
If we are working with two separate files (one for testing access to knack and printing all IP addresses, and another to access a single camera), then it will be time to merge both scripts, in any case we need to make sure:

- [ ] Modify the Knack script look so that it only prints ONE ip address and it stops.
- [ ] Add the code that will log in to the camera and add the new firewall rules.

**Comment by patrickm02L** [comment]
Issue is no longer relevant. RIP
