### ISSUE TITLE
Enterprise Dispatch Tracking Intake

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3367]
### Objective 

- Understand current work flow
- What is not working/captured in current work flow
- What is the desired outcome from a new solution

### Agenda

- Review request
Move https://cityofaustin.sharepoint.com/sites/ATD/dispatch/  from Sharepoint into Knack Parking Enterprise Reporting Portal.
They also have some documents that need to migrate from their Dispatch SharePoint that just needs to be moved to their Parking Enterprise Document library.
- Review current workflow
- What’s working and what’s not working with current workflow/form
- Desired outcome
- Next Steps
Estimate of how long it will take to build 
- Priortize 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Diana's Notes
### Parking Dispatch
- Keep track of workflow of officers
- Radio Checks
- Dispatchers call for radio checks
- Line of communication that is open

- Call to come in through CSR
- Phone call to main line/cell phone goes to dispatcher 
  - majority come from citizens
  - complaint or report an issue or set of issues
  - customer complaint (CUSTOMER INFORMATION)
  - or officers, additional assistance from APD or AFD
- Dispatch officers to address the situations
- Input notes in the outcomes
- Documents what happens during the dispatch

- What they did for SharePoint 
  - pull stats
  - put into a report
  - not very friendly
  
### Categories: 
- are pretty static
- is the list pretty good? Yes, for the most part

### Sources and Results: 
- complete after the fact
- instantly put in results
- no desired time frame 
- 72 hrs (CSR response)

### Prioritization
- CSR and citizen also call
- No priority 
- unless like vehicle blocking fire lane
- first come first serve

## PARKING ENFORCEMENT NEEDS
- Address - autocomplete

- Status: 
  - OPEN, IN PROGRESS, CLOSED
- Officer accountability
- Generate reports that need to be user friendly
- Pre-defined reports
  - Daily Call Count 
  - Monthly totals
    - Total CSRs
    - Total
  - Calls - Vision Zero - bike lane 
  - Employees by category (by total calls dispatched to)
  - Track Employees on Dispatch - FUTURE ENHANCEMENTS
  - track break/lunch
- Integrate CSR service requests - FUTURE ENHANCEMENTS

### NetMotion - link to log-in
- Look at the map location
- Brazos 

## Officer Citation Tracking
- Individual Performance

## Dispatch Tracking
- one off 
- Dispatch Performance
-

**Comment by moorerst** [comment]
What they have is currently working for them
Improvements
Better reporting - monthly by category, by dispatcher, by address (will think of more criteria)
Status - Open, In progress and Closed
Received By - CSR and Phone
Comments field
Future Enhancements
Ability to determine which officers are available - list of officers with status in/lunch/out
Integrate with CSR
View map locations
