### ISSUE TITLE
Builder Huddle: Digitize RPP Petition

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3368]
### Objective 
Estimate work load based on requirements from https://github.com/cityofaustin/atd-data-tech/issues/3171

### Participants
John, Surbhi, Chrispin, Diana, Stephanie

Meeting scheduled 7/16
------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by moorerst** [comment]
THINGS TO CONSIDER
Should applicant have an account? log-in
Communicate comment/notes: petition phase, Status update to Parking Office

PROPOSED PROCESS
Applicant turns in application
Applicant talks to Ryan
Ryan creates digital petition
Attachments - functionality
Applicant to also add attachments - function
Email goes to applicant
Status - In Review, Petition Phase, Verify Petition, Parking Occupancy Survey, Engineering Review, Approved, Denied, Withdrawn

Not in scope
Intake process
Parking Survey
Approval Process

**Comment by dianamartin** [comment]
## Diana's Notes - Builder Huddle
### Digital Petition
- Digital Petition - `parent`
  - Petition signature record - `child`
  - Address, Name, Phone, Decision: `S`upport, `O`ppose, Go with `M`ajority, Phone Number, Vehicle License Plate, Notes (for resident not providing a response) - `child`
  -  Add Attachments - attachment features - `child`

**Concerns:** 
- security - possibly enable a reCaptcha? 
  - Ask JD

**Comment by moorerst** [comment]
Effort score 8
Value score 11
https://docs.google.com/spreadsheets/d/1o0Q_xIx0c1njAg6opnAJwyCIhAkU7W-hK_7P8jgMCug/edit#gid=0
