### ISSUE TITLE
Create Service Now knowledge articles for DTS Service Request work flow

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3370]
Coordinate with CTM knowledge base admins on knowledge articles for SN

**Comment by moorerst** [comment]
discussed DTS Service Request work flow with SN knowledge base administrators and provided sample of knowledge article. Waiting on feedback

**Comment by moorerst** [comment]
submitted 2 draft knowledge articles to CTM KB Admins for review/approval

**Comment by moorerst** [comment]
@johnclary @dianamartin @SurbhiBakshi @jaime-mckeown 
here is a link to the 2 SN knowledge articles that have been submitted for the DTS Service Request. The first document list the ATD specific items so they can be searchable by the CTM Service Desk . They are Drafts right now until approved and published by CTM. Comment if you have any modifications. https://docs.google.com/document/d/1TlMm8hQps7ZyroV0dhOCEnaI9QhfHC5HucY-Kr1nj2A/edit#

**Comment by moorerst** [comment]
CTM has published KB0013738 in SN Knowledge Base for external and internal viewing
https://atx.service-now.com/sp?id=kb_article&sys_id=bd90ece31b4e1c10c00dba651a4bcb1e

**Comment by johnclary** [comment]
awesome--thank you @moorerst!

**Comment by moorerst** [comment]
Submitted updates provided by Surbhi. Contacted CTM to publish updated version.
