### ISSUE TITLE
Format Green Zone Permits for import

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3382]
Reference
- `permits_import_GREEN_20200710`
- `Customer_import_GREEN_with_appID`
- `Permit 2020_GREEN_ZONE`

**Comment by dianamartin** [comment]
- [ ] Add new line for each decal/hang tag/day pass
- [ ] Review "Customer Name" - `Display Name`
- [ ] Populate `Renewal Year`
- [ ] Populate `Issued Date`

**Comment by ChrispinP** [comment]
Permits_GREEN Spreadsheet formatted, verified, and complete. Saved as Permits_GREEN_529.csv

Test import completed on Friday 07/24/20 with Diana

Permits_GREEN_515.csv excludes the test import records and is ready to be imported.

**Comment by amenity** [comment]
@ChrispinP - is this still in progress? If so, will you update the milestone? Thanks!

**Comment by amenity** [comment]
Completed, but waiting to close this until #3634 is resolved.

**Comment by moorerst** [comment]
confirmed with RPP staff that migration of historical data from the Excel spreadsheet is no longer needed.
