### ISSUE TITLE
Meet with HR to discuss priorities 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3389]
Things have evolved since remote interviews were instituted. 

- Longer-term roadmap for the HR Knack App... or should we start evaluating an off-the-shelf solution?
- Banner integration

**Comment by moorerst** [comment]
Nathan B is Out of Office Aug 3rd - Aug 17th

**Comment by moorerst** [comment]
At their request scheduling week of 8/31

**Comment by amenity** [comment]
We're iceboxing #1488, but some of the information in there might be useful to include in this discussion.

**Comment by moorerst** [comment]
review meeting scheduled 9/17

**Comment by moorerst** [comment]
Meeting scheduled for 6/16 to discuss Knack forms for on boarding process issue #6325. 
If time permits we will ask about other priorities.

**Comment by moorerst** [comment]
@amenity @johnclary 
While discussing the HR On boarding forms with Nathan we had a brief discussion on what some of their other priorities might be.

- Right Now: 
Add the 4 On Boarding forms to Knack
Move the NEO Feedback form from MS Forms to Knack

- Short Term:
 Add the Secondary Employment Acknowledgement  Form to Knack
Create an evaluation form the the new ATD Supervisor Training program they will be implementing later in the summer

- Long term:
Have the ability for new hires to access Knack to complete new hire paperwork

They are eager to use Knack for many different processes but they are willing to take baby steps and work on a few items are a time. Their overall goal is to have a central location for employees to complete forms and HR and Supervisors to review them.

**Comment by moorerst** [comment]
The immediate request to put 4 On Broading forms in Knack and move the NEO elevation to Knack is complete

**Comment by moorerst** [comment]
@moorerst in the near future set up a follow up meeting to discuss the Secondary Employment Acknowledgement Form to Knack. Also discuss the report issue and the email notification issue if they are not resolved.

**Comment by moorerst** [comment]
follow up meeting scheduled for 8/9

**Comment by moorerst** [comment]
Per email from Nathan in reference to the Secondary Employment form - Let’s hold off on this for now.  I have way too many projects going right now and this is not urgent.  We only get a dozen or so a year.  No rush.

In reference to the Course Evaluation form  - Definitely.  That is a high priority for my group.

**Comment by johnclary** [comment]
Looks like there's nothing left to do here—closing.
