### ISSUE TITLE
New User Account: Darren U.

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3396]
**From Kym:** We have a new ROW supervisor over the TCP and UC Review Teams. We will need a new AMANDA account for Darren U., and the AMANDA rights should mirror Ryan M.

**Comment by TracyLinder** [comment]
Kim sent us the NERF on 7/6/20, and asked us for an update on 7/15/20.

**Comment by TracyLinder** [comment]
Nate, I put the estimate at 2. Not sure if that's accurate.

**Comment by Nadin-Nader** [comment]
I added the user to the TEST environment yesterday and set the automation to run and add the account on PROD last night. Unfortunately the account being mirrored has a client security of "Administrator" and it errored out when the batch tried to create the account on PROD. It needed an administrator to create the account.
Work around for this is to create the account with the Client Security as "Staff", then once it gets promoted to PROD, change the Cleint security on TEST to Admin and ask Gita, Jenice or someone with the AMANDA Admin account to update the Client Security on PROD.

Firs i have to have someone rerun the batch or wait til 6pm tonight for the batch to create the "Staff" account automatically on PROD as i chave left the TEST account with the Client Security as "Staff" just in case CTM doesnt get to run the batch manually.

**Comment by Nadin-Nader** [comment]
Kim/Darren,

Hope you too are doing well. I am reaching out to you to inform you that I have created Darren’s AMANDA accounts on both TEST and PROD. Please use the instructions below to log into both TEST and PROD. I have made the account to mirror Ryan Mooney. If you are missing anything just let me know.

Once the account is created in PROD you will receive an email stating that it has been created. At that time, please use the same instructions to log into the PROD environment and change your temporary password.
 
Instructions:
 
Your UserID is UJANOD
Your Temporary password is the same as your UserID in all caps.  
UserID are not case sensitive but your password is.  
You will be prompted to change it upon login.
 
Please log into both AMANDA TEST and PROD application to test your account and update your password.  
 
Once you get your EmployeeID and In the Future-If need be, 
you can reset your password using your Employee ID 10152868:
Steps:
Click on this link to access the AMANDA Password Reset Application 
URL:
http://cityspace/services/amanda
 
In the Employee ID: field, type your eAccess 8-digit Employee Number 
In the PIN: field, type your eAccess 6-digit PIN 
In the Database: field, click the drop-down arrow and select AMANDAProd or AMANDATest 
Click the Submit button 
Click the Reset Password button 
 
You will receive an email with your new AMANDA password 
The password is sometimes hard to interpret, so it is best to copy it from email and paste it in Amanda prompt.
You will be prompted to change it upon login.
 
NOTE: This is only for COA employees main Amanda PROD and TEST accounts.
If you have secondary Amanda accounts OR are Travis County employees, those have to be reset by CTM thru a Service Now Incident or Request.  
In this case, contact the CTM Customer Service Desk at (512) 974-4357 so an Incident can be created and assigned to AMANDA_SUPP.
 
Please let me know if this works for you or not. I will now close the request
 
If you have any questions or concerns, please do not hesitate to email me.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department
