### ISSUE TITLE
Account Updates: GF Insert Permissions 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3398]
### Per Laura on 7/14/20, she is unable to insert GF folders. 
- Also verify that users Hector A.  and Brandi B. have the same GF permissions as Laura, as they are the backups.

**Comment by TracyLinder** [comment]
@Nadin-Nader this is the issue for GF user permissions. Right now the request is for Laura and Hector A, her backup.

**Comment by TracyLinder** [comment]
Nate, I updated the description to include verifying permissions for Hector & Brandi match Laura's. I also added a high impact label.

**Comment by Nadin-Nader** [comment]
@TracyLinder I have modified the accounts and emailed all parties asking them to verify and let me know.

**Comment by Nadin-Nader** [comment]
All GF permissions needed to the parties have been added. Closing card
