### ISSUE TITLE
Update ASMP Knack application with textual changes 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#34]
Cole emailed me and said, 

<i>"Textual changes:
Make the following change at the end of the first paragraph on the home page;
“The right of way requirements for Level 2, 3, and 4 streets are included in the Street Network Table. Level 1 streets (local streets) with improvements identified are included in the Street Network Table. Level 1 streets without improvements identified (local streets) were not evaluated for right of way constraints and are all required to be 50 feet in constrained conditions and 60 feet in greenfield developments."</i>

**Comment by johnclary** [comment]
i updated the labels. for fun.

**Comment by dianamartin** [comment]
Updated ASMP application, forgot to close issue on 4/19.
