### ISSUE TITLE
GridSmart: Write Monitor Script

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#340]
We need to have a script that shows what cameras are working and which ones are not.

1. Gather list programmatically with python.
2. Set up a script that will gather a list of cameras
3. Loop through the list and check status
4. Store status of the camera in Knack

** Note the order of the tasks is opposite since they were transferred from another repository **

The actual order of the tasks is:

#339 GridSmart: List Camera IP addresses from Knack with Python
#338 GridSmart: Test python script with a single camera
#337 GridSmart: Document findings with single camera exercise
#336 GridSmart: Apply single-camera code into batch code that connects with Knack
#335 GridSmart: Plan on running on production environment

**Comment by sergiogcx** [comment]
I've created a repo for GRIDSMART and uploaded the files Seth created. I will have him set up his environment correctly so that he can run knack in a secure way (not showing api keys).

**Comment by sergiogcx** [comment]
This is the repo: https://github.com/cityofaustin/atd-gridsmart

**Comment by patrickm02L** [comment]
Shelf life of 2-years for this Issue has expired. Conferred with @ChristinaTremel for sign off to close the AMD related individual Issues.
