### ISSUE TITLE
Remove extra space between two alert messages at the top of the Summary page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3401]
**Describe the bug**
Extra space between alerts at the top of the Summary page. At full width, there is some extra space in between the "This is a beta..." alert and the "Austin is consistently ranked..." information banner section on the VZV Summary page.

I would expect to see the same amount of vertical space between the two alerts that we have between the other elements on the page (1.5 rem; .75 rem of padding from each element)... 

<img width="1394" alt="Screen Shot 2020-07-14 at 11 59 35 PM" src="https://user-images.githubusercontent.com/1463708/87573323-5ada4400-c692-11ea-9a64-84d339aed65f.png">

**Device**
Macbook Air

**Browser**
Chrome & Safari

**Comment by mateoclarke** [comment]
The alert banner was only temporary. Its been removed in staging and the inconsistent spacing is no longer an issue.

![Screen Shot 2020-07-15 at 5 55 39 PM](https://user-images.githubusercontent.com/5697474/87608053-86762200-c6c4-11ea-89ef-aa14621d7cc8.png)
