### ISSUE TITLE
Get Approval from the CISO to Use Stripe

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3404]

**Comment by johnclary** [comment]
Reached out to Jeremiah today:

> Jeremiah—hope you've been well. If you recall, you helped me look into using Stripe for online payments back in April 2018. 
> 
> We're finally moving forward with this, having resolved most of the administrative issues. To summarize:
> Stripe integrates directly with our software as a service, Knack
> Stripe will deposit funds directly into our bank account. We will not use a merchant processor.
> We (the City of Austin) do not directly handle any payment information. This information is sent by the application client directly to Stripe.
> We will need to prove our PCI compliance with Stripe. As far as I can tell, this process cannot begin until we connect Stripe to a bank account. Stripe will not allow us to accept payments until we meet PCI compliance.
> 
> So my ask of you is: what steps do we still need to take to have the CISO's blessing on our use of Stripe? I'd prefer to focus on the IT security rather than PCI compliance, as this compliance is a gated step in our use of the service which we're not quite ready to undertake.
> 
> I don't recall how thoroughly you reviewed Stripe from a security perspective, but my hope is that their protocols are well enough established that this is a minor lift on your side. 
> 
> Here's their documentation: https://stripe.com/docs/security/stripe
> 
> Happy to setup a time to discuss. Thanks!

**Comment by amenity** [comment]
@johnclary - pass along any info @moorerst will need to take the lead on this please.

**Comment by moorerst** [comment]
Followed up with CTM security on this issue. They requested a internal meeting to walk through the Knack/Stripe integration before requesting a meeting with the vendor to understand how their application is set up from a security perspective.  They also suggested we review the PCI Quick Start Guide which is a introduction of what they do.
[PCI Compliance Quick Start Guide.pdf](https://github.com/cityofaustin/atd-data-tech/files/5091931/PCI.Compliance.Quick.Start.Guide.pdf)

Will look for date to schedule meeting.

**Comment by moorerst** [comment]
From the PCI Compliance Quick Start Guide:

- [ ] Before setting up a payment card processing solution, request a merchant ID from the Treasury Department and begin gathering the following information to help the ISO with your PCI compliance assessment: 

- [ ]  Expected number of annual credit card transactions

- [ ] Different ways payments are accepted (e.g., in person, phone, web, IVR, manual) 

- [ ] A description of the existing/planned CDE, including: o Device(s), application(s), and connection(s) o Network diagram illustrating the connections between the components and how payment card data travels between them 

- [ ] A list of the vendors supplying any part of the solution, and any PCI compliance-related documentation that those vendors can provide

**Comment by moorerst** [comment]
Reached out to Jeremiah to determine who should attend the meeting from his team. He forwarded to Matt as the lead of Compliance Management. 
Per Matt include him, Tarek, John and myself. Will schedule for next week.

**Comment by moorerst** [comment]
Meeting schedule 8/31

**Comment by moorerst** [comment]
Meeting rescheduled to 9/8 due to conflict for CTM Security

**Comment by amenity** [comment]
@moorerst @johnclary - any updates here? Bump to Sprint 33?

**Comment by moorerst** [comment]
@johnclary attended meeting the CTM Security and has been communicating with Knack Support regarding PCI compliance. Details in issue https://github.com/cityofaustin/atd-data-tech/issues/3919. Closing this issue
