### ISSUE TITLE
Create a data relationship mapping document

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3406]
Create a defined workflow that:
- maps out relationship between the same field in different tables
- outlines which table should be updated for a specific 
- create a process so that when a crash record changes, the updated fields are updated in the correct tables

**Comment by patrickm02L** [comment]
We should look into using SchemaSpy as a way to resolve this in the same way it's being used for Moped.

**Comment by mateoclarke** [comment]
Schema Spy for VZ would be a great investment. cc/ @chiaberry @frankhereford. Maybe rename this issue and Backlog it as `Type: Tech Debt`?

**Comment by patrickm02L** [comment]
This was a 2-year old Issue. Created a new Issue for this with the intention of implementing after the LDM.
