### ISSUE TITLE
Create and Publish Speed Limit Change Feature Services for AGOL and Collector

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#3408]
# Speed Limit Signs Point Layer
 This layer will be used by TED to record the location of speed limit signs, whether currently active or to be installed in the future. This layer will be used in an AGOL desktop editing app, and on mobile devices through the Collector App

## Fields
- FIELD_CHECK: Needed, Completed (dropdown)
- STATUS: Install, Remove, Replace (dropdown)
- CURRENT_SPEED_LIMIT: (numeric dropdown)
- FUTURE_SPEED_LIMIT: (numeric dropdown)

# Signs Work Order Polygon Layer
TED will use this layer to draw a polygon around the desired stop signs and streets to include per work order. This 
layer will be edited in an AGOL dekstop app, and can be shown as a reference on the collector app. This layer will use the field `WORK_ORDER_STATUS` to QA/QC progress on the project.

## Fields
- DESCRIPTION : Text
- WORK_ORDER_STATUS: This will be populated from the list of values from Knack, and will add `READY TO SUBMIT` (dropdown)

# Proposed Speed Limits Vector Tile Layer (reference)
It will be helpful to use the Proposed Speed Limits Layer to verify the change from current speed limits to future ones. This feature layer will be converted into a vector tile layer to load quickly across all devices, and its legend will be included. The current and future speed limit data from this layer will be recorded in the appropriate fields in the Speed Limits Signs Point Layer.

# Maps
## Speed Limit Sign Changes
This map will use the Speed Limit Signs Point Layer, and TED staff will use it to record the location of signs they find on Google Street View. Staff can record the current speed limit through imagery, and future speed limits by checking the proposed speed limits layer onto the Speed Limit Signs Point Layer through a drop down menu.

## Collector
TED staff will be able to access the Speed Limit Sign Changes Map through the Collector app on mobile devices to confirm the location of an existing speed limit sign if Google Streeview does not have accurate imagery. Staff can drive along a road, tap a point, and verify its location by the changing the value of `FIELD_CHECK` from `Needed` to `Completed`. Staff can also drop new points on the map to record future stop signs.

## Work Orders App
This app will load a map that includes the Speed Limit Sign Changes Point Layer, the Proposed Speed Limits Vector Tile Layer, and the Signs Work Order Polygon Layer. TED staff will use this app to draw a polygon around the speed limit sign changes they wish to group in a work order. They'll be able to track the progress of the work order through the `WORK_ORDER_STATUS` field.

**Comment by dianamartin** [comment]
I think there needs to be another field added for the `Signs Work Order Polygon Layer`. The `REQUESTER_WORK_ORDER_ID` - alias `Requester ID`. 

If this layer is the one that the TED engineers are creating and we are generating a work order for them, then we need to have some unique identifying information for who made the polygon.

**Comment by alan-deanda** [comment]
@dianamartin  agreed, that's a good idea

**Comment by alan-deanda** [comment]
Changing the name of the `STATUS` field in the Speed Limit Sign point layer to `INSTRUCTIONS` to be more precise.
