### ISSUE TITLE
Shared Micromobility: Drop the word "Dashboard" from header

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#341]
To be consistent with our other dashboards, drop the word "dashboard" from the title header on the shared micromobility dashboard.

![Screen Shot 2019-07-11 at 2.50.26 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/7e84ff67-f3b1-479a-bfeb-35d0e47c77a9)

**Comment by mateoclarke** [comment]
This one has already been implemented, right @tcwcodes?
