### ISSUE TITLE
Format Pink Zone Permit Applications for FY 2020

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3410]
- [x] Started PINK Zone Permit Applications
- [ ] Populate License Plates
- [ ] Populate RPP Zone - in RPP app
- [ ] Populate RPP Zone - spreadsheet
- [ ] Populate Customer - `Display Name`

**Comment by moorerst** [comment]
confirmed with RPP staff that migration of historical data from the Excel spreadsheet is no longer needed.
