### ISSUE TITLE
DevOps (Test to Prod) - Mitigation Fees 1729 (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3425]

**Comment by TracyLinder** [comment]
@Nadin-Nader I put this in the backlog for you.

**Comment by Nadin-Nader** [comment]
The DevOps Deployment TASK is SCTASK0090582. The Deployment for the LookUp is going to CTM Tango as it is a LookUp on PROD and i cant add it to PROD. I have submitted the task for this and it is SCTASK0090583.

Status:
Waiting on CTM Tango and CM DevOps team to deploy to PROD
