### ISSUE TITLE
Update Markings Work Order Scripts to Point to New Signs App

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#343]
Data published to AGOL from Data Tracker need to be updated to point to new app.

**Comment by amenity** [comment]
See also Pavement Markings Work Orders not updating on AGOL since 3/15/19

**Comment by johnclary** [comment]
Merged to `master` and letting `master` run on production for a day until promoting to production.

**Comment by johnclary** [comment]
It's done. Merged to prod and prod is running on the prod server again. prod prod prod.
