### ISSUE TITLE
Add a KSI sortable column to the crash change index table

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3439]
As a user, i want to be able to quickly triage the changes queue by changes to injury severities that include Fatalities and Suspected Serious Injuries 

- [ ] Add a sortable column to the crash change index table that sorts the changes queue based on whether a crash has an updated injury severity of Fatality or Suspected Serious Injury

![Screen Shot 2020-07-17 at 1.44.27 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/e29e2fb6-b14f-4938-a85e-46e17093265a)

**Comment by JaceDeloney** [comment]
Moving this back in priority. This would be useful if we were expecting the changes queue to remain long, but we don't expect there to be that many changes on a weekly basis.

**Comment by JaceDeloney** [comment]
Revisit this issue to determine whether we actually need this. Sync with Xavier on the importance of this.

**Comment by patrickm02L** [comment]
Address with #11959

**Comment by patrickm02L** [comment]
I like this idea about adding a Killed or Serious Injury column in the Changes table, but in recent conversation Xavier admitted that KSI was not as affective as it had been when VZE was created. Perhaps, we'll revisit this idea again, but for now I'm retiring it.
