### ISSUE TITLE
Feature request: Configure Email Task - Department Head/Designees based on assigned divisions

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3440]
Nathan B. 
HR

Would like the HR system to be able to email the users in the user role "Department Head Designee" whenever a telework request form is in that status. 

- [ ] Get mapping of Department Head Designees to assigned divisions 
>ex. Example of Dept. Head/Designee – Division mapping
- Jim 
>  - ROW
>  - AMD
>  - SMB
- Rob
>  - HR
>  - Finance
>  - Office of the Director

- [ ] Create email task on object table `form_telework_request` for each Dept. Head/Designee that contains their divisions
- Action - `send custom email`
- When - `status` is `Department Head/Designee Signature Required`
- Division - contains (Ex. `Data and Technology`)
- Send - to `email of DHD`
- Message
  - From Name
  - From Email - no-reply-HR
  - Subject - Department Head/Designee Signature Required : Telework Request Form
  - Message
>Please log into the HR Management Portal and approve outstanding [telework requests](https://atd.knack.com/hr#forms/view-form-details/5ee0fe597e18a50016062565/).

Filter to your "**Divisions**" in order to review employee telework forms.

#### Reference Images
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/ed2aadbb-cf48-4c7e-a3fa-33b2a12c0443)
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/fb18320e-1885-4c81-afe9-8e87d371caf9)
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/644dfd84-d52a-4a8e-9df0-2adc4c92c36b)****

**Comment by amenity** [comment]
@moorerst will follow up with Nathan; this is going to be a lot of work on our end and we're not convinced it would have an impact. 
We can provide any additional lists/reports that would help him address this.

**Comment by moorerst** [comment]
8/31 provided Nathan with a report of forms with status Needs Dept Head Signature. There were 125 forms needing Dept Head signature, as of 9/1 there are 83. So some progress was made.

**Comment by moorerst** [comment]
this task is not needed at this time
