### ISSUE TITLE
TDS - Add 2 Fees to Folder Insert + Run Procedure (TL)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3447]
### Add 2 fees to the folder Insert + Run Procedure 
- These were missed in our requirement on #2401

**Stakeholder:** Sangeeta
**DTS Manager:** Tracy

**Acceptance Criteria:**
- The 2 fees in the below table are available on the folder tab, Insert + Run Procedure
- The fee procedure works for these folder types: C8, C, SP,  ZC
- When the user selects the fee from the fee list, the system inserts a fee line with the correct amount

Fee Code | Description | Amount
-- | -- | --
83478 | ATD-SUB-Final Plat | $1,310
83477 | ATD-SUB-Preliminary Plan | $2,920

**Comment by Nadin-Nader** [comment]
Subha will be Deploying to DEV. I have approved commits (ff7d16933c9d, c95ed81890e3 ) She will also be sending @TracyLinder  and myself a demo on DEV.

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader  Have sent the demo to you. Once you approve it, I will submit Dev deployment request.
@Sreelatha-BlazeKannan

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @SubhaShroff  @TracyLinder Reviewed the demo and it looks good. Both fees are there and they run with the "Insert and Run" option.

**Comment by SubhaShroff** [comment]
Thanks @Nadin-Nader . I have submitted a request for **SCTASK0084964** Dev deoployment. And also I added respective lookup codes in Dev.

**Comment by Nadin-Nader** [comment]
Checked on SCTASK0084964 and it is in the To-Do pipeline and waiting to be deployed  to DEV

**Comment by SubhaShroff** [comment]
Thank you @Nadin-Nader.
@TracyLinder @Nadin-Nader The issue is deployed in DEV successfully and I have tested 'Insert + Run' of fees 83477, 83478 for the folder types C8, C, SP & ZC.  Its ready for DEV testing.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Waiting for feedback in DEV environment.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  @TracyLinder This is good to go on DEV. Ready for TEST

**Comment by SubhaShroff** [comment]
**Status:** I have submitted a ServiceNow Request (SCTASK0087077) for the commits TEST Deployment today(8/4/2020). 
And sent a request to @Nadin-Nader to add the respective lookup values in TEST instance.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @Sreelatha-BlazeKannan @TracyLinder 

I have added the Lookups to TEST.

**Comment by SubhaShroff** [comment]
Thank you @Nadin-Nader.
@Nadin-Nader @TracyLinder This ticket is now in TEST, I tested it and ready for your testing.(8/5/2020)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader  Tested the same and it meets the acceptance criteria.

**Comment by TracyLinder** [comment]
### Approved to promote to Prod 🎉

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader  PROD deployment requests are submitted: SCTASK0088709, SCTASK0088719.

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan  This ticket is moved to PROD.

**Comment by TracyLinder** [comment]
### Email to Sangeeta:

Hi Sangeeta,

The 2 fees that were missing from the Insert + Run are now live in Prod. Below is a screenshot of the ticket details. Please let us know if anything isn’t working as expected.
