### ISSUE TITLE
ROW Performance Measure Report - Fix Parameters (TL)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3465]
### See #1872 for full details.

**Comment by Nadin-Nader** [comment]
Sree has completed Changes and testing but working with Dev Team since she has to use a new function package but is having an issue with it. May be a Crystal Problem. Waiting on response from Gita and SAP Customer Service.
Sree will wait til tomorrow and if she hasnt heard back from SAP and if she hasnt she will use the fix given by Gita (use standalone procedure).

**Comment by Sreelatha-BlazeKannan** [comment]
Completed the changes using Function and Object type. DEV Commit submitted on 07/27/2020

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  I have submitted the TASK to CTM for deployment to DEV. 

TASK: SCTASK0085177

Status waiting on commit to DEV Deployment by CM DevOps Team

**Comment by TracyLinder** [comment]
**Status:** Pending promote to DEV (submitted on 7/28). Updating to Sprint 30.

**Comment by TracyLinder** [comment]
Martin finished promoting this to DEV on 7/28
Sree - did you want to test this on DEV before I begin UAT?

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Sree will test in Let you know

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan audited and approved commit 6a55b96a2a3a

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Reverted and recommit will be done by EOD

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Commit submitted 372598c13414

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  @TracyLinder I accepted the commit on Monday

**Comment by Nadin-Nader** [comment]
Waiting on deployment plan to send to CM DevOps Team

**Comment by Nadin-Nader** [comment]
Received Deployment plan. Will send to CM DevOps by COB

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder  I have submitted the Tasks for the CM Team to promote to Dev. SCTASK0090281 for the regular commit and SCTASK0090285 for the manual commit. I will be deploying the report to DEV today.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have added the report to DEV. We are just waiting on the deployment by the CM DevOps team.

**Comment by Nadin-Nader** [comment]
Per our Stand-Up
**Status:**
Aish/Subha are currently working on this when Sree is out

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - THe Function not moved to the DEV Environment; still the old report is being called causing the issue. Trying to work with Nadin & Martin to fix the issue.

**Comment by Nadin-Nader** [comment]
I tested this for Sree earlier this week and found that the second column was still not calculating correctly.

**Comment by Nadin-Nader** [comment]
Redeploying fixed report to DEV for Sree

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Its completed and moved to DEV and tested the same in DEV environment and  ready for TEST move for further testing .

**Comment by Nadin-Nader** [comment]
**Status:**
Ready for TEST deployment

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Sent the TEST Deployment Plan on 09/09/2020

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan Created Task - SCTASK0095108 (Procedure commit),  I also created Task-SCTASK0095111 (Manual Commit) and sent it to the CM Team  for deployment to TEST.
I have already added the new report to TEST.

**Status:**
Waiting on CM Team to deploy both tasks to TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  Just checked Service now and it seems like Gita has completed the manual commit for this SCTASK0095111. The other TASK sent to the CM team, SCTASK0095108 (Procedure commit), has not been deployed yet

**Status:**
Waiting on CM DEVOPS team to deploy SCTASK0095108 (Procedure commit)

**Comment by Nadin-Nader** [comment]
**Status:** 
Sree is looking into the error with Gita that was received when Martin tried to commit the changes to the real commit number, 372598c13414
Sree will give us an update once she finishes working with Gita.

**Error during commit:**

> Error during PACKAGE 'COA_DECLARE' validation:
> PLS-00201: identifier 'COA_OBJ_AUDIT_TYPE' must be declared
> Compile error at line 256, column 42
> PL/SQL: Declaration ignored
> Compile error at line 256, column 6
> Error during PACKAGE 'COA_DECLARE' validation:
> PLS-00201: identifier 'COA_OBJ_AUDIT_TYPE' must be declared
> Compile error at line 256, column 42
> PL/SQL: Declaration ignored
> Compile error at line 256, column 6

**Comment by TracyLinder** [comment]
**Status:** In Test, ready for UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder ,@Nadin-Nader - In TEST, Ready for TEST UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder ,@Nadin-Nader - Waiting on Tracy's Review Comments.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have looked at the report and it looks good. 
Dates I ran were 10/1/2019 to 10/6/2020. The information that came back in the report and the totals were correct. Ready for Tracy and Stakeholders review

**Comment by Sreelatha-BlazeKannan** [comment]
Thank you @Nadin-Nader 
 Waiting on @TracyLinder 's Review Comments.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder -
Waiting on Tracy's review comments in TEST Environment

**Comment by TracyLinder** [comment]
### UAT w/ Sree Results
- Remove 'subcode null' exclusion

**Comment by TracyLinder** [comment]
UAT Data Validation Query I Used Today:

Select f.folderrsn, vs.statusdesc, f.indate, f.issuedate
From folder f, validstatus vs
Where f.foldertype = 'UC'
And f.indate between sysdate -22 and sysdate
aND F.Subcode not in 50510
And f.statuscode = vs.statuscode;

Select f.folderrsn, vs.statusdesc, f.indate, f.issuedate
From folder f, validstatus vs
Where f.foldertype = 'UC'
And f.Issuedate between sysdate -22 and sysdate
And f.statuscode = vs.statuscode;


--where indate between sysdate - 21 and sysdate and foldertype in('RW','DS','EX')

**Comment by TracyLinder** [comment]
We are going to move this to Prod so we don't lose the function Sree built in the query. Then we'll come back to make the changes.

**Comment by TracyLinder** [comment]
### Approved for Prod 🎉

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader -  PROD DP Submitted on 10/23/2020

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder  I have submitted the deployments to go to PROD for this. Per Martin it had to be 2 different TASKS for the Manual and Procedure commit and then the one for CTM Tango to deploy the report to PROD:

Manual Commit Deployment TASK Number: **SCTASK0102236**
Procedure Commit Deployment TASK Number: **SCTASK0102244**
Report Deployment TASK Number: **SCTASK0102247**

## **Status:**
Waiting on CM DevOps and CTM Tango to deploy to PROD

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder Checked the status on this and found the following statuses for the TASKS:

Manual Commit Deployment TASK Number: SCTASK0102236 **Deployed and closed**
Procedure Commit Deployment TASK Number: SCTASK0102244 **Waiting to be deployed**
Report Deployment TASK Number: SCTASK0102247 **Deployed and closed**

**Comment by TracyLinder** [comment]
SCTASK0102244 was promoted on 10/28; will test with stakeholders today in PROD

**Comment by TracyLinder** [comment]
### PROD ERROR

![image](https://user-images.githubusercontent.com/49930868/97751888-121f8d00-1ac1-11eb-9f9b-55a821d4cd94.png)

**Comment by Nadin-Nader** [comment]
@TracyLinder @Sreelatha-BlazeKannan This has been deployed to PROD. All 3 requests have been closed.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - Moved to PROD Successfully. This can be tested and closed

**Comment by TracyLinder** [comment]
Looks great! I have informed the stakeholders; closing.
