### ISSUE TITLE
7/25 - Restore user access back to Signs and Markings Work Order system

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#347]
## Users already `Inactive` status (return to `Inactive` after migration)
- [ ] J. Bohac
- [ ] A. Chapman
- [ ] D. Cordell
- [ ] S. Guzman
- [ ] A. Mills
- [ ] J. Padron
- [ ] M. Stevens
- [ ] J. Woodyard

#Need to add people back as inactive otherwise work orders will not have people associated to them

Names
--
- [x] Alison Mills - DUP
- [x] Ann DeSanctis
- [x] Jesse Duncan
- [x] Juliet Thomas
- [x] Reza Veladi
- [x] Stephanie Spangler

**Comment by johnclary** [comment]
I restored the missing accounts as listed above.

**Comment by dianamartin** [comment]
Plus Alan de Anda, Ed Beaudet and Ella Ryan. I think I'll need to add Jaime too.

**Comment by johnclary** [comment]
Done!
