### ISSUE TITLE
Builder Review: SMB Invoicing enhancements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3479]
7/23 11-12pm

**Comment by dianamartin** [comment]
### Feedback changes 7/23
#### Notes from invoice INVOICE DOCUMENT
- [x] Add print function to signs
- [x] Add INVOICE in big letters on the top
- [x] Add "Project:" in front of the ID

#### INVOICE DETAILS
- [ ] Add plans to the page or add link to main work order.
