### ISSUE TITLE
Schedule VZA shifts through the end of September

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3480]

**Comment by amenity** [comment]
Waiting for Lewis to circle back on this.

**Comment by SurbhiBakshi** [comment]
1. July 20 - July 26 ----Aug 17 - 23
2. July 27 - Aug 2 ----Aug 24 - 30
3. Aug 3 - Aug 9 ----Aug 31 - Sep 6
4. Aug 10 - Aug 16 ----Sep 7 - Sep 13
5. Aug 17 - Aug 23 ---- Sep 14 - Sep 20
6. Aug 24 - Aug 30 ----Sep 21 - Sep 26
7. Aug 31 - Sep 6 ---- Sep 7 - Oct 4 ???
