### ISSUE TITLE
VZD: Graphs Static Data

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#3481]
- [x] Implement a solution for VZV to use a static, cached file to enhance performance

We want to update the Socrata datasets once a month. The reason we update VZV on a monthly cycle is to allow for data QA processes to take place before it gets to the public. That frequency should also be put in place for the publicly available crash data in Socrata.

improve our task monitoring and consider caching monthly queries so VZV is more robust than ETL failures or Socrata outages. This would have immediate performance benefits for VZV because it would only request data once a month rather than every day.

**Comment by sergiogcx** [comment]
There is already a PR:
https://github.com/cityofaustin/atd-vz-data/pull/861

**Comment by JaceDeloney** [comment]
This was completed nut never closed out
