### ISSUE TITLE
Feature request: Schedule deletion for Apps Team to delete RPP Attachment Records

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#3482]
- As a RPP Staff person, I want to delete RPP attachment records so that I don't keep documents of residents after I've reviewed their application. 

- As a DTS Apps staff, I want to delete RPP attachment records so that I don't have to go in manually to batch delete records. 

PROPOSED WORKFLOW
- go to `attachments` object table, filter `Attachment Status` is `To Delete`
- Batch select, Delete records
- Determine how often the Apps team wants to do this

TESTED
- [x] if you delete an attachment, that the Attachment Status on the `permit_application` is unchanged.

**Comment by SurbhiBakshi** [comment]
Checked with Meredith S with reference to Records Retention policies.

**Comment by amenity** [comment]
Waiting to get specifics on the records retention policy here.

**Comment by moorerst** [comment]
Tracy met with the City Clerk's Office. Here are the takeaways from that meeting:

- It’s very unlikely that we’ll see a new record series that will allow us to get rid of the PII sooner than the 2 years that the records have to be held for. 

- City Clerk's Office is going to ask the State Records office if they are interested in creating a series for it, but again it’s very unlikely. 

Conclusion
- We should move forward planning to hold those records for the full 2 years, and plan for how we will meet disposition after the records have met retention deadlines.

**Comment by johnclary** [comment]
thanks @moorerst. i'm going to make a separate issue for us to create an automated process which moves these records out of Knack and into an extra-secure location.

**Comment by johnclary** [comment]
Opened [#3927](https://app.zenhub.com/workspace/o/cityofaustin/atd-data-tech/issues/3927). i'm closing this.
