### ISSUE TITLE
Meeting: PNTS Discussion w/ Prentic M. (CTM GIS)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3484]
### Continued discussion re #3348 

**Date/Time:** 7/28/20 @ 2:30pm
**Attendees:** Tracy, Prentice, Alan
**Agenda:**
•	Why is AMANDA part of this process, and what function does it serve?
•	Is it necessary for AMANDA to continue being part of this process/tool?
•	Are there any system logs that can help identify what is actually happening?
•	Any idea what is happening here?

**Comment by johnclary** [comment]
@alan-deanda @TracyLinder plz add your notes.

**Comment by TracyLinder** [comment]
### Notes

**The meeting was cancelled and the discussion continued via email.**

1.	Resolve Dylan’s (Healthy Streets) issue as much as we’re able to.
a.	How sure are you that his errors are caused by system maintenance?
i.	The errors can be caused by any number of reasons including AMANDA maintenance/general errors. The question to ask is, is the error coming from AMANDA. AMANDA sends back an error when something goes wrong. 
b.	If I ask users to log the date & time they encounter this error, would that help us better identify what is happening, based on system log of errors? 
i.	Yes.
2.	Push to remove AMANDA from the PNTS process altogether.
a.	If we understand correctly, AMANDA is critical for the unique ID the feature needs. Is the LID/Token thing you wrote about just part of getting that unique ID from AMANDA, or is that performing a separate critical function? 
i.	The LID is used to call AMANDA Web services. It tells AMANDA that the request being sent is authorized to call the web service. Without the LID then the request will be denied and no folderRSN will be created and returned in the response.
b.	We maintain GIS features that create it’s own unique ID. Is it worth pursuing that as an alternative solution to using AMANDA for this need?
i.	I think that there is a good chance it would not be approved because the unique identifier is being created by an outside source. Furthermore, the folderRSN is needed by other departments that use PNTS. They need the folderRSN because it is associated with data in AMANDA inside of a folder that they have created. The PN folder is not the only folder that PNTS use when creating public notifications. We would need to modify existing code or create new code to bypass creating AMANDA folders for public notification. The level of effort to do this is unknown and would require time to investigate and developers from another team would need to get involved. 

Prentice Mooney
IT Application Developer
City of Austin 
Communications & Technology Management
CTM Enterprise Geospatial Services
Office: 512-974-5193 
prentice.mooney@austintexas.gov
Romans 10:8-10

From: Linder, Tracy 
Sent: Tuesday, July 28, 2020 3:02 PM
To: Mooney, Prentice <Prentice.Mooney@austintexas.gov>; DeAnda, Alan <Alan.DeAnda@austintexas.gov>
Cc: Hrncir, Jacqueline <Jacqueline.Hrncir@austintexas.gov>
Subject: RE: PNTS Discussion

Thanks Prentice, those answers did help clarify a lot for us. Alan helped translate some of that for me so I understand it as much as I’m able to. Lol

My 2 main goals are below, with more follow-up questions/comments
1.	Resolve Dylan’s (Healthy Streets) issue as much as we’re able to.
a.	How sure are you that his errors are caused by system maintenance?
b.	If I ask users to log the date & time they encounter this error, would that help us better identify what is happening, based on system log of errors? 
2.	Push to remove AMANDA from the PNTS process altogether.
a.	If we understand correctly, AMANDA is critical for the unique ID the feature needs. Is the LID/Token thing you wrote about just part of getting that unique ID from AMANDA, or is that performing a separate critical function? 
b.	We maintain GIS features that create it’s own unique ID. Is it worth pursuing that as an alternative solution to using AMANDA for this need? 

Thanks Again!

Tracy Linder, Product Manager
Data & Technology Services 🚲 Austin Transportation
————————————————————————

From: Mooney, Prentice 
Sent: Tuesday, July 28, 2020 1:34 PM
To: Linder, Tracy <Tracy.Linder@austintexas.gov>; DeAnda, Alan <Alan.DeAnda@austintexas.gov>
Cc: Hrncir, Jacqueline <Jacqueline.Hrncir@austintexas.gov>
Subject: PNTS Discussion

Hello Tracy, I was looking forward to speaking with you today. However my phone is not working because there is a tower that is down in my area and they are working on it. I’ve responded to your questions below. Please take a look and I hope that my answers will satisfy the questions that you have. If not, we can always schedule another meeting in the future that I am able to attend.
•	Why is AMANDA part of this process, and what function does it serve?
o	The AMANDA FolderRSN is used as a primary key in a table that relates to a feature. The geospatial data analysis that is performed uses the FolderRSN to locate the feature, and then takes the feature and does a drill down intersecting multiple layers to gather property owner data for public notifications.
•	Is it necessary for AMANDA to continue being part of this process/tool?
o	Yes. Without the AMANDA FolderRSN the application will not work because it relies on that unique identifier to get the feature for generating the property owners list in PNTS.
•	Are there any system logs that can help identify what is actually happening?
o	Yes. The application creates logs of errors.
•	Any idea what is happening here?
o	Yes. The first steps in creating a list of owners for public notifications in PNTS is to call an AMADA web service to authenticated. After authentication the service will return a LID. The LID is used as a token that is passed to another web service that creates a new PN folder in AMANDA and then returns an AMANDA FolderRSN. When AMANDA fails to return a LID to the PNTS Geoloader application then that is when an error gets generated and the customer will not be able to go forward with creating their PN folder and attaching their feature. 
I’ve opened a ServiceNow ticket to have all of the PNTS users added to the AMANDA Users DL (which is a distribution list of emails that get notified when AMANDA will be down for maintenance). I think this will help in alerting customers of when to expect AMANDA system outages and plan accordingly. However, sometimes AMANDA has issues that are not planned but there is not much I can do in that case.
I hope this is helpful. Sorry I am not able to join the meeting. If you have any more questions please feel free to get in touch with me.   


Prentice Mooney
IT Application Developer
City of Austin 
Communications & Technology Management
CTM Enterprise Geospatial Services
Office: 512-974-5193 
prentice.mooney@austintexas.gov
Romans 10:8-10
