### ISSUE TITLE
VZD | Dedupe Blueform table

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3488]
Xavier reported some dupe non CR3 records.

![image](https://user-images.githubusercontent.com/5697474/88334929-1c7aff80-ccf8-11ea-86e0-9555387f0301.png)

Lets:
- [ ] Confirm dupe insert prevent is working in Non-CR3 upload tool
- [ ] Dedupe records that might have been added before upload tool bug fix was deployed

**Comment by JaceDeloney** [comment]
This was part of the non-CR3 record update issue
