### ISSUE TITLE
7/24 - Create test environment for technician training

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#350]
DO THIS IN THE MORNING!!

- One user account
- Need to redo hard coded homepage links
- Send Kati and Christina links to test environment and test technician user un/pw

**Comment by dianamartin** [comment]
Finalizing the request cancellation display filter on Signs and Markings work orders. I think I fixed the issue. Started copy of Signs and Markings Operations app. Will email Kati and Christina new URL in the morning.
