### ISSUE TITLE
Write wiki to set up geo partner accounts with Google Maps

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3518]

**Comment by alan-deanda** [comment]
@johnclary  I spoke with Mateo about setting up partner dashboard login through transportation.data@austintexas.gov, and we reasoned it might be easier to set up accounts through each personal email. Instead of this, I'll write a short internal wiki with instructions to setup your own account.

**Comment by alan-deanda** [comment]
Wiki is now live [here](https://app.gitbook.com/@atd-dts/s/atd-geospatial/google-maps-partner/google-partner-account)
