### ISSUE TITLE
7/31 Mobile Signals MVP Sprint Review

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#352]
### Agenda

- Discuss usability findings
- Demo camera functionality
- Launch plan
- Prioritize next features/enhancements
------
- [x] Schedule meeting
- [x] Meet
- [x] Attach meeting notes to this issue
- [ ] Create resulting issues

**Comment by mateoclarke** [comment]
rescheduling...

Here's the slides: 
https://docs.google.com/presentation/d/1tFZvCeJbKQVoMDdzD2k0-M9amQwR407e4qQYPO6Io5A/edit#slide=id.p

**Comment by amenity** [comment]
My notes
_@mateoclarke @johnclary @dianamartin  - go ahead and edit these directly...I'm sure I missed & miss-wrote a lot of stuff._

Time logs on details page:

- Sometimes there are more than one time log for a given work order
- Day call need and emergency calls the received/go-home fields in the time logs, don't get rid of them - those that need will use
- Billy is cool with it being in both places



Sticky footer

- How did we decide on the icons in the sticky footer? 

- Likes autopopulate on start time

- Technician should not be able to edit the inventory items
- Only people doing emergency calls should 



Design system

- Icons
- Status colors



Process used to be so bad 

- Can we get photos of before and after



Attachment section on signals details page is 



New (unofficial) process

- Tech in the field opens up data tracker for CoA intersection
- Look at date and if it's been done recently they stop and don't go on
- Starts at the top and goes down
  - Am I on secondary or primary?
  - Are there bike signals?
  - No - edit signal and chand
  - Are there count logs?
  - Does it have next phase? 
  - Is it 332?
  - Are there SRs open there? Engineers need to know.
  - Are there work orders assigned tickets that aren't closed? If so, they need to fix that issue before the go.
- If any of this is wrong, they need to tell engineer



APS button requests



Trying to get away from laptops, so need to be able to see on mobile app:

- Detectors

- Work orders

- Preventitive maintenance

Do they need to be able to click on details for work order? No, they only need to be able to see: 

- Action Taken - needs to be expandable 
- Status - 
- Problem Found - 

Pilot with Toby, Gene, and Roman

**Comment by amenity** [comment]
Side thought: Love that we are making UIs look consistent across apps, e.g. adding status colors here to the mobile signals app like we have in signs app. It would be great to get a little pattern library going where we could document them so devs and app-builders could reference them as they build out. 

Might also consider user testing some things like icons. I personally don't get the "My Workorders" = 🕴️and "All Workorders" = 🚚 icons, but maybe there's precedent for this?

**Comment by dianamartin** [comment]
@amenity Yes, there is consistency on the Signs and Markings app for the status colors and symbols. I haven't added it to the Knack Style Guide, yet..

**Comment by mateoclarke** [comment]
Created an Epic for that idea here: https://github.com/cityofaustin/atd-mobile-signals-work-orders/issues/143

I think this would be really helpful once we start developing the Mobile Sign Work Orders app.
