### ISSUE TITLE
VZD | Follow up on SFTP dumps with TxDOT

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3525]
- need test implementing the automated downloads
- and follow up with TxDOT

**Comment by mateoclarke** [comment]
We got an email from Mark M on 3/2/21 saying they are updating their automated SFTP configuration for standard extract users. He asked a few questions and ultimately suggested that we create a new user account in an email on 3/22. We saw a two day pattern of records being imported but not a recurring daily extract.

I followed up today, asking if there is something missing in our setup to get the daily automation established.

**Comment by patrickm02L** [comment]
Migrated from the bot that was filling out form (automatically manually downloading) to an SFTP delivery method. 
Associated to data.transportation@austintexas.gov
