### ISSUE TITLE
Discuss VZA Locations Geographies

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3528]
@SurbhiBakshi to schedule this.

**Comment by SurbhiBakshi** [comment]
Scheduled for August 7th, 2020

**Comment by amenity** [comment]
Met on Friday and decided that while using the CTM street segments is visually messy in a map interface (particularly highways and frontage roads), we don't think that there is a compelling use case for spatial analysis or geographic visualization of VZA **_assignments_**. (Citations, yes.) The kind of reporting needed for assignments can be performed in a tally format — e.g. how many assignments in a particular school zone, council district, etc.
