### ISSUE TITLE
UC Emails - Critical Updates Needed (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3536]
### Currently the automated UC emails instruct applicants to show up physically to the wrong place. This needs to be updated ASAP.  Related to #2952

**Stakeholder:** Jacyln
**DTS Manager:** Nate

Processes that send the emails:
Application Review (82005), Permit Completeness check (51065), Web Application Acceptance (70000) and Initial Distribution (51070)

**Acceptance Criteria:**
lookupCode 90245 for lookup1 of 199 and 191
- Remove Verbiage in all UC emails stating:
"Deliver one (1) half-size paper plan set to Austin Water at 625 E 10th St (Attention: AW-Infrastructure Management AULCC Review) on the Wednesday two weeks prior to your scheduled AULCC meeting and include a screen print displaying your case, tracking or folder number. Bring a plan set to your scheduled AULCC meeting. "  

- Verbiage to be changed in the Permit Completeness Check email:
**From** "10th Floor Conference Room, One Texas Center, 505 Barton Springs Road"
**To** "Online via Microsoft TEAMS. You will receive an email invitation with the TEAMS link and optional call in number at a later date"

- Meeting Date and time will remain the same since they never change (Thursdays at 2pm)

**Comment by Nadin-Nader** [comment]
@licarir @TracyLinder I have updated the description and Acceptance criteria, please review and let me know if you need anything else to start this. Moving card to On Deck for when Robert is ready to work

**Comment by TracyLinder** [comment]
@Nadin-Nader it looks good to me!

**Comment by TracyLinder** [comment]
@licarir the pipeline for this is 'On-Deck'. Can you please update it to 'In Progress' when you begin work on it? Thanks!

**Comment by Nadin-Nader** [comment]
In today's meeting with Isaiah , Jaclyn, Robert Kaarthy and Tracy. we were able to go over which process should be sending the email.
The conclusion was to have the email tied to the Initial distribution and the Adjust Review Due Dates Process as they are used on all folders.
We also discussed "turning off" the processes (via the code) that currently send the email from and switch it to just the two processes needed

Next Steps:

Find lookup table with emails
Fix the verbiage on emails #3536
Disable current triggers that send the email to users; Possible triggers Web Application Acceptance (70000) and Permit Completeness Check 51065
Tie in the sending of email to the Initial Distribution (51070) and the Adjust Review Due Dates (61060)
@licarir Please let me know if i am missing anything from here if not pull in when ready after #3536

**Comment by licarir** [comment]
@Nadin-Nader 
Hey Nate, I have made this change on Dev. Do you know if there is an easy way to test the emails? If not, maybe you can just review the verbiage in the table to make sure I got it right? See below for records updated.
Thank you.

SELECT * FROM ValidLookup
WHERE 
Lookupcode = 90245 AND
Lookup1 IN (199,191) AND
Stampdate IS NOT null
ORDER BY Stampdate desc

**Comment by licarir** [comment]
@Nadin-Nader Have you had a minute to consider the best way to test this on Dev if possible? Maybe you can just review the records in the database/admin window?

**Comment by Nadin-Nader** [comment]
@licarir I am going to try to be an applicant on a UC then try to process it in AMANDA to see if i get the emails if not then i will check the records with the script

**Comment by Nadin-Nader** [comment]
@licarir I could not get it to send me an email but the verbiage in the table looks good. Go ahead and promote it to TEST

**Comment by TracyLinder** [comment]
**Status:** Pending promote to TEST. Updating milestone.

**Comment by licarir** [comment]
@Nadin-Nader I have promoted these two records to TEST now. Code 90245 for lookup1 of 199 and 191. Please review and let me know if it looks correct so I can get this to PROD soon. If we need to figure out how to get it to email from Test, we can work on that.
Thank you.

**Comment by Nadin-Nader** [comment]
@licarir it looks good in the lookup. Let me see if i can get Jaclyn to create and send herself or me an email, if not i will start an application and let her process it to see if i get the email. Once that is done i will let you know.

**Comment by Nadin-Nader** [comment]
Sent email to Jaclyn and Isaiah asking them to test this on TEST:

Good Morning,

Hope you are doing well. I am reaching out to you regarding the UC Email - Critical Updates card #3536. I was wanting to see if you could go ahead and test out the email and look at the verbiage on TEST to make sure it is what you want and how it’s supposed to look.

Once you have reviewed it please let me know if any changes need to be made. Once approved, the changes can go to PROD and we can start work on the UC Email Clutter.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by TracyLinder** [comment]
@Nadin-Nader can you follow up w/ Jaclyn please?

**Comment by Nadin-Nader** [comment]
Sent a second email to Jaclyn and Isaiah along with a Teams chat message asking them to test this on TEST:

From: Nader, Nadin 
Sent: Thursday, August 27, 2020 3:26 PM
To: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>; Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov>
Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
Subject: RE: UC Email - Critical Updates #3536 Follow up
Importance: High

Hi Jaclyn and Isaiah,

Hope you are both doing well. I was reaching out again regarding card 3536 the UC Email - Critical Verbiage Updates. I was wondering if you have had the chance to test this on TEST to see if the email verbiage is how it should be. Please let me know as soon as you can so we can get this all the way to PROD and avoid any more incorrect information to the Customers.

Once you have reviewed it please let me know and once approved, the changes can go to PROD and we can start work on the UC Email Clutter request.

**Comment by Nadin-Nader** [comment]
@licarir i received the response from Jaclyn in 3 different emails. I will just put her response and if there is a change,requested, then i will paste it in another comment in full.

> From: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov> 
> Subject: FW: [TEST] Application Accepted - **TEST E-MAIL. PLEASE IGNORE**
> Web Application Accepted Email
> This one looks fine. 
> Jaclyn Lozano | 1501 Toomey Rd. Austin,TX 78704 | Jaclyn.Lozano@AustinTexas.gov | 512 974 2412


> From: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov> 
> Subject: FW: [TEST] Application Accepted - **TEST E-MAIL. PLEASE IGNORE**
> Application Review Approved
> This one looks ok as well. 
> Jaclyn Lozano | 1501 Toomey Rd. Austin,TX 78704 | Jaclyn.Lozano@AustinTexas.gov | 512 974 2412

**Comment by Nadin-Nader** [comment]
@licarir here is the other one she had a comment on:

> From: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov> 
> Sent: Thursday, August 27, 2020 5:07 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Cc: Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov>
> Subject: FW: [TEST] Austin Utility Location - **TEST E-MAIL. PLEASE IGNORE**
> 
> Permit Completeness Check - 90% Submittal Result 
> 
> This one needs some changes. I have highlighted to show the changes. 
> Isaiah, do you see anything else that needs to change? The last few sentences sound outdated. It uses the term “minutes tab” and I think that was when we were using the Excel Data Workbook. 
> 
> Jaclyn Lozano | 1501 Toomey Rd. Austin,TX 78704 | Jaclyn.Lozano@AustinTexas.gov | 512 974 2412
> 
> 
> -----Original Message-----
> From: jaclyn.lozano@austintexas.gov [mailto:jaclyn.lozano@austintexas.gov] 
> Sent: Thursday, August 27, 2020 4:59 PM
> To: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>
> Subject: [TEST] Austin Utility Location - **TEST E-MAIL. PLEASE IGNORE**
> 
> **TEST E-MAIL. PLEASE IGNORE**
> 
> Hello: 
> Thank you for your submittal to the Austin Utility Location and Coordinantion Committee (AULCC). Your ROWMAN Utility Coordinantion Application has been scheduled.
> 
> AULCC Meeting date: 04-SEP-20
> Meeting Location: **Meeting Online via Microsoft Teams. You will receive an email invitation with the Teams link and optional call-in number at a later date.**     
> Meeting Starts: 2pm 
> 
> Please review your information.  
> If any data needs to be revised, added, or deleted; Please contact: 
> Reza.Sedghy@austintexas.gov 
> (512) 974-7912
> 
> Isaiah.Lewallen@austintexas.gov, AULCC@austintexas.gov 

**Email Examples**

AULCC Tracking Number #:
ROWID: 12394866
Project Name:map test cancel selection
Applicant:  Jaclyn Lozano

Project Contact:  Jaclyn Lozano

Project Description: test map for cancellation errors

1.  Once the Project is reviewed, please begin a Spreadsheet or Minutes Sheet to record resposes, identify areas of conflict, and note proposed resolutions. 
-   Projects that have been through the AULCC previously, most must contain all utility comments from previous reviews. The Minutes tab, or a Conflict/Resolution spreadsheet should be utilized for this effort.                 
-  Final review and clearance will be contingent on final review of the Conflict/Resolution Data and concurrence form the Project Engineer, Project Manager, Project Owner, and the AULCC Chairman.                                      
2.      A Final AULCC Clearance Letter will be granted to the Project once all the conflicts have been identified, and resolution has been verified. This letter will be required for General Permit, or Site Plan submittal to the Development Services Department Intake office on the 4th floor of One Texas Center.

**Comment by Nadin-Nader** [comment]
@licarir email from and too Isaiah:

From: Nader, Nadin 
Sent: Friday, August 28, 2020 8:05 AM
To: Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov>; Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>
Subject: RE: [TEST] Austin Utility Location - **TEST E-MAIL. PLEASE IGNORE**

Good Morning Isaiah and Jaclyn,

I have updated the card for Robert, I did want to ask you where you would like us to put Jaclyn’s address and if you meant Email or Work address. Did you want us to replace the Highlighted yellow and crossed out email address from Permit completeness Check example?

From: Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov> 
Sent: Thursday, August 27, 2020 6:15 PM
To: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>; Nader, Nadin <Nadin.Nader@austintexas.gov>
Subject: RE: [TEST] Austin Utility Location - **TEST E-MAIL. PLEASE IGNORE**

Jaclyn

Thanks for testing it, but you don’t get off the hook just for that.

Nate

Put Jaclyn’s address in there too, please.

Thank you

Isaiah Lewallen
Engineering Associate C
Utility Coordinator
Austin Transportation Department
Right-of-way Management Division

isaiah.lewallen@austintexas.gov
512-974-1479

**Comment by licarir** [comment]
Text template changes should be worked out beforehand. This slows down work having to redo something that could have been figured out by looking at an email as it stood. It is possible that people changed positions or the directives changed between beginning work and now. I will try to get back to this soon.

**Comment by TracyLinder** [comment]
**Status:** Work is currently in Test and will be moved to DEV. Then Robert will make the fixes, and promote back to test.

**Comment by licarir** [comment]
@Nadin-Nader Did you receive a response from Isaiah?

My takeaways are to update one email template for lookupcode 90245 either 191 or 199 (to be discovered today by looking at the table).
Change 'most' to 'must' in paragraph.
Remove Reza email
Remove phone number
Add Isaiah, aulcc, and Jaclyn emails in a list at contact info

**Comment by licarir** [comment]
@TracyLinder @Nadin-Nader These changes have made it back to Test. Please coordinate UAT. Thank you.

**Comment by licarir** [comment]
All the emails look good to me. Thank you!

Jaclyn Lozano | 1501 Toomey Rd. Austin,TX 78704 | Jaclyn.Lozano@AustinTexas.gov | 512 974 2412

@Nadin-Nader Can I move this to PROD?

**Comment by licarir** [comment]
Thank you. I have requested this be promoted to PROD now.

**Comment by TracyLinder** [comment]
**Status:** In Prod!! @Nadin-Nader will you let the stakeholders know & close this out please.

**Comment by Nadin-Nader** [comment]
@TracyLinder @licarir sent email to Jaclyn and Isaiah informing them that this is on PROD and that i was closing the issue. See email below:

> Jaclyn/Isaiah,
> 
> Hope you both are doing well. I am reaching out to you regarding Issue 3536 UC Emails - Critical Updates Needed. I wanted to inform you that the changes to the verbiage has been deployed to PROD.
> 
> Now that this has been deployed to PROD we can start looking at 2952 UC Automated Email Clutter and see what sprint would be best to start this. I will send you an update about that once our team has discussed it. 
> 
> I will go ahead and close out this issue 3536. If there are any concerns, Please let us know. 
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services 
> Austin Transportation Department
>

**Comment by Nadin-Nader** [comment]
From: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov> 
Sent: Thursday, September 24, 2020 5:31 PM
To: Nader, Nadin <Nadin.Nader@austintexas.gov>; Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov>
Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>; Licari, Robert <Robert.Licari@austintexas.gov>
Subject: RE: UC Emails - Critical Updates Needed #3536

Sounds good. If you need any additional info, feel free to reach out. 
Thank you Nadin


Jaclyn Lozano | 1501 Toomey Rd. Austin,TX 78704 | Jaclyn.Lozano@AustinTexas.gov | 512 974 2412
