### ISSUE TITLE
Update ROW Portal Banner

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3540]
As described [here](https://app.gitbook.com/@atd-dts/s/atd-knack-operations/knack/style-guide) create a banner for the ROW app with the title "Right-of-Way Operations".

This is the app: https://builder.knack.com/atd/row

**Comment by ChrispinP** [comment]
The Gimp site is blocked for me on work laptop either need whitelisted, application installation, or complete on personal computer

**Comment by ChrispinP** [comment]
Banner files uploaded to G drive. Banner updated in ROW app.
![image](https://user-images.githubusercontent.com/67915167/89443603-1df3f100-d716-11ea-95c5-7b70d1f978d3.png)

**Comment by ChrispinP** [comment]
I checked some of the other banners for our apps, some scales are slightly off but I saw Data Tracker does not have a banner and the Vision Zero in Action is missing the ATD part of the banner.

Should I update these as well?

**Comment by ChrispinP** [comment]
complete

**Comment by ChrispinP** [comment]
complete, verified all banners and headers
