### ISSUE TITLE
[RPP Back Office] Modify Application Record

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3549]
The wrong permit #'s for Decals and Hang Tags was entered into RPP application # 2020-0789 for  
customer: Erin McDowell
residential address: 2109 Thornton Road
The permit #'s 4479, 4480, 4722 and 4723 need to be deleted so the new permit #'s can be entered.

**Comment by SurbhiBakshi** [comment]
@moorerst - I can look into this today.

**Comment by ChrispinP** [comment]
Erin McDowell customer record is now linked to the permit application 2020-0789.

Decal #'s for Permit records 1492 - 1495 for Erin have been removed.

What are the correct decal #'s for these permits?

**Comment by moorerst** [comment]
I asked Steve to provide the correct #'s but I have not received them yet. Will provide them once I get them from Steve. Thks

**Comment by ChrispinP** [comment]
PERMIT #'S 4485-4486 (DECALS) & #'S 4729-4730 (HANG-TAGS) added to records 1492-1495 for Erin McDowell

complete
