### ISSUE TITLE
Polygon drawing tool enhancements

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3550]
John has some suggestions for enhancing the polygon drawing tool on the map page:
- [ ]  clicking the trash icon cancels the polygon drawing
- [ ] double-click to complete drawing (rather than having to click back to the first point you drew) 
- [ ] add the polygon drawing tooltips that Mateo built for the scooter data explorer

**Comment by JaceDeloney** [comment]
De-prioritizing based on hotjar data

**Clicks Heatmap**
![Screen Shot 2020-08-11 at 3.58.39 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/a396c2c7-84e1-4549-8cbd-e025ee259b74)

**Cursor Move Heatmap**
![Screen Shot 2020-08-11 at 4.01.46 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/ae3cb915-eaf4-4520-b2d1-5f38536c7f74)

**Taps Heatmap (Mobile)**
![Screen Shot 2020-08-11 at 4.03.10 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/3e73064b-5faf-404f-9807-131b9b435323)

**Comment by patrickm02L** [comment]
@patrickm02L take a look at this, and break it down. Bookmark to touch base with Lewis about. 

Early research with users brought this idea as something they wanted. The were interesting in replicating an existing workflow in Vision Zero Viewer. MS2, which was a crash diagramming tool. (ms2soft.com)

Stakeholders wanted an interactive map to draw polygons to pull out crashes for those locations, and be able to export them to excel. 

There's value in fixing the bug where the polygon tool does not close and turns into a white screen. Focusing on the polygon enhancements is less of a priority, but we could think about how to make it more discoverable in the future.

**Comment by patrickm02L** [comment]
There hasn't been any attention for polygon tools enhancements since we last commented. The white screen Issue was resolved with #9714.

25+ months of inactivity. Considering this a dead Issue.
