### ISSUE TITLE
[RPP Back Office] Verify Report Criteria

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3552]
In the RPP application Reports Page I filtered the following reports:
Number of Permits Issued  for Issue Date is for the previous 1 month
Revenue By Payment Type for Issue Date is for the previous 1 month

The results don't seem to match
Number of Permits issued
Hang Tags / 431 x 16.24 each = $6999.44
Decals / 426 x 16.24 each = $6918.24
Day Passes / 24 x $1.08 each = $25.92
Total $13,943.60

The Total Revenue amounts are displaying 
Day Passes - $1611.90
Decals - $24,666.81
Hang Tags - $23,658.12

Specially the Orange Zone for July seems to be too high

Can we look into how this is calculated?

(https://atd.knack.com/parking#reports/?view_225_0_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_85%22%2C%22operator%22%3A%22is%20during%20the%20previous%22%2C%22range%22%3A%221%22%2C%22type%22%3A%22months%22%2C%22field_name%22%3A%22Issued%20Date%22%7D%5D%7D&view_225_1_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_85%22%2C%22operator%22%3A%22is%20during%20the%20previous%22%2C%22range%22%3A%221%22%2C%22type%22%3A%22months%22%2C%22field_name%22%3A%22Issued%20Date%22%7D%5D%7D))

**Comment by SurbhiBakshi** [comment]
@moorerst - can we talk about this request?

**Comment by ChrispinP** [comment]
I looked at this and found 2 discrepancies:
![image](https://user-images.githubusercontent.com/67915167/89320847-abb4db00-d647-11ea-8aee-46a2c93f768d.png)
Where is this field located? Is this an integration? Cant find it in RPP.

![image](https://user-images.githubusercontent.com/67915167/89320973-e9196880-d647-11ea-804e-8f4ea1cc031a.png)
This is a new field that calculates total decals instead of the old Requested Permits field. I fixed the formula.

**Comment by moorerst** [comment]
The issue is with the Revenue By Payment Type chart - it is not calculating the correct revenue for each Permit Type. 
We can discuss via Teams when it's a good time for both of you.

**Comment by SurbhiBakshi** [comment]
@moorerst sounds good

**Comment by SurbhiBakshi** [comment]
@ChrispinP @moorerst - scheduled some time this Thursday 08/06

**Comment by SurbhiBakshi** [comment]
Hang Tags / 448 x 16.24 each = $7,275.52
Decals / 441 x 16.24 each = $7,161.84
Day Passes / 24 x $1.08 each = $25.92
Total $14,463.28

The Total Revenue amounts are displaying
Day Passes - $1611.90
Decals - $25,348
Hang Tags - $24,535

**Comment by SurbhiBakshi** [comment]
The permit numbers by type look right across districts, the calculation for fees looks right as well. The problem does not seem to lie with the objects, but the report at the end is what is throwing the calculations off.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/57da4f9a-f003-48a7-b875-f838bbbadf41)

**Comment by SurbhiBakshi** [comment]
looked into creating a different type of field in the object, a number field instead of the currency type, but with the same results.

**Comment by SurbhiBakshi** [comment]
- [ ] add field for cost per permit/ day pass - conditional
- [ ] add field for number of permits/ day pass - conditional
- [ ] add equation field calculating the cost of permits/ day passes
- [ ] Change the 'Total Number of Records' in 'Number of Permits Issued' to 'Number of Permit'
- [ ] Change the field in 'Revenue by Payment Type' to 'Cost of Permits/Day Passes'

**Comment by moorerst** [comment]
@SurbhiBakshi the modifications you made seem to be calculating correctly.  I checked the numbers in the two charts and they seem accurate

**Comment by SurbhiBakshi** [comment]
@moorerst - glad to hear that! I am going to check the rest of the tables and see if any of those fields need to be redirected. I have the list above your comment, will let you know when I am done, will be glad to get those as well reviewed by you.

**Comment by SurbhiBakshi** [comment]
@moorerst - I finished the above listed changes, have assigned #3634 to Chrispin to look into the Transaction date. Going to move this issue into Review/ QA for now. Please review and let me know if you see any thing else.

**Comment by moorerst** [comment]
@SurbhiBakshi when checking the reports something seems off. The number of permits issued and the revenue was in sync yesterday but is off today.
920 decals @ 16.24 is 14,940.80 not 10,036.32
The Monthly Permit Issuance Trends table looks correct but the Total Revenue - All Districts table is missing data for April, Dec, Feb, May and Nov
Is this related to the Transaction Date issue?

**Comment by SurbhiBakshi** [comment]
@moorerst - yes, I took off the transaction month filter I had on The Revenue by Permit Type chart
and I took the Total Revenue - All Districts off because I was using that to cross-reference. 

Think this might be better in the Blocked lane since we need to know more about getting the Transaction Month filled out or think of another substitute. Wondering if we could use Issue Month instead if getting the Transaction Month is not possible.

**Comment by SurbhiBakshi** [comment]
blocked by #3634

**Comment by SurbhiBakshi** [comment]
@moorerst @ChrispinP  - Should I icebox or close the two reporting issues, since the data structure changed, reporting would need to be redone.

**Comment by moorerst** [comment]
@SurbhiBakshi I would say lets icebox them until we have a chance to see look into reporting in more detail in the near future

**Comment by ChrispinP** [comment]
this issue has come a long way but its time to say farewell. new data structure, new reporting. built successfully in test and looking to additionally add new fields that will provide more accurate reporting and deliver the results we expect.

check out issue #4590 for a list of fields being added, updated, or removed to get reporting into a positive state

closing
