### ISSUE TITLE
Add a crash_time requirement to temp crash record creation 

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3553]
The ETL process requires a date/time object to run properly (this is used in the date/time filter in the map view). The original temp record creation UI did not have a `crash_time` as a requirement, so that field was null when it gets concatenated into the date/time object. 

- [ ] Add `crash_time` as a requirement to the temporary crash record creation process.

**Comment by mateoclarke** [comment]
This was completed with https://github.com/cityofaustin/atd-vz-data/pull/895
