### ISSUE TITLE
VZ | ETL | Choose Socrata dataset to publish to based on environmental variables

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#3554]
Currently, the Socrata ETL is hardcoded to publish to the production Socrata dataset regardless of whether production or staging environmental variables are passed to the script. This causes unexpected results and increases the risk of clearing the production dataset or overwriting the production data with test data when not intending to. This needs to be improved to choose the target dataset based on the environmental variables.

**Comment by patrickm02L** [comment]
This was covered with the Airflow 2 migration.
