### ISSUE TITLE
Flag bad CRIS geocodes

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3563]
There are crashes (including some crashes w serious injuries) that have incorrect geocodes. This is causing some crashes that occur in other jurisdictions to show up in City of Austin Full Purpose and may also cause some crashes that have occurred in City of Austin Full Purpose to be geocoded to a different, incorrect jurisdiction.

Steps needed to address this issue:
1. Update CRIS ETL to query crashes from all responding agencies in our jurisdiction
2. Run our own geocoding processes (with HERE) against those records.
3. Flag records with a low geocode score
4. implement some sort of flagging system for new crash records that have bad geocodes

This would allow the VZ team to know that there might be a problem with a crash record's geocode
(e.g. travis county sherrif's office files a crash report that is actually outside the city limits, but gets geocoded to inside Austin city limits. assuming that had a low geocode score, we could flag it for review.) because if we start querying by agency instead of county, we will have to filter out crashes that are not in our jurisdiction. but we can't do that based on the geocodes that CRIS provides, because we don't trust them.

There are 197 crashes since 2015 that are in the Austin Full Purpose, but don't have an Investigating Agency listed in the 10 below:
AUSTIN ISD POLICE DEPARTMENT
AUSTIN POLICE DEPARTMENT
CEDAR PARK POLICE DEPARTMENT
PFLUGERVILLE POLICE DEPARTMENT
SUNSET VALLEY POLICE DEPARTMENT
TEXAS DEPARTMENT OF PUBLIC SAFETY
TRAVIS COUNTY CONSTABLE PRECINCT 4
TRAVIS COUNTY SHERIFF'S OFFICE
UNIVERSITY OF TEXAS AT AUSTIN POLICE DEPARTMENT
WILLIAMSON COUNTY SHERIFF'S OFFICE

**Comment by JaceDeloney** [comment]
@JaceDeloney to find an example crash

**Comment by patrickm02L** [comment]
This might have been a reaction to an edge case when it was initially created.

A possible direction going forward would be to ask a GIS person to do further analysis on the problem to get the scale of it. 

Through extensive QA/QC the VZ team has not identify serious flaws in our crash acquisition methods, and will continue to monitor the data as it comes in.

**Comment by patrickm02L** [comment]
Was resolved by #10126
