### ISSUE TITLE
Update ETL to filter out records that do not have a crash_date or crash_time

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3564]
Part of the [action items](https://docs.google.com/document/d/1ZwgDHICk1ZuvyoNJdV9-kw2ehXoxeryfOB6qYLO6EXk/edit?usp=sharing) from the 8/3 no data incident was to update the ETL to filter our records that do not have a crash_date or crash_time. This is really a fall back because the temporary crash record UI feature should now require crash_date and crash_time.

**Comment by sergiogcx** [comment]
We really need to turn on the ETL as soon as possible, I've created a branch with a quick patch addressing the two fields.
