### ISSUE TITLE
Fix ETL to Revert last successful data upload if the ETL fails

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3575]
Fix ETL to Revert last successful data upload if the ETL fails (AKA: fail loudly, but not in a way that breaks VZV with no data)

- Add a script in ETL to save successful data as csv (saving as JSON would be easier for reading/writing, right?) to S3
- Update ETL to use an old version of the static file in S3 if script fails (ETL should make sure that the backup file exists before truncating the socrata table. e.g. first step of ETL: download backup file)

**Comment by sergiogcx** [comment]
We just have to make sure we are ready to re-enable.

**Comment by sergiogcx** [comment]
Ideas:
1. I need to find ways to create backs within Socrata.
2. Extract data from Socrata
3. Rehearsal of the extraction and insertion.

Problems or constraints:
- Currently VisionZero Viewer looses all its data for 15 minutes.
- The amount of disk space in the airflow server.

**Comment by sergiogcx** [comment]
Alternative:
- Insert to staging first, if all succeeds proceed to insert to production.

Pros:
- Easier to implement
- Staging and production always stay updated.

Cons:
- Does not have backups, no way of rolling back.

**Comment by sergiogcx** [comment]
Since the ETL is not even active, I am going to go ahead and merge this in without review:
https://github.com/cityofaustin/atd-vz-data/pull/904

This basically allows us to pass via environment variables the names of the dataset we need the script to upsert to.

**Comment by sergiogcx** [comment]
After speaking yesterday with @JaceDeloney, we are going to try implementing this in production on Wednesday evening.

**Comment by sergiogcx** [comment]
For production, I first have created two backups:

```
curl --silent --location --request GET   --header "Cache-Control: no-cache"   --header "Accept: */*"   --header "Accept-Encoding: gzip, deflate, br"   --header "Connection: keep-alive"   "https://data.austintexas.gov/resource/y2wy-tgr5.csv?\$limit=9999999"   --output crashes.json.gz


curl --silent --location --request GET   --header "Cache-Control: no-cache"   --header "Accept: */*"   --header "Accept-Encoding: gzip, deflate, br"   --header "Connection: keep-alive"   "https://data.austintexas.gov/resource/xecs-rpy9.csv?\$limit=9999999"   --output persons.json.gz
```
