### ISSUE TITLE
Decide on Geocoding QA workflow

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#358]
1. Human QA Interface in Knack
2. Geocoding processing for missing geocodes
3. Automated QA of TxDOT lat/lon vs addresses

**Comment by sergiogcx** [comment]
As a quick comment, I remember Lewis saying he didn't like the idea of having too many columns containing different lat/longs.

We could have the only two columns for lat/long, and a couple more specifying 1) the origin of the coordinates (Human review, CRIS, CR3, Here, Google, ESRI, etc), 2) The status (Confirmed, Accurate, Not reviewed, pending review, etc), 3) Last update timestamp

**Comment by mateoclarke** [comment]
I remember different. I remember his asking if it was a problem, and I think @johnclary's response was no, not really. I could be totally misremembering though.

**Comment by sergiogcx** [comment]
I remember John's comment, not opposed to either, but maybe have two more columns (one set) of lat/long with geocoding, that could help us determine the difference between what is provided by CRIS and what our GeoCoding determines is the best point for an address.

**Comment by johnclary** [comment]
Hmm. What about:
-  the original lat/lon from chris (two columns)
- our geocoded results (two columns)
- the QA/confirmed lat/lon (two colums)
- the QA status (confirmed, pending, ...?)

Wondering if we want to track which source was ultimately used as the confirmed lat lon (CRIS, our gecooder, or manual adjustment)?

**Comment by sergiogcx** [comment]
@johnclary Awesome, I can live with that. The extra columns will give us enough room to work with.

**Comment by sergiogcx** [comment]
Implementing on issue #445, closing this one.
