### ISSUE TITLE
Resolve 'Undefined' error for Data Tracker login

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#3584]
When users, for example Larry M try to change their password, this is what they see . 

The last line in the specifications for a password reset looks off.

**Comment by SurbhiBakshi** [comment]
When users, for example Larry M try to change their password, this is what they see. The last line in the specifications for a password reset looks off.

**Comment by SurbhiBakshi** [comment]
![Screen Shot 2020-08-05 at 5.19.30 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/d4a37ad3-c253-4042-a8fd-79c6554a6c0b)


![Screen Shot 2020-08-05 at 5.24.25 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/766702ef-e0fc-4a96-a630-c20b073e28b0)

**Comment by dianamartin** [comment]
This isn't urgent, users can still change their password. The view just looks buggy bc of the "_undefinedundefinedundefinedundefined_". Would be nice to replicate and check the page code source to see what is going on.

**Comment by johnclary** [comment]
See also this [VZA issue](https://github.com/cityofaustin/atd-data-tech/issues/5047) which appears to be the same issue.

**Comment by johnclary** [comment]
It's been a long time since we've heard of this problem. I'm going to close this this.
