### ISSUE TITLE
GIMOB Meeting - August 2020

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#3588]
@johnclary see below for notes:
# GIS Community Committee
- Looking for volunteers to join the group (if interested talk to Pamela Quarles or RoxAnne Parker)
- New Bloomfire Spark will be coming to the city soon (8/9/20 at 7pm)
- Short Demo to show the new interface - will need to search through the filter
- CTM hired a new Communications person for the GIS Group, Stephanie Gregory
# Open Discussion to talk about GIS while working remotely
- RoxAnne has lag at home, extra distractions, not as comfortable, likes to be around co-workers, printers/plotters, using Teams was a challenge, got a new home computer which is helping
- Allison H. uses GoToMyPC to connect to computer, has a MacBook Pro at home, uses Teams on her home computer.
- Daniel D. supervises 8 GIS people, all using GoToMyPC, mix of COA laptops and personnel devices. Maintaining a descent rate of productivity. Explored NetMotion to Remote Desktop but isn't working for most. GoToMyPC is laggy.
- Dolph's group is using GoToMyPC, but he's using NetMotion and is hideous for him. Having issues with Pro throughout Austin Water. AW has a one device policy which makes things difficult. Looking into virtual machines.
- Bryan PW - GoToMyPC, NetMotion with laptops connecting to the databases, Cisco AnyConnect VPN is working pretty good.
- PW is using AGOL data vs. GISDM when only needing to view data.
- I shared how I use GIS, John Cook is interested in the details, will reach out separately.
# GIS Modernization Project - Shannon
- Project is on track and in good health
- More training courses are becoming available for Pro
- CTM is seeing that some City computers are still below 10.6.1
- Developing an SOP for transitioning to Pro, would like to add that to Service-Now
- Planning Phase 2 departments in the next few months
# Data Purchases
- LiDAR request has been submitted, 4 points/square meter for watershed area, Full Purpose looking at 8 & 12 points/square meter unless it's too expensive.
- Aerials, we are being included in the TNRIS aerial project, same area as 2019.
# APD Architectural Review
- Initial conversations with Esri about performance problems that APD is having
- Meeting to get Enterprise requirements coming up
# Governing Board Roadmap
- Has been approved and they are moving forward through 2022.
# AGOL Committee
- Next meeting on 8/19/20
- New WebMap Viewer is up, talked about new functionality
- Come to next meeting to discuss the new WebMap Viewer
- Federated Login for AGOL, always had issues with other domains. They have added Azure Active Directory for login, and now everyone can use the Federated Login.
- Janny has a list of the new compatibles between the old and new Web App Viewer
- Can't currently add REST URLs to the new Map Viewer
- Burn rate of credits is high for AGOL, wanted to let everyone know. We have been using more due to Geocoding for APH and COVID-19. Currently spend 1500 credits / day just on storage. **(We need to clean-up our area!, can send an email to all AGOL Users to clean up their content.)**
# Geospatial Technology Management
- Upgrading Enterprise GDB to 10.7.1. Any application or automation in MAINT, APP, or GISDM
- Need to be up to 10.6.1 to be able to connect to SDE after the upgrade **(need to get an install list from Scott again!)**
- We may have to go to 10.8.1 early next year due to Oracle upgrading

![image](https://user-images.githubusercontent.com/48842809/89555535-c917af80-d7d5-11ea-888a-74b040c8bdbe.png)

# APH
- Has been getting a lot of requests for the data, only the data in the Dashboard is available publicly.
https://atc-covid19data-austin.hub.arcgis.com/
# ARR
- Currently searching for a new IT Application Analyst Senior, new person to oversee the departments technology for the fleet.

**Comment by johnclary** [comment]
thanks @jaime-mckeown !
