### ISSUE TITLE
Waze Feed Processor evaluation

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#359]
Evaluate the effort and benefit of upgrading our Waze data feed

from @johnclary:

> Sergio—I'd like to hear your thoughts on this project. We have access to the Waze CCP feed and our former teammate (Joey) create a simple Python script which archives the feed to a postgres DB. This cloud implementation seemed like overkill, but I'd be happy to support this project.

> https://github.com/LouisvilleMetro/WazeCCPProcessor

**Comment by ChristinaTremel** [comment]
@johnclary do you think we can close this or should we leave it in the icebox? 🥶

**Comment by johnclary** [comment]
closed!
