### ISSUE TITLE
TCP Tracker: New Field - Deficiency Type

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3597]
- **New: Deficiency Type**
    - Type: Drop down
    - Values: Darren will send us a list to add
    - Does not allow users to add new values, 
    - Allows users to select multiple values 
    - Lives on the 'Submissions' table
    - Column is added to Submissions view on the TCP Details Page
    - ![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/8b65a19f-e4db-4d18-93b6-b98e8122a403)

**Comment by ChrispinP** [comment]
new field added with help text. received field values from Darren and updated.

**Comment by ChrispinP** [comment]
Added Deficiency Type field to TCP Submission form

Ready for review

**Comment by ChrispinP** [comment]
Deficiencies built in Test

New Grandchild object connected to Submissions
![image](https://user-images.githubusercontent.com/67915167/128227809-efdf4892-c530-4ada-9536-0b0005fcebf4.png)
![image](https://user-images.githubusercontent.com/67915167/128227883-a31e1c13-33c9-4ded-9553-fa322a337126.png)

Submissions Table
![image](https://user-images.githubusercontent.com/67915167/128227598-a929a867-fd95-42c5-8f09-36b17d061db6.png)

TCP Details
![image](https://user-images.githubusercontent.com/67915167/128227616-95cf323b-d1fc-42bd-8f51-b777be40383c.png)

**Comment by dianamartin** [comment]
@ChrispinP It looks like the Edit Deficiencies have some customizations on them, any particular reason?

## Custom In-line Edit Multi-choice selection
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/876e824c-3bfa-444a-b8c0-bb88aedd5f10)

## Default In-line Edit Multi-choice selection
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/816202f3-cc1d-45c4-8bb4-a930fd97ab71)

**Comment by ChrispinP** [comment]
@dianamartin oh, thats why we added the dash, because that box doesnt appear around the connected field like those names. I wonder if this is intended by knack or a bug.

**Comment by dianamartin** [comment]
@ChrispinP so when we added the dash, the background color changed from grey to white?

**Comment by ChrispinP** [comment]
No issues, closing
