### ISSUE TITLE
TCP Tracker: New Field - CIP?

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3599]
- New: **Capital Improvement Project?**
    - Type: Pick/Select
    - Values: CIP, Non-CIP
    - Does not allow users to add new values
    - Allows only one value to be selected by users
    - Lives in  'TCP Details' table
    -  Field is added to '[Add TCP' form](https://data.mobility.austin.gov/data-tracker/#tcp-tracking/add-tcp-tracking/)
    - Field is added to these views: TCP Details, Export Submissions, TCP Tracking

**Comment by ChrispinP** [comment]
new field added with help text

**Comment by ChrispinP** [comment]
CIP field added to TCP Submission form

Ready for review

**Comment by ChrispinP** [comment]
CIP field built in Test.

New TCP form
![image](https://user-images.githubusercontent.com/67915167/128084802-56e9fd71-e754-4e04-b52c-ff74b26166bb.png)


TCP Reviews page
![image](https://user-images.githubusercontent.com/67915167/128084748-7b305570-d4f8-4dbc-b825-7616b5571e90.png)


TCP Details page
![image](https://user-images.githubusercontent.com/67915167/128084572-88c0717c-c5d2-4505-bfd5-9d730a4a0d60.png)


TCP Project Search page
![image](https://user-images.githubusercontent.com/67915167/128084344-f5d8f9fd-6d1e-478c-b51d-7ae934b9cbaf.png)

Discovery:
- [ ] Should this field be Required?
- [ ] Be positioned after, before, or next to a specific field?

**Comment by dianamartin** [comment]
@ChrispinP Reviewed feature, looks good to push to PROD. 

### Observances
- the search fields in the Advanced Search might need some rearranging
- Account Management should be on two lines, there is enough real estate on the menu bar or simply renaming to "Accounts" would be sufficient too

**Comment by ChrispinP** [comment]
No issues, closing
