### ISSUE TITLE
TCP Tracker: New Field - Total # Deficiencies

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3600]
- **New: Total # of Deficiencies** 
    - Type: Auto-Calulated Field
    - Logic: Calculates the total number of deficiencies on the Submissions Table
    - Lives in  'TCP Details' table
    - Field is added to: TCP Details view, [TCP Tracking Table](https://data.mobility.austin.gov/data-tracker/#tcp-tracking/)

**Comment by ChrispinP** [comment]
field created but need to update with formula

**Comment by ChrispinP** [comment]
Built in Test

TCP Details and Submissions Table
![image](https://user-images.githubusercontent.com/67915167/128228843-6167e90c-7fee-43c7-bf4f-6a8c56ab2434.png)

TCP Reviews table
![image](https://user-images.githubusercontent.com/67915167/128228937-1c088170-dae0-4c50-bbee-a63a00e3be19.png)

**Comment by dianamartin** [comment]
@ChrispinP so this one is related to #3597, the screen shots from it?

**Comment by ChrispinP** [comment]
@dianamartin exactly, I used the same screenshots. Number of Deficiencies is a count field that counts the number of connected Deficiency records. Currently they manually input this number so this would automatically update that count.

**Comment by dianamartin** [comment]
@ChrispinP this can be pushed to PROD

**Comment by ChrispinP** [comment]
No issues, closing
