### ISSUE TITLE
TCP Tracker: Update Field - Deficiencies

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3602]
- **Update: Deficiencies Field**
    - Customer is requesting that the 'Deficiency' field on the 'Submissions' page auto-calculate based on the number of values selected in 'Deficiency Types' field. 
    - The 'Deficiencies' field lives on the 'Submissions' table

![image](https://user-images.githubusercontent.com/49930868/89667243-6986d600-d8a1-11ea-9901-bbd9f768f92f.png)

**Comment by ChrispinP** [comment]
Field added, formula to be updated

**Comment by ChrispinP** [comment]
Built in Test

TCP Details and Submissions Table
![image](https://user-images.githubusercontent.com/67915167/128229224-7ed97882-8941-4b18-9979-a35bfb8bf013.png)

**Comment by dianamartin** [comment]
@ChrispinP this seems like a dup of #3600

**Comment by dianamartin** [comment]
@ChrispinP oh, I see. I remember you saying that. Okay to push to PROD

**Comment by ChrispinP** [comment]
No issues, closing
