### ISSUE TITLE
TCP Tracker Reporting: Bar Chart for Deficiency Percentage

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3604]
**New Bar Chart on TCP Reports Page**

- The bar chart shows each deficiency type and the percentage of each deficiency for the selected time frame
- Report by month if possible; by quarter if not
- Name: Deficiency Type by Month

**Comment by TracyLinder** [comment]
**Update**
- Reviewed w/ Darren, updated description, putting on backlog

**Comment by ChrispinP** [comment]
Bar Charts added for each category of Deficiency Types by %
![image](https://user-images.githubusercontent.com/67915167/149574506-dc436567-57f1-487e-aea2-d11ccf407756.png)
![image](https://user-images.githubusercontent.com/67915167/149574541-fd2f8457-831c-47e7-a890-a910d02e0a97.png)

Additionally the Deficiency Pivot Table now includes %
![image](https://user-images.githubusercontent.com/67915167/149574648-83542047-694d-409a-8b91-de840ea18fd6.png)

Submissions Pivot Table now includes Submitted Date filters
![image](https://user-images.githubusercontent.com/67915167/149574813-b60070bf-37fe-4ed6-a940-5b80db419854.png)

Number of Deficiencies and Deficient Submission % calculated for all Submissions by Submitted Date
![image](https://user-images.githubusercontent.com/67915167/149575073-9f6cb47a-885d-42b3-8d85-db2cc5fe27f6.png)

Added overall Metrics Card for all Submissions and YTD Submissions
![image](https://user-images.githubusercontent.com/67915167/149575338-53d836b6-fc4b-4a58-b8c6-483ddf4ea49a.png)

Two new TCP Reporting objects to pull overall metrics
![image](https://user-images.githubusercontent.com/67915167/149575412-54fabaf4-fe30-40c7-b16e-fc26a67913da.png)

Updated TCP Deficiency object to calculate Deficiency Percentages
![image](https://user-images.githubusercontent.com/67915167/149575671-c8a55754-efcb-46e4-97a3-cf06487b6554.png)

Updated rules for Submission fields in object and on Submissions Table
![image](https://user-images.githubusercontent.com/67915167/149575882-f9111137-e6ed-4b3b-a0cb-0c181343261f.png)

Ready to Review
