### ISSUE TITLE
Meeting: Scoping SD23 M.A.4

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3605]
**Date/Time:** 8/11/20 @ 2:30pm
**Attendees:** Tracy, Nathan A.

**Comment by TracyLinder** [comment]
### Meeting Notes

Number and percentage of development applications with a transportation analysis that meet or exceed the drive-alone trip reduction for the appropriate area type (by shifting trips to other modes and not by decreasing intensity).

- This measure is reported once annually, similar to  KIP.
- SOV = Single Occupancy Vehicles
- It takes a large amount of effort to calculate this metric, as there is not data input/capture (Bean counting)
- The % of trip reduction is dictated by the area (regions) the development is located
    - What are those area boundaries, and where do they live?
    - [ ] Find out if a GIS layer exists for this
- Regions & SOV Percentages
- TDM = Transportation Demand Management 
- SOV = 100% - the TDM reduction
- During scoping, there is an SOV goal set by reviewer. Later on during the review, the goal/ability to meet the goal may be reduced. 
    - Keep track of goal and actual outcome? - A: Not useful to track the difference. They will always be assumptions until case is closed. Project requirement: Customer must report on how this requirement has been met 1 year from approval. 
- This has not been codified yet

Fields Name: TDM Reduction Goal, the value will always be a percentage
TDM Reduction Actualized, always be a percentage
Ability to map those 2 fields to a region (see 4 categories in screenshot)

- Reporting on customer follow-up of the TDM/SOV may not be ideal right now as it's a new, undefined process. It will one day be a need.

**Comment by TracyLinder** [comment]
@TracyLinder clean up these notes, create feature issue, send to Nathan for review.

**Comment by TracyLinder** [comment]
I have it on my calendar on 9/14 to finish the outstanding tasks for this.

**Comment by johnclary** [comment]
@TracyLinder do this please

**Comment by ChrispinP** [comment]
putting in backlog, pending further scoping and review

**Comment by TracyLinder** [comment]
We need to discuss w/ stakeholders during a prioritization meeting.

**Comment by TracyLinder** [comment]
This is only meeting documentation. Closing.
