### ISSUE TITLE
Determine why crashes are unassigned to location polygons

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3606]
The Vision Zero Team is working on analysis for TxDOT grants and came across a situation where a fatal crash is 'unassigned' to a polygon. Example crash:
https://visionzero.austin.gov/editor/#/crashes/16517389

Tasks:
- [ ] Determine what is causing this crash to remain unassigned to a location polygon
- [ ] Run a report to see how many KA crashes are 'unassigned' in VZE across the city at this point?

**Comment by sergiogcx** [comment]
I think I already know, the SQS had been buggy for a little while and did not associate some crashes to locations.

The SQS is still buggy as of this moment, and I am currently working on two different solutions:

1. Refactoring and unit-testing for SQS, so we can anticipate every situation.
2. I’ve created a redundant ETL that captures anything that SQS misses for any reason. This is actually done and working in Staging, but not currently enabled in Production. I have just finished this and I wanted to see it run in staging before enabling it in prod.

More on this here: https://github.com/cityofaustin/atd-data-tech/issues/2210 (edited) 

I apologize in advance, this is a high-complexity solution, but making good progress. I can enable the ETL immediately in prod, but consider this is our backup plan that runs nightly and not in real-time. For that I am still working on SQS events.

**Comment by JaceDeloney** [comment]
Crash ID is now assigned to location in VZE
https://visionzero.austin.gov/editor/#/crashes/16517389

Jace will communicate this update to Lewis.
