### ISSUE TITLE
Talk about dev approach to Moped frontend

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3611]
@amenity here's a recap of the conversation Mateo, Mike, and I had about our approach to front-end dev in Moped. @mateoclarke @mddilley feel fee to fix up. cc @JaceDeloney @zappfyllc @sergiogcx 

## Reflections on VZE

- Most components are designed around data structure. E.g. "Crashes Page", "Locations Page".
- Notable exceptions are the data grid component and grapql wrapper.
- CoreUI's baked-in routing added complexity that we'd prefer to leave behind
- Agreement that CoreUI template's were handy for getting VZE up and running, but it might make sense to start with just a component library (one of the React bootstrap libs or Material) and not use CoreUI (that's John's opinion coming through so correct if wrong)

## On building Moped

- As much as possible, we want to write code that can be re-purposed for future admin apps.
- So we should build core components independently of Moped (ie in a separate repo), and extend/customize those components as needed for Moped.
- We should use a component explorer framework, e.g. [Storybook](https://storybook.js.org/). This will pomote documentaiton-driven development and unit testing, and will have the side effect of reminding us to keep business logic out of core components so as to keep them re-usable.
- Under this approach, we will use Moped's user stories to determine which components we build, and Moped becomes our testing ground for proving out/testing our component library.

## On transition the dev team to work on Moped

- Mateo suggested that after Sprint 31-ish, we have a dev rotation where one person focuses on VZx each sprint.

## Todo's

- make more time for VZx reflections and dev discussion on this. and obviously looking forward to @sergiogcx's thoughts
- bring the whole moped team together to talk about these things?
- Check out the [Bootstap implementations](https://fezvrasta.github.io/bootstrap-material-design/) of Material Design
- Decide on a UI framework. Sorry, but, after leaning back toward Bootstap, I think we should re-open discussion of using Material UI.
- Identify and prioritize the components we're going to build/extend from existing frameworks.
- Identify what we need to do to get Zappfy started on writing code while dev team wraps up VZx.

**Comment by mateoclarke** [comment]
Closing this now that we have https://github.com/cityofaustin/atd-data-tech/issues/3666 scheduled.
