### ISSUE TITLE
Apply style refinements to customized "All Assignments" table

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3613]
@mddilley worked all kinds of magic in #3305: <img width="1251" alt="Screen Shot 2020-08-09 at 10 26 03 PM" src="https://user-images.githubusercontent.com/1463708/89750270-d9a77e80-da90-11ea-861f-858a3c3d832e.png">

Let's do a bit of style tweaking. I think some of these are actually handled in the Builder side of things, so assigning this to you as well, @SurbhiBakshi. 🙌
- [x] Remove the teal background color from the Time column cells. 
- [x] Change the `table-group` headers to `background-color: #023F74;` and `color: white`
- [x] Remove the faint grey every-other row background color 
<img width="1234" alt="Screen Shot 2020-08-09 at 10 50 59 PM" src="https://user-images.githubusercontent.com/1463708/89751305-1b3a2880-da95-11ea-9068-149c0c54592c.png">

- [x] I'm seeing the same pagination + scrollbar + flashing header that [we had before](https://github.com/cityofaustin/atd-data-tech/issues/3248#issuecomment-655311550)... So I guess we apply a new limit to the number of records shown on each page?

Questions:
- Will we be able to retain the time/keyword filters we have in production? 
<img width="357" alt="Screen Shot 2020-08-09 at 10 36 11 PM" src="https://user-images.githubusercontent.com/1463708/89750274-dd3b0580-da90-11ea-8da5-fed4b4b9e065.png">

**Comment by mddilley** [comment]
@amenity I've thought about the time/keyword filters, and they are possible. The time filter would present no issues, but the keyword search would have to be thought about carefully so that the field that we search doesn't return single `officer_assignments` from Knack instead of the set that makes up a shift.

For example, searching for "Frank" would return only half of the `officer_assignments` that make up a shift that we would like an officer to sign up for. And, in turn, the UI would present a button to only sign up for that single `officer_assignment` instead of both "Frank" and "David" sector assignments like we intend. 

It's a tradeoff of the improvements but condensing the content provides more information per page which will make navigating available assignments faster and possibly make filters less essential. Happy to talk through this in more detail!

**Comment by amenity** [comment]
@mddilley - aha, makes total sense. I think just including time filters will help. I still suspect that officers will want to filter by sector, but Pat said that's not the case in our last meeting with him. 🙃

**Comment by SurbhiBakshi** [comment]
@amenity - worked with the Test instance
- Removed the teal
- Tried adding a background color and changed text color to white for the headers, it does not translate to the front end. I had tried this before as well before incorporating color in the time field. 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/797d4086-6070-409b-9eec-ab81cab18dfd)
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/456dd22f-5627-4795-9970-eacbb1963a48)
- I don't see a way to remove the faint grey from alternate rows. I think that is a default of the Standard Knack theme 
- limiting the number of records goes back to our discussion we had about having shifts split over pages.

**Comment by SurbhiBakshi** [comment]
@mddilley @amenity - I agree with having the preset filters set to Next Week, Next Month. We can remove the Search Word function and then check if it comes up often when we test the app with officers.

**Comment by mddilley** [comment]
@SurbhiBakshi Sorry, just seeing your comment before the previous one. I can apply the rest of the style updates needed. Thank you for diving into the Knack side of these improvements! I can override those defaults in the Knack theme with CSS styles. 👍

@amenity The records per page and the pagination logic are now defined in the custom JavaScript. Pagination is also now working and testable in the test instance.

**Comment by mddilley** [comment]
@amenity @SurbhiBakshi  I fixed the issue with the scrollbar and header flashing were re-introduced. I removed some Knack classes that were the culprit. Now, all records per page are in view and scrolled through along with the rest of the page. The rest of the CSS changes are done as well. I'll close this out once these changes are reviewed, and we decide if any more tweaks are needed.

Screenshot:
![screencapture-atd-knack-31-july-2020-test-vision-zero-in-action-2020-08-11-14_48_30](https://user-images.githubusercontent.com/37249039/89942375-0f0fb180-dbe2-11ea-8b62-27670f446fa5.png)

**Comment by SurbhiBakshi** [comment]
@mddilley it looks really good!

**Comment by amenity** [comment]
Ooohhhh, @mddilley this looks ✨beautiful✨!! Thank you. 🙏

**Comment by amenity** [comment]
@mddilley - @SurbhiBakshi is going to make that small tweak (changing the background color in the time column) and then we are good to deploy this in Production. 🙌

**Comment by mddilley** [comment]
Closing because this is deployed in VZA production already.
