### ISSUE TITLE
Implement simplified assignment cancellation 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3614]
@mddilley is [implementing customizations](https://github.com/cityofaustin/atd-data-tech/issues/3305) to allow officers to sign up for all the shifts in a given assignment at once from the _Available Assignments_ table on the _Sign Up_ page.  

We would also like to have the same functionality and styles (see #3613) on the _My Assignments_ page in both the _Today's Assignments_ and _Future Assignments_ tables. 
<img width="1234" alt="Screen Shot 2020-08-09 at 10 50 59 PM" src="https://user-images.githubusercontent.com/1463708/89758506-97406a80-daad-11ea-92a4-4b93447efe12.png">

**Comment by amenity** [comment]
@SurbhiBakshi - is this what you were thinking?

**Comment by amenity** [comment]
PS That's font awesome `circle-minus`... I wanted a circle with an x. There's also a calendar with an x, but it doesn't coordinate with the simple plus button to sign up. 

Trash could also work: 
<img width="101" alt="Screen Shot 2020-08-10 at 1 58 51 AM" src="https://user-images.githubusercontent.com/1463708/89758825-5b59d500-daae-11ea-9a76-be6f9613e55a.png">

@johnclary @SurbhiBakshi - do y'all have a pattern for remove/cancel icons?

**Comment by SurbhiBakshi** [comment]
@amenity - works for me, however  we are not giving officers the option to cancel their assignments for 'Today's Assignments' right now. It's only available for Future Assignments. Think we need to ask this question in the Sprint Review.

**Comment by amenity** [comment]
Gotcha. I added it to that agenda. 

A few questions:
- Who requested that we don't lett them cancel day-of? Can't find anything in my notes.
- In the case they can't make it, don't we want the TMC (and anyone else) to know that they will not be on that shift?
- How will the "empty" shift affect Randy's workflow for identifying canceled shifts? Does this mean he'll have to look in two places to assess what shifts have been cancelled?

**Comment by SurbhiBakshi** [comment]
@amenity - I don't remember who requested that specifically, but think it was more of a process question, in the sense that I think the officers would have notified Randy in currently adopted process. We needed to know about this in any case. We need to know who needs to be notified if the officer calls in sick for that day. After the assignment is removed from the officer's tasklist, it should follow the same policy as the 'Cancelled within 48 hours' assignments , and those will all show up in the 'Account Administration' page.

**Comment by SurbhiBakshi** [comment]
@amenity - we should probably rethink the 'Account Administration' page title as well.

**Comment by amenity** [comment]
@mddilley - would you please add an estimate to this when you get a chance?

**Comment by amenity** [comment]
Going to use the `:fa-ban:` icon here and in #3863.

**Comment by amenity** [comment]
@mddilley  — would you size this, plz? 👕🙏

**Comment by mddilley** [comment]
Here are some screenshots of the "My Assignments" page with the new tables and cancellation modal.

<img width="979" alt="Screen Shot 2020-09-18 at 3 33 18 PM" src="https://user-images.githubusercontent.com/37249039/93643892-7c271b80-f9c6-11ea-8cb1-921a9cb45980.png">

<img width="979" alt="Screen Shot 2020-09-18 at 3 34 20 PM" src="https://user-images.githubusercontent.com/37249039/93643897-7f220c00-f9c6-11ea-9325-6807069e026e.png">

**Comment by amenity** [comment]
@mddilley, that looks super!✨
 
I also checked to see what the tables look like when empty since in production they get a weird extra column, "Officer Shift Label," when there aren't any shifts to display. In your test instance, they are looking good: 
<img width="1305" alt="Screen Shot 2020-09-18 at 4 09 02 PM" src="https://user-images.githubusercontent.com/1463708/93645703-41bf7d80-f9ca-11ea-9344-7a2d789f2271.png">

Would it be possible to remove the "Details" and "Status" columns from the "Future Assignments" table?

**Comment by mddilley** [comment]
@amenity Yes, I can definitely remove those columns from the "Future Assignments" table.

I also realized that the links under the "Details" column of the "Future Assignments" table need to link to a different route (`#my-assignments/future-assignment-details/:record_id`). Is it okay if those links take the user to a separate page (like in the "Today's Assignments" table)? They open a modal in the original table.

**Comment by mddilley** [comment]
@amenity @SurbhiBakshi Please disregard my previous comment about the "Future Assignments" modal. I didn't realize that the Knack app is already set up to render the `#my-assignments/future-assignment-details/:record_id` path as a modal. I updated the pathname for the folder link in that table, and it renders the "Future Assignment Details" modal just like it did before replacing with the custom table. Here is a screenshot:

<img width="979" alt="Screen Shot 2020-09-21 at 12 36 37 PM" src="https://user-images.githubusercontent.com/37249039/93801097-1ecddd00-fc07-11ea-97a7-c4c94eecadd7.png">

**Comment by mddilley** [comment]
Updated "Future Assignments" table with "Details" and "Status" columns removed:
<img width="979" alt="Screen Shot 2020-09-21 at 12 58 45 PM" src="https://user-images.githubusercontent.com/37249039/93803338-512d0980-fc0a-11ea-8b7e-fe0634d1294a.png">

**Comment by amenity** [comment]
Looks 💯, @mddilley. Deploy at your leisure. cc/ @SurbhiBakshi
