### ISSUE TITLE
Remove inventory component of Knack API

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3615]
We've decided to use the Data Tracker for inventory management. Remove the inventory logic and models from [this repo](https://github.com/cityofaustin/atd-knack-api/tree/master/atd_knack_api)

**Comment by amenity** [comment]
@amenity - ask a dev to help prioritize this

**Comment by chiaberry** [comment]
the repo is archived and now this issue will be too 😴
