### ISSUE TITLE
Disable Finance & Purchasing task order integration

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3618]
We're currently [pushing task orders from the controller's office](https://github.com/cityofaustin/atd-finance-scraper) website in to the finance and purchasing system, but they're not actually used in the app. If we want to do this in the future, we can use [atd-finance-data](https://github.com/cityofaustin/atd-finance-data) (as we do in the AMD Data Tracker).

**Comment by amenity** [comment]
@johnclary - did you want to bump this to 33?

**Comment by amenity** [comment]
@amenity - ask a dev to check on this.

**Comment by johnclary** [comment]
Yes—the PR was merged but this issue didn't close. Closed.

**Comment by johnclary** [comment]
@dianamartin the "task_orders" object can be deleted from the finance and purchasing app

**Comment by dianamartin** [comment]
@johnclary There are two objects, `task_orders` and `task_orders_managed`, just making sure it's not both object that need to be deleted?

**Comment by johnclary** [comment]
@dianamartin `task_orders` - double check but I didn't see it being used anywhere.

I'm not sure what `task_orders_managed` is used for (if anything)
