### ISSUE TITLE
CCTV Image Publication Status Not Propagated to KITS

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3622]
Billy H.
AMD
>   We ran into a situation today where we needed to cut off some thumbnail generation on the fly due to a situation on the South 1st bridge.  However, when I told a few cameras to not produce thumbnails, they still did.  The one I kept an eye on in the Device Status page was Brazos Garage, and I disabled its thumbnails via the data tracker around 1 PM.  I just checked now though, and the thumbnail is dated for 1:28 PM, so it’s still producing them.   I might know why – is that one of those things that only gets checked once a day?  This kind of situation is really rare, but it can occur, so is there any way we can have the “don’t produce thumbnails” thing checked more often or some other way to stop them from generating them in times like this?

**Comment by johnclary** [comment]
> Hi Billy—Thanks for flagging this. I see there's an issue on our side. A script failed to update the "do not publish" status in KITS, which would disable the thumbnail publication. 
> 
> I'll see if I can get this fixed real quick.
> 
> Side not about the how quickly this should normally work. The script is set to run hourly, so there would typically be at most 1 hour until the thumbnail publication is disabled. Obviously, that's too long. This hasn't come up before because we usually disable the camera thumbnails due to a planned event. Will also see if we can get the lag time reduced.

**Comment by johnclary** [comment]
Appears to be an issue with our MSSQL driver version in the atd-data-publishing docker image. I'm working on it.

**Comment by amenity** [comment]
@johnclary - any updates here?

**Comment by johnclary** [comment]
too busy. backlogging.

**Comment by johnclary** [comment]
This is resolved by https://github.com/cityofaustin/atd-data-tech/issues/1046. The publication status no longer involves the KITS database.
