### ISSUE TITLE
[RPP Back Office] Grant access to RPP Reports

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3623]
Jacob C is attempting to access Report in the RPP application. Getting message Email or Password is incorrect
email is jacob.culberson@austintexas.gov
url https://atd.knack.com/parking#home/
select Sign in with COACD gets error message Email or Password is incorrect

**Comment by SurbhiBakshi** [comment]
@moorerst - @ChrispinP is having the same issue with the HR app. @ChrispinP can you try logging into the RPP app?

**Comment by SurbhiBakshi** [comment]
Jacob C did not have an account in the app, created an account for Jacob C
