### ISSUE TITLE
[RPP Back Office] Modify RPP Reports Month Order

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3625]
For RPP Reports whenever the data is monthly can we get the months to run in order instead of alphabetical? 

![image](https://user-images.githubusercontent.com/56606465/89823424-1453fa00-db17-11ea-9b3c-3faf74edf9bf.png)

**Comment by ChrispinP** [comment]
Surbhi and I found two workarounds currently:
1) concatenate month number with the month name for reports
2) use the issued date field and group by month

Reports will also need to be grouped into yearly/ytd options to separate 2020 permits from previous years.

**Comment by moorerst** [comment]
@ChrispinP question: the total of permits in the Number of Permits Issued pie chart is higher than the Monthly Permit Issuance YTD table 
hang tag / 971 - 797
decal / 942 - 799
day pass / 931 - 769
Is this because the pie chart is counting permits issued before 2020? Just want to understand the difference. Thks

**Comment by SurbhiBakshi** [comment]
@ChrispinP @moorerst - we should know which date to use for the reports - the issue date or the transaction date. We can base the month number of the chosen date.

**Comment by moorerst** [comment]
@ChrispinP @SurbhiBakshi I think i vote for using the issue date. However I'm confused by how the dates are populated. In the screenshot below the Issue Date (not shown on screenshot) and Transaction Date 8/12/2020 is before the Create Date 8/13/2020.

![image](https://user-images.githubusercontent.com/56606465/90533531-47614380-e13e-11ea-9236-fcbeca63e8b5.png)

**Comment by SurbhiBakshi** [comment]
Add field "Issued Month Number Text " to the permits object so month number is a text field. This field is a conditional that will get populated from the Issue Month field (number). 
For each report - 
- [ ] In the Source tab, add a condition to match at Source - Issued Date is not Blank
- [ ]  In the Report tab, under Table Rows in the Layout include Issued Month Number Text as Month No and Issued Month Date as Month
- [ ] In the Options tab, check Exclude Empty Groups
- [ ] In the Options tab, check Filter Menu and add two filters - 
All for all records with Issued Date is not blank 
Current Year - all records with Issued Date during the current year.

**Comment by SurbhiBakshi** [comment]
Waiting for Knack - ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/3c8132e4-cf3f-4eb0-b9ca-3c2a7063f32a)

**Comment by amenity** [comment]
@ChrispinP - when you make the issue for refactoring, mark this and #3552 as blocked by it, please. 🙏

**Comment by SurbhiBakshi** [comment]
@moorerst @ChrispinP  - Should I icebox or close the two reporting issues, since the data structure changed, reporting would need to be redone.

**Comment by ChrispinP** [comment]
going to close this issue now that i have rebuilt reporting in test. unfortunately there is no alternative to alphabetical order for knack reporting. therefore it is advisable to stay clear of trend line and tables for these purposes. reports are now built used a tabbed menu and filters using different date equations to categorize reports.
