### ISSUE TITLE
[BUG] Multiple time values on HR: Telework Request Form

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#3630]
**Describe the bug**
Workday Begin Time and End Time include multiple days worth (2 to 5 days) of the same time values

**URL**
https://atd.knack.com/hr#new-telework-request/

**What steps can we follow to reproduce the bug you are seeing?**

1. Click on Workday Begin Time dropdown or Workday End Time dropdown
2. Scroll through options to see multiple entries of the same time values

**Screenshots**
![image](https://user-images.githubusercontent.com/67915167/89836103-afef6580-db2b-11ea-8e4a-57a0e1c8a091.png)

**Application**
Knack HR app : Telework Request Form

**Device**
Desktop

**Browser**
Chrome

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [ ] Major — can only perform work using a workaround
- [ ] Minor  — can perform work, but could be easier or faster
- [x ] Does not affect work performance
- [ ] Unsure

**Additional context**
Form submits without issue, wondering if selecting two of the same time values is read as the same time or two different times in Knack

**Comment by ChrispinP** [comment]
Checked the Telework Request Form and found that these time fields do indeed contain multiple time values in them. Is it safe to remove the ones from the bottom so there are only 24 hours worth of times? @SurbhiBakshi @johnclary 

As an aside, was there a reason for not including Saturday/Sunday as options for ones workweek or is that not allowed as a city employee? 

Cheers

**Comment by johnclary** [comment]
Yes, ok to remove the dupe time values. iirc we were asked not to include saturday or sunday as options.

**Comment by ChrispinP** [comment]
Removed duplicate time values, verified drowpdowns now only showing correct values. Verified records that no empty fields are present.

complete
