### ISSUE TITLE
[BUG] Chrispin's COACD login not working for Knack HR app

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#3631]
**Describe the bug**
Unable to login to HR app with COACD login by clicking the COACD login button

**URL**
https://atd.knack.com/hr#home/

**What steps can we follow to reproduce the bug you are seeing?**
I deleted my HR record and recreated. COACD login button still not working for HR app but does work for other knack apps. After recreating record, I am able to login with a non-coa login from the new credentials i created for my new record in the builder.

**Screenshots**
![image](https://user-images.githubusercontent.com/67915167/89836947-7ae41280-db2d-11ea-908b-ee4b5b4e573f.png)

**Device**
Laptop (Reset PC, same result)

**Browser**
Chrome (Tested in MS Edge as well with same result)

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [ ] Major — can only perform work using a workaround
- [x ] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Additional context**
I noticed that the HR app requires a special character for password when i created my new non-coa login. Would this have an affect if my Active Directory password does not include a special character? Do other apps not have this requirement?

**Comment by amenity** [comment]
There's a workaround for this.
