### ISSUE TITLE
Fix typo in crash data information icon text

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3633]
Xavier let us know that there was a word missing in the crash data information icon text on the top banner. Update the info icon text
**From**
Suspected Serious Injury: A suspected serious is defined as a severe injury that prevents continuation of normal activities, including:
**To**
Suspected Serious Injury: A suspected serious injury is defined as a severe injury that prevents continuation of normal activities, including:

**Comment by mateoclarke** [comment]
I think this was a placeholder record that was manually created. But we can look more into it and try to find the CR3
