### ISSUE TITLE
[RPP Back Office] Update information on RPP Home Page and email notifications

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3638]
The following pages need to be updated in the RPP application to reflect changes to location and office hours:

- [x] RPP Home Page 

As part of Austin Transportation's concerted efforts to stop the spread of COVID-19, we have closed our permitting offices to the public and are not providing walk-in service until further notice. See below for offices that are closed and further details.

Parking and Mobility Services Permitting Office (1501 Toomey Road) - **this is a link to google maps that needs to reflect the new address 1501 Toomey Road** https://www.google.com/maps/place/1501+Toomey+Rd,+Austin,+TX+78704/@30.2632201,-97.761388,17z/data=!3m1!4b1!4m5!3m4!1s0x8644b519e0f2edf1:0xacfb1fff17d8b6b2!8m2!3d30.2632201!4d-97.7591993

- New/Renewal Residential Parking Permits are issued only on Wednesdays, between the hours of 8 a.m. – 12:00 p.m., by appointment only

- No applicants are allowed to enter the building. ATD Staff will assist applicants with curbside services

- Limited permits are being issued by regular mail with over-the-phone payments

- Staff can be reached via email at Steve.Ingenito@AustinTexas.gov or by phone at (512) 974-2891 or John Lopez by email at John.Lopez@austintexas.gov or by phone at (512) 974-1438

- [x] RPP Help Page
Update address to 1501 Toomey Road 78704
Where do I pick up my permits?
You can pick up your permits at: **1111 Rio Grande Street,** Austin TX 78701 or permits can be mailed out to you.

- [x] RPP email notifications 
Review email notifcations sent to residents to determine if they need to be updated
Submitted/Needs Review email notification
Reviewed/Approved email notification

**Comment by ChrispinP** [comment]
RPP Home Page and Help Page updated.

**Comment by ChrispinP** [comment]
No email notification updates needed.

Payment Options page did need an update though with the new google maps location, hours, and payment options/methods

This page will also need to be updated for whomever manages it: http://austintexas.gov/page/permit-application-process-residential-permit-parking-program

**Comment by moorerst** [comment]
Thanks looks like everything is up to date. One question do you know what this sad face is about?

![image](https://user-images.githubusercontent.com/56606465/90409998-73fa5a00-e06f-11ea-9cd4-9cddef1f9881.png)

**Comment by moorerst** [comment]
@ChrispinP I reviewed the page and the links. 
One update: Under In Person Payment can you remove - **Please make payment by mail or over the phone.** 
It seems confusing to have that statement when we have phone and mail payment options mentioned above. Curbside for limited days/hrs is the available option for In Person.
Everything else looks great, all the links work as expected. Thanks

**Comment by ChrispinP** [comment]
Agree. Cleaned up In-Person Payments section.

complete
