### ISSUE TITLE
Create Python + Oracle Dockerfile

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3639]
Put together a dockerfile. John needs an image that is ready for python Oracle DB development. So it needs [Oracle Instant Client](https://www.oracle.com/database/technologies/instant-client/downloads.html), python 3.8 (preferably), and [cx_Oracle](https://oracle.github.io/python-cx_Oracle/). oracle has a [docker image](https://hub.docker.com/_/oracle-instant-client) that gets him most of the way there.

**Comment by sergiogcx** [comment]
Note to self:

- I've downloaded Oracle 19 and oracle 11, will create a dockerfile for each to test the connection compatibility of the client.

- Article on medium:
https://medium.com/idomongodb/oracle-18-4-xe-on-a-docker-container-5fe8e434a34e

- Oracle's take:
https://blogs.oracle.com/oraclemagazine/deliver-oracle-database-18c-express-edition-in-containers

- Python Oracle library with high copatibility:
https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html

**Comment by sergiogcx** [comment]
Hello, this is done:

https://github.com/cityofaustin/atd-oracle-py

**Comment by sergiogcx** [comment]
I was able to connect to the Oracle DB in question via VPN:

![2020-08-12_20-39-09.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/6713b587-1ca3-4610-9b1c-ba6d4ee5fa71)

![2020-08-12_20-40-49.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ee6c5888-307d-4a9f-af3b-83a889369bda)
