### ISSUE TITLE
RW-Street Event: Update info types Event Start & End Times (SR) (Deploying to PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3641]
### Convert Event Start & Event End Time infos from text to time type.

**Stakeholders:** Maria, Laura
**DTS Manager:** Nate

- Applies to RW - Street Event only
- Event Start Time (79135)
- Event End Time (79300)
- Portal Customer should only be able to enter a valid time in these two fields during permit application

**Notes:**
Changing the field type will effect all other folders using this info. Will need to:
- Identify all folders using these infos
- Get approval from all stakeholders for changing field type
- Or, create new infos for this specific folder

**Comment by TracyLinder** [comment]
**Next Step:** Meet w/ stakeholder to identify requirements & acceptance criteria.

**Comment by vschandramouli** [comment]
Updated AC based off meeting with Stakeholders. Ready to review by @Nadin-Nader

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on confirmation from Maria about the second screenshot, if its right as well or wrong. Once we get confirmation, it can go to Backlog.

**Comment by Nadin-Nader** [comment]
Email confirmation form Maria about screenshot. The second one is wrong and the one most recently captured is correct. Moving to Backlog.

@TracyLinder @vschandramouli 

> From: Alonso, Maria <Maria.Alonso@austintexas.gov> 
> Sent: Monday, September 21, 2020 1:57 PM
> To: Vishwa chandramouli <Vishwa.c@launchitcorp.com>
> Cc: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Subject: RE: Question on Zenhub ticket 3641
> 
> Hi Vish, 
> 
> Good catch!
> 
> You are correct, we would need the help text in the screen shoot which you captured where the language is missing. 
> 
> Thanks for checking! 
> 
> Maria Alonso (she/her/hers)
> Office of Special Events
> Austin Transportation Department
> O: 512-974-7275 | M: 512-698-8061

**Comment by vschandramouli** [comment]
Removed this screenshot from the ticket as it seemed misleading. 

![7367e2e1-f327-47a1-88d2-8ae59368c0b9.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/874b8494-9cc5-4e22-bb01-8575b7fc8d4f)

**Comment by TracyLinder** [comment]
### Previous Acceptance Criteria

### As an RW-Street Event applicant completing the portal application, I'd like help text on the property free-form page that informs me that I need to input military time in the start & end time fields. 

**Stakeholder:** Maria A
**DTS Manager:** Tracy

**Acceptance Criteria:**
- When a user fills out info fields for RW-Street Event on AB+C Portal, help text 'Time is in 24-hr format' should display below each of the following info fields: 
      - Event Start Time
      - Event End Time

**Note** - Screenshot provided below for where the Help Text needs to go  

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/96cf0a41-ef1c-4e9e-bd2a-8982bc04aae3)

**Comment by TracyLinder** [comment]
@vschandramouli can you please make sure the AC on this is accurate & ready for development?

**Comment by vschandramouli** [comment]
The time format issue may be resolved once the new PIPS portal is up and running. PIPS portal automatically provides time format for these fields. The help text portion of this ticket can still be worked on. The help text 'Time is in 24-hr format' should display for the info fields marked in the screenshot below. Moving to On Deck per advice from Nadin. 

![96cf0a41-ef1c-4e9e-bd2a-8982bc04aae3.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/31895ec9-46a8-440f-91b3-2014fe52fb5f)

**Comment by Nadin-Nader** [comment]
Notes were deleted by Battery dying. I was able to speak to Maria via chat and phone over the answers to the questions in the email. We then had a meeting with Sree to discuss the possible solutions.

**Notes from Talking with Maria::**
The below Subtypes below have Event Start time and Event End time info’s. Other than these subtypes; its not used any where in RW.
RW - Street Event
RW - Valet Parking Annual
RW - Street Vendor
RW - Valet Parking Temporary

Question is, can we disable the info field in back office? This is so that no one can enter or update the info except the internet user. When internet user updates the info online or in portal the value will be saved to see in back office. But cant be updated.
**Answer:** No, this field cannot be disabled as it is used by other users and can be updated by an event time change.**

	Since the changes are applicable to street event folder only, we can just disable only for the RW subtype – Street event. If this solution works then no need to create any new info’s etc.,
**Answer:**  No, this field cannot be disabled as it can be updated by an event time change.**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan Approval has been given for either of the solutions proposed

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan Per Tracy, we are moving this back to Backlog

**Comment by TracyLinder** [comment]
I'm moving this to the backlog until V7 goes live.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Had a meeting with Maria to confirm the solution. Development is in Progress.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - DEV DP of #3641 submitted. Kindly approve and create task id for me. This can’t be tested in Localhost and moving the changes to DEV so, that I can test it. 

Commit ID: [f9ea65eebbf4](http://coaamandadevops02.austintexas.gov/R5:f9ea65eebbf4c1e55518ef34b80e1204dbf8276c)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps Team to be deployed to DEV under **SCTASK0271957**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV and found that all functionality is working except the display format of new info field start date and time is not getting displayed with time. So, updated the table display format tested in Localhost submitting 2nd commit changes now. DEV DP of #3641 Commit 2 submitted. Kindly approve and create task id for the same.


Commit ID: [0bc7d4db3ca1](http://coaamandadevops02.austintexas.gov/R5:0bc7d4db3ca123fbf249302a3065bac165447d53)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have sent this to the DevOps CM Team to be deployed to DEV under **SCTASK0273633**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Getting a dev portal error to create a RW-Street event folder in DEV; Informed Swapna about this yesterday; and she is looking into DEV. However this cant be tested until I move the changes to TEST or wait until DEV is fixed. Kindly suggest further action on this. Thank you! Swapna also mentioned that, she will let me know once it is fixed in DEV.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan lets give Swapna a few days to fix Dev. If not ready by next Wednesday 1/11/23 let's move to Test without UAT in DEV.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Dev Portal was working when I tested in the morning, created a test folder and tried to test the changes.  Info field format working as expected however procedure has got a typo in a query and freeform procedure updated as well. Updated and DEV DP submitted. Please approve and create task id for the same. 

Commit ID -  [73ec832a8416](http://coaamandadevops02.austintexas.gov/R5:73ec832a84160de73f2deaac3b069ede51a06d7b)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0277910**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to to DEV please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder -  I have tested in DEV and found that default procedure in admin not updated. Committing again with defaultaccountbillfee and created standalone procedure to avoid this in future. DEV DP for Commit  #3641 submitted; Could you please approve and create task id for me. 

Commit ID – [294e5e4267cf](http://coaamandadevops02.austintexas.gov/R5:294e5e4267cfaa9542363f1c71927abc6004d595)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0278852**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV, please UAT and let me know the outcome

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Tested in DEV, yet one change not working as expected need to submit another commit; however need clarification from Maria as I have a question, Upon clarification I can submit both changes together in the commit. you may notice too many commits for this card as I cant test in localhost, each change needs to go to DEV to get tested. Thank you!

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan what clarification is needed? Please work with @vschandramouli to see if he can help get this clarified. Thank you.

**Comment by vschandramouli** [comment]
Spoke with @Sreelatha-BlazeKannan  and requested Maria for a time to meet either today or on 1/30/23.

CC @Nadin-Nader @TracyLinder

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Had a meeting with Maria and Vish regarding the clarification; Here are the details - 
1. Online RW Street Event folder Creation trigger behaviour 
Initial Info values - NULL
Property & Street info - would have Begin/End date values

2. Backoffice folder creation behaviour, when do we add street & Property info?
Info - Can be edited/updated
Property & Street info - automatic add phase no rows

3. Any process attempt, do I need to add code to copy the fields in either of the cases?
In event review process - hard stop error to add info values (New Requirement)

4. Is there a chance that street & property info can be with more than one property records of begin and end dates if it has more than one property? If so, how to address that?

Yes, Maria will discuss and if any changes needed then she would confirm.

upon completing the changes in DEV, will have to showcase to Maria for TEST and PROD Move.

CC @vschandramouli

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  This has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0285921**

**Comment by Nadin-Nader** [comment]
@sree this has been deployed to DEV. Please UAT

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This new DEV commit has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0290450**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV and it is working as expected.  TEST DP submitted; Kindly approve and create task id for me.

Please find the Commit ID Order.

Commit ID 1 – f9ea65eebbf4 
Commit ID 2 – 0bc7d4db3ca1
Commit ID 3 – 73ec832a8416
Commit ID 4 – 294e5e4267cf
Commit ID 5 – 362851931be2
Commit ID 6 - 84f9c11ff5f4

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to TEST under **SCTASK0292275**

**Comment by TracyLinder** [comment]
### Convo w/ Maria OSE

- Maria wants to do serious UAT on this, but doesn't have time currently. This will be sitting in test for a while.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to TEST please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Completed testing in TEST and its ready for UAT. I also request that we can have a call with Maria to do complete round of testing. Thank you!

**Comment by Nadin-Nader** [comment]
Scheduled call for 3/21/23 1pm, waiting on Mari's confirmation

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As Per Maria's meeting today, this card is approved for PROD Move

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0296919**

**Comment by Nadin-Nader** [comment]
Per Maria this is fixed and working properly:

> 
> [1:23 PM] Nader, Nadin
> Hi looks like 3641 is now complte on PROD can you verify?
> 
> [1:24 PM] Alonso, Maria
> Yesr! We tested it this morning and with the Re-Default it all seems to be working properly. Thank you!!!
