### ISSUE TITLE
RW-Street Event Info Field Update: Number of Blocks (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3642]
### As an OSE Reviewer, I want the system to auto-calculate and insert the value in the folder info 'Number of Blocks' so I no longer have to manually count and update that field. 

**Stakeholder:** Maria A
**DTS Manager:** Nate

**Acceptance Criteria:**
- Updates apply only to RW-Street Event
- At folder creation, the system inserts the correct value in info 'Number of Blocks'
- When updates are saved to the folder info tab, the system will insert the correct value in info 'Number of Blocks', it will overwrite the existing value with the correct value. 
    - Example: If the user at any point were to delete the existing value and click Save, the system will input the correct value
- Correct Value: The system counts the number of rows on the folder property tab. This is the correct value.

**Comment by TracyLinder** [comment]
@Nadin-Nader I assigned this to you. I think the acceptance criteria might be complete. Will you please review and determine if this is backlog ready (ready for development)? Thanks!

**Comment by Nadin-Nader** [comment]
Have a meeting with Maria to verify the acceptance criteria for tomorrow 8/28/2020 at 1030am

**Comment by Nadin-Nader** [comment]
@TracyLinder Spoke to Maria and she said that the acceptance criteria is correct. The only worry she had (its not really a worry because they manually change it and it doesnt happen often) is that the applicant will be selecting multiple properties instead of segments and that may cause the count to be off.
She is not worried about it at this moment as this usually happens with new applicants and they mostly get recurring ones. Moving this to Backlog.

**Status:** Backlog Ready

**Comment by aishwarya2505** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan 

Demo for review sent on 9/16/2020.

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @Sreelatha-BlazeKannan @TracyLinder I have reviewed the demo and all of the acceptance criteria has been met. I approve to move this to DEV.

### **APPROVED FOR DEV! :)**🎉

**Comment by Sreelatha-BlazeKannan** [comment]
Thank you @Nadin-Nader  
@Nadin-Nader, @TracyLinder - Aishwarya will send the DEV Deployment soon.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 I have sent the deployment request to the Devops CM team to deploy this to DEV. It is SCTASK0098445

**Status:**
Waiting on Deployment to DEV by CM Team

**Comment by Nadin-Nader** [comment]
Checked the TASK to see if it was completed and it has not been. Still waiting on CM Team to deploy to DEV.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder This has been deployed to DEV and is ready for UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV UAT Pending

**Comment by aishwarya2505** [comment]
@Sreelatha-BlazeKannan @TracyLinder @Nadin-Nader , I can see part of my changes on DEV and other part seems to be missing. The Github tool reads. "squashed commit". I shall get in touch with Martin on this.

**Comment by aishwarya2505** [comment]
@Sreelatha-BlazeKannan @TracyLinder @Nadin-Nader , I have tested this one in DEV and it works as expected. Folder RSN 11884842

**Comment by aishwarya2505** [comment]
Hi @Nadin-Nader, are you able to see the Group drop down options in TEST? Was this missing in the demo?

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - Aishwarya will get in touch with Nadin to resolve this testing.

**Comment by TracyLinder** [comment]
**Status:** Per Nate, this is pending a deployment to DEV. @Nadin-Nader please update.

**Comment by Nadin-Nader** [comment]
**Status:**
With CTM Waiting on deployment to DEV SCTASK0098445

> From: Nader, Nadin 
> Sent: Thursday, October 1, 2020 12:27 PM
> To: Aishwarya Ramesh <Aishwarya.r@launchitcorp.com>
> Cc: Rajesh B. <Rajesh.b@launchitcorp.com>; Sreelatha.b@launchitcorp.com; Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: #3642 Request for DEV Deployment
> 
> Aish,
> 
> I have sent the deployment request to the Devops CM team to deploy this to DEV. It is **SCTASK0098445**

**Comment by TracyLinder** [comment]
Nate & I will test in DEV on 10/22

**Comment by TracyLinder** [comment]
### DEV UAT Results (Failed)

- ✔ Updates apply only to RW-Street Event
- ✔At folder creation, the system inserts the correct value in info 'Number of Blocks'
- ❌ When updates are saved to the folder info tab, the system will insert the correct value in info 'Number of Blocks', if that field value is Null.
    - Example: If the user at any point were to delete the existing value and click Save, the system will input the correct value
- ✔Correct Value: The system counts the number of rows on the folder property tab. This is the correct value.

When i deleted the info value & clicked save, the system threw an error:

![image](https://user-images.githubusercontent.com/49930868/96926097-c181b180-147a-11eb-843e-e1eaf3501f6d.png)

**Comment by aishwarya2505** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan Hello, the info "Number of Blocks" is a mandatory field. As you can see, the error message will appear if any of the pink info boxes are left blank while saving through the Info Tab. 

To check this, you can enter 0 and save, the system will have updated the correct value against "Number of Blocks"

Or, we could change this into a non mandatory info field. That way, the value would get updated without throwing the error message and the user can do away without having to enter a dummy value. 

Let me know if you'd like to have this non mandatory. It is a simple change and should take couple minutes to fix. :)

**Comment by TracyLinder** [comment]
@aishwarya2505 thanks for the info. I just tested and this looks good to promote. 

### Approved to promote to test. 🎉

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @Sreelatha-BlazeKannan @TracyLinder I have sent this to the CM DevOps team for deployment to TEST under **SCTASK0102615**

## **Status:**
Waiting on CM Team to deploy to TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder  This has been deployed to TEST

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder @Nadin-Nader - @aishwarya2505 will test the same  in TEST environment; then it will be ready for TEST UAT.

**Comment by TracyLinder** [comment]
**UAT Results (Passed):**
- Test RSN 12396293 looks great

### Approved to promote to PROD 🎉

**Comment by aishwarya2505** [comment]
PROD Deployment Plan submitted on 11/2/2020 @TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @Sreelatha-BlazeKannan I sent this to the CM DevOps team for deployment to PROD **SCTASK0103513**

## **Status:**
Waiting on CM DevOps to deploy to PROD

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @aishwarya2505 @TracyLinder This has been deployed by the CM Team to PROD. I will email Maria and let her know and close the card.

> Maria,
> 
> Hope you are doing well. I am reaching out regarding the RW-Street Event Info Field Update: Number of Blocks request. I wanted to let you know that this is has been changed and is on PROD. 
> I will close the card but if you have any question, please feel free to email us.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services
> Austin Transportation Department
> 
>
