### ISSUE TITLE
VZ Events: Integration testing

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#3646]
We need to 2x check that the new events are working as intended from VZE:

1. Test Non-CR3 updates:
- Test dissociation (note speed, original coordinates)
- Test association to any specific polygon
- Test association to the original location.
2. Test CR3 location update;
- Test dissociation (note response speed, coordinates)
- Test association to any specific polygon
- Test association to the original location
3. Test Jurisdiction:
- Test dissociation (note response speed, original coordinates)
- Test association to jurisdiction 5 (original coordinates)

**Comment by sergiogcx** [comment]
The first test (No 1) went well, in part A) the location was removed after about 5 seconds.

```
UPDATE
	atd_apd_blueform 
SET 
	longitude  = NULL,
	latitude   = NULL
WHERE 
	case_id  = 140010282;
```

In part B) the location was re-assigned after 10 seconds.

```
UPDATE
	atd_apd_blueform 
SET 
	longitude  = -97.731079,
	latitude   = 30.268667
WHERE 
	case_id  = 140010282;
```

**Comment by sergiogcx** [comment]
For CR3s:

1. Tested dissociation:

```
-- To nullify coordinates across the record, we need to do it all at once or the trigger will not allow the update.
UPDATE 
	atd_txdot_crashes
SET 
	latitude = NULL,
	longitude = NULL,  
	latitude_geocoded = NULL,
	longitude_geocoded = NULL,
	latitude_primary = NULL,
	longitude_primary = NULL
WHERE 
	crash_id = 16414673;
```

About 10 seconds later you can see the location_id was nullified too:
![2020-08-11_19-48-16.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/d5c56b3e-f541-4913-82b6-407337fa9242)

2. Tested a different set of coordinates/polygon

```
UPDATE 
	atd_txdot_crashes
SET 
	latitude_primary = 30.436369,
	longitude_primary = -97.689699
WHERE 
	crash_id = 16414673;
```
You can see the location_id and the shape have been modified:

![2020-08-11_19-37-17.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/eaa7ebb6-2bd4-495e-8230-94197345861f)


3. Associating again to original values:

You can see the dot being populated immediately:
![2020-08-11_19-51-02.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/2559ad84-3190-4826-9676-69a7f0f5c4da)

10 Seconds later, it she shape appears:
![2020-08-11_19-51-14.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/b02cb5f8-16a0-4333-9241-9eee59bb8c71)

**Comment by sergiogcx** [comment]
CR3 Jurisdiction:

Original Position, notice it shows as 'N' for full purpose.

![2020-08-11_20-01-13.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/e0584570-1687-440b-a138-1439522ac472)

1. Nullify the location, the position is now gone:
![2020-08-11_20-03-17.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/dfef0a97-c7c2-4c67-ac22-3e530fb4d977)

2. Put into the polygon by slightly modifying the coordinates. Notice the flag changed to 'Y'.

```
-- Updated all fields, to not mess with the trigger
UPDATE 
	atd_txdot_crashes
SET 
	latitude = 30.43593474,
	longitude = -97.68886247,
	latitude_geocoded = 30.43593474,
	longitude_geocoded = -97.68886247,
	latitude_primary = 30.43593474,
	longitude_primary = -97.68886247
WHERE 
	crash_id = 16414673;
```
![2020-08-11_20-16-01.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ca5ada17-e021-47da-a678-55740efc9992)

3. Switching back the original position:

```
UPDATE 
	atd_txdot_crashes
SET 
	latitude = 30.43593474,
	longitude = -97.68886247,
	latitude_geocoded = 30.43593474,
	longitude_geocoded = -97.68886247,
	latitude_primary = 30.43593474,
	longitude_primary = -97.68886247
WHERE 
	crash_id = 16414673;
```

We can see the dot moved back to its original point, the flag changed back to 'N':

![2020-08-11_20-28-13.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/5025ae82-4f68-485e-8fb2-836ea7d5a637)

**Comment by sergiogcx** [comment]
The integration tests were successful, closing this issue.

**Comment by mateoclarke** [comment]
Very cool, thanks for documenting. Look forward to hearing more about your process and what you learned overall.
