### ISSUE TITLE
Tech Debt / Form Framework Refactor in VZE

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3654]
@mddilley and I have discussed using the Temp Record Creation Form UI as a test for refactoring and adopting a React Form Framework.

We've discussed using:
- [Formik](https://formik.org/)
- [React-hook-form](https://react-hook-form.com/)

The output of this discovery would result in a more maintainable path forward for forms in VZE and also influence the direction of admin forms in the MOPED project

**Update** We explored these libraries during discovery in #2475 and went with React Hook Form for MOPED.

**Comment by amenity** [comment]
@mddilley - do you think this was covered by #2457?

**Comment by mddilley** [comment]
Just seeing this @amenity, yes this was addressed in the MOPED discovery day. I'll place it back in the backlog in case we decide it is worth refactoring this or other forms in VZE in a future tech debt sprint.
