### ISSUE TITLE
[Feature] Phases

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3655]
As a project manager, I want to advance a project forward into a new phase without losing track of the previous phase's details (start date, end date, length, deliverables, etc.) so that I can maintain both a current understanding of where the project is and the past history of a project.

**In-scope:**
- CRUDL operations for phases
- Keeping a timestamped history of all phase changes in order to maintain a linear timeline of the project's history.

**Out-of-scope:**
- (Eventual functionality that may be tied into project templates): See notes below, but the ability to automate phase changes based on specific milestones (e.g. deliverables). For example, once final design plans are submitted, the phase would change from Design to Construction.
- Ideally a phase change would be our best place to trigger some workflow/process automation for projects, but this will need to be spec'd out after Alpha/Beta.

**Data Model:**
_Brackets = relational data source
Parentheses = additional context/questions
Asterisks = required field for entry_

**Requirements**
- List of phases in a given project
- Add a phase to a given project, select from list of phases in the database

**Associated tables**
- moped_phases (controlled list of milestones)
- moped_proj_phases (list of phases per project)

**Wireframes:**
https://balsamiq.cloud/senhupm/p9y6tuy/r0869

**Terminology**

Term | Definition | Examples | Notes
-- | -- | -- | --
Status | Current indicator of project | Proposed, Planned, Scheduled, Active, Complete, On Hold, Archive | Option to add note when you change status
Phase | Discrete time-boxed portion of a project | Preliminary Design, Preliminary Engineering, Permitting, Construction | Fixed chronology (order/rank)
Milestone | Significant event or deliverable | 3/12/20 Advisory Council Meeting, Rosewood Community Feedback Session | Description, date, adjustable notifications/reminders

**Notes on future functionality; not in current scope**
Once a Phase ends, a consecutive Phase begins. The history of Phase changes and their associated dates are tracked for reference.

**Comment by zappfyllc** [comment]
@amenity I understand the renaming here but since this involves quite a few entities, I chose to list out bullet point requirements that should be able to lend themselves to user stories within this epic. Could you and @JaceDeloney possibly do this from my bullet point (happy to discuss too!)?

**Comment by zappfyllc** [comment]
Updated the description above to more accurately match the ask here. Requirements can be broken down into user stories and estimated to decide on whether phases/milestones should be broken out as their own epics.

**Comment by amenity** [comment]
@zappfyllc - might you be able to create issues for the rest of this epic? Something tells me this one is a little more complex than "do database" and "do React" ...

**Comment by amenity** [comment]
@sergiogcx is going to go through these sub-issues to size, identify dependencies, etc. so that they can be divided up in a way that makes sense.

**Comment by amenity** [comment]
@mateoclarke is going to look over this epic and make recommendations on how we should tackle it. cc/ @zappfyllc

**Comment by amenity** [comment]
Leslie is down to help with this, too.

**Comment by amenity** [comment]
@zappfyllc - do you have any examples (screenshots, if possible) of how workgroups are using & tracking phases and milestones currently? I think it would help us understand the business need here. cc/ @mateoclarke

**Comment by amenity** [comment]
Also, @zappfyllc, should we work w/ stakeholders to compile starter lists of Phase and Milestone terms, like we did during #4401?

**Comment by amenity** [comment]
@johnclary @zappfyllc @mateoclarke  - I moved the spreadsheet NW sent this morning [here](cs.google.com/spreadsheets/d/1S8STpKUaJ6xn4QFfR0gESiT1X5b4XD26GZnPByrU1RQ/edit#gid=462777356), in case it's helpful to have a working doc. (Started simplifying in the _Simplfied_ tab. ;)

**Comment by amenity** [comment]
@mateoclarke @zappfyllc - feedback from Paloma (ROW after watching the recording from the phases and milestones work session: 

> Just finished the video!  The three categories – status, phase, milestone – seem really intuitive to me.  I’m not certain if I properly grasped what Nathan was referring to as “phase simple”. 
> 
> Seconding Dylan as well – I see merit in making all of this data publicly viewable, right down to the milestone.  It’s also worth noting that Tracy is heading up a project to extract and publish as much AMANDA permitting data as possible/allowable under the law. 😊  Perhaps there’s some connection with this effort.
> 
> If/when it’s time to begin compiling the titles for each category, I’d be happy to pitch in.  I’m guessing there will be a link sent out so I’ll keep my eyes peeled.

**Comment by amenity** [comment]
@zappfyllc will you update this issue and epic to represent Phases, then create another issue for Milestones.

**Comment by zappfyllc** [comment]
#5210 covers Enhancements to Project Phases, closing this
