### ISSUE TITLE
[Feature] Work Orders

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3659]
As a project team member, I want to easily view work orders associated with a project so that I can avoid changing systems to view granular details related to a project.

**In-scope:**
- Lightweight linking to other applications that manage work orders based on a given user's workgroup (e.g. I'm a project manager in AMD, so therefore the link that appears in Moped will send me to a Data Tracker link that's unique to the project)

**Out-of-scope:**
- Creating and managing work orders inside of Moped itself

**Additional notes:**
Basic workflow would send users to work orders that are stored in AMD Data Tracker or Signs and Markings. Other workgroups need to be considered; these would also be specified by the user entering the work order (or automatically based on their role/permission/workgroup).

Note: IPD calls ATSD's work orders (along with SMB, anyone else who has been onboarded in Moped)

**Comment by zappfyllc** [comment]
Applying the "Should Have" label here only because of AMD (our initial group to onboard) and their collective concern for using two different applications (their original hope was that we could just build out Data Tracker.

**Comment by amenity** [comment]
This will not be handled as a Moped feature. 

In Moped 1.0, we have a link to list of work orders in Data Tracker:
![Moped1 0-Project-Summary copy](https://user-images.githubusercontent.com/1463708/154632329-d7857b60-9b46-4589-9ac0-359cacea64a7.png)
![Screen Shot 2022-02-18 at 12 49 11 AM](https://user-images.githubusercontent.com/1463708/154632404-9b4a2f15-b7aa-4cf5-874f-533e3f0676d0.png)

See also #8501.
