### ISSUE TITLE
Bug: User LewallenI Unable to edit R.O.W. Review comment document 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3664]
### Per Isaiah, AMANDA will not allow him to edit the R.O.W. Review folder document. This is preventing him from completing reviews on various folder types. 

**"It seems there’s a security setting preventing me from opening a R.O.W. Review comment document for editing.  I’ve tried following the instructions provided but I’m not able to modify Trusted Sites in IE Internet Options Security tab.  Functionally, this prevents me from recording a review result other than Approved.  This condition is true for all folder types.  Should this go to the AMANDA team or is this a local issue Scott should address?"**

**Screenshots Provided by User:**
![image](https://user-images.githubusercontent.com/49930868/90069626-2caf4a80-dcb8-11ea-98bc-aff8f2d17cc3.png)

![image](https://user-images.githubusercontent.com/49930868/90069633-2faa3b00-dcb8-11ea-831c-c8463ab4dd3f.png)

![image](https://user-images.githubusercontent.com/49930868/90069645-33d65880-dcb8-11ea-93eb-c33d5d6be049.png)

**Comment by TracyLinder** [comment]
**Email to Customer & Nate:**

Hi Isaiah, thanks for letting me know. This does seem like a potential show-stopper. 

Nate, can you please check out the screenshots Isaiah sent and let us know the best next step for resolving it? I’m not sure if we can fix this in-house or if it should be escalated to CTM. I’ll create a DTS issue and assign us both. 

Thanks,

Tracy Linder (she/her)
Product Manager, Data & Technology Services
Austin Transportation Department

**Comment by TracyLinder** [comment]
Email to Customer:

Hi Isaiah, 

Just following up on this ticket. Has this issue been resolved for you?

Thanks,

Tracy Linder (she/her)
Product Manager, Data & Technology Services
Austin Transportation Department

**Comment by Nadin-Nader** [comment]
@TracyLinder Im making the call on this one and closing it. Isaiah still has not responded to any emails about this and has not complained or we have not heard anything about it. I will send an email letting him know

**Comment by Nadin-Nader** [comment]
Email sent to Isaiah:

Isaiah,

Hope you are doing well. I was reaching out to you to inform you that I will be closing out this request as we have not heard back from you.

If the issue still exists, please let us know.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services 
Austin Transportation Department

**Comment by Nadin-Nader** [comment]
Email conversation with Isaiah before closing:

From: Nader, Nadin 
Sent: Monday, August 17, 2020 2:27 PM
To: Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov>
Cc: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>; Linder, Tracy <Tracy.Linder@austintexas.gov>
Subject: RE: Isaiah can't open AMANDA comment document for editing 

Isaiah,

Hope you are doing well. Sorry for the late response. The person to people to help with that is your IT department. The team or person that gave you your workstation should be able to give you Admin access or set it up for you. Please let me know and we can find out the right people to get this done.

From: Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov> 
Sent: Friday, August 14, 2020 3:03 PM
To: Nader, Nadin <Nadin.Nader@austintexas.gov>
Cc: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>; Linder, Tracy <Tracy.Linder@austintexas.gov>
Subject: RE: Isaiah can't open AMANDA comment document for editing 

Dear Nate

Understood.  I cannot add AMANDA to Trusted Sites.  Who can help me resolve that?  Being able to successfully generate the comment document, edit it and send it to the folder is a mission-critical function of the Utility Coordinator role.  Thanks for any assistance or resources you can provide.

Sincerely

Isaiah Lewallen
Engineering Associate C
Utility Coordinator
Austin Transportation Department
Right-of-way Management Division

isaiah.lewallen@austintexas.gov
512-974-1479
6310 Wilhelmina Delco Dr 
Austin, Texas 78752

CASE SUBMITTAL:  AULCC case submittals received at https://abc.austintexas.gov/web/permit/index.  If file size greater than 20MB you may send e-mail attachment or fileshare URL.
 

From: Nader, Nadin 
Sent: Friday, August 14, 2020 8:17 AM
To: Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov>; Linder, Tracy <Tracy.Linder@austintexas.gov>
Cc: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>
Subject: RE: Isaiah can't open AMANDA comment document for editing 

Isaiah,

Hope you are doing well this morning. Sorry you are experiencing this issue. Unfortunately, modifying Trusted Sites in IE Internet Options Security tab is something that needs that security setting in order for AMANDA to work properly. Luckily in AMANDA 7 this wont be an issue. This can be done in house but by the IT team. 
Once the Trusted Sites in IE Internet Options Security tab is modified you shouldn’t have the issue anymore. If you do, then it could be something we or CTM needs to look at.

From: Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov> 
Sent: Thursday, August 13, 2020 6:57 PM
To: Linder, Tracy <Tracy.Linder@austintexas.gov>
Cc: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>; Nader, Nadin <Nadin.Nader@austintexas.gov>
Subject: RE: Isaiah can't open AMANDA comment document for editing 

Thank you Tracy and Nate.

Isaiah Lewallen
Engineering Associate C
Utility Coordinator
Austin Transportation Department
Right-of-way Management Division

isaiah.lewallen@austintexas.gov
512-974-1479
6310 Wilhelmina Delco Dr 
Austin, Texas 78752

CASE SUBMITTAL:  AULCC case submittals received at https://abc.austintexas.gov/web/permit/index.  If file size greater than 20MB you may send e-mail attachment or fileshare URL.
 

From: Linder, Tracy 
Sent: Wednesday, August 12, 2020 4:18 PM
To: Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov>; Nader, Nadin <Nadin.Nader@austintexas.gov>
Cc: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>
Subject: RE: Isaiah can't open AMANDA comment document for editing 
Importance: High

Hi Isaiah, thanks for letting me know. This does seem like a potential show-stopper. 

Nate, can you please check out the screenshots Isaiah sent and let us know the best next step for resolving it? I’m not sure if we can fix this in-house or if it should be escalated to CTM. I’ll create a DTS issue and assign us both. 

Thanks,

Tracy Linder (she/her)
Product Manager, Data & Technology Services
Austin Transportation Department
