### ISSUE TITLE
MOPED | Dev Meeting/Kickoff

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3666]
Continues https://github.com/cityofaustin/atd-data-tech/issues/3611

Goals: 
- Get everyone on the same page about Moped implementation work and timeline. 
- Unblock implementation of dev infrastructure including repos and CI. 
- Outline tasks, issues, and spikes that can start being assigned to JD now and dev team in Sprint 32.

Agenda:
- [x] VZE front end reflections
- [ ] Decide on a UI framework. 
     - Bootstrap & Material UI
- [x] Identify and prioritize the components we're going to build/extend from existing frameworks.
- [x] Identify what we need to do to get Zappfy started on writing code while dev team wraps up VZx.
    - Storybook

**Comment by mateoclarke** [comment]
**VZE front end reflections**

- no problems with routing, except with some Auth0 login
  - lazy loading included in CoreUI template
  - adding new pages was easy
- Netlify worked well, except for Auth0 preview app deployments
- no issues with Bootstrap + CoreUI, good documentation
- new Non CR3 upload tool component/editable spreadsheet, using React library was easy
- expanding on the functionality of Tables was tricky and we had to do some custom work
- forms, we did a lot custom, could use a standard library
  - this will be big for moped
- user creation process seems to be working well in VZE

**Decide on a UI framework**

- What do we want the framework to look like?
- spike to spin up UI frameworks, experiment with alternatives
- Ex components: timeline management, calendar status 
- [ ] Mateo to schedule Wednesday moped kickoff discovery. 
    - Goal: figure out if starting with bootstrap would exclude use of Material UI or other UI frameworks or themes. 
    - experiment with form libraries and compatibility with Material UI or Bootstrap
    - add directories to [moped repo](https://github.com/cityofaustin/atd-mobility-project-database)
    - setup storybook on new admin component repo
 

 **Identify and prioritize the components we're going to build/extend from existing frameworks**

- [ ] Amenity to list out some components and user stories between now and next Wednesday, starting with AMD needs

**Identify what we need to do to get Zappfy started on writing code while dev team wraps up VZx.**

- Heroku Hasura hosting, scaling? Wait til speak with JD about the best point in the project timeline to migrate to AWS
- monorepo setup, admin component repo setup with storybook
- Authentication with Auth0 vs AWS Cognito
- AWS Amplify
- get Sergio's spike input about hosting moped repo on Netlify or AWS
- Netlify hosting for admin UI/storybook repo

**Comment by amenity** [comment]
[Recording here](https://web.microsoftstream.com/video/99863f6f-2162-4014-bdb8-7a36ea9d8b07). 📺

**Comment by amenity** [comment]
- Refactored #2475 for "Decide on a UI" framework fun
- #3343 covers my prep work
- @johnclary - wanna factor [this]( https://github.com/cityofaustin/atd-data-tech/issues/3507) in somewhere?
