### ISSUE TITLE
[Feature] ArcGIS Online Viewer

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3672]
As a project manager, I want a map of related projects that my team and stakeholders can reference to communicate and organize work. See #9421. 

As a project manager, I want to view overlapping projects geographically so that I can quickly and easily identify projects in the same vicinity that may present challenges for projects I'm responsible for and will be helpful to address sooner than later. I need the map data to be available in ArcGIS Online so that I can easily access Moped spatial data for reporting and analysis.

As a portfolio strategist, I want to view overlapping projects geographically so that I can quickly and easily identify projects in the same vicinity that may have opportunities for coordination.

**In-scope:**
Three ArcGIS Online feature layers:
1. Projects - each map feature represents one project and contains core project attributes
2. Component lines - each map feature represents one line-type project component and contains core component attributes
3. Component points - each map feature represents one point-type project component and contains core component attributes 

An ArcGIS Online web map which emulates the functionality of the interim database viewer. The map should allow users to search and filter projects and easily navigate from a map feature to the projects's summary page in Moped.

**Out-of-scope:**
- Cluttered information related to a project appearing against the map view (likely direct them to views already created by the Project Overview/Project Details features)

**References**
[Interim Mobility Projects Database Viewer](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=d6194f783b114453a70eb769853e390c) - fed from Interim Mobility Project (Access) Database

**Comment by johnclary** [comment]
@amenity can you provide a link to the interim project database viewer?

**Comment by amenity** [comment]
@johnclary - what are next steps here? Thoughts:
- If we want to continue to maintain points and lines, we won't be able to have the kind of advanced filtering available in the IMPDV. Or the experience won't be as seamless, bc the user will have to apply to each feature class separately
- We may not need a real-time map, but something updated nightly or on-demand is reasonable. 
- This may not be a 1.0 feature...

    `

**Comment by amenity** [comment]
@johnclary - moving this into the backlog until we resume active work on it for Moped 2.0. If you have ideas about next steps, it would be great to document those here.

**Comment by andrewshensky** [comment]
Below is a link to the current MOPED Viewer in AGOL which contains data from moped being pushed daily to AGOL. This application has been built in coordination with ATSD and will likely continue to evolve over time, but it does serve as an MVP for this initial request.

https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=404d31d56b57491abe53ccfd718fcaee
