### ISSUE TITLE
[Feature] Project Listing

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3675]
As a user, I want to identify projects of importance to me from a set of all projects in the mobility project database so that I can compare or analyze projects across that set.

**In-scope:**
- Table/list view of all projects in the Mobility Project Database

**Out-of-scope:**

**Additional notes:**

**Comment by amenity** [comment]
It seems like this feature will present a good candidate for our first Kickstand component, see #4016. 

cc/ @zappfyllc

**Comment by zappfyllc** [comment]
Some related features/sub-features that could condense the UI quite a bit but also complicate this issue. I am curious to know what in this list below is included in the table component built in VZE.

- Filtering columns
- Sortable columns
- Keyword search of table data
- Data export of table data
- Table links to child pages

**Comment by amenity** [comment]
- What columns should be shown
- What columns should be included in keyword search
