### ISSUE TITLE
[Feature] Project Financials

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3676]
As a portfolio strategist or project team manager, I want to view the anticipated budget and expenses for a project that hasn't been capitally funded (operational needs, anticipated needs) so that I can strategize to find overlapping funds or projects.

**In-scope:**
- Available budget, current budget, budget YTD, fiscal years, current expenses, expenses YTD, etc.

**Out-of-scope:**
- eCapris Integration feature covers the eCapris subproject ID, so this would involve expanded functionality.

**Additional notes:**
This may be tied into #3663 (Implementation Cost Estimates feature)

#2320 has helpful information about where to source FDUs as a picklist (controller's office) vs. where to source FDUs in the context of a subproject ID (eCapris)

**Comment by amenity** [comment]
Note: As we ramp up on eCapris, wondering about [tracking financials for _all_ projects there](https://github.com/cityofaustin/atd-data-tech/issues/4820#issuecomment-754418989).

**Comment by johnclary** [comment]
During today's sprint review Nathan W brought up the need to tie Moped projects to an eCapris sub-project ID, _and/or an FDU_. Renee seconded. 

This makes sense and is consistent with our tie-ins to FDUs in the Data Tracker.  I have started drafting a long read about how these elements all tie together, but will hold off on posting for now. I asked Nathan and Renee to provide example FDUs. Once they provide those I'd like to dig deeper into the links between such FDUs and project budgets.

**Comment by johnclary** [comment]
Closing this and leaving https://github.com/cityofaustin/atd-data-tech/issues/8096 in the icebox
