### ISSUE TITLE
[Feature] Advanced Global Search

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3677]
This is a global search leveraging Algolia or Elasticsearch that goes beyond the Postgres search used for #4746

**Comment by amenity** [comment]
@mateoclarke @johnclary - do y'all think this feature is a must-have for Moped 1.0?

**Comment by johnclary** [comment]
No. Barring feedback from users I think the project search/filters will be sufficient for 1.0.
