### ISSUE TITLE
[Feature] Single Sign-On

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3682]
As a Moped user I want to log in to Moped with my City of Austin network credentials so that I don't have to manage additional passwords or worry about security. 

**In-scope:**
 - Microsoft AD

**Out-of-scope:**

**Additional notes:**

**Comment by sergiogcx** [comment]
I am currently working on this, I have been given a url with the certificate metadata. Currently configuring AWS workflow (logging in, redirect if success, redirect on failure, etc)

**Comment by sergiogcx** [comment]
I am going to experiment mapping the user's department and job title into the claims, but I cannot guarantee it will be there yet. I am going to first try to make it work, if it works then we can attempt to pull the department and job title info into the profiles:

![2020-10-06_13-54-59.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/66288b0f-2365-4181-8d78-bfc5c7a30a8e)

**Comment by sergiogcx** [comment]
I have created a few issues, the scope of this work extended as did the number of things needed for this to work. As expected, there are things we need to do in the front end to make the SSO work. The backend requires a few more things and will require a couple more days to complete it.

**Comment by sergiogcx** [comment]
This should be closed

**Comment by sergiogcx** [comment]
Having all these issues completed, I am going to close this epic.
