### ISSUE TITLE
[Feature] User Management 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3684]
As a DTS team member, I want to be able to add and update user accounts to Moped so that staff has access to the application. 

**In-scope for Moped 1.0:**
- List of users
- Ability to edit user roles — Viewer, Editor
- Form to add users
- Ability to edit user status — Active, Archive

- Basic filters (Viewer/Editor; Active, Archive)
- Sortable columns
- Search

**Out-of-scope for Alpha:**
- Usage outside DTS Team
- Bulk add/update

**Data model** 
[Hasura `moped_coa_staff`](https://coa-moped.herokuapp.com/console/data/schema/public/tables/moped_coa_staff/browse)

**Comment by amenity** [comment]
@zappfyllc — should #3776 be under this epic?

**Comment by zappfyllc** [comment]
@amenity Yes, and I would have it block SSO as a feature, which maybe could be rolled up as an issue in this Epic as well, but I'd keep them separate for now until @sergiogcx and/or @mddilley can weigh in on the amount of work entailed to implement SSO. If SSO implementation is not Epic-worthy (many sprint's worth of work), then I would move it underneath this larger feature.

**Comment by amenity** [comment]
Oops — I meant to come back and correct this. I realized that configuring authentication (#3776) — obviously belongs under SSO (#3682). And they should then block this, yes?

**Comment by zappfyllc** [comment]
Sure, they're all arguably a part of the same overlying capability so how we want to slice them up is fine with me. SSO doesn't have to be the implementation choice for user authentication, but I'm assuming it will be and provides the most value from an end-user perspective (hence why it was called out as its own feature).

**Comment by amenity** [comment]
Two options: 
- Anyone with a COACD account can create an account
- Send an invite, which will create an account, which we can't force to log in through COACD

**Comment by amenity** [comment]
Requirements for this should be written without assuming that COACD will be used for log in with Cognito.

**Comment by amenity** [comment]
- List of users
- Form to create a user
- Archive user
- Set role

**Comment by amenity** [comment]
Per @zappfyllc in Slack. 
> Add a moped-admin role to our list of roles and build a simple UI that allows that role to create/list/<insert action verb> users. Then we can always delegate account creation to users with those privileges without opening it up to everyone.

**Comment by amenity** [comment]
I think... We also want a separate "User Listing" feature that will allow users to see how many projects a user has... w/ the number of projects being a hyperlink to a list of projects. 

Or that is functionality that could be added to this page and then hidden, along with edit/add functionality.

**Comment by mddilley** [comment]
@amenity - During today's dev sync, @mateoclarke brought up a good point that a user being able to strengthen their own password is an important step for when we open the gates to users outside of the dev team. I agree, and I wanted to make sure to capture that here. Once the UI work is started, it will be straightforward to extend the API to handle this action.

**Comment by amenity** [comment]
Thanks, @mddilley @mateoclarke — I agree. I'm not opinionated about what the workflow looks like and I suspect there might be an existing component or pattern you can follow. If you'd like more guidance or want to discuss, lmk!
