### ISSUE TITLE
Update cityid classification for certain jurisdictions 

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3689]
Xavier requested the we make the following updates to allow for additional jurisdictions to be included with city_id 22. This would allow him to do additional analysis in coordination with other, adjacent municipalities (e.g., coordinating crashes with the City of Buda).
- [ ] Update crashes that fall within jurisdictions (5,3,7,8,10) to be classified as `city_id` = 22

**Comment by sergiogcx** [comment]
Currently, the crashes table trigger copies the value of city_id into original_city_id on INSERT only. This is needed as the first step.

```
-- COPIES THE CITY_ID INTO ORIGINAL_CITY_ID FOR BACKUP
    IF (TG_OP = 'INSERT') THEN
            NEW.original_city_id = NEW.city_id;
    END IF;
```

**Comment by sergiogcx** [comment]
I think the proper place for this code to live is in the SQS triggers.

Once a record is inserted or updated:
- If there are valid coordinates, the SQS trigger should adjust the city_id if it falls in any of those jurisdictions
- If it falls outside it keeps the original value.
- If there are no valid coordinates, it keeps the original value.

**Comment by sergiogcx** [comment]
While there is an SQS PR ready to be reviewed, I forgot to update the existing records in the database. Will do so now via SQL

**Comment by sergiogcx** [comment]
The following script yields the below results:

```
SELECT
    atcl.city_id,
    atcl.city_desc,
    COUNT(1) AS total

    FROM atd_txdot_crashes AS atc
        INNER JOIN atd_jurisdictions aj
        ON ( 1=1
            AND aj.id IN (5,3,7,8,10)
            AND (aj.geometry && atc.position)
            AND ST_Contains(aj.geometry, atc.position)
        )
        LEFT OUTER JOIN atd_txdot__city_lkp AS atcl ON atcl.city_id = atc.city_id
WHERE
    1=1
    AND atc.city_id != 22
GROUP BY
    atcl.city_id,
    atcl.city_desc
```

Result:

![2020-09-03_12-42-29.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/0f560b86-cbf5-4275-bb0b-b71554931d6e)

**Comment by sergiogcx** [comment]
I noticed a lot of crashes belonging to the not listed section, so I wanted to make sure that those were originally not listed or if that was somebody's work. So I ran a query to count how many of these have been modified to have a different city_id and still fall on the jurisdictions above, this is the result:

![image.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/d6d24de5-3101-4592-9754-410f4fd6b690)

**Comment by sergiogcx** [comment]
Having Xaviers approval to modify those records, I applied the following SQL script:

```
UPDATE atd_txdot_crashes
SET city_id = 22 WHERE crash_id IN (
    SELECT
        crash_id
        FROM atd_txdot_crashes AS atc
            INNER JOIN atd_jurisdictions aj
            ON ( 1=1
                AND aj.id IN (5,3,7,8,10)
                AND (aj.geometry && atc.position)
                AND ST_Contains(aj.geometry, atc.position)
            )
    WHERE
        1=1
        AND atc.city_id != 22
);
```

Output:

```
11456 rows affected in 47 s 892 ms
```
