### ISSUE TITLE
[Bug] Delete Multiple Fields: Edit Request Details Page & TIA Review Details

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3694]
### Remove 3 fields from two pages on the TIA Portal
- Trips per day, land use, intensity of site
- Pages: Edit Request Details (public portal), and tia-reviews/view-tia-review-details

![image](https://user-images.githubusercontent.com/49930868/90213022-68323d80-ddba-11ea-82d0-f0de106fd59b.png)

**Comment by ChrispinP** [comment]
@SurbhiBakshi @johnclary is this an existing issue by chance to remove these fields or are they still intended to be used and function appropriately? 

A) I need to make sure these fields function and look correct on the add and edit review forms as well as the detail pages OR
B) need to remove/hide these fields from the forms and detail pages as well as any tables

**Comment by SurbhiBakshi** [comment]
@ChrispinP - going to look at this today, dont think this has come to my notice before in the TIA app

**Comment by SurbhiBakshi** [comment]
@ChrispinP - I can't find another issue that addresses this task. @TracyLinder - did you have a conversation about this with Diana, I am guessing she put in the 'DELETE' comments. I found the edit form, if that is what you need @ChrispinP

**Comment by johnclary** [comment]
@ChrispinP unless Tracy says otherwise I think you can go ahead and delete these. Before you delete them, you'll want to check the display rules on any forms that use these fields and remove those first.

**Comment by ChrispinP** [comment]
Removed these 3 inactive fields from all pages they were on. Then removed 3 fields.

complete
