### ISSUE TITLE
[Bug] Project Location Not Populating - TIA Public Portal

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3696]
### There is a project location in the case details, but it isn't loading on the review status > view details page

![image](https://user-images.githubusercontent.com/49930868/90214193-5ef6a000-ddbd-11ea-81f9-5db4b6abccfd.png)

**Comment by ChrispinP** [comment]
Cannot replicate this bug. Project Location logic was verified and is in place to make sure this field is completed upon form completion. Some existing test completions may have not filled this field in initially. Project Address is set to required for TIA Reviews.

Should 'Address' for Development Reviews also be set to required?

**Comment by TracyLinder** [comment]
Both of us are unable to replicate bug. Closing this.
