### ISSUE TITLE
[Bug] Fee Status Field Error

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3697]
### Update Fee Paid Field to accept 'No' as a valid value.
- When updating the 'Review Fee Sent' field to 'Yes', and the Fee Paid field to 'No', the system throws the error "Fee Paid is Required"

![image](https://user-images.githubusercontent.com/49930868/90214598-a3cf0680-ddbe-11ea-9f74-9868d4696ff7.png)

**Comment by ChrispinP** [comment]
Both fields were requiring a 'yes' value to submit the form. Removed this option since both answers can be 'No' or one can be 'Yes' with the other as 'No'.

complete

**Comment by TracyLinder** [comment]
I tested this on record ID 15, and it worked as requested. Closing ticket.
