### ISSUE TITLE
Check and update MDS versions for all providers

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3704]
When we upgraded to supporting 0.4.0 none of our providers used that version at the time. So we had to have some level of "backwards compatibility" for providers (like Spin) that still used older MDS versions. Over the past 6 months, a lot of providers have updated their MDS version. 

Here is the current list:
```
"bird":   "version": "0.3.0"
"jump":   "version": "0.3.0"
"lime":   "version": "0.4.0"
"lyft":   "version": "0.4.0"
"spin":   "version": "0.2.0"
"ojo":    "version": "0.3.0"
"wheels": "version": "0.3.0"
"veoride":"version": "0.2.0"
```

- [x] check on all providers to see if we are using their latest MDS version
- [x] if we are not, update the ETL to use the latest MDS version

**Comment by sergiogcx** [comment]
Whenever I query spin in MDS v0.4, it errors out asking me for the start time; however, as far as I understand in the MDS specification it says it isn't required, and therefore it was not implemented in our MDS 0.4 driver:

https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/provider#trips-query-parameters

**Comment by sergiogcx** [comment]
For Spin, I will try to play along and provide a start date, and see if they can provide results.

**Comment by sergiogcx** [comment]
As a note to self, this is a related previous issue: https://github.com/cityofaustin/atd-data-tech/issues/1088

**Comment by sergiogcx** [comment]
Ok, so it looks like I have been able to connect to the MDS v0.4 of Spin:

![2020-08-26_15-51-32.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/99645e71-5ec9-4a81-b3c4-4eebbc747576)

**Comment by sergiogcx** [comment]
I got spin to work with MDS v0.4, already upgraded in production:

![2020-08-26_18-03-53.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/20bd3da7-09d5-44ee-9de3-698ab0c731c6)

**Comment by amenity** [comment]
@JaceDeloney @sergiogcx — assuming this is still in progress, bumping to Sprint 33.

**Comment by JaceDeloney** [comment]
This was completed
