### ISSUE TITLE
Refine in-app and email confirmation for Officers on sign up 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3714]
Two elements to this: 

**Confirmation email**
Currently the confirmation email that goes to officers is sent in the evening. Surbhi implemented this as a workaround for a broken trigger, but ideally the confirmation email would go out immediately. @mddilley, can you walk through the back end of the sign up workflow you implemented and see if we can set up an immediate email? 

**In-app confirmation**
It would be good to have a confirmation for the officers when they sign up for a shift.
- If we can send the confirmation email immediately, the small standard Knack pop-up in the upper right will be fine. 
- If the email won't send immediately, we should advise them about this in the confirmation. In this case, there will be more text and it probably makes sense to do a bigger modal like the one that comes up when an officer cancels.

**Comment by amenity** [comment]
@mddilley - we can bump this to Sprint 32 if that's better for you. :)

**Comment by amenity** [comment]
@mddilley - labeling this Sprint 32 because it would be wonderful to have going for our pilot with officers, but it can wait if that won't work for you. Also, will you add an estimate, please?

**Comment by mddilley** [comment]
@amenity - I'm reading Knack docs today to see what our options are for this feature. Happy to work on it this week so y'all will know before the pilot.

**Comment by amenity** [comment]
Thanks, @mddilley !

**Comment by mddilley** [comment]
I was able to trigger emails upon officer sign up using [Action Links](https://support.knack.com/hc/en-us/articles/225776907-Send-Emails#send%20emails%20using%20action%20links) and a PUT request to the API table view from the front end JS. Talked with Amenity and Surbhi about implementing, and we agreed that one email per `officer_assignment` is okay to get this feature built.

**Comment by mddilley** [comment]
Closing since this was deployed to production on August 28th.
