### ISSUE TITLE
Add person to crash_id 1005

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3715]
When the information for crash_id 1005 was first entered, the VZ team only knew of 1 person that was fatally injured. They didn't realize that there was an injury to another person in the crash. After looking at the CR3, the VZ team realized that another person had been seriously injured. We need to update crash_id to include this additional person.

- [x] Add an additional person to crash_id 1005 with a suspected serious injury
- [ ] Alternative, delete the crash record for crash_id 1005 and allow Xavier to create a new temp record.

**Comment by mateoclarke** [comment]
Added in production.

![Screen Shot 2020-08-17 at 5 27 45 PM](https://user-images.githubusercontent.com/5697474/90450303-fbb38900-e0ae-11ea-8232-54b791c7f73f.jpg)
