### ISSUE TITLE
BI Discovery Slack Message 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#372]
**Ask the slack community who is doing BI right.**

**Comment by amenity** [comment]
@timwis shared this [excellent report](https://docs.google.com/document/d/1IPzkUVEH071iTLVA5_vKd5Nf3pibDOHlZcs8BbAXh8I/edit?usp=sharing) he put together consulting at the UK environment department. The "engagements" section captures the patterns he observed from data releases in Philadelphia.

**Comment by amenity** [comment]
Closing this fellow, but I'll add anything else that comes our way via Civic Union.
