### ISSUE TITLE
Update email notification when an assignment they have taken is updated

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3720]
- Updates to VZA shift location
- Convert to a signal shift

Should come from `no-reply`

**Comment by amenity** [comment]
@SurbhiBakshi — is this correct to assign to you?

**Comment by amenity** [comment]
@SurbhiBakshi - what do you think about 

> The shift you signed up for on [date] at [time] has been updated. 
> 
> The location is now [new location]. 
> 
> If you are no longer able to work this shift, please log into the VZA App to cancel: https://atd.knack.com/vza

**Comment by SurbhiBakshi** [comment]
This should work - I'll update the email content.

**Comment by amenity** [comment]
Thanks, @SurbhiBakshi !

**Comment by amenity** [comment]
Thanks!
