### ISSUE TITLE
Strava Data Download

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#3721]
Downloading Strava Data for 2020 Q2

**Comment by alan-deanda** [comment]
Strava's website continues to show an error message when signing in to retrieve the data. They have recently changed their data delivery system. The data will be downloaded when the website works.

**Comment by johnclary** [comment]
@alan-deanda reach out to Strava and/or TxDOT for support.

**Comment by alan-deanda** [comment]
Strava's custom filter date is currently broken, but we can download monthly data.

Download queue:
- [ ] April
- [ ] May
- [ ] June

**Comment by alan-deanda** [comment]
All data has been queued for download. Once Strava has packaged the data it'll be saved to G Drive as per documentation.
