### ISSUE TITLE
Setup Speed Limit Sign Collector <> Knack integration

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3726]

**Comment by amenity** [comment]
@johnclary - any updates here?

**Comment by alan-deanda** [comment]
@andrewshensky do you know if we're still trying to do this?

**Comment by andrewshensky** [comment]
@alan-deanda I'm not sure on the origins of this issue, but I think our current work to integrate the new sign work order process with the current knack process would make this issue redundant. I will go ahead and close this.
