### ISSUE TITLE
Review w/ Unisys - UC Self-Assign: Move Create Child Feature

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3738]
### Can the create child feature on the SP folder for UC be moved from 'Utility Coordination Review?' to 'ROW Review?'

- It appears that 'Utility Coordination Review' infos were created just for the create UC child feature, when an info already existed for this group's review on the SP folder. Can we move the feature to the existing info and get rid of 'Utility Coordination Review?'?

**Comment by TracyLinder** [comment]
@TracyLinder per David G., this can be done. Iron out the details w/ UC team.

**Comment by DavidGallantUnisys** [comment]
@TracyLinder which info fields should we use?

**Comment by TracyLinder** [comment]
@DavidGallantUnisys This is the one to use

![image](https://user-images.githubusercontent.com/49930868/94604239-fd9b6b00-025c-11eb-9f06-d61ceb2a4e5c.png)

**Comment by TracyLinder** [comment]
Tested this today; UAT successful.
