### ISSUE TITLE
UC & LM Self Assign: Button Updates

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3747]
### Update to 3 buttons on the Self-Assign Workflows

1. On the submission confirmation page: remove the Cancel Assignment Button (Both LM & UC)
2. On the Acknowledgments Page: When clicking 'Cancel - I do not meet these criteria', update the folder status to 'Pending Customer Action' (LM only)
3. On the Application Attachments Page: When clicking 'Cancel this Application', update the folder status to 'Pending Customer Action' (Both M & UC)
    - Note: When updating the folder status manually to 'Pending Customer Action', the LM folder allowed me to begin the assign process again, however the UC folder would not, throwing the error 'Contractor Already Assigned' 

![image](https://user-images.githubusercontent.com/49930868/90689322-81614100-e235-11ea-8d5e-9b1a3dd7a773.png)

![image](https://user-images.githubusercontent.com/49930868/90689332-8625f500-e235-11ea-8e6a-afb6999aca83.png)

![image](https://user-images.githubusercontent.com/49930868/90689342-8b833f80-e235-11ea-98dd-9d94dd9c0562.png)

**Comment by TracyLinder** [comment]
Per David, these are ready for testing.

**Comment by johnclary** [comment]
@TracyLinder pls schedule UAT for self-assign

**Comment by TracyLinder** [comment]
This has been tested & UAT passed.
