### ISSUE TITLE
Updates to OPM Strategic Measure_Vision Zero dataset and metric calculation - M.D.1

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3752]
Vision Zero team has to report certain metrics to the Office of Performance Management. Of focus is the yearly number of KSI persons per 100k. https://data.austintexas.gov/stories/s/Number-of-persons-and-number-of-persons-per-100-00/xgcc-d979

Currently, this metric is powered by a [static dataset](https://data.austintexas.gov/Public-Safety/Strategic-Measure_Vision-Zero-Traffic-Deaths-and-I/qn39-uq6s/data) that Surbhi helped Xavier publish under a tight deadline from OPM when our dataset wasn't yet stable. We need to figure out the best solution to get the OPM metric consuming the same regularly updated data as what we display in VZV.

- [x] @JaceDeloney to schedule time with Xavier and Surbhi to discuss
- [x] Decide on an approach below:
**Approach 1:** Add `KA per 100k (by Year)` to our comprehensive Open Crash data. This is the fast and simple solution but that attribute would be repetitive and the same value for crashes of the same year. It kind of feels out of place, but some hacks are good.
OR
**Approach 2:** Create a new Socrata dataset that is a more simple table with important aggregated crash metrics like "KA per 100k (by Year)" as columns and Years as rows

- [x] Understand the updates required on the OPM measurement side so that we can design a sustainable solution (ex, future years)

**Comment by SurbhiBakshi** [comment]
Meeting with Nicole scheduled for 08/27/2020

**Comment by johnclary** [comment]
+1 for Approach 2

**Comment by SurbhiBakshi** [comment]
Here is the table and measure card if we choose to use the aggregate table, I am using population numbers from the OPM dataset
1. Dataset
2. [Measure Card]

**Comment by JaceDeloney** [comment]
Since @SurbhiBakshi also has to create two new measures using population data, it was decided that Approach 2 makes the most sense. Will assign this to Surbhi and discuss action items from tomorrow's meeting.

**Comment by SurbhiBakshi** [comment]
Hi @JaceDeloney , slight correction to the comment above, I have two more VZ related metrics for this wave, but not related to population. I agree with Approach 2, but we would still need to know what population data to use.

**Comment by SurbhiBakshi** [comment]
@johnclary @JaceDeloney @mateoclarke - Here is the table and measure card I created to prep for the meeting tomorrow - It does not match the VZ Viewer or OPM metric charts because I am sourcing from the [VZ dataset](https://data.austintexas.gov/Transportation-and-Mobility/Vision-Zero-Crash-Report-Data/y2wy-tgr5/data) but using the population numbers used for the OPM metric.  
1. [Dataset](https://data.austintexas.gov/dataset/DRAFT_VZ_SD2023_MD1/fcfw-yx98/data)
2. [Measure Card](https://data.austintexas.gov/dataset/DRAFT_VZ_SD2023_MD1_Measure/5bkd-z8de)

**Comment by SurbhiBakshi** [comment]
- updated the assets above after replacing Total Population with Full Purpose Population.

**Comment by SurbhiBakshi** [comment]
**Meeting with Nicole, Lewis, Xavier, Jace, John** 
1. Get Xavier and Nicole to look at assets
2. Lewis will get confirmation from management that we can switch out the old dataset and measure card
3. Replace older links with links to new measure card and dataset
4. Include some way to navigate to VZ Viewer for most recently updated data / add text about how data is updated.

**Comment by JaceDeloney** [comment]
Next steps:
- [ ] Document queries needed to replicate the methodology used in the By Population chart in  VZV
- [ ] Work with @mddilley to define a solution that enables the M.D.1 measure to update automatically for future years (do not use a static crash number table, use the VZ crash table)
- [ ] Create documentation with link to VZV, explanation of changes made to this measure, measure methodology, definitions, and disclaimers

**Comment by amenity** [comment]
- [ ] @JaceDeloney add query here
- [ ] Update Socrata with new table
- [ ] Adding crash numbers to👆
- [ ] Demo for Lewis
- [ ] Push to Production

**Comment by JaceDeloney** [comment]
Next steps:
- Pull fatality and serious injury numbers by year
- Add those yearly numbers to [this dataset](https://data.austintexas.gov/Public-Safety/Strategic-Measure_Vision-Zero-Traffic-Deaths-and-I/qn39-uq6s/data) that includes [the latest Austin Area Population Histories and Forecasts](http://www.austintexas.gov/sites/default/files/files/Planning/Demographics/Austin_Forecast_2020_pub.pdf)
- Create the updated M.D.1 metric by summing the Death count with the serious injury count, dividing by population, and multiplying by 100,000
- Add the following content to the [M.D.1 metric page](https://data.austintexas.gov/stories/s/Number-of-persons-and-number-of-persons-per-100-00/xgcc-d979)

**Additional Measure Insights**
In August 2020, the Austin Transportation Department released Vision Zero Viewer, which allows people to view crash data by month, year, transportation mode, demographic groups impacted, time of day, and geographic location. Visit Vision Zero Viewer [here](https://visionzero.austin.gov/viewer/).

**Date page was last updated:** September 2020. Explanation of changes: The total number of persons who were killed or seriously injured was updated in September 2020 to reflect the latest information available to the City of Austin. Additional information regarding the Vision Zero Viewer was added.

**Comment by JaceDeloney** [comment]
Surbhi has had her hands full with other SD 2023 metrics during this sprint, so M.D.1 was moved to Sprint 34

**Comment by SurbhiBakshi** [comment]
- Made all the changes
 - asked Lewis to review. He had one small change to the content of the Story Page which I made. 
- Wrote to Nicole to review
