### ISSUE TITLE
Storybook followup tasks from MOPED Discovery Day

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3756]
- [x] Set up Github Action to auto deploy updates. https://www.learnstorybook.com/intro-to-storybook/react/en/deploy/
- [x] Explore how to package component library and import into moped repository.

**Comment by amenity** [comment]
https://medium.com/encode/setting-up-storybook-with-material-ui-and-styled-components-5bdacb6db866

**Comment by amenity** [comment]
@sergiogcx - if you have thoughts/resources re: Github actions, please add them here 🙏

**Comment by sergiogcx** [comment]
Thanks Amenity, I will 😃

**Comment by mateoclarke** [comment]
I've set up CI deployments with Github Actions for Chromatic with this PR:
https://github.com/cityofaustin/atd-kickstand/pull/4/files

![Screen Shot 2020-08-31 at 10 51 38 AM](https://user-images.githubusercontent.com/5697474/91735052-5c43cb00-eb71-11ea-84fa-e5fecce217f2.jpg)

![Screen Shot 2020-08-31 at 10 55 12 AM](https://user-images.githubusercontent.com/5697474/91735062-5f3ebb80-eb71-11ea-80fb-cc888c6202e1.jpg)

**Comment by mateoclarke** [comment]
@mddilley and I are going to pair on Kickstand component importing tomorrow 9/10

**Comment by mddilley** [comment]
Made progress pairing with @mateoclarke yesterday (9/10), and we decided to test out starting with the package and then adding Storybook. Today, I created a [new branch ](https://github.com/cityofaustin/atd-kickstand/tree/md_create_react_lib) and initialized the package with [`create-react-library`](https://github.com/transitive-bullshit/create-react-library). I then added Storybook and Mateo's story code. I was able to import a test component from the library locally, and the existing Github Actions deployment of the Storybook to Chromatic worked as well.

#### Outstanding ?'s
- [ ] Deployment? Possibly push updates to `main` for testing, and then use [Publish-to-npm](https://github.com/marketplace/actions/publish-to-npm) GitHub action to create new npm versions when pushing to `production`
- [ ] Development? Can develop the package locally using the example app provided by `create-react-library` but can we import into an app in a separate repo (before publishing to npm)?

**Comment by mddilley** [comment]
Local development using `npm link`
https://docs.npmjs.com/cli/link
https://flaviocopes.com/npm-local-package/
