### ISSUE TITLE
Improve DTS Service Rotation process

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#3763]
From #3762 , Action Items 

- [x] Note what happens to vendor email especially the ones related to new features and conferences
- [x] Outlook rule for Github issues (not DTS Service Requests)
- [x] Document how to transfer issues from one team member to another between rotations
- [x] Figure out which issues are urgent and process to address those - made a separate issue #3806
- [x] Make a note in Slack if someone makes a significant addition to the documentation

**Comment by johnclary** [comment]
looks like a productive retro @SurbhiBakshi! let's discuss during app sync?

**Comment by SurbhiBakshi** [comment]
@johnclary modified the rule to stop comment notifications from Zenhub coming to the inbox. @ChrispinP - tagged you on on this issue

**Comment by SurbhiBakshi** [comment]
Updated Rotation team in Slack channel.
