### ISSUE TITLE
Bug: RW-Street Event Web Application Acceptance  Process Missing (TL)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3765]
### Per stakeholder, folder process 'Web Acceptance Intake' is missing from their folders, causing staff to miss application submittals. This is a critical bug. 

**Stakeholder** Maria A
**DTS Manager:** Tracy

**Acceptance Criteria:**
- When an applicant submits an RW-Street Event via portal, the system should:
    - Update the folder status to 'Internet Pending'
    - Insert 'Web Application Acceptance' Process on the process tab

**Comment by licarir** [comment]
@TracyLinder @Nadin-Nader Is there a PROD RSN that we can use to trouble shoot this? What specific folder did this bug appear on? Thank you.

**Comment by licarir** [comment]
12530325 is one sample that I located. Surya said that if a folder does not ever get into the Application Incomplete Status and then the Internet Pending status, it will not run the procedure on the back end which inserts the 70000 procedure properly. The one I checked above through the audit button did not ever enter those statuses.

**Comment by licarir** [comment]
Checked issue 3047 to see if that was related. However, that changed Street Event RW folders from Pending Payment 50600 to Pending 50005 status by default.

We met with stakeholders earlier this week and confirmed that the folders in Test that are sent from Portal are not put into the Application Incomplete or Internet Pending status. They come in and are Pending.

**Comment by licarir** [comment]
Is this an issue of some folders needing default status of Pending and others needing another status? Previous code checked for User not containing @ and user not being INTERNET and fees existing. The last piece, fees existing was deemed to not matter for these Street Events as they said they will handle them separately.
 
 
IF (NOT (DUserID LIKE '%@%' OR DUserID = 'INTERNET'))  AND (ln_FeeCount > 0) AND ln_sub <> '50510'  THEN
  lv_error := COA_FOLDER.f_update_statuscode(argFolderRSN,50600); --pending payment
  IF lv_error IS NOT NULL THEN
     raise_application_error(-20001, lv_error);
  END IF;
END IF;


IF ln_sub = '50510' THEN
  lv_error := COA_FOLDER.f_update_statuscode(argFolderRSN,50005); --pending 
  IF lv_error IS NOT NULL THEN
     raise_application_error(-20001, lv_error);
  END IF;    
END IF;

**Comment by TracyLinder** [comment]
**Convo w/ Robert:** He needs to add a clause that says 'If the folder is input from portal, the status needs to update to Internet Pending'. Currently work is in branch; he thinks he can work on this on Wednesday & Thursday of this week.

**Comment by TracyLinder** [comment]
@licarir is there an update on this? Thanks!

**Comment by licarir** [comment]
@TracyLinder Making change this afternoon. I hope to be unit testing today and then get it back to Test by tomorrow. I had to spend a lot of time with new recruits training and handling Tango bugs. I also have had too many meetings this week. I have this time blocked out for ATD work.

**Comment by TracyLinder** [comment]
**Status:** Promoted to test on 9/9/20. Will need to facilitate UAT w/ Maria. @TracyLinder

**Comment by TracyLinder** [comment]
**Status:** Tracy to facilitate UAT. 
@TracyLinder

**Comment by TracyLinder** [comment]
UAT scheduled for 10/9 @ 11:30am

**Comment by TracyLinder** [comment]
**UAT Successful**
- Test RSN 12395749

### Approved for PROD 🎉

@licarir please work on deployment

**Comment by licarir** [comment]
Apparently this was being worked under INC0049603 put in by Maria Alonso. I have requested this go to PROD. This should go to PROD on Tuesday.

**Comment by TracyLinder** [comment]
Maria has been notified. Closing.
