### ISSUE TITLE
TDSD Web Map - Optimize performance

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#3766]
Look into the TDSD Web Map to see if there are any ways that I can make it run faster.
- maybe grouping feature layers into multiple feature feature layers would be faster for the data that we have sitting in the TDSD directory.
- Can look into making a copy and migrating it to the Web Viewer BETA version.

**Comment by johnclary** [comment]
You can consider simplifying the geometry of layers you have control over. E.g. with [mapshaper](https://mapshaper.org/).

**Comment by jaime-mckeown** [comment]
Created a new issue to modify TDSD Web Map when I met with them, forgot about this Issue, #5656. Closing this Issue.
