### ISSUE TITLE
[BUG] "Add Location" button disappearance bug when a comment is added to Signs Work Orders 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3777]
From the Work Order Details page, if you add a comment to the work order, the "Add Location" button disappears from the embedded map, and you must refresh the page in order to proceed.

Steps to reproduce:
- Login as a technician user.
- Navigate to a signs work order details page in an Issued status.
- Add a comment to the work order.
- "Add Location" button is not visible on map.

All the infos here: #1674

**Comment by amenity** [comment]
Haven't heard about this in a while.

**Comment by chiaberry** [comment]
code in [test app](https://atd.knack.com/test-smb-29-jun-2021-signs-and-markings-operations), PR is opened here: https://github.com/cityofaustin/atd-knack/pull/83
Christina will test on tablet tomorrow.

**Comment by amenity** [comment]
Thanks, @chiaberry !
