### ISSUE TITLE
Create Attribute Rules based on Attribute Assistant Rules

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#3787]
Work on creating Attribute Rules for Markings data to replace current Attribute Assistant Rules.

**Comment by jaime-mckeown** [comment]
- Created Thiessen Polygons for Intersections as this will be the quickest way to find the nearest intersection. Will make it only on Insert so the editor can change the intersection when a better choice is available.
- Figured out how to make an Intersect Attribute Rule work for finding the Intersection ID.

**Comment by jaime-mckeown** [comment]
Emailed Susanne and Christina regarding some of the AA Rules and the layers they reference.
- For the CBD field, they were using an old layer, but the CBD layer matches the Central Zone on the dapcz layer. Christina verified, and said to use the dapcz Central Zone for coding CBD.
- For the SIGNAL_INTERSECTION field, they were using the signalized intersections layer located in MAINT. This layer is static, and hasn't been updated in years. I will need to figure out the best method for keeping a copy of the Traffic Signals and Pedestrian Signals layer from AGOL in MAINT.
- For the SCHOOL field, it is a more complicated task, Christiana's response below:

> For schools, we determine that with several factors, but the main factor is a 0.25 mile buffer surrounding the schools. We do, however, also take into consideration the school zones surrounding that school. I’m not sure if there is one particular layer that would be good for school classification.

**Comment by jaime-mckeown** [comment]
# Specialty Point Domains
**Specialty Point Type**

1 - Word
2 - Arrow
3 - Symbol
4 - Parking
5 - Other
6 - Raised Pavement Markings

**Specialty Point Sub-Types for Bicycles**
- Arrow
   - 11 - Bike Arrow
- Other
   - 2 - Green launch pad
- Parking
   - 7 - Bicycle
- Raised Pavement Markings
   - None
- Symbol
   - 1 - Bicycle (Bike)
   - 3 - Bicylist
   - 5 - Chevron
- Word
   - 14 - Bike (word)

**Comment by jaime-mckeown** [comment]
Finally finished created and checking the Attribute Rules, started documentation for the Att. Rules in GitBook.

**Comment by jaime-mckeown** [comment]
Documentation complete: https://app.gitbook.com/@atd-dts/s/atd-geospatial/signs-markings-banners/markings-gis-pro-attribute-rules

**Comment by amenity** [comment]
@jaime-mckeown - Christina said this is working beautifully. Thanks!
