### ISSUE TITLE
Review Officer registration process and adjust as necessary

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3791]

**Comment by SurbhiBakshi** [comment]
@amenity - Reviewed and made changes to this page, put in some text on what to expect next. Do you remember if Pat had to use ausps email to login? I think so, but was not 100% confident, so did not include that specific detail. Perhaps that needs to be in the email sent out to the officers. Right now I am directing the officer to the home page after the form is successfully submitted.

**Comment by SurbhiBakshi** [comment]
@amenity - we need to communicate in the email the officers receive that the officer can log in either with the password in the form, or using COACD.

**Comment by amenity** [comment]
Wonderful! According to [our notes](https://docs.google.com/document/d/1PBtoOPWAwLMduMZs9jJhMu-YX213UgxbOuNnVBAumko/edit#), he was able to use COACD to log in so we are good there.

**Comment by amenity** [comment]
@SurbhiBakshi - Looking at the registration page: ![Screen Shot 2020-09-08 at 4.57.42 PM.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/f3643335-6687-4d71-935b-f4732bb681b8)

Can we hide the password field since they'll be logging in with their City credentials? I think we discussed setting the password to the officer's badge number with a rule so that the form could be submitted without that field.

**Comment by amenity** [comment]
@SurbhiBakshi got rid of the password field and the registration works great. ![Screen Shot 2020-09-08 at 5.09.16 PM.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/78c6d94b-4e0e-4697-b78d-d587914a3b3d)
