### ISSUE TITLE
M.D.1 - Create Draft Aggregate Dataset and Measure Card with VZ Viewer dataset

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#3800]

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/078d80c4-3f9a-4b18-b98d-641b32943ad5)

**Comment by SurbhiBakshi** [comment]
going to share the dataset and measure card with Xavier for review.

**Comment by amenity** [comment]
See #3752
