### ISSUE TITLE
IT Support: Create Escalation Procedures for DTS Service Desk on SharePoint

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#3805]
- [x] Rules
- [x] Urgent Issue Guidelines/Examples
- [x] Link to Service Desk Ticketing for all other issues
- [x] Support Times
- [x] Contact Tree/Structure
- [x] Accessible to ATD Department personnel only

**Comment by amenity** [comment]
Moving this to `On Deck`.

**Comment by johnclary** [comment]
@dianamartin would you take care of this for us? :)

**Comment by dianamartin** [comment]
@johnclary Where should I put this information GitBook Knowledge Base?

**Comment by dianamartin** [comment]
After speaking with John, his idea was to create a page in our DTS SharePoint page. Context needs to be added though.

**Comment by amenity** [comment]
@ChrispinP - all yours 🌻

**Comment by ChrispinP** [comment]
Updated Sharepoint Org Chart. Updated Service Request Sharepoint page with CTM Service Desk link, urgent/critical request guidelines, typical SLA, some language changes, and adding link to Escalation Procedures.

Created Sharepoint Escalation page with a Matrix for who to contact for specific issues. Not sure if any other numbers/emails should be added here.

Linked the Escalation page on the DTS Service Request form for reference.

Ready for review.

**Comment by ChrispinP** [comment]
reviewed this with team. now closing due to no further resulting issues.
