### ISSUE TITLE
Moped | Project Geometry - Create wireframe for VZ polygon base geometry approach

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3807]

**Comment by johnclary** [comment]
@amenity 
![project geometry wireframe](https://share.balsamiq.com/c/pPuj7Ld6Uu9aEh2z2RU2FP.png)

**Comment by amenity** [comment]
@johnclary - can you add an estimate to this and close it? We may need to do more wireframes if we take a different approach, but I think this one is done!
