### ISSUE TITLE
Moped | Phases and Milestones - Create wireframe

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3811]
Phases and Milestones Tables: https://balsamiq.cloud/senhupm/p9y6tuy/r0869

**Comment by amenity** [comment]
@zappfyllc — did you decide whether it would be more expedient and/or effective to do this in Knack over Balsamiq?

**Comment by zappfyllc** [comment]
I can do it in Balsamiq after our Slack convo! It isn't too difficult to create, I'm going to try to get to it before the end of the day!

**Comment by zappfyllc** [comment]
Estimated adjusted to 2 because I'm going to work out the phases/milestones workflow in addition to the wireframe(s) so this may tie in a bit with the project timeline feature.

**Comment by zappfyllc** [comment]
Balsamiq wireframe added for phases/milestones tables, which can viewed in the context of a project. Per comments in Balsamiq:

```
MVP or "Alpha" feature should just include a table of phases with associated milestones that the user can add/delete.

Future feature will involve a more complex workflow where the user will be able to end one phase (making it inactive) and start another (making it active), which could spawn a set of predetermined milestones, but this would need to involve configuration from a user based on project type or at the outset of the project. Needs some user research/validation first.
```

**Comment by amenity** [comment]
@zappfyllc - _finally_ looking ... all looks great. 👍 📆

**Comment by amenity** [comment]
@zappfyllc - In case Balsamiq didn't notify you sufficiently, I did end up making a few tweaks and comments. 🧹
