### ISSUE TITLE
VZV | Map | Mode filters reset after changing type filter on touch devices

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#3812]
While using the map on my iPhone, I noticed a bug where mode filters that were removed would reset to active after changing a type filter. I tested in BrowserStack and saw the same bug in iPhone 8, iPad, Galaxy Tab, and Samsung S10 devices. Bug not present in Windows or macOS.

To reproduce:
1. Use a touchscreen device to go to VZV map view
2. Remove any mode filter
3. Change the type filter
4. See the mode filters all applied again

![iosbug](https://user-images.githubusercontent.com/37249039/91477841-94db6000-e864-11ea-9767-aa9040e64d0d.gif)

**Comment by mateoclarke** [comment]
Good find! 
![image](https://user-images.githubusercontent.com/5697474/91515496-f1fc0380-e8ae-11ea-919d-9e3be391a052.png)
