### ISSUE TITLE
Moped | New Project - Create wireframe

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3816]
[Wireframe here](https://balsamiq.cloud/senhupm/p9y6tuy/r2278).

**Comment by amenity** [comment]
@JaceDeloney @johnclary @zappfyllc — I feel like this one is pretty straightforward...ready for review.

**Comment by johnclary** [comment]
@amenity looks good to me. r.e. eCapris ID: noting that ideally this would be a controlled autocomplete field that searches a list of known eCapris subproject IDs. not MVP, though!

**Comment by amenity** [comment]
![New Project](https://user-images.githubusercontent.com/1463708/96050455-45b2b400-0e3f-11eb-8f52-527e5ef74561.png)
