### ISSUE TITLE
VZE | Spike Upgrade to CoreUI 3.2.0

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3818]
We used CoreUI v2.1.12 when we started developing VZE. This is a spike to evaluate the level of effort required to upgrade to v3+.

Document the steps for better sizing and scoping.

**Comment by patrickm02L** [comment]
We should review the release notes to see if there are any really strong added benefits to upgrading. 

Before doing it we would need to get an idea of the scope of upgrading. CoreUI's latest release is v4.0.1.

**Comment by patrickm02L** [comment]
@patrickm02L maybe a light weight issue that devs can explore in upcoming sprint.

**Comment by patrickm02L** [comment]
Core UI is now on version 4

**Comment by patrickm02L** [comment]
At some point I'm sure we'll want to upgrade to the latest CoreUI, but since it never gained any traction as a priority I'm happy to let this one go since it way over it's 2-year expiry date.
