### ISSUE TITLE
Nice photos for presentation deck

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#383]

**Comment by amenity** [comment]
@dianamartin - close this when we have them all, please.

**Comment by dianamartin** [comment]
Christina had her camera and was able to upload the pictures. [Folder path](\\coacd.org\dfs\TPSD\ATD\Signs_and_Markings\SIGNS\Photos_Videos\Sign Technicians Using Knack). I went and made a parent label so we can go through them easier.
