### ISSUE TITLE
Investigate missing records in Bluetooth Travel Sensors 

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#3832]
Bluetooth Travel Sensors -Traffic Match Summary Records (TMSR):
Hello, My name is Bhooma and I am a M.S Data Science Student at DePaul University. I am doing a research project under Dr. Ustun analyzing the impact of COVID-19 on Transportation Networks. I was looking to compare speed data between 2019 and 2020 and noticed that parts of May-June 2019 and May 15-August 1 2020 were missing. I was hoping you would be able to clarify the reason behind the missing data. Thank you in advance for your time! Bhooma

**Comment by SurbhiBakshi** [comment]
- Hard to know which records are missing from May 1 to June 30, 2019 , will write to Bhooma to ask for more specific details on the gaps.
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/7687c6e2-ca02-4b6c-b988-9205a43dc46f)


- Records missing from June 1 to August 1, 2020 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/9650c2f9-f4e5-4b3b-a9be-56d6e836014d)

**Comment by SurbhiBakshi** [comment]
@johnclary - don't see any records from June 1 to Aug 1, I have asked Bhooma to give me more detailed information on the gaps from 2019.

**Comment by SurbhiBakshi** [comment]
@johnclary, as per Bhooma -There seems to be a gap between June 02 9:00:00 AM to June 25 10:15:00 AM. May is complete.

**Comment by amenity** [comment]
We do not have this data — the Bluetooth server went down for 3 weeks.

**Comment by SurbhiBakshi** [comment]
Wrote to Bhooma that we don't have this data.
