### ISSUE TITLE
SCP3 Bug: Create Child Process Attempt System Error 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3835]
### On ROW Admin Process, when attempting to save attempt 'Create Permits', the system would not save the attempt, throwing an error message "Unable to Update Process Status", however the child permit was created. 

![image](https://user-images.githubusercontent.com/49930868/91746325-09264400-eb82-11ea-8f65-090ef9b3ad78.png)

**Comment by DavidGallantUnisys** [comment]
@TracyLinder This is no longer required as we have automated the Child Creation process correct?

**Comment by TracyLinder** [comment]
This was user error. Child permits are created based on folder infos. Closing.
