### ISSUE TITLE
Create job posting

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3855]
Looks like we can reuse [this one](https://docs.google.com/document/d/1FELWSOMEEehdB-qAYIzehguBEABL9ViJqRJX_WRbDpM/edit)

**Comment by jaime-mckeown** [comment]
@johnclary I've added comments to the job posting. Tomorrow is the GIMOB, any new info to share about the posting with the group?

**Comment by johnclary** [comment]
we're just waiting on signatures so that we can post the job. you can tell them it will be up within two weeks.

**Comment by johnclary** [comment]
I incorporated @jaime-mckeown 's edits and sent the posting to HR. Asked for a three-week posting open to the public.

**Comment by jaime-mckeown** [comment]
Job posting was listed last Friday. Added a post to the GIS Community and to the ATX GIS General Teams Page to get the word out.
