### ISSUE TITLE
Review resumes

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3856]

**Comment by dianamartin** [comment]
1/4-1/5
- Reviewed 61 candidates, Supplemental Questions, Cover letters and Resumes
- Tagged which ones passed `Preferred Qualifications` requirements to shrink candidate pool
- Jaime to review "Maybe" selections, then we regroup as a team to get our final selections to John and HR

**Comment by jaime-mckeown** [comment]
1/6 - Reviewed Diana's notes and Supplemental Questions for the Yes and Maybe list. Added some notes for the discussion this afternoon.

**Comment by jaime-mckeown** [comment]
1/7 - The team met yesterday to review the applications. We sent 11 to HR for interviews.
