### ISSUE TITLE
Extract CR3s for 10 Locations

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3859]
VZ Team is working with an outside consultant to do crash mapping on top-ranking locations. They need the CR3s for those 10 locations so that they can better understand the direction/movement that led to the crash.

**Request:**
Create a script that pulls the CR3s for the 10 location IDs and deposit them to a G-drive folder. Create script that can take arguments as an array so that the extraction process can remain flexible, yet reusable in the future.

**Requirements:**
Date range: August 1, 2015 to July 31, 2020.
G Drive Location: G:\Trans\2018 Bond Vision Zero Safety Projects\Safety Projects\AECOM
Locations:

- Stassney at Congress, Polygon ID 969C3189BB
- S 1St at Stassney, Polygon ID DDFFFF8BD0
- William Cannon at S. 1st Street, Polygon ID 784D6606D5
- Congress at Cesar Chavez ID 4CE5E0D8E4
- Riverside at Congress ID 296FD98E7C
- Menchaca at WmCannon ID BAAA91CF6A
- Dessau at Braker/Shropshire ID 3B357E509F
- Dessau at Braker ID 2C2D258CDC
- McNeil at Parmer ID 0A4FCA4EA6
- Burnet at Gracy Farms ID 668BD59CE9

**Comment by sergiogcx** [comment]
The data has been uploaded to that specific folder under the name `vze_extract_sept_08_2020.zip`

![2020-09-08_15-02-27.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/577d1486-3f1a-427e-a5e7-30d3ec5b43c6)

**Comment by sergiogcx** [comment]
The script I wrote to download these files and to package them together can be re-used, all I have to supply is the list of locations and the two dates (start, end date). This means we can use the code to automate this process in the future via the UI.

**Comment by sergiogcx** [comment]
For the automation part, I am thinking of two different approaches:

1. Make extracts on request: We would wait until a request is made.

Pros:
- Less complexity to make it work.
- No need of tracking changes to locations.

Cons:
- UI development will be needed
- Zip downloads will not be instant.


2. Make extracts for all locations preemptively: We would take initiative to package CR3s for every location.

Pros:
- CR3 PDFs for a location would be available instantly, no need of request.

Cons:
- Managing updates to locations can take a lot of code. Imagine a crash belonging to one location is assigned to another, that makes two locations that need to be updated. Also every night new crashes come in, some of them will have locations assigned to them, meaning those locations need to be updated.
