### ISSUE TITLE
Document Alpha user permissions 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3862]
We are only going to have one role in Alpha, Project Team Member, so we just need to document a [very basic permissions scheme](https://docs.google.com/spreadsheets/d/1gNCz63qFpztiuL_JK4aPNnicjCglmATOW1dbpU0wxWk/edit#gid=351804243) that delineates what functionality they have access to based on whether or not they are associated to a given project as staff/personnel/team.

**Comment by amenity** [comment]
@zappfyllc — It looks like you've taken care of this. 🙏 If so, will you add an estimate and close? 

What do you think are next steps here? cc/ @sergiogcx

**Comment by sergiogcx** [comment]
@amenity if there aren't any more changes to the permissions scheme, we can begin working on implementing those roles in Cognito and Hasura. You can assign that task to me.

**Comment by amenity** [comment]
@sergiogcx made ya #3873  —— but wait until @zappfyllc gives ya the go-ahead. 🐎

**Comment by sergiogcx** [comment]
Thank you @amenity
