### ISSUE TITLE
Review Vision Zero Zenhub estimates, velocity, etc. to inform Moped (& DTS) Product Ops

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3869]
Having used [this estimate system](https://atd-dts.gitbook.io/wiki/product-ops/github-project-management#estimates) in Zenhub for VZ* work,  let's 
- Review velocity and other patterns over time
- Consider how this can inform Moped Sprint Planning going forward
- Consider whether we should modify our DTS-wide approach to estimates

**Comment by JaceDeloney** [comment]
Based on the previous 7 sprints with Vision Zero Crash Database and Vision Zero Viewer labeled issues, the team completes ~95% of the issues that they take on each sprint. Here are the averaged Estimated vs Completed numbers:
**Average estimated:** 182
**Average completed:** 172

This info may be helpful in communicating high-level delivery dates if we are able to size all of the known work within a given release (e.g., all issues that are within the MOPED alpha scope). Overall, the team is good at completing the work that they commit to per sprint.

**Comment by JaceDeloney** [comment]
Just checked MOPED sprints and so far the trend has been exactly the same across VZ & MOPED; the team completed 95% of what they commit to! Closing this out.
