### ISSUE TITLE
Meeting: TIA Module Clarifications 9/2/20

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#3872]
**Date/Time:** Sep 2, 2020 @ 2pm
**Attendees:** Joan, Nathan, Tracy, Chrispin

**Comment by TracyLinder** [comment]
### Notes

**Changes to +Comment button/feature:**
- Remove 'Type' field
- Remove 'Email Address' field
- Update the default value on 'Send Email?' field to No
- If user inputs 'Yes' on the Send Email field, the system should send the email to the email address in the case details and incorporate any text/attachments the user adds

**New Feature/Button: +Scope**
- Position the button between existing buttons 'Comment' and 'Fee Status'
- Clicking button opens a form similar to the +Comment form
- Form Fields: Scope Status, Comment, Send Email?
    - Scope Status field pick values: In Review, Revision Required, Approved
    - Send Email field: Displays and defaults based on user input.
        - Scope Status = Approved, do not display the Send Email field
        - Scope Status = Revision Required or In Review, display the Send Email field and default value to 'Yes'
    - Comment field: Update to optional; it's currently required
- If user inputs 'Yes' on the Send Email field, the system should send the email to the email address in the case details and incorporate any text/attachments the user adds

**TIA Review Details Page**
- Create a feature that allows users to edit an existing general comment or an existing scope comment. 
    - _If the general comments and scope comments live on the same table, we will need to still capture the comment type without the user having to input that info. Tracy & Chrispin may need to discuss this further._ 

**New Feature: Communications**
_A new button on the TIA Case Details Page, and a new page._
- New button on TIA Case Details 'Communications'
- Clicking 'Communications' button takes user to the 'Communications' page
- The page displays a Communications Table and an 'Add Communication' button
- Communications Table Columns: 
    - Type
        - Field Values = Approval, Scope - Revision Required, General Comments, Outlook
    - Date & Time
    - Recipient Email
    - View Email (Feature opens the email/attachment for user viewing)
- Feature that allows user to add new records to the Communications Table
    - Button 'Add Communication'
    - Clicking 'Add Communication' opens a form with the table column fields, allowing users to input values in each field
    - The form allows user to attach the email, and maps the attachment to the 'View Email' field
- Feature that creates a record on the Communications Table whenever an email is sent via the app or by the system

**New Feature: TIA Case Log**
_A new button on the TIA Case Details Page, and a new page._
- Create button on TIA Case Details Page, 'TIA Case Log'
- Clicking the button takes user to the 'TIA Case Log' page
- The page displays a table of case changes/updates
- _Table columns and page design are TBD_

------


### +Scope Approved Workflow
1. Click +Scope
2. Update Scope Status field to 'Approved'
3. (Optional) Input comments and attachments
4. Click Submit
5. The system sends an email to the case applicant (email address in TIA case details)
    - We will need to review this email template and update it

### +Scope Revision Required & In Review Workflows
1. Click +Scope
2. Update Scope Status field to 'Revision Required' or 'In Review'
3. (Optional) Input comments and attachments
4. (Optional) The 'Send Email' field defaults to yes. Update to no if an email should not be sent
4. Click Submit
5. If 'Send Email?' value is Yes, the system sends an email to the case applicant (email address in TIA case details)
    - We will need to review this email template and update it

**Comment by TracyLinder** [comment]
### Followup Tasks
- [ ] Make resulting GH issues (Tracy)

**Comment by johnclary** [comment]
@ChrispinP would you mind making issues for the items that came out of this meeting? @TracyLinder is swammmped.

**Comment by TracyLinder** [comment]
@ChrispinP you should be able to copy & paste from my notes above, and add anything you see was missed.

**Comment by ChrispinP** [comment]
Issues #3901, #3902, #3903, #3905, and #3906 created from this meeting.
