### ISSUE TITLE
ARR Requesting to Add Street Sweeper data to Bike Map - Heather K.

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#3882]
From Heather:

> Hi there,
> 
> Would it be possible to add some data from Austin Resource Recovery to the existing bike web maps?
> 
> ARR is hoping to have a web map that shows which bike routes our street sweepers go down:
> 
> “ARR is working on creating a performance measure story page for a measure given to our department by Council (Estimated Percent of Protected Bike Lanes Swept Annually). The Office of Performance Management is requesting to include a map of the City highlighting all Protected Bike Lanes.”
> 
> I put together some concept maps (attached) showing the protected bike lanes and our street sweeping data. However, they are looking for something much more robust.
> 
> It didn’t seem like the best approach to me for ARR to completely recreate the bike map. Especially since ARR doesn’t “own” the bike lane data. Also, it’s probably more effective to enhance the existing map, rather than create more maps with less data per map. I also think that ATD’s bike map users would appreciate knowing which streets are regularly swept!
> 
> I’m imagining just having a switch somewhere in the bike lane web map where users can turn on the data showing which streets the street sweepers go down.
> 
> We can provide a street sweeper polyline feature class in ArcGIS Online, and keep it up to date.
> 
> What do you think?

**Comment by jaime-mckeown** [comment]
Forwarded Heather's email to Sophia at ATSD for feedback.

**Comment by jaime-mckeown** [comment]
> Hey Jaime, 
> 
> Well my first thought, or question really, is that I understand that a lot of the street sweeping that takes place in bike lanes is 311 request based. For example, when we get a 311 request about debris in the bike lane we forward it to ARR (I really want those 311 requests to go directly to ARR but that’s not happening currently). Granted, I see the email is about protected bike lanes and perhaps referring to the baby sweeper schedule. I think internally we differentiate between regular bike lane sweeping and protected bike lane sweeping b/c we have to use different equipment but I wouldn’t want there to be confusion for people viewing the schedule and thinking that’s all the bikeways that get swept and that’s the only time they get swept. Does that make sense?
> 
> As far as data duplication v. adding a field to the bikeways data, we recently created (surely, with yalls help!) a webmap viewer so perhaps we could add that as a feature. My main concern is that would not reflect the true work of ARR based on my comment above. 
> 
> Hope this is helpful!
> 
> Sophia

**Comment by jaime-mckeown** [comment]
Forwarded Sophia's response on to Heather to get a conversation going.

**Comment by johnclary** [comment]
Closing :)
