### ISSUE TITLE
Project: Real-Time Road Condition Dashboard

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3883]
A public-facing dashboard which displays current and historical road conditions from sensor data.

### Background

AMD will be installing weather sensors on a number of key roadways, the primary purpose of which is to monitor the condition of bridges which might freeze.

We have been asked to:
- archive the weather sensor data in a centralized location
- develop a public-facing dashboard which displays the current and historical conditions of these roadways

### Desired Outcomes

The information displayed in this dashboard will be used by regional decision-makers when closing roadways and cancelling schools as a result of icy conditions.

### Resources
- [Drive folder](https://drive.google.com/drive/u/0/folders/1UPhyCladgInDeFm5zXG5BA89BXTgPOVl)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://data.mobility.austin.gov/about/) team. Project status is documented regularly in the comments below.

**Comment by JaceDeloney** [comment]
Jace to schedule info gathering meeting this week with Jen, Brian, and John

**Comment by JaceDeloney** [comment]
Meeting has been scheduled for Friday, September 25.

**Comment by amenity** [comment]
This kinda sounds like a `Product` @johnclary @JaceDeloney ...

**Comment by amenity** [comment]
Getting cold, seems too ambitious to get a fully-featured dashboard delivered before the first freeze...

Goal: Somebody who doesn't know about these systems can look up conditions online. In the near-term, it is fine if Jim/Rob/et al. translate the data. 

DTS just needs to make data accessible to ATD staff.  Still waiting for word from Finance on when the sensors will be purchased+installed.

**Comment by johnclary** [comment]
The [ETL Pipeline](https://github.com/cityofaustin/atd-data-tech/issues/4866) is complete and will process any additional sensors that are setup in the Data Tracker. Per discussion, we will not be developing a dashboard in the near term. Moving this project to backlog.

**Comment by johnclary** [comment]
Per discussion with Brian C., the MMC will develop a dashboard based on our [public dataset](https://data.austintexas.gov/dataset/Real-Time-Road-Conditions/ypbq-i42h). [ETL repo](https://github.com/cityofaustin/atd-road-conditions).

**Comment by amenity** [comment]
@johnclary - do you have the link to that dashboard?
