### ISSUE TITLE
Project: Residential Parking Permits v1.0

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#389]
We replaced a paper-based process with a web-based interface through which residents can easily apply for and renew their residential parking permits.

![RPP Blueprint Print](https://user-images.githubusercontent.com/1463708/61570018-bd810b80-aa4f-11e9-941a-082f6fa4e6a2.png)

This project encapsulates our work to modernize the City of Austin's [Residential Permit Parking](http://www.austintexas.gov/rpp) (RPP) program. The effort includes the procurement or development of a web-based permitting interface through which residents can easily apply for and renew their residential parking permits.

### Resources
- [Teams directory](https://teams.microsoft.com/_#/files/General?threadId=19:e3597e8949f8488c961b78460a886d45@thread.skype&ctx=channel)
#### Phase I: Discovery
- [User interviews](https://teams.microsoft.com/_#/files/General?threadId=19%3Ae3597e8949f8488c961b78460a886d45%40thread.skype&ctx=channel&context=Phase%2520I%252FInterviews)
- [Photos](https://teams.microsoft.com/_#/files/General?threadId=19%3Ae3597e8949f8488c961b78460a886d45%40thread.skype&ctx=channel&context=Phase%2520I%252FMedia)
- [Synthesis presentation](https://teams.microsoft.com/l/file/42035821-BD12-456F-887A-D49C3EFAF20C?tenantId=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&fileType=pptx&objectUrl=https%3A%2F%2Fcityofaustin.sharepoint.com%2Fsites%2FResidentialParkingPermitApplication%2FShared%20Documents%2FGeneral%2FPhase%20I%2FSynthesis%2FCopy%20of%20RPP%20Synthesis%20Presentation.pptx&baseUrl=https%3A%2F%2Fcityofaustin.sharepoint.com%2Fsites%2FResidentialParkingPermitApplication&serviceName=teams&threadId=19:e3597e8949f8488c961b78460a886d45@thread.skype&groupId=0dc56302-8767-4d4b-9f5e-e6a70cd07e4f)
- [Service blueprint](https://cityofaustin.sharepoint.com/sites/ResidentialParkingPermitApplication/Shared%20Documents/General/Phase%20I/RPP%20Service%20Blueprint.png)
- [All the data points ever](https://airtable.com/tbl7UYLYuYzOe5a52/viwNunLldWj4jH88J?blocks=hide)

#### Phase II: Implementation
- [Project repo](https://github.com/cityofaustin/atd-residential-parking-permits)
- [Project board](https://github.com/cityofaustin/atd-data-tech#workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/board?labels=project%3A%20residential%20parking%20permits&repos=138333607,140626918) — view with [ZenHub extension](https://www.zenhub.com/extension)
- [Cost model of current process](https://teams.microsoft.com/_#/xlsx/viewer/teams/https:~2F~2Fcityofaustin.sharepoint.com~2Fsites~2FResidentialParkingPermitApplication~2FShared%20Documents~2FGeneral~2FPhase%20II~2Fcost%20model~2FRPP%20cost%20model.xlsx?threadId=19:e3597e8949f8488c961b78460a886d45@thread.skype&baseUrl=https:~2F~2Fcityofaustin.sharepoint.com~2Fsites~2FResidentialParkingPermitApplication&fileId=01D8FE20-840D-4944-A61F-0CEC71D73503&ctx=files&viewerAction=view)
- [Statement of work](https://teams.microsoft.com/l/file/D4B883E3-B2BC-4A45-8F91-5C7FAA7AB82F?tenantId=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&fileType=docx&objectUrl=https%3A%2F%2Fcityofaustin.sharepoint.com%2Fsites%2FResidentialParkingPermitApplication%2FShared%20Documents%2FGeneral%2FPhase%20II%2FSOW%2FATD%20SOW%20Mobile%20platform.docx&baseUrl=https%3A%2F%2Fcityofaustin.sharepoint.com%2Fsites%2FResidentialParkingPermitApplication&serviceName=teams&threadId=19:e3597e8949f8488c961b78460a886d45@thread.skype&groupId=0dc56302-8767-4d4b-9f5e-e6a70cd07e4f)
- [Platform requirements](https://teams.microsoft.com/_#/xlsx/viewer/teams/https:~2F~2Fcityofaustin.sharepoint.com~2Fsites~2FResidentialParkingPermitApplication~2FShared%20Documents~2FGeneral~2FPhase%20II~2FSOW~2FATD%20SOW%20Mobile%20park%20Platform%20Requirements.xlsx?threadId=19:e3597e8949f8488c961b78460a886d45@thread.skype&baseUrl=https:~2F~2Fcityofaustin.sharepoint.com~2Fsites~2FResidentialParkingPermitApplication&fileId=642FE46D-2E41-4904-A6E7-07DCBC51B3A8&ctx=files&viewerAction=view)

### Prioritization
|                              | score |
|------------------------------|-------|
| Builder time                 |       |
| Customer effort to implement |       |
| Demonstrated capacity to work in an iterative, user-centered (negative) |       |
| **Total: Effort**                |       |

|                              | score |
|------------------------------|-------|
| Solves multiple needs                 |       |
| # of users                         |       |
| Efficiency gains |       |
| **Total: Value**                |       |

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://transportation.austintexas.io/about/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
**Status update:**
We have refined user stories, calculated [costs of the current RPP process](https://cityofaustin.sharepoint.com/:x:/s/ResidentialParkingPermitApplication/ESD-2AENhERJph8M7HHXNQMB_XF2LWZ6yrSdCwy56uOuIQ?e=PXUm48), and [compiled requirements](https://cityofaustin.sharepoint.com/:x:/s/ResidentialParkingPermitApplication/EUOIzkWg8EFMgyR2jEvs3DsBDZYQxwNIFJog3nqH1_kXFQ?e=sRDyuz) in an SOW. We are now amending ATD's [ParkATX](https://www.parkatxapp.com/) contract to include a [permitting solution](https://www.passportinc.com/product/permits/) that the vendor, Passport Labs, offers. We will pilot the application for a year before posting a formal RFP for long-term solutions.

**Comment by amenity** [comment]
**Status update**
We decided to limit the area of the initial Passport RPP implementation to West Campus. Beginning with this pilot brings the price below the needs-Council-approval threshold, making the amendment much simpler. We have brought on Stephanie M. as a part time project manager. She will oversee the Passport implementation and pick up where Teri left off for the RFP that will go out next year.

**Comment by amenity** [comment]
@TracyLinder - in your court now! 🎾💥🙌

**Comment by johnclary** [comment]
Per Joseph, this is backlogged and will be rolled into parking RFP(s) for parking technology.
