### ISSUE TITLE
Schedule TE BO & Home Upgrade

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#3896]
Emailed TE GIS users on 10/2 to verify where their computers are located since my list doesn't seem to be accurate. Hoping to do upgrade next week.

**Comment by jaime-mckeown** [comment]
- 5 users had their computers in the office, upgraded Wed night, all were successful.
- Sent email to home users yesterday, gave them until the end of next week to upgrade.

**Comment by johnclary** [comment]
@jaime-mckeown plz follow up

**Comment by jaime-mckeown** [comment]
Sent follow-up email to the users that I have not heard from.
