### ISSUE TITLE
Cancellation modal on "Sign Up" page

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#3899]
In https://github.com/cityofaustin/atd-data-tech/issues/3863, a "Cancel My Sign Up" button was added to give officers the ability to cancel on the "Sign Up" page. When the officer clicks this button, it should open a [cancellation confirmation modal](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/5b916487-6d6b-44bc-81df-6c066551256f) that is currently implemented on the "My Assignments" page.

**Comment by mddilley** [comment]
This is now ready in the `test-vision-zero-in-action-27-august-2020` instance. The form replicates all of the fields populated by the submission of this modal on the "My Assignments" page.

![vzaCancel](https://user-images.githubusercontent.com/37249039/92533369-efc36e80-f1f7-11ea-980b-f536e5b31c97.gif)

**Comment by amenity** [comment]
@mddilley - missed commenting on this one; it looks great! A few notes in [this issue](https://github.com/cityofaustin/atd-data-tech/issues/3965) probably make sense for you to look at here, if possible.
