### ISSUE TITLE
[Enhancement] Add/Edit Scope Button for TIA Module

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#3902]
- Position the button between existing buttons 'Comment' and 'Fee Status'
- Clicking button opens a form similar to the +Comment form
- Form Fields: Scope Status, Comment, Send Email?
- Scope Status field pick values: In Review, Revision Required, Approved
- Send Email field: Displays and defaults based on user input.
- Scope Status = Approved, do not display the Send Email field
- Scope Status = Revision Required or In Review, display the Send Email field and default value to 'Yes'
- Comment field: Update to optional; it's currently required
- If user inputs 'Yes' on the Send Email field, the system should send the email to the email address in the case details and incorporate any text/attachments the user adds

+Scope Approved Workflow

- Click +Scope
- Update Scope Status field to 'Approved'
- (Optional) Input comments and attachments
- Click Submit
- The system sends an email to the case applicant (email address in TIA case details)
- We will need to review this email template and update it

+Scope Revision Required & In Review Workflows

- Click +Scope
- Update Scope Status field to 'Revision Required' or 'In Review'
- (Optional) Input comments and attachments
- (Optional) The 'Send Email' field defaults to yes. Update to no if an email should not be sent
- Click Submit
- If 'Send Email?' value is Yes, the system sends an email to the case applicant (email address in TIA case details)
- We will need to review this email template and update it

**Comment by ChrispinP** [comment]
Created new Scope enhancement. In order to work correctly had to create a scope details page. Have not yet removed old comment/scope feature.

Can add more scope buttons/tables to Review Details page if wanted there as well. Considering implementing these same changes to submissions so they are more organized. Still need to add email notifications for attachments and verify data formulas are working.

Wondering if keeping a single attachment object instead of creating multiple attachment objects is ideal. Im under the impression that a single object is more efficient than multiple of the same objects creating more connections and fields.

**Comment by ChrispinP** [comment]
Removed Email field, unable to create rule to populate field. Created email rules instead for add and edit comment/attachment forms that will automatically send email to requester if Notify Requester is set to Yes. Need to set comment field back to required since there is email rule now so non informative emails are not sent on accident.

@TracyLinder ready for review

**Comment by ChrispinP** [comment]
Updated Scope, Review, and Submissions for sending emails and adding comments/attachments.

**Comment by ChrispinP** [comment]
Removed old comment/scope feature. The Scope Details page is now home to Scope Status Change, Scope Comments, and Scope Attachments.

Converted all attachments and comments into their respective single objects. Knack does not benefit from common object practice as exemplified in code development. Scope object was also combined with the Request object for usability ease and functionality. Previously had issue with comments and attachments not displaying correctly for Scopes and Submissions. This should now be rectified. Dates, Updates rules, and Email rules were all updated to automatically set email and status upon submission. 

Ready for review

**Comment by TracyLinder** [comment]
Scope page & features looking good! Closing.
