### ISSUE TITLE
Project Extent | Test conversion of Interim Project Database geometries into VZ-polygon-based geometries

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3904]
We are going to use the Vision Zero polygons as a basis for Moped project geometries, see discussion [here](https://github.com/cityofaustin/atd-data-tech/issues/3667).

At some point we will need to migrate spatial data from ATSD's Interim Project Database into Moped, so we will need to convert the hand-drawn polylines to VZ-polygons. 

The Interim Project Database tabular data in Access is related to spatial data stored in an ArcGIS MXD file via a join on each a project_facility ID field that exists in both systems. Accordingly, visualizing and editing spatial data has been performed in ArcGIS. Dylan J., however has been building a process/system to make the data accessible (and editable, I believe — checking on this) via AGOL. For a demo, see ~34:00 in this [Sprint Review recording](https://web.microsoftstream.com/video/760716a9-931e-444e-9acc-0a0b31c235e6). 

Per a conversation with Dylan 9/3: 
- They have geometries for every project
- Geometries represent the full extent of every project, either as
    - A compilation of real-world facilities with their own geometries;
    - A “Project Extent” facility type developed for groups like TED who do not have time to map their work at the facility level

We would like to test:
- Can _all_ projects be converted to polygons?
- What does the conversion entail, process-wise?
- Are there any data quality issues with the resulting data?

As a second, follow up spike, I might suggest looking at [how we will represent a multitude of overlapping polygons on a map](https://github.com/cityofaustin/atd-data-tech/issues/3667#issuecomment-682145851).

**Comment by amenity** [comment]
@johnclary - I think this is still a very worthy investigation... More than the conversion itself, I'm interested in how, cartographically, we could visualize everything.

**Comment by amenity** [comment]
@alan-deanda @johnclary - I'm thinking it would be good to try this out before the mapping work session on January 8th. Sprint 40?

**Comment by alan-deanda** [comment]
@amenity , would you say this issue can be closed?

**Comment by amenity** [comment]
@alan-deanda - heck yeah. Can we leave the [demo map up on AGOL](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=434ea5ac127f41ce86448115f6187931)?

**Comment by amenity** [comment]
For posterity...
![Screen Shot 2021-01-11 at 3 11 55 PM](https://user-images.githubusercontent.com/1463708/104238977-60d19780-541f-11eb-82af-b7cbc3484650.png)
![Screen Shot 2021-01-11 at 3 11 34 PM](https://user-images.githubusercontent.com/1463708/104238984-6202c480-541f-11eb-8e50-60af62bb651f.png)
