### ISSUE TITLE
[Feature] Communications Button and Table/Page for TIA Module

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#3905]
A new button on the TIA Case Details Page, and a new page.

- New button on TIA Case Details 'Communications'
- Clicking 'Communications' button takes user to the 'Communications' page
- The page displays a Communications Table and an 'Add Communication' button
- Communications Table Columns:
- Type
- Field Values = Approval, Scope - Revision Required, General Comments, Outlook
- Date & Time
- Recipient Email
- View Email (Feature opens the email/attachment for user viewing)
- Feature that allows user to add new records to the Communications Table
- Button 'Add Communication'
- Clicking 'Add Communication' opens a form with the table column fields, allowing users to input values in each field
- The form allows user to attach the email, and maps the attachment to the 'View Email' field
- Feature that creates a record on the Communications Table whenever an email is sent via the app or by the system

**Comment by ChrispinP** [comment]
Created Add Communication button and Communication table for Reviewers. Ability to send email to all Reviewers upon submission.

Ready for initial review

**Comment by TracyLinder** [comment]
Tested w/ stakeholder, looks good.
