### ISSUE TITLE
Crash details page notes

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3916]
Ability to record notes so that other users can see important information regarding a crash record

**Comment by patrickm02L** [comment]
Add layer of information to augment the narrative. Could add news links, obituaries and additional information for context at the Traffic Fatalities Review Board. 

Would need to add a text column in the database, and a text field to the crash details page where an author could enter in new notes.

Added level of complexity if we wanted text formatting.

**Comment by patrickm02L** [comment]
The Fatality Tracking Tool #7177 will incorporate these extra layers of information.
