### ISSUE TITLE
Add pagination widget below "All Assignments" table 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3921]
When a user scrolls to the bottom of the "All Assignments" table it may appear that they have reached the end of the assignments since there is no "Next" button or pagination visible. This is especially problematic on mobile. 

**URL tested:** https://atd.knack.com/vza#sign-up/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fatd.knack.com%2Fvza%23sign-up%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://atd.knack.com/vza#sign-up/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone XR |
| Browser | Mobile_safari |
| Operating System | iOS 12.0 |
| Resolution | 828 x 1792 px |
| Screen size | 6.1 in - 2.56 x 5.54 in |
| Viewport | 414 x 896 dp |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/4ab21d6f89b3b9eea3804b5d25bfe854e41275f7/realios_iPhone_XR.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/4ab21d6f89b3b9eea3804b5d25bfe854e41275f7/realios_iPhone_XR.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fatd.knack.com%2Fvza%23sign-up%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://atd.knack.com/vza#sign-up/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by mddilley** [comment]
#### Screenshot from August 27th test instance
![Screen Shot 2020-09-11 at 3.01.29 PM.png](https://images.zenhubusercontent.com/5cfe7d078509cb6dcbaafdc3/ef2e0dcb-78d0-49c5-9077-4202f5142e4a)

**Comment by amenity** [comment]
💯, @mddilley !
