### ISSUE TITLE
Make "Cancel" icon red 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3922]
The "Cancel My Sign Up" button is an important indicator for the officers since it will help prevent them from registering multiple times for an assignment. 

Let's make the icon red — #af3c3c — so it stands out more. 

**URL tested:** https://atd.knack.com/vza#sign-up/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fatd.knack.com%2Fvza%23sign-up%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://atd.knack.com/vza#sign-up/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone XR |
| Browser | Mobile_safari |
| Operating System | iOS 12.0 |
| Resolution | 828 x 1792 px |
| Screen size | 6.1 in - 2.56 x 5.54 in |
| Viewport | 414 x 896 dp |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/3eab1e3aa2a4730101bf7627fb3f2ac1b75df70b/realios_iPhone_XR.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/3eab1e3aa2a4730101bf7627fb3f2ac1b75df70b/realios_iPhone_XR.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fatd.knack.com%2Fvza%23sign-up%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://atd.knack.com/vza#sign-up/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by mddilley** [comment]
@amenity I tested out the background color change and ran into some issues with readability. We could either adjust the red or change the text to white. Let me know what you think or if you have a different suggestions! Screenshots below.

#### Change background color (#af3c3c) only
<img width="367" alt="Screen Shot 2020-09-10 at 12 20 32 PM" src="https://user-images.githubusercontent.com/37249039/92771589-a0e51880-f360-11ea-90ed-507c7d055327.png">

#### Change background color (#af3c3c) and text (#ffffff)
<img width="367" alt="Screen Shot 2020-09-10 at 12 20 48 PM" src="https://user-images.githubusercontent.com/37249039/92771608-a5a9cc80-f360-11ea-8639-575c450e5740.png">

**Comment by amenity** [comment]
@mddilley — ooh, I'd actually meant the icon itself being red, but that background color change with white is much more eye-catching.... Is it overly-jarring, though? 

Some options

### Red icon
<img width="458" alt="Screen Shot 2020-09-10 at 1 05 11 PM" src="https://user-images.githubusercontent.com/1463708/92789730-bc581f80-f370-11ea-9663-c09247aecac3.png">
<img width="383" alt="Screen Shot 2020-09-10 at 1 04 05 PM" src="https://user-images.githubusercontent.com/1463708/92789737-be21e300-f370-11ea-9123-9e5970afc43a.png">

### Other background colors
<img width="404" alt="Screen Shot 2020-09-10 at 12 49 36 PM" src="https://user-images.githubusercontent.com/1463708/92789970-f6c1bc80-f370-11ea-977a-7649580bc3bf.png">
<img width="410" alt="Screen Shot 2020-09-10 at 12 53 17 PM" src="https://user-images.githubusercontent.com/1463708/92789974-f7f2e980-f370-11ea-9844-427495790bb0.png">

I'm still kinda partial to the red-background + white-text that you posted, though:
<img width="367" alt="Screen Shot 2020-09-10 at 12 20 48 PM" src="https://user-images.githubusercontent.com/37249039/92771608-a5a9cc80-f360-11ea-8639-575c450e5740.png">

**Comment by mddilley** [comment]
@amenity - Oh yep, I see that now about the icon color. I like the icon idea! If it becomes something that is overlooked, then we can always update. I think that it stands out enough to show that a shift taken by the current user. 👍

**Comment by amenity** [comment]
@mddilley - Cool, let's go with `color: #af3c3c` then.

**Comment by mddilley** [comment]
#### Screenshot from August 27th test instance
<img width="435" alt="Screen Shot 2020-09-11 at 3 01 09 PM" src="https://user-images.githubusercontent.com/37249039/92968164-386d6880-f440-11ea-8fb8-a43985b776a2.png">

**Comment by amenity** [comment]
Perfect, @mddilley! 🙏
