### ISSUE TITLE
Improve time tracking usability

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3923]
As @ChrispinP [noted](https://github.com/cityofaustin/atd-data-tech/issues/3741#issuecomment-689196443) while testing the officer workflow, if an officer exits the Details page of a particular shift within an assignment, the table shows that the shift is "In Progress":
<img width="1053" alt="Screen Shot 2020-09-08 at 7 03 24 PM" src="https://user-images.githubusercontent.com/1463708/92539082-0670c200-f206-11ea-846f-471842b8e985.png">

However, when they return to that shift details view, there is nothing that indicates that the shift has started. Furthermore, they can still see the "Start" button, likely to cause confusion. 

We need:
- A way for the users to see the status of an assignment in the details view
- A way to guide users to start and end each assignment once, in that sequence

The first thing that comes to mind is making a disabled button style with CSS `opacity: 40%` and text below says "Assignment started at [start timestamp]."
<img width="407" alt="Screen Shot 2020-09-08 at 7 41 34 PM" src="https://user-images.githubusercontent.com/1463708/92541346-5b630700-f20b-11ea-8e56-1ae808bc9891.png">

### Triggers & style changes

Open assignment:
- "Start Assignment" button is enabled
- "End Assignment" button is disabled

Click "Start Assignment"
- "Start Assignment" button disabled 
- Text below button "Assignment started at [start timestamp]."
- "End Assignment" button enabled

Click "End Assignment"
- "End Assignment" button disabled
- Text below button "Assignment ended at [end timestamp]."

**Comment by amenity** [comment]
Also, I'm not sure if this is for the Apps or Dev team. See also the adjustments to these buttons' CSS [here](https://github.com/cityofaustin/atd-data-tech/issues/3920).

**Comment by amenity** [comment]
Also, it would be good to show when an assignment has ended in the same way.

**Comment by amenity** [comment]
Open assignment:
- "Start Assignment" button is enabled
- "End Assignment" button is disabled

Click "Start Assignment"
- "Start Assignment" button disabled
- Text below button "Assignment started at [start timestamp]."
- "End Assignment" button enabled

Click "End Assignment"
- "End Assignment" button disabled
- Text below button "Assignment ended at [end timestamp]."

**Comment by mddilley** [comment]
@amenity @SurbhiBakshi The idea in Amenity's last comment could be added with a small bit of custom JS if needed. The data about start/end times comes for free from Knack when the view loads so code could be added to enable/disable them if needed.

```
$(document).on("knack-view-render.view_448", function (event, view, data) {
  var startTime = data.field_560;
  var endTime = data.field_561;
  // Do stuff with these values
});
```

**Comment by amenity** [comment]
@mddilley — I think that would be great. @SurbhiBakshi — thoughts?

**Comment by SurbhiBakshi** [comment]
@mddilley , @amenity - it would be really useful to see that!

**Comment by amenity** [comment]
@mddilley - updated the description to reflect what we discussed in the comments above. Would you please provide an estimate?

Thanks!

**Comment by mddilley** [comment]
These updates are now live in `test-vision-zero-in-action-27-august-2020`

### Assignment not started
<img width="521" alt="Screen Shot 2020-10-01 at 2 29 16 PM" src="https://user-images.githubusercontent.com/37249039/94854544-adeea800-03f2-11eb-9679-1c938fd87e3f.png">

### Assignment started
<img width="521" alt="Screen Shot 2020-10-01 at 2 29 44 PM" src="https://user-images.githubusercontent.com/37249039/94854548-b1822f00-03f2-11eb-9adb-6f0f301f56c9.png">

### Assignment ended
<img width="521" alt="Screen Shot 2020-10-01 at 2 29 54 PM" src="https://user-images.githubusercontent.com/37249039/94854555-b646e300-03f2-11eb-8cf7-d2278264cf37.png">

**Comment by amenity** [comment]
@mddilley this looks beautiful in my browser. I am not able to try in out in Browserstack due to what I suspect are some Knack-server performance issues:
![Screen Shot 2020-10-02 at 5 22 22 PM](https://user-images.githubusercontent.com/1463708/94974346-f762f400-04d3-11eb-992d-e3d261ab0efd.png)
#foreverhang 

@SurbhiBakshi — will you give it a lookover?

**Comment by amenity** [comment]
@SurbhiBakshi approved™️ ...
