### ISSUE TITLE
Add users to Arterial Management Notifications DL

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#3925]

**Comment by SurbhiBakshi** [comment]
Can you please add Ravi, Ricky, and Nelson to this email list

**Comment by amenity** [comment]
Signal Construction notifications. 

@SurbhiBakshi - please send @johnclary the email addresses.

**Comment by SurbhiBakshi** [comment]
Sent the email addresses to @johnclary

**Comment by SurbhiBakshi** [comment]
Added users to the DL
