### ISSUE TITLE
Update styles on time tracking buttons

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3929]
- [x] Update CSS for "Start" and "End" buttons: 
    - `background-color: #00396D;`
    - `border-radius: .2em;`
    - `padding: 10px 45px;`
    - remove `width: 20%`
- [x] Rename "Start" button to "Start Assignment"
<img width="382" alt="Screen Shot 2020-09-09 at 1 09 00 AM" src="https://user-images.githubusercontent.com/1463708/92562945-64b89780-f23c-11ea-974b-93a714004a25.png">
<img width="373" alt="Screen Shot 2020-09-09 at 1 29 48 AM" src="https://user-images.githubusercontent.com/1463708/92562974-726e1d00-f23c-11ea-9103-f3ebd4552c4d.png">

**Comment by amenity** [comment]
@mddilley - @SurbhiBakshi took a stab at implementing these styles but ran into some problems. Could you take a look at this and size it? Note, also, that this CSS is likely something we would want to change state, see #3923.

**Comment by mddilley** [comment]
#### Screenshot from August 27th test instance with these updates
<img width="435" alt="Screen Shot 2020-09-11 at 3 00 49 PM" src="https://user-images.githubusercontent.com/37249039/92968076-0cea7e00-f440-11ea-98e9-a885a09d202d.png">

**Comment by amenity** [comment]
Nice, @mddilley. 🙌 🙏

**Comment by SurbhiBakshi** [comment]
It looks great @mddilley
