### ISSUE TITLE
Project: B-Cycle Locating Planning

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#393]
## Description
Perform GIS Analysis to help determine the location of new B-Cycle to provide first and last mile connections between destinations and transit stations.

### Resources
[cityofaustin/atd-geospatial/issues/76](https://github.com/cityofaustin/atd-geospatial/issues/76)

**Comment by alan-deanda** [comment]
@johnclary no more map or support requests have come in for this project. The planners are currently using it. Should I close this project?

**Comment by johnclary** [comment]
@alan-deanda yep. please set the Milestone and Estimate that reflects when the bulk of the work was complete.

**Comment by alan-deanda** [comment]
@johnclary , I've set the milestone for Sprint 6 because the project was delivered on time (a few weeks ago, probably during Sprint 5 or 4), and choosing Sprint 5 would have made it seem like the project was delivered late.
We haven't done sprint planning formally in atd-geospatial, so let me know if I need to categorize this project differently.
Thanks!

**Comment by johnclary** [comment]
thanks @alan-deanda. if the bulk of the work was in four or five, i'll set this to sprint 5. my goal is to be able to better estimate our bandwidth for delivering projects, so I want to try to get a realistic estimate of work completed during a given sprint.
