### ISSUE TITLE
 Bulk CR3 download tool

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#3931]
Users want the ability to quickly download multiple CR3s at a single time without needed to search for and navigate to each individual crash ID page. We could add a new tool section to VZE that allows users to bulk download CR3s.

**Key Features:**
- Bulk download of CR3s per location IDs
- Bulk download of multiple CR3s per crash IDs

**Comment by patrickm02L** [comment]
Here's the [script for downloading](https://github.com/cityofaustin/atd-vz-data/tree/master/atd-toolbox/download_cr3s) the CR3s
