### ISSUE TITLE
Moped | New Project - Write query/mutation for GraphQL endpoint

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#3940]
Queries:
- [x] Get Phases (for dropdown list)
- [x] Get Stasuses (for dropdown list)
- [x] Get Fiscal Years (default to current fiscal year, others should be allowed as options)

Mutation(s):
- [x] New Project (insert a new project into the Moped projects table; insert other necessary rows based off of this)

**Comment by zappfyllc** [comment]
@lazavazav let me know if you want me to add each of the queries in the description above as their own issues or if this is appropriately sized (i.e. less than a sprint's worth of work)

**Comment by lazavazav** [comment]
I think this is a good size for one sprint.

**Comment by zappfyllc** [comment]
New Project mutation can be further refined via #4130. @lazavazav close this when you feel the tasks in the description have been completed and moved to their own queries file (maybe already done?), and when the queries have been decoupled from the "onChange" event for the inputs on New Project

**Comment by amenity** [comment]
@lazavazav @zappfyllc - can this be closed?
