### ISSUE TITLE
[RPP Back Office] Update and Re-Import Customer Spreadsheets

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#3949]
Reformat Customer Import Spreadsheets w/ notes, updated format, and catching data errors
- [x] Blue
- [x] Green
- [x] Orange
- [x] Pink
- [x] Purple
- [x] Red
- [x] Teal

Import new Customer Spreadsheets with missing or corrected data
- [ ] Blue
- [ ] Green
- [ ] Orange
- [ ] Pink
- [ ] Purple
- [ ] Red
- [ ] Teal

**Comment by ChrispinP** [comment]
Customer import spreadsheets updated for all color zones and organized on the G drive

**Comment by moorerst** [comment]
Confirmed with RPP staff that migration of historical data from the Excel spreadsheet is no longer needed.
