### ISSUE TITLE
Speed Limit Sign Change Feature Layer / Web Map Updates

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#3956]
Initial changes after meeting with TED
- Need to republish Speed Limit Sign Change Feature Layer after Nelson populates all the required fields
- Waiting to hear back from Alison regarding the Proposed Speed Limits feature layer.

Discussion with John on 9/15
- Add WORK_ORDER_URL field to the Signs Work Order layer, script will populate the link to the Work Order Details Page for each work order. It will only be visible on the read-only version that is filtering out Null Work Order Status records that have not been submitted.
- Remove Requester ID field from Work Order layer and turn on Editor Tracking instead
- Add READY_TO_SUBMIT field to Work Order layer that can be Yes or No, coded based on what polygon type is created
- Add WORK_ORDER_STATUS field to Speed Limit Signs layer
- WORK_ORDER_STATUS field on both layers will not be editable, set to a default value of Null on creation, updated by script coming from Knack.
- Will have 2 versions of each layer in the map, editing version and read-only version.
   - Edit Version - filter Work Order Status to only show Nulls
   - Read-only Version - filter Work Order Status to only show not Null values

**Comment by jaime-mckeown** [comment]
- Changing to Joel's version of the Existing-Proposed Speed Limits feature layer is a go from TED per Alison.
- Added Notes field to the Proposed Speed Limits feature layer, checked the public facing App, no affects
- Created a View Layer from the Existing-Proposed Speed Limit Feature Layer for editing
- TED will be editing the Proposed feature layer, Existing feature layer will be added to map as a reference (read-only)

**Comment by jaime-mckeown** [comment]
Updated to Desktop and Collector App Documentation pages on GitBook to account for now adding Signs Work Orders as "Not ready to submit" or "Ready to Submit". The Work Order Status will be populated by Knack and only displayed in the read-only versions of each layer.

**Comment by jaime-mckeown** [comment]
Went over all the changes with John, everything is good to go for tomorrow's training.

**Comment by jaime-mckeown** [comment]
- Added requested fields for Knack.
- Re-published feature layer in State Plane as it was in Web Mercator. Trying to find the nearest street segment ID will not work when content is in different coordinate systems.

**Comment by jaime-mckeown** [comment]
- Turned off Proposed / Existing Speed Limit Layers by default
- Turned off Editor Tracking fields on Editable layers
- Added Domains and Re-symbolized the Signs and Work Order layers as the fields in Knack are in all Caps.

**Comment by jaime-mckeown** [comment]
- [ ] Create a filter to show features based on editor. I won't be able to create filters by user until all users have created a Sign and a Work Order.

**Comment by johnclary** [comment]
@jaime-mckeown go ahead and add the requester name field back in. thanks!

**Comment by jaime-mckeown** [comment]
- Speed Limit Sign Type: add details to better name the choices in the drop down
- Custom Sign Field: sounds like its not needed
- Add City of Austin field: Yes or No, we can filter out the No's
- They need the ability to delete, make a backup copy in case lines are accidentally deleted (Allison to setup a discussion with Joel to talk about the ability to edit current and proposed speed limit lines.
- Remove Knack fields from the Editor version since they are currently blank. Remove Nearest Segment as well, coded in knack.
- Change Requester_Work_Order_ID field to Requester Name (drop down of names)
- Add Requester ID: need to ask John what this field is going to be calculated with...
- Currently TED generates their own work order numbers. Discussion on whether or not they keep them as well as knack work order ID.
- Description field: rename to Instructions
- Still going to keep work order ID.
- John mentioned that we were going to initially assign the work orders to On Hold.

**Comment by jaime-mckeown** [comment]
Notes from John:

> good morning. here are the todo's i captured at our meeting with Alison on friday:
> - Rename Current Speed Limit to "Removal Sign Speed Limit"
> - Rename Future Speed Limit to "Install Sign Speed Limit
> - Nix "Custom Sign" text field
> - Rename "Requester ID" to "Requester Name"
> - Add a "Requester Work Order ID" text field
> - Add the "DIGTESS Status" back. I believe the choices were "Needed", "Not Needed", "Compelete"
> - Rename "Description" to "Instructions"
> - Add a text field called "Location"
> - Update the Sign Types to include a text description of the special 25 x 54" sign.
> 
> we also agreed that TED will use the "Ready to Submit" field to prioritize their work orders with the Signs & Markings. Once the work order is "ready to submit" it will be sent to Signs and Markings. When Signs & Markings is ready, they will notify TED via email that the DIGTESS needs to be completed, and TED will update the work order in AGOL accordingly
> 
> I'll setup follow up meetings. i think we need one with the rest of the TED area engineers and another with Christina and Jesse.

**Comment by alan-deanda** [comment]
@andrewshensky do you think we still need this issue?

**Comment by andrewshensky** [comment]
@alan-deanda I think this one is pretty out dated at this point. I know there have been additional changes to this data and much of it has been repurposed to capture other speed limit related data. I will go ahead and close this issue.
