### ISSUE TITLE
Signal Request Lookup map is not shared publicly 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3958]
This app should be available without a login: https://austin.maps.arcgis.com/home/item.html?id=7ee6d705358a443eae77e6bab54df34d

We embed this in the Data Tracker to identify street segments and lat/lon, and that iframe is broken without this being shared publicly.

**Comment by jaime-mckeown** [comment]
The TRANSPORTATION_environmental_justice feature layer is not shared. Submitted a CTM request to have the sharing updated ASAP.

**Comment by jaime-mckeown** [comment]
Ben updated the sharing on the env. justice layer, the App opens without a login again.
