### ISSUE TITLE
[RPP Back Office] Application submitted without required documentation 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#3959]
I did not think a New RPP application could be submitted without the Required Documents attached
Application 2020-1207 does not have any required documents attached but was successfully submitted. 
Can you review if there are checks in place for this scenario?

**Comment by ChrispinP** [comment]
So those required document fields did update to trigger the document status to update to 'Submitted' either from actually being uploaded or the fields just changing somehow. 

One scenario rules I saw that could have made this happen:
![image](https://user-images.githubusercontent.com/67915167/93650315-cbc01400-f9d3-11ea-97a8-20db987762df.png)
With this rule its possible the applicant was able to skip the attached documents page altogether. Is this rule correct?

**Comment by moorerst** [comment]
I think it is correct you can just purchase Day Passes and when purchasing Day Passes only the documents are not required. 
For a test I started a application and selected 2 Day Passes only - the Required Documents did not display. 
I then edited my application and added 2 Hang Tags which should require documents but the Required Documents view did not display.

**Comment by ChrispinP** [comment]
I added a counter-logic argument for if Day Passes are set to 0 since no required documents are needed. I tested the 2 Hang Tags scenario you had mentioned and looks to be working. There could be another selection or rule affecting this but I dont think so from what I see.

![image](https://user-images.githubusercontent.com/67915167/94460814-e38b5b00-017e-11eb-8b1e-afebaf3e78ea.png)

**Comment by moorerst** [comment]
@ChrispinP I tested this scenario and it does seem to work correctly. Thanks

**Comment by ChrispinP** [comment]
updated this logic for the new application so that if either license plate details or resident decals are selected, it will direct you to the required documents page
