### ISSUE TITLE
Add information on assignment type (VZA vs Signals) to Sign Up page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3964]
Officers should be able to distinguish signals shifts from other shifts since they will be performing different activities on these shifts. 

It should be clear that a shift is a signals shift throughout the app:
- During sign up, so they know what they're getting into...
- During the shift itself, since they will be performing different activities

**Comment by SurbhiBakshi** [comment]
Set up a Teams meeting with @mddilley on Tuesday, December 29th to see if adding these fields will affect the page.

**Comment by SurbhiBakshi** [comment]
spoke to @mddilley - he will add the Assignment Type field to the Available Assignments table.

**Comment by mddilley** [comment]
@SurbhiBakshi @amenity Is there a specific position that the Assignment Type should be placed? I can drop it in any order with existing columns.

<img width="939" alt="Screen Shot 2020-12-30 at 1 44 31 PM" src="https://user-images.githubusercontent.com/37249039/103377502-30940b80-4aa5-11eb-9163-cbb3be9991e7.png">

**Comment by SurbhiBakshi** [comment]
@mddilley - I don't have a preference.

**Comment by SurbhiBakshi** [comment]
Hi @mddilley - I put in a text formula field for Assignment Type in the `officer_assignment` object which pulls the information from the `assignment' object. It's taking a bit of time to calculate, will let you know once it's done.

**Comment by SurbhiBakshi** [comment]
- Realized when I was testing how the Assignment Type field was passing through the processes and showing up on the Sign Up page that the two types of assignment could get rolled into one Shift. 
- This could be misleading if the officer signs up and then realizes that there are two types of assignment, especially if the location and time don't work with the other assignment. 

 ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/d484df69-2d12-4490-b6f5-db99c4da9c93)


![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/331aced3-7364-4ee4-985f-b90798aacf92)

**Comment by SurbhiBakshi** [comment]
![Screen Shot 2021-01-04 at 12.18.08 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/0f976b05-bb72-4600-be47-f99c25f5a344)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/331aced3-7364-4ee4-985f-b90798aacf92)

**Comment by amenity** [comment]
@SurbhiBakshi - I am thinking that we should just ask Lewis and Billy to keep one type for all assignments on a shift.

**Comment by amenity** [comment]
@mddilley - sorry I missed your question about placement! If it's not too late, I think the far right probably makes the most sense.

**Comment by SurbhiBakshi** [comment]
@amenity - The assignments Lewis and Billy create will default to VZ and SE assignment types respectively based on the forms - `Add VZ assignment` and `Add SE Assignment`. they use. But since the other fields are common - Date, Shift, Team, the two assignments get rolled up together on the Sign Up page.

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/8a016bb2-3bd2-4bcc-bd24-95a74f92bd33)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/0d51584b-3a57-4b1d-8a4f-acc6b7f2c62f)

**Comment by SurbhiBakshi** [comment]
Moved the Assignment Type to second place in the label string, and removed an extra hyphen.

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/0a041a26-47d7-47ca-bf78-bf9eb745a0c0)

**Comment by SurbhiBakshi** [comment]
@mddilley @amenity - tried adding the Assignment Type to the Shift Label for a few test records and it works to separate the shifts by  assignment type. 
@amenity - @mddilley and I were wondering if we still need a field to show Assignment Type?

**Comment by amenity** [comment]
@SurbhiBakshi @mddilley - heck no, this looks great! 😍  No extra field necessary. 

Can we change "Signal Engineer" to "Arterial Management"?

**Comment by amenity** [comment]
One more nit-picky request: Could we update the Scheduler button text  to "Add Vision Zero Assignment" and "Add Arterial Management Assignment"?

**Comment by SurbhiBakshi** [comment]
Renamed Signal Assignment to Arterial Management Assignment.

- [ ] Renamed Menu link
- [ ] Renamed form heading
- [ ] Renamed slug
- [ ] Renamed option in Assignment Type
- [ ] Changed record rules for Create Assignment form to Arterial Management.
- [ ] Changed Edit form

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/ee3bd4a9-227e-4349-804d-225eb70c292c)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/c5aea57a-1f67-496c-9859-e3a7f5d466e8)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/870615fb-81f5-4140-a0f2-6f93d941d223)

**Comment by SurbhiBakshi** [comment]
@amenity - renamed Signal Assignment to Arterial Management Assignment.

**Comment by amenity** [comment]
@SurbhiBakshi - Ready for me to test this out in production?

**Comment by SurbhiBakshi** [comment]
@amenity - yes, this is ready to be tested.

**Comment by amenity** [comment]
Beautiful, y'all!
