### ISSUE TITLE
Setup custom domain for Knack Explorer

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#3966]
Currently the [Knack Explorer](https://github.com/cityofaustin/knack-explorer) lives at a [netlify domain](http://knack-explorer.netlify.app/). We should route this through our own custom domain so that we're not beholden to using Netlify for this app. I propose `knack-explorer.austinmobility.io`.

**Comment by johnclary** [comment]
@mddilley @mateoclarke could one of y'all take care of this in Sprint 34, and, if so, would you assign yourself?

**Comment by mddilley** [comment]
@johnclary This is now complete, a new CNAME has been added in Route 53 for `austinmobiility.io` and the settings in Netlify were updated as needed. The SSL cert was provided by Netlify, but we could provision one through AWS if needed.

Knack Explorer can now be accessed from https://knack-explorer.austinmobility.io/

**Comment by johnclary** [comment]
thanks @mddilley! Does Netlify manage that cert for us or do we need to track the renewal?

**Comment by mddilley** [comment]
@johnclary Netlify renews the cert automatically ✅
