### ISSUE TITLE
Add "Past Assignments" page for Officer reference

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3967]
While [training the VZA 2.0 pilot officers](https://docs.google.com/document/d/1nPgvr7cG97ZJy1AFEs2mmDO8A41s4oZUCfj0AoAcK1s/edit#) we learned that sometimes they are not paid for shifts they have worked. Currently, they have to search through emails to collect the relevant details and correspondence.  

It would be very helpful for them to have a log of all the shifts they've worked inside the app.

**Comment by amenity** [comment]
@SurbhiBakshi - do you have anything to add here? It occurs to me that it would be cool if Randy marked shifts as "Invoiced" as part of his process and the officers could see that data on their end.

**Comment by amenity** [comment]
@SurbhiBakshi I think you covered this already, right?

**Comment by SurbhiBakshi** [comment]
@amenity - yes, this is done
