### ISSUE TITLE
Document DTS development workflow process 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3970]
@mateoclarke is going to document this, @lazavazav will review.

**Comment by mateoclarke** [comment]
@lazavazav @amenity @zappfyllc, these docs are ready for your review:
https://app.gitbook.com/@atd-dts/s/moped-technical-docs/dev-guides/dts-development-workflow-process

**Comment by amenity** [comment]
LGTM. 👍📚

**Comment by amenity** [comment]
Leslie and JD approved!
