### ISSUE TITLE
Discuss and document Moped information architecture

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3971]
- Material Design layout
    - [Navigation drawer](https://material.io/components/navigation-drawer) — nested main menu w various design/hierarchy options (groups, dividers, icons)
    - [Apps bar](url) 
- [Moped UI Views](https://docs.google.com/spreadsheets/d/1gNCz63qFpztiuL_JK4aPNnicjCglmATOW1dbpU0wxWk/edit#gid=1731506475)
- [MatX Dashboard](https://matx-react.ui-lib.com/dashboard/analytics)

**Comment by zappfyllc** [comment]
[Rough draft of userflow](https://miro.com/app/board/o9J_knyFAmc=/)

<img width="1074" alt="userflow" src="https://user-images.githubusercontent.com/34947604/93807816-2c8c5e00-fc19-11ea-90d1-8f07aa457f1b.png">

**Comment by zappfyllc** [comment]
Follow-up item from discussion:

- Create navigation/page structure and clean up template to reflect Moped initial scope (move material UI docs to a dev branch?)
