### ISSUE TITLE
Project Staffing | Build React frontend for "Project team" table 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3979]

**Comment by zappfyllc** [comment]
Per #3941, we have the Material UI table working with Autocomplete fields setting the state via a custom hook (to facilitate the stepper component workflow), but there are some bugs/kinks we're still working out. Once #3941 is done, we'll open up a PR and move this and #3941 to Review/QA

**Comment by lazavazav** [comment]
This issue can be closed as it is done and was the precursor to #3980 that is closed.
