### ISSUE TITLE
Project Staffing | Write GraphQL queries

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#3980]
Queries:
- [x] Get Project Roles (for dropdown list to present to user)
- [x] Get COA Staff (for dropdown list to present to user)

Mutation(s):
- [ ] New Project Personnel (insert new project staff into moped_proj_personnel table)

**Comment by lazavazav** [comment]
I would give this issue a 3 for estimate of time to complete.

**Comment by zappfyllc** [comment]
@lazavazav when we move over to the new template and new Apollo client configuration, we will need to rewrite the query to conform to @sergiogcx's user table. I think this only will impact the COA Staff query above.

**Comment by lazavazav** [comment]
coa_staff_queries were rewritten to conform to new endpoint and new column name of moped_users.
