### ISSUE TITLE
Convert KMZ to AGOL feature service

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#3987]

**Comment by SurbhiBakshi** [comment]
hi @jaime-mckeown, please add an estimate and thanks again!

**Comment by jaime-mckeown** [comment]
I had already created an Issue for this: https://github.com/cityofaustin/atd-data-tech/issues/3985

**Comment by jaime-mckeown** [comment]
Feature Layer Published.
I have created a new directory for SD 2023 GIS Requests: G:\ATD\ATD_GIS\SD_2023
