### ISSUE TITLE
VZD Bug | Crash fatality count and severity ID mismatch

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#3990]
Ex" https://visionzero.austin.gov/editor/#/crashes/16558108

From Xavier:
The crash above is showing as a possible injury as the original severity. The original CR3 is a fatal crash and it is showing as a fatality in the original submission through Brazos.
 
I have updated the VZE to a Fatal (Non-ATD), but there is a concern that there are other crashes that have incorrect severity ids and that the CRIS death_cnt won’t be displayed accurately.

**Comment by mateoclarke** [comment]
For this specific crash, it definitely seems like a coding error between APD and CRIS.

In CRIS Search, you can see the CR3 PDF has the pedestrian marked as injury severity `K`. But in their interface you also see the crash data coded as non fatal and the highest injury severity as "Possible Injury".

![Screen Shot 2020-09-28 at 3.57.07 PM.jpg](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/f44c25d5-3f03-493d-8775-3a9950a922a7)

![Screen Shot 2020-09-28 at 3.48.23 PM.jpg](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/f3e58640-4dc4-44ea-9ecc-67131b029732)

![Screen Shot 2020-09-28 at 3.58.01 PM.jpg](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/36d61de1-b631-44cc-a3b5-3d39ea5d06fb)

So, I'm not sure what we can do to resolve this type of miscoding, in the CRS PDF to crash attribute setting. Maybe we should contact CRIS reps?

Going to see if I can run a query of crashes where fatality counts mismatch crash injury severity.

**Comment by JaceDeloney** [comment]
This was manually updated by Mateo last week. Closing this out.

**Comment by mateoclarke** [comment]
Thanks Jace!
