### ISSUE TITLE
Determine Active vs Expired permit status based on date

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4006]
Currently, users have to select if a permit is expired or active during the Add a New Permit form that they fill out when creating a new permit. The ideal experience would be for the system to determine status based on the date range. 

Requirements:
- Remove status from the Add a New Permit form
- Determine status based on data range
- If the Expiration Date is after the current date, the permit should be `active`
- If the Expiration Date is before the current date, the permit should be `expired`
- The system should automatically move records from the Active Permits table to the Expired Permits table

**Comment by SurbhiBakshi** [comment]
@JaceDeloney - This is done, so you can test the functionality.

- I have set a conditional on the Status field so any permit with a Permit Expiration Date before today to a Status of Expired and any permit with a Permit Expiration Date of today and after will be set to a Status of Active. 
- The tables filter permits based on the Status, so any Active status permit will show up in the Active table, same for Expired. Any permit with a Deleted status will not show up in either. 
- I took away the Status entry in the 'Add a New Permit' form. Do you want to retain it in the Edit Permit form? I am leaving it there so it can be used to set the permit to a 'Deleted' Status so the permit no longer appears in the Active and Expired tables.

**Comment by SurbhiBakshi** [comment]
@JaceDeloney - wondering if a Delete icon in the record makes more sense than putting the Delete Status in the Edit Permit.

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/ee3f8624-dedd-4083-ad65-3a7227b2bf38)

**Comment by JaceDeloney** [comment]
Met with @SurbhiBakshi on this. Decisions:
- Remove the status field in the Add a new permit form
- Add a delete icon on the table
- Remove the status field in the edit permit form
