### ISSUE TITLE
Write a Job Description

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#401]

**Comment by amenity** [comment]
@johnclary @mateoclarke - will probably start with [ODD's PM job description](https://github.com/cityofaustin/odd/blob/master/_jobs/positions/__agile-project-manager.md). Anything in particular you'd like me to add/revise?

**Comment by amenity** [comment]
[Done](https://docs.google.com/document/d/1KsuRBsV3YojlVYZlfRljwp0dj0Tlmjm5FsOpSJ08Gwk/edit#).
