### ISSUE TITLE
[RPP Back Office] Modify RPP Rates

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4010]
**Effective Oct 1, 2020** the RPP Rates will change for Hang Tags, Decal and Day Passes. From the attached spreadsheet there is also a increase in price for each additional permit 
[RPP and CVLZ rates.xlsx](https://github.com/cityofaustin/atd-data-tech/files/5269458/RPP.and.CVLZ.rates.xlsx)

- [x] RPP Backend Permit cost will need to be updated
- [x] Get Started/Learn More About page will need to be updated

**Comment by moorerst** [comment]
Since this is a time sensitive issue Chrispin and I met to review RPP Permit rate changes. Also discussed other design ideas he has based on his review of the data during the migration process. Will create a new issue for those ideas which need to be reviewed with RPP Staff. 
Meeting scheduled for Monday 9/28 with RPP team to discuss the Permit Rate changes

**Comment by moorerst** [comment]
Notes from meeting with RPP team
Residents can now purchase up to 6 permits per address, first come first serve. Mueller residents are still limited to 2 permits per the HOA
Permit cost increases with each permit purchased with the largest increase for permit # 5 and 6
Residents can purchase unlimited Day Passes

- [ ] New status may be required for applications that have been reviewed and need to be processed by the Cashier (Ready for Payment)

- [ ] Add a price change notification on the Home page

**Comment by moorerst** [comment]
@ChrispinP here are several additional update request from Steve
From the RPP Home Page

- [ ] Change language to:  UPDATE: As part of Austin Transportation’s concerted efforts to stop the spread of COVID-19, we have closed our PARKING AND MOBILITY SERVICES PERMITTING OFFICE to the public (1501 TOOMEY RD. ) and are not providing walk-in service at this time. Any in person requests are being done by appointment only. Please see below for additional details.   

- [ ] DELETE top bullet point ‘New Residential Parking Permits and Renewal Parking permits are issued only on Wednesdays….”

- [ ] Change “Limited permits are being issued…’ to read  “Permits are still being issued by regular mail unless otherwise requested, with payment available by phone.” 

For the RATES UPDATES

- [ ] Can we remove the ‘Special Circumstances’ language. I feel like it will open the door to all types of requests and issues with residents.

**Comment by ChrispinP** [comment]
All customer facing information pages updated.

Pending Zone # add to the application details page

**Comment by moorerst** [comment]
From Get Started/Start Application/Permit Information the information icon next to Number of Visitor Day Passes is directing back to the Home page not to Day Pass Cost page

**Comment by ChrispinP** [comment]
Corrected the cost links and the information icon link.

**Comment by ChrispinP** [comment]
All listed issues completed, complete
