### ISSUE TITLE
VZD ETL | Make sure ETLs don't fail silently

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#4011]
When CRIS updated to version 21.0, one breaking change was in the format of emails that are stored in S3 that we have to parse using a regex pattern to find a download URL with a token.

When the format changed, this was failing silently and breaking the whole ETL request, download, and insert to Hasura process.

We should update this `process_cris_request_download` code so it doesn't fail silently again when that URL isn't successfully parsed.
https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/app/process_cris_request_download.py#L84-L105

We should also examine the rest of the ETL process for other places where the code fails silently.

**Comment by patrickm02L** [comment]
Would like to take the concept of this idea and attach it to an adjacent issue. 

[#5973](https://github.com/cityofaustin/atd-data-tech/issues/4011) Daily report of new records added or updated in VZD.

**Comment by patrickm02L** [comment]
Updated version of this Issue #10228. 

Considering this a duplicate.
