### ISSUE TITLE
Moped | Implement API functionality 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4014]
Scaffold the API and ensure that it is protected by Cognito so that only authenticated users can access it. 

- Adds users
- List users

The whole CRUD....

Per discussion at Sprint Retro today, this will include documentation 🙌 📚

Alpha permissions documented [here](https://docs.google.com/spreadsheets/d/1gNCz63qFpztiuL_JK4aPNnicjCglmATOW1dbpU0wxWk/edit#gid=351804243).

**Comment by amenity** [comment]
Duplicate of #4000

**Comment by amenity** [comment]
@sergiogcx and @mddilley reviewed this and have the skeleton worked out, will flesh out this week.

**Comment by mddilley** [comment]
Update as of 10/7: Get users, list users, and create user routes are implemented. The create user route needs to be extended to encrypt and set user claims in DynamoDB and to set a permanent password. I also need to consider how payloads from the frontend should to be formatted.

Outstanding work:
- [ ] Encrypt and set user claims in DynamoDB on account creation and set temp password as permanent
- [ ] Update user (set encrypted claims if changed)
- [ ] Delete user

**Comment by amenity** [comment]
Somehow I overlooked discussing this one individually in Sprint Planning, @mddilley — sorry! Thanks for the update.

**Comment by mddilley** [comment]
Update for 10/12: Get users, list users, create user, update user, and delete user routes are implemented. The user temporary password, if valid, is now set as permanent during the account creation process as well as the user's email verification. 

Some error handling has been added, but I see developing the front end as an important step in identifying important errors going forward. Documentation has also been started in Confluence.

Next steps:
- [ ] Complete documentation
- [ ] Create another issue to add tests coverage to the API

**Comment by amenity** [comment]
🙌
