### ISSUE TITLE
Ensure comprehensive cost values are being derived from ATD death count

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4017]
Lewis found [a crash id](https://visionzero.austin.gov/editor/#/crashes/14747769) that apparently isn't using the correct values for comprehensive cost, economic cost, and speed management points. The correct values per ATD fatality (person count) should be:
- $2,829,000 for comp cost
- $1,679,600 for economic cost
- 10 points for speed management

We need to determine what is causing the issue with this specific crash ID, and then determine if this issue is affecting other crashes as well.

**Comment by tylerwhitson** [comment]
@JaceDeloney, investigating this with help from @sergiogcx. I think the values per fatality are correct in VZE, so the problem may lie elsewhere.

If you're able to provide me with the correct totals we should be displaying, I may be able to figure out where the discrepancy is coming from and how to solve it.

Should est comp cost take into account unknown injury count? Prod does not currently factor that in.

**Comment by tylerwhitson** [comment]
Current triggers in prod:

    NEW.est_comp_cost = (0
       + (NEW.apd_confirmed_death_count * (estCompCostList[2]))
       + (NEW.sus_serious_injry_cnt * (estCompCostList[3]))
       + (NEW.nonincap_injry_cnt * (estCompCostList[4]))
       + (NEW.poss_injry_cnt * (estCompCostList[5]))
       + (NEW.non_injry_cnt * (estCompCostList[6]))
   )::decimal(10,2);

    NEW.est_econ_cost = (0
       + (NEW.apd_confirmed_death_count * (estCompEconList[2]))
       + (NEW.sus_serious_injry_cnt * (estCompEconList[3]))
       + (NEW.nonincap_injry_cnt * (estCompEconList[4]))
       + (NEW.poss_injry_cnt * (estCompEconList[5]))
       + (NEW.non_injry_cnt * (estCompEconList[6]))
   )::decimal(10,2);

	NEW.speed_mgmt_points = (0
		+ (NEW.apd_confirmed_death_count * (speedMgmtList [2]))
        + (NEW.sus_serious_injry_cnt * (speedMgmtList [3]))
        + (NEW.nonincap_injry_cnt * (speedMgmtList [4]))
        + (NEW.poss_injry_cnt * (speedMgmtList [5]))
        + (NEW.non_injry_cnt * (speedMgmtList [6]))
    )::decimal (10,2);

**Comment by JaceDeloney** [comment]
Action items from sprint review:
- [ ] change to ATD confirmed
- [ ] Add unknown injury severity category

**Comment by tylerwhitson** [comment]
Unknown injury should be counted at $51,000 per person count

**Comment by JaceDeloney** [comment]
<img width="739" alt="Screen Shot 2020-10-06 at 11 05 41 AM" src="https://user-images.githubusercontent.com/10567316/95227608-ec55df80-07c3-11eb-8c86-32cd847226dd.png">

**Comment by sergiogcx** [comment]
This is the PR associated to this issue: https://github.com/cityofaustin/atd-vz-data/pull/938
