### ISSUE TITLE
Hosting Vision Zero Coordination Tool

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4020]
Frank has created a dashboard that helps the VZ Team coordinate projects. The VZ Team has asked if we could host this tool moving forward, as it is currently on Frank's home server.

**Current setup:**
Housed on a t3a.medium EC2 instance running Ubuntu Focal 20.04, which provides two CPU cores and 4 GB of RAM and which it is sharing with handful of other small applications. The app is comprised of a docker stack which stands up a PostgreSQL DB server, an Apache webserver, and a Martin PostGIS-to-protobuffer vector tile server. All this to say, the application is inherently multithreaded and becomes more performant based on the number of CPU cores available to it, but it is capable of being run on a relatively slim server.

**Next Steps:**
- [x] Decide if it makes sense for us to host this tool
- [x] Outline next steps needed to begin the process of migrating the VZ Coordination tool to DTS servers

**Comment by sergiogcx** [comment]
Frank and I will be coordinating on Monday (at 10am) to deploy and host the stack on our AWS account.

**Comment by sergiogcx** [comment]
As a side note, it appears Mateo and Mike had a screenshare with Frank and they spun up an AWS EC2 instance (server) called `atd-vz-coordination-tool`, and they gave him access. The server we are going to deploy will be hosted in AWS Lightsail (a similar service to EC2), and will require to remove any old instances, including atd-vz-coordination-tool.

**Comment by sergiogcx** [comment]
Frank created the resources, closing this issue.
