### ISSUE TITLE
Troubleshoot Craig Q. login issues

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4021]
Craig is part of the VZA 2.0 Pilot and is having issues logging in to the app. I've walked him through it over the phone and exchanged emails for a while, but we haven't solved it. 

@SurbhiBakshi — it seems like it may be an actual bug with the COACD authentication, as he's getting this error:
![thumbnail_Image](https://user-images.githubusercontent.com/1463708/94302747-53f16c80-ff32-11ea-90a5-f2d915ec081e.jpg)

Can you reach out to him to troubleshoot, please?

**Comment by SurbhiBakshi** [comment]
Scheduled a meeting with Craig to screenshare if needed on Wed, Oct 30th.

**Comment by SurbhiBakshi** [comment]
Rescheduled meeting for Thursday - Oct 1st after waiting for Craig on Wed Sept 30th. 
Also messaged him on Teams to see if the time works for him. I have not heard back.

**Comment by amenity** [comment]
Craig reported that this was user error — seems like a couple of misspellings in his email address (he'd created several accounts) were causing issues.
