### ISSUE TITLE
UC Data Workbook Doc Update (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4022]
### Need to replace existing data workbook doc on the UC folder with updated doc. 
- Tracy has the updated doc 

**Jaclyn wants to test this in Test before it goes to Prod.**

**Comment by TracyLinder** [comment]
@Nadin-Nader let's talk about this today during our 2pm meeting.

**Comment by TracyLinder** [comment]
\\Coacd.org\dfs\Amanda\docs\Dev\Templates

**Comment by TracyLinder** [comment]
### Covo w/ Nate Notes:

- Doc Name: UC - AULCC Data Workbook
- Per Nate, this does not need to go through DevOps process
- Asking Jaclyn to confirm we have the correct doc to replace it with
    - Doc is [here](https://drive.google.com/file/d/1T-WU0ZVtKGuTug0o5Cwj65qiY-BNyp-f/view?usp=sharing)

**Comment by TracyLinder** [comment]
@Nadin-Nader I'm putting this on-deck for you; pending confirmation from Jaclyn

**Comment by TracyLinder** [comment]
@Nadin-Nader please follow up w/ stakeholder.

**Comment by Nadin-Nader** [comment]
Went to \\coacd.org\dfs\amanda\docs\DEV\templates\UC - AULCC Data Workbook.dot and replaced the file with the new file provided by Jaclyn. I sent her an email asking for her to test it on TEST and if all is well i will try make the change on PROD. If im not allowed to, i will send to CTM to replace the file.

**Comment by Nadin-Nader** [comment]
The file Jaclyn sent is creating a file size 300kb larger and is not right. She is going to update it and send me the new one.

Response from Jaclyn:

It looked fine in TEST but the file is now 3Xs the size. It used to be 300KB and now it’s over 1MB and won’t save when I edit the document the way a customer would. This size won’t work because I have to send out multiple workbooks in our weekly email and I know I’ll reach the email attachment size limit. I’ll have to take out the check boxes and resend you the document. Sorry about that. 

Jaclyn Lozano | 1501 Toomey Rd. Austin,TX 78704 | Jaclyn.Lozano@AustinTexas.gov | 512 974 2412


## **Status:**
Waiting on Jaclyn to send new file

**Comment by TracyLinder** [comment]
**Status:** In PROD, pending final confirmation from Jaclyn.

**Comment by Nadin-Nader** [comment]
Had Robert change the path in PROD as well as the file extension. 

Waiting on Jaclyn to test again

**Comment by Nadin-Nader** [comment]
Sent another email to Jaclyn asking her to test the changes made by Robert:

From: Nader, Nadin 
Sent: Wednesday, November 18, 2020 10:23 AM
To: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>; Linder, Tracy <Tracy.Linder@austintexas.gov>
Subject: RE: Need Data Workbook doc to be updated

> Hi Jaclyn,
> 
> Hey just checking to see if it is working on PROD now since Robert made a change. Please let me know as soon as you can so I can either continue troubleshooting/making changes or close the request.
> 
> From: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov> 
> Sent: Monday, November 16, 2020 1:14 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>; Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: Need Data Workbook doc to be updated
> 
> I’m still getting the same error in PROD
>  
> 
> Jaclyn Lozano | 1501 Toomey Rd. Austin,TX 78704 | Jaclyn.Lozano@AustinTexas.gov | 512 974 2412

**Comment by Nadin-Nader** [comment]
Received email from Jaclyn stating the doc works but the watermark is blocking the document. I sent her instructions from Google on how to take the watermark off and that i would close the issue.

> From: Nader, Nadin 
> Sent: Wednesday, November 18, 2020 2:52 PM
> To: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>; Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: Need Data Workbook doc to be updated
> 
> Jaclyn,
> 
> Glad it is working. I will go ahead and close the request now.
> 
> To take the watermark off, I found the following instructions:
> 
> Click on “New” > “File upload”, select a PDF document and then upload it. Once done, you can check the uploaded file on your Drive, then right click to open it with “Google Docs”. Afterwards, your watermark will be removed automatically. To save it, go to “File” and click “Download as” and then choose “PDF document
> 
> Let me know if this helps.
> 
> From: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov> 
> Sent: Wednesday, November 18, 2020 12:49 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>; Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: Need Data Workbook doc to be updated
> 
> Nadin, 
> 
> I have received feedback from a customer stating that the City of Austin watermark is blocking the document. This customer is using Google Docs. Do you know how to remove the watermark in Google Docs?
> 
> Other than that, the document works fine in PROD. 
> 
> Jaclyn Lozano | Jaclyn.Lozano@AustinTexas.gov | 512 974 2412
>
