### ISSUE TITLE
UC - Master Comment Report - Macro Not Working

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4023]
### UC Master Comment Doc Bug - Macro Error

**Stakeholder:** Jaclyn & Isiah 

Reproduce this bug:
1. Generate UC Master Comment Doc
2. Click 'Build Doc' smiley face macro
3. Error window populates

![image](https://user-images.githubusercontent.com/49930868/94304891-ef381100-ff35-11ea-8f2c-98fe1811898c.png)

**Comment by TracyLinder** [comment]
@licarir this is a new bug that I'd like you to work on please. Take a look and let me know if there are any questions. Thanks!

**Comment by licarir** [comment]
@TracyLinder this probably has to do with the same issue as before regarding the Active Directory groups. Has Jaclyn tried since I added her to the AMANDA Docs Access group?

**Comment by licarir** [comment]
I worked with Anu Mahindrakar on Tango to get this completed. It made it to PROD but the DBAs ran the incorrect script. It should be corrected and work today. Awaiting redeploy.

**Comment by licarir** [comment]
@TracyLinder This has been fixed and is working on PROD per Jaclyn. She was added to an active directory group, LDRWM.
