### ISSUE TITLE
Temp Valet Application Fee - Add Post Payment Feature

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4025]
### As the system, I need to add the Temp Valet Application fee to the Insert + Run Procedure on the RW folder. 

**Stakeholders:** Paloma, Kim
**DTS Manager:** Tracy

**Acceptance Criteria:**
- Applies to RW with Work type Temporary Valet Permit
- Applies to folders submitted via Portal
- When customer clicks 'Submit' the system should:
    - Insert application fee (83494) , tech surcharge (50174) & bill
    - Update folder status to 'Pending Payment'
    - Portal should inform the customer of fee that must be paid
- After the bill has been paid the system will update the folder status to 'Internet Pending'

**Comment by TracyLinder** [comment]
**User story has been added.**

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/c37e26d0-f23a-4cf7-a03e-3bf823991fc7)

**Comment by TracyLinder** [comment]
**Update**
- I'm removing this from the FY22 fee project because it's not MVP
- The AC for this was written over 9 months ago. I think we should revisit & do another round of scoping/discovery. 
- Moving this to Needs Scoping

**Comment by vschandramouli** [comment]
Updated AC. Moving to Backlog.

**Comment by TracyLinder** [comment]
This needs to be configured in V7. Putting in the backlog until after V7 is live.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in Progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - It is found that these changes are already in V6 PROD and also V7 TEST. And also found that these changes are already implemented as per the ATD Card#8278 https://github.com/cityofaustin/atd-data-tech/issues/8278 by Subha. Please do let me know whether this can be closed or any other issues that need attention now.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan you are correct. I will close this issue. Thank you!
