### ISSUE TITLE
Automate RW-Parking (Load/Unload) Approval Fees

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4026]
### As a ROW Permit Analyst, I want the system to insert the correct approval fees on the RW Parking Spaces (Load/Unload) folder

**Stakeholders:** Paloma, Kim
**DTS Manager:** TBD

**Acceptance Criteria:**
- Info field 'Number of after hours of service' (Info code 75947) should be removed from any RW folder (Currently exists, needs to be removed)
- Users should be able to see a new info field 'Rate if metered (in $ per parking meter)' (No infocode exists, needs to be added) in RW folders of subtype Parking Spaces and worktype Load/Unload
- System should insert the Parking Space Permit Fee (50170) when 'Approved' attempt is made in Parking Parking Review Process (50662) in RW folder of subtype Parking Spaces and worktype Load/Unload 
- System should also create a bill when the Parking Space Permit Fee (50170) is inserted in Right of Way folder of subtype Parking Spaces (Fee code exists, logic needs to be updated)
- The amount for Parking Space Permit Fee should be calculated as follows:
Metered Fee = Value in Info Rate if metered (in $ per parking meter)   **X**   Value in 'Number of Days' Info field (Info Code 75390)  **X**   16   **X**   Number of 'Parking Spaces : Meter Number' Rows in Property & Street Information Freeform 
Unmetered Fee = 3.20   **X**   Value in 'Number of Days' Info field (Info Code 75390)   **X**   Value in 'Number of (#)' field in 'Parking Spaces : # Unmetered Spaces' row of Property & Street Information Freeform
Parking Space Permit Fee (50170) = Metered Fee + Unmetered Fee

**Note** 
- '**X**' in the payment logic above denotes multiplication
- Values 16 and 3.20 are variables and may change in the future. These should not be hard coded and should be added to a lookup table (Tracy mentioned this was lookup table 5025)
- The logic for inserting the fee may currently exist. If it does, it needs to be updated or removed to account for this new change in logic
- A screenshot of Property & Street Information Freeform provided below for reference
![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/4a74ca42-471a-4264-89fe-1ad733410534)

**Comment by TracyLinder** [comment]
@vschandramouli I've assigned this to you. You can add it to your workload when you have time; no rush.

**Comment by vschandramouli** [comment]
Updated AC based on feedback from Nate. 
Pending items before ticket is ready for Backlog: 

1. Need to confirm existing logic for when this fee is inserted 
2. Need to update the codes for the info fields mentioned in this ticket.

**Comment by vschandramouli** [comment]
Updated codes for infos and processes. Ready for Backlog.

**Comment by Nadin-Nader** [comment]
@vschandramouli this looks ready, you can move it to backlog

**Comment by TracyLinder** [comment]
**Update:**
- This needs to be an eipc, and the work needs to be sliced up into smaller issues.
- Moving this to Needs Scoping until that's done.

**Comment by TracyLinder** [comment]
**Tasks for @vschandramouli** 

- [ ] Turn this issue into an epic
- [ ] Make a child issue for each chunk of work

Work Chunks:

1. Update folder infos
2. Update fee logic

**Comment by TracyLinder** [comment]
Work has been delivered. Closing this EPIC.
