### ISSUE TITLE
Hire a Temp Product Manager

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#403]
Potential Project assignments:
- BI Discovery
- Vision Zero Editor + Viewer
- Paperless Hiring
- Micromobility Data Management
- Signs & Markings Operations App / Backlog

**Comment by johnclary** [comment]
Potential Projects:
- RPP procurement
- Vision Zero data management/visualization
- Development Review management
- paperless HR initiatives

**Comment by amenity** [comment]
@johnclary - do you have the text you used for my job description kicking around somewhere?

**Comment by johnclary** [comment]
Yes, just copied to our drive: https://docs.google.com/document/d/1e1IXmdi7Ov79cofaYmqJUr9q-XRdRzxkpLpNyDU07sU/edit
