### ISSUE TITLE
[RPP Back Office] Update RPP GIS layer

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4031]
Effective Oct 1 there will be a change in the rates and rules for Residential Parking Permits
Permit rates are increasing 
Residents can now purchase up to 6 permits per address (Mueller is the exception)
The RPP GIS layer needs to be updated with the new rules
![image](https://user-images.githubusercontent.com/56606465/94580224-48a68580-023f-11eb-912f-59046626e343.png)

Please let me know if any additional information is needed. Thanks

**Comment by jaime-mckeown** [comment]
@moorerst Parking has their own GIS Analyst, I thought that he would be doing these kinds of tasks. I normally publish data to ArcGIS Online for them, but Francesco does all the GIS work.

**Comment by moorerst** [comment]
@jaime-mckeown John asked me to assign the issue to you. Sorry I will follow up with them. Thanks

**Comment by moorerst** [comment]
Sent follow up email to RPP team to get direction on who can make the necessary updates.

**Comment by moorerst** [comment]
Completed by Royal R - rules were updated to reflect new maximum permit purchases per address
![image](https://user-images.githubusercontent.com/56606465/95100939-3e7cff00-06f7-11eb-9cd0-d100c8944e5c.png)
