### ISSUE TITLE
Remove Old FY20 Fees

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4033]
## Old zoning fees need to be removed from the ZC folder fee procedures. 
[FY 21 Fee Updates](https://app.zenhub.com/files/140626918/b06e8c53-0aeb-4b39-9ae4-29c0ac28e023/download)
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/ad87d878-cc35-4d26-8e7d-a111ccdc0720)

Commit#1: d183b245

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan this is the ticket for removing fees. I'll leave it in the backlog until we get to it in a future sprint planning.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - Not Started

**Comment by licarir** [comment]
Changes complete. Waiting on audit and promotion.

**Comment by licarir** [comment]
@TracyLinder @Nadin-Nader This has been requested to be moved to Dev and Test.

**Comment by licarir** [comment]
@TracyLinder @Nadin-Nader This change has made it to Dev and Test and is ready for UAT. Thank you.

Please Promote commit #d183b245b0d9 to Dev and Test for ATD Issue#4033-Remove 5 fees. - Done on CM team board.

**Comment by licarir** [comment]
53f2b53e54be9ef57018a8f0b97836bff2f40dfa

Corrected Commit above. Use this for PROD when/if promoting.

**Comment by TracyLinder** [comment]
Putting this at the top of the backlog until the code freeze is over.

**Comment by TracyLinder** [comment]
@SubhaShroff can you please look into this and comment with a current update? Thank you.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader As per the Robert's notes on this ticket, here is what I noticed:
- Robert has done necessary code changes and one more commit(ea9fe1d84306) needs to move from ATD branch to DEV and then TEST before UAT is done. It all looks good on phabricator. Since the change is done on ATD local branch, I cant test it on LIT local branch. Please let me know if the commit-ea9fe1d84306 can be moved to DEV. So that we can test it on DEV.

- From the commits I see that the fees are deleted from TIA permit also. Just want to confirm if that is part of requirement.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder DEV deployment request is submitted for commit(ea9fe1d84306) as per Robert's notes in the ticket -SCTASK0133038. [4/22/3031]

**Comment by Nadin-Nader** [comment]
@SubhaShroff Updated TASK for DEV deployment to reflect High Urgency

## **Status:**

Waiting on DevOps TO Deploy **SCTASK0133038** to **DEV**

**Comment by SubhaShroff** [comment]
Status:
Tested it on DEV, looks good. Further, ea9fe1d84306 needs to be promoted to TEST as per Robert's notes. I submitted a ServiceNow request for TEST deployment of ea9fe1d84306 : **SCTASK0133544**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  SCTASK0133544 is served.  I tested it on TEST and its ready for your testing.

**Comment by SubhaShroff** [comment]
**Status:**  I tested it on TEST and its ready for testing.

**Comment by SubhaShroff** [comment]
### Status:
Waiting on UAT.

**Comment by SubhaShroff** [comment]
### Status:
Waiting for UAT.

**Comment by TracyLinder** [comment]
UAT Passed, See screenshot.

### Approved for Prod 🎉
@SubhaShroff please promote.

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/d130dda0-21a1-4146-8fbd-cd532042b2c8)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder I submitted ServiceNow request - **SCTASK0137282** (commits:53f2b53e54be, ea9fe1d84306) for PROD Deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  **SCTASK0137282** is closed. **PROD deployment is done.**

**Comment by Nadin-Nader** [comment]
## **Status:**

## **Ready for PROD UAT**

**Comment by TracyLinder** [comment]
The stakeholders have been notified. I'm closing this one. Thanks everyone.
