### ISSUE TITLE
PIR 80473 - Small Cell Location Data

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4037]
Due October 5th.

> I am seeking the following information from the City of Austin. Generally speaking, I am trying to determine the location data (address or lat/long) of all small cells or distributed antenna system (DAS) nodes within the City of Austin that have been deployed in the Public Right Of Way. I am also seeking information about the owner of the small cells or DAS nodes, the wireless provider using them, and what technology they are using to the extent available.
> 
> 1. Any compilations, spreadsheets, maps, summaries, dataset, or lists of all small cell permits and applications created by, submitted to, or approved by the City of Austin for small cells or DAS nodes within the City of Austin.
> 2. If no such compilations, spreadsheets, maps, summaries, dataset, or list of small cells permits are available, copies of any permits approved to date. If easier or it reduces costs, we do not need the supporting documentation to each permit application.
> 3. If there is an easier way to provide the information that we are requesting that we haven’t asked for, please let us know. It is not our intention to create additional work or burden. We are just trying to get location data, ownership information, wireless carrier using each node or small cell, and technology type information to the extent available.
> 
> Electronic copies of the permits or responsive documents are acceptable. If the permit information is available online, please describe specifically how the system can be searched to identify small cell permits if the requestor is not familiar with the location of the small cells already. If there is a cost to this report, please provide the estimate to us.

**Comment by johnclary** [comment]
I emailed the Small Cell group and CC'd Tracy. This data lives in the Data Tracker can be easily downloaded.

> April and John—my team can provide the pole attachment data in the Data Tracker. It sounds like the requester would be content with that data without having to run any additional reports/queries.

**Comment by amenity** [comment]
Completed by April S. :).
