### ISSUE TITLE
Launch OMF Privacy and Security Committee

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#404]
Todo:
- recruit participants
- schedule regular meetings
- define goals/deliverables

Possible deliverables:
- privacy principles which define practices for handling, retaining, and distributing MDS data
- data processing toolkit
- list of cities which are using MDS and what approach they're taking

**Comment by amenity** [comment]
@johnclary - you want this on deck for Sprint 12?

**Comment by johnclary** [comment]
Meeting held on 11/20. Repo is [here](https://github.com/openmobilityfoundation/privacy-committee). Working on adding notes and such. I added this repo to our zenhub board, though the board does not seem happy about it (because the repo belong to another org).
