### ISSUE TITLE
Create Digital Nomination Form

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#4041]
The idea right now is to do a simple Google Form. HR has decided that people can only nominate themselves. We need the listing of "Work Groups" to be provided by Gilda.

Title: Self-nomination Form for Equity Committee Elections
Fields: 
1. What is your name? -> short text
2. What is your work group -> dropdown of options
3. Confirm that you are nominating yourself to run for a Equity Committee position representing your work group -> checkbox
- Submit

**Comment by amenity** [comment]
Gilda will send a list of workgroups. They'd like to send this out by this Friday.

**Comment by mateoclarke** [comment]
John and I have received the spreadsheet. Forwarding to @SurbhiBakshi and please reach out via DM if other need it.
