### ISSUE TITLE
Update Knack Fiscal Year filters

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4046]
Update Knack Fiscal Year filtering functionality for 2021 

Workaround using YTD filters will need to be updated. 

- [x] TCP in Data Tracker - Chrispin
- [x] [Signs Reporting Page](https://github.com/cityofaustin/atd-data-tech/issues/3954) - Surbhi

**Comment by amenity** [comment]
@SurbhiBakshi — please send calendar invite🙏

**Comment by ChrispinP** [comment]
@amenity Do we have a link for the Fiscal Year reporting in AMD Data Tracker? Under the TCP reports I dont see a current Fiscal Year report to update.

**Comment by amenity** [comment]
@ChrispinP I actually couldn’t find it either. @johnclary do you remember where it is off the top of your head?

**Comment by johnclary** [comment]
Hmm, it looks like we're just using a rolling year filter rather than an explicit fiscal year filter. E.g., https://builder.knack.com/atd/amd#pages/scene_737/views/view_1972

<img width="810" alt="Screen Shot 2020-12-14 at 3 38 45 PM" src="https://user-images.githubusercontent.com/14793120/102138794-89677100-3e22-11eb-940f-063c7159bdd9.png">

So it appears there's nothing to do here.

**Comment by ChrispinP** [comment]
@johnclary Thanks so much John. I also double checked the front end to make sure its noted that we use rolling years and it is indeed.

This is definitely the best option to avoid us having to go in and update all reports every year but still sad there is no Fiscal Year option.

@SurbhiBakshi I would just make sure that the reports in Signs also use rolling year filters and state that they do on the front end. If Signs explicitly needs YTD reports then they should be created separately from the rolling year reports.

I will apply this to RPP as well once I update the reporting there as well.

**Comment by SurbhiBakshi** [comment]
@ChrispinP - SMB wants to see Fiscal Year Reporting and some of it's reports had that in place already. I  have updated those and also made changes to other ones that SMB wanted  to see Fiscal Year Reporting. Also, if we update Fiscal Year filters, we need to do it in October.
