### ISSUE TITLE
Intake Meeting: Signs and Markings contractor tracking

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4047]

**Comment by amenity** [comment]
Scheduled for 10/23.

**Comment by dianamartin** [comment]
Talked to Christina briefly this morning to ask where to find the `Daily Contractor Ticket` forms I had made for Joe Michael. Some screen shots of filled out ones.

File path for "form": `G:\ATD\Signs_and_Markings\MARKINGS\0_PROGRAM_Markings_Maintenance\Forms\Working_Forms`

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/1a3eec53-403d-4cb4-a635-f04c77888fc0)

### Things we discussed:
- Loading contractor materials list (Contractor 1 & Contractor 2) - _[Similar to AMD Construction Cost Estimate](https://atd.knack.com/amd#construction-cost-estimates/)_
- Entering materials used form - _Similar to AMD Construction Cost Estimate_
- Inspections process - returning to contractor to fix issues
  - Button to update:
    - `Inspected` field (Y/N), 
    - `Inspected By`, 
    - `Inspected Date` 
    - `Issue/Comment`, 
    - `Inspection Status` - default "Inspected - Pass/Fail", 
    - `Follow-up` (Y/N) default based on "Inspection Status"
  - Inspection table has fields listed above but also another field for contractor to change
    - `Follow-up Status` (Needs Correction/Resolved)

**Comment by dianamartin** [comment]
#Diana's Notes

## Process 
Work Assignments - maintenance on long line and crosswalks
Maintenance work that contractors do
Markings work

Line items, marking material - identify price of project
Pull street segments from GIS, identify the street assignments

Spreadsheet is created from GIS
Work Assignment spreadsheet given to contractors

## Contractor Process
Daily work ticket, the date, street they're on
Work assignment #
Line items from contract

Submit through email to Toran and Joe Michael
Come as excel document
Joe Michael prints into paper ticket
Goes to locations and field checks everything
Calls/Texts contractor
No good email/paper trail

Need to go back and follow-up on the work
Inspection is good, Joe Mike signs and approves
Scans in an email back to Toran and says they're done
Ready to be invoiced - by Toran

At the end of the month, invoicing is done for each work assignment
Contractor sends an excel sheet, different kind of markings
Other columns they work 
Toran reviews excel spreadsheet and not errors in how much they charged, QC'ing the spreadsheet from the contractor
Verifies and sent to CCO 

### GOAL
Inspections tracked
Daily work tickets completed
Toran to review daily work tickets
SMB to review and then ready to invoice
DIJ to pull that information easily - export data for their own spreadsheet

## Common Errors
- Price accidentally changed
- Do they ever make mistakes on Daily Work Tickets
  - line item Ex. Lamar, Toomey to 45th
  - multiple days Daily Work Tickets - Work Order
    - child work order?
  
- All on one page
- Work Assignment - multiple material items
-

**Comment by amenity** [comment]
SMB Contractor Tracking Intake

*Lauren, Christina, Surbhi, Diana, Amenity*



**Current process**

- Tooran creates work assignment
- Money give to work assignment 
- DIJ is current contractor and will be adding another this year
- Line items, contractor identifies price
- Christina makes and Excel doc and pulls information from GIS
- Asks Toron to issue to contractor using a given DO 
- Every day Contractor uses line items from contract to report on what they did, total that, then submit via email to Toron and Joe M. 

- Joe then prints to take to field and texts DIJ staff person (no email trail here) if there is an issue. Once everything is approved, they scan and email to Tooran. Contractor sends giant spreadsheet with all work they are billing for. Toron has to compare to initial spreadsheet to check for errors, most commonly

- Wrong price

- Quantities might not match up b/c manual data entry



**Summary**

Want inspections tracked

Contractor work tickets completed through Knack

Avert bad data, relieve Toron of unnecessary QA



**Mapping**

Ideal world, these could be mapped in Knack either as a separate GIS dataset or with all the SMB work orders. 

- That will blow scope; would have to be future enhancement
- We can have a status for "Needs QA/QC" for GIS process
- Better process: Christina/Suzanne could create and maintain geospatial data when they're creating Work Orders and add the Street Segments ID

- Christina could create the Feature up front by selecting street segments, joining, and entering the Feature ID to a field in the Contractor Work Order in Knack. 
- (Theoretically she could then export completed work orders from Knack and import in ArcGIS to update the status on those.)

**Comment by amenity** [comment]
SMB Contractor Tracking Intake

*Lauren, Christina, Surbhi, Diana, Amenity*



**Current process**

- Tooran creates work assignment
- Money give to work assignment 
- DIJ is current contractor and will be adding another this year
- Line items, contractor identifies price
- Christina makes and Excel doc and pulls information from GIS
- Asks Toron to issue to contractor using a given DO 
- Every day Contractor uses line items from contract to report on what they did, total that, then submit via email to Toron and Joe M. 

- Joe then prints to take to field and texts DIJ staff person (no email trail here) if there is an issue. Once everything is approved, they scan and email to Tooran. Contractor sends giant spreadsheet with all work they are billing for. Toron has to compare to initial spreadsheet to check for errors, most commonly

- Wrong price

- Quantities might not match up b/c manual data entry



**Summary**

Want inspections tracked

Contractor work tickets completed through Knack

Avert bad data, relieve Toron of unnecessary QA



**Mapping**

Ideal world, these could be mapped in Knack either as a separate GIS dataset or with all the SMB work orders. 

- That will blow scope; would have to be future enhancement
- We can have a status for "Needs QA/QC" for GIS process
- Better process: Christina/Suzanne could create and maintain geospatial data when they're creating Work Orders and add the Street Segments ID

- Christina could create the Feature upfront by selecting street segments, joining, and entering the Feature ID to a field in the Contractor Work Order in Knack. 
- (Theoretically, she could then export completed work orders from Knack and import in ArcGIS to update the status on those.)

**Comment by dianamartin** [comment]
@amenity dup notes?

**Comment by amenity** [comment]
![Screen Shot 2020-10-23 at 3 22 09 PM](https://user-images.githubusercontent.com/1463708/97054935-5fdd4800-154b-11eb-8ab1-6771f6a551a2.png)
Also...

**Comment by amenity** [comment]
@johnclary @SurbhiBakshi feel free to add any thoughts.

**Comment by johnclary** [comment]
@amenity looks good to me—thanks!

**Comment by SurbhiBakshi** [comment]
@amenity - Looks good to me as well, thanks!
