### ISSUE TITLE
Clean up old service requests

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#405]
- [x] Christina to send out SRs and WOs that need to be deleted from the system

CSR Number
--
- [x] 19-00281549
- [ ] 19-00281787
>no record existed. might've already deleted this morning. 

- [x] 19-00282097
- [x] 19-00282344
- [x] 19-00281526
- [ ] 19-00281549
>no record existed. might've already deleted this morning. 
- [x] Delete those SRs and WOs on her list

**Comment by dianamartin** [comment]
Deleted 23 records this morning. SRs from 7/23 to 7/29.

**Comment by dianamartin** [comment]
## Delete Flex Notes
- [ ] Filter `csr_flex_notes` object table for no `SR Number` 
- [ ] Delete those orphaned flex notes

**Comment by dianamartin** [comment]
## More SR records to delete

- [ ] 19-00281905
- [ ] 19-00281910
- [ ] 19-00280626
- [ ] 19-00280254
- [ ] 19-00280406
- [ ] 19-00280202
- [ ] 19-00280626
- [ ] 19-00281275
- [ ] 19-00281472
- [ ] 19-00281598
- [ ] 19-00281660
- [ ] 19-00281905
