### ISSUE TITLE
Moped | Project Staffing - Build React frontend for "Add team member" modal

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4053]

**Comment by amenity** [comment]
@lazavazav @zappfyllc — does the Material UI add-record-to-table-inline cover this?

**Comment by lazavazav** [comment]
yes, I think so.

**Comment by zappfyllc** [comment]
@amenity I think this can be closed as a duplicate of #3979 since the functionality is given out-of-the-box with the MatUI table

**Comment by amenity** [comment]
🙏
