### ISSUE TITLE
Moped | Roles and Permissions - Synchronize Cognito with Postgres users table

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4054]
Users table in Moped: moped_coa_staff

**Comment by sergiogcx** [comment]
Whenever a cognito account is created, we have to do a few tasks:

- [ ] Sync with Hasura, and populate the user, and user details such as the Cognito ID, email, (roles?), and other flags.
- [ ] If the email contains austintexas.gov, that means it is a city account and the is_city_staff column needs to be populated.

**Comment by sergiogcx** [comment]
So after a couple days of work and implantation, we had to re-evaluate the direction where I was heading with using triggers in cognito to make this happen. I think, it would be a lot better and simpler to use the API. Here is a graph that describes the way it would work:

https://miro.com/app/board/o9J_kh_YXrY=/

**Comment by amenity** [comment]
@sergiogcx - link to the Moped board version is here: https://miro.com/app/board/o9J_knyFAmc=/?moveToWidget=3074457350012857291&cot=12

**Comment by sergiogcx** [comment]
I've continued work on this, so far I have had needed to add a validation library that can help us with the intake of data and make sure that data has all the necessary validation. We are now able to validate this data and provide feedback to the UI about what fields specifically need correction and what is expected when creating a new user.

Having this validation, can help us make sure no user is crated in AWS or Hasura until we have all the fields we need.
