### ISSUE TITLE
Compare Serious Injury counts from multiple sources s (crashes vs. people)

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#4062]
Xavier noticed that the number in the VZV serious injuries widget is off by 3 when compared to data pulled from the person tables in the VZD (data through August 31, 2020). We need to compare the numbers when pulled from the Socrata crashes dataset and when pulled from the Socrata people dataset to see how they compare.

We also need to take another look at how to ensure that any edits through VZE result in changes that are consistent across the crashes, units, and people tables (triggers, etc.) so that any VZV visualization numbers agree with what the VZ team sees internally from VZD.

<img width="1195" alt="Screen Shot 2020-10-01 at 4 41 55 PM" src="https://user-images.githubusercontent.com/37249039/94866550-3413ea00-0405-11eb-9e36-a282a69b7780.png">

**Comment by JaceDeloney** [comment]
Closing this out as it doesn't seem to be a prob anymore
