### ISSUE TITLE
Suspend Permit Folders When Contractor License Expires

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4070]
# Delivered on #10849

### When an LC folder expires, we'd like the system to identify the related active permit folders, and update the folder status to 'Suspended'. 

**Stakeholders:** Paloma, Kim
**DTS Manager:** TBD

**Acceptance Criteria:**
- System should run a daily batch that checks to find LC folders that are 9 days away from expiry, and send an email to 'Right-Of-Way Contractor' of those LC folders  
- Only one email should be sent to each contractor
- Text for the email is below

Subject: ROW Permit Expiration Notice
Dear Michael Miller [Right-Of-Way Contractor People record First Name and Last Name],

This email is to advise you that your Right of Way Contractor License will expire on [LC folder Expiry date].

All Driveway/Sidewalk and Excavation permits associated with your Right of Way Contractor License will expire on [LC folder Expiry date] if the license is not renewed. A list of those permits is provided below. To renew your Right of Way Contractor License, look for the "How is a Right of Way Contractor License renewed?" Section at this URL - https://austintexas.gov/page/right-way-contractors

Your DS/EX Permits That Will Expire:

- [Folder Number of DS or EX folder, for example, 2022-012345 DS]

**The Acceptance Criteria provided below applies to a batch job that ROW would ideally like to be split into a separate ticket and handled after the email above.** 
- System should run a daily batch that checks for LC folders that have a status of 'Expired'. 
- System should then check the People record of LC folders that have a type of 'Right-Of-Way Contractor' to see if they are part of any DS or EX folders 
- If there are any DS or EX folders for the People record that have a status of 'Active', system should change the folder status of these folders to 'Expired - License'
- System should also check daily if any LC folders have changed from 'Expired' to 'Active'
- If there are any LC folders that are now 'Active', system should change the corresponding DS and EX folders from 'Expired - License' to 'Active'  

**Note** - The status 'Expired-License' does not exist currently. It needs to be newly created. 
**Note** - As an extension to this feature, it was also suggested that the insurance dates can be considered to expire DS and EX folders. This may be addressed as a separate ticket after this one is implemented.

**Comment by TracyLinder** [comment]
@vschandramouli when you're ready to look at this let me know. It will be easier to show you in AMANDA what this is versus trying to explain it.

**Comment by TracyLinder** [comment]
@vschandramouli when you're ready to move this to the backlog, can you please schedule some time with me to go over the AC? Thank you!

**Comment by vschandramouli** [comment]
AC definition complete. Will move to Backlog after meeting with Tracy.

**Comment by vschandramouli** [comment]
AC updated. Moving to Backlog.

**Comment by TracyLinder** [comment]
**Update:** We'd like to speak to Ryan about this before we prioritize this. Also, we may not want to use the word suspended.

**Comment by TracyLinder** [comment]
### AC Needs to be updated

- LC renewals are now done via smartsheet... the initial LC application is also done via smartsheet. 
- Tracy wants to re-think the way the emails are triggered (we should notify LC is about to expire regardless of any of their permit folders, and include a list of active DS/EX folders if there are any associated.)

**Next Steps:**
1. Tracy & Vish to review current AC on Monday 11/21
2. Vish will work with ROW to update AC

**Comment by vschandramouli** [comment]
Updated based on feedback from Paloma.. Ready to discuss with Ryan and others before moving to Backlog.

**Comment by TracyLinder** [comment]
### Checkin w/ ROW
- Tracy cautioned that this feature may not be worth building considering the AMANDA replacement.
- This is a huge lift
- Ryan needs to approve the AC also

- Icebox this until ECM replacement.

**Comment by vschandramouli** [comment]
Moving to Icebox as mentioned above.

**Comment by TracyLinder** [comment]
@vschandramouli please create a new ticket for the 9 day advanced notice batch job, and include a note that Nate is concerned about creating new batch jobs as they are all running on S1 and causing the system to slow/crash. He suggests if it's not necessary - we should consider not doing it.
