### ISSUE TITLE
Feature: Display status of urgent priority pages to technicians in Data Tracker

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4074]
Per #3914: 

Morning shift— e.g. Martin
- Review what came in overnight, assess status of requests
- Anything marked as "priority urgent" will page technicians if it's after hours
- MMC will see request but just because there isn't a work order associated with it does not mean it's still open... All techs have different process — might create a work order immediately or may wait days and do them in batches
- MMC has log in to Premier to see whether page was acknowledged — can't see it in Data Tracker

Request: Give MMC staff ability to see whether technicians have acknowledged a page in Data Tracker

**Comment by amenity** [comment]
Sounds unlikely that this is possible, but would need a dev to look into it.

**Comment by dianamartin** [comment]
Messaged Lance and Allyson about this request
>there was one more I have a question about: Display status of urgent priority pages to technicians in Data Tracker

Lance
>hmmm. i am not aware of that one

Perhaps he'll look into this request

**Comment by amenity** [comment]
Thanks, @dianamartin - going to Icebox for now.

**Comment by amenity** [comment]
I take that back — did you share this full write up with Lance? We discussed it thoroughly during #3914.

**Comment by dianamartin** [comment]
@amenity I didn't share that last issue, I just sent it to them to look at. I think they still might want this still but they just have to jog their memories.

**Comment by ChristinaTremel** [comment]
@dianamartin won't this request be resolved with the enhancements we're making for 311? The Techs will be responding to pages in Data Tracker, therefore the MMC will easily be able to see that pages were acknowledged.

**Comment by dianamartin** [comment]
@ChristinaTremel Yes, this will be addressed with the new Paging Activity page we're setting up to manage pages in the Knack environments (Data Tracker).

**Comment by ChristinaTremel** [comment]
Closing this issue because this feature will be added to Data Tracker through the enhancements we are making for 311 (issue #9960).
