### ISSUE TITLE
[RPP Back Office] License Plate Requirement

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4075]
There should not be a requirement to enter License Plate information for 6 vehicles on the Permit Information page.
Number of license plates needed is based on the # of permits requested

**Comment by ChrispinP** [comment]
Had to set a rule for 0 values and update hide/show values so License Plates correctly display. Tested and should be good now.

complete

**Comment by moorerst** [comment]
confirmed its working correctly now
