### ISSUE TITLE
[RPP Back Office] Review Application Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4076]
From the Review and Submit Application page all applications are displaying. I should only see my application to review, sign and submit

**Comment by moorerst** [comment]
Also seeing everyone required documents
![image](https://user-images.githubusercontent.com/56606465/95093363-4edcac00-06ee-11eb-8639-0284444a7da5.png)
![image](https://user-images.githubusercontent.com/56606465/95093449-6a47b700-06ee-11eb-9863-c180936484d6.png)

**Comment by moorerst** [comment]
I can't get pass this step to continue testing.

**Comment by ChrispinP** [comment]
this should be corrected now that the review page is now a child page only displaying the current records being worked with. Edit options should be available and working.
