### ISSUE TITLE
[RPP Back Office] Permit Information - Hang Tag Max

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4077]
If the max # of Hang Tags is 2 should the drop down list only show 1, 2 not up to 6?

**Comment by ChrispinP** [comment]
up to 6 is the max for visitor hangtags under RPP staff approval. On the application, a customer will only be able to select up to 2 now or you get a validation error.

complete

**Comment by moorerst** [comment]
@ChrispinP This is also an item listed on issue #4116 so I'm going to close this issue.
