### ISSUE TITLE
Update VZA Officer interface

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4081]
#### Today's Assignments

Details | Time | Location | Clock In(editable) | Clock Out(editable) | Observations
-- | -- | -- | -- | -- | --
📁 | 10:00 to 12:00 |   |   |   | [number of notes]

### _Past Assignments_ page
Same as what Randy sees minus Officer info:

Details | Date | Time | Location | Clock In | Clock Out | Hours
-- | -- | -- | -- | -- | -- | --
📁 | AP 6422 | 09/18/2020 |   | 07:00 to 10:00 | 10:00 | 13:01

**Comment by amenity** [comment]
@SurbhiBakshi - will you estimate this one? It would be great to do this one this Sprint so we can get it in front of pilot officers.

**Comment by SurbhiBakshi** [comment]
@amenity - going to put this at a 2, will check in with @mddilley for Today's Assignments before making any changes.

**Comment by amenity** [comment]
@SurbhiBakshi - please make Past Assignments into its own page.

**Comment by SurbhiBakshi** [comment]
Filter query on Today's Assignments  should only be for Today's Assignments
Add fields - Clock in, Clock Out, Observations to Today's Assignments
Add Editable Clock In and Clock Out to Assignment Details below Details

**Comment by mddilley** [comment]
I've updated the fields in the "Today's Assignments" on the "My Assignments" page and added the "Start Time" (`field_560`), "End Time" (`field_561`), and "Number of Observations" (`field_733`) fields to the API view (`scene_238` and `view_487`) in staging and production.

**Comment by amenity** [comment]
@SurbhiBakshi @mddilley cool! Is this ready for review, then?

**Comment by SurbhiBakshi** [comment]
@amenity - @mddilley and I are trying to figure out how to reincorporate the fields filled by the triggers - Start and End Assignments. The fields in the Assignments Details - Start Time and End Time were being used in the code. I (yikes) did not realize that , and took those away when I put the editable time stamps under Assignment Details. I am wondering if we could put those back in, or @mddilley suggested there may be a way to hide them.

**Comment by mddilley** [comment]
As a fix, I updated the code to depend on values in the "Clock In" and "Clock Out" fields. The enabled/disabled statuses of the buttons as well as the timestamps below the buttons now work as it did before.

#### Screenshot
![Screen Shot 2020-11-05 at 11.14.23 AM.png](https://images.zenhubusercontent.com/5cfe7d078509cb6dcbaafdc3/116c7562-6bb1-4d4f-ba5c-4120043bb978)

**Comment by mddilley** [comment]
This is deployed in production and has been tested. Closing.

**Comment by amenity** [comment]
@mddilley - wonderful, thank you!
