### ISSUE TITLE
Update VZA Admin Interface

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4082]
- [x] Rename "Account Administration" to "Officers" and make just the Officers section
- [x] New page, "Invoicing" — shows [what is currently in "Account Administration > Assignments"](https://user-images.githubusercontent.com/1463708/95142967-8ffaad80-073a-11eb-8b24-629cbf89c9c0.png)
- [x] New page, "Cancellations" — shows [what is currently in "Account Administration > Cancelled Within 48 Hours"](https://user-images.githubusercontent.com/1463708/95143208-14e5c700-073b-11eb-9929-11cdd9837d2c.png)
- [x] Remove "Cancellation Policy" tab
- [x] Add "Assignments" tab:

Details | Badge Number | Date | Time | Clock In | Clock Out | Time on Assignment
-- | -- | -- | -- | -- | -- | --
📁 | AP 6422 | 09/18/2020 | 07:00 to 10:00 | 10:00 | 13:01 | 2.87

I am not sure what refinements to recommend on the "Cancelled Within 48 Hours" table, but 
- I don't know why "Removed Hours" would be useful for Randy 
- How will he know if the shift was ultimately filled or not if there isn't info on which team and assignment it is? Dream state we would obviously only show ones there that were not worked by anyone, but I assume that is a bit complex. Can we make the shift dates/times hyperlinks that go to the log for a given assignment?

**Comment by SurbhiBakshi** [comment]
@amenity - want to clarify if this is what you mean -  

1. Randy should be able to see an Assignments tab with two new pages - Invoicing and Cancellations?
2. Randy should not be able to see Cancellations Policy tab.
3. The table you have drawn above is the Invoicing table.
4. The Removed Hours is not specifically for Randy, but whoever is the team lead for the officers and keeps an eye on the cancellations. At one point, both Randy and Pat were supposed to have access to this page. 


Answering your questions below - 
- How will he know if the shift was ultimately filled or not if there isn't info on which team and assignment it is? I don't think Randy has asked us to show which specific assignments were not filled. However at one point in an earlier iteration of the app, I had two reports which showed which assignments went unfilled by day of the week, and by location. If needed, I think I can still do that.


Dream state we would obviously only show ones there that were not worked by anyone, but I assume that is a bit complex. - We had that as part of the reporting to show unfilled assignments. If I am not mistaken, Lewis was interested in that information.

Can we make the shift dates/times hyperlinks that go to the log for a given assignment? - We can hyperlink to a modal with assignment details. What do you want to see in the log?

**Comment by amenity** [comment]
@SurbhiBakshi 
1-3, yes. 👌

Let's revisit the need to track removed hours with the stakeholders. I remember them wanting to stay on top of repeat offenders who constantly cancelled, but don't know that it warrants a column in this main view. Seems like it would make more sense as a column on the Officers (currently "Account Administration") page? Then you could sort to see who had cancelled most frequently or look up hours by officer. 

---
Re: unfilled assignments

Since Officers are only violating the SEU Cancellation policy if the shift they cancel within 48 hours is not filled, I think we should have some sort of a workflow for Randy to check on that. What I meant by "dream state" is that Randy's interface would only show violations of the policy, e.g. assignments that were _**both**_
- Cancelled w/in 48 hours
- Not backfilled by another officer
Since I don't think we're able to show that programatically, if we give Randy a hyperlink to a modal with assignment details showing who, if anyone, took the shift from the cancelled-within-48-hours listing, he can work from there. 

Thanks!

**Comment by amenity** [comment]
Looks beautiful 😍 - going to rename "Cancelled Within 48 Hours" to "Cancelled Within 48 Hours Without Replacement"
