### ISSUE TITLE
Shared Mobility Data Request - Voting Trips

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4095]
### Background
Shared Mobility Services would like to analyze shared mobility trips taken during primary runoffs to plan for and support future trips to polling locations in November.

This analysis would help us understand if there is a need for shared mobility support in certain areas, e.g., increased deployments, rebalancing, provider promotions if necessary, etc.
 
**Date range:** 
Early voting was June 12-July 10, except July 3 and 4 because no voting took place for the July 4 holiday. July 14 was Election Day.
**Early voting locations:**  https://countyclerk.traviscountytx.gov/images/pdfs/polling_locations/07.14.2020/PR20_and_SE20_Early_Voting_Sites_Flyer.pdf
**Election Day (July 14) locations:** https://countyclerk.traviscountytx.gov/images/pdfs/election_results/2020.07.14/07142020locreportingrun3_w.pdf
**Fields we require:**

**Retention period:** 
Until November 3, 2020 – Election Day.
**Temporal precision:** 
Hourly

--- 
Francesco is working on a GIS shapefile with polygons and points for the polling locations, and suggested a buffer of 100 feet around these locations for trips that end (and/or start) within these target locations. 

In addition to the number of trips that entered/left the voting areas and the average (+min/max, if possible) trip distances, which was brought up by John, Francesco has also proposed including orientation in degrees (from 0 to 360) or just as 8 categories (north, northwest, west, southwest, south, southeast, east, northeast) between the start and end points of each trip. This would make the analysis much more meaningful while also preserving privacy and would certainly help to identify hot spots where scooters/bikes are more needed.

**Comment by JaceDeloney** [comment]
Attached is the shapefile with the 100 polling locations, which can be used to filter the data. This shapefile, called "TC_PollingLocations_Buffer", was created by drawing a 100-foot buffer around the buildings where the voting took place last July. As a reference, he also included the "TC_PollingLocations" shapefile, which includes just the building polygons.

**Comment by JaceDeloney** [comment]
Next Steps:

1. they give us the voting locations as a GIS point layer
2. they give tell us the radius around each point they want they want to use as a filter for trips
3. we can tell them how many trips entered or left those areas, including average trip distance for both origins and destinations

**Comment by JaceDeloney** [comment]
Attached is the shapefile with the 100 polling locations, which can be used to filter the data. This shapefile, called "TC_PollingLocations_Buffer", was created by drawing a 100-foot buffer around the buildings where the voting took place last July. As a reference, he also included the "TC_PollingLocations" shapefile, which includes just the building polygons.

**Comment by JaceDeloney** [comment]
@JaceDeloney Work with John to specify the database query that will be needed to associate trips to polygons.

**Comment by sergiogcx** [comment]
Taken from a Slack conversation:

> Cool, this should be possible. I will stop deleting raw data until we take care of this (data stays there for 30 days).

> I do have a concern though, if I remember correctly, the start/end points for a trip get truncated several digits, not sure how much this would affect our accuracy.

>Though I am thinking we might be able to add an extra ETL step with the data we collected from the provider, then insert those special trips in a separate table in Postgres. What do you think of this approach?

**Comment by sergiogcx** [comment]
Another idea, I could implement special views in Postgres that search for these trips, in whatever state the points are.

**Comment by JaceDeloney** [comment]
This was completed and sent over to Shared Mobility. We have not received any feedback, questions, or updates from their team. Closing this out.
