### ISSUE TITLE
Project: Traffic Counts

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#410]
## Description
This project created a new module in the Data Tracker to help streamline the traffic count and data collection request process for our Data Collection team. This helped the tracking of the data requests and made the process transparent and easier to use for users

### Resources
- Link to folder `G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\AMD_DATA_TRACKER\Traffic_Counts`

**Comment by johnclary** [comment]
@dianamartin closing this. Please open additional issues for any outstanding work. Thanks.
