### ISSUE TITLE
Retro on RPP data leak 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4104]
- What worked? 
- What went wrong?
- What needs to change? 
--

**Comment by amenity** [comment]
@moorerst — would you please schedule, ideally this sprint?

**Comment by johnclary** [comment]
Scheduled two on 10/22: 930am (internal) and 1pm (with info sec office)

**Comment by johnclary** [comment]
@johnclary add notes and create follow up issues
