### ISSUE TITLE
Update "B-Cycle" to "Metrobike"

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4105]
Update all instances of B-Cycle to Metrobike

**Comment by amenity** [comment]
Good catch, @ChrispinP! @dianamartin @johnclary @SurbhiBakshi - any other B-Cycle references you know of? 

Assuming the Knack ones are quickies, are you down to take care of them all at once, Chrispin?

@jaime-mckeown - do you want a separate issue for yours?

**Comment by jaime-mckeown** [comment]
@amenity yes, please.

**Comment by amenity** [comment]
@jaime-mckeown #4212 🗺️
