### ISSUE TITLE
Moped | Make AWS accessible to all devs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4107]
~Create a single Cognito user account and add credentials to 1Password.~
Sergio and Mike are going to pair on getting individual accounts set up.

**Comment by amenity** [comment]
Ultimately will have individual accounts, but this is more complex creating profiles etc...

**Comment by mddilley** [comment]
All devs have accounts in the staging Cognito user pool and can log in to develop locally. I will create accounts in the production user pool, and this is tracked in https://github.com/cityofaustin/atd-data-tech/issues/4183.
