### ISSUE TITLE
Break up Invoicing Reporting by Day

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4112]
Randy does invoicing on a day-by-day basis, so we should show him the total hours for a given day. He'll then add 30 minutes to the beginning and 30 minutes to the end for each of these.

**Comment by SurbhiBakshi** [comment]
discussed a few approaches with @amenity today morning and demo'ed some variations - Group. by Day, Group By Shift, a link in an officer table leading to hours for assignments. Going to go with Group by Shift.
Next Steps
1. Create the Invoice (Group by Shift Label) in Production
2. Show Randy the filter by Officer function
3. Incorporate inline editing for Clock In and Clock Out.
4. Show Randy inline editing for Clock In and Clock Out.
