### ISSUE TITLE
[RPP Back Office] Testing - Am I Eligible Resident Address

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4115]
When entering the Resident Address on the Am I Eligible page the address drop list is displaying International addresses (can't recall if it was doing this before)

**Comment by ChrispinP** [comment]
I double checked all address fields, they are all set to US still. Are you able to take a screenshot of how you are seeing international addresses?

**Comment by moorerst** [comment]
@ChrispinP when typing in the resident address on the permit information page
![image](https://user-images.githubusercontent.com/56606465/95619204-d6e6ec80-0a33-11eb-94c5-04a1855a84bd.png)

**Comment by johnclary** [comment]
I just tested and could not reproduce. May no longer be an issue?
