### ISSUE TITLE
FY21 Fee Bugs ‼

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4120]
### Three reports of 'Error Calculating Fees' on SP & ZC folders

- ATD SP-Site Plan Case Review (Zach Whitaker, DSD)
    - INC0058375
- ATD Zoning Review fee (Adrea Burt, DSD)
    - INC0057771
- ATD- SP Administrative Non-environmental waiver (Sangeeta, ATD)

**Comment by TracyLinder** [comment]
**Email to Andrea & Zach:**

Hello,

You both have submitted Service Now tickets for errors inserting ATD fees on either ZP or ZC folders. I received confirmation from Sam w/ DSD yesterday that he did not cause these errors, so we (ATD) have started working on fixing this today. I will keep you both updated on our progress. 

Thank You,

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - Made changes and DEV commit submitted on 10/12/2020

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  -- Reply from Martin

Hello,

George is out right now and wont be back to the 19th.
I took a look into and seems we had a merge conflict on another commit effecting validlookups. 

I reprocessed it and everything seems good.
Can you please verify and confirm on your side ?

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - If everything works as expected this can be closed.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I sent an email to the Stakeholders (Snageeta, Andria and Zachary Whitaker) stating that this has been fixed on PROD and that they should not be getting errors.
Closing card

> Good Afternoon Everyone,
> 
> Hope you are all doing well. I am reaching out in regards to the FY21 Fee Bug issue. The issue has been resolved according to Martin with the CTM team. He was able to reprocess a commit conflict and that seems to have fixed the problem. 
> 
> In the mean-time, I will close the card/issue out. But if you are getting errors on FEEs, please let us know as soon as you can.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services
> Austin Transportation Department
