### ISSUE TITLE
Update GL on ATD Tech Surcharge

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4121]
### Change GL code for ATD Technology Surcharge (fee code 50174 in AMANDA) from 5125 2400 9100 4187 to  5125 2400 9301 4187 effective immediately.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan we just had this request come in from ATD finance manager. It will need to be high priority along with #4120

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader  - 112b4faba92e DEV Commit submitted on 10/12/2020

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader  - Sree will be working on this.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have sent the deployment to the CM team as a level 2 priority. The task for this is SCTASK0100686

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been deployed to DEV. Next step is UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder, @Nadin-Nader - Changes moved to DEV and tested the same in DEV. Ready for DEV UAT.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have looked this up on DEV and the change is correct:
![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/d2ada2f2-3631-49d3-b848-c5b59ab6037c)

## **Approved for TEST!!🎉**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder - TEST Deployment Plan Submitted on 10/20/2020.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder  I have sent this over to the CM Team for TEST deployment under TASK **SCTASK0101771**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been deployed to TEST and is ready for UAT

**Status:** 
Ready for UAT on TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder i have tested this on test and found that the change was good to go. I believe this is PROD ready unless we need the stakeholders approval


![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/0f63ff4c-ee6d-4cdb-9999-3bc73843babc)

**Comment by TracyLinder** [comment]
### Approved for Prod 🎉

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have sent this to the DevOps team for PROD Deployment under TASK **SCTASK0102232**

**Comment by TracyLinder** [comment]
SCTASK0102232 was promoted to Prod yesterday. I will update the stakeholders; closing ticket.
