### ISSUE TITLE
Add Scope Status to TIA Review Details Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4124]
### Add 'Scope Status' field to TIA Case details, below 'TIA Review Status' field. 

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/e8485e60-ec34-4786-bca2-ab04c8cf26de)

**Comment by ChrispinP** [comment]
Scope Status should now be present of Request Details page and the Case Details page

Ready for Review
