### ISSUE TITLE
Bug: TIA Submission Comment Email Feature

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4127]
### The email feature is not sending the customer an email when option is set to Yes

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/a5bc059f-00f2-41c4-952d-6b9e1a0f9b85)

**Comment by ChrispinP** [comment]
Should be working correctly now after updating submission and email rules. Need to confirm.

Ready for Review

**Comment by ChrispinP** [comment]
no longer an issue, closing
