### ISSUE TITLE
Bug: TIA Mod Attachments Tables

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4128]
- TIA Review Details Attachments Tables: Show all attachments (Scope & TIA Submission)
- Scope Page Attachments & TIA Submittal Attachments Tables: Not populating attachment's

**Comment by TracyLinder** [comment]
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/e25d2287-5538-427c-a313-91fc497fb8d2)

**Comment by ChrispinP** [comment]
Had to rebuild attachment and comment tables after combining attachment and comment objects together into only 2 separate objects. All attachment and comment tables should be displaying correctly. Request Details page will now show all attachment and comments whilst navigating to specific detail page will only show respective comments or attachments, for example the Scope page.

Ready for Review

**Comment by ChrispinP** [comment]
no longer an issue, closing
