### ISSUE TITLE
Project Definition | Update existing New Project mutation to include multiple mutations

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#4130]
For the "New Project" mutation, we will need to identify the related tables impacted by the information being collected in new project and sent to the mutation so we may be able to [add these in as nested inserts.](https://hasura.io/docs/1.0/graphql/core/mutations/multiple-mutations.html)

The entities in the "New Project" workflow that are impacted by the creation of a new project are the following:

- [ ] moped_proj_entities (1:1)
Requires: project_id
- [ ] moped_proj_timeline (1:1)
Requires: project_id
- [ ] moped_proj_financials (1:1)
Requires: project_id
- [ ] moped_proj_phases (1:many)
Requires: project_id, phase_name (from selected phase in "Define Project" phase input)
- [ ] moped_proj_status_history (1:many)
Requires: project_id, status_name (from selected status in "Define Project" status input)
- [ ] moped_proj_dates (1:many)
Requires: project_id, project_date (from selected date in "Define Project" start date input), date_type == "original start date"

**Comment by zappfyllc** [comment]
@sergiogcx [this was one my one concern](https://hasura.io/docs/1.0/graphql/core/guides/data-modelling/one-to-one.html#current-limitations-with-nested-mutations) with nested inserts because we do have foreign key constraints on the 1:1 entities as well. But does this just mean it won't work the opposite way (i.e. inserting timeline before project?), because that isn't as big of a deal to me. We just definitely need the project ID to carry over to the one-to-one relationships listed above in the issue description.

(Maybe we don't need the 1:1 project object decomposition I originally planned for if this makes things too complicated, but I think the use cases for timeline, entities, financials will build enough that it would be ideal to have these separated out to avoid table bloat on the project table.)

**Comment by amenity** [comment]
@zappfyllc - any updates on this? It would be great to wrap up #3159 💝  😉

**Comment by lazavazav** [comment]
Hoping to finish it today
