### ISSUE TITLE
[RPP Back Office] Testing - Permit Information Page Vehicle Information

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4131]
- [x] Getting error message Invalid License Plate when entering a license plate with a hyphen ex. DHY-1234. Should hyphen be allowed? 

- [x] Getting error message license plate is already being used ex. 3452845

What if I purchased permits last year and used the license plate #3452845 will I get this message when I attempt to purchase permits for the new renewal period?

**Comment by ChrispinP** [comment]
Removed License Plate unique value so the same license plate can be entered. A standard license plate can be no longer than 8 characters so spaces should not be included.

**Comment by moorerst** [comment]
@ChrispinP confirmed all these items are complete

**Comment by moorerst** [comment]
like the addition of the Note that details how the license plate should be entered
This issue is complete
