### ISSUE TITLE
Moped | Add tests to user management API

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#4143]
Use Pytest and check out [moto](https://github.com/spulec/moto) to add some test coverage to the Moped user management API.  [moto](https://github.com/spulec/moto) can mock the AWS resources used in the API.

https://docs.pytest.org/en/stable/index.html
https://blog.codecentric.de/en/2020/01/testing-aws-python-code-with-moto/

**Comment by johnclary** [comment]
moto looks great! i've been dreading writing those s3 tests :)

**Comment by amenity** [comment]
Not trying to have full-coverage here.
