### ISSUE TITLE
[RPP Back Office] Testing - Review Page Permit Info

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4161]
- [x] In the example below the 1 Visitor Hang Tag is the 3 permit requested so it should be $30 not $20 

![image](https://user-images.githubusercontent.com/56606465/95999673-bd5eef80-0dfb-11eb-8301-8e640a338187.png)

- [x] Not sure it's necessary to display the Tax Percentage 

- [x] Info in the titles should changed to Information

- [x] Need a Total Cost for all Permits purchased

**Comment by ChrispinP** [comment]
Tax percentage removed, information spelled out and total cost added to page.

**Comment by ChrispinP** [comment]
Combination totals were added so when both decals and hangtags are chosen that they display the correct amounts

**Comment by ChrispinP** [comment]
In addition to percentage, tax amount and subtotals were removed for customer clarity and back-end organization.

complete
