### ISSUE TITLE
Project Listing | Design refinements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4172]
Updated todos:

- [x] Remove time, leave just date for Added and Started
- [x] add "No Data" default if status is missing

Currently in Staging: 
![Screen Shot 2020-12-15 at 2 32 13 PM](https://user-images.githubusercontent.com/1463708/102270249-681a8980-3ee3-11eb-8345-a353686908b2.png)

@sergiogcx 's proposed changes:
![2020-12-15_14-10-41](https://user-images.githubusercontent.com/1463708/102270298-736db500-3ee3-11eb-9b95-cacc09e0aa3d.png)

**Comment by amenity** [comment]
ICYMI... [Changes discussed over Slack](https://austininnovation.slack.com/archives/CNUEPKLB1/p1608063068266100).

**Comment by mateoclarke** [comment]
update the description above based on sync up our convo today

**Comment by mateoclarke** [comment]
Looks like @sergiogcx wrapped this one with these commits:

- https://github.com/cityofaustin/atd-moped/commit/35e29ec7aeaee284dd8382f5c504a26cc133ab7f
- https://github.com/cityofaustin/atd-moped/commit/190fcffc5beef1a1a6c51242f1cdf1fa5f40cea2
