### ISSUE TITLE
Meeting - Service Rotation Retrospective | October 14, 2020

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#4174]
[Retrospective Board - ](https://miro.com/app/board/o9J_ki9iI-o=/)

Action Items - 

- [x]  @SurbhiBakshi  will add documentation on how to access DTS Rotation Calendar and see who is next on rotation, also put information in Slack.
- [x] @SurbhiBakshi will add Geodatapusher time sensitivity to  documentation 
- [x] @jaime-mckeown will ask CTM to cc her on Geodatapusher notifications
- [ ] @JaceDeloney will put in a CTM ticket to address mailbox issues that he and @mddilley experience.
- [x] @SurbhiBakshi will add documentation on what to do when the issue assignee is out of office
- [x] @SurbhiBakshi will add documentation when primary is unsure of who the assignee should be for the service request.

**Comment by jaime-mckeown** [comment]
@SurbhiBakshi only one email is allowed for Geodatapusher. I told Ben to leave it with the transportation.data email since it's shared.

**Comment by SurbhiBakshi** [comment]
@jaime-mckeown - thanks for looking into it!

**Comment by SurbhiBakshi** [comment]
Hi @JaceDeloney - please close this issue if you have put in a Help Desk ticket for the issues you and Mike are experiencing with the inbox.
