### ISSUE TITLE
Project Summary | Create wireframe

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4175]
Wireframe: https://share.balsamiq.com/c/dBZr6MmfNVtkFH5J2A6wLP.png

**Comment by amenity** [comment]
Project Summary

**Comment by amenity** [comment]
@johnclary @zappfyllc - if y'all get a chance, I'd love your eyes on [this wireframe](https://share.balsamiq.com/c/dBZr6MmfNVtkFH5J2A6wLP.png).

**Comment by johnclary** [comment]
Looks good. Thinking it might make sense to status and phase above the description, possibly inline together?

I agree that we should leave the embedded mini-map out of scope for this iteration.
