### ISSUE TITLE
VZE | Location details pages crash in Microsoft Edge 

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#4178]
Xavier reported an issue where location details pages did not load and displayed a blank grey screen in Microsoft Edge. He reported this issue with:
https://visionzero.austin.gov/editor/#/locations/911D0A2B00
and I replicated once in BrowserStack with Windows 10/Microsoft Edge (version 86) with:
https://visionzero.austin.gov/editor/#/locations/9DEC4E6FC6

I was unable to grab screenshots of the console in BrowserStack when the bug was replicated.

Xavier shared the following errors from his machine:
`RangeError: Failed to construct 'TextDecoder': The encoding label provided ('utf8') is invalid.`
`Unhandled promise rejection RangeError: Failed to construct 'TextDecoder': The encoding label provided ('utf8') is invalid.`

The workaround for now is to use Chrome or Firefox to access VZE.

**Comment by JaceDeloney** [comment]
Let's first try and replicate this issue before diving into debugging.

**Comment by tillyw** [comment]
I've attempted to replicate this issue using Edge 86 in Windows 10 on BrowserStack but haven't encountered any errors (I tried both locations listed in the comments along with several others). I also tried with IE11 and surprisingly didn't encounter any errors! I reached out to Xavier to see if he can replicate it again or connect me with someone else who has encountered it, so I will see if that leads anywhere. @JaceDeloney if I'm unable to replicate this issue, what do you think we should do? Thanks!

**Comment by JaceDeloney** [comment]
Thanks @tillyw. If we can't replicate it, I'm fine with closing this out. If it comes up again we can re-open the issue.

**Comment by tillyw** [comment]
Thanks, @JaceDeloney! Please feel free to close it for now, otherwise I can do it or we can do it at the next Backlog Grooming meeting.

**Comment by mateoclarke** [comment]
@tillyw did you try on a Window machine instead of BrowserStack?

Also looks like updating versions of some dependencies might be a quick fix worth trying. Doesn't help us with replicating the issue, but seems harmless to upgrade if nothing breaks.
https://github.com/auth0/auth0-spa-js/issues/316

**Comment by JaceDeloney** [comment]
Unable to replicate and the user that reported this has moved to chrome without experiencing the same issue again. Closing out
