### ISSUE TITLE
Read Only Account CasillasM

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4179]
### Michelle Casillas with Finance needs a read-only AMANDA account. 
- She should already have an AMANDA account; it may be inactive and needs to be updated for current role.

**Comment by TracyLinder** [comment]
**Email to Customer:**

Hi Van & Michelle,

My apologies for the late response to your email. We can get Michelle set up in AMANDA. Below is the info we’ll need:
•	Employee ID #:
•	Name:
•	Title:
•	Email Address:
•	Phone Number:
•	Supervisor Name:

**Comment by Nadin-Nader** [comment]
@TracyLinder I reactivated Michelle's old account with her information and the information from the AMANDA Master User form. I sent her an email with the login information and let her know that the AMANDA automation will create her account on PROD tonight. Moving to review QA until tomorrow then closing if i see she has logged in.

**STATUS:**
Waiting for PROD account to be created and for user to log in.

**Comment by Nadin-Nader** [comment]
User needs access to attachments. I have submitted a TASK to CTM to add her to the necessary groups in Active Directory. The TASK number is **SCTASK0100851** 

**STATUS:**
Waiting on CTM to add user to Active Directory Groups

**Comment by Nadin-Nader** [comment]
Checked to day and it was still not done

**Comment by Nadin-Nader** [comment]
User is now able to log into TEST and PROD and view attachments successfully. Closing card
