### ISSUE TITLE
Create Admin accounts for DTS team

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4183]
An Admin `moped-admin` has permissions to
- Create Editors `moped-editors` and Viewers `moped-viewers`
- Convert existing Editors to Viewers and vice versa
- Update status (e.g. Active/Inactive) of Editors and Viewers

Admin accounts themselves can only be created by devs via direct database access. 

We need Admin accounts for 

#### Staging
- [x] Mateo
- [x] Sergio
- [x] Mike
- [x] Tilly
- [x] Leslie
- [x] JD
- [x] John
- [x] Amenity

#### Production
- [x] Mateo
- [x] Sergio
- [x] Mike
- [x] Tilly
- [x] Leslie
- [x] JD
- [x] John
- [x] Amenity

**Comment by mddilley** [comment]
Will create production accounts using the enhanced user management API and user UI in moped editor once completed.

**Comment by amenity** [comment]
The tike has come! We're going to start demoing and sending users to Production, so we'll want to take care of this.

**Comment by mddilley** [comment]
I tripped over a small bug in the production Moped API while creating the production accounts above. The endpoint set for the API to POST to the production Hasura instance needed a small update. Sergio and I paired on patching this up, and all production admin accounts above are now created. Closing.
