### ISSUE TITLE
Make Sample Data for Lewis, Josh

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#419]
We need to create a data sample that includes
- [ ] 100 rows for
     - [ ] Crashes
     - [ ] Person
     - [ ] Charges
     - [ ] Units
- [ ] Export to Excel

@johnclary @mateoclarke does this sound accurate?

**Comment by johnclary** [comment]
Closed. See also [#67](Done. See also [#67](https://github.com/cityofaustin/atd-vz-data/issues/67)
