### ISSUE TITLE
[RPP Back Office] Testing - Application Summary

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4190]
**Applicant Information** - no issues
Confirmed: required fields , Questions email address, Spanish form. There is a delay when select Save & Continue

**Permit Information** - 
Confirmed: Look up address, RPP Eligibility Listing, information links, license plate display correctly based on permits selected
- if I save without a license plate # error message Invalid Plate # Check Accuracy - should this message have different language? 

**Required Documents** - no issues

**Permit Info** - would like to review how the cost is being calculated. 
I think the total should be $142.48 based on the screenshot below: (total count of permits is 4 total cost $110 + 32.48 = $142.48)
![image](https://user-images.githubusercontent.com/56606465/96375913-8d885280-1141-11eb-815c-5b1feeb537e0.png)

Suggest Permit Bundle Cost be changed to Total Permit Cost

Application Invoice Page - no issues

**Comment by moorerst** [comment]
Sorry in the example above I forgot the tax on the 4 permits
110 + 9.07 = 119.09 + 32.48 = $151.55 total

I confirmed the total cost for 2 decals, 2 hang tags and 6 day passes with the RPP team:
It’s going to be $151.55 with tax included ($119.08 for 4 permits and $32.47 for 6 passes).

Thanks,
Daniil Kontsevoy

**Comment by ChrispinP** [comment]
updating license plate error messaging, total cost calculations, and adding language for submit/save delay

**Comment by ChrispinP** [comment]
Review page language, view order, equations, and costs updated. complete
