### ISSUE TITLE
[RPP Back Office] Testing - Email Notifications

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4191]
Have the email notifications been reconfigured?

**Comment by ChrispinP** [comment]
Email notification added for Application submission

**Comment by moorerst** [comment]
There is also a email notification for Reviewed & Approved - Pending Payment

**Comment by ChrispinP** [comment]
that email is triggered by a status change by RPP staff. Link may need to be updated once new application is live since url's need to be updated.

**Comment by moorerst** [comment]
The Submitted Date is not populating on the Submitted - Pending Review email

Your Residential Parking Permit Application was submitted on {SUBMITTED DATE} for this address 2800 SALADO STREET
AUSTIN, TX 78705. Your application is Pending - Review by the Austin Transportation Department (ATD).

**Comment by moorerst** [comment]
Submitted Date is now populating.

- [ ] Can we display the date only and not the time?

- [ ] The link in the email notification to view a copy of the Invoice is not directing to the Invoice page. It's directing here:  

https://atd.knack.com/parking#

**Comment by ChrispinP** [comment]
For this we would need to create a new field that only sets date and not time just for the customer since have both date and time is important for the backend.

The link is directing to the in production app which should be correct once we push the construction environment to production.

**Comment by ChrispinP** [comment]
Invoice link was corrected. Emails updated. please review

**Comment by moorerst** [comment]
@ChrispinP invoice links in both Submitted and Reviewed/Approved email notifications are displaying correctly.

**Comment by moorerst** [comment]
complete
