### ISSUE TITLE
DTS Spring 2021 Retreat and Strategic Planning

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4202]
- [Miro board](https://miro.com/app/board/o9J_lP-Ptfg=/)
- [Agenda](https://docs.google.com/document/d/1fUtahlgjYPioWxu6n-ijsqWw-xsBypIN_rL8bdYc2VI/edit)

**Comment by johnclary** [comment]
closing but will leave #5644 open
