### ISSUE TITLE
Take Strengthsfinder 💪🧠

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4204]
Take [Strengthsfinder](https://www.gallup.com/cliftonstrengths/en/252137/home.aspx) and email results to Amenity. 

- [x] Mike
- [x] Sergio
- [x] Tilly
- [x] Surbhi
- [x] Stephanie
- [x] Jace
- [x] Nate
- [x] Chrispin

**Comment by amenity** [comment]
All y'all will be getting links and instructions once the PR goes through.

**Comment by amenity** [comment]
@JaceDeloney @SurbhiBakshi @moorerst @tylerwhitson @sergiogcx @mddilley @Nadin-Nader @ChrispinP - y'all should get an email with a link to take your test. Please forward/share your results with me when you've completed it! 

Not a giant rush, but would be great to get done before the Product Offsite (11/5; Jace + Stephanie) and DTS Team Retreat (11/9). :)

**Comment by SurbhiBakshi** [comment]
@amenity - got the email!

**Comment by Nadin-Nader** [comment]
@amenity I sent you the results

**Comment by mddilley** [comment]
@amenity I completed mine today and will send you the report.

**Comment by SurbhiBakshi** [comment]
@amenity - completed mine today and shared the report with you.

**Comment by JaceDeloney** [comment]
@amenity - Forwarded the results 

![K8L6TghEG5FT](https://user-images.githubusercontent.com/10567316/97362142-8f06f880-186e-11eb-8250-6ccf9954953f.gif)

**Comment by ChrispinP** [comment]
I took my assessment today but didnt get any results. I thought maybe you got the results automatically.

**Comment by SurbhiBakshi** [comment]
@ChrispinP - it looked like that to me as well! When I logged in again, I could see the results.

**Comment by amenity** [comment]
Thanks, y'all. @mddilley @sergiogcx @SurbhiBakshi @Nadin-Nader @JaceDeloney I can see all y'all's results in the system like a creeper, so no need to send if you haven't yet.

**Comment by moorerst** [comment]
@amenity I have the email I will complete the assessment on Thursday 10/29

**Comment by moorerst** [comment]
completed assessment and emailed results to @amenity
