### ISSUE TITLE
[RPP Back Office] Testing - Applicant Menu

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4210]
- [x] Organize the Application Menu - all the links has been tested 

Am I Eligible
Rules and Guidelines
Permit Cost
Single Use Day Pass Cost
Payment Options
Get Started
Survey
FAQ
Contact Us

- [x] Duplicate Apply buttons

**Comment by ChrispinP** [comment]
Multiple apply buttons (applications) are there just during the build phase, they are old builds. Once they are no longer needed they will be removed. application menu will be updated accordingly thereafter.

**Comment by ChrispinP** [comment]
Steph, can you confirm that the order you listed the pages above is the exact order for the Applicant Menu we or RPP Staff want. Maybe review with them if they like the current order of the menu or if they would like something moved up or down.

Make sure they are directed to in construction app [RPP Portal under Construction](https://atd.knack.com/residential-parking-permits-rpp--new-prod-copy--21-oct-2020#rpp2/)

**Comment by ChrispinP** [comment]
Leaving menu as is for now, tested links and pages, all seems to be well.
