### ISSUE TITLE
Update "B-Cycle" to "Metrobike" in GIS realm

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4212]
Changed Name of Feature Layer and Service Definition.

**Comment by amenity** [comment]
@jaime-mckeown - not high priority at all. :)

**Comment by amenity** [comment]
@jaime-mckeown - please close #4015 when y'all get time to take care of this.

**Comment by jaime-mckeown** [comment]
@amenity is this still a low priority?

**Comment by amenity** [comment]
@jaime-mckeown low as can be. :) I'm just gonna stick the epic back in the Backlog assuming it will be a while. Will you add an estimate?

**Comment by jaime-mckeown** [comment]
Feature layer and Service Definition updated in AGOL.
