### ISSUE TITLE
Update "B-Cycle" to "Metrobike" in Knack apps

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4213]
- [x] <strike>B-Cycle Form (ATD Forms)</strike> - _ATD Forms doesn't have B-Cycle, just Bike Share and Bike Parking_
- [x] Data Tracker 
- [x] Socrata Open Data Portal

**Comment by amenity** [comment]
@dianamartin will look at this and do it only if it's a 1. 😄

**Comment by dianamartin** [comment]
- [ ] object table: `bcycle_kiosk_locations`
- [ ] button: `bcycle_kiosk_locations`
- [ ] page header: ` B-Cycle Kiosk Locations`
- [ ] button on the page: `Add B-Cycle Kiosk Location`

**Comment by dianamartin** [comment]
## Bcycle Dataset -  Refresh

- [ ] Data set 1: https://data.austintexas.gov/Transportation-and-Mobility/Austin-B-Cycle-Kiosk-Locations/qd73-bsdg
- [ ] Data set 2: https://data.austintexas.gov/Transportation-and-Mobility/Austin-B-Cycle-Trips/tyfh-5r8s

**Comment by dianamartin** [comment]
@ChrispinP @johnclary @SurbhiBakshi Would you like to review the changes where all "B-Cycle" used to be before I closed this issue?

**Comment by amenity** [comment]
@SurbhiBakshi - please check :)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/74a77202-3c84-43b0-a4c7-7d0f432a1763)

**Comment by dianamartin** [comment]
@SurbhiBakshi thanks, I'll correct it

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/bc126962-20ed-4298-aff8-54ce8e3a64cf)

**Comment by SurbhiBakshi** [comment]
@dianamartin - I corrected both since I am already in

**Comment by dianamartin** [comment]
#### Change the following:
- [ ] Details form header
- [ ] Edit form header
