### ISSUE TITLE
CTN Deep-Dive

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4221]
@alan-deanda plz schedule

**Comment by alan-deanda** [comment]
Create Issues for:

- [ ] Setting up a change notification from the street.segment centerlines to incorporate updates into CTN's ID fields
- [ ] Set up the CTN in a network dataset to analyze for topology, set elevation field
- [ ] Determine field tables by category, and note on priority and feasibility.

**Comment by jaime-mckeown** [comment]
@alan-deanda are you going to create an Epic for this?

**Comment by alan-deanda** [comment]
@jaime-mckeown  they're all in #394 now, I've turned that issue into an Epic
