### ISSUE TITLE
Add "Common Name" to inventory item from Inventory Control Form

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4223]
AMD has asked that the item "Name" field in the Data Tracker [object_15](https://builder.knack.com/atd/amd#data/object_15) match the item names on the ICF, [see this list](https://app.zenhub.com/files/140626918/e74d89a0-c2c1-4fb7-90c0-240cb22d40c7/download)

**Comment by dianamartin** [comment]
Found that there are new records on the ICF for cameras (different sizes, ex. 6mm, 8mm..), not sure if I should add them. When I talked to John he said we can't add the same `inventory item` with the same `Stock#`, so we'll have to bring it up in the next Inventory Check-In meeting next 10/27.

**Comment by dianamartin** [comment]
@johnclary There are also items on the `inventory_items` list that aren't on the ICF, do we keep those or put their status as "inactive"?

**Comment by johnclary** [comment]
@dianamartin please leave those items as-is for now. Will need to review entire list with ray/johnny/van

**Comment by dianamartin** [comment]
In our AMD Inventory Check-in meeting, AMD Staff said they'd like to look over the inventory item names. If changes are necessary they'll reach out to the AMD inventory planner staff.
