### ISSUE TITLE
[RPP Back Office] Testing - Review Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4225]
Suggestions from RPP team testing

- [x] change Combined cost or Cost to “Permit Base Costs" for both the Decal/Hang-tags & Day passes to keep it consistent. 

- [x]  put the ‘Permit Bundle information’ after the Decal/hang-tag & Day pass information, and title it ‘Total Permit Costs’

**Comment by ChrispinP** [comment]
completed for review

**Comment by moorerst** [comment]
RPP team has reviewed and approved - closing this issue
