### ISSUE TITLE
[RPP Back Office] Testing - Payment Options Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4230]
Per RPP Team 
There’s been changes to our office hours. 

- [x] Under Payment Hours can we change to – Monday – Friday: 8am – 3pm.  

- [x] The phone # for payment under ‘Payment Options’ can change to 512-974-7828.

- [x] Under “In Person payment”  change the days & hours to Monday – Friday: 8am – 3pm. 

- [x] Add in ‘By appointment only’  

- [x] At the bottom of the page under Permitting Office  change the day & hours to Monday – Friday: 8am – 3pm and phone # to 512-974-7828

**Comment by ChrispinP** [comment]
completed for review

**Comment by moorerst** [comment]
RPP staff has reviewed and approved - closing this issue
