### ISSUE TITLE
[RPP Back Office] Testing - Application Invoice Page 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4233]
- [ ] There are 2 values populating for permit count under Permit Information. It displays correctly on the Review Application page 

![image](https://user-images.githubusercontent.com/56606465/96750315-6f189600-1391-11eb-8467-d6c4715cc255.png)

**Comment by ChrispinP** [comment]
Possible bug, we should try to replicate. No issues on the records.

**Comment by moorerst** [comment]
we can close this I could not reproduce the issue

**Comment by ChrispinP** [comment]
copy that. closing, no action taken.
