### ISSUE TITLE
Knack Training for Nate N.

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4235]
Starting Monday, Nov 23.

Found [training plan](https://docs.google.com/spreadsheets/d/1rfyMC0SbFb_JKrMxXcY10s4sFKf9y002ZBgw8GPIt_c/edit?usp=sharing) for IT App Analyst

**Comment by johnclary** [comment]
@dianamartin @SurbhiBakshi can you help set up a training plan for Nate?

**Comment by SurbhiBakshi** [comment]
@johnclary - sounds good, @dianamartin will set up some time with you to discuss.

**Comment by SurbhiBakshi** [comment]
@dianamartin - meeting scheduled for 10/23

**Comment by SurbhiBakshi** [comment]
[Reworked Chrispin's plan](https://docs.google.com/spreadsheets/d/1rfyMC0SbFb_JKrMxXcY10s4sFKf9y002ZBgw8GPIt_c/edit?usp=sharing)

**Comment by amenity** [comment]
@Nadin-Nader attended the #4142 and debrief. Will pick up training again in Sprint 38.

**Comment by amenity** [comment]
@ChrispinP - please check with @Nadin-Nader to see how it makes sense to proceed.

**Comment by ChrispinP** [comment]
Added Nate to the Knack Slack channel.

**Comment by ChrispinP** [comment]
Made sure Nate was setup with Knack and 1Password yesterday so he can begin working in his Sandbox. I have scheduled some shadow time if Nate is available. Webinar is also scheduled for next week. I spent some time talking about some of the basic functionality and structure of Knack in relation to his sandbox and the existing RPP application.

**Comment by johnclary** [comment]
Meeting with Chrispin today to review sandbox work.

**Comment by ChrispinP** [comment]
Had Nate attend the new builder Webinar yesterday and spent a couple hours working together on some simple issues and having him shadow some of my TIA Module work on creating a new page linked from a menu with multiple tables, forms, and record rules.

**Comment by johnclary** [comment]
Nate is occupied with v7 UAT at the moment. Moving to blocked

**Comment by ChrispinP** [comment]
following up with Nate on Friday the 8th or Monday as his time allows

**Comment by ChrispinP** [comment]
The Amanda release has been delayed again and Nate is focused on that work currently. Will resume sandbox review and any further training later in Feb.

**Comment by amenity** [comment]
Since @Nadin-Nader is taking on a ton of AMANDA responsibly now, closing this. Will continue to include him as optional in Apps Planning/Grooming.
