### ISSUE TITLE
[Feature] Ability to add file attachments to work order

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4237]
From Ivonne (construction services group):
> Sometimes requests come from contractors bringing a check to pay for items (and sometimes labor) -- could there be options to add attachments to that work ticket for maybe copy of check or cost estimate PDF?

**Comment by amenity** [comment]
@johnclary - were you planning to take care of this yourself?

**Comment by johnclary** [comment]
I'm going to backlog this. There's an open question of which attachments belong on a signal asset vs a work order, and i see some overlap with project tracking as well.

**Comment by dianamartin** [comment]
this was configured in the `TEST | Austin Transportation Data Tracker | 27 OCT 2021` environment, needs to migrated to Prod Development area

## Page Menu
![image](https://user-images.githubusercontent.com/21112975/161573785-6d78379a-d404-492a-ade8-25b18701e3b7.png)

## Form
![image](https://user-images.githubusercontent.com/21112975/161573892-15dc1b62-5607-41fc-8ad0-43b409a95481.png)

## Attachments Table
![image](https://user-images.githubusercontent.com/21112975/161582298-09de9000-33cb-4cf7-ad3f-b576f5deb92b.png)

**Comment by dianamartin** [comment]
This has will be addressed by issue #8762
