### ISSUE TITLE
[RPP Back Office] Testing - Permit Information Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4238]
Per RPP team 
On the Permit Costs page under Permit information can we put the breakdown to show the costs that include not only the breakdown of the order, but also if purchasing multiples like this example that Daniil created. 

Example:  
![image](https://user-images.githubusercontent.com/56606465/96757554-341b6000-139b-11eb-8fd1-f14122667aa2.png)

**Comment by ChrispinP** [comment]
completed for review

**Comment by moorerst** [comment]
reviewed - this is complete closing issue

**Comment by moorerst** [comment]
From the Permit Information Page when I select the information icons for each of the permits I'm not seeing the updated Permit Cost breakdown

**Comment by ChrispinP** [comment]
Heres the link for the updated page currently: [Permit Info](https://builder.knack.com/atd/residential-parking-permits-rpp--new-prod-copy--21-oct-2020#pages/scene_154/views/view_449)

**Comment by ChrispinP** [comment]
Permits Cost accurately reflected now on production app
