### ISSUE TITLE
Consider changes to labeling labeling scheme

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4240]
I propose replacing the `Index` label with a `Project` and `Product` label, with different templates for each. The `Project` issue would be very similar to the `Index` issue template today, with some tweaks to make data capture easier on the new [product website](http://atd-product.netlify.app/).

The new `Product` issue would capture the core information about each product we support. E.g. a description of what the product, a link to the login page, wiki, etc.

There should be a 1:1 match between `Product` issues and `Product: xyz` labels.

There should be a 1:1 match between `Project` issues and `Project: xyz` labels (_for projects which have been scooped_)

**Comment by amenity** [comment]
@johnclary - good stuff! 😅  I started to write questions, but I think maybe talking in person would be more efficient... And, if you have the stomach for it, we might want to take a look at it in the context of our [Product Delivery Workflow](https://atd-dts.gitbook.io/wiki/product-ops/product-delivery-workflow) and definitely [this issue](https://github.com/cityofaustin/atd-data-tech/issues/1435). 

Potentially an (optional?) part of the Product #3722 ...

**Comment by amenity** [comment]
@johnclary — I think we can close this? I created [this issue to update docs](https://github.com/cityofaustin/atd-data-tech/issues/4506).

**Comment by johnclary** [comment]
Agreed. Closed. Thanks.
