### ISSUE TITLE
Moped | Editor | Implement User table

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4242]
Add a table to list users stored in the DB. 

See https://balsamiq.cloud/senhupm/p9y6tuy/r8865 for wireframe

**Comment by amenity** [comment]
@mddilley - create sub-issues as helpful.🙏

**Comment by mddilley** [comment]
This issue closed with https://github.com/cityofaustin/atd-moped/pull/105. It will be merged to `main` along with the Devias template branch.
