### ISSUE TITLE
Run a spatial join of trips data to voting locations

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4247]
We have been asked to do some analysis for the Shared Mobility Team that shows scooter trips that were used to get to voting locations during the Summer 2020 election. 

I have already shared the file that contains all of the trip data, as well as the polygons shapefile.

**Output Requirements:**
- [x] Export a flat file that includes the subset of trips that either have an origin or destination within a voting location polygon

**Comment by jaime-mckeown** [comment]
- Created 2 separate Spreadsheets for Start and Stop trips.
- Imported tables, created points, projected to State Plane.
- Updated fields to match and merged into one point layer.
- Spatial Join between Polling locations buffer with a one to many join, only keep matching features with an intersect.
- Initial Polling location buffer layer contained 100 locations, only 15 locations intersected with start/end trips, with 1,739 total joins.
- Create table export and send to Jace.
