### ISSUE TITLE
Enable COACD button on VZA login URLs, add fancy buttons, and document process

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#4251]
Description below copied from parent issue

**Comment by SurbhiBakshi** [comment]
If I log out, or trying to access a valid URL (e.g. https://atd.knack.com/vza#my-assignments/) without being logged in, the login screen I get is missing the "Sign in with COACD" button.

Apps to check:

 
 VZA [Surbhi]

URL tested: https://atd.knack.com/vza#my-assignments/assignment-details/5f3db2b4911f490a5ab49321/

Open URL on Browserstack

Property	Value
Device	iPhone XR
Browser	Mobile_safari
Operating System	iOS 12.0
Resolution	828 x 1792 px
Screen size	6.1 in - 2.56 x 5.54 in
Viewport	414 x 896 dp
Aspect Ratio	19.5 : 9

**Comment by amenity** [comment]
@SurbhiBakshi is going to test this when it's in VZA Production, @mddilley

**Comment by SurbhiBakshi** [comment]
@mddilley , @amenity - Test production and it works great, thanks @mddilley!
