### ISSUE TITLE
ROW Performance Measure, Update 3 (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4255]
### Updates:
- Pull subcode null values
- Exclude from EX metrics the subtype Corridor Program Office
- Update with ne Subs but still Exclude CPO
See #3465 & #1872

**Comment by TracyLinder** [comment]
### Bug Report from Paloma

![Screen Shot 2021-05-26 at 3.32.50 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/42750218-3dc0-4b89-9981-b441b1ee07de)

![Screen Shot 2021-05-26 at 3.34.30 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/dbc91ecc-ed2a-45f4-8251-8ff362534fbf)


![Screen Shot 2021-05-26 at 3.34.52 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/987a1850-140a-416a-a4a0-244a9b1c3b1c)

**Comment by Nadin-Nader** [comment]
Need to research and find out what causing the difference in results

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan below is the Report from PROD with the same date Range.

[https://app.zenhub.com/files/140626918/e9697a68-f3cf-4936-aa70-1fb00bc12dba/download](https://app.zenhub.com/files/140626918/e9697a68-f3cf-4936-aa70-1fb00bc12dba/download)

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder  - Sent DEV Commit on 06/23/2021, here is the commit ID : 2b549e5b5f11

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  I have sent this to the DevOps team to promote to DEV under **SCTASK0147418**


**Status:**
Waiting on CM Team to deploy to DEV

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this was deployed to DEV on 6/28/21 by Martin. I am going to UAT on DEV but please test it as well.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - I did DEV UAT on this and it is working as expected, upon your approval this can be moved to TEST. 

Now we can see the Subcode NULL value like this below.

![image](https://user-images.githubusercontent.com/44907715/124023949-34510e00-d9b4-11eb-9be8-197573345f50.png)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan lets get this to TEST when you are ready

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - TEST DP Sent today (07/01/2021)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan sent to DevOps CM Team for TEST deployment under **SCTASK0149079**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to TEST

**Comment by Nadin-Nader** [comment]
**STATUS:**

Ready for UAT on TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan We will need to update the Subs this is looking at since they changed. Then we can UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - I have tested in TEST Environment its working as expected. I can see the null values like below and also EX-Corridor Program Office has 1 Submitted record which is not appearing in report. Both AC met. Kindly review and this is ready for PROD Deployment.

![image](https://user-images.githubusercontent.com/44907715/125129731-8507eb80-e0c5-11eb-8838-cecd048e1194.png)

**Comment by Nadin-Nader** [comment]
@Nadin-Nader send to CTM for PROD once you get DP

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - PROD Deployment plan sent and here is the commit id: 2b549e5b5f11

**Comment by Nadin-Nader** [comment]
**Status:**

Sent to DevOps CM Team to deploy this to PROD under **SCTASK0152096**

**Comment by Nadin-Nader** [comment]
This has been deployed to PROD

**Comment by TracyLinder** [comment]
No issues have been reported to-date. Closing. 
**Good work team**
