### ISSUE TITLE
[RPP Back Office] Testing - Format Review Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4257]
Comments from team testing

- [x] Some suggestions for the Review Application page. Replace ‘Information’ with ‘Cost’. 

- [x] Make the reported fields uniform - use the same number of columns or arrange the same way for all.

- [x] RPP REVIEW APPLICATION PAGE (Proposed Reorder of sections)

Applicant Information
Resident Decal Cost
Visitor Hangtag Cost
Day Pass Cost
Permit Information: is where the totals should be
Total Permit Costs
Vehicle Information
Required Documents
Submit Residential Parking Permit Application
Instructions 1-4: should be smaller text

Confirm updates with Surbhi and Diana

**Comment by ChrispinP** [comment]
Information language was changed to Cost for cost sections. Costs aligned right in 3rd column.

Finalize Application (Submit RPP App) section header changed from H1 to H2. Required documents moved under Vehicle Info. Remove Permit Address Information section, moved permit totals with Total Costs and move address to Applicant Info.

complete
