### ISSUE TITLE
[RPP Back Office] Testing - Format Headings

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4258]
Comments from team testing

- [x] Link to invoice and application status, which is sent in the email is still directed to the old app, but shows the maintenance message. - we are aware of this issue this should redirect properly when application is moved into production

- [x] The H1 headers all look the same, not visual hierarchy. Lots of places my eyes are looking, page doesn't read easily.

Confirm updates with Surbhi and Diana

**Comment by ChrispinP** [comment]
Once app goes live, should double check email link to make sure working as intended. No action needed right now.

Headers for all sections except Rich Text are H2 headers. There should be an obvious break between sections but Im not familiar with any sort of hierarchy needed with certain headers being bigger or smaller than others. Is there anything that could visually look better without being distracting? Should review.

**Comment by ChrispinP** [comment]
Links verified/updated and emails updated. Headings should be good.
