### ISSUE TITLE
Setup Knack Master Agreement for Next Renewal Period

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4267]
Our current contract ends in May 2021. Let's get this started in February.

**Comment by amenity** [comment]
@johnclary - should we get to this?

**Comment by johnclary** [comment]
@dianamartin would you mind taking the lead on this? I will walk you through it all. We negotiated through a contract last fall, so this should be pretty straightforward, and will involve getting a master agreement in place.

Once we have a quote from Knack, the next step is to create an ATD purchase request and a CTM purchase request. I copied you on my request for a quote. Let's chat once we have that.

**Comment by amenity** [comment]
Waiting for Stee to get us the new agreement.

**Comment by dianamartin** [comment]
Just received the quote from Steve and will create an ATD PR. @johnclary How do you create a CTM PR?

**Comment by dianamartin** [comment]
- Created CTM Ticket for Purchase #`REQ0075777`
- Created PR #`2021-02-2363`
- Began open dialogue with Ken B. to ask about RQM process. He said that a RQM can take up to 3-4 months and our timeline is shorter than that. He recommended we pursue a 1 year purchase and then next year try for a multi-year contract agreement. 
- Steve submitted muti-year quote, I attached it to PR
- Gave Steve go ahead for verbiage on exclusive provider letter that ATD Finance and CTM Finance is requesting

**Comment by dianamartin** [comment]
- Ken had us review a document and I made the appropriate changes to remove "upgrade" in the language. Also made sure he was aware we wanted a 24 month base and 2 - 12 month renewal options. 
- Emailed Steve to request a new quote, I haven't heard back from him on it

**Comment by dianamartin** [comment]
Set a reminder for 3/8 to follow-up with Steve on new quote

**Comment by dianamartin** [comment]
Emailed Steve this morning (3/18) to remind him that I send him and email last Thursday and I had a clarification question

**Comment by dianamartin** [comment]
- Received email from Steve with the 2 options on quotes. 
- Emailed Ken to confirm which option we're going with so I can request a new quote from Steve. 

Next Steps
- Request new quote from Steve
- Ken to draft COE,
- I sign
- Get Peggy to Sign
- Turn in COE to CTM

**Comment by dianamartin** [comment]
Emailed Ken on 3/18
>Asked him about which option we should be doing. 
>Let me know which option we’re doing and I’ll request the quote from them. It’s my understanding we’re still going to do the 24 month + 2 yr option.

**Comment by dianamartin** [comment]
- Ken and I sync'd on 3/22, said we'd pursue 24 month, 2 year option. 
- replied to email he originally sent saying we talked on Teams
- I emailed Steve about the plan and requested a quote for 24 month, 2 year option

**Next Steps**
- Ken will update COE once quote is received
- I need to sign COE, Peggy to sign
- CTM still waiting for signed COE

**Comment by dianamartin** [comment]
- Peggy made some minor changes to COE explanation section, signed COE and returned
- I emailed David B. and attached signed COE

**Comment by dianamartin** [comment]
Checked ServiceNow for update
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/a0865057-f3c1-4ca9-805d-a38829bb45ce)

**Comment by dianamartin** [comment]
Checked my emails and noticed I got this on 3/31
>Status: `Pending Purchase`
Assigned Group: `IT_PURCHASING`

**Comment by dianamartin** [comment]
Gil Z. (CTM) emailed me about the quote, to get clarification
>In the purchase request, it is indicated we are to pay out $ the amount for one year. However, in the attached quote it looks like we are to pay for 2 years in advance with the option for a second 2-year purchase. Is that your understanding?

I replied
>Great timing, I was going to email you but you emailed first. Yes, it is my understanding we are pursing a 2 year contract up front with a 2 year option for renewal. 

Steve also emailed 4/22
>Just a heads-up that we're just over a month out from the renewal date of May 31, 2021. Anything I can help with, please let me know.

I replied
>I think we’re still on track for a May timeline, it’s in the hands of our Central IT Purchasing group now. They’re currently working on it, I got an email today about it.

**Comment by dianamartin** [comment]
5/12
Gil from CTM emailed
>Hi Diana and Ken,

>Can you please complete the attached Contract Hand-Off worksheet?
I need this completed in order to finalize the MA.

**Comment by dianamartin** [comment]
@johnclary FYI

5/19 Emailed Gil
>My supervisor is asking what the status for this request is now that Ken provided the Contract Hand-Off worksheet? 

Checked ServiceNow status 5/20
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/7f906aa3-7843-4cae-bc37-7fd799364f4e)

**Comment by dianamartin** [comment]
Steve emailed 5/24
>Good afternoon! 

>The agreement has been executed so at this stage we are only awaiting the purchase order number.
If any other information is required please let me know.

>Thanks, 
 Steve

**Comment by dianamartin** [comment]
I replied
>Hi Steve, 

>Thanks for the update. I believe Gil will be in touch with the purchase order number at some point. I’m not entirely familiar with this step. I’ll let you know if we need anything else. 

>Thanks!

**Comment by dianamartin** [comment]
My CTM ticket update 5/12

>Submitted By: David B.
On Behalf of: Diana M.
Status: Purchased
 
Business Justification: Request for new Multi Year Contract - RQM is `2400 21030100426`.

**Comment by dianamartin** [comment]
Emailed with Ken this morning 6/14
>I reached out to Gil last week and he told me that the purchase order is issued out by ATD. I know you were out last week, but is there any way to issue this purchase order out soon? The vendor is asking about processing this soon. 
•	Gill said the contract number is MA 2400 NS210000051
Let me know if there’s anything that we can do to help expedite this. 

K
>what’s the PR # for this request in Knack?

D
>PR # `2021-02-2363`

K
>Working on the DO now.  Can you double check the FDU?  I get a “Budget not found” error for `.... 8784-7580`

J
>Please use: `... 8782-6388`

K
>Attached is the DO for 2021-02-2363.  John I changed it to your FDU.  Please pass along to your vendor contact and let me know if you have any questions.

**Comment by dianamartin** [comment]
Steve emailed on 6/15
>I appreciate the update and the PO. Just to make sure I understand the PO correctly; you are opting for a "single year" term vs a 2 year discounted term, right? Totally fine, just wanted to make sure.

I talked to John and it seemed like the PR wasn't exactly right. Go a hold of Ken to fix.

Emailed Ken 6/15
>I talked to John and was wondering if you’d be able to update the DO that you created for $20,475 to reflect the vendor quote of payment upfront for the first 2 years, $36,855. Wouldn’t it still fall within the amount guidelines?

Ken 
>I can change the DO to the below amount; I just went by the dollar amount listed on the PR, and will need to adjust that amount on the PR for Accounts Payable.  Is there a way to reopen it?  I can make all the adjustments once it’s open. PR is 2021-02-2363.

Diana
>I reopened the PR 2021-02-2363, you should be able to adjust the line item and amount in the PR.

**Comment by dianamartin** [comment]
Steve replied 6/17
>Thanks Diana, I believe everything looks good. If Liz has questions I will let you know, but we'll get this processed and an invoice out asap.

**Comment by johnclary** [comment]
thanks @dianamartin!!!!!!!
