### ISSUE TITLE
Meeting: AMD Traffic Signal Scoring Changes

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4269]
### Objective 
Talk about how 2020 Evaluations and scoring have changed. What changes AMD would like to make on the Open Data Portal, AMD Dashboard, Data Tracker.

### Participants
Jen, Renee, Brian C., John, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

File Shared
[https://app.zenhub.com/files/140626918/084c9de6-b02c-4fac-a2af-a6250ac2ff7b/download](https://app.zenhub.com/files/140626918/084c9de6-b02c-4fac-a2af-a6250ac2ff7b/download)

[Dup 7241?](https://github.com/cityofaustin/atd-data-tech/issues/4271)

**Comment by dianamartin** [comment]
### Diana's Notes

Limit number of requests that move forward year to year 

Scoring didn't have a cap on it
Locations with crashes got higher scoring
Max Score of 100

No observations this year - covid impacts to traffic volumes and traffic patterns (2021)

2020 Scores will be different

### 2019 EVALUATIONS
180 requests, some don't score very high

Don't see the value in increasing the locations. They have the ability to monitor location and their crashes. 

**Questions:** 
Do we have status for active locations, traffic locations

**Add new status:** 
Has been looked at, will evaluate every new request
- Reviewed 
- Consider locations that rank high
- Identified for study

**Possible Status**
BACKLOG
ARCHIVED

Will need to update website wording 

Dashboard & Open Data portal

Putting together a ranked list
Recommended PHBs & Signals - ranked list (annually)
(If we had funding, ignoring all other factors)

### TO DO
AMD will creating PDF of the recommended and ranked signals and pdf - upload to city website 
AMD will give us link to use to post to dashboard page

### Changes to Signal Request Dashboard
- remove Map
- remove List
- Update text copy

### Changes to Open Data Portal 
- Cleaning up Signal PHB Request (Traffic Evaluations)

### Changes to Data Tracker
- Renee will update Signal Requests - add traffic evaluations for 2020 for ones that are to remain
- Remaining locations/evaluations will be "Archived"

**Comment by dianamartin** [comment]
@johnclary you can add your notes here

**Comment by amenity** [comment]
@dianamartin - please create issues for implementation steps you outlined above and add to #2785 🙏
