### ISSUE TITLE
Project: Digitize Vacancy Tracking and Reporting

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#427]
Digitizing vacancy tracking will provide Human Resources with a streamlined and efficient process for pulling required reports and will provide more transparency into the process for management. 

## Background

Reporting on vacancies is a requirement for all departments in the City and in the process of merging legacy Public Works and legacy Austin Transportation, HR realized each department had different formats for reporting vacancies. Legacy Austin Transportation was using SharePoint to manage it, but it wasn't conductive for sharing out. 

HR needs the ability for HR Staff to update the vacancy report and maintain privacy, while also sharing out some of the information to Assistant Directors, Managers, and Supervisors so they can see statuses of positions they are responsible for. Data and Technology Services needs a high level view of the report for forecasting expected new hires and preparing IT technology procurement (buying computers) in advance of hiring new staff.

## Scope & Deliverables

We are delivering a new application, called TPW HiRe, that includes a page for Human Resource Advisors to manage vacancies they are assigned to. This feature tracks the vacancy status, milestones achieved, and reports on the number of days vacant. 

The application then has reporting pages designed for specific uses. This includes a report that's sent to the City Manager's Office weekly, a report that the Tech Services team can access to prepare technology needs for new hires, and a report that Hiring Mangers and Management can check statuses of vacancies. 

## Desired Outcomes

Streamlined processes for reporting and tracking vacancies.

## Request details
- Executive sponsor: Jennifer W.
- Date: 3/3/2023

![Digitize Vacancy Tracking](https://github.com/cityofaustin/atd-data-tech/assets/110200023/81bae078-d94a-475f-82b9-dcb33af6f522)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by dianamartin** [comment]
@ChristinaTremel we might/could use this issue, right?

**Comment by stephaniemoorer** [comment]
Status Update
The Vacancy Tracking application is in production. This new application provides Human Resources Advisors with the ability to manage vacancies assigned to them. Features of the application include, tracking vacancy status using important milestones, captures important information on the position is one place and tracks the number of days the position has been vacant. 
The reporting feature provides a weekly report for the City Manager's Office. This application can be the foundation for streamlining future Human Resources processes.
