### ISSUE TITLE
Ability to override process assigned users on DS folders (NEEDS DSD COORDINATION)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#4282]
As a reviewer on DS folders, I want the ability to update process assigned users without having to do each process manually
----
Similar to ticket #2395 

**Stakeholders:** Kim, Paloma
**DTS Manager:** Tracy
**Acceptance Criteria:** 
- A new folder info needs to be created for DS folders with name 'Driveway Sidewalk Inspector', similar to Excavation Inspector (76155) info field from EX folders 
- The new info field 'Driveway Sidewalk Inspector' should be of Pick type. 
- The values for the new info field should be inspector names that come from GIS Map layer 'Service Areas -> DSD Street Inspector areas' 
- System should update the assigned user of the following processes when the info field is updated with a value
     - 200 Pre-Construction (50113)
     - 201 Sidewalk Prepour (50115)
     - 202 Final Sidewalk (50135)
     - 203 Driveway Prepour (50120)
     - 204 Final Driveway (50130) 
     - 205 Curb/Gutter Prepour (50127)
     - 206 Final Curb/Gutter (50129)
     - 207 DS TCO Occupancy (50132)
     - 208 DS TCO Occupancy (50133)
- The assigned user should be the corresponding user account of the inspector value chosen in the 'Driveway/Sidewalk Inspector' info field
- System should update the assigned user for a process only if the process does not have a Started Date
- System should update the assigned user only for DS folders 
- System should allow the user to type in a value and save it for the new info field 'Driveway/Sidewalk Permit', and then update the assigned user for the processes if a matching User Account is found. For example, if the user types in John Smith in Info field Driveway/Sidewalk Inspector, system must look to see if there is a John Smith user account. If found, system should assign the processes to the John Smith user account.

**Comment by vschandramouli** [comment]
@TracyLinder @Nadin-Nader I created this ticket after conversation with Kim. If there is something I may have missed, let me know. I will work on scoping this ticket.

**Comment by vschandramouli** [comment]
Updated AC. Ready for Backlog.

**Comment by TracyLinder** [comment]
- This requires more stakeholder coordination w/ DSD. To be done with the other discovery #2395

**Comment by TracyLinder** [comment]
**Note:** The system is not always assigning the correct DSD inspector to the process inspections. This causes DSD to have to update the processes.

**Comment by TracyLinder** [comment]
### Prioritization Oct 2024

- Inspectors do have a workaround right now; they're able to manually override each process.
