### ISSUE TITLE
Meeting "Discuss/Demo Digital Interview Roll Out" with HR

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#429]
Scheduled: Wed, 8/7/2019

Meet with HR to clarify need

Attendees: John, Diana, Adan and Nathan B.

**Comment by johnclary** [comment]
Schedule for 8/7

**Comment by dianamartin** [comment]
## Diana's Notes
Background 
Replacement of Interview binder resources 
Streamline and make things as easy as possible for HR staff 

**Minimal Concerns** 
- Records retention 
- Panel members are writing (required that is had to be written) 

## Phase 1
### Interview packet 
- **Daily Interview Schedule** 
     - Pull from eCareer, raw data, formatted 
     - Generates on Excel Spreadsheet 
     - New tab: people who are to be interviewed 
     - `Requisition Number` (Posting Number) 
     - `PCN` – unique       
          - `T numbers` (Temporary Position), `i number` (Intern Position) 
            - System generated 
      - `Panel Members` 
      - `HR Rep` 
- **Interview Guide**
  - Only 3 fields entered 
     - Number of applications 
     - Candidates for Phone Interview 
     - Candidates for In Person Interview 
  - Readable Text 
      - Guidance for new panel members 
      - What is expected 
- **Position Information**
  - Created in Word Doc 
  - Min Quals 
  - Preferred Quals 
- **ECareer of Screen Shot of Posting**  
  - Attachment? 
- **Job Description**
  - Linkable? _Link to web URL_ 
  - Some jobs are melded together (2 job titles) - temporary 
 - FTE jobs are not affected, it's a 1 to 1 job description 
 - MuniProg – mapped to 1 job description 
- **Applications for each candidate**
  - Come from eCareer 
  - Print or link? 
- **Interview Panel Member Confidentiality Agreement**
 - Internal requirement 
 - E-signature 
- **Candidate Matrix** 
  - Exported from eCareer  
  - Into a spreadsheet 
- **Zone Determination Letter** 
  - Candidate to approve the zone determination 
  - Similar 
-**Offer Letter**

## Phase 2
### Vacancy List (Real-Time positions) 
- Vacancy list (2 weeks delay) - from Banner system 
  - Keep up with what is open 
  - What is open? 
     - How long has it been open? 
     - 100 – 200 days 
     - Comment section 
     - What is the Status? 
     - Title Changes (Reclassification) 
`Green` - accepted 
`Blue`- pending offer out, haven't accepted 
**Vacancy percentage – Total Vacancies #** 
- 8% is the target (during this time of the year) 
- Funding is tied to PCN 
- Sometimes there is a back charge between groups 
   
## Phase 3
    Tracking FMLA 
    Tracking Works Comp 
    Tracking ADA 

**Hardware**
Lenovos v. laptops 

## MUST HAVES 
- **User roles**
   - HR staff 
     - have access to all items and edit ability 
     - Have access to reports 
   - Panel Members 
     - Have access to interview materials 
     - My panels they've been on hidden 
     - Expires after interview date 

After posting of job 
        Matrix of candidates 

- *Tracking reclassifications of position* 
  - Encumbered position 
  - Use PCN 
- **Tracking vacancies list**
  - Notes waiting for manager to  
  - Comments history  
- Interview Details for panel members 
- **Tracking of full time**
- **Tracking of temps** 
- **Tracking of interns** 
- **Tracking of CPO** 
 
**Wireframe Tabs/Buttons**
- Home Page (tab)
  - Re-classifications (big button)
  - Recruitments (Hiring) (big button)
  - Vacancy Report 
- ATD Recruitment (tab)  
  - Temps (big button)
  - Interns (big button) 
- CPO Recruitment (tab) 
   - Temps (big button)
   - Interns (big button)

## Success and Outcomes
- Make paper packet disappear 
  - Next a couple of months 
- Staff from printing and time it take to prepare 
  - Set Basic Metrics on performance 

**Priority**
1. Interview Packets 
2. Vacancy Reporting 

**Project Deadline**
By October 1st

**Comment by dianamartin** [comment]
@johnclary Do we still need your notes added to this before closing?

**Comment by johnclary** [comment]
"If we wait for central HR, it will never happen” -Nate

Question: What data can be pulled from eCareers? Who is tech contact?

Nathan: Concerns:
- Records Retention, MCS requirements
- Question: interview notes have to be handwritten?

#### PACKET
- Interview schedule
    - Pulled from eCareer into Excel Sheet
    - Get people who are selected for interview, PCN REQ Number (Posting # in ECareer)
- Interview Guide
    - Might go over it. Need to update the applications and candidates received
    - Same for every interview process
- Min/Preferred quals
- Question: do we give the candidate a tablet?
- Position Info Page from eCareer; PCN’s are assigned as “T” (temp) numbers or “I” (intern); system generated by eCareer. 
- Job Description > Straight from Austin Jobs Website (URL?) >> or maybe attach? There are gray areas. With temp positions, you have to map Temp titles, muniprog gets “mapped” to the job description
- Application (eCareer), Resume, Cover Letter
- Confidentiality Agreement <> eSignature > this is an ATD form

### PHASE 2
- Interview questions/notes
- Candidate Eval Matriculates
- Self-Service, Zone Determination, Offer Letter
- Encumbered Reclassification tracking

#### Vacany Report
Banner is a two-week lag, so we maintain our own
- Age (number of days), when you get over a hundred
- Status
- Hiring Manager
- Notes: reclasss, etc.

#### Other
- Generally the funding doesn’t change after the funding is created, it’s tied to the PCN
- Want to track a recluse in-situ 

Next Steps

#### What does success look like?
- Make the packet disappear
- ETA Q1 FY2020
- Reduce time spent staff spends printing and putting together packets
- Basic metrics on performance (vacancy filling)
- Create a live vacancy report
    - Bonus: able to track temp hires and interns
    - CPO tracking (separately)

####  Deliverables — Phase 1
- Digitized Interview Packet
- Vacancy list

**Comment by johnclary** [comment]
added. closing.
