### ISSUE TITLE
Add module documentation to Gitbook

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4295]

**Comment by dianamartin** [comment]
Created two [new pages](https://app.gitbook.com/@atd-dts/s/atd-knack-operations/smb-tracker/contractor-work-order-tracking)

**Comment by dianamartin** [comment]
@SurbhiBakshi @ChrispinP @amenity Can y'all check out the documentation pages I made and let me know if I should add anything else?

**Comment by dianamartin** [comment]
Chatted with Christina and will create some SMB help guides in [SMB Tracker Help Guides](https://atd-dts.gitbook.io/signs-and-markings-tracker-help-guides/) GitBook.

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/7644df54-27ee-4a26-b801-3ccda28fd4b3)
