### ISSUE TITLE
Project: Development Review Workflow Management

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#430]
## Description
This is the original request submitted by Nathan Aubert, for Transportation's Development Services Division project review platform.

#### Request
> We need something like E-Builder to track and manage development projects which require comments from multiple divisions within ATD. Our project managers will need the ability to set time deadlines and to close review and comments after deadlines have passed. They will also need to be able to dictate which individual divisions are required for a different review and which just need an FYI.

#### Success measures

> Our division will have a platform which allows us to gather comments from all of ATD on a given product and consolidate those into one set of AMANDA comments (Done outside of this platform). There will be as much automation as possible (reviewers will receive 10 days to review a specific project).

#### Describe any workarounds currently in place and/or alternative solutions you have considered.

> E-Builder is currently in use by CPO but is cost-prohibitive. Comments are currently obtained via email which is clunky and unreliable.

#### How have other divisions/departments/cities addressed similar challenges? *

> DSD was ok just using email with a task list in AMANDA.

#### Users

> Individuals from each ATD division

#### Stakeholders

> Development Review Services Division

#### Executive sponsor

> Upal Barua, Joe Calabrese, Nate Aubert

#### How would you rate the impact of this application?

> Must have — ATD operations are not legal, safe, or functional without it.

#### Would this application affect any of the Strategic Direction 2023 “Mobility” indicators?

> System efficiency and congestion

#### Would this application support any of the Austin Strategic Mobility Plan goals?

> Commuter Delay – Reduce the amount of time workers spend traveling between home and work.

> Travel Choice — Promote a balanced transportation network and the ability to make informed choices based on personal needs and preferences.

> Health & Safety — Protect Austinites by lowering the risk of travel-related injury and promoting public health.

> Economic Prosperity — Promote economic growth for individuals and the city through strategic investments in transportation networks that meet the needs of the 21st century.

#### If it is critical that this is delivered by a certain date, when and why?

> ASAP

**Comment by TracyLinder** [comment]
@johnclary I'm really interested in this project and how it might (or should) intersect with AMANDA.

**Comment by johnclary** [comment]
@TracyLinder glad to hear it. I've included you on a Weds meeting to collect the details. Lmk if you can't make it; I'd like to reschedule if you can't be there.

**Comment by dianamartin** [comment]
## Diana's Notes
_Meeting to discuss needs for reviewing Site Plan/TIA cases with ATD Vision Team Members. Specifically, which products may be available for IT team to recommend/help create._ 

Team: multidisciplinary team  
Attendees:

- Joe Calabrese -  
- Nathan Aubert -  North Area for TIA reviews 
- Sangeeta Jain

Build a process  
Development cases go to project manager 
- Review period (ex. 30 days) 
- Collecting comprehensive comments from ATD 

**Old process** 
- DSD handle a case – send to ATD contacts (ROW, Area Engineer, ATSD) all different people 
- No coordination 
- No tracking of this request  
- Responses back DSD 
- Communication was only in email, was very messy 

**Interim Process**
Development Review Case comes through AMANDA
ATD gets it for "formal submission" for review 

3 project managers (N, C, S)  
- Sangeeta – PM: decides on who needs input on the case review 
- Other 2 PMs not hired yet

Comments get internally distributed through a review request, go back to project manager 
PM reviews for conflicts, aggregate comments 

Single coordinated response back in AMANDA 
Developer gets holistic review  

7-8 Vision Team – will be the one to review  
3 Lead Engineer (N, C, S) 

1. ATSD 
2. AMD 
3. SDD 
4. CAPMETRO - external entities 
5. URBAN TRAILS (PWD) - external entities 
6. VISION ZERO 
7. SMART MOBILITY 
8. CORRIDOR PLANNING OFFICE 

_Process started but it's via email right now_

## App Name: Transportation Development Services 
 **Future Process**  
Create record entry (Development Review) for Case Review (30 days to do entire review) 

**Development Review**

1. `SP #` - ID the same as AMANDA 
2. `Project Name`
3. `Location/ Address`  - map insert? 
4.   - Need Location fields (Like Signs and Markings 
5. `Review number`: 1-10 (unlimited)
6. `Case Status`: OPEN, CLOSED 
7. `Special Instructions/Notes` 
8. `Due Date` 
  - First Review - Due Date – automated date (3 days) 
  - Second Review – Due Date  
  - Three Reviews – Due Date   
  - or make Due Date selectable by PM

Add new Review Request
**Form Review Request** 
Check box – list of people and their specialty 
1. ATSD 
2. AMD 
3. SDD 
4. CAPMETRO - external entities 
5. URBAN TRAILS (PWD) - external entities 
6. VISION ZERO 
7. SMART MOBILITY 
8. CORRIDOR PLANNING OFFICE 

**Review Request FORM**
- `Reviewer Comment` (required) 
- `Attachment` 
_After 4 days expires the request comment status_  

**Review Status - Choice list** 
`PENDING REVIEW`
`REVIEW COMPLETE`
`NO RESPONSE RECEIVED`

**Review Request - Emails**
- Automatic emails send to requester to review
_(Reference Finance and Purchasing email templates)_
- Due Date on subject 
- Link to Review page  
 
**Review Requests TABLE**
Review Cycle | Reviewer Comment | Created By| Review Status
-- | -- | -- | --
1 | Need bike lane | Jane Doe | Completed
1 |   | Jack Doe | Completed
1 |   | Josh Doe | No Response Received
2 |   | Jane Doe | Pending Review
2 |   | Jack Doe | Pending Review
2 |   | Josh Doe | Pending Review

**Functionality**
- My Reviews (Sorted by Due Date :Oldest to Newest) (similar to Finance & Purchasing)
- Search by Comment by individual (Advanced Search page, similar to Work Order Search)
- Reassigned Reviewer – PM can reassign (3 people) 
 
**User Roles** 
    Admin: DTS staff 
    PM – Supervisor: Can view comments, reassign review requests, submit review request
    Requester/Viewer: Can only view comments

## (Phase II) 
TIA Tracking 
- TIA's are being tracking manually on spreadsheet 
 
## (Phase II) 
Waiver Tracking
- Tracking waivers that have been approved by ATD
- `Waiver Approval` - Y/N 

**Process Description**
- Send to Area Engineer 
- Want to Track Waivers separately 

Outside of standard 

## DUE DATE 
- Sept 1:  ASAP (Legislation changes, limiting number of day can review a Development Review Case
- October 1 – dead line

**Comment by dianamartin** [comment]
Created blank app `Transportation Development Services Tracker`

**Comment by johnclary** [comment]
@dianamartin would you add this to the Data Inventory? https://atd.knack.com/dts#applications/new-application/

(Just did this for Signs & Markings).
