### ISSUE TITLE
Clarify record retention policies for RPP proof of residency files

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4310]

**Comment by johnclary** [comment]
I reached out to Sean C. in the Law Dept:

> Hi Sean—I'm hoping you can help us clarify our obligation to retain some sensitive documents. As part of our Residential Parking Program, applicants must submit proof of residence by submitting electronic copies of their driver's license, a utility bill and/or their lease agreement.
> 
> Once a permit application is approved, staff no longer need to reference these documents—they just check a box indicating that the resident is eligible.
> 
> Because these documents present a security liability, we would like to purge them from our database once the permit application process is complete.
> 
> Would you be able to advise if this approach would be acceptable under the city's records retention policies? I'm happy to setup a time for us to discuss.

**Comment by johnclary** [comment]
Meeting schedule w/ Sean on 1/11

**Comment by moorerst** [comment]
Per Sean for audit purposes the required documents are needed to show a clear trail of approval/verification. There is no issue with where the documents are stored as long as they can be retrieved and associated with the RPP application. So attachments can be stored outside of the application on a network drive.

**Comment by moorerst** [comment]
@johnclary did we get all the information we needed from Sean regarding record retention for RPP documents?

**Comment by johnclary** [comment]
Yes. Closing.
