### ISSUE TITLE
Resolve CCTV issue reported by Vizzion

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#4330]
Brian J from Vizzion reported that CCTVs have been out of service since 21st October.

**Comment by amenity** [comment]
@johnclary - @SurbhiBakshi wasn't able to verify that this is happening. Would you please take a look?

**Comment by SurbhiBakshi** [comment]
Brian reported the following cameras as examples - 

- [ ] 233

- [ ] 217

- [ ] 527

- [ ] 520

- [ ] 374

- [ ] 155

- [ ] 102

- [ ] 15

**Comment by SurbhiBakshi** [comment]
Wrote to Lance, he reached out to Cole. Looks like this was due to an update that happened around the same time. Cole will work on resolving this issue. I have asked him to keep us in the loop.
