### ISSUE TITLE
Phases | Add current phase to "All Projects" table

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#4331]
As a Moped user, I want to view the current phase of a project from the "All Projects" table so that I can quickly identify what phase the project is currently in.

**Wireframe**
https://balsamiq.cloud/senhupm/p9y6tuy/r0869 (bottom table of this page)

**Details:**
- Current Phase (moped_proj_phases WHERE active is true, should only be 1 value)
- Ignore Milestones for now

**Comment by amenity** [comment]
@chiaberry took care of this in #5482
