### ISSUE TITLE
Milestones | Create project milestone table to add/edit milestones

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#4333]
As a Moped user, I want to view and update a list of milestones accomplished throughout a project's lifecycle so that I can keep track of important deliverables, dates, etc.

[Wireframe](https://balsamiq.cloud/senhupm/p9y6tuy/rE41E)

**Details:**
- Data source: moped_proj_milestones
- Milestone Description needs to truncate (75-125 characters?) so the table formatting isn't messy since it could be a longer description.
- User should be able to click to view the full milestone description (create separate user story if we need to)
- When user clicks "Add Milestone", the "add milestone" should autocomplete based on the list of milestones in the database (source: moped_milestones)
~- **NOTE:** A separate issue is created for the "Other" option for the user to add a milestone in #4334)~

**Comment by tillyw** [comment]
This was closed by [Creates project milestone table to add/edit milestones #302](https://github.com/cityofaustin/atd-moped/pull/302)
