### ISSUE TITLE
Create dummy data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4338]
Let's get some nice dummy data up in this 🛵. so that we can demo/share screenshots with users w/ minimal distraction.   

Maybe importing from a Product-supplied CSV? Or @zappfyllc loading into the database directly? 

- [x] Amenity, inquire about getting a fresh data dump from IMPDB

**Comment by amenity** [comment]
@zappfyllc - will an `.mbd` file work for you?

**Comment by amenity** [comment]
@zappfyllc - data [https://drive.google.com/file/d/1p-62EXA5-oIAMmmQsa9e-hvhtgNfdtG_/view?usp=sharing]).

**Comment by zappfyllc** [comment]
Thanks @amenity, I should be able to complete this for the next sprint. Will give it a 2 for now; it might be somewhere between a 2 and 3 depending on how many tables I add data to.

**Comment by amenity** [comment]
Thoughts from Sprint Planning today: Best practices dictate data comes from Production — seed data [here](https://github.com/cityofaustin/atd-moped/blob/main/moped-database/seeds/1602292389297_initial_seed.sql)...

**Comment by amenity** [comment]
@zappfyllc - discussed this today and decided it will be fine to go ahead with this being as that it's so early on.

**Comment by amenity** [comment]
Up in #4669
