### ISSUE TITLE
Migrate Flashing Beacons (aka Hazard Flashers) to new Knack ETL

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4341]
Migrate the flashing beacons ETL to the new Knack ETL. Note that this asset is referred to as "hazard flashers" in the legacy script.

- Some background info: [#3961](https://github.com/cityofaustin/atd-data-tech/issues/3961)
- [Legacy script config](https://github.com/cityofaustin/atd-data-publishing/blob/24c4fbad9d4fc06085fe8254e4584092f8c2746a/transportation-data-publishing/config/knack/config.py#L166)

**Comment by johnclary** [comment]
will fix as part of #4471.

**Comment by amenity** [comment]
@johnclary I'll let you update the milestone on this one...

**Comment by johnclary** [comment]
I cleared the milestone. This is now part of the "Chia" epic, which will indeed be epic...

**Comment by johnclary** [comment]
@chiaberry this ETL has been broken for some time because we renamed a few of these fields in Knack and they may not match the Socrata or AGOL datasets. E.g. `ATD_FLASHER_ID` became `ATD_BEACON_ID` in Knack.

Good luck! I'm happy to help.
