### ISSUE TITLE
Set up a CTN change management process from the street.segment

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#4346]
- [x] Talk with Jacquie
- [x] Talk to Dwayne about how the change notifications FME workbench works
- [x] Ask Dwayne to add transportation.data address to the workbench
- [ ] Setup inbox rule to forward these to Slack. See [this page](https://slack.com/slack-tips/send-email-to-slack) under "Send one email at a time into Slack with a forwarding address"

**Comment by alan-deanda** [comment]
I've received the FME workbench from Public Safety, and I will schedule a meeting with Dwayne to go over setting it up the change notification.

**Comment by alan-deanda** [comment]
After my meeting with Dwayne, I understand how the workbench works, and have some options for different types of change detectors. Currently my FME is having issues with my connection files to databases, so I'm working on making it read layers from AGOL instead.

**Comment by johnclary** [comment]
@alan-deanda please do a review of how many changes we're looking at (and of what nature) to street segments on a monthly basis

**Comment by alan-deanda** [comment]
I've extracted edits to the street.segment layer by month in 2020.
My next steps are:
- [ ] Consolidate the data by checking for differences in the data from month to month in FME, and combine those outputs.
- [ ] Check the CTN against the ASMP for any data that may have been lost while splitting segments before adjusting the split domain rule from default to duplicate
- [ ] join the combined edit outputs to the CTN in ArcPro. This will allow me to see which street.segments did not match and why.
- [ ] Once the join happens, I will build a model to field-calculate the fields we transfer over from street.segments to the CTN
- [ ] The remaining edits will have to be done after analyzing the cause for the mismatches - difference in road digitization, difference due to split geometry, difference due to new geometry, etc

**Comment by johnclary** [comment]
Email to Jacquie:
> Hi Jacquie! Hope you're holding up OK in your neck of the woods.
> 
> I wanted to restart our conversation around some challenges we're having with the CTM street segments.
> 
> While working on an AMANDA PIR last week we discovered that many of the ROW permit property ID's (which are typically segment IDs) were nowhere to be found in the street segments layer. It seems that the problem is that those missing IDs refer to segments that have been replaced/split/something in the CTM layer. Fortunately, Sean M was able to help us retrieve most of those through a layer on APP1 that's used for notifications, but I think this is going to be ongoing issue for us for both permit data and other asset data we have that reference street segments.

Jacquie's response:
> I spoke with Sean and Lee (two of our developers) and it sounds like they might be able to make a view that would resolve a current segment back to its history.  Then all you would need to do was query it with the current Segment ID. Or vice-versa if they have a discontinued Segment ID, it would take you to the current one. 
> 
> Does this sound like something you’d be interested in pursuing?

**Comment by johnclary** [comment]
I'll respond to Jacquie and let her know that we need to preserve the historical geometries, and also need a change log/diff of changed segments.

**Comment by johnclary** [comment]
To Jacquie:

> That would definitely be helpful, but ideally it would be possible to see the historical attributes and geometries as well. For example, if we issue a ROW permit for a specific segment, and that segment ID is deprecated, we lose the original geometry that permit was tied to.
> 
>  
> 
> I didn't mention this in my original request, but we're facing challenges around tracking changes to street segments in general. E.g., when a street name or a block range is changed. Currently, all we have to go on is a modified date. We really need a change log or historical dataset so that we can track these.

**Comment by alan-deanda** [comment]
Closing this issue, as Andrew has taken over this process and maintenance is ongoing.
