### ISSUE TITLE
Ensure that Jen has the data she needs to verify invoicing

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4349]
Need to check with Jen to see: 
- Does she need us to add "periods of inactivity" back?
- Will [this Power BI dashboard](https://app.powerbigov.us/groups/me/reports/00eec5d7-d663-4163-a304-5188d8f0a323/ReportSection?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f) work for her? 

Example filtering down to a single shift for a single officer: 
![Screen Shot 2020-11-02 at 12 22 58 PM](https://user-images.githubusercontent.com/1463708/97905200-3a98c880-1d07-11eb-95d0-f434aa487c4e.png)

**Comment by SurbhiBakshi** [comment]
@amenity - I created the PowerBI to QAQC the process to link datasets from Knack and Brazos, can refine it further based on what works for Jen.

**Comment by amenity** [comment]
Questions for Jen:
- Can invoicing happen on a regular schedule? How often? 
     - Otherwise, could do ad-hoc via DTS Service Request — expectation would be delivery by EOD the following business day. 
- Will you be able to get all the data you need for invoicing in PowerBI instead of having to have both apps open? 
     - If so, what would you expect to use the Knack app for (registered officers, officer contact info, schedules...)? 
- Is it necessary for officers to explicitly report periods of inactivity in Knack? 
     - We have this functionality and can restore it if you and Pat agree on that.

**Comment by amenity** [comment]
@SurbhiBakshi and I met with Jen and David and they were very pleased with the new process. 

A few tweaks:
- [ ] Add a column in Power BI to show whether a warning or citation was issued
- [ ] Change text above Notes field:

> During your shift, please add a note for: 
> - Safety concerns, e.g. "pedestrians crossing without crosswalk Cesar Chavez between Comal and Chicon", "low visibility around corner at 12th and MLK", etc.
> - Long periods of inactivity such as vehicle or equipment malfunctions

And a few features:
- [ ] Increase accessibility of officers' on-shift notes for ATD staff — PowerBI would be wonderful so ATD staff can do all their invoice review and program management in a single application, otherwise adding "Details" modals to Randy's invoicing page and giving David, Jen, and Lewis access.
- [ ] Digitize invoicing process, including payment status — Invoices occasionally fall through the cracks and then ATD and Finance have to scramble to address them later on

**Comment by SurbhiBakshi** [comment]
Refining the report in #4561
