### ISSUE TITLE
VZE | Fix bug that prevents new users from logging into VZE successfully

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#4350]
Last Friday, Frank reported a bug where he could log into VZE from his work machine but not a separate one. On the other machine, he encountered an endless loop of clicking "Login" and then being redirected back to the "Login" page. I was able to reproduce this in incognito mode.

![image](https://user-images.githubusercontent.com/37249039/97904749-9020a580-1d06-11eb-8e10-ca774c3a4528.png)

After some troubleshooting, Frank isolated an issue with Netlify not offering a `Access-Control-Allow-Origin` header, and that subsequently preventing Auth0 from creating a cookie for a successful login.

Mateo found a [post in the Netlify community](https://community.netlify.com/t/access-control-allow-origin-policy/1813) that lays out some steps to resolve this issue by updating the Netlify config.

**Comment by mateoclarke** [comment]
Here is the [commit to master](https://github.com/cityofaustin/atd-vz-data/commit/cd578e9e6c737ea8fd759de310e16cc412fa1c25) where I tried updating the netlify.toml config as suggested in the Netlify forum and I can see that the Response Headers for the staging URL now include `access-control-allow-origin : *` as show in the screenshot below, but this does not seem to fix the looping Login issue that I can also reproduce in Incognito.

![Screen Shot 2020-11-02 at 9.29.07 PM.jpg](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/38e39eae-d484-40bf-aa60-086b823c4c2e)

**Comment by mddilley** [comment]
I found [this GH issue](https://github.com/auth0/auth0-spa-js/issues/577) that points to some problems with blocked cookies and a proposes a solution of implementing [rotating refresh tokens](https://auth0.com/docs/libraries/auth0-single-page-app-sdk#use-rotating-refresh-tokens) in order get around session cookies for the auth process.

I made the changes in https://github.com/cityofaustin/atd-vz-data/pull/945 and was able to log in successfully in Chrome Incognito and also Brave (which I had never logged into VZE with before). Frank is testing today to see if it resolves his login issue.

**Comment by mddilley** [comment]
I tested the updates to staging on my machine with Chrome, Firefox, and Brave (private and non-private windows) and also in BrowserStack. All works great. I think that it would be a good idea to have others test on their machines on 11/5 so I'll reach out then.

**Comment by mddilley** [comment]
Confirmed that this fix is working in staging with Mateo and Frank. Will add the needed updates to the production settings in the Auth0 in the deploy notes with the next release. Closing.
