### ISSUE TITLE
Gitbook documentation for Officer log in process

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4353]
See investigation in process [here](https://github.com/cityofaustin/atd-data-tech/issues/4134#issuecomment-720723043). 🕵️‍♀️

**Comment by SurbhiBakshi** [comment]
thanks @amenity for creating the issue!

**Comment by SurbhiBakshi** [comment]
Documentation at ATD Knack Operations - Vision Zero in Action - Login Process for Officers.

**Comment by amenity** [comment]
Looks great, @SurbhiBakshi. How do you think we should share [this page](https://atd-dts.gitbook.io/atd-knack-operations/vision-zero-in-action/officer-login-process) with Officers? Should we potentially make the Help page on the app accessible without logging in and add the information there? Create a freestanding Knack page with this information? Send it as an email when officers register?

**Comment by SurbhiBakshi** [comment]
@amenity  - I am inclined towards sending it in the email that the officers receive once they register. If Lewis does the introduction and then shares the link with officers to register for accounts, the officers will get the email with this information once they create an account.

**Comment by amenity** [comment]
Sounds good, @SurbhiBakshi —closing this.
