### ISSUE TITLE
[Enhancement] Standardize City and State formatting

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4355]
Standardize City and State - Austin vs AUSTIN and TX vs TEXAS (should decide what we want and update address verification records and javascript to correspond accordingly)

**Comment by moorerst** [comment]
@ChrispinP I'm ok with either no strong opinion either way

**Comment by ChrispinP** [comment]
Removed unused autofill JS for City/State. Went through all application records and corrected license plate 1 and 2 fields to be TEXAS instead of the old TX. Went through Address Verification records and removed USA from address fields, removed duplicate Second Address entries, updated all States to abbreviations from TEXAS to TX.

There are also a lot of formatting errors in address entries but would be too cumbersome to go through all 1000 records and update. In addition, City is set to either Austin or AUSTIN, it as well would be too cumbersome to go through all records and update to one format. Filters treat capitalization the same as lowercase.

Complete with possible future improvements to formatting or removing duplicate addresses still available.

**Comment by moorerst** [comment]
closing this issue
