### ISSUE TITLE
[Update] Migrate/Copy customer object fields to Applicant fields on permit_application object

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4356]
Should we migrate customer object fields to the customer fields on the permit application?

**Comment by ChrispinP** [comment]
Unable to Migrate the Name connection field values from the customer object into the Applicant Name field for older applications. Was able to successfully update Applicant Type, Phone, Email, & No Email/Phone values.

Applications missing an Applicant Name will need to be updated manually. Should we create a new Backlog issue for this or should the onus be on RPP staff to update these older applications?

**Comment by moorerst** [comment]
@ChrispinP thanks for migrating the information you could. Let's not create a backlog issue for the Name field, if it becomes an issue we can address it then. I'll make sure RPP staff is aware of it. But I think they have what they need for renewals. Thanks
