### ISSUE TITLE
[Update] Remove unused fields from permit object

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4361]
Need to scope out any data migration work needed. Remove unused fields. Update Reporting to reflect any changes.

**Comment by ChrispinP** [comment]
I have scoped out work and updated blocking issue #4590 on which fields are to be removed from the permit object.

pending reporting implementation and unused field removals thereafter

**Comment by ChrispinP** [comment]
**Fields to remove:**
Final Cost
Final Cost Currency
Transaction Month
Month Text
Issued Month for Reports
Issued Month Number Text
Cost per Permit or Pass
Cost of Permits or Passes

**Comment by johnclary** [comment]
@ChrispinP go ahead and remove the fields from the permit object, and would you please take another look at the `permit_application` object?

**Comment by johnclary** [comment]
Will leave `customer` and `attachments` object as-is until we move on to RPP v2.0

**Comment by ChrispinP** [comment]
removed unused permit fields, complete
