### ISSUE TITLE
[RPP Back Office] Update Reports Page with new values

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4368]
Update the existing reports page with the new values

**Comment by moorerst** [comment]
@ChrispinP the following new query needs to be added to the Reports Page

- [ ] Number of website applications is "Completed - Permits Issued" status for the certain period of time? (weekly, monthly)

This is currently being reported weekly to management

**Comment by moorerst** [comment]
See notes on issue #4647

**Comment by ChrispinP** [comment]
Building existing and new reports in Test, in progress.

**Comment by moorerst** [comment]
schedule meeting with stakeholders to review and provide feedback on RPP Reports modifications
attendees: Jacob, Steve, Daniil, Diana, Chrispin, Stephanie
Meeting scheduled 1/14

**Comment by moorerst** [comment]
@chrispin is there a schedule date for moving the reports into production?

**Comment by ChrispinP** [comment]
Finished updating report pages. The Completed Applications by District report has a Past 7 Days filter to see numbers for the past week. Ready to review with Stakeholders for any final adjustments.

**Comment by moorerst** [comment]
@chrispin the reports page looks really good. You will probably hate me for this but the COA fiscal year is Oct to Sept the data may have more value to them using that timeframe than YTD. But let's see what feedback we get from them. Thanks

**Comment by moorerst** [comment]
@ChrispinP sent email on 1/28 to RPP staff to review Reports Page and provide feedback. Have not received any responses. If no responses by Wed 2/3 we can close the issue.

**Comment by ChrispinP** [comment]
closing as complete. will create new issues as necessary.
