### ISSUE TITLE
TIA Submissions Page Design

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4371]
This page needs better design. 

https://atd.knack.com/development-services#view-tia-reviews/tia-request-details/5f80d60665abf800163a2c9e/project-submissions/5f80d60665abf800163a2c9e?

**Comment by ChrispinP** [comment]
Had to rebuild Submissions page and update rules. Not sure how much nicer in comparison it looks now but should be an improvement. Function wise, everything on the page should be working as intended now.

Ready for Review

**Comment by ChrispinP** [comment]
no further issues, closing
