### ISSUE TITLE
Project Comments | Implement logged-in user app context for re-use

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#4374]
When adding a project note, the user who creates the note needs to have their name/ID logged to the note automatically. This will be a common pattern across Moped: logging newly created database rows with the logged-in user. Since it would be ideal to log the user for almost all entities (both creation and edits), this should be considered from the onset of implementation.

**Comment by sergiogcx** [comment]
@lazavazav I believe there is the `useUser()` method available to retrieve the current user session data:
https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/App.js

**Comment by zappfyllc** [comment]
@mateoclarke if this is redundant and unnecessary since this problem has already been technically solved with some of the auth work, we can close this but I just wanted to ensure we're using the same method for logging the user's name to project comments (to match the wireframe) since we'll probably reuse that for other features.

**Comment by zappfyllc** [comment]
@zappfyllc move this to epic GetUserDetails

**Comment by amenity** [comment]
The work that @sergiogcx has done with user tokens and the activity feed will enable us to record the user who makes a comment.
