### ISSUE TITLE
Project Comments | Edit and delete project comments

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#4376]
As a Moped user, I want to edit and/or delete past project notes so that I can fix any typos, incorrect information, etc. without having to add yet another note to the project record.

**Wireframe:**
https://share.balsamiq.com/c/c9TkgGvd99ESusDnZm22ND.png
Note: we would likely just add an edit icon with a "Delete" dropdown within the same context as #4375 

**Details:**
- Data source: moped_proj_notes
- We need logging of both time and user for when notes are edited or deleted.
- Data should be archived, not deleted

**Comment by amenity** [comment]
https://github.com/cityofaustin/atd-moped/tree/4376_mc_edit_comments ...
