### ISSUE TITLE
Test signal location configurations in test instance of VZA

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4377]

**Comment by SurbhiBakshi** [comment]
Changes that will need to be made when the Signal Locations object is separate from the Vision Zero Location object 

- [ ] Calendar description will have to be updated to show SE Locations. Will involve creating a calculated field with a conditional based on Type of Assignment - VZ or SE that has the location and will be incorporated in the Calendar Description.

**Comment by SurbhiBakshi** [comment]
1. I tried another approach of combining the two location objects.
2. This does mean that we will have to figure out if the assignment is a Signal Engineering or Vision Zero assignment, so the drop down is not extremely long. Predictive typing might take away some of the pain.
3. If we give both the schedulers the same role,  we can have of two forms - one for VZ and one for SE, I can set a filter in the form itself that filters the locations by VZ or SE.
4. Also, most of Lewis's assignments occur by the batch copy process and he edits in the calendar or the table. I am not sure how many he adds  or will add in the future. 
5. We could also do two roles, with neither seeing the other's form.
