### ISSUE TITLE
Review data structure to see if updating status on a parent record can propogate to individual signals

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4378]
[Detector Workflow - Miro](https://miro.com/app/board/o9J_kpabH40=/)

**Comment by dianamartin** [comment]
Was testing in AMD test environment
So far testing steps
- built new page on `Detector QC` page, `Batch_Update`
- added to main Detector QC table, next to `Edit Detection`

**Comment by dianamartin** [comment]
## Test Build Notes
Event:  
DETECTION CHECKED
DETECTION RESTORED - OK
ISSUE REPORTED - BROKEN
DETECTION INSTALLED - OK
DETECTION UNINSTALLED - REMOVED
VERIFICATION NEEDED - VERIFICATION NEEDED

Date
Comment
Created By - logged in user

Detector Status Date - Event Date
Modified Date - Current Date
Set "signal" to "signal detectors>signal"

**Comment by amenity** [comment]
@SurbhiBakshi is going to look into the possibility of doing this with Tasks.

**Comment by SurbhiBakshi** [comment]
@johnclary , @amenity - Wanted to confirm the below -
Signal - parent
Signal Detector - child
Signal Detector Status Log - grandchild
and
The purpose of the issue is that when Detection Status on a record in the Signal object is updated, it needs to be updated on all related Detector Status records in the Signal Detector object.

**Comment by amenity** [comment]
Some of this is set up in TEST and we think this can be accomplished with tasks, but we have outstanding questions about the process so going to do #4458 instead this year and review what that process they used before automating. Will need to review in June 2021 for their next system-wide check.
