### ISSUE TITLE
[Bug] Ability to delete permit record after issued

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4381]
From RPP team (Daniil)
noticed that there is no way to delete a permit after you hit "Issue". It will be there and the total cost will be changed accordingly. Even if I change the serial # and the status to blank

![image](https://user-images.githubusercontent.com/56606465/98139443-d5b9ab80-1e89-11eb-9d73-768179a80ec6.png)

**Comment by ChrispinP** [comment]
This field was reliant on a field thats not currently being used anymore since app status is set under the permit_application and should not be set under the permit object. Removed the rule and the Remove field should now appear.

Complete for Review

**Comment by moorerst** [comment]
Confirmed with RPP Staff this issue is complete/closed
