### ISSUE TITLE
Meet to discuss calculating labor on shifts that span multiple dates

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4382]
Peggy reported an issue with negative hour totals on HR shifts that span from one day to the next #4373 ... Will need to figure this out for VZA as well.

**Comment by dianamartin** [comment]
## Process to Solution
Figured it out..this article was helpful: https://support.knack.com/hc/en-us/community/posts/220716468-Time-Equation-Formula

- Created `MIDNIGHT` - default to 12 am
- Created `START_TIME_TO_MIDNIGHT_EQUATION` - equation that took `{MIDNIGHT}-{Start Time}`
- Created `MIDNIGHT_TO_END_TIME` - `{End Time}-{MIDNIGHT}`
- Created `TOTAL_LABOR_HOURS` - `{START_TIME_TO_MIDNIGHT_EQUATION}+{MIDNIGHT_TO_END_TIME}`

Lots of testing to see if field calculated correctly in the records. 

## Need To Do
- Replace all fields that have "HOURS_WORKED" with new field `TOTAL_LABOR_HOURS`
