### ISSUE TITLE
[Bug] Knack Rounding not working as intended

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4388]
Knack Default Rounding is rounding .005 values down instead of up.

For example: $110 x 1.0825 (cost x tax) = $119.075. Knack rounds this to $119.07 instead of $119.08.

**Comment by ChrispinP** [comment]
I submitted a ticket to Knack

**Comment by ChrispinP** [comment]
No updated from Knack yet

**Comment by ChrispinP** [comment]
Submitted a new Service Request due to no response.

"Hello,
Knack Default Rounding is rounding .005 values down instead of up.

For example: $110 x 1.0825 (cost x tax) = $119.075. Knack rounds this to $119.07 instead of $119.08. If we changed Default Rounding to Round Up instead, this would make our other values that are rounding correctly to then round incorrectly.

Is there a way to fix this default rounding error?"

**Comment by moorerst** [comment]
@ChrispinP is there any update on this issue with Knack? Is it still and issue?

**Comment by johnclary** [comment]
@ChrispinP would you test this in the new builder?

**Comment by ChrispinP** [comment]
Submitted support message to Knack again to followup on this bug:

Hello, following up on the Knack rounding error bug we have come across and reported back in early November and never received a response for.

Details about the bug:

Knack Default Rounding is rounding .005 values down instead of up.

For example: $110 x 1.0825 (cost x tax) = $119.075. Knack rounds this to $119.07 instead of $119.08.

Additionally, i tested for different values and knack rounding isnt working on values under 100, partially works for values between 100 and 1000, and seems to fully work for values over 1K.

I have also tested this bug in the new builder and it still exists.

Help to resolve this so our cost calculations are accurate for customers, staff, and financial reporting is appreciated.

**Comment by ChrispinP** [comment]
Yay! Received some followup today for the rounding bug. Research so far shows that is could be how rounding works in JavaScript as being the culprit.

Knack response:
Hi Chrispin - I'm looking through our bugs and logs to see if I can gather any intel or find a known issue. I am seeing a note from a developer that it appears we have come across something like this that has to do with floating-point rounding in Javascript (see http://www.jacklmoore.com/notes/rounding-in-javascript/ for more on why this can happen with numbers ending in 5). 
I'm going to check to see if that is what you're experiencing and see what the plan is to address this - whether it be a bug fix we tackle now or if it's part of a larger solution. 
Would you mind sharing a URL to an example in your app, or even a test that you have set up (if you have?) so I can confirm?

**Comment by ChrispinP** [comment]
More Knack Followup:
Hi Chrispin - So I've spoken with our engineers about this one, and it does appear that it's a known issue that you're running into with decimals ending in 5 rounding down instead of up. While it is a bug, it’s also a foundational limitation of how javascript handles numbers out of the box. We are going to need to address this at a higher level, in order to consider all ramifications of making changes to rounding and value normalization.

I'm trying to get a better idea of a path forward for prioritizing this work, but in the meantime - I found a colleague who ran into this with a customer created a workaround that could help patch you up. I'm trying to understand it all, but basically they made a conditional equation that compensates for this scenario. Let me try and break it down for you.

**Comment by ChrispinP** [comment]
still working with Jessie from Knack on a possible workaround with ternary operations.

otherwise the new current workaround we need to implement for all apps is as follows:
A) add .001 to costs (one one-thousandth) & B) Tax Amount Equation must have 3 decimal places

a plan needs to be laid out on implementing for all apps, especially as we get closer to implementing stripe payments in our apps

**Comment by ChrispinP** [comment]
No further workaround was discovered besides the one I have noted above. Will updated Gitbook with some documentation for this workaround so we are aware when calculating any costs in any of our applications. Will close issue after I have created the documentation.

**Comment by ChrispinP** [comment]
I have updated gitbook with documentation on how to implement workaround and custom JS solution into Knack apps to correctly round costs and tax.

[Rounding Knack Costs Correctly](https://app.gitbook.com/@atd-dts/s/atd-knack-operations/knack/knack-rounding-costs)

**Comment by moorerst** [comment]
Closing this issue the workaround has been documented
