### ISSUE TITLE
Evaluate COORD

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#439]
Parking Enterprise and Smart Mobility have taken an interest in [COORD](https://www.coord.co/). We had a demo period, which ended, but we (DTS) did not participate. My last email to COORD:

> Hi Stephen—apologies for the slow reply. My team has not had a chance to review the data that was collected. Would it be possible restore access to your app for a short time?
> 
> 
> To add some more info on related work we're doing for this project: there is currently an effort underway to digitize all of our street regulations in a geospatial database, using our Traffic Registry as the source. It's a major effort, including more than 50k regulations, which we expect to be complete early next year. We're using the city's planimetric data as a reference for curbline regulations, but there are also regulations that do not pertain to curbs, e.g., turning movement restrictions and stop signs.
> 
> 
> As part of this effort, we are also re-designing the process by which regulations are authored into the traffic registry, and migrating the registry itself, which is currently an Access DB, into our web-based workflow management system.
> 
> 
> Based on my limited understanding of your solution, my main point of concern is that the universe of regulations we need to track is larger than what your application supports, since we need to capture non-linear regulations such as stop signs. Further, once our digitization process is complete, we would need to migrate those records to your application and attach them to corresponding curbline features.
> 
> I can absolutely see value in having a user-friendly interface for maintaining our curbline feature data, but this may be redundant to other data management efforts in the city, particularly since we (ATD) do not manage curb and sidewalk infrastructure, that’s handled by the Public Works Department.
> 
> We can discuss all of this in more detail, but a starting point would be for folks from my team to actually demo the app. My apologies for not taking that opportunity when we had the chance.
> 
> Thanks.
> John

**Comment by johnclary** [comment]
Stephen replied that we will be given another two weeks to demo the app. He'll follow up after that. @jaime-mckeown @alan-deanda would you let me know if you have received your credentials to login to the COORD app?

**Comment by jaime-mckeown** [comment]
@johnclary The login I created last time works again.

**Comment by amenity** [comment]
@dianamartin and @jaime-mckeown - can you add your thoughts about COORD here? Thanks!

**Comment by amenity** [comment]
@john is going to follow up with Stephen Smyth.

**Comment by johnclary** [comment]
We've done some preliminary work and I just don't think this fits our need at the moment. Will let the vendor know.
