### ISSUE TITLE
New AMANDA User Accounts: 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4391]
- [x] Julie Anderson 
- [x] Allison Mills

**Comment by Nadin-Nader** [comment]
Created Julie Andersons account and emailed the following:

> Good Morning Julie,
> 
> Hope you are doing well. I was reaching out to you in regards to your AMANDA Account request. I have created your AMANDA account on TEST. Please use the instructions below to log into TEST and change your password. 
> 
> I have also set the automation to create the account on PROD after 6pm tonight, you will receive an automated email stating the account was created on PROD. Once the automation creates the account on PROD, please use the same instructions below to log in and change your PROD password.
> 
> Your UserID is ANDERSONJ
> Your Temporary password is the same as your UserID in all caps.  
> UserID are not case sensitive but your password is.  
> You will be prompted to change it upon login.
>  
> Please log into AMANDA TEST application to test your account and update your password.  Please keep in mind that changing the password on TEST does not affect the password on PROD.
>  
> In the Future-If need be, 
> you can reset your password using your Employee ID 10150096:
> Steps:
> Click on this link to access the AMANDA Password Reset Application 
> URL:
> https://apps.austintexas.gov/eas/amanda_pw_reset/confirm_user.cfm
> 
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services
> Austin Transportation Department

I also found that Allison already had an active AMANDA account on TEST and PROD. I sent the following email with login and reset instructions:

> Allison,
> 
> Hope you are doing well this morning. I am reaching out to you in regards to the AMANDA Account request submitted for you. I looked in AMANDA and you already have an Active account on TEST and PROD. I have put the login instructions below. Please use them to log in and change your Password.
> 
> Your UserID is MILLSALI
> Your Temporary password is; AUSTIN1234 in all caps.  
> UserID are not case sensitive but your password is.  
> You will be prompted to change it upon login.
>  
> Please log into both AMANDA TEST application to test your account and update your password.
>   
> **Since I cannot change your PROD password, you will need to use the reset Link below to reset PROD
>  
> In the Future-If need be, 
> you can reset your password using your Employee ID 10138839:
> Steps:
> Click on this link to access the AMANDA Password Reset Application 
> URL:
> https://apps.austintexas.gov/eas/amanda_pw_reset/confirm_user.cfm
> 
> Please let me know if you were able to log in or not.
> 
> Respectfully,
> 
> Nadin A. Nader 
> IT Business Systems Analyst
> Data and Technology Services
> Austin Transportation Department

## **Status:**
Waiting on Automation to create Julie's account on PROD and for both to log into TEST and PROD.

**Comment by Nadin-Nader** [comment]
Allison is able to log in but Julie doesnt have AMANDA installed and is working on getting the application to log in. I will close this out and if they have issues with AMANDA they will let us know.

Allison,

Hope you are doing well. Yes you should have all the same permissions as Leslie. I will now close the request. If you get an error or anything please email me an let me know.

Respectfully,

Nadin A. Nader 
IT Business Systems Analyst
Data and Technology Services
Austin Transportation Department
