### ISSUE TITLE
Sign Asset Domains from Knack

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#4392]
I am starting to work on the Signs GIS Asset Management data. I talked to Christina and she said that some of the fields in the GIS data should be populated by the same domains that already exist in Knack. Can you provide me with the domains from Knack that will populate the GIS data in the Asset Sign Poles and Asset Locations GIS data?

The Spreadsheet where all the tables and feature classes are broken down is located here:
G:\ATD\ATD_GIS\01_ADMIN\DATA_MANAGEMENT\Data_Migration\signs

Asset Sign Poles Fields
![image](https://user-images.githubusercontent.com/48842809/98169023-21cc1680-1eb1-11eb-97e5-c4ebce470274.png)

Asset Location Fields
![image](https://user-images.githubusercontent.com/48842809/98169077-390b0400-1eb1-11eb-9dd8-a8789937db96.png)

**Comment by dianamartin** [comment]
@jaime-mckeown I'm going to check with Christina to see if these are the fields that you need. I've attached what I think is needed, but just not 100% on it.

## Knack Signs tables

`work_order_signs_asset_spec` - equivalent to `Asset Sign Poles Fields`
- [20201104_work_orders_signs_asset_spec.xlsx](https://github.com/cityofaustin/atd-data-tech/files/5490996/20201104_work_orders_signs_asset_spec.xlsx)
![image](https://user-images.githubusercontent.com/21112975/98179640-d58ad180-1ec4-11eb-82d9-b18fa10ff93a.png)

`work_order_signs_locations` - equivalent to `Asset Location Fields`
- [20201104_work_order_signs_locations.xlsx](https://github.com/cityofaustin/atd-data-tech/files/5491003/20201104_work_order_signs_locations.xlsx)
![image](https://user-images.githubusercontent.com/21112975/98179605-c015a780-1ec4-11eb-8d35-b26284e95b24.png)

**Comment by jaime-mckeown** [comment]
@dianamartin Thank you! Christina will definitely be able to give you better details for the fields.

**Comment by jaime-mckeown** [comment]
@dianamartin Christina is going to create domain tables for me today. I'll let you know if I need anything from the backend tables after looking over what she sends. Thanks!

**Comment by jaime-mckeown** [comment]
@dianamartin I got what I needed from Christina. I will close this Issue so it's not sitting in your Review/QA until 2021. Thanks!
