### ISSUE TITLE
Refine PowerBI VZA reports

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4408]
We have reporting needs well-documented from a while back. Circle back with Jen and Lewis to see if anything has changed.

**Comment by SurbhiBakshi** [comment]
Here is a list of reports that came out of a meeting last year Contacts per hour

1. - [ ] Contacts per hour
2. - [ ] Average contacts per hour by a given officer
3. - [ ] Breakdowns by citation type
4. - [ ] Average contacts per hour at a given location
5. - [ ] Total hours scheduled per location
6. - [ ] Total contacts made per location
7. - [ ] Average number of shifts per month
8. - [ ] Number of person shifts by month
9. - [ ] Number of unfilled person shifts
10. - [ ] Total hours worked by each officer
11. - [ ] Citations recorded by time of the day
12. - [ ] Average number of contacts per shift

**Comment by amenity** [comment]
@amenity — schedule a meeting with Lewis ~month out to discuss reporting-beyond-invoices.

**Comment by amenity** [comment]
@SurbhiBakshi and I are meeting with Lewis & Jen on 3/18 to scope this work.

**Comment by SurbhiBakshi** [comment]
Here is a list of reports that came out of a meeting last year -

 Contacts per hour
 Average contacts per hour by a given officer
 Breakdowns by citation type
 Average contacts per hour at a given location
 Total hours scheduled per location
 Total contacts made per location
 Average number of shifts per month
 Number of person shifts by month
 Number of unfilled person shifts
 Total hours worked by each officer
 Citations recorded by time of the day
 Average number of contacts per shift
 Number of hours scheduled and number of hours unfilled

**Comment by SurbhiBakshi** [comment]
From meeting on 04/01/2021
 - [ ] Check how assignments over two days will work in reporting.

**Comment by SurbhiBakshi** [comment]
Error while resolving assignment scheduled over two days 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/17d65962-dd0d-4d2b-acfc-45ea21e0e8ec)

**Comment by amenity** [comment]
@SurbhiBakshi — do you think this is a dealbreaker?

**Comment by amenity** [comment]
Probably easiest to discuss in Teams w/ Lewis once you've assessed. 🙏

**Comment by SurbhiBakshi** [comment]
@amenity - Don't think this is a dealbreaker, I have thought of a way around it, and am in the process of implementing it in Power BI.  It might take some time to iron out the steps, but think this should work.

**Comment by SurbhiBakshi** [comment]
**Notes -** 

1. Categorize Assignment Date and Time from Knack in `mm/dd/yyyy hh:mm to hh:mm` or `mm/dd/yyyy hh:mm to mm/dd/yyyy hh:mm` format based on if the assignment is scheduled for one day or over two days by length of string (25 and 36). 
2. Create Assignment Start Date and Time using the first date and time entry in the record. 
3. Create two Assignment End Date and Time columns using the date and time entry - One will be Start Date and End Time and the other will be End Date and End Time. 
4. Create a conditional column Assignment End Date and Time that is then populated by the records in the two columns mentioned above based on the length of the string.
