### ISSUE TITLE
Feature: Update Inventory Request pages for FDU Reviewer

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#4411]
## - [ ] Include the TK number on the review needed screen (and have it sort-able by clicking the field name as the other fields are).  
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/cd26950d-cd6c-4fa0-bb56-94df739aead2)

## - [ ] Add cost info to the following screen to Request Details page
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/af400946-54fd-4e3e-a0fd-aeb35d0c898c)

### Creating `Total Cost` field for work order/request object
**Line Total**
- transactions object table, create:
  - New field `Line Total` - Equation _(quantity & unit cost)_

**Total Cost**
- work order/request object
  - New field `Total_Cost` - Sum (of Line Total from transactions object)

**Comment by amenity** [comment]
@johnclary -note that we had this slated for Sprint 37, way back when.

**Comment by johnclary** [comment]
Done
<img width="1359" alt="Screen Shot 2021-04-16 at 2 36 49 PM" src="https://user-images.githubusercontent.com/14793120/115075790-3d583600-9ec1-11eb-9c02-c5b484603142.png">
