### ISSUE TITLE
COACD Login not working

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4413]
User's are getting an error message when trying to login with their CoA email/password. It appears that CTM will need to update the active directory SAML metadata so that it includes our new application ID.

I exported the login metadata from the new app and sent it to CTM:

> Hello,
> Please assign this to the Active Directory team.
> Our SAML metadata for our "RPP" application has changed slightly. See attached new metadata and old metadata.
> Note the minor change to the <AssertionConsumerService> "location" property.
> Would you please update this app's metadata accordingly? Thanks for your help.
> John

**Comment by johnclary** [comment]
@moorerst @ChrispinP FYI

**Comment by amenity** [comment]
Also got a report from Daniil K. via ServiceNow (INC0064639):
> I use https://atd.knack.com/parking#home/ to log into it with my COA email and password. If I hit "sign in" - it will always say "Email or password incorrect.". If I hit "Sign in with COACD" (which used to work before) - it will transfer me to another page with the following Troubleshooting details: Request Id: ddb9d2b0-6b22-4d9b-8f89-9e4ea65a1001

**Comment by jaime-mckeown** [comment]
@amenity @johnclary can someone please contact Daniil K. as they rejected the closed Service-Now ticket which was re-opened this morning. Thanks!

**Comment by moorerst** [comment]
The incident was Closed again by the system - not sure how that works so I'm trying to get it reopened with additional information that John provided

**Comment by jaime-mckeown** [comment]
@moorerst do you know what the CTM Active Directory Team is called in Sevice-Now? I can't find it to reassign Danill's Incident?

**Comment by moorerst** [comment]
@jaime-mckeown ESA

**Comment by moorerst** [comment]
As a workaround Daniil was able to login with his email address after he selected Forgot Password and reset his password. So he is able to log in and process application. We will continue to attempt to resolve the COACD Login issue.

**Comment by moorerst** [comment]
@jaime-mckeown this has been resolved by John Dykowski. The incident can be Closed. Thanks for your help.

**Comment by moorerst** [comment]
Per John D (CTM) I have updated the assertion URL. 
This was tested and confirmed it is working properly

**Comment by moorerst** [comment]
Issue is complete and can be closed
