### ISSUE TITLE
[Feature] Document Repository

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#4423]
As a project staff member, I want to upload important files/documents so that I can access file/documents related to a project quickly.

**In-scope:**
- File attachments via S3
- Uploading and deleting attached files; table listing of file attachments
- User-facing file versioning

**Out-of-scope:**
- Sharepoint/Google Drive integration

**Implementation notes:**
It seems to be possible to assign an IAM policy to a cognito JWT token in a way that we can have a private S3 bucket and only authenticated users can get files from it (upload, download).

Articles:
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_cognito-bucket.html
https://medium.com/@ldarren/access-aws-s3-with-cognito-7c96fd1038f0

**Comment by sergiogcx** [comment]
This should be feasible, here are my findings:
https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/4467

**Comment by sergiogcx** [comment]
Another interesting article, it talks about setting up the cookie and lambda validator.
https://medium.com/@vasilii.trofimchuk/lambda-edge-and-jwt-authentication-to-protect-sensitive-components-of-your-reactjs-app-901e0c10fd35

**Comment by sergiogcx** [comment]
There is a branch, not a PR yet:
https://github.com/cityofaustin/atd-moped/tree/4423-sg-cloudfront

**Comment by sergiogcx** [comment]
PR ready btw, here is the link:
https://deploy-preview-219--atd-moped-main.netlify.app/moped/

Unfortunately, the only way to test is to log in, go to any page with database interactions (ie. the projects page) and wait for one hour, you should see the spinner and the page refresh.

**Comment by sergiogcx** [comment]
I've converted this issue into an Epic, it will be a rather large task. There are two approaches we can follow and I am making note as follows:

**Comment by sergiogcx** [comment]
## Subdomain Approach

Why do we need another way to deploy our PRs?
- S3 does not handle JWT requests, but CloudFront does. 
- We need a way to pass the JWT Token to CloudFront efficiently (Ideally using a single cookie, or passing the token per every secure request)

Why not use localhost instead?
- Cookies are isolated per domain, localhost is a different domain than anything on the cloud. Unfortunately, we would not be able to use cookies locally and on the cloud.

Can localhost be used at all?
- Yes, we still use localhost and connect it to CloudFront/S3?
- We will need a special component that passes a JWT Token for every protected file in CloudFront/S3.

![Moped Subdomain.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/50ab7dcb-18df-4992-a0c9-c41c5bbb363c)

**Comment by sergiogcx** [comment]
## Subdirectory Approach

This approach is similar but uses subdirectories in a single domain. This provides the advantage of having SSO for our PRs. The disadvantage could be "cookie collision", we need to be careful to isolate the cookies per subdirectory or test what the behavior would be if we have the same cookie for all PRs (i.e., log in once and use that cookie to authenticate for all other PRs).

Notes:

![Moped - Subdir.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/03b4baa1-7460-4ef4-8ceb-da1ce15d06d9)

**Comment by amenity** [comment]
@sergiogcx - Would it be possible to rename this epic? `Single Sign-On | Implement JWT S3 bucket access` doesn't encapsulate all that you've got in here 😅... 

Can I rename it "[Feature] Document Repository" and add some of the information from #3661 to the description?

**Comment by amenity** [comment]
@amenity - based on [3/23 Sprint Review](https://web.microsoftstream.com/video/0f6d4784-1d02-469b-ae54-d0b1cb5a74a8) make an issue for enhancements: File "types"
- Work Instructions/Authorization, e.g. Rain gardens for contractors, Signs and Markings
- Approvals and authoritative files, usually emails that might Sealed plans
- Knack integration
- Data Collection from Knack or directly from - e.g. speed or volume requests, e.g.
- Folder in the G drive for every project

**Comment by amenity** [comment]
@sergiogcx — Is it necessary for #5302 and #5300 to be in this epic?
