### ISSUE TITLE
Update - Contact info on Payment Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4438]
Would it be possible to change the contact # for payment on the payment options page. Hector who is our admin person here hasn’t been trained on the process yet.
https://atd.knack.com/parking#payment-options/

You can put my number down & Daniil’s

Steve Ingenito 512-974-2891
Daniil Kontsevoy 512- 974-1613

**Comment by ChrispinP** [comment]
duplicate issue. completed work in issue #4446
