### ISSUE TITLE
PSM User Permissions: PLA Updates

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4445]
The PSM will require Supervisor role permissions for user to be able to issue the folder. 
- Paloma has sent a list of users to Tracy. 
- Work w/ Nate to get this done by 11/20.

**Paloma confirmed we should give the permissions to Evelyn and that will suffice until the V7 upgrade.**

**Comment by TracyLinder** [comment]
Per Paloma: Give Evelyn the permit supervisor role; leave others as-is.

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please promote the changes to Evelyn's test account to PROD?

**Comment by Nadin-Nader** [comment]
@TracyLinder Automation has been set to update Evelyn's PROD account role and Database Security from Non-Escrow Permit Technician to Non-Escrow Permit Supervisor.

**Comment by TracyLinder** [comment]
@Nadin-Nader thank you 🙏
Will you please let Evelyn know that it will be updated and her password will change?

**Comment by Nadin-Nader** [comment]
@TracyLinder i let Evelyn know via chat. I will also send an email. As for the password changing...on TEST it did but since we did an Update via the automation to PROD, the automation just updates the profile with the changes.
