### ISSUE TITLE
[Update] Update all table views for ease of usability and readability

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4449]
- [x] Permit Application (Permit Management and Backlog Apps)
- [x] Permits
- [x] Customers
- [x] Addresses
- [x] RPP Zones
- [x] Transactions (Paid and Unpaid)
- [x] Cashier Tracking

**Comment by ChrispinP** [comment]
I updated all RPP Staff tables so they are easier to use and look nicer (not span past the page if necessary) with some formatting changes and html tags.

Ready for Review

**Comment by moorerst** [comment]
@ChrispinP   Reviewed all tables they look good.
One question - on the Customer Page what is the column Associated Apps? 
Most often it has the same application id as the Application Details column.

**Comment by ChrispinP** [comment]
Im not sure necessarily why both fields are present/needed. Did not build it unfortunately. Something we can look at in the future though.
