### ISSUE TITLE
[Feature] Allow RPP Staff to Issue multiple Day Passes at once

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4450]
Ability for RPP Staff to issue multiple Day Pass permits at once.

They are currently not using the form as intended and are using similar to their spreadsheet methods.

The form as of now is meant to add one permit at a time with its respective serial # . When they add Day Passes, they are inputting the range of serial #'s instead of individually. This will cause data discrepancies if continued to be used in this way since the permit object is meant to be a single permit record not multiple. RPP Staff use the form this way because its easier for them even though not correct.

A) We need a solution that allows them to enter a range of numbers and based of that, creates separate Day Pass records
or
B) Create a new day_pass_bundle object that is specifically for Day Passes only where each record is equal to 1 - infinite number of Day Passes. There would be a different form to issue Day Pass permits into this object. This object would be connected to the permit_application object 1 to 1.

**Comment by ChrispinP** [comment]
I was sketching how we would do this and I think JS is the best approach rather than using equations and auto-increment fields. First we create two new Number fields, a minimum permit # value and a maximum permit # value. With JS we can create an If-Then loop that would calculate the difference between the two values (max - min = # of day passes) and then iterate a increment loop. Starting with the Minimum number, For each i, +1 , up to the Difference value(aka number of day passes) it would insert a day pass record with that permit # value thus inserting a record upon each iteration. Once it hits the Difference value it inserts that last record and also creates a Day Pass Bundle object. We would then use a text formula field to display the range of all day passes for an application in this bundle object.

**Comment by moorerst** [comment]
@ChrispinP Per John display the Number of Permits and Passes field for the RPP staff to use for total # of day passes issued.
This field would also be used for reporting.

**Comment by ChrispinP** [comment]
so ive done some more testing on this and discussed a couple possible routes with Diana.

1) in Test I was able to pull the left and right values from a field (granted its only a range) with text formulas and assign them to number fields. But unfortunately this is only two values. In order for an equation to run a ternary operation to subtract the bigger serial number from the smaller serial number until those number fields would have to already be set and then iterate each number to create a value and then set that to its own unique number field. I would unreasonably need as many number fields to cycle through the entire range of numbers. (a good 20 fields at least if we limit to that). I would then insert a permit record for each number field that was not blank with that serial number.

2) second alternative is to create a new form and two inputs. I would again have like 20 equation fields that pull a serial number from that range and then the submit button would insert new permit records for each equation field that had a value.

3) third option is something we do with data tracker or signs and markings where you can create multiple jobs for a work order. difference is we need to understand if permit serial numbers are unique. if they are, this solution may not work since we could create a trigger button that would insert X number of permits following the pre-existing order of serial numbers for existing permits. for example if we had serial number 1555 day pass issued and wanted to issue 20 day passes. we would trigger the record inserts but those 20 day passes would have serial numbers 1556 to 1575 and would not be customizable.

if none of these solutions are feasible we would need to re-educate RPP staff on only entering permit records one at a time. we could reinforce this habit with some regex validation on the serial number field to limit to a single serial number only.

**Comment by moorerst** [comment]
option 2 as a starting point to capture permit range.
Discuss at next sprint review

**Comment by ChrispinP** [comment]
so mocking up and evaluating the multiple day pass options i suggested above, I believe all are too messy to get working correctly and end up with us just circling back to inserting single day passes at a time. Knack has no built in function to insert N number of day pass records.

so re-evaluating, my 3 suggestions are such moving forward: 

1) another automation tool (webhook/integration) that inserts multiple records for us with a form submit/trigger button 
- such as Integromat or Zapier
![image](https://user-images.githubusercontent.com/67915167/107818342-12c0f400-6d3d-11eb-897a-4bb2176ac6bd.png)
[Integromat](https://www.integromat.com/en/integrations/gateway/knack)

2) custom JS that inserts multiple records

3) we remove all entry fields for inserting Day Pass permits so staff can just keep clicking the button for how many records they want to insert and we autofill the permit info (fields set and serial number set to an auto-increment)

**Comment by moorerst** [comment]
meeting scheduled for 3/2

**Comment by johnclary** [comment]
With [#4754](https://github.com/cityofaustin/atd-data-tech/issues/4754) complete, we can backlog this for now. Question for staff: is there a need to track day passes individually (rather than as a range of serial numbers), particularly when looking ahead to the transition to fully digital permitting.

**Comment by moorerst** [comment]
Discussed in the Sprint Review on 3/11 - there is no need to track day pass serial #'s individually. Having the ability to enter the Total # of Day Passes and the range of serial #'s works for them.
