### ISSUE TITLE
Create template for AMD to update all detectors on a given signal

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4458]

**Comment by johnclary** [comment]
@SurbhiBakshi columns for template:
- Signal ID
- Date
- comment

This template will be used for the MMC to document all signals which were checked and *did not have an issue found*. If a signal has a detection issue, they'll need to report that through the normal process via the UI.

**Comment by johnclary** [comment]
@SurbhiBakshi to double-check that Lance has a copy

**Comment by SurbhiBakshi** [comment]
@johnclary - sent the template to Lance.

**Comment by SurbhiBakshi** [comment]
@johnclary - Checked with Lance B and Billy H yesterday to make sure they have the  template  and it works for them. They have the template, think it will work for them. They will send any batch updates to us.
