### ISSUE TITLE
Prep Product Session for DTS Retreat

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4461]
- [New website](https://github.com/cityofaustin/atd-data-tech/issues/4199 ) 
- Updates to DTS Github/Zenhub workflow
- ...

**Comment by amenity** [comment]
@JaceDeloney suggested getting feedback from Builders on how Product peeps can better support the rest of the DTS team. I love this idea. We could create an anonymous feedback/satisfaction survey in advance to structure the discussion, or we could do an activity at the retreat itself. @TracyLinder @moorerst @johnclary - thoughts?

**Comment by TracyLinder** [comment]
Sounds like a great idea! I'd love to hear suggestions for improvement. I like doing it in advance of the retreat.

**Comment by amenity** [comment]
@TracyLinder - do you want to take the lead on the survey?
