### ISSUE TITLE
Determine formats for customer communications

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#447]
How might we...
 - Give customers regular updates on the status of their requests? 
 - Collaborate with customers to maintain accurate prioritization of backlog items
 - Increase organizational visibility into what we're working on and for whom

The easiest option is just leveraging the power of Zenhub filters to give someone a URL they can visit or that we can pull up in meetings with them. However this requires them to install a browser plugin, and the interface can be really overwhelming.

**Comment by amenity** [comment]
![screencapture-app-zenhub-workspaces-data-technology-services-5caf7dc6ecad11531cc418ef-board-2019-08-07-12_58_14](https://user-images.githubusercontent.com/1463708/62656944-eac42980-b92a-11e9-96ce-3cd4464f968b.png)
Screencapture of AMD's stuff 😬

**Comment by amenity** [comment]
@johnclary and I discussed the idea of building a simple dashboard on transportation.austintexas.io that would allow people to see issues & pipelines in a less noisy view. [Here's an example](https://portal.productboard.com/zenhub/1-zenhub-s-roadmap/tabs/2-under-consideration), from ZenHub, ironically, that I like.

**Comment by johnclary** [comment]
@amenity i like that too

**Comment by amenity** [comment]
I think this will be covered by #1903.
