### ISSUE TITLE
Migrate MMC activities publisher to new AWS ETL

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4470]
Migrate the MMC activities publishing ETL from atd-data-deploy to atd-knack-services. [This](https://data.austintexas.gov/dataset/-UNDER-CONSTRUCTION-Mobility-Management-Center-Act/p7pt-re4k) is the destination dataset.

**Comment by amenity** [comment]
@johnclary - bump to Sprint 39?

**Comment by johnclary** [comment]
Fixed in November [here](https://github.com/cityofaustin/atd-knack-services/commit/bd61a2244e9c224a470851aa9a3941fc46618f2d).
