### ISSUE TITLE
Add `unique` constraint to Knack AGOL layers' primary keys

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4472]
In order to support [upserting](https://developers.arcgis.com/python/api-reference/arcgis.features.toc.html?highlight=upsert) via the ArcGIS Python API, we need every layer to have a unique constraint applied to its primary key field. Otherwise the atd-knack-service [upsert](https://github.com/cityofaustin/atd-knack-services/blob/602d135d060f9ec4483c92a2d764e2c52f4a8328/services/records_to_agol.py#L56) will fail.

TODO:

- [signals layer](https://austin.maps.arcgis.com/home/item.html?id=e6eb94d1e7cc45c2ac452af6ae6aa534&view=list&sortOrder=desc&sortField=defaultFSOrder): `SIGNAL_ID`
- ...

**Comment by alan-deanda** [comment]
@johnclary  are there other layers that you still need me to add unique constraints to?

**Comment by johnclary** [comment]
Nope—thanks! Now that I see how to do this in the UI I'll knock them out as I go. Closing.
