### ISSUE TITLE
SCP3 Site Corrections Bug (In Prod)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4478]
### From Stakeholder:
I have a new site correction permit #12480836 that was created exactly how it was supposed to be. The applicant uploaded the revised plans thru the portal and it came in as “CC Pending” – yay!
**However…. The info tab is not updated and it did not assign to the correct reviewers.
INFO TAB – still looks the same. The default reviewers are not on the pick list.**

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/965b71ea-10de-4ac4-8dc6-835b839db975)

**Comment by TracyLinder** [comment]
**Email from Unisys:**

I will have someone take a look. I think I know the issue but want them to confirm first.

Thanks, 

David

**Comment by amenity** [comment]
@TracyLinder - this is AMANDA, right?

**Comment by TracyLinder** [comment]
Amanda label has been added. 😁

**Comment by amenity** [comment]
😺
