### ISSUE TITLE
Project: Mobile Signs Work Orders

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#448]
Develop a mobile-first web application to be used by street sign technicians to complete work orders in the field. This project builds on the React framework we've used for [Mobile Signal Work Orders]( https://github.com/cityofaustin/atd-data-tech/issues/251)

**Comment by johnclary** [comment]
@amenity @TracyLinder this does not need to be run through intake yet, I just want to keep it on our radar. I've set Mobile Signal Work Orders as a blocker.

**Comment by ChristinaTremel** [comment]
- Closing this issue because we are not going the direction of mobile sign work orders. We will be looking for a solution in #3163.
