### ISSUE TITLE
TIA MOD: Automate Request Status Field

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4480]
### The Request Status should, as much as possible, automatically update with the case workflow
- eg When Scope status is set to 'Revision Required', the Request Status field should update to 'Awaiting Reponse'

**Tracy needs to scope this out.**

**Comment by ChrispinP** [comment]
Added Review Status updates for the 3 Scope Status changes.

@TracyLinder Do these look correct?
![image](https://user-images.githubusercontent.com/67915167/99992559-1c5d4000-2d7c-11eb-9ee2-50c96f2d2d07.png)

**Comment by ChrispinP** [comment]
Also added one for the Review Status and 4 for the Submission Status.

Ready for Review

**Comment by TracyLinder** [comment]
Tracy & Chrispin will need to test this together during a project mtg w/ stakeholders.

**Comment by TracyLinder** [comment]
This is looking good. Likely to be some changes in the future as testing continues. Closing.
