### ISSUE TITLE
TIA MOD BUG: Fees Paid Date Requires Time

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4481]
### Remove the time from this form

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/4acdebde-3ca7-4a6d-9011-306fa8777473)

**Comment by ChrispinP** [comment]
Time is required when Knack date field uses both date and time. Reverted the change so that Fee Paid Date is only a date entry.

Ready for Review

**Comment by ChrispinP** [comment]
no longer an issue, closing
