### ISSUE TITLE
TIA Scope Comments Customer Email Template Update

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4482]
### Update the customer email template that is sent when a scope comment is saved. 

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/f4c36a34-1465-4271-96a4-262f296a617c)

**Comment by ChrispinP** [comment]
Updated all emails. Formatting and language updated. Added Requester name to body and Request ID to subject.

I am also wondering if we shouldnt add a footer as well to make them look more professional. Not sure. Otherwise, these should be looking better now.

Ready for Review
