### ISSUE TITLE
TIA Submissions Feature: Ability to send attachment w/ comment

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4483]

**Comment by ChrispinP** [comment]
The ability to add attachment and comments on the same page has been configured. Will need to decide if we still want to allow them to be added individually as well and therefore either remove or keep the existing menu buttons. May also want to rename the Add Attachment/Comment menu button name as well for simplicity/clarity.

Ready for Review

**Comment by TracyLinder** [comment]
This has been tested; closing.
