### ISSUE TITLE
TIA MOD, Submissions

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4484]
- When revisions are required, The customer needs an email w/ instructions
- The user needs to be able to view, from the Submissions page, each submittal & it's details.

**Comment by ChrispinP** [comment]
Should the requester have the ability to edit their submissions at any time? Should we allow a reviewer to request more than one submission(send email) if submission changes are needed from the requester? Currently reviewers are locked out after requesting the first submission.

The submission email has a link for their custom TIA Case Details page where they can add submissions and view other case details.

**Comment by ChrispinP** [comment]
Reviewers can now request as many submissions as necessary and specify the type of submission. requester will receive an email when the reviewer sends this request. A link to the requester's case details will be in the email.
