### ISSUE TITLE
Explore needed updates to JS projects to make use of optional chaining and nullish coalescing

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#4485]
We've talked about some newer JS syntax in dev syncs that could make life easier, and we should look into what steps are needed to start using in existing (VZx and Moped) and new React projects or anywhere else.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by chiaberry** [comment]
I think we have been doing a good job of doing this as we refactor code, closing
