### ISSUE TITLE
Update VZE Dashboard

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4498]
The current VZE Dashboard widgets are incorrect (known issue). As more people have been using VZE, we need to make this home screen experience more engaging and useful. Here are the current ideas:

**Tasks**
- [ ] Remove dashboard widgets 

**VZE Metrics**
- Metrics to help prioritize crash record reviews/updates (e.g., Number of changes that need review, number of crashes with unassigned locations)

**Links**
- Investigate including VZ Power BI dashboard views
- Investigate including VZ ArcGIS maps

**Comment by patrickm02L** [comment]
Review stats widgets for accuracy. 

VZE Metrics could be an addition to [#5973](https://github.com/cityofaustin/atd-data-tech/issues/5973)

Links have already been added.
