### ISSUE TITLE
Increase accessibility of officers' on-shift notes to ATD staff

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4499]
Currently officers add notes to their spreadsheets and these are used to
- Identify when ATD is being charged when they shouldn't be, e.g. when the officer isn't working their hours due to a vehicle malfunction
- Gather information on safety concerns from officers

PowerBI would be wonderful so ATD staff can do all their invoice review and program management in a single application, otherwise adding "Details" modals to Randy's invoicing page and giving David, Jen, and Lewis access.

**Comment by SurbhiBakshi** [comment]
- [ ] Create an API view table for Notes
- [ ] Export as CSV and connect to Power BI.

**Comment by SurbhiBakshi** [comment]
**Fields** 
- [ ] Assignment Date
- [ ] Assignment Time
- [ ] Assignment Location
- [ ] Officer Name
- [ ] Officer Badge number?
- [ ] Note Type - Cause for Concern/ No Violation Observed/ Period of Inactivity?
- [ ] Note
- [ ] Note Time Stamp
