### ISSUE TITLE
Rolling Needs Assessment 2020

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#4505]
Map new projects for the RNA 2020, and QA/include projects from RNA 2019.

**Comment by alan-deanda** [comment]
- [x]  2020 Projects have been mapped, though sub-project IDs may change.
- [ ] QA RNA 2019 Projects

**Comment by johnclary** [comment]
@alan-deanda what's the latest on this?

**Comment by alan-deanda** [comment]
@johnclary  I forgot to move this to Review/QA. I've finished the work, but have not heard back from Chris. I'll reach out to him to check if they're satisfied with the RNA.
