### ISSUE TITLE
Project Staffing | Add "Notes" column to "Assign team" table

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4507]
During #4489, we determined that the "Project role" taxonomy will be more concise and flexible if we allow users to add a note to clarify the role a particular team member has on a given project. 

- Instead of having numerous roles specific to a given workgroup — such as "ERI Support", "Utility Coordination", "Permitting" — we can use "Project support" as a catch-all. 
- When someone is handling a specific aspect of a role, like performing project coordination with a particular vendor, we can make that information easily accessible

![Project Team](https://user-images.githubusercontent.com/1463708/99586033-c586ed80-29ac-11eb-823a-b2e17b43eceb.png) 

Let's start with a character limit of 75 and adjust if necessary.

**Comment by amenity** [comment]
@zappfyllc - does the Notes data go into the moped_proj_personnel table? @sergiogcx - check to make sure this is good w/ you, too.

**Comment by amenity** [comment]
@zappfyllc confirmed that this will be a text column in the moped_proj_personnel table.

**Comment by lazavazav** [comment]
the branch 4507_lz_projNotes was accepted to merge and the branch has been deleted. This issue can be closed.
