### ISSUE TITLE
Update Unit Code on 2 OSE Fees

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4511]
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/266030c9-74e1-4644-80d0-552a0196b050)

**Comment by TracyLinder** [comment]
Per Van, we are unable to record revenue when the unit code is wrong; so this is a major issue.

**Comment by Nadin-Nader** [comment]
AMANDA Admin/Developer account needed to work on this

**Comment by aishwarya2505** [comment]
This has been committed. ATD #4511 Commit ID: 27d70bd4502f. Post COA Review, I will be sending the commit request for DEV

**Comment by aishwarya2505** [comment]
The DEV Deployment Plan for this card has been emailed. Waiting for DEV Deployment

**Comment by Nadin-Nader** [comment]
@aishwarya2505 I have sent this to the DEVOps Team to deploy to DEV under **SCTASK0133093** for **Commit- 27d70bd4502f**

## **Status:**
Waiting on DEVOps CM Team to deploy to DEV

**Comment by aishwarya2505** [comment]
The DEV Deployment Plan for this card has been emailed on 4/14/2021.  Waiting for DEV Deployment.

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @Sreelatha-BlazeKannan @tracy This has been deployed to DEV by Martin

## **Status:**
Ready for DEV UAT

**Comment by sreelathab** [comment]
@Nadin-Nader @TracyLinder  - Verified in DEV and the fee unit code updated to "9100" successfully. 

![image](https://user-images.githubusercontent.com/65371095/117186852-e0a1ba00-ada0-11eb-9e99-f45716e5b07f.png)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan lets go ahead and get this on TEST. If you send it to CTM, Please let me know the TASK number and commit for tracking purposes.

**Comment by Nadin-Nader** [comment]
##**Status:**
Ready for TEST deployment  🎉

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder - TEST Deployment plan for Card #4511 has been sent.  and created servicenow request Task Id: SCTASK0136223

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan looks like this was completed and deployed to TEST per George.

## **Status:**
UAT on TEST/ Schedule UAT on TEST with Stakeholders

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan spoke to Van and it looks like all is well and good to promote PROD

## **Status:**

## Ready for PROD Deployment 🎉🎉‼

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder  - PROD Deployment Plan sent on 05/12/2021.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder CM Team has deployed this and it is now on PROD and Ready for Stakeholder UAT.

##  **Status:**

## **Ready for UAT on PROD

**Comment by Nadin-Nader** [comment]
@Nadin-Nader Schedule UAT with Van

**Comment by Nadin-Nader** [comment]
Van verified  via chat that the unit code 9770 does not exist and is using the 9100:

> [5/19 2:01 PM] Pham, Van
>     here is the fee code for Street event Application fee 5125 2400 **9100** 4502

Closing.
