### ISSUE TITLE
Meet w/ RPP staff to review purchase of replacement, renewal, and additional permits

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4512]
Do permits renew at different times depending on when you bought one?

> All permits expire at the same time regardless of when the permit was purchased. Orange zone expires end of August and all others expire at end of calendar year. Staff receive the new physical. permits ~6 weeks before renewal date.

_Todo: Add multi-choice field to the application that allows the applicant to indicate if they are renewing, replacing, adding additional permits, or applying for the first time._ @ChrispinP is on this.

How are replacement permits priced?

> They are priced as if the customer is buying additional permits. So if the customer has two permits and loses one, the replacement cost is the cost of a third permit.

How are you tracking the prices for replacements and additional permits today, given that the system does not allow you this flexibility?

> We are entering the actual amount paid in the the comment field.

We cannot show the customer an invoice for a replacement permit because we don't know how many permits we have. What should we do about that?

> It is ok to not show an invoice to the customer until the application is reviewed by RPP staff.

_Todo: John to review cost management and add flexibility for staff to edit the cost manually._

_Todo: Chrispin is going to work on a revised invoice page that does not show costs, it will only show the pricing break-down._

How soon do you need this?
> We need this as soon as possible as we are ready to send out the renewal notices.

_TODO Estimate the level of effort to make these changes and provide RPP an update by end of day tomorrow._

What do you think about having user logins?

> We want to go live with completely digital permitting (with license plate readers) by the end of calendar year 2020. We are absolutely going to need user logins! The decals, hangtags, and day passes will all be digital. A customer will need to be able to assign a hangtag to a vehicle for 24 hours. Day passes will need to be able to be assigned to vehicles. We will need online payments as well!

@moorerst ^^^ this is a big project coming our way. i'd like to start planning for it in January.

**Comment by ChrispinP** [comment]
My Notes:

- Customers need the ability to renew/buy permits early (up to 6-8 weeks in advance)
- Permits only last Y-Y (Jan to Jan or Aug to Aug)
- Warn customers who select to purchase additional permits for the same period with Renewal period coming soon
- If a customer loses a permit, they are charged as if buying an additional permit (lose permit 1, charged the cost of permit 2)
- If a customer loses multiple permits, it works similar (lose permits 1, 2, & 3, charged the cost for permits 4, 5, & 6)
- A customer can only be charged up to permit 6 (lose permit 6, charged the cost of permit 6 to replace)
- An online account will be necessary to facilitate the future permit digitization process so customers can update the license plates connected to their permits at will
- RPP Staff currently notating replacement costs in payment notes field
- Residents living at the same address abide by the principal they are one customer (6th resident charged for permit 6)
- The ability to indicate if a customer is a new resident, and if so, charge at original rates
- The ability for RPP Staff to indicate a pricing adjustment and provide a reason for it

**Comment by moorerst** [comment]
closing complete - moving forward with enhancements based on meeting details
