### ISSUE TITLE
[Update] RPP Review and Invoice Page Cost Text

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4513]
Update the invoice page to specify estimated costs instead of actual costs. The invoice page will no longer be an "invoice" page. Show permit cost info on this page for reference for buying additional permits, renewing, new customer, or replacing.

Build in test first.

**Comment by ChrispinP** [comment]
**In Test:**
Updated views to show Estimated Cost text instead if the Application Type selected is either Replacement or Additional.

**Comment by ChrispinP** [comment]
Set to move to production and test on Tuesday

**Comment by ChrispinP** [comment]
Since we are now calculating real costs, there is no longer a need to push the text changes to the invoice page in production. I did update the Review page instead with 'Final' values since these fields will be used by the JS calculations now. We will no longer be using a multiple choice field and conditionals to determine cost.

**Comment by moorerst** [comment]
@ChrispinP can this one be closed?

**Comment by ChrispinP** [comment]
no further action, closing
