### ISSUE TITLE
[Update] RPP Permit Application Type

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4514]
Add permit application type field to determine the type of application the customer is submitting; new, renewal, replacement, or additional. Update logic flow and costs accordingly. If renewing, provide another option for renewal period. If renewing for current year, provide a warning message about permit expiration.

Build in test first.

**Comment by ChrispinP** [comment]
**In Test:**
added application type field to customer information page of the application with the 4 options. the permit information page shows a read-only value to change the text of the Number fields to make more sense to the user based on application type. Info text is added below the field to help users select the correct option. Added these same elements to the edit application page.

Need some custom JS to display a warning message on the customer information page either after selecting application type or on submission to save and continue.

**Comment by ChrispinP** [comment]
Set to move to production and test on Tuesday

**Comment by moorerst** [comment]
@ChrispinP I tested using Type - Additional I requested 1 decal and 1 hang tag no day passes. 
On the Permit Information Page got message that Number of Day Passes is required
Can Day Pass field default to 0?

**Comment by ChrispinP** [comment]
Day Pass field will now be required and default to 0. Permit Application Type logic has been added to both the permit information page and the edit application page. Pushed these changes to Production.

The custom JS message would be a still nice to have to warn applicants of their selection.

**Comment by moorerst** [comment]
tested and confirmed complete. Has been put into production
