### ISSUE TITLE
Set up Google Analytics on all Knack apps

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4516]
Analytics would help us make informed design and information architecture decisions about our Knack applications, e.g. where are people dropping off in the RPP registration process? Where do we most need to optimize for mobile devices?

- [ ] Learn how to [do this in Knack](https://support.knack.com/hc/en-us/articles/360015668211-Can-I-add-Google-Analytics-to-my-Knack-app-)
- [ ] Generate the code needed for DTS' universal Google Analytics account - @mateoclarke do y'all have this documented somewhere?
- [ ] Add to an app and document process in Gitbook

Epic-ate this issuse and create sub-issues as needed, see #3924. 

 If this turns out to be a lot of work, our public-facing sites are the most important: 
- RPP
- TIA module

cc/ @TracyLinder @moorerst.

**Comment by mateoclarke** [comment]
analytics.google.com
Sign in with "ATD Data & Tech Gmail Account" in 1P.
Let me know if theres a good place to document that or what you had in mind.

**Comment by TracyLinder** [comment]
@amenity is this still something that should be in the backlog? What's the next step?
