### ISSUE TITLE
Project Extent | Publish location polygons as vector tile layer to AGOL

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4521]
We need to fully understand AGOL's vector tile functionality. We need the VZ location polygons published as:
- a hosted tile layer
- a tile layer package

**Comment by amenity** [comment]
@alan-deanda - can you provide and estimate for this? Are you able to do it this this sprint?

**Comment by alan-deanda** [comment]
I've created a web map containing the hosted tile layer [here](https://austin.maps.arcgis.com/home/webmap/viewer.html?webmap=c1b42b638c7f416fbd70086f3b291ce2). It is currently being shared with the organization, you'll need to log in to your AGOL account to view it. 
The map, the hosted tile layer and the tile layer package are all saved in the new MOPED folder, for those with ATD_Publisher AGOL logins.

**Comment by johnclary** [comment]
thanks @alan-deanda! FYI I went ahead and shared this content publicly to make it easier for the dev work we need to do.

**Comment by alan-deanda** [comment]
I published Vector Tiles with IDs by highlighting the fields in the tile creation process.
ESRI documentation can be found [here](https://pro.arcgis.com/en/pro-app/help/data/services/use-vector-tiled-layers.htm) and [here](https://pro.arcgis.com/en/pro-app/help/mapping/map-authoring/author-a-map-for-vector-tile-creation.htm#GUID-3A2EEC7F-6993-4956-8D92-2C676B8A81C5).

**Comment by amenity** [comment]
LGTM! Thanks, @alan-deanda.
