### ISSUE TITLE
Knack JS: Ability to hide field from user but submit value

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4523]
In Knack, I need some help figuring out how to hide a form field from the user and to set its value with javascript. It would seem that hiding the field with `display: none` or the `hidden` property will cause the field value to be ignore when the form is submitted.

Here's a form to test with:
https://atd.knack.com/knackpy-development-app-production#tests/

And here's the app in the builder:
https://builder.knack.com/atd/knackpy-development-app-production#data

Test case:
- hide **Test Short Text** and **Test Number fields**
- set those fields to the value in the **Default Value Number** field

**Comment by mddilley** [comment]
After experimenting with some solutions, I noticed that once the form is submitted in Knack, a [`disabled` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) is added to the hidden fields. This prevents it the form values from submitting with the form.

Things that I've tried:
- Moving the inputs outside of the elements that Knack wraps them inside but still within the form tag
- Removing the id attributes (so maybe Knack wouldn't be able to target them)
- Using jQuery [`.change()`](https://api.jquery.com/change/) to listen for the `disabled` attributes
- Using Knack [Record Create event](https://www.knack.com/developer-documentation/#record-create) in attempt to mutate the payload (looks like it just passes the record that was already sent to Knack)
- Using [this SO answer](https://stackoverflow.com/a/26674017) about listening for `disabled` attribute change, form still didn't submit input values after re-enabling with jQuery on change

**Comment by mddilley** [comment]
@johnclary The jQuery to grab the default value and populate the hidden inputs as well as the CSS to hide those fields is now in https://builder.knack.com/atd/knackpy-development-app-production#data and ready to test. I included the code below since it isn't in a repo right now.

JS
```
$(document).on("knack-view-render.view_17", function (event, view, data) {
  var defaultValue = $("#field_134").val();
  
  // Set values of CSS-hidden elements
  $("#field_131").attr('value', defaultValue);
  $("#field_132").attr('value', defaultValue); 
});
```

CSS
```
/* Hide form inputs but still submit values */
#kn-input-field_131, #kn-input-field_132 {
    visibility:hidden;
    height: 0px;
}
```

**Comment by johnclary** [comment]
thanks @mddilley!! will give this a try

**Comment by johnclary** [comment]
Worked like a charm in the RPP app. I ended up creating a custom class so that I can dynamically apply this class as needed. i did need to tweak the div margin as well. so the final CSS for me is: 

```
.hiddenFormField {
    visibility: hidden;
    height: 0px;
    margin-bottom: 0 !important;
}
```

Thanks again Mike!
