### ISSUE TITLE
Project Extent | Compile a shapefile of off-street trails

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4528]
@frankhereford is going to polygon-ize urban trail data for us so that Moped users can also select those polygons when mapping project extent.

**Comment by alan-deanda** [comment]
@amenity , @johnclary , @frankhereford , I've finished mapping trails from Urban Trails and imagery in the area, and I've exported them to a shapefile located in: G:\ATD\ATD_GIS\CTN\MOPED.

**Comment by johnclary** [comment]
thanks @alan-deanda!
