### ISSUE TITLE
Bug: DS Permit Report (50506)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4537]
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/d8c98dd3-93ea-4b4f-ab2d-8821907d0509)

**Comment by TracyLinder** [comment]
**Status:** Sree has completed in local. Next step is to submit deployment for DEV.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have deployed the form to DEV
Please UAT

**Comment by TracyLinder** [comment]
RSN 10119057 in DEV looks good. 

### Please promote to TEST

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Promoted to TEST and Tested. Ready for UAT. FolderRSN: 12378278

**Comment by TracyLinder** [comment]
Test permit looks perfect. 

### Approved to promote to PROD 🎉

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I have sent the deployment for PROD to the CTM Team to deploy under TASK **SCTASK0107575**

**Comment by Nadin-Nader** [comment]
Checked and this has not been deployed to PROD yet by CTM.

## **Status:**
Waiting on CTM to deploy to PROD

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder This has been deployed to PROD per CTM
