### ISSUE TITLE
Meeting to talk to Data Collection team about spatial workflow and spatial enhancements 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#454]
Brandon B.
AMD - Data Collection

Had approached me about setting up a meeting to discuss streamlining their geospatial/attachment process for Traffic Counts. I said that mid August would be a good time for it because we were in the middle of the Sign Migration. 

### Processes to merge
1. **New Traffic feature layer** (that Frank Hereford worked on added TIAs volume counts) 
>He's given it to @jaime-mckeown to publish to AGOL and update the Traffic Count Web App
2. **Update traffic counts points in the Traffic Count Web App**
>We've merged the data sets into the new one on the first item. There were attachments that existed on those older features that we need to figure out what to do. Originally, the pdf files were being attached. We could update the process so that it points to the Data Tracker attached files that the team is updating now. 
3. **G drive network folder pulling Traffic Counts posting to Socrata Open Data Portal** (Status: Script is not  working)
>Requested to stop process, data sensitivity issue? _According to Jamie Atencio, this is what he told me_
4. **Traffic Count and Data Requests coming in to Data Tracker**
>They update status and attach the files requested on the request record

**Comment by jaime-mckeown** [comment]
@dianamartin, I completed steps 1 & 2 a while back, but just logged into AGOL to double check and found that the Web Map looks like it was corrupted as it won't open anymore, just opens a blank map. Maybe that's why the Socrata script isn't working. I will get the map re-created.

**Comment by dianamartin** [comment]
@jaime-mckeown I think it's might be a basemap issue. Go into AGO Assistant and update the basemap. Reference on he geospatial repo the issue of me updating the geocoder/basemap.

**Comment by jaime-mckeown** [comment]
@dianamartin that didn't fix it.

**Comment by dianamartin** [comment]
I believe this is a backlog project that we'd like to enable for the Data Collection Program, to be have a more integrated spatial component. At this time no one has escalated this again, I think it's seen as a "nice to have".

**Comment by amenity** [comment]
This potential work is represented in #1697 7.
