### ISSUE TITLE
Bug: ROW Deficiencies Folder Summary Report Errors (50514)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4540]
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/ca19299e-5e27-4f4a-8e3d-f627126927c9)

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/2a011ba8-8961-49f7-a946-66b77ddf72ed)

**Comment by TracyLinder** [comment]
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/9c012417-1c5c-4f0b-a786-0367096fc529)

**Comment by Nadin-Nader** [comment]
@TracyLinder Had the meeting and Subha informed me that she could not see the error or duplicate it. I tried to see if i could print the dock but my PROD login is admin and is limited so i cannot print this. I gave her the Conditions and Description. She is going to try to recreate it but would like to also have you try it with her.

The issue with the DSD inspectors, she is Checking the query for the attempt codes to see why they are coming up. She will let us know what she finds.

**Comment by TracyLinder** [comment]
**Status:** Subha is working on updating the report.

**Comment by Nadin-Nader** [comment]
@SubhaShroff I have deployed this to Dev and TEST

**Comment by shroffjs** [comment]
Thank you @Nadin-Nader. 
@TracyLinder The report 50514 is updated to restrict the attempts to TCI inspection and also I checked the each field properties in the report format and did necessary changes to avoid the possible occurence of 'Page Area too large' error. I have tested it on both DEV and TEST. 
Its ready for you to test.

**Comment by TracyLinder** [comment]
### UAT RESULTS (PASSED)

EX - 12384601
TURP - 12385936
ECV - 12395938

**Comment by TracyLinder** [comment]
### Approved for PROD 🎉

**Comment by shroffjs** [comment]
A ServiceNow Request : **SCTASK0108883** is submitted to move the updated report file to PROD server.

**Comment by shroffjs** [comment]
@TracyLinder @Nadin-Nader @Sreelatha-BlazeKannan SCTASK0108883 is closed, now the latest report must be in PROD.

**Comment by TracyLinder** [comment]
I will test this, and notify the stakeholder. Thanks for your good work @SubhaShroff

**Comment by Nadin-Nader** [comment]
@TracyLinder @Sreelatha-BlazeKannan @SubhaShroff this has been deployed to PROD
