### ISSUE TITLE
Fetch authoritative email addresses from CTM

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4546]
In order to complete our integration of Banner employee data with the HR app and the DTS Portal, we need to know an employee's email address. As it turns out, if an email address is created or changed after the employee is setup in Banner, there is no process in place by which Banner is retroactively updated to reflect the change. 

We need to be able to query some CTM resource by employee ID # and return their email address.

**Comment by johnclary** [comment]
I just emailed the CTM help desk:

> Hello,
> 
> I am in need assistance getting programmatic access to ATD staff's current email addresses.
> 
> Some background: we are integrating Banner employee data with our personnel management system. In order to create new users in this system automatically, we need to know an employee's email address. As it turns out, if an email address is created or changed after the employee is setup in Banner, there is no process in place by which Banner is retroactively updated to reflect the change.
> 
> I am hoping there is an Active Directory API or some other CTM database where we can query by employee ID # and return an employee's email address.
> 
> Thanks for your help.
> John

**Comment by johnclary** [comment]
Have been working with Jeffery H at CTM, who is going to drop a weekly export of this data on the G drive. I gave him the G drive path, which will be in our GIS/enterprise apps folder. Waiting to have confirmation that the export task is setup.

**Comment by johnclary** [comment]
Jeffery H has started putting the weekly email output on the network drive:
`.../ATD_GIS/02_ENT_APPLICATIONS/app_Human_Resources_Manager/_ctm_users_integration`

Todo:
Setup a process to process this data.

**Comment by chiaberry** [comment]
Addressed in PR for https://github.com/cityofaustin/atd-data-tech/issues/2167
