### ISSUE TITLE
Decide on Officer registration process

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4548]
- Avert situation where sergeants register since we have to pay them a much higher rate. 
- Ensure all officers doing shifts have been trained

Initially we were thinking Lewis would just share the link after he trained someone, but he points out that it could then shared with other officers. 

Two solutions come to mind: 
- Lewis gets an automated email whenever an officer registers
- Officers don't self-register; Lewis (or Randy, or us... but I think Lewis would be most efficient) creates officer accounts himself after training them. The benefit of this is that it's one less thing to train/support the officers with

What do you think, @SurbhiBakshi ?

**Comment by amenity** [comment]
Discussed today and agree that registering officers (whether VZ team or our team) makes sense. 

@amenity - ask Lewis if he is comfortable doing this. @SurbhiBakshi - turn off the officer account registration pages.

**Comment by SurbhiBakshi** [comment]
@amenity - the officer account registration has been turned off
![image](https://user-images.githubusercontent.com/13035849/100279144-967ff700-2f2b-11eb-83ae-60d3bd32ad1b.png)

**Comment by amenity** [comment]
We'll do a bulk import of officers who attend #4102 into the app. We'll need:
- Email
- Phone number
- Badge # (? @SurbhiBakshi, I see we don't have this for the pilot officers and we're still able to connect to Brazos in PowerBI...so can we do away with it?)

After that, we think that either of these would work as a starting point: 
- Lewis/VZ staff creates officer accounts once an officer has been trained - would need to expose this functionality in the Scheduler interface
- Lewis/VZ staff submits a DTS service request once an officer has been trained; DTS creates account
