### ISSUE TITLE
Bugs: Event Process and Fees on Other RW Permits

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4551]
### RW-Street Event features on the RW-TURP folder & RW-Film & RW-Parking

1. The system is inserting the 'Event Review' process. Then the system requires the user to complete the process before permit issuance.
2. The system is inserting RW-Street event fees on the TURP folder. 

**Example Folders:**
- 2020-124292 RW (TURP)
- 2020-171461 RW (Parking)
- 2020 179995 000 00 RW (Film)
- 2020 179996 000 00 RW (Film)
- 2020 178991 RW (Temp Valet)

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/8f544d5c-1d8f-498a-a910-a9f450f5d8de)

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/75dddf06-c4bf-4563-a34d-965a1ab04ae2)

**Comment by TracyLinder** [comment]
I just updated the description with film permit details that were reported to me this morning.

**Comment by TracyLinder** [comment]
**New report of issue on Temp Valet Folder 2020 178991 RW **
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/27dd79bf-b4bf-48b4-b1e0-8fe1ca8e0cbd)

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please take this up next, after submitting deployment for #4537

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader  - Fixed the issue and tested in Localhost. Email sent with test results on 12/8/2020. Upon approval DEV commit can be done. Thank you.

**Comment by Nadin-Nader** [comment]
@TracyLinder per Sree this has been fixed  and is working as expected. She would like to go over this wit you tomorrow morning if possible. I will set up the meeting for 10am tomorrow.

**Comment by TracyLinder** [comment]
### Approved to promote to DEV

**Comment by Nadin-Nader** [comment]
@TracyLinder @Sreelatha-BlazeKannan I have sent this over to the CM Team to deploy to Dev under TASK **SCTASK0108449**

**Comment by Nadin-Nader** [comment]
This has been deployed by the CM Team. UAT Ready

**Comment by TracyLinder** [comment]
### UAT Failed

The exclusions did not promote correctly. @Sreelatha-BlazeKannan will contact Martin about this and follow up w/ Tracy & Nate.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Martin confirmed that it is skipped and not moved to DEV and he has updated the phabricator link and mentioned that it will hit DEV in another 10 minutes.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - DEV Move Successful. Tested in DEV and all working as expected. here are the tested folders.

1. RW - Subtype - TURP - Folderrsn - 11898079
2. RW - Subtype - Film - Folderrsn - 11898085
3. RW - Subtype - Parking Spaces - Folderrsn - 11898087 
4. RW - Subtype - StreetEvent - work type - Neighbourhood - Folderrsn  - 11898092
5. RW - Subtype - StreetEvent - work type - Arterial/Collector - Folderrsn - 11898088
6. RW - Subtype - StreetEvent - work type - Safety Closure - Folderrsn - 11898091
7. RW - Subtype - StreetVendor - Folderrsn - 11898093
8. RW - Subtype - ValetOperator - Folderrsn - 11898095
9. RW - Subtype - ValetParkingAnnual - Folderrsn - 11898096
10. RW - Subtype - ValetParkingTemporary - Folderrsn - 11898101

**Comment by TracyLinder** [comment]
This is being assigned to @aishwarya2505. She'll start looking into it.

**Comment by aishwarya2505** [comment]
This is being tested on DEV. Post confirmation will be moved to TEST.

**Comment by TracyLinder** [comment]
@aishwarya2505 can you please add an update to this issue? Thank you.

**Comment by aishwarya2505** [comment]
@TracyLinder The demo for this card has been sent 4/21/2020. 

This is in DEV.

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @TracyLinder I have reviewed the Demo for this on DEV and it looks go to me.

## **Status:**
Ready to start the move to TEST environment

**Comment by aishwarya2505** [comment]
4/28 - Sent the TEST Deployment Plan on 4/26/2021

**Comment by aishwarya2505** [comment]
@TracyLinder Once this moved to TEST, I need to do a round of testing to make sure this is ready for UAT. I'll check with @Nadin-Nader on the PROD move for this one.

**Comment by Nadin-Nader** [comment]
@aishwarya2505 @Sreelatha-BlazeKannan I have sent this over to DevOps CM Team to deploy to TEST under **SCTASK0135073**

## **Status:**
Waiting on DevOps to deploy to TEST

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been deployed to TEST. I will go ahead and schedule UAT on TEST.

**Comment by Nadin-Nader** [comment]
@Nadin-Nader have Maria test SE side

**Comment by Nadin-Nader** [comment]
Spoke to Maria yesterday and she said she would UAT and get back to me.

## **Status:**

Waiting on Marias UAT of the SE Folder

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder  - PROD Deployment Plan sent on 05/14/2021. Commit ID: 160ba7521283 and Service Request # SCTASK0137696

**Comment by Nadin-Nader** [comment]
## **Update:**
Waiting on CM Team to deploy to PROD

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been deployed to PROD. I will send an email to the stakeholders and have them UAT and/or close the request.

##**Status:** 
**On PROD🙌🙌🎉**

**Next Steps:**
Have stakeholder UAT and/or close @Nadin-Nader

**Comment by Nadin-Nader** [comment]
Sent email to Kim and Paloma asking then to UAT this in order for it to be closed:

> From: Nader, Nadin 
> Sent: Wednesday, May 19, 2021 5:27 PM
> To: Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>; Perez, Kimberly <Kimberly.Perez@austintexas.gov>
> Subject: Bug: Event Process and Fees on Other RW Permits #4551
> Importance: High
> 
> Hi Kim/Paloma,
> 
> Hope you are doing well. I wanted to inform you that Bug: Event Process and Fees on Other RW Permits #4551 Is now on PROD and ready for your testing. Please let me know how the testing goes on PROD and let me know the outcome.
> 
> If all is well, please let me know and we can go ahead and close the request. 
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)

**Comment by Nadin-Nader** [comment]
Paloma would like to keep this open for about a week to see if they get any errors.

## **Status:**
Closing on 5/26/21

**Comment by Nadin-Nader** [comment]
All UAT was successful with SE and ROW folders. Closing card
