### ISSUE TITLE
[Bug] Cashier Tracking Filter Menu not showing Unpaid and Paid applications

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4554]
Cashier Tracking Filter Menu not showing Unpaid and Paid applications. It does show Ready for Payment applications.
![image](https://user-images.githubusercontent.com/67915167/100024823-25b2d080-2dad-11eb-82ab-de43f0a08b40.png)

**Comment by ChrispinP** [comment]
Checked back-end, records are recording Payment Status correctly.
Payment Status field conditional rule is working as expected.
Payment Information form submit rule is working as expected.
Removed conflicting conditional rules from the Payment Status field but still not working.

With all this in mind, im considering the cause for this bug could be either page hierarchy since it is not a child page of the applications OR the cashier tracking page was build on a specific object instead of blank page like old application pages were. If either of these are true, a page rebuild would be required.

**Comment by ChrispinP** [comment]
After removing the bad conditionals, I also removed the data source filter which allowed the unpaid and paid to show up since application status can vary. Should now be fixed.

**Comment by moorerst** [comment]
@ChrispinP confirmed this is displaying all statuses correctly

**Comment by ChrispinP** [comment]
Thanks Steph, closing
