### ISSUE TITLE
Feature: Customer Submission Resubmittal

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4558]

**Comment by TracyLinder** [comment]
I'm unsure of what this solution will look like. @ChrispinP and I will need to discuss further.

**Comment by TracyLinder** [comment]
Actually, let's discuss @ our next project meeting on 12/2.

**Comment by ChrispinP** [comment]
A reviewer now has the ability to set a submission into Revision status which notifies the customer via email. This status will display to the requester on their Case Details page. The requester would use the edit attachment form/page to add new documents to the submission and would then hit the Confirm button again to finalize and send submission for review. Attachment deletion will be disabled for previously uploaded documents.

**Comment by ChrispinP** [comment]
The reviewer also has the ability to request a new submission for the the scope and determination form which may have been attached with the original application.  Updated attachment pages for proper view, add, edit functions for the requester.
ready for review
