### ISSUE TITLE
Enhancement: TIA Submittal Attachment Types

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4559]
### A new field for TIA Submittals 'Attachment Type'
- Drop down for customer to select the type of attachment

**Views to Add Field To:**
- Customer Submissions New Submittal Form
- TIA Submission Details, Submission Attachments Table

**Types of Attachments:**

- Traffic Impact Analysis Document
- TIA Appendices 
- Trip Distribution Spreadsheet(s)
- Synchro Files
- Signal Timings

**Comment by ChrispinP** [comment]
Submission attachment types have been added to all relevant pages for requester and reviewer. I have now applied filters to tables to filter the many different attachment types.

ready for review
