### ISSUE TITLE
Feature: Confirm Submittal Button

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4560]
- **As a TIA customer, I'd like to click a button to formally submit my TIA Submittal.**
- **As a TIA customer, I want an email confirming my TIA Submittal**
- **As the TIA case reviewer, I want an email informing me of a new TIA Submittal**
- **As the system, I need to prevent the customer from updating TIA Submittals after they have clicked 'Confirm Submission'**

**Comment by ChrispinP** [comment]
There is now a Confirm trigger for the requester to finalize and send submission. The field is disabled if the Submission Status is either Completed or Approved, same with the option to Remove submission. The trigger updates Submission Status, Request Status, creates a case log entry, sends a confirmation email to requester, and sends email notification to the reviewer.

**Comment by ChrispinP** [comment]
Ready for review
