### ISSUE TITLE
Delete "csr_flex_notes" from AMD Data Tracker - December 2020

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#4563]
Received automated reminder to delete flex notes in Signs and Markings Operations PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings#data/object_172/records

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 11/01/20

Total Records: 23754
To Delete: 16535
New Total: 7219

**Comment by SurbhiBakshi** [comment]
@ChrispinP - do you want to tackle this one?

**Comment by ChrispinP** [comment]
new total of 7219 is matching.

complete
