### ISSUE TITLE
Bug: User Isiah L Unable to View Folder Attachments

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4564]
### User receives system error when attempting to open attachments on RSN 12594450

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/985f22f3-c72b-45f7-b267-79699e460f57)

**Comment by TracyLinder** [comment]
I was able to open and view both folder attachments; I've asked @Nadin-Nader if he knows how to help w/ this one.

**Comment by Nadin-Nader** [comment]
Spoke to Martin about this and he said they may have a corrupt reader and may have to have it reinstalled. Scott is currently looking into it.
On our end i have tested this in PROD and was able to view and download the files in the attachment tab.

Waiting on Troubleshooting results from Scott

**Comment by Nadin-Nader** [comment]
@TracyLinder Jaclyn responded and it seems like Isaiah is the one experiencing the issue. Have we heard from Scott?

**Comment by Nadin-Nader** [comment]
email from Jaclyn: 

> From: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov> 
> Sent: Tuesday, December 1, 2020 9:48 AM
> To: Linder, Tracy <Tracy.Linder@austintexas.gov>; Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov>
> Cc: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Subject: RE: folder 12594450 and others; error message generated when opening attachment
> 
> I have not experienced that issue. Both attachments opened for me. 
> 
> Jaclyn Lozano | Jaclyn.Lozano@AustinTexas.gov | 512 974 2412
> 
> From: Linder, Tracy 
> Sent: Monday, November 30, 2020 11:39 AM
> To: Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov>
> Cc: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>; Nader, Nadin <Nadin.Nader@austintexas.gov>
> Subject: RE: folder 12594450 and others; error message generated when opening attachment
> 
> Jaclyn, are you having the same issue as Isaiah? 
> 
> Tracy Linder (she/her)
> Product Manager, Data & Technology Services
> Austin Transportation Department
>

**Comment by TracyLinder** [comment]
@Nadin-Nader I have not heard from Scott

**Comment by Nadin-Nader** [comment]
Reached out to Isaiah to see if he was still getting the attachment error.

## **Status:**
Waiting on Isaiah's response

**Comment by Nadin-Nader** [comment]
Isaiah sent an email saying this has been resolved and he can now see the attachments. Closing card.

> From: Lewallen, Isaiah <Isaiah.Lewallen@austintexas.gov> 
> Sent: Thursday, December 17, 2020 9:57 AM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: folder 12594450 and others; error message generated when opening attachment
> 
> I can view the attachments in folder 12594450 now.
> 
> Thank you
> 
> Isaiah Lewallen
> Engineering Associate C
> Utility Coordinator
> Austin Transportation Department
> Right-of-way Management Division
> 
> isaiah.lewallen@austintexas.gov
> 512-974-1479
> 6310 Wilhelmina Delco Dr 
> Austin, Texas 78752
>
