### ISSUE TITLE
[Enhancement] RPP - Add Comments sections to Payment Information Pages

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4566]
Add a Comments table section to the Add Payment Information and Edit Payment Information pages so Cashier can make more informed decisions during payment processing. Customer information was also added previously in the case the Cashier needs to contact customer.

**Comment by ChrispinP** [comment]
Comments section added to both Add Payment Information and Edit Payment Information pages. Also fixed a bug where the Edit Payment link was directing to the Add Payment Information page instead of the Edit page. Updated the table link and the Edit Payment page accordingly. Updated page formatting.

complete

**Comment by moorerst** [comment]
confirmed complete
