### ISSUE TITLE
Handle null person_ethnicity_id

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4569]
Upon QAing the next month's worth of crash data in the VZV preview, the team noticed that null values in the prsn_ethnicity_id field were causing those fatalities to not display in the By Demographics component. 

Null prsn_ethnicity_id fields are being caused by two issues:
- when an officer does not provide a value for ethnicity while completing the CR3
- when a VZE user creates a temporary record without assigning a prsn_ethnicity_id 

For more information/background see [this Slack thread](https://austininnovation.slack.com/archives/CHZE6BC6L/p1606759077134200).

**Risks:** 
Making this change could skew the demographics numbers from previous months for crashes that had a null  prsn_ethnicity_id. We will need to check to see if the crash numbers change after this update and take appropriate, TBD actions to address.

**Requirements:**
- Update the table in Postgres to default to UNKNOWN/0 (right now it defaults to null) when no data is provided for prsn_ethnicity_id 
- Run a count of the changes to crash numbers this would cause
- Run script to update previous null values to UNKNOWN/0

**Expected result:**
Crash records that are created with null values for the prsn_ethnicity_id field should update to 0 prsn_ethnicity_id code and therefore display in the single "Other or unknown" category in VZV

**Comment by JaceDeloney** [comment]
This will likely need to be completed by end of December.

**Comment by tillyw** [comment]
Counts in staging
<img width="879" alt="Screen Shot 2020-12-23 at 11 44 25 AM" src="https://user-images.githubusercontent.com/35410637/103023876-60c33380-4514-11eb-95a7-7fc25f14fd49.png">
Couns in production
<img width="875" alt="Screen Shot 2020-12-23 at 11 42 58 AM" src="https://user-images.githubusercontent.com/35410637/103023885-63be2400-4514-11eb-9d02-db315da15607.png">

**Comment by tillyw** [comment]
Ran the following query to update defaults prsn_ethnicity_id to 0

```
alter table
atd_txdot_person
alter column
prsn_ethnicity_id
set default
0;
```

<img width="871" alt="Screen Shot 2020-12-23 at 11 53 15 AM" src="https://user-images.githubusercontent.com/35410637/103024436-76852880-4515-11eb-9b81-fc4aaf6a8585.png">

**Comment by tillyw** [comment]
Ran the following script to update previous null values on staging

```
update
atd_txdot_person
set
prsn_ethnicity_id = 0
where
prsn_ethnicity_id is null
```

with the following results

<img width="875" alt="Screen Shot 2020-12-23 at 11 57 52 AM" src="https://user-images.githubusercontent.com/35410637/103024834-383c3900-4516-11eb-88b8-735514a10280.png">

**Comment by sergiogcx** [comment]
We had to suspend the pairing session @tillyw and I. We were facing a severe performance degradation on the RDS instance due to multiple concurrent processes overwhelming the database.

I went ahead and finished the task in production:

![2020-12-23_13-37-32](https://user-images.githubusercontent.com/5282430/103031733-03cf7980-4524-11eb-810e-b9ef59110655.png)

**Comment by tillyw** [comment]
Thanks, @sergiogcx!
