### ISSUE TITLE
Assign unknown prsn_ethnicity_id to 3 crash records

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4571]
Update persons 792385 and primary persons 2941593 and 2999808 (which currently have a null prsn_ethnicity_id to 0 (UNKNOWN). The expected result is that the By Ethnicity chart would show 78 fatalities on Dec 1, 2020.

**Comment by mateoclarke** [comment]
| ID | 792385 | 2941593 | 2999808 |
| -- | -- | -- | -- |
| Table | person | primaryperson | primaryperson |
| Crash ID | 17651047 | 17809473 | 1012 |
| prsn_ethnicity_id | NULL | 1 | NULL |

**Comment by mateoclarke** [comment]
Ok, all `prsn_ethnicity_id` for 792385, 2947791, 2999808 have been updated from `NULL` to `0`.
