### ISSUE TITLE
[Enhancement] RPP - Ability to see Zone # in the Zone Display Name

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4575]
Append the Zone# field to the Display Name field for the zone object so it can be something like:

100 35 ST W | Orange | Zone 1

**Comment by ChrispinP** [comment]
Zone # has been appended to the Display Name field text formula and will now display and be searchable when associating with an application.

complete

**Comment by moorerst** [comment]
closing confirmed with RPP staff it displays in RPP Zone details as requested
 Yes! It made our lives so much easier
