### ISSUE TITLE
[RPP Back Office] Update Payment Options Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4578]
Since our cashier is now able to process payments using RPP website, we will need to use his desk phone number as a main number to call for payments.

Could you, please, make the following changes:

At https://atd.knack.com/parking#payment-options/ 

PAYMENT OPTIONS
Phone Payment
Pay over the phone with credit card, call the PERMITTING OFFICE during payment hours: 512-974-7828 (Hector Aguilera)

For any Residential Parking Program questions, call:
512-974-2891 (Steve Ingenito) or 512-974-1613 (Daniil Kontsevoy)

**Comment by ChrispinP** [comment]
Nate and I updated the Payment Options page with the Cashier number. We removed header tags for the numbers so spacing looked good. Let me know if anything else needs to be adjusted.

**Comment by ChrispinP** [comment]
Updated formatting so Payment number is first and cleaned up formatting a bit more.

**Comment by moorerst** [comment]
This is complete - Closing
