### ISSUE TITLE
Update Changes business logic

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4582]
![Screen Shot 2022-01-05 at 4.19.16 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/b272e171-4f0d-4423-b0c9-c8437a78f203)

- Add 2 new columns for killed and seriously injured field to the changes index page table
- Double check that VZE rejects any records that were previously manually QA/updated. So that the query that populates this table checks whether the status is manually QA-ed and blocks incoming changes so it doesn't show up on the table.
- Accept changes to lat/long changes by default (if not manually updated previously), and don't include those records in this index.

Move following fields to bottom table:
- rpt_lat
- rpt_long

Move to top table, flag if there is a change to:
- onsys_fl
- crash_sev_id
- Show changes for changes to injury severity

**Comment by patrickm02L** [comment]
![Screen Shot 2021-08-12 at 2.44.33 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/e7b3722f-13f6-4759-9b34-2474b7e645f3)

@patrickm02L Bring this up in the September Sprint Review meeting get feedback from Lewis and Xavier to see if we're using this, also get Sergio's input because he created this change index page.

**Comment by frankhereford** [comment]
When thinking about this issue's original text, the context is protecting changes which have been made by the VZ team in terms of QA/QC and not letting changes that come in from CRIS, particularly when related to a separate field, cause our system to overwrite the improved location with the original location from CRIS.

**Comment by xavierapostol** [comment]
Let's also add "private_dr_fl" to the top table.

**Comment by chiaberry** [comment]
@xavierapostol will do!

**Comment by xavierapostol** [comment]
So, I noticed changes are going back all the way to the 10 year limit. Is there a way to automatically accept the changes from TxDOT for crashes occurring BEFORE 11/1/2014?

**Comment by xavierapostol** [comment]
I was doing some QA/QC today and noticed several crashes that I had already assigned the "MOVEMENT" and the "DIRECTION" but now states "UNKNOWN" "MOVEMENT" and the original "DIRECTION". Is there a way to ensure that the ETL process does not automatically revert the values here?

**Comment by patrickm02L** [comment]
@xavierapostol created a new Issue #8639 to address your comment about MOVEMENT and DIRECTION.
