### ISSUE TITLE
Share new schools layer with GIS Community Bloomfire

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4587]

**Comment by jaime-mckeown** [comment]
Before sharing with the community, I did a search in our AGOL organizational content on Schools. By the looks of what I found, every department is doing their own thing when it comes to schools. The Schools layer I created is geared toward ATD, so I don't want to add an extra post telling people about something they are already maintaining in a different way for their own purposes. It's too bad the School Districts themselves don't share out good data for everyone to use.
