### ISSUE TITLE
Deliver school beacon collection training to AMD techs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4588]

**Comment by jaime-mckeown** [comment]
Billy has not provided me with who will be getting training and using the Web App. Will send email reminding him.

**Comment by jaime-mckeown** [comment]
They are interviewing for a new position that will be involved with this project, he asked to email him again on Friday.

**Comment by jaime-mckeown** [comment]
2 people have created AGOL accounts, still waiting for 3 more to create accounts. Sent a reminder email to group.

**Comment by jaime-mckeown** [comment]
Still one guy left, sent another email letting him know that he is now holding up moving forward on this project.

**Comment by jaime-mckeown** [comment]
- Finally got last guy setup.
- emailed Billy to get the training scheduled.

**Comment by jaime-mckeown** [comment]
- Creating a training version of the feature layers, Web Map, and Web App so they can practice editing data without worrying about the data getting messed up.

**Comment by jaime-mckeown** [comment]
Training has finally been scheduled for next Monday. I will need to spend some time creating an Agenda for how I want to go over this with them.

**Comment by jaime-mckeown** [comment]
- Purpose of the map and what they will be doing
- Discuss the layers in the map (reference and editable)
- Widgets, layers, bookmarks, editing
- How to get around in the map
- How to edit (attributes, moving a point, adding a point, Asset Status and why it's important, how to assign addresses to the SZB)
- Have everyone interact with the map, do some editing, add points, etc.

**Comment by jaime-mckeown** [comment]
- Field work for collection.

**Comment by jaime-mckeown** [comment]
- Billy will let me know when they are ready to start working on the project. At that point, I will send share the actual Web App and email the group with the link.

**Comment by jaime-mckeown** [comment]
Set a filter on the SZB layer to filter out any records with a beacon status of Remove. Will wait to update this on the actual data until I know they like this option.

**Comment by jaime-mckeown** [comment]
Created a new Issue to prep the Map/App for use by AMD.
