### ISSUE TITLE
Meet with Sean from ACC 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#459]
Meet with Austin Community College's GIS Department Chair to discuss the options to establish a contract with ACC GIS Inc.

**Comment by amenity** [comment]
@dianamartin - please include Peggy in this meeting. :)

**Comment by dianamartin** [comment]
@johnclary I don't see any time in your calendar this week. How about next Mon, 8/18 @ 1pm?

**Comment by johnclary** [comment]
@dianamartin sure!

**Comment by dianamartin** [comment]
- Sent email for proposed meeting time/date

**Comment by dianamartin** [comment]
Meeting scheduled for Mon, 8/19

**Comment by dianamartin** [comment]
## Diana's Notes
Street View data is old
Heads up digitizing

**Level 2**
GPS class - cancelled
Sign Inventory Project 

**ACC GIS Inc.** 
- Staff 2-3 trained up
- Trained team, lose an intern, then bring on someone else
- Plus: done at a fraction of the cost
- Familiar with the original project
- Pilot a small project
- Get better pricing 
- Get better estimate of how long it's going to take
	
Estimate: 12-18 months
Cost: dependent on pilot 
	
Workflow and Time

**Contractor**
Big Picture – more quickly
Control over deliverables
Interim milestones
Using a contractor

50-70k – 911 county control points
3-4 months to refine the workflow, generate a product, client comments
3-4 months to do the project 

**Option 1**: market, office at ATD
**Option 2**: hire the students, office with ATD
**Option 3**: office and run the interns, supervise students
- Northridge: 4 interns
- Next summer to Highland: Phase II
  - Office with 6 work stations
  - Staff up
	- 1 hour supervisor to 8-10 hours of interns
	- $15/hr, $110/hr
		- Release time: 3 hours to do this during the program
		
6 months to get the contract with CSEC

Sam Grier: blanket contract agreement with City of Austin

Scope Document --> Statement of Work 
Pilot an area (Medium complexity) - built in to contract
- Helps with pricing

Task: Pilot
Task: Contractual Value – not the real project amount

2-3 staff: 19 hours
Summer semester: 30 hours

**ACC GIS Inc**: visit when discrepancies
**DTS GIS**: visit locations 100%
**CycloMedia**: lidar process, imagery  

Push back from vendors
Supporting the academic

**Comment by dianamartin** [comment]
@johnclary Did you want to add your notes so we can close this?
