### ISSUE TITLE
Review existing RPP reports to determine scope of work for creating reports to match new data structure

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4590]

**Comment by ChrispinP** [comment]
Was able to use new data structure to build out new reporting in Test environment successfully. Below is the scope of changes necessary to implement accurate, flexible, and usable reporting while maintaining organization on the backend with ternary operations on date equations and cleaning up fields.

### **permit object**
**Fields being added:**
mc - Permit SubType
fx - Permit Cost
fx - Issued Quarter Number + ternary operation
fx - Issued Fiscal Quarter Number + ternary operation

**Fields being changed:**
mc - Renewal Year -> Renewal Period
txt - Serial Numbers > Serial Number
txt formula - Issue Month Date > txtIssuedMonthName
fx - Issue Month > Issued Month Number + ternary operation
fx - Issued Year > Issued Year Number + ternary operation

**Fields to remove:**
Transaction Month
Month Text
Final Cost
Final Cost Currency
Issued Month for Reports
Issued Month Number Text
Number of Permits or Passes
Cost per Permit or Pass
Cost of Permits or Passes

### **permit application**
**Fields being added:**
fx - Transaction Quarter Number + ternary operation
fx - Transaction Fiscal Quarter Number + ternary operation
fx - Transaction Year Number + ternary operation
mc - Payment Location
sum - Total Active Permit Cost
sum - Total Issued Permit Cost
sum - Issued Day Pass Cost
sum - Issued Decal Cost
sum - Issued Hangtag Cost
count - Count of Active Permits

**Fields being changed:**
fx - Transaction Month Number + ternary operation

**Fields to remove:**
none

**Comment by ChrispinP** [comment]
ready to review with stakeholders and push to production

**Comment by ChrispinP** [comment]
pushed to production. remaining work is to determine level of maintenance once February hits and removing the legacy fields from the permit object.

**Comment by ChrispinP** [comment]
closing as complete. no maintenance work needed and issue for removing legacy fields from permit object is in the backlog.
