### ISSUE TITLE
Transition Parking App Store Accounts to Austin

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#46]
To be compliant with Apple’s new restrictions on white labeled applications on App Store accounts, every white label will need to be on a City-owned account. Until the app is migrated to a City-owned account, the app will not be able to be updated by Passport.

**Comment by mateoclarke** [comment]
Chandra Perez from 311 told us that they get help related to App Store/Developer accounts from Shawn Willett, who is the Deputy Procurement Officer for the City of Austin.

I've looped her into the email thread with Passport folks and left her a VM today to see if she can help with the account transfer.

**Comment by mateoclarke** [comment]
Liz Roop from Passport sent this update:

>
Thanks Mateo and Shawn! Here are the instructions for the users from Passport to add to your app store account and google play account. Please let me know when these are complete and I'll send over next steps. 
>
Also please provide the following: 
>
-account holder emails (apple IDs) for App Store and Google Play
-team ID for App Store
-developer token and/or transaction ID for Google Play
>
Thanks,
Passport
>
Liz Roop ● Product Manager ●

**Comment by mateoclarke** [comment]
Shawn let me know that Bill Starks is assigned to complete the updates according to Passport's documentations. He's out today but will pick it up on Monday.

**Comment by mateoclarke** [comment]
Our responsibilities on this seem complete. We just needed to connect our Parking Division ppl & Passport reps with the right people in procurement. Will reopen if more action is required on the part of our team.
