### ISSUE TITLE
Project: Development Review Workflow Management (Stabilization) 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#460]
## Description
This project will deliver a solution for ATD Development Review case management. The solution will allow the Transportation Engineering project manager and various reviewers (AKA the Vision Team) to collaborate on the development cases ATD is responsible for reviewing. The users will be able to view case information, set review deadlines, assign reviews to the Vision Team members, and provide review comments directly to the case record. 

### Resources
- [Project Folder](https://drive.google.com/drive/u/1/folders/1efT5aT0AtYKR3Q_70nkQE9r7UTC4ewmc) 
- Request Submittal #430 
- [Development-Review Repo](https://github.com/cityofaustin/atd-knack-development-review/)
- AMANDA [query](https://github.com/cityofaustin/atd-amanda/blob/master/plsql-queries/TDSD_Reviews.sql) for active TDSD reviews

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://transportation.austintexas.io/about/) team. Project status is documented regularly in the comments below.

**Comment by TracyLinder** [comment]
**High Level Overview of The Workflow:**

1. This process starts & ends in AMANDA. (The AMANDA user is the PM.)	
2. During the Site Plan formal review process, the case is assigned to the PM in AMANDA, which must be completed by the review deadline (also in AMANDA).
3. ATD is not involved in the completeness check process. 
4. The PM determines who in the Vision Team is required to provide review comments, and assigns the review to them via email.
5. The project team requests the review comment due date to be 3 business days. 
6. The PM consolidates all review comments received by the Vision Team, and then adds the consolidated comment to the associated AMANDA Site Plan task for ATD. 
7. For each Site Plan this process can be repeated an indefinite number of times. 

**Desired Outcomes:**

- Easy coordination between the PM & Vision Team members
- Ability for the PM to easily assign reviews to any or all members of the Vision Team
- Ability for assigned users to add a review comment, an attachment, and the review outcome (approved, denied…)
- Ability to track the status and outcomes of reviews assigned to Vision Team users
- Ability for the PM to record the final review outcome and comment provided to the customer, for each review cycle
- Ability to track the overall status of an ATD development case
- Ability to attach PDFs to the case
- Ability to associate each case with the Site Plan case number (This number will not always be unique, and is the AMANDA Folder Reference ID.)
- Ability for a Vision Team user to easily view and sort the reviews assigned to them
- Ability for the PM to quickly see a workload overview, with emphasis on upcoming deadlines
- A feature that automatically closes an assigned review after the due date has passed. The auto closure rule should be ‘due date + 1 to give the user 1 extra day to complete the review
- A feature that notifies users by email when a review has been assigned to them
- Reporting Needs: Ability to search by reviewer or case #
-

**Comment by TracyLinder** [comment]
### Update

The project intake meeting for this request took place on 8/7/19
- Tracy Linder was assigned as Product Manager for this project on 8/12/19
- The DTS development team will be meeting on 8/20/19 to review this request, determine a level of effort for development, and estimate when this project is likely to go live.
- An update will be sent to the customer after the meeting on 8/20.

**Comment by dianamartin** [comment]
I created a new repository: https://github.com/cityofaustin/atd-knack-development-review/, going to add issue of the functional project requirements.

**Comment by johnclary** [comment]
Dropping the milestone from this since it is an `Index` issue.

**Comment by johnclary** [comment]
**Status Update**
The beta version of the app has been released for use by TDS staff, and more than seventy review comments have been collected from project reviewers.
