### ISSUE TITLE
RPP v2: Upgrades for Digital Permits

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4601]
A technology solution to enable completely digital operation of the Residential Parking Program—no more decals or hangtags.

### Background & Context

- Conversion to fully digital permits. No more decals or hangtags
- Ability for customers to login to manage permits and pay
- Possible expansion to ground transportation permits (e.g. taxi, limos, chauffeur)

**Comment by johnclary** [comment]
@moorerst let's discuss with RPP staff at next sprint review.

**Comment by moorerst** [comment]
Sprint Review meeting scheduled for 12/17

**Comment by johnclary** [comment]
@moorerst please schedule an intake meeting for this.

**Comment by moorerst** [comment]
Intake meeting scheduled for 3/26

**Comment by moorerst** [comment]
Intake meeting issue #5511 
Builder Huddle issue #5643

**Comment by moorerst** [comment]
Builder Huddle completed 4/5
Placing issue in Backlog until review of projects during Product Huddle

**Comment by moorerst** [comment]
Vendor solution will address RPP upgrades. Closing this issue.
