### ISSUE TITLE
Review PCI Questionnaire and Identify Questions for Knack

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4602]
@moorerst please attach SAQ document here and schedule time for us to review.

**Comment by moorerst** [comment]
@johnclary there are different types of SAQ's each with a different questionnaire 
We have to determine which one fits our environment. 
The attached document details each type of SAQ
https://www.pcisecuritystandards.org/documents/SAQ-InstrGuidelines-v3_2_1.pdf?agreement=true&time=1589915070699
SAQ A – Card-not-present Merchants, All Cardholder Data Functions Fully
Outsourced
SAQ A-EP – Partially Outsourced E-Commerce Merchants Using a Third-Party
Website for Payment Processing
SAQ B – Merchants with Only Imprint Machines or Only Standalone, Dial-Out
Terminals. No Electronic Cardholder Data Storage
SAQ B-IP – Merchants with Standalone, IP-Connected PTS Point-of-Interaction
(POI) terminals, No Electronic Cardholder Data Storage
SAQ C-VT – Merchants with Web-Based Virtual Terminals, No Electronic
Cardholder Data Storage 
SAQ C – Merchants with Payment Application Systems Connected to the
Internet, No Electronic Cardholder Data Storage
SAQ P2PE – Merchants using Only Hardware Payment Terminals in a
PCI SSC-listed P2PE Solution, No Electronic Cardholder Data
Storage
SAQ D for Merchants – All Other SAQ-Eligible Merchants 
SAQ D for Service Providers – SAQ-Eligible Service Providers

**Comment by johnclary** [comment]
Thanks @moorerst. It's the SAQ A-EP that we need.

**Comment by moorerst** [comment]
@johnclary attached is the SAQ A-EP questionnaire. It's really long
https://www.pcisecuritystandards.org/documents/SAQ_A-EP_v3.pdf

Is the next step sending this to Knack to complete?

**Comment by moorerst** [comment]
Per John i'm going to block off time to review the SAQ next week. 
i can go through it and flag what we need to answer vs what knack needs to answer
Will follow up the week of 1/4

**Comment by moorerst** [comment]
@johnclary please advise on the next steps for getting the SAQ to Knack for completion. Thanks

**Comment by moorerst** [comment]
@johnclary should I schedule a meeting to review the SAQ?

**Comment by johnclary** [comment]
We've decided to use Citybase for Knack payments. Closing.
