### ISSUE TITLE
Kickstand | Perform gqlAbtract.js updates and import into Moped Editor via Kickstand

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4616]
As a follow-up to #4016...

- [x] refactor gqlAbstract.js to be not specific to Vision Zero Editor
- [x] implement some unit testing
- [x] move files to Kickstand repo
- [x] import for usage into Moped Editor

**Comment by sergiogcx** [comment]
There is a PR:

https://github.com/cityofaustin/atd-kickstand/pull/7

**Comment by amenity** [comment]
@sergiogcx - would you add an estimate here, plz?

**Comment by sergiogcx** [comment]
@amenity Added the estimate, ready for review.

**Comment by amenity** [comment]
🙏 😎  @sergiogcx .
