### ISSUE TITLE
Phases and Milestones | Stakeholder work session to align on phases and milestones

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4617]
- [Recording](https://web.microsoftstream.com/video/6fa972df-5e6f-4a54-bf1f-9ff4bced09f5)
- [Deck](https://docs.google.com/presentation/d/1iSXFiIzbtmPSjGb7WCZNREdBjKoEXM0j7MkXJduWYXI/edit)

**Comment by zappfyllc** [comment]
@amenity we should discuss Milestones in this session too, touching on the fact that it will help us cut down on the list of phases but tracking deliverables.

Questions:

- Do we want to add milestones/deliverables ahead of time for a project (placeholders, dates TBD?)?
- Do we want a milestone description in case the milestone name needs more context?
- Are we ok with controlled autocomplete milestones or would we prefer free text? Should users be able to add milestones?

Confirmation on all of the above would be great

**Comment by amenity** [comment]
Great work, @zappfyllc!

Watching the recording, some thoughts:
- While I prefer _Active, Complete, Cancelled, On Hold_ as options for "Status" _conceptually_, it sounds like having it more like a "Phase Simple" that can be represented in colors on a map makes sense. 
- Agree that phases should be in a chronologically ordered drop-down; predictive typing may be distracting; 20 is very much pushing it, and 30 is out of the question
- Could "Status" be used to drill down phases? (@johnclary mentioned phase categories; Dylan agreed that the current Access list is too long) 
- +1 against free text or user-supplied milestones; a long list that is managed by the Moped operating board makes sense and; can have an “Other” milestone for outliers
- I am still not sure I see a benefit to milestones being assigned to a particular phase; it sounds like, for both ATSD and AMD, milestones occur on a specific date and these are tracked independently of phase

@mateoclarke @johnclary - did y'all have any notes or thoughts to add before we close out this issue?

**Comment by mateoclarke** [comment]
I'm going to go ahead and move this to closed. If there is follow-up I'm missing, we can reopen.
