### ISSUE TITLE
TDS App Bug: Duplicate Table Views on Review Details Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4622]
### BUG: There are two duplicate tables populating on the main view (Reviewer comments and Attachments)
Example Review [here](https://atd.knack.com/development-services#development-reviews/view-development-review-details/5e6122aa4f263d0015b23168/)
- Reviewer comments table:
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/80949b2d-bab8-401c-84a5-bd5e340083ae)
- Attachments Table:
- ![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/32634d76-5e60-4b40-a6a4-bc964c9f16f6)

**Comment by ChrispinP** [comment]
This should now be fixed. User role rules were incorrect for Project Managers and Admin showing both the editable and view tables.

complete
