### ISSUE TITLE
Add assignment type, description, and attachment fields to Shift Details page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4629]
Information that officers will want to see in the Shift Details
- Assignment Type (Signals/VZA)
- When the Scheduler adds notes or an image/file to 
(These might already be there and don't show b/c they aren't populated.)

Will need to coordinate with @mddilley to ensure this doesn't cause any conflicts with custom code.

**Comment by SurbhiBakshi** [comment]
Set up a Teams meeting with @mddilley on Tuesday, December 29th to see if adding these fields will affect the page.

**Comment by SurbhiBakshi** [comment]
made the changes, spoke to @mddilley - confirmed this will not affect any enhancements.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/19ff0556-cefa-4ffe-9cb7-f6f74402af4a)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/fff7f29e-7ff8-4254-9153-7309dda37186)
