### ISSUE TITLE
Update Index issues to meet our new Product and Project issue standards

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4643]
The time has come for us all to update our `Index` issues to meet our [new Product and Project issue](https://atd-dts.gitbook.io/wiki/product-ops/index-issue-specifications) standards.For all `Index` issues assigned to you, please make sure the issue has a title, description, labels, and assignee that matches what's defined in the docs. This applies to completed projects as well.This will generally involve:

-   replacing the `Index` label with `Project Index` or `Product Index`
-   Adding an "in a nutshell" description of the project/product
-   Reformatting the issue description section headers to match the new issue templates
-   Adding an image to your product issues which will be used as a thumbnail image on the website

If you'd like to track your progress on this task, I suggest [filtering zenhub](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/board?labels=index&labels:not=product%20index,project%20index&repos=140626918&showReleases=false&showDependencies=false) for all issues assigned to you that have an "Index" label, but do not have either a "Product Index" or "Project Index" label.Note that once you add a the new Project/Product Index label to your issue, it will appear on the [projects](https://atd-product.netlify.app/projects) or [products](https://atd-product.netlify.app/products) section of the new website within an hour.

Please have this work completed by 12/21.

**Comment by amenity** [comment]
Mine: 
- [x] Product: Moped — [Website](https://austinmobility.io/projects/5086) | [Github](https://github.com/cityofaustin/atd-data-tech/issues/307)
- [x] Project: Moped 1.0 — [Website](https://austinmobility.io/projects/5086) | [Github](https://github.com/cityofaustin/atd-data-tech/issues/5086)
- [ ] Product: VZA
- [ ] Project: VZA 1.0
- [ ] Project: VZA 2.0
- [ ] Product: Data Tracker
- [ ] Product: Signs and Markings
- [ ]

**Comment by TracyLinder** [comment]
I believe all of my issues have been updated w/ new specs.

**Comment by johnclary** [comment]
Just finished another batch of cleanup. The `Index` label is gone. I'm calling this done. 

> PMs, I’ve deleted the Index label from our repo. This required some cleanup:
> 
> I did a sweep of the remaining issues that had an Index label but no Product Index or Project Index , and replaced the generic Index with the product or project index as needed (and tweaked the issue content to at least somewhat match our new template).
> 
> There were a handful of Product Index or Project Index issues that also had an Index label. I removed the Index label from all of those.
> 
> We also had 15 closed projects using the Index label, so I went ahead and replaced that with a Project Index . Most of those issues still need to be reformatted to the new template. I think we need to set aside some time to groom those completed projects and assign folks to revise their descriptions so that they look nice on the website.
