### ISSUE TITLE
Support Duplicate Case IDs from different investigating agency

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#4646]
There was a recent fatality that has the Case ID = 203340060

Unfortunately, the Texas Sheriff's Department already submitted [a CR3](https://visionzero.austin.gov/editor/#/crashes/17987240) with that number. It is prevent me from entering a new one with this Case ID because "one already exists."

For the time being, Xavier submitted a temporary one with a leading zero [0203340060](https://visionzero.austin.gov/editor/#/crashes/1013)

The investigating agency is the group that creates the Case ID. 

**Requirements:**
- Replace the constraint for Case IDs with the regular index
- Update [the temporary record](https://visionzero.austin.gov/editor/#/crashes/1013) with the correct Case ID (203340060)

**Comment by sergiogcx** [comment]
@tillyw 

Here is a good article on different types of indexes, a regular index (default) is B-Tree:
https://www.postgresqltutorial.com/postgresql-indexes/postgresql-index-types/

Here is what a unique index is:
https://www.postgresqltutorial.com/postgresql-indexes/postgresql-unique-index/

**Comment by tillyw** [comment]
This has been completed. There are two records in production with the same case_id:

17987240	203340060	2020-11-29	9999
18031607	203340060	2020-11-29	22

The preexisting Texas Sheriff's Department record is 17987240 and the new one that was added by our staff is 18031607.

I ran the following query on both staging and production to create a new regular index for the case_id column in atd_txdot_crashes:

create index atd_txdot_crashes_crash_id_index
	on atd_txdot_crashes (crash_id);

These are the results:

<img width="887" alt="Screen Shot 2021-01-12 at 3 58 41 PM" src="https://user-images.githubusercontent.com/35410637/104388338-9bf6c800-54fe-11eb-9e5d-51ea9100c18c.png">

<img width="887" alt="Screen Shot 2021-01-12 at 3 59 05 PM" src="https://user-images.githubusercontent.com/35410637/104388363-a3b66c80-54fe-11eb-86f8-870127bf8629.png">

<img width="798" alt="Screen Shot 2021-01-12 at 5 49 45 PM" src="https://user-images.githubusercontent.com/35410637/104388410-b6c93c80-54fe-11eb-9306-3f3718bcd4ec.png">
