### ISSUE TITLE
Update fiscal year filters in Signs and Markings

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4662]

**Comment by SurbhiBakshi** [comment]
Contacted Christina to get an idea of where reporting might involve fiscal years. She has sent me the information. going to take a look and see what needs to be done.

**Comment by SurbhiBakshi** [comment]
Notes - 

- [ ]  [Specification by Month](https://atd.knack.com/signs-markings#work-orders-markings/markings/work-order-reports-markings/specifications-by-month/) - Filter Table to start 10/1/2020
- [ ] [Specifications Actions Table ](https://atd.knack.com/signs-markings#work-order-signs/reports-signs/) - Check and modify filter as needed.
- [ ] Number of Overhead Signs - Adjust filter as needed.

**Comment by SurbhiBakshi** [comment]
Going to check back with Christina if the changes work for her and the team. Also confirm there was no need of fiscal year reporting in the last two reporting widgets.

**Comment by SurbhiBakshi** [comment]
Communicated with Christina, she wants Fiscal Year Filters on the last two reporting widgets, so put those in.

1. ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/4b1ffbfc-62fd-4944-8104-27b8af718661)



2. ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/3f6c0e9f-0e19-43ec-a6f9-7822753814dd)
