### ISSUE TITLE
[BUG] RPP Required Documents Page is freezing

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4664]
**Describe the bug**
when the residents attempts to add a required documents the page freezes.
I tested and experienced the same issue after attempting to add a DL file
Resident cannot move forward with completing application

**URL**
RPP Required Documents Page

**Comment by ChrispinP** [comment]
Investigated issue and should now be resolved, most likely a Knack database issue with the Attachment field.

**Comment by moorerst** [comment]
no new reports of this issue - closing
