### ISSUE TITLE
[RPP Back Office] Modify Payment Options page 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4665]
- [x] Is it possible to add 12-1 PM lunch to the payment hours here: City of Austin Residential Parking Permits Portal (knack.com)

- [x] Also I just noticed that our Cashier doesn't see customer address on his tab but he needs it to verify that this is the right application. Plus some customers submit multiple applications for their properties.
Check for Hector Aguilera

**Comment by ChrispinP** [comment]
Added address field for the customer to Applicant Information on Application Details page and added address to Payment Information pages when adding or editing payment info. Address is already in the table.

Added lunch hours to the payment options page

complete

**Comment by moorerst** [comment]
confirmed this is complete
