### ISSUE TITLE
Project Definition | Implement progress/spinner animation in "Finish" button

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4668]

**Comment by amenity** [comment]
![Screen Shot 2020-12-09 at 4 35 39 PM](https://user-images.githubusercontent.com/1463708/101699505-dc1ae480-3a40-11eb-8d06-7cea882c3683.png)
@johnclary pointed out that this lil' spinner is good.

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/143
