### ISSUE TITLE
Update Dashboard with more Moped-relevant chart titles

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4670]
Fixup the chart titles so this is more closely resembles future state. 

<img width="1178" alt="Screen Shot 2020-12-09 at 4 01 25 PM" src="https://user-images.githubusercontent.com/14793120/101694777-3a43c980-3a39-11eb-98d1-93bde044eac3.png">

**Comment by johnclary** [comment]
@mateoclarke i'll take this one. tweaking the code is going to be as easy as marking up a doc for the changes.

The charts live [here](https://github.com/cityofaustin/atd-moped/tree/main/moped-editor/src/views/reports/DashboardView)
