### ISSUE TITLE
Monthly Update to ATD Work Groups

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#468]
## Description: 
Per John, work groups should receive a monthly update regarding their backlog and work in progress. 

**Objectives:**

- Which work groups get updates?
- What info to include in the update?
- Can any of this be automated?

**Comment by amenity** [comment]
I think that reviving the DTS Monthly Newsletter and performing [quarterly stakeholder meetings](https://github.com/cityofaustin/atd-data-tech/issues/688) would be sufficient. Iceboxing for now.❄️
