### ISSUE TITLE
Enable manual entry of shift start and end times to work on the back end

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4687]

**Comment by SurbhiBakshi** [comment]
1. Matthew G bypassed the Start Assignment and End Assignment trigger buttons and manually entered Start and End Times in the form fields. 
2. He used the Submit button but did not see the Assignment recorded in the Past Assignments table. He emailed me to let me know about this.
3. I looked at the records in the Officer Assignments objects and all the timestamps had been recorded, however the Status field is triggered by the Start and End Assignment trigger buttons.
3. I looked up the Past Assignments and Invoicing tables and changed the filters for those tables from Status is Complete to a combined filter as shown in the screenshot below - 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/a69da095-3c01-423f-804b-461548e12999)
4. Replied to Matthew and asked him if the fix works and he can see the assignments he worked. 
5. Also check with @mddilley to see if any of the changes impacted the enhancements he has put in place for the Officer pages.
