### ISSUE TITLE
Determine Standard Project Discovery Meeting Questions For Devs

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#469]
## Description
Gather standard discovery meeting questions from John & Diana (questions they want asked at all intake meetings).

**Comment by TracyLinder** [comment]
@johnclary @dianamartin Here is the place to jot down your ideas about standard questions you think would be useful during a project intake meeting.

**Comment by johnclary** [comment]
- how many users?
- will there be public viewing of info? editing?
- does the solution need to pull in data from an external system? E.g. GIS, eCapri, AMANDA, Data Tracker?
- does the solution to ingest push data to an external system? E.g. GIS, eCapri, AIMs, AMANDA, Data Tracker?
- does your workflow require an approval process? what more can you tell us about that?
- does your solution need to collect or visualize geospatial data?
- what kind of hardware will your primary users rely on? mobile device, desktop pc. etc.
- how many records will your solution need to handle?
- do your records need to tie to authoritative address or ATD asset information?

**Comment by dianamartin** [comment]
- Do you require a importing legacy data?
- Do you need user roles to do different things in a system? 
  - _(ex. user for viewing only, user for editing data, user to do both editing/viewing)_
- Do you have a need for users to be notified automatically from a system 
  - _(ex. Status change, form submitted, approval request?)_
- Does your business need require strict records retention?
- Does the data you're tracking have:
   - **Personal Identifiable Information (PII)**?
   - **Health Information (HIPAA)**?
   - **Criminal Justice Information (CJIS)**?

**Comment by johnclary** [comment]
@mateoclarke we're compiling a list of questions that a PM will ask requesters when we're doing intake on a new project. meant to give us enough info so that we can roughly estimate level of effort based on a conversation with apps/dev teams. anything you want to add?

**Comment by mateoclarke** [comment]
• How many database tables, overall complexity of Entity Relationship Diagram?
• How much of the scope of work can use off-the-self systems vs. open-source custom development?
• How many roles?

**Comment by TracyLinder** [comment]
Re: Formatting the legacy data question:

1. What is your current solution?
2. What software is used for the current solution? 
    * If none, then no legacy question
3. Will the new (project) solution need to include or import any existing data from the named software? 
    * If not, no more related questions. 
4. Tell us more about the data that needs to be included. What is it used for? What is it's record retention? How much of it is there (thinking of the data like a record, how many records are we talking about?)

**Comment by TracyLinder** [comment]
@mateoclarke I'm assuming you're talking about user roles, but please correct me if I'm wrong.

**Comment by TracyLinder** [comment]
Re: Roles

Let's talk about who will use the solution, and for what purposes. 

1. Who needs the ability to view the solution/app?
2. Who needs the ability to edit the solution/app?
3. Will different levels of user (editing) permissions be needed? If so explain.
4. Who will perform user account management?

**Comment by TracyLinder** [comment]
@amenity I'm thinking we may need a logic based form for this. (Not KNACK powered though.)
