### ISSUE TITLE
Feature: Send the reviewer an email when a new case is opened

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4690]
### When a case is created/submitted, send the assigned case reviewer a notification email.

**Comment by ChrispinP** [comment]
Added an email notification for the reviewer when a TIA request is submitted. Should send to correct reviewer based on area selected for the request.

ready for review

**Comment by TracyLinder** [comment]
We need to test this w/ a reviewer who gets the email.

**Comment by TracyLinder** [comment]
Looks good; closing
