### ISSUE TITLE
Allow multiple select on Request Submission button

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4693]
### Allow multiple select on Request Submission button

The case manager needs to be able to select multiple submission types when requesting a submittal from the applicant. (This generates a system email.)

**Comment by ChrispinP** [comment]
Actually, I remember now why i made this a new field separate from attachment type to begin with. With this foresight i was able to update the field to multiple selection and added some language on the form. I also added TIA Packet as an option. Email template should still work as is but im not sure if it might look a little wonky with multiple documents selected or if the email will automatically generate commas or spacing. Something to test and verify.

Ready for review

**Comment by TracyLinder** [comment]
Tested w/ stakeholder. Looks good.
