### ISSUE TITLE
Executive team demo mini-sprint

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4695]

**Comment by amenity** [comment]
Notes from today's meeting w/ Rob, Karla, Chris M., Mateo, Amenity, John:

- "Capital" funding 😅 #4745 
- In addition to current status, track approximate dates of future maintenance, e.g. "in three years you need to be thinking about re-painting these bike lanes" - @johnclary mentioned SMB is doing already good job of accounting for long term maintenance
- Add distinct, required field for Project Owner 
- Project search and filter and by 
   - Workgroup
   - Project Owner (also show as column in Project Listing?)
- Bring Brian L. (Airport) may be available to advise on Moped; is currently extending eCapris to include non-capital projects

Moped "About" page
- Moped mission and/or problem statement - "should emphasize that Moped is an add-on to eCapris"
- Release notes from github
- Companion documentation and training
- Support request
