### ISSUE TITLE
Register first round of VZA 2.0 officers

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4696]
### Registration
Per, #4548, we'll do a bulk import of officers who attend the training into the app. A spreadsheet w/:
- Email
- Phone number
- Badge # (for connecting to Brazos data)
- Call # (? - may not need this, check w stakeholders)

**Comment by amenity** [comment]
@SurbhiBakshi - do we want to just have them add their info to a Google Sheet during the training?

**Comment by SurbhiBakshi** [comment]
@amenity - that should work for me, is Lewis going to invite the officers or Pat? At what point does Lewis look at who wants to do VZA assignments?
