### ISSUE TITLE
Support AMD transition to Interim Mobility Project Database

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4698]
Initially we were planning to address AMD's basic [project tracking needs](https://github.com/cityofaustin/atd-data-tech/issues/3974) via [a Moped Alpha integration with Data Tracker](https://github.com/cityofaustin/atd-data-tech/issues/#3669).

Given the intense and immediate coordination now required for Prop B activities, the Signals group is going to use IMPDB to track their work until Moped is launched. 

We'll follow along to 
- Stay up to speed on any changes made to the IMPDB data model to accommodate AMD's needs; keeping an eye out for anything that might impede the ultimate Access ---> Moped migration
- Advise re: Knack v. Access v. Excel data division
- Ensure Renée, Scott, et al have viable workflows, potentially making changes to Data Tracker 
- Capture requirements for future Moped issues, such as #3663.

**Comment by amenity** [comment]
Notes: 
- Signals is one of the most complicated divisions
  - Own some projects and self-organize on a that scale
  - Participate on others' projects, eg. signals for CPO on North Lamar
- AMD already struggles to keep existing Knack data up to date
- Some Data Tracker dashboards might be abandoned in favor of moving to Moped* Need to talk with John
  - New Signal Construction, Signal Modifications - these can move into Moped 
- Will give exposure to all the other groups that are using this, will facilitate communication
Questions/ideas
- Where is alignment with eCapris?
- Is quarter cent a project group?
- How are other groups accounting for their unfunded needs? Lots of different ways to handle unfunded needs
- We may want to tag a project as corridor program and something a bit more meaningful?

Plan:
- Moving data into appropriate data structure and adapt it with Nathan to accommodate AMD’s projects
- This data structure is what’s transitioned into the next system

**Comment by amenity** [comment]
@johnclary - for your review

**Comment by amenity** [comment]
_12/15 work session: Nathan, Dylan, Renée, Scott, Jen, John, Amenity_

- AMD uses quarters to document their project completion; prefers less-precise unit to set reasonable expectations; e.g. we are going to start that the beginning of next year, but we don't know whether it will be January or February — so "FY2021 Q1" is preferable
  - Jen: This might not be the place to set expectations
  - Going to keep this in Access for now; NW indicated that this could be phased out 

- Can we commit to not go back to spreadsheets? 
  - Renée - Can we export as a spreadsheet to do one-off calculations 
  - Track that we have enough controllers; sometimes we have projects 
  - "When are you going to build Anderson Mill at Pecan Creek?"... "When we get two 40' arms
- [Fearure] Cost estimates
  - AMD's current version: 
    - Manually maintained Excel file, axis:
      - AIMS (inventory) quantities
      - Projects (not *all* projects; the most )
    - "When are you going to build Anderson Mill at Pecan Creek?"... "When we get two 40' arms"
  - (ATSD handles this in Access; have agreed not to 
- Standalone Signal Projects:
- ![Screen Shot 2020-12-15 at 9.24.42 AM](/Users/amenity/Downloads/untitled folder/Standalone-signals.png)

Naming conventions: 

- AMD uses the CSJ ID (TXDOT)
- ATSD includes the year

**Comment by zappfyllc** [comment]
[https://docs.google.com/document/d/1PirEv01IfGnOkxydlT5HEMR0wisXsNXhAWIlE89sE44/edit?usp=sharing](Notes from AMD Data Session Part 3 on 1/20/21)
