### ISSUE TITLE
Product: Right of Way Portal

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4699]
Right-of-Way Management's Knack application for centralized operations management. 

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/5cc69fcf-b713-431c-99d8-6ab6906c3cfa)

### Login

[https://atd.knack.com/row-portal#home](https://atd.knack.com/row-portal#home)
[https://atd.knack.com/amd#tcp-tracking/](https://atd.knack.com/amd#tcp-tracking/)

### Support

This product is managed by ATD's Data & Technology Services. Please submit a request to us for support using [this form](https://atd.knack.com/dts#new-service-request/).

---
This Github issue represents a product of Austin Transportation's [Data & Technology Services](https://product.austinmobility.io/) team.

**Comment by TracyLinder** [comment]
**Dec 2021 Stakeholder Review**
_See issue #7923_

**Priorities**

1. TCP Reviewer Dashboard [Enhancement] (TCP Tracker) - TCP Reviewer Dashboard #7400
2. Convert "Conflict/Shared Work Zone Analysis" intake form Convert "Conflict/Shared Work Zone Analysis" intake form in Smartsheet to Knack in ROW Portal #7397
3. Reporting Metrics: [ROW] TCP Reporting Metrics: Monthly Intake #7062 TCP Tracker Reporting: Bar Chart for Deficiency Percentage #3604 KNACK Report: CIP & Department Types #5672 Enhancement: TCP Reporting: TCP review time, i.e. the highest # days that it has taken for a TCP review #6042

**Comment by KyleErich** [comment]
@TracyLinder Can this old ticket be closed now?

**Comment by KyleErich** [comment]
Unclear why this issue is still open. Closing.
