### ISSUE TITLE
Create standard discovery meeting doc template

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#470]
### The purpose of the discovery meeting is to gather enough info for DTS to
1. Be confident is suggesting an idea solution
2. Provide a rough level of effort (estimate)

**Not In Scope**
* Gathering user stories or requirements
* Project Brief

[WIP here](https://drive.google.com/open?id=1AcjxHv6XCEutSAIzNebnxNR9EL8CORiHrVfNlQuChII)

**Comment by TracyLinder** [comment]
### Notes From Conversations About This

* Stay in the scope (see issue description)
* We should leave having a working understanding of the business unit workflow related to the project request
* Review the project intake form
* Ask the dev's questions

**Comment by amenity** [comment]
Have been using that WIP for a while now and it's great. :)
