### ISSUE TITLE
Preserve user input when navigating between steps in the New Project form

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4700]
Preserve data when the user navigates between steps. 

Currently, data is lost on these fields: 
- [ ] Define Project — Fiscal Year, Current Status, Current Phase, Priority
- [ ] Assign Team — Notes - @mddilley will get this w/ #4544 
- [x] Map Project — (polygon selection in map)

**Comment by mddilley** [comment]
Updated the polygon selections to be preserved when navigating between New Project form steps in https://github.com/cityofaustin/atd-moped/pull/152

**Comment by amenity** [comment]
This was taken care of at some point during the #4695. :)
