### ISSUE TITLE
Update DAPCZ Boundary and maps

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#4705]
Mary asked about which DAPCZ Boundaries were correct. She sent me this PDF:
https://austintexas.gov/sites/default/files/files/Transportation/Parking/DAPCZ_Map.pdf

And also referenced the ROW Version:
https://www.austintexas.gov/page/downtown-austin-project-coordination-zone-dapcz

She sent me the municode for the dapcz:
https://library.municode.com/tx/austin/codes/code_of_ordinances?nodeId=TIT14USSTPUPR_CH14-11USRI-W

**Comment by jaime-mckeown** [comment]
I checked the municode against the layer in GISDM, both PDFs were incorrect for the area around town lake. There were a couple discrepancies related to the layer that did not match up to the municode. Need to check with Alan.

Need to figure out who created the PDFs for Parking and ROW so they can be fixed.

**Comment by jaime-mckeown** [comment]
@alan-deanda Mary asked me about the dapcz boundaries this morning as she was seeing 2 different versions. It turns out that both PDFs referenced above are out of date.

I wanted to ask you about the boundaries though. She sent me the municode description of the boundary and the GIS Boundary does not follow the description exactly. Was there a reason why the western boundary follows the Mopac frontage rd instead of Mopac itself? Was there a reason why the boundary along the lake is following the center of the lake instead of the north shoreline? I just want to make sure the boundaries are correct. Thanks!

**Comment by alan-deanda** [comment]
@jaime-mckeown I don't know who created those maps, but we should probably replace them.  

I'm not sure why the boundary is that way - on Mopac I could imagine the difference could come from the imagery it was digitized to, it doesn't exactly follow the street geometry (is it supposed to?) 

As far as the river, boundaries on rivers are typically aligned to their centerline. That being said, I wasn't able to find the stated boundaries in the MUNI code, so I don't know if the boundary should be north shore.

**Comment by jaime-mckeown** [comment]
@alan-deanda there is a link to the municode in the first comment above. I was planning on figuring out where those PDFs came from, was waiting to see what you said about the boundaries.

**Comment by jaime-mckeown** [comment]
@alan-deanda 
![image](https://user-images.githubusercontent.com/48842809/102265186-626d7580-3edc-11eb-8255-40de9d1b31b0.png)

**Comment by johnclary** [comment]
@alan-deanda please also update the PDF maps or make a web app.

**Comment by alan-deanda** [comment]
Boundaries have been updated to follow the northern shore of Lady Bird Lake and to not include MOPAC. I notified Mary V, who thinks a web app would be a more suitable option for displaying the boundaries to the public. She has also looped in other stakeholders.

**Comment by alan-deanda** [comment]
Updated geodatapusher to push new edits to GISDM.

**Comment by jaime-mckeown** [comment]
Implemented by PIO.
