### ISSUE TITLE
Bug: Resource Links on Street Banners Resource Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4710]
### Update the Resources Page
- Rename & update hyperlink on the AMANDA button
    - https://atd.knack.com/dts#new-service-request/
- Remove all guide buttons
- See screenshot below
-----

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/8764558d-0c03-47eb-a817-eedb236ff20b)

**Comment by TracyLinder** [comment]
@dianamartin @ChrispinP @SurbhiBakshi - Just an FYI that this bug issue has been created but not assigned to anyone. I'll look for assigning it during Sprint 41 planning.

**Comment by TracyLinder** [comment]
@TracyLinder add the correct link for the Amanda resource. 
@ChrispinP will delete the guide links.

**Comment by TracyLinder** [comment]
@ChrispinP i updated the issue description. This is ready to work on.

**Comment by ChrispinP** [comment]
Created a new JS Function to open these buttons into a new tab, corrected the AMANDA support link and removed the Guide buttons. Tested that button links open in new tabs.

complete

**Comment by TracyLinder** [comment]
Looks great! Thanks Chrispin.

![image](https://user-images.githubusercontent.com/49930868/102392212-652f9f80-3f9c-11eb-8347-6cb1020a1a4c.png)
