### ISSUE TITLE
Research Possible Confidential Data

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4714]
See notes [here.](https://github.com/cityofaustin/atd-data-tech/issues/4711#issuecomment-745566471)
- [ ] Is any of this data confidential? Health permit #, sales tax #, insurance co name
- [x] Email PIO: Can we publish numbers & email addresses? (See Valet emergency contact concerns in notes)
    - We can publish phone numbers, we **cannot** publish email addresses

**Comment by TracyLinder** [comment]
**Email to ATD PIO:**

Hi Joana,

We are working on publicly publishing ROW permit data, and a question about PII came up that I’m hoping you can answer. Can we publish phone numbers and/or email addresses?

**Comment by johnclary** [comment]
@TracyLinder i'm cool with just leaving out the phone numbers and email addresses for now

**Comment by TracyLinder** [comment]
@johnclary the phone & email in question are populating from a specific folder info on the valet permit types. If it's PII we can do an info exclusion.

**Comment by TracyLinder** [comment]
Update re: Email w/ Joana (PIO):

- Joana asked for a sample of the data
- I sent this: [https://app.zenhub.com/files/140626918/75126960-c475-4164-946a-cc8175f75860/download](https://app.zenhub.com/files/140626918/75126960-c475-4164-946a-cc8175f75860/download)

**Comment by TracyLinder** [comment]
### Email & Phone Nu. Determination From PIO:
- Phone number OK to publish
- Do not publish emails

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/2674c3cc-4eed-4743-a06f-6bd711fae959)

**Comment by TracyLinder** [comment]
### Update & Closing

This is an outdated project request that no longer represents active work or business needs. DTS continues to publish open data sets as they are identified.
