### ISSUE TITLE
Project Extent | Restrict geocoder to our region

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4715]
Chatted w/ @mddilley about an enhancement to [restrict the geocoder results to the Moped "region"](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-limit-region/)... Only ... I don't know how to define it. 😅

I guess "Texas" would be safe, @johnclary ?

![Screen Shot 2020-12-15 at 3 40 47 PM](https://user-images.githubusercontent.com/1463708/102276061-eaa74700-3eeb-11eb-9a8f-de4c1542118d.png)

**Comment by mateoclarke** [comment]
had the same thought. Wonder you could restrict the results by a radius from Austin

**Comment by amenity** [comment]
That would be cool. The state of Texas would be a safe start — at least keep Malaysia out of the top suggestions. 

Is this "Austin" clump of counties that appears on the [TXDOT project tracker](https://apps3.txdot.gov/apps-cq/project_tracker/) a formalized region, @jaime-mckeown @alan-deanda?
<img width="736" alt="Screen Shot 2020-12-16 at 1 34 24 AM" src="https://user-images.githubusercontent.com/1463708/102318626-4222d280-3f3f-11eb-8515-7f507a36e515.png">

**Comment by jaime-mckeown** [comment]
@amenity that area most likely encompasses the Austin District of TXDOT which includes those counties.

**Comment by alan-deanda** [comment]
@amenity  this is the boundary for the [Capital Area Council of Governments](https://www.capcog.org/)

**Comment by amenity** [comment]
Thanks, @alan-deanda @jaime-mckeown. 

Nathan's 2 ¢:

**Comment by johnclary** [comment]
sounds good to me! assuming @mddilley is able to configure the geocoder as such...

**Comment by johnclary** [comment]
Assuming that if we can configure the geocoder to limit results to a geometry, it will probably be be done by plugging in a bounding box. This [url](https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/BOUNDARIES_jurisdiction_1231_1951/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=&returnGeometry=true&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=true&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=) is a query that returns a geojson bounding box of the ETL and full-purpose jurisdiction.

so @mddilley hopefully you can plug this into the geocoder!

```
{
  "type" : "FeatureCollection", 
  "crs" : 
  {
    "type" : "name", 
    "properties" : 
    {
      "name" : "EPSG:4326"
    }
  }, 
  "bbox" : [-97.940377028014, 30.1337172258415, -97.578205982277, 30.4648268798927], 
  "features" : []
}
```

**Comment by johnclary** [comment]
If this doesn't work out, we do have a RESTful COA-only geocoder that is managed by CTM. we'd have to write the code to interact with it ourselves, so here's hoping we don't need to do that 🤞

**Comment by mddilley** [comment]
@johnclary That bounding box worked perfectly with this library - thanks for providing! 🙏

**Comment by johnclary** [comment]
oh, nice! @mddilley just realizing now that it'd probably be wise to shave off some decimal places from that bbox.  Anything beyond 6 decimal places is basically a meaningless artifact of the translation from our local coordinate system to web mercator. It probably doesn't impact performance, but it maybe could?

**Comment by mddilley** [comment]
@johnclary Thanks for the heads up about that - I'll make that small change in an upcoming PR. 👍
