### ISSUE TITLE
Define Project - New Project form | Fix fields that aren't included in the insert mutation

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#4720]
- make sure projects and status phase submit in the create mutation
- inventory what others aren't working on the first step of this page: https://moped.austinmobility.io/moped/projects/new

This might already be addressed in https://github.com/cityofaustin/atd-moped/pull/134

**Comment by amenity** [comment]
@sergiogcx - I think this may be irrelevant now or incorporated by work you're already doing?

**Comment by amenity** [comment]
@chiaberry is removing the phase drop down
