### ISSUE TITLE
Assign Team - New Project Form | Fix mutation for moped_proj_personnel

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#4721]
Staff table records aren't actually being associated to the project
- Submit a mutation with staff info to project personnel 

~This might already be addressed in cityofaustin/atd-moped#134~

**Comment by amenity** [comment]
Another, @sergiogcx, that may be covered by #5747 work?

**Comment by amenity** [comment]
@sergiogcx @mateoclarke — I am not sure why I thought this would relate to #5747... Does this still need to be done?
