### ISSUE TITLE
Discuss Moped data model documentation and approach

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#4723]
The devs have been getting their hands dirty with the user workflows, devops infrastructure, user mgmt features, and now some basic UI and workflows. We're ready to grow our understanding of how all the database pieces works starting with a small scope and building out.

- [x] Get references to ERD/data model docs and add decide where to reference from project README or Gitbook dev documentation
- [x] Discuss implementation of data dictionary for reference like we had in the CRIS excel sheets #4744
- [x] Schedule retro in January to take account of documentation approach @amenity

**Comment by amenity** [comment]
Here is the Entity Relationship Diagram:
- [Draw.io](https://drive.google.com/file/d/1aettIN9dtD02xg_WFNkvTPaimk81uhRE/view?usp=sharing)
- [PDF](https://drive.google.com/file/d/1R438B4PcZZyidYkh9_42FuL2ThGqW1Vl/view?usp=sharing)

[Here is a doc](https://docs.google.com/spreadsheets/d/1pDVF6z5tHdtHFqhFTnvROf9FkSgabZbpQxgn53hKz-4/edit#gid=0) @zappfyllc used during his research to track entities needed by each workgroup. 

@zappfyllc - anything else?

**Comment by amenity** [comment]
Discussed during Sprint Planning: We're going to incorporate data model discussions and documentation into feature implementation. So for a given feature, document the tables, relationships, constraints, etc. as we refine requirements and build out the feature. 

Additionally, will have a "Documentation" issue in every feature epic and begin maintaining a data dictionary, #4744.

**Comment by amenity** [comment]
We have a meeting on 1/12 to check in on this.

**Comment by amenity** [comment]
We put together a good [outline of our various documentation platforms](https://docs.google.com/document/d/1dBVkmzCXBQktEltwv5cQOiKvL_BroTNpVzMkbqalk8c/edit#).

The overall consensus is that we've been proactive with documentation, are satisfied with the various tools we're using, and want to keep incorporating it into our work as we go. 

@tillyw @mateoclarke @sergiogcx @mddilley — reviewing my notes above, I see that we'd initially decided to add a "Documenatation" issue to every epic. I don't thinkkkk we've been doing that, but am happy to start reminding/enforcing that if it's helpful.
