### ISSUE TITLE
Update options in "Current Phase" dropdown

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4724]
@sergiogcx @mateoclarke — sorry, I missed what's going on with Phases. Is this being directly written to the record in the same way status is?  

Either way, it would be very wonderful to get these options updated so they're not identical to those for Status. 
<img width="1057" alt="Screen Shot 2020-12-16 at 2 16 08 AM" src="https://user-images.githubusercontent.com/1463708/102322532-d5123b80-3f44-11eb-99ca-6622ba4d2109.png">

### Mock data
phase_name | required_phase
-- | --
Complete | FALSE
Construction | FALSE
Design | FALSE
Preliminary Design | FALSE
Scoping | FALSE
Planned | FALSE
Potential | FALSE
Hold | FALSE
Canceled | FALSE

**Comment by amenity** [comment]
Hoping this fits well with the other seed data work for today, but if it's more complicated than that we don't need to cram it in before the demo. Your call, @sergiogcx

**Comment by sergiogcx** [comment]
I will try to have it fixed today, the issue is the database structure constraints won't let me make updates, but there are work-arounds. I will not do anything on staging yet, to keep it clean. Will provide feedback @amenity

**Comment by sergiogcx** [comment]
This is done, thanks to removing the projects data I was able to update the values.
