### ISSUE TITLE
Edit employee information

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#4727]
Linda E would like to edit employee related information (for example - full time/ part time, temp/regular) in the Knack application. These fields are not part of the Edit Employee information form right now. 
Have scheduled some time to talk to @moorerst about this request. Need to figure out is there are any restrictions on users accessing some of those fields.

**Comment by moorerst** [comment]
@SurbhiBakshi where are no issues with adding the fields Work Class, Work Class Description and Work Status to the Edit Form. I don't know all of the unique values for those fields.

**Comment by SurbhiBakshi** [comment]
@moorerst - I added the work class description from Linda's email and added the fields to the Edit Employee form.

**Comment by moorerst** [comment]
@SurbhiBakshi looks great. Can the Class Description field default to blank instead of Executive/1?

**Comment by SurbhiBakshi** [comment]
@moorerst - The default is blank and I set the drop down list for Class Description to sort A to Z in descending order, so Executive/1 is the last option. Let me know if that works.

**Comment by moorerst** [comment]
@SurbhiBakshi looks good. Thanks

**Comment by moorerst** [comment]
i emailed Linda to let her know the fields are now available on the Edit form.
