### ISSUE TITLE
[RPP Back Office] Customer Phone & Email Requirement - Data Integrity

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4733]
When manually entering paper applications where customers don't put neither an email address or phone number can the requirement for Phone # and Email address be removed?
Example: 2020-2009 user did not include a phone # or email address on paper application. RPP staff was forced to enter their own phone and email because the fields are required.

![image](https://user-images.githubusercontent.com/56606465/102390480-12ed7f00-3f9a-11eb-8b0f-682489c30d24.png)

**Comment by ChrispinP** [comment]
This brings up an important question, should RPP staff be entering incomplete paper applications into the system to begin with? If this customer information is not gathered during the application process, how would we get ahold of the customer to take payment or for any other reasons? Secondly, this again brings up a data integrity issue, staff should not be entering information the way they have been in the past. Data in the system should be accurate and therefore dummy data should not ever be an option.

**Comment by ChrispinP** [comment]
Built in Dec 16 Test environment. Created two new boolean fields 'No Phone' and 'No Email' that trigger display rules to hide phone or email when checked. Placed on Customer and Application new and edit forms for RPP Staff. Hide rules working as expected.
![image](https://user-images.githubusercontent.com/67915167/102926000-e3d38380-4459-11eb-99e5-3d9e8923ce07.png)

Ready for prod

**Comment by moorerst** [comment]
@ChrispinP can you move this to production and I'll inform the RPP staff Thks

**Comment by ChrispinP** [comment]
No Phone and No Email boolean fields added to production forms.

Ready for Review

**Comment by moorerst** [comment]
customer confirmed this issue is working correctly. Closing this issue.
