### ISSUE TITLE
Perform scoping with SMB and Shared Mobility

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4737]
**Attendees:** 
Smart Mobility: Luke U., Hannah B., Jordan P.
SMB: Lauren
DTS: Diana, Stephanie

**Comment by ChrispinP** [comment]
@TracyLinder reminder to reschedule this meeting or we can discuss during SMB Progress meeting on 03/09/21. Sync with Amenity?

**Comment by TracyLinder** [comment]
@TracyLinder reschedule this.

**Comment by moorerst** [comment]
Kick off meeting scheduled for 9/15

**Comment by moorerst** [comment]
@dianamartin please review slides for meeting and provide feedback. Thanks
https://docs.google.com/presentation/d/1BccURC5UDt0bZObmNks9lmCfaqiA2Ak-qXa-DIRorJQ/edit#slide=id.p

**Comment by dianamartin** [comment]
@moorerst I've reviewed and left some comments for you

**Comment by dianamartin** [comment]
# Diana's Notes

## Review Request
>We want to use one application to perform all banner permitting related tasks

## Current Workflow & Identify Pain Points
- Receive banner requests (PDF application, scan/email back from customer)
- Had back and forth with the customer (to confirm location is available)
- Manually enter into AMANDA
- Manually enter into Knack - Street Banner Portal (Lauren & Cathy)
- Installation crew uses it for work order/work tickets

**Q: Who are customers?**
- event organizers, city internal staff

**Q; pain points?**
- Enter into AMANDA, don't really need a permit for banners
- bc historically how payments have been tied to finance system
- having to enter into two system
- Don't enter payment into AMANDA
- Enter application and reservation 
- Payments can be taken on AMANDA portal, check to Toomey front desk
- Go into AMANDA, status update

- AMANDA doesn't reflect the real banner process

**Q: Methods of payment?** 
- Check, mailed nowadays

**Q: Approval Process workflow?**
- atxbanners mailbox -check in on location availability, approve design before they fabricate

**Q: Integrate with other systems?**
- mailbox, AMANDA, Knack

**Q: Users need automated from a system**
- Upload their design and approve it there

**Citybase payment processor, experience?**

**Payment Online**
- ABC portal
- Create user account
- Which email for user account
- AMANDA - back into system and internet user account (Applicant Account & Internet User Account) - manually link
- Then see their charges

## Desired Outcomes
### MUST HAVES
- Upload Designs for Approval
- Application Review before payment

### COULD HAVE
- Online payments with CityBase
- Customer External Application

### OUT OF SCOPE
- Reservation Availability Calendar - revisit when Smart Mobility takes over

### TIMELINE
- Hand off program with this completed project 
- two month time frame
- Smart Mobility timeline? 

Fall and Spring are busy - per week applications 5-10
- Number of emails is a lot 
- Emails for questions or follow-up

Number of customers - 
- Ton of repeat customer
- Marketing associate changes year to year 
- 1 to 5 brand new customers

No log in for customers 
- each individual application is unique

Permit ID # - Reservation number

### Consequences for not using AMANDA
- moving operations, pull report for weekly installs/removals

**Comment by moorerst** [comment]
Action items:
learn more about Citybase
Scheduled next sprint review
