### ISSUE TITLE
[Enhancement] Return user to log in page upon session termination 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4739]
Currently shows "JWT token expired" — instead terminate session and reroute user to login page.
Potentially could show a dialog that warns a user when their session is about to expire.

**Comment by amenity** [comment]
Connected to #4667.

**Comment by amenity** [comment]
If this can be resolved along with #4667 let's take care of it. Otherwise can return to the backlog.

**Comment by sergiogcx** [comment]
Comparing the output of `Auth.currentSession()` (the one that refreshes tokens, not in use) against `Auth.currentAuthenticatedUser()` (which is currently in prod), we can see the token is available and nearly identical. We can still store both objects in memory, but I'd say let's stick with current session for now.

![2021-02-18_17-02-05.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/efe3e394-8cb2-4e4c-99c6-3d95fcbe7af4)

**Comment by sergiogcx** [comment]
I've made some progress, so far the JWT Token expired message is showing, but it immediately reloads. I am working on hiding the message behind a spinner making the user wait while it reloads the page.

**Comment by amenity** [comment]
We should increase, if possible, the duration of each session to a week/month/year so that users don't lose work. Usability trumping airtight security here...
