### ISSUE TITLE
Meeting: ROW Portal Stakeholder Product Review

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4740]
### We will be reviewing the KNACK ROW Portal and your existing apps to plan the future of the ROW Portal. Please invite any staffers you feel would be a good addition to the conversation.

**Date/Time:** 4/9/21 @ 2:30pm
**Attendees:** Tracy, Chrispin, Ryan M, Paloma, Darren U, Nate, Laura R.

**Discuss:**
- Current Apps
    - Still in use? Why/why not?
- Future of the Portal
    - There are 3, which to keep?
- [TCP Tracker Migration](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/2052)

**Current Apps:**

- [ROW Operations #1](https://atd.knack.com/row-portal#home/)
- [ROW Operations #2](https://atd.knack.com/row#home/)
- [ROW Portal New](https://atd.knack.com/row-portal-new#row-portal/)
    - Chrispin recommends we use this as the official portal
- [TCP Tracker](https://atd.knack.com/amd#tcp-tracking/)
- [Permit Extension Requests](https://atd.knack.com/row-portal#permit-extension-requests/)
- [Fee Collections & Mail Merge](https://atd.knack.com/row-portal#fee-scrub/)
- [ROW Tracking](https://atd.knack.com/row-portal#row-numbers/)

**Comment by TracyLinder** [comment]
### Be sure to discuss #3824

**Comment by ChrispinP** [comment]
@TracyLinder reminder to reschedule this for this month.

**Comment by TracyLinder** [comment]
### NOTES
_I need to clean these up_

### ROW Tracking: 
Old attempt at collecting & reporting ROW performance measures. 
- We're currently using AMANDA Reports to gather data, and tracking/reporting via email. 
- Ryan would still like a performance tracking spreadsheet that all ROW groups can submit to, and provide reports. 
    - PowerBI solutions in work may meet this need. 
- The current AMANDA report(s) is a PDF output. 
**Retire/delete this mod**

---

### Permit Extension Requests

- The intent was to replace the smartsheet with KNACK so we could stop paying for Smartsheet
**Delete/scrap this mod**

----
### Fee Collections

- We did finish scrubbing the data, it's good data.
- We did not finish the debt collection. 
- Don't really need to use it, but might one day, so still need instant access to it. 
- Will need to migrate to new portal
- Mail merge should be w/ the fee collections


---
### ROW Visitor Log
- Won't need at the PDC as they already have a solution for that. 
- Export the data, provide to ROW for archiving purposes, and retire the mod. 
- Be sure no other divisions are using this before we retire it. 
- Chrispin says last updated/used March of 2020


----
atd.knack.com/row#home/
- Scrap

---
Any KNACK requests?

- Zero Damage Initiative
Start recording facility damages in the ROW (above or below ground), to track and report on damages. 
Provide a path/workflow to resolve the damages.
Cost/Fees
This program is in design/planning
Formstack form (Darren is making this) to input/collect data
Damage Ratio (DR): Per 1,000 ROW Projects, how many result in a utility hit?  
Can we reduce the number of utility hits throughout the city? 
Potential savings of 500k - 2mil

----

### Project: ROW Attendance Tracking (357)

**Comment by ChrispinP** [comment]
@johnclary @TracyLinder Lets reconvene on this discussion soon and make a plan of action on any action items to add to ROW and which old Knack apps we should officially scrap so we may close this.
