### ISSUE TITLE
Identify fields required when creating a new project

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#4742]
Product Team: 
- [ ] Decide what fields are required

Dev Team:
- [ ] add UI and validation in the create form on the proper fields

Maybe a first stab at defining these already exists? @zappfyllc 

## Required/Validated Fields:
- [ ] Map Extent has at least one line selected.
- [ ] more TBD

**Comment by amenity** [comment]
@zappfyllc @johnclary

**Comment by johnclary** [comment]
Project name, project description, at least one team member must be added, and at least one geometry feature selected?

Beyond that we need direction from users, and might should just table all of this until after user testing? I know we've already discussed that project phasing and status don't really make sense as standalone fields, but rather should be tied in some way to the project timeline.

**Comment by amenity** [comment]
Will be covered by #5376 and #4834 .
