### ISSUE TITLE
Change "Capitally Funded" to "Capital Funding"

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4745]
- [x] [Project Definition](https://moped.austinmobility.io/moped/projects/new)
- [x] [Project Summary](https://moped.austinmobility.io/moped/projects/147)
- [x] [Project Listing](https://moped.austinmobility.io/moped/projects)

**Comment by mateoclarke** [comment]
Lol, I'll claim this one. Fight the good fight Amenity!
