### ISSUE TITLE
[Feature] Moped Tables

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#4746]
Similar to our `<GridTable/>` Component in VZE but better! And Material-ui compatible.

Here's some mockups:
![Screen Shot 2020-12-17 at 11 51 39 AM](https://user-images.githubusercontent.com/5697474/102524831-1dbe1780-405f-11eb-9a9e-e66b47c4f2ba.jpg)
[Balsamiq](https://balsamiq.cloud/senhupm/p9y6tuy/r8070)

We also talked about using Algolia for search indexing and predictive text since they have a generous free tier.
https://www.algolia.com/

Related to these other issues:
- https://github.com/cityofaustin/atd-data-tech/issues/3677
- https://github.com/cityofaustin/atd-data-tech/issues/2324

**Comment by mateoclarke** [comment]
Notes from @johnclary:

> i envision that we keep the existing generic search form just above the projects table and configure it to search on a few predefined fields (e.g., project id, project name, project owner).
> there would be a "filters" toggle next to the search box that would cause this filtering interface to display.

[Knack field types with supported operators](https://docs.knack.com/docs/filters-field-types)

**Comment by sergiogcx** [comment]
Looking at the code, I am thinking this could easily turn into an Epic. Will try to make a few changes, but if the changes are too many then I will turn this into a series of issues.
