### ISSUE TITLE
New AMANDA Accounts: Cathy Kam w/ SM

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4750]
Refer to Service Desk Incident, [here](https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fatx.service-now.com%2Fnav_to.do%3Furi%3Dincident.do%253Fsys_id%3Dd70bf2021b8dec50a7951f861a4bcb5b%2526sysparm_stack%3Dincident_list.do%253Fsysparm_query%3Dactive%3Dtrue&data=04%7C01%7CTracy.Linder%40austintexas.gov%7C5bf70b17a67e4460040d08d8a29dcb1d%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637438145897817796%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YmrurDYpJwvPMryRmaoBEbdCbUnozawJXWLavDCtNoQ%3D&reserved=0)

**Comment by Nadin-Nader** [comment]
Connected to TEST and added the user as requested mirroring Kati Alcantara. I also set the automation to create the account on PROD tonight. Lastly, I  created a TASK **(SCTASK0110031)** to add Cathy to the necessary Active Directory groups.

## **Status:**
Waiting on automation to add account on PROD and CTM to add user to Active directory groups
Also waiting on User to log into PROD.

**Comment by Nadin-Nader** [comment]
The account has been created on PROD
