### ISSUE TITLE
AMANDA Account Modification: Allison R.

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4751]

**Comment by Nadin-Nader** [comment]
Checked the Permissions form and found that the only thing changed was the phone number but her email is requesting the GIS mapping portion, as well as having the ability to pull PDF copies of the TCP (Print Permissions to TCP)


> From: Nader, Nadin 
> Sent: Monday, December 21, 2020 2:19 PM
> To: Richey, Allyson <Allyson.Richey@austintexas.gov>
> Cc: Ballard, Lance <Lance.Ballard@austintexas.gov>
> Subject: RE: AMANDA Accounts Created #4232
> 
> Hope you are doing well. I was finally able to review the form you filled out but i do not see any requested changes on the form.
> 
> In order for me to make an account change I would need a similar user to copy the groups and security you will need for AMANDA. Basically the name of a person that has both of the modifications you would like.
> 
> Once I get that, I will be able to make the requested changes.
> 
> From: Richey, Allyson <Allyson.Richey@austintexas.gov> 
> Sent: Friday, November 13, 2020 8:48 AM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>; Ballard, Lance <Lance.Ballard@austintexas.gov>; Duthie, Jen <Jen.Duthie@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>; Craig, Brian <Brian.Craig@austintexas.gov>
> Subject: Re: AMANDA Accounts Created #4232
> 
> Good morning,
> 
> Thank you for the feedback. I have attached the updated permissions form.
> 
> I will reach out to them for the training inquiry. Thank you for all of your help! 
> 
> Allyson Richey, EIT
> Mobility Management Center (MMC) Manager
> City of Austin, Austin Transportation Department

## **Status:**
Waiting on response and updated Permissions Modification form

**Comment by Nadin-Nader** [comment]
I am closing this as i have not heard back from Allison
