### ISSUE TITLE
[Feature] Edit Project

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#4752]
Within the Project Summary page, we want to create a toggle button that allows the user to go from Viewing data to editing it.

All the data attributes should stay in the same place for the Summary and Teams tabs, just become editable in the toggled Edit Mode. We also want it to be very clear when you're in editing mode, maybe a bar at the top or some other visual indicators?

We also need to think ahead to which users will have permissions to edit a given page. If this isn't ready to be tackled, we need to spin out a future issue to come back to who sees the toggle to edit button/icon.

@amenity can make a mockup if more visual direction is needed. This also seems like something that there are good examples for, probably within other MaterialUI apps so whatever is the past of least resistance that provides a good user experience should be good.

**Comment by amenity** [comment]
As I'm [reading+thinking more about this](https://ux.stackexchange.com/questions/17528/is-it-better-to-have-an-edit-mode), I am curious to learn about the differences, from an implementation perspective, in creating an "edit" mode and allowing constant edit in place. There are two aspects to this: 
- The immediate simplicity/complexity of the UI that is always (to editors) editable 
- The implications in terms of version tracking— if you have an "edit" mode with a "save" button you will get a bundle of edits that can be recorded in "bulk". That said, I think it's actually helpful to see a precise history of each field, if possible. So this is an argument for an inline/always edit mode.
