### ISSUE TITLE
[RPP Back Office] Update Payment Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4755]
- [x] We will need to change a phone number for our cashier in the "Payment Options" tab and also add a disclaimer.

PAYMENT OPTIONS
 
Payment Inquiries

To pay over the phone with a credit card, call the PERMITTING OFFICE during payment hours
512-974-7857
 
*There are no additional fees charged for paying over the phone

- [x] change the Mail In Payment address from 'Parking Enterprise division' to 'Residential Parking Program'.

**Comment by ChrispinP** [comment]
phone number updated from 28 to 57 and additional language changes updated.

complete

**Comment by ChrispinP** [comment]
I have updated production again with the new number since initially it would not ring and it is now fixed.

complete
