### ISSUE TITLE
User Management | Replace "Login" in side drawer with "Log out" 

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#4758]
On smaller screens, the left side menu collapses and a hamburger button appears in the top right of the menu bar. During this transition, the logout button also hides and leaves the user with no way to logout. We could change when the logout button hides or add a logout item to the side menu. I encountered this when dev tools were open in Chrome.

<img width="1499" alt="Screen Shot 2020-12-18 at 11 10 37 AM" src="https://user-images.githubusercontent.com/37249039/102668579-dbc1ce00-4151-11eb-9067-d5c4162c296b.png">

<img width="817" alt="Screen Shot 2020-12-18 at 11 10 52 AM" src="https://user-images.githubusercontent.com/37249039/102668582-debcbe80-4151-11eb-928c-2f63370b40f2.png">

**Comment by amenity** [comment]
- Leave the logout icon as-is in Desktop
- Replace "Login" in side menu with "Log out"; can use the same `[->  ]` icon here
