### ISSUE TITLE
Re-Design Page: TIA Submission Details > Add Submission Attachment/Comment

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4764]
TIA Submission Details > Add Submission Attachment/Comment
- [x] There should only be one button/feature for emailing the requester. Currently there are two imbedded in the page; one for comments, and one for attachments. 
- [x] Can the user request the revision on this form (optional)?

**Comment by ChrispinP** [comment]
Some styling updates have been completed on the attachment/comment pages for both submissions and scope. Only one Notify Requester field exists now and I have added a menu button to the page to update the status (either approve or reject) that scope or submission during the add attachment/comment process in addition to still being able to update from main menu buttons. Rules and emails have been applied and setup for both.

Ready for testing and review

**Comment by ChrispinP** [comment]
no further action needed, closing
