### ISSUE TITLE
Bug: Emails not received on TIA Submission Details > Add Submission 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4765]
### On this page I chose Yes on both 'Notify Requestor' features, but did not receive any emails.

**Comment by ChrispinP** [comment]
@TracyLinder There is no Notify Requester options when adding a new Submission from the customer portal. Do you recall if there was another page where you didnt get an email?

**Comment by TracyLinder** [comment]
@ChrispinP I'm looking at the page this seems to be referencing, and there isn't an option to add a Submission. I'm guessing we changed the way we do this since this issue was created. 

I'm closing this. If the bug persists, we'll catch it in future testing.
