### ISSUE TITLE
TIA Mod: Review content for all system generated emails

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4768]
Review all system generated emails and update as needed. 
- We should do this closer to the end of the project.

**Comment by TracyLinder** [comment]
@ChrispinP and I will review the email workflows & content during this sprint.

**Comment by TracyLinder** [comment]
Work sesh w/ Chrispin scheduled for Friday 3/26/

**Comment by TracyLinder** [comment]
We need to document all system generated emails, a link to where the email lives in the KNACK builder, when it's triggered, who it goes to, and it's content. 

@SurbhiBakshi do you mind attaching your VZA email documentation for our reference please?

**Comment by TracyLinder** [comment]
@TracyLinder schedule a sync w/ Chrispin on this.

**Comment by ChrispinP** [comment]
All emails updated from issue #5791 . Removed original Submission Packet request email based on Fee sent status.

Joan also suggested adding this image to the email which is possible but would need to be a smaller size (prob no larger than 100 x 100) and hosted publicly on the web somewhere so I can link it.
![image](https://user-images.githubusercontent.com/67915167/115613054-90f7c480-a2b1-11eb-8e27-8ac18e0c2036.png)

Alternatively, if we can host the image, a signature image would play better with the email formatting inclusive of the other email footer text (prob no larger than 300 x 100)

Ready to review again.
