### ISSUE TITLE
Enhancement: Tia Submissions Details, Insert Review Completed Date

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4769]
### As a TIA reviewer, I'd like the system to auto-insert a value into the 'Review Completed Date' filed based on user inputs. 
- Insert sysdate when user requests revisions OR
- Insert sysdate when user approves submission

**Comment by ChrispinP** [comment]
Rules are in place to set Review Completed Date whenever revision is requested or submission is approved for individual menu buttons and update status button on attachment/comment page. Value has been added to Submission Details page and all submissions tables.
