### ISSUE TITLE
eCapris integration | Meet with Brian L. to learn about eCAPRIS

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4770]

**Comment by mateoclarke** [comment]
notes I took:

- $4bn in 5 years, bc of Covid, changed it so it was never shown to the public. Reprogramming eCapris. Show changes to airlines and council that accounted for covid.
  - reducing the outflow of money
- 9 gate expansion, parking garage $300m of work
  - real time day by day expenses 
- What DTS is building: project mgmt tracking solution for any mobility project in Austin
  - extension of eCapris
  - don't want to duplicate, don't want double entry
  - need to understand eCapris touchpoints
- Brian asks: What are we using to pull data?
  - straight SQL queries?
  - read-only access?
  - Bruce & Phil (technical POCs for eCapris)
    - "where you are going, there is no easy button"
      - If Rob says why isn't this done tomorrow
      - COA is like GE, Jet engines and toaster ovens
        - the way each of those divisions work is very different
- Our accounting system is built to take care of everything
  - Gotta understand where the dollars come from, dollars and financing 
    - **what's been spent?**
    - **what I am planning to spend going forward**
      - this is hard for orgs bc plans are always changing
    - when showing eCapris to other orgs - ppl wanted to buy it
    - Oracle db, integrated automatically in AIMES every year
    - eCapris as source of record for planning and budget. 
    - Finance wise, its actually business intelligence
    - 30% BI from financial system / 70% data origin (schedule, budgeting, planning, contracts)
      - contracts are separate but totally related to projects
        - many to many relationships
      - then take in what you have to take to Council
      - That's where eCapris is wonderful
      - in order to get reports you had to call Bruce to get anything
        - that's when they came out with MicroStrategy
        - the hard part is understanding what to ask from MicroStrategy, not putting together queries
        - just looking at tables that are available
      - terminology is challenging. for ex: term budget, "budget estimate", "spend plan budget", 'budget in AIMES' = apropriation in eCapris
        - mess of terminology, need at CoA PHD to understand
        - data is all there, and you can do amazing things with it and its not easy. 
    - Project Systems Intelligence Office
      - built a lot of things but didn't have a lot of users
      - found that their systems didn't influence decision making
      - "what type of thing do you want to make better decisions?"
      - Ex: from Director of Airport - "I want to know how much over budget we are?"
        - from original plan? from when we first bid it? from when construction started? from where we are now?
        - easy request for her to make, but hard to get back
        - contracts, task orders, interdepartmental charges
        - FDU cycle
        - once you start to blend operating, getting into eCombs

- Everyone wants transparency and data, but the amount of data we're talking about can tell stories and we're all biased in how we show the data.
  - Be ready for some black eyes, you'll have sponsors that don't like how you are showing things.
  - ex: 2016 Bond, getting behind, there's going to have to be a story about why
  - was having the challenge to get everyone on board doing things from the bottom up.
- Brian has MicroStrategy set up to look like eCapris
  - offered to give us a tour, combined metrics to make them time dependent
    - spend plan
      - doesn't get compared to expenses until the end of year
    - appropriation plan
    - reusing MicroStratgey SQL queries into Tableau
- eCapris and AIMES don't have good training
- Once we get good at tracking spend, then you can plan better
  - spending plan is cash flow you think
    - a successful spend flow is cash flowed the way it was supposed to be
    - no one does this well.
  - Earn value analysis
    - looks at schedule, risk, expenses on a chart
    - Tracking way more, are you ahead of schedule or over budget?
- quick eCapris tour
  - start with spending plan
    - real world is Object Code
    - Report Codes
    - FDUs
      - subproject is a group of FDUs

- Going forward:
  - schedule appoints with Brian
    - specific agenda of what to talk about:
      - helping getting things setup in Microstrategy, and then we can make that a connection, work on connections, get the power that everyone else has done.
      - advice on feature sets, demo of what we're building

**Comment by amenity** [comment]
Brian L.

- Went to CPO, then at Airport since March
- Reprogrammed their use of eCapris so that they could manage giant capital projects in it while accommodating drastic schedule/funding changes (e.g. COVID)

- Needed real-time day-by-day expenses
- "Everyone wants transparency and data...But it's always going to be biased." Be ready for black eyes if you push for transparency


**Data**
To get access, talk to Bruce N. - Financial Services @ Controller

  - What's been spent to date, last year, etc. 

  - What's going to be spent going forward

    

**eCapris**   
- Source of record for 
  - Budgeting
  - Spending
  - Funding - FDUs, contracts (many-to-many)
  - Appropriation
- 30% BI that pulls data from AIMS
- Planning - for some projects
- Off-label use as Airport's tenant-managment system



**Data analysis**

- Use Microstrategy, the hard part is pulling the eCapris data itself in addition to the 
  - Microstrategy Office clicks to update and Excel
  - Tableau users at Airport take Microstrategy SQL code 

- Appropriations load automatically into AIMS every year
- Looking at [ThoughtSpot](https://www.thoughtspot.com/) for automated BI  



**Follow-up meetings**

- eCapris Data
  - How is eCapris data being accessed and used in other applications?
    - BI in Microstrategy 
    - Microstrategy Office + Excel — Allows (who?) to work 
    - Tableau (u)sers at Airport take Microstrategy SQL code 
  - Identify Moped + eCapris data connections

- Moped demo and roadmap review

**Comment by amenity** [comment]
[Today's meeting](https://github.com/cityofaustin/atd-data-tech/issues/4770)
- eCAPRIS basics
- Austin Finance Online
- Constructing eCAPRIS queries in Microstrategy

cc/ @mateoclarke @zappfyllc @sergiogcx
