### ISSUE TITLE
TIA Mod: Review Customer Portal UX/UI

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4772]
Review the portal with stakeholders and make updates as needed. 
- Let's do this when the backend app is closer to done.

**Current Public Facing Pages:**

- TDS Home/Landing Page
- TIA Portal (Start application page)
- View TIA Details Page
- View Submission
    - Edit Submission
- View Scope Submission
    - Edit Scope

**Comment by ChrispinP** [comment]
Did some cleanup work on styling, formatting text, and cleaning up details. Also improved submission buttons, opacity, hover, size, etc. Will need to consider mobile optimizations.

**Comment by TracyLinder** [comment]
### Review Agenda

- Introduce the new home page
- What content should go on TDS Portal Home, Tia portal Landing Page

**Comment by TracyLinder** [comment]
This is ready for usability testing. We will create issues for any updates as the need arises. Closing.
