### ISSUE TITLE
Feature: Updating reviewer names

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4776]
### As a TIA Mod power user, I need to be able to update reviewer names.
- We need to be sure that changing a reviewer will not update existing records (we need to preserve record integrity)

**Comment by ChrispinP** [comment]
Updated conditional rules on Reviewer Name Division connection field to only set the Reviewer name if the field is blank to maintain integrity of reviewer names on existing cases.
![image](https://user-images.githubusercontent.com/67915167/103245732-b63d7d00-4926-11eb-92c1-fb0987a1b297.png)

We may want to think about future Reviewer changes if we should have a form within the app to update these rules or if we should maintain as is with the onus on a knack builder to update the conditionals on this connection field when necessary.

If we want to test this we can change a name, create a new request record, then change the name back and see if the field integrity is maintained.

Ready for Test and Review

**Comment by ChrispinP** [comment]
Spoke with Apps team and depending on order of operations, we may be able to use some JS to pull in reviewers from mapping areas and set them to the appropriate areas.

In addition to districts and reviewer areas, stakeholders will likely be requesting area classifications like urban core, suburban, etc so we will likely need to incorporate them as well.

**Comment by ChrispinP** [comment]
will create new issue if we decide to update reviewers based on our future mapping integrations. otherwise, no further issues, closing
