### ISSUE TITLE
Moped Editor: GridTable bug with cache enabled

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#4788]
There seems to be a strange problem happening when using the `cache-first` fetch policy in Apollo. It appears as if it is always loading. I do not understand why or how this bug happens. 

In this case, I have been working on the projects list, and somehow it only affects certain sub-components of the GridTable component. This is fixed by using a no-cache policy, but it is strange that VZE was not affected by this. It is unpredictable what subcomponents will be affected, but more homework is needed.

![2020-12-28_12-20-44 (1).gif](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/f6d3f7ad-532e-43a7-ac00-c1b3e9a7dd86)

![2020-12-28_12-20-08 (1).gif](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/03b75269-5103-41f3-9b7f-3c86bd8f5cd5)

**Comment by sergiogcx** [comment]
I've been reading some threads, but nothing conclusive as to what may be happening:

https://github.com/apollographql/react-apollo/issues/3361
https://github.com/magento/pwa-studio/issues/2230
https://github.com/apollographql/react-apollo/issues/3270

**Comment by amenity** [comment]
This is a problem in Apollo that we encountered in VZE. We averted it there by using a no-cache policy.

**Comment by amenity** [comment]
@mddilley - please review and see if ☝️  is still the right approach.

**Comment by amenity** [comment]
This was addressed as described above.

**Comment by mddilley** [comment]
I spent some time looking at this and agree with Sergio and our previous experience in VZE that it is an elusive bug in the Apollo library. I was able to reproduce by changing rows per page in `GridTable` (as shown in the screenshot above).

I found some workarounds that involve triggering additional re-renders or using combined logic of `loading` and `data` [results](https://www.apollographql.com/docs/react/api/react/hooks/#result) from `useQuery`, but it doesn't seem worth it at this point with `no-cache` fetch policy working. 

Workarounds:
https://github.com/apollographql/react-apollo/issues/3270#issuecomment-621247569
https://github.com/apollographql/react-apollo/issues/3774#issuecomment-651786246

Hopefully, if this becomes a performance issue down the line, there will be a patch that addresses it on the Apollo side.

Migrating to [`@apollo/client`](https://github.com/apollographql/apollo-client) https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/ might also fix this issue.
