### ISSUE TITLE
Bug: Customer Link to TIA Submittal Not Working

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4792]
### The Customer email/link to submittal comments & attachments not working correctly. 
- See: https://atd.knack.com/development-services#review-tia-case-status/view-tia-details/5fdd188b30b2f0001ce7e4b6/

**Comment by ChrispinP** [comment]
@TracyLinder Do you recall which email this one wasnt working for? Ive checked the Scope Revision email.

**Comment by TracyLinder** [comment]
@ChrispinP I think this is the email w/ the link. 

![image](https://user-images.githubusercontent.com/49930868/104483809-263a3d00-558e-11eb-8763-fc062b009e48.png)

**Comment by ChrispinP** [comment]
closing as resolved.
