### ISSUE TITLE
Bug: No content on the landing/confirmation page after submitting application 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4793]
### When submitting a test case today, the content on the successful submission landing page was missing.

**Comment by ChrispinP** [comment]
Im not sure we ever had anything on this confirmation page but if we would like to add a message or other content here, will need to know what to add that is useful.

**Comment by ChrispinP** [comment]
Okay, Im a bit silly. Forgot there was a page rule that displays the message, not a rich text view. The rule incorrectly updated at some point when the Request Status field was updated. Ive fixed the rule and the confirmation message should now appear again.

Ready for review

**Comment by ChrispinP** [comment]
no further issues, closing
