### ISSUE TITLE
Enhancement: Scope Status Upon Submittal

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4794]
### When a new application is submitted, the scope status should default to something like 'Needs Review', and the review shouldn't start until user clicks 'Begin Scope Review'

**Comment by ChrispinP** [comment]
Created a new Scope Status 'Needs Review'. A new application will set Scope Status to the 'Needs Review' status. Updated page rules for both Scope and Submissions so the new statuses correctly message and hide buttons.

Complete, ready for review

**Comment by TracyLinder** [comment]
Looks good; closing
