### ISSUE TITLE
Bug: Applicant link to revise scope doesn't allow them to resubmit

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4795]
While testing today, we requested a scope revision from the applicant. The system sent the applicant an email with a link for resubmitting, but the page for that doesn't offer a feature to resubmit.

**Comment by ChrispinP** [comment]
Double checked url and repasted the Record ID. Was able to revise scope for a request and access the Case Details via the email in Google Chrome. Pasting in Edge and Firefox also worked

If page is unable to load for you still Tracy, it may be a browser cache issue.

Ready for review

**Comment by ChrispinP** [comment]
rebuilding scope now to function similar to submissions. requesters will soon be able to resubmit a new scope and determination form as necessary. no further issue, closing
