### ISSUE TITLE
TDS Portal: Review Account Management

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4797]
### TIA leads need to be able to manage accounts for the TIA mod.

- How is the other mod managing accounts? 
- May need a new account management page for TIA mod

**Comment by ChrispinP** [comment]
Spoke with Apps team and considering that many Development Service requests will need TIA's as the next step in the process, it may be best to create a single login for both. If necessary, we can assign multiple roles to a reviewer or user. This would also allow users to see both development reviews and tia reviews in one place if desired.

**Comment by ChrispinP** [comment]
I have updated the Account Management page with updated filters and some cleanup. Both Admin and Project Manager users can see Account Management and either Edit or Add users. Should we give TIA Leads the Project Manager role or should we tag them with a new TIA Lead user role?

Ready to review

**Comment by TracyLinder** [comment]
Let's review this at the project meeting on 3/29/21.

**Comment by TracyLinder** [comment]
Let's look at this w/ project team on 3/29/21

**Comment by ChrispinP** [comment]
Removed menu links to Home and Reviewer Dashboard. Moved the page menu next to Reviewer Dashboard so Menu looks nicer.

**Comment by TracyLinder** [comment]
Looks great!
