### ISSUE TITLE
User Management | Implement default avatars

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4798]
### User icon
https://feathericons.com/?query=user `user`

### Or initials (preferred)
![Screen Shot 2020-12-28 at 9 40 57 PM](https://user-images.githubusercontent.com/1463708/103257102-7215a100-4955-11eb-8deb-763abbba93d2.png)

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/202
