### ISSUE TITLE
[Enhancements] "Projects" page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#4799]
## Big features
- Quick filters (project sponsor, fiscal year, council district(?))
- Edit in place — 😬
- Toggle columns shown(?)
- Save :point_up_2: (with Advanced Search, if applied) as a “View” - tile could go on Dashboard
- [Collapse rows on mobile](https://material-ui.com/components/tables/#collapsible-table)?

## One-offs
- [[Enhancement] Extend filtered search functionality](https://github.com/cityofaustin/atd-data-tech/issues/8579#)
- [[Enhancement] Refine CSV export](https://github.com/cityofaustin/atd-data-tech/issues/8454)
- #8595

**Comment by amenity** [comment]
Some of these may not be applicable any longer, but I know that spinner could still use a bit of polish. 💅 
cc/ @patrickm02L

**Comment by amenity** [comment]
Mateo's comments in the OG issue: 
## Loading spinner
Padding around the loading spinner. I think the spinner could use a little room to breathe here. Could even see it being centered.

Side note: I also see the page load twice when I first log in. 

![Screen Shot 2020-12-28 at 2 40 08 PM](https://user-images.githubusercontent.com/5697474/103242208-09a9ce00-491b-11eb-9f18-879d07d0188c.jpg)

## Sortable headers

The alignment of the sort arrow and the way the text wraps looks a little off visually.

![Screen Shot 2020-12-28 at 2 40 15 PM](https://user-images.githubusercontent.com/5697474/103242232-20e8bb80-491b-11eb-9a89-672852ab8f64.jpg)

Maybe the example from the [Material UI `<DataGrid>` component](https://material-ui.com/components/tables/#data-table) could be a good example to look at.

![Screen Shot 2020-12-28 at 2 46 11 PM](https://user-images.githubusercontent.com/5697474/103242358-889f0680-491b-11eb-942e-2617b8bf0482.jpg)

[Material-Table](https://material-table.com/ ) also has some good examples for visual inspiration.

I couldn't get a screengrab of this but I would only expect the column headers that are sortable to show the `cursor: pointer` on hover. The rest that aren't sortable, I would expect a more default cursor. The pointer implies there is interactivity.

**Comment by johnclary** [comment]
We need a design spec for the advanced search state (how does one exit advanced search?)

**Comment by patrickm02L** [comment]
New search: remove search button (users can hit return to confirm query), download button icon has changed.

![Advanced Search.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/b4edc87a-685c-4228-bce3-6f809d11bcc2)

The advanced search becomes a drop down which can expand in a modal.

![Advanced Search drop down.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/cf95fe27-1626-472d-98f5-9941b863d754)

**Comment by patrickm02L** [comment]
Mobile views:

Normal Search
![iPhone 12 - New Search.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/ee0963bd-a738-4eb0-a342-684e2733b1ff)

Advanced Search one filter
![iPhone 12 - New Search Advanced.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/9eed43f2-ec06-4b04-8c59-f1d3265ea503)

Advanced Search two filters
![iPhone 12 - New Search Advanced multiple fields.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/17badfaf-0de3-4dc1-a080-2aa53b2596ef)

**Comment by amenity** [comment]
Beautiful, @patrickm02L🙏. . Created an issue for implementation here: 
https://github.com/cityofaustin/atd-data-tech/issues/7207.

**Comment by johnclary** [comment]
Great work everyone! I'm closing this. We have more changes coming via https://github.com/cityofaustin/atd-data-tech/issues/15353
