### ISSUE TITLE
All hands offsite meeting

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#48]
This is a time to step back and look at the bigger picture: Where do we want to go, and how do we want to get there? 

Feel free to add and comment to [this collection](https://docs.google.com/document/d/1PVhLUgdLfUqESp6s68whTDdxM7ySkrIh9QH-LlOcnWs/edit#) of starting points and example mission, values, and tactics statements.

-----

### Location & parking

The Central Library is just down the road from City Hall and an easy 7 to 10 minute relaxing walk West. We encourage all City employees to park at City Hall and enjoy the vibrant downtown atmosphere as you walk to the library. For those that need to park onsite, the entrance to the Central Library parking garage is located on the West side of the building on West Street.

Special instructions for a pre-10am meeting:
_[See PDF for photos and maps](https://drive.google.com/open?id=1cGeh4KsE00FNzpZbrtpNS6nhJM3tSPqw)_
- Heading west down Cesar Chavez take a right onto West Avenue.  The garage entrance will be on your right.
- The Garage will be CLOSED – approach the barricades and inform the security guard you are there for an training on the 4th floor. They will remove the barricades.
- Pull a parking ticket and enter. Bring your parking ticket with you to the meeting to be validated.  
- Park on LEVEL P2 close to the Elevator on the 2nd street side of garage
- Take elevator on the 2nd street side of the garage to the sidewalk outside of the 2nd street main entrance.
- Staff will meet you at the entrance doors to give you access into the library.
- Take the main elevator in the lobby up to the  4th floor

Shared Learning Room, (SLR) 471 is on the 4th floor. Click on the SLR 471 link at the bottom of our [Shared Leaning Rooms Schedule](http://library.austintexas.gov/rooms-calendar/ace/daily) online to assist in locating the room.

**Comment by mateoclarke** [comment]
@amenity, We can close this now right?

**Comment by amenity** [comment]
@johnclary - will you upload the photos you took here? https://drive.google.com/drive/folders/1FtnSp5paNUHTnfIAOnrJaNf1qHqL8L2p

**Comment by johnclary** [comment]
@amenity done.
