### ISSUE TITLE
ProjectsView: Optimize project filters for small screens

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4804]
The project filters on [this page](https://austinmobility.io/projects) don't look great on a small screen. Not sure what to do about it. Maybe hide them and display a "Filter" button that pops an overlay where you can set them?

![Screen Shot 2020-12-29 at 11.51.25 AM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/e28856e6-83c1-4d30-8d29-683e040d9cb0)

**Comment by amenity** [comment]
@johnclary @tillyw — sticking this in https://github.com/cityofaustin/atd-data-tech/issues/6034 for the CIC dev to work on. Should it go in "Needs Scoping" since there are design decisions to be made before implementation?
