### ISSUE TITLE
Bug: UC Portal App missing Dates Infos

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4807]
**Description** - The portal application for the Utility Coordination (UC) folder is no longer populating necessary info fields. 
Infos Missing: Estimated Start Date, Estimated Completion Date

We cannot perform a review without this info from the applicant. Also, ATD doesn't have any development resources staffed right now so we'll need CTM to perform the fix. 

To find the UC portal application: Apply for Right of Way Permits/Special Events > Utility Coordination

- Service Now ticket submitted, INC0073656
- Stakeholder: Jaclyn L.

**Comment by Nadin-Nader** [comment]
This has been fixed according to Swapna's comment in the incident
