### ISSUE TITLE
Update "eCapris ID" to "eCapris Subproject ID"

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4808]
During today's Sprint Review, Cole and Lianne pointed out that we actually want to name the field "eCapris Subproject ID"
![Screen Shot 2020-12-29 at 5 55 04 PM](https://user-images.githubusercontent.com/1463708/103321381-00922d00-49ff-11eb-9fc6-0b147c5c8b7c.png)

**UI task**
- [x] Rename "eCapris ID" to "eCapris Subproject ID"

**Database tasks**
- [x] Rename eCapris_id to eCapris_subproject_id for consistency
- [x] Add a numeric column for eCapris_subproject_pk (subproject_id is mutable, this is the real unique value)

**Comment by amenity** [comment]
@zappfyllc - Can I get your blessing on this change?  (It's called `eCapris_id` in the database, but I assume that's for brevity's sake.)

**Comment by zappfyllc** [comment]
Per @johnclary's comment in issue #3668, these tasks should be done on this issue:

- [ ] Rename eCapris_id to eCapris_subproject_id for consistency
- [ ] Add a numeric column for eCapris_subproject_pk (subproject_id is mutable, this is the real unique value)

**Comment by zappfyllc** [comment]
@amenity is this a duplicate?

**Comment by amenity** [comment]
@zappfyllc - I believe so. @tillyw updated the frontend. Is the database table renamed?

**Comment by tillyw** [comment]
> @zappfyllc - I believe so. @tillyw updated the frontend. Is the database table renamed?

Not that I'm aware of. The changes I made as outlined in other issues pertained only to the UI. The database table hasn't been renamed, unless someone else did it. @sergiogcx @mddilley @mateoclarke

**Comment by amenity** [comment]
@zappfyllc - pretty sure this issue was to update the table, so not a duplicate.

**Comment by sergiogcx** [comment]
There is PRs:
- https://github.com/cityofaustin/atd-moped/pull/271
