### ISSUE TITLE
Render user avatar images in activity feed

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4809]
- [ ] Users should be able to upload, delete, and replace a photo at https://moped.austinmobility.io/moped/account
- [ ] The photo should render wherever anywhere we use the `MuiAvatar` component, like the 
<img width="1131" alt="Screen Shot 2021-03-08 at 1 21 31 PM" src="https://user-images.githubusercontent.com/1463708/110370614-87701100-8011-11eb-9a44-f304e28fbb27.png">

**Comment by mddilley** [comment]
We mentioned showing these profile photos in the personnel table in https://github.com/cityofaustin/atd-data-tech/issues/4876

**Comment by sergiogcx** [comment]
There is a PR:

https://github.com/cityofaustin/atd-moped/pull/386

![2021-08-04_20-40-24.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/eefb70b3-873e-4c79-bce3-19b236c4244e)
