### ISSUE TITLE
eCapris integration | Learn about eCapris data access

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4812]
- Overview of eCapris data 
- How is eCapris data being accessed and used in external platforms?
   - BI in Microstrategy
   - Microstrategy Office + Excel
   - Tableau users at Airport take Microstrategy SQL code

**Comment by amenity** [comment]
1/20/21 Meeting with Controller's Office
@johnclary, Tina VW, Bruce N., Phil K., Cole K. Peggy, Megan B. 



Next big features
- Partnership FDU
- Schedule — additional templates


How to stay up to date with eCAPRIS progress?
- Emails
- Release notes in the app

What departments are accessing Microstrategy Data Warehouse:
- Austin Resource Recovery — integration with OpenGov software 
- Austin Energy — procurement and master documents
- Austin Water — get financial data
- SMBR — integration with B2GNow 



How to access Microstrategy Data Warehouse?
- Send email to microstrategyhelp@austintexas.gov
  - Can have view-access to whatever tables we need
  - Ask what we want and create views using Microstrategy SQL

Questions on eCAPRIS ecaprishelp@austintexas.gov

**Comment by johnclary** [comment]
TIL the finance data we’ve been [pulling from the controller’s office]( https://github.com/cityofaustin/atd-finance-data) is coming from the same microstrategy database that we’ll use to access eCapris data. Credentials are in the developer vault.

**Comment by amenity** [comment]
Meeting with Brian scheduled for 1/28  at 2:30pm.

**Comment by amenity** [comment]
More notes in the epic parent; closing this one.
