### ISSUE TITLE
Unable to connect PowerBI to MMC Issues dataset

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4817]
Lance reports that he's getting the below error message when trying to import [this dataset](https://data.austintexas.gov/Transportation-and-Mobility/Mobility-Management-Center-Issues/v7vh-gbi6/) into PowerBi.

![thumbnail_image001](https://user-images.githubusercontent.com/14793120/103364503-a12a3080-4a83-11eb-8b3c-2d5bb1791599.png)

**Comment by johnclary** [comment]
@SurbhiBakshi will try to re-produce and open a Socrata request.

**Comment by SurbhiBakshi** [comment]
- I checked the Odata endpoints.It looks like the V2 one works and I get the same error as Lance for the v4 endpoint. 

- asked Lance if he can check if V2 works.

-  I shall put in a ticket with Socrata and also reach out to Marbenn at CTM to see if he know why the V4 does not work.
