### ISSUE TITLE
Project Extent | Restore outlines of VZ polygons

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4821]
During the Sprint Review, we learned that the VZ Polygons, because they are derived from the ASMP, actually contain unbuilt geometries that aren't visible on the base map. We want to enable users to easily select these polygons so we should turn back on the polygon outlines. Use a partial opacity to reduce visual noise.

**Comment by mddilley** [comment]
I updated the colors and opacity based off of feedback [here](https://github.com/cityofaustin/atd-moped/pull/172#issuecomment-755082468), and I think that it looks much better than the grey outline as well. The color for each layer is set in a config, and the opacity indicates the three states: selected (75%), hovered (50%), and unselected (25%). Happy to adjust as this moves further along.

 ![Screen Shot 2021-01-07 at 6.01.04 PM.png](https://images.zenhubusercontent.com/5cfe7d078509cb6dcbaafdc3/343a5b64-3649-43f7-a21d-d6e14831625e)
