### ISSUE TITLE
PSM Bug: Folder Expiration Date Inserts Before Folder Issuance (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4822]
### As the system and PSM Folder reviewer, i have noticed that the system inserts the folder expiration date before the folder is issued. The expiration date should only populate after issuance.

**Acceptance Criteria** 

- Expiration Date for PSM folders needs to be inserted ONLY when the Issue/Approve button is clicked on the Folder. 
- Currently expiration date inserts when Approved attempt is made in Maintenance Agreement Process (83728). This logic needs to be removed.  

- See test RSN 12396688 for example. The folder expiration date is inserted when the Maintenance Agreement Process (83728) is approved/closed.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have scheduled a meeting with Paloma, Kim and Isabel for 6/22/21 at 3pm

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder - @Nadin-Nader will update the Acceptance Criteria to proceed further on this card.

**Comment by Nadin-Nader** [comment]
**Status:**

@vschandramouli Visj will be scheduling time with Kim and Paloma to Scope this a bit more

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by SubhaShroff** [comment]
1. I assume its COMPLETE attempt but not APPROVED, as there is no approved attempt with Maintenance Agreement Process (83728). Please confirm on that.
2. Assuming its COMPLETE attempt, I checked the code for it. With this attempt, the system triggers ISSUE procedure of the PSM permit. This procedure is updating the expiry date along with the following validations :

- if SubCode is Street Patio or Café/Patio Combined, check 'Number of Parking Spaces(50355)' is not null.
- TABC expiration date,  insurance expiration date, bond expiration date validation if the respective flags are selected as YES.

  So, if I remove the call to ISSUE procedure, above validation checks won't happen with COMPLETE attempt.  Will that work for the user if validation not happen with COMPLETE attempt on Maintenance Agreement Process (83728)?

**Comment by TracyLinder** [comment]
### My Feedback

- Complete attempt is correct
- We need to remove the call to issue procedure. 
- We must keep those validations.
- We should add the validations to the process attempt **Complete** - system should check those validations and throw the same errors. If validations aren't met the system should not save the process attempt.

**Comment by SubhaShroff** [comment]
Thank you @TracyLinder 
The changes are done and DEV deployment request is submitted for the commit - SCTASK0209763.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is deployed in DEV and I tested it. We can do UAT today, in the call.

**Comment by Nadin-Nader** [comment]
## Approve to Move to TEST and PROD if all is well on TEST

**Comment by SubhaShroff** [comment]
@Nadin-Nader  TEST deployment request is submitted - SCTASK0209914.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  PROD deployment is done for this ticket.

**Comment by SubhaShroff** [comment]
### Status: 
On PROD a week ago. I am not sure if the stakeholders are informed to do the review.

**Comment by TracyLinder** [comment]
PSM application volume is low, so testing in PROD isn't an option right now. Closing this.
