### ISSUE TITLE
Enhancement: Add PSM People Types (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4823]
### As a permit analyst, I need to add people types that are not currently available on the PSM folder. 

**Stakeholder:** Paloma

**Acceptance Criteria:**
Back Office: 
- System should allow user to select from all People roles available in AMANDA when user is trying to add a people record to the PSM folder. 

Public Portal:
- User should be able to add a Contact People type when applying for a new PSM permit through the portal. 
- Contact People type should not be mandatory to add when user applies for a new PSM permit through the portal.

**Comment by Nadin-Nader** [comment]
Not enough info. Needs more Scoping

**Comment by vschandramouli** [comment]
Updated AC. Moving to Backlog.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0217164 is submitted for DEV deployment and its deployed in DEV. I tested it and following are the screenshots from DEV. 
**People page added and the contact people type is added (not mandatory). _But I observe its not displaying the title 'Contact'. I will get it fixed.**_
![image](https://user-images.githubusercontent.com/51680715/167663181-af9a32a1-74e6-49f6-bdc8-fd576950ba79.png)

**On Back office, now People type dropdown displays all the types**
![image](https://user-images.githubusercontent.com/51680715/167664226-fceb38cf-8285-4c2f-a6f1-d8013df0fe26.png)

**Comment by SubhaShroff** [comment]
Thanks @vschandramouli to get the following confirmation from Paloma.
[4:10 PM] Chandramouli, Vishwa - Vendor
Hey Vish! I went back to the PSM folder process doc to see what it said but it doesn't include that level of detail. I suppose I am okay with not requiring a contact but it would still be good if it at least offered the applicants the option to add a contact. As for adding the Applicant people record by default, yes that is how we would like it to work. The real issue is that back-end users need to be able to add other types of people records to the folder and presently they are unable to do that.

[4:10 PM] Chandramouli, Vishwa - Vendor
From Paloma
==============================

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0217958 - DEV promotion request  is submitted  to fix People type title on Portal people page.

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0218851 is submitted to revert the previous commit - to undo the extra line that is added in the above screenshot. I have texted Swapna on Teams, to guide with the CONTACT title display.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0219141 is submitted for the DEV deployment of LOOKUP table update.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @vschandramouli This ticket is deployed in DEV and I have verified. Now the portal page displays as follows.

![image](https://user-images.githubusercontent.com/51680715/169310335-a2c6afe4-17a6-4024-abe3-6d6aaf2a53e9.png)


SCTASK0219258 - TEST deployment request is submitted after Nadin approved.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @vschandramouli  This ticket is in TEST and verified. Ready for UAT.
RSN 12867326 - Contact people selected from portal
RSN 12867327 - Without selecting Contact people

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  SCTASK0219721 - is submitted for PROD promotion.

**Comment by Nadin-Nader** [comment]
@SubhaShroff This has been deployed to PROD. I will let the stakeholders know

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The PSM PROD deployment is re-done. I verified it on database and all good. Can we ask the user to verify it on PROD Amanda/portal?

**Comment by Nadin-Nader** [comment]
This is good to go. Closing
