### ISSUE TITLE
Delete "csr_flex_notes" from Signs & Markings - Feb 2021

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4827]
Received automated reminder to delete flex notes in Signs and Markings Operations PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings#data/object_172/records

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 12/01/20

Total Records: 10,761
To Delete: 2,963
New Total: 7,798

**Comment by SurbhiBakshi** [comment]
@ChrispinP - I can take care of Signs and Markings, if you want to work on AMD Data Tracker. Removed you from this issue.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/f4af27bc-5f54-45fc-ab53-cdd7bde8f7c5)
