### ISSUE TITLE
Delete "csr_flex_notes" from AMD Data Tracker - Feb 2021

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4828]
Received automated reminder to delete flex notes in AMD Data Tracker PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/amd#data/object_95/records

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 12/01/20

Total Records: 22589
To Delete: 7380
New Total: 15224

**Comment by SurbhiBakshi** [comment]
Hi @ChrispinP, the created date should be before 11/01/20. We delete records that are closed and were created before two months https://app.gitbook.com/@atd-dts/s/atd-knack-operations/data-tracker/csr-or-flex-note-archiving

**Comment by ChrispinP** [comment]
Flex Notes have been removed, complete
