### ISSUE TITLE
Delete "csr_flex_notes" from Signs & Markings - Jan 2021

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#4829]
Received automated reminder to delete flex notes in Signs and Markings Operations PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings#data/object_172/records

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 11/01/20

Total Records: `11,061`
To Delete: `4,230`
New Total: `6,831`

**Comment by SurbhiBakshi** [comment]
thanks @ChrispinP for creating the issue.

**Comment by SurbhiBakshi** [comment]
![image](https://user-images.githubusercontent.com/13035849/103419830-4dd6e180-4b5a-11eb-9331-8a8ccaf9965c.png)
