### ISSUE TITLE
[Enhancement] Tweak tab navigation on DTS Portal

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4833]
These changes will make finding the Application Inventory more intuitive and avert the blank page situation users currently see if they click on the "Data Inventory" tab directly instead of one of the dropdown items. 
- Make tabs for "Applications" and "Datasets"
- Get rid of "Data Inventory" tab

**Comment by amenity** [comment]
@johnclary - hoping this is a 1? No rush, can ride along with some future DTS Portal work.

**Comment by johnclary** [comment]
yep—good call. any of our builders can knack that out pretty quickly.

**Comment by dianamartin** [comment]
- [x] Removed the `datasets` and `applications` pages for the Page Menu "Data Inventory"
- [x] Updated the JS for the big button on the home page from "Data Inventory" to "Datasets"
- [x] Added JS for big button "Applications"
