### ISSUE TITLE
Implement refinements to "Define project" and "Assign team" in new project workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4834]
### Define project
- [x] **Make required fields: Name, Description**
- [x] Sentence case "Define project" (lowercase "p")
- [x] Remove "Project" in first two field names — _Name_, _Description_
- [x] Sentence case all multi-word field names: _Start date_, _Fiscal year_, _Current status_, _Current phase_, _Capital funding_
- [x] _Name_ field 50% width and on row by itself (desktop) 
- [x] _Description_ field 50% width and on row by itself (desktop)
- [x]  _Start date_, _Fiscal year_, _Current status_, _Current phase_, all 1/4 width and in one row (desktop)
- [x] Remove "Priority"
- [x] Rename "eCapris ID" "eCAPRIS subproject ID" — ps [this was entertaining](https://stackoverflow.com/questions/1151338/id-or-id-on-user-interface)
- [x] Remove "Back" button to nowhere🕴️

### Assign team 
- [x] Sentence case in "Assign team" 
- [x] Sentence case in "Project team" 

 
![Screen Shot 2020-12-30 at 1 17 11 PM](https://user-images.githubusercontent.com/1463708/103597268-7990f900-4ec5-11eb-9385-54a384fd92ef.png)

**Comment by amenity** [comment]
![Screen Shot 2021-01-29 at 10 45 35 AM](https://user-images.githubusercontent.com/1463708/106400836-8e8a7a80-63e6-11eb-8d0e-588e1b391370.png)

@zappfyllc - 
Should "Start date" and "Fiscal year" be conditionally visible based on status? E.g. hidden if status = potential? ?

**Comment by amenity** [comment]
Also, @zappfyllc - what fields should be required for a new project? 

My guess:
- Project Name
- Project Description
- Current Status

I am pretty positive Start Date is _not_ required, so we will need a way to either only show it when logical (see [previous comment](https://github.com/cityofaustin/atd-data-tech/issues/4834#issuecomment-770467788) or clear the field.

**Comment by amenity** [comment]
@johnclary @mddilley - how would you recommend we enforce the requirement to provide a location for a project? Display an alert if they haven't selected at least one line segments?

**Comment by mddilley** [comment]
@amenity I think an alert is a great idea. We could add a check to the flow that happens after the user clicks the "Finish" button and trigger an alert above the button, on top of the map, or anywhere that would be obvious to a user. The button would not submit the project form data until at least one segment is selected.

**Comment by johnclary** [comment]
sounds good to me. suggest putting the alert near the submit button to make sure the user sees it.
