### ISSUE TITLE
[Feature] Finance and Purchasing Integration

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4837]
Integrate with DTS' Finance and Purchasing Knack app.

**Comment by johnclary** [comment]
@amenity closing as a dupe of [#4530](https://github.com/cityofaustin/atd-data-tech/issues/4530)

**Comment by johnclary** [comment]
Ah, just realized this is the epic on the v1.0 roadmap. @amenity i don't want to mess that up any further so FYI sorry.

**Comment by amenity** [comment]
@johnclary - no I was about to do the same thing.
