### ISSUE TITLE
[Feature] Usage Analytics

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4839]
Free, open source options: 
- [Countly](https://support.count.ly)

Vendor options we have experience using 
- HotJar
- Google Analytics

**Comment by johnclary** [comment]
If we do this—I'd like use to write out really clear and compelling use cases before we start sharing our user data with Google or another vendor. There are FOSS alternatives. E.g. [countly](https://github.com/Countly/countly-server).

**Comment by johnclary** [comment]
I put together some sample reports of what we can pull from our own activity log, [here](https://docs.google.com/spreadsheets/d/1iiU9VABepO0z-NBIlnlSpHrSoGiQRn3P67izlIAMGEg/edit#gid=247060807).

I'm going to repurpose this epic to focus on analytics and reporting that we can derive in this way, from our own DB.

![New projects created](https://user-images.githubusercontent.com/14793120/197591166-294aed2e-83ad-4b54-8f4e-ec79b42e35aa.png)

![Daily activity events](https://user-images.githubusercontent.com/14793120/197591170-cf899806-9da3-493a-aad0-26471ec97bc0.png)

![Activity by record type](https://user-images.githubusercontent.com/14793120/197591173-34ee3156-c6be-4a1b-8569-7d7360e5d542.png)

**Comment by johnclary** [comment]
also for consideration: https://www.goatcounter.com/

**Comment by johnclary** [comment]
I [set up a system](https://github.com/cityofaustin/atd-moped/pull/1197) for keeping track of when users open Moped in their browser. This gives us:
- A timestamp of the last time each user used Moped
- A running list of Moped page load events

Combined with the activity log we have solid coverage of our basic app usage.
