### ISSUE TITLE
Provide ability to modify status of Completed-Permit Issued applications

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4840]
Currently RPP staff cannot modify the status of applications with Completed-Permit issued status.
Provide RPP staff the ability to update the status of RPP applications that have status Completed-Permit Issued.

**Comment by johnclary** [comment]
Remove these rules: https://builder.knack.com/atd/parking#pages/scene_36/rules

And add modified by/modified date rules here: https://builder.knack.com/atd/parking#pages/scene_36/views/view_95

**Comment by ChrispinP** [comment]
Modified rules are in place:
![image](https://user-images.githubusercontent.com/67915167/103811858-377dc980-5023-11eb-9960-cfd32e5c8602.png)

Also updated Application Status field order to replicate workflow so completed status is not at the top.

Removed page rules that limit the ability to change status if set to 'Completed' status.

Marking this as complete.

@moorerst Can you create a new issue for 'create application status buttons' feature that we can build for version 2. Thanks

**Comment by johnclary** [comment]
Thanks @ChrispinP !!
