### ISSUE TITLE
Add Official Disclaimer to RPP Portal

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4842]
Customers are concerned/confused that the site is hosted at knack.com. 
Todo: consider putting a disclaimer on the City website that explains that Knack is an authorized vendor. 
We can also evaluate what it would take to embed the app on an official city web page. Something like parking.mobility.austin.gov. or data.mobility.austin.gov

**Comment by dianamartin** [comment]
Banner like this: 
![image](https://user-images.githubusercontent.com/21112975/103825679-ea0d5680-503a-11eb-8c4e-f818a4adff92.png)

"An official website of the City of Austin"

**Comment by dianamartin** [comment]
I tested a few things, simply putting rich text and header separator, updating banner logo. 

![image](https://user-images.githubusercontent.com/21112975/103831572-f77a0f00-5041-11eb-8325-51705e336f41.png)

**Comment by dianamartin** [comment]
I updated the RPP banner and will reupload to site.

![image](https://user-images.githubusercontent.com/21112975/103832479-fba72c00-5043-11eb-9f61-f4ce6c4c8c75.png)
