### ISSUE TITLE
Create new Non Payment status for RPP applications

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4843]
Need new status for RPP applications that can be used when there is no charge for permits being issued. 
Must provide a comment to detail why permits are being issued with no payment. There is concern that is it well documented why permits were issued at no cost.

**Comment by ChrispinP** [comment]
@moorerst I forget, was it preferred the status be 'No Charge' or 'Exempt' ?

We can add this status to the Payment Type field and we could use Payment Notes for the area where it is documented.

**Comment by moorerst** [comment]
@ChrispinP let's go with Exempt

**Comment by ChrispinP** [comment]
Added 'Exempt' as a Payment Type and added a note to provide reasoning in Payment Notes section.

complete
