### ISSUE TITLE
Create a query for RPP applications in Completed-Permits issued status

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4846]
RPP staff provides management a weekly count of online applications with Completed-Permits Issued status.
They need a easy way to query that count.
Number of online applications with "Completed - Permits Issued" status for the certain period of time?

**Comment by ChrispinP** [comment]
Can create a report that shows the record count of applications in Completed status over the previous week. Attempting to also add a monthly count for each zone. In progress.

**Comment by moorerst** [comment]
@ChrispinP is this ready for review in the reports meeting?

**Comment by ChrispinP** [comment]
Was able to create multiple report types that filter out any applications not in the completed status.

1)Completed Applications by Type
2)Completed Applications by Payment Type
3)Completed Applications by Permit Count
4)Completed Applications by Applicant Type
5)Completed Applications Cost Estimates
6)Average Cost Estimate per Completed Application
7)Total Permits Requested for Completed Applications

Additionally (once new fields Payment Location and Transaction Amount are added)
8)Completed Applications by Payment Location
9)Completed Applications Transaction Amount
10)Average Transaction Amount per Completed Application

All of these reports are additionally filtered by zone, year, quarters, and months with some featuring corresponding pie charts.

Ready for review

**Comment by moorerst** [comment]
@ChrispinP when will this be moved to production?

**Comment by ChrispinP** [comment]
These 6 reports have been pushed to production with their filters for all zones and each zone individually.

Active Permits by Type
Total Permits by Type
Completed Applications by District
Completed Applications by Application Type
Completed Applications by Payment Type
Completed Applications by Transaction Amount

Pending review and maintenance assessment will determine if more work needs to be done or this will be it until we implement a more robust reporting tool.

**Comment by ChrispinP** [comment]
will create a new issue if any of the other reports or filters are requested to be built later on.

Steph has reviewed the current reports and there are no further issues, closing
