### ISSUE TITLE
Getting error Employee ID already being used

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#4849]
Linda E was attempting to enter New Employee James E with Employee ID 10061922
When she submitted received error Employee ID must be unique "10061922" is already being used

I searched James E - no result
I searched Evans - 1 result not James
I searched employee list for 10061922 - no result

**Comment by SurbhiBakshi** [comment]
Hi @moorerst - James was marked as Inactive and so did not show up in the table. He should show up now.

**Comment by SurbhiBakshi** [comment]
@moorerst - The table has a filter to show only employees who are marked Active in their User Status. Wondering if the filter should be removed?

**Comment by dianamartin** [comment]
Or we can have them be listed by name and "- status" at the end so the person knows what their status is?

**Comment by SurbhiBakshi** [comment]
Was thinking about including a field for User Status in that table, so the filter for the table would include that.

**Comment by moorerst** [comment]
@SurbhiBakshi I like the idea of including the User Status field to the table but if only Active employees are being displayed we still would not see Inactive employees. Is that correct?

**Comment by dianamartin** [comment]
@moorerst I think Surbhi is suggesting showing both statuses, Active and Inactive to the HR user

**Comment by moorerst** [comment]
Awesome Thanks

**Comment by SurbhiBakshi** [comment]
- [ ] Add User Status field to the Employees (Accounts) table.
- [ ] Remove the User Status is Active filter from the Data Source for the table.

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6f0a398a-b34f-4cb0-b14b-086af636ea4c)

**Comment by SurbhiBakshi** [comment]
Hi @moorerst - I added the User Status field to the table on the Employees page and removed the filter on the back end restricting the table to only showing Active status accounts. 
The table now shows all  Inactive and Active accounts. Looks like some of the Inactive accounts might need to be reviewed. Two records are missing a name. 

Linda can use the Filter at the top of the table to filter by User Status now if needed. 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/2f5e99e5-7583-4261-bbfa-0f23766b77c3)

**Comment by moorerst** [comment]
@SurbhiBakshi Thanks I will fill in the name of the two blank inactive employee based on the email address on the record.
Complete

**Comment by moorerst** [comment]
this is complete closing this issue
