### ISSUE TITLE
Implement ability to soft-delete projects

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4867]
- [x] Add [more-horizontal](https://feathericons.com/?query=more-horizontal) Feather icon to the upper right of the "Project summary" page 
- [x] Clicking icon opens a [simple menu](https://material-ui.com/components/menus/#simple-menu) with the following menu items
- Share [disabled]
- Add to favorites [disabled]
- Rename
- Delete 

- [x] When user clicks on "Delete," modal opens: 
> Deleting this project will make it inaccessible to Moped users and only available to administrators. Users may request a deleted project be restored by [opening a support ticket](https://atd.knack.com/dts#new-service-request/).
>
>[DELETE]

**Notes**
- Projects will still be visible at their original URL
- Separate issue: Implementing a "This project has been deleted" banner for deleted projects.

**Comment by zappfyllc** [comment]
@amenity I just saw this perusing the backlog but `archived` refers to deleting a project (but not really deleting it), while `canceled` refers to a project that may have been stopped at any point for a specific reason (vs. just deleting the project)

**Comment by amenity** [comment]
@zappfyllc - that's my understanding as well. So the intention of this issue was to create an interface for users to archive projects. 

Are you suggesting that this is the pattern we'd want for cancelling projects, so we should handle archiving a different way? Maybe it actually looks like a "Delete" button and we have a "Deleted" project page visible to admins only?

**Comment by zappfyllc** [comment]
@amenity I think what you have is great (I wasn’t actually suggesting anything, just clarifying) but I do think your last question makes sense to me: a “Delete” button instead of “Archived” and then handle restoring projects that were accidentally deleted by admins only. I’ll let the devs weigh in on whether an archived/deleted project should be a Boolean value in the project table or another status in `moped_status`.

For cancelling, suspending, or otherwise changing the status of a project, I think we can come up with a different experience TBD. Still thinking on that and very open to ideas.

**Comment by johnclary** [comment]
Sounds good, but questioning whether we need to add "restore" functionality. My assumption is that "deletions" will be rare and the need to restore will be even rarer. I suggest we always exclude `archived` (aka "deleted") projects from any view in Moped and not worry about accommodating them with filters. If a user wants to restore a project they will need to ask us for help—and we could communicate that in a confirmation dialogue when they hit `Archive` button.

**Comment by johnclary** [comment]
Also, I just remembered that we use a status called `Void` in the Data Tracker for this same purpose, which I think is clearer than both "Archived" and "Deleted"

**Comment by amenity** [comment]
>An alternative approach for "undoing" a deletion: Github allows you to delete branches from a repository with one click, but presents the option to undo the deletion until you navigate away from the page.
Yup, I really like this pattern — discussed it with Sergio [here](https://austininnovation.slack.com/archives/CHZE6BC6L/p1612136944078800). 

Updating the issue description to simplify (no restore, no visibility at all once archived/deleted/voided)... @johnclary - how is "void" handled from a UI perspective? Just a "VOID" button? I like "delete" better.

**Comment by amenity** [comment]
@amenity @johnclary - please update this issue description to reflect Slack discussion

**Comment by tillyw** [comment]
Suggested language for deleting project modal: Deleting this project will make it inaccessible to Moped users and only available to administrators. Users may request a deleted project be restored by [opening a support ticket](https://atd.knack.com/dts#new-service-request/).

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/248
