### ISSUE TITLE
Project Staffing | Render Project Team table on Project page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4876]
Essentially the table on the _Assign team_ page, but not editable, no field names or help text. (Will have to coordinate with how it goes into editing mode as we do #4752.)
<img width="963" alt="Screen Shot 2021-01-08 at 3 16 19 AM" src="https://user-images.githubusercontent.com/1463708/103997197-63eb3000-5160-11eb-953c-2237a602d6f1.png">

Eventually we will want to include avatars next to the names. Does that make #4798 or #4809 a blocker for this, or will it just Rob-up the table if we do it now?

**Comment by zappfyllc** [comment]
Ideally #4400 should be considered in this implementation. #4400 was not needed for new projects because the project doesn't get saved until the user gets through mapping and clicks "Finish" but it is necessary to consider for any future edits of a project team

**Comment by amenity** [comment]
@mddilley @zappfyllc - this has been covered and be closed, yes?

**Comment by mddilley** [comment]
@amenity yep, thanks for the reminder! It closed with https://github.com/cityofaustin/atd-moped/pull/218. I'll close this one and add a note about the avatars in this table in https://github.com/cityofaustin/atd-moped/pull/218.
