### ISSUE TITLE
Project Activity Feed | Evaluate backend data storage options 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4894]
The main objective of this issue is to determine what is the best way to store the activity logs. There are a few technologies to explore:

Infrastructure:
- [x] Google Pub/Sub
- [x] AWS Lambda + SQS
- [x] AWS Lambda + Dynamo + Streams
Database Storage:
- [x] DynamoDB
- [x] AWS Keyspaces for Cassandra
- [x] PostgreSQL

**Comment by sergiogcx** [comment]
I finished investigating Google Pub/Sub. It's very promising, but we cannot connect Hasura directly to it. There needs to be an intermediary API, and that is a bit wasteful. Not to mention we are adding two or more layers of additional DevOps we do not really need. For now, it's not really worth considering.

DynamoDB and Streams sounds like a great alternative; however, it is going to take time to design the table in Dynamo in a way we can query data back efficiently. This also is not really what we need at the moment.

Cassandra is very promising too, it is easy to design and query for, it is price-friendly and it can store very large volumes of data. In the future, I would definitely argue in favor of using this as or activity log, once we have lots of data. The only problem I foresee, is additional cost and complexity of our AWS stack. Still an option on the table on a moment's notice,
 
Given our constraints and conditions, I think best of reusing our VisionZero code and implement a Lambda function with SQS and insert back into PostgreSQL. Once we have a lot of activity, we can always switch to Cassandra for better storage capacity & optimize performance.

**Comment by amenity** [comment]
Sounds good. Thanks for the thorough, speedy research, @sergiogcx. 🙏
