### ISSUE TITLE
Project Activity Feed | Implement backend data storage solution

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4895]
Based on our learnings [from the spike in this issue](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/4894), we need to begin implementation of our activity log. 

Database:
- [x] Implement PostgreSQL activity log table(s)

API Infrastructure:
- [ ] Disable the Cognito validator in favor of software-based validation (already in place).
- [ ] Implement event handler in API
- [ ] Configure event generator in Hasura

SQS Infrastructure:
- [ ] Create SQS Deployment Pipeline from VisionZero
- [ ] Re-use code from VisionZero for SQS and data events.

**Comment by zappfyllc** [comment]
Mostly DevOps work; already merged
