### ISSUE TITLE
Adjust HTML validation settings on Signs "attachments" layer

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4897]
One of our Knack ETLs is choking because staff are using `<` and `>` characters in text fields. AGOL is flagging these as "invalid HTML content."

Accoring to [this article](https://enterprise.arcgis.com/en/server/latest/publish-services/windows/feature-services-and-client-applications.htm#ESRI_SECTION1_CE856452327D42ED95044D9EC32E4598) it should be possible to disable the "Filter HTML content"setting the feature service.

To test this, let's disable the html filter on the `attachments` layer. If this can be set for a specific column, the column in question is `ATTACHMENT_DESCRIPTION`.

**Comment by johnclary** [comment]
@jaime-mckeown would you mind looking into this? One thing—I have recently modified this service's schema directly on AGOL by adding a few column. I believe you're able to reference the most recent service definition from AGOL, rather than any version you might have that was originally used to publish the layer, correct? I just don't want my changes to be overwritten.

If you need to delete data, that's no problem.

**Comment by jaime-mckeown** [comment]
@johnclary The article refers to Server to modify the feature service, so it's referring to feature services that are hosted through ArcGIS Server. Our feature service is hosted, and I don't see any options to change this...

**Comment by johnclary** [comment]
Boo—thanks for checking. Would you mind opening an Esri ticket for this? _Usually_ most of the ArcGIS server configuration options exist in AGOL somewhere, and I feel like this html content problem must be a common issue for other people.

**Comment by johnclary** [comment]
R.e. the attachments layer—we don't actually attach any files; we just link to the file in Knack.

**Comment by jaime-mckeown** [comment]
I'll ask the CTM AGOL Administrators first in case they are familiar before dealing with Esri.

**Comment by jaime-mckeown** [comment]
Submitted a CTM Help Desk Ticket to see if COA AGOL Administrators can help. If not, I will submit a ticket to Esri.

**Comment by johnclary** [comment]
thanks!

**Comment by jaime-mckeown** [comment]
Filtering HTML content on hosted feature services is not an option under the COA Organization Admin account. Submitting ticket directly to Esri.

**Comment by jaime-mckeown** [comment]
Submitted ticket to Esri - https://my.esri.com/#/support/cases/02716319

**Comment by jaime-mckeown** [comment]
@johnclary please see below for Esri response regarding this request, not good news:

```
Hi Jaime,

This is Chryse from Esri Premium Support following up on a case you had with Asraf that was then converted to a Premium case. After doing some research and speaking with colleagues, Asraf and I have both found that unfortunately this functionality is only available in ArcGIS Enterprise and not ArcGIS Online. 

In ArcGIS Enterprise, filter web content prevents input of unsupported HTML entities or attributes. This option is enabled by default and, unless your editors require the ability to input these unsupported HTML entities, do not disable Filter web content. Disabling this option allows a user to enter any text into the input fields, which exposes the service to potential cross-site scripting (XSS) attacks. Though, at this point this is not available in ArcGIS Online.

Please let me know if you have any additional questions or would prefer to discuss this on the phone. If you'd like to close out the case, I can go ahead and do that as well. We apologize for the inconvience.

Thank you,
Chryse
Esri Premium Support Services
```
