### ISSUE TITLE
MetroBike GIS Data Request

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#4902]
This request came in from Nelson/Nygard, CapMetro's consultant for expanding MetroBike, regarding micromobility data. It would be used for the purpose of planning the expansion:

> "[We] would like to gain access to several aggregated outputs from your MDS Provider feed. I am not sure if you are ingesting the Provider API directly or if Ride Report provides that service for you. At any rate, we would like average daily trip start density, average daily trip end density, and average daily deployment density (deployment defined as any non-operational status to available status). 
> 
> We are using a 1/16 sq. mile hex grid. Our data analyst can coordinate with you on the base hex grid. In terms of timeframe, we would love for one month pre-pandemic (preferably September 2019) and a representative month during the pandemic after ridership stabilized slightly (June 2020?)."

**Comment by johnclary** [comment]
Backlogging pending converstaion with parking folks.
