### ISSUE TITLE
Discuss removal of Sector and Location Type from location for Viewer table

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#4905]
Separate APD Sector from the concatenated location. This could help with filtering the assignments by location when MMC wants to see who is in the vicinity.

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/105e31ec-c512-476c-9b7a-09221d38d232)

**Comment by amenity** [comment]
@SurbhiBakshi I like that idea! Can we provide them a link to a map of the sectors, too?

**Comment by SurbhiBakshi** [comment]
Notes - 
- [ ] Remove Vision Zero Location (concatenated field)
- [ ] Add APD Sector
- [ ] Add Location
- [ ] Create AGOL Map with APD Sectors
- [ ] Add link to the map on the Viewer page
- [ ] Ask Jaime to take ownership of map and share it publicly so a login in not required to access the map. The feature class for APD Sectors does not require a login.
