### ISSUE TITLE
Project Extent | Edit project extent 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4906]
As a project team member, I want to edit the extent of my project so that everyone can see its most location.

**Comment by amenity** [comment]
@sergiogcx suggested we might use[ Full Screen Dialog](https://material-ui.com/components/dialogs/#full-screen-dialogs) here. 😃

**Comment by zappfyllc** [comment]
@amenity provide feedback on [open PR above](https://github.com/cityofaustin/atd-moped/pull/190)
