### ISSUE TITLE
Small updates to restored notes UI

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4910]
It looks great, just a couple tweaks: 

- [x] Rename two note types to "Safety Concern" and "Inactivity Explanation"
- [x] Update the note field label from "Notes" to "Note"
- [x] Extend the first bullet in the help text: 
> "Safety concerns, e.g. "pedestrians crossing without crosswalk Cesar Chavez between Comal and Chicon", "low visibility around corner at 12th and MLK", etc. **Please remember to include the location in your note.** "

**Comment by SurbhiBakshi** [comment]
@amenity - Should there be something that talks about creating a note every 15 min to explain Inactivity?

**Comment by amenity** [comment]
Yes, good catch. I can re-word it later this eve.

**Comment by amenity** [comment]
- Safety concerns, e.g. "pedestrians crossing without crosswalk Cesar Chavez between Comal and Chicon", "low visibility around corner at 12th and MLK", etc. Please remember to include the location in your note. 
- Periods over 15 minutes with no warnings or citations issued, e.g. "Took 90 minutes to perform arrest," or "patrol vehicle computer malfunctioning."

**Comment by SurbhiBakshi** [comment]
@amenity - thanks, made the change.

**Comment by amenity** [comment]
Looks good, @SurbhiBakshi 🙏
