### ISSUE TITLE
Project Staffing | Edit project team

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#4913]
As a user, I want to edit the project team associated with the project I'm viewing so that I can add/remove team members.

Could use the same inline editing with Material Table that Mateo looked at for Project Phases. 

**Details:**
- #4949 Activity feed will capture the history of changes for project team (role changes, staff removals, staff additions, name changes, etc.)

**Comment by amenity** [comment]
Assign Team was implemented in the demo-for-Rob rush and still needs some work, see #4974

**Comment by mddilley** [comment]
This issue needs one last PR to update the mutations to let the activity feed do its magic.
