### ISSUE TITLE
Assisting with AGOL Cleanup

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#4915]
Diana will be helping out with the AGOL Cleanup since much of the content has been around for quite some time.

**Comment by dianamartin** [comment]
I started by reviewing the AGOL Status Dashboard, but realized I don't have rights to it. I'll be reviewing the content in my own personal AGOL account (non-federated) one.

**Comment by dianamartin** [comment]
Need to move data set ownership over to ATD Publisher that were tagged on my spreadsheet to keep

**Comment by dianamartin** [comment]
@jaime-mckeown I moved the following layers to ATD_Publisher

- `COA Fuel Center Locations` - in 0_Departmental
- `COA Fuel Locations`- in 0_Departmental
- `Banner Notes` - in SM_BANNERS
- `Banner Program - web applications`- in SM_BANNERS
- `Banner Program Analysis map - AE Utility Poles`- in SM_BANNERS
- `Overhead Sign Maintenance Tracking Web Map` - in SM_Signs_Markings folder
- `Overhead_Sign_Maintenance` - in SM_Signs_Markings folder
- `Overhead_Sign_Maintenance` - in SM_Signs_Markings folder
- `Maintenance Areas - FILL` - moved to Susanne, per Christina's suggestion
