### ISSUE TITLE
Make Past Assignments table the same format as Invoicing table

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#4922]
For the Past Assignments table that the officers will look at - change the format to be similar to what Randy sees on the Invoicing page, limited to that officer's assignments. That way, if the officer needs to call Randy, they will be looking at similar tables, and it also easier to read.

**Comment by SurbhiBakshi** [comment]
Replace 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/54c9d0b8-d173-46cd-9bde-a823781fa62e)



with 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/1145dffe-48ca-4783-bcc7-f557e84e12d4)

**Comment by amenity** [comment]
I like this idea, @SurbhiBaksh! We will need dev help to implement, right?
