### ISSUE TITLE
Bug: Customer gets 2 system emails requesting TIA MOD submission

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4924]
I didn't document the steps to produce this error 😫

**Comment by ChrispinP** [comment]
I have a hunch this was caused by the request submission button. When the Fee status is updated to yes, it will automatically send a submission request email for the entire TIA Packet. Therefore the request submission button would only be used for follow up submissions.

**Comment by TracyLinder** [comment]
Will circle back to emails on #4768. Closing.
