### ISSUE TITLE
Enhancement: New TIA Details fields to capture people info

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4930]
### As a TIA reviewer, I need to capture various information related to the customer/applicant. 

**New Fields:**
-  Requestor Company Name
- Sealing Engineer Name
- Sealing Engineer Company Name

1. Add these fields to the TIA Request Details page
2. Add these fields to the portal application

**Comment by ChrispinP** [comment]
Added 3 fields to the request object, the tia request application, the edit request page, and the tia request details page.

Will these fields need to be required? Ready for review.

**Comment by ChrispinP** [comment]
no further action, closing
