### ISSUE TITLE
Possible Feature: Ability to manually create a TIA Submission

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4933]
### Allow the TIA Reviewer to manually create TIA Submissions
- Button name: + Submission
- Button Location: Top of Page

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/b89996e4-9097-43f7-8c68-ab91400c4df7)

**Comment by TracyLinder** [comment]
Feedback: This would be useful especially for creating records/cases where there is already a submittal.

**Comment by ChrispinP** [comment]
New Submission button added with the ability to create a new submission, see existing request comments and attachments, and add new ones.

**Comment by ChrispinP** [comment]
need to review

**Comment by TracyLinder** [comment]
looks good; closing
