### ISSUE TITLE
Meet to discuss expanded contractor tracking needs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4935]

**Comment by amenity** [comment]
@dianamartin please schedule :)

**Comment by dianamartin** [comment]
@amenity Scheduled on 1/22, invitation sent out

**Comment by amenity** [comment]
Thanks, D!

**Comment by dianamartin** [comment]
## Notes
- Talking to Christina and Amenity this morning

Markings maintenance contractor work orders - super simple work
one intersection, one roadway (a couple of hours), 

**ATSD Work is complex**
(work done over the course of days, weeks) so not as straight forward

- They want to separate out the work order daily

## To Do 
- Remove "Date Worked"
- Reformat "Materials Used" 
  - did this on contractor side
  - need to do on Contractors
- Attachments need to have "plans" type
- Add Comments (edit only) - SMB and Contractor
- Adding prototype work order (ATSD example of multi-day, multi-week w/Christina)
- Adding "Corrected Date" - Contractor side to inspection table/form

**Comment by amenity** [comment]
Active Transportation work orders are different from others — work is more extensive and complex; spans several days

- Request: separate each day's work into its own ticket, can be children of the work order

  - Will submit a ticket every single day; Tooran will have to look at tickets for invoicing instead of the overall work order
  - Concern: Inspections live on parent; will have to move to child
  - Unneccessarily complex; having child tickets on all work orders will be overkill
  - Up to 30 tickets per work order...

  

- Alternative: Add a comments field to the "Date Worked" log in each work order

- Alternative: "Resume later" (?) button on the WO page that allows them to duplicate the ticket so there is a new one open with all the same information 



Next steps:

Would like users to start using the existing feature we've built for them before requesting enhancements

- Amenity schedule meeting for 1st week of February Need to talk to Tooran and Joe Michael
- Diana can will implement changes to demo for discussion 
  - Extend file-upload attachments to include plans
  - Get rid of "Dates Worked" and "Materials Used" so that section functions more like a work log section
  - Add a "Correction Date" to track when contractor resolved a particular issue
