### ISSUE TITLE
Meet with AMD for Review and Prioritization 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#494]
### Attendees
*AMD: Jen, Billy, Brian VDW, Jonathan*
*DTS: Diana, Amenity, John*

### Resources
[Doc](https://docs.google.com/document/d/1DN4RNQJ2ihtQV5LalRKC-9_PU_LJX_zBR6cHuL7q8oo/edit#heading=h.b9jbavfk3tz7)

**Comment by amenity** [comment]
**Mobile Signals**
- DTS will train Roman, Gene, and Toby to kick off pilot for next week
- Concerns about "Nearest Signal" detection in Fulcrum
  - Sometimes the signals are too close to eachother and technicians don't catch it
  - Sometimes technicians forget to get it in the field and can't do it afterwards
  - DTS

**MPD**
- Augmented staff Andres will begin working with Nathan to put AMD data into Access database, give intro to interested AMD stakeholders
- AMD has major need to see comprehensive, department-wide list of upcoming projects including timelines, detailed plans (materials, asset types, timelines, etc.)
  - Signal Techs work for every division. Recurring issues with communication: Requesting work without sufficient notice, AMD goes out and begins work only to find out that there are hold-ups. No holistic overview of what is needed and when it's needed; dependencies with materials installed in the field what's available in the warehouse

**Traffic Counts**
- Might be a conversation about expanding the count program



**Detection**
- Doing away with NextPhase



**Bug fixes**
- Brian is getting what he needs from detection log - exports CSV and runs filters for fixed and duplicates
- Can't customize data range for pie chart on 


**TODO:** 
- Find Github issue for Airwatch tablet issues and figure out what's wrong- @dian 
- Add enhancement request "Signal detector status chart" - can't customize data range for pie chart on exports CSV and runs filters for fixed and duplicates
  - We need to keep a log of when signal changes from broken to repaired, not individual detectors
- Billy will give example of issues with Preventative Maintenance -
  -  to see example look at map and search for ones with 2016



**Prioritization**
- VZA is important, and Jen manages money so it is an AMD 
- SIgnal Mods and Upgrades (Issue 124) will really help internal organization, lots of people involved...Yes requires scoping, but might be ways to build off of what is there?
  - Might just be a training session for Diana to show everyone all together how to do this
- ROW activity would be great, but not as high a priority
  - Maybe ops-map is all we need, just more data
  - If you could add unassigned it would be cool (but it's public facing)
- Intro meeting with Brian and Jen on the two needs scoping

**Comment by amenity** [comment]
@dianamartin @johnclary - please feel free to add/correct directly in my comment/notes. ☝️

**Comment by johnclary** [comment]
added mine to yours. thanks @amenity

**Comment by dianamartin** [comment]
I made changes yesterday. Should we create new issues for the meetings we should have?

**Comment by amenity** [comment]
@dianamartin - yes please!
