### ISSUE TITLE
Get a Microstrategy account 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4941]
Ask Scott; will have to be someone who has a PC or get Citrix
If we have a VM we could have full control of w/ credentials, that would be useful long term.

**Comment by amenity** [comment]
@johnclary - Does [this](https://github.com/cityofaustin/atd-data-tech/issues/4812#issuecomment-763861375) mean that we have what we need? cc/ @mateoclarke

**Comment by johnclary** [comment]
We have an account to access the Microstrategy database. If we want to use the UI as Brian L. suggested then we'll need to do this. With the limited read-only integration we're targeting right now I don't think this is necessary.

**Comment by johnclary** [comment]
We have this
