### ISSUE TITLE
Research: AMANDA V7 Communication Tracking Solutions (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#4945]
Ryan M. would like to explore any available AMANDA features that enable users to email/communicate with folder applicants from the permit folder as a possible solution for some of the permitting metrics deliverables. We may be able to use timestamps on these communications as part of the reporting. 

- "As a ROW Permit Analyst, I want AMANDA to capture the date/time that a permit applicant sends me an email w/ responsive information."

**Explore AMANDA & other possible solutions for this need.**

**Comment by TracyLinder** [comment]
Need: Merging various email threads, finding all related communications in one place.

**Comment by TracyLinder** [comment]
@Nadin-Nader will begin researching possible AMANDA solutions. Let's aim to discuss research findings during the sprint that begins 4/7/21.

**Comment by Nadin-Nader** [comment]
Spoke to Amita and she informed me that there is a V7 features that enables users to email/communicate with folder applicants. She mentioned that it was like an Informal update attempt that sends a trigger to send an email. That email is copied and saved in AMANDA V7 and can be queried.
She did not have much more on this and asked me to talk to Gita as she knows more about it. I sent Gita an email asking her to elaborate.

> From: Nader, Nadin 
> Sent: Tuesday, March 30, 2021 12:34 PM
> To: Rajagopalan, Gita <Gita.Rajagopalan@austintexas.gov>
> Subject: AMANDA V7 Communication with Users Tracking Solution
> 
> Hi Gita,
> 
> Hope you are doing well. I was wondering if you could help me with a request I received from one of our stakeholders? He was testing V7 and was thinking about some of the permitting metrics deliverables. He was wondering if there were any available AMANDA V7 features that enable users to email/communicate with folder applicants from the permit folder? They would like to use the timestamp on these communications as a part of the reporting.
> 
> I spoke to Amita and she mentioned that V7 has some type of informal update attempt that can be added that triggers an email to be sent. It was also mentioned that a copy of that email is stored in AMANDA to possibly be queried. Can you possibly elaborate on this, please?  or Point me in the right direction.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services


## **Status:**
Waiting on Gita's response

**Comment by Nadin-Nader** [comment]
Email from Gita said that this can be done. See below:

> There are a triggering events that emails can be sent out using code for sure. 
> I suggest you set up time with Amita, Jenice and George once you get details about requirements from this stake holder. 
> They may be aware of some newer ways of sending emails from 7

Next step is to gather all of the Acceptance criteria then set up time with Amita, Jenice and George to see how to work on this and who will be working on this.

**Comment by Nadin-Nader** [comment]
## **Next Step:**

Schedule Time with Ryan

**Comment by Nadin-Nader** [comment]
Meeting Scheduled for 4/12/21 @ 1030am

**Comment by Nadin-Nader** [comment]
This is going to have to wait until we have the ROW AMANDA Permitting Metrics Meeting (#5734) with Ryan on 4/14/21.

**Comment by TracyLinder** [comment]
Closing this util a need for more research is identified.
