### ISSUE TITLE
Project Activity Feed | Implement front end in Activity Log tab

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#4949]
The most basic table; whatever is simplest to implement.

**Comment by sergiogcx** [comment]
Let's make it look like this:
https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/4614

**Comment by amenity** [comment]
Not in my Balsamiq wireframe and can be a future enhancement, but I would like it to show users' avatars [like this](https://confluence.atlassian.com/doc/page-history-and-page-comparison-views-139379.html).

**Comment by sergiogcx** [comment]
@amenity It would be a really easy thing to do if we already had a column in the users table for an avatar picture. I don't see one at the moment in the docs: https://db-docs.austinmobility.io/atd-moped-staging/tables/moped_users.html

To make it work fully, we are going to need to let users upload files, storing files securely and storing the links of the files to the database. Alternatively, we can store the pictures of the users directly in the database, but that idea gives me a heartburn.

For now, we can create a column that is always null, allowing us to put for now a generic avatar in the mean time, and whenever we have to cross the file-upload bridge, we can make that update.

**Comment by sergiogcx** [comment]
Notes to self:
- What does a minimal working version of the Activity log look like?
- What is missing in the activity log at the moment?
- What are the different case-scenarios we need to anticipate right-away?
- How does the framework scale/grow? What patterns would make it easy to work on it?
- Does it need more demo data right-away?

**Comment by sergiogcx** [comment]
These are by the way all the tables being tracked for changes, it should be very easy to add more as we need to add them:

```
activity_log_moped_proj_categories
activity_log_moped_proj_components
activity_log_moped_proj_dates
activity_log_moped_project
activity_log_moped_proj_entities
activity_log_moped_proj_financials
activity_log_moped_proj_fiscal_years
activity_log_moped_proj_fund_opp
activity_log_moped_proj_fund_source
activity_log_moped_proj_groups
activity_log_moped_proj_location
activity_log_moped_proj_milestones
activity_log_moped_proj_notes
activity_log_moped_proj_partners
activity_log_moped_proj_personnel
activity_log_moped_proj_phases
activity_log_moped_proj_sponsors
activity_log_moped_proj_status_history
activity_log_moped_proj_status_notes
activity_log_moped_proj_timeline
```

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/201
