### ISSUE TITLE
Migrate Knack Detectors publishing to new ETL

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4961]
Migrate the detectors ETL to the new Knack ETL. This data is published to both AGOL and Socrata.

- [Legacy script config](https://github.com/cityofaustin/atd-data-publishing/blob/24c4fbad9d4fc06085fe8254e4584092f8c2746a/transportation-data-publishing/config/knack/config.py#L113)
- [Source Knack View](https://builder.knack.com/atd/amd#pages/scene_468/views/view_1333)
- The process is called `detectors_agol` and `detectors_socrata` in the [atd-data-deploy config](https://github.com/cityofaustin/atd-data-deploy/blob/production/config/scripts.yml#L75).

The legacy config for this one is a lil different than the norm, but the location ID field is the same as the other asset datasets you've worked on @chiaberry: `field_182`.

**Comment by chiaberry** [comment]
The Location data type in socrata is "location" I am deleting the column and adding a location column "point"
