### ISSUE TITLE
Configure Robin Single Sign-On

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4969]
![Screen Shot 2021-01-15 at 1.56.08 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/03965cac-12e3-4c08-9bff-7a8766eb73c8)

**Comment by johnclary** [comment]
Waiting for documentation from Alisha. Unclear if we will need to setup a SAML integration or if the O365 calendar integration will take care of this as well.

**Comment by johnclary** [comment]
FYI @moorerst

**Comment by dianamartin** [comment]
I just tested this out, it was pretty smooth. Had to wait a bit, but it didn't have me enter credentials in at all.

**Comment by dianamartin** [comment]
@moorerst I believe this has been done, will close this.
