### ISSUE TITLE
Create & share job posting

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#4981]
- [x] Update [this doc](https://docs.google.com/document/d/1KsuRBsV3YojlVYZlfRljwp0dj0Tlmjm5FsOpSJ08Gwk/edit#)
- [x] Screenshots of VZV and VZE?
- [x] Post on Medium
- [ ] Shareeee

**Comment by johnclary** [comment]
@amenity I'd like to get this job posting done this week. Would you start a draft?

**Comment by amenity** [comment]
@johnclary doc is ready for review. And here are some pix:
![Bike-to-Cameron](https://user-images.githubusercontent.com/1463708/111581208-d727a880-8786-11eb-9827-8fc47e1aadb3.JPG)
<img width="1440" alt="VZE" src="https://user-images.githubusercontent.com/1463708/111581217-d8f16c00-8786-11eb-9dc8-0b4ce7a152ac.png">
<img width="1439" alt="VZV" src="https://user-images.githubusercontent.com/1463708/111581218-da229900-8786-11eb-9c0d-eb7a60a318c1.png">

**Comment by amenity** [comment]
https://atd-dts.medium.com/job-product-manager-austin-transportation-data-technology-services-103650396d7 🎉

**Comment by amenity** [comment]
Just realized I should add this to the Public Interest Tech Job Board...

**Comment by amenity** [comment]
Slack: 
- [x] City of Austin - #general
- [x] Municipal Design - #jobs
- [x] Civic Union - #loc-atx
- [ ] Open Austin - @mateoclarke, can you do this one, please?

Other
- [x] Posted on Austin Digital Jobs FB
- [x] Submitted to https://jobs.codeforamerica.org/


Am I missing any, @mateoclarke @johnclary?

**Comment by amenity** [comment]
Boo... Just got this message from CfA:
>Thank you for posting on the Code for America Public Interest Tech Job Board. This is a notice that the site will be down for [some much overdue] system maintenance and migration 3/24-5/1. All functionality will be down during this time and we therefore will not be posting your recently added job. Thank you for your patience and understanding as we perform the necessary work to continue to provide this free service.

**Comment by johnclary** [comment]
We hired Patrick.
