### ISSUE TITLE
[BUG] Fulcrum app - Unable to Edit Signal After Nearby Signals Found

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#499]
Billy Bolander
AMD

Billy called me this morning, trying to figure out why Toby's tablet wasn't able to select other signals while back at the shop (Cameron).

**Comment by dianamartin** [comment]
@johnclary Troubleshooting iOS phone v. Android tablet

I logged into Fulcrum website (just incase). Also have Fulcrum on my iOS phone so I was able to troubleshoot with him on the phone on it. He was saying that Toby couldn't select any signals from his android device. I was able to log into the technician account of my phone and change the record's signal record. 

I also tested on my own personal Samsung Android 8" tablet (older version). I downloaded Fulcrum, logged in as technician and attempted to change the already created PM record. My location services were turned on however, I was getting an error message when I was in the `signal` field. No signals populated like on the iOS device. I was unable to type in a signal ID, no results would populate when searching. 

This is when I thought it might be a hardware issue. I think further testing is needed.

**Comment by dianamartin** [comment]
This is what I found from Fulcrum on their [release notes](https://www.fulcrumapp.com/releases/#ios)

**Comment by johnclary** [comment]
@dianamartin thanks for testing. We have custom JS (called a "data event") that populates that field. We will probably need to modify it. I'll probably loop in @mddilley or @mateoclarke to take a look.

**Comment by dianamartin** [comment]
thanks for having them take a look. Billy said that this is happening daily to all technicians, it's a big problem for them.

**Comment by johnclary** [comment]
ok, i've got it fixed. need to set up version control + docs for this and then will migrate to the prod app.

**Comment by dianamartin** [comment]
Let me know when it gets to Production so I can test it out before letting Billy know

**Comment by johnclary** [comment]
@dianamartin this has been pushed to production. There is now a "clear selected signal" button that clears out the signal value, and populates the choice list with all signals. This should resolve the issue. Let me know what you hear from Billy. Thanks!

**Comment by johnclary** [comment]
screenshot :)

![thumbnail_image1.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/1a5549c3-c5ad-4bc6-84f6-ff40a300e9a7)

**Comment by dianamartin** [comment]
@johnclary I don't think this issue is fixed. I just tested it on the tablet that I have and it continues to not be able to find any signals when I create a new record. Or if I try to edit an existing signal it gives an error message. I'm going to attach screen shots, on iOS this isn't a problem. It's the android interface.

**Comment by dianamartin** [comment]
We have two tablets at the office that we can test this on Monday.

**Comment by johnclary** [comment]
ok. two questions. 1) did you sync the app to get the latest updates. 2) are location services enabled?

**Comment by dianamartin** [comment]
1. I downloaded the app this morning for the first time on the table, I'd assume it's got the latest updates
2. Location services are turned on

I just checked the Fulcrum settings, nothing out of the ordinary. So I attempted to try to create a new record. It said searching for nearby assets and then did the "error with request: undefined" error. Perhaps it's throwing that error bc i'm on wifi. I'll try with my mifi device.

**Comment by johnclary** [comment]
@dianamartin i was unable to reproduce the error message after downloading the updated version of the app. let's test again tomorrow from 8700.

**Comment by johnclary** [comment]
update functionality to be more intuitive. now, regardless of if you’re editing a pm or creating a new one, the app will fetch the entire list of signals, sorted by closest to your location. if this is a new PM, we will populate the signal field automatically with the nearest signal, but the user can modify it.
