### ISSUE TITLE
User Management | Populate user role in Edit User form

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#4994]
When editing a user, the role always default to `viewer` since the payload from Hasura does not include the role of the user. We could add the user role field to the `moped_users` table to fix this. Need to consider how the API will handle this upon user creation and all other routes that will need to be updated.

#### Form in Moped
<img width="313" alt="Screen Shot 2021-01-19 at 5 42 04 PM" src="https://user-images.githubusercontent.com/37249039/105107693-3bc3d100-5a7e-11eb-9308-8f1fd7b13ab8.png">

#### Payload
<img width="216" alt="Screen Shot 2021-01-19 at 5 42 31 PM" src="https://user-images.githubusercontent.com/37249039/105107707-42eadf00-5a7e-11eb-827b-21fdff537e65.png">

**Comment by zappfyllc** [comment]
"Delete User" deactivates the user (status is changed); check assumption on what impacts this has on the Cognito user
