### ISSUE TITLE
Create Prototype for Uniform Tracking

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#500]
### Executive Management team member (HR, Finance)
As a Executive Management team member, I want to know how much overall we're spending on each ATD Division on Uniforms and PPE items so that we can properly budget for it in the future.

### Division Manager
- As a Division Manager, I want to know how much we're spending per employee, monthly, annually so that I can do better budget forecasting when it comes time to ask for budget.
- As a Division Manager, I want to know how many items were issued to a single individual so that I can see we're being equitable to all team members.

### Supervisor
- As a Supervisor, I want to know what Uniform & PPE items we've issued out to my crew so that I have an understanding of how many items my team has. 
- As a Supervisor, I want to know when my crew need to order items again for their annual allotted uniform/PPE so that I can organize work group to be able to get their orders.
- As a Supervisor, I want to know why a single individual is being issued out PPE's so often so that I can determine if there is an underlying issue. 

### Staff Member
- As a Staff Member, I want to know which items are issued annually and items that need to be returned upon separate or transfer.
- As a Staff Member, I want to know what time of the year I need to start collecting uniform/PPE ordering should be. 

### ATD Employee
As an ATD Employee, I want to know what items are being issued to me and what items I'm responsible for and which ones I need to return if I leave or transfer groups.

**Comment by dianamartin** [comment]
related to #322, #323

**Comment by dianamartin** [comment]
## Interpreting User Stories - Functional Requirements

### Non Functional
Load Employee List from various Divisions
- ROW (Right of Way)
- AMD (Arterial Management)
- SMB (Signs, Markings & Banners)
- PE (Parking Enterprise) Enforcement - Meters
### Functional
Reporting Page - View Cost monthly, yearly, by Division

**Comment by SurbhiBakshi** [comment]
- working on figuring table structure and connections for database.

**Comment by amenity** [comment]
Backlogging this until we get a new PM.

**Comment by JaceDeloney** [comment]
I'm closing this out. It's not relevant anymore.
