### ISSUE TITLE
Meeting to go over Signal Mods, Upgrades, Inspection, Signal Timing Needs

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#501]
### Objective 
Review the required elements for Signal Mods, Upgrades, Inspection, Signal Timing. What information would AMD like to start tracking?

### Participants
Diana, Amenity, Jen, Brian

### Agenda

------
- [ ] Schedule meeting
- [ ] Meet
- [ ] Attach meeting notes to this issue
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
@amenity this looks very similar to #2251

**Comment by amenity** [comment]
@dianamartin - agreed.
