### ISSUE TITLE
IT Support: Update the 'shape' column with the contents of 'geometry' for 38 records in atd_txdot_locations

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#5013]
Some weeks ago, the DTS team processed a file of UPDATE statements to refine certain polygon shapes. In the production of the file of UPDATEs, I was unaware that the VZE application drew on the column 'shape' and not from 'geometry.' 

I have checked the current database with the following query to ensure that it's only these 38 polygons which have a difference between these columns using this query:

`SELECT location_id FROM atd_txdot_locations WHERE ST_Equals(shape, geometry) IS false`

The resulting rows match exactly the rows which were updated in that original set of UPDATEs. I have double checked also by loading these polygons in QGIS to make sure they appear as expected.

Further, the following query indicates that both columns of are of the same type and projection:

`SELECT f_table_name, f_geometry_column, srid, type 
FROM geometry_columns 
WHERE 1 = 1
AND f_table_name = 'atd_txdot_locations' 
AND f_geometry_column in ('geometry', 'shape')`

As a result, I propose the following query to be run on the database to get those shapes moved over to where the VZE will use them.

`UPDATE atd_txdot_locations SET shape = geometry WHERE location_id IN ('5503FB4E94', '27BF74798C', '2731E39AC1', '57B84C4D1A', '7169910510', 'D98E20E875', '1548575ACF', '1597553A08', 'A08AD3704A', 'A5DF90D337', 'E133E22652', '371C0C8058', '7D12F9FD99', 'A3EA6DF981', '03B23A52CE', '97FA66536A', 'C91093D186', '055FB8E58C', 'AF1EA8A4CC', '79CCC55C42', 'C435108C69', '7D304E9329', 'CEB60D166D', '19B272B352', '804E60B082', '5D0D6D870D', 'B7683545EB', '0768E6D2AE', 'E5D58EF734', '3DBD796FF5', '64E025E0FD', '8827B41ECE', 'D12345C1DD', '9CDE142A11', '32E7337EB8', '323493A4F8', '8F8303886E', '351BF1C84A');`

There will be crashes which move in, out and between polygons based on these changes. I am not sure what is the best way to address this problem. It may be to refresh the materialized views in place and use that data to associate crashes or I can build / find a query that could be used to find those that are out of place and write a script to trigger the update mechanism on it. Please let me know if these ideas, or any other technique that would preferred, would be helpful which I might be able to provide.

**Comment by frankhereford** [comment]
As an aside, I think we may want to evaluate and potentially drop the vestigial geometry columns that are hanging around in that table from the polygon generation. In addition, we will need to consider the status of the level 5 polygons which have a geometry but do not have a shape. Both of these operations (in this comment, not the above issue) will have impacts on the materialized views, and may not even be possible based on the database's self-sanity checks until those materialized views.

**Comment by sergiogcx** [comment]
@frankhereford What we can do is run a query that finds any crashes within that list of polygons and assigns them to their respective polygon.

**Comment by frankhereford** [comment]
@sergiogcx There may be crashes which _were_ in that set of polygons but no longer are that wouldn't be caught there. I can cook up something that UNIONs all those shapes together and buffers out say 250 feet, essentially making 'islands of interest' that crashes which fall into could be reevaluated. Does that sound useful?

**Comment by sergiogcx** [comment]
@frankhereford What do you say we try this:

1. Update the polygons with your query

2. Observe the list of affected crashes:

```
SELECT
        DISTINCT (atc.crash_id)
    FROM atd_txdot_crashes AS atc
        LEFT OUTER JOIN find_location_for_cr3_collision(atc.crash_id) AS loc ON TRUE
    WHERE 1=1
        AND atc.location_id IS NOT NULL
        AND (atc.austin_full_purpose = 'Y' OR (atc.city_id = 22 AND atc.position IS NULL))
        AND atc.location_id != loc.location_id
```


3. Update the crashes:

```
UPDATE
    atd_txdot_crashes
SET
    location_id = find_location_id_for_cr3_collision(crash_id),
    updated_by = 'SYSTEM'
WHERE
  crash_id IN (
    SELECT
        DISTINCT (atc.crash_id)
    FROM atd_txdot_crashes AS atc
        LEFT OUTER JOIN find_location_for_cr3_collision(atc.crash_id) AS loc ON TRUE
    WHERE 1=1
        AND atc.location_id IS NOT NULL
        AND (atc.austin_full_purpose = 'Y' OR (atc.city_id = 22 AND atc.position IS NULL))
        AND atc.location_id != loc.location_id
);
```
