### ISSUE TITLE
Create Filter for cancelled assignments

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#5014]

**Comment by SurbhiBakshi** [comment]
On @mddilley's advice, put in a filter removing any assignment that had a blank Assignment Date Time.

**Comment by amenity** [comment]
@SurbhiBakshi, am I right that y'all took care of this? If so, can you check the labels and add an estimate? Thanks!

**Comment by SurbhiBakshi** [comment]
@amenity - done
