### ISSUE TITLE
[RPP] Remove Second Edit Payment page and Update Display Rules

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5015]
Since all payment information is housed in the application we can remove the second Edit Payment column from the Cashier table and consolidate to the single Payment column that functionally adds and edits payment information as an edit form. Once Payment page is updated and display rules are updated in Cashier table we can remove the second Edit Payment Information page.

**Comment by ChrispinP** [comment]
Removed the Edit Payment column from the Cashier table and the second Edit Payment form. Updated Edit Payment page with new Payment Location and Transaction Amount fields.

**Comment by moorerst** [comment]
@ChrispinP I have not gotten any feedback from RPP staff on this update. They have been completing the new fields on the Edit Payment Page (Payment Location & Transaction Amount). I think this is complete and can be closed. Thanks

**Comment by ChrispinP** [comment]
Thanks Steph. no further issues, closing
