### ISSUE TITLE
[RPP] Remove Manage Attachments Button and Page

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5016]
Find out if RPP Staff still uses the manage attachments feature. If not, we can remove the button and page.

**Comment by moorerst** [comment]
Waiting on response from RPP staff.

**Comment by moorerst** [comment]
Per RPP Staff - We normally do use the attachments page With it being so busy with renewals we probably haven’t kept up on it as of late though. Do you know if they are still automatically being deleted out after 30 days, which is what I think was previously talked about?

**Comment by ChrispinP** [comment]
We will be offloading attachments to a secure environment in the future. Therefore releasing the burden on RPP staff and us to maintain this feature. Removed the Menu Button and the Manage Attachments Page.

complete
