### ISSUE TITLE
[RPP] Determine Usability of Transactions Table for RPP Staff and Finance

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5018]
We need to find out if RPP Staff and Finance are still using the Transactions table and if so, if anything needs to change or be updated and if not, if it can be removed.

**Comment by moorerst** [comment]
Waiting on response from RPP Staff and Finance.

**Comment by moorerst** [comment]
Per RPP Team - For finance we normally provide them deposit information weekly, which includes cash & check deposits as well as weekly credit card transactions. Then at the end of the month they have us verify totals. I’m unsure if Pham in finance is pulling any data from knack or not?

Example of the data sent to Finance
[CC_Charge_Weekly Form ( 1-11 to 1-15-2021) pdf.pdf](https://github.com/cityofaustin/atd-data-tech/files/5869506/CC_Charge_Weekly.Form.1-11.to.1-15-2021.pdf.pdf)
[Deposit CRQ 01-08-2021 2515000157.pdf](https://github.com/cityofaustin/atd-data-tech/files/5869507/Deposit.CRQ.01-08-2021.2515000157.pdf)

**Comment by ChrispinP** [comment]
Some requirements gathering is necessary here to determine how they generate or get the information they need to send to Finance. We also need to reach out to finance if their needs are met from this or if they need to access anything from Knack?

**Comment by moorerst** [comment]
discuss in sprint review

**Comment by moorerst** [comment]
Sprint Review scheduled for 3/11

**Comment by moorerst** [comment]
@ChrispinP I spoke with Van in Finance yesterday and she indicated she needs a report with Name Date Amount Payment Type monthly. 
I exported a report from the Transaction Page for the month of February and she said the report will work for her. She would like to be able to select the month she needs data for like on the Reports Page
[RPP transactions.xlsx](https://github.com/cityofaustin/atd-data-tech/files/6117036/RPP.transactions.xlsx)

Is the data from Transactions/All Paid payment statuses report correct?
Can we add the option to select the month for reporting?

**Comment by moorerst** [comment]
Need to verify with Van if any quarterly or annual reports are needed

**Comment by ChrispinP** [comment]
Updated Payment Type Filters
Fixed Check display
Removed Unnecessary fields
Added to Lookup Menu so Finance team can access
Added Date, Quarter, and Month filters

Transactions table update is now complete and ready for review.

**Comment by moorerst** [comment]
Report filters provides the options the Finance personnel requested.
Sent March report to Finance staff with instructions on how to export the report monthly.
Waiting on response from Finance staff

**Comment by moorerst** [comment]
closing issue to additional updates requested by Financial staff.
