### ISSUE TITLE
Feature: Ability to manually create a TIA Case

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5021]
### As a TIA reviewer, i need to be able to manually create TIA cases.
Button name: + TIA Review
Button location: TIA Mod Menu

**Comment by ChrispinP** [comment]
Added menu and button for a reviewer to manually create a new request from the TIA Requests page. Need to determine if any additional functions need to be added to the application process for reviewers that would be different from information a customer would enter. If no differences, a reviewer can utilize the same TIA Request application process that already exists.

**Comment by ChrispinP** [comment]
will create a new issue if this process needs to be adjusted any further.
