### ISSUE TITLE
Coding it Forward Civic Innovation Corps: Fill out position description by 2/23

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#5027]
> As a reminder, we ask that you please submit a position description for each Corps member you intend to host by February 12 to corps@codingitforward.com. We will use these to inform our recruiting and facilitate the matching process between candidates and host offices. Additionally, as our team shapes our application requirements, it would be helpful to know if your team has any requirements regarding citizenship, residency, education, or other factors. Feel free to reply directly to this email with those details

- ~[2021 Position Description Template _ Civic Innovation Corps.docx](https://github.com/cityofaustin/atd-data-tech/files/5845890/2021.Position.Description.Template._.Civic.Innovation.Corps.docx)~ [DTS Template](https://docs.google.com/document/d/1lwrzK9RZsHCNMmLOpOfvOGsCSSxm1Q9XP57mntMq10Y/edit?usp=sharing)
- [CDF 2021 Role Descriptions.pdf](https://drive.google.com/file/d/1IQtWnlqda3P-MOVDStb4nfmPtMMdAWx2/view?usp=sharing)
- [Partner Call Deck.pdf](https://github.com/cityofaustin/atd-data-tech/files/5845892/Partner.Call.Deck.1.pdf)

- [Drive folder](https://drive.google.com/drive/u/0/folders/1fVXL1i8okeoTQ6K9fRGBWbOU86ySqJUx)

---
- [x] [Design Researcher](https://docs.google.com/document/d/1vUXevYzf_8rwq8RA8L372AleFVdKd-nTjwdCntSX8Xg/edit)
- [x] [Software Developer](https://docs.google.com/document/d/1yVZn8r7w5dl7H2o3-hPJ3VCGuR1bMDf5EiHSuK_BKdA/edit)
- [x] [Data Scientist](https://docs.google.com/document/d/17-Iqq1Q-5eW7cqiHnnmO9Mqi3Q5PMWadGd48bK5-syc/edit)

**Comment by amenity** [comment]
Sounds like they bumped their deadline a week out to 2/19.
