### ISSUE TITLE
Signal Detection - Date captured when detector status changed (BROKEN to OK) 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#503]
Brian VDW
AMD

Brian needs a report of which how many signals (not *detectors) were broken/fixed in the past week. To accomplish this we need a script which logs when a signal's detection is fixed or broken.

Currently, can't customize data range for pie chart on Signal Detector Status Count by Intersection, it can't show a snap shot in time of when the status changed. (BC we were not tracking when a status changed from BROKEN to OK)

**Comment by johnclary** [comment]
Just reached out to BVDW:
> Brian—need some more clarification on this.
> 
> We can generate a report that will show, on a weekly basis, the number of signals with working detection and without. So in effect it will take the "snapshots" for you.
> 
> However, I don't know that this solves your problem. It sounds like the main issue is that technicians are not updating the detector statuses? We could look into how we could make that easier, maybe by adding more detection info in work order page.
> 
> Regarding the TMC updating statuses, this sounds like a training issue?
> 
> Any info you can share would be helpful. Thanks.
> John

**Comment by johnclary** [comment]
Latest from BVDW:

> There are definitely training opportunities on this. Our signal techs sometimes just forget to update the detection module in Data Tracker.  SOP changes are also needed. For instance:
> 
> - The TMC makes changes to the detection module of Data Tracker, but no Work Ticket.
> 
> - I don’t think the engineers update Data Tracker or create work tickets when they make changes.
> 
>  
> The part where I can’t figure out how to use Data Tracker to get what Jim wants is that he wants to know exactly what work was done at the intersection to fix detection. That isn’t in the detection module, so I have to look through every work order and work ticket for the past week to hunt for specific action items.

**Comment by amenity** [comment]
@dianamartin - did you talk to BVdW about this one?

**Comment by dianamartin** [comment]
@amenity I did not get to ask him about this, I asked him about a different one

**Comment by johnclary** [comment]
Per BVDW this is a training issue. Closing.
