### ISSUE TITLE
CTN as Project Extent Geometry

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#5037]
Test creating a project extent geometry that captures data from the project components currently being tracked through [ATSD's IMDB](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=d6194f783b114453a70eb769853e390c)

**Comment by alan-deanda** [comment]
![image](https://user-images.githubusercontent.com/42655533/105538218-ee2aac80-5ca7-11eb-92ae-0c903794de1c.png)
 This is a demo of the CTN used to represent Project Extents.
 The location polygons were key in turning project components into CTN-aligned project extents. They essentially catch all the free-drawn projects from designers and engineers, and I'm then able to do a spatial join to the CTN. the transparency layering to show density of projects works just as well as the location polygons.  The data still needs some QAQC work, however. Notice how the Waller Creek Trail geometry is very solid - it grabbed every project it crossed. I need to change the spatial join, but I thought I'd share with y'all that a) using the CTN for this purpose seems fairly feasible, and b) the work of the previous demo ended up being very useful. This spatial join used `intersect`, which is used to capture project components in location polygons. Next iterations will use different spatial join relationships.
 
Using the `PROJECT_EXTENT_ID` field from the vector tile version of the CTN that will be used in MOPED to choose project extents would help with QAQC.

The alternative to not using location polygons is to 1) align every existing project to the CTN, and 2) enforce snapping-to-CTN rules for any future project component mapping. I don't like the chances of either of those things happening or for this to be a sustainable strategy.
I think for the CTN to continue being a viable option we'll need to define its purpose so that it includes planned geometries as well, so we'll need to maintain the STATUS  field. We'll also need to make sure that whenever new project geometries are drawn, that corresponding CTN segments and Location Polygons are added.

**Comment by alan-deanda** [comment]
@amenity is this issue ok to close for now?

**Comment by amenity** [comment]
Yes!
