### ISSUE TITLE
Create Dispatch Reporting page

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5042]

**Comment by dianamartin** [comment]
- Created prototype for Dispatch Reporting
- Added basic reporting requirements from initial scoping session

**Comment by moorerst** [comment]
@dianamartin during Sprint Review stakeholder Tyrone requested a report on the # of Citations Issued filter by timeframe

**Comment by dianamartin** [comment]
@moorerst I'm going to close this issue and create a new one to rebuild the reports for Parking Dispatch that sources the SR table

**Comment by dianamartin** [comment]
The Dispatch Form will be removed and the SR Form will be used in place of this feature
