### ISSUE TITLE
VZV map ASMP street level to crashes

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#5043]
Epic to assign ASMP street levels to crash records.

To options for addressing this use case:
- geospatial processing
- tags

**Summary View**
[add use case from other ASMP-specific issue]

**Map View**
As a user of the VZV map feature, I want to be able to see fatalities and serious injuries on specific ASMP street levels so that I can see if there is a correlation between ASMP street level and injury severity. 

![Screen Shot 2021-01-21 at 2.48.00 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/ca7c09be-c22c-49cf-bf03-fd5ae01c3565)

**Comment by patrickm02L** [comment]
Nice to have. Don't see it as a crucial feature. Moving to Icebox incase we're interested in something like this in the future.

**Comment by patrickm02L** [comment]
## 10/2

Chatting with @Xavierapostol

Would require a new field in the crashes table that assign the max ASMP street level, using this new field you can associate with the toggle on the VZV map

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHYzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--caea231c477b10329f58bfe85aaa5229f0dda6fc/Screen%20Shot%202023-10-02%20at%202.47.12%20PM.png)

**Comment by patrickm02L** [comment]
Maybe one day, but retiring for now.
