### ISSUE TITLE
Add 'takeaways' text to components

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#5046]
We received feedback from users that it may help to understand a visualization if there was text describing the takeaway from the chart. For example, the Time of Day component could have text explaining that "The most dangerous time of day in X year is/was between the hours of X and X."

![Screen Shot 2021-01-21 at 6.26.19 PM.png](https://images.zenhubusercontent.com/5dc05535495c1e0001182c16/81662484-ba01-42d9-b39f-38b5dac9677c)

**Comment by patrickm02L** [comment]
This request opens up a larger discussion about how to interpret the data and where to put the onus. 

@patrickm02L would like to have a conversation in September Sprint Review as to how to approach this, and see if there's a manageable way to responsibly interpret the data.

**Comment by patrickm02L** [comment]
Nice to have.

**Comment by patrickm02L** [comment]
We haven't moved on this in 20 months. Retiring this Issue.
