### ISSUE TITLE
Meet with Tooran and Joe Michael to review request

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5051]
Would like to get them what they need to start using the app ASAP, even if it's not with all contractors, before taking on substantial re-engineering to do single-day work tickets.

After 2/1.

**Comment by amenity** [comment]
Scheduled for February 4, 2021.

**Comment by amenity** [comment]
@dianamartin — will you have time to do https://github.com/cityofaustin/atd-data-tech/issues/5033 before 2/4? Otherwise I'll push back the meeting.

**Comment by amenity** [comment]
Had to push back due to winter storm, now Friday 2/26 🤞

**Comment by dianamartin** [comment]
# Meeting Notes
- Reviewing Contractor Work Order - Current Prototype/Module
- Discussion points: Daily Work Tickets - benefits
  - whether we pursue daily work tickets
  - or Keep it to one project and have multiple time logs

**Comment by amenity** [comment]
Problematic part of only inspecting a project at the very end — if it's a long-term project, certain parts of the work, e.g. paint/striping might deteriorate by the time the project ends.

**Comment by dianamartin** [comment]
I completed a lot of the suggested changes, but I will create a new issue to document them. I have one more feature to do, I plan to do it at the end of this week.
