### ISSUE TITLE
Implement initial modifications

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5052]
### Remove "Date Worked" tables and form
- [x] Removed "Date Worked" form
- [x] Removed "Date Worked" table w/o delete button
- [x] Removed "Date Worked" table w/ delete button
- [x] Removed page rule on "Submit for Review" about Date Worked

### Reformat "Materials Used" tables/form
  - [x] Renamed to "Daily Work Log"
  - [x] Renamed to "Date Material Used" to "Date Worked"
  - [x] Reordered Daily Work Log form
  - [x] Renamed "Add Material" to "Add Daily Log"
  - [x] Grouped "Date Worked" field in table
  - [x] Added "Date Worked" field again on table - _per stakeholder preference_

### Attachments need to have "plans" type
  - [x] Added "Attachment Type" to form
  - [x] Renamed anything that said "Photo" or "Photo Attachment" to "Attachment
  - [x] Updated the icons used on table
- [x] Add Comments (edit only) - SMB and Contractor

### Adding "Corrected Date" - Contractor side to inspection table/form
  - [x] Added "Corrected Date" to `contractor_work_log` object - default to show "no date"

### Adding prototype work order (ATSD example of multi-day, multi-week w/Christina)
- [x] Christina adding ATSD

**Comment by dianamartin** [comment]
- Worked with Christina and tested the new features and found some elements we were missing
- Deleted test records and left test information for next week to show Tooran and Joe Mike
