### ISSUE TITLE
Project: Historic Traffic Impact Analysis Tracking

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5054]
We're enhancing our Traffic Impact Analysis (TIA) application to support the tracking of historical TIA cases.

The Transportation Engineering and Transportation Development Services groups have expressed a need to see TIA historic case data and TIA mitigation data that existed prior to the TIA Mod application in the TDS Portal application. The engineers and reviewers need a place to reference those old cases and mitigations to be able to conduct research that can allow them to utilize fiscal monies set aside for transportation mitigation projects.
 
## Background
The project is a high priority for the department as we need to track $15-$20 million in TIA Mitigation Data. This tracking will allow us to determine which roadway improvements can be done as we will have fiscal resources to be able to support those initiatives.

## Scope & Deliverables
- We are importing historic TIA cases into the TIA mod for the TDS reviewers to reference the captured dates their team needs to track for reporting purposes. 
- We are doing data (spreadsheet) clean up in order to have a single source of TIA Mitigation data with spatial coordinates and TIA Mitigation Fee Paid Dates (as close as possible)
  - Constraints: we are being requested to pull the TIA Memo dates from the PDF memos. However the PDFs aren't all Doc to PDF, some are just scanned in and converted to PDFs.
  - We have thought of searching in the AMANDA DB to see if there is a date field that would suffice
- We are importing historical TIA mitigation data into the system to be able to map it spatially for use in the Street Impact Fee Program as well. 
- TIA Mitigation page that allows TED group to manage the TIA Fiscal and allow users to search and find TIA Fiscal Memos

## Desired Outcomes
This project will be successful if we are able to allow users the ability to have all their historical TIA cases and TIA mitigations at their finger tips. The TED group managing historical TIA fiscal will have a place to point ATD users to query locations (tabular search) for TIA locations with fiscal. 
- Historic TIA cases being queried in the system like the other TIA cases being managed
- TIA Mitigation page that allows TED group to manage the TIA Fiscal and allow users to search and find TIA Fiscal Memos

## Timebox
We are thinking this may take up several sprints depending on the data clean up portion for both TIA fiscal and TIA mitigations. Perhaps the 2021 calendar year to finish?

### Sources
- [Original Spreadsheets folder](https://drive.google.com/drive/folders/1I7lSLv3fR-nS9crk8fZBVqJrGi_rNYv3?usp=sharing)

![image](https://user-images.githubusercontent.com/21112975/137774828-dbf9085a-9a9c-4577-ae4a-a56337f5b564.png)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
This is covered by https://github.com/cityofaustin/atd-data-tech/issues/6678

**Comment by dianamartin** [comment]
## 6/24
Chrispin was able to import in the historical TIA mitigation records. We rolled out the new historical TIA mitigation pages for TED in May 2022 and got the TED stakeholders to review and start managing the regulations. We followed up with them and got feedback on critical fields they needed and did several tweaks to get the pages exactly right. 

Last update, 6/8/22 we created the ability for the TED team to add more viewers so that can manage the folks who needed access to the historical TIA mitigation table.

**Comment by ChrispinP** [comment]
@dianamartin just realized we still had this open. Should we close this? I figure we should probably create a new epic if it evolves into a mapping project in the future.
