### ISSUE TITLE
TIA Mitigations Data Expansion

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5056]
### TIA Mitigations stakeholders will at some point need to identify when somebody is interested in the money, when the money is spoken for,  when it has been spent, how much is spent, and how much is remaining. 

Other data of interest:
- Who all requested the money
- Who actually spent the money
- What the money was spent on
- Why money was given to one stakeholder over another (if this ever happens)

**Comment by TracyLinder** [comment]
This will be scoped when it is identified by stakeholders as a priority. It is not MVP for the TIA Mod project.

**Comment by ChrispinP** [comment]
Closing. This request was ameliorated with the completion of Historical Mitigations and Mitigation Editor updates to the TIA Mod
