### ISSUE TITLE
Build deployment pipeline for Power BI

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#5057]
- [x] Research on building a deployment pipeline in Power BI while creating reports for VZA. 
- [x] Send in a ticket to CTM
- [x] Premium workspace creation
- [x] Testing with reports and datasets I create
- [ ] Testing with reports and datasets not owned by me

**Comment by katelunceford** [comment]
Closing this out; further work is captured in #16934
