### ISSUE TITLE
Robin Training Session for Configuring Desk/Spaces on floorplan

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5064]
Training session with Gilda's team to train them to how to configure desk and spaces on an existing floorplan.
The Barton Oaks floorplan will be used for training.
Scheduled 1/27

**Comment by moorerst** [comment]
Barton Oaks - updated layout and amenities
[Barton Oaks Robin seating map 012121.xlsx](https://github.com/cityofaustin/atd-data-tech/files/5874566/Barton.Oaks.Robin.seating.map.012121.xlsx)
[Amenities .xlsx](https://github.com/cityofaustin/atd-data-tech/files/5874567/Amenities.xlsx)

**Comment by dianamartin** [comment]
@moorerst You can add any notes you had for this

We met with Barton Oaks admin team to show them certain features that I used to create their map and figure out how to manage their spaces, desks, and people. 

We did some testing, instruction. I created a simple help guide that aggregated the help guides that Robin software created. Emailed that to Stephanie. Stephanie was going to email Gilda some other information. We documented some bugs we encountered and would email to Robin team.

**Comment by moorerst** [comment]
emailed help guide to Gilda's team also sent instructions for using the mobile app.

Expectation for the admin team to complete following training:

- the layout for the Barton Oaks floorplan by end of week 1/29.
-  have the discussions with Jen? on space for 8700 and 8900 Cameron
-  layout for 8700 Cameron Rd
I'll follow up with them on Monday 2/1.
