### ISSUE TITLE
TIA Mod Bug: Remove Old Form Instructions

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5069]
### Remove notification that displays after the customer uploads an attachment. 

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/0ae71b89-eef3-42ac-b287-b9f371215c88)

**Comment by ChrispinP** [comment]
@TracyLinder haha, nice catch. I caught this during my test as well and already updated.

complete
