### ISSUE TITLE
TIA Mod Bug: Reviewer Communication Text Missing from View

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5070]
### See below on case ID 57. I input a message/communication and it's not populating on this view.

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/84679290-7439-4621-8de0-651e4175c368)

**Comment by ChrispinP** [comment]
communications messages are working as expected. tested and also checked backend. Looks like a Horizontal rule was put in the communication message resulting in nothing displaying. Funnily enough it does display on the record and even the Text Formula pulls the horizontal line into its formula. Muy interesante.

no issue though. Closing
