### ISSUE TITLE
Knack Attachments Preview Bug

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5071]
### When user clicks on attachment link on the Case Details Page, the system acts like it's supposed to give the user a preview of the attachment but instead it populates a blank screen. 
- https://atd.knack.com/development-services#view-tia-requests/tia-request-details/600f176186e251001b028705/
- Happening here too: https://atd.knack.com/development-services#view-tia-requests/tia-request-details/600f176186e251001b028705/tia-scope-details/600f176186e251001b028705/

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/cb32f333-c9da-45bd-8b5c-bf55224de9a8)

**Comment by ChrispinP** [comment]
No bug but there is a load delay depending on file size and file type. The Loading text also appears small and feint. I have notified Knack on how we can improve this ourselves or if its fixable on their end.

Pending update.

**Comment by johnclary** [comment]
We could have the devs look at this to see if we could force a download instead of loading the file in-browser. But this should not be happening for smaller files (< 1mb). I'd like to hear Knack's response to this.

**Comment by johnclary** [comment]
@dianamartin would you test with some large files in the Signs & Markings app?

**Comment by dianamartin** [comment]
# Testing
- Marking WO: `ATSD-1930`
  - [plan - 8 mb](https://atd.knack.com/signs-markings#work-orders-markings/markings/?view_2107_filters=%5B%7B%22field%22%3A%22field_2153%22%2C%22operator%22%3A%22is%20not%20blank%22%2C%22text%22%3A%22All%20Work%20Orders%22%2C%22value%22%3A%22%22%7D%5D&view_2107_page=1&view_2107_search=shoal%20creek) - _opened pretty quickly_
- Marking WO: `ATSD-1803` 
  - [plan - 3 mb](https://atd.knack.com/signs-markings#work-orders-markings/markings/?view_2107_filters=%5B%7B%22field%22%3A%22field_2153%22%2C%22operator%22%3A%22is%20not%20blank%22%2C%22text%22%3A%22All%20Work%20Orders%22%2C%22value%22%3A%22%22%7D%5D&view_2107_page=1&view_2107_search=shoal%20creek) - _opened pretty quickly_
- Signs WO: `LA-2020-030`
  - [plan - 621 kb](https://atd.knack.com/signs-markings#work-order-signs/?view_2565_filters=%5B%7B%22value%22%3A%22%22%2C%22text%22%3A%22All%20Work%20Orders%22%2C%22operator%22%3A%22is%20not%20blank%22%2C%22field%22%3A%22field_3207%22%7D%5D&view_2565_page=1&view_2565_search=airport%20speed%20) - _lagged a little bit_

**Comment by ChrispinP** [comment]
I tested some more of these signs attachments and there is a small correlation to file size but it seems random on which files load in a reasonable amount of time. Here is an example of a <300KB doc not showing for over 10 seconds. The Knack spinner only lasts for about 2-3 seconds and disappears leaving the black screen.
![image](https://user-images.githubusercontent.com/67915167/107545061-778b1b80-6b90-11eb-8439-4cc2b03f4026.png)

**Comment by TracyLinder** [comment]
John suggesting: Check console for any errors. 
@ChrispinP

**Comment by ChrispinP** [comment]
So did some testing in console. It looks like on average its taking 9 or 10 seconds to try and load the attachment before it throws back a response, either the attachment, an error icon, or nothing(black screen). 
![image](https://user-images.githubusercontent.com/67915167/109729530-9c662380-7b7d-11eb-99d5-e6e670d56bf6.png)


Looks like its using a jquery integration to GET the file. The GET fails resulting in something like so: 
us-api.knack.com/v1/applications/5d4c508cab248a00108992e0/asset/6036ab4a25bc22001b44ec99/download/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBsaWNhdGlvbl9pZCI6IjVkNGM1MDhjYWIyNDhhMDAxMDg5OTJlMCIsInVzZXJfaWQiOiI1ZjIxY2JmZDg4ZGQyNTAwMTU2ODgxYTEiLCJzY2VuZV9rZXkiOiJzY2VuZV8xODciLCJ2aWV3X2tleSI6InZpZXdfNDQ4IiwiZmllbGRfa2V5IjoiZmllbGRfMTkwIiwiYXNzZXRfaWQiOiI2MDM2YWI0YTI1YmMyMjAwMWI0NGVjOTkiLCJzb3VyY2UiOiJyZW5kZXJlciIsImlhdCI6MTYxNDcyNzM2MX0.xlwJVkyR-mkg1tOuFAIrygqCNk9rr4ykxqqBKz3YTDM?preview=true#view-tia-requests/tia-request-details/6025ace3cceb98001ca59fd2/tia-case-management/6025ace3cceb98001ca59fd2/tia-submission-details/603690e074983d001d774dc5/kn-asset/187-448-190-6036ab4a25bc22001b44ec99/donald_duck.jpg:1 GET https://us-api.knack.com/v1/applications/5d4c508cab248a00108992e0/asset/6036ab4a25bc22001b44ec99/download/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBsaWNhdGlvbl9pZCI6IjVkNGM1MDhjYWIyNDhhMDAxMDg5OTJlMCIsInVzZXJfaWQiOiI1ZjIxY2JmZDg4ZGQyNTAwMTU2ODgxYTEiLCJzY2VuZV9rZXkiOiJzY2VuZV8xODciLCJ2aWV3X2tleSI6InZpZXdfNDQ4IiwiZmllbGRfa2V5IjoiZmllbGRfMTkwIiwiYXNzZXRfaWQiOiI2MDM2YWI0YTI1YmMyMjAwMWI0NGVjOTkiLCJzb3VyY2UiOiJyZW5kZXJlciIsImlhdCI6MTYxNDcyNzM2MX0.xlwJVkyR-mkg1tOuFAIrygqCNk9rr4ykxqqBKz3YTDM?preview=true 500 (Internal Server Error)

![image](https://user-images.githubusercontent.com/67915167/109729433-793b7400-7b7d-11eb-8a70-d228cf8a9a4c.png)

**Resulting in a Internal Server Error in the console.**

**Comment by ChrispinP** [comment]
@johnclary anything you can assess from my previous console testing? Can we make this attachment experience better for users?

**Comment by ChrispinP** [comment]
Ive submitted a new request into Knack to shift the file down so the file name and visible and increase the duration of the loading spinner until the file loads.

**Comment by ChrispinP** [comment]
@chiaberry @mddilley giving you both visibility on this issue should Knack not be able to improve the attachment preview. The new builder improved the preview some such as more visible text and close button but the positioning and load spinner still need to be improved. No action needed atm.

**Comment by ChrispinP** [comment]
Knack agreed and created a case for their product team to improve this feature. Pending any further updates.

**Comment by ChrispinP** [comment]
No updates or changes yet.

**Comment by ChrispinP** [comment]
Images are still a bit too high and cover up the file name but the visibility has been improved and documents, specifically pdfs load well now.
![image](https://user-images.githubusercontent.com/67915167/124030553-ea6c2600-d9bb-11eb-973e-18fb53c112d3.png)

The loading time and spinner no longer seem to be issues. Closing as 99% complete for Knack
