### ISSUE TITLE
TIA Scoping Iterations

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5072]
### Update Scoping features to be as identical to Submissions features as possible.

**Comment by TracyLinder** [comment]
The system sent two emails to the customer relating to the rejection of the scope.
1. The email instructs the user to open this link and resubmit. The page does not offer that functionality. 
 - https://atd.knack.com/development-services#review-tia-case-status/view-tia-details/600f176186e251001b028705/
2. The other email instructs the customer to review their case at this link:
- https://atd.knack.com/development-services#review-tia-case-status/view-tia-details/600f176186e251001b028705/

**Comment by TracyLinder** [comment]
- Separate scope into it's own object
- New customer process for submitting a scope

**Comment by ChrispinP** [comment]
Scope Submissions are now its own object, identical to the Submissions object and pages. The process for both customers and reviewers to add scope submissions is now built. The Submissions button is now > Case Management. Case Management house both Submissions and Scope Submissions and allows the reviewer to create new submissions from this page.

Will be updating any corresponding emails or log rules as necessary.

complete
