### ISSUE TITLE
TIA Mod Case Status Update - After Scope Approval

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5073]
### After scope is approved, the case status should update to 'Pending Submission'
- Currently updating to 'Pending Memo'

**Comment by ChrispinP** [comment]
Updated to Pending Submittal but will need to update these rules again to the connected TIA Request object once Scope is its own object again.

**Comment by ChrispinP** [comment]
Scope is now its own object. I have updated the status to be set to Pending New Submittal if approved.

complete
