### ISSUE TITLE
Mitigation Fee Expiration Automation

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5076]
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/b847d3b5-f2fa-4301-860d-6102b35dfbd8)

**Comment by ChrispinP** [comment]
Created equation with Ternary Operators to set blank if Mitigation Fees Paid is No and to set expiration date when set to Yes

complete

**Comment by ChrispinP** [comment]
no further issue, closing
