### ISSUE TITLE
Project: Street Impact Fee Implementation

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5078]
As part of ATD's Street Impact Fee Implementation Team, DTS will manage the technology-related needs of the project. Project deadline is Tuesday, June 21, 2022.

### Resources

- One Drive folder [here](vishwa.c@launchitcorp.com)

### Timebox
Street Impact Fees go into effect mid-summer 2022.

![StreetImpactFee](https://user-images.githubusercontent.com/1463708/170152529-109fa3fd-d3cf-4da7-be01-e6728904a032.jpg)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by johnclary** [comment]
@TracyLinder I changed the issue title and took a shot at the one-liner. I would prefer that you don't apply the `Project Index` label until there is customer-friendly content in the description. Other wise the issue looks like this on the website:

<img width="1191" alt="Screen Shot 2021-01-30 at 2 13 56 PM" src="https://user-images.githubusercontent.com/14793120/106367063-b7870e80-6305-11eb-8353-3fbea916918b.png">

**Comment by TracyLinder** [comment]
@johnclary my apologies, I haven't gotten back to update this template yet. Regarding pipeline, we're actively meeting as a project team so I consider it ongoing.

**Comment by johnclary** [comment]
@TracyLinder what's the latest on this? Will LIT being picking up the AMANDA work now that we have them back on contract?

**Comment by TracyLinder** [comment]
### Project Update

Hi All,

I hope the holiday’s have treated you well. The SIF IT project is moving along on schedule and I’m feeling confident about the project overall. Below is an overview/update on the project. Please reach out with questions/concerns/feedback. Wishing you all a great 2022!


**Timeline**

- Nov - Jan: Requirements Gathering & Documentation
    - We’ve identified & documented business requirements and we are currently refining the technical documentation.
    - We have an AMANDA business analyst on the team who has attended all meetings to date. He is responsible for technical documentation and being an extra set of hands as needed.
- Jan - Apr: AMANDA Development
    - We have hired an AMANDA developer solely dedicated to this work. She has experience building new AMANDA folders and managing migrations from V6 to V7.
- May: Release & User Training

**AMANDA Development Details**

- Due to the AMANDA V7 upgrade project we must build SIF in both versions of AMANDA (V6 & V7). Our approach will be to do the full build in V6 then migrate it to V7. We will have to do full user acceptance testing in both environments. Luckily our developer has experience managing these types of migrations.
- We plan to begin AMANDA development the 2nd week of January. We will not have all of the technical criteria ready at this point, but we already have enough to begin.
- We will show our work early and often and incorporate user feedback into our work as we go. We’ll either do weekly or bi-weekly reviews during this time with the project team.
- I’ll be meeting with our technical team next week to discuss the implementation timeline and set hard deadlines. I’ll communicate those with you ASAP.


**Our Work To Date**

- The SIF IT project team meets twice weekly until all requirements are identified and documentation is complete.You can view meeting notes here. 
- We've ironed out about 85% of the SIF AMANDA workflow. The remaining 15% involves coordination with DSD. We will meet again with all DSD stakeholders on 1/6/22 to determine where in the site development process ATD will insert and collect SIF fees. 
- We are currently focused on the AMANDA tech specifications document; here if you're interested. 

Thanks, 

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
### Update June 24, 2022

The Street Impact Fee program began assessing fees in AMANDA on June 22nd using the newly created SIF folder in AMANDA. SIF Reviewers are being assigned to plan review (PR) folders in AMANDA and are able to perform their job functions. 

Just before rollout last Friday 6/17 the project team was made aware of a plan review workflow requiring a system integration with ProjectDox, which is used by DSD to perform expedited reviews. TDS staff were able to identify an interum manual workaround to still deliver SIF assessments while the integration piece is scoped out with DTS. 

We were also asked by DSD to make a SIF info field required, which we are working on and hoping to deliver before the V7 code freeze.

**Comment by amenity** [comment]
@TracyLinder - please write a several-sentence update here & delete this comment. ✍🏻 🗑️

**Comment by TracyLinder** [comment]
### Update & Closing

All deliverables for the initial implementation of SIF features in AMANDA have been met. We consider SIF-AMANDA to be in maintenance mode moving forward and we are closing this project.
