### ISSUE TITLE
TIA Mitigations Page Updates

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5079]
### Fee in Lieu Table
- Remove fee expiration and relocate to request object
- Add export option

### Mitigation Construction Table
- Remove Pro Rata Share, Fee Expiration
- Add export option

### Mitigations Form
- Don't ask for pro-rata when it's construction
- Add field for Direction
- Update Improvement values to exclude duplicates and remove direction

**Comment by ChrispinP** [comment]
complete

**Comment by ChrispinP** [comment]
updated the Mitigation page a bit more with some styling edits and centering the project name on the page. added icons for sections and updated table formatting.

closing
