### ISSUE TITLE
Discuss location for VZA reporting data for Power BI

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#5087]
@amenity - We should discuss putting VZA reporting data (for Power BI) in a location that the three of us can access. @dianamartin - We will probably need your advice on One Drive.

**Comment by amenity** [comment]
@SurbhiBakshi - Is there a reason we can't use Drive? It's not PII, right?

**Comment by SurbhiBakshi** [comment]
@amenity - right now it's on my One Drive. Not sure what that means in terms of accessibility, wanted to make sure you and Diana can access that, or if there is a better alternative for location in terms of updating the datasets.

**Comment by amenity** [comment]
Let's create a folder in the [VZA Google Drive](https://drive.google.com/drive/folders/1IUXtA0WsDXK5WfFidIZCfuDg5DjkHvOt) so it is stored with everything else related to the project.

**Comment by amenity** [comment]
One Drive has an integration with PowerBI, so we should test this and make sure Diana and I have access. (We'll be backup for updating the PowerBI reports on a weekly basis.) @SurbhiBakshi please send link to where the files are now.

**Comment by SurbhiBakshi** [comment]
Scheduled a meeting for March 12th.

**Comment by dianamartin** [comment]
was reschedule to 3/22

**Comment by dianamartin** [comment]
Instructions in ATD Knack Operations wiki
- [x] Can access OneDrive 
- Follow steps on wikie page `Update reports in PowerBI`
