### ISSUE TITLE
Create draft Data Reporting Specification content

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#5092]
Provide the Shared Mobility Team with a draft of the Data Reporting Specification document that will be added to the Shared Mobility website. This information outlines the data, reporting, and geo file requirements for successfully complying with the Shared Mobility Operating policies. 

Current draft of the document can be found here:
https://docs.google.com/document/u/1/d/1y5N71Jtu8NkM5iZ2DhXJ2iwmSu5te0O1h_DPYz3i1Wk/edit#

**Comment by amenity** [comment]
@johnclary - do you want Patrick to help/own this? What timeline are we looking at?

**Comment by johnclary** [comment]
Moved into the backlog. I've nudged the Mobility Services folks about this a few times but it sounds like the director's rules re-write is on hold.

**Comment by patrickm02L** [comment]
Considering this request expired.
