### ISSUE TITLE
VisionZero Database | Level 5 Polygons

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#5093]
There need to be changes to the database to accommodate for the categorization of crashes happening in Level 5 polygons.

**Comment by frankhereford** [comment]
## Definitions

Just for ease of writing, I want to define some ways of referring to the different sets of crashes and polygons.

**Highway** crashes: crashes which occur on a level 5 road, which is related but not always aligned to having the on-system flag set to true.
**Surface Street** crashes: crashes which occur on a level 1-4 road.

**Highway** polygons: Polygons which were created from a road network of the ASMP's level five roads. They are indicated currently in the atd_txdot_locations table by `location_group = 2`.
**Surface Street** polygons: Polygons which were created from the ASMP network's level 1-4 roads. They are indicated in the atd_txdot_locations table by `location_group = 1` currently.

Note: Each of the sets of polygons above do not overlap with one another _internally_, however, the two _sets_ do overlap with each other.

## Goal

To enable the ability to track if a crash occurred on a highway, and based on that information, control which set of polygons that crash is allowed to associate to.

## Proposal for discussion

### Enable the tracking of Highway vs. Surface Street status for a crash. 

1. Create a new column in the atd_txdot_crashes table called `is_lvl5` of type integer with default value of _null_. The value 0 will be used to indicate surface street status and the value 1 will indicate highway status. Crashes which are of type _null_ are in the set that need to be processed, such as when a new crash is retrieved from CRIS.
2. Utilize a one-time use query that selects the crashes which fall within the 1-foot buffer around the main-lane geometry and updates the set `is_lvl5 = 1`.
3. Immediately then do something like `UPDATE atd_txdot_crashes SET is_lvl5 = 0 WHERE is_lvl5 IS NULL;`.
4. Add logic to the end of the ETL import process which uses similar logic as above to set the `is_lvl5 ` flag for a new crash. It is important to populate the is_lvl5 flag prior to attempting to associate a crash to a polygon, as it describes which set of polygons are appropriate to associate against. 
5. Add the ability in the VZE to view the current state of the `is_lvl5 ` flag and toggle it as needed.
6. Crashes which were once on the main-lane (and therefore originally highway crashes) but have been manually moved off main-lane (making them now look like surface street crashes), will end up being flagged as `is_lvl5 = 0`. This is expected, and the Vision Zero team will be responsible for isolating this limited set of crashes and manually toggling them back to `is_lvl5 = 1` via the VZ UI or via a proposed set of simple UPDATEs to be delivered to the DTS team for consideration, hopefully to be run against the production database.

### Enable the viewing of highway polygons in the VZE

1. Execute a query along the lines of `UPDATE atd_txdot_locations SET shape = geometry WHERE location_group = 2;`.
2. Remove the WHERE clauses from appropriate queries that are restricting these highway polygons from matching queries that drive the VZE. Presumably, it would be the removal of something akin to `WHERE location_group = 1`. 
3. Expand the search criteria for locations to include the ability to filter the results in the sortable locations table to restrict the polygons of interest to either `location_group = 1` or `location_group = 2` (surface or highway polygons).

### Expand the routines which are responsible for associating crashes to polygons

1. On INSERT or UPDATE to a crash, and in particular to the `is_lvl5` flag or the location (or latitude/longitude columns -- whichever is the authoritative store of spatial location), expand the logic either through a CASE statement in SQL or procedural logic in the lambda function, to have the system check the `is_lvl5` flag to decide which set of polygons the crash should be geospatially matched against.

**Comment by frankhereford** [comment]
Just as a thought outside of the scope of the above comment -- I hope the ideas above are taken only as a jumping off point for discussion. I am sure there are considerations which I'm not aware of as well as better ways to do things! My only intent here was to try to capture and memorialize some of the discussion today. Thanks!

**Comment by mateoclarke** [comment]
As we discussed via phone, @frankhereford is going to take the lead on these tasks and let me, @sergiogcx, or @tillyw know if he needs support along the way with any SQL ALTER updates he doesn't have permissions to execute, knowledge gaps with the code structure of frameworks (ie: React), or ability to test in staging/dev environments before running in production.

**Comment by patrickm02L** [comment]
- Distinguishing crashes on level 5 main lanes versus service roads
- Frank has developed a better way to identify what polygon a crash belongs to.
- Next step: @frankhereford to schedule a work session to go over polygon improvements.

**Comment by patrickm02L** [comment]
@frankhereford I feel like this has been completed? Can we close this issue?

**Comment by frankhereford** [comment]
@patrickm02L Not really, but we have done work on getting some crashes off the level 5 road centerlines into service road polygons when appropriate. There are still crashes which are genuinely on the main, proper lanes of level 5 five roads which are entirely unaccounted for in the polygons. This has previously been a non-issue as our VZ focus was on off-system roads that we had more control over as a department, but now there is increased interest from VZ leadership to track on-system, level 5 crashes at a more granular level. 

I am currently tasked with creating a level 5 map outside of the VZ app environment, and that may be enough on the level 5 analysis for the near future - **this may be something we can icebox**.

**Comment by patrickm02L** [comment]
We are capturing this work in #11844
