### ISSUE TITLE
Feature: TIA Mitigations Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5095]
### Scoping Needed

- What is the purpose of this page & the deliverables?

**Comment by ChrispinP** [comment]
We have a Mitigations Details page, an add Mitigation form page, and a Mitigations Directory advanced search page.

@TracyLinder are there any other Mitigation pages needed?

**Comment by TracyLinder** [comment]
Currently the page is in good shape. Will open new issues as needed.
