### ISSUE TITLE
Meet to discuss SMB and AMD DSDD tracking

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5096]
[Recording](https://web.microsoftstream.com/video/99f712db-f367-4010-9042-db96617ff423)

**Comment by dianamartin** [comment]
# Diana's Notes

## SMB Request: Daniel/Max, Billy 
Email notification when - know when DSDD signs are installed/removed
- will get emails when "asset" form is submitted
- remove Daniel in a few weeks

Amica is the new Eric
Max is the new Mario - LATM, Speed Management Program (DSDD)
Roadway Safety and Design - lives there
Should be in Speed Management Mitigation

## AMD Request DSDD 
Daniel shared information with Jen/Billy about DSDD
Biggest issue/pain point

Keeping up the maintenance of these DSDD devices
Will start needing to do preventative maintenance 

Don't have a way to keep good records of those locations
Technicians are used to using Data Tracker 
Emails aren't that efficient

Daniel shared the program with AMD
Shared the location of the DSDD's once they're activated

TED needs to know when it was installed and serial numbers to upload the information in their software program. 

Example. Review last 4 devices, then asked to look at 2 of 4 have already reviewed the information. 

Don't have a DSDD module in AMD
Difficulty for the technicians to track their work

Can give access to the program - different user roles 
- Web Director 2.0 - [DSDD Program](streetsoncloud.com)
- Traffic Logix, manufacturer of DSDD

Ask the area technicians - do the Digg Tess, then do the markings
When the Digg Test is done - install 4-5 units
Work Order is completed
Received the serial number, address and sign facing direction

There is a map function (GIS map)
Green - active 
Red - some issues
Grey - previous installed or not connected to the cloud

**Manage Locations**
- Add New locations, he creates a new location (Must type in the whole address), there is an autopopulated result.
- Confirm address, confirm, "Ok"
- Location Name
- Traffic Direction (which way it faces)
- Time Zone
- No way to filter locations in this program
- Can be assigned to a "group"
- Updates sign settings
- Enters the "serial number" (There are 2 serial numbers, outside of the box, serial number is the motherboard serial number)

Ex. One unit needs a new motherboard. How do you know where it is?
- Can filter by serial number from the map?

TED New funding - Purchase new DSDD units (time frame: May 2021)
- to add to unit fleet

# Proposed Ideas
IN AMD DATA TRACKER
- Digitizing DSDD unit spreadsheet into AMD Data Tracker
- DSDD units
  - related historical locations table
  - related historical service requests

IN SMB DATA TRACKER
- Create page to show Asset Specificaitons - DSDD
  - related SMB locations
  - related work orders

**Comment by dianamartin** [comment]
Created prototype pages in SMB of asset specs and related locations, not as elegant as imagined..

**Comment by dianamartin** [comment]
Reviewed current DSDD spreadsheet and would like to request a list only of DSDD permanent locations. I wonder if exports can be done from the online platform because that seems like the cleanest data.

**Comment by amenity** [comment]
@dianamartin - that sounds like a good idea. Do you have access to StreetsOnCloud yet?

**Comment by dianamartin** [comment]
@amenity Yes, Daniel gave me access as Report Manager group, but asked me if I wanted Power user access. I responded with wanting Power user access so I can figure out all the functionality.

**Comment by dianamartin** [comment]
I'm having trouble signing it, looks like there may be a global maintenance going on. Will have to try again later in the week.

**Comment by dianamartin** [comment]
I was able to log in the Web Director site "Streets on Cloud", had a password snafu. Am going to start looking around for exporting functionality.

**Comment by dianamartin** [comment]
Just had our builder huddle meeting, closing this.
