### ISSUE TITLE
Publish Bike Facilities to DM

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#5104]

**Comment by alan-deanda** [comment]
Request has been submitted in Service Now.

**Comment by alan-deanda** [comment]
Re-submitted request ticket to CTM. Ticket number: INC0082966

**Comment by alan-deanda** [comment]
Need to update metadata and notify CTM.

**Comment by johnclary** [comment]
Will be published to DM on Thursday (2/24)

**Comment by alan-deanda** [comment]
Data is live in DM now
