### ISSUE TITLE
Feature: Add link to signal details page (in Data tracker) from pop-ups in ArcGIS online asset map and ideally open in new tab

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5114]
AMD users (Robin, Brian VDW) use the AMD asset map to find the signal they're looking for, they're really like a link that opens in ArcGIS pop-up to open a new tab/window that opens to the signal asset details page.

**Comment by johnclary** [comment]
The [signals layer](https://austin.maps.arcgis.com/home/item.html?id=e6eb94d1e7cc45c2ac452af6ae6aa534#data) has an `id` field (alias "Knack ID") that can be used to construct the URL. The pattern is

`https://atd.knack.com/amd#signals/signal-details/<knack-id>/`

[For example](https://atd.knack.com/amd#signals/signal-details/58164b9af9195edb2a5e3a07/).

I can't remember—is it possible to create this link in AGOL with this information alone, or do we need to add this URL as a column to layer and include it in the ETL? cc @jaime-mckeown

**Comment by dianamartin** [comment]
- I checked Data Tracker API View, Knack ID is in the feature layer `signals`
- Asked for help from Susanne after I attempted to do it on my own, she helped me out since she'd done it many time before and Jaime was out. 
- Modified the "configure pop-up"
- Added Attribute Expressions - created custom expression
`https://atd.knack.com/amd#signals/signal-details/"+$feature.id`

### ArcGIS Web Map
![image](https://user-images.githubusercontent.com/21112975/106179198-4fe38e80-6160-11eb-99da-2a49c1b38069.png)

### Tested in AMD Asset map
![image](https://user-images.githubusercontent.com/21112975/106179612-e57f1e00-6160-11eb-855d-9b3229fef091.png)

### AMD Data Tracker - opens up Signal Details
![image](https://user-images.githubusercontent.com/21112975/106179836-33942180-6161-11eb-8545-50162afdd5c7.png)

**Comment by dianamartin** [comment]
Will message interested parties, Brian VdW and Robin.

**Comment by johnclary** [comment]
Cool! Nicely done! 🙌
