### ISSUE TITLE
Meeting: Bi-weekly Robin Configuration Review

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5116]
### What we have accomplished:
- Focus has been on layout for the Barton Oaks Floor 3
  - Added spaces
  - Added desk
  - Added Amenities
### Some policies
- Established the Calendar Connection and SSO
- Added spaces to the calendar
- We had a training session for the internal admin staff to get them familiar with navigating all features of the layout

Goal is to have the Barton Oaks map complete by **Friday 1/29**.

Next, we plan to begin testing the user experience from the website and mobile app and work on 8700 Cameron Rd map.

**Comment by moorerst** [comment]
We have a few issues for discussion on Friday:

1. 

We have the spaces set as Request Only. When we request to reserve the space we are not seeing an approval for the reservation. - RESOLVED

1. 

When I access Robin as a member the Desk are not displaying for me to reserve.

**Comment by moorerst** [comment]
can the email notifications we receive be modified - can the logo be changed
![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/c0962454-17e6-4556-b8e7-66cb809946ee)
![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/7ef0aa2c-e2e5-4ec8-a281-9134ab2bf742)

**Comment by dianamartin** [comment]
@moorerst We haven't branded our Robin environment, I think there's a place to make those changes. I don't know if they're trickle down to the email that is sent though.

**Comment by dianamartin** [comment]
# Meeting Notes 1/29/2021

## Questions
- As a member user role, couldn't see the "Offices" tab
  -  Training issue: select "Floor" not "All Floors" 
  
### Best Practice
- Remove campus? redundant "Campus>Building" - consider removing the campus
- Ali asked why we set it up as points of interest v. desk 
  - Reference where the hotel is
- Long term - assigned desks: check-in
- Set up as desk 

### ATD Licenses: 
- We've bought 1,100 desks and licenses 
- Assign a desk - user in Robin (name/email)
- Health check point 

## Questions
- Book through outlook?
  -  Meeting rooms
  - Can sync with Robin
  - Meeting rooms will stay in sync
  - Delegate set up, 4-5 people can accept for reservation
  - Re-test booking, delegate
  
#### Room request feature
Accept/Deny a request
9 Admin role
Owner v. Admin 
  - difference? Admin: view billing page, Owner: can edit billing page
Create custom role "Delegate" to request and deny
- get 2 emails from Outlook and Robin?

**Meeting Room Approval**
https://support.robinpowered.com/hc/en-us/articles/360035496232-Meeting-Room-Approvals-Google-O365-users-

**Comment by moorerst** [comment]
Debriefed with Diana. Will create New Issues resolving from this meeting. Closing
