### ISSUE TITLE
Test Robin website with member only permissions

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5121]
Test reserving a desk and space from the website as a COA employee would.

Initial test did not display the Desk for reservation. - this was sent to vendor as an issue

**Comment by moorerst** [comment]
@dianamartin I did some testing as a member only. Documented what I tested. I had a few questions highlighted in red.
https://docs.google.com/document/d/15ESpZLwVe6bYeZQDJVEEhQ6pOYfWd-52IlPxU2jn6lw/edit

Overall I felt pretty good about what I tested

**Comment by dianamartin** [comment]
I think we tested pretty thoroughly. We will be having users test this week as "members" and will add their feedback when we collect them.

**Comment by moorerst** [comment]
Completed internal testing of the desktop version of the application. Testing will also be done as part of User Testing. If any new issues are identified during user testing those will be documented in the User Testing issue. Closing this issue
