### ISSUE TITLE
[Data Model] | Running list of data model changes

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#5122]
We have agreed to track necessary/requested data model updates under one umbrella in order to tackle data model changes every sprint but group them in a manner that makes it easiest for developers. We can determine issue-by-issue under this epic how significant the data model change is.

**Comment by amenity** [comment]
@zappfyllc - do we still want this issue?

**Comment by zappfyllc** [comment]
@amenity no I'll close it, think we should just make data model changes as we go with features and we already have #6233 that's going to involve some database cleanup
