### ISSUE TITLE
Meeting: Dispatch Tracking Kickoff

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5128]
Kickoff meeting scheduled 2/4

**Agenda:**
- Review requirements collected in previous intake meeting
- Determine if there are any new requires
- Demo prototypes

**Comment by moorerst** [comment]
@dianamartin please review the slides for the kickoff meeting and update or provide feedback. Thanks
https://docs.google.com/presentation/d/14OSs6N3CoEqkQdnB0IRO2gwzEWZDNduEFYOlt9Gy400/edit#slide=id.g7e5c9351e1_0_19

**Comment by dianamartin** [comment]
@moorerst  
Messaged you in Teams
>I talked to John yesterday and we think we'll be able to incorporate the 311 CSR requests for them. We just have to figure out their future state and what that might look like. So I think the plan to demo what we have is nice to get their minds going and then asking that question about "what would it look like if we incorporated 311 requests into this portal?"

**Comment by dianamartin** [comment]
# Diana's Notes

J Tower: Can Knack submit attachments to 311 system?

Dispatcher have 311 access
Opens 311 website
Review 311 SR 
Radio dispatch officers
Put that information in SharePoint Dispatch list 
- Putting in 311 Activities 
Close SR type

Email: Everyone (leadership and dispatch staff) gets email CSR, opens CSR from actual email.
- Still want to keep email

How many CSRs do you receive? They also receive, Micromobility CSRs? GT? Parking Enforcement? Booting, RPP? 
- Except for Parking Meters CSRs

What do you want to track?
Specification?: "Action"

Outcome: What is the outcome?
Attachments: blank parking space/curb - show no violation
- include Photo
- 1 to 3 photos
Dispatch - QC

M, T, - one dispatchers assigned
W- F - two dispatchers assigned (3 hour overlap)

Open - by default
"Assign" - In Progress status

Assign Equipment - equipment going down, needing to check out a spare
`Leadership Notes` - Announcement, Teams used now. 
- ex. Change in shift

Move "Dispatch Note" - closer to Action/Outcome
Drop down to 20
Edit Form - audit tracking

Next Steps: Bi-weekly sprint review meeting

Records Retention: 3 years?

**Comment by moorerst** [comment]
Stephanie' s Notes
[Kickoff Meeting](https://docs.google.com/presentation/d/14OSs6N3CoEqkQdnB0IRO2gwzEWZDNduEFYOlt9Gy400/edit#slide=id.p
)
Attendees: Toni, Levi, Shavyvonne, Christine, Tyrone, Joe, Jasmine, Lyndon, Lesha, Hillary

CSR work flow
Leadership gets email notification of CSR
Can open CSR from email or website
View info, dispatch officer, put info into Sharepoint (SP)
Enter outcome into CSR and Close in CSR
Add additional information into SP

** Need to keep email notifications for CSR's
CSR Types
Micromobility
Parking Enforcement General
Booting
RPP
Only want to track What they do and What is the Outcome

Attachments:
If there is no violation they will attach a photo of the officer at the location just to confirm the office did go on site
Currently Officers send photos to the Dispatcher via Teams and the Dispatchers will attach to SP
**Would be nice if the Officer could attach the photo in Knack from the Brazos device. Officer may need to upload multiple photos up to 3

Service Request Form
**New calls should default to Open
**Once the request is assigned to an Officer Status changes to In Progress - so anyone can see what request has been started

Categories
Assign Equipment - used when an Officer's equipment is broken and they are using spare equipment
Leadership - used to display announcements that are important for everyone, needs to be visible
**Both of these categories can be removed from the list and put somewhere else  
**Announcements need to be visible, like a broadcast message
**Clean up Dispatch Categories
**Clean up Officer list to include only Active Officers
**Action and Outcome keep as separate fields
**Move Dispatch Notes closer to Action and Outcome
**# of citations can be a drop list up to 20
**SR Table remove ability to edit from the table, need to be able to log who edited last
**Need a Final Review process

Resource Tracking
Calendar list - not important
Records Retention current year = 3 years

scheduled recurring Sprint Review meetings
