### ISSUE TITLE
Automated Notification to Mike S.

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5133]
### When TIA case is created/submitted, the system should email Mike S

**Template**
- Subject Line:
New TIA Case: [Project Name] - Case ID: [Case ID]
- Body:
A new TIA case has been opened. 
[Link to case]

**Comment by ChrispinP** [comment]
Email rule setup for Mike. Updated Email workflow documentation accordingly

![image](https://user-images.githubusercontent.com/67915167/126690187-df699331-b0f4-42e3-8c14-284670293b44.png)

Ready to review

**Comment by TracyLinder** [comment]
@TracyLinder email mike as an FYI & close this.

**Comment by ChrispinP** [comment]
emailed Mike, closing
