### ISSUE TITLE
UC Folder: New Default People Types (ON PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5142]
### Update UC folder people types.

**Stakeholders:** Jaclyn, Greg Pepper

**Acceptance Criteria:**
- Applies to UC folder
- People type options on the people tab should be:
    - Applicant (new)
    - Contact (new)
    - Engineer (new)
    - Project Manager (existing)
- Remove people type 'Spons or Contact'

**Notes**
- No logic or portal updates required. Users just need to be able to add these people types to the folder manually when needed.

**Comment by TracyLinder** [comment]
AULCC Data workbook not pulling all people records:

![image](https://user-images.githubusercontent.com/49930868/106332230-fd7f9c00-624b-11eb-8368-497bc8f44dec.png)

**Comment by TracyLinder** [comment]
We'll be scoping this on 7/8/21 w/ Pepper, Isiah, and Jaclyn

**Comment by TracyLinder** [comment]
### Scoping 7/8/21

**Portal Options**
![Screen Shot 2021-07-08 at 1.03.48 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/191b0d3f-2639-4138-98d3-906779f48097)

**Comment by TracyLinder** [comment]
AC has been updated; this is ready for development.

**Comment by Nadin-Nader** [comment]
This was also a part of the incident Greg emailed about and was sent to CTM under INC0116652, which has been resolved.
@Nadin-Nader add to next sprint

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0153583 is submitted for DEV deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader The ticket is DEV deployed. I tested it and looks good. 

![image](https://user-images.githubusercontent.com/51680715/126554519-e03b461e-5d4c-417a-a2c8-0025aefa347b.png)

**Comment by Nadin-Nader** [comment]
@SubhaShroff looks good, lets go ahead and get this to TEST

## Approved for TEST deployment🙌🎉

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0153924 is submitted for TEST deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is deployed in TEST and it looks good. 

![image](https://user-images.githubusercontent.com/51680715/126701674-afabd374-fd26-40c2-998a-1b212104fe73.png)

**Comment by Nadin-Nader** [comment]
@SubhaShroff got approval from Jaclyn to send to PROD

## **Approved for PROD Deployment 🎉🙌‼**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  **SCTASK0154733** - PROD deployment plan is submitted.

**Comment by SubhaShroff** [comment]
### Status:
PROD Deployment is done. :)

**Comment by Nadin-Nader** [comment]
@SubhaShroff thank you. I will send an email to the stakeholders informing them that this is on PROD

**Comment by Nadin-Nader** [comment]
Email Sent to Greg P and Jaclyn L.:

> Good Morning,
> 
> Hope you are both having a great morning so far. I was reaching out regarding ZenHub card #5142, UC Folder: New Default People Types and wanted to let you know that it is now on PROD.
> 
> Please go ahead and verify that the New Default People Types are correct and visible and let me know the outcome. If all is well, I will go ahead and close the request.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services
> ————————————————————————————
> transportation.data@austintexas.gov 🚦 austinmobility.io

**Status:**

Waiting on Response from Greg or Jaclyn to either close the card or make adjustments

**Comment by SubhaShroff** [comment]
### Status:
Its on PROD and waiting on response from stakeholders.

**Comment by Nadin-Nader** [comment]
Everything is good according to Greg and Jaclyn. Closing card:

> From: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov> 
> Sent: Tuesday, July 27, 2021 5:02 PM
> To: Pepper, Gregory <Gregory.Pepper@austintexas.gov>; Nader, Nadin <Nadin.Nader@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: UC Folder: New Default People Types # 5142
> 
> Yup, it’s working great. 
> 
> Thanks
> 
> 🚧 Jaclyn Lozano - 6310 Wilhelmina Delco Dr., Austin,TX 78752 - 512 974 2412 - www.austintexas.gov/AULCC
> 
> From: Pepper, Gregory <Gregory.Pepper@austintexas.gov> 
> Sent: Tuesday, July 27, 2021 4:33 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>; Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: UC Folder: New Default People Types # 5142
> 
> I saw that!!! 
> Jac,
> Are we good? It seemed to correctly work for me! 
> Thanks y’all!!!
> 
> Respectfully,
> 
> Gregory Pepper
> Construction & Inspection Services Program Manager
> Utility Coordination Program Manager
> AULCC Chairperson
> 512-974-7282 Office
> 512-277-4787 Mobile
>
