### ISSUE TITLE
UC Enhancement: Email Template on Document Tab (Ready for PROD Deployment)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5145]
### When emailing folder documents from the UC document tab, I want the email subject to be useful, and to copy our workgroup. 

**Stakeholder:** Greg P.

**Acceptance Criteria**
- This applies to the UC folder, document tab (all documents)
- The email subject template should be: {Folder Name} - {Folder Reference #} - ROWID{RSN}
- CC: Aulcc@austintexas.gov, Folder Case Manager {Assigned user on process Permit Case Manager Review (51095)}

**Comment by TracyLinder** [comment]
@Nadin-Nader let's try to get this on deck for the sprint beginning 7/14 if possible.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan per Tracy, we are moving this to backlog for now

**Comment by TracyLinder** [comment]
Medium Priority

**Comment by Nadin-Nader** [comment]
Subha needs permissions added. She reach out to Jenice for more admin permissions on DEV

**Comment by Nadin-Nader** [comment]
@SubhaShroff looks like that all for now. Send it through

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0263000 is submitted for TEST Manual deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is deployed in DEV/TEST. I verified and its ready for UAT.

**Comment by Nadin-Nader** [comment]
Waiting on UAT form Greg or Jaclyn on TEST.

> From: Nader, Nadin 
> Sent: Monday, November 14, 2022 5:29 PM
> To: Pepper, Gregory <Gregory.Pepper@austintexas.gov>; Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>
> Cc: Shroff, Subhashini - Vendor <Subhashini.S@launchitcorp.com>
> Subject: UC Folder email template
> Importance: High
> 
> Greg/Jaclyn,
> 
> Hope you are both doing well. I am reaching out to inform you that there have been changes made to the email Template for the UC folder. The changes are on TEST and we need you to UAT and make sure it is correct.
> 
> It was applied to the following and a few others:
> 1.	UC - AULCC Data Workbook (Order-10096)
> 2.	UC - Case Manager Comments (10095)
> 3.	UC - Master Comment Report (9993)
> Please go ahead and verify and let us know if it is good to send to PROD. I added the link to the card below.
> https://github.com/cityofaustin/atd-data-tech/issues/5145
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> Product Delivery Manager
> Data and Technology Services

**Comment by TracyLinder** [comment]
### UAT Failed 2022 004381 000 00 UC
- documentrsn 27619664 didn't work
- Add 'Traffic Control Comments' as doc

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The fix deployment is done in TEST and I have verified the changes and tested. Its ready for UAT.

**Comment by Nadin-Nader** [comment]
Asked Jaclyn to UAT on TEST. If she cant i will try to ask Greg P. to UAT

**Comment by Nadin-Nader** [comment]
@SubhaShroff Jaclyn responded and she needs to check with Greg P to see if they need copies of emails that are sent:

> [5:40 PM] Lozano, Jaclyn
> That last part, CC the folder case manager? Might have to change to the person who's sending out the document.  Isn't that how it does it right now? Otherwise Isaiah is gonna be getting a lot of emails. And even then, I don't need a copy of the document sent to me lol. 
> 
> [5:42 PM] Lozano, Jaclyn
> Oh let me ask Greg first. 

Part that may change: 
** [5:40 PM] Lozano, Jaclyn 
That last part, CC the folder case manager? Might have to change to the person who's sending out the document.**

**Comment by SubhaShroff** [comment]
@Nadin-Nader As conveyed on Teams Jaclyn asked you for the following changes:

1. Remove case manager email id from CC
2. Add document name in Email subject: UC Data Workbook: Folder Name - UCC# - RSN. 

I am done with the changes and testing it on DEV. Once I prepare Manual deployment document, I will submit TEST deployment request.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I submitted SCTASK0269270 for Manual deployment of the above mentioned changes. Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Manual deployment is done. Ready for UAT.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been approved for PROD

**Comment by SubhaShroff** [comment]
@Nadin-Nader  [SCTASK0272417](https://atx.servicenowservices.com/sc_task.do?sys_id=b9386c751bb399d091528407624bcb0e&sysparm_record_target=sc_task&sysparm_record_row=1&sysparm_record_rows=1&sysparm_record_list=request_item%3D29382c751bb399d091528407624bcbb3%5EORDERBYnumber) is submitted for PROD manual deployment.
Thank you.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Anu is deployed it on PROD.

**Comment by Nadin-Nader** [comment]
Informed Jaclyn  That this was on PROD and working. Closing
