### ISSUE TITLE
Create an offboarding checklist

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5147]
We need a checklist in Gitbook which captures offboarding tasks for our team.

Deactivate accounts in:
- 1Password
- Slack
- Miro
- Vision Zero Editor
- Knack apps
- Github (remove from our team and re-assign issues)

What else?

**Comment by johnclary** [comment]
@dianamartin would you take the lead on setting up the wiki page for this and making sure it gets done? Please work with @amenity @mateoclarke @jaime-mckeown to capture tasks. Once it's done, let's run through this with Jace.

**Comment by dianamartin** [comment]
- [x] Created Off Boarding Checklist
- [x] Slacked team members to review what I started
-  Waiting for feedback to add additional tasks to the list

**Comment by dianamartin** [comment]
Offboarding check list created, we can iterate as needed. Closing.

**Comment by johnclary** [comment]
@dianamartin would you share a link to the offboarding checklist here?

**Comment by dianamartin** [comment]
[Offboarding Checklist](https://atd-dts.gitbook.io/wiki/offboarding/off-boarding-checklist)
