### ISSUE TITLE
Offboard Jace's Accounts

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5148]

**Comment by johnclary** [comment]
Blocked by [#5147](https://app.zenhub.com/workspace/o/cityofaustin/atd-data-tech/issues/5147).

**Comment by johnclary** [comment]
@amenity would you take the lead on this next sprint? @dianamartin can share a link to the offboarding checklist and you can assign tasks to others as needed to make sure we get Jace fully offboarded.

**Comment by dianamartin** [comment]
[Offboarding Checklist](https://atd-dts.gitbook.io/wiki/offboarding/off-boarding-checklist)

**Comment by amenity** [comment]
@johnclary @dianamartin - yep, on it.

**Comment by amenity** [comment]
- [ ] 1Password
- [ ] Slack
- [ ] Miro
- [ ] Vision Zero Editor
- [ ] Knack Applications
- [ ] GitHub (remove from team & re-assign issues)
- [x] Google Drive (revoke access)
- [ ] Fill out employee separation form - [Separated Employee Request Form (SERF)](https://atx.service-now.com/sp?id=sc_cat_item_guide&sys_id=72fb6289db9f73405b03f482ba961956) (Supervisor must complete)
- [ ] DTS email distribution list
- [x] About Us page #5181 
- [ ] DTS SharePoint team lists

**Comment by dianamartin** [comment]
@amenity I can look at the 1password stuff for Jace

**Comment by dianamartin** [comment]
# Disable access to Knack apps
- [x] AMD Data Tracker
- [x] HR Manager
- [x] DTS Portal
- [x] Finance and Purchasing

**Comment by dianamartin** [comment]
- John said the Employee Separation Form's been completed for Jace

**Comment by dianamartin** [comment]
@amenity is this issue completed, can we close it?

**Comment by amenity** [comment]
@mateoclarke — did you do the VZE account removal?

**Comment by mateoclarke** [comment]
Yes, I just deleted his account in VZE. Thanks for the poke, I missed this originally.
