### ISSUE TITLE
VZ ETL | Add case ID to demographics Socrata dataset

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#5149]
When investigating inconsistencies between the VZ Team fatality counts and the fatality counts in the demographics visualization of the VZV preview instance, it would be nice to have the case ID field available to export from Socrata since the [VZ Team QA/QC Sharepoint spreadsheet](https://cityofaustin-my.sharepoint.com/:x:/r/personal/lewis_leff_austintexas_gov/Documents/2015-2020_VZE%20QA-QC%20on%20Fatals.xlsx?d=weeca586a0a144989834e1b731b3c6676&csf=1&web=1&e=IYNAZ9) includes the case ID but not crash ID. The [VZ Demographics dataset](https://data.austintexas.gov/Transportation-and-Mobility/Vision-Zero-Demographic-Statistics/xecs-rpy9/data) has the crash ID but not the case ID. 

It is worth checking back to see if there is a reason why this is not included in the dataset before making the update.

- [ ] Update GraphQL people queries in VZ ETL to fetch the `case_id` (person record > unit > crash > `case_id`)
- [ ] Add field to both test and production demographics datasets through the Socrata UI
- [ ] Run ETLs to update datasets

**Comment by patrickm02L** [comment]
## 10/2

@mddilley is this something that we'd still want to look at for the VZV?

Chatting with @xavierapostol he said that it is included in the fatality tracking tool, and said that the crash ID that comes up on the popup is more accurate than the case ID.

**Comment by mddilley** [comment]
Yes! Thanks for including Xavier's thoughts on this because I was fishing around in my brain. 🙏 This one takes me back! The fatality tracking tool replaces the need for this change. 🎉 cc @roseeichelmann 👏
