### ISSUE TITLE
Add Filters to VZA Signal Locations picklists

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#5153]
From #2874 - Add filters to picklist in Forms for Arterial Management Scheduler.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/00a7cde1-c085-475d-822a-55217b6a1dbc)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/8205a317-9850-4ece-b745-e3b16460d99d)

**Comment by johnclary** [comment]
@SurbhiBakshi would an "is not" filter work? 

- Location Type is Signal Location
- Location status Status is not DESIGN
- - Location status Status is not READY FOR DESIGN
- ...

**Comment by amenity** [comment]
Sounds like we're not going to be able to help Billy here, for now, since most of their assignments require a sergeant and they have to be scheduled by Randy.

**Comment by patrickm02L** [comment]
Can we close this?

**Comment by johnclary** [comment]
Yes
