### ISSUE TITLE
Project: ROW Closures & Construction Data Platform

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5154]
A suite of tools which enable City staff to push road closure notifications to the public and navigation app providers.

### Background & Context
We are aware of the need for real-time road closure data and have fully scoped the [ROWMAN Phase 4 project](https://www.austinmobility.io/projects/422?tab=description) which is intended to solve this need. 

It's a big project, and includes a full integration with AMANDA as well as the workzone data (WZDx) feed for navigation app providers. Our notes estimate this as a six-month effort—but I think twelve months is more realistic given the number of systems integrations involved. We have contractor funding available for this, but work cannot begin until April (at the earliest) due to AMANDA v7 upgrade.

Jim D. has asked for an interim solution with the smallest possible scope and shortest time to delivery. As such, this work will seek to:
- Allow CPO contractors to report their closure information via a web form
- Allow the Mobility Management Center (MMC) to review closures and map them
- Leverage possibly existing Esri tools to transform the closures to a [Waze-compliant data feed](https://developers.google.com/waze/data-feed/road-closure-information), or, possibly, the [Work Zone Data Exchange specification (WZDx)](https://github.com/usdot-jpo-ode/jpo-wzdx)

### References
- Austin Finance Contract Information for the purchased product is [here](https://financeonline.austintexas.gov/afo/contract_catalog/OCCViewMA.cfm?cd=MA&dd=2400&id=NC240000013).

![Workzone Data Specification](https://user-images.githubusercontent.com/14793120/106485592-62b6d580-6476-11eb-8d74-40ee0d4969c5.png)

**Comment by johnclary** [comment]
Scoping meeting with Jim D scheduled for 2/2.

**Comment by TracyLinder** [comment]
@johnclary an index already exists for this. See #422

**Comment by johnclary** [comment]
Based on discussion with Jim today I'm renaming this to "Real-time Road Closure Notifications MVP." Next steps:

- Jim to schedule meeting with CPO to clarify their need and resource availability
- John to research what Esri tools are available to us
- Jen to research what feed specifications and closure types the navigation providers support

**Comment by johnclary** [comment]
Jaime and I met with Esri to review their road closures tool for ArcGIS Online. Jaime did some follow-up research to understand if/how we can use the Esri tool to create a Waze-compliant closure feed. Our understanding is that Waze is able to consume the ArcGIS Online data. 

Next steps are to meet with CPO to understand their needs and involvement. Waiting on Jim to re-schedule this meeting.

**Comment by amenity** [comment]
Had a OneNetwork demo last week. @TracyLinder will set up a meeting with Allyson and Lance to discuss next steps.

**Comment by TracyLinder** [comment]
ROW contacted me; they would like to consider Dot Map as a potential vendor for this project.

**Comment by amenity** [comment]
Ken B. from Finance's 11/23 email update:
>  I just spoke with CTM Purchasing; they are getting to solicit this shortly.  I made sure they include all the vendors that Stephanie notified me about.  I will keep you all updated on the process.

**Comment by amenity** [comment]
@moorerst completed the [preliminary real-time road closure vendor procurement process](https://github.com/cityofaustin/atd-data-tech/issues/8804). CTM will be handling procurement and @TracyLinder will [perform software evaluation](https://github.com/cityofaustin/atd-data-tech/issues/10921) while CTM manages the rest of procurement.

**Comment by TracyLinder** [comment]
### Update

Project stakeholders are meeting on 1/3/23 to select the best procurement method; IFB or RFP.

**Comment by TracyLinder** [comment]
### Update

We've decided to move forward with an RFI. Currently we're reviewing the SOW and hoping to get to solicitation ASAP.

**Comment by TracyLinder** [comment]
### Update
The project team has been working with COA Central Purchasing to identify the best procurement process for our needs. We decided the best first step is to post an RFI. Currently we are reviewing and updating the software requirements in the SOW. We hope to have this published for solicitation ASAP.

**Comment by TracyLinder** [comment]
### Update

The Request For Information solicitation has closed and the project team is analyzing the responses. We will put together an evaluation matrix and meet with the vendors.

**Comment by TracyLinder** [comment]
### Update

TPW will perform the final RFI responses review on 6/5/23 and evaluate next steps.

**Comment by TracyLinder** [comment]
I updated this project's DTS evaluation today.

**Comment by TracyLinder** [comment]
### Update & Closing

The product evaluations concluded that SADA's software Coordinate is the only software that offers tools/features specifically built for conflict detection/resolution and coordination features, and the only software that meets our needs out-of-box. City council [authorized the purchase on Oct. 19, 2023](https://services.austintexas.gov/edims/document.cfm?id=416779) and the [contract has been signed.](https://financeonline.austintexas.gov/afo/contract_catalog/OCCViewMA.cfm?cd=MA&dd=2400&id=NC240000013) We will now move on to the implementation project.
