### ISSUE TITLE
GIMOB Meeting - February

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#5166]

**Comment by jaime-mckeown** [comment]
- Homelessness (Heather K from ARR) Proposing a Homelessness Subcommittee. Mat P. had made a dashboard for all the homeless datasets, when he left it fell to Heather, she is looking for help.
- Starting having lot of technical issues, people could not get into meeting, then everyone was kicked out.
- Waiting to hear back from RoxAnne for a re-schedule.

**Comment by jaime-mckeown** [comment]
Re-scheduled for next Thursday.

**Comment by jaime-mckeown** [comment]
- Modernization Project
   - continuing to install Pro for Phase 1 users and uninstall ArcMap for 0 use licenses.
   - Phase 2 Kickoff next week.
   - COA needs to be at 10.7.1, departments need to upgrade. ATD is complete (need to double check with Scott)
   - Training classes have not been very full, will be opening up the classes to Phase 2, and possibly all other departments since we are wasting money.
- Homelessness GIS Data
   - Would like to create a Homelessness Subcommittee
![image](https://user-images.githubusercontent.com/48842809/107663847-6fdf7b80-6c51-11eb-89a8-72a4f2f4cc9b.png)
- GIS Speed Mentor / Mentee: Janny would like to propose a Speed Mentor/Mentee Event, 1 hour where people would speak with people for 10-15 minutes at a time. If you are interested, sign up for the virtual event.
https://forms.office.com/Pages/ResponsePage.aspx?id=9hleXKumRUux0L5GCKmmf1D4gfaqrP5IrRKIQK5dwWJUQUJBSlRXS1lQSlFKUUZIVlhVUFNCTzZMSiQlQCN0PWcu
- ArcGIS Online Subcommittee
   - Webinar coming up on 2/24
   - 1st quarter meeting coming up in March, date/time still TBA
   - Would like to update the Governance document again as AGOL changes so often
   - Planner Board under ATX GIS Teams group
- Knowledge Base
   - will be sending out a GIS Community Survey soon regarding the new platform
   - next quarterly meeting on 4/23
- Remote GIS Work: will be writing a test that will test all the different options that we are currently using to compare. Will be writing up recommendations based on outcomes to help departments find the best options. Trying to get a resource to help out with this if possible.
- Esri Credits: ~370 unallocated at this point
- Geospatial Data Services
   - Cathy W. retired, will be working on getting her position re-filled.
   - Have been testing the AMANDA v7 for upgrades
   - Almost everyone on the team has Pro installed, but not fully using it at this point
 - Esri Yearly Planning Meeting
   - John sent out an email regarding this meeting to the SPOCs regarding the yearly planning meeting
 - Geospatial Tech Management
   - Issues upgrading GISDM, do not have a new date yet
   - Trim the Esri authorized callers down. If you need to submit an Esri ticket, submit a CTM Service-Now request.
   - Upgraded FME to 64-bit, data with Attribute Rules can now be updated through Geodatapusher to GISDM
   - Ronnie M. retired
 - Training: changes had to be made since classes changed from 11 credits to 12 credits. 2 3 day classes now only have 1 class instead of 2. Approved by the board.
 - Esri has 10 seats for the Developers Summit, sign up on the Conference Spreadsheet within GIMOB documents under Training.

**Comment by johnclary** [comment]
thanks Jaime! I assume we'll start communicating ArcGIS Pro training to ATD once we kick off our upgrade? Any reason not to start sharing that more widely now, since you mention low attendance?

**Comment by jaime-mckeown** [comment]
@johnclary I haven't started communicating the ArcGIS Pro training to the department since part of the migration is to determine which users need to continue to use desktop software as they want the minimal desktop users to be move to AGOL only. I don't want to send people to the training if they really don't need it. I can look into the user reports and let those that are using desktop regularly know about the upcoming training sessions.

**Comment by johnclary** [comment]
sounds good. thanks.
