### ISSUE TITLE
Set up delegates in Robin who can accept reservations

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5170]
Delegate set up, 4-5 people can accept for reservation - Gilda, Stephen, Marisol
Create custom role "Delegate" to request and deny
get 2 emails from Outlook and Robin?
Meeting Room Approval
https://support.robinpowered.com/hc/en-us/articles/360035496232-Meeting-Room-Approvals-Google-O365-users-

**Comment by dianamartin** [comment]
@moorerst I created the "Delegate" user roles yesterday (2/1).
- Added Gilda, Marisol and Stephen

Have not tested since doing it though. I learned that I couldn't assign a desk unless I was a "delegate" so I added myself as a "delegate" to be able to do it and Stephen and I learned it together.

**Comment by dianamartin** [comment]
- Tested being a "delegate" user role
- Able to assigns staff to desks 

@moorerst I think we should figure out what an admin should be able to do v. what a delegate is. So we can make our recommendations for scaling up to expand to other departments

**Comment by moorerst** [comment]
set up the Delegate role with permission to Approve and Deny Space Request. Removed that permission from the Owner and Admin Role so only the Delegate Role has that permission. Tested and it's worked successfully. Closing issue
