### ISSUE TITLE
ArcGIS Pro Migration

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#5179]
ATD will be part of the Phase 2 departments that will be starting the official migration to Pro this year.

**Comment by jaime-mckeown** [comment]
@johnclary over the past month, I started working on the Project. Below lists what I have done so far:
- Sent out mass email to all ATD GIS Users letting them know that this project would be starting
- Got an updated GIS Installs list from Scott, there's always work to do with these lists as it only shows the last person that logged into the computer, so I have to do research to get it in order (this is why a Knack App would be great!)
- Going through the Usage Report for all users and adding notes to my Spreadsheet
- Fixed the Pro License mess after finding out that the super helpful Software Usage Report only tracks usage connected to the Concurrent License Manager (ATD had users on Single Use and Named Licenses).
- Received a current employee list from HR so I could properly group users under Divisions as Outlook is unreliable.
- Started emailing divisions separately, need to figure out what users would be keeping desktop software and which will be uninstalled. There are many installations that have had zero usage over the past year.
- As I'm hearing back from divisions, sending Scott lists of computers that need Pro installed or Desktop removed.
- Enrolling users in GIS TRAIN Classes as I hear back.
- Andrew started working on a Wiki that will include additional Esri training classes that will supplement the TRAIN classes and Learning Plans that CTM has created.

**Comment by johnclary** [comment]
thanks @jaime-mckeown!

**Comment by jaime-mckeown** [comment]
@johnclary update on Pro Migration:
- Continued emailing (meeting with some) Divisions regarding project, have finally gotten to all divisions. All have decided who will be keeping Desktop or moving to AGOL except TED.
- Met with Eric last Friday, he still needs to meet and discuss this with his group.
- Enrolled many users in 2 instructor-led trainings for this month.
- Continue to work with Scott to get Pro installed / Desktop removed for each division.
- PE, SM, and SMB are complete for Pro installs / Desktop removals
- Submitted DTS Request to create a Knack Form in the DTS Portal for tracking of ArcGIS installations, devices, and users. Meeting with Amenity and Diana today to discuss.
- Andrew has created 2 Wiki's that narrow down Esri Trainings from the Catalog
   - Pro: https://atd-dts.gitbook.io/atd-geospatial/arcgis-pro/training-page
   - AGOL: https://atd-dts.gitbook.io/atd-geospatial/arcgis-online/training-page

**Comment by jaime-mckeown** [comment]
- Continue to work with Scott to get Pro installed / Desktop removed for each division
- AMD, OSE, ROW, and SDD are complete for Pro installs / Desktop removals
- Registered more users for Pro TRAIN Classes
- Users that have attended Pro training are inquiring about how to start incorporating Pro into their processes, helping them to get started using Pro
