### ISSUE TITLE
Test COACD Login on test version of VZA

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#5183]

**Comment by amenity** [comment]
For troubleshooting #5047 ... will potentially help diagnose the undefined error [we're seeing in other Knack apps](https://github.com/cityofaustin/atd-data-tech/issues/5047#issuecomment-769332446) ...

**Comment by SurbhiBakshi** [comment]
Incident INC0082562

**Comment by SurbhiBakshi** [comment]
CTM set up ADFS on the test application. I and @dianamartin tested it out successfully. Teams messaged Ramon to see if he is able to sign in.

**Comment by SurbhiBakshi** [comment]
Ramon was not able to log in.
