### ISSUE TITLE
eCapris integration | Get access to subproject database views

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5194]
Get access to a Microstrategy view of subproject data:
- Subproject ID
- Subproject primary key
- Subproject name
- Subproject status
- Subproject responsible department
- Parent project ID
- Parent project Name

This is good start, pending a better idea of the financials we'll need access to.

**Comment by johnclary** [comment]
Sent to eCapris help:

> I am writing to request a Microstrategy database view for eCapris subproject data. At this time, we only need access to test/staging data.
> 
> We are in need of the following fields for all ATD (dept 2400) projects:
> Subproject ID
> Subproject primary key
> Subproject name
> Subproject status (or "open/closed", if that's easier)
> Subproject responsible department
> Parent project ID
> Parent project name
> Subproject modified date (if such a field exists)

**Comment by amenity** [comment]
@johnclary - are you still working on this?

**Comment by johnclary** [comment]
We have #9820 which is sufficient for now. Closing.
