### ISSUE TITLE
eCapris integration | Load eCapris data snapshot into Moped DB

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5196]
Pending [eCapris data access](https://github.com/cityofaustin/atd-data-tech/issues/5194) and some DB schema changes.

**Comment by amenity** [comment]
@johnclary - am I understanding this issue correctly as a one-time import while #5195 is implementing a standing data feed?

**Comment by johnclary** [comment]
@amenity exactly!
