### ISSUE TITLE
eCapris Integration | Implement project-specific hyperlink to eCapris

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5199]
As a project team member, I would like to easily navigate from Moped to a particular project's relevant information in eCAPRIS. 

Notes: 
- Many Moped projects are not tracked in eCAPRIS. 
- Not in scope now, but we later on we want to build in validation and use a sweet predictive-typing UI for editing the field.
- This appears to be the url pattern: `https://ecapris.austintexas.gov/index.cfm?fuseaction=subprojects.subprojectData&SUBPROJECT_ID=<my.subprojectid>`

Locations: 
- [x] _[Project summary](url)_ page
- [x] [_Projects_ page](https://moped.austinmobility.io/moped/projects), wherever a subproject ID is rendered in the eCapris column

Specs:
- Default hyperlink color and underline style
- Add the ["External link"](https://feathericons.com/?query=external) Feather [svg](https://github.com/feathericons/feather/blob/master/icons/external-link.svg)

**Comment by amenity** [comment]
@zappfyllc - please pull some examples here for @tillyw to use. 

To test this, you'll can create a few new Moped projects for actual projects from eCAPRIS. I copy them from Nathan's Access database, looking them up [in their map viewer](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=d6194f783b114453a70eb769853e390c).

I can step through this with you!

**Comment by zappfyllc** [comment]
@tillyw Here's some mock/test data for your testing when implementing the eCapris hyperlink. The subproject_id is included along with project name, project description, and start/end dates. [Mock Data with SubProject IDs](https://drive.google.com/file/d/1_czdguRJWOGCW80mBe5vK5fQI7R9i2k0/view?usp=sharing)

**Comment by amenity** [comment]
[Here is an example of CSS used to implement external link icons](https://github.com/cityofaustin/atd-data-tech/issues/5199). 
<img width="266" alt="Screen Shot 2021-02-23 at 11 48 46 PM" src="https://user-images.githubusercontent.com/1463708/108954536-8d89e900-7632-11eb-8850-bd9fec9fd50c.png">
