### ISSUE TITLE
Functionality to have Parking SR convert to Parking Work Assignment

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5204]

**Comment by dianamartin** [comment]
This may not be needed depending on what the stakeholder would like to do. I can foresee switching back and forth from SR and WOs to be no very streamline. 

We need to have a discussion with them to show them the new and improved SR process that includes the Dispatch Categories they tracked historically.

**Comment by moorerst** [comment]
@dianamartin have we determined this is not needed, we will move forward with the new SR process? If so can this be closed?
