### ISSUE TITLE
Rubric for project prioritization

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#521]
We need a way to prioritize projects to ensure that DTS resources are allocated in an efficient, equitable, impactful way. Having a standard rubric where we can assign points based on predetermined criteria would bring consistency and transparency to the process. 

For reference:
 - [A rubric the Austin.gov team made back in the day to prioritize departments transitions to the new website](https://docs.google.com/document/d/19i3c9gwMoRhZWKflvge4natqcsuIk3cYwA1bjK7J-fA/edit).
- @danielhonker and @sarahscottr are working on a [Service Access project](https://cityofaustin.gitbook.io/service-access/) focused on assessing services for accessibility and prioritizing services for redesign and digitization. Here is their [framework for prioritization](https://docs.google.com/presentation/d/16WAgW2fV5xxdtuvIoTtIf0y6YKOAUrpsihuGsOmRiiA/edit#slide=id.g5d0db05e8e_0_112) and the [factors they are considering in each bucket](https://airtable.com/shrWn1TrwCKi8Mp8o/tblqUpz9CiyxuX4U1?blocks=hide). 
- [Austin Strategic Mobility Plan](http://www.austintexas.gov/asmp) guides the City of Austin’s mobility-related policies, programs, projects, and investments for the next 20+ years.  
- [Austin Strategic Direction 2023](https://www.austintexas.gov/financeonline/afo_content.cfm?s=73&p=160) outlines a shared vision and six priority Strategic Outcomes.

- Draft intake/eval process from USDS Veteran's Affairs:
> # Headlines
> * **Project name** -
> * **Project owner/discovery lead** -
> * **Top user stories** - "As a [user], in order to accomplish [a goal], I need a [thing/change/feature/product].”
> * **Initial "Definition of Done"** -
> * How do we know when we're ready for the next iteration/phase?
> * What next steps or resources are needed to advance the goals of the project?
> * **Notable updates** -
> # Discovery or project roles/skills needed
> These are necessary skills for a discovery sprint. Please list proposed team members, their ~% commitment, the skills/role they fulfill, and any gaps we could help fill:
> * Project owner/discovery lead -
> * Design (e.g. user experience, visual, content, etc.) -
> * Technology expertise of appropriate flavors -
> * Policy savvy -
> * Product management -
> * Communication/presentation skills -
> # Key factors for choosing work
> * **Impact** - Does this improve the lives of veterans and their communities? (directly or indirectly) This should be a descriptive mission statement that explains the potential impact to Veterans. If a holistic sense of impact is unknown pre-Discovery, use any data available to you, & update as you discover!
> * **Team interest** - Who from USDS is interested in working on this?
> * **Fit for USDS VA** - Our skills and  [USDS values](https://www.usds.gov/values)
> * **Institutional support**- Who from the biz and IT will partner with us and continue to manage it post launch?
> # Additional factors to consider
> These help us evaluate the work and our options.
> * **Known** - How confident are we that we understand the shape of the problem? (Rate on a scale of 1-5?)
> * **Type of involvement** - What are different options for supporting the work?
> * DSVA Scopes/Discovery - What questions are you trying to answer?
> * DSVA Manages (BPA, BAC, Other Contract) - What are our acceptance criteria? How are we measuring success?
> * DSVA Supports (Other VA team)) - What needs to exist for us to feel comfortable stepping back?
> * **Estimated timeline, notable upcoming events** (especially new statutory deadlines, commitments made)
> * **Metrics** - Key Performance Indicators, metrics, data we can use to track goals
> * **Known risks** - What could lead to a negative, undesirable outcome for the project or people impacted? This is from lean product design that helps us identify red flags for further discovery (we don’t prioritize low risk; we track risk).
> # Reference links
> * GitHub repo, priorities.md, contract documentation, roadmaps and planning materials, key briefing materials
> * How can USDS folks best discuss or learn about the project? ex: slack channel, comment in issue, attend next biweekly meeting

## Tracy's Thoughts

**DTS Work Scoring System**

What is the purpose of scoring DTS work/issues?

- Determining a request's value, and prioritizing DTS work

- Should we have the purpose formally stated somewhere for any reason?

o Tracy's Thoughts: Yes, it should be stated formally somewhere (maybe project brief), so customers understand their place in the backlog, and DTS is able to defend its prioritization methods.

What work/issues should be scored?

- Projects, features, anything else?

What is our scoring method/approach?

- [Weighted Scoring](https://hygger.io/blog/prioritize-product-features-criteria-weighted-scoring/) -- based on scoring criteria

- [RICE](https://hygger.io/blog/4-powerful-factors-rice-scoring-model/) -- Reach, Impact, Confidence, Effort

- [ICE](https://hygger.io/blog/ice-method-helps-choose-better-product-features/) -- Impact, Confidence, Ease

When do we perform scoring?

- When completing the Project Intake Document during the Project Discovery Meeting?

o The doc may need updating to allow us to collect the scoring info needed.

o [Workflow Diagram](https://www.draw.io/?state=%7B%22ids%22:%5B%221CAxAypAhB8dve1FnthN4LvIyVfKpTFKA%22%5D,%22action%22:%22open%22,%22userId%22:%22104144569414369680128%22%7D#G1CAxAypAhB8dve1FnthN4LvIyVfKpTFKA)

o [Project Intake](https://docs.google.com/document/d/1hYIp2gMbeukzTsu7GF--mLwwKyQIE5FLtrKQZI0A5gY/edit#heading=h.b5b3w7oomxfq)

Does the scoring completely determine an issue's priority in the backlog?

- Tracy's Thoughts: We've had our discovery meeting, the scoring is complete.... What next? Will we reorganize the backlog according to the issue's score placement? Or will other things need to be taken into consideration?

- Add a step in the workflow diagram for prioritizing the issue?

SD23 & ASMP Discussion

- Determine the criteria that should be scored

- Who should be scoring these criteria?

o Us, or send it to ASMP staff to score?

**Comment by amenity** [comment]
@johnclary - please stick the USDS doc that you mentioned ☝️.

**Comment by johnclary** [comment]
@amenity donezo

**Comment by amenity** [comment]
Bring, Peggy, Leann, and Cole into discussions on how to quantify alignment with SD23.

**Comment by TracyLinder** [comment]
@amenity let's discuss this next Friday 11/1

**Comment by amenity** [comment]
Thanks, @TracyLinder and @JaceDeloney, for taking a first stab at this! 🔪🍰

**Comment by amenity** [comment]
@TracyLinder @JaceDeloney - [these "Action Tables" from the ASMP](https://drive.google.com/open?id=1TPQlrEMCecWNm7qLXVbk0f5vzk7iIiI4) might be an interesting reference for the assessment.
