### ISSUE TITLE
Delete "csr_flex_notes" from Signs & Markings - Mar 2021

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5221]
Received automated reminder to delete flex notes in Signs and Markings Operations PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings#data/object_172/records

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 01/01/21

Total Records: 10,689
To Delete: 3,699
New Total: 6,990
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/2c406811-6d48-4ff2-8770-75705ab883e8)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/a5f4a2b2-af32-4937-beed-3ad31114a495)
