### ISSUE TITLE
[TIA] Update Case Log Field options and Case Log Rules

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5224]
Update Case Log Fields from one (Type) to three (Category, Type, and Action). This allows us to provide better reporting in the future and allow us to provide more detailed case log details for reviewers. Additionally connected to the new Scope Submission object.

**Comment by ChrispinP** [comment]
completed, ready for review

**Comment by TracyLinder** [comment]
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/2d0d0238-18ea-4a33-8205-6a1c9ad06ffe)
