### ISSUE TITLE
Meeting: Internal Robin Configuration Review 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5231]
- Review 
- Floorplans
- Desk/Spaces Policies
- Populating People list for testing and phase 1 rollout
- Testing Plan
- Health Survey

Attendees:
Stephen, Stephanie, Scott, Diana

**Comment by dianamartin** [comment]
Scott needs to create new calendar for each hoteling desk in Barton Oaks.

**Comment by moorerst** [comment]
- Determined that we do not need to have a calendar for each hoteling desk. Scott will have all the calendars that were created for this purpose deleted.

- Received a list of possible testers from Gilda.

- Made updates to the Health Survey based on feedback from HR - tested the Health Survey and it works. It has been disabled for now.

- People list has been populated with ATD employees with employee as a Member

**Comment by moorerst** [comment]
closing as complete
