### ISSUE TITLE
Ability to disable custom Buttons or Knack Trigger Buttons

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5235]
Ability to disable custom Buttons or Knack Trigger Buttons from being clickable

**Comment by johnclary** [comment]
@ChrispinP would add more details to this issue description?

**Comment by mddilley** [comment]
I did some testing to disable Big Buttons which can be seen as an extra "Applications" button in https://atd.knack.com/test-feb-12-2021-rpp-residential-parking-permits-portal#home/. This was done by adding a class called `.big-button-disabled` and the following CSS. This should work for button templates from custom code and also Knack-generated buttons. For the Knack-generated buttons, we can use jQuery `.addClass()` to add this class or something similar to a target button.

The colors, etc. that we use can be adjusted too so it is clear to a user that it is disabled. Conditionally disabling buttons would take some additional code. Just a first step and definitely happy to look at more button types!

```css
.big-button-disabled {
  pointer-events: none;
  background-color: #f7f7f7;
}
```

**Comment by ChrispinP** [comment]
Working with Mike, we were able to successfully disable both Custom and Trigger buttons with JS and CSS.

For Trigger buttons, the JS:
`/****************************************************/
/*** Disable Trigger buttons from being Clickable ***/
/****************************************************/
$(document).on('knack-scene-render.any', function(event, view) {
  var $blockContainerButton = $(".block-container-disabled").parent();
  $blockContainerButton.removeClass("kn-action-link");
})`

the CSS:
`.block-container-disabled {
  width: 25%;
  border-color: transparent;
  border-radius: 4px;
  background-color: #cbcbcb;
  color: white;
  padding: 10px 10px;
  font-size: 18px;
  text-align: center;
  opacity: 0.6;
  display: inline-block;
  outline-color: transparent;
}`
and
`.disabled { cursor: not-allowed; }`

instructions for disabling a custom Big Button have been added to Gitbook:
`function bigButton(id, view_id, url, fa_icon, button_label, is_disabled, callback) {
  var disabledClass = is_disabled ? " big-button-disabled'" : "'";
    $( "<a id='" + id + "' class='big-button-container" + disabledClass + " href='" + url + 
      "'><span><i class='fa fa-" + fa_icon + "'></i></span><span> " + button_label + "</span></a>" ).appendTo("#" + view_id);

  if (callback) callback();
}`

the CSS:
`.big-button-disabled {
  background-color: #f7f7f7;
  opacity: 0.6;
}`

My testing has been successful and now both custom buttons and triggers buttons are now only clickable within the button area and can be disabled with JS and CSS.
