### ISSUE TITLE
Disable ability to schedule recurring meetings for conference rooms in Robin

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5241]
From Gilda - Question about the conference reservations. 

I played a little this morning reserving the Colorado conf. room and found out that in the reservation page you can select the option of “repeat” and it takes you to another page that allows you to reserve the room ongoing and could go with no end in sight.  Can we check on that please? 

For some instances in the cases of reoccurring meetings, we had established a procedure at Barton Oaks that rooms could not be reserved for more than 6 months (reoccurring meeting) and the administration (Stephen) could override that and extend it if the meeting was critical to operations (example: Management monthly meeting, ERC, etc.).

Let me know if this works.

**Comment by dianamartin** [comment]
Have been talking to Stephanie to figure out why, we had disabled a few rules before her demo. 

Stephanie
>Recurring is disabled but the Repeat option still shows up

**Comment by dianamartin** [comment]
We asked Robin about this and they said that the repeat and reoccurring is pulling from the Outlook meeting options. Even though Robin shows it when creating a request, the delegate can deny it and the user won't be able to book a space for repeating occurrences.

**Comment by dianamartin** [comment]
@moorerst Should we close this?

**Comment by moorerst** [comment]
closing this is complete
