### ISSUE TITLE
[Database] Update project statuses

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#5251]
[List of project statuses](https://app.gitbook.com/@atd-dts/s/moped-technical-docs/user-guides/project-statuses/)

**Comment by amenity** [comment]
@zappfyllc - Is this ready to go?

**Comment by zappfyllc** [comment]
@amenity just finished it and added the link for status. Moving to Backlog.

**Comment by sergiogcx** [comment]
This one was a breeze, PRs:
https://github.com/cityofaustin/atd-moped/pull/273
