### ISSUE TITLE
Update Production data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5254]
E.g. Fiscal Year, 
![Screen Shot 2021-02-10 at 4.52.43 PM.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/9e99a49c-6434-4900-a4af-a0dde8fb302d)

[Project Roles](https://atd-dts.gitbook.io/moped/user-guides/project-roles)

**Comment by sergiogcx** [comment]
This is done :)
