### ISSUE TITLE
Enhancement: Hydrate other project details tabs when any tab loads

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5255]
As a Moped user, want to quickly navigate between project details tabs instead of waiting for each tab to load when I click on it.

**Comment by johnclary** [comment]
@amenity FYI. I tagged this with 1.0 so it doesn't get lost in the shuffle, but it's not MVP.

**Comment by amenity** [comment]
@mateoclarke - no action necessary, but want to get this on your radar.

**Comment by amenity** [comment]
See #5309 for potential approach.

**Comment by amenity** [comment]
@johnclary - We discussed this with @mateoclarke in Dev Sync today. It seems like the current implementation has a few advantages, including the cleanliness of code. Caching the data, like you mentioned in #5256 might be a better approach if we're looking to improve performance.

**Comment by johnclary** [comment]
👍 closed.
