### ISSUE TITLE
[Enhancement] Cache data on all project tabs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5256]
When I navigate to, away, and back to the Team, Timeline, and Activity Log tabs, the app re-queries the API.

This does not happen on the summary page. Can we configure Apollo to cache the data for these other tabs?

[Screen recording](https://user-images.githubusercontent.com/14793120/107592456-a0340500-6bd2-11eb-9960-aa2b58cbeae5.mp4).

**Comment by johnclary** [comment]
@amenity is there a Project Summary backlog epic we should stick this in?

**Comment by amenity** [comment]
@johnclary - is this issue title maybe backward? It sounds like what you'd like is for data from the _other_ tabs to be cached?

**Comment by johnclary** [comment]
@amenity yes, title is not right. what's the right wording—"project tabs"? Agree it's not a bug. Attempted to rename it better.
