### ISSUE TITLE
Review Roles/Groups/Permissions in Robin

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5258]
Based on the meeting with Robin we need to have a strategy for Roles/Groups and Permissions

I'm visual so I had to poke around and try to make sense of it. 
I came with something like this.

 **Role**
Austin Transportation Department (rename existing Role 8700 Cameron)

**Group assigned to this role** 
Austin Transportation Department Employees - which contains all ATD employees

**Permissions for the Role Austin Transportation Department**
No Admin Management Rights

**Scheduling Rights**
Can book room at BO and Cameron Rd

**Desk**
Can reserve desk at BO and Cameron Rd

**Features**
People - allow users to view members of your organization
Not allow to view analytics
Allow users to request meeting services?

**Role - ATD Admins**
Admin Groups
Barton Oaks - Stephanie, Diana, Gilda, Stephen, Scott, Marisol
8700 Cameron Rd - Stephanie, Diana, Gilda, Stephen, Scott, Marisol
8900 Cameron Rd - Stephanie, Diana, Gilda, Stephen, Scott, Marisol

- this part is not working out because each of the groups is taking on the same role.
- Maybe each Admin Group has to have it's own role

**Permissions for Role ATD Admins**
Admin management
Some can Edit Billing
Some can View Billing

**Manage Desk and Spaces** 
for their specific building

**Additional Departments**
Each new department would have a:
Role - department name
Group - employees
Admin Role(s) and Admin Group(s)

**Comment by moorerst** [comment]
Examples
You’ll find a few common scenarios below. Remember that by default the Member role grants permission to book everything.

“Everyone can book everything in our organization”

Change nothing. The Member role allows this by default.

“Alice shouldn't be able to book anything except for on the 6th floor of Building A.”

Modify the default Member role, removing the ability to book all spaces.
Create a role that's allowed to book anything on the 6th floor.
Assign the role to a group, and add Alice to the group.
“People in the Marketing group can book anything on the 6th floor except for two rooms, Council Chamber and the Knight Conference.”

Modify the default Member role, removing the ability to book all spaces.
Create a role that's allowed to book anything on the 6th floor.
For that same role, add two exclusions for the Council chamber & the Knight Conference room.

**Comment by moorerst** [comment]
can't figure out how to override the Member Permissions

**Comment by dianamartin** [comment]
@moorerst I'll look into this and see if I can take away all the permissions as a member

**Comment by dianamartin** [comment]
@moorerst 

I removed any abilities under the "Member" user role because all new person will be given this default user role

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/ab061e41-c99a-47bc-b5e0-9ead29b16885)

I plan to make a user role for the "Testers", I've made a group for them already and added the people that Gilda emailed us a few weeks ago and added you and me to the list as well for testing. 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/be02faba-82f7-447b-bf45-3248efffb148)

**Comment by moorerst** [comment]
through trail and error we have Groups/Roles/Permissions in place for ATD/Barton Oaks and Cameron Rd
