### ISSUE TITLE
IT Support: Tablet troubleshooting with Parking Meters

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5259]
Gilbert M. 
Parking Meters

Emailed Scott
>The tablet is having this message is this something you can help me with.

I emailed with him and found out what the situation is: 

Jacob C. is using Collector app on the tablet, he adds a point and attachments. When he clicks on the attachment, he gets an error message 
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/40a7d80c-b319-4e00-a146-0ea514a82810). 
There is an option to "Download" and it attempts to download something, but the tablet then shows an error ![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/7de1872b-b138-4bd5-99c2-6c6ea4c08da4)

**Comment by dianamartin** [comment]
Called Gilbert in the morning to see what the error was and what steps he was doing to get there. I was able to set my tablet up so that collector would open for me and I was able to recreate the issue on my tablet as well. I could not get my test tablet to correct itself.
- Tested logging into ArcGIS Online via browser, it's do-able and the attachment can then be enlarge when in the web map, but there are far too many clicks and not technician friendly. 
- Attempted to uninstall Collector, then reinstall Collector and sign in and try again. Still caused the same errors. 
- Decided to factory reset the tablet, walked Gilbert through configuration steps. 

As I was walking through, I thought I'd reset my test tablet as well to re install a different profile on it. The set-up was going well until it asked for my credentials and then it said they were invalid.

**Comment by dianamartin** [comment]
- Danny responded with credential format for sign-in, that worked
- QR code he gave me worked and tablet configured
- Looks very similar to AMD profile
- Was able to replicate the issue in ArcGIS Online

* Admin Code is having issues.

**Comment by dianamartin** [comment]
I can't seem to figure this out..not sure if I should asked GIS people, CTM.

**Comment by dianamartin** [comment]
I posted another discussion in the ATX GIS - AGOL channel. I hope I'll get some feedback otherwise I'll have to create a CTM/ESRI ticket for this.

**Comment by jaime-mckeown** [comment]
@dianamartin is the attachment issue still happening? I only have a personal device and the attachments open fine there.

**Comment by jaime-mckeown** [comment]
@dianamartin for the tablets not allowing multiple users to login, did you try adding multiple federated accounts to the tablet? On my personal tablet, I was able to add my federated and the ATD Publisher account and switch between the 2.

**Comment by dianamartin** [comment]
@jaime-mckeown I believe it is. If you want to talk to the user, contact Gilbert. He's been trying to sign in another co-worker into a tablet and this was the issue. It happens on my testing tablet too. I had uninstalled the app, made the tablet go into factory settings and still nothing.

**Comment by dianamartin** [comment]
@jaime-mckeown the ATD Publisher isn't a federated account using SSO, while the named federated account does. That's why you could add both accounts.

**Comment by jaime-mckeown** [comment]
@dianamartin I know that, but I don't have access to other federated accounts...

**Comment by dianamartin** [comment]
Yes, I think that's the issue. Not sure if this is a CTM or ESRI question and who would answer it.

**Comment by jaime-mckeown** [comment]
I just emailed Gilbert about the attachment issue. I will submit at CTM ticket for that problem. Regarding the login issues, I will submit an Esri ticket. I'll keep you posted here.

**Comment by jaime-mckeown** [comment]
- Scott will be getting Gilbert a new tablet, hopefully this solves the attachment issues.
- Asked Diana to check out ArcGIS Collector on a city tablet. I discovered that the new version of Collector allows users to sign out of the App, but I was on a personal device. Diana will get back to me once she tests it out.

**Comment by jaime-mckeown** [comment]
Diana will be submitting a CTM Ticket to request a profile update for AMD, Parking Meters, Signs and Markings, and Parking Enterprise that will add ArcGIS Collector to the available Apps.

**Comment by dianamartin** [comment]
CTM Ticket created `INC0088371`

**Comment by jaime-mckeown** [comment]
ArcGIS Collector is available on the tablets.
- Diana tested and was able to view attachments.
- She was also able to sign out.

**Comment by johnclary** [comment]
@dianamartin how's this going?

**Comment by dianamartin** [comment]
@john CTM had added this to the profiles, I can see it on my testing tablet that I have. I messaged Gilbert on Teams bc Scott was helping him out that day (3/12), Gilbert was supposed to help finish the tablet configuration for this co-worker Jacob. 

>Scott told me to talk to you to make sure you were able to log in both Jacob and Wilber on to the ArcGIS Collector app?
He never got back with me. I can call him tomorrow to follow-up.

**Comment by dianamartin** [comment]
Gilbert has replied to say he'd get a hold of me on 4/6, but we ended up never syncing at 10 am like we discussed. I think I'm going to close this unless he brings up any new issues.
