### ISSUE TITLE
[BUG] Assign project personnel is not working in New Project workflow

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#5263]
**Describe the bug**
When adding project personnel, I get an error in production that mentions the workgroup is not found in the mutation for moped_proj_personnel_insert_input. _Please note that workgroup does not need to be in this mutation at all, as the workgroup attribute is for display in the UI and is originating from the moped_user: it does not need to be inserted into the moped_proj_personnel table._

**URL**
https://mobility.austin.gov/moped/projects/new

**What steps can we follow to reproduce the bug you are seeing?**
1. Add "New Project" within Production
2. Add a staff member to Project Personnel
3. Move to Step 3 (mapping) and click "Finish"

**Screenshots**
![Screen Shot 2021-02-15 at 7.34.21 PM.png](https://images.zenhubusercontent.com/5d8cf7301165610001736992/36c5e0a1-4402-4de4-a610-637c682675dd)

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [X] Major — can only perform work using a workaround
- [ ] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Additional context**
I believe @mddilley is working on implementing the new project personnel table (based on Material Table), so this may get caught when his code merges to main and into production, but logging this since it currently breaks assigning any staff to the project

**Comment by mddilley** [comment]
@zappfyllc Thanks for reporting this! 🙏  I assigned this to myself for this sprint since it is closely tied to my work on the personnel table work.

**Comment by mddilley** [comment]
This will be fixed when https://github.com/cityofaustin/atd-moped/pull/218 is merged.
