### ISSUE TITLE
Builder Huddle: DSDD operations tracker

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5270]
Attendees:
_Diana, Chrispin, Surbhi, John, Amenity_

We need a place where
- AMD can see the maintenance history for a particular DSDD
- TED can see the presence-of-DSDD history for a specific location
Installation & relocation are actually performed by SMB and tracked in Signs and Markings Data Tracker

### Solution
- New asset type in Data Tracker 
   - Object for devices
   - Track location history (potentially normal Knack address field, not canonical Data Tracker locations since these will add clutter and move frequently)
   - Billy can then associate Signals WOs with devices
   - Max will update locations based on installation/removal notifications from Signs and Markings work orders
- Continue to manage SMB work orders in Signs and Markings

### Level of effort
- 2 for builder effort on our prioritization matrix

**Comment by dianamartin** [comment]
We discussed back and forth what the we could do and talked about the proposed recommendations. 

- AMD wants to track asset: DSDD, and write work orders against the asset. See maintenance history of the devices.
- TED wants to track the assets DSDD and the historical locations of these devices. 

**FUTURE**
Thinking that the stakeholder will ask for a spatial component in the future

**BUILD PLAN**
- DSDD - object table (parent)
- connection to AMD Work Orders (This will show maintenance records of the device)
- DSDD locations - (child) 1:M (device - multiple install/removal locations)
