### ISSUE TITLE
Robin User Testing

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5272]
Set up Robin user training
Training via the bowser
Training via the mobile app

- [x] Gilda provided names for user testing

- [x] Send draft for browser user testing to Cari for review:
https://docs.google.com/document/d/15ESpZLwVe6bYeZQDJVEEhQ6pOYfWd-52IlPxU2jn6lw/edit#

- [x] Send draft for mobile app user testing to Cari for review:
https://docs.google.com/document/d/1CtbZ_OddrB3NYwKQVr0u7dQfKa0pbO3mBYI9xjaJx6k/edit#

- [x] Email to be sent to testers

- [ ] Need a feedback method

**Comment by moorerst** [comment]
From the mobile app I can't book anything pass the current day. Get message The Office is closed now. See Hours 
when you look at the hours they show M - F 7am - 6pm

**Comment by moorerst** [comment]
@dianamartin I updated the testing instructions for the mobile app. Please review.
https://docs.google.com/document/d/13WbAuFYm_bd6xofIeRVSANrGTLyYxm-2LhSjt35j8PI/edit#

issues I experienced from the mobile app
Spaces not showing for Barton Oaks
Desk at Cameron Rd. have no amenities attached - will ask Stephen/Scott to add those

**Comment by moorerst** [comment]
Answers below:
1.	Can you send an example of an Admin who is still receiving these requests? It looks like you've removed this permission from the Admin role, so without more information I'm not sure what the issue is.
2.	This "office closed" banner is a bug. Our engineering team is working on resolving it, so I will update you when that ticket is closed.
3.	All of these spaces (with the exception of the Mother's Room) have been set-up as On Demand or Request Only. On Demand spaces can never be booked via mobile or dashboard, and can only be booked if attached to a room display. Request Only spaces (as noted in mobile app if clicked on) must be booked in the dashboard. I've looped in our Support team though to help figure out why the Mother's Room (set up as a Scheduled space + paired with a resource calendar) is still displaying as gray in mobile.

Jerther here with Robin support. I'd be more than happy to offer some additional insight in terms of the behavior you're seeing here.

Let's start with the space approval notices. I've reviewed the users on your account who have admin access and it looks like they're being sent the notice because of the permissions that they've been granted under the ATD Barton Oaks Admin, Delegate, and ATD 8700 Cameron Rd Admins roles. Please see the attached screenshots of where you can locate the approval setting within the roles towards the bottom. When this is enabled for the given role the admins will all be sent the notice. Keep in mind that this will apply to spaces that are designated as Request Only which we share more about in our guide here. You can make adjustments under the roles as needed.

**Comment by moorerst** [comment]
@dianamartin I completed the two surveys for you to review/edit
[Mobile App Survey](https://forms.office.com/Pages/DesignPage.aspx?fragment=FormId%3D9hleXKumRUux0L5GCKmmfzH995p7JkFAoX5m0wOxVpVUNVBRSElDWEE4NzJWSkhLUlYwVkVTVEhUVS4u%26Token%3De667404e103445b393d9fc6e1371a51d)

[Desktop App survey](https://forms.office.com/Pages/DesignPage.aspx?fragment=FormId%3D9hleXKumRUux0L5GCKmmfzH995p7JkFAoX5m0wOxVpVUNzA3SUZRMUhTOEgwMzdLSVVDSlhYTEJLQS4u%26Token%3Dbf38b0bb24a64f4eb64be18dbbc7f6da)

I updated the testing instructions for you to review/edit:
Mobile app - added Note regarding the "Office Closed" bug
Desktop app - added Note regarding use Chrome not IE

**Comment by moorerst** [comment]
3/3 sent email to 4 groups of testers - test instructions which include link to survey
Barton Oaks - desktop
Barton Oaks - mobile
Cameron Rd - desktop
Cameron Rd - mobile

testing complete 3/10

**Comment by dianamartin** [comment]
@moorerst Are we still testing this week or are we just now compiling the feedback we received from testers?

**Comment by moorerst** [comment]
distributed Robin User Testing results to stakeholders 3/15
https://docs.google.com/document/d/1ZoQNS-8k9CVHak-baaN1mTvaIAUJMM5Sm1dhemyRy_4/edit#heading=h.rqimlh3z59

Will follow up with a technical document addressing some comments from the survey and other questions:
How to cancel a reserved space?
Outstanding questions:
Will we assign employees to their desk which will result in them getting a Health Check survey via email daily if the survey option is enabled.
Request directions for Next Steps for rollout
