### ISSUE TITLE
AMANDA User Nazlie S Update

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5278]
**Update Nazlie's permissions so she can manually update the folder status on TIA.**

**Comment by Nadin-Nader** [comment]
@TracyLinder Spoke to Nazlie and logged into AMANDA V6. i added all folder permissions to the EV, SP and TIA, then had Nazlie test. It was successful. I will add the UPROD to have the account automation update her PROD account and create a Ticket for her to be a Power User on V7.

**Comment by Nadin-Nader** [comment]
Spoke to Amita and she told me that if a user needs to have their permissions updated in V7, to send her the changes and she will make them. She was able to upgrade Nazlie's Security Group from 50420 to 50430.
Nazlie is now a Power User in V7 TEST, V6 TEST and will be a Power user after tonight on V6 PROD when the automation runs. Closing Card
