### ISSUE TITLE
AMANDA User Permissions Update: PSM

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5280]
gonzalezmi needs power user permissions on PSM folder.

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please look at the old ROW user permissions doc & add the other users who need PSM permissions to this issue please?

**Comment by Nadin-Nader** [comment]
[https://app.zenhub.com/files/140626918/c5d3e9cb-3833-4a47-8046-f4bb637d9d96/download](https://app.zenhub.com/files/140626918/c5d3e9cb-3833-4a47-8046-f4bb637d9d96/download)[https://app.zenhub.com/files/140626918/7629d1de-81b2-40ce-a349-ed5780db2181/download](https://app.zenhub.com/files/140626918/7629d1de-81b2-40ce-a349-ed5780db2181/download)

**Comment by Nadin-Nader** [comment]
@TracyLinder I was able to update everyone's AMANDA PSM Button permissions that was on the list and needed to be updated except for Ryan Mooney. He has an Admin profile and that requires for his request to go to CTM as the AMANDA ADMIN Login is needed to make changes to Admin accounts. The automation cannot do it. 
I created a **SCTASK0123336** for it. Adding the awaiting response label so we know we are waiting on CTM

## **Status:** 

Waiting on CTM to update Ryan's button permissions

**Comment by Nadin-Nader** [comment]
Email from CTM to Ryan (he was the last account needing the PSM update, his account was an admin):

Hello Ryan,

In regard to the ticket to add button permissions for PSM, they have been added to your account. Please log out and back into AMANDA to see them.

Let me know if there are any issues.

Thank you,
Andrea Guerra - AMANDA Support
City of Austin - Communications and Technology Management 
Office: 512-974-2803

Closing card
