### ISSUE TITLE
Identify DSDD data source and prepare for import

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5287]

**Comment by johnclary** [comment]
@dianamartin take a look at the StreetsOnCloud export. Once you have a template figured out you can pass the data entry to Max.

**Comment by dianamartin** [comment]
Am going to sync with Max this afternoon 3/5 at 3pm, to ask him which data he believes to be more accurate. Streets on Cloud or Spreadsheet.

**Comment by dianamartin** [comment]
Max was able to log into StreetsOnCloud and find a place to download active DSDD units/locations, he downloaded it and I will import that 60+ locations into the system.

**Comment by dianamartin** [comment]
To Do
- format spreadsheet to Knack field headings

**Comment by dianamartin** [comment]
Imported 60+ unit records from Streets on Cloud download from Max, some information was missing like the door serial #s. I was populating those fields from the previous spreadsheets I was working with. Primarily the permanent unit records I had QC'd. 
- Max has looked at the ones I imported and he thinks they're correct
- He will start working in the system and populating the missing serial # from the doors
- Reviewing his DSDD Deployment log and creating his "Pending" queue of DSDD locations
