### ISSUE TITLE
Meet with Max and Billy to review new DSDD workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5289]

**Comment by dianamartin** [comment]
@amenity I think we need to set-up a meeting with Max and Billy before I can implement the WO association to the DSDD asset. Read more here #5291

**Comment by amenity** [comment]
Thanks, @dianamartin — scheduled a meeting for 3/26.

**Comment by dianamartin** [comment]
@johnclary What were your concerns/questions about this? 
- Ask Max who is creating work orders? 
- Ask Billy how he wants the work orders to come in?

**Comment by dianamartin** [comment]
- Scheduled a short meeting with Billy, 4/2 - to ask about work flow. 
- Plan on messaging Max about who actually sends maintenance requests to Billy - TED engineering associates or him

**Comment by dianamartin** [comment]
# Meeting Notes with Billy - 4/2

We discussed the `Unassigned` - work order status 
- In Data Tracker Billy says he reviews work orders daily, especially the `Unassigned` queue
- He's imagining that he'd continue to review that page and catch "new" work orders that are DSDD types. 
- Thinking that a new column for the `DSDD` asset would be added to that "Unassigned" work order page or somewhere on the `Description`.

## Current DSDD Process: 
- Email from Daniel/Max
- Email usually says something like
>I need you to look at this DSDD on this road, reported as not working
- Billy forwards email to technician and AMD supervisors
- Billy also calls technician, says
>you have an email to review DSDD, asks them to reply to email thread

This new process would be converting the email process to AMD work order process
