### ISSUE TITLE
Meet to Review TDSD Unified Comment Tracking App

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#529]
Scheduled for 9/4

**Comment by TracyLinder** [comment]
@johnclary can you provide more info on this? When are we meeting, or have we already?

**Comment by dianamartin** [comment]
@TracyLinder We had the issue description say the meeting was scheduled for 9/4. It was a Dev Review that John, Surbhi and I meet this week.

**Comment by johnclary** [comment]
@TracyLinder yes sorry we left you out—meant to include you. i'm sure @dianamartin can give you access if you want a sneak peek.
