### ISSUE TITLE
Meeting/Demo: DSDD maintenance work orders

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5290]
Scheduled meeting for 4/16

Discuss: 
DSDD maintenance work orders, the process, expectations, behavior and any feedback

Attendees: 
Amenity, Billy, Max, Diana

**Comment by amenity** [comment]
@dianamartin - should we tee this up for our next sprint?

**Comment by dianamartin** [comment]
Yeah, we're almost there. I've configured it in Test, I just need Billy to look at it then we can schedule something.

**Comment by dianamartin** [comment]
@amenity I repurposed this issue and schedule the meeting

**Comment by amenity** [comment]
- Max has already done a rotation, worked well but don't have the motherboard number (Diana found it in Daniel's OG spreadsheet)
- No more emails
- Really quite intuitive
- 

Need the motherboard serial when communicating with TrafficLogix 

New DSDD form
- First people to see them are Billy's crew
- They'll communicate the serial numbers and asset ID to Max 
- Max fills out the form

New work order
- Max fills out small subset of information, remaining data is automatically pulled
- Work Order looks like all the other work orders
- Billy fills it out 

When a follow-up is needed, e.g. a new motherboard — happens about 1/4 of every trip
- AMD creates a "follow-up needed" 
- Billy creates the follow-up work order
- Assuming it's under warranty (almost all the time) Edward Garcia will call TrafficLogix to get motherboard 
- Max does not need to be directly involved, but should be notified when it's _**closed**_ so he knows it's able
    - What was wrong with it
    - The asset #

New issues
- Add retired DSDDs
- Need to configure follow-up work order workflow to capture specific asset 
- Max should get a notification for follow-up workorders created

**Comment by dianamartin** [comment]
@amenity I created a new issue for the testing and email configurations I need to do
