### ISSUE TITLE
Moped File Upload | CloudFront PR Deployment Pipeline

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#5300]
We need to deploy PRs to S3 using GitHub Actions.

Subdirectory deployments:
- We need to patch anything with "/moped" to "/pr-123/moped" during the build.
- Create a folder in S3 under the name "/pr-123"

Subdomain deployments:
- No need to patch configuration.
- Create a folder in S3 under the name "/pr-123"

**Comment by amenity** [comment]
@sergiogcx Do you think this is a must have for Moped 1.0, or can it be addressed later on?

**Comment by sergiogcx** [comment]
No longer necessary for Moped 1.0 with new cookie arrangement. Closing.
