### ISSUE TITLE
Moped File Upload | Cookie Storage Management

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#5302]
Cookies are isolated per domain/subdirectory. We need to make sure AWS Amplify is fed the right domain/subdomain configuration settings at the time of deployment, or make it aware of where it is being run.

- Test subdirectory isolation (DevOps: How will AWS Amplify know what subdirectory the app lives in?)
- Test subdomain isolation (DevOps: How will AWS Amplify know what subdomain the app lives in?)
- Test local does not store cookie.
- Test deployments.

References:
- https://docs.amplify.aws/lib/auth/manageusers/q/platform/js#managing-user-attributes
- https://aws-amplify.github.io/amplify-js/api/interfaces/authoptions.html

**Comment by sergiogcx** [comment]
Probably the simplest form I could think of, moving this to backlog given the complexity.

![CloudFront-Cookie.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/65ad0e19-c63a-43b2-82ed-46e6da65df74)

**Comment by patrickm02L** [comment]
@amenity We discussed this at grooming 12/22, and @johnclary gave the go ahead to pull it On Deck for this Sprint.

**Comment by sergiogcx** [comment]
This is done, it requires extensive testing:
https://github.com/cityofaustin/atd-moped/pull/507

**Comment by sergiogcx** [comment]
Changed to 8, the complexity is very high in terms of design. It has taken months of work and thinking, but thankfully things have worked out recently (in the past two or three days).
