### ISSUE TITLE
Moped Editor | Look into Apollo Link for Global error handling

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#5305]
@mddilley made some really good comments about using Apollo Link to globally handle errors (including JWT errors) without the need of wrapping up components (as we currently do). We need to spend some time to fully grasp and test Apollo link in moped, it would be very useful.

Thread:
https://github.com/cityofaustin/atd-moped/pull/219#pullrequestreview-597766794

Apollo link:
https://www.apollographql.com/docs/link/links/error/

**Comment by amenity** [comment]
@sergiogcx will you add an estimate to this

**Comment by sergiogcx** [comment]
As it turns out there is a great article written by Hasura on how to use error links and interface directly with Hasura via GraphQL:
https://hasura.io/blog/handling-graphql-hasura-errors-with-react/

The problem with this pattern is that we are using a newer version of React Router (v6), and we do not exactly follow the same patterns they suggest in the article. It's a bit more difficult to use something like a `navigation` function or `props.history.push` because those need to be used under the Router context.

I've been thinking of using Context, but not sure how that's going to look in the rest of the chain.

For now, I've settled with a custom pass-through component that should detect if there is an expired JWT-Token and redirect to the root /moped path to attempt reloading.

**Comment by sergiogcx** [comment]
This is the PR:
https://github.com/cityofaustin/atd-moped/pull/256

This is the PR live preview:
https://deploy-preview-256--atd-moped-main.netlify.app/moped/session/signin

**Comment by sergiogcx** [comment]
I am gonna close this issue, we don't need links we can use React's Error Boundaries
