### ISSUE TITLE
Implement all proposed Material Table customizations in "Project team" panel on the Teams tab 

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#5308]
Before we start using Material Table in too many places, let's get the styles, custom buttons, and icons aligned to keep a consistent UI. Right now, this library is used in the Project Team tab and the Project Timeline tabs (phases).

See Mateo's comment here:
https://github.com/cityofaustin/atd-moped/pull/218#issuecomment-785390970

**Comment by amenity** [comment]
Will be covered in https://github.com/cityofaustin/atd-data-tech/issues/5375.
