### ISSUE TITLE
Update ATD SharePoint - Remove Emgage Menus to Modern Page Menus

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5311]
David G./Bert B. 
CTM 

Received an email about how Emgage Menus were going to be retired. 

## Email
>Your Intranet site/department site and the top navigation which it uses - this will need to be updated by the end of the year (earlier the better).

>At the end of the year, we will no longer being renewing the license for the 3rd Party MegaMenu provider called Emgage.   This is the top navigation provider for your site listed below.  Your site is using this Emgage add-on and it will need to be replaced with the Out-of-the-Box Modern SharePoint Megamenu.   

>This email is just to give you a heads up for your planning purposes.  If you have additional questions, please let me know.

### Deadline
October 1st, 2021

**Comment by dianamartin** [comment]
Emailed Bert
>I remembered seeing this after talking with David. Are you able to help me figure out how to remove the Emgage menus?

**Comment by dianamartin** [comment]
Talked to Jeff S. from WPD about the Emgage Menu migration. It seems to be intertwined with SharePoint Modern pages. 

# Notes
Emgage Menu
- Different role 
- Monitoring SharePoint site

**Process**
- 1 Hub - broken down by division
- Support Services
- 5 teams
- Finance - meet with them: Classic

What's needed and what can go away

Rebuilt the whole thing from scratch
ShareGate - Classic to Modern
Rebuilt the pages and migrated the data

Cleaning up stuff they needed

Classic has no hubs
Modern site - to connect to other site

CTM to create a HUB
Tenant Admin to create a Hub Site

- I created a CTM HD request once I found out that they are the only folks that can create a Hub site
- Reached out to Jacque D. from PWD bc she's going through the PWD Modern page migration
  - I wanted to see what I could learn from her since she's currently migrating and rebuilding pages

**Comment by dianamartin** [comment]
Should follow up with Bert on this to show him the mega menus I've created on the Hub site

**Comment by johnclary** [comment]
Diana is talking to Spoorthy this week to figure out which options are viable.

**Comment by amenity** [comment]
:tada: Complete.
