### ISSUE TITLE
Bug: TIA MOD - Portal Breadcrumbs 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5312]
### The breadcrumbs are back

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/401d07aa-6ca9-4f4d-b69c-b1a10bbd983d)

**Comment by ChrispinP** [comment]
May have occurred when the Javascript was being edited yesterday. Double checked JS and submitted a new request. No issue.

complete
