### ISSUE TITLE
Remove columns from "Projects" table

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#5314]
Staging link: https://mobility.austin.gov/moped/projects

**Remove columns**
- [x] Capital Funding
- [x] Date Added

**NOTE TO QA/PRODUCT/DEV**

Let's check for regression with exporting the data from these columns that are just added. Not sure how that will work (maybe it will be fine, but just making a note!).

**Comment by zappfyllc** [comment]
@amenity please feel free to add/remove details and/or combine this with other project table enhancements.

@tillyw #5309 is related to this same effort, so feel free to partner with or punt to @mateoclarke if anything's unclear

**Comment by amenity** [comment]
Thanks, @zappfyllc!
 
Updated "Personnel" to "Team" :) ...that said, I'm concerned about legibility if we show everyone's name for each project on this page. 😬  Having all the roles in parenthesis will look cluttered and if we use a new line for each we will risk project rows being really high and having to scroll lots. 

I know it's a deeper DB dig, but I'd prefer to see a comma separated list of (project team members') Workgroups instead. 

Then maybe we can add a way to search by personnel name via Advanced Search?

**Comment by amenity** [comment]
@johnclary - I think you suggested we might remove the edit_road icon and just have the project name be a hyperlink to the project summary? This would save some space and also be a bit clearer, conceptually, since people are not only going to be clicking to edit the project but also just to look at it. 

In Material Table, you click the pencil icon on the lefthand side of a row to edit in place and I think that's a good pattern to stick to.

**Comment by zappfyllc** [comment]
@amenity not at all attached to the project roles being in parentheses and added to that list: I am anticipating that request from ATSD and can understand the use case there (e.g. user searches for a project by a street name or keyword that generates 5-6 results and wants to see who the P.E. is for those projects without clicking into each project details page).

If we agree on comma-separating the list of team members in the Team column here, then I think we're good for now and we can wait for that request when it comes. Otherwise, if we want to discuss more, I'd say let's just break this out into a separate issue and I can write a user story with some examples and we can put that in front of a few stakeholders to see what they think.
