### ISSUE TITLE
Create and publish intersection points as vector tile

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5318]

**Comment by alan-deanda** [comment]
@mddilley [here](https://austin.maps.arcgis.com/home/item.html?id=ce1045ba695c4e4680f2e9508e685848) are the intersection points Vector Tiles. The only field I added to it was an ID field, and all intersections and endpoints from the CTN are in it.

**Comment by alan-deanda** [comment]
Need to add `PROJECT_EXTENT_ID` field and values

**Comment by alan-deanda** [comment]
Republished with `PROJECT_EXTENT_ID` field [here](https://austin.maps.arcgis.com/home/item.html?id=7b895583e6df45c88463a5c1da50c84e).
