### ISSUE TITLE
Extend project extent mapping to include points

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5319]
To start exploring project components, we will begin by adding a vector tile layer of intersection points to the project extent map.

- [x] Add [new CTN vector tile layer](https://austin.maps.arcgis.com/home/item.html?id=0d892e2cbfa24441ad501e26a810ece4) to project extent map
- [x] Add [new Project Components vector tile layer](https://austin.maps.arcgis.com/home/item.html?id=ce1045ba695c4e4680f2e9508e685848) to project extent map
- [x] Style with [Mapbox spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#circle)
- [x] Test out toggling layers in UI
- [x] Update Project Summary map to display all layers in project

**Comment by mddilley** [comment]
Updated the map with the [new vector tile layer](https://austin.maps.arcgis.com/home/item.html?id=9ba4f2cdab98467881460f59ad5a5f71) and have been unable to replicate the duplicate point IDs bug. I will request review on https://github.com/cityofaustin/atd-moped/pull/236 so I can merge and close this issue.
