### ISSUE TITLE
Republish CTN-derived vector tiles with additional attributes

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5320]
, e.g. Street Name

**Comment by alan-deanda** [comment]
Mike, the new CTN Vector Tiles with Street Names and Address Range live [here](https://austin.maps.arcgis.com/home/item.html?id=0d892e2cbfa24441ad501e26a810ece4)

**Comment by amenity** [comment]
Thanks, @alan-deanda! @mddilley - updated #4942 with the link for ya. Spike away! 🚀
