### ISSUE TITLE
Project: Develop UI + Workflow for Markings 311 SRs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#533]
# Summary
We have been asked to develop a module in the Signs & Markings Ops app to manage markings 311 issues. It will be very similar to the existing Signs module, in that staff can update/close SRs, as well as issue work orders from the SR. 

# Desired outcomes

# Notes

# Resources
- [Project folder](https://drive.google.com/drive/folders/1LeRoQgYhPG7kNiZbvjzfr-1RkLNZ15E8)
- [Github issues](https://github.com/cityofaustin/atd-data-tech/labels/Project%3A%20SMB%20311%20Module)

**Comment by amenity** [comment]
Let's shoot to get started on this in Sprint 11. 🎯 🏃‍♀️
Resizing per @johnclary's estimate that this will take a week of @dianamartin's time.

**Comment by dianamartin** [comment]
Talked with stakeholder and John and we are planning for a Go Live date of 1/6/2020.
