### ISSUE TITLE
TIA Mod Case Status' Update

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5337]
**TIA Case Status Details**

- Upon application submittal: Needs Case Review
- Upon beginning scope/submission: Under Review
- Upon rejecting scope/submission: Pending Customer Action
- Upon approving scope: Pending Customer Action
- Upon approving submission: Pending Memo
- Upon case completion: Approved

**Comment by ChrispinP** [comment]
Statuses have been updated.

complete

**Comment by TracyLinder** [comment]
I re-opened this & put it in Review Q/A so I can do some UAT on it soon.

**Comment by TracyLinder** [comment]
Reviewed with team. This is looking good. Closing.
