### ISSUE TITLE
TIA MOD BUG: Attachments Table on Case Log Not Populating

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5339]
### Example [here](https://atd.knack.com/development-services#view-tia-requests/tia-request-details/6036d2a21d2d28001bf15898/tia-case-log/6036d2a21d2d28001bf15898/)

**Comment by ChrispinP** [comment]
I believe this may have been a result of a specific case issue or setting or no new attachments yet being added to the case outside of the application process. Case logs are appropriately showing up as intended.

No issue, closing
