### ISSUE TITLE
Signs Work Orders: Increase "Add Location" Button Contrast

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#534]
It's hard to see the "Add Location" button from the map on the Signs Work Order details page. Let's increase the contrast to optimize for use outdoors. E.g., White button with black text.

![Screen Shot 2019-08-28 at 10.29.05 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/1625c736-8c6d-49e0-844c-fa89e8e372b6)

**Comment by mateoclarke** [comment]
Issue moved to [cityofaustin/atd-knack-signs-markings #218](https://github.com/cityofaustin/atd-knack-signs-markings/issues/218) via [**ZenHub**](https://www.zenhub.com/)
