### ISSUE TITLE
Data Migration | Test migration of a sub-set of IMPD data

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#5345]
[Previous Spike/Research](https://github.com/cityofaustin/atd-data-tech/issues/1645)

Potential Solution (to be discussed):

- [x] Identify subset of IMPD data needed (tables, columns, etc.) - JD
- [x] Identify current state gaps vs. ideal state for data described above (i.e. Moped data structure) - JD

Additional issues:
- [x] Write script to transform IMPD data based on analysis above - TBD
- [x] Migrate newly transformed data to new Postgres instance of IMPD (not to be confused with Moped) to generate seed data to test locally (not sure if we need to migrate this to Postgres, but I recall Sergio mentioning that exporting out seed data was easy once data was in Postgres?)

Notes:

- As mentioned in previous spike/research, we are not planning an integration with Access but a sequence of ETLs from IMPD into Moped with subsets of data needed for Moped features. Reduce the risk of a waterfall migration by testing the ETL and slowly adding additional schema/data over time.
- [FullConvert](https://www.fullconvert.com/) will migrate data from Access to Postgres in a 1:1 match with the schema, with some features supporting schema transformation. TBD on schema transformation efficacy here. FullConvert's pricing is $699/single user for its base plan (unsure about schema comparisons at this level) and $1499/single user for its pro plan which offers schema comparisons.
- Having examined the IMPD data, the transformations happening to get the data from IMPD's state to Moped's state will be significant, albeit lots of wording changes and fewer data type conversions (though there will undoubtedly be some of these).
- We do not need to migrate tables that represent picklist or lookup values, though this will need to be controlled during the data cleanup/transformation process.
- There will be areas where we will be extending the schema of IMPD which results in needing to insert data that is currently not stored in IMPD (e.g. phase history, status history, etc.)
- Does it make sense to perform an ETL or and ELT?

**Comment by zappfyllc** [comment]
Other Options To Consider:

- Adding IMPD tables to Moped and then use those tables as a source (pollutes the Moped database a bit, but could make it easy)
- Using FullConvert for simply extracting and loading the data into a Postgres instance.
- Writing a Python script for transformations needed between IMPD and Moped schema.

**Comment by zappfyllc** [comment]
@sergiogcx I will get you the details for a sample project transformation between IMPD and Moped in this issue and then we can queue up your work for next sprint

**Comment by zappfyllc** [comment]
[Working spreadsheet for schema/data migration](https://docs.google.com/spreadsheets/d/1S8BiXf_H09epwPFI9VxeSgmQ6Jp25U-tWDJUlpzq0PM/edit?usp=sharing)

**Comment by sergiogcx** [comment]
Ok, so I was able to extract data and now all I need is to turn the data into graphql queries.

**Comment by sergiogcx** [comment]
Managed to make the insertions happen:

![2021-03-11_14-43-17.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/5faeaa07-c113-4ed7-957e-39101e9b705d)

![2021-03-11_14-46-03.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/68b8c544-b579-4435-83c3-fdbbbb91c140)

The way this works is very patchy, but seems to be reliable.
1. I built a docker container that installs command line access db tools for linux that exports a CSV file for a table
2. The python script runs a configuration file and extracts data from a table, in this case we are extracting `projects`
3. We load the CSV output from that command and transform it into JSON
4. Each record's data is adjusted to fit into Hasura
5. We make an attempt to insert into the moped_projects table via GraphQL, if the primary key already exists it will attempt to update the project.

**Comment by sergiogcx** [comment]
Branch with code:
https://github.com/cityofaustin/atd-moped/tree/5345-sg-migration-tool/moped-tools


@amenity @zappfyllc

**Comment by sergiogcx** [comment]
I've updated the branch to use Java's JDBC drivers  (as opposed to ODBC) to make advanced SQL queries directly against the access database, since we are going to need joins.

A quick test shows that basic joins are supported:

```
SELECT pp.* FROM Project_Personnel AS pp LEFT JOIN PROJECTS AS p ON p.projectid = pp.projectid
```

Output from python+java+docker container:

![2021-03-12_10-52-48.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/ca0e4331-e380-4f80-95f5-7ec9f400a291)

**Comment by sergiogcx** [comment]
I've also adjusted the main.py file to insert directly from the output of a SQL query into Hasura:

![2021-03-12_11-26-21.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/2adc8852-96cc-4f6b-b0a1-f766335b3913)

**Comment by zappfyllc** [comment]
@sergiogcx
