### ISSUE TITLE
Migrate radar (Wavetronix) counts publisher to new ETL

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5347]
The radar count publisher is broken. We should fix [this script](https://github.com/cityofaustin/atd-data-publishing/blob/master/transportation-data-publishing/open_data/radar_count_pub.py) while migrating it to the to the new [atd-kits](https://github.com/cityofaustin/atd-kits) repo.

**Comment by SurbhiBakshi** [comment]
We have a request from Charlie H at UT Austin. Going to make note here in case this is feasible - 
_Also, would it be possible to change the current date time format from "fixed" to "floating"? Without this, it is harder to group by day/hour/etc as the SODA API only supports grouping for the non-timezone "floating" format. Adding a column with the floating time would work, too. I have ran into the same issue with the Traffic Incidents dataset (https://data.austintexas.gov/Transportation-and-Mobility/Real-Time-Traffic-Incident-Reports/dx9v-zd7x). The camera traffic counts dataset does have the easier to work with floating timestamp format (https://data.austintexas.gov/Transportation-and-Mobility/Camera-Traffic-Counts/sh59-i6y9)._

**Comment by Charlie-Henry** [comment]
@johnclary what do you think about me taking a crack at this once we get data03 on the signal network? I saw this one failing in the data-publishing logs.

I also see this comment above from a concerned citizen I could take a look at too 😉

**Comment by johnclary** [comment]
These devices are no longer maintained.
