### ISSUE TITLE
Digital RPP Petition Builder Huddle

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5348]
### Objective 
Discuss scope and level of effort

### Participants
Stephanie, Diana, Chrispin

Unavailable: John

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
## Meeting Notes

We as a group looked at the ATD Forms - survey "Waterways" and the HR app and looked at the HR Forms>Telework form structure

We think we can keep the scope small

2 object tables: 
`Parent Information Petition` - Ex. Neighborhood address and schedule
>`Petition Signature information` - Ex. Address, Name, Decision, etc...

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/2382518b-c9d3-4eef-b568-2ad80fd6fc8a)

**Comment by dianamartin** [comment]
@johnclary Have you had a chance to review the notes or sync with Stephanie on this?

**Comment by johnclary** [comment]
We have not sync'd yet. Thanks for the laying out the Knack solution. That make sense, and I think it would work. I'm feeling pretty meh about public-facing Knack forms, and would like to at least consider other options. I think Survey Monkey and Formstack could both be really good. Formstack in particular seems to have a great UX.

What if we dedicate some time next sprint to give you @dianamartin a research issue around Survey Monkey and Formstack?

**Comment by johnclary** [comment]
For SurveyMonkey and Formstack, I wonder if there's some way we could create a link to the form which pre-populates the petition identifier. Basic flow would be:

- Resident views petition details (aka, the packet) are on COA website
- Resident clicks link to the petition form, which has the petition ID pre-filled.

Alternatively, I assume we'd need to setup a new form/survey for each petition. That might not be such a big deal if the staff can just copy it from an existing form.

**Comment by dianamartin** [comment]
I understand your concerns about public facing knack forms. I was just thinking I'd hate to have RPP staff have to use a 3rd party to collect data that relates to RPP and not centralize the data. I can do the exploration, but I feel like we'd be need to help manage another tool. The fact we'd need to generate many different surveys. Couldn't we build it out like how HR forms are structured? is the concern data retention/storage?

**Comment by johnclary** [comment]
Good point—I'm also worried about adding another tool to manage. I would not want us to generate the surveys; RPP staff would need to do it. So part of your exploration would be to see how hard it would be for them to create additional surveys after we setup the template for them. With formstack (not sure about survey monkey) we can pipe the data into Knack (or wherever) at a later phase, but I'm adamant about not adding any back-office workflow mgmt to this scope.

**Comment by dianamartin** [comment]
I can take some time to prototype in FormStack, I'm on a trial right now. I think it will expire soon though. I just reached out to Jacob B. from PIO about SurveyMonkey and the latest details. I haven't worked with SurveyMonkey access since Smart Commute tracking (long time ago..)

**Comment by dianamartin** [comment]
I reached out to PIO and didn't get much of a helpful response about Survey Monkey. 

I asked:
>Can you tell me more..is a person limited to how many surveys they can create?

reply
>No, our only limitation is number of users. We have two seats. Honestly it’s one of the best tools we use and we use it frequently. Weekly, at least.

I asked:
>I see, but are you able to loan the seat out by request?

reply
>We don’t loan out the spot as a policy. It is kept within the PIO team. What are you curious about?

**Comment by dianamartin** [comment]
I think I'll need to jump into FormStack and do a prototype before my trial runs out

**Comment by dianamartin** [comment]
I created a prototype RPP petition [form](https://atd-forms.formstack.com/forms/petition_for_residential_permit_parking), but the way the CTM license check out happens I'm not sure the RPP staff will be able to create multiple surveys as needed. They will have to set up the surveys to get emailed to them, which might not be ideal. 

There definitely some obstacles and things we have to think about. The form itself is easy to configure.

**Comment by amenity** [comment]
@dianamartin - the prototype looks really sharp. 👌

I know $59/Month is not nothing, but it may make sense for us to get a single-seat license and use it the same way CTM does — loan out to staff as needed, shut down forms as soon as they're no longer necessary.....

**Comment by amenity** [comment]
If we want to consider a subscription, we can talk ask CTM for a list of Formstack "power users" to get the DL on the strengths and shortcomings.

**Comment by dianamartin** [comment]
- Tested adding a URL Link to the petition documents that is hosted on the austintexas.gov site
- Closing because Stephanie created a new Digital Petition Builder Huddle meeting with John, will talk more about FormStack and our approach
- I will contact Amber T. from CTM about FormStack
