### ISSUE TITLE
TIA MOD Case Log: Team Reviw

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5349]
### Reviewing the case log during project meeting on 3/1/21

**Comment by TracyLinder** [comment]
**Feedback**

- Looks good
- Blanks mean the record was created by the customer (they don't have an account)

**Tasks**
- [ ] System auto-inserts 'Customer' in Edited By column when it's blank

**Comment by ChrispinP** [comment]
Created a Customer account and set a conditional rule to set Edited By to the Customer when the log is created by someone without a login.

Logged out and tested adding an attachment on the customer portal and is working as intended.
