### ISSUE TITLE
Onboard Part-Time Project Manager (Stephanie)

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#535]
### Accounts
- [x] CTM Network account request
- [ ] 1Password?
- [ ] Slack
- [ ] Google Drive
- [ ] ~Github Team~*
- [x] DTS Email Group

### Software
- [ ] ~Zenhub Extension~*

### Hardware

*Stephanie will be 100% remote*

- [x] Laptop
- [ ] Badge

### Communications
- [ ] newsletter announcement

\* _Decided to simplify and work via emails and checkins rather than Github/Zenhub. _

**Comment by amenity** [comment]
@johnclary - I think this is complete...Bumping to Review/QA

**Comment by TracyLinder** [comment]
@amenity I don't think so.
