### ISSUE TITLE
Mitigation Page Updates

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5350]
- Change Improvement Length field to be manual user input instead of drop-down options.
- Input form missing pro-rata share for fee
- Is it possible to click on the street in the map, and have the segment ID auto-populate?
- Change field title to Approximate Expiration Date

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/fa97a6ae-48e2-48dd-b5a6-d55391bb14af)

**Comment by ChrispinP** [comment]
Improvement Length field updated to manual entry with text indication for feet. Added pro rata % entry to the Add Mitigation form. Adjusted Expiration Date field and text. Construction and Fee in Lieu totals will now display $0.00 values if blank.

**Comment by ChrispinP** [comment]
Mitigation Map is searchable by street name and segment id as well as entry field. The field is now a connection and no longer functions in a way where auto-population would be as useful.

Would be a heavy lift that would require dev work to check for the map selection/click and autofill a field.

Ready for review

**Comment by TracyLinder** [comment]
This all looks great. Closing.
