### ISSUE TITLE
Add Scope/Submission Comments Table to Customer Portal View

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5351]
- Only show comments when 'Email Requestor' = Yes
- Add tables to submission details view
- Remove Case Comments table from main case details view

**Comment by ChrispinP** [comment]
Added Case Comments table to customer Case Details page with filters. Comments will only show if a Submission is in the Revision Required or Approved statuses or if Notify Requester is set to Yes. Looks like Comments and Attachments dont like connected automatically to more than one parent object so I updated rules to manually force the connection to the Request object. Will need to test to make sure Content is connecting to both objects so they display properly.

Ready to review

**Comment by ChrispinP** [comment]
Figured out why your comment didnt appear for the Customer @TracyLinder 

The text formula was broken so I updated it and the record and the comment now appears.
![image](https://user-images.githubusercontent.com/67915167/112390495-6a4f6980-8cc4-11eb-9b9a-1f5557e3ffd2.png)

**Comment by TracyLinder** [comment]
This looks great.
