### ISSUE TITLE
Use project_name for the HTML page title on project pages

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5355]
Currently, it is set to "Project Summary Page" across all tabs.
![Screen Shot 2021-03-01 at 4 11 54 PM](https://user-images.githubusercontent.com/1463708/109573098-fe5a5680-7ab3-11eb-8221-07f74ee03c26.png)

**Comment by amenity** [comment]
Can do this with Material UI components.

**Comment by mateoclarke** [comment]
https://github.com/cityofaustin/atd-moped/blob/45593430d0a17c8c30701566e3c10704bc893831/moped-editor/src/views/projects/projectView/ProjectView.js#L275-L276
