### ISSUE TITLE
Project Components | Define (initial) Moped 2.0 "Component Type" taxonomy 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5357]
Establish the baseline list of components, subtypes, and subcomponents to be used in the Moped components interface.

### Definitions
- `moped_component`: a single mobility asset tied to a specific location. E.g. traffic signal, bike lane.
- `component_subtype`: a property of a `moped_component` which further defines the component. E.g. a bike lane component may be of subtype `buffered` or `contraflow`
- `moped_subcomponent`: capture additional details about the component. A traffic signal component may have subcomponents such as `Accessible Pedestrian Button` or `Leading Pedestrian Interval`.

As a starting point, we're referencing the existing  120 component ("facility") types from the IMPDB. We are incrementally mapping these types to our new schema. Tracking progress [here](https://docs.google.com/spreadsheets/d/1rgw3KL9fQ0xS49LLyzexHMPbV58WsWcr2jYaC2oSmKM/edit#gid=1948602978). 

**Purpose**
- Cost estimates (cost * `count`/`length`)
- Performance measures 
- Visualization (labeling and symbology)

**Comment by amenity** [comment]
@johnclary - I see you've started looking at this... Do you have a sense of how to proceed?

**Comment by amenity** [comment]
@johnclary - I see you've started [work on a proposed schema](https://docs.google.com/spreadsheets/d/1rgw3KL9fQ0xS49LLyzexHMPbV58WsWcr2jYaC2oSmKM/edit#gid=2133340878) ... any thoughts on how to proceed? 

@mddilley @zappfyllc - this is related to #5559.

**Comment by johnclary** [comment]
Let's use #6163 as a starting point—it contains the minimum component properties that I feel confident about based on the IMPDB. Will leave this larger defining/refining task in the backlog and revisit a little further down the road.

**Comment by johnclary** [comment]
@johnclary Renee mentioned today that APS stands for "Accessible pedestrian signal" not "Audible push button". Please include that in your taxonomy update.

**Comment by johnclary** [comment]
I've queued up another batch of component updates in #6512.

Capturing @amenity's issue description here because I'm about to overwrite it.

> The IMPDB uses [120 component ("facility") types](https://docs.google.com/spreadsheets/d/1rgw3KL9fQ0xS49LLyzexHMPbV58WsWcr2jYaC2oSmKM/edit#gid=1948602978). 
> 
> **Purpose**
> - Cost estimates (cost * `count`/`length`)
> - Performance measures 
> - Visualization (labeling and symbology)
> 
> **User interface thoughts**
> - Showing all of these to users in a mammoth dropdown sounds awful, but with predictive typing to filter the options it probably wouldn't be too bad. 
> - Actually probably _easier_ to have one field with 👆 than several fields in a row (does not necessarily mean we have to _store_ it in a flat list, instead can just concatenate for the users' view)
> 
> **Asset data sources**
> - Data Tracker - E.g. [Traffic Signals](https://atd.knack.com/amd#signals/signal-list/?view_1169_page=1&view_1169_filters=%5B%7B%22field%22%3A%22field_201%22%2C%22operator%22%3A%22in%22%2C%22value%22%3A%5B%22TRAFFIC%22%5D%7D%5D), [PHBs](https://atd.knack.com/amd#signals/signal-list/?view_1169_page=1&view_1169_filters=%5B%7B%22field%22%3A%22field_201%22%2C%22operator%22%3A%22in%22%2C%22value%22%3A%5B%22PHB%22%5D%7D%5D)
> - Signs and Markings - 
>

**Comment by johnclary** [comment]
I emailed NW for input on the remaining not-implemented facility types. We definitely need input from Renee, et all as well, but priority is to finish facility type >> component mapping so that we can do #6612.

My email (with link to spreadsheet):
> As you can see, we have the interim facility name in the left-most column—which we need to prefer exactly for the migration. You can via the "status" column what's been implemented in Moped.
> 
> The remaining columns reflect the Moped data structure.  This was my initial pass at a mapping. Changing these is fairly trivial (at least until we launch Moped 1.0).
> 
> Field definitions:
> Component name: the high-level name of the component (required)
> Component sub-type: additional specificity of the component type (optional)
> Activities: the types of actions that can be performed on this component. These have not been implemented, but I propose something like install/modify/remove.
> Line representation: should this component be represented by a line? If false, indicates that component should be represented by a point. We have not implemented any UI functionality around this—but we're aware it may be ideal to enforce geometry type mapping this way. 
> 
> Notice all the moped_subcomponents tab. the subcomponents capture additional component properties. We have just a handful at present. 
> 
> Here's where we need your input:
> 
> Review existing components and provide feedback on the assumptions I've made.
> For components that are not in Moped, provide input on the component/subtype/subcomponent definitions for each.
> What are your thoughts on "activities"? Do install/modify/remove cover enough use cases for reporting purposes? 
> 
> Should I set up a meeting for us to discuss, or can we do this asynchronously?

**Comment by amenity** [comment]
Comments from Dylan [via Teams](https://teams.microsoft.com/l/message/19:b1179ddfc92d44ea9abb23db713eb60c@thread.tacv2/1636139606657?tenantId=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&groupId=54a90854-d3fa-4053-9173-5352715bab37&parentMessageId=1636139606657&teamName=Moped&channelName=General&createdTime=1636139606657)

> Three comments on the MAP tab for the Components list:
> 
> 1.  Small typo on Crossswalk
> 2.  Trails and shared use paths are missing from the components list. Not sure if this is something that was missed?
> 3.  I can't remember if there was discussion on including or not including lighting as a component, but it is also missing from the list. Lighting can be added as a safety feature for bridges and underpasses for bike/ped infrastructure, as well as along trails (ex: Lower Boggy Creek Trail) that allows for folks to feel more comfortable commuting by trails when its dark out.

**Comment by johnclary** [comment]
From https://github.com/cityofaustin/atd-data-tech/issues/6923 - include a Rain Garden component type (per Ella and Alan)

**Comment by johnclary** [comment]
Closing this. We have a working list of all known component types in the Access DB, [here](https://docs.google.com/spreadsheets/d/1rgw3KL9fQ0xS49LLyzexHMPbV58WsWcr2jYaC2oSmKM/edit#gid=1948602978),  with the caveat that we have not kept what is implemented in Moped update to date in the doc. The current Moped component list is [here](https://moped.austinmobility.io/moped/dev/lookups#moped-components).
