### ISSUE TITLE
Update RPP reporting to use new "Number of Permits" field for day passes

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5359]
See also: https://github.com/cityofaustin/atd-data-tech/issues/4754

**Comment by ChrispinP** [comment]
All Reports that pull Permit information, specifically the Active Permits and Permits Issued reports for all zones have been updated to be grouped by the Number of Permits field instead of the record count now. These charts should be accurate counts now.

Complete
