### ISSUE TITLE
Robin Lessons Learned Document

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5366]
Document lessons learned during Robin pilot 

https://docs.google.com/document/d/1LKdJf9q3H8B8zL_O79mX1GklsbOaCyFYUt9wLprNGLA/edit#

**Comment by dianamartin** [comment]
@moorerst I think we can close this now, right?

**Comment by moorerst** [comment]
sounds good to me. Closing issue
