### ISSUE TITLE
Copy Mobile Optimization styling from SMB to test in RPP Test Environment

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5367]
Came from other issue #4841.

We need to identify the pages/views which need styling applied. @ChrispinP will do this and @dianamartin will implement in test

**Comment by dianamartin** [comment]
Went to SMB Tracker, in CSS code
- Copied from Line 88 to 208
- Didn't get all the code at the bottom bc I wasn't sure what those were, just the things that said Mobile Styles

Added code to TEST | FEB 12 2021 | RPP | Residential Parking Permits Portal
- Line 767 to Line 887
- Copied app URL
- Opened in mobile device and was able to see mobile changes

## Apply for Permits 
- this page has 2 columns, need to reduce to 1 for mobile viewing
- limited screen real estate
- Weird gap still seen on the License Plate and State 1, bc fields are hidden
- 

### Changes
- Form Entry fields look to be globally changed
- Field headings look larger
- Drop down field entry looks larger
- Submit button globally changed

**Comment by dianamartin** [comment]
@ChrispinP @moorerst I've done an initial run through of the Mobile Styling in the RPP Test Environment. I've added the screen shots from my mobile device so you can see it.

**Comment by ChrispinP** [comment]
@dianamartin awesome, thanks, would you still like me to compose a list of scene and view numbers or do you have enough info?

**Comment by dianamartin** [comment]
@ChrispinP are you able to put the scene/view IDs in this issue please? or is the plan to create a new issue and tag the Devs?

**Comment by ChrispinP** [comment]
### All Scenes and Views for RPP Application


//apply for permits (applicant information)
#kn-scene_309
kn-view_1172 //applicant information - form
kn-view_1174 //questions footer - rich txt

//permit information
#kn-scene_310
kn-view_1175 //permit information - form
kn-view_1176 //questions footer - rich txt

//required documents
#kn-scene_312
kn-view_1178 //required documents - form
kn-view_1179 //questions footer - rich txt

//review application
#kn-scene_313
kn-view_1182 //review your application - rich txt
kn-view_1193 //edit application - menu
kn-view_1181 //applicant information - details
kn-view_1255 //combined decal hangtag information - details
kn-view_1254 //resident decal information - details
kn-view_1184 //no resident decals added - rich txt
kn-view_1253 //visitor hangtag information - details
kn-view_1185 //no visitor hangtags added - rich txt
kn-view_1252 //day pass information - details
kn-view_1186 //no day passes added - rich txt
kn-view_1251 //permit bundle information - details
kn-view_1189 //vehicle information - details
kn-view_1187 //no vehicles added - rich txt
kn-view_1191 //required documents information - details
kn-view_1183 //no require documents added - rich txt
kn-view_1188 //finalize application - rich txt
kn-view_1192 //submit application - form


//application invoice
#kn-scene_314
kn-view_1195 //review your application - rich txt
kn-view_1196 //applicant information - details
kn-view_1212 //permit address and bundle information - details
kn-view_1256 //combined decal hangtag information - details
kn-view_1257 //resident decal information - details
kn-view_1198 //no resident decals added - rich txt
kn-view_1258 //visitor hangtag information - details
kn-view_1199 //no visitor hangtags added - rich txt
kn-view_1259 //day pass information - details
kn-view_1200 //no day passes added - rich txt
kn-view_1201 //signature details - details

//edit application
#kn-scene_315
kn-view_1194 //edit application - form

**Comment by moorerst** [comment]
check common patterns
apply global changes
Diana will review the views

**Comment by dianamartin** [comment]
Was gonna work on it 3/26, but realized I didn't have a Test environment ready to go. Will have to push this back to next week.

**Comment by dianamartin** [comment]
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/89fa9fa3-3002-4be9-8342-afcf48db495c)

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/becdca82-a67e-428a-8f8b-42cdb41178fe)

**Comment by dianamartin** [comment]
@moorerst @ChrispinP please review the changes above, let me know if we'd like to push the changes to RPP PROD

**Comment by dianamartin** [comment]
Closing this, Chrispin and I have a meeting scheduled for 4/9 to review the changes in RPP Production
