### ISSUE TITLE
Enable Work Orders to be associated with DSDD assets in TEST

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5372]
- Scheduled Builder Review for 3/17 
- Hopefully afterwards will be able to do this issue after guidance on asset relationship to work orders

**Comment by johnclary** [comment]
@dianamartin let me know when you want to look at this together

**Comment by dianamartin** [comment]
In TEST | AMD - 17 MAR 2021 | AMD Data Tracker
- looked at existing AMD Work Orders that originate from the asset
- noticed they had the wrong asset types, probably bc you can edit after it gets created, just a quick way to create work order
- reviewed the signal work order fields to see which ones can be pre-populated when a new DSDD work order form is created

**Comment by dianamartin** [comment]
- Schedule a quick demo with Billy
- Billy was able to see the changes in Test and approve of the path forward
- Amenity created an issue to deploy changes to production environment #5714, closing this.
