### ISSUE TITLE
Define Moped Material Table theme/design customizations

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5375]
Using the "Project team" table as an example: 
- [x] @tillyw's [form validation fix](https://github.com/cityofaustin/atd-moped/pull/239)
- [x] Tilly's [moving action buttons to the far right](https://github.com/cityofaustin/atd-moped/pull/239#issuecomment-796869149)
- [x] Add row button should have a specific text label — see @mateoclarke's implementation in the "Project phases" component
- [x] Add row button should remain in upper right
- [x] Add row button should have a circle-plus icon instead of a square-plus icon (see "Projects" page)
- [x] Hide/remove "Actions" column heading
- [x] Show pagination only when there are more than 25 rows.
- [x] Render dates as mm/dd/yyyy
- [ ] Enable date-clearing on calendar picker #6159
- [x] Make the "No records to display" text context-dependent, e.g. "No team members to display" on the Team tab.
- [x] Remove min-height on table
- [x] Change table title from h6 to h2
![Screen Shot 2021-06-02 at 3 21 22 PM](https://user-images.githubusercontent.com/1463708/120554342-3cbb2680-c3bf-11eb-847e-5a209ddae4a0.png)

Once these customizations are implanted we can discuss how best to make them resuable.

**Comment by amenity** [comment]
@johnclary - going to want your input on these

**Comment by johnclary** [comment]
@amenity i believe we captured some of this the initial project timeline pull request, right?

**Comment by amenity** [comment]
@johnclary - yes, but just kind of telephone from my convos with you to a slack message w/ @mateoclarke on moving the "+" button below the table. He has those changes reflected in a branch he is working on.

**Comment by johnclary** [comment]
@amenity a few additional suggestions. We can move these into the issue description but wanted to run it by you.
<img width="911" alt="Screen Shot 2021-05-04 at 10 09 17 AM" src="https://user-images.githubusercontent.com/14793120/117027385-43705400-acc2-11eb-942f-d7d905d83a19.png">

**Comment by amenity** [comment]
A suggestion from #5210:

> It would be nice if the date-picker calendar opened automatically when a date field is active. if y'all agree, we might move this into a separate issue to address it globally since we need this enhancement in Sergio's advanced table filters and will need it elsewhere.
