### ISSUE TITLE
Delete "csr_flex_notes" from Signs & Markings - April 2021

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5379]
Received automated reminder to delete flex notes in Signs and Markings Operations PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings#data/object_172/records

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 02/01/21

Total Records: 11,555
To Delete: 3,449
New Total: 8,106

**Comment by SurbhiBakshi** [comment]
Hi @ChrispinP - I can take Signs and Markings and unassign myself from AMD.
