### ISSUE TITLE
Data Model | Update values in `moped_phases`

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#5381]
Update values in moped_phases table

[List of phases](https://app.gitbook.com/@atd-dts/s/moped-technical-docs/user-guides/project-phases)

**Comment by amenity** [comment]
@mateoclarke - I am going to clean up this list right quick.

**Comment by amenity** [comment]
Ready to go. ✅  Please add an estimate 🙏👕
