### ISSUE TITLE
Project Summary | Implement various style refinements to text panel

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5383]
![Screen Shot 2021-03-03 at 11 57 18 PM](https://user-images.githubusercontent.com/1463708/109919722-c3584e80-7c7e-11eb-904f-1016b630c3bb.png)

### Update field titles
- [x] "Current status"
- [x] "Current phase"
- [x] "Start date"
- [x] "Fiscal year"
- [x] "Capital funding"
- [x] "eCapris subproject ID" 

### Addtional refinements
- [x] Form data is being rendered as currently form labels; should be (normal? body) text 
<img width="1028" alt="Screen Shot 2021-03-09 at 9 54 20 PM" src="https://user-images.githubusercontent.com/1463708/110699357-63006a00-81b4-11eb-802e-a30a957f632e.png">

**Comment by amenity** [comment]
@tillyw via Slack on 3/11
Just a heads up this issue might need to be broken up into three!

Conditionally rendering the eCapris ID and using a switch for capital funding are a little more complicated than I initially thought because they will involve making changes to the DataTable component, which isn't really set up for such specific behavior

I have everything done except for that and the pencil icon stuff (edit

**Comment by johnclary** [comment]
- [Issue for Capital Funding enhancements](https://github.com/cityofaustin/atd-data-tech/issues/5518)

**Comment by amenity** [comment]
saeklntaewrnt

**Comment by amenity** [comment]
@tillyw, breaking this up. @johnclary got ya 
#5518
#5519

**Comment by tillyw** [comment]
Thanks @amenity and @johnclary! I'm going to remove the requirements from this issue that are covered in the other two and submit a PR to close this one out.

**Comment by amenity** [comment]
@tillyw - perfect, was just about to do that. Thanks!
