### ISSUE TITLE
Meeting - Parking Dispatch Process for handling different types of CSR

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5391]
Different Types of CSR's / CSR is sent via email notification to everyone
Residential
Booting
Parking Violation
Pay By Phone - Joseph team will pick up the CSR's for technical issues related to Pay by Phone

CSR's received outside of normal business hours - these should be flagged by 311 and sent to PD but we are receiving them anyway.
need process for handling these types of CSR's

- New Activity - Received After Hours / Outside Agency Transfer???

- Activity 311 Feedback with a email notification back to 311 indicating SR received outside of normal business hours???

- [x] need to set up separate meeting with Levi, Jasmine, Shavyvonne and Joseph to discuss the process for handling different CSR's - preferred time W - F after 10:00

**Comment by moorerst** [comment]
meeting scheduled 3/24
Attendees: Joseph, Jacob, Lyndon, Diana, Shavyvonne, Stephanie

**Comment by moorerst** [comment]
Agenda: https://docs.google.com/presentation/d/1L_Olz36_8UkoKQtXvu0e8X9huaBDZfEmM8_bsjSqUt4/edit#slide=id.p

**Comment by dianamartin** [comment]
# Meeting Notes
- re-vamped the SR - Pay by Phone
- Took away the "technical issue"
- Won't take an SR anymore - will give citizen information to call Passport
- Pay by Phone is essentially going away
- Parking citation issues: got rid of parking citations
  - going straight to Municipal Court

## ATD Booting Complaint
- austintexas.gov - 311 website
- Depended on the complaint description
- APD Complaint - with actual booting company
- ATD if there is a signage discrepancies 
on Private Property, don't regulate the TDLR (Texas Department of Licensing and Regulation) signage?
- Can be issued a citation
- Could be ATD/APD co-worked SR
- Gets assigned to officer
- (8) Booting Companies
 
## RPP Enforcement 
- 311 Request
- Attach photos with complaint
- Dispatcher looks at complaint and photo
- To send officer? usually send officer
- Check vehicle has permit
- No permit, cited
- Resolution and closed out 

## Parking Violation Enforcement
- 311 Request
- Attach photos with complaint
- Dispatcher looks at complaint and photo
- Officer dispatched
- Citation?
- Pictures of violation
- Resolution and closed out 

Parking Violation - sub-type: RPP future?

[Ground Transportation Complaint Form](https://cityofaustin.formstack.com/forms/ground_transportation_complaint_form) - Formstack
- is not a 311 SR
- create new 311 SR for this

## Shared Micromobility
- 311 request
- mobility provider 
- 2 emails go out, shared mobility resource account and provider
  - 311 generated email gets send out to both ATD and provider
- emailing result for SR to ATD, emailing shared mobility resource account
- ATD staff to close it out
- SR timelines to be answered per SLA

Dispatch doesn't really get involved... really back up to Shared Mobility SRs
- no response after 2 hrs 
- dispatch should be monitoring
- send officer out to check if they responded
- decision to impound devices 

# Decisions Made
311 - Chandra
- [ ] disable automatic email
- [ ] disable automatic activities

**Comment by dianamartin** [comment]
Yes, it can. I'm closing this!
