### ISSUE TITLE
Technical Huddle - Parking Dispatch CSR Integration

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5392]
Set up Technical Huddle to discuss when to start the process of integrating CSR's into Knack

**Comment by moorerst** [comment]
scheduled for 3/15

**Comment by moorerst** [comment]
For my understanding How does the CSR to Knack integration work/who is involved:
311 - will publish CSR's to ATD based on SR Request Type
CTM/ESB/Omar - gets some specific Knack information, does some configuration, pushes 311 SR's and Flex Notes to Knack

Diana spoke with Bill S about our interest in integrating new SR types into Knack for Dispatch. 
He indicated they were very busy right now with handling vaccine request/issues. The timeline for 311 would be about 4 weeks
Bill also mentioned they were revamping the Pay By Phone SR type, working with Joseph. Would be ready sometime in April.  This SR type came up in our process discussions, the technical SR for Pay By Phone are handled by Joseph team. They are pulled from the group email notifications and handled directly by his team. Dispatch does not do anything with these.

Need meeting with Joseph, Jacob, Shavyvonne and Lyndon to talk about how the different SR's  are processed.

If all of the SR's are integrated into Knack and the email notifications are eliminated how will Joseph's team get the technical Pay By Phone SR's. Per John there is a way to pull keywords from the SR Flex Notes and populate a field to filter out certain types of SR's that need to processed differently

next steps:
get clarification on SR process
soft launch with out the SR integration
Integrating the SR's is not a blocker for continuing on with the project since it is not something that is in place today.

**Comment by dianamartin** [comment]
Anything else we need to add to this before closing?

**Comment by moorerst** [comment]
closing issue
