### ISSUE TITLE
Purchase AWS from DIR 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5394]
We need to purchase AWS through the Texas DIR and stop using our Procard for it.

We met with our account reps (Greg and Marcus) to understand our options. Because AWS is a DIR vendor, we can purchase their services through the DIR. This will allow AWS to invoice the city for services COA accounts payable will manage payments.

- [x] Provide usage summary to AWS account mgrs
- [x] AWS will set up a cost estimating instance for us, we'll review it, then ask for a formal quote from them
- [x] Create a CTM purchase request for the quote 
- [x] Finalize purchase and stop paying by procard

**Comment by mateoclarke** [comment]
cost estimate for Feb 2021 has been sent.

**Comment by johnclary** [comment]
I sent the attached quote to Ken B and created a purchase request. Waiting to hear on next steps.

[ATD AWS Price Estimate 6-10-2021.pdf](https://github.com/cityofaustin/atd-data-tech/files/6652864/ATD.AWS.Price.Estimate.6-10-2021.pdf)

**Comment by johnclary** [comment]
Dan V has approved the PR. Now Jon (ATD Finance) has been assigned to this and will create the CTM purchase request.

**Comment by johnclary** [comment]
We have a contract! We're now paying through direct fund transfer. I need to submit our sales tax exemption info. Submitted a request for the latest documentation to our accounts payable.

**Comment by johnclary** [comment]
I submitted our sales tax exemption info. We did it!
