### ISSUE TITLE
Assist Billy and Jorge creating a fillable PDF for signal intersection inspection punchlists

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5407]
- Billy configured a PDF fillable form but wasn't able to email the form without the form being in a readable format
- He wanted to explore inserting images to the pdf form
- He wanted the tablet experience to be smooth for the technicians

**Comment by dianamartin** [comment]
- I tested the prototype form that Billy made on a tablet, found some areas of improvement
- Sync w/ Billy to let him know of improvements (make form fields larger for tablet use)
- Reconfigured PDF fillable form to add images
- Tested on tablet with Jorge
- Decided to remove images, incompatible with mobile devices unless using a different Adobe license $299+
- Helped come up with a workaround process
- Tested process on tablet/desktop with Jorge
- Jorge finished PDF fillable form by adding check boxes
