### ISSUE TITLE
Parking Dispatch Testing

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5420]
I'll pulling different examples from the Dispatch SP list and entering them into the Parking Dispatch prototype.
Will track questions/comments/suggestions here:

1. How does an SR get Closed. I opened 000065 added activities, selected Closed Issue (Resolved) but the SR still has status In Progress.
- Delete the activity, refresh and close it again. I didn't have a rule on the form. That form is still missing rules bc it's not final bc normally this is when the form pushes rules so that it sends communication back to the 311 system - resolved

2. When they use the category Radio Check they often enter some notes ex. 10:30AM @ car wash/10-8 10:45AM. 
We are not capturing any notes when we select Radio Check in Resource Tracking. Should we?

- [ ]  We're currently not, but we can ask next sprint review if they need it. Maybe this needs to be another option because they are Not Available while they are at the Car Wash, are they?

3. They enter multiple Radio ID's in one Radio Check ex. Radio check @ 9:30AM 195,177,179,201,197,178,189,215,187
- They won't be able to do that with the Resource Tracking page. They will have to search them one at a time.

**Comment by moorerst** [comment]
I see some instances where they capture # citations and # of warnings -  vehicles parked in travel lane - peo 444 - 21 citations/4 warnings

- [ ] Do we need to provide the options to capture # of Warnings?

In this example are they dispatching 2 officers? 
PEO 195/177 4100 cat Mountain Dr. Vehicle on both side of street, making it difficult for traffic and pedestrians

- [ ] Would they enter two different Dispatch Investigator activities for each Officer id? Which Officer would see the SR in My Assignments?
- [ ] In the Radio Checks I see 10-8 and 10-7 a lot. What does that mean?

**Comment by dianamartin** [comment]
@moorerst 
- Added the `number of warnings` field to activity form
- Changed the `Assigned To` field to allow multiple officers and created a Dispatch Officer activity
  -  Checked under "Diana" and "PEO Officer", only one account got the SR send to them to work on. I added "Diana" first and then the "PEO". So it might be the last person who is added gets the SR actually assigned to them.

**Comment by dianamartin** [comment]
@moorerst Should we include this (our questions) in the status email?

**Comment by moorerst** [comment]
@dianamartin did you get a chance to review the sprint review status email for Dispatch Tracking? I think we addressed all the issues from testing in the status email.

**Comment by dianamartin** [comment]
@moorerst I did review, but didn't realize I was supposed to add/edit it. I'll do that today :)

**Comment by moorerst** [comment]
closing this issue is complete
