### ISSUE TITLE
New Knack Builder: Signs and Markings (SMB) Application Testing

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5431]
SET-UP
- [x] Test Environment - check if one exists for 2021 , if not create new one
- [x] Update Application Inventory
- [ ] Get an application power user to help test
- Asking Christina if she wouldn't mind testing in the TEST environment bc she knows the system so well. Scheduled some time with her on Monday.  
- [ ] Set up password for testing env - power user

BACK END
- [x] Big button re-direct links
- _the links from the big buttons are functioning correctly, no issues_
- [x] Big button (rich text) - add tags 
- _The BE Home page has the Rich Text come in, but not the labels from the Rich Text_ 
- _I forgot I had to turn on the labels. Screen shot below._
- [ ] Coordinate with dev team
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

FRONT END
- [x] Check for broken icons
- [x] Check for broken links
- _tested this on the New Work Order as a `Test-Tech`, there is a link to Street Segments map_
- _Map opened up with no issues_
- [x] Check multiple columns
- _tested this on the New Work Order as a `Test-Tech`_
- [ ] Document every change that needs to be changed in Prod application
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

### Before Migration May 1st, 2021
- [ ] Create back-up for application - April 29/30th

**Comment by dianamartin** [comment]
- Logo doesn't come in on the live app, but that is a known issue when you make a copy of an app

**Comment by dianamartin** [comment]
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/6eb5f276-21bf-43a0-9c0b-fc6e138bbcd9)

**Comment by dianamartin** [comment]
Testing Signs Work Order
NEED TO BE ISSUED- was logged in as myself
- Prod: Location map showed up fine, could find a location
- Test: Location map DOES NOT SHOW UP, blank white space before the Time Log table

NEED TO BE ISSUED- was logged in as Test-Viewer
DETAILS PAGE
- Prod: Page looked identical, map showed up fine
- Test: Page looked identical, map showed up fine

OPENED PDF - the PDF tool bar looks very different (probably new builder stuff)
- Prod: PDF has a white background
- Test: PDF has a grey/black background
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/92e5ff0e-745f-439e-bb38-c1a5a782ad25)

ISSUED STATUS
- Prod: Asks to allow location access
- Test: Does not ask for this (?) What?!

CLOSED
- Prod: Page looked identical, map showed up fine
- Test: Page looked identical, map showed up fine

**Comment by dianamartin** [comment]
# SMB CUSTOM STUFF
- New Work Order, Pulling user's division into the "Requester" field automatically (this PASSES, STILL WORKING)
- Issued Work Order, Location map showing up, Adding a location (this PASSES, STILL WORKING)
- Location Details, big back button on the bottom of the page to help user not have to scroll all the way up to get back to the previous screen (this PASSES, STILL WORKING)

**Comment by dianamartin** [comment]
# Mobile Testing
`Current Attachments process`: Technician is required to download attachment and view it through Adobe Reader
_Christina is wondering if new builder and new PDF will change that process, will test it to see

**Comment by dianamartin** [comment]
- The mobile testing on the tablet seemed to be fine, there was nothing out of the ordinary.
- Christina said she'd test some areas in the SMB tracker in the new test environment to see if it's what she's used to seeing

**Comment by dianamartin** [comment]
I think this one is ready to switch over, will wait till we speak to John about it first

**Comment by dianamartin** [comment]
### Button Code
- line `336-550`

### COACD Button Code
- line `373-415`

**Comment by dianamartin** [comment]
- SMB Page without COACD Big Button
Pages that doesn't have: 
- manage-records
- manage-hardware
- reimbursements

**Comment by mddilley** [comment]
Updated Signs and Markings production with the new COACD code so the following pages now have the custom big button login:
- manage-records
- manage-hardware
- reimbursements

The big button code was also updated in both TEST | SMB - 17 MAR 2021 and Signs and Markings Production so that the issue with the underline text decoration and right margin that was clickable is now gone.

**Comment by dianamartin** [comment]
- Created BACKUP | APR 22 2021 - Signs and Markings Operations on 4/22
-

**Comment by dianamartin** [comment]
Closing, have an issue for the SSO functionality not showing up #5720
