### ISSUE TITLE
New Knack Builder: VZA Application Testing

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5433]
SET-UP
- [x] Test Environment - check if one exists for 2021 , if not create new one
- [x] Update Application Inventory
- [ ] Get an application power user to help test
- [ ] Set up password for testing env - power user

BACK END
- [x] Big button re-direct links
- [x] Big button (rich text) - add tags 
- [ ] Coordinate with dev team
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

FRONT END
- [x] Check for broken icons
- [x] Check for broken links
- [x] Check multiple columns
- [ ] Document every change that needs to be changed in Prod application
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

### Before Migration May 1st, 2021
- [ ] Create back-up for application - April 29/30th

**Comment by SurbhiBakshi** [comment]
Pages to check 
1. As Scheduler 
- [ ] Assignments
- [ ] Locations
- [ ] Invoicing

2. As Officer Administrator
- [ ] Assignments
- [ ] Invoicing
- [ ] Cancelled

3. As Officer 
- [ ] Sign Up
- [ ] My Assignments
- [ ] Past Assignments
- [ ] Cancellation Policy

4. Miscellaneous
- [ ] Tasks to send email notifications
- [ ] Tasks to create child records
- [ ] Login with CoA credentials

**Comment by SurbhiBakshi** [comment]
@amenity and @mddilley - I transitioned the 3rd Feb test instance for VZA to the New Builder for Knack and tested it. It's working smoothly, including the pages dependent on custom code. If you want to take a look, try out the 3rd Feb 2021 Test instance.

**Comment by SurbhiBakshi** [comment]
Tried the application both on my laptop and my phone (officer workflow) - worked smoothly.

**Comment by SurbhiBakshi** [comment]
- [ ] Check submit rules

**Comment by SurbhiBakshi** [comment]
@amenity - Here is the link to the [Test application](https://atd.knack.com/test-vision-zero-in-action-3-feb-2021#home/)

**Comment by amenity** [comment]
@SurbhiBakshi - logged in as Officer, Scheduler, and Invoicer. All looked great.

The banner image is broken for me, though. 
![Screen Shot 2021-04-16 at 7 13 16 PM](https://user-images.githubusercontent.com/1463708/115095694-d00bcb80-9ee7-11eb-83f2-74b7f07acf3e.png)

**Comment by SurbhiBakshi** [comment]
Post Migration Checklist - 

### Pages to check
 **As Scheduler**

 Assignments
 Locations
 Invoicing

**As Officer Administrator**

- [ ]  Assignments
- [ ]  Invoicing
- [ ]  Cancelled

**As Officer**

- [ ]  Sign Up
- [ ]  My Assignments
- [ ]  Past Assignments
- [ ]  Cancellation Policy

**Miscellaneous**

- [ ]  Tasks to send email notifications
- [ ]  Tasks to create and update child records
- [ ]  Login with CoA credentials

**Comment by SurbhiBakshi** [comment]
@amenity - the banner came across when I migrated the Production instance to the New Builder. ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/72c96c47-aaca-4411-91ec-336cc183d6c1)

**Comment by amenity** [comment]
@SurbhiBakshi — nice
