### ISSUE TITLE
New Knack Builder: Finance Application Testing

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5434]
SET-UP
- [x] Test Environment - check if one exists for 2021 , if not create new one
- [x] Update Application Inventory
- [ ] Get an application power user to help test
- [ ] Set up password for testing env - power user

BACK END
- [x] Big button re-direct links
- [x] Big button (rich text) - add tags 
- [ ] Coordinate with dev team
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

FRONT END
- [x] Check for broken icons
- [x] Check for broken links
- [x] Check multiple columns
- [x] Document every change that needs to be changed in Prod application
- [x] Get code working in test application
- [ ] Schedule maintenance down time for app

### Before Migration May 1st, 2021
- [ ] Create back-up for application - April 29/30th

**Comment by dianamartin** [comment]
- Just created new test environment, waiting for it to finish. 
- Will update app inventory and delete old test environment

**Comment by dianamartin** [comment]
## Big Button Code Change
- line `85-103`
- replace with [JS code](https://atd-dts.gitbook.io/atd-knack-operations/knack-code/functionality/big-buttons) - `85-106`
- check CSS code

**Comment by dianamartin** [comment]
- Tested links in live app in test environment, links worked fine
- Button redirects were fine as well

**Comment by mddilley** [comment]
I made the same updates to **TEST | APR 4 2021 | Finance and Purchasing System** that were applied to the SMB apps, and I'm no longer able to reproduce a bug where the custom login would disappear after logging out. The issue with clickable white space to the right of the big buttons is now gone as well. The updates are in [this PR](https://github.com/cityofaustin/atd-knack/pull/33) which I will request review on tomorrow. These updates can easily be added to production when needed.

**Comment by dianamartin** [comment]
- Created back up for app `BACKUP | APR 23 2021 - Finance and Purchasing System`
- Added SSO button code added to Backup - code worked properly
- Modified SSO button code in Finance and Purchasing PROD - code worked properly
