### ISSUE TITLE
New Knack Builder: HR Application Testing

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5435]
SET-UP
- [x] Test Environment - check if one exists for 2021 , if not create new one
- [x] Update Application Inventory
- [ ] Get an application power user to help test
- [ ] Set up password for testing env - power user

BACK END
- [x] Big button re-direct links
- [x] Big button (rich text) - add tags 
- [x] Coordinate with dev team
- [x] Get code working in test application
- [x] Schedule maintenance down time for app

FRONT END
- [x] Check for broken icons
- [x] Check for broken links
- [x] Check multiple columns
- [ ] Document every change that needs to be changed in Prod application
- [x] Get code working in test application
- [x] Schedule maintenance down time for app

### Before Migration May 1st, 2021
- [x] Create back-up for application - April 29/30th

**Comment by ChrispinP** [comment]
Scheduled Switchover for Monday and emailed stakeholders.

**Comment by ChrispinP** [comment]
New Builder Switchover Complete
