### ISSUE TITLE
New Knack Builder: Visitor Log Application Testing

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5436]
SET-UP
- [ ] Test Environment - check if one exists for 2021 , if not create new one
- [x] Update Application Inventory
- [ ] Get an application power user to help test
- [ ] Set up password for testing env - power user

BACK END
- [ ] Big button re-direct links
- [ ] Big button (rich text) - add tags 
- [ ] Coordinate with dev team
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

FRONT END
- [ ] Check for broken icons
- [ ] Check for broken links
- [ ] Check multiple columns
- [ ] Document every change that needs to be changed in Prod application
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

### Before Migration May 1st, 2021
- [x] Create back-up for application - April 29/30th

**Comment by ChrispinP** [comment]
Visitor Sign In Switchover is complete. This app has a custom sign in so no SSO updates needed. I updated the CSS
