### ISSUE TITLE
New Knack Builder: Shared Mobility Application Testing

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5438]
SET-UP
- [x] Test Environment - check if one exists for 2021 , if not create new one
- [x] Update Application Inventory
- [ ] Get an application power user to help test
- [ ] Set up password for testing env - power user

BACK END
- [ ] Big button re-direct links
- [ ] Big button (rich text) - add tags 
- [ ] Coordinate with dev team
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

FRONT END
- [x] Check for broken icons
- [x] Check for broken links
- [x] Check multiple columns
- [ ] Document every change that needs to be changed in Prod application
- [ ] Get code working in test application
- [ ] Schedule maintenance down time for app

### Before Migration May 1st, 2021
- [ ] Create back-up for application - April 29/30th

**Comment by SurbhiBakshi** [comment]
1. As SMO Team 
- [ ] Home
- [ ] Permits
- [ ] Fees/ Payments

2. As SMO Partner
- [ ] Fees/ Payments

3. Miscellaneous
-  [ ] Login

**Comment by SurbhiBakshi** [comment]
**Post Migration Checklist**

**As SMO Team**

- [ ]  Home
- [ ]  Permits
- [ ]  Fees/ Payments


**As SMO Partner**
- [ ]  Fees/ Payments
- [ ] Miscellaneous
- [ ]  Login

- [ ] Check Single Sign On

**Comment by SurbhiBakshi** [comment]
Notes 
1. Get single sign on all pages except for Impounds.

**Comment by SurbhiBakshi** [comment]
The Permit Expiration notification email that is sent out when a permit expiry date is 30 days away lost it's formatting. When I reformatted the content and tried to save the task, I see the error documented below. If I don't save the formatting and run the task as it came in from the Old Builder it works and sends the email. Don't see any error message. 




 ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/f4ad281b-6706-478b-ab1a-7f92a751884f)
