### ISSUE TITLE
New Knack Builder: Development Services Application Testing

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5439]
SET-UP
- [x] Test Environment - check if one exists for 2021 , if not create new one
- [x] Update Application Inventory
- [ ] Get an application power user to help test
- [ ] Set up password for testing env - power user

BACK END
- [x] Big button re-direct links
- [x] Big button (rich text) - add tags 
- [ ] Coordinate with dev team
- [x] Get code working in test application
- [x] Schedule maintenance down time for app

FRONT END
- [x] Check for broken icons
- [x] Check for broken links
- [x] Check multiple columns
- [x] Document every change that needs to be changed in Prod application
- [x] Get code working in test application
- [x] Schedule maintenance down time for app

### Before Migration May 1st, 2021
- [x] Create back-up for application - April 29/30th

**Comment by ChrispinP** [comment]
Reviewed custom JS and CSS code, reviewed both builder and front-end functionality. Everything is looking and functioning correctly from my testing. I do not think a Power User is necessary for the Test env. Will want power users available on Switchover day to ensure normal workflow is working as expected i.e. Tracy, Sangeeta, Nathan.

Action Items after Switchover:
[ ] Update icons for Nav Menu and Parent pages

**Comment by ChrispinP** [comment]
email sent to stakeholders for 04.14 @ 5pm Switchover

**Comment by ChrispinP** [comment]
Completed followup actions. New Menu Icon bug where they are not currently displaying. I have messaged Knack about it.

Putting into QA if any further action is necessary.
