### ISSUE TITLE
Collect Feedback For 1st Round of Fixes -  DTS Service Request Form Workflow

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#544]
**Scope**: Collect thoughts on how the new portal form submission workflow is working, including possible upgrades/fixes. 

- [ ] Collect feedback through sprint 7
- [ ] Create issues for any changes/upgrades needed.

**Comment by TracyLinder** [comment]
See item #211 - It's making us wonder if the ticket is truly reflecting what Billy submitted. A possible solution is

**Comment by amenity** [comment]
@TracyLinder - I think the issues should actually go into this repo: https://github.com/cityofaustin/atd-knack-dts-portal/ 
@johnclary ?

**Comment by amenity** [comment]
Added one here: https://github.com/cityofaustin/atd-knack-dts-portal/issues/2

**Comment by amenity** [comment]
I think we can close this issue and open others if anything else comes up. @johnclary @TracyLinder ?
