### ISSUE TITLE
TIA Mod Project Team Feedback 3/8/21

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5446]
### Notes & tasks down in the comments.

**Comment by TracyLinder** [comment]
- [ ] Update edit case form to allow to connect to TDS cases from TIA Case Details page
- [ ] Remove Case Notes field from the portal application.
- [ ] A new feature to allow users to change the assigned reviewer
- [ ] Case Management Submissions Details Pages: Change green 'Yes' box to a check box
- [ ] On Case Management details, add Review Start Date, Review End Date.
- [ ] Move Case Management button to top left of button section



- We spoke at length about whether we should capture all segments related to a single mitigation record, or if the current design of assigning the record to one segment will work. It was decided to leave as-is. John asked that we get Jaime's team to do a GIS review at some point.

**Comment by ChrispinP** [comment]
I have completed all listed items. Reviewers are now able to be added, updated, and changed for the entire case, or individually for each Submission. This will allow us to create Task Pages for individual Reviewers so they may see all Cases and by extension, all Submissions they have been assigned or worked on. Form buttons on each of the Details pages have been built for this. Did a sweep over pages and forms where user information could be helpful and provided help text where needed.

Additionally multiple Development Cases can be connected to a TIA case either on the TIA Requests table or on its Details page with the Connect Cases button.

Both Reviewers and Connected Cases and also displayed on the Case Details page

complete, ready for review

**Comment by TracyLinder** [comment]
All of this looks great. Closing.
