### ISSUE TITLE
Knack New Builder Migration Issues - Escalated to Knack

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5448]
- Add issues here that need the attention of the vendor
- blocker level type things we can not work through

**Comment by dianamartin** [comment]
# List
- New builder switch over, doesn't have Single Sign On functionality when PROD environment has it
  - put in a Knack ticket
- Didn't have conditional rules on a field in object
  - put in a Knack ticket
  - confirmed later that the conditional rules showed up
-

**Comment by SurbhiBakshi** [comment]
- Miss the Single Sign On function for [one page](https://atd.knack.com/smo#impounds/) in Shared Mobility, it appears on all other login points.

**Comment by ChrispinP** [comment]
Posted these in Slack but posting here as well so we can keep tabs on them:

You must click on report name or chart to open report edit view:
![image](https://user-images.githubusercontent.com/67915167/116122331-3d0d2700-a687-11eb-8995-a63422a0f3af.png)

Adding a new Details view to the top of a page shrinks the page rule message to single column width:
![image](https://user-images.githubusercontent.com/67915167/116122465-6e85f280-a687-11eb-8810-980b84e96eab.png)

Row Hover not working:
![image](https://user-images.githubusercontent.com/67915167/116122657-b4db5180-a687-11eb-91af-74d0c4684d29.png)


I have reported these issues to Knack

**Comment by ChrispinP** [comment]
The report edit button, the table row hover, and the expanded group records issues have been fixed.

**Comment by dianamartin** [comment]
Outstanding: `Custom SSO login buttons not rendering` #5925

**Comment by dianamartin** [comment]
Finally closing this epic!
