### ISSUE TITLE
Send out communication to Knack stakeholders about new knack backend

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5449]
Communicate with Knack application stakeholders so they are aware there is a change that is happening in the back end of Knack. We would encourage them to reports anomalies or bugs they find in their applications to the DTS group. 

### Time line
2 weeks prior to switch over date - April 16

**Comment by ChrispinP** [comment]
Diana, Surbhi, and I have been notifying stakeholders. A few applications remain which do not need stakeholder notification.

Closing as complete
