### ISSUE TITLE
Implement Mandatory Application - DTS Service Request Form

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#545]
## Description:

1. Make the application field mandatory
    * Update the 'other' value to 'Other/I Don't Know'
2. Map the application field to the GH issue description

**Comment by TracyLinder** [comment]
@amenity FYI

**Comment by TracyLinder** [comment]
See #208 for example of why this would be useful.

**Comment by johnclary** [comment]
Done, except checking the mapping to githhub issue
