### ISSUE TITLE
(Remove) TIA Case Details Attachments 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5453]
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/ab862559-eb7d-438b-9d8b-2c3df4416d10)

**Comment by ChrispinP** [comment]
Case Attachments currently appear when adding other content to a Submission. We removed them from the Case Details page. Would we like to re-add them to the Case Details page or should we place somewhere else?

**Comment by TracyLinder** [comment]
Ask stakeholders: Do they need generic case attachments? _Or is attaching to the case management features all that's needed?_
- If yes, add the table to TIA Case Details
- If no, remove the +Attachments button

**Comment by ChrispinP** [comment]
Removed CSS and Attachment Button

complete
