### ISSUE TITLE
[Bug] Activity feed does not display all project changes as intended 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5456]
- Add additional triggers for every field that can be edited by users, e.g. adding/editing the project team on the "Team" page

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/238

As a first step, I've modified the order in which events are shown. They happen in create_date descending, meaning older events show first. Also, we make sure the project creation is the first event in the list. SQS does not guarantee order of operations, so a user added to a project can make it to the logs before the project creation event so the timestamps are not reflective of what the order really is.
