### ISSUE TITLE
Implement point-drawing in project extent mapping

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5466]
https://nebula.gl/geojson-editor/

**Comment by mddilley** [comment]
As an update, the UI to draw points has been added. There are some styling details to be worked out, but the next steps are:

- [ ] Add the drawn points to the extent associated with the project
- [ ] Generating unique IDs for drawn points and adding metadata so they can be differentiated from points sourced from a vector tile layer
- [ ] Finish out some styling details like changing the cursor in different drawing modes and refining the styling in the draw UI

#### Demo of progress so far
![drawOnly](https://user-images.githubusercontent.com/37249039/113067524-1b9d4600-9182-11eb-8cc7-51fd56297270.gif)

**Comment by amenity** [comment]
😍

**Comment by mddilley** [comment]
Moved some of the tasks above to https://github.com/cityofaustin/atd-data-tech/issues/5749

**Comment by johnclary** [comment]
This is very exciting, Mike!

Meandering thoughts prompted by seeing this visually:

How will the user know if they should draw a points, lines, or both? We intend to add constraints around the kinds of components that will be represented with points vs lines, but component-level detail is not part of the project creation process. At this early stage of project creation, it might be enough to add some helper text on the page. E.g. "Point-y things are signals, sidewalk ramps, and crosswalks. Street-y things are bike lanes and sidewalks"

I wonder if we should just completely shelve project mapping until _after_ project creation. Display a very annoying banner on the project details page when a project is not mapped. This would allow us to have a single interface for project/component mapping. If the project is in its early stages, a user could use that interface to solely add locations without components. We could also redirect the user to the project mapping tab immediately after a project is created...

I'm picturing a kind of stepper workflow when adding a new location. Click a "new location" button, pick the type of component you want to add, and automatically enter drawing mode for that component type (e.g., pick a signal, begin drawing a point).

**Comment by amenity** [comment]
>It might be enough to add some helper text on the page...
_"Map the general location of your project using **points** for work at intersections or crossings, e.g. signals, crosswalks, and ramps. Use **lines** to identify work that follows a stretch of road, such as sidewalks and bike lanes._

>I wonder if we should just completely shelve project mapping until after project creation. Display a very annoying banner on the project details page when a project is not mapped. This would allow us to have a single interface for project/component mapping. 
Totally get where you're coming from and am willing to go there if it makes sense. Concerns:
- If a user creates a new project and straightaway gets an annoying banner, that's a pretty bad vibe. They may put off mapping components because it's truly complicated/time-consuming/uncertain. I'd prefer to use annoying banners sparingly so users don't get banner blindness or just feel subtly guilty and chided every time they open Moped. :P  
- The "New project" workflow should be, I think, an easy "ceremonial" way to create a new project... That's why we went with the stepper component. Without the mapping step, it doesn't feel nearly as special. 
- Moped is, potentially, where staff can stash their fantasy/clever/long-shot/pet projects (like a virtual whiteboard) and see where there are opportunities for collaboration or knowledge-sharing. Getting this type of data without a location is just noise, though. 

What about...
- Remove the points from the "New project" workflow so that extent mapping is the simple segment selection that we've been demoing to users (what's on Production now). To address cases like Renée's, where it's silly to use segments to map a project, provide an option to skip mapping and go straight to components?
![Screen Shot 2021-04-08 at 2 29 51 AM](https://user-images.githubusercontent.com/1463708/113985993-5eaa8980-9812-11eb-8384-408ec1583d19.png)

Could also be a checkbox below the map with something like that. If users choose to skip mapping location, they're taken directly to the component-drawing stepper workflow you're envisioning, @johnclary, and not able to leave until they've defined at least one component. 
 

>stepper workflow when adding a new location. Click a "new location" button, pick the type of component you want to add, and automatically enter drawing mode for that component type (e.g., pick a signal, begin drawing a point).

👌 💯 Sound great. 
(Only the button would say "new component" not "new location," right?)
