### ISSUE TITLE
Project: E-Citation System for Parking Enforcement

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#547]
Parking Enforcement currently uses APD's citation system (Brazos). As a result, we receive limited support, and staff are unhappy in general with the solution. This project will deliver an ATD-owned citation system for parking enforcement.

**Comment by amenity** [comment]
@johnclary - this looks like a dupe of #595 ... yes?

**Comment by johnclary** [comment]
@amenity the challenges around #595 is one of the reasons we want to do this project, which is to procure and/or have our own relationship with Brazos. We've identified this is a project that Stephanie could take on with whatever time is not dedicated to RPP. So I think 595 should icebox until we address this one here. cc @TracyLinder

**Comment by johnclary** [comment]
Blocked pending PE's decision to begin this procurement. My last email to Jason R:

> Jason—remind me: I know y'all have intentions to re-evaluate Brazos and possibly procure a different solution for parking e-citations. Any idea what timeline y'all are on for that?
> 
> Some background—we received a request from the parking enforcement folks related to their dispatch tracking. Basically, the ask is that we move this out of Sharepoint and into a Knack-based system. That sounds good, and  Stephanie will be meeting with them on the 15th to capture the need in detail. 
> 
> I can see that there's a lot of duplicate data entry going on with regard to citations, CSRs, and reporting. The e-citation system is a big piece of the puzzle. So that's where I'm coming from.
> 
> Thanks.

**Comment by johnclary** [comment]
Per Jason R. an e-citation procurement is years away. We're stuck with Brazos.
