### ISSUE TITLE
[TDS] Build Customer/Third Party/Requester Help Menu

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5474]
Use a tabbed menu for table of contents. Use images, tables, and links where useful.

A How To: Submit a Development Review
A How To: Submit a TIA Request
A How To: Access and Review Case Status
A How To: Submit a Submission/Scope Submission
Reference: Development Review process for the Customer
Reference: TIA Request process for the Customer
Reference: Searching/Looking at Developments/TIA Projects/TIA Mitigations

**Comment by ChrispinP** [comment]
Submitting a Submission video is currently being edited and reviewed.

Need to determine if any other how to documentation is needed or if there should be any sort of help menu.

**Comment by TracyLinder** [comment]
Materials will need to be updated to include instructions about the access code.

**Comment by TracyLinder** [comment]
This work has been done on various other issues. Closing this.
