### ISSUE TITLE
FormStack Research 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5479]
Called Amber T. with CTM Admin for FormStack to learn what I could about the licenses/management

**Comment by dianamartin** [comment]
@amenity @johnclary 

# Notes
CTM license management - loans out licenses out for 30 days
- manage the form
- edit the form 
- check submission

30 days cycle can licenses can be checked-in/checked-out
CTM has limited licenses: 75
Some licenses are reserved for admins, so lower than 75 really
They keep a close watch of license usage

A user can user a license if they are "actively"
- building
- testing 
- editing a form

If after 30 days, license gets checked back in
- saw in 6 months you need to add a field
- Contact Amber/put in ticket so she can reissue license

##New FormStack License requests
User must complete a `Form Guidance request` form - idea on how they intend to use it
This is also a FormStack form 
- Form is submitted, emailed to help desk, they create a ticket and assigned to Amber

### They suggest using FormStack 
when using it as a public facing anonymous form

For internal folks - they suggest MS Forms, SharePoint
If an internal form requires attaching  documents - they're more lenient on usage

Amber says, when a user requests a license that's had one before, it can be issued pretty quickly
- If you know Amber well (which I do) she can give you a license within 30 min to 1 hour

**THINGS TO KNOW**
There is a submission limit: 10k submissions
After 10k, submissions don't get stored on FormStack DB, you will get them via email (as long as it's set up)

Workflows can be used in FormStack, they don't allow the FormStack platform to sent submissions to outside entities. If a user submits or forwards the information then it's okay. 

For AMD USE CASE - Amber suggests maybe using
Nintex Form - example (she'll share an example to see on a mobile device)
Nintex (front end) - SharePoint List (back end)

ENVIRONMENT
FormStack Instance - City of Austin Form Stack 
Municipal Court Instance to ATD Instance 
- We co-exist, our forms are in folders that we can access

If we wanted our own instance of FormStack
It would not be connected to the City of Austin - ex. "ATD FormStack"
CTM will not pay for that or manage the instance 

ISSUES IN THE PAST
FormStack: Themes/Styles 
A developer in Muni Court 
- Added header code 
- Theme got corrupted 
- Broke all of their forms
- Logic stopped working
CTM helped with this problem bc the Municipal Court was in their instance

MANAGEMENT
CTM Admin manages all the licenses for everyone and keeps track of those
There's not an easy way to see who belongs to what department or when the last time the user had used it
- Can't denote the last time you first created the license
- There's a decent amount of administrative overhead
- She manages the licenses and sends out reminders to users: a week before license set to expire and the day license expires
- She estimated it take about 1/3 of her time 

OTHER INTEGRATION
If you create a FormStack front end and have submission emailed to shared email inbox
CTM person has been able to scrap that information and push into SharePoint list

ATD USERS
- Mary Vo
Dockess Inspection License Application
Accessible
Ground Transportation Complaint Form
Volunteer 
Get Home Safe parking Ticket
RPP - Transportation Street Request 
- Andrea Martinez
Shared Mobility License Check list
- Amenity Apple
- Darren Ujano 
- Paloma Amayo- Ryan
Excavation Applications
ROW Damages
Extension revision request
 
FORMS that don't have submissions, some created by CTM ADMIN for ATD staff.  We need to check with staff if they know these forms exist. 
- ROW License Renewal
- Dockless Transportation System License Application Workflow
- Residential Permit Parking Street Request
- Commercial Delivery Loading Permit
- Dockless Mobility License Application

**Comment by johnclary** [comment]
thanks @dianamartin! Really helpful.

Would you mind asking Amber if we would be allowed to use these features? 

- [Webhooks](https://help.formstack.com/hc/en-us/articles/360019516191-WebHook-Submit-Actions)
- [Formstack Go (mobile app)](https://www.formstack.com/features/formstack-go)

And I'm curious if any other departments are using [payments](https://www.formstack.com/features/payment-processors).

**Comment by dianamartin** [comment]
@johnclary I can ask Amber about webhooks and FormStack Go, but she specifically said the COA instance allow the use of payments the other day.

**Comment by dianamartin** [comment]
# RPP Prototype Screen Shots
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/57c63e13-ea1b-4fef-aad2-87b3d0303e3d)
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/1a111c4c-7557-4e91-9665-040670723750)

## FormStack GO

**Comment by dianamartin** [comment]
# AMD Signal Inspection Punch list on FormStack GO app
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/b7350a73-6806-43a0-8a71-360258d10d62)
## Could take a photo or select photo from gallery
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/1e09984d-8946-44cd-9d07-e82b8ac0fc30)
## Still had to scroll over to mark the other column selection
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/28b61158-9edd-4c10-b9bc-a58da0d7dc78)

**Comment by dianamartin** [comment]
@moorerst I've documented a lot of information about FormStack here. I added more photos from the FormStack GO app. Probably not going to use it for RPP, but thought you should know.

**Comment by dianamartin** [comment]
Going to request FormStack license through CTM to experience the process first hand and then document so that I can share with users interested in getting the FormStack license for themselves.

**Comment by dianamartin** [comment]
Send in request through `CTM Form Guidance Request`, will turn in CTM ticket

**Comment by dianamartin** [comment]
I have access to FormStack and am checking it out now, closing this!
