### ISSUE TITLE
[Product] Sign Fabrication Request Management

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5483]
Will need a solution for sign fabrication requests — currently receive work orders, so many extraneous fields (location, etc.); get requests for retirement signs from other departments aren’t even tracked. - Should be simple; request coming soon

**Comment by amenity** [comment]
Separate page — 

Two types of requests
 - Work Orders related to MUTCD* street signs - kind of "fake" fill out current work order form since not all fields are relevant
 - Non-
    - Retirement signs (requests from other departments)
    - SXSW signs


*Manual Uniform Traffic Control Devices

**Comment by johnclary** [comment]
@amenity what are next steps here? Do we need to be tracking this as a `Project Index`?

**Comment by amenity** [comment]
@johnclary I believe this is actually feature-sized; not a fully-fledged project... Tracking here: [Create a Sign Fabrication Work Order page for Non-MUTCD signs](https://github.com/cityofaustin/atd-data-tech/issues/5485 )
