### ISSUE TITLE
Perform usability testing with Joe Michael, Tooran, and a contractor

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5484]

**Comment by amenity** [comment]
@dianamartin - are we ready to plan and schedule this?

**Comment by dianamartin** [comment]
Messaged Christina this morning 4/20
>Morning, did you guys end up meeting with the contractors yets? Tooran/Joe Mike need to do usability testing?

**Comment by amenity** [comment]
SEFBO will start with crosswalk maintenance since that's a simple place to start.

**Comment by amenity** [comment]
Christina is going to collect any potential enhancements while onboarding everyone.
