### ISSUE TITLE
[TDS] Update TDS Workflow, Customer, Data Diagrams, and Submission Process Video

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5487]
We need to update the Workflow Diagrams for the entire TDS application, both Development and TIA workflows.

Options are to use Miro, Visio, or LucidCharts. 

We may also want to create a Customer Experience Diagram and a DFD as well.

**Comment by ChrispinP** [comment]
Began working on the Customer Workflow so far and created my first rough draft using LucidCharts. Will work on the Reviewer Workflow next.

**Comment by ChrispinP** [comment]
Work on the Reviewer Workflow is underway. I've completed the charts for submitting an application, reviewing a scope submission and all of the features on the Case Details page. More to come

**Comment by ChrispinP** [comment]
Updated the workflows some more after language changes. Need to finish adding Mitigation workflows, simplified process workflows, and update the Customer workflows again.

**Comment by ChrispinP** [comment]
Stakeholders would like to implement an informative Customer Video for the Customer Portal utilizing a Sample Test Case and improved documentation.

**Comment by ChrispinP** [comment]
Finished making rough draft of the Customer Submission Process Video. Getting feedback from Nathan & Joan for final draft.

**Comment by ChrispinP** [comment]
Made adjustments to the Customer Submission Process Video based on feedback from TDS. Will put 2nd edit together and send to everyone for review and add the Application Process to the same video or to a separate video depending on TDS feedback.

**Comment by ChrispinP** [comment]
Awaiting on TDS feedback this week to make final edits to the Customer Submission Video.

**Comment by ChrispinP** [comment]
Received feedback on Video. Will make final edits and prepare videos for Knack. Will also work on a Rough Draft of an Application video.

**Comment by ChrispinP** [comment]
Postponing any work on an Application Process video until after Compliance and Determination changes are complete. Requested a new request be made thereafter.

Video files for the final draft are hosted on the [TDS Portal Gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-Mdw_HGhQRPU5N26oPGn/tia-user-documentation/tia-customer-portal-guide)

Complete and sent email to stakeholders. Pending response to publish and close out this issue.

**Comment by ChrispinP** [comment]
postponing this further until after Customer Portal landing page is live with new banner. :)

**Comment by ChrispinP** [comment]
Throwing back on deck now that Customer Portal is now live

**Comment by TracyLinder** [comment]
We will update & maintain our docs as we go. Closing this.
