### ISSUE TITLE
[RPP] Update RPP Workflow, Customer, and Data Diagrams

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5488]
We need to update the Workflow Diagram for the RPP application.

Options are to use Miro, Visio, or LucidCharts.

We may also want to create a Customer Experience Diagram and a DFD as well.

**Comment by moorerst** [comment]
@chrispin attached is the initial work flow we created for the user interface. Of course this was prior to all the fee changes.
But maybe it can be a starting point
[ATD_Residential_Parking_Permit_User_Interface_work_flow_20200723.pdf](https://github.com/cityofaustin/atd-data-tech/files/6184302/ATD_Residential_Parking_Permit_User_Interface_work_flow_20200723.pdf)

**Comment by moorerst** [comment]
Closing this issue no additional documentation is needed. Additional features will be addressed in vendor solution.
