### ISSUE TITLE
Document Repository | Implement refinements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5496]
Initial implementation: https://github.com/cityofaustin/atd-moped/pull/230

### Files tab
- [x] Title should be "Files" to match tab
- [x] Remove "Project File Attachments" heading inside component
- [x] "File Description" ---> "Description"
- [x] "Created By" ---> "Uploaded by"
- [x] "Created Date" ---> "Date uploaded"
- [x] "File Size" ---> "File size"
- [x] File size should be rounded, no decimals
- [x] Common file size abbreviations; `KiB`, `MiB` ---> `KB`, `MB`

![Screen Shot 2021-03-15 at 6 42 48 PM](https://user-images.githubusercontent.com/1463708/111241503-4789ca80-85cb-11eb-9c44-dad3b3938b71.png)

### Modal
- [x] "Upload Media" ---> "Upload a file"
- [x] Remove icons next to fields
- [x] "File Title" ---> "File name"
- [x] "File Description" ---> "Description"
- [x] "Save" ---> "Upload"
![Screen Shot 2021-03-15 at 6 41 06 PM](https://user-images.githubusercontent.com/1463708/111241317-dfd37f80-85ca-11eb-8ebd-e49042c2a4bd.png)

**Comment by amenity** [comment]
@sergiogcx - this wasn't ready 😅  That's why it was "In scoping" and unassigned. 💁

**Comment by sergiogcx** [comment]
@amenity ah my bad 😅 , feel free to add changes on top of the list :) These are easy fixes and I don't mind coming back later

**Comment by amenity** [comment]
@sergiogcx it was just those two re: file size — h/t @johnclary... Now ready to go

**Comment by amenity** [comment]
@sergiogcx - will you add an estimate to this, please?
