### ISSUE TITLE
Plan Dispatch Tracking Soft Launch

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5501]
Plan and Schedule soft launch using the test system

**Comment by moorerst** [comment]
We have two dispatchers doing user testing this week. They will enter SR's into Sharepoint as they normally do but also enter some of the SR's into the Knack application
Diana developed a Help Guide: https://atd.knack.com/parking-enterprise#help/.

**Comment by moorerst** [comment]
@dianamartin the Dispatcher Metrics (Created By and Modified By) on the Reports page is displaying Number of non-311 SR dispatched by dispatcher. Should we also included the 311 SR's they are creating?

**Comment by dianamartin** [comment]
@moorerst I added that report on the page

**Comment by moorerst** [comment]
@dianamartin the number of 311 SR's seems to be off by 1. I only count 4 311 SR's entered by Hillary.

**Comment by moorerst** [comment]
3 different dispatchers entered SR's into the new system from April 5th to 13th. Received very positive feedback from the Dispatchers during testing.
Next step for user testing will be with the Officers testing uploading images from device while on site and using the Manage My Time feature. This user testing is targeted for the week of April 19th. we have a list of Officers for testing during each shift.

**Comment by moorerst** [comment]
Tracking quick fixes and process questions in issue #5753

**Comment by moorerst** [comment]
Tracking PEO user training on issue #5755

**Comment by dianamartin** [comment]
Shavyvonne said in a communication that she wanted the PEOs to test for a few weeks. I said we should wrap up testing on Apr 29th, so that on the 30th we can make changes before the May 3rd Go-Live.

**Comment by moorerst** [comment]
Closing this issue we completed user testing with the Dispatchers and will end user testing with the PEO's on 4/29. Issues for each user testing are captured in separate issues.
Testing was very successful for Dispatchers and PEO's
