### ISSUE TITLE
Create web app for collecting and editing bike parking data

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#5503]
As stated in #5329 , Crowdsource Reporter won't solve all of our bike parking mapping issues, and would present new barriers. Creating a browser-accessible web app that would draw the data with the correct symbology (Type and Status), use templates to create new features, and access the related table for maintenance is the next step.

**Comment by johnclary** [comment]
- Define symbology for all possible racks / create feature templates
- Convert to collector app. Test on Android tablet with @andrewshensky 
- Test with parking meter shop

**Comment by alan-deanda** [comment]
ESRI symbols are not cutting it. With simple shapes, it is difficult to see the logic between the symbol choice once we introduce more than 3 symbols, and with this project we have 6 symbols. I'm moving on to designing PNG symbols in illustrator - I'll continue symbolizing by type and status, but showing greater difference between symbols.

**Comment by alan-deanda** [comment]
![image](https://user-images.githubusercontent.com/42655533/113457373-7625e480-93c4-11eb-8f5b-c70d305cb5e2.png)
these are the proposed symbols for each rack type. green=good, gray=mapped, orange=needs repairs.

**Comment by johnclary** [comment]
@alan-deanda will finish his symbology work, then pass this off to Andrew to configure pop-ups, etc that mirror the existing web map.

**Comment by andrewshensky** [comment]
**Steps taken for data switchover**
1. Export current data to FGDB in AGOL - 10min
2. Download to local - 5min
3. Take maintenance table from test data and add to FGDB extract (clear any test data) - 10min
4. Append records from Origin table to maintenance table - 5min
5. Remove fields from Origin table that are now in maintenance table - 5min
6. Create 1:Many relationship class-5min
7. Format popups for Origin data and related maintenance table - 10min
8. Make sure attachment tables are added to map viewer in addition to Origin and Maintenance tables-5min
9. Add correct symbology (lyrx in SampleBikeParkingUpdate folder), verify all symbols are included even if no record present in data - 5min
10. Publish to AGOL - 10min
11. Add data to map and verify correct configuration - 10min
