### ISSUE TITLE
Enhancement: Email Body Updates for TCI Folder Reports

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5506]
_Received by email from Ryan M:_

_I'd like to change the default text when an investigation report is sent by email. Currently it is 'Thank you for using our service' which isn't quite the right tone. What is the amount of effort to change this?_

_"Please review the attached investigation report for information on your project. Any listed deficiencies must be corrected. If you have questions, please contact the ROW inspector listed on the report."_

### As a ROW Contractor receiving traffic control inspection reports by email, I want the email body to make sense & be useful. 

**Stakeholder:** Ryan M. w/ ROW

**Acceptance Criteria**
- Applies to folder reports 50563, 50568
- The email body for both of the reports should say:
    - Please review the attached investigation report for information on your project. Any listed deficiencies must be corrected. If you have questions, please contact the ROW inspector listed on the report.

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/8d7b7035-d797-4e4e-adf4-16832c8bbe9c)

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/24c2a773-2263-47e0-89ce-9f8d1724d342)

**Comment by TracyLinder** [comment]
**I'm emailing w/ Ryan to further clarify this request**

- To Ryan: There are 2 TCI inspection emails; the other is attached. Should we use the same language on both of the reports?

**Comment by SubhaShroff** [comment]
@Nadin-Nader  the required change is done in **DEV** for both 50563 & 50568. Below is the demo link, please let me know if its good enough to move to TEST.
https://user-images.githubusercontent.com/51680715/122990791-f3307c80-d369-11eb-8b1f-817611383745.mp4

**Comment by SubhaShroff** [comment]
###Status:
Waiting for feedback to move to TEST.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this looks good to go to TEST.

## **APPROVED for TEST Deployment🎉🎉**

**Comment by SubhaShroff** [comment]
@Nadin-Nader I sent you the TEST deployment plan. Please do the change as in Deployment plan.

**Comment by Nadin-Nader** [comment]
@SubhaShroff I have deployed this to TEST. Please UAT

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I tested it on TEST. It looks as expected.

**Comment by Nadin-Nader** [comment]
@SubhaShroff Finally got a word from Ryan and he said that the format would be:


**“Investigation report - FOLDER# - PRIMARY ADDRESS**

**Comment by SubhaShroff** [comment]
@Nadin-Nader Following is the example of subject line for  a UC permit. Hope that is what expected.
"Investigation Report - 2021-100214 UC - HONEY BEE LANE, Texas, USA
![image](https://user-images.githubusercontent.com/51680715/124933957-ec407580-dfc9-11eb-8fb6-22f17094b73d.png)

**Comment by Nadin-Nader** [comment]
**Status:**
Needs approval to move to PROD

**Comment by Nadin-Nader** [comment]
@Nadin-Nader send UAT email to Darren and Blake, cc Ryan

**Comment by SubhaShroff** [comment]
### Status:
Waiting for UAT happen.

**Comment by Nadin-Nader** [comment]
@SubhaShroff Ryan has approved the body of the email. 

> From: Mooney, Ryan <Ryan.Mooney@austintexas.gov> 
> Sent: Wednesday, July 21, 2021 4:34 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>; Ujano, Darren <Darren.Ujano@austintexas.gov>; Barnard, Blake <Blake.Barnard@austintexas.gov>
> Subject: RE: This is an example of the email sent for card 5506 Enhancement: Email Body Updates for TCI Folder Reports
> 
> The language in the body is correct.
> 
> 
> 
> Ryan Mooney 
> ROW Management │ Division Manager
> Austin Transportation Department
> Direct (512) 974-2482 | Media (512) 974-8000
          
## Approved for PROD Deployment🙌🎉

**Comment by SubhaShroff** [comment]
@Nadin-Nader  PROD deployment request is submitted - SCTASK0153691.

**Comment by Nadin-Nader** [comment]
## **Status:**
Waiting on DevOps to deploy to PROD

**Comment by Nadin-Nader** [comment]
Sent Deb a chat to see what the status of this is.

**Status:**
Waiting on Deployment to PROD and response from Deb

**Comment by Nadin-Nader** [comment]
Spoke to Deb and she informed me that Anu will get to this today.

**Status:**
Waiting on Deployment to PROD (should be done today 7/26/21)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  A moment ago, Anu informed that the changes are depoloyed in PROD.

**Comment by Nadin-Nader** [comment]
Email sent to Ryan, Blake, Darren, Paloma and Tracy stating that the changes are on PROD and that i would be closing the card;

> Hello Everyone,
> 
> Hope you are all doing well. And staying safe. I wanted to let you know that the changes requested by the Enhancement: Email Body Updates for TCI Folder Reports (ZenHub Card # 5506) request is now on PROD.
> 
> If any issues should arise, please do not hesitate to let me know. I will now close the card.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services
