### ISSUE TITLE
Update ROW Permit Data Markup Spreadsheet

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5508]
- Spreadsheet is [here](https://drive.google.com/file/d/1CXcDJY8sVVACbMwKfzncFdzQjnwQy2Yq/view?usp=sharing)
    - [Folder](https://drive.google.com/drive/u/2/folders/1wfqbJh9zsnFy8s7qWgh1RE_UraSBifb4)
- [ ] Create new data sheet specifically for Franchised Utilities related data
- [ ] Email to Ryan, CC @johnclary when done.

**Comment by TracyLinder** [comment]
### Update & Closing

This is an outdated project request that no longer represents active work or business needs. DTS continues to publish open data sets as they are identified.

**Comment by KyleErich** [comment]
Closing based on comment above.
