### ISSUE TITLE
Meeting: RPP V2 Intake meeting

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5511]
Meeting scheduled 3/26
Will add agenda

Attendees: 
- Steve, Jacob, Ryan R., John, Chrispin, Stephanie, Diana

**Comment by moorerst** [comment]
Agenda: https://docs.google.com/presentation/d/1jTdbKiD2Jd4duWFFi9F-mKikRWUN9kaHDhzLD0kqxsI/edit#slide=id.ga906a84050_0_1

**Comment by dianamartin** [comment]
# Meeting Notes
- Wish: by end of Calendar Year (DEC 202)

## Resident Logins
- Log ins: self-service for the customer, so they can manage their history, receipts, applications, permits
- Appears to be a definite Must have!!
- application already completed to be able to renew
- improve customer experience
- payment info - saved? (Wish they could have)

## Renewal Application
- Auto-populate information for next renewal period
- reason for the log-in
- order new permits (several different times, changes vehicle information)
- Digital system - using license plate
- renew every 24 hrs (digital hangtag) --> digital decals

## Auto renewal notices send to residents based on renewal due date
- Do we have to customized the renewal notices?
- Generic notice, "It's time to renew, basic information"
- 6 zones, 5 renew at the same time
- doesn't have to be personalized

## Online Payments
- `Must Have` for this version
- Easier for the staff
- The adoption rate is great so far
- Residents are asking when are we going to pay online??
- "Credit card fees are worth it"

## Digital Permitting with license plate reader by the end of calendar year 2021
LPR: license plate reader enabled (4 vehicles they have now)
Drive by and reads the license plate
Enforcement quicker and efficient
Using LPR for RPP
- No stickers required on their car
- Using Tyler Tech software (doing it for Vehicle for Hire program, not RPP yet) 
  - end of this quarter, will be digitally permitted
- manual bulk update to the digital database
  - Enter to Brazos system, populate the data there
    - Brazos portal: 
  - Tyler Tech: LPR, auto-populate
  - exempt plate list: Court house, state legislatures, police
  - manually entering into that list
  - using the VfH plates into that list
- able to enter their license plates and auto-populates

**Comment by dianamartin** [comment]
@ChrispinP @johnclary @moorerst 
You can add your notes here!

**Comment by moorerst** [comment]
Attendees: John, Chrispin, Diana, Steve, Jacob, Ryan
**Resident Logins**
A must have
Logins will provide self service to look up info, update info
would make for a better customer experience
If payment information could be stored that would be a plus
will allow residents to log in and renew digital hangtags
Update vehicle license plate info 
**Automatic renewal notices**
Currently these renewal notifications a generic
Do these need to be customized with resident specific information?
There is not a need for these notifications to be personalized
**Renewal application auto populated**
With resident logins this would be a Must Have
Populate renewal application from previous transaction
**Online Payments**
Must have
current system is working well online payments would improve the experience
residents ask for it all the time
Will eliminate one extra step for staff and resident
**Digital Permitting by end of calendar year 2021** 
Enforcement is LPR License Plate Reader enabled
Uses Tyler Tech - done for Vehicle for Hire not for RPP yet
By end of quarter will be all digital
License plates are manually entered into the Brazos portal then populated into Tyler Tech system
List is updated the next day
There is an Exempt Whitelist for police, legislatures, etc
How important is the End of calendar year 2021 timeline. The system is working well, residents have adapted well. Online payments is a hold up if we can continue to build out with online payments and resident logins there is no pressure for end of year timeline planning for 2022 would work.
Day Passes/HangTags
Digital Day passes will require a lot of maintenance
There is a lot of day pass activity YTD 464
license plate list will need to be synced more real time if the residents has access to go into the system a assign a license plate to a Day Pass
1 day turnaround for sync will not work. 
Officers can sync in the field depending on reception sync can take a couple of minutes
May need to establish new policies for Officers regarding syncing - Resync at each new RPP zone
From Knack we would need to pull a list of license plates and type of permit to be populated into the Brazos portal and updated in Tyler Tech
**Possible expansion to other types of permits**
Would definitely like to have a central location of all permits ground transportation, commercial loading, rides for hire
In many ways we are working like 1985
**Ability to identify eligible corner lots**
Per Jacob this is a Engineering question
Ryan offered some explanations for why the corner lots are showing ineligible 
Some corner lots have a different address than the address for the RPP zone
Maybe the points can be expanded so the corner lots do appear on the eligible list???
This is something that can possibility be resolved
**Ability to identify primary customer** 
Can have multiple contacts per property Owner, Renter
This will need more scoping
**Replacing Permits**
If permits are not received because of error on our part (lost in mail) there is no charge - there is no way to verify
does not happen too often
with digital permits this will not be an issue
**Additional discussion**
Would like to pull reporting into Power BI
Data would be in the Open Data Portal 
Jacob only concerned if residents are able to see transactions for their neighbors
This would only be # of permits and cost not individual transaction data
Jacob is good with it
Jacob was asked about this being an short term solution and possible integration with Passport at some point soon - he would rather keep it in house likes the personal touch they have now that you would not get with a vendor. Customer feedback is positive, if they use a vendor it will cost more and take more time to implement enhancements. Overall we are pleased with the system and direction we are going.
 
Next Steps:
Schedule Builder Huddle

**Comment by dianamartin** [comment]
Closing issue as there are no additional notes to be added.
