### ISSUE TITLE
V7 - Manually Updating Folder  (NN)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5514]
### As an ATD AMANDA power user, I need to be able to manually update the folder status for various reasons.
- Trello Card [link](https://trello.com/c/z0727dlh/121-atd-cant-manually-update-process-status)

- Who in ROW should have permissions to update folder status manually?
- [x] @Nadin-Nader please meet w/ Izzy to have her test updating folder status & gather feedback from her.

**Comment by Nadin-Nader** [comment]
Sent and email to Izzy asking her to verify that she is able to manually update the Folder status on a folder without issue. I also asked her to verify if her permissions were  correct and to give her feedback on V7.
I also scheduled a meeting for today March18, 2021 @3pm to go over this.

**Comment by Nadin-Nader** [comment]
I met with Izzy Yesterday and she was able to test manually changing the folder status. She was able to and it didnt affect the date adversely. It extended it if it needed to. She also looked into the Oage conflict to make sure the amount of items shown would work for them and it did.

She sent an email with her thoughts (see below):

"From: Pena, Isabell Isabell.Pena@austintexas.gov
Sent: Thursday, March 18, 2021 4:08 PM
To: Nader, Nadin Nadin.Nader@austintexas.gov
Cc: Perez, Kimberly Kimberly.Perez@austintexas.gov; Amayo-Ryan, Paloma Paloma.Amayo-Ryan@austintexas.gov
Subject: RE: Manually Update Folder Status on V7

I made several status changes and the dates were not affected. If a DS permit is put into active status then that would have a change on the date. DS permits are issued for 6 months. If the permit was made active with a status change, then the expiration date should be 6 months from the date it was made active.

I did notice that CTRL R does retrieve like in V6. Do you know if there will be any other hot keys?

Thanks,

Izzy"

I also sent her the hot key screenshot i had from the training (attached)
![A7 Keyboard Shortcuts.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/836078b8-69b0-4850-b9e7-90d084fb1b84)
I also poste dthis in the V7 UAT Trello Board.  Closing card
