### ISSUE TITLE
Add Chia and Andrew to austinmobility.io

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5515]
Add Chia and Andrew to our team's [About](https://www.austinmobility.io/about) page.

[Source code](https://github.com/cityofaustin/atd-product/blob/main/src/views/aboutView/AboutView.jsx)

**Comment by johnclary** [comment]
Might as well assign this one to @chiaberry :)

@amenity would post Andrew's photo here? CC @mateoclarke

**Comment by chiaberry** [comment]
What is Andrew's title? actually what is my title? and does it matter where I insert the photos? Could I just put us at the end of the list?
