### ISSUE TITLE
[TIA] Conditionally Hide/Show Fields based on Improvement selection

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5516]
## Need to confirm w/ Stakeholders if this is MVP

Be able to conditionally hide/show fields based on which Improvement is selected on the Add Mitigation Improvement form (Mitigation Details page).

Add Mitigation Improvement modal page (scene_232)
Add Mitigation Improvement form (view_628)

_Current selections:_

**Improvement**  (field_495)

Construct Turn Lane
Construct New Road
Install Traffic Signal 
Construct Sidewalk
Construct Protected Bike Lane
Stripe New Bike Lane
Relocate Bus Stop
Signal Modifications
Signal Timing Modifications
Construct Urban Trail
Install Pedestrian Crosswalk
Install Pedestrian Hybrid Beacon
Construct Curb Ramps

_Hide/Show fields:_

Improvement Orientation (field_494)
Improvement Direction (field_728)
Improvement Length (field_496)
Improvement Width (field_727)
Improvement Pavement Modifications (field_729)
Improvement Signal Leg (field_730)
Improvement Bike Lane Separation (field_731)
Improvement Bike Lane Striping (field_732)
Improvements for Signal Modifications (field_733)
Improvement Ped Crossing Refuge (field_734)
Improvement Ramp Type (field_735)
Improvement Bulb (field_736)
Improvement Road Crossection (field_737)

**For example;** Construct Turn Lane will need to show Orientation, Direction, Length, and Pavement Modifications while hiding the other fields listed.

**Comment by mddilley** [comment]
Sync'd with Chrispin today. The code will:
1. Hide all fields on load (except Mitigation Location, Mitigation Type, Improvement, Cost, and Recommendation Notes)
2. Unhide the relevant fields once the user chooses the Improvement type (field_495)

**Comment by mddilley** [comment]
I created a [PR](https://github.com/cityofaustin/atd-knack/pull/22) with these updates. The next steps are to update the form that lives at https://builder.knack.com/atd/development-services#pages/scene_232/views/view_628 with all available fields and then update the `fieldsIdsShownOnFieldSelect` config object with the fields that should show on each Improvement dropdown choice.

**Comment by ChrispinP** [comment]
I have added the JS code to the application and tested. Reviewed with Tracy. Everything is working as intended.

Ready to review. Review with stakeholders on the finality of the Improvement list and what maintenance looks like. Also review the individual fields to confirm the data needing to be collected.

**Comment by ChrispinP** [comment]
Thanks Mike for your work on this. Will create any followup issues as necessary for updating the Mitigation form.

Closing as complete
