### ISSUE TITLE
Project Summary: Change default component for boolean fields to switches

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5518]
![Screen Shot 2021-03-03 at 11 57 18 PM](https://user-images.githubusercontent.com/1463708/109919722-c3584e80-7c7e-11eb-904f-1016b630c3bb.png)

- [x] Replace Yes/No dropdown for "Capital funding" with switch used when creating a new project.

![Screen Shot 2021-03-04 at 12 12 33 AM](https://user-images.githubusercontent.com/1463708/109919602-8429fd80-7c7e-11eb-87f4-7997d9389190.png)

- [x] Hide "eCapris subproject ID" if "Capital funding" is switched off 
- [x] Switch should be blue, I think that's `Primary-color` vs. actual hex code

**Comment by tillyw** [comment]
Question/edge case: So, let's say someone selects capitally funded, then they enter and save a subproject ID. But then they change their mind for some reason and unselect capitally funded. The subproject ID field disappears. Do we want the value to persist so if they reselect capitally funded it's still there, or do we want to clear out the value to avoid confusion?

**Comment by amenity** [comment]
@tillyw thanks for thinking this through... I'd prefer to have it persist at least through their "session" ... What's easier from a technical perspective?

**Comment by tillyw** [comment]
> @tillyw thanks for thinking this through... I'd prefer to have it persist at least through their "session" ... What's easier from a technical perspective?

The default behavior would be for the data to persist in the database and be redisplayed if the user reselects the "capitally funded" option. If that's okay, then no further changes are needed!

**Comment by amenity** [comment]
@tillyw - that's just fine. Super appreciate your attention to detail! 🕵️‍♀️

**Comment by johnclary** [comment]
@tillyw @amenity i think we should clear out the the subproject ID value from the database if the user unselects "capital funding". if we persist the data, i can see see confusion if a different user comes to the project later to add a subproject ID and finds a value in that field. it's also quirk to deal with when creating reports from the data.

**Comment by amenity** [comment]
@johnclary — very good points... @tillyw should I create a new issue for clearing the data?

**Comment by tillyw** [comment]
> @johnclary — very good points... @tillyw should I create a new issue for clearing the data?

Thanks @johnclary, I was also concerned that having a mismatch could lead to data quality issues later on. @amenity I think maybe it would be best to include it as part of this issue and potentially resize it later? The two items are so intertwined. I can follow up with you if it seems like it should be a separate issue. wdyt?

**Comment by amenity** [comment]
@tillyw super. I would prefer to keep it in this issue and resize if that makes sense for you.🙏
