### ISSUE TITLE
Project Summary: Implement style refinements to the pencil

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5519]
![Screen Shot 2021-03-03 at 11 57 18 PM](https://user-images.githubusercontent.com/1463708/109919722-c3584e80-7c7e-11eb-904f-1016b630c3bb.png)

On the project summary page:
- [ ] ~Show the edit pencil only on hover (like the "Project name" above).~ Let's hold off on this; was helpful for peeps during user testing
- [ ] Additionally, allow user to edit field : (Minnie Mouse) glove hand on hover, click to turn into "text cursor"; render checkmark and cancel in the field
- [ ] Place the edit icon next to the end of the text
- [ ] Make the pencil color our primary blue color instead of black. This change will need to be implemented in the Project Name

**Comment by johnclary** [comment]
@amenity did i interpret this correctly?
> Place the edit icon adjacent to the label instead of text

**Comment by amenity** [comment]
@tillyw - add an estimate to this, plz 👕 ?

**Comment by amenity** [comment]
@johnclary @tillyw - got feedback from Max S that he wouldn't have known the fields were editable in place if he didn't see the pencil. So putting this in "Needs Scoping" until we get further user feedback.

**Comment by johnclary** [comment]
The pencil has been gone for a while, and we've also got #10419 in review/QA.
