### ISSUE TITLE
Remove Vison Team Column From Reviewer Comments Table (Dev Reviews, Details Page)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5532]
### [View Development Review Details Page](https://atd.knack.com/development-services#development-reviews/view-development-review-details/5d925dcdd8686438e0e6f5b9/), Review Cycles Table

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/e13c0e1c-b544-4f9f-a15b-6a8f3f2c35af)

**Comment by TracyLinder** [comment]
@ChrispinP It looks like you already tried to make this change, but removed the wrong table. Add back the Reviewer column, and remove the Vision Team Column. See screenshot in description.

**Comment by ChrispinP** [comment]
Updated Review Comment Tables, complete
