### ISSUE TITLE
New Page: TIA Customer Portal

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5535]
### New Page: TIA Customer Portal
_Home Page Content: https://atd.knack.com/development-services#tia-portal/_
_URL: development-services#tia-portal-home/_

**Page Menu:**
- Tab: Home
    - TIA Customer Portal Home
- Tab: Help
    - Help Guide

_Home Page Content: https://atd.knack.com/development-services#tia-portal/_

**Comment by TracyLinder** [comment]
Work sesh w/ Chrispin scheduled for Friday 3/26.

**Comment by TracyLinder** [comment]
We need to review w/ stakeholders. What content should go on the home page?

**Comment by TracyLinder** [comment]
**Update:**
- No need to display the TIA Customer Home Page at this time



**Apps Tasks:**
- [ ] Hide TIA Customer Home Page
- [ ] Hide TIA Customer Help Page until we have content for it. 

FYI @ChrispinP

**Comment by ChrispinP** [comment]
removed customer home and help from navigation menu until we have content for them.

Moving issue to Blocked until we have the home information and help pages ready

**Comment by ChrispinP** [comment]
@TracyLinder Need to determine with stakeholders if this is still a need. Would be necessary if stakeholders wanted user logins.

**Comment by ChrispinP** [comment]
closing as duplicate, we now have a new issue for a TDS Customer Landing Page #8236
