### ISSUE TITLE
TDS Portal Home Page Updates

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5537]
### Update the TDS Portal [Home Page](https://atd.knack.com/development-services#home)

- [x] Remap the My Reviews button to link [here](https://atd.knack.com/development-services#reviewer-dashboard/)
- [x] Add Buttons: TIA Reviews, Pre-Assessment Reviews

**Comment by ChrispinP** [comment]
Re-mapped home buttons and added navigation, ready to review

**Comment by ChrispinP** [comment]
no further home page updates at this time, closing as complete
