### ISSUE TITLE
Feature: KNACK TDS Pre-Development Assessments

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5540]
### As a TDS Reviewer, I need a feature or module that allows me to record pre-development meetings (Transportation Development Assessments (TDA)).**
- _**TDA:** A meeting that occurs between TDS staff & a development customer prior to a formal Site Plan submittal, where staff can provide informal consulting on the proposed development._

----
- [x] **Page/Object: Pre-Assessment Review Details**
_Design should mirror [TDS Review Details](https://atd.knack.com/development-services#development-reviews/view-development-review-details/5d925dcdd8686438e0e6f5b9/) as much as possible._
- **Fields**: Project Name, Project Address, Reviewer Area, Case Notes, Applicant/Contact info (free text field, paragraph type), Fee Status (Paid, Unpaid)

- **Buttons:**
    - ➕ TDA Review
    - 📝 Edit
- **Table:** Attachments
        - Button: ➕ Attachment
        - Columns: Remove, Edit, Date, Attached By, Attachment Description, File Link
![image](https://user-images.githubusercontent.com/49930868/111672240-c3f8f500-87e7-11eb-8a37-e1d915383ecb.png)

- **Table:** Meetings
        - Button: ➕ Meeting
        - Columns: Remove, Edit, Meeting Date, Meeting Notes
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/2b60f54b-49b5-4d3d-b189-288b564c6ac0)

 

----
- [x] **Page/Object: Pre-Assessment Reviews**
_Visually & functionally similar to [this page](https://atd.knack.com/development-services#development-reviews/)_
- A page with a table view of the existing TDA Records
        - **Table Columns:** Details (Icon to open record), Project Name, Project Location, Reviewer Area, Case Notes
        - **Table Filters:** North, Central, South (Filter by Reviewer Area)
- **New Button:**  ➕ TDA Review
        - Location: Top left of page
        - Button will open the 'Add TDA Review' form for the user to input new record details
  

------
- [x] **Form: Add TDA Review**
_Visually & functionally similar to [this form](https://atd.knack.com/development-services#add-development-review/)
- Form Fields: Project Name, Project Address, Reviewer Area, Case Notes, Applicant/Contact info (free text field, paragraph type), Fee Status (Paid, Unpaid)
    - After saving the new record, the page should load to the new case record details.

----
- [x] **New TDS Portal Menu Tab: TDA Reviews**
- Menu Options: "➕ TDA Review", "All TDA Reviews"
- ➕ TDA Review: Opens 'Add TDA Review' for the user to input new record details
- All TDA Reviews: Opens Pre-Assessment Reviews Page
![image](https://user-images.githubusercontent.com/49930868/111668567-e25cf180-87e3-11eb-959a-b392c960b7b3.png)

**Comment by ChrispinP** [comment]
I have prototyped this feature.

Ready to review

**Comment by ChrispinP** [comment]
@TracyLinder lets schedule a time to review this feature with the appropriate stakeholders

**Comment by TracyLinder** [comment]
**Status/Update**

- This is being placed in the backlog until the AMANDA portion of this epic is ready to work on, which likely won't happen until October 2021. 
- @ChrispinP please hide the tab & button for this feature on the TDS Portal

**Comment by amenity** [comment]
@dianamartin, please review!

**Comment by dianamartin** [comment]
# Diana's Feedback
## Add/Edit TDA Review
- the `Review Area` field looks awkward in the middle between two paragraph text fields, it seems to get lost. I'd probably move it above the "Project Address" field. 
- Maybe incorporate static headers to break up the sections a bit more, I notice you have them divided up in the TDA Details page

**Comment by dianamartin** [comment]
Reviewed, Chrispin made changes based on recommendations. Whenever Tracy wants to reach out to users to show TDA Reviews then this should be ready.

**Comment by TracyLinder** [comment]
We are meeting w TDS tomorrow 11/4 to provide quick training and prep for an official go-live date.

**Comment by dianamartin** [comment]
@ChrispinP we just captured some changes from our meeting. I'll be updating them whenever you're not in TDS this week.
