### ISSUE TITLE
Style tweaks to navbar layout

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5542]
_Zero heuristic evidence to support this — I'm just always for aligning all the things!_ 📏 🤓

Let's make `.navbar` the same width as everything else and give it a lil' extra vertical breathing room while we're at it. 

- [ ] Add `.navbar` to media queries so it gets that `max-width` 
- [ ] Apply `margin: .5rem auto;` to `.navbar`

Before n' after:
![Screen Shot 2021-03-18 at 1 35 17 PM](https://user-images.githubusercontent.com/1463708/111695596-46da7980-8801-11eb-95c4-495ef5539553.png)

 
![my opinion](https://media.giphy.com/media/MPuTZQqOmYKPK/giphy.gif)

**Comment by amenity** [comment]
Will leave this one to you to Icebox or Backlog, @johnclary

**Comment by johnclary** [comment]
Yes—I am in favor of all changes! Just want to point out the ATD-style wordmark on data.mobility.austin.gov:
<img width="1512" alt="Screen Shot 2022-10-05 at 8 17 32 PM" src="https://user-images.githubusercontent.com/14793120/194186458-892ccfe8-71d9-465d-89ad-2384187dcc8c.png">

**Comment by amenity** [comment]
No longer applicable after the redesign.
