### ISSUE TITLE
Configure activity feed timestamps to display to users in CDT

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5543]
All user-facing timestamps should display in CDT.

See [Slack convo](https://austininnovation.slack.com/archives/CNUEPKLB1/p1616103203036900) for examples. 

This should be handled in the UI since we don't want to maintain original timestamps in the database.

**Comment by sergiogcx** [comment]
For reference, this is a test entry that happened at 4pm, yet it is shown to be at 9pm:

<img width="1498" alt="2021-03-18_16-39-52" src="https://user-images.githubusercontent.com/5282430/111701536-fe26be80-8808-11eb-8e66-d16fe918b81e.png">

**Comment by amenity** [comment]
I mean, if it’s happening in the UI it’s more elegant to detect the user’s own timezone… Initially I thought that was too big an ask but it occurs to me that’s probably an ultra-common use case and there might be utility already available in the React time library y'all are using.
