### ISSUE TITLE
Bug: TIA Mod Menu Hyperlink

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5545]
### Hyperlink opens an [empty page](https://atd.knack.com/development-services#tia-reviews2/).

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/bfef731b-a5b9-48dd-8c40-34872b8454c8)

**Comment by TracyLinder** [comment]
@ChrispinP let's discuss this before you work on it. 👍

**Comment by ChrispinP** [comment]
@TracyLinder wow, this happens for all menus. Knacks creates a "fake" page for each menu. In the builder I dont see any way for me to edit these blank pages. Will submit a Knack ticket and test in new builder to see if the issue carries over.

Nice catch, thanks

**Comment by ChrispinP** [comment]
Issue also applies to the new builder. Sent a message to Knack about the bug. Pending response.

**Comment by ChrispinP** [comment]
Knack has confirmed this as a bug and is working on a fix.

**Comment by TracyLinder** [comment]
Chrispin built a work-around; bug has been fixed. Closing.
