### ISSUE TITLE
Project Components | Update data model to include project and component attributes for project/component switching/hybrid

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#5556]
**Goals:**

- Enables devs to re-use project paths/routing and project features for components that need to be both a project and a component.
- Simplifies a component-heavy data model by allowing components to maintain the same kinds of attributes a project might collect (or vice-versa)

**Outstanding Questions:**

- Can components become projects from the UI? #5558 might solve/assist with the complexity here.
- Can projects become components from the UI? #5558 might solve/assist with the complexity here.

<img width="786" alt="projects, components, and relationships" src="https://user-images.githubusercontent.com/34947604/113936521-dd2d0a00-97c5-11eb-97f1-b74a212b4196.png">

**Comment by johnclary** [comment]
Closing since we've decided to go with a simple one-many relationship between moped projects
