### ISSUE TITLE
Project Relationships | Add project-to-project relationships

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#5558]
As a user navigating the details of a project, I want to relate projects together so that I can later view a list of projects relevant to this project.

**Details:**
- A project can be a **child** of another project
- A project can be a **parent** of another project
- A project can simply be **related** to another project (no hierarchy)

Ignore components below, but idea would be to create a table that maintains associations between projects
<img width="786" alt="projects, components, and relationships" src="https://user-images.githubusercontent.com/34947604/113935893-15801880-97c5-11eb-8827-122ac03fa03c.png">

**Notes:**

Future (nice-to-have, maybe never-have): we could add some mechanism for projects to inherit attributes from their parents or the user could select which attributes to inherit (of a finite list we decide won't cause tons of issues)

**Comment by johnclary** [comment]
Closing this since we solved this with #9267
