### ISSUE TITLE
Project Components | Define data model

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5559]
### Reference
- https://hasura.io/blog/native-support-for-postgis-topology-operators-now-in-graphql-engine/
- https://hasura.io/blog/building-a-realtime-geolocation-app-with-hasura-graphql-and-postgis/
- [John's Mapping thoughts deck](https://docs.google.com/presentation/d/1u-ehecX1noZRsdh8gbmf2VqpTeBf5r4s-mkBgiAM35g/edit#slide=id.gbd2a54ca88_0_12)
- [IMPDB facility (component) types](https://docs.google.com/spreadsheets/d/1rgw3KL9fQ0xS49LLyzexHMPbV58WsWcr2jYaC2oSmKM/edit#gid=1948602978)
- [Project Components | Define (initial) Moped 1.0 "Component Type" taxonomy](https://github.com/cityofaustin/atd-data-tech/issues/5357)

**Comment by amenity** [comment]
### Reference
**Hasura + Postgres**
- https://hasura.io/blog/native-support-for-postgis-topology-operators-now-in-graphql-engine/
- https://hasura.io/blog/building-a-realtime-geolocation-app-with-hasura-graphql-and-postgis/

**Comment by amenity** [comment]
@zappfyllc - can you schedule this one? @johnclary @mateoclarke and myself optional, I believe. Don't worry about accommodating my calendar, will plan to just drop in to listen if available.

**Comment by zappfyllc** [comment]
Meeting scheduled for March 30th. Outstanding questions:

- What format do we store the GIS data for project extent and/or components? (PostGIS vs. GeoJSON)
- Where do we associate tabular data (project components) with GIS data? (e.g. in the projects table, in the components table, etc.)

**CRUD use cases:**

- Create a new project component and associate it with existing geometries/locations
- Create a new project component and create new geometries/locations associated with the component
- Update an existing project component and change its existing geometry/location
- Delete an existing project component without removing its existing geometry/location
- Delete an existing project component AND its existing geometry/location

**Comment by zappfyllc** [comment]
@zappfyllc add notes from 3/30 meeting later for this issue once the notes are organized and not your jumbled thoughts :)

**Comment by zappfyllc** [comment]
@amenity @johnclary I added my comments here and #5651 covers the next step in this process so this can be closed whenever but I'll keep it open until you've had the chance to review/want to close it.
