### ISSUE TITLE
Feature: TIA Cases Advanced Search Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5567]
### Make an advanced search page for TIA Cases. 
- Visually & functionally similar to the [TDS Review Search](https://atd.knack.com/development-services#search-reviews/)

**Comment by ChrispinP** [comment]
Created the initial Search TIA Cases page with results linking to the Case Details page.

Need to determine what others fields need to be searchable or viewable.

**Comment by TracyLinder** [comment]
Looks great.
