### ISSUE TITLE
Give new folks access to Transportation.Data inbox

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5569]
[Per Slack](https://austininnovation.slack.com/archives/G010RPYJ83W/p1616162774014900):
- @tillyw 
- @andrewshensky 
- @chiaberry

**Comment by dianamartin** [comment]
CTM Ticket has been created `INC0090422`

**Comment by dianamartin** [comment]
8 days ago..

Got confirmation from Chia that she could open the inbox. 
>i was able to open it in the web email, is the inbox empty?

Andrew needed help to add the inbox, but was able to see it afterward. 
>That worked, I was able to open the email box that way. Thanks!

Tilly confirmed she could see the 
>Worked for me! I sent a test email as well and received it via transportation.data. Thanks, y'all!
