### ISSUE TITLE
Meeting: Digital Petition Kickoff Meeting

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5575]
Agenda: https://docs.google.com/presentation/d/1dvejiPcINaZbiQAoOiu9gHWGpQqzOIRIh1t7884lu30/edit#slide=id.p

Attendees: Diana, Stephanie, Ryan
Was out due to schedule conflict:  ~Joseph~

**Comment by moorerst** [comment]
@john here are the notes from the Digital Petition Kickoff - Ryan had a very positive response to the form and the process. You'll see a few questions/action items in the notes. Joseph was not able to attend the meeting Ryan will brief him and we'll send him a link to the test form. We'll follow up next week.

**Comment by moorerst** [comment]
Joseph was not able to attend the meeting. Forwarded email 3/24 to Joseph and Ryan recapping what was proposed in the kickoff meeting.  
Sent follow up email 3/30 - waiting response

**Comment by moorerst** [comment]
email response from Ryan: 
Good Afternoon Stephanie,

Thank you for the follow up email. I don’t believe Joseph has had a moment to review the RPP Digital petition process. He should be able to get to it by the end of the week. I do have a question though. Can you please remind me what my to do’s are? I started to write them down but got distracted and didn’t finish them. I know one of them was to speak to Joana about a legal issue but I wasn’t sure what exactly it was. Thank you in advance. 

Reply: No problem. We'll wait to hear from you. Action items are listed at the bottom of the original email. Thanks

**Comment by dianamartin** [comment]
Closing issue, we had this meeting and have created additional issues if needed
