### ISSUE TITLE
Inspections, Report 4

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5579]
**Stakeholder:** Ryan
Main Report Sample Layout: 
![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/a60e1f1f-d317-448d-aca1-849d12d77d3c)

Acceptance Criteria: 
- From Date and To Date should be available to select as report parameters. 
- From Date and To Date is based on Folder InDate.
- Report should pull data from EX folder (all subtypes) and RW folder (Temporary Right of Way Subtype ONLY).
- Report data should not take into account any deficiencies in "Void" status 
- The data for the report needs to come from the following sources: 
-- Department: One row for each drop-down value in Info 76765
-- Number of Attempts: Sum of the number of attempts made in each qualifying folder's Traffic Control Inspection process
-- Number of Deficiencies: Sum of the number of deficiencies added in each qualifying folder's Traffic Control Inspection process 
-- Average Deficiencies: The average number of deficiencies added in each Traffic Control Inspection Process 
-- CIP: Any folder where info 76352 "CIP?" is populated as "Yes" 
-- Non-CIP: Any folder where info 76352 "CIP?" is populated as "No" 

Subreport (Drill-down) Sample layout: 

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/f23d956b-ad32-4e8a-a4b7-273cd1c89ce8)

- There needs to be one table in the subreport for each department, i.e. the subreport needs to be grouped by department. 
- The data contained in the Subreport should come from the following sources:
-- Permit Number:  Folder Reference Number
-- Folder Name: Folder Name
-- CIP (Yes/No): Based on value provided in Info 76352
-- Applicant Name: Contact field of Applicant People Record in the folder
-- Right of Way Contractor: Contact field of Right of Way Contractor People Record in the folder
-- Attempt Result comment: Any attempt comments recorded in the Traffic Control Inspection Process (Each attempt comment will be one row in the drill-down report). 
-- Attempt Date: The corresponding Attempt date to each attempt comment shown in the report. 

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/1697aec3-14d4-4170-9c0c-1b5ee3605d99)

**Comment by vschandramouli** [comment]
Outstanding questions: 

1. For average deficiencies, would it be okay to calculate per process instead of per attempt?

**Comment by vschandramouli** [comment]
Possible report layout: Need to confirm with Ryan. 

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/a21db768-c232-48f5-85f0-5d57a0551053)

**Comment by vschandramouli** [comment]
Had a meeting with Ryan, finalized AC. Currently working on converting notes into usable AC for this ticket.

**Comment by vschandramouli** [comment]
@TracyLinder @Nadin-Nader Could you take a look at this ticket too?

**Comment by TracyLinder** [comment]
@vschandramouli it looks great. I'll move to backlog. Good work.

**Comment by SubhaShroff** [comment]
Status: Currently Working on, in progress.

**Comment by SubhaShroff** [comment]
### Status:
In Progress.

**Comment by Nadin-Nader** [comment]
@Nadin-Nader move file to DEV for Testing

**Comment by SubhaShroff** [comment]
### Status:
Sample report output is sent this morning for review to @Nadin-Nader  @vschandramouli  @TracyLinder.

**Comment by TracyLinder** [comment]
### Tracy's Notes on PDF Sample:
- 1st page looks great



- For the 2nd portion of the report, please show the column names at the top of each page:
![image](https://user-images.githubusercontent.com/49930868/118010581-cde53300-b314-11eb-835a-468f2a73ee90.png)




- On the 2nd page there are no permit numbers in the permit number column. Is this a bug? 
![image](https://user-images.githubusercontent.com/49930868/118010835-0258ef00-b315-11eb-84ea-0c0f6279c0d8.png)

FYI @SubhaShroff & @Nadin-Nader

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader 
- Added the page header from 2nd page onwards. Following attached PDF is the latest one for your review.
- Permit number is showing empty for most of the permits, because the respective column (folder.referencefile) is null for those permits. As the column is not editable, I couldn't add any value to it in those permits.  There are two permits on page 3 & 4 displaying the Permit number.

[99021_TCI_Inspections_Report.pdf](https://github.com/cityofaustin/atd-data-tech/files/6474494/99021_TCI_Inspections_Report.pdf)

**Comment by vschandramouli** [comment]
@TracyLinder @Nadin-Nader After reviewing sample report by Subha and having a conversation with Stakeholders, I added one more AC to the sub-report: 

- There needs to be one table in the subreport for each department, i.e. the subreport needs to be grouped by department. 

Also, in the main report, the average of all the averages that Subha has displayed does not seem accurate and I am not sure that it adds value or would be confusing to users. It may be better to remove it. Thoughts?

CC @SubhaShroff 

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/8ca90a13-cf27-42d8-93b3-950ca10a4b54)

**Comment by SubhaShroff** [comment]
@vschandramouli  @Nadin-Nader  @TracyLinder The grand averages can still be calculated as:
(sum of CIP Def Averages )/ (Total no. of CIP TCIs)
The same formula can be used for NonCIP also. In the following table its done that way. In both cases total of TCIs is 4.
![image](https://user-images.githubusercontent.com/51680715/118306502-294b2880-b4af-11eb-9667-bdcf91902b57.png)

**Comment by Nadin-Nader** [comment]
@SubhaShroff @vschandramouli the averages can be left blank per Ryan M. then we can proceed from there.

**Comment by SubhaShroff** [comment]
@vschandramouli @Nadin-Nader  The changes are done. Here is the latest Report output.

[99021_TCI_Inspections_Report.pdf](https://github.com/cityofaustin/atd-data-tech/files/6481202/99021_TCI_Inspections_Report.pdf)

**Comment by vschandramouli** [comment]
@SubhaShroff I think it looks great.

**Comment by SubhaShroff** [comment]
### Status:
Should I move it to TEST?

**Comment by Nadin-Nader** [comment]
@SubhaShroff looks good. Go ahead and Promote.

## **Ready for TEST Deployment🎉🎉‼**

**Comment by Nadin-Nader** [comment]
Request to deploy to TEST has been submitted by Subha under **SCTASK0139325**
## **Status:**
Waiting n DevOps to Deploy to TEST

**Comment by Nadin-Nader** [comment]
@SubhaShroff I have deployed this new file to the DEV/TEST reports location. Please test it and let me know the outcome. I will also try to get the Stakeholder to test on TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader I tried to access report #5579, but I couldn't see the report on TEST with my login. I sent you an email this morning about it  with the screenshot.

**Comment by TracyLinder** [comment]
I'm updating the pipeline from In Progress to Review Q/A
Just FYI

**Comment by Nadin-Nader** [comment]
@SubhaShroff please try to run the report again to test it

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  @vschandramouli   My  login may have role permission issue, so I couldn't get the report displayed. But Nadin, Anu tested on TEST Amanda and they could see the report. Here is the downloaded report that is shared by Nadin with me. Kindly let me know your feedback.

[CustomReport_servlet.pdf](https://github.com/cityofaustin/atd-data-tech/files/6554600/CustomReport_servlet.pdf)

**Comment by TracyLinder** [comment]
@vschandramouli please help coordinate UAT for this one. Thank you

**Comment by Nadin-Nader** [comment]
Vish has scheduled a UAT Session with Ryan for Monday 6/7/21 at 2pm

**Comment by vschandramouli** [comment]
Performed UAT walkthrough with Ryan M and Darren U. Report output format looks good and information displayed looks appropriate per Ryan and others. 

@SubhaShroff  Please work on deployment for PROD. 

CC @Nadin-Nader

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @vschandramouli 
PROD deployment request is submitted -  SCTASK0143247 (INC0106738).

**Comment by SubhaShroff** [comment]
### Status:
PROD Deployment is done. :)
**NOTE:** George Shirai from CTM Team has suggested to check if it is done, properly, as he doesn't promote the reports, often.

**Comment by Nadin-Nader** [comment]
@SubhaShroff Awesome. I will send an email to the stakeholders and close this out

**Comment by Nadin-Nader** [comment]
Sent email to Ryan and Darren informing them that this is now on PROD and that i will be closing the card on Wednesday if there are no issues. (see email below)

> Ryan/Darren,
> 
> Hope you are doing well. I am reaching out regarding the Inspections Report 4, Card #5579. It is now on PROD and ready for your use in the ATD Report menu. 
> 
> Please let me know if there are any issues. I will keep this open until Wednesday to make sure you have enough time to report it and that there are no issues with it. 
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services
> ————————————————————————————
> transportation.data@austintexas.gov 🚦 austinmobility.io
>

**Comment by Nadin-Nader** [comment]
## **Status:**

On PROD, Keeping open til 6/11/21 (Wednesday)  and closing then if no issues are reported

**Comment by Nadin-Nader** [comment]
Got a response from Ryan asking if this was the report we went over the other day in the meeting. I responded with yes and to let me know tomorrow if the report is good to go on PROD. If it is i will close the card. Email below:

> Yes sir it is. Let me know tomorrow if everything is good and I will close the card
> 
> From: Mooney, Ryan <Ryan.Mooney@austintexas.gov> 
> Sent: Wednesday, June 9, 2021 2:38 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>; Ujano, Darren <Darren.Ujano@austintexas.gov>
> Cc: Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>; Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: Permitting Metrics INSPECTIONS Report 4 #5579
> 
> This is the one we went over earlier this week right?

**Comment by SubhaShroff** [comment]
### Status:
PROD deployment is done. As per Nadin's comment above, we are waiting for Ryan's response to close this.

**Comment by Nadin-Nader** [comment]
Closing by COB Today 6/15/21 Email sent to Ryan by me below:

> Ryan,
> 
> Hope you are dong well. I was reaching out to inform you that the Inspections report is on PROD and since I have not heard back from you saying that there is an issue with it, I will go ahead and close the card #5579 by 4pm today if I have not heard back from you.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services
> ————————————————————————————
> transportation.data@austintexas.gov 🚦 austinmobility.io
>

**Comment by Nadin-Nader** [comment]
Closing Card as i have not heard back from Ryan saying that there are issues with this.
