### ISSUE TITLE
New info: 'CIP?' | Vales: Yes, No

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5580]
### As a ROW Manager, I need to report on CIP-permit data.

**Stakeholders:** Ryan, Darren, Paloma

**Acceptance Criteria: **

- System should display a new info field 'CIP?' of Boolean type in the AMANDA Back Office and Public Portal. 
- The new info should display in the back office and portal for the following permit types and subtypes: 
-- EX
-- RW, Temporary Use of Right-of-Way (TURPS)
- The new info 'CIP?' should display under the Info Group 'Project Information'.
- The new info should not be mandatory for populating in the Back Office or the Portal.

**Comment by TracyLinder** [comment]
@vschandramouli can you please add acceptance criteria for this please?
- EX
- RW, Temporary Use of Right-of-Way (TURPS)

**Comment by vschandramouli** [comment]
Updated AC, Moving to Backlog.

**Comment by TracyLinder** [comment]
Thanks @vschandramouli it looks good. I added user stories to the description. This is ready for development.

**Comment by Nadin-Nader** [comment]
@TracyLinder Moved to on Deck and assigned @subha to look at it.

**Comment by SubhaShroff** [comment]
DEV Promotion Request for the changes done is raised: **SCTASK0131373**

**Comment by SubhaShroff** [comment]
Status: Dev promotion is done. Need to be tested by me.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  I have sent you the demo for this ticket today (4/15/2021).

**Comment by Nadin-Nader** [comment]
@SubhaShroff i have reviewed the demo and it looks good. Let me see what the Stakeholder says, then we can proceed.

**Comment by TracyLinder** [comment]
**Status:** Pending stakeholder feedback.

**Comment by Nadin-Nader** [comment]
@TracyLinder @SubhaShroff Both Paloma and Kim are busy for the reset of the week and will most likely not be able to get back to us fast. I sent them the demo via email to review and asked for their feedback. If anything we can go over it in our weekly ROW meeting tomorrow 4/23/21.
Here is the demo:

https://user-images.githubusercontent.com/63309637/115780913-59efe480-a37f-11eb-81b7-1fc9472d365d.mp4

email sent:

> Hi Kim and Paloma,
> 
> Hope you two are doing well. I was reaching out regarding card #5580 where it was requested to have a new info stating if it was CIP or Not. I am attaching a demo of the changes, to this email for the both of you to go over.
> 
> Please let me know if this was what was needed. Once approved we can try to get this through to CTM and deployed to all environments.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services

**Comment by Nadin-Nader** [comment]
## **Status:** 

Waiting on Paloma/Kim's Feedback to proceed to TEST

**Comment by TracyLinder** [comment]
**Stakeholder Review:**

@SubhaShroff please group this in the Project Information grouping that already has CIP related info in it.

**Comment by SubhaShroff** [comment]
![image](https://user-images.githubusercontent.com/51680715/116305605-9ea5c200-a769-11eb-89f8-dd838e02a4f1.png)

**Comment by SubhaShroff** [comment]
![image](https://user-images.githubusercontent.com/51680715/116307557-1a087300-a76c-11eb-84dc-269ad66367c7.png)

RW

**Comment by SubhaShroff** [comment]
**Status:** Grouped 'CIP?' with other CIP related infos. The above screenshots are from local branch. 
@Nadin-Nader  @TracyLinder  if those screenshots look good, I can commit the changes.

**Comment by TracyLinder** [comment]
### Update
- Stakeholders approve. Please commit.

**Comment by SubhaShroff** [comment]
Status: **SCTASK0134855**(27c4283b3046)  is submitted for DEV deployment(5/3/2021)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  The deployment is done DEV. Below are the screens on DEV, displaying 'CIP?' under project information group. Kindly let me know if this looks good to move to TEST.


![image](https://user-images.githubusercontent.com/51680715/117059313-4892ca80-ace5-11eb-8bf0-ea909fcda4d2.png)
![image](https://user-images.githubusercontent.com/51680715/117059372-5ea08b00-ace5-11eb-97f0-4439b0c0d098.png)

**Comment by TracyLinder** [comment]
Hi @SubhaShroff , will the value on both folders default to No? 

Thanks,

**Comment by SubhaShroff** [comment]
Yes @Tracy. It will default to 'No' for both folders.

**Comment by SubhaShroff** [comment]
### Status:### 
I did DEV test and screenshots are given above. Waiting for approval to move to TEST.

**Comment by Nadin-Nader** [comment]
## **Approved for TEST Deployment**

**Comment by SubhaShroff** [comment]
@Nadin-Nader **SCTASK0136285**(d33e2414d0d8, 27c4283b3046)  is submitted for TEST deployment.

**Comment by SubhaShroff** [comment]
### EX
![image](https://user-images.githubusercontent.com/51680715/117849616-1ab00780-b24a-11eb-932b-61ec68b40aa5.png)

### RW TURP
![image](https://user-images.githubusercontent.com/51680715/117850850-55666f80-b24b-11eb-801e-6032191f9524.png)

**Comment by SubhaShroff** [comment]
### Status:
@TracyLinder @Nadin-Nader  Tested in TEST instance and above are the screenshots.  
But on Portal: CIP is not displaying while creating a Permit for EX & RW TURP but saved with No value. When opened this permit from My permits/cases - CIP displays with 'No' value.
I checked the configuration that promoted to TEST. It all looks good. I think, TEST Portal cache clear/server refresh will do the trick, as I remember similar issue from one of the tickets I worked before. I will communicate this to Swapna/Surya.

**Comment by Nadin-Nader** [comment]
## **Status:**
Subha will reach out to Surya or Swapna to see what the issue could be.

**Comment by SubhaShroff** [comment]
### RW TURP (12657723)
![image](https://user-images.githubusercontent.com/51680715/118009311-932ecb00-b313-11eb-8074-5d1b071293f7.png)

### EX (12657724) -
![image](https://user-images.githubusercontent.com/51680715/118010254-7941b800-b314-11eb-9476-ae5dbd72ade1.png)

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder After Swapna did clear cache on TEST Portal server, I tested for it. It looks good now on portal also and the screenshots are shared above. CIP field displays with NO value selected as default for both EX & RW TURP.

**Comment by Nadin-Nader** [comment]
## **Status:**

Ready for TEST UAT

**Comment by Nadin-Nader** [comment]
Per Paloma, Everything looks good to send to PROD

**Comment by SubhaShroff** [comment]
### Status:
PROD deployment request is submitted on 5/14/2021 -**SCTASK0137747**

**Comment by Nadin-Nader** [comment]
Sent email to Paloma and Kim asking both of the to UAT this on PROD and let me know the outcome.

> Hi Kim/Paloma,
> 
> Hope you are doing well. I wanted to inform you that the New Info: CIP? | Values: Yes, No. Is now on PROD and ready for your testing. Please let me know how the testing goes on PROD and let me know the outcome.
> 
> If all is well, please let me know and we can go ahead and close the request. 
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)

**Comment by Nadin-Nader** [comment]
Per Paloma, There have not been any issues reported. Closing Card
