### ISSUE TITLE
Implement `view` parameter in "Projects" page URL

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5581]
Currently we can provide a link to a list of work with a specific status via a URL parameter, `?status=In%20Progress`. We cannot, though, link to the chart view.
![Screen Shot 2021-03-23 at 1 00 23 PM](https://user-images.githubusercontent.com/1463708/112195397-e6b84e80-8bd7-11eb-9fbe-7ed152d54200.png)

The chart view is awesome so being able to send someone directly to`?status=In%20Progress&view=Chart` would be so nice.

**Comment by amenity** [comment]
@johnclary - leaving this in scoping for now because I'm also curious about replacing the tabs w/ something like buttons for filters... and not sure this would be wasted work if we went there.

**Comment by johnclary** [comment]
great suggestion—thanks. there would not be much work wasted if we changed the filter tabs. i'll move this to backlog.

**Comment by RR216** [comment]
I have two questions regarding this issue:
1. Concerning "replacing the tabs w/ something like buttons for filters", are we still considering implementing this feature?
2. From my understanding of the issue, we want to create a URL that can send a user directly to the chart view. Currently, we have four URL parameters (aka. `?status=needs_scoping` ,`?status=backlog `, `?status=in_progress` , and `?status=completed` ) for the four sections in "Projects" page. Each of these parameters sends a user to the list view of this section and they intuitively read like the default URL for each section. Do we want to create URL parameters for each of these sections in chart view, say, something like `?status=needs_scoping_chart `,`?status=backlog_chart` , ?`status=in_progress_chart` , and `?status=completed_chart`?

**Comment by amenity** [comment]
> 1. Concerning "replacing the tabs w/ something like buttons for filters", are we still considering implementing this feature?

Naw, not seriously. You can ignore that. ;) 

> Do we want to create URL parameters for each of these sections in chart view, say, something like ?status=needs_scoping_chart ,?status=backlog_chart , ?status=in_progress_chart , and ?status=completed_chart?

The pattern I typically see online is using `&` to add parameters to the URL. E.g., in [this Github/Zenhub URL](https://github.com/cityofaustin/atd-data-tech/issues#workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/board?assignees%3Anot=chiaberry&labels=product%3A%20dts%20website&repos=140626918), you can see the board filters tacked on in the URL: `assignees%3Anot=chiaberry` + `&` + `labels=product%3A%20dts%20website` + `&` + `repos=140626918`

One could edit the URL to [show _only_ Chia's issues](https://github.com/cityofaustin/atd-data-tech/issues#workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/board?assignees=chiaberry&labels=product%3A%20dts%20website&repos=140626918) by updating that parameter from `assignees%3Anot=chiaberry` to `assignees=chiaberry`. 

Mozilla Developer Network has some solid docs on this: [What is a URL?](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL).

To answer your question, I'd suggest that instead of `status=needs_scoping_chart` we would do `status=needs_scoping&view=chart`. 
<img width="1328" alt="Screenshot 2023-07-25 at 12 16 57 PM" src="https://github.com/cityofaustin/atd-data-tech/assets/1463708/110bff14-8a2c-4d59-a3f8-1ebab2c14f04">

**Comment by amenity** [comment]
Also... The DTS Website ["Projects" page](https://austinmobility.io/projects) already uses multiple URL parameters: When you select a workgroup using the dropdown, it updates the URL and shows a subset of projects. 

_But_ if you go to that workgroup-specific URL, e.g. [`https://austinmobility.io/projects?status=in_progress&workgroup=Finance`](https://austinmobility.io/projects?status=in_progress&workgroup=Finance), it loads all projects. 

@johnclary, do you know what's up w/ this?

**Comment by johnclary** [comment]
I see—the URL params are currently totally busted. That is a bug! I'm not sure how long they've been broken 🙃
