### ISSUE TITLE
TIA Case Details Custom Drop-down Menu

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5585]
### We need to clean up the buttons on TIA Case Details, and implement a custom drop-down menu for them. 

- [x] Step 1: Analyze current buttons & nail those down/clean up as needed
- [x] Step 2: Wireframe button/menu future state
- [x] Step 3: Map each button to it's feature/page
- [x] Step 4: Review w/ Chrispin
- [x] Step 5: Ask Amenity to bring this up during Dev planning (John suggest tasking to Chia)

----
- [1st Draft of Wireframe](https://github.com/cityofaustin/atd-data-tech/files/6199187/TIA.Buttons.xlsx)

----
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/51baa56d-395a-4d62-8691-3d7fb2eb178f)

**Comment by TracyLinder** [comment]
Next steps, per John:

Wire frame the design
Map each button to it's functionality/page

**Comment by TracyLinder** [comment]
### 1st Draft of Button Organization

Proposing 3 Main Tabs:
- **Case Management**
    - One tab for all buttons that load a new page 
- **Update Case Details**
    - One tab for all buttons that update or add new records to TIA Case Details 
- **Fees**
    - One button for updating both review fees & mitigation fees. (_one form_) 


Top-Level   Menu Name | Nested Buttons
-- | --
Case Management | Case Log
Case Management | Memo Builder
Case Management | Mitigations
Case Management | Scope & Sumbissions
Update Case Details | ➕ Location
Update Case Details | ➕ Communication
Update Case Details | 📝 Case Details
Update Case Details | 📝 Case Reviewers
Update Case Details | 📝 Request Status
Fees | No Nested Buttons



----
**Notes**

- Alternate name for Case Management: Case Pages
- Consider breaking 'Update Case Details' parent tab into 2 parent tabs: Add New Case Details, Update Existing Case Details

**Comment by ChrispinP** [comment]
I think we should maintain the actionable buttons (Add Location, Communication, Attachment) as top level with the other 3 Case Management, Update Case Details, and Fees that you mention. Especially since we have these tables live on the Case Details page.

I think Connected Cases and Request Submission could both go under Case Management

**Comment by TracyLinder** [comment]
Chrispin & I agree to this order:

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/61778e9c-14c4-4f1e-b4e3-d2c6bcd084b8)

**Comment by TracyLinder** [comment]
@ChrispinP pls finish this mapping. 



----

Tab/Button Name | URL | Scene
-- | -- | --
Case Management | N/A | N/A
Scope & Sumbissions |   |  
Mitigations |   |  
Memo Builder |   |  
Case Log |   |  
Update Case Details | N/A | N/A
📝 Case Details |   |  
Assign Case Reviewers |   |  
📝 Request Status |   |  
🔗 Connect Cases |   |  
Fees |   |  
➕ Attachment |   |  
➕ Communication |   |

**Comment by ChrispinP** [comment]
Updated mapping. Ready to handoff to Devs. Creating Test env today for testing this and other TDS needs.

**Comment by TracyLinder** [comment]
@ChrispinP should i schedule a huddle for this w/ us & @chiaberry?

**Comment by chiaberry** [comment]
I'd love a huddle so I can get a good idea of what all the deliverables are

**Comment by TracyLinder** [comment]
Huddle scheduled for 4/5 @ 11am.

**Comment by TracyLinder** [comment]
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/62bec341-3f16-44c4-9d4f-f0374a770467)

**Comment by TracyLinder** [comment]
We huddled. 😊

**Comment by chiaberry** [comment]
Link to work in progress: https://atd.knack.com/test-tds-02-apr-2021-transportation-development-services-portal#tia-requests/tia-request-details/60677899da9d57067ec52e30/

**Comment by ChrispinP** [comment]
Pushed to production. Moving to Review. We are happy with new menu, links work correctly and looks similar to Knack theme. Could be improvements to the styling or mobile optimizations if we want to use for other applications where there is a heavier mobile use.

**Comment by TracyLinder** [comment]
This is done; closing.
