### ISSUE TITLE
TDS Bug: Assigned Reviewer

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5586]
**Reported by Sangeeta by email on 3/23/21 @4pm.**
_Hi Tracy, Something has changed in KNACK.  I just added a project and then selected Vision team groups. And now under “Assign Reviewer”, they are all the same. Earlier, it would list the Vision Team group.  Does it matter to who I assign or it need to be in a particular order?_
![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/bdbc117a-bce2-4734-a4a8-c83b48cf63ee)

**Comment by TracyLinder** [comment]
### Scoping scheduled 3/24 @11:30am

**Comment by ChrispinP** [comment]
We added the Vision Teams column back to the table since the Reviewers Names with their appended Vision Teams are not visible yet. Seeing the Vision Team values allows the PM to correctly assign Reviewers to each Review Comment.

complete
