### ISSUE TITLE
Rollout Robin at Barton Oaks

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5591]
Plan for rollout of Robin at Barton Oaks 4/5

- [x] Provide Help Guides 
- [x] Provide draft of communication that Gilda will send to employees

**Comment by moorerst** [comment]
- sent Help Guides to Shelby for review 
https://docs.google.com/document/d/1wfPxLv6iuzvsKTVvTwFbSa-Pvy9Tsui3JZUfPr7NqdU/edit#

- Shelby drafted the email communication 

- Shelby sent packet of documentation for rollout to be reviewed by the team.

In the communication there was reference to PWD being included in the rollout.
After some back and forth emails JJM responded:
My understanding is that Rob is expecting to see PWD (as well as other depts. in the mobility portfolio) participate in the roll out.  If that is a second stage of the BoP rollout, that is ok.  Can/will we keep Richard and his assistant on the roll-out as planned?

Sounds like there is additional work to do with regard to adding PWD.  Lists, carve out of area, onboarding, etc. 
Let’s add that to the critical path so that I may communicate it properly…and we need to begin/expand that coordination with PWD.

To clarify:  **Move fwd with the roll out at BOP (ATD +2PWD).**  Add a stage 2 to add more PWD to BOP. We should use what we learn from Stage 2 of the BOP roll-out in the Cameron plan.

2 PWD staff have desk with their names 331/Franklin, 332/Mendoza  - 6 available desk are labeled PWD

**Comment by moorerst** [comment]
Email and attachments sent 4/5 announcing rollout of Robin at Barton Oaks:
 Hello ATD Team, 

We are excited to announce the launch of a desk hoteling pilot at Barton Oaks! We have acquired a desk hoteling software called “Robin”, which will be utilized to reserve desk hotel spaces in ATD buildings. Phase one of this pilot will begin with the Barton Oaks Plaza facility and will expand to other ATD buildings over the next few months.

Hoteling allows employees to temporarily work in different locations. Using the Robin software, employees can reserve a desk space at an ATD facility and work there for a day or a short time.

Any Austin Transportation employee is eligible to participate in this pilot as long as they have approval from the supervisor/manager to hotel/telework.  As a reminder, in order to telework, a request form must be submitted to our HR Division.  Please see the attached help guide, hoteling procedures, and FAQ sheet. 

Should you have any additional questions or concerns about this pilot, please contact Jason JonMichael, Shelby Smith, or Gilda Powers.

Attachments included: Hoteling FAQ, Hoteling Procedures, Hoteling User Help Guide

**Comment by dianamartin** [comment]
@moorerst should we close this since roll out happened on 4/5?

**Comment by moorerst** [comment]
The rollout happened on 4/5. To date no issues have been reported from the rollout. Closing issue
