### ISSUE TITLE
Feature: RPP Petition - After Meeting (3/24) Tasks

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5603]
Diana - will create new issue

- [x] Vehicle hiding fields? test it!
- [x] Mobile friendly font size: test it!
- [x] Archiving petition - Test URL after petition is archived: test it!
- [x] Research Schedule Export
- [x] Research - ADA signature
- [x] Recommend consistent naming convention

**Comment by dianamartin** [comment]
- [x] Was able to hide the additional License Plate fields
- [x] Added new field (slider), `How many vehicles do you own?` - Added logic to form

**Comment by dianamartin** [comment]
@moorerst Check this out, when you're back in the office. cc: @amenity I was able to make a shorter url - semi customizable

**Comment by amenity** [comment]
That URL tho 😍

**Comment by dianamartin** [comment]
@moorerst When Joseph gets back to us after he reviews, we can either draft and email to Ryan and him letting them know we did our action items for the RPP Petition. Maybe we need to check in to see if they checked in with Joana on the citizen information.

**Comment by dianamartin** [comment]
Closing this, we can just use tasks as reference to let Parking know what we did on our end.
