### ISSUE TITLE
Data Migration | Extend migration script to include new project fields

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5605]
[Moped to IMPD Schema Mapping](https://docs.google.com/spreadsheets/d/1S8BiXf_H09epwPFI9VxeSgmQ6Jp25U-tWDJUlpzq0PM/edit?usp=sharing)

For new project fields that are either one-to-many or many-to-many, we will have to consider how we are migrating that data that's either nested in columns in the project table in IMPD or potentially in related tables.

**Comment by johnclary** [comment]
We'll definitely have to do this one way or another as we move forward with #4838. I'm going to close this because it's too generic.
