### ISSUE TITLE
Perform Moped data model stewardship handoff

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5609]
Before @zappfyllc leaves: 
- What data in IMPDB will be migrated?
- Is there anything unaccounted for in the Moped data model? 

The data migration work @sergiogcx and @zappfyllc are collaborating on will organically surface some of this. 

@zappfyllc recommends asking Nathan to identify what's missing from the UI. (If it's not available there, what is it used for?)

**Comment by amenity** [comment]
@zappfyllc - please schedule and include all devs

**Comment by sergiogcx** [comment]
This is an orthogonal rendering of the access database, it might be helpful to understand how the moped database was implemented in Postgres:

![access_database_layout_orthogonal.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/9d18f689-62bd-4180-b3db-64de20d2b5f0)

**Comment by sergiogcx** [comment]
As far as the mapping is concerned, this is my progress so far:
https://miro.com/app/board/o9J_lMysndE=/

**Comment by sergiogcx** [comment]
We need to establish:
1. What tables will need to be migrated, which don't need to be migrated.
2. The order of tables (this in respect to foreign keys)
3. The mapping of each table's fields from source (accessdb, moped) to destination (moped).
