### ISSUE TITLE
Data Migration | Integrate with Postgres for Access data migration

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#5612]
Here we will need to create a series of methods that will allow us to join the output of AccessDB and Moped's PostgreSQL. Maybe create a function that can join any output of Access against any output of postgresql.

**Comment by zappfyllc** [comment]
@sergiogcx Main goal is to provide a pathway for you to easily add data to staging/production (staging 1st just for demo purposes, proof of migration, etc.)

**Comment by sergiogcx** [comment]
This is what I have been going by:
https://miro.com/app/board/o9J_lMysndE=/​​​​​​​

**Comment by amenity** [comment]
Connection/integration is working, able to pull Access data into local Postgres db.
