### ISSUE TITLE
User Hector Aguilera and a few other users cannot Print Receipts directly from AMANDA after Paying fees in the LC folder (NN)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#5627]
User Hector Aguilera cannot Print Receipts from AMANDA after Paying fees in the LC folder. He doesnt get any error or a PDF of the receipt to print. He has tried the IE Reset. He can print the FUD Revenue report (a PDF Report) just fine. This started around the time of a network issue.
One example is:
LC 2015-020897
Internal ref no for that is 11299912
or invoice number is 7307496

![Capture.PNG](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/d1f508ec-47a8-445f-8968-d3a55f8b449f)

**Comment by Nadin-Nader** [comment]
I have tested this on my end and i cannot print directly from the receipt in AMANDA. He has done an IE reset and has permissions to print from the LC folder. Scott (our IT) has even looked at his PC and the Reader to see if they were good and up to date, they were.

Chat conversation with Hector:

> [1/8 11:49 AM] Aguilera, Hector
>     im not getting any error i click the print icon and nothing happens
> ​[1/8 11:50 AM] Aguilera, Hector
>     no pdf comes up to print 
> ​[1/8 11:50 AM] Aguilera, Hector
>     nothing
> ​[1/8 12:01 PM] Nader, Nadin
>     ok since there were no steps in the incident, can you send me the steps you are taking to print along with the folder RSN and info so i can try. Are you the only one experiencing this? If not can you try to have one of your colleagues print it? that way i know if it is your PC, profile or AMANDA
> ​[1/8 12:52 PM] Aguilera, Hector
>     i don't have anyone here that prints them only me. So i go to the permit i pay the fee with whatever payment they have. I process that then i hit the print receipt. The other window on amanda opens shows me the receipt i then click the print icon at the top of it and nothing. I can print my Fud revenue report just fine. its only the receipts  

## **Status:**
This issue is with CTM and waiting a response from DEB; **SCTASK0122438**

**Comment by TracyLinder** [comment]
@Nadin-Nader has there been an update on this? Thanks.

**Comment by Nadin-Nader** [comment]
Spoke to Deb via chat and she mentioned that this is still in their queue but have been given AMANDA 7 stuff to work on as a Priority. Once they have a window they will pull it in.

Will follow up in On Friday or Monday 4/9 or 4/12

**Comment by TracyLinder** [comment]
We're assigning LIT to work on this. @Nadin-Nader will you please let Deb know that we've added our resources to this so we don't have people double-working?

**Comment by Nadin-Nader** [comment]
Sent email to DEB:

> Deb,
>  Hope you are doing well. Hey I wanted to let you know that  you don’t have to rush to get to or worry about SCTASK0122438. Since we now have Launch IT back, we have decided to let them troubleshoot it and see what the issue could be. I also wanted to let you know so that we wouldn’t be doing double efforts,
> 
> I would say lets keep the TASK open for now (til mid next week) and if LIT finds out the issue, I will go ahead and close it. If not then I will talk to Tracy to see what she would like to do.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services

**Comment by Nadin-Nader** [comment]
Sent an email to Hector after UATing this on TEST again. Aish may have made some changes n TEST because now i can print them. I sent an email to Hector asking him to UAT on TEST.
If it works, we will apply any changes made to TEST, on PROD 

Email to Hector

> Hi Hector,
> 
> Hope you are doing well. I was reaching out to see if you could go ahead and test the Invoice printing from AMANDA on TEST. It seems like its working on TEST now. If it is working for you then I will ask the developer to do the same on PROD.
> 
> Please let me know as soon as you can. If it does not work, please let me know as well and send me the ROWID of the folder so that I can try on my end.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services

## **Status:**
Waiting on Hector to test

**Comment by Nadin-Nader** [comment]
Hector could not test this as he needed to get a new laptop. He wont be getting his New laptop until Monday. He said he would ask Brandi to try to print on Monday to see if it works.

## **Status:**
Waiting til Monday for results from Hector or Brandi

**Comment by aishwarya2505** [comment]
This issue works on TEST for Nadin and I. ROW ID: 12652150. It is not working for Hector though. I will be sending a list of things he could do to make sure the issue to verify if this is a configuration set up issue.

**Comment by aishwarya2505** [comment]
4/28 - Sent a document on few configuration alternatives to see if Hector can follow the steps and have the print functionality enabled.

**Comment by Nadin-Nader** [comment]
Hector was still not able to print with the troubleshooting steps applied. I asked that he try to print from Brandi's PC and vice versa (using each others log in).
Once he does this, the system should indicate if its his PC or Profile. He does not want to give Brandi his login info but she is supposed to be in the office today 5/12/21.

## **Status:**
Waiting on Hector to test with Brandi in Person

**Comment by Nadin-Nader** [comment]
Spoke to Hector on 5/12/21 and he said that he was still not able to print and would try to have Brandi print from his work station using her login info and vice versa.

I also spoke to Hector via chat today and he said to close the ticket. His words below:

> [8:40 AM] Aguilera, Hector
>     no we did not get to test it before left. you can close the ticket i have to save the pdf of the receipt then go in to the folder and print from there. Thats good enough

Closing this and SCTASK0122438
