### ISSUE TITLE
Feature: View TIA case loads & bulk reassign

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5633]
### As a lead TIA Reviewer, I need to be able to view case load by reviewer, and by area. I need to be able to reassign cases either individually, or with a bulk action.

**Comment by ChrispinP** [comment]
New Tabbed Menu: 
![image](https://user-images.githubusercontent.com/67915167/116291245-f9cfb880-a759-11eb-88dd-fdce113e737b.png)

Case Load by Area:
![image](https://user-images.githubusercontent.com/67915167/116291002-b83f0d80-a759-11eb-8cb7-b26a162d1250.png)

See Assigned Cases by Area:
![image](https://user-images.githubusercontent.com/67915167/116291191-ed4b6000-a759-11eb-9416-6c134f223d36.png)

Case Load by Reviewer:
![image](https://user-images.githubusercontent.com/67915167/116291330-10760f80-a75a-11eb-8351-4eedcbe456bd.png)

Reviewers Assigned Cases:
![image](https://user-images.githubusercontent.com/67915167/116291399-27b4fd00-a75a-11eb-8ee1-a6412c90d96c.png)

& access to Customer's Case Details.

**Comment by ChrispinP** [comment]
Ive allowed inline editing for assigned reviewers but the function seems to be bugged atm. You can still navigate to the Case Details with the quick link and re-assign from the Case Details page.

**Comment by ChrispinP** [comment]
Ready to review

**Comment by ChrispinP** [comment]
Moving to blocked until Knack is able to resolve the expanded group records issue that would allow us to reassign case reviewers from the table. Otherwise, this has been reviewed and is complete.

**Comment by ChrispinP** [comment]
Expanded group tables are now fixed. I also needed to move the Lead and Case Reviewer conditionals to the application form instead so that these connection fields could be editable from the table.

complete, ready to review

**Comment by TracyLinder** [comment]
**Review Q/A w/ Stakeholders:**
- There's not a feature to bulk reassign, but we're open to building this feature in the future if the need to do so arises. 
- Update the case/reviewer area filter to filter out 'Request Approved' cases
    - @ChrispinP can you try to filter these out please?

**Comment by ChrispinP** [comment]
Approved cases are now filtered out
![image](https://user-images.githubusercontent.com/67915167/120719631-38127300-c490-11eb-8108-7e40a42497c6.png)

**Comment by TracyLinder** [comment]
Looks good. closing
