### ISSUE TITLE
New Field (On Submissions Table): Cycle #

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5636]
### Users need to count cycle numbers, and be able to report on it. 

**Acceptance Criteria**
- New Field on TCP Details; Submissions Table: **Cycle #**
- The system generates & inserts the cycle number each time a new submission is created.
    - ROW/Submission  1 = Cycle 1
    - ROW/Submission 2 = Cycle 2

**Comment by ChrispinP** [comment]
Cycle Fields pre-built during migration in Prod
![image](https://user-images.githubusercontent.com/67915167/128093802-b04edb93-140b-4b0c-b97e-6805b238c981.png)

![image](https://user-images.githubusercontent.com/67915167/128093777-618431b0-bbc3-43e1-a17e-da4ff0bb9a7b.png)

Built in Test, Cycle field added to Submissions Table
![image](https://user-images.githubusercontent.com/67915167/128093947-1003c202-6a38-471f-b353-2aae8fc2678d.png)

**Comment by dianamartin** [comment]
@ChrispinP so was this an update to the `Cycle` equation/formula too?

**Comment by ChrispinP** [comment]
@dianamartin Cycle didnt exist before, I prebuilt it during the migration so migrated records would have a submission cycle. This works the same as TIA and uses this [Review Cycle Article](https://app.gitbook.com/@atd-dts/s/atd-knack-operations/tds-portal/app-logic/review-cycle-automation)

**Comment by dianamartin** [comment]
@ChrispinP oh okay, this is fine to push to PROD then

**Comment by ChrispinP** [comment]
No issues, closing
