### ISSUE TITLE
Enhancement: Display the Submission Count field on TCP Details

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5637]
### User want to see the # of submission in the TCP Details.

**Acceptance Criteria:**
- Add the **Submission Count** field to the TCP Details page.

**Comment by ChrispinP** [comment]
Added to Prod

TCP Details page
![image](https://user-images.githubusercontent.com/67915167/128092588-a1e16b07-bfc5-4ad1-8166-02a1a04fb732.png)

**Comment by ChrispinP** [comment]
No issues, closing
