### ISSUE TITLE
Enhancement: Allow TDS Reviewers to save draft comments

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5649]
### As a TDS Reviewer, I'd like to be able to save a draft of my comments before I finalize them. 
_Currently the # 1 priority for TDS_

**Stakeholder:** Sangeeta

**Criteria:**
- New Field Value on 'Comment Status': In Draft
- Allow reviewer users to save/edit draft comments when the Comment Status value = 'In Draft'
- Do not allow reviewers to edit comments if the Comment Status value = 'Review Complete'

**Comment by TracyLinder** [comment]
@ChrispinP I don't assign myself to apps tickets. I just use filters to find them. Please stop.

**Comment by TracyLinder** [comment]
We want to discuss this with Sangeeta before doing the work. Will speak to her about #4624 as well.

**Comment by TracyLinder** [comment]
Per our stakeholder review on #6175, this is the top priority for the TDS mod.

**Comment by ChrispinP** [comment]
Updated Comment Status, defaults to In Draft
![image](https://user-images.githubusercontent.com/67915167/124176336-6629a980-da74-11eb-9264-473bc35fcb65.png)

Updated Records and Display Rules
![image](https://user-images.githubusercontent.com/67915167/124176445-822d4b00-da74-11eb-9973-e6918fd396d1.png)

New comments will show as In Draft
![image](https://user-images.githubusercontent.com/67915167/124175921-d257dd80-da73-11eb-8242-ea4d6f8a43c3.png)

Comments that are In Draft or Pending Review will show up in the Needs Review section and can be edited
![image](https://user-images.githubusercontent.com/67915167/124174997-a38d3780-da72-11eb-8871-98e207f4ff2b.png)

Comment Status added to form and rules updated
![image](https://user-images.githubusercontent.com/67915167/124176078-0af7b700-da74-11eb-9c4d-b572eba48a57.png)

Form will hide and not be editable if Comment Status is set to Review Completed
![image](https://user-images.githubusercontent.com/67915167/124176177-2ebafd00-da74-11eb-97e3-20be74078607.png)

**Comment by ChrispinP** [comment]
Moving to Review/QA

**Comment by ChrispinP** [comment]
Sangeeta messaged and said they will do a final review on this feature to make sure it meets their need.

**Comment by ChrispinP** [comment]
Sangeeta is happy with the enhancement, working as expected.

closing
