### ISSUE TITLE
Data dump of 1k CRIS crash records from other agencies

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#565]
@johnclary would like to be able to follow up on missing lat/long in APD data — (Austin is the only one in TX missing lat/long).

**Comment by mateoclarke** [comment]
Sergio ran an analysis to see if other public safety agencies do any better at geocoding. This is complete.

**Comment by johnclary** [comment]
Spreadsheet is [here](https://docs.google.com/spreadsheets/d/1uXAVq2pGkEcZianeNOyUwibCWsy_FsellgQkvESzs-g/edit#gid=925989988).
