### ISSUE TITLE
Enhancements: Digital Petition 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5652]
Enhancements discussed in the Digital Petition Kickoff meeting:

- [x] Vehicle hiding fields?
- [x] research - ADA signature
- [x] Mobile friendly font size: testing -
- [x] Research Schedule Export
- [x] Test URL after petition is archived
- [x] consistent naming convention

**Comment by dianamartin** [comment]
This was completed March 31st, we were waiting on the stakeholder to review the RPP form and set up a brief with them. The details of what was done is in issue #5603

**Comment by dianamartin** [comment]
This was completed March 31st, we were waiting on the stakeholder to review the RPP form and set up a brief with them. The details of what was done is in issue #5603
