### ISSUE TITLE
Project Meeting 3/30/21

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5654]
**Agenda:**

- [x] Review Nate's memo review
- [x] Review QA column
- [x] In Progress column
- [x] Discuss custom drop-down menu #5585 
- [x] TIA Case Details Attachments #5453

**Comment by TracyLinder** [comment]
### Notes

- Concerned about only using street segments for mitigation data; especially with the way that ends up looking on the final memo. Let's talk to John about what it would look like to use segments & intersections. Is that possible?

- Chrispin will ask KNACK about this:
![image](https://user-images.githubusercontent.com/49930868/113037279-d6b1e900-915a-11eb-9532-eecd08db382e.png)


- Change the signature field type. User wants to upload their own signature. (jpeg)
![image](https://user-images.githubusercontent.com/49930868/113037506-124cb300-915b-11eb-84d1-bcbfb96b06a4.png)

**Comment by TracyLinder** [comment]
### Apps Tasks

**Comment by TracyLinder** [comment]
### PM Tasks

- [ ] Ask John to commit to next week's meeting so we can discuss using intersections/nodes on mitigation locations
- [ ] Make backlog issue to include TDS reviews on the Reviewer Dashboard
- [ ] New issue on mitigation map epic: (Not MVP) The users would like the ability, on the advanced mitigation search page, to search for sites within a certain radius of any given location. 
- [ ] (Create issue) View new mitigation data on existing mitigation tables
- [ ]

**Comment by ChrispinP** [comment]
Changed Memo signature to an image and updated the Search TIA Cases page queries. Added some page breaks to the Memo to review.

**Comment by ChrispinP** [comment]
all action items completed and reviewed, closing
