### ISSUE TITLE
Develop Sample of Proposed Reformatted CTN

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#5662]
Per conversation with Alan, I will be looking into and creating a sample version of a reformatted CTN dataset. The goal will be to enhance data accuracy, reduce/eliminate segment splits to CTN, and efficiently make data available to stakeholders/public.

**Comment by johnclary** [comment]
Linear referencing option is viable! todo: agree on which reference dataset we'll use (CTN vs OSM).
