### ISSUE TITLE
Enhancement: Updates to UC Process Attempts on 61060 Adjust Review Due Dates (SS) (On PROD, Waiting for UAT Response)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5663]
### As a UC manager, I need to know the number of resubmittals for each UC folder, and the number of corrections.

**Stakeholders:** Ryan, Darren, Isiah, Jaclyn

**Acceptance Criteria:**
On process 61060 Adjust Review Due Dates:
- Remove 'Complete' as a valid attempt result
- Add 2 new attempt results:
    - Resubmittal
    - GP/SP Corrections 
- These 2 new attempts will have the same exact functionality as the current 'Complete' attempt. 

**Notes:** 
- Before developing this, we need to know if anyone else is using this process on a folder other than UC.
- This change will break the report we build for #5578. We'll need to update the average # of resubmittals formula to only count Resubmittal attempts.

**Comment by TracyLinder** [comment]
**Prioritization Notes w/ Darren:** This is still a need for performance reporting.

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0283823 is submitted for DEV deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  61060 Adjust Review Due Dates process is configured to LM folder also. If we remove 'Complete' attempt it will be gone for LM also. 
Instead of removing Complete attempt for UC, we can display error message with this attempt, something like  - 'Complete is not a valid attempt for UC'. Thanks.

**Comment by Nadin-Nader** [comment]
Waiting on Greg P to approve. He said he will be able to look at this tomorrow

**Comment by SubhaShroff** [comment]
@Nadin-Nader  [9e15fbcf4d9a](http://coaamandadevops02.austintexas.gov/R5:9e15fbcf4d9aa21d977ea191c819b33ba6ed2bf2)  - this is the commit I did for the changes after Greg's response. Please audit it.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Thanks for auditing. I have raised DEV promotion request for this commit - SCTASK0286494.

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder  This is deployed in DEV and demo recorded is attached here. Please review and let me know your feedback. Thanks.
https://user-images.githubusercontent.com/51680715/219433035-75a4e514-7f85-46d9-a869-dcbd0252e96b.mp4

**Comment by Nadin-Nader** [comment]
@SubhaShroff Jaclyn says this is good to go to TEST

> [11:29 AM] Lozano, Jaclyn
> I got it now thanks lol. It's good to go to TEST.

**Comment by SubhaShroff** [comment]
Thank you @Nadin-Nader. I submitted SCTASK0300345 for TEST deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  TEST deployment is done. I have tested it and its ready for UAT. Thanks.

**Comment by Nadin-Nader** [comment]
Awaiting UAT from Jaclyn Greg or UC team

**Comment by Nadin-Nader** [comment]
Got a response from Jaclyn:

[1:49 PM] Lozano, Jaclyn




5663 - Adjust Review Due Dates looks good in test

@SubhaShroff Approved for PROD

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0309874 is submitted for PROD deployment.

**Comment by Nadin-Nader** [comment]
This has been deployed to PROD

**Comment by Nadin-Nader** [comment]
Have not heard back from Jaclyn and no issues on this being on PROD have been reported. Closing
