### ISSUE TITLE
MOPED Intersection Points re-publish

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#5670]
The current intersection points vector tiles I generated for MOPED have a couple of duplicate IDs. This seems to be some type of bug, as the `PROJECT_EXTENT_ID` field was generated by adding 600,000 to the `OBJECT_ID` field, which doesn't have duplicates.
I'll re-create the dataset, and examine which parts of this process need to be documented for future updates.

**Comment by alan-deanda** [comment]
@mddilley  I've re-calculted the `PROJECT_EXTENT_ID` and ran a 'delete duplicates' tool for some peace of mind. As far as I can tell through GIS, there should be no more duplicates. I've saved the layer [here](https://austin.maps.arcgis.com/home/item.html?id=9ba4f2cdab98467881460f59ad5a5f71). Please let me know if it gives you any more issues.

**Comment by mddilley** [comment]
Thanks, @alan-deanda! I've updated the Moped code with the new url, and the bug is now gone. 🙏

**Comment by alan-deanda** [comment]
The issue is resolved, and I've deleted previous versions of the intersection points from AGOL.
