### ISSUE TITLE
Data Table | Add configuration option to clear dependent data for switch fields

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5679]

**Comment by mateoclarke** [comment]
@amenity, this issue is confusing to me. Can you provide more context or a use case? specifically the part about "configuration option".

**Comment by tillyw** [comment]
Sorry, it's hard to articulate this one! The use case would be when a user switched off "Capitally Funded," the DataTable component mutation would include a set statement that clears out "eCapris ID." I'm doing this by setting a new field in ProjectSummaryTable called "childField" under "Capitally Funded." Before running a mutation, DataTable will check to see if the field being modified has the "childField" property, if it does it clears out that childField.

**Comment by amenity** [comment]
Thanks, @tillyw, that captures it well. I should have also added @johnclary's point [here](https://github.com/cityofaustin/atd-data-tech/issues/5518#issuecomment-809475168) for more context, @mateoclarke. 

I don't quite remember why we decided it should be a configuration rather than default behavior for any data "dependent" on a switch.🤔  Does that make it a lot more complicated?

**Comment by tillyw** [comment]
> Thanks, @tillyw, that captures it well. I should have also added @johnclary's point [here](https://github.com/cityofaustin/atd-data-tech/issues/5518#issuecomment-809475168) for more context, @mateoclarke.
> 
> I don't quite remember why we decided it should be a configuration rather than default behavior for any data "dependent" on a switch.🤔 Does that make it a lot more complicated?

Nope! The configuration is just a single property that tells DataTable whether a field has a dependent field and the name of that field. If it does, DataTable will automatically clear the dependent field if you deselect the main field.
