### ISSUE TITLE
Delete "csr_flex_notes" from Signs & Markings - May 2021

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5698]
Received automated reminder to delete flex notes in Signs and Markings Operations PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings#data/object_172/records

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 03/01/21

Total Records: `12,277`
To Delete: `3,090`
New Total: `9,187`

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/97b4e8fc-0796-40b6-aa94-1c046d433313)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/0a2e9d95-506f-4251-9ab5-9ea018c24da4)
