### ISSUE TITLE
[DTS] Update Application Details page Environments table with Notes and Modified by fields

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5701]
Improve information at a glance by providing Notes field and Modified by fields to be viewable on the Environments table

**Comment by dianamartin** [comment]
- Added "Modified By" to Environments table
- Removed "Application" on Environments table
- Moved "Application" higher on Edit Environments form

**Comment by dianamartin** [comment]
Updated Change Log too
