### ISSUE TITLE
Micromobility Complaints Feature Layer

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#5707]
- Francesco asked me how would be the best way to move forward to update the Micromobility Complaints feature layer in AGOL.

**Comment by jaime-mckeown** [comment]
- He asked about continually to export a shapefile from AGOL.
- Told him how we normally update data to AGOL.
- The layer is not shared publicly, so I let him know if it was not going to be shared publicly that he could take over ownership and publish updates himself since he is a Power User.
- It's not going to be public yet, so I moved the feature layer to his account.
- I let him know that when they were ready to publish it publicly that the ATD Publisher account would have to take over the ownership.

**Comment by johnclary** [comment]
Good to know. thanks!
