### ISSUE TITLE
Meeting : Builder Huddle for Shared Mobility Operations

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#5721]

**Comment by SurbhiBakshi** [comment]
Meeting on 04/06/2021

**Resources -** 
[Backlog Review ](https://docs.google.com/presentation/d/1QEoZ_obyGOl_hMxW8-MBh-HrVd_kEdTdVP1PDJy_BLE/edit?usp=sharing)
[Miro Workflow Board](https://miro.com/app/board/o9J_lU6H3zc=/)

**Notes -** 
1. Look into 311 integration for SR's. (#5720)
2. Demo permits functionality to SMO team so they can start using it. 
3. Check if Impound records will come from CSRs or 311


**Wait for new product manager to address** 
1. Clarification on geographical zones
2. Permit - License - Insurance workflow

**Comment by dianamartin** [comment]
@SurbhiBakshi should we close this?
