### ISSUE TITLE
Perform 4/13 VZA App officer training

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5726]
- [x] Update [registration form](https://docs.google.com/forms/d/1o0Jpe21BboUJgPLZ4Bo7yC8kdynBDZ1whrNAhYgWWDg/edit?usp=drive_web) with new date
- [x] Perform training and have officers fill out registration form
- [x] Create officer accounts
- [x] Add officers to VZA Officer Contact List in Outlook 
- [x] [Email officers](https://docs.google.com/document/d/1OBxv49_LD_T2YT9AkyRugjmiScBCnQfI8k3WzRan2Qw/edit)

**Comment by amenity** [comment]
Sticking another story point on this because I need to review + test assignments with Lewis' new approach before the demo.

**Comment by SurbhiBakshi** [comment]
@amenity - I created the accounts for the officers who attended the training on 4/13.
