### ISSUE TITLE
Evaluate barcode reading in Knack

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#573]
_As a warehouse staff person, I need the ability to create a barcode and assign it to an inventory item._

Look into creating your own barcode via Knack 
- Reading barcode into field
- Bluetooth/hardwired reader

Also consider using QR codes.

**Comment by dianamartin** [comment]
Found this in Knack help guides: https://support.knack.com/hc/en-us/articles/230232228-Generate-Simple-Numeric-Barcodes-Automatically

Might need assistance from dev team

**Comment by dianamartin** [comment]
- [ ] Test in Finance & Purchasing test application

**Comment by amenity** [comment]
Knack responds the way we expect when input into Knack; opening an issue for testing the hardware.
