### ISSUE TITLE
Print Bike Map Spring 2021

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#5731]
The last updates to route comfort levels are currently being implemented. Full-size print reviews have shown that the new workflow has been successful. Creating the entire map in ArcPro renders it in high resolution, and creating the art in Adobe makes room for creative freedom. 

This update is being prompted and prioritized by two factors: current stock of the 2020 print bike map is running low, and May is Bike Month. This edition will use a new workflow to ensure the data is fresh, prevent the scope of the map from growing too large, and increase the speed of production.

# Map Updates in this edition:

* Bike Facilities completed by end of Q2 (march 2021)
* PHBs
* Updated MetroBike kiosk locations

# New Workflow 
The map will be wholly created in ArcPro, then migrated to Illustrator to merge with the graphics from 2020 edition and final adjustments. ArcPro can now match the aesthetic of previous bike maps drawn in Illustrator, which will help keep all data fresh, and free from accidental distortions. The bike map will be exported to Illustrator using the original map's data extents. 

## Base map
* Base map will be  drawn after testing it in the following two ways:
    * Using the AGOL base map for the online bike map
    * Creating the base map using CTM feature services for each base map layer
    * Street labels will likely have to come from TRANSPORTATION.street_segments no matter which option is chosen
    
### Route Geometry
* The routes will come from the CTN's `LEVEL_OF_COMFORT_FIELD`
* All new facilities and corresponding levels of comfort will be mapped by Andrew, with feedback from myself and ATSD   
    * To ensure the map is delivered on time, ATSD has agreed to limit the scope of the map to projects completed by the end of Q2 (march 2021). In the past, waiting for new projects to be completed has pushed the delivery of the bike map by several months.
* The CTN's `ELEVATION` field will be filled in to draw the map's over- and under-passes
    * ArcPro's Advanced Symbol Layer Drawing will be used to "merge" lines on the same elevation
* Labels for routes will come from the existing Illustrator document

## Over-map Data
* PHBs will be added to the bike map for the first time in this edition. The data will come from the PHB feature service in AGOL.
* MetroBike Kiosks will be drawn from the feature service in AGOL
* Pools, bike shops, schools, etc., will come from the existing Illustrator document
* If steepness chevrons aren't feasible to generate in GIS for this edition, we'll use the existing ones

**Comment by johnclary** [comment]
it's done!!!!!

**Comment by johnclary** [comment]
@alan-deanda please close
