### ISSUE TITLE
Moped Database | Add CorridorPlan to categories

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#5736]
From a [conversation with JD](https://austininnovation.slack.com/archives/CNUEPKLB1/p1617817788119800) it appears we need to add `CorridorPlan` to the list of categories for a project, this in order to assist the quality of the data migration.

This is the current state of `moped_categories`

![2021-04-07_13-27-09.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/487df753-002d-429e-9a97-ff74c602c853)

**Comment by amenity** [comment]
This will be covered during https://github.com/cityofaustin/atd-data-tech/issues/5465#issuecomment-815135267
