### ISSUE TITLE
Map Bike Facilities up to Q2

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#5739]
This issue will track the updates to the bike map by street/trail name. I'll add projects from ATSD here.

**Comment by johnclary** [comment]
@alan-deanda anything else needed here?

**Comment by alan-deanda** [comment]
@johnclary Andrew has mapped the facilities from Q2, I'll close this issue. If there are any subsequent requests about the level of comfort of these facilities I can add them to an issue of post-review edits
