### ISSUE TITLE
Show drawn points in project summary map and refine UI

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#5749]
This will involve adding a config to the `mapConfig` object for the drawn points layer so they can be displayed alongside point and street features in the summary view.

Also, some other details:
- [x] Include drawn locations in the "number of locations" total at the bottom of the map
- [x] Update the cursor in drawing mode (right now is the grab for everything)
- [x] Explore data driven styling for the radius of the drawn points while in draw mode (they look massive when zoomed out while in draw mode)
~- [ ] Determine what actually enables/disables the draw mode (instead of the placeholder switch)~ Decided to stick with the toggle for now

**Comment by johnclary** [comment]
as discussed you can style drawn points the same as selected points.
