### ISSUE TITLE
Question about Road Closures and Google Maps - Adrien at CPO

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#5751]
From Adrien:

> Does ATD publish road closures to Google Maps? This recently came up in a discussion regarding CPO’s road closure data. 
> https://support.google.com/mapcontentpartners/answer/10187434?hl=en&ref_topic=22146

**Comment by jaime-mckeown** [comment]
Response from Lance in MMC to send to Adrien:

> We can put full road closures in Waze which will then populate in Google maps.
> 
> We have an email we can submit to Google Maps, but not a direct way to input them into the map.
> 
> Usually, this has been related to special events and someone at ACE usually beats us to the punch. However, we’ve been inputting Waze closures ourselves a bit more lately.
> 
> I think the Geo Data Partnership at the link may be for more long-term things, but we’re happy to help explore it if folks desire to do that.

**Comment by jaime-mckeown** [comment]
Also let Adrien know that ATD has a Google Partner Account and that we have sent updates for healthy streets and bike infrastructure in the past.

**Comment by johnclary** [comment]
Worth noting here that [Jim has engaged us](https://github.com/cityofaustin/atd-data-tech/issues/5154) and CPO to discuss automating road closure to navigation providers, but it seems to have stalled out. We were supposed to meet with CPO the week of the snowpocalypse, and it never got rescheduled.

**Comment by jaime-mckeown** [comment]
Response from Adrien:

> This is super helpful, I meant to inquire about Waze, too. 
> 
> I may set up a meeting to discuss coordination and to understand more about the process. Our Comms team requested this initially and I don’t want to duplicate efforts.
