### ISSUE TITLE
[BUG] Running List of quick fixes for Parking Dispatch - Dispatch testing feedback

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5753]
## LIST OF THINGS I'VE FIXED
- Un-grouped Created Date on SR Table
- Sorted Created Date on SR Table
- Added Created By & Modified By to SR Table
- Added display rule bc "SR number" kept showing up on "Edit SR" form
- Added display rule for "Issue Code" Duplicate from activity to update parent status to "Closed Issue (Duplicate)"
- Removed modal setting for "New SR" form - dispatcher kept clicking out and having to start over
- Added "Provider/Company Name" when an Issue Type is "Scooter/Electric" (multi-select)
- Added "Complaint Type" - drop down selection (one choice)
- Added "Towed Vehicle" to `Issue Type` drop down selection
- Will delete "Mid" filter for Resource Tracking

## PROCESS THINGS EXPLAINED
- How to see timestamps for Breaks, Lunches, etc.. - didn't know where to find it, showed Shavyvonne
- How to change PEO officer assignment (Instruct dispatcher to add new activity for "Dispatch Investigator" will override the Assigned To 
- How to edit an SR - dispatchers would panic and want to delete the SR they created, first instinct was to create a brand new SR

**Comment by dianamartin** [comment]
@moorerst 

I messaged Jasmine since Shavyvonne said that she was having some issues with the app when dispatching. She's on a laptop so I wonder if the issues are more noticeable bc she doesn't have the same dual monitor set-up like being in the office.

I've talked to her about some of the issues she's had.

**Comment by moorerst** [comment]
@dianamartin when reviewing entries I noticed when she was using the Dispatch Investigator activity she was not populating the Assign To field with a specific Officer - Discussed with Shavyvonne yesterday

**Comment by dianamartin** [comment]
@moorerst Yeah, I think I mentioned it to Hilary the other day too. She's doing that now. I checked the Issues they've created are 88, 19 didn't have the Assigned To filled out.

**Comment by dianamartin** [comment]
@moorerst if you think we're done with tracking during the pilot

**Comment by moorerst** [comment]
Dispatcher user testing is complete, they continue to enter SR's into the system on their own. They are also entering SR's and assigning to the PEO's who are testing. 
The response to the new system from the Dispatchers is very positive.
