### ISSUE TITLE
User Testing: Dispatch Tracking PEO testing 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5755]
Staff has provided a list of Officers for testing

Testing will include:

- Accessing My Assignments
- Attaching images from device while on site
- Managing My Time - lunch, break, check in/out

**Comment by dianamartin** [comment]
Talked with Shavyvonne this morning, we thought that doing the training for PEOs should be done before their shifts. 

### To DO
- Create Teams meetings
- Inviting their supervisors and Shavyvonne
- Provide URL to Shavyvonne
####  Monday
  - 8 am
  - 10 am
#### Wednesday
  - 10:30 am

### Demo
- Manage My Time
  - How to log breaks, lunch, clock out
  - Need help, ask dispatcher
- Dispatcher - adds activity to dispatch and assign
- PEO - opens assignment
- Takes picture and then then submits for review
- Dispatcher - reviews, adds actions, closes assignment

**Comment by moorerst** [comment]
First training session @ 8:00 included 2 PEO's and 2 Leads
Questions from training session:

- will we get a notification when a SR has been assigned to us like in Teams we get a beep?

Knack does not have the option to beep when an assignment is made. We can set up a email notification. Per Shavyvonne not all Officers have city email on their device. We will need to discuss how to handle the notifications.

- for Manage My Time only options are Break/Lunch/Check Out how do we handle other Out Of Service reasons?
Other reason to be Out of Service i.e. meetings, car wash, etc. will need to be reported to the Dispatcher

- The check box for Submit is not clear it makes me think that I am unchecking Submit?

we will need to look at other options for the submit button

**Comment by moorerst** [comment]
Second training session @ 10:15 included 2 PEO's and 1 Lead
had some issues with assigning the SR's to the PEO. The Assign To field was not populating, had to manually populate for testing
PEO Bookman was having issues with his device, he was getting kicked out of the browser and the screen froze so he was not able to complete attaching an image.

We will assign some test SR's to both of the PEO's to test later today

**Comment by moorerst** [comment]
@dianamartin not sure if this scenario happens often but as a Officer I submitted SR  PSR00-002790 after attaching a photo.
As the Dispatcher I reviewed it in Final Review 
I added a new Activity for Dispatch Investigator and added a Note that the photo is not clear and needs to be retaken
I assigned the SR back to myself I see the SR in My Assignments with the status In Progress but I don't see the Notes telling me to retake the photo
Should the Notes field be visible to the Officer?

**Comment by dianamartin** [comment]
@moorerst It depends, I'm not following which "Notes" they need to see. Might need to talk to the dispatcher about what they did.

**Comment by moorerst** [comment]
Feedback from Dispatch Lead: 
Currently we have 27 tester out of 34 onboard and active testers. Currently about 7 PEO’s ranging from Officer, Lead , or Supervisor that haven’t been trained on how to operate the new Parking Enterprise Portal due to being scheduled off or scheduled to provide assistance at the Vaccination cites.

So far so good……We haven’t experienced any issues so far on the application side of things. The issues we have addressed, have been more with the Brazos device camera taking forever to upload or wouldn’t load at all. We sent those devices to the Radio shop to be fixed. 

I will keep you updated if I receive any feedback from the Officers or Dispatchers these next few days.

PEO testing will end 4/29

**Comment by dianamartin** [comment]
We received all the feedback we needed from the dispatcher and PEOs on 4/29
