### ISSUE TITLE
Enable COACD single sign on button on Parking Enterprise Reporting Portal

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5758]

**Comment by dianamartin** [comment]
There was a weird bug happening that I escalated to Knack. Some knack applications didn't have the ability to set up the Single Sign On. Chrispin and I did a fairly thorough test on it, converting apps and switching them temporarily to see if they had the functionality. Only 3 apps didn't have them: AMD, SMB and Banners (some of our earliest apps).

**Comment by dianamartin** [comment]
I turned in a ticket into Knack about the new builder and SSO functionality on 4/8

**Comment by dianamartin** [comment]
Created CTM ticket `INC0094656` to create AFDS sign-in,

**Comment by dianamartin** [comment]
- John D. (CTM) emailed me the metadata I needed for the SSO configuration
- Attempted to configure it, tested and there was an issue
- Reached out to Surbhi, we discovered an incorrect field
- Tested and it was successful
- Added COACD big button code

**Comment by moorerst** [comment]
@dianamartin I was able to login using the big Sign In button

**Comment by dianamartin** [comment]
@moorerst I meant to send out an email to everyone about how to log in. 
-  Block'o said he wasn't able to see what the dispatchers were seeing and that's bc he was in the wrong user role, so I updated him and got him logged in. 
- Email from you or from me about log-ins?

**Comment by dianamartin** [comment]
@moorerst I'll send the email out about logging-in

**Comment by dianamartin** [comment]
Emailed stakeholders on 4/14, to let them know of the changes
>Yesterday afternoon, I was able to add the single sign on button function to the application. What that means is you won’t need the username and password you’ve been using to log into the application. You can click the “Sign-in” button the [home page](https://atd.knack.com/parking-enterprise#home/) and it may/will take you to a City of Austin log-in page where you can use your normal network credentials to log in. This was important for us to add so the parking enforcement officers won’t have to learn a new username and password to access their “My Assignments” page when they get into the system. 

>Another thing, we update the logo header of the application. It used to be “Parking Enterprise Reporting Portal”, but because we’re doing more than just reporting now we thought it was a good idea to update it.
