### ISSUE TITLE
Comply with TXDOT CRIS data retention policy (10 years)

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#5764]
Upon reviewing and signing the attached "Texas Motor Vehicle Traffic Crash Data Confidentiality Agreement" to update our extract delivery method with SFTP access, I noticed they state an explicit 10 year data retention policy. We've talked about 5 years of data being sufficient for most of our analysis. Now would be a good time to enact a process to purge old data and comply with TXDOT's retention policies.

> The department’s retention period for crash data is 10 years. The department requires that crash
> data provided pursuant to this Confidentiality Agreement be purged responsibly in accordance with
> this retention policy. I understand that any crash data obtained from the CRIS system that is
> retained longer than the department’s retention policy will become my liability and responsibility. The
> department will not provide, release, or support crash data retained outside of its published
> retention policy by external entities or individuals. I understand that if the department discovers that
> I or my organization has historical data, no longer retained at the Department, that this may
> jeopardize my access to the Crash Record Information System. 

[CRIS Automated Interface Confidentiality Agreement.pdf](https://github.com/cityofaustin/atd-data-tech/files/6287277/CRIS.Automated.Interface.Confidentiality.Agreement.pdf)

**Comment by mateoclarke** [comment]
Two updates from the May monthly DTS/VZ checkin:

- Brazos data retention isn’t strict to 10 years and can serve as an alternative if we need old data, though not official and not complete data
- The next step should be work to establish summary statistics on older data before archiving older raw data

**Comment by patrickm02L** [comment]
Next step: Frank, Joel, and Xavier to come up with set of summary statistics by year

**Comment by patrickm02L** [comment]
@patrickm02L Bring this up in September Sprint Review.

**Comment by amenity** [comment]
@johnclary - understands this to mean that TXDOT will no longer support this data but it doesn't compel us to purge it on our end.

**Comment by johnclary** [comment]
ok—I just re-read that last sentence. I assigned this to myself and will check with our legal about it.

**Comment by patrickm02L** [comment]
In the September Sprint Review Meeting:

Lewis suggestion: Pull down the data from the open data portal that is older than 5 years old. 
Mateo added: that we could hide the data on VZE by changing the date range.

**Comment by patrickm02L** [comment]
Initial steps to data compliance retention policy.

Go through and audit every query in the VZE and every query that drives the datasets in the VZV, and add a WHERE clause condition that makes it impossible for crashes of a certain age to not show up.

**Comment by frankhereford** [comment]
@frankhereford The exporting routine that builds the datasets that replace the Socrata VZV datasets should use the interval of 10 years from now(), not the 5-6 years we had discussed previously.
