### ISSUE TITLE
Publish AMD Inventory Transactions to Open Data Portal

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5769]
Publish AMD inventory transactions to Socrata so that the data can be used in PowerBI. See also [#5770](https://github.com/cityofaustin/atd-data-tech/issues/5770)

Neither AMD nor Finance has not asked for this, but I'd like to take the initiative to show them what's possible.

**Comment by ChristinaTremel** [comment]
- Inventory transactions was published to Socrata - Reference issue #13587
