### ISSUE TITLE
Dispatch Tracking - Scheduled delete of Resource Tracking Logs?

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5776]
Questions for stakeholders:

- Every event is logged for each Officer in the Resource Tracking Log. How log do these events need to be kept before they can be deleted?

- If it is determined the events can be deleted every x days/weeks/months can this be scheduled?

- To eliminate so many events in the log it may be possible to override the existing event with the new event, this would mean there is no history of events for Officers. Is this an option the stakeholders would consider?

![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/f8d785e7-6254-4d77-b20c-8a8f6bdff16c)

**Comment by dianamartin** [comment]
- We talked to the stakeholders and they said they'd be okay with keeping only 1 week of "Resource Tracking logs". 
- I created an automated task to tag the logs as "Marked for Deletion" if a records from the previous week
- All new and current records are marked as "Active"

@johnclary 
- We (DTS Apps) can either delete on a monthly basis similar to flex notes or have chia work on an automated way to batch delete records in a specific status? thoughts?

**Comment by johnclary** [comment]
If we're estimating a few thousand records a month, I agree that's probably more than we want to retain if we can avoid it, but I also don't think it will significantly impact app performance in the near term. Suggest we hold revisit in 6-8 weeks when we have more data. Perhaps there could be some useful reporting from this data?

**Comment by dianamartin** [comment]
Will create a new issue to follow-up in a few sprints. Closing this.
