### ISSUE TITLE
Dispatch Tracking Sprint Review

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5777]
Scheduled 4/29
Sprint Review agenda/slides

- Review Dispatcher User Testing Results (April 5th - 14th)
- List of quick fixes during Dispatch User Testing
- Review PEO User Testing (April 19th
- Next Step:
 Go Live date 5/3 issue #5854
Questions:
- What to do with historical data. 
We need to ask them what they'd like to do, just cut over
Export the records for retention purposes - the issues is we won't be able to keep attachments, they don't download easily from what I remember
If we plan to keep the records, how long and set a reminder to purge them in a few years.
- Resource Tracking Logs issue #5776
- would like to request add in the "Issue Type" tab "Inspection" and once "Inspection" is selected I would like a request for a drop down box to be created for "Type of Inspection".
The different types of inspection are: Taxi, Limo, Charter, Pedicab, Bus, Electric Low Speed Vehicle (ELSV), Valet, Horse Drawn Carriage (HDC), and Peddle Pub Crawler.

- I would also like to request to add in the "Issue Type" tab "Airport" and once "Airport" is selected i would like a drop down box to select "Visit" and "Inspections". - **amended will add to the Out of Service options**

This information will be used to collect data on certified Ground Transportation Officers, what type of inspections they conduct and the number of times they visit the Airport and or conduct inspections on Airport premises.

Currently they are using a Excel spreadsheet that they fill in everyday which is time consuming and only one Officer can complete this task via Excel at a time. issue #5888

**Comment by dianamartin** [comment]
@moorerst I think we can close this, right?

**Comment by moorerst** [comment]
sprint review complete 
Agenda: https://docs.google.com/presentation/d/1pfj4osqD8TswDIcgrepBrnhrzs0Bhwzv0N-6_SzW-lE/edit#slide=id.p
