### ISSUE TITLE
[RPP] License Plate Fields inserting Copied/Random letters during Mobile input

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5779]
![image](https://user-images.githubusercontent.com/67915167/114450513-b7c04780-9b9b-11eb-948d-74c2eadc646a.png)

While filling out the RPP application on mobile, entering in the license plates behaves abnormally. As I enter in characters on my phone everything seems fine until the 3rd/4th character. The box fills with similar characters that were already entered.

For example:
1st characters - TES
generated after entering S - TETES
adding - YG
turns into - TETESYTETESYG

This seems to happen for all characters. After 3rd character is entered it creates extra characters and also every 2nd character entered thereafter creates more duplicated characters.

**Comment by johnclary** [comment]
@ChrispinP please test this again

**Comment by moorerst** [comment]
@ChrispinP I cannot duplicate this issue when entering license plate info from my android

**Comment by ChrispinP** [comment]
Yea, the issue is still occurring for me. I can type in numbers without it generating the extra characters but letters will create the extra letters.

Here is a related article I found: https://stackoverflow.com/questions/58045310/bizarre-code-issue-extra-characters-appearing-on-input

We may need to update/modify the way we do the keyup function on these fields.

**Comment by ChrispinP** [comment]
@chiaberry can you identify a way we can update our capitalization keyup functions to standardize for all apps?

**Comment by johnclary** [comment]
thanks for that research @ChrispinP. two ideas:
- make the input all-caps after the user un-focuses from the form input
- stop worrying about the capitalization and just remove the code

@chiaberry if you could spend a lil time on it this week we'd appreciate it. sounds like it's kinda hard to reproduce, but it'd be worth trying on browserstack.

**Comment by chiaberry** [comment]
I wasn't able to reproduce the random letters, but I did notice that its hard to insert something in the middle of what you've entered, because the cursor keeps jumping to the end of the field. 

Also I can't tell why yet, but the first address input here isnt going to all caps on my phone nor my browser
https://atd.knack.com/test-mar-26-2020-rpp-city-of-austin-residential-parking-permits-portal#apply-for-permits/enter-permit-information/6091e44e5d307b001c439284/

in RPP Test I changed it so "make the input all-caps after the user un-focuses from the form input". The first address input still isnt going to all caps, im poking around some more to see why

**Comment by moorerst** [comment]
@chiaberry have you had a chance to poke around further on this issue?

**Comment by chiaberry** [comment]
I haven't made any progress on why the first address input isn't going to all caps, does it happen on your device as well?

**Comment by moorerst** [comment]
@chiaberry sorry for the delay. No it does not.

**Comment by johnclary** [comment]
@chiaberry please move the code you've written to production. then we'll re-test the issue you're experiencing.

**Comment by chiaberry** [comment]
I moved the code from RPP test to production. All the inputs here https://atd.knack.com/parking#verify/ go to uppercase once i leave the input, except the first address input. I'm on chrome.

**Comment by moorerst** [comment]
@ChrispinP can you re test this? Thanks

**Comment by ChrispinP** [comment]
Did we have Address capitalize before?

In testing the Address field, the focusout function is technically working but if I use the autocomplete feature, that takes precedence over the focusout. I would have to tap into the address field again, make any changes, and tap out again for it to capitalize. Unfortunately the Knack Address field doesnt include City and State in that formatting so I would remove this function for the Address. Otherwise we would have to update to also capitalize Address 2, City, and State even when using autocomplete.

For the License Plates, all 6 fields are correctly capitalizing once I leave the field.

**Comment by moorerst** [comment]
@ChrispinP are you ok with the results for the license plate field. Can this issue be closed?

**Comment by ChrispinP** [comment]
Updated commenting and removed the address handler since it is not working as intended.

Complete, closing

**Comment by ChrispinP** [comment]
Created PR 64 for review https://github.com/cityofaustin/atd-knack/pull/64
