### ISSUE TITLE
Ability to view aerial imagery on map

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5780]
As a Moped project creator, I need to be able to view aerial imagery when I'm selecting/drawing project locations.

Add a radio buttons to the exsting layer toggle (pictured below) that switches between the mapbox basemap  and Nearmap imagery.

![Screen Shot 2021-04-12 at 3 18 56 PM](https://user-images.githubusercontent.com/14793120/114456431-78492980-9ba2-11eb-9f85-fa58c970fb43.png)

**Comment by mddilley** [comment]
I've opened a ticket with CTM for an API key. I requested the the same URL restrictions used for the Moped Mapbox token.

**Comment by mddilley** [comment]
Code used for aerial imagery in VZE https://github.com/cityofaustin/atd-vz-data/blob/e99a1ab0bb1f0bd7e4b45bb0f8ebad93c4a42b37/atd-vze/src/views/Locations/LocationMap.js

**Comment by mddilley** [comment]
Just received the API key from CTM. It is saved under **Moped Nearmap API Key** in the Developer vault in 1Password. I'll add a note about its location in the Moped dev docs and test the key this week.

**Comment by mddilley** [comment]
I tested the API key and was able to render the raster tiles locally. The CTM ticket is now closed. Will need to verify that all restricted URLs work, but the code above from VZE worked great.
