### ISSUE TITLE
Usability enhancements for identifying streets vs urban trails

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5781]
When selecting line features, users need to be able to easily distinguish between streets and urban trails.

Suggest a combination of:
- Adding contextual information to a pop-up that displays on hover, such as the street name or trail name
- Symbolizing trails with a thinner dashed line

Todo:
- Understand what existing CTN attributes we can add to the vectors to make this possible

<img width="1014" alt="Screen Shot 2021-04-12 at 10 09 07 PM" src="https://user-images.githubusercontent.com/14793120/114491347-1dccbf00-9bdc-11eb-8c87-8bae098ef2cd.png">

**Comment by johnclary** [comment]
@alan-deanda can we have your thoughts on this? can you propose one or more attributes that can be include in the CTN vectors that we can use to symbolize streets vs trails, extract a street name or tail name, or anything else you think would be useful?  cc @andrewshensky @amenity

**Comment by alan-deanda** [comment]
@johnclary , to not get into the "what do we call this trail type?" never-ending cycle, we can use the `LINE_TYPE` field. it includes the On-Street, Off-Street, Off-Street Connectors and Street Crossings. I'll symbolize all non On-Street segments as dashed lines.

**Comment by amenity** [comment]
@alan-deanda - that sounds good to me!

**Comment by alan-deanda** [comment]
@mddilley the new vector tile layer can be found [here](https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/CTN_Project_Extent_VTs_with_Line_Type/VectorTileServer)

**Comment by mddilley** [comment]
@alan-deanda Thanks so much for the updating the layer so that I could test it out, and I am able to filter the layer by the `LINE_TYPE`. 🙏

The more I think about it, it would also be useful to include the `LINE_TYPE` field as an attribute in the vector tile layer. Further down the Moped mapping experience, we show the user what features they have associated with a project, and this part doesn't interact with the vector tile layer. The `LINE_TYPE` would be needed to set the `line-dasharray` paint property there.

**Comment by amenity** [comment]
@mddilley @alan-deanda Definitely agree we need the attribute in the vector tile layer so that we can adjust symbology based on user needs and feedback. 

Actually, in the interest of separating content from presentation, we may want _just_ the attribute in the vector tiles. @johnclary  — I bet u have thoughts. 😏

**Comment by alan-deanda** [comment]
@amenity , @mddilley, @johnclary  the line type attribute field is included in these vector tiles. let me know if they give you any issues. on the GIS side, a trail has the following fields:
![image](https://user-images.githubusercontent.com/42655533/114747904-2de0bd80-9d06-11eb-9163-8a71d960757c.png)
a street has the following fields:
![image](https://user-images.githubusercontent.com/42655533/114747982-42bd5100-9d06-11eb-902f-17f7fd5d318d.png)

it's interesting that it removes fields if there is no value, or the value is null. this should save some more space/eliminate worries of a vector tile getting heavy from adding more attribute fields to it.

**Comment by johnclary** [comment]
thanks @alan-deanda!

**Comment by mddilley** [comment]
I tested out some methods of adding dashed lines for trails, but Mapbox GL JS isn't quite there yet. [Line-dasharray](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-line-line-dasharray) works but it doesn't support data-driven styles so there is no way to apply the dashed lines to the trails in the project summary map. 

I also tried [line pattern](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-line-line-pattern), but there is a known issue with this overriding color styles (making everything grey). It also requires a fallback pattern for "On-Street" which leaves no way to apply a solid line to the street lines.

In the end, I updated the "Off-street" trails with a custom green color. This can easily be adjusted, and hopefully there will better support for a patterned or dashed line for the trails in the future.

**Comment by johnclary** [comment]
Good news—[Mapbox GL v2.3.0](https://github.com/mapbox/mapbox-gl-js/pull/10591) now supports data-driven styles for `line-dasharray`. Will try to remember this when we re-visit [project components](https://github.com/cityofaustin/atd-data-tech/issues/3662) styling.
