### ISSUE TITLE
LINK MDS setup

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#5786]
- [x] work with LINK to coordinate the hand-off 
- [x] get them setup on MDS data ingestion
- [x] backfill April data by 5/5 monthly reporting deadline

> In their license application, they provided these links which will be activated prior to launch.
> https://wrangler-mds-production.herokuapp.com/gbfs/us_tx_austin/
> https://wrangler-mds-production.herokuapp.com/mds/us_tx_austin/

**Comment by mateoclarke** [comment]
- email sent to LINK suggestion secure token delivery method.
- email sent to ATD Mobility Services team on expected timeline for implementation.

**Comment by mateoclarke** [comment]
Add a checkbox for making sure we get a backfill of April data by their reporting deadline on 5/5

**Comment by mateoclarke** [comment]
Followed up today with LINK today about getting an access token upon request from Shared Mobility team.

**Comment by sergiogcx** [comment]
This is all done @mateoclarke let me know what steps you would like to take next. The only thing I can think of that we have not yet done is the trips reporting for April, which I can do next.

**Comment by sergiogcx** [comment]
Closing this, the data has been posted to Knack
