### ISSUE TITLE
Make shift "Description" visible to officers 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5792]
Lewis is adding important information for officers in the "Description" field for assignments. It needs to be easily discoverable by officers. 

**Scheduler view**
![Screen Shot 2021-04-13 at 4 05 15 PM](https://user-images.githubusercontent.com/1463708/114621316-2e2f7900-9c72-11eb-99a7-4a636b0b930a.png)

- [x] Add "Description" to pop-up when you click on calendar
![Screen Shot 2021-04-13 at 4 09 18 PM](https://user-images.githubusercontent.com/1463708/114623116-6f288d00-9c74-11eb-93f5-cc61b8b34305.png)

- [x] Enable calendar pop-up on "My Assignments" page (is this a bug that's not working?)

**Comment by amenity** [comment]
@SurbhiBakshi - size plz 👕🙏 ... Setting for next sprint, but would be great to do it sooner if you find the time.

**Comment by SurbhiBakshi** [comment]
Think it might be a good idea to also put the description in the email notification the officers get?

**Comment by amenity** [comment]
@SurbhiBakshi - YES! That's a great idea.
