### ISSUE TITLE
CTM Request for ArcGIS Pro to be added to the Citrix Storefront App

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#5793]
Nathan in ATSD asked about ArcGIS Pro being added to Citrix.

**Comment by jaime-mckeown** [comment]
Submitted CTM Request for ArcGIS Pro 2.6.2 to be added to the Citrix Storefront App.

**Comment by johnclary** [comment]
Cool—this should come in handy for others as well.

**Comment by jaime-mckeown** [comment]
- Boris at CTM has been in contact to get to the Application location. CTM will be installing Pro today and doing some testing before making it available to users next week.
- After chatting with Scott about how Citrix works, I modified the request to make sure they apply the same settings to the Pro group that exist on the ArcMap Group, that way everyone will have access to both Apps.

**Comment by jaime-mckeown** [comment]
- Pro was added to Citrix this morning. I tested it and it works great.
- Let Nathan know that Pro is now available in Citrix.
