### ISSUE TITLE
Delete a corrupted project

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5794]
Opening https://moped.austinmobility.io/moped/projects/156 in staging results in WSOD ☠️

**Comment by sergiogcx** [comment]
Rather than deleting a corrupted project I wondered if it would be possible to change the code and make it more stable, this because corrupted projects might keep appearing in the future. It seems to be a one-liner simple fix for this error.

**Comment by sergiogcx** [comment]
Debugging steps:


<img width="661" alt="2021-04-14_17-50-08" src="https://user-images.githubusercontent.com/5282430/114791436-30fe9c80-9d4c-11eb-8014-0ea02f3e8112.png">

<img width="759" alt="2021-04-14_18-06-35" src="https://user-images.githubusercontent.com/5282430/114791465-3825aa80-9d4c-11eb-99ec-1e06b9294c43.png">
<img width="1027" alt="2021-04-14_17-51-01" src="https://user-images.githubusercontent.com/5282430/114791486-407de580-9d4c-11eb-892e-fc0eb877b54a.png">
<img width="1085" alt="2021-04-14_17-52-22" src="https://user-images.githubusercontent.com/5282430/114791495-44aa0300-9d4c-11eb-962c-aea953c4ade9.png">

**Comment by amenity** [comment]
@sergiogcx — I'm still seeing nothing

**Comment by amenity** [comment]
And refreshed the page and it loaded fine. 😅

**Comment by amenity** [comment]
@sergiogcx — I'm still seeing this on staging: https://moped.austinmobility.io/moped/projects/156
(Go to [Projects](https://moped.austinmobility.io/moped/projects) > `john's latest project`
