### ISSUE TITLE
Feature: Review new Robin Mobile App Office Pass

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5798]
Noticed a new option of the Robin desktop app to Book A Desk. Log into the mobile app to see if it was there also and saw this new feature Office Pass. Was not aware of this new feature. 
Contact Robin Support asking what is the policy for communicating new features:  
We did send out messages to owners this week, you should have received one yesterday via our messenger app. I'd also recommend signing up for product updates via our Product Updates page here. Folks who are subscribed to this page will receive the latest updates from Robin powered.

I don't log into the application daily so I did not notice the message on the messenger app.

Research How the Office Pass works:
![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/d3a450cd-655f-4e7d-adaf-15a71dde1ba1)

**Comment by moorerst** [comment]
We need to test the "Office Pass" functionality bc they want to limit (cap) the number of users coming into BOP to make sure they're within the 50% threshold of staff, so Stephanie and I tested a little bit but we need to test limiting staff to certain days and seeing if that will work for them. I've already warned them that this

**Comment by moorerst** [comment]
Tested Office Pass feature
Set up a Office Pass for 
Barton Oaks Monday-Wednesday
Barton Oaks Tuesday - Thursday

- Diana added me to the Barton Oaks Monday - Wednesday Office Pass. It was a Thursday when we were testing. When I attempted to Book a Desk from Robin desktop and mobile received message Do not have access to the Office on this day.
- Diana added me to the Barton Oaks Tuesday - Thursday Office Pass and I had access to book a desk

The Analytics in Robin provides data on Desk Availability 
  
![image](https://user-images.githubusercontent.com/56606465/116894733-02ac0880-abf8-11eb-8f89-89ee2195b007.png)

@dianamartin is there any info you want to add to this before we close it?

**Comment by dianamartin** [comment]
## Office Pass Functionality
- Can create as many custom office passes for locations and access days
- Can add individual people
- Can add groups to the access pass
- Can be added to multiple office passes

- When you designated under an office pass, Robin mobile banner shows that says you do not have access to this building today (something like that)
  - Prevents users from reserving a desk for that day

@moorerst I added my notes or FYI stuff
