### ISSUE TITLE
Investigate and address User API failures

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#5799]
When trying to create accounts for Andrew and Diana in Moped Staging, Amenity ran into a problem which came down to API errors. For Andrew's account, a Cognito account was created but his permissions did not make it into the DynamoDB table or the User table in the Moped DB. The UI showed an endless spinning wheel.  Andrew's entry in the staging user pool showed that his temporary password was never made permanent by the API.

#### Response when attempting to create Andrew's account again
![Screen Shot 2021-04-14 at 10 50 32 AM](https://user-images.githubusercontent.com/37249039/114747802-da2aa000-9d16-11eb-8bb2-93fe37df7c6d.png)

#### Entry in staging Cognito user pool for Andrew
![Screen Shot 2021-04-14 at 11 02 56 AM](https://user-images.githubusercontent.com/37249039/114748110-3261a200-9d17-11eb-924e-f7083dd9ad39.png)

**Comment by amenity** [comment]
Plot-thickening update: 
- I was able to create a test admin account in staging, so
- I tried adding Andrew as an admin and got the same forever-🔄  as before
- I tried adding Andrew as an editor with `andrew.shenskytestemail@austintexas.gov` as the email and it worked
- I went back to update Andrew's email to his real email and hit save — _leaving the password field blank  — not sure if that is kosher_ — got forever-🔄  
- Refreshed the page and the email address update showed up
- Asked Andrew to try logging in: "When I click the city of austin sign-in button it seems like it just reloads the page"
