### ISSUE TITLE
Update automated VZA emails to officers

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5800]
- [x] Include [shift "Description" field](https://github.com/cityofaustin/atd-data-tech/issues/5792#issuecomment-819545446)
- [x] Add [Quick Links blurb](https://docs.google.com/document/d/1OBxv49_LD_T2YT9AkyRugjmiScBCnQfI8k3WzRan2Qw/edit#)

**Comment by SurbhiBakshi** [comment]
### Notes - 

Added Shift Description and Quick links blurb to 
- [ ] Email officers get when they sign up
- [ ] Seven day reminder email
- [ ] One Day reminder email
- [ ] Email when details on an assignment change
- [ ] Email when an assignment is cancelled.
