### ISSUE TITLE
Turn "VZA Officers" contact list into Outlook group

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5801]
This way other people can email all officers, they can email each other to swap shifts or ask questions, etc.

**Comment by dianamartin** [comment]
- Testing creation of groups in desktop outlook v. web outlook
- Created 2 test groups
  - vza desktop
  - vza web
- Added Surbhi and Amenity as members in both groups
![image](https://user-images.githubusercontent.com/21112975/114889860-1a9a2480-9dd0-11eb-9d83-d2dc91933b5d.png)

**Comment by SurbhiBakshi** [comment]
@amenity - One way to reduce efforts to maintain a contact list would be to give Lewis access to the [`Officers`](https://atd.knack.com/vza#officers/) page with the contact information for all the registered officers. He could export that out as a CSV and plug those in the email as and when required.

**Comment by amenity** [comment]
@SurbhiBakshi — I like that idea! But it's also cool to see the group emails and, theoretically, for officers to be able to contact each other that way.🤔

**Comment by dianamartin** [comment]
Messaged Amenity
>Hey, remember you asked me to create a VZA Officer MS Group? Do you want me to delete the Groups I created for testing? I had created these ones
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/836f1692-c99e-4e56-aa2b-7bb4d995fb63)

**Comment by dianamartin** [comment]
- [x] Deleted `TEST VZA desktop`
- [x] Deleted `TEST VZA web`

Did notice `Trial - VZA Development`, either you guys create this one? @amenity @SurbhiBakshi

**Comment by dianamartin** [comment]
@amenity if this is all good, can we close this issue?

**Comment by amenity** [comment]
Looks good to me, thanks!
