### ISSUE TITLE
Create documentation on VZA Power BI workflow and hand off process to Xavier

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5802]

**Comment by SurbhiBakshi** [comment]
### Notes - 
Confirm Xavier has access to 
- [ ] has access to the reporting table in the VZA application
- [ ] access to the Citation Audit by STEP report
- [ ] One Drive location for Power BI report
- [ ] edit/share permission to the Power BI report
- [ ] access to Google Doc with documentation
