### ISSUE TITLE
[TDS] Enhancement: Ability to Hide Summary Name or Row for Table Groupings on Mitigation Tables

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5808]
Ability to hide all Summary Names or the entire Summary Row for Table Groupings
![image](https://user-images.githubusercontent.com/67915167/114772116-0b18ce00-9d33-11eb-8cb7-1afcf061cffe.png)

Reached out to Knack and there is no current options to exclude. Will need custom code for this.

This will de-clutter the Mitigation Tables, especially for the Memo where clarity and spacing is important.

**Comment by chiaberry** [comment]
I highlighted some of the rows/cells here https://atd.knack.com/test-tds-02-apr-2021-transportation-development-services-portal#tia-mitigations-directory/tia-mitigation-details/60677899da9d57067ec52e32/

Are the pink cells the ones you want to hide? The text inside the cells. Except not the last pink cell in the table, the one that just says "total" ? 

![Screen Shot 2021-04-15 at 11 15 08 AM](https://user-images.githubusercontent.com/12474808/114902912-e2004800-9ddb-11eb-921f-7b4c53db5676.png)

**Comment by ChrispinP** [comment]
@chiaberry That last row is the Summary row for the entire table. In Knack we already have the option to hide that last row and even decide how it sums (min, max, avg, sum).

The other 3 pink rows you highlighted yes. These will have the Group Header name in the Group Summary row. We need to be able to either hide the text, simplify it to something like "Group Total", or be able to hide the Group Summary row completely.

Thanks

**Comment by chiaberry** [comment]
https://atd.knack.com/test-tds-02-apr-2021-transportation-development-services-portal#tia-mitigations-directory/tia-mitigation-details/60677899da9d57067ec52e32/

I have it so the text in the third cell in the table total rows is replaced with empty string, except for the last table total row.  Is the ability to hide summary name only on these two tables (Construction and Fee in Lieu), or are there other tables?

I need to run it by Mike / dev team to make sure the logic I used isn't too convoluted. And do some code clean up. But is this on the right track?

**Comment by ChrispinP** [comment]
Its looking much cleaner without that text. I also have those tables on the memo here:
https://builder.knack.com/atd/test-tds-02-apr-2021-transportation-development-services-portal/pages/scene_255

What would it look like if instead of leaving a blank string that it shows "Location Total"

**Comment by chiaberry** [comment]
I can't find the subtotal location totals on the memo, is it because the preview data is shorter? 

![Screen Shot 2021-04-23 at 9 46 59 AM](https://user-images.githubusercontent.com/12474808/115901597-0507a900-a427-11eb-9df2-5f9898509711.png)
Here is what it looks like with "Location Total" in as text. Should whatever text in that field be **bold** like the original styling?
![Screen Shot 2021-04-23 at 11 23 41 AM](https://user-images.githubusercontent.com/12474808/115901617-0933c680-a427-11eb-9e53-02dc54e65589.png)

**Comment by ChrispinP** [comment]
Yea we should bold Location Total so it matches the number bolding.

Here is what they look like on the Memo, Fee in Lieu table with only the 4 columns, and Construction table with only 2 columns.
![image](https://user-images.githubusercontent.com/67915167/115908464-d04c1f80-a42f-11eb-8690-8b42e3c9efcd.png)

https://atd.knack.com/development-services#tia-requests/tia-request-details/6025ace3cceb98001ca59fd2/memo-builder/6025ace3cceb98001ca59fd2/memo-details/604fda95464669001b89fe7c/generated-memo/604fda95464669001b89fe7c/

**Comment by chiaberry** [comment]
I have functions in the javascript in test-tds-02-apr-2021, you can choose what you want to replace the cell text with. I can also slack you the code @ChrispinP if that is easier

**Comment by ChrispinP** [comment]
Thanks @chiaberry 

Code reviewed in Test and looks good. Moved to production.

Ready to review

**Comment by ChrispinP** [comment]
Reviewed with Tracy and stakeholders, closing as complete
