### ISSUE TITLE
[TDS] Update JS to not hide Pro Rata Share % on Improvement Selection

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5811]
Currently if Mitigation Type: Mitigation Fee in Lieu is selected the Pro Rata Share % field will show. Once the Improvement selection is chosen the field becomes hidden again unintentionally.

![image](https://user-images.githubusercontent.com/67915167/114915413-247c5180-9de9-11eb-86ba-174b7a77dd4d.png)

![image](https://user-images.githubusercontent.com/67915167/114915553-4f66a580-9de9-11eb-8e27-b02427d42b02.png)

The Pro Rata Share % Entry field_488 needs to be visible if existing Type is Fee in Lieu or if it changes to Fee in Lieu and to be hidden if Type is blank or if Type is Construction

**Comment by mddilley** [comment]
There is a PR with the updated code [here](https://github.com/cityofaustin/atd-knack/pull/32)

And, the code has been updated in **TDS | Transportation Development Services Portal | BACKUP | 14 APR 2021** and can be tested at https://atd.knack.com/tds--transportation-development-services-portal--backup--14-apr-2021#tia-mitigations-directory/tia-mitigation-details/607766d886a1e30676ce819c/

**Comment by ChrispinP** [comment]
I have tested both forms and everything is looking good. updated production.

@TracyLinder Ready to review
