### ISSUE TITLE
SZB Collector App Introduction - Charles

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#5817]
Work with Charles to learn how to use Collector for SZB Editing.

**Comment by johnclary** [comment]
@jaime-mckeown would you please continue tagging this work with `Project: Beacon Data Tracking`?

**Comment by jaime-mckeown** [comment]
Charles still hasn't scheduled time to meet with Scott to get his tablet fixed. Just sent him a reminder to get that done.

**Comment by jaime-mckeown** [comment]
Charles stopped by on Tuesday to go over his tablet using Collector. He had set it to only use the old Collector, which was causing some issues. Got the tablet fixed and he is up and running again.
