### ISSUE TITLE
Bug on AMANDA TCI Report: Page Area Too Large

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5819]
_Submitted by Nathan C. w/ ROW via Email_
### I received the attached error while trying to send an deficiency report for both permits 2021-049888-EX as well as 2021-045864-EX.

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/d7d812ea-ef92-4c22-a0be-785757a4075e)

**Comment by TracyLinder** [comment]
**Email to Nate C**

I’ve created a DTS ticket for this and assigned it to Nate with our team (copied). He’ll be triaging it today and will follow up when he has more information and/or a status update for you.



---

FYI @Nadin-Nader

**Comment by Nadin-Nader** [comment]
Issue has been resolved with an IE reset. See email below:

> From: Chandler, Nathan <Nathan.Chandler@austintexas.gov> 
> Sent: Wednesday, April 21, 2021 9:38 AM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Subject: RE: Page area too large?
> 
> Good morning Nadin,
> 
> I have followed the detailed directions you sent me and have found no issues a moving forward at this time. Thank you for you help and have a great day!
> 
> Respectfully,
> 
> Nathaniel Chandler
> ATSSA Certified Traffic Control Supervisor
> Inspector C
> Office: 512-974-7828
> Cell: 512-695-9055
