### ISSUE TITLE
Enhancements: PEO User Testing 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5836]
Will we get a notification when a SR has been assigned to us like in Teams we get a beep?

- [x] Knack does not have the option to beep when an assignment is made. We can set up a email notification. Per Shavyvonne not all Officers have city email on their device. We will need to discuss how to handle the notifications.

For Manage My Time only options are Break/Lunch/Check Out how do we handle other Out Of Service reasons?

- [x] Other reason to be Out of Service i.e. meetings, car wash, etc. will need to be reported to the Dispatcher. Need to make this clear in the work flow/process
added instructions to the Manage My Time Section: 
**If you have other reasons to be "Out-of-service"
(ie. meetings, training, car wash, etc...)
Please contact the on shift dispatcher.**

The check box for Submit is not clear it makes me think that I am unchecking Submit?

- [x] we will need to look at other options for the submit button

- [x] had some issues with assigning the SR's to the PEO. The Assign To field was not populating, had to manually populate for testing - this was a Knack bug that was resolved on issue #5843

- [x] Added a required field for Attachment Description

**Comment by dianamartin** [comment]
@moorerst let me know if these changes are okay, then we can close this issue.

**Comment by moorerst** [comment]
All changes are complete and approved by the stakeholders. Closing this issue.
