### ISSUE TITLE
Bug: Dispatch Tracking - Assign To field not populating

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5843]
After selecting the Activity - Dispatch Investigator and assigned to a specific PEO the Assign To field is not populating.
Was working previously seems to stop working mid morning 4/19 - noticed during PEO User Testing

**Comment by moorerst** [comment]
reviewed internally seems to be a Knack bug - Knack ticket submitted

Response from Knack:
Thanks for reaching out and providing us links! We're currently looking into this issue, where forms with a data source "connected to logged-in user" are not capturing the data into the fields as expected. We've also had some reports where record rules doing the same are also not working, so it looks to be related to the account/user role fields.
﻿
﻿We'll keep you posted on any updates, please let us know if the issue changes in the meantime.

**Comment by dianamartin** [comment]
Knack responded
>The team has released a fix for the issue you were seeing in your forms. Please go ahead and retest and let us know if you still see the issue (you may need to log out/in for the update to take place).

- I tested in the SR # `PSR00-002780`, added the TEST PEO and it finally showed up!
- Success..it is fixed

**Comment by dianamartin** [comment]
Will associate the missing SRs with the assigned PEOs so we can use it for reporting analysis
