### ISSUE TITLE
Enhancements to Dockless Mobility Data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5844]
Shared Micromobility
- [Data Explorer](https://micro.mobility.austin.gov/)
- [Summary Dashboard](https://data.mobility.austin.gov/micromobility-data/)
- [Open dataset](https://data.austintexas.gov/Transportation-and-Mobility/Shared-Micromobility-Vehicle-Trips/7d8e-dm7r)

**Comment by johnclary** [comment]
Closing this since we have deprecated our in-house micromobility data operations.
