### ISSUE TITLE
Go Live: Dispatch Tracking

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5854]
Schedule 5/3/2021
Task to complete for Go Live:
When is the best time to disable the Sharepoint list?

**Comment by dianamartin** [comment]
@moorerst We need to ask them what they'd like to do, just cut over
Export the records for retention purposes - the issues is we won't be able to keep attachments, they don't download easily from what I remember

**Comment by moorerst** [comment]
@dianamartin do we need to ask these questions prior to the sprint review on the 29th? If we discuss on the 29th is that enough time before go live on the 3rd?

**Comment by dianamartin** [comment]
What to do with the SharePoint database records shouldn't affect Go-live because it's historical data. We just have to discuss the plan to keep the records and to set a reminder to purge them in a few years.

**Comment by dianamartin** [comment]
Deleted 1012 records -csr
1 was from today

Deleted 3012 (3016 total)
4 from today

**Comment by dianamartin** [comment]
@moorerst Closing this since we got them on the system 5/3
