### ISSUE TITLE
Dropdown order of project roles, status, and phases should match in Gitbook

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5857]
Order, capitalization, etc. should match Gitbook
- [x] [Project roles](https://atd-dts.gitbook.io/moped/user-guides/project-roles) (DataTable used on the "Assign team" step for new projects and "Team" tab for existing projects)
![Screen Shot 2021-04-20 at 12 17 38 PM](https://user-images.githubusercontent.com/1463708/115438380-f032d780-a1d2-11eb-8491-8b05704d0ef5.png)

- [x] [Project phases](https://atd-dts.gitbook.io/moped/user-guides/project-phases) 
![Screen Shot 2021-04-20 at 12 24 30 PM](https://user-images.githubusercontent.com/1463708/115439236-f7a6b080-a1d3-11eb-8209-dde58144d5a5.png)

- [ ] [Project statuses](https://atd-dts.gitbook.io/moped/user-guides/project-statuses)
![Screen Shot 2021-04-20 at 12 25 08 PM](https://user-images.githubusercontent.com/1463708/115439345-19a03300-a1d4-11eb-8343-af1d97f4e7db.png)

**Comment by amenity** [comment]
@sergiogcx — I know you're updating some of these now so this issue may be irrelevant.

**Comment by sergiogcx** [comment]
Thank you @amenity, yes it's part of the migrations.

**Comment by amenity** [comment]
@sergiogcx — super. I just wanted to make sure the order in the frontend dropdown/picklist itself doesn't sort to alphabetical or anything else. Do you want me to close this issue?

**Comment by sergiogcx** [comment]
@amenity No I will close it, I need to have it open to remember to make sure I follow these specific instructions.

**Comment by amenity** [comment]
@sergiogcx - sounds good. Adding it to the "Data Model + Migration" epic you have underway.

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/296
