### ISSUE TITLE
TIA Enhancement: Default Scope/Submission Assigned Reviewer

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5868]
### When scope or submissions are created, default the reviewer to the lead case reviewer.
- [Example scope](https://atd.knack.com/development-services#tia-requests/tia-request-details/607f1c8e8e1051001b2a778a/tia-case-management/607f1c8e8e1051001b2a778a/tia-scope-submission-details/607f1d342c6105001b7dd0d6/)

**Comment by ChrispinP** [comment]
Case Reviewers will default to the Lead Reviewer if blank and by virtue, now Scope & Submission Reviewers will default to Case Reviewers for all 3 instances where this occurs; when a Reviewer creates a submission, when a Customer submits an application, and when a Customer creates a submission.

Ready to review
