### ISSUE TITLE
Automate CC Email to Site & Sub in AMANDA (Portal Changes) (On PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#5875]
As the Site & Subdivision group of DSD, I need a copy of certain EX permits emailed to my resource account when they are issued. I am currently manually emailing copies of certain EX permits to the Site & Subdivision group of DSD. I'd like the system to take over this function.

Stakeholders: Kim, Paloma
DTS Manager: Nate

Acceptance Criteria:

On DS & EX folders (all subtypes)
Upon folder issuance, the system emails a copy of the permit to sitesubpermits@austintexas.gov
This happens without user interaction
This feature works when a user issues the permit, and when the permit is issued automatically as part of the post payment procedure.

Older Info:
Description: 2/28/18 - Maria Becker should be copied on all EX permits except AWU. This may be updated to include DS permits.
8/3/18 Update - SSI has a group email account now. Send the permits to that email address instead of Maria.
Request Date: 2018-11-29 16:36:00
Request ID: DTS18-103020
DTS URL: https://atd.knack.com/dts#service-requests/view-issue-details/5c0069f1efe6294ca5e476c6

Migrated from atd-amanda #34

**Comment by SubhaShroff** [comment]
@Nadin-Nader **SCTASK0137748** ( for commit:efc94227e983 ) DEV deployment request is submitted.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to DEV by CM DevOps Team

**Comment by SubhaShroff** [comment]
@Nadin-Nader Can we request TEST deployment for this?. It can't be tested in DEV directly. the email will be sent only after post payment issue. So, we can test it in TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader As you agreed on Teams, I submitted TEST deployment request - **SCTASK0138138**

**Comment by SubhaShroff** [comment]
### Status:
Waiting for TEST deployment.

**Comment by SubhaShroff** [comment]
### YET to edit......
Tested on TEST for the following permits:
12657811 EX

**Comment by SubhaShroff** [comment]
@Nadin-Nader  following permits were activated with online payment on TEST instance. Please check with Becker if she got the emails for the below permits.
12657811 EX - Turned active. An email must have gone on **5/20/2021**.
12657569 DS - Tested in 2-3pm call today. (as part of Kim's demo).  Email must be dated **5/21/2021**.

**Comment by Nadin-Nader** [comment]
@SubhaShroff I spoke to Mariya and she informed me that both emails went through and yes there were 2 of each:

[11:09 AM] Becker, Mariya
    12657569 - Received twice 5/21
​[11:10 AM] Becker, Mariya
    12657811 - Received twice 5/20

**Comment by SubhaShroff** [comment]
### Status:
As per Becker feedback, with online payment (issued), emails are sent twice for each permit tested. I will need to look into this.

**Comment by SubhaShroff** [comment]
### Status:
I will take up this, once I am done with #6021 & #2616.  
Or as per the priority.

**Comment by SubhaShroff** [comment]
### Status:
I will look at this ticket today.

**Comment by SubhaShroff** [comment]
Reverted the code change done in the portal related procedure on TEST as the code change done for Back office is working for Portal also. That was resulting in double emails of each permit on post payment issuance.
Following are the Permits tested:
12658222 EX

### YET TO EDIT.............................

**Comment by SubhaShroff** [comment]
### Status:
Tested on TEST. Need to check with Maria Becker if the emails are received.

**Comment by Nadin-Nader** [comment]
@SubhaShroff  I am waiting on AnnMary to get back to me about the emails.

**Comment by SubhaShroff** [comment]
### Status:
Waiting on AnnMary to get back to me about the emails.

**Comment by Nadin-Nader** [comment]
@SubhaShroff AnnMary got back to me via chat and let me know that she found 3 out of the 4:

> [2:13 PM] Becker, AnnaMary
>     12658248 received
> ​[2:15 PM] Becker, AnnaMary
>     12657571 received
> ​[2:16 PM] Becker, AnnaMary
>     12658222 received
> ​[2:22 PM] Becker, AnnaMary
>     i didn't see 12658249 

**Was not Found**
_12658249 EX - Austin Water Utility (AWU) - Paid online. 'Activate Upon payment' is Yes. No fees were inserted. Manually added the fees and paid online that triggered Issue. - Batch job added, so, Email must be sent._

Seems like its working. I am pretty sure the other was there but since it has been 14 days it probably got lost in the emails. Do you want to try another EX AWU by itself to see if it goes through? Let me know what you think

**Comment by SubhaShroff** [comment]
Sure @Nadin-Nader  I just did another EX AWU - 12658432 on TEST. OnlinePayment is done.
With the payment, permit turned ACTIVE and it triggered the batch job to send  the email.
![image](https://user-images.githubusercontent.com/51680715/123480986-b9a97c80-d5c8-11eb-8654-2fe49cfa6c31.png)
![image](https://user-images.githubusercontent.com/51680715/123481105-e78ec100-d5c8-11eb-86ed-5ed58aa3bd8e.png)

Please check with AnnaMary for this one.

**Comment by Nadin-Nader** [comment]
**Status:**

Still waiting on Response from Mariya Becker on This. I will also ask AnnMary Becker if i dont hear back from Mariya.

**Comment by Nadin-Nader** [comment]
@SubhaShroff I got a response and they did get the email but they also got a duplicate:

> [9:58 AM] Becker, Mariya
>     Is it an email from Friday??
> ​[9:59 AM] Nader, Nadin
>     
> yes from the 25th EX AWU - 12658432
> ​[10:00 AM] Becker, Mariya
>     We got it. . . actually, we got that email twice lol

Email:

-----Original Message-----
From: noreply@cityofaustin.org [mailto:noreply@cityofaustin.org] 
Sent: Friday, June 25, 2021 3:15 PM
To: DSD Site Sub Permits MB <SiteSubPermits@austintexas.gov>
Subject: [Subtype], [PermitNumber] Permit Approved and Attached

*** External Email - Exercise Caution ***

This permit has been issued and is attached to this email.
Please contact the permit staff you've been working with if you have any questions about your permit.
CAUTION: This email was received at the City of Austin, from an EXTERNAL source. Please use caution when clicking links or opening attachments. If you believe this to be a malicious and/or phishing email, please forward this email to cybersecurity@austintexas.gov.

[https://app.zenhub.com/files/140626918/f7d55331-bf59-4ec3-96e8-8c582539b42c/download](https://app.zenhub.com/files/140626918/f7d55331-bf59-4ec3-96e8-8c582539b42c/download)    <PDF from email

We can try one more time if you want to make sure it doesnt actually send a duplicate. What do you think?

**Comment by Nadin-Nader** [comment]
Approved for PROD and close

**Comment by SubhaShroff** [comment]
### Status:
**PROD Deployment is done** for both #1877 and #5875.

**Comment by Nadin-Nader** [comment]
Sent email to Kim and Paloma letting them know this is on PROD. I also asked them to let me know if i can close the cards tomorrow or early next week. See email below:

> Hi Ladies,
> 
> Hope you are both doing well. I wanted to let you know that the changes to cards 1877 and 5875, Automate CC Email to Site & Sub in AMANDA, Are now in PROD. Well they have been for a few days now. Please let me know how things are going with this and if I should close it tomorrow or early next week.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services

**Comment by SubhaShroff** [comment]
### Status:
Waiting for stakeholder feedback to Close.

**Comment by Nadin-Nader** [comment]
Per Paloma, this can be closed along with 1877
