### ISSUE TITLE
Tablet Troubleshooting with Parking Meters

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5877]
### Objective 
- Meet at Cameron at 9 am in Allandale
- Get all Parking Meter tablets working, access to the new ArcGIS Collector app and address outstanding tablet issues.

### Participants
Jaime, Andrew, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting on 4/22
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
Parking Meters 
Has 6 tablets
- Nick F.
- Gilbert M. 
- Wilber S.
- Steve S. 
- Juan A. - getting set up, Jacob's old profile was on it
- Jacob C. - might reassign Kyle

**Comment by jaime-mckeown** [comment]
Created new AGOL Accounts, configured Bios, added to Groups:
- Nick F.
- Jose A.
- Ali M.
- Kyle B.
- Wilber S.
