### ISSUE TITLE
Bug | Can't add or edit Team members

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#5880]
The save action in the “Assign Team” view is disabled. This makes is impossible to add new team members or update existing ones. It's happening in both the “New Project” workflow and “Team” tab in project summary.

https://user-images.githubusercontent.com/5697474/115590966-36ea0580-a297-11eb-8f4d-e4027729f6bb.mov

**Comment by sergiogcx** [comment]
Ok, I see a problem in the code already. Sorry for this bug, let me go ahead and fix it.

**Comment by sergiogcx** [comment]
There is a PR, ready for review:
https://github.com/cityofaustin/atd-moped/pull/289
