### ISSUE TITLE
Research 311 integration with Knack Dispatch Tracking

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5884]
Communicate with 311 staff Chandra and Bill about getting in the queue to integrate 311 SR's with Knack Dispatch Tracking system
SR's to be integrated

- Pay by Phone
- ATD Booting Complaint
- RPP Enforcement
- Parking Violation Enforcement

**Comment by moorerst** [comment]
4/26 emailed 311 personnel to get this request on their radar

**Comment by moorerst** [comment]
5/3/2021
Response from Chandra: 
Greatly appreciate you reaching out, as I’ve included this on our Transportation request document. At this time, does your workgroup have a timeline of any sort you’re working towards? 

Austin 3-1-1 is in the process of conducting a Standardization Project. The project will include me working with all ATD Divisions and bringing documentation, visio flows to standards and integrating all service request on our mobile app. We will need to work closely together to identify an approach how best to proceed given both our groups current efforts. 

Lets definitely get a meeting scheduled to further discuss.  

Response from Diana:
Today we started having our users go-live in their dispatch tracking application. I have configured the application for integration with 311 SR data like we have in many of our other applications. We are working towards doing the integration now, but we were reliant on 311’s time line. When I spoke to Bill he said that y’all were pushing out a modified SR type for the Parking Engineering group for the “Pay to Park” type in April and to provide some lead time and communicate with 311 so that we can begin our integration process.

Clary, John how have you done this process with 311 and CTM in the past?

**Comment by johnclary** [comment]
Hi all—Before we meet with Chandra, I think we need to get more aligned on the SR types and flows. We should address Shared Mobility's 311 SRs ([#5720](https://github.com/cityofaustin/atd-data-tech/issues/5720)) in addition parking enforcement. Do we know what the Shared Mobility SR types are?

@dianamartin, can you re-share the workflow/notes you had about the parking SRs? I think you mentioned that in some cases a booting complaint may go to another workgroup besides Parking Enforcement?

Does it make sense to bring together Shared Mobility and Parking Enforcement to talk through all this? I believe y'all have already spoken with both groups about this.

**Comment by moorerst** [comment]
document Shared Mobility SR process

**Comment by dianamartin** [comment]
@johnclary @moorerst I finally found the issue that had our notes with the stakeholders when we asked them how they handled 311 requests #5391

**Comment by dianamartin** [comment]
We have these Parking SRs: 

- `ATD Booting Complaint`
- `Parking Violation Enforcement`
- `Residential Parking Permit Enforcement`
- `Pay-by-Phone App` - this is the one that changed recently, this April 2021
- `Shared Micromobility` - Shared Mobility work group, Joseph's group

We aren't going to do this on just yet because they don't have an application to house the SRs 
- `Parking Machine Issue` - Parking Meters, not sure who is handling the SRs. Opening & closing them

**Comment by dianamartin** [comment]
I called Andrea M. bc Mary was out and Joseph was busy to clarify the Share Mobility Process. I whipped up their current SR Process
@johnclary @moorerst @SurbhiBakshi 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/13aca847-77f1-4e45-ac31-432c4b0f5365)

**Comment by moorerst** [comment]
scheduled meeting with Chandra(311) for 5/20

**Comment by SurbhiBakshi** [comment]
thanks @dianamartin for the workflow!

**Comment by moorerst** [comment]
Notes:
Previous Process

- Activate publication of SR to test system
- Coordinate with CTM for ESB message handling

New Standards

- Per Bill due to an audit there are now new standards in place that have to be met by the SR and Knack
- Need to set up work sessions to review which high level activities are needed for each SR type
- Each Activity is posted as a separate Activity
- Cannot provide a timeline for integrating the 5 SR's. Chandra will need to work with us on that

Paging Activity

- call back to 311 to stop paging
- 311 will not be closing SR's
- How could the Knack interface handle closing these SR's
- May have 2 SR types that used the Paging Activity Traffic 
Signal???/Traffic Sign Emergency???

Did some troubleshooting on the issue with out of order activities from Knack to CSR. 

- Reviewed detailed documentation from Motorola
- Meeting will need to be set up to discuss with the ESB team regarding
the messages being from the ESB??? John will set up meeting and include Bill

ATD Pay by Phone revised SR is active

**Comment by moorerst** [comment]
Waiting on Chandra to provide next steps. Will follow up on Tuesday 6/1.

**Comment by moorerst** [comment]
Sent follow up email to Chandra requesting some direction on next steps.

**Comment by moorerst** [comment]
emailed Chandra and Bill again for update on nest steps.

**Comment by moorerst** [comment]
Response from Chandra: During the call it was mentioned about the message reopening the requests, it would help to get some kind of a status on the research that was being doing on the message reopening the requests. 

Austin 3-1-1 will soon be able to start putting resources to this effort, as it will roughly take 3-4 weeks given the other projects in queue at this time. During this timeframe we will create tables to show what is in place now, look at each current SR type and the proposed additions to see what activities make sense to target. 

I will look to schedule a meeting the week of June 28th. 

Meeting has been scheduled for 6/30

**Comment by moorerst** [comment]
@dianamartin Question from Chandra: During the call it was mentioned about the message reopening the requests, it would help to get some kind of a status on the research that was being doing on the message reopening the requests. 
Is that question related to the Paging Activity?
Do we have any information on how Knack would handle this?

- Paging Activity
call back to 311 to stop paging
311 will not be closing SR's
How could the Knack interface handle closing these SR's
May have 2 SR types that used the Paging Activity Traffic
Signal???/Traffic Sign Emergency???

**Comment by dianamartin** [comment]
@moorerst I think that stop paging alert might be a question for John. We will need to discuss at Builder Huddle.

**Comment by johnclary** [comment]
@moorerst i need to get back in touch with Omar to do further research on the requests that are re-opening. based on our initial research I do not think it's related to paging. It appears to be an issue with the ESB.

With regard to paging—we can definitely update our integration to enable staff to stop the paging request in Knack. We did not know that 311 supported this functionality through the integration. We would need to work with  311/ESB team to implement that.

**Comment by moorerst** [comment]
Meeting scheduled for 6/30

**Comment by dianamartin** [comment]
311 Meeting on 6/30

### Currently
Activity Type -- Review Interface Request - Details: has the notes/comments for citizen

### New Standard
SR Activities --> Activity Outcome (preset choices)

DTS will need to review the SR Control Panel Reports
- we have 4 reports for Parking Enforcement
- we need to meet business reports 

## Paging Events
- What happens if no one responds to the page?
- Q: John - Can we page and close?
  - 15 minutes, Completed if there is a response back
  - Pager assignment message: location information
   - Copied to several phone numbers and emails
Overdue 2nd page - 15 minute, send to assigned staff member
- CC to other pagers and phone numbers
Overdue 3rd page - 15 minute, send to assigned staff member
- CC to other pagers and phone numbers
Page to 311 - Call them

**Comment by moorerst** [comment]
next meeting scheduled 8/2

**Comment by moorerst** [comment]
@dianamartin set up follow up meeting with stakeholders

**Comment by dianamartin** [comment]
Closing, created new issues for follow-up actions
