### ISSUE TITLE
Test GIS Laptop

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#5887]
Scott ordered a couple GIS laptops. When they arrive, I will test one out to see how they work.

Brian Craig was inquiring about them.

**Comment by johnclary** [comment]
It's done!

**Comment by jaime-mckeown** [comment]
Tested Precision laptop against current setup (latitude laptop remoting to GIS workstation), current setup is faster, will stay with what we have.
