### ISSUE TITLE
Spike | Provide recommendation on approach to improving testing workflow 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5889]
Would be great to have a way to preview PRs that involve backend development with the PR-specific database in place. 

Heroku- supported improvements to dev-ops pipeline

**Comment by sergiogcx** [comment]
There is a way to build any branch on demand using a feature called ``, this allows us to run a build workflow manually and select any branch we want to build.

To see it work go to Actions > Build & Deploy DevStage > Run Workflow (dropdown) > Select a branch (Right now only main works, meaning that main will be built in the separate devstage):

![image.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/bd2d9246-94fd-49d5-8ee7-57e330b445d9)

The output of the DevStage:
https://moped-dev.austinmobility.io/moped

Any branch can be selected, as long as they have been updated with the latest code from main:

![2021-05-03_20-53-36.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/e7977ce1-3cb3-4872-b00b-ec682210564b)
