### ISSUE TITLE
[TDS] Update Report Styling

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5894]
Once we determine the final set of reports needed, will need to update report styling so it is more readable.

Reports styling will be based off RPP reporting seen here: https://atd.knack.com/parking#reports/

**Comment by ChrispinP** [comment]
I have updated report styling for TIA so now the bar chart colors are matching the pie charts:
![image](https://user-images.githubusercontent.com/67915167/117165864-7af70300-ad8b-11eb-830d-53161ddaa6f5.png)

**Comment by ChrispinP** [comment]
Since case types were updated, the Case Type reports have also been updated.

![image](https://user-images.githubusercontent.com/67915167/118302955-7c6eac80-b4aa-11eb-8d78-008e3955593e.png)

**Comment by TracyLinder** [comment]
Looks great; closing.
