### ISSUE TITLE
Configure ADFS

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#590]
Configure single sign on on the TDSD application: https://atd.knack.com/development-services#home/

**Comment by johnclary** [comment]
I've initiated setup on the home page. I sent CTM our app metadata. They will complete their setup, send us their metadata, and I will finish up setup in Knack.

**Comment by johnclary** [comment]
@dianamartin this is done. would you please test?

**Comment by dianamartin** [comment]
@johnclary Certainly, I saw you working on it the other day.

**Comment by dianamartin** [comment]
@johnclary Tested ADFS sign in, works like a charm. 

Can we make the button color match the rest of the app? 
HTML `#163F6E`

**Comment by johnclary** [comment]
Yes—it’s a setting on the login page config.

On Sep 19, 2019, at 09:42, Diana Martin <notifications@github.com<mailto:notifications@github.com>> wrote:

*** External Email - Exercise Caution ***

@johnclary<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohnclary&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C62c38f51cfdb440b681608d73d17f8f5%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637045045476367015&sdata=bWNXB9DbpuVZPKgKnSpsJGicy4dLKcI9jY3c9%2FLGznA%3D&reserved=0> Tested ADFS sign in, works like a charm.

Can we make the button color match the rest of the app?
HTML #163F6E

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-data-tech%2Fissues%2F590%3Femail_source%3Dnotifications%26email_token%3DADQ3TIA375MZ5NWLYZ3IMMLQKOMV5A5CNFSM4IXGTTTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7D5ONI%23issuecomment-533190453&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C62c38f51cfdb440b681608d73d17f8f5%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637045045476377011&sdata=zWbW9OSaHE5yLSji%2BQKSkujPAze%2BUB7XRGaJtOsV0Jw%3D&reserved=0>, or mute the thread<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADQ3TICU75ZPQHKRZIZZNFDQKOMV5ANCNFSM4IXGTTTA&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C62c38f51cfdb440b681608d73d17f8f5%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637045045476387006&sdata=WQjKmP2LOrP8F%2BwMe2%2F68sOfvA40uagk4pyZbZT5OXk%3D&reserved=0>.

CAUTION:This email was received at the City of Austin, from an EXTERNAL source. Please use caution when clicking links or opening attachments. If you believe this to be a malicious and/or phishing email, please forward this email to CSIRT@austintexas.gov<mailto:CSIRT@austintexas.gov>.

**Comment by dianamartin** [comment]
I found where to update it:

_Home>Login Form_
_Options_ (on the left menu)>`credentials` (link the right of COACD)

Login Button (section)
Button Color:
