### ISSUE TITLE
[HR] Update CSS Code for Big & Small Buttons. Update JS for SSO and Big Buttons

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5904]
Update CSS Code for Big & Small Buttons. Update JS for SSO and Big Buttons

- [x] SSO
- [x] Big Button JS
- [x] Big Button CSS
- [x] Small Button CSS

**Comment by ChrispinP** [comment]
Updated all HR code and tested. Pushed to production.

**Comment by moorerst** [comment]
@ChrispinP Thanks Was able to login successfully Closing this issue
