### ISSUE TITLE
[HR] Remove Test Field from Accounts object

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5905]
![image](https://user-images.githubusercontent.com/67915167/115892554-e0a6cf00-a41c-11eb-86a3-8bf63e3adf1b.png)

**Comment by ChrispinP** [comment]
Also if Test Time Log Reporting should be repurposed or removed
![image](https://user-images.githubusercontent.com/67915167/115912053-79951480-a434-11eb-876a-1c37d281026f.png)

**Comment by johnclary** [comment]
@dianamartin will check to see if we need this report?

**Comment by dianamartin** [comment]
- [x] Deleted `Test` field in `Accounts` object
- [x] `TEST Time Log Reporting` page
