### ISSUE TITLE
[HR] Enhancement: Update Employee Acknowledgement & Signature for Telework Form

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5906]
Update Employee Acknowledgement & Signature for Telework Form

![image](https://user-images.githubusercontent.com/67915167/115893400-bf92ae00-a41d-11eb-9fee-28cc7e6ad45f.png)

- [ ] Update Acknowledgements to Checkboxes
- [ ] Add Electronic Signature Field to type name?

**Comment by johnclary** [comment]
The signature field may be used in a conditional rule for the approval process.

**Comment by moorerst** [comment]
closing this issue the employee acknowledgement and e-signature has been updated on the Telework Request form
