### ISSUE TITLE
Enable COACD button on Parking Enterprise Portal login URLs, add fancy buttons, and document process

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5907]

**Comment by dianamartin** [comment]
- Added SSO button code added to Backup - code worked properly
- Modified SSO button code in Parking Enterprise Portal PROD - code worked properly
- Confirmed SSO button on home page doesn't have extra space beyond button - Big button and small button
- Saw "SSO Log-in" buttons on "Home" page
- Signed into HOME page
- Saw "SSO Log-in" buttons on "Service Requests" page
- Saw "SSO Log-in" buttons on "Reports" - `dispatch-reports`
- Saw "SSO Log-in" buttons on "My Assignments" page

BUG?
- Did NOT see "SSO Log-in" buttons on "Resource Tracking"

**Comment by moorerst** [comment]
@diana is this what you are referring to as SSO Log-in? **Logged in as Stephanie Moorer - Account Settings - Log Out**
I see this on Resource Tracking.

**Comment by dianamartin** [comment]
@moorerst The log in button issue is on this issue #5925

**Comment by dianamartin** [comment]
Closing because there's another issue addressing the weird SSO Big button issues on Parking Enterprise
