### ISSUE TITLE
Consolidate Project Information Info Groups on EX, RW-TURP

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5909]
### There are multiple 'Project Information' info groups. We need to clean this up so the info tab makes more sense and is easier to manage. 

**Stakeholders:** Paloma, Izzy

**Acceptance Criteria:**
- Applies to EX, RW-TURP
- All folder Infos that are under the different 'Project information' Folder Info groups need to be moved to a single Project Information Folder Info group
- Currently the Project Information folder info group is shared between some DSD folders (like GENP) and ATD folders. All the infos used by ATD need to be moved to the Project Information info group NOT used by DSD for their folders.

**Comment by vschandramouli** [comment]
Updated AC, moving to backlog. @TracyLinder @Nadin-Nader  could you review this once? Need to know if I am missing something.

**Comment by TracyLinder** [comment]
@vschandramouli if there is a group code please add it. Otherwise the AC looks great.

**Comment by TracyLinder** [comment]
@vschandramouli can you please map the info codes to their group codes, and then move back to on-deck? Thanks.

**Comment by vschandramouli** [comment]
Question for Tracy: Can we rename ATD's Project Information Info group to something else to prevent confusion?

**Comment by SubhaShroff** [comment]
@vschandramouli I am not sure what are all the folders that come under DSD other than GENP. So, here are all the Project Information Group infos listed with the Foldertype. The list is sorted by infocode, so that we can see all the foldertypes together, that a infocode is configured to. Let me know if that helps any way.

[Proj Info Group - Infos & Foldertypes.csv](https://github.com/cityofaustin/atd-data-tech/files/8163530/Proj.Info.Group.-.Infos.Foldertypes.csv)

**Comment by Nadin-Nader** [comment]
@vschandramouli I asked Tracy your question, im just waiting on a response.

**Comment by Nadin-Nader** [comment]
@vschandramouli Tracy response is below:

> 
> Tracy Linder  12:23
> We can do whatever makes the most sense.
> We just need to be sure we don't rename things other departments are using, or change the group code for infos used by other departments.
> Is there a query that will tell us every folder an info is used on?

**Comment by vschandramouli** [comment]
@TracyLinder @Nadin-Nader 

Select foldertype from defaultinfo where infocode= 9999 

This query should give us all the folders an info is used on, per @SubhaShroff

**Comment by TracyLinder** [comment]
### Update

In V7 the system is consolidating the info groups into 1 Project Information section. This will solve this problem. I'm putting this in the icebox until we upgrade.

**Comment by KyleErich** [comment]
Closing this card. The Project Information section of the Info tab in both the EX and RW-TURP folders has been consolidated into one in V7.
