### ISSUE TITLE
[BUG] Custom SSO login buttons not rendering

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5925]
**Describe the bug**
The single sign on function is enabled on the old builder, we switched to new builder and found that only one page of an application isn't showing up properly.

**URL**
@SurbhiBakshi Can you add our page that isn't showing up properly here.

**Screenshots**

**Comment by dianamartin** [comment]
@amenity This issue needs to be issued at the next Dev Sync, not urgent bc stakeholders have a process to sign in, but just doesn't look like the rest.

**Comment by SurbhiBakshi** [comment]
Here is the page from Shared Mobility - [Impounds](https://atd.knack.com/smo#impounds/)

**Comment by amenity** [comment]
Thanks, y'all! @chiaberry - headed your way.

**Comment by dianamartin** [comment]
# No SSO Big Button here
![image](https://user-images.githubusercontent.com/21112975/116159867-9f315080-a6b6-11eb-83da-bda777bc8ee1.png)

# SSO Big Button on - Home
![image](https://user-images.githubusercontent.com/21112975/116159907-b2442080-a6b6-11eb-9641-379a47ac35e1.png)

# SSO Big Button on - My Assignments
![image](https://user-images.githubusercontent.com/21112975/116159961-c8ea7780-a6b6-11eb-86b9-50011bb58237.png)

# SSO Big Button - Reports - Is cut in half??
![image](https://user-images.githubusercontent.com/21112975/116160015-df90ce80-a6b6-11eb-981b-c98a87cf289c.png)

**Comment by chiaberry** [comment]
None of the pages that are missing the SSO Big Buttons have the knack sso div included `<div class="kn-sso-container column is-narrow"">`. I did a check on the settings for the pages (just another set of eyes to see if I caught anything) and it all looks the same on the pages with single sign on as the ones without. 

Should I contact knack support?

**Comment by dianamartin** [comment]
I wonder if we should review the backups in the "old builder" environment to see if the buttons are still behaving incorrectly

**Comment by dianamartin** [comment]
Testing 6/10 
### Tested Parking Enterprise again
- `Dispatch Reports page` - was not logged in, Big button SSO here
- `Dispatch Reports page` - was logged in, when logged out the log-in in half the size, refreshed and back to full size
- `Resources Tracking page` - was not logged in, no Big button SSO page, knack standard log-in
- `Resources Tracking page` - was logged in, when logged out the knack standard log-in, no Big button SSO 

@SurbhiBakshi 
### Tested Shared Mobility
- `Impounds` - was not logged in, the Big button SSO log in page not seen just the standard knack log-in
- `Home` - not logged in, looks like normal Big button SSO page

**Comment by dianamartin** [comment]
John said he went into the app and the SSO wasn't enabled.

**Comment by ChrispinP** [comment]
@dianamartin do we want to make sure all appropriate login pages have SSO enabled? Since Knack fixed SSO, we would just need to check the checkboxes. This could be something I can double check when I update certs this week if you would like. That way we can close this and #5448 out.

**Comment by dianamartin** [comment]
@ChrispinP You can definitely check. The issue for some of them is the SSO is checked by still not showing up on the page. I'm in SMO now, i guess I can re-check the Impounds page.

**Comment by dianamartin** [comment]
Just checked the SMO#Impounds page and the SSO wasn't checked, I think it was checked but there was a lot of issues with SSO when we migrated. I think Knack may have fixed the issues. 

Checked the Parking Enterprise page #ResourceTracking and that was also not checked. 

Confirmed the pages are working, closing issue.
