### ISSUE TITLE
[BUG] The "View Request Details" button in the "Review Approval Details" page incorrect direct

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5927]
**Describe the bug**
A user should be in the Review Purchase Requests section, under the "Review Approval Details" they will have a link that should take them to the Purchase Request details, but when a user clicks on the button is just takes them to the "All Purchase Requests" list. 

I don't remember if this was the behavior from the beginning, but apparently some users have indicated that this behavior is incorrect and it's broken. 

**URL**

**What steps can we follow to reproduce the bug you are seeing?**
1. Go to [Review Purchase Requests](https://atd.knack.com/test-apr-4-2021-finance-and-purchasing-system#reviews/)
2. Click on `File` icon
3. Scroll down to `View Request Details` - 
4. See error - takes you to [All Purchase Requests](https://atd.knack.com/test-apr-4-2021-finance-and-purchasing-system#purchase-requests/) rather than sending you to the Purchase Request details of the Purchase request that you're reviewing

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/b0b18208-08f1-4cc5-bae4-aa59278dc741)

**Code Information**
- `line 147` to `line 157` - in TEST Environment - `TEST | APR 4 2021 | Finance and Purchasing System`

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [x] Major — can only perform work using a workaround
- [ ] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Additional context**

**Comment by dianamartin** [comment]
@johnclary I forget what we were going to do if this was still broken. Oh, I just remembered that this was the Knack bug where the page rules were not editable. There is an issue for that #5928. Knack ticket open and their engineering group is looking into it.

**Comment by johnclary** [comment]
Sounds good. I'm pretty sure this issue is unrelated. [Here's the code](https://github.com/cityofaustin/atd-knack/blob/562128827327283868e4f1f2106963daeff910a4/code/finance-puchasing/finance-purchasing.js#L151) that creates that button link to the PR details.

I don't see how this was ever working correctly. The code just creates a link back to the "all purchase requests" table view.

**Comment by johnclary** [comment]
@dianamartin I fixed this by just removing the big button placeholder and javascript. I think the normal Knack link looks just fine. Asked for your review on the code change in the linked pull request.

<img width="964" alt="Screen Shot 2021-04-28 at 12 53 53 PM" src="https://user-images.githubusercontent.com/14793120/116450620-213d8880-a821-11eb-8a73-f4415160e265.png">
