### ISSUE TITLE
[BUG] Knack Issue: Page rules do not show up in new builder environment 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5928]
**Describe the bug**
When you log into the back end of the new builder, you are supposed to see the page rules. Right now, you see the number of rules, but the rules can't be seen or edited. 

**URL**
Ex. [Page rules page](https://builder.knack.com/atd/finance-purchasing/pages/scene_4/rules)

**Screenshots**
## No Page Rules
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/865eedc1-8b75-4ca9-90b5-a3c5af7b655c)

## Page Rules from back up app
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/a8445e3b-ff45-4523-a1b6-114a2b167a86)

**Comment by dianamartin** [comment]
A knack ticket was submitted for this.

**Comment by dianamartin** [comment]
Knack replied
>We went ahead and escalated this to our engineering team to take a look. We will reach out with any updates, please feel free to reach out if you have any questions in the meantime.

**Comment by dianamartin** [comment]
@johnclary 

Knack said 4/28/21
>Update: the team has fixed the issue you were seeing with the page rules not surfacing. Please take a look and let us know if you have any questions!

- I just tested and went in to the "Request Details" page and can see all 13 page rules

**Comment by johnclary** [comment]
hooray! thanks.
