### ISSUE TITLE
Reconfigure Barton Oaks Robin Floorplan

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5929]
Notes from Robin Barton Oaks Debrief meeting:
Barton Oaks
- Add New hotel spaces - went from 15 to 50 spaces
- Managers to this building, which places they have vacated to clean up the areas.
- Reduce dual monitors, going to 1 monitor only
- proposed set-up is: 1 laptop monitor - 1 monitor
some spaces would be just open spaces with expectation that user bring their own laptop and uses WiFi

Mgmt got information about return to work
Majority of staff will be in the office Monday, Wednesday
Still need to see how to manage that, how to make sure they are within the reduced numbers they're supposed to be within
Need to know who is coming when, there will be 47-50 pp coming in to the floor at the same time

**Comment by moorerst** [comment]
Barton Oaks Reentry Map
[Barton Oaks Reentry map 042621.xlsx](https://github.com/cityofaustin/atd-data-tech/files/6385943/Barton.Oaks.Reentry.map.042621.xlsx)

What equipment will be located at each of the Hotel desk?

**Comment by moorerst** [comment]
Per Gilda Please keep in mind that some of the spaces have people’s personal stuff so they will not be available until later. Maybe we can start with the spaces that are empty now and as people vacate their spaces, then add those to the list and include the amenities.

Scott provided a list of desk that can be made available (17) - other desk will need to have personal items cleaned out first. There are also desk that will need to be assigned to person or position

**Comment by dianamartin** [comment]
- Emailed with team about discrepancies in spreadsheet
- Got with Stephanie to review discrepancies
- Finalized desks that are available and active for hotel reservations
