### ISSUE TITLE
Digital Petition Go Live Plan

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#5932]
Go Live scheduled June 1st

- [ ] Week of 5/3 - Ryan will provide final language for Petition Description, Vehicle Information and Support/Oppose

- [ ] Update template with new language

- [ ] Week of 5/3 Ryan will provide list for internal user testing

- [x] Work on training documentation
Help Guide: https://docs.google.com/document/d/1h5kUKP3LnmotI5WypN0SUU99i9saoFC8oxlPg3v6sHI/edit

- [ ] Week of 5/10 Complete internal User Testing

- communicate with internal testers

- [ ] Week of 5/24 Training for staff (Ryan, Joseph, David)

- Do we need to request a license for Ryan to use for training?

- Ryan will provide actual petitions that are ready to move forward

**Comment by dianamartin** [comment]
@moorerst Here is the [help docs](https://docs.google.com/document/d/1h5kUKP3LnmotI5WypN0SUU99i9saoFC8oxlPg3v6sHI/edit?usp=sharing) - hopefully this doesn't delete on me..

**Comment by moorerst** [comment]
@dianamartin looks great hate you had to recreate it. 
Should we add Requesting the Formstack license to the Help Guide?

**Comment by dianamartin** [comment]
@moorerst Oh you're right, that might be a good place to put it too and the workflow

**Comment by moorerst** [comment]
Include John in the training session

**Comment by moorerst** [comment]
Ryan is the primary user for digital petition and he is on paternity leave. There are no further actions until he returns. We do not have a date for his return.

**Comment by moorerst** [comment]
Ryan still out on paternity leave.  No ETA. Moving issue to Backlog until we have a timeline for moving forward.

**Comment by moorerst** [comment]
Waiting response to check-in email sent to Ryan.

**Comment by dianamartin** [comment]
Ryan replied 6/11
>I have started working on this again and I am hoping to have it done by the end of next so we can get this program started again.

**Comment by moorerst** [comment]
Follow up meeting scheduled for 6/24

**Comment by moorerst** [comment]
Meeting notes:
By end of week Ryan will send the following

- updated petition language for Description and Suppose/Oppose
- list of users for testing
- list of people to be trained
Supposed Go Live date is Aug 2nd

Update petition template
Schedule/communicate user testing
Schedule training
