### ISSUE TITLE
[BUG] Knack Explorer links need updating after new builder migration

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#5933]
**Describe the bug**

https://knack-explorer.austinmobility.io/5815f29f7f7252cc2ca91c4f/views/view_124

clicking Edit in Knack Builder does not open the correct view 

**URL**

**What steps can we follow to reproduce the bug you are seeing?**

**Screenshots**

**Device**

**Browser**

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [ ] Major — can only perform work using a workaround
- [x] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Additional context**

**Comment by johnclary** [comment]
thanks for flagging this @chiaberry. i was wondering if the new builder would break that feature. if you've got the solution in mind by all means have it 🙏

**Comment by chiaberry** [comment]
I think i have it fixed, i just need to check on some other types of views to see if i got the url pattern correct. 
https://github.com/cityofaustin/knack-explorer/compare/5933-update-view-links#diff-19628026eaf2fd151089a11eb0388ce26a95448ef6cc14f168d3674ef2050a38

I will PR once I check some other links

**Comment by johnclary** [comment]
thanks @chiaberry!!
