### ISSUE TITLE
[DTS] Update Application List for Service Requests

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5934]
Most Service Requests are coming in as Other/Not Sure for application choice.  The application choice is also not available for any of the service requests except for Bug Report and Feature/Enhancement options.
![image](https://user-images.githubusercontent.com/67915167/116315722-87b99c80-a776-11eb-8d61-37662417ead2.png)

- [ ] Update Application List
- [ ] Display application field for all but New Project help options
- [ ] ~Add a Module/Feature multiple choice field that lists major modules or features for an app based on application selected~
- [ ] Update Servicebot integration as necessary

This will allow us to provide an up to date service request form and provide Service Desk primaries the ability to triage better knowing the application and module/feature the issue is about.

**Comment by johnclary** [comment]
Missing apps:
- Shared Mobility
- Parking Enterprise
- Development Services
....?

**Comment by johnclary** [comment]
@dianamartin @ChrispinP @SurbhiBakshi any other apps missing here?

@chiaberry let's look at this one together next sprint.

**Comment by johnclary** [comment]
let's also move the “what application are you using” question to sit right below “what do you need help with”. to make it more obvious that your form has been pre-filled. 

<img width="542" alt="Screen Shot 2021-04-29 at 10 25 28 AM" src="https://user-images.githubusercontent.com/14793120/116576978-ac785600-a8d5-11eb-8d4d-9de5e35c9948.png">

**Comment by dianamartin** [comment]
@amenity yes, I believe so

**Comment by johnclary** [comment]
@dianamartin would you put together an updated list with the corresponding product label?

**Comment by dianamartin** [comment]
Current Application List

| Name | GitHub Label | App List |
| -- | -- | -- |
| AMANDA | AMANDA Portal | X | 
| ArcGIS | | | 
| Data Tracker | AMD Data Tracker | X | 
| Finance & Purchasing | Finance & Purchasing | X | 
| Moped | Moped | X | 
| Vision Zero in Action | Vision Zero in Action | X | 
| Signs & Markings Operations | Signs & Markings | X | 
| Street Banners | Banners | X | 
| Vision Zero (Editor) | Vision Zero Crash Data System | X | 
| Vision Zero (Viewer) | Vision Zero Viewer | X | 
| ----- |  -----|  ----- | 
| ATD Forms | | | 
| Visitor Log | | | 
| ROW Portal | | |
| Shared Mobility Operations | | |
| Human Resources | | |
| Parking Enterprise Portal | | |
| TDS Portal | | |
| Residential Parking Permit | | |
| Data and Technology Services Portal | | |

Reviewed the GitHub Label page and filtered the keyword "Product"

**Comment by johnclary** [comment]
thanks @dianamartin. we will need a dev to update the application list dropdown while making the integration code changes at the same time. i'm going to assign to @chiaberry.

@chiaberry this is lower priority than whatever else you have on deck, but we'd like to get to it during this sprint or the next one.

**Comment by johnclary** [comment]
while we're updating the service bot, we should update the code to store the DTS portal metadata locally and side-load it into the `knackpy.App` instance, [here](https://github.com/cityofaustin/atd-service-bot/blob/50f98721156378cba364659dfbd6a3445f400e75/intake.py#L181).

This will cut down on a lot of API calls and hopefully result in fewer task failures.

**Comment by amenity** [comment]
There's a test Knack app that will create issues in Github. Ask John for guidance as needed!

**Comment by amenity** [comment]
We're getting an updated official ATD org chart from HR and may want to update our labels and Knack options to match it. Stay tuned.

**Comment by amenity** [comment]
Nevermind - no updated org chart.

**Comment by amenity** [comment]
@johnclary - ping

**Comment by johnclary** [comment]
Done. I added:
- Transportation Development Services (TDS)
- Parking Enterprise Portal
- Human Resources
- Shared Mobility Operations
- Right-of-Way (ROW) Portal
- Residential Parking Permits (RPP)
