### ISSUE TITLE
Enable COACD Login for ATD Forms

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5941]

**Comment by SurbhiBakshi** [comment]
Set up the application with all the information on the ATD side and sent the metadata to CTM, opened a service request.

**Comment by SurbhiBakshi** [comment]
John D made the change noted above. COACD sign has been enabled on this application.
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/60beae82-7fc2-44ec-9518-dfe9c3dd80e1)

**Comment by SurbhiBakshi** [comment]
I copied the Javascript and CSS from the[ Gitbook ](https://atd-dts.gitbook.io/atd-knack-operations/knack-code/custom-login-buttons) and the page showed that it was spinning and then blanked out.

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5cc0ec61-e48b-47a4-8e47-b2add4d32aca)

**Comment by SurbhiBakshi** [comment]
I copied over the Javascript and CSS from Shared Mobility and the Custom Login button was created and I was able to sign in.
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/b17d65aa-1fc7-4331-9a7c-8838d651f28e)

**Comment by SurbhiBakshi** [comment]
however the COACD login button does not show up for the Account Management login page
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/1a67d5a9-3399-46fc-83eb-d52004b5cb03)


or the Form Management login page 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/18a3a713-4965-4f4d-a9ee-8ef4af664abf)

**Comment by SurbhiBakshi** [comment]
The COACD checkbox for both pages cannot be enabled and is greyed out. 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/57a06257-d78f-4a43-bffd-225b876c8ea5)

**Comment by SurbhiBakshi** [comment]
unlike the Home Login page 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5fc9cf6e-ba52-478f-88d7-9a689479ea87)

**Comment by SurbhiBakshi** [comment]
Sent a request to Knack to look into the issue of greyed out Single Sign On checkboxes.

**Comment by SurbhiBakshi** [comment]
Even though COACD login has been enabled on the application, it is not applicable to all login pages. Waiting the hear back from Knack, so putting this issue in the Blocked lane.

**Comment by SurbhiBakshi** [comment]
Hi Surbhi,

Thank you for your patience as we got back to you here. I am seeing some SSO related fixes that are about to go through QA, but I will confirm that this issue you are experiencing with the box is greyed out is related to the known issue or not and let you know what we find. 

Will be in touch when we have an update. 

Thanks,
Jessie

**Comment by SurbhiBakshi** [comment]
Email from Knack - So I think that the greyed out box actually is due to a new feature in the new builder, where we validate the settings and will not allow them to be turned on unless everything is accurate.

I looked at https://builder.knack.com/atd/atd-forms/pages/scene_5/views/view_5/login/settings/sso/edit/COACD for example, and am seeing some incorrect property values:

​

Please check those out, and let me know if you are able to retry the configuration.

**Comment by SurbhiBakshi** [comment]
Need to look again at the configuration.

**Comment by SurbhiBakshi** [comment]
Although I was able to sign in a few days back via the COACD sign in button on the Home Page, now I get an error - 
In Firefox  - upstream connect error or disconnect/reset before headers. reset reason: connection termination![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/fbeac574-9334-41dd-8542-d12edc2fbeab)

in Chrome - https://atd.knack.com/atd-forms#home/?klem=PEM_read_bio_PUBKEY%20failed
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5f3aea89-a887-43ed-8331-9a816635bffb)

**Comment by amenity** [comment]
Handing off to @ChrispinP .

**Comment by ChrispinP** [comment]
Updated certs for ATD Forms. Updated one pass. SSO is now active and working.
