### ISSUE TITLE
Hand off VZA customizations to Chia 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5943]

**Comment by amenity** [comment]
@SurbhiBakshi — do you mind scheduling this?

**Comment by SurbhiBakshi** [comment]
Scheduled for Monday 3rd May at 3 pm.

**Comment by mddilley** [comment]
I'll put some slides together. Also, I found the Excalidraw file from back in the day and attached it so we can go through that first. ⚔️ 
[VZA.excalidraw.zip](https://github.com/cityofaustin/atd-data-tech/files/6395218/VZA.excalidraw.zip)

**Comment by SurbhiBakshi** [comment]
Notes - 
1. [Slides](https://docs.google.com/presentation/d/1yakheTcwUWhnc_wmL_aFR6CrEJRm4SwApiAhwxKRmQc/edit?usp=sharing)
2. [Recording](https://web.microsoftstream.com/video/91267365-4d6d-45a6-a226-62b2ea618dfb)
