### ISSUE TITLE
Knowledge transfer: Mike's Mapbox work 🗺️ 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#5945]
- Tuesday, May the Fourth at 11am

**Comment by amenity** [comment]
@mateoclarke will schedule

**Comment by mddilley** [comment]
Presented on 5/4

[Slides](https://docs.google.com/presentation/d/1l8PyYUynsUmHO6kYCtzsnT4oKPzWvh4Upn7QWzyvyCI/edit)
[Recording](https://web.microsoftstream.com/video/9ab02e69-c2f5-4a73-a9ef-009fabb27a70)
