### ISSUE TITLE
Project: Integrated Parking Citation Reporting

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#595]
Unlock and integrate parking citation data from the Brazos system to enable reporting and insights. This is currently accomplished haphazardly by importing/exporting spreadsheets  into SharePoint.

# How might we integrate Brazos citation reports with Knack?

## Challenge
The Parking Enforcement Division currently has a Knack application to track their reporting citations by citation type and by employee weekly. The Brazos reports are canned and can't be changed without a lot of effort. The supervisors enter this information in by hand into Knack in order to get the reporting metrics they need to have for performance measure reporting. 

## Request
If there is a way to read the Brazos report in Knack so we can pull the citation numbers with ease.

## Target users
Parking Enforcement staff

## Stakeholders
Parking Enforcement Division Managers, Supervisors
 

## What else should we know?
Brazos is owned by APD, we fall under a contract to use Brazsos. The licensing is ending or has ended. There might be an opportunity to fix this issue.

## How would you rate the impact of this issue?
- [ ] Must have — ATD operations are not legal, unsafe, or functional without it.
- [ ] Should have — This is important but not vital functionality or there is a temporary workaround. 
- [x] Could have — We want this but there are more important requests. 
- [ ] Unsure

**Comment by amenity** [comment]
@moorerst - reassigning this to you as the Parking Enterprise PM and myself as the AMD PM since this project could both divisions' products. (It would be lovely to have citations in the VZA App.)

That said, this isn't a customer request and doesn't need intake, per se. It's fine for it to lounge in the Backlog until we have pressing use cases, but good to be aware of it in the meantime. 

Correct me if I'm wrong on any of this, @johnclary ... 🚓

**Comment by amenity** [comment]
@dianamartin - do you think we should keep this open?

**Comment by dianamartin** [comment]
# 2/29/24
We are talking to Parking this morning, I can ask if this is even a thing/ask anymore.

**Comment by amenity** [comment]
@dianamartin @patrickm02L - any update on this?

**Comment by patrickm02L** [comment]
Based on how long this Issue's been open, it was labeled as could have, and that there hasn't been any movement on it, I'm going to consider it past it's shelf life. If this becomes a need in the future this Issue will be good to have for posterity. Considering this closed, for now!
