### ISSUE TITLE
Portal Help Text on Info 'CIP?'

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#5961]
### As a ROW customer applying for a permit online (AB+C Portal), I need help text on the info 'CIP?'

**Stakeholder:** Paloma

**Acceptance Criteria:**
- Applies to EX, RW-TURP
- Help Text: 

Capital Improvement Projects (CIPs) include projects such as the construction, replacement, renovation, or purchase of **City** assets.  These projects are funded by the Capital Budget (with the exception of projects funded by Austin Energy). 
 
CIPs have dedicated City of Austin Project Managers as well as a unique project identification number.  If the work is part of a CIP, it is important that both these pieces of information be provided.
 
For more information regarding CIPs visit the [City of Austin Capital Projects Explorer](https://capitalprojects.austintexas.gov/projects)

**Comment by Nadin-Nader** [comment]
@vschandramouli schedule time with Paloma

**Comment by vschandramouli** [comment]
Updated AC. Moving to Backlog.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Analysis completed, requested Nadin to provide any sample existing help field to continue with development.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan spoke to Kim about where the help text should go and she said that the verbiage can go to the left or right side of the "CIP?" question on the portal page. Or it can go above it. See image below. I think it would look better above it since there are 2 paragraphs.

![MicrosoftTeams-image (2).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/6b02eabb-6975-418f-9bf7-886a9668102c)

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/c0b705d2-621c-4eb7-9ea9-c8832a8d94c8)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder  - Got it @Nadin-Nader, So I will put it under Project Information group level help text for CIP like the above groups.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Completed Development, This can be tested only upon DEV Deployment. Submitted Deployment plan today and here is the commit ID: f9033bd19878

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan accepted commit. Sending to Devops

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed by the DevOps team to DEV. Please UAT

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on CM Team to Deploy **SCTASK0151479** to DEV

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been deployed to DEV. Please UAT and let me know how it looks.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - DEV UAT done, but EX working as expected. but not RW so, re-submitted the Commit to test again by making small update to lookup3. Here is the commit ID: bb9bf0dedb71

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I audited the recommit

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the the DevOps CM Team for deployment to DEV under **SCTASK0152830**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV UAT Completed for both EX & RW-TURP, Help text is appearing like below.

Ex: EX - 2021-103018 EX , RW-TURP - 2021-103022 RW
![image](https://user-images.githubusercontent.com/44907715/126664151-38007327-3be3-48f6-a743-69847d3484f6.png)


![image](https://user-images.githubusercontent.com/44907715/126664453-ef1fc006-2804-46d6-9b94-ecdc28c7d11a.png)

**Comment by Nadin-Nader** [comment]
Paloma approved the changes all the way to PROD if it works on TEST but she would like to see if we can get the font on the second screenshot to match all of the verbiage.

Waiting on Sree's analysis of that to see how long it will take if possible.

**Comment by Nadin-Nader** [comment]
**Status:**
Sree is still working on the Font change in the Help Text that the system is inserting.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Changes are completed and dev commit submitted today. here is the commit ID: 3046d6aeefcb

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this over to the DevOps CM Team to deploy to DEV under **SCTASK0154772**

**Status:**
Waiting on CM Team to deploy to DEV

**Comment by Nadin-Nader** [comment]
After Sree figured out how to chnage the font a new commit had to be created and sent to CTM for deployment under **SCTASK0155912** for commit ID: **d946942ab89f**

**Status: ** 
Waiting on DevOps Team to deploy to DEV

**Comment by Nadin-Nader** [comment]
After Sree figured out how to chnage the font a new commit had to be created and sent to CTM for deployment under **SCTASK0155912** for commit ID: **d946942ab89f**

**Status: ** 
Waiting on DevOps Team to deploy to DEV

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV by DevOps. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV and it looks as expected. RW-TURP Font looks same. also verified EX and looks good.

**RW-TURP **

![image](https://user-images.githubusercontent.com/44907715/127920306-67b6cca7-2510-4c87-b38b-1117b82ec584.png)

**EX **
![image](https://user-images.githubusercontent.com/44907715/127920359-e34b31dc-2394-49b4-9b16-a2e75a903115.png)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan looks good. Lets get it to TEST

## **Approved to move to TEST🙌**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this to the DevOps CM Team to deploy to TEST under **SCTASK0157529**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy to TEST under **SCTASK0157529**

**Comment by Nadin-Nader** [comment]
**Status:**
Ready for TEST UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - UAT Completed and help text appearing as expected for both EX & RW (TURP) folders. 
EX - Project Information 
![image](https://user-images.githubusercontent.com/44907715/129627932-171beb99-faed-463b-822e-e6c0b146e950.png)

RW - Project Information (TURP)
![image](https://user-images.githubusercontent.com/44907715/129627981-500cf1d5-ce2c-408d-b1b7-58e0585c70d5.png)

Expanded CIP https://capitalprojects.austintexas.gov/projects link 
![image](https://user-images.githubusercontent.com/44907715/129627798-5d7d7d9e-9372-4488-9082-798578c18d1f.png)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan 
## **Approved for PROD**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - PROD Deployment plan sent. Here is the commit id 'd946942ab89f', Please create TASK ID for me

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - PROD Deployment plan sent. Here is the commit id 'd946942ab89f', Please create TASK ID for me

**Comment by Nadin-Nader** [comment]
**Status:**
Still waiting on DevOps to deploy to PROD under **SCTASK0162517**

**Comment by Nadin-Nader** [comment]
email to Stakeholders:

> Good Morning,
> 
> Hope everyone is doing well and staying safe. I wanted to let you know that the request for Portal Hel Text on INFO "CIP?" # 5961 has been deployed to PROD. Per our meeting, I will go ahead and close the card out. If anything comes up, please feel free to email me or send me a chat message.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services
>
