### ISSUE TITLE
Project Components | Update data model to relate components and features

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#5962]
Tasks to complete the components data model.

![components (1)](https://user-images.githubusercontent.com/14793120/118374171-48fe5180-b580-11eb-8d36-c03bdf96126a.png)

**Comment by amenity** [comment]
John's [mapping ideas: locations, components, and the mapping UI ](https://docs.google.com/presentation/d/1ReEDaHTggCL5dkhnX47g0N-zPad2FiFlZd-rIHkDB1w/edit#slide=id.gd6e63e50b0_2_123)

**Comment by johnclary** [comment]
@sergiogcx—up to you how you want go about this. I have no opinions about entity or column names, the ERD (below) is just to illustrate the relationships.

- `moped_project_components`: table which stores component records. One record has one `moped_projects`, many `moped_project_features`, and one `moped_components_lookup`. This table is already partially implemented but you mentioned that you might drop it and create a new one.

- `moped_components_lookup` will be used as a lookup table for component types. This table currently exists as `moped_components`.

- `moped_project_features_components`: a join table to relate many `moped_project_features` to many `moped_project_components`. This table needs to be created.

- `moped_project_features`: existing table which holds the project geojson data. No changes needed.
-
![components (1)](https://user-images.githubusercontent.com/14793120/118374171-48fe5180-b580-11eb-8d36-c03bdf96126a.png)

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/311
