### ISSUE TITLE
Delete "csr_flex_notes" from Signs & Markings - Jun 2021

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#5966]
Received automated reminder to delete flex notes in Signs and Markings Operations PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings/records/objects/object_172

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 04/01/21

Total Records: 13742
To Delete: 4281
New Total: 9461

**Comment by ChrispinP** [comment]
complete, removed flex notes

**Comment by SurbhiBakshi** [comment]
Thanks @ChrispinP!
