### ISSUE TITLE
VZV crash info popup box disappears

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#5971]
> On the Vision Zero Viewer map when you hover over a crash a box pops up with basic crash info., but it disappears when you move your cursor. I frequently use this map to find crash IDs to find more info. in VZE, and currently I have to either write down the crash ID on a post-it note or do a screen capture. If there was a way to have this box stay up after you move your cursor then it could allow us to continue to see the crash ID (and ideally be able to copy it) and make my job a lot easier. Not super high priority but it would be nice to have.

Originally: https://github.com/cityofaustin/atd-vz-data/issues/978

**Comment by amenity** [comment]
@patrickm02L may have design ideas on this one... Visual to indicate active state would be helpful.
