### ISSUE TITLE
Create Bike Parking Reporting Hub

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5985]
Now that we have a new maintenance tracking process for bike parking, staff need to access to data and reporting metrics.

**Comment by andrewshensky** [comment]
5/11 - Initial draft of Hub including Dashboard and Web App shared with Bike Parking folks.

https://austin.maps.arcgis.com/apps/MapSeries/index.html?appid=d2579caf0f2d41fdb5fd256be3068dd3

**Comment by johnclary** [comment]
@andrewshensky please follow-up with the bike parking folks

**Comment by andrewshensky** [comment]
5/28 - Bike rack install date filter now linked to bar chart per request by bike parking folks
