### ISSUE TITLE
Simplify Traffic Signal Detection Status

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5987]
Simplify the logic that sets the detection status of a signal based on the status of its child detectors. If a single detector is `BROKEN`, the signal should have a status of `BROKEN`. Otherwise the status is `OK` unless there are zero detectors at the signal, in which case `NO DETECTION`.

![image (4)](https://user-images.githubusercontent.com/14793120/117093075-8283c100-ad25-11eb-8a39-5b1205038089.png)

**Comment by johnclary** [comment]
Done. See attached PR.

This caused 64 signals to have an OK status instead of whatever the status was before. 

<img width="630" alt="Screen Shot 2021-05-04 at 10 02 48 PM" src="https://user-images.githubusercontent.com/14793120/117093063-7b5cb300-ad25-11eb-9b9d-047019ec76d0.png">

**Comment by dianamartin** [comment]
@johnclary That report widget seems correct now, there shouldn't been anymore `UNKNOWN` statuses. I'll check it this morning and confirm this. 

I'll also confirm that AMD wants to drop the `UNKNOWN` status from the signal (parent) `Detector Status`

**Comment by amenity** [comment]
@dianamartin - please follow up with Brian V to see if this can be closed.

**Comment by dianamartin** [comment]
Messaged him on teams
>Hey Brian, I wanted to check in to see if the "Signal Detector Status Count by Intersection" Report works for you now? I have an issue that John did back in May that said he updated.
 
>He said _"This caused 64 signals to have an "OK" status instead of whatever the status was before, "UNKNOWN"_ (included the image that john has on this issue)

**Comment by dianamartin** [comment]
Reminder: Anything that is "Unknown" is now "OK". John updated the script.

**Comment by amenity** [comment]
https://github.com/cityofaustin/atd-data-publishing/pull/294/commits/2f18538a2f3f9520a54103db064eef5fd359a187
