### ISSUE TITLE
Follow-up: Dispatch Tracking - Scheduled delete of Resource Tracking Logs, check-in on records and performance

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#5991]

**Comment by moorerst** [comment]
issue #5776 for reference

**Comment by moorerst** [comment]
schedule meeting for 7/1 

- agenda:
check in 
resource tracking logs
311 SR integration update

**Comment by moorerst** [comment]
Discussed setting up a schedule to delete the older records in the resource tracking log. Currently we are marking records for deletion after a week but there is no job scheduled to delete the marked records. Need feedback from the leadership on how long to keep records, they were not all in the meeting. It was suggested that I email them for feedback.

**Comment by moorerst** [comment]
sent email to leadership for feedback on deletion schedule

**Comment by moorerst** [comment]
@dianamartin the team has decided on a one month schedule for deleting records from the resource tracking log.

email response from team: We’ve discussed and have all agreed the Daily logging of the officers can be deleted after a month, to eliminate the system holding of older generated records. Let us know if you have any further questions.

**Comment by dianamartin** [comment]
- [x] I updated the task action for `dispatch_resource_tracking` - from previous 1 "week" to previous 1 "month"
