### ISSUE TITLE
Migrate ROW SSO Login to Migration Copy of App

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#5993]

**Comment by johnclary** [comment]
Migrate row from [this prototype](https://builder.knack.com/atd/row) to the [Migration Copy](https://builder.knack.com/atd/right-of-way-portal-johns-migration-copy).

- Swap URLs
- Copy certificate/SAML config info

**Comment by ChrispinP** [comment]
created support ticket INC0099531 and sent email to John & Michael to get updated metadata and cert information. Updated SAML info and urls but test was unsuccessful.

pending response

**Comment by ChrispinP** [comment]
SSO is now setup and working for ROW: https://atd.knack.com/row

![image](https://user-images.githubusercontent.com/67915167/118307618-8dbab780-b4b0-11eb-9b4e-de739fe89355.png)

When providing CTM the metadata file, they need to update their Azure Instance with the new ACS Reply URL which now includes US in it for the New Builder.

**Comment by ChrispinP** [comment]
Knack was able to fix SSO issues. SSO is now enabled and tested to be successfully working.

complete
