### ISSUE TITLE
Install Metabase (Business Intelligence) sandbox 

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#60]
on Heroku or AWS?

https://metabase.com/

**Comment by mateoclarke** [comment]
Took 3 tries but I was able to get an Elastic Beanstalk instance running in AWS with Metabase installed:
http://atd-metabase-test1.us-east-1.elasticbeanstalk.com/

Now looking into how to connect to our datastore. Looks like Postgres a default option:
<img width="744" alt="Screen Shot 2019-04-29 at 3 49 01 PM" src="https://user-images.githubusercontent.com/5697474/56926323-267f6580-6a97-11e9-9104-f6561048d31c.png">

**Comment by mateoclarke** [comment]
First I looked in 1Password. Then, I poked around in our AWS RDS account and wasn't sure which DBs might be our Postgres DB instances. Lots of the names are auto-generated. I'm going to wait til @johnclary is back and get port connection details.

docs: https://metabase.com/docs/v0.12.0/administration-guide/01-managing-databases.html

**Comment by mateoclarke** [comment]
@JoeyL6 gave me a heads up that the RDS instance we'd probably want to connect is `atd-rodeo-prod`. I think in order to this, I need to set up Metabase on the same VPC or establish an SSH tunnel.

https://metabase.com/docs/latest/administration-guide/01-managing-databases.html#rds-databases

**Comment by sergiogcx** [comment]
It took me all of last Friday to learn about it, I was able to spin up a metabase cluster in AWS Fargate, it is currently connected to the atd-vz-data instance, but we should be able to connect to any other.

You should have been given access to this by now, if not reach out to me and I can give you access.

**Comment by sergiogcx** [comment]
Ah, yes the url is:
https://atd-metabase.austintexas.io

Maybe the next steps are to set up the email settings through AWS Simple Email Service, so that way we can reset passwords if needed.

**Comment by sergiogcx** [comment]
Tested, it runs well and scales well.
