### ISSUE TITLE
Signal Timing Dashboard: Show Green Text if Travel Time Savings is Positive

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#600]
Jim requested that the signal timing dashboard display green indicator text if the total travel time savings is positive, and red if it's negative. Currently, the dash uses red text if the travel time savings is lower than the annual goal.

![Screenshot.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/b8b71fa6-0d1d-49b7-9e6c-4644ac9f892e)

**Comment by johnclary** [comment]
@mateoclarke probably a good for Tyler.

**Comment by tcwcodes** [comment]
Issue moved to [cityofaustin/transportation.austintexas.io #325](https://github.com/cityofaustin/transportation.austintexas.io/issues/325) via [**ZenHub**](https://www.zenhub.com/)
