### ISSUE TITLE
Contact CTM about Nearmap restrictions for Netlify deploy previews

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#6008]
The URL provided to CTM for the restrictions on the Moped Nearmap API token does not behave like the restricted urls for Mapbox basemap tiles. I suspect that a wildcard needs to be added to account for the changes in the deploy preview URLs. We also need to consider the new test instance (GH workflow dispatch with the Heroku Hasura cluster).

The URLs provided to CTM were (the same ones set in the Mapbox dashboard for the Moped token):

https://mobility.austin.gov/
https://moped.austinmobility.io/
https://netlify.app/
https://localhost:3000/
http://localhost:3000/
http://bs-local.com:3000/

#### Error in UI
![Screen Shot 2021-05-06 at 12 31 16 PM](https://user-images.githubusercontent.com/37249039/117340888-0d200980-ae67-11eb-919b-c94347dbe794.png)

#### 401
![Screen Shot 2021-05-06 at 12 31 42 PM](https://user-images.githubusercontent.com/37249039/117340895-0ee9cd00-ae67-11eb-8969-88ffbafd613e.png)

#### Response
![Screen Shot 2021-05-06 at 12 31 51 PM](https://user-images.githubusercontent.com/37249039/117340899-10b39080-ae67-11eb-825b-2e7c27ddb776.png)

**Comment by amenity** [comment]
I don't notice these anymore... did something change, @johnclary ? Or can this be iceboxed?

**Comment by johnclary** [comment]
i defer to you and other devs if this is still a prob. iirc we don't have imagery previews in local or stage, but no nasty error message either

**Comment by johnclary** [comment]
@patrickm02L I tagged this with Vision Zero as well — we should probably sort out both Moped and Vision Zero's Nearmap token issues with CTM at the same time.

**Comment by patrickm02L** [comment]
@mddilley Was this updated with #9890?

**Comment by mddilley** [comment]
@patrickm02L I'm putting this on my list to check out tomorrow (10/3). I see NearMap tiles coming into my local Moped instance which is good but has me scratching head about how that is working. I can't remember if we see the same thing locally with VZ or not.

**Comment by mddilley** [comment]
@patrickm02L I gave VZE local a spin, and I see that we have the same behavior. I'm not getting tiles from NearMap, but it falls back to the Mapbox satellite tiles which I think is more than enough for local dev. 👍

**Comment by patrickm02L** [comment]
@mddilley agreed the fall back to Mapbox is good for local. If we ever want to get fancy we can implement Nearmap.
