### ISSUE TITLE
Data request: Micromobility summary of miles per trip 

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#601]
**Deadline: Friday, September 27**

From email:

> Could you please ask one of your team to provide us a summary of miles per trip?  This would be a total of all trips taken since February of 2018.  Below are a few more details.
> 
> - Percentage of trips 0-1 miles
> - Percentage of trips 1-2 miles
> - Percentage of trips 2-3 miles
> 
> Please let me know if this is possible.

We should be able to do this from the open dataset:
https://data.austintexas.gov/Transportation-and-Mobility/Shared-Micromobility-Vehicle-Trips/7d8e-dm7r

~Asking for clarification if this should include only `vehicle_type == "scooter"` or `bicycle` as well.~ All modes.

**Comment by mateoclarke** [comment]
Article that inspired this report:
https://www.smartcitiesdive.com/news/micromobility-could-replace-48-of-car-trips-in-10-us-cities/562489/ @sergiogcx

**Comment by sergiogcx** [comment]
@mateoclarke 

These are my findings:

| Category  | Count | Pctg % |
|------|---|----|
|0-1 | 432689700 | 62%|
|1-2 | 141150700 | 20%|
|2-3 | 43560000 | 6%|
|MORE | 83516100 | 12%|
|TOTAL | 7009165 | 100%|

I downloaded the entire dataset from the link above (`https://www.smartcitiesdive.com/news/micromobility-could-replace-48-of-car-trips-in-10-us-cities/562489/`), put in in a SQL instance and ran this query:

```
SELECT  (CASE 
    WHEN (trip_distance > 0 AND trip_distance <= 1610) THEN '0-1'
    WHEN (trip_distance > 1610 AND trip_distance <= 3219) THEN '1-2'
    WHEN (trip_distance > 3219 AND trip_distance <= 4829) THEN '2-3'
    ELSE 'MORE'
    END
) AS category,
COUNT(1) as trips
FROM shared_micromobility_vehicle_trips
GROUP BY category
```

1610 is equivalent to 1 mile in meters, 3219 is two miles, and 4829 is three miles.

Let me know if this is what you are looking for :)

**Comment by sergiogcx** [comment]
I will also lave the data in the RDS instance in case we need to run more queries.

**Comment by mateoclarke** [comment]
This looks solid, but I think for consistency, we should've also filtered out messy trip data. This is what we've used in the past. Sorry for forgetting to tell you about this.

> Note that our official trip reporting metrics only include trips which meet the following criteria:
> - trip distance greater than or equal to .1 miles and less than 500 miles
> - trip duration less than 24 hours

@sergiogcx

**Comment by mateoclarke** [comment]
Updated with those new filters

| Category  | Count | Pct % |
|------|---|----|
|0-1 miles | 3,894,099 | 64.10%|
|1-2 | 1,429,512 | 23.53%|
|2-3 | 440,759 | 7.26%|
|>3 | 310,613 | 5.11%|
|TOTAL | 6,074,983 | 100%|

Updated query:
```SQL
SELECT
	(
		CASE WHEN (trip_distance > 0
			AND trip_distance <= 1610) THEN
			'0-1'
		WHEN (trip_distance > 1610
			AND trip_distance <= 3219) THEN
			'1-2'
		WHEN (trip_distance > 3219
			AND trip_distance <= 4829) THEN
			'2-3'
		ELSE
			'MORE'
		END) AS category,
	COUNT(1) AS trips
FROM
	api.dockless
WHERE
	trip_duration < 86400
	AND trip_distance > 161
	AND trip_distance < 804672
GROUP BY
	category
```

**Comment by mateoclarke** [comment]
email has been sent to KT

**Comment by mateoclarke** [comment]
Updated report has been requested.

- Control date range for YTD
- break down by mode

**Comment by mateoclarke** [comment]
### Micromobilty Trip Distance by Mode

Category | Total Count | Pct % | Scooter Count | Scooter Pct % | Bike Count | Bike Pct %
-- | -- | -- | -- | -- | -- | --
0-1 miles | 3,419,646 | 64.28% | 3,298,070 | 65.78% | 121,576 | 39.72%
1-2 | 1,251,068 | 23.52% | 337,039 | 6.72% | 45,503 | 14.87%
2-3 | 382,542 | 7.19% | 224,295 | 4.47% | 42,186 | 13.78%
3+ | 266,481 | 5.01% | 1,154,283 | 23.02% | 96,785 | 31.62%
Total | 5,319,737 | 100.00% | 5,013,687 | 100.00% | 306,050 | 100.00%

**Date range: 2018-09-24 to 2019-09-24**

_NOTE: We use the following criteria to filter out bad data in most of our micro-mobility reporting._ 
Data in this report includes:
- trips with distance greater than or equal to .1 miles and less than 500 miles
- trips with duration less than 24 hours
