### ISSUE TITLE
TIA Bug: Lead Reviewer Missing

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6011]
The lead reviewer did not populate on [this case.](https://atd.knack.com/development-services#tia-requests/tia-request-details/609442654f5995001c9bcc13/)

**Comment by ChrispinP** [comment]
Rule that sets the Lead Reviewer is on the application to allow for inline editing. Application must be completed so that the Lead Reviewer and Case Reviewers are correctly set.
