### ISSUE TITLE
TIA: Default Submission Cycle #

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6012]
When a scope or submission is manually created by staff, default the cycle # to prevent user input error.

**Comment by ChrispinP** [comment]
When inserting a new scope submission or submission from the Case Management page (Reviewer). The Cycle # is now automatically set.
![image](https://user-images.githubusercontent.com/67915167/118049174-f97f1200-b342-11eb-93f6-6ad0d515a5c0.png)

Ready to review

**Comment by TracyLinder** [comment]
Looks great. Closing.
