### ISSUE TITLE
OSE Folder Process Cleanup; Initial and Event Review Process (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#6030]
## As an OSE reviewer, I need the folder processes updated to add more value and efficiency to our AMANDA usage. I would like to have the Processes, their attempt results and what those processes and attempts do to the folder reviewed to better fit our workflow.

**Stakeholder:** Maria A.
**DTS Manager:** Nate

**Acceptance Criteria:**
**This will apply to the RW SubType: Street Event (50510)**

- Customer applies online/submits
- System inserts process 7000 Web Acceptance (Same; no changes)
- Upon saving 'Accepted' attempt on Web Acceptance the system will:
  -  Update the folder status to ‘Pending’
  -  Insert processes Event Review (50560) and Event Billed (new)
- Event Review (50560) should **not** add any fees when inserted
- If it is from Backoffice submission, only Event Review (50560) process must be added
- **Remove** the "Event Intake" Process (50555)
- **Remove** the "Activity Log" Process (80115)

- **(50560) ‘Event Review’** - Attempts: Approved, Awaiting Update, Expired, Rejected, Send Notification Letter, Withdrawn, Cancelled (new)
    -  Is assigned to ‘**_ACE ATD Reviewer_**’ group
    -  ‘Cancelled’ (new) will close the ‘Event Review’ process, update the process status to **_‘Closed’_**, and updates the folder status to **_‘Cancelled’_**
    -  ‘Approved’ changes the folder status to **_‘Pending’_** and closes the process. **_Inserts_** ‘Event Billed’ (only for backoffice submission) and ‘Event Permitting’ processes
    -  ‘Awaiting Update’ = **_Please remove_** (Only for Subtype Street Event)
    -  ‘Expired’ = **_Please remove_** (Only for Subtype Street Event)
    -  ‘Rejected’ changes the folder status to **_‘Rejected’_** and closes the process. **Requires a comment.**
    -  ‘Send Notification Letter’ = **_Please remove_** (Only for Subtype Street Event)
    -  ‘Withdrawn’ changes the folder status to **_‘Withdrawn’_** and closes the process. **Requires a comment.**
    -  ‘Cancelled’ changes folder status to **_'Cancelled'_** and closes the process. **Requires a comment.**
-  The Process Date fields should work in the following way:
    -  In Date = The date the process was inserted
    -  Start Date = The date the process was closed
    -  End Date = The date of the start date of the event

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Need clarification - Amanda back office Street Event folder creation. when the folder is created it is inserting Event Review Process, Activity Log and Traffic Control Inspection processes are getting inserted. above AC we are making changes to Online submitted applications only right? If I need to make same changes on Event intake process approved attempt please do let me know.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Development Completed.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder -  DEV DP submitted for Config and Procedural commits. Please approve and create task id for the below commit no’s.

Commit ID
1.	[b1c225dce3bb](http://coaamandadevops01.austintexas.gov/R3:b1c225dce3bb1d0304f242f384ac7201d95636d2) – Config Commit
2.	[5a290ad50351](http://coaamandadevops01.austintexas.gov/R3:5a290ad5035143d36dd5282e91083230608c8a90) – Procedural Commit

**Comment by Nadin-Nader** [comment]
**Status:**
This has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0203275**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV Please UAT when you have a moment.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in Back Office DEV,  but not able to test in DEV Portal. If anyone has access please do let me know to continue testing.

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team for deployment to **_TEST_** under **SCTASK0206074**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to TEST. Please UAT and let me know fi it is ready for Stakeholder UAT.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan spoke to Maria and she will have the UAT done for this sometime tomorrow

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan here is Maria's response to her UAT on TEST:

> HI! Here are some initial UAT findings (Row ID 12866769):
> 
> when the Event Review is approved,
> the process status is also 'Approved' and should be 'Closed'
> the folder status is 'Pending Permit' and should be 'Pending'
> It is still seeing the items below as attempts. If they can't be removed, no big deal, I just wanted to note they are still there.
> ‘Awaiting Update’ = Please remove (Only for Subtype Street Event)
> ‘Expired’ = Please remove (Only for Subtype Street Event)
> ‘Send Notification Letter’ = Please remove (Only for Subtype Street Event)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder -  #6030 DEV DP submitted. This order 2 commit is to fix the Folder status from Pending Permit to Pending when Subcode – Street event for RW folders.

Kindly approve and create task id for me. Commit ID: [cb3c789415cd](http://coaamandadevops01.austintexas.gov/R3:cb3c789415cdb8800786354b8e5a6cbd570a674b)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - TEST DP submitted. Please create task id for me.

#2666 EPIC Commit ID’s
-------------------------------

**1.	#6030 Commit ID’s**
a.	Order 1 - b1c225dce3bb & 5a290ad50351 – Already in TEST
b.	Order 2 - [cb3c789415cd](http://coaamandadevops01.austintexas.gov/R3:cb3c789415cdb8800786354b8e5a6cbd570a674b)

**2.	#6031 Commit ID’s** 
a.	Order 1 - d896d8858596
b.	Order 2 - ad554c8c117d
c.	Order 3 - 6f7ee477b54a
d.	Order 4 - 6eef99981bf5

**3.	#6032 Commit ID’s** 
a.	Order 1 - 355395df49a2

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0211462**

**Comment by Nadin-Nader** [comment]
Still waiting on CTM

**Comment by Nadin-Nader** [comment]
This has been deployed to TEST

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST Environment; all working as expected and ready for UAT.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per Maria’s approval, PROD DP’s of Epic #2666 (Cards #6030, #6031 & #6032) submitted. Kindly approve and create task id for same.

**Please find the order below to promote to PROD -** 

1. #6030 Commit ID’s
a. Order 1 - b1c225dce3bb & 5a290ad50351 
b. Order 2 - cb3c789415cd

2. #6031 Commit ID’s
a. Order 1 - d896d8858596
b. Order 2 - ad554c8c117d
c. Order 3 - 6f7ee477b54a
d. Order 4 - 6eef99981bf5
e. Order 5 - 2792c4969685

3. #6032 Commit ID’s
a. Order 1 - 355395df49a2

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps cm Team to be deployed to **_PROD_** under **SCTASK0215849**

**Comment by Nadin-Nader** [comment]
This has been deployed to PROD and Maria has been informed. Closing
