### ISSUE TITLE
OSE Folder Process Cleanup; Event Billed Process (New) (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#6031]
## As an OSE reviewer, I need the folder processes updated to add more value and efficiency to our AMANDA usage. I would like to have the Processes, their attempt results and what those processes and attempts do to the folder reviewed to better fit our workflow.

**Stakeholder:** Maria A.
**DTS Manager:** Nate

**Acceptance Criteria:**
**This will apply to the RW SubType: Street Event (50510)**
- **‘Event Billed’ (New)** is inserted in a **_‘Pending’_** status - Attempts: Billed, Reminder, Cancelled, Paid, Waived
    -  The ‘assigned to’ should be the assigned user
    -  ‘Billed’ will send the customer an email with bill information
        -  Email goes to folder applicant’s Internet User, parent record’s email address
        -  Keeps folder in **_‘Pending’_** status
        - The email verbiage sent to the applicant should be:
          - From Email: 
               - (assigned user, aka whoever created the attempt)
          - To Email: 
               - (applicant email)
          - Subject Line:
              - ACE App. Update: Austin Transportation Special Events Fees Invoiced for [FOLDERNAME]
          - Message Intro:
              - Hello,  
          -  Project Details (Message):
             -  Street Event fees for event [FOLDERNAME] have been billed.  
             -  You can pay online by Check or Credit Card by visiting https://abc.austintexas.gov. Go to 'My Bills' to view and pay your pending invoices.   
             -  Please reach out if you have any additional questions. 
             - Austin Transportation 
             - Austin Center for Events

- ‘Reminder’ will send the customer an email with bill information
    -  Email goes to folder applicant's Internet User, parent record's email address
    -  Keeps folder in **_‘Pending’_** status
    -  The email verbiage sent to the applicant should be:
          - From Email: 
               - (assigned user, aka whoever created the attempt)
          - To Email: 
               - (applicant email)
          - Subject Line:
              - ACE App. Update: Austin Transportation Special Events Fees Invoiced for [FOLDERNAME]
          - Message Intro:
              - Hello,  
          -  Project Details (Message):
             -  ** Street Event fees for event [FOLDERNAME] have already been billed. ** 
             -  You can pay online by Check or Credit Card by visiting https://abc.austintexas.gov. Go to 'My Bills' to view and pay your pending invoices.   
             -  Please reach out if you have any additional questions. 
             - Austin Transportation 
             - Austin Center for Events
-  ‘Cancelled’ will **_close_** the process ("Event Billed") and update the folder status to **_‘Cancelled’_**
-  ‘Waived’ will: **_close_** the process ("Event Billed") and update the folder status to **_‘Pending’_
-  ‘Paid’ will **close** the process ("Event Billed") update folder status to **_'Pending'_
-  The Process Date fields should work in the following way:
    -  In Date = The date the process was inserted
    -  Start Date = The date the process was closed
    -  End Date = The date of the start date of the event

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder  - Development is in Progress.

**Comment by TracyLinder** [comment]
### Status Update

I moved all work for epic #2666 from On Deck to the Backlog until our higher priority issues are complete (ROW Cost of Service reports, FY 22 fee scoping.)

**Comment by TracyLinder** [comment]
AC has been updated

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Few Clarifications required. 

Event Billed process will get inserted along with Event Permitting in Event Review process when approved attempt is given. But here in Event Billed again why should we insert Event Permitting on Waived/Paid attempt?

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i asked Maria. We are just waiting on a response

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan here is Maria's response:

> [4:03 PM] Alonso, Maria
> Hey Nate! Hmmm maybe it was a typo? I don't see why we would need to readd the Event Permitting process again. You can update it to remove that please.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted DEV DP, however not able to test BILLED n REMINDER attempts in localhost as it triggers email. Upon DEV Promotion this can be tested. Please approve and create task id for me. 
Commit ID: [d896d8858596](http://coaamandadevops01.austintexas.gov/R3:d896d8858596d837ce2f50f25d9be85c770e5750)

**Comment by Nadin-Nader** [comment]
Thus has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0205982**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader, @TracyLinder  - DEV Testing is in progress; Emails are not working. trying to debug the same.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP for https://github.com/cityofaustin/atd-data-tech/issues/6031 submitted. Kindly approve and create task id for me. This will resolve the email triggering

Here is the Commit ID: [8d0a1d656fb6](http://coaamandadevops01.austintexas.gov/R3:8d0a1d656fb65fc97b72e93af9663e099a011b1a)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been Sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0208471**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to **DEV** Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Earlier commit was not moved appropriately, so submitted DEV DP. Kindly approve and create task id for me.

Commit ID: [ad554c8c117d](http://coaamandadevops01.austintexas.gov/R3:ad554c8c117d73d1b93feaea78c22f24e9fc81e8)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP of #6031 – 3 submitted. Kindly approve and create task id for me.
This commit is to fix the issue On Paid and Waived attempt 50562 process is not closing. 

Commit ID: [6f7ee477b54a](http://coaamandadevops01.austintexas.gov/R3:6f7ee477b54a32e2b9f92e816b3afc75b56c996d)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this over to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0209833** in order to revert commits from **ad554c8c117d**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan looks like SCTASK0209833 already got deployed to DEV

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this over to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0209840**

**Comment by Nadin-Nader** [comment]
This has been deployed to DEV, Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted DEV DP of #6031. Kindly approve and create task id for me. This will fix the html email issue.

**Comment by Nadin-Nader** [comment]
This has been Sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0211035**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - TEST DP submitted. Please create task id for me.

https://github.com/cityofaustin/atd-data-tech/issues/2666 EPIC Commit ID’s
1. https://github.com/cityofaustin/atd-data-tech/issues/6030 Commit ID’s
a. Order 1 - b1c225dce3bb & 5a290ad50351 – Already in TEST
b. Order 2 - [cb3c789415cd](http://coaamandadevops01.austintexas.gov/R3:cb3c789415cdb8800786354b8e5a6cbd570a674b)

2. https://github.com/cityofaustin/atd-data-tech/issues/6031 Commit ID’s
a. Order 1 - d896d8858596
b. Order 2 - ad554c8c117d
c. Order 3 - 6f7ee477b54a
d. Order 4 - 6eef99981bf5

3. https://github.com/cityofaustin/atd-data-tech/issues/6032 Commit ID’s
a. Order 1 - 355395df49a2

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0211462**

**Comment by Nadin-Nader** [comment]
Still waiting on CTM

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to TEST. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - #6031 DEV DP submitted. Kindly approve and create task id for me. This commit will remove the semicolon from the to-email address as it is throwing an error in TEST.

Commit ID: [2792c4969685](http://coaamandadevops01.austintexas.gov/R3:2792c49696851f9a9af797bbaf3a5e188cc4a4a5)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0213541**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV, please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV and working as expected. here is the email received to customer email id (my austin dev id). I will be submitting the TEST DP by today.

![image](https://user-images.githubusercontent.com/44907715/164752543-47d5af32-bcab-4617-a992-ce4c5ba4a5d2.png)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - TEST DP submitted. Kindly approve and create task id for me.

Commit ID: 2792c4969685

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have requested that the new changes be moved to **_TEST_** under **SCTASK0213800**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST Environment; all working as expected and ready for UAT.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per Maria’s approval, PROD DP’submitted. Kindly approve and create task id for same.

**Please find the order below to promote to PROD -** 

1. #6030 Commit ID’s
a. Order 1 - b1c225dce3bb & 5a290ad50351 
b. Order 2 - cb3c789415cd

2. #6031 Commit ID’s
a. Order 1 - d896d8858596
b. Order 2 - ad554c8c117d
c. Order 3 - 6f7ee477b54a
d. Order 4 - 6eef99981bf5
e. Order 5 - 2792c4969685

3. #6032 Commit ID’s
a. Order 1 - 355395df49a2

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps cm Team to be deployed to **_PROD_** under **SCTASK0215849**
