### ISSUE TITLE
OSE Folder Process Cleanup; "Event Permitting" Process (Deploying to PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#6032]
## As an OSE reviewer, I need the folder processes updated to add more value and efficiency to our AMANDA usage. I would like to have the Processes, their attempt results and what those processes and attempts do to the folder reviewed to better fit our workflow.

**Stakeholder:** Maria A.
**DTS Manager:** Nate

**Acceptance Criteria:**
**This will apply to the RW SubType: Street Event (50510)**

-  **  (50565) ‘Event Permitting**’– Attempts: Approved, Rejected, Cancelled, Withdrawn
    -  This process **is mandatory for permit issuance** (process must be closed before permit issues)
    -  Folder status should stay as **_“Pending”_** until an attempt is entered
    -  The ‘assigned to’ should be the assigned user
    -  Attempts:
        -  'Approved' will: **close** the Process and update the folder status to **_'Pending Permit'_**
        -  'Rejected' will: **close** the Process and update the folder status to **_'Rejected'_**
        -  'Cancelled' will: **close** the Process and update the folder status to **_'Cancelled'_**
        -  'Withdrawn' will: **close** the Process and update the folder status to **_'Withdrawn'_**
    -  **Remove** **_‘Customer Contacted’_** attempt
-  The Process Date fields should work in the following way:
    -  In Date = The date the process was inserted
    -  Start Date = The date the process was closed
    -  End Date = The date of the start date of the event

**Comment by TracyLinder** [comment]
AC has been updated

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis and Development is in Progress.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - DEV DP for #6031. Kindly approve and create task id for me. This will resolve the email triggering

Here is the Commit ID: [8d0a1d656fb6](http://coaamandadevops01.austintexas.gov/R3:8d0a1d656fb65fc97b72e93af9663e099a011b1a)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted #6032 DEV DP. Kindly approve and create task id for me. 

Here is the commit id: [355395df49a2](http://coaamandadevops01.austintexas.gov/R3:355395df49a26c0d828019634c77040340e49dd3)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  I have sent this over to the DevOps CM Team to be deployed **_DEV_** under **SCTASK0208477**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to **DEV** Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - TEST DP submitted. Please create task id for me.

https://github.com/cityofaustin/atd-data-tech/issues/2666 EPIC Commit ID’s
1. https://github.com/cityofaustin/atd-data-tech/issues/6030 Commit ID’s
a. Order 1 - b1c225dce3bb & 5a290ad50351 – Already in TEST
b. Order 2 - [cb3c789415cd](http://coaamandadevops01.austintexas.gov/R3:cb3c789415cdb8800786354b8e5a6cbd570a674b)

2. https://github.com/cityofaustin/atd-data-tech/issues/6031 Commit ID’s
a. Order 1 - d896d8858596
b. Order 2 - ad554c8c117d
c. Order 3 - 6f7ee477b54a
d. Order 4 - 6eef99981bf5

3. https://github.com/cityofaustin/atd-data-tech/issues/6032 Commit ID’s
a. Order 1 - 355395df49a2

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0211462**

**Comment by Nadin-Nader** [comment]
Still waiting on CTM

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been deployed to TEST please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Testing is in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST Environment; all working as expected and ready for UAT.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Rejected Attempt should require Attempt comments. This will be done once v7 goes live

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per Maria’s approval, PROD DP’s of Epic #2666 (Cards #6030, #6031 & #6032) submitted. Kindly approve and create task id for same.

**Please find the order below to promote to PROD -** 

1. #6030 Commit ID’s
a. Order 1 - b1c225dce3bb & 5a290ad50351 
b. Order 2 - cb3c789415cd

2. #6031 Commit ID’s
a. Order 1 - d896d8858596
b. Order 2 - ad554c8c117d
c. Order 3 - 6f7ee477b54a
d. Order 4 - 6eef99981bf5
e. Order 5 - 2792c4969685

3. #6032 Commit ID’s
a. Order 1 - 355395df49a2

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps cm Team to be deployed to **_PROD_** under **SCTASK0215849**

**Comment by Nadin-Nader** [comment]
This has been deployed to PROD and Maria has been informed. Closing
