### ISSUE TITLE
Learn about PNTS Process / moving to Pro?

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#6043]
Dylan provided the below videos, will start there. Maria in OSE also offered to chat about PNTS if I would like.

PNTS Pull:
https://cityofaustin.sharepoint.com/:v:/t/ActiveTransportationandStreetDesign/EcGMjviFkLdEvoi2DeDxuIgBgK8FNygnfx8lIN2jvSl3WQ?e=HtNvNZ

Getting email address for the Community Registry using the Neighborhood Association IDs from the PNTs system:
https://cityofaustin.sharepoint.com/:v:/t/ActiveTransportationandStreetDesign/EZBrfAWXzaNFsAe0q3KKB8MBjCBg147m88mH4hP7HKOLbg?e=3m6UBQ

**Comment by jaime-mckeown** [comment]
Need to find out if it will be moving to Pro or will be online only moving forward.

**Comment by johnclary** [comment]
@andrewshensky please add your notes and make a new issue for creating a webapp for creating a shapefile to upload to the PNTS GeoForm.

**Comment by johnclary** [comment]
We also need to find out who maintains PNTS and the process for requesting help. The documentation is old.

**Comment by andrewshensky** [comment]
### Responses from Dylan

1.	**Other than creating the shapefile, is ArcMap required for any other processing?** No, the other steps in the process are outside of GIS.
2.	**Is it a requirement to use the MXD and datasets you are using in the video for tracking purposes, or is that just a recommendation for users using PNTS and the shapefile could be created elsewhere?** 
•	The datasets are needed for pulling the PNTS correctly. You’ll see in the video that you have to draw the shapefile around boundaries and the address points. 
•	The MXD could migrate over to an ArcPro project if everyone in our work group is migrating over to ArcPro. I would just need to re-shoot the video for training purposes. 
•	The PNTS Geoloader requires a zipped shapefile (see highlighted text below), so as long as ArcPro still allows for data export in the form of shapefiles, I think we should be good. The shape can be drawn in the map in the PNTS Geoloader, but it does not allow you to save the shape for future use (for projects with multiple follow-up mailings for notifications) and recordkeeping of where we have mailed notifications. 
3.	**We are currently working on a project migrating users from ArcMap to ArcPro and/or ArcGIS Online, do you foresee any issues moving the PNTS process from ArcMap to ArcPro or ArcGIS Online?** I do not at this time.

**Comment by andrewshensky** [comment]
### Notes from communication with Jacquie

1. Outside of creating the initial shapefile, PNTS is made up of two separate applications. Both are maintained by a developer in the Geospatial Data Development (GDS) group.
2. Requests for accounts and issues should be submitted through a service now ticket and asked to be assigned to "GIS_DATA_DEVELOPMENT”.

**Comment by johnclary** [comment]
@andrewshensky check-in with Maria A. in Office of Special Events to let her know you're building and this and see if she has a similar need.

**Comment by andrewshensky** [comment]
Email was sent out to Maria regarding PNTS transition from ArcMap to AGOL. Awaiting response regarding any feedback.

**Comment by jaime-mckeown** [comment]
Maria told me that she doesn't need to save her GIS layers for notifications as they keep the list for reference.

**Comment by andrewshensky** [comment]
Sounds good. I let her know that if there are any other enhancements she can think of that may help their process to let me know.  

I still think adding a field to track which division is creating a polygon may be good so it doesn't create noise for other groups using that to track. Also it will give us some insight on who is actually using it.

**Comment by jaime-mckeown** [comment]
Yes, I believe that TED is also starting to use PNTS as well, so that will be useful.
