### ISSUE TITLE
Meeting: Dispatch Tracking Sprint Review

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6046]
Scheduled 5/13/21
Agenda:
Review new features added:
- Viewer Role
- Attachment Delete button

Review Reports

**Comment by dianamartin** [comment]
Dispatch Reports is broken after I edited it :( I'm trying to rebuild it but having issues. I'll keep working on it.

**Comment by dianamartin** [comment]
I fixed those Dispatcher Reports, not organized side by side by works

**Comment by dianamartin** [comment]
# Reports
1. **Call Log Reports**  - Daily Call Count (Current Week) - BAR CHART
Doesn't expand
2. **Calls by Status** (Current Month) - PIVOT TABLE
Doesn't expand
3. **By Source** (Current Month) - PIE CHART
4.

**Comment by moorerst** [comment]
5/13/21 sent sprint review status email to stakeholders.
Status included:

- Features added since GO Live
  Viewer Role
  Attachment Delete button

- Next Steps
Review reports - provided a spreadsheet of reports to review and provide feedback
Meeting with 311 staff to discuss 311 integration
