### ISSUE TITLE
Alley GIS Meeting with ROW and AW

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#6047]
Meeting with Ryan from ROW and AW to discuss the possibility of creating and Alleys GIS layer on 5/19.

**Comment by jaime-mckeown** [comment]
- Alleys have ROW, utilities installed, etc. but there is no Alleys GIS layer
- For work they need to use the nearest street segment
- Vacations for Alleys happen so you don't know if it's vacated or not
- AW scopes the waste water products, non-transmission mains, etc.
- For planning purposes, AW needs to know where Alleys are located.
- CIP Planning for future planning would be helpful
- Talked about Road Class in the street segment layer and is it kept updated or is it static as they rely on the information
- We don't see a lot of mobility through alleys, but there are a lot of utilities
- Main concern with alley closures are fire response and trash pickup
- Sometimes work is inevitable, but need to try and maintain emergency access
- Setup a separate conversation to discuss classification of roads and some of the implications of projects
- Traffic Control Reviews and how ATD plans for proposed work
- Need to reach out the CTM GIS to discuss the possibility of adding Alleys to street segments

**Comment by jaime-mckeown** [comment]
- Will need to reach out to Jacquie regarding the possibility of adding Alleys to the street segment layer.
- Also need to find out if the Road Class field is updated periodically.

**Comment by jaime-mckeown** [comment]
@andrewshensky would you like to take the lead on this?

**Comment by andrewshensky** [comment]
@jaime-mckeown yeah I can take the lead on this. I will reach out to Jacquie regarding the possibility of adding alleys to street segments through road class and verify the frequency of updates to the road class field.

**Comment by andrewshensky** [comment]
5/24 - Responses to questions above provided by Jacquie and shared with group.

**Comment by johnclary** [comment]
Closing since this will be part of the broader street segment convo.
