### ISSUE TITLE
Projects page 2.0 | Implement design refinements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6061]
- [x] Sentence case: "Project name", "Current phase", "Start date", "Team members", 
- [x] "eCapris Subp." ——> "eCAPRIS ID"
- [x] Override visited-link color
- [x] Tighten vertical row spacing

Some ideas - need to get a single, better mockup:
![Screen Shot 2021-05-17 at 3 10 00 PM](https://user-images.githubusercontent.com/1463708/118550162-f6f53180-b721-11eb-8f64-37a296554797.png)
and [this one](https://docs.google.com/document/d/1aZFQOa75TNeXUZ3ptjhd-LUbw5pG1sFn4npEtK4x8pg/edit#).

**Comment by chiaberry** [comment]
This is what its looking like now with the road icon removed and current phase/team members added 
![Screen Shot 2021-05-13 at 3 22 16 PM](https://user-images.githubusercontent.com/12474808/118183039-49231380-b3ff-11eb-99b8-eaba57d70a72.png)

**Comment by amenity** [comment]
@chiaberry nice!
I think we may need to address that purple ... see also https://github.com/cityofaustin/atd-data-tech/issues/5568

**Comment by chiaberry** [comment]
yeah I personally dont like the purple. I'll make it stay blue.

**Comment by johnclary** [comment]
@chiaberry [these](https://github.com/cityofaustin/atd-moped/commit/bf2c6d3d292102a29d02750618d001bee30b9a6e#diff-3cf902b80f1ce95a892953082bfd2c47e08a776caca79166498382aa897a79f7) [three](https://github.com/cityofaustin/atd-moped/commit/d8716099f74721cae45aa4385e0f758c7db403d8#diff-3cf902b80f1ce95a892953082bfd2c47e08a776caca79166498382aa897a79f7) [commits](https://github.com/cityofaustin/atd-moped/commit/a2f77effd27fcb33baeca5822cf6f699a42940ef#diff-3cf902b80f1ce95a892953082bfd2c47e08a776caca79166498382aa897a79f7) were my quick attempt to tighten up the spacing on this page. that should check the last box on this issue.

**Comment by chiaberry** [comment]
@johnclary the first commit will also affect the Staff Table, that's a desired improvement, right?

**Comment by johnclary** [comment]
i'm quite sure it is. let's have @amenity take a look once you push those changes?

**Comment by chiaberry** [comment]
https://6061-project-table-design--atd-moped-main.netlify.app/moped/staff @amenity

**Comment by amenity** [comment]
Tight! 🙌👍

**Comment by amenity** [comment]
@chiaberry @johnclary - do you need something from me to move forward merging these? I think they look great.

**Comment by johnclary** [comment]
Agreed. I think we're good to go @chiaberry! 🙏

**Comment by chiaberry** [comment]
I will merge main and open a PR, didn't know if you wanted to specify column widths.

**Comment by amenity** [comment]
@chiaberry - oops, right -- thanks! I'm playing around with column widths, though, and think they're good as is. We can tweak that when we have more real data and the full-width page John is implementing. 

Let's just get in those capitalization tweaks and call it a day!
