### ISSUE TITLE
Feature: Add Bug button to DTS Request

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6064]
Dan V. 
Finance

## As a Finance Admin I want a button easily create a DTS Request so that I can enter feature requests or bugs. 

Dan requested this on 5/5 after I was helping him with a different issue. He suggested a bug button.

**Comment by dianamartin** [comment]
He also mentioned that it would be nice to have a button/link to the DTS request from the Finance and Purchasing application
- [x] created a menu button that linked to the DTS Request
- [x] need to add special one that chia built that pre-populates for the Finance & Admin app - 5/12
- I finally found the issue that Chia had been working on the #5735 - parameter values to pre-populate the DTS Request form

**Comment by dianamartin** [comment]
@amenity FYI, I added the new URL that Chia helped with to this app! yay

**Comment by amenity** [comment]
🙌, thanks @chiaberry @dianamartin !
