### ISSUE TITLE
[TDS] Update Case Type & Case Type Abbreviations

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#6072]
Update forms and rules with the updated list:

C8- Subdivision
SP- Site Plan
SPC- Site Plan
C14- Zoning
C814- Zoning
C8J-Subdivision Joint City/County

**Comment by ChrispinP** [comment]
Case Type abbreviations and conditional rules have been updated. Case Type Field has also been changed from radio buttons to a drop down now that there are 6 options.

![image](https://user-images.githubusercontent.com/67915167/118150498-3d702680-b3d8-11eb-9865-cda0cedfd331.png)

complete

**Comment by TracyLinder** [comment]
Looks good; closing.
