### ISSUE TITLE
[TDS] Re-import Mitigation Geo Coordinates

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#6078]
Was not able to successfully import coordinates during initial import for intersection points.

Re-format coordinates so they can be imported successfully.

**Comment by ChrispinP** [comment]
Reached out to Andrew to see if its possible to get a list of the real coordinates for intersection points

**Comment by ChrispinP** [comment]
Was provided an updated csv for the coordinates. Did a test import for the records and the coordinate address populated correctly. Import and record updating is now underway.

![image](https://user-images.githubusercontent.com/67915167/118302592-079b7280-b4aa-11eb-9959-c8e74ce448f9.png)

**Comment by ChrispinP** [comment]
Coordinate import is complete. For some it seems to have input a standard set of coordinates rather than leaving blank for some reason.

![image](https://user-images.githubusercontent.com/67915167/118545745-9dd6cf00-b71c-11eb-8e54-efb84a01af8e.png)

But otherwise, most did import correctly.

**Comment by ChrispinP** [comment]
Not sure if its worth updating the records where the coordinates may be incorrect with another import. May be easier to correct ad hoc or set to a standard Austin,TX coordinates.

Moving to Review/QA

**Comment by TracyLinder** [comment]
**Status/Update:** Chrispin has more work to do to fix the coordinates bug described above.

**Comment by ChrispinP** [comment]
Was able to dig into the issue and found out 83 records were missing from the coordinates import file. I have reached out to Andrew for these coordinates.

![image](https://user-images.githubusercontent.com/67915167/118878183-e7f2b880-b8b4-11eb-88cf-ea68e5a4a05a.png)

**Comment by ChrispinP** [comment]
I have imported these missing coordinates and now all intersections in the mitigation_geo object have coordinates.

complete, closing
