### ISSUE TITLE
Review VZA citation app progress

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#608]

**Comment by SurbhiBakshi** [comment]
NOTES FROM VZA Dev Review
Shift table
Shift calendar
Shift Details
Location/Assignments
Location/Assignments Details
  Volunteers connection (Accounts)
  Citation connection
  Citation form (on Location/Assignments Details) - similar to Prototype 1 form
My Assignments
Advanced Search
Citation Tables
Reports
