### ISSUE TITLE
Bug on TIA Portal Application: Duplicate Case Types

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6093]
### See screenshot

![image.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/0772a104-e701-4307-ac02-8e7073b8ea42)

**Comment by ChrispinP** [comment]
This was a built update in #6072 

We may reformat depending on stakeholders/AMANDA

no action needed
