### ISSUE TITLE
Projects page 2.0 | Change default sort order to show most recently-modified first

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6094]

**Comment by chiaberry** [comment]
@amenity do you want to show the column of when the projects were last updated and give the option to sort by ascending? 
![Screen Shot 2021-05-20 at 5 37 43 PM](https://user-images.githubusercontent.com/12474808/119057432-1befdb80-b992-11eb-9f05-455f0ba7f5e3.png)

**Comment by amenity** [comment]
@chiaberry - Good call — we better show the field we're sorting by. 😅 

Let's just do the date, leave off the time. And the column can be labeled "Las modified"?
<img width="1103" alt="Screen Shot 2021-05-20 at 7 43 01 PM" src="https://user-images.githubusercontent.com/1463708/119065635-9b39db00-b9a3-11eb-94a1-dddb564c59d6.png">
