### ISSUE TITLE
TIA Mitigations Redesign 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6097]
### Updates to TIA Mitigation Features
`Chrispin will prototype new inline editing features for stakeholders prior to development.`

**Why we're updating design:**
- Improve system performance
- Pro-rata share field conditional bugs/issues
- Records are duplicating in both tables

**Updates:**
- Add the primary project address to the page details
- Mitigation Fees Required - Default value should be 'TBD'
- Cost field should be optional
- Change user input from a pop-up form to inline editing
- Add new mitigation improvement type: Shared Use Path
    - Conditional: Length, Width
    - Conditional: Shared Use Path Separation (same as Improvement Bike Lane Separation)
- Give users the ability to add multiple segments/locations to a single mitigation (Not MVP)
- Give users the ability to add multiple mitigations to the selected location (Not MVP)
- Segments/Intersections Map Updates:
    - Add the map to the mitigations details page, or make a button that opens the map in a new window
    - Both segments & intersections should be clickable
    - Add street names to zoomed in view
    - When you click on an attribute, open the details view instead of having to click on an arrow to see it.

**Comment by TracyLinder** [comment]
**Notes from Project Team Review:**
- We need to see a mockup or prototype before we can sign off on the new design. 
@ChrispinP are you able to create a mockup for next weeks' meeting?

**Comment by TracyLinder** [comment]
### From #6184

- [ ] Users will need to add multiple segments or intersections for a single mitigation. This isn't necessarily MVP.
- [ ] Make the mitigation cost field not mandatory
- [ ] Mitigation Fees Required - Default value should be 'TBD'
- [ ] Add new mitigation improvement type: Shared Use Path
- [ ] Conditional: Length, Width
- [ ] Conditional: Shared Use Path Separation (same as Improvement Bike Lane Separation)

**Comment by TracyLinder** [comment]
This is ready for development.

**Comment by TracyLinder** [comment]
### Next Steps

- [ ] Chrispin will mockup the user input changes (from form to inline)
- [ ] Review mockup w/ stakeholders for approval
- [ ] Begin development

**Comment by TracyLinder** [comment]
![Uploading Screen Shot 2021-06-02 at 1.28.15 PM.png…]()

**Comment by ChrispinP** [comment]
Reached out to Andrew for updating the Mitigation Map and we were successfully able to make segments clickable and now the features open directly into the blue/white popup that shows the Feature ID and Name
![image](https://user-images.githubusercontent.com/67915167/120719949-cab31200-c490-11eb-953b-cc5be2abcb5c.png)

**Comment by ChrispinP** [comment]
Redesign is now ready to review. Here are the new editable tables. Reviewers are now able to edit, view, and remove mitigations. Multiple locations can now be added to a primary location.
![image](https://user-images.githubusercontent.com/67915167/121095691-6c4ea200-c7b6-11eb-98b9-67d04baa26ad.png)

The edit improvement page:
![image](https://user-images.githubusercontent.com/67915167/121095783-97d18c80-c7b6-11eb-814b-41226d469532.png)

The view mitigation details page shows mitigation info and maps out any intersection points
![image](https://user-images.githubusercontent.com/67915167/121096214-5beaf700-c7b7-11eb-9677-1d524173a1ed.png)

**Comment by ChrispinP** [comment]
The ability to bulk add Mitigations has been added for feedback
![image](https://user-images.githubusercontent.com/67915167/123485554-f331b600-d5cf-11eb-9e0c-116653f596ee.png)

**Comment by TracyLinder** [comment]
Reviewed w/ stakeholders. Looks good, closing.
