### ISSUE TITLE
Remove & Replace TIA Memo features

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6098]
### Remove & Replace Memo features

**Criteria:**
- [x] Remove Pages: Memo builder landing page & Edit Memo 
- [x] Redesign Memo Details Page
- [x] Rename to 'Memo Details'
- [x] Remove page buttons

**Case Data to Include:**

- [x] Applicant & Engineer Info
- [x] Project Locations
- [x] Project Name
- [x] Case ID
- [x] Submittal date of most recent TIA Submittal cycle
- [x] Mitigation Tables 

![Screen Shot 2021-05-24 at 5.10.20 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/f8f0c277-9f86-4393-a570-5167b0e1325c)
![Screen Shot 2021-05-24 at 5.11.41 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/75ecf889-4f53-4f86-93b7-269c8ad4b0a4)
![Screen Shot 2021-05-24 at 5.13.06 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/cf48e0f3-a865-47c7-a4f5-f1b3c820e95a)

----
### Based on usability feedback, this feature is unlikely to be used. 
- Discuss with stakeholders: Can we remove this from MVP?
- Interim solution: Generate a page w/ the blocks of text/case data so the reviewer can copy + paste.

**Comment by TracyLinder** [comment]
**Stakeholder approval on Memo Builder changes**

- Remove memo builder features
- Replace w/ a single 'Memo Data' page that makes copy + pasting easier

**Comment by TracyLinder** [comment]
This is ready for development.

**Comment by ChrispinP** [comment]
Memo Details page:
![image](https://user-images.githubusercontent.com/67915167/122451533-e11b9c00-cf6d-11eb-9a14-719433b78f18.png)

Memo Data page:
![image](https://user-images.githubusercontent.com/67915167/122451598-f7295c80-cf6d-11eb-985f-c71a3315736d.png)

I believe we should add the Case Management menu to the Memo Data page as well. Memo has only two statuses now; Being Constructed and Sent. Mark as Sent button will show if Memo has not been marked as sent.
![image](https://user-images.githubusercontent.com/67915167/122452110-859dde00-cf6e-11eb-81df-37466f8fd298.png)

**Comment by ChrispinP** [comment]
Pending review before we decide if we should add the mitigation tables to the Memo Data page or if them being on the Mitigations page is fine.

**Comment by TracyLinder** [comment]
@ChrispinP can you look into the paragraph text in the mitigation export please?
![Screen Shot 2021-06-30 at 1.50.00 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/19a60bfd-eee8-4dff-aec6-bf4f62f0c9fc)

**Comment by TracyLinder** [comment]
See previous two comments; moving back to In Progress.

**Comment by ChrispinP** [comment]
Memo and Request objects now merged. Memo object removed. Memo Data page removed.

Memo Details page now houses the case, location, and memo information in addition to the mitigation tables. Last Submittal Date and Memo Status are present on this page.
![image](https://user-images.githubusercontent.com/67915167/124821244-17788580-df34-11eb-9941-ff51fe30da0f.png)

Ready to review

**Comment by TracyLinder** [comment]
**Ask stakeholders:** Do they want the case status to update to approved when the memo is marked as sent, or would they rather do that manually?

**Comment by ChrispinP** [comment]
Status now bolded and at the top
![image](https://user-images.githubusercontent.com/67915167/125130899-6e629400-e0c7-11eb-8fee-36d98f776640.png)

Sent message to Knack about the html tags on a Rich Text export, if no alternative, we may need to change the field to Paragraph Text instead unless we are okay with the tags showing in the export. Pending response.

**Comment by ChrispinP** [comment]
Recommendation notes field has been changed from Rich Text field to a Paragraph Text field so export does not include html tags.

For case status, for now they will manually approve cases and marking a memo as sent will not change status.

Stakeholders are happy with layout. Ready to close
