### ISSUE TITLE
Revoke access for MD

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#6122]
Asking Apps to Team help finalize MD offboarding.

- [x] Remove access to Knack applications
  - [x] SMB Tracker
  - [x] Street Banners
  - [x] AMD Data Tracker
  - [x] Vision Zero in Action
  - [x] Data and Technology Services Portal
  - [x] TDS
  - [x] ROW
  - [x] HR
  - [x] SMO (did not have an account)
- [ ] Remove from DTS SharePoint team lists

**Comment by dianamartin** [comment]
@ChrispinP @SurbhiBakshi Can you please check your apps that you primarily work in and see if Mike has any accounts in them, if so please make him "inactive" and remove user roles. Please add your app to the list above.

**Comment by ChrispinP** [comment]
Inactivated in ROW and TDS, no RPP account. Anything additional I should check?

**Comment by SurbhiBakshi** [comment]
Inactivated in VZA and DTS Portal, will check in the HR app tomorrow.

**Comment by dianamartin** [comment]
Updated SharePoint information. Need to double check if he's still on the distribution lists. There should've been a separated employee form filled out, I'll ask John.

**Comment by ChrispinP** [comment]
@dianamartin Do you mind showing me how to update the SharePoint Information or if it is already part of our offboarding documentation? Thanks

**Comment by dianamartin** [comment]
@ChrispinP I just removed him from some of our DTS org chart, I updated the page so we don't have to update it. I embedded the "About Us" page on the Org Chart [page](https://cityofaustin.sharepoint.com/sites/ATD/DTS/SitePages/Organization%20Chart.aspx).

**Comment by dianamartin** [comment]
Putting in CTM ticket to remove Mike from DL "ATD Data and Technology Services"
