### ISSUE TITLE
Review Dispatch Tracking Reporting

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6127]
•	Leadership to review Reports:
Review the existing reports and consider these questions
•	which reports are needed? 
•	are the reports you have meeting what you need to report on 
•	we are also showing the reports in different ways (ex. Current Week, Current Month, Current Quarter, or All Time), we want to know which ones you need to be filtered a certain way 
•	we need to know which reports you need to "expand" so it opens up into a results table, not all the reports do that. 
•	I would suggest to be strategic to select which reports you use like this as if you say all of them, that is a lot of work to configure. 
•	I'll do it if it's necessary for you to review/reference but we want to eliminate doing that for all reports if they're not being used that way.
Complete attached reports spreadsheet by Thursday 5/20

Provided spreadsheet for reporting feedback

**Comment by dianamartin** [comment]
Toni S. provided spreadsheet back
[Parking Enterprise Portal Reports spreadsheet - filled](https://app.zenhub.com/files/140626918/d5920069-1281-421c-ae19-49185d87ad73/download)

**Comment by dianamartin** [comment]
We need to create a new issue to Update Reporting for them

**Comment by moorerst** [comment]
Leadership completed the reporting spreadsheet. Created a new issue for updating reporting. Closing this issue.
