### ISSUE TITLE
Spike: Explore implementation in Power BI

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6131]
Also look at #6211

**Comment by SurbhiBakshi** [comment]
### **Notes -** 

### Datasets needed - 
1. work_order_signs
2. work_order_markings
3. work_order_markings_jobs
4. work_orders_signs_markings_time_logs

### 
Datasets available on AGOL - 
1. Pavement Markings Work Orders
>> a. signs_markings_jobs
>> b. signs_markings_work_orders

**Comment by SurbhiBakshi** [comment]
Fields needed for the High Level Dashboard are located [here](https://cityofaustin-my.sharepoint.com/:x:/r/personal/christina_tremel_austintexas_gov/_layouts/15/Doc.aspx?sourcedoc=%7B54AA800B-E890-4478-96EA-2E7A664D6721%7D&file=Work_Orders_High_Level_Dashboard.xlsx&action=default&mobileredirect=true)

**Comment by SurbhiBakshi** [comment]
Will reach out to Andrew/Peter at ESRI for help with above #6211

**Comment by SurbhiBakshi** [comment]
https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/6165

**Comment by SurbhiBakshi** [comment]
Going to meet Christina 06/30 to talk about feedback from Jim D and also if more fields need to be added to the datasets on the Open Data Portal. Jim D would like to see the reports updated twice a day.

**Comment by amenity** [comment]
There may be future enhancements, but considering this spike closed.
