### ISSUE TITLE
Inventory Reports accessible to "Viewer" role

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6134]
Ivonne N./Jen D.
AMD

Emailed
>Can you grant me access to the inventory module in data tracker? Current message:  "User doesn't have permission to access this page". I don’t know how the interface looks like but my “main” use will be to monitor expenses associated to specific TKs/FDUs. I imagine there are some reports/search available in the module.  I don’t need any editing permission.  

Jen authorized the request (CC), let me know if you need any additional information.

**Comment by dianamartin** [comment]
@johnclary did you want me to do this or did you want to take this?

**Comment by johnclary** [comment]
You can do it. Just change the permissions on [the reports page](https://builder.knack.com/atd/amd/pages/scene_1152) to `Viewer`. That will cause the "Reports" page to be visible on the Inventory drop-down menu for all users.

The [items page](https://atd.knack.com/amd#inventory-items) is already available to viewers.

I am expecting that Ivonne is going to need a specialized report.

**Comment by dianamartin** [comment]
I updated the "Inventory Reports" page and included "Viewer" role to be able to see it. I'll email Ivonne so she can see what the Reports look like. I also think maybe she may request a more customized report too.

**Comment by dianamartin** [comment]
Emailed Ivonne
>I talked to John and we had an “Inventory Editor” role, but we ended up deciding to make the page viewable by “Viewer” roles. You already have this role so you should now be able to see the Inventory Reports page. Refresh your page if you don’t see it initially. I am not 100% sure if what you’re looking for will be in these reports. If you don’t find what you’re looking for you can put in a request for a report, if needed.
