### ISSUE TITLE
Create Banner Program Field Review Maps - Lauren

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#6145]
From Lauren:

> Attached are 6 areas of inquiry for new lamppost banner districts. Some may have regular poles, some may have the shorter pedestrian scale poles. If you’re able to see and indicate the difference, that’d be ideal. Again, nothing super fancy needed at this point: dots for poles, street names, pole numbers, type/size of pole.

**Comment by jaime-mckeown** [comment]
Met with Andrew to go over the Lamppost Banner Program and talked about this request.

**Comment by andrewshensky** [comment]
5/26 - Maps delivered to Lauren for her review.
