### ISSUE TITLE
Use "Authoritative" tag on AGOL

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6146]

**Comment by jaime-mckeown** [comment]
- Need to be logged in as ATD Admin to assign content in AGOL as Authoritative
- Went through AMD content and set layers coming directly from Data Tracker to Authoritative
- Updated and added data to data inventory.

**Comment by jaime-mckeown** [comment]
Need to go through other division folders to see if there is any other authoritative content.

**Comment by johnclary** [comment]
@andrewshensky plz mark the bike parking layers as authoritative. @alan-deanda can you think of other "authoritative" data?

**Comment by andrewshensky** [comment]
Bike Parking layer has now been marked as authoritative.
