### ISSUE TITLE
Bill inventory items to one or more task orders

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#615]
### As a AMD supervisor I want track the items so that can be charged to a project to get reimbursable money for the division. 

This is already on the ICF and will be on the DICF/EICF too.

**Comment by amenity** [comment]
Let's discuss this in the sprint review

**Comment by dianamartin** [comment]
During stakeholder meeting, it was agreed that the task order would go on inventory request. One to one.
