### ISSUE TITLE
Project Components: Ability to draw lines

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6150]
As a project editor, I need to be able to draw line features when my project is at a location that doesn't exist in the basemap.

#### Funcional requirements
- drawn lines should be stored in `moped_proj_features` in a way that mirrors the way draw points are stored. Refer to the [geoJSON specification](https://gist.github.com/sgillies/1233327)'s `LineString` type.
<img width="1426" alt="Screen Shot 2021-05-19 at 4 04 43 PM" src="https://user-images.githubusercontent.com/14793120/118884914-ac5bec80-b8bc-11eb-96f7-b1ec4f532c72.png">

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/316
