### ISSUE TITLE
Receive an inventory shipment

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#616]

**Comment by dianamartin** [comment]
Create a `shipment` table or connect to the 'invoice items', new field "Received", "Quantity"
Have it trigger restock of inventory.

**Comment by dianamartin** [comment]
Called Adelita and reminded her that we talked about Shipment Received "enhancement"

So I asked her what she needs on the Finance side (Accounts Payable)

- [ ] `Shipment Received` - Y/N
- [ ] `Quantities Received` - _User enters quantities_
- [ ] Attachment - shipping receipt

**Comment by dianamartin** [comment]
Talked to Ray about what he thinks. We could just edit the existing Invoice Details, add `Shipment Received` form that asks for `Quantity` and `Received Date`. 

Then update the `Invoice Details` by adding an attachment.

**Comment by dianamartin** [comment]
Configured in the Test environment and it looks like it's working. 
### `invoice_items` object table
Added new fields:
- [ ] `Date Received`
- [ ] `Received By` - accounts connection
- [ ] `Received Quantity`
- [ ] `Received Shipment`

### `invoice_details` page
Add menu - `Menu | Warehouse`
Add table - `invoice_items | Warehouse`

### Page Rules
Account>User Role - is no - `Admin`
Hide views:
- menu menu
- delete invoice details
- invoice items | Accounts Payable
- add Invoice Item form

**Comment by dianamartin** [comment]
### Process
Purchase Requests goes through whole work flow
During the `Pending Invoice` step

Warehouse staff receives an order to the warehouse
Warehouse staff will go into `Purchase Request>Invoice Details` page
Special table was created for the warehouse staff to add quantity and date shipment was received. 

Can also add `invoice attachment`. This attachment is the original attachment form and adds it to the Purchase Request attachment table. 

From that point, we can configure an email notification to the Accounts Payable email that Finance has set-up. 

Accounts Payable would have same closure/invoice process in order to close the purchase request.

**Comment by johnclary** [comment]
@dianamartin closing this one out and will open new issues for any refactoring that needs to be done.
