### ISSUE TITLE
Extend component data model and load initial component data

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6163]
This work encompasses schema updates and preliminary loading of Moped component data. These changes allow for the subtype and subcomponent attributes pictured in [this slide](https://docs.google.com/presentation/d/1ReEDaHTggCL5dkhnX47g0N-zPad2FiFlZd-rIHkDB1w/edit#slide=id.gd6e63e50b0_2_130). We'll need to add additional columns down the road but this is the minimum we're feeling confident about at the moment. 

#### Columns
- `subcomponent_id` (serial)
- `subcomponent_name` (text)
- `component_id` (int) - `moped_components` foreign key. One `moped_component` relates to many `moped_subcomponents`. Is not nullable.

#### Create new table: `moped_proj_components_subcomponents`

This table will hold a many-many relationship between `moped_proj_components` and `moped_subcomponents`.

#### Columns
- `id` (serial)
- `proj_component_id` (int): `moped_proj_components` foreign key
- `subcomponent_id` (int): `moped_subcomponents` foreign key

#### Update moped_components table

1. Drop column: `date_added`
2. Drop column: `component_order`
3. Add column: `component_subtype` (`text`)
4. Add column: `line_representation` (`bool`)

#### Load preliminary data into `moped_components`

component_name | component_subtype | line_representation | status_id
-- | -- | -- | --
Access Control | Driveway Closure | TRUE | 1
Access Control | Driveway Modification | TRUE | 1
Access Control | Hardened Centerline | TRUE | 1
Access Control | Median | TRUE | 1
Bike Box | &nbsp; | FALSE | 1
Bike Lane | &nbsp; | TRUE | 1
Bike Lane | Buffered | TRUE | 1
Bike Lane | Climbing | TRUE | 1
Bike Lane | Colored | TRUE | 1
Bike Lane | Contraflow | TRUE | 1
Bike Lane | Protected One-Way | TRUE | 1
Bike Lane | Protected Two-Way | TRUE | 1
Crossswalk | Continental | FALSE | 1
Crossswalk | Creative | FALSE | 1
Crossswalk | Raised | FALSE | 1
Signal | PHB | FALSE | 1
Signal | RRFB | FALSE | 1
Signal | Traffic | FALSE | 1

#### Load data into `moped_subcomponents`

Once the component data is created, I will provide the subcomponent data to be loaded. For example:

subcomponent_id|subcomponent_name| component_id
-- | -- | --
1 | Raised pavement markers| ?
2 | Audible push button| ?
3 | Bicycle signal| ?
4 | Leading pedestrian interval| ?

**Comment by sergiogcx** [comment]
There is a PR ready for review:
https://github.com/cityofaustin/atd-moped/pull/322
