### ISSUE TITLE
Create list of residents eligible for RPP renewal email notification

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6174]
The issue to create a task to send automatic email notifications to residents eligible for RPP residents has some complexity so it's being placed in the backlog.

- [x] As a workaround manually generate list of residents eligible for RPP renewals that can be used for mass email renewal notification.

**Comment by moorerst** [comment]
Target RPP August renewal
Use Application email address

**Comment by moorerst** [comment]
Stephanie will notify Steve confirm 60 day and 30 day notification

**Comment by moorerst** [comment]
@ChrispinP confirmed with Steve that getting the list by June 1st would be needed for 60 day renewal notifications. Thanks

**Comment by ChrispinP** [comment]
exported permit_application data and formatted spreadsheet.

Sent email with file. Pending anything further.

**Comment by moorerst** [comment]
@ChrispinP there are a lot of missing email addresses for residents who renewed in June July Aug Sept timeframe. But there is an email address on the application.
For example Application ID 2020-3045 
![image](https://user-images.githubusercontent.com/56606465/119849394-3403b580-bed2-11eb-849e-c15db9d917ea.png)

**Comment by ChrispinP** [comment]
Yea, before the update, email was only stored on the Customer object so for the older applications the Customer ID can be used to reference the customers email. Cleaning up this customer data is an issue we have in the backlog #4356 

RPP Staff can also edit an application and update the emails as well.

**Comment by moorerst** [comment]
That's a large chunk of residents with no email address so the list is not as useful. How would they edit the application to update the email address. I have some time I could work on that to make this list more useful.

**Comment by ChrispinP** [comment]
It will take some time but the easiest solution would be for me to update all application records with customer information that is missing and then re-export again. Would need #4356 pulled on deck and set to high priority.

**Comment by moorerst** [comment]
Done. Thank you!

**Comment by ChrispinP** [comment]
Finished updating records and sent out a new email with the updated excel file.

Pending any further action

**Comment by moorerst** [comment]
@ChrispinP thank you for your efforts on this. Closing issue.
