### ISSUE TITLE
(TIA Customer Portal) Remove filter tabs from all views

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6177]
![Screen Shot 2021-05-24 at 5.00.14 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/39df76b7-a8e3-4cab-9d43-39f5ed679387)

**Comment by ChrispinP** [comment]
Filter tabs removed for Submission tables:
![image](https://user-images.githubusercontent.com/67915167/120519238-028a5e80-c398-11eb-9549-d5dbd77c218a.png)

and Attachment tables:
![image](https://user-images.githubusercontent.com/67915167/120519809-b12e9f00-c398-11eb-9875-7f6c6384c774.png)

**Comment by TracyLinder** [comment]
Reviewed w/ stakeholders. Looks good, closing.
