### ISSUE TITLE
(TIA Customer Portal) Updates to TIA Case Details View

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6178]
- [x] Remove filter tabs
- [x] Remove fee paid info
- [x] Remove Final Memo date
- [x] Move Request Status to top left, just under project name, and unbold 

----
![Screen Shot 2021-05-24 at 12.12.25 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/7153fed6-ca28-4074-a3e8-557b71280b5e)

**Comment by ChrispinP** [comment]
Complete
![image](https://user-images.githubusercontent.com/67915167/120552263-a0902000-c3bc-11eb-966c-e8f5496843f4.png)

**Comment by TracyLinder** [comment]
Reviewed w/ stakeholders. Looks good, closing.
