### ISSUE TITLE
(TIA Customer Portal) Landing Page & TIA Details Content Updates

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6180]
### Content To Be Updated:
- **Final Content is [here](https://docs.google.com/document/d/13eJ2d2pVepvJhvjwj9RfuT23HHcuZAmnwQyW6pAINGw/edit)**

![Screen Shot 2021-05-24 at 3.35.44 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/770d6afa-84d6-4e56-92a7-be5ca2eff2d5)

![Screen Shot 2021-05-24 at 3.37.11 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/6d04ef25-4f4d-4fde-8848-b83e322344d9)

**Comment by TracyLinder** [comment]
@ChrispinP the link to the doc with the final content is in the issue description.

**Comment by ChrispinP** [comment]
Updated TIA Details text with icons and highlighting for user testing. Will remove highlighting if not helpful for users
![image](https://user-images.githubusercontent.com/67915167/120717861-e36df880-c48d-11eb-8d10-c8d08e2878a1.png)

Updated TIA Portal page with buttons for user testing. Will remove buttons if not helpful for users.
![image](https://user-images.githubusercontent.com/67915167/120717990-292ac100-c48e-11eb-9ca4-855b540887af.png)

**Comment by TracyLinder** [comment]
@ChrispinP this doesn't appear to be done. Please check it.

**Comment by ChrispinP** [comment]
Landing Page has been updated. Ready for user testing
![image](https://user-images.githubusercontent.com/67915167/122091256-3c168d00-cdce-11eb-99a5-b945024802e3.png)

**Comment by TracyLinder** [comment]
@ChrispinP please make the DTS Staff button a link at the bottom of the page.

**Comment by TracyLinder** [comment]
@ChrispinP please make this change & close the ticket.

![Screen Shot 2021-06-30 at 2.07.52 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/93fe55d9-2aaa-4f30-9a47-1b3e2580904b)

**Comment by ChrispinP** [comment]
Complete
![image](https://user-images.githubusercontent.com/67915167/124028000-1c2fbd80-d9b9-11eb-9202-aa00311d34fa.png)
