### ISSUE TITLE
(TIA Customer Portal) Comments Table Bug on TIA Details

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6181]
### Comments are not populating in this table, and the review cycle # isn't populating correctly.

![Screen Shot 2021-05-24 at 12.19.00 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/349e53a4-ccbd-4025-81c7-65ba0825056a)

**Comment by TracyLinder** [comment]
We will be redesigning the features on the reviewer side, and will need to finish that before we tackle this. (#6099)

**Comment by ChrispinP** [comment]
Rules have been updated for these Comment Tables. Need to test again with new data to make sure records are assigned correct cycle # and correctly show up in the table if the Comments field is not blank and meets at least 1 of 3 criteria; Status is Revision Required, Status is Approved, or Show Customer is Yes(checked).

**Comment by ChrispinP** [comment]
The comments are now located within the Submission View. Removed these tables. Pending any further action.

**Comment by ChrispinP** [comment]
Table rules updated to not display hidden or empty records
![image](https://user-images.githubusercontent.com/67915167/122092451-8f3d0f80-cdcf-11eb-8b56-d7800a2df66b.png)

**Comment by TracyLinder** [comment]
Reviewed w/ stakeholders. Looks good, closing.
