### ISSUE TITLE
Meetings: TIA Mod Technical Design Review 6/4 & 6/9

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6182]
### Internal DTS meeting to perform a technical design review of the TIA Mod

**Who:** Tracy, Chrispin, Amenity, Diana
**When:** 6/4/21 @ 11am

**Prep/Next Steps:**
- Copy the app w/o customizations (comment it out)
- As much as possible, try not to change the UI prior to this review
- Meet, and do a side-by-side comparison (design review)
- Documentation of custom CSS in the app 
    - Where it is & why it exists

**Comment by dianamartin** [comment]
# Diana's Notes
## TIA Requests page
### Announcements table (Header)
  **- Keep default, incorporate page rule**
  - Page rules, hides the table completely
- Custom: Has weird divider bar, scroll bar? hiding the header makes the "No Announcements" look funny

## Filter Menu
- Take "North, Central, South" filters
- Remove the "empty filters" for separation purposes

## Request Information Form - Customer Intake Application
- this is filled out by customer
- can be manually filled by TIA reviewer
- Keep default, doesn't have outline

### Custom CSS to to make hyperlinks look and act like "real" hyper links 
- "Look up Council District" - external link
- "form-class"
- update GitBook HTML link - on Style Guide

## Request Details page
- Menu Navigation - Custom Menu worked with Chia Berry
- Menu buttons to Menu Tree
- CSS code to change width to switch from Menu Tree v. Default menu 
- Keep Stacked buttons
- [ ] Removed Drop shadow
- [ ] CREATE NEW ISSUE: @ChrispinP Cross device testing in browser stack to update the code to remove the stacked menus
- [ ] Dev time too
- [ ] @ChrispinP Explore multiple menu buttons 

## Request Details Page
- Custom: remove gray background, remove extra space
- Keep Default, remove custom
- Case Notes 
  - [ ] Move to own details widget, 1 column

**Comment by dianamartin** [comment]
# Diana's Notes - 6/9
- ## Modal Windows
### Enhancement to darken the "x" icon on modal pop-ups
  - Add Commenting labels for "Modal pop-up CSS"
  - If we turn it into a standard, have Dev review code
### Enhancement: Modal Close Styling - disable users from clicking out of model pop-up
- JS code, written in GitBook
- no use case improvement
- [ ] Add section headers
- [ ] Decision: Modal v. Stand alone - See the customer pages first to make that determination
  - Keep Modal Close Styling if stand alone is chosen

## Mitigation Details
### Mitigation Fee-in-Lieu - remove default summary text that Knack has 
- "Total - Record Name" to "Location Total"
- JS Code - 15-20 lines of code
- Determine which column to put it
- [ ] SKIP enhancement, to avoid more custom JS code

## TIA Reviews>TIA Reporting
Knack uses High Charts to configure reporting
### Global setting that is applied to all reports: 
  - Highcharts.setOptions
- plot background - grey/blue background
- plot outline thicker
- color matching - colors are consistent
- Written code for charts to match legend colors, Knack matches charts and legends by default
- Avoid investing in Knack reports, report configuration
- [ ] Remove reporting CSS styling

Discussed layouts and mobile responsiveness

## Customer Page - TIA Details
### "New Submission" green button 
- make trigger button look like normal Knack button
  - [ ] Change button to look like big button
- Make TIA Details, look visibly friendly like "Get Started" RPP page

### Previous Window button
- Default - disabled breadcrumb 
- JS function

### Back to View TIA Details
- [ ] Remove icon - remove from HTML label

**Comment by dianamartin** [comment]
# Diana's Notes - 6/21
## Current State - Customer Portal
- Splash page - for learning how to create new TIA request
## TIA Details - link from email to navigate there to view case details, prompt to submit submissions
- Details section is not default yet, it's got white background and no outline
- Need to update page rule "TIA Submission" header is showing without table
- Disabled state button (html button), opacity on it
- use Knack disabled button? 
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/dfd5fa16-1b8f-46cf-b47d-03ea5dad8c40)
- bigger size button (+ New Scope Submission), white text is washing out the button info. Suggestion: change to dark grey text color instead. 
- @ChrispinP please take a screen shot of the new styled knack button

## Table 
### Edit icon/background
- Keep edit icon showing, when disabled keep default hidden/hide icon
### Status Colors 
- Use knack styling colors
### Send Submission field
- trigger button, usually link text 
- Icon and text link 
- The "check mark" icon should say "Yes"
- Remove green button style. "Confirm" status, used icon "mail/forward" "Confirm"
- Remove "dash" - display rule

### Submission View table
- Previous Window, add "Reply" icon
- Back to View TIA Details, "Arrow" icon
- Scope Submission Attachments table, "File" Name, we replace "Attachment" 

### Edit Submission Cycle
- Attachment is above the "Checkbox "Attachment is over 100MB in size"
- "Online" doesn't need capitalization 
- Maybe add a note "After 24 hours, you can not remove a file.."

### Edit Submission Attachment form
  - Add Checkbox "Attachment is over 100MB in size" 
  - Make add and edit forms as close as possible
-

**Comment by TracyLinder** [comment]
@ChrispinP is this ready to close?

**Comment by ChrispinP** [comment]
Reviewed design changes with Tracy. We are happy with made changes. In addition, removing top TIA tabbed menu since it is too close to the case menu.

complete, closing
