### ISSUE TITLE
Update Amenity's role to supervisor

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6185]
Please make me a "Supervisor"🙏 so that I can approve peep's telework requests. 
![Screen Shot 2021-05-24 at 1 59 03 PM](https://user-images.githubusercontent.com/1463708/119395113-af7a2280-bc98-11eb-9def-bd93d05e3971.png)

**Comment by ChrispinP** [comment]
Amenity's role updated to Supervisor
![image](https://user-images.githubusercontent.com/67915167/119404274-31704880-bca5-11eb-92f8-4018b508c274.png)


complete
