### ISSUE TITLE
Begin Review Popup Content

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6186]
### Update content on 'Begin Review' for both scope & submissions

![Screen Shot 2021-05-24 at 6.05.06 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/5e12d1ca-1a22-426f-b949-a8f49705a3b4)

**Comment by ChrispinP** [comment]
Complete
![image](https://user-images.githubusercontent.com/67915167/120367504-8d0a8980-c2d6-11eb-9d41-1f528b0636d4.png)
