### ISSUE TITLE
Add the submission/scope cycle case log to the TIA Submissions

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6187]
### Add this feature to the TIA Submissions

![Screen Shot 2021-05-24 at 6.07.15 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/05fbb931-c51a-458c-a634-e38b8f1cdfec)

**Comment by ChrispinP** [comment]
Complete
![image](https://user-images.githubusercontent.com/67915167/120367834-f68a9800-c2d6-11eb-8e8f-a864715bc40b.png)
![image](https://user-images.githubusercontent.com/67915167/120367885-04401d80-c2d7-11eb-8dcd-7dfd156e9e4e.png)
