### ISSUE TITLE
Navigation Button Updates

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6188]
- [x] Move the navigation menu from it's current location, to just below the page header. 
- [x] Add this navigation button to all main pages
    - Case Management, Submission/Scope Details, Mitigations, Memo Data

![Screen Shot 2021-05-24 at 6.09.00 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/5281a2f3-5c20-4a14-bd7e-9d6380b090a1)

**Comment by TracyLinder** [comment]
**Update** Most work has been done however KNACK doesn't allow us to add the navigation menu to child pages. @ChrispinP will check with @chiaberry to see if she has any magic to help w/ this.

**Comment by ChrispinP** [comment]
I reached out to Chia to see if we can add the Case Management nav menu to the Submission Details pages

**Comment by chiaberry** [comment]
Are the menus in the right place?

https://atd.knack.com/test--tds--09-jun-2021--transportation-development-services-portal#tia-requests/tia-case-details/60c0d98007ba0e0b9590c3e7/tia-case-management/60c0d98007ba0e0b9590c3e7/tia-submission-details/60c0d98807ba0e0b9590c75b/

https://atd.knack.com/test--tds--09-jun-2021--transportation-development-services-portal#tia-requests/tia-case-details/60c0d98007ba0e0b9590c3e7/tia-case-management/60c0d98007ba0e0b9590c3e7/tia-scope-submission-details/60c0d98207ba0e0b9590c494/

**Comment by ChrispinP** [comment]
@chiaberry they might get moved, but yes.

You'll notice that the url parameters need to be updated specifically for these two child pages. If you click on Case Details for example you end up on this empty page:
![image](https://user-images.githubusercontent.com/67915167/122097452-4ee09000-cdd5-11eb-993c-11b5dbab4974.png)

![image](https://user-images.githubusercontent.com/67915167/122097510-615ac980-cdd5-11eb-9e1b-b1f25d85279a.png)

**Comment by ChrispinP** [comment]
Chia was able to submit PR #62. Reviewed and tested code. Able to successfully add and use Case Management menu on child pages.
![image](https://user-images.githubusercontent.com/67915167/124029187-7da45c00-d9ba-11eb-9738-4d63bcd0dfbc.png)

complete, closing
