### ISSUE TITLE
Manually adjust inventory levels to reconcile discrepancies

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#619]
### As a warehouse staff member I want the ability to change the quantities to make sure that I'm tracking the items on hand and documenting and discrepancies.

**Comment by amenity** [comment]
Adjustment transaction type.

**Comment by dianamartin** [comment]
- [ ] Add `Adjustment` button to transactions

**Comment by dianamartin** [comment]
On object table `inventory_transactions`  - the `Quantity` field has a validation rule
![image](https://user-images.githubusercontent.com/21112975/67719937-cd8a7e80-f9a0-11e9-8579-801c539fef93.png)

Removed so that a user can enter a negative number to be able to do an adjustment.

**Comment by dianamartin** [comment]
Just tested. The `AMBER LED` had a quantity of 65, made an adjustment record of -10. The "reports" page shows 55 and the -10 adjustment record I made. 

Working!
