### ISSUE TITLE
Meeting: Mid-migration User Testing w/ Laura R.

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6200]
**Why:** Test the TCP Tracker app on the new ROW Portal prior to full migration.,
**Who:** Laura R., Tracy, Chrispin, John (optional)
**When:** 6/3/21 @ 11am

----
[Here's](https://web.microsoftstream.com/video/f80affe4-b929-4940-a5c0-9e4247ff8e47) the meeting recording.

**Comment by TracyLinder** [comment]
### To Test

- [ ] Create new TCP
- [ ] Edit existing TCP
- [ ] Search TCP
- [ ] Add a TCP submission
- [ ] Edit an existing submission

**Comment by TracyLinder** [comment]
### Notes

Assigned To: Values should be:
- Robert Alvarez, Shawn Jackson, Juliet Thomas, Darren Ujano, Ryan Mooney, Doug Slauson, Jonathan Thompson, Richard Zapata
Assigned To - Should only allow one value
- Assigned to field isn't populating

After submitting new TCP, system should open the record.

The TCP status isn't populating.
The Submitter name isn't populating. 
Missing TCP ID

Project page should sort newest to oldest

Be sure to give users export options from the TCP Project Page
### Create New Submissions
- The page form is missing fields: Needs Submitted Date, Due Date
- Submission Status: Lots of duplicates. 
- Submission assigned to should auto-populate to the TCP Assigned to 
- Due date should auto-populate with 10 business days after submitted date
- Remove date field from Review Completed

**Comment by TracyLinder** [comment]
These results need to be rolled into #6191

**Comment by TracyLinder** [comment]
My notes have been cleaned up. @ChrispinP please add any notes you may have, and close this issue when you don't need it to be open anymore. Thank you!

**Comment by ChrispinP** [comment]
- Replaced old fields with new fields for Submission ID, Assigned To, Submitter Name, etc
- Cleaned up user accounts
- Completed all listed bugs/action items above

**Notes**
1) With new builder, if we default Due Date with a conditional it will remove the ability to inline edit in the table.
2) Should update field casing in Excel before import so it does not include Capitalized values as options in the field values.
3) Need to create fields to do the automation for TCP Status, Submission Status, and TCP ID
