### ISSUE TITLE
Bug: DS Permit Report Not Available On Portal (Nate Verifying)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6201]
### Portal users were once able to print their DS permits, but are now unable to do so. 

**Stakeholder:** Kim P.

**Comment by TracyLinder** [comment]
I let Kim know we'd pick this up during sprint planning on 6/1/21.
FYI @Nadin-Nader & @Sreelatha-BlazeKannan

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder  - Verified and found that the portal is looking at report code 83933 for DS permit. where the report path was incorrect. 

![image](https://user-images.githubusercontent.com/65371095/122094227-8cdbb500-cdd1-11eb-80fc-ad13a4886fc2.png)

I have corrected the path in DEV and TEST as 
\\COACD.ORG\DFS\AMANDA\BROWSERFORMS\DEV\50506_F_DRIVEWAY_SIDE_WALK_PERMIT.RPT

Now I can see the DS Permit in portal like below
![image](https://user-images.githubusercontent.com/65371095/122094520-e2b05d00-cdd1-11eb-9243-365ca1d4876f.png)

please review and let me know your thoughts.

**Comment by Nadin-Nader** [comment]
This has been sent to AMANDA CTM under **SCTASK0146307** to adjust the path.
**Status:**
Waiting on CTM to make change on PROD

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on CTM to make change on PROD

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan Swapna changed the path for this on PROD and closed the TASK. Please UAT

**Comment by Nadin-Nader** [comment]
I asked Paloma to UAT this. She said shed try to get to it today 6/28/21.

**Status:**

Following up tomorrow if i dont hear back from Paloma.

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder  - Once if we can verify it on PROD this can be closed.

**Comment by Nadin-Nader** [comment]
This is not showing on ROD Portal Continue to work

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Working on this, Previously I was able to view all permits, but now EX Permit is visible in Test but not DS & RW.

**Comment by Nadin-Nader** [comment]
Email sent to Swapna about portal:


Hi Swapna,
Good Evening, This is regarding the card #6201 - Bug: DS Permit Report Not Available On Portal; I found that the report path was not mentioned appropriately in AMANDA back office which caused the issue in DEV. Upon which tested and updated the card with Screen shots. Last week when tried with stake holders it was not working in Either DEV or TEST. And now its again working in DEV but not in TEST. May I know why I am not able to see a report in TEST when I am able to see it in DEV. Is it any access issue. 


DEV Portal for DS appears like below – 
![DS DEV.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/fc078d86-350f-4630-8773-6b83cb30be23)

TEST PORTAL for DS appears like below – 
![DS TEST.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/cf3e9dc8-715e-4df0-9dd6-091f9ad75c10)
 



Thanks & Best Regards,
Sreelatha Blaze Kannan

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please follow up w/ Swapna?

**Comment by Nadin-Nader** [comment]
**Status:**
Since i could not get a hold of Swapna i sent her another email asking for her response and verification. Waiting on Swapna's response.

**Comment by Nadin-Nader** [comment]
**Status:**
Swapna and Anu from CTM are looking into this

**Comment by TracyLinder** [comment]
@Nadin-Nader FYI

**Comment by Nadin-Nader** [comment]
I am looking into this

**Comment by Nadin-Nader** [comment]
I have asked multiple users if they have heard of any applicants complaining that the DS permits are not available online and they have not. I am closing this card. If the issue arises, we will create a new one and reference this one.
