### ISSUE TITLE
Add new fields/values to bike parking collecting feature service

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#6204]
We need to:

- [ ] Add `INSTALLED_BY` field with a domain for the values: 'ATD', 'Contractor'
- [ ] Add value 'Brick Sidewalk` to the field `ROW_LOCATION`

**Comment by alan-deanda** [comment]
@andrewshensky  what is the best way to add fields and values to the new bike parking feature service?

**Comment by andrewshensky** [comment]
@alan-deanda you should be able to add the fields and domains directly to the service through AGOL. If open the service page and click the data tab, there will be an option to view fields on the right hand side. If you click that you will have the option to add new fields by using the +Add button on the left side of the page. Once the field is added there will be an option to create a list, that will be the domains you are adding for that field.

**Comment by alan-deanda** [comment]
@andrewshensky will all future schema maintenance happen in AGOL, or will we ever need to refresh or republish the service entirely from Pro? I think it might be useful to document the maintenance strategy on gitbook. There have been cases with the Healthy Streets data where the relates break due to making a change in AGOL and later needing to make changes in Pro. I just want to make sure this won't be the case with this data.

**Comment by andrewshensky** [comment]
@alan-deanda Yeah I think all schema maintenance can take place in AGOL at this point. There are some changes to the data structure that could prompt a republish but adding fields and domains shouldn't impact anything as long as there are not edits to fields linking the main table to the related table.
