### ISSUE TITLE
Consolidate Small Cell Location Data

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6215]
The pole attachments object in the Data Tracker currently has two different location fields.

1. The `locations` object connection
2. A `Location` field on the `pole_attachments` object.

We should stop using the `locations` object connection and enable the Small Cell group to manage location info directly on the `pole_attachments` object. 

Todo:
1. Add `Primary Street` and `Cross Street` fields to the `pole_attachments` object. These should be connections to the `street_segments` object. 
2. Create a new "Add pole attachments" form which enables the user to create a new pole attachment and populate the primary/cross street fields in the same as in the existing [New Location Form](https://builder.knack.com/atd/amd/pages/scene_100/views/view_277/form). 
3. Update the "Edit Pole Attachments" form to include the primary/cross street fields
4. Compare the lat/long values in the connected `locations` records against the `Location` field on the `pole_attachments` object. When records do not match—flag them and ask April which coordinates are correct.
5. Make sure the `Location` field on the `pole_attachments` object is populated for every record
6. Identify records that do not have any location information and ask April to update them.
7. Import the primary and cross street segment IDs from the `locations` object into the corresponding `pole_attachments` field

Clean up tasks:
1. Update the Data Tracker > AGOL etl to use the location information on the `pole_attachments` object 
2. Identify all locations in Data Tracker which exist only for Small Cell—delete them.
3. Remove the "New Pole Attachment" form the Location details page in the data tracker.
4. Delete the connection between `locations` and `pole_attachments`

**Comment by johnclary** [comment]
@dianamartin this is what I think we need to do. It's....a lot! Happy to discuss. cc @amenity

**Comment by amenity** [comment]
@johnclary — this is all in prep to remove this data from Data Tracker? 🤔

**Comment by amenity** [comment]
Opting for #6264 instead.

**Comment by amenity** [comment]
We won't have to do this extensive cleanup, but will want to remove the small cell tracking functionality from Data Tracker if DSD's GIS team can handle it on their own.

**Comment by amenity** [comment]
Summary from @johnclary via Slack
