### ISSUE TITLE
ROW Permit Processes Technical Analysis

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6216]
### The final analysis lives [here](https://drive.google.com/file/d/1lN-Z0Tn6uoK9cfN4CfD_a11V6RyuOjZT/view?usp=sharing)
On the ROW Permitting Metrics Project, we're unsure of which approach to take with the intake process:
- Option 1: Reuse existing processes where they exist, and update the attempt types...
- Option 2: Create a new process to use across all permit types

We're unsure which of these options is best; we'd like to ask Subha to analyze the existing processes and make a recommendation or at least present findings to help us make this decision. Vish said he can work with Subha on this and assist with documentation.

**Comment by TracyLinder** [comment]
### Goals
For each folder/permit type, analyze the existing processes to determine what actions are the attempts for each process performing.

- RW - TURP
- RW - FILM
- RW- Street Vendor
- RW - Valet Temp
- RW - Valet Annual
- RW - Valet Operator 
- EX 
- DS

**Comment by TracyLinder** [comment]
@Nadin-Nader or @vschandramouli - After speaking w/ Subha about this can you please comment with an estimate for how long this will take?
Thank you!

**Comment by Nadin-Nader** [comment]
@TracyLinder Had the meeting with Vish and Subha this morning. We decided that she would start looking into the Folders with the Web Acceptance process first. Since the users usually use the web acceptance process for everything, we want to see what may need to be done to modify it. She will then move on to the others. Vish is going to supply her with the process names. 
She will start the estimate once Vish supplies her with the process names

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader  @vschandramouli 
As per the Vish's processes' list, will take 3-4 days overall to come up with the actions in each WAA & Intake/review process.

**Comment by TracyLinder** [comment]
**Update w/ all of the current review processes:**
<img width="620" alt="Screen Shot 2021-06-01 at 2 51 40 PM" src="https://user-images.githubusercontent.com/49930868/120382149-eaa7d180-c2e8-11eb-8444-3ad74706a877.png">

**Comment by Nadin-Nader** [comment]
Subha is still working on this

**Comment by SubhaShroff** [comment]
### Status:
Done with 1st set of processes. After finishing with #6021 tomorrow, I will be picking the processes @TracyLinder has listed.

**Comment by SubhaShroff** [comment]
List provided by Vishwa:
•	RW – TURP
o	Web Application Acceptance Process
o	TURP Permit Intake Process
•	RW – FILM
o	Web Application Acceptance Process
•	RW- Street Vendor
o	Web Application Acceptance Process
o	Vendor Intake Process
o	Vendor Review Process
•	RW - Valet Temp
o	Web Application Acceptance Process
•	RW - Valet Annual
o	Annual Valet Intake/Review Process
o	Web Application Acceptance Process
•	RW - Valet Operator
o	Valet Operator Intake Process
o	Valet Operator Review Process
•	EX
o	Web Application Acceptance Process
o	Excavation Intake/Review Process
•	DS
o	Web Application Acceptance Process

**Comment by TracyLinder** [comment]
We need to add analysis for process 50520 TURP Review
FYI @SubhaShroff

**Comment by SubhaShroff** [comment]
@TracyLinder Yes, as you mentioned permit status change to 'Active' triggers the inspection processes insertion in the permits(for both DS, EX).

**Comment by SubhaShroff** [comment]
> Are you (Subha) able to identify what triggers the DS and EX folders to insert the folder inspection processes?
> - We think it happens when the folder is issued.

@TracyLinder Yes, as you mentioned permit status change to 'Active' triggers the inspection processes insertion in the permits(for both DS, EX).

**Comment by SubhaShroff** [comment]
The latest list of processes analysis:
[#6216 - Processes-Actions.xlsx](https://github.com/cityofaustin/atd-data-tech/files/6695123/6216.-.Processes-Actions.xlsx)

**Comment by TracyLinder** [comment]
@SubhaShroff  please Add analysis for Right-Of-Way Admin (50075)

**Comment by SubhaShroff** [comment]
@TracyLinder  Right-Of-Way Admin (50075) is done. Here is the updated document.
[#6216 - Processes-Actions.xlsx](https://github.com/cityofaustin/atd-data-tech/files/6696962/6216.-.Processes-Actions.xlsx)

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader I found the code for DS Permitting Review(50730) and updated it in the document.
[#6216 - Processes-Actions.xlsx](https://github.com/cityofaustin/atd-data-tech/files/6705211/6216.-.Processes-Actions.xlsx)

**Comment by SubhaShroff** [comment]
### Status:
The latest analysis document is available for review.

**Comment by Nadin-Nader** [comment]
@TracyLinder this is ready for you

**Comment by SubhaShroff** [comment]
### Status:
The analysis is ready.

**Comment by TracyLinder** [comment]
I filed the analysis [here](https://drive.google.com/file/d/1lN-Z0Tn6uoK9cfN4CfD_a11V6RyuOjZT/view?usp=sharing).
closing

**Comment by TracyLinder** [comment]
Spoke w/ stakeholders about this today; staff will pick this back up while we work on COS auto-payments
