### ISSUE TITLE
(Biweekly) Project Meetings: ROW Permitting Metrics  

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6218]
### Issue to document all notes from all project meetings.

**Who:** Project core & support teams.
    - Tracy, Vish, Nate, Paloma, Izzy, Kim, Subha, Sree
**When:** Biweekly, Tuesdays @ 2pm

**Comment by TracyLinder** [comment]
### Notes from meetings prior to creating this issue:

- #4414 Initial Scoping on 11/6/20
- #5734 Project Kickoff on 4/14/21
- #6118 5/18/21

**Comment by TracyLinder** [comment]
### 6/1/21 

**Agenda:**


Updates:
- [ ] #6120 Documenting review deficiencies
    - [Spreadsheet](https://docs.google.com/spreadsheets/d/1p2wmB5qWHac3iiWVMwzSxPdatKadeTmmz9CBIFKmjrE/edit#gid=0) 
- [ ] #6119 Analysis of current permit intake/review processes
    - #6216 Technical Analysis

**Comment by TracyLinder** [comment]
**Reviewed possible attempt types**

Want to discuss internally w/ the team and then provide us more feedback.

![Screen Shot 2021-06-01 at 2.37.09 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/093a5ef1-c5cd-47f1-9869-6393a0f3a3c7)

**Comment by TracyLinder** [comment]
# 6/15/21

**Review Previous Action Items**
- ROW: Review attempt names & deficiencies with staff during their weekly Monday meeting on 6/7
- DTS: Perform process analysis #6216

### Notes


### Action Items

**Comment by TracyLinder** [comment]
### 11/2/21

We re-grouped to determine if we're ready to continue with this project. We decided we're going to keep it in the backlog until all Cost of Service deliverables are done. In the meantime ROW staff will be working on #6453 Deficiency types

**Comment by TracyLinder** [comment]
### 11/16/21

No progress made since last meeting. We decided to keep this project backlogged until we've finished our code freeze release. Picking back up in January.

**Comment by KyleErich** [comment]
Closing this card. These biweekly project meetings have not been occurring over the last couple years, which negates the need for this notes card.
