### ISSUE TITLE
Remove password reset UI from account page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6220]
This is confusing, we want everyone to sign in w/ SSO, see #6219 
![Screen Shot 2021-05-26 at 12 26 44 PM](https://user-images.githubusercontent.com/1463708/119705289-2c82d480-be1e-11eb-83b4-0ced417842b3.png)

**Comment by sergiogcx** [comment]
There is a PR now:
https://github.com/cityofaustin/atd-moped/pull/349
