### ISSUE TITLE
[Bug] Map error handler not rendering on projects without locations

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6228]
On Production, all existing project geometries are gone. 
- [Map error handler](https://austininnovation.slack.com/archives/CHZE6BC6L/p1620345836251200) not rendering on projects without locations
- Cannot add new locations to a project, e.g. https://mobility.austin.gov/moped/projects/31
![Screen Shot 2021-05-26 at 4 10 43 PM](https://user-images.githubusercontent.com/1463708/119735310-be500900-be41-11eb-8389-abbeb057a032.png)

**Comment by sergiogcx** [comment]
It will not be difficult to show the placeholder instead.

**Comment by sergiogcx** [comment]
@amenity So for now I've updated all the production projects to be editable by adding a feature. I can replicate the conditions in staging or locally to mimc this error in those environments while making all the maps editable.

**Comment by amenity** [comment]
@sergiogcx - thanks! This is working super. Should I create  the map-error-handler-not-rendering into another bug report?

Side note: It appears I'm able to delete all locations now, though. Earlier, we prevented users from doing this: https://github.com/cityofaustin/atd-moped/pull/265 ... Should I make a bug report for this?

**Comment by sergiogcx** [comment]
Ah, yes there is a PR, test using moped-test:
https://github.com/cityofaustin/atd-moped/pull/330
