### ISSUE TITLE
[Bug] Map is no longer zooming to full extent in the project Summary tab

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6231]
The map on the Summary tab used to zoom so that the full extent of a project was visible. Now that's not working. 

Example:
https://user-images.githubusercontent.com/1463708/119766671-0f302380-be7b-11eb-9461-4d18097f7ead.mov

Example 2:
This one shows that the north/south zoom is working but not the east/west? Or something... it fits when the project is as tall as it is wide. 
https://user-images.githubusercontent.com/1463708/119767727-02143400-be7d-11eb-8999-8f0d7420ab1c.mov

**Comment by sergiogcx** [comment]
I've refactored the map sizing which affects it's zoom behavior; please test on your end now.

PR:
https://github.com/cityofaustin/atd-moped/pull/326

Live Demo:
https://deploy-preview-326--atd-moped-main.netlify.app/moped/projects/269
