### ISSUE TITLE
Sprint Review with stakeholders

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#624]
[Presentation deck](https://docs.google.com/presentation/d/16A8vnQZa8AAjV3mz4DW0oZocnZVWwtfks7joFi_4Ank/edit#slide=id.g568eddf782_2_82)

- Work done til date
- Demo
- Questions
- Prioritize and up next

### Meeting Info
Scheduled: 10/16/2019

### Attendees
- Jen Duthie
- Patrick Oborski
- John Clary
- Surbhi Bakshi
- Amenity Applewhite
- Diana Martin

**On the Phone**
- Lewis Leff
- Randy

**Comment by amenity** [comment]
@SurbhiBakshi - was this our meeting last week?

**Comment by SurbhiBakshi** [comment]
@amenity , yes, I am going to close this issue.

**Comment by dianamartin** [comment]
## Notes with stakeholders
Showing the home page

Lewis: creating the shifts and assignments
Randy: reviews assignments and assign officers
Officers: view shifts, add citations

**Comment by SurbhiBakshi** [comment]
Problems putting in cross streets

**Comment by amenity** [comment]
(Additional notes in the slide deck).
