### ISSUE TITLE
[Enhancement]: Nest user avatar within sidebar

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6245]
- Nest user avatar at top of sidebar and hyperlink it to the account page. Include the user name and a separator below that nav item. 
- Remove "Account" navbar item

As part of this work we should refactor our `Avatar` code to be consistent with how Avatar's are constructed across the app. E.g., the Project Activity Log and the Profile page.

<img width="1440" alt="119903178-eefd7480-bf0d-11eb-8984-2cf3f700ef0e" src="https://user-images.githubusercontent.com/14793120/119910839-a51c8a80-bf1d-11eb-9811-139c98c99547.png">

**Comment by johnclary** [comment]
@patrickm02L will mockup top nav alternative.

**Comment by patrickm02L** [comment]
@johnclary Created the mock up and new issue #6585

**Comment by amenity** [comment]
@johnclary @patrickm02L - are we good to close this one out in favor of #6585?

**Comment by patrickm02L** [comment]
@amenity Yes, I think so. If we're going with the new header layout.

**Comment by johnclary** [comment]
so my beautiful mock-up for for nothing???

**Comment by patrickm02L** [comment]
You should know I took inspiration from it now for the mobile version of the new header.

It is a work of art. I'll put it on my refrigerator!

**Comment by amenity** [comment]
Actually, @johnclary I'd be down to reopen this and keep in the backlog with @patrickm02L's approval. We do want users to be able to access their account settings from mobile and I like the super-simple avatar-le mobile menu.
