### ISSUE TITLE
Document Knack to Power BI process 

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#6247]
[Document](https://docs.google.com/document/d/1yJvEGIV5zvb6NjqW8x0rZEPXng5OUW1p64KqZmoDkiE/edit?usp=sharing)

**Comment by amenity** [comment]
@SurbhiBakshi is going to do a knowledge-transfer meeting with @dianamartin and @ChrispinP this week.
