### ISSUE TITLE
BUG: After Creating a child RW-Parking from an SE folder, The system inserts an unwanted Electrical Permit fee

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#6252]
When the system to auto-creates a child parking permit folder, when the folder info 'Parking Reservations' value is 'Yes' on an SE folder, the system is inserting an unwanted Electrical Permit fee (50010). See #3640 for more history.

**Stakeholder:** Maria A
**DTS Manager:** Nate

**Acceptance Criteria:**
-  This only applies to the newly created child RW-Parking Folder from card #3640
-  Electrical Permit fee (50010) needs to be removed

**Comment by Nadin-Nader** [comment]
**Status:**
Sree is looking into this at the moment

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder - As of now this is card is on hold; Could not replicate the issue in DEV/TEST so, asked for example folders to do further analysis. Nadin sent an email to Maria until she gets back on that it will be on hold.

**Comment by Nadin-Nader** [comment]
Got on a call with Maria and Sree to see what was going on with the electrical fee being added but she was not able to recreate the insertion of the fee.
We decided to close the card and she will keep an eye out to see if it happens again. If it does, we will revisit this card and issue.
