### ISSUE TITLE
Cleanup Folder 'Run Procedure' Menus (Fee Tab) (SR) (Deploying to DEV)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6254]
### Refer to #8687 where the work was recorded for this request. 

-----
**Stakeholders:** Paloma, Kim, Izzy

**Acceptance Criteria**

-The acceptance criteria provided below applies for RW, DS and EX Folders.
-The fees mentioned below need to be removed from the 'Insert and Run Procedure' menu option in the fee tab of the folders mentioned.

RW -
License Agreement Fees
Film Fees
Investigation Fees (If there are multiple, all of them should be removed)
RW - New folder 
Residential Parking Decal and Hangtag
TURP - Application Fee
Gate Fees 
Plan Fee
Sound Impact evaluation Fee
Sound Permit fee
Street Event Tier 1 fees (there are multiple, all of them should be removed)
Street Event Tier 2 fees (there are multiple, all of them should be removed)  
Safety Inspection Fee 
Sidewalk Cafe 1 Annual Payment
Sidewalk Cafe Processing Fee 

EX -
Barricade Fees
Default New EX Folder Fee
Investigation fees (If there are multiple, all of them should be removed)
Working without valid Permit fee

DS -
Barricade Fees
Default New DS Folder Fee 
Investigation Fees (If there are multiple, all of them should be removed)
Excavation/Concrete Permit Fee (might have already been removed, please confirm)
Work without a permit fee

**Comment by TracyLinder** [comment]
### Changes based on the fee schedule

**Film Fees**
- Remove from RW folder

![Screen Shot 2021-05-28 at 2.08.05 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/200b0b43-db40-4675-96cc-c64e3d5506da)

**Investigation Fees**
- Remove from RW, EX, DS, ECV
![Screen Shot 2021-05-28 at 2.06.38 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/3594d8f7-8785-447f-9728-d2b5b4c717ee)



### Scoping Needed
- Per the fee schedule, Construction Inspection Right of Way Fees are being removed. Do the exist on the fee menus on any of our folders?
![Screen Shot 2021-05-28 at 2.05.22 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/e2457b96-03f3-4672-983d-dd1ca853f810)

**Comment by TracyLinder** [comment]
### Misc. Updates
_We need to review this w/ stakeholders._

**RW**
![Screen Shot 2021-05-28 at 2.45.26 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/220e10aa-510b-4637-b3cf-574c3116e1ef)
![Screen Shot 2021-05-28 at 2.45.55 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/14343258-7a86-4691-8e9c-74cfed022dff)
![Screen Shot 2021-05-28 at 2.46.10 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/12a9bbd3-edd7-41d7-b2c8-e5d3a35324a0)
![Screen Shot 2021-05-28 at 2.46.29 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/79f70b97-3ec7-4a46-8547-cfc561ceace2)
![Screen Shot 2021-05-28 at 2.46.44 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/fdf4ab92-8e75-4b42-b8e5-78f923fc44e5)
![Screen Shot 2021-05-28 at 2.46.59 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/d3f3f9fb-fd27-453e-8722-7ce771856ccb)
![Screen Shot 2021-05-28 at 2.47.11 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/4f4885c0-7704-4b8b-b9bf-136e56c15b12)
![Screen Shot 2021-05-28 at 2.47.24 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/d6da871f-c910-4fa8-b019-88640420c6c1)
![Screen Shot 2021-05-28 at 2.47.37 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/a016e369-d75c-4e61-ab20-d0da1a2f3575)
![Screen Shot 2021-05-28 at 2.47.52 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/0876995b-9e7c-46da-a132-469000d3a63f)




**EX**



**DS**

**Comment by TracyLinder** [comment]
Vish will pick this up for scoping.

**Comment by TracyLinder** [comment]
@vschandramouli please continue

**Comment by vschandramouli** [comment]
Scoping meeting scheduled with Paloma for 3/10/2022

**Comment by TracyLinder** [comment]
### Update

Paloma created a DTS request for this - #8687. I closed it because it's a duplicate of this issue. Here's what Paloma put in the service request form:




> What application are you using?

AMANDA

> Describe the problem.

Cleanup "Insert and run procedure" menu on RW, DS, and EX folders - part two.  Presently working to remove unnecessary fees.  As a next step would like to *ADD* fees which should be in the "Insert and run procedure" menu (that are presently only able to be pulled up via the Insert function).  And then would like to standardized the naming of fees across all of these menus.

> Describe the outcome you'd like to see when this feature is implemented.

This will ensure we are assessing fees accurately and consistently, benefiting our customers and our department.  (Avoids over or under collection.)

> Describe any workarounds you currently have in place or alternative solutions you've considered.

We add fees via the Insert menu but that requires knowing the fee name or code.  Some fees are named so similarly that it can be difficult to discern which is the correct one to assess.

> Requested By
Paloma A.

Request ID: DTS22-103615

**Comment by vschandramouli** [comment]
3/10/22 - Meeting notes. 

The fees mentioned below need to be removed from the folders mentioned. 

RW - 
License Agreement Fees 
Film Fees
Investigation Fees
RW - New folder (would this break something?)
Residential Parking Decal and Hangtag

EX - 
Barricade Fees
Default New EX Folder Fee
Investiagtion fees
Working without vlaid Permit fee

DS - 
Barricade Fees
Default New DS Folder Fee (confirm with Tracy first before removing) 
Investigation Fees
Excavation/Concrete Permit Fee (might have already been removed, confirm)
Work without a permit fee 

Need to schedule a separate scoping meeting for adding fees to insert & run procedure.

**Comment by vschandramouli** [comment]
Meeting notes 3/16 - 

Paloma mentioned she would work on this fee list and share when it is ready.

**Comment by Nadin-Nader** [comment]
@vschandramouli this needs to be re-scoped

**Comment by vschandramouli** [comment]
Meeting set up with Maria on 4/5/23 to confirm special events fees. Review complete for RW DS and EX fees with Paloma.

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - In progress

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0325890**

**Comment by TracyLinder** [comment]
FYI this has been merged with #8687. Closing.
