### ISSUE TITLE
Implement design refinements to project page tab bar

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6256]
1) Remove the CSS overrides to background color and font color in project page tab bar. 
![Screen Shot 2021-07-19 at 4 35 15 PM](https://user-images.githubusercontent.com/1463708/126382625-79c09e01-6847-4a87-a321-8c232995b313.png)
2) Change the selected tab underline to our [Moped primary light color](https://moped.austinmobility.io/moped/dev/devias).
![Screen Shot 2021-07-20 at 2 21 53 PM](https://user-images.githubusercontent.com/1463708/126383963-30d37c8e-cf1d-4271-a681-1d1bf5290130.png)

**Comment by amenity** [comment]
This may need to be addressed at the theme level so it applies to future tab components.

**Comment by patrickm02L** [comment]
Yes, please remove that awful blue. The white background is so much cleaner.

**Comment by amenity** [comment]
Should be full width, stick to the top of the top menu: 

https://user-images.githubusercontent.com/1463708/126593784-39de6ca8-e900-4448-b11c-881193a243b4.mov


https://user-images.githubusercontent.com/1463708/126594102-8376de41-8dc3-4306-9984-333407d4dd0e.mov

**Comment by amenity** [comment]
Will be covered by #6859
