### ISSUE TITLE
Delete "csr_flex_notes" from Signs & Markings - Jul 2021

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#6258]
Received automated reminder to delete flex notes in Signs and Markings Operations PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings/records/objects/object_172

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 05/01/21

Total Records: `14,771`
To Delete: `4,253`
New Total: `10,518`

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/d86a601c-09dc-48cd-83e3-196ed7d6aba0)
