### ISSUE TITLE
[Bug] Moped Production won't fully load (or reloads repeatedly?) when Amenity logs in

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6260]
When I sign in to Production with SSO, the "Projects" page reloads itself over and over. 
https://user-images.githubusercontent.com/1463708/120271516-18e9ca80-c271-11eb-986f-df8f820769bd.mov

- In Firefox I can see a flash of "Network error when attempting to fetch resource". 
- I am able to log in with Test Editor without issues. 

When I sign into Staging, using Test _Editor_ (the Test Admin credentials in 1P aren't working for me)
- Firefox: "Network error when attempting to fetch resource". flashes and then everything loads fine. 
- Safari & Chrome: Reloads once, everything is then fine

Console logs:
[AA-projects-page-bug-PRODUCTION.txt](https://github.com/cityofaustin/atd-data-tech/files/6573614/AA-projects-page-bug-PRODUCTION.txt)
[AA-projects-page-bug-STAGING.txt](https://github.com/cityofaustin/atd-data-tech/files/6573616/AA-projects-page-bug-STAGING.txt)

**Comment by chiaberry** [comment]
This looks like what happens to me on moped-test. Were you able to log out? I have tried to logout from test, but I think the page reloads too quickly for it to go through. I've only tried it on Chrome. 
![2021-06-01 04 05 06](https://user-images.githubusercontent.com/12474808/120298286-93294780-c28f-11eb-8e09-105f5fd52ccb.gif)

**Comment by sergiogcx** [comment]
It appears user accounts were deleted accidentally or unknowingly, we need to be careful whenever we use SQL directly or migrations. 🙏 🙏 🙏  Recreating the user entries in production solved the problem.
