### ISSUE TITLE
Update TIA Email Documention

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6275]
The documentation lives in the TIA folder in our drive.

**Comment by ChrispinP** [comment]
Updated Links for the approve/reject submission emails.

@TracyLinder Should we re-add these two emails when a reviewer creates either a scope submission or submission record themselves?
![image](https://user-images.githubusercontent.com/67915167/120858865-090c0800-c549-11eb-9149-f03cabfe2e95.png)

**Comment by ChrispinP** [comment]
@TracyLinder forgot to ask about this one. Should we re-add these two emails or is this good to close with no updates needed?

**Comment by TracyLinder** [comment]
@ChrispinP yes, please add those emails.

**Comment by ChrispinP** [comment]
Spreadsheet and links updated: 
![image](https://user-images.githubusercontent.com/67915167/125828199-dced169e-383b-4802-8491-767c63dafb6b.png)

**Comment by ChrispinP** [comment]
Email Templates are now also updated both in app and on the google doc. We may need to make some tweaks as Reviewers use the system. Language and fields have been updated to be more consistent.

complete, closing
