### ISSUE TITLE
Update "Working Remotely" section of ATD Staff Resources wiki

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6282]
We want to be able to direct new DTS staff to a section [here](https://app.gitbook.com/@atd-dts/s/atd-staff-resources/working-remotely/getting-started) to do all the things necessary to do remote work. 

Needed for Janet and Patrick's first day, 6/7.

---
To include ... (Stuff I'm deleting from the onboarding materials in the DTS wiki)

- [Fill out Remote Access Request Form](https://apps.austintexas.gov/helpdesk/remote/) 
- Submit [Telework Request](https://atd.knack.com/hr#new-telework-request/)

VPN & Remote Access
-----------------------

You need to be on the City of Austin internal network to access various resources such as shared network drives, the HR Portal, the original CitySpace, and many City of Austin Sharepoint sites.

-   CiscoAnyConnect VPN is the client we use to remotely connect to the City network from a Mac.

    -   [Installer](https://drive.google.com/file/d/1YJFvFCGJIbXhgnl_omWwTGQR2dpmMyAo/view?usp=sharing)

    -   [Instructions for installing and configuring to work in OSX Catalina](https://docs.google.com/document/d/1_RoFPflbpzvWOuSq7g2WbNidgPkbWdTmIoa4Fftf94Q/edit#)

-   CTM Help Desk [Remote Access Request Form](https://apps.austintexas.gov/helpdesk/remote/)

Use of personal devices
---------------------------

If you use your personal computer for work at the any CoA office be advised that you should never directly connect to the CoA Ethernet network. You can connect to the CoA internal network via VPN when necessary. CTM runs occasional security scans for devices that shouldn't be on the network and if they discover your personal computer, they reserve the right to take your computer, run scans, and review files.

**Comment by dianamartin** [comment]
@amenity I updated the "ATD Staff Resources" wiki and the "DTS Resource Index". I went through most all the links and update any broken or old links. Let me know if you need anything else modified.

**Comment by dianamartin** [comment]
Amenity said
>At a glance, they look fantastic. thanks so much
