### ISSUE TITLE
Update language on RPP Home Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6289]
Can we change the language at the top of the Home Page to read: 
Please be advised that the Parking and Mobility Services Permitting office (1501 Toomey Rd.) is not providing walk-in services at this time. All requests are being handled by appointment only. Please see below for additional details. 
-Permitting staff is in the office everyday M-F between 8a-3p. 
- Applicants cannot enter the building but we can assist all customers with curbside services. 
-  Permits will be issued by regular mail unless otherwise requested, with payment available by phone.

**Comment by ChrispinP** [comment]
I have updated the RPP Portal page, how does this look?
![image](https://user-images.githubusercontent.com/67915167/120856032-d52ee380-c544-11eb-8df2-7e6bcbd01646.png)

**Comment by moorerst** [comment]
confirmed with RPP staff the changes look good. Closing issue
