### ISSUE TITLE
Update RPP Submitted - Pending Review email notification

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6290]
Modify items below From:

- Your application will be reviewed by ATD staff, please allow 7 to 10 business days from 01/04/2021 13:01 for a review to be completed.

- You will receive an email within 7 to 10 business days and instructions on how to pay for your permits/passes.

To:

- Your application will be reviewed by ATD staff, please allow 2 to 3 business days from 01/04/2021 13:01 for a review to be completed.

- Once your application is approved you will receive an email with payment instructions.

**Comment by ChrispinP** [comment]
Updated Application Confirmation email
![image](https://user-images.githubusercontent.com/67915167/120856827-fcd27b80-c545-11eb-8c17-1f03a09e43e9.png)

**Comment by moorerst** [comment]
Updates made as requested by RPP staff. Closing issue
