### ISSUE TITLE
Meeting w/ April S. to understand Comprehensive Small Cell workflow

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6303]
April said 6/7 works for her. I scheduled a meeting for 6/7 at 9 am.

**Comment by dianamartin** [comment]
rescheduled for 6/8 at 2 pm

**Comment by dianamartin** [comment]
# Diana's Notes

Small Cell

John M. - new boss for small cell
Using Microstrategies
Microstrategies - map

Small Cell - web application (DSD)

Would prefer to enter into AMANDA  
Have XY

- Smart Sheets
- Data Tracker
- AMANDA

## Process 
- Application comes through AMANDA
- site plans PDF attached
- customer entry for XY coordinates (not required currently) - would like to make required entry
- enter into Smart Sheet - purely internal tracking
  - bc were using it in AE (Using Google Fiber project)
  - AE was using it
  - using it primarily as spreadsheet (multiple editor, cloud storage)
 - A lot of city is using smart sheet, bc they have enterprise account
- Then open up Data Tracker (mapping purposes for public consumption)
  - Cut and paste from Smart Sheet to Data Tracker
  - AE opened pole 

Weekly update - if not live
Main goal: have a public facing map for small cell reference

What kind of reporting does Smart Sheet? 
site corrections - throws number off, this is fixed now.
- children folders
- now it's in the parent folder

**Comment by johnclary** [comment]
thanks, @dianamartin !
