### ISSUE TITLE
Bug: Filters do not stack up correctly

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#6308]
Currently, we cannot apply two or more filters on a single field. For example, if we want to search for a project description that contains the word `Lamar` and also contains the word `Koenig`, the filters will ignore the first word and use only `Koenig`.

This is likely a data structure problem caused by the way the filters being stored using the name of the field, so when a new filter is added on top of another on the same filed it will override whatever was already there.

**Comment by amenity** [comment]
Thanks, @sergiogcx! @chiaberry - will you size, plz?🙏👕

**Comment by chiaberry** [comment]
The filters should stack as "and" and not "or" right?

**Comment by amenity** [comment]
@chiaberry I think so. I have a feeling @johnclary has thoughts. 

In sprint planning, @sergiogcx suggested we allow the user to choose and/or. Shall we make an issue for that enhancement  @johnclary? I think it is going to be useful down the line, for sure.
