### ISSUE TITLE
Testing trigger button default look in new builder

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6314]

**Comment by dianamartin** [comment]
I tested in my sandbox what it would be like to add a trigger button on the details of page
- When I added the "trigger button", the text came in as normal font, not bolded, not underlined, did not look like a button or outline

**Comment by amenity** [comment]
Thanks, @dianamartin @ChrispinP. I think it makes sense not to have it as a prominent button and would recommend leaving as the default, unstyled w/o custom HTML in TIA. cc/ @TracyLinder.  

@ChrispinP - can you remove any custom HTML from the elements in the next test instance, with the exception of those that are standardized in other Knack apps?
