### ISSUE TITLE
Host a Data Needs Workshop for ATD

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#632]
We've been tasked by exec leadership to host a data needs workshop with ATD staff. The workshop will seek to identify unmet and future data needs, so that we can better plan for, fund, and address these needs in the long term.

The workshop can take whatever form we like. I'll setup a planning meeting.

**Comment by amenity** [comment]
@johnclary - do you have a sense of whether this workshop is still desired?

**Comment by johnclary** [comment]
#icebox

**Comment by johnclary** [comment]
#closed
