### ISSUE TITLE
Publish parking revenue data to open portal

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6320]
Per Rob, we should work with Parking Enterprise (Joseph, Jason R) to make their parking revenue and utilization data public. 

The data currently lives in ArcGIS Online. We should:
- Work with PE to define which data to publish
- Work with our dev team to implement a publishing script from AGOL to Socrata

**Comment by johnclary** [comment]
@SurbhiBakshi can you take the lead on this next sprint? First step will be to meet with Joseph A.

**Comment by SurbhiBakshi** [comment]
@johnclary, sounds good

**Comment by SurbhiBakshi** [comment]
Meeting with Joseph and Jason scheduled for June 22nd.

**Comment by SurbhiBakshi** [comment]
@jaime-mckeown - could you point me to AGOL feature services for parking revenue and utilization.

**Comment by SurbhiBakshi** [comment]
As per @jaime-mckeown only revenue data is available in AGOL

**Comment by SurbhiBakshi** [comment]
Data in AGOL
[Monthly Time Series by Zone](https://austin.maps.arcgis.com/home/item.html?id=b5131d7791ea4e789faaf93f3df58a15#data)

**Comment by SurbhiBakshi** [comment]
-  @johnclary - My notes for the meeting are [here](https://docs.google.com/document/d/1_FRAK1DSR_Z_JJ4MdqGN3jQXyWTt_C_cYGUlEO9Pdxw/edit?usp=sharing). 

 - Joesph will contact @jaime-mckeown for some GIS help with the datasets before I can pick this issue up again.

**Comment by johnclary** [comment]
This will be covered by #7601
