### ISSUE TITLE
New Folder Info: Secondary?

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6321]
### New RW-TURP & EX folder Info: Secondary?

**Stakeholders:** Kim, Paloma

**Acceptance Criteria:**
- A new info field needs to be added to EX and RW-TURP folders. 
- Info Description: Secondary?
- Info type: Boolean 
- Default Info Value: 'No'
- Info should be Required for Insert and Required for Issue (Is mandatory for folder creation & issuance)
- "Secondary?" info should be published on Portal for all subtypes 
- The new Info field must be displayed on portal as a mandatory field for EX and RW-TURP applications
- The new info field must have the following help text on Portal: 
An agreement with ATD management is required to obtain these permits. These permits are secondary in nature to other permits.  Accordingly, if another permitted activity needs access, crews or contractors will be required to vacate the ROW as promptly as is reasonable to safely return the ROW to the traveling public (approximately 15 minutes).

**Comment by TracyLinder** [comment]
@Nadin-Nader can we pull this on deck as soon as the AC is ready please?

**Comment by vschandramouli** [comment]
Scoping meeting scheduled for 6/29. Will update AC as soon as it is done.

**Comment by vschandramouli** [comment]
Updated Acceptance Criteria. This item is ready for Backlog.

**Comment by Nadin-Nader** [comment]
##  Assigned to Sreelatha

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Analysis and Development is in Progress

**Comment by vschandramouli** [comment]
@Sreelatha-BlazeKannan  Help text on the EX and RW-TURP Permits are currently displayed like shown below:
![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/745f669e-0edb-46f9-9d5e-6c344fa0b3e6)

We would need the new info to have help text displayed the same way. Let me know if you have any questions.

**Comment by vschandramouli** [comment]
@Sreelatha-BlazeKannan The info field will need to be part of the Project Information info group. There are currently more than 1 'Project information' Info groups, so here is a screenshot with the highlighted section for better clarity. 

![MicrosoftTeams-image (27).png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/fdc09142-5166-4cf0-b915-5a11e6b1d44a)

![MicrosoftTeams-image (28).png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/6dda7ce5-804f-4079-b8ca-97bb2688457e)

**Comment by Nadin-Nader** [comment]
## **Status:**

Sree is still working on the development

**Comment by Sreelatha-BlazeKannan** [comment]
**Status **
@Nadin-Nader , @TracyLinder - Development completed, but can't be moved or tested as there is a conflict with lookup table 83735 update. #5961 must be deployed before this can be moved.

**Comment by TracyLinder** [comment]
@Nadin-Nader I'm speaking w/ Paloma about this and there's concern about private contractors being able to view this info during the portal application. We may need to update AC to say "Do not show info on application if subtype is private contractor". Let's talk about this.

**Comment by TracyLinder** [comment]
@Nadin-Nader @Sreelatha-BlazeKannan 
If possible, Paloma would like the Secondary info not to show on the portal application if the application is for Private Development. Is this possible?

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder updated AC with:
"Secondary?" info should NOT appear on the portal application if the application is for "Private Development (PVT)"

**Comment by TracyLinder** [comment]
**Status:**
Development is done. Pending #5961 to move through DevOps before we can promote this.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Clarifications received on 

AC - "Secondary?" info should NOT appear on the portal application if the application is for "Private Development (PVT)"

as this cant be excluded only in portal. Tracy asked to make it appear for all subtypes in both portal n back office for EX.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  -  #6321 DEV Deployment plan sent. Kindly approve and create task id for me.

**Commit ID’s 
2132d4580c6c 
84eb2e0c40b4

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV. Please UAT

**Comment by Nadin-Nader** [comment]
@Nadin-Nader UAT on DEV

**Comment by Nadin-Nader** [comment]
## Approved for TEST deployment🙌

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - 
Submitted TEST DP for #6321 card. Please approve and create task id for me. 
Here is the commit ID’s –
2132d4580c6c
84eb2e0c40b4

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been sent to the DevOps CM Team to deploy to TEST under **SCTASK0164364**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy to TEST under **SCTASK0164364**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been deployed to TEST by the DevOps team. 
Ready for TEST UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested and working as expected. 

![image](https://user-images.githubusercontent.com/44907715/132911623-0ef67299-daa7-4a14-ab6e-dd0365492eb5.png)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan lets get this on PROD

**Comment by Nadin-Nader** [comment]
## **Approved for PROD Deployment🎉🙌‼**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per PROD approval, #6321 PROD Commit Deployment Plan sent on 09/16/2021. 
Please create task id for the below commit Id’s –
2132d4580c6c
84eb2e0c40b4

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this to the DevOps CM Team to deploy to PROD under **SCTASK0167851**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy to PROD under **SCTASK0167851**

**Comment by Nadin-Nader** [comment]
@TracyLinder @Sreelatha-BlazeKannan this has been deployed to PROD. I will send the stakeholders an email and close the card

**Comment by Nadin-Nader** [comment]
Email sent:

> Hi Team,
> 
> Hope you are all doing well. I was reaching out to inform you that the New Folder Info: Secondary ? Card # 6321 is now on PROD. I will go ahead and close this out. If anything comes up, please do not hesitate to send me an email or chat.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services
> ————————————————————————————
> transportation.data@austintexas.gov 🚦 austinmobility.io
