### ISSUE TITLE
Update RW-TURP WorkTypes (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6322]
# CANNOT GO TO PROD BEFORE 10/1

### Update RW-TURP Worktypes to match new EX subtypes

**Stakeholders:** Paloma, Kim, Izzy

_**Cant go into PROD til after 10/1, can mess with current fee logic**_

**Acceptance Criteria:**
- Work types for Right of Way Permits with Temporary Right of Way use subtype need to be changed to the items below. Work types that currently exist for RW-TURP permits will need to be removed and replaced with the following. 
-- Austin Energy (AE)
-- Austin Transportation (ATD) 
-- Austin Water Utility (AWU)
-- Corridor Program Office 
-- Franchised Utility - Gas Utility
-- Franchised Utility - Other Electric Utility 
-- Franchised Utility - Telecommunication/Cable Utility 
-- Other City Departments
-- Private Development 
-- Project Connect 
-- Public Works Department (PWD)
-- Watershed Protection Department (WPD)

- Legacy records need to be maintained with previously used work types. However, the previous work types should no longer be available to select when applying for new RW-TURP Permits through Back Office or Portal.

**Comment by vschandramouli** [comment]
Updated Acceptance Criteria. Moving item to Backlog.

**Comment by TracyLinder** [comment]
**Update:**

- I'm moving this On Deck so it can be assigned to Subha or Sree, and they can begin their analysis. 
- Development should not start until review of the analysis w/ BA.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  @vschandramouli After the analysis, I have following concerns/questions, sent an email also:
1.	The same issues can arise in 6322 as in #2397 with old TURPs that are with old set of worktypes. 
2.	When the user opens the permit either in BO or Portal, the old TURPs still need old set of worktype to be displayed,. If we remove the old ones,  it may not display the work types that are removed.(but the data exist on the Database).
3.	The above same questions apply for the old TURP workflows(that includes the processes, fees, any email notifications, documents, attachments etc.,) on both BO & Portal. 
4.	 The each new worktype going to be added to TURP, would need the detailed flow defined.
5.	The other existing functional dependency/connection of the old worktypes, I could identify from the code is as follows:
a.	50515 - Private Short-term
Issue RW TURP –-> Permit Extension Process is deleted. 
Info Validation - May have to remove ‘#of days for Extension’(75995) info validation for this worktype.
Info Validation - Based on END DATE & START DATE, the permit is updated with the old work types for all three work types.

b.	50530 - Historical Landmark
The following fee insertions might have validations related to the worktypes 50515, 50520, 5030.
50215, 50174

**Comment by SubhaShroff** [comment]
## Status:
Need more details and discussion, my review notes is given above.

**Comment by TracyLinder** [comment]
We will meet w/ Gita next Tuesday to review our options & hopefully answer Subha's questions.

**Comment by TracyLinder** [comment]
Meeting with Gita rescheduled for 8/23

**Comment by TracyLinder** [comment]
Sree asked Subha to create the work types in Dev so Sree can move forward #6844

**Comment by SubhaShroff** [comment]
@TracyLinder  @Sreelatha-BlazeKannan 
Created new worktypes and added the above listed new Work Types to RW-TURP on Localhost. @Sreelatha-BlazeKannan You are good to go for 6844.
@Nadin-Nader  @vschandramouli

**Comment by SubhaShroff** [comment]
### Status:

- The work types are added on localhost.
- Code check is done. As suggested by Gita, looking out the configurations and batch jobs code as well, for old TURP worktypes.
- @TracyLinder  would give me/walk through the workflow for each new WORKTYPE.

**Comment by SubhaShroff** [comment]
### Status:
Waiting on @TracyLinder  to update with the workflow for each new WORKTYPE.

**Comment by TracyLinder** [comment]
@SubhaShroff can you please send me the list of default infos for the TURP permit please?

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  as per the flow you have provided, I tested for Back Office in localhost. And it looks good. I would need to move it to DEV to test the Portal part. Before that, I want to check with the Portal Street Info page for the new work types and do changes in the code accordingly.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0167673 - is submitted for DEV Deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0168173 -  is submitted for DEV deployment of the fix.

**Comment by Nadin-Nader** [comment]
**Status:** 
Waiting on DevOps CM Team to deploy to **_DEV_**

**Comment by TracyLinder** [comment]
UATers: Izzy, Kim, Evelyn, Paloma, Peter

**Comment by TracyLinder** [comment]
### Next Steps
1. Nate & Subha to UAT in DEV
2. Promote to TEST
3. ROW staff to UAT w/ Tracy's testing plan
4. Promote to Prod or rollback for fixes.

**Comment by TracyLinder** [comment]
Let's try to get this to test by this Thursday 10/23

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  Tested this ticket on DEV BO & PIPS Portal(ABC portal has login issue). Its for your UAT. Kindly let me know if I can promote it to TEST.
@Sreelatha-BlazeKannan  The path is clear for you( for 6844) till TEST. 🙃👩

**Comment by SubhaShroff** [comment]
### Status:
I finished testing and ready @Nadin-Nader 's UAT on DEV.

**Comment by Nadin-Nader** [comment]
Tracy will be UATing this today 9/22/21

**Comment by TracyLinder** [comment]
### Update

We have been unable to UAT on DEV because of Portal work. Let's go ahead and move this to TEST so we can continue w/ UAT.

**Comment by TracyLinder** [comment]
@SubhaShroff & @Nadin-Nader can we get this deployed to TEST ASAP please?

**Comment by SubhaShroff** [comment]
@TracyLinder  sure I will get submit the request. 
@Nadin-Nader

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  SCTASK0169103 is the ServiceNow request submitted for TEST deployment.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to TEST please UAT

**Comment by Nadin-Nader** [comment]
**Status:**
Ready for UAT on **_TEST_**

**Comment by TracyLinder** [comment]
### My UAT Results

- I tested Private Development, ATD, and Franchise. All 3 tests went well & no bugs were found.

**Comment by TracyLinder** [comment]
### APPROVED FOR PROD

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  SCTASK0170270 - is submitted for PROD deployment.

**Comment by Nadin-Nader** [comment]
**Status:**
This has been deployed to PROD
