### ISSUE TITLE
Meeting: HR forms for on-boarding process

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6325]
- Meeting to discuss knack forms for our on-boarding process.

- Draft forms located: `G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\app_Human_Resources_Manager\reference`
  - 30 Day Supervisor Survey
  - 90 Day Supervisor Survey
  - 120 Day Supervisor Survey
  - Employee 30 Day Feedback

- Meeting scheduled for 6/16

**Comment by dianamartin** [comment]
Meeting scheduled for 6/16 at 1:30 pm

**Comment by moorerst** [comment]
Attendees: Nathan, Linda, Diana, Stephanie
Discussed different tools for forms intake/management
Diana presented a comparison matrix

- Their main goals for forms are:
keep it simple
centralized place to store forms
knack is very user friendly
 
- Requirements:
keep survey feedback private only HR staff should have access to view form
All new hire employees are required to complete at 30/60/120 days
HR person will track when the new hire needs to complete the survey and notify employee - may be an option to automate???
should be connected to the employee record so we can see all forms completed for an employee

- Next Steps:
Build 4 onboarding forms in Knack
Move the NEO Feedback form from MS Forms to Knack - do not need to export existing data

**Comment by dianamartin** [comment]
# Diana's Notes

Goal to centralize all forms that supervisors/managers and employee fill out
Learned that the forms will be required as it's a new onboarding process:
- 30 Day Supervisor Survey
- 90 Day Supervisor Survey
- 120 Day Supervisor Survey
- Employee 30 Day Feedback
- MS Form "ATD New Employee Orientation (NEO) Evaluation

HR would like these 5 forms to be digitized in the Human Resources application. I feel like it could be done in one sprint. Some testing needs to be done after form creation, but it's pretty straight forward.

**Comment by dianamartin** [comment]
Stephanie said she'd create new issues for the form configurations
