### ISSUE TITLE
Error when entering 3 character license plate number in RPP

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6329]
Resident getting Invalid License Plate number when entering a 3 digit personal license plate number.

![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/fa879116-84c2-44e9-8b6d-3111238becf2)

**Comment by moorerst** [comment]
Specialty, Handicap, and Govt all have a minimum of 5 characters

we previously accepted his 3 digit license plate on app 2020-1154. Looks like that must really be his plate #, 
Yea, this is definitely an exception to the rule. I only found 1 other 3 character plate entered and three 4 character plates.
if we stick to a 5 character minimum we'll need to add language to include the hash symbols

Email suggestion to RPP staff to keep the 5 character minimum and add instructions to include hashtags for additional characters. Waiting response.

**Comment by moorerst** [comment]
Need to reach out to RPP staff and ask how 3 character license plates are handled in the license reader software. 
Also consider moving the minimum to 3 characters

**Comment by moorerst** [comment]
@ChrispinP Response from RPP Staff: 
I’d say if it’s not a problem let’s change the minimum. I’ve heard that complaint a few times from residents in the past. 

- [ ] change the minimum for license plate from 5 to 3 characters

Thanks

**Comment by ChrispinP** [comment]
I have updated the minimum character count for validation from 5 to 3 characters.
![image](https://user-images.githubusercontent.com/67915167/121551718-7d292e80-c9d5-11eb-9549-9c338501313d.png)

**Comment by moorerst** [comment]
@chrispin I'll inform the RPP staff. Thanks 
Closing this issue.
