### ISSUE TITLE
Update Fee Dates - All ATD Fees (Main Card)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6330]
### Make sure all ATD fee codes have the correct dates so they won't break on 10/1

**This is the main card for the epic**

The Three child cards are:
50255 (SCP Fees ) - #7089
90266 ( SP,C, C8, ZC fees) - #7090
50200 (RW Fees) - #7093

Card 1 of 3

**Comment by TracyLinder** [comment]
I emailed Nate & Sree the fee list that Amita sent us recently.

**Comment by Nadin-Nader** [comment]
**Next Steps:**
-  Review list and determine which need changes
- Look at a few DSD procedure that have the functionality that expires old logic and starts new logic on a certain date.
DefaultFee_SP_245
DefaultFee_SP_51121
FEE_BP_50000

**Comment by TracyLinder** [comment]
**UPDATE**
Pending Dev promotion.

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please make this an epic for Priya?

**Comment by Nadin-Nader** [comment]
We have identified 3 different lookups for this (for now) and will be making cards for them:
ATD fees - 50200 ( RW Fees) , 50255 (SCP Fees ) and 90266 ( SP,C, C8, ZC fees)

**Comment by Lpriya-LIT** [comment]
All the cards (#7090, #7093, #7129, #7130) related to this main card are deployed to Prod.
Changes look good in Prod.

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on #7093 to be RE-deployed to PROD on 9/30 to complete/close.

**Comment by Lpriya-LIT** [comment]
Deployed to Prod , changes look good

**Comment by Nadin-Nader** [comment]
All fee dates are in PROD and good to go. Closing
