### ISSUE TITLE
Amanda UC folder - Automatic emails that get sent out need to be updated

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6331]
Emails sent by the UC folder need to be updated. There is outdated information that confuses customers.
_SCTASK0141163_

**Comment by TracyLinder** [comment]
**Email from Jaclyn:**

Emails that need to be updated are generated from the UC folder after the following processes:

INTERNET PENDING ------ Result: Approved ---- Subject Line: Application Accepted

APPLICATION REVIEW ----- Result: Approved ---- Subject Line: Application Accepted

PERMIT COMPLETENESS CHECK ------- Result: [All Results] ------- Subject Line: Austin Utility Location  

 

I included the emails with the requested changes in red text. I would like the subject line for the INTERNET PENDING email to change from Application Accepted to Application In Review. Is it also possible to display the day of the week along with the date in the PERMIT COMPLETENESS CHECK email? Currently the date displays as 28-SEP-20 and I would like it to display as THURSDAY, 28-SEP-20.

 

Please let me know what further information you need.

 

Thank you

**Comment by TracyLinder** [comment]
![Screen Shot 2021-06-08 at 12.52.00 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/e885132a-3f42-419e-a51e-137c48b0704a)

**Comment by TracyLinder** [comment]
**Email to Jaclyn:**

Hi Jaclyn,

We've opened a DTS Ticket for this request. It will be prioritized with the other ROW requests in our backlog. Can you tell me what the urgency is on this request please? (Critical, Urgent, Important, Not Very Important...)

Thank You,

**Comment by TracyLinder** [comment]
Jaclyn said this is Important, but not urgent or critical. 
@Nadin-Nader will get it prioritized in our backlog

**Comment by Nadin-Nader** [comment]
**Bold and Italic = What needs to be added**

Application Accepted email. This email goes out when the Application Review is Accepted:

To: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>
Subject: [TEST] Application Accepted - TEST E-MAIL. PLEASE IGNORE

TEST E-MAIL. PLEASE IGNORE

Thank you for your submittal to the Austin Utility Location and Coordination Committee (AULCC).  Your Utility Coordination Application has been accepted.
Please review your information. If any changes need to be made, please contact:  
Email: Isaiah.Lewallen@austintexas.gov (512) 974-1479 
AULCC@austintexas.gov                     

ROWID: 12395357
Project Name: Final email verbage test
Applicant:  Jaclyn Lozano
Project Contact:  Jaclyn Lozano

Project Description: final email verbiage test

We've received all information necessary to distribute your case for review. **_IMPORTANT! Franchise cases do not get placed on an AULCC agenda. Please disregard further emails with a meeting date._**

For more information about the AULCC please visit https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.austintexas.gov%2FAULCC&amp;data=04%7C01%7CNadin.Nader%40austintexas.gov%7C45f1e9fcbc48481c075308d92ab14805%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637587763172692177%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=E%2BZAglbgTQjGYuWk4T3DEj2N0Om318wxSaIUD6t4EPI%3D&amp;reserved=0

**Comment by Nadin-Nader** [comment]
2nd email from Tracy's comment.
Bold and Italic = What needs to be added added or answered in the email. 
Austin Utility Location (Sent After Completeness Check) This email goes out when the Application Review is Accepted:

To: Lozano, Jaclyn <Jaclyn.Lozano@austintexas.gov>
Subject: [TEST] Austin Utility Location - **TEST E-MAIL. PLEASE IGNORE**

**TEST E-MAIL. PLEASE IGNORE**

Hello: 
Thank you for your submittal to the Austin Utility Location and **Coordination** Committee (AULCC). Your ROWMAN Utility **Coordination** Application has been scheduled.

AULCC Meeting date: 28-SEP-20 _**Is it Possible to have the day of the week display as well (Wednesday/Thursday)??? Also, Is it possible to not send this email for any case that falls on Wednesday or are SubType "Franchise Utility"???**_

Meeting Location: **Meeting Online via Microsoft Teams. You will receive an email invitation with the Teams link and optional call-in number at a later date.** **FRANCHISE PROJECTS ARE NOT PLACED IN AN AULCC AGENDA.**     
Meeting Starts: 2pm 

Please review your information.  
If any data needs to be revised, added, or deleted; Please contact: 
Isaiah.Lewallen@austintexas.gov, Jaclyn.Lozano@austintexas.gov, and AULCC@austintexas.gov

AULCC Tracking Number #:
ROWID: 12395357
Project Name:Final email verbage test
Applicant:  Jaclyn Lozano

Project Contact:  Jaclyn Lozano


Project Description: final email verbiage test

1.  Once the Project is reviewed, please begin a Spreadsheet or Minutes Sheet to record **responses**, identify areas of conflict, and note proposed resolutions. 
-   Projects that have been through the AULCC previously, must contain all utility comments from previous reviews. The Minutes tab, or a Conflict/Resolution spreadsheet should be utilized for this effort.		
-  Final review and clearance will be contingent on final review of the Conflict/Resolution Data and concurrence form the Project Engineer, Project Manager, Project Owner, and the AULCC Chairman.			
2.  A Final AULCC Clearance Letter will be granted to the Project once all the conflicts have been identified, and resolution has been verified. This letter will be required for General Permit, or Site Plan submittal to the Development Services Department Intake office on the 4th floor of One Texas Center.

**3.  FRANCHISE CASES DO NOT GET PUT ON AN AULCC AGENDA**

**Comment by TracyLinder** [comment]
Medium-Low

**Comment by TracyLinder** [comment]
### Update & Closing

- Currently there aren't any system emails we can think of that need to be updated. A new request will need to be submitted in the future for any system email that should be updated.
