### ISSUE TITLE
Work with Nathan to define + refine list of Moped terms 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6334]

**Comment by patrickm02L** [comment]
Scheduled meeting with Nathan for 7/1/21 to go over the Moped Terms.

**Comment by patrickm02L** [comment]
Talked with Nathan, and got a pretty comprehensive understanding about how he's thinking about Moped and how it aligns with the Access data base. He walked me through his databases and showed how he's visualizing the data on an Esri map. 

I think there's an opportunity to start bringing in real project data into Moped. There's a Shoal Creek example that Nathan keeps bringing up that may act as a good test case.

**Comment by amenity** [comment]
@patrickm02L - I would love to add more real data to Production! So far I've just been copy-pasting from the IMPD Viewer, but that only gets a few pieces of data (description, project team)... Would be rad to get a few projects fully entered with timelines, files, etc.

**Comment by patrickm02L** [comment]
I had a brief chat with John about starting to bring in real data to help us find the gaps for the terms. 

I'll open another one about testing with 'Real' project data into Moped. 

Closing this issue.
