### ISSUE TITLE
Perform preliminary project planning

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6339]
### Getting started
- [x] Review [Mobility Project Viewer overview](https://github.com/cityofaustin/atd-data-tech/issues/1106)
- [x] Review Moped [overview](https://github.com/cityofaustin/atd-data-tech/issues/307) | [roadmap](https://github.com/cityofaustin/atd-data-tech/#workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/roadmap?labels=product%3A%20moped&repos=140626918,185268238) | [Zenhub](https://github.com/cityofaustin/atd-data-tech/issues/1106#workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/board?labels=product%3A%20moped&repos=140626918,185268238) | [Miro](https://miro.com/app/board/o9J_knyFAmc=/)
- [x] Write [research questions](https://docs.google.com/document/d/1qAmKaCV91P5N1_MdkH79m9s87NgZkqFNio9V-x-jgXY/edit#heading=h.5t9hgvk6hjbb)

[Research plan](https://docs.google.com/document/d/1qAmKaCV91P5N1_MdkH79m9s87NgZkqFNio9V-x-jgXY/edit#heading=h.vf1aayvza2o)

**Comment by patrickm02L** [comment]
@janet looks good. Close it out.
