### ISSUE TITLE
Dev Review

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#634]
Attendees: John, Surbhi and Diana
Scheduled:10/10

**Comment by SurbhiBakshi** [comment]
Non Process Questions -

- [ ]  how do we restrict assignment times to fit into shift times?
 - [ ] how do we stop shift assigner from assigning an officer to an assignment if the officer is already - [ ] assigned to another assignment?
 - [ ] How do we ensure only the assignee is able to log records?
 - [ ] Since location information is getting captured by the device/ app, should there be a place for location entry in the form?
 - [x] Is there a way to separate date and time into separate fields? The separated date and time look better when viewing a record, but it works better in a form to have a date time field since the time component is tied to the date.
- [ ] When the shift assigner assigns the shifts, instead of an email, can a calendar invite/ meeting invite be sent out? This would block off that time on the person's calendar when accepted instead of depending on looking up email or a web page.
- [ ] What is the preference? Scrolling or clicking?
- [ ] Is there a way to prevent two shifts overlapping?
- [ ]  the calendar event (Shift) can be dragged to another day or time, but the related assignments are connected to the older time and record. Is there a way to stop the event from moving? or to carry forward the assignments?
- [ ] Should the assignment location get filtered by sector to narrow down the possible list of locations, so the drop down menu isn't too long. Or should each location auto fill a sector?

**Comment by dianamartin** [comment]
### Notes of Dev Review

Started with:
Event Scheduling Worksheet (Set up in Revolution 9-1-1)

**Comment by SurbhiBakshi** [comment]
- [ ] Make Calendar read only - take away functionality to drag event or add events, since there is no way of enforcing record rules to populate audit fields.
