### ISSUE TITLE
Perform secondary research

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6340]
Take a "mood board" approach in [Miro](https://miro.com/app/board/o9J_l_y7IaA=/)
Collect examples of mobility/infrastructure project tracking assets and tools

**Comment by amenity** [comment]
@janetchuhl pulled together a really solid collection of similar/related maps+dashboards. We'll present it at the sprint review tomorrow and invite stakeholders to send additional examples.

**Comment by amenity** [comment]
@amenity add screenshots of IMMPACT. @TracyLinder - could you Slack Janet screenshots of ROWPACT?

**Comment by patrickm02L** [comment]
@janetchuhl Presented at the Mobility Sprint Review.
