### ISSUE TITLE
Replicate automated status logic in new app

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6341]
Replicated the automated TPC status based on the child submissions—as is currently implemented in the Data Tracker version.

**Comment by ChrispinP** [comment]
Review Completed Date is automated based on Status change
![image](https://user-images.githubusercontent.com/67915167/122099110-3cffec80-cdd7-11eb-924f-b690027df4f6.png)

Submitted Status and Date can default now
![image](https://user-images.githubusercontent.com/67915167/122099947-36be4000-cdd8-11eb-9f3c-60af944b4bbf.png)

TCP Statuses automated. Most recent submission status overrides previous status in most cases. For Rejected or Returned, all submissions must be in that status to update overall TCP Status
![image](https://user-images.githubusercontent.com/67915167/122100259-9ae10400-cdd8-11eb-9399-0dbf80242e4d.png)

**Comment by ChrispinP** [comment]
Automated processes (field conditionals) added again after import.

TCP ID:
![image](https://user-images.githubusercontent.com/67915167/124403454-207f1200-dcfc-11eb-9cd0-b28db0974f1c.png)

TCP Status:
![image](https://user-images.githubusercontent.com/67915167/124403482-4c9a9300-dcfc-11eb-9b63-bc34861f8fe2.png)
![image](https://user-images.githubusercontent.com/67915167/124403472-40163a80-dcfc-11eb-8e38-016ff29533f4.png)

**Comment by ChrispinP** [comment]
complete, no further action
