### ISSUE TITLE
[Bug] Projects List: Current Phase column is blank

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6344]
On the projects list view, the "Current Phase" column is blank for new projects. It seems to be related to the fact that the "Current Phase" is now being populated from the "Active" phase of the project timeline.

<img width="974" alt="Screen Shot 2021-06-09 at 2 52 54 PM" src="https://user-images.githubusercontent.com/14793120/121420502-c70d0880-c932-11eb-84f3-586ed2cea7c6.png">

<img width="1071" alt="Screen Shot 2021-06-09 at 2 53 00 PM" src="https://user-images.githubusercontent.com/14793120/121420505-c83e3580-c932-11eb-96cb-3d4f71ca1e7e.png">

**Comment by chiaberry** [comment]
@tillyw here is where we wrote the sql view: https://github.com/cityofaustin/atd-moped/blob/main/moped-database/migrations/1621542484886_run_sql_migration/up.sql

**Comment by chiaberry** [comment]
I just checked in the hasura console for moped-editor-development to compare the sql view and the moped_project table to see if there were differences on the current_phase results, are they are the same results

the query i ran
```
query MyQuery {
  project_list_view(where: {project_name: {_ilike: "%delete%"}}) {
    current_phase
    project_id
    project_name
  }
  moped_project(where: {project_name: {_ilike: "%delete%"}}) {
    current_phase
    project_id
    project_name
  }
}

```
