### ISSUE TITLE
VZD Austin Full Purpose check

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#6351]
From XA:

> Good morning Mateo! I didn't know if I should include Patrick in this request, but could you look at this list of crashes?
> 
> [20210609-misassigned_crashes_austin_full_purpose.csv](https://github.com/cityofaustin/atd-data-tech/files/6632091/20210609-misassigned_crashes_austin_full_purpose.csv)
> 
> ```SQL
> select atc.crash_id, atc.case_id, atc.rpt_street_name, atc.rpt_sec_street_name, atc.crash_date, atc.position, atc.city_id, atal.agency_desc, atc.austin_full_purpose 
> from atd_txdot_crashes as atc 
> left join atd_txdot__agency_lkp as atal 
> 	on atal.agency_id = atc.investigat_agency_id
> where atc.city_id = 22 and position is null and atc.crash_date >= '2014-11-01'
> ;
> ```
> 
> I believe they should be flagged as Austin Full Purpose
> 
> 
>

**Comment by patrickm02L** [comment]
- [ ] @mateoclarke to update all the records from XA's query that should be Austin Full Purpose = Y
- [ ] Triage and fix the bug in the ETL logic

**Comment by mateoclarke** [comment]
Updated prod with this SQL command:

```sql
UPDATE
	atd_txdot_crashes
SET
	austin_full_purpose = 'Y'
WHERE
	city_id = 22
	AND position IS NULL
	AND crash_date >= '2014-11-01';
```

`Query 1 OK: UPDATE 3481, 3481 rows affected`

**Comment by mateoclarke** [comment]
This PR offers a solution to make sure `austin_full_purpose` gets set when a record is created stays in sync when city ID or position gets updated.
