### ISSUE TITLE
Meeting w/ DSD GIS: Proposed ownership change - small cell GIS asset discussion

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6356]
### Objective 
This is a planning meeting about proposed changes and potential project timelines to see if ATD has to make some process changes until a permanent solution is in place for small cell stakeholders.

### Participants
Danny H, Cheryl V, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
Scheduled 6/15 at 10 am

**Comment by dianamartin** [comment]
Danny, Cheryl and I looked at a small cell asset - took a look at it's address and used the Property Profile to see what might come up. The permits nearby the address came up and the small cell folder type came up. 
Ex. Looked up this address:  `709 1/2 Congress Ave NE`
- This pulled up "Permits" associated to this location
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/f5218e47-2d3c-488d-b025-5e9d918b8901)
- UCC-170824-22-01: Folder Type UC - In Review

**Comment by amenity** [comment]
DSD GIS is going to meet internally to make sure their GIS team can accommodate this data in their GIS datasets.
