### ISSUE TITLE
Meeting: Parking Meters Discovery Meeting - Part 2

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6358]
Attendees: Stephanie, Diana, David S., David D, Gilbert, Jeremy, Steven S., Steven S.

Discovery Meeting - learn more about your parking meter work order processes and CSR processes. 

Agenda: 
https://docs.google.com/presentation/d/1eiZJwZHQoz3JO-DwGmuWfRcTI1O22iT5AmYIgXJb47g/edit#slide=id.p

**Comment by moorerst** [comment]
Follow up meeting scheduled for 6/17
Agenda: 
- Permit Processes
AMANDA permit requests, Special Events
- Inventory Management
Toolbag
Filing cabinets
Paystation housing
Other parts
- GIS Assets
Pay station, Meter, Zones, Space
Bike corrals, Bike racks
Installation Dates?
 Map ADA zones
 Other maps
- Reporting

**Comment by dianamartin** [comment]
Debrief discussion with Stephanie
- Make a Big Picture workflow of all the systems they touch and how they connect, will help with Builder Huddle

**Comment by moorerst** [comment]
@dianamartin the Big Picture workflow looks great it looks so doable on paper...lol

**Comment by dianamartin** [comment]
Closing Issue, we can reference for Builder Huddle if we need to
