### ISSUE TITLE
Add accurate Weather and Time data to VZE crash page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#6364]
In sprint review [#34](https://docs.google.com/document/d/1y_MMs5TgJAheQFMWqbJdch0oeyT_eQhV1e_yaEl3uz0/edit#heading=h.3sdgu3b3w33l) we discussed the inaccuracy of road conditions data in CRIS. We should explore external data sources and API, i.e: NOAA.

**Comment by mateoclarke** [comment]
Ex: https://www.mapbox.com/blog/better-with-weather

**Comment by patrickm02L** [comment]
@tillyw your Discovery Day project reminded me of this Issue. I'm going to pull it into Needs Scoping, so we can talk about it in an upcoming grooming session.

**Comment by patrickm02L** [comment]
12/21/22 In grooming. 

Charlie suggested adding the [realtime roadway conditions](https://data.austintexas.gov/dataset/Real-Time-Road-Conditions/ypbq-i42h).

**Comment by patrickm02L** [comment]
This one has been out for over 2 years, don't feel like there's any urgency or major improvement around doing this, putting it to rest.

**Comment by johnclary** [comment]
Leaving this in needs scoping since there is still hope out there that we do.

**Comment by johnclary** [comment]
See also: https://github.com/cityofaustin/atd-data-tech/issues/10972
