### ISSUE TITLE
Purchase Request TablePlus

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#637]
What:
TablePlus 
- database admin software for Mac
- useful for remote database connections
- SQL queries
- table/column/schema/triggers modifications 

Why:
- I've been testing the free version and its really nice and easy to use. The main reason to upgrade to pro is because you can only have two tabs of work open at a time. It's good software and I think the cost is justified.  

Cost:
https://tableplus.com/pricing 
$59 license 
This is a perpetual (lifetime) license. It includes one year’s worth of updates.

**Comment by johnclary** [comment]
@mateoclarke hit up @dianamartin to help you submit a purchase request and assign it to me.

**Comment by amenity** [comment]
@johnclary here's the request, assigned it to ya: https://atd.knack.com/finance-purchasing#purchase-requests/purchase-request-details/5dc399978c4bbc00163f42d6/

**Comment by johnclary** [comment]
It's approved. Waiting for confirmation to pay w/ procard

**Comment by mateoclarke** [comment]
Yay!!!

![unicorn_spreadsheet](https://user-images.githubusercontent.com/5697474/68436084-8f504480-0182-11ea-8073-ebddfe13a987.gif)

**Comment by mateoclarke** [comment]
anything new here?

**Comment by dianamartin** [comment]
@john, have you had a chance to purchase this software with your ProCard? cc @mateoclarke

**Comment by amenity** [comment]
Creo que this is done, yes @mateoclarke ?
