### ISSUE TITLE
Patch account creation API to address bug with existing Cognito users

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6372]
API needs to check if a user exists already in Cognito, if so use the existing Cognito user when creating the Moped account.

**Comment by sergiogcx** [comment]
It was a bit more complicated than I anticipated, but I've managed to make it work. You should be able to 

https://images.zenhubusercontent.com/140626918/f2844c0a-4ca2-4b37-8fc3-c6a3309442d9/2021_06_22_15_33_27.mp4
