### ISSUE TITLE
TIA Reporting: Total Cases by Council District & TIA Need

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6374]
Add a reporting section for Total Cases by Council District

**Comment by ChrispinP** [comment]
Total Cases by Council District and Total Cases by TIA Need reports added
![image](https://user-images.githubusercontent.com/67915167/122426730-1a481200-cf56-11eb-81fe-d593595c0ac6.png)

**Comment by TracyLinder** [comment]
Reviewed w/ stakeholders. Looks good, closing.
