### ISSUE TITLE
TIA Case Loads: Filter out Inactive Status

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6376]
On Area Case Load & Reviewer Case Load, filter out cases w/ status of Inactive.

**Comment by ChrispinP** [comment]
Cases that are Inactive are now filtered out by default
![image](https://user-images.githubusercontent.com/67915167/121960596-ee494880-cd2b-11eb-976c-04e725bba6e5.png)

**Comment by TracyLinder** [comment]
@ChrispinP please remove the date filter 'current year' from both case load views, then close this ticket. 
_Moving back to In Progress_

**Comment by ChrispinP** [comment]
Removed Current year filter from both Area Case Load and Reviewer Case Load as well as for Dev Reviews
![image](https://user-images.githubusercontent.com/67915167/124025516-27351e80-d9b6-11eb-8454-5755012016d6.png)
