### ISSUE TITLE
TIA Gitbook Documentation

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6377]
_[Gitbook](https://app.gitbook.com/@atd-dts/s/tds-portal/)_

- Data Dictionary (for example, does days under review mean business days or calendar days)
- Glossary of terms
- Case status triggers

- External Customer workflow training/documentation
    - also to help review staff troubleshoot customer portal issues

**Comment by TracyLinder** [comment]
### Work Sesh 7/6/21
_Chrispin & Tracy_

![Screen Shot 2021-07-06 at 11.47.11 AM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/1114b730-ba28-4414-9c9f-65971f90bd84)



-----
**Assignments**
Chrispin: 
- TIA Workflow
- Case status & triggers
- Emails

Tracy:
- Glossary
- Mitigation Guide

**Comment by ChrispinP** [comment]
Documentation for ERD, Case Status automation, Emails, Customer Workflows, and Reviewer Workflows have been added and updated. Pending any further tweaks.

**Comment by ChrispinP** [comment]
Color Palette documentation added to Gitbook

**Comment by ChrispinP** [comment]
Glossary updated. Kept it simple for now, can add more terms later if needed. Will update Customer Portal Guide and Mitigations Guide after data migration and have spent more time learning to create user guides and gifs. Once there is more data in the app and the coordinates bug is fixed, circling back to update this documentation will make more sense.
