### ISSUE TITLE
TIA Advanced Search: Add column for Engineer Company

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6378]
On the search results, add a new column for Engineer Company

**Comment by ChrispinP** [comment]
Sealing Engineer added to Case Search
![image](https://user-images.githubusercontent.com/67915167/121966783-d924e780-cd34-11eb-97ef-6d6ae30f8e05.png)

**Comment by TracyLinder** [comment]
Reviewed w/ stakeholders. Looks good, closing.
