### ISSUE TITLE
Create Forms decision workflow 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6379]
I decided to create a forms [decision workflow](https://miro.com/app/board/o9J_lAKE95k=/), I had made something similar for geospatial forms. I took that old decision workflow and updated it to the new form products that DTS uses. 

Hoping that this can be a helpful guide for users to determine if they need a Knack form or if they should use FormStack.

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/f495b48f-d00c-4b00-b6b2-91086f10ebe9)

**Comment by moorerst** [comment]
@dianamartin this is interesting I think it asked users some good questions when considering a tool for their forms. 
On the question Do you want users to login with their COA credentials - would that be a YES for Knack Forms also?

**Comment by dianamartin** [comment]
@moorerst I think I need to make a comparison matrix too. Knack does it too.

**Comment by moorerst** [comment]
@dianamartin I think that would be a good idea it would be easier to represent features that cross multiple platforms

**Comment by dianamartin** [comment]
I created the comparison matrix too, showed this decision tree to stakeholders on 6/16
