### ISSUE TITLE
Project: Bike Parking Data Inventory

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#638]
We're building GIS tools for tracking information about bicycle rack installations and maintenance. 

DTS GIS staff has created an online bike rack data collection map for Parking Enforcement and Active Transportation to manage the installation and maintenance of bike racks in the city. Location data is currently being collected in the field by Parking Enforcement staff, who are providing feedback to GIS staff to improve the data collection map.
![image](https://user-images.githubusercontent.com/42655533/116584838-9ca84400-a8cc-11eb-98c9-01d34c183a34.png)

### Resources

 - [Collector Map](https://austin.maps.arcgis.com/apps/mapviewer/index.html?webmap=b890742f771e438ab4047c3ff07ac0a5)
 - [Documentation](https://atd-dts.gitbook.io/atd-geospatial/active-transportation/updated-bike-rack-data-collection/~/settings/share)
- [Initial Scoping](https://github.com/cityofaustin/atd-geospatial/issues/296)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://transportation.austintexas.io/about/) team. Project status is documented regularly in the comments below.

**Comment by johnclary** [comment]
@alan-deanda would you add the link to the wiki in this issue description?

**Comment by alan-deanda** [comment]
Project update:
See description for links to documentation

**Comment by johnclary** [comment]
@andrewshensky @alan-deanda is there still active work remaining for this project?

**Comment by andrewshensky** [comment]
I think we can probably close this one. Data collection is ongoing but everything has been pretty stable for the past couple of months.
