### ISSUE TITLE
BUG: Event Review Process is not being inserted into the RW-SE Folder with two of the WorkTypes (ON PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#6388]
Event Review Process is not being inserted into the RW-SE Folder with the WorkTypes of Arterial/Collector (50535) and Safety Closures (50545). Neighborhood (50540) WorkType already inserts the Event Review Process which is ok but it NEEDS to be on the other two WorkTypes.

**Stakeholders:** Maria, Laura
**DTS Manager:** Nate

**Acceptance Criteria:**

-  This applies to RW-Street Event folder with the WorkTypes of Arterial/Collector (50535) and Safety Closures (50545)
-  "Event Review Process" Must be inserted upon folder creation

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder  - analyzed and found that the issue is because of the #4551 PROD move in May 2021. The request is to Exclude the Event review process to fix the bug in RW folder; so to fix this issue, we need to delete 2 rows from Defaultprocessexclusion table. 

SELECT * FROM DEFAULTPROCESSEXCLUSION WHERE processcode = 50560 
AND subcode = 50510 AND workcode IN (50535,50540,50545)

![image](https://user-images.githubusercontent.com/65371095/122128826-c2e15f00-cdfa-11eb-82ff-2adb3c507811.png)


Delete from  DEFAULTPROCESSEXCLUSION WHERE processcode = 50560 
AND subcode = 50510 AND workcode IN (50535,50540,50545)

Upon which this can be fixed. I am not sure whether we need to create a request/Task id for this. as it's just a SQL statement.

These changes are tested in LocalHost
11885244 - RW Street Event arterial/collector
11885246 - RW Street Event Neighbourhood
11885247 - RW Street Event safety closure
Kindly let me know your views on this.

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder  - Manual commit Deployment plan sent to Nadin on 06/21/2021

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to CTM DevOps to deploy the manual commit to DEV under **SCTASK0146521**

**Status:** 
Waiting on CTM DevOps to deploy to DEV

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan Per Martin this will not be a manual commit. This needs to be a regular commit. Please make the change in local and submit a regular commit to send to the DevOps Cm Team.

**Status:**
Needs to be changed in Local and a commit must be created and sent through DevOps

**Comment by sreelathab** [comment]
@Nadin-Nader , @TracyLinder  - Sent DEV Commit today with Commit ID:b7057d6a22b4

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have approved the commit. Please send me the Deployment plan

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have sent this to DevOps CM Team under **SCTASK0148726** to deploy to DEV

**Status:**
Waiting on DevOps to deploy to DEV

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this one has been deployed to DEV by the DEVOps team. Please UAT and let me know

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Tested in DEV and it's working as expected. Now Both RW_ Street event - Arterial/Collector, Safety Closure  work codes are inserting Event Review process. FolderRSN's 11901689, 11901691. Kindly review and let me know your thoughts

**Comment by Nadin-Nader** [comment]
Status:

Test Deployment will be sent today

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Sent TEST Deployment plan. Here is the Commit IDb7057d6a22b4

**Comment by Nadin-Nader** [comment]
**Status:**
Sent to DevOps CM Team to deploy to TEST under **SCTASK0152097**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on Response from George about deployment

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan spoke to George and this has been deployed to TEST. Can you UAT and let me know if you are good with the changes so i can let Maria know to test on TEST

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST environment. Working as expected; ie.,Event Review process getting inserted automatically in RW- Street event folders

RW - Arterial/Collector - 12658766
RW - Neighborhood  - 12658768
RW - Safety Closure - 12658771

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan ok awesome, I will send an email to Maria and Laura asking them to UAT on TEST and get approval for PROD

**Comment by Nadin-Nader** [comment]
email sent to Maria and Laura:

> Hi Maria/Laura,
> 
> Hope You both are doing well. I was reaching out to inform you that the fix for the Event Review Process Not Being Inserted into the RW-SE # 6388, is now on TEST. 
> Sree has verified  that it works. Can you please verify it has been resolved and let me know?
> 
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services
> ————————————————————————————
> transportation.data@austintexas.gov 🚦 austinmobility.io

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on Maria to get back from Leave on 7/27/21/ Laura is on Maternal Leave

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan Spoke to Maria and everything looks good. Lets Get this to PROD.

Maria's email:

> From: Alonso, Maria <Maria.Alonso@austintexas.gov> 
> Sent: Wednesday, July 28, 2021 1:52 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>; Bosmans, Laura <Laura.Bosmans@austintexas.gov>
> Subject: RE: Event Review Process Not Being Inserted #6388
> 
> Hi Nate, 
> 
> I just tested and it seem to be working! 
> 
> Here is the Row ID 12665200
> 
> Let  me know if I can help with anything else. 
> 
> Take care, 
> 
> Maria Alonso (she/her/ella)
> Project Coordinator
> O: 512-974-7275 | E: maria.alonso@ausintexas.gov


## **Approved for PROD Deployment🙌🎉‼**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan the DP for this is not accessible and was not a downloadable doc. Please resend. 
**Status:**
The PROD DP was not accessible. waiting on Sree to resend before sending to CTM

**Comment by Nadin-Nader** [comment]
**Status:**

Sent to DevOps CM Team for deployment to PROD under **SCTASK0156481**

**Comment by Nadin-Nader** [comment]
@Nadin-Nader follow up tomorrow

**Comment by Nadin-Nader** [comment]
Sent Martin a chat asking him if they were able to deploy this or if it was going t be deployed today.

**Status:**
Waiting on Martin's response

**Comment by Nadin-Nader** [comment]
**Status:**
Per Martin he will deploy this to PROD today but may be at the end of the day

**Comment by Nadin-Nader** [comment]
This has been deployed to PROD. Sending Stakeholders an email for PROD UAT and closure of card

**Comment by Nadin-Nader** [comment]
Sent email to Maria and Laura:

> 
> Hi Maria/Laura,
> 
> Hope you are both doing well. I was reaching out to you in regards to card 6388 where the Event Review process was not being inserted into the RW SE folder for two of the WorkTypes. The fix for this has been deployed to PROD. Please log on and verify that all is well and let me know the outcome. Once we hear back we can either close the card or address any issues.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services


**Status:**
Waiting on  PROD UAT from Stakeholders

**Comment by Nadin-Nader** [comment]
Email response from Maria:

> Hi Nate, 
> 
> It appears to be working on all folder subtypes. 
> 
> Thanks again for your help on this! 
> 
> Maria Alonso (she/her/ella)

Closing card
