### ISSUE TITLE
Get VZA Citation Data from Brazos

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#639]
Can we get the VZA citation data from Brazos? We have an upcoming meeting with Tyler Tech, so we'll inquire about options.

@johnclary has been speaking with Trey about getting information via CSV files

@SurbhiBakshi has two additional  ideas
- Daniel Y. from ATD gets CRIS data to look at in Microstrategy
- There PDFs with a TON of information can be downloaded from Brazos through the web interface. So some OCR situation could be an option... 😬

**Comment by johnclary** [comment]
Surbhi has reached out to Auzzie to ask for Microstrategy availability/access.

I followed up on an issue we opened with Tyler tech to get the "secondary street" column added to the Brazos xlsx report.

We discussed possibly having a VZ staff person export/load the citation to a google drive folder where we would process it.

FYI @amenity in case there's another issue for this.

**Comment by SurbhiBakshi** [comment]
@johnclary @amenity [#939] (https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/939) is related. Going to close that.

**Comment by johnclary** [comment]
I followed up again with Brazos support this morning:

> Good morning, Sam—has your development team had a chance to look at this? Is this typically something that requires development work, or might it be something we can configure with Cognos? Thanks.

**Comment by SurbhiBakshi** [comment]
A Parsons has said she will connect me to MuniCode staff to explore the idea of connecting to the proposed data warehouse.
A Zehnder responded to my earlier email, will set up a meeting with her.

**Comment by SurbhiBakshi** [comment]
set up meeting with A Zehnder for tomorrow
waiting to hear back from T Salinas at MuniCourt.

**Comment by SurbhiBakshi** [comment]
A Zehnder communicated she will send in a ticket to vendor to inquire into an automated report/ dataset delivery via FTP on a weekly basis with the addition of a cross street information field. She will include the ticket number created by @johnclary for cross street information.

**Comment by amenity** [comment]
@SurbhiBakshi - Will you ping Amy again and cc me?

**Comment by SurbhiBakshi** [comment]
Reached out to Amy on Jan 9th, haven't heard back. 
Emailed her again today, and cc'd @amenity

**Comment by amenity** [comment]
Amy replied and said she submitted the request 12/20 and will follow up on it today. 🐌

**Comment by amenity** [comment]
Since Tyler Tech has shown no indication that they can perform these changes in a timely manner, Amy is going to give @SurbhiBakshi access to Cognos reports so that we can create one that works for VZA. Closing this, creating #1370.
