### ISSUE TITLE
Display consistent list order of 'travel modes' between filter buttons

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#6391]
The travel modes list order changes when you select 'Serious injuries'. 

The 'All' and 'Fatalities' filters have Pedestrian before Motorcyclist. When you select 'Serious Injuries' it flips the order to Motorcyclist to Pedestrian. 

Keep the order across all filters so that it reads Pedestrian, then Motorcyclist.

![travel by mode-all.jpg](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/70bb231e-47e9-471c-a1e6-68388a93ee4b)![travel by mode-serious injuries-switch.jpg](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/fb3bfa4b-5800-49fe-8811-3841f7e2e24c)

**Comment by mateoclarke** [comment]
Assigning this one to @jgabitto with an 1 day timebox before we spend any extra time on it. If it's looking to challenging based on the 3rd party dependencies and limited ability to override built-in behavior, we can put on it til later. cc/ @chiaberry
