### ISSUE TITLE
Update Comprehensive Costs Table

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#6395]
- Needs to be done before July 1
- Update values for comprehensive cost table, `atd_txdot__est_comp_cost`. Need these new values.
- Create a new field similar to `est_comp_cost` but that calculates the cost using the highest injury severity in the crash. 
  - Context for change: to help TED better prioritize street treatments and redesign. "flatten the noise of crashes with lots of people involved"
- Update the VZE queries to display the new field value instead of `est_comp_cost`

**Comment by johnclary** [comment]
Frank and @sergiogcx are working on a patch. The code has been written and needs to be deployed.

**Comment by frankhereford** [comment]
This afternoon I have completed a set of changes to the atd-vze & atd-vzd in the atd-vz-data repo which define the new comprehensive cost tables, get the two crash tables updated and reflect these changes in the VZE. 

It touches a bunch of files, and I want really try to commit in a way that explains what each change is and not just one big monolith for the sake of the reviewers.

That said, I will be committing it shortly and will ping this thread when it's available for review. Thanks!

**Comment by frankhereford** [comment]
@patrickm02L I'm rereading this after finding it on zenhub. 

This issue is addressed by the [merged PR 1011](https://github.com/cityofaustin/atd-vz-data/pull/1011), and I believe is a candidate to be closed either now or when 1.21.0 is pushed to production.

**Comment by patrickm02L** [comment]
Closing. @frankhereford believes this was addressed by v.1.21.0.
