### ISSUE TITLE
Attend Advantage 311 demo

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#64]
### Objective 
Learn about Advantage 311 to see if it would meet our warehouse inventory management needs. 

### Participants
DTS: Diana, Amenity
SMB: Lauren Seyeda, Christina Tremel, Kati Alcantara, Anthony Forcier 
AMD: Ray Flores, Johnny Padron
Purchasing: Sam Dominguez 
Controller's: Jennifer Margolis-Husted, Fabian Mesa

### Summary
Sam walked us through [the slide deck](https://drive.google.com/open?id=1jSQ2PaFlRjkAiGRj9_tpSMuWFpSXE4GS) that CGI presented to everyone a few weeks ago. No one has gotten a software demo, just screenshots of new features, but he also walked us through the current application. 

If we want to use the enhancements, we need to tell Sam by Friday. They discouraged us from doing this if we are still evaluating solutions because it will require a substantial amount of their resources (plus time from our materials managers) to configure the application for us to test. 

AMD likes the ability to track items, but it's not clear how robust that part of the functionality is, given that the core functionality was built around purchasing. Seems likely that a vendor solution built specifically for inventory and asset management would be a better fit. 

Amenity & Diana's main concerns are: 
 - On-prem solution, need to be on network. Adds a layer of complication for field work
 - Not clear weather application can be used from a mobile device
 - Only 30% of AMD's asset types are even _in_ AIMS, so this would only be a partial solution. 

Next steps 
- Amenity reaching out to Austin Water to find out why they decided not to stick with Advantage #71 
- Amenity emailing list of questions to Sam to give to CGI #72

### Notes
[Diana's notes](https://cityofaustin-my.sharepoint.com/:o:/r/personal/diana_martin_austintexas_gov/Documents/Notebooks/Diana%20@%20Work?d=w434b1a507b274d30864e21740e23f0da&csf=1&e=W6bYni)
[Amenity's notes](https://docs.google.com/document/d/1hE7E8UCeHyjuE9ZXq0UeJUk0cKELf-_lz1by0zvYlWg/edit#)

**Comment by johnclary** [comment]
thanks @amenity. this is a 100% no-go.

**Comment by johnclary** [comment]
@dianamartin i don't have access to your notes via the link above.

**Comment by dianamartin** [comment]
@johnclary I just shared my notebook with you.
