### ISSUE TITLE
UC - Unpaid Review Fees report, with a monthly batch email job. (SS) (On PROD and Approved by Darren's)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6403]
### A new UC - Unpaid Review Fees report, with a monthly batch email job.

**Stakeholders:** Darren U., Isiah, Jaclyn

**Acceptance Criteria**

`Batch Job`
- Runs on the 1st day of the month
- Emails UC Unpaid Invoices report to: Darren Ujano, aulcc@austintexas.gov 

`Custom Report`
_Spreadsheet/Markup is [here](https://docs.google.com/spreadsheets/d/1AOyFJMEuAEtPExn3t_7-obqXkgvWgC8TGwzzhev0nIQ/edit?usp=sharing)._
- Report (File) Name: UC Unpaid Invoices
- Report Page Title: Unpaid Utility Coordination Invoices Report
- Group by FolderRSN
- Sort by invoice date, oldest to newest

![Screen Shot 2021-06-15 at 12.49.11 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/40cd3ff5-5235-4250-a43d-52d16a10b3b7)

**Comment by TracyLinder** [comment]
I sent the report markup to Darren for review/approval.

**Comment by TracyLinder** [comment]
**Prioritization Review Note:** Still needed for finance purposes.

**Comment by TracyLinder** [comment]
**Prioritization Review Note:** Still needed & high.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Crystal report is ready and I am trying to configure a batch job on DEV. There is an issue to save the configured one as the system assigns an existing JobRSN to the new record and it says 'This record already exists'. I have raised an incident for this - INC0261265.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  

1. What should be the from email id for this?
2. Please confirm Darren's email id is darren.ujano@austintexas.gov.
3. What should be the output format that should be sent in email? Excel is not going in the expected format. I think I can send it in PDF in the expected format. Please let me know.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This report is done in DEV along with the batch job. The report format is set in pdf format and from the system automatically picking  AMANDAMBDEV@austintexas.gov id.
[Report (1).pdf](https://github.com/cityofaustin/atd-data-tech/files/10690179/Report.1.pdf)

**Comment by Nadin-Nader** [comment]
@SubhaShroff the users need this report in an excel format

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Excel format sent through Amanda will look like this:
![image](https://user-images.githubusercontent.com/51680715/218124853-7be52c2a-8fb1-4960-acd3-bc5f3720fd2d.png)

If we take it from Crystal Report tool, directly, we get the expected format. But that won't be helpful for the user as they have to use Crystal Report tool.

**Comment by Nadin-Nader** [comment]
@SubhaShroff Spoke to Darren and he said that they need this report in an excel format. This is needed because the recent reports he gest from excel has all the raw data, so they have to manually filter it down. I also asked Jaclyn and she told me that Samson (another user for this report) needs it in excel.

**Comment by SubhaShroff** [comment]
Thank you @Nadin-Nader.
The report is sent for TEST deployment - SCTASK0286667.

**Comment by SubhaShroff** [comment]
Hi @Nadin-Nader  This report with batch job is deployed in TEST. Tested it by asking Anu to RUN the batch for once. The report must be sent to Darren and [aulcc@austintexas.gov](mailto:aulcc@austintexas.gov).  I checked the output and its in EXcel format in my email. Please check with Darren as well.

NOTE: Though, the batch job is set to run every month, for some reason, the job is resetting only for Feb month in both DEV/TEST. Anu also not sure and she said she will check with Jenice. We will check this in PROD as well.

**Comment by SubhaShroff** [comment]
### Status:
Ready for UAT on TEST since last week.

**Comment by Nadin-Nader** [comment]
Sent Darren a Message about the batch having been run on TEST and that he should have gotten an example of the emailed report. I asked him to please review it and let me know the outcome. Waiting on Response

**Comment by Nadin-Nader** [comment]
@Nadin-Nader send Swapna a message in the AM to run the batch report for Darren

**Comment by SubhaShroff** [comment]
@Nadin-Nader  On Tuesday, I had requested Anu to run the Batch job(193) on TEST. I have received email with the report. Today, I sent it to Darren and you for review.
Thanks.

**Comment by Nadin-Nader** [comment]
@SubhaShroff  send this to PROD

**Comment by SubhaShroff** [comment]
Thanks @Nadin-Nader. I have raised a PROD promotion request for this - SCTASK0302114.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This ticket is deployed in PROD. We may want to wait till 1st of May for the Batch job trigger. Or should we ask Anu to do it manually on PROD to verify? But if its working that will send email to the user.
Thanks.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this can wait til the 1st unless the users want to run it early. I will ask and let you know

**Comment by Nadin-Nader** [comment]
Asked Jaclyn if she wanted to wait til the 1st or if she would like us to have CTM run the batch job before then.....Waiting on Response.

**Comment by Nadin-Nader** [comment]
Jaclyn Responded and asked to have the report ran before the first to verify before then. Asked Anu to run it on PROD when she gets a moment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  Looks like there is an issue with Batch job configurations. Though it was configured for every month, it got reset only for February. So, it didn't fire on PROD on May 1st. Unfortunately, I don't have PROD admin access, so I can't verify what is configured in there and who/when it got removed/updated. I just checked on DB, querying for it. I have asked Anu to have a look at it.
Batch job on PROD - 195.

**Comment by Nadin-Nader** [comment]
Sent message to Darren asking him to verify if he received the report. Jaclyn did not but she may not be on the distro for it.
Waiting on Darren's response

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder , @SubhaShroff - Job reset to run on July1st I believe the query looks good.

![image](https://github.com/cityofaustin/atd-data-tech/assets/44907715/96d3a6c9-f1ea-47e6-9157-caf2f6c971ed)

Thank you!

**Comment by SubhaShroff** [comment]
Thank you @Sreelatha-BlazeKannan.
@Nadin-Nader  I see that job was executed on JUN 01. If Darren can verify if he got the email and the content of it, we can closed this.
Thanks.

**Comment by Nadin-Nader** [comment]
Reached out to Darren Via TEAMS. Waiting on Response

**Comment by Nadin-Nader** [comment]
Closing Per Darren's response:
[11:11 AM] Ujano, Darren

that works with me!

> [11:11 AM] Ujano, Darren
> 
> thank you
