### ISSUE TITLE
Set Patrick up with eCAPRIS

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6407]
- [ ] [Request account](https://ecapris.austintexas.gov/login/)
- [x] [Read eCAPRIS / Moped context](https://docs.google.com/document/d/1ICBPcJLQrAvXv2JqHIW5fCCDZqOUF_adxTaochMSZc4/edit#)

**Comment by patrickm02L** [comment]
Downloaded VPN, need to get to a docking station to connect, and request remote access from ServiceNow.

**Comment by patrickm02L** [comment]
Successfully set up my account.
