### ISSUE TITLE
Give Annie P. access to VZD read-replica

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6422]
@phanaq will be assisting VZ with data research. She needs access to the Vision Zero database read replica.

**Comment by johnclary** [comment]
FYI @SurbhiBakshi

**Comment by SurbhiBakshi** [comment]
thanks @johnclary and @sergiogcx!

**Comment by sergiogcx** [comment]
@SurbhiBakshi @johnclary @phanaq I forgot to close this issue, doing so now. 🙏
