### ISSUE TITLE
Preliminary research on ATD data needs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#643]
Before doing hosting a workshop, #632, let's compile existing information on data needs:
- @dianamartin - will you upload Jacquie's previous survey [here](https://drive.google.com/drive/folders/1k3Nbl-g-LvUYn9jzxeiXUs3G3qWhsBl8)
- @amenity, @TracyLinder, @johnclary review BNAs

Based on this, create a survey that will fill in gaps and give us updated information.

**Comment by johnclary** [comment]
Closing this issue.  Our service delivery workflow enables these needs to surface.
