### ISSUE TITLE
Rebuild ATD pages in Modern Page layout

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6436]
# Recommended Tasks
- Check all sub sites in Site Settings that "Site Pages" feature is enabled
- Create modern "Home" pages for all sub sites
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/b9004289-9fa6-4c28-99cb-0bfe10545fe8)
- Set Document Library to - Advanced Settings>Set to "new" experience
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/cda51c15-dc6f-4387-ae1e-60b7100a05e1)
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/ebf828ee-e9bc-4811-acdb-7f7791522a10)
- When all sub sites have a Modern Page
- Make the new Modern page a home page (Site Pages>"three ellipses", "Make Home page"
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/2be7d43d-1b96-4139-b863-4bedfe7bae14)
- Optional: Create CTM Ticket to make ATD Hub Site into Root site

## Option 1
- Keep ATD page as root parent
- Create new Modern page (will have the left navigation menu)
- Create CTM Ticket to make ATD Hub Site into Root site
- Configure all the menu links to the new sub site menu pages

## Option 2
- Keep ATDHub page 
- Create new modern Home pages for each sub site
- See recommended tasks
- Create CTM Ticket to make ATD Hub Site into Root site (will keep the URL name "ATDHub" instead of our normal "ATD"
- Connect the sub sites to the ATD Hub site (this will bring over the parent navigation menu)

## Option 3
- Have ATDHub page
- rebuild all sub site pages under ATDHub 
  - going to be painstaking, not the recommended
  - pages will not have left navigation menu (modern look)

**Comment by dianamartin** [comment]
- [x] Created modern page on ATD Root Site (Current site) 
- Need to create more modern pages for
- [ ] sites/ATD/AF - **Finance**
- [ ] sites/ATD/**Administration** 
  - PIRs, eTimesheet Resource Page
- [ ] sites/ATD/**ATD Dispatch** - create new front? Looks like it's already done (ARCHIVE status)
- [ ] sites/ATD/SM - **Signs and Markings**

## Sub-site Clean up
- [ ] sites/ATD/Training - Old eLearning page (never used)
- [ ] sites/ATD/GrantsP3 - Kirk S., can we delete? using?
- [ ] sites/ATD/AT - created back during O365 migration, using?
  - [ ] ATSD Team site (make Diana owner)
- [ ] sites/ATD/AMD- created back during O365 migration, using?
- [ ] sites/ATD/ACT - not being used

**Comment by amenity** [comment]
@dianamartin something to look forward to for next week!

**Comment by dianamartin** [comment]
Preferable ATD Hub Site as Hub 
- ATD Hub Site - make that the HubSite?
  - change to ATDHUB to ATD - Danny can do that
- link to other Modern sites?

# Next Steps
- Work on ATDHUB -make sure links are current 
- CTM Ticket - atdhub - atdold
  - Spoorthy to ask Danny about name swap
- Create SharePoint sites slowly

## Create new SharePoint site
- Waffle
- Sharepoint
- Teams v. Comm site
-  URL naming: atdSITENAME, 

## Status
- atdHub will convert to Hub Site
- Current work around: link old sites to Hub Site
- Highly recommend to create new modern sites for each sub site and link to Hub site

**Comment by dianamartin** [comment]
I built out the modern sites for the ATD work groups that need it for the migration. 

- Finance
- Transportation Development Services
- Right of Way Management Division
- Human Resources
- Data and Technology Services
- ATSD
- SMB

All others need archiving or linking for historical document repository

**Comment by amenity** [comment]
🙌😎 Thanks, @dianamartin !

**Comment by dianamartin** [comment]
@amenity it's not quite done...I'll be creating new issues for that.
