### ISSUE TITLE
Onboard Jace

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#644]
Jace starts on 11/4!

### Accounts
- [x] new Employee form (John)
- [x] Network account request (John)
- [x] Phone request (John)
- [ ] 1Password
- [x] Slack
- [x] Google Drive
- [x] Github Team
- [x] DTS Email Group (John)

### Software
- [ ] Zenhub Extension
- [x] Docking station driver

### Hardware
- [x] Desk/Office Space
- [x] Computer
- [x] Monitors
- [x] Docking station
- [x] Chair
- [x] Power supply
- [x] Keyboard
- [x] Mouse
- [ ] Badge

### Meetings
- [x] monthly team
- [x] dev sprint planning
- [x] discovery day

### Communications
- [x] Lunch
- [ ] newsletter announcement
- [ ] email to Cameron Rd employees

**Comment by amenity** [comment]
@johnclary he's good with common people's keyboard, but wondering if we should get him a chair?

**Comment by johnclary** [comment]
@dianamartin what's our chair situation? need one for jace. cc @amenity

**Comment by dianamartin** [comment]
@johnclary @amenity we have a guest chair currently at the desk space for him. No new chairs unfortunately.

**Comment by johnclary** [comment]
I've submitted the new emp request form via Service Now

**Comment by johnclary** [comment]
@amenity @TracyLinder i added jace to slack and invited him to our github org/team
