### ISSUE TITLE
Knack Environment Clean-up

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6443]
COMBO
- [x] Data Tracker [John/Diana] 

DEV ASSIST
- [x] VZA [Surbhi] - Dev. assist
- [x] Signs and Markings [Diana] - Dev. assist

SURBHI
- [x] DTS Portal [Surbhi] 
- [x] Shared Mobility [Surbhi]
- [x] ATD Forms [Surbhi]

CHRISPIN
- [x] Visitor Sign-In [Chrispin]
- [x] RPP [Chrispin]
- [x] ROW [Chrispin]
- [x] TDS [Chrispin]
- [x] HR [Chrispin]

DIANA
- [x] Finance [Diana]
- [x] Street Banners [Diana]
- [x] Parking Enterprise Reporting Portal [Diana]
- [x] ASMP [Diana]

**Comment by dianamartin** [comment]
Diana's To Do List
- [x] Finance
- Deleted the `TEST | APR 4 2021 | Finance and Purchasing System`
- Updated App Inventory
- Renamed Backup to Test, updated app inventory
- [x] Street Banner
- Deleted the `TEST - Street Banners Program Portal | 28 DEC 2020`
- Updated App Inventory
- Renamed Backup to Test, updated app inventory
- [x] ASMP
- only had 1 environment
- [x] Parking Enterprise Portal
- only had 1 environment
- [ ] Signs and Markings
- Deleted the `BACKUP | APR 22 2021 - Signs and Markings Operations`
- waiting until Surbhi comes back to make sure she's not using the other 2 TEST environments

**Comment by ChrispinP** [comment]
Recent HR and Visitor Sign In backups updated to test environments. For ROW, TDS, & RPP backup and old test environments removed. Updated App Inventory accordingly for all 5 apps.

apps assigned to me are now complete

**Comment by SurbhiBakshi** [comment]
Surbhi's notes - 

- [ ] Backup | ATD Forms | April 22 2021 
- [ ] Test | Shared Mobility Operations | March 11 2021
- [ ] Backup | Shared Mobility Operations | 23 April 2021

**Comment by dianamartin** [comment]
@dianamartin do this: Deleted the `TEST | SMB - 17 MAR 2021 | Signs and Markings Operations`

**Comment by dianamartin** [comment]
Deleted SMB 17 MAR 2021
