### ISSUE TITLE
Explore Vision Zero read-replica database

### ISSUE THREAD

**Issue by phanaq** [cityofaustin/atd-data-tech#6444]
Become familiarized/comfortable with the VZ read-replica database.

**Action Items**
- [x] Research and establish working environment for project (DBeaver vs Jupyter)
- [x] Make first attempt query for crashes/units/persons
- [x] Create basic data visualizations and notes on data

**Notes**
- Reference updated CRIS data dictionary (excel file) provided by Xavier 
- Completed basic analysis of vehicle characteristics
- Created basic decision tree models to predict crash severity based on vehicle characteristics

Work can be found in vz_exploration.ipynb

**Comment by dianamartin** [comment]
Closing as the CIC Fellowship has ended on 8/20/21.
