### ISSUE TITLE
Meeting: Builder Huddle HR Employee List Automation

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6445]
Meeting schedule 6/29
Github issue #6355

**Comment by moorerst** [comment]
Product evaluation: https://atd.knack.com/dts#project-evaluation/

**Comment by moorerst** [comment]
Notes:
Reviewed the workflow diagram Diana created

Questions from the discussion:

- How long is the delay of getting the EIN into Banner
- When/Who updates the ATD Employee DL's
- When is the email address available from CTM
- What is Scott's role in the NERF
- What are some of Scott's pain points

Next Steps:

- continue with discovery 
- set up meeting with Scott, Gilda and Meredith
- set up the trial Banner integration 
- investigate the daily G: drive Active Directory report that can be
 provided by Jeffery H at CTM 

Sample NERF from ServiceNow
[Patrick NERF.pdf](https://github.com/cityofaustin/atd-data-tech/files/6743210/Patrick.NERF.pdf)

**Comment by dianamartin** [comment]
We answered Meredith's follow-up question, but she hasn't responded to that email from last Thursday. New inquiry is on a different issue.
