### ISSUE TITLE
Knack ETL background work

### ISSUE THREAD

**Issue by phanaq** [cityofaustin/atd-data-tech#6447]
**Action Items**
- [x] Set up docker configuration & follow dev docs
- [x] Follow Knackpy user guide, try to download & manipulate Knack data using Knackpy
- [x] Explore Knack test application through "builder" mode

[Resources](https://docs.google.com/document/d/1wf3VYbAB4ETAtZmDGNqkDBncwEfyD4RB2uA-X4axwBI/edit)

**Notes**
- Successfully able to follow dev docs/load app metadata, but still some confusion over how to set up a new ETL
- Comfortable using Knackpy to download/manipulate data

**Comment by dianamartin** [comment]
Closing as the CIC Fellowship has ended on 8/20/21.
