### ISSUE TITLE
Recruit 3 New Techs for Pilot Phase

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#645]
@dianamartin we want to add three additional techs to the mobile signals pilot. Would you work with Billy to get this done?

**Comment by dianamartin** [comment]
Skyped Billy, his response:
>1. Roldan Coronado
>2. Randy Palos
>3. Ed Eberle

**Comment by dianamartin** [comment]
Follow up convo
Me:
>Should we do another meeting to get them acquainted or did you want to just tell them to click the new mobile signals button?
 
Bolander, Billy:  
>click the button - lets see how they do cold

Billy:  
>give it a week or two to collect the feedback if thats ok
 
>perfect, so like last week of oct?
>or earlier?
 
Billy:  
>give it a week or two to collect the feedback if thats ok
 
>perfect, so like last week of oct?
>or earlier?

Billy:
>sounds good
