### ISSUE TITLE
Analysis: ROW Permitting Review Process Attempt Types

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6453]
### As part of our effort to create a single ROW review process that works across all ROW permit types, we need to identify the process attempt types we will use and what features each attempt should have. 

- [ ] Identify any current features/attempt types that cannot be accomplished with our one process approach
- [ ] Identify each attempt name & it's purpose
- [ ] For each attempt, document any validations and kick-off procedures
- [ ] As part of this work, we'll need to identify the permit status workflow (internet pending, pending, awaiting update...) and incorporate that into the attempt procedures.

**Comment by TracyLinder** [comment]
**Attempt types we need to further analyze:**
- Expired
- All attempts on Valet/Street Vendor annual renewal processes
    - Annual renewal, update issue & expiry dates
- TURP - Event rescheduled
- Every attempt on the ROW Admin process

**Comment by TracyLinder** [comment]
### Process Name: ROW Permit Review
_Documentation of process attempts & their functions_

Note: We don't need to capture when the review begins (w/ an attempt) because comments will be sent to the customer almost always on the same day as review begins. 

**Attempt Name: Information Request**
_Purpose: Informing the customer that there are missing requirements_
- Validations before attempts are saved: 
    - Do not save attempt if there are no open/unresolved deficiencies
    - Throw an alert window if unpaid bills exist, or if unbilled fees exist 
- Forward Actions: 
    - Update folder status to 'Pending Customer Action'
    - Email the applicant the review deficiency report
    - Update the process status to 'Deficiencies'
    - (Keep the process open)
    - Assign the process to the user who saved the attempt



**Attempt Name: Approved**
_Purpose: Recording approved review and informing the customer_
- Validations before attempts are saved: 
    - Do not save attempt if there are open/unresolved deficiencies
    - Throw an alert window if unpaid bills exist, or if unbilled fees exist
    - Validate folder infos (permit specific; TBD) 
    - Validate people info (permit specific; TBD) 
- Forward Actions: 
    - Insert fees (for certain permits; TBD)
    - Update folder status to 'Pending Permit', or, if there are unpaid bills 'Pending Payment'
    - Close the process
    - If there are no unpaid bills, send applicant email notification of approval
    - If there are unpaid bills, send applicant email notification of approval w/ the invoice attached
    - Assign the process to the user who saved the attempt



**Attempt Name: Rejected**
_Purpose: Recording reject review and informing the customer_
- Validations before attempts are saved: 
    - Throw an alert window if unpaid bills exist, or if unbilled fees exist
    - Do not save attempt if there are no open/unresolved deficiencies
- Forward Actions: 
    - Update folder status to 'Rejected'
    - Close the process
    - Email the applicant the review deficiency report
    - Update the process status to 'Closed'
    - Assign the process to the user who saved the attempt


**Attempt Name: Response Received**
_Purpose: Informing staff that the customer has resubmitted missing requirements, and another review is needing to be done._ 
- Validations before attempts are saved: 
    - None
- Forward Actions: 
    - Updates folder status to 'Pending Staff Action'
    - Emails folder applicant a confirmation email
- **Problem**
    - Customer may need to submit multiple attachments. That means we can't remove the resubmittal attachment type from the portal view, and we may need to go the self-assign route for resubmittals.

**Comment by TracyLinder** [comment]
@vschandramouli the notes from our last meeting are complete. This one is yours now.
Please schedule the next meeting for this, and start discussing a possible process specifically for renewals/extensions, and what those attempt types might be. 

We still need to ask stakeholders about:

- The attempt type 'Event Rescheduled' on the TURP permit
- How the process 'ROW Admin' is being used

**Comment by TracyLinder** [comment]
**Note to Self:**
- We need to add to the forward actions that when the customer is emailed the review deficiency report, the system should also attach a copy of that report to the attachments tab. The attachments need to be viewable on portal by the applicant.

**Comment by vschandramouli** [comment]
The attempt type 'Event Rescheduled' on the TURP permit (part of the TURP Review Process) - Currently not being used.
How the process 'ROW Admin' is being used - Not used on TURPs. Used in EX folders for extensions. Possibly also used to void or withdraw permits.

**Comment by TracyLinder** [comment]
### Update Oct 2024 & Closing
- This documentation is done in the Miro workflows created by Ulfath for the ECM
- The documentation is missing the attempts we have but don't use, and using it to clean up the processes. 
- The analysis is complete.
