### ISSUE TITLE
VZD Sprint Review #6

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#646]
### Agenda

------
- [x] Schedule meeting
- [x] Meet
- [x] Attach meeting notes to this issue
- [x] Create resulting issues

**Comment by mateoclarke** [comment]
https://docs.google.com/document/d/1MDHaApLsQ-_akUVLMUn0Eh05HKjYmrjgL_mURtwS9WQ/edit#heading=h.3sdgu3b3w33l

**Comment by amenity** [comment]
@mateoclarke - is this ready to close?

**Comment by mateoclarke** [comment]
yes
