### ISSUE TITLE
TIA Memo Data Page Updates

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6461]
### Updates to the Memo Data page after stakeholder review:

- [x] Remove all memo blurbs; only publish the raw data
- [x] Data to publish: Memo data & status, Case/project info, Mitigation Tables, Submittal date for the most recent TIA submittal.

**Comment by TracyLinder** [comment]
@ChrispinP can you please add an estimate to this when you have time.

**Comment by ChrispinP** [comment]
Mitigation Tables added to Memo Data page, removed fields without data being pulled. Cleaned up organization.

**Comment by TracyLinder** [comment]
Closing.
