### ISSUE TITLE
Bug: TIA segment map new tab

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6462]
![Screen Shot 2021-06-22 at 1.21.17 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/80bb6f6c-8ec4-4bef-b982-2d550c55c07c)

**Comment by ChrispinP** [comment]
@chiaberry  Since this is a custom menu, we need to update the function to pass an additional value to the list item (feature-map) on the Mitigations page so it may open in a new tab.

`${dropdownMenuItem(recordId, "feature-map", "fa-road", "Segment & Intersection Map")}\`

**Comment by TracyLinder** [comment]
Reviewed w/ stakeholders. Looks good, closing.
