### ISSUE TITLE
TIA customer application help text

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6463]
### Do not press the back button; you will be able to edit your application before submitting.

![Screen Shot 2021-06-22 at 1.08.39 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/75835cfa-848b-4329-bc4f-d747c0af782b)

**Comment by ChrispinP** [comment]
Added Application Header and help text to application pages. 
![image](https://user-images.githubusercontent.com/67915167/124148640-71b9a800-da55-11eb-847a-4e1705ea79fe.png)

Ready for review

**Comment by ChrispinP** [comment]
Header text is now updated to be:
![image](https://user-images.githubusercontent.com/67915167/125827854-5f68f241-000a-42ed-aae6-911b79ca4b09.png)

Footer text is now updated to be:
![image](https://user-images.githubusercontent.com/67915167/125827783-e11f5da6-6c37-40a5-bdc7-239167cd25d9.png)

**Comment by ChrispinP** [comment]
Based on Technical Review, we updated the language a bit more and warning messages.
