### ISSUE TITLE
TIA Customer Application: Re-order project location fields

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6464]
### The stakeholders requested that the customer first enter the project location(s), then be prompted for the council district. 

![Screen Shot 2021-06-22 at 1.05.12 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/8c78689a-07f3-43ae-8305-445294c9ca71)

**Comment by ChrispinP** [comment]
Added Council District after the primary address entry and trips per day for both the edit case details and project information pages
![image](https://user-images.githubusercontent.com/67915167/124009294-0911f300-d9a3-11eb-9f6e-d4bf637a6e72.png)

Ready to review

**Comment by TracyLinder** [comment]
Reviewed w/ stakeholders. Looks good, closing.
