### ISSUE TITLE
TIA: New mitigation improvement type 'other'

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6465]
### Add a new mitigation improvement type: Other

**Comment by ChrispinP** [comment]
Improvement list alphabetized for ease of use and added Other option
![image](https://user-images.githubusercontent.com/67915167/123174937-90f97980-d446-11eb-994e-e57fbcad6387.png)

**Comment by ChrispinP** [comment]
Edit Improvement display rules added for the Other option and fields are hidden if Improvement is blank

![image](https://user-images.githubusercontent.com/67915167/123175768-f00bbe00-d447-11eb-985e-5ddbfbcc8033.png)
![image](https://user-images.githubusercontent.com/67915167/123175785-fa2dbc80-d447-11eb-9a0f-ac961f0c5e45.png)

**Comment by ChrispinP** [comment]
complete, ready to review

**Comment by TracyLinder** [comment]
Reviewed w/ stakeholders. Looks good, closing.
