### ISSUE TITLE
TIA Segment Map Research 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6466]
Chrispin will ask Andrew about the mitigation map. 
- It's difficult to view street names and orient yourself when looking at the map. 
- Also ask him if it's possible for the map to keep a memory of the address that you've already entered, or a feature to allow users to move around and come back to the previous location easily.

**Comment by TracyLinder** [comment]
**Diana's feedback**

- When you're zoomed out, the segment ID's shouldn't be so prominent. 
- The zoom level should be closer to the street before the user sees the segment ID's![Screen Shot 2021-06-23 at 1.10.29 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/305529a9-d5d9-4d09-8f05-64dcdc86c7e5)

**Comment by ChrispinP** [comment]
Increased transparency on intersection points and segment IDs. Unbolded Segment IDs and pushed down one zoom level. Street names should be easier to see at most zoom levels now
![image](https://user-images.githubusercontent.com/67915167/123458697-f4042100-d5aa-11eb-80c6-2e1a33d49166.png)
![image](https://user-images.githubusercontent.com/67915167/123458740-02523d00-d5ab-11eb-82e7-dfa18234720a.png)

**Comment by ChrispinP** [comment]
We increase map width and included the Bookmark and Draw widgets. Will need to train/show users how to use these map features.

ready to demo/review

**Comment by TracyLinder** [comment]
Reviewed w/ stakeholders. Looks good, closing.
