### ISSUE TITLE
Migrate DTS website to Nextjs

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#6476]
The idea here would be to go ahead and port over the existing site to use the Next.js framework for React. This would be a good opportunity fo us to make a low cost investment to see if we can use this framework for other projects going forward and evaluate the level of effort to migrate and existing application.

@johnclary @amenity

**Comment by johnclary** [comment]
Agreed. One major benefit (as @mateoclarke has pointed out) is to use [hybrid static rendering](https://nextjs.org/docs/basic-features/pages) for SEO and performance.

**Comment by jgabitto** [comment]
I've included information about the migration in the the `README.md` of the `jg_migrate-to-nextjs` branch in the `atd-product` repo.

**Comment by mateoclarke** [comment]
All the work that Jorge completed moving the site to Next.js is great. The last piece missing as far as I can tell is to troubleshoot why the deploy preview build is failing.

First, it seemed like the [build command was failing](https://app.netlify.com/sites/atd-product/deploys/612fd732f2a8090007ff3b00#L206-L214). So I tried to install the `netlify/plugin-nextjs` library which seemed to be the community standard for configuring NextJS apps on Netlify, but now the site is failing with that plugin with a [different error](https://app.netlify.com/sites/atd-product/deploys/61328aae41a385b153fc2c9e#L250-L255).

This issue needs more troubleshooting.

**Comment by johnclary** [comment]
@mateoclarke i was able to build locally, so i forked and tried to deploy to my personal netlify. the deploy failed with a PostCSS dependency issue. this is not my wheelhouse, but maybe we should start with an empty package-lock and re-install dependencies one by one?

**Comment by johnclary** [comment]
I did ☝️  in a [new PR](https://github.com/cityofaustin/atd-product/pull/24).

It's [still failing](https://app.netlify.com/sites/atd-product/deploys/614927d54d890200aaff9406):

```
Error: '/opt/build/repo/build/index.html' already exists
```

Googling was not particularly helpful. I'm stopping there.

**Comment by johnclary** [comment]
Ok, this was clearly driving me nuts. Should have just read listened to the error message. [Here](https://github.com/netlify/netlify-plugin-nextjs/issues/464#issuecomment-884954812) is a resolution to someone who had the same problem.

It appears that this was a legacy file from CRA. Running locally must just overwrite it, but the netlify plugin doesn't handle it the same? In any case, deleting it resolved the build.  The good news is that this file was a reminder that we need to implement `<meta>` tags, which are in that file. I think the Next way of doing this with is the `Head` [component](https://nextjs.org/docs/api-reference/next/head).

[Here's](https://deploy-preview-25--atd-product.netlify.app/) the preview.

I notice at least one minor styling issue. The cards on /projects have underline decoration.

**Comment by johnclary** [comment]
also—gotta mention that Jorge's work on this was truly awesome! this was a huge undertaking.

**Comment by amenity** [comment]
Preview looks flawless!
