### ISSUE TITLE
Meeting - Usability testing with Shared Mobility team

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#6477]

**Comment by SurbhiBakshi** [comment]
Meeting has been scheduled for Friday 06/25 with Mary V and Andrea M.

I will make a script of the tasks that the SMO team will test, and @patrickm02L will review that before the meeting.

**Comment by SurbhiBakshi** [comment]
@patrickm02L - here is the [script](https://docs.google.com/document/d/1TTXvyTsG6MP6oXt08pGogsc-fgHc8wKy2Q74scHnbfY/edit?usp=sharing) for the tasks that we would like to see the SMO team go through. I can do a demo at the start of the meeting, and then we can get Mary and Andrea to go through the steps.

**Comment by patrickm02L** [comment]
@SurbhiBakshi Looks good. I made a few comments on follow up questions.

**Comment by SurbhiBakshi** [comment]
thanks @patrickm02L!

**Comment by SurbhiBakshi** [comment]
[Surbhi's notes](https://docs.google.com/document/d/1C99LHNZYMy5PO6Bp2WtM8vGNCWIbEVUQ-zVGUs1R1QA/edit?usp=sharing)
[Patricks's notes ](https://docs.google.com/document/d/1TAvoe8AJnZMSeb4Ls0rmqKcs55kCZt2WaP40_2Zx8jk/edit?usp=sharing)

**Comment by SurbhiBakshi** [comment]
Three broad themes that came up in the meeting were. These three broad themes and smaller changes along with a possible bug are noted below. 
1. The renewal process for licenses and permits needed to be refined so users understood the sequencing of the steps - # 6534
2. Users wanted the Status of the License to trigger the statuses of associated permits and provider contacts - #6535
3. Some research into how users could access and report data in case of a PIR - #6536
4. There were smaller changes and additions - #6537
5. When user select the Sitdown Scooter option, the chart for Permits by Type populates both Sitdown Scooter and Scooter. Sending this to Knack as a possible bug.
