### ISSUE TITLE
Test tablet ---> cloud storage workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6478]

**Comment by dianamartin** [comment]
## Testing Steps
- [ ] Create Box.com folder shared 
- [ ] Email link to myself
- [ ] Log into tablet
- [ ] Open tablet
- [ ] Take pictures

### Option 1: Shared Box.com URL (no user accounts for users uploading photos/videos)
- [ ] Click Box.com URL link from email 
- So it opened up the Box folder, but either prompted to download Box app or open in Box app
- This option needs to get CTM involvement and request Box be added to the tablet profiles
- [ ] Upload test images

### Option 2: OneDrive
- [ ] Had to log into OneDrive using city credentials
- [ ] Created new folder
- [ ] Clicked the OneDrive app on tablet home screen
- [ ] Shared with Susanne
- Need to find out if there is a limitation

**Comment by dianamartin** [comment]
- [ ] Reach out to Danny C. (CTM) to see if Box.com can be added to AirWatch Profiles
- [ ] Not log into box.com to upload photos

**Comment by dianamartin** [comment]
I put in a ticket to get the Box.com app installed and have a shortcut on the tablets. Issues here #6572

**Comment by dianamartin** [comment]
# Option 4
Create a Teams with everyone
Open Teams app
Find group
Select the channel
Create a conversation or insert an app

**Comment by dianamartin** [comment]
# MS Teams 
## Test 1 - Upload 1 photo/file
- [x] Worked smoothly

## Test 2 - Upload multiple photos/files
- [ ] 

## Test 3 - Upload photo - activate camera, take live picture
- [ ]

**Comment by dianamartin** [comment]
Tested enough to be able to get the stakeholder a good idea of which product to use, closing.
