### ISSUE TITLE
[Feature] Project Funding

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6481]
New "Funding" tab to track project funding: 
-   eCAPRIS Subproject ID (optional; only one per project but needs to go in a table to track the amount)
-   Funding Sources (table)
    -   [Source](https://docs.google.com/spreadsheets/d/1c_7AjATgxclZqcduLJRapUUawQv6R1pY7DcdBfD8dhc/edit#gid=1209041359)
    -   [Program](https://docs.google.com/spreadsheets/d/1c_7AjATgxclZqcduLJRapUUawQv6R1pY7DcdBfD8dhc/edit#gid=1209041359) (optional) 
    -   $ amount
    -   [Status](https://docs.google.com/spreadsheets/d/1c_7AjATgxclZqcduLJRapUUawQv6R1pY7DcdBfD8dhc/edit#gid=659213456) 
    -   FDU - ~link to eCAPRIS (there is a URL for each FDU in eCAPRIS, will handle like the Subproject ID field)~
    -   Description

Future enhancements
-  Hyperlink to eCAPRIS FDU pages - there is a URL for each FDU in eCAPRIS, but [it's going to be a lift to construct](https://github.com/cityofaustin/atd-data-tech/issues/6481#issuecomment-901376878)
-  Pull ecapris financial numbers nightly (appropriations, encumbered, spent, balance)
- File attachments #6992 

### UI
![Funding 1 0](https://user-images.githubusercontent.com/1463708/130153465-f0bf7f1a-ea82-4d1a-84dc-8271c201f6b6.png)

**Comment by amenity** [comment]
Wrinkle wrt the FDU link to eCAPRIS, @johnclary - 

Whereas the eCAPRIS URLs can be constructed if the subproject ID is provided, the FDU URLs may only be accessible via an ID: The URL for FDU `8112 2507 A016` is `https://ecapris.austintexas.gov/index.cfm?fuseaction=fdus.fduData&FDU_ID=99502`... 

<img width="855" alt="Screen Shot 2021-08-18 at 1 13 54 PM" src="https://user-images.githubusercontent.com/1463708/129960903-5cfa3c26-1718-40e6-b230-ecc655158e85.png">

**Comment by johnclary** [comment]
@amenity boo. good to know. in that case we will need to hold off on linkable FDUs until we start pulling in data from eCapris to create an FDU lookup table. When we do that we can pull in the FDU IDs and create the proper links. For now I'd say we'll have to leave this as a text field.

**Comment by johnclary** [comment]
@amenity in discussion with Mateo and Patrick we had a few questions/todos.

### File attachments
We need to think through what it means to store a file at the funding record level. Would it be ok to add a "File Category" drop-down to the existing file attachments UI, where the user could pick things like "Funding Commitment" or "Plans" or whatever other file types might be common? In this case, a file attachment would not be linked directly to a funding record. The user would use the existing "Files" tab to upload files related to funding. 

The other task is to define the data model/schema for this. There are some existing funding-related tables in the DB that are similar but don't quite match this. We need to review those tables and define exactly what the data model should look like for this. 

For funding source and program pick lists—your spreadsheet has dupes in each column. I take it we can just reduce those to the list of unique values, or do those still need to be refined?

**Comment by johnclary** [comment]
I started #6986 to flesh out the data model. I didn't have time to finish it. Will do tomorrow.

**Comment by amenity** [comment]
@johnclary I don't see why file attachments on the file page wouldn't work, but it creates additional steps in that workflow and makes it more difficult to organize and access this particular type of file. The two pages seem more likely to fall out of sync (funding source deleted/updated but the file is not) if we divide them up. And the name/description/date/size information that is provided by the file table is superfluous for this use case...

Yes, we only need unique values. We should be 90% of the way there, but NW still needs to review and sort out some gunk.

**Comment by johnclary** [comment]
@amenity that makes sense. I think we should separate the file attachments as a separate issue and implement the basic functionality first. I finished writing up the necessary DB changes (including mock data) in #6986. That needs to be reviewed and estimated by a dev @mateoclarke.
