### ISSUE TITLE
Purchase XD licenses

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6485]
- [x] Create [purchase request](https://atd.knack.com/finance-purchasing#purchase-requests/purchase-request-details/60d5066b35dc0e001e778867/) ✍️
- [ ] Purchase and [file paperwork](https://austininnovation.slack.com/archives/CHXHA8YAU/p1574792382137800) 💸 📁
- [ ] Add to [DTS subscription list](https://atd.knack.com/dts#it-subscriptions/add-subscription/)
- [ ] Distribute 🎅

**Comment by amenity** [comment]
[CTM help ticket](https://atx.service-now.com/sp?id=ticket&table=incident&sys_id=a8521f141b2df410f9edc8451a4bcbc9). Have also asked Scott for help.

**Comment by amenity** [comment]
@patrickm02L @johnclary - Scott purchased the licenses through CTM.

**Comment by patrickm02L** [comment]
Thanks, I have installed XD on my work computer!
