### ISSUE TITLE
Knack ETL background work - Docker research

### ISSUE THREAD

**Issue by phanaq** [cityofaustin/atd-data-tech#6488]
After setting up the docker configuration and following the [update dev docs](https://github.com/cityofaustin/atd-knack-services/tree/staging/dev), I still do not have a strong understanding of how docker works.

**Action Items**
- [x] Take a deeper look into how [docker](https://docs.docker.com/) works
- [x] Read through the [atd-knack-services docs](https://github.com/cityofaustin/atd-knack-services#load-knack-records-to-postgres) to ensure understanding - schedule meeting with John or Chia if necessary

**Comment by dianamartin** [comment]
Closing as the CIC Fellowship has ended on 8/20/21.
