### ISSUE TITLE
Modify Digital Petition Template

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6490]
Update Digital Petition Template with the modifications provided by stakeholders

**Comment by dianamartin** [comment]
We received email from Ryan on updated form language. I added the language to the form. 

## Change Review
### Current Language
We, the undersigned, hereby petition for the designation of the residential frontage along San Marcos Street between Spence Street to Taylor Street for the hours from 7:00 A.M. to 6:00 P.M. on Monday through Friday as a Residential Permit Parking (RPP) area according to guidelines and procedures established by the Austin Transportation Department. We understand that the residents will have to purchase the parking permits yearly for a fee. The fees go toward permit processing, sign fabrication, installation and enforcement.  The fee for each permit is $15 per permit plus sales tax, up to 4 (four) permits per eligible household. Types of permits include resident decals and visitor hang tags (Visitor hang tags have a max 2 per household). 

Note: The Street mentioned above will be considered for RPP designation only if the affirming signatures below represent at least 60% of all the households (residents only) adjacent to the street.  ALL PROPERTIES (INCLUDING EACH APARTMENT UNIT/DUPLEX) ON THE STREET MUST BE LISTED ON THE PETITION.  Only one signature from each household will be considered.   Resident vehicle license plate numbers are collected to determine eligibility based on non resident/commuter vehicles parked within petition area.


### New Language
We understand by signing the below petition we are supporting the implementation of Residential Permit Parking (RPP) on the requested street for residential households. A Residential Permit Parking (RPP) area shall follow the guidelines and procedures established by the Austin Transportation Department. 
We request the following boundaries and times for Residential Permit Parking:
•	70 San Marcos Street between Spence Street and Taylor Street
•	Residential permit parking hours from Monday through Friday 7:30 A.M. to 6:00 P.M. 
We understand that our petition must meet the following guidelines:
•	60% of all the households (residents only) adjacent to the street must support implementation of RPP.
•	All residential properties (including each multi-family unit) on the street must be listed on the petition.
•	Only one signature from each household will be considered.
•	Resident vehicle license plate numbers are collected to determine eligibility based on non-residents/commuter vehicles parked within petition area.

**Comment by dianamartin** [comment]
@moorerst you can review changes [here](https://cityofaustin.formstack.com/forms/rpp_petition)

**Comment by moorerst** [comment]
@dianamartin changes look good. I noticed there is no permit information in the new language. Send email to Ryan asking if cost should be left off or use the permit cost links.
https://atd.knack.com/parking#permit-costs/
https://atd.knack.com/parking#single-use-day-pass-costs/

**Comment by dianamartin** [comment]
@moorerst yeah, good catch on that!

**Comment by dianamartin** [comment]
We need to add permit information about permit costs, use this [link](http://www.austintexas.gov/page/purchase-permits-residential-parking)

**Comment by dianamartin** [comment]
I added a line for "Review Permit Cost Information"

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/1e7390a5-9189-4a2b-b02d-a3028889f372)

**Comment by moorerst** [comment]
@dianamartin last question I have is about the Phone Number. Can we add the format the phone # should be entered in either in the field itself or in the note below?

**Comment by dianamartin** [comment]
Stephanie and I had a conversation about this:

![image](https://user-images.githubusercontent.com/21112975/123694562-1aca8d80-d81f-11eb-8b52-a673372f3c61.png)

**Comment by moorerst** [comment]
Language has been updated and approved by the stakeholder. Closing issue.

**Comment by moorerst** [comment]
@dianamartin 
Email from Ryan
I just reread the petition and wanted to change the support/oppose/go with majority language slightly. Can you please change the language to what I have written below. 

**Please check one selection to indicate whether you are in Support or in Opposition to RPP on your street or Go with the Majority***

**Comment by dianamartin** [comment]
- change language
- email user the update
>The language has been modified per your request. See template form.

**Comment by moorerst** [comment]
Updates that have been requested by the stakeholders have been made. Closing this issue.
