### ISSUE TITLE
Stakeholder Training for Digital Petition

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6492]
- [x] Receive list of people to be trained from Ryan
- [x] Schedule training

[Training Guide](https://docs.google.com/document/d/1h5kUKP3LnmotI5WypN0SUU99i9saoFC8oxlPg3v6sHI/edit#heading=h.hopbc8jkiro2)

**Comment by dianamartin** [comment]
# Internal user testers
- [ ] Joseph A.
- [ ] Mary V.
- [ ] Ryan R.
- [ ] Andrea M.
- [ ] Timothy S.
- [ ] David B.
- [ ] Eric B.
- [ ] Steve I.
- [ ] Richard D.

**Comment by moorerst** [comment]
@dianamartin this issue is for stakeholder training I will add the internal user testers list to issue 6491

**Comment by moorerst** [comment]
per email from Ryan they have not identified who will need training on the new process.

**Comment by moorerst** [comment]
Training scheduled for 8/17
Stakeholders Ryan and Mary have been invited to the training

**Comment by dianamartin** [comment]
I went through the `FormStack RPP Digital Petition Help Guide` with them. Showed them the change to the embed forms rather than just an plain old Google Map, the My Google Maps embed technique. After the meeting I emailed them the help guide again and helpful links to get started.
