### ISSUE TITLE
[Enhancement] Activity Feed 2.0

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6496]
We will rename "Activity Log" "Activity" and convert it into a more Facebook/Github-like interface that combines conversation with a changelog in chronological order. In doing so we will need to provide filtering/search functionality so that it remains usable even when it is very long. 
![image](https://user-images.githubusercontent.com/1463708/151268328-3d967052-50fe-438f-adcc-45113325cc1b.png)

This second generation of the activity feed will include 
- #6566 
- Improved readability of activity/changelog entries
    - #6552
    - #7121 
- Improvements to comments
   - "Are you sure" popup when user deletes comment (like project deletion confirmation)
- Navigation enhancements
   - Filter down to edits (in addition to comment types)
   - Pass all filter parameters in URL (hopefully can port over from comments tab implementation in #6995) example use cases:
       - From project summary page, click on history icon next to "Status update" and go to Activity feed filtered down to status updates

**Comment by amenity** [comment]
@patrickm02L - Could we consolidate this issue with #6566? They both have important pieces of information about the same potential feature, right?

**Comment by amenity** [comment]
Or would "Activity Feed 2.0" work for the name of the epic, and it could include: 
- #6566
- Enable search and filter on Activity Feed
- Improve readability of changelog entries

**Comment by patrickm02L** [comment]
@amenity I think we could re-author it to be "Activity Feed 2.0" and include #6566.

**Comment by johnclary** [comment]
Discussed in grooming today.

Questions to answer:
- does the current activity log table schema capture all of the updates we need to remder
- which triggers are missing from the Hasura event configuration
- should we spike on Moving away from the lamnda/sqs-based log, and implement our own database triggers for this purpose?

Todo:
- @johnclary create issues that that break this feature into smaller pieces

**Comment by johnclary** [comment]
For reference, we have a list of tables that _should_ be tracked in the activity log https://github.com/cityofaustin/atd-moped/pull/873/files#r1023218444

**Comment by johnclary** [comment]
We've done a lot of great work on the activity feed since this was authored. Although we never went through with the complete vision for an integrated comments + activity log. Projects end up accumulating a whole lot of activity, so I have some doubts about pursuing this any further being worthwhile. There's plenty of room for UI/UX improvement on the comments tab itself, but i'm going to close this epic.
