### ISSUE TITLE
Project: Business Intelligence (BI) Solution

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#65]
## Description
The goal of this project is to identify a business intelligence solution for use by ATD employees and all of our stakeholders. The solution should deliver real-time performance monitoring, and drive meaningful insights from our data in an efficient and transparent way. Our goal is to empower ATD staff, ATD stakeholders, and the public to leverage ATD data to inform their work.

### Resources
- [Project Folder](https://drive.google.com/drive/u/1/folders/1cYfTJUImvQRpLNgJM9PZ0Vexub299Sbc)

**Comment by amenity** [comment]
@johnclary - will you set an Impact for this?

**Comment by amenity** [comment]
@TracyLinder - I moved this over from the portal in April and it has some issues in it. Close/use as an index/reorganize... whatever works for you. 🏃‍♀️

**Comment by TracyLinder** [comment]
@amenity Thanks for looking out. I've updated this to project index standards.

**Comment by johnclary** [comment]
@amenity @TracyLinder we're going to pause on this until we hire our new PM. Tracy's priority is now Development Review.

**Comment by johnclary** [comment]
This did come up in the mgmt meeting yesterday, and remains a high priority to Rob + Peggy.

**Comment by TracyLinder** [comment]
### Update

This project is going back 'On Deck' until the new PM is hired and can manage it.

**Comment by TracyLinder** [comment]
ROW Project/Backlog Review Note: Pepper worried the folder status & process workflows will give the public inaccurate views of what is actually happening.

**Comment by johnclary** [comment]
Running list of pilot projects/use cases:
- Right of Way: permits by status or something (ask Tracy)
- Arterial Management: Traffic volume counts (requested by Brian C)
- Vision Zero things (as Jace)

**Comment by JaceDeloney** [comment]
**Status Update**
The official kickoff of this project should happen over the next month. There have been a number of requests that have recently come in related to BI. ATD management team has requested recurring reports on KPIs. Mobility Management has also requested a way to automate their monthly reports.

**Comment by JaceDeloney** [comment]
**Status Update**
We have reached out to MMC staff to see if they need help creating BI views using the new datasets we published a few months back. [Here](https://github.com/cityofaustin/atd-data-tech/issues/1241) is the issue where we completed that work. Still awaiting a response.

There has been no other work related to BI Discovery.

**Comment by amenity** [comment]
@johnclary @TracyLinder ... since Jace closed this, should pare down [these other issues](https://github.com/cityofaustin/atd-data-tech/issues/5024)?
