### ISSUE TITLE
Write interview guide

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6501]
Write interview guide

**Comment by janetchuhl** [comment]
[Interview Guide](https://docs.google.com/document/d/1l4RtxdRjh5duAR3DxbhFVsOyfyV0wGSCrPfkWHPosCs/edit) created.

**Comment by janetchuhl** [comment]
@patrickm02L ready for review

**Comment by patrickm02L** [comment]
The interview guide works well. I like the way you set up each section to roll into the next. The exploratory questions get at the heart of the PIOs process, their pain points, and their expectations. My only comment is to ask them if they wanted to share anything else you didn't go over in the interview.
