### ISSUE TITLE
Synthesize PIO in-person interviews

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6503]
@janetchuhl 
- Highlight [transcripts](https://drive.google.com/drive/folders/1Iy6AJGZHsbjiEDeD6NAN6ueq22CwAlfU?usp=sharing) and pull quotes
- Consolidate quotes into groups

@patrickm02L @janetchuhl @TracyLinder @amenity 
- Review and identify themes
- Discuss next steps — resident interviews? Ideation session with PIO? ??...

**Comment by patrickm02L** [comment]
@janetchuhl Here's the basic outline I was thinking of to help you with your Interview Guide. 

**Introduction & Consent**

**“Warm-up”**
_OK, let’s start by getting to know each other a little bit. [Interviewer offer a brief introduction to who you are and why you are interested in this work.]_ 

**Interview Questions** 
_[This section can be conducted as an experience-mapping exercise OR as a conversation. Interviewer should feel out what would be most appropriate for the particular interviewee. If using a timeline, the timeline should have 3 rows with space to include data for each type of data: Doing, Thinking, and Feeling.]_

**Reflection Questions** 
_[Offer praise and recap what you’ve discussed so far.] Now I’d like you to reflect on the conversation we just had as you answer the next questions._ 

**Concluding Questions** 
_[Offer praise & appreciation.] We’re almost done. I just have a couple of questions left to ask you._

**Comment by janetchuhl** [comment]
[Stakeholder Interview Guide](https://docs.google.com/document/d/1l4RtxdRjh5duAR3DxbhFVsOyfyV0wGSCrPfkWHPosCs/edit) created.

**Comment by patrickm02L** [comment]
Scheduled meeting for 7/8/21 to Review Janet's findings from the In-Person Interviews. During the meeting we'll consolidate findings into themes, and define next steps.

**Comment by janetchuhl** [comment]
Interview recordings [here](https://web.microsoftstream.com/group/99102985-3914-4798-8cd7-ec44fb849086?view=videos)
Transcripts [here](https://drive.google.com/drive/folders/1Iy6AJGZHsbjiEDeD6NAN6ueq22CwAlfU?usp=sharing)

**Comment by patrickm02L** [comment]
During the meeting we reviewed the quotes and findings from Janet's interviews. We still need to synthesize, so we schedule another session for 7/14.

**Comment by patrickm02L** [comment]
We've consolidated the research from the PIO interviews into a doc for ease consumption. The doc draws out the finding from the interviews and organizes them into Themes and Insights, and groups supporting quotes from the Interviews. 

[Mobility Project Viewer Summary for PIO Interviews](https://docs.google.com/document/d/1P8A4ocvQaGApe-_CKXhMvNTeYrguflOj7-xR6HHIRIE/edit?usp=sharing)

**Comment by patrickm02L** [comment]
Reviewed this doc, and sent it off to our PIO partners in conjunction with an Ideation work session we conducted on Monday, Aug. 2nd.
