### ISSUE TITLE
Propose new DTS web style guide

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6506]
- Inventory of current design standard across ~knack~, data hub, ~vision zero viewer~, and DTS website
- Propose basic font and color standards
- Re-think tile component used to preview projects and products

**Out of scope**
- Design system for use in our apps , e.g. reconciling Knack/VZE/Moped patterns

**Comment by amenity** [comment]
@patrickm02L - existing colors we're using in decks/docs, email signatures, & Github labels [here](https://drive.google.com/drive/u/0/folders/1dW57tTVZMJakahxS2JkRTkvKCRBV4P8_)

**Comment by patrickm02L** [comment]
Meeting Scheduled for 7/2/21 with Janet to go over preliminary designs.

**Comment by patrickm02L** [comment]
In order to get a sense of the colors I looked at the logo, and found an aesthetic that had transit oriented illustrated feel. 

![Aesthetic.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/0023f631-9d20-4ff6-98e3-48b46e9bce59)

From there, I compared the Austin logo colors, the current DTS colors, and tried to blend them together. The main change is replacing green with yellow. 

![Fonts and Colors.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/e1fa40bf-cf7f-47a3-b487-2777be8634c7)

**Comment by patrickm02L** [comment]
Screen captures of the current website. 

Home
![screencapture-austinmobility-io-2021-06-22-21_14_47.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/7e8c3372-d4a3-41c3-a25d-60c2694c289e)

Our Work
![screencapture-austinmobility-io-projects-2021-06-22-21_15_35.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/63b1df43-3d1c-4c22-b4e4-08ff9c6e1c29)

What We Deliver
![screencapture-austinmobility-io-products-2021-06-22-21_16_14.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/559bd0ab-4eff-4291-a93a-c5461904391c)

About Us
![screencapture-austinmobility-io-about-2021-06-22-21_17_01.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/8398e41c-cad5-4fe7-967c-57df7fe90510)

**Comment by patrickm02L** [comment]
I created wireframes to get the basic shapes and spacing and structure of the website. To get a quick read on the design language, I re-imagined the Home Page, a Projects (Our Work) page.

Home
![Home – New – 2.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/0d418ead-585a-4287-a70d-1754fc1e2a9d)

Projects (Website)
![Projects.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/60035fec-cb78-4cd9-aeb4-5e9a267fcc36)

Projects (Tablet)
![iPad Pro 10.5in – 2.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/3e2f723b-577f-4007-8653-e23ebf18fe22)

Projects (Mobile)
![iPhone 12 Pro Max – 5.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/869d5c92-c876-4ff5-bcda-abc968fdd7aa)

**Comment by patrickm02L** [comment]
Finally, filled in the Home page wire frames with images and some of the colors from the Proposed Color palate.

![Home – New – 1.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/7e9bfa2e-7058-409a-bae6-3a4713050fae)

**Comment by amenity** [comment]
I dig it!! Such a fresh, professional, streamlined design. You're awesome, @patrickm02L. 

I _would_ like to think a bit more about these colors. The City of Austin is doing a rebrand, and our colors were derived from my Github label color scheme... So I don't think we need to take either of these into account. Logistically speaking, maintaining the current blue (as you've specced) saves us from revising all of our existing templates. So I'd vote for keeping #0d3e79 and building off that!

**Comment by amenity** [comment]
Per the email Suzanne/PIO just sent out, the department is doubling down on the CoA seal and adopting a very simple blue/black/grey color palette. I'm up for adopting theirs. (And maybe throwing in a single bright highlight color for @TracyLinder 😉). 

I also like the greyscale with blue overlay effect:
<img width="1275" alt="Screen Shot 2021-07-09 at 4 13 37 PM" src="https://user-images.githubusercontent.com/1463708/125392889-91fa3880-e36c-11eb-9cdc-03195afd04d4.png">

**Comment by patrickm02L** [comment]
That works, I'm all for the minimalist approach.

**Comment by patrickm02L** [comment]
We've created a new color scheme for Moped that could be adopted to the new DTS Web Style Guide. Rather than reinvent the wheel with what I proposed earlier, I think we should use the colors described in the following issue. https://github.com/cityofaustin/atd-data-tech/issues/6712

**Comment by amenity** [comment]
@patrickm02L - will you get these from Jacob?  
- [Palette](https://user-images.githubusercontent.com/1463708/140802438-aa2793c5-0043-47f8-918e-e8bc5421b117.png) as adobe swatches?
- [Streetscape vectors](https://user-images.githubusercontent.com/1463708/140802238-27c6f1a9-dfa3-48f4-a0e9-98b5c6f15c70.png)
- [Icons](https://user-images.githubusercontent.com/1463708/140802589-67799069-28f9-4cfe-9753-a107f93b8c96.png) 
- DIN font if you want though I'm still on the fence about using it; don't like it enough that it's worth the overhead to using in docs/websites over easily accessible Google fonts

May also ask if they want to join forces w/ us in building/managing an icon library... I bought all of [these](https://drive.google.com/drive/folders/1YJo4dvBf9uL1uuVhvUE1RSFxU3YFcEpr) a few years ago

**Comment by patrickm02L** [comment]
#7687 has a good example of an updated homepage with the blue banner shown above.

**Comment by patrickm02L** [comment]
We've moved past the design proposal. All Issues are now being tracked in #10615 Epic.
