### ISSUE TITLE
New Sign Service Requests Should Not Default to "Open" Status in CSR

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#651]
Gilda reports that 311 service requests of type: Sign - New (code: SIGNNEWT) are defaulting to "Open" status in the CSR system. This setting was changed during the signs migration preparation, however these SRs are handled by Traffic Engineering. We did disable publication of this SR type to the integration, but apparently the default "Open"  status was not returned back to defaulting to "New".

**Comment by johnclary** [comment]
I reached out to Chandra and Sini and asked them to make the change.

**Comment by amenity** [comment]
@johnclary - any word on whether the change has been made?

**Comment by johnclary** [comment]
Nothing at all. Sending follow up now.

**Comment by johnclary** [comment]
Chandra tells me this was completed back in August. I asked Gilda to confirm if they're still dealing with this problem.

**Comment by johnclary** [comment]
Confirmed this is resolved.
