### ISSUE TITLE
Meeting: ATD Dashboard Discussion with AMD

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6513]
### Objective 
Jen has asked that we assemble a weekly report showing the status of devices in our transportation network (i.e. Detectors, DMS, CCTV, BBS, etc.) and their operational status.

The report would include:
-	Total number of devices
-	Number of working devices
-	Number Awaiting Repair
-	Number Repaired in the previous week
-	Number of days each device has been on the not working list

This meeting would be an initial brainstorming of 
-	What can be done with the data already being collected
-	What additional data could be easily captured
-	How to collect the data that is more elusive

This meeting will be a preliminary brainstorming session. Please forward to whoever you think should be invited.

### Participants
Brian VDW, Brian C, Billy, Lance, Frank, John and Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes
## Detection
Jen wanted a report of work completed that week. Free flow field, it wasn't easy to decide which was detection repairs. Report back that it's broke. Was supposed to fix it, but just was a field check. 

Detection status log - whether or not a detector is working or not. It is the technician's responsibility to update the Detector page. 
- Don't know if they're doing that
- Even with the mobile app, it's challenging to get them to do their computer work once work has been completed so it's updated

Diana thinks: Work Order Specifications! 

Detection types: equipment type

Frank G - entry in Data Tracker is fairly easy
It's getting the technicians to do the detection assessment - Update Detection
- Close out detection work order, Loops, SBS/Camera/CCTV
- Timing issues, Stuck on Red
- Review HIPS report
- Closing WO and updating detection
- Supervisor updates the detection too if not completed by 
- MMC updates the detection too 
- Detection Report: type in broken (the fix isn't in Data Tracker, it's going to be "man hours")

Frank to coordinate: Pull down menu

# Requirements to Track
- Want to know the status of detection on a week to week basis
- Assets: Detectors, DMS, CCTV, BBS, etc.
  - Total number of devices
  - Number of working devices
  - Number Awaiting Repair
  - Number Repaired in the previous week
  - Number of days each device has been on the not working list

Has Power BI Dashboard for Detection already (might need "Detection Status Log")
- Signals/DMS
- CCTV is more complex
- Not a problem to generate reports

**Comment by amenity** [comment]
@johnclary @dianamartin - good to close this?

**Comment by dianamartin** [comment]
I need to follow-up with Frank G.

**Comment by johnclary** [comment]
Added to AMD stakeholder discussions epic.

**Comment by amenity** [comment]
@dianamartin - check with Lance to ensure this is ready to close.

**Comment by dianamartin** [comment]
I ran into Lance in the hallway the other day 7/14 and asked if the dashboards have already been configured or if they'd like some assistance with them. He said he'd talk to Allyson and see. 

Allyson messaged me
> Lance mentioned you having an intern with some availability. We'd be thrilled to have the help, when do you think that availability would begin so we can get stuff together and schedule a kickoff?

**Comment by amenity** [comment]
@dianamartin - nice! Will you intro @phanaq and Lance/Allyson, or shall I?

**Comment by dianamartin** [comment]
@amenity You certainly can since you have more of the details about the CIC program :)

**Comment by dianamartin** [comment]
Follow-meeting to assist stakeholders #6692, closing this issue
