### ISSUE TITLE
GIMOB Meeting - July

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#6515]

**Comment by jaime-mckeown** [comment]
-  WPD and DSD have new Alternate GIS SPOCs, voted yes for both
- Vote for new setup for SDE External: Option 1 voted yes (Lee and Dwayne can help with any questions)
- GIS Modernization Project
   - went over the current status of the project, everything is still moving along
   - still identifying additional training needs at the next meeting
   - brought up the Creating and Editing Class again as there is nobody registered,  voted to remove the class and re-purpose the credits
- AGOL Subcommittee
   - Scheduled an Arcade Workshop after the conference, message Janny if interested
   - Questions about registering for Esri UC and what account to use. Register under your federated account
- Esri UC Subcommittee: probably moving away from Survey123 and moving to another automated form process
- GIS Remote Work Subcommittee: presents recommendations to the board, uploaded document to the Planner Board so it's available to everyone
- Geo Tech Management
   - Ortho's purchased and complete, still waiting on the LiDAR
   - New employee on their team Chris C.
   - GISDM upgrade failed, but it's due to the schema issue with SDE External
- CTECC
   - Matt got Belinda's old position
   - New version of CAD coming out in August
   - Migration to Pro is still on-hold due to the current CAD
- Training
   - classes still have seats available, especially in July, please get people signed up

**Comment by johnclary** [comment]
thanks!
