### ISSUE TITLE
Display Moped editor version number in footer

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6520]
As a product manager, I would like to see the Moped editor version number in the app so that I can verify the expected behavior of the app. As a Moped user, I would like to see the Moped editor version number in the app so that I know when new features have been released.

This can be implemented in the same fashion as in the VZ editor footer:
<img width="1260" alt="Screen Shot 2021-06-28 at 11 18 30 AM" src="https://user-images.githubusercontent.com/14793120/123670612-04163d80-d803-11eb-89d1-8ef6aa6d9b3e.png">

Bonus points if the release number can be hyperlinked to the [release notes in Github](https://github.com/cityofaustin/atd-moped/releases/tag/v0.7.0).

**Comment by johnclary** [comment]
@amenity FYI

**Comment by amenity** [comment]
Thanks, @johnclary. May also want to implement #5813 at the same time/in the footer.
