### ISSUE TITLE
Meeting: Streamline/Clean up badging system for Cameron Road

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6521]
### Objective 
Clean-up badging system at Cameron Road. Identify users to remove, review clearance groups, update clearance groups, set up SOP for adding/removing users to badging system.

### Participants
Jen, Brian C., Brian VDW?, Billy, Frank, Joe Michael, Lauren, Stephanie, Diana, Scott, David

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by moorerst** [comment]
Meeting scheduled for 7/15

**Comment by dianamartin** [comment]
Dup of #6660
