### ISSUE TITLE
Meeting: Demo of HR Forms in Knack

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6522]
Demo HR Forms in Knack:
30 Day Supervisor Survey for New Employee
90 Day Supervisor Survey for New Employee
120 Day Supervisor Survey for New Employee
30 Day Employee Feedback

NEO Evaluation form moved from MS Forms to Knack

**Comment by moorerst** [comment]
Questions:

- Is there a way to send an automated reminder to the Manager’s who complete the forms at each benchmark? 

- Also, is there a way for me to create a bi-weekly or monthly report?

**Comment by dianamartin** [comment]
I emailed Meredith back to answer her questions
>We can look into this, but this definitely increases the scope of this task. So the difficult part about this is, we would need to have a lot of updated information about the employee such as their Hire date, Start date to be able to calculate out what is 30, 90, 120 days to come up with a date that will run an email notification that the Supervisor needs to submit an Employee Survey.

>What information do you need for the bi-weekly/monthly report? You will have the ability to query the submitted records and export them. I guess we need to know what it is you're wanting from the report before we can determine the level of effort.

**Comment by moorerst** [comment]
Stakeholders were very pleased with the new HR On boarding forms and the NEO evaluation form in Knack. Created new issues for the enhancements they have requested.

**Comment by johnclary** [comment]
Wonderful to hear that! Thank you both! Thanks @dianamartin for pushing back on the email reminder. That sounds hard.
