### ISSUE TITLE
Model impact of basic vehicle characteristics on crash severity

### ISSUE THREAD

**Issue by phanaq** [cityofaustin/atd-data-tech#6531]
The units data has been pared down to a few variables of interest, including vehicle age, make, and model. I will complete a grid search of classification models on target variables and measure performance in order to determine the "best" model for each of the target variables. 

I will examine performance for three target variables: 
- Crash severity categories
- Fatal injury vs. nonfatal (binary)
- Serious or fatal injury vs not (binary)

Models may include the following:
- Decision tree
- Logistic regression
- Kernel SVM
- Random forest

For the binary target variables, I will try to minimize "false negatives" - i.e. cases where the model predicts that the vehicle crash did not result in a serious/fatal injury, when in reality a serious/fatal injury occurred. 

Notes:
- Later on, I may bring in additional variables such as weather, crash type, and road conditions. For now I will explore if vehicle characteristics alone do a good job of predicting crash severity, and narrow the lens once I have a better understanding of these relationships.

**Comment by dianamartin** [comment]
Closing as the CIC Fellowship has ended on 8/20/21.
