### ISSUE TITLE
Analyze characteristics of vehicles involved crashes resulting in serious or fatal injuries

### ISSUE THREAD

**Issue by phanaq** [cityofaustin/atd-data-tech#6532]
- Create visualizations and determine if there are trends in the types of vehicles that are involved in crashes resulting in serious/fatal injuries. 
- Compare these vehicles to the types of vehicles that were involved in crashes resulting in less serious injuries. 
- Find a comparative dataset (vehicles registered in Austin, perhaps?), explore and compare.

**Comment by dianamartin** [comment]
Closing as the CIC Fellowship has ended on 8/20/21.
