### ISSUE TITLE
Create AGOL Viewer for Parking Enterprise

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#6533]
Requested by Jeffery B.

Requested map to capture data (parking, land use, property info, emerging projects) and produce quick visuals for reports.

**Comment by andrewshensky** [comment]
6/30 - Demo provided to users. Users do not have AGOL access and will need accounts to be created.

**Comment by johnclary** [comment]
@andrewshensky please add a link to the app here and in the [Data Inventory](https://atd.knack.com/dts#applications/)

**Comment by andrewshensky** [comment]
Web app link for this project:

https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=bac5ae83506a4109bdc9d81c5cd21f15
