### ISSUE TITLE
Trigger associated permit and provider contact license based on changes in license status

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#6535]

**Comment by SurbhiBakshi** [comment]
**For Permits associated with a License**

- Added a Text Formula field  to the Permits object - License Status = Provider.License Status

- ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/831a02ae-d8e2-43bd-8962-0853337689a5)

**Comment by dianamartin** [comment]
Deactivate license 
- permit status to match -active or non-operational
- provider contact status - inactive/active

Further Testing 
- Provider Contact

**Comment by dianamartin** [comment]
## Testing
- Created new Provider company - Active
- Created new Provider contact - Active
- Created new Permit - Active
- Clicked "Deactivate License"
  - Trigger changed status for License, Contact and Permit - to "Not Operational"
- Clicked "Activate License"
  - Trigger changed status for License, Contact and Permit - back to "Active"

**Comment by dianamartin** [comment]
This is ready to be reviewed by SMO team

**Comment by dianamartin** [comment]
Showed application in sprint review on 8/6, stakeholders were happy with the reporting. Closing
