### ISSUE TITLE
Look into how users can use permits and license data in case of a PIR

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#6536]

**Comment by SurbhiBakshi** [comment]
Examples sent by Andrea
1.Can you provide the total number of permits purchased by each dockless company per month from Oct 2019 until now?
2. [Example 2](https://drive.google.com/file/d/1gsknHKy6uubvgdJ1ZzWNc_NzR5i_Q4Nj/view?usp=sharing)
3. [Example 3](https://drive.google.com/file/d/1lUntkdLb7WmbzdKdceRdCGy2hUFn5G3W/view?usp=sharing)

**Comment by SurbhiBakshi** [comment]
Update - 1.Can you provide the total number of permits purchased by each dockless company per month from Oct 2019 until now?
2. Example 2
3. Example 3

**Comment by dianamartin** [comment]
Scheduled a meeting with stakeholders on 7/30 to get caught up on what the PIR Reporting page should be, what's left to do.

**Comment by amenity** [comment]
@patrickm02L - check out this cool request. 😎

**Comment by dianamartin** [comment]
Showed application in sprint review on 8/6, stakeholders were happy with the reporting. Closing
