### ISSUE TITLE
Project: GIS Support for ASMP Amendment

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#6539]
Provide GIS support for the 2021 amendment of the Austin Strategic Mobility Plan (ASMP).

### Background
ATD leads the Mobility Annual Plan (MAP) process which relies on AGOL maps, both external and internal facing, to coordinate across multiple capital delivery programs. Support is needed to maintain and improve on these tools for use in analytics on bond delivery.

### Proposed solution
Maintain and improve the internal-facing tool used for annual coordination. Work with MAP lead, Laura D., and others on analytics for mobility bond delivery.

Users: Capital delivery program staff.
Sponsorship: ATSD
![Screen Shot 2022-05-24 at 6 57 49 PM](https://user-images.githubusercontent.com/1463708/170150783-05173a2b-4db2-43e7-962e-3f4871bef0d1.png)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
The data has been created and uploaded to AGOL. The maps have been created and configured. Crowdsource Reporter and Polling apps have been configured with the maps.

**Comment by alan-deanda** [comment]
The ASMP Amendment was officially adopted on June 9th, 2022. All published ASMP Amendment web viewers have been updated to reflect the official adoption of the amendment.  SSD has provided DTS GIS with the final version of the new ASMP Street Network, and it is currently being distributed to internal databases as well as being published to ArcGIS Online as authoritative data

**Comment by alan-deanda** [comment]
The ASMP data is now up to spec in MAINT, DM, and AGOL. Closing this epic now.
