### ISSUE TITLE
Meeting: Discovery of Parking Meters Inventory Management Spreadsheet

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6548]
### Objective 
Discovery meeting to learn more about the Inventory Management spreadsheet

### Participants
Stephanie, Diana, Steven S

### Agenda
[Inventory Report - May 2021.xlsx](https://github.com/cityofaustin/atd-data-tech/files/6735818/Inventory.Report.-.May.2021.xlsx)

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes
- Steven is only data manager
- Only person doing physical counting, back-ups: check-in/check-out

# Pain Points
- Daily: checking in and checking out and purchasing additional order (1/4 of his day)
- 2-3 day physically counting, creating report 
- Better way to input the systems
- Paper log sheets and enter into Excel


## Summary - _Transactions_
- Didn't have an inventory system
- First 3 tabs were created, parts usage to see trends on a daily 
- Tracked only pay station parts
- Monthly spreadsheet 
- Report it to Parking Meter managers/supervisors
- Prints summary

## Add Parts - _Transactions_
- Receiving parts from Vendor - if bad parts, they get replacement parts
- Purchase parts from Vendor

## Subtracted Parts - _Transactions_

## Parts Bag
- What should be in each back
- Parts bag: infrequent inventory
- Technicians return bag and parts get replenished
- Quantities are added to the Summary page#
- Bag PEO: 145 (On-Call bag that has working parts)

## Bike Rack Tool kits
- Reference of what's in the tool kit 
- Was created recently, newer sheets
- To install bike racks
- Tool Kit is like a parts bag
- Works like parts bag

## Consumables 
- Labor intensive tracking
- This one has to purchase and replenish often
- How is this tracked? Check these counts once a month
- Does physical count monthly
- Shopping list of Purchase Request orders - mainly consumables, rarely a tool

## Pay Stations - Inventory (reminds me of AMD Cabinets)
- Most expensive assets, 10k
- Basic storage 
- Track serial # system
- 
## Tools & Equipment
- Informational

## Tech Tools Inventory 
- Have another tool bag 
- All parts that are included
- Used to check it more, now quarterly
- Technician said lost or broke a tool to update the list

## Uniforms
- part cabinet drawer
- Extra uniforms that can be issued to technicians

## Vehicles
- Vehicles issued to Parking Meters

## PPE - consumable list
- part cabinet drawer

**Comment by moorerst** [comment]
Showed Steven some examples of other inventory systems

Next steps:

- continue discovery of Parking Meter asset spreadsheet (schedule meeting)

- Steven will think about other features, reporting that would be helpful

- After we complete our discovery we'll have another builder huddle to determine possible phases of the project

**Comment by moorerst** [comment]
closing this issue. Builder huddle will be scheduled soon.
