### ISSUE TITLE
Meeting: Discovery of Parking Meters Pay Station Asset Spreadsheet

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6549]
### Objective 
Discovery meeting to learn more about the Pay Station Asset Spreadsheet

### Participants
Diana, David S, Jeremy
- Optional: John
- Did not attend: Stephanie

### Agenda

- [ ] request a copy of the Pay Station Asset Spreadsheet
- [x] Determine who else needs to attend

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by moorerst** [comment]
Emailed Jeremy for a copy of the spreadsheet to review. Jeremy is out of office until 8/10. Will schedule meeting to discuss spreadsheet.

**Comment by moorerst** [comment]
received copy of the spreadsheet
Meeting sched
[paystation.inventory.8.5.21.xlsx](https://github.com/cityofaustin/atd-data-tech/files/6969377/paystation.inventory.8.5.21.xlsx)
uled 8/17

**Comment by dianamartin** [comment]
# Diana's Notes
>As part of our continued efforts to understand the day to day processes for your team we would like to get a better understanding of the Parking Meters Pay Station Asset spreadsheet that you maintain. I would like to set up a meeting to discuss how the spreadsheet data is collected and used. 

- Spreadsheet was the only way they used to track them, manually
- Kept every single updates from the beginning

Get a work order to add a new area
Go out an map it
Bring data back and fill in spreadsheet

- Parkeon - install machines
- send email to Flowbird
- Flowbird maps it
- Tied to API and send to ticket writers
- Parkeon machine number

Ticket writers 
Parking Meters

### Color Coding
Yellow- Core
Green - Non-Core
Towards the end, PT and D? Parking Management District
- includes Route Numbers

### Zone Groups
- Non Core - multiple routes in that zone 
- Core 
- West Campus
- Parks
- Walsh

# Route 1
Mobile Pay Zone - less than 4 spaces, no actual pay station machine
Address 
Block
Park ATX Zone
PS - Number of spaces
CSZ - Customer Service Zone

Below is a summary

Total = Cover sheet (Reporting)
Not PT&D - Mueller, Toomey, Rainey, Walsh Landing
PARD
East Campus
Colorado 
Austin High

MZ - Mobile Pay Zone

Limited to 99 to routes
Pull out a meter - meter gets archived
Machine's number recycled, new data go into new zone

Issue in the beginning. 

Station number will stay in the same route
- don't reassign a number within a year. 

## GIS Data Management
- Have you looked at the data set, why aren't you using it? Any reservations?

Also in Parking Inventory Map, originally mapped
Map is primary - 
- map first, attributes in map

They weren't using the new version. Francesco said. 

Curb IDs in the new system. 

### Editing Management
- Jaime will work with Parking Meter team
- Review data structure again
- Training staff
- Migration Plan

Flowbird would add to API
- transactions

Software Update 7/4/21
- Flowbird is aware 
- double charged customers
- BOA FISERV 

Passport - mobile pay (merchant processing)
Flowbird - physical pay station
Pill - Pool pass payments (physical, web, app)

Action Items: 
- GIS Initiative: Jaime, Steve Smith, Joseph, Jeremy, Ryan, new planner - Pria
- Financial Talks: Van, Ashlande, Jeremy, David S., Joseph

**Comment by dianamartin** [comment]
@jaime-mckeown @johnclary you can add notes here from the meeting

**Comment by johnclary** [comment]
Thanks @dianamartin - i made a few edits

**Comment by jaime-mckeown** [comment]
Thanks @dianamartin - looks good, small edit made in notes.

**Comment by moorerst** [comment]
@dianamartin can this be closed since the action items for GIS are being managed by Jamie and the Financial by John?

**Comment by dianamartin** [comment]
Yes, the meeting itself is done.
