### ISSUE TITLE
Rename "Activity Log" tab to "Activity"

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6553]
The Activity Log tab name and tab title do not match. We should rename the tab to "Activity Feed"...or just "Activity".

<img width="1177" alt="Screen Shot 2021-06-29 at 3 34 23 PM" src="https://user-images.githubusercontent.com/14793120/123899622-2c01c000-d92d-11eb-857f-55092b85ff83.png">

**Comment by amenity** [comment]
I like "Activity" ...  @patrickm02L, what works with your new activity feed vision #6566 ?

**Comment by patrickm02L** [comment]
+1 for "Activity"

**Comment by amenity** [comment]
This is covered by #6496
