### ISSUE TITLE
Meeting: Refine Renewals Workflow

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#6558]
Discuss some of the obstacles with the Renewals workflow, based on the Usability Tests. Suss out an easier workflow that's more intuitive and directs users to complete a successful renewal. 

https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/6477

**Comment by SurbhiBakshi** [comment]
@patrickm02L - Meeting scheduled for July 7th, 2021. I'll try to get some time with the other builders  before this meeting to see if they have recommendations based on other Knack workflows.

**Comment by patrickm02L** [comment]
We had the meeting. Get rid of the extra model, consider a 'snackbar' to let users know they have successfully completed a renewal.
