### ISSUE TITLE
Knack-Proxy: Fix 502 Issues

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#656]
From speaking with John, it appears that the knack-proxy server is returning a bunch of 502's and it is difficult to determine if it is generated on our end, or coming in from Knack.

Two ways we can approach the problem:

1. Troubleshoot and refactor the knack-server.

2. Refactor and deploy to a lambda function in AWS.

**Comment by sergiogcx** [comment]
Repo: https://github.com/cityofaustin/atd-knack-proxy

**Comment by sergiogcx** [comment]
There is now a PR:
https://github.com/cityofaustin/atd-knack-proxy/pull/10

And a working prototype ready for testing:
https://jr5e1b4gsf.execute-api.us-east-1.amazonaws.com/production

**Comment by johnclary** [comment]
@sergiogcx I reached out Omar (CTM) and provided him with the new endpoint (knack-proxy.austintexas.io) and cert. We will hold until he's able to test.

**Comment by sergiogcx** [comment]
Oh perfect, let's wait.

This is the link in CircleCI where it shows the automated deployment status:
https://circleci.com/gh/cityofaustin/atd-knack-proxy

This is the PR we should concern ourselves with:
https://github.com/cityofaustin/atd-knack-proxy/pull/11/files
