### ISSUE TITLE
IT Support: Upgrade Annie P. to G5 license to access PowerBI O365 app

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6561]
Put in CTM Ticket for that

**Comment by dianamartin** [comment]
@SurbhiBakshi 
- [x] Submitted a CTM Ticket `INC0112500` to request Annie to be upgraded to G5 license

**Comment by dianamartin** [comment]
@SurbhiBakshi Checked status on 7/12, looks like it's `In Progress` and assigned to Anastaysia so should be completed soon.

**Comment by SurbhiBakshi** [comment]
@dianamartin - thanks!

**Comment by dianamartin** [comment]
@SurbhiBakshi CTM assigned a G5 license to Annie. I received email confirmation. 
>A G5 license has been assigned to you; it comes with Power BI access and Skype/Teams Audio Conferencing feature. You will get an email from Microsoft regarding the dedicated Skype/Teams line # (512 number) and your personal PIN. Please make sure to save this email as you will need your PIN to join your Skype/Teams meetings as an organizer. **It may take a couple hours for this license to be synced up with your O365 account**.
