### ISSUE TITLE
Add New SubType to EX Folder - Other City Departments (UAT on PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#6562]
- Add a new subtype to Excavation (EX) Permits: 
-- Other City Departments
- This would work the same as the other subs added on #4469

**Comment by SubhaShroff** [comment]
@Nadin-Nader  DEV deployment request is submitted - SCTASK0155026.

**Comment by SubhaShroff** [comment]
### Status:
DEV deployment request is submitted.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to DEV. Please UAT and send demo for approval to TEST

**Comment by SubhaShroff** [comment]
@Nadin-Nader Portal display is not happening for new subtype. I did another commit to fix it and just raised DEV deployment request for ce06d31ddc40 - **SCTASK0157390**.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The ticket is working on both BO & Portal. I will be sending a demo for this soon.

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DEV demo and review of demo before TEST deployment

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Demo video is sent to you in email. Please let me know if we can move it to TEST.

**Comment by Nadin-Nader** [comment]
@SubhaShroff i reviewed the demo and it looks good. Lets get this over to TEST.

## **Approved for TEST deployment🎉🙌‼**

**Comment by SubhaShroff** [comment]
@Nadin-Nader **SCTASK0158072** TEST Deployment is submitted.

**Comment by SubhaShroff** [comment]
### Status:
TEST deployment is done. Testing is in progress.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I checked the deployment on TEST database. It all looks perfect but the new subcode doesn't display yet on POrtal. Probably TEST portal needs a refresh. So, I have sent an email to Swapna to do the refresh.

**Comment by Nadin-Nader** [comment]
**Status:**
Subha is still working with Swapna on why its not showing on Portal. Waiting on status of what happened after the portal refresh on DEV.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The changes that got promoted to TEST are exactly same like in DEV. I did go again and again to check the related lookup records. It look good and not sure why its not displaying on TEST portal. So I sent an email to Swapna/Surya asking for help to check on TEST Portal.

**Comment by SubhaShroff** [comment]
### Status:
Its deployed in TEST, but the new subtype is not displaying Portal. Follow up email sent to Swapna for help to check it on TEST Portal.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  - SCTASK0161008 is submitted for DEV deployment for commit - cd41715d86ca.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  DEV deployment is done and it looks good. Please let me know if I can promote it to TEST.

![image](https://user-images.githubusercontent.com/51680715/130521200-d8a30605-71d5-4682-84dc-f88ab699e5b8.png)

**Comment by SubhaShroff** [comment]
@Nadin-Nader After your confirmation on Teams, I have submitted TEST deployment request for the above change. - **SCTASK0161747**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  TEST deployment is done. I tested it on both TEST Portal and Back office. Following are the screenshots.

![image](https://user-images.githubusercontent.com/51680715/130663945-a6439f85-71c3-4b89-a567-51a25614a71f.png)

![image](https://user-images.githubusercontent.com/51680715/130664069-671e32ee-1683-43dd-9f7c-e21a4c5e4fc9.png)

**Comment by SubhaShroff** [comment]
### Status: Up for UAT on TEST.

**Comment by SubhaShroff** [comment]
### STATUS:

- Needs a defined Workflow. Probably a call set up might help  for going through the existing subtype and mark TO DO & Not TO DO.
- Parallelly, I am doing analysis to figure out the changes need to be done on Portal for STreet Info page(refer the link Tracy has posted). Taking ATD(50694) subtype as reference for the analysis.

**Comment by SubhaShroff** [comment]
### Status:
I raised a DEV deployment request - SCTASK0165141 to omit the unwanted fields on Street Info page.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  

Please check the following Property Street info page on DEV.  Let me know if that looks good. And also any other changes need in the further pages.

![image](https://user-images.githubusercontent.com/51680715/132566989-813403b5-d1d2-4f5f-b8b6-dd1a38cc4bef.png)

**Comment by SubhaShroff** [comment]
### Status:
As per @Nadin-Nader, its in scoping.
Otherwise, streetinfo extra fields on Portal are removed(refer above screenshot).

**Comment by TracyLinder** [comment]
Currently this work is in Dev

**Comment by Nadin-Nader** [comment]
**Status:**
Asked Paloma to test this on TEST. Waiting on results

**Comment by SubhaShroff** [comment]
### Status:
Waiting for UAT to be done.

**Comment by Nadin-Nader** [comment]
@SubhaShroff spoke with Paloma yesterday and she found 2 things:

> [Yesterday 5:30 PM] Amayo-Ryan, Paloma
>     Two observations:
> 
> The Fund Dept Unit Object fields are suppose to require exactly 4 numerical characters but I was able to enter fewer characters and still proceed to the next page.  (I tested this on other permits sometime last month and the feature was working.)
> 	
> I goofed and forgot to hit Submit at the end of one of the applications.  At the time it said $0.00 fees owed but when I went into My Incomplete Applications it showed the $290.00 fee.  I'm gonna try to duplicate this.

![MicrosoftTeams-image (4).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/06b19ac1-a27c-4b99-bb22-0add1688938f)

![MicrosoftTeams-image (5).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/a773d2fb-9307-457e-bfa4-bad0194325f6)


> [Yesterday 5:40 PM] Amayo-Ryan, Paloma
>     For now, it's not suppose to show any fees due because we don't want City customers to try to pay with a credit card or check.  But eventually, the permanent solution is suppose to be that the Cost of Service payment type should automatically apply.
> ​[Yesterday 5:41 PM] Amayo-Ryan, Paloma
>     The good news is that when I went into the incomplete application I was able to Submit it without being told to pay any fees.  (In fact, it reverted to showing $0.00 fees due.)


> [Yesterday 5:46 PM] Amayo-Ryan, Paloma
>     Ideally it wouldn't show any fees due for the Application Incomplete.  (I can picture panicked customers reaching out to us.)  But since it's not actually forcing them to pay the fees, it's not a deal breaker.  Still, if it's possible to fix the issue that would be best.

**Comment by Nadin-Nader** [comment]
**Status:**
This has been approved for **_DEV_** move

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0179435 is submitted for DEV deployment of 25c79c2fb163 (info validation to restrict value to 4 digits exactly).

**Comment by SubhaShroff** [comment]
### Status:
DEV deployment is done. I need to test it.

**Comment by SubhaShroff** [comment]
@Nadin-Nader - SCTASK0179658 - DEV Deployment Request is submitted to correct the error message to "Fund, Department, Unit and Object info values should be  4 digits not exceeding 9999".

**Comment by SubhaShroff** [comment]
@Nadin-Nader  DEV deployment is done. I tested it on DEV for the info validation and new error message. Let me know if I can deploy in TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0179836 is submitted for the TEST deployment of 25c79c2fb163, e176e66b14ec commits.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I tested for this ticket on TEST.

- 2021-048668 EX - the fee added was COS auto paid. 
- Paid by still comes as Applicant, not AMANDA - This is not in the scope of this ticket. It's related to #7162. And This change has to go to DEV yet.

The rest all looks good and, its ready for UAT.

**Comment by Nadin-Nader** [comment]
After a brief UAT with Paloma, she said that she was ok with everything except for what is below:

- Applications that are not completed/submitted should be going into a status of "Application Incomplete" instead of Internet pending
- Applications that are not completed/submitted should be going into the "My Incomplete Applications" list
- This should be for **ALL** COS items

**Comment by Nadin-Nader** [comment]
**STATUS:**
Approved for **_PROD_** deployment

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  PROD Deployment Request is submitted - SCTASK0180685.

**Comment by SubhaShroff** [comment]
### Status:
This is in PROD now.

**Comment by Nadin-Nader** [comment]
Hi Ladies,

Hope you are both doing well. I wanted to let you know that 6562 Add New SubType to EX Folder - Other City Department Is now on PROD. As discussed I have created the card for the status change. I will leave this open until Friday and close it after our meeting if no issues arise.
Please let me know if any issues do arise with this before our meeting on Friday

Respectfully,

Nadin A. Nader (He/Him/His)
Product Delivery Manager

**Comment by Nadin-Nader** [comment]
I am closing this as it has been a week and i have not heard any issues with this again.
