### ISSUE TITLE
(Documentation) New TURP Fee Structure & Logic

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6564]
### Dev work will not be done on this issue/ticket. This issue is now for reference only.

**Notes 7/27/21**
- Vish will update the AC
- We will review w/ Sree
- Ask Sree: Which order the work should be done in, and how she would like the work split up into separate issues. 

**Sections/Grouping of Work**
- Removing existing functionality
- Add new fees, update existing fees
- Add new functionality for new fee logic (triggers for fee insertion)

**Acceptance Criteria:** 
**Remove the following functionality:**
The current fee insertion and work type selection triggers for RW-TURP folders need to be removed as they are all going to change (#4469, #6322) . Provided below are some places where these triggers have been identified. 

- Info field Event Start Date (75980) and Event End Date (75985) determine appropriate work type for the folder. This functionality needs to be removed.
- Any functionality based on Info field Project Sponsor (76765) needs to be removed. 

**Configure the following fees in the AMANDA Back Office:**

1. Fee Description - 'TURP Permit Fee - New'
Fee amount - $320
GL Account Number - 5125 2400 9100 4087

2. Fee Description - 'TURP Permit Fee - Secondary'
Fee amount - $95
GL Account Number - 5125 2400 9100 4087

3. Fee Description - 'TURP Permit Fee - Emergency' 
Fee amount - $95
GL Account Number - 5125 2400 9100 4087

4. Fee Description - 'TURP Permit Fee - Extension'
Fee amount - $195
GL Account Number - 5125 2400 9100 4087

**Create new fee logic for the fees provided below:**
**TURP New Permit Fee**
- Applies only when work type is NOT 'Franchised Utility -Gas Utility', 'Franchised Utility - Other Electric Utility', 'Franchised Utility - Telecommunication/Cable Utility'.
- This fee needs to be added when a new application is created either from portal or back office
- Fee needs to be added only if folder Info 'Emergency' (#6641) and Folder Info 'Secondary' is answered 'No'. 
- Applicant must pay this fee before folder status updates to Internet Pending

**TURP Emergency Permit Fee**
- Applies only when work type is NOT 'Franchised Utility -Gas Utility', 'Franchised Utility - Other Electric Utility', 'Franchised Utility - Telecommunication/Cable Utility'.
- This fee needs to be added when a new application is created either from portal or back office
- Fee needs to be added only if folder Info 'Emergency' (#6641) is answered 'Yes'. 
- Applicant must pay this fee before folder status updates to Internet Pending

**TURP Secondary Permit Fee**
- Applies only when work type is NOT 'Franchised Utility -Gas Utility', Franchised Utility - Other Electric Utility', Franchised Utility - Telecommunication/Cable Utility'.
- Fee needs to be added only if folder Info 'Secondary' (#6321) is answered 'Yes' and Folder Info 'Emergency' is answered 'No'.
- When Folder Info 'Secondary' is answered 'Yes' and Folder Info 'Emergency' is answered 'Yes', System should insert TURP Emergency Permit Fee ONLY.  
- This fee needs to be added when a new application is created either from portal or back office
- Applicant must pay this fee before folder status updates to Internet Pending

**TURP Extension Permit Fee**
- Currently the system inserts TURP ROW fees for extensions when attempt 'Extension Granted' is made in Permit Extension Process (50680). 
- System needs to insert the TURP Permit Extension Fee at this trigger along with other fees. 
- Applies only when work type is NOT 'Franchised Utility -Gas Utility', 'Franchised Utility - Other Electric Utility', 'Franchised Utility - Telecommunication/Cable Utility'.

**Update the fee logic for the fees provided below**
**TURP ROW Usage Fees (50150) **
- This fee is currently inserted when Approved attempt is made in TURP Review Process (50520) 
- The fee logic that this fee uses is working correctly. Fee amounts for this fee has changed. Fee amounts need to be updated as per the values provided below. 
- Fee values are stored in Lookup table 50200. 
- The GL Account number for this fee is 5125 2400 9100 4062

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/efeb2ac1-8eac-4626-ad2f-56d95c04ac1a)

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/de84a572-2ba3-49a5-97a3-5ac9bfc9704b)

**Comment by vschandramouli** [comment]
Outstanding questions: 

This line is from @TracyLinder 's notes. What does this mean? 
- There's no specific fee name for 'Secondary' because the fee is the same as TURP New Permit

**Comment by vschandramouli** [comment]
Updated Acceptance Criteria. @TracyLinder Could you give this a quick look and let me know if it is Backlog ready?

**Comment by Nadin-Nader** [comment]
@vschandramouli looks good but do we know what Tracy meant by **There's no specific fee name for 'Secondary' because the fee is the same as TURP New Permit**

**Comment by TracyLinder** [comment]
@vschandramouli @Nadin-Nader 
I just got clarification on this from stakeholders. We don't have the correct AC on here; I will schedule a mtg to discuss.
