### ISSUE TITLE
(Documentation) New EX Fee Structure & Logic

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6565]
### Dev work will not be done on this issue/ticket. This issue is now for reference only.

**Notes 7/27/21**
- Vish will update the AC
- We will review w/ Sree
- Ask Sree: Which order the work should be done in, and how she would like the work split up into separate issues. 

**Sections/Grouping of Work**
- Removing existing functionality
- Add new fees, update existing fees
- Add new functionality for new fee logic (triggers for fee insertion)

Refer to 1st scoping meeting on #6306

**Acceptance Criteria:** 
**Remove the following functionality:**
The following fee procedures and logic need to be removed for the EX fees:
- The Excavation/Concrete Permit fee - Transport (50348) is inserted when application is created through Portal. This fee insertion needs to be removed. 

**Configure the following fees in the AMANDA Back Office:**
1. Fee Description - 'Excavation Permit Fee - New'
Fee amount - $290
GL Account Number - 5125 2400 9100 4057 

2. Fee Description - 'Excavation Permit Fee - Secondary'
Fee amount - $95
GL Account Number - 5125 2400 9100 4057 

3. Fee Description - 'Excavation Permit Fee - Emergency' 
Fee amount - $95
GL Account Number - 5125 2400 9100 4057 

4. Fee Description - 'Excavation Permit Fee - Extension'
Fee amount - $175
GL Account Number - 5125 2400 9100 4057 

**Create new fee logic for the fees provided below:**
**Excavation Permit Fee - New**
- Applies only when subtype is NOT 'Franchised Utility -Gas Utility', 'Franchised Utility - Other Electric Utility', 'Franchised Utility - Telecommunication/Cable Utility'.
- This fee needs to be added when a new application is created either from portal or back office.
- This fee should be added only if Info field 'Emergency' (#6641) and Info field 'Secondary' (#6321) are answered 'No' 
- Applicant must pay this fee before folder status updates to Internet Pending.

**Excavation Application Fee - Secondary - $95**
- Applies only when work type is NOT 'Franchised Utility -Gas Utility', Franchised Utility - Other Electric Utility', Franchised Utility - Telecommunication/Cable Utility'.
- Fee needs to be added only if folder Info 'Secondary' (#6321) is answered 'Yes' and Folder Info 'Emergency' is answered 'No'.
- This fee needs to be added when a new application is created either from portal or back office
- Applicant must pay this fee before folder status updates to Internet Pending

**Excavation Application Fee - Emergency - $95**
- Applies only when subtype is NOT 'Franchised Utility -Gas Utility', 'Franchised Utility - Other Electric Utility', 'Franchised Utility - Telecommunication/Cable Utility'.
- This fee needs to be added when a new application is created either from portal or back office.
- This fee should be added only when folder info 'Emergency'  is answered 'Yes'
- When Folder Info 'Secondary' is answered 'Yes' and Folder Info 'Emergency' is answered 'Yes', System should insert TURP Emergency Permit Fee ONLY.  
- Applicant must pay this fee before folder status updates to Internet Pending.

**Excavation Application Fee - Extension - $175**
- This fee should be inserted manually when user navigates to fee tab and clicks Add->Insert. 
- The manually inserted fee should be inserted with the fee amount of $175.
- Applies only when subtype is NOT 'Franchised Utility -Gas Utility', 'Franchised Utility - Other Electric Utility', 'Franchised Utility - Telecommunication/Cable Utility'.

**Update the fee logic for the fees provided below**
**ROW Usage Fee - Street Lanes and ROW Usage Fee - Structure**
- The fee logic that this fee uses is working correctly. Fee amounts for this fee has changed. Fee amounts need to be updated as per the values provided below. 
![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/66b978ec-f3cd-4aaa-b756-5e1d1cc80466)

**Comment by TracyLinder** [comment]
**Need to clarify w/ Paloma**: 
If the EX subtype is private contractor, and the info Secondary is YES, should the system insert the EX New Permit fee of $290 or if an emergency, the emergency permit fee?

**Comment by TracyLinder** [comment]
@vschandramouli can you add an update to this issue please?

**Comment by vschandramouli** [comment]
Currently working on editing Acceptance Criteria. Will request a review and move to Backlog by today 7/16.

**Comment by vschandramouli** [comment]
Completed AC. @TracyLinder Could you give this a quick look and see if this is ready for Backlog?

**Comment by TracyLinder** [comment]
@vschandramouli @Nadin-Nader 
I just got clarification on this from stakeholders. We don't have the correct AC on here; I will schedule a mtg to discuss.
