### ISSUE TITLE
TIA Segment Map Bookmark Image Size Increase

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6568]
![Screen Shot 2021-06-30 at 2.33.50 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/c264ce7a-844f-4536-a621-0539edd02d2f)

**Comment by ChrispinP** [comment]
According to Andrew, there does not seem to be a way to increase the bookmark image size limit.
