### ISSUE TITLE
Mitigation Buttons - Single Row

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6569]
1. Rename 1st button (see screenshot)
2. Align buttons into a single row

![Screen Shot 2021-06-30 at 2.27.51 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/b49dba7e-16b4-4406-9efe-39d9f35ff699)

**Comment by ChrispinP** [comment]
Update Mitigation Fee-in-Lieu and Construction tables so both have the buttons and are all in a single row.
![image](https://user-images.githubusercontent.com/67915167/124660139-6ad2d100-de6b-11eb-81ba-b5c59a944b3b.png)


Ready to review

**Comment by ChrispinP** [comment]
Reviewed with stakeholders. They are happy with buttons. closing
