### ISSUE TITLE
Unusual date formats in Traffic Signals and Pedestrian Signals dataset

### ISSUE THREAD

**Issue by tcwcodes** [cityofaustin/atd-data-tech#657]
I was sorting through this <a href="https://data.austintexas.gov/dataset/Traffic-Signals-and-Pedestrian-Signals/p53x-x73x">dataset</a> and noticed that all but a handful of the dates under the "modified_date" field have a five-digit year, followed by month, day and time. For example: 51435 Jan 14 06:40:00 PM. It also seems to effect the "Detection Status Date" and "Comm Status Datetime" fields as well. It may be a conversion issue, perhaps those first few digits are part of a Unix timestamp that is being partially converted.

Mateo noted that it may relate to the following Python script:

https://github.com/cityofaustin/atd-data-publishing/blob/e92a64cb548062f2b36f83812c2132757f9f6158/transportation-data-publishing/data_tracker/device_status.py#L95

**Comment by dianamartin** [comment]
@johnclary is this anything to be concerned about?

**Comment by johnclary** [comment]
@dianamartin yes it is. assigning it to me. thanks @tcwcodes.

**Comment by johnclary** [comment]
Well, I'm noticing that the comm status dates in the [Traffic Cameras](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Cameras/b4k4-adkb) dataset are no longer showing up. I'm guessing Scorata's recent API changes is at cause. Further investigation needed...

**Comment by amenity** [comment]
@johnclary - bumping to Sprint 10. Estimate, please.

**Comment by johnclary** [comment]
Demoting to Sprint 9. This has been fixed.
