### ISSUE TITLE
[Project Summary] Prevent user from nullifying project title or project description

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6582]
When editing a project, it is possible to erase the project's title or description and save the project. These fields are required.

![Screen Shot 2021-07-01 at 1.20.05 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/8a15dc56-4c64-46fc-b0ed-fb05795276a6)

**Comment by johnclary** [comment]
Will need to extend this component's framework to support validation configuration.

**Comment by chiaberry** [comment]
Do we want any error message to appear? If someone tries to save an empty field. @amenity @patrickm02L 

Right I have it behaving the same as when someone tries to click the checkmark without updating the field, which is, it does nothing. 

https://6582-prevent-nulling--atd-moped-main.netlify.app/moped/projects/274/ 
try saving the description as blank (I havent prevented the title yet)

**Comment by amenity** [comment]
@chiaberry - can we apply the "error" style to the field the same way we do in the new project workflow? 
<img width="810" alt="Screen Shot 2021-07-06 at 2 49 47 PM" src="https://user-images.githubusercontent.com/1463708/124658595-905edb00-de69-11eb-89b4-a53ff4d68389.png">
