### ISSUE TITLE
CR3 PDF ETL is broken

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6583]
Mateo's TXDOT account pw expired for the account associated with the PDF download ETL job. We need to update the new pw in the ETL config environment variables and make sure the bad PDFs are replaced. 

Original discussion in Slack [here](https://austininnovation.slack.com/archives/C013G4RNJ01/p1625060635034300?thread_ts=1624946750.029200&cid=C013G4RNJ01)

**Comment by johnclary** [comment]
@mateoclarke would you fill in the details here?

**Comment by mateoclarke** [comment]
pw has been updated in Airflow for staging and prod.

We still may need to do something similar to what Frank suggested [here](https://austininnovation.slack.com/archives/C013G4RNJ01/p1625146987036000?thread_ts=1624946750.029200&cid=C013G4RNJ01). Basically, we have a bunch of broken HTML pages pretending to be PDFs. We need to purge them and re-download the actual CR3 PDFs.

**Comment by mateoclarke** [comment]
I used this query to see how many records may have broken PDFs.

```sql
SELECT
	*
FROM
	atd_txdot_crashes
WHERE
	cr3_file_metadata->>'mime_type' = 'text/html';
```

There were 1,632. 

To narrow the focus on the recent records associated with the expired pw, I slightly modified the query:

```sql
SELECT
	*
FROM
	atd_txdot_crashes
WHERE
	cr3_file_metadata->>'mime_type' = 'text/html'
	AND cr3_file_metadata->>'last_update' > '2021-06-20'
```
1,502 in total.

After spot checking some of the older records, I decided to go ahead and purge all 1,632. Clearing both the `cr3_file_metadata` and `cr3_stored_flag`.

```sql
UPDATE
	"public"."atd_txdot_crashes"
SET
	"cr3_file_metadata" = NULL,
	cr3_stored_flag = 'N'
WHERE
	cr3_file_metadata ->> 'mime_type' = 'text/html'
```

These PDF should be downloaded in batches every 30 minutes if everything is working properly. I will follow up on the ~1.6k records with `cr3_stored_flag = 'N' AND cr3_file_metadata IS NULL` tomorrow.

**Comment by mateoclarke** [comment]
All but one of the records was able to backfill. Pretty sure that one record is an edge case that just doesn't have an available CR3 PDF associated with its crash ID.
