### ISSUE TITLE
Implement New Header Navigation Design

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#6585]
This navigation design takes the menu items that were hidden in the old hamburger menu and presents them across the top for quick access. Note that the the first three mocks below don't include the question mark icon for the support menu icon. 

## Full width
![image](https://user-images.githubusercontent.com/1463708/125137649-bb983300-e0d2-11eb-91cd-cb24207f0a74.png)

## Mobile - collapsed
![image](https://user-images.githubusercontent.com/1463708/125137618-ab805380-e0d2-11eb-8948-c39742b1fcf7.png)

## Mobile - expanded 
![image](https://user-images.githubusercontent.com/1463708/125137578-9acfdd80-e0d2-11eb-8147-d10cd989dee6.png)

## Support button 
![Home – Header info](https://user-images.githubusercontent.com/5566727/125649814-933c1f86-9273-45d4-a147-3642d5fe3494.png)

**Comment by johnclary** [comment]
Thanks @patrickm02L! I like this a lot. Sticking it inside #4060. Let's discuss with @amenity.

Along these lines, we've talked about making the nav bar and background the same color. [Here's](https://docs.google.com/document/d/1aZFQOa75TNeXUZ3ptjhd-LUbw5pG1sFn4npEtK4x8pg/edit) some meandering discussion that we link to from #4060.

**Comment by amenity** [comment]
@patrickm02L - Really like this.😊 @johnclary has proposed getting rid of the sidebar menu for a while now and I've been holding out because it works well on mobile and can gracefully hold many nested menu items... But I really can't envision what those items would be, so... 

If you add specs for a mobile mock-up, I think this is ready to go into the backlog for implementation. 🙌🙏

**Comment by patrickm02L** [comment]
@amenity I can do that. Will try to have it ready for next grooming session.

**Comment by amenity** [comment]
@patrickm02L wonderful, thank you!👨‍🎨

**Comment by johnclary** [comment]
Ah yes, good point r.e. mobile. More feedback:
- I _think_ we might want a text label inside the new project button. It's not as elegant but I don't know that a new user would intuit that they should click the plus (+) icon to create a new project.
- I'm all for adding basic project searching to the navbar, but we might table that to be scoped as a separate issue.

**Comment by patrickm02L** [comment]
I'm for adding a button with text label. Here's an example.

![Home – 3](https://user-images.githubusercontent.com/5566727/124790099-7fb57000-df10-11eb-8ba1-e34c509b0d50.png)

**Comment by patrickm02L** [comment]
For mobile, my though is to condense the header back to a hamburger menu that turns into a drop down. I think we can draw back to the original header for inspiration. 

I did a quick pass on the other elements like Search and Project Names just to see how they might transform, but not married to the way the look or function.

![iPhone 12 Pro Max – 2](https://user-images.githubusercontent.com/5566727/124791953-2bab8b00-df12-11eb-851a-af2217577373.png)

![iPhone 12 Pro Max – 4](https://user-images.githubusercontent.com/5566727/124791962-2d754e80-df12-11eb-82b9-295353e42ea0.png)

**Comment by amenity** [comment]
I was going to suggest a text label as well. Users overwhelmingly preferred it over icon-only buttons. I'd actually go so far as to add it to our [Moped design standards](https://atd-dts.gitbook.io/moped/dev-guides/design-system/component-styles/). 

Basic search in the header would be lovely: https://github.com/cityofaustin/atd-data-tech/issues/6622

**Comment by amenity** [comment]
I like this mobile projects page! Would the idea be that the rows would be accordions and the additional column info would [display vertically](https://codepen.io/team/css-tricks/pen/wXgJww?editors=1100) on click? I really like that alternative to horizontal scrolling on mobile.

**Comment by amenity** [comment]
@patrickm02L — can you mock up the mobile menu expanded, or should we go with the one @johnclary provided [here](https://github.com/cityofaustin/atd-data-tech/issues/6190)? 
![image](https://user-images.githubusercontent.com/1463708/124797659-20f3f480-df18-11eb-8662-0c2df020ee9c.png)

**Comment by johnclary** [comment]
love it!

**Comment by amenity** [comment]
**_Updating to tee up for devs. Here's @patrickm02L's original description for easy access:_**

 
This navigation design takes the menu items that were hidden in the old hamburger menu and presents them across the top for quick access. 

An 'Add new project' icon, and 'search' icon were added for quick access as well. This improvement is meant to act as a static header across all pages so that a user can create a new project or search where ever they are in the platform. 

![Home – 2.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/76e12db8-4513-4750-bf53-ee308f3fec2e)

The old header consisted of the logo, profile avatar, and a hamburger menu that for navigation to different pages and login options. 

Old header
![Home.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/0353fd72-0a95-40c2-b2c5-1c99afe1ace3)

Hamburger Menu
![Home – 1.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/2e307ef1-060a-4f63-a62f-407ceb1b0743)

**Comment by amenity** [comment]
@patrickm02L - can we incorporate a [help button/menu item](https://github.com/cityofaustin/atd-data-tech/issues/5813) into this header? 

We could use the text "Support" where you have "Reports" or we could use the `?` icon Material UI standardizes on.

**Comment by patrickm02L** [comment]
My vote is to put it on the other side of the Avatar. Based on the material UI options, we had either a filled in question mark or the outline. I think the outline is cleaner. 

![Home – Header info](https://user-images.githubusercontent.com/5566727/125649814-933c1f86-9273-45d4-a147-3642d5fe3494.png)

**Comment by chiaberry** [comment]
A few questions @patrickm02L 
Is the gray color of the navbar text the same color as the background, ` #E1E2E1`? 
Does the avatar in the upper right corner open the Account page? 
How does a user logout, from the Account page?
I am assuming I'm adding a tab for Staff with a link to its page, and omitting the Reports tab for now. lemme know if that's wrong

**Comment by patrickm02L** [comment]
Yes the Avatar should open the account page, and show a logout option. 
Let's add staff in the place of Reports.

**Comment by chiaberry** [comment]
![Home – 4](https://user-images.githubusercontent.com/12474808/126012930-699a48ee-9867-4775-b74a-49eb03542f8c.png)

**Comment by patrickm02L** [comment]
Updated the mobile view so that the Avatar stays in the header and the Help button moves to the drop down Menu. This allows for users to easily select the Avatar menu to make changes to their account or logout. 


![iPhone 12 Pro Max – 3](https://user-images.githubusercontent.com/5566727/126390956-02a7fa45-de35-4395-9e65-ec3b99842bfd.png)
![iPhone 12 Pro Max – 5](https://user-images.githubusercontent.com/5566727/126390965-35f454ef-7e9c-4f97-ac24-5fda65ab7e6f.png)
