### ISSUE TITLE
[TDS] Mobile TIA Menu Enhancement

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#6586]
During TIA Design Review we found a need for the custom TIA Menu to be more mobile friendly and stack menu items similar to how Knack does by default on small screens. Currently we use code to hide the custom menu for mobile viewers but we would like to enhance this menu to show on all screen sizes.

Current Desktop View:
![image](https://user-images.githubusercontent.com/67915167/124191667-bc551780-da89-11eb-9742-321d3d46e8e8.png)

Current Mobile View:
![image](https://user-images.githubusercontent.com/67915167/124191776-e9092f00-da89-11eb-95bc-1d55632f27c0.png)

**Comment by amenity** [comment]
@TracyLinder - can you sync with @chiaberry on this? She can get started this sprint, but needs a bit more clarification.

**Comment by TracyLinder** [comment]
<img width="998" alt="Screen Shot 2021-07-08 at 1 37 24 PM" src="https://user-images.githubusercontent.com/49930868/124973826-a7303980-dff1-11eb-8f3f-8d98f2232a03.png">

**Comment by ChrispinP** [comment]
Mobile Menu tested and added to production for all necessary pages. Pending any final changes.

Ready to review with stakeholders

**Comment by ChrispinP** [comment]
Reviewed with Tracy and stakeholders, no issues. closing as complete
