### ISSUE TITLE
Conduct Usability Testing on Moped 0.7.0 with Alpha Users

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#6589]
We want to test the new features that were launched in version 0.7.0 of Moped to get feedback and insights about how the tool is working and what refinements to make.

- [x] Create Usability Test Guide

- [x] Schedule Tests Tests with Alpha users for self directed test or guided tests

- [x] Conduct Tests

Next up: #6705

**Comment by patrickm02L** [comment]
We'll need to share the results of the tests with the Team/Devs in particular to help work through any additional features to add or refinements to what we currently have.

**Comment by amenity** [comment]
0.2.0 Usability tests:
- [Recordings](https://web.microsoftstream.com/channel/a5423c36-f8ff-42ee-84c8-f074e1bebcbd)
- [Script and results](https://drive.google.com/drive/folders/1bJvpU3lUsiOfigELhO3GA2aLJQd-P0P9)

**Comment by patrickm02L** [comment]
Usability test is scheduled for 7/13 with Renee Orr.

**Comment by patrickm02L** [comment]
Meeting action items 7/9/21:

- @janet will create Usability Guide. 
- @patrickm02L will schedule 3-4 testing meeting and add Devs to each. 

We'll meet for a dry run and to go over roles on Tuesday. 7/13 morning before our first User Test.

**Comment by amenity** [comment]
Ivonne N. is out of office next week, so scheduled for 7/20.

**Comment by patrickm02L** [comment]
Frank H. is scheduled for a Usability Test on Friday, 7/16.

**Comment by amenity** [comment]
Scheduled Mike S. For Thursday, 7/15.

**Comment by janetchuhl** [comment]
[v0.7.0 Usability Testing Guide](https://docs.google.com/document/d/1fp8QGjntURTkmu1irSs6LeSSXd4o7OhwYPAp3cEwnTw/edit) created.

**Comment by patrickm02L** [comment]
Usability Test for v.0.7.0

[Recordings](https://web.microsoftstream.com/channel/a5423c36-f8ff-42ee-84c8-f074e1bebcbd?referrer=https:%2F%2Fapp.zenhub.com%2F)
[Script, Guide, and Notes](https://drive.google.com/drive/folders/1WH2a_0p-6_83aAUQ86ZIQyKr130E9kMz)

**Comment by patrickm02L** [comment]
All of the In-Person Interviews have been conducted.
