### ISSUE TITLE
Give feedback to CTM on change tracking dataset

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6593]
Review the test layer and send feedback to Dwayne. The test layer has been added to GISDM Test: TRANSPORTATION.street_segment_historic.

Todo:
- Define which fields we want to detect changes
- Confirm that we would prefer the column headers to be stable and match the column name which changed.
- Re-iterate that we want new/added segments to be included in the dataset

**Comment by andrewshensky** [comment]
7/9 - Feedback was provided on this issue via email
