### ISSUE TITLE
Meet with TED about better tracking of speed limit change work orders

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6595]

**Comment by johnclary** [comment]
Sign work orders layer:
https://austin.maps.arcgis.com/home/item.html?id=72eb70e5afe2429ea0606a93db8df855

Speed limit change work order map:
https://austin.maps.arcgis.com/home/webmap/viewer.html?layers=93e29b23c39b4110ab0bbefde79b4063

**Comment by jaime-mckeown** [comment]
- Add/check for a new field for actual speed limits
- Add Signs Work Orders layer to Speed Limit Map
- Remove point/polygon layers from original map
- Look into adding Filters based on the work orders

**Comment by jaime-mckeown** [comment]
Andrew and I discussed this more after the meeting:
- going to modify the current Desktop Web Map / App
- remove edit ability on the proposed speed limit field in the Layer View
- add final speed limit field (Max will be editing this field after Work Orders are complete)
- add Signs Work Orders feature layer to the map for Area Engineer Teams to use to see what work orders have been submitted (filter by Requester: transportation engineering)
- add transportation engineering areas feature layer to the map

**Comment by jaime-mckeown** [comment]
@andrewshensky please add any notes if I forgot anything. I will move this to Review/QA. Thanks!

**Comment by johnclary** [comment]
This all sounds great—thank you both!

**Comment by andrewshensky** [comment]
Separate issue has been created to track tasks associated with this work #6688
