### ISSUE TITLE
[Enhancement] Enable ability to archive/hide datasets in the Data Inventory

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6596]
In the [Data Inventory](https://atd.knack.com/dts#datasets/?view_1_search=parking&view_1_page=1), add the ability for editors to soft delete records by setting them to an "inactive" status.

- Add a "status" field to the `dataset` object. Choices: `active` (default), `inactive`.
- Add a menu button to the existing [dataset details](https://atd.knack.com/dts#datasets/view-dataset-details/5d8242578bbaf500105af4ea/) page to "Delete" the dataset. When submitted, the dataset status should be set to "inactive"
- Configure rules on [Datasets table](https://atd.knack.com/dts#datasets/) to hide projects based on "inactive" status

<img width="1440" alt="Screen Shot 2021-07-02 at 2 35 31 PM" src="https://user-images.githubusercontent.com/14793120/124321473-57f68e80-db43-11eb-866d-d6ffeff34ddc.png">

**Comment by SurbhiBakshi** [comment]
### Notes - 

- [ ] Add a "status" field to the dataset object. Choices: active (default), inactive.
- [ ]  Add a menu button to the existing dataset details page to "Delete" the dataset. When submitted, the dataset status should be set to "inactive". 
- [ ] Set Modified By to logged in account
- [ ] Set Modified Date to current date
- [ ] Set Delete Dataset trigger to only show up for Active Status datasets
- [ ] Set the New Dataset form to default to Active Status 
- [ ] Configure rules on Datasets table to hide projects based on "inactive" status
