### ISSUE TITLE
Deleted Test CSR Issues and Activities

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6598]
Diana M
DTS

@moorerst I was in the system doing clean up bc a user was having trouble logging in and he was using the Test Dispatcher account. I was converting them from Test to his name so he get credit on the reporting. 

Anyways, for fun I put in keyword "Testing" in the service request, "All" tab and got 30 records back. I'm sure there are activities tied to them. Should we ask the stakeholders if they want to delete them? It's skewing their numbers a bit.

**Comment by dianamartin** [comment]
# Test records
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/2e161098-78ce-4765-8b08-e3e04eda559e)

**Comment by moorerst** [comment]
messaged Shavyonne to review the test records and advise how they want to handle them.

**Comment by moorerst** [comment]
Shavyonne confirmed the test records can be deleted.
I've reviewed and Diana can proceed with deleting all that are detailed as "test".

**Comment by dianamartin** [comment]
- I added separate activities table so that I could delete the activities
- Added page rule to hide from other users except me

- PSR00-015880- will delete on back end to see if I can easily delete the activities too
- [x] Deleted CSR
- [x] Queried Activities with blank CSRs, matched 1 record
Will delete CSRs with "Test" in "Details" field
- [x] Delete records with "Test" in "Details" field - `29 records`
- [x] Delete `csr_activities` records that related to "Test" `csr_issues` - `67 records`
