### ISSUE TITLE
Create Signs Asset Feature Class

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#660]
We need an authoritative street signs asset feature class. I believe we're going to want it to live on AGOL, so that we can reference the signs work order layers when doing QA/QC. But it's up for discussion.

**Comment by johnclary** [comment]
@dianamartin would you work with @alan-deanda to make sure he has the schema for this?

**Comment by dianamartin** [comment]
@alan-deanda I believe I send you the spreadsheet of the sign schema when you were creating these AGOL feature classes and GISMAINT layers. 
[Network drive](G:\ATD\ATD_GIS\01_ADMIN\DATA_MANAGEMENT\Data_Migration\signs)
File Name: Signs_Layers_AGOL_MAINT_20190816.xlsx

**Comment by alan-deanda** [comment]
@johnclary , @dianamartin should these be point or multipoint feature classes?

**Comment by johnclary** [comment]
@alan-deanda these should be point (not multipoint) feature classes. Thanks.

**Comment by alan-deanda** [comment]
@johnclary , both asset feature classes now live in AGOL [here](https://austin.maps.arcgis.com/home/item.html?id=ff625668dbe04e4d8ebd378397c2e86e&view=table#overview).
