### ISSUE TITLE
Implement refinements to "New project" extent mapping 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6600]
(Need specs, see [0.8.0 XD](https://xd.adobe.com/view/d59bde9e-a378-4763-97f5-882d6c34db0f-80c8/screen/8b87d301-8368-4d1d-8248-e17863fe9be2) and [0.7.0 XD](https://xd.adobe.com/view/87c30c8b-590f-4347-b832-73beb9b21888-d290/screen/40800008-49e8-427b-90bd-81d3571d15cb)) 

### Issues
* **Extent doesn't convert to components nicely**
Users were frustrated they couldn't convert their project extent into components once the project was created. (Technically they could, but they could only make it into a single component composed of all the locations they selected.) This is particularly annoying if the users carefully draw features:
   > _When adding components, it would be nice to be able to select geometries that were added while project mapping. This would ensure that the data is coincident, which would ensure that spatial operations  are possible/accurate. For example, I'm adding a rain garden (new point) to Shoal Creek Blvd. My component for the rain garden should have the same XY coordinates than the point I added while project mapping._

   **Ideas**
   - Get rid of extent: Instead of having a project extent, users add (a single?) components in the mapping step of project creation
   - Keep extent and better convey that it is only meant to map an approximate project location: Remove draw capabilities (and point selection??) and instruct users to simply select existing roads/trail segments that will be impacted by their project. Would extent data be useful — perhaps for performant rendering in a map viewer? If so, we could clarify the difference between extent and components more and have functionality to recalculate extent based on components. 

---
**John's previous comments on 0.7.0 "draw" mode, to be incorporated into this feature**
- [ ] Select mode should be enabled by default when drawing mode is toggled. 
- [ ] Select (triangle) button should be placed at top of draw button group.
- [ ] When a new feature is created (point or line), switch back to select mode automatically.
- [ ] In select mode, the cursor should be the browser default (arrow), except when hovering a drawn feature. Cursor should be a pointer when hovering

![draw_toolbar](https://user-images.githubusercontent.com/14793120/124523493-e9bd0080-ddbc-11eb-85ef-dfc202bf0689.jpg)

**Comment by amenity** [comment]
Per discussion w/ @johnclary and @patrickm02L - moving this to the Icebox for now. We're going to focus on component mapping and let users skip this step of project creation, see #7002 .
