### ISSUE TITLE
Spike: Style refinements to project components/map layer toggles

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6601]
- Create a horizontal menu at the top of the map frame (see image)
- Remove "Drawn points" and "Draw lines" checkboxes.
- The "Points" and "Streets" checkboxes should toggle both selectable and drawn features
- Replace the "Draw mode" switch button toggles (see image)
 - Move zoom controls and search box to bottom of frame?
![mapbar](https://user-images.githubusercontent.com/14793120/124523508-f7728600-ddbc-11eb-9421-36074b4297a7.jpg)

**Comment by patrickm02L** [comment]
I liked your idea about bringing everything to the top and moving some of the navigation around. 

I did a quick mock up of how it might be improved. 

- Used the whole space for the map
- brought the search to the top left
- layers to the bottom left
- zoom to the bottom right
- kept the select/draw where it was

![Moped Map-1](https://user-images.githubusercontent.com/5566727/124649856-a3b87900-de5e-11eb-9b6e-c9fec5d49047.png)

**Comment by johnclary** [comment]
nice! i think this could work. you’re right, more map is better. my only concern is if that form needs to grow down beyond the fold if/when we add additional fields. two releases ago the editing interface was actually a full screen modal. maybe we should revisit that approach, would give us plenty of real estate.

**Comment by patrickm02L** [comment]
Good feedback. I think maybe just moving the layers option to the left would free up more space. My instinct is to keep everything on the same page, rather than clicking on a modal and having a new screen. 

![Web 1920 – 3](https://user-images.githubusercontent.com/5566727/124789410-dec6b500-df0f-11eb-9c32-62927cac9e67.png)

**Comment by amenity** [comment]
@sergiogcx thinks this is doable —tricky part may be the overlap of the map and the components. (Looking back to when Mike struggled with the search/geocode causing users to inadvertently click map.

**Comment by amenity** [comment]
Turning this into a spike. @sergiogcx will explore what can be done and coordinate @patrickm02L on any design modifications to that latest spec.

**Comment by johnclary** [comment]
Awesome!

**Comment by sergiogcx** [comment]
After speaking with @patrickm02L about design specifics, we are going to settle with this for now:

![web_1920_____4.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/d8c275bd-7d3e-4081-9e3f-a10e961f7769)

**Comment by sergiogcx** [comment]
There is a pr: 
https://github.com/cityofaustin/atd-moped/pull/378
