### ISSUE TITLE
Enhancement: Email Notification for HR Onboarding Forms

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6607]
Is there a way to send an automated reminder to the Manager’s to complete the forms at each benchmark?
Benchmarks are 30 days, 90 days and 120 days from the employees start date.

**Comment by moorerst** [comment]
We can look into this, but this definitely increases the scope of this task. So the difficult part about this is, we would need to have a lot of updated information about the employee such as their Hire date, Start date to be able to calculate out what is 30, 90, 120 days to come up with a date that will run an email notification that the Supervisor needs to submit an Employee Survey.

**Comment by moorerst** [comment]
follow up meeting scheduled for 8/9

**Comment by moorerst** [comment]
Notes on the requirements for this enhancement:

- Email Notification
   Supervisor Survey - 30, 90, 120

- When should they be updated
   notification 2 weeks prior to 30, 90, 120 survey date

- Linda enters the hire date when she enters a new employee record

- Hire Date field
  Calculate Hire Date to 30 days out
  Calculate 30 days out
  Calculate 90 days out
  Calculate 120 days out
  Calculate 30 day out - 14
  Calculate 90 day out - 14
  Calculate 120 day out - 14

- HR Form Details -Supervisor Surveys table
  30, 90, 120
  email nudge notification - auto

- Timeline
   This month (August) or next month (Sept)
   Sept 6th

**Comment by dianamartin** [comment]
### Supervisor Survey Email Notifications
- [x] Added fields to `form_30_90_120_supervisor_survey_employee_SSPR` 
- Hire Date - text formula
- Date of Hire - date/time
- 30 Due Date - equation
- 90 Due Date - equation
- 120 Due Date - equation
 
### Noticed that NEO Evaluations was missing from Employee Details page
- [x] Added table for NEO Evaluations
- Form Name, Submitted Date
- [x] Added page rules if no forms associated, hide form table

### Configure `transportation.data` email notifications
- [x] Configured email for adding new employees
- [x] Configured email for employee separation
- Tested with my work email

**Comment by moorerst** [comment]
@dianamartin all the calculations are based on the Hire Date. Where are you getting the Hire Date from? Are you using the Hire Date that is entered   when Linda creates a New Employee record? I'm just trying to understand the process.

**Comment by dianamartin** [comment]
@moorerst Yes, I'm using the "Hire Date" that Linda enters. Then I calculated the date fields needed, and had to calculate more fields.

**Comment by dianamartin** [comment]
## Brainstorm Session w/ Chrispin
- New Employee form submitted, generates a 30 day survey auto
- Email task #1- on 30 day reminder date
- Email task #4 - 30 Day Employee Follow-up 
- Employee submits `30 Day Employee Follow-up` form, form rule generates a 90 day form
- Supervisor submits 30 day form, form rule generates a 90 day form
- Email task #2- on 90 day reminder date
- Supervisor submits 90 day form, form rule generates a 120 day form
- Email task #3- on 120 day reminder date
- Supervisor submits 120 day form

**Account TBL**
- Count of 30-90-120 - formula filter on `Duration`

**Simplifying Calculation Fields**
- Duration from multi-choice to integer 
  - using Duration in equations
- Making 3 equations

**Comment by dianamartin** [comment]
- [x] Added email task for 30 day reminder for Employees to fill out `30 Day Employee Follow-up Survey`
- [x] Tested email task, configured it more
- [x] Added email task for 30 day reminder for Supervisors to fill out `30 Day Supervisor Survey for Employee SSPR`
- [x] Added form record rules to generated a 90 day form under Employee

**Comment by dianamartin** [comment]
- Tested email tasks with Test Staff
- Configured nudge email reminder for Supervisors
- Needs Review from PM

**Comment by moorerst** [comment]
@dianamartin can you set me up with the permissions needed to review the updated you made?

**Comment by moorerst** [comment]
@dianamartin - some questions/suggestions

- [ ] on the HR Form Management form can we remove the following fields: form id, created by, created date
- [ ] on the forms detail page some of the completed survey dates are still appearing in red:
![image](https://user-images.githubusercontent.com/56606465/130646622-64c73942-7444-4254-aa9f-44fe14fc5157.png)

- [ ] on Forms Details page can we add a filter so HR can filter by Supervisor or Employee?
- [ ] on the Forms Details what does the Updated column represent?
- [ ] on the Forms Details page in the headings there is a line with Hire Date and another line with employee name can that be combined into one heading? - **oh I see the hire date is grouping all employees with that hire date.**

**Comment by moorerst** [comment]
@dianamartin is there a way for HR to CANCEL the process if an employee do not make it to one of the milestone dates?

**Comment by dianamartin** [comment]
## Testing & Screen Captures
### Scenario - 8/31
`Test Staff`   30 day
Supervisor: `Diana` - 30, HR Admin, 90, HR Admin, 120 day
HR Admin - Final Review - export

### Scenario - Set-up 
Employee: `Stephanie` (to fill out 30 day notification)
Supervisor: `Diana`

- [ ] Add Status to Supervisor Details
- [ ] Add Delete button field to table

**Comment by dianamartin** [comment]
Showed stakeholders on 8/31 and they had no follow-up modifications for it
