### ISSUE TITLE
Enhancements: Reports for HR On Boarding Forms

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6608]
Requested by Meredith: is there a way for me to create a bi-weekly or monthly report?

Response from Diana:

- What information do you need for the bi-weekly/monthly report? 
You will have the ability to query the submitted records and export them. 
I guess we need to know what it is you're wanting from the report before we can determine the level of effort.

**Comment by moorerst** [comment]
follow up meeting scheduled for 8/9

**Comment by moorerst** [comment]
Notes on requirements for this enhancement:

- Generate a monthly report 
   Tracking the managers
   Responses that need HR attention

WIP

**Comment by dianamartin** [comment]
Showed stakeholders on 8/31 and they had no follow-up modifications for it
