### ISSUE TITLE
Add Shoal Creek Boulevard project to Moped

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#6612]
Add the [Shoal Creek Boulevard project](https://data.austintexas.gov/stories/s/yjim-unm2) to Moped. 

Intersection maps: 
-   [Woodview Avenue at Shoal Creek Boulevard](https://www.austintexas.gov/sites/default/files/files/Shoal%20Creek%20at%20Woodview_v4.pdf)

- [38th Street and Shoal Creek Boulevard](https://adobeindd.com/view/publications/7d1de6b0-7557-4c3f-a7e4-590d0e188eec/7168/publication-web-resources/pdf/Shoal_Creek_at_38th_Street.pdf)

-   [Hancock Drive and Shoal Creek Boulevard](https://adobeindd.com/view/publications/87b625ee-ded7-4f3b-8a77-b83161ed3f57/1/publication-web-resources/pdf/Shoal_Creek_Boulevard_at_Hancock_Drive_0427.pdf)

-   [45th Street and Shoal Creek Boulevard](https://austintexas.gov/sites/default/files/files/Shoal_Creek_Blvd_at_45th_Street_Map_Jan_2020.pdf)

-   [Foster Lane and Shoal Creek Boulevard](https://austintexas.gov/sites/default/files/files/Shoal_Creek_Foster_Intersection_Map_nov22.pdf)

This will help us
- further our understanding of tags, labels, and categories; show us where the gaps are
- give us lotsa component data to 

- [ ] Get Shoal Creek data from IMPDB
- [ ] Enter data into Moped (Manually for now)
- [ ] Document any gaps

**Comment by johnclary** [comment]
@amenity asked NW for Shoal Creek project data. NW responded that we should reference project IDs 869 for lower shoal creek and 1430 for upper shoal creek.

[Here](https://github.com/cityofaustin/atd-data-tech/files/7004462/shoalcreek.xlsx) is the tabular component (aka facility) data for these two projects.

For spatial data, the [Interim Project Viewer](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=d6194f783b114453a70eb769853e390c) can be filtered for these specific projects. Note that each record in this map is a facility (aka component). 

In in case it's useful, here's the [geojson extract of these features](https://github.com/cityofaustin/atd-data-tech/files/7004417/shoalcreek.geojson.txt)

**Comment by alan-deanda** [comment]
hi @patrickm02L , @amenity , @johnclary 

I've mapped the Shoal Creek Boulevard project extent and components to moped. I've also left some feedback regarding the app. Please let me know if you need me to make any changes. I believe a rain garden or two may be missing as components, but I've laid out the digitization difficulties that led to this in the feedback.

Thanks,

**Comment by amenity** [comment]
Thank you, @alan-deanda. [It looks great](https://moped.austinmobility.io/moped/projects/293/) and we really appreciate [all your thoughtful feedback](https://xd.adobe.com/view/d59bde9e-a378-4763-97f5-882d6c34db0f-80c8/screen/8b87d301-8368-4d1d-8248-e17863fe9be2).
