### ISSUE TITLE
Urgent: ROW-TCP Tracker Metrics Reports 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6614]
### The TCP tracker reports that Laura needs to perform daily duties need to be stood up on the new portal ASAP.

**Comment by ChrispinP** [comment]
![image](https://user-images.githubusercontent.com/67915167/124675103-9c569700-de81-11eb-9732-94e0fba05977.png)
 
Added. Need to determine if any other critical reports are needed to built. Ready to review

**Comment by ChrispinP** [comment]
Followed up this morning with Laura. Updated report.

No other reports are critical to her workflow as this time.

**Comment by TracyLinder** [comment]
Delivered & Closing
