### ISSUE TITLE
[Bug] Previous 'Subtype' stays in text box after selecting new 'Type'

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#6616]
In the map editor...The 'subtype' from the previous 'type' will remain in the text box if you change to a new type. 

Instead, the 'subtype' should clear when a new 'type' is selected.

Video

 https://images.zenhubusercontent.com/140626918/61243547-3f2c-4d33-b615-666fd1d14c4c/example.mp4

Images

![Highway.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/f8440427-7783-4547-9d76-cad76d43ef32)

![Bikelane.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/85348b08-3a34-4fc7-8823-a7fd208dbf30)

**Comment by johnclary** [comment]
Thanks @patrickm02L—looks good to me.

**Comment by sergiogcx** [comment]
There is a PR:

https://github.com/cityofaustin/atd-moped/pull/364
