### ISSUE TITLE
 Support data quality control on timeline dates

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6618]
While staff plan projects, it's helpful to track tentative dates for phases and milestones.  As the project progresses, however, real dates should replace speculative dates. How might we let users quickly verify/update dates and easily track which are "real" and which are theoretical?

The most obvious way to confirm that a date is accurate would be for a user to update/okay the date after the date has passed. 

Ideas from Nathan and Renée: 
- Create a boolean "confirmed" field for each date* and style differently
- Style dates that have not been edited after the date differently, e.g. a date is in grey/italic/has question mark icon until it is edited after the date has past

Down the line, this information could be used for further QA... For example, we could pull a view of all projects that are complete but have unconfirmed dates. Or prevent projects from being marked as complete until they have confirmed dates.

_*If tracking "confirmed" for **every** timeline date seems too crowded from a data model perspective, we could track whether the dates are confirmed on the phase, subphase, and milestone level. But for phases and subphases, this would be the same indicator for two dates, and therefore harder for a user to use. (E.g. the start date may be confirmed, but the end date isn't... so you forget to check the box)._

**Comment by amenity** [comment]
Changing this to a should have because I really think it would help users keep an eye on schedule data quality. Simply telling everyone to "keep your dates up to date" without providing a UI to track that is not ideal.

**Comment by johnclary** [comment]
We did this with #14562
