### ISSUE TITLE
[Enhancements] Subprojects

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6625]
Continuing work from #9267.

### User stories
As a project manager, I need the ability to group related projects together under a single project so that I can track major aspects of implementation individually. I also need the ability to subdivide a project into multiple smaller projects as the project evolves.

As a project stakeholder, I need to understand, at a high level, the state of a large project without having to dig through the details of its various subprojects.

### Anticipated functionality
- View aggregated subproject data from within a parent project (timeline, components, team ...)
- Move/copy project attributes from one project to another (components, funding, ...)
- Define project attributes which can be pushed from a project to its subproject automatically (project name, funding, ...)
- View changes to subproject relationships in the activity log

**Comment by amenity** [comment]
@mateoclarke - this is JD's recommended approach to database implementation. I have zero recollection of the non-hierarchical "related" project idea. I think these would be designated with a label/tag of some sort.

**Comment by amenity** [comment]
@johnclary - we got pushback on the lightweight approach during today's sprint review. Setting up a work session to discuss. 

NW is advocating for linking project components to subprojects. The hardest thing for me to figure out for that direction is what the workflow would look like, and what the expected behavior would be in terms of synchronizing geometries. A kind of hacky approach:
- From map, option to add an existing project as a component (same as the interface you have mocked above)
- Only projects with a single component are eligible
- Once a project is a child (associated as a component on another project), the child project's map interface redirects to the parent project's map interface

**Comment by johnclary** [comment]
Work session sounds good. We need to better define the purpose of subprojects, and what information will differ across a project's subprojects. The thinking behind the lightweight approach is that we could address a lot of this through process/standards rather than functionality. 

Maybe just need to do #6612 and have the conversation around it?
