### ISSUE TITLE
Rename TCP Fee

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6634]
### Rename TCP Fee in AMANDA

**Stakeholders:** Laura, Darren

**Acceptance Criteria:** 
- On fee Traffic Control Plan (TCP) Out of Process Review Fees (51283)
    - Rename fee to **TCP Review Fee**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Make table changes and DEV Deployment sent. Please approve and create task id, here is the commit id: eb0743519f65

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have audited the commit

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this over the DevOps CM Team for deployment to DEV under **SCTASK0155920**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps to deploy to DEV under **SCTASK0155920**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this ha been deployed to DEV by the DevOps team.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Viewed the Renamed TCP Review fee in DEV. 

![image](https://user-images.githubusercontent.com/44907715/127911443-3ac14284-4523-4771-a011-7da50b8767c9.png)
![image](https://user-images.githubusercontent.com/44907715/127912235-09083348-9b52-4067-a884-f9295b5b1602.png)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan looks good. Lets get it to TEST for Stakeholder approval

## **Approved for TEST Deployment🙌**

**Comment by Nadin-Nader** [comment]
**Status:**

Sent to DevOps CM Team to deploy to TEST under **SCTASK0157528**

**Comment by Nadin-Nader** [comment]
**Status:**

Sent to DevOps CM Team to deploy to TEST under **SCTASK0157528**

**Comment by Nadin-Nader** [comment]
**Status:**

This is on TEST ready for UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - UAT in Test completed and working as expected. 

AMADA ADMIN
![image](https://user-images.githubusercontent.com/44907715/129627099-4ec62b88-d19e-4e14-95c9-32b0aa138f84.png)

AMANDA Application side
![image](https://user-images.githubusercontent.com/44907715/129627131-dc16d7db-c972-47af-b5d0-947ab004b679.png)

**Comment by TracyLinder** [comment]
@vschandramouli if you can include this UAT before Friday (same stakeholders) that would be great. If not we'll discuss during the weekly mtg.

**Comment by Nadin-Nader** [comment]
@TracyLinder @Sreelatha-BlazeKannan @vschandramouli i Have UATd this on TEST and the fee has been renamed

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/4e1e4ce5-d638-4fac-a281-85cd919ae182)

**Comment by Nadin-Nader** [comment]
Reached out to Darren again asking him if he was able to get Lura to UAT this on TEST. He said she is out sick and returns tomorrow. I will follow up tomorrow

**Comment by TracyLinder** [comment]
### This is approved. Please promote to PROD.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - PROD Deployment plan submitted. Here is the commit ID “eb0743519f6” and could you please create the task id for me.

**Comment by Nadin-Nader** [comment]
**Status:**
Still waiting for DevOps CM Team to deploy to PROD **SCTASK0162511**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been deployed to PROD. I will send an email to the stakeholders and close

**Comment by Nadin-Nader** [comment]
Email to Stakeholders:

> Good Morning,
> 
> Hope you are all doing well. I was reaching out to inform you the request to Rename the TCP Fee # 6634 has been deployed to PROD. I will go ahead and close the card out but if anything should arise with this, please feel free to email me or send a chat message.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services
