### ISSUE TITLE
Meeting - Automate process for data updates from Signs and Markings app to Open Data Portal

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#6636]
@chiaberry - I'll set up some time next week to discuss this issue and give you an overview. Timing will depend on your bandwidth and a few  fields I need to add to the views in Knack. Hope that works!

**Comment by SurbhiBakshi** [comment]
Jim wants to see at least two updates a day with a 4-5 hour window between the two updates.

**Comment by chiaberry** [comment]
sounds good to me! ill be on the lookout for the calendar invite

**Comment by SurbhiBakshi** [comment]
**[Notes](https://docs.google.com/document/d/19C31MLIKiwFJobT8359sfJyYxHc0Mqa5v5_2jDXFUzQ/edit?usp=sharing)**
