### ISSUE TITLE
IT Support: Review AMD SRs in 311 System

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6639]
John C
DTS

Emailed
>Hi—would you mind checking the issues Jonathan lists below to see if they've been closed in CSR?. Would you take some screenshots of the activity details in CSR and take note of any patterns you're seeing? I don't see any issues in the back end. All of the activities should have been sent to CSR. I'm guessing this is similar to the issue we saw in April where activities were not being received by CSR in the correct order.

Of the two Burleson and US 183 issues on the report, both are in the data tracker:
`21-00304256` - pending MMC review
`21-00248506` - closed: probably the same issue as with the others on your list.

# Jonathan's List - 8 SRs
### Oak Springs and Airport
- [x] MMC Issue ID: TMC21-239685
SR 21-00246624
Closed on Data Tracker, open on Weekly Aging Report for SRs
>Checked 7/9, confirming CLOSED

Activity | Created Date/Time | Completed Date/Time
| -- | -- | -- |
Close Issue (Duplicate) | 5/25 at 6:43 pm | 5/24 at 11:24 am
Other Re-Open Issue | 6/6 at 10:35 am | 7/6 at 10:26 am
Close Issue (Resolved)| 6/6 at 10:35 am | 7/6 at 10:26 am
 
### Springdale and MLK

- [x] TMC21-239750
SR: 21-00246624
Closed on Data Tracker, open on Weekly Aging Report for SRs
>Checked 7/9, confirming CLOSED

Activity | Created Date/Time | Completed Date/Time
| -- | -- | -- |
Close Issue (Duplicate) | 5/25 at 6:56 pm | 5/24 at 10:52 am
Other Re-Open Issue | 6/6 at 10:35 am | 7/6 at 10:28 am
Close Issue (Resolved)| 6/6 at 10:36 am | 7/6 at 10:29 am

### Barton Springs and Lamar
- [x] TMC21-239915
SR: 21-00247824
Closed on Data Tracker, open on Weekly Aging Report for SRs
>Checked 7/9, confirming CLOSED

Activity | Created Date/Time | Completed Date/Time
| -- | -- | -- |
Close Issue (Resolved) | 5/25 at 6:50 pm | 5/24 at 11:06 am
Other Re-Open Issue | 6/6 at 10:36 am | 7/6 at 10:30 am
Close Issue (Resolved)| 6/6 at 10:36 am | 7/6 at 10:30 am

### Springdale and MLK
- [x] TMC21-240025
SR: 21-00248472
Closed on Data Tracker, open on Weekly Aging Report for SRs
>Checked 7/9, confirming CLOSED

Activity | Created Date/Time | Completed Date/Time
| -- | -- | -- |
Close Issue (Resolved) | 5/25 at 6:50 pm | 5/24 at 11:24 am
Other Re-Open Issue | 6/6 at 10:38 am | 7/6 at 10:31 am
Close Issue (Resolved)| 6/6 at 10:38 am | 7/6 at 10:31 am 

### Burleson and US 183
- [x] SR: 21-00248506
Open on Weekly Aging Report for SRs, not showing up at all on DataTracker Service Request list on signal page. 
>Checked 7/9, confirming CLOSED

Activity | Created Date/Time | Completed Date/Time
| -- | -- | -- |
Close Issue (Duplicate) | 5/25 at 6:43 pm | 5/24 at 11:46 am
Other Re-Open Issue | 6/6 at 10:38 am | 7/6 at 10:32 am
Close Issue (Resolved)| 6/6 at 10:39 am | 7/6 at 10:33 am  

### Congress and Live Oak
- [x] TMC21-240070
SR: 21-00249265
Closed on Data Tracker, open on Weekly Aging Report for SRs
 >Checked 7/9, confirming CLOSED

Activity | Created Date/Time | Completed Date/Time
| -- | -- | -- |
Close Issue (Resolved) <br>_Monitored situation via signal and historical intersection timing reports. The signal is functioning normally at this time. Continuing to monitor signal operations._ | 5/25 at 6:52 pm | 5/24 at 3:15 pm
Other Re-Open Issue | 6/6 at 10:39 am | 7/6 at 10:34 am
Close Issue (Resolved)| 6/6 at 10:44 am | 7/6 at 10:35 am  

### Shore District and Riverside
- [x] TMC21-240075
SR: 21-00249469
Closed on Data Tracker, open on Weekly Aging Report for SRs
 >Checked 7/9, confirming CLOSED

Activity | Created Date/Time | Completed Date/Time
| -- | -- | -- |
Close Issue (Resolved) | 5/25 at 6:53 pm | 5/24 at 4:50 pm
Other Re-Open Issue)| 6/6 at 10:45 am | 7/6 at 10:38 am
Other Re-Open Issue | 6/6 at 10:51 am | 7/6 at 10:38 am
Close Issue (Resolved) | 6/6 at 10:51 am | 7/6 at 10:38 am
 
### Jones and Westgate
- [x] TMC21-240195
SR: 21-00250681
Closed on Data Tracker, open on Weekly Aging Report for SRs
 >Checked 7/9, confirming CLOSED

Activity | Created Date/Time | Completed Date/Time
| -- | -- | -- |
Close Issue (Resolved) | 5/25 at 6:53 pm | 5/25 at 12:50 pm
Other Re-Open Issue | 6/6 at 10:51 am | 7/6 at 10:42 am
Close Issue (Resolved) | 6/6 at 10:51 am | 7/6 at 10:43 am

**Comment by dianamartin** [comment]
@johnclary I reviewed the 8 SRs that Jonathan referenced and they're all in a `Closed` status, the creation and completion dates are interesting. I can't determine when we sent over the Closed (Resolved) or Closed (Duplicate) that the SR actually closed. I just know that on 7/6 the MMC re-opened and closed them and when I checked on 7/9 they were already `Closed`.

**Comment by amenity** [comment]
@johnclary - good to close?

**Comment by amenity** [comment]
@johnclary - please reach out to AMD.
