### ISSUE TITLE
Generate Barcodes for Non-AIMS Items

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#664]
### As a warehouse staff member, I need barcodes for all items, including non-aims items.

We need to come up with a standard scheme for creating non-aims barcodes. They do not necessarily need to be 11-digits, but they must be unique, and would ideally be driven by a combination of a categorical code and a sequence of numbers.

**Comment by johnclary** [comment]
@dianamartin i updated this issue, which was formerly 'create bar codes'

**Comment by dianamartin** [comment]
@johnclary Do you have any idea what numbering schema we should come up with for these items?

**Comment by dianamartin** [comment]
11 total digits

**Comment by dianamartin** [comment]
Reference `purchase_requests` object table
Fields to reference
- ITEMS AUTO INCREMENT
- `ID_GEN_YEAR` - getDateYear({Created Date})
- `Request ID` - {ID_GEN_YEAR}-right({ID_GEN_PAD_ZEROS}, 4)
- `ID_GEN_PAD_ZEROS`  - 10000 + ({AUTO_INCREMENT})

**Comment by dianamartin** [comment]
Created fields
- `ID_GEN_PAD_ZEROS` - equation - "10000 + {ATD_INVENTORY_ID}"
- `STOCK_NUMBER_AIMS` - _number_
- `STOCK_NUMBER_NON_AIMS` -_text formula_ - `999{Object.Code}right({ID_GEN_PAD_ZEROS},4)`
- `STOCK_NUMBER` - _short text_ - 
  - Conditional Rule: 
Inventory Tracking - is - `FINANCIAL`, set `STOCK NUMBER AIMS`
   - Conditional Rule: 
Inventory Tracking - is - `NON FINANCIAL`, set `STOCK NUMBER NON AIMS`

- `STOCK_NUMBER_DISPLAY` - _text formula_ - `left({STOCK_NUMBER}, 3)-mid({STOCK_NUMBER},4,2)-right({STOCK_NUMBER}, 6)`
