### ISSUE TITLE
Meeting - Knack to Power BI workflow

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#6645]
[Documentation](https://docs.google.com/document/d/1yJvEGIV5zvb6NjqW8x0rZEPXng5OUW1p64KqZmoDkiE/edit?usp=sharing)

**Comment by dianamartin** [comment]
# Diana's Notes
## Things to Do
- [x] Download PowerBI desktop
  - Worked the 2nd time
- [x] Create personal Socrata account 
  - I apparently already had one
