### ISSUE TITLE
Meeting - SD 2023 Overview

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#6646]
[Documentation](https://docs.google.com/document/d/10RmDwBoBef8VEUVek0CM4HuD1oIxacJWYh6zI4dRMbk/edit?usp=sharing)

**Comment by dianamartin** [comment]
# Diana's Notes
Center of Excellence SharePoint site
  - Peggy to request access to or Jim P. or Nicole C. 

We don't create data sets
Export to dataset as .csv and give to stakeholder
Stakeholders add new rows (ex. 2022)
- Ask stakeholders if historical data has changed if not just the current year
- DTS is to update the data set
- Edit the dataset
- Add Data
  - Append
  - Add 
Careful that data is already public

## Measure Card
- Should automatically updated
  - True for all datasets besides a couple
 
Write back to team, but they should already be working on Story page narrative. 
- Stakeholders should have template and they make changes to the template
- DTS copies text over to Story page
- Make those changes in the same day
- Numbers may be updated and description might not match
- Have teams work on story page narrative 

Spreadsheet to track the status of teams and data

**Comment by dianamartin** [comment]
@SurbhiBakshi anything to add here?

**Comment by SurbhiBakshi** [comment]
@dianamartin Looks good to me! 



Timelines - 
1. M.B.1 is on hold till a data source is available.
2. M.A.2.b and M.A.5.b are in the works right now with a July end deadline for Wave 4 (Jen, Lance and Allyson are working with CTR)
3. Otherwise all other measures will need to be updated in 2022.
