### ISSUE TITLE
Research: HR Employee List Automation

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6649]
Diana M
DTS

- Researched how Employee IDs and Email Addresses are created
- Reached out to HRD and then Controllers office

**Comment by dianamartin** [comment]
Contacted Controller contact Ginny M. 
- We had a discussion about what I was looking for in the BANNER System
- Ginny said she'd follow up with her contacts about my questions

She messaged 7/8/21
>Hi Diana, sorry for the late response.  I did receive one response back on the emails in Banner.  It was confirmed that what is in Outlook does not feed into Banner.  The emails are manually entered by the department HR.  I will reach back out to my other contact on the employee ID.  i will make sure to get an answer to you tomorrow.  i hope you are doing well.  have a great evening.

I replied 
>Thanks for getting back to me about it. Okay, that's really good to know and confirm about the email addresses. Let me know what you find out, I appreciate your effort to help me get answers. Have a good weekend if we don't sync today!

Messaged on 7/9
>Hi Diana,  I confirmed that the employee ID is generated when the department first enters them into PPAIDEN in Banner.  The ID is generated before they are even assigned a position.  As soon as the department enters in the name, address, etc, the ID generates for them.

**Comment by dianamartin** [comment]
# What I Learned from research on BANNER
- `Employee ID`:  the employee ID is generated when the department first enters them into PPAIDEN in Banner. The ID is generated before they are even assigned a position. As soon as the department enters in the name, address, etc, the ID generates for them. 
- `Email Address`: Outlook does not feed into Banner. The emails are manually entered by the department HR. 
  - so essentially the Outlook list if the accurate more up to date list which was we speculated.

**Comment by moorerst** [comment]
@dianamartin I sent email to Jeffery @ CTM requesting information on the employee data that John mentioned may be available on the G: drive

**Comment by moorerst** [comment]
@dianamartin received the following information from Jeffery @ CTM:
What I did for John Clary was create an script to export employee data out of Active Directory which I’ll run usually once a month unless requested more often. 

Here is the latest export of ATD Users:
[ATD users.xlsx](https://github.com/cityofaustin/atd-data-tech/files/6803615/ATD.users.xlsx)


I export this data here: '\\coacd.org\dfs\atd\atd\ATD_GIS\02_ENT_APPLICATIONS\app_Human_Resources_Manager\_ctm_users_integration\'  
The info is for any Austin Transportation Employee.

**Comment by moorerst** [comment]
I noticed a few fields that we capture in the HR Employee app are not on this list:
Class
Class Description
Work Status
Position # 
Date of Hire
Ask Jeffery if these fields could be added. Here is his response:
So there isn’t an standard attribute for those values but we do have custom attributes we can use. To my knowledge currently not all extensionattributes are used as there are 1-15. 

For example 

Class: = extensionAttribute10
Contractor
Regular
Temporary
Class Description: extensionAttribute10
Temporary Exempt
Temporary Non Exempt
Standard Exempt
Standard Non Exempt
Executive 1
Executive 2
Work Status: extensionAttribute11
Full Time
Part Time
Position # extensionAttribute12
Date of Hire extensionAttribute13

I would however suggest that the Class and Class Description could be one value vs two in AD. 

Here is an example for an made up user John.Smith who is Postion Number 123456789 hired March 12 2009 and is a Contractor Temporary Non Exempt

extensionAttribute10 = “Contractor – Temporary Non-Exempt” 
extensionAttribute11 = “Full Time”
extensionAttribute12 = “123456789” 
extensionAttribute13 = “03/12/2009” 

Provided you have this data for the employees this could be added into the AD but would only be viewable via the Excel as the Address Book wouldn’t show the Extension Attributes values. 

Let me know if you have any questions as this can be added, but the output from AD would show  extensionAttribute vs the world Class, Work Status, ect..
