### ISSUE TITLE
Enhancements to VZ DB export to Socrata (data dictionary, data age limit, & description text)

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#6661]
Following a discussion in the Vision Zero Sprint Review, the following enhancements were identified for the ETL process which exports data from the Vision Zero database to be upserted into Socrata:

- Add columns which contain the textual description of the value shown in the /something/_id columns. The intent is to allow these values to be self documenting and not require a separate lookup table. The columns to be addressed are found in the attached spreadsheet, as well as the values for the various integer values.
- Implement a age limit for records which are contained in the Socrata dataset with the intent of focusing the data on more recent events, staying in compliance with any inherited CRIS data-retention policies, and continuing to offer 100% of the data required by queries in the VZV, such that no changes to that application are required.
- Modify the metadata description of the datasets to minimize or remove the implied responsibility of the VZ team to process data requests by the public. Lewis offered to suggest the revised language.

**Comment by frankhereford** [comment]
There are other valuable suggestions in issue #2553 which should be considered.

**Comment by Charlie-Henry** [comment]
Took the intermediate step to change the column description of the `prsn_ethnicity_id` column in the Crash Victim Demographic Records dataset:

>Person Ethnicity ID. Coded as: 0: UNKNOWN, 1: WHITE, 2: HISPANIC, 3: BLACK, 4: ASIAN, 5: OTHER, 6: AMER. INDIAN/ALASKAN NATIVE, 94: REPORTED INVALID, 95: NOT REPORTED

All of the other column descriptions had their own respective lookups.

**Comment by patrickm02L** [comment]
##10/2 
Chatting with @xavierapostol we determined tha this has been resolved through multiple individual Issues. Here is the dataset link for [reference](https://data.austintexas.gov/Transportation-and-Mobility/Austin-Crash-Report-Data-Crash-Victim-Demographic-/xecs-rpy9), which include a data dictionary, update description removing VZ reference, and a 10-year retention policy requirement.
