### ISSUE TITLE
[ROW] Report: Submissions Avg Review Time & Days Elapsed calculation

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#6664]
This report is a high priority for ROW Management. To calculate Days Elapsed was previously done with a script that was only partially successful in updating records. This report is provided weekly to upper management.

Need to determine if we can easily update the Days Elapsed script for the new ROW Portal or if we need to build in Knack. If we build in Knack we need to capture a Begin Review Date and use a Business Days equation.

**Comment by ChrispinP** [comment]
Built prototype report for Average Review Time by Month
![image](https://user-images.githubusercontent.com/67915167/125674679-6138992e-59d9-401b-b6a8-a497779a6a8f.png)

**Comment by amenity** [comment]
@ChrispinP - check with Ryan to see if he has what he needs on this.

**Comment by ChrispinP** [comment]
Darren currently ooo but sent teams message to Ryan & Darren for followup.

**Comment by ChrispinP** [comment]
No issues, closing
