### ISSUE TITLE
Disable the Robin Check In feature

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6668]
Gilda requested the Robin check in feature be turned off because it is not being used.

**Comment by dianamartin** [comment]
The "Desk check-ins" function is on `All desk types`, switching to `Hote/hotel only`
- Stephanie and I think that if ATD Executives want employees to check-in it needs to come as a mandate, strictly enforced too.

**Comment by dianamartin** [comment]
Emailed user
>I’ve updated the "Desk check-ins" function is from All desk types, switching back to Hot/hotel only desks. I think if you want to know the daily attendance of staff then the check-in function would need to be more enforced and mandated.
