### ISSUE TITLE
Builder Huddle: Employee List Automation Discovery

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6670]
Meet again to review the research gathered for the employee list automation
issue #6649

**Comment by moorerst** [comment]
Meeting scheduled for 7/27

**Comment by dianamartin** [comment]
Needing rescheduling due to John being out of town

**Comment by moorerst** [comment]
rescheduled for Friday 8/6

**Comment by dianamartin** [comment]
# Diana's Notes
- CTM report has Employee ID
- CTM report has active employees?
- HRD has active employees? API access to Banner, have code written to fetch the information

Create Employee ID 
Knack flag for manual entry - temp
Email Address creation - delay (from NERF process)

Use HRD report and Jeffrey's report 
- Have correct email from CTM and Banner will let us know a new employee exists
- Create accounts and deactivate accounts automatically
- Send emails when folks get activated and deactivated 
- Run that same process on the DTS Portal

## Next Steps
- Chia project when she gets back - 8/16
- Set up meeting with Chia to orient Chia
- Grooming session: Amenity, Mateo, Chia, John, Stephanie and Diana 

## Set-up Deliverables
- Susanne Harm's report export
- Email notifications: Meredith, Gilda, Scott

**Comment by moorerst** [comment]
@dianamartin these fields were missing from Jeffery's report should I ask him to include these fields in his report?
Class
Class Description
Work Status
Position #
Date of Hire

**Comment by dianamartin** [comment]
@moorerst Yes, I think it'll be helpful bc if we use both reports and one report turns out to be better than maybe we can simplify the process

**Comment by moorerst** [comment]
emailed Jeffery to add the additional attributes to the report.

**Comment by moorerst** [comment]
@diana this is the response from Jeffery: 
**That’s simple enough to do I would just need your department/group to provide/update the excel spreadsheet with that info for the users. Or provide the info and I can work on adding it into Active directory and then schedule an task to generate the file monthly.** 

After speaking with Jeffery I determined the fields we wanted to add are Banner data fields. There are attributes/spaces in active directory to put the Banner data but the data is not currently captured from Banner and populated in AD. We would have to provide the data to be added into AD. I don't see any advantage to doing this. We can still use the AD list along with the Banner list to generate a complete of new and separated ATD employees. There are fields we would capture from each report to complete a new employee record.

**Comment by dianamartin** [comment]
@moorerst Yeah, I don't see why we'd do this if the Banner report does provide these fields. It'd be faster for us to take both reports and combine the fields we need to have instead of making one report transfer fields to another report.

**Comment by moorerst** [comment]
scheduled follow up meetings for next steps:
Deliverables
Builder huddle/grooming
Closing this issue
