### ISSUE TITLE
Meeting: 7/14 - TIA Mod Project Meeting 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6671]
### Participants
Nathan, Joan, Chrispin, Nate, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [x] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes

7/14 NOTES

### MITIGATIONS MAP PAGE
Andrew improving mitigation map, improved search functionality
Project location: can center on the primary project location
- Address
-Trips Per Day: Is this necessary?
**STAKEHOLDER ACTION**
 - Joan said that it's not that important, most important is the name
 - Will talk internally if there is a need to see additional information  

## MAP SEARCH
indexing every combination of streets and street name
COA Address Points - using this layer as geocoder
ArcGIS Geocoding Service
- Just needs first 3 letters of

There is a bug right now: Knack bug, normally can pull coordinates. 
- back end bug

## SEGMENT & INTERSECTION MAP - Opens in new window or new tab

## CHANGES EXPLAINED
### MITIGATION FEE-IN-LIEU
- this field was Rich Text, now Short Text - will help with export
- formerly paragraph tags, html tags

### MITIGATION BUTTONS
Trigger buttons
- Click 5 and click on 1
- These buttons are all spaced out
- Buttons add new rows to these tables

### MITIGATIONS REPORTING
Total Mitigations By Type
Order of these fields are not ideal for the stakeholder
Add a legend at the top for most used field

### TIA REPORTING
- Bar Charts - giving the total numbers 
- Get Curtis' feedback
- Pie charts are nice to have, can remove them

### MEMO DETAILS PAGE
- Everything that is on the memo is on the same page now
- Aggregated bc it was separated before
- Mitigation tables that are exportable
- Includes Last Submitted Date
- Inlcudes Send Final Memo button - generates the final memo date

- Memo Details Title is too large
- Reduce the size of the title
- If can reduce the white space

Icons on the sub sections
- Ruled in favor of keeping the Icons

### TIA APPLICATION
- Change the "Don't press the back button", put to bottom page
- Adjust the "Do not refresh instructions to include, do not press back button

### TIA CASE DETAILS
- MOBILE ENHANCEMENTS
Keep custom menu, but make it mobile friendly - Custom
-  Chia is working on it..

## LANGUAGE UPDATES
### CASE DETAILS PAGE
- Request Status, change to "Status"
- Request Created, change to "Created"

### EDIT CASE DETAILS & NOTES - this makes sense to stakeholders
APPROVE OR CHANGE CASE STATUS
- Change to "Update Case Status"

### MEMO DETAILS PAGE
- SEND FINAL MEMO - only action is to add date
- Want to change case status to completed?
  - Leave it manual, no automation at this point

### TIA CASE DETAILS
REVIEWER COMMUNICATION
- Suggest to call it "Notes", decided to call it "Comment Log" 
- remove "Leave a message for other Reviewers on the case"

### REQUESTER INFORMATION
- Would like to call it "Applicant" v. "Requester"

### SCOPE SUBMISSIONS & SUBMISSIONS 
SUBMISSIONS 
- Submissions, change to "TIA Submissions"

### TIA SCOPE SUBMISSION DETAILS
- Scope Submission Cycle #1 - Approved, change to "Cycle #1 - Approved" 

## TRAINING PLAN & GO LIVE
Meeting next Monday, TIA Project Meeting
Workshop scheduled, the training for TDSD team

INTERNAL TRAINING
- Stakeholders requesting to record so that other staff who can't attend can watch the training session 

- Working on agenda
- Working on workflows

Delete Test Records
Import Records?

Planned Go-Live for July 26

**Comment by ChrispinP** [comment]
Some of the small action items completed. Will discuss with Tracy on other resulting issues such as a report legend. It may not be mvp but seems like a good idea.

**Comment by amenity** [comment]
@TracyLinder - please close once you've created issues for action items. 🙏

**Comment by ChrispinP** [comment]
no further action for now, closing
