### ISSUE TITLE
Implement design refinements to "Staff" page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6674]
These changes will make it easier to scan through the list of users and see more at once. 

<img width="1201" alt="Screen Shot 2021-07-15 at 12 00 20 AM" src="https://user-images.githubusercontent.com/1463708/125731342-2866e29c-a4e4-4950-b1ee-8640a7cc09a6.png">

- [x] Remove pagination (show all records)
- [x] Remove "Date Added" and "Cognito user ID"*
- [x] Increase "Workgroup" column width so that it doesn't wrap at full/desktop width.
- [x] Add column "Role" (viewer, editor, or admin)
- [x] Default sort alphabetical by first name

*@sergiogcx - can we remove Cognito user ID from that page? If not, can we display it in the individual users' actual account pages if we need to be able to access it, so the table rows aren't so tall?

**Comment by patrickm02L** [comment]
@patrickm02L review.

**Comment by johnclary** [comment]
looks good to me! do we need the "Date Added" column?

**Comment by amenity** [comment]
Good call. I think "Role" would be useful though.

**Comment by sergiogcx** [comment]
@amenity there is a PR:
https://github.com/cityofaustin/atd-moped/pull/380
