### ISSUE TITLE
Write script to automate process for data updates from Signs and Markings app to Open Data Portal 

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#6676]
https://docs.google.com/document/d/19C31MLIKiwFJobT8359sfJyYxHc0Mqa5v5_2jDXFUzQ/edit

knack to socrata only
no legacy config or scripts exist
twice a day updates, 10a, 4p CST

**Comment by chiaberry** [comment]
https://github.com/cityofaustin/atd-data-tech/issues/6636 meeting issue

**Comment by johnclary** [comment]
@chiaberry See also #3114. There is already an [ETL in place](https://github.com/cityofaustin/atd-knack-services/blob/37aa667e17d265ffcaa3568587cf470ace55da8d/services/config/knack.py#L140) to publish this data to AGOL. Happy to discuss.

**Comment by chiaberry** [comment]
@johnclary the ETL that is in place references different views and scenes then the ones Surbhi outlined in this document (https://docs.google.com/document/d/19C31MLIKiwFJobT8359sfJyYxHc0Mqa5v5_2jDXFUzQ/edit#) They are different sets of data, right? The existing ETLs use "scene_1249", but the ones in the doc use scene 1407 cc: @dianamartin

**Comment by dianamartin** [comment]
@chiaberry @johnclary Surbhi made the API views under the "Private" not "Public", is that okay? the Scene 1407 is the page the other object tables were added to, so multiple tables on that page scene. 

- High Level Dashboard Datasets for PowerBI - scene `1407`
  - work_orders_signs_markings_time_logs - scene_1407/views/`view_3516`/table
  - work_orders_signs - scene_1407/views/`view_3518`/table
  - work_order_markings - scene_1407/views/`view_3519`/table
  - work_orders_markings_jobs - scene_1407/views/`view_3521`/table

**Comment by chiaberry** [comment]
I have been able to pull the records from knack -> postgrest for all of the views  and knack -> socrata for all of them except 3521/ markings jobs (troubleshooting that now)

**Comment by dianamartin** [comment]
I just checked the OpenData datasets and they look like they've updated on 8/2 which is when you worked on them, so I'm thinking they worked as well!

**Comment by johnclary** [comment]
@chiaberry when you're back in the office—would you remove the Knack API views you're not using anymore? looks like there are some redundant ones in the high-level dashboard scene.

**Comment by johnclary** [comment]
ah, wait. i'm confused now. plz hold off.

**Comment by johnclary** [comment]
ok—we're good here. All remaining tasks are captured [here](https://github.com/cityofaustin/atd-data-tech/issues/3114#issuecomment-894562461).
