### ISSUE TITLE
Requested notice of updated comp costs on VZE dashboard

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#6685]
@patrickm02L - Per Lewis Leff, the VZE dashboard should contain a notice of the updated comprehensive cost schedule when we roll those changes into production. I will submit a PR to provide this feature.

**Comment by patrickm02L** [comment]
@frankhereford I think we can Use this as the Issue for the feature. We'll just need to edit it a bit to add more information about what the Comprehensive Cost Schedule.
