### ISSUE TITLE
Offboard Surbhi B.

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6694]
## IT Permissions and Access

- [x] 1password
- [x] Slack
- [x] Miro
- [x] Knack Apps
  - [x] Shared Mobility
- user account - inactive
  - [x] VZA
- user account - inactive
  - [x] SMB 
- user account - inactive
  - [x] AMD
- user account - inactive
  - [x] Banners
- user account - inactive
  - [x] DTS Portal
- user account - inactive
  - [x] Finance & Purchasing
  - [x] ATD Forms
- user account - inactive
  - [x] HR
- user account - inactive
  - [x] Parking Enterprise
- user account - inactive
  - [x] RPP
- user account - inactive
  - [x] ROW
- user account - inactive
  - [x] TDS
- user account - inactive
- [x] GitHub - team/reassign
  - [x] Transfer issues assigned from Surbhi to Diana
- [x] Google Drive
- [-] SERF
>I called CTM to confirm that a SERF was submitted. Turns out we didn't but Surbhi got all her emails/account stuff sorted so CTM said submitting a SERF isn't necessary. 
- [x] DTS email DL
- [ ] About Us
>I created an issue for this
- [x] DTS Team Slide
- [x] DTS SharePoint team lists - references the "About Us" page on austinmobility.io

## Recover organization assets

- [x] Badge - Remove access
- [x] Laptop - check DTS hardware closet
- [ ] Docking Station
- [x] Monitors
- [x] Desk Riser - at Cameron
- [x] Chair - at Cameron

## Exit Interview - John was out
- [x] follow up in 2 weeks - scheduled 8/10

## Transfer of Ownership
- [x] Offboarding Plan on 7/6
- [x] Knack -> PowerBI Overview meeting on 7/9
- [x] SD 2023 Overview meeting on 7/9
- [x] Vision Zero Overview meeting on 7/9
- [x] Shared Mobility Operations Overview meeting on 7/14
- [x] Vision Zero CIC Project Updates and Discussion meeting on 7/14
- [x] CIC Midsummer Review on 7/15

**Comment by dianamartin** [comment]
- I removed Surbhi's builder access to Knack apps, still have to go through every app to remove user accounts for her.
- I finished re-assigning GitHub issues that were Surbhi to me or unassigned them all together if it was a backlog "old" issue.

**Comment by dianamartin** [comment]
@amenity Do we consider this done?

**Comment by amenity** [comment]
@dianamartin - sounds like it! Thank you.🙏
