### ISSUE TITLE
Bug: DTS Portal To GH Assignee

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#670]
**What Happened:** I was testing an AMANDA bug report submission. The issue created was assigned to Jamie. 

**What Should Have Happened:** It should have been assigned to Tracy. 

I'll try to attach the PDF of the form as I submitted it.
https://github.com/cityofaustin/atd-amanda/issues/151

**Related Bug:** The severe AMANDA bug report I just submitted was also assigned to Jamie. 
https://github.com/cityofaustin/atd-amanda/issues/152

**Comment by TracyLinder** [comment]
[Portal Test 2.pdf](https://github.com/cityofaustin/atd-data-tech/files/3726841/Portal.Test.2.pdf)

**Comment by TracyLinder** [comment]
[Portal Test 3.pdf](https://github.com/cityofaustin/atd-data-tech/files/3726854/Portal.Test.3.pdf)
This was what I submitted for the severe bug test.

**Comment by TracyLinder** [comment]
@johnclary is there an update on this?

**Comment by johnclary** [comment]
Patched w/ PR under review.

**Comment by johnclary** [comment]
@TracyLinder this has been fixed. will you run a test to confirm?

**Comment by amenity** [comment]
@TracyLinder - can you confirm this is fixed?

**Comment by TracyLinder** [comment]
I performed the same test & all went well!
