### ISSUE TITLE
Feature - [ROW] TCP Tracker - Due Date Auto-Populate

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6701]
### As a TCP Tracker User, I would like the TCP Due Date to Auto-populate. I'd also like to be able to manually select the due date as well. 

**Stakeholder:** Laura R.

**Notes**
For inline editing to work, there can't be any conditional rules on the field. So right now stakeholders must choose one or the other. Laura chose manual for right now, until we can find a better approach.

**Comment by TracyLinder** [comment]
Chrispin asked Laura to choose between autopopulate and manual (for right now), and she chose manual.

**Comment by TracyLinder** [comment]
### Possible Solution

1. Add edit button on the submission line, to allow user to manually override the due date.

@ChrispinP may add more possibilites later.

**Comment by TracyLinder** [comment]
**Notes:**

- Still a need
- Solution: Add new button to Submission Details page: Adjust Review Dates

**Comment by ChrispinP** [comment]
This been successfully built in Test TDS and can be replicated for the ROW Portal.

4 Fields to auto calculate the initial due date, set it, and adjust it manually.
![image](https://user-images.githubusercontent.com/67915167/147123858-af8f09ae-9acc-4068-8697-2b358e484c46.png)

Adjust the Due Date Manually with a menu button:
![image](https://user-images.githubusercontent.com/67915167/147124027-ac8c58fe-a986-451b-8ce2-7baf1893eeff.png)

Both fields present in the table so Reviewers know the original due date and the new due date with strikethrough and bolding to emphasize the new due date:
![image](https://user-images.githubusercontent.com/67915167/147125149-2005afbe-bf53-48b5-8024-4a6d3e24705c.png)

Ready to review and put on deck

**Comment by ChrispinP** [comment]
Feature added for TCP Submissions.

Updated the Submissions Table:
![image](https://user-images.githubusercontent.com/67915167/147836614-21cf0777-e5de-433e-99fd-4c632dc477f0.png)

Updated the Form:
![image](https://user-images.githubusercontent.com/67915167/147836625-96c4398e-6f9b-46e7-ac64-a31b0b715d7b.png)

Ready to review

**Comment by TracyLinder** [comment]
I need to notify stakeholders that this was done.

**Comment by TracyLinder** [comment]
Hi Darren,

Just a quick note to let you know The TCP Tracker was updated last week for this request/issue. The system now auto-populates the submission due date and also allows the user to change the date manually. 

My apologies for not notifying you sooner about this. Please forward this to staff as needed and let me know if there are any questions. 

Thanks,

Tracy Linder, Product Manager
