### ISSUE TITLE
Synthesize Mobility Project Viewer Research Phase

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6704]
Create slide deck or text document that compiles and summarizes @janetchuhl 's work on the Mobility Project Viewer.

**Comment by janetchuhl** [comment]
@amenity @patrickm02L Mobility Project Viewer Research Phase [summary deck](https://docs.google.com/presentation/d/1oqPyPEg_Gyt4_mYj-t4ZFob5tdqsX296taAe7O8dSLM/edit#slide=id.ge80d652fb6_0_10) ready for review.

**Comment by patrickm02L** [comment]
This is phenomenal!
