### ISSUE TITLE
Review Moped 0.7.0 usability tests and synthesize findings

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6705]
- Create bug reports
- Document interesting pain points and interesting observations

**Comment by patrickm02L** [comment]
Now that that all of the In-person interviews are complete. Lets do the following to get out findings:

- Create doc to captures the issues from the user tests
- Group observations where testers struggled by task
- Call out where in the videos those struggles happened
- Summarize the main issues with each task

For XD: Incorporate the issues for each task into the doc. Tests are still out until Fri, July 23.
Link: https://xd.adobe.com/view/87c30c8b-590f-4347-b832-73beb9b21888-d290/screen/6220afb3-da95-4af6-89bd-9181fa2b8e3a

For Presentation: Collect clips for each task that highlight main issues. (download, clip with Quicktime, upload back to google drive.

**Comment by patrickm02L** [comment]
Send out to John, Amenity and Patrick by Tuesday, 7/27/21 for review.

**Comment by janetchuhl** [comment]
@johnclary @amenity @patrickm02L I have compiled all feedback from both in-person and self-moderated usability tests to this [doc](https://docs.google.com/document/d/1O9xvIlyvJOy90lGN4s6ec7p3A5PUU4FPBnK5m_fJ9Hs/edit#). Please review them and add comments before we meet on Thursday, 7/29. Thanks!

**Comment by patrickm02L** [comment]
Meeting moved to Friday, 7/30. 

We talked through some of the Add Project observations, and came up with a good format for how to resolve the issues. Each task will have an 'Action Items' section for resolutions. We're also planning to use the XD screen shots to use to apply the changes. 

Next meeting is Monday, 8/2.
