### ISSUE TITLE
Conduct Mobility Project Viewer ideation session with PIOs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6707]
Shoot for two hours the week of August 2nd 
Include on invite
- Devs (optional)
- Patrick, Amenity
- Stephanie (optional)
- John (optional)
- Tracy (optional)

**Comment by janetchuhl** [comment]
[PIO Ideation Summary Doc](https://docs.google.com/document/d/1Gm7jBAVxVIO8caLzz_rSUgkeN9U9mFBja3PFmmRsw_k/edit#heading=h.vf1aayvza2o) created to capture all inputs.

**Comment by janetchuhl** [comment]
@patrickm02L good for review

**Comment by patrickm02L** [comment]
Looks good!
