### ISSUE TITLE
Prepare for Mobility Project Viewer ideation session 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6708]
- [x] Schedule #6707 
- [x] Determine ideation activities (@patrickm02L can provide guidance)
- [x] Put together Miro board

**Comment by janetchuhl** [comment]
Scheduled ideation session: 8/2 Mon 8-10am

**Comment by patrickm02L** [comment]
Review [PIO Interview Synthesis](https://docs.google.com/document/d/1P8A4ocvQaGApe-_CKXhMvNTeYrguflOj7-xR6HHIRIE/edit?usp=sharing) doc internally, send out to everyone who's participate in the Ideation no later than Thursday.

@amenity would you take a look at the synthesis and add comments to the doc by Monday, July 26th.

**Comment by amenity** [comment]
Will do.

**Comment by amenity** [comment]
@patrickm02L @janetchuhl - the synthesis doc looks great. Fantastic idea to put this together.

**Comment by patrickm02L** [comment]
Created a plan outline and choose Brain Writing Exercise for next week with @janetchuhl. As prep, Janet will send the PIO Interviews Insights and Themes Doc, as well as ask everyone to RSVP by Thursday, 7/29/21. 

Janet and Patrick will meet on 7/29/21, to walk through agenda, and do a dry run of the Ideation Session actives.

**Comment by patrickm02L** [comment]
Janet and I met to go over the [Plan/Agenda](https://docs.google.com/document/d/10hRQM_xsF54qUORJGF4iFxGOZiYKXpc_iKlZ08E-MME/edit?usp=sharing) and Brainwriting exercise in Miro. We worked out the flow of who's taking what in the agenda, and did a dry run of the Brain Writing exercise to make sure that it was smooth. 

Janet will ping individuals to get their spirit animals for our icebreaker if they don't get them to us by the Friday, July 30th deadline.

Everything's good for Monday, August 2nd @ 8am.

**Comment by janetchuhl** [comment]
@patrickm02L ready for review and to be closed

**Comment by patrickm02L** [comment]
Great work!
