### ISSUE TITLE
Compile Mobility Project Viewer Impact Feasibility Matrix

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6709]
Use the post-it notes from the ideation session that were starred to come up with a prioritization of solutions for each theme and insight. 

Create a doc, with the starred post-its at the top of each sections and a screen shot of the miro board to capture all of the of the post-its. 

In Miro, create a Feasibility Matrix with four quadrants. Impact is at the top. Feasibility is the far right.

Set up a session with Patrick and Amenity to sort the starred post-its in to each feasibility matrix. 

Then add the Prioritization to the doc for each theme and insight.

**Comment by janetchuhl** [comment]
Ideation [summary doc](https://docs.google.com/document/d/1Gm7jBAVxVIO8caLzz_rSUgkeN9U9mFBja3PFmmRsw_k/edit) is created. Impact Feasibility Matrix is on [Miro](https://miro.com/app/board/o9J_l_y7IaA=/).

**Comment by patrickm02L** [comment]
Amenity, Janet and I met on Monday, August 9th to go over the Impact/Feasibility Matrix and have made notes that will come in handy when we start creating a Moped Viewer. Considering this issue closed.
