### ISSUE TITLE
Update Moped theme colors

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6712]
@patrickm02L @johnclary - I'd like to propose [gently adjusting primary red/cyan/grey that we currently have and adding some additional variations on each](https://material.io/resources/color/#!/?view.left=0&view.right=1&primary.color=1E88E5&secondary.color=ff4949). 

Previous
![Moped-previous](https://user-images.githubusercontent.com/1463708/126237866-14afc0b1-5ac1-48d3-a0ca-76f6bb20fc7a.png)

Proposed
![Moped-proposed](https://user-images.githubusercontent.com/1463708/126384316-77e04e8f-63c6-44f1-9cea-9b840b3f4235.png)

---
So, redefining the specifications at https://github.com/cityofaustin/atd-moped/edit/main/moped-editor/src/theme/index.js :

Background Default `#edeeed` 

Background Paper `#ffffff`(maybe this should be set with `colors.common.white`?)

Primary Main `#1e88e5`

Primary Dark `#005cb2`

Primary Light `#61b5ff`

Secondary Main `#ff6549`

Text Primary `#212121`

Text Secondary `#848484`

### Addendum

Remove the default background color override applied to `jss20`
![Screen Shot 2021-07-22 at 3 36 14 PM](https://user-images.githubusercontent.com/1463708/126706763-502321ac-47ec-4da2-a7eb-c336e5213879.png)

- Try removing the line that specifies background color here: https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/layouts/DashboardLayout/DashboardLayout.js (We'd _like_ to maintain all our style definitions in the [theme](https://github.com/cityofaustin/atd-moped/tree/main/moped-editor/src/theme) folder rather than individual files.) 
- If that doesn't work, set it to Background Default

**Comment by amenity** [comment]
Nu colorz in action: 
<img width="1338" alt="Screen Shot 2021-07-19 at 6 04 50 PM" src="https://user-images.githubusercontent.com/1463708/126238445-f24281f3-fa56-46a1-9901-7cf3c6b50962.png">

**Comment by patrickm02L** [comment]
Those colors look good to me. They're a lot softer and play well together.

**Comment by amenity** [comment]
![Screen Shot 2021-07-20 at 2 33 51 PM](https://user-images.githubusercontent.com/1463708/126385633-479ad43f-e8c4-4572-9504-6aea1e6c5873.png)
I'm not sure what to do with the dark background...

**Comment by johnclary** [comment]
Colors look great to me. You could search the repo for use of the dark style.

**Comment by amenity** [comment]
@jgabitto, please also remove the override of the default background color. It's applied on `jss20`
![Screen Shot 2021-07-22 at 3 36 14 PM](https://user-images.githubusercontent.com/1463708/126706763-502321ac-47ec-4da2-a7eb-c336e5213879.png)
