### ISSUE TITLE
[Enhancements] Moped Typography 2.0

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6713]
Making this into an epic, since some tasks are for Devs and some are for Product. Nothing should be merged to master until all issues in epic are complete; otherwise we'll have some whacky fonts.

**Comment by amenity** [comment]
@jgabitto it would be super helpful if you could show us the Material default typography so we can customize starting there instead of with the Devias specs. 

Steps: 
- Comment out lines 3 and 30 here: https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/theme/index.js
- Go to the /devias page locally 
- Copy/past into [this doc](https://docs.google.com/document/d/1aZFQOa75TNeXUZ3ptjhd-LUbw5pG1sFn4npEtK4x8pg/edit#heading=h.b71v6ehlyna4)

**Comment by amenity** [comment]
@patrickm02L - this may be useful to define the new system: https://material.io/design/typography/the-type-system.html#type-scale

**Comment by jgabitto** [comment]
![image](https://user-images.githubusercontent.com/26661521/126830104-2d0fdf0c-5a05-4f5b-ada8-34d34e527b9a.png)

**Comment by jgabitto** [comment]
![image](https://user-images.githubusercontent.com/26661521/126830132-f7ceb355-42c6-4f7e-b414-b05fd69eeab8.png)

**Comment by jgabitto** [comment]
![image](https://user-images.githubusercontent.com/26661521/126833455-c46e5208-411a-4048-b443-3ad1cbe1db9e.png)
