### ISSUE TITLE
Migrate CTR / data-rodeo AWS resources from odd to austinmobility account

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#6722]
- research process to migrate assets
- communicate with KP and confirm production assets that need to be maintained.
- plan migration

**Comment by mateoclarke** [comment]
meeting scheduled with Ken for 9/7

**Comment by johnclary** [comment]
@johnclary @mateoclarke read ken's mateo

**Comment by johnclary** [comment]
We met with Ken last week to plan for this. I'll be working on it throughout the week.

**Comment by johnclary** [comment]
I set up a new postgrest stack on our knack-services ec2/rds for the data lake. Ken is working on migrating the existing data and pointing his ETL scripts to the new instance
