### ISSUE TITLE
BUG: ROW Performance Measure Reports pulled for same date range are reflecting different permit numbers (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#6728]
BUG: ROW Performance Measure Reports pulled for same date range are reflecting different permit numbers

**DTS Manager:** Nate
**Stakeholders:** Paloma, Ryan, Kim, Darren, Blake

![ROW Performance Measure.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/131939ad-78e5-4965-8237-6c04bc10a98f)

**Comment by Nadin-Nader** [comment]
Email to Paloma:

Hi Paloma,

Hope you are doing well. I was reaching out to you to ask you if the report is still reflecting different permit numbers. I will be testing this today also but I wanted to get your input on it. Please let me know when you get a moment.

Respectfully,

Nadin A. Nader (He/Him/His)
IT Business Systems Analyst
Data and Technology Services

**Comment by Nadin-Nader** [comment]
Spoke to Paloma on this and she asked that we wait til Friday's meeting to discuss this as she wanted to run it one more time to see if the numbers are still not matching. She also mentioned that the mismatch is not that big so she has a thought that it may not be the report itself. 

**Status:**
Waiting on results and the Friday meeting to go over them

**Comment by Nadin-Nader** [comment]
The difference in the number has vastly increased recently. Sree will look into this again

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP submitted. This will fetch 50698 (Austin Energy) in our report. And also tried to put another fix to resolve the mismatch issue. This can be tested only in TEST/PROD. Kindly approve and create a task id for me.

Here is the commit ID: [9ac89a7bebee](http://coaamandadevops01.austintexas.gov/R3:9ac89a7bebee878dcdbee13c57c2c368f793c2c4)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0209457**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to **DEV** Please UAT

**Comment by Nadin-Nader** [comment]
This is still waiting on CTM DevOps to deploy to TEST under SCTASK0211411

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to TEST. Please UAT

**Comment by Nadin-Nader** [comment]
Status: Currently Testing/Analyzing

**Comment by Nadin-Nader** [comment]
Sent a message o the Testing/UAT TEAMS channel informing Paloma and Izzy that this was ready for their UAT on TEST.

**Comment by Nadin-Nader** [comment]
From Paloma:

> [2:39 PM] Amayo-Ryan, Paloma
>     We won't have time to test this before we meet on Friday so we would like to look at it during our meeting.

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0217615**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  
I checked the report stored procedure code and verified the data given in the above tables. The reason for the difference:

- In the report the query is omitting the StreetEvent subtype(50510) permits, that looks purposeful. Here is the example of that query.
SELECT  COUNT(F.INDATE) 
FROM FOLDER F
WHERE F.FOLDERTYPE = 'RW'
_**AND (F.SUBCODE NOT IN (50510) OR F.SUBCODE IS NULL)**_ 
AND F.STATUSCODE NOT IN (50003, 70045)--app. incomplete, aborted
AND TRUNC(F.INDATE) BETWEEN TO_DATE('12/01/2021','mm/dd/yyyy') AND TO_DATE('12/30/2021','mm/dd/yyyy');

**Comment by Nadin-Nader** [comment]
During our Friday meeting it was found that the report was correct and that the subcode needed to NOT be selected was 50510. Closing
