### ISSUE TITLE
Project Sponsor Info Update on UC Folder

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6729]
From #6051 

**Project Sponsor Info update Acceptance Criteria:**
- System should display Project Sponsor Info field (76765) in UC folders. 
- The options for the Project Sponsor Info field must be same as the list provided in #2397 .
- The Project Sponsor Info field should be marked Required for Insert and Required for Issue in Back Office (Mandatory for creating application and Validated during Folder Issuance) 
- The Project Sponsor Info field must be displayed on the Portal for UC applications. 
- The Project Sponsor Info field must be mandatory for portal applications.

**Comment by TracyLinder** [comment]
### My Notes

- The info we add will need to be the same we implemented on #2397 
- Do we need to remove any existing project sponsor type fields from the UC when we add this one? 
- I'm assuming it should be added to portal (is it a mandatory application info?)
- Should this field be validated in any processes or folder issuance? 

**This needs to be** assigned to Vish for scoping & AC.

**Comment by vschandramouli** [comment]
Scoping meeting with stakeholders held on 7/29. Currently updating AC for this ticket. Will move to Backlog when done.

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.
