### ISSUE TITLE
[Enhancement] Track who created a project

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6730]
As a Moped user, I need to know who created a project and search for projects based on the creator.

Currently, the only way to see who created a project is to check the activity log. However, we do have an `added_by` column in the `moped_project` table. It is not being used.

1. Add a nullable foreign-key constraint from `moped_project.added_by` against `moped_users.user_id`. On delete, `SET NULL`, on update, `CASCASDE`.
2. Establish Hasura array and object relationships with appropriate permissions.
3. From the Hasura console, modify the `moped_project` table permissions to establish a rule on insert that sets the `added_by` column to the user's ID (assuming it's available from the auth header).
4. Backfill `null` values for this column for existing projects
5. Update the fk constraint for this column to not be nullable.

**Comment by sergiogcx** [comment]
@amenity the event creation is presented last, as per @tillyw's work:

https://github.com/cityofaustin/atd-moped/commit/53da144b5d8be093a7458f6ff10bd041f22160ef#diff-3453284977058be3b359631d89cd76d13664f995724df64eb90aa7c977a2f9a8

**Comment by johnclary** [comment]
I don't know that https://github.com/cityofaustin/atd-data-tech/issues/6697 is really a priority, but we really should get the database side (this issue) taken care of. It is hard to retroactively fix this.
