### ISSUE TITLE
Modify contact information in RPP

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6744]
Requested by Steve:
Can you please remove the contact info for Richard from the Knack website? and also add the contact info for John 512-974-1438 and email. In addition can you please put John's name first and my name second, as I will be handing over RPP duties to him. Our dept will be rotating duties going fwd fyi.   

- [x] Update home page - remove Richard's info, add John's info ahead of Steve's info

- [x] Update Contact Us page - remove 4-1613 add 4-1438 before 4-2891

- [x] Update Payment Options page - remove 4-1613 add 4-1438 before 4-2891

**Comment by ChrispinP** [comment]
all 3 pages updated. complete

**Comment by moorerst** [comment]
@ChrispinP can you format the Payment Page phone numbers so they are not broken up? 

![image](https://user-images.githubusercontent.com/56606465/126683727-b131452f-3002-4b97-84ce-f47bb68fd5ea.png)

**Comment by ChrispinP** [comment]
Ive bumped the tab margin size down. How it shows is a bit dependent on your monitor size. For smaller screens it will break but for most desktops it should show as a single line now

**Comment by ChrispinP** [comment]
It breaks at about 730px now which is tablet size.

**Comment by moorerst** [comment]
@ChrispinP Thanks Closing issue
