### ISSUE TITLE
Add additional workgroups to Moped

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6768]
Create new table, `moped_department`
- Austin Transporation
- Corridor Program Office
- Public Works
- Other

Add lookup column to `moped_workgroup` to connect with `moped_department`.
- All the existing workgroups are in Austin Transportation

Add additional workgroups to `moped_workgroup` table and associate all workgroups to departments

**Public Works** department workgroups:
   - Urban Trails 
   - Safe Routes to School
   - Sidewalks
   - Engineering Services Division 

**Corridor Program Office** department workgroups:
   - Corridor Program Office

**Austin Transportation** department workgroups:
   - ([All existing workgroups](https://user-images.githubusercontent.com/1463708/127951609-e57974a6-d46a-4cab-82f1-cd50b3e5e045.png), besides "Other")

**Other** "department" workgroups:
   - Other

**Comment by amenity** [comment]
@johnclary - I don't remember why we didn't include non-ATD workgroups from the beginning, but I think they'll be important for basic project analysis. If we need to differentiate ATD from PWD (not sure why we would?) then we could either add a new field, add another column to the workgroup table, or prefix the workgroup with `ATD` or `PWD`.

**Comment by johnclary** [comment]
Sounds good to me :)

**Comment by amenity** [comment]
@sergiogcx recommends adding a new departments table rather than adding a column to the workgroup table. 
> If we just add a column, whenever we need to rename or fix something it becomes increasingly difficult and tedious

**Comment by sergiogcx** [comment]
@amenity sounds good, feel free to assign me! :)

**Comment by sergiogcx** [comment]
@amenity there is a PR:
https://github.com/cityofaustin/atd-moped/pull/381
