### ISSUE TITLE
Update "About Us", remove Surbhi B.

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6777]
Update "About Us" page on austinmobility.io 
- [ ] Add Frank
- [ ] Remove Surbhi
- [ ] Update Amenity's title to "Head of Product"

**Comment by amenity** [comment]
@johnclary - setting this up for next week. Should we also remove the CIF peeps?

**Comment by johnclary** [comment]
@amenity just added #7067 to the todo list. This will have to be done by branching from the NextJS version of the site, or, ideally, we finish #6476 first

**Comment by mateoclarke** [comment]
Next.js branch has been merged to prod so this issue and #7067 are unblocked.
