### ISSUE TITLE
[BUG] Incorrect value for a Metrobike kiosk longitude

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6780]
Via Socrata feedback form:
> Hi! I'm part of a Data Science class and our team decided to use this dataset as one of out inputs for our final project. Seems that Kiosk ID: 4699 in the Austin MetroBike Kiosk Locations data set is missing a minus for the longitude Thought you should know! the quality of this data is amazing btw!

**Comment by jaime-mckeown** [comment]
Added the minus to the longitude field for record 4699. The feature layer will update again tonight and the data will be fixed.

**Comment by jaime-mckeown** [comment]
Checked data in AGOL and Open Data, both reflect the change. Let David know.
