### ISSUE TITLE
Discuss amendments to "Data" subchapter of ASMP

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6781]
[ASMP "Data" action table and subchapter](https://drive.google.com/file/d/1ebUafmRtYGKj4O7SbvLMIDXCn-FG5j6o/view?usp=sharing)

From Dan
> It has already been two-plus years since the Austin Strategic Mobility Plan was adopted, and our team is now working on the ASMP’s first amendment process! The ASMP amendment process is focused on ensuring that both ASMP policy and the Street Network Table are aligned with current City needs and goals, and that the ASMP is providing you (and all our Mobility departments) with what is needed to successfully implement your projects and programs.
>
> Earlier this summer we reviewed the Data chapter in preparation for this upcoming amendment process. We would like to meet with you to discuss this subchapter. The introductory meeting this upcoming Thursday the 22nd, will be a brief overview of why we’re amending the ASMP and what our process for doing so will be. This meeting on the 27th will be a deeper dive into the Data subchapter, specifically. We would like to go over our subchapter review with you, and if there are any needs/desires/issues surrounding the ASMP that you would like to discuss, we would like to have that conversation.

**Comment by dianamartin** [comment]
# Meeting Notes
## Meet SDD Team
- Cole, Dan, Warner, Alex, Kelsey, Ashley, Arthur
 
## Meet DTS Team
- Amenity, Mateo, Jaime, Diana

# ASMP Policies

**Comment by amenity** [comment]
**Some first thoughts on policies** 
- I think we could add a 4th policy that calls out "proactively collect ... quality data" (currently squished into #3, "Use data to make informed decisions". Our most significant in-house products (VZE, Moped, Data Tracker) revolve around the collection/management of quality data. 

**Action Items**
- Can point to these when speaking with Council, so make sure that these capture justifications for what we need. 

**Indicators and targets** 
- Practically speaking, have not been tracking these since SD23 reporting is so involved
- Also some overlap with SD23
- Going to attempt to cover these but play by ear on whether we're able to vet, find good data sources, etc.
- Don't need to wholesale update at this point

Warner thinks "Data Rodeo"  came from the old Smart Mobility Roadmap document... @johnclary ?

**Comment by johnclary** [comment]
Correct—Data Rodeo was a smart city challenge idea. there's a video of Mayor Adler talking about it somewhere. We transferred that energy into projects with CTR, namely our data lake.

**Comment by johnclary** [comment]
@johnclary do this

**Comment by johnclary** [comment]
I sent comments to the ASMP team in August.
