### ISSUE TITLE
[TDS] TIA - Ability to inline edit Dates for Cases and Submissions for Historical accuracy

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#6787]
Currently date/time fields are automated but stakeholders would like the option to adjust date/time fields for historical case and submission data they are adding to the application for the first time.

Preference is to inline edit them on the Reviewer Dashboard and Case Management pages. They would like all dates opened to editing while they determine which ones they need to adjust.

**Comment by amenity** [comment]
@TracyLinder - Nathan asked for this yesterday. Let us know whether @ChrispinP can get started on it or whether there are other backlog issues that are higher priority.

**Comment by ChrispinP** [comment]
John gave me the go ahead on this enhancement on Thursday.

**Comment by ChrispinP** [comment]
Inline Editing enabled for all date fields on the Reviewer Dashboard and Case Management page excluding Fee Paid Dates since those can already be set in app. Added Modified Date and Modified By rules for date updates.

complete
