### ISSUE TITLE
Add flag to track if a crash was caused by a medical issue

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#6789]
Crashes which are the result of a medical issue are a special class of crashes. We have experimented with different queries which can be used to identify these crashes, but often it is only down to the human interpretation of the investigator's narrative. Being able to track these and then be able to exclude them from various analysis efforts would be a aid to the VZ division.

**Comment by patrickm02L** [comment]
@xavierapostol MVP manual flag. Automatic triggers - crash severity, personal injury severity, and update APD/ATD fatality count.

**Comment by patrickm02L** [comment]
@patrickm02L, @xavierapostol, @frankhereford meet to talk about how to think through how the medical events are tracking fatalies.

**Comment by patrickm02L** [comment]
Frank and Xavier and I met Sep 14th to talk about how to approach this problem. 

We came to the conclusion that the best approach to identifying which crashes were related to a medical conditions was to create a foreign key lookup table that could join Serious Injuries and Serious Injury Types. 

Identifying which ones were medical flags based on the ATD criteria and 30-day time frame could be accomplished by creating a `null` condition that would act as a hidden boolean. 

Implementation is as follows:
- Create look up table and populate it
- Create a field in the crashes table that points to the causes table was created
- Add user interface element to allow the user to select the cause and have the selected cause be stored in the database.

@frank please let me know if I've missed anything.

**Comment by xavierapostol** [comment]
> identifying which crashes were related to a medical conditions was to create a foreign key lookup table that could join [Killed] and Serious Injury Types.
> * Create a field in the crashes table that points to the causes table was created [I don't think another field would be helpful, I'd suggest doing this in a query/view]

Some suggested edits in []

**Comment by patrickm02L** [comment]
Thanks for the consideration/input @XavierApostal.

**Comment by frankhereford** [comment]
9/20 Grooming:

This is an attribute of the person/primaryperson object, and we should store it as a boolean value on that table. We can create a view to aggregate this data to be joinable against crashes, and then exposed via the graphql.

**Comment by xavierapostol** [comment]
Per @patrickm02L's request: could you define the fields that are the contributing factors atd_txdot__contrib_factr_lkp to at fault?

The contributing factor fields are attributed to the UNITS table. That unit will either be a Motor Vehicle, Pedestrian, or Pedalcyclist (for the most part). If there is a contributing factor to that unit, then it should get an "at fault" flag = TRUE.

**Comment by patrickm02L** [comment]
@xavierapostol thanks that makes sense.

**Comment by patrickm02L** [comment]
## 10/2
chatting to @xavierapostol and realized that there are other ways that the VZ team is tracking medical events including in the VZE notes. He gave the go ahead to close.
