### ISSUE TITLE
[VZA] Vision Zero in Action schedule Shift imports

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6799]
See #6745 for @dianamartin's notes on her first round.

**Comment by patrickm02L** [comment]
@amenity is this Epic okay to close?

**Comment by amenity** [comment]
@patrickm02L - no; this is the one we made last week during grooming to organize this series of recurring tasks. The epic itself stays in the "Ongoing" pipeline and has no story points.

**Comment by ChrispinP** [comment]
Confirmed with @johnclary , these imports are no longer needed, closing this epic as complete
