### ISSUE TITLE
[Spike] Explore Excel macro as potential solution

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6801]

**Comment by ChrispinP** [comment]
My Excel Discovery was successful. Tested creating a few Macros. I believe a Macro will greatly improve the reconciliation process by simplifying the spreadsheet process and limiting the amount of Excel work needing to be done. I believe this is an optimal short term solution.

**Comment by johnclary** [comment]
If we went this route—would need to step through the reconciliation process with Ashlande to develop macros. Let's hold off until we have a better send of what data Flowbird will provide. Closing
