### ISSUE TITLE
Propose and discuss digitization of existing work order in Knack

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6802]
Meeting scheduled 7/29 at 3:30 pm. 

I've discussed this request with Christina and it's a long story so I might make a workflow instead.

**Comment by dianamartin** [comment]
New Work Order Markings as template
Create brand new New Work Order Markings form
- Requester: populate SBO/Whereabouts
- Create new fields: 

**TYPE OF MARKINGS**
check box, multi-select
#### Long Line Markings

- Bike Lane Lines
- Cat Tracks / Guide Tracks
- Center Lines
- Edge Lines
- Lane Lines
- Turn Bays

#### RPM Markings

- Concrete Domes
- Raised Pavement Markings

#### Short Line Markings

- Crosswalks
- Railroad Crossings School Zone Lines
- Stop Lines

#### Specialty Markings

- Arrows
- Delineators
- Hash bars / Crosshatches (4”-12” width)
- Legends
- Painted Curbs
- Painted Domes / Radius
- Parking “T”s and “L”s
- Rubber Speed Cushions
- Speed Hump Markings
- Words
- Yield Lines

WORK TYPE - Add to work type
- Pothole Repair
- Utility Cut
- Concreate Work

SBO COMPLETED DATE - Already exists
SCHOOL - Y/N - Already exists

**Comment by dianamartin** [comment]
Discussed with Lauren, Susanne, Christina on how we should approach the SBO form creation. Everything sounded pretty good and straight forward. I placed this task on deck.
