### ISSUE TITLE
Implement TIA refinements discussed in TIA Technical Review

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6805]
Some of the refinements are checked off [here](https://github.com/cityofaustin/atd-data-tech/issues/6717#issuecomment-883622552). 

- [ ] Reorder _Assign Case Reviewers_ to:
- Assigned Reviewer Area
- Lead Reviewer form
- Case Reviewer - check boxes

- [ ] TIA Case Status Workflow workflow diagram: Add color legend

**Comment by ChrispinP** [comment]
@amenity should we close this for now?

**Comment by TracyLinder** [comment]
Old/closing
