### ISSUE TITLE
[Enhancement] Project Summary Redesign

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6808]
Implement design refinements and accommodate additional project information on the "Summary" tab. 

### Original
![Original Project Page – 2.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/36a1f767-2e13-420f-8f94-992a3c80dc69)

### New
![New Summary Page – 3 0 – 1](https://user-images.githubusercontent.com/1463708/135401327-ee17025c-cd65-4db4-b728-32f3b7cd39ee.png)
![New Summary Page – 3 0 – Cancel project](https://user-images.githubusercontent.com/1463708/135401330-861a022d-0d4a-4192-9335-24f0807b702e.png)

**Comment by patrickm02L** [comment]
Original
![Original Project Page – 2.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/36a1f767-2e13-420f-8f94-992a3c80dc69)

With all the fields completed
![New Summary Page – 2.0.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/97d90944-7f08-4e6f-a4ec-fdf235d286c7)

With editing capabilities on
![New Summary Page – 2.1.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/f74e50ff-332c-4911-9286-867644f7d2f5)

With Dropdown menus
![New Summary Page – 2.2.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/28688022-468b-4e4a-b40e-481084777502)

**Comment by amenity** [comment]
Discussed with @patrickm02L and our preference is for the pencil to appear on editable fields on hover — the same way it's implemented in the title now. 

https://user-images.githubusercontent.com/1463708/131894661-08af1cad-2146-436c-8792-795ebc078303.mov

**Comment by amenity** [comment]
Latest: 
<img width="957" alt="Screen Shot 2021-09-06 at 5 24 43 PM" src="https://user-images.githubusercontent.com/1463708/132263613-8d8a0435-3657-4b45-b976-3e842ac084e9.png">
