### ISSUE TITLE
Update enforcement activities records

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#682]
The dropdown for violation types types should only include activities that VZA/ATD is interested in tracking. The existing numbering and order is a relic of the old system and can be abandoned. New activities should be:
- Bus-only Lane 
- Don’t Block the Box
- Driver Inattention – electronic device use while driving
- Driver’s License – expired/invalid
- Driver’s License – no license*
- Expired Registration*
- Failure to Maintain Financial Responsibility*
- Failure to Stop – Pedestrian Hybrid Beacon
- Failure to Stop – red light
- Failure to Stop – stop sign
- Failure to Yield – to another car
- Failure to Yield – to a pedestrian/bicyclist/mobility device
- Miscellaneous Violation – hazard
- Miscellaneous Violation – non-hazard
- No Seatbelt – driver
- No Seatbelt - passenger
- Speeding – school zone
- Speeding – non-school zone
- Stopped School Bus
- (No violation observed in 15-minute period)

*@SurbhiBakshi - I think you might also need to get the citation fees for these ones since they're not already in the system?

**Comment by SurbhiBakshi** [comment]
thanks @amenity for this list. Will ask LLewis for the fees. Also need to know if this list will be used to provide the focus for each assignment.
