### ISSUE TITLE
Create How-To GitBook Document for Pro

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#6829]
Create How-To document to help users get going in Pro:
- Opening Pro
- Creating database/folder connections
- Working in the Map View
- Importing Layouts and working with them

**Comment by johnclary** [comment]
@jaime-mckeown do you still need this issue?

**Comment by jaime-mckeown** [comment]
@johnclary This Issue must have gotten lost when I created it. I will add my notes and close it.

**Comment by jaime-mckeown** [comment]
Created Pro Help Document in GitBook for department GIS Users:
https://atd-dts.gitbook.io/atd-geospatial/arcgis-pro/working-in-arcgis-pro
