### ISSUE TITLE
Housekeeping: GitHub Misc. related to Service Delivery

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#684]

**Comment by amenity** [comment]
@TracyLinder - what is this issue for?

**Comment by TracyLinder** [comment]
@amenity the only thing I remember is sitting in QP, and you said you needed to do some GitHub cleaning before roll-out, and to make an issue for you.

**Comment by amenity** [comment]
@TracyLinder - 😆well then. I would say this is covered by #880 .
