### ISSUE TITLE
Fee Logic Updates to TURP & EX (On PROD 🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6844]
# This single issue covers the development for removing old fee logic and implementing new fee logic on the RW-TURP & EX permits. 

### Remove the following functionality:
- [ ] The current fee insertion and work type selection triggers for RW-TURP folders need to be removed as they are all going to change (#4469, #6322) . Provided below are some places where these triggers have been identified. Make sure Extension Fee inserts based on Property & Street Information irrespective of the WorkType: PVT Long Term

- [ ] Info field Event Start Date (75980) and Event End Date (75985) determine appropriate work type for the folder. This functionality needs to be removed.
- [ ] Any functionality based on Info field Project Sponsor (76765) needs to be removed.

### Create new fee logic for the fees provided below:

- [ ] **TURP New Permit Fee**

- Applies only when sub type is NOT 'Franchised Utility -Gas Utility', 'Franchised Utility - Other Electric Utility', 'Franchised Utility - Telecommunication/Cable Utility'.
- This fee needs to be added when a new application is created either from portal or back office
- Fee needs to be added only if folder Info 'Emergency' (#6641) is answered 'No'.
-Applicant must pay this fee before folder status updates to Internet Pending

- [ ] **TURP Extension Permit Fee**

- Currently the system inserts TURP ROW fees for extensions when attempt 'Extension Granted' is made in Permit Extension Process (50680).
- System needs to insert the TURP Permit Extension Fee at this trigger along with other fees.
- Applies only when work type is NOT 'Franchised Utility -Gas Utility', 'Franchised Utility - Other Electric Utility', 'Franchised Utility - Telecommunication/Cable Utility'.

----
### Remove the following functionality:
_The following fee procedures and logic need to be removed for the EX fees:_

- [ ] The Excavation/Concrete Permit fee - Transport (50348) is inserted when application is created through Portal. This fee insertion needs to be removed.

### Create new fee logic for the fees provided below:

- [ ] **Excavation Permit Fee - New**
- Applies only when worktype is NOT 'Franchised Utility -Gas Utility', 'Franchised Utility - Other Electric Utility', 'Franchised Utility - Telecommunication/Cable Utility'.
- This fee needs to be added when a new application is created either from portal or back office.
- This fee should be added only if Info field 'Emergency' (#6641) and Info field 'Secondary' (#6321) are answered 'No'
- Applicant must pay this fee before folder status updates to Internet Pending.

- [ ] **Excavation Application Fee - Secondary - $95**
- Applies only when work type is NOT 'Franchised Utility -Gas Utility', Franchised Utility - Other Electric Utility', Franchised Utility - Telecommunication/Cable Utility'.
- Fee needs to be added only if folder Info 'Secondary' (#6321) is answered 'Yes' and Folder Info 'Emergency' is answered 'No'.
- This fee needs to be added when a new application is created either from portal or back office
- Applicant must pay this fee before folder status updates to Internet Pending

- [ ] **Excavation Application Fee - Extension - $175**
- This fee should be inserted manually when user navigates to fee tab and clicks Add->Insert.
- The manually inserted fee should be inserted with the fee amount of $175.
- Applies only when subtype is NOT 'Franchised Utility -Gas Utility', 'Franchised Utility - Other Electric Utility', 'Franchised Utility - Telecommunication/Cable Utility'.

----

![image](https://user-images.githubusercontent.com/49930868/127917884-442085a5-984c-43f6-806c-24fa3cea3f77.png)

**Comment by TracyLinder** [comment]
This is ready for development.
FYI @Nadin-Nader @vschandramouli @Sreelatha-BlazeKannan

**Comment by TracyLinder** [comment]
**AC Update:**

_This was removed:_

- [ ] **TURP Secondary Permit Fee**

- Applies only when work type is NOT 'Franchised Utility -Gas Utility', Franchised Utility - Other Electric Utility', Franchised Utility - Telecommunication/Cable Utility'.
- Fee needs to be added only if folder Info 'Secondary' (#6321) is answered 'Yes' and Folder Info 'Emergency' is answered 'No'.
- When Folder Info 'Secondary' is answered 'Yes' and Folder Info 'Emergency' is answered 'Yes', System should insert TURP Emergency Permit Fee ONLY.
- This fee needs to be added when a new application is created either from portal or back office
- Applicant must pay this fee before folder status updates to Internet Pending

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to CTM to deploy to DEV under **SCTASK0163113** (lookup 50200)

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy to DEV. Under **SCTASK0163113**

**Comment by Sreelatha-BlazeKannan** [comment]
** Status 
@Nadin-Nader , @TracyLinder - Completed Development for RW-TURP and working on for EX

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder DEV deployment has been completed.
@Sreelatha-BlazeKannan please UAT on DEV

**Comment by Nadin-Nader** [comment]
**Status:**
Sree is currently testing this

**Comment by Nadin-Nader** [comment]
Added to AC:

Make sure Extension Fee inserts based on Property & Street Information irrespective of the WorkType: PVT Long Term

**Comment by TracyLinder** [comment]
Currently blocked by #6842 commit.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Please find attached Demo for EX folder for your reference. All AC working as expected. if you have any questions please do let me know. 

https://user-images.githubusercontent.com/44907715/133338881-5e03bcc6-d9cb-4f96-9ebb-768db1bc2023.mp4

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - AC Update according to Kim and Paloma

Franchised utility No Extension fee and No row-usage fee must be added

City Departments and will have extension fee but not Row-usage fee

Private Development will have Extension fee and row usage fee

I will work on the changes and update the card.

**Comment by TracyLinder** [comment]
<img width="518" alt="Screen Shot 2021-09-20 at 10 12 00 AM" src="https://user-images.githubusercontent.com/49930868/134026969-77b68fb8-185e-42cb-bbb0-e8e9ce6d6c61.png">

<img width="513" alt="Screen Shot 2021-09-20 at 10 11 54 AM" src="https://user-images.githubusercontent.com/49930868/134026991-cd738cc0-ef71-46c8-8a79-4be7030a178e.png">

**Comment by TracyLinder** [comment]
### Update - Emergency Permit Fees

The emergency permit fees for both EX & TURP have been removed by stakeholders. Sree will comment out the code in case we decide to use it in the future. Currently this work is in local.

**Comment by TracyLinder** [comment]
<img width="838" alt="Screen Shot 2021-09-20 at 5 03 44 PM" src="https://user-images.githubusercontent.com/49930868/134082065-c657ad78-52c2-4dcc-be7e-88d745328a53.png">


<img width="847" alt="Screen Shot 2021-09-20 at 5 02 55 PM" src="https://user-images.githubusercontent.com/49930868/134082077-73458032-05b2-4324-badf-370f389645c6.png">

**Comment by TracyLinder** [comment]
@vschandramouli FYI - the emergency permit fees were not approved & are being removed,.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan & @Nadin-Nader do you know when we will be ready for UAT on this one?

**Comment by TracyLinder** [comment]
### Update

**Sree will:**

- [ ] Today send EX deployment plan 
- [ ] Tomorrow send RW deployment plan 


**Tracy will:**
- [ ] @TracyLinder needs to confirm if only pvt development should have the tech surcharge. What scenarios are we not assessing the surcharge? 
- [ ] @TracyLinder should the secondary application fee on the EX folder have the tech surcharge? Currently w/ Sree's updates, the secondary fee for EX will insert & bill by system automatically.

**Comment by TracyLinder** [comment]
**Feedback from Kim:**

1. ATD Tech Surcharge only applies to private development permits
2. The secondary permit fee on EX should **not** have a surcharge. 
3. There is no secondary fee on RW


FYI @Sreelatha-BlazeKannan

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I have updated the changes as per above feedback; Submitted DEV Deployment plan for EX-FEE UPDATES ONLY.  Please create task id for the commit id: c407e2de383c. And working on the RW changes

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have sent this over to the DevOps CM Team to deploy to **_DEV_** under **SCTASK0168582**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy to **_DEV_** under **SCTASK0168582**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - EX Changes are moved to DEV and I tested the same. All looks good. Please UAT The same to move to TEST

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted DEV Deployment plan for RW Changes  and informed George to make the move asap. Here is the commit ID: 2fb16c5c2e95 for your reference. Kindly create task id for the same.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have sent the RW changes in commit **2fb16c5c2e95** to the DevOps CM Team to deploy to DEV under **SCTASK0169045**

**Comment by Nadin-Nader** [comment]
**Status:**
EX changes are in DEV ready for UAT to move to TEST
RW changes have been sent to DevOps CM Team to deploy them to DEV under **SCTASK0169045**

**Comment by TracyLinder** [comment]
### Update

Please promote to TEST so UAT can continue.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I tested both RW & EX changes and all working as expected. Submitted TEST DP plans and here is the order to promote the changes to TEST. Please ask George to promote the changes as he did the DEV promotion.

** Order to Promote the changes from DEV to TEST **

1. 259c194a7 – It is already in TEST
2. 884bded88b96 (validlookup) – Promoted by George (c0a93748cf4d9e147208b97b394e667eee9118c8)
3. c407e2de383c – (EX Updates) – Promoted by George
4. 2fb16c5c2e95 – (RW Updates) - Promoted by George (70fe8cd2a7c009bfefb636001e19aa229dc6998d)

**Comment by Nadin-Nader** [comment]
**Status:** 
George is currently deploying this to TEST under **_SCTASK0169134_**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan George has informed me that this is ready for UAT on **_TEST_**. Please test before our meeting or we can try to test at our meeting.

**Comment by Nadin-Nader** [comment]
**Status:**
Ready for UAT on **_TEST_**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I have tested in TEST Environment both EX & RW-TURP, all working as expected.

**Comment by TracyLinder** [comment]
### Update / Blocker

During testing i encountered system errors related to issue #1802 . I've asked Nate & Subha to roll back 1802 ASAP.

**Comment by TracyLinder** [comment]
Note to Us: We're going to need to think of a better way to keep track of the bugs that need to be fixed before we go to PROD.

**Comment by TracyLinder** [comment]
### UAT ISSUE 2
_Reported by me (Tracy)_
- [ ] Done/Resolved

**ATD Tech Surcharge did not insert on RSN 12666674 with the TURP extension fees.**
I saved 'Approved' attempt on TURP Review (50520) and the system:
✔️ Inserted TURP Permit Fee - Extension
✔️ TURP ROW Usage Fee
❌ FAILED to insert ATD Tech Surcharge
❓The system did **not** bill the fees. I'm not sure if that's correct yet.

**Comment by TracyLinder** [comment]
![fee logic bug.jpg](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/2d1f8e5b-a901-461d-be07-b1513249eff1)

**Comment by TracyLinder** [comment]
**TURP Test Plan is Ready**
[Here](https://docs.google.com/spreadsheets/d/1ofPM3O2g2Cv_OsfmycmuvpGMdsfQm6fXhFIcE9Ft3_A/edit?usp=sharing)

**Comment by TracyLinder** [comment]
### UAT ISSUE 4
_Reported by Tracy_
- [ ] Done/Resolved


When I saved the Approved attempt on process (50520) TURP Review, the system ❌ **didn't** ❌ insert a ROW usage fee (it should have). Nothing happened when I tried to add the TURP ROW Usage Fee from Insert + Run.
- Test TURP RSN 12666674
- TURP ROW Usage Fee & ATD Tech Surcharge should have inserted with the attempt because the work-type is Private Development.

**Comment by TracyLinder** [comment]
### UAT ISSUE 5
_Reported by Kim_
- [ ] Done/Resolved

Per Kim, on TURP, when Emergency info is Yes, no fee should be inserted. She's going to talk to Paloma or Ryan to confirm we need to make changes and she'll get back to us.

**Comment by TracyLinder** [comment]
### UAT ISSUE 6
_Reported by Kim_

**TURP ROW Usage Fees are not updated**
In all tiers the following fees were not correct:
- Sidewalk Space Extension
- Alley extension
- Additional traffic lane extension

**Comment by TracyLinder** [comment]
### UAT ISSUE 7
_Reported by Kim_
- [ ] Done/Resolved

**On expired TURP permits, when 'extension granted' saved and the extension fees are paid, the system is not updating the folder status to Active.**
- This may have something to do w/ the folder info Activate Upon Payment. We're not sure about that yet. 
- TEST case: 21-039267 

**The TURP extension workflow is not updating the folder expiration date w/ the new extension end date.**
- Test case: ?

**Comment by TracyLinder** [comment]
### TURP UAT is complete. Ready for Bug fixes.

**Comment by TracyLinder** [comment]
### UAT ISSUE 7
_Reported by Tracy_

During portal application for EX - Project Connect, on the Property & Street Info page, the system is showing fields for the TURP folder. 
- Only happening on Project Connect subtype (so far)
- See screenshot; all the fields in the red box need to be removed.
- ----



<img width="640" alt="Screen Shot 2021-09-29 at 7 39 28 PM" src="https://user-images.githubusercontent.com/49930868/135367330-c9db8aa8-645e-4d06-9c56-07b0558566c9.png">

**Comment by TracyLinder** [comment]
### UAT ISSUE 8
_Reported by Tracy_
- [ ] Done/Resolved

**Can't issue Franchised Utility permit; system requires me to insert a Right-of-Way Contractor people record. (This may _not_ be a bug.)**

Questions:
1. Is this how it's working on PROD, or is this a bug? 
----



![Franchised Issue Error.jpg](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/b77b7845-8dfa-484c-926c-85bdddbb08fa)

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder @Sreelatha-BlazeKannan  SCTASK0170364 - submitted to for DEV promotion of Issue 7.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan the new changes have been sent to DevOps CM Team to deploy to DEV under **SCTASK0170433**
Once UATd we will send to TEST and approve for PROD

**Comment by Nadin-Nader** [comment]
**Status:**
Sent to DEVOPS to be deployed to **_DEV_** under **SCTASK0170433**

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  
Summary for Bug -7:
First commit is in TEST. Two more fields had to be removed so did another commit. And  SCTASK0170435 is submitted for DEV & TEST deployment of the 2nd commit. Once its in TEST, I can test it.

**Comment by Nadin-Nader** [comment]
2 out of the 4 commits had EX changes. We decided to revert any EX changes and proceed with the rest to go to PROD under **SCTASK0170454**

**Comment by TracyLinder** [comment]
# Update / Critical Bugs
### There may be service interruptions with TURP & EX permits. The full impact is unclear as of 9pm


**Two bugs/failures have been identified on the EX folder; both are critical:** 
_TEST#: 2021-047486 EX_
1. The system fails to insert the  Right-of-Way Contractor record on the folder.people tab. 
2. The system fails to create an EX folder for each street submitted by the applicant. Only one folder is being created for all streets.
----

### We are launching tonight, with major issues.

Here's what we did: 
1. Rolled back both commits on 6844 - 2 (EX) _(c407e2de383c & c0a93748cf4d9e147208b97b394e667eee9118c8)_
2. Promoted the other commits to PROD. 
----

### Moving Forward
1. Tracy will smoke test EX & TURP tonight; I'm just not sure if the promotes are done yet.
2. We sync with the project team tomorrow am to assess the situation and identify solutions.

**Comment by Nadin-Nader** [comment]
**Status:**
This has fixes that went to PROD on 10/1 under #7325

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on 7327 to go to PROD in order to close

**Comment by Nadin-Nader** [comment]
Closing as 7327 is closed and i have not heard any more issues with the fee logic.
