### ISSUE TITLE
Implement ability to toggle and edit components from full page map

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6845]
Essentially get rid of the standalone components view and show all components in the full map view.

**Comment by patrickm02L** [comment]
Add Components Menu allows for users to add new layers to the map. The menu would expand to a fixed shape on the map, and adopt a scrolling action if new layers exceeded the space allowed. 

![Web 1920 – Layers – 1.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/fdc80801-b8a2-4f1d-b8ad-9ad2e5d0a058)

**Comment by patrickm02L** [comment]
@patrickm02L Updates to drawing
- radio buttons
- edit pencil
- move search to the right

**Comment by patrickm02L** [comment]
New components menu with layers update. The pencil looked heavy, so I opted for an arrow. When you hover over it it gains a light grey background to indicate it's clickable.

![Web 1920 – Layers – 2.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/73fa3db4-e1db-4886-85d0-9512eaa19902)

Clicking on the 'Add New Component' button or the arrow will lead take you to the editing state. Once you 'save', 'cancel', or 'delete' your taken back to the new components menu.

![Web 1920 – Layers – 3.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/c74e34e4-4aa7-4939-8e32-ebca29c4bd61)

**Comment by patrickm02L** [comment]
@amenity please take a look at the updates.

**Comment by amenity** [comment]
Oooooh nice, @patrickm02L! This looks really clean. I think we want to remove the edit-y icons in the upper right when it's in the "listing" view?

**Comment by patrickm02L** [comment]
@amenity, updated the image. The edit tools are gone.

**Comment by sergiogcx** [comment]
@amenity @patrickm02L we need to determine what we want the map to look like when there aren't any components available to show. The map is programmed to crash whenever there aren't any components.

![2021-08-05_13-57-58.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/856b98f2-75da-4062-a07c-c45369f42d0e)

**Comment by sergiogcx** [comment]
@amenity @patrickm02L there is a PR:
https://github.com/cityofaustin/atd-moped/pull/387

**Comment by patrickm02L** [comment]
@sergiogcx I would keep it as the current default image that reads no map available, and allows the user to click on the button to create a new map. I don't like the idea of having an empty map because that might make users think they've added a component when they haven't.
