### ISSUE TITLE
Update SSO Documentation

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#6848]
Will need to update SSO documentation so it more accurately reflects updated login security for all apps and the process by which to update certs, test them, and for creating new apps.

**General Steps**
Generate New Certs
Add New Certs to Knack during meeting with CTM
Test SSO, if you get a Public Key error, CTM will need to recreate App Instance in Azure
Remove IP Cert and provide CTM the updated metadata file/link
Once the new App Instance is created, CTM will provide a metadata file/link with the x509 Cert
Verify that the x509 Cert and the IP Cert in Azure match
Format the x509 Cert with headers and add to Knack
Test SSO

**Comment by ChrispinP** [comment]
Completed the update for [SSO documentation]( https://atd-dts.gitbook.io/atd-knack-operations/knack/single-sign-on)

**Comment by amenity** [comment]
@dianamartin - please review

**Comment by dianamartin** [comment]
@ChrispinP Great documentation! @johnclary Take a peep, lots of good information in a different arrangement.

**Comment by johnclary** [comment]
really nice @ChrispinP! i have no further changes. thanks for putting this together!

**Comment by ChrispinP** [comment]
no further changes at this time, closing as complete
