### ISSUE TITLE
[Bug] The bot is mislabeling Transportation Engineering service requests

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6849]
DTS Portal requests from TED are being labeled `Workgroup: TE` instead of `Workgroup: TED`.  

Example, after correct label was added: https://github.com/cityofaustin/atd-data-tech/issues/6839
![Screen Shot 2021-08-02 at 7 13 36 PM](https://user-images.githubusercontent.com/1463708/127938791-83bfb3f5-46b9-4b27-aa47-fe4e997878a6.png)

We can either 
- adjust the script
- Update the new `Workgroup: TE` label color and description and relabel all the existing [`Workgroup: TED` issues](https://github.com/cityofaustin/atd-data-tech/issues?q=label%3A%22Workgroup%3A+TED%22+) with it.

**Comment by amenity** [comment]
@johnclary - do we want to go with "TE" now instead of "TED"?

**Comment by johnclary** [comment]
@amenity this is fixed and deploying. You can test it in 30 minutes.

**Comment by amenity** [comment]
Works #6917 !
