### ISSUE TITLE
Look into link/DTS # within email

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#686]
Customer should be able to easily get to the Github issue for status updates from the confirmation email they receive.

**Comment by johnclary** [comment]
@amenity @dianamartin i think we implemented this. can y'all confirm?

**Comment by dianamartin** [comment]
@johnclary @amenity I found an email from a user who forwarded his GitHub auto reply email and it does show a link to a GitHub issue

![image](https://user-images.githubusercontent.com/21112975/82506006-4e879f80-9ac4-11ea-9644-1874e328926c.png)

**Comment by amenity** [comment]
IIRC, we heard a report that this wasn't working but weren't able to reproduce. Seems like we're good.

**Comment by dianamartin** [comment]
FYI: I tested the link in the email that was forwarded to me by Allen and the link worked and went to this GitHub issue.
