### ISSUE TITLE
GIMOB Meeting - August

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#6861]
Attend GIMOB Meeting

**Comment by jaime-mckeown** [comment]
-  AGOL Backup Manager: selected Backup Manager for backing up AGOL. GIS SPOCs from each department can get access to the tool for backing up content with. Documentation has been created for the application, attached to the card in the Planner Board
- ArcGIS for Teams: official documentation is available, integrates AGOL with Teams. Links available in the card in the Planner Board
- SDE External to SDE: GISDMDev date for move is 9/1. Michael sent out an email regarding this change, I already forwarded to John, Mateo, Sergio, and Frank.
- Voting for New Primary and Secondary SPOCs for Austin Code, approved
- Voting for new Secondary for Public Works, approved
- Reestablished UAV Drone Subcommittee: will be re-activating, looks like PW will lead (Istvan and Bryan)
- New GIMOB Documents Subcommittee: looking for interested members
- GIS Modernization Project
![image](https://user-images.githubusercontent.com/48842809/128377562-474df585-b7f3-4461-a6be-51b9771b6b19.png)

**Comment by johnclary** [comment]
thanks @jaime-mckeown !
