### ISSUE TITLE
Update Badging Documentation

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6864]
Diana M
DTS 

Update Documentation for JJM, get Lauren and Jen's approval then send to JJM. 
- Describe Clearance Groups and the employee personas in them

- [x] Executive Team member list to give CAM RD access

**Comment by johnclary** [comment]
@dianamartin get the executive list so you can finish this up

**Comment by dianamartin** [comment]
Emailed Nathan (HR)
>JJM asked if I could add the Executive team that needed access to Cameron Rd into the badging system. Do you happen to have a list of folks that need that kind of access? I’m also not sure if it’s the whole team or a subset of people.

**Comment by dianamartin** [comment]
Emailed David to ask BSD for badge IDs
>Hi David, 

I was trying to add the executive team to the badging system when I realized that we don’t have all of them in there at the moment. We’ll have to request their badge IDs from BSD. 

The folks we need badge IDs for are these seven:
1.	Jason JM
2.	Anna M
3.	Karla T
4.	Peggy M
5.	Gilda P
6.	Lewis L
7.	Upal B
And can you forward me an example of a normal BSD request you’ve sent this year for anyone at Cameron Road? I’ll be using it as a referenced to the Cameron Road Badge Access Request Form.

**Comment by dianamartin** [comment]
David was able to get me badge IDs for most of the executives. Couldn't add: 
-  Karla T
-  Peggy M
-  Gilda P

they apparently have old badges and would need to get them physically added to the system.

**Comment by dianamartin** [comment]
@moorerst FYI, see above comment.

**Comment by johnclary** [comment]
thanks @dianamartin !! yay
