### ISSUE TITLE
Develop Asset Dashboard in PowerBI

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#6865]
Reference epic #6804

**Comment by dianamartin** [comment]
- Created PowerBI dashboard called "AMD Asset Dashboard" in the network drive `ATD>ATD_GIS>Business_Intelligence_BI_Dashboards>AMD Asset Dashboard`
- So far configured the "Detection" page that referenced the `Detection` PowerBI Dashboard MMC had already created
  - got a chance to see how they built it

**Comment by dianamartin** [comment]
Met with stakeholders: Brian VDW, Lance and Allyson, Chrispin
@john - They (MMC) requested publishing `detector log` to Socrata
- They need the detector events to create the dashboard to help Brian's maintenance reporting

They will work on getting the data from Brian C. (BBS & CCTV). Will keep Brian VDW in the loop.

**Comment by dianamartin** [comment]
Added `signal detection status log` dataset to the OpenData portal like Allyson and Lance requested. Emailed them this morning.

**Comment by dianamartin** [comment]
# Status Update - MMC created dashboard
## AMD Device Status Overview
PowerBI created by Kimley Horn

### Pages
- Overview
- Signals
- Detector Status
- Detector History
- DMS
- CCTV
- BBS
- MMU
- WOs

**Frequency:** Daily, every hour

Sources: KITS, DataTracker via Socrata, spreadsheets (in the future have spreadsheets to DataTracker)

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/fdbf3007-3387-43c8-8035-71f4679f7318)

**Comment by johnclary** [comment]
wow—looks really good!

**Comment by dianamartin** [comment]
Synced up with Lance - 2/1
AMD Device Comm Status
Only missing is the work order stuff. 

![image](https://user-images.githubusercontent.com/21112975/152057653-3568a6c2-314e-481e-9151-c26a781b7570.png)
