### ISSUE TITLE
[Bug] ~6.5K crashes have the TXDOT CRIS login page stored in lieu of the CR3 PDF

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#6866]
Upon report that a handful of crashes had been found that did not have valid CR3 files stored, I have observed that:

1) These crashes contain metadata in the VZDB that there is a PDF stored correctly in S3, which prevents us from finding them via SQL query
2) They have the CRIS TxDOT login page stored in S3 as the "CR3"
3) They have had a valid PDF in the past, as the narrative has been OCR'd and the diagram extracted
4) This valid PDF can be found in the file version history in S3
5) All of the crashes which I have hand inspected in S3 had the last change to the file on disk occur on July 1

Please see [this gist](https://gist.github.com/frankhereford/6a73084997629e6bf583d49cf05b6f6b) for a script which I used to filter down the output of the AWS S3 CLI, like this.

```$ docker run --rm -it -v ~/.aws:/root/.aws -v `pwd`:/mnt amazon/aws-cli s3 ls s3://atd-vision-zero-editor/production/cris-cr3-files/ | ./find_small_cr3s.pl | vim -```

Here's a query you can use to inspect crashes and their change history _in the database_:

```
select c.crash_id, l.update_timestamp update_time_from_audit_log,
--c.cr3_file_metadata as current_cr3_file_metadata,
c.cr3_file_metadata->>'file_size' as current_cr3_file_metadata_file_size,
(l.record_json->>'cr3_file_metadata')::json->>'file_size' as this_value_should_change_on_file_update,
l.record_json->>'cr3_file_metadata' as update_log_cr3_file_metadata
from atd_txdot_crashes c
left join atd_txdot_change_log l on (l.record_crash_id = c.crash_id) 
where c.crash_id = 18190547
and l.record_type = 'crashes'
order by l.update_timestamp desc
```

I see at least two routes forward:

1. Easy but inelegant: Use this script to either build a mega-sized SQL query (where crash_id in (monster_array_of_crash_IDs)) or directly connect to the production database and set these crashes to a state where the ETL process will try to redownload the file, or
1. Difficult but better: Write a short program to inspect the version history of the files in S3 and find the most recent one that the file program validates as a legit PDF and restore it. At the same time, this program would need to restore the cr3_file_metadata object in the database to contain accurate data.

Thanks!

**Comment by patrickm02L** [comment]
Adding button to VZE to clear the downloads could be a one off solution to unblock Xavier for now.

**Comment by sergiogcx** [comment]
I am just wondering if this issue really needs work that urgently, but if we do I've been pondering about this a little bit and these are some ideas and questions I have:

- Doesn't Xavier have credentials already to download PDFs from CRIS or Brazos if he can't find them on VZE? If not, why not give him our credentials, so that way Xavier is never blocked.

- Scanning the database sounds great, but I am not so convinced that it will be a short script. After all, we will need to query the database for metadata on files that may need attention, and then we will also need to update that metadata. We also need to find a way to keep track of PDFs are are just not available anywhere. And lastly, even if we run a full scan of the S3 bucket every day, we sill have to wait 24 hours if a PDF is missing.

**Comment by patrickm02L** [comment]
After discussion with Frank, Sergio, and Mateo we've agreed to move forward with option 2. Frank you have the thumbs up to move forward.

**Comment by patrickm02L** [comment]
After consulting with the team in Dev Sprint Planning, it was determined that the script can be deployed and will not be affected by the Backups. 

@frankhereford please move to closed once the script is live.

**Comment by frankhereford** [comment]
The CR3 restoration script was executed this afternoon successfully in just under two hours. I monitored the process and tested many crashes throughout, all with expected results. Thanks to everyone who contributed to getting this issue squared away.
