### ISSUE TITLE
New Payment Type: Cost of Service

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6867]
### As part of our Cost of Service workflow, we intend to pay ROW permit invoices with a payment type of 'Cost of Service'.
This new payment type is needed because ATD will be paying the invoice **before** we receive funds from our partner departments. For this reason we cannot use payment type 'JV', because we all know JV to mean that the monies were transferred prior to the invoice being paid. 

**Stakeholder: Tracy**

**Acceptance Criteria:**
- TBD. I'm not sure what we need to do other than create the new payment type. 
- A new valid payment type is created. Description '**Cost of Service**'
- Everything else about the valid payment type should be identical to the 'JV' payment type.
    - Do not include the help text Subha found in the code.  
- Goes on backoffice only; not on portal
- Applies to folders:
EX
RW
UC
DS
GF
SCP

**Comment by TracyLinder** [comment]
### AOB VOTE
- Approval by vote during AOB on 8/12/21

**Comment by TracyLinder** [comment]
**Update**
I think Subha is a good Dev for this. Nate is going to ask George with CTM if he has any feedback about creating a new payment type. 
The AC isn't great, but I'm not sure what else to say.

**Comment by TracyLinder** [comment]
Goes on folders:
EX
RW
UC
DS
GF
SCP

**Comment by SubhaShroff** [comment]
@Nadin-Nader 

1. A commit is done - 0225935147d89308c74ba5af2ca91184ace42069, waiting Martin to have a look at it, as recently we are having complications in commits.
2. I checked the given Report for 'Print Receipt'. The query in the report looks good with no hard coding. So when this ticket is deployed in later instances, there should not be any issues with Print Receipt.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  DEV Deployment request for commit(0225935147d8) is submitted - **SCTASK0163377**.

**Comment by TracyLinder** [comment]
### Approved to promote to TEST

**Comment by SubhaShroff** [comment]
Following are the tested permits on DEV. Checked the Print Receipt, Print Bill buttons for the respective reports to display. All look good.
EX - 11902190
RW - 11902976
DS - 11901810
UC - 11902138
GF - 11902045
SCP - 11901353

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0163735 is submitted for TEST Deployment.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been promoted to TEST. Please UAT on your end then let me know if we can UAT with the stakeholders

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Its tested on TEST for all 6 permits and checked the Bill & Receipts also. All looking good. Up for UAT.

**Comment by Nadin-Nader** [comment]
@SubhaShroff i will send an email for the Stakeholders to test this on TEST

**Comment by Nadin-Nader** [comment]
Email sent to Stakeholders for UAT on TEST:

> Hi everyone,
> 
> Hope you are all doing well and staying safe. I wanted to reach out to let you know that the new Payment type: Cost of Service is on TEST and ready for you to UAT and approve. Please go ahead and test this on TEST and let me know the outcome. Thank you for your time.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services

**Comment by SubhaShroff** [comment]
### Status:
Email sent to stakeholder by Nadin to test this on TEST

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder Per Paloma's email, all looks ad functions well and has approved the move to PROD.

## **Approved for PROD Deployment🙌🎉‼**

**Comment by SubhaShroff** [comment]
Thank you @Nadin-Nader. SCTASK0166681 is submitted to do PROD Deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  PROD Deployment is done.

**Comment by Nadin-Nader** [comment]
email to stakeholders:

> Hi Team,
> 
> Hope everyone is doing well. I wanted to let you know that the request for the New Payment Type: Cost Of Service #6867 is on PROD. I will go ahead and close the request as mentioned in our Friday meeting. If any issues should arise, please feel free to reach out to us.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services

Closing card
