### ISSUE TITLE
New Info: Sub-Project ID #

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6868]
### Partner departments have asked for the ability to report on their own data, specifically the sub-project ID number. 
- _Request came from CPO_
- _Request is related to FY22 Fee Updates, specifically Cost of Service, however I (Tracy) am not including it in the FY22 fee project. It will be worked in the backlog after fee updates are implemented._ 

**Stakeholders:** Paloma's Group & Tracy, Maybe Jessica Davis

**Acceptance Criteria:**

1. **New Info Created**
_Note to Sree or Subha: Please check before creating this info to be sure one doesn't already exist._
- Description: Sub-Project ID #
- Type: Allows text and numeric values

2. **Add New Info to RW-TURP, and EX folders**
- Add new info to RW-TURP folder
- Add new info to EX folder
- Not mandatory for setup, or folder issuance
- No validations anywhere

3. **New Info to Portal Applications**
- Add to both TURP & EX
- Not a mandatory field

**Comment by TracyLinder** [comment]
@Nadin-Nader just FYI, i created this, added AC, and put it in the backlog.

**Comment by TracyLinder** [comment]
Subha is picking this up

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  worked on this ticket and a commit is done - **d80522d0274a**. 

![image](https://user-images.githubusercontent.com/51680715/130523294-03041639-0870-4444-8163-7a097823a988.png)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0161752 - is submitted to Deploy the code changes in DEV.

**Comment by SubhaShroff** [comment]
@Nadin-Nader DEV deployment is done. And following are the screen shots of the new info on BO & Portal. Please let  me know, if it looks good and can be promoted to TEST.
EX
![image](https://user-images.githubusercontent.com/51680715/130672131-6a3b469d-5b31-47c3-813e-4f67549818a7.png)

RW-TURP Portal
![image](https://user-images.githubusercontent.com/51680715/130672602-b04375da-a921-42a2-a2b4-fa94f5a61c2e.png)

**Comment by SubhaShroff** [comment]
### Status:
Ready on DEV for Approval to move to TEST.

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on CTM DevOps to deploy to TEST

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Tested this ticket post-deployment in TEST. Meets the AC in both BO & Portal. Ready for UAT.

**Comment by SubhaShroff** [comment]
### Status:
Ready for TEST UAT.

**Comment by Nadin-Nader** [comment]
@Nadin-Nader UAT on TEST

**Comment by Nadin-Nader** [comment]
@SubhaShroff i UATd this and found that this is ready for PROD

**Comment by Nadin-Nader** [comment]
**Status:**
## **Approved for PROD deployment 🙌🎉‼**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0165134 is submitted for PROD deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  PROD Deployment is done. Checked with George.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder  I will send an email to Paloma and Kim stating that this is now on PROD

**Comment by Nadin-Nader** [comment]
Email to Stakeholders:

> Hello Everyone,
> 
> Hope you are doing well. I was reaching out in regards to the New Info: Sub-Project ID # (Zenhub card # 6868). This is now on PROD. I will go ahead and close the card out but if anything should arise, please feel free to email me.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services
> ————————————————————————————

Closing card
