### ISSUE TITLE
TDS Portal: Add Connect Cases Feature to TDR Mod

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6869]
### We built a feature for the TIA Mod that allows users to connect a TIA case to a TDR case. We should add this feature to the TDR Mod, so they can connect a TDR case to a TIA case. 
_That's way too many acronyms._

**Stakeholder:** Sangeeta

<img width="699" alt="Screen Shot 2021-08-04 at 3 10 01 PM" src="https://user-images.githubusercontent.com/49930868/128248095-bee8e439-e76b-4b68-8ebc-66973ad9690a.png">

**Comment by ChrispinP** [comment]
#7714 is now a culmination of this feature for all 3 mods. closing as duplicate
