### ISSUE TITLE
Update Existing TDS Fees & Add Surcharge (Going to PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6870]
### [See FY22 TDS Fee Sheets](https://cityofaustin-my.sharepoint.com/:x:/g/personal/tracy_linder_austintexas_gov/EaEsKiGikgFChsWbGNw5g5QBhuo5oax8loNMn30q_Au_8w?e=6qTbnF)

**Acceptance Criteria:** 
- System should contain updated fee information  as per the spreadsheet linked above. 
- TDS fees should insert with the 4% ATD Tech Surcharge TDS for all fees other than Administrative Conditional Use and Administrative Small Site Plan Review.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this to the DevOps CM Team to deploy to **_DEV_** under **SCTASK0177491**

**Comment by Nadin-Nader** [comment]
**Status:** 
Waiting on the the DevOps CM Team to deploy to **_DEV_** under **SCTASK0177491**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to **DEV** Please UAT when you get back 11/4

**Comment by Nadin-Nader** [comment]
**Status:**
Ready for UAT on **DEV**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Development is in Progress for all fees mentioned in excel for folders SP/ZC/C/C8/TIA.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Development of 35 fee code updates on 35 procedures completed with testing. Working on 24 remaining procedures in Localhost.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP Submitted; Please approve and create task id for me. Here is the commit id's
1.	Commit ID – All (99) Procedures - 960f033b3d51
2.	Commit ID – Lookup table updates - f8804b5b6948

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to deploy to **_DEV_** under **SCTASK0180567**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to **_DEV_** Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Submitted #6870 TEST Deployment plan. Please approve and create task id for me.
Commit ID’s
1.	e3b1e5663f24 – Update Lookupfee
2.	960f033b3d51 n f8804b5b6948 – All procedures

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this over to the DevOps CM Team to be deployed but under 2 different TASKS:

**SCTASK0182178** = e3b1e5663f24

**SCTASK0182179** = 960f033b3d51 & f8804b5b6948

**Comment by Nadin-Nader** [comment]
**Status:**

Waiting on DevOps CM Team to deploy to **_TEST_** under **SCTASK0182178** and **SCTASK0182179**

**Comment by TracyLinder** [comment]
### UAT Scheduled
12/1/21 @ 3:30 w/ Nazlie & Amber H

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder the two tasks have been deployed to **TEST**. This is ready for UAT with Nazlie on 12/1 @ 3:30pm

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Completed TEST UAT and working as expected. Ready for UAT in TEST with Stakeholders.

**Comment by TracyLinder** [comment]
### UAT Passed / Please promote to PROD 🎉

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted PROD DP, please approve and create task id for me. Here is the commit Id's. Please post the order aswell to promote.
Order 1 - e3b1e5663f24
Order 2 - 960f033b3d51 & f8804b5b6948

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this to the DevOps CM Team to deploy to **_PROD_** under **SCTASK0183734**

**Comment by Nadin-Nader** [comment]
**Status:**

Waiting on the DevOps CM Team to deploy to **_PROD_** under **SCTASK0183734**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder This has been deployed to **PROD** I will send an email to Sangeeta and close the card

**Comment by Nadin-Nader** [comment]
Email to Sangeeta:

> Sangeeta,
> 
> Hope you are doing well. I was reaching out to inform you that card 6870 Update TDS Fees and add Surcharge, has been deployed to PROD as per your approval during the TEST UAT. I will now close the card.
> 
> If any issues arise, please feel free to email me or Tracy or send us a Teams Chat.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> Product Delivery Manager
> Data and Technology Services
