### ISSUE TITLE
[Bug] ~824 crashes have $0 comprehensive cost

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#6875]
The comprehensive cost for a crash should never be $0; a crash with no injuries should get the minimum cost amount of $50,000 for a CR3 crash.

**Comment by frankhereford** [comment]
Looking at https://github.com/cityofaustin/atd-vz-data/blob/master/atd-vzd/triggers/atd_txdot_crashes_updates_audit_log.sql#L114-L121, it's clear that the fall through case here isn't the best choice, but it also shouldn't ever be possible to achieve, as line 118 is the case of no injuries. 

I believe that the root cause may be related to crash summations coming from CRIS being set at the time of INSERT on their database and possibly not being recalculated when they UPDATE. If a crash initially doesn't have any records in the persons/primarypersons table, all types of injuries (including the non-injury state) are set to zero and may not be updated if a person is added later in a CR3 revision. This observation is based on conversations with @xavierapostol, and I seek to verify and expand my understanding of this by some row-by-row inspections of raw CRIS data which @sergiogcx has pointed me to on S3. 

Further findings will be reported - thanks!

**Comment by frankhereford** [comment]
The crashes in question are almost entirely those without entries in the `persons` and `primarypersons` tables. They lack entries because the persons sections of the CR3 itself are blank. The database reflects the CR3 data correctly, in my opinion.

A handful of the crashes in question concern fatalities which occurred after the 30 day window post-crash, which is not an injury outcome that has a defined comprehensive cost value.

I propose we ask the VZ stakeholders to define a default, ground-state value for the comprehensive cost of a crash which is not $0 as it is currently. My first suggestion would be the non-injury comprehensive cost, and that's what's used in the PR, but that could be easily and quickly amended.

**Comment by frankhereford** [comment]
The update to the `audit_log` function has been deployed to production and crashes which do not have persons associated to them have had the `est_comp_cost_crash_based` field set to the new ground-state of $50,000.

**Comment by patrickm02L** [comment]
Asked about in the Oct SR - What is the preferred route on the non-ATD fatalities. We don't have a comprehensive cost for that injury outcome.

Lewis L. will take a look at what Frank H. has sent over and give him feedback in the next few days.
