### ISSUE TITLE
Update RPP Digital Petition Form stack template

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6876]
Stockholders have submitted their final language for the RPP Digital Petition.

- [ ] Update the Digital Petition form stack template

**Comment by moorerst** [comment]
@dianamartin looks good, I have a few updates:
This form is **a** community - add the a
Learn more about the... - put on a separate line

**Comment by dianamartin** [comment]
@moorerst I updated it
## Added an "a"
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/94f9cea8-c0a6-4921-bbb0-3b7fa7f3eb7e)

## Learn more on new line - center aligned
![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/07709737-3279-4ff7-9800-915fa74b8e55)

**Comment by moorerst** [comment]
set updated template to stakeholders for review

**Comment by moorerst** [comment]
@dianamartin add this sentence to the guidelines bullet list: **Resident vehicle license plate numbers are collected to determine eligibility based on non-residents/commuter vehicles parked within petition area.**

**Comment by moorerst** [comment]
Final language has been updated and approved by the stakeholders on the Digital Petition template. Closing this issue.
