### ISSUE TITLE
Meeting: Follow up with HR on forms for Knack

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6877]
Agenda:
Issue #6607 Email notifications for on boarding forms
Issue #6608 Reports for on boarding forms
Issue #6773 New form Evaluation Form for ATD Supervisor Course

**Comment by moorerst** [comment]
Per email from Nathan the Secondary Employment form is not a priority can be put in the backlog. However the Course Evaluation form is a high priority for his group. It's on the agenda for discussion.

**Comment by dianamartin** [comment]
# Diana's Notes
## Email Notification
Supervisor Survey - 30, 90, 120
- When should they be updated
- 2 weeks prior notification

Linda - enter hire date
- Hire Date field
- Calculate Hire Date to 30 days out
- Calculate 30 days out
- Calculate 90 days out
- Calculate 120 days out
- Calculate 30 day out - 14
- Calculate 90 day out - 14
- Calculate 120 day out - 14

## HR Form Details -Supervisor Surveys table
- 30, 90, 120
- email nudge notification - auto

## HR Reporting
- Generate a monthly report - 
  - Tracking the managers
  - Responses that need HR attention

## Timeline
- This month (August) or next month (Sept)
- Sept 6th

# Supervisor Training - 8 hr

**Comment by moorerst** [comment]
The Github issues discussed in this follow up meeting have been updated with the details that were discovered. Closing this issue.
