### ISSUE TITLE
Meeting: Dispatch Tracking Sprint Review SR Activity Outcomes

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#6878]
Agenda: 
•	General check in
•	SR Activity clean up task for 311 integration. Need to review the Activity 
        Outcomes for 3 SR types

ATD Booting Complaint
Parking Violation Enforcement
Residential Parking Permit Enforcement

Meeting scheduled for 8/12

**Comment by moorerst** [comment]
Several questions came up during the discussion:

- When the 311 Feedback activity is used with the action **refer to another agency**  is used does anyone at 311 take action?

- When dispatchers save an attachment from the 311 SR and added ti to the Knack attachments the officer cannot enlarge the image. - Shavyvonne and Hillary will test and report back their findings.
- Reviewed the activity outcomes for the 3 SR's . Updated the spreadsheet Diana is working on to mark the outcomes that can be removed.
- Discussed if the New CSR email will still be needed once 311 integration to Knack is done. Their are some staff that find it beneficial others do not because it does not provide enough information. Will revisit this to make a decision.

**Comment by dianamartin** [comment]
@moorerst are we closing this one or keeping it open?

**Comment by moorerst** [comment]
closing
