### ISSUE TITLE
Use screen width dimensions constant

### ISSUE THREAD

**Issue by jgabitto** [cityofaustin/atd-data-tech#6890]
- There's a "magic number" being used to determine if the browser is being viewed in tablet or mobile dimensions. Would be a good idea to move that value into a constants file.

![image](https://user-images.githubusercontent.com/26661521/128718493-e10f96fd-91b3-42c1-97c6-e39249de5433.png)

**Comment by amenity** [comment]
@johnclary @roseeichelmann -is this backlog issue still applicable?

**Comment by johnclary** [comment]
nope—looks like @roseeichelmann [fixed it](https://github.com/cityofaustin/atd-product/blame/cfd55d0da34dcb93a3fdbbe40b143d75acd1326c/components/projectsView/ProjectFilters.js#L64) 😊 

Closing...
