### ISSUE TITLE
Add custom menu to ATD Data Tech wiki

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#69]
<img width="1130" alt="Screen Shot 2019-05-01 at 1 41 41 AM" src="https://user-images.githubusercontent.com/1463708/57007990-65eea480-6bb2-11e9-9e1b-bffe00d9ceff.png">

[Our wiki](https://github.com/cityofaustin/atd-data-tech/wiki) has outgrown its sidebar! I heard there's a cool trick where you can easily collapse things as sub-pages to quickly create a custom sidebar menu... 😏

**Comment by mateoclarke** [comment]
Done. 

![Screen Shot 2019-05-01 at 10.45.55 AM.png](https://images.zenhubusercontent.com/59f0b24ba468affe6df81d8f/76ce24cb-e605-4119-9c46-678351e705be)

Also working on instructions to add as a wiki page on how to do it yourself.

**Comment by mateoclarke** [comment]
@amenity Here's some new docs about the process:

https://github.com/cityofaustin/atd-data-tech/wiki/Github:-Custom-wiki-sidebar

**Comment by dianamartin** [comment]
@mateoclarke Nice wiki! I'll have to try it soon when i have a lot of wiki pages
