### ISSUE TITLE
ATD Maintained Streets - Research to add Attribute Rules to Markings related fields

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#6907]
Need to do further research to see if it's possible to add Attribute Rules that will update the markings fields based on updates on the markings layers.

**Comment by amenity** [comment]
Christina thinks this might be done? 

Christina actually opted to go the _other_ direction and get rid of extraneous fields in ATD Maintained Streets. Christina will let us know whether this can be closed.

**Comment by amenity** [comment]
SMD uses ATD Maintained Streets for longline markings and raised pavement markings (RPMs).
