### ISSUE TITLE
AMANDA New Account: Sydnie F.

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6912]
### New account

- Requested by Amber H. in TDS

**Comment by TracyLinder** [comment]
I sent the NERF to Amber & Sydnie just now.

**Comment by Nadin-Nader** [comment]
Waiting on NURF

**Comment by Nadin-Nader** [comment]
Created the V6 account and set the automation to create PROD. I also sent a TASK to CTM to create the V7 accounts and add Sydnie to the AMANDA Active Directory group under **SCTASK0160415**

**Comment by Nadin-Nader** [comment]
This has been completed
