### ISSUE TITLE
[Spike] Assess historic TIA data sources

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6913]
Review various data sources that relate to historic TIA data
- [AECOM mapped mitigation fee data](https://docs.google.com/spreadsheets/d/1vxuYQV4smEtF6SZhYVIZ4M4-Q6-2Rb94/edit#gid=476125083) 
- Nelson's [spreadsheet of unused TIA mitigation fees](https://docs.google.com/spreadsheets/d/1CE-O-9A-tvAIxPnkG4XyDt511fOKuE2NpUTKr9OlsMQ/edit#gid=4695449) 
- Joann's [historic TIA case spreadsheet](https://cityofaustin.sharepoint.com/:x:/r/sites/ATD/TDS/_layouts/15/Doc.aspx?sourcedoc=%7B4007CA1B-CBA3-45CF-96C1-873177CDD089%7D&file=TIA%20Primary%20List.xlsx&action=default&mobileredirect=true)

Recommend approach to get make all historic cases browsable in the TDS Portal TIA Module.

**Comment by ChrispinP** [comment]
TIA Cases### 

- [ ] To create the unique Knack Record ID, each case **must** be submitted with an application currently, a case import would not generate this. Could build separate application with only 2 pages to streamline for builders & reviewers, or as a builder, if I did want to import, I would have to have a button to generate the records first using the Knack Save Record ID function and then update the records with the import
- [ ]

**Comment by amenity** [comment]
@ChrispinP - check with CTM GIS to see if there's a Global ID we can use as a unique identifier for each case.

**Comment by ChrispinP** [comment]
Case & Submission Templates
[TIA Case Template.csv](https://github.com/cityofaustin/atd-data-tech/files/7130163/TIA.Case.Template.csv)
[TIA Scope Template.csv](https://github.com/cityofaustin/atd-data-tech/files/7130164/TIA.Scope.Template.csv)
[TIA Submission Template.csv](https://github.com/cityofaustin/atd-data-tech/files/7130165/TIA.Submission.Template.csv)

**Comment by ChrispinP** [comment]
spoke with Andrew and confirmed that the mapped datasets do not have a hidden Global ID. Will need to determine how we generate the unique IDs for mitigations and what they will look like.

**Comment by ChrispinP** [comment]
Created a unique generated Mitigation Improvement ID that now allows us to identify mitigation records in Knack.

**Comment by ChrispinP** [comment]
Updated Template Files:
[TIA Historical Template for Stakeholder Central.xlsx](https://github.com/cityofaustin/atd-data-tech/files/7306891/TIA.Historical.Template.for.Stakeholder.Central.xlsx)
[TIA Historical Template for Stakeholder North.xlsx](https://github.com/cityofaustin/atd-data-tech/files/7306893/TIA.Historical.Template.for.Stakeholder.North.xlsx)
[TIA Historical Template for Stakeholder South.xlsx](https://github.com/cityofaustin/atd-data-tech/files/7306895/TIA.Historical.Template.for.Stakeholder.South.xlsx)

**Comment by ChrispinP** [comment]
@TracyLinder We may want create two resulting issues from this, a Geo issue, and a Memo issue, and then we can go ahead and close this.

**Comment by ChrispinP** [comment]
Added Geo prep & followup to Mitigation Import issue. Closing as complete.
