### ISSUE TITLE
Get programmatic access to parking meter transactions (Flowbird - Smartfolio)

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6925]

**Comment by johnclary** [comment]
I have followed-up with Flowbird multiple times and have not received a response. I've cc'd Jason R on my latest email.

**Comment by johnclary** [comment]
i spoke with Cory (CTM) and Everett (Flowbird) this morning. Everett is going to send me additional details about their integration capabilities. Once I review those I will respond, probably with more questions, until we have a clear understanding of our options for protocol/design of the integration.

**Comment by johnclary** [comment]
I still have not received the info that Everett committed to providing. I just sent this email to him, Lionel, Emmanuel, Peggy, and Diana:

> I am following up with you regarding access to the Flowbird data warehouse for ATD and PARD data. I am waiting to receive documentation from you about Flowbird's integration capabilities. 
> 
> We are seeking access to both of the data sources described by the attached dictionaries, and we require the data that is available for both physical meters as well as payments made through Flowbird apps. 
> 
> As I mentioned, we can support a variety of protocols and architectures. We just need to understand your capabilities and preference.
>

**Comment by johnclary** [comment]
I tested the DR-direct tool and was able to extract transactions from 2019-present using the `transaction_history` report. Documentation about the DR direct tool is in 1Passsword. I wrote a basic ETL and will add that code [here](https://github.com/cityofaustin/atd-parking-data).

**Comment by johnclary** [comment]
I asked Darren for login access to Smartfolio for both Charlie and me.

**Comment by johnclary** [comment]
@Charlie-Henry has been investigating the transaction data to identify a common row identifier between the meter transactions and Fiserv transactions. He's going to out to Darren (Flowbird) about this now that we have a better understanding of Fiserv's data (via #7546)

**Comment by Charlie-Henry** [comment]
The sample data from DR-Direct looks like it does not include any cash transactions. These are available within the smartfolio web interface. @johnclary maybe there's a setting to change to include the cash transactions?

**Comment by Charlie-Henry** [comment]
I went back to the data retrieved from the DR-direct tool and it looks like it is missing the "Banking Id" field (which is in the smartfolio reports) is missing from the dataset. @johnclary is it possible you dropped that field in case it was sensitive? Currently I am using it to match back to the fiserv reports.

**Comment by Charlie-Henry** [comment]
What fields are needed + where we're getting the data from
<img width="655" alt="Screen Shot 2021-11-24 at 3 46 30 PM" src="https://user-images.githubusercontent.com/30810522/143316941-54706703-b8b9-4b79-a290-4fbfbd6b0f21.png">

**Comment by johnclary** [comment]
I'm going to call this one complete. We have the access we need.
