### ISSUE TITLE
Add New Employees to DTS Portal

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#6928]
This is a notification request to add new employee, Matthew S. to DTS Portal.

•	Division: Transportation Engineering
•	User Role: Viewer (Unless a DTS team member) 
•	Home Office Photo - leave blank
•	Send an email intro - No

This is a notification request to add new employee, Don P. to DTS Portal.

•	Division: Finance
•	User Role: Viewer (Unless a DTS team member) 
•	Home Office Photo - leave blank
•	Send an email intro - No

**Comment by ChrispinP** [comment]
Matt and Don added to DTS Portal, complete
