### ISSUE TITLE
Migrate AGOL integrations to use new dev credentials

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6934]
@jaime-mckeown set us up with dedicated ArcGIS Online (AGOL) publisher credentials to manage our AGOL integrations. We should migrate our Airflow and legacy publisher to use these credentials. This will make it transparent to our GIS folks which layers are managed via ETL. 

Order of operations:
1. Test new credentials (done)
2. Update Airflow credentials (john)
3. Update atd-data-publishing credentials (john)
4. Change owndership of AGOL items to new script publisher account (jaime)

Here are the items which need to change ownership (sorry that they don't have titles):
- https://austin.maps.arcgis.com/home/item.html?id=c8577cef82ef4e6a89933a7a216f1ae1
- https://austin.maps.arcgis.com/home/item.html?id=a9f5be763a67442a98f684935d15729b
- https://austin.maps.arcgis.com/home/item.html?id=6c4392540b684d598c72e52206d774be
- https://austin.maps.arcgis.com/home/item.html?id=e7104494593d4a44a2529e4044ef7d5d
- https://austin.maps.arcgis.com/home/item.html?id=9776d3e894a74521a7f63443f7becc7c
- https://austin.maps.arcgis.com/home/item.html?id=52f2b5e51b9a4b5e918b0be5646f27b2
- https://austin.maps.arcgis.com/home/item.html?id=7d4d0b1369504383a42b943bd9c03f9a
- https://austin.maps.arcgis.com/home/item.html?id=66f4b5b0339d4275b64f265dd59727e5
- https://austin.maps.arcgis.com/home/item.html?id=444c8a2b4388485283c2968bd99ddf6c
- https://austin.maps.arcgis.com/home/item.html?id=3a5a777f780447db940534b5808d4ba7
- https://austin.maps.arcgis.com/home/item.html?id=c3fd3bb177cc4291880bbe8c630ed5c4
- https://austin.maps.arcgis.com/home/item.html?id=93e29b23c39b4110ab0bbefde79b4063
- https://austin.maps.arcgis.com/home/item.html?id=47d17ff3ce664849a16b9974979cd12e
- https://austin.maps.arcgis.com/home/item.html?id=e6eb94d1e7cc45c2ac452af6ae6aa534

**Comment by johnclary** [comment]
Scheduled time with @jaime-mckeown for the morning of 8/18.

**Comment by jaime-mckeown** [comment]
Changed owner to Scripts Publisher
- City of Austin Traffic Camera feature layer/service definition
- Travel Sensors feature layer/service definition
- Dynamic Message Signs feature layer/service definition
- Flashing Beacons feature layer/service definition
- Pavement Markings Work Orders feature layer
- Traffic Signal Requests and Pedestrian Signal Requests feature layer/service definition

**Comment by johnclary** [comment]
I updated Airflow and atd-data-publishing `secrets.py` with the new credentials. i ran a few tasks. all looks good.
