### ISSUE TITLE
[Bug] Forever spin on "Assign team" step of new project workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6943]

**Comment by chiaberry** [comment]
The Hasura instance that the moped-test uses (https://atd-moped-editor-development.herokuapp.com/console) is throwing an error in the TeamSummary query. Staging Hasura (and Production) doesn't throw that error, I am not sure yet why moped test's hasura won't accept null in the query.
<img width="1290" alt="Screen Shot 2021-08-14 at 8 05 29 PM" src="https://user-images.githubusercontent.com/12474808/129464107-374c6998-308d-48cb-9faa-995fa9fb55b3.png">
