### ISSUE TITLE
REQUEST to add new employee, Priyadharshini B to DTS Portal

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#6948]
New Employee, Priyadharshini B was added to the Human Resources Manager application on 08/16/2021.

This is a notification request to add new employee, Priyadharshini B to DTS Portal.

First Name: Priyadharshini
Last Name: B
Division: Parking Management
User Role: Viewer (Unless a DTS team member)
Home Office Photo - leave blank
Send an email intro - No

**Comment by ChrispinP** [comment]
Added Priya to DTS, complete
