### ISSUE TITLE
Update Power BI Gitbook Documentation

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#6952]
- [x] External User Guide (download, connect data, clean data, setup powerbi, use data)
[Staff Docs](https://app.gitbook.com/@atd-dts/s/atd-staff-resources/power-bi)
Use Surbhi training video as resource to update documentation
- [x] Internal User Guide (advanced connections, powerbi features/how to, using different data, dashboards)
Create new Gitbook Space for ATD Apps?
- [ ] Send updated external guide to relevant stakeholders such as Brian VDW

**Comment by ChrispinP** [comment]
Moving back to the Backlog, didnt have time to complete before leave. Adding to Tech Debt since its been some time since touching PowerBI

**Comment by susannegov** [comment]
Doing this on Friday - Triage specific issues
- [ ] Link to how-to install Power BI
- [ ] SOP on getting access to Power BI Premium Workspace

**Comment by susannegov** [comment]
All general Power BI SOPs are put in the SharePoint resource page. https://cityofaustin.sharepoint.com/sites/PowerBIUsersInternalOnly/SitePages/Power-BI-Training-Resources.aspx

Any DTS/TPW specific SOPs are put in GitBook - Accessing data gateway, Requesting premium work space access, Creating a new premium workspace

**Comment by susannegov** [comment]
List of External stakeholders for TPW - 25 members

**Comment by susannegov** [comment]
Ready for review/qa.

Not sure about external guide

**Comment by susannegov** [comment]
I think I'm gonna close this issue for now. 
# Reasons
- Wrote up relevant Power BI stuff in Gitbook specific to TPW
- Wrote up relevant Power BI stuff in SharePoint specific to COA

The notifying stakeholders should be kept separate issue at a later date anyway to coordinate with Deployment Pipeline release
