### ISSUE TITLE
[BUG] Empty date field displays "Invalid date"  

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6959]
**Describe the bug**
When no dates are entered for a milestone/phase in the Timeline tables, the field should stay blank. Currently, once the row is saved, all fields display "Invalid date."

![Screen Shot 2021-08-16 at 10 16 22 PM](https://user-images.githubusercontent.com/1463708/129658587-a720c416-5e58-4f55-965c-3975c54ee6f5.png)

**URL**
https://moped-test.austinmobility.io/moped/projects/176?tab=timeline

This is a regression from previous releases. 

Note that there is a related enhancement/fix, #6159, underway, but it is a complex problem and may take some time.

**Comment by mateoclarke** [comment]
This bug is fixed with an [existing PR](https://github.com/cityofaustin/atd-moped/pull/392) that drops the moment.js dependency. We're going to merge that PR into the release candidate instead of the patch. They are very similar.
