### ISSUE TITLE
[Bug] CSV export from projects page doesn't have all the columns in the table

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#6961]
The export only contains 

project_id | project_name | project_description | current_status | start_date
-- | -- | -- | -- | --

![Screen Shot 2021-08-17 at 1 41 28 AM](https://user-images.githubusercontent.com/1463708/129676453-b005a9a5-80a6-45b8-92bc-687a012e4abe.png)

**Comment by chiaberry** [comment]
Here is where the columns to export are being defined
https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
