### ISSUE TITLE
Meeting: Historical TIA Case & Mitigation Data/Migration

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#6963]
# Agenda
- 2 tickets, similar ask with different data
  - Help import TIA mitigation data
  - Import historical TIA case data

### Participants
TED: Cody, Nelson
TDS: Joan
- Nate not making it
DTS: Tracy, Chrispin, Diana

**Comment by dianamartin** [comment]
# Diana's Notes
- Easier solution, combination solution to have overlap

## TIA Historical Mitigation Import
Issue #6678
TIA Fiscal Solution - renamed TIA Historical Mitigation Tracking Solution
- Cases v. Mitigation

### Option1
**Short Term**: update to TDS portal, give tools to clean up data
- needs scoping

### Option 2
**Long Term**: is project sized work, Good news - cleaning up data
- the project will be easier
- Needs to be weighted and prioritized
- Waiting longer, but plus side you get project team 

## Import Historical Cases into Knack
- What would you like us to import?
- Request: import any project prior to 2018
- Goal? Accomplished tracking money, dormant projects. Will get with Nate.
- N: import 2018, 2019/2020 to current
  - report on it
  - List mitigations

Potential audit?
Tracy will interface with Peggy

### 2018 to Current
- TDS has the data Sangeeta
- Site Plans paying the money, in 2020
- Didn't start assessing in late 2018/2019
- [ ] We need to get that data from Sangeeta

Nelson's data is aggregated in the spreadsheet
- Completed data they have worked on

## Action Items
- [ ] Chrispin: send the tables to stakeholders (Template to look at)
- [ ] 2 Week check back with stakeholder

**Comment by TracyLinder** [comment]
## Tracy's Notes

### TIA Case Data (#6776)
- We're not sure where this data currently lives or what it looks like
- We're not sure if we're importing all historical data, or just a certain range
- Goals/Purpose for importing this data:
    - We have to import this data so we can create the TIA cases to connect the mitigation data to.
    - We want to import the TIA Memos for historical cases; get them off of the network drive. This will need to be connected to a TIA Mod case
    - Be able to report on historical data
    - Be able to be responsive to an upcoming audit


**Action Items:**
- [ ] Chrispin will send Joann a tia case spreadsheet template so she can get a feel for how the case data should be formatted for import #6965 
- [ ] Joann will find the historical case data
- [ ] We will sync back up on 10/30


----

### TIA Mitigation Data (#6678)
- We're not sure where the data for 2018 - current is, or if it even exists.
    - Sangeeta may know; Tracy will ask 
- We will split this request into 2 parts:
    - (Pre-Project) Importing existing data, connect mitigations to the TIA case folder (in KNACK), and potentially start scrubbing the data
    - (Project) scrub data, geo-tag, OCR the TIA Memo & append to their case files, create fiscal tracking features
 - This is blocked by importing the TIA case data (above)


**Proposed Steps for Importing the Mitigation Data**

1. Join the 2 mitigation data sets
2. Separate that data into 2 chunks: those with geotags and those without (orphan)
3. For those that already have geotags, ask DTS-GEO if they can append a segment/intersection ID, then import into KNACK
    - Discovery w/ geo team scheduled for 8/23
4. For the orphans, we will import them into KNACK, and Nelson's team will need to manually geotag the data. 

**Action Items:**
- [ ] Chrispin will create mitigation import spreadsheet/template  #6965 
- [ ] Tracy will email Sangeeta about the missing mitigation data (2018 - current)
- [ ] DTS will meet internally w/ our GEO team to discuss # 3 above (8/23)


### Project vs Pre-Project Work

**Pre-Project**
_Epic created: #6964_ 
- Everything explained above
- Lots of data analysis
- Some data scrubbing

**Project**
_I still need to setup the project in GH_
- Data scrubbing
- Finish Geotagging
- OCR the TIA Memos
- Attach each TIA memo in the network drive to the TIA case in the TIA Mod
- Build fiscal tracking features

**Comment by TracyLinder** [comment]
I sent our notes to the stakeholders. Closing.
