### ISSUE TITLE
Create svg exports of full-size bike map art elements

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#6968]
Instead of exporting the massive map file from Pro into Illustrator, we'll export small SVGs of the legend/other overlaid items from Illustrator into Pro to complete the full-size bike map.

**Comment by alan-deanda** [comment]
elements to export:

- [ ] highway symbols
- [ ] route comfort
- [ ] legend pois
- [ ] scale
- [ ] qr code
- [ ] time travel radii
- [ ] dismount zone (UT)
- [ ] one way arrows
- [ ] blowup area

**Comment by alan-deanda** [comment]
While all the art was simplified before exporting as svgs, bringing the art into Pro does not work as expected. In the past, we've successfully incorporated svg symbols of a similar complexity into Pro as styles. However, these elements aren't part of the geography of the map, they hover above, so these elements are treated differently, and one is not able to manipulate them or see their details in the same way one can with a svg style. 
**Issues:**
- The text included in svgs did not scale appropriately. All legend items include a lot of text.
- Being unable to see the individual layers of the svg files makes it impossible to fix the art within Pro
- Some art was included in the svg export, but it did not make it into Pro, like the QR code, or the route comfort legend symbols.

**Comment by alan-deanda** [comment]
@andrewshensky  here's what didn't work about bringing svgs into Pro

**Comment by andrewshensky** [comment]
@alan-deanda Thanks for sharing this. Do you think it would be possible to export the final graphics as a PNG at the proper size and scale to maintain resolution, then just add the flatten PNG to the map in Pro?

**Comment by alan-deanda** [comment]
![highway symbols](https://user-images.githubusercontent.com/42655533/130663796-5ef94cb1-8302-481a-8fab-1fec187a513b.png)
@andrewshensky this is what a full scale png symbol looks like. it's very lossy/looks as bad as the old versions of the highway icons.

**Comment by andrewshensky** [comment]
Yeah it does have a pretty pixelated look to it
