### ISSUE TITLE
Add "Date Received" to monthly trip report records

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#6979]
From Andrea:
> Would like to update the monthly trip comparison table so that the created date reflects the date received. 

Fix is to create new "Date Received" field and populate when uploading trip records.

**Comment by johnclary** [comment]
Sergio patched this [here](https://github.com/cityofaustin/atd-airflow/commit/ec67ea69b235b7f6c729fd943dbce2d91e162078). The August report will be populated with this when it runs on 9/3. Diana will back-date the previous report records.

**Comment by sergiogcx** [comment]
Yes, thank you @johnclary 🙏 Sorry, I should have updated y'all

**Comment by dianamartin** [comment]
Will check on 9/3/21.

**Comment by dianamartin** [comment]
Checked 9/3 and the monthly trip records show up and the filter works perfectly! Thanks @sergiogcx 
- updated to "Received Date" to show as current

**Comment by dianamartin** [comment]
Let Sergio know that the only thing was
>I forgot to tell you on the last update for the MDS trip data Andrea noticed that the new numbers were duplicated.

- Sergio fixed the script to check for error messages
He said
>Yes, it’s totally fine if you delete the duplicates...

- Deleting 4 DUP records
