### ISSUE TITLE
Auto-Delete Old PostgREST ETL Job Logs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#698]
We write ETL logs to our postgrest instance at http://transportation-data.austintexas.io/jobs. We do not currently delete old log records from the postgresql table (`api.jobs`).

We should set up a python or bash job to regularly delete records older than x days. x should be greater than our most infrequent jobs. we currently have nothing running less than a weekly basis; [here's](https://github.com/cityofaustin/atd-data-deploy/blob/production/config/scripts.yml) our deploy config.

**Comment by chiaberry** [comment]
the jobs stopped logging when the scripts were migrated dts-int-data-p01

**Comment by johnclary** [comment]
we should tear down the publisher page and that public view on postgrest, eh?
