### ISSUE TITLE
Upgrade VZdb to `graphql-engine` 2+

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#6988]
Upgrading to Hasura 2.0 would be a smart move long term and have added benefits to the Vision Zero Product. 

From the conversation in the Dev Backlog Grooming on August 18th we determined that it would be feasible to do, but that it would be tricky because we're dealing with the Terraform script and that recovering from an error is not easy. 

It was recommended by John, that in addition to upgrading to Hasura 2.0 the Devs on the team would shadow whomever was taking the lead in order to understand the upgrade process. 

This issue came about because it is preventing us from moving forward in a clean way with [#6915](https://github.com/cityofaustin/atd-data-tech/issues/6915).

**Comment by mateoclarke** [comment]
Here is the [miro board](https://miro.com/app/board/o9J_l0Qx9SE=/?moveToWidget=3074457364359887028&cot=14) frame that explains the steps in the process. As of know, we're on step 4 of the process. We need to add seed data that would be initialized when a new local environment when it gets created. Depending on the size of the seed data, we may consider rolling the seeded data into a docker image which would speed up the time required to spin up a new environment.

**Comment by patrickm02L** [comment]
@patrickm02L Turn this into epic, then use the Miro board to create individual Issues.

**Comment by patrickm02L** [comment]
@mateo is working on Step 4 to 5.

**Comment by mateoclarke** [comment]
Added the Tech Debt label and reassigning to Chia and Frank for later prioritization.

**Comment by frankhereford** [comment]
Based on the work of [#666](https://github.com/cityofaustin/atd-moped/pull/666) for Moped, I'm optimistic that this is going to be a smaller task than we may have thought. We're massively behind in the version of `graphql-engine` used for VZ, and I am very eager to see that caught up. @patrickm02L @chiaberry - do you see a chance where we can we get to this in a < 60 day timeline?

**Comment by patrickm02L** [comment]
I'm putting this on the agenda this week to revisit in grooming on 9/12/22.

**Comment by patrickm02L** [comment]
- Do a code sweep to see what breaking changes could exist between version 1 and 2. 
  - make sure to focus on breaking changes that were introduced between GraphQL engine
- Update task definition for staging and test the following days after. 
- Barring any changes we could update in Production.

**Comment by frankhereford** [comment]
It's always fun to close these old ones. This issue had been superseded by a more recent one, so please see it for more information. https://github.com/cityofaustin/atd-data-tech/issues/13392
