### ISSUE TITLE
Enhanced daily report of new records added or updated in VZD

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#6989]
In order to enable a more detailed reporting of new records added and updated, we'll need to:

1. Create a new DB table, let's name it `atd_etl_updates`
  - Here are the values we'll want to track for each row in a table that gets updated. Each row represents a daily update to a given vzdb table, ex: changes on 8/19/21 to the `atd_txdot_crashes` table.
    - Type of records (ex: crashes, person, unit, etc)
    - Number of new records added
    - Number of existing records edited/altered
    - Runtime of the updates to the table
    - Date/timestamp of updates
    - (maybe) textfield to capture any error statements?
2. Update our ETL process to add records to the `atd_etl_updates` table via a GraphQL mutation executed at the end of the existing ETL process. We should expect to see one record per table type per day.
3. Create a UI to display the key takeaway for stakeholders to have a pulse on the state of recordings being added. This part needs more scoping and should probably be a separate issue dependent on the backend work and some design.

**Comment by patrickm02L** [comment]
@mateoclarke thanks for authoring this issue!

**Comment by patrickm02L** [comment]
Retiring this one!
