### ISSUE TITLE
Discuss management of transportation.data inbox

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#699]

**Comment by amenity** [comment]
Notes:
@dianamartin is going to continue to own it for now, cc @SurbhiBakshi on interesting/helpful responses, and begin compiling commonly-requested info [here](https://docs.google.com/document/d/1A_GTUSb6zH3xLuBlsF4e33v45rJb3rKDMuIBCfLt0NM/edit).

**Comment by dianamartin** [comment]
I've added some FAQs and an introduction to the inbox.
