### ISSUE TITLE
Meet with Unisys

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#70]
### Objective
Unisys is the AMANDA developer for the ROWMAN upgrade project. Their hope is that by learning more about our department needs and long term goals, they’ll be able to develop more valuable solutions (AMANDA-based or others) for us in our current and upcoming projects with them.

### Attendees
Tracy, Amenity, Diana, Ryan Ward, Ryan Mooney, Paloma Amayo-Ryan
Unisys: Paul Olive

### Notes
- [Diana](https://cityofaustin-my.sharepoint.com/:o:/r/personal/diana_martin_austintexas_gov/Documents/Notebooks/Diana%20@%20Work?d=w434b1a507b274d30864e21740e23f0da&csf=1&e=YcC1ka)
- [Amenity](https://docs.google.com/document/d/1BsvNOWcN-z48HLIty3c0P21V5awmKjMKgTjChhKElek/edit#heading=h.5mfsiihrir88)

**Comment by dianamartin** [comment]
[Link to my OneNote](https://cityofaustin-my.sharepoint.com/personal/diana_martin_austintexas_gov/_layouts/15/WopiFrame.aspx?sourcedoc={434b1a50-7b27-4d30-864e-21740e23f0da}&action=edit&wd=target%28MEETING%20NOTES.one%7Cd348b226-65a0-4e43-a67d-e628dcbbf69b%2FAMANDA%20%20Unisys%20Meeting%7C608a34ff-d835-45ba-b974-778c3959288d%2F%29)

AMANDA & Unisys Meeting

**Comment by TracyLinder** [comment]
@amenity @dianamartin ... So when would an issue like this get closed? Is closing it important?

**Comment by dianamartin** [comment]
@TracyLinder @amenity I would think that we could close it once we have attended the meeting. If further action items are needed like follow-up demo. We could create a new issue for that "meeting".

**Comment by amenity** [comment]
What she said. ☝️ 
It's important to close it so that the board is accurate and we document that our time was spent doing this task.

**Comment by TracyLinder** [comment]
:clap::clap:
I agree.
