### ISSUE TITLE
Simplify new project workflow

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7002]
- [ ] Remove stepper, only going to show first screen
- [ ] White container `MuiContainer-root` `width: 75%` and `min-width: 40rem`
- [ ] Remove requirement for project extent

![New project - filling](https://user-images.githubusercontent.com/1463708/132907984-de88fb62-0974-4a91-aebb-9f6ac1fc9a79.png)
![New project - blank](https://user-images.githubusercontent.com/1463708/132907990-f39ee7b3-8f3e-4ac4-9ae8-bd14dedb39df.png)

**Comment by johnclary** [comment]
looks great! i'm sad to say that #7073 is blocking this 😞 i will wrap it up ASAP

**Comment by amenity** [comment]
In recent weeks we've opted to keep the "Standard" variant in several places including #6808. So I'm removing these: 
- [ ] "Project name" in [Material UI "Outline" variant](https://atd-dts.gitbook.io/moped/dev-guides/design-system/component-styles#text-fields)
- [ ] "Description" in Material UI "Outline" variant
- [ ] "Signal" field in Material UI "Outline" variant

cc @tillyw
