### ISSUE TITLE
New Info Fields - FDU - Cost of Svc 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7004]
### ROW applications need to collect FDU numbers, so we can provide the cost of service monthly FDU report. 

**Stakeholders:** Paloma, Kim, Peggy

### Back Office
**Acceptance Criteria**
The following info fields need to be created in AMANDA as per the specifications provided: 

Fund

- Info Code: New, needs to be created
- Info Description: Fund
- Info type: Numeric
- Info Group: Cost of Service
- Applicable to folders: EX and RW (subtype Temporary Right of Way use only)
- Required for Insert: No
- Required for Issue: No
- Show in Portal: Yes
- Mandatory in Portal: No
- Validations/Business Rules: Value provided can be a maximum of 4 characters only 

Department

- Info Code: New, needs to be created
- Info Description: Department
- Info type: Numeric
- Info Group: Cost of Service
- Applicable to folders: EX and RW (Temporary Right of Way use subtype only)
- Required for Insert: No
- Required for Issue: No
- Show in Portal: Yes
- Mandatory in Portal: No
- Validations/Business Rules: Value provided can be a maximum of 4 characters only   

Unit

- Info Code: New, needs to be created
- Info Description: Unit
- Info type: Numeric
- Info Group: Cost of Service
- Applicable to folders: EX and RW (subtype Temporary Right of Way use only)
- Required for Insert: No
- Required for Issue: No
- Show in Portal: Yes
- Mandatory in Portal: No
- Validations/Business Rules: Value provided can be a maximum of 4 characters only 

Object

- Info Code: New, needs to be created
- Info Description: Object
- Info type: Numeric
- Info Group: Cost of Service
- Applicable to folders: EX and RW (subtype Temporary Right of Way use only)
- Required for Insert: No
- Required for Issue: No
- Show in Portal: Yes
- Mandatory in Portal: No
- Validations/Business Rules: Value provided can be a maximum of 4 characters only

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  sent you the demo in email. Please let me know your feedback.

**Comment by Nadin-Nader** [comment]
@SubhaShroff reviewed the demo and it looks good. Only thing i would add is in the error message. I think it would be helpful to include something like "...Unit and Object info values should be up to 4 digits not exceeding 9999."
Other than that, it looks good.
One you add that in there, go ahead and send it to CTM for DEV deployment

**Comment by SubhaShroff** [comment]
### Status:
I need to do the change in message as per @Nadin-Nader's feedback given above.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  - SCTASK0167597 is submitted for DEV deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  UAT done on DEV & PIPS portal (as DEV portal is not allowing to login). Based on the approval, I will submit TEST deployment request.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0167880 is submitted for TEST deployment.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to TEST please UAT

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The new FDU infos look good on BO. But Portal may need refresh and would prefer to test it tomorrow, as I see Swapna is on screen sharing call. Otherwise, I tested it on PIPS test Portal. It looks good for both EX & RW. Will update tomorrow after testing on usual Portal.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Tested on ABC TEST Portal also after Swapna did clear cache. Its ready for your UAT.

**Comment by SubhaShroff** [comment]
### Status:
Ready for UAT on TEST.

**Comment by TracyLinder** [comment]
Ticket #7005 needs to go to PROD before this ticket does.

**Comment by TracyLinder** [comment]
@Nadin-Nader please test today at the 2pm meeting

**Comment by Nadin-Nader** [comment]
@TracyLinder @SubhaShroff per todays meeting and UAT the fields were working as requested on TEST. This is ready for PROD

**Comment by Nadin-Nader** [comment]
## **APPROVED for _PROD_ Deployment🙌🎉🙌‼**

**Comment by SubhaShroff** [comment]
### Status: Ready for PROD, waiting for #7005 PROD Deployment. Can go together in PROD.

**Comment by TracyLinder** [comment]
**Note:** I just tested a portal application & input 3 numerical numbers instead of 4 and the system accepted the values. We should probably update this feature to only allow if all 4 characters exist.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  SCTASK0170272 is submitted for PROD deployment.

**Comment by Nadin-Nader** [comment]
Issue Reported by Paloma:

Permit # = 2021-155117 EX
RSN = 12793396
Issue = Entering funding numbers using only numeric input but receiving error that states "Wrong Number Format, This field allows numbers only"


![FDU Fields 1.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/cdd7bd88-131a-4f6e-9df5-e471c52554f9)
![FDU Info 2.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/0f36a32c-ea50-47e1-9e68-8288ba4ec3e0)

**Comment by Nadin-Nader** [comment]
**Status:**
This has been deployed to PROD and is working as requested. Closing card
