### ISSUE TITLE
New Info: Work Order #

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7005]
### A new info needed for Cost of Service

**Stakeholders:** Paloma, Kim...

**Acceptance Criteria:**
A new info field below needs to be added to AMANDA as per the specifications provided. 

- Info Code: New, needs to be created
- Info Description: Work Order #
- Info type: AlphaNumeric
- Info Group: Cost of Service
- Applicable to folders: EX and RW (subtype Temporary Right of Way use only)
- Required for Insert: No
- Required for Issue: No
- Show in Portal: Yes
- Mandatory in Portal: No
- Validations/Business Rules: None

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT i have sent this to be deployed to **_PROD_** by the DevOps CM Team under **SCTASK0168157**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on this to be deployed to **_PROD_** by the DevOps CM Team under **SCTASK0168157**

**Comment by Lpriya-LIT** [comment]
Deployed to Dev , Changes look good. please refer attached Portal and Backoffice screenshots

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/c42f7aa2-e866-4f23-818d-47bc05346674)

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/2fa79518-bc7c-45d4-90d4-72f389fd7077)

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on this to be deployed to TEST by the DevOps CM Team under **_SCTASK0168306_**

**Comment by Nadin-Nader** [comment]
**Status:**
Ready for UAT in TEST B.O. and TEST Portal

**Comment by Lpriya-LIT** [comment]
Update after UAT  - Work order # has to be Alpha numeric

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Updated AC to reflect InfoType to be AlphaNumeric per the UAT done today

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I Have sent this to be deployed to **_DEV_** under **SCTASK0169805**

**Comment by Nadin-Nader** [comment]
**Status:**
Sent to DevOPS CM Team to deploy the last changes to **_DEV_** under **SCTASK0169805**

**Comment by TracyLinder** [comment]
**Update**

Dev deployment done. Priya sent test deployment to Nate & he will work on promoting today.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM TEAM for **_TEST_** deployment under **SCTASK0170112**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team  to deploy to **_TEST_** under **SCTASK0170112**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT  @TracyLinder the changes have been deployed to TEST

**Comment by Nadin-Nader** [comment]
**STtaus:**
On TEST ready for UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test . Data type has been updated to Alpha numeric

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/868fdb20-2c8a-4a3d-8724-4648af9f2453)

**Comment by Nadin-Nader** [comment]
## **Approved for **_PROD_** Deployment👍🙌🎉‼

**Comment by TracyLinder** [comment]
**Note:**
I just noticed that this info defaults to 0. I'm not sure if that matters or not.

**Comment by Nadin-Nader** [comment]
@TracyLinder @Lpriya-LIT This has been sent to the DevOps CM Team for PROD deployment under **_SCTASK0170258_**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy to **_PROD_** under **SCTASK0170258**

**Comment by Nadin-Nader** [comment]
**Status:**
This has been deployed to PROD and is working as requested. Closing card
