### ISSUE TITLE
[BUG] Current phase not listed correctly in project list

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7011]
In the project list, the current phase is either blank or does not match the current phase of the project. For example, project [#290](https://moped.austinmobility.io/moped/projects/290/). 

Project listing:
<img width="920" alt="Screen Shot 2021-08-20 at 4 07 09 PM" src="https://user-images.githubusercontent.com/14793120/130293508-fb26e691-fee6-44d4-878f-a8a1cd225e3d.png">

Project detail:
<img width="869" alt="Screen Shot 2021-08-20 at 4 07 30 PM" src="https://user-images.githubusercontent.com/14793120/130293512-85426b4c-80ef-4db7-bdab-33bae3e1b8e1.png">

**Comment by amenity** [comment]
Thanks to #7827, this is no longer an issue.
