### ISSUE TITLE
Publish Moped CTN segments to AGOL feature service  

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7013]
In order to accomplish #7012, we need the Moped CTN segments to be published as a publicly-shared feature service on ArcGIS Online. The only attributes that need to be included are the same attributes currently published in the vector tile layer. 

Note that we do not need the intersection points (which are included in the tile layer).

**Comment by alan-deanda** [comment]
@johnclary , I've uploaded the feature service, it can be found [here](https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/Moped_CTN_Segments_08_23_2021/FeatureServer)


The content page for the feature service is [here](https://austin.maps.arcgis.com/home/item.html?id=d73703dbcea248e6ab878e20ec2382f8) in case you need it.

On an interesting note, this file seems to be 38MB compared to the 14MB of the vector tile version. I was expecting this file to be much heavier. Hope it works well!

**Comment by johnclary** [comment]
thanks @alan-deanda! looks great. ran a quick test and it has everything I need. closing this!
