### ISSUE TITLE
DTS Service Delivery: Discuss Change Management

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#702]
### Objective: 
Discuss what steps/actions should be involved when changes are made to a project that have a significant impact.

**Comment by TracyLinder** [comment]
*Idea:* Update the project brief & require new signatures.

**Comment by amenity** [comment]
@TracyLinder - I'm tempted to close this and leave change management strategy to each PM to handle however they see fit... thoughts?

**Comment by TracyLinder** [comment]
@amenity I agree. Closing.
