### ISSUE TITLE
Communicate with all stakeholders about SharePoint site migration to Modern Pages

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7034]
Diana 
DTS

see [spreadsheet](https://docs.google.com/spreadsheets/d/1O_wW70EpLydQ0t5-fV2z80NN_jzhA72m32m3o5hBbMg/edit#gid=0) for assignments 

We've discussed and assigned which sites we'll be emailing, trying to get feedback by Sept 1st. 

- Follow-up email sent to Spoorthy on 9/2 - to check in w/ how many replies we've gotten
- Follow-up meeting w/ Spoorty 9/6

**Comment by ChrispinP** [comment]
@dianamartin Should we update and close this now?

**Comment by dianamartin** [comment]
@ChrispinP yes, let's update and close this. We can create another one for the post migration communication.

**Comment by dianamartin** [comment]
Closing this issue, will create more if need be,
