### ISSUE TITLE
[Enhancement] Project Status Badge

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7036]
### UI & Triggers
- Add menu items for "Place on hold" and "Cancel", see below
![New Summary Page – 3 0 – Cancel project](https://user-images.githubusercontent.com/1463708/135399309-630ad621-53c3-49e0-aa85-5f882a33afda.png)
- Display status as a badge at the top of the project - design specs in #7492

## Background
The use of the project "Status" field is confusing. It's options are:
- Active
- Potential
- Cancelled
- On hold
- Completed
- Archived

Meanwhile, we have phase names which feed into the "Current Phase" attribute and serve a similar purpose. "Potential" and "Complete" are both Phase names.

### Initial proposal
- Show the status as a badge, a 
- Simplify the project Status field to these values
   - Active
   - On hold
   - Cancelled
- Default status is "Active". Users can place a project on hold or cancel it in the upper righthand menu at the top of a project page. 
![New Summary Page – 3 0 – Cancel project](https://user-images.githubusercontent.com/1463708/135399309-630ad621-53c3-49e0-aa85-5f882a33afda.png)
- Cancelled projects are hidden from the "All projects" listing.

**Comment by johnclary** [comment]
@amenity FYI obvi needs further discussion

**Comment by amenity** [comment]
@johnclary @patrickm02L @zappfyllc 
I don't love the idea of "on hold" and "cancelled" as phases. What about this: 

![Project status](https://user-images.githubusercontent.com/1463708/132068953-03372797-af3e-404e-9098-de4732942a3e.png)

**Comment by johnclary** [comment]
I like it! And I kinda think we should change the menu icon from [three dots] to a cog ⚙️.

So the only way to edit the status would be to use that menu. The possible statuses are:
- Active (default)
- On Hold (set from menu)
- Cancelled (set from menu—formerly known as "archived")

We're still stuck with the nuisance of having two status fields displayed to users (current status and current phase). Perhaps "Current phase" can take the value of "On hold" or "Cancelled" if not active? If we do this, we can remove "Current status" from the project summary table and the project list—which I'd really like to do.

I think we should also consider forcing at least one phase to exist on the project. This would ensure that all projects always have a "current phase". For example, we could automatically insert a "Potential" phase when a project is created.

Alternatively—"Potential" is a weird name for a phase. Maybe we do away with the "Potential" phase, and use it as the default "Status" instead of "Active"? Sorry for rambling....

**Comment by amenity** [comment]
I agree that "Potential" is kind of a weird name for a phase, but not when you consider the subphases: 

- Active development review
- Study recommended
- Study in progress
- Environmental study
- Recommended

See [@patrickm02L's latest project summary view without status](https://github.com/cityofaustin/atd-data-tech/issues/6808#issuecomment-913874427).

I prefer the three dots to the settings cog because it's broader so can accommodate "Share", "Favorite", "Export" etc.

**Comment by amenity** [comment]
@johnclary @patrickm02L - I updated the description to reflect what we've discussed. Look okay?

**Comment by patrickm02L** [comment]
This works. My only addition is to include a on-hover tool tip to distinguish between "edit" and "new status" icons.

**Comment by johnclary** [comment]
Looks good. In terms of the database changes, this is how I'm proposing we determine the "Current Phase":

status | phase | current phase
-- | -- | --
Cancelled | (any) | Cancelled
On hold | (any) | On hold
Active | (any) | (use phase)

I also propose we add a requirement that all projects have one and only one phase that is marked as "active". Otherwise, what we have will have a blank "Current phase" field (as we often do now).

In order to accomplish this, I suggest we automatically insert a "Potential" phase when the project is current and set it as "active". We would also need to prevent the user from deleting this phase of a project.

I'm open to other ideas!

**Comment by amenity** [comment]
@patrickm02L - thanks, getting that in #7322 🙏

**Comment by zappfyllc** [comment]
@johnclary Your last comment makes sense to me once I reread this entire issue. I think a way to simplify this is to add a `related_status` column in `moped_phases`, then map that column to the options in `moped_status` based on the criteria you've mentioned.

This should simplify the frontend, as we can then just query `moped_proj_phase` where `active` is `true` (since we're adding the constraint of one phase being uniquely active per project) and return both the `current_phase` (`phase_name` where `active` is true) and the `current_status` (`related_status` based on `phase_name`).

If I'm understanding correctly, `current_phase` and `current_status` then would only be controlled through writes to `moped_proj_phase` as opposed to trying to maintain separate values stored at the `moped_project` level.

**Comment by zappfyllc** [comment]
@johnclary Thanks for the clarification: I think this might be a semantical argument and I poorly communicated in my comment above. I am still suggesting we pull the phase for a given project's active phases from `moped_proj_phases` into a `current_phase` field (I think you're suggesting this as the meaningful descriptor), and then my suggestion for `related_status` is effectively a way of simplifying the projects to active/cancelled/on hold in relation to the phases. Phases would effectively dictate the project status (e.g. Active would be mapped to all of the other possible phases outside of cancelled and On Hold via the `related_status` field). The effect should be the same unless I'm missing something.

The original intended benefit of separating phase/status was that you could have a project get Cancelled or placed On Hold while maintaining the phase in which that project was left (e.g. Cancelled during Design, On Hold in Pre-Construction, etc.) but I think the activity log effectively captures that information, so if it's easier to condense everything into `moped_phases`, call the query with BL above a computed field of `current_status`, we could keep status potentially only for archived/active distinction. (eliminating the redundancy of cancelled/on hold)

**Comment by zappfyllc** [comment]
@amenity @johnclary and I touched base about this on 10/29 quickly post our call with Frank regarding AMD/Knack integration.

I'm going to assign this to myself to sort out the data model this week and get the work queued up for next sprint, but we're all in agreement about the following:

- Status changed by UI actions or changes in phase: no longer a dropdown field (really just a read-only value that could be a label)
- We won't have a "Cancelled" phase, at least not one that's ever seen by users in the UI (we may need one depending on the data model, but it would be hidden from the users).

There are three terms here, all somewhat related:

- _Current phase_ is always most descriptive
- _Current status_ is concise, as John has presented above, and is determined by UI actions (or, if deemed appropriate, rules stored within the database)
- _Phase simple_ is a third term here that is more descriptive than _current status_ but less descriptive than _current phase_ and it will most likely match to external systems or reports such as Capital Projects Explorer, eCapris and other standardized mappings (IMPD does this, and it doesn't quite match the two terms above)

We should be able to accomplish all of this via some mapping in the database to make the queries relatively easy, and then we can have the values set based on BL in the app.

**Comment by amenity** [comment]
@johnclary @zappfyllc - y'all are the best. This sounds perfect. 
Making this into its own epic with a couple other issues.

**Comment by amenity** [comment]
@zappfyllc @sergiogcx - am I understanding this correctly? Feel free to [add/correct in Miro](https://miro.com/app/board/o9J_knyFAmc=/)
![Screen Shot 2021-11-29 at 10 42 45 PM](https://user-images.githubusercontent.com/1463708/143986988-7f433427-9bb2-47f1-87d4-336beae4ac0b.png)

I want to clarify this so we can spec how we handle the [displayed status on the projects page and advanced search](https://github.com/cityofaustin/atd-data-tech/issues/7827).

**Comment by amenity** [comment]
Hurray! Thanks, @zappfyllc @sergiogcx .
