### ISSUE TITLE
GIMOB Meeting - September

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#7043]

**Comment by jaime-mckeown** [comment]
- SPOCs to overlook authoritative and public items on AGOL
   - display will change to show City of Austin as owner (owner stays the same) on any data that is public and authoritative
   - need to go over ATDs data in AGOL that is published from GISDM
   - will give everyone 1 month to verify items
- City wide issues: Creating new GIS Accounts/Passwords
   - errors are occurring when links are sent to users to create passwords
   - Allison is trying to get a meeting setup to try and get this problem fixed
- Vote for SPOC for Other Depts: Marna as Primary, Lauren as Alternate
- Modernization Project Update: talked about progress, training, etc.
- Street Initiative
   - Esri has been conducting interviews with departments, then Esri will be delivering a report with recommendations for moving forward and what kinds of projects they will be starting
   - She will share the findings with the board
- AGOL Subcommittee
  - Print Widget Discussion to create a new general template, will be meeting again
  - User Group Meeting will be scheduled to discuss what everyone is doing in AGOL
  - Will also be updating the Governance Documentation: recommendations for markup layers and map notes
  - Looking for a co-lead for the AGOL Subcommittee
  - Next meeting is on 11/17
- UAV Drone Committee: working on the Governance at this point
- Esri UC Subcommittee:

**Comment by johnclary** [comment]
thanks!
