### ISSUE TITLE
Create new Web Map for accessing AMANDA ROW Permits

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#7044]
I just had a request for some AMANDA ROW Permit numbers. Want to make a Web Map for ROW to be able to produce the same results through AGOL.

**Comment by jaime-mckeown** [comment]
https://austin.maps.arcgis.com/home/item.html?id=b37b292fdb8642ac8f55c3743ecca858

**Comment by johnclary** [comment]
Jaime is working with Sean M. to debug slowness. The layer is not loading.

**Comment by jaime-mckeown** [comment]
Chatted with Sean about the layer in AGOL. He suggests that we filter the layer to remove the old data. As an example, there are 130,486 total records, but only 24,604 records available in ROWPACT. Below is what is available in ROWPACT:

![image](https://user-images.githubusercontent.com/48842809/134722087-b867cbed-6f33-4a85-9554-20e34fc0eb7e.png)

**Comment by jaime-mckeown** [comment]
I also think we will need closed records for a specific number of years. The request I just helped out with for Jim D. went back a couple of years.
