### ISSUE TITLE
[Feature] Project Sponsors and Partners

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7050]
In Moped 1.0, we want to track the following information so that users can see what projects a particular workgroup is involved with:
- Project Sponsor - Division, department, or external organization that owns a project
- Project Partner - Division, department, or external organization that is participating in a project

![New Summary Page – 3 0 – 2](https://user-images.githubusercontent.com/1463708/136119623-cd6e6969-1728-4591-bba7-55861365983e.png)

**Comment by amenity** [comment]
@zappfyllc - now that you're back... could use some advice on how much we should modify the schema now that we have more context for this use case. Let's discuss.

**Comment by amenity** [comment]
Previously, @johnclary and I had specified this for the data model: 
- Remove all columns from the [Project sponsor table](https://db-docs.austinmobility.io/atd-moped-production/tables/moped_proj_sponsors.html) besides
    - `project_sponsor_id`
    - `sponsor_name`
    - Rename table to `moped_project_sponsors` 
- Populate with [these values](https://docs.google.com/spreadsheets/d/1VGO57EL1TtASbLz2yeWyLwcTB1lT9LR8G6_QZ4WSifs/edit#gid=1258054259)

Discussing w/ @mateoclarke, though, we realized that there are a lot more tables set up for this functionality. Here's the relevant portion of @zappfyllc's ERD: 
![Moped Schema - archived 6 5 2020-Entities _ Personnel](https://user-images.githubusercontent.com/1463708/131895992-e6410904-5df8-4ecd-8760-49952c726c13.png)


Maybe we don't need all of that, but I do think it's wise to have a table for entities and be able to relate it to projects in a variety of ways. So I'd propose we 
- Have a table for entities, populated with [this list](https://docs.google.com/spreadsheets/d/1VGO57EL1TtASbLz2yeWyLwcTB1lT9LR8G6_QZ4WSifs/edit#gid=1258054259) 
- Have a "Project sponsor" field (one per project) to pick one of👆
- Down the line, could also use entities for "Project partners" or similar fields

Another wrinkle, I realize: 
Logically, the tables we are using for user accounts, [moped_workgroup](https://db-docs.austinmobility.io/atd-moped-production/tables/moped_workgroup.html) and [moped_department](https://db-docs.austinmobility.io/atd-moped-production/tables/moped_department.html) concatenate into a subset of these entities. Should we hold those relationships in the database? 

E.g. 

Sponsor | Department | Workgroup
-- | -- | --
COA ATD Signs & Markings | ATD | Signs & Markings
COA ATD Systems Development | ATD | Systems Development
COA PWD Sidewalks & Special Projects | PWD | Sidewalks

**Comment by amenity** [comment]
@johnclary @mateoclarke @zappfyllc 

After discussions with AMD, I think two basic fields would be really helpful for 1.0: 
- "Project sponsor" (ultimate "owner" entity ) 
- "Project partners" (all entities involved)

This just ensures that users can a)filter down to "their" team's stuff b) find out who's involved in larger projects, before we implement #6625. 

I could see the necessity for these evolving or phasing out as we implement Subprojects, "Project Types", "Project Groups" etc. etc. but since we're still lacking strong use cases around those I'd like to move forward with this.

**Comment by amenity** [comment]
@zappfyllc please update the data model section of this issue description before passing off to @sergiogcx

**Comment by zappfyllc** [comment]
@sergiogcx [the list Amenity attached to the issue description](https://docs.google.com/spreadsheets/d/1VGO57EL1TtASbLz2yeWyLwcTB1lT9LR8G6_QZ4WSifs/edit#gid=1258054259) needs to go into the table _moped_entity_ (we can rename this to moped_entities @amenity do you want to use that lingo?)

"Project sponsor" should be a column in the _moped_project_ table that represents a single reference to the _moped_entity_ i.e. each project has one "project sponsor" but each project sponsor is associated to many projects.

Additionally, we need a many-to-many relationship between _moped_projects_ and the newly created _moped_entities_ table, which would inherently be _moped_proj_partners_ (can rename to moped_project_partners if you prefer). A project can have many partners and partners can associate with many projects, but these are still sourced from _moped_entities_.

WIP for UI changes:

**Comment by amenity** [comment]
@zappfyllc Thank you!! Adding 👆to this issue description. 

I think "entities" is fine... unless you have a better suggestion, cc/ @johnclary .

**Comment by amenity** [comment]
@zappfyllc - do we want to make any other edits to the _moped_entity_ table? 
- "Workgroup name" --> Entity name
- Note sure what "Affiliated workgroup" is ...
- I know that we want a concatenated looong name like "COA ATD Active Transportation & Street Design" available for GIS queries, but should we also have columns for Organization (COA), Department (ATD), Workgroup (Active Transportation)? Seems more elegant in non-GIS code to filter specifically for one of those values, rather than doing a text search within the long string to bring up all the ATD projects, for example.

**Comment by zappfyllc** [comment]
@amenity good catch, we should certainly always reconsider the columns from my theoretical data model since it's been so long.

"Affiliated workgroup" > I think the idea here was to place a reference to Active Transportation, Signs & Markings, etc., similar to how you're suggesting breaking up the names, but it would be a reference to the workgroup's id in `moped_workgroup` to hold the relationship.

"Workgroup name" > Entity name makes sense. We also might want an abbreviated name like Nathan has in the IMPD, "ROW" for "COA ATD Right of Way" for usability at times? Or that might go against your philosophy for usability? Might there be situations where a less wordy but commonly used abbreviation would be nice to have? I do not have strong feelings here :), just putting it out there.

I absolutely +1 the columns for concatenation because I also think this gives us an opportunity to set up a relational structure that could tie into users, etc. I know we may not have features in v1.0 or v2.0 that necessarily make use of these relationships, but I still like the idea of relating users to entities (originally my goal was to do that through the use of `moped_workgroup`) so that we could easily query data in a way that might make it easier for some workgroup-specific features.

**Comment by amenity** [comment]
@sergiogcx took care of this, looks great!
