### ISSUE TITLE
Spike: Evaluate Prefect

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7054]
Everybody:
- pick a DAG
- follow the prefect tutorial to translate it and deploy it
- create agent on local machine to test
- try to register/deploy flow on prefect

John:
- atd-prefect repo
- clean-up prefect cloud and share credentials

**Comment by amenity** [comment]
@sergiogcx - please send out calendar invites for a Thursday in January:
- Prefect dev skillshare 
- Placeholder day-long event for everyone to work
