### ISSUE TITLE
Review Updated Street Segment Change Dataset

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#7055]

**Comment by johnclary** [comment]
Waiting for Dwayne to deploy process to maint prod.

**Comment by andrewshensky** [comment]
Dwayne will be accepting a new role in a different department. He has updated Jacquie with our progress on this and she will now be the main contact.

For time being this dataset will live in MAINTEST. This will not impact any processing on our end.

**Comment by andrewshensky** [comment]
Street Segment Changes dataset had stopped collecting updates at end of August. Dwayne has updated processing which will allow it to run everyday without stopping.

Processing should begin running again tonight, I will verify to make sure process has restarted and past changes have been captured

**Comment by johnclary** [comment]
Bummer to hear Dwayne is moving on. Glad he was able to get this mostly wrapped up.

**Comment by andrewshensky** [comment]
I was able to verify this morning that processing has restarted and changes that were made while processing was down appear to have been captured. I think we are in a good spot with everything in its current state.

**Comment by andrewshensky** [comment]
Everything has continued to update properly with this dataset for the past week. I will be closing this issue.
