### ISSUE TITLE
Migrate to ATD AWS Organization

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#706]
The loss of `austintexas.io` has prompted us to consider leaving the shared AWS account currently "managed" by ODD. The benefits of moving to our own AWS Org:

- We will have tighter control over user access and permissions
- We will be able to manage AWS resource usage according to our own well-defined processes
- It will be easier to more clearly track and forecast our usage costs

Dev team is in agreement that we should proceed.

**Comment by mateoclarke** [comment]
In this epic we are prioritizing #710, migrating VZ services first.

Then the rest of the Non VZ infrastructure.

**Comment by johnclary** [comment]
priorities doc:
https://docs.google.com/document/d/1iVfofusVa5UrXMF096MH8NvTC_SkW7FKHd0Jk6xrgwI/edit
