### ISSUE TITLE
Implement "Project website" field 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7069]
### Data model
- Add a (text?) column to the [`moped_project`](https://db-docs.austinmobility.io/atd-moped-production/tables/moped_project.html) table

*UI*
- Add text field to project "Summary" tab
- Render as the URL string, truncated to 25 characters, with ellipsis and external link icon
![Screen Shot 2021-08-27 at 10 59 59 AM](https://user-images.githubusercontent.com/1463708/131155853-0d9c3c7a-de80-4575-ae17-d95710df24ed.png)

**Comment by johnclary** [comment]
Tilly is working on validating that the input is a valid URL.

**Comment by amenity** [comment]
@sergiogcx - I spoke with @tillyw and she's good for you to take this from here as you do the Data Table deprecation.
