### ISSUE TITLE
Ability to define new project from signal asset

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7073]
As a Moped user, I would like to define my project's details by selecting a signal asset so that I can create new projects quickly without entering redundant asset information. 

Functional reqs:
- Ability to select from a list of signals when creating project
- If signal is selected, project name should take name of signal name
- If signal is selected, project component should be automatically created as a "signal" (not "generic") component with correct subtype ("Traffic" or "PHB")
- Enforce validation: either project name or signal must be populated
- Disable map editing when user has selected a signal — component feature will be created automatically

In scope:
- select a signal from the new project workflow

Out of scope:
- Select a signal when adding a component on the Map tab

**Comment by johnclary** [comment]
https://user-images.githubusercontent.com/14793120/131234107-1240d1c0-e72d-433c-b587-43f3ead261af.mp4

**Comment by johnclary** [comment]
In case you're confused by the numbers that prefix the signal name, e.g. "2: GUADALUPE / LAMAR", this is the traffic signal id and this labeling convention mirrors the Data Tracker exactly. It will be familiar and useful to AMD.

In case you loathe the UPPER CASE signal names—this is an artifact of the Data Tracker, which is in turn an artifact of the canonical GIS streets layer. I'm open to changing it but probably warrants discussion.

**Comment by amenity** [comment]
Also, it may make sense to loop in #7002 (assuming it's small?) along with this.
