### ISSUE TITLE
VZE: Update Fatality and Serious Injury counts for accuracy

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7080]
The Vision Zero fatality and serious injury counts do no reflect an accurate number. Xavier brought this up a few weeks after our August Sprint review as an issue that needed a fix. 

This inconsistency can cause reporting problems for those who want to get a quick reference counts of the latest numbers. 

It's possible that the numbers that are currently being reported are CRIS fatalities, and regardless of the filtering, is not pointing to the ATD fatality count, which is why the number is wrong. 

![Screen Shot 2021-08-30 at 12.01.11 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/9fc560e6-b470-40ce-921e-40dc4d657322)

**Comment by mddilley** [comment]
Looks like the VZV widgets that live on https://www.austintexas.gov/department/vision-zero are embedded using an iframe from https://visionzero.austin.gov/viewer/measures and could be added in the same manner to VZE without too much of a lift

**Comment by patrickm02L** [comment]
Look into fixing the numbers with the widget code #7205. Timebox to a 2.

**Comment by patrickm02L** [comment]
Not sure if this is related to #2413, but it might be worth checking out.

**Comment by mddilley** [comment]
@patrickm02L mentioned in dev sync that there is another Years of Life Lost widget that is zeroed out. I will look into this in this issue as well.
Ex.: https://visionzero-staging.austinmobility.io/editor/#/locations/2162272C47 
![Screen Shot 2022-09-22 at 4.12.20 PM.png](https://images.zenhubusercontent.com/5cfe7d078509cb6dcbaafdc3/20cd5199-7150-49b8-9b74-ed98b7a0dede)

**Comment by patrickm02L** [comment]
Code has been merged considering this closed.
