### ISSUE TITLE
[TDS-TIA] Admin Button, Form, & View Based API to create empty TIA Case records before Historical Import

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#7084]
Since we capture the unique Knack Record ID for each TIA Case to correctly associate it to all of the customer submissions. We need to make sure that these case records are first created as empty templates using a view based API on a form the same way we do the TIA Application. This button & form will be viewable to Admins only since we dont want reviewers using this function and is only intended so we can import historical cases into the app.

**Comment by ChrispinP** [comment]
New Case Template Admin Menu and Button created that navigates to the Case Template Form
![image](https://user-images.githubusercontent.com/67915167/132741313-3fc870e1-a07e-49e6-bf4e-9da0577735b7.png)
![image](https://user-images.githubusercontent.com/67915167/132741354-679174db-c504-4c69-ab4c-33000771693c.png)

The JS has been updated so the API saves the Knack Record ID for the Case Template
![image](https://user-images.githubusercontent.com/67915167/132741511-6e7a603e-2760-43fb-b94f-100c155820bc.png)

Test Template record successfully created.
![image](https://user-images.githubusercontent.com/67915167/132741786-9909edb2-0422-4804-8326-87bc169a755b.png)

**Comment by ChrispinP** [comment]
the API View Based PUT Request is no longer needed as I have updated TDS with an updated workaround for linking customers to their TIA Portal since we can successfully use Page URL email field for the customer's side and use a Short Text field in the child objects to grab the Knack Record ID of the parent from the connection field and drop that in the Email link URL for the reviewer's side.

Therefore, the Admin Button is no longer necessary and cases can be directly imported into the database since the PUT request is no longer working, active, or needed.

@johnclary Should I create a new issue to remove the Admin Button, the PUT Request code, and the Save Knack Record ID page or can I use this issue to do so?

**Comment by johnclary** [comment]
@ChrispinP I think you should re-purpose  #7253 for this work. Please add whatever notes make sense there, and you can link that issue to the Pull Request you open to commit the custom javascript code change. Thanks for doing this!

**Comment by ChrispinP** [comment]
this feature is no longer needed for case import. the pages, form, and menu for this Admin Button have been removed. Historical cases can now be imported normally without having to first create the records.
