### ISSUE TITLE
Move trips data; Add transactional data to update Fees/Payments page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7085]
During the Thursday, Aug 26th Sprint Review, the Shared Mobility Team discussed making the following improvements to the Fees/Payments page. 

- Move "Trip Data" to a new tab with a new URL
- Add transactional data to the Fees/Payment page.

Currently, Providers pay a lump sum every six months for all the permits they're renewing. That amount is captured in under the "Monthly Trip Fee Payment Tracking" section of the page.

As an addition or replacement, Staff would like to have a table that tracks ongoing transactions/payments by Provider, which includes the number of total permits being renewed, and monthly payment for per/trip fees on the Fees/Permits page.

@dianamartin referenced an achieved license page that we might be able to use to show past transactions. 

[Miro board ](https://miro.com/app/board/o9J_l4LSuvE=/)showing the table relationships.

**Comment by dianamartin** [comment]
Messaged Sergio
>Hey Sergio, the Shared Mobility team was asking if I could relocate the Monthly Trips information on to a different page. Would this action mess anything up on our end for the MDS automation? The object would remain the same object 10. The current page is scene 26 and it's called Fees & Payments, so if I created a new page the scene number would most likely be different and would be called "Monthly Trips" or something.
- Let me know if there are any consequences to doing this. I'll wait on your reply before making any changes. Thanks!

**Comment by dianamartin** [comment]
- [x] Created page `Trip Data`
- [x] Copied all tables from "Fees & Payments" to "Trip Data"
- [x] Added Page Rules from "Fees & Payments" page to "Trip Data"

**Comment by dianamartin** [comment]
- I created a new object table `transactions`
#### Field Headings

- Transaction ID - auto increment
- provider - connection
- archived license - connection
- impoundment - connection
- monthly trip - connection
- Created By - connection
- Transaction Date - date
- Modified By - connection
- Modified Date - date
- Date Received Payment
- Transaction Type
- Transaction Amount
- Transaction Status
- Invoice Date
- Invoice Number
- Period
- Payment Type

Created Transactions table on "Fees & Payments" page
- Tested:
- impoundments
- monthly trips
- NEED TO TEST: license/permit renewals

**Comment by dianamartin** [comment]
Talked to Andrea 9/3

# Notes from discussion
### Invoice Info
- There should be an "Invoice Due Date" - should be paid within 30 days
- applies to Impoundments, Monthly Trips
- Permits/Licenses just need to be before the permit/license expires

### Finance Invoice Info
- Monthly Trip invoices are generated and given to Finance
- Current Process: Tim creates invoice, comes up with made up Invoice IDs for permits, inspection and impoundment records
- Crystal says the Invoice ID for monthly trips in SMO spreadsheet is generated from AIMs system
- She said she uses it as a backup, like for SMB invoices
- She enters them into the AIMs system and then when they receive funds that closes it in AIMs, it's what Finance uses to determine which invoices are still outstanding
- Fields Crystal uses on invoice: 
  - Trips Amount
  - Date
  - Month
  - Provider

### Future Info
- Will be charging license fees to providers, will be flat rate
  - Dec/Jan renewal: $Flat Rate + Permit charges too
  - June Renewal - Permits charges only

### Ideas/Need to Do
- Create new page called "Payment History" page under "My Licenses" for providers
  - Different Section Headers, different tables filtered by Transaction Type
- Add button under "My Licenses"
- Add button under "Provider details" page called "Payment Info" 
  - showing a table showing only Provider transactions
  - filterable

**Comment by dianamartin** [comment]
# TESTING License Renewal Fee 
## Option 1: generated by trigger button during license renewal (provider details>start license renewal process)
- Transaction generated at the time of renewal

## Option 2: generated by renewal history, table trigger link
- Transaction generated after renewal

**Comment by patrickm02L** [comment]
@dianamartin will schedule with @johnclary and @ChrispinP to get a technical review on the transactions.

**Comment by dianamartin** [comment]
Meeting scheduled 9/13 at 1:30 pm

**Comment by dianamartin** [comment]
# Sprint Review Feedback 9/10
License & Permit fees
- $1500 for annual license
- Upping permit fee to $40 a month.

**Comment by dianamartin** [comment]
Synced with Mary and Andrew on 9/15, they seemed happy with the new transactions & invoices approach. I showed them the changes I made and said there were more to finish up but wanted to make the redirection we did was okay for the stakeholders.
