### ISSUE TITLE
Add Comments to Fees/Payments Page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7086]
During the sprint review on August 26th, Andrea pointed out the need for a comments section. 

In the spreadsheet that the SM team is using to track Provider information, she is adding a note if providers haven't paid or if something doesn't match. Staff would like to have that functionality for payment information in the app.

@dianamartin indicated we would be able to do this.

**Comment by dianamartin** [comment]
Reached out to Andrea and she said that the "comments" were rare, but they do make then for when transactions are paid weird. 
- She asked that the transaction be editable in every status 
- We'd move the "Edit" button to the far left of the table and keep the invoice stuff to the "right" side

**Comment by dianamartin** [comment]
- [x] Added `Transaction Note` to transaction object table
- [x] Added `Transaction Note` to edit transaction form

**Comment by dianamartin** [comment]
Shared with stakeholders on 9/10 at SMO Sprint Review, no modifications to features
