### ISSUE TITLE
Add ability to create invoices 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7087]
During the sprint review on August 26th, a discussion about how the SM team was generating invoices came up. @dianamartin said that it was possible to create invoices in Knack and demoed an example from Sign Fabrication.

Currently, invoices for permits and impounds are created in-house, then emailed out. Trip fees are created by Finance. 

Because we can create invoices in Knack, adding that functionality to the Fees/Payments page would enhance the workflow for staff who normally create invoices.

**Comment by dianamartin** [comment]
Talked to Andrea 9/3, she will be sending me a current invoice as reference

**Comment by dianamartin** [comment]
Showed stakeholders at last Sprint Review, 9/10. They were excited for the invoices, but I felt like the structure of the invoices was kind of off. I had originally set it up where the user had to go to the: 
- impoundments page and create a new impoundment, then a record rule would automatically create an invoice record
- go through a renewal, go to renewal history and create a transaction after the fact

I revamped the database design after talking with John. I was able to create a new object that connected with all the objects that were a data point and would be added to an invoice.

**Comment by dianamartin** [comment]
Sync'd with stakeholders on 9/15 and they seemed happy with the new invoice approach. Told them I'm still working on the following: 

- 30 day due date, move to renewal due date for License and Permit
- Flat fee $1500 for license renewal - change "Amount Paid"

**Comment by dianamartin** [comment]
- [ ] Added `Renewal YN` 
- [ ] Added `Renewal No`
- [ ] Added `Renewal Due Date`
- [ ] Updated `30 Day Due Date` 
- [ ] Added `Renewal Due Date` to Invoice Details page - hid fields that are blank
- [ ] Added `Renewal Due Date` to Invoice page - hid fields that are blank

**Comment by dianamartin** [comment]
Have sprint review with stakeholders on 9/24, will show the updates.

**Comment by dianamartin** [comment]
Showed stakeholders on 9/24 and they're happy with the changes.
