### ISSUE TITLE
Update Fee Dates - All ATD Fees (1 of 3)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7089]
### Make sure all ATD fee codes have the correct dates so they won't break on 10/1

**This card will be used for the ATD fees - 50255 (SCP Fees ) **

The other two cards are:
50200 ( RW Fees) - #7093
90266 ( SP,C, C8, ZC fees) - #7090

Card 1 of 3

**Comment by Lpriya-LIT** [comment]
The SCP fee lookup table 50255 has no expiration date (end date) , so the fee will not expire.
Verified all the fee procedures in SCP folder as well.

**Comment by TracyLinder** [comment]
Thank you Priya. I'm closing this.
