### ISSUE TITLE
Update Fee Dates - All ATD Fees; SP,C, C8, ZC fees (2 of 3)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7090]
### Make sure all ATD fee codes have the correct dates so they won't break on 10/1

**This card will be used for the ATD fees - 90266 ( SP,C, C8, ZC fees) **

The other two cards are:
50200 ( RW Fees) - #7093
50255 (SCP Fees ) - #7089

Card 2 of 3

**Comment by Lpriya-LIT** [comment]
Expiry date for all ATD fee codes in Lookup - 90266 for SP, C, C8 and ZC folders has been updated.
Commit id - 9ad95e860a98

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder I have sent this over to the DevOps CM Team to deploy to DEV under **SCTASK0165381**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy this to DEV under **SCTASK0165381**

**Comment by Lpriya-LIT** [comment]
Changes has been deployed to Dev,  looks good. 
Ready to be deploy in Test

**Comment by Nadin-Nader** [comment]
## **Approved for TEST deployment**

**Comment by Nadin-Nader** [comment]
**Status:**
Sent to DevOps to Deploy to TEST under **SCTASK0166343**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test, changes looks good.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to be deployed by the DevOps CM Team under **SCTASK0168143**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy to PROD under **SCTASK0168143**

**Comment by Lpriya-LIT** [comment]
Deployed to Prod, Changes look good

**Comment by Nadin-Nader** [comment]
@TracyLinder this has been on PROD for a week with no issues. Closing
