### ISSUE TITLE
Update Fee Dates - All ATD Fees; RW Fees (3 of 3)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7093]
### Make sure all ATD fee codes have the correct dates so they won't break on 10/1

**This card will be used for the ATD fees - 50200 (RW Fees)**

The other two cards are:
50255 (SCP Fees ) - #7089
90266 ( SP,C, C8, ZC fees) - #7090

Card 3 of 3

**Comment by Lpriya-LIT** [comment]
Expiry date for all RW fee codes in Lookup - 50200 has been updated.
Commit id - fd53179d676c

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT i have sent this to the DevOps CM Team under **SCTASK0163844**

**Comment by Nadin-Nader** [comment]
**Status:**
Sent to DevOps CM Team to deploy to DEV under **SCTASK0163844**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV by DevOps CM Team. Please UAT/verify on DEV.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been sent to the DevOps CM Team to deploy to TEST under **SCTASK0164346**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on the DevOps CM Team to deploy to TEST under **SCTASK0164346**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test, changes look good. 
@TracyLinder

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to the DevOps CM Team to deploy to PROD under **SCTASK0168145**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on the DevOps CM Team to deploy to PROD under **SCTASK0168145**

**Comment by Lpriya-LIT** [comment]
Deployed to Prod, Changes look good.

Update - @Sreelatha-BlazeKannan  please let me know when your change to lookup 50200 ( #6842) is deployed to Prod.  I have to promote the data fix commit. 
@Nadin-Nader

**Comment by Nadin-Nader** [comment]
This has caused some errors on PROD and will be reverted and recommitted with a change to the date so that the correct current fee is added until 10/1.
Priya will be reverting the commit and in touch with the DevOps team

**Comment by Lpriya-LIT** [comment]
Commit fd53179d676c has been reverted from Prod.
It has to be deployed only after 6842 is deployed to Prod. 
@Nadin-Nader @Sreelatha-BlazeKannan

**Comment by Nadin-Nader** [comment]
**Status:**
On TEST ready for PROD deployment on 9/30 for 10/1

**Comment by Nadin-Nader** [comment]
**Status:**
Resubmitted to DevOps CM to deploy all the way to PROD UNDER **SCTASK0170455**

**Comment by Nadin-Nader** [comment]
This has gone to PROD and the code fixed.
[9:13 AM] Sureshkumar, Lakshmipriya - Vendor
    Update - Datafix for 7093 is promoted to prod 
​[9:14 AM] Sureshkumar, Lakshmipriya - Vendor
    It looks correct in Prod now
