### ISSUE TITLE
Update Location types

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#711]
Jen and Lewis are going to give us an updated list of locations.

**Comment by SurbhiBakshi** [comment]
As per Jen, 
1. signalized intersections  - https://atd.knack.com/amd#home/signals/
2. School Zones - https://atd.knack.com/amd#home/school-zone-beacons/

**Comment by amenity** [comment]
Well done, @SurbhiBakshi! What's up with those 83? Do we send officers to locations outside APD's sectors? 🤔

**Comment by SurbhiBakshi** [comment]
@amenity , sorry just read this comment, think this slipped due to my earlier Notification settings. Anyway, I am not sure why the locations are outside the Sectors, probably need to ask Jen?
