### ISSUE TITLE
Enhancement - TCP Tracker - Add advanced search fields

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7111]
We need two fields added to the advanced search page:![Screen Shot 2021-09-02 at 12.41.28 PM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/f1addd3d-1f22-40ac-a84f-4ec9f8b011f1)

**Comment by dianamartin** [comment]
- [ ] Add "Submitting Agency" field to "Advanced Search"
- [ ] Add "Department Name" field to "Advanced Search"

**Comment by dianamartin** [comment]
@TracyLinder fields have been added per Peggy's request.

**Comment by dianamartin** [comment]
Messaged Tracy 9/2
>It is done

Tracy replied 9/2
>Thank you so much!
