### ISSUE TITLE
[Bug] Activity log displays UTC timestamps

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7121]
The dates displayed in the activity log are in UTC time. This can be observed in the "Date" column of the activity feed, as well as the timestamp displayed on the activity details page. For example, see below screenshots from project ID 280. Amenity made this change the evening of 9/5, but dates are displayed in UTC time (9/6)

<img width="403" alt="Screen Shot 2021-09-06 at 11 31 03 AM" src="https://user-images.githubusercontent.com/14793120/132245319-c01c9263-dcd3-491b-aa1a-430484f1cec5.png">

<img width="965" alt="Screen Shot 2021-09-06 at 11 30 55 AM" src="https://user-images.githubusercontent.com/14793120/132245259-4a3006f1-e73f-475a-b050-366dccc96aae.png">

**Comment by johnclary** [comment]
@amenity FYI

**Comment by amenity** [comment]
Weirdddd... @sergiogcx took care of this [here](https://github.com/cityofaustin/atd-moped/pull/254), I believe. 

See also @tillyw's [backlog issue for a backend fix](https://github.com/cityofaustin/atd-data-tech/issues/5732).

**Comment by johnclary** [comment]
Ah, interesting. It would seem there's an underlying Moped editor. 

We need to drop the `timeZone` option in [this line](https://github.com/cityofaustin/atd-moped/blob/720083d6d81cf2ffc7b0478b056dadffb0e7984d/moped-editor/src/views/projects/projectView/ProjectActivityLog.js#L102).

```javascript
// sample input date from moped
const date = "2021-04-23T22:42:12.102357+00:00"

// renders UTC datestring
new Date(date).toLocaleDateString("en-US", { timeZone: "UTC" });

// renders local time because timezone offset (`+00:00`) is present in input date
new Date(date).toLocaleDateString("en-US");
```

**Comment by tillyw** [comment]
Looking into this!

**Comment by amenity** [comment]
@tillyw - This is very low priority.

**Comment by tillyw** [comment]
Got it, no problem! I haven't found a solution yet. Please move it to the backlog.

**Comment by mddilley** [comment]
Picking this up since it aligns very closely with https://github.com/cityofaustin/atd-data-tech/issues/9169 and https://github.com/cityofaustin/atd-data-tech/issues/5732. Will test and provide updates.

**Comment by mddilley** [comment]
Continued forward with a front-end fix. See https://github.com/cityofaustin/atd-data-tech/issues/9169#issuecomment-1133130779.
