### ISSUE TITLE
Implement Comment types

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7124]
Comments can have multiple types. So far:
- **Status updates** - made from the "Summary" tab in the "Status update" field #6995 
- **Timeline notes** - made from the "Timeline" tab #6409 — does not need to
- **Internal notes** - made directly on the "Comments" tab using existing functionality

Users can filter — via [outline button UI](https://material-ui.com/components/buttons/#outlined-buttons) — to see comments of a certain type: 
![Comment-types](https://user-images.githubusercontent.com/1463708/133522019-3be0cb0c-d9d2-44ad-8126-2355c48cb626.png)

Also note that the "+ Add comment" text on the button is now simply "Comment" ... Hopefully this will help users understand that they don't have to click the button _before_ typing anything. 

We can link to a filtered list, e.g. the history icon in #6995 can go to a list of "Status updates"

**Comment by johnclary** [comment]
@amenity is this good to go?

**Comment by amenity** [comment]
@johnclary @sergiogcx - good to go now. We can leave off the "Timeline notes" filter until we implent #6409

**Comment by sergiogcx** [comment]
There is a PR for review:
https://github.com/cityofaustin/atd-moped/pull/421/files
