### ISSUE TITLE
Add New Employee Maggie to the DTS Portal

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7125]
This is a notification request to add new employee, Maggie C. to DTS Portal.

- Division: Transportation Engineering
- User Role: Viewer (Unless a DTS team member)
- Home Office Photo - leave blank
- Send an email intro - No

**Comment by dianamartin** [comment]
- Checked system if Maggie had account, she did not
- Created account for Maggie
