### ISSUE TITLE
Update Fee Dates - All ATD Fees; TIA Fees (51060)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7129]
### Make sure all ATD fee codes have the correct dates so they won't break on 10/1

**This card will be used for the ATD fees - TIA Fees (51060)  **

Main card is #6330

**Comment by Lpriya-LIT** [comment]
Expiry date for all TIA fee codes in Lookup - 51060 has been updated.
Commit id - f6fc8eec050d

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been sent to the DevOps CM Team to deploy to DEV under **SCTASK0165269**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on CM Team to deploy to DEV under **SCTASK0165269**

**Comment by Lpriya-LIT** [comment]
Changes has been deployed to Dev,  looks good. 
Ready to deploy in Test

**Comment by Nadin-Nader** [comment]
**Status:**
Sent to DevOps CM Team for deployment to TEST under **SCTASK0166344**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been deployed to TEST. Please go ahead and UAT to make sure all the fees are correctly deployed to TEST

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test, changes looks good.

**Comment by Nadin-Nader** [comment]
**Status:**
Ready for verification before moving to PROD (Developer UAT done on TEST)

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to be deployed to PROD by the DevOps CM Team under **SCTASK0168146**

**Comment by Nadin-Nader** [comment]
**Status:**

Waiting on this to be deployed to PROD by the DevOps CM Team under **SCTASK0168146**

**Comment by Nadin-Nader** [comment]
@TracyLinder Closing this one since its been on PROD for about a week with no reported issues
