### ISSUE TITLE
Prep for VZA Sprint Review #2

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#713]
### Objective 
- Review reporting functionality
- Discuss what to cover in review and build out [agenda](https://docs.google.com/document/d/1qH_Lke-E3R0c5FJcVvFGz0KbVED4-5aHA8vG6UYMPYc/edit#)

### Participants
Amenity & Surbhi, Diana and John optional

### Docs
- [Sprint Review #2 Agenda](https://docs.google.com/document/d/1qH_Lke-E3R0c5FJcVvFGz0KbVED4-5aHA8vG6UYMPYc/edit#)
- [Sprint Review #2 slide deck](https://docs.google.com/presentation/d/1bAQeR7MYqx6QMu0uVdHqjm3-s0j0g-OFs_EsKFp3tPk/edit#slide=id.g6512805fdb_0_198)

------
- [x] Schedule meeting

**Comment by dianamartin** [comment]
Change "Violation" to "Contact"

**Comment by amenity** [comment]
Notes: 
@dianamartin - show Surbhi the new Knack date/time format
"NVA - No Volunteer Available" - maybe call "Unfilled" or "Empty"
"Ongoing" --> "In Progress"
Hours scheduled per location - list will get long, maybe drop down for location type...
