### ISSUE TITLE
Update Fee Dates - All ATD Fees; DS /EX fees ( Multiple lookup tables involved )

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7130]
### Make sure all ATD fee codes have the correct dates so they won't break on 10/1

**This card will be used for the ATD fees - DS /EX fees ( Multiple lookup tables involved ) **

Main card is #6330

**Comment by Lpriya-LIT** [comment]
Expiry date for all ATD fee codes in Lookup - 50050, 50081, 50105 for DS and EX folders has been updated.
Commit id - 3aace92a00eb

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to the DevOps CM Team to deploy to DEV Under **SCTASK0166774**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy to DEV under **SCTASK0166774**

**Comment by Lpriya-LIT** [comment]
Status:
Changes have been deployed to Dev, verified and it looks good. 
Ready to Deploy to Test

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT lets go ahead and move this to TEST

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to the DevOps CM Team to be deployed to PROD under **SCTASK0168152**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on this to be deployed to PROD by the DevOps CM Team under **SCTASK0168152**

**Comment by Lpriya-LIT** [comment]
Deployed to Prod, Changes look good

**Comment by Nadin-Nader** [comment]
Changes have been made successfully and email sent to Stakeholders. closing card

> Good Morning Team,
> 
> Hope you are both doing well. I wanted to reach out to you and inform you that the DS/EX fee date changes are on PROD and have been for several days. I will now go ahead and close that card. If issues or questions should arise, please feel free to reach out to me or Tracy.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> IT Business Systems Analyst
> Data and Technology Services
> ————————————————————————————
> transportation.data@austintexas.gov 🚦 austinmobility.io
