### ISSUE TITLE
Restrict component features to points or lines (but not both)

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7133]
It is currently possible to create a project component with a mix of points and lines. However mixing these geometry types is not compatible GIS.

If we want to display a single component as a map feature in ArcGIS Online, the feature must be comprised of either points or lines, but not both. Also, for the sake of data quality, we probably don't want users to draw, for example, a point which represents a bike lane.

We have already accounted for this is in the `moped_components` data model—there is boolean field called `line_representation` that is `true` when a feature should be represented as a line.

Funcional requirements:
- Show only the appropriate selectable layers and drawing tools depending on the selected component type's `line_representation` value

**Comment by johnclary** [comment]
@chiaberry some more deets below in case it's helpful. Happy to pair on this to get you oriented.

When a component type must be a line, we want to hide the selectable points layer (`Project_Component_Points_prototype`): 
https://github.com/cityofaustin/atd-moped/blob/4007fa676508c8114b54a7c9e5926ce10a33a173/moped-editor/src/utils/mapHelpers.js#L180

And when the component must be a point, we want to hide the selectable streets layer (`CTN`):
https://github.com/cityofaustin/atd-moped/blob/4007fa676508c8114b54a7c9e5926ce10a33a173/moped-editor/src/utils/mapHelpers.js#L133

And here's the function that renders layers from layer config. You can see my conditional rendering based on if the component is a signal:
https://github.com/cityofaustin/atd-moped/blob/4007fa676508c8114b54a7c9e5926ce10a33a173/moped-editor/src/views/projects/newProjectView/NewProjectMap.js#L491

And I think you could modify this function to conditionally hide the point/line draw buttons:
https://github.com/cityofaustin/atd-moped/blob/4007fa676508c8114b54a7c9e5926ce10a33a173/moped-editor/src/views/projects/newProjectView/MapDrawToolbar.js#L19

**Comment by chiaberry** [comment]
components should be restricted, but a single project can have a mix of line components and point components, right?

**Comment by patrickm02L** [comment]
In Dev Sync, Chia pointed out that we currently have the ability draw features on the map before selecting components. In grooming, we discussed making it so that we could prevent drawing features to the map before selecting component. I think we should write another issue for this, rather than tagging it on to this one.

cc: @johnclary, @amenity

**Comment by johnclary** [comment]
@chiaberry correct.

@patrickm02L sounds good, but in that case we should probably implement "prevent drawing features without component" before we do this.

**Comment by amenity** [comment]
@chiaberry - here's the new one: https://github.com/cityofaustin/atd-data-tech/issues/7213
