### ISSUE TITLE
Add New Employee Gabriel G. to the DTS Portal

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7138]
This is a notification request to add new employee, Gabriel G. to DTS Portal.

Division: Right of Way
User Role: Viewer (Unless a DTS team member)
Home Office Photo - leave blank
Send an email intro - No

**Comment by dianamartin** [comment]
@ChrispinP can you do this one, thanks!

**Comment by ChrispinP** [comment]
Gabriel added to DTS Portal
