### ISSUE TITLE
Implement design refinements to Material Table in some random places 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7139]
### Apply min-width 8em to dropdowns:
![Screen Shot 2021-09-09 at 3 36 21 PM](https://user-images.githubusercontent.com/1463708/132759009-0a4a5d96-b9c2-4e07-88a7-4ab61bc20c56.png)

- [x] Project phases - phase name, subphase name
- [x] Project milestones - milestone
- [x] Project team - ~name~, role
- [x] Funding sources - source, program, and status columns
- [x] Files - type

### Mark required fields with "Required" in helper text
![REquired-field-material-table](https://user-images.githubusercontent.com/1463708/132759048-ee707754-99ad-44e7-b81b-bbff697e4b0f.png)

- [x] Project phases - phase name
- [x] Project milestones - milestone
- [x] Project team - name, role

### Use [outline icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aedit%3A) for pencil
- [x] Project phases 
- [x] Project milestones 
- [x] Project team 
- [x] Funding sources 
- [x] Files 

### Remove date-clearing trashcan
Unnecessary custom code, at this point. :\
- [x] Project phases - start date, end date
- [x] Project milestones - completion estimate, date completed

### Misc
- [x] Add padding to heading on "Funding" table - [before](https://user-images.githubusercontent.com/1463708/150427788-655f7743-4650-41a3-9e62-d7dec9ae72b0.png) / [after](https://user-images.githubusercontent.com/1463708/150427836-a4e83698-cff0-470d-8512-14ea79a1b6b1.png)

**Comment by amenity** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data--Technology-Services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/7139?planning-poker) with ZenHub @chiaberry @mateoclarke @sergiogcx

**Comment by tillyw** [comment]
Closed with https://github.com/cityofaustin/atd-moped/pull/532
