### ISSUE TITLE
Clear out Scoobi test data from MDS database

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7146]
Scoobi would like to carry out some test runs of their devices in Austin in order verify MDS is 100% working. 

In order for them to test, we need to make sure that the dummy data that we tested with earlier is cleared from the MDS database. 

Once the MDS database is clear we'll need to notify Andrea M. on the Shared Mobility Team to let her know Scoobi's MDS is good to go.

**Comment by sergiogcx** [comment]
For context, we have about 5955 trips in the database, and 1985 schedule 1 hr. blocks completed. I will be deleting all the trips, as well as resetting the status of those hour blocks:

<img width="678" alt="2021-09-10_14-16-49" src="https://user-images.githubusercontent.com/5282430/132899362-489e7151-28a1-4e5c-981a-3f67eeeb8486.png">
<img width="784" alt="2021-09-10_14-03-52" src="https://user-images.githubusercontent.com/5282430/132899367-f937f80d-9045-4686-b5e6-f051816b7801.png">

**Comment by sergiogcx** [comment]
Gone:

<img width="392" alt="2021-09-10_14-33-50" src="https://user-images.githubusercontent.com/5282430/132901131-7b308276-06ec-4508-afdf-686b3cbf98e1.png">

**Comment by patrickm02L** [comment]
Excellent!

**Comment by patrickm02L** [comment]
Sent an email to Andrea M. letting her know that the Scoobi MDS database was clear.

**Comment by dianamartin** [comment]
John asked me to delete Scoobi Test records in the SMO Knack app
- 2 records
- July & August: Record ID `80` and `84`
- Deleted

**Comment by patrickm02L** [comment]
@johnclary  realized that we needed to delete the Scoobi trips from the Socrata dataset as well. He wrote a script to isolate records by `vehicle_type = "moped"` to delete them row by row.
