### ISSUE TITLE
School Beacon Follow-up Questions / Data Clean Up

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#7148]
Charles Z. reached out and is looking to finish his tasks by the end of the week of 9/13. He mentioned there is no immediate rush but if you could follow up with him on Monday that would be great.

1. Wants to verify that the School Zone Beacon data he has been working with has been/is being pushed to DataTracker.
2. Wants to know if there is anything else on his end that needs to be completed.

**Comment by jaime-mckeown** [comment]
Go through data and clean up before talking with Charles tomorrow.

**Comment by jaime-mckeown** [comment]
- Charles called to discuss the email that I sent yesterday. He will verify the SZB this week and reply with answers.
- He is also getting an error when trying to login to Collector that started this week, will be sending a screenshot.

**Comment by jaime-mckeown** [comment]
- Charles called to discuss the items I sent to him via email. He has fixed most, we fixed a couple while on the phone. He just needs to verify the Web-IO, then will let me know.

**Comment by jaime-mckeown** [comment]
- Web-IO verified, Exposition @ Windsor changed to Exposition @ Westover, changes complete on SZB
- Started going through SZB to check the addresses, most are wrong and need to be fixed.

**Comment by jaime-mckeown** [comment]
Completed cleanup of data, let AMD know that everything is good to go, moving forward to the next phase of the project.

**Comment by jaime-mckeown** [comment]
@amenity the GIS piece for the SZB project is complete. Below are links to the 2 feature layers:
SZBs: https://austin.maps.arcgis.com/home/item.html?id=9fb0da0611414ae7a5ed64864ca0e772
WEb-IOs: https://austin.maps.arcgis.com/home/item.html?id=7a47b6cdf5a441759cd07b9df7148133

**Comment by amenity** [comment]
Thanks, @jaime-mckeown !
