### ISSUE TITLE
Meeting: 311/Knack integration discussion

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7153]
Attendees: Stephanie, Diana, John, Chandra, Bill
Continuation of discussion on 311 SR integration with Knack
Agenda
-	Control Panel Reports 
-	Resources 
-	ATD Needs 
-	Next Steps

**Comment by moorerst** [comment]
311 team rescheduled meeting to 9/20

**Comment by dianamartin** [comment]
# Diana's Notes

- [ ] Add Chandra - to google sheets

# Paging Change
- user account 
- by completing the activity
Field Mobile module - requires license
3 SR types set up for that

MS Internet Explore - needs to have MS Edge

# Action Items
- Chandra to set-up meeting with ESB, 311 and ATD
- Bill to update Control Panel Reports - so updates are going live tomorrow 9/21

**Comment by moorerst** [comment]
Meeting with ESB team, 311 and ATD for 311/Knack interface discussion scheduled for Oct 11
