### ISSUE TITLE
Meeting: Go Live for HR Forms and Email Notifications

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7154]
Attendees: Stephanie, Diana, Linda, Meredith, Nathan

Agenda:
let’s check in before we Go Live with the HR Forms and Email Notifications.

Administrative task to complete prior to Oct 1 Go Live:
Configure settings
Delete test records
Clear Hire Date
Reset Supervisor

Update on Banner integration

Scheduled 9/20

**Comment by dianamartin** [comment]
# Diana's Notes
- Linda found a question missing on the Supervisor Survey - 30 day 
- Add this question to the Supervisor 30 day form
`Was your performance evaluation, called the SSPR, conducted in the last 30 days?`
-  Yes
- No
`If not, what delayed it?`

# Test records
- Can go ahead and delete the test records and do clean-up

# 4 Employee Category Types to track
- full time
- part time
- temporary
- interns
- no Contractors

# Timeline
- October 1st is not a hard deadline
- Shooting for more of a mid-October time frame
- To time it up with supervisor sessions

## Example time line - future process
10/10 Beginning of pay period
10/14 NEO
10/16 - CTM to export emails
10/17 Run script

## Employee Class
01
02
03 - none
04 - none
08 - Part Time

**Comment by dianamartin** [comment]
Q1.30
Q2.30
Q2.30.2
`Q3.30.01`
`Q3.30.02`
Q3.30 --> Q4.30
Q3.30.1 --> Q4.30.1

**Comment by moorerst** [comment]
Contacted CTM to schedule the upload of ATD employee data to G: anytime on Saturday beginning 9/25

HR may need to reschedule ATD NEO sessions to  week two to ensure the employee file has been updated 

September 26th pay period will be a good test run
Should receive a list of employee changes from HR and will compare to the script. Can make adjustments for next pay period.

**Comment by moorerst** [comment]
New question added to the Supervisor 30 day survey. Approved by stakeholders. Good to go!
