### ISSUE TITLE
[ROW - TCP] Review Multiple Submission Attachments Feature

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#7156]
### Objective 
Review the Multiple Submission Attachments feature for TCPs 
#3867 

### Participants
- Chrispin P
- Diana M
- Darren U
- Robert A

### Agenda
- [x] Make sure feature meets need
- [x] Make sure users know how to use feature
- [x] Make any adjustments to feature
- [x] Plan to enable feature (when/how?)

Testing: Sept 20th - 24th
Go Live: Sept 27th
------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes
-  ROW Portal Demo
- TCP Details
- Submissions Table (several)
  - Details icon (Submission Details)
  - Details column will be on the left 
- Submission Details
  - Add Row - rename "Add Content"
Q: Add Comment with Attachment
- Makes sense they're together

DEMO
- Creates test TCP record
- Submission 1 is created
- Submission Details
  - Adding Document
  - Adding Mark-up
Currently: only attach the first revision and last revision, but the the individual revisions.

Bug in demo
- The attachment is not showing up

Knack Attachment 250 mb
- Plans (PDF)
- CAD Drawings
- Word Documents

**Attachment Categories**
- [ ] `Plans` - default
- [ ] `Specifications`
- [ ] `Other`

"Due Date" field
- [ ] Move to second column 
- [ ] Bold the field

Rename
- [ ] Submission "Content" --> Submission "Attachments"
- [ ] Add "Row", Add "Attachment"

"Remove" button
- Submission is completed 

Timeline
Modifications by 9/17
Testing 9/20-9/24
- Delete test records
- 9/27 Implementation

**Comment by ChrispinP** [comment]
all action items were completed, test records removed. Multiple attachments now live
