### ISSUE TITLE
Meeting: Kick off for Robin pilot with Information Security Office

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7157]
Attendees: Stephanie, Diana, Wendy, Tracy, Karl, Bart
Did not attend: Karl, Bart, Stephanie
Attendees: Wendi, Tracy, Shelby, Diana

Items for Discussion:

- Which office locations you would like to have participate in the pilot program
- Acquire the most recent floor plan of the office space so we can work with Robin to get it in the system – If you have this available please send to me 
- Identify the distribution list that will have all the users you need to access the Robin software (using single sign on)
- Identify which shared resource calendars (meeting rooms) you want to have in Robin
- What groups/divisions might be participating (ex. 1-4 work groups: office staff, field staff, etc..)
- Do these groups have different needs for hoteling – access on certain days/time etc..
- Who will be your facility Administrator(s)

Scheduled 9/22

**Comment by dianamartin** [comment]
Notes were take in a [google doc](https://docs.google.com/document/d/1nZ2jF4uva45jTH66zJvoeoV7pEY088XROB8Ek9uSLE0/edit?usp=sharing) - ISO Kick-Off

**Comment by moorerst** [comment]
Will schedule follow up meeting for training after the floorplans are uploaded.
