### ISSUE TITLE
Attend TNRIS GIS Conference

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#716]
Add notes from talks that we attend at the conference.

**Comment by jaime-mckeown** [comment]
Vision Zero based talk:

**Using a Graph-based Database can Improve Data Modeling and Analysis - Washington DC DOT**
- Started as a safety data project
- Crash analysis realm was difficult to use GIS for analysis, understanding why a crash happened in complicated
- Output of analysis is the 20 most dangerous intersections
- They then migrated to a top 20 most dangerous roadways displaying as a heat map
- Find a way to model cross section data
    - Types of lanes
    - Direction of travel
    - Width
- With more complicated questions, you need a network
    - Start with roads and highways, segment into more usable pieces
        - Blocks - created between block intersections
        - Sub-blocks - created between sub-block intersections (between alleys, driveways, etc.)
- Overview of Graph Databases
    - Graph theory is all about relationships
    - Graph database is a collection of things where the relationships between things are just as important as the things themselves
    - Social media uses graph databases
    - Searching for fraud uses graph databases to pinpoint
    - Graph is composed of 2 elements
        - Nodes
        - Edges
    - ArangoDB is being used for graph database
        - Node documents - crash data
        - Edge documents - street data
    - Need to be careful and thoughtful on how to build the database
    - Attributes available for queries - connect segments, intersections, crash data, etc.
    - Build query to see intersections on the map
        - Creates a cross section viewer
        - Streetmix.net to see cross sections
    - Graph database originates from an ETL pipeline - enterprise GIS, weekly updates to graph database
    - Cross section data collection was phase 1 (1 year)
    - Modeling phase (in progress now)
    - Crash data is received from Police and placing an exact point for collision is not the highest priority (sounds familiar)
    - GIS is the source of the data, but not the only part needed for the analysis
    - Graph databases are extremely flexible, expandable, changeable
    - Adding more criteria is easier to do using a graph database

**Comment by jaime-mckeown** [comment]
**State of the State - Federal updates**
- Geospatial Maturity Assessment
    - TNRIS is working on this
    - TX is # 13 on the list (A-), 2 years ago TX would have probably been a D category
    - Coordination - how do we coordinate among the state, community meetings, website, etc. (A-)
        - Data Products
            - Address Points - new dataset for TX last November (B) - over 10 million points gathered, still some issues with the dataset
            - Cadastral Mapping Parcels - (B+) was put together quickly
            - Elevation - (B-) flights in place, 50% available data for the state
            - Ortho leaf-off - (A) top notch program, TX imagery services are going strong
            - Transportation - (B-) progress being made for improvements
            - Geodetic Control - (B-)
            - Government Units - Political, Taxation, etc., not doing well in this category (didn't get the letter grade)
             - Hydrology - (B-) going to work on improving this category
             - Ortho leaf-on - (A) using NAIP
    - TNRIS lost funding in 2011, receiving funding back during last legislature to be fully funded
- National Address Database & Next Generation 911
    - PSAP - Public Safety Answering Point
    - Will be moving to a "private internet" for public safety
    - ESRP - Emergency Services Selective Router - calls routed through, location sent through router using GIS data in the database
    - Data will be refined down to building, floor, unit, room, mile post, etc.
    - GIS Data Model has been created so all organizations create identical schema
    - Required GIS Layers
        - Road centerlines
        - Site / structure address points
        - PSAP Boundaries
        - Emergency Responder Boundaries (Law, Fire, EMS)
        - Provisioning Boundary (the area of GIS provisioning responsibility)
    - Universal Unique IDs must be included for all required GIS data elements in NG 911
    - Data Model - field description, domain, examples
    - Automated GIS for Public Safety
         - Phone call x,y will be compared to PSAP boundary layer, geometry and accuracy is vital for system to work
    - FCC new accuracy requirements
        - Outdoor horizontal accuracy (x,y)
        - Indoor horizontal accuracy (x,y)
        - Vertical accuracy (z)
        - Defines dispatchable location (subaddressing)
        - National Emergency Address Database (NEAD)
    - Site Structure Address Point (SSAP) Methodologies
        - On a parcel
        - Based on property access
        - Based on a structure
        - Based on a group of structures
        - Based on exterior structure entry
        - Based on interior locations within a structure
    - Consumable for REST services
    - NAD Minimum Content Guideline
        - Address
        - Geographic location of the address
        - Metadata about the address
- State Plan Coordinate System of 2022
    - Optimally would be 70 zones for TX
    - Now talking about 40-45 zones for TX
    - This transition will be more detailed than the last transition
    - Mathematical computation for new areas, but local landmarks need to be considered (airport not cut in half, etc.)

**Comment by jaime-mckeown** [comment]
**State of the State - state updates**
- Lidar data for TX
    - TX has 100% lidar coverage - statewide coverage is Fall 2020 - Spring 2021
    - Remaining 2018 federal lidar projects will be available this winter
    - Many areas the data is getting old, original coastal FEMA data has been re-flown
    - It will continue to be refreshed over time with continual updates
    - StratMap Program was re-funded
        - Looking into additional point cloud classifications for federal points to match state datasets
        - Looking into inland bathymetric data
- Imagery updates in TX
    - Statewide ortho-imagery
        - NAIP - USDA
            - Flown every other year, last acquired 2018
            - Down to 0.6 meter resolution
            - Leaf-on
            - Color and color infrared
            - 2018, DOQQs available, no CCMs yet (mosaic)
        - TX ortho-imagery program TNRIS
             - 0.5 meter resolution
             - Leaf-off
             - Color and color infrared
             - Last acquired in 2015
         - TX Imagery Service TIS
             - Google and AppGeo
             - 6 inch
             - Leaf-on/leaf-off mix
             - Natural color only
             - Licensed subscription for TX.gov users
             - Ongoing acquisitions
             - Urban is flown annually, rural not as often (3-5 years)
             - Image updates from Google are ending 8/31/2020
             - Looking into new options for continuing program through a new vendor
             - TxDOT brought up possibly buying own aircraft and sensor system, need to do a cost analysis, weekly meetings on-going
                 - With this option, the data can be made publicly available
- Statewide Land Parcels
    - Appraisal districts maintain parcels in TX
        - They use CAMA software in TX, CAMA data joined to the geometry in GIS
        - Over half of counties in TX don't have inhouse GIS, contract out to maintain the GIS side of parcels
        - 31 counties that TNRIS could not get parcel GIS data for, reached out to AppGeo for help with those counties
        - TNRIS has the state-wide parcels available for download on the datahub
            - Metadata is complete, fields has descriptions
        - Tnris.org/stratmap

**Comment by jaime-mckeown** [comment]
**Migrating Python Add-Ins from ArcMap to ArcPro (TXDOT)**
- Configure ArcPro under Options without coding
- Custom Tools and solutions using Pro SDK, C#
- Esri Documentation
    - Community Samples
    - Pro Snippets
    - GeoNet
    - GIS Stack Exchange
- What you need
    - Visual Studio 2017
    - ArcGIS Pro
    - ArcGIS Pro SDK - downloaded through Visual Studio
- Lessons learned
    - Log Bugs
    - Test first!
    - Try/Catch Statements
    - Breakpoints/Debugging
    - Communication/Collaboration
    - Learn Visual Studio

**Comment by jaime-mckeown** [comment]
**Esri Web GIS**
- Who is your audience
- Who might reference or link to the map
- Plan for an unintended audience (social media, news, etc.)
- What is the intended experience
    - What is being communicated
    - What device will users be viewing it on
    - What data and visualization are important
    - How should the user interact with the map
- What is the performance expectation
- Plan for your app to go viral

**Comment by jaime-mckeown** [comment]
**ArcGIS Arcade Presentation - Jordan Carmona, McKinney, TX**
- Arcade is an expression language
- Written more like JavaScript, fancy Excel
- Does everything on the fly
- Demo - derived fields, sexier fields, symbolization
- Demo - link automation, simplifying data
- jcarmona@mckinneytexas.org
- Not a lot of Arcade help yet, Esri documentation can help, as well as on GeoNet as Esri staff is watching for Arcade questions

**Comment by jaime-mckeown** [comment]
**Programmatic Metadata Augmentation - Michael Schensky, UT Austin**
- 60,000 datasets needed metadata populated for the portal for UT (scanned map rasters)
- There was no existing metadata in GIS format standards
- Limited metadata for individual datasets, more available at collection level
- Had to use old arcpy 2.x version for more options with working with metadata in python
- GeoBlacklight - open source product that universities are using to share data

**Comment by jaime-mckeown** [comment]
**Providing Roadway Match Points across Multiple Jurisdictions - ACC Inc.**
- ACC Inc. - ACC Incubator for Professional skills to help newly graduated students to procure real world skills to help them get jobs in the private/public sector
- 911 Geospatial Data Assessment - ACC Inc.
- 50+ county reports submitted since 2016 to help create a statewide street centerline for statewide 911 project
- Next Generation (NG) 911 Roadway Match Points - have created a statewide road network for 911

**Comment by jaime-mckeown** [comment]
**Tribal GIS for Transportation Planning - Atkins**
- TxDOT Potential Archeological Liability Maps
- TX Archeological Sites Atlas
- TxDOT Early Tribal Coordination Tools
- Tribal Features
    - Discrete locations
        - Landscape features - landscapes, springs, water bodies
    - Non-discrete locations
        - Sacred sites
        - Village sites
        - Trails and traces
        - Crossings
        - Hunting grounds
        - Habitats
    - Each tribe will have its own custom dataset
    - Feature sources:
        - Oral histories - primary source of information
        - Recorded histories
        - Georeferenced digitized maps
        - Other sources approved by the tribes - foundation of data is trust
    - Feature capture
        - Recorded from georeferenced and non-georeferenced maps
        - Attribution includes date, source, and ground condition correlation (how closely the feature location correlates with the feature on the ground)
        - Features are approximated, restricted or excluded at tribe's discretion
- Project status
    - Initial consultation - 27 tribes have ancestral connections to TX
    - Pilot project
    - Additional work - 12 tribes have expressed interest in participation in project

**Comment by jaime-mckeown** [comment]
@johnclary I've added my notes from the conference to the issue if you're interested in the topics that were covered.
