### ISSUE TITLE
Request to add new employee, Andrew A. to DTS Portal.

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7165]
This is a notification request to add new employee, Andrew A. to DTS Portal.

•	Division: Smart Mobility
•	User Role: Viewer (Unless a DTS team member) 
•	Home Office Photo - leave blank
•	Send an email intro - No

**Comment by ChrispinP** [comment]
Andrew added to DTS Portal, complete
