### ISSUE TITLE
Request to add new employee, Ramon G. to DTS Portal

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7166]
New Employee, Ramon G. was added to the Human Resources Manager application on 09/13/2021. 

This is a notification request to add new employee, Ramon G. to DTS Portal.

•	Division: Office of the Director
•	User Role: Viewer (Unless a DTS team member) 
•	Home Office Photo - leave blank
•	Send an email intro - No

**Comment by ChrispinP** [comment]
Ramon added to DTS Portal, complete
