### ISSUE TITLE
Request to add new employee, Lance C. to DTS Portal.

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7167]
New Employee, Lance C. was added to the Human Resources Manager application on 09/13/2021. 

This is a notification request to add new employee, Lance C. to DTS Portal.

•	Division: Arterial Management
•	User Role: Viewer (Unless a DTS team member) 
•	Home Office Photo - leave blank
•	Send an email intro - No

**Comment by ChrispinP** [comment]
Lance added to DTS Portal, complete
