### ISSUE TITLE
Publish signal studies dataset to socrata

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7168]
Publish signal studies data from Data Tracker to [this Socrata dataset](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-and-Pedestrian-Signal-Evaluations-BETA-/fnxd-mtmb) so that they can be kept current for the [new dashboard](#4383).

**Comment by amenity** [comment]
@johnclary - still in progress?

**Comment by johnclary** [comment]
Reopening b/c this needs to be deploy to prefect.
