### ISSUE TITLE
Discovery: Citybase online payment system

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7179]
Get understanding of how Citybase online payment system works for Banner's Payments.

Who should we meet with?

**Comment by moorerst** [comment]
@johnclary will make contact and provide introductions

**Comment by moorerst** [comment]
Mark C and Amber R are the contacts
John could you set up a meeting so we can talk through this.

- In general once we decide to move forward we will need to agree to a Statement of Work. 

- Then it is a matter of agreeing on timing and getting a commitment from ATD for resources (or vendor if that were the case) to make the necessary changes to your system. 

- Then we would gather information for configuration of the Citybase system for ATD

- Citybase then builds that environment

- ATD builds to connect to that environment

- we test

- sign off

- go live

Yep that was at a very high level and at best 

- I expect this to take at least 3 or 4 months from beginning to end. 

- A couple of items we will definitely want to know up front is the volume of transactions on a monthly basis and an average dollar amount per transaction. 

- I can also talk through cost with ATD at the meeting and we can of course talk through the process in greater detail and answer questions ATD may have.

**Comment by dianamartin** [comment]
@moorerst Should we set-up the meeting on behalf of John since we're doing the discovery and invite him of course?

**Comment by moorerst** [comment]
meeting scheduled for 9/30.
Per stakeholder the approximate number of transactions is 5-10/wk
Banners have a different cost depending on the type of Banner (over the street, lamp post)

**Comment by dianamartin** [comment]
# Meeting with CTM - discussion about CityBase
## Discussion about Street Banner Program being interested

Attendees: Mark C, Jim M. (CityBase), John, Diana

Next program: RPP to do ePayments
Annual permits, renewals, day passes (ad hoc purchases)
No online payments 

Designing the payments
Passing the information 
Tracking what the person paid for
- Accounting line distributions - automatic reconciliation
- Making sure we know what funds 

City is each service cost
Ex. $140 of it

V/MC 1.85%
AMX 2.2% 

We need to discuss how to collect the fees
- Customer to pay fees or internal stakeholder to pay fees

CityBase to write Statement of Work
- What data they're getting
- 

Payment page that accepts an order
- Customer will see order details
- Card or Check
- CityBase processes the 
- Get payment to V/MC
- Update Knack with all the accounting codes

Back and Forth API conversation
Create JSON string
- Text 

Send to end point at CityBase
- They read it
- We send to URL 
- Send user to URL
- Sent back Post to to say that the person paid for AMEX

Call back to Knack - can't control how we receive the POST request
Parse the response

Mark has the call back information that ATD needs 
- example of callback

Knack has an API

Payment Confirmation screen 
- Continue button - send them back to (Knack)
- If user doesn't click "continue" they don't get back to Knack

They get sent back, post back, sent directly back to Knack
Knack would have to receive the API call

Could pass an off-token, that off token used in CityBase and authenticate an API request

Do share a "key", unique hash, use key to share to recreate the hash
- Can recreate the hash

Send custom parameters and get them back in the POST
Design the information
- Invoice Number
- Payment token

J's Q: Post back - the web client? or back end server from CityBase (coming from city base's server)
Configure that with a static token
Whatever you send to CityBase will get send back

Can you install a certificate on CityBase's side? Will share a (secret/key), CTM saves it in the database. Uses that as a verification tool. API get hits from other things that aren't CityBase. Helping weed out the information. 

Other ways to make it work with CityBase
- this one works the best for the city
Real time, near real time. 
Customer pays immediately, information is back immediately

CityBase Integrations

Lobbyist Payments- City Clerk's Office
Hotel Tax System - taxes that hotels and short term rentals, they have to pay taxes
HR is going live 
  - Employment Expos - Dell/Samsung/Tesla (big employers) - pay to get a spot in the employment expos
 Peer Request system - Law - In the middle of the build
  - Public Information request (city can charge for PIR request if it takes a lot)
Alarm Payments - In the middle of the build
- Alarm system on the property, pay a regular annual fee
- false alarms, get some number of false alarms
- sent out the police

5-9 other projects in total
Public Works want to come on
Other departments want to get on

Just recently Statement of Work, Austin Public Health
- Not tackling this until building (before Nov or Dec, even in Jan)
- Currently load hopefully in Nov.

DTS will struggle with bandwidth too
Need to tackle the real mechanics and go through the handshakes

BIG ONES
- AMANDA has to move into CityBase
  - Heard they did the portal upgrade, 
- EMS
- Library - not high dollar, but high volume

Statement of Work
- Does take 2 months, can take up to 2 months
Timeline? Pre-holiday season
Meet internally - need to start meeting
Once Statement of Work is happening can add to Project Management calendar

Service fees for the credit cards
Payment Types, ACH, Credit Cards
What kind of integration  
- API based?
- build a file, who they are and what they owe

Library has a middle ware they run
- Library, interesting IT space (Bob B.)
- One system that runs their check-ins/out/late
- Where the books are

They built a system they made in-house

Secret/Key - what the token looks like getting back from CityBase?
- Mark can have a discussion about that

BEST PRACTICES
- Agree to a time, getting the engagement from the departments 
- Department can commit to this, focus and get this done
- DevOps at the city, every day work and extra projects
- Hard on the vendor to get commitments from the City

Talk to Finance as well to determine their preferences

**Comment by moorerst** [comment]
Follow up meeting scheduled 10/13
Closing this issue
