### ISSUE TITLE
Rename "Requestor" to Requester" in AGOL, Knack, and Integration

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#718]
@alan-deanda let me know when the feature service is updated and I'll take care of the Knack stuff. Thanks!

**Comment by alan-deanda** [comment]
@johnclary  I've made the update in AGOL

**Comment by johnclary** [comment]
@johnclary fix the integration.

**Comment by amenity** [comment]
@johnclary - ping. 🛎️

**Comment by johnclary** [comment]
This is done!
