### ISSUE TITLE
Create Audit Log for each of the Mobility Providers

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7180]
User can review all the potential transactions that they want to invoice. 

Create a page that shows all the "data points."

**Comment by dianamartin** [comment]
Repurposed the "Renewal History" page, had called it "Audit Log" but after syncing with the stakeholders it didn't seem fitting. 
- Renamed to "History"
- This page has:
- [x] archive licenses
- [x] permits
- [x] archive permits
- [x] monthly trips
- [x] impoundments

**Comment by dianamartin** [comment]
Have sprint review with stakeholders on 9/24, will show the updates.

**Comment by dianamartin** [comment]
Showed stakeholders on 9/24 and they're happy with the changes.
