### ISSUE TITLE
Identify CTN Field Usage

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#7182]
This will help identify which fields are not being maintained and should be considered for removal

**Comment by johnclary** [comment]
@andrewshensky let us know where you put your workbook

**Comment by johnclary** [comment]
@jaime-mckeown @alan-deanda please review the workbook in the atd-dts-geospatial team team

**Comment by andrewshensky** [comment]
@jaime-mckeown @alan-deanda @johnclary I was thinking it may be best to go through this process of cleaning up the CTN prior to putting the CTN into a dataset in MAINT. Once we have identified the necessary fields, we can push a cleaned version to a new dataset in MAINT where it can live with intersection points, topology, etc. That way we can leave the CTN in its current form in MAINT as a legacy copy while the new version gets established in the new dataset. Let me know if you have any additional thoughts or comments.

**Comment by johnclary** [comment]
New CTN has only the fields identified in teams channel. We can review the fields on an ongoing basis.
