### ISSUE TITLE
Determine Workflow for Updating Intersections from CTN/Incorporate into Street Segment Updates

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#7206]
As street segments are updated, we will need to update intersections as well prior to exporting as vector tiles. This should be included as part of the monthly street segment update process.

**Comment by johnclary** [comment]
Andrew's proposed process:
- Take segments
- Generate points 
- Along segments
- take endpoints
- remove duplicates
- capture x/y for remaining points
- dissolve
- select by location that aren't dupes
- Result is new intersections plus locations that have moved
Need to update/append and republish CTN point tiles
