### ISSUE TITLE
[Spike] Power BI Gantt chart with Moped timeline data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7217]
- [Abilene Trail in Moped](https://mobility.austin.gov/moped/projects/19?tab=timeline)
- [Data export](https://docs.google.com/spreadsheets/d/1UGCbn42FjTPKedx1bpSZQLcUN9n81OrhX32foGVmXH8/edit#gid=0)
- [Power BI dashboard](https://app.powerbigov.us/groups/me/reports/37d4e681-2d83-48b2-a24e-12c6014b165d/ReportSection?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f)

**Comment by amenity** [comment]
@Charlie-Henry - should I put this in the backlog?

**Comment by Charlie-Henry** [comment]
@amenity I've been taking a look this week if this is a thing we could do

**Comment by Charlie-Henry** [comment]
There is a service called [Power BI Embedded](https://azure.microsoft.com/en-us/services/power-bi-embedded/#features). Supposedly this is included in our Pro subscription but we will need to set up an Azure App ID where there may be cost associated with it?

[Here is the step by step setup.](https://app.powerbi.com/embedsetup/AppOwnsData?session_id=82e9947c-1a3d-4bff-ae18-8583147eda49)  I don't have the authority to create an azure web application.

We would likely use the left column here:
<img width="724" alt="Screen Shot 2022-06-13 at 3 26 34 PM" src="https://user-images.githubusercontent.com/30810522/173439339-72fc0faa-d3d5-4180-8290-cb1dca6231ad.png">

Major problem I see with this approach is the database. I don't see how we would create a live connection to our dataset. It looks like the only supported connection is through an [Azure data warehouse](https://www.epcgroup.net/power-bi-embedded-supported-data-sources/).

We could set up automated refreshing of this dataset on a schedule but it would be out of sync whenever a user made a change.

I think this is something that could be really useful for a dashboard-type page where you don't really care about the staleness of the data and are more looking at monitoring trends and what work has been completed.
