### ISSUE TITLE
Meet w/ Ronnie

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#723]
Scheduled for 10/22: [Notes](https://docs.google.com/document/d/1L7LteyQHm-RA5F-p0Zcy-85hN-V29eLWLh1Mwh-d9b4/edit)

Attendees: Ronnie, John, Ray, Johnny and Diana

**Comment by johnclary** [comment]
[Notes](https://docs.google.com/document/d/1L7LteyQHm-RA5F-p0Zcy-85hN-V29eLWLh1Mwh-d9b4/edit)

**Comment by dianamartin** [comment]
### Outstanding Tasks

- [ ] Inventory Request Form: remove FDU input
- [ ] Request Approval: Automatically set approval date and remove form input
- [ ] Filter task order selection by ‘active’ only
- [ ] Remove date autopopulate on #OC and let staff enter the whole thing, but do validate the length. Never an alpha character in the OC#. It’s all numbers. This should be set up as a text field though!
- [ ] On transaction report: show the transaction amount, not the quantity, which will show negative numbers for issuances and positive numbers for returns, restock, etc.
- [ ] Rename “Order” transaction type as “Request”
- [ ] Rename FDU # to “Object #” on new inventory item page
- [ ] Sometimes we need to override the object number, and we need to populate that object number on the transaction, and that’s where it’d be overwritten
- [ ] Need to make object code available in transaction reporting
- [ ] Show a warning or restriction when a requester is trying to a quantity that is greater than what’s on hand
Ideal world: don’t allow multiple checkouts for same location. Requiring work order for inventory request should fix this

**Comment by dianamartin** [comment]
Need to create issues for these new changes

**Comment by dianamartin** [comment]
@johnclary Went through an updated the application with the changes we discussed. If we could review these changes, I want to make sure I'm not missing any functional things.
