### ISSUE TITLE
Review state of existing Signs and Markings AGOL/Socrata/Knack data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7234]
Spreadsheet [here](https://docs.google.com/spreadsheets/d/1PrllmMjYJ6HkiudUTLEIVodclPVA6daW/edit?usp=sharing&ouid=109109021747362399747&rtpof=true&sd=true).

**Comment by amenity** [comment]
@dianamartin please upload the spreadsheet [here](https://drive.google.com/drive/u/0/folders/1gUjDrU4H7d_D7xYKK8avTBkTQG0vRUr4).

**Comment by dianamartin** [comment]
@amenity @ChrispinP Spreadsheet uploaded `Signs and Markings Fields - DataSources.xlsx`

**Comment by ChrispinP** [comment]
@dianamartin I completed the first tab in the spreadsheet for work_order_signs. Am I only matching the AGOL & Open Data fields or do I need to list all Knack fields?

**Comment by dianamartin** [comment]
@ChrispinP we're doing the whole list of datasets

**Comment by johnclary** [comment]
spoke with @ChrispinP about this just now. putting on deck

**Comment by ChrispinP** [comment]
This is now complete, emailed a completed version to Christina/Lauren.

Pending closure

**Comment by ChrispinP** [comment]
Christina responded and is happy with the data. Closing

**Comment by johnclary** [comment]
thanks @ChrispinP !
