### ISSUE TITLE
[MEETING] Builder Huddle to assess level of effort  - TIA Historical Mitigations

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7235]

**Comment by TracyLinder** [comment]
@amenity I don't think we started charging mitigation fees in AMANDA until Oct 2020. We should be able to pull data for after 10/2020

**Comment by dianamartin** [comment]
We could close this issue, right?

**Comment by amenity** [comment]
@dianamartin yes. Closing and removing all the automatically added sprints.
