### ISSUE TITLE
QA/QC Inventory Item List

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#724]
We need to make sure we have all of the inventory items setup correctly in the system.

Todo:
- [x] Provide a spreadsheet of items, descriptions, skus, and costs to inventory staff
- [ ] Ask them to make modifications to this spreadsheet **in a new column** so that we can reconcile the differences in knack

**Comment by dianamartin** [comment]
- [ ] Take ICF Form (digital)
- [ ] Convert to spreadsheet format
- [ ] Save `inventory_item` object - back-up
- [ ] Import into existing Fin and Purchasing `inventory_item` object
- [ ] Review missing SKU
- [ ] Add new field for alternate name label

**Comment by dianamartin** [comment]
Met with Ray this morning to discuss the approach I should take. Which list I should use at the primary one to aggregate the other lists into. 

- I had the `inventory_items` in the Finance and Purchasing list, which is what I've been using for the inventory requests and everything. 
- the `items` list are the items that the inventory warehouse people have been using to order the items they need. I noticed they're missing the `inventory_item` connection, bc there were several items that weren't on our list so we'll have to re-associate those items with their corresponding inventory_item. 
- then the AIMS list

We talked and decided to merge the existing `inventory_item` list and import the AIMS list into our existing list. By doing this we'd hopefully add all items that were didn't have and the items that they had ordered that weren't on the list would be added. We could check their stock numbers to re-associate them.

**Comment by dianamartin** [comment]
Have been reviewing the items spreadsheet of things that AMD has ordered that has been tagged as coming from the Inventory fund. Imported the unit costs from AIMS into the `unit cost change log` object table so that every `inventory item` has a unit cost price. 

Made all items that have zero quantity on the AIMs report have an `inactive` status, this can be changed if we need order them.

**Comment by amenity** [comment]
Assume that users will report discrepancies once app is released. 
Authoritative cost will move to Finance system instead of Data Tracker. 

~@dianamartin will you export a spreadsheet and email to Billy, copying @johnclary~ Billy has already okayed using the AIMS naming convention.
