### ISSUE TITLE
Set up local dev environment for Vision Zero editor

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7240]
As described on this [Miro board](https://miro.com/app/board/o9J_luPHQDg=/), the steps to get a local dev of the Hasura cluster running for VZE local dev are the following:

- [x] configure Docker compose
- [x] create migrations to setup Postgres DB
- [x] create metadata to configure Hasura with DB schema
- [ ] create seed data (subset of data for testing)
- [ ] change VZE backend endpoint to local cluster instead of staging cloud instance

**Comment by patrickm02L** [comment]
@mateoclarke please wrap up where things are stalled. Turn last 2 bullet points into a new issue. And close out by the end of this sprint on the 25th.

**Comment by patrickm02L** [comment]
Cleaning up the Issue. Moving this to the backlog.

**Comment by frankhereford** [comment]
In the course of working on #8746, I have extended my set of `docker-compose.yml` + supporting helper scripts that could be used or contribute to a possible solution for this task. 

The docker-compose stack includes

* A PG server
* An ETL docker image
* The VZE
* `graphql-engine` 1.* (custom compiled for ARM) and 2.* (built for ARM by Hasura)
* A modified Ubuntu image with commonly used libraries for interacting with the stack

The helper scripts can:
* Download the latest backup
* Load it into the local postgres server
  * Skip the change log optionally for fast loads

**Comment by mateoclarke** [comment]
@frankhereford @chiaberry I think this is another one of those VZE `Type: Tech Debt` issues that would be worth addressing. Going to reassign to y'all for visibility.

**Comment by frankhereford** [comment]
On this one, I have an old feature branch with some semblance of this working. It's a modification of my own docker stack that I use for local VZ dev. If this issue were to come to me at some point, I would enjoy dusting that off and getting it ship-shape.

**Comment by patrickm02L** [comment]
These last two bullet points have been or will be executed in other Issues

- [ ]  create seed data (subset of data for testing)
- [ ]  change VZE backend endpoint to local cluster instead of staging cloud instance

via @frankhereford 

> The create seed data has been supplanted by a reliable “replicate from production” system :white_check_mark:
> Change the backend … that one has been supplanted by this enhancement by chia https://github.com/cityofaustin/atd-data-tech/issues/11401
