### ISSUE TITLE
[MEETING] Sync: TIA Historical Case Import - 9/24

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7244]
### Objective 
- Initial Template - a tad big (77 columns)
- Revamped Templates
- Pain points of import?
- Breakdown of responsibilities - stakeholder = data clean up, DTS = import
- Expectations (TIA Case, very bare) - w/ attached scope/submissions

### Participants
Chrispin, Nathan, Joan, Diana
Optional: Amenity

### Agenda
- [TIA Cases](https://cityofaustin.sharepoint.com/:x:/r/sites/ATD/TDS/_layouts/15/Doc.aspx?sourcedoc=%7B4007CA1B-CBA3-45CF-96C1-873177CDD089%7D&file=TIA%20Primary%20List.xlsx&action=default&mobileredirect=true&CID=CDA9B80A-D49A-4A4D-9794-1FF00F3CB75D&wdLOR=c00B7DF0E-EFA6-4B1A-BA23-E5C6D559BACD)
- TIA Historical Case Import - g drive (`ENT_Application>app_TDS_Portal>module_TIA`)
------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by ChrispinP** [comment]
updated and simplified stakeholder spreadsheets added to G drive
