### ISSUE TITLE
Parking Inventory GIS Data Discusion

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#7255]
Meeting included:

- [x] Jaime
- [x] Joseph
- [x] Mary
- [x] Ryan
- [ ] Jeremy (cancelled last minute)
- [ ] John (calendar conflict)

**Comment by jaime-mckeown** [comment]
- go over data and update documentation to prepare to start back up on getting this process migrated into Maint from AGOL
- will setup a 1.5 hour meeting for week after 2nd ACL weekend (Mon-Wed only)
- we will be going over the data in Maint and how it's different, then start planning how to attack the project
- I mentioned possibly bringing Stephanie on for Project help, we will wait until we are back into it before deciding if we need help. I suggested this since there will be AMANDA integration eventually when the new data goes live

**Comment by jaime-mckeown** [comment]
@johnclary the meeting today was just a quick planning meeting, my notes are above. We will be meeting again in 2 weeks to get into the data and start planning this out.

**Comment by johnclary** [comment]
OK! Thanks!
