### ISSUE TITLE
Locations for VZA

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#726]
@amenity @TracyLinder looks like I created a duplicate. #711 is the right issue. Closing this one. Thanks for bringing this to my notice.

**Comment by amenity** [comment]
@SurbhiBakshi - is this maybe a duplicate of #711 ?

**Comment by TracyLinder** [comment]
@SurbhiBakshi can you please update this issue? (Pipeline, assignee, labels)

**Comment by amenity** [comment]
@SurbhiBakshi - I labeled and pipelined... But still wondering if it is a dupe and/or if it's complete.
