### ISSUE TITLE
[Bug] Locations maps not rendering in the VZE

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7260]
Lewis L. pointed out that the maps for the Location records were not rendering Friday afternoon, Sep 24th. 

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/34e269fc-fac4-4073-9c80-948a9ecf0153)

Reached out to Mateo and Sergio on slack to help troubleshoot. 

@mateoclarke's preliminary diagnosis is that the Locations maps use a Nearmap tile layer, and that the API token has expired. The maps for each of the records in the Crashes tab are built on the Mapbox API and are still rendering. Sergio also confirmed this to be the case. 

In order to fix this, we need to make sure that the Nearmap token is up-to-date. 

Will follow up with Lewis L. as soon as we've resolved the issue.

**Comment by mateoclarke** [comment]
I've updated the Nearmap API token for both staging and production and both are now working. I've also updated the note in 1Pw
![Screen Shot 2021-09-24 at 4 51 13 PM](https://user-images.githubusercontent.com/5697474/134743694-876a1ab1-ef02-4165-baca-ccdf5f78537f.png)

**Comment by patrickm02L** [comment]
Let Lewis know on Teams that the expired token has been updated, and that the maps in the Locations tab are working again.
