### ISSUE TITLE
[ROW-TCP] Data Cleanup: Number of Deficiencies old

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#7262]
Now that Deficiencies is its own object we can count them without needing the original number field. Reviewers will need to select deficiencies for older projects so we can remove this field.
![image](https://user-images.githubusercontent.com/67915167/134937745-a95e4aa3-1239-4e80-b342-c0666837fe70.png)

**Comment by TracyLinder** [comment]
Ok to remove this field. Moving to backlog.

**Comment by ChrispinP** [comment]
Number of Deficiencies old removed from object and views, complete

**Comment by ChrispinP** [comment]
no further action needed, closing
