### ISSUE TITLE
Parking Inventory Data Migration GIS Support

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#7265]
Help PE get the Parking Inventory moved from AGOL to Maint (data, workflow, processes, etc.)

**Comment by jaime-mckeown** [comment]
@andrewshensky reassigning the Epic to you for support you continue to provide the team until the new GIS Analyst comes onboard.

**Comment by jaime-mckeown** [comment]
Directory for project:
G:\ATD\ATD_GIS\01_ADMIN\DATA_MANAGEMENT\Data_Migration\parking\parking_inventory\Migration_Project\Parking_Migration_Project

**Comment by amenity** [comment]
Moving to the backlog - will be passing this work off to new Parking GIS person.
