### ISSUE TITLE
Renew *.mobility.austin.gov certificate

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7275]
Work with Jason G. (linux team) to get a new cert issued/installed

**Comment by johnclary** [comment]
@mateoclarke would you make sure this gets done this week?

**Comment by mateoclarke** [comment]
New CSR was generated by @sergiogcx and shared with CTM Linux Team. 

After conversation with Jason, we got a followup from the Certificate provider, Entrust.

> Your account administrator has accepted your request for a SSL Certificate renewal

**Comment by mateoclarke** [comment]
✅ 🔒 

https://www.sslshopper.com/ssl-checker.html?hostname=https%3A%2F%2Fmobility.austin.gov%2Fmop
