### ISSUE TITLE
Update VZ polygons which have been flagged by staff

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7278]
@frankhereford has a list of VZ location polygons that need to be reviewed/updated based on staff requests.

@jaime-mckeown let's use this as an opportunity to train the Geo team to do this. 

Frank, can you put together a list of the poly IDs that need to be reviewed and attach it here? FYI @patrickm02L 

See also #7236.

**Comment by frankhereford** [comment]
Below is a list of the unprocessed requests from the VZ team for adjustments to the current VZ Locations (polygons) layer. This list is drawn from the set of issues submitted on the private GH repo, frankhereford/atd-street-polygonizer. Many of these locations have a screen grab submitted by the original poster, and I would be more than happy to invite anyone who would like to have access to this repo to it so they can see the original issues that this list was drawn from. 

- 1727C0E486: Lewis asked this one to be adjusted at least to capture the slip lane
- E3A6F25A01: doesn't include the legs and stems from being on the edge of the ASMP network, perhaps?
- 4C21F93901: E SH 71 EB TO S FM 973, S FM 973 RD
- 7259D99593: This location does not capture the slip lane (right turn).
- Missing portions of US 290 WB @ Joe Tanner Ln
- [ID not reported]: N FM 620 RD NB, N FM 620 RD SB, see image
![image](https://user-images.githubusercontent.com/3653206/135141243-421b928b-a569-4df5-8eb8-c1ac2514b063.png)
- Update to the new road geometry at Montopolis & US 183
- combine 19B272B352 and 804E60B082 into intersection
- 4C21F93901: FM 973 / SH 71 WB SVRD geometry
- combine 6978FC155F and 7D54961DC2 to make it a true intersection
- Oldham St is Missing in Polygons (Between E. Dean Keeton & Red River)
- Manually draw E3A6F25A01 (US 183 and Loyola) to better represent the intersection post-183 South construction.
- add E/W legs to N Lamar/5th (D0A613CEA8) 
- Clean up the edge cases of these polygons @ W. Louis Henna Blvd & CR 172 (B569606A44, 2A9F310D05)
- Remove / Merge 1D766C0127 into adjacent polygon
- E3A6F25A01: Per Lewis, Can you please add this to the list of locations that need the polygon adjusted to add in approaches on service roads? Need to split up SB intersection and NB intersection into two distinct polygons too. Lots of construction in this area lately which I think is complete now.
- Review polygons for Springdale & Webberville, in particular regarding the slip-lane
- Stassney (just east of Mira Dr, split lane is not wide wide enough)
- Missing Roadway at Lamar & Koenig (Right Turn Cut-Through)
- Missing a section of Cromwell Cir (East of Wickersham)
- Montopolis (just north of Oltorf the split lane is not wide enough)
- Metric Boulevard (is a split lane, but the polygon is not)
- Missing Henneman Dr (and others) - new neighborhood development?
- Missing Clayton Lane (btwn Middle Fiskville & Thomas Hatfield)
- 0F958648A2; ASMP network @ E 18th ST & private drives
- East Riverside Dr. overpass at E Ben White - ID# 148A96149A
- Remove C8CCD2E537, 38761D7C2D, 8F329982B1, & A898936F57 (stem from a road in the ASMP network (ASMP Street ID 339810) represents a road for which the ROW has not been acquired or built connecting Ralph Ablanedo Dr to I-35.)

**Comment by johnclary** [comment]
@alan-deanda would you pick a few of these that are straight-foward and give it a shot? based on your questions that come up we can discuss as a bigger group

**Comment by alan-deanda** [comment]
## Polygon maintenance checklist

- [ ] 1727C0E486: Lewis asked this one to be adjusted at least to capture the slip lane
- [ ] E3A6F25A01: doesn't include the legs and stems from being on the edge of the ASMP network, perhaps?
- [ ] 4C21F93901: E SH 71 EB TO S FM 973, S FM 973 RD
- [ ] 7259D99593: This location does not capture the slip lane (right turn).
- [ ] Missing portions of US 290 WB @ Joe Tanner Ln
- [ ] [ID not reported]: N FM 620 RD NB, N FM 620 RD SB, see image
![image](https://user-images.githubusercontent.com/3653206/135141243-421b928b-a569-4df5-8eb8-c1ac2514b063.png)
- [ ] Update to the new road geometry at Montopolis & US 183
- [ ] combine 19B272B352 and 804E60B082 into intersection
- [ ] 4C21F93901: FM 973 / SH 71 WB SVRD geometry
- [ ] combine 6978FC155F and 7D54961DC2 to make it a true intersection
- [ ] Oldham St is Missing in Polygons (Between E. Dean Keeton & Red River)
- [ ] Manually draw E3A6F25A01 (US 183 and Loyola) to better represent the intersection post-183 South construction.
- [ ] add E/W legs to N Lamar/5th (D0A613CEA8) 
- [ ] Clean up the edge cases of these polygons @ W. Louis Henna Blvd & CR 172 (B569606A44, 2A9F310D05)
- [ ] Remove / Merge 1D766C0127 into adjacent polygon
- [ ] E3A6F25A01: Per Lewis, Can you please add this to the list of locations that need the polygon adjusted to add in approaches on service roads? Need to split up SB intersection and NB intersection into two distinct polygons too. Lots of construction in this area lately which I think is complete now.
- [ ] Review polygons for Springdale & Webberville, in particular regarding the slip-lane
- [ ] Stassney (just east of Mira Dr, split lane is not wide wide enough)
- [ ] Missing Roadway at Lamar & Koenig (Right Turn Cut-Through)
- [ ] Missing a section of Cromwell Cir (East of Wickersham)
- [ ] Montopolis (just north of Oltorf the split lane is not wide enough)
- [ ] Metric Boulevard (is a split lane, but the polygon is not)
- [ ] Missing Henneman Dr (and others) - new neighborhood development?
- [ ] Missing Clayton Lane (btwn Middle Fiskville & Thomas Hatfield)
- [ ] 0F958648A2; ASMP network @ E 18th ST & private drives
- [ ] East Riverside Dr. overpass at E Ben White - ID# 148A96149A
- [ ] Remove C8CCD2E537, 38761D7C2D, 8F329982B1, & A898936F57 (stem from a road in the ASMP network (ASMP Street ID 339810) represents a road for which the ROW has not been acquired or built connecting Ralph Ablanedo Dr to I-35.)

**Comment by johnclary** [comment]
@alan-deanda please hold off on any edits that required deleting or merging of polys.

**Comment by alan-deanda** [comment]
@adrien-atd here is our list

**Comment by alan-deanda** [comment]
Closing this issue because it's too long to work with effectively. I've started issue #8388 so that Adrien and I can track our work more efficiently.

**Comment by patrickm02L** [comment]
@alan-deanda cool, thanks!
