### ISSUE TITLE
COS Payment Automation - TURP Extension Fees (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7283]
**Acceptance Criteria**

- The rules mentioned below apply to RW folders of subtype Temporary Right of Way Use (TURP) only.
- Worktypes for RW-TURP Folders where this logic needs to be applied (#6322) :
-- Austin Energy
-- ATD
-- Austin Water
-- Corridor Program Office
-- Public Works
-- Other City Department
-- Watershed Protections

- There seems to be a bug in the Permit Extension process that needs to be fixed and also new requirements implemented as part of this ticket.
  
- Existing Bug Fix (will be fixed #7707) 
-- System should insert Permit extension fee and ATD Surcharge fees and bill them when Extension granted attempt is made on Permit Extension process (this should be working currently but it was reported by stakeholders that sometimes it was not working as it should).

- New requirements
-- System should pay the Permit Extension Fee and ATD surcharge fees when Extension Granted attempt is made on Permit extension process. 
-- Payment type for this auto-payment should be recorded as Cost of Service.
-- The stamp user for the auto-payment should be AMANDA.
-- The paidby field for the auto-payment should be AMANDA.

**Comment by TracyLinder** [comment]
**Notes**

TURP extension fee is triggered by process attempt. Which one? Can this attempt be used to apply COS payment?

**Comment by TracyLinder** [comment]
Vish will begin scoping & meet with stakeholders.

**Comment by vschandramouli** [comment]
Updated AC. Ready for backlog pending review.

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by TracyLinder** [comment]
**Update:** Assigned to Subha & moved to On Deck

FYI @Nadin-Nader

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  @vschandramouli 
In 7162 ticket,  following are the RW TURP worktypes considered for COS auto-payment. In this ticket, we have Project Connect for the auto payment and Other City Department is not in the list given in AC. Please confirm if we are still going with what is given in AC.
50550	Austin Energy (AE)
50555	Austin Transportation (ATD)
50560	Austin Water Utility (AWU)
50565	Corridor Program Office
50585	Other City Departments
50596	Public Works Department (PWD)
50597	Watershed Protection Department (WPD)

**Comment by SubhaShroff** [comment]
### Status:
In progress. Need a clarification on the point mentioned in the previous comment.

**Comment by TracyLinder** [comment]
AC has been updated
- Removed Project Connect as a COS department
- Added Other City Department

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader  demo is sent in email. Please review and let me know your feedback.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder Demo looks good. Lets get this to **_DEV_**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  SCTASK0183694 is raised for the DEV deployment of this ticket.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This ticket is deployed in DEV, I tested it and  looks good. Please let me know if I can get it deployed in TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0183793 TEST Deployment request is submitted.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This is tested on TEST and upto the AC. And its ready for your UAT.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder Here are Kim and Paloma's notes from Kim's UAT:

> [Yesterday 6:05 PM] Perez, Kimberly Test Results for Ticket 7283
>     ALL COA TURP permits collected extension fees and were automatically issued after extension granted attempt was made. 
> See conversation below: Permit should NOT be extended if “Activate Upon Payment” is a “No”!
>  
> OBSERVATION:
> Still adding TDS Tech Surcharge. See ticket 7707. (Cannot move 7283 to PROD without 7707)
> Updating Issue Date. Should be resolved by ticket 7909.
> Permit still issued even though "Activate Upon Payment" was a "No".
>  
> QUESTION:
> Amayo-Ryan, Paloma Do we need or want the "Activate Upon Payment" feature to function correctly for these city permits?
> Edited​[10:03 AM] Amayo-Ryan, Paloma
>     Perez, Kimberly - the Activate Upon Payment feature - in theory - shouldn't matter at the time of initial review, since the feeing and payment happens before the permit is even submitted.  The only time it would come into play is during extensions.  If Activate Upon Payment is set to No then the permit should NOT issue.
> ​[10:21 AM] Perez, Kimberly
>     Amayo-Ryan, Paloma yea this was testing extensions. So if we still want it to function correctly for them, then this is an issue for this ticket. I’ll update these results!
> (1 liked)

**Comment by TracyLinder** [comment]
![TURP Permit Extension - Extension Granted (1)](https://user-images.githubusercontent.com/49930868/145620240-1c596bd4-771e-486f-972b-7db669deb83f.jpg)

**Comment by TracyLinder** [comment]
![RW Activate Upon Payment Workflow](https://user-images.githubusercontent.com/49930868/145620264-9f4a86e1-0b23-4833-af63-0dd54de120a3.jpg)

**Comment by TracyLinder** [comment]
@SubhaShroff the UAT feedback from Kim & Paloma above:
`Permit should NOT be extended if “Activate Upon Payment” is a “No”!`

I think this needs to be fixed in the Activate Upon Payment procedure for RW (I could be wrong). Checkout the workflows I attached above & let me know if this is enough for you to continue working on this one.

**Comment by SubhaShroff** [comment]
@TracyLinder  I just got that clarity. Thanks for filtering the feedback. Yes, I will work on that. 
Can we add these workflows in 6255 as well?

**Comment by Nadin-Nader** [comment]
Subha had 3 questions:

If no extension happens should we add the fee, autobill it and pay?
In case of AUP = NO, Permit should not be extended. In that case, are we still needing to add fees and auto pay them?
Should we update the event start date, end date and expire date when the extension is granted and AUP is set to no?
**_Response from Tracy:_**

> If extension granted is saved
> And AUP is no
> The system should still add fees, bill & pay with COS
> Do not update the date infos if AUP is no.

**_Response from Kim:_**

> When AUP is set to no.. it should not update any dates or status for any permit types. When it comes to the cost of service permits, it should still add fees, autobill, and pay them, but that is all. When it comes to private development, it should add the fees and that is it. We don't want them auto-billed, because we typically have to manually change those fees and the parking fees have never calculated correctly.

**Comment by TracyLinder** [comment]
**Demo Feedback:**

- Extension Granted process did not insert attempt comment. It should always insert an attempt comment, regardless of A.U.P. value. 
- I need to gather some user feedback before we promote.
- @SubhaShroff did you test a private development and project connect to make sure they still work correctly with this update?

**Comment by TracyLinder** [comment]
**Updated Workflows**
FYI @SubhaShroff 

![AMANDA Misc  - Frame 3](https://user-images.githubusercontent.com/49930868/146254516-46e21b83-5e75-443d-9330-686bbd207d37.jpg)

![AMANDA Misc  - Frame 4](https://user-images.githubusercontent.com/49930868/146254542-51a32e10-95b0-4650-8df1-a74e06c56914.jpg)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  SCTASK0187030 is submitted for DEV deployment of the latest workflow for Extension changes based and changes based on AUP value.

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder  The DEV deployment is done. I tested for following permits. And its working as expected. Let me know your feedback to push it TEST.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SUBHAS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SUBHAS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



RSN | Worktype | AUP | Activated? | Infodates | Expiry Date | Process Comment | FEE added | billed? | COS Paid? |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
11904134 | AWU | NO | NO | YES | NO | YES | YES | YES | YES |  
11904134 | AWU | YES | YES | YES | YES | YES | YES | YES | YES |  
  |   |   |   |   |   |   |   |   |   |  
11904039 | PVT | NO | NO | YES | NO | YES | YES | NO | NO |  
11904039 | PVT | YES | NO | YES | NO | YES | YES | NO | NO | activated after billed and paid from Amanda
  |   |   |   |   |   |   |   |   |   |  
11904135 | OCD | NO | NO | YES | NO | YES | YES | YES | YES |  
11904135 | OCD | YES | YES | YES | YES | YES | YES | YES | YES |  



</body>

</html>

**Comment by Nadin-Nader** [comment]
@SubhaShroff 
**Status:**
Approved by Paloma and Kim for PROD

**Comment by SubhaShroff** [comment]
@Nadin-Nader  
SCTASK0187300 - request is created for TEST deployment.

**Comment by Nadin-Nader** [comment]
**Status:**
This is ready for UAT on TEST

**Comment by TracyLinder** [comment]
I posted in the teams channel that this is ready for UAT, and tagged Kim & Paloma.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder here is Kims UAT results:

> [Yesterday 12:19 AM] Perez, Kimberly
>     Test Results for 7283
> 
> ALL COA TURP permits collected correct extension fees and were automatically issued after extension granted attempt was made. Permit was not issued if "Activate Upon Payment" was marked "no". yes
> 
> OBSERVATION:
> Will need manual extension process, see ticket 7990.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder this is good to go to PROD per Kim's UAT but needs #7990 to go with it for the manual process ( @Lpriya-LIT )

**Comment by SubhaShroff** [comment]
### Status:
Ready for PROD but dependent on 7990. Today I will be starting with 7990.

**Comment by SubhaShroff** [comment]
### Status:
Ready for PROD but dependent on 7990. Today I will be starting with 7990.

**Comment by SubhaShroff** [comment]
### Status:
Waiting on 7990 to be moved to PROD.

 (**7990** is UATed on DEV for stakeholders on Friday call. Approved and TEST deployed. Now waiting it to be UATed on TEST and get approval for PROD deployment.)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0194846 is submitted for PROD deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  PROD deployment is done.

**Comment by TracyLinder** [comment]
**❌ PROD UAT FAILED❌**

In my test case there were bugs I think are caused by this issue. (My notes are [here](https://github.com/cityofaustin/atd-data-tech/issues/8319).) Confirming that this does need to be redeployed.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  After redeployment of this ticket in TEST today, I tested it and it works as per the AC.

**Comment by TracyLinder** [comment]
### UAT Failed in PROD
- system did not bill or pay the extension fees on ROW ID 12875367

**Comment by Nadin-Nader** [comment]
All is well per Paloma. Closing
