### ISSUE TITLE
COS Payment Automation - TCP Fee on GF Folder (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7285]
**Acceptance Criteria** 

The Acceptance Criteria provided below only applies to folders of type GF with subtype ATD and no work type: 

- During Folder creation, system must insert TCP Review fee and ATD Tech Surcharge in the folder (Being implemented as part of #7682).
- System must also check to see if the Info field 'COS Partner Department?' on the GF folder is answered 'Yes' (#7465).
- If COS Partner Department is 'Yes', system should automatically pay the TCP Review Fee and the ATD Tech Surcharge. 
- Payment type should be recorded as 'Cost of Service'.
- The stamp user for the auto-payment should be AMANDA.
- The paidby field for the auto-payment should be AMANDA.
- If there are any folder status changes currently happening after the GF folder fees are paid, system should make the same folder status change after automatic COS payment is applied.

**Comment by TracyLinder** [comment]
Backend user (Robert) inserts GF folder, ATD subtype, No Work type
On Info tab, user identifies if COS y/n & COS department (#7465)
During auto add phase, system inserts & bill TCP Review Fee & Tech Surcharge (#7682) 
If COS is yes, system pays the fee w/ COS Payment Type & Updates folder status to ?
- _Whatever the system does when the fee is paid normally, it should do after the COS payment is made._
If COS is no, continue ...

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @Lpriya-LIT  I have completed COS automation payment part. The last point in AC has to be worked upon: 

-" If there are any folder status changes currently happening after the GF folder fees are paid, system should make the same folder status change after automatic COS payment is applied."

 I will do the commit for the completed part and let you know the commit.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0187064 is submitted for DEV deployment of 7285, along with status update that @Lpriya-LIT  has done.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  DEV deployment is done by EOD and I tested it. It looks good and the status changes to ACTIVE along with COS auto payment.
@Lpriya-LIT  has fixed the surcharge, yesterday as part of #7682. And its with CTM  team to DEV deploy.

**Comment by Nadin-Nader** [comment]
@SubhaShroff 
**Status:**
Approved by Paloma and Kim for **PROD**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  TEST deployment request is submitted - SCTASK0187299.

**Comment by Nadin-Nader** [comment]
**Status:**
This is ready for UAT on **_TEST_**

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/8b73e854-2148-446f-aeed-03b53019198d)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder Verified in Test , The fee is added and auto paid.

**Comment by TracyLinder** [comment]
I chatted Robert A. on teams asking if he can UAT, and offering to help.

**Comment by TracyLinder** [comment]
I scheduled a UAT sesh w/ Robert on Monday 12/27 at 10:30am.

**Comment by TracyLinder** [comment]
### UAT Passed; Please promote to PROD
FYI @Nadin-Nader @Lpriya-LIT

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0188661**

**Comment by Nadin-Nader** [comment]
@SubhaShroff @Lpriya-LIT @TracyLinder this has been deployed to PROD. I will post it in the TEAMS channel to let the stakeholders know.

**Comment by Nadin-Nader** [comment]
Closing as i have not heard anything on this, it is on PROD and i informed the stakeholders yesterday that i would be closing it
