### ISSUE TITLE
Automate comprehensive cost maps

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7296]
Comprehensive cost maps are currently being updated on a bi-weekly basis following a process that Frank H. created.

We would like to incorporate his code into the VZD so that we output materialized views that are refreshed daily.

related issue #3316

**Comment by frankhereford** [comment]
The level 1-4 comprehensive cost map has been updated as part of working issue #7384.

**Comment by patrickm02L** [comment]
Frank had a meeting with the new VZ Team GIS Analyst Adrien where he talked about his process for making comprehensive cost maps. 

There is a possibility of Dockerizing this process if she would like. 

Putting this in the Icebox, if she wants to dockerize we'll revisit.

**Comment by patrickm02L** [comment]
Haven't heard any talk about this on the DTS side for a long time, and Adrien has been gone for a while. FWIW I think Milad (Adrien's successor) with the VZ team has been working on this. Considering this accounted for.
