### ISSUE TITLE
[Bug] MDS - Data is being parsed as CST

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#7299]
It appears that the MDS data is behind 4 hours from UTC; which is neither CST or UTC.  We will need to first check that the output of the data is valid (before it inserts to the database), then:

1. Refactor the code so that the timestamps remain transparent all the way to the database (and potentially socrata)
2. Check database and see if the hours in the database are configured to have a timezone. A SQL or Python script may be needed to update the database to correct its values.
3. Update the socrata insertion if needed. Basically we will try to keep the timestamp as UTC from origin. Potentially we may need to translate from epoch into ISO or a string, but it seems that is already implemented since the timestamps are exactly the same in socrata as they are in the database.

![2021-09-29_14-55-55.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/8751959c-c5e6-4dd8-97b5-77ff04370a0a)

![2021-09-29_14-58-26.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/6ba3f49d-be34-44e1-98e8-b8e2c0a30b1b)

![2021-09-29_15-05-22.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/baa1b532-b003-4e9d-bed1-e334980cbd66)

**Comment by sergiogcx** [comment]
@johnclary sounds good, working on this right now.

**Comment by sergiogcx** [comment]
For `translate_timestamp` which is found in [this file](https://github.com/cityofaustin/atd-mds/blob/7b200b092424b15c883cb8e1dfab64daba5ca7ef/MDSTrip.py#L280)

It appears to be providing the correct output:

Example timestamp taken from a lime trip `1632842501000`, in the image below I printed the original value in UTC and the translation to CST:

![2021-09-30_12-45-17.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/cf1f3215-0ef9-40b7-935a-bb03c15de963)

Then I ran the unit test with that specific value in mind, and the function seems to be translating to CST correctly:

![2021-09-30_12-35-28.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/5ffcfed7-1573-4746-b7cd-16315be36b4d)

**Comment by johnclary** [comment]
thanks @sergiogcx. the `translate_timestamp` method appears to have a bug. it assumes the timestamp being processed can be translated with the local timezone's _current_ offset. 

however, if we were to process historical trips, this function would apply the current daylight savings offset to all trips, regardless of the offset at the time of the trip.

E.g., `1609468589000` will return `2020-12-31 20:36:29 CDT` when it is in fact `2020-12-31 20:36:29 CST`.

I think this would affect a very small number of trips, given that we almost always process trips within an hour of their creation. It's possible to repair this, but I'm honestly not sure it's worth it. 

Let's talk?

**Comment by sergiogcx** [comment]
The code part of the issue is finished, working on updating the dataset

**Comment by sergiogcx** [comment]
John ran an analysis of the MDS database and provided some observations:
https://austininnovation.slack.com/archives/DEGDGP1UY/p1633451360002800

**Comment by amenity** [comment]
@sergiogcx - thanks. 

@johnclary What would you like to do as next steps? Should we make a follow up issue?
