### ISSUE TITLE
[Enhancement] Data Tracker Task Order Integration

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#7310]
## As a Data Tracker and Moped user I want to link task orders between AMD and Moped so that I can track projects against specific financial task orders already stored in Data Tracker.

**Context**
Similar to the work accomplished in #7073, we would like to give the users the ability to select from a dropdown (populated by the Knack object [`financials_task_orders`](https://builder.knack.com/atd/amd/records/objects/object_86). We do not want to reply on a simple call to the Knack API but instead Socrata.

**Acceptance criteria**
- [x] AMD projects table must contain a "Task Orders" column
- [x] "Task Orders" column should contain value options originating from the Knack object [`financials_task_orders`](https://builder.knack.com/atd/amd/records/objects/object_86) in Data Tracker.
<img width="1091" alt="task order column in table" src="https://user-images.githubusercontent.com/34947604/135512992-dea143b8-4ece-44fe-8c3d-a0557863d660.png">

**Notes**
Please note that the AMD projects table work is tracked separately in another issue.

**Comment by zappfyllc** [comment]
@amenity @johnclary cc: @mateoclarke 

Mateo raised important questions and clarifications with this integration pattern for task orders, which originate from the `financials_task_orders` table in Data Tracker. Originally when I scoped out this column for Chia's work under #3974, I thought that we could avoid storing these same records in Moped, send them over to Socrata to effectively function as the dropdown lookup list, then store a Knack record ID in a newly created `task_order` column in the table `moped_project`. That may still be an ok approach, but since the user is querying against a concatenated `task_order` column and a `name` column, there are some complexities here where querying directly from a table in Moped could make more sense.

This introduced some other concerns so we'll be discussing this in our product sync discussion today (12/8) to quickly make sure we're headed in the right direction.

**Comment by johnclary** [comment]
@zappfyllc @mateoclarke If I follow you, we should be able to handle whatever formatting/concatenation we need in the socrata dattaset. Socrata remains the best option IMO. @mateoclarke happy to walk you through the socrata setup.

**Comment by zappfyllc** [comment]
Per convo on 12/8:

- We will use a JSONB in `moped_project` for storing the Knack record ID (retrieved during Socrata ETL, @zappfyllc has provided initial Knack record IDs), and the `NAME` + `TASK_ORDER` columns from `financials_task_orders` in Data Tracker.
- We will include the same "Task Order" column that's being added to the signal projects table (under the Dashboard page currently) in the Project Summary for now (underneath Project Partners).
- We should be able to select many task orders for a single project. [this is a change @mateoclarke]

**Comment by mateoclarke** [comment]
This feature is implemented all except for displaying the TasK Order value on the Project Summary page. It sounds like there may be some mock-ups in progress to put this info on the Funding tab. cc/ @amenity @patrickm02L

**Comment by amenity** [comment]
@mateoclarke - the issue for that that ETL is here, I think: https://github.com/cityofaustin/atd-data-tech/issues/7931
