### ISSUE TITLE
Build signal project dashboard

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#7316]
As an AMD Moped user I want to track my signal projects so that I can update multiple projects at once without opening Data Tracker or individually editing a project's details.

**Requirements:**

- [ ] Copy the [projects table from Data Tracker](https://atd.knack.com/amd#projects/)

<img width="1723" alt="Data Tracker table with columns" src="https://user-images.githubusercontent.com/34947604/135906348-487f6776-aea8-485c-b277-9a5fcf407f15.png">

- [ ] Allow inline editing of the table
<img width="1091" alt="inline editing" src="https://user-images.githubusercontent.com/34947604/135906363-c9fb86b2-7029-4b68-b2e8-ed021258a279.png">

**Data Model:**
From left to right in screenshot above, the columns above map accordingly:

- Details > Ignore, let's create a link to the project details through the project name below
- Project ID > Ignore for now
- Name > Project name
- Signal IDs > Signal ids (this is saved in the json blob in `moped_proj_features`; we want to add columns to support storing signal IDs and ideally Knack IDs)
![signal options](https://user-images.githubusercontent.com/34947604/135906590-534cad52-0deb-460d-bf02-2d2dd531f8ca.png)

- Project Type > Project type (rename moped_categories to moped_types and moped_proj_categories to moped_project_types: moped_types contains the list below and moped_project_types is where each project has a record for each and every project type it can be)
Project type will start with the AMD options given in Data Tracker (Signal - Mod, Signal - New, RRFB - New, PHB - New, PHB - Mod), knowing that for v2.0 we will then import the [following list](https://docs.google.com/spreadsheets/d/1VGO57EL1TtASbLz2yeWyLwcTB1lT9LR8G6_QZ4WSifs/edit#gid=1128465159)
- Current phase > Current phase
- Task Order > covered by #7310, temporary placeholder is fine or you can do this work concurrently
- Contractor/Contract > new string column in Moped _project
- Internal status note > Status update (from Project details page)
![status update](https://user-images.githubusercontent.com/34947604/135906542-0086ecae-9c6d-42f1-b877-27c3535b4457.png)

- Funding > Funding source
- Project DO # > Project DO # 
- Project Sponsor > Project sponsor
- Targeted Construction Start > moped_proj_phases where phase = Construction, display the phase start date, otherwise leave blank
- Modified Date > Last modified

**Comment by amenity** [comment]
@chiaberry - giving you this one. @zappfyllc will be your point product person for it!

**Comment by chiaberry** [comment]
@amenity @zappfyllc Question about editing a project's funding source. Now that Mateo's branch is in main and I'm looking at the funding sources, when you add a source there's a lot more information (amount, status, program). My question is if this is editable from the Signal Project Table, how should it handle including all that information?

**Comment by zappfyllc** [comment]
> @amenity @zappfyllc Question about editing a project's funding source. Now that Mateo's branch is in main and I'm looking at the funding sources, when you add a source there's a lot more information (amount, status, program). My question is if this is editable from the Signal Project Table, how should it handle including all that information?

@chiaberry my bad, I did not at all check the funding tab. This will follow the same pattern as the hyperlinked project team and phase (construction, completion) date columns. You can read from `moped_proj_fund_source` and concatenate the values just like you did with the signal ids for now.

**Comment by chiaberry** [comment]
@amenity & @zappfyllc  I added `purchase_order_number` to moped_proj_financials and brought it into this view. But now as I'm going to write the update/mutation I've run into a snag. I tried testing an upsert where I add a dummy PO# to an existing project

```
mutation MyMutation {
  insert_moped_proj_financials(objects: {purchase_order_number: "#44", project_id: 156}) {
    affected_rows
  }
}
```

and I get a constraint violation error, `"message": "Not-NULL violation. null value in column \"subproject_name\" violates not-null constraint"`. Is the subproject name the project name? Or where are the moped_proj_financials changed in moped, should I just link to that tab?

**Comment by chiaberry** [comment]
@johnclary  ^^^ here's the question I was bringing up at dev sync

**Comment by zappfyllc** [comment]
@chiaberry let me check with both @amenity and @johnclary on whether they see the columns in `moped_proj_financials` as relevant to the later scope of Moped (it was originally conceived as a 1:1 match to consolidate any financials coming over from external systems so as not to always perform reads and writes nor throw everything into `moped_project`), but for now let's actually add `purchase_order_number` to `moped_project` so you can avoid being blocked by any longer discussion this might invite.

`subproject_name` does not need to be non-null either if that solves the problem easier, but if there's a chance at `moped_proj_financials` is not really needed anymore, then I think it's better to avoid that table altogether and go forward with storing the `purchase_order_number` in `moped_project`. My apologies for the conflicting direction before since I know I told you to store it in this table :)!
