### ISSUE TITLE
Design route for signal project management page in navigation

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#7317]
@patrickm02L - please advise on how we should provide AMD Moped 1.0 users a path to their [signal project management dashboard/table](https://github.com/cityofaustin/atd-data-tech/issues/7316).

Top-level menu item? In Data Tracker, it's a "Projects" tab that's accessible sitewide. 

We'll revisit once we add additional views and workgroups, just need something simple for 1.0.

**Comment by amenity** [comment]
I spoke with @patrickm02L and we decided to repurpose the Dashboard page for this. Pretty sure one of you offered that solution when we last spoke, @johnclary @zappfyllc ... sound okay?
