### ISSUE TITLE
Delete "csr_flex_notes" from Signs & Markings - Nov 2021

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#7324]
Received automated reminder to delete flex notes in Signs and Markings Operations PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings/records/objects/object_172

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 09/01/21

Total Records: `17,389`
To Delete: `6868`
New Total: `10,521`

**Comment by dianamartin** [comment]
![image](https://user-images.githubusercontent.com/21112975/140146361-a668e36f-e6bb-4d1e-b9d0-5ad2817524a1.png)
