### ISSUE TITLE
Critical Bug on EX - Permits Not Splitting by Street

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7326]
### System is not creating a folder for each street input during the EX portal application.

**Comment by Nadin-Nader** [comment]
Moved back to On Deck, per Paloma's priority request to have #7327 be worked on first

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Need more TEST RSN's and a meeting to understand the issue to continue my analysis

**Comment by TracyLinder** [comment]
I just tested on PROD and this feature is now working correctly. 
Closing this ticket.
