### ISSUE TITLE
Bug on TURP: Permit issuing w/ Fee Payment (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7327]
### On TURP, when the TURP Permit Fee - New payment is made, the system is updating folder status to Active and inserting a folder issue date.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Commented out the folder status and Issue date update for TURP in Payment_rw procedure.
Commit id - 58944f1eb438

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT i have sent this to the DevOps Team to deploy to DEV and TEST under **SCTASK0170738**

**Comment by TracyLinder** [comment]
### Approved for PROD

@Nadin-Nader @Lpriya-LIT FYI

**Comment by TracyLinder** [comment]
**Notes on Bug Fix:**

_This bug was causing the system to issue TURP permits before staff has reviewed the application. Being that the permit applicant can access the approved permit online and possibly close the ROW without approval, this is a **major** bug._

- Nate, Priya and I reviewed the RW_TURP fee procedure and I feel very strongly that a significant section of the procedure is missing all-together. The most likely cause is the AMANDA DevOps process. We will need Sree's input to know for sure. 
- If there is code missing, and we can find it, we will redeploy that code. (That's my preferred solution.)
- Since I don't know when Sree will be back I instructed Priya to comment out the post-payment features.

**Comment by TracyLinder** [comment]
**Notes on My UAT**

_Bottom Line: We fixed the major bug, but only by causing a smaller bug._

- The section of the code that is missing is responsible for folder status automation, and folder process insert. The TURPS will no longer issue themselves, but now they will require a user to manually push the permit to the next stage of the workflow.

**Workaround**

1. Check for pending payment turps 
2. Check to see if they've been paid. 
3. If they have, go to the process tab and manually insert the web acceptance process. 
4. When you save approved on web acceptance, it will insert the other folder processes that are missing.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder I sent this to DEVOPS under **SCTASK0170774**

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader The changes has been deployed to Prod

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I have reviewed the Payment procedure and do not see any difference than previous code; as Tracy aware I commented to make sure to update the folder status from expired to active for all work types of TURP. Work types commented and PVT check commented.  This will not hurt any existing process. Kindly provide me with TEST RSNS to continue further analysis on the issue.

**Comment by Sreelatha-BlazeKannan** [comment]
Examples - PROD RSN's Portal - 12793432, 12793455, 12793460

**Comment by Nadin-Nader** [comment]
**Status:**

Sent to CTM DevOps under **SCTASK0174111** to deploy to PROD

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder Izzy mentioned that this was resolved/not happening anymore. I am closing this per my chat with Izzy and Paloma. We agreed to close this at 4pm today if the issue did not happen again. 
I am also closing #7466

**Comment by TracyLinder** [comment]
**Small update to Sree's AC update above:**

_Work type Project Connect is also treated exactly as Private Development._

RW_ TURP - Except for Private Development **and Project Connect** all city departments fee must not be able to pay from Portal.
Upon making the payment on private development portal status must change from pending payment to internet pending.
Franchise there will not be any fee it will directly goes to internet pending

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Once #7162 changes are in TEST, this can be tested

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST For Private Development and Project Connect able to make payment online. Ready for TEST UAT.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per our meeting today with Stakeholders Kim and Paloma, this can be moved to PROD once #7162 moved to PROD.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Once OTH changes on #7162 are moved to TEST, I have tested OTH worktype and it is working as expected. Ready for PROD Move when #7162 PROD Move submitted.

**Comment by TracyLinder** [comment]
### Clarification on TURP Online Payments

**Work Types:** All Work Types
**Status:** Active, Expired, Withdrawn, Pending, Pending Payment, Pending Permit, Suspended, Internet Pending

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this over the DevOps CM Team to be deployed to _**PROD**_ under **SCTASK0186590**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on the DevOps CM Team to deploy to _**PROD**_ under **SCTASK0186590**

**Comment by Nadin-Nader** [comment]
**Status:**
On **PROD**, Waiting to see if all keeps working as expected. Kim is keeping an eye out. Will close, Hopefully by Wednesday.

**Comment by Nadin-Nader** [comment]
Closing as i have not heard anything on this, it is on PROD and i informed the stakeholders yesterday that i would be closing it
