### ISSUE TITLE
Create design for Activity Feed 2.0

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7354]

**Comment by patrickm02L** [comment]
Feedback: for status updates show Icon and overlay PFP medalion like in github.

![Screen Shot 2021-11-10 at 11.47.23 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/24bdd019-f708-4db1-a9a1-0a9ed1efd431)

**Comment by patrickm02L** [comment]
Improvements
- Activity Feed represented by icons and PFP medallion, offset from comments
- Line connects the Activity Feed entries
- Comments become speech bubbles

![Activity Log 2.0 – 4.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/ef7b172b-6c48-4971-a68f-fb5f2216ecfd)

**Comment by patrickm02L** [comment]
@amenity ready for review.

**Comment by amenity** [comment]
😍💯 This looks superb, @patrickm02L. 🙏 🙏

**Comment by amenity** [comment]
\

**Comment by patrickm02L** [comment]
Need to create issues to Implement the design. @amenity
