### ISSUE TITLE
Implement Moped "Project sponsor" and "Project partners" UI

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7358]
![New Summary Page – 3 0 – 2](https://user-images.githubusercontent.com/1463708/136119623-cd6e6969-1728-4591-bba7-55861365983e.png)

- Project sponsor - **Single select** project sponsor from `moped_entity`, data store is a new column called `project_sponsor` in the `moped_project` table
![Screen Shot 2021-10-05 at 7 00 15 PM](https://user-images.githubusercontent.com/1463708/136120074-138ef009-c63c-4ff2-bb12-c985a7df1aeb.png)

- Project partners - **Multi-select** from `moped_entity` using [checkmarks](https://mui.com/components/selects/#checkmarks), select component; render as long text with commas; data store is `moped_proj_partners`

**Comment by sergiogcx** [comment]
Finished the sponsor on Friday, now working on the partner. The partners will be inserted as they are selected, and soft-deleted as the partners are unselected from the menu. 

![2021-11-01_13-46-43.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/c07860c9-9f15-4b85-b80d-847452512f25)

**Comment by zappfyllc** [comment]
> Finished the sponsor stuff on Friday, now working on the partner work. The partners will be inserted as they are selected, and soft-deleted as the partners are unselected from the menu.
> 
> ![2021-11-01_13-46-43.png](https://camo.githubusercontent.com/beb6e95ad1c49e9457f6edb6ae18cafc5a767782972802eb24d7856e204d0ff5/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3562376564616437323930616163373235616563323930632f63303738363063392d396631352d346238352d623830642d383437343532353132663235)

Great work, @sergiogcx!
