### ISSUE TITLE
Send knack banner update summaries to email

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#7368]
The logs are available in airflow, but it would be much easier to read summaries in emails. With which records were added, which were updated and which were mark as inactive. 

Email only sent when records were altered.

**Comment by dianamartin** [comment]
>John suggested sending to the `transportation.data` email might be the way to go. We also can see if have it published to a URL and we just link the URL in an auto-generated email in Knack to the transportation.data email perhaps?

**Comment by amenity** [comment]
@moorerst - what is the prioirity on this? 

@sergiogcx suggests looking at the DAG we use for MDS.

**Comment by moorerst** [comment]
@amenity next sprint will be fine. 
I'm not familiar with DAG. Email format was preferable because there are other individuals within HR that can also use the summary to make updates in other systems/applications. i.e. Train

**Comment by sergiogcx** [comment]
@chiaberry this an example use of the email operator, now that I have a better understanding of what the DAG is supposed to do I think it may be insufficient. But for here it is for what it's worth:

https://github.com/cityofaustin/atd-airflow/blob/faef3309a40621338e974a436c687bf1d6b866f3/dags/atd_mds_monthlyreport_production.py#L49

**Comment by dianamartin** [comment]
@chiaberry was this converted to an email notification?

**Comment by chiaberry** [comment]
I prematurely closed it -- the code is reviewed and in prefect but I need to toggle the switch to turn it on officially

**Comment by dianamartin** [comment]
that's exciting 👍🏽
