### ISSUE TITLE
Meeting: Banners Permit/Payments in Knack 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7369]
Attendees: Stephanie, Diana, Luke, Hannah, Alex, Lauren
Agenda:
•	Update on CityBase online payments process
•	Requirements for external facing application

Scheduled 10/18

**Comment by dianamartin** [comment]
@moorerst reviewed slides, updated some slides and left comments

**Comment by moorerst** [comment]
Diana is developing the external facing interface based on the initial requirements we got from the stakeholders.
