### ISSUE TITLE
Bug: ATD-SP Case Review Fee Inserting w/ Revision

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7374]
**Reported by Zachary W. w/ DSD, INC0139385**

AMANDA inserted 83475 - ATD-SP-Site Plan Consolidated'
See Row ID 12777258

**Comment by SubhaShroff** [comment]
### Status:
Yesterday, I checked the “Completeness Check Distribution.” process code in TEST environment and it doesn't have any related code to insert the specified fee(83475). Tested it for the same attempt in TEST, it didn't add this fee. 

The investigation is in progress.

**Comment by TracyLinder** [comment]
**Update**

Subha is looking through code to find any clues as to what caused this bug. Nate emailed Zach asking for more example folders.
