### ISSUE TITLE
Port MDS to Prefect

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7379]
We have several MDS DAGs running in Airflow that need to be ported to Prefect as a test, including:

1. Vendor data retrieval
2. Redundant data retrieval
3. MDS monthly reports

**Comment by sergiogcx** [comment]
After porting them, the data has been successfully running for the past few hours:

![2021-12-22_08-01-31.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/53a15f2d-f1ee-4a05-ae8b-9e5cd75793a1)
