### ISSUE TITLE
Inventory Request: Display Quantity in Red if More than What's On Hand

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#740]
As a workaround

**Comment by dianamartin** [comment]
@johnclary Looking at this and realizing that we can't have it look at the column because it's a `number` field and it only allows you to set it if it's higher/lower or is a ______ entered field. :(

**Comment by johnclary** [comment]
@dianamartin ok. moving this to backlog because it's not mvp.
