### ISSUE TITLE
Always render current components in "Summary" map

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7403]
Pretty minor, but it would be better if the map image were refreshed whenever the "Summary" tab renders - or regenerated and cached every time components are updated?

https://user-images.githubusercontent.com/1463708/136734724-b76f1110-f1fe-4e5c-b1a6-08c756d46668.mov

**Comment by chiaberry** [comment]
I was talking this through with @frankhereford and it sounds like he has an idea of how to address the issue....

**Comment by frankhereford** [comment]
> I was talking this through with @frankhereford and it sounds like he has an idea of how to address the issue....

@chiaberry - thank you for your time today to pair up re the `forwardRef` usage **and** also for taking the time to look into this bug as it relates (well, didn't relate) to [PR #473](https://github.com/cityofaustin/atd-moped/pull/473). 

Re this issue, while I have *not* coded anything up to investigate, I think it may be a matter of either refetching the `projectFeatureCollection` once new features are added or appending the new features to the object as they are added. _This is just a hunch_, but I would be happy to give it a whirl if it gets assigned to me.

**Comment by chiaberry** [comment]
While working on https://github.com/cityofaustin/atd-data-tech/issues/7493, I found that if I put `refetch()` in the ProjectSummary component, it fixes this issue. However, I dont to needlessly refetch. 

The ProjectComponentEdit has a refresh prop passed through it, but its not being used (https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/views/projects/projectView/ProjectComponents.js#L188)
