### ISSUE TITLE
Inventory request: Don’t allow multiple identical checkouts for same location

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#741]
Let's backlog this. Requiring work order prior to inventory request should fix this

**Comment by johnclary** [comment]
Hold off until we are in prod with work orders connected to inventory requests.

**Comment by amenity** [comment]
@johnclary - thinking that this was addressed by #1107 ... Let us know if you agree.

**Comment by johnclary** [comment]
Agreed. and/or this is a process issue. closing.
