### ISSUE TITLE
IT Support: Create Test Technician Account for Brian VDW in SMB Test Environment

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7412]
Brian VDW
AMD

Messaged
>Can you set me up with a user account for Signs and Markings work orders? Test database only. (Don't let me muck up the real data.)

**Comment by dianamartin** [comment]
Messaged Christina to let her know that this was requested to make sure there were not issues before creating the account.

**Comment by amenity** [comment]
Christina did this herself.
