### ISSUE TITLE
Add Nearest Street Segment ID to SZB GIS Data

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#7418]
From Diana:

> I am now starting to work on the school zone beacon task that am assigned to. When I talked to John, he said I had to create locations for the new school zone beacons. However, to import and create those records I would need a street segment. The “School_Zone_Beacons_Audit” layer does already have the X and Y which I also need, but John asked if I could get with you and see if you can also populate the nearest street segment for the beacon? You don’t have to update the same dataset if it’s difficult, you can provide a copy of the layer with the “Street Segments” on them too if it’s easier.

**Comment by dianamartin** [comment]
Thank you! :trophy:
