### ISSUE TITLE
Update Nazlie's Permissions for SC

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7420]

**Comment by TracyLinder** [comment]
@Nadin-Nader Nazlie needs the same permission on SC that Amber has. Can you please work w/ her for the NURF?

**Comment by Nadin-Nader** [comment]
Per Nazlie's email her account is working how she needed it. Closing request. Email from Nazlie below:

> 
> Hi Nadin,
> 
> Thank you! It’s working now.
> 
> 
> Nazlie Saeedi, P.E.
