### ISSUE TITLE
[BUG] WSOD on Moped teams tab when viewing a certain project

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#7428]
On the deploy previews and https://moped.austinmobility.io/moped/, the WSOD can be found by visiting [project 176](https://moped.austinmobility.io/moped/projects/176/) (Manor Rd. from Dean Keeton St. to US 183) and clicking on the “team” tab. 

When discussing the issue with @amenity, she recalled that this has been previously observed, which @chiaberry affirmed. I looked through open issues, and I was not able to find an existing issue. Amenity noted that this is related to a user having been deleted, which is not an expected case to happen in production.

**Device**
MBP running MacOS 11.6.

**Browser**
Chrome & Safari

**How would you rate the impact of this issue?**
Major — can only perform work using a workaround

**Additional context**

**Comment by amenity** [comment]
Thanks, @frankhereford! I actually meant _closed_ issues. I found [this PR](https://github.com/cityofaustin/atd-moped/pull/314) but that was responding to `Cannot read property 'first_name' of null` whereas the console errors I'm seeing this time are `Cannot read properties of undefined (reading 'workgroup_id')` ...

Could still be a deleted user, being as that it's the "Teams" tab.

**Comment by amenity** [comment]
Shouldn't happen in theory b/c we won't delete users, but might as well add the small bit of code that causes the error. @sergiogcx said just needs a `?` ...

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/441

## Live demo:
https://deploy-preview-441--atd-moped-main.netlify.app/moped/projects/176?tab=team

## Screenshot:

![2021-10-21_15-45-13.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/779a087c-f3e3-4324-9514-a1f864f71828)
