### ISSUE TITLE
New UC Folder Review Fee needs to be added to UC Folders with a "Pending Customer Action" status upon submittal

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7429]
CPO needs to have UC Folder folders  (or come from the Site Plan or GEP folders), that are "Pending Customer Action" from the self assign process to have the UC Review fee added when Customers complete the application (submit the action required). This is an addition to #6401

Stakeholders: Jaclyn, Isaiah

Acceptance Criteria:
When the applicant makes the required actions on anything that has a status of "Pending Customer Action", 
-  The UC folder should trigger the UC Review fee to be inserted once the applicant submits whatever is needed/or the application. 
-  The folder status should change to "Internet Pending" Once the UC Review fee is paid, This only applies to the SubTypes PVT and anything not Franchise".
​-   If the SubType is Franchise, after the applicant completes the application, no fee is inserted and the status should be "Internet Pending".

**Comment by TracyLinder** [comment]
We won't be able to do this work until the UC self-assign features are working again.

**Comment by TracyLinder** [comment]
I added the fee component to ticket #5892, so I will close this as a duplicate.
