### ISSUE TITLE
Project: TDSD App, Additional Phase(s)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#743]
## Description
Many out of scope needs were identified during the first phase of the Development Review App. This project will identify deliverables that can be developed in subsequent phases. 

### Resources
- Link to folder in Sharepoint or Drive where project docs are stored
- Link to Project Brief - [template here](https://docs.google.com/document/d/1omjuT_T9ZRO87yFJ_EQ3IFxWL8jAdoLCOTSknU7PGyE/edit#heading=h.h5hsw4rbm6wg)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://transportation.austintexas.io/about/) team. Project status is documented regularly in the comments below.

**Comment by TracyLinder** [comment]
**Update:**This has been scoped - I need to get this project updated & moved to the backlog.

**Comment by amenity** [comment]
Sticking this in _In Progress_ @TracyLinder !

**Comment by TracyLinder** [comment]
@amenity there's an Index issue already in progress for the work we're doing #2526. I'm going to rename this to phase 3 and stick back in the backlog.

**Comment by TracyLinder** [comment]
I'm closing this. It's like a place-holder for future projects, when we should really be capturing that project when the need arises.
