### ISSUE TITLE
Builder huddle: Knack <> Citybase Integration

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7437]
Schedule for Weds, 10/27

[Technical files](https://cityofaustin.sharepoint.com/sites/CitybaseImplementation/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2FCitybaseImplementation%2FShared%20Documents%2FGeneral%2FTechnical%20Docs&FolderCTID=0x01200016DA610C58D4C24FA76DA0BB07B739CA) from CityBase Teams Team

**Comment by moorerst** [comment]
Builder huddle complete. Closing this issue. Setting up Spike with Dev team to evaluate Citybase in Knack.

- Reviewing technical documentation

- Reviewing Controller's Office existing integration for Short Term Rental payments
