### ISSUE TITLE
Meeting: TDSD Phase 2 Discovery 11/19/19

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#744]
### Objective 
Many out of scope needs were identified during the first phase of the Development Review App. Let’s look at what was identified, and discuss how we might move forward with meeting those needs. 

### Participants
Tracy, Sangeeta, Amber, Joe, Nathan

**Comment by TracyLinder** [comment]
## Identified Needs
1. TDS Mitigation Tracking
2. AMANDA Integration 
3. TIA Case Management Spreadsheet 
4. TDS Waiver Tracking

### 1. TDS Mitigation Tracking

- **TDS Mitigation Program Basics:**
    - A development is likely to affect traffic on adjacent streets
    - ATD seeks to mitigate these affects on traffic by making requirements of the development
        - e.g. A dedicated left turn lane must be built
    - The development has 2 choices regarding traffic mitigation:
        - Comply with the requirements (build the left lane)
        - Pay a mitigation fee to ATD, in lieu of complying

- **Mitigation Fee Basics**
    - ATD started collecting this money in FY 18/19, however it has been collected as part of the review process for 20+ years
    - The mitigation fee collected has certain restrictions:
        - Must be used in 10 years; then the development can request a refund
        - Must be used to implement the mitigation(s) it was collected for (all or part). e.g. Has to be used on that left turn lane; can't be used on a traffic light if the light wasn't identified in the mitigation review
        - Restrictions on how the money is spent change based on the regulations in place when the money was collected

- **Misc**
    - ATD hired AECOM (in the last 6 months) to compile the mitigation fee data identified to date. 
        - More info needed
    - A similar process exists that allows certain developments to pay a fee in lieu of building sidewalks. The money goes to Public Works.
        - Public works has done a good job at using that money to build sidewalks. 
        - John Eastman is the program contact

- **The Need**
    - The people/groups (stakeholders) who are able to use this money need to know it exists, and is available
        - Stakeholders: Active Transportation, Arterial Management, CPO, Signals, Public Works, Amica's new PM group
        - e.g. Public Works can use the money to build sidewalks required by mitigation
        - e.g. ATD signals can use the money to perform the signal work required
        - A map is an ideal starting point
    - TDS needs a case management tool to manage everything that happens after the fee is paid
        - What mitigation was required, how much did we collect for it?
        - Has the mitigation been performed?
        - How much longer do we have to use this money?
        - For completed mitigation, what info needs to be collected? e.g. who did it, total cost...

### 2. AMANDA Integration

- **Basic Info**
    - There is a level of overhead required in using the TDS KNACK app, because staff must manually enter all cases, even though the data being entered already exists in AMANDA 

- **The Need/Request:**
    - A KNACK feature that will auto create TDS cases, based on AMANDA data. 
    - Include TDS data in the DTS AMANDA open data project
        - It's possible that DSD is already publishing some of this data. Tracy needs to research 

### 3. TIA Case Management Spreadsheet

- **Basic Info**
    - A spreadsheet maintained in SharePoint
    - Used for case management & reporting of TIA reviews
        - Link to the spreadsheet [here](https://gcc01.safelinks.protection.outlook.com/ap/x-59584e83/?url=https%3A%2F%2Fcityofaustin.sharepoint.com%2F%3Ax%3A%2Fr%2Fteams%2FDevelopmentReview%2F_layouts%2F15%2Fdoc2.aspx%3Fsourcedoc%3D%257B8b068972-21b3-497b-9498-ce4effdb65d6%257D%26action%3Ddefault%26uid%3D%257B8B068972-21B3-497B-9498-CE4EFFDB65D6%257D%26ListItemId%3D25%26ListId%3D%257B576C1B99-0EF0-44EA-9AC1-467483224630%257D%26odsp%3D1%26env%3Dprod%26cid%3D873b9569-de49-428b-a70f-550f756dad2f&data=02%7C01%7CTracy.Linder%40austintexas.gov%7C76f8bb0c9fd54a60419608d769435be5%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637093610330353488&sdata=dUIWiBE2%2FwnK4FPGkU9usELRc6YQF%2FOmgLNSI%2BHxWf8%3D&reserved=0)

- **The Need/Request:**
    - Staff would like to stop using the spreadsheet, and instead use a more intuitive tool that helps them do their work
    - The overall need is very similar to the TCP tracking app on the data tracker
    - TIA reviews are often related to a TDS reviews (cases), but not always. For those that are related, a feature that allows users to reference the related case. e.g. When viewing the TDS case in KNACK, click a link to open the related TIA case.
        - Should be a 1:1 relationship
    - A feature to assign vision team reviewers as needed, similar to TDS app

### 4. TDS Waiver Tracking

- **Basic Info**
    - During the development review process, TDS is asked to waive certain standards
        - e.g. Standard driveway width is 24', developer requests a waiver for their driveway to be 22'
    - Each case can have multiple waiver requests, with multiple results
    - This is currently happening via email 

- **The Need**
    - Currently no data exists on these waiver activities
    - Useful waiver data includes:
        - Number of waivers, grouped by the standard/ordinance being waived. e.g. In 2017 we received 35 requests to wave the driveway width requirement. 30 were approved. 
        - Waivers grouped by council district
            - In 2017 we approved 30 driveway waivers; 15 of them were in district 10. 
    - Staff views this potential data entry as a large amount of staff overhead that may not be proportionate to the potential benefits of collecting the data. 
        - Staff will escalate this as a need to DTS when/if needed.

**Comment by johnclary** [comment]
@TracyLinder create issues for AMANDA integration and for the TIA Case Management spreadsheet

**Comment by TracyLinder** [comment]
Phase 2 will be documented in #2526. Closing this.
