### ISSUE TITLE
Publish contractor work orders to AGOL & Open Data Portal

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7440]

**Comment by dianamartin** [comment]
I've asked Andrew to create the required AGOL feature class
- Christina mentioned that they'd also like this contractor data set from Knack to ODP and would like the last two fields like the "Roadway markings" data set. 
- `Road Class`
- `Total Segment Miles`
![image](https://user-images.githubusercontent.com/21112975/182662920-2221d5c5-e6cd-4e56-b6d6-77214d52d164.png)

She said that John had done if for them somehow. @johnclary Do you know if a dev should just use the roadway markings script you made?

**Comment by johnclary** [comment]
If the contractor work orders have street segment IDs (just like the non-contractor work orders), then, yes, we should re-use the existing script. Hopefully just minor tweaking needed.

**Comment by dianamartin** [comment]
Yes, it is modeled the same

**Comment by dianamartin** [comment]
This is a dupe of # 7434
