### ISSUE TITLE
Create an API view of contractor work orders

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7441]
Karo notes 2022/07/14: 

SMB 
API Views page
Private view 
Notes / model [here](https://atd-dts.gitbook.io/atd-knack-operations/knack-integrations/arcgis-online-integration)

**Comment by dianamartin** [comment]
# Steps
SMB Tracker
Pages>API Views (Private)

- [ ] Create a table view of "contractors table" 
- [ ] Add all fields that stakeholder needs

**Comment by dianamartin** [comment]
Add these fields to API
- Work Group Category
- GIS QA
- Street Segments

**Comment by KaroEngstrom** [comment]
W 7/20/22 

- [ ] Added Work Group Category, GIA QA, and Street Segments to the new table (bottom of the page [here](https://atd.knack.com/signs-markings#api-views-private/))
