### ISSUE TITLE
Update script to publish Signs and Markings Contractor work orders to AGOL

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7442]
Andrew completed creating an AGOL layer for the "Contractor Work Orders", this is ready to give to a dev. Will need to bring up at next Product Sync.

The ETL will need to be created in Prefect.

**Comment by dianamartin** [comment]
# 8/10
New script ETL needs to be created for Contractor Work Orders 
- Add API View (scene): 
- Contractor Work Order (table): 

@KaroEngstrom can you please add the scene and view number to this issue.

**Comment by KaroEngstrom** [comment]
Th 8/11/22
* API View (scene): 1249
* Contractor Work Order (table): [View 3628](https://builder.knack.com/atd/signs-markings/pages/scene_1249/views/view_3628/table)

**Comment by dianamartin** [comment]
# New Contract Work Order Script Details
### Details
- API View (scene): `1249`
- Contractor Work Order (table): [`View 3628`](https://builder.knack.com/atd/signs-markings/pages/scene_1249/views/view_3628/table)
- AGOL Rest API: [`7eb2da1d8e6c4f79b368d8e295dec969`](https://austin.maps.arcgis.com/home/item.html?id=7eb2da1d8e6c4f79b368d8e295dec969&view=service)

### Reference this script
The marking work order feature layer is a polyline and so is this contractor work order feature layer. 

`line 158- 167`

```
  "signs-markings": {
        "view_3099": {
            "description": "Markings work orders",
            "scene": "scene_1249",
            "modified_date_field": "field_2150",
            "service_id": "a9f5be763a67442a98f684935d15729b",
            "layer_id": 1,
            "item_type": "layer",
            "location_field_id": None,
            "socrata_resource_id": "nyhn-669r",
```
and this one

- [agol_build_markings_segment_geometries.py](https://github.com/cityofaustin/atd-knack-services/blob/9672797fe9e79b7c7f2158769b610febc8200513/services/agol_build_markings_segment_geometries.py#L33) - markings work order line features. it has a config with the layer info

@johnclary let me know if I've got all the details for Charlie

**Comment by dianamartin** [comment]
Check Layer Level - ArcGIS Services
![image](https://user-images.githubusercontent.com/21112975/185444547-3337480e-2999-42be-
abe7-28bf18f5cdb0.png)

**Comment by dianamartin** [comment]
Synced with Christina and she said that they'd like to have just a a table for the "contractor work logs" going to Open Data Portal. I'll can create a new issue for that.

**Comment by Charlie-Henry** [comment]
I was able to get something working in Prefect that is downloading the data from Knack and then passing it onto AGOL. It follows our past schedule pattern of 2:30PM and 6:30PM. 

I also have implemented the `agol_build_markings_segment_geometries.py` step. Looks like there is "0 features to process" because we are waiting for Christina T to QA/QC some for us to test.

I'll build out our Prefect knack services more next week!

**Comment by dianamartin** [comment]
8/19: User asked about frequency, I let her know it's scheduled to run at 2:30 pm and 6:30 pm

**Comment by Charlie-Henry** [comment]
@dianamartin I'm curious if Christina has had a chance to QA/QC the GIS data because I'm still seeing `0 features to process` in the build geometries step.

**Comment by dianamartin** [comment]
@Charlie-Henry She said she's actually doing some of the QA/QC now, until 3:30 pm. So maybe you can run it then, we'll be in an interview panel.

**Comment by patrickm02L** [comment]
@Charlie-Henry follow up with Christina T. and then close out when done.

**Comment by dianamartin** [comment]
@patrickm02L @Charlie-Henry I'm closing this, we closed the related issues already.
