### ISSUE TITLE
Build Knack interface for GIS QA on contractor work orders

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7444]

**Comment by amenity** [comment]
Now we're at the point we're getting all the work orders coming through Knack, this is now a higher priority ask from SMD. 

Christina said it would be helpful if it was similar to Markings QA where they submit segment IDs.

**Comment by amenity** [comment]
@andrewshensky - ~when do you need us to set this up in Knack?

**Comment by andrewshensky** [comment]
@amenity I'm not aware of any timeline on this. I can work with @dianamartin and Christina on anything that will be needed on my end.

**Comment by dianamartin** [comment]
@andrewshensky this is a markings feature, but contractors completing the work. It should be similar to the marking work order feature in AGOL.

**Comment by dianamartin** [comment]
# Need to Add to Contractor Work Orders
- [ ] `Work Group` Category: longling, shortline - multiple choice, multi select 
- [ ] `GIS QA` - Y/N - set default to "No"
- [ ] `Street Segments` - multi-select (markings GIS QA)

**Comment by dianamartin** [comment]
Synced with Christina 8/3
- would like to add new button
![image](https://user-images.githubusercontent.com/21112975/182652535-2cbf11da-9360-4581-a1b7-18a46d363972.png)

**Comment by dianamartin** [comment]
Added code for "GIS QA | Contractor"
![image](https://user-images.githubusercontent.com/21112975/182679781-af2b7c0d-b18c-4b4c-831b-e9d3bd8caec7.png)
- [ ] Submitting PR for peer review
