### ISSUE TITLE
[BUG] Can't add study record to Location Details page

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7450]
Renee O
AMD.

Emailed
>I have one question, I was trying to add a signal Study to the I35 @ 4th street location and it would not allow me to add a study here.  Is that because it is already in design?

>Also there are 2 locations for this signal, since there will be a signal on either side of I35.  Would this be better handled in the “signal” phase where one signal is the primary with the other signal being secondary; instead at the request/study level?  The location IDs associated with this signal are:  LOC18-012505 & LOC19-015140

Issue:
- Can not add study from Location details page
- How to handle duplicate intersection (E and W) of signal request?

**Comment by amenity** [comment]
@dianamartin - check again w Renée, plz :)
