### ISSUE TITLE
Get shapefile of driven streets from RAS

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7454]

**Comment by andrewshensky** [comment]
We have been given access to this data through a group in AGOL. There is no "Date Driven" field included in the data, which is necessary to track installs and removals that take place after streets are driven. I have communicated to Christina that a date field will need to be included. She will be reaching out to RAS so they can add the date driven data.

**Comment by andrewshensky** [comment]
Access has now been provided to a new layer in AGOL called "Austin Daily Progress Master". Per RAS, this is the official layer that shows areas the have been scanned. A date field has been included and although it stored as text, we can now incorporate this data into our processing for mapping existing signs from work orders
