### ISSUE TITLE
[TDS-TIA] Enhancement: Include Project Name in Email Titles

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#7456]
Reviewers would like to remove the Request # and add the Project Name to email titles instead.

**Comment by ChrispinP** [comment]
TIA Emails updated to include Project Name and removed TIA Case ID & Request # 
![image](https://user-images.githubusercontent.com/67915167/137398419-7031281e-5d18-4ca6-835e-cf1c842bd3f6.png)

ready to review

**Comment by TracyLinder** [comment]
I emailed Joan to inform her that this update was made 20 days ago. Closing.
