### ISSUE TITLE
Create Bond Log for SMRT

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7458]
The Bond and Rider ID are always going to be the same number. Instead of entering the Bond ID and Rider ID how might we be able to tie them together?

**How the Bond Works**

A Bond will be affected when there's an increase in devices and amount. For example: they could increase the Rider; the Rider is like an amendment to the bond. 

If the Bond runs out, the Rider also runs out unless they get a continuation certificate which extends the life of the Bond and the Rider. 

Right now there's no relationship to see how many times the Bond ID has been extended. 

**We'll need to figure out**
- What the Bond ID parent looks like and what the children (Riders & Continuation Certificates) are
- How to display that in the Bond form
- How to display that in the table for each Provider

**Considerations**
- The dates for the Continuation Certificates will change because they'll change the life of the bond. There will be a start and end date.
- The Riders could increase the amount of the bond.
- Effective date of the Rider changes.

**Comment by dianamartin** [comment]
# Diana's Notes from feedback sync

Create `bond_log` object to have the ability to track the events that change with the bond. 

- Increase/Decrease the bond amount (which results in a Rider "Amendment")
- Continuation Certificate (an extension of the bond after the initial expiration date)

Fields to Create: 
- [ ] Type
- [ ] Amount 
- [ ] Effective Rider Date
- [ ] Cert Start Date
- [ ] Cert End Date

Ex. 
Bond
`bond log`
- Rider – increase Action? – Amount, Effective Rider Date
- Rider – increases Action? – Amount, Effective Rider Date 
 - Continuation Certs – Start, End Date
- Continuation Certs - Start, End Date
- Continuation Certs - Start, End Date

**Comment by dianamartin** [comment]
Updated Insurance Details page, was really Bond Details
- Updated url slug and page name

Added to Bond table
- Count of Rider field
- Count of Continuation Certs field
