### ISSUE TITLE
Project: Improved Annual Signal Retiming Management

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7462]
Make it easier to update signal retiming corridor assignments in Data Tracker while preserving the corresponding open data sets and [Signal Timing dashboard](https://data.mobility.austin.gov/signal-timing/). 

The acronym for this activity is Annual Signal Retiming (ASR) Management.

## Background
The system we have in place for corridor management in Data Tracker was designed quite a long time ago. The current data structure allows for that and enables to us to produce the maps on the [signal timing dashboard](https://data.mobility.austin.gov/signal-timing/).

## References
- [Data Tracker interface](https://atd.knack.com/amd#sync-corridors/?view_367_filters=%5B%7B%22value%22%3A%22ACTIVE%22%2C%22operator%22%3A%22is%22%2C%22field%22%3A%22field_533%22%7D%5D)
- [Signal Timing Data and Performance Hub dashboard](https://data.mobility.austin.gov/signal-timing/)
- Open data sets
   - [Traffic Signal Re-Timing](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Signal-Re-Timing/g8w2-8uap)
   - [Synchronized Traffic Signal Corridors](https://data.austintexas.gov/Transportation-and-Mobility/Synchronized-Traffic-Signal-Corridors/efct-8fs9)
- Intial service request: https://github.com/cityofaustin/atd-data-tech/issues/7421

_Requested by Lance B. and Brian G., Arterial Management_

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by johnclary** [comment]
Diana is going to [refine the prototype](https://github.com/cityofaustin/atd-data-tech/issues/7421) based on our recent discussion with AMD.

The AMD folks weren't sure how they want to track re-retiming data in the future (e.g., before/after travel time). They need to sort that out before we can estimate level of effort for (1) additional Data Tracker enhancements for re-timing and (2) enhancements to the signal-retiming performance dashboard.

**Comment by amenity** [comment]
_Meeting today w/ @dianamartin, @johnclary, Lance, Jonathan, Brian C._ 

New corridor retiming: approach
- Corridors are broken up and now fully contained within a retiming zone
- All signals in a zone re-timed at once
- Metrics reported at the corridor level using INRIX data
    - Before/after retiming weighted average travel time on a section of a corridor in a given zone
    - Yes, can be gathered at that granular point-to-point scale 

Next steps
    - AMD is going to review naming conventions
    - AMD is going to propose how to store the retiming data in Data Tracker, i.e. what fields they will need

**Comment by dianamartin** [comment]
I was able to sync up with Brian G. and he wanted to update the Signal Engineer Areas for the Signals first. I believe Lance was looking into the data to determine how they (AMD) wanted to track details pertaining to metrics of the program. He said the corridor revamp can happen sometime in February, so we can follow-up with them next month.

**Comment by amenity** [comment]
Per our meeting last week with AMD, they are going to discuss how they want to move forward with metrics for this.
