### ISSUE TITLE
‼️ CRITICAL: TURP Folder Issuing w/ Application Fee Payment

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7466]
[12:37 PM] Perez, KimberlyImportant!
    Starting 10/13/21, all TURPs with fees were automatically issued without a review once the (new permit) fees were paid. These turps went to an "Active" status after the payment was made. This is a CRITICAL Issue! Nader, Nadin Linder, Tracy

RSN's:
12800422

12800557

12800728

Isabell has changed all current turps back to internet pending.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder 
Izzy mentioned that this was resolved/not happening anymore. I am closing this per my chat with Izzy and Paloma. We agreed to close this at 4pm today if the issue did not happen again.
I am also closed #7327 as well
