### ISSUE TITLE
BUG: Jaclyn would like to stop the creation of UC folders from the GENP folder

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7468]
Jaclyn would like to **stop** the creation of UC folders from the GENP folder. The GENP folder is creating a UC child folder at the 30% submittal attempt, in the GENP review process.

Stakeholders: Jaclyn, Isaiah, Greg P.

Here is the GENP ROWID:
12800519    Here is the UC folder it created: 
12800988

**Comment by TracyLinder** [comment]
My Thoughts:

To my knowledge there has never been a feature on the GENP folder that would generate a child UC folder. So my 1st question is why is this even happening?
