### ISSUE TITLE
HR App Data Review

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7476]
- [x] Add date of hire when creating new record in knack - WORKING (Lawrence M.)
- [ ] Add created_date when creating new record in knack - HAVE TO CHECK NEXT WEEK
- [ ] Add user_role of Staff to new records - HAVE TO CHECK NEXT WEEK
- [x] If employee's class is contractor do not mark as inactive - WORKING (Lawrence M.) 
- [x] Update Banner Division Name with information in banner field divn_name - WORKING (Lawrence M.)

**Comment by dianamartin** [comment]
# Notes
- [ ] make up email address for users that have "No email addresses". we'll use the first.lastname@at.gov naming schema. 
-

**Comment by dianamartin** [comment]
@chiaberry will update the "no email address" script and add Melissa and Gadius into the system

**Comment by moorerst** [comment]
Updated script ran successfully. Closing this issue.
