### ISSUE TITLE
New COS infos on UC Folder (ON PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7478]
### Adding existing COS infos & creating 2 new infos. 
----

### Acceptance Criteria

All changes/additions mentioned below are for the UC folder in AMANDA.

**Changes to Existing Info**
- Info field Sub Project ID # (#6868) should be displayed under Cost of Service Info Group
- Info fields 'Fund', 'Department', 'Unit', 'Object', 'Work Order #' and 'Sub Project ID #' needs to be added to all UC folders.

**New info to be added (to all UC folders)**
1. Partner Department 
- Info Description: COS Partner Department? 
- Info Type: Boolean
- Required for Insert in Back Office
- Visible and Mandatory in Portal 
- Add help text to info in Portal:  'Is this application for a Cost of Service City Department?'

2. Type of Partner Department
- Info Description: Partner Department Name
- Info Type: Choose
- Pick Values: 
-- Austin Energy
-- ATD
-- Austin Water
-- Corridor Program Office
-- Public Works
-- Watershed Protection
- Create info validation: This info is mandatory in Back Office and Portal IF Info 'COS Partner Department?' is answered 'Yes'. 
    - Throw error if value is null & COS Partner Department is Yes: Partner Department Name is required when info COS Partner Department is YES.

**Comment by vschandramouli** [comment]
Completed AC. Ready for Review/Backlog. Pasting previous notes on ticket in this comment for reference. 

** Existing infos**
- Four FDU infos (Fund, Department, Unit, Object)
- Work Order # 
- Sub project ID #  (can we group this info with the COS info group?) #6868 

**2 new infos:**

- COS Partner Department? (Y/N) with help text 'Is this application for a Cost of Service City Department?'
- COS Department Name - Pick List - identical to EX subtypes

**Comment by TracyLinder** [comment]
Assigned to Subha; going on deck. High priority for this sprint.

**Comment by TracyLinder** [comment]
@Nadin-Nader or @vschandramouli can you please help facilitate UAT on this as soon as possible?

**Comment by Nadin-Nader** [comment]
@TracyLinder @SubhaShroff I have UATd this on TEST and it looks good. I will send an email to Paloma asking her to test this as well.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder looks like there may be an update to the list for UC. Waiting on results from Jaclyn's UAT

**Status:**
Waiting on Jaclyn's UAT results

**Comment by SubhaShroff** [comment]
### Status:
Waiting on Jaclyn's UAT results.

**Comment by Nadin-Nader** [comment]
@SubhaShroff i spoke to Jaclyn and got her UAT notes for this. She said;

> [Yesterday 3:33 PM] Lozano, Jaclyn
>     Yes I submitted the test application and now I'm going through the UC folder. Isaiah mentioned we would need to remove Project Connect from the drop down menu and add "PAR COA Parks & Recreation". Also Watershed Protection has an extra 's' at the end. 

So the Partner Department Drop Down list we will need to remove Project Connect and add "PAR COA Parks & Recreation".
We also need to fix the extra "S" at the end of Watershed Protection

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The above mentioned changes are done and committed. After your approval, I submitted SCTASK0178252 for DEV deployment request.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The deployment is done. Here are the changes reflecting in DEV. Can we move this change to TEST?
![image](https://user-images.githubusercontent.com/51680715/140336728-7eef9203-32f6-41d0-b80c-2149a5b4e1e7.png)

On Portal:

![image](https://user-images.githubusercontent.com/51680715/140336577-02797659-bf32-4e0e-8827-0245ed604e61.png)

**Comment by TracyLinder** [comment]
**Email to Stakeholders**

Howdy UC Team,

I want to make you aware that I directed Nate not to make the updates you requested yesterday to the list of values in the Partner Department Name field,. 

The list of departments must be limited to our COS Partner Departments, which are: ATD, AE, AW, PWD, WPD, and CPO. Parks & Project Connect are not COS partners and therefore will need to pay per invoice as private developers do. 

Please let me know if you have questions or concerns. 

Thanks,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
### These are the COS Partner Departments 
<img width="502" alt="Screen Shot 2021-11-04 at 3 32 42 PM" src="https://user-images.githubusercontent.com/49930868/140415807-f7e04819-6d65-4f4c-ab62-191fbaea1afc.png">

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  submitted SCTASK0178740 to remove "PAR COA Parks & Recreation" from the list.

**Comment by Nadin-Nader** [comment]
**Status:**
On TEST but changes made still need to go to DEV. TASK for changes to DEV is SCTASK0178740

**Comment by Nadin-Nader** [comment]
@SubhaShroff the changes have been deployed to **DEV** Please UAT

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Its tested on DEV, ready for TEST deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0179344 is submitted for TEST deployment.

**Comment by SubhaShroff** [comment]
### Status:
I have to test for removal of Project Connect and PAR from the list on TEST.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to **TEST**. Please UAT and make sure its ready for UAT with the stakeholders.
Moving to Review/QA column

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder The ticket is tested on TEST. The Partner Department Name list is updated and ready for UAT.

![image](https://user-images.githubusercontent.com/51680715/141820796-230b593f-f075-47e4-9414-c4fe1a143aba.png)

**Comment by Nadin-Nader** [comment]
@SubhaShroff Jaclyn has approved the move to PROD.

**Status:**
## Approved for **PROD** Deployment

**Comment by SubhaShroff** [comment]
@Nadin-Nader  PROD Deployment request is submitted - SCTASK0181346.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to PROD. I will send an email informing the Stakeholders and close it.

**Comment by Nadin-Nader** [comment]
**Status:**
On PROD. Will close by Friday (latest). Email sent to stakeholders (see below):

> Good Afternoon,
> I hope everyone is doing well. I was reaching out to inform you that the New COS Infos for the UC Folder are on PROD and have been since Friday. I will keep the request open for another day or so and will close it by Friday (at the latest) if I do not hear of any issues arising because of this.
> 
> Please reach out to me and let me know if something is amiss.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> Product Delivery Manager
> Data and Technology Services
>

**Comment by SubhaShroff** [comment]
### Status:
PROD Deployed and Nadin informed the stakeholders in email.

**Comment by SubhaShroff** [comment]
### Status:
PROD Deployed a week ago. Waiting to close.

**Comment by Nadin-Nader** [comment]
Closing as i have not heard about any issues for this
