### ISSUE TITLE
Update TDS AMANDA Permissions on GF Folder

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7481]
### Update TDS staff permissions on GF as needed for #5538 

- [x] Sangeeta Jain
- [x] Amber Mitchell/Hutchins
- [x] Bryan Golden
- [x] Nathan Aubert
- [x] Nazlie Saeedi
- [x] Justin Good

**Comment by Nadin-Nader** [comment]
Automation has updated Bryan's AMANDA PROD profile/closing card
