### ISSUE TITLE
[CORRECTION] Restock quantity from 50,550 to 50,000 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7482]
Ronnie/Johnny
AMD

Ronnie emailed Johnny
>Can you edit the restock to only reflect the quantity that was on the original DO?  If so, it seems like editing that and then doing another restock transaction for the overage quantity when the new DO is created would be the way to go.  If the existing restock quantity cannot be edited, then we will likely need to get with John or Diana to see if they can edit (or otherwise fix) the restock transaction for us.  While the total quantity that was entered on the restock and the resulting total value reflects what was received, it only references the original DO and both the quantity and value on the restock exceeds the quantity and value on that DO.  

I replied
>I believe we can edit the existing restock unit price. Johnny and I had an instance where there was a duplicated restock transaction that we corrected on the back end. We can discuss tomorrow at the inventory meeting. Yes, John is out the whole week and returning the following week. Let know if this correction is urgent so we can prioritize accordingly. 

Ronnie replied to me
>The quantity on the restock transaction will need to be reduced to 50,000 to match the quantity on the DO.  The restock unit price is correct.  Since the on hand quantity is so low (17) and the restock quantity is high (50,000), the quantity reduction on the restock transaction will have a negligible impact on the new unit cost.  It looks like it will remain at $0.8499

>Once the existing restock transaction has been revised and a new DO issued for the overage quantity, Johnny can do another restock transaction for the extra 550 feet.  The unit cost on the new DO should be the same as on the original DO.  According to my manual calculations, the new unit cost will remain at $0.8499 after the correction to the existing restock transaction and the entry of the additional restock transaction.

Stakeholder is requesting
>To change the `Composite Camera Cable Double Braid 75 ohm coax` from quantity 50,550 to 50,000 because the vendor didn't deliver that much material.

**Comment by dianamartin** [comment]
I updated `TXN 13228` from 50,550 to 50,000 on 10/18/21.
![image](https://user-images.githubusercontent.com/21112975/137812877-84e12298-8061-42e3-8942-609cf144bfba.png)

**Comment by johnclary** [comment]
Yes—resolved and customers notified.
