### ISSUE TITLE
Create 3 New COS Fields on TCP Tracker Case Details

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7484]
Add three fields to the TCP Case Details view. 

1. Work Order #
2. Sub-Project ID #.  
3. AMANDA Bill # (numeric)

- Alphanumeric
- Not Mandatory
- Include on both Add and Edit forms
    - Location: Under CIP and before Project Notes

**Comment by ChrispinP** [comment]
@TracyLinder any further adjustments needed for these ROW COS fields?

**Comment by ChrispinP** [comment]
Reached out to Robert, no issues or adjustments needed for these fields.

Closing
