### ISSUE TITLE
[BUG] Moped project status not synchronized between comment and summary tabs

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#7493]
1) When a status is deleted from using the comments tab on a project in Moped, the status disappears from the list as expected. However, when you return to the summary tab, the status remains visible, including after a full refresh of the page. I anticipate that a WHERE condition needs to be added to the query that pulls the project comment data or logic to avoid displaying a comment that has been marked as deleted.

2) Related, but ever so slightly different issue: When a status is edited via the comments tab, it is not updated in the state variable that provides the content to the Summary tab's display of status, so changes won't show up until the page is reloaded. 

![image](https://user-images.githubusercontent.com/3653206/138101205-c55d7da9-b9cf-4bd0-9edd-020e4cf48192.png)

**How would you rate the impact of this issue?**
Minor  — can perform work, but could be easier or faster

https://user-images.githubusercontent.com/1463708/137571231-b0732570-4a38-4c86-b0e5-11b4c39f9a86.mov

---
### See also 
- https://github.com/cityofaustin/atd-data-tech/issues/7471
- https://github.com/cityofaustin/atd-data-tech/issues/7473

**Comment by amenity** [comment]
@tillyw @chiaberry - can y'all size this please?
