### ISSUE TITLE
Go Live: Parking Meters Non 311 Service Request

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7503]
Go Live scheduled for 11/1

**Action Items:**
- [x] Update CSR map for Service Request details page for PM
  - [x] Created a [pull request](https://github.com/cityofaustin/atd-knack/pull/72) to change the code
- [x] Create new SR Details for PM
- [x] Configure Resource Tracking for PM (separate) stuff
- [x] Updated "Manage Accounts" page for PM Admin
- [x] Add Parking Meter staff to system
- [x] File Attachments
- [x] Meet with Parking Enforcement team
- [ ] Training with Parking Meters tech lead

**Comment by moorerst** [comment]
Meeting with Parking Enforcement scheduled for 10/18

**Comment by moorerst** [comment]
List of techs to be added to the system:
David Smith
Steve Slawson
Gilbert Marrero
Jose Aviles
Julio Woolf
Wilber Santiago
Ali Merabtene
Robert Boatman
Steve Smith
Kyle Baldwin
Roy Flores
Dworski Paul
Jeremy Stephens

**Comment by dianamartin** [comment]
- [x] Updated new "CSR Activity" choice: `Repair/Replace`
- [x] Updated new staff permissions - we will have to finalize this with a follow-up email on who needs "PM Admin" access @moorerst 
- [x] Updated notification emails from "Officer" just the Assigned Name

**Comment by dianamartin** [comment]
Closing, we have another issue # 7650 that is working on training documents for Parking Meters and Parking Enforcement
