### ISSUE TITLE
Create invoice notes in SMRT

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7515]
In the meeting on 10/22/21, Andrea asked for the ability to add notes to the Invoice. 

She noted that the internal notes that were created were not populating in the invoice and wondered if we could include that kind of functionality. We determined that the invoice notes should be separate from the internal notes, so we'd need to create the ability to add notes to the invoice.

Also discussed adding a place for notes on the Invoice Details page.

**Comment by patrickm02L** [comment]
Show at Sprint on Friday, Nov 5.

**Comment by dianamartin** [comment]
Showed to stakeholders, they had no additional changes. Closing
