### ISSUE TITLE
[Feature] Ability to track inventory item order status

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7526]
There was conversation on tracking the inventory items that are or order, not received yet
- Would be nice if we could link the inventory items to their PR numbers, if not then having a way to reference the order on the inventory item. I know we've talking about linking the two in the past. 

They'd want to track this information: 
- `PR Number`: Ex. `2021-10-21001`
- `Purchase Order Status` - would be like:
  - On Order
  - Shipped
  - Received
  - Complete
  - Backordered
- `Estimated Received Date` - this would be on the material planners once they sync with the vendors

**Comment by amenity** [comment]
@dianamartin will prototype this in TEST to demo to stakeholders.

**Comment by dianamartin** [comment]
@johnclary I've prototyped an [Inventory Item Order Status Report](https://atd.knack.com/backup-apr-23-2021-finance-and-purchasing-system#inventory-report/) so we can review tomorrow

**Comment by dianamartin** [comment]
@johnclary still need to sync up on this, right?

**Comment by dianamartin** [comment]
@johnclary not sure where this is..

**Comment by johnclary** [comment]
We delivered this functionality and demo'd to users in late January. 
https://atd.knack.com/finance-purchasing#inventory/?view_790_filters=%5B%7B%22field%22%3A%22field_370%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%22ACTIVE%22%7D%5D
