### ISSUE TITLE
Develop prototype for Banners Permits and Payments in Knack

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7530]
Met with stakeholders to review what we learned in the discovery meetings for the Citybase online payment process. 

Stakeholders are ok with the timeline. In the meantime we will begin developing a prototype for external facing application using some of the requirements we discussed

Discussions
Mailed Application discourage this process
try to only do online payments only

Debit/Credit
Have ACH option too
Cathy said customer do ask for invoice

Proposed Process
Customer - application
PENDING
Location verification
APPROVAL
PAYMENT

FUNCTIONALITY

 Attachment for Design
 Reporting
 Comments back to user - email functionality
 Email automation to customer when status is "REMOVED"
Can make installations on Monday?

Can add content language
Have user choose following day if Holiday falls on Monday
REMOVE OTS APP FIELDS

 Non-Profit Status
 Alternate Phone No.

**Comment by dianamartin** [comment]
Created 
- `Portal` - Customer "Home" page
- Splash page - `Get Started`
- `Eligibility` - modal pop-up

**Comment by dianamartin** [comment]
- [ ] PORTAL 
- [ ] APPLICATIONS
- [ ] APPLICANT INFO
- [ ] EVENT INFO
- [ ] DESIGN
- [ ] ADD BANNERS

**Comment by dianamartin** [comment]
Closing this issue, since we are past the prototype stages and the app development is in a soft launch stage.
