### ISSUE TITLE
Build prototype of Bike Share Benefit app

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7534]
To stand up prototype we'll need:

- Re-purpose the current sign up form
- Create backend form details for backend management
    * Staff Access
    * Vendor Access
- Codes page that allows BikeShare of Austin to sign off on codes approval.

**Comment by patrickm02L** [comment]
**Staff sign up tracking and promo codes examples**

[City of Austin Employee Pass Program](https://docs.google.com/spreadsheets/d/1IpYz9ewzzpUR2AsQbMunzJLIW1-iN4o9c81WakoKzzc/edit#gid=0)
[Austin Energy Employee Pass Program](https://docs.google.com/spreadsheets/d/1aQmfsBiB_GY2g7XU7WHXILmmHOGxEI4FRNmMKqamCIQ/edit#gid=0)

**Comment by dianamartin** [comment]
- [x] Created App - `Smart Mobility`

**Comment by patrickm02L** [comment]
URL: https://atd.knack.com/smart-mobility#bike-share-benefits

**Comment by dianamartin** [comment]
![image](https://user-images.githubusercontent.com/21112975/141211118-3746da61-e30a-472b-b0ef-d50ff3b93322.png)

- [x] Updated page name to `manage-codes`
- [ ] Tested adding promo codes
- [ ] Added modified date for all in-line editing fields
- [ ] Added highlight for fields that are editable
- [ ] Added Pivot Report bc it existed on spreadsheet
- [ ] Added quick Add Promo Code form
![image](https://user-images.githubusercontent.com/21112975/141211235-b2802782-f666-4f0d-8ff2-5d32b10e3612.png)
- [ ] Added large redeem button, redeem button only available in "Assigned" status
![image](https://user-images.githubusercontent.com/21112975/141211338-fae3d5b9-15c7-4ec5-8ab6-e6a6d63a5f28.png)

**Comment by dianamartin** [comment]
Showed stakeholder on 12/3

**Comment by dianamartin** [comment]
@patrickm02L do we close this one bc we have other issues for the other outstanding features for them?

**Comment by patrickm02L** [comment]
@dianamartin thanks for flagging this. Yes, we've completed this issue.
