### ISSUE TITLE
Implement single sign-on

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7536]
Set up single sign-on for the app so that multiple Austin staff can have access. 

Refer to [Gitbook documentation](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzNSSXajDFpzOv2IhIv/knack/single-sign-on).

**Comment by patrickm02L** [comment]
@dianamartin as discussed in Sprint Planning 1/26 will put in a request with CTM, then set things up in Knack once we we have access.

**Comment by dianamartin** [comment]
Submitted CTM Ticket `INC0167052`

**Comment by dianamartin** [comment]
I received the CTM metadata file from Michael S.
>Hello Diana, The Enterprise Application in Azure for Knack SmartMobility is setup with SSO using the xml file provided. I set you as the owner and if needed, the link to the application follows. (attached link - you will most likely need the IDP Metadata file, so just in case I've attached it here (attached metadata file)

- I added the x509 cert to the Smart Mobility knack app
- Tested home page

Will update big buttons tomorrow - 2/9

**Comment by dianamartin** [comment]
Created PR and added SSO code to .js file. Awaiting review. 

![image](https://user-images.githubusercontent.com/21112975/153260059-940f4446-d3f9-44b3-a4b2-17ac184e450b.png)

**Comment by patrickm02L** [comment]
This is complete. Need to update Eliza Y.
