### ISSUE TITLE
Meeting: Parking Enforcement Sprint Review 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7541]
•	Review work flow for Parking Meters non 311 Service Request (Parking 
        Meters related issues)
•	Parking Meters team is on board. Discuss Go Live date

- Who needs to have training? 
- Quarterly deletion of resource records

**Comment by dianamartin** [comment]
# Diana's Notes
Training for Officers
- Requesting SRs for Parking Meters

Help Guide - Submitting a SR to Parking Meters
- Adding SR
- Adding Photo

Nov. 8-12
Nov. 15 
PEP

6/8/2021
4600 total - 
3700 records - 
2976 records - 2 months

1. Delete Filter
Every quarter delete 2 months from the date
- calendar reminder
 - November
 - February 
 - May
 - August
- new github template

1. Out of Service Reason
- Inspections - new choice field

Signed in of Knack
One CSR to another
- 

2. NEW REPORT
Officer Metrics
- Created By PEO for PM

Parking Meters 
- Reporting Needs?

3. Prep for Go Live 15th? - Delete Test records
- Testing Week
- Testing Notes
- Last minute changes

**Comment by moorerst** [comment]
Following the meeting PE requested we moved their testing date back to Nov 15th. With possible Go Live week of Nov 22nd.
Created new issues for other items discussed in the meeting. Closing issue.
