### ISSUE TITLE
Create Knack app for managing fee recovery workflows

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7550]
There is a workflow management component to this monthly report for the Cost of Service Program. We will use KNACK to meet this need. John is committing to building the bare bones for the KNACK portion.

**Comment by johnclary** [comment]
We have a basic working prototype in the ROW portal which needs additional feedback from staff. We will refine the app after we complete the November fee updates manually.

**Comment by TracyLinder** [comment]
### Sync

Q: Can we move away from exporting & importing fee data? 
- A: We could make each of them a page in the app where they can see the data. We don't have batch updating in KNACK, so the fastest way for stakeholders to batch approve is with an import.

Idea: Take out the dpt approval from the workflow; reverse it. If they don't object, we assume it's approved. Then we don't need a batch update.

We'll still need to batch update for missing FDUs. Blah. 

**Proposed Workflow**
1. Paloma reviews data
2. Departments log into portal & export their data
3. Departments perform review & add/edit data
4. Department logs in & imports data
5. ATD Finance performs review
6. ATD Finance exports the AIMS template from the portal
7. ATD Finance imports template into AIMS. 
8. ATD Finance manually inputs JVID into raw data & sends to John
9. John imports data back into portal

**Next Up:**
ROW COS Import for Stakeholder Dpts. #8057


How does AMANDA currently get fund data to AIMS?

**Comment by TracyLinder** [comment]
**Sync - John & Tracy - 1/13/22**

- Discussed #8057 (Import feature)
- John will do a spike to determine if this feature is feasible & how we'd do it. 
- Meeting again on 1/25

**Comment by TracyLinder** [comment]
@johnclary I'm going to close this. IMO you got the app stood up. We can manage everything else as feature issues.

**Comment by johnclary** [comment]
yep—thanks!
