### ISSUE TITLE
Robin Contract Renewal

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7551]
Current Robin contract expires 12/31/21
Current contract is for 1100 desk/10 spaces
Team has agreed to renew contract for 500 desk/ 15 spaces

ATD Purchase Request has been submitted

**Purchase was process by CTM Purchasing PR #0012127
Aims CT 2400 20122100180
RQS # is 20120200163 and ecapris  # is 134993.** 
**City of Austin Solicitation - RFQ 2400 KMB0022 - Office Space Management Software**

**Comment by moorerst** [comment]
Ken asked if this needed to be a multi year Master Agreement or a 1 year renewal. Since the adoption of this tool has been slower then expected we opted for 1 year renewal with fewer desk/spaces.

**Comment by moorerst** [comment]
Ken is requesting we reach out to Robin and request a sole source justification letter similar to what was used for the AE Robin procurement. Sent email to Robin contact.

**Comment by moorerst** [comment]
After some back and forth with Robin we received the sole source justification letter.

**Comment by moorerst** [comment]
@dianamartin @johnclary can one of you please sign the document in Ken's email

**Comment by dianamartin** [comment]
- I downloaded and signed the COE
- Emailed stakeholders
>Sorry for the delay. Here is the Certificate of Exemption form, see attached. Just a note, is page 2 supposed to be blank?

**Comment by moorerst** [comment]
Purchase Request has been entered into ServiceNow for processing by CTM IT purchasing. All documents are attached to the PR. PR0013517 is now in Pending Purchase status

**Comment by moorerst** [comment]
PR still in Pending Purchase status. There is communication documented in ServiceNow between CTM purchasing and ATD purchasing.

**Comment by moorerst** [comment]
emailed the CTM Buyer that is assigned to this PR to ask why the PR is still Pending Purchase. Is there additional information that is needed to move this PR forward. Informed buyer the contract expires 12/31.

**Comment by moorerst** [comment]
Email response from CTM Buyer: Hello Ken, I took a look and I don’t see anything that appears missing but if I do need something I will reach out to you.

**Comment by moorerst** [comment]
Per CTM puchasing:
Hello Stephanie, I am drafting the contract today, which will need to be approved internally before I can forward to the vendor. So it will most likely be next week sometime before the vendor sees a CT from us.

**Comment by johnclary** [comment]
Thanks Stephanie!

**Comment by moorerst** [comment]
Hello Stephanie, the contract needs to be sent to Legal for review.  The vendor had T’s and C”s  which need to be reviewed which they sent me last week. 

Hoping to get the package together to send to Legal today. 

Purchasing is communicating with the vendor so they are aware of the status of the PR

**Comment by moorerst** [comment]
Procurement documents sent to Robin
Robin confirmed receipt of documents and renewal now complete.
Robin response:
This renewal is now all set- our billing team will invoice with the PO shortly.
