### ISSUE TITLE
GIMOB Meeting - November

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#7563]
Creating this issue before I forget. Please add notes below and @ john.

If there is a vote, you will be voting for ATD.

Thanks!

**Comment by jaime-mckeown** [comment]
@andrewshensky no notes from meeting?

**Comment by andrewshensky** [comment]
Meeting Notes: @Johnclary
 
 
**GIMOB Chair**: RoxAnne's time as chair ending soon. Asked for volunteers for new GIMOB Chair. Would like to hold vote on new chair during December meeting.
 
 
**GIS Software/Database Account Request Form**: Do we only need SPOC approval or should we continue to require Manager Approval? Some issues have occurred with manager approval requirement, particularly for interns. Will be leaving Supervisor/Manager section in form, but will work to make it not a requirement that supervisor/manager approval is needed. This will reduce time constraints.
 
Conversation has started on having active directory sign on for Database Access. Will take time (Months) if it does happen.
 
 
 
 
**Street Initiative From Jacquie:** No update, expecting report from ESRI Prior to Thanksgiving
 
**Data purchases/lidar**: Impervious cover out for quote, waiting for qc on lidar
 
 
**_Subcommittees_**
**AGOL**: Enabled SAML based group membership. Sets up group that allows to pull users department from Active Directory and automatically adds users to AGOL Groups
(Configuring organization-specific logins, such as SAML logins (previously known as enterprise logins), allows members of your organization to sign in to ArcGIS Online using the same logins they use to access your organization's internal systems. The advantage of setting up organization-specific logins using this approach is that members do not need to create additional logins within the ArcGIS Online system; instead, they can use the login that is already set up with the organization.)
 
Enable SAML based group membership—Enable this option to allow organization members to link specified SAML-based groups to ArcGIS Online groups during the group creation process.
 
 
**Print widget:** Testing of custom templates has taken place and there were some issues. Limitations to esri templates (can't add disclaimer/Logo). New proposed templates are available for review in sub committee planner. Janny would like feedback by Tuesday the 9th
https://cityofaustin.sharepoint.com/:f:/r/sites/ATXGIS/Shared%20Documents/AGOL%20-%20Widgets/AGOL_Print_Templates/Review?csf=1&web=1&e=qjqsTb
 
**UAV/Drone**: Waiting on city wide governing body to be approved.
 
**Knowledge Base:** Currently 476 unpublished articles in bloomfire and only 88 published. Encourage users to update unpublished articles and publish for people to look at.
 
**UC**: Survey sent out on interest to attend next year's conference, 17 people are interested. Registration is not open yet but spots remain for additional people to attend.
 
**Homelessness:** Full inventory on homelessness related datasets (hundereds in AGOL). Survey in Teams regarding this request ATX GIS General Channel.
 
**GIMOB Documents**: Updating/Cleaning up documents in Sharepoint site and putting in archive folder. Goal is to have Sharepoint folder to only hold most recent information
 
**Esri Credits:** We have credits to use. Will renew soon 
 
 
 
**CTECC:** Address Points and unpinched streets being moved to secondary CAD Environment. Have unpinched streets for routing purposes. New employee Megan Yancy
 
**Geospatial Data Services**: Jacquie Hrncir officially manager. Single member districts will be updated (in the works. have not recieved shapefiles yet), just mentioned that certain districts are still being changed (changes will occur over the next months). A What's Happening will be sent out regarding single member districts.
 
**Geospatial Technology Management:** 
Geocortex Analytics Agent to 1.7.2 upgrade scheduled for 11/12
FME Production Upgrade  to 2021.1.1 10/6
ArcGIS Enterprise on Azure Upgrade to 10.8.1 10/8
SDE_External Update
GISDMDEV SDE_External migration complete 10/1
GISDMTEST SDE_External migration complete 10/25
     Testing will need to be completed by 11/19
     Please check your test environment connections.
If you have any questions about what this means, please contact Lee Kinser or Michael McKeever
 
GISDMF SDE_External migration scheduled for 11/8
Internal GTM check, nothing needs from stakeholders
 
GISDM SDE_External migration scheduled 12/3 4:00 PM
Will need department testers on hand for this weekend.
 
**Tx GIS Day**
TxGIS Day Career Cupid Speed Mentoring Event 11/15
Sign-up: https://docs.google.com/forms/d/e/1FAIpQLSfRLzEPfg8fNTWe-yz2IcbZbjLtFq-rLfBv3m6psb_ZDnFZgA/viewform?vc=0&c=0&w=1&flr=0
 
Register on Txgisday.org online streaming for presentations and workshops 11/15-11/17
https://txgisday.org/sessions/#!/

TxGIS Day Career Cupid Speed Mentoring Event 11/15
Sign-up: https://docs.google.com/forms/d/e/1FAIpQLSfRLzEPfg8fNTWe-yz2IcbZbjLtFq-rLfBv3m6psb_ZDnFZgA/viewform?vc=0&c=0&w=1&flr=0
