### ISSUE TITLE
Create mechanism to insert Moped IDs into Data Tracker

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#7566]
@zappfyllc As I've been thinking about this, my understanding is that there will be a token or key that is used to authenticate to Knack for this `insert` operation. This key shouldn't be embedded into the JS app as that would allow an unscrupulous user to extract it and gain unintended access to that API. 

Because of this, I believe we may need either create a flask API or a Lambda function that contains that authentication credential and performs the `insert` on behalf of the Moped app. 

Alternatively, we may be able to follow the pattern in place which uses JWT tokens to authenticate to Knack, but that is going to be dependent on Knack's authentication schemes. 

This script / function needs to have robust error handling / detection and gracefully handle an inaccessible Knack API and retry requests and / or maintain the record as pending in the scripts datastore. (See [this comment](https://github.com/cityofaustin/atd-data-tech/issues/7311#issuecomment-954174327) for some more brainstorming ideas on ways to keep track of the requests and their statuses.

- [x] Find out what capabilities Knack has for authentication
- [ ] Capture and store the Knack ID for the created record

**Comment by zappfyllc** [comment]
Per convo on 10/29 with @johnclary and @frankhereford:

We will actually create a toggle component on the project details page to connect to Knack (i.e. sends the request over to insert a new record into the `moped_projects` object) and then if the request fails, the user can just retry the toggle.

Let's call the label text "Connect to Data Tracker" for now

**Comment by zappfyllc** [comment]
cc @frankhereford @amenity @johnclary per convo today:

"Toggle" in the comment above will not work because there is no "undo" or "off" state that makes sense once the integration has succeeded. We landed on a button for now that will push data to Knack, then will display a link to the project in Data Tracker if already pushed to Knack.
