### ISSUE TITLE
Meeting: Overview - TDS Pre-Dev Assessments App 11/4/21

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7569]
### Final stakeholder meeting before going live with the TDS Reviews Mod

**Date/Time:** Nov 4, 2021 @ 11am
**Attendees:** Tracy, Diana, and everyone who reports to Upal., 

----

Hi Everyone,

The new TDA Reviews Mod is now live in the TDS KNACK Portal and ready for user testing! You can kick the tires on the mod anytime you like by logging into the TDS Portal and clicking on the TDA Reviews heading in the top menu. All test data will be deleted before you begin using the mod for real cases. 

**Meeting Agenda:**

- Tracy will demo the TDA Reviews Mod and answer user questions. 
- TDS staff will provide user testing feedback (if you have any)
- Discuss next steps & go-live

Please feel free to forward this to potential users of the TDA Reviews mod, or any other stakeholders. I will also record this meeting and make the video available to all city employees. 

Thanks,
Tracy Linder, Product Manager

Data & Technology Services🚲 Austin Transportation

**Comment by TracyLinder** [comment]
### Notes

- Diana will make the updates from today's stakeholder feedback (see her notes), then delete test records, then we will inform TDS that the app is live. 



Tracy: make issue to review the connect cases features

**Comment by dianamartin** [comment]
This is what the Connected Development Cases looks like on the TIA Reviews
- it's a separate form on the selections.
![image](https://user-images.githubusercontent.com/21112975/140772404-7f8a1e7e-df61-4285-8d00-7e889cf65824.png)
- Also, the "Edit Review" buttons are in different locations on the "Development Reviews" page compared to the "Development Assessment" page. Did you need them to match at all? @TracyLinder

**Comment by dianamartin** [comment]
Sync'd with Tracy on 11/9
- We reviewed my changes, they looked goo
- Identified the need to add an "All" filter, set it as default
- Deleted all test records on
  - TDA_review
  - TDA_meeting
  - TDA_attachment

![image](https://user-images.githubusercontent.com/21112975/140983683-4cbcbe4a-422e-47ee-bed1-f9d6893187bc.png)

**Comment by dianamartin** [comment]
@TracyLinder is this one ready to be closed?

**Comment by TracyLinder** [comment]
This has been released. Closing.
