### ISSUE TITLE
Support local cloning of Production database

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#7572]
- New `./hasura-cluster` command for devs to clone the Moped Production database locally
- Write up documentation in GitBook

With the substantial number changes to the original Moped database design, it is worthwhile for us to invest in our migration management processes. This will allow devs to better test their migrations before deploying to Production.

**Comment by sergiogcx** [comment]
Work in Progress PR:
https://github.com/cityofaustin/atd-moped/pull/445

Will be adding comments to the PR as to what it is missing.

**Comment by sergiogcx** [comment]
### 1. Main Security Goals
1. Ensuring database endpoint and credentials are not exposed to github, and reduce the risk of merging by accident by making the credentials not part of the git workflow.
2. Implement port-forwarding via bastion-to-rds ssh linking.
3. Make automation comprehensive and less cumbersome by not using .pgpass and instead use an alternative configuration file in the ~/.ssh folder with user rw-only per missions (ie chmod 600)
