### ISSUE TITLE
VZ Polygonizer meeting notes

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#7580]
## Meeting Notes

When the original Vision Zero Polygons were created, future data maintenance needs were unaccounted for. With time, it's become clear that the data used to create the polygons didn't always align with real-world streets as shown in satellite imagery, and there is [a list of polygons that need to be updated](https://github.com/cityofaustin/atd-data-tech/issues/7278). 

Some of these edits, like merging or cutting polygons are complex because we currently don't have a way to keep track of the IDs, or generating new ones without creating duplicates. Other edits are complex because the distance between the polygons and the real streets is large enough that several polygons would have to shift.

Bringing the polygons into a GIS environment would make maintenance possible. However, we need to decide our approach and scope of future maintenance before work can begin. 

Should future maintenance consider the possibility of adding large numbers of streets not currently covered by the polygons, or will maintenance be limited to fine-tuning the existing polygons? 

It's important to consider that in cases were many polygons (>5) need to be shifted, it may be easier to re-run the polygonizer on a properly aligned street line. This would be especially true of locations that include complex intersections. Adding even a single polygon would still require a new unique ID for it. There are potentially other scenarios in which having some type of automation would be helpful.

However, the current state of the polygonizer is such that only a developer can use or modify it. In order for the polygons to undergo complex GIS maintenance, the tool would need to be reversed engineered, and considerations for maintenance would have to be built into it. Looking at [the list of polygons that need maintenance](https://github.com/cityofaustin/atd-data-tech/issues/7278), several of them need complex editing techniques, and it is not difficult to imagine that more complex editing will be needed the longer we work with the polygons.

**Comment by jaime-mckeown** [comment]
@alan-deanda can this issue be closed?
