### ISSUE TITLE
Automate CTN Intersection Update Process

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#7583]
Current manual process is documented but can be automated using model builder to produce output of intersection points that are new or have moved since previous update.

**Comment by johnclary** [comment]
Andrew is reviewing the output from the first run of the automated process.
Todo:
- include in the model a distance check to determine if an intersection is new or moved.

**Comment by andrewshensky** [comment]
Functionality now includes a field in the output identifying whether an intersection point was moved or is new. Modified points within 100ft of existing intersection point are marked as 'Moved' and modified points beyond 100ft are marked as 'New'. This radius may need fine tuning in the future but the process is pretty solid.
