### ISSUE TITLE
Modify who can approve Telework Request Forms

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7595]
Rob has given the approval to allow his A.D.'s to approve the telework request forms on his behalf.  I think currently the emails go directly to him and the A.D.'s are not getting those.  Is that something we can change without a huge amount of work?  We also need to include Upal - even though he isn't an A.D. - he reports directly to Rob.

Nathan: Let me check with Anthony and see if he really wants to approve my staff, Karla & Peggy.  Rob allowed us to approve.  I will also ask Jim on Lewis before you do a whole bunch of work.  But definitely the other A.D.'s who report up to Rob.

**Comment by moorerst** [comment]
Follow up with Nathan: 
Not yet.  Jim Dale is on vacation and I will get with him next week.  I have my 1:1 with Anthony tomorrow and I will ask him.

**Comment by moorerst** [comment]
@dianamartin can this be updated/closed based on your email communications this week with Nathan and Meredith?

**Comment by dianamartin** [comment]
@moorerst So HR has the power to change people's user roles. I'm not sure if this request can be closed because I think we hard code the emails for those specific email notifications.

**Comment by dianamartin** [comment]
@moorerst I think we need to follow back up with Nathan on this

**Comment by moorerst** [comment]
Will discuss in meeting scheduled 1/11

**Comment by moorerst** [comment]
No additional action items for the issue.
