### ISSUE TITLE
Project: Centralize Parking Data

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7598]
An effort to centralize all of TPW's parking transactions into a single data store. 

## Background

ATD's parking transaction data flows through a dizzying number of systems and services. Payments through physical meters, the ParkATX app, and kiosks at public pools are each housed in a different vendor solution. This has led to a cumbersome administrative process for conducting financial reconciliation, and prevents staff from conducting holistic, data-informed analysis of our parking enterprise.

This project seeks to automate, standardize, and centralize all parking transaction data to simplify our reporting processes and unlock new insights from data.

## Scope & Deliverables

What's been completed:
- A centralized data store of data from all three vendors TPW uses for parking transactions.
- An internal dataset in the open data portal of parking transactions dating back to January 2020.
- A dashboard for finance for helping reconcile parking sales and deposits 
- A tab in TPW's dash project with details on parking trends

What's left:
- Opening up this dataset to the public. This has been blocked by the parking division due to concerns about the validity of parking meter geospatial data.

### Data sources

- Parking meters & pay stations (Flowbird - Smartfolio)
- Pool and parking pass transactions (Flowbird hub)
- PartATX mobile app payments (Passport)
- Flowbird bank deposits (Fiserv)

### Resources

- [Google doc](https://docs.google.com/document/d/10WW6Q-iwg0ueVhF7azijvvtJWQ_7VISup1_b94WyTM8/edit) which summarizes various data sources
- [Code repository](https://github.com/cityofaustin/atd-parking-data) for ETLs

![parking](https://user-images.githubusercontent.com/14793120/140663410-f1b42b44-2189-4c5b-ae3b-8f703e0b9d25.jpg)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by patrickm02L** [comment]
Blocked because of #7601. We'll need to follow up with Joseph and team to find out when we can publish the parking transactions dataset.

**Comment by johnclary** [comment]
@patrickm02L this project feels substantially complete. like maybe close-able??

**Comment by patrickm02L** [comment]
Agreed!
