### ISSUE TITLE
Get programmatic access to pool parking and pass transactions (Flowbird - hub)

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7599]

**Comment by johnclary** [comment]
I asked Darren for login access to Flowbird ub for both Charlie and me.

**Comment by johnclary** [comment]
Per Darren:
> There is not HUB data so therefore there will be no accounts.

I replied to ask for clarification

**Comment by Charlie-Henry** [comment]
Update that Darren is setting us up accounts but we haven't heard anything for about two weeks now.

**Comment by Charlie-Henry** [comment]
Darren created us accounts today. I don't see a place where we can get some sort of automated report from the HUB. Looks like the last transaction happened on Oct. 31st which was the last day Barton Springs/Deep Eddy pools required fees for entrance. 

There is a "transaction ID" but it does not match any fields in the Fiserv reports. These transactions are appearing in the fiserv data (matching by CC# and date/time), though. The missing matches in the fiserv->smartfolio data appear to be close-ish (+/-10% on the amount).

**Comment by johnclary** [comment]
Despite any useful field linking this data together, we want to incorporate this data into our database to enable it to be easily accessible from a single dashboard. Closing this. Next steps inn #7895.

**Comment by johnclary** [comment]
Unclear why I closed in December, but we have identified a mechanism to retrieve reports programmatically from the Flowbird hub.
