### ISSUE TITLE
Bus Ridership Incentives Project - needs scoping

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#76]
This project came from a resolution sponsored by CM Garza. The departments invovled are ATD, Innovation Office, CM Garza's Office, and CapMetro.

https://www.austinmonitor.com/stories/2018/12/council-hopes-to-reduce-car-use-with-two-initiatives/

- Working with Tien-Tien (TDM) on bus ridership incentives 
  - CM's first idea was Deduction on Austin Energy bill (that idea was a no-go)
- Kerry wants something evidence-based
- RS has a list of 25 incentive ideas, just doesn't know what will work
- Team needs to deliver a plan by mid-June. Execute the plan over the rest of the year
- Need from us Data wrangling on CapMetro data
  - David has been working with NHCD data
- Develop personas of actual target audience, choice-riders who could take the bus but drive
- Need to measure if incentives work

@johnclary we should catch up IRL on this.

**Comment by mateoclarke** [comment]
@johnclary did KO or TT ever talk to you about this?

I just saw it in the news so I think if it hasn't been scoped yet, we should close this out:
- https://www.austinmonitor.com/stories/2019/07/council-to-mull-funding-for-incentives-to-increase-transit-use/
- http://www.ci.austin.tx.us/edims/pio/document.cfm?id=322881

**Comment by johnclary** [comment]
Nope, never heard anything. Let's close this and ask the backlog gods to grant us six months until it comes up again.

**Comment by mateoclarke** [comment]
amen 🙏

**Comment by amenity** [comment]
@johnclary - is there a reason for us to keep this [in the DTS Portal](https://atd.knack.com/dts#project-evaluation/)?

**Comment by johnclary** [comment]
Nope—I deleted it.
