### ISSUE TITLE
Get programmatic access to ParkATX transactions (Passsport)

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7600]

**Comment by johnclary** [comment]
We're meeting with Joseph tomorrow to get a tour of Passport's "OpsMan" back-office reporting platform.

**Comment by johnclary** [comment]
We're meeting with Passport on 12/20 to get an update on our request for access. Joseph told us to expect good news 🤞

**Comment by Charlie-Henry** [comment]
We have access to the Passport API based on @johnclary's poking around with their web app. I am working to ETL it now.
