### ISSUE TITLE
Add Charlie to "About Us" page

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#7602]
Add Charlie to our [team website](https://github.com/cityofaustin/atd-product).

Pronouns: He/Him
Title: Data Scientist
Headshot photo: [google drive](https://drive.google.com/file/d/1KAgUV2fRPxI9EFQYTb1Y0Xvo5k7DiooY/view?usp=sharing)

**Comment by johnclary** [comment]
Title: Data Scientist
