### ISSUE TITLE
[Enhancement] Bulk Delete of TIA attachment records

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7605]
Jayesh D.
TDS

Spoke with him when troubleshooting some issue and he brought up that it takes the TDS Reviewers time to individually delete an attachment on the tables and asked if there was a way to easily delete attachments. Ex. Scope submission attachment records

**Comment by TracyLinder** [comment]
After speaking with Diana and Jayesh, we've determined that this feature would require DTS-DEV work, and I don't believe the value of this feature justifies the use of our DEV team. Should this need resurface in the future we will reconsider. The stakeholder has been informed & agrees. Closing.
