### ISSUE TITLE
[Enhancement] Limit Scope Submission Attachment Types for TIA Attachments

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7606]
### As a TIA Reviewer, I only want to see Scope specific documents during the Scope review. All other attachment types should only be available during the Submission review phase. 

**Acceptance Criteria:**
Limit scope attachment types to: Determination Form, Scope, Other

**Comment by TracyLinder** [comment]
### Discovery Notes

We will update this issue to focus on limiting the type of attachments available during the application / scope phase to:
- Scope
- Determination Form
- Other

- [ ] Rename issue & update description

**Comment by dianamartin** [comment]
# Diana's Notes
There were certain ways to approach this issue
- Training issue - user upload guidance has been implemented
- Scope Submission and TIA Submission are on 2 different tables, they both have "Attachment Types" and those selections can be deleted for each phase.
- `Scope`
- `TIA Determination Form`
- `Other`

**Comment by TracyLinder** [comment]
This will require power user approval before building / development. 
- Joan, Nathan A.

**Comment by TracyLinder** [comment]
**Email to Power Users:**

Howdy Joan & Nathan,

Jayesh gave us some good user feedback on TIA submittal attachments. He reviewed a scope submission where the applicant submitted all TIA attachment types instead of just the scope and determination forms. 

We're now wondering if the scope submission attachment types should be limited to 3 options: Scope, Determination Form, and Other. This will prevent the customer from submitting a bunch of inapplicable documents. 

Please let us know your thoughts. Diana said this would be an easy lift for her if you decide we should make the update. 

Thanks,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
Name & description have been updated.

**Comment by TracyLinder** [comment]
Power user Nate A. approved this change. Moving this to the backlog for possible implementation this sprint or next. FYI @dianamartin

**Comment by dianamartin** [comment]
For "Attachment Type" field on `TIA_scope_submission_content` removed all other types except for
- `Scope`
- `TIA Determination Form`
- `Other`

Removed fields:
- Site Plan
- Traffic Impact Analysis Document
- TIA Appendix/Appendices
- Trip Distribution Spreadsheet(s)
- Synchro Analysis File(s)
- Signal Timings
- Response Memo
- Final Memo

**Comment by dianamartin** [comment]
Joan replied 11/8
>Thank you for this change. Can we implement something similar to the “Attachment Types” for the TIA’s?

**Comment by dianamartin** [comment]
Joan confirmed
>Yes, I am requesting to keep the following type. We can just leave the last option as Other unless there are any further suggestions.
•	Trip Distribution Spreadsheet(s)
•	Synchro file(s)
•	Traffic Impact Analysis Document
•	TIA Appendix/Appendices
•	Site Plan
•	Signal Timings
•	Response Memo
•	Final Memo
•	Other (e.g., traffic volume Excel spreadsheets) or we can specify Traffic Volume Excel Spreadsheets for above-mentioned conditions.

**Comment by dianamartin** [comment]
@TracyLinder Am I okay to proceed?

**Comment by dianamartin** [comment]
Joan emailed asking to keep the following Attachment Types for TIA Submissions
•	Trip Distribution Spreadsheet(s)
•	Synchro file(s)
•	Traffic Impact Analysis Document
•	TIA Appendix/Appendices
•	Site Plan
•	Signal Timings
•	Response Memo
•	Final Memo
•	Other (e.g., traffic volume Excel spreadsheets) or we can specify Traffic Volume Excel Spreadsheets for above-mentioned conditions. 

I removed: Determination Form and Scope as options.
![image](https://user-images.githubusercontent.com/21112975/140983113-e3bcc1d9-afdf-44a9-9532-eaacfa4b8329.png)

**Comment by TracyLinder** [comment]
@dianamartin thanks for your good work on this one. Am i good to close it?

**Comment by dianamartin** [comment]
@TracyLinder yes, i think think the stakeholders were happy with it when we demo'd to them..
