### ISSUE TITLE
Create new info (Activity) & Add to Permit Folders (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7607]
### Our Cost of Service permits need to be updated with a new funding info 'Activity' 

**Requested by:** Van w/ Finance

**Acceptance Criteria:**
A new info field needs to be created based on the criteria below:
- Info Code: New, needs to be created
- Info Description: Activity
- Info type: Character (only allows digits)
- Info Group: Cost of Service
- Applicable to folders: EX, RW (subtype Temporary Right of Way use only), UC and GF
    - On GF, exclude work type Pre Development Assessment 
- Required for Insert: No
- Required for Issue: No
- Show in Portal: Yes
- Mandatory in Portal: No
- Validations/Business Rules: Value provided can be a maximum of 4 numerical characters only

**Comment by TracyLinder** [comment]
@vschandramouli can you please put this on your plate? We need to get the AC done and get this on deck ASAP. 
This info is the same as the four FDU fields we built on #7004 
Check it out and let me know what questions you have. 

FYI @Nadin-Nader

**Comment by vschandramouli** [comment]
Added Acceptance Criteria. Moving to Backlog.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Same question I have here also about the New Info Field validation. Is there a chance the value can start with 0.?
0061, 0801, 0001 - are these valid values?

**Comment by Nadin-Nader** [comment]
@SubhaShroff Spoke to Van and she said that they do need to be 4 digits but they can start with 0

**Comment by Nadin-Nader** [comment]
@SubhaShroff demo looks good. I approve for this to be deployed to **DEV**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  SCTASK0181185 is submitted for DEV deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  The DEV deployment is done and I verified. Tested on DEV Portal as well.  It looks as expected.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  TEST deployment request - **SCTASK0181388** -is submitted after Nadin's approval on Teams.

![image](https://user-images.githubusercontent.com/51680715/142657984-09d24f0e-67dd-41d8-b184-c7f59a9ab8f3.png)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  The TEST deployment is done. I verified for it and its ready for your UAT.

**Comment by SubhaShroff** [comment]
### Status:
Ready for test on TEST.

**Comment by SubhaShroff** [comment]
### Status:
Ready for UAT on TEST.

**Comment by Nadin-Nader** [comment]
@SubhaShroff UAT from Kim:

EX CPO- 21-048867 EX
-	has property and street info fields for TURPS and SCP folders
-	can’t start with a zero (see below)
![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/08f05852-cce5-4a97-9814-4d8331f3b031)

RW AE - 21-048869 RW
-	did not require 4 digits
![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/76980c9e-ee70-42fe-8c47-264d469da2db)

Waiting on Jaclyn for UAT of UC folder

**Comment by Nadin-Nader** [comment]
@SubhaShroff you may want to UAT the DS to verify.

**Comment by Nadin-Nader** [comment]
Still need to UAT this on the GF

**Comment by SubhaShroff** [comment]
@Nadin-Nader  

- I tested creating GF from Amanda (online GF not available).

2021 049055 000 00 GF - Activitiy - worked as expected.
2021 049054 000 00 GF  - (Austin Transportation (ATD) subtype and Pre-Dev Assessment worktype) - No infos should be added for this combination. So Activity info is not added.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been UATd on TEST and has passed.

## Approved for PROD 🎉🎉

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0185031 is submitted for PROD deployment.

**Comment by Nadin-Nader** [comment]
@SubhaShroff i sent an email to the stakeholders informing them that this is on PROD. I will ask to close tomorrow at our 2pm.

**Email**:

> 
> Hi Paloma, Kim, Isabel, Jaclyn and Isaiah,
> 
> Hope you are all doing well. I wanted to inform you that Card # 7607 Create New Info (Activity) & Add to Permit Folders is now on PROD. 
> Please make sure it is working as expected on PROD and let me know if something is wrong or if it can be closed.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> Product Delivery Manager
> Data and Technology Services

**Comment by Nadin-Nader** [comment]
Approved to close
