### ISSUE TITLE
[Meeting] Discuss signal corridor retiming update process 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7620]
## Agenda
- Discuss new corridor re-timing structure 
- Show Prototype on `TEST | Austin Transportation Data Tracker | 11 June 2021` environment

## Participants
Brian G., Lance, Jonathan, Amenity, John, Diana
Brian C.?

**Comment by dianamartin** [comment]
# Diana's Notes
Non-Corridor
continue timing corridors
- Moving to zones and areas 
Zone it's part of 
- New area engineer areas

New Geographic Zone and can be part of a corridor

Signal Details
- Signal Engineer Areas
- Define "Timing Zone" - to group the re-timing efforts
- Corridor 1
- Corridor 2
- Some isolated Y/N

Signal Re-timing
Re-timing Zone
Corridor 1 in a Zone
Last time it was re-timed

**Comment by dianamartin** [comment]
Scheduled debrief for 11/16 at 9 am

**Comment by amenity** [comment]
Misc notes:
Proposed approach
- New zones to manage retiming work
    - Include signals and PHBs
- Redefined corridors based on zones, e.g. Lamar essentially split into 3 different corridors where it crosses into 3 different zones


Isolated intersections
- Already have many
- Are not being accounted for when re-timing is done

Corridors will change and be added; what happens with historical data

- AMD does not see historical data as a priority, don’t measure year over year, measure before and after retiming

To-do:
- Brian G submit request to update Engineering Service Area geospatial data

Ramifications
- MMC corridor assignments will be off - actually this isn’t being done now
- Need to update Signal Retiming Dashboard

**Comment by amenity** [comment]
Will meet next week to debrief/huddle and prioritize; assuming it's project-sized, will need to update https://github.com/cityofaustin/atd-data-tech/issues/7462.

**Comment by johnclary** [comment]
@dianamartin will reviisit prototype in https://github.com/cityofaustin/atd-data-tech/issues/7421 based on discussion with AMD.
