### ISSUE TITLE
[Enhancement] Refactor details page links from various inventory tables

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7625]
Per AMD request, update various links in inventory tables for consistency.

1. The [completed txns report](https://atd.knack.com/amd#inventory-reports/issued/)

<img width="1404" alt="Screen Shot 2021-11-03 at 9 53 32 AM" src="https://user-images.githubusercontent.com/14793120/140084479-d7d33215-4d17-4594-a1ba-ef7223e9a88e.png">

2. [inventory item details](https://atd.knack.com/amd#inventory-items/inventory-item-details/5dfa6ac42057600ac95e792e/)

<img width="1390" alt="Screen Shot 2021-11-03 at 9 52 28 AM" src="https://user-images.githubusercontent.com/14793120/140084488-9fd75bb2-3d20-4961-ade2-f8bfc058a82d.png">

**Comment by amenity** [comment]
@johnclary notes here. :)
