### ISSUE TITLE
Change SM labels to be more descriptive and reflect correct subgroups

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7629]
@johnclary there are a few labels that need to be amended for Shared Mobility/Smart Mobility. 

I've already changed the Product label from: 
- "Product: SMO" to "Product: Smart Mobility Reporting Tracker." 

I'm proposing that we change:
- "Workgroup: SM" to "Workgroup: Shared Mobility Services,"
- Create a new label "Workgroup: Smart Mobility Office."

**Comment by patrickm02L** [comment]
via @johnclary 

> When we add or modify workgroups or products, we need to:
> 1. PM creates/updates labels in github
> 2. Knack builder updates the [service request form](https://atd.knack.com/dts#new-service-request/)
> 3. Dev updates the [service bot field mappings](https://github.com/cityofaustin/atd-service-bot/blob/production/config/config.py!)
>
> ![Screen Shot 2021-11-03 at 10.16.01 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/ff868c3d-362a-41e8-a141-afa3a65a2751)
> 
> this is a size 1 for both builders and devs.

**Comment by patrickm02L** [comment]
Changed "Product: SMO" back to it's original "Product: Shared Mobility Operations" label to coincide with the service bot. 

Will check later today to see if Shared Mobility Operations label is working.

Created a new label for "Product: Shared Mobility Reporting Tracker"

Created new workgroup labels: "Workgroup: SMO" for Smart Mobility Office, "Workgroup: SMS" for Shared Mobility Services.



May need to add another Product: Smart Mobility Operations.

**Comment by johnclary** [comment]
@patrickm02L looks like this is ready for a knack builder. chrispin or diana should be able to squeeze this in whenever you're ready to pass it off.

**Comment by patrickm02L** [comment]
@johnclary thanks. I was using this Issue so that I could have instructions for what I needed to do to make the change. I created another issue #7706 for Diana or Chrispin that captures it in a more succinct way.
