### ISSUE TITLE
Enhancement: Parking Meters non 311 Service Request Excel attachment

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7630]
Attached are two types of spreadsheets we use on almost a daily basis. 
We currently print these off but if we could find a way to send electronically to the tech and then have the tech return them electronically it would be great.

Will discuss further in Sprint Review scheduled 11/5

**Comment by moorerst** [comment]
Will set up meeting with Jose & Gilbert to review the process used to download the Excel spreadsheet. See if there is a better way.

**Comment by dianamartin** [comment]
Emailed Jose and Gilbert 11/16
>David told me that you found a way to download the PM spreadsheet, save and re-upload the files to the Parking Meter service request assignment? I wanted to see if you’d both be available to talk/screen share with me and walk through your steps on Friday morning? I want to see what the steps are to see if I can help streamline anything for your team.

>Let me know your availability and I can send a meeting invite.

**Comment by moorerst** [comment]
@dianamartin you met with the team and worked out a process that seems to be working for them. Can this be closed?

**Comment by dianamartin** [comment]
@moorerst Yes! We did configure a new "Add Attachment" button on the "My Assignments" page for Technicians. It uses the same attachment object for the photos.
