### ISSUE TITLE
Update maint layer from Vision Zero database

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7634]
Also, create a new ID sequence on and assign all features a new ID in a new column.

**Comment by johnclary** [comment]
@alan-deanda work with Sergio to get read access to the Vision Zero read-replica. Same permissions that Jaime has.

**Comment by johnclary** [comment]
This is not needed. Per Frank the polygons in maint match VZD

**Comment by johnclary** [comment]
@alan-deanda would you work with Frank and Adrien to confirm that this layer is actually current compared to what's in VZD?

**Comment by alan-deanda** [comment]
@johnclary  the audit and new ID fields have been added. I've also added the street level 5 polygons. closing this issue. I'm tracking progress of Adrien and I's progress on the polygons on a separate issue.
