### ISSUE TITLE
Add UI triggers for project status and apply design updates to project menu

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#7639]
- [x] Update "Rename" menu item to use the [_outlined_ Pencil](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aedit%3A)
- [x] New menu item, "Place on hold" using [Pause Circle](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apause_circle%3A) - should set the project's `status_id` to the int pointing to `on hold` in `moped_project` (related to `moped_project_status` created in #7638)
- [x] New menu item, "Cancel" using [Cancel](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Acancel%3A) - should set the project's `status_id` to the int pointing to `cancelled` in `moped_project` 
- [x] Update "Delete" menu item so that it is not red on hover
- [x] Remove "Share" and "Add to favorites"
![Screen Shot 2021-11-17 at 10 19 59 PM](https://user-images.githubusercontent.com/1463708/142351262-ee8fed6a-b607-4fe9-a07d-55e1a03b1c88.png)

**Comment by zappfyllc** [comment]
@amenity should we distinguish between "Delete" and "Cancel"? I think these and "On Hold" specify/communicate three different statuses:

- On Hold: a project is suspended and may resume an active status in the future
- Cancelled: a project was created, may have made some progress, but was cancelled for any reason
- Deleted: could be a user mistakenly entering a project into Moped for any variety of reasons (e.g. it doesn't really constitute a project but is agreed to be more of a task, maybe it doesn't really have anything to do with mobility, etc.)

Thoughts?

**Comment by amenity** [comment]
@zappfyllc I'm totally on board with this distinction. "Deleted" projects are data our users wouldn't want to include in any analysis, but canceled projects might conceivably be useful.

**Comment by zappfyllc** [comment]
@amenity Agreed. If we add a third option to this menu, maybe we use the trash icon for "Delete", use the cancel icon for "Cancel", and add a third icon (clock/calendar) for "Place on hold"?

**Comment by amenity** [comment]
@zappfyllc - yep. I'll get you an updated mock up today
