### ISSUE TITLE
Build CSR tables 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7643]
Create the tables for the Service Request as a new tab in SMRT. Use Parking Enforcement Portal as a template. 

The micro mobility devices will come from Micro Mobility Service Request, whereas Scoobi, a moped, will be housed in the Parking Enforcement Violation SR as a new type because it can be ticketed - ATD-Shared Vehicle Services.

**Comment by dianamartin** [comment]
@dianamartin On deck for you

**Comment by dianamartin** [comment]
# TO DO
Create Tables
- [ ] csr_activities
- [ ] csr_flex_notes
- [ ] csr_issues
