### ISSUE TITLE
Enhancement: Parking Enforcement Dispatch Tracking New Out of Service Reason

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7648]
Parking Enforcement staff requested new choice field for Out of Service Reason

- Inspections

**Comment by dianamartin** [comment]
Added new choice to `Out-of-Service-Reason`

**Comment by moorerst** [comment]
confirmed with Jasmine that the new Out of Service reason "Inspection" is showing in the list. Closing issue.
