### ISSUE TITLE
Prep for Parking Meters non 311 SR's Go Live 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7650]
Planned Go Live date 11/15

- [x] Provide Help Guide to Parking Enforcement leadership to provide to PEO's
- [x] Testing with PEO's week of 11/8
- [x] Testing with Parking Meters admin staff 11/8
- [x] Testing Notes/Feedback
- [x] Modifications from testing
- [ ] Delete test records

**Comment by dianamartin** [comment]
Create help guide for
- New SR for Parking Meters
- Add Image for SR for Parking Meters

Create new PEO Filter 
- Showing only Parking Meter Issue Types
- Form Rule to set correct "Issue Type"

Create My Assignments "Add Attachment" button - only for Parking Meter techs

**Comment by moorerst** [comment]
@dianamartin as a PM Admin if I select Issue Type Preventive Maintenance should I need to enter a Address if the Preventive Maintenance is covering a wide range of addresses?

**Comment by dianamartin** [comment]
@moorerst that's currently how we have the SR Issue set-up.. it might be something we have to change.

**Comment by moorerst** [comment]
- Training and testing with Parking Enforcement Officers entering Parking Meter SR's

- Training and testing with Parking Meters Admins and techs on receiving, assigning and closing SR's

**Comment by moorerst** [comment]
Follow up meeting with Parking Meters after two days of testing. They are pleased with the system, seem to navigate within the system fairly easily.

Items to review:
- Techs can't enter notes unless they use the Attach An Image activity. 
Option - maybe add a Meters Notes activity. Would need to discuss with Parking Enforcement 

- Would like to have the PEO's enter the meter # 

GO Live plan:
Nov 29th delete test records/delete button
Dec 1st go live with PEO's enter PM SR's

**Comment by dianamartin** [comment]
## Add Note, no photo
![image](https://user-images.githubusercontent.com/21112975/142079823-185d4efc-cbe5-419a-8e4c-c191cbb143e1.png)

## On Samsung Tab A
![image](https://user-images.githubusercontent.com/21112975/142079911-b18dc1e8-6206-491b-9443-b10a6dacda6e.png)

## SR Details page
![image](https://user-images.githubusercontent.com/21112975/142080053-30a3f3a9-29e7-45f4-af71-432972b97dbe.png)

**Comment by moorerst** [comment]
Prep for training/testing is complete. Opening new issues for items identified during testing. 
•	Parking Technicians can't enter notes unless they use the Attach An Image activity.
o	Option - maybe add a Meters Notes activity. Would need to discuss with Parking Enforcement
•	Would like to have the PEO's enter the meter #
