### ISSUE TITLE
Update PSM, Vendor, Valet and other TURP Fee amounts for FY22 that were missed (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7672]
Update PSM, Vendor, Valet and other TURP Fee amounts for FY22 that were missed

**Acceptance Criteria**

Link to Fees:
https://www.austintexas.gov/sites/default/files/files/Transportation/Right_of_Way/Fee%20Schedule%202021-2022.pdf

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader If possible, could you please let me know the fee codes for the above mentioned fees

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT here is the link to the fee codes that Tracy has. Please let me know if this will work. If not i can try to get it some other way (The fee amounts are in the link in the AC.
https://drive.google.com/drive/u/1/folders/17nc2pJqTVMqo7CncLaPKwWYJgwVpTGSi

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Did the fee codes in the link above help? We can talk about it tomorrow

**Comment by TracyLinder** [comment]
Paloma & Kim would like to meet with Priya to identify which fees need to be updated. @Nadin-Nader is going to schedule.

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader 
Confirmed with Paloma, there are 10 fee codes

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/d3d5e564-a850-4dc5-89e5-042441196c0f)

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Whats the status of this?

**Comment by TracyLinder** [comment]
Don't update fee code 83494; we will use 50205. It's the same fee.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this over to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0183784**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on the DevOps CM Team to deploy this to **_DEV_** under **SCTASK0183784**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to **DEV**, please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Fee amounts are updated. Can be deployed to Test

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team to deploy to **_DEV_** under **SCTASK0184028**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on the DevOps CM Team to deploy to **_DEV_** under **SCTASK0184028**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been deployed to **_TEST_** Please UAT

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT i got the UAT back and 5 need updates:

> [Yesterday 3:12 PM] Amayo-Ryan, Paloma
> **Test Results for Ticket 7672**
>     Five fees are fixed and five fees still need to be updated.

![MicrosoftTeams-image (6).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/44789961-a88c-4e2c-8923-599280e0b266)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader It would be helpful if Paloma could share the folderrsn that she used for testing

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on Paloma's response:

> [Yesterday 10:13 AM] Nader, Nadin
>     Amayo-Ryan, Paloma, Hey Priya asked if you could provide the RSN for the fees you tested? She needs to do some research to see why they arent correct

**Comment by TracyLinder** [comment]
**UAT on PSM fee Temporary Cafe/Patio Application Fee:**
✅ The correct fee amount was inserted
❌ The fee is not on the Insert + Run menu on the PSM folder. @Lpriya-LIT the fee needs to be on the insert & run menu. 


<img width="740" alt="Screen Shot 2021-12-22 at 12 26 49 PM" src="https://user-images.githubusercontent.com/49930868/147138692-78c30c24-9ed4-43ab-b349-7dbe80d06158.png">

**Comment by TracyLinder** [comment]
**Clarification Requested on Temp Valet Application Fee:**

i need clarification on Temp Valet please. Is the application fee supposed to insert & bill itself when the portal application is submitted?

**Comment by TracyLinder** [comment]
**Valet Operating Fees**

I'm confused about how these fees should be applied. Scheduled a mtg today at 3:30 to discuss w/ stakeholders.

**Comment by TracyLinder** [comment]
**Street Vendor UAT Results (failed)**

❌ Incorrect fee inserted. See below. The fee should be $320. 
<img width="817" alt="Screen Shot 2021-12-22 at 12 44 53 PM" src="https://user-images.githubusercontent.com/49930868/147141306-6679a508-fa0c-4047-8a08-1af00216ea74.png">

**Comment by TracyLinder** [comment]
**Question's for Kim & Paloma**

Valet Temp
- Should the application fee be auto inserted & billed when the portal application is submitted? 
- When should the space rental fee be charged? 
- What AMANDA field should we base the space fee calculation on?

Valet Operator
- Confirm: The initial operating fee is $50, then each year after that it will cost $250 to renew? 
- The renewal fee is new? If so, how should we program it to work? In what part of the overall workflow? 
- The $10 site fee is already working & doesn't need to be updated, correct?

**Comment by TracyLinder** [comment]
**Valet Temp Answers:**
- We want the fee to auto insert & bill. (It never has, but we've requested). 
- 50205 (Temp valet permit fee) should be the per space fee; $50 per space per day
    - Rename fee to 'Temp Valet Space Rental Fee' (In PROD it currently shows as the Valet Parking Space Fee, 50185) 
- The per space fee is calculated based on 2 info fields:
    -  # of on-street parking spaces
    - # of days requested
- We're not sure at what point the space fee is currently inserted, or how exactly it is triggered. 

It looks like we have 3 temp valet fees. Which ones are currently is use on PROD? I need to sync w/ Priya for analysis before we move forward. 
- 50180
- 50185
- 83494

**Valet Operator:**
- Let's update the fee amount. They will update the initial license fee from $50 to $250 for FY23. In the meantime, if staff needs to charge the lower amount, they will need to adjust the amount manually. 
- Is the $10 site fee working currently? A: Yes, it's good

**Comment by Nadin-Nader** [comment]
**Status:**
Priya will continue working on this early next week (week of 1/10/22).

**Comment by Nadin-Nader** [comment]
**Status:**
Priya was working on this but has Network connection issues today (1/12/22)

**Comment by TracyLinder** [comment]
### List of Updates Needed:
_I think i may move the temp valet things to their own card. Not sure yet._

- [ ] Add Temporary Cafe/Patio Application fee to PSM Insert & Run Menu on the fee tab
- [ ] Update amount of Vending Application Fee to $320
- [ ] Rename Valet Parking Space Fee (50185) to Temp Valet Space Rental Fee
- [ ] Update fee amount for Valet Initial Operating Permit Fee (75300) to $250

FYI @Lpriya-LIT @Nadin-Nader

**Comment by Nadin-Nader** [comment]
@TracyLinder @Lpriya-LIT This needs a couple of update (added in the comments above with the checklist) Once those are addressed, Paloma approved the move to PROD if all looks well on TEST.

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/b6274a5f-90c9-49b7-8c98-2cdfb42d9860)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Added 4% surcharge for Vending application fee and undo the rename for Valet Parking Space Fee

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team for deployment to **_DEV_** under **SCTASK0195140**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been promoted to DEV and TEST, please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified , works fine. The Surcharge for Vending application fee has been added and the Valet Parking Space Fee  name change has been reverted

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team for deployment to **_PROD_** under **SCTASK0195142**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader  Deployed to Prod

**Comment by TracyLinder** [comment]
**❌UAT FAILED❌**
- The incorrect fee amount was inserted for Vending Application fee. ($150 was inserted; it should be $320)
- Just confirming that this was rolled back and needs to be redeployed
FYI @Nadin-Nader

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test, Changes have been re-applied. Working as expected

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on UAT results from Paloma about PROD

**Comment by Nadin-Nader** [comment]
PROD UAT Failed
Results from Paloma's UAT:

> 
> [12:14 PM] Nader, Nadin
> Hi. Hey looks like 7672 is not working right, Can you look into it?Paloma's UAT on PROD:[10:59 AM] Amayo-Ryan, PalomaNader, Nadin and Linder, Tracy - Still having issues with the RW - Valet Operator folder.Valet Operating Permit Fee = 50200This fee is not available in the "Insert & run procedure" menuThis fee is not populatingThis fee should be populating at $250Valet Initial Operating Permit Fee = 75300This fee is available in the "Insert & run procedure" menu This fee is populating at $250This fee should be populating at $50

**Comment by Nadin-Nader** [comment]
**Status:** 
Priya is looking into as to why the fees arent showing up.

**Comment by TracyLinder** [comment]
[3:23 PM] Linder, Tracy
    Amayo-Ryan, Paloma you previously asked us to code the fee amount for the FY23 fee ($250) and that staff would manually change the amount in the meantime. Please confirm, should we change the amount or go with the original plan? TY.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Paloma's response:

> 
> [Tuesday 3:36 PM] Amayo-Ryan, Paloma
>     Linder, Tracy - ah, okay, I forgot about that.  (I think all of these super similar names are confusing me!)  I'm certain now that there are two separate Valet Operating Permit Fees - one for initial issuances and one for renewals.  I'd rather have the Initial one (75300) coded to $50 and then the Renewal one (50200) can just stay blank as is until the new FY hits us.

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/8bb771e4-a541-4775-88eb-3b9a98e65e2d)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Updated the fee amount for 75300 from 250 to 50

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0209183**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV. Please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Dev, Ready for Test Promotion

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0210631**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been deployed to TEST, Please UAT and verify it is ready for Stakeholder UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test. Fee amount for fee code 75300 has been updated from 250 to 50

**Comment by TracyLinder** [comment]
@vschandramouli  please add this to the TEAMS ROW channel asking for UAT.

**Comment by vschandramouli** [comment]
UAT meeting on 4/21 - Approved by Paloma. Ready for PROD deployment.

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader @vschandramouli UAT done, Ready for PROD.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Please request for Prod promotion, have sent you the deployment plan
@TracyLinder @vschandramouli

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder This has been sent to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0213545**

**Comment by Nadin-Nader** [comment]
@TracyLinder @Lpriya-LIT this is now on PROD. I will post and send the message to ROW via TEAMS chat.

**Comment by Nadin-Nader** [comment]
Per Paloma this is goo to close
