### ISSUE TITLE
Refine Data and Performance Hub Styling

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7674]
Met with @johnclary on 11/5/21 to go over how to clean up the [Data and Performance Hub](https://brave-wozniak-4a02f0.netlify.app/), how to standardize the styling across the main landing page cards, and what happens when the cards open up to their own page. 

Reference:
- [ATD Branding Guidelines](https://drive.google.com/file/d/1op7hXYnQOYYzW8P1-8LISoQA0WmVvpQL/view)
- [Proposed DTS Website Branding](https://github.com/cityofaustin/atd-data-tech/issues/6506)

### Proposed designs
[XD](https://xd.adobe.com/view/57c969ae-6136-4521-a467-000e1d5fe98e-029a/grid)

### Refinements by Page

**Landing page**
- Update COA logo to align with Transportation branding guideline
- Remove icons next to titles on the cards
- Improve the footer

![screencapture-brave-wozniak-4a02f0-netlify-app-2021-11-05-15_13_14.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/c2b48f40-4cf9-49da-93a2-21ebb86ce06d)

**Maps type page (Traffic Signal Monitor)**
- Create cards or zone for featured data
- Designate a clear space for search/filter component; square or greyed area
- Relocate the Updated information and download data or rethink how to incorporate it on page better

![screencapture-brave-wozniak-4a02f0-netlify-app-signal-monitor-2021-11-05-15_12_50.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/5106384d-d8e3-4b6f-aaf4-69f5830a0719)

**Maps type page (Traffic Signal Evaluation)**
- Move the Steps flow diagram under the fold
- Rework filter; needs intentional space
- Refine how individual records are shown (Address | Status)

![screencapture-brave-wozniak-4a02f0-netlify-app-signal-evaluations-2021-11-05-15_13_31.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/41f42cec-93cb-4911-8661-b86940d082e4)

**Maps type page (Signal Timing)**
- Create cards or zone for featured data (Signal Re-Timed, Travel Time Reduced)
- Refine how individual records are displayed (kind of like the way they are here)
- Relocate the Updated information and download data or rethink how to incorporate it on page better

![screencapture-brave-wozniak-4a02f0-netlify-app-signal-timing-2021-11-05-15_49_38.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/89fb2043-e667-4f61-833e-3733cbe6a4d9)

**table type page (Shared Mobility)**
- Legibility of the table. Resize fonts to promote hierarchy of data.
- Adjust placement of filters
- Labels on the bar graph

![screencapture-brave-wozniak-4a02f0-netlify-app-micromobility-data-2021-11-05-15_16_18.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/7e46ec25-a106-4095-a9db-c3c3f36c0718)

In general, the styling needs to be tweaked a bit, standardized information across pages, align information in predictable way, and create hierarchy and predictability amongst similar pages. I would say this site is at 80% completion. I'm anticipating this taking 4-5 hours of design work.

**Comment by patrickm02L** [comment]
## Updated New Pages

**Landing Page**
![Data Performance Hub Home Page - New Updated.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/26a8da43-28e3-4e9c-b55f-2ed280cfdc60)

- Transportation Logo and DTS Logos were switched
- Catalog in Nav Menu became "Data Catalog"
- External link icon on cards changed from grey to blue
- Cleaned up footer menu a bit
- Need to change "curated by" tag line, remove curated.

**Comment by patrickm02L** [comment]
@johnclary I've incorporated feedback and the new pages are ready to be coded. 

Please use the **Updated New Page** "Landing Page" and the other **New Pages** for reference.

**Comment by johnclary** [comment]
incredible—thanks @patrickm02L. looking forward to implementing this!

**Comment by amenity** [comment]
Nice, @patrickm02L ! Maybe curated is fine. 🤷‍♀️  Defer to PIOers.

**Comment by johnclary** [comment]
I have incorporated these oustanding (!) changes into the the [app](https://deploy-preview-397--austin-transportation.netlify.app). I'm closing this and will continue to track work in the epic.
