### ISSUE TITLE
BUG: Bugs on GF w/ TCP Fee (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7682]
### Updates to GF subtype Austin Transportation, no work type

StakeHolders: Robert A., Paloma

- [ ] System should insert & bill the TCP Review Fee & surcharge during the automatic add phase
- Traffic Control Review $220
- ATD Tech surcharge ROW 4% of Traffic Control Review Fee 
- [ ]  Add TCP Review Fee to Insert & Run menu on fee tab. When this fee is selected the System should insert & bill the TCP Review Fee & surcharge. 
- [ ] Why isn't the TCP fee renamed in the Insert fee menu? (change made on #6634)
- [ ]  Remove folder info "Consultation Hours' and any fee logic related to it

Date: 11/8
Attendees: Tracy, Richard

**Comment by TracyLinder** [comment]
@Nadin-Nader lets talk about this

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT the name of the TCP fee that it needs to display in the Insert menu is "**_TCP Review Fee_**" reference card #6634

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Commit id - 53fda8cc1067 . 
Ready to deploy to Dev

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT 
**Status:**
This has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0181775**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT 
Status:
This has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0182320**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to **DEV**, please UAT

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT the new commit has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0183206**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy new changes to **_DEV_** under **SCTASK0183206**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to **_DEV_**, Please UAT Let me know the outcome

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/0e74752f-5b31-45f6-b280-cbe3c3193df5)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Dev . TCP fee has been renamed and inserted with right amount and surcharge. 'Consultation Hours' info and fee logic related to it has been removed

**Comment by TracyLinder** [comment]
Hi @Lpriya-LIT , question: Is the system billing the fees or did you do that manually? 

If the system billed the fees please promote to TEST. If not, the system needs to bill the fees.

**Comment by Lpriya-LIT** [comment]
@TracyLinder The system is billing the fees

**Comment by TracyLinder** [comment]
### Approved to promote to TEST

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT i Have sent this to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0184911**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder This is now on TEST. Priya please UAT and verify all is working as expected and let me know so that i can inform the stakeholders

**Comment by Lpriya-LIT** [comment]
[Uploading... image.png]

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/fcf67fbb-4020-4634-959f-b8592dc7853b)

**Comment by Nadin-Nader** [comment]
**Status:**
Awaiting Robert Alvarez's UAT results from **_TEST_**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0187164**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV. Please UAT and verify

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader  Verified in dev , can be promoted to Test

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Tea to deploy to **_TEST_** under **SCTASK0188289**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to **TEST**, Please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader verified in test, surcharge name has been updated .

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/cfa49e23-e419-47a2-b7de-7a4bc0fc0b8c)

**Comment by TracyLinder** [comment]
### UAT Passed; Please promote to PROD
FYI @Nadin-Nader @Lpriya-LIT

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT i have sent this to the DevOps CM Team to deploy to **_PROD_** under **SCTASK0188660**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder This has been deployed to PROD. I will post it in the Teams channel and let the Stakeholders know

**Comment by Nadin-Nader** [comment]
Closing as i have not heard anything on this, it is on PROD and i informed the stakeholders yesterday that i would be closing it
