### ISSUE TITLE
Create a new logo

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7686]
Update logo on the app to reflect the Smart Mobility Office.

**Comment by dianamartin** [comment]
- [x] Created logo folder on network drive
- [x] Copied the "Shared Mobility" gimp file
- [x] Recreated "Smart Mobility Office" png
![image](https://user-images.githubusercontent.com/21112975/141017268-66e2ba6e-3f58-4dc9-9bbb-098a528a273a.png)

**Comment by dianamartin** [comment]
Showed stakeholder application on 12/3, no additional comments were provided. Closing
