### ISSUE TITLE
[Enhancement] Create new banner image for Austinmobility.io

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7687]
The [bicycle logo](https://austinmobility.io/) doesn't adequately capture the scope ATD's portfolio. Replace it with a new image/logo. 

![bike banner.jpeg](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/3e27fe9b-e274-4bea-b763-3d9424d3689a)

**Comment by patrickm02L** [comment]
Public Information Office [Transportation Branding Assets](https://cityofaustin.sharepoint.com/sites/atdPIO/SitePages/ATD-Department-Branding.aspx). 

To get the blue filter effect: turn stock photo into b&w image, overlay royal blue layer at 10-20%.

<img width="929" alt="Screen Shot 2021-11-22 at 3 47 21 PM" src="https://user-images.githubusercontent.com/5566727/142939926-656f5e82-c722-4685-a09c-2e0887f2fdd3.png">

**Comment by johnclary** [comment]
nice!

**Comment by patrickm02L** [comment]
In addition to updating the header image, I went ahead and updated the styling of the DTS website home page to match the new design improvements for the Data and Performance Hub. 

## Old

![Home.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/7cf3d1d5-c004-4bbb-b37c-b1fda3ab03d5)

## New
![Home – New – 4.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/42374bd1-7b66-49bf-a6c0-fa0f494e876c)

**Comment by patrickm02L** [comment]
@johnclary Moving this to Review/QA.

**Comment by patrickm02L** [comment]
Getting update as part of #10562.
