### ISSUE TITLE
[Feature] Backend geospatial queries

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7694]
As a Moped user, I want to easily see, in Moped, project information that is determined by project location and geometry.

### In Scope
- https://github.com/cityofaustin/atd-data-tech/issues/10889
- https://github.com/cityofaustin/atd-data-tech/issues/14156

### Out of Scope / Future 
- (iceboxed) [Jurisdiction](https://github.com/cityofaustin/atd-data-tech/issues/10890)
- [SIF Service Area](https://austin.maps.arcgis.com/apps/View/index.html?appid=af6815a6521747f3a5dc1dfd11a8da6e) - needed for #7693 
- Zoning
- Proximity to a school/bus stop/housing - potentially needed for #3678

**Comment by johnclary** [comment]
This is definitely a must have for a future version of Moped, but I don't think it needs to ship with v1.0. Current workaround in Data Tracker is to join this information from signal records.

**Comment by johnclary** [comment]
We have established patterns for this and have already implemented:

- https://github.com/cityofaustin/atd-data-tech/issues/10889
- https://github.com/cityofaustin/atd-data-tech/issues/14156

And these are all on the wish list:
- https://github.com/cityofaustin/atd-data-tech/issues/10890
- https://github.com/cityofaustin/atd-data-tech/issues/7693
- https://github.com/cityofaustin/atd-data-tech/issues/3678

I'm closing this epic. We can open new threads as these backlog items surface
