### ISSUE TITLE
VPC config or SSH tunnel for AWS RDS Postgres

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#77]
@JoeyL6 and I are both interested in establishing connections to atd-rodeo-prod. Joey wants to set up pgAdmin4 and I'm looking at setting up a connection to Metabase. Since atd-rodeo-prod is on a VPC, we can't just pass in the credentials to make a connection.

@johnclary, could you remind us why the db needs to be on the VPC? Is there any issue if we create this SSH tunnel for these purposes?

**Comment by mateoclarke** [comment]
Related to #60

**Comment by mateoclarke** [comment]
Going to recruit @sergiogcx's help with this one day...

**Comment by amenity** [comment]
This will probably resurface in future needs.

**Comment by johnclary** [comment]
We've adopted the practice of using an SSH bastion on EC2. Closing.
