### ISSUE TITLE
Develop VZ polygon editing docmentation

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7701]
Create documentation about the process for editing Vision Zero polygons. Let's do this along side https://github.com/cityofaustin/atd-data-tech/issues/7278.

**Comment by mateoclarke** [comment]
Looks great Frank, I created this placeholder in Gitbook where you could save these notes and we can make further edits or changes there: https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/c/mLa7kNeUdCWrVx9rdNcW/vision-zero-crash-database/location-polygon-creation-from-asmp-network

**Comment by frankhereford** [comment]
Thanks Mateo! I've transferred the document to GitBook -- thanks making that page; it's a much better place for that.

**Comment by mateoclarke** [comment]
@johnclary @alan-deanda, on second thought, if the audience for these docs is the GIS team and/or the new GIS Analyst with Vision Zero, maybe these docs shouldn't live under ATD Dev because our permissions are locked down. 

We could move them to the "Vision Zero Editor", "ATD Geospatial", or somewhere else. What do y'all think?

**Comment by alan-deanda** [comment]
@mateoclarke if you're able to move it to ATD Geospatial that would be ideal.

Thanks!

**Comment by alan-deanda** [comment]
I just re-created the doc in the Geo space. @mateoclarke , how should I go about removing your copy from Dev?

**Comment by mateoclarke** [comment]
Just deleted it @alan-deanda.

**Comment by alan-deanda** [comment]
Closing this issue, as the initial VZ polygon documentation now lives in gitbook in an appropriate location. Adrien and I will collaborate on documentation as we work together on updating the VZ polygons
