### ISSUE TITLE
Update Workgroups labels in the Service Bot - SMS, SMO

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7706]
The Shared Mobility workgroup label (Workgroup: SM) was being used as a catch all for both Shared Mobility Services and Smart Mobility Office. 

![Screen Shot 2021-11-09 at 3.31.03 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/0141dbfd-2413-418e-a543-6a4ff2e9d3d8)

I updated the "Workgroup: SM" label in github to "Workgroup: SMS" for Shared Mobility Services, and created a new label "Workgroup: SMO" for Smart Mobility Office. 

When I changed SM to SMS it no longer maps to the correct label because it doesn't exist. It's greyed out now.

![Screen Shot 2021-11-09 at 3.26.33 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/31017cb3-a1e8-4602-aaf9-8c588142e803)

Please update the Workgroups in Service Bot so that there's a Shared Mobility Services option to select that maps to "Workgroup: SMS" label, and a Smart Mobility Office option that maps to a "Workgroup: SMO" label.

![Screen Shot 2021-11-09 at 3.48.17 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/59c19291-9f5d-4fba-a022-c0b29cb1ed3f)

**Comment by dianamartin** [comment]
@johnclary I thought it was for you..

**Comment by johnclary** [comment]
@dianamartin looks like we need to update the workgroup options on the DTS service request.

1. Change Smart Mobility to "Smart Mobility Office"
2. Add "Shared Mobility Services"

Once you take care of that I'll do the service bot code.

<img width="658" alt="Screen Shot 2021-11-09 at 5 02 25 PM" src="https://user-images.githubusercontent.com/14793120/141019501-8220effb-4c70-49be-a215-0f30c05b2dff.png">

**Comment by dianamartin** [comment]
- [X] changed "Smart Mobility to "Smart Mobility Office"
- [X] added "Shared Mobility Services" 

![image](https://user-images.githubusercontent.com/21112975/141137524-8836c472-86a3-4141-8cc4-b26171a6ead8.png)

**Comment by johnclary** [comment]
@dianamartin I checked the DTS portal and did not see your changes. Maybe you made them in another app?

In any case, I updated the choices in the knack app and submitted a PR - pending review.

**Comment by johnclary** [comment]
@patrickm02L the patch will be deployed in 10 minutes. Please test this by creating new DTS service requests for Smart Mobility Office and Shared Mobility Services.

**Comment by patrickm02L** [comment]
@johnclary I did tested the SRs to see if the labels were rendering. Neither the SMS #7941 nor SMO #7942 labels were added to the issue.

**Comment by johnclary** [comment]
I've double checked the code and SRs and don't see an obvious reason why the workgroup label's are not populating. Will need to test locally.

**Comment by johnclary** [comment]
I just ran locally and this one processed correctly https://github.com/cityofaustin/atd-data-tech/issues/7977

**Comment by johnclary** [comment]
ok @patrickm02L we should be all set. there was a devops isssue that was preventing the latest code to run on the Airflow server. would you try again?

**Comment by patrickm02L** [comment]
@johnclary everything works! 

reference: SMS #7992, SMO #7999
