### ISSUE TITLE
BUG: EX and TURP New Permit & Extension fees don't insert w/ the tech surcharge (On PROD)🎉🎉

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7707]
### Whenever the TURP New Permit Fee or EX New Permit Fee is inserted, or TURP Extension Fee, or EX Extension Fee, the ATD Tech Surcharge ROW Fee needs to also insert at 4%. 
_During the automatic add phase, the system should insert the ATD Tech Surcharge ROW Fee at 4%._

**Stakeholders:** Kim and Paloma
----

Fee Insertion for EX Extensions
System should insert fees and bill them in the EX folders when 'Extension Granted' attempt is made in the ROW Admin Process based on the following criteria:

Secondary/Extension Fees
-- If Info field 'Secondary?' is answered Yes, insert Excavation Permit Fee - Secondary ($95)
-- If Info field 'Secondary?' is answered No, insert Excavation Permit Fee - Extension ($195)

ROW Usage Fee
-- If the info fields under Info Group 'ROW Usage' contain a non-zero value (any value apart from blank or 0), system should calculate and insert ROW Usage fee.

ATD Tech Surcharge
-- System should also insert ATD tech surcharge automatically, which 4% of any fees inserted from the list above.

**Comment by Nadin-Nader** [comment]
email from Kim:
The ATD Tech Surcharge should insert and calculate 4% on any and all fees added. This applies to all folders with fees; so it would only exclude the Franchise Utilities. 

The ATD Tech Surcharge should insert with the application fee and should conform to the cost of service automation for all city departments. Therefore it should be billed along with the application fee when the permit is first submitted.

This ATD Tech Surcharge should also insert with ROW Usage Fees (Private Development and Project Connect only) and with extensions fees (all except Franchise Utilities).

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis and Development is in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - ATD Tech Surcharge TDS -84004 added to EX and RW-TURP Fees

** EX Fee**

1. EX Permit Fee-New - 50176 
2. Ex Permit Fee-Secondary - 50177 
3. Ex Permit Fee - Emergency - 50178 
4. Ex Permit Fee-Extension - 50179 

** RW-TURP Fee**

1. TURP Permit Fee-New - 50322 
2. TURP Permit Fee-Emergency - 50324
3. TURP Permit Fee-Extension - 50325

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted DEV DP. Please approve and create task id for me.

Commit ID - 002eb2ee7856

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have submitted this request to the DevOps CM Team to deploy to **_DEV_** under **SCTASK0182182**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to **DEV**, Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV environment. all fees are working as expected. can be moved to TEST.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0182897**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on the DevOps CM Team to deploy to **_TEST_** under **SCTASK0182897**

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to **_TEST_** Please UAT and let me know the outcome

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - ATD Tech Surcharge TDS -84004 added to EX and RW-TURP Fees

** EX Fee**

EX Permit Fee-New - 50176
Ex Permit Fee-Secondary - 50177
Ex Permit Fee - Emergency - 50178
Ex Permit Fee-Extension - 50179 (Only Insert & Run) 
** RW-TURP Fee**

TURP Permit Fee-New - 50322
TURP Permit Fee-Emergency - 50324
TURP Permit Fee-Extension - 50325 (Insert & Run + Extension Granted Attempt)

**Comment by TracyLinder** [comment]
### Note

The tech surcharge has to be exactly 4%. We should not round up or down.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per Kim & Paloma, i will update the ATD Tech Surcharge ATD from ATD Tech Surcharge TDS for the new ATD Fees that we have added. thank you.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - DEV DP for #7707 upon updating the ATD Tech Surcharge for ROW. Kindly approve and create task id for me . Here is the commit id: 0e4019b94115

Demo prepared and sent to Nadin in teams.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have sent this to the DevOps CM Team for deployment to **_DEV_** under **SCTASK0184880**

**Comment by Nadin-Nader** [comment]
**Status:** 
Waiting on DevOps CM Team to deploy the New Changes to **_DEV_** under **SCTASK0184880**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have resent this to the DevOps CM Team to deploy the New Changes to **_DEV_** under **SCTASK0185376**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy the Newer Changes to **_DEV_** under **SCTASK0185376**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to **DEV**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Tested in DEV and all looks good. As per the above approval submitted TEST DP. Please approve and create a task id for me. Here is the commit ID: b8af8bd5426d

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have sent this to the DevOps CM Team to deploy to **_TEST_** under **SCTASK0185749**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on DevOps CM Team to deploy to **_TEST_** under **SCTASK0185749**

**Comment by Nadin-Nader** [comment]
**Status:**
Changes have been deployed to TEST. @Sreelatha-BlazeKannan is doing UAT and Paloma will start her UAT at 1pm if it is ready.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST. All working as expected. That is EX & RW-TURP New fees getting added with ATD Tech Surcharge insertion of exact 4% and tested #7828 AC - When emergency info is Yes then no fee should be added for all sub/work types

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted PROD DP; please approve and create task id for me. Commit ID : b8af8bd5426d

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  **SCTASK0185949** is the TASK for this to be deployed to **_PROD_**

**Comment by Nadin-Nader** [comment]
Closing as i have not heard anything on this, it is on PROD and i informed the stakeholders yesterday that i would be closing it
