### ISSUE TITLE
New field: Archive Historical Signal Engineer Areas in Signal Details page

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7709]
Allyson R
AMD

Emailed
>We’re looking forward to the signal engineer area restructuring. After some preliminary discussion, from a data standpoint we think the following would be useful:

>- Archiving the original signal engineer area. We’d be happy to have this as an archived/not visible field and be able to pull if needed.
>- Thinking this archived/historic field could live in signal details, but the current signal engineer area could continue to be the only thing visible in SRs.

**Comment by dianamartin** [comment]
Talked to Allyson about this because I was confused as to what what happening. Apparently Brian G. was going to talk to me about it. 

@johnclary @jaime-mckeown  FYI:
Sounds like they want to change the geographic boundaries of the AMD Signal Engineering Areas. They'll probably work with the Geo team on that, but before the changes are made the Apps team has to create a new field `Archived Area` that takes a snap shot of the existing Signal Engineering Area on the `signals` object table.

**Comment by johnclary** [comment]
Thanks. Changing the districts is fine. We'll need to re-associate all the records with the new areas. I'm not convinced we need to preserver the historical area—what purpose would that serve?

**Comment by dianamartin** [comment]
@johnclary the stakeholders are specifically requesting it, but I can find out their need for it.

**Comment by amenity** [comment]
Thanks, @dianamartin - adding this to our stakeholder discussions

**Comment by amenity** [comment]
We don't need to explicitly store this in Knack, we just need to backup the current geospatial layer so that we can refer to it in the future if necessary.

**Comment by amenity** [comment]
@jaime-mckeown - have you received a request to update the signal engineer areas recently?

**Comment by amenity** [comment]
@dianamartin will reply to the email to see if they still want this.

**Comment by jaime-mckeown** [comment]
The last update I did was in August and it was only to change an attribute in the table.

**Comment by dianamartin** [comment]
Emailed Allyson - 12/8
>Is this a need for AMD to archive the signal engineer areas?

**Comment by dianamartin** [comment]
I replied 12/9
>As a middle ground, we can simply save a copy (snapshot) of the signal engineer areas in a GIS format and in the future if you need to reference anything we can do a spatial join with the signals in GIS rather than keeping the signal engineer area snap shot on the signals table. Thoughts?

Allyson replied
>I think that sounds like a perfect compromise. Thanks Diana!

# Action Items
Save GIS layer of AMD Signal Engineer Areas at current state 20211209 @amenity @jaime-mckeown do we create a new issue for this?

**Comment by jaime-mckeown** [comment]
I will create a new Issue to archive the GIS layer, then add a link to it in this Issue if that works.

**Comment by dianamartin** [comment]
@jaime-mckeown That works, thanks!

**Comment by amenity** [comment]
Per 👆, this won't be necessary. Thanks, @jaime-mckeown !
