### ISSUE TITLE
[Spike] Investigate (and remove?) current_status column from moped_project

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#7717]
`Current_status` has been used in the UI in the past with text values and is currently a text column. We already have a `status_id` set up in a relationship with `moped_status`. We don't really need this column but we're not sure of any dependencies with this exact column due to its use in the UI.

**Comment by zappfyllc** [comment]
We are no longer planning to implement a separate `moped_project_status` table to avoid the dependencies here. But we should remove this column still

**Comment by amenity** [comment]
@sergiogcx @zappfyllc if y'all think this is going to be a 5, do you mind if I remove it from the epic?

**Comment by sergiogcx** [comment]
@amenity yea, I have been thinking it is going to be a 5. It can be removed from the epic for now.

**Comment by amenity** [comment]
@sergiogcx, thanks!

**Comment by sergiogcx** [comment]
So the amount of effort for this is epic-worthy, these are all the files that are affected by that field:

```
❯ grep -rIno "current_status" src

src/queries/project.js:11:current_status
src/queries/project.js:42:current_status
src/queries/project.js:813:current_status
src/views/projects/projectsListView/ProjectsListViewExportConf.js:19:current_status
src/views/projects/projectsListView/ProjectsListViewExportConf.js:20:current_status
src/views/projects/projectsListView/ProjectsListViewFiltersConf.js:55:current_status
src/views/projects/projectsListView/ProjectsListViewQueryConf.js:95:current_status
src/views/projects/projectView/ProjectSummary/ProjectSummaryCurrentStatus.js:28:current_status
src/views/projects/projectView/ProjectSummary/ProjectSummaryCurrentStatus.js:83:current_status
src/views/projects/projectView/ProjectSummary/ProjectSummaryTable.js:31:current_status
src/views/projects/projectView/ProjectView.js:351:current_status
src/views/projects/projectView/ProjectView.js:351:current_status
src/views/projects/projectView/ProjectView.js:437:current_status
src/views/projects/projectView/ProjectView.js:451:current_status
src/views/projects/projectView/ProjectTimeline.js:500:current_status
src/views/projects/projectView/ProjectTimeline.js:506:current_status
src/views/projects/projectView/ProjectTimeline.js:579:current_status
src/views/projects/projectView/ProjectTimeline.js:585:current_status
src/views/projects/projectView/ProjectTimeline.js:604:current_status
src/views/projects/projectView/ProjectTimeline.js:638:current_status
src/views/projects/projectView/ProjectActivityLogTableMaps.js:40:current_status
src/views/projects/projectView/ProjectActivityLogTableMaps.js:926:current_status
src/views/projects/newProjectView/NewProjectView.js:74:current_status
```

As a summary:
1. it will require multiple database migrations.
2. Graphql query refactoring (at project.js) (easy but with lots of scope creep)
3. Adjusting the projects list's configuration, filters, etc. (easy, lots of scope creep)
4. Updating the project summary table. (medium)
5. Updating the project view (medium)
6. Updating the timeline file (hard)
7. Refactoring of the activity log configuration (easy)

**Comment by sergiogcx** [comment]
Current phase is a little bit wilder:

```
❯ grep -rIno "current_phase" src

src/queries/signals.js:38:current_phase
src/queries/project.js:10:current_phase
src/queries/project.js:18:current_phase
src/queries/project.js:41:current_phase
src/queries/project.js:81:current_phase
src/queries/project.js:86:current_phase
src/queries/project.js:220:current_phase
src/queries/project.js:252:current_phase
src/queries/project.js:263:current_phase
src/queries/project.js:263:current_phase
src/queries/project.js:278:current_phase
src/queries/project.js:343:current_phase
src/queries/project.js:866:current_phase
src/queries/project.js:872:current_phase
src/views/projects/projectsListView/ProjectsListViewExportConf.js:22:current_phase
src/views/projects/projectsListView/ProjectsListViewExportConf.js:23:current_phase
src/views/projects/projectsListView/ProjectsListViewFiltersConf.js:66:current_phase
src/views/projects/projectsListView/ProjectsListViewQueryConf.js:107:current_phase
src/views/projects/projectView/ProjectView.js:317:current_phase
src/views/projects/projectView/ProjectView.js:321:current_phase
src/views/projects/projectView/ProjectView.js:322:current_phase
src/views/projects/projectView/ProjectView.js:337:current_phase
src/views/projects/projectView/ProjectView.js:350:current_phase
src/views/projects/projectView/ProjectTimeline.js:172:current_phase
src/views/projects/projectView/ProjectTimeline.js:175:current_phase
src/views/projects/projectView/ProjectTimeline.js:178:current_phase
src/views/projects/projectView/ProjectTimeline.js:372:current_phase
src/views/projects/projectView/ProjectTimeline.js:375:current_phase
src/views/projects/projectView/ProjectTimeline.js:501:current_phase
src/views/projects/projectView/ProjectTimeline.js:507:current_phase
src/views/projects/projectView/ProjectTimeline.js:517:current_phase
src/views/projects/projectView/ProjectTimeline.js:556:current_phase
src/views/projects/projectView/ProjectTimeline.js:559:current_phase
src/views/projects/projectView/ProjectTimeline.js:563:current_phase
src/views/projects/projectView/ProjectTimeline.js:580:current_phase
src/views/projects/projectView/ProjectTimeline.js:586:current_phase
src/views/projects/projectView/ProjectTimeline.js:605:current_phase
src/views/projects/projectView/ProjectTimeline.js:620:current_phase
src/views/projects/projectView/ProjectTimeline.js:620:current_phase
src/views/projects/projectView/ProjectTimeline.js:621:current_phase
src/views/projects/projectView/ProjectTimeline.js:632:current_phase
src/views/projects/projectView/ProjectTimeline.js:639:current_phase
src/views/projects/projectView/ProjectActivityLogTableMaps.js:55:current_phase
src/views/projects/projectView/ProjectActivityLogTableMaps.js:672:current_phase
src/views/projects/newProjectView/NewProjectView.js:70:current_phase
src/views/projects/newProjectView/NewProjectView.js:146:current_phase
src/views/projects/signalProjectTable/SignalProjectTable.js:106:current_phase
src/views/projects/signalProjectTable/SignalProjectTable.js:124:current_phase
src/views/projects/signalProjectTable/SignalProjectTable.js:127:current_phase
src/views/projects/signalProjectTable/SignalProjectTable.js:198:current_phase
src/views/projects/signalProjectTable/SignalProjectTable.js:204:current_phase
```

**Comment by sergiogcx** [comment]
@amenity Moving this to the backlog as it needs further discussion.

**Comment by amenity** [comment]
@sergiogcx - sounds good, thanks for the update.

**Comment by amenity** [comment]
@sergiogcx @zappfyllc - given the level of effort here I am tempted to take this out of Moped 1.0.

**Comment by sergiogcx** [comment]
We must consider that we have been writing one year of code based on the two columns, rolling back will not be trivial and will require the effort by more than one developer. 

This may be a high-effort/low-reward situation, so if this is not critical to Moped 1 we can leave the columns there for now, keeping in mind these things will have to change slowly.

**Comment by zappfyllc** [comment]
@amenity This can definitely be removed from Moped 1.0: I mostly wanted out of this issue exactly what @sergiogcx provided in terms of insight on the dependencies. So I actually consider this "spike" to be completed with what he's provided, but I'm totally fine with leaving this issue open for now as a placeholder and tackling it down the road.

Sergio, thanks so much for your work on this! This summary below was super helpful:

> it will require multiple database migrations.
> Graphql query refactoring (at project.js) (easy but with lots of scope creep)
> Adjusting the projects list's configuration, filters, etc. (easy, lots of scope creep)
> Updating the project summary table. (medium)
> Updating the project view (medium)
> Updating the timeline file (hard)
> Refactoring of the activity log configuration (easy)

Given some of these items will inevitably be addressed via other issues (for example, Amenity raised the status issue in #7827 and #7831, which should cover a couple/few of these), I think that's an appropriate way to handle this situation for now and not worry too much about a clean removal of these columns until later.

This is also the kind of issue I can address in the future as a dev if we need some extra hands on deck for this kind of tedious task thanks to Sergio's analysis here.

**Comment by amenity** [comment]
@sergiogcx @zappfyllc - Makes sense to close the spike. Opening this for the backlog: #7910
