### ISSUE TITLE
Meeting: Banner Permits/Payments in Knack Sprint Review

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7728]
Sprint Review scheduled 11/16

@dianamartin here is the link to [slides](https://docs.google.com/presentation/d/1p9Yr29mCKBxtYdjpciQN4epKZNJavP6bSkb27h-Vkc4/edit#slide=id.p)

**Comment by moorerst** [comment]
- Remove Pursue Banner Sponsor info

- Fees charged by # of poles not # of banners - 

# of Poles Requested

- Stakeholder will provide wording for the Submitted email notification
- Add text that explains the install and removal requirements
- Decide on process for having the customer edit an application
- email notification to atxstreetbanner when new application is submitted
- ability to adjust price ?

**Comment by dianamartin** [comment]
Diana's Notes

### Email Confirmations
- [ ] Set up email confirmation - submitted to customer and atxstreetbanner email

### Payment Steps
- Invoice generated by CityBase
- Keeping the Knack invoice

- [ ] Remove banner sponsor messaging on "Portal" page

### Customer Information
- [ ] Ability to connect old banner organization - on the back end

Add Date Context on Installation and Removal Date input fields
- [ ] `Banner are installed and Removed on Tuesdays - LPB`
- [ ] `Banner are installed and Removed on Mondays - OTS

- [ ] Add `Number of Poles` to application - LPB

- [ ] Remove `Previous customer` field? Only remove the extra text

- [ ] Banner Locations - add map?

Next Steps: Staff is checking availability for your locations

**Comment by moorerst** [comment]
@dianamartin do you want a new issue for these task or do you want them added to the Develop Prototype issue 7530?

**Comment by dianamartin** [comment]
@moorerst we probably want to debrief so we can organize our build out

**Comment by dianamartin** [comment]
I added the feedback notes to #7530

**Comment by moorerst** [comment]
Closing this issue. Opening new issues for items discussed in Sprint Review.
Email notifications
Review tables/pages
Payment process
