### ISSUE TITLE
Update DAG with new Wheels token

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7742]
The DAG for Wheels, which retrieves hourly trip data and sends it to Socrata, failed. 

@sergiogcx triaged the failure and found that their token is expired. In order to continue to retrieve their hourly data we need to get a new token from Wheels.

@patrickm02L will reach out to the Shared Mobility Services team to get in touch with Wheels to get an updated token. 

![2021-11-16_10-34-41](https://user-images.githubusercontent.com/5566727/142039955-f61247a1-c70a-46d6-9ebe-706fabe98296.png)

**Comment by patrickm02L** [comment]
Andrea followed up with Will at Wheels, who said they would get us the token in the next 24hrs.

**Comment by sergiogcx** [comment]
This is done, closing.
