### ISSUE TITLE
[Enhancement] Allow users to update project status updates from the "Signal projects" table

### ISSUE THREAD

**Issue by zappfyllc** [cityofaustin/atd-data-tech#7749]
We need to add the status update component currently on the Project summary page to the column. 

![Screen Shot 2022-01-20 at 7 16 42 PM](https://user-images.githubusercontent.com/1463708/150448612-7e603409-7332-47b4-b512-b492c6c2213e.png)

**Comment by amenity** [comment]
Removing from the main epic. We can do this if/when users prioritize it.

**Comment by amenity** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Data--Technology-Services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/7749?planning-poker) with ZenHub @chiaberry @tillyw @mateoclarke @frankhereford

**Comment by amenity** [comment]
Per conversation with AMD, we're not confident this will be really useful functionality. Instead, we're going to prioritize a basic version of #3683 that lets users update statuses.

**Comment by amenity** [comment]
The edit modal is going to be on the personalized dashboard, so this issue is superceded by #8806.
