### ISSUE TITLE
All New COS Payment Automation need to change the status "Application Incomplete" when not Submitted

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7755]
All New COS Payment Automation need to change the status "Application Incomplete" when not Submitted
Stakeholders: Paloma, Kim

Current function:

Applicant selects "Save and Finish Later" in the portal, the payment automation for COS works but it is making the status of an incomplete application "Internet Pending" and not sending it to the "My Incomplete Applications" menu.

How it should function:

Applicant selects "Save and Finish Later" in the portal, the system does the COS automation, changes the status to "Application Incomplete" and sends it to the "My Incomplete Applications" menu.

Acceptance Criteria:

If "Save and Finish Later" is selected:
-  The System will do the COS automation and change the status to "Application Incomplete"
-  The system will send the incomplete application to the "My Incomplete Applications" menu

**Comment by Nadin-Nader** [comment]
@TracyLinder This came about in the UAT for #6562

**Comment by TracyLinder** [comment]
This is no longer an issue.
