### ISSUE TITLE
Enhancement: Banner Permits in Knack Email Notifications

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7761]
Set up email notifications for staff and customer when new Banner application is submitted

**Comment by dianamartin** [comment]
- # [x] Configured OTS customer submission email
![image](https://user-images.githubusercontent.com/21112975/145260151-5f76eb67-8d7b-44fb-a530-86a809b0d98f.png)

**Comment by dianamartin** [comment]
# - [x] Configured LPB customer submission email - "Approved - Pending Payment"
![image](https://user-images.githubusercontent.com/21112975/146846552-f9f53724-daee-43c2-9fea-dea09996b72f.png)

**Comment by dianamartin** [comment]
Sync'd with Stephanie - 12/21 and showed her the email notifications for customer submissions, staff notifications and payment notifications as well. Total 6 emails have been configured until we figure out the payment solution for it. We have a meeting with stakeholder next week.

**Comment by dianamartin** [comment]
Reviewed with stakeholders during sprint review meeting. No feedback about emails templates at this moment. Will open new issues if changes arise.
