### ISSUE TITLE
Discovery: Banner Permits/Payments in Knack Payment Process

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7764]
Mock up Payment Process

This issue is to do some discovery on the payment pages in Knack and write the webhooks for CityBase integration.

**Comment by moorerst** [comment]
Citybase SOW discussion issue #8112
Next Steps:
Get Statement of Work done
Get it into project queue
Statement of work for standard checkout
writing to those specs to generate payment page and send payload
Assign solution engineer will gather requirements
Q; Timing and quickly this moves?

How quickly do we need to mobilize?
Mark: not going to leap frog (APH - in March)
ATD would be after (started discovery in March, start in April)

**Comment by moorerst** [comment]
Email communication from vendor regarding service fee:
With our engagement with the City, there is an option to assess a service fee to the payer for Card and Check payments. This effectively passes on the cost of processing the transaction to the payer, as opposed to incurring that fee in the Department. 

For example, if you elect to assess a service fee, if someone is charged $100 for their street banner permit, a $2.35 fee would apply bringing the total payment to $102.35.

The fee amounts are:
•	Card: 2.35% (min $2.00)
•	Check: $0.55 
Do you know if your department will elect to assess the fee to the payer, or do you plan on absorbing that cost? 

Response from Lauren:
If there’s any choice in the matter, I’d rather not have that fee be passed to street banner program customers.

**Comment by moorerst** [comment]
Per Lauren
After chatting with Cathy about the pros/cons, I’d think having the customer pay the service fees is the right way to go. Absorbing the service fee isn’t financially responsible to the taxpayers. 

If possible on the payment page, I just ask that we be transparent about the difference in costs between e-check and credit card fees.

**Comment by moorerst** [comment]
Other CityBase requirements documented in issue #8268

**Comment by moorerst** [comment]
Informed CityBase of the decision to pass the service fee to the customer.
Response from Matt/CityBase: Thank you for confirming. That should be all of the information we need to move forward. I will finalize the document and Jim B will follow up with your team for next steps

**Comment by moorerst** [comment]
We have completed the Discovery phase with Citybase. Citybase is now beginning the Build phase. We have no action items at this time, waiting for next steps from Citybase.

**Comment by moorerst** [comment]
Recurring weekly check in meetings (Monday's) for the build phase have been scheduled with Citybase.
Agenda:
The purpose of this call is a weekly stand for CityBase and ATD teams to connect on build progress and address any issues/questions that have arisen.

**Comment by dianamartin** [comment]
@chiaberry @moorerst 
# Banner - LPB Application Details page - this page is for when a user is redirected their application details to make a payment, they will see a button "Make Payment", see below
- `scene 1219`

The button that goes to "Make Payment" - which is just a place holder to show "Payment Successful"
- scene_1278/views/view_3377/rich_text
- `scene 1278`
- `view 3377`

# Banner - OTS Application Details page - this page is for when a user is redirected their application details to make a payment, they will see a button "Make Payment", see below
- `scene 1243`

The button that goes to "Make Payment" - which is just a place holder to show "Payment Successful"
- scene_1278/views/view_3377/rich_text
- `scene 1278`
- `view 3377`

**Comment by chiaberry** [comment]
@dianamartin @chiaberry synced 10/5 on knack integration
happy path - inventory transaction to citybase, citybase back to knack

updating new knack object table: citybase messages, record messages from citybase postback

unhappy path - refunds will insert a new record into the transactions table while voids will just update existing transaction record in the table.

make payment big button, add hidden transactions table for sysadmin only to get information for payment request

add transaction status "refund" in dropdown choice

@chiaberry create ticket for her postback dev work
@dianamartin ticket for apps work
