### ISSUE TITLE
Formstack account migration

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7765]
Our team manages the Formstack enterprise account;  and, we have been advised to migrate to Formstack’s  unified authentication and account management service. 
Unfortunately, when we migrate the City’ account, your free account will no longer be able to access Formstack.  

Please let me know if you have any questions or if you would like to consider a paid account.  

We have some programs that are using Form Stack need to determine how they will be affected by this change.

**Comment by moorerst** [comment]
Meeting scheduled with CTM 1/3

**Comment by moorerst** [comment]
Met with CTM to get a better understanding of the changes to Form stack forms:

- updating to a secure attachment upload which is require a license to view

- One Drive is the selected 3rd party integration tool for attachments

- Formstack account will need to be given access to integrate attachment to One Drive

- ATD currently has 2 forms that are using attachments Zero Damages Report & Get Home Safe Ticket Wavier Form

- Forms will be saved on the ATD One Drive folder
- Email notification will provide a link to the attachment on One Drive
- In general our process will not change as we are evaluating new use cases for Form stack this new integration process will be explained
- Diana will test the ability to integrate attachments to One Drive

**Comment by dianamartin** [comment]
# Diana's Notes 
_Meeting with Mireya (CTM) and Stephanie M._

FormStack change in "secure" attachments - those who used to get links to see user attachments will require a FormStack licenses to view attachments 
- CTM tested out 3rd party integrations, but landed on OneDrive bc of the need to have a O365 account to access files
- They've created a OneDrive for all departments and their attachments will be stored there, users can't manage the attachments, but simply view them
- CTM will tackle the retention of the forms at a later date

## How to change from FormStack to One Drive
Go to form back end
Go to "Settings"
Go to "Integrations"
Look up "OneDrive", click add
Should see a folder tree to select "ATD"

### Zero Damages Report 
- Failed to do `SmartSheet` - follow-up? 

During the call I tested if I could add the OneDrive integration for the Get Home Safe form and was not able to. Had some permission errors. 

- [ ] Follow-up with ROW about forms, if we can delete the forms or need to save anything?

**Comment by moorerst** [comment]
set email to ROW staff they confirmed the test data and the Formstack forms ROW Damage, Extension/Revision and ROW License Renewal can be deleted.

**Comment by dianamartin** [comment]
From Paloma/Darren's email, good to remove forms: 
Paloma said
>We no longer require access to either of the highlighted forms below.

Darren said
>- To add to Paloma –the test form titled “ROW Damages” can also be deleted, I also highlighted it as well.
>- We do need to keep the “Zero Damages Report” since we still use that one – it’s highlighted in green.  

![image](https://user-images.githubusercontent.com/21112975/149007856-a8fd159e-097e-48d7-a117-b2251ac177b0.png)

Delete these forms
- [ ] Row Damages
- [ ] Extension and/or Revision Request
- [ ] ROW License Renewal
