### ISSUE TITLE
Meet with RAS to discus data questions

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7768]

**Comment by johnclary** [comment]
@andrewshensky please create follow-up issues after the meeting.

**Comment by andrewshensky** [comment]
![image](https://user-images.githubusercontent.com/80716478/142647004-9ca5bbf0-3fc5-4fe5-8bb2-0cb1ec1bde4a.png)

- In scenario above, RAS's standard would be to use the data from the most recent date driven to map the features. If that data is not sufficient, they would resort back to a previous date driven. Using most recent data driven is in line with our current processing, but this may create a manual review component on our end to check scenarios where RAS uses data from an earlier date with higher data quality.
- **Driving should be all completed the first week of December**, this should eliminate any issues with changes to the date driven data. Once driving is complete the date driven data should be stable.
- **Pilot data should be provided week after Thanksgiving**
