### ISSUE TITLE
Create new project table and details in Data for Moped v1.0 migration

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7776]
Replace the current Data Tracker projects table and details pages with a new set of pages that includes only the limited field set coming over from Moped.

We can do this well ahead of the migration, but keep the pages hidden in the Data Tracker until launch.

**Comment by zappfyllc** [comment]
@amenity @johnclary Linking #7777 here since we have a discussion going on that ultimately impacts whether we need this or not. Happy to discuss whenever!

**Comment by amenity** [comment]
Discussed during grooming and we'd _prefer_ not to do this. 

We talked about:
- Adding a column (and filter?) for "Project" on the [Data Tracker work orders page](https://atd.knack.com/amd#work-orders/)
- Adding a list of a projects' work orders to the "Summary" tab, a la "Data Tracker signal IDs" signals here  
![Screen Shot 2021-12-08 at 5 44 14 PM](https://user-images.githubusercontent.com/1463708/145308922-9eb69cfb-67cb-4b18-94f3-42fcb553aacb.png)

@zappfyllc @johnclary and I still need to meet with Renée and Ivonne next Thursday 12/16 to review the dashboard and Data Tracker --> Moped workflow, so this remains a possible solution.
