### ISSUE TITLE
Implement "Status update" history link

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7778]
![Screen Shot 2022-03-22 at 12 31 43 PM](https://user-images.githubusercontent.com/1463708/159583588-6205cb92-44e0-437b-9ec1-69b5c1ffc2c0.png)

Use [history](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Ahistory%3A) icon; link to "Comments" tab filtered down to status updates.

**Comment by amenity** [comment]
@amenity - also add specs for viewing date stamp and author of note in the heading; 
Also try out + /pencil icons next to history.

**Comment by amenity** [comment]
@patrickm02L - Renée and Ivonne would like to see this implemented, along with attribution for the Status update on the summary page. They also mentioned that having the ➕  icon all the way over on the right feels a bit awkward. 

I mocked up a couple options in the "Project Summary" XD:  
![Summary Page – Updating status update](https://user-images.githubusercontent.com/1463708/159399677-28bceb2b-e805-4df4-9db6-fd1c7a631170.png)
This one draws on your [Activity Feed 2.0 design](https://github.com/cityofaustin/atd-data-tech/issues/6496)
![Summary Page – Updating status update – 1](https://user-images.githubusercontent.com/1463708/159399680-6f680f87-20f6-41bf-8f4a-0dee0f423fe5.png)

Thoughts?

**Comment by johnclary** [comment]
The status update history is now available in the [status update modal](https://github.com/cityofaustin/atd-moped/pull/788).
