### ISSUE TITLE
Go Live Parking Meters non 311 SR's

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7780]
Go Live scheduled 12/1

**Comment by moorerst** [comment]
Check in with team:
I’m just checking in to see how things are going with the Parking Meter SRs. Need anything, finding things working okay for y’all? 
 
Just let us know, we’re hear to answer any questions.

Response:
So far, so good. Back office to exporting into Excel needs some work on my end. The last two days have been good.

To Date:
SR's Closed - 25 for Inspection, Damaged, Graffiti, Permit Material Issues, 

SR's in Final Review - 1

SR's In Progress - 2

Will schedule a follow up check in meeting

**Comment by moorerst** [comment]
Communicated with Parking Enforcement and Parking Meters stakeholders to get their feedback on how the Go Live is going:
PM - Dianna/Stephanie,
Please see the attached. I addressed the address situation with Shavyvonne.

On another note, we have been getting several of these types of work orders that mention possible malfunctions. I think we should add Meter Malfunctions to our list of categories if at all possible. This would also allow us to have a category to send out the morning call list. Currently I am currently sending it out under Preventative Maintenance which really does not fit. Is that possible?

Seems like we are taking to this pretty well. Will need some future training on certain things like reports and stuff.

PE - No issues to report on our end.

We'll review Parking Meters request for a new Issue Type

**Comment by moorerst** [comment]
@dianamartin how long do we keep this issue open? We are 2 weeks into the Go Live with no issues.

**Comment by dianamartin** [comment]
@moorerst I think we're in the clear especially from the reply we got from David. We might want to ear mark a date to check in with them for the new "Issue Type" or we can wait until they bring it up again.

**Comment by moorerst** [comment]
@dianamartin I put the new Issue Type issue in the backlog so I'll remember to check in with them later. Closing this issue. 
Great job I'm excited about this one, think it will open up new opportunities for that group.
