### ISSUE TITLE
[Bug] CircleCI failure notification when merged to atd-vz-data

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7784]
CircleCI is failing. Will need to have compiler to build libraries updated.

Messaged @sergio yesterday 11/17/21 to ask about a failure notification I got from Circle CI.

> I'm not sure if this is common behavior, but I've gotten this message that CircleCI has failed both times I merged today. 
> 
> Also, I looked at the commits page on github and it looks like a Franks merge's are also failing. 
> 
> https://github.com/cityofaustin/atd-vz-data/commits/master
> 
> Thoughts?

Failure notification:

![Screen Shot 2021-11-18 at 10.54.59 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/c4838b72-964c-4752-acc8-7fc042e53640)

He messaged back:

> ...yes the CircleCI builds have been failing. It's not uncommon for pipelines to break due to external factors (e.g., library upgrades and deprecations, services being down, etc.)
> 
> I took a quick look and for some reason the container that builds the python ETLs no longer has the C/C++ compiler to build python libraries and it is failing to install them.

**Comment by sergiogcx** [comment]
It took about an hour of troubleshooting and trying different versions of packages, reading some docs. Nothing crazy, but I did have to merge to master to really know if this was going to work.
