### ISSUE TITLE
[Enhancement / TIA] Filter out TIA Cases That Aren't Submitted Yet

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7787]
### As a TIA Reviewer, I don't want to see incomplete TIA applications in our queue. 

**Stakeholders:** Nathan, Joann

- Update the 'All' filter tab based on the below:
    - Per Chrispin, he already has a boolean field to check if the app has been submitted. He will filter out the incomplete cases based on this field.

**Comment by TracyLinder** [comment]
@ChrispinP this isn't urgent. We'll get it On Deck for the next sprint beginning 12/1

**Comment by ChrispinP** [comment]
@TracyLinder for clarification, we want to filter out incomplete applications entirely from the TIA Review table and remove the No Status/Incomplete filter tab? Added my estimate, this is a quick fix. Feel free to throw on Deck

**Comment by ChrispinP** [comment]
Updated Filters based on Application Submitted
![image](https://user-images.githubusercontent.com/67915167/146245313-010d691a-aa25-4ff6-b1c0-fdb10644aee4.png)
![image](https://user-images.githubusercontent.com/67915167/146245354-4fe35ceb-b1e6-4489-8f14-68a6c4dbb4a5.png)

Ready to review
