### ISSUE TITLE
New Solution for CR3 PDF retrieval process

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#7801]
With the CRIS 23.0 software release, ReCAPTCHA has been implemented on the login page which breaks our current process of automatically downloading CR3 PDFs in bulk via the Python Splinter framework. 

The way our existing process worked was by using [this script](https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/app/process_cris_cr3.py#L1) to login, create a valid session in CRIS and then get all the session cookies from the browser. With those cookies and using [helper functions like this one](https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/app/process/helpers_cr3.py#L123-L140), we could then reverse engineer the endpoint to access the PDF for each crash, iterate over a list of crashes, and then upload their PDFs to our S3 bucket. This process ran every 30 minutes in Airflow on [this DAG](https://airflow.austinmobility.io/code?dag_id=atd_visionzero_cr3_production&root=).

After discussions today, instead of trying to beat the new ReCAPTCHA login page, we'd like to explore two new potential paths forward for retrieving CR3 PDFs in bulk:

1) Is there a way were could use Splinter and our existing Airflow ETL process using Brazos endpoints instead of CRIS? Brazos uses Case IDs instead of Crash IDs. Could we use a list of Case IDs and download PDFs in an automated way? Also important to note this would only cover crashes where APD filled out the crash report.

2) Could we create a new Python script that works similar to our existing process? It would still use the CRIS endpoint but would take input values of browser cookies retrieved manually from a browser session initiated by a human that has gotten past the ReCaptcha riddle. This could be a local script that uses AWS helpers to upload the PDFs to S3.

Other ideas:
- add feature to VZE to trigger single ad-hoc PDF retrieval 
- embed iframe in VZE that lets you log into CRIS manually and then stores your cookies temporarily to trigger a bulk download.

**Comment by frankhereford** [comment]
Good news; the end point which serves up the PDFs continues to do so as y'all expected if you give it the same base64 encoded parameters. I am hopeful to have a PR for you all to review NLT first thing in the morning. I think the route where we baby the script and pass it valid, current cookies should get us back in business. 

More info to follow - thanks!

**Comment by frankhereford** [comment]
I have branched the repo and hacked together [a derivative of the CR3 downloading script](https://github.com/cityofaustin/atd-vz-data/blob/flh_7801_cr3_downloading/atd-etl/app/process_cris_cr3.py) which takes the cookie string as found in the request header to the CR3 end point and a list of CR3 crash IDs and downloads these files and processes the in the normal way. I will execute the script tomorrow after our normal CRIS tabular data ingest, and I will report on my experience using the script to maintain our CR3s current. There are plenty of rough edges that can be added to make it easy to use, but I am hopeful this is a good start.

**Comment by frankhereford** [comment]
At @patrickm02L's request, I have documented the process I'm using to download new CR3 PDFs, for when we resolve getting new tabular crash data via the CRIS-SFTP process. You can find that documentation for the workaround here in #7815.

**Comment by mateoclarke** [comment]
This issue is resolved for our immediate purposes. But I think we should open a PR (even if we never merge it) with Frank's branch that changes the way `process_cris_cr3.py` operates. This will just make sure we keep that code in mind. I'll do that once close this issue. 

After we have a conversation with the VZ team about this obstacle, we can open a new issue to track our next steps and ides for a more sustainable PDF retrieval process.

**Comment by mateoclarke** [comment]
https://github.com/cityofaustin/atd-vz-data/pull/1048
