### ISSUE TITLE
Update Fee_EX_New Procedure so EX invoices correctly (On PROD 🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7812]
### When the system inserts the EX New Permit Fee & Tech Surcharge, the system should automatically bill the fees. 

- On Fee_EX_New: Remove the validation based on user type. The fee should invoice regardless of the user type.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  For EX its all good as I see. To ensure need to test with you.

**Comment by SubhaShroff** [comment]
### Status:
The feature is already in place. Ready for UAT on TEST.

**Comment by Nadin-Nader** [comment]
@SubhaShroff here are Paloma's UAT Results on TEST:

> [6:52 PM] Amayo-Ryan, Paloma
**Test Results for Ticket 7812**
>     I'm not entirely certain where this ticket stemmed from but I believe it was related to Kim's COS test results (from an 11/9 email):
> 
> 
> 
> 	
> Project Connect added an application fee but did not create an invoice for them to pay online.
> 	
> Private added an application fee but did not create an invoice for them to pay online. (It looks like it functions correctly in PROD though.)
> 
> 
> We're fairly confident that this isn't an issue in PROD because if it were it would have been brought to our attention.
> 
> I submitted three applications (1 Private Development EX and 2 Project Connect EX) and was unable to pay fees online in all three cases.  Here are the three permits, none of which are showing up in the "My Bills" section of Portal Test:

![MicrosoftTeams-image (7).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/5994d733-dccf-4764-85a8-effca6c8d8b8)

**Comment by Nadin-Nader** [comment]
@SubhaShroff notes from Paloma this morning:

> [8:41 AM] Nader, Nadin
>     Amayo-Ryan, Paloma Good Morning, so is this working on PROD but not TEST, correct?
> ​[9:32 AM] Amayo-Ryan, Paloma
>     Nader, Nadin, morning!  That's correct.  PROD is functioning fine; I just confirmed this was the case.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Online Payment feature is working all good for EX. If the inserted fees are billed the fees will be available for online payment. In the above permits, the fees are not billed.

**Comment by TracyLinder** [comment]
### Update

I just updated the title & description. 
@SubhaShroff @Sreelatha-BlazeKannan who will be working this?

**Comment by SubhaShroff** [comment]
> ### Update
> I just updated the title & description. @SubhaShroff @Sreelatha-BlazeKannan who will be working this?

I will work on this.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  The change is done and DEV deployment request is raised - SCTASK0186292.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0186464 is submitted DEV deployment of the fix the Project Connect auto bill.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This ticket is fixed on DEV, I tested it. Please let me know if its good to go to TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  since you approved on Teams to move to TEST, I have submitted TEST Deployment request - SCTASK0186593.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is in TEST and I tested it.  Ready for your UAT.
![image](https://user-images.githubusercontent.com/51680715/146096130-c7813451-7c71-4b3c-af78-631df27ecd49.png)

**Comment by Nadin-Nader** [comment]
@SubhaShroff 
**Status:**
Approved by Paloma and Kim for **PROD**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  PROD Deployment request is submitted - SCTASK0187293.

**Comment by Nadin-Nader** [comment]
**Status:**
This is has been deployed to **_PROD_**

**Comment by Nadin-Nader** [comment]
Closing as i have not heard anything on this, it is on PROD and i informed the stakeholders yesterday that i would be closing it
