### ISSUE TITLE
Bug: Save Finish Later & Multiple Fees (On PROD Via 7162)🎉🎉

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7813]
### During the portal application for EX & RW-TURP, if the user chooses `Save Finish Later`, the system inserts another New Permit Fee. This is only happening on COS permit types. 

**Examples:**

- 2021-048796 RW
- 2021-048795 RW
- 2021-048843 EX

**Comment by TracyLinder** [comment]
@vschandramouli you're the lead BSA on this. Please help Sree w/ the acceptance criteria as needed.

**Comment by Nadin-Nader** [comment]
**Stsus: This should be fixed by #7162 If not Subha will manage

**Comment by Nadin-Nader** [comment]
Closing as i have not heard anything on this, it is on PROD and i informed the stakeholders yesterday that i would be closing it. Fixed by #7162
