### ISSUE TITLE
Indicate when CRIS ETL script runs successfully

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7814]
On 11/24, @mateoclarke and @frankhereford responded to an observation that @xavierapostol reported in Slack about why the latest CRIS data did not reflect the latest crash reports processed through 11/19. 

> Good morning y'all! I was hoping to go into the 4 day weekend without a hitch, but I noticed an issue with the crashes this morning. The last one we received was on 2021-11-17 and I went into CRIS to see how recent they have data. What I found was that CRIS has a few dozen crash reports that have been processed and the latest date should be 2021-11-19. Is there anything going on with the ETL? Or, is this the typical CRIS delay?

They checked the DAG and discovered it was running normally, the files for 11/19 were in the S3 bucket, but they were empty except for headers. We have records, but they are incomplete, which means there's a snag on CRIS's end. 

Mateo emailed CRIS Support to let them know they weren't actively pushing updates to us, and surmised this snag may have something to do with their recent CRIS 23.0 software update - which has also effected our CR3 PDF retrieval process (see #7801).

To be proactive about issues like this in the future, Mateo recommended that we augment our DAG to send a notification in the 'Airflow' slack channel when CRIS crashes reports are received successfully. This will allow the DTS team to monitor whether or not CRIS is delayed or there is something wrong with our ETL.  

It was also recommended that an enhancement further down the road would be to include this kind of notification into VZE, which would notify the VZ team when there are inconsistencies with records received.

**Comment by mateoclarke** [comment]
Just to add some clarification. Your description above might be confusing the Crash Date of the new/updated records and the download date of the CSV extract files. It was the CSV files from the extract on 11/21 (not 11/17) that were empty with only headers. They didn't include any crash records. After 11/21, we haven't received any new CSV files.

In terms of the solution desired, my opinion is that we should add logic to the existing ETL process that reports 2 things to Slack via Airflow, 

1) Were there any new files in the SFTP storage that were processed and moved to S3? 
- If yes, do nothing. 
- If no, flag a warning that CRIS didn't send us any new extracts the night before.

2) Were there any crash records in the new extract files?
- If yes, post to Slack as a success report the number of new and number of updated crashes.
- If no, post to Slack that there were no new or updated records as a warning.

**Comment by patrickm02L** [comment]
@mateoclarke thanks for responding with clarity and how to resolve the problem!

**Comment by frankhereford** [comment]
This issue may be deprecated with the completion of #9789.

**Comment by chiaberry** [comment]
Enough humans touch CR3s now that we will know if there is a silent failure somewhere.
