### ISSUE TITLE
ACE Conflicts Feature Layer: look into how to keep updated

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#7818]
Asked Maria about the ACE Conflicts feature layer that's in the ACE Downtown Conflicts Web Map that hasn't been updated since 2018. She said it would be a useful layer for their group if it's kept current. Will need to look into how Mat created this layer.

![image.png](https://images.zenhubusercontent.com/5cb8d2e073d7e234297df108/bd071572-f38f-46b1-b9ff-564902e40eaa)

**Comment by jaime-mckeown** [comment]
Web Map:
https://austin.maps.arcgis.com/home/item.html?id=d42b0ae4802e428e8a3c9d2783b2cb84
Feature Layer: 
https://austin.maps.arcgis.com/home/item.html?id=4e1f8bc4003b48a69d60ff3819c2980f

**Comment by ATD-ZachB** [comment]
This web map is now kept up to date on a weekly basis and is embedded in the process for updating the AMANDA ROW permits. Refer to "Amanda Street Closures: Weekly Updates - 2023" #11099 and subsequent epics that follow the same naming convention for future reference on this issue.
