### ISSUE TITLE
[Bug] Build process for editor is failing

### ISSUE THREAD

**Issue by sergiogcx** [cityofaustin/atd-data-tech#7819]
The build process is failing for the moped editor (and the api, but a new issue will be created for that one), even though there is no code to be linted:

![2021-11-29_10-46-21.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/468c34f0-953e-4bbd-94c4-bbdb08ea11e9)

![2021-11-29_10-51-46.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/96ddfa4d-c2ad-4813-9f78-afbdc7ad96d3)

None of the editor code has changed recently, will attempt to figure out what has changed to cause this problem.

**Comment by sergiogcx** [comment]
So we have to options:

1. Wait until github actions updates their npm version. If we wait, then we have to downgrade all our systems with it.
2. Use a docker for the build. This is a more elegant solution, so we are not bound by GitHub actions and Ubuntu to upgrade their npm versions, we will simply upgrade our docker image's version to match our local standard.

That being said, we do need to establish a local standard moving forward, we will likely need everyone to use nvm with nvmrc, if they aren't already.

https://github.com/nvm-sh/nvm#nvmrc

If any dev isn't familiar, it works/looks just like pyenv:

![2021-11-29_11-23-30.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/af5ea45b-6aca-4119-a6f1-7637ac538f19)

**Comment by johnclary** [comment]
thanks @sergiogcx - cc @mateoclarke. looks like we need to get the gang in the habit of using nvmrc?

**Comment by mateoclarke** [comment]
Sounds good. What version of node should we install and use with nvm? Will we be able to set that as configuration and have it automatically work with nvm in a local environment? Do we need to add any steps to the install process to the setup docs for this app?
