### ISSUE TITLE
BUG: Fees should NOT be applied to ANY Emergency RW TURP and EX Permits (On PROD via 7707)🎉🎉

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7828]
## Fees are being applied to the Emergency RW TURP and EX permits, Fees should **NOT** be applied to **ANY** RW TURP and EX

Stakeholder: Kim, Paloma

During UAT of #7162 COS Payment Automation - TURP & EX New Permit Fees,  Kim found that fees are being applied to the Emergency RW TURP and EX Permits:

RW- PWD 21-048876 RW (Emergency)
-	charged TURP permit fee- new (This is an emergency permit and should not be charged any fees!)
![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/65ecb0e9-18cd-4868-9ee9-4c3f98d659b3)

**Comment by TracyLinder** [comment]
I just sent a chat to Paloma & Kim asking for confirmation on this work

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP submitted; please approve and create task id for me. here is the commit id: 5d133e8a5ae5

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0183988**

**Comment by Nadin-Nader** [comment]
**Status:**
Waiting on the DevOps CM Team to deploy to **_TEST_** under **SCTASK0183988**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to **_DEV_** please UAT

**Comment by Nadin-Nader** [comment]
Maybe resolved by deployment to **_DEV_** on #7707

**Comment by Nadin-Nader** [comment]
**Status:**

This is resolved with #7707 and that was sent to DevOps CTM to be deployed to **TEST**
Waiting on DevOps CM Team to deploy to **_TEST_** under **SCTASK0185749**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST. All working as expected. That is EX & RW-TURP New fees getting added with ATD Tech Surcharge insertion of exact 4% and tested #7828 AC - When emergency info is Yes then no fee should be added for all sub/work types

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted PROD DP; please approve and create task id for me. Commit ID : b8af8bd5426d

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  **SCTASK0185949** is the TASK for this to be deployed to **_PROD_**

**Comment by Nadin-Nader** [comment]
Closing as i have not heard anything on this, it is on PROD and i informed the stakeholders yesterday that i would be closing it
