### ISSUE TITLE
BUG: ROW TURP Usage Fees are not available in the Insert and Run menu (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7829]
## ROW TURP Usage Fees are not in the Insert and Run menu and have to be calculated manually. This is adding work to the users.

Stakeholders: Kim and Paloma

During the UAT of #7673 BUG: TURP ROW Usage Fees are not updated or calculating Properly Kim found that the ROW TURP Usage fee is not in the Insert and Run menu

RW-PVT 21-048878 RW (Initial Issuance)
-	Insert & Run Procedure does not insert TURP ROW Usage Fees!
-	After completing TURP Review, no ROW Usage Fees were inserted.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Debugging is in progress.

**Comment by TracyLinder** [comment]
@vschandramouli please speak with Kim and find out exactly what the issue is. Thank you.

**Comment by vschandramouli** [comment]
Meeting scheduled with Kim and Paloma for 1/13/2022.

**Comment by vschandramouli** [comment]
Notes from meeting: 

- Kim and Paloma mentioned that the various ROW Usage fees used to be inserted 'Approved' attempt is made in TURP Review Process in RW-TURP folders. This is no  longer happening. 
- The system needs to auto-calculate and insert fee codes 50311, 50313, 50315, 50317, 50319, 50356 when Approved attempt is made in TURP Review process. 
- Since that is no longer happening, Kim tried to insert manually add the fee by going to Fee tab, clicking Insert and Run Procedure and selecting 'TURP ROW Usage Fee'. This is not doing anything. 
To fix this issue, system needs to auto-insert fees when approved attempt is made. And selecting TURP ROW Usage fee from Insert and Run should calculate correct fee and insert into the system.

**Comment by vschandramouli** [comment]
@Nadin-Nader  @SubhaShroff  I added my notes to this ticket. Please refer and let me know if there are any questions.

**Comment by Nadin-Nader** [comment]
**Status:**
Subha is debugging still

**Comment by SubhaShroff** [comment]
@vschandramouli  @Nadin-Nader  @TracyLinder 
The existing code logic summarized for TURP and my observations attached here in the document. 

Please let me know if you have any questions. 

[7829 - Existing Code Logic.docx](https://github.com/cityofaustin/atd-data-tech/files/7935479/7829.-.Existing.Code.Logic.docx)

**Comment by TracyLinder** [comment]
@vschandramouli will schedule a meeting w/ us and SME Evelyn P. to get the fees mapped and documented.

**Comment by TracyLinder** [comment]
**Update** Vish sent Evelyn teams mtg. She'll be in next week (out today).

**Comment by TracyLinder** [comment]
@vschandramouli will work on mapping ROW usage fees & their logic [here](https://docs.google.com/spreadsheets/d/1r-DpQuFhtBcD-YEel_ma2TwxC92fBdwEissclXWOv8c/edit?usp=sharing)

**Comment by vschandramouli** [comment]
Mapped the Info type freeform options to the ones that insert fees. The document exists [here](https://cityofaustin-my.sharepoint.com/:x:/g/personal/ex-vishwa_chandramouli_austintexas_gov/EWlvgtLUXadClx04hLWT_DMBgBvrUMW834KgQ4DHShbHog?e=ihM806)

**Comment by vschandramouli** [comment]
@SubhaShroff  Could you review this document and the comments added to the spreadsheet once. We can go over it together if you have more questions.

**Comment by vschandramouli** [comment]
Response from LaTonya on how system identifies Traffic Lanes as 1st, 2nd or additional : 

In the Property & Street Information tab, the 'Number of # ' is where the user indicates if a traffic lane is 1st 2nd or additional.

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader  @vschandramouli  After removing the conditions of old work types for TURP RW and trying different combinations of the existing lookup table mapping in the code, only fee set up that I could match is 'TURP Sidewalk/Behind Curb Space' fees with the excel fee calculations. The other fees must have changed its not the same as in Excel.
I will update the existing code logic shortly. We may have to create new lookup records and rewrite the new code.

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader  @vschandramouli Finally I could Trace the calculations. Please verify the attached excel sheet.
Compared it with the excel sheet that we got from stakeholders. The user provided fee calculations(unit fee) match the Extension fees(2nd worksheet the list starts from 43rd row).
[Existing old code ROW fees Calculations.xlsx](https://github.com/cityofaustin/atd-data-tech/files/8092317/Existing.old.code.ROW.fees.Calculations.xlsx)
Please verify. And let me know for further proceedings.

**Comment by SubhaShroff** [comment]
### Status:
Currently working on the fee calculations procedure based on the above mentioned inputs from Tracy and stakeholders on Friday's 2pm call.

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder @vschandramouli This is done and the demo is sent to you all, yesterday.  And the code is committed .Waiting for the feedback.

**Comment by Nadin-Nader** [comment]
@SubhaShroff the demo looks good. lets go ahead and get this going

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  For Unmetered, on Property street tab, which one should be chosen? 'Closure : Unmetered Parking' or 'Parking Spaces : # Unmetered Spaces'

**Comment by TracyLinder** [comment]
@SubhaShroff great question. 

**Answer:** Chose ''Closure : Unmetered Parking'



> @Nadin-Nader @TracyLinder For Unmetered, on Property street tab, which one should be chosen? 'Closure : Unmetered Parking' or 'Parking Spaces : # Unmetered Spaces'? (In the demo, i have chosen 'Closure : Unmetered Parking'. I chose this based on the entry already in lookup table for Unmetered Parking)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0202531 is requested for DEV deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Tested the deployment and I had missed to commit couple of objects. So did another commit today and  submitted DEV deployment request(SCTASK0204192)  for the new commit-"8ba184481483".

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This is now in DEV and I tested it. Ready to be deployed in TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0204632 is submitted for TEST deployment of this ticket.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This ticket is tested on TEST and ready for UAT.

**Comment by SubhaShroff** [comment]
UAT is done. As per Paloma feedback:
For '50313 - TURP Unmetered Parking Lane fee' The info on Property & Street information tab - 'Parking Lane : Dimensions' should be considered.
I will get work on that.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0205979 is submitted for DEV Deployment of the above mentioned fix.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  DEV deployment is done. I tested it in DEV for unmetered parking lane fees. It works as expected. Please let me know if I can submit TEST deployment for this.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  SCTASK0206205 is submitted for TEST deployment of unmetered parking lane fees fix.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder SCTASK0207009 is submitted for PROD deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  this is promoted to PROD.

**Comment by SubhaShroff** [comment]
### Status:
PROD promoted 2 days ago.

**Comment by TracyLinder** [comment]
**Status:** Nate requested stakeholder verification of PROD completion on Monday 3/21. Pending stakeholder verification feedback.

**Comment by Nadin-Nader** [comment]
Closing Card as the only issues with this was the fact that the Usage fees needed some to have a comment showing what the fee is for. This is on card #8795
