### ISSUE TITLE
Replace "Current status" filter in advanced search with project badge values

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7831]
Remove "Currrent [sic] phase" and "Current status" from advanced search and replace with "Status" to search projects' badges...

![Screen Shot 2021-12-29 at 4 02 37 PM](https://user-images.githubusercontent.com/1463708/147706827-f19d6731-617b-4882-a945-06fb477ec514.png)

Related #7832 ...

**Comment by zappfyllc** [comment]
I am very open to searching by the badge since that's what we display to the user, but we should get feedback from stakeholders on whether they want to display both the phase and status in the table for searching against all projects before we implement this. If they want both the phase and status in that table, then the status badge may actually be confusing in that situation since it's a hybrid of the two. Technically you can easily retrieve both the status and current phase of a project with GraphQL without any business logic so it is a bit more straightforward to include both columns.

**Comment by amenity** [comment]
Discussed with @zappfyllc and @johnclary earlier and we decided that the use cases where users would want to use both columns (e.g. analyzing what phases projects tend to be in when they are put on hold) are outliers.

I wanted to circle back, though, because by doing this and #7827, we're essentially re/mis-defining project "Status" for our users. "Status" will be the values they see in badges. I was adamant that phase and status should operate independently from a data model perspective, but simplifying the user view of things feels like it's improving usability. 

Is blurring that distinction for our users a bad idea?

**Comment by zappfyllc** [comment]
@amenity I hear you but after our conversation, I strongly believe your suggestion is the way to go. Our best guess at the requirements upfront based on initial user feedback via requirements elicitation, including the Phase/Status/Milestone activity and subsequent conversations you led, provided a somewhat blurry answer in terms of how those two entities (phase and status) were used/tracked and there wasn't quick, unanimous consensus. I'd argue that, if anything, we're actually clearing up a situation that is already blurry with the status badge and how it displays.

I definitely vote we move forward with what you suggested in this issue and #7827 in terms of using the logic from the badges in the overall project listing/search and call that status for the sake of simplicity to the end user (as you mentioned already). It's very possible that we won't know the fallout from our decision until Moped v2.0 and we also don't know how the phases are going to go over with users yet, so maybe we end up with a completely different mechanism for tracking that information which ultimately impacts the status badge.

We could've had two badges, one showing the status and one showing the phase, but I think our logic makes sense and gives a concise description of the state of the project (if we want to avoid saying status, we could call it the project state? but I'm fine with status personally) while subtly encouraging users to fully fill out the Timeline tab if they want more descriptive information to show up in the status. Your suggestion that maybe we just have pre-filtered views for the unique status options ("Canceled" and "On hold") was a great one, and I think we can tackle that problem when we come to it with users requesting a subset of projects that might need both status and phase information. That information is still available in the database so it's not like we've done anything that's irreversible and it should be easy to implement.

**Comment by amenity** [comment]
Sounds good, thanks for the consideration, @zappfyllc !

**Comment by amenity** [comment]
@chiaberry - on the heels of #7827, care to venture an estimate on this?

**Comment by chiaberry** [comment]
I am thinking a 3. I am hoping that the logic can all happen on moped (and we wouldnt have to change atd-kickstand) but I am not 100% sure

**Comment by amenity** [comment]
Update view to add column that represents status badge.

**Comment by sergiogcx** [comment]
It turned out to be a 2, finished at around one-two hours. There is a PR:
https://github.com/cityofaustin/atd-moped/pull/514
