### ISSUE TITLE
Enable users to see canceled projects

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7832]
One idea:
![Screen Shot 2021-11-30 at 6.16.23 AM.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/ffc7bcd7-6d42-4783-816a-6fd645d79860)

Takes users to a list of canceled projects at `/projects/canceled`

**Comment by amenity** [comment]
FWIW, @chiaberry - the "Canceled projects are not shown." text actually probably belongs in the "No search results" verbiage instead of the way I have it mocked up here. 

Reminding myself, @amenity, to update the mockup once you've completed #7402 .

**Comment by chiaberry** [comment]
@amenity , what do you want it to say for no results when searching Staff? 

zero results projects page: "Canceled projects are not shown."
zero results staff page: ?

**Comment by amenity** [comment]
@chiaberry - Updated wording [here](https://github.com/cityofaustin/atd-data-tech/issues/7402#issue-1021471461).

**Comment by johnclary** [comment]
We fixed this as part of https://github.com/cityofaustin/atd-data-tech/issues/7910 - there's a relevant review comment here: https://github.com/cityofaustin/atd-moped/pull/872#discussion_r1020777759
