### ISSUE TITLE
Update Manchaca to Menchaca on Critical Arterials Layer

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#7849]
Jeffrey in HPD requested that Manchaca be updated to reflect the new spelling of Menchaca on the Criticals Arterials layer in GISDM.

Need to update the following fields in MAINT, then update on GISDM:
- ROADWAY
- SEGMENT_LIMITS
- FULL_STREET_NAME

New Project already created in:
G:\ATD\ATD_GIS\Arterial_Management\49_Identify_Critical_Arterials\Critical_Arterials_Project

**Comment by johnclary** [comment]
@alan-deanda please also check AGOL for this layer

**Comment by alan-deanda** [comment]
Dec 6 push to AGOL did not include new updates, so I submitted a ticket for a manual push

**Comment by jaime-mckeown** [comment]
- I didn't see a task in Geodatapusher for Critical Arterials, so I created a new task and updated the layer on GISDM.
- Responded to RoxAnne's email regarding Alan's Service-Now request that I manually updated to GISDM, and asked if the GTM group could push to AGOL.

**Comment by jaime-mckeown** [comment]
Request was transferred to the GTM group and layer was updated in AGOL.
