### ISSUE TITLE
IT Support: Assist with SMB Hardware Testing and recommendations

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7850]
Susanne G
SMB

Emailed/Invited 11/30
>Start discussion of how to get possible test tablets. Also, we’d like to get a few options to do comparisons

### Possible options: 
- iPad (apple)
- Samsung tablet (android) upgraded version
- Surface Pro (Windows)
- Lenovo Chromebook
- Any CTM recommended tablet

### Testing:
-	Time to load websites
-	Accessory attachments (keyboard, weatherproof casing, pens(?))
-	Photo/Camera quality
-	File storage size
-	Intuitive UI (how easy is it for the user to select apps)
-	Viewing PDFs
-	Battery Life
-	SSD

**Comment by dianamartin** [comment]
Emailed the CTM contacts provided by Danny - 12/6
>I got your information from Danny C. He’s my contact I work with for AirWatch and I had asked him who would I could contact about testing hardware. I have some stakeholder looking to upgrade their tablet devices, we currently have Samsung Tab A. They were wanting to test other hardware devices out and I was told there might be a way to test some devices prior to us deciding on one and ordering. 

>The ATD IT hardware contact is Scott, who is cc’d. He regularly works with your team to get IT purchases from the Wireless shop. Let me know how we should go about this. Should I have the stakeholders submit a ServiceNow ticket, have Scott put in a request or get on a quick phone call with the my stakeholder point of contact for the devices?

**Comment by dianamartin** [comment]
Scott replied to me 12/7
>Vendors typically don’t send over hardware any more for testing. Don’t know if that is a city policy or vendor policy. 
>- They did provide testing equipment before about 7 years ago

I replied
>Well I’m going based off what Danny said, so maybe he’s not in the loop on that anymore. We’ll see that Wireless says?

**Comment by amenity** [comment]
@dianamartin - please follow up with CTM (again)...

**Comment by dianamartin** [comment]
Followed up from by 12/6 email

Emailed Shannon/Kimberly - 12/15
Cc'd Anthony M, Danny C. 

>I’m following up on this email because I’d like to get to the stakeholders to let them know whether CTM still allows stakeholders to borrow devices. If not, then we’ll have to figure something else out. 
>- Any response is greatly appreciated.

**Comment by dianamartin** [comment]
I said on 12/15
>I’ve cc’d our stakeholder division contact that can expand on the brand/models they’re looking into testing. 

I followed up on 12/17
>I found the list of hardware devices the Signs and Markings Division were interested in testing out. 
>- iPad (apple)
>- Samsung tablet (android) upgraded version
>- Surface Pro (Windows)
>- Lenovo Chromebook
>- Any CTM recommended tablet

**Comment by dianamartin** [comment]
Anthony replied 12/17
>Unfortunately we do not keep devices like this stocked. 
>- I recommend submitting a Request for Quote for an IT Purchase or a Request for an IT Purchase with Quote. 

I replied 12/17
>We’ll figure out a way to test what we need and submit an IT Purchase Request when we’re ready to purchase new devices.

**Comment by amenity** [comment]
SMB needs to have internal discussions on how they would like to move forward. 

We also want to see if updating the Airflow profile might improve performance.
