### ISSUE TITLE
[Enhancement] Standardize edit-in-place and hyperlink UIs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7870]
Right now, we have several types of edit in place happening:

![Two edit-in-places UIs.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/e78d9d6c-1827-4a13-9da8-c0462178ee34)
1. Standardize patterns between project "Summary" tab and "Signals projects" dashboard. 
-  Edit-in-place, empty
-  Edit-in-place, filled
-  Edit on another page, empty 
-  Edit on another page, filled / Internal hyperlink
- External hyperlink

![Two edit-in-places UIs copy.png](https://images.zenhubusercontent.com/5a5f8dc94b5806bc2bc322a5/cd6b5796-0218-4f19-8f64-f12c32d8a5a6)

### Proposed solution
- [x] Replace pencil on "Summary" tab with a dashed underline like Material Table provides 
![Screen Shot 2021-12-08 at 3 51 24 PM](https://user-images.githubusercontent.com/1463708/145290429-5e746792-6ede-41c1-aea7-6000c5d8a327.png)

- [ ] Display all blank values on signals dashboard as `—` with either the edit in place or hyperlink styles
- [ ] Take edit-row pencils off of signals dashboard

Note: We will leave the "Add new status update" button/icon without the pencil. It just needs a tooltip #7320 .

**Comment by amenity** [comment]
@zappfyllc @johnclary @patrickm02L I’ve got this marked as Moped 1.0 because, while I know we could stumble along as is, I think we can’t fairly evaluate the usability of current patterns when they’re in competition... But if it turns out to be a heavy lift, it's definitely not a must-have.

**Comment by patrickm02L** [comment]
I think there's some value to standardizing the interactions in 1.0. Also think that the Signals project table could use some sprucing up from an aesthetic standpoint.

**Comment by amenity** [comment]
@chiaberry will you size the "proposed solution" up there? cc/ @johnclary @patrickm02L

**Comment by chiaberry** [comment]
So there isn't a way for users to edit by an entire row on the signals dashboard after this issue is completed right? I ask because there is code written to handle the row updates, and if we don't need it, I can remove the code along with the pencil.

**Comment by amenity** [comment]
@chiaberry - I'd vote for no... 
- The pencil isn't always going to be visible because the table is ultra-wide
- Not all the data in the row will be editable, since it comes from other places

When it comes to the other instances of Material Table, I think the "edit row" UI will actually come in handy when we look into features like #6409.

**Comment by amenity** [comment]
@chiaberry - I snuck those external link icons in here after all. 🙈  Maybe a PR for the signals dashboard parts and a PR for the "Summary" page parts makes sense, though...
