### ISSUE TITLE
Enhancement: Banner Permits in Knack Embedded Map

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7872]
Embed map for Banner locations

**Comment by dianamartin** [comment]
Looked into this task and have thought about what needs to be done for it. 

Options 1: try the JS code embed

**Comment by dianamartin** [comment]
I used the iframe code from the Drupal sight where we currently have the LPB map embedded and used it in Knack, it worked well. 
LPB
![image](https://user-images.githubusercontent.com/21112975/144505591-7945586a-5ac1-4a1a-bc31-be2588872e0b.png)



OTS
![image](https://user-images.githubusercontent.com/21112975/144505399-731bc63d-248c-425c-8216-5f4d59d41088.png)

**Comment by moorerst** [comment]
Will review with stakeholders in Sprint Review scheduled 12/9

**Comment by dianamartin** [comment]
Sync'd with Christina (12/2) so she could have a preview, we worked out some layout options. 

# LPB 
![image](https://user-images.githubusercontent.com/21112975/145252872-e0b73338-90b5-43c9-86d8-1b82cceca399.png)

# OTS
![image](https://user-images.githubusercontent.com/21112975/145252943-664bdd02-fb47-4988-93a0-27db1e93b806.png)

**Comment by moorerst** [comment]
Stakeholder agreed with map Closing issue

**Comment by dianamartin** [comment]
Worked on better LPB embed map to incorporate the table (from application) and overview map. 
# Before
![image](https://user-images.githubusercontent.com/21112975/147509405-91facbbc-8ee9-4a13-996e-6793f2b24475.png)

# After
![image](https://user-images.githubusercontent.com/21112975/147509724-78756f5b-3a65-4e4e-9757-ecfd47fb47c4.png)
