### ISSUE TITLE
[Feature] Vision Zero Intervention Tracking

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7878]
We want to add a map of [Vision Zero](https://www.austintexas.gov/department/vision-zero)-related infrastructure projects/interventions to [Vision Zero Viewer](https://visionzero.austin.gov/viewer/), a la [vzv.nyc](http://vzv.nyc/). 

How might we filter down to all of these projects in Moped? 
- Manually-managed "Vision Zero" tag?
- All projects in certain project types, programs, or funding?
- The asset types themselves, e.g. trail, bike path - in combination w/ their delivery dates

**Comment by patrickm02L** [comment]
Considering this part of the larger Moped mapping effort we're working on. It's possible to revisit this Issue if we decide to integrate an interventions map in VZ. I don't foresee any movement on this front in the near future.
