### ISSUE TITLE
Reporting: Contacts per hour

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#788]
Contacts per hour:  Ratio of number of contacts (warnings+citations) to number of hours worked

**Comment by SurbhiBakshi** [comment]
emailed RDavila and LLewis to check if the shift is always 6/8 hours or does the shift duration change, in which case I will need to set up a process to calculate it.

**Comment by SurbhiBakshi** [comment]
- [ ] Need help with terminology for violations by hour.

![Screen Shot 2019-11-22 at 2.19.41 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/503dbcdc-2948-4cba-b647-481e964e1a5a)

**Comment by SurbhiBakshi** [comment]
[ ] Is there an easy way to restrict records to current year? the Filter for current year doesn't seem to work. Need to check again. ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/a07395da-aedf-4f2c-a43f-bffcab1ddef8)
