### ISSUE TITLE
SMO Sprint Review 12/3/21

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7886]
Issue to address that came up in the [12/3/21 Sprint Review](https://docs.google.com/document/d/1jQUfx5jdlKnI65i9CUv_TYDr9Vd2CR91eIT7i7wEVSw/edit#).

### Things to do 
- [x] Auto update "Issue Date" when adding employee - DONE on 12/3
- [x] Update naming of Bikeshare Benefit to be MetroBike Employee Benefit 
  - [x] Updated Home page - need to update JS
  - New Form Title
  - MetroBike Employee Benefits - main table
- [x] Create Reporting page for analytics
- Totals
- Comparing Previous Years
- Number of Employee by Department 
- Renewing and New
- [x] Update Application status states
_need to Test next week_

**Comment by dianamartin** [comment]
@patrickm02L This is ready for your review, let me know if you want to sync on it

**Comment by dianamartin** [comment]
## Reports Page
![image](https://user-images.githubusercontent.com/21112975/145062473-e6c89f7d-da69-43b5-8e62-76a1c873939b.png)

## Drop down menu list
![image](https://user-images.githubusercontent.com/21112975/145062581-b5348b7d-1ab7-493d-a985-d4c3b2ca3c5f.png)

## Update Naming 
### Home Page
![image](https://user-images.githubusercontent.com/21112975/145062654-f63ef64a-f643-4f9f-b806-b7d1a1943ad3.png)

### Bike Benefit Application - Main Page
![image](https://user-images.githubusercontent.com/21112975/145065048-fdb5690c-5b8f-4abd-bb91-6be24634f844.png)

**Comment by patrickm02L** [comment]
@dianamartin Thanks for making the updates. 

I spent some time going through what happens when a new application is added, and found the adding codes task to be a little puzzling. This may be a training thing, but it makes me realize we need to do some user testing with Eliza Y. to make sure she's familiar with the workflow. 

From a design standpoint. Can you left align the Total Number of Applications table?

![Screen Shot 2021-12-09 at 10.56.20 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/b5b094d2-b7a0-4d78-8466-5dee4162bf48)

**Comment by dianamartin** [comment]
@patrickm02L Yes, I think we need to do user testing with her to make sure the process we have set up works for her. 
The reports can't be aligned like that, To improve it, I can make the other bar chart move into the spot the pivot table was and leave the pivot table on the bottom right corner. Let me know if you want me to rearrange it.

**Comment by patrickm02L** [comment]
@dianamartin we can leave it.
