### ISSUE TITLE
Set up Gitbook documentation

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#7887]
Create a new parking data gitbook.

Things to include:
- Links to socrata datasets
- Database schema
- Field metadata
- Cool stuff like [this](https://github.com/cityofaustin/atd-data-tech/issues/6925#issuecomment-978285153)

**Comment by johnclary** [comment]
@Charlie-Henry create a new ATD Parking gitbook for this

**Comment by johnclary** [comment]
[Charlie's work in progress.](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/mIbPlhSICnKK9WwKFJLl/)

**Comment by johnclary** [comment]
@Charlie-Henry please add your list of todos here

**Comment by patrickm02L** [comment]
@johnclary we're closing this Issue but if you have any feedback please feel free to chime in.
