### ISSUE TITLE
Reporting: Average contacts per hour by a given officer

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#789]
Average contacts (warnings+citations) per hour for a given officer

**Comment by SurbhiBakshi** [comment]
[ ] Using Created By populates Table Rows in the pivot, but not Officer Assignment / Officer connections. Not sure why?
 ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/487f5824-c757-4e5f-95fa-e40b7e63c0ef)
