### ISSUE TITLE
Provide access to RPP in Knack

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7899]
Can we please get the following employees added to Knack:

Courtney  (If access hasn’t already been given)
Dan R

Same access as John L

**Comment by ChrispinP** [comment]
Courtney has existing access to RPP. Dan added to RPP.

Complete

**Comment by moorerst** [comment]
confirmed both users have access to RPP:
Just checked and looks like both do have working access. Thanks for your help with this!

Closing issue
