### ISSUE TITLE
Create Awards and Recognition Nomination form in Knack

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#79]
[PDF form](https://drive.google.com/file/d/1P-jFfFvdVzBVmwExbALaC94odfyg1jCq/view?usp=sharing)

**Comment by amenity** [comment]
Here's the digitized form: https://atd.knack.com/atd-forms#nominate-an-atd-employee/

@johnclary @dianamartin — anything I should modify?

**Comment by dianamartin** [comment]
@amenity I went to the back end and saw that you just had a form. I would suggest that you add a "Rich Text" then add all the program description stuff. 
![image](https://user-images.githubusercontent.com/21112975/57257389-e3853b00-701e-11e9-8098-eaccaec02e84.png)

You can ask me tomorrow if you need any help.

**Comment by johnclary** [comment]
Looks great! Minor suggestion that you add more helpful text after you submit the form. E.g., "Thanks, someone will be in touch soon blah blah."

**Comment by amenity** [comment]
@dianamartin - Ah cool! I hadn't seen the rich text. 

Do we usually start a form with a rich text block as opposed to just the form element? In this case, since I don't have links or need any special formatting, there isn't much of a difference between the plain text and rich text:

<img width="1019" alt="Screen Shot 2019-05-06 at 9 06 54 PM" src="https://user-images.githubusercontent.com/1463708/57266901-b0a16e00-7043-11e9-86ba-204ef1a823b1.png">

**Comment by dianamartin** [comment]
@amenity the "Rich Text" block allows for more formatting of the first paragraph, the way you have it now is kind of limiting.

**Comment by amenity** [comment]
@dianamartin - For sure. Is there any additional formatting you would recommend in the first paragraph though? In my eyes it only needs basic paragraph text. 

Weirdly, the non-rich-text paragraph text style is a little more legible since it's larger — matches the size of the form fields.🙃
