### ISSUE TITLE
Enhancement: New Issue Type Parking Meters SR's

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7901]
Requested by Parking Meter stakeholder: 
Can we add Meter Malfunctions to our Issue Type list

**Comment by moorerst** [comment]
Communicate between Diana and David regarding new category:
I know that Parking Meters already has a 311 SR for “Parking Machine Issue”. These seems like this may be more of a training issue that we’d have to work with the Parking Enforcement group with. Are you still receiving a fair number of those SR types (machine malfunction)? **I think we have received 3 so far.**

We had said to have the Parking Enforcement office direct any customer to submit a 311 system so that their contact information would be captured and so that you’d get those through 311. Is that still what you want the Enforcement group to continue doing? **I think we may want to do both. If an officer encounters a citizen with a machine issue, I am okay with them letting us know of the issue either by radio or a work order. They can continue to direct the citizen to 311 as well. I just want us to be as responsive as we can to supply the best customer service that we can to both the officer and the citizen** I think if you are getting a large number of SRs that are for malfunction then we should consider adding a new category, but since we’re still in our first week I’d suggest to wait to add that new category. **Agreed.**

Going to put this issue in the Backlog to review/evaluate later, after they have been using the system a while.

**Comment by dianamartin** [comment]
I got email from Shavyvonne this morning 12/9
>Did I need to submit a ticket for adding a new parking meter issue type “Meter-Parking Machine Issues”

I replied
>I’m working on this issue this morning. The new issue type will be called: Meters – Parking Meter Issue. I didn’t want the name to match so closely to the 311 SR name “Parking Machine Issues”, so we can distinguish them differently in the future. I’ll let you know when I’ve completed the change.

- [x] Added new choice field for `ISSUE_TYPE_MANUAL_CREATE`
- `Meters - Parking Meter Issues`
- [x] Added new choice field for `PEO SR ISSUE CHOICES`
- `Meters - Parking Meter Issues`
- [x] Created new PM SR, tested and saw on the Main Service Requests page for PM

![image](https://user-images.githubusercontent.com/21112975/145436706-ce5881f6-5c34-4092-8627-e1568d506dad.png)

Emailed stakeholders
>A new issue type was added “Meters – Parking Meter Issues”. I just created a test SR and it shows up correctly in your Service Requests | Parking Meter table. (inserted screen shot) Let me know if you require any additional changes.

**Comment by moorerst** [comment]
Confirmation from stakeholder: 
Thanks Diana…… I will update the officers and Dispatchers.
