### ISSUE TITLE
[Bug] Not able to edit or add users

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7908]
Lewis L. brought up in the December Sprint Meeting that he was not able to edit or add users even though he has IT Supervisor permission. 

@mateo is triaging and will add further details about how to resolve. 

![Screen Shot 2021-12-07 at 1.15.00 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/a65e6870-eb5e-43e3-86ae-c2288dfe16bd)

**Comment by mateoclarke** [comment]
@patrickm02L, I'm stumped on this one. Lewis appears to have all the same permissions as my account. I've emailed Lewis asking him for some more info found on the `visionzero.austin.gov/editor/#/profile` page that might help me troubleshoot further.

**Comment by patrickm02L** [comment]
Brought it up in 2 previous VZ Sprint Meeting. Lewis said it was a low priority. Iceboxing.

**Comment by mddilley** [comment]
Rose E. reported this same issue in the user detail view and shared this screenshot below. So, we now know that it affects two user roles: Admin and IT Supervisor.

If this is prioritized again, a good start would be to have an affected user attempt to load this view and then look at the CloudWatch logs for the VZ API Lambda and see what error we are encountering on the backend. Also, checking for any updates to the [Auth0 Management API](https://auth0.com/docs/manage-users/user-accounts/manage-users-using-the-management-api) could help to see what is up. There aren't any obvious differences in the user metadata that returns in the user list view for the affected users when compared to unaffected users.

![image](https://user-images.githubusercontent.com/37249039/195393160-71e87054-cb9b-4d5a-9697-f8a6670ccbb0.png)

**Comment by patrickm02L** [comment]
Thanks for bringing this up. I'll pull it into the backlog, so we can start to consider it again.

**Comment by patrickm02L** [comment]
10/26/22. In grooming Mike's reviewed notes with where to start the discovery around Cloudwatch and auth0. 

Rose will add a screen recording of her trying to login for future investigation.

**Comment by roseeichelmann** [comment]
Here is what happens when I try to click on a user. This is staging, the same thing happens in production.

[Screencast from 10-26-2022 04:07:48 PM.webm](https://user-images.githubusercontent.com/67130963/198138760-728f7f05-3aba-4c4a-8c72-6f4a8b661c38.webm)

**Comment by roseeichelmann** [comment]
This is what happens when I click on a user, it just loads forever. For some reason this video freezes and the loading wheel stops moving but irl the wheel is moving. This is staging, the same thing happens in production.

[Screencast from 10-26-2022 04:11:42 PM.webm](https://user-images.githubusercontent.com/67130963/198139152-c4f3a60f-e75f-4e85-9cc1-22388f04abe0.webm)

**Comment by patrickm02L** [comment]
## 10/09/23

An Admin can add, delete and edit users. JC is the only IT supervisor listed as of now. 

For practicality sake, those who was this ability can be changed to Admins.

**Comment by mddilley** [comment]
@patrickm02L I was just able to reproduce this bug with admin role when using Firefox. I added a note to the v1.38.0 VZE test script but wanted to note here too. Looks like it could be browser-related issue since @roseeichelmann was probably using Firefox when making the screencap above?
