### ISSUE TITLE
(Duplicate) Bug - EX Date Extension Features need to NOT update the Extension Date when the Extension is Approved

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#7909]
### This was merged into #7631. It's now a duplicate.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Just fyi Subha will be out the starting the 18 or 19 so this will have to be ready for PROD by the 17th

**Comment by TracyLinder** [comment]
### Previous Issue Description: 

If the EX work types are Franchise, ATD, Austin Energy, Austin Water, Corridor Program Office, Public Works, Watershed Protection when user Grants Extension:

Stakeholder: Kim and Paloma

Acceptance Criteria:
1. User saves "Extension Granted" Attempt
2. System should **NOT** update the Issue date with the Extension If the issuedate is already there
3. System updates **folder infos** extension start date and extension end date
4. System updates folder status to Active and folder expiration date to info extension end date
5. If there is no issue date & its a first time issue, it should write the issue date.

Note: Kim & Paloma just told her that they never want the issue date to change w/ the extension process on both EX & RW.

**Comment by TracyLinder** [comment]
This has been merged into #7631. I am closing it.
