### ISSUE TITLE
Info Field Changes to RW Parking folders (On PROD🎉🎉)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#7911]
**Acceptance Criteria (Applies only to RW - Parking folders):**

- Info field 'Number of after hours of service' (Info code 75947) should be removed from any RW folder (Currently exists, needs to be removed)
- Users should be able to see a new info field 'Rate if metered (in $ per parking meter)' (No infocode exists, needs to be added) in RW folders of subtype Parking Spaces and worktype Load/Unload

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - In progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted DEV DP; kindly approve and create task id for me.

Commit ID:  7d525e914be7

**Comment by TracyLinder** [comment]
This is in TEST

**Comment by TracyLinder** [comment]
@vschandramouli will setup UAT sesh with Jonathan W. End-to-end testing needed.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Today while testing another card, I found that RW-temp the new info  is appearing. Looks like I missed adding it in the infoexclusion for RW-temp. Sending another commit. Here is the commit ID: a7355654f29d. DEV DP submitted aswell.

**Comment by vschandramouli** [comment]
Scheduled UAT with Jonathan W for 2/24 at 12PM

**Comment by vschandramouli** [comment]
Completed UAT with Jonathan. Sree will be sending out a new commit with changes restricting the info to only Load/Unload work type.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder - As per the UAT Meeting today on #7911 added other work types also to the infoexclusion table and committed the changes. Please approve and create task id for me.

Here is the commit id: [dd8a3838887c](http://coaamandadevops01.austintexas.gov/R3:dd8a3838887c80e1e63b6115771f5e626254af78)

**Comment by Nadin-Nader** [comment]
Sent new commit to be deployed to **_DEV_** under **SCTASK0202513**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested, Working as expected. TEST DP Submitted. here are the commit id's: 
1.	a7355654f29d
2.	dd8a3838887c

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @Nadin-Nader the new info is showing on TURP again.

**Comment by Nadin-Nader** [comment]
New Changes to TEST under **SCTASK0203632**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST and ready to move to PROD as this will fix another bug. submitted PROD DP, please approve and create taask id for your reference. Here is the order. This bug is because its one commit is already moved to PROD which causes the bug. 

Commit ORDER
1.	Order 1 - 7d525e914be7 – Moved to PROD already
2.	Order 2 - a7355654f29d 
3.	Order 3 - dd8a3838887c

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder This has been sent to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0204228**

**Comment by Nadin-Nader** [comment]
Sent email to Paloma and Isabel informing them that this is on PROD and to please UAT. I will close Friday unless i am told all is well.

> Good Morning,
> Hope you are all doing well. I was reaching out to inform you that card 7911 Info Field Changes to RW Parking folders is now on PROD.
> 
> Please UAT and let me know if the changes are working and look as expected. I will keep the card open til Friday unless I am given the go ahead to close.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> Product Delivery Manager
>

**Comment by Nadin-Nader** [comment]
This has been delivered on PROD and new changes are going on #7912. Closing this card
