### ISSUE TITLE
[BUG] `reimbursement_tracking` object - missing `signs_work_order` connections

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#7913]
**Describe the bug**
When updating the `rembursement_tracking` object, deleted conditional rule attached on markings work order connection and signs work order connection. Marking connection stayed in place, signs connections disappeared. 

## SMB Tracker - Prod
- Total Records: `839`
- Markings Connections: `365`
- Records w/o Connections: `474`

## SMB Tracker - Test 
`TEST | SMB - 29 JUN 2021 | Signs and Markings Operations`
- Total Records: `645`
- Markings Connections: `253`
- Records w/ Signs Connections - `351`

**Comment by dianamartin** [comment]
Submitted a ticket to Knack on 12/6

They replied
>The most recent restore would be yesterday, 12/5/21. We could restore your entire app to that point but any changes made after the restore point would be lost.
﻿
﻿Knack automatically backs up your application on a daily basis. However, the backups are not currently readily available to our users. It requires manual labor by our team in order to restore from a previous backup. Backup restores are included in our Corporate plans and above.
Restore requests are scheduled in the order that they are received and your restore may not begin the day it is requested. Once the restore has begun, depending on the complexity of the restore, it generally takes 1-3 hours to restore from a recent backup. In total, the turnaround time for a restore can take 3-5 days.
Is this something you would like to consider?

i replied with
>That sounds great! Yes please. - 3:37 pm
>- So, to confirm.. I want a copy of the backup. I don't want the current app to be restored to 12/5.
>- I want to make sure before you begin, if that's possible

Knack replied
>﻿I'm sorry. We're not able to make a copy of the backup to a new app on the account. The way the restores work is that they'll overwrite the existing copy. Do you still want that?

i said
>The issue is we can't override the existing app because we have field technicians entering information in daily. We'd lose all that date. I just need a table from the backup copied if at all possible. I see the connection value i the audit log but it's for 474 records. (I included a screen shot of the audit log, to see if they could revert the action) 
![image](https://user-images.githubusercontent.com/21112975/145244209-3b9e9bfd-b4cf-482a-b0f2-be1a4150d8fd.png)
Is it possible to undo this action "Field Index action"..

Knack replied
>Thank you for that. We were able to revert that action but we can't guarantee it will have brought everything back. Please give it a check in ten or fifteen minutes and let us know.

I replied (later that evening)
>Looks like the table still doesn't have the connections. Not sure if that action was in fact reversed, doesn't appear to be.

**Comment by dianamartin** [comment]
I just followed up - 12/8 (on 12/7, there was an AWS disturbance and caused services to go offline)
>since some of the internet went down bc of that AWS server..I'm sure y'all have been putting out fires since yesterday. Just checking back in to say the revision didn't seem to work.

**Comment by dianamartin** [comment]
Knack said 12/8
>﻿Thanks for being understanding about that outage setting us back a bit. Since that revision didn't work we're going to try exporting that object from your backup into a csv file that we can then share with you so you'll have that data. Can you confirm the object we'll need that for?

I provided the object `188`

I messaged 12/9
>Did this work?

Knack replied 
>The request is still with our engineers. Restores are performed in the order they came in, so there may be a bit of a lag.
 
I said
>Gotcha, thanks! Stakeholders were checking in, so i followed up.

**Comment by dianamartin** [comment]
Knack sent message - 12/13
>This has been completed and we've shared a CSV with you with the object you were looking for in it.﻿ Please let us know if you need anything else. 
>- We've uploaded the object that you were asking about. We'll leave this up for 3 days for you to download and make a copy of. We've uploaded the object that you were asking about. We'll leave this up for 3 days for you to download and make a copy of. 
﻿
- [x] I downloaded .csv file and renamed to: `Knack_recovery_5d13ae5b438091000ac0197d_object_188`

**Comment by dianamartin** [comment]
John pointed me to the [OpenData dataset](https://data.austintexas.gov/Transportation-and-Mobility/Street-Sign-Work-Orders/ivss-na93) which has the Knack Record IDs. 
- [x] Exported sign work order table w/ IDs
- [x] Cleaned up table, re-saved to new .csv
- [x] Cleaned up `Knack_recovery_5d13ae5b438091000ac0197d_object_188` table to only have the "RT ID" and the "work_order_signs" and "work_order_marking" fields
- [x] Created field "Knack OID" on signs work order table
- [x] Created back up for signs work order table
- [x] Imported the sign work order table w/ IDs (5 records)
- [x] Spot checked
- [x] Imported the sign work order table w/ IDs (19417 records)

**Comment by dianamartin** [comment]
I spot checked this morning an it looked like there were some reimbursement tracking records that were associated to a work order multiple times. Ran a filter for `work order signs` is NOT blank AND `work order markings` is NOT blank: `145`. I checked the back end to see if the audit log showed the signs WO or only the marking WO. In 6 occasions there were duplicated the same exact way. I was pretty sure those were the mistakes bc the other records were stand alone.

**Comment by dianamartin** [comment]
Sync'ing with Christina in the morning 12/15

**Comment by dianamartin** [comment]
Christina and I found a handful of records that still have a duplicate reimbursement tracking. We exported the Sign Reimbursement table in the "Closed" status and added 2 temporary fields: RT ID and Bond to do a visible check on the data. She's going to double check those and get them back to me to delete the connections and add the Work Order that it was disassociated from.

**Comment by dianamartin** [comment]
On 1/3/22 Christina and I sync'd to change the reimbursements 
- [x] SGN21-086675, was associated to RT_ID - 412, 712. Disassociated 412
- [ ]

**Comment by amenity** [comment]
@dianamartin - does this need anything else to be closed?

**Comment by dianamartin** [comment]
@amenity I can ask Christina if there were any more that's had to be corrected. There were a couple that she still had to look into.

**Comment by amenity** [comment]
Christina confirmed that other apparent disassociations were from a previous process and has manually cleaned this up. 

Opening #8126 since the table was modified during the data restore by Knack
