### ISSUE TITLE
Import South Area TIA Cases

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7922]
Joan emailed the list this morning. Will attach soon. 
[TIA Historical Template for Stakeholder South_JM.xlsx](https://github.com/cityofaustin/atd-data-tech/files/7830546/TIA.Historical.Template.for.Stakeholder.South_JM.xlsx)

**Comment by ChrispinP** [comment]
I have completed my preliminary spreadsheet prep for the South area import of Cases, Scopes, & Submissions. These files are saved in the TIA folder on the G drive.

Some field/object prep is needed:

- [ ] Decouple the Case Type / Case # automation

TIA_request object New fields
- [ ] Secondary Case ID (connection?)
- [ ] Auto-generated Case ID (like ROW)

New Case Types:
- [ ] PUD | C814
- [ ] Assessment | CD
- [ ] Site Plan | SPC

Submission Status:
- [ ] Pre-approved/Pre-negotiated

Memo Sent Status:
- [ ] Uncertain

Need TIA field: (this enhancement may need some scoping, may be a new field altogether, Joan will discuss with Nate)
- [ ] Need PUD
- [ ] Need Limited TIA
- [ ] Need Amendment Letter
- [ ] Need TIA Waiver
- [ ] Need TIA Addendum
- [ ] Need TIA Mitigation Memo (captured as status already?)

**Comment by ChrispinP** [comment]
Successfully imported South Area cases. Scopes & Submissions still pending.

**Comment by ChrispinP** [comment]
Data QA complete.

Ready to close

**Comment by ChrispinP** [comment]
No further action, closing
