### ISSUE TITLE
Meeting: ROW Portal Product Review 12/14/21

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7923]

**Comment by ChrispinP** [comment]
Some Talking Points
#3603 TCP Deficiencies (search page)
#7262 Number of Deficiencies old
#3604 TCP Pie Chart Report

**Comment by dianamartin** [comment]
# Diana's Notes

- Want to report by "Department Name" - can do it if it's populated
- Removed "Deficiency OLD#" - 

Report on Deficiencies
- Export, Query by Review Dates (Submitted Date & Review Completion)
- Deficiencies by Department and Sealing Engineering
- [ ] Create table from TCP Cases, Add TCP Submission/Deficiency information
- [ ] Create table from TCP Submission/Deficiency information, Add TCP Case Information

**Comment by TracyLinder** [comment]
We were unable to finish the review in an hour today. I scheduled a followup on Friday at 3pm.

**Comment by TracyLinder** [comment]
### 12/17/21 Agenda

- [ ] Finish discussing reports
- [ ] Capture undocumented needs
- [ ] Prioritize

**Comment by TracyLinder** [comment]
**Needs**

1. Would like the UC team to have the ability to know the volume of intake, how many plans received, help w/ staffing & resource planning. He'd prefer to see this in KNACK vs an AMANDA report because KNACK is better, faster, and he'd like to see his metrics all in one place. This will involve an AMANDA integration so it will be a bigger lift. 
2. CSR/311 Request Data .... Would like to see CSR volume data in the ROW Portal, similar to the UC need above. 
3. Perhaps create a new tab on ROW Portal for 'Volume Reporting' (or a better name). Create a page for each reporting category: TCP, UC, 311
