### ISSUE TITLE
Add signal ID to payload sent to and stored in Data Tracker from Moped

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#7925]
During the review and discussion around [this Moped PR (#455)](https://github.com/cityofaustin/atd-moped/pull/455), @zappfyllc indicated that we needed to add signal ID(s) to the payload we store in Knack about a project. This issue is to track that enhancement. He wrote:

> @frankhereford I think I know the answer to this, but for the sake of documenting it with this work, do you want me to create a separate issue for figuring out adding the signal_ids into the payload, or roll that requirement up into this PR? @chiaberry is going to be addressing some of the same dependencies via #466. I don't believe the Knack record id of the respective signals related to a project are currently making it into the Moped DB (there's a JSONB column in moped_proj_features that is currently lacking that info, but that's where we would draw the signal Knack record IDs from and place into this payload), but I believe @chiaberry's work in #466 will fix that.

---
**Acceptance criteria**

- [ ] Transmit on creation and update on further synchronization, the signal IDs related to a project when a user uses the Sync to Knack feature in Moped

**Comment by zappfyllc** [comment]
- [ ] Adding an array of signal_ids (knack record vales) from the `location` JSONB column in `moped_proj_features` (should be the id property of the GEOJSON feature) to update the signals connection field in Knack @frankhereford feel free to change
