### ISSUE TITLE
Feature: Improve communication about the state of synchronization to Knack in Moped

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#7927]
@patrickm02L, in the course of reviewing [PR 455 for Moped](https://github.com/cityofaustin/atd-moped/pull/455), suggested an enhancement around the UX of telling a user about the state of synchronization with Knack. His comment includes a video, and is best seen here: https://github.com/cityofaustin/atd-moped/pull/455#issuecomment-971834332. This issue is to track the scoping process and possible implementation of this enhancement request.

**Comment by amenity** [comment]
@patrickm02L is going to cover this in his design for #7777

**Comment by amenity** [comment]
I think what we have is great. 

Success
![Screen Shot 2021-12-15 at 5 45 28 PM](https://user-images.githubusercontent.com/1463708/146282383-c6f09114-7a40-4bc1-976f-beb24a0ed73e.png)

Failure.
![Screen Shot 2021-12-15 at 5 44 55 PM](https://user-images.githubusercontent.com/1463708/146282373-b168ad5f-0092-4e21-9341-9b839d7f9dfd.png)
