### ISSUE TITLE
Perform initial project discovery

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#7935]

**Comment by moorerst** [comment]
scheduled a conversation with Tracy 1/5

**Comment by moorerst** [comment]
rescheduled 1/13

**Comment by moorerst** [comment]
Notes from discussion with Tracy
Current process 
- 24 hrs before road closure 311 is contacted
- 311 sends a email notification to a distribution list
- pain point - persons on the DL do not read the notifications, too many notifications, too much information or not enough information in the notification
Proposed process (simplified)
- Permit holder would submit the road closure info in a very easy to use platform
- Stakeholders who care would get a notification with specific information

Multiple workgroups need to coordinate construction closures
Stakeholders/work groups:
ROW
MMC - Lance, Allyson R, Brian C
PIO
CPO
Special Events Office? - Francis, Marie
Jim D

Next steps:

- meet with individual stakeholders/work groups to gather requirements/importance for COTS solution 
- [vendor evaluation template](https://docs.google.com/spreadsheets/d/1Ax1ymTcc1QWQn4lls9mJGZTvUNMoIrV6dWJV8p3YblI/edit#gid=1898501235)
- review previous demo/demo notes

**Comment by moorerst** [comment]
Notes from One Network recorded demo
Reviewed some of the pain points each stakeholder group is experiencing:
**ROW permitting:** 
need real time data
Amanda is clumsy
planned event schedules not accurate
**Special Events:**
communicating to public is difficult
coordinating with other divisions is difficult
difficult to identify scheduling conflicts
streamline impact reports, are too numerous and difficult to read
**Engineering:**
all closures have the same level of notice - no level of importance 
too many email notifications/alerts
**Demo notes:**
One Network meant to be super quick to use no technical experience needed
view of all temporary events minor and major
pull in permitting info from many sources into a map based interface
permits are points on the map, icon displays type of work
map is public facing can view with no account
need account to map areas of interest
operators in the system can open and close closures real-time from mobile app
Demoed ATL map
permit data feeds into system lane closures, 511 road work, road closures
**Traffic Management tool:**
create new event
add info to existing event
create a parent event
group event by category
set up recurrence rules/patterns

**Live link**
home dashboard
mobile app can be used by contractor for real time road closure open/close

can map detours, will produce real-time detour directions
can set up email alerts by area
have visibility to TXDOT 511 feed, traffic camera data can be made available

**Comment by moorerst** [comment]
Scheduling kickoff meeting

**Comment by moorerst** [comment]
Kickoff meeting scheduled 2/22/22 (hope that's a lucky number???)

**Comment by moorerst** [comment]
Completed initial Kickoff meeting issue #8527
