### ISSUE TITLE
Banner Permit and Payment in Knack Staff Review

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7949]
Provide page links to SMB staff so they can review what fields/layout they'd like to see

**Comment by dianamartin** [comment]
Emailed stakeholders 12/21
>I’ve been working on updating the Street Banners pages for the ATD Staff in order to review applications based on the a customer intake application. I’ve included links to test record pages you can review and compare against the old pages. I’ve also created a new test tab called “Proposed” that quickly links you to the new Lamppost Dashboard and the Over-the-Street Dashboard to review applications. I’ve also added some side-by-side comparison screen shots of the Details pages and Edit Forms. 

We’ll talk more next time we meeting, but wanted to get this you in case you wanted to review before we all met next week. 
![image](https://user-images.githubusercontent.com/21112975/147509292-f7792342-2b5b-4867-8195-2a52d59ee9a7.png)

![image](https://user-images.githubusercontent.com/21112975/147509316-072ec52a-88f8-4209-b1ef-66c92dc9d576.png)

**Comment by dianamartin** [comment]
Stephanie emailed users 12/27 and cancelled meeting for 12/28, will reconvene on 1/4. 
>Hello all, the meeting scheduled for 12/28 has been canceled. Please take some time to review the information Diana provided in the email below and we will discuss your feedback in detail during the meeting scheduled for Jan 4th. If you have any questions please let us know.
