### ISSUE TITLE
Reporting: Number of person shifts by month

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#796]

**Comment by amenity** [comment]
@SurbhiBakshi is this covered here?
![Screen Shot 2019-12-19 at 1 47 33 PM](https://user-images.githubusercontent.com/1463708/71204608-228e9680-2266-11ea-9eb0-3c8b6d270bfe.png)

**Comment by SurbhiBakshi** [comment]
@amenity yes
