### ISSUE TITLE
Reporting: Number of unfilled person hours

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#797]
Calculate the percentage of assigned but unfilled hours.

**Comment by SurbhiBakshi** [comment]
[ ] Should I keep both the pie chart and the pivot table for Scheduled Hours. Not sure if all three reports need to be included. 



![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/e671e2cc-9149-4142-a1b6-c3680b357ea7)

**Comment by amenity** [comment]
@SurbhiBakshi I think this looks good for now!
