### ISSUE TITLE
Invite Eliza Y. to the MetroBike Benefit App

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#7973]
In advance of meeting with Vendors to review the app, we need to onboard Eliza Y. to the Knack app. 

30 minute meeting.

**Comment by dianamartin** [comment]
- [ ] Create account for Eliza 
- [ ] Write up simple guideline for testing assigning code

**Comment by dianamartin** [comment]
@patrickm02L i think the "Shared Mobility Operations" should be changed to "Smart Mobility Operations".

**Comment by patrickm02L** [comment]
@dianamartin agreed. I'll put it on my plate to change the label, and request the change in the SR form.

**Comment by dianamartin** [comment]
Was testing the assigning codes and fixed the workflow. 

## Steps
The Program Manager will go to "Bike Benefit Program" to review applications
Clicks "Go to codes" - redirects to Manage Codes page
Would be under the "Available" filter and clicks "Assign & Email"
Modal pop-up shows up, selects Employee and an email is triggered

## Vendor
Would log into the system
Click 'Manage Codes" or redirected from Home URL
Under the "Assigned" filter, clicks "Redeem" icon
or
Add Promo Codes (one-off)
or
Submits spreadsheet to be imported into the application (scheduled timeline)

**Comment by dianamartin** [comment]
@patrickm02L 
I created a special filter called "TESTING" on the Manage Codes table as a Program Manager, so when Eliza is testing she won't accidentally issue a real code. 

Try out the new flow and let me know.

**Comment by patrickm02L** [comment]
The flow makes sense. I would specific on the outset to only use the "Test" entries which are both directed at your email, so that she knows to select your records in the "Needs Review" tab (step 1), and the modal pop-up (step 4).

**Comment by dianamartin** [comment]
I reviewed the "Steps" as I was writing the email to Eliza and caught something I wanted to say differently. Emailed user -12/21
>**Steps**
>1.	Go to "Bike Benefit Program" tab and click “MetroBike Employee Benefit” page to review applications 
  >- or under the “Home” page is a quick link to the “MetroBike Employee Benefit” page
>2.	Under the “Needs Review” tab (I’ve currently set it to the test records I created), Click “Go to codes” icon for one of the records - redirects to "Manage Codes" page
>3.	On "Manage Codes" page (I’ve created the “TESTING” filter to show the test codes I created), Click under the “Assign & Email” field (envelope icon)
>4.	A pop-up dialog box will show up, select "Employee" (Select “Diana” or “Test Tester”) 
  >- Can add "Notes & Comments" (optional) and an email is triggered to the Employee (which will send an email to me)

**Comment by dianamartin** [comment]
Will follow-up next week when schedules are back to normal

**Comment by dianamartin** [comment]
We walked Eliza through logging on during our sprint review 1/6
