### ISSUE TITLE
Create automated process for EMS to VZD ETL pipeline

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#7985]
Once we complete https://github.com/cityofaustin/atd-data-tech/issues/7955, we'll need to scope out the data import pipeline which will likely require some back and forth with partners at EMS. They may prefer to send data via email or SFTP, or they may be able to expose a database view for us.

We'll also need to decide whether this new ETL should get implemented in Airflow or Prefect.

**Comment by patrickm02L** [comment]
Bring up in January Sprint meeting. Who is the EMS contact that manages the data and can send it to us?

**Comment by patrickm02L** [comment]
The contact for EMS is Lynn C., and Pamela Q. Xavier sent an email introduction that includes Lewis, Joel, Mateo, and I.

**Comment by patrickm02L** [comment]
Lynn set up automated email to deliver EMS data to us, 3/17/22.
