### ISSUE TITLE
Provide a list of addresses from RPP in Knack

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#7988]
Requested by RPP staff 
Is there a simple way to pull a list of all addresses we issue RPP permits to from Knack?

- You want any address that was issued a permit no matter what type of permit? -**Yes -any RPP permit**

- What format do you want it in, will an excel spreadsheet do? **-Excel is fine**

- Do you want us to eliminate duplicates? -**To eliminate duplicates would be preferable, but not absolutely necessary.**

- You just want address no additional information? -**Just addresses is fine.**

**Comment by moorerst** [comment]
@chrispin there is an By Address page on the RPP back end app that may provide the information they are looking for but there is not a export option on that page
![image](https://user-images.githubusercontent.com/56606465/146405221-bc890306-e686-426f-97bf-ac077c594d53.png)

**Comment by ChrispinP** [comment]
@moorerst yea I can update this view and make it exportable.

**Comment by moorerst** [comment]
@ChrispinP if you can update the view and make it exportable I think this will provide the data they are looking for

**Comment by ChrispinP** [comment]
Added the Export option to the By Address table
![image](https://user-images.githubusercontent.com/67915167/146411919-e1bceea7-810f-4bef-9b42-a6c01ed941a9.png)

Fixed the table grouping, set to Name of Applicant. Updated the Application ID field

**Comment by moorerst** [comment]
Selected status - Completed and exported the report ApplicationsByAddress. Provided the data to the RPP Staff for review with instructions on how to produce the same report in the future. Waiting for confirmation from staff.

**Comment by moorerst** [comment]
@ChrispinP thanks for your quick response. Customer confirmed this provides that information they are looking for. Closing issue
