### ISSUE TITLE
New Feature: Manual Extension Update for TURP (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7990]
### Due to updates on #7283 (TURP extension updates), staff will have no way to update the folder status and expiration date when the extension fees are paid and the folder info Activate Upon Payment is no. We must implement a solution before #7283 can go to PROD.

**Acceptance Criteria**

- A new attempt called "Manual Extension" needs to be created on the Permit Extension Process in RW folders for subtype TURP. 
- System needs to perform the following actions when the attempt "Manual Extension" is made on the Permit Extension Process 
-- Display an Alert (not hard stop) stating "Please make sure Applicant's Bond, Insurance, Fee and Date Range information are up to date."
-- Change the folder status to "Active".
-- Update the folder Expiry date with the date provided in the Extension End Date Folder Info field RW Folder. 

Note: The Folder Issue Date and Folder Issue User should NOT be updated as part of this attempt. 
The Permit Extension Process should NOT be updated with an Ended Date as part of this attempt.

**Comment by TracyLinder** [comment]
@Nadin-Nader will assign this to Vish tomorrow. I'd like Vish to write draft AC for a new process attempt that will update the folder status & expiration date. Call the attempt **Manual Extension**.

**Comment by vschandramouli** [comment]
@Nadin-Nader  I completed the AC for this. Please review. Moving to Backlog.

**Comment by TracyLinder** [comment]
AC looks good to me.

**Comment by SubhaShroff** [comment]
### Status:
@Nadin-Nader  @TracyLinder  This is completed on localhost and sent you in email for review, today.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder the DEMO looked good. It can go to **_DEV_**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0192426 is submitted for DEV deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0192665, SCTASK0192660 are submitted to do DEV deployments. To add new attempt - Manual Extension and another request to assign the attempt to the RW permit Extension Process.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to **TEST**. Please UAT

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I Tested it and it looks as expected. Please let me know if we can get it to TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0192925, SCTASK0192922 - commit (1171f8fe9d54) are submitted for TEST deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is deployed on TEST. I tested it and it works as expected. Ready for UAT.

**Comment by Nadin-Nader** [comment]
@SubhaShroff Paloma did her UAT and found the following:

> [1:20 PM] Amayo-Ryan, Paloma
> I tested ticket # 7990 on RSN #12669246.  It did not pass the test. 
> 
> The folder was in Expired status.  
> 
> Just to be thorough, I ensured "Activate Upon Payment" was marked No.  Then I attempted to add a fee and pay the related bill but apparently I'm not able to pay bills in AMANDA test.  (Not sure when I lost those permissions.)
> 
> I then skipped to the Process tab, "Permit Extension" process, Info sub tab.  I added the Extension Start Date (01/19/22) and 10 days in Tier 1. That made the Extension End Date 01/28/22.
> 
> Next I went to the Attempt sub tab.  I selected the "Manual Extension" attempt and saved.
> 
> The permit status was changed to Active; however, the new expiration date was not correctly listed.

**Comment by Nadin-Nader** [comment]
@SubhaShroff here is Palomas response:

> [4:14 PM] Amayo-Ryan, Paloma
>     
> 
> Nader, Nadin - Yes, the issue is that we cannot/do not update those Extension Start and End Dates from the folder Info Tab.  The dates are updated from the Process tab ->"Permit Extension" process -> Info sub tab.  (And it's those dates that are not reflecting on the Info Tab nor the Folder Expires date.

**Comment by SubhaShroff** [comment]
@Nadin-Nader @vschandramouli  The ticket AC mentions Folder info, so its done that way. Can I get the AC updated accordinly?   Parallely, I can start working on that change.
![image](https://user-images.githubusercontent.com/51680715/150229912-c52919a5-4256-4e5a-bdc6-6dfa47fa7977.png)

**Comment by TracyLinder** [comment]
**Here is my feedback / also posted in the teams chat:**

So IMO, the expiration date should populate with the value in info 'Extension End Date'. That info is supposed to be updated when 'Extension Granted' is saved on TURP Permit Extension process. Subha is there a bug causing this info not to update properly?

See in the red box; is this where the bug could be?
<img width="1122" alt="Screen Shot 2022-01-20 at 4 45 08 PM" src="https://user-images.githubusercontent.com/49930868/150434404-557bfd39-2593-4373-af0b-3647d99699f7.png">

**Comment by TracyLinder** [comment]
**Updated Feedback:**

Paloma was expecting the 'manual extension' attempt to do the 'Other Functions' in the red box above. Only 'extension granted' will do that. 

**Teams chat:**

Ok, Subha and I figured out that this probably isn't a technical issue. Amayo-Ryan, Paloma the 'Manual Extension' attempt is not meant to do anything with the process infos so you wouldn't use the process infos when saving Manual Extension. (Process Infos are new start, new end, days in tiers...)
 
You'll still need to use extension granted to update start/end/extension dates. Manual Extension is only meant to update the folder status and expiration date. Clear as mud? I'm around if you want to chat.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  As per the TEST UAT feedback, there is a variation in AC and stakeholders statements about from where the Expiry Date should be picked from. So, as I spoke to Tracy last evening(1/20/2022), she  is going to talk to them and confirm/update the finalized AC.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  PROD deployment request is submitted today after stakeholders agreed with AC in UAT 2PM Call.
SCTASK0194831.

**Comment by TracyLinder** [comment]
I just tested this in PROD and it works fine. I'm closing this.
- Test Case: 22-012603

FYI @Nadin-Nader
