### ISSUE TITLE
New Feature: Manual Extension Update for EX (RE-UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#7991]
### Due to updates on #7631 (ex extension updates), staff will have no way to update the folder status and expiration date when the extension fees are paid and the folder info Activate Upon Payment is no. We must implement a solution before #7631 can go to PROD. 

**Acceptance Criteria**

- A new attempt called "Manual Extension" needs to be created on the ROW Admin Process in EX folders. 
- System needs to perform the following actions when the attempt "Manual Extension" is made on the Permit Extension Process 
-- Display an Alert (not hard stop) stating "Please make sure Applicant's Bond, Insurance, Fee and Date Range information are up to date."
-- Change the folder status to "Active"
-- Update the folder Expiry date with the date provided in the Extension End Date Folder Info field in EX folder.  

Note: The Folder Issue Date and Folder Issue User should NOT be updated as part of this attempt. 
The ROW Admin Process should NOT be updated with an Ended Date as part of this attempt.

**Comment by TracyLinder** [comment]
@Nadin-Nader will assign this to Vish tomorrow. I'd like Vish to write draft AC for a new process attempt that will update the folder status & expiration date. Call the attempt **Manual Extension**.

**Comment by vschandramouli** [comment]
@Nadin-Nader  AC updated. Please review.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader, @TracyLinder - I have a few questions before I begin on this Card. 

1. Do I need to check that the previous attempt must be "Extension Granted" when this attempt is given?
2.  It is mentioned that we need to check fee and date range must be up to date; meaning the date ranges must be re-entered again in this attempt? or can it be picked from the extension end date to update the expiry date?
3. Do I need to check whether the billed fee is paid or not?

**Comment by vschandramouli** [comment]
@Sreelatha-BlazeKannan For points 1 and 3, I asked the stakeholders if any pre-validations were needed for this attempt and they did not want to add anything. 
For Point 2, we dont need to check for updated dates, we would just need to update the Folder Expiry date with the date provided in the Process Info. 

CC @Nadin-Nader

**Comment by TracyLinder** [comment]
AC looks good to me.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader @TracyLinder - Analysis is in progress.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Upon submission of #7631 DEV DP, will be working on this.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Development completed, working on the warning message. And testing will be done once warning message

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Sent the Demo and Submitted the DEV DP; kindly approve and create task id for me here is the commit ID: 2a8b72d9534a

**Comment by TracyLinder** [comment]
**My Feedback to Nate regarding the save/alert issue from today's demo:**

1. Subha & Sree sync to try to fix it (Seems to work for TURP)
2. Is there a different type of popup alert box we can use to get around this issue?
3. If 1 & 2 don't work, I'll ask stakeholders if we can drop the alert.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - fixed the issue, warning code -20999 was missing in my code. which resolved now. Created a general Warning procedure for COA usage (P_COA_WARNING) in future.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Since the previous commit was not audited, reverted and resubmitted the single commit as two commits to avoid dependencies for 7990 n 7991. Here are the two commits for reference. 

1. Valid Table Commit - 1171f8fe9d54
2. Code Commit - c60f210aaa27

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan sent the Commits to be deployed to **_DEV_** under two different TASKS:

**SCTASK0192660** = **1171f8fe9d54** Valid Table
**SCTASK0192667** = **c60f210aaa27** Code Commit

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0193398**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV and submitted Demo for this card. Will be sending the TEST DP by eod.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Submitted  TEST DP for #7991; kindly approve and create task id for me.

Here are the commit IDs and their order.
1.	Order 1 - c60f210aaa27
2.	Order 2 - 8b092c5c52b2

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0194072**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been deployed to **TEST** Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - This cant be tested until #7631 moved to TEST. So, sent TEST DP for #7631.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been sent to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0194857**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been deployed to PROD

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has not been completed as i am waiting on the last commit sent at 230 today to go to **_PROD_** under **SCTASK0195144**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been deployed to PROD

**Comment by TracyLinder** [comment]
**❌ UAT Failed ❌**

Test case 22-012662-EX does not have 'Manual Extension' as an attempt type on the Row Admin Process. This needs to be re-deployed. 

FYI @Nadin-Nader

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST and it is working as expected. Ready for PROD implementation.

**Comment by TracyLinder** [comment]
### UAT Passed - Please promote to PROD

**Comment by TracyLinder** [comment]
## Tracy's PROD UAT 3/11 @ 2pm

### COS
_2022-034458 EX TRACY - UAT: Manual Extension_



### PVT
_2022-034462 EX_
