### ISSUE TITLE
[BUG] Inconsistent comment filter behavior

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8001]
It's hard to replicate consistently, but occasionally I see a "status update" comment appear under the "timeline notes" filter tab.

This seems to happen immediately after creating a new comment from the comment's tab, then clicking the various filters. If I refresh the page the error is resolved.

<img width="809" alt="Screen Shot 2021-12-16 at 1 05 34 PM" src="https://user-images.githubusercontent.com/14793120/146434404-d34e703b-3d78-402f-9dd0-de8d79207892.png">

Also, Renée reported seeing comments ordered with oldest at the top when the "Status updates" filter was on — backwards from how it is otherwise and should be.

**Comment by amenity** [comment]
I just saw the "Status update" field empty when it shouldn't have been.
