### ISSUE TITLE
[BUG] Deleted funding item appears on signals dashboard

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8002]
After deleting a funding item from a project, it still appears in the signal dashboard.

To reproduce:
1. add a funding item to a project
2. delete the funding item
3. navigate to signal dashboard and check the funding column for the project in question

<img width="1418" alt="Screen Shot 2021-12-16 at 1 11 52 PM" src="https://user-images.githubusercontent.com/14793120/146434826-7c266f5c-3f32-4409-9650-94316c827e71.png">

<img width="1359" alt="Screen Shot 2021-12-16 at 1 11 58 PM" src="https://user-images.githubusercontent.com/14793120/146434823-b79f8944-a6b4-48a6-84d7-92b96d9ab8e0.png">

**Comment by amenity** [comment]
@chiaberry - queuing this up for next sprint... any pointers where someone might start to troubleshoot this?

**Comment by johnclary** [comment]
One should troubleshoot the use of the `FUNDING_QUERY` ([here](https://github.com/cityofaustin/atd-moped/blob/2f87f38fa9bd706b5e30677fa6e87b6301985d02/moped-editor/src/queries/funding.js#L3)) and the `DELETE_PROJECT_FUNDING` query ([here](https://github.com/cityofaustin/atd-moped/blob/73140e3f80293a6d497058512b5b858e15bf18c3/moped-editor/src/queries/funding.js#L63)).

Either the filter conditions for the funding query need to be updated, or we're not setting the right status of deleted funding items.

**Comment by amenity** [comment]
@frankhereford - sticking a 2 on her for now, feel free to update when you're done.

**Comment by frankhereford** [comment]
This is up for review now in PR 529. 

I'm going to downgrade the points to a `1`, this was very straightforward. 

Thanks!
