### ISSUE TITLE
Convert milestone select input to autocomplete

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8006]
The milestone select input has a lot of options. Convert it from a select input to an [autocomplete component](https://mui.com/components/autocomplete/).

<img width="596" alt="Screen Shot 2021-12-16 at 3 13 33 PM" src="https://user-images.githubusercontent.com/14793120/146451268-c3f81a98-7904-4564-9ea5-cbde70533afe.png">

Example autocomplete is signal picker:
<img width="836" alt="Screen Shot 2021-12-16 at 3 13 55 PM" src="https://user-images.githubusercontent.com/14793120/146451248-d5244f08-c518-4fd5-a437-ed95f936f1b2.png">

**Comment by sergiogcx** [comment]
There is a PR:
https://github.com/cityofaustin/atd-moped/pull/518

https://images.zenhubusercontent.com/140626918/1dcfdc6b-19fa-45fb-9c15-e0033ea7c8ab/2022_01_06_05_48_34.mp4
