### ISSUE TITLE
CSV-based workflow to duplicate teams and assignments from month to month

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#801]
It is quite time-consuming for Lewis to make the VZA schedule. Anything we could do to expedite this (like implementing defaults for some fields) would probably be helpful. 

His current workflow begins with copying the spreadsheet for the previous set of assignments and making various changes. Could we replicate this in Knack? I can think of a few approaches:
- A button under the calendar "Duplicate this schedule" that would either replicate that same schedule 28 days later or allow the Scheduler to specify a start date for the repeated schedule
- Checkboxes in the Assignment Table that would allow Lewis to bulk select assignments and replicate them at a later date
- Some sort of import+export workflow with a CSV

**Comment by amenity** [comment]
@johnclary - The need for this functionality was strongly validated during @SurbhiBakshi's walkthrough of the process with Lewis today. I'm not sure if you have something in mind, but if not I can circle back with Lewis and see if he has an ideal solution.

**Comment by johnclary** [comment]
@amenity @SurbhiBakshi what needs to be copied—the shift only, or both the shift and the assignments?

**Comment by johnclary** [comment]
we could add a "copy" button to the shift details—this would pop a modal form where lewis puts in the new shift date. the form submission would cause the shift and assignments to be copied to the specified date.

**Comment by SurbhiBakshi** [comment]
@johnclary @amenity just the assignments, we got rid of the shifts object some time back, shifts and teams are fields that mainly used as labels. I did a manual export as CSV, change date, import as CSV into the object, but wanted to see if there was an automated way to get this done.
There are about 58 assignment records per week, Lewis schedules the whole month at a time, so he would  create around 250 assignments records at a time.

**Comment by johnclary** [comment]
ok, I must have been looking at the wrong prototype. in that a CSV import is probably your best bet.

**Comment by SurbhiBakshi** [comment]
I guess that is something only a Knack builder can do?

**Comment by johnclary** [comment]
indeed. alternatively, we could add checkboxes to a table view so that lewis could bulk select/copy. probably 12 hours of python + javascript development to implement.

**Comment by SurbhiBakshi** [comment]
in the near future I can do the CSV process, and for now put the python/ javascript approach  in the backlog? cc @amenity

**Comment by amenity** [comment]
Here's an issue for the custom code: https://github.com/cityofaustin/atd-data-tech/issues/1295. 

This is the work Surbhi did for this round of scheduling: https://github.com/cityofaustin/atd-data-tech/issues/1299

Next time: https://github.com/cityofaustin/atd-data-tech/issues/1300
