### ISSUE TITLE
Propose light redesign of "Funding" tab

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8011]
The Funding page will need to accommodate some additional information: 
- Links to task orders, see #7930 
- DO # 
- Estimated cost ?? just a simple write-in value to be replaced by #3663 down the line

We're also enhancing the "Funding sources" table itself - #4530 

Things are already looking a bit awkward with the eCAPRIS link and my [mockup adding task orders](https://user-images.githubusercontent.com/1463708/146332929-8c345de1-8eea-4648-8d3e-bdfd85c8f2e8.png) might make it worse? In any case, it would be good to take a thoughtful look at the design before barnacle-ing on more items. 🤪

**Comment by amenity** [comment]
@johnclary please correct/add anything I've missed here. @patrickm02L - John can help provide context and terminology for the funding data and its various sources.

**Comment by patrickm02L** [comment]
Proposal:

- Links to eCapri and Task Order become buttons. (referencing the sorting buttons on comments page)
- New funding sources table
- "Add Funding Source" button moved underneath entries. 

![Moped Funding - Light Redesign](https://user-images.githubusercontent.com/5566727/147285274-3fc39c65-5d33-48ff-a0ca-3a662f266eda.png)

**Comment by patrickm02L** [comment]
@amenity ready for review.

**Comment by amenity** [comment]
@patrickm02L - I like! What were you thinking it would look like before there was a value, when the user needs to add one?

**Comment by patrickm02L** [comment]
Is the eCapris value in-line editable? Also, is this the only place where task orders are added?

**Comment by amenity** [comment]
@patrickm02L - yes, eCapris should be inline editable here instead of on the "Summary" tab. Task orders can also be added from the "Signal projects" table.

**Comment by amenity** [comment]
@patrickm02L - when this design is ready, please 
- Update issue #7930 issue description to reflect your new design
- Update #8079 with all other refinements you're proposing

**Comment by patrickm02L** [comment]
@amenity I updated #7930 I don't have and additional suggestions for refinement #8079 at this time.

**Comment by amenity** [comment]
So excellent! I tweaked the XD a bit and filled out #8079.
