### ISSUE TITLE
Add VZA Citations App user account credentials to 1Password

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#802]
@SurbhiBakshi - when you get a chance could you please save one set of credentials per VZA Citation App role so that I can familiarize myself with role-specific UIs, perform acceptance testing, etc? 

Here's the pattern that we are using: 
![Screen Shot 2019-10-23 at 2 37 09 PM](https://user-images.githubusercontent.com/1463708/67428120-28883400-f5a3-11e9-8e22-e93c464a5585.png)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/5ed7aa4d-5f68-4701-a022-75967ba52fd1)

@amenity

**Comment by amenity** [comment]
@SurbhiBakshi beautiful, thanks!

**Comment by amenity** [comment]
I moved these to Knack Shared vault, /cc @dianamartin ...
