### ISSUE TITLE
Go-Live Tasks for: [TDS Portal] TDR Dec 2021 Upgrade

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#8021]
### Planning/Prep
- [x] Meeting with stakeholders to talk about go-live, roll out plan to end users - **12/10/21**
- [x] Set Go-Live Date - **12/27/21**
- [x] Create workflows, status matrix
- [x] Provide user training (create issue?)
- [x] Go Live Email with Date & Time

### Testing
- [x] Test all buttons (as each user role)
- [x] Check page permissions (sign in as each user role)
- [x] Record data populating and displaying correctly
- [x] Are page, view, table rules working correctly
- [x] Are tasks, record rules, & email rules working correctly
- [ ] User testing, user acceptance
- [x] Chris Test
- [ ] Diana Test
- [ ] Tracy Test
- [x] PM Test (Sangeeta/Amber)
- [ ] Reviewer Test

### Clean-up/Finalize
- [x] Delete all test records from everything (object tables)
- [x] Provide access to users for new modules/new user roles
- [x] Change out email addresses for email notifications
- [x] Remove any page rules that have pages hidden
- [x] Modify page log-in user roles for Go Live

### After Go Live
- [x] Stakeholder/Power users available during Go-Live dates to make sure they are QA/QC for any issues coming from end users
- [x] Schedule app builder to be available during Go-Live day to be available in case of issues
- [x] Check in with stakeholders day of Go-Live and 1-2 days after Go-Live
- [x] Remove any deprecated Fields
- [x] Remove any deprecated Pages
- [x] Migrate any attachments if necessary #8065 and #8066

**Comment by ChrispinP** [comment]
### Moving TDR Update to Prod 12/23/21:

- [ ] Application Announcement created 
![image](https://user-images.githubusercontent.com/67915167/147262846-aeedd1c4-507c-47da-842c-1ac0a7fd3873.png)

- [ ] Update TDR object names
![image](https://user-images.githubusercontent.com/67915167/147281608-91927e2d-ece5-4720-bbdc-ae278d85c29f.png)

- [ ] Create TDS Viewer role and update TDR Reviewer role
![image](https://user-images.githubusercontent.com/67915167/147269579-750b097c-9cb6-4c5d-b4dd-a0a701ab3ef1.png)

- [ ] Update Accounts Count fields
![image](https://user-images.githubusercontent.com/67915167/147272514-fa7c6e02-2122-4916-b8a3-c1ea46d32a23.png)

### TDR_review_cycle_comment

- [ ] Update Date/Time & By fields
![image](https://user-images.githubusercontent.com/67915167/147272150-06d67175-45af-47a3-913a-a6c71751fd48.png)

- [ ] Update Requested By & Assigned Reviewer to Lead Reviewer & Vision Team Reviewers
![image](https://user-images.githubusercontent.com/67915167/147273435-09d7c0bc-5240-469a-a8f3-c711ab81e4d7.png)

- [ ] Updated record Connection fields
![image](https://user-images.githubusercontent.com/67915167/147275166-16dc80dd-9118-4ccc-8353-732ddd163843.png)

- [ ] Update Due Date & Text Formula fields. Add fields for reporting/dashboard metrics
![image](https://user-images.githubusercontent.com/67915167/147279858-537490c0-66c6-42ba-a182-0156b100afca.png)

- [ ] Update Attachment fields
![image](https://user-images.githubusercontent.com/67915167/147279978-44e1fc29-418f-4e53-8baa-f64ad1a846a2.png)

- [ ] Update No Response Equation and Task
![image](https://user-images.githubusercontent.com/67915167/147281399-3ecba1d0-5be2-41f4-b9b7-918bef680e55.png)
![image](https://user-images.githubusercontent.com/67915167/147281343-28be9773-d262-4f41-9eac-c9da1220c7c1.png)

**Comment by ChrispinP** [comment]
### TDR_review_cycle_attachment

![image](https://user-images.githubusercontent.com/67915167/147296077-c0de6f57-1980-42ae-9b60-a87ad0fd08f1.png)

- [ ] Attachment Description > Attachment Name
- [ ] Added Date/Time & By fields
- [ ] Added Text Formula fields
- [ ] Added Review Cycle connection

**Comment by ChrispinP** [comment]
### TDR_review_cycle

- [ ] Update Date/Time and By fields
![image](https://user-images.githubusercontent.com/67915167/147296621-963d74f4-e42f-496b-abb8-cc131e23aaa2.png)

- [ ] New Boolean fields for when a Review Cycle is Assigned, Completed, or Adjusted
- [ ] Added Lead Reviewer and Vision Team Reviewers connections
![image](https://user-images.githubusercontent.com/67915167/147296744-5219bbb2-4eec-4abf-83bc-7238c8b68fb8.png)

- [ ] Added Text Formula fields
- [ ] Updated or added Review Cycle Status, Cycle Number, and Due Date fields
![image](https://user-images.githubusercontent.com/67915167/147296825-556ad092-681f-4998-974f-6560fc8dd650.png)

- [ ] Added fields for reporting/dashboard Metrics
![image](https://user-images.githubusercontent.com/67915167/147296889-8ea1a067-e0f4-43f5-9f6a-8828001d29bb.png)

**Comment by ChrispinP** [comment]
### TDR_review

- [ ] Updated and added Date/Time & By fields with Submitted and Completed Boolean fields
![image](https://user-images.githubusercontent.com/67915167/147299203-a965f9c4-ba23-40ba-934e-26da55ef266d.png)

- [ ] added Lead Reviewer and Vision Team Reviewers connections 
![image](https://user-images.githubusercontent.com/67915167/147299230-f859b13f-42a3-42d2-8af3-6891e8933657.png)

- [ ] Added Project Description
- [ ] Updated Case ID
- [ ] Added Text Formula fields
- [ ] Setting Addresses to Short Text instead of Text Formulas now for Coordinates
![image](https://user-images.githubusercontent.com/67915167/147299315-dfbae374-7e01-4373-b714-7520161ff55a.png)

- [ ] Added fields for reporting/dashboard Metrics
![image](https://user-images.githubusercontent.com/67915167/147299338-0c5950af-49c6-4e1d-90b2-a11f628a4152.png)

- [ ] Update Text Formulas in child objects so everything is accurate

**Comment by ChrispinP** [comment]
TDR Reviews Update Complete
![image](https://user-images.githubusercontent.com/67915167/147504842-5abb4f00-336f-4d92-93f9-dd8b84715293.png)

TDR Advanced Search, Application, and Vision Team Dashboard Update Complete
![image](https://user-images.githubusercontent.com/67915167/147504917-f74d688c-3943-40cc-b7cc-b0aa567c12ea.png)

Reviewer Dashboard Update Complete
![image](https://user-images.githubusercontent.com/67915167/147504680-ef46c1e4-c02d-44f6-bc74-91f15593e6b7.png)

All ready for testing and review

**Comment by ChrispinP** [comment]
Completed Testing; verified data collection and population for objects as well as double checking all rules.

Removed deprecated fields from objects, deprecated views, deprecated rules, and deprecated pages. Also secured all attachment fields. Minor code updates to home and back buttons, will push a PR for them. Will create attachment migration issues to migrate historical attachments.

**Comment by ChrispinP** [comment]
New TDR Process Workflow rough draft can be found in [Miro](https://miro.com/app/board/uXjVOZGdMbU=/): 

![image](https://user-images.githubusercontent.com/67915167/147840245-f74f545a-2f06-452e-a3e7-da237cae45ae.png)

**Comment by TracyLinder** [comment]
This release is stable. Closing.
