### ISSUE TITLE
Bug: UC Invalid Payment Type (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8034]
**Acceptance Criteria** 

- Check should be made a valid payment type for UC folders when users pay for UC folder fees.

_Email from Customer; Isiah w/ ROW_

A customer phoned to say they tried to pay by cheque invoice 7525597 on folder 12849295 at PDC Cashier.  Cashier attempted to process payment and reportedly received error message Invalid payment type for this folder type.  Is payment type on UC folder restricted to card-only?

**Comment by TracyLinder** [comment]
I asked @Lpriya-LIT to look up the valid payment types for UC. We'll go from there.

**Comment by vschandramouli** [comment]
Existing payment types allowed for UC folders: 

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/94101e01-da9c-47a7-ae14-1433a272e991)

@Nadin-Nader @TracyLinder  This was the only AC I could think of for this ticket after conversation with Isaiah. Moving to Backlog.

**Comment by vschandramouli** [comment]
Reached out to Amber H on Teams requesting fee info.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder The Check payment type is added to UC permit.  And SCTASK0201961 is submitted for DEV deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This is deployed in DEV. Check payment type is valid for UC permit in DEV now. Please let me know if I can get it on TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0202480 is submitted for TEST Deployment.

**Comment by Nadin-Nader** [comment]
This has been deployed to TEST

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I tested this on TEST and its ready for UAT.

**Comment by Nadin-Nader** [comment]
Waiting on Darren's approval for PROD

**Comment by Nadin-Nader** [comment]
Approved for PROD but they wont be able to test it as they have to wait for someone to Pay with a check.

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0205435 is submitted for PROD deployment.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to PROD. Jaclyn, Darren and Isaiah know but this cannot be tested until a customer tries to pay with a check.
@TracyLinder should we close it and ask then to let us know if it works when someone tries to pay with a check in the future?

**Comment by SubhaShroff** [comment]
### Status:
@TracyLinder  @Nadin-Nader  should we close this?

**Comment by Nadin-Nader** [comment]
[9:46 AM] Lozano, Jaclyn
Hey Nadin finally found someone who can process payments. They said the check payment worked.
