### ISSUE TITLE
BUG: New "Activity" Info showing up on the GF Folder, should only show with SubType "ATD", Exclude form all other Subs (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#8042]
## BUG: New "Activity" Info is showing up on the GF Folder, SubType "Fire" with ATD Fees: "TCP Review Fee" and the "ATD Tech Surcharge - TDS"

Reference card #7607 Create new info (Activity) & Add to Permit Folders
Commits:
  -  "1179e4ad84b4" (This one is the creation of the info)
  -  "1ed8c5b88761a" (This one was a change to the validation)

**We will need to Exclude all Subs not ATD for this info and Fees**

Krisha Allen Put in an Incident with CTM (**_INC0158856_**) stating the following:

> The GF folders with Sub Type Fire and Group Permits is now generating infos and fees that do not pertain to fire fees. Please remove all fees and infos on the GF folder for Sub Type Fire and Group Permits. Please see attached screen shots. Please let me know if you need additional information. Thanks.

![GF Fire Folder.JPG](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/71eb76e3-5d1c-4d68-8636-c237e71765c5)
![Error on GF.JPG](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/b0587856-387f-4622-a32e-0a1ddd06e1af)
![Capture.JPG](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/7469b118-3103-48ae-b6f7-2eed1166117b)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  
I am wondering how the fees are added in the above permit (screenshots). I see its on TEST and I tried to recreate the same permit but it didn't add any fee. 

![image](https://user-images.githubusercontent.com/51680715/148096612-c0317394-0d4c-45e0-9549-9a5b72877518.png)

![image](https://user-images.githubusercontent.com/51680715/148096679-817db220-bda1-407b-87f1-6bab6a11c84b.png)

![image](https://user-images.githubusercontent.com/51680715/148096788-7403ff49-d7a5-4ab4-8272-527bc57784ea.png)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0190539 is submitted for the commit to exclude the subtypes of GF for Activity info.

**Comment by SubhaShroff** [comment]
### Status:
SCTASK0190539 - Waiting for CTM team to do DEV deployment.

**Comment by SubhaShroff** [comment]
### Status:
DEV deployment is done. Tested for all GF subtypes. ACTIVITY info is added only to ATD & no work type combination. I tested for FIRE subtype - Fee is also not added.
@Nadin-Nader  please let me know if I can submit TEST deployment request for this. 

![image](https://user-images.githubusercontent.com/51680715/148407384-92cccccb-34ea-4247-ad8a-23ee7873b034.png)

![image](https://user-images.githubusercontent.com/51680715/148407472-b697818b-3e19-4034-8dcd-f11cdc77ccd9.png)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0191162 is submitted for TEST deployment.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to **_DEV_**, please UAT

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Tested on TEST. Looks good, displays ACTIVITY info only for ATD & no worktype of GF.

**Comment by Nadin-Nader** [comment]
Sent a Teams message to Krisha asking her to test this on TETS to make sure the GF folder doesnt put in any ATD Fees or "Activity" infos when the worktype is anything but ATD.

**Status:**
Waiting on Krisha to UAT on TEST

**Comment by Nadin-Nader** [comment]
@SubhaShroff Got a response from Krisha saying everything works properly now. 

> [1:27 PM] Allen, Krisha
>     Hi Nadin - I was able to test and everything is working for the fire subtype now. Thanks!

##  APPROVED for PROD Deployment🎉🎉

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0191892 is submitted for PROD Deployment.

**Comment by SubhaShroff** [comment]
### Status:
PROD deployment request is submitted. CTM is on it.

**Comment by Nadin-Nader** [comment]
On PROD. I will let Krisha know and close

**Comment by Nadin-Nader** [comment]
Informed Krisha that the change is on PROD via Teams chat. Closing
