### ISSUE TITLE
Redesign and modernize data.mobility.austin.gov

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#805]
Re-design and modernize the code base of our central online presence, the [Data and Performance Hub](https://data.mobility.austin.gov).

**Comment by JaceDeloney** [comment]
This is what I spent part of my Discovery Day putting together

[Updates to the Data & Tech Website
](https://docs.google.com/document/d/1nhCppg1A9FLQ8AahJ0ZELpdbkEvO6xhh5ylRAcmYzK4/edit#heading=h.5bb83cf8ubvc)

**Comment by johnclary** [comment]
This will be covered by [#6482](https://github.com/cityofaustin/atd-data-tech/issues/6482)
