### ISSUE TITLE
Expand "Activity Tracking" to tracking to include new tables and columns

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8055]
We'll need to listen for inserts or updates on these tables:
- `moped_project` (insert is handled by `updated_at`'s default `NOW()` )
- `moped_proj_components`
- `moped_proj_entities`
- `moped_proj_funding`
- `moped_proj_milestones`
- `moped_proj_notes`
- `moped_proj_partners`
- `moped_proj_personnel`
- `moped_proj_phases`
- `moped_project_files`
- `moped_project_types`

And can exclude these tables:
- `moped_proj_features`	(covered by edits to `moped_proj_compoents`)
- `moped_proj_components_subcomponents`	(covered by edits to `moped_proj_components`)
- `moped_proj_features_components`	(deprecated)
- `moped_proj_financials`	(not implemented)
- `moped_proj_fiscal_years`	(not implemented)

**Comment by frankhereford** [comment]
@amenity - I have a question for you that has come out of the inspection of our database triggers and the event definitions in `graphql-engine`. In addition to `INSERT` and `DELETE` operations on these tables, `UPDATE`s trigger an entry to be created in the activity log. What's interesting is that we don't currently trigger an entry for an update to all fields in the following tables. Is this the behavior you want, or should we be tracking an `UPDATE` on all fields?

`moped_proj_funding`: dept_unit, fund
`moped_proj_notes`: added_by_user_id, status_id, project_note_type
`moped_proj_partners`: status_id
`moped_proj_phases`: phase_id, status_id, subphase_id, subphase_name
`moped_project`: is_retired, milestone_id, status_id, task_order, contractor, project_sponsor, knack_project_id, project_website, work_assignment_id, purcahse_order_number
`moped_project_files`: file_type
`moped_project_types`: status_id

Thanks!

**Comment by frankhereford** [comment]
@amenity indicated that the fields in the above comment should trigger an update in the activity log.

**Comment by frankhereford** [comment]
@amenity @mateoclarke 

During today's dev sync, we discussed the option of extending the schema map JavaScript object that helps define the behavior to use FK relationships to display rich content for records recorded by integer. It was indicated that this was a useful feature and worth including in this PR.
