### ISSUE TITLE
[TDS-TDR] Data Cleanup: Migrate Historical Attachments from TDR_review object

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#8065]
Migrate historical TDR_review attachments from the TDR_review object to the TDR_review_cycle_attachment object
![image](https://user-images.githubusercontent.com/67915167/147840123-5ba10866-12d0-455f-b160-225f779e85a1.png)
![image](https://user-images.githubusercontent.com/67915167/147840111-94680151-9fe8-43bf-aece-a9a3c4ceb1ee.png)

**Comment by johnclary** [comment]
@ChrispinP how soon do y'all need this done?

**Comment by ChrispinP** [comment]
@johnclary I dont think there is a rush but this would help eliminate a step for them having to manually connect them to their Review Cycles right now. I am also open to learning how to migrate attachments myself if you are open to teaching.

**Comment by johnclary** [comment]
@ChrispinP is there a way to determine which review cycle the attachment belongs to? would you also list out how the field IDs in TDR_review should map to the field IDs in TDR_review_cycle_attachment? (attachment name, etc).


<img width="445" alt="Screen Shot 2022-01-07 at 8 47 54 AM" src="https://user-images.githubusercontent.com/14793120/148560760-db3effc9-a9c6-41a6-8efd-f04800a3d133.png">

**Comment by ChrispinP** [comment]
So interestingly, all but 3 of these attachments return an 'Internal Server Error' when trying to download. So im assuming these attachments became corrupted at some point. I made sure to connect them all to their respective Review Cycle and they now live in the TDR_review_cycle_attachment object now. Removing old attachment field.

This is complete.
