### ISSUE TITLE
Migrate Flowbird parking ETLs to prefect

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8068]
Migrate [this dag](https://github.com/cityofaustin/atd-airflow/blob/master/dags/atd_parking_data_meters_txn_history.py) to Prefect. It's running this [script/image](https://github.com/cityofaustin/atd-parking-data/blob/production/meters/txn_history.py).

**Comment by sergiogcx** [comment]
There is now a pull request: https://github.com/cityofaustin/atd-prefect/pull/1

**Comment by sergiogcx** [comment]
@johnclary @Charlie-Henry 

It looks like the first production run was successful:
https://cloud.prefect.io/dts/flow-run/83415f03-cfa3-4138-bc78-8d09fc3ec83c?logs

**Comment by sergiogcx** [comment]
I need a review to make sure that the data was in fact processed correctly, I do not know how to do that.

**Comment by johnclary** [comment]
@Charlie-Henry can you confirm for Sergio that the data is landing in S3 as expected?

**Comment by Charlie-Henry** [comment]
Data is looking good 👍 

Looks like it's not running anymore? Did we just do a test run?

**Comment by johnclary** [comment]
Yes, the Flow was not enabled. I just switched it on.
