### ISSUE TITLE
Meeting: DTS Service Delivery & The GEO/Maps Route

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#807]
### Objective:
Currently the Service Delivery Workflow doesn't expand beyond ticket creation.
* Should Map/Geo projects follow same workflow as all other projects?
    * Who will be the PM?

### Participants:
Jamie, Tracy, Amenity

**Comment by jaime-mckeown** [comment]
Meeting needs to be re-scheduled.

**Comment by TracyLinder** [comment]
Meeting has been rescheduled for Tue 11/12/2019

**Comment by jaime-mckeown** [comment]
- Tracy and I discussed on Tuesday. The GEO Team will keep handling our own requests.
- If a project level request comes through we will direct the customer to the Service Request Form and ensure they fill out the Project Request. These requests will go through Amenity, Tracy, and Jace for scoping.
