### ISSUE TITLE
[Enhancement] Allow admin users to access inactive and/or deleted accounts

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8081]
Currently, inactive users are hidden from the Staff page. It would be nice to have a toggle so that admins could access those accounts while troubleshooting or managing users. 
![Screen Shot 2022-01-03 at 10 12 52 PM](https://user-images.githubusercontent.com/1463708/148008686-0340891d-98f3-47c9-b3fa-b30c6af9dfb6.png)
 
If possible, also:
- [ ] Swap solid "edit" pencil on the lefthand end of each table row for the [outlined pencil icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aedit%3A) we are using elsewhere

**Comment by amenity** [comment]
@sergiogcx - this isn't urgent, but it will save time down the line if we are not relying on a dev to see archived user accounts.

**Comment by sergiogcx** [comment]
There is a PR:

https://images.zenhubusercontent.com/140626918/7195745e-c6d1-43d8-9b6e-d20fddd9d8a1/2022_01_06_07_54_45.mp4
