### ISSUE TITLE
Delete project data in Production

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8083]
Per discussion in backlog grooming, going to hard delete project data. 

- [ ] Create list of proposed tables to truncate... Generally,
    - Keep user accounts 
    - Keep look-up tables (e.g. Milestones, Roles)
    - Clear all project/project-related data
- [ ] Delete via UI, SQL script, or migrations...

**Comment by sergiogcx** [comment]
Sorry for the lack of enthusiasm for this issue during grooming guys, I'm just wanting us to be cautious. Happy to provide any support you need.

**Comment by frankhereford** [comment]
Prior to removing project and project related data in production, take careful back-ups in addition to our normal, automated backups to facilitate any sort investigations that may come up in the future.
