### ISSUE TITLE
Enhancement - TDS Portal [TDR] - Vision Team Dashboard and Review Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8089]
**Review Comment Details Update**
_Requested by stakeholders during a meeting on 1/4/21. Amber, Allison, Mike_

- [x] Add menu / buttons to navigate to Case Details and Review Cycle Details
- [x] Rename the page: Vision Team Comment Review Page
- [x] Add a reference section at the bottom
- [x] Add a table of all other reviewer comments, grouped by cycle #

**Comment by TracyLinder** [comment]
Hi @ChrispinP can you please add an estimate. I forgot to ask. Thanks!

**Comment by ChrispinP** [comment]
Vision Team Review Page create with updated sections for the Case, Cycle, & Comment sections.
![image](https://user-images.githubusercontent.com/67915167/149240086-ff52e6bd-a858-4932-81eb-f89419d4a55a.png)
![image](https://user-images.githubusercontent.com/67915167/149240181-e2d93290-4173-41ef-b4d4-620c188b2ce9.png)

As a child page of the Vision Team Dashboard, reviewers are now able to navigate back to their assigned or completed work without having to click the top navigation. The Case and Cycle sections display a connected link to navigate to either the Case Details or Cycle Details pages. All Review Comments Table shows all connected Review Comment records and sorts them by Cycle # > then Comment Status > then by Modified Date.

Im currently showing all sections in this example but each view would be hidden if blank.

**Comment by ChrispinP** [comment]
Updated Display and Page Rules, ready to review

**Comment by TracyLinder** [comment]
Meeting w/ stakeholders to review on 1/26/22

**Comment by TracyLinder** [comment]
We're meeting this afternoon with a few vision team reviewers for a quick UAT & demo.

**Comment by TracyLinder** [comment]
FYI @ChrispinP i just renamed this issue to Enhancement - TDS Portal [TDR] - Vision Team Dashboard and Review Page

**Comment by TracyLinder** [comment]
We need to train staff, update the table links, and then we can close this. 
@TracyLinder

**Comment by TracyLinder** [comment]
**Still to-do**
1. Review w/ stakeholders / everything working good?
2. Update the dashboard table links (remove most of them.)
![Screen Shot 2022-02-23 at 10.05.47 AM.png](https://images.zenhubusercontent.com/5cca1e522b8dfc0ee14dedf5/ec0948a8-f98b-4537-9f34-c99702365e1d)

**Comment by TracyLinder** [comment]
**Email to Eric B.**
_I'm hoping to update stakeholders at a team meeting if possible, vs creating a meeting just for this._

Hi Eric,

We're done with our updates to the Vision Team Dashboard and new review page. Do you know if there is a regularly scheduled Vision Team meeting i could attend to provide an update on this? 

Thanks,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
This is complete & delivered. Closing.
