### ISSUE TITLE
[Feature] Column Filtering on "Signal projects" Table

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8098]
The out of the box Material Table search component doesn't capture data from all columns in the "Signals projects" table. Most importantly, we don't have a way for users to search by "Project sponsor" or "Project type". 

Additionally, the basic search limits users to filtering on data in one column. At some point they will likely want more advanced combinations of filters. 

So let's try out Material Table's [filtering functionality](https://material-table.com/#/docs/features/filtering). 

Search ![Screen Shot 2022-01-05 at 8 02 07 PM](https://user-images.githubusercontent.com/1463708/148317132-1b93ea0e-49bd-4900-84a0-852c22698eb3.png)

**Comment by amenity** [comment]
@chiaberry - would it be possible for you to deploy a branch with the filtering turned on so we can show AMD?

**Comment by chiaberry** [comment]
@amenity https://8098-column-filter--atd-moped-main.netlify.app/moped/dashboard Here you go!

**Comment by amenity** [comment]
Pretty cool! 
![Screen Shot 2022-02-27 at 11 41 13 PM](https://user-images.githubusercontent.com/1463708/155930296-3d7edc7a-d747-4eed-a243-a947e8a499f6.png)

Unfortunately, the default filters don't work on the same columns that search misses—inline editable multi-select fields:
- Project types
- Task order
- Funding source
- Project sponsor

Users might ultimately prefer to turn off edit-in-place on those so that they could use them for filters. 😬

**Comment by amenity** [comment]
@chiaberry - Is there a way to adjust the configuration so that 👆 those columns are filterable? 

If not, AMD confirmed that the edit-in-place functionality on these fields is not as valuable as the ability to sort columns. So we can just disable that.
