### ISSUE TITLE
DTS Discovery Day 2.0

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#810]
Let's take a day to discover new tech! This is an opportunity to explore new software, libraries, and methods and apply them to a challenge facing our department. 

Some examples of things you  might do on discovery day:
- Test out a data visualization tool, such as PowerBI or Tableau
- Make a map  using a new ArcGIS Online  app template 
- Research how other organizations are managing and  communicating their product operations
- Learn a new programming language or code library

Folks are welcome to work in teams or on  their own. More details to come. Feel free to start adding ideas here.

**Comment by CodeMcConnell** [comment]
Is this for DTS or inclusive of participants from other ATD divisions?

**Comment by johnclary** [comment]
@CodeMcConnell let me check in with the team on this. want to make sure it's a safe space for them to explore crazy ideas. are you interested?

**Comment by CodeMcConnell** [comment]
> want to make sure it's a safe space for them to explore crazy ideas. 
That makes sense to me.
>are you interested?
I suspect that I will be slammed through the end of the year, so only hypothetically. I could see folks from System Design getting excited about this and making contributions.

**Comment by mateoclarke** [comment]
Closing this since we're now in 3.0
