### ISSUE TITLE
Update copy for renewal email

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8101]
Eliza will send Diana the new copy to update renewal email, which includes a line that warns users not select “auto-renew” because they will be charged when it renews.

**Comment by dianamartin** [comment]
Eliza sent email 1/10
## New - Email Template
![image](https://user-images.githubusercontent.com/21112975/148847586-46580b41-7597-4206-ae25-71d1434edaba.png)

## Renewal - Email Template
![image](https://user-images.githubusercontent.com/21112975/148847667-63aa8d7d-0937-45e0-aa32-fd9fca7c1cdf.png)

**Comment by dianamartin** [comment]
## Updated "New" email template
- [x] updated the email for new submissions
![image](https://user-images.githubusercontent.com/21112975/148848892-ca1850d2-baea-4e1a-9e79-f35c9ca0b3f8.png)

**Comment by patrickm02L** [comment]
@dianamartin MetroBike logo in our email is too big. Pleas shrink down to a similar size as what Eliza sent.

Also, the "Happy Riding!" text can come down a few sizes too. 

All I see is the logo, and Happy Riding!

**Comment by dianamartin** [comment]
@patrickm02L I had originally shrunk the logo, but it resized. I can try it again now that the email template is more in the final stages. I'll also reduce the text size for "Happy Riding".

**Comment by dianamartin** [comment]
@patrickm02L has Eliza seen the update emails yet?

**Comment by patrickm02L** [comment]
Thanks for sending her an email to review. Looks like she's out until Monday, 1/24/22.

**Comment by dianamartin** [comment]
Eliza replied 1/24
>Hi Diana,
Yes this all looks good, thank you!
