### ISSUE TITLE
Search by date and add a renewal email trigger 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8102]
Create a way for staff to search through records by date that are coming up on renewal, defined by a year from their redeemed date, so that they can trigger and email reminder to renew. 

- [ ] Search by date 
- [x] email button that sends renewal email reminder
- [x] status in table that shows when email reminder was sent 

This will satisfy function of #7885.

**Comment by patrickm02L** [comment]
@dianamartin please size. Planning to bring on to the next sprint, but if you have time you can pick it up earlier.

**Comment by dianamartin** [comment]
- [x] Created new page `Renewals`
- [ ] Added promo code table 
- [ ] Set up trigger
- [ ] Configuring renewal email
- [ ] Testing email and process

**Comment by dianamartin** [comment]
Emailed Patrick - 1/11
>Here are all of the new emails I tested, see attached. Also, the new renewal email is there.

He replied
>Yes! This is a go!

**Comment by dianamartin** [comment]
@patrickm02L I've configured a new page ["Renewals"](https://atd.knack.com/smart-mobility#manage-codes/renewals/) 
- the top table is a normal table that just lets the user user the "filter" button and use it to query. 
![image](https://user-images.githubusercontent.com/21112975/148992031-8d868f23-d06f-43f3-a776-e80f6619ddd4.png)

- the bottom table is a "search" table that I configured so the user can easily just enter From/To Dates to search for redeemed date and then can click the icon. 
![image](https://user-images.githubusercontent.com/21112975/148992160-ac32f1d3-9aff-4e5f-b25e-127b2a8c2fdf.png)

These are triggers to it will send an email as soon as you click it, so be careful on the second table. 
- FYI: You can resend an email (for testing purposes) by changing the "Sent Renewal Email" from "Yes" to "No".

**Comment by patrickm02L** [comment]
My vote is for Option #1 to filter by date, and/or other variables. We'll test with Eliza to get her preference.

**Comment by patrickm02L** [comment]
Updated Eliza Y. on 1/13. She choose Option #1.

**Comment by dianamartin** [comment]
The alternative table option 2 was removed and the chosen table configuration remains in the application.
