### ISSUE TITLE
Reconcile data for Go Live

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8103]
Before we Go Live we need to update the database in Knack to make sure that the most current data exists, which is where we’ll continue collect additional application data going forward. 

Before the launch time, we’re planning a 4-hour block of time where the application form will be down in order for us to:

- [ ] ~Delete all test data~
- [x] Import the latest applications spreadsheet
- [x] QC check with Eliza Y. to make sure accurate (associated correctly, have codes, etc.)
- [x] Make sure connections between tables are working 
- [x] Update email notifications to the correct email address (1/31)

Once this is complete we’ll active the form again to collect all the concurrent MetroBike Employee Benefit data.

**Comment by patrickm02L** [comment]
Tentatively scheduled for Friday, 1/28.

**Comment by patrickm02L** [comment]
Quoting from #7373

> We decided GoLive date will be Tuesday, Feb. 1st.
> On Friday, Jan 28th Diana will reconcile the data. Jan 31st, Eliza will QA/QC.
> Next NEO presentation is on Feb 17th.

**Comment by patrickm02L** [comment]
Send Eliza Y. email to let her know to put note on Sharepoint letting staff know that the Bikeshare sign up will be down until. @patrickm02L

If Eliza needs help with sharepoint @dianamartin can help, and to possible disable ATD forms.

**Comment by dianamartin** [comment]
Checked applications, since import there are `39` new applications in the ATD Forms DB
- [ ] import 39 records - records after M. Tang
- [ ] import 178 records - all of them

**Comment by dianamartin** [comment]
Sync'd with Eliza this morning - 1/28
- Made sure the SharePoint page was up to date and the link to the form was removed/disabled
- Checking to see if there were any applications entered since 1/26 when I imported the rest of the applications in
  - there were no new applications in the system

**Comment by dianamartin** [comment]
Messaged her 1/28
>So I checked and there were not applications submitted after 1/26. The last employee who signed up is Andrew M. I think it's safe for you to log in now and check the codes that you've sent and let me know if any need to have a different status or if you catch anything weird.  You can also do it on Monday.

Eliza replied
>Okay yeah I can check them this afternoon. I'll let you know when I'm done

**Comment by dianamartin** [comment]
@patrickm02L FYI

Eliza reviewed and found a code that is assigned to her, but she doesn't have an application record. She needs to create one and then associate herself to her code. 
She has 3 other promocodes that have 3 users without apps, she's going to fill them out for them. The emails in the system are still going to me. I'll switch them out on Monday after Eliza creates the application records. 

We had 3 other promocodes that were originally assigned to employees, but they moved to AE and redeemed or were assigned. We just removed the "Issue Date" on them. She'll talk to the BSA to see if they can still use those codes or not.

**Comment by dianamartin** [comment]
I manually entered on the back end and used their apps in the ATD Forms apps
- [x] Steve N.
- [x] Kaz W.
- [x] Jesse B.
We thought their Employee IDs weren't there, but they just weren't visible on the email that Eliza was being sent.

Will associate them to their promo codes.

**Comment by dianamartin** [comment]
Messaged Eliza - 1/31
>Okay, I switched out all the email notifications email
>- Switched new application confirmation email to ATD staff to - `bikesharebenefit`
>- Switched new application confirmation email to Customer to - Customer Email
>- Switched renewal application confirmation email to Customer to - Customer Email
>- Switched renewal reminder application confirmation email to Customer to - Customer Email
>- removed the "Admin Backfill" form
>- checked that all promo codes have an employee assigned to them

**Comment by patrickm02L** [comment]
Everything's good. No major issues from Eliza.
