### ISSUE TITLE
Enhancements: Banner Permits in Knack Application Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8104]
# Application page
- [x] For the field # of Banners Requested - maybe add some information that the # of Banners and # of Poles may be different (stakeholder can provide content)

- [x] Make Attachment field Not Required
 Add question Do you have your Banner Design ready?
Yes or No if Yes have option to Add Attachment

TEST THIS  
- Add Yes/"No" to app
- Hide Button/Table if "No"
 
- [x]  On the Location table change the column headings for Total Poles and Total Banners (stakeholder will provide content)
  - Action Item: Lauren will provide

**Comment by dianamartin** [comment]
### Attachment Bypass
Added "Submit Design' (Y/N)
Added "Option Chosen" (multi-choice)
- Yes - trigger, sets Option Chosen to Yes
- asks user to refresh page and add Banner Design
- No - redirect to a page "Add Banner Location'
App Review Details page 
if Option Chosen to No, hides the Attachment tables and Add Attachment Button

Page Rules need tweaking on this page

**Comment by dianamartin** [comment]
Emailed Lauren - 1/13 
>Just making sure we remember this action item. I’m checking in with you about if you’ve gotten a chance to work on updating the LPB Banner No. Poles/No. Banners table yet. In our last meeting we talked about indicating two numbers for pole/banners on the table. 
![image](https://user-images.githubusercontent.com/21112975/149399186-6699a03c-f9f8-4039-8472-ffc100c59cb8.png)
>I can update it whenever you’re done with it, just let me know!

**Comment by dianamartin** [comment]
Will follow-up with her on1/20

**Comment by dianamartin** [comment]
I just did the calculation for the Total Banners and it looks like this
![image](https://user-images.githubusercontent.com/21112975/150176792-d386acd3-f2c7-4119-84b7-13361926aff1.png)

**Comment by moorerst** [comment]
Will review enhancements with stakeholders in Sprint Review meeting scheduled 1/25

**Comment by moorerst** [comment]
reviewed enhancements with stakeholders during sprint review. No additional changes at this time will review in detail during user testing.
Closing issue
