### ISSUE TITLE
Enhancement: Banner Permits in Knack Review Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8105]
Review Page

- [x]  When reviewing the application is there a easy way to toggle to the Location Availability page to check the availability of the location the customer is requesting
 
- [x] Add Status Pending Customer Action with option to add Comments and email to customer

- [x]  Need workflow for allowing customer to update application with additional information while application is in Review status. No updates allowed after application is Approved

**Comment by dianamartin** [comment]
Added new status 
- [x] `In Progress: Pending Customer Action`
-

**Comment by moorerst** [comment]
Will review enhancements with stakeholders in Sprint Review meeting scheduled 1/25

**Comment by moorerst** [comment]
reviewed enhancements with stakeholders during sprint review. No additional changes at this time will review in detail during user testing. Closing issue
