### ISSUE TITLE
SOW Discussion with CityBase (1/7)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8112]
### Objective 
Talk about SOW Process for ATD

### Participants
Matt (CB), Jim (CB), Mark C (CTM), Eva (CTM), John, Diana

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
# Diana's Notes

**Horizon Projects**
- Accept payments for street banners

Technical Side
- Different options - `standard check out` v. `guided check out`

### Standard Checkout
- pass in invoice details
- amount owed
- line item information
- send to payment page and process a card or check transaction
- payment accepted
- web hooks to pass data back

**J Concerns:** 
- Have to set up middle ware to process post back hooks
- Set up a fetch, periodically query
- Remittance file (get transactions up until midnight), Can use Oracle DB

If we generate a link to them to have a confirmation page 
still having the concern for closing the loop - "the postback" 

CityBase said they can request a report it they need to confirm the payment
CityBase - confirmation email?
Confirmation page and confirmation email for details of payment

Eva: customers get payment and refund emails
Matt: Flipping on the web hook on the test environment, CB can turn it back off

On CB, they draft out statement of work
What they're going to do in the project 
They need to prioritize it and get it going

## Guided Self Checkout
Different workflow
CB is responsible for interface - entering bill number
Additional integration component
more of the workflow is managed by CB
They're integrating to an external system
Need to collect more information and facilitate the integration

We think the use case works best with standard checkout

CB: needs to go through approval process
use cases: parking ticket, one time utility bill payment

Eva: 3 depts using a file
- Public Works
- EMS (2 citybase flavors, reoccurring payment (profile checkout) and guided (one-time payment)

Let's proceed for a standard checkout.

We are added to the CityBase teams channel, but we'd love the docs again. 

## Next Steps
- Get Statement of Work done
- Get it into project queue
- Statement of work for standard checkout
  - writing to those specs to generate payment page and send payload
- Assign solution engineer will gather requirements

**Comment by johnclary** [comment]
thanks @dianamartin! 💯
