### ISSUE TITLE
Create sharepoint folder for external partners to upload files

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8116]
For the Signal Data Collection project Roadway Asset Services (RAS) needs a place to upload large image files so that they can be reviewed by our team.

**Comment by johnclary** [comment]
thanks @dianamartin for looking into this. would you let me, @andrewshensky and Christina know when it's ready?

**Comment by dianamartin** [comment]
Asked Christina on 1/7
>Hey, for the sharepoint site creation for Sign Data Collection. Did you guys want a new site created?
Also, do you already have external sharing capabilities?

She replied
>I feel like it should be a new site don’t you think? And do you mean does my sharepoint account have external sharing capabilities?

I said 
>did you ever turn in a request?

she said
>Not for this sign data collection site because we just talked about it this morning! I can definitely submit a request if I need to!

I said we'd catch up next week to make sure of the site decision and if she has existing external sharing capabilities

**Comment by dianamartin** [comment]
Messaged Christina - 1/10
>If you're free at 10:30 am, I wanted to chat about the external sharing capabilities for SharePoint

**Comment by dianamartin** [comment]
Sent follow-up message to user - 1/10
>Hey, I looked up the list for external sharing and I didn't see your name. I think we might've talked about it but you never actually submitted it. 
Click the `1.` on the site to fill out the form and it should go to me. When you get added to the security group you will have the POWER..to shared a file, folder or site with external users. This is the training [slides](https://cityofaustin.sharepoint.com/sites/O365/Training/SPES/SitePages/Home.aspx) you need to go through to understand what you can/can't share..etc.

**Comment by dianamartin** [comment]
I confirmed in ServiceNow that Christina's request was "In Progress". Sync'd with Christina and created the new site "atd_SignDataCollection".

**Comment by dianamartin** [comment]
Christina was granted access on 1/21, she reached out to Danny because she was still unable to share the site. 

She said
>I just followed the instructions on the SharePoint External Sharing How-To and I’m still unable to share a folder with an outside vendor. This is the message I’m getting:

He replied
>Currently the ATDHub does not allow external sharing. If you wish to have the site enabled for external sharing, the site Owner will need to submit a request to enable the feature. The current site owner is Diana.

**Comment by dianamartin** [comment]
Received CTM confirmation that the ATDHub had been granted external sharing. 

I had just tried to add the contractor emails and they still didn't work so I was confused, so I messaged Danny to ask. He said I already had external sharing rights, but the ATDHub site had just been granted them. 

The issue is we needed `atd_SignDataCollection` to be granted external sharing. 

Danny and I are communicating which site needs to have external sharing on it. I said
>the site `atd_SignDataCollection` is the site that the external folks will need (folder access) to drop images into for QC

**Comment by dianamartin** [comment]
I tried to add the email for the external stakeholders and wasn't given an error message. 

Messaged Christina that I was able to add them. 
![image](https://user-images.githubusercontent.com/21112975/151574561-199ea475-53fe-42db-b7b8-ff626add4abd.png)
