### ISSUE TITLE
Present DTS Product/Project prioritization framework to management team

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#812]
Monday, 2/3
[Deck](https://docs.google.com/presentation/d/165UiyTGnph8H8LNcvU4mN3QoJHWqKrh5qz2pefX0MFI/edit#slide=id.p)

**Comment by amenity** [comment]
Notes:
- Subset of management team could be available to score projects - 
- Jim: Also consider resident-facing
- Karla: Marketing initiatives that require pivots; e.g. Ford plan could become political priority - not necessarily 
- Nathan: How do you consider what CTM 
- Lewis: In addition to ASMP, add in Rob's quarterly goals
- Jim: Having customer be part of prioritization process so they 
- Rob: There needs to be an "override" button 
- Jim: Always looking back to "Why did we move away from CTM?" 
- Jason: Does project age factor in, e.g. how long something has been in the backlog? 
- Jen: E.g. warehouse Inventory - interested to see how some of these "in-the-weeds"
- Rob: There needs to be a way to say "We're not going to do this, kind of an irritant, brilliant idea but moonshot, not going to happen

To-do:
- Please share presentation

**Comment by amenity** [comment]
@johnclary - reminder to slap your notes up here. 🤾‍♀
