### ISSUE TITLE
[Bug] Reimbursable columns were lost when Knack restored older data

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8126]
We had added reimbursement fields on the "edit reimbursable forms" but never added them to the Sign Reimbursement table or Markings Reimbursement

**Comment by dianamartin** [comment]
Signs Reimbursement table
Added fields
- [ ] Batch No
- [ ] Contract Labor Vendor
- [ ] Contract Labor Vendor No.
- [ ] Labor Invoice Date
- [ ] FM Budget
Removed
- [x] RT_ID

**Comment by dianamartin** [comment]
Closing, this issue as it's been resolved.
