### ISSUE TITLE
Document and clean up the way total est comprehensive cost is computed

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#8130]
Adrien brought up some question about total comprehensive cost and where these values live in the VZ database.

Currently, the main source of truth for total comprehensive costs comes from [this SQL query](https://github.com/cityofaustin/atd-vz-data/blob/c1e90b5561ce600facb005cd5c7f1fec0e359fc8/atd-vzd/triggers/get_location_totals.sql
) that powers the Locations index page. This was updated most recently by Frank in [this view](https://visionzero.austin.gov/editor/#/locations). Previously, we relied on view called `view_location_injry_count_cost_summary` to power this page. It seems like this old view is no longer being referenced and may be database cruft.

We need to understand if there is any other cruft in our database related to comprehensive cost. This may include some SQL functions, columns (ex: `total_comprehensive_cost` on the Locations table), or views.

We should document the current process and methodology for producing total comprehensive cost values and evaluate if we need to make any improvements either for database navigation or VZE performance

**Comment by patrickm02L** [comment]
When assigning consider making an epic for maintenance and clean up for database cruft.

**Comment by patrickm02L** [comment]
## 10/30
This Issue is no longer valid. Milad has made changes and is managing the comp costs in the [GIS Crash Data by Location](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=981b687bb68d465cab737792bbf56198) map.
