### ISSUE TITLE
DTS Virtual Retreat

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8131]
### Objective 

Design and organize a meeting that specifically facilitates the ability for the team to step back from their day-to-day demands and activities for an extended period of concentrated discussion, dialogue, and strategic thinking about the organization's future or about specific issues.

### Participants

Everyone in DTS.

**Comment by dianamartin** [comment]
@patrickm02L here are some ideas I looked up and liked :)

# Ideas
- dress up in matching colors (Team Red, Yellow, Blue, Rainbow)
- dress up in theme.. (Animals, Hero, Crazy Hair)

## Games
- draw phone
- trivia/quiz
- Digital Scrapbooking (Miro board)
- Video Charades
- Virtual Scavenger Hunt
- Guess the refrigerator
>This one gives a playful look into the personal spaces of team members. Each member takes a picture of the inside of their refrigerator or a snapshot of their home workspace and posts them in a dedicated group chat. The other team members review the images and offer their best guesses at which image belongs to which member. A great opportunity for the team to tidy their desks and fridges, if it’s been a while since they’ve done so!

## Team building - (everyone must participate..)
- Show & Tell (to tell share something new about something in your life that others may not know about you) something you think your colleagues can relate to
  - Photo of your life: 
>Each team member is tasked with summing up their life in an image taken on their phones. It could be a location, a landmark, a favorite object, a chosen hobby or a beloved pet. Then the image is shared with the rest of the team with an explanation of the significance and story behind the image. This is a thoughtful way to present a more personal side to the team members who may not know much about one another, and a fun way to put your personal technology to work for a professional team-building purpose.
- Talent Show?
- Pair up and coffee talk
- Pitch Me
>Another creative challenge. The event leader assembles a slide deck of interesting items, and workers broken into small groups cycle through the images to give their best sales pitches for the items. How would someone sell a carrot peeler, for instance, or a propeller beanie, or a corkscrew? Encourage players to use their online tools and technology for research to refine their pitches and have them collaborate on PowerPoint presentations, TikToks or quick video ads to put their best pitches forward.

**Comment by amenity** [comment]
On my to-do list since last retreat: 
> Groom ["Influence & impact" ideas from strategy](https://miro.com/app/board/o9J_lP-Ptfg=/?moveToWidget=3074457356031249371&cot=14) session

Hope we can move forward with strategic planning!!

**Comment by patrickm02L** [comment]
Met with Diana on 01/21/22. 

We discussed a general format that would focus social activities across teams, reviewing past expectations, setting new expectations, and how to celebrate and reflect on the amazing work we've done over the last year. 

We're looking at a day-long time commitment late March/early April for a Spring Retreat, and the potential of incorporating outside facilitators.

Action Items include
- Build a simple survey to ask what team members want from a retreat @dianamartin
- Create a doc that recaps the history of the last retreat, and ideas for strategic planning @dianamartin
- Investigate what working with Honker would look like @patrickm02L
- Review Strengths Finder evaluation @patrickm02L

**Comment by dianamartin** [comment]
- [x] Created draft survey for DTS team

**Comment by dianamartin** [comment]
- 1/26: posted survey to slack channel
- 1/31: posted reminder to slack channel
- 2/1: deadline for feedback

**Comment by patrickm02L** [comment]
DTS Retreat scheduled for Friday, 4/8/22.

**Comment by patrickm02L** [comment]
2/25/22 - worked through agenda and and icebreakers. For meeting on 3/4/22 suss out details of 3 sessions sections of the agenda.

**Comment by dianamartin** [comment]
# Notes from 2/25
- Actions: we finalized social activities and ice breakers
- Drawphone? fit in at lunch (optional)

## To Do
- Create Doc for Agenda details
- Go through the sessions in depth (next time) 
- Timeline estimates: for how long things will take
- Timeline for email information for team, week of April 1st

**Comment by patrickm02L** [comment]
Retreat happened on 4/8/22. Everything is captured in this [Miro board ](https://miro.com/app/board/uXjVON1-NDE=/). Need create a follow-up meeting to go through the Team Roadmap.
