### ISSUE TITLE
Feature: Enable exporting on School Zones data table

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8138]
Jorge G
AMD

Messaged me 1/11
>I have an issue with exporting the school zones from Data Tracker.

I replied
>Hey, what's happening?

he said
>we cant do it. it does not give us the option.

**Comment by dianamartin** [comment]
I checked the table/page and it was not enabled. I enabled the page with the export functionality. 

Messaged user
>Okay, refresh your page. I've enabled the exporting on that table

**Comment by dianamartin** [comment]
He replied
>um still not working for me. maybe i'm doing something wrong.
I just sent you a meeting invite for tomorrow. We can discuss then.

i replied
>okay, talk to you tomorrow

**Comment by amenity** [comment]
Was on the wrong table; fixed now.
