### ISSUE TITLE
Meeting to Discuss Plan for Sign Assets QA/QC Process

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#8141]

**Comment by andrewshensky** [comment]
- Discussed issues in pilot data we have found so far (will be documented in a group shared document Christina created)
- Awaiting photos from RAS, once we receive them we will need to figure out process to associate with proper features
- We need to establish rules for which feature scenarios can be incorporate into master dataset and which will need to go through QC. This could help to reduce backlog
- Discussed potential need for tech to ensure long term maintenance and reliability of data (Since October over 2,000 signs installed or removed and would likely need QC )
- I will be putting together QA/QC ArcPro Template for Christina and Susanne to make a copy of for data editing

**Comment by johnclary** [comment]
@andrewshensky can you estimate the volume of what the manual QA/QC counts will be?

**Comment by andrewshensky** [comment]
I will be closing this issue. Manual QA/QC volumes will be track in issue #8165.
