### ISSUE TITLE
Meeting with MetroBike Vendors

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8145]
On 1/13/22, demo the MetroBike employee benefit app for vendors to show them how to login and redeem codes, and get their input for the best way to import new codes.

**Comment by dianamartin** [comment]
# Diana's Notes

- Import bulk promo codes sent to ATD Staff twice a year (once every six months)
  - as needed
- Vendor redeems once a month
- Vendor needs
  - [ ] Ability to Backdate "Redeemed Date"
- Redeem date trigger icon not needed

### Reporting
- Number of Redeemed codes
- Number of Assigned codes

**Comment by patrickm02L** [comment]
BSA contact email for Vendor sign-on is: contact@bikeshareofaustin.com

**Comment by patrickm02L** [comment]
Sent follow up email 1/18 with instructions for logging in to the redeem codes page.
