### ISSUE TITLE
New AGOL Accounts in AMD (Signal Shop)

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#8147]
Charles told me that there is at least one new person that needs an AGOL account. Sent Edward an email asking for a list of all new people.

**Comment by jaime-mckeown** [comment]
- received list from Edward
- emailed people that need AGOL accounts with instructions

**Comment by jaime-mckeown** [comment]
Account setup:

- [ ] Miles M.
- [ ] Lawrence R.
- [ ] Lance C.
- [ ] Gabriel M.
- [ ] Richard G.
- [ ] Sray W.
- [ ] Randy P.
- [ ] Jimmie J.
- [ ] Rudolph V.
- [ ] Andrew C.
- [ ] Gene P.
- [ ] Francisco G.
- [ ] Roman P.

**Comment by johnclary** [comment]
If additional folks need access, Charles will need to let us know. They need to create accounts.
