### ISSUE TITLE
Test ability to provide distinct work order views based on workgroup

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8149]
Brian C asked if it was possible to only show the AMD components based on the work group signed in. I was going to test it out and figure out if it's possible.

**Comment by dianamartin** [comment]
I created a connection to "User Role" - Technicians then added my name individually beside the components. I was able to filter based on that relationship on the form field. 

The user only sees a limited selection of components

**Comment by dianamartin** [comment]
Showed stakeholder and suggested to try to filter by work group first. Testing adding work group.

**Comment by dianamartin** [comment]
Created new object `amd_workgroup` and added:
![image](https://user-images.githubusercontent.com/21112975/150431558-3779e598-4e2f-4d64-87f2-16b41aba8aec.png)

Set components on `work_order_signal_components` object table to the "amd workgroups" and added the "amd workgroups" to the "Work Completed" form and it filtered it!

Group | Component Selections |
-- | -- | 
AMD Staff | ![image](https://user-images.githubusercontent.com/21112975/150432001-9515ba79-b384-47c4-af14-65c8b041380e.png) |
Non-AMD Staff | ![image](https://user-images.githubusercontent.com/21112975/150432113-f60277cb-3112-4a9f-adf8-fbfe22aa3c82.png) |
Technicians | ![image](https://user-images.githubusercontent.com/21112975/150432171-fb897996-4b6d-404c-8853-5965ab34d991.png) |
Inspections | ![image](https://user-images.githubusercontent.com/21112975/150432206-4307e479-7dfd-429d-a498-d451b5b84357.png) |
Timing Engineers | ![image](https://user-images.githubusercontent.com/21112975/150432242-a6b33728-1022-416a-9b69-80cd8b1fd038.png) |

**Comment by dianamartin** [comment]
Showed this off to stakeholders at last meeting 1/24 for "Maintenance Work Order Discussions". Stakeholders will have to define what components each work group can access.
