### ISSUE TITLE
Work with CTM to update SMB Airwatch profiles

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8150]
Areas that need improvement: 

- Time to load websites
- Accessory attachments (keyboard, weatherproof casing, pens(?))
- Photo/Camera quality
- File storage size
- Intuitive UI (how easy is it for the user to select apps)
- Viewing PDFs
- Battery Life
- SSD

**Comment by amenity** [comment]
Since #7850 wasn't fruitful, going to try updating the Airwatch profiles.

**Comment by dianamartin** [comment]
Set up work session on 1/18 to determine what SMB needs for hardware (reoccurring pain points) and what technician profiles should be able to do. 
- Discuss w/ CTM as well for recommendations on updated profiles

**Comment by dianamartin** [comment]
# Discussion with Christina about new profile and next steps

## Profile Needs
Have the ability to 
- being auto signed in Admin mode or not having an admin mode and allowing users to function without it
- have profile to auto download apps to tablet
- have users open attachments easily
- installed new apps from COA App Catalog
- have access to camera app and photo gallery
- still assigned to named user


## Next Steps
- [ ] See if AW would consider lending tablet for testing current AirWatch configuration and new AirWatch Configuration
- [ ] Upgrading MiFis (Supervisors & OPALS) 
- [ ] Upgrading in FY 2023
- [ ] Asking WPD, DSD tablet usage

**Comment by dianamartin** [comment]
Emailed AW contact - 1/24
>I’ve approached CTM and we’ve asked to see if they still loan out hardware prior to purchase and they said they don’t do that anymore. Would there be any possibility to loan out a tablet that is and iOS (ipad mini)? I know we discussed a possibility, but I know you have to ask your management chain if it’s possible. 

>The Signs and Markings Division operational and planning team (Christina and colleagues) would like to test out our current AirWatch profile on the tablet. We’re also looking into creating a new profile and hoping to test that on the tablet too, if we are able to borrow one. Once we can assess the user experience on an iOS device, their division can budget for purchasing these kinds of tablets in the next fiscal year. 
>- Let me know if there is even an remote possibility.

**Comment by dianamartin** [comment]
Set up meeting with Danny & Christina

**Comment by dianamartin** [comment]
# Discussion Notes
A lot of changes and processes
Strongly look at new hardware

Ease of use - success with iOS devices
easier to manage and enroll
experience over the last few years android has had more issues in the past
iOS is more stable

- Can for go the admin mode
- All the apps are there on the device
- Layout can be not used
- Bypass the "Launcher" 

Redesign and development on the launcher
new launcher version

-

**Comment by dianamartin** [comment]
Ping John S. next week 2/7, to see if he's had time to ask his supervisors.

**Comment by dianamartin** [comment]
Talked to John S (AW) - 2/8
He asked his upper management and they said they won't be able to loan out devices. 
- They said that they had trouble getting iOS devices and pair them with GPS unit (they don't want to split them)
- Wouldn't be able to split up the bluetooth units
- Steve suggested to: buy one $650 for testing.. John S. disagreed
- Recommended lifecycle 3 years, for AGOL software compatibility but I think we can get by with a 4 year device refresh

**Comment by dianamartin** [comment]
Emailed Danny 2/23
>Just seeing if you had a chance to create those two test AirWatch profiles for the Signs and Markings Division. We talked about creating two new profiles for testing:
•	"Signs and markings Test – New launcher" with launcher (the same apps that exist on the profile but be in Admin Mode all the time)
•	"Signs and markings Test" without launcher (a super non-locked down version and a version but the same apps that exist on the profile would be downloaded to it)
Let me know if you prefer that I put in a ServiceNow ticket for this as well.

**Comment by dianamartin** [comment]
I put in ServiceNow ticket 3/8
>Please create TEST profiles 
• "Signs and markings Test – New launcher" with launcher (the same apps that exist on the profile but be in Admin Mode all the time) 
• "Signs and markings Test" without launcher (a super non-locked down version and a version but the same apps that exist on the profile would be downloaded to it)

**Comment by dianamartin** [comment]
Danny messaged me 3/15
>FYI.. I Started working on the new launcher environment on Friday (3/11)
Thank you for the reminder
I am hoping to have it ready by some time tomorrow, if distractions do not happen 

I said
>Thank you! 

he replied
>the new android is almost complete and we can enroll one of the device
that said, I do want to have a conversation on exactly what is needed to make sure everything is functioning as expected.
When your ready, you can enroll a device and we can meet and test all the functions 
the tether app, I believe will no longer be required 
(pasted QR code for new Test Signs and Markings)

I messaged Christina 3/15
>Danny has the new test Signs and Markings profile ready, we can add it to the Android device
- [x] Sent VMWARE TEST PROFILE SIGNS MARKINGS doc

**Comment by dianamartin** [comment]
Need to follow-up with Christina to see if she was able to set-up the tablet and then schedule time with Danny to see what he wanted to test on the new profile

**Comment by amenity** [comment]
Christina hasn't had time to review. @dianamartin - please schedule time.

**Comment by dianamartin** [comment]
We are tentatively planning for Wed afternoon 3/30

**Comment by dianamartin** [comment]
did the remain testing tasks on #8797
