### ISSUE TITLE
Migrate Traffic Reg Data to GISMAINT

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8153]
Move the traffic regulation data from FGDB to GISMAINT.

**Comment by ChristinaTremel** [comment]
@andrewshensky also checking in on this issue (related to [8285](https://github.com/cityofaustin/atd-data-tech/issues/8285))

**Comment by ChristinaTremel** [comment]
Traffic reg data was migrated to Maint!
