### ISSUE TITLE
Meet with Nathan W. to review traffic regulation GIS data

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8154]
I'd like to review the reg data with Nathan and discuss how best to maintain it in coordination with the Traffic Registry 2.0 (Knack) project.

@alan-deanda please include the geo team plus me and Chispin.

**Comment by alan-deanda** [comment]
We met yesterday, 02/02/2022.

I need to re-create the traffic registry in MAINT from all the regulations that AECOMM digitized, not just the ones that had QA issues. This will result in one line feature class for all line-type regulations and one point feature class for all point-type regulations. Once this data is created and QA-ed, it will go up on AGOL, and a viewer with useful filters will be created to help staff view and update the geometry from the traffic registry as found in tabular form in knack.
