### ISSUE TITLE
2022 Print Bike Map

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8156]
- Send reminder on Feb 1 and Mar 1 (Include Sean C and Laura D)
- Mid March: notify ATSD that final review period ends on 4/1
- Deliver PDF week of Apr 1 (estimated)

**Comment by johnclary** [comment]
Todo:
- Process this month's updates
- Re-share the comfort level verification web-app to capture ATSD edits

**Comment by johnclary** [comment]
Met with Sophia—they are reviewing the data and deciding on final geometry changes to include. Sophia will schedule the next meeting to review feedback on comfort levels, probably as a work session to make live edits together to finish things up.

**Comment by johnclary** [comment]
Final version of map has been reviewed with ATSD. Waiting for confirmation that it has been sent to print.

**Comment by alan-deanda** [comment]
The print bike map 2022 is out!!
