### ISSUE TITLE
Use new (stable) Moped vector tile endpoint

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8157]
Update the ArcGIS Online layer endpoints for street lines and intersection points. These are stable endpoints that will be updated periodically by our trusty GIS folks.

### Streets

Defined in Moped config [here](https://github.com/cityofaustin/atd-moped/blob/a26e2850b243879f166a0d9d76c20647eeb05a64/moped-editor/src/utils/mapHelpers.js#L139). 

New tile layer endpoint
```
https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/CTN_Segments_MOPED/VectorTileServer
```

### Points 
Defined in Moped config, [here](https://github.com/cityofaustin/atd-moped/blob/a26e2850b243879f166a0d9d76c20647eeb05a64/moped-editor/src/utils/mapHelpers.js#L185).

Tile layer endpoint
```
https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/CTN_Intersections_MOPED/VectorTileServer
```

### Streets feature service

Defined in Moped config [here](https://github.com/cityofaustin/atd-moped/blob/a26e2850b243879f166a0d9d76c20647eeb05a64/moped-editor/src/utils/mapHelpers.js#L70).

Layer endpoint
```
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/CTN_Segments_MOPED_FS/FeatureServer/0
```

**Comment by johnclary** [comment]
@andrewshensky plz ping @amenity when this URL is ready. not urgent

**Comment by andrewshensky** [comment]
@amenity The URLs to the Vector Tile layers that will have stable locations are below:

**Segments**
AGOL Data Location
https://austin.maps.arcgis.com/home/item.html?id=e044fcb58d95470c871aa2040085b9e9
Service URL
https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/CTN_Segments_MOPED/VectorTileServer

**Intersection Points**
AGOL Data Location
https://austin.maps.arcgis.com/home/item.html?id=57d5dce0d2f44aaeb00c5d3436780282
Service URL
https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/CTN_Intersections_MOPED/VectorTileServer

Let me know if anything else is needed or if any changes/modifications need to be made to the data.

**Comment by amenity** [comment]
@andrewshensky 🙌  rad, thank you! @johnclary - shall I create an issue to update these URLs in Moped?

**Comment by johnclary** [comment]
thanks @andrewshensky!! I updated the issue description and removed you from assignment.

@amenity this is nice-to-have for v1.0.

**Comment by johnclary** [comment]
@andrewshensky I just remembered that we also rely on a CTN _feature service_ for the segments. 

[This](https://austin.maps.arcgis.com/home/item.html?id=d73703dbcea248e6ab878e20ec2382f8) is the current service we use.

So we'll need a stable feature service for the segments that is also updated whenever the tiles are updated. This was no on your radar, correct?

**Comment by andrewshensky** [comment]
@johnclary I was thinking MOPED only relied on the vector tiles so thanks for letting me know this. I will set up and test this workflow for a new feature service. Once everything looks good, I will add the new feature service url to this issue.

**Comment by andrewshensky** [comment]
@johnclary and @amenity the feature service below will be updated as part of the monthly CTN update process. We can overwrite the service each month with the updated data and the url will remain stable.

**CTN Segments Feature Service**
Location in AGOL
https://austin.maps.arcgis.com/home/item.html?id=24455c781dbd48669c601ede4b365d1f
Service URL
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/CTN_Segments_MOPED_FS/FeatureServer/0

**Comment by johnclary** [comment]
thanks @andrewshensky! @chiaberry this is ready to gooooo

**Comment by andrewshensky** [comment]
@johnclary and @chiaberry Both the Segments vector tile layer and the feature service have been updated to replace PROJECT_EXTENT_ID with CTN_SEGMENT_ID. The URLs should not have changed but I have included them below:

**Feature Service**
AGOL Location
https://austin.maps.arcgis.com/home/item.html?id=24455c781dbd48669c601ede4b365d1f
Service URL
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/CTN_Segments_MOPED_FS/FeatureServer/0
![image](https://user-images.githubusercontent.com/80716478/151603212-2e66f2e5-fed4-4a30-935f-5a8a00c0d4b7.png)

**Vector Tiles**
AGOL Location
https://austin.maps.arcgis.com/home/item.html?id=e044fcb58d95470c871aa2040085b9e9
Service URL
https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/CTN_Segments_MOPED/VectorTileServer
![image](https://user-images.githubusercontent.com/80716478/151603547-8bb52828-1d1d-40ee-9da5-7f776ee9a9b6.png)
