### ISSUE TITLE
Refine delete/inactivate user account interface 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8158]
- [x] Remove status inactive/active toggle
- [x] Rename "Delete" "Inactivate"
- [x] When deleted, button becomes "Reactivate"

**Comment by amenity** [comment]
@sergiogcx - when a user is deleted, the expectation is that 
- They can't log in w/ SSO
- Their name stays in place in any existing comments/projects
- They are not available as an option in the "Project team" pick-list

**Comment by sergiogcx** [comment]
Done, just needs testing. I am not sure I've done the reactivate part correctly yet. Will retake the efforts tomorrow.
