### ISSUE TITLE
Perform dependabot updates for Moped 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8161]
- [Updates](https://github.com/cityofaustin/atd-moped/security/dependabot)
- Can use [this script to test](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=1866883478)

**Comment by johnclary** [comment]
Closing this since we generally keep up with these now.
