### ISSUE TITLE
ROW Permit FDU Infos Need to be Alphanumeric (RE-UAT on PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8166]
Per Ryan & Peggy, all funding info fields need to accept alphanumeric values. Currently only numeric is allowed. 

Applies to: TURP, EX, UC, GF

**Acceptance Criteria** 

- The changes provided below applies to folder type RW with subtype Temporary Right of way Use and folder types EX, UC and GF. 
- In all the folder types mentioned above, the following folder infos are already displayed under Info group 'Cost of Service': 
-- Fund (90001)
-- Department (90002)
-- Unit (90003)
-- Object (90004)
-- Activity (75078)
- Currently, the info type for all these infos is Numeric. This should be changed to Alpha in the admin configuration.
- Currently, there is a validation on these infos to allow only a maximum of 4 characters. This should be maintained even after changing info type.

**Comment by TracyLinder** [comment]
**Email to stakeholders:**

Howdy,

Following up on this. Should I try to get this pushed through the code freeze? We are allowed to do updates for urgent fee or bug related requests. 

Thanks,

**Comment by TracyLinder** [comment]
@vschandramouli can you please add AC to this? Do you think it could be done by tomorrow (Friday) afternoon?

**Considerations**

- All 5 FDU related fields need to able to accept alphanumeric values.
- Each value should be 4 characters
- This needs to be updated in all the folders: EX, RW-TURP, GF, UC

**Comment by vschandramouli** [comment]
@TracyLinder  Sure. I can work on this and have it done by tomorrow morning to review.

**Comment by vschandramouli** [comment]
@TracyLinder  I updated the AC, moving to backlog. Please review if needed. 

CC @Nadin-Nader

**Comment by TracyLinder** [comment]
@vschandramouli can you please add the info 'Activity' to the AC

**Comment by Lpriya-LIT** [comment]
@TracyLinder Please confirm whether this error message looks good if the character limit exceeds 4

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/ac693b13-7d6c-48f3-9289-8a85e238014b)

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/5bdcf77e-969b-4da5-9c99-62fb8fd8f451)

**Comment by TracyLinder** [comment]
@Lpriya-LIT @Nadin-Nader this looks great. Please promote.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to the DevOps CM Team to deploy to **_DEV_** under **SCTASK0195056**

**Comment by Nadin-Nader** [comment]
##  **APPROVED for **PROD** Deployment🎉🎉

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team to be deployed to **__PROD_** under **SCTASK0195131**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder  Deployed to Prod

**Comment by TracyLinder** [comment]
I just tested this on portal, the system does not allow alphanumeric values, so this must have been rolled back. 
FYI @Nadin-Nader

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes were re-applied in Test, Verified. Working fine

**Comment by TracyLinder** [comment]
### PROD UAT PASSED 🎉
_I'm closing this._
