### ISSUE TITLE
Write & submit position descriptions

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8177]
[Template](https://docs.google.com/document/d/1PW8Y3S7AzpEZ0jRhvhYvtJEEe7Fb7MUXzVt1wbhrNhE/edit?usp=sharing)

**Comment by patrickm02L** [comment]
@amenity here's the [draft](https://docs.google.com/document/d/1Ns8jiDa6Gzj9cRYJi4J7-Z65kyp0k07rIAYIHV5cbvM/edit?usp=sharing) for the Designer role.

**Comment by mateoclarke** [comment]
Dev draft [here](https://docs.google.com/document/d/1ZZhlT9SpYfC3Js43v0bAo0_qfXLgnEBnkDg_bfILYpo/edit?usp=sharing)
