### ISSUE TITLE
Utility Coordination (UC) folder Sent Email after the Permit Completeness Check is done needs a Correction (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#8180]
##  Utility Coordination (UC) folder Sent Email after the Permit Completeness Check is done needs a Correction

Stakeholder: Jaclyn Lozano

The generated email comes from the UC folders, this email is sent after the process PERMIT COMPLETENESS CHECK is completed.

**Correction needed:**

-  2nd line, Coordination is spelled incorrectly twice. Extra 'n'.. See below:

> Subject: [TEST] Austin Utility Location - **TEST E-MAIL. PLEASE IGNORE**
> 
> **TEST E-MAIL. PLEASE IGNORE**
> 
> Hello: 
> Thank you for your submittal to the Austin Utility Location and Coordinantion Committee (AULCC). Your ROWMAN Utility _**Coordinantion**_ Application has been scheduled.
> 
> AULCC Meeting date: 01-DEC-21
> Meeting Location: **Meeting Online via Microsoft Teams. You will receive an email invitation with the Teams link and optional call-in number at a later date.**     
> Meeting Starts: 2pm 
> 
> Please review your information.  
> If any data needs to be revised, added, or deleted; Please contact: 
> Isaiah.Lewallen@austintexas.gov, Jaclyn.Lozano@austintexas.gov, and AULCC@austintexas.gov
>

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0193658**

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/f01f5b3d-044e-47a5-9cec-02d7c1b90909)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Dev, The email content has been updated. Ready for Test promotion

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to the DevOps CM Team to deploy to **_TEST_** under **SCTASK0194533**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been deployed to **TEST**. Please UAT on TEST

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in test, Ready for Prod

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0194784**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Promoted to Prod on 1/21/2022

**Comment by Nadin-Nader** [comment]
This was deployed to PROD 1/21/22 (Friday)
