### ISSUE TITLE
Store record information in atd_txdot_changes table as JSON instead of string

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#8183]
Tech debt that should be addressed:

In the `atd_txdot_changes` table, "The JSON object `record_json` is a valid JSON field, but it’s currently populated with a `String`ified copy of a JSON Object". 

The information is processed here https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/app/process/helpers_import.py#L555, 
` new_record_escaped = json.dumps(json.dumps(new_record_dict))`.  

We would need to test removing the outer json.dumps, update the existing records and update the SQL view that uses atd_txdot_changes. 

edit 2/28/24: the correct line of code is now here: https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/cris_import/lib/helpers_import.py#L40

**Comment by johnclary** [comment]
you guessed it: this will be fixed in the new data model's change log tables. 

folks, we 9 change log tables (and counting) in the new data model! wowee
