### ISSUE TITLE
BUG: ROW CASE REVIEW MANAGER process (51095) - When REJECTED, it is openingBUG: ROW CASE REVIEW MANAGER process (51095) - When REJECTED, it is opening up ALL of the processes in red on the UC Folder (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#8187]
## As a Permit Review analyst for the UC folder, when the ROW CASE REVIEW MANAGER process (51095) is "Rejected", AMANDA is opening up a lot of other different Processes as well. This needs to stop as it is causing issues and confusion

Stakeholders: Jaclyn L., Greg P., Isaiah L.

System Should **_NOT_**:
-  Open Up any new Processes when a "Rejected" attempt is entered on the ROW CASE REVIEW MANAGER process (51095)  process

Examples:
21-049141
21-049161
21-005515 (from Isaiah)

[https://app.zenhub.com/files/140626918/32b4ee76-1bb5-43e6-9cd5-445828729945/download](https://app.zenhub.com/files/140626918/32b4ee76-1bb5-43e6-9cd5-445828729945/download)

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to the DevOps CM Team for deployment to **_DEV_** under **SCTASK0194513**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT  This has been deployed to **DEV** Please UAT

**Comment by Nadin-Nader** [comment]
**Status:**
Per StandUp this is ready to be deployed to TEST

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0194782 **

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/3bb717f0-08f2-474c-838b-f2bd8290b0c4)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Added a screenshot from Dev. Rejected attempt is done in 51095 process and review processes were not open/ inserted

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes promoted to Test, works as expected

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0195037**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Deployed to Prod

**Comment by Nadin-Nader** [comment]
Verified with Isaiah and this is good to go, Closing

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test, Changes have been re-applied. Working as expected

**Comment by Nadin-Nader** [comment]
**Status:**
Sent this to get Redeployed to **PROD** from Rollback items under **SCTASK0201315**

**Comment by Nadin-Nader** [comment]
Sent email to stakeholders informing them that this is now on PROD. Closing on Wednesday 2/23/22.

> Email:
> Hello,
> Hope everyone is doing well. I wanted to reach out and inform you that the ROW CASE REVIEW MANAGER process (51095) - When REJECTED, it is opening BUG: ROW CASE REVIEW MANAGER process (51095) - When REJECTED, it is opening up ALL of the processes in red on the UC Folder, card # 8187 is now back on PROD.
> Please let me if there are any issues with the deployment or if any new ones arise from the deployment. I will keep the card open until Wednesday 2/23/22 if I don’t hear anything back.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> Product Delivery Manager
> Data and Technology Services

**Comment by Nadin-Nader** [comment]
Waiting for an example. @Nadin-Nader check back with Darren on 3/2/2022

**Comment by Nadin-Nader** [comment]
Per Darren  the team was able to find a test folder and the bug did not appear again. Closing
