### ISSUE TITLE
Create work order mock up for 311 Service Requests

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8198]
Once 311 SR requests come in, create a work order in that Vendors can access through their Vendor Page in SMRT (Shared Mobility Reporting Tracker). 

The work order will capture flex notes and images from the CSR, and allow vendors to add additional comments in SMRT that will be pushed back up to the 311 platform before staff does final review to close the SR.

Create a mock up similar to other work order example in other Knack Apps. 

Things to do:
- [x] Create Mock up
- [x] Testing
- [ ] Get Vendor Feedback

**Comment by patrickm02L** [comment]
@dianamartin schedule time with @johnclary to review work order status to rollup to CSR.

**Comment by dianamartin** [comment]
# Questions for stakeholders
- Would you want vendors to auto-create their own work orders from a SR?
- Would you want vendors to "Re-open" a work order
- Is there anything else you want to know about a vendor while they complete the work order for the SR?

**Comment by dianamartin** [comment]
Created initial service request to work order process. Will have to check-in with vendors to see if there are other enhancements that are needed. Will close this issue.
