### ISSUE TITLE
Meeting: Banner Permits and Payments in Knack Sprint Review

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8201]
Scheduled 1/25

AGENDA:
Enhancements:
Review page
Application page

CityBase updates

[Sprint Review slides](https://docs.google.com/presentation/d/16qm-c5ZIvXPfh5Zz-xXKQJM85RS8mtIwxEPD4479XeI/edit#slide=id.g1ebb8a7ebd_0_60)

**Comment by moorerst** [comment]
@dianamartin please review the sprint review slides and provide feedback Thanks https://docs.google.com/presentation/d/16qm-c5ZIvXPfh5Zz-xXKQJM85RS8mtIwxEPD4479XeI/edit#slide=id.geec2d7738f_0_6

**Comment by dianamartin** [comment]
@moorerst I've reviewed and left some comments on the slides. I still need to get the Commenting/Email feature built before our meeting, but that should be fairly easy-ish

**Comment by moorerst** [comment]
@dianamartin just checking in. Are we set for meeting tomorrow? Above you mentioned you needed to complete the commenting/email feature.

**Comment by dianamartin** [comment]
@moorerst I plan to work on that this afternoon before the meeting

**Comment by moorerst** [comment]
Reviewed enhancements with stakeholders.
No additional modifications 

- Will review in more detail during User Testing with Customer Role and Reviewer Role

Discussed CityBase updates. Stakeholders has a few questions: (new issue)

- When payment is completed using CityBase will there be a confirmation of payment in Knack?

- Will the customer get a receipt?

- Each fiscal year there is the possibility for rate change. How is a rate change handled in CityBase?

- When a COA Department is purchasing a Banner they receive a discount or no payment how is that handled in CityBase?

- How is it handled if a COA Department needs to JV their payment (payment within the COA financial system between departments)?

Next Steps:
User Testing - 3 possible sessions of user testing (new issue)

- 1st session - Signs and Marking Lauren/Kathy
customer role and reviewer role.
Make any modifications based on testing with this experienced team

- 2nd session - Smart Mobility Luke/Hannah 
customer role and reviewer role

- 3rd session optional - actual customer

- Start looking into the Technician Work Order and Technician Page (new issue )

**Comment by dianamartin** [comment]
Stephanie and I debriefed after the meeting to discuss next steps and follow-up action items. Stephanie created new issues based on action items. Closing this.
