### ISSUE TITLE
Documentation for Bike Map Data Sources/Paths

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#8205]
@alan-deanda I created a page for this documentation in the location below. I have gone ahead and added a couple for the online bike map. Feel free to make any additions or changes that you see fit, particularly for the Print Map section.

https://atd-dts.gitbook.io/atd-geospatial/active-transportation/bike-map-processes/bike-map-data-sources-paths

**Comment by johnclary** [comment]
@alan-deanda working to transfer notes to Gitbook. Please try to complete this during the current sprint.

**Comment by alan-deanda** [comment]
this wiki is now complete!
