### ISSUE TITLE
[Feature] Create a Power BI Dashboard to view AMD Inventory

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#8212]
Create a Power BI dashboard for the inventory dataset John has created and is now on [Socrata](https://data.austintexas.gov/Transportation-and-Mobility/Arterial-Management-Materials-Warehouse-Inventory/hcaw-evi2).

More specifications here:
#7581 

Slack Messages from John
- Filter on the published_date filter such that a user could view on-hand quantities for a given date?
- Report should be sorted by commodity code ascending. Only capture “financial items”

**Comment by Charlie-Henry** [comment]
[Link to Power BI dashboard.](https://app.powerbigov.us/links/HhyrMFbRAH?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare)

It currently has a date calendar selector (only two days of data 1/19, 1/25) that will filter the table below. I've included all fields from the Socrata report and filtered the table to only show `Tracking Type == 'FINANCIAL'` and `Status == 'ACTIVE'` items. 

I've included a calculation of the inventory value for the selected date which is the sum of `Total Value`. Also a graph which will show the trend over time (max of last 365 days displayed).

To download the CSV, click export data -> Data with current layout
![image](https://user-images.githubusercontent.com/30810522/151221619-64cc5f12-d713-4197-8d3e-fd3585582fab.png)

It will be named "Inventory Items Status - 1252022.xlsx" for January 25, 2022's data

There is a duplicate query on 1/19 that @johnclary will remove.

**Comment by johnclary** [comment]
@Charlie-Henry can you add the ability (maybe another view/what have you?) to filter the table rows for a specific item across multiple dates?

**Comment by Charlie-Henry** [comment]
After our meeting last week with the inventory folks, @dianamartin  and I have made some changes to the dashboard based on their feedback. [Notes are here](https://github.com/cityofaustin/atd-data-tech/issues/8359l) 
1. Resorting the columns of the table on the bottom of the page.
2. Changed the refresh time of Power BI to 1AM central. (DAG for socrata runs at 10PM-12AM).
3. John refreshed the data, so now we shouldn't have duplicates within each date.
4. I removed interactivity between the chart and table since that was potentially confusing.
5. Added `Stock Number` and `Common Name` slicers
6. [Documentation is here](https://atd-dts.gitbook.io/amd-data-tracker-help-guides/)

Will leave this issue open until we check back in with them.
<img width="703" alt="Screen Shot 2022-02-09 at 9 04 39 AM" src="https://user-images.githubusercontent.com/30810522/153246481-25c4d9d4-d291-4fb1-8ada-81509490b843.png">

**Comment by amenity** [comment]
@Charlie-Henry @johnclary - this issue is still in the "New" pipeline... 😅 

Looks like it's at least "In Progress"?

**Comment by dianamartin** [comment]
@amenity I've seen the inventory dashboard that Charlie made so it's complete and I'd have to check the date of when the help guide instructions were sent. This might also be a dup?

**Comment by dianamartin** [comment]
Found the email that John sent out to stakeholders on 2/24,
>- Charlie has created a **dashboard** in PowerBI which reports the daily on-hand quantity and value of inventory items. The dashboard is updated on a nightly basis.
>- Charlie has written up instructions for using the report, [here](https://atd-dts.gitbook.io/amd-data-tracker-help-guides/inventory-1/reports#dashboard-user-guide).
>- Let us know if you have any questions.

**Comment by amenity** [comment]
Thanks, @dianamartin !
