### ISSUE TITLE
Meeting: Parking meters Sprint Review/Check In  

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8214]
Agenda:
General conservation on how the non 311 SR process is going for Parking Meters
•	Been in production for 3 months
•	Any pain points with the process
•	Any next steps you might want to explore

Meeting scheduled 2/10

**Comment by moorerst** [comment]
Enhancement requested:
Wanted to see if we could somehow implement this (DOSA) work sheet  into our Tablet functions daily. What would be the best and easiest way to add to Knack system? Also, if able could we pull historic records easily. Just considering the idea of this worksheet.

Will be discussed at the meeting scheduled for 2/10

**Comment by moorerst** [comment]
@dianamartin please review slides for Check In meeting 
https://docs.google.com/presentation/d/1_rJdfca0kRoPXhjBKeWvyr_LOlRaAxDxw5Jx8dsXjlc/edit#slide=id.g8105978563_0_5

**Comment by dianamartin** [comment]
# Diana's Notes
Check-in with Parking Meters
Like the graffiti
Went back to emailing the spreadsheet through email

**Comment by moorerst** [comment]
No further action at this time. Closing this issue.
