### ISSUE TITLE
[BUG] TDS App unable to preview or download Attachments - Internal Server Error

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#8225]
Submitted a ticket to Knack regarding to bug:

Hello, Our TDS app is having an Internal Server Error when accessing files preventing all attachments from previewing, loading, or have the ability to download. Selecting the download button does nothing. We tested across browsers and apps and this is the only app having this issue. Would moving this app to a different server instance resolve this issue?
![image](https://user-images.githubusercontent.com/67915167/150434586-d5a80dd6-9add-4d92-87fa-c13663770893.png)
![image](https://user-images.githubusercontent.com/67915167/150434597-f7a2a917-1a41-4d91-b983-cd9f84b3ef39.png)

**Comment by ChrispinP** [comment]
Knack responded and is working on this issue

**Comment by ChrispinP** [comment]
Server migration was a success. Tested several attachments that didnt open previously are now opening. Issue may now be resolved. Will need to confirm with users.

**Comment by TracyLinder** [comment]
This is fixed. Closing.
