### ISSUE TITLE
Spike: Evaluate approaches for adding speed limits to CTN

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8226]
Evaluate how we might:
1. Update the CTN with current speed limit data
2. Establish a process to keep speed limit data current

Consider these possible data sources:
- The TED web map that tracks speed limit changes as part of the citywide prima-facie change
- Frank's earlier work creating a similar layer
- Data that can be extracted from signs work orders and/or the RAS data collection effort

**Comment by patrickm02L** [comment]
@andrewshensky says that speed limits are an attribute that GIS has added to the CTN and are maintaining.
