### ISSUE TITLE
Hire temp IT Geospatial Technicians

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8227]
[Drive folder](https://drive.google.com/drive/u/0/folders/1TmMFEm_mLhbGZvVyy4C8G9Y73chB8dxk).

**Comment by jaime-mckeown** [comment]
Adding Andrew and removing myself from Issue.

**Comment by amenity** [comment]
@amenity - check with Peggy on this. Especially pressing since a big chunk of sign data will be turned in presently and Adriene (VZ) will be on maternity leave any day now.

**Comment by amenity** [comment]
@amenity - get info from Peggy/HR ASAP



[https://lh5.googleusercontent.com/ijTxCiWJyLk-IPqwswoCA0GTDPcsXMws8wCQh2B_wxHLyJSw_0PRLz_eB7o8REt-g_5gMlwGX-H7dsdF3G5F1xtNrBRPvGNLWIVJ163Ll4yy_NlAM6l0Eo59ReQAwo3GkQKQ36hE]

Amenity Applewhite (she/her)

Data & Technology Services<https://austinmobility.io/> │Head of Product

Austin Transportation Department

Direct (512) 974-3571  | Main (512) 974-1150

[https://lh4.googleusercontent.com/19-1RTtCDiFy55wa6nwSgVRIfFwwHWo2ROrgbryjo8z56Ac3xCfCOvBhzkBb7_OtSzdTue7NVCW-9J0-94OQaci971jc2Dc6PLeQHFS0xVx8gJjb1g0sKN3fRw0D5foBy3d1LXF8]     [https://lh6.googleusercontent.com/Vg79kCUivHkMhcdaHHQr5DceLjL_vf6lqG1slSPTNQ9SbYht3jqSX8Y8UaHaTiG7l0GrXSqlnEJmICCQf5jLT-5e4cqQAg8hRCS3q-Ts7TgLNFF2Z2BtdWnA2o3sId5blPvJZmoI]      [https://lh3.googleusercontent.com/yKeZuZBtq-Nt6OtW8ZWj2OxOAa-A5aX2JgtPmiHlGV7Z8scf5byhdNc3IBt4Vlw4m-N_bGcfqFcfCK5T-bDmkYsznQc5TRcuhlzCfew-xAcLSh9bJawFtCqI9lCe-YgwVmfkOb-t]

________________________________

**Comment by ChristinaTremel** [comment]
@andrewshensky can we close this issue?

**Comment by andrewshensky** [comment]
This has now been completed
