### ISSUE TITLE
[Feature] TURP - Manual Extension Info Updates (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8232]
### Update 'Manual Extension' attempt on Permit Extension Process (RW-TURP) to update folder info with process info values.

![AMANDA Misc  - TURP - Manual Extension (1)](https://user-images.githubusercontent.com/49930868/150596787-6c6b4905-eb8a-4fe4-bdd5-cbdc20d9e929.jpg)

**Comment by TracyLinder** [comment]
**Highlighted are the new features we need to implement for this attempt**

<img width="1249" alt="Screen Shot 2022-01-21 at 2 40 26 PM" src="https://user-images.githubusercontent.com/49930868/150597230-e54708b1-0cce-417e-b8de-cbde93584d5f.png">

**Comment by Lpriya-LIT** [comment]
When the Turp extension attempt ia saved, the process info value has to be updated in the folder Info. The infos are Extension start date and Extension end date.
@TracyLinder @Nadin-Nader Please confirm whether my understanding is correct.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I asked Paloma about this and she is going to ask Evelyn P. and get back to me

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Here is Paloma's response from Evelyn:

> [11:48 AM] Amayo-Ryan, Paloma
> [11:27 AM] Powers, Evelyn
> 
> yes sorry i guess i misunderstood the question.  the actual start date will never change but there is a seperate start date for extensions on the info tab and that number will change:
> 
> ![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/bd10921c-113f-414f-8cdb-80181ac6c7a5)

> [11:49 AM] Amayo-Ryan, Paloma
> Thank you!  And those dates are coming from what is getting calculated when processing the extension (on the Process Tab).
> 
> [11:50 AM] Powers, Evelyn
> Correct

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/49204ec6-0074-4d26-866a-62194ed8b501)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader The Extension Start and End dates will get updated with the data in process info when Manual Extension attempt is done in Permit extension process for RW-TURP

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this over to the DevOps CM Team to be deployed to *_DEV_** under **SCTASK0199641**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader  Verified in Dev, Looks good. Ready for Test Deployment

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/fffac86b-8a74-4df9-89bf-d9bdb5b50c13)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0201660**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes Deployed to test, works as expected.

**Comment by Nadin-Nader** [comment]
Tracy will UAT this on TEST  during our meeting but on the side.

**Comment by TracyLinder** [comment]
### UAT Results: Not Approved

_Test RSN 12862934_

**Process Info Validation '# of Days in Tier':**
_❌ System requires user to input Tier infos; it should not._
- Must Validate: Extension Start Date, Extension End Date, Number of Days for Extension
- Should **Not** validate: All tier infos (there are 4)



----
**❌ Missed Requirement: Clear Process Info values**
- When attempt 'Manual Extension' is saved, system should clear the values in the process infos as is done with attempt 'Extension Granted'

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Please go ahead and make the Necessary changes

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/62dc6168-a28d-4464-9b53-06999e921c4b)

**Comment by Lpriya-LIT** [comment]
Commit has been done , will update once it is promoted.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0205383**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been moved to DEV Please UAT so we can move to TEST.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Dev , ready for Test promotion

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0206080**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to TEST. Please UAT and let me know if it is ready for Stakeholder UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test , Works as expected. 
Test folderrsn - 12866695.
Ready for Stakeholder UAT

**Comment by Nadin-Nader** [comment]
Comments section for the extensions is not populating the date on the process comments  and the description field on the Folder Tab

Has to update the process comment and the description field

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/d95fabc2-ef23-4100-9963-3352f262d22e)

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/1ae657e2-53c4-4ed0-86c3-38ef6cde1acd)

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Added the extension dates in comment and folder description. Please refer the screenshots and let me know whether it looks good.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT looks good to me, Please send to DEV

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0209185**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to **DEV**, please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Dev, Ready for Test Promotion

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0210634**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to TEST. Please UAT and verify all is well for stakeholder UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test , works as expected.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this over to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0215038**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0215827**

**Comment by Nadin-Nader** [comment]
Sent a message o the Testing/UAT TEAMS channel informing Paloma and Izzy that this was ready for their UAT on TEST.

**Comment by Nadin-Nader** [comment]
From Paloma:

> [2:39 PM] Amayo-Ryan, Paloma
>     We won't have time to test this before we meet on Friday so we would like to look at it during our meeting.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Sent the prod deployment plan, please request prod promotion

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been sent to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0218637**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been deployed to PROD. I will let the Stakeholders Know via the TEAMS channel

**Comment by Nadin-Nader** [comment]
I let Paloma and Isabel know that this is now on PROD and that i will keep it open for about a week or so or until i am told otherwise

**Comment by Nadin-Nader** [comment]
According to Izzy this is working properly and the dates seems to be populating right. closing
