### ISSUE TITLE
[Feature] EX - Manual Extension Info Updates (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8233]
### Update 'Manual Extension' attempt on ROW Admin Process (EX) to update folder info with process info values.
_Yellow are the new features_

![AMANDA Misc  - Frame 5 (1)](https://user-images.githubusercontent.com/49930868/150598877-23f2fb29-d44f-48ab-b0a7-0369f5c42ac9.jpg)

**Comment by vschandramouli** [comment]
@Sreelatha-BlazeKannan  No, we will not be checking for AUP value during this attempt. This attempt was designed for folders where AUP was 'No' when Extension Granted attempt was made, so the folder did not issue at that point. Staff should be able to go into those folders, do Manual Extension attempt and activate the Permit regardless of AUP value. 

CC @Nadin-Nader @TracyLinder

**Comment by Sreelatha-BlazeKannan** [comment]
@vschandramouli - Thank you Vish for clarifying. I will remove AUP - NO Check.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  whats the status of this?

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP Submitted, and please approve and create task id for me. Here is the commit id: 3f0519d25587

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent this to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0199636**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV and working as expected.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Sent the TEST DP on 2/17/2022. Please approve and create task id for me. Commit ID: 3f0519d25587

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan 
**Status:**
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0201299**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST environment. Working as expected. PROD DP of #8233 for your reference. Kindly approve and create task id for me. 
Here is the commit ID: 3f0519d25587

Note: Please make sure 6255 & 7631 & 7991 commits are in PROD before committing the above.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST environment and working as expected.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - PROD DP Submitted. please approve and create task id for me. 
Commit ID: 3f0519d25587

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0205380**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder This has been deployed to PROD

**Comment by TracyLinder** [comment]
### PROD UAT PASSED 🎉
_I'm closing this issue._
