### ISSUE TITLE
[Enhancement] Display an alert banner in the staging environment

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8234]
As a Moped user, I want to know when I am using the staging vs production Moped environment.

- Text: "Welcome to Moped Staging. This environment is for testing purposes."
- Style: [Information alert](https://v4.mui.com/components/alert/), but fixed, top-aligned, full-width, and without border-radius rounded corners. (Use whatever the default is for the text and icon; I think our XD kit might be off)

![Full-width-staging-banner](https://user-images.githubusercontent.com/1463708/151225256-eeb1f804-f688-4838-acde-dae7d04e2efc.png)

**Comment by johnclary** [comment]
@amenity FYI needs scoping and prioritization

**Comment by amenity** [comment]
@patrickm02L - please provide specs for simple banner. 🙏
