### ISSUE TITLE
Provide additional technical documentation for Moped

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8235]
@mateoclarke @chiaberry @frankhereford @tillyw @johnclary  - please review the "Dev Guides" section of the Moped docs [[read](https://atd-dts.gitbook.io/moped/dev-guides/how-tos) | [write](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/dev-guides/how-tos)] specify what you would like to see filled in: 

### [Account management and authentication ](https://atd-dts.gitbook.io/moped/dev-guides/authentication/hasura-and-cognito)
- [ ] Review and update as needed
- [ ] Replace missing images - maybe from [this Miro board](https://miro.com/app/board/o9J_knyFAmc=/?moveToWidget=3074457350012857291&cot=14)?
- [ ] [specific topics/questions]

### & maybe
- Deploy pipeline (Netlify PR deploys ? Github Actions deploy to Test?)
- Any more on [maps](https://atd-dts.gitbook.io/moped/dev-guides/maps-and-geospatial-data)

Note: there's lots of stuff in Miro that may need to be linked to in Gitbook.

**Comment by amenity** [comment]
@frankhereford @chiaberry @mateoclarke @johnclary - feel free to add any specific areas/questions you want addressed

**Comment by chiaberry** [comment]
I'll take a look at the [documentation on gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/dev-guides/authentication) and see what questions I come up with.

**Comment by chiaberry** [comment]
I rewatched the moped users skillshare that Sergio did last fall and am taking some notes. He does mention that setting up the Active Directory integration was super hairy and he wrote extensive private documentation. That section is empty on gitbook, it would be nice to have some parts filled in if possible.
https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/dev-guides/authentication/single-sign-on-with-ctm

**Comment by amenity** [comment]
Thanks, @chiaberry - made that into #8390 .

**Comment by amenity** [comment]
Thanks, @frankhereford and @chiaberry for reviewing docs.
