### ISSUE TITLE
[New Public Page] TDS-TIA Customer Portal Landing Page

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8236]
### Currently the only public application for the TDS Portal is the TIA Application, so we have not created a customer portal landing page. With the addition of the Determination Form Intake (#8163) we will need to create a general landing page for TDS/TIA. 

- See wire frames [here](https://miro.com/app/board/uXjVOMzA_lE=/?moveToWidget=3458764518993136197&cot=14)

**Comment by TracyLinder** [comment]
@patrickm02L will be joining us for the initial content conversations. Yay!

**Comment by TracyLinder** [comment]
Meeting w/ stakeholders 2/8/22 @2pm. #8374

**Comment by TracyLinder** [comment]
### Stakeholder Review / Convo

**Page Parts**
1. Welcome w/ Icon
2. What this portal is / why
3. Choose your application type

**Comment by TracyLinder** [comment]
**Update**

Chrispin is working on the page layout & initial content. Should be ready to show stakeholders by tomorrow.

**Comment by ChrispinP** [comment]
**Updates for TDS Customer Portal & Determination Portal:**

![image](https://user-images.githubusercontent.com/67915167/155397408-eb499b2f-af06-4bab-a483-9f8f70d3cebd.png)

![image](https://user-images.githubusercontent.com/67915167/155397203-a461f057-75e8-48b2-9a39-ce5574c0c109.png)

We may also want to provide a button for the new Case Access Code page

Ready for Review

**Comment by TracyLinder** [comment]
We are meeting with TIA stakeholders on 3/2 to review.

**Comment by TracyLinder** [comment]
### Stakeholder Feedback:

- [ ] (Tracy) Ask PIO for a banner
- [ ] Add clarification that the customer doesn't need to create an account or log in. 
- [ ] Add links to TDS & TIA Websites
- [ ] Add a Getting Started section just above the buttons. Add a brief description of each application type and instruct customer to click the button to get started. 
- [ ] Add verbiage: `This is an official site of the City of Austin. ` 
- [ ] Add a link to the TIA Portal to access the landing page.

**Comment by ChrispinP** [comment]
Customer Portal landing page updated. Added information buttons for each application type, updated language for login requirements, and updated service verbiage. PIO is helping with the Banner and Link. Meeting scheduled to discuss updates.

**Comment by ChrispinP** [comment]
![image](https://user-images.githubusercontent.com/67915167/158647331-266ef2c0-f337-4e8a-b698-62b6b1839f1f.png)

**Comment by ChrispinP** [comment]
![ATD DSCP Banner](https://user-images.githubusercontent.com/67915167/159734261-edd30e56-6e0a-4cf5-9ba2-5e4472434ad3.png)

**Comment by TracyLinder** [comment]
## Stakeholder Review - Approved for Go-live 🎉

**Updates Requested:**
- Justin will provide updated language for the Determination info button
- [ ] Rename the Determination button to 'TIA Determination'
- [ ] Rename TIA button to 'TIA: Traffic Impact Analysis'

**Comment by TracyLinder** [comment]
### Go-live Scheduled for Thursday 3/24/22.

**Comment by ChrispinP** [comment]
Customer Portal is now Live. Emailed Stakeholders.

**Comment by TracyLinder** [comment]
We'll leave this open for bug support until 4/1. Good work @ChrispinP !

**Comment by TracyLinder** [comment]
This is stable. Closing.
