### ISSUE TITLE
Feature: [TDS-TIA] - Customer Portal Privacy Issues Access Code

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8237]
### Currently the public can access the public view of all TIA cases, including proprietary synchro files.

- We want to avoid user accounts as a solution. 
- We have stakeholder approval to prototype a solution using a case access code.

**Comment by ChrispinP** [comment]
New Page structure built out one page deeper so page rules can be applied to second page.
![image](https://user-images.githubusercontent.com/67915167/154544157-44c59c18-1462-4a2d-b40f-d6026428b6af.png)

User will be greeted with an access button
![image](https://user-images.githubusercontent.com/67915167/154544403-8cfb80ad-768f-4a0d-b4b8-a758f6fba8f9.png)

Customer must enter Access Code for their TIA Case:
![image](https://user-images.githubusercontent.com/67915167/154544524-be1f4aa0-cbbb-4982-a62f-76d0df787c41.png)

When a valid code is entered it will show a button to open the case.
![image](https://user-images.githubusercontent.com/67915167/154545265-1ea8a206-8afe-471a-9bf3-c62a297c0c2c.png)

For a case to show as valid, it must be connected to the parent object.

**To Do once feature is enabled:**
- [ ] Update Customer Email to provide updated link and access code.
- [ ] Update Customer View button link for Reviewers
- [ ] Hide/Remove/Disable Access to old customer pages
- [ ] Remove/Replace any affected code
- [ ] May need to add a way for Reviewers to provide Access Code to customers that lose the email, I suggest an email button to send code.

Ready for Testing

**Comment by TracyLinder** [comment]
We are meeting with TIA stakeholders on 3/2 to review.

**Comment by TracyLinder** [comment]
### Stakeholder Review 3/2

- We did not have time to discuss this. I will schedule another meeting.

**Comment by TracyLinder** [comment]
I emailed Anton w/ PIO asking for a banner/image.

**Comment by ChrispinP** [comment]
Meeting scheduled to discuss feature and go live.

**Comment by TracyLinder** [comment]
## Stakeholder Review
_They like it!_

- [ ] Move the **Access TIA Case** button/feature to the Customer Landing Page, and remove the page it's currently on. 
- [ ] Add **Access TIA Case** to the nav. menu
- [ ] Update TIA application submittal confirmation page to include the access code
- [ ] Update the customer confirmation email w/ the access code
- [ ] Update TIA Case Details w/ the access code (lets try adding it to the bottom of the **Applicant Information** section)
- [ ] Update the **Open TIA Case** button to include the project name
- [ ] Update the access code page w/ help language, directing customers to email the TIA resource account for help finding their access code.

**Comment by TracyLinder** [comment]
@ChrispinP just FYI i updated the issue name to include _access code_

**Comment by ChrispinP** [comment]
Prepared TIA Case Details, TIA Reviews, Customer Portal, and Access Code pages for the implementation of the Access Code. Remaining changes must occur for Go Live.

Ready to review

**Comment by ChrispinP** [comment]
Emails, Buttons, Code, and Urls updated for this feature. Old pages are no longer accessible.

Will send followup email on Monday and complete old code and page removal next week.

**Comment by ChrispinP** [comment]
Followup Email successfully sent.

Ready to close

**Comment by TracyLinder** [comment]
Leave this open until 4/15.

**Comment by TracyLinder** [comment]
Everything is stable. Still need to document #8837. 
Closing this
