### ISSUE TITLE
Dockerize Crash Mapping Tool

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8239]
As VZ staff, I would like to create high-level diagrams that contains geo-located data and supporting CR3s that can be passed to Engineers for analysis and insights on what interventions to apply at crash sites.

@frankhereford created an app that assists him in making crash diagrams while he was on the VZ Team. The app is a stand alone tool that is not part of the Vision Zero suite. This tool allowed him to manipulate geolocated data in a GUI to organize crashes into a legible data visualization on his local computer.

In order to continue the quality of diagramming, the DTS team would like to package up the app in a Docker container, and give it to the VZ team, specifically Adrien H., to use locally on their computers as a stand alone app. 

The DTS team will not improve or maintain this app beyond its current state.

Things to do:
- [x] Dockerize Crash Mapping Tool
- [-] Install software onto Adrien H.’s computer (not included in estimate)
  - [x] I'm afraid we need to get `git` on her machine. I am hopeful this is a well received request. It's very low risk. It'll make our life easier, as the crash mapping crew for sure. @patrickm02L 
  - [x] We also would benefit up an upgrade to the latest and greatest QGIS. We should ask Scott bright and early tomorrow. @patrickm02L 
- [x] Walk through creating a crash map together (not included in estimate)

**Comment by patrickm02L** [comment]
@frankhereford please add any additional insights and provide a size estimate.

**Comment by patrickm02L** [comment]
On the advice of @mateoclarke it would be more prudent to create this tool in a separate repo `atd-vz-crash-mapping` or something to that effect.

**Comment by frankhereford** [comment]
@patrickm02L Howdy, while this is fresh in my mind,  I wanted to memorize the state of the crash diagramming app. As it stands, we have it being:

* Able to spin up a (arch dependent) pg server with persistent data on disk
* Able to spin up a linux container to run utility scripts, inc all dependencies
  * Includles scripts to refresh the DB from VZ backups on S3
  * Includes scripts to extract CR3s by AOI
  * Includes scripts to author XLSX files by AOI
  * Extract backups of diagramming data
  * Provide an `icon_exploder` utility to produce new versions of symbology glyphs
  * Apply views and stored procedures to generate HTML tables for layout purposes
* Able to spin up a webserver including:
  * JS app, built around `yarn`
    * This code is so rough, but it works..!
  * Apache web server to:
    * Serve static images for crash symbology, a few hundred `pngs`
    * Provide `cgi-bin` old-school endpoint to deliver data to JS app
 * GIS project files that connect to localhost and render the results for layout into PDF
 * All this in pretty tidy docker-stack, so can connect to the DB, webservers on the `localhost` hostname and not expose any of it to other hosts on the network.

All of the following is built up from a `docker-stack` and related `Dockerfile` definitions with all secrets held in a .env file. Template .env file is included in the repo. All deliverables are exported out of the docker stack via bind-mounts, so our users can simply pull them off their filesystems.

**Comment by patrickm02L** [comment]
Met with Adrien 2/3/22, spent 2hrs setting up software on her computer including git, and latest version of QGIS.

**Comment by patrickm02L** [comment]
Met with Adrien on Monday 2/7/22 for 3hrs, and Wednesday, 2/9/22 for 1 hr. Onboarding is complete.

Still need to do documentation for using the Crash Mapping Tool.
