### ISSUE TITLE
Non-CR3 uploads enhancement - validate lat/lons

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#8248]
A common mistake in the [user upload process](https://visionzero.austin.gov/editor/#/tools/upload_non_cr3) for Non-CR3s (AKA: Blueform records) is that the lat/lon columns are flipped.  

In addition to the null check, we could add validation for a geospatial check.

This could either do something like a bounding box check, to make sure the coordinates are within the Austin Region.

Or it could be more simple and just check that a latitude is postive and a longitude is negative.

```js
const isValidCoord = (x, y) => {
   Number(x) < 0 && 
   Number(y) > 0 &&
   isFloat(Number(x)) && 
   isFloat(Number(y));
}
```

**Comment by mateoclarke** [comment]
Related to https://github.com/cityofaustin/atd-data-tech/issues/8220

**Comment by patrickm02L** [comment]
In Product Sync, 1/11/23. Where do we get blue form records to test?

**Comment by patrickm02L** [comment]
An error message if the point is outside plus or minus 2 degrees latitude or longitude.
