### ISSUE TITLE
Provide Data Tracker view of a project's work orders based on URL parameter

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8249]
Update the [main work order list in data tracker](https://atd.knack.com/amd#work-orders/) as follows:
- Replace tabbed filters with standard custom filtering
- Create a new menu above the table search with links to filtered views of the same page that match the existing filters
- Provide Amenity with the URL pattern to use to filter work orders on this page based on the "Project ID" column. That will unblock #8251 

The goal is to be able to link to a view of all a project's work orders from Moped: 
![Screen Shot 2022-01-26 at 10 55 36 AM](https://user-images.githubusercontent.com/1463708/151209855-0cd32c79-6a08-45dc-a57e-456503e52d36.png)

**Comment by dianamartin** [comment]
- [x] Created a new filter menu on the Work Orders (Technicians) page. 
- Emailed stakeholders - 1/26
> I just wanted to make sure you all were aware that we updated the Work Order (Technicians) page to have the table not have pre-set filters. I created a menu above it so you can still filter by the status you’re looking for. 

![image](https://user-images.githubusercontent.com/21112975/151222300-5d322f38-2265-4470-ae4d-5440f2950c1e.png)
 
>Let me know if you have any questions or concerns.

**Comment by dianamartin** [comment]
@amenity This is the filter for ex. (Manor & Cherrywood)
- [full filter](https://atd.knack.com/amd#work-orders/?view_713_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_3965%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%22611b10fa5a7fc4071f0ca6ec%22%2C%22val_label%22%3A%22%20MANOR%20RD%20%2F%20CHERRYWOOD%20RD%22%2C%22field_name%22%3A%22project%22%7D%5D%7D&view_713_page=1)

Filter URL Pattern 
`https://atd.knack.com/amd#work-orders/?view_713_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_3965%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%22611b10fa5a7fc4071f0ca6ec%22%2C%22val_label%22%3A%22%20`MANOR`%20`RD`%20%2F%20`CHERRYWOOD`%20`RD`%22%2C%22field_name%22%3A%22project%22%7D%5D%7D&view_713_page=1`

**Comment by amenity** [comment]
Beautiful, @dianamartin !!
