### ISSUE TITLE
Create Design Comps for Personalized Dashboard

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8252]
What information would be useful to staff when they open their Moped account? 

How might we arrange a webpage to deliver customized information in a quick and easy way that caters to their workflow? 

Things to do:

- [x] Gather examples of profile landing pages
- [x] Sketch 3-4 versions of a layout
- [x] Draw in Adobe XD: https://xd.adobe.com/view/a2124c8e-9278-4652-ba17-4ca669e44a38-f741/
- [ ] Get feedback on drawings and make refinements

Will become part of #3683

**Comment by amenity** [comment]
@patrickm02L - Let's try to keep the scope for this tight and simple. 🙏

**Comment by patrickm02L** [comment]
#### Concept

This dashboard keeps it super simple, maintains the styling and header architecture, rethinks the body. 

When thinking about what information would be useful, it made sense to narrow the dashboard down to four basic sections: Progress of Projects, Project Status, Recent Projects staff members are working on, and Links

**The body imagines four sections.** 
* Graph that represents the cases that are being worked on day-to-day
* Table that captures Status and Funding
* Table that captures the most Recent Projects an individual is working on
* Quick Links section

![Dashboard Sketch.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/ea2662f8-4a2f-486b-b79c-37b5552abab5)

**Comment by patrickm02L** [comment]
### Mock Ups (Draft)

Accounts for the 4 sections of the Concept, and adds a filtering feature for staff members to use that would narrow the projects to their specific team, and fiscal year.

**Example 1**
Filtering feature is housed below the date. 

![Dashboard – 1.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/02af6fd4-078f-43fd-9b44-e8e4b031c75d)

**Example 2**
Filtering feature is in line with the date on the right side of the page.

![Dashboard – 2.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/7bdc26d6-a2f8-427e-ab78-4bd603091fc7)

**Comment by patrickm02L** [comment]
Showed this at Dev Sync on Thursday, Jan 22, 2022.

**Comment by amenity** [comment]
XD link [here](https://xd.adobe.com/view/a2124c8e-9278-4652-ba17-4ca669e44a38-f741/).

**Comment by amenity** [comment]
We aren't yet sure where custom views like the "Signals projects" table will go, but I imagine we'll be making at least a few more. @mateoclarke said that providing links to these one-off pages from the dashboard would be a relatively lightweight way of making them accessible to users. 

I was thinking we could render them using a simplified MUI [card](https://v4.mui.com/components/cards/) component, maybe with an icon? Mocked up very roughly in the XD file:
![Screen Shot 2022-01-31 at 5 51 26 PM](https://user-images.githubusercontent.com/1463708/151893706-c69a0745-f1f5-4606-8c6c-6f87086fef69.png)

**Comment by patrickm02L** [comment]
Latest

![Dashboard – 2 – 2.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/ad5d487e-0c46-496b-b76f-0e1e521303d3)

**Comment by amenity** [comment]
- Remove filter
- "My projects" heading
- Sentence case greeting and date


Going to show to AMD for feedback on the actual use case.

**Comment by patrickm02L** [comment]
Updates based on feedback

> * Remove filter
> * "My projects" heading
> * Sentence case greeting and date
> * Define what it looks like for users who have no projects

![Dashboard – 2 – 4](https://user-images.githubusercontent.com/5566727/154765341-e19900c5-fb47-44d4-a696-8c1a807f59cc.png)

![Dashboard – 2 – 3](https://user-images.githubusercontent.com/5566727/154765528-63ec7392-80cc-4b6b-a0fb-6b51be522c44.png)
