### ISSUE TITLE
Review Miro diagrams and add links to Gitbook 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8254]
@sergiogcx - you have some really excellent diagrams in Miro, e.g. this  and it would be great to make sure we have links to them in Gitbook so they are discoverable. 

Please review your boards and boards you've contributed to [in Miro](https://miro.com/app/board/o9J_luPHQDg=/) and add links where they make most sense in Gitbook.

**Comment by sergiogcx** [comment]
This is done, most of the diagram already had links, just filled in what was missing.

**Comment by amenity** [comment]
Thank you!
