### ISSUE TITLE
SG Review Issues 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8255]
Review the following Vision Zero Backlog Issues and assess the workload for each.

#8248 Non Cr3s Upload enhancement - validate lat/lon
#2413 VZD | Unit metadata | Inconsistent fatality counts between crash total and unit metadata totals
#7842 Perform quality control data related to modality-fatality numbers on VZV
#6789 Add flag to track if a crash was caused by a medical issue
#5973 Daily report of new records added today in VZD
#5149 VZ ETL | Add case ID to demographics Socrata dataset
#6661 Enhancements to VZ DB export to Socrata (data dictionary, data age limit, & description text)
#3818 VZE | Spike Upgrade to CoreUI 3.2.0

Any of these would good to pick up over the next few weeks.

**Comment by amenity** [comment]
Per feedback from @sergiogcx and discussion with @patrickm02L, it doesn't make sense for Sergio to start working on the VZ backlog again at this point.
