### ISSUE TITLE
[Enhancement] Purchase Order Tracking

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8259]
As a project manager, I need the ability to track multiple contracts and purchase orders for my project.

### Scope
- Create a new DB table, `moped_purchase_order` which will store purchase orders related to projects
- In the UI, add a new table to the Funding (or Team?) tab which displays information about related contracts
- Allow users to add and "delete" rows to this table

### Questions
- Team or Funding tab?
- Figure out how to migrate existing data from `moped_project` to `moped_contract`. Does every existing project with a DO (`purchas_order_number`) have a `contractor`?
- For discussion: rename "Contractor" to "Vendor"? Make "Vendor" required, DO optional?

### DB specs

field name | UI label | field type | table | required
-- | -- | -- | -- | --
`id` | (not rendered in UI)| int (auto incrementing) | moped_purchase_order | yes
`vendor` | Vendor | text | moped_purchase_order | yes
`purchase_order_number` | DO # | text | moped_purchase_order | no
`description` | Description | text | moped_purchase_order | no
`project_id` | (not rendered in UI) | int (foreign key - moped_project.project_id) | moped_purchase_order | yes
`is_deleted` | (not rendered in UI) | boolean | moped_purchase_order | yes (default `false`)

**Comment by johnclary** [comment]
I split off task order needs into https://github.com/cityofaustin/atd-data-tech/issues/9683 and will refine this to contract tracking.

**Comment by johnclary** [comment]
@amenity not sure if this belongs on "Team" or "Funding" tab. i lean funding.

It needs a visual spec and would be good to run this by the rest of the MUG

**Comment by amenity** [comment]
@chiaberry - are you comfortable taking a stab at this without a mockup?

**Comment by amenity** [comment]
@johnclary -  should we consider including https://github.com/cityofaustin/atd-data-tech/issues/6992 here?

**Comment by amenity** [comment]
@johnclary - please update to use `purchase order` instead of `contract`

**Comment by johnclary** [comment]
I updated this to reflect that these are purchase orders.

I suspect we may also want a `purchase_order_type` column, which would have options like "Delivery Order (DO)" and "Purchase Order (PO)".  But that feels like over-optimizing to me at this point. We have the "description" column for capturing extra info.

**Comment by chiaberry** [comment]
@amenity and @johnclary 

> Figure out how to migrate existing data from moped_project to moped_contract. Does every existing project with a DO (purchas_order_number) have a contractor?

4 records in prod have DO numbers but no contractor (9 records come up when i do this search, but 5 of the records have a DO number of "need DO" or something similar.) What should I do about these records? Should no field be required for the time being?

There are a few projects that have multiple contractors listed, separated by a comma. I was thinking of splitting on a comma and making multiple records for those. And there's one project where the multiple contractors are separated by `/`

There are a number of projects where the DO number is a variation on "need DO" or "DO in progress". Should that also be migrated into the new table?

**Comment by chiaberry** [comment]
Actually, there are a few contractors that also have a `,` in it, but the comma is part of the contractor's name, ex: "Contractor, Inc"

**Comment by mateoclarke** [comment]
From Grooming 7/20:
- Yes, migration of data is within scope for this issue.
- Q: When should we run that migration in prod?
  - Include in launch party
  - Should testing be in a new issue? Nah
- Should vendors be required if they are blank in existing data?
  - No, let's change the requirements and let vendors be null.

**Comment by chiaberry** [comment]
Ivonne's feedback in moped sprint review 7/26:

> You can move work assignment too, it is just part of the description of a DO in our case. It might not need a field you can add any existing info to description.
