### ISSUE TITLE
Handoff daily CR3 download

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8267]
DTS team has continued to manually download CR3s since CRIS 23 update which introduced Captcha, 11/22/21. Until we can automate the retrieval of CR3s once again, the task of downloading needs to be known amongst the team. 

Here are some clear steps to take h/t @frankhereford:

Execute `process_cris_cr3.py` repeatedly in a local build of the VZ ETL image to download CR3 files for crashes which have been reprocessed and delivered as part of the daily extracts from CRIS. 

The current volume of crashes needing to be processed by the script can be found via:

`select count(*)`
`from atd_txdot_crashes`
`where cr3_stored_flag = 'N' and temp_record is false`

See PR #1048 and [download instructions](https://github.com/cityofaustin/atd-data-tech/issues/7815#issuecomment-981931328) for more information

**Comment by frankhereford** [comment]
@patrickm02L - I'd like to propose that this be closed. I ran into it searching for other issues today, and I think we're pretty stable with me running the download process. Open to any direction of course!

**Comment by patrickm02L** [comment]
Thanks, we'll close it. If we have an opportunity to hand off it the future we'll have this issue to look back on.

**Comment by patrickm02L** [comment]
In Dev Retro 1/25/23, we discussed creating a rotation to do CR3 downloads. This [schedule](https://docs.google.com/spreadsheets/d/1R7PSupharkW8wW7rA2ezN_zY23SWUWs8WrR5MG7yfbU/edit#gid=0) lays out the rotation for the rest of 2023. Calendar invites for Devs and PM to rotate on a weekly schedule were sent out through August.
