### ISSUE TITLE
User Testing Banner Permits and Purchasing in Knack 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8269]
User Testing - 3 possible sessions of user testing 

1st session - Signs and Marking Lauren/Kathy/Christine
customer role and reviewer role.
Make any modifications based on testing with this experienced team

2nd session - Smart Mobility Luke/Hannah...
customer role and reviewer role

3rd session optional - actual customer

Will schedule first training session for the week of 2/7

**Comment by moorerst** [comment]
1st session scheduled for 2/9

**Comment by moorerst** [comment]
[Test Guide](https://docs.google.com/document/d/1A8Zg_LxBfFQluA0k6Zex48nT4rlUaDYdk5Co2x_Yi4U/edit)

**Comment by moorerst** [comment]
Questions for stakeholder:
Location Installation Date
Location Removal Date - can these be pre-populated with what was entered previously in application?
**Ask stakeholders about Y/N Check box If date is not the same as Install Date of reservation**

After I SUBMIT the application can the message Banner Location Added
be moved to underneath the SUBMIT button so it's easier to see? i didn't see it because it was located at the top.
 **Ask stakeholder - Move table above form?**

Can I get to the map from this page in order to select an additional District/Sub District?
 **Ask stakeholder - if we should configure the "Add location" form on the Review page the same as the original "Add location".**

Thank you for Submitting page
Should we add text regarding if there are any issues with your application you will be contacted via email or phone.

 **Ask stakeholder - if they want to add more text to let customer know they may be contacted.**

**Comment by dianamartin** [comment]
# Diana's Notes

Get Started - button not obvious
Likes About the Program opens in new tab
Help - go straight to the document
FAQ's - open links in new tab
- [ ] make links in new tab

## LPB Banner Application Test
### Customer Info 
- no problem
- Breadcrumbs plan to be disabled, if so add a note to customer they can change it at the end 

### Event Info
- "Refresh page" message
- [ ] Get dev estimate for changing that

### Design Attachment

### Banner Location
- like that the map is there, easy to use
- [ ] Add `Number of Banners` field and `Number of Locations` to Add Banner Location page
- [ ] Remove `Location Comment`, keep it for the reviewer
- [ ] Remove `Location Installation Date` and `Location Removal Date` - for customers/reviewer
- [ ] Change "Submit" to `Add Location`

### Review Page
- Add Location modal, add reference map link
- [ ] Add Reference map link
- [ ] Remove "Add a new option" on Add Location form

### Submission
- [ ] Change 10 business days to 5 business days

### Email Submitted | Pending Review
- [ ] Change 10 business days to 5 business days
- [ ] Remove any where that says "permit/permitting"
- [ ] Remove phone number at footer
- [ ] If changes are necessary, please email atxstreetbanners email

### Global Application 
- [ ] Remove phone number at footer - globally

## LPB Reviewer Steps
- Lamppost Availability 
  - [ ] table can show by default
  - [ ] sort by Oldest to Newest

## Comments
- Add Banner Status to roll up to parent status

## Review Page
- [ ] "Completed Customer Action" 
- [ ] Completed Action - Y/N
- [ ] Add Customer Action table on the review page

## OTS Banner Application Test
- By passed to Add Locations
- Count locations, over 3 remove add form
- Add note they are $600 each
- Add reference link
check locations OTS Locations- 11, 24, 49, 65 
- filter "active" locations 
- Change to 5 business days on submission and email
- Configure comment email


-

**Comment by moorerst** [comment]
Schedule additional user training sessions:

- Another session with Lauren, Cathy and Christina
after updates have been made

- Session with Technical staff after updates have been made

After we have worked out the kinks

-  Session with Smart Mobility
