### ISSUE TITLE
Review Banners Permit and Payment in Knack Technician Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8271]
Start looking into the Technician Work Order and Technician Page
Cathy, Lauren, Christine met in November and discussed some of the enhancements we would like to see with the Banner Technician page

- Removed “Edit Work Order” button on the Technicians work orders.

- Reservation Input: Banners are ready for install, application has been submitted and approved.

- Install: When Specification is “Banners Installed | EACH” change status to “Installed”

- Removed: When Specification is “Banners Removed | EACH” change status to “Removed”

- Either/or pickup or dispose. Determined by “Will Pickup” yes/no field. If yes – then banner needs to be picked up. If no, banner can be disposed. 

- To Pickup: If “Will Pickup” is yes, then technician could select new button at the top named “Banner Shelved”. In this button, the technician selects a location from the drop down and submits. If possible, we would like this to trigger an automated email to the Requester letting them know the banner is ready for pick up.

- To Dispose: If “Will Pickup” is no, then technician could select new button at the top named “Banner Shelved”. Don’t have any location selection because it will go on shelf “To Dispose” and submit. 

Completed: 

- If “to be re-installed” is yes, the “Banner Shelved” button should have a drop down to select location that banner is being stored and move the status directly to completed

- If “Will Pickup” is yes then have a list of all banners “To Pickup”. Add new field for “Pick Up Date” that can be generated once banner is picked up. Once “Pick Up Date” is not blank, move to “Completed” status.

- Have a field specifically for who to contact to pick up the banner. 

Will Pick Up – Yes/no
	If not picked up, next field “To be Re-installed”
	If not “To be Re-Installed”

**Comment by dianamartin** [comment]
Scheduled meeting with Christina on 1/28 to talk about scoping of these enhancements and to understand what they're looking for.

**Comment by moorerst** [comment]
@dianamartin can you send me the invite also. I'll plan to attend if I can. Thanks

**Comment by dianamartin** [comment]
# Discussion Notes
- `Approved - Pending Delivery` - Approved and payment made, banners not received
- `Ready to Install` - payment made, banners received, ready to go out

**Comment by moorerst** [comment]
@dianamartin I created a new issue for the enhancements discussed during this meeting. You may want to break it out into separate issues. Closing this issue.
