### ISSUE TITLE
Design simple alert banner for Staging

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8272]
Banner will alert user that they're in the Staging environment version of Moped.

Things to consider:
- [x] Material UI precedent
- [x] Placement
- [x] Animation
- [x] Alternative to banner

**Comment by patrickm02L** [comment]
### Alert Banner

Blue banner is present when staging is opened. Opportunity to close the alert. 

![Alert banner - 1](https://user-images.githubusercontent.com/5566727/151058627-a4c0ebd8-faa4-493a-a3ad-846cf90a6ffe.png)

Demonstrates where alert is in relation to the search menu item.
![Alert banner](https://user-images.githubusercontent.com/5566727/151058836-063b007c-df3a-4a05-8742-be71dd9f6db9.png)

**Comment by patrickm02L** [comment]
### Alternative to Alert Banner

This might be an option when the banner is closed to signify that user is still in Staging or could act as an alternative to a banner. 

**Blue Dot with tool tip** (Moped logo, staging tool tip = Moped Staging)
![Blue dot hidden Tooltip – 1](https://user-images.githubusercontent.com/5566727/151060611-6a4f3dde-e395-45ad-8c40-928dbf9e6628.png)

**Comment by patrickm02L** [comment]
@Amenity Ready for review.

**Comment by amenity** [comment]
Thanks, @patrickm02L! I wasn't clear on this one, my apologies. 🤦‍♀️ Going with a simple static bar this time.
