### ISSUE TITLE
Modify Exisiting Speed Limit Change Web App to Enahnce Editing

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#8274]
[Here's the app](https://austin.maps.arcgis.com/apps/MapSeries/index.html?appid=b135dddbe79149b88d74405ba780dc42).

This map is foundation for enabling https://app.zenhub.com/workspace/o/cityofaustin/atd-data-tech/issues/8215.

**Comment by andrewshensky** [comment]
- [ ] Add Street Level = 1 to existing 36' filter query
- [ ] Remove "Speed Limit" from exisitng work order query (Should only include "25 " for Work Order Instructions)

**Comment by johnclary** [comment]
@patrickm02L FYI that Andrew has been working with Max to refine the speed limit change tracking map. Y'all should catch up so that you can update Lewis. cc @alan-deanda

**Comment by patrickm02L** [comment]
@johnclary, 

@andrewshensky and I met today to talk through the speed limit changes map. 

**Takeaways**
- The map was created July 20, 2020
- Work order data starts October 11, 2019 (there is some 2018 data)
- The changes are grouped in clusters, and mostly reflect level one (neighborhood) speed limits. Andrew believes this is based on an ordinance passed by Council to reduce speed limit by 5 mph.
- There are 306 unique streets (762 segments) changed - time frame starts from June 2020 and is up to the present

It's possible to track changes that are non-neighborhood changes. 

If this is something that we might be able to pull into the VZ Viewer map later incorporating a feature service would give us real time data. If it's tile then we would get data weekly/monthly. 

Max will be the maintainer of this map going forward. He has created specific instructions for how to log the speed limits changes so we can query it easier.

**Comment by johnclary** [comment]
Sounds great—thanks for the update.
