### ISSUE TITLE
Create Dashboard For Tracking Speed Limit Changes

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#8275]
TED is looking for ways to report on speed limit change progress by tracking Total Streets needing modification, Streets that have been modified, and number of 25 mph sings installed. They would also like reporting on these number by council district

[Here's the app](https://austin.maps.arcgis.com/apps/MapSeries/index.html?appid=b135dddbe79149b88d74405ba780dc42).

**Comment by johnclary** [comment]
Has been delivered. Will open a new issue for future enhancements.
