### ISSUE TITLE
ASMP Feedback Dashboard

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#8276]
Create dashboard to evaluate public feedback for the ASMP Amendments, modeled after the one used for Healthy Streets.

The dashboard can be found [here](https://austin.maps.arcgis.com/apps/dashboards/0e86356f7e3643e28925d2a49173bca5) (internal link only)

**Comment by alan-deanda** [comment]
Submitted first draft to Cole, awaiting feedback.

**Comment by johnclary** [comment]
Dashboard is created. Cole loved it.

**Comment by johnclary** [comment]
@alan-deanda would you a link to the dashboard in this issue's description?

**Comment by alan-deanda** [comment]
@johnclary dashboard linked in the description. closing this issue now.
