### ISSUE TITLE
Update Fee Name & Logic: Temporary Valet Permit Fee (50205) (UAT On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8277]
Update Fee Name & Logic: Temporary Valet Permit Fee
Stakeholders: Paloma, Kim, Isabel

- We should rename 'Temporary Valet Permit Fee' to 'Temporary Valet Space Rental Fee'
    - Don't forget the surcharge.

**Comment by Nadin-Nader** [comment]
@TracyLinder , we checked to see if the logic was working and it is. This card really just needs to rename the fee

**Comment by Nadin-Nader** [comment]
AC Taken out during 1/26/22 Scoping meeting with Vish, Paloma and Kim:

- We need to update this fee logic from $50 per space, to $50 per space **per day** (_currently the system only charges $50 per space)
    - New Logic: `#of on street spaces for valet (75925)` X `Number of Days Requested (75390)` X `$50` = Fee Amount
    - Example: Applicant requests 4 spaces for 2 days. The fee should be (4*2) * $50 = $400

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Demo is sent across for review.
And did two commits - adec6bb10293 & cf63c6437819. Please audit the commits if the demo is good enough.

**Comment by TracyLinder** [comment]
@Nadin-Nader @SubhaShroff when i did my test case 22-000158-RW, the fee logic was not working correctly. I did the test yesterday morning in AMANDA Test. Are we sure the fee logic is working correctly?

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader i just checked 22-000158-RW for the values you entered in infos,  5 * 2 * 50 = 500 is inserted. I think that is correct as per the given formula. I guess, you added the surcharge on top of it, separately doing insert+run.

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader  SCTASK0196025 is submitted for DEV deployment after Nadin gave approval in today's stand up.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This ticket is deployed in DEV and I tested it. It works as per AC.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0199139 is submitted for TEST deployment of this ticket.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This ticket is on TEST and I did the unit testing. Ready for UAT.

**Comment by TracyLinder** [comment]
### UAT Passed, Please promote PROD

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder  PROD Deployment request is submitted - SCTASK0199705.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  PROD deployment is done.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder UAT on PROD Passed per Isabel. Closing card

> [3:05 PM] Pena, Isabell
> Fees calculated correctly and the field name is correct
>![MicrosoftTeams-image (9).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/8308f43c-5002-4562-96b2-8d6bdec217b5) 
>
> [3:31 PM] Nader, Nadin
> Awesome then i will go ahead and close the card.
