### ISSUE TITLE
BUG: ATD - TEMP - Valet Application Fee (83494) NOT Populating (on Prod)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8278]
##  BUG: ATD - TEMP - Valet Application Fee NOT Populating
Stakeholders: Paloma, Kim, Isabel

   - Fee should insert & bill at the time of permit application (same workflow as a TURP or EX; status should update to Pending Payment, then after payment is made update to Internet Pending)
   - The fee is $60 flat (no logic)
   - The ATD Tech Surcharge ROW fee needs to append/insert w/ this fee ($2.40)

**Comment by Nadin-Nader** [comment]
Took out of AC 1/26/22 from Scoping meeting with Paloma; who said that the fee is there it just not inserting:

- We should create a new fee called 'Temporary Valet Application Fee'

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  SCTASK0197247 is submitted for DEV deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0198807 is submitted for DEV deployment of "c4c3058bb351".

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I tested it on DEV. Inserts the fees when application is created. Since DEV portal login is not working, I created application from BO. Please let me know if we can deploy it in TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0199287 is submitted for TEST deployment of this ticket.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is in TEST and working as expected. Ready for UAT.

**Comment by TracyLinder** [comment]
### UAT Passed - Approved to promote to PROD

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  PROD Deployment request is submitted - SCTASK0199713

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader PROD deployment is done.

**Comment by SubhaShroff** [comment]
### Status:
This is PROD deployed. Waiting to close.

**Comment by Nadin-Nader** [comment]
Sent Paloma Isabel and Kim an email stating that this was on PROD and needs to be UATd. I also mentioned that if there are no issues with this that i hear about, i would close this out on Thursda or Friday of this week (2/24-25/22)

**Comment by Nadin-Nader** [comment]
Response from ROW user stating that the application fee is not being inserted at the time of application. Needs to be tested on UATd on TEST portal. 
Paloma is testing..

**Comment by Nadin-Nader** [comment]
@Nadin-Nader please check with Martin on **PROD** deployment. Works on **TEST**

**Comment by Nadin-Nader** [comment]
**Status:**
Currently reviewing with Martin

**Comment by Nadin-Nader** [comment]
@SubhaShroff i spoke to Martin and we scrubbed the commit and compared TEST and PROD. Besides a minor Comment nothing is different or out of place. Please continue to troubleshoot.

**Comment by TracyLinder** [comment]
### PROD UAT PASSED

rsn 12888999

**Comment by Nadin-Nader** [comment]
@TracyLinder @SubhaShroff Passed PROD UAT Closing Card
