### ISSUE TITLE
Create Database Views for MAINT Test Data

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#8279]

**Comment by jaime-mckeown** [comment]
- Created new issue since it had been months since I've worked on this.
- Finally realized that I was trying to use the Status Type field for the parking zones in the database view, but the field is not in the query, only the Status Type of the parking restrictions.
- Created Database View for Active records based on parking restrictions Status Type field, and it finally worked.
- Since it's a view, it should not have to be updated as it is actively hitting the MAINT data. I will need to test this out.
- Worked on creating symbology for the layer since there is overlap between many of the parking restrictions along the same zones.

**Comment by jaime-mckeown** [comment]
Tested making edits to see if changes are visible in the view, they are not. Did some research and found this below.

![image](https://user-images.githubusercontent.com/48842809/151203861-584bd07f-739c-4c36-bc80-b680ee1720f6.png)

**Comment by jaime-mckeown** [comment]
Verified with Thomas at CTM that the current compression schedule for MAINT is once/week on Friday nights.

I asked him if compression could be done on MAINT daily, his response below:

> there is a way yes, but there are probably some dependencies or workflows I am unaware of that may be affected. I would submit a ticket for this one to my group.

**Comment by jaime-mckeown** [comment]
Production data:
- Created database views (Active, Inactive) for MAINT data

**Comment by jaime-mckeown** [comment]
- Talked to John about the issue with needing the database compressed in order to see the changes
- He suggested that maybe we look into exporting versions of the parking zones and restrictions and create the database views from those, then versioning and compression may not be an issue.
- Tried this out and it worked, edited the data, exported, then refreshed the map, and the database view updated
- Created a Script that will export the parking zones and restrictions for the database view, and will recreate view privileges for everyone.
- Added Script to a Script Tool, then put the Script Tool on a schedule to see how that would work. The tool run when Pro is open or closed.
- Have it set to run every hour, will check the updates tomorrow morning to see if they run with me logged out.

**Comment by jaime-mckeown** [comment]
- Created script and script tool for production data, ran once to create layers
- Created new database view from new layers

**Comment by jaime-mckeown** [comment]
@andrewshensky I'm going to leave this issue open and assign it to you. See the comment above with the highlight. You may want to ask CTM if they can start compressing the MAINT database daily to see if that will make a difference for the database views. I don't want to put the request in since it won't be completed before tomorrow. Thanks!

**Comment by johnclary** [comment]
Holding off until parking GIS analyst is hired

**Comment by andrewshensky** [comment]
Closing this issue as it is no longer relevant to current workflows
