### ISSUE TITLE
Create AGOL layer and map for traffic register maint data

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8285]

**Comment by andrewshensky** [comment]
@ChristinaTremel the traffic registry data below was published from maint to agol about a year ago. Let me know if anything else is needed.

https://austin.maps.arcgis.com/home/item.html?id=52222ace4f03402b955858c918b22700

**Comment by ChristinaTremel** [comment]
The traffic registry data from Maint exists on AGOL.
