### ISSUE TITLE
[BUG] [TDR Mod] - System extremely slow since Dec Update

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8286]
Users are reporting the system is extremely slow since the December update.

**Comment by TracyLinder** [comment]
@ChrispinP can you please update this with your findings & the suggested fix? Thank you.

**Comment by TracyLinder** [comment]
KNACK can do a server migration. It will cause 2 hours of down-time. 
City offices will be closed tomorrow 2/3/22, so tomorrow would be ideal.
@ChrispinP will schedule w/ KNAKC & @TracyLinder will send user email blast.

**Comment by ChrispinP** [comment]
Server migration was a success. Will need to confirm with users that this issue is resolved.

**Comment by TracyLinder** [comment]
No issues have been reported. Closing.
