### ISSUE TITLE
Upgrade package.json to newer version

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#8311]
Make sure we're using the most up-to-date version of package.json/package-lock.json in Moped. 

https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion

**Comment by johnclary** [comment]
Resolved by https://github.com/cityofaustin/atd-moped/pull/688.

**Comment by johnclary** [comment]
Resolved by https://github.com/cityofaustin/atd-moped/pull/688.
