### ISSUE TITLE
Bug: C8 Folders inserting FY21 fee amounts (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8313]
### DSD is reporting that the C8 folder is inserting the FY21 fees instead of the FY22 fees.
<img width="851" alt="Screen Shot 2022-01-26 at 5 04 14 PM" src="https://user-images.githubusercontent.com/49930868/151261998-df4cd808-e928-4f81-9345-928339d7daf1.png">
<img width="875" alt="Screen Shot 2022-01-26 at 5 04 26 PM" src="https://user-images.githubusercontent.com/49930868/151262006-e5c0ee81-9b9f-41a0-8724-666cb8a8aeda.png">

**Comment by TracyLinder** [comment]
**Email to Nate, Zach, Amber, Bryan:**

Hi Everyone,

I created a DTS request for this #8313. I know Zach reported this issue well over a month ago and unfortunately it looks to have fallen through the cracks during our mad dash to push everything through before the AMANDA code freeze. I apologize Zach that the burden fell on your team. 

Zach - around how many cases per day or week is your staff having to manually update ATD fees?

Amber/Bryan - do you have a list of current fees that should be on the C8 folder, and the fee amounts? 

Thanks,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
**Notes**
- SPOC is Amber
- We need a list of all fees for the C8 folder and the current amounts.

**Comment by SubhaShroff** [comment]
@vschandramouli 
What I see is all these fees are related to different subtypes of C8. It will be helpful if I can get more details on it. 

- Which fees are added to for which subtype?
-  Which point these fees are added on each subtype. I checked for Final Plat subtype, I think few of those fees are added in Checklist Distribution process with calculate fees attempt.  But I don't see all those fees added.

 So, I think the listed fees are subtype/worktype specific.
I am still trying to trace the fees through the code, that will take a while. Meanwhile if you can get the above information that will help.

**Comment by Nadin-Nader** [comment]
**Status:**

Sent an email to Zac asking for more information for Subha to Troubleshoot. Waiting on Response.

Email Sent:

> Hi Zach,
> 
> Hope you are doing well. I was reaching out to you in regards to card 8313 where you state that the C8 folder is inserting FY21 fees. I have this issue being looked at b one of our developers and she has a few question she needs answers to in order to get this resolved properly.
> 
> Below are her questions:
> 
> What I see is, all these fees are related to different subtypes of C8. It will be helpful if I can get more details on it.
> •	Which fees are added for which subtype?
> •	At which point/process are these fees added on each subtype? I checked for Final Plat subtype, I think few of those fees are added in Checklist Distribution process with a “calculate fees” attempt. But I don't see all those fees added.
> Once we get the answers to these, we can continue to Troubleshoot.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> Product Delivery Manager
> Data and Technology Services
>

**Comment by Nadin-Nader** [comment]
@SubhaShroff here is Zach's response:

> From: Whitaker, Zachary <Zachary.Whitaker@austintexas.gov> 
> Sent: Tuesday, March 1, 2022 2:52 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Cc: Subhashini Shroff <Subhashini.S@launchitcorp.com>; Vishwa chandramouli <Vishwa.c@launchitcorp.com>
> Subject: RE: Need some more info on C8 Folders Inserting FY21 fees Issue
> 

> Nadin, 
> 
> It would probably be easiest to discuss this in a meeting. However, 
> 
> 
> 1.	The fees are determined by ATD during completeness check and are conveyed to intake via a document where they type which fee is necessary. They roughly follow an assignment to sub/work types but that is not a given. 
> 
> 2.	The fee is inserted after the completeness check, but before the formal submittal. I am not sure how you refer to these stages. The fee is an “insert and run,” (this is probably the thing that will help you) as mentioned by ATD staff on that Completeness Check document.  This takes place during the process “CC Distribution” during an attempt of “complete without site visit.”
> 
> Thank you,
> 
> Zach Whitaker 
>

**Comment by SubhaShroff** [comment]
@Nadin-Nader DEV deployment request is submitted - SCTASK0204225 for C8 fees with feecodes - 83427,83424,83477,83478 as Zach mentioned in the call.

**Comment by Nadin-Nader** [comment]
@subha this has been deployed to **_DEV_**. Please UAT

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @vschandramouli  This is tested on DEV and I recorded demo and sent to you for review. Please let me know if we can promote it to TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0205381 is submitted for TEST deployment of this ticket.

**Comment by Nadin-Nader** [comment]
@SubhaShroff  this has been deployed to TEST. Please UAT and make ready for 2pm meeting

**Comment by SubhaShroff** [comment]
@Nadin-Nader I tested it on TEST and the amounts are correct as given in the excel.

**Comment by Nadin-Nader** [comment]
Messaged Zach and asked him to please UAT this on TEST. Waiting on Response

**Comment by Nadin-Nader** [comment]
@SubhaShroff Zach Responded and said that the Fee below, ATD SUB-Construction Plan Non-Concurrent ($1,310.00), Is the one he found that is wrong. Its supposed to be like the other image attached, Construction Plan Non-Concurrent ($2,810.00)

![Contruction Plan Fee.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/8522b374-75eb-4355-9ad0-c7579bda8511)

![Actual Wrong Fee Showing.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/a016778c-82c2-4e63-b17b-33902ca2103e)

**Comment by SubhaShroff** [comment]
@Nadin-Nader  "991d711116a6" - commit is done to correct the Fee amount of ATD-SUB-Construction Plan Non-Concurrent (83425). Once you audit it, I will submit a DEV deployment request.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0207586 Is submitted for DEV deployment of the above commit.

**Comment by SubhaShroff** [comment]
### Status:
Waiting for the DEV deployment to be done.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  The fee amount for ATD-SUB-Construction Plan Non-Concurrent (83425) is changed to $2810 as suggested.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The change is deployed in TEST and looks good for UAT.

**Comment by Nadin-Nader** [comment]
Sent a chat to Zach asking him for permissions to send this to PROD.
Waiting response

**Comment by Nadin-Nader** [comment]
@SubhaShroff Zach gave permission to Push this to **PROD**🎉🎉

**Comment by SubhaShroff** [comment]
### Status:
Deployed on PROD 2 weeks ago.

**Comment by Nadin-Nader** [comment]
Have not heard any issues on this. Closing
