### ISSUE TITLE
Enhancements Banners Permits and Payments in Knack Technician Page

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8318]
Enhancements from review meeting with Christina issue #8271
- Approved - Pending Delivery - Approved and payment made, banners not received

- Need to be to Installed - payment made, banners received, ready to go out

- [x] NEW FIELDS

- Delivered Date
- Picked Up Date

- [x] Add new field "Work Order Status":

- Needs to be Installed (Banner Status = Delivered)
- Issued (Installed/Removed)
- Work Complete (Removed & Shelved)
- Closed (Picked up/Disposed)
- Add new field "Banner Status"
- Pending Delivery - Default
- Delivered
related field: Delivered - Y/N
related field: Will Pick Up - Y/N
- To Pick Up
- To Dispose
- Complete

NEW ENHANCEMENTS

- [x] Page for Delivery/Pick-up Tracking

        a page that has Banners statuses all on one page

         use if for anyone to update the status if they receive a banner or have 
         one picked up from the shop
  

- [ ] Create a button for "Banner Stored"

- [x] NEW PROCESS
Comment if communicated with customer about Pick-up/Disposing of banners

- [ ] Create new pages
work-orders-lpb
work-orders-ots

**Comment by dianamartin** [comment]
LPB Dashboard
- [ ] Removed Other Statuses
- [ ] Added new app status "Approved"

**Comment by moorerst** [comment]
Reviewed updates with the stakeholders. They approved the changes. Added the outstanding items from this issue to the new enhancements issue #8601
