### ISSUE TITLE
PROD Rollbacks on 1/24/22

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8319]
### Per CTM all promotes since Monday 1/24/22 had to be rolled back. We need to figure out what broke and fix it.

**Comment by TracyLinder** [comment]
### RW-Parking

- While attempting to create a folder from the backend, the system wouldn't allow me to continue past the people tab. Threw this error InfoCode=75948 not found in cache.

**Comment by TracyLinder** [comment]
### RW-TURP

  ❌ ROW Usage fees were not added when attempt 'Approved' was saved on process TURP Review (22-012603-RW)
- System should have inserted & billed TURP ROW Usage fees & ATD Tech Surcharge ROW
- _I'm not sure which issue this relates to._

**Comment by TracyLinder** [comment]
RW-TURP Extension 

22-012603

1. User - On process 50680 Permit Extension, user:
    - Updates process infos (start 2/14, end 2/18, 5 days for extension, 5 in tier 1)
    - Saves attempt 'Extension Granted'
2. System
    - Inserted dates in folder infos extension start date, extension end date
    - Updated info _Total Days of Permit Validity_ from 5 to 10.
    - Inserted all ROW usage fees & surcharge & TURP Permit Fee - Extension  (_not sure if amounts are correct_) 
    - Did **not** create a bill ..... _Is it supposed to?_ ❓
3. User creates bill
4. User updates AUP to No (so i can test the manual extension features)
5. User - Pays Fee
6. System:
    - Updated folder status to Active ❌ _AUP = No so this shouldn't have happened_
    - Updated f.expirydate ❌ _should not have happened_
    - I'm actually not sure when the expiry date was updated, i'll need to test again 😞 
7. User manually updated folder status from Active to Expired
8. User did another Extension Granted, w/ new start & end being 2/21 
    - System did **not** update the folder expiry date (_so it was the fee procedure that did it in step 6_)
9. User deleted the fees
10. User saves attempt 'Manual Extension' on process Permit Extension
11. System alert window popped up reminding to check bond, insurance, fee and date range info
12. User clicks OK
13. System:
    - Updated folder status to Active
    - Update folder expiry date to 2/21

**Comment by TracyLinder** [comment]
**To Kim:**

 I just tested this in PROD 2022-012603 RW. Are you able to confirm if the fee amounts are correct? Here are screenshots of the prop & street info tab & the fees the system added when i saved extension granted for 5 days in tier 1. (I had to delete the fees so i could test a $0 payment.) 
![TURP prop info tab](https://user-images.githubusercontent.com/49930868/151458292-edcf309d-724f-4644-b9fd-eb34143823f6.jpeg)
![TURP Usage Fees](https://user-images.githubusercontent.com/49930868/151458302-e4669edf-65db-43c8-9496-fa2a560cdac5.jpeg)

**Comment by TracyLinder** [comment]
**I'm done testing TURP and moving on to EX. I'll ask Kinsley to void the payments I made.**

**Comment by TracyLinder** [comment]
### EX

**Test Cases:**
- EX Private Developer or CIP w/ two streets
- EX ATD (COS)
![EX multi-street](https://user-images.githubusercontent.com/49930868/151464313-f9a216c2-9620-46e8-ae82-bcc890fcadf9.jpeg)
![EX COS Payment Confirmation](https://user-images.githubusercontent.com/49930868/151464322-d8c4c6ae-72ae-466e-8609-ffc3926eaefc.jpeg)

**Comment by TracyLinder** [comment]
Test Notes:

1. Portal User - Submitted EX-ATD (COS) application 22-012667-EX
2. System:
    - Updated folder status to? 
    - Inserted fees Excavation Permit Fee - Secondary ($95) & Surcharge ($3.80) ✅
    - Created bill & paid it
    - Updated folder status again? 
    - Inserted processes (not sure which ones)
 3. I voided the payment ASAP, and cancelled the bill
 4. User saves Approved attempt on Web Acceptance Process
 5. System updates folder status to Pending, probably added more processes (_not sure_)
 6. User updated folder infos (added row usage info, updated AUP to Yes
 7. User saves 'Approve' attempt on process Excavation Intake & Review
 8. System did nothing (❓_is this a bug? were fees supposed to be inserted?)
 9. User clicks Insert & Run Procedure; clicks 'ROW Usage Fees' from menu
 10. System inserts Right-of-Way usage fees ($49.50)
     - ATD Tech Surcharge ROW was not inserted. Probably a bug. ❌
11. User manually adds surcharge using Insert & Run
12. System Inserts ATD Tech Surcharge ROW ($1.98)
13. User creates bill
14. Payment is made (no. 7439976)
15. System:
    - Updates folder status to Active
    - Inserts issue date & expiration date
16. **next up will test extensions**

**Comment by TracyLinder** [comment]
## Test Notes EX Private Developer or CIP & multiple streets

1. User submits portal application
2. System: 
    - ✅ Creates 2 EX permits 
    - ✅ Makes a parent/child relationship between the folders
    - ✅ For each permit inserts & bills Excavation Permit Fee - New ($290) and ATD Tech Surcharge ROW ($11.60)
    - ✅ For each permit updates folder status to Pending Payment
    - ✅ Does not insert any folder processes 
3. Bill is paid
4. System:
    - ✅ Updates folder status to 'Internet Pending'
    - ✅ Inserts processes Web Application Acceptance and Traffic Control Inspection
5. User updates folder infos
    - ❌ Folder info that shouldn't have been inserted - Total Linear Footage (76300)
    - Updated AUP to Yes
6. User saves attempt 'Accepted' on Web Application Acceptance process
7. System:
    - ✅ Inserts 3 processes (Activity Log, Right-of-Way Admin, Excavation Intake & Review)
    - ✅ Updates folder status to 'Pending'
8. User saves 'Approved' attempt on process Excavation Intake & Review
9. System: Does nothing. `❓Is this correct, or should the system have added fees?`
10. User manually adds fees & creates bill.
11. Bill is paid
12. System:
    - ✅ Updates folder status to 'Active'
    - ✅ Inserts folder issue & expiration dates
**Moving onto Extensions**
13. I manually update folder status to 'Expired' and AUP to No
14. I had the same results with extension features as I did with the previous use case.
**Moving on to Manual Extension Update.**
15. ❌ 'Manual Extension' is not an attempt type on process 50075 Right-Of-Way Admin. Related to #7991

**Comment by TracyLinder** [comment]
## RW - Valet Parking Temporary

1. User submits portal application
2. System:
    - Does not insert a fee `❓is this a bug?`
    - Updates folder status to 'Internet Pending'
    - Inserts 2 folder processes: Web Acceptance, Traffic Control Inspection
3. User updates folders infos. Updates AUP to Yes
4. User saves attempt 'Accepted' on web intake process
5. System:
    - Inserts 2 processes: Activity Log, Temporary Valet Intake
    - Updates folder status to 'Pending'
6. User saves attempt 'Accepted' on process Temporary Valet Intake
7. System:
    - Inserts 1 process: Temporary Valet Review
    - Updates folder status to 'In Review'
8. User saves attempt 'Approved' on process Temporary Valet Review
9. System: ❌❌ Throws error: `Error in DefaultFee_RW_50205 for number of spaces: 4 and number of days: 2. Error message: Error calculating formlua based fee. Contact the Help Desk`❌❌
10. User clicks OK
11. User updates folder info 'Number of Blocks' from 0 to 1, and tries to save the 'Approved' attempt again
12. System: ❌ Same alert thrown
13. User: Updates folder info 'Number of Days' from 2 to 1 and tries to save the 'Approved' attempt again
12. System: ❌ Same alert thrown
13. I tried all kinds of things to work around this error (including updating AUP to No). Nothing worked. 
14. User attempts to manually add the fee using the Insert & Run Procedure and clicking 'Temporary Valet Permit Fee'
15. System: Same alert thrown
### `This is a major issue / stoppage / no workaround `
FYI @Nadin-Nader

**Comment by TracyLinder** [comment]
### RW-Street Vendor UAT

1. User submits portal application 22-012706
2. System: 
    - Inserts 2 fees and creates a bill: Vending Application Fee ❌($150.00)❌ and ATD Tech Surcharge ROW (6.00) 
    - **Vending Application Fee amount should be $320. This is a bug related to #7672**
    - Updates permit status to 'Pending Payment'
3. User:
    - Cancels bill
    - Inserts correct fees
    - Creates bill
    - Pays bill
4. System:
    - Updates folder status to 'Internet Pending'
    - Inserts folder 2 processes: Web Acceptance, Traffic Control Inspection
5. User saves 'Accepted' on web acceptance
6. System:
    - Inserts 2 processes: Activity Log, Vendor Intake
    - Updates folder status to 'Pending'
7. User:
    - Updates folder infos, updated AUP to Yes
    - Saved attempt 'Accepted' on process Vendor Intake
8. System:
    - Inserts 1 folder process: Vendor Review
    - Updates folder status to 'In Review'
9. User saves attempt 'Approved' on process Vendor Review
10. System: 
    - Updates folder status to 'Pending Permit'
    - Inserts & bills 2 fees: Annual Space Rental Fee ❌($650)❌ and ATD Tech Surcharge ROW ($26)
    - Annual Space Rental Fee amount should be ❌($715)❌
11. User pays bill
12. System: Updated folder status to 'Active', inserted folder issue & expiration date
--Done Testing--

**Comment by TracyLinder** [comment]
**I'm done testing for the night.**

**Comment by TracyLinder** [comment]
## UAT TURP - Franchise
_Izzy reported issues w/ extending a franchise TURP this morning. I need to troubleshoot._
- Test 2022-013189 RW

**Comment by TracyLinder** [comment]
**Update**

- We're meeting w/ CTM on Friday 2/18 to discuss. 

**Issues still affected by rollbacks:** 


- #6255 
- #7283 
- #7631 
- #7991 
- #7785 
- #7672 
- #8166 
- #8187

**Comment by Nadin-Nader** [comment]
@TracyLinder I have sent the first 16 commits to the DevOps CM Team to send to **_PROD_** under **SCTASK0201936**

**Comment by TracyLinder** [comment]
## Tracy's PROD UAT 
- We're told the rollbacks have all been re-promoted. We need to UAT in PROD again. 

### RW - TURP - PVT
_2022-032194 RW_

1. User submits portal application
2. System:
    - Inserted & created bill: TURP Permit Fee - New ($320.00), ATD Tech Surcharge ROW ($12.80)
    - tbd

### RW - TURP - COS & Secondary
_2022-032198 RW_

1. User submits portal application
2. System:
    - tbd

### EX - PVT
_2022-032202 EX_

1. User submits portal application
2. System:
    - Inserted fees & created bill: Excavation Permit Fee - New ($290.00), ATD Tech Surcharge ROW ($11.60)

**Comment by TracyLinder** [comment]
The EX Folder constantly updated AUP from Yes to No in many of my tests.

**Comment by TracyLinder** [comment]
Can we do a bulk folder re-default on TURP & EX?

**Comment by TracyLinder** [comment]
### Izzy's Extension Granted UAT
_12710246_

- She re-defaulted the folder, and that resolved the 'YES' error.
- ✅ This was COS, the system correctly inserted, billed & paid the fee
- ✅ System updated the folder infos Extension start & end dates
- ❌ System did not update folder expiration date

**Comment by TracyLinder** [comment]
## Current Issues Friday 3-11 / 4pm

### EX Folder

- Franchise Utility WorkTypes needs to be "Yes" on AUP in order for it to update, Currently it is set to "NO" 
    - #8671 
- The printed permit is populating the wrong expiration date. 
    - #8671 
- The extension comment is not inserting in the folder description in certain situations. 
    - #8671 
- Issue with folder expiration date not inserting in certain situations. 
    - #8701

### UC Folder
- System won't accept checks as a valid payment type. 
    - #8034 


----
### RW Folder
- ROW TURP Usage fees not inserting
    - #7829 
- Extension Bugs
    - #7785 



----
### Other
This week a few features that we released months ago stopped working in PROD:
- Unable to pay fees on portal for Rejected or Closed ROW Permits
    - #8679 
- Folder In Date Rule w/ Internet Pending Status
    - #8693

**Comment by TracyLinder** [comment]
<body link="#0563C1" vlink="#954F72">



Issue # | Impact | Folder Type | Description | Status
-- | -- | -- | -- | --
8701 | Urgent | EX | Issue with folder expiration date not inserting in certain situations. | We're sending a patch through DevOps. If all goes well it will be fixed in PROD by Thu/Fri of next week.
8671 | Urgent | EX | The printed permit is populating The wrong expiration date. | We began working on the fix for this today. Should be fixed by next week.
8034 | Urgent | UC | System won't accept checks as a valid payment type. | The patch was sent to PROD yesterday. Pending UAT confirmation that it's fixed.
7829 | High | RW | ROW TURP Usage fees not inserting | The fixes are pending UAT in Test, then we will promote to PROD
7785 | High | RW | Misc. TURP Extension bugs | These may have been resolved. Pending PROD UAT confirmation.
8679 | High | EX, RW, DS, UC, PSM | Unable to pay fees on portal for Rejected or Closed ROW Permits | Scoping; new bug report
7672 | High | RW, PSM | Misc. fee amount updates rolled back | The fees are identified. We are debugging.
8693 | Medium | EX, RW, DS, UC, PSM | Folder In Date Rule w/ Internet Pending Status | Scoping; new bug report
8671 | Medium | EX | Franchise Utility WorkTypes needs to be "Yes" on AUP in order for it to update, Currently it is set to "NO" | We began working on the fix for this today. Should be fixed by next week.
8671 | Medium | EX | The extension comment is not inserting in The folder description in certain situations. | Debugging.
8166 | Low | RW, EX | ROW Permit FDU Infos Need to be Alphanumeric | Fixed in PROD. Pending Prod UAT confirmation.



</body>

</html>
</div>

**Comment by TracyLinder** [comment]
### Testing TURP Extension Features in PROD
**🎉 Everything Worked!**



----
**COS**
_2022-034656 RW_

🎉 Everything Worked! 🎉


----
**PVT**
_2022-034659 RW_

- TURP ROW Usage fees did not insert; we're fixing on 7829
- 🎉 Everything Worked! 🎉


----
**Franchise**
_2022-034661 RW_
- 🎉 Everything Worked! 🎉

**Comment by TracyLinder** [comment]
Good job team! You fixed all the crazy bugs.
