### ISSUE TITLE
[Bug] Lightsail server missing the VZE replicated data

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8324]
Investigate what's causing missing data. Make updates to resolve.

![image.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/c27fc07b-0b3a-4a2c-99ec-55ae43695ae5)

@frankhereford add thoughts on any further steps if this is more than a quick fix.

**Comment by frankhereford** [comment]
I imagine this is actually related to the fact CTM shutdown our airflow server during the backup the other night. I'm going to make a new issue related to moving that back-up window and also pull a backup from the day before. Thanks for the heads up.

**Comment by frankhereford** [comment]
The particular event (failed restoration of VZDB on lightsail server on 2022-04-14) has been addressed and the service restored. 🏁
