### ISSUE TITLE
[BUG] "Signal_Detector" object table in TEST | Austin Transportation Data Tracker | 27 OCT 2021 not showing up

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8326]
Joshil B.
AMD

Messaged
>I'm not sure if I messed it up or it's a server issue but the test server no longer displays the "signals_detector" page or the records in the builder (but the records still exist per the api). 

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/cdbf8cb0-0c0b-409d-ba59-47a4d9af0ae3)

**Comment by dianamartin** [comment]
Chia slacked
>Frank and I got a message from Joshil about some weird behavior in his test Data Tracker instance. The records won’t show up in the builder, and when I open the console there is an error `TypeError: Cannot read properties of undefined (reading ‘input_type’)`. 

>When I query the records in Postman, nothing has undefined. Does anyone have experience with a similar error? He thought he might be a result of an image he uploaded the api, but hes now removed them and the error persists

**Comment by dianamartin** [comment]
Chrispin logged in and also saw that the table records weren't populating. I created a Knack ticket
>A colleague and I are working in an test environment app and he was working on an API and now the object table he's sourcing is not longer showing up. (Included the screen shot above)

**Comment by dianamartin** [comment]
Knack said on 1/31
>Hi Diana,
﻿Just wanted to let you know we're looking into this and will let you know soon what we've discovered.

**Comment by amenity** [comment]
@dianamartin gave Joshil access to a Test environment.

**Comment by dianamartin** [comment]
Joshil messaged 3/10
>So it looks like they fixed the October test server. Did they find the issue and if so, what was it?
Or rather was it their issue or my meddling?

I replied
>I just checked the last conversation with the vendor and they hadn't notified me they fixed anything.. 
>- in Jan they had said:
"Hi Diana,﻿ Just wanted to let you know we're looking into this and will let you know soon what we've discovered."
 >- so I think it was your meddling 

![image](https://user-images.githubusercontent.com/21112975/158827180-71221891-f5c4-413e-a476-af440ca26941.png)
