### ISSUE TITLE
Integrate Work Orders with New Inventory Request

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#833]

**Comment by amenity** [comment]
@johnclary - did you have someone in mind you wanted to review this?

**Comment by amenity** [comment]
@johnclary - did you have someone in mind you wanted to review this?

**Comment by johnclary** [comment]
It may be ideal to have technicians add their inventory items directly to work orders, and then have have a process that automatically generates the inventory request form in the finance system from the data tracker. 

In this model, the technician never has to use the finance system, they manage their inventory requests on their workflow.

The workflow would be:
1. Technician adds inventory to work order in Data Tracker
2. Technician submits inventory for approval
3. Supervisor approves, revises, or returns to technician for modification
4. Once approved, the inventory items on the work order are flagged as “Requested”
5. An inventory request is generated in the finance system
6. Inventory staff fulfill work order
7. The inventory items on the work order are flagged as “Issued”
8. If needed, the technician may add additional items to the work order and we go back to step 2.

Questions:
- How do we handle the tracking of “working stock” items that techs use (these do not require an inventory checkout)
- ???

If we did this, we would need to:
1. Update the Work Orders/Data Tracker inventory section to support submitting an inventory request for approvall
2. Create a supervisor view in the Data Tracker for approving inventory requests
3. Update the transactions table in the data tracker to support these approval statuses
4. Re-build the (in-progress) work order integration to support two-way communication between work orders and the finance 

@dianamartin let's discuss since we didn't have time today. I would say this adds another 8 hours of development on the integration

**Comment by johnclary** [comment]
Closing this and opening a new issue to generate inventory request from work order.
