### ISSUE TITLE
Ability to create a new regulation

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8331]
Ability to create a new reg that is either an Install or a Delete.

Per discussion w/ stakeholders:
- implement ability to delete a reg when creating a new reg parent
- either (1) add a separate table for deletes vs new regs or (2) show the reg action type (delete or install) as a column on the regulation children table

---- Notes from 2/ 7 meeting  ---
Deleting a reg, will always have new parent reg, reference old parent reg, and old regulation
It is common to both delete old regs and create new regs on a single parent.
Staff need to see the regulation details of delete regs.
possibly two tables on reg parent (one for add and on for delete)
add column for action (install or delete) on reg items

**Comment by ChrispinP** [comment]
Ability to add a Parent Regulation added as a workflow process with the ability to add and edit individual regulations to that parent before submitting. Ability to add Regulations thereafter added to the Parent Regulation Details page. Similar to the edit forms, need to determine which fields should be present when a regulation is being created.

**Comment by johnclary** [comment]
Per discussion w/ stakeholders:
- either (1) add a separate table for deletes vs new regs or (2) show the reg action type (delete or install) as a column on the regulation children table

**Comment by ChrispinP** [comment]
Updated Package Details page to show separated tables for installed and retired regulations. An action button on the Installed table allows you to retire individual regulations.
![image](https://user-images.githubusercontent.com/67915167/153515450-20df3309-b9a4-44e4-9d54-235a7e4fbebf.png)

We need to determine if only certain user roles should have access to retiring regulations. Ready to review

**Comment by ChrispinP** [comment]
Ability to create new regulations is part of the Drafting process with the 4 sub-processes allowing for Installs and Retires with the ability to edit and delete these new or copied regulations.
![image](https://user-images.githubusercontent.com/67915167/188958925-07d70b2a-da1a-4768-a6ef-860b6d6088eb.png)
![image](https://user-images.githubusercontent.com/67915167/188959034-7da0b827-a64c-411c-b579-038264393773.png)
