### ISSUE TITLE
Ability to edit a regulation

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8332]

**Comment by ChrispinP** [comment]
Ability to edit both Parent and individual Regulations added to Details pages. Will need to determine if certain fields will need to be present or removed and whether they should be changed from short text to multi-choice selections to limit data entry errors.

**Comment by ChrispinP** [comment]
Kept existing fields for now, removed old multi-page add/edit process since the review process will be separate.

**Comment by ChrispinP** [comment]
This is no longer part of the Details pages and is part of the Draft Builder and Regulation Editor pages for the review process.
![image](https://user-images.githubusercontent.com/67915167/188954181-ac700fcb-f5ef-4947-af51-79a3869ea624.png)

Regulation Line Item # and General Location are new required fields to improve data quality for future regulations.

complete, closing.
