### ISSUE TITLE
Ability to review and approve a regulation

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8333]
1. Anyone drafts a reg parent with child regs
2. User assign the reg parent to an engineer
3. Two approval layers based on engineer area:
-  1st level: Area engineers (or delegate). E.g. South area: Allison M > Eric
- 2nd level: engineering manager (Eric, Anna)
4. Engineer approves, modifies, rejects. Can edit individual regs and parent reg. The approval happens on the parent reg.

Make sure we've got audit for each role in the process (drafter and approver).

**Comment by ChrispinP** [comment]
Added Assign and Review buttons for the reg package. Lead & Area Engineers will use the same buttons and can review at the same time or after one another. Audit fields created and set.
![image](https://user-images.githubusercontent.com/67915167/154727832-0b5fb877-bdce-4362-9ffc-c483d9d9f632.png)

Need to determine/clarify if the review results in a status decision such as reject/approve or if it stays in review until it is approved. Also need to construct a list of users who will be reviewing regulations so roles can be assigned.
