### ISSUE TITLE
Traffic Register Prototype Discovery

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8342]

**Comment by ChrispinP** [comment]
- List of Lead Engineers, Area Engineers, Users, & Viewers
- Determine if Packages should Draft every time a change is made or every time a child reg is added/retired.
- Remarks > Notes?
- Add Package Comments & Table?
- Install > Active?
- Regulation Type Subgroups/Subtypes?
- Does Code Section or Regulation Type Code need to be displayed for each reg? 
Such as: BUS STOP 12-1-12(B)(5)
- Is there a standard set or list of Restrictions (Days, Times, Hours)
- Does Restriction apply to individual regs or to the entire package?
- Should records indicate they have a Restriction with an icon or status?
- Should there be an audit log for each package or are details sufficient?

**Comment by dianamartin** [comment]
# Diana's Notes
Want Advanced Search function on Regulations Main Table

Remarks (renamed to "Notes") - "Yes, sounds good"
Reason for remarks, why did they put the regulation in there. Place to put the request is from Community and Other. 

Individual comments in a table
- Engineers might want to have that

Tickets Issued
Justify how we did it in the package

Choose to create a new reg and add a remark for the actions taken. 

Option to view a copy
- PDF

**Comment by ChrispinP** [comment]
closing issue out now that we are finishing up the prototyping phase. Further work will be documented in their respective issues.
