### ISSUE TITLE
Add New Steepness Data to Online Bike Map

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#8352]
The current dataset used in the online bike map is not set up properly to be updated easily. I have created another steepness dataset that will allow slope and direction updates to be made and reflected on the map in real-time. 

Need to clean up some points that are closely clustered.

**Comment by johnclary** [comment]
This layer is ready to go. Let's wait for print map to be finalized.

**Comment by andrewshensky** [comment]
Closing this issue as it is now outdated
