### ISSUE TITLE
Get GIS Utility Pole Data from Bluebonnet Electric COOP

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-data-tech#8354]
Harrell finally let me know that he spoke to George M. at Bluebonnet. He gave me Jason Ks number to call to get the GIS data from.

**Comment by jaime-mckeown** [comment]
Called Jason, left voicemail.

**Comment by johnclary** [comment]
@jaime-mckeown plz follow up with Jason

**Comment by jaime-mckeown** [comment]
- Received GIS data from Bluebonnet
- Published to AGOL
- Added to Harrell's Pro Project and configured to his liking
- Sent Andrew contact info for utility pole providers
