### ISSUE TITLE
Create & Maintain SIF Workflows

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8357]
Start a SIF/AMANDA workflow on Miro:

1. PM identifies SIF requirement, either during site plan, plat review (they are assigned via ATD Engineering Review)
    - Perhaps use a process info 'SIF Required?' and if Yes, system would create a child SIF folder when attempt is saved.
 2. System creates the SIF child folder; copy down the data we want from the parent folder (properties, people, any matching info fields that we can map). f.status = In Review
 3. The SIF Assessment process needs to show up on ATD Engineering
 4. User fills out the rest of the SIF folder
 5. User provides the customer w/ Formal Assessment (outside of AMANDA)
 6. User saves Formal Assessment attempt on SIF Assessment Process
 7.  ATD will repeat steps 5 & 6 until the Final Assessment is due/ready
 8. Final Assessment time - ATD user adds & bills fee, adds fee data to free-form, sends invoice to customer, saves 'Final Assessment' attempt on SIF Assessment process

**Comment by vschandramouli** [comment]
Created workflow on Miro. Screenshot below. @TracyLinder  Please review and let me know if something needs to change. 

![image.png](https://images.zenhubusercontent.com/5f50fe1f66d1a40f7f557fb4/dcce7b9d-7f23-4ac6-bc3f-3a1f0b9c9546)

**Comment by TracyLinder** [comment]
The first pass looks great. Let's talk about this on Wed. We need to add PR folder review to the workflow.
