### ISSUE TITLE
Provide report of inactive inventory items with a zero quantity

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8358]
Send AMD (Ronnie, Ray, Johnny) a list of AMD inventory items which are inactive but have a quantity > 0

**Comment by dianamartin** [comment]
Emailed stakeholders
>Hi Ronnie/Ray/Johnny, 
I’ve exported out a list of all inventory items that have a quantity under 0 (32 records), only three of those records are “INACTIVE” status. See attached .xlsx.
>- 3 section Astro-Brac Kit with 84 inch cable.| EA
>- Cable, Quad (Four) Twisted Pair| FT
>- Composite Cable with RG59/u Coax and 18/3 Power cable| FT
>Let me know if you need anything else.
