### ISSUE TITLE
Connect Work Orders to Inventory Request

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#836]
- Create work order object and connect to inventory request. Fields:
- [x] `Location` - _Locations>Location Name_ (short text) - **(connection)**
- [x] `Work Column` - _Work Needed_ **(text formula)** `{WORK TYPE TROUBLE CALL}{WORK TYPE SCHEDULED WORK}
- [x] `Lead` - _Technician Lead_ **(connection)**
- [x] `Support` - _Technician_Support_ **(connection)** 
- [x] `Signal ID` - _signals_SIGNAL_ID_ **(number)**
- [x] `School Zone Name` - _school_zone_ **(connection)**
- [x] `Work Order ID` - _ATD_WORK_ORDER_ID_ **(short text)**
- [x] `Status` - _WORK_ORDER_STATUS_ **(multiple choice)**

Also, add a yes/no: "Work Order?" that defaults to `Yes`. If `No`, show "Work Location" free text field.

Display name: maybe? Signal Id - Location Name – Work Order ID - Lead
anything not closed is available to search
can we pull task order from work order?

**Comment by dianamartin** [comment]
@johnclary New object [`work_order_signals`](https://builder.knack.com/atd/finance-purchasing#data/object_33/fields).
Added display name (text formula)
Added to form with display rules to show `Work Location` only if `Work Order` is "No"

**Comment by johnclary** [comment]
@dianamartin woohoo. thanks. will prioritize the WO integration.

**Comment by johnclary** [comment]
@dianamartin i have loaded some work orders into the inventory app. you're welcome to do your development on the request form.

**Comment by dianamartin** [comment]
I've added the `work_order_signals` field on the `New Inventory Request` form and `Edit Inventory Request` forms. 

### Approvers
- [x] `Edit Inventory Request` form 
- [x] `Edit Inventory Request` form  - FDU Review form

### Viewer
- [x] `Edit Inventory Request` form

**Comment by dianamartin** [comment]
Form was configured pretty easily. Had to update the details widget to show the Work Location and the Work Order Signals. The display rules on the forms also had to be updated to hide or show the correct fields.
