### ISSUE TITLE
Update status for separated staff's accounts

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8365]
~25 of AMD's Data Tracker accounts are users who have left the City or no longer work for AMD. CSV [here](https://drive.google.com/file/d/1aVUc1WMJW_SSZ4VU7ItXmSRk6e5SAr5c/view?usp=sharing). 

And John is apparently still "Support Staff" for AMD. :P

**Comment by amenity** [comment]
@dianamartin - this is good to go. I got bounced emails from a handful of users when trying to create Moped accounts and updated the CSV. Hopefully I didn't mess up the formatting editing.

**Comment by dianamartin** [comment]
Updated accounts in the spreadsheet, added a new field "Action" to track which ones I completed. All accounts listed were changed to "inactive".
