### ISSUE TITLE
Perform minor updates to DTS Service Request form and service-bot script

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8371]
**_WIP - I still need to make sure this is comprehensive before pulling it into the backlog!_**
These should be in unison (pretty quick succession) by Apps and (then) Dev. 

## Automated bot-mail
This [email](https://user-images.githubusercontent.com/1463708/179323669-5eaf783a-6dc3-403d-97ec-ef3f4ef06d58.png) needs to be updated with Andrew's name instead of Jaime's. 
- Completed 10/5/22 / @KaroEngstrom 

## Signs & Markings re-name
The Street Banners program recently moved to ATD's Shared Mobility division, so the previous "SMB"—Signs, Markings, and Banners—acronym has changed to "SMD"—Signs and Markings Division.

The DTS Portal dropdown "Signs & Markings" is good to go. 
- [x] Update the [label "Workgroup: SMB"](https://github.com/cityofaustin/atd-data-tech/labels?q=Workgroup+SMB+) to "Workgroup: SMD" in the atd-data-tech repo
- [x] Update [atd-service bot](https://github.com/cityofaustin/atd-service-bot) to map "Signs & Markings" to "Workgroup: SMD"

## Project Delivery
- [x] Add "Project Delivery" to dropdown - **Apps**
- [x] Update label `Workgroup: PD` to `Workgroup: PDD`
- [x] Update atd-service-bot to map "Project Delivery` to `Workgroup: PDD`
![Screen Shot 2022-02-02 at 12 12 42 PM](https://user-images.githubusercontent.com/1463708/152212951-4a6cf65c-3873-4209-a4e2-c0cc702f8c48.png)

**Comment by amenity** [comment]
Let's document this process so that Apps team members can handle it in the future.

**Comment by amenity** [comment]
@dianamartin @mateoclarke - not urgent, but let's get this process documented while @johnclary is still here. 🧠

**Comment by amenity** [comment]
@chiaberry @johnclary - do y'all think this is something we could document for an Apps-er?

**Comment by amenity** [comment]
Sounds like this could actually be broken up into two separate issues and that the Apps team could fix the email if it's in DTS Portal. (Can't check now since Knack is down. 😅 )

**Comment by KaroEngstrom** [comment]
### T 10/4/22 

Two related issues 
* #9020
* #10058

@amenity Could this be turned into an epic for these related issues?

**Comment by ChrispinP** [comment]
also related #10212

**Comment by johnclary** [comment]
@KaroEngstrom the short answer is yes, we need to coordinate these changes with a dev. 

See [this blurb](https://github.com/cityofaustin/atd-service-bot/blob/6624dedd031168e9c7152d4ad68a6085d7294b3f/intake.py#L9) from the integration script.

```
You must update [the integration script] if you change any of these in the DTS Knack app:
- Workgroup names
- Any pre-defined choice-list options (impact, need, application, workgroup, etc)
...or if you change any of these things on github:
- repo names
- labels
```
