### ISSUE TITLE
SIF Folder Configuration

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8375]
### The initial folder configuration. Development began Feb 2, 2022. 

- Updated Specs sheet with codes configured by Priya is [here](https://cityofaustin-my.sharepoint.com/:x:/g/personal/tracy_linder_austintexas_gov/EXdDr5oy9wlHrmzdLkMZjCsBIvBWk_AUpdrAj0HtcDIgHw?e=Y4emMH)

**Comment by vschandramouli** [comment]
@Lpriya-LIT  I updated the Specs sheet and added Freeform data. Please let me know if there are any questions.

**Comment by TracyLinder** [comment]
### Specs Sheet Updated

I added a new folder info today 'Mitigation Offset'
FYI @Lpriya-LIT

**Comment by Lpriya-LIT** [comment]
@TracyLinder @vschandramouli I have completed the SIF folder Configuration in Localhost.
Testing is in progress.
Will send you an update once I'm done with Initial testing.

**Comment by TracyLinder** [comment]
We cannot promote this until a folder group is decided. #8495

**Comment by vschandramouli** [comment]
Items that need to be added as part of config - 

- New column in Freeform 
-- Description : Comments
-- Type: Alpha

- New info fields in PR folder (maybe in SP C8 also? Need to confirm with Tracy)
-- Description : SIF Folder Row ID
-- Type: Numeric 

- Create two new user accounts 
-- ATD Engineering User
-- ATD SIF Review User

- Create new Process 
-- Description - ATD SIF Review 
-- Assigned to - ATD SIF Review User
-- Statuses - Open, Closed 
-- Attempts - TBD

@Lpriya-LIT @TracyLinder

**Comment by TracyLinder** [comment]
@Lpriya-LIT @vschandramouli 

Are we ready to promote this to DEV & Test?

**Comment by Lpriya-LIT** [comment]
@TracyLinder We can promote to Dev first and test whether it works as expected and then request for Test promotion . I'm almost done , will commit the changes and update you. 
we need to create 2 user groups , this is not part of DevOps. So I will create a service now ticket and assign it to Amanda Support group.
@vschandramouli

**Comment by Lpriya-LIT** [comment]
@TracyLinder Committed the configuration changes and sent the dev deployment plan to @Nadin-Nader.
Once its deployed to Dev , will verify and update here.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV please UAT

**Comment by Lpriya-LIT** [comment]
Done a commit to add the new folder group 'SIF'.
@Nadin-Nader Please request for Dev deployment , have sent the deployment plan

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0210699**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been deployed to DEV, Please UAT

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Dev, We can Deploy to Test once all the additional corrections are done and approved by SIF Team

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder all 6 commits have been sent to be deployed to **_TEST_** By the DevOps CM Team under **SCTASK0213187**

> Commit list:
> 8375 - 28c3faeef4e7
> 8375 - 2ce43d8a7eff
> 8833 - 2d133cafadee
> 8728 - 218f353bbb29
> 8726 - 4fccec6ebbad
> 8725 - aa6db6c443df

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been deployed to TEST. Please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder Verified SIF configuration in Test, looks good.
