### ISSUE TITLE
Connect Purchase Requests to Item Restocking

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#838]
**As an inventory manager, I want to be able to trigger an inventory restock when I close out my purchase request.**

**Comment by dianamartin** [comment]
Create a button to set-up a restock from this page? Will work on this tomorrow.

**Comment by dianamartin** [comment]
Created a page `Orders` page.
That has a table of invoices that are in a `Pending Invoice` that need to have the orders confirmed and a shipping receipt attached. 

There is another invoice table that is called `Received Orders` that has invoices with confirmed received orders. 

The third table is of the invoice items, this has a details page that has a `Restock` button that also adds a transaction beneath it.

**Comment by dianamartin** [comment]
There is a section of the `Orders` page called `Restock Items`. This shows which items have been received and restocked or not. 

The user has the ability to click the `Details` button and add a Restock based on the Received Quantity on the Purchase Request.
