### ISSUE TITLE
Ability to copy a regulation during the creation workflow

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8387]
When creating new regulations I need the ability to copy a regulation to the same regulation parent so that I can do my work quickly without entering the same data repeatedly.

**Comment by ChrispinP** [comment]
The Add Regulation process has been updated to a 2 step process. First we determine if the new regulation is replacing a retired one, secondly, we decide if we want to copy that retired regulation (with the exception of a couple fields such as comments) and then are directed to a second page to enter regulation information only if a previous regulation is not copied.
![image](https://user-images.githubusercontent.com/67915167/153516375-61953a4b-132a-4aeb-939c-6490df37cfbf.png)
![image](https://user-images.githubusercontent.com/67915167/153516404-4a442cda-c308-4e4c-a02f-0de318a2182a.png)
![image](https://user-images.githubusercontent.com/67915167/153516470-15a41b5d-3764-4a1e-bbfc-cec715d8bea4.png)

Ready to review

**Comment by ChrispinP** [comment]
3 of the 4 sub-processes for the updated Draft Builder copy approved regulations by default.
![image](https://user-images.githubusercontent.com/67915167/188956855-1e4597cb-7f50-4f43-b0fd-3623df3f8c10.png)
![image](https://user-images.githubusercontent.com/67915167/188956950-9d41bb4e-6c2c-4903-b26f-7978099b7b36.png)

The drafting process also automatically updates the connected approved regulation

closing as complete.
