### ISSUE TITLE
Meet with Finance and AMD to Discuss Finance Tracking Process

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#839]
Scheduled for 11/21

**Comment by johnclary** [comment]
Agenda:

- 
- clarify when a request can be `cancelled`

**Comment by johnclary** [comment]
postponed to 12/9

**Comment by dianamartin** [comment]
### NOTES from meeting

Try to track mods and upgrades instead of a PM task order

Need to charge inventory item then to a different funding source that what the others are being charged to.
