### ISSUE TITLE
Provide documentation on Moped Active Directory integration

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8390]
@sergiogcx - In the Moped users skillshare that you did last fall, you mention that setting up the Active Directory integration was super hairy that you had written extensive private documentation. However [that section is empty on Gitbook](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/dev-guides/authentication/single-sign-on-with-ctm). 

Would you please add the documentation you've written into Gitbook somewhere, whether it's the public Moped docs or the private Dev Gitbook? If you can't find that previously-written documentation, this issue can be re-sized and instead represent writing the bare basics that other devs will need.

**Comment by sergiogcx** [comment]
@amenity This is done, let me know if there is more detail needed.

**Comment by amenity** [comment]
Thanks, @sergiogcx. 🙏  @chiaberry @mateoclarke @frankhereford @tillyw - please take a look at [these docs](https://atd-dts.gitbook.io/moped/dev-guides/authentication/single-sign-on-with-ctm) and comment here if there's any other information you need.
