### ISSUE TITLE
Update Moped Data Tracker synchronization to point to Production Data Tracker

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8393]
- Moped Project ID: `field_4133`
- Moped Project Name: `field_3857`
- Moped Project Status: `field_4136`
- Knack scene for data push: `scene_514`
- Knack view for data push: `view_3089`

**Comment by johnclary** [comment]
@frankhereford ☝️ this is ready to go!

**Comment by frankhereford** [comment]
Completed & merged.
