### ISSUE TITLE
Track project modified date

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8398]
We need to track when a project was last modified, including when related entities are modified. This is captured in `moped_project.updated_at`, but, as far as I can tell, the value is not currently updated after project creation.

This list needs to be reviewed, but we can hopefully manage this with a single trigger that covers most (if not all) tables of concern.

I believe we'll need to listen for inserts or updates on these tables:
- `moped_project` (insert is handled by `updated_at`'s default `NOW()` )
- `moped_proj_components`
- `moped_proj_entities`
- `moped_proj_funding`
- `moped_proj_milestones`
- `moped_proj_notes`
- `moped_proj_partners`
- `moped_proj_personnel`
- `moped_proj_phases`
- `moped_project_files`
- `moped_project_types`

And can exclude these tables:
- `moped_proj_features`	(covered by edits to `moped_proj_compoents`)
- `moped_proj_components_subcomponents`	(covered by edits to `moped_proj_components`)
- `moped_proj_features_components`	(deprecated)
- `moped_proj_financials`	(not implemented)
- `moped_proj_fiscal_years`	(not implemented)

**Comment by johnclary** [comment]
@amenity this needs to be groomed. i think we should update a project's modified date when essentially anything is edited on the project?

**Comment by amenity** [comment]
@sergiogcx is going to look at this if he has time.

**Comment by johnclary** [comment]
well, i've got this wrong, we're updating the project modified when we update the project activity log, [here](https://github.com/cityofaustin/atd-moped/blob/0a0b27aa97165510104141828be2d047ebcde4a2/moped-data-events/activity_log/MopedEvent.py#L50).

So this _should_ be covered by https://github.com/cityofaustin/atd-data-tech/issues/8055 - right @sergiogcx ?
