### ISSUE TITLE
Meeting: SLA Review for Map & Data Requests

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#84]
**Objective** 
Tracy needs a better understanding of map request workflow, and time frames, before drafting SLA. 

**Participants**
@TracyLinder 
@dianamartin 
@jaime-mckeown 
@mateoclarke 

**Agenda**

- Look at the proposed workflow in #83 
- Will this work for map & data requests? 
- Any special considerations for the map/data request workflow?

------
- [x] Schedule meeting _5/9/19_
- [x] Meet
- [x] Create resulting issues

**Comment by dianamartin** [comment]
Jaime needs to be involved in this, she is the GIS SPOC.

**Comment by TracyLinder** [comment]
@dianamartin :thumbsup:
@jaime-mckeown Welcome to the discussion!

**Comment by TracyLinder** [comment]
Meeting Notes
=
_Attendees: Diana, Jaime, Tracy, Mateo_

**Map Requests:**

- Are there varying levels of map requests that should be defined? 
- What is the definition of "map request" - 
- 	Ø The creation of web or paper map, with a limited data scope. 

**DATA REQUESTS**

- Definition / Scope of a "Data Request"?
- GIS data requests (updates, exports, new data, updating a web map)

**General Notes**

- Critical & Minimal Issue timing should work for all 3 service areas
- The application enhancement workflow doesn't work well for map requests… it's too much/over the top
- Step # 2 (User Story & Work Estimate): Update the language (requirements gathering, discovery….)
- Mateo's great feedback: Customer can't be the only one to decide when work goes active, DTS needs to be involved in that decision
- Most of Mateo's requests are coming from John & Diana
- The bulk of the data requests that Mateo gets are "critical" i.e. an executive needs it by EOD, extremely urgent
