### ISSUE TITLE
[Enhancement] Manually add missing task orders and funding codes to Moped

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8406]
Manually adding these to Socrata/Moped will enable Ivonne to track project funding before #8724 and #7931 are completed. 

## Task orders
- Public Works task orders, e.g.   (to be covered by https://github.com/cityofaustin/atd-data-tech/issues/8724)
   - 60G1408ESD
   - 60M1408QMD
   - (check for more)
- [x] 24ART01185

## Funding codes (pulled from #8559)
- [x] 8401 (fund)
- [x] 820B (fund)
- [x] D308 (unit) goes under 820B
- (check for others on the `work_orders` object specifically for inventory checkouts)

**Comment by amenity** [comment]
cc/ @johnclary

**Comment by amenity** [comment]
@johnclary how might we get a full list of all the codes that are in Data Tracker but missing from Moped?

**Comment by amenity** [comment]
It's become evident that keeping these codes updated is a small but must-have need for AMD. From Ivonne, via Teams today:
> UNIT, FUND and TK pull downs in the funding tab are not functional because the information in the pull down is incomplete.

Different options I see: 
- Escalate all of these requests so that a dev can implement them within the week they're requested (potentially even as a patch to Production) ... "requests" could come from 
    - Individual users when they request/add new codes to Data Tracker
    - Automated notification emails to Amenity/service desk whenever new codes are added to Data Tracker
    - Apps team whenever they add new codes themselves
- Create an interface for users to add TKs and funding codes in Moped (risks input errors, no single source of truth)
- Tackle [Configure ETL to publish financial codes to Socrata](https://github.com/cityofaustin/atd-data-tech/issues/7931)

**Comment by johnclary** [comment]
@amenity i just cross-checked Data Tracker vs Moped. These funds are missing from Moped prod:
```
8181 | 2010 MOBILITY BOND
820B | 2020 BOND
8401 | ATD TRANSPORTATION CIP
```

**Comment by amenity** [comment]
@johnclary added all of the above to Socrata, as the issue specifies, yesterday:
- [Task orders](https://data.austintexas.gov/Transportation-and-Mobility/-TEST-Mobility-Project-Task-Orders/ggav-ufvc)
- [Funding units](https://data.austintexas.gov/dataset/Transportation-Project-Financial-Codes/bgrt-2m2z)

Closing the issue, but need to note that neither the [funds](https://user-images.githubusercontent.com/1463708/159055346-8441a1c5-b686-47f2-9d90-6bfdec7e42e6.png) nor the [dept-units](https://user-images.githubusercontent.com/1463708/159058907-1beb3a19-60ac-4663-b5cf-42941dca9515.png) are showing in Production.
