### ISSUE TITLE
Pre-Launch QA/QC

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#841]
## Workflow Scenarios
Let's run through these scenarios and make sure they work as expected.

### Inventory Requester
- [x] submit inventory request
- New request - goes into NOT SUBMITTED status
- Add inventory items 
- Added comment
- Click Submit, click `Submit` again
- Request - goes into WAITING FOR APPROVAL status

>Needed clarification on whether or not we want cancellation to happen only on NOT SUBMITTED and WAITING FOR APPROVAL. 
- [ ] submit inventory request, cancel
- request - NOT SUBMITTED
- Click Submit, click `Submit` again
- Request - goes into WAITING FOR APPROVAL status
- tried to cancel, but banner says can't cancel if it's waiting for approval.
>we can change this depending on the stakeholders needs
- [ ] withdraw inventory request, edit, resubmit
>not sure if we have a use case here, need to confirm during sprint review
- [x] receive returned request, resubmit

### Inventory Request Approver
- [x] return request to requester
- added comment per instructions on the "Return to Requester"
- request - goes to "NOT SUBMITTED" status
>should there be an email notification?

- [x] modify and approve request
- Changed "Work Order" to `No`, filled out `Work Location`
- [x] review and approve request (memo task order)
used `24ART01041` (memo, skips FDU review)

### Inventory Request Approver - FDU Reviewer
- [ ] review and approve request (back chargeable task order) 

### Inventory Manager
- [x] fulfill request
- Click `Issue`
- Assign to `Inventory Viewer` - Diana
- request - go to NEEDS AIMS ENTRY
- [x] return request to requester
- request - was SUBMITTED
- made a comment to describe why sending it back
- Clicked `Request Change`
- request - goes to NOT SUBMITTED
- [x] enter request to AIMS
- clicked on request that was in - NEED AIMS ENTRY status
- clicked `Completed`
- prompted for OC# (comes from AIMS)
- request - goes into COMPLETED status
- [x] complete adjustment 
- [x] add order received
- [x] restock items in inventory from purchase request order

**Comment by johnclary** [comment]
@dianamartin feel free to add to these...

**Comment by dianamartin** [comment]
@johnclary We need to ask the users how they want to use the `Cancel` button in the process and where they want email notifications to happen
