### ISSUE TITLE
BUG - ATD GL Account number have the FDUs in old format (Ready for UAT PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8411]
### INC0155811 Created
Description - 5125 2400 9100 4057, 5125 2400 9100 4087, and 5125 2400 9100 4098 seem to still be in the old string format and not the new 0000-0000 format.

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please assign somebody for scoping? Not sure if it should be Vish or a dev. 

Is there a way to know which fee codes are associated with the FDU's in the description? I'd like to ask ATD finance to validate the FDUs before they get updated.

**Comment by TracyLinder** [comment]
Also @Nadin-Nader can you update the Service Now ticket please?

**Comment by Nadin-Nader** [comment]
Below are the account numbers that need the update to the format:

![GL Account needing new format.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/6dbd7f14-b583-491f-b88f-b250faae1680)

**Comment by Nadin-Nader** [comment]
@Nadin-Nader ask George if he can do this manually or push it through

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0201269 is submitted for DEV deployment of this ticket.

**Comment by SubhaShroff** [comment]
@Nadin-Nader SCTASK0201302 is submitted for TEST deployment.

**Comment by SubhaShroff** [comment]
### Status:
Waiting on CTM team to do TEST promotion.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  This is deployed in TEST. Please let me know if I can submit PROD deployment request.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  PROD Deployment request is submitted - **SCTASK0201896**.

**Comment by Nadin-Nader** [comment]
This is ready to UAT on PROD
