### ISSUE TITLE
Modify RPP email notification content

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8416]
Change the working on the last bullet on the Submitted Your Application customer email notification:

Can we remove the last part of the bottom bullet point that states in regard to the permits being ‘active’ and just have it read … 
**‘Once you make payment your permits will be issued by mail or in person pick-up.’**

**Comment by moorerst** [comment]
Steve confirmed he is ok with the text for the last bullet.

**Comment by ChrispinP** [comment]
Updated Email language
![image](https://user-images.githubusercontent.com/67915167/153238863-f6250965-bd1b-41b5-a395-b45a32bb45e4.png)

complete

**Comment by moorerst** [comment]
confirmed with stakeholder. Closing issue
