### ISSUE TITLE
Dev Huddle: ROW Visitor Queue & Attendance Tracking Requests

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#842]
**Participants:**
Tracy, John, Diana, Surbhi, Amenity

**Date/Time/Location**
11/4/19, 3:30pm, Allandale

**Comment by TracyLinder** [comment]
**Visitor Queue** 
* KNACK isn't good at calendar views, or appointments 
* Tons of out-of-box solutions available 
    * Calendly may be an option
    * Offer a DTS PM to help them with software discovery efforts
    * Offer help testing any free trials they look at

**Attendance Request:**
* KNACK solution will be ideal
* Small project size (2-4 weeks)

**Comment by dianamartin** [comment]
@TracyLinder can this be closed out?
