### ISSUE TITLE
Review Warehouse Inventory Design

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#843]
Review the Inventory Warehouse app for design consistency across the entire F&P system as well as, time allowing, the Signs and Markings app. This is an opportunity to shore up and document our app design patterns, pick favorites where multiple patterns exist, and make sure we're optimizing for usability before we put our end-user testers in front of the app.

**Comment by johnclary** [comment]
@amenity we have a burgeoning style guide, [here](https://github.com/cityofaustin/atd-data-tech/wiki/Knack%3A-Style-Guide).  @dianamartin FYI and let us know if there is other style documentation elsewhere

**Comment by dianamartin** [comment]
I've tried to keep everything in the Wiki Style Guide, I haven't updated it in a bit.

**Comment by amenity** [comment]
@johnclary - mind if I Icebox this?

**Comment by johnclary** [comment]
i'm just going to close it. we've done a pretty good job?
