### ISSUE TITLE
Automate SXSW file attachments upload to AGOL feature services

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8433]

**Comment by johnclary** [comment]
@jaime-mckeown plz dig up whatever docs you have for this

**Comment by jaime-mckeown** [comment]
- We didn't add attachments to the temporary permits layer this year as OSE said they did not need them.
- I will still try and find any documentation for how we did this in 2020.

**Comment by jaime-mckeown** [comment]
I think I found Sergio's script:
G:\ATD\ATD_GIS\Office_of_Special_Events\SXSW\SXSW_Data_App_Configurations\SCRIPTING

**Comment by johnclary** [comment]
@jaime-mckeown would you slack me a copy this script?
