### ISSUE TITLE
Document Process for using Crash Mapping Tool

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8436]
Write documentation for how to use dockerized Crash Mapping Tool and QGIS to make crash maps.

**Comment by frankhereford** [comment]
[A PR](https://github.com/cityofaustin/atd-vz-crash-mapping/pull/1) has been created on the [atd-vz-data-repo](https://github.com/cityofaustin/atd-vz-crash-mapping) with modifications to the README.md containing instructions for using the application.
