### ISSUE TITLE
[Bug] Map UI is rendering out of place

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8440]
- Map layer toggle is raised
- Map zoom is scooted to the right, almost off-screen

![Screen Shot 2022-02-09 at 8 07 56 PM](https://user-images.githubusercontent.com/1463708/153325398-bf384f7f-2884-4094-8773-49a60bf3f521.png)
![Screen Shot 2022-02-09 at 8 05 25 PM](https://user-images.githubusercontent.com/1463708/153325408-125b0af8-7f03-4f60-8544-e9044f808f07.png)

Seen in Windows/Chrome and Mac Chrome.

**Comment by johnclary** [comment]
hmmm—this looks familiar. when a map container `<div>` changes size (i.e., React renders it for the first time), mapbox needs to "repaint" the map to fit properly inside the container. it happens automatically sometimes, but repaint can be [invoked directly](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#triggerrepaint).

it's possible my refactor eliminated some side effect that was ensuring the repainting was being handled correctly. 

also, i jimmied some of the map tab's DOM while trying to fix a console error. that actually sounds more likely to be the problem.

**Comment by patrickm02L** [comment]
When adding a new component the map aerial layer and zoom moves out of place

![Screen Shot 2022-03-14 at 4.13.34 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/35d883cc-af3e-45a3-9eaf-0b32bf15d798)

**Comment by mateoclarke** [comment]
After syncing with @amenity, we're going to target work on this for later this sprint, but keeping VZx the priority. This is less of a regression and more of an incomplete bug fix. Thank you @patrickm02L for the thorough testing to catch it.

**Comment by amenity** [comment]
@mateoclarke & @mddilley will pair on this.
