### ISSUE TITLE
Feedback Banners Permits and Payment in Knack User Testing

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8446]
Suggested enhancements and modifications from the stakeholder user testing.
Testing was done for the customer role and the reviewer role for both LPB and OTS.
Attendees: Lauren, Cathy, Christina

Get Started - button not obvious
Likes About the Program opens in new tab
Help - go straight to the document
FAQ's - open links in new tab

- [x] ~~make links in new tab~~
- >I just made the "Get Started" page non-modal pop-up and then the link for the "Street Banners Program" worked by opening a new tab. When it starts as a modal, it opens a new tab but the modal pop up disappears. 

**LPB Banner Application Test**
Customer Info

- [ ] Breadcrumbs plan to be disabled, if so add a note to customer they can change it at the end

**Event Info**

- "Refresh page" message
- [ ] Get dev estimate for changing that

**Design Attachment**

**Banner Location**

- [x] Add Number of Banners field and Number of Locations to Add Banner Location page
- [x] Remove Location Comment, keep it for the reviewer
- [x] Remove Location Installation Date and Location Removal Date - for customers/reviewer
- [ ] Change "Submit" to Add Location

**Review Page**

- [x] Add Location modal, add reference map link
- [x] Add Reference map link
- [x] Remove "Add a new option" on Add Location form

**Submission**
 - [x] Change 10 business days to 5 business days
- [x] Add text informing the customer they may be contacted by email or phone if more information is needed 

**Email Submitted | Pending Review**
 - [ ] Change 10 business days to 5 business days
- [x] Remove any where that says "permit/permitting"
- [x] Remove phone number at footer
- [x] Add Note.. If changes are necessary, please email atxstreetbanners email

**Global Application**
 - [x] Remove phone number at footer - globally

**LPB Reviewer Steps**
**Lamppost Availability**

- [x] table can show by default
- [x]  sort by Oldest to Newest

**Comments**

- Add Banner Status to roll up to parent status

**Review Page**
 - [x] "Completed Customer Action"
>Added `In Progress - Completed Customer Action` on the "Banner Status" 
- [x] Completed Action - Y/N
>Added "Customer Action Complete" (Y/N)
- [x] Add Customer Action "Comments" table on the review page

**OTS Banner Application Test**

- [x] By passed to Add Locations
- [ ] Count locations, over 3 remove add form
- [x] Add note they are $600 each
- [x] Add reference link
- [x] check locations OTS Locations- 11, 24, 49, 65
- [x] filter "active" locations
- [x] Change to 5 business days on submission and email
- [x] Configure comment email

**Comment by dianamartin** [comment]
Review Demo w/ Stephanie

- LPB Comment & Status config
- LPB not showing up! 
- LPB email - add line about staff contacting customer
- LPB main table - add new status filter
- OTS email - Pending Action, include link to application details
- OTS - configure customer complete button

**Comment by dianamartin** [comment]
2/16 Testing 

# LPB


# OTS
- [ ] Need to configure "Approved - Pending Payment" email to trigger using commenting feature
-

**Comment by moorerst** [comment]
OTS application
Add Banner Location: 

- [ ] getting Direction Facing is Required when I select Add Location to add a 3rd location

![image](https://user-images.githubusercontent.com/56606465/154324921-65b8ab9e-a8d3-4e7d-942b-5ce4ea271521.png)

Application Details
- [ ] Contact Phone . before (xxx)

From Reviewer page

- [ ] sent Email notification to customer the Note About Your Application email does not have a Update Your Application link

- [ ] From this link the phone # is still displayed on the bottom of page https://atd.knack.com/street-banners#portal/

**Comment by dianamartin** [comment]
Stephanie and sync'd and she's going to run a few more test applications
I'll delete the existing test ones for now

**Comment by moorerst** [comment]
Reviewed updates with the stakeholders. They approved the changes. Added the outstanding items from this issue to the new enhancements issue #8601
