### ISSUE TITLE
Critical Bug: TDS Reviewers Unable to Generate Review Docs

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8448]
### System throwing error when TDS users attempt to generate the _ATD Engineering Review Comments_ document on the C8 & SP folder document tab. This bug is critical.

_Reported by Amber H & Bryan G._

- **C8 Example:** 2021 176807 000 00 C8 Subdivision
- **SP Example:** 2021 105858 CSH 00 SP Site Plan
- **Document Name:** ATD Engineering Review Comments

<img width="635" alt="Screen Shot 2022-02-10 at 3 09 31 PM" src="https://user-images.githubusercontent.com/49930868/153496882-2211a302-edfe-4ead-824f-09c2794e8c37.png">

**Comment by TracyLinder** [comment]
I just emailed DSD IT asking if they've promoted anything in the last 24 hours that could have caused this bug.

**Comment by TracyLinder** [comment]
**From Surbhi:**

DSD staff are reporting the same issue, I wrote to Deanna about it. Going to forward her email reply to me.

**Comment by TracyLinder** [comment]
**Email to Deanna w/ CTM:**

Hi Deanna,

We have users reporting the system won't allow them to generate folder docs on SP and C8. I checked around and it seems users with DSD and ACD are having the same issues. Is this something your team is aware of or working on? I'm not sure how to assist our customers on this.

**Comment by Nadin-Nader** [comment]
This is a known error that can be resolved by KB0014101 [here](https://atx.service-now.com/nav_to.do?uri=%2Fkb_view.do%3Fsysparm_article%3DKB0014101%26sysparm_stack%3D%26sysparm_view%3D)

Sent an email to Amber asking her to follow the steps in the KB article. Waiting on response

**Comment by Nadin-Nader** [comment]
Sent followup email to Amber asking if the KB article resolved her issue.

**Status:**
Waiting on Response

**Comment by Nadin-Nader** [comment]
Amber replied stating that the KB worked and resolved her issue.

> Email:
> From: Hutchens, Amber <Amber.Hutchens@austintexas.gov> 
> Sent: Monday, February 21, 2022 3:47 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>; Linder, Tracy <Tracy.Linder@austintexas.gov>
> Cc: Golden, Bryan <Bryan.Golden@austintexas.gov>
> Subject: RE: AMANDA message
> 
> It did for me, thanks!
> 
> From: Nader, Nadin <Nadin.Nader@austintexas.gov> 
> Sent: Monday, February 21, 2022 3:19 PM
> To: Hutchens, Amber <Amber.Hutchens@austintexas.gov>; Linder, Tracy <Tracy.Linder@austintexas.gov>
> Cc: Golden, Bryan <Bryan.Golden@austintexas.gov>
> Subject: RE: AMANDA message
> 
> Hi Amber,
> 
> Hope you are doing well. I was reaching out to you to see if that KB Article helped you resolve the issue. Please let me know once you get a moment.
> 
closing
