### ISSUE TITLE
Audit and repair / normalize the primary keys on four Moped database tables

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#8451]
In recent work on Moped's database for [PR #567](https://github.com/cityofaustin/atd-moped/pull/567), I discovered that we have at least four tables which have unexpected primary key configurations or lack any at all. 

While this won't mess us up often because they are on tables which almost never are `INSERT`ed into, I would be good administrative practice to us to get these in line with the rest of the database. The tables in question are:

### non-int pk
`moped_city_fiscal_years`

### missing sequence
`moped_phases`
`moped_status`

### missing PK - These are the "Freak Out" ones
`moped_fund_programs`
`moped_proj_fiscal_years`

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [x] Major — can only perform work using a workaround
- [ ] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Comment by amenity** [comment]
Thank you, @frankhereford! @mateoclarke @johnclary - how urgent do you see this being?

**Comment by amenity** [comment]
@frankhereford will you size this please
