### ISSUE TITLE
[Enhancement] Refine CSV export

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8454]
## Include additional columns
- [ ] **Project type**

## Tidying
- [ ] **eCAPRIS** should be blank if empty (currently `null`)
- [ ] **project_sponsor** should be blank if empty (currently `None`)
- [ ] **project_partner** should be blank if empty (currently `null`)
- [ ] **current_status** shows [lowercase "p" for "potential"](https://user-images.githubusercontent.com/1463708/155436993-b1318670-fb49-450c-8436-22e352d300d7.png); should be "Potential"
- [ ] Remove **current_phase**

**Comment by johnclary** [comment]
I'm calling this a dupe of https://github.com/cityofaustin/atd-data-tech/issues/10765.
