### ISSUE TITLE
[Bug] Can't filter for projects in "Construction" phase

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8457]
On the Project page, when filtering the CURRENT PHASE for "contains construction" it comes back with projects whose current phase is COMPLETE but that have a CONSTRUCTION phase.

**Comment by chiaberry** [comment]
I found what seems to me to be a bug, here's how to replicate. It's kinda convoluted, so maybe its not a big deal at all. 

1. have a project with the current phase being Potential. the badge should reflect the name Potential and the correct color. 
2. add another phase, make sure to mark it not current.  
3. Edit the name of the phase in number 2. Still dont toggle the current_phase switch. 
4. The badge changes to Green and Active, even though the current phase is still potential.

**Comment by amenity** [comment]
@chiaberry - this is kinda related, right? https://github.com/cityofaustin/atd-data-tech/issues/8596

**Comment by amenity** [comment]
Spoke with @chiaberry and we decided we'll fix these manually. Wrote Ivonne & Renée in Teams: 

> Hi! We may have messed something up in the migration: Are these projects supposed to be complete, or was the completion date that was in Data Tracker meant to indicate that only construction is complete, but the project is still open? 
> 	
> - [BURNET RD / PENNY LN PHB](https://mobility.austin.gov/moped/projects/103/)	
> - [SLAUGHTER LN / VINEMONT DR PHB](https://mobility.austin.gov/moped/projects/96/)	
> - [BURNET RD / TWIN OAKS DR PHB](https://mobility.austin.gov/moped/projects/100/)	
> - [MC CALLEN PASS / CENTER RIDGE DR Traffic Signal](https://mobility.austin.gov/moped/projects/43/)	
> - [CESAR CHAVEZ ST / TILLERY ST Traffic Signal](https://mobility.austin.gov/moped/projects/45/)

**Comment by amenity** [comment]
I resolved the reported bug by toggling the "Is current phase" switch for the "Complete" phase, so now they don't show on the list of projects [here](https://mobility.austin.gov/moped/projects?filter=eyI5ZDcxZDFiYy02MjE3LTQ0YjUtYTUxMi1kMTYwZWU4OGVmMGQiOnsiaWQiOiI5ZDcxZDFiYy02MjE3LTQ0YjUtYTUxMi1kMTYwZWU4OGVmMGQiLCJmaWVsZCI6InN0YXR1c19uYW1lIiwib3BlcmF0b3IiOiJzdHJpbmdfY29udGFpbnNfY2FzZV9pbnNlbnNpdGl2ZSIsImF2YWlsYWJsZU9wZXJhdG9ycyI6W3sib3BlcmF0b3IiOiJfaWxpa2UiLCJsYWJlbCI6ImNvbnRhaW5zIiwiZGVzY3JpcHRpb24iOiJTdHJpbmcgaXMgY29udGFpbmVkIGluIGZpZWxkIChjYXNlLWluc2Vuc2l0aXZlKSIsImVudmVsb3BlIjoiJXtWQUxVRX0lIiwidHlwZSI6InN0cmluZyIsImlkIjoic3RyaW5nX2NvbnRhaW5zX2Nhc2VfaW5zZW5zaXRpdmUifSx7Im9wZXJhdG9yIjoiX2lsaWtlIiwibGFiZWwiOiJiZWdpbnMgd2l0aCIsImRlc2NyaXB0aW9uIjoiRmllbGQgY29udGVudCBiZWdpbnMgd2l0aCBzdHJpbmcgKGNhc2UtaW5zZW5zaXRpdmUpIiwiZW52ZWxvcGUiOiJ7VkFMVUV9JSIsInR5cGUiOiJzdHJpbmciLCJpZCI6InN0cmluZ19iZWdpbnNfd2l0aF9jYXNlX2luc2Vuc2l0aXZlIn0seyJvcGVyYXRvciI6Il9pbGlrZSIsImxhYmVsIjoiZW5kcyB3aXRoIiwiZGVzY3JpcHRpb24iOiJGaWVsZCBjb250ZW50IGVuZHMgd2l0aCBzdHJpbmcgKGNhc2UtaW5zZW5zaXRpdmUpIiwiZW52ZWxvcGUiOiIle1ZBTFVFfSIsInR5cGUiOiJzdHJpbmciLCJpZCI6InN0cmluZ19lbmRzX3dpdGhfY2FzZV9pbnNlbnNpdGl2ZSJ9LHsib3BlcmF0b3IiOiJfaXNfbnVsbCIsImxhYmVsIjoiaXMgYmxhbmsiLCJkZXNjcmlwdGlvbiI6IlNlbGVjdGVkIGZpZWxkIGlzIG51bGwiLCJlbnZlbG9wZSI6InRydWUiLCJ0eXBlIjoic3RyaW5nIiwiaWQiOiJzdHJpbmdfaXNfbnVsbCJ9LHsib3BlcmF0b3IiOiJfaXNfbnVsbCIsImxhYmVsIjoiaXMgbm90IGJsYW5rIiwiZGVzY3JpcHRpb24iOiJTdHJpbmcgZmllbGQgaXMgbm90IG51bGwiLCJlbnZlbG9wZSI6ImZhbHNlIiwidHlwZSI6InN0cmluZyIsImlkIjoic3RyaW5nX2lzX25vdF9udWxsIn1dLCJncWxPcGVyYXRvciI6Il9pbGlrZSIsImVudmVsb3BlIjoiJXtWQUxVRX0lIiwicGxhY2Vob2xkZXIiOiJDdXJyZW50IHN0YXR1cyIsInZhbHVlIjoiY29uc3RydWN0aW9uIiwidHlwZSI6InN0cmluZyJ9fQ==).
