### ISSUE TITLE
Create 1password logins for dummy users in active Knack Apps

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#846]
Here's the pattern that we are using: 
![Screen Shot 2019-10-23 at 2 37 09 PM](https://user-images.githubusercontent.com/1463708/67428120-28883400-f5a3-11e9-8e22-e93c464a5585.png)

**Comment by dianamartin** [comment]
Created new vault `Knack Shared` in 1password

**Comment by amenity** [comment]
@SurbhiBakshi @dianamartin @johnclary I it cool if we save these as complete 1Password logins, e.g. not just the password but also the username and sign-in page URL, así:
![Screen Shot 2019-11-04 at 7 47 06 PM](https://user-images.githubusercontent.com/1463708/68172139-08118f80-ff3c-11e9-8e62-ea65e2de4fa6.png)

Thanks for creating the vault, Diana, and thanks in advance for taking the time to get these in there. :)

**Comment by amenity** [comment]
@dianamartin - when you get a chance can you add in the Data Tracker creds? It would really help me triage service requests to be able to see the interface staff use.

**Comment by dianamartin** [comment]
@amenity I've added credentials for the ATD Data Tracker app

**Comment by johnclary** [comment]
@dianamartin can this be closed?
