### ISSUE TITLE
Update fatality details People tab in Related Records section

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8461]
Reference #7178 for original Mock Ups. See images below to compare updates.

### Things to be updated

**Fatality Avatar and Name**

- Default to grey silhouette, discuss uploading actual image (will only be available to Admin level permission)
- Make name a manual input
- If not manual input there's a larger question about storing PPI that we'd have to consider storing in VZBD

**Additional Demographic Information**
- Add Gender column (already in database)
- Add Race/Ethnicity column (already in database)

#### Acceptance Criteria

- [x]  add age gender and race/ethnicity to the primary people table
- [x]  make these fields editable
- [ ]  add a text column to the primary person table to store a name
- [ ]  add that field to the UI (only if there is a fatality) and make it editable (who can edit? only admins?)
- [ ]  add a default grey silhouette image for persons (should this be gender neutral? or depend on gender listed? are there instances where no gender is listed?). again only if fatality.

**Comment by patrickm02L** [comment]
### Present State

Current example ([18735223](https://visionzero.austin.gov/editor/#/crashes/18735223)) of Related Records People section  

![Screen Shot 2022-10-21 at 11.53.54 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/7e8ce09b-ad74-4ee7-bfc9-05084bbef48a)

### New State

The image below is a fake record so the data from the current state won't necessarily match. Green highlighted sections will need to be added.

![persons section.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/ab62c82b-5af3-4687-a062-811ad22a4c3f)

**Comment by patrickm02L** [comment]
Types of documents to be housed in Documents folder.
![Screen Shot 2022-10-21 at 12.16.46 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/bf43afea-5140-478d-b8df-d2f41577cb77)

**Comment by patrickm02L** [comment]
Initially, the FTT was going to be its own page #8654, but we decided to roll the data into the existing crash pages. In 8654, we broke down what data was already in the vzdb, what was there but in a different state from the rendering, and what wasn't there. 

**Example: Profile pic and demographics**

![Screen Shot 2022-10-21 at 2.14.02 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/665277cc-581d-4e55-afc3-8599825daee2)

**Comment by patrickm02L** [comment]
@chiaberry tagging for updates.

**Comment by chiaberry** [comment]
document and image upload should be spun out into a different issue, afaik there isn't a way to upload and store documents in vision zero

my understanding of the acceptance criteria is
- [ ] add age gender and race/ethnicity to the primary people table
- [ ] make these fields editable
- [ ] add a text column to the primary person table to store a name
- [ ] add that field to the UI (only if there is a fatality) and make it editable (who can edit? only admins?)
- [ ] add a default grey silhouette image for persons (should this be gender neutral? or depend on gender listed? are there instances where no gender is listed?). again only if fatality. 

Is the silhouette asset somewhere, or do you have one in mind already?

**Comment by roseeichelmann** [comment]
@patrickm02L @chiaberry 
I also had some questions come up about the silhouette. It feels arbitrary giving long hair silhouettes for people with "female" listed as their gender and short hair for "male". I think a gender neutral silhouette (same silhouette for all genders) makes the most sense to not make any assumptions about physical attributes based on gender. This would also help clear up any issues if there are person records without a gender listed. I was thinking something like this: 
![image.png](https://images.zenhubusercontent.com/62a749345515571c03fe54eb/c8bc8121-5308-4d4c-a240-9bb0b3c67acf)
Also is the point of the silhouette to just hold space in the case that an actual photo of the person is uploaded, or to just emphasize the human life lost?

**Comment by patrickm02L** [comment]
Implement without photo until we get sign off from various levels of leadership, and we're in alignment about what information we're storing and the implications of what storing that information means as well as who can access it.

**Comment by roseeichelmann** [comment]
I have a few questions:

Should names only be displayed for primary people and if they were killed in the crash? Or are names displayed for everyone involved in a crash with a fatality?

Also, what does the UI look like if there hasn't been a name entered for that person yet? And what does making the name a manual input mean? That the VZ team can't update or add names through the UI, only directly through the DB? Or should it be editable through the UI as well?

@patrickm02L @chiaberry
