### ISSUE TITLE
🐧  Make ready for `atd-data03`

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#8467]
@johnclary told the group that there has been a new VM created and it's accessible at the `atd-data03` hostname. 

CTM Linux has provisioned a certain amount of block space and it's addressable as a `PV` under LVM2. 

This issue is intended to cover distributing that disk space as desired and to install any server software that we want to run on this machine, including scripts to restart it on reboot.

**Comment by frankhereford** [comment]
Be sure to add documentation to GitBook here: https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/dts-server-list

**Comment by frankhereford** [comment]
This needs to include adding a prefect agent and a PG database for holding flow state if needed.

**Comment by frankhereford** [comment]
For all intents and purposes, this issue is ready to close. 

The one thing that it explicitly calls out is to distribute block resources on the machine and expand file systems as appropriate, but until we have more of an idea of where those resources are most needed doing this is putting the cart ahead of the horse. 

We'll know when we need to use those pv extents and we can open an issue as needed at that point. I've taken a look at the machine, and nothing is bumping up on full. 💾

**Comment by mateoclarke** [comment]
@frankhereford I didn't see any documentation add [here](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-M4Ul-hSBiM-3KkOynqS/dts-server-list). Should we make updates there before closing out this task?

**Comment by mateoclarke** [comment]
cool, just noticed your comment above and didn't see anything on the page you linked. A new section is totally fine. Thanks for sharing the link in the issue.
