### ISSUE TITLE
Follow up User testing for Banners Permit and Purchasing in Knack

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8470]
Review feature updates and new enhancements we discussed during the first user testing.

Scheduled 3/1/22

**Comment by moorerst** [comment]
Notes from User Testing
Add Location Page

- [ ] Change Submit button to Add Location

- [ ] Modify customer email when application submitted from 10 days to 5 days

Availability Page

- [ ] Add all of statuses to the table

- [ ] Make the Customer Actions button more visible
- [ ] Add email to reviewer when the customer has completed their action

Technician Page

- [ ] Under Admin Info remove Design and Payment 
approved

- [ ] Remove Customer Information ???

- [ ] Remove old statuses that are not being used

**Comment by moorerst** [comment]
Next steps:

- update the app with the feedback changes and the other changes I thought I made

- Technical Review: with you, me and Karo

- Work on help guides for Smart Mobility and SMD

- Update Miro workflow

- New meeting with SMD: including Joseph A
and everyone from today
showing the work flow to team, show work order process for Joseph
talk about data clean up, migrating the new pages and updating the old data

- New meeting with Smart Mobility - showcase new applications and work order
Have help guides available to them

**Comment by moorerst** [comment]
Stakeholders are very pleased with the updates and the application and review process. They commented the process is very user friendly.
have created new issues for Next Steps
@dianamartin you can add any comments/notes and close out

**Comment by dianamartin** [comment]
We were able to review the changes we made from the last meeting with the stakeholders and documented a few that weren't fully complete. We talked about some new changes as well and then the future meetings and plans we had for the Street Banner application revamp project.
