### ISSUE TITLE
[Bug] Deleted projects showing on "Signal projects" dashboard

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8474]
https://mobility.austin.gov/moped/dashboard

![Screen Shot 2022-02-14 at 4 15 52 PM](https://user-images.githubusercontent.com/1463708/153955696-a7759a7f-d22c-4fd0-8fa3-86e95b7e9d41.png)

This was previously fixed [here](https://github.com/cityofaustin/atd-moped/pull/529). 

Cancelled projects are also showing in the table.

**Comment by chiaberry** [comment]
Here's where the query happens that is supposed to not include deleted projects: https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/queries/signals.js#L21

**Comment by amenity** [comment]
@chiaberry the plot thickens: 
I created [this project](https://mobility.austin.gov/moped/projects/159?tab=summary) yesterday using the "Use signal asset" switch. Then I removed the signal and added a "project extent" component. 

So it shouldn't be showing on the dashboard either.
