### ISSUE TITLE
Onboard Jace to Mobile Signals App

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#848]

**Comment by mateoclarke** [comment]
original meeting time was cancelled. We need to reschedule onboarding

**Comment by JaceDeloney** [comment]
Reprioritizing this to happen in the new year.

**Comment by amenity** [comment]
@JaceDeloney - please include @zappfyllc / JD here.

**Comment by JaceDeloney** [comment]
John was able to onboard me last week. I feel onboarded! Closing this out
