### ISSUE TITLE
Disable MDS ETL for SMRT Tracker

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8482]
We are discontinuing data collection through MDS for the [SMRT Tracker](https://atd.knack.com/smrt#home/), and will need to turn off the ETL that integrates into the Knack app. 

Things to do

- [x] Disable Knack ETL

Needs to be done before March 1, 2022.

**Comment by chiaberry** [comment]
I've turned off the DAG on airflow that handles the monthly summary.
