### ISSUE TITLE
Shut down MDS

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8483]
- [x] #8491
- [x] #8492
- [x] #8493

**Comment by frankhereford** [comment]
There are 3 servers that are still running in support of the MDS work. They are located in lightsail, and they should be inspected to make sure there is nothing on there we need to keep, backed up if needed, and shutdown. During discussion with the dev team, there was agreement that I would be OK to do that, so I wanted to document that here and will add a comment and re-close this issue when that is completed.

**Comment by frankhereford** [comment]
The 3 remaining MDS lightsail servers have been deleted. We agreed that no backups of the data on them was needed, and I took a quick peek to see if there was anything in the home directories, and there was nothing of value. 

As a side note, I also decommissioned an unused prefect-1 lightsail server that we agreed was no longer (or ever?) in use.
