### ISSUE TITLE
SXSW/ATD Command Center Staffing Meeting

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#8484]

**Comment by andrewshensky** [comment]
@johnclary Meeting Notes are below:

- There is effort to reduce number of people in command center due to covid
- Masking/rapid tests etc will be provided
- Half of applications compared to 2020 SXSW
- No streets closed until 230 to 3 each day due to APD staffing issues
- Still trying to determine staffing needs and plans
	Frances believes we can get away with less staffing this year
 	Thinking potential hybrid, full staffing only during peaks times/days with remote support
- Planning to have draft of proposed schedule to present to Jim this Friday
 	Another planning meeting likely late this week/early next week
- Frances said sounds reasonable for GIS support to be remote with 1 person per day covering shift from 10am to 8pm

**Comment by johnclary** [comment]
thanks Andrew! i'm cool w/ remote support so long as the end-users are trained/have documentation. cc @jaime-mckeown
