### ISSUE TITLE
Review Impact of Menchaca Street Name Change

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#849]
This name change potentially impacts Data Tracker, Signs and Markings, Banners — and the way this data is stored is different in each app. 

Are we going to retroactively update all of our records?
Ensure we have the new street name in all our apps. 
Verify that the street segment ID hasn't changed. 

@SurbhiBakshi will provide geo expertise and take the lead on looking at this. We'll have a meeting if it turns out the impact is significant.

**Comment by SurbhiBakshi** [comment]
| Name | Geo ID change | Date of Change |
|---------|------------------|------------------ |

**Comment by SurbhiBakshi** [comment]
Check if any of these are being pulled into Knack for location - 
1.	LOCATION.address_point 
2.	LOCATION.coa_intersection_points 
3.	LOCATION.coa_intersection_segments
4.	LOCATION.coa_str_name_intersection
5.	LOCATION.coa_str_range_intersection 
6.	LOCATION.coa_street_locator 
7.	LOCATION.address_locator 
8.	TRANSPORTATION.segment_locator
9.	Sidewalks
10.	TRANSPORTATION.street_segment

**Comment by SurbhiBakshi** [comment]
| Name of Application | Location Object | Location Object Connects To | Connects to Location Object |  Connection Field | 
|---------|------------------|------------------ |-------------- | -----------------|

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/1614ea30-4d21-4926-af8e-494ea00f117b)

**Comment by SurbhiBakshi** [comment]
| Name of Application | Location Object | Location Object Connects To | Connects to Location Object |  Connection Field | No. of Records Affected | 
|---------|------------------|------------------ |-------------- | -----------------| --------- |
|Signs and Markings|street_segments|------------------ |work_orders_markings | STREET_SEGMENT_IDS|90 |

**Comment by SurbhiBakshi** [comment]
Signs and Markings

| Name of Application | Location Object | Location Object Connects To | Connects to Location Object |  Connection Field | No. of Records Affected | 
|---------|------------------|------------------ |-------------- | -----------------| --------- |
|Street Banner Program|banner_locations| |banner_reservations_lpbs | banner_locations| |
|  | |  |  | |  |

**Comment by johnclary** [comment]
thank you @SurbhiBakshi for this excellent research. i believe the easiest approach would be to export the affected records to csv, modify them, and import them back into each application. we only need to update the primary objects, and the connected objects should be updated accordingly:

- banner_locations (banners)
- street_segments (signs & markings)
- street_names (signs & markings)
- street_segments (data tracker)
- tmc_issues (data tracker)

Can you work on this? You'll definitely want to do this in test first.

**Comment by SurbhiBakshi** [comment]
@johnclary, yes, will work on this issue. Planning to wait to hear from CathyW from CTM GIS who will be able to give me an estimate on when the ETJ street names will change, since that may affect some of the records.
