### ISSUE TITLE
Set up Moped read replica data access

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8497]

**Comment by frankhereford** [comment]
Requirements from Grooming:

* Break from the VZ pattern and assign access on a per-user basis.
* Attempt to enforce the use of SSL

**Comment by frankhereford** [comment]
Standing up the moped read replica is complete. In the course of getting this going, I have:

* Enabled automated backups of our production moped RDS instance, taken daily @ 5AM local time and retained for one week.
* Created a read replica RDS instance. I sized it down to save a little money; it's a db.t3.small. We have lots of headroom on our db.t2.medium in production.
* Created a new security group that allows access to the read replica from our CTM IP block. I have added my home, static IP as well.
* Created a new parameter group for this RDS instance that enforces the use of SSL.
* CNAME'd the RDS hostname as `moped-read-replica.austionmobility.io`
* Formed an account scheme as follows:
  * Create a new role for each human user, <lastName + firstInitial>, with read only access to `atd_moped` and `atd_moped_staging`. 
  * Create a new role for each application independent of the developer's access, with read only access to the same two databases.
  * Please note, that the read replica is inherently read-only, but, just in case, if a developer were to open a tunnel via SSH through the bastion host and connect with these users / roles, I wanted to trim the access down at the account level to read-only.  
* Granted myself an account and Charlie one as well. The passwords are private to the user and are not available in 1Password. Application accounts will have their password stored there.

**Comment by johnclary** [comment]
this is super cool, @frankhereford! i learned a lot just from your notes. thanks for taking the lead on DB + infrastructure!!

**Comment by frankhereford** [comment]
I put together a little documentation on the read replica [in gitbook here](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/moped-data/moped-read-replica). Most notably, it covers account maintenance on the instance, and also is configured to allow you access to the `public` schema, but also `hdb_catalog` and `hdb_views` which allow you to peek into the state and configuration of `graphql-engine`.
