### ISSUE TITLE
Create user test plan for VZA Citation app

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#851]
[Here](https://docs.google.com/document/d/1SZVOeN5SBXZ1ROBa5oWYumrm6qwHf_PsCjAUq_8BOno/edit#heading=h.wzokivvhuesg).

**Comment by SurbhiBakshi** [comment]
@amenity 
- created accounts for the officers
- created assignments that will be visible to them when they sign in
- sent them an email with credential details, as well as a follow up email asking them to let me know if they did not get my earlier email. POborski confirmed he received the email.
- tested with Diana to ensure that the link I sent out works.
- also got my phone to project in Allandale with an HDMI and an HDMI converter. Think that should work with a Smart Board. Will bring both items to the meeting tomorrow.

**Comment by amenity** [comment]
You rock, @SurbhiBakshi .
