### ISSUE TITLE
Build out data tables

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8513]
Taken from the [Intake meeting doc](https://docs.google.com/document/d/1rCAnQOy56Limz9o1W25yyHcihWdcY5hql8GVsQ-73ZU/edit#)
[Fillable PDF application](https://www.austintexas.gov/sites/default/files/files/Transportation/Dockless_Mobility_License_Application.pdf)

**How many database tables, overall complexity of Entity Relationship Diagram?**
Tables they have
- Permits

Tables they will need
- Application
- Attachment
- Initial bond and insurance digital versions
- Commenting
- Inspections

**How many records will your solution need to handle?**
- How many applications do you receive per week/month/year
  - 3-4 a year (pandemic)

**Does your solution need to collect or visualize geospatial data?**
Yes: DACPZ and Equity Areas

**Do your records need to tie to authoritative address or ATD asset information?**
No

**Do you require importing legacy data?**
Yes, allow to backfill old applications

**Does your business need require strict records retention?**
- Rejected application, must keep for 1 year after rejection date
- Accepted application, must keep for 2 years of acceptance date

**Does the data you're tracking have:**
- Personal Identifiable Information (PII)? n/a
- Health Information (HIPAA)? n/a
- Criminal Justice Information (CJIS)? n/a

**Comment by dianamartin** [comment]
Created objects
- `application`
- `application_attachments`
- `application_comments`
