### ISSUE TITLE
AMANDA Data Request: ROW Investigation Deficiencies 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8520]
### Customer has asked for an excel output of the ROW Deficiencies Summary Report. 

**Stakeholder:** Darren

**Notes:**
- Can we pull the sql from the crystal report, run it & export the raw data? 
![thumbnail_image001](https://user-images.githubusercontent.com/49930868/154771140-24239678-748c-4f52-a5ff-809e710e629b.jpg)

**Comment by TracyLinder** [comment]
**Email to Darren:**

Thank you for pinging me on this Darren. In short, yes we can give you data to use.  [Issue #8520](https://github.com/cityofaustin/atd-data-tech/issues/8520). I doubt I can get this assigned today or Monday. Will Tuesday be OK? 

We should be able to run the sql that generates the deficiency report and export the raw data for you. If there is only one query it will be easy, if there are multiple queries it could get complicated but we'll figure that out.

Questions: 
What date range are you looking for? 
What is the number on the name of the report in Paloma's screenshot?

**Comment by Nadin-Nader** [comment]
Spoke to Anu yesterday since after changing the file path to the correct name, subha screen, while running the report had no information.
Anu said she would look into this today

**Comment by TracyLinder** [comment]
I sent the data to Darren & asked if it will suffice.

**Comment by Nadin-Nader** [comment]
Asked Tracy if this can be closed.

**Comment by Nadin-Nader** [comment]
Stakeholders never responded. Closing
