### ISSUE TITLE
[Enhancement] New role for "Signal contractors"

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8521]
Brian C. is going to touch base with you, @dianamartin, about what he needs here. Maybe a new role, maybe renaming an existing role. 

Staci I. is the only `Contractor | Detection` user, can potentially re-work that role.

**Comment by johnclary** [comment]
I think we should probably hold off/roll this into Diana's work on #5125. But we do need more detail from Brian C. Per last convo with AMD, AMD will talk internally to refine the ask here.
