### ISSUE TITLE
Update seed data for Moped test/local

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8522]
We've discussed that it would be helpful to pre-populate Test and Staging databases with example Moped projects. Needs discussion, see also #8450. 
### Projects
- Good ol' Abilene Trail
   - ![Abilene Trail- Summary](https://user-images.githubusercontent.com/1463708/155203251-58f15464-d7bf-45ef-8d71-44df8f742660.png)
   - ![Abilene-Trail-Timeline](https://user-images.githubusercontent.com/1463708/155203246-899d145b-89e5-4584-a1eb-b43204078278.png)

**Comment by amenity** [comment]
cc/ @mateoclarke @chiaberry @frankhereford @johnclary

**Comment by chiaberry** [comment]
I noticed that we have 67 projects in our seed data, but 57 of them are `is_deleted` true right out the gate

**Comment by frankhereford** [comment]
@chiaberry Thanks for considering this with me - I'd like to revisit this in grooming if you're 👍 on it

**Comment by johnclary** [comment]
We did this some time ago and have been keeping up with changes.
