### ISSUE TITLE
[BUG] Remove application parameters from Moped source code

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#8526]
On [line 151](https://github.com/cityofaustin/atd-moped/blob/eecf4127e5f9548fcf6aed6b13a3baff2d21e972/moped-data-events/activity_log/MopedEvent.py#L151) in the MopedEvent python library, an S3 bucket name, and to a lesser extent, the form of a file name should be removed from the python code and pulled into environment variables as configuration parameters. 

Doing so will increase the maintainability and readability of this part of the Moped stack and increase it's portability for other organizations.

**Comment by amenity** [comment]
Thanks, @frankhereford! What size would this be?

**Comment by frankhereford** [comment]
@amenity said:
> Thanks, @frankhereford! What size would this be?

I think my tag of snackoo might have been a little optimistic on this, now that I'm thinking about sizing.

I think maybe a `2` or a `3` since it's involves setting environment variables that get consumed by a lambda function on AWS. It might be a little tricky to test, needing to be deployed in staging or similar.

**Comment by chiaberry** [comment]
handled when addressing https://github.com/cityofaustin/atd-data-tech/issues/10897
