### ISSUE TITLE
[Bug] Can't create new user accounts

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8532]
I tried creating an account for a non-CoA user on Friday and got an error, see [thread](https://austininnovation.slack.com/archives/CNUEPKLB1/p1645213909607239).
![Screen Shot 2022-02-18 at 1 55 30 PM](https://user-images.githubusercontent.com/1463708/155235369-66f4a16b-6e7f-4568-b597-269d4895d027.png)

Now, I'm trying to add an account for someone with a `@austintexas.gov` email and not able to do so:
![Screen Shot 2022-02-22 at 5 05 59 PM](https://user-images.githubusercontent.com/1463708/155235196-80357c8d-0867-4189-87a2-fcc0fb0a2f50.png)

- This is happening on both Staging and Production. 
- No problems activating existing user accounts that have been deactivated. 
- Not specific to the account/email, was able to reproduce with another user
- Tried both Viewer and Editor roles

**Comment by chiaberry** [comment]
This bug had a few parts. Some where addressed in the PR linked above, #603. Another part had to be addressed by updating the pointer in the prod database, in order to prevent a key value uniqueness violation. Thanks to @frankhereford for identifying and executing the command to do so.
