### ISSUE TITLE
ROW Portal Tech Debt: Clean Up Fields: Submitting Agency + Project Owner

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8535]
It's not clear what the intent of these two fields are & they have been causing a bit of confusion across teams.

**Comment by TracyLinder** [comment]
I'll need to either kick this convo off w/ an email or meeting.

**Comment by TracyLinder** [comment]
Discovery w/ stakeholder scheduled for 3/31/22 @ 10:30

**Comment by ChrispinP** [comment]
No action needed. Users have the ability to self-manage & update/inactivate Submitting Agencies and Project Owners through the App Admin menu within the app. Closing
