### ISSUE TITLE
Import Historical TIA Mitigation Data

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#8548]
Once Mitigation Data merge is complete, prepare data for import.

Import Prep:
- [ ] Will need to use formatted coordinates to match mitigation locations.

Import Followup:
- [ ] Updated mapped ArcGIS layers with mitigation IDs

**Comment by dianamartin** [comment]
- [x] Chrispin did formatted coordinates to match mitigation locations
- [ ] Currently associating Street Segments to TIA data

**Comment by dianamartin** [comment]
From 5/17 meeting
- [ ] Email stakeholders once TIA Mitigation records have been imported

**Comment by ChrispinP** [comment]
All 963 historical mitigation records imported successfully. Had to manually connect 61 of them. If multiple cases exist, connected on the more recent Case ID if possible. Imported short text fields as reference data. Also removed any unconnected mitigation records. Spreadsheets will be saved on the G Drive.
