### ISSUE TITLE
[TDS-TIA] TIA Application Video

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#8550]
This Video Guide for the TIA Application Process is pending the updates to the application process, customer home, and completion of the Submission Process Video.

**Comment by TracyLinder** [comment]
We need to discuss w/ stakeholders during a prioritization meeting.

**Comment by TracyLinder** [comment]
Ask stakeholders if this is still a need.

**Comment by ChrispinP** [comment]
There has been not additional ask for this now that there is 7 public facing applications instead of just the one now.

Closing as Not Needed/No Action
