### ISSUE TITLE
Modify - HR Telework Report

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8553]
Request by Nathan B.
When running the Telework Report I noticed some of the employees who have left are still showing as active on the report.

**Comment by dianamartin** [comment]
I told Nathan on 2/23
>To answer your questions about the TLC Report that you’re running. The Employees status is actually correct in the “Employees” table, but the TLC Report page isn’t showing the employee’s status. I could put the status on the report table or filter those employees out of the table to help. If you look up for example.  Warner Cook on the TLC report, she’s in the Employee table as “inactive”. 

he replied
>I like the idea of adding user status to the report.  Then I can filter out if needed.  

I added the field and emailed the stakeholder
>I’ve added the field “User Status” to the TLC Report. I unfortunately can’t color the background, but you should be able to export and filter out the “active v. inactive” employees. 

![image](https://user-images.githubusercontent.com/21112975/155417290-6112151d-42a1-43c3-812c-78d5cb0e827f.png)
