### ISSUE TITLE
Meeting: TIA Stakeholder Review of Review/QA Pipeline 3/1/22

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8554]
- #8163 
- #8120 
- #8236 
- #8237

**Comment by dianamartin** [comment]
# Diana's Notes
## Determination Form
- I think we should remove some of the icons on the Determination Form where is shows 3 details fields (Edit page?)
- email to Justin, recommended to 

## TIA Determinations table
- Reference TIA list
![image](https://user-images.githubusercontent.com/21112975/156253301-61e4b27a-e92c-4632-9a09-7c3adadd93f1.png)
- Record ID: `TDW` -`22`-`number sequence`

**Comment by TracyLinder** [comment]
### Tracy's Notes

- Meeting recording is [here](https://cityofaustin-my.sharepoint.com/:v:/g/personal/tracy_linder_austintexas_gov/EVxtLXbJkn1Do4KQINShjFcBGBRuVcbrxrDNSlL330bsDg?e=kgMmi2).

**Customer Landing Page #8237**
- [ ] (Tracy) Ask PIO for a banner
- [ ] Add clarification that the customer doesn't need to create an account or log in. 
- [ ] Add links to TDS & TIA Websites
- [ ] Add a Getting Started section just above the buttons. Add a brief description of each application type and instruct customer to click the button to get started. 
- [ ] Add verbiage: `This is an official site of the City of Austin. ` 
- [ ] Add a link to the TIA Portal to access the landing page. 



----
**Determination Form #8163**

🎉 Approved to go live! 🎉

- [ ] Update the submittal email. Remove the email to Justin, add him as CC to the customer notification email.
- [ ] Create new record ID format; same as TIA. This acronym will be TDW.
- [ ] Re-order & rename table columns on reviewer landing page. 
- [ ] (Tracy) Create a backlog issue for an automated system email to the customer with a link to download the signed determination form. 



----
**Compliance Letter #8120**
 
🎉 Approved to go live! 🎉

- Go-live scheduled for Thursday 3/3/22 around 4pm. It will take up to 2 hours. Stakeholders were notified. 



----
**Access code demo #8237**
- No time to discuss.
- [ ] Tracy will schedule time to discuss this & customer landing page.
