### ISSUE TITLE
[Enhancement] Indicate that an advanced search is active on the "Projects" page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8556]
Unless the advanced search drawer is open (or you look in the URL), you can't tell whether or not there are filters applied on the projects page. 

Ideas for how to show the active filters:
### Blue circle
<img width="404" alt="circle" src="https://user-images.githubusercontent.com/1463708/155430068-de9a1374-5dc5-4d2c-bdbf-0a36407ef21b.png">

### Blue icon
<img width="404" alt="icon" src="https://user-images.githubusercontent.com/1463708/155430043-f0e35c82-841d-4e51-bbf7-b27e26c518bf.png">

### Text content
<img width="912" alt="Screen Shot 2021-10-13 at 12 40 58 AM" src="https://user-images.githubusercontent.com/1463708/137074966-cfcaf2e7-bfa3-4228-94f5-4ae1df0b7459.png">

Bonus points:
- [ ] [Shrink hover effect of the advanced search to be inside the input box to 33px](https://user-images.githubusercontent.com/1463708/137071154-b596ddb5-a659-4003-b8a8-6e781e84ce4c.png)

**Comment by amenity** [comment]
@patrickm02L @johnclary - I vote for having center-aligned text in addition to an indication on the icon. What do y'all prefer?

**Comment by johnclary** [comment]
no pref on alignment! looks good!

**Comment by patrickm02L** [comment]
Left aligned (magnifying glass side) with "FILTERED BY:" text lining up on the edge of the search field.

**Comment by amenity** [comment]
@patrickm02L - that was my first impulse but I think it's gonna look weird when it goes multiline.

**Comment by chiaberry** [comment]
Do we want the blue circle or the blue icon to be the signifier?

**Comment by johnclary** [comment]
Feel free to ignore me, but another alternative could be to nix the "FILTERING BY" text and just render each field being filtered with a [chip](https://mui.com/components/chips/) and maybe a lil filter icon next to it. 

Knack example
<img width="515" alt="Screen Shot 2022-03-02 at 12 54 55 PM" src="https://user-images.githubusercontent.com/14793120/156429181-6ad5dbf7-15c1-40b5-ab90-93c8a61c6432.png">

**Comment by patrickm02L** [comment]
Could we include the advance search terms in the search bar? May be an easier solution that creating chips or some other way to indicate the filters. 
<img width="964" alt="Screen Shot 2022-03-02 at 2 51 45 PM" src="https://user-images.githubusercontent.com/5566727/156448272-ac215f16-2fae-4706-838b-a9288ba06965.png">

**Comment by johnclary** [comment]
@chiaberry per discussion go with the easiest option for the icon. @amenity we did not decide to adopt any of the changes Patrick and I posted earlier today.
