### ISSUE TITLE
Create accounts for Renée and Ivonne in TDS Portal & share historic TIA maps

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8566]
They'd like to see how Traffic Impact Analysis funding is being managed so that they can prep to utilize it for signals projects.

**Comment by ChrispinP** [comment]
@KaroEngstrom let me know if you need some guidance on this

**Comment by KaroEngstrom** [comment]
Met with Chrispin to work on this (i.e. to learn from him). 
- [x] Added both users Renee Orr and Ivonne Natal to the TDS portals as TDS Viewers
- [x] Created a TIA Mitigations page (table view) under TIA Reviews (visible to all logged in users), displaying mitigation funding data for approved TIA cases. 

![image](https://user-images.githubusercontent.com/100615928/159059957-3a76071f-72c5-43ac-993c-729559143c7c.png)

This is live in the TDS Portal but have not contacted the requestors yet. We wanted to ask @dianamartin and @TracyLinder for feedback first.

**Comment by TracyLinder** [comment]
**My Feedback:**

- Looks good
- Please add a link button to take users to the advanced search page for mitigations.

**Comment by KaroEngstrom** [comment]
4/14/22 - worked with @ChrispinP on this

- [x] Added link button from $ TIA Mitigations page to Mitigations Advanced Search
   
![image](https://user-images.githubusercontent.com/100615928/163439702-0560745e-d4d0-4f7a-9f9c-c8b3c2ad1612.png)

- [x] Added link button from Mitigation Advanced Search to $ TIA Mitigations page 
   
![image](https://user-images.githubusercontent.com/100615928/163439811-bd01f087-eb34-42ed-9758-545309503e47.png)

- re: permissions, we can extend those as needed as we see what the users will need

- [x] Emailed requesters: 
   "We’ve created a page for viewing TIA Mitigations funding in the [TDS Portal].
Direct link: [TIA Mitigations]
You can also access the page from the TIA Reviews dropdown after logging into the TDS Portal: [image]
Please let us know if you have any question or need access to further information."
