### ISSUE TITLE
Investigate redundant S3 deploys for production React/frontend apps

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#857]
Inventory of apps:
- micro.mobility.austin.gov
- vze
- vzv
- mobile-signals
- signs-markings-map
- data tracker 

(production & staging as necessary)

- Investigate ODD appetite to request CTM enterprise purchase of Netlify
- scope CI config requirements for build automation
- scope Cloudfront multiple origin

**Comment by sergiogcx** [comment]
Closing, it looks like we are happy with Netlify.
