### ISSUE TITLE
Urgent Amanda Finance Data Request 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8572]
### ATD Finance needs fee data today ASAP

We need data on all payments made 12/1/21 - 1/31/22 for the following GL codes:

- 5125 2400 9100 4057
- 5125 2400 9100 4087
- 5125 2400 9100 4098
- 5125-2400-9100-4057
- 5125-2400-9100-4059
- 5125-2400-9100-4062
- 5125-2400-9100-4082
- 5125-2400-9100-4087
- 5125-2400-9100-4138

**Select / Columns:**
- Fee description
- Sum of payment amount for each Fee description

**Example:**
<img width="827" alt="Screen Shot 2022-02-25 at 10 55 26 AM" src="https://user-images.githubusercontent.com/49930868/155756133-3ddb1a3c-f05e-4e2c-a2a2-66b10d0b5a87.png">

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader  I have shared the data in email.

**Comment by TracyLinder** [comment]
The data looks great. Finance will likely ask us for more data related to January's payments. I'll put this in Review Q/A for a while. Good work @Lpriya-LIT 👏🏽

**Comment by TracyLinder** [comment]
### New Data Requested
_FYI @Nadin-Nader @Lpriya-LIT_
Peggy asked for payment data for each payment included in Priya's original query. She'd like to see it broken out by payment. See screenshot below of data column names and let me know if there are any questions. 

<img width="845" alt="Screen Shot 2022-02-25 at 2 45 03 PM" src="https://user-images.githubusercontent.com/49930868/155800496-2d4edb42-2637-4a9a-a5b0-579fde9e5b35.png">

**Comment by TracyLinder** [comment]
@Lpriya-LIT the data you've provided has been great. We've been asked if you can please run both queries you've written for both Oct & Nov 2021. Please email them to me Monday ASAP. 

Thanks, Tracy

**Comment by Lpriya-LIT** [comment]
@TracyLinder I have shared data for Oct 2021 and Nov 2021 in email.
