### ISSUE TITLE
Define and Prioritize Migration Tasks

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#858]

**Comment by johnclary** [comment]
@mateoclarke would you schedule time for us to do this?

**Comment by mateoclarke** [comment]
@johnclary scheduled for Wed after MDS ETL checkin

**Comment by mateoclarke** [comment]
Notes from our discussion about devops prioritization here:
https://docs.google.com/document/d/1iVfofusVa5UrXMF096MH8NvTC_SkW7FKHd0Jk6xrgwI/edit#
