### ISSUE TITLE
Bug: System Error with EX - Extension Granted (Deploying to PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8590]
### System threw the error `YES` when user attempted to save 'Extension Granted' on EX folder. 

**Notes:**
- User is Russel B
- FolderRSN: 12755788

![MicrosoftTeams-image](https://user-images.githubusercontent.com/49930868/156058984-6781f1ee-05f9-4bf5-a74d-105adf617028.png)

**Comment by TracyLinder** [comment]
Pending more info from Russel

**Comment by TracyLinder** [comment]
@Nadin-Nader I'll slack you about this.

Richard reported this to me in a Teams DM. He said John was also having trouble doing EX extensions this morning. 
I'm sure this is to do with #7991  or #8233

**Comment by Nadin-Nader** [comment]
@TracyLinder sent Martin an email with the commits needed to be redeployed to PROD He said he would try to get to them tonight if not by tomorrow as he is the only one doing the commits.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Fixed and tested in Localhost for all subtypes
Austin Energy -11885693
Austin Transportation - 11885710
Austin Water Utility - 11885433
Corridor Program Office - 11885583
Franchised Utility - 11885751
Other City Departments - 11885449
Private Development - 11885761
Project Connect - 11885789
Public Works Department - 11885431
Water protection Department - 11885569

Submitted DEV DP to promote changes from Localhost to DEV.  Please approve and create task id for me. 
Here is the commit id. [20f3437f49d4](http://coaamandadevops01.austintexas.gov/R3:20f3437f49d46c57e522c30f32ded2089efc81b2)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder This has been sent to the DevOps CM Team to be deployed to *_DEV_** under **SCTASK0204239**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV all working as expected.. 
Austin Energy - 11903592
Austin Transportation - 11904265
Austin Water Utility (AWU) - 11904156
Corridor Program Office - 11904023
Franchised Utility - 11904022
Other City Departments - 11903822
Private Development (CIP) - 11904159
Project Connect - 11904066
Public works Department - 11903893
Watershed Protection Department - 11901149

TEST DP of #8590 submitted. Kindly approve and create task id for me. 
Here is the commit ID.[20f3437f49d4](http://coaamandadevops01.austintexas.gov/R3:20f3437f49d46c57e522c30f32ded2089efc81b2)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0204255**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder I sent a Teams chat to Paloma and Izzy letting them know that this fix is on TEST and ready for their UAT in order to move it to PROD.

Waiting on Response.

**Comment by Nadin-Nader** [comment]
Email sent to Paloma, Isabel, Tracy Russell:

> 
> Good Morning,
> 
> Hope you are both doing well I wanted to let you know that the EX Extension bug fix 8590 Bug: System Error with EX - Extension Granted has been deployed to TEST. 
> Please UAT the fix on TEST and let me know the outcome. Once approved, we can get it on PROD today.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> Product Delivery Manager
>

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST all working as expected..
Austin Energy - 12864917
Austin Transportation - 12865637
Austin Water Utility (AWU) - 12865661
Corridor Program Office - 12817939
Franchised Utility - 12775754
Other City Departments - 12153785
Private Development (CIP) - 12348166
Project Connect - 12813291
Public works Department - 12865648
Watershed Protection Department - 12770591

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan looks like this is not resolved. Russell and Jonathan tested this and they are still having problems:

> From: Bond, Russell <Russell.Bond@austintexas.gov> 
> Sent: Monday, March 7, 2022 1:47 PM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>; Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>; Pena, Isabell <Isabell.Pena@austintexas.gov>
> Subject: RE: EX Extension Bug Fix 8590 Bug: System Error with EX - Extension Granted on TEST
> 
> Good afternoon Nadin,
> 
> It still deletes whatever comment you type and replaces it with the “extension from_____to______.” It also still does not update the folder tab with the extended dates. I was practicing on RSN 12847109 in Amanda Test, FYI. Seems like all the same issues are still present. 
> 
> Best regards,
> 
>  	Russell “Russ” Bond
> Right of Way │ Permit Licensing Analyst
> Austin Transportation Department
> Direct (512) 978-1554 | Media (512) 974-8000
>              
>

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan here is Jonathan's UAT (he still needs to provide examples:

> 
> [4:41 PM] Wheeler, Jonathan
> Hey Nadin. Paloma had me helping with some of the AMANDA TEST for extensions. I have worked a few permits and still having the same bug issues as in PROD, just FYI
> 
>

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - PROD DP submitted. Kindly approve and create a task id for me. 

Commit ID: 20f3437f49d4

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder This was sent to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0205210**

**Comment by Nadin-Nader** [comment]
**Status:**

This fix will work for the Yes error and once it is on PROD we should be good.
UAT testing on TEST found that there may be a couple of little bugs with this. Card was created for it #8671

**Comment by TracyLinder** [comment]
### UAT (For the 'YES' error)

- I did many extensions on multiple types of EX and did not encounter this error. 🎉

**Comment by TracyLinder** [comment]
Folders need to be re-defaulted for the YES error to resolve. Can we do a batch re-default of EX folders? (Should we think about TURP too?)

**Comment by Nadin-Nader** [comment]
Per Isabel and all the UATers, the yes error has been resolved by re-defaulting the EX folder Closing this card and working on the rest of the EX errors on card #8671
