### ISSUE TITLE
[Bug] Mystery subphase shows in "Current status" 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8596]
I think this is a remnant of the migration, but weird situation [here](https://moped.austinmobility.io/moped/projects/1792?tab=timeline) in that the badge shows the name of a subphase that we don't see in the "Phases" table. 

![Screen Shot 2022-02-28 at 5 47 50 PM](https://user-images.githubusercontent.com/1463708/156078214-ca3dc32c-440a-48d4-ad10-94f28b492acc.png)

Ideally, if this was in "Ready for design" in Data Tracker it should look like this in Moped: 
![Screen Shot 2022-02-28 at 6 04 27 PM](https://user-images.githubusercontent.com/1463708/156079633-268ff8f4-6214-4d6c-b08f-67dda05583db.png)

**Comment by chiaberry** [comment]
I check the project and the badge says Planned, were you able to fix the badge by toggling the phase?

**Comment by amenity** [comment]
Discussed [in Slack](https://austininnovation.slack.com/archives/CNUEPKLB1/p1646092669300799) and determined this was just a small mis-mapping. No code to fix. 

I just manually adjusted the ~10 projects that were affected. 
<img width="1428" alt="Screen Shot 2022-03-01 at 12 05 26 PM" src="https://user-images.githubusercontent.com/1463708/156225878-5135ba77-1f31-4507-9d0d-7460be0974c1.png">
