### ISSUE TITLE
Update DTS Portal SR Intake Form

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#86]
**Updates:**

- When opening the DTS Service Portal, a customer should quickly and easily understand their 2 options for requesting support from the DTS team (contact a SPOC, or submit a new SR).
- The Portal should enable the customer to easily identify who their SPOC is.
- When a customer submits a new service request in the DTS Portal, a new issue needs to be opened in atd-data-tech.

**Comment by TracyLinder** [comment]
Note from @amenity : Need to see if this link is preserved when we transfer between repos

**Comment by amenity** [comment]
I'm imagining a few different intake forms, depending on the type of request: 
 - [Bug report](https://github.com/cityofaustin/atd-data-tech/issues/new?assignees=johnclary&labels=&template=bug_report.md&title=%5BBUG%5D)
 - Enhancement - improve existing functionality in existing application
 - Feature - new functionality in an existing application
 - New application —  maybe something like [this](https://github.com/cityofaustin/atd-data-tech/files/3193137/Project-Poster-Template.pdf)

**Comment by johnclary** [comment]
Form is here (in progress): https://atd.knack.com/dts#new-service-request/

**Comment by johnclary** [comment]
@TracyLinder @amenity would y'all add the form submit and confirmation email text for the various cases here?

**Comment by johnclary** [comment]
Notes from today about emails and assignments:

## Issue Assignments

- Bug reports and everythign else: assign to both amenity and tracy if it's severe
- AMANDA issues go to Tracy
- GIS issues go to Jaime
- Everything else goes to Amenity

## Emails

### IT Support

- Always Email Scott; close github issue

- Email to Requester:
    - Copy Tracy and Amenity on email if it's severe
        - Subject: Inlucde severity
    - Content:
    > "Thanks for your request. If this is severe call Scott. We'll be in touch soon."
        
### Bug Report
    - "If this severe/urgent call tracy for amanda or amenity"

### Feature Request
    - "If this urgent call amenity or tracy"

### Project
  - "We're going to be in touch soon." 

### GIS & Maps
    - "If this urgent call Jaime"

### Evertything Else
    - "If this severe/urgent fire call Amenity"

**Comment by amenity** [comment]
Thank you. We have received your request and will be in contact with you shortly. 

If this is an urgent situation that needs to be addressed immediately, please call a DTS team member directly.
IT Support: Scott Reedy, [phone #]
AMANDA: Tracy Linder, [phone #]
GIS and Maps: Jaime McKeown, [phone #]
Other: Amenity Applewhite, 512-974-3571

@TracyLinder - thoughts?

**Comment by johnclary** [comment]
@TracyLinder @amenity i've updated the intake form for all request types:
https://atd.knack.com/dts#new-service-request/

I updated the templates to match, with the major change being that IT support, GIS, and "Something Else" are identical:
https://docs.google.com/document/d/1hYIp2gMbeukzTsu7GF--mLwwKyQIE5FLtrKQZI0A5gY/edit#

**Comment by amenity** [comment]
At first glance, these look great. "If it is critical that you get it, when and why?" sounds weird to me. I'd vote for something more like, "If you need this by a certain time, when and why?"

**Comment by johnclary** [comment]
I like that!

**Comment by amenity** [comment]
![Screen Shot 2019-08-13 at 11 13 29 AM](https://user-images.githubusercontent.com/1463708/63052460-fffa0480-bea4-11e9-80f7-f5cd3e24e2fe.png)
We should also have consistency in this dropdown: 
- `and` instead of `&` for ATSD
- Remove `(Hr) and `(ROW)`
- `PIO` --> `Public Information Office`

**Comment by amenity** [comment]
- [ ] Capitalize `An` in ` Flexible — an extended timeline is OK`
- [ ] Replace dash with emdash in `IT Support - Help with licenses, accounts, hardware, etc.`

I also don't know if we need "Feel free to upload something here."

**Comment by johnclary** [comment]
Very close to do. Just need to move email notifications from the service request submit form to the form that is submitted by the service-bot post-github issue creation. This will ensure that the notification emails have a link to the github issue. Est 30 min of work.

**Comment by amenity** [comment]
🙌 💪 Get it, @johnclary!

**Comment by johnclary** [comment]
@amenity @TracyLinder the form work is complete. ready for testing. maybe we make all the issues in a batch, then i'll run the integration service to process everything. once i do that, the github issues will be created and confirmation emails will be sent—hopefully ;)
