### ISSUE TITLE
Enhancements User Testing 2 for Banner Permits and Purchasing in Knack 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8601]
Location Page
- [x] Change Submit button to Add Location
- [x] Modify text customer email when application submitted from 10 days to 5 days

Availability Page
- [x] Add all of statuses to the table
- [x]  Make the Customer Actions button more visible
![image](https://user-images.githubusercontent.com/21112975/158207718-9b3ed6b8-b8fe-4382-8cde-0440a1016a7e.png)

- [x]  Add email to reviewer when the customer has completed their action
![image](https://user-images.githubusercontent.com/21112975/157773578-e314ae51-e7df-4cc1-ab66-6d3f7bd0bae7.png)

Technician Page
- [x] Under Admin Info remove Design and Payment approved
 - [x] Remove Customer Information ??? not sure what was decided on this one
- [x] Remove old statuses that are not being used

**Outstanding items from previous issue**

Technician Page
- [x] Create a button for "Banner Stored"

LPB Banner Application Test
Customer Info
- [x]  Breadcrumbs plan to be disabled, if so add a note to customer they can change it at the end
### Application
![image](https://user-images.githubusercontent.com/21112975/158224579-460f2a69-2278-48f6-967a-a1de2fe26181.png)

### OTS
![image](https://user-images.githubusercontent.com/21112975/158224231-1a07956a-0721-411e-96dd-b34aa5c06d0b.png)
### LPB
![image](https://user-images.githubusercontent.com/21112975/158224296-40d4bce2-1e17-4db9-b6e3-d8aafd2adf2b.png)

Event Info
- [ ] "Refresh page" message
 Get dev estimate for changing that
>Created new issue #8691

**Comment by dianamartin** [comment]
**Applicant View**
Edit Form for Applicant Info on Review page
New Details section for PII to hide in other status than "Not Submitted"

**Comment by dianamartin** [comment]
@moorerst I've removed the extra fields and fixed this form. I had to do the same form for OTS.

**Comment by moorerst** [comment]
@dianamartin since you have opened a new issue for the Refresh Page message and all other items are complete can this issue be closed?

**Comment by dianamartin** [comment]
We can or we can keep it open until the stakeholders see it at the sprint review demo next week unless you're putting this into their agenda

**Comment by dianamartin** [comment]
Walked through technician process and had to add tables that were "Non-Editable" after WO status is "Work Complete". 

Noticed that if "Pick Up" is No, and WO status is "Work Complete" will not show up in Banner Pick up which is what we want, but haven't triggered it to go from "Work Complete" to "Closed".

**Comment by dianamartin** [comment]
Showed stakeholders during sprint review 3/22
