### ISSUE TITLE
[Meeting} 311/Knack Paging Testing

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8602]
### Participants
Robert F, Bill S, Chandra P, John C, Stephanie M, Diana M.

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
SR Type: Traffic Signal - Maintenance
Page happens after hours, during normal business hours it doesn't get paged out. 

Scenario set up: 
- SR pushed to Knack
- Page activity pushed to Knack

### Questions for 311/CTM:
Have they had any set-ups with activities being sent through ESB?
Currently: Only push things back from stakeholder database

**Comment by dianamartin** [comment]
Seems like there were some issues on the ESB side that Robert had to resolve after our testing session. 

He emailed a few days later, 3/4:
>I was able to fix a couple of things and the messages are now flowing. However, I am getting a 400 error from Knack.

**Comment by dianamartin** [comment]
Closing this issue for the meeting

**Comment by amenity** [comment]
@dianamartin @johnclary - please make sure there is an (index?) issue for the outstanding work here. 🙏 ⏳ Also we need to let Chandra P. know that John is leaving and put him in touch w/ Mateo/Diana.
