### ISSUE TITLE
Documentation: Banner Permit and Purchasing in Knack

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8603]
- Technical Review: with you, me and Karo

- Work on help guides for Smart Mobility and SMD

- Update Miro workflow
@dianamartin can you add a link to the Miro workflow

**Comment by dianamartin** [comment]
Set up new GitBook space for Street Banners
- For ATD Staff
Update Miro Board 
- For ATD Staff
Video Creation? - SnagIt
- Take screen captures for video project (Public)

**Comment by moorerst** [comment]
technical review meeting scheduled 3/10

**Comment by dianamartin** [comment]
# Documentation Overview
## Street Banner Staff


## Customer
### How to Submit an Application
#### LPB Banner Locations v. OTS Banner locations
- call out the minor difference
### Receiving Email for Customer Action

**Comment by dianamartin** [comment]
I think this is ready for the first [review ](https://atd-dts.gitbook.io/street-banner-portal-or-help-guides/)@moorerst @KaroEngstrom

**Comment by moorerst** [comment]
@dianamartin the document is very comprehensive. I haven't completed reviewing it, so far so good it looks great. I'll complete it tomorrow

**Comment by KaroEngstrom** [comment]
This is great. I took these notes for later. 

### CUSTOMER SIDE
Navigating the Street Banner Portal Application
- **Get Started**: add “and allows you to apply/including the online application” or similar to guide the applicant
- **About the Program** – website URL missing “t” for austin 

How to Submit an Application 
- language suggestion: “When you are ready to apply, click “Get Started” 
- **Event information** section – language suggestion: “Banner Text – if your banner includes text” 
- **Adding Banner Locations**: language suggestion: “The next page will display an embedded map to allow you to reference banner locations.”  
- UXwise, I had a hard time figuring out the number of banners - just a note from a newbie.

Reviewing Application 
- language suggestion: “All of your application information will populate for your review, and you will have the opportunity to edit the information before submitting your application.”  
- Did not get email but it’s probably not activated 

Receiving email for Customer Action
- **Adding Banner Locations** - language suggestion: selectable over “select-able” unless reason to use “select-able”
- **Action Completed:** “Staff will be notified **to** review your application.” 

### INTERNAL DOCUMENTATION - ATD BANNER STAFF
 - **Receiving an Application** - With menu buttons, can we highlight the actions the reviewer can take? Just a sentence like “The menu buttons allow you [or the reviewer] to complete the following actions, as needed:” then list the four buttons and their actions
- **Adding Comment/Emailing Customer**- My instinct is to note that when adding a comment, there’s the choice to email customer or not. Basically adding a really short overview sentence.

**Comment by moorerst** [comment]
@dianamartin no other changes from me.
