### ISSUE TITLE
Meeting: Review Banner Permit and Purchasing in Knack with Smart Mobility

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8605]
Meeting with Smart Mobility
We have been developing the application with input from Signs and Marking team who has been responsible for this process. 
This process is eventually transitioning to Smart Mobility. Now is the time to review the new process with the Smart Mobility team in preparation for Go Live

- showcase new applications and work order

- Have help guides available to them

- [ ] schedule meeting week of March 27th

**Comment by moorerst** [comment]
Meeting scheduled 3/31

**Comment by moorerst** [comment]
Discussed with the team during the recent sprint review and decided to cancel this training until the SMB team has soon time to test drive the system with new applications. We'll make any tweaks needed before we do training with the Smart Mobility team.
On hold for now estimated to reschedule at end of April

**Comment by moorerst** [comment]
scheduled 4/19

**Comment by moorerst** [comment]
@KaroEngstrom we will be using this Help Guide for training with the Smart Mobility. There have been some changes to the application since the Help Guide was completed. 
Are you able to make some updates:
https://atd-dts.gitbook.io/street-banner-portal-or-help-guides/customer/navigating-the-street-banner-portal-application

The order of the buttons have changed:
![image](https://user-images.githubusercontent.com/56606465/163865826-ce73604e-9aae-4c5f-afbb-5cef3a5c58e4.png)

**Comment by KaroEngstrom** [comment]
@moorerst @dianamartin 
I updated the image to reflect the current button order on https://atd.knack.com/street-banners#portal/ 
 
![image](https://user-images.githubusercontent.com/100615928/163867032-6265af01-c910-4ed0-b02c-df6b92e10408.png)

I'll try to tinker with the size so it matches the other images in the series (it's larger right now).

**Comment by moorerst** [comment]
@KaroEngstrom can you also change the button definitions at the top to match the button order. Thanks

**Comment by KaroEngstrom** [comment]
@moorerst 
Yes, only noticed that after merging the image change. 
Updated the text above the image to match the current button order as well.

**Comment by moorerst** [comment]
@KaroEngstrom a few additional updates. Thanks

- How To Submit and Application/Event Information Section:

Remove - Alternative Date Range - alternate date range for banner installation and update the image

- Adding Design Attachment:

Update the instructions and move under the Add Design Attachment title like the image below:
![image](https://user-images.githubusercontent.com/56606465/163870545-bac1c197-bc01-4abe-9919-b4a74ba682f3.png)

**Comment by KaroEngstrom** [comment]
@moorerst @dianamartin I hope these will work for you. 

## Event Information Section
- [x] Removed the Banner Text line from instruction to reflect the form
- [x] Removed the Alternative Date Range line from instruction to reflect the form
- [x] Added the word Banner to Installation Date and Removal Date to reflect the form
- [x] Updated the image

![image](https://user-images.githubusercontent.com/100615928/163876842-191402ca-aabf-4a46-a6b9-66c744b66935.png)

 ## Adding Design Attachment Section
 - [x] Updated the instructions to reflect the form
 - [x] Updated the image
 
 
![image](https://user-images.githubusercontent.com/100615928/163877395-022c329a-1eb0-4506-ba70-04c2e65141d9.png)

- [x] Added small edit to the table instruction 

![image](https://user-images.githubusercontent.com/100615928/163877741-5af181f7-4e45-4856-b231-a94961a91334.png)

**Comment by moorerst** [comment]
Next Steps:

- meet with Smart Mobility team provide them a update on what is happening with the new application

- Determine if they have access to the mailbox

- Provide them with the Help Guide

- Review the workflow

- Provide access to a test system so they can become familiar with managing the program

**Comment by moorerst** [comment]
Diana showed the Smart Mobility team the process of entering an application and reviewing the application on the backend.
 
Clean up items:

- [ ] switch the OTS and LPB images on the Home Page
- [ ] Event Information page remove the question Have you submitted an application before?
- [ ] Follow up with CTM on access to the group mailbox
- [ ] Application Details page highlight the Customer Action Complete instructions
- [ ] remove locations 11,24,40,49,65 from the OTS map

Next Steps

- email testing information to Smart Mobility staff (Hannah, Luke, Nick)
link to test environment
link to Help Guide
usability test script

**Comment by dianamartin** [comment]
# Diana's Notes
# Knack Action Items
- [ ] Remove: Have you submitted a street banner app before?

Customer must click "Action Completed" 
- [ ] add Yellow Banner 

- [ ] Update ALL emails font
- `Ensure banners are properly labled...`

- [ ] Update TEST ENVIRONMENT for test links
Check OTS: 
Remove Locations in Knack or filter out
- [ ] Update Maps to remove: 11, 24, 40, 49, 65

# Action Items outside of Knack
- [ ] CTM Follow-up

**Comment by KaroEngstrom** [comment]
T 4/19/22

After internal and training meetings, edited the Gitbook Help Guide for Customers, _How to Submit an Application_ page, to reflect updates to the application (updated listed in the comment above): 
- [x] Removed instruction line for "Have you submitter a street banner application before?" from the _Event Information_ section

![image](https://user-images.githubusercontent.com/100615928/164086379-6f7bed29-5ef0-4a4f-ae02-3614da4a0182.png)

- [x] Removed the bullet for "Requesting # of Banners" from _Adding Banner Locations_ section
![image](https://user-images.githubusercontent.com/100615928/164086103-70e651d3-f5dd-4b39-8e89-8f0c0bf0c754.png)

**Comment by dianamartin** [comment]
Added Yellow banner for "In Progress - Customer Action Needed" 
![image](https://user-images.githubusercontent.com/21112975/164260949-086a16c6-b58b-4f42-8d01-69b296a0fc86.png)

**Comment by dianamartin** [comment]
Will have to update the AGOL maps and make sure the 7 OTS locations are removed
![image](https://user-images.githubusercontent.com/21112975/164336515-ed5a535c-3521-4b02-a6f2-c6bd2af0bab0.png)

**Comment by dianamartin** [comment]
Updated the web map applications:
- [x] OTS Customer Facing
- [x] OTS Reference Map embedded in Street Banner Knack App

**Comment by dianamartin** [comment]
@moorerst completed all the feedback changes, closing.
