### ISSUE TITLE
Soft Launch Banner Permit and Purchasing in Knack

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8609]
Place holder no firm details at this time
Possible soft launch with Signs and Markings in early April
They would do a test run by processing a few applications before handing over to Smart Mobility

**Comment by moorerst** [comment]
- [ ] April 1st, change URL links in Street Banner application

- [ ] April 4th, start having customers use intake form
SMB staff will manually direct customers to the new form

- Month of April have SMB staff use new forms/tables/pages and get feedback

- 2nd week of April, have training session with Smart Mobility team on new process

**Comment by moorerst** [comment]
Target date 5/2

**Comment by dianamartin** [comment]
@moorerst We changed the Street Banner big buttons to redirect to the new pages. Cathy has already been instructing customers to use the applications, she's had 2 customer enter things in and there were no issues that's she's heard about.

**Comment by dianamartin** [comment]
4/18
Lauren emailed saying
- the "Permit #" field needed to be added back to the application, they still use that to find the AMANDA records
- [x] Added back "Permit #" to Application details and Edit Forms
- Cathy had a user enter a new app but they had an old one, she needed the attachments moved from the old app to the new app and add the permit numbers to the new app
- [x] Moved 2 attachments attached to `792` and moved to `810`
- Cathy added the permit numbers to the reservation

**Comment by moorerst** [comment]
Closing this issue. Issue #8939 has the most recent enhancements from the sprint review.
