### ISSUE TITLE
Delete "csr_flex_notes" from Signs & Markings - April 2022

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#8619]
Received automated reminder to delete flex notes in Signs and Markings Operations PROD and reference the Flex Note Archiving wiki

Ran filter on: https://builder.knack.com/atd/signs-markings/records/objects/object_172

Filter:
`ISSUE_STATUS_CODE` contains `closed`
`CREATED_DATE` is `before` 02/01/22

Total Records: 15323
To Delete: 4693
New Total: 10630

**Comment by KaroEngstrom** [comment]
Removed flex notes, complete.
