### ISSUE TITLE
Investigate inclusion of Microsoft Projects data in dashboard

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8634]

**Comment by Charlie-Henry** [comment]
The Microsoft Project file (.mpp) I received from Fernando cannot be read by PowerBI but they do support loading in data from Microsoft Project Online. I currently don't have a license but @dianamartin says I can get one. I'm not exactly sure wha the difference is between the desktop and online versions of Project are but I hope that Fernando could move over to the online one easily?

[Docs about loading Project Online files into Power BI.](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-project-online-connect-to-data)
[Gantt charts in Power BI tutorial](https://www.youtube.com/watch?v=cdUg8LfarCg)

**Comment by Charlie-Henry** [comment]
Also wanted to point out the MPXJ library that should allow us to read in the data and export over to CSV which could potentially allow us to cut MS Project out of the process entirely.

[MPXJ](https://pypi.org/project/mpxj/)

**Comment by amenity** [comment]
Whaaa... MPXJ?? 

@dianamartin - what is the process for getting a license? We would want one for Fernando, too.

**Comment by Charlie-Henry** [comment]
Sorry should have CC'd you but Scott got me a MS Project license. I assume Fernando already has one since he's been working in MS Project.

**Comment by Charlie-Henry** [comment]
Steps to get Project for Web to Power BI:

1. Download template [here](https://github.com/OfficeDev/Project-Power-BI-Templates/blob/master/Project%20for%20the%20Web/Microsoft%20Project%20for%20the%20Web%20Power%20BI%20Template.pbit)
2. Go Office.com -> Power Apps
3. Click Apps on sidebar
4. Find and click Project on the list
5. Get the url from this page of the form: https://<envrioment>.<region>.dynamics.com
6. Paste that into Power BI
