### ISSUE TITLE
[Bug] Work orders do not show at the "View in Data Tracker" link

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8637]
The following work orders are associated with [BURNET RD / TWIN OAKS DR PHB](https://mobility.austin.gov/moped/projects/100): 

- [WRK21-129075](https://atd.knack.com/amd#signals/signal-details/603e754e79e9a7001b0535c2/work-order-details/61570cc84ef135001f67f331)
- [WRK21-131780](https://atd.knack.com/amd#signals/signal-details/603e754e79e9a7001b0535c2/work-order-details/617bfa2d22d0a4001ec6b5ef/)

...But the [page you get to](https://atd.knack.com/amd#work-orders/?view_713_filters=%7B%22match%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22field_4133%22%2C%22operator%22%3A%22is%22%2C%22value%22%3A%22100%22%7D%5D%7D) when you click the the "View in Data Tracker" link from the "Summary" tab is empty.
![Screen Shot 2022-03-03 at 1 39 52 PM](https://user-images.githubusercontent.com/1463708/156640301-a857c4c1-03e7-4f21-9402-e12e5acdc97f.png)

**Comment by johnclary** [comment]
these work orders belong to the “Construction Services” workgroup, however the work orders table in Data Tracker only displays work orders in the “Technicians” workgroup.

i tweaked the the settings on that technician work order table to use a preset-but-editable filter for  “workgroup = technician” work orders. this causes the workgroup filter to be applied by default, but it can be removed/modified through UI.

here's the [default view](https://atd.knack.com/amd#work-orders) of the work order table page:
<img width="946" alt="Screen Shot 2022-03-03 at 11 08 55 PM" src="https://user-images.githubusercontent.com/14793120/156703661-db26a310-f326-413b-9568-fe15dd1a0c74.png">

and here's what we see when using the direct link from Moped
<img width="1056" alt="Screen Shot 2022-03-03 at 11 08 37 PM" src="https://user-images.githubusercontent.com/14793120/156703651-5f62b19a-3ddb-4645-9c60-d7645a75a880.png">

**Comment by amenity** [comment]
Nice, thank you, @johnclary !
