### ISSUE TITLE
Set up meetings with SMS Providers | SMRT SR/WO feedback on DOLA

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8643]
- Patrick and I need to find time slots to set up meetings
- Need to get questions together for providers so that each session will be efficient

Set up meetings with SMS Providers:

- [x] Bird
- [x] Lime
- [ ] Wheels
- [ ] Scoobi
- [ ] Link
- [ ] Free2Move

Reference latest Mary V. email for current vendors.

**Comment by patrickm02L** [comment]
In lieu of Calendly, we could set up a calendar that has designated times for vendors to chose from.

**Comment by patrickm02L** [comment]
In grooming4/27/22, Stephanie is following up about project standardization.

**Comment by patrickm02L** [comment]
Andrea sent out a message to Providers on 10/19/22. 

> Good morning everyone,
> 
> The  Shared Mobility Services team has been working diligently with our Data team to create an Online License Application system. We would like to know if any of you would be interested in testing the new system ahead of the rollout for the upcoming renewal term in December. If you are interested please respond to this email and I can provide more direction. This would definitely help work out any issues since your teams are the ones that would be using this system.
> 
> Appreciate your help with this.

**Comment by patrickm02L** [comment]
15 min meeting with Claire at Lime on 10/31/22 to help with set up, self-directed testing, and to schedule a test window so we can be available to unlock parts of the app.

**Comment by patrickm02L** [comment]
On 10/31/22, @dianamartin and I met with representatives with Bird (Dominic) and Lime (Claire). 

We showed them how to [login](https://atd.knack.com/smrt#home/), and provide the [user testing feedback](https://atd.knack.com/smrt#usability-test/). 

They'll have the week to do the testing, and will let us know when they're ready to submit so we can unlock the bond and insurance portion of the application.

**Comment by patrickm02L** [comment]
Completed this.
