### ISSUE TITLE
Project: Fatality Tracking Tool

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8651]
The Fatality Tracking Tool is a web page in the Vision Zero Editor that displays a table of individuals who have died, similar to the format used on the crashes and locations page.

## Background

The VZ currently team tracks fatalities is through an internal spreadsheet which serves as the single source of truth. Creating a new section in the VZE and drawing from the data of the VZDB the Fatality Tracking Tool replaces the spreadsheet and becomes the single source of truth. 

## Desired Outcomes

The Fatality Tracking Tool will consist of an Index page and Statistics page which will provide an efficient and comprehensive resource for monitoring and analyzing traffic-related fatalities.

## Timebox

August 2022-June 2023

## Concepts and references

Reference original FTT Issue #7178

![fatality tab](https://user-images.githubusercontent.com/5566727/204917877-1c6ff440-524c-42e8-8418-57fd2a71b8f5.jpeg)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

Build a page that captures the fatalities in a table arrangement much like the crashes and locations page. Every entry on this table is a person vs. the crash tab which are crashes.

**Comment by chiaberry** [comment]
@roseeichelmann I'll help you track down the link to the shared drive and troubleshoot how to connect to it, if you need help

**Comment by roseeichelmann** [comment]
Some questions I have:

I'm assuming this should include both primary persons and non-primary persons?

The status column is the status of the recommendation for that crash?

What is the CaseID? I dont think we have this data anywhere unless it means crashID?

Are we keeping or nixing the Name column (we had a [discussion](https://github.com/cityofaustin/atd-data-tech/issues/8461#issuecomment-1322747494) about not storing names bc its PII)

**Comment by chiaberry** [comment]
discussion in grooming 12/7 cc: @patrickm02L 
- we believe it should both primary and non-primary persons, but would like confirmation from VZ team
- if the status column is the recommendation status, there will be repetition since the recommendation is related to one crash and not to persons
-  should we also include a column with the corresponding crash id? (and have it link to crashes page?)
- @patrickm02L Could we check in with Mary and Joel about the usage of Names in the Fatalities Index page and ask about their need and use for them before Rose starts editing the database to add PII to the tables? por favor

**Comment by patrickm02L** [comment]
In 12/12/22 Meeting with Joel and Mary:
- Only `Injury Severity` indicated as Killed will show up in Index Page.
- Primary/non-primary is not a way that VZ team thinks about Killed victims. Use `Type` to add level of distinction.
- The # column should reflect the APD fatal crash number (could also be DPS number). Manual entry would happen in the crashes page either in the Details or Fatalities components.
- Joel will check with Lewis about names.
- Mary asked for an additional column for `Area Engineer`
- Joel said he would schedule a meeting with Lewis and Xavier to revisit what columns to include in the Index page.
- Mary also brought up filtering. We don't currently have this in the mock up, but would make sense as a next step to build out similar to the filtering in the crashes and locations indexes.

**Comment by patrickm02L** [comment]
VZ Team is going to send us a condensed version of the current spreadsheet. 
- With FRB as the main priority
- What the next priorities are to include in the index page.

**Comment by patrickm02L** [comment]
1/6/22. Joel sent [this spreadsheet](https://cityofaustin-my.sharepoint.com/:x:/g/personal/joel_meyer_austintexas_gov/ESyinv4ESM5Inl-UKNPafssBuevqjqwE84CkHa9D1UGOyg) as a model of what the data schema should include. 

![Screen Shot 2023-01-06 at 3.20.32 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/3e6e0564-e8f8-4454-87f3-c3d512fa3b76)

![Screen Shot 2023-01-06 at 3.20.43 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/356ddde0-b1c2-4a7a-8679-449ff3051993)

**Comment by patrickm02L** [comment]
Since its launch in March, the Fatality Tracking Tool (FTT) MVP has been a valuable addition to the Vision Zero Editor. The FTT provides essential information about fatalities for individual crashes and presents a running count of fatalities by year, current FRB status, and recommendations for the Fatality Review Board.

In response to user feedback, the FTT team is now working on building out an advanced search feature. This will allow users to search for specific information about fatalities, such as location, type of vehicle, or time of day, to better understand the circumstances surrounding each fatality.

Additionally, the team is updating the crashes export to include data from the FTT. This will make it easier for users to export and analyze data about crashes and fatalities, allowing for more informed decision-making around road safety.

**Comment by patrickm02L** [comment]
This past month we made significant progress. We have successfully delivered an Advanced Search tool, crash exports, and incorporated the Victims Names into the Index page. 

Currently, we are focusing on adding Engineering Areas to the export feature and enhancing filtering capabilities for advanced search. 

With these developments, the bulk of the Fatality Tracking Tool is nearing completion.

**Comment by patrickm02L** [comment]
We have officially closed out the Fatality Tracking Tool (FTT) feature. There are still a few follow-up issues remaining, but the majority of the work is complete, and we consider this feature to be delivered.
