### ISSUE TITLE
Demo Warehouse Inventory App to Finance Division

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#867]
Scheduled for 11/12 at 9:30am w/ Peggy and Van.

@dianamartin I don't think there's much to prep. Just be prepared to demo the end-to-end process for all user roles.

**Comment by dianamartin** [comment]
Task Orders for testing

`Memo`: 24ART61028
`Back Chargeable`: 24ART01041

**Comment by johnclary** [comment]
I did a brief demo and peggy scheduled a follow-up meeting to discuss her concerns wrt financial tracking. i don't have notes; sorry.
