### ISSUE TITLE
Bug: System Errors with EX - Extension Granted (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#8671]
## Bug: System Error with EX - Extension Granted (Multiple Bugs)

- Permit status is not Updating automatically and the staff has to manually change the Folder status

- Franchise Utility WorkTypes needs to be "Yes" on AUP in order for it to update, Currently it is set to "NO"

- Dates are not updated on the printed Permits dates are pulling from the wrong field on the info tab Estimated Completion Date. Should be pulling from the Folder Expiry date. 
  - RSN 12776808
![Permit Expiry date.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/a6645120-abd7-4130-9638-e0730591bd77)

Dates **not** Updated:
![Estimated completion date.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/91663e67-d68a-4278-a1d5-f67f789c142e)
![Expiry Date.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/0adb0b56-1df7-448f-a230-b7ae6a85ea97)

**Comment by Nadin-Nader** [comment]
The dates issue may be resolved with #8233
Spoke to Paloma and she is willing to wait til tomorrow to test it again since 8233 may fix the date issue

Reassessing after 8233 is deployed to PROD

**Comment by Nadin-Nader** [comment]
❌❌❌ System did not insert a folder expiration date when folder was issued. AUP = YES, the system issued the folder after payment was made. ❌❌❌

❌ Extension Granted: System did not insert the process comment into the folder description.

Everything else passed UAT. AUP was Yes, System updated the folder expiration when the payment was made.
❌ Manual Extension:

System did not update folder infos w/ new extension dates (extension start & extension end dates)
System did not update the folder expiration date.
System did not clear the process info values (as is done w/ attempt Extension Granted)

**Comment by Nadin-Nader** [comment]
EX - Franchise
_2022-032970 EX _

❌❌❌ System did not insert a folder expiration date when folder was issued. AUP = YES, the system issued the folder after payment was made. ❌❌❌

❌ Extension Granted:

System did not update the folder status from Expired to active.
System did not update folder expiration date.

**Comment by Nadin-Nader** [comment]
❌❌ The EX Folder constantly updated AUP from Yes to No in many of my tests.

**Comment by Nadin-Nader** [comment]
Izzy's Extension Granted UAT
12710246

She re-defaulted the folder, and that resolved the 'YES' error.
✅ This was COS, the system correctly inserted, billed & paid the fee
✅ System updated the folder infos Extension start & end dates
❌ System did not update folder expiration date

**Comment by Nadin-Nader** [comment]
From #8319
## **Test Notes - EX COS & Secondary**
System:
❌ updates folder status to Active - (this should not have happened because AUP is No)
❌ Updates folder expiry to 3/15 (process info end date?) (same as above, AUP is No)
✅ Updated folder infos (estimated start date, estimated end date) w/ the process info dates.
❌ Did not insert extension fees (or any fee) -- system should have inserted and billed 2 fees: Excavation Permit Fee - Secondary, and ATD Tech Surcharge ROW
❌ System did not make COS payment (no fees to pay)
--Ending this test here--

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder -  DEV DP submitted. Kindly approve and create task id for me. 

This commit will resolve the below Issues in EX Folder for PVT, Project Connect & Franchise subtypes

**EX-PVT & EX-Franchise**

❌❌❌ System did not insert a folder expiration date when folder was issued. AUP = YES, the system issued the folder after payment was made. ❌❌❌

Commit ID:
[230d3ad79bf0](http://coaamandadevops01.austintexas.gov/R3:230d3ad79bf031a5203b4f9cb9ce036ba6f1f1ff)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Please find attached #8671 DEV Commit for your reference. Kindly approve and create task id for me. 

This will update 50510 Crystal report completion Date which will be updated to Folder Expiry date. 

![image](https://user-images.githubusercontent.com/44907715/158257961-b1458710-77a9-46f4-84b1-dc2f3da7d005.png)

**Comment by Nadin-Nader** [comment]
The First commit has been sent to the DevOps CM Team to Be deployed to **_DEV_** under **SCTASK0206075**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I was able to deploy the report to DEV. Please UAT unless the Dev commit needs to go first

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan the report and commit have both been deployed to DEV Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested the above two commits in DEV and working as Expected.

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0206780**

**Comment by Nadin-Nader** [comment]
I have deployed the report to \\COACD.ORG\DFS\AMANDA\BROWSERFORMS\DEV\. This is where TEST pulls the report from.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to TEST. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Completed TEST UAT, submitted PROD DP. Please approve and create task id for me.
Commit ID: 230d3ad79bf0
& 
50510 Crystal Report Move from TEST to PROD.

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team t be deployed to **_PROD_** under **SCTASK0207028** for commit: **230d3ad79bf0**
The report must be deployed by CTM as i do not have rights to deploy reports to **PROD** This is under TASK **SCTASK0207029**

**Comment by Nadin-Nader** [comment]
This has all been resolved except for the fact that all the dates need to be shown in the report (56210). A card was created for it # 8794.

closing this one
