### ISSUE TITLE
Mock up must-have Moped dashboard design

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8672]
Patrick's latest: 
![Dashboard – 2 – 3](https://user-images.githubusercontent.com/5566727/154765969-63e09835-6f31-4cd4-85e4-3d4f83f50eeb.png)

@amenity just update mock to reflect [user feedback](https://xd.adobe.com/view/a2124c8e-9278-4652-ba17-4ca669e44a38-f741/screen/5000e479-ddb6-4ac3-8892-28d68f9066f0) and lowest level of effort

**Comment by amenity** [comment]
Added my very scrappy works in progress and design inspo to the XD board. Passing back to @patrickm02L for the XD mockup. 

@amenity - post meeting pics and notes from yesterday now

**Comment by amenity** [comment]
semi-functional XD prototype [here](https://xd.adobe.com/view/2c9892e4-a5c6-4870-be4c-689289547678-79cb/grid).
![Dashboard - Modal - Milestones](https://user-images.githubusercontent.com/1463708/159866110-81c125dc-ebae-4c7d-8b11-5d4ae7042872.png)
![Dashboard - Modal - Phases](https://user-images.githubusercontent.com/1463708/159866117-96121fa2-9377-4ecf-aa72-95587dc5d03e.png)
![Dashboard](https://user-images.githubusercontent.com/1463708/159866118-09a03d14-97a3-4537-b5f5-9e7fbe9e4f5b.png)
![Dashboard - Modal - Status updates](https://user-images.githubusercontent.com/1463708/159866121-a752bb0d-d1be-4fde-aca9-613bde7e3429.png)

**Comment by patrickm02L** [comment]
Looks good. The modal edges could be rounded a bit more, and I think you a close button should be added. Though you can probably close by clicking off the modal, I can imagine an "X" button will help navigate that action with intentionality. 

<img width="519" alt="Screen Shot 2022-03-24 at 9 21 24 AM" src="https://user-images.githubusercontent.com/5566727/159937657-255b4fa7-f700-4a94-adc7-39826b0bbf0a.png">

<img width="524" alt="Screen Shot 2022-03-24 at 9 21 34 AM" src="https://user-images.githubusercontent.com/5566727/159937651-b115a375-7234-4e5d-8937-8f9fc79a2144.png">
