### ISSUE TITLE
Bug: Sys does not calculate ROW Usage Fee for metered parking spaces (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8674]
### The system should calculate the correct usage fee for TURP metered parking spaces, and insert the fee along with the other ROW Usage fees. 

**Acceptance Criteria** 

- The acceptance Criteria provided below applies to RW-TURP folders only. 
- System should automatically insert TURP Metered Parking Spaces Fee (50321) when attempt 'Approved' is made in TURP Review Process or 'Extension Granted' attempt is made in Permit Extension Process. 
- Fee logic for TURP Metered Parking Spaces Fee - Value in Info Rate if metered (Hourly Meter Rate) X Value in 'Number of Days' Info field (Info Code 75390) X 16 X Number of 'Parking Spaces : Meter Number' Rows in Property & Street Information Freeform (same as #7912) 

**Notes:**
- We found this bug when we mapped the usage fees on issue #7829 
- Staff is currently manually entering this fee.
- Fee should insert when other ROW usage fees are inserted (when TURP Review is approved, and when extension granted is saved)
- This fee has never worked as per Paloma

**Comment by TracyLinder** [comment]
Hi @vschandramouli - I just assigned this to you for scoping.

**Comment by vschandramouli** [comment]
Scoping meeting scheduled for 3/21/2022

**Comment by vschandramouli** [comment]
Updated AC. Ready for Backlog.

**Comment by TracyLinder** [comment]
I'm going to ask @vschandramouli to provide feedback for @SubhaShroff questions above. 

1. Should we add the info (75948) Hourly Meter Rate to RW-TURP?
2. Does the parking rate increase with the extension tiers as other TURP ROW fees do?

**Comment by Nadin-Nader** [comment]
Asked Paloma and Tracy Subha's question. Waiting on a response

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder After call with Paloma today, here are the responses from her:

1. Should we add the info (75948) Hourly Meter Rate to RW-TURP? Yes
2. Does the parking rate increase with the extension tiers as other TURP ROW fees do? No.

I started working on this with these inputs.

**Comment by Nadin-Nader** [comment]
Demo Review in Progress

**Comment by SubhaShroff** [comment]
@Nadin-Nader  DEV deployment request is submitted - SCTASK0216640.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0216838 - is submitted for DEV deployment of VALIDLOOKUP = 50200 record.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to DEV. Please UAT

**Comment by SubhaShroff** [comment]
@Nadin-Nader I tested this ticket on DEV for Metered parking spaces fee, the calculation is now as expected for Extension also. Please let me know if we can get it deployed in TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0217789 is submitted for the TEST promotion.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  This is promoted to TEST and I tested it, ready for UAT.

**Comment by Nadin-Nader** [comment]
Waiting on Paloma to UAT this on TEST

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  This ticket sent for PROD Deployment. - SCTASK0219717.

**Comment by Nadin-Nader** [comment]
@SubhaShroff this has been deployed to PROD. I will et the stakeholders know

**Comment by Nadin-Nader** [comment]
This is working as expected, closing
