### ISSUE TITLE
Updates to Speed Limit Change Web App to Track Changes Made Prior to Ordinance

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#8681]
- [x] Add city code speed limit dataset to map

- [x] Add/Repurpose field to track segments changed prior to ordinace

- [x] Update reporting filters in Dashboard 

- [x] Review changes and make refinements with TED

**Comment by johnclary** [comment]
Closing and will open additional issues as needed. Andrew is meeting w/ Max later today.
