### ISSUE TITLE
Create New Batch Job to Re-Default EX and TURP Folders (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#8684]
A new Batch Job needs to be created in order to Re-Default EX and TURP Folders. This will ensure that any changes, additions, deletions, updates will get populated to the EX and TURP folders

**Comment by Nadin-Nader** [comment]
@SubhaShroff Spoke to Paloma and she informed me that she would like this batch to run daily late in the evening so no other batch would interrupt it.

Please Let me know what other information you need.

**Comment by SubhaShroff** [comment]
@Nadin-Nader Redefault is done through the button provided in AMANDA UI. There is no procedure available. Not sure what exactly this button does, other than adding the configured infos, processes. I checked with Guna from DSD, if anyone has done it before in COA. Looks like, it was never attempted before. So, before proceeding on, to start with I have following questions.

1. How(in what way) the redefault is helping the user?
2. What information is expected to get redefaulted? any particular tab, like INFO tab, PROCESS tab?
3. Should it remove the obsolete infos or just adding the new info fields in case of INFO tab/PROCESS info tab? Please list of any other tabs are expected to be redefaulted.

**Comment by Nadin-Nader** [comment]
Asked Paloma, Izzy and Tracy the following in the TEAM chat:

> [4:45 PM] Nader, Nadin8684 ReDefault Batch Job
>     Amayo-Ryan, Paloma; Pena, Isabell; Linder, Tracy Subha has some questions on this request. I have posted them below. Once
> Questions:
> 
> 	What information is expected to get redefaulted? any particular tab, like INFO tab, PROCESS tab?
> 	Should it remove the obsolete infos or just adding the new info fields in case of INFO tab/PROCESS info tab? Please list of any other tabs are expected to be redefaulted.
> 	Please let me know any other expectations/requirements that's not mentioned in my above questions?
> 	
> 	She also noted:
> 	Redefault is done through the button provided in AMANDA UI. There is no procedure available. Not sure what exactly this button does, other than adding the configured infos, processes. I checked with Guna from DSD, if anyone has done it before in COA. Looks like, it was never attempted before.
> 	
> 	Once we get the answers she will continue to research on how to get this delivered.

**Comment by SubhaShroff** [comment]
### Status:
Currently I am working on it.

**Comment by Nadin-Nader** [comment]
@SubhaShroff Just in case you still need it, Here is Paloma's response:

[Tuesday 5:28 PM] Amayo-Ryan, Paloma
    

	
I believe we were hoping it would be the whole folder.  (This particular ticket was triggered by the extension issues which were occurring - in part - due to older folders not having the new info field on the Info tab.)  Since any/all additions to a folder have the potential to impact our folder issuance and extension, it would be ideal for it to cover the whole folder.  If we must concentrate on one tab only then I would suggest the Info Tab.
	
Both would be great but if we must choose one or the other then the new info fields should be captured.
	
Run daily in the late night or earl morning hours.

**Comment by SubhaShroff** [comment]
@Nadin-Nader @TracyLinder Based on Paloma's response and my analysis, here are the points I want to bring to your notice:
1. Please observe the screenshot on Amanda with 'Redefault' button click. It will redefault - Property, Info, Document, Fixture, Process, File & Milestone and these are selectable. I am not sure if you want all these tabs to be defaulted.
2. Since we are trying to do it programmatically and for the first time, if issuance is working well with Info tab redefault, I think its good to stick to only info tab redefault and I am working on this part, currently. Further, we can extend it to Process tab, if necessary. 
3. I suggest to keep old info fields in old folders, unless you insist to remove. 

![image](https://user-images.githubusercontent.com/51680715/160011273-42d25cf2-1cff-4d96-9286-57adca6a4d43.png)

**Comment by Nadin-Nader** [comment]
@SubhaShroff below is Paloma's response. The last question she referred to Tracy. I asked her and i am waiting on a response:

> [11:59 AM] Amayo-Ryan, PalomaCheck Acceptance Criteria for Ticket 8684
> Nader, Nadin:
> Based on Paloma's response and my analysis, here are the points I want to bring to your notice:
>  	
> 1. Please observe the screenshot on Amanda with 'Redefault' button click. It will redefault - Property, Info, Document, Fixture, Process, File & Milestone and these are selectable. I am not sure if you want all these tabs to be defaulted. **_No, not all of these tabs will need to be redefaulted since not all of them are even on our permit folders.  See #2 below._**
> 	
> 2. Since we are trying to do it programmatically and for the first time, if issuance is working well with Info tab redefault, I think its good to stick to only info tab redefault and I am working on this part, currently. Further, we can extend it to Process tab, if necessary.  **_That's fine._**
> 	
> 3. I suggest to keep old info fields in old folders, unless you insist to remove.  _**Good with that.**_
> 	
> 4. Should it check for the EX, TURP folders status before the batch job does redefault? What status, should we avoid to update? **_... I really don't know.  Maybe Tracy will have some thoughts on this._**
>

**Comment by Nadin-Nader** [comment]
@SubhaShroff here is Tracy's response:

> Tracy Linder  12:06
> I don't think the folder status matters. Re-defaulting has never updated the folder status and has never caused any existing information to change. If Subha needs to narrow down the RW/EX folders so as not to update all that ever existed, I'd recommend including every folder with an in date of 1/1/2019 or newer.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  SCTASK0208499 is submitted the DEV deployment request.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  DEV Manual deployment request for the Batch Job is submitted - SCTASK0208880.

**Comment by SubhaShroff** [comment]
@Nadin-Nader This is deployed in DEV and tested. Looks good now, working as expected.

(NOTE to self: The batch was throwing error: Error while executing before procedure: DefaultReport_RedefaultEX_TURP. Grant to Batch procedure did the trick. I have to mind it when it is further deployed in TEST/PROD).

**Comment by Nadin-Nader** [comment]
@SubhaShroff this is ready for UAT on TEST. Please let me know if it will be ready for stakeholder UAT at the 2pm meeting

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I submitted another request SCTASK0209869 for DEV/TEST deployment of a commit that takes DefaultReport_RedefaultEX_TURP batch procedure to DEV/TEST.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The above request is completed. So, I submitted another Manual TEST deployment request to deploy Batch Job. - SCTASK0209908.

**Comment by TracyLinder** [comment]
Hi @SubhaShroff - I think we only need to run the batch job once in PROD.

**Comment by SubhaShroff** [comment]
Right @TracyLinder. I had asked Paloma on Friday call, if this needs on daily basis. She said yes. And looks like there would be more new infos added in future. That was her answer.
Please confirm.  Accordingly, I will get this job inactive on DEV/TEST also.  Or set it monthly once?
@Nadin-Nader

**Comment by TracyLinder** [comment]
### Approved for PROD
_by me_

**Comment by SubhaShroff** [comment]
Tested on TEST for following permits:
12486717 - EX(AWU)  with Indate - Jun 09, 2020
12582391 - RW (Private Long-term) - In Date Nov 06, 2020

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  SCTASK0210766 is submitted for PROD deployment.

**Comment by SubhaShroff** [comment]
SCTASK0210766 is deployed in PROD. Yet Batch job (SCTASK0210771 ) has to be deployed.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  The batch job is deployed in PROD to run ONCE.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder Left a message in TEAMS on the "On PROD" channel stating this was on PROD and that i would close.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  Since Gita suggested to change the package procedure name as per the naming convention. So, I have done the changes and submitted DEV/TEST request - SCTASK0212183.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I tested this ticket on DEV as I had privileges to RUN a batch job in DEV. But couldn't test it in TEST due to no access to do so. In DEV, the batch job completed, successfully. 
Please let me know if I can submit PROD request for this.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0212819 - is submitted for PROD deployment request - Package procedure name change as per naming conventions.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  The procedure name change part is promoted to PROD.
