### ISSUE TITLE
[Open Data] Open Data Portal Refresh -  Pilot Kickoff

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8686]
Charles P./ Brad M. 
CTM 

Asking for pilot group of departments to participate in effort to do a data 

3/4

>Hey Everyone,
Thanks again for attending our meeting yesterday about Open Data Refresh.  Today,  I've included the "How To Guide" that was covered in the meeting.  It's labeled DRAFT, but still covers all the steps demonstrated in Wednesday's meeting.  The link to the Open Data Inventory Tool is included inside the .pdf document.  I've also included the LINK here if you'd like a shortcut.

>We always look forward to feedback from our Open Data community, so if you have any suggestions or concerns about either the document or the tool, please let us know. 
Thanks everyone.
[DRAFT - How to Update Your Department.pdf](https://github.com/cityofaustin/atd-data-tech/files/8226558/DRAFT.-.How.to.Update.Your.Department.pdf)

**Comment by dianamartin** [comment]
3/14 - Downloaded the list of Public and Private data sets
- Public 42 records
- Private 32 records (some are owned by the "Community", do not delete those)

**Comment by dianamartin** [comment]
Realized the OpenData export was not working correctly because I kept getting a blank spreadsheet. Messaged the CTM OD team and Brad got back to me. We sync'd in the afternoon 3/15 and I walked him through my steps. 

He told me that the "Department" filter he created isn't perfect that I had to create a custom filter to to be able to capture the "Austin Transportation" and "Austin Transportation Department" records. 
- Public `79` records - was able to re-download
- Private `???` records - need to have Brad resend since he isn't having any issues

**Comment by dianamartin** [comment]
Messaged Brad 3/16
>Hey Brad, did you get my email about missing records with that last export you sent me?

**Comment by dianamartin** [comment]
Talked about it in App Sync and will divide up the open datasets and chip away at it.

**Comment by KaroEngstrom** [comment]
3/22
- [x] Moved Data QC notes from the Public spreadsheet to the Public 79 one in SharePoint
- [x] Checked a few dozen items against the Open Data List and Data Inventory; indicated the findings in the Data QC columns - total QC count 31/79

**Comment by KaroEngstrom** [comment]
3/23 
- [x] Checked another set of items against the Open Data List and Data Inventory - total QC count now 59/79

**Comment by KaroEngstrom** [comment]
3/24
- [x] Completed the first pass of QC 79/79 comparing the Public 79 list to the Open Data List and Data Inventory

**Comment by dianamartin** [comment]
Will close, going to create new issue for continued refresh tasks
