### ISSUE TITLE
Research Options for Getting Austin Water Utility Data

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#869]
Reach out to Austin Water's GIS SPOC to see what options they have for sharing their GIS Utility data.

**Comment by jaime-mckeown** [comment]
Dolph responded back with multiple options for accessing their data:
- Operations Web Map
- Layer files if we request an account for direct access to their SDE database
- Rest Services to Reuse, Water, Wastewater

**Comment by jaime-mckeown** [comment]
I tested using the Rest Services, was able to add a map service to a Web Map on AGOL.
