### ISSUE TITLE
Feature: Auto page refresh when button is clicked

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8691]
When a user is filling out an application, they get to a page that asks "Do you have a Banner Design ready?"
![image](https://user-images.githubusercontent.com/21112975/157749456-2db2a44e-2ed6-4e04-9be2-06ce89711e53.png)

- If No, you will be taken to the Add Banner Location page - this is a URL redirect to another page
- If Yes, you will be prompted to Add a Design Attachment - this is a trigger button that shows a message
  `Please refresh page and attach Banner Design.`

We'd like for the customer to click the "Yes" trigger button and for the page to refresh based on that action rather than showing the message to refresh the page manually. 

![10DDF430-3E45-4131-9011-C05B4D865A6D](https://user-images.githubusercontent.com/21112975/157750604-298dc682-8a75-4c82-9000-0ef17c417a8e.GIF)

**Comment by dianamartin** [comment]
@amenity here is a new one, just letting you know

**Comment by patrickm02L** [comment]
Looking to launch April 18, or 25th. Meeting with stakeholders tomorrow, 3/30/21. 

Based on Product Sync discussed moving it to the the next sprint. 

@Mateo, says it's pretty straight forward. Would like you to spell out in a comment what the changes would entail. @dianamartin

**Comment by dianamartin** [comment]
## Banner Designs page
![image](https://user-images.githubusercontent.com/21112975/160913776-d83aa385-577f-4a2e-b652-d514026a7db6.png)

LPB Application>Add Design Attachment (add-design-attachment-lpb)
- form back end: https://builder.knack.com/atd/street-banners/pages/scene_1212
- form front end: [Test Event](https://atd.knack.com/street-banners#lpb-application/623b7e10bb81050021bba801/event-information-lpb/623b7e10bb81050021bba801/add-design-attachment-lpb/623b7e10bb81050021bba801/)
- submit design - https://builder.knack.com/atd/street-banners/schema/list/objects/object_161/fields/field_3265/settings - `field 3265`
- option chosen - https://builder.knack.com/atd/street-banners/schema/list/objects/object_161/fields/field_3267/settings - `field 3267`

OTS Application>Add Design Attachment (add-design-attachment-ots)
- form back end: https://builder.knack.com/atd/street-banners/pages/scene_1234/settings
- form front end: [TESTING Feels like Spring Festival](https://atd.knack.com/street-banners#ots-application/622a3e82b4f89b001e9a149e//event-information-ots/622a3e82b4f89b001e9a149e//add-design-attachment-ots/622a3e82b4f89b001e9a149e/)
- submit design - https://builder.knack.com/atd/street-banners/schema/list/objects/object_164/fields/field_3275/settings - `field 3275`
- option chosen - https://builder.knack.com/atd/street-banners/schema/list/objects/object_164/fields/field_3276/settings - `field 3276`

## Form Rule 
- Submit Design set to `Yes'
- Option Chosen set to `Yes`

- If `No`, you will be taken to the Add Banner Location page - this is a URL redirect to another page
- If `Yes`, you will be prompted to Add a Design Attachment - this is a trigger button that shows a message `Please refresh page and attach Banner Design.`

## Page Rules
1. Submit Design is "No" - hides "Add Design Attachment" form/table and "Save & Continue" button
2. Option Chose is "Yes" - hides "Banner Design" details that has "Do you have a Banner Design ready?"

## Knack Confirmation Message configuration
![image](https://user-images.githubusercontent.com/21112975/160914608-9b161716-7f6d-4826-a685-74baef4a4eff.png)

## Knack Confirmation Message - front end
![image](https://user-images.githubusercontent.com/21112975/160919494-ffd307a4-ea40-4011-94b0-7254529b7bd6.png)

# Enhancement Goals
1. Form action field `enter it here` = "Yes"
3. Hide the blue Knack confirmation message notification banner that triggers as a response
4. Auto-refresh the page so that the user will see the "Add Design Attachment" form - there is a page rule that un-hides the form when the "Option Chosen" field is "Yes".

**Comment by dianamartin** [comment]
@amenity The go live for this is was bump to May 1st, but we'd like this done before then so we can test before the go-live

**Comment by amenity** [comment]
@dianamartin thanks for the reminder.

**Comment by amenity** [comment]
@mateoclarke volunteered to pick this one up and take care of by the end of next week so there is time to test. 🙏

**Comment by dianamartin** [comment]
# Testing - 4/27

**Comment by dianamartin** [comment]
Feel good about enhancement, it's behaving as expected.
