### ISSUE TITLE
Traffic register check-in: 14 Mar 2022

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8708]
Attendees: John, Chrispin, Diana, Gilda, Joana, Eric.

### Misc facts
- Eric is the final co-signer on **every regulation**.  He is Rob's delegate as the "City Traffic Engineer".
- Parking enterprise has periodic meetings to review their upcoming regs and "soft" approve them.
- Joana is responsible for checking the Signs & Markings work order system for completed/installed regs, which she enters into the access database

### Todo
- Add a third level of approval for admin staff QA/QC. The order of operations is:
  - Technician drafts a reg package and submits it
  - Admin staff review it for errors, and approve or reject the reg package. Admin staff can also edit the regulations, but changes should be minor and not related to the substance of the reg. When the pacakge is approved or rejected, it is assigned back the original author
  - If rejected: The author makes corrections and resubmits to admin QA
  - If approved: the author assigns the package for approval by area engineer.
  - The area engineer approves or rejects the package. Can also make modifications.
  - If approved, the packaged is assigned to chief engineer Eric B. for final approval
  - If rejected, the technician can make edits and resubmit back to lead engineer

- Throughout the approval process, the approver should be able to add comments that send an email to to the author.

- Consider having the ability to edit the regulation text after it has been autogenerated. So as to handle edge cases/anomalies. 

- Scope an automation which will update regulations with their installation date based on data from the Signs & Markings app. 

Next steps:
- John to schedule bi-weekly meeting with reg authors
- John to groom issues with Chrispin

**Comment by dianamartin** [comment]
I have an old workflow y'all can reference I had made when I was trying to understand the Regulations process. It should show the current process with the 3 approval levels.
