### ISSUE TITLE
Add additional information about PDF CR3 files in Vision Zero Editor

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#8711]
## User Story

As user of the Vision Zero Editor, I would like to know some additional information about the file stored in S3 that contains (or should contain) the CR3 PDF. It would be helpful to see if the file matches the characteristics of a CRIS Login HTML Page that was inadvertently stored when capturing those documents, or also, an indication if the ORC program determined that the PDF on file is a scan of a paper document and therefore not a candidate for OCR.

## Usage
These pieces of information would be helpful in diagnosing why a PDF may be invalid or why certain elements of the crage page are not appearing as expected.

## Background
These ideas came from a discussion with @mateoclarke related to the two VZ issues which were closed last week: #8694 and #8700.

---
**Acceptance criteria**
* This feature would be acceptable if the user were presented with the agreed upon additional information about the state of the PDF or lack-thereof when using the Vision Zero Editor.

**Comment by mateoclarke** [comment]
This sounds good. But one comment I'd like to make is that we should probably try to fix the issue where we download and PDFify the "CRIS Login HTML Page" in the ETL process itself. I looked back for a related issue because I thought we had one in the backlog but I must've been mistaken.

**Comment by frankhereford** [comment]
@mateoclarke wrote:
> This sounds good. But one comment I'd like to make is that we should probably try to fix the issue where we download and PDFify the "CRIS Login HTML Page" in the ETL process itself. 

I agree with this 100%. @patrickm02L, what would you think about expanding this issue to include that work? IIRC, we have some python code that we can reuse to quickly ID a file as being a valid PDF or an HTML page. Also, even just the file size can be used to tell them apart

**Comment by patrickm02L** [comment]
@patrickm02L Bring to grooming 4/18/22.

**Comment by patrickm02L** [comment]
Supe up the ETL with Lib Magic that will help determine whether PDF is scanned or HTML page that's been PDF-ified. The information will be stored in the JSON blob for each crash. 

**Note:** Review CRIS 24.0 Release notes to see if there's a potential endpoint that will free us from re-captcha.

**Comment by mddilley** [comment]
@patrickm02L I'll bring this up in dev sync, but I think a good next step after https://github.com/cityofaustin/atd-vz-data/pull/1171 is tested and merged is to find all crash records with non-pdf CR3 downloads and reprocess them. This would look exactly like what Mateo [did here](https://github.com/cityofaustin/atd-data-tech/issues/6583#issuecomment-877991466) and would estimate on a 1 or 2. That should take care of this issue going forward. 🤞 📄
