### ISSUE TITLE
Execute and monitor a fresh OCR pass on ~10K Crash CR3s

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#8712]
Recently, ~10K crashes have been identified as candidates to give the OCR system another pass at their CR3s to make sure we have extracted narratives and diagrams wherever possible. 

Please see the "Next Steps" in the following comment on #8700: [here](https://github.com/cityofaustin/atd-data-tech/issues/8700#issuecomment-1065749324).

This ticket is to document the work of executing that OCR pass which is expected to involve a single query to start the process and then intermittent monitoring of the DAG responsible for executing that work. Total duration of task is <12 hours, however, nearly all that time is a DAG running in the background without user interaction.

**Comment by patrickm02L** [comment]
@frankhereford Thanks for documenting this!

**Comment by xavierapostol** [comment]
I found a few more that have a narrative, but are missing a "Field Diagram" (strange). I hope this is the correct issue to add these into.
https://visionzero.austin.gov/editor/#/crashes/15570073
https://visionzero.austin.gov/editor/#/crashes/15588763
https://visionzero.austin.gov/editor/#/crashes/15575949

**Comment by frankhereford** [comment]
@xavierapostol wrote:
> I found a few more that have a narrative, but are missing a "Field Diagram" (strange). I hope this is the correct issue to add these into. 

it is - thank you! I am about to trigger the re-OCR pass on all crashes missing one or the other pieces of information from the OCR. All the crashes you listed☝️ are in the set that will OCR'd. 

I'm going to start with these 8 as another test, and if they are repaired, I'll close this ticket once the larger pass is underway.

**Comment by frankhereford** [comment]
There is something more complex going on here. I have triggered the DAG after updating the database to cause these crashes to be processed. The continue to not have a diagram displayed in the VZE. 

I will next spin up a copy of the docker image which does this processing and step through the process to see what's preventing these from being handled as normal. 🔧 🔨

**Comment by frankhereford** [comment]
The above crashes are repaired in terms of the OCR related tasks.

Got the image built and the script behind the dag appears to be working without modification my local copy. I'm going to work through the backlog created by the following query. In the interest of getting this done quickly and ease of monitoring, I'm going to do the OCR task here locally before handing it back to airflow in a few hours.

```
update atd_txdot_crashes set cr3_ocr_extraction_date = null
where cr3_ocr_extraction_date is not null
and crash_date >= '2015-01-01'
and (  cr3_file_metadata->>'diagram_s3_file' is null
    or investigator_narrative_ocr is null)
```
