### ISSUE TITLE
[Enhancement] Add Public Works' Task Orders to our ETL Scope

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8724]
As requested in #8406, Moped users need the ability to identify PWD's task orders as part of Moped's funding UI. 

Currently, our DB view (furnished to us by Financial Services Department) only includes ATD's task orders (department codes `2400`).

We need to:
- [x] Request that our DB view be modified to include PWD task orders (dept code = `6207`)
- [x] Verify that [our ETLs](https://github.com/cityofaustin/atd-finance-data) (including any new ETLs via #7931) will pick up these new records automatically.
- [ ] Decide if we want these PWD records included in the Data Tracker. If no, we need to modify our existing Knack ETL to exclude PWD records.

**Comment by amenity** [comment]
A significant number of AMD's projects have PWD funding codes (6207?), so moving this up as equal priority to #7931

**Comment by johnclary** [comment]
I reached out to Eva S. at FSD to request PWD task orders

> Y'all have provided us with a DB view of task orders ( DEPT_2400_TK_VW).
> 
> Would it be possible to modify this view, or create a second view, such that it also includes task orders from public works (dept code 6207).

**Comment by amenity** [comment]
@johnclary - ping

**Comment by amenity** [comment]
@amenity - please make an issue for that last item.
