### ISSUE TITLE
SIF - Auto-populate Property Information in Folder 

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8725]
Acceptance Criteria: 

- All acceptance criteria below applies to SIF folder only 
- When a user adds a Primary Property to the SIF folder, the system needs to auto-populate the SIF Folder infos 'Council Districts' and 'SIF District' with values from Property Infos 'Council District' and 'SIF District' of the Primary Property selected in the folder.

**Comment by TracyLinder** [comment]
@Lpriya-LIT can you please update with the current status?

**Comment by TracyLinder** [comment]
Priya is still working w/ CTM on this. Currently working w/ Martin on possible solutions.

**Comment by Lpriya-LIT** [comment]
@TracyLinder Committed changes, Ready for Dev promotion
@Nadin-Nader Please request for Dev deployment , have sent the deployment plan.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been sent to the DevOps CM Team to deploy to **_DEV_** under **SCTASK0210988**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder all 6 commits have been sent to be deployed to **_TEST_** By the DevOps CM Team under **SCTASK0213187**

> Commit list:
> 8375 - '28c3faeef4e7'
> 8375 - '2ce43d8a7eff'
> 8833 - '2d133cafadee'
> 8728 - '218f353bbb29'
> 8726 - '4fccec6ebbad'
> 8725 - 'aa6db6c443df'

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been deployed to TEST. Please UAT

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Test , The SIF Folder infos 'Council Districts' and 'SIF District' are auto-populated with values from Property Infos 'Council District' and 'SIF District' of the Primary Property selected in the folder.
