### ISSUE TITLE
SIF - Auto-Populate SIF amounts folder Info

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8726]
Acceptance Criteria: 

- All acceptance criteria below applies to SIF folder only 
- When a user saves a row in the Building SIF Info freeform, system should total the values provided in all rows of the freeform with Status 'Active' for column 'Total Reduction Amount' and populate that value in the 'Total Reduction Amount' Folder Info. 
- System should also total the values provided in all rows of the freeform with Status 'Active' for column 'Standard SIF Amount' and populate that value in the 'Total Standard Amount' Folder Info.

**Comment by Lpriya-LIT** [comment]
@TracyLinder Committed changes, Ready for Dev promotion
@Nadin-Nader Please request for Dev deployment , have sent the deployment plan.

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0210765**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Dev, We can Deploy to Test once all the additional corrections are done and approved by SIF Team

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder all 6 commits have been sent to be deployed to **_TEST_** By the DevOps CM Team under **SCTASK0213187**

> Commit list:
> 8375 - '28c3faeef4e7'
> 8375 - '2ce43d8a7eff'
> 8833 - '2d133cafadee'
> 8728 - '218f353bbb29'
> 8726 - '4fccec6ebbad'
> 8725 - 'aa6db6c443df'

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been deployed to TEST. Please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder Verified in test , works as expected.

**Comment by Lpriya-LIT** [comment]
Freeform column names are updated in #8894. Need to update the coding to include the change. Work in Progress.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT I have sent this to the DevOps CM Team to be deployed to **_DEV_** and **_TEST_** under **SCTASK0215205**

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader The changes are deployed to Dev and Test, verified and works as expected.
