### ISSUE TITLE
[TDS-TIA] Data Research: Updating Intersections & Street Segments with CTN/CTM data

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#8727]
- Determine which dataset is best for updating street segments & intersections data in the mitigations_geo object for TIA
- Determine method and frequency for updating the data in Knack (integration possible?)

**Comment by ChrispinP** [comment]
Andrew will merge together the CTN and CTM data together for us so we can compare with Knack dataset for an accurate master list.

**Comment by ChrispinP** [comment]
Added new CTN fields to Mitigation Geo object in preparation for importing new segments and intersections. Andrew was able to merge segment datasets and provide. Requested intersection datasets now.

**Comment by dianamartin** [comment]
We intent to re-purpose this issue to be the task for updating Geo records with the TIA Mitigations

**Comment by dianamartin** [comment]
Let's have this discussion with Geo team at the start of the year, 2023
- Try to match update cadence with a Apps maintenance task to update TDS street segments

**Comment by TracyLinder** [comment]
**Next Steps:**
- sync w/ Geo to determine effort & resources
- [ ] Tracy will schedule w/ Andrew, Chrispin, Diana

**Comment by TracyLinder** [comment]
# Meeting Notes
- Mitigation map data set is static
- Needs to be refreshing to capture add/deletions by CTM street segment changes
- Decision to refresh quarterly
- Not worried about intersection data right now, maybe in the future 

## Future Steps
- automated process? 
- the return on investment doesn't seem worth it here
- We DO have to map these mitigation records in geospatial format


## Action Items
- Andrew: taking add/delete report and publishing to AGOL dataset 
- Chrispin: export the mitigation dataset and figure out highest locations and additional locations, give list to Andrew's team
- Tracy: set up meeting with Nelson to find out about mapping preferences and goals
- Tracy: set up GItHub stuff

## Proposed Steps
- Chrispin: export mitigation table `~679 records` to cross reference the AGOL dataset to see if anything needs updating

**Comment by TracyLinder** [comment]
Goal refresh: End of February

**Comment by ChrispinP** [comment]
I've sent Andrew a list of the 40 records that have geo records connected. The remaining mitigation records are still missing locations. We will crosscheck the IDs for the last 2 years to see if any of these 40 records need to be updated.

**Comment by ChrispinP** [comment]
Andrew was able to determine only 1 of the records needs to be updated: Mitigation Feature ID "5775251" was an intersection point at Bluebonnet and S Lamar that has been changed in the CTM Intersection data to "6615726"

@TracyLinder @dianamartin Should I manually update this one record and keep track of its previous ID in another field or just override?

**Comment by dianamartin** [comment]
@ChrispinP I think override, I don't think we need to keep the historical ones because it's not being referenced in anything else beside the TIA Mitigation, right?

**Comment by ChrispinP** [comment]
I have updated the single record:![image.png](https://images.zenhubusercontent.com/5f036c8940760b58210af838/0f513387-6ed6-4e34-924e-09f4109ff074)

Complete, ready to review. Should we create a yearly or 6 month task to review these again in the future?
