### ISSUE TITLE
SIF - Unique ID for SIF Building Info Freeform 

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8728]
Acceptance Criteria: 

- All acceptance criteria below applies to SIF folder only
- When a user saves a new freeform row in the SIF Building Info freeform, system must generate a Unique ID for that row (such as 1, 2, 3... and so on) and insert it in the Unique ID column of the newly saved Freeform row.

**Comment by TracyLinder** [comment]
It's ok to label this column **Freeform RSN**

**Comment by TracyLinder** [comment]
@Lpriya-LIT can you please update with the current status?

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/f366492b-4775-43f2-8fd9-111afea26800)

**Comment by Lpriya-LIT** [comment]
the Unique id will be generated when the row is saved. Done the coding in localhost, will update once the changes are promoted to Dev and Test

**Comment by Lpriya-LIT** [comment]
@TracyLinder Committed changes, Ready for Dev promotion
@Nadin-Nader Please request for Dev deployment , have sent the deployment plan.

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0210703**

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been deployed to DEV, Please UAT

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Dev, We can Deploy to Test once all the additional corrections are done and approved by SIF Team

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been deployed to TEST. Please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder Verified in test, Unique id is generated.
