### ISSUE TITLE
SIF - Allow bill payment through portal

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8731]
Acceptance Criteria

- All Acceptance Criteria provided here applies for SIF folders only. 
- A user whose people record is added as Applicant to the SIF folder should be able to view the SIF folder on the My Permits page of the portal. 
- The user should also be able to pay any outstanding bills from the SIF folder through the Portal.

**Comment by TracyLinder** [comment]
Bill should be payable for all SIF folder statuses.

**Comment by TracyLinder** [comment]
@Lpriya-LIT can you please update with the current status?

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader committed changes, sent you the deployment plan. Please request for Dev promotion

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been sent to te DevOps CM Team to be deployed to **_DEV_** under **SCTASK0219171**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Dev, ready for Test promotion.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0219441**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Test
