### ISSUE TITLE
SIF - SIF folder on Portal 

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8732]
Acceptance Criteria

- All Acceptance Criteria provided here applies for SIF folders only. 
- A user accessing the Portal should be able to search for and view SIF folders through the Public Search tool on the portal.
- All folder information on the SIF portal can be displayed in the folder details without any restriction.

**Comment by Lpriya-LIT** [comment]
@TracyLinder Committed changes, Ready for Dev promotion

**Comment by TracyLinder** [comment]
@Lpriya-LIT thank you. Will you be submitting deployments to Nate?

**Comment by Lpriya-LIT** [comment]
@TracyLinder  yes Tracy. Nate reviewed the commit and I have sent him the dev deployment plan as well.

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Dev, As per Gita I have to do a additional commit to make SIF folder available in Public Search. Work in progress

**Comment by TracyLinder** [comment]
@Lpriya-LIT can you please add a comment with your recent updates?

**Comment by Lpriya-LIT** [comment]
@TracyLinder A custom web service is used to make a folder visible in Public search,  Need to do a commit to add SIF to that, Work in Progress

**Comment by Lpriya-LIT** [comment]
@TracyLinder Added SIF to a lookup table 99091 to make it visible in public search and committed changes.
@Nadin-Nader Sent you the deployment plan , please request for Dev promotion.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0219116**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Dev, ready for Test promotion.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0219438**
