### ISSUE TITLE
Equity Analysis of the Mobility Annual Plan

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8733]
- Equity Analysis Zones (EAZ) - [About](https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/Equity_Analysis_Zones_2021/FeatureServer) | [Map](https://www.arcgis.com/home/webmap/viewer.html?url=https://services.arcgis.com/0L95CJ0VTaxqcmED/ArcGIS/rest/services/Equity_Analysis_Zones_2021/FeatureServer/0&source=sd)
- Mobility Annual Plan (MAP) - [About](https://data.austintexas.gov/stories/s/Mobility-Annual-Plan/2xkd-czyh/so) | [Map](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=c4ce502105e748fb8be725eb54a35fae)

---
Requested by Laura D. and Anna M.

**Comment by amenity** [comment]
@amenity please schedule and ask Anna and Laura to submit a concise request.

**Comment by amenity** [comment]
### 3/29 internal meeting to review request 
@andrewshensky @mateoclarke @Charlie-Henry @amenity

**Now**
- Andrew is building in ArcGIS and checking in periodically with Anna and Laura
- Their initial ask was [project-counts-per-EAZ broken up by type](https://user-images.githubusercontent.com/1463708/160698732-4c647f57-247d-4827-9695-266ad4c59ebb.png)
- ☝🏻  problematic because big projects might just barely enter a zone
- Want to give them a map, too, to demonstrate the potential of this meaningful data
<img width="1150" alt="Screen Shot 2022-03-29 at 3 15 51 PM" src="https://user-images.githubusercontent.com/1463708/160711200-c705c507-4aa7-47ee-a615-a595955eca71.png">

**Future**
- More meaningful calculations using linear feet 
- Consider the larger network impact; whose commute/travel do these improvements ultimately benefit
- Include expenditures
- Pull projects directly from Moped



@andrewshensky, please forward future meeting invites to Mateo

**Comment by amenity** [comment]
@amenity - circle back with Laura and Anna to schedule a review of where things stand for @Charlie-Henry and @mateoclarke

**Comment by patrickm02L** [comment]
Unassigned @mateoclarke and @Charlie-Henry on 6/15/22 Sprint review to clean things up a bit. They'll continue to be notified if things change in the epic.

**Comment by andrewshensky** [comment]
@amenity Here is the link to the current dashboard for this project. It may be worth including in the email to aid users.
https://austin.maps.arcgis.com/apps/dashboards/c948db63ff9f4941a7d237bc0bfac940

**Comment by amenity** [comment]
@andrewshensky - it looks like this work has tapered off. Should we close the epic?

**Comment by andrewshensky** [comment]
@amenity I definitely support closing this issue. I will go ahead and do so now.
