### ISSUE TITLE
[Traffic Register] Feature: Ability to track temporary/event regs and auto-retire

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8737]
Ability to flag certain regs as temporary and define an expiration date for their removal.

- Where do we track the "temporary" status and expiration date? On the reg package or individual regs?
- Can we automatically retire temporary regs, or do they need to go through the full approval process?

**Comment by ChristinaTremel** [comment]
Chrispin has created the fields to do this, but need to ask stakeholders if this is still a need and if we need to implement it.

**Comment by ChristinaTremel** [comment]
@ChristinaTremel Ask City Engineer and Area Engineers to make a decision on if we need to track temporary/event regs.

**Comment by ChristinaTremel** [comment]
We discussed this during a sprint review and Engineers no longer create temporary regs for construction zones. This feature is no longer needed.
