### ISSUE TITLE
Update ETL to prevent overwriting of human-updated fields in Unit, Person & PrimaryPerson tables

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#8746]
_Relates to #8639_ 

The two specific fields in the Units where we've lost data are `travel_direction` and `movement_id`.

These columns were created by ATD DTS and do not exist in CRIS' data. On import, an upsert should not delete these values. 

The first mystery to solve is why these records are being overwritten. Then we need to update the ETL or triggers that run when a Unit record is updated or created to fix this problem going forward.

We also need to account for data we change or edit on Person and Primary Person tables

**Comment by mateoclarke** [comment]
One immediate thing I've noticed is that there is an active trigger in the DB that isn't manually version controlled in our [`atd-vzd/triggers` directory](https://github.com/cityofaustin/atd-vz-data/tree/master/atd-vzd/triggers). It is called `atd_txdot_units_create` and contains this SQL code:

```sql
CREATE OR REPLACE FUNCTION public.atd_txdot_units_create()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN

  NEW.travel_direction = NEW.veh_trvl_dir_id;
 	NEW.movement_id = 0;

    RETURN NEW;
END;
$function$
```

According to our DB, the trigger only runs on INSERT but maybe something about our ETL treats new Unit updates and secondary records as INSERTS? Not quite sure but thought it could be an important insight.

![Screen Shot 2022-03-22 at 12 07 11 PM](https://user-images.githubusercontent.com/5697474/159536194-bc7d8ce8-ea91-476e-9058-0b35ffca8b8d.png)

**Comment by mateoclarke** [comment]
Action items from 3/31 grooming meeting:
- [ ] Explore the ETL function by experimenting with dummy CRIS unit extracts to insert/update on a fake crash via standard process
- [ ] Discover if the `atd_txdot_units_create` is being executed on "updates"/"upserts".
- [ ] Write updated unit business logic in ETL ([`process_line`](https://github.com/cityofaustin/atd-vz-data/blob/master/atd-etl/app/process_hasura_import.py#L95)) or record type specific trigger (ex: `atd_txdot_units_create`)

**Comment by mateoclarke** [comment]
In Backlog Grooming on 7/6, we discussed expanding the scope here to make sure person and primary person table table is also protected for overwrites.

**Comment by frankhereford** [comment]
Pre-work Results:

The following database fields are editable from the VZE and when crafting upserts, the existing stored in the database will be protected from an overwrite by incoming CRIS data:

```
atd_txdot_crashes.longitude_primary
atd_txdot_crashes.latitude_primary
atd_txdot_crashes.city_id
atd_txdot_crashes.crash_speed_limit
atd_txdot_crashes.road_type_id
atd_txdot_crashes.traffic_cntl_id
atd_txdot_crashes.crash_sev_id
atd_txdot_crashes.atd_fatality_count
atd_txdot_crashes.apd_confirmed_death_count
atd_txdot_crashes.tot_injry_cnt
atd_txdot_crashes.sus_serious_injry_cnt
atd_txdot_crashes.address_confirmed_primary
atd_txdot_crashes.address_confirmed_secondary
atd_txdot_crashes.private_dr_fl
atd_txdot_crashes.road_constr_zone_fl
atd_txdot_crashes.micromobility_device_flag

atd_txdot_units.travel_direction
atd_txdot_units.movement_id
atd_txdot_units.death_cnt
atd_txdot_units.sus_serious_injry_cnt

atd_txdot_person.injury_severity
atd_txdot_person.prsn_age

atd_txdot_primaryperson.injury_severity
atd_txdot_primaryperson.prsn_age
```

**Comment by patrickm02L** [comment]
Upgraded this Issue to an 8 to reflect the complexity and effort spent to realization versus the initial 3 we estimated on the outset.

**Comment by frankhereford** [comment]
Reopening this until all deployment steps are completed, as seen [here](https://github.com/cityofaustin/atd-prefect/pull/28#issuecomment-1251477196).
