### ISSUE TITLE
Rename VZD table "atd_txdot_changes" to "atd_txdot_conflicts"

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#8747]
This table gets confused with `atd_txdot_change_log` often. The intention of the database is to protect record changes from automatic CRIS updates by holding them in a queue for manual review. They represent records where incoming CRIS data conflicts with human changes.

**Comment by johnclary** [comment]
We would have saved future devs a lot of confusion if we ever got around to doing this, but we didn't, and now the table will be removed in the new data model. cc @frankhereford
