### ISSUE TITLE
Create Data Structure for New Utility Pole Workflow

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#8754]
New layers, fields, and domains have been requested to be added to AE Pole data. The new fields and domains will also need to be added to bluebonnet and perdernales data once everything looks good for AE Pole. We will also need to determine process for capturing existing data and adding to updated pole data when received.

**Comment by johnclary** [comment]
Andrew has put together the basic structure for incorporating changes between AMD's data and AE's data.

Andrew will show AMD folks so that they can test it out and provide feedback.

**Comment by johnclary** [comment]
Closing this out - will open new issues once AMD starts providing more feedback
