### ISSUE TITLE
Update QC Process for Install w/o Poles, Removals, and Outliers

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#8766]
The QC process for installs w/o poles, removals, and outliers can be streamlined by tracking these attributes in the Sign Maint Dataset. Fields will need to be added and attribute rules will need to be implemented.

**Comment by johnclary** [comment]
### New fields in signs maint dataset
- Type of QC
- QC Status

### Attribute rules
- set status and attributes automatically based on point location
