### ISSUE TITLE
Conduct customer testing for new public Banners portal

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8769]
Recruit ATD staff who are unfamiliar with the Banners process and conduct testing with them as "customers".

**Comment by johnclary** [comment]
@moorerst @dianamartin please make sure this gets done before go-live.

**Comment by dianamartin** [comment]
# To Do
## Write Test Script
- Submit Application
- v1. Do not attach Design Attachment
- v2. Attach Design Attachment

## Invite Testers
Possible testers
- Erin B - AMD
- Renee O - AMD
- Dan Brown - SDD
- Andrea Martinez - SMS
- Ryan Royal - SMS
- Paul Baldwin - MS

**Comment by moorerst** [comment]
sent email to 6 potential user testers. Asked them to reply with date/time they are available for 1 hour user testing

**Comment by dianamartin** [comment]
@moorerst are we good with only 3 testers?

**Comment by moorerst** [comment]
[Usability Testing Feedback](https://docs.google.com/document/d/1cPHWUrOAl34z6KnpQe3sLtpRNJ7SNtufSXt2Iz7VOiU/edit#)

**Comment by moorerst** [comment]
Completed user testing with 3 testers. Combined the feedback into a comprehensive document that we will review with the stakeholders in meeting scheduled 3/31
