### ISSUE TITLE
HR SharePoint Site Redesign

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8771]
**Goal of project:**
Redesign the current ATD HR SharePoint site to be more interactive and provide easy access to things that employees request all the time. 
Be a one stop shop for all things HR.

https://cityofaustin.sharepoint.com/sites/ATD-HR/SitePages/Home.aspx

**Scope of project:**
- Provide the basic design and framework so ATD HR staff can maintain the site

- Use CTM HR SharePoint site as a model for design

- Design Homepage

- Build out 3 HR Resource sections
Employee
Compensation
Employee Relations (policies and procedures)

- Build the framework for Quick Links section and External Links

**Comment by moorerst** [comment]
@KaroEngstrom have you had any recent communication with Adan regarding HR sharepoint updates? Should I reach out to him to see if any additional assistance is needed? Want to close this issue if we have completed our part. Thoughts?

**Comment by KaroEngstrom** [comment]
@moorerst I talked to him briefly and he is only wanting a consult type meeting with me to look over / help with small tweaks to his content. No need to reach out. It sounds like no real deliverable for us, just maintenance type consult meeting. So we can close as completed and I can do a separate standalone ticket if any small request comes out of the maintenance consult meeting. Thanks.

**Comment by moorerst** [comment]
Deliverables for this issue have been completed. We will continue to provide maintenance and consultation as needed. Closing this issue
