### ISSUE TITLE
Design Review for HR SharePoint Redesign

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8772]
Design Review and markup for:

- Home page

- HR Resource sections

Employee
Compensation
Employee Relations (policies and procedures)

Will schedule design review meeting with stakeholder for 4/5

**Comment by moorerst** [comment]
@KaroEngstrom you can log/track your SharePoint redesign task on this issue.

**Comment by KaroEngstrom** [comment]
- [x] Checked in with @dianamartin on the design M 4/4/22
- [x] implemented proposed changes T 4/5/22; ready for Sprint Review with HR stakeholder

**Comment by moorerst** [comment]
@KaroEngstrom @dianamartin sorry I missed the check in meeting yesterday. The review of the redesign updates are the only thing on the agenda for the meeting today . We'll have you demo the redesign and get feedback. Thanks

**Comment by moorerst** [comment]
@dianamartin @KaroEngstrom 
The site looks really nice and fresh. Good job!
I have few observations:
-  Welcome to ATD Human Resources home page - should Home Page be capitalized?

-  The purpose of the Human Resources - suggestion The Purpose of ATD Human Resources...

- I was confused by the titles under the images I thought that's what I was going to see. Can there be a title on the images to indicate what information is available there? Like you did for Supervisor Resources.

- The eTimesheet Resource Page does not open in another tab like some of the other links - its a little cleaner when it opens in a new tab you can close it and be back at the site

- HR Portal Link - should that be the link you have or this link https://hrportal.coacd.org/login.cfm?

- In some places you use HR in some place Human Resources - suggestion consistently use ATD Human Resources

**Comment by moorerst** [comment]
@KaroEngstrom I kinda changed by mind I think I like HR Function and HR Team better. 
We can let the stakeholder decide.

**Comment by dianamartin** [comment]
# Diana's Notes
- Karo leads this meeting
- Adan likes "hero" elements
  -  auto size text

### Top of HR page section
- keep Mission Statement - likes the summary

- ### 3 Main HR Function sections
- [ ] change "Compensation" page to hero links

### Supervisor Resources section
- call to action button
- can add "Click Here" to be more obvious or "-----> Supervisor Resources"

### HR Contact section

**Comment by moorerst** [comment]
- Karo did a good job of leading the review with the stakeholder.

- She reviewed each section. It was nice that each section displayed a different style so the stakeholder could see different possibilities.

- Overall he was very happy with the initial redesign. 
Action items:
- He will review the look and feel of the site with his team as well as additional content that can be added.
- We will schedule follow up meeting to review the feedback from the HR team
