### ISSUE TITLE
Crashes are not being delivered and imported from CRIS

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#8775]
During the daily downloading of CR3s, for the past 3 mornings, I have observed no new crashes having been imported into the system. I recommend that we investigate what is holding up this integration by looking into the CRIS SFTP endpoint, the CRIS query / export itself, and the ETLs used to import that data. When the problem is understood and then resolved, a query to backfill crashes should be executed and run through the import process.

**Comment by frankhereford** [comment]
Our `transportation.data@austintexas.gov` CRIS account which houses the CRIS queries that send us data daily extracts of data has been disabled, presumably from not logging into it frequently enough. 

I am going to ask @mateoclarke if it's alright if I call them to resolve it. He has handled this type of communication in the past, but I'm interested in picking up that task if that's a workable route.

**Comment by frankhereford** [comment]
I spoke with Mateo on slack, and he gave me a 👍 to call CRIS. I did so, and they were not willing to discuss the account with me, as my name was not associated with the account at creation.

@mateoclarke, I'm afraid they want to speak to you. The representative that I spoke to asked me to pass along that they would want to know that it's an _extract_ account as well. 

Sorry I wasn't able to pick this up and get it completed - thank you a ton for your help.

**Comment by mateoclarke** [comment]
I called in and was able to successfully request that they re-enable the account. I'm going to make sure to add you to the reminder to for periodic login Frank. Hopefully that helps mitigate this issue going forward. Here is my support ticket number: #CRIS286871
