### ISSUE TITLE
Configure Attachments

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8779]
There are 12 attachment requirements

Initially configured three options:
Option | Type | Pro | Con
-- | -- | -- | -- 
1 | Table view - Patrick suggested | easy to read | lag time and related table
-- | Can separate how many child records get created by splitting up trigger to create records, some on Pg 1, some on Pg 2
2 | Separated, filtered table view | very separated to see section | overkill? 
3 | All the text upfront, add button as table | all the information is laid out | too much to read all at once & not that easy to read
4 | Created fields for attachments in application - John's suggestion | easier for processing time | not that easy to read

**Comment by dianamartin** [comment]
Showed stakeholders 3/24, we talked about going the table view route. I said I'd like to try the embedded attachments on the attachment to see what that's like too.

**Comment by dianamartin** [comment]
# Diana's Notes 4/7
## Payment Information section
- 1500 and 750 
- Collect payment at six month term
- Put $750 first then $1500 total over 12 months 

## Eligibility section on Get Started
- [ ] Add bullet, expression of interest form
- TX Sales Tax License

## Application Changes
- Add new field "Adding to Fleet?" - Mary V.
- If "Renewal" - don't show "Initial Fleet" only 
  - "Additional Units" 
  - "Number field"
 
## Add New Fields to App
- Type of device
- Permit Term 
>She will provide choices for these

## Change "Comment" field
 - [ ] from Short Text to Rich Text

# Future Ideas
Renewal - Past Performance reporting
- Grading sheet per provider
  - Number of Trips
  - Impounds
  - Fees Paid
  - how long it takes to pay invoice
  - how long it takes to closing CSRs
  - Unresponsive
  - Not wearing PPE

## Diana's Performance Idea for Attachments
Edit - Approve attachments individually 
- Approve

## Additional Processes
### BEFORE APPROVAL
- Working API feed
- Bond 
- Insurance

### AFTER APPROVAL
- Device Inspection - done after approval
- Take device photos (use Attachments table?)

# NEXT STEPS - Discovery of Attachments
1. Table Creation - SMS app ahead of time
2. Adding attaching attachment one by one
3. Attachments related app

Plan is to create 3 forms that really allow use to test different attachment layouts/structure
- make attachments not required - FOR TESTING
- 5-6 attachments on forms

# Proposed Process
1. Expression of Interest
2. SMS Staff to create account and application
3. Provider create or edits application?
4. Provider then work on attachment requirements
5. Provider to submit application
6. SMS Staff to review application
- In Progress - Pending Action
- In Progress - Complete Action
- Pending Approval - Pending Action
7. Provider finalizes additional requirements (API, Bond, Insurance)
7. SMS Staff to "Approve"
8. Provider get device inspection
9. SMS upload photos of inspection & inspection report
10. Provider receives license

**Comment by patrickm02L** [comment]
Pages are ready to test, send link to SMS Team to do initial testing for Fri, April 22. Ask them to give general observations and provide screen shots. 

https://atd.knack.com/smrt#app-option-1/
https://atd.knack.com/smrt#app-option-2/
https://atd.knack.com/smrt#app-option-3/

**Comment by patrickm02L** [comment]
Sent email to SMS team 2/20/22 asking them to test the links for the upcoming Sprint meeting.

**Comment by patrickm02L** [comment]
Showed to SMS team on 4/22/22. They liked option 3, which @dianamartin has implemented.
