### ISSUE TITLE
[TDS] Enhancement: Update TDS Connected Cases Feature

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#8780]
I'd like to update the Connected Cases Feature to replace the inline editing with the improved icon + form layout instead. This will improve readability that the field is editable.

Currently:
![image](https://user-images.githubusercontent.com/67915167/160014745-30febbcd-77bf-48de-8453-beb9cd503b53.png)

Improved:
![image](https://user-images.githubusercontent.com/67915167/160015058-eb5849eb-f061-41db-bd26-542b8107929e.png)

**Comment by TracyLinder** [comment]
### Update
- This feature is live, although not being used much. 
- Tracy will send users email encouraging user adoption of this feature.
