### ISSUE TITLE
Bug: System Report (50510) Date Errors with EX - Extension Granted (On PROD🎉🎉)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#8794]
Report (50510) ROW Performance Summary Report is not showing all of the dates on the printed report.

-  System should be using all 4 Date fields for the INFO tab:
   -  Estimated Start Date, Estimated Completion Date, Extended Start Date and Extended Completion date
-  System Should hide the Extended Date fields (Not showing on the report) when they are null or the permit has not been extended

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been approved to Move all the way to PROD if it works as expected in each environment

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - UAT Approved. DEV DP submitted and 50510 Report sent for DEV promotion. Kindly approve and create task id for me.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have deployed the updated report to **DEV**, Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV and it is working as expected. Ready for TEST promotion.

![image](https://user-images.githubusercontent.com/44907715/162063823-0ab06368-15d6-4a41-82e4-d4a4bff9c4f6.png)


![image](https://user-images.githubusercontent.com/44907715/162064024-8e8cf2ce-ebe9-4fce-ae3e-9d49eacd7e45.png)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have deployed this to TEST. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST environment. all working as expected and ready for UAT and PROD Move.

**Comment by TracyLinder** [comment]
### Approved for PROD 🎉

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - PROD DP Submitted. Kindly approve and create task id for me.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i have sent this over to CTM to deploy to **_PROD_** under **SCTASK0212676**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan i spoke to Anu and she said that she deployed this to PROD. Please verify. I will also verify and if all is well i will let ROW know about it.
