### ISSUE TITLE
Support SMD tablet evaluation

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8797]
Priority evaluation criteria: 
- Airwatch launcher performance
- Attachment usability (need to be able to view in browser; currently downloads)
- Run through signs work order process to compare general web-app performance & usability differences and Knack compatibility

**Comment by dianamartin** [comment]
I have messaged Danny (CTM) 3/29
>Hey Danny, I was wondering if you finished the iOS AirWatch test profile for Signs and Markings? I'm eager to set up the ipad I have so I can test before Friday. I am helping the Signs and Markings stakeholders decide the budget and which hardware to recommend moving forward. Let me know ASAP :pray:

**Comment by dianamartin** [comment]
Sync with Christina on 3/30
- Tablet Testing ipad/Android

## Android - New Launcher
- Opening attachments - working better than old profile, still have to download and open in Adobe to see plans
- Don't have to be in Admin mode to allow Adobe to open (Ask Danny was admin mode bypassed?)
- Launcher profile, not normal apps android mode still
- Hub, can see App Catalog
- Chrome browser - worked well with Knack
- Didn't require pin to be set (ask Danny about pin requirement)


## Ipad - New Launcher
- Open Attachments shows a preview, option to open in Adobe Reader

See if Thursday 1 pm, 4 pm works for Danny
or Friday some point

**Comment by dianamartin** [comment]
Followed up with Christina 4/19
>[12:15 PM] do we have to do any more testing for the new SMB AirWatch profiles? I still have this issue open

**Comment by dianamartin** [comment]
Send user a follow-up message 8/4
>Hey, I'm following up about

_Followed up with Christina 4/19
    [12:15 PM] do we have to do any more testing for the new SMB AirWatch profiles? I still have this issue open_

**Comment by dianamartin** [comment]
Christina says that the evaluation is completed and they're working on procurement options for the new tablets.
