### ISSUE TITLE
Enhancement: HR Work Log Prototype

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8799]
Add new enhancement to the HR portal
Develop a prototype

HR Work Log page(s):

**- Tracking Employees Daily Activity:** 
audit purposes
see what work is happening
prioritize work

**- Employee will enter task updates daily**

**- Task details will be entered by 9am for the previous day**

**- Need to capture**
entered date/time
entered by
task details (freeform text)

**- HR Admin will review task**
Reviewed check box 
Reviewed By
Review date/time
Comments (?)
Email employee for specific task (?)

**- Reporting**
Ability to filter by timeframe
Ability to filter by employee
Ability to export records

**Comment by dianamartin** [comment]
- [x] Created object table `hr_work_log`
Fields:
- HR Work Log ID
- Created Date
- Employee Name
- Work Log Description
- Reviewed By
- Reviewed Date
- Review Status
- Submitted Date
- Work Date
- [x] Created page `My HR Work Logs` - for staff
- [ ]

**Comment by dianamartin** [comment]
Sync'd with Stephanie and updated
- Removed all test "delete" buttons
- Updated Status Colors
- Added "Email" Y/N
- Added Employee Email (text formula)
- Added Employee Email Edit (email)
- Submitted Date - activated Time settings
- Updated Edit Log | Staff and Supervisor to include "Review Comments" 
- Added "Email" Y/N to Edit Log | Supervisor to allow supervisor to email employee comments

**Comment by moorerst** [comment]
Will review with stakeholder 4/13

**Comment by dianamartin** [comment]
cc: @moorerst Sync'd with Nathan and he said he and Jennifer would review the HR Work Logs tomorrow, 4/20 and get back to us by the end of the day so we can delete test records and finalize things so they can go-live with their new module.

**Comment by moorerst** [comment]
closing this issue. Tracking stakeholders feedback on issue #8802
