### ISSUE TITLE
Manage preliminary real-time road closure vendor procurement process 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8804]
Need to get guidance on moving forward with vendor evaluations

3/30 - met with Ken and Dan w/ATD Finance

Provided overview of what the project is and what we want to accomplish:

- The high level goal of the project is to have suite of tools which enable City staff to manage notifications and push road closure notifications to the public and navigation app providers. 

- This project has been scoped using Amanda as a possible solution however for various reasons it will not be viable solution. 

- The stakeholder are now exploring a few different platforms for managing lane closures and related data. 

- They have a list of vendors with software that may meet this need that they would like to explore 

- I’m looking for some direction on what is the proper way to handle this. 
Can we contact  3 – 4 vendors provide them with some requirements and gather information on what they have to offer? 

- We are having meetings with the various stakeholders (ROW, MMC, Office of Special Events) to gather their requirements.

- They are also interested in pursuing a Grant to help with the cost.

- They hope to encumber the funds for the project this fiscal year.

- They estimate the cost might be 120k – 150k

- I need to provide the procurement method and estimated timeline.

Discussion:

- Do we need to do a Request for Information (RFI)? - we would do this if we did not have enough information about what we needed and what is available in the marketplace. Since we have ample information  NO RFI needed

- Will this be a Master Agreement (used year after year) - YES multi year MA

- Can this be a Sole Source - probably not

- We can proceed forward as a Solicitation
need to complete the State of Work (template sent)
needs to be complete by 4/18 - contact Ken if you have any questions
submit to ATD Finance for review
when ready they will forward to CTM Central Purchasing
will have to go to Council that can take 5/6 months
once this is a published solicitation cannot make contact with any vendors

- Applying for any Grants needs to be coordinated with Dan. It's COA policy that only grants that offered more than 25k can be considered.

**Comment by moorerst** [comment]
Emailed Darren with the information regarding applying for a grant.
Response: Great! I believe the grant provides more than $25k (I recall reading something about covering 50% of the cost, which this would be a total reimbursement of $400-500k since the total cost can be about $800k-$1 million).

**Comment by moorerst** [comment]
Received the updated and formatted SOW draft from ATD Finance. There are a few outstanding questions in the SOW. Forwarded to Darren to review and provide a response to the questions. Once completed the SOW will be prepped for solicitation. Will ask ATD Finance for timeline and details on the solicitation process.

**Comment by moorerst** [comment]
Forwarded the updated SOW and vendor list to ATD Finance (Ken)
One Network
Mixon Hill
Dot Maps

**Comment by moorerst** [comment]
per stakeholder FYI we also were able to secure funding for this, I believe it's $400k. I have to double check

**Comment by moorerst** [comment]
Provided ATD Finance contact information for the 3 vendors and also provided the funding code 
Per Darren
Sure it’s 5125-2400-7783 with Object Code #5860. 

It says there’s a total of $600k, but that’s a combination of $400k for Lane Closure GIS and $200k for Bulky Items Contractors. 

We also discussed our budget with our ATD Finance. There also appears to be an additional $600k within the IT budget (same as DTS?) for Lane Closure GIS platform. I’m not sure what the FDU is within that budget. 

PR 2022-02-3784 needs to be approved by my Supervisor

**Comment by amenity** [comment]
@maccallump @moorerst - any updates on this?

**Comment by amenity** [comment]
Ken B. from Finance's 11/23 email update:

> I just spoke with CTM Purchasing; they are getting to solicit this shortly. I made sure they include all the vendors that Stephanie notified me about. I will keep you all updated on the process.

**Comment by amenity** [comment]
@moorerst is passing the torch to @TracyLinder, so I'm opening #10921 for the next steps.
