### ISSUE TITLE
Add Splash page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8805]
Create splash page for new applicants that outlines the steps of the application.

- Application Information
- Past Performance
- Attachments
- Review
- Payments

**Comment by dianamartin** [comment]
This was shown to stakeholders on 4/7, minor modifications being addressed on #8865

**Comment by patrickm02L** [comment]
> @patrickm02L should we close this and create a new one if they have changes?

Yes and Yes.
