### ISSUE TITLE
Implement "Project status" edit modal

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8806]
Implement "on-page" editing: When user clicks on field, the (single, existing) component used to view+edit that field within the project is pulled up in a modal:

![image](https://user-images.githubusercontent.com/1463708/160929075-34ffc954-6eb6-49e5-bbb5-d7c9e80eb72d.png)

![image](https://user-images.githubusercontent.com/1463708/160929003-7d1fa5d7-e3a8-4bd5-8169-0802ad8690c6.png)

"Status update" column should be min-width 300 and [max-width 360](https://user-images.githubusercontent.com/1463708/160001247-5f632c8f-578f-4872-ab4a-7a27274904ae.png) for optimal legibility

**Comment by amenity** [comment]
Notes: 
- The component will need a project ID to query the data needed to render the status updates for a particular project; not currently available in the URL

**Comment by amenity** [comment]
Other options from [this N/N article](https://www.nngroup.com/articles/data-tables/): 
- Accordions - note that [Material Table has them](https://material-table-core.com/demos/details-panel/single)
- Edit-in-place (current implementation; they recommend this only for narrow tables though not positive why)
- [Side panel](https://user-images.githubusercontent.com/1463708/161645256-f13b96aa-c72d-4f22-b9c8-f0a5aa4085d8.png) - a la Zenhub

**Comment by amenity** [comment]
In terms of what happens on save, we're leaning toward automatically closing the window upon save. 

Also, @chiaberry pointed out that the modal should have the name of the project in it.

**Comment by amenity** [comment]
@chiaberry - what size should this be?

**Comment by chiaberry** [comment]
I think 5?
