### ISSUE TITLE
Redundant payments parking data from Barton Springs

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8808]
[Spawned off of 8647.](https://github.com/cityofaustin/atd-data-tech/issues/8647)

The parking transactions for the 885 account number was showing almost exactly double of the amount that was showing up in the bank deposit report on the Controller's website.

**Comment by Charlie-Henry** [comment]
[This PR](https://github.com/cityofaustin/atd-parking-data/pull/20) explains what the issue was and how it is being addressed. I had to rebuild the Fiserv table in the parking database to get the new IDs.
