### ISSUE TITLE
[Feature] Extend work orders for MMC work

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#881]
_See also https://github.com/cityofaustin/atd-data-tech/issues/5125_

### How might we... 
- increase operational efficiency and quality service delivery?
- increase visibility into our performance metrics?
- provide insight into resource allocation?

#### Provide Work Order Process for
* Mobility Management Center Staff
Lance: I would like to discuss adding the ability to assign SRs & Work Orders to the MMC and/or MMC staff as we begin to consider Corridor Management responsibilities for our operators. Our current practice doesn’t really have us doing that even though the functionality appears to be available within Data Tracker. I’d like to discuss this potential workflow change, our motivations for it within the MMC, and the potential implications for other groups.
* Signal Engineers
Tracking of ad-hoc signal retimings and misc engineering work in the Data Tracker, as well as updates to the signal retiming dashboard to incorporate this info.
* Communications Technicians

**Comment by amenity** [comment]
Met on this today; @dianamartin is going to:
- Add high-level next-steps as a comment here
- Modify this epic to include the meetings we've had thus far

**Comment by amenity** [comment]
@dianamartin @johnclary — this is smaller than a project, right?

**Comment by amenity** [comment]
During a meeting with Lewis yesterday, he mentioned that the folks they're working with at Toole Design said that Seattle's asset management data is incredible; "all work captured in the field by technicians, updated nightly for everyone in the organization to see" ...  Does sound a lot like Data Tracker. ;) It might be worth reaching out to them and learning about their approach, @dianamartin @johnclary.

**Comment by dianamartin** [comment]
@amenity I found this [map](https://www.arcgis.com/apps/webappviewer/index.html?id=b826e5b6d4df4564a91a05604e8cd671), I have a feeling they use CityWorks

**Comment by johnclary** [comment]
nice find @dianamartin! super impressive. and I think we're making a lot of progress towards this! sloww progress.

@amenity i know some good transportation folks in Seattle. but who has the time?

**Comment by amenity** [comment]
@ChristinaTremel @dianamartin - shall we close this epic?

**Comment by dianamartin** [comment]
No, we're refactoring Signal Inspectors. We might need to circle back on this.

**Comment by ChristinaTremel** [comment]
- All of the work requested for the MMC has been completed. We will be working on signal inspector work orders, but those issues will be tracked on #15962
