### ISSUE TITLE
Enhancements from Street Banner Permits in Knack Usability Testing 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8816]
- Completed usability testing with 3 testers
- Compiled feedback from testers
- Reviewed feedback with the stakeholder and decided what changes to implement

[Final Usability Testing Feedback](https://docs.google.com/document/d/16w5dKEBGiti3AT_X8QOkRuh8TdMge_6WuunVk_Bczfw/edit#)

Next steps:
- implement changes documented in feedback document
- test
- schedule follow up meeting with stakeholder for week of 4/11
- provide training to Smart Mobility team
- prep for Go Live
- Go live May 2nd

**Comment by dianamartin** [comment]
### LPB Application
- [ ] ADD: Adding the notes on the label line v. the description line bc it’s not obvious
- [ ] Monday and Tuesdays to be bolded
- [ ] ADD: Add “Banner” in front of Date fields to be really clear it’s not event dates
- [ ] REMOVE: “Alternate Date Range” field for LPB application
- [ ] REMOVE: “If you are a first time user, please ensure your design is approved.”

**Comment by dianamartin** [comment]
@moorerst I'll probably have to sync with you sometime. Maybe tomorrow?

Also, can you test OTS process? I haven't tested it yet against the new enhancements.

**Comment by moorerst** [comment]
@dianamartin I completed testing OTS - no additional comments. I'm available until 2:30

**Comment by dianamartin** [comment]
Stephanie and I synced about her comments on the LPB form and updated the OTS forms too. Just minor changes to wording and sorting orders. Ready for stakeholder review.

**Comment by moorerst** [comment]
Enhancements from usability testing have been implemented and reviewed with the stakeholders. Closing this issue.
