### ISSUE TITLE
Update DTS Portal with HR New Hires - May 2022

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#8824]
Check HR new hires for previous month:
https://atd.knack.com/hr#manage-accounts/

Add all regular employees to DTS Portal as Viewer

**Comment by dianamartin** [comment]
@KaroEngstrom It might be because of the filter, you can adjust it to see what you need to see

**Comment by KaroEngstrom** [comment]
- [x] Checked April hires in back office; there were no records. Closing this issue and creating one for next Month
