### ISSUE TITLE
TDS Portal Info Request from John

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8837]
can y’all (1) itemize what actions a user can take on one of these pages, and (2) estimate what the impact might be if an unauthorized user took those actions?
e.g.
create a scope submission
modify a scope submission
download files associated with the submission

**Comment by ChrispinP** [comment]
Put together a Miro board with the actions currently available to customers

[TIA Customer Actions](https://miro.com/app/board/uXjVO_O5HjA=/)

**Comment by TracyLinder** [comment]
Still need to document: The impact if a user were to access/view TIA cases they should not have access to. The impact of somebody uploading docs on a case that doesn't belong to them.
