### ISSUE TITLE
AMANDA Void Permissions for ATD Finance (Waiting on Users to UAT on TEST)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8838]
ATD's finance manager Erin W has requested void permissions for all payments, not just same day. 
- Erin W
- Melissa B.

_These are special AMANDA permissions; we may need Gita's approval._

**Comment by TracyLinder** [comment]
I sent an email to Gita & Amita asking if we need approval prior to granting this access; or if ATD even has the ability to grant these permissions ourselves.

**Comment by TracyLinder** [comment]
**From Gita:**

Hi Tracy,

Hope all is well with you.

A Service Now ticket from you on their behalf should work for updating these permissions.

Thanks

Gita

**Comment by TracyLinder** [comment]
I asked @Nadin-Nader to submit a Service Request ticket for this, per Gita's instructions.

**Comment by Nadin-Nader** [comment]
SCTASK0215451

**Comment by Nadin-Nader** [comment]
Still waiting on Gita

**Comment by Nadin-Nader** [comment]
Erin and Robert are working on this together still.

**Comment by Nadin-Nader** [comment]
Created Melissa B.'s AMANDA account and set the automation to create it on PROD tonight. I also sent a TASK to CTM to create Melissa's V7 account and add her to the Active directory groups for AMANDA **SCTASK0220087**

**Comment by TracyLinder** [comment]
Still pending a followup from ATD Finance

**Comment by Nadin-Nader** [comment]
This has been completed
