### ISSUE TITLE
HR SharePoint Site Redesign Feedback Sprint Review

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8845]
- Presented the initial redesign ideas to the stakeholder
- Get rest of team to review the initial mock up
- Meet again in 2-3 weeks
- Feedback meeting scheduled for 4/19

**Comment by dianamartin** [comment]
# Diana's Notes

## Focus areas
1. Leave Management/Benefits
2. Payroll - 2nd row
3. Training & Development- 
5. Safety - 2nd row
6. Records - 2nd row

**Comment by KaroEngstrom** [comment]
- [x] Built out the 4 by 2 link grid for the focus areas (Quick Links > Film Strip) and the linked site pages (w/o content for now) per notes above. Changes in the titles and images can be implemented based on the decisions and content as we receive them. 

![image](https://user-images.githubusercontent.com/100615928/164055636-61a52435-3313-4785-9f7f-c6c73068bf7f.png)

**Comment by moorerst** [comment]
@KaroEngstrom I created a new issue for the enhancements. Can you add the information above to issue #8952. I'm going to close this issue.

**Comment by moorerst** [comment]
New issue created for the enhancements and future sprint review (5/17)
