### ISSUE TITLE
Launch and Stabilization: Markings 311 SRs

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#885]
Stay tuned into any issues that arise after 1/13 launch. This issue can be closed  2/13.

**Comment by dianamartin** [comment]
Messaged user
>how far are you guys from getting to the Markings SRs in the SMB Tracker?

User response
>I think this Friday we are going to start issuing more of them out!

**Comment by dianamartin** [comment]
I say let's keep this open til the end of the month, end of Sprint 18. Check in on 2/25.

**Comment by dianamartin** [comment]
Christina had emailed on 2/19 alerting us of issues of SRs closing in Knack, but staying in `Work In Progress` in the 311 System. 

John and I looked into this yesterday (2/20). We discovered there were some form rules in the forms that were from testing in production that were not allowing activities to be sent and also there was a rule creating new activities related to a WO, but created activities regardless if it was a 311 SR originated WO. We added a filter to prevent that and tested in Production with success.

**Comment by dianamartin** [comment]
Christina isn't in yet today 2/26. I'll ping her this afternoon to see if we can close this issue today.

**Comment by amenity** [comment]
@dianamartin - did you ever hear back from Christina?

**Comment by dianamartin** [comment]
I talked to Christina and they're starting to issue more and more markings SRs now. However, the only thing preventing us from closing this issue is the `Job Flex Notes`. John's working on this and said that hopefully, he's going to be done this week. He said it was one of his priorities.

**Comment by amenity** [comment]
Gotcha, thanks. So is that https://github.com/cityofaustin/atd-data-tech/issues/1795?

**Comment by dianamartin** [comment]
That's related to the Job flex notes, yes

**Comment by amenity** [comment]
@dianamartin - just wanted to see which of the flex note issues we need to add it to the [epic](https://github.com/cityofaustin/atd-data-tech/issues/533). There are[ quite a few](https://github.com/cityofaustin/atd-data-tech/issues?q=is%3Aissue+is%3Aopen+flex+notes) and some that don't have the Project label still look like they could be related.

**Comment by dianamartin** [comment]
@amenity I believe it's this one: #1795

**Comment by dianamartin** [comment]
@johnclary @amenity Closing this since John finished configuring the job flex notes script.

**Comment by amenity** [comment]
![image](https://user-images.githubusercontent.com/1463708/79156278-353e5580-7d98-11ea-9701-e076c8c5301c.png)
