### ISSUE TITLE
SIF - Email Resource Account when Payment is made.

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8851]
Acceptance Criteria: 

- System needs to automatically send an email to email ID of user that made Final Assessment attempt in SIF assessment process when payment on a SIF folder is made. 
- Email body: 
Subject: SIF Payment Made - 22-12345678-SIF (Folder Number)

Invoice # XYZ (Invoice Number) for $1,000,000 (Fee Amount) has been paid on 22-12345678-SIF (Folder Number).

**Comment by TracyLinder** [comment]
Email to the user who saved the Formal Collection attempt on SIF Collections process. 

Subject: SIF Payment Made - 22-12345678-SIF

Body: 
Invoice # XYZ for $1,000,000 has been paid on 22-12345678-SIF.

**Comment by Lpriya-LIT** [comment]
@TracyLinder Added Email trigger when payment is made and committed changes.
@Nadin-Nader Sent you the deployment plan, Please request for Dev promotion

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Dev, ready for Test promotion.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0219444**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified payment email in Test
