### ISSUE TITLE
SIF - Mitigations Assessed folder info

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8852]
Acceptance Criteria: 

- A new folder Info needs to be created for SIF:
-- Description: Mitigations Assessed? 
-- Type: Boolean
-- Info Group: SIF Financials 
-- Functionality: When this info is answered Yes and folder info 'Mitigation Offset?' is answered No, system needs to throw an alert message (not hard stop) when user saves folder info. 
-- Alert message text: If mitigations are assessed, please update the Mitigation Offset Info field to Yes.

**Comment by TracyLinder** [comment]
The AC looks great. Pending the alert message.

**Comment by Lpriya-LIT** [comment]
@TracyLinder Added the Mitigations Assessed? and related validation. Committed changes 
@Nadin-Nader Sent you the deployment plan , please request for Dev Promotion

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder  this has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0219432**

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader  Verified in Dev , Ready for Test promotion

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0219724**
