### ISSUE TITLE
SIF - New folder Info for PR, SP, C8, BP (Deploying to TEST)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8857]
Acceptance Criteria: 

- Two new info fields need to be added to BP, PR, SP and C8 folders

-- Description: SIF Folder RowID
-- Type: Numeric 

-- Description: SIF Required?
-- Type: Boolean

**Comment by TracyLinder** [comment]
### More Info
There are 2 new infos

1. SIF Required? 
2. SIF Folder ROW ID

**Comment by vschandramouli** [comment]
Updated ticket. Moving to On Deck and assigning Priya.

**Comment by Lpriya-LIT** [comment]
@vschandramouli Please confirm whether these 2 are mandatory infos. And what is the info group.

**Comment by TracyLinder** [comment]
@Lpriya-LIT @vschandramouli 
- Not mandatory
- Choose group 'SIF Infos' _(I might have the name wrong; the one you recently created.)_

**Comment by TracyLinder** [comment]
@Lpriya-LIT another requirement for display order. 
- SIF Required? needs to be ordered just before SIF Folder RowID

**Comment by Lpriya-LIT** [comment]
@TracyLinder The Group name is SIF Site Info

**Comment by Lpriya-LIT** [comment]
@TracyLinder @vschandramouli Please confirm that the info needs to be added in BP as well.
In title BP is included not in AC, so just wanted to confirm before committing changes

**Comment by TracyLinder** [comment]
@Lpriya-LIT yes, please add to BP

**Comment by Lpriya-LIT** [comment]
@TracyLinder Committed changes, Ready for Dev promotion

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0212008**

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/2fd77e54-ea3f-4d8c-9586-89644c313622)

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Dev, The two new info fields has been added to BP, PR, SP and C8 folders

**Comment by Nadin-Nader** [comment]
This has been sent t the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0214209**

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Test, The two new info fields has been added to BP, PR, SP and C8 folders.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan or @Nadin-Nader did this go to PROD?

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Yes went along with SIF PROD move as per Lakshmi Priya's DP.
