### ISSUE TITLE
Compile functional requirements/user stories

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#886]
Added [user stories](https://docs.google.com/spreadsheets/d/1iTiXHL8qTaq73TcS8SgriaM8qDNktiwI7AQ1bKhNEyA/edit#gid=179231394)

**Comment by dianamartin** [comment]
I've added the user stories that I picked up from the Project Kickoff notes. These will probably be GitHub Issues to help during the build.
