### ISSUE TITLE
Migrate/port VZ ingest DAG to Prefect

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8861]
The two DAG which I would like to work on to get into prefect are:
* [atd_visionzero_download_production](https://airflow.austinmobility.io/tree?dag_id=atd_visionzero_download_production)
* [atd_visionzero_hasura_import_production](https://airflow.austinmobility.io/tree?dag_id=atd_visionzero_hasura_import_production)

They are responsible for downloading the latest CSV from CRIS onto the airflow machine and then importing them into the VZ database. I am not proposing changing the mechanics of the import, just the venue that runs them (airflow => prefect). @mateoclarke, please let me know if there is some more information that is needed.

**Comment by frankhereford** [comment]
The two DAG which I would like to work on to get into prefect are:
* [atd_visionzero_download_production](https://airflow.austinmobility.io/tree?dag_id=atd_visionzero_download_production)
* [atd_visionzero_hasura_import_production](https://airflow.austinmobility.io/tree?dag_id=atd_visionzero_hasura_import_production)

They are responsible for downloading the latest CSV from CRIS onto the airflow machine and then importing them into the VZ database. I am not proposing changing the mechanics of the import, just the venue that runs them (airflow => prefect).
