### ISSUE TITLE
April 2022 Updates to SD 2023 Reporting

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#8863]

**Comment by amenity** [comment]
We'll have a meeting about this with Peggy next week, @KaroEngstrom @Charlie-Henry .

**Comment by amenity** [comment]
Oh wait... @dianamartin @johnclary - is this a dupe of #4814?

**Comment by dianamartin** [comment]
@amenity i'm not sure, but it could be..

**Comment by amenity** [comment]
Nice, thanks Charlie! Feel free to store this stuff in spreadsheet and link if that’s more legible for you.

**Comment by Charlie-Henry** [comment]
Meet with Peggy and Dan B last week to discuss M.C.3. He was the one who did the analysis last time. He said he will complete this. 

Other than M.C.3, all datasets are updated in Socrata.

Need to follow up with Cole K and Dan B about the outstanding story pages as well.

**Comment by Charlie-Henry** [comment]
We have three items that are scheduled in June that need updating, probably need a new issue for these.

Data received: 
Data | Measure ID | Contact
-- | -- | --
- [ ] | M.A.2.b | Lance B, Allyson R
- [ ] | M.A.5.b | Lance B, Allyson R
- [ ] | M.C.6.b | Nathan W

Narrative received: 
Data | Measure ID | Contact
-- | -- | --
- [ ] | M.A.2.b | Lance B, Allyson R
- [ ] | M.A.5.b | Lance B, Allyson R
- [ ] | M.C.6.b | Nathan W

**Comment by johnclary** [comment]
Nice work!!!

**Comment by patrickm02L** [comment]
Closing this and making a new epic.
