### ISSUE TITLE
Meeting - RAS Sign Data Collection

### ISSUE THREAD

**Issue by andrewshensky** [cityofaustin/atd-data-tech#8866]

**Comment by andrewshensky** [comment]
@johnclary Meeting notes below:

- Christina and Sussane provided QC notes to RAS
      RAS did intial review of notes, no major question
 
- RAS will ID all signs where possibilities of double signs may be present
      A manual review will take place to identify locations of double signs
 
- Next data delivery will be official pilot data
  
- RAS will provide timeline for final Pilot data tomorrow or early next week
 
- Next check-in is next Friday

**Comment by johnclary** [comment]
thanks!
