### ISSUE TITLE
[Feature] Update VZ change log system to capture "before" and "after" state of changes

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#8877]
The JSON stored in the change log system captures only the "before" state of a record being updated, which requires the subsequent change log entry or final state of a record be discovered to compute the actual difference in the update. 

The VZ change log system could be improved by borrowing some of the moped-like behaviors and capturing both states and optionally computing and storing the diff. 

These observations came out of various grooming meetings (@patrickm02L @mateoclarke @chiaberry @frankhereford) related to #8639 and #8746. 

Additionally, and this may need to be spun-off at the discretion of the product manager, but there was discussion also of renaming the data-conflict resolution system to use the word `conflict` instead of `change` in the database tables, components, etc.

**Comment by mateoclarke** [comment]
Definitely in favor of both these actions. Would be good to discuss and document the level of effort and preferred approach for this change so we can estimate the work before prioritizing.

**Comment by mateoclarke** [comment]
Notes from 5/11 grooming:
- Use a trigger which has access to both the “previous” and “new” state of the record, and this can be persisted through the lambda function which stores this into a JSON blob holding both the previous and new states.
- We should enhance the process to store as much metadata (who is responsible for the change, other related IDs, etc) as we have existing columns for. In essence, making not-crash changes as much like crash changes that we can.

**Comment by patrickm02L** [comment]
@frankhereford has this been completed based on the other 2 Issues that are referenced and closed?

**Comment by frankhereford** [comment]
No, this is not complete at all. Right now when we record something in the change log, we're only capturing the "before" state and not the after state. Therefore, you can't compute exactly what the change is. We just have a "backup" of data when we make a change.

**Comment by johnclary** [comment]
👍 strong agree, and we have adopted this convention in the data model's  change log triggers by following the same convention that we follow in Moped, wherein the record JSON has a `new` and `old` property. Here's the current trigger code that we're templating from to create the trigger migrations: https://github.com/cityofaustin/atd-vz-data/blob/73d924e253a78c4f608f22ac28fa58bef13e7f2e/atd-toolbox/data_model/python/sql_templates/change_log_triggers.sql#L18


This requirement is also captured in our tracking doc so it won't be missed by acceptance testing. I'm closing this issue!
