### ISSUE TITLE
Signs and Markings Server Migration

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#888]
Knack is migrating our Signs & Markings app to a new server in hopes that it resolves issues with batch deleting 311 csr flex notes. We're also hoping it resolves the recent performance issues. Both of those are flagged as dependencies in this issue.

### before
- [x] what's happening email
- [x] export list of accounts by status (inactive v active)
- [x] disable all accounts
- [x] disable knack-proxy/311 integration
- [x] disable ETL jobs

### after
- [x] reenable accounts
- [x] reenable 311 integration
- [x] reenable integration scripts
- [x] what's happening email follow up

**Comment by SurbhiBakshi** [comment]
ask Knack to notify individual emails with progress

**Comment by johnclary** [comment]
All done. Everything looks good. There were 5 new signs CSRs that were created after we revived the 311 integration.

**Comment by johnclary** [comment]
Email to Kati and Christina:

> Hi Kati and Christina—the maintenance went smoothly. Two things:
>
> We see 5 signs SRs that came through during the maintenance window, and are now available in the Signs & Markings app. That matches what I'm seeing in the CSR system. So we appear to be all good there.
>
> We're hoping that this migration improves the performance issues we've been seeing, so please let us know on Friday AM how things are going. We've also scheduled some time for our Knack consultant to investigate these issues if they persist.
