### ISSUE TITLE
[ROW] Process Cost-of-Service (COS) JV imports for March 2022

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8880]
- In Knack, rename `Approval Date` to `Import Date`
- For each file—remove rows that do not have a Journal Voucher ID. Save as CSV. 
- Import the file(s) to Knack. Only import `Journal Voucher ID` and `Fee Number`. Set the `Import Date` field to default to current date.
- Confirm that the number of imported records matches what was expected
- Let Melissa (and others cc'd) that the import is complete

**Comment by ChrispinP** [comment]
Imported Journal Voucher IDs for 1123 records (AE, ATD, AWU, CPO, PWD, & Watershed)

1117 records updated. 6 records currently missing from Knack or Fee Number does not match.

**Comment by amenity** [comment]
@ChrispinP - please figure out wuzzup with those 6 records. 🕵️‍♂️

**Comment by ChrispinP** [comment]
Matched the records, the 6 records are actually duplicates on the PWD spreadsheet.
![image](https://user-images.githubusercontent.com/67915167/163261749-b8cd6b5e-8146-4edd-a9e5-c77f57747891.png)
Therefore, all 1117 records updated and accounted for. 

Email sent to Melissa and folks. Complete, Ready to close

**Comment by johnclary** [comment]
Thanks @ChrispinP!!!

**Comment by TracyLinder** [comment]
Per Chrispin, this can be closed. We'll create a new issue for each import requested.
