### ISSUE TITLE
[Enhancement] Create Excel Macro for combining cost-of-service-files

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8882]
Develop a macro that combines the monthly COS spreadsheets into a single file.

**Comment by johnclary** [comment]
@amenity @TracyLinder FYI

**Comment by amenity** [comment]
@TracyLinder - does this need a ROW label?

**Comment by TracyLinder** [comment]
@amenity yes. I added workgroup ROW & the product label.

**Comment by TracyLinder** [comment]
We'll leave this in the backlog until we need to make the import process quicker for DTS or customer.

**Comment by TracyLinder** [comment]
We determined we won't build this.
