### ISSUE TITLE
Update status Matrix/User Role

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#889]
- [x] Create status matrix

**File Location** - `G:\ATD\ATD_GIS\02_ENT_APPLICATIONS\app_Finance_and_Purchasing_System\module_Warehouse_Inventory`

**File Name** - `warehouse_inventory_user_privileges_matrix`

**Comment by amenity** [comment]
@dianamartin - did you already do this?

**Comment by dianamartin** [comment]
@amenity I did do this, but I need to review it again bc things have changed

**Comment by johnclary** [comment]
@dianamartin would you attached the G drive file here, please? I'll update it.

**Comment by dianamartin** [comment]
@johnclary Here is the [matrix](https://github.com/cityofaustin/atd-data-tech/files/6336613/warehouse_inventory_user_privileges_matrix.xlsx)
