### ISSUE TITLE
SIF - Replace the word Assessment with Calculation in SIF Assessment Process

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8892]
Acceptance Criteria: 

- Need to replace the word 'Assessment' to 'Calculation' in SIF Assessment process 
-- Process name needs to be changed to SIF Calculation Process
-- Attempt names need to be changed to Formal Calculation, Final Calculation, Correction to Final Calculation.

**Comment by TracyLinder** [comment]
@Lpriya-LIT good job catching this. 
Yes please do make the update to the process discipline.

**Comment by Lpriya-LIT** [comment]
@TracyLinder Committed changes, Ready for Dev promotion
@Nadin-Nader Please request for Dev deployment , have sent the deployment plan.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder I have sent this over to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0211997**

**Comment by Lpriya-LIT** [comment]
![image.png](https://images.zenhubusercontent.com/611eac1954217f265acc0499/2532d94b-2392-4ad1-8d3f-dfdd82c41a1f)

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Dev, Process and Attempt names has been updated. Ready for Test Promotion along with the other cards

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT lets send this to TEST when ready

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0214216**

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Test, Process and Attempt names has been updated.
