### ISSUE TITLE
SIF - Remove Freeform Columns

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8893]
Acceptance Criteria: 

- Remove free-form columns from SIF Building Info Freeform: SIF Service Area, Council District

**Comment by Lpriya-LIT** [comment]
@TracyLinder Committed changes, Ready for Dev promotion
@Nadin-Nader Please request for Dev deployment , have sent the deployment plan.

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been deployed to TEST, please UAT

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Dev. SIF Service Area, Council District has been removed

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0214213**

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Test. SIF Service Area, Council District has been removed.
