### ISSUE TITLE
SIF - SIF Building Info Freeform Changes 

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8894]
Acceptance Criteria: 

- Any freeform columns in Yellow means update to existing column. 
- Any freeform column in Orange means new column.
- Any Strikethrough means the column needs to be removed. 

Changes to freeform are in Sheet1 tab of document below. 

https://cityofaustin-my.sharepoint.com/:x:/g/personal/tracy_linder_austintexas_gov/EXdDr5oy9wlHrmzdLkMZjCsB1uKOL8ql6hDjrUoxAR8ypw?e=Utw76U

**Comment by vschandramouli** [comment]
Re-purposing this ticket to include newly discussed changes to Freeform. Pasting old description of ticket below: 

Acceptance Criteria:

- For all freeform columns that record percentages in SIF Building Info freeform, we need a numeric column next to it that records the actual amount that corresponds to the percentage.
- Transit proximity amount column needs to be added next to Transit Proximity percentage column.
- Parking Reduction amount column needs to be added next to Parking Reduction percentage column.
- Trip Capture amount column needs to be added next to Trip Capture percentage column.
- Affordability amount column needs to be added next to Affordability percentage column.
- Total Reduction amount column needs to be added next to Total Reduction percentage column.

Outstanding questions:

- Are any of the existing columns already recording this information?

**Comment by Lpriya-LIT** [comment]
@TracyLinder @vschandramouli Committed changes, Ready for Dev Deployment.
@Nadin-Nader

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder Verified the changes in Dev, Ready for Test promotion.

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0214217**

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Test, looks good.
