### ISSUE TITLE
Create Warehouse Inventory Workflow

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#890]

**Comment by johnclary** [comment]
@dianamartin i know you're working on this. Do you have another issue you're working from?

**Comment by johnclary** [comment]
@dianamartin would you add these docs here: https://drive.google.com/drive/u/1/folders/1Dh4UF9rNXxIrZMXorhjoPl_i0ZGUGn33

**Comment by dianamartin** [comment]
@johnclary they've been added

**Comment by johnclary** [comment]
@dianamartin closing this out and making a new issue to update the workflow.
