### ISSUE TITLE
[BUG] Device Status Page Issues - April 2022

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8902]
Allyson R
AMD

Emailed this morning 4/13
>Hi John and Diana, 
 
>We’re noticing an issue with the device status page (https://data.mobility.austin.gov/device-status/) where all the CCTVs are seeming to time out. However, if we work around the device status page and access directly by the IP it works. 
> - Could y’all take a look? Thanks!

**Comment by mateoclarke** [comment]
CCTV docker service has been restarted and service restored.

AR confirms MMC is all good now:
> All looks functional on our end, thanks for the quick work y’all!
