### ISSUE TITLE
SIF Calculation Process Infos & Functionality (Ready for PROD Deployment)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8908]
Acceptance Criteria:

- Two new Process infos need to be inserted in the SIF Calculation Process. 

-- Description: SIF Building#
-- Type: AlphaNumeric

-- Description: SIF Invoice Amount 
-- Type: Numeric

- The following validations must be added to the 'Final Calculation' attempt in the SIF calculation process.

-- Pre-condition: System must not allow the user to save the attempt if the process infos SIF Building # and SIF Invoice Amount do not have a value. 
-- Post-Action: System should insert ATD - Street Impact Fee in the Fee tab with the fee amount provided in SIF Invoice Amount Process info and GL Account number chosen based on SIF District Folder Info and bill the fee. 
-- Post-Action: System must also clear the values present in the SIF Building # and SIF Invoice Amount Process Infos. 
-- Post-Action: System must add Building number provided in the SIF Building # process info to the AccountBillFeeComment column of the Fee.

**Comment by TracyLinder** [comment]
@vschandramouli please update the AC

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan will do this work,

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder  - Analysis is in Progress

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder This has been deployed to DEV, Please UAT

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Verified in Dev , Ready for Test promotion

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0217618**

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Test, works as expected

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan or @Nadin-Nader did this go to PROD?

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Yes went along with SIF PROD move as per Lakshmi Priya's DP.
