### ISSUE TITLE
SIF - Add Process 'ATD - SIF Review' Process to PR (Deploying to TEST)

### ISSUE THREAD

**Issue by vschandramouli** [cityofaustin/atd-data-tech#8916]
### Add ATD SIF Review Process to PR

1. When attempt 'Distribute formal reviews' is made on folder process Coordinating Reviews
2. And the folder info 'SIF Required?' is Yes,
3. The system should insert folder process ATD SIF Review:
    - Insert process comment "Cycle: 1" or whatever the next cylce number is 
    - Set to-start & to-end value (_using current logic_) (_matching the other formal review dates_)
    - Assign to ATD SIF Review group
    - Set process status to Open
4. Insert a folder document 'ATD SIF Comments' (_use existing comment document as template_)

----
1. When attempt 'Re-distribute' is made on folder process Coordinating Reviews
2. The system must validate the status of the previous ATD SIF Review process, if the status is 'Rejected' the system should insert a new ATD SIF Review Process. (_Follow AC for Distribute Formal Reviews attempt._

----
**ATD SIF Review Process Attempt AC:**

**Approved:** 
1. Update process status to approved
2. Close Process 

**No Review Required:**
1. Update process status to Review Not Required
2. Close Process 

**Rejected:** 

1. Verify folder doc 'ATD SIF Comments' status is 'Waiting for Reply' (_must be the correct doc, not a previously sent doc_)
2. If the document status is not "Waiting for Reply" throw error "ATD SIF Review
Update process status to Rejected
Close Process 

----
**'Create Permits' attempt on 'Coordinating Reviews Process':**
- System must validate that the most recent ATD SIF Review Process status is not 'Rejected'
- If ATD SIF Review Process is rejected, throw system error: _All Reviews not Complete_ (Same as current error for attempt.)

----
**'Volume Builder - Approved' attempt on 'Coordinating Reviews Process':**
- System must validate that the most recent ATD SIF Review Process status is not 'Rejected'
- If ATD SIF Review Process is rejected, throw system error: _All Reviews not Complete_ (Same as current error for attempt.)

----
### VBM-PR Test Case:

- Apply for VBM on portal, update SIF Required to Yes, accept web acceptance & distribute reviews. 

----
### Volume Builder Reference Doc:
[Volume Builder presentation - HBA Advocacy meeting 20190212 - revised 20200305.pdf](https://github.com/cityofaustin/atd-data-tech/files/8818687/Volume.Builder.presentation.-.HBA.Advocacy.meeting.20190212.-.revised.20200305.pdf)

**Comment by TracyLinder** [comment]
1.  Backend user saves attempt 'Create Permits' on process Coordinating Reviews' 
2. If folder info 'SIF Required?' is yes, the system should insert the ATD SIF Review Process
- IDK what the process status should be; probably open
- Assigned to ATD SIF Review (@vschandramouli please confirm name)
- The system should insert a to-end date value (we're not sure how the system decides what end date to choose. (@TracyLinder ask Mac O'Neil)
- The to-start date should be the date the process is inserted
3. The system should insert a folder document for ATD SIF Review

**Comment by TracyLinder** [comment]
### Email to PR Leads
_Mackenzie O & Christopher H._



Hello,

ATD will begin working on the PR folder next week to add SIF features. An overview of those features is below. I met with DSD's IT managers last week and got their approval to move forward with this development. I will also be sending out a separate email about user acceptance testing (UAT).

I have 2 questions for both of you:
When intake kicks off a formal distribution on the PR, how does AMANDA know the review deadline date? (AMANDA inserts the due date as the review process 'To-End Date' field.)

We'd like to look at an existing formal review process on the PR folder so we can be sure our ATD SIF Review process behaves exactly as the other formal reviews do. Is there a PR folder example you can point me to that would be a decent reference for us? 


Thank You,

Tracy Linder, Product Manager

[Data & Technology Services](https://data.mobility.austin.gov/about/)🚲 [Austin Transportation](http://www.austintexas.gov/department/transportation)

————————————————————————

**Comment by TracyLinder** [comment]
Which folder attempt is used by PR staff to approve the formal distribution? That's the attempt we need to be sure doesn't save if ATD SIF Review is 'Rejected'

**Comment by TracyLinder** [comment]
Examples: Example PR review processes for SIF - Add Process 'ATD - SIF Review' Process to PR #8916: Residential Zoning Review (50049), Commercial Zoning Review (50045)

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan please begin analysis

@vschandramouli please update AC to include the SIF folder info validation

@TracyLinder figure out which process & attempt trigger the formal distribution approval.

**Comment by TracyLinder** [comment]
I'd like to have this in DEV by May 19th if possible

**Comment by TracyLinder** [comment]
When user saves 'Create Permits' attempt on Coordinating Reviews, system should not save if ATD SIF Review is rejected.

**Comment by TracyLinder** [comment]
On ATD SIF Review, do not save Rejected attempt if the SIF Comment Doc has not been sent.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder @Nadin-Nader  - Analysis is in Progress

**Comment by TracyLinder** [comment]
UPDATED AC

1. When attempt 'Distribute formal reviews' is made on folder process Coordinating Reviews
2. And the folder info 'SIF Required?' is Yes,
3. The system should insert folder process ATD SIF Review:
    - Insert process comment "Cycle: 1" or whatever the next cylce number is 
    - Set to-start & to-end value (_using current logic_) (_matching the other formal review dates_)
    - Assign to ATD SIF Review group
    - Set process status to Open
4. Insert a folder document 'ATD SIF Comments' (_use existing comment document as template_)



----
1. When attempt 'Re-distribute' is made on folder process Coordinating Reviews
2. The system must validate the status of the previous ATD SIF Review process, if the status is 'Rejected' the system should insert a new ATD SIF Review Process. (_Follow AC for Distribute Formal Reviews attempt._


----
**ATD SIF Review Process Attempt AC:**

**Approved:** 
1. Update process status to approved
2. Close Process 

**No Review Required:**
1. Update process status to Review Not Required
2. Close Process 

**Rejected:** 

1. Verify folder doc 'ATD SIF Comments' status is 'Waiting for Reply' (_must be the correct doc, not a previously sent doc_)
2. If the document status is not "Waiting for Reply" throw error "ATD SIF Review
Update process status to approved
Close Process

**Comment by TracyLinder** [comment]
@vschandramouli please provide Sree with 2 doc templates:
- review comment doc
- Master comment doc

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader, @TracyLinder - Analysis and Development is in Progress

**Comment by TracyLinder** [comment]
**Status/Update:**
- In Progress
- Was able to create & test the folder docs

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - #8916 DEV Commit 1 submitted; However this is not a complete Commit list and few changes (document / rejected /re-distributed attempt related) are yet to be tested in DEV upon complete testing few other changes can be promoted in a different commit. 

Kindly approve and create a task id for me. 

Sent Manual Commit DP, DEV DP for the Devops components, and ATD SIF REVIEW Comments document template to DEV Promotion. 

Commit ID: [ee87bf3c08dd](http://coaamandadevops01.austintexas.gov/R3:ee87bf3c08ddcb2b67064766ea64c04fd7377105)

**Comment by TracyLinder** [comment]
I need to update AC to include UAT on VBMR applications.

**Comment by TracyLinder** [comment]
The AC is updated.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder , @vschandramouli  - Submitted DEV DP of #8916, it takes care of Volume builder folder requirement as such. Please approve and create task id for me. 

Commit ID - [4561676cc5c0](http://coaamandadevops01.austintexas.gov/R3:4561676cc5c00585ee41e657e4c6e7f806b6900b)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team To be deployed to **_DEV_** under **SCTASK0224322**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder , @vschandramouli - Tested in DEV. As per Tracy, Submitted TEST DP of #8916. Please approve and create task id for me. Please find the order to promote changes.

Commit order to promote changes from DEV to TEST
1.	Manual commit as per the DP
2.	Post the ATD-SIF Review documents template in TEST Server 
3.	Commit Order 1 – ee87bf3c08dd
4.	Commit Order 2 - 4561676cc5c0

Also had a call with Srikanth to check on overflow error, error fixed but still i was not able to generate document but he can generate the same, here is the screen shot of SIF Review inserting into master comment report for Srikanth. He asked me to send an email to CTM to check on credentials if necessary. 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/44907715/172939723-115b7ddd-bf38-496e-be83-2b5206d23340.png)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0224616**

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader , @vschandramouli - Moved to TEST and Tested in TEST Environment; all working as expected. Since I am not able to generate the Build master doc add-on taking Srikanth's help to generate the same for the folderrsn 12867528. Once I receive it, I would post it here for reference. Ready for UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder , @vschandramouli  - PROD DP Submitted. Please approve and create task id for me. 

Commit order to promote changes from TEST to PROD
1.	Manual commit as per the DP (Please make sure Gita/George updates the user permission as per TEST)
2.	Post the ATD-SIF Review documents template in PROD Server 
3.	Commit Order 1 – ee87bf3c08dd
4.	Commit Order 2 - 4561676cc5c0

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder , @vschandramouli - Created Task ID with Subha's help here is the ID -
SCTASK0226694, SCTASK0226700(manual) for your reference. Sent an email to Gita on MITCHLLA user access. Following it up with George on PROD Move.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder , @vschandramouli  -  George have created the document on PROD. The DevOps commits will go at 5:30 this afternoon as per George. George has sent an email to Gita on User permission updates for SIFREV user.
