### ISSUE TITLE
Update / deprecate AWS λ functions using Python 3.6 runtime 

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#8922]
AWS has announced that they are ending support for their python 3.6 runtime environment. Python 3.6 hit EOL at the end of last year. This AWS change will occur in two phases:

* No more patches or security updates after July 18, 2022
* No more updates or creation of python 3.6 runtime λ functions after August 17, 2022

Ideally, we should have this completed by the July deadline, but we really *must* have it done by the August cut-off. Our deployment & CI mechanisms will begin failing at that point.

`aws lambda list-functions --function-version ALL --region us-east-1 --output text --query "Functions[?Runtime=='python3.6'].FunctionArn"` returns various versions of a single service, the `atd-micromobility-api`. 

It's my understanding that this is a likely a service we can simply turn down making this a straightforward job, but it would be worth our time to do a audit of our dependencies on which python environments we have serverless functions deployed under to ensure that both this list is complete and to have an understanding of when future versions of our λ inventory will come to EOL.

Tagging both @amenity & @patrickm02L as our use of λ spans VZ, Moped, and other products.

**Comment by amenity** [comment]
Thanks, @frankhereford 🙏 Adding a future-but-not-too-distant sprint label so we make sure to pull this up before June. Can can-kick from there as necessary. 

How would I look up which of our applications rely on the Python 3.6 runtime environment?

**Comment by patrickm02L** [comment]
This is something that @mateoclarke is working on to shut MDS #8483, #8492 will take care of AWS.

**Comment by patrickm02L** [comment]
I spoke to Frank only MDS environments are affected. Closing this because it's resolved by other Issues that we have on the docket.
