### ISSUE TITLE
Bug: DS/EX - When AUP is triggered but system can't issue (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8927]
### System should not issue folder if there is a system error when payment is made online. 

When AUP is yes, but the system throws an error, the system inserts a folder comment w/ the error and should cancel AUP.
Instead the system is updating the folder status to Active even though the issue procedure wasn't called.

**Comment by TracyLinder** [comment]
Find all Active folders that don't have a folder reference number.

**Comment by TracyLinder** [comment]
<img width="680" alt="Screen Shot 2022-04-15 at 2 48 47 PM" src="https://user-images.githubusercontent.com/49930868/163626351-fbc2f22f-e3f7-4c2f-9b84-15f50e4e6284.png">

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan this is assigned to you for analysis. If you have questions please include @vschandramouli.

**Comment by TracyLinder** [comment]
**Examples sent from Paloma:**

22-015207 DS - 1609 GREENWOOD AVE - invoiced 03/15/22, Activate Upon Payment was marked, invoice paid 03/15/22. Audit shows that I adjusted something on this permit 03/30/22 @9:37 but I did not, I was in a meeting. The expiration date changed but not by me.

RESULT: I DID NOT COMPLETE PROCESS initially but I did now and then hit Issue/Approve and Issued Date is now showing 04/08/22

 

22-036774 DS - 2207 LINDELL AVE - Invoiced 03/18/22, Activate Upon Payment was marked, invoice paid 03/18/22. Audit shows that I adjusted something on this permit 03/31/22 @8:26, 8:27, 8:28 but I did not, I was not even logged in to AMANDA at that time. The expiration date changed but not by me. I do see some inspections were passed at those same times by Ernesto Gomez. See screenshot of error message found in Comment tab.

RESULT: The contractor Cutting Edge of Texas DBA Austins Cutting Edge has expired insurance. I have notified contractor to send me current insurance to update LC, then I will ‘Issue’ again to show date on active permit.

 

22-043018 DS - 1803 CEDAR AVE - Invoiced 03/29/22, all processes completed on 03/29/22. See screenshot of error message found in Comment tab.

RESULT: The contractor Cowboy Foundations and Construction, Inc has expired insurance. I have notified contractor to send me current insurance to update LC, then I will ‘Issue’ again to show date on active permit.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I see the above examples are from DS folder. does it occur only on DS folder?  or EX too?

**Comment by TracyLinder** [comment]
**Note:** This is still happening

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This is still happening on both DS and Ex folders

**Comment by Nadin-Nader** [comment]
Leaving in On Deck Pick up next

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in progress

**Comment by TracyLinder** [comment]
**Update:** We're having a hard time reproducing this issue. Vish & Tracy & Sree will meet next week to try to recreate it.

**Comment by TracyLinder** [comment]
Recreated on test on ROWID 12876476

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Submitted DEV DP of #8927; changes are committed to ONLY DS folder to test the online payment in DEV, once it is working as expected will make similar changes to EX folder as well. Kindly approve and create task id for me thankyou!


Commit ID: [98fa35720a33](http://coaamandadevops02.austintexas.gov/R5:98fa35720a33d595eee2cb6c21740029fb619af0)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this was sent to the DevOps CM Team to be deployed to DEV under SCTASK0264728

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV portal payments are not reflecting in backoffice tested for other folder types as well (RW); so, unable to test it in DEV submitted TEST DP on 11/28/2022.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @Nadin-Nader is the DEV payment reflecting a bug or has this always been the case?

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this was deployed to TEST 11/30. Please UAT on TEST

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Tested in TEST and verified with Tracy; However this is not the expected solution, as per Tracy did some more research and found that George has introduced Valid_Payment_Method check only for backoffice not for online payments. I informed George to correct it and push it to PROD. It is already in DEV & TEST; It goes to PROD by today(12/8) 5:30pm as per George. 
Identified the root cause for this issue - Why Online payments automatically turns the folder "Active" without inserting comment?
1. When AUP is ON For Residential Permits it is the ISSUE_DS which is making the permit to Active and inserting the comment and Turning AUP OFF
2. When AUP is ON for Commercial Permits it is the PAYMENT_DS which is making the permit to Active and turning AUP OFF

So, these changes were added on 01/2022 in #6255 card. So now  it is that Stake holders would want to change the business rule ?
Need **confirmation** whether I need to make changes for Both Residential & Commercial permits? that is when Online payments made and AUP is ON Comment must be inserted if Row-Contractor not found? And permit must not turn to Active Other wise can be turned to Active? AUP Off is required or not? AUP is OFF then do I need to Insert comment?

Note: I also noticed that Internet applications will not get this error because Row-contractor is mandatory when they submit the application.

**Comment by Sreelatha-BlazeKannan** [comment]
@Sreelatha-BlazeKannan, @TracyLinder , @Nadin-Nader - Confirmation on Steps 
When Online payment done,  For both Commercial & Residential permits 
                                   a) make sure When Row-Contractor not found, comment must be inserted
                                   b) No Updates to Permits folder (status/issudate/issueby)
                                   c) IF AUP is ON, Set AUP OFF

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DS Folder Updates are completed and submitted DEV DP but can be tested when it is moved to DEV.
Commit ID: 219b16b02bf7

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps Team to be deployed to DEV under **SCTASK0272322**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been deployed to DEV. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - #8927 TEST DP submitted. Kindly approve and create task id for me; In DEV I am unable to test online payments for DS folder type.
Commit ID: 219b16b02bf7

Note: Submitting 2nd commit only as Commit - 1 already in TEST. While moving to PROD need to be mindful

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been sent to the DevOps CM Team to be deployed to TEST under **SCTASK0273197**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been deployed to TEST. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST and ready for UAT in TEST for DS Folder ONLY. Once this is approved I will make changes to EX in a seperate card. 

Tested in TEST for DS Folder type 
Scenario 1 - Commercial subtype - 12877204; Online payment made, row contractor not found, AUP - ON 
<<Output >> Payment made successfully, Comment inserted saying row-contractor not found, Status not changed from Pending and AUP is still ON (Note: AUP, No changes as per #6255 for commercial)
Scenario 2 - Residential subtype - 12877540; Online payment made, row contractor not found, AUP - ON 
<<Output>> Payment made successfully, Comment inserted saying row-contractor not found, Status not changed from Internet Pending and AUP is set to OFF (as per #6255)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per Tracy’s approval, submitted PROD DP of #8927 for your reference. Kindly approve and create task id for me. 

Commit ID’s and Order 
Commit 1 - 98fa35720a33
Commit 2 - 219b16b02bf7

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0274613**

**Comment by TracyLinder** [comment]
OK to close.
