### ISSUE TITLE
[BUG] Latest Serious Injuries and Fatalities Records Missing Fields on Prod

### ISSUE THREAD

**Issue by JaceDeloney** [cityofaustin/atd-data-tech#893]
**Describe the bug**
The latest CR3 records are not showing the following fields in Prod:
-No Primary
-No Secondary
-No Death Count
-No Unit Description
-No lat/longs

We would expect that these fields would be populated per the normal ingestion process.

**URL**
Production: https://visionzero.austin.gov/editor
Staging: https://visionzero-staging.austinmobility.io/editor

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [X] Major — can only perform work using a workaround
- [ ] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Comment by JaceDeloney** [comment]
This was requested to be completed by 11/14.

**Comment by sergiogcx** [comment]
@JaceDeloney Thanks for making an issue for this problem. Not sure if this is a "bug" in the code, but definitely a problem.

Those fields get calculated and populated by a database trigger after a record is inserted or updated. After the insertion into production and staging, that data is present in staging just fine, but not in production; which meant the trigger was not enabled in production (I guess for testing).

I fixed this yesterday evening, what I did was to re-enable the trigger in production, then refresh the new records, and that seemed to fix the problem:

![Screen Shot 2019-11-08 at 9.43.29 AM.png](https://images.zenhubusercontent.com/5b7edad7290aac725aec290c/349bd01c-91ef-4ae4-9149-b48e7be3b26a)

**Comment by sergiogcx** [comment]
As a reminder, staging does not present the same problem. I also created a new issue to give you access to VZE:

https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-vz-data/425

**Comment by JaceDeloney** [comment]
Thanks Sergio. Yeah, wasn't sure of the classification that I should give to this. I saw your email about the fix this morning. This issue was created mainly for tracking purposes. 👍

**Comment by sergiogcx** [comment]
Clearing my board a bit, closing this issue.
