### ISSUE TITLE
Explore ability to generate citywide teleworking estimates

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8938]
Using Tarrytown as a test case, explore how we might produce estimates of the number of people/households who are teleworking. 

Would it be possible to enrich these estimates (or give context to them) using traffic count data, or other census data (such as population growth)?

The deliverable is a few slides which explain a potential methodology which can be reviewed by Cole K. and Anthony S.

**Comment by johnclary** [comment]
@Charlie-Henry can you estimate this work?

**Comment by Charlie-Henry** [comment]
@johnclary I think a 3 is fine for testing different ways of estimating this for the 78703 zip code. City-wide would be a bigger lift once we get some consensus around the approach

**Comment by johnclary** [comment]
@Charlie-Henry can you have this ready by 5/4 so that we can review internally? Due to Anthony on 5/6

**Comment by Charlie-Henry** [comment]
Yes this is a reasonable timeframe. Also, I've gotten access to INRIX data with Lance's help.

**Comment by Charlie-Henry** [comment]
Met with Peggy and Anthony S last week to show what I've been working on. 
- [Power BI of Austin Intersection volumes](https://app.powerbigov.us/links/9dFKzXFs7q?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&bookmarkGuid=39aa8103-c9bd-4fb9-912b-90ac7d6e5fa7)
- A visualization of ACS data for those who work from home.

Both really liked the idea of looking deeper into this as a way to answer questions about post-pandemic travel patterns.
- How much people working from home has changed our traffic?
- Do schools being open have an impact?
- What is the disparity of the changes to Austin's traffic?
- Is downtown back to normal?

I'll look into our existing INRIX data to see if it is possible to help answer some of these questions. We're meeting on Wednesday.

**Comment by patrickm02L** [comment]
@Charlie-Henry will follow Peggy and Cole to get a sense of what the next steps are.

**Comment by patrickm02L** [comment]
Meeting with Anthony S. 8/1/22.

**Comment by patrickm02L** [comment]
Charlie contacted a group in Maryland to try to get an API for teleworking data. We aren't paying enough to be eligible for the API. 

Lance Bower is hosting a meeting with INRIX about our intersection volume data and answer questions about work-form-home data.

**Comment by patrickm02L** [comment]
Charlie will work with Shelby S. to help get access to the data they need. Meeting scheduled for 8/31/22.

**Comment by patrickm02L** [comment]
@maccallump is working on setting up a meeting with Richard so they can present their findings.

**Comment by patrickm02L** [comment]
Sent a Slack reminder to Peggy during our Planning meeting 9/22/22.

**Comment by Charlie-Henry** [comment]
I'll be giving this similar presentation to Annie A of the Austin Downtown Alliance on Wednesday. I'm in the process of updating our data with the September numbers from INRIX.

**Comment by maccallump** [comment]
@Charlie-Henry and @johnclary is this still a viable approach to estimate remote work?

**Comment by amenity** [comment]
Closing this and will need to discuss next steps, cc/ @maccallump
