### ISSUE TITLE
Banners Permits and Purchasing in Knack Soft Launch

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8939]
As of  Monday 4/18 the team began using the new application.
Meeting 4/19 

- How is it going 
- Make sure Joseph is familiar with processing the work orders

**Comment by moorerst** [comment]
Team processed several new applications in the system a few questions came up:

- Can I edit an existing comment - no you can copy/paste the old comment and add as a new comment with updated information

-  How can Joseph see what work he may have in the future? - Joseph uses the Technician Schedule and Calendar feature. This works fine for him

-  Sometimes the status Pending Delivery does not get changed which is a trigger for Joseph's work orders - they will work on setting up a tablet that can be used to update the Delivery status when a Banner is delivered. 

Action Item

- [ ]  Sometimes Banners are delivered by the vendor who produced it and they don't know the event name or date - Add wording to the portal Home Page and to the confirmation email "Banner Delivery package must be labeled with the Event Name and Event Date" 
- [ ] SMB team will work on organizing the area where the Banners are stored and update the status of those Banner request in the application. 

Possible Future enhancement 
At some point after there is a organized system in place for storing the Banners maybe we can include a bin # on the record so they know where a Banner is located.

Next Steps:

- meet with Smart Mobility team provide them a update on what is happening with the new application

- Determine if they have access to the mailbox

- Provide them with the Help Guide

- Review the workflow

- Provide access to a test system so they can become familiar with the system

**Comment by dianamartin** [comment]
Started copying new Street Banner test environment 10:23 am

**Comment by dianamartin** [comment]
Set up Banner Test environment for Smart Mobility and send out lengthy email on 4/20
>This is the email everyone’s been waiting for, I kid..

>I checked to see if the CTM request was processed, and it seemed to be, so I’d like for the folks at Smart Mobility to try to add the resource account to their emails. I’ve added links below to help.

### ATXBanners – email inbox
>I checked that ticket: REQ0106776 it was closed and said this was completed. 
•	Add the inbox to your Outlook environment [Desktop]or [Web]
•	Add [atxstreetbanners] email
** Luke is going to submit a new CTM service desk ticket to have Nicholas added 

### Short-hand
>These are the common shorthand used to differentiate the two banner programs (internally), you’ll see how useful these are once you having to start typing out “lamppost banner” and “over-the-street banners” repeatedly 😊
•	LPB: lamppost banners
•	OTS: over-the-street banners

### Test Environment
>I’ve created a Test Environment for the testing. We can set up a quick tour of it for the SMO Team. Let us know your what your availability is, and we can set something up. Once we set-up the meeting we can show you the Testing Script so you can try it out for yourselves. 
>- I’ve added accounts for you three
>- To log into the Test Environment, click the “home” link below
>  - Click “Non-COA Sign-in”
>  - And reset the password, you can reset your password to something you’ll remember. In the Production application, you click the big “Sign-In” button instead. 

Test Environment 
>- Link 1: Primary where Reviewers go
>- Link 2: Customer view where they initially start or the “Get Started”

>These are the written help guides with screen shots  - these might be influx as we might need to update things depending on if there are system changes.
Help Guides
Street Banner Portal Knack Application | Help Guides

### Street Banner Resources
Street Banners page (external – austintexas.gov)
[https://www.austintexas.gov/page/street-banners](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.austintexas.gov%2Fpage%2Fstreet-banners&data=05%7C01%7CDiana.Martin%40austintexas.gov%7C8a10eeea191d4902750108da23bf4b9c%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637861601766913020%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n7K8%2BIf%2Fy3kO66AZfHQEA0s82%2F%2F3SaPl5OtgJ8%2FqLmE%3D&reserved=0)
LPB: [https://www.austintexas.gov/page/lamppost-banners](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.austintexas.gov%2Fpage%2Flamppost-banners&data=05%7C01%7CDiana.Martin%40austintexas.gov%7C8a10eeea191d4902750108da23bf4b9c%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637861601766913020%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xJNW5iUsVRPydTdB0fB9BIIbzf7Y3jPw2gaBqKSkk2E%3D&reserved=0)
OTS: [https://www.austintexas.gov/page/over-street-banners](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.austintexas.gov%2Fpage%2Fover-street-banners&data=05%7C01%7CDiana.Martin%40austintexas.gov%7C8a10eeea191d4902750108da23bf4b9c%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637861601766913020%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=duXDLDZ1LWIZcQ%2Bm9%2BWgx6k3fNVeFwGDtWr85lWzMVE%3D&reserved=0)

Web Map Applications
>- LPB Customer Facing
>- Black background, whole district walk-through
>- LPB Reference Map embedded in App
>- White background, less content, more pertinent information
>- OTS Customer Facing:
>-  Black background
>- OTS Reference Map embedded in App:
>- White background, less content, more pertinent information

>Lauren will cover the AMANDA payment aspect at some point. Let me know if you have any questions about onboarding and training materials.

**Comment by dianamartin** [comment]
@moorerst when do we close this one?
