### ISSUE TITLE
Migrate parking ETLs to prefect prod

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8945]

**Comment by johnclary** [comment]
@Charlie-Henry discuss this with the rest of the devs and estimate it

**Comment by Charlie-Henry** [comment]
I am having problems with moving one of my more straight forward flows into `production`. @chiaberry helped do some investigation into finding why it keeps referencing `staging`. Maybe we break from the template we have, we will have to discuss at a future Prefect Sync. 

https://github.com/cityofaustin/atd-prefect/pull/12#issuecomment-1131902367

**Comment by patrickm02L** [comment]
Charlie will wrap up by merge, and hope everything goes well by 6/17.

**Comment by Charlie-Henry** [comment]
Looks like it ran with issues 🍾 . I was noticing that sometimes it was failing on Fridays/sundays for some reason, added some logging if this happens again will open a separate issue 👍
