### ISSUE TITLE
Parking spatial data

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8946]

**Comment by amenity** [comment]
@Charlie-Henry @johnclary - I have a hunch this is old?

**Comment by Charlie-Henry** [comment]
This is lacking detail but I think so. We created the schema for them but we are sadly blocked to release the parking dataset due to them not implementing some system that would maintain their spatial data.

**Comment by amenity** [comment]
Thanks! Let's go ahead and open a more specific issue when the project picks up again.
