### ISSUE TITLE
HR SharePoint Redesign Enhancements

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8952]
Based on feedback from sprint review they would like the design to include the following focus areas:

- Leave Management/Benefits
- Payroll/Compensation- 2nd row
- Training & Development
- Safety - 2nd row
- Records - 2nd row
- Employee Relations - ????

HR will meet with their team to discuss the content for each area.
For now they just want the proposed design in place to review with staff.

**Comment by KaroEngstrom** [comment]
4/19/22 per HR team's request 

- [x] Built out the 4 by 2 link grid for the focus areas (Quick Links > Film Strip) and the linked site pages (w/o content for now) per notes above. Changes in the titles and images can be implemented based on the decisions and content as we receive them.

![image](https://user-images.githubusercontent.com/100615928/164069832-78e9b16d-0bc4-4bb7-badd-d9ebb056abbe.png)

**Comment by amenity** [comment]
Closing this since the enhancements have been implemented and there's a follow up issue for next steps. 🙌 cc/ @moorerst
