### ISSUE TITLE
[Update Data] Open Data Portal in Open Data Inventory

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#8957]
- Reference the OpenData spreadsheet that Karo compiled in "OpenData" folder in Google Drive
- Update Open Data Inventory 
- Check/Update: Owner, Data refresh and status

**Comment by dianamartin** [comment]
Karo and I synced to remember which spreadsheet we used to QC the datasets and we mapped out the relationships in [Miro ](https://miro.com/app/board/uXjVO6vKjok=/)to confirm where the datasets lived and what we needed to update. 

# Steps
- Update existing dataset records in Opendata Inventory 
  - [ ] Confirm data owner?
  - [ ] Descriptions
  - [ ] Hosted
- Added new dataset records

**Comment by KaroEngstrom** [comment]
F 7/8/22 
I'd like to pick this up in mid-August as July is booked

**Comment by KaroEngstrom** [comment]
Duplicate of #10750 
Closing this one.
