### ISSUE TITLE
Fatality Review Board Recommendations

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8960]
For crash records with fatalities, staff would like to add notes to the crash page to reflect the Fatality Review Board recommendations, as well as Coordinating Partner and Status of the recommendations. 

**UI considerations**
- View for non-editing roles
- View for editing roles
- Behavior when the edit button is activated
  - Drop down menus with list of Partners & Status
  - View for an editable text box

**Technical considerations**
- New table that includes
  - Recommendation ID, Project ID, Coordinating Partner (multi-select), Status, Text
  - Coordinating Partner and Status are discrete lists; new lookup tables will need to be created.
- Enabling edit mode for Editor role and higher
- Recommendation component only appears when fatality is recorded

**Comment by patrickm02L** [comment]
Non-editable Recommendations component in relation to the rest of the components on the page.
![Recommendations - Not editable](https://user-images.githubusercontent.com/5566727/164080415-5b15a74a-2d4b-450a-8133-100ddaf4458e.png)

**Comment by patrickm02L** [comment]
**View with Editor Permissions**

![Recommendations - Editor view](https://user-images.githubusercontent.com/5566727/164080555-d1044c12-a41f-4311-8881-80c4631dd818.png)

**Edit mode**

![Recommendations - Edit mode](https://user-images.githubusercontent.com/5566727/164080685-ff42df62-45a6-496b-a609-9a4e7da91633.png)

**Editing Coordinating Partner**

![Recommendations - Edit Coordination Partner](https://user-images.githubusercontent.com/5566727/164080812-2ab4ae43-fe2f-4d3a-b641-39750898c3d3.png)

**Editing Status**

![Recommendations - Edit Status](https://user-images.githubusercontent.com/5566727/164080857-0c2de47b-4fce-449d-8328-eed01c83ec08.png)

**Comment by patrickm02L** [comment]
We can use the work that Chia's doing in Moped to help with Multi-select for coordinating partners, as well as a JSON blob.

**Comment by mateoclarke** [comment]
This is still on my plate to break down into smaller tasks but going to wait until we get further along with https://github.com/cityofaustin/atd-data-tech/issues/9297

**Comment by patrickm02L** [comment]
Feedback from VZ Sprint Review 8/2/22. 
- Only allow Admin level permissions to view the Recommendations section. Make sure Lewis, Xavier, and Joel have this level of permission.
- Create an Issue to migrate Recommendations and notes from internal spreadsheet to the VZE

**Comment by mateoclarke** [comment]
I've unassigned myself from this Epic and will assign @chiaberry for visibility. There's one last issue to migrate existing data from a csv into Postgres that should be ready to assign in an upcoming sprint.

**Comment by patrickm02L** [comment]
Very proud of this work, and all who contributed!
