### ISSUE TITLE
Comments and Review

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8964]
Staff would like a way to comment on each record and aggregate them into one email that will be sent through the app. Create a mock up of what this will look like to show on April 22, 2022. 

Similar to TDS commenting process. Use this as a reference for the Online App comments.

**Comment by dianamartin** [comment]
I apparently started doing this the last time I was working on SMRT, yay me!

I'm just adding a few more options for the user so we can talk about it on Friday.

**Comment by dianamartin** [comment]
Sync'd with Patrick, we decided that Option 2 provided no real value. The "commenting" function of Option 1 is great for internal reviewer comments. Option 3 is good for providing "Attachment Comments" so that the applicant can see them. We've outlined a process and will need to scope a little more about the details of the SMS review. We'll talk to the stakeholders on Friday about it.

**Comment by dianamartin** [comment]
Need users to decide on if they want to use "Feedback Comments" or "Add Reviewer Comment"
![image](https://user-images.githubusercontent.com/21112975/166558579-b0f8a1bf-e7aa-4351-9117-3891c8d74da8.png)

## OPTION 1: Feedback Comments
### 1. Sends default email to stakeholder
![image](https://user-images.githubusercontent.com/21112975/166558807-ae3acadf-0c7c-470e-bc99-5917245ec3a3.png)
### 2. Auto creates "Reviewer Comments" record
![image](https://user-images.githubusercontent.com/21112975/166559069-75783e6f-b09d-478b-b487-1310e49f07c5.png)

## OPTION 2: Add Reviewer Comment
### 1. Can send email to stakeholder (Optional)
Reviewer has the ability to email stakeholder (Applicant Email) when creating a comment
- [ ] Need to configure email
![image](https://user-images.githubusercontent.com/21112975/166559756-831fc7fc-f733-49ab-9937-258f87d3bc4d.png)
### 2. Creates "Reviewer Comments" record
Reviewer can create an comment that is not shown to provider, kept with application records only
![image](https://user-images.githubusercontent.com/21112975/166560113-63275e02-8030-410e-b40e-028aec2df8a2.png)

**Comment by dianamartin** [comment]
Will show stakeholders on 5/6

**Comment by dianamartin** [comment]
Showed stakeholder on 5/13, our original meeting on 5/6 was rescheduled. They seemed to understand the differences between the commenting functions but didn't necessarily say one was more useful than the other. I think they want both functionalities kept.
