### ISSUE TITLE
Develop new standard map icons for DTS geo products

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#8972]
**Colors**
- In https://github.com/cityofaustin/atd-data-tech/issues/4761, asked the user for information 

**Bike icons**
- Meet review what we have existing, and identify what might be missing
- Create/modify new SVGs as needed
- Test them on online bike map

For other discussion:
https://github.com/cityofaustin/atd-data-tech/issues/8903

**Comment by johnclary** [comment]
@alan-deanda will schedule a meeting with Andrew, Noelle, and Sophia. @amenity  as optional.

**Comment by amenity** [comment]
@amenity - schedule something with Sophia and Noelle.

**Comment by amenity** [comment]
@alan-deanda @andrewshensky ... Sophia's last day of work is 6/1... should we backlog this until her position is filled, or meet w/ Noelle sooner?

**Comment by andrewshensky** [comment]
@amenity We had a related request come in this week regarding color blind friendly colors for the online bike map. Alan and I discussed this on Thursday, I'm thinking maybe we create an epic where we can track all symbology standardization related work. Then this issue can be backlogged but housed in an ongoing epic.

**Comment by amenity** [comment]
# Ideas 
- Do Discovery Day research on standards/techniques that we could adopt
- Consider offering alternate vector tiles that the user could choose from
- Get input from PIO - especially on bike icons

**Comment by alan-deanda** [comment]
I have met with PIO, and we agreed on adopting their icons for the 2023 version of the bike map.
