### ISSUE TITLE
AFD & EMS ETL change requests

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#8976]
After asking XA to review the tables that have been implemented in both production & staging VZD, he provided changes requests.

Update 5/18/22: After discussing in our monthly meeting, we've split out the change requests into separate issues:
- https://github.com/cityofaustin/atd-data-tech/issues/9075
- https://github.com/cityofaustin/atd-data-tech/issues/9076
- https://github.com/cityofaustin/atd-data-tech/issues/9077
- https://github.com/cityofaustin/atd-data-tech/issues/9201

**Comment by patrickm02L** [comment]
Talked about this in VZ Sprint Review 5/3/22. 
@mateoclarke, @frankhereford, Xavier to schedule conversation about “transformations”
Refer to VZ Sprint video from ________.
