### ISSUE TITLE
Clarify Locations options with Jen and Lewis

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#898]
Locations Lewis is currently using for his Excel assignments: 

Jen's location listing is 1700+ single addresses 

Issues:
- Officers prefer location to be specified as blocks between two street addresses, e.g. "2222 — 360-Mopac"
- Lewis chooses three different locations for each shift, not user-friendly to choose from ☝️ 

Options:
- Add column to Jen's locations "Description" with officer-friendly description to each one
    - A lot of work for Lewis, but maybe not so bad if he adds in as he uses them 
- Agree on a subset of Jen's list to use in VZA enforcement
    - Perhaps associate sector or officer-friendly location with a collection of Jen's locations

**Comment by SurbhiBakshi** [comment]
![Schools.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/b37d8698-cd78-4101-a084-bd33bf6c7294)

**Comment by SurbhiBakshi** [comment]
![Signal_Intersections.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/572ebe0e-bb2c-4ad0-8578-3002ecdf713a)

**Comment by amenity** [comment]
After #929 we decided to witch back to Lewis' list: 

Using Jen's list is not feasible at this point

-   [Difficult UI](https://drive.google.com/open?id=18n98XyZKpUjc-DfCYmcSDfNF55bBjpBe) for Lewis/Shift Creator

-   Not as user-friendly for officers (they prefer a street with limits at specified cross-streets)

-   [Reporting is going to need a lot of aggregation to be meaningful](https://drive.google.com/open?id=1emvJvFXzDXxUJcrF1Q2rmBphPywP-t7m)

[Lewis' existing Location list](https://drive.google.com/open?id=1snfZghyCnxHInt0o0H2msoxPFFdGUHBY) is refined, based on High-Injury Network

Later on, will connect the two datasets. #955
