### ISSUE TITLE
CR3 Data Quality - April 2022

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#8981]
Tracking recent CR3 Issues for April.

**Comment by xavierapostol** [comment]
Here are some examples of records that have a non-working `CR3 Download` button:
> - https://visionzero.austin.gov/editor/#/crashes/18838706
> - https://visionzero.austin.gov/editor/#/crashes/18864317
> - https://visionzero.austin.gov/editor/#/crashes/18838701
> - https://visionzero.austin.gov/editor/#/crashes/18840761
> - https://visionzero.austin.gov/editor/#/crashes/18857822

**Comment by xavierapostol** [comment]
Is this the same as #8980 ?

**Comment by patrickm02L** [comment]
See #10158 for future Issues like these.
