### ISSUE TITLE
BUG: ROW Deficiency Report (50514) is throwing a "Page Area to Large" error on PROD (Waiting on Blake)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#8984]
Blake B. reported that the ROW Deficiency Report (50514) is throwing a "Page Area to Large" error on PROD This only seems to be happening on this permit ( 21-202490-EX). 

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/be1e37e9-b30f-490b-b99a-2b40d70e5b90)

![image.png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/6ff72ed0-54ea-4533-b8d4-7550fcc16ac0)

**Comment by Nadin-Nader** [comment]
I have spoken to Anu and she found that the issue could be with the Folder description. She asked that i have Bake change the name to something shorter. I sent an email to Blake. Waiting on his response:

> From: Nader, Nadin 
> Sent: Wednesday, April 27, 2022 1:42 PM
> To: Barnard, Blake <Blake.Barnard@austintexas.gov>
> Cc: Linder, Tracy <Tracy.Linder@austintexas.gov>; Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov>
> Subject: Page Area too Large error for EX Card 8984
> Importance: High
> 
> Hi Blake,
> 
> Hope you are doing well. I m reaching out regarding the error you are getting when printing the ROW Deficiency report for permit ( 21-202490-EX). I have received word from CTM as to what could be causing the issue with the permit report. 
> 
> The issue they found was that the Folder Description was too long compared to others. They are asking if there is a way it can be changed to something shorter. Please let me know if changing the Folder description helps run the permit.
> 
> Please let me know the outcome.
> 
> Respectfully,
> 
> Nadin A. Nader (He/Him/His)
> Product Delivery Manager
>

**Comment by TracyLinder** [comment]
@Nadin-Nader we need to ask Blake for the correct folder number. Paloma says this number is pulling up an electrical permit.

**Comment by Nadin-Nader** [comment]
3rd time following up:

I received a message from Blake yesterday saying to reach out to him today as he was not able to chat due to the City Department event.
I reached out via teams chat and im still waiting on a response:

Message:
[12:01 PM] Nader, Nadin

> Hi Blake. Hey when you get a chance before 130pm, can we talk about  the error you were getting "Page area too Large"? CTM nor we could find it in the system anymore but were able to find the issue. The issue was that the folder description was too long. CTM asked if you could edit the Folder description to make it shorter. Please let us know if it is still happening. If so we will need the folder information. and will also need to know if it is happening on other folders or just the one.

**Comment by Nadin-Nader** [comment]
Spoke to Blake this morning and he informed me that this has not happened again to any other folder and that he could not find the permit. I asked if we could close this out since it hit a dead end. He said yes to closing. See chat below:

> [10:03 AM] Barnard, Blake
> I have not be told it has happened again. It just seem to happen on that 1 permit. I will check for the permit number and send to you.
> 
> [10:20 AM] Barnard, Blake
> Nader, I can not find the permit. I will continue to check but, I have not heard of any further issues. 
> 
> [10:21 AM] Nader, Nadin
> ok cool. Is it ok if we close the card?
> 
> [10:22 AM] Barnard, Blake
> Yep.. Close it. I will look for the permit. Thank you.
> 
> 
>
