### ISSUE TITLE
HR Digital SSPR Discovery Meeting

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#8995]
Meet with stakeholder to get a better understanding of what the goals are.

Request:
Looking to move the SSPR process over to the HR Knack System for all management to use. issue #8933

What are other department doing? (PWD, CTM, etc.)
github issue #8992

Meeting scheduled with stakeholder 5/16

**Comment by dianamartin** [comment]
# Diana's Notes - 5/16
## SSPR Goals
- Form with process
- Workflow: supervisor complete, mid-year, year-end

ATD Accountability on SSPRs
Promised to management 
Process move to electronic
- Planning Document
- Mid-Year
- Year-End
- to exist throughout the course of the year
- Want edit functionality

## HR to have SSPR information
- SSPR Plan document

## Tracking SSPRs
- Debbie W. having to track it
- SSPR Reporting

## Functionality
- Attaching kudos, additional information
- Reporting: Querying their individual priorities

## Confidentiality
Division Manager & Supervisor
HR Admin: select group of people 
Employee should not edit the SPPRs
- Memo of Concern? 
- Performance Improvement Plan

Reminder notification to complete the form
- Planning, Mid-Year, Year-End
  - Nathan send out 30 days out of SSPR dates
  - Reminder to supervisors - Nice to Have
- 30, 90, 120 Surveys - additional

Supervisor promotes to the other division
- They need to have personnel files if they leave the department

- HR SSPR Reporting
- Ratings by Employee by year
- Export the document 

Training & Help Guides
- Add to Leadership Academy

- Add Safety Component

**Comment by dianamartin** [comment]
## How do we deal with these scenarios?
- New Manager
- New Division Manager

## Delegating SSPRs
How many years kept in Knack? Records retention.

**Comment by dianamartin** [comment]
# DEV FUNCTIONALTY
1. Copying a SSPR and their Priorities table - removing ratings comments
2. Account - Recognize division and filter table division

**Comment by moorerst** [comment]
Created new issues for the features identified during the discovery meting.

**Comment by dianamartin** [comment]
Closing, Stephanie created new features for new tasks.
