### ISSUE TITLE
Feature: ROW Emergency Permit Fee (On PROD🎉🎉)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#8996]
**Email from Ryan M. 4/25/22:**

The City Council will be considering an item on May 5 that will allow us to begin charging emergency permit application fees. If passed, we would want to begin assessing this fee ASAP. It already exists in the fee schedule and I think the work was done in AMANDA, but we just need to enable it. What would the timeline look like to enable if it’s passed on 5/5?

**Acceptance Criteria** 

- **RW TURP Emergency Permit fee -  Fee amount - 95$ -- GL A/C: 5125 2400 9100 4087** 

-- System should insert the TURP New Permit fee in an RW folder if the work type is NOT Franchised Utility and 'Emergency' info is NO (This feature may already exist) 

-- System should insert the TURP Emergency Permit fee in an RW folder if the work type is NOT Franchised Utility and 'Emergency' info is YES (This is a new feature) 

-- TURP Emergency Permit Fee should also be available to add through the Insert and Run fee procedure. 

- EX Excavation Application fee - Emergency - Fee amount - 95$ -- GL A/C: 5125 2400 9100 4057** 

-- System should insert Excavation new permit fee in the EX folder if subtype is not franchised utility and Info fields 'Emergency' and 'Secondary' are 'NO' (This feature may already exist)

-- System should insert Excavation application fee - Secondary in the EX folder if subtype is not franchised utility and Info fields 'Emergency' is answered 'NO' and 'Secondary' is answered 'YES' (This feature may already exist)

-- System should insert Excavation application fee - Emergency in the EX folder if subtype is not franchised utility and Info fields 'Emergency' is answered 'YES' and 'Secondary' is answered 'YES' (This is a new feature)

-- The Excavation Application Fee - Emergency should also be available to insert through the Insert and Run Fee procedure.

**Comment by TracyLinder** [comment]
**My Response:**

We have done the work in AMANDA V6 for the emergency permit fee and we commented it out so we could use it in the future. I need to speak with my team to get a better understanding of the considerations that could affect the delivery timeline, but my estimate is **5 weeks** from start to PROD.

**Comment by TracyLinder** [comment]
**Questions for Sree:**
1. What level of effort & time this will take to get to PROD.
2. Is this already in PROD and commented out?
3. Please do an analysis to determine if the enhancements done since August will cause any code conflict.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I have reviewed the card. Here are my findings
RW - Commented the code to add emergency fee Insert & Run and Commented while creating the new folder based on the Emergency info value 
EX - Commented the code to add emergency fee Insert & Run and Commented the code while creating a new folder when Emergency is Yes (No fees will be added) 
To enable this in both EX and RW - Development and Testing 3 to 4 days then DEV OPS process. Kindly let me know if you need any other information.

**Comment by TracyLinder** [comment]
**Email to Stakeholders:**

Howdy Everyone,

Thanks for your patience on this while i synced with our developers. Implementing the emergency permit fees on both Excavation & TURP permits will take about 5 weeks.

We will start working on this by the end of the week.

Thanks,

Tracy Linder, Product Manager

**Comment by TracyLinder** [comment]
@Nadin-Nader we need to pull this on deck ASAP. We should probably write good AC first.

**Comment by TracyLinder** [comment]
@Nadin-Nader we need to pull this on deck ASAP. We should probably write good AC first.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Can we make AC like below? Please do let me know if any corections required.

**RW TURP Emergency Permit fee -  Fee amount - 95$** 

>> Insert & Run for Emergency Permit Fee

>> If RW work type not Franchised Utility and Emergency info is NO then TURP NEW PERMIT FEE -- (Already programmed)

>> If RW work type not Franchised Utility and If Emergency is YES then TURP EMERGENCY PERMIT FEE - (New Requirement to be developed) 

**EX Excavation Application fee - Emergency - Fee amount - 95$** 

>> Insert & Run for Excavation Application Fee - Emergency

>> If EX subtype is not franchised utility and Emergency & Secondary are 'NO' then Excavation permit fee-new -- (Already programmed)

>> If EX subtype is not franchised utility and Emergency = No & Secondary = 'Yes' then Excavation Application fee- Secondary -- (Already Programmed)

>> If EX subtype is not franchised utility and Emergency = Yes & Secondary are 'Yes' then Excavation Application fee- Emergency -- (New Requirement to be developed)

**Comment by TracyLinder** [comment]
**Email from Ryan M:**

Good afternoon,

The City Council approved this item and it can be implemented. Thank you.

**Comment by TracyLinder** [comment]
@vschandramouli please update AC and notify Sree when she can begin work.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - #8996 DEV DP submitted. Kindly approve and Create task id for same.

Commit ID: [8e919d61374d](http://coaamandadevops01.austintexas.gov/R3:8e919d61374dbaac26c87a334a2f42bfed8bab18)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0218502**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in DEV environment; All working as expected. Submitted TEST DP today. Kindly approve and Create a task id for the same.

Commit ID: [8e919d61374d](http://coaamandadevops01.austintexas.gov/R3:8e919d61374dbaac26c87a334a2f42bfed8bab18)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0219454**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this has been deployed to DEV

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST Environment and ready for UAT

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0219719**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to PROD. I will let the stakeholders know

**Comment by TracyLinder** [comment]
### Update - Fee doesn't begin until 6/1

**Email from Ryan M:**
FYI, the emergency permit fees will be assessed starting June 1.
Tracy, I assume you already aware since this originated with Peggy.



**My response:**
Hi Ryan,

I must have missed the memo as I was not aware. This went to PROD yesterday. I'll speak with Nate about getting it rolled back until 6/1.

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been resent to the DevOps CM Team to be deployed to **_PROD_** under **SCTASK0221854**

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Emergency fee charged for EX & RW-TURP in PROD.

![image](https://user-images.githubusercontent.com/44907715/171466365-6a863697-c883-4c59-8389-23169a1c77fe.png)


![image](https://user-images.githubusercontent.com/44907715/171466651-00993533-7c65-4589-8ee3-6b70e1b8b266.png)

**Comment by Nadin-Nader** [comment]
Closing:

> [Wednesday 2:31 PM] Amayo-Ryan, Paloma
>     #8996 Looked good to me!  And I saw an email where Tracy said she tested it as well!
