### ISSUE TITLE
Project: AMANDA FY23 Fee Updates

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#8999]
Implementation of ATD FY23 fee schedule updates for fees maintained in the [AMANDA System](https://github.com/cityofaustin/atd-data-tech/issues/4790)

## Background

The city's yearly [Budgeting Process](https://financeonline.austintexas.gov/afo/afo_content.cfm?s=1&p=57), Department Fee schedules, Fee Logic/Workflow and Fee amounts have to be updated in AMANDA, if it has an applicable change, by September 30, 2022 and Go live date of October 01, 2022. With this being a large public facing project, it will require a Project Based approach to be delivered on time and to specs.

## Scope & Deliverables

_**In Scope:**_
-  Updating the AMANDA Budgeting Processes, Department Fee schedules, Fee Logic/Workflow and Fee amounts have to be updated in AMANDA, allowing staff to be able to Process approved FY23 fees in AMANDA.
- Budgeting Process, Department Fee schedules, Fee Logic/Workflow and Fee amounts have to be updated in AMANDA, if it has an applicable change, by September 30, 2022 and Go live on October 01, 2022.

_**Out of Scope:**_
- Fees on the fee schedule that are not, or should not be maintained in AMANDA are out of scope. 
- Any non-AMANDA solutions are also out of scope.

_**Constraints/RoadBlocks:**_
    - CTM's V7 Upgrade Project
    - Payment connections between AMANDA and CityBase
    - Testing payments on V7
    - Changes to FY22 fees must go live on Oct1 2022 only and cannot impact current PROD environment and its fees

## Desired Outcomes
-  All updated AMANDA Budgeting Processes, Department Fee schedules, Fee Logic/Workflow and Fee amounts will be UATd and verified properly prior to and after implementation.
- 2-3 week stabilization period for any changes
- All new fees and their changes are implemented properly and working on Oct 01, 2022
Impact this project can have, success metrics

## Timebox

All changes to fees must and will be implemented by September 30th, 2022 and go Live on October 01, 2022

**_Components:_**

Scoping: April - May
Technical requirements and documentation: May - June
System development: June - July
User acceptance testing: July - August
Training and implementation: September

## Concepts and references

- OSE FY23 Fees are [here](https://docs.google.com/spreadsheets/d/1sZchwEo_qq54bh4F9nnEuXBukXaktoJm/edit?usp=sharing&ouid=114042363287535953312&rtpof=true&sd=true)
---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by Nadin-Nader** [comment]
Email from Nathan Aubert (**_TDS_**):

> From: Aubert, Nathan <Nathan.Aubert@austintexas.gov> 
> Sent: Monday, April 11, 2022 10:55 AM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Cc: Hutchens, Amber <Amber.Hutchens@austintexas.gov>; Linder, Tracy <Tracy.Linder@austintexas.gov>
> Subject: RE: FY23 Fee Season has Arrived
> 
> Hey Nadin,
> 
> TDS will have fee updates as we’ve increased some and decreased others. We have not quite finalized with Peggy and team what those look like but I’ll reach out as soon as we have.
> 
> Thanks,
> 
> 
>  	Nate Aubert, P.E.
> Transportation Development Services Division │ 
> Supervising Engineer &
> Acting Lead Development Engineer – North Area │
> Austin Transportation Department │
> Direct (512) 974-7136
>              
>

**Comment by amenity** [comment]
@TracyLinder @Nadin-Nader - I believe this issue is closed, correct?

**Comment by TracyLinder** [comment]
### Closing
