### ISSUE TITLE
Accommodate multiple violations per contact

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#900]
Officers regularly report multiple violations in a single contact. In Brazos, they stack up with warnings in green and citations in red:
![Screen Shot 2019-11-13 at 5 12 34 PM](https://user-images.githubusercontent.com/1463708/68813317-126a1280-063b-11ea-8010-4f35dee56652.png)

Ideally we could have an "Add another" UI so that as many violations as necessary could be added to a contact and each can be either a warning or a citation. 

See [user testing video here](https://drive.google.com/open?id=1ouwlTPrRiRk-LmHhnYfKV-OEXSLBn9qk).

**Comment by SurbhiBakshi** [comment]
When I add multiple violations to a contact, I am not sure how to get the form to navigate back to Assignment Details.

**Comment by amenity** [comment]
@amenity - schedule a time to review with Surbhi and Diana

**Comment by SurbhiBakshi** [comment]
- [ ] Need a big button to direct officers back to earlier page after recording violations for that contact.
![Screen Shot 2019-11-22 at 2.06.12 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/dba98031-c0de-4101-b9cf-33edd0721935)

**Comment by amenity** [comment]
@SurbhiBakshi implemented this. The UI isn't ideal so we are looking into other options, namely #639. Will create new issues to improve user experience if necessary.
