### ISSUE TITLE
Add `crash_created` timestamp to `atd_vz_data.public.atd_txdot_crashes`

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9000]
Adding a timestamp that is set to the current time when a crash record is initially created from the CRIS → VZ ETL would allow for a much easier diagnosis of potential or on-going issues with the ETL itself. This will allow for quicker and more informed responses to crash ingest issues.

I propose this be run on the database. The data will self populate as new records are created and no changes are required to any other portions of the suite. 
```
ALTER TABLE atd_txdot_crashes ADD COLUMN crash_record_created timestamp DEFAULT now();
```

**Comment by mateoclarke** [comment]
Just wanted to articulate my support for this enhancement. Frank mentioned to me he thought it would be beneficial to make this update as he works on refactoring/Prefect-ifying the CRIS ingest process.

**Comment by frankhereford** [comment]
We had [a brief discussion about the column name](https://austininnovation.slack.com/archives/CM9MK950S/p1651176097823319) in slack today, which lead to the outcome of picking `imported_at`. The intent is to describe the event when we pulled the data into the VZD and differentiate it from when the crash was originally created in upstream systems.

I plan on creating a PR shortly after today's dev sync which notes the migration and upon acceptance into the code base, executing the `alter`s on the staging and then production database.
