### ISSUE TITLE
Enhancement Banners Permit and Payment in Knack  

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9001]
- [x] Curious about the statuses. There’s a reservation “Thrive Summit 2022” ID 421. Joseph installed and submitted work ticket. My status is “Installed” but the Work Order Status is still “Need to be installed”. Are we missing something?
>Looked into this and added a new specification, I didn't update anything. I think i just refreshed the page after the change. 
I did ask stakeholders if they wanted me to made the form modal so that it would update upon submission. 

- [x] I’m entering an application for HRD. When entering Banner Locations, can there be a “number of poles” and “comment” section for each district entry? For example, 8 poles on Congress Bridge and 8 on N. Guad.
- [x] Added back "Location Comment" on the Banner Location tables for the Dashboard details view and the Technician Work Order view.

**Comment by dianamartin** [comment]
Emailed stakeholders of the updates 4/26
>I went in to check out that “Thrive Summit” record and saw Joseph’s specifications. I just added another one behind his and then manually refreshed the page and it turned from “Need to be Issued” to “Issued”. 
>- That might be what’s happening, you might not be seeing it update automatically afterwards. I can change the behavior of the form so it’s a modal pop-up and just refreshes the parent page when it’s submitted if that’s better? 

>I’ve added the “Banner Location Comment” field on the Banner Locations table in the LPB Dashboard details page, which is inline editable for a Reviewer. 

>- On the work order details page for LPB, Joseph will also see those comments on the Locations table. 
![image](https://user-images.githubusercontent.com/21112975/165541051-e5590991-b79b-48b9-aad9-1d57df7122c3.png)

**Comment by dianamartin** [comment]
Lauren replied 4/26
>Perfect, thank you Diana!
