### ISSUE TITLE
Persist column configuration between user sessions

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#9008]
Follow up enhancement to this issue: https://github.com/cityofaustin/atd-data-tech/issues/8931

Previous issue addressed the column configuration resetting between renders. This issue should persist the toggled columns between reloading, navigating away, new sessions. 

Configuration could be stored in url, as a cookie, or in local storage.

**Comment by johnclary** [comment]
@chiaberry i think your original PR for column persistence covered this? column settings go to local storage.

**Comment by johnclary** [comment]
This has been available for some time.
