### ISSUE TITLE
Assignment Details Page improvements

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#901]
- Change page title to "Assignment Details"
- Remove "Assignment..." from row headings, e.g. "Assignment Date" ---> "Date"
- Remove the "Contacts Filter" functionality that appears once there are contacts - unnecessary since rarely more than 6 contacts captured in a single two hour period
- "Back to Officers" link at bottom should be "Back to My Assignements" or  "◀️ My Assignments" (ask @mddilley if there is a way to add an arrow to the button.

**Comment by mddilley** [comment]
An arrow can definitely be added. We did a similar thing with Signs and Markings for the "back to top" button/link. Putting this snippet here so I don't lose it.

```
/* Make back link in Location Details View bold, larger, and add FontAwesome back arrow */
#kn-scene_1039 > div.kn-view.kn-back-link > a {
  font-weight: 700;
  font-size: 18px;
}

#kn-scene_1039 > div.kn-view.kn-back-link > a:before {
  font-family: "FontAwesome";
  content: "\f0a8";
  display: inline-block;
  padding-right: 3px;
  vertical-align: middle;
  font-weight: 900;
}
```

**Comment by amenity** [comment]
@SurbhiBakshi - can you size this? If the back button code is something we would need a developer to do, we can break it off into a separate issue.

**Comment by amenity** [comment]
@SurbhiBakshi based on your conversations with Lewis, do you think we should keep this in the backlog?

**Comment by SurbhiBakshi** [comment]
@amenity looks like these were improvements slated for the Officer phase. We are not recording contacts (citations + warnings) anymore, think we can remove this from the backlog and create new ones based on Pat's feedback.

**Comment by amenity** [comment]
Ahh right, @SurbhiBakshi. Agree. We can compile recs for the new UI in future issues.
