### ISSUE TITLE
SIF AMANDA Permissions

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9017]
**The following users need SIF folder permissions:** 

- [ ] Tracy - LINDERT
- [ ] Vish - CHANDRAV
- [ ] Amber - ~MITCHEA~ MITCHLLA
- [ ] Nathan - AUBERTN
- [ ] Dan V - VALBRACD
- [ ] Bryan G -  GOLDENB 
- [ ] Sree - SRBLAZE, SBLAZETEST
- [ ] Subha - SHROFFS,SHROFFS1
- [ ] Nadin - NADERNAD, NADERTEST

**Comment by TracyLinder** [comment]
@Lpriya-LIT the list of users is ready in the description. Thank you.

**Comment by Lpriya-LIT** [comment]
@TracyLinder @vschandramouli Created request to Add the users to SIF - Button Permission 
Request Number - SCTASK0214980
