### ISSUE TITLE
[Enhancement] Ability to add non-Moped users to Project Team

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9018]
As a Moped user, I need the ability to add team members to projects who do not have login access to Moped.

### In scope
- On the staff page, add a "Role" option called "No login" that enables staff to create non-user staff members.
- Remove the ability to create a user with a "Viewer" role (b/c viewer-specific functionality is not currently implemented in the editor UI)
- Update the Moped API to support this setting?
- Bonus points: add a column to the Moped staff page that displays whether or not the user is active.

### Out of scope
- Ability to convert a non-login user to a login user via the staff/edit page. @johnclary will make a separate issue
- Overhauling the Moped DB to support a `Person` class, etc.

### Other considerations
- We reference the `moped_users.cognito_user_id` field in a few places in the editor. Definitely the activity log. What are the complications of this?

![Screen Shot 2022-09-14 at 2.26.16 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/f56fe5fd-1eec-4206-93fb-be4a23c8f9a7
)

**Comment by mateoclarke** [comment]
@amenity @johnclary This need came up again with PDD/TED in their onboarding meeting. The example was a PWD user who is on a project team but doesn't need user access to Moped.

**Comment by mateoclarke** [comment]
The lazy way would be just to expand the functionality of the moped_users table so that a Staff member can be external and a non user with a new boolean column. This would also require small updates to the Create/Edit user UI. This needs further understanding if it would be compatible with the user API.

The more holistic solution would be to create a new table/concept of a Person, who can be a moped_user via inheritance in a OOP example. But this would need further scoping and a lot more refactoring.

**Comment by mddilley** [comment]
After thinking about this some more, the "lazy way" would be a small effort. I'll have a user management UI refactor PR shortly that disconnects the form submit action from the form itself. So, we could recycle the form to create a non-user pretty easily.
