### ISSUE TITLE
Update GIS emergency contact on automated DTS service request confirmation email

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9020]
![Screen Shot 2022-04-27 at 5 38 39 PM](https://user-images.githubusercontent.com/1463708/165644519-528d9ba7-8755-4a11-b6a6-69174b642604.png)

**Comment by KaroEngstrom** [comment]
### W 10/5/22

Updated in DTS Portal 
![image](https://user-images.githubusercontent.com/100615928/194145648-7e8cb255-7b29-45af-9437-b3a02b7026c6.png)

Tested 
![image](https://user-images.githubusercontent.com/100615928/194146282-e7fc67db-0d7d-4d00-86ad-99ff0cb7a9c5.png)
