### ISSUE TITLE
Enhance "TIA Mitgations" search page for TIA Mitigation Managment

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9028]
From meeting 4/28 #9023 

# Enhancements on TIA Mitigations

- [x] Add locations fields (intersections, street segments)
- [x] Add `Project Address`
- [x] Add (New field) `Fund Status`
- Available
- Pending
- Spent
- [x] Add (New field) `Category`: "Historical" (to differentiate between historical TIA Mitigations v. more recent ones. To help with filtering)

**Comment by ChrispinP** [comment]
Updated Search input and results accordingly to task list. Added Permissions to Search Mitigations page to direct TDS Viewer and Mitigations Editor to the new Mitigation Details page for them.
![image](https://user-images.githubusercontent.com/67915167/168898378-48aef43b-55e8-4c3c-b98e-85ba53e479f8.png)

ready to review and close

**Comment by dianamartin** [comment]
Showed to stakeholder on 5/17, they were good with the update. No feedback, closing.
