### ISSUE TITLE
Create "Mitigations details" page on TIA Migitations search page

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9029]
From meeting #9023 

Requester would like the ability for a stakeholder to location a TIA Case that has a mitigations on it and be able to open up a details page to see the individual mitigations. 
![image](https://user-images.githubusercontent.com/21112975/165801118-a12e54a1-70d3-41d3-9d65-6770d44b1cca.png)

This would be built on the current "[TIA Mitigations](https://atd.knack.com/development-services#tia-mitigations/)" page

**Comment by ChrispinP** [comment]
New TIA Mitigation Details page specifically for TDS Viewer & TIA Mitigation Editor roles
![image](https://user-images.githubusercontent.com/67915167/168896598-b152fa61-14fe-45ac-996a-800a604b7d99.png)

Editable and non-editable tables for Mitigation Improvements
![image](https://user-images.githubusercontent.com/67915167/168896794-3cd2eac5-3582-4aec-94ae-4bddf088cd19.png)

Edit form for Mitigation Funding fields for Mitigation Editor role (PMs and TIA Reviewers also have access)
![image](https://user-images.githubusercontent.com/67915167/168897052-6f1c6479-2b1b-49c6-a315-f1a7b7d1f358.png)

**Added:**
Historical Fiscal Mitigations & Total
New Funding Fields
Edit Funding Audit Fields

ready to review & close

**Comment by dianamartin** [comment]
We showed to stakeholder in 5/17 meeting. They seemed pleased with the update, but did want to see this: 
- [ ] Add "Comments" field to the table @ChrispinP

**Comment by dianamartin** [comment]
Need to add some TIA Mitigation fields that are currently hidden
- Mitigation Cost
- Revenue Amount
- Check/JVD/CR#
- Payment Date
- Improvement Comment
- Mitigation Location Reference (put next to Primary Location)

**Comment by ChrispinP** [comment]
all listed fields were added, complete, closing
