### ISSUE TITLE
Update RPP - Add RPP Zone Restriction Days/Time

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9030]
Add the following day/times to the RPP/Add RPP Zone /Restriction Day/Times drop down:

 Monday-Sunday 8am-8pm

**Comment by ChrispinP** [comment]
Oh my, this multi choice field could use some cleanup for formatting and duplicates.

Otherwise, Monday - Sunday  8:00AM to 8:00PM restriction added since it did not exist.
