### ISSUE TITLE
Submit bug to Knack: Intersection address only populates City, State, Zip

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#904]
Officers are accustomed to giving location by intersections. In Brazos, there are two street fields so they can identify the cross street. For this reason, we are removing the second street field - built for Apt # etc. from our Report Contact page; officers would mistake it for the cross street. The officers can learn to type it all in one line, like "North Lamar and W 6th," and that appears to work initially since the predictive text completes with the correct information in the drop down. 

However, selecting the text in the drop-down or clicking enter only fills out the City, State, and Zip; not the street address that the intersection correlates to.  

Here is an example:
![out](https://user-images.githubusercontent.com/1463708/68817356-0d12c500-0647-11ea-81dc-07d8858cae40.gif)

**Comment by amenity** [comment]
@johnclary @mateoclarke @mddilley @dianamartin - y'all seen this before?

**Comment by amenity** [comment]
SIgns and Markings has an intersection location look up, but requires that all locations are preloaded in the database; would be a pain. 

Amenity will try to recreate in blank app and report to Knack if it still exists .

**Comment by amenity** [comment]
Recreated in a sandbox app and verified that it's still happening. Submitted a Knack support ticket. 

We're using the Knack default maps provider, HERE Maps. According to [the Knack docs on map providers](https://support.knack.com/hc/en-us/articles/360028811371-App-Settings-Map-Provider): 
> _Partial searches (street address only, city only, or ZIP code only) are not supported in HERE maps._

So I guess that the autocomplete suggestions are not considered a partial search. FWIW, typing the intersection in the map input on the [HERE Maps website](https://wego.here.com/) works as expected.

**Comment by amenity** [comment]
Reply from Knack:

> _Valerie (Knack)Dec 5, 5:53 PM EST_
> 
> _Hey Amenity, Thanks for reaching out about this. We were able to reproduce this issue and I've filed it as a bug with the team. Unfortunately, I wouldn't be able to provide an ETA on when this would be fixed, and it doesn't seem like this one would have a good workaround .. other than not using intersections to search against.We'll let you know once this is fixed but please let me know if you have any questions._

**Comment by johnclary** [comment]
@amenity we could try to work around this custom code. we would make our own CORS request to the HERE geocoder. would need @mddilley or @mateoclarke to look into it.

**Comment by amenity** [comment]
@johnclary @mateoclarke @mddilley - We have a Sprint Review on Monday so I'll take the temp on how important this is, but I suspect it would be a major usability improvement if we got this working. Officers currently use intersections for all of their reporting and even verbal communication and I think they'd have to look up addresses as an additional step in their process if they can't use intersection data. Do you have a rough idea about level of effort?

**Comment by amenity** [comment]
Another note from Valerie @ Knack:I have a feeling this might have to do with the autocomplete functionality of Knack though and not necessarily HERE maps or Google maps.
