### ISSUE TITLE
Onboard Mike D.

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9042]
[New Employee Checklist](https://atd-dts.gitbook.io/wiki/onboarding/new-employee-checklist)

**Comment by mateoclarke** [comment]
## Accounts - Team Lead
- [x] Submit a [CTM New Employee Request Form](https://atx.service-now.com/sp?id=sc_cat_item_guide&sys_id=b714eb12db7a3f0021ccef92ca961972&sysparm_category=ea848d3adbce37405b03f482ba96193c) for a COA network account, eAccess PIN/HR Portal, and phone 
- [ ] Submit a [CTM service request](https://atx.service-now.com/sp) to add to DTS Distribution Email Group:
- [ ] Add "First Last Name" to email distribution list "ATD Data and Technology Service" ([ATDDataTechnologyServices@austintexas.gov](mailto:ATDDataTechnologyServices@austintexas.gov)) and "ACE ATD DL"
- [ ] Add to City of Austin Slack - austininnovation.slack.com
- [ ] Add to DTS Google Drive
- [ ] Add to [Gitbook](https://app.gitbook.com/@atd-dts/spaces)
- [ ] Add to [Austin Transportation Github Team](https://github.com/orgs/cityofaustin/teams/transportation/members) 
- [ ] Add to [DTS Presentation Template Team section](https://docs.google.com/presentation/d/1tHKTfUgQ-uAXdRBkEdXqR7ryBo_LTU86IzQxo1gJoeA/edit#slide=id.gfd2da31025_0_6) - two places
- [ ] Diana, John, or Mateo add to DTS 1Password (if needed; we pay for seats)

## Hardware — DTS Systems Admin
- [ ] Coordinate with DTS System Admin (Scott), make sure there is enough lead time for equipment to be acquired.
- [ ]  Laptop
- [ ]  Monitors
- [ ]  Chair - check availability, ask John to ask Peggy how we're handling this?
- [ ]  Power supply
- [ ]  Keyboard
- [ ]  Mouse
- [ ]  Docking station

## Calendar invites 
- [ ] Monthly Team Meeting — John
- [ ] Sprints — Amenity
- [ ] Sprint Ceremonies — Apps/Dev: Amenity; Geo: John 
- [ ] 1:1 — Supervisor
- [ ] First day: DTS Team Orientation — John
- [ ] First Week: DTS Product Ops — Amenity

**Comment by patrickm02L** [comment]
@amenity make one for Peggy.

**Comment by mateoclarke** [comment]
Todo:
- [ ] Still need to add Mike to Gitbook Dev Team once the Gitbook invitation is accepted.
