### ISSUE TITLE
IT Support: Revert Contractor Work Order to "Issued" from "Approved" - 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9060]
Christina T
SMB

Messaged 5/3

>Kati is needing this contractor work order pushed back to the issued status and I'm unable to move it because it's already been "APPROVED". Could you push it back to issued on the back end?
- Reference ID: 272
- [Work Order](https://atd.knack.com/signs-markings#work-orders-contractor/manage-contractor-work-order-details/621527ded7249a001e2ba20e/)

**Comment by dianamartin** [comment]
Steps: 
- Change `Work Order Status` to `Issued`

**Comment by KaroEngstrom** [comment]
T 5/3/22
- [x] Found the contractor work order using the Work Order ID in the contractor_work_order table. 
- [x]  Changed the status from APPROVED to ISSUED as requested. 

![image](https://user-images.githubusercontent.com/100615928/166507393-655715e6-b018-4472-99e3-4e1e3a3617f4.png)

![image](https://user-images.githubusercontent.com/100615928/166507408-bd37acbc-164d-48da-a2f2-2933451a5c3c.png)

- [x] Notified the requester via Teams  "Hi Christina, I rolled back the status on this Work Order from Approved to Issued" and included a link for her to be able to check the result.  Response: "Thank you so much!"
