### ISSUE TITLE
[MEETING] Quick Touch Base - Street Banners Program

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9074]
### Objective 
Talk about how things are going and some questions staff had

### Participants
Cathy, Lauren, Diana 
Stephanie couldn't make it

### Agenda
Add agenda here or create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting
- [ ] Optional: Schedule debrief
- [x] Meet and take notes
- [ ] Optional: Debrief with DTS team members
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
@moorerst we are anticipating that her latest email will enable them to use the Test Environment and then we might be invited to those

**Comment by moorerst** [comment]
Training sessions will be set up with SMO as needed. 
Closing issue.
