### ISSUE TITLE
AFD ETL Latitude and Longitude fields

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9076]
_Broken out of #8976_

- [x]  `afd__incidents` table: Add lat/lon columns to the table schema 
- [x]  Update the ETL to populate those values.

Details added by @mateoclarke on 5/18/22

**Comment by mateoclarke** [comment]
AFD Incidents table has a `geometry` point column representing the geospatial combined lat/lon of the incident. In addition we need lat/lon columns to the table schema and update the ETL to populate those values.

EMS Incidents table also has a `geometry` point column representing the geospatial combined lat/lon of the incident. It also has an existing `incident_location_longitude` and `incident_location_latitude`. No change is needed here.

The request to create a new `primary_latitude` & `primary_longitude` columns in addition to the lat/lon values for both the AFD and EMS Incident tables is not going to be implemented as requested. This require much more UI features to update and populate the "confirmed" lat/lon like we do for Crashes with the pin drop UI. 

Instead, we're going to set up AFD and EMS Incidents to have a relationship to a Crash ID and assume that they will inherit the QAed lat/lon values from the crash record. That work is captured in this issue: https://github.com/cityofaustin/atd-data-tech/issues/9077

The description above has been updated to reflect the scope of the work required.
