### ISSUE TITLE
[Feature] Edit Draft Regulation Process

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9090]
As a admin/technician I'd like to edit my Draft Package

**Comment by ChrispinP** [comment]
The Draft Builder has been refactored to be similar to an application process. The Draft Builder allows for the creation of the 4 different regulation sub-processes (Retire, Retire & Replace, Install, and Blank Install) with the ability to edit drafted regulations.
![image](https://user-images.githubusercontent.com/67915167/188947786-6339bbba-d773-444c-9e90-eb224c9c868c.png)

Closing as complete, will create new issues for any further updates
