### ISSUE TITLE
Guidance Document - Creation of automated regulation language

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9093]
Aggregate different "Regulation Types" and create a guidance document 

## As an engineer/engineering technician I'd like to create a regulation package that has standardized regulation language, this guidance document will help me standardize the regulation text.

[Guidance Document w/ EB comments](https://cityofaustin.sharepoint.com/:x:/r/sites/atdDTS/Shared%20Documents/KNACK_PROJECTS/Traffic%20Register/20220516%20-%20Guidance%20Document%20-%20creating%20automated%20regulation%20language%20with%20EB%27s%20comments.xlsx?d=w234954225d234c1fbaa932ee1823fddc&csf=1&web=1&e=LI5PL8)

**Comment by dianamartin** [comment]
Created a [guidance document](https://cityofaustin.sharepoint.com/:x:/r/sites/atdDTS/Shared%20Documents/KNACK_PROJECTS/Traffic%20Register/Guidance%20Document%20-%20creating%20automated%20regulation%20language.xlsx?d=w01252c8115d640979caa13be22c08726&csf=1&web=1&e=uvcUyQ) in SharePoint so we can easily share with stakeholders. 

Emailed 5/6
>Here is the start of the templates that we’d use for the automated regulation text language.    Guidance Document – Creating automated regulation language

>Please, review and choose which template language you want to keep. Just populate “Yes” under the column for “Keep Language?” You’ll see that there are some that are highlighted in “yellow”, which I don’t have examples for. For those, if you can enter some examples that would be super helpful. 

>Have a great weekend everyone!

**Comment by dianamartin** [comment]
Discovered a copy of the ["Regulations"](https://docs.google.com/spreadsheets/d/12P4F51H3Fhe7_cuLIYig8ZGmJcXh_CGQCx1e_4xi8JU/edit#gid=1332607283) in their raw and untouched format. This has a complete listing of regulation types. Will use it to fill in the gaps to the spreadsheet.

**Comment by dianamartin** [comment]
Emailed stakeholders - 5/25
Users: Eric, Joana, Gilda, Nathan W.
>I filled out the missing ones with some examples from an old export that John had in a shared drive. Can you please review them again and give the go ahead that these are the templates you’d like us to reference when building it out?

**Comment by ChrispinP** [comment]
Pulling this back in progress to update text strings according to View IDs for potential Dev work.

**Comment by ChrispinP** [comment]
Reached out to Mike and Chia on what is needed. For now we are going to attempt a more modular approach so right now there is no need to create every combination of field mapping for each variation of reg text. Moved documentation to the [Google Drive - Reg Text Automation](https://docs.google.com/spreadsheets/d/1keWdmOVl2GM4KTnm-KbnCI8HJc01anq5VlAdbzyf4Us/edit#gid=1749632919).

Ready for Devs, no further action needed from Apps at this time.

**Comment by johnclary** [comment]
@ChrispinP let's sync real quick about the best way to format these "patterns" for the devs.

**Comment by ChrispinP** [comment]
@johnclary Diana's comment was not inclusive of everything so I have updated with all 3 possible options in how we can update the records. Is it then still required that I create those 38+ Field ID combinations using the $ sign?

**Comment by dianamartin** [comment]
@dianamartin Send Eric B. another email to do a final review of guidance document.

**Comment by dianamartin** [comment]
Chrispin sent Eric email for me 🙏🏽 - Thanks @ChrispinP

**Comment by dianamartin** [comment]
We (Chrispin and I) synced on 8/11 with Eric to go over his comments on the guidance document. Chrispin got a lot of good notes and was able to update the guidance document. It's linked at the top of this issue. Closing issue now that Eric finalized his comments.
