### ISSUE TITLE
SIF: Adding property values to the free-form address drop-down

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9101]
Acceptance Criteria: 

- System must display the Address line of every property record added to the SIF folder as a drop-down option in the Address column of the SIF Building Info freeform for that folder.
- Every time a new property record is added to the SIF folder, system must update the options for the address column in the SIF building info freeform to include that property address.

**Comment by TracyLinder** [comment]
@vschandramouli please update AC

**Comment by vschandramouli** [comment]
Updated AC, moving to backlog. Assigning to both Sree for now.

**Comment by Nadin-Nader** [comment]
This has been deployed to DEV and UATd. Sending to TEST

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT @TracyLinder this has been sent to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0218072**

**Comment by Lpriya-LIT** [comment]
@TracyLinder @Nadin-Nader Verified in Test, works as expected
