### ISSUE TITLE
Milestone Template MVP

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9102]
_For more background and notes, see [this issue](https://github.com/cityofaustin/atd-data-tech/issues/8010)_

1. Add a the "Project Type" field to the "New Project" page `moped/projects/new` 
    - _See the mockup below_
    - This field should be single-select (unlike on the Project Summary page where it is a multi-select field)
1. Add any new milestones from [Renée/Ivonne's excel sheet](https://github.com/cityofaustin/atd-data-tech/files/8636559/Signal.Project.Milestones_040622.xlsx) to the `moped_milestones` table.
1. Using [Renée/Ivonne's excel sheet](https://github.com/cityofaustin/atd-data-tech/files/8636559/Signal.Project.Milestones_040622.xlsx), implement 1 hardcoded `SignalAndPHBMilestoneTemplate` mutation. 
    - This mutation should execute only on the initial Project Create action.
    - This `SignalAndPHBMilestoneTemplate` mutation would only get appended to the standard `addProject` mutation when the `project_type` field is one of these four types:
        - Signal - New
        - Signal - Mod
        - PHB - New
        - PHB - Mod
     - Make sure the mutation also updates the `moped_project_milestone`s' `milestone_order` field using the order provided in the Excel sheet.
1. Update the Projects Timeline page `/moped/projects/:id?tab=timeline`, Milestone table to use the `milestone_order` field as the default sorting for the table display. (We'll address drag & drop reordering in a future issue)

### New project page mockup with new field 
_But remember, not multi-select_

![mockup](https://user-images.githubusercontent.com/1463708/167475876-b9fd2c86-12f8-4410-a867-9d1b2f64a75a.png)

**Comment by amenity** [comment]
Per discussion with Renée and Ivonne, this MVP will also include a column for the associated phase in the Milestone table.
