### ISSUE TITLE
[Traffic Register] Feature: Configure SSO 

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9103]
Need to set up SSO for user to be able log in easily

**Comment by amenity** [comment]
@ChrispinP added the code. Now we need to get configuration from CTM.

**Comment by ChrispinP** [comment]
Did initial SSO setup on the Reviewer Dashboard login page

Created the ServiceNow ticket: INC0203209

Emailed CTM to setup. Pending Response

**Comment by ChrispinP** [comment]
Received the XML Metadata from CTM.

Traffic Register is successfully setup with SSO. Tested by Karo and I. Saved IP Cert in 1Password.

Enabled SSO for all Login pages and added a login page for the Home page.

complete
