### ISSUE TITLE
DTS Workflow Discovery Meeting Task

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#911]
We should identify potential executive support for a project during the discovery meeting. Add a note to discuss this somewhere so you don't forget.

We should have a discovery meeting checklist.

**Comment by amenity** [comment]
@TracyLinder -we have this question on the intake form:
<img width="650" alt="Screen Shot 2019-11-15 at 11 44 22 AM" src="https://user-images.githubusercontent.com/1463708/68963735-478e7600-079d-11ea-9f28-399c9ca1a5c8.png">

Are you specifically wanting an _executive_ sponsor? If so, should that be an additional question or should we update this one?

**Comment by amenity** [comment]
[Here's the Discovery Meeting template](https://docs.google.com/document/d/1AcjxHv6XCEutSAIzNebnxNR9EL8CORiHrVfNlQuChII/edit#).

**Comment by TracyLinder** [comment]
[Here's the issue for the template.](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/470) Closing.
