### ISSUE TITLE
BUG: AMANDA cases not assigning Cases to staff correctly on SP and C8 Folders (Waiting on Zachary to let me know if all good)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#9121]
**BUG**: on SP, C8 cases when intake runs the process "initial distribution" Amanda finds names in the info tab and creates processes. 

User: Zachary W.

Please see ROW ID **12925870**
No name was populated for Process 51132 ATD Engineering Review
Amber M. should have been the reviewer which was pulled from Info 51474 "ATD Engineering Review"

From Incident: **INC0194323**

**Comment by SubhaShroff** [comment]
NOTES: **The ticket mentions about SP & C8 folders, but the given RSN is ZC.**
ZC -  12925870 - (Checked on PROD for code and config)
The configuration for the Process 51132 ATD Engineering Review - default Assigned user will be - ATD Engineering Review.  And when I checked the Process Audit, it shows it was assigned to ATD Engineering Review. Some Code reset it to empty value. Yet I am not sure what code is overwriting as there is no obvious code in the process procedure. I am revisiting it.

I didn't find any code in the process procedure that sets the assigned user to respective infovalue.

ATD Engineering Reviewer on PROD has 4 names: Amber Hutchens, Bryan Golden, Matiur Rahman, Sangeeta Jain and default value will be Amber Hutchens. 
But AMBER MITCHELL is not found in the ATD Engineering Reviewer(51474) info dropdown list. So, that name can't be assigned to the process assigned user, unless its picked manually from process tab.
----------------------------------------------------------------------------------------
@Nadin-Nader  @TracyLinder  Above is my notes till now what I found for the given RSN(ZC). Can I get the list of processes for SP/C8 that has this bug? Or is this bug happening for all the processes of SP/C8?

**Comment by Nadin-Nader** [comment]
Yesterday i worked a bit with Subha on this. In the case of Amber, Her maiden name was still on her profile (Mitchell) but she was listed in the info as Hutchens. I modified her account profile to Hutchens to match the info. Subha tested it last night on TEST and it worked. 

I responded to an email from Zachary W. explaining the above to him.

**Comment by Nadin-Nader** [comment]
I tried to get information from Zachary Whitaker about the issue and he informed me that he has not had time to check to see if AMABER is getting cases assigned. 
Since i have not heard any more about this in emergency/hi priority/important labeled emails from Zachary, i am closing the card.
@TracyLinder fyi
