### ISSUE TITLE
Testing HR SSPR Prototype

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9126]
@dianamartin some comments from my initial testing:

View My SSPR

- Added a New Responsibility and it displayed twice

![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/7b58d79c-e3b8-45e2-93b8-0d01a06dafc5)

- Added a second priority but I did not display

- Add Competencies button - should it say **Rate Competencies** since it's where  the competencies are rated and not added

- Not sure how to add the Mid Year Rating for Competencies. I selected the column on the table which gave me the option to Edit which I did but it's just spinning. 

![image.png](https://images.zenhubusercontent.com/5da61135c9a7f8000179986e/dc07a48d-4415-41a1-80da-cdaffdcf3375)

I'll continue testing in more detail next week.

**Comment by dianamartin** [comment]
# Corrections
- View My SSPR
- Added a New Responsibility and it displayed twice 
> Added a page rule to hide in "In Review" status

**Comment by moorerst** [comment]
Confirmed the corrections. Closing this testing issue. Will open new testing issues as needed.
