### ISSUE TITLE
Assign new Github org owner

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9141]
I am still assigned as an org owner in [COA Github](https://github.com/orgs/cityofaustin/people). We should designate a different DTS person to be our second owner.

The owner change process is outlined [here](https://github.com/cityofaustin/coa-github-governance#how-to-change--add-an-owner). 

> 1. Open a pull request with the requested changes to the owner list.
> 2. Assign two other owners to review the PR.
> 3. Once approved, merge the PR
> 4. Update the user's github role accordingly. If you do not have owner privileges, contact one of the owners who approved your PR for help.

**Comment by mateoclarke** [comment]
Updated the doc, and assigned reviewers: https://github.com/cityofaustin/coa-github-governance/pull/2

**Comment by amenity** [comment]
@mateoclarke - can we close?
