### ISSUE TITLE
Review Metric Boulevard

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#9143]
Metric Boulevard (is a split lane, but the polygon is not)

**Comment by alan-deanda** [comment]
The CTN is digitized to show the centerline of a road, not the "sausage links" of split polygons.

**Comment by patrickm02L** [comment]
Going forward VZ GIS staff will be able to make edits in MAINT, which will publish to this public [AGOL map](https://austin.maps.arcgis.com/apps/mapviewer/index.html?layers=f9db1ee0aaa2438284154ccc47302eb5).
