### ISSUE TITLE
HR Digital SSPR - Functionality

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9151]
Functionality
- [x] Attaching kudos, additional information
- [x] Employee should not have access to edit
  - If anything is signed off on, it can't be edited
  - Must have read only ability for Mid-Year, Year-End, Special Review
- [x] After SSPR has been Completed/Signed/Closed no changes should be made with a mandatory comment

Moving Reporting to it's own issue

**Comment by dianamartin** [comment]
# Notes from 6/1 Meeting
- [x] Department/Division - Add "Division" 

## Priorities
- Convert Supervisor/Manager Comment field - Paragraph to Rich Text
- Add Employee Comment/Feedback - Rich Text

## Edit Access
- If something is "signed off" by employee, those records can't change
- Need to refactor the "editing" functionality

## Division Manager access to records
- build out Division pages for SSPRs
- Add connection for Division Manager

**Comment by moorerst** [comment]
- SSPR copy function
- [ ] copy entire SSPR from fiscal yr to fiscal yr

- Ability to edit
- [ ] No one should have the ability to edit after the Mid Year is Complete and Signed and after the Year End is complete and signed

**Comment by KaroEngstrom** [comment]
No completed and signed version should be editable (including the initial start version that sets the agreed-upon goals for the year).

**Comment by moorerst** [comment]
@dianamartin 
Testing Notes 6/7
**Logged in as Test Supervisor A**

- Staff Forms / SSPR Details / SSPR Supervisor View

- Created New SSPR
- Updated Dept/Divison mission, goals, etc
- [ ] Attachment Section - suggestion move this section under Priorities

- Added 3 New Priorities
- Added Employee Development Plan
- Added Meeting Type SSPR Planning Meeting 
- Status changed to Complete & Signed

**Logged out and Logged Back in as Test Supervisor A**

- Located existing SSPR
- Changed Status to Mid Year - Employee Feedback
- Added Rating and Comments to Mid Year Priorities
- Added Ratings for each Competencies and Overall Rating

- [ ] Reviewed the Competencies informational button. The second set of Competencies listed at the button need to be removed

- Added SSPR Meeting Type Overall Mid Year Feedback Rating without Employee Signature

**Logged in as Employee Stephanie Moorer**

- Added Attachment File - showed up in the table
- [ ] Added Attachment Link - does not show up in the table
- Select the Employee Feedback Edit button and added comments to each priority. Had to Refresh to see the comments
- Priorities section displays twice
Priorities | Employee has the employee feedback edit option
Priorities does not have the edit option but has the comments that were entered by the employee
- [ ] should this be titled Priorities | Supervisor?
- could not edit Competencies or Development Plan
- Added Employee eSignature
- Status changed to Complete & Signed

Logged in as Test Supervisor A for Year End Review

- Changed SSPR Status
-  There were no Year End Priorities. Used the COPY function from the Mid Year Priorities. **THIS IS AWESOME**
Rated each Priority
- Rated Year End Competencies
- Added SSPR Meeting Type Year End Evaluation Rating

Overall - this is looking great. I'm super excited with it. I would like to think about the SSPR Status after the Development Plan Employee Signature and after the Mid Year Employee Signature.
Maybe Planning Complete & Signed and Mid Year Complete & Signed based on the Meeting Type???

**Comment by moorerst** [comment]
6/8 Testing continued:
Logged in as Test Supervisor A

SSPR Details/Supervisor View/All

- [ ] some of the SSPR's in the table have Division displayed and some don't. How is Division being populated?
- [ ] On the same page Division Manager Access/DTS
I can access the SSPR Details for employee Test Supervisor B created by Test Division Manager

**Comment by dianamartin** [comment]
Your comment on this:
>On the same page Division Manager Access/DTS
I can access the SSPR Details for employee Test Supervisor B created by Test Division Manager

- This should only be for division managers, I probably hadn't configured that yet.

**Comment by dianamartin** [comment]
@moorerst this is ready to review

**Comment by moorerst** [comment]
@dianamartin I reviewed the updates and all looks good.

**Comment by dianamartin** [comment]
Closing issue, now that PM tested feedback updates.
