### ISSUE TITLE
HR Digital SSPR - Assigning & Delegating 

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9152]
**Assigning & Delegating**
**How do we deal with these scenarios?**

- New Manager

- New Division Manager
- Supervisor promotes to the other division
They need to have personnel files if they leave the department

Delegating SSPR's
- Delegate responsibility (Supervisor/Manager/Division Manager on leave)

Records retention

- How many years kept in Knack?

**Comment by dianamartin** [comment]
We can make inline editable for HR Forms - have the ability to change it now

**Comment by dianamartin** [comment]
We discussed this in our 7/27 meeting. I showed them the TLC form under HR Forms allows HR staff to edit the Supervisor Manager Name. 
- [x] Made table inline editable
- [x] Added background color to fields that are inline editable like the TLC forms
![image](https://user-images.githubusercontent.com/21112975/181367784-83926a93-1015-4247-9bc9-798dc6b65bf5.png)

**Comment by moorerst** [comment]
Closing this issue.
