### ISSUE TITLE
[Feature] SSPR Priority Templates to use with multiple employees (solution for copy SSPR)

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9153]
As a supervisor, I want to create an SSPR once that I can use with multiple employees so I can do many SSPRs for staff with identical priorities without having to manually copy + paste for each person. 

There are 6 groups across multiple divisions, and this is a very high-visibility project.

**Comment by dianamartin** [comment]
Some of the components are currently built out in `TEST | 18 APR 2022 | HR | Human Resources Manager`

The page where the new table is being added exists. We'd need the table set-up in PROD to get this done, but can do it TEST environment first to see if it's working. 

Staff Forms>Details
- [Details page](https://builder.knack.com/atd/test--18-apr-2022--hr--human-resources-manager/pages/scene_162)
- [SSPR | Division Manager view](https://builder.knack.com/atd/test--18-apr-2022--hr--human-resources-manager/pages/scene_162) - `scene 162, view 321`
- Division field: `scene 162, view 321, column 5`

**Comment by dianamartin** [comment]
## Code 
// --- Begin Item Copying ---
$(document).on("knack-view-render.view_315", function (event, view) {
  // automatically submit 'copy' form when modal renders
  $("button[type=submit]").submit();
});

$(document).on("knack-form-submit.view_315", function (event, view, record) {
  // Insert a copy of an item to the same purchase request

  var formUrl =
    "https://api.knack.com/v1/pages/scene_123/views/view_316/records/";

  // url where to redirect to on record insert success
  var redirectUrl =
    "https://atd.knack.com/finance-purchasing#purchase-requests/purchase-request-details/";

  // grab ID of purchase request and append it to redirect URL
  console.log(record.field_20_raw);

  redirectUrl = redirectUrl + record.field_20_raw[0].id;

  console.log(redirectUrl);
  fields = [
    "field_36", // unit of measure
    "field_37", // part #
    "field_15", // description
    "field_16", // unit cost
    "field_20_raw", // purchase request
    "field_189_raw", // department
    "field_105_raw", // fund
    "field_103_raw", // unit
    "field_104_raw", // object
    "field_357_raw",
  ];

  // reduce object to specified fields
  const filtered = Object.keys(record)
    .filter((key) => fields.includes(key))
    .reduce((obj, key) => {
      var new_key = key.replace("_raw", "");
      obj[new_key] = record[key];
      return obj;
    }, {});

  insertRecord(filtered, formUrl, redirectUrl);
});

function insertRecord(record, url, redirectUrl) {
  Knack.showSpinner();

  var user = Knack.getUserToken();

  var headers = {
    "X-Knack-Application-ID": "5b422c9b13774837e54ed814",
    Authorization: user,
    "content-type": "application/json",
  };

  // insert the record
  $.ajax({
    url: url,
    type: "POST",
    headers: headers,
    data: JSON.stringify(record),
    success: function (response) {
      Knack.hideSpinner();
      window.location = redirectUrl;
    },
  });
}
// --- End Item Copying ---

**Comment by amenity** [comment]
Discussion at Product Sync:
- The app is stable
- Devs will need to know which objects and, in those, which of the views and fields
- Diana will make sure everything is configured in Test when devs are ready to work on it

**Comment by dianamartin** [comment]
# Test Details
- App: TEST | 17 OCT 2022 | HR | Human Resources Manager
## Object Info (`form_sspr`)
- `form_sspr` - [object 31](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/records/objects/object_31)

### When copying the SSPR (`form_sspr`), these fields to be copied:
- `Status` - [Field 448](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/schema/list/objects/object_31/fields/field_448/settings) - populate with "Planning"
- `Created Date` - [Field 437](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/schema/list/objects/object_31/fields/field_437/settings) - populate with "Current Date"
- `Fiscal Year` - [Field 449](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/schema/list/objects/object_31/fields/field_449/settings) - clear to blank 
- `Employee Name` - [Field 441](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/schema/list/objects/object_31/fields/field_441/settings) - populate with "Employee name" of SSPR being copied. This is a connected record to Accounts (object 5/ field 17)
- `Supervisor Name` - [Field 444](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/schema/list/objects/object_31/fields/field_444/settings) - populate with "Supervisor name" of SSPR being copied. This is a connected record to Accounts (object 5/ field 17)

## Object Info (`sspr_priorities`)
- `sspr_priorities` - [object 32](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/records/objects/object_32)

### When copying the SSPR Priorities (`sspr_priorities`)
- `Type` - [Field 468](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/schema/list/objects/object_32/fields/field_468/settings) - populate with "Planning"
- `Priority` - [Field 471](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/schema/list/objects/object_32/fields/field_471/settings) - populate with "Priority" of SSPR being copied
- `Major Responsibility` - [Field 472](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/schema/list/objects/object_32/fields/field_472/settings) - populate with "Major Responsibility" of SSPR being copied
- `Key Tasks and Areas of Responsibility` - [Field 474](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/schema/list/objects/object_32/fields/field_474/settings) - populate with "Key Tasks and Areas of Responsibility" of SSPR being copied
- `Individual Performance Measure` - [Field 473](https://builder.knack.com/atd/test--17-oct-2022--hr--human-resources-manager/schema/list/objects/object_32/fields/field_473/settings) - populate with "Individual Performance Measure" of SSPR being copied

# Prod Details

**Comment by chiaberry** [comment]
@dianamartin What do you want to trigger copying the ssprs? In the finance app, I believe it is automatically copied when someone submits a form (though I may be misreading the code)

Are you picturing a button where someone could choose to copy the existing SSPR into a blank one?

**Comment by dianamartin** [comment]
@chiaberry I'm thinking a button in the table would be nice or the in the SSPR Details

**Comment by patrickm02L** [comment]
@patrickm02L tagging for updates.

**Comment by chiaberry** [comment]
I am leaning towards putting a button in the SSPR table. Should a supervisor be able to copy any SSPR? Or exclude ones that are in planning or exclude completed and signed? 

And how do you want to handle copying the priorities? should the priorities be automatically copied when the SSPR is being copied?

**Comment by dianamartin** [comment]
I feel like we should only allow supervisors to copy in the "Planning" and "...Completed and Signed" status. I'll have to check with HR but that's my gut feeling bc in Planning, they can prep an SSPR and keep it in Planning as a template. 

We can try to put an edit button on the table or a trigger and see which is best to configure your button.

**Comment by dianamartin** [comment]
@chiaberry I don't remember where we went with this..do you remember?

**Comment by chiaberry** [comment]
put back into the backlog, but it can be pulled back out as we get closer to the midyear sspr season

**Comment by ChristinaTremel** [comment]
# 10/17
Met with Chia and identified the things that we need to clarify to get this issued to someone on the Dev team
- Identify fields to copy
- Identify fields to leave blank
- Where should the copy function should exist?
- Where should the user be navigated after copying the SSPR? And what should happen when the SSPR is copied?
- Should we/could we make the copy button disappear after 1 copy? (Chia thinks this might be possible but we need to look into it)
- Will discuss this with HR during their Sprint Review

**Comment by ChristinaTremel** [comment]
Could we possibly look at creating a template? Or a bank of priorities?

**Comment by dianamartin** [comment]
# 10/25
Christina and I synced and came up with a way to perhaps do this mostly in knack with a little bit of custom code. 

OBJECT STUFF
- `sspr_priorities` - create self connection `SELF-CONNECTION PRIORITIES`
- `sspr_priorities` - add a new field `TEMPLATE` (Y/N)
- `sspr_priorities` - add a new field `TEMPLATE NAME` - short text

PAGE STUFF
- [ ] Created new page `SSPR TEMPLATE LIBRARY` - have to be login enabled
- [ ] Copied "New SSPR" form to this page 
- [ ] Removed all field from this form
- [ ] Submit rule, redirect to new child page `Select Priorities`
- [ ] On "Select Priorities' 
- [ ] Add `sspr_priorities` table - rename "Template Priorities" - SOURCE "Template" is "Yes"
- [ ] Details widget - show `ID` field (temporary) until dev can auto assign it (could also be hidden)
- [ ] Add `sspr_priorities` table - rename "Copied Priorities" - SOURCE "form_sspr" is blank 
- [ ] Add `sspr_priorities` table - rename "Added Priorities" - enable "inline editing"
- [ ] Added update `form sspr`
   - with no fields, just Submit button renamed to "Review SSPR"

**Comment by dianamartin** [comment]
# 10/27
- "Add Priority" (trigger) [builder side](https://builder.knack.com/atd/test--26-oct-2023--hr--human-resources/pages/scene_271/views/view_554/table/columns/0)
- SSPR ID Details [builder](https://builder.knack.com/atd/test--26-oct-2023--hr--human-resources/pages/scene_271/views/view_556/details)

![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/4a1f81b2-71f2-41c3-bd16-00872cb700f0)

**Comment by dianamartin** [comment]
# 10/27
## New Direction
Christina and I synced and think we've found a new solution

- [ ] Created a new object `sspr_priority_template` 
- [ ] Field Headings
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/5f50fe9e-d7cd-4b16-9cc5-a49e6f2f1fe0)
- [ ] Create "Display Name" (Template Division | Template Name)
- [ ] Set to show for the object choice
- [ ] Create connection on `sspr_priorities` with `sspr_priority_template` 
- [ ] Created new page on SSPR Details (next to + Add Priority) - rename to `Add Template Priority`
- [ ] Add new form `add SSPR priority - connected to form_sspr`
- [ ] Add `sspr template priority` field
  - [ ] Show confirmation - `Priority added`
  - [ ] Create Record Rule
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/f0d8aed2-9b56-4e8d-b392-caf0b3755a3d)
- [ ] Add `sspr priority` table
![image](https://github.com/cityofaustin/atd-data-tech/assets/21112975/01a36e1b-a7d7-4969-9eb8-937d9364de7f)
- [ ] Add updated form (form_sspr), clear all field, redirect to parent
  - [ ] Change submit to "Back to SSPR"

**Comment by ChristinaTremel** [comment]
This was completed and we were successfully able to create a solution and assist SBO, Parking and some additional groups with utilizing the templates for the first time.
