### ISSUE TITLE
HR Digital SSPR - Training & Help Guides

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9155]
**Training & Help Guides**

- Add to Leadership Academy
- Add Safety Component
- Training Video
- Training Help Guides

**Comment by dianamartin** [comment]
Started off by revamping the "Help" section of the application
![image](https://user-images.githubusercontent.com/21112975/181383922-3702974f-7860-4554-8b9e-b0de33993c06.png)

- [x] Created a new Drop down Menu called "Help"
- [x] Renamed original Help page to "Time Log Help"
- [x] Created a new page called "TLC Help"
- [x] Started a new page called "SSPR Help"
- [x] Reviewed the pages and made formatting more consistent

**Comment by moorerst** [comment]
@dianamartin these Supervisor steps look great. I added some steps for the Employee.

Review and Edit SSPR | Employee
1. Go to Forms tab, click My Forms

2. Click on Details icon under "Success Strategy Performance Reviews | SSPRs" table for the current Fiscal Year SSPR

3. Under **PRIORITIES** section  select the Meeting Type (Mid Year, Year End, etc.)
4. Review each of the PRIORITIES for the Meeting Type. Review Rating and Supervisor/Manager Comments

5. Select the Edit button in the Employee Feedback column. Add comments in the Employee Comments section. 
6. When complete click **SUBMIT** at the bottom of the form. Continue for each priority.

7. Go to ATTACHMENTS section. Select Add Documentation to Add Supporting Documentation which can include a file and/or link. 
8. When complete click **SUBMIT** at the bottom of the form.
9. Go to the **COA COMPETENCIES** - review the rating for each COA COMPETENCY

10. GO TO **SSPR MEETING SIGNATURES** locate the current Meeting Date and Meeting Type. Select the Edit button in the Employee eSignature column. Type your name in the Employee eSignature column. 
When complete click **SUBMIT** at the bottom of the form.

Employee would complete these steps for each SSPR Meeting Type.

**Comment by dianamartin** [comment]
@moorerst I've added your notes to the SSPR Help [page](https://atd.knack.com/hr#sspr-help/) for the HR group tomorrow.

**Comment by dianamartin** [comment]
I updated some text formatting, so that words were proper case rather then uppercase.

**Comment by moorerst** [comment]
closing this issue
