### ISSUE TITLE
[Urgent] VZV Discrepancies

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9157]
@xavierapostal has requested we look into some discrepancies in advance of a Statesman article being published Thursday, May 19th. 

> VZV has 85 Pedestrian Serious Injuries in 2019
> VZE has 90 Pedestrian Serious Injuries in 2019
> 
> I'd like to get a list of the crash IDs from the VZV that account for those 85 to find the "missing" 5

Xavier let us know what other discrepancies you find.

**Comment by mateoclarke** [comment]
Hey Xavier,

After reviewing this, I believe the 85 count in VZV is accurate. The discrepancy isn't related to a problem with the database but with the assumptions made when using that VZE screengrab of the Crashes table you shared. 

Even though you've sorted and filtered the Crashes table view to include only "Pedestrian involved" crashes, the sum of the Serious Injuries column in the table includes anyone (in any unit) with a serious injury from a "Pedestrian involved" crash. This means, if a crash involved multiple vehicles and a pedestrian, the SIs sum total could include non-pedestrians. 

If you look at the details of those first two crashes in the sorted list you shared a screengrab of you'll see: 
- [Crash #17226820](https://visionzero.austin.gov/editor/#/crashes/17226820): 4 SIs, only 1 of the 4 is a pedestrian
- [Crash #17210700](https://visionzero.austin.gov/editor/#/crashes/17210700): 2 SI, neither pedestrian 

Together, those two "Pedestrian involved" crashes account for the 5 non-pedestrians that got you from the 85 SI count in VZV to 90 from that specific table view in VZE.

Here's a [view in the open data portal](https://data.austintexas.gov/Transportation-and-Mobility/Vision-Zero-Crash-Report-Data-Demographic-Statisti/xecs-rpy9/explore/query/SELECT%0A%20%20%60person_id%60%2C%0A%20%20%60prsn_injry_sev_id%60%2C%0A%20%20%60prsn_age%60%2C%0A%20%20%60prsn_gndr_id%60%2C%0A%20%20%60prsn_ethnicity_id%60%2C%0A%20%20%60crash_id%60%2C%0A%20%20%60crash_date%60%2C%0A%20%20%60crash_time%60%2C%0A%20%20%60mode_desc%60%2C%0A%20%20%60mode_id%60%0AWHERE%0A%20%20%28%60crash_date%60%0A%20%20%20%20%20BETWEEN%20%272019-01-01T00%3A00%3A00%27%20%3A%3A%20floating_timestamp%0A%20%20%20%20%20AND%20%272020-01-01T00%3A00%3A00%27%20%3A%3A%20floating_timestamp%29%0A%20%20AND%20%28%28%60prsn_injry_sev_id%60%20IN%20%28%271%27%29%29%20AND%20%28%60mode_id%60%20IN%20%28%277%27%29%29%29/page/filter) that shows the 85 discreet pedestrians seriously injured in 2019 including with their Crash IDs.
