### ISSUE TITLE
Add Enhancements to the Markings Work Schedule 

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#9158]
Christina T. sent an email regarding further updates requested by the Signs and Markings supervisors: 

1. [Unscheduled Markings Jobs](https://atd.knack.com/signs-markings#manage-schedule/) table: can we add the “filter” option back to this table (example of the filter option on the Scheduled Markings Work table below).

![image.png](https://images.zenhubusercontent.com/621d512ff265461f22b1e2f2/3a910171-4798-47dc-bde8-c95d8c325051)

2. [My Work Orders (technician) page](https://atd.knack.com/signs-markings#my-work-orders/):
Add WORK GROUP to the My Jobs | Markings table.

3. [Add link to job on markings calendar pop up:](https://atd.knack.com/signs-markings#work-schedule/) **[Need to be logged in as Technician to see the calendar view on this page]**
Could we keep the link to the work orders and add link to go to the “JOB” from the pop up as well. (This is useful for the Technicians)

4. [Jobs page:](https://atd.knack.com/signs-markings#jobs/)
Add “Scheduled Date” to the jobs table before the “Issued” column

**Comment by amenity** [comment]
Follow up from #9056 .

**Comment by KaroEngstrom** [comment]
W 5/18/22 

- [x] Item 2: Added Work Group to the My Jobs | Markings table on the My Work Orders (Technician) page. 
![image](https://user-images.githubusercontent.com/100615928/169157652-0f324e6d-6ac6-4a30-ae5a-a00eed2940ee.png)

**Comment by KaroEngstrom** [comment]
Th 5/19/22 

1. Removed menu filter for when WORK_SCHEDULE is blank
![image](https://user-images.githubusercontent.com/100615928/169323994-9f1c3b8d-303d-4749-9f8a-9bfa84fa573f.png)
 and replaced it by adding the same to the source filter to allow users to create their own filter when using the table: 
![image](https://user-images.githubusercontent.com/100615928/169324284-861670d4-9c92-47b1-8581-9214595b0932.png)

**Comment by KaroEngstrom** [comment]
Th 5/19/22 

- [x] Item 3. Added a link to Job Details using the link to existing page option in the Event Details for the Technician table on the Work Schedule page. 

![image](https://user-images.githubusercontent.com/100615928/169352263-f8965e4c-bd4d-4545-8f92-d08ccab8315c.png)

**Comment by KaroEngstrom** [comment]
- [x] Emailed requester to let them know of the changes.
