### ISSUE TITLE
HR Digital SSPR - Testing Round 2 (document content & format)

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9166]
**Testing - second round focus on contents/format of the document not so much on work flow
Here are some suggestions**:

**SSPR Details:**

- [x] Missing fields - Supervisor Title
>Had the wrong "Title" field showing - had to do some testing. I also didn't have the Title on the Test Supervisor's accounts

- Missing section - Before Priorities the Department Mission, Goals, Programs and Activity section has not been added
  - [x] Added section to the `form_sspr` object
  - [x] Made Editable and Non-Editable details section
  - [x] Update page rules

![image](https://user-images.githubusercontent.com/21112975/170579932-ab3678f6-f03c-4dda-affa-d3094fe018b0.png)

- Edit Status drop list options includes Close, do we need the **CLOSE SSPR** button?
>I made this "Close SSPR" button as a quick way to close the SSPR, bc it's fewer clicks. I was thinking about the ease of use for the user.

**Priorities:**

- Move New Responsibilities button under the Priorities title and rename to New Priority
  - [x] removed "Priorities" title under the table
  - [x] added "Priorities" title under the button
  - [x] renamed button "New Priority"
![image](https://user-images.githubusercontent.com/21112975/170580049-040dc27c-0b46-42f9-a7f6-0401197eaa26.png)

**- Adding new Priorities, rating the priorities and adding comments is super easy to do**

**Competencies:**

- [x] There are definitions for each of the competencies can those definitions be added under the competency title or as a informational note you can click on? 
Customer Service: The ability to accurately identify and determine customer needs and take appropriate actions or steps to address identified needs.

Cultural Competence:  The ability to recognize, value and include different perspectives, experiences, approaches and cultures in achieving organizational goals.

Dependable & Trustworthy:  The ability to gain and maintain the trust and confidence of others and the organization through consistency and reliability.

Effective Communication:  The ability to give, receive, or share thoughts, ideas, perspective, and data to create a shared understanding.

Problem Solving:  The ability to define, analyze and find solutions for difficult or complex problems.
>Added this to the page
![image](https://user-images.githubusercontent.com/21112975/170580317-3c90e66a-d7d8-4aab-ae52-0f7fb2ccdfa3.png)

- Missing Mid Year and Overall Competencies Comment Section
>They are there, but look different in the system
![image](https://user-images.githubusercontent.com/21112975/170580579-d6216bde-0df7-46ec-a909-c0feab319b24.png)

**Employee Development Plan**

- Like the table display better

- [x] How can these important instructions be included: 

Discuss appropriate development opportunities with the employee; it is not required to have an entry for each section.  For each opportunity you include please provide:
WHAT: what is the activity; describe the development activity (i.e. department-specific training, classroom, online, coaching, job shadowing, etc)
WHY: why is it important; what is the competency, performance/department goal, and/or employee development goal that will be addressed by this activity
WHEN: when will the activity start and/or be completed
>I added them to a "new Employee Development Plan" form
![image](https://user-images.githubusercontent.com/21112975/171277998-3f8fef87-80dd-4c8a-a246-e31cb70a3185.png)

**Add SSPR Meeting Section:**

- Love this section and having all the different meeting options here

- [x] For Meeting Type Planning Meeting:

There is no rating for this meeting type but there are items to check to verify they were covered during the planning meeting. 
Can these be added if Meeting Type = Planning Meeting:
This is to acknowledge that my supervisor and I have discussed: 

- Major job responsibilities, competencies and performance expectations including but not limited to the contents of this SSPR plan. 
- Employee development plan.
- Department policies and procedures regarding workplace safety.
- 
![image](https://user-images.githubusercontent.com/21112975/171283175-3f4cae90-b68c-4674-b18c-7f4e973b9335.png)

**Concerns**

How are we going to handle the Supervisor/Manager and Executive SSPR?
It seems the only differences are Title and cumulative/additional Competencies.

**Supervisor/ Manager Competencies**

- Leadership:  The ability to inspire, motivate and influence others to achieve individual and collective goals.
- Decision Making:  The ability to make sound decisions in a timely manner that solve issues and stand the test of time.
- Planning Priorities:  The ability to recognize, plan, focus upon, and work toward what is important or critical.
- Employee Development:  The ability to recognize strengths and areas for improvement in others and to provide opportunities, guidance, and encouragement to build skills and capacity.
- Conflict Management:  The ability to recognize, manage, and resolve conflict efficiently and equitably.

**Executive Competencies**

- Boundaryless Perspective:  The ability to see a broad view of an issue or challenge across typical organizational lines and beyond the present.
- Purpose and Vision:  The ability to create, convey, and instill a unified vision and purpose.
- Strategic Thinking:  The ability to see past the moment and adapt to a rapidly changing environment.
- Achieve Results:  The ability to achieve organizational goals and objectives.
- Politically Savvy:  The ability to navigate relationships involving complex, emotional, and/or value-based issues in order to influence and achieve positive results.

**Comment by dianamartin** [comment]
## Supervisor Title
@moorerst I added the "Supervisor Title"
![image](https://user-images.githubusercontent.com/21112975/171285960-1e6e40e5-eeec-433d-8b40-e6f1b4bd0fb2.png)

## City of Austin Vision
- is only showing up once for me, I did update the page to be hidden under certain statuses, perhaps you didn't refresh after I had made the change.
![image](https://user-images.githubusercontent.com/21112975/171286009-175f2e26-c34b-4d35-b586-296e4afb726e.png)

**Comment by dianamartin** [comment]
I think we'll need to discuss this:

## Concerns

How are we going to handle the Supervisor/Manager and Executive SSPR?
It seems the only differences are Title and cumulative/additional Competencies.

### Supervisor/ Manager Competencies

    Leadership: The ability to inspire, motivate and influence others to achieve individual and collective goals.
    Decision Making: The ability to make sound decisions in a timely manner that solve issues and stand the test of time.
    Planning Priorities: The ability to recognize, plan, focus upon, and work toward what is important or critical.
    Employee Development: The ability to recognize strengths and areas for improvement in others and to provide opportunities, guidance, and encouragement to build skills and capacity.
    Conflict Management: The ability to recognize, manage, and resolve conflict efficiently and equitably.

### Executive Competencies

    Boundaryless Perspective: The ability to see a broad view of an issue or challenge across typical organizational lines and beyond the present.
    Purpose and Vision: The ability to create, convey, and instill a unified vision and purpose.
    Strategic Thinking: The ability to see past the moment and adapt to a rapidly changing environment.
    Achieve Results: The ability to achieve organizational goals and objectives.
    Politically Savvy: The ability to navigate relationships involving complex, emotional, and/or value-based issues in order to influence and achieve positive results.
