### ISSUE TITLE
Moped Project table shows Construction start date as a day earlier than entered in Timeline

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#9169]
**BUG:** 
After updating the Project Status from the Timeline tab, the project shows a Construction start date one day earlier in the Projects table. 

**URL**
https://moped-test.austinmobility.io/moped/projects

**Screenshots**

Projects: 
![image](https://user-images.githubusercontent.com/100615928/168900382-529461ba-b9d8-4e60-a0fc-eab97d261d66.png)

Dashboard/Projects table: 
![image](https://user-images.githubusercontent.com/100615928/168900531-c656c6f4-ebcb-42fd-8d8f-9dd38d6419b0.png)

**Device**
Macbook 2017 

**Browser**
Chrome 101 on Monterey 

**Additional context**
Found while testing Moped 1.3

**Comment by mateoclarke** [comment]
May be related/duplicate: https://github.com/cityofaustin/atd-data-tech/issues/5732

**Comment by mddilley** [comment]
Dates are coming back correctly from the backend. Need to modify the formatting happening on the front end, and I think that adding a helper could help us in the future for whenever dates come from the backend in `YYYY-MM-DD` format.

**Comment by mddilley** [comment]
This came down to handling date types (fields like `start_date` and `end_date` that store only a date from a picker UI) and time stamp with time zone types (fields like `date_added` and `created_at` that capture a moment in time for the activity log or record creation) with distinct formatting helpers.

Thanks to @tillyw and @johnclary for good docs in https://github.com/cityofaustin/atd-data-tech/issues/7121 and https://github.com/cityofaustin/atd-data-tech/issues/5732 so I could wrangle the bugs. Maybe we could update the backend date types to timestampz type in the future, but it doesn't seem necessary at the moment. Hopefully the helpers will prevent 🐛 🐛 🐛  in the future 🤞.

```
Code sample adapted from John's doc

// sample input for date type from moped
const date = "2022-01-15"
// Method to handle date type from the DB to display in the UI
new Date(date).toLocaleDateString("en-US", { timeZone: "UTC" });

// sample input for time stamp with time zone type from DB (generated from [PostgreSQL `now()` or `clock_timestamp()` functions](https://www.postgresql.org/docs/current/functions-datetime.html))
const timestampz = "2021-04-23T22:42:12.102357+00:00"
// Method to handle time stamp with time zone from the DB to display in the UI
new Date(date).toLocaleDateString("en-US");
```
