### ISSUE TITLE
Data model modifications

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#917]

**Comment by SurbhiBakshi** [comment]
- [ ] On Officer Assignment Detail page, make Start Assignment and End Assignment Bold (and perhaps different colors) to match rest of list, but also highlight function.
- [  ] Change Ongoing as a status option to In Progress.
- [  ]

**Comment by amenity** [comment]
- _**Knack time stamps are an hour ahead. Not sure if something needs to be changed on our end for Fallback?**_
Yes, these need to be corrected to CST. @johnclary @dianamartin - do y'all have a method for this?

- _**For no violation reported in the last 15-20 minutes, is an e-Citation created at all? If not, what would be a good term to use as a default for those records? 'NA'? I see this as an valuable contribution to future reporting needs.**_
It is valuable, for sure and "not applicable" makes sense. @dianamartin @johnclary - do we have a standardized way to write "n/a"

**Comment by johnclary** [comment]
@amenity @SurbhiBakshi you can set the timezone and daylight savings settings in the app's main settings. but it appears to already be set correctly. you sure this is an issue?

**Comment by dianamartin** [comment]
@amenity I don't think we have a standard way of writing "N/A", but having it all typed out "not applicable" is descriptive to the point.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/1b1daa0c-5360-405e-ba90-3d90320e4308)

**Comment by SurbhiBakshi** [comment]
@johnclary  it took me some time to get back to the Time Stamps issue, looks like the Contact Time coming from the application user interface is right, but the Created Date time stamp from the Record rules is an hour ahead. The created data isn't seen anywhere, but I wasn't sure why this is happening. 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/f8d45d81-469b-42e1-b600-a580ddb6f02e)

**Comment by johnclary** [comment]
strange. maybe try changing the app time zone setting to else and then changing it back again? i would also add another date/time field on the object temporarily and see if that's being set properly.
