### ISSUE TITLE
Figure out "Account" & "Provider" creation process

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9179]
Account management for providers.

**Comment by dianamartin** [comment]
- Renamed "Account Management" tab to "Accounts" - was quite a large label
- Created a separate page under Accounts for Provider Accounts, this page is for Reviewers to see the new provider accounts they create
- Updated the "Add Account" form to include "Company" (Provider) connection to choose or create a new Provider at the same time as creating an individual account

**Comment by dianamartin** [comment]
When I was testing the new account, new provider process I noticed a bug. The attachments were correct when I was going through the application process, when I clicked "Save for Later" button the attachments update to 11 and 12. I checked the rules and it was incorrect, so I updated them.

**Comment by dianamartin** [comment]
Showed stakeholder on 5/20, no feedback modifications Closing.
