### ISSUE TITLE
Delete extraneous test environments in Knack

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#918]
We need to have prod, test, and ESB environments for each Data Tracker and Signs and Markings. Nothing else. :)
- [x] Diana document September 10 Signs and Markings
- [x] Diana delete September 10 Signs and Markings
- [x] Diana document 2019 02 07 Data Tracker
- [x] Diana delete 2019 02 07 Data Tracker
- [x] Diana delete JD's performance Nov 4
- [x] Surbhi is going to get rid of 24 July after troubleshooting https://github.com/cityofaustin/atd-knack-signs-markings/issues/253
- [x] Create new Signs and Markings test env and share with JD

**Comment by dianamartin** [comment]
@amenity @SurbhiBakshi I deleted all the documented and deleted the environments I needed to. Let me know when you're done updating the Signs and Markings app in Prod so I can make a new Test environment. We'll have to also tell Kati and Christina.

**Comment by dianamartin** [comment]
Talked to John yesterday to confirm we'd be okay copying the Signs and Markings PROD environment without having to worry about the record counts. I started the copying process before I left.

**Comment by dianamartin** [comment]
So the app is done copying, however, it's now not showing up on the app list in the main builder account. I've opened a ticket with  Knack.

**Comment by dianamartin** [comment]
Knack has resolved this issue, the application was showing up on our main builder page.
