### ISSUE TITLE
Email Configuration for SMRT

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9180]
Configure "Application Submission email" for applicant - when they submit their application finally

**Comment by dianamartin** [comment]
I checked is an email was configured for when the applicant submits and it is configured. I just have the emails being sent to me right now. 

![image](https://user-images.githubusercontent.com/21112975/169125798-c1c6a8c3-52ad-49ed-8573-fd85b2179c21.png)

**Comment by dianamartin** [comment]
Updated link for: 
![image](https://user-images.githubusercontent.com/21112975/169570434-1dab0ace-5ff8-4f32-8d5c-3192752387c9.png)
- Should be directing to: `View your application on My Application details page`
