### ISSUE TITLE
My Application Details page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9181]
Add "Approval Letter" button on My Application details page (when "Approved"?)

**Comment by dianamartin** [comment]
Configured a new menu to appear on the My Applications Details page
- Only shows in "Approved" Status

![image](https://user-images.githubusercontent.com/21112975/169155276-81833896-62d8-4dd4-9de2-d794891f6695.png)

**Comment by dianamartin** [comment]
Showed stakeholder on 5/20, no feedback modifications Closing.
