### ISSUE TITLE
Edit N FM 620 RD NB, N FM 620 RD SB 

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#9182]
[ID not reported]: N FM 620 RD NB, N FM 620 RD SB, see imageComment This is a complex edit. Either the entire section gets re-created, or the polygon is split and edited to fit. New polygons would likely still need to be created.

**Comment by patrickm02L** [comment]
Going forward VZ GIS staff will be able to make edits in MAINT, which will publish to this public [AGOL map](https://austin.maps.arcgis.com/apps/mapviewer/index.html?layers=f9db1ee0aaa2438284154ccc47302eb5).
