### ISSUE TITLE
Add Oldham St

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#9187]
Oldham St is Missing in Polygons (Between E. Dean Keeton & Red River)

**Comment by patrickm02L** [comment]
Going forward VZ GIS staff will be able to make edits in MAINT, which will publish to this public [AGOL map](https://austin.maps.arcgis.com/apps/mapviewer/index.html?layers=f9db1ee0aaa2438284154ccc47302eb5).
