### ISSUE TITLE
Add Clayton Lane

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#9191]
Missing Clayton Lane (btwn Middle Fiskville & Thomas Hatfield)

**Comment by alan-deanda** [comment]
Clayton Lane was added by moving existing polygons from where Clayton and Highland Mall Dr used to be.
It's probably okay to re-align polygons from the same road, but what about polygons from other roads that don't exist anymore?

**Comment by alan-deanda** [comment]
Self assignment:

There are many roads in the re-developed highland mall that need to be added, retired, or re-purposed.

**Comment by patrickm02L** [comment]
Going forward VZ GIS staff will be able to make edits in MAINT, which will publish to this public [AGOL map](https://austin.maps.arcgis.com/apps/mapviewer/index.html?layers=f9db1ee0aaa2438284154ccc47302eb5).
