### ISSUE TITLE
Discuss potential approaches and scope spike

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9197]
Possible hosting solutions for a reimagined testing environment have been discussed. They are AWS & the DTS on-prem servers. Evaluate these options and formulate a route forward. Write this plan up in the form of issues in the parent epic of this issue and present them to the group for consideration.

**Comment by amenity** [comment]
@frankhereford - please schedule

**Comment by frankhereford** [comment]
Invite has been sent, tentatively meeting 2PM on 5/24.

**Comment by frankhereford** [comment]
### Brainstorming Up Some Ideas

I am looking forward to our conversation, and I don't want to set anything too firm down as an agenda because I hope that we are all comfortable to brainstorm and thinking outside of the box in terms of what we have grown accustomed to in a CI cycle, but here are some ideas we can bat around if we need them:

* On-prem vs. AWS vs. something nouveaux like koyeb.com
  * If AWS, do we want to use EC2 to provide us ephemeral servers, or do we want to use the more managed stuff like ECS & RDS, Route 53 for custom domains. BTW, I have `moped.app` domain for us if we want to use it, and I'd happily donate it to the group to own. Imagine `frank-test.moped.app` for frank's testing purposes, `yourname-test.moped.app` etc - so we can all have one. 
  * If AWS, tiny throw away servers each with one deployment on (imagine the app installed in "`/var/www`) vs. bunches of npms reversed proxied out by haproxy / nginx or something along those lines.
* Should deployment be scripted and executed by GitHub's workflow service or scripted as a prefect flow
* Do we want to generalize this process so we can spin up more environments then just `test`? 
* Do we want to be thinking of feature branches each with their own DB?
* Does the database want to live in a docker container à la local development or RDS?


### Stepping back, we can ask ourselves:

What problem are we trying to solve?
What goals do we have? 
What is the balance between aspiration and speed to deliver this product?

**Comment by mateoclarke** [comment]
Going to close this out and move the next stage of discussion to the new spike issue:
https://github.com/cityofaustin/atd-data-tech/issues/9261
