### ISSUE TITLE
Publish updated Census-based data to ATD's AGOL

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9198]
We use Census data for a lot of analysis. Added the following updated data resources to ATD AGOL. 
- Tracts for Travis and surrounding counties
- "Central City" geometry

**Comment by andrewshensky** [comment]
This data has been published to AGOL and is available through the link below:
https://austin.maps.arcgis.com/home/item.html?id=6ee0881724a141aea40bf511b5e0e086
