### ISSUE TITLE
Look into performance impact of our custom JS in Signs and Markings app

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#920]
Users [reported some significant performance issues in the the Signs and Markings work order app](https://github.com/cityofaustin/atd-data-tech/issues/832).

We got [feedback from Knack](https://github.com/cityofaustin/atd-data-tech/issues/832#issuecomment-549155467) on what they consider to be contributing factors and also had @zappfyllc dig into it. 

JD noticed a [couple of areas](https://github.com/cityofaustin/atd-data-tech/issues/832#issuecomment-550386948) where our custom Javascript might be impacting performance. It would be great to have a dev familiar with this code investigate this so we can implement fixes, document best practices, etc.

**Comment by johnclary** [comment]
@mateoclarke @mddilley can y'all pick up this issue this week? i was running some tests this morning, and signs work order is running really slowly. the main issue i noticed was when adding or deleting locations, which took ~20 seconds. i'm guessing it's the knack API that's choking, but would like y'all to confirm.

@dianamartin can point you to the current test env.

**Comment by johnclary** [comment]
I'm noticing the same issue when adding asset information to the sign word order details > location details page. So I don't think this is unique to the map UI.
