### ISSUE TITLE
New Account: LIT Developer Nandhini (Check on VPN Status)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9202]
Nandhini 

---- 
Click edit to view her full name & phone number.

**Comment by Nadin-Nader** [comment]
@TracyLinder need more ifo on new Developer in order to create their account.

**Comment by Nadin-Nader** [comment]
Added the account to AMANDA TEST and set the automation to create it on PROD. I also created the TASK to have the account created in V7 **_SCTASK0222260_**

Only thing left is to change or create the admin version of the account if needed

**Comment by Nadin-Nader** [comment]
Not going through with Hiring Nandhini
