### ISSUE TITLE
Add Welcome Header component to Dashboard

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9204]
- [x] Add welcome phrase that is aware of the time of day and the current users name
- [x] Add day of week and current date.

![Dashboard – 9014](https://user-images.githubusercontent.com/5697474/169150650-ab8ba469-fe36-4f5f-b513-f36f7cdea716.png)

**Comment by tillyw** [comment]
closed via https://github.com/cityofaustin/atd-moped/pull/663
