### ISSUE TITLE
Review project template progress with AMD

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9207]

**Comment by amenity** [comment]
@amenity - please schedule. Chia, Mateo, other devs optional.

**Comment by johnclary** [comment]
me too, please :)

**Comment by mateoclarke** [comment]
Here are some notes I took from this meeting:

- Ordering change got a big 👍  from Ivonne 
  - they like the new default ordering regardless of dates in the Milestones
  - Drag & Drop sorting requested (in the backlog [here](https://github.com/cityofaustin/atd-data-tech/issues/8524))
  - This is bc after the template milestones are created, any new milestones added get sorted to the bottom.
  - John highlighted that you can't get the default sorting back. Workaround is to refresh the page. We can discuss in grooming whether to make a backlog issue.
- Renée asekd about the connection b/t phases and milestones
  - JD had thought about automated workflows and triggers (ex: change current milestone, update a current phase)
  -  #3673  could help with this
  - For now, a column on milestones with a related phase would help. (@chiaberry tackling this within current PR)
  - possibility to filter milestones by phase
- Renée shared some early versions of workflow diagrams that AMD is working on to formalize their processes. 
- Discussion of moving forward with Phase templates, building on success from Milestone templates
  - New issue: https://github.com/cityofaustin/atd-data-tech/issues/9255
- AMD will work on templates for other project types. They don't know much about the Fiber process. But maybe RRFB (Rectangular Rapid Flashing Beacon)
- Discussion about adding help text vs a "are you sure" modal to prompt users into using Project Types
  - new issue created: https://github.com/cityofaustin/atd-data-tech/issues/9258
- Discussion about applying the Milestone templates on existing AMD projects.
  - new issue: https://github.com/cityofaustin/atd-data-tech/issues/9257
