### ISSUE TITLE
Create foreign key relation between moped_proj_milestones and moped_milestones

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#9208]
The moped database has lookup tables for the phases and the milestones
![Screen Shot 2022-05-18 at 4 55 35 PM](https://user-images.githubusercontent.com/12474808/169162442-a8efc17b-a6a6-4e93-a7c0-82b21a3afcf8.png)

However, we do not reference these tables in the moped_proj_milestone table nor the moped_proj_phases table and instead store the milestone/phase name directly in the column. 

![Screen Shot 2022-05-18 at 4 56 55 PM](https://user-images.githubusercontent.com/12474808/169162562-f0b0f45a-0272-405f-bf70-2a077fa17cd2.png)

These tables need to have a foreign key relation between them. 

We compare the milestone name that is stored in the moped_proj_milestone table to the moped_milestone text, so any updates to the milestones, this needs to be reviewed after updates to the tables. 
https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/views/projects/projectView/ProjectTimeline.js#L127

**Comment by chiaberry** [comment]
@amenity Are there any columns I should remove while I am making changes to the moped_proj_milestones table (https://db-docs.austinmobility.io/atd-moped-production/tables/moped_proj_milestones.html) like milestone_privacy or milestone_priority? or leave them all as is?

**Comment by amenity** [comment]
@chiaberry - I see several that could go but want to check w/ Nathan first. Started a doc [here](https://docs.google.com/spreadsheets/d/17gYrf79rj_wHDkOH-kJ6oh-TLv9dLD8dVqD3OaeY4Ss/edit#gid=1248155997).
