### ISSUE TITLE
[DATA] Import the remaining Traffic Regulations records into Traffic Register

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9217]
Chrispin and I sync on 5/19 and suspected that not all regulations were imported into the Traffic Register. We did find a [spreadsheet](https://drive.google.com/drive/folders/17GnQTov9Szyp7Lj1FMx7t5zChi84sopt) from Jan 2022 that has all raw regulations. We converted it to a Google Sheet to determine how many records were in there. There were about `45k` records and in the system we only have `~500`. 

We need to figure out how to import the regulations correctly. We suspect we might need to ask John his recommended steps to do this.

**Comment by dianamartin** [comment]
# Meeting "Traffic Register - Regulations Import sync"
Participants: John, Chrispin, Diana
- Demoing Draft Package

Added more information on the:

## Package Builder 
- must connect regulations to draft package number
- 
## Review page
- Allow builder activities on it (if not "Approved")
- Showing table of Approve regulations connected to the draft regulations

## Import Steps
- Access DB - Approved Regs, Retired Regs
- will go into canvas object and approved object

**Comment by dianamartin** [comment]
# Imported Data History
- subset of traffic regulations
- Clean up
Took from the access db and parsed out the fields in order to import into knack

**Comment by johnclary** [comment]
I created https://github.com/cityofaustin/atd-data-tech/issues/9270 for my task

**Comment by ChrispinP** [comment]
Finished prepping all 38 spreadsheets and prepping all fields in the Traffic Register. I updated Line Item ID and text formulas to accommodate the data. Short text fields added for all Connection fields to maintain data integrity should something not connect, data is inaccurate, for text formulas, and the ability to duplicate and update records for all the additional Retire records that must be added afterward.

There is a huge discrepancy in the data regarding the Retired Regulation specified. Created a new field `Retired or Replaced With Regulation` short text to dump these values in until I can run a query to determine if they are the `Retired Regulation` vs the` Replaced With Regulation`

Completed first import of all ANGLEPARK regulations into the regulation_approved object. All connections were successful for all 160 records. Will continue to import the remaining regulations.

**Comment by ChrispinP** [comment]
**To Import into regulation_approved**

- [ ] ANGLEPARK
- [ ] BIKELANE
- [ ] BUS STOP
- [ ] CABZONES
- [ ] COMMSRZN
- [ ] CONSTSPD
- [ ] CUSTSRZN
- [ ] EXCLUSIVEZN
- [ ] HANDICAP
- [ ] LIMOMVNT
- [ ] LOADZONE
- [ ] MISCPARK
- [ ] NBIKESAT
- [ ] NOTRUCKS
- [ ] NPATALLY
- [ ] NPATSTRT
- [ ] NPBIKELANE
- [ ] NPSPECHR
- [ ] ONEWAYAL
- [ ] ONEWAYST
- [ ] PARALLEL
- [ ] PASSZONE
- [ ] PAYSTATION
- [ ] PHBSIGNAL
- [ ] PRKMETER
- [ ] RESPARK
- [ ] REVERSE LN
- [ ] STOPSIGN
- [ ] TIMEPARK
- [ ] TOW ZONES
- [ ] TRAINSPD
- [ ] TRSIGNAL
- [ ] TRUCKRTE
- [ ] TURNPRHB
- [ ] TWOWAYLT
- [ ] VALET PARK
- [ ] YIELD SIGN

**To Import into regulation_canvas**

- [ ] ANGLEPARK
- [ ] BIKELANE
- [ ] BUS STOP
- [ ] CABZONES
- [ ] COMMSRZN
- [ ] CONSTSPD
- [ ] CUSTSRZN
- [ ] EXCLUSIVEZN
- [ ] HANDICAP
- [ ] LIMOMVNT
- [ ] LOADZONE
- [ ] MISCPARK
- [ ] NBIKESAT
- [ ] NOTRUCKS
- [ ] NPATALLY
- [ ] NPATSTRT
- [ ] NPBIKELANE
- [ ] NPSPECHR
- [ ] ONEWAYAL
- [ ] ONEWAYST
- [ ] PARALLEL
- [ ] PASSZONE
- [ ] PAYSTATION
- [ ] PHBSIGNAL
- [ ] PRKMETER
- [ ] RESPARK
- [ ] REVERSE LN
- [ ] STOPSIGN
- [ ] TIMEPARK
- [ ] TOW ZONES
- [ ] TRAINSPD
- [ ] TRSIGNAL
- [ ] TRUCKRTE
- [ ] TURNPRHB
- [ ] TWOWAYLT
- [ ] VALET PARK
- [ ] YIELD SIGN

**Comment by ChrispinP** [comment]
1 Stop Sign Reg didnt connect because it was lowercase > fixed
Finishing update for unique Doc + Reg ID, once done I will be able to investigate why there is one extra Tow Zone record.

**Comment by ChrispinP** [comment]
**Phase 2 Complete:** All Approved Regulation records imported into the `regulation_approved` object and all record values updated. Given the `Approved & Installed` status.

**Phase 3 Complete:** All 14,532 Approved Regulations marked as deleted were exported and re-imported as Retire records with a unique status, `Retire Approved`. `Retire Date` on the Install records became the de facto `Approved Date` for Retired records. The unique `Reg Doc + Line Item ID` became the de facto `Retired Regulation` ID as well to connect them to their Installs. Original records updated to `Retired & Uninstalled` and marked as Retired and Uninstalled.

**Phase 4:** Export all 59,802 Approved Regulations and compile records as the "Master List". Re-import into `regulation_canvas` object.

**Comment by ChrispinP** [comment]
Phase 4 is now Complete. Final Update will be done by EOD.

Ready to Review & Close

**Comment by dianamartin** [comment]
Closing as all records have been imported.
