### ISSUE TITLE
Disable CCTV Image Publishing on 11/20 from 1pm to 4pm

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#922]
Due to VIP visit we have been asked to disable CCTV publishing from 1pm to 4pm on 11/20.

We did this recently, described here:
https://github.com/cityofaustin/atd-data-tech/issues/811

**Comment by johnclary** [comment]
@SurbhiBakshi can you plan on taking care of this? happy to walk you through it.

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/a8396d13-5707-46a4-9d47-301ca4242220)


![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/d118b76c-0643-4c67-a943-0ef1ebce0bee)

**Comment by SurbhiBakshi** [comment]
26
27
28
31
38
43
44
45
46
54
156
366
537
567
571
612
613
614
616

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/e02ebc36-1241-42b2-8fa1-fbed4bc26211)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/73a7ca98-721c-42dc-8332-c55e2f123670)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/626b0b01-b325-4962-a03a-965aadaee51c)

**Comment by SurbhiBakshi** [comment]
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/338d6012-8f10-4b7f-80ef-50eb8f0f77d1)
