### ISSUE TITLE
Conduct Usability Testing for DOLA

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9222]
Plan to have Christina, Tim S., and Patrick do testing before 6/10/22.

Testers will get link to access new application. The submitted application will go to SMS staff for review, and go permitting team for review. 

- [x] Create accounts for testers and associate to test provider companies
- [x] Script for what users will need to test for in Moderated testing.
- [ ] Notify SMS team
- [ ] Make sure SMS team is managing their email to respond to user testing
- [ ] Update emails to go to active users

Target date Jun 1, 2022 (placeholder)

**Comment by dianamartin** [comment]
5/26
I created [testing script](https://docs.google.com/document/d/1qYyCoosH2ehkrt9Ig0UeItADjVTI3mD9dqZ89ZhfFGw/edit#heading=h.66dyvc9d3nhx) and [testing personas](https://docs.google.com/presentation/d/1nvTjDYGBj-O_yJNGgdPsm5hEScnMNGYPE-MXVpzE2DA/edit#slide=id.p) for testers

**Comment by patrickm02L** [comment]
Tenitative testing times.

6/7 @ 11am - Susanne or Patrick
6/7 @ 2pm - Tim
6/8 @ 11am - Christina

On the 9th, share usability testing results with SMS staff.

**Comment by patrickm02L** [comment]
@dianamartin can you make updates based on the initial [user testing](https://docs.google.com/document/d/1J7IMbBWDQ7y16bXWgJ1L2kSmRTBvKIalamJ1jhXT178/edit#).

**Comment by dianamartin** [comment]
## Do This 
- [ ] Business Structure - Other, display rule
- [ ] Attachment "Status" - rule 
- [ ] Created Date <--> Modified Date
- [ ] Email to user when submission completed - update URL to My Application
- [ ] Add "Sort Id", rename on Required Attachment table
- [ ] Test button in statuses for Customer Action

**Comment by dianamartin** [comment]
We completed our usability testing/training with the SMS team at our 6/17 meeting. They created provider contacts and provider accounts. Showed how to link and unlink accounts.
