### ISSUE TITLE
[Enhancement] - PSM Info Type Change - # of Bolts

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9224]
### Ordnance update removed the # of bolts limit. This info needs to allow any number value. 

- Note from Tracy: Will changing the info type cause us to loose any data? If yes let me know please.

**Comment by TracyLinder** [comment]
This issue was generated during a sprint review w/ ROW and requested by Paloma.

**Comment by vschandramouli** [comment]
@TracyLinder Confirmed from Priya that changing the info type will not affect any historical data. 

This card is a duplicate of #11929 , which is currently in Ready to Deploy status. 

I am closing this card.
