### ISSUE TITLE
Test new paging activity field mappings

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9238]
Conduct end-to-end testing of the new Data Tracker [field mappings](https://github.com/cityofaustin/atd-data-tech/issues/8956) for paging activities.

**Comment by johnclary** [comment]
We're waiting to hear back from Robert / ESB team. See communication in https://github.com/cityofaustin/atd-data-tech/issues/8956.

**Comment by johnclary** [comment]
I followed up with CTM and asked if they're available to meet to review this next week.

**Comment by johnclary** [comment]
We tested on 6/9, but unfortunately the ESB was not cooperating, and we were fully down in test and prod at the time we were trying to test :/

I've scheduled another session for 6/17, and I followed up with Robert F. to see if he could try to push a test message through to the AMD test environment in the meantime.

**Comment by johnclary** [comment]
We met again today. We discovered that the flex note field maps were not configured correctly. Robert was just able to fix that. He's still working on configuring the activities. We're working async on teams.

Once the inbound activities are sorted, we'll need to decided what the "stop paging" UI should look like. i'm going to make a separate issue for that @dianamartin

**Comment by amenity** [comment]
Thanks for doing this, @johnclary! Will you adjust the pipeline and label sprints, please?

**Comment by johnclary** [comment]
✅ i followed up with Robert on teams to ask if he resolved the activity field maps

**Comment by amenity** [comment]
@johnclary - should this go in Review/QA?

**Comment by amenity** [comment]
@johnclary - still waiting to hear back from 311 on this?

**Comment by johnclary** [comment]
Robert and I met today to review the activity field mapping. It seems to have clicked. He's going to work on it and asked to reconvene at the end of next week. I scheduled another work session for 11/4.

**Comment by johnclary** [comment]
we did this—the tests we're good. we have data flowing for these activities. there may be a few small follow-ups to the inbound mappings for activities. but i'm calling this done.
