### ISSUE TITLE
Configure Data Tracker UI to close paging activities

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9239]
Configure the Data Tracker to enable staff to search, view, and close paging activities in Data Tracker. The activity will be sent through existing integration to ESB/311. Thereby closing the paging activity and halting the paging.

**Comment by johnclary** [comment]
@dianamartin FYI this may be a dupe if you captured your work in another issue...

**Comment by dianamartin** [comment]
DUP of #9960, Closing
