### ISSUE TITLE
Create import template for Traffic Register - Admin backfill

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9248]
Create import spreadsheet template for Admin team to populate Traffic Regulations to be able to import into the new Traffic Register application. 

Phase 1: 2019 - 25 records
Phase 2: 2020 - 95
Phase 3: 2023 - 264

**Comment by ChrispinP** [comment]
Created 2 Template excel files, one for Packages, and the other for Regulations. Pending review and any further changes before sending to Admin.

**Comment by ChrispinP** [comment]
Templates updated after today's meeting as the chosen data entry method and emailed to stakeholders to begin.

complete, closing
