### ISSUE TITLE
Populate existing Production projects with milestones

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9257]
Write a one-time use Python script that lives moped-toolbox to add all the project templates except those that have the current phase as "Completed" or "Post-Construction"

This could be done by directly connecting to the DB with psycopg or via a Hasura mutation. (https://github.com/cityofaustin/atd-moped/blob/2bb0af7b5997fae06162b68343ec53f29396f036/moped-toolbox/knack_migration/utils.py#L10)

These are the phases that need to be inserted in moped_proj_phases for each project. 
https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/utils/timelineTemplates.js

**Comment by chiaberry** [comment]
Checking the read-replica, there are 213 total moped projects. 22 do not have types associated with them (4 of those have variations on "test" as the project title)

**Comment by amenity** [comment]
Ivonne and Renée and would like _all_ projects except those that have the current phase as "Completed" or "Post-Construction"

**Comment by johnclary** [comment]
For reference, [this function](https://github.com/cityofaustin/atd-moped/blob/2bb0af7b5997fae06162b68343ec53f29396f036/moped-toolbox/knack_migration/utils.py#L10) makes a hasura request.

**Comment by johnclary** [comment]
I asked Renee and Ivonne on teams:

> Ivonne we're getting ready to work on backfilling the milestones for existing projects. question for you: It looks like a handful of your projects do not have a "Project Type". Do you want to review those before we proceed? Only projects that are New/Mod PHB/Signal will be updated with milestones
> 
> Also, what should we do if a project already has one or more milestones? We don't want to duplicate anything. Can we skip those projects?

**Comment by johnclary** [comment]
per Ivonne
> We are ok with overwriting existing info, just don't bother with projects completed or in post-construction. Thank you.

**Comment by johnclary** [comment]
It's done! I let Renee and Ivonne know that we updated 150 projects with missing milestones.

**Comment by amenity** [comment]
Sweet! Thank you, @johnclary
