### ISSUE TITLE
Project: VZ Polygon Maintenance

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#9260]
The Vision Zero team uses a set of polygons to collect and analyze crash data. The polygons were originally generated from the 2019 ASMP Streets data, and the polygons need maintenance to fix coverage errors and to keep up with Austin's growth. This project tracks all GIS work in creating a maintenance process, establishing rules for making edits at scale, and the maintenance of the polygons itself.

![VZ-polygons](https://user-images.githubusercontent.com/5566727/203077723-f991409e-1bbf-44bf-bf78-830caf1ca968.png)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by patrickm02L** [comment]
The work for this project was tracked in #8388. We identified an opportunity for future GIS VZ staff to make edits directly to MAINT #11003 going forward and consider this project complete.
