### ISSUE TITLE
Feature: Manage Street page (Traffic Register)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9275]
Need to create "Manage Streets" page so that the admin team can update the Street Names that aren't on the list. 

Similar to the Signs and Markings [page](https://atd.knack.com/signs-markings#manage-street-names/). 

![image](https://user-images.githubusercontent.com/21112975/170330151-4db529b8-079b-4bf4-98a9-ad63eefe8dca.png)

**Comment by dianamartin** [comment]
@ChrispinP This should have some instructions to use the GIS [street segment look up web map](https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=c06c383726d64640a2abc7dc592d4517) or something, we don't want them to enter things in incorrectly.

**Comment by ChrispinP** [comment]
to prevent incorrect entry we can auto-capitalize the field and use regex validation. The most likely scenario is that the street being entered is a newly formed street that a street segment map may or may not have. We do need to come up with a plan for updating this street list with updated street segment data.

**Comment by ChrispinP** [comment]
Street Map Lookup button added
![image](https://user-images.githubusercontent.com/67915167/173938396-394e3a8b-dfd0-4392-9729-078df3bf0bd2.png)

closing as complete
