### ISSUE TITLE
Feature: Make values entered into "Sign Type" field - All Caps

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9276]
## When a user is filling out the field "Sign Type" while creating a new regulation, they must use the ALL CAPS key. Would like it if the field could enter values in All Caps automatically. 

This was discussed at the last meeting on 5/23 - `Traffic Register - Admin backfill scoping` - #9421

**Comment by ChrispinP** [comment]
added JS to convert Sign Type to Uppercase
![image](https://user-images.githubusercontent.com/67915167/171479582-73ac3c42-bd5e-450d-af70-a73da9609c8a.png)

Need to test and confirm working during a test draft

**Comment by ChrispinP** [comment]
tested and working, closing
