### ISSUE TITLE
Correct spelling of "transportation" from "transporation"

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9280]
A citizen (Tyler. M.) has submitted two emails via the Open Data Portal. He has observed that there is a misspelling in the `transportation` tag on the following datasets:

https://data.austintexas.gov/dataset/Street-Events/6cc9-pf63
https://data.austintexas.gov/Transportation-and-Mobility/Wifi-Travel-Sensor-Raw-EXPERIMENTAL-/eitg-njyb

**Comment by dianamartin** [comment]
Edit button on top right
Edit Metadata

**Comment by KaroEngstrom** [comment]
w 5/25/22

- [x] Corrected the tag on each of the datasets: 

![image](https://user-images.githubusercontent.com/100615928/170349626-83239b10-18a6-408a-8706-32daafc3e19a.png)

![image](https://user-images.githubusercontent.com/100615928/170349654-61361685-31d9-4c5f-8f91-6e7299c3a5b7.png)

- [ ] Check with Frank on how to contact the requester to let them know
