### ISSUE TITLE
Help Guide documentation for DOLA

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9282]
Write instructions for staff about how the Dockless Online License Application works. 

**Things to consider**
- Account Creation
- Submission
- Reviewing applications
- Commenting
- Updating statuses

@dianamartin please add additional sections to include.

**Comment by dianamartin** [comment]
Include:  
- [ ] Cheat sheet of statuses - GitBook
- [ ] SMS Reviewer Workflow

**Comment by dianamartin** [comment]
Started new "Help Guide" page for [Application Help](https://atd.knack.com/smrt#app-help/) and renamed the old Help page to ["License & Permit Help"](https://atd.knack.com/smrt#lp-help/), currently only accessible when signed in.

**Comment by dianamartin** [comment]
- [x] Updated the "App Help" page with all the check items
- [x] Created a new page "Customer Action Help" - the page that shows them how to correct a requirement

**Comment by dianamartin** [comment]
I removed "version 2" on the cheat-sheet page, so that it's cleaner in final view for stakeholders.

**Comment by patrickm02L** [comment]
Reviewed status color logic with Diana 08/17/22. Created alternatives that follow a visual progression through color gradients (rainbow themed). Drawings in [Miroboard](https://miro.com/app/board/o9J_l4LSuvE=/)

**Original**
![Screen Shot 2022-08-17 at 10.39.53 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/5cf669a2-a4b5-4eef-9aa0-202596482800)

**Alternatives**
![Screen Shot 2022-08-17 at 10.39.40 AM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/e0d54d54-52c1-44eb-a0d6-d1e132a4f56e)

**Comment by dianamartin** [comment]
@patrickm02L I've updated the [cheat sheet page](https://atd.knack.com/smrt#status-cheat-sheet/)

**Comment by patrickm02L** [comment]
Feedback from 08/17/22 grooming. Flip the the Blue and the Green statuses.

**Comment by dianamartin** [comment]
Also updated the "Application Status" background colors to the Application Dashboard table
![image](https://user-images.githubusercontent.com/21112975/185236415-592214bc-6745-44e4-82f5-fa6f19b2f8d0.png)
![image](https://user-images.githubusercontent.com/21112975/185236478-46d49292-117b-461a-b9c1-ee3869485e6c.png)

**Comment by dianamartin** [comment]
Met with stakeholders on 8/25 and they had not other feedback for us regarding the documentation.
