### ISSUE TITLE
Gather feedback on Shift Creator UI

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#929]
Meet with Lewis and Randy to review the interfaces we've built for them:

## Shift fields
- Shift Description
- Contact Name - essentially "created by"
- Equipment Required — ever multiple items?

## Assignment fields
- Location Description
- Number of Officers Required 

## Calendar
- What information would visible without clicking modal?

## Table
- Extraneous/additional columns? - "Assignments Available" "Assignments Filled"
- Names

**Comment by amenity** [comment]
@SurbhiBakshi - add any notes [here](https://docs.google.com/document/d/1E4Uul_wyAvfLILuC9mZBcXol_WMZZYXKt2_6qi9krJE/edit) and close this issue!

**Comment by SurbhiBakshi** [comment]
@amenity, don't think we need this issue anymore since the Shift Creation process has been removed from the app.

**Comment by amenity** [comment]
@SurbhiBakshi - I meant your notes about our meeting with Lewis. "Shift Creator" just meaning the role, not actual shifts.
