### ISSUE TITLE
[Bug] Component select / draw UI is hidden at narrower screen widths. 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9298]
<img width="750" alt="Screen Shot 2022-05-26 at 11 50 10 AM" src="https://user-images.githubusercontent.com/1463708/171212925-bb34a58e-ae70-44dd-82be-d23ac59ac647.png">
<img width="707" alt="Screen Shot 2022-05-26 at 11 52 14 AM" src="https://user-images.githubusercontent.com/1463708/171212933-d4197af0-00e6-4675-add8-f097d5ee89d2.png">

I see this as pretty low-priority given
- Most users won't have the browser window that narrow, and for now we don't expect people to be editing project components on mobile devices.
- @johnclary will be working with @mddilley on this interface and potentially refactoring the design, so no need to polish it before that.

**Comment by johnclary** [comment]
We fixed this with https://github.com/cityofaustin/atd-data-tech/issues/10399
