### ISSUE TITLE
Refine Shift Creator UI

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#930]
## Calendar
- [x] Make all blocks the same color - done. Visually it would help to have the text 'Bold' so it will stand out against a background, but this options doesn't seem to be available in the Calendar tools. @amenity didn't we discuss having a different color for shifts with zero unassigned slots versus shifts that needed assigned officers? 

## _Add a Shift_ modal
- [x] ![Screen Shot 2019-11-20 at 3 16 46 PM](https://user-images.githubusercontent.com/1463708/69358588-b449ba80-0c4c-11ea-903c-e944ee72af1e.png)
@amenity , the all day and repeat check boxes will need a CSS solution to disappear. 
## Shifts table 
- [x] ![Screen Shot 2019-11-21 at 10 52 12 AM](https://user-images.githubusercontent.com/1463708/69359792-e0663b00-0c4e-11ea-9bc5-c01320c9ce75.png)
- [x] Also make a filter "Upcoming" and "Past" - Default to upcoming
done, past is before today, upcoming is today and after.
## _Add an Assignment_ modal
- [x] ![Screen Shot 2019-11-21 at 11 30 07 AM](https://user-images.githubusercontent.com/1463708/69362227-bbc09200-0c53-11ea-9414-13ed4ca54d93.png)

- Note that we are going to try adding a second location field, per discussions around #898 .
@amenity this is done, and working. I have kept both versions of the form, the two locations for range and the earlier one with a single location for testing purposes.

**Comment by SurbhiBakshi** [comment]
- [ ] Enhancements to the location page to help with the street range issue.
[Screen Shot 2019-11-22 at 1.25.02 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/f8dd38d0-bb2c-4dad-ae07-76851aaae0df)

**Comment by amenity** [comment]
Ooh, like that, @SurbhiBakshi!

**Comment by amenity** [comment]
Can we make "All" the default?
