### ISSUE TITLE
Fairway / Montopolis - 63EC821F4A

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9302]

**Comment by frankhereford** [comment]
Feedback from Gavin J:

>WB approach driveway shows 2 RA crashes caused by LTC movements. Could you show a LTC symbol in these cases? See crash ID below:
>  * Section 232 – 16580995
>  * Section 232 – 15827964
>
>NB approach of Montopolis Drive crash ID ‎Section 229 – 18503177 was caused by a LTC movement that originated on the SB approach of Montopolis Drive. Display crashes like this at the approach that failed to yield.

**Comment by frankhereford** [comment]
Feedback processed 🙏

**Comment by patrickm02L** [comment]
![Montopolis Dr - Fairway St.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/51bdf3cb-1782-4928-bb21-49d073b23c8c)
