### ISSUE TITLE
E. Oltorf / East Side - 5A2363A648

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9303]

**Comment by frankhereford** [comment]
Feedback from Gavin J:

> Crash ID Section 241 – 15839758 is shown as RA collision of a WB and NB car. Per report cars were traveling EB and NB. Show Section 241 – 15839758 at NB approach and as an EB/NB RA crash.

**Comment by frankhereford** [comment]
Feedback processed.

**Comment by patrickm02L** [comment]
![E Oltorf St - East Side Dr.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/c4e5e4ed-083d-4b43-bed4-59baa0ffe70a)
