### ISSUE TITLE
Burton / E. Oltorf - C19CA012A1

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9304]

**Comment by frankhereford** [comment]
Feedback from Gavin J:

>  SB approach of Burton Dr shows many RA crashes. While these are RA crashes, they are caused by LTAP movements. A LTAP symbol should be shown in these cases? See crash IDs below:
>  * Section 246 – 18183480
>  * Section 246 – 17774239
>  * Section 246 – 17609559
>  * Section 246 – 18021779

**Comment by frankhereford** [comment]
feedback processed

**Comment by patrickm02L** [comment]
![E Oltorf St - Burton Dr.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/8156fd66-b181-4355-9541-5d0ab4eb63e7)
