### ISSUE TITLE
Collinfield and Mearns Meadow / Rundberg - 897FECAA37

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9305]

**Comment by frankhereford** [comment]
Feedback processed

**Comment by patrickm02L** [comment]
![Collinfield Dr - Mearns Meadow Blvd - Rundberg Ln.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/5bce6262-74fa-4f40-89d4-de09dc70f875)
