### ISSUE TITLE
[Enhancement] Ability to add an RRFB component

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9312]
Let's also do https://github.com/cityofaustin/atd-data-tech/issues/10106 at the same time.

Add a new "RRFB" subptype to the Signage component.

This is the `moped_components` table.

component_name | component_subtype | line_representation | status_id 
-- | -- | -- | -- | 
Signage | RRFB | FALSE | 1

### Earlier notes

We have an RRFB (rectangular rapid flashing beacon) component subtype in the Moped DB. However, because the RRFB is a subtype of a signal component, it is not currently possible to select RRFB in the UI. This is because the signal component autocompletion sets the signal subtype automatically based on the signal data fetched from Socrata.

RRFB's are **not** included in the Socrata dataset we source signal records from, so it is not actually possible to create an RRFB component.

A quick fix would be to change RRFBs to be a subtype of the “Signage” component rather than a subtype of signals. In that case we would treat them like a plain ole component and not have any autocomplete / data tracker linkage for the time being.  On the Data Tracker side, RRFBs are not managed the same way as signals. RRFBs are tracked as "Flashing Beacon" assets and do not have "planned / potential / construction" statuses.

### Questions for AMD
- Is it correct to consider an RRFB as a subtype of a signal component? Perhaps it makes more sense to assign RRFB as a subtype of a "Signage" component.
- We can include RRFBs in the signal autocompletion component, however that their project managers would need to understand that an RRFB must first be created in the Data Tracker in order for it to be available in Socrata/Moped. If we go this route—do we need to connect Moped projects in the Data Tracker to their RRFB assets in the same we connect signal assets to Moped projects in the Data Tracker?

**Comment by amenity** [comment]
Notes from today's sprint review. Discussion between @johnclary, Nathan, and Renée:
 -   RRFBs are _not_ subtype of a signal component

-   Existing potential signal records in Data Tracker, e.g. [this](https://atd.knack.com/amd#signal-requests/signal-request-details/581eb3f24648a8b32a1faf84/) 

-   Signal studies [tracked in Data Tracker](https://atd.knack.com/amd#signal-pipeline/studies2/) - would be useful to have those selectable in Moped

-   ...But potential signals also come from signal requests, planning recommendations for engineers ... it wouldn't make sense to send ATSD planners to Data Tracker to create a study as the only way to map a potential signal

-   Relatedly, AMD doesn't have a good way of mapping potential signals; reticent to put them in Data Tracker considering its asset mapping functionality

-   Drawing new geometries in Moped is pretty easy; just need to be able to leverage this for RRFBs and signals that aren't in Data Tracker

**Comment by chiaberry** [comment]
I made a comment in slack, but I'll paste a summary here. I think it is related to this issue, but ultimately should be its own separate issue and warrants further discussion

On the old signals dashboard we filter for all projects where the component name is _ilike: "signal" , but in the main projects list view we don’t filter on anything, its just that all the projects in prod right now happen to be signal projects.

- should we have an ability in the advanced filters to filter on component name?

- or does the dashboard that Tilly is implementing and the ability to follow projects make it so we dont need to be able to filter on component type / name?

- or should projects be associated with a division, and we have an option to filter on that too?

**Comment by mateoclarke** [comment]
Discussed in grooming 8/3:
- Make a new component for RRFB as its own type.
- Going to confirm with Moped User Group via Teams. @johnclary
