### ISSUE TITLE
Conduct interviews

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9318]
- [x] Choose panelists
- [x] ~HR~ DTS schedules interviews
- [x] Provide interview link to interviewees through follow-up emial
- [x] Perform interviews
- [x] Score
- [x] Have HR put together offer for chosen applicant
- [x] Provide to applicant
- [ ] Once they've accepted, follow up with other applicants

**Comment by amenity** [comment]
@amenity - check with HR to see when this will close and what next steps are.

**Comment by andrewshensky** [comment]
Interviews have been scheduled with the two applicants we would like to proceed with. The interviews are currently set to take place on Thursday August 11th at 9:30am and 2pm

**Comment by andrewshensky** [comment]
Initial interviews took place 8/11. One applicant needed to reschedule due to an illness and we decided to reach out to a few applicants from outside the Austin area. Additional interviews are tentatively planned for week of Aug 22nd.

**Comment by andrewshensky** [comment]
Both applicants have signed their offer letters and they have been provided to HR. I will be closing this issue.
