### ISSUE TITLE
Onboard new IT Geospatial Technicians

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9319]
# Day 1/2
## Zach
- [x] Log into computer
- [x] Review On-boarding [Checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/your-first-week)
- [x] Set up AGOL account
- [x] Setup DTS Portal account - Apps
- [x] Review DTS Data Inventory
- [x] Check out Open Data Portal
- [x] Review GIS Onboarding GitBook
- [x] Set up GIS Community Bloomfire KB
- [x] Set up Signs and Markings GIS QA - Apps
- [x] Set up Slack - ask Amenity/Diana
- [x] Set up GitHub - need to ask Frank for access
- [x] Set up GitBook - ask Amenity/Diana
- [x] Download ZenHub extension

## Terrence
- Pick up hardware at 9 am
- Cameron at 10 am
- [x] Log into computer
- [x] Review On-boarding [Checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/your-first-week)
- [x] Set up AGOL account
- [x] Setup DTS Portal account - Apps
- [x] Review DTS Data Inventory
- [x] Check out Open Data Portal
- [x] Review GIS Onboarding GitBook
- [x] Set up GIS Community Bloomfire KB
      - Submitted, awaiting account approval 
- [x] Set up Signs and Markings GIS QA - Apps
- [x] Set up Slack - ask Amenity/Diana
- [x] Set up GitHub - need to ask Frank for access
- [x] Set up GitBook - ask Amenity/Diana
- [x] Download ZenHub extension

# Day 2/3
Tuesday afternoon at Cameron
- [x] Log into computer
- [x] Review On-boarding [Checklist](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-LzDGg7hKQ_fUjXnzGGx/onboarding/your-first-week)
- [x] Set up AGOL account
- [x] Setup DTS Portal account - Apps
- [x] Review DTS Data Inventory
- [x] Check out Open Data Portal
- [x] Review GIS Onboarding GitBook
- [x] Set up GIS Community Bloomfire KB
- [x] Set up Signs and Markings GIS QA - Apps
- [x] Set up Slack - ask Amenity/Diana
- [x] Set up GitHub - need to ask Frank for access
- [x] Set up GitBook - ask Amenity/Diana
- [x] Download ZenHub extension

# Onboard Boarding Items
- [ ] Set up GIS Maint/Data Mart accounts - dependency on EID
- [x] Access to G drive - Office of Special Events 
- [ ] Planning SSPR

**Comment by andrewshensky** [comment]
Link to join City Slack organization has been provided to T and Z

**Comment by andrewshensky** [comment]
DM/Maint account creation tickets have been submitted for T and Z
