### ISSUE TITLE
Create map for SS4A grant

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9322]
In the meeting with Lewis and Joel on 5/27/22 --

The VZ team identified the need for a map of the signalized intersections, approximately 1100 within Austin Full Purpose jurisdiction, that are potential area for treatments.

Specifically intersection polygons with the following layers (sub-bullets indicate where to look for or who might have information about the highlighted datasets):

- **Signal backplates**
  - Check with (Brian and Ivonne)
- **Signal battery backups**
  - Spreadsheet in the Gdrive
- **APS signal locations/needs**
  - Check with AMD (Brian and Ivonne)
  - APS flag in the signal PHP database
  - AE contact?
- **ADA compliant curb ramps**
  - Colleen?
- **Sidewalks**
  - John E.
  - Colleen?
- **Bike plan planned/future locations**
  - DTS has an internal layer
  - Could also reach out to Nathan, Mike, or Laura
- **Lighting**
  - Talk with AMD to identify signal pole lighting
  - Roam platform
- **Equity overlaps**
  - [Equity Analysis Zones 2021](https://austin.maps.arcgis.com/home/webmap/viewer.html?useExisting=1&layers=0a095a37ea8a4eb8b835a888f00ef53f)
  - [Historically Disadvantaged Communities](https://usdot.maps.arcgis.com/apps/dashboards/d6f90dfcc8b44525b04c7ce748a3674a) 

@alan-deanda will check in Thursday, 6/2/22 with the VZ team on map progress.

**Comment by patrickm02L** [comment]
Via Lewis on 6/1/22:

> Just spoke with Coleen and Amir and wanted to see if you could add one more layer into the analysis for the grant.  Safe Routes to School has a point file that has intersections they’ve identified for improvements.  This will be another factor we’ll consider as we look to prioritize the systemic safety aspects of the grant application.
> 
> If you can’t find it in the Data Mart, Coleen can point you in the right direction.

**Comment by alan-deanda** [comment]
Update from Ivonne:

> I asked Brian C. about backplates list, what ever priority criteria Vision Zero decides to apply we are fine with it, his suggestion is to start with eastern crescent by corridors. Gavin developed backplate list from street view.
> AMD don't data on street light on traffic signal poles, the pole attachment list is communications antennas for comm companies and he said AE doesn't have that information neither. Something to consider, sometimes an intersection will have some lighting at traffic signal poles OR at AE poles very close by the traffic signal poles, maybe ATD needs another list using street view?
> I hope this information helps.

**Comment by patrickm02L** [comment]
Alan presented to the Austin SS4A Grant App meeting on 6/17/22 on the progress of the [AGOL map](https://austin.maps.arcgis.com/apps/dashboards/9d92714102b54ff5b2ca5836b13188c0).

**Comment by amenity** [comment]
@alan-deanda - create issue for dashboard

**Comment by alan-deanda** [comment]
Today concludes what may be called phase 1 of the geospatial analysis for the SS4A grant application. We have compiled and analyzed the universe of intersections for funding considerations. The next phase involves assigning cost values and provide further analysis.
