### ISSUE TITLE
Add link to parent project from subproject summary page

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9330]
If a project has a parent project, link to the parent project on the summary tab, just below the project name.

<img width="1489" alt="subproject-summary-link" src="https://user-images.githubusercontent.com/14793120/171207426-c8f5cbb2-3f54-4d4f-9f6a-c4fa2940c342.png">

**Comment by amenity** [comment]
@chiaberry - I spoke with @johnclary and he's good with the simplified approach we discussed where the parent project appears under the project description: 
![Screen Shot 2022-06-21 at 4 44 21 PM](https://user-images.githubusercontent.com/1463708/174917704-7235a9d4-0813-489c-a341-7793ab7acfb4.png)

**Comment by johnclary** [comment]
@amenity does the underline implies that you can edit the parent project to something else? i suggest this renders as a hyperlink to the parent project.

**Comment by amenity** [comment]
@johnclary - yes! Good call.
