### ISSUE TITLE
Visualize ATD Cost of Service Data 

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#9339]
Peggy shared with me her spreadsheet which details the department's services by division. She is interested in visualizing it in a better way for presenting to ATD leadership.

She provided me with 2020 and 2021 budget data for the whole department. 

I'll share my work with Anthony S and Peggy on Wednesday.

**Comment by Charlie-Henry** [comment]
I have some code for this @mateoclarke, would it make sense for us to start an `atd-data-science` or `atd-data-viz` repo?

**Comment by patrickm02L** [comment]
Charlie with create a repo called `atd-data-viz `in https://github.com/cityofaustin.
