### ISSUE TITLE
Meeting: TDS Training session on the TDS Development Review Tracker

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#934]
Schedule 12/3 @ Barton Oaks

### Objective 
Introductions
KNACK Development Review Tool
Regular meeting schedule

### Participants
TDS work group
Tracy
Diana

### Agenda
Sangeeta to update agenda

------
- [x] Schedule meeting
- [x] Meet and take notes in agenda doc
- [ ] Create resulting issues

**Comment by dianamartin** [comment]
1. Individual comments grouped by site that showed final unified comment and PM comment status of whether or not the comment was included in the final response. 
2. Would want a multiple comments per review by defined thing "driveway, signals" 
3. Notified of unified comments finalized (review cycle was "Completed"
4. Additional late notices or reminders of review due date.

**Comment by dianamartin** [comment]
Sangeeta emailed 12/4

>Here is a comment from a reviewer:

>Requesting to add a “Save Draft” button besides “Submit” comments button. Sometimes it takes longer to review a site plan and when I am on a different window, Knack may just logout and I have to retype everything I wrote. So, having a “Save Draft” button is really helpful. Also, there should be a possibility to edit the comments until the deadline, even after submission of comments.

**Comment by amenity** [comment]
@TracyLinder can you make feature/enhancement issues for all of these and close this one, please?
