### ISSUE TITLE
V7 UAT Scheduling

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9347]
**ATD-AMANDA will be leading UAT sessions for each major workflow. Nate, Vish, and Tracy will be leading the sessions.** 

----
### UAT Lead Directions
1. Schedule UAT sessions, ideally 1.5 hours each
2. Update the [V7 ATD Test Template](https://teams.microsoft.com/l/file/7E165312-3DAE-4ACE-8F53-B35CB8523882?tenantId=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&fileType=xlsx&objectUrl=https%3A%2F%2Fcityofaustin.sharepoint.com%2Fsites%2FAMANDA-EnterpriseCaseManagement%2FShared%20Documents%2FGeneral%2FUAT%2FUAT%20Test%20Scripts%2FATD-V%20UAT%20Test%20Plan.xlsx&baseUrl=https%3A%2F%2Fcityofaustin.sharepoint.com%2Fsites%2FAMANDA-EnterpriseCaseManagement&serviceName=teams&threadId=19:ace4bf7e72c94603a24afe7501327dad@thread.tacv2&groupId=f0d92127-f6e2-4242-ac5e-f8d488b60389)
    - Update SPOC email from Tracy to **your** name
    - Add UAT date/time to the field 'Test Period Start' 

----
### Email Template

This will be a guided AMANDA V7 user testing session for `Insert Workflow Name (EX permits)`. During this session you will be asked to share your screen while you perform certain tasks in AMANDA or AMANDA Portal. I will capture your testing results and help troubleshoot any defects. 

Please be sure to test logging into your AMANDA V7 user and portal accounts. If you don't have a portal account please follow the prompts to create a new account. 
- [AMANDA V7 TEST](https://coaamdtest.austintexas.gov/backoffice/core/login.zul)
- [AMANDA V7 Portal Test](https://coaamdportaltest.austintx.gov/web/permit)

### Assignments
<div ccp_infra_version='3' ccp_infra_timestamp='1654102888475' ccp_infra_user_hash='881534590' ccp_infra_copy_id='fa0d8859-f1fc-4b3a-b8c9-10a0dd6285df' data-ccp-timestamp='1654102888475'><html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0563C1" vlink="#954F72">

Workflow Name | Division | Manager | Tasked w UAT | UAT Lead
-- | -- | -- | -- | --
LC | ROW | Paloma | Daniil | Nate
UC | ROW | Darren | Jaclyn, Isiah | Nate
RW - Street Vendor | ROW | Paloma | Paloma | Nate
TDS fees on DSD folders | TDS | Nathan | Amber | Nate
TDS fees on GF folder | TDS | Nathan | Amber | Nate
TIA | TDS | Nathan | Joan M | Nate
RW - TURP | ROW | Paloma | Peter & Evelyn | Nate, Sree
EX | ROW | Paloma | Daniil, Izzy | Nate, Subha
ECV | ROW | Darren | Nathan Chandler | Tracy
TCP Inspections | ROW | Darren | Nathan Chandler | Tracy
COS Integration | ROW | All | Tracy, John Carr | Tracy
SB | Signs & Markings | Lauren | Kathy K. | Tracy
SIF | TDS | Nathan | Amber, Tracy | Tracy
RW - Parking | OSE | Frances | Maria | Vish
RW - Street Event | OSE | Frances | Maria | Vish
GF Fees | ROW | Darren | Alyse, Robert | Vish
RW - Parking | ROW | Paloma | Johnathan W. | Vish
RW - Film | ROW | Paloma | Kensley | Vish
DS | ROW | Paloma | Kim | Vish
RW - Valet Annual | ROW | Paloma | LaTonya | Vish
RW - Valet Temporary | ROW | Paloma | LaTonya | Vish
PSM | ROW | Paloma | Paloma | Vish
RW - Valet Operator | ROW | Paloma | Paloma | Vish

</body>

</html>
</div>

**Comment by TracyLinder** [comment]
### Nate's List

- [ ] LC
- [ ] UC
- [ ] RW - Street Vendor
- [ ] TDS fees on DSD folders
- [ ] TDS fees on GF folder
- [ ] TIA
- [ ] RW - TURP
- [ ] EX

**Comment by amenity** [comment]
Notes for Amenity's sake:
Signs and Markings has two pieces of functionality left in Amanda: 
 - Banners payments - will be retired once CityBase stuff is set up w/ Knack app
 - Kati submits weekly reports to existing Amanda permits on work locations SMD has visited
