### ISSUE TITLE
Account access: Natalia R. (utexas)

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#935]
John C.
DTS

Emailed
>Could you work with Natalia to get her access to these things? Possibly a knack public view? Let her know if you need clarification.

**Comment by dianamartin** [comment]
Emailed user

>- So you’re looking to have the digitized TIA data (GIS format I presume?). 
Traffic Counts data (in .pdf format) – we use JAMAR and TimeMark software. 
- We have a page of requests and their attachments. Will you be downloading the attachments?

**Comment by dianamartin** [comment]
Created account for Natalia in the Data Tracker, but kept her in `inactive` status until I hear back on the clarification of her request.

**Comment by dianamartin** [comment]
Have call/screen share scheduled for next Tuesday, 11/26

**Comment by amenity** [comment]
- Wants raw TIA pages Frank worked with
 - Haven't heard from Natalia but suspect she will access this through an API. Account access is pending for now.
