### ISSUE TITLE
[ROW Portal] Copy COS for Test V7 Connection (Apps)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9354]
### Create a copy of the ROW Portal Cost of Service app
_should we include the connect to V7 or make a separate issue for it?_

**Comment by ChrispinP** [comment]
The copy is now ready: TEST V7 | ROW | 22 JUN 2022 | Right of Way Portal
and can be found [Here](https://atd.knack.com/test-v7-row-22-jun-2022-right-of-way-portal#home/)

Let me know if anything else is needed :)

**Comment by ChrispinP** [comment]
Frank has successfully Tested the V7 connection.

**Comment by TracyLinder** [comment]
@ChrispinP I think we're good to close this one. Please close if you agree. Thank you!
