### ISSUE TITLE
AMANDA Fee Data Request 

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9369]
### Data requested by Paloma, Jim D
- ASAP

----
### Query Paramenters:

- All fees in the fee list that are PAID
- From 10/1/2020 to current date

### Fees

1. Driveway Inspection Fee - Transportation 
2. Sidewalk Inspection Fee - Transportation
3. Curb and Gutter Inspection Fee - Transportation
4. Excavation Inspection Fee - Transportation 

### Data Output 
- Output should be raw data. 

<div ccp_infra_version='3' ccp_infra_timestamp='1654286401556' ccp_infra_user_hash='881534590' ccp_infra_copy_id='1b90c0b2-7258-4972-b379-751b653dda19' data-ccp-timestamp='1654286401556'><html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0563C1" vlink="#954F72">

Folder RSN | Folder Type | Fee Name | Fee Amount (Not payment amount) | Payment Date
-- | -- | -- | -- | --

</body>

</html>
</div>

**Comment by TracyLinder** [comment]
@Nadin-Nader this is the ticket for the data Paloma requested in our review meeting today. I wrote the AC and put this On Deck.

**Comment by SubhaShroff** [comment]
Notes:
The fees with feecodes
Driveway Inspection Fee - Transportation **(50349)**
Sidewalk Inspection Fee - Transportation **(50350)**
Curb and Gutter Inspection Fee - Transportation **(50351)**
Excavation Inspection Fee - Transportation **(50149)**

**Comment by Nadin-Nader** [comment]
Information and Query have been sent to Paloma, closing.

> From: Amayo-Ryan, Paloma <Paloma.Amayo-Ryan@austintexas.gov> 
> Sent: Thursday, June 9, 2022 11:30 AM
> To: Nader, Nadin <Nadin.Nader@austintexas.gov>
> Subject: RE: Data Query
> 
> Thanks Nate!  I’ve shared this with the larger group that has been looking at these fees.
> 
> Paloma Amayo-Ryan
> Program Manager
> (512) 974-2841
>
