### ISSUE TITLE
Compile custom CSS requirements for VZA Application

### ISSUE THREAD

**Issue by SurbhiBakshi** [cityofaustin/atd-data-tech#937]
Document requirements with https://github.com/cityofaustin/atd-data-tech/issues/966. 
- [ ] Need a big button to direct officers back to earlier page after recording violations for that contact.
![Screen Shot 2019-11-22 at 2.06.12 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/dba98031-c0de-4101-b9cf-33edd0721935)

**Comment by SurbhiBakshi** [comment]
## Calendar
- [x] Make all blocks the same color - done. Visually it would help to have the text 'Bold' so it will stand out against a background, but this options doesn't seem to be available in the Calendar tools. Think we discussed having a different color for shifts with zero unassigned slots versus shifts that needed assigned officers? 

## _Add a Shift_ modal
- [x] ![Screen Shot 2019-11-20 at 3 16 46 PM](https://user-images.githubusercontent.com/1463708/69358588-b449ba80-0c4c-11ea-903c-e944ee72af1e.png) the all day and repeat check boxes will need a CSS solution to disappear.

**Comment by SurbhiBakshi** [comment]
- [ ] If we decide to ask officers to record start and end times for assignments, then the options need to be bigger and bolder.
![Screen Shot 2019-11-22 at 2.19.41 PM.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/83bbf98a-4f12-4f91-b7d0-3f6014215739)

**Comment by amenity** [comment]
@mddilley - Sticking this On Deck for Sprint 13 but no need to review the notes above for the time being — lots in flux with this right now. @SurbhiBakshi is going to compile a request for specific changes this week and hopefully you can set aside time to implement next week.

**Comment by SurbhiBakshi** [comment]
[ ] Assignments Calendar Page - Make Team 1, Team 2, Team 3 , All buttons  bigger and bolder. 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/aa23f0cb-f7b0-4749-9a48-bced16f8f1cf)

**Comment by SurbhiBakshi** [comment]
[ ] Assignments Calendar Page - make the selection buttons for month, week, day bigger and bolder. 

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/bc9bc332-01c6-4317-ba78-36850c25c6f4)

**Comment by SurbhiBakshi** [comment]
[ ] Assignments Table on Assignments page - make the selection buttons for Upcoming and Past bigger and bolder. 
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/a2b3f57a-156b-44b3-ba46-58bb7319f9e1)

**Comment by SurbhiBakshi** [comment]
[ ] Is there a way to color in records based on if an officer has been assigned, if no officers have been assigned?

**Comment by SurbhiBakshi** [comment]
[ ] Assess level of effort for this request, this will probably go into phase 2. 
 I wrote to Knack asking if there was a way to update multiple records from a table on the user end instead of using a form / inline editing to do the updates one at a time. I think it would be useful for RandyD when he is assigning officers to assignments to assign them to multiple assignments. As per Knack, there is no feature that allows batch updates from the live app, but customers have been using custom code to create this feature.

https://support.knack.com/hc/en-us/community/posts/222365967-Update-multiple-records-with-a-checkbox

**Comment by SurbhiBakshi** [comment]
[ ] Is it possible to take some of the fields associated with the location field. 
Street Address 2 (mainly this one, since this can lead the officers to put in an intersection, which doesn't work)
City
State
Zip

These come in a block/ group via the Location field. Using a plain text field as Street Address will mean taking way the autocomplete function that the officers like.

![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/2c5a606b-5d3b-4ab3-9237-2b3b1175ea76)

**Comment by SurbhiBakshi** [comment]
[ ] Create big buttons for main pages,  as in old page.
 ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/8aed60ad850-43e0-9e7b-aae316831772)
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/4de958b3-3dc4-4471-ac95-9ea8f706d5ae)

**Comment by SurbhiBakshi** [comment]
- [ ] Can the options for Equipment which have been enabled for Inline Editing be shown in a different color?

**Comment by SurbhiBakshi** [comment]
[ ] Make the Add Contact button bigger and bolder.
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/38ff7f22-aa2d-4691-9749-ba01b1223e17)

**Comment by SurbhiBakshi** [comment]
- [ ] Make Banner icons and text bigger and bolder ![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/8613a6e6-f60c-4c43-8391-182253e918f6)

**Comment by SurbhiBakshi** [comment]
|Role | Home (Assignments)| Officers | Administration | Location | Reports |
|:---:|:----:|:----|:----:|:-----:|:-----:|

**Comment by SurbhiBakshi** [comment]
@amenity , here is the list of CSS enhancements I think would benefit the app.
