### ISSUE TITLE
Update the DTS Division Website staff listings

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9376]
Peggy, Mateo & John each need to have either a title change or an addition to our staff listing page. We'll need the usual info, (name, title, pronouns), for each to make the update.

- [x] Update Mateo's title to "Head of Software Engineering"
- [x] Move John to "Alumni".  
- [x] Add Peggy to the top. Title: Division Manager. Headshot [here](https://drive.google.com/file/d/1jSwUGD5yMribr4KYdeuHA1M8Qpwx6N1n/view?usp=sharing), [pronouns](https://docs.google.com/document/d/1gRjTic8FD3s-t0sVZhErAidMIAktU-0Vn2GYPpPcUeg/edit) she/her
- [x] Add Rebecca. Title: UX/UI Design Fellow 
- [x] Add Rose. Title: Software Engineering Fellow

**Comment by amenity** [comment]
Thanks, @frankhereford. :) Let's update Rose and Rebecca at the same time, cc/ @patrickm02L.

I left comments for @maccallump @mateoclarke and @johnclary in [this doc](https://docs.google.com/document/d/1gRjTic8FD3s-t0sVZhErAidMIAktU-0Vn2GYPpPcUeg/edit).

**Comment by amenity** [comment]
@patrickm02L @mateoclarke - hoping that this can get passed over to a dev at next week's sprint planning.

**Comment by mateoclarke** [comment]
This might be a really good first commit for Rose to work on early in the week too. Instead of holding it for Sprint Planning.

**Comment by patrickm02L** [comment]
@mateoclarke I agree. Let's move it On Deck on Monday when's she's logged in and has access to our github.

**Comment by amenity** [comment]
Even better! 🙌🏻
