### ISSUE TITLE
[Enhancement] Remove "None" as a project partner option

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9377]
We have a "Partner" option called "None." It's used in a way that makes "None" not the absence of a partner, but rather, an actual, real partner, in the same usage that we might call "Active Transportation" a partner.

Let's remove the "None" partner option, and display "None" when no partners have been designated. 

The intent of this suggestion is to mirror the way that "Project Types" works. This possible partner state best summarizes this suggestion:

<img width="905" alt="Screen Shot 2022-06-03 at 11 21 05 AM" src="https://user-images.githubusercontent.com/3653206/171905832-2d0754d4-dd85-4633-958f-1917721dc496.png">

Via Frank's comment, [here](https://github.com/cityofaustin/atd-moped/pull/660#pullrequestreview-995163441).

**Comment by chiaberry** [comment]
We no longer show None as an option.
