### ISSUE TITLE
[GIS] Update Street Banner Web Apps

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9379]
Referenced to #6155 

Lauren has decided we'd phase out the PDF lamppost banner maps for the Street Banner Program. We will need to remove the links to the PDFs that exist on the [LPB Web App](https://austin.maps.arcgis.com/apps/MapSeries/index.html?appid=b0e65307b3514804901519d911aeb158). 

ex. 
![image](https://user-images.githubusercontent.com/21112975/172187351-10eebdde-1239-4a7d-ae0d-9a115cc171b1.png)

ex. 
![image](https://user-images.githubusercontent.com/21112975/172187459-5e7c8abf-ebf0-4764-9164-cfa963f57147.png)

**Comment by dianamartin** [comment]
@andrewshensky Let me know if you want to chat about this

**Comment by andrewshensky** [comment]
@dianamartin I think it would be great to sync on this. Feel free to schedule a time to discuss that works best for you.

**Comment by dianamartin** [comment]
# Steps
- document the URLs from austintexas.gov to provide to PIO to remove from Drupal
- Put in [PIO request](https://austinmobility.typeform.com/to/MWCcvlQ1?typeform-source=cityofaustin.sharepoint.com)
- remove links in web app to the individual PDFs
-

**Comment by andrewshensky** [comment]
The PDF links have now been removed from the web app and the request to PIO has been submitted
