### ISSUE TITLE
Review the usage volumes of SQS requests for all queues, remediating any which are being used unintentionally

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9383]
The service desk got an email yesterday noting that we’re at 85% of our month’s allocation of free SQS requests. Normally, these emails are non-items, but SQS gives you a million freebies, and I think of the SQS counter being very closely tied to our lambda function usage, in particular for the VZ suite. Because of that, a million requests seems high for six days of use. 

Looking at the free-tier or cloudwatch rates recorded for the various queues, I’m able to look back at the last month or two of data. We don’t keep anything more detailed or historical (yet). 

I believe we do have an issue. We are receiving ~10 empty requests per minute to the `atd-vz-data-events-crash_update_location_production` SQS queue. I would expect these to only be triggered when a crash has its location updated, and as a result, not at this frequency or "steady" rate of consumption. 10 requests a minute is a little shy of a half million every 30 days, so we can expect the cost wastage of this issue to be in the order $1 / month. 

@mateoclarke suggested writing this up so we have a placeholder to make sure we look into it enough to know we don't have another, bigger problem on our hands causing this. I agree with his ideas and plan. 

> https://austininnovation.slack.com/archives/CHZE6BC6L/p1654514809418389.

**Comment by amenity** [comment]
Thanks for getting this into an issue, @frankhereford. Tasks/requests concerning DTS' system-level dev software/tools would be best assigned to @mateoclarke. If they're for a particular application, e.g. Moped, Vision Zero, it's great to include the relevant PM.

**Comment by frankhereford** [comment]
@amenity wrote:
> Thanks for getting this into an issue, @frankhereford. Tasks/requests concerning DTS' system-level dev software/tools would be best assigned to @mateoclarke. If they're for a particular application, e.g. Moped, Vision Zero, it's great to include the relevant PM.

Thanks Amenity - that makes total sense. My bad, it was force of habit. I will make sure to keep that in consideration in the future though when making or assigning issues.

**Comment by mateoclarke** [comment]
I'm reassigning this to @chiaberry. This issue seems very low priority and should probably be investigated if the [AWS Cost Tracking](https://github.com/cityofaustin/atd-data-tech/issues/9992) review highlights a higher than expected costs for the SQS service.

**Comment by chiaberry** [comment]
we no longer have any active SQS queues
