### ISSUE TITLE
Upgrade Moped to `graphql-engine` 2.7.0 or later

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9385]
After a Friday afternoon conversation about possible projects which would be fun and unexpected to put in an upcoming Moped PR 666, @mateoclarke came up with a great idea to make it an opportunity to look into upgrading our current version of `graphql-engine` from 1.3 to 2.7+. I had some time to try it out over the weekend, and then this [conversation happened in slack.](https://austininnovation.slack.com/archives/CNUEPKLB1/p1654287743257939)

My first comment: 

>I opened a feature branch, [the devil is in the details](https://github.com/cityofaustin/atd-moped/tree/the-devil-is-in-the-details), to check out the double-dog-dare of seeing what road blocks would come up with regards to running with the latest release of graphql-engine. :dog2: :guide_dog:
>
>I think we’re in a surprisingly good place — 2.7.0 spun up and worked out of the box for me locally. I can’t get it to break going through each UI view while entering and removing data.
>
>Hasura has written downright [excellent documentation](https://hasura.io/docs/latest/graphql/core/guides/upgrade-hasura-v2/) for this process, and the list of breaking changes is a must read. I’ve gone through each, and I think the only one that has potential to break something in moped is the new support for the updated graphql spec which requires:
>
>[#3: Order of keys in objects passed as “order_by” operator inputs is not preserved](https://hasura.io/docs/latest/graphql/core/guides/upgrade-hasura-v2/#hasura-v2-behaviour-changes)
>
>I have looked at all the instances of order_by in our entire codebase, and I believe that our only use of anything except a single key-value pair occurs in GQLAbstract.js. However, we don’t feed any configurations into GQLAbstract which would cause it to make unordered, tiered order_by configurations so .. :white_check_mark: i think.
>
>Additional reading of the [change-logs](https://github.com/hasura/graphql-engine/releases) going back to the 2.0 release would also be prudent, in particular focusing on any behavior or breaking changes Hasura points out. Luckily, there are few. I’ve brushed through these and don’t see any glaring issues, but I’d want to spend an hour or so carefully inspecting them.
>
>I’d love to discuss any of those behavior changes that anyone thinks could be impactful. It’s my belief that if we were to 1) all :thumbsup: on that list of changes as being safe or understood, and 2) have the app be tested with the testing script that Product maintains, then we could plan for an upgrade in testing, staging and then production.
>
>This was just a fun exercise initially, but I think it has strong potential to be straightforward. I would be happy to spin this conversation into an issue also at anytime. The new graphql-engine is :fire: , it’s notably faster on startup, maybe 2-3X faster and I think it’s noticeable in the app too.

I will snag that PR # when it comes up, and we can discuss the idea generally here and with a more practical consideration in that when it's available. Until then, feel free to browse the changes I have in the branch, [the devil is in the details](https://github.com/cityofaustin/atd-moped/tree/the-devil-is-in-the-details). It's really nothing, it's super easy to get to where you can test the app just by firing it up after checking it out.

**Comment by amenity** [comment]
@johnclary - In dev sync, @frankhereford explained that this doesn't need to be tied to a release since there is no code involved. He actually thinks it may be better to stagger them.

**Comment by amenity** [comment]
Wait... this must be the wrong issue... 🙈
