### ISSUE TITLE
[BUG] MetroBike trips dataset missing "Bike Type"

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9388]
David O. and Eliza have reported that the "Bike Type" column on our [public MetroBike trip dataset](https://data.austintexas.gov/Transportation-and-Mobility/Austin-MetroBike-Trips/tyfh-5r8s) is empty.

TLDR: our script will automatically handle this attribute, but it's been missing from the trip files that Diego (MetroBike) uploads to Dropbox.

#### Historical Context
- User emailed transporation data inbox on 4/14
>I'd love for the metrobike trip data to populate the 'bike type' column
[https://data.austintexas.gov/Transportation-and-Mobility/Austin-MetroBike-Trips/tyfh-5r8s/data](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.austintexas.gov%2FTransportation-and-Mobility%2FAustin-MetroBike-Trips%2Ftyfh-5r8s%2Fdata&data=05%7C01%7CDiana.Martin%40austintexas.gov%7C08619f8556d94aa303e508da23aa5c13%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C637861511846437956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YWxRN0honyLXPYBDVl66kc%2F3gKjr%2B7XmNJp77ktr%2FRA%3D&reserved=0)
- David O. reported to us on 4/21
>Regarding the user request to add bike type to the Open Data Portal dataset, it isn’t included in the BCycle (Trek) dataset.  However, Diego with BSA has offered to add it on our end.  Could you provide guidance on where that column needs to be added and anything he might need to know about the attributes, etc. so that this can be completed successfully?
- Diego gave Dropbox access to other DTS peeps (Mateo, Diana) on 5/25/22

**Comment by johnclary** [comment]
My email to Deigo on 4/21/22: 

> Please include a column with the exact name  "BikeType" on the monthly trip spreadsheet our ingestion process will push that data to the public dataset. 
> 
> I'm speaking from memory, but I believe earlier spreadsheets included that column, but more recent ones have not.

**Comment by johnclary** [comment]
I have followed up three times, most recently today. Waiting for Diego to take care of this.

**Comment by patrickm02L** [comment]
@john or @diana do we have any idea about the status of this Issue?

**Comment by johnclary** [comment]
I emailed Deigo about this again. It Eliza is the right person on the program side it would be great to have her reply to try to escalate it with Diego. :/

**Comment by johnclary** [comment]
ah, interesting that we can use the bike IDs to determine the type. possibly something @Charlie-Henry would have an interest in doing? [DAG](https://github.com/cityofaustin/atd-airflow/blob/master/dags/atd_metrobike_trips.py) and [repo](https://github.com/cityofaustin/atd-metrobike).

**Comment by Charlie-Henry** [comment]
This sounds fun I'll take it on ✔️ 🚲

**Comment by patrickm02L** [comment]
@Charlie-Henry let's hold for a minute. I want to hear back from Dylan to see if he's able to resolve things with B-cycle.

**Comment by Charlie-Henry** [comment]
Sounds good @patrickm02L

**Comment by patrickm02L** [comment]
Via @johnclary through Slack

> our ETL that publishes Metrobike Trips is failing because the most recent trip file in Dropbox has a bunch of empty rows for the checkout date and time. Can y’all work with them to get the data repaired?

**Comment by patrickm02L** [comment]
We're continuing to reach out to MetroBike to try to resolve dataset maintenance, specifically Hunter H. 

We'll either have to deprecate this dataset or put together an agreement to update this data on a regular basis. 

@maccallump offered to take the lead in setting up an MOU with MetroBike to regularly update this dataset.

**Comment by patrickm02L** [comment]
Follow w/ Hunter about about Bike Type and more recent missing data that's causing our ETL to fail #11252

> It's been a while since we talked back in December about bike_types.
> 
> The MetroBike Trips data which is transferred to the open data portal from Dropbox is missing data for several fields, and is preventing us from being able update this dataset in the data portal.
> 
> In November, we stopped getting Return Kiosk ID data (first image). Prior to that the Month and Year data was no longer coming in (second image). 
>
> ![Screen Shot 2023-01-25 at 1.44.18 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/30333e44-f2ea-4ff4-a0dd-ad4abcd7979f)
> 
> 
> ![Screen Shot 2023-01-25 at 1.54.51 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/337cdfc7-60c5-4007-866f-f239989079ec)
>
> The missing data from the field is causing our ETL (extract, transform, load) process, which pulls the data from the Dropbox spreadsheet and populates it in the open data portal to fail. 
>
> Do you have any insights into why the data is no longer populating in the bike_type, return_kiosk_id, month, and year columns?
> 
> Happy to meet and troubleshoot with you if need be.

**Comment by Charlie-Henry** [comment]
@patrickm02L @maccallump sent me the data provided by Metrobike. It contains data from January 1st 2022 to December 31 2022.

Looks like November and December are still malformed from what we were receiving previously. Checkout time and date were not provided for about 80% of that month. The table below is a summary. The non-null column is the count of the number of rows that are not blank.

| TripReport-012022.csv |                     |                |         |
|-----------------------|---------------------|----------------|---------|
| #                     | Column              | Non-Null       | Dtype   |
| 0                     | TripId              | 14513          | int64   |
| 1                     | MembershipType      | 14513          | object  |
| 2                     | Bike                | 14513          | object  |
| 3                     | CheckoutDateLocal   | 14513          | object  |
| 4                     | CheckoutTimeLocal   | 14513          | object  |
| 5                     | CheckoutKioskID     | 14513          | int64   |
| 6                     | CheckoutKioskName   | 14513          | object  |
| 7                     | ReturnKioskID       | 14513          | int64   |
| 8                     | ReturnKioskName     | 14513          | object  |
| 9                     | DurationMins        | 14513          | int64   |
| TripReport-022022.csv |                     |                |         |
| #                     | Column              | Non-Null       | Dtype   |
| 0                     | TripId              | 21251          | int64   |
| 1                     | MembershipType      | 21251          | object  |
| 2                     | Bike                | 21251          | object  |
| 3                     | CheckoutDateLocal   | 21251          | object  |
| 4                     | CheckoutTimeLocal   | 21251          | object  |
| 5                     | CheckoutKioskID     | 21251          | int64   |
| 6                     | CheckoutKioskName   | 21251          | object  |
| 7                     | ReturnKioskID       | 21251          | int64   |
| 8                     | ReturnKioskName     | 21251          | object  |
| 9                     | DurationMins        | 21251          | int64   |
| TripReport-032022.csv |                     |                |         |
| #                     | Column              | Non-Null       | Dtype   |
| 0                     | TripId              | 27573          | int64   |
| 1                     | MembershipType      | 27572          | object  |
| 2                     | Bike                | 27573          | object  |
| 3                     | CheckoutDateLocal   | 27573          | object  |
| 4                     | CheckoutTimeLocal   | 27573          | object  |
| 5                     | CheckoutKioskID     | 27541          | float64 |
| 6                     | CheckoutKioskName   | 27573          | object  |
| 7                     | ReturnKioskID       | 27548          | float64 |
| 8                     | ReturnKioskName     | 27573          | object  |
| 9                     | DurationMins        | 27573          | int64   |
| TripReport-042022.csv |                     |                |         |
| #                     | Column              | Non-Null       | Dtype   |
| 0                     | TripId              | 36790          | int64   |
| 1                     | MembershipType      | 36790          | object  |
| 2                     | Bike                | 36790          | object  |
| 3                     | CheckoutDateLocal   | 36790          | object  |
| 4                     | CheckoutTimeLocal   | 36790          | object  |
| 5                     | CheckoutKioskID     | 36790          | int64   |
| 6                     | CheckoutKioskName   | 36790          | object  |
| 7                     | ReturnKioskID       | 36790          | int64   |
| 8                     | ReturnKioskName     | 36790          | object  |
| 9                     | DurationMins        | 36790          | int64   |
| TripReport-052022.csv |                     |                |         |
| #                     | Column              | Non-Null       | Dtype   |
| 0                     | TripId              | 26351          | int64   |
| 1                     | MembershipType      | 26351          | object  |
| 2                     | Bike                | 26351          | object  |
| 3                     | CheckoutDateLocal   | 26351          | object  |
| 4                     | CheckoutTimeLocal   | 26351          | object  |
| 5                     | CheckoutKioskID     | 26351          | int64   |
| 6                     | CheckoutKioskName   | 26351          | object  |
| 7                     | ReturnKioskID       | 26351          | int64   |
| 8                     | ReturnKioskName     | 26351          | object  |
| 9                     | DurationMins        | 26351          | int64   |
| TripReport-062022.csv |                     |                |         |
| #                     | Column              | Non-Null       | Dtype   |
| 0                     | TripId              | 19530          | int64   |
| 1                     | MembershipType      | 19526          | object  |
| 2                     | Bike                | 19530          | object  |
| 3                     | CheckoutDateLocal   | 19530          | object  |
| 4                     | CheckoutTimeLocal   | 19530          | object  |
| 5                     | CheckoutKioskID     | 19530          | int64   |
| 6                     | CheckoutKioskName   | 19530          | object  |
| 7                     | ReturnKioskID       | 19530          | int64   |
| 8                     | ReturnKioskName     | 19530          | object  |
| 9                     | DurationMins        | 19530          | int64   |
| TripReport-072022.csv |                     |                |         |
| #                     | Column              | Non-Null       | Dtype   |
| 0                     | TripId              | 19486          | int64   |
| 1                     | MembershipType      | 19486          | object  |
| 2                     | Bike                | 19486          | object  |
| 3                     | CheckoutDateLocal   | 19486          | object  |
| 4                     | CheckoutTimeLocal   | 19486          | object  |
| 5                     | CheckoutKioskID     | 19486          | int64   |
| 6                     | CheckoutKioskName   | 19486          | object  |
| 7                     | ReturnKioskID       | 19486          | int64   |
| 8                     | ReturnKioskName     | 19486          | object  |
| 9                     | DurationMins        | 19486          | int64   |
| TripReport-082022.csv |                     |                |         |
| #                     | Column              | Non-Null       | Dtype   |
| 0                     | TripId              | 24159          | int64   |
| 1                     | MembershipType      | 24159          | object  |
| 2                     | Bike                | 24159          | object  |
| 3                     | CheckoutDateLocal   | 24159          | object  |
| 4                     | CheckoutTimeLocal   | 24159          | object  |
| 5                     | CheckoutKioskID     | 24159          | int64   |
| 6                     | CheckoutKioskName   | 24159          | object  |
| 7                     | ReturnKioskID       | 24159          | int64   |
| 8                     | ReturnKioskName     | 24159          | object  |
| 9                     | DurationMins        | 24159          | int64   |
| TripReport-092022.csv |                     |                |         |
| #                     | Column              | Non-Null       | Dtype   |
| 0                     | TripId              | 40256          | int64   |
| 1                     | MembershipType      | 40256          | object  |
| 2                     | Bike                | 40256          | object  |
| 3                     | CheckoutDateLocal   | 40256          | object  |
| 4                     | CheckoutTimeLocal   | 40256          | object  |
| 5                     | CheckoutKioskID     | 40256          | int64   |
| 6                     | CheckoutKioskName   | 40256          | object  |
| 7                     | ReturnKioskID       | 40256          | int64   |
| 8                     | ReturnKioskName     | 40256          | object  |
| 9                     | DurationMins        | 40256          | int64   |
| TripReport-102022.csv |                     |                |         |
| #                     | Column              | Non-Null       | Dtype   |
| 0                     | TripId              | 43211          | int64   |
| 1                     | MembershipType      | 43211          | object  |
| 2                     | Bike                | 43211          | object  |
| 3                     | CheckoutDateLocal   | 43211          | object  |
| 4                     | CheckoutTimeLocal   | 43211          | object  |
| 5                     | CheckoutKioskID     | 43211          | int64   |
| 6                     | CheckoutKioskName   | 43211          | object  |
| 7                     | ReturnKioskID       | 43211          | int64   |
| 8                     | ReturnKioskName     | 43211          | object  |
| 9                     | DurationMins        | 43211          | int64   |
| TripReport-112022.csv |                     |                |         |
| #                     | Column              | Non-Null       | Dtype   |
| 0                     | TripId              | 26547          | int64   |
| 1                     | MembershipType      | 26547          | object  |
| 2                     | Bike                | 26547          | object  |
| 3                     | CheckoutDateLocal   | 26547          | object  |
| 4                     | CheckoutTimeLocal   | 26547          | object  |
| 5                     | CheckoutKioskID     | 26547          | int64   |
| 6                     | CheckoutKioskName   | 26547          | object  |
| 7                     | Return Kiosk ID     | 26547          | int64   |
| 8                     | ReturnKioskName     | 26547          | object  |
| 9                     | DurationMins        | 26547          | int64   |
| 10                    | CheckoutDateLocal.1 | 26547          | object  |
| 11                    | ReturnDateLocal     | 26547          | object  |
| 12                    | CheckoutTimeLocal.1 | 26547          | object  |
| 13                    | ReturnTimeLocal     | 26547          | object  |
| TripReport-122022.csv |                     |                |         |
| #                     | Column              | Non-Null Count | Dtype   |
| 0                     | TripId              | 17313          | int64   |
| 1                     | MembershipType      | 17313          | object  |
| 2                     | Bike                | 17313          | object  |
| 3                     | CheckoutDateLocal   | 3245           | object  |
| 4                     | CheckoutTimeLocal   | 3245           | object  |
| 5                     | CheckoutKioskID     | 17313          | int64   |
| 6                     | CheckoutKioskName   | 17313          | object  |
| 7                     | ReturnKioskID       | 17313          | int64   |
| 8                     | ReturnKioskName     | 17313          | object  |
| 9                     | DurationMins        | 17313          | int64   |

**Comment by Charlie-Henry** [comment]
I want to fix this dataset did we hear back anything from CapMetro on this data quality problem?

**Comment by Charlie-Henry** [comment]
@johnclary looks like the top 9 bikes used last month were all 5-digit bike IDs that start with 19 and 20,21,22. So that's probably the case but it would be good to get confirmation if this is still the case?

**Comment by Charlie-Henry** [comment]
Update from Hunter:
> All e-bikes will have 5 digit bike numbers starting with “15” and up

**Comment by Charlie-Henry** [comment]
@johnclary I opened a PR for editing the ETL. As for re-processing the past data, I got back to June 2022 before I got some null values in the Membership Type column which caused it to fail the schema validation. Can we ignore nulls in some of the columns when it comes to historical data?
