### ISSUE TITLE
Investigate Brazos integration for VZA app

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#939]
If we can get the Brazos email report functionality to work, we could do an ETL with that data and drastically simplify the officer UI - they would just have to record "No Contact" or "eCitation number". 

@SurbhiBakshi is going to:
- Get Brazos credentials
- Talk to Ryan Mooney
- Circle back with @johnclary if necessary

**Comment by SurbhiBakshi** [comment]
@johnclary , RyanM can access Brazos, but not sure it is through a BI tool. DanielY may be accessing Brazos using MicroStrategy as per JaimeM.
