### ISSUE TITLE
[Bug] Funding Sources Not Rendering on Projects Page Table

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#9406]
**BUG**
Testing: "Add multiple funding sources to a project, Go back to the Projects page, make sure to toggle the "Funding source" column is on and verify you see the comma-separated sources."
- No funding sources render on the Projects page table 

Funding tab: 
![image](https://user-images.githubusercontent.com/100615928/172466630-2d8207ab-841f-4fa0-84e0-4f42e4d1ae6d.png)

Projects table: 
![image](https://user-images.githubusercontent.com/100615928/172466690-63b8c63e-f11f-4af0-8040-ece07d4bca34.png)

 

**URL**
https://moped-test.austinmobility.io/moped/projects

**Device**
Macbook Pro 2017

**Browser**
Chrome

**Additional context**
DTS Moped testing

**Comment by mddilley** [comment]
I took a quick look at this one, and it looks like if the funding source **Status** is set to either **Set up** or **Funding setup requested** then the funding source does not show up in the projects table. I'm looking into this more to see where this is happening, but I suspect it is in the `project_list_view`.
