### ISSUE TITLE
[Bug] Advanced search field names do not match table column names

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9417]
The advanced search allows you to search by "Current status" and "Current phase", however the project list only has a column called "Status". The "status" column on the project list seems to map to "Current phase".

It's unclear from the UI which search field actually searches on the "Status" column.

<img width="582" alt="searchlist" src="https://user-images.githubusercontent.com/14793120/172670018-bf263a2c-4ade-48b3-b0a3-b0c87d0ee100.png">

<img width="431" alt="searchcolumns" src="https://user-images.githubusercontent.com/14793120/172670019-1053af10-fe34-462b-b850-c145987f6212.png">

**Comment by chiaberry** [comment]
Here is what the fields are in staging
![Screen Shot 2022-07-06 at 4 49 06 PM](https://user-images.githubusercontent.com/12474808/177832715-3a2cc1f7-3a5e-4e3f-844b-30cd1d4d567e.png)
And here are the badges for those projects
![Screen Shot 2022-07-06 at 4 49 12 PM](https://user-images.githubusercontent.com/12474808/177832844-2fb3d810-6c9f-4ae4-bd29-c271da92e4e1.png)

How does dropping current_status as a search option sound, and changing the field name to be Status and search on the current_phase column in the db?

**Comment by johnclary** [comment]
@chiaberry that sounds good to me. thank you!
