### ISSUE TITLE
Port Airflow DAG to Prefect: Vision Zero OCR / extraction script

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9419]
During our biweekly Prefect huddle yesterday, the group discussed me porting another, simpler DAG from Airflow to Prefect. 

We settled on the OCR script because it is a simpler python script, and by doing it in inside the framework I've been working on [here](https://github.com/cityofaustin/atd-prefect/pull/9), it should be a demonstration of the general lift one could expect in writing a new script from scratch, especially one that is not going to require nested docker invocations.

**Comment by mateoclarke** [comment]
Thanks for making this issue Frank. It would be great to try to do this before our next Prefect Huddle on 6/21 if you think you'll have room on your plate before then.

**Comment by frankhereford** [comment]
This is ready for review in our next Prefect Huddle, and [this PR](https://github.com/cityofaustin/atd-prefect/pull/14/files) will come out of WIP very shortly after the KV store is worked out so it can be controlled via the Prefect UI.
