### ISSUE TITLE
[ROW] Data Discrepancy for May Cost of Service (COS) JV Records

### ISSUE THREAD

**Issue by ChrispinP** [cityofaustin/atd-data-tech#9422]
**Issue:** There were 92 cost of service fees in May that were JV'd  **and** voided, which should never happen.

**Cause:** The workflow currently used by ATD Finance uses outdated data to perform JVs, so the voided payments are not updating the data sheets being used, causing finance to transfer money on voided fees. 

**Solution:** ATD Finance will reconcile their data files against KNACK Void data just before processing the transfers. DTS will add a feature to view the voided fees to make the reconciliation possible. See #9567

**Comment by ChrispinP** [comment]
@johnclary @mateoclarke

**Comment by johnclary** [comment]
thanks @ChrispinP. I propose:
- A dev runs [this query](https://github.com/cityofaustin/atd-cost-of-service-reporting/blob/production/queries/fees.sql) against the AMANDA DB and provides the output to @ChrispinP
- If any of the fees which have been archived in Knack are present in the query output, we've got an ETL problem. Those fees would need to be modified in Knack to **not** be archived.
- Further debugging of the ETL script would be necessary but not urgent

If all of the fees in Knack are correctly archived (they do not exist in the AMANDA query output), then we need to involve Tracy and Melissa to figure out why these voided fees were JV'd and what to do about that.

**Comment by mateoclarke** [comment]
@johnclary to make sure devs have access to AMANDA Oracle DB via 1PW

**Comment by ChrispinP** [comment]
John confirmed all records were not in the dataset. Melissa requesting a meeting to go over in greater detail what makes a COS fee record active vs archived and how the JV update affects that.

@johnclary would you like to schedule this meeting with Finance?

**Comment by johnclary** [comment]
yes @ChrispinP will schedule - thanks

**Comment by TracyLinder** [comment]
@ChrispinP can you please email me the spreadsheet w/ the records?

**Comment by TracyLinder** [comment]
### 6/24/22 Meeting w Finance
_Tracy, Chrispin, Peggy, 

- Task: Analyze the voids - who did them, what date, why did that happen? 
    - We need data to move forward. 
    - Re-meet at 2:30

- PERMISSIONS: Access has been denied by CTM who referred to an audit that requires controller's approval.  
-

**Comment by TracyLinder** [comment]
**Issue:** There were 92 cost of service fees in May that were JV'd  **and** voided, which should never happen.

**Cause:** The workflow currently used by ATD Finance uses outdated data to perform JVs, so the voided payments are not updating the data sheets being used, causing finance to transfer money on voided fees. 

**Solution:** ATD Finance will reconcile their data files against KNACK Void data just before processing the transfers. DTS will add a feature to view the voided fees to make the reconciliation possible. See #9567 



----
**Closing**
