### ISSUE TITLE
Activity Log lookup map not being used in Activity Log Feed

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-data-tech#9423]
In Moped Editor, the Activity Log feed has a regression where the map of lookup values for records with foreign key relationships is no longer used. This may be intentional, but, if not, the UI is still making a request for the data every time the log renders. We should either restore the lookup functionality or remove the custom hook and query from that view.

**_I'll confirm and provide screenshots once the activity log is patched up_** 📸 

TLDR: 
In the activity log feed, a project personnel `role_id` of 1 translates to "1" instead of "Project Manager"
In the activity log details modal, a project personnel `role_id` of 1 translates to "Project Manager"

- [Example of a configuration for the activity log lookup](https://github.com/cityofaustin/atd-moped/blob/9bc6f9bc79b202d6795be7b7296ea513e84c61a6/moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js#L433)
- [Lookup hook not fully implemented in ProjectActivityLog component](https://github.com/cityofaustin/atd-moped/blob/9bc6f9bc79b202d6795be7b7296ea513e84c61a6/moped-editor/src/views/projects/projectView/ProjectActivityLog.js#L76)
   - Doesn't expose the `lookupMap` returned from `useActivityLogLookupTables` but still calls `getLookups` which fires the request that populates the map
- [Lookup hook fully implemented in ProjectActivityDialog component](https://github.com/cityofaustin/atd-moped/blob/9bc6f9bc79b202d6795be7b7296ea513e84c61a6/moped-editor/src/views/projects/projectView/ProjectActivityLogDialog.js#L77)
   - Uses the `lookupMap` returned from `useActivityLogLookupTables` 

PR to patch this issue for project phases for Moped 1.4 release https://github.com/cityofaustin/atd-moped/pull/677

**Comment by mddilley** [comment]
Screenshot of the bug
![Screen Shot 2022-07-15 at 5.54.31 PM.png](https://images.zenhubusercontent.com/5cfe7d078509cb6dcbaafdc3/f1f4b3b1-c62e-45ea-a033-c0b37098a533)

This is the PR where this hook was originally implemented: https://github.com/cityofaustin/atd-moped/pull/229/

Looks like a regression which is probably due to a confusing implementation (my hands are all over this). I could clean it up and make the custom hook's purpose more obvious.

**Comment by mddilley** [comment]
After looking at this some more, there might be some code that was added later on that does this same exact thing in the `ProjectActivityLog` component (check out `userList` and `phaseList`). If so, we might be able to cut out the `useActivityLogLookupTables` custom hook altogether.

**Comment by johnclary** [comment]
Some of this work may get done via https://github.com/cityofaustin/atd-data-tech/issues/11000

**Comment by johnclary** [comment]
@chiaberry i'm inclined to close this since this will be resolved by #10896.

**Comment by chiaberry** [comment]
it will get resolved yes! ill close it for those endorphins
