### ISSUE TITLE
Implement Weighted Average Unit Costs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#944]
** Pending clarification from finance staff on 12/9 **

We're told that we need to track unit cost as a weighted average of (quantity received * unit cost at time of purchase). But need more clarification. Will very likely need to add a unit cost field to restock transactions to manage this.

**Comment by johnclary** [comment]
I reached out to Dan, Van, and Peggy for clarification:
> Hi all—we need some clarification on how unit cost should be tracked in the inventory system.
> 
> I understand it should be weighted average, so if we purchased 10 units of Material A on January 1st for $1/each, and 5 units of Material A on February 1st for $2/each, the weighted avg unit cost would be: (10 * 1) + (5 * 2) / (5 + 10) = $1.33.
> 
> Is that right?
> 
> My question is how the weights should be changed over time. Does that weighted average need to be continuously updated as we use the material we purchased at $1/ea? I'm hoping you tell me there's a less onerous way of tracking this.
> 
> Happy to set up a call if needed.

**Comment by johnclary** [comment]
Schedule meeting for 2/13.

**Comment by johnclary** [comment]
Per finance, the logic is:

- (old unit cost * old quantity) + (new unit cost * new quantity) / (old quantity + new quantity)

@dianamartin see if you can use the Knack calculation fields for this.

**Comment by dianamartin** [comment]
@johnclary This is what I configured yesterday: [Yagi inventory item details]9https://atd.knack.com/finance-purchasing#inventory/inventory-item-details/5b773da7fb0fe322c3902845/)

New Fields Created
- `Total On Hand` - Text formula (coming form inventory items)
- `NEW UNIT COST` - new unit cost of inventory item
- `PREVIOUS UNIT COST` - old unit cost from previous record
- `UNIT SUM` - the calculated amount (new cost*total on hand amount)
- `OLD UNIT SUM` - the calculated amount (old cost* total on hand amount)
- `Quantity` - the amount of Total On Hand items (adding old stock + new stock, ex. 10 on shelf, 10 being restocked = 20)
- `ADD UNIT SUMS` - field that calculates the old unit sum and new unit sum
- `DIVIDE TOH` - taking the `ADD UNIT SUMS` sum and dividing it by the `Quantity` to get new unit cost for that item after being restocked. 

![image](https://user-images.githubusercontent.com/21112975/75383548-27914700-58a2-11ea-8b0c-27c947c1e0b3.png)

![image](https://user-images.githubusercontent.com/21112975/75383530-1e07df00-58a2-11ea-99c0-6a3fa40cc166.png)

**Comment by johnclary** [comment]
Done. The weighted cost is calculated on the fly with [custom js](https://github.com/cityofaustin/atd-knack/commit/26c2464732202157d3b35fbad207c4248909e5f6). This happens during the restock process. The new unit cost is set directly on the `inventory_item` record, and also inserted into a historic `invtentory_unit_cost_log` object.

![Screen Shot 2020-11-16 at 4.05.14 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/ffb8fb1f-6ad2-4fd7-9aad-7c4a5c810e72)
