### ISSUE TITLE
Feature: Create simple data entry in Traffic Register - Admin backfill

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9447]
reference #9248 

After much discussion, the admin team has concerns about the import spreadsheets. Would like to have an easier solution. Chrispin suggested putting the fields they typically in the spreadsheet and doing a data dump and we'll correct the data later before the app goes live. 

![image](https://user-images.githubusercontent.com/21112975/173090634-12c159df-a0a4-4be1-afa0-8ff2acafe214.png)

**Comment by dianamartin** [comment]
# Steps to take
- new object for data entry - match to their spreadsheet fields and order (Regulation Item)
  - ParentReg: nothing is connected, but will connect afterwards

## Post Entry Steps
- [ ] Export the data and separate records into parent records and child records 
- [ ] Need to categorize installs v. retires
- [ ] Confirm connection fields
- [ ] Re-import two tables

**Comment by dianamartin** [comment]
Syncing today 6/15 about Admin table and Manage Streets in Traffic Register. Close after meeting.

**Comment by ChrispinP** [comment]
**App Administration menu:**
![image](https://user-images.githubusercontent.com/67915167/173940285-cb06d51a-3740-4d1f-bbfe-631347cd0d95.png)

**Add Regulation Item button and table:**
![image](https://user-images.githubusercontent.com/67915167/173940418-7fd2c0c7-84e9-4b3b-a7d7-487fed8e1016.png)

**Backfill form:**
![image](https://user-images.githubusercontent.com/67915167/173940527-7a6f80b6-0716-4be5-aadf-5cebb27abadd.png)

Edit form is the same. Made sure all data entry users are in the app and cleanup up all test records. Pending SSO completion for Backfill Go Live.

**Comment by ChrispinP** [comment]
Updated help text, updated Side Direction values, and added text formulas for adding FT to offset distance fields. This process is now active.

Ready to review and close

**Comment by ChrispinP** [comment]
Updated Display rules for Intersections to show From Street as Cross Street:
![image](https://user-images.githubusercontent.com/67915167/175396514-d6b4e524-69be-4ae6-af94-bcb0f0454d93.png)

**Comment by ChrispinP** [comment]
Primary Street was also disabled from being required to be left blank for inaccurate streets.

Admin staff have successfully entered over 300 records.

Complete, Closing
