### ISSUE TITLE
Discovery Day: UX/UI certificate course

### ISSUE THREAD

**Issue by tillyw** [cityofaustin/atd-data-tech#9450]
Begin Google UX/UI certificate course on [Coursera](https://grow.google/certificates/ux-design) to better understand these principles when I am adding features and enhancements to our products.

**Comment by maccallump** [comment]
Tilly, 

Did you check to see if any of this content is available on linked in learning?  The city has an account and it might be less expensive.

**Comment by tillyw** [comment]
> Tilly,
> 
> Did you check to see if any of this content is available on linked in learning? The city has an account and it might be less expensive.

Thanks, @maccallump! I wanted to try out the Google/Coursera course because I'm interested in potentially obtaining the Google UX certificate. Thankfully they offer a week free trial so this came at no cost!
