### ISSUE TITLE
Show projects' council districts

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9456]
Use cases
- Reports based on council district
- Traffic Engineering will want to restrict by engineer area (composed of council districts)

Potential approaches
- open text
- calculate based on project component geometry like [location assignment to council districts in Data Tracker](https://user-images.githubusercontent.com/1463708/173134189-a94e3f70-9b0f-4d8e-8923-0936e37c88f1.png)

**Comment by johnclary** [comment]
This feature is covered by
- https://github.com/cityofaustin/atd-data-tech/issues/10889
