### ISSUE TITLE
Make users followers of any project they create

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9457]
If a user creates a project, it doesn't automatically show up in their dashboard. We're going to take @chiaberry's advice and have users automatically follow any projects they create.

**Comment by johnclary** [comment]
+1 i really like the unified view projects relevant to me. tabbing it out makes it hard to find what i'm interested in.

**Comment by amenity** [comment]
Future hopes and dreams can live [here](https://github.com/cityofaustin/atd-data-tech/issues/3683).
