### ISSUE TITLE
Align status edit permissions mismatch

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#9472]
Restrict the editing and deleting of all Moped comments to the author of that comment. 

---
_@chiaberry's original context_ 

In the ProjectComments component, we prevent editing comments unless the user is the author of the comment or an admin
https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/views/projects/projectView/ProjectComments.js#L288

However, when adding or editing statuses from the Project Summary page, we don't check any permissions:
https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js#L172

Which is the preferable track to take? Allow all editing of statuses, or restrict to only status/comment authors? 
If anyone can edit a status, should we include a note after a status has been edited? Should we include one anyway?

Another mismatch, when someone (an admin) edits another user's status update, we don't update who the comment author is. 
But if anyone edits a status update from the project summary page, the comment author gets replaced by the new user.

**Comment by mateoclarke** [comment]
We discussed this briefly in Dev Planning but decided we needed @amenity's input

**Comment by amenity** [comment]
@chiaberry @johnclary - my inclination would be to restrict all comments to be edited only by their author. I dunno why an admin needs the ability to edit comments.

**Comment by amenity** [comment]
Just saw John's personal opinion and updating the issue accordingly.

**Comment by amenity** [comment]
@chiaberry - do you feel comfortable providing an estimate on this one, or would you like to discuss in grooming?

**Comment by chiaberry** [comment]
I think it should be a 2, unless we get into adding "edited" and/or "last edited" dates in the database, then i'd bump it up to a 3 and we'd need to discuss a bit in grooming.
