### ISSUE TITLE
Make Updates to DOLA from User Testing Feedback

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9488]
Have reviewed the user feedback and will let SMS stakeholders know.

**Comment by patrickm02L** [comment]
Follow up to #8643

**Comment by dianamartin** [comment]
User Feedback
![image](https://user-images.githubusercontent.com/21112975/202237292-6063d5b6-01c9-4b34-a2d2-ece50408dcf7.png)
