### ISSUE TITLE
Add ability to create a new note

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9497]
A user with editor access should be able to create a new note

- [x] Conditionally display form field for "Date" and "Note" text if user is an editor. Hide when user only has read-only access
- [x] Use current date as default, but allow user to select date with datepicker UI. Highlight date field with focus when active.
- [x] When the user clicks "Add" button, send a graphQL mutation to insert a new record into the `notes` table.
- [x] Include info about current user with graphQL mutation for DB storage and display in "Updated by" column. 

_An open question we may need to re-address in the `notes` DB schema is if we need to store the `created_by` data as a user_id or as an email address. This depends on what's easiest to pull from Auth0, our user management and external authentication database/provider. We'll need to reference the the Users/Staff page to review queries and Auth0 data._

![Notes – Edit mode.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/edc305ba-433a-4a5b-ab20-e722534a1421)

**Date Picker**
Defaults to the current day. Highlights when selected.

![Notes – Edit mode – date picker.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/bc7bf22f-07e3-4b23-a382-0d55882859df)

**New Notes Input**
Highlighted when selected. Input field should grow vertically to accommodate text that exceeds the width of the input box.

![Notes – Edit mode – text box.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/ad25a83d-1135-4d8d-9e6f-f6c6b7b8401e)

**Comment by patrickm02L** [comment]
After the VZ Sprint Review meeting 7/7/22, in which we got feedback from the VZ team, we've decided to replace the date picker with a time stamp. The thought is that creating a note should be a singular event that is meant to create documentation on that date.
