### ISSUE TITLE
Add ability to edit & delete an existing note

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9498]
Editing will allow staff to make small changes to existing notes. Date will remain the same after editing.

In order to edit, user will click on pencil button. Text box will highlight blue, and user will have the ability to make changes to the text. 

User can choose to save the updated text by selecting the blue check mark button, or exit editing by clicking on the red X button. 

![Notes – Edit mode – previous note – 1.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/6a623b78-9fb5-4dee-ada8-114cd768ceda)

**Comment by amenity** [comment]
@mateoclarke - this will be up next for Rose.

**Comment by patrickm02L** [comment]
@mateoclarke I've updated the description for this Issue and added a new mock-up. Please add any technical specs that are needed.
