### ISSUE TITLE
June SD2023 Reporting

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9502]
We have three items that are scheduled in June that need updating, probably need a new issue for these.

Data received: 
Data | Measure ID | Contact
-- | -- | --
- [x] | M.A.2.b | Lance B, Allyson R
- [x] | M.A.5.b | Lance B, Allyson R
- [x] | M.C.6.b | Nathan W

Narrative received: 
Data | Measure ID | Contact
-- | -- | --
- [x] | M.A.2.b | Lance B, Allyson R
- [x] | M.A.5.b | Lance B, Allyson R
- [x] | M.C.6.b | Nathan W

**Comment by Charlie-Henry** [comment]
Worked though the reporting details with Natalia, Allyson, and Lance about the two travel time PMs. Both story pages are updated.

Just waiting for narrative update to the bike network completion data.

**Comment by Charlie-Henry** [comment]
I have the last text updates in my inbox, have a meeting with @katelunceford to show her how to update the story pages in Socrata.

**Comment by Charlie-Henry** [comment]
Kate updated the last story page so I'll close out this issue!
