### ISSUE TITLE
SD 2023 Reporting

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9503]
Updating Strategic Direction Socrata datasets. Working toward goals for 2023. There are other goals that reference 2029.

[SD 2023 Dashboard](https://data.austintexas.gov/stories/s/Mobility-Dashboard/gzb5-ykym/)

**Comment by amenity** [comment]
CM Garza retired SD23 - TBD what strategic reporting processes we'll use going forward.
