### ISSUE TITLE
1:1 meetings with Dev team

### ISSUE THREAD

**Issue by rebeccabrand** [cityofaustin/atd-data-tech#9505]
### Objective 
For Rebecca to meet members of the DTS development team, allowing her to familiarize herself with the team's work and flag any potential collaborations for her summer fellowship projects. 

### Participants
- [x] Meeting with Chia @ 10:30 AM EST, 6/16

- [x] Meeting with Frank @ 12 PM EST, 6/16

- [x] Meeting with Tilly @ 2 PM EST, 6/16

- [x] Meeting with Mike @ 4 PM EST, 6/17

- [x] Meeting with Charlie @ 2:30 PM EST, 6/22

- [x] Meeting with John @ 11:30 AM EST, 6/22

### Agenda
No specific agenda, but will use this template if need be. 
(https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and add link. 

------
- [x] Schedule meeting(s)
- [ ] Optional: Schedule debrief(s)
- [ ] Meet and take notes
- [ ] Optional: Debrief with DTS team members (NA)
- [ ] Create resulting issues

**Comment by rebeccabrand** [comment]
Finished these intro meetings @patrickm02L, unless you think there's anyone else I should meet with.

**Comment by patrickm02L** [comment]
It's good to close.
