### ISSUE TITLE
Conduct VZ discovery to determine how to build VZ/Moped Viewers

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9510]
On 6/16 Rebecca and Patrick talked about what we needed to suss out what to build for the Vision Zero/Moped Viewers. It will include a combination of reviewing the research from last year's CIC Fellow, comparing NYC Vision Zero Viewer and ATX VZV and reviewing current Issues for Viewer builds. 

Reference: 
- [Research Summary](https://docs.google.com/presentation/d/1oqPyPEg_Gyt4_mYj-t4ZFob5tdqsX296taAe7O8dSLM/edit#slide=id.gb858504152_0_360)
- [NYC Viewer](https://vzv.nyc/)
- Issue #9453

Add finding to the Issue and set up a meeting with Amenity and Patrick to discuss potential plan for building.

**Comment by rebeccabrand** [comment]
Making a Miro board to compile [initial thoughts & findings here. ](https://miro.com/app/board/uXjVOsWhYcQ=/?share_link_id=203291198518)

**Comment by rebeccabrand** [comment]
Hi @patrickm02L - I'm updating the time estimate from a '3' to '5' - 3 full days might be a stretch, but it's taking me a bit longer than 1 full day to record everything. Plus, I'm hoping to discuss doing some mockups as part of this discovery section.

**Comment by patrickm02L** [comment]
Sounds good. Can you send a meeting invite to @amenity and me when you feel like your at a finishing point?

**Comment by rebeccabrand** [comment]
Working on some XD mockups here: 

https://xd.adobe.com/view/03bb86d3-02c8-4124-8921-b48a5b032976-56e8/

Let me know if this link doesn't work for you.

**Comment by rebeccabrand** [comment]
Presented progress to Patrick & Amenity on Monday, 6/28.

Refined presentation for Moped Sprint Review on Tuesday, 6/29. 

The presentation is [linked here.](https://docs.google.com/presentation/d/1iNNyt2RdcqZ_d0z5rg7SnnMC4RUdkc1y32QPZrktNQw/edit#slide=id.g139f5f52248_0_20)
