### ISSUE TITLE
Deploy Hasura graphql-engine 2.7.0 to staging

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9512]
With the merge of [the-devil-is-in-the-details](https://github.com/cityofaustin/atd-moped/pull/666) into main, the `graphql-engine` 2.7.0 needs to be deployed to staging. This will require some devops, in the form of configuration changes, in AWS to deploy the correct version of `graphql-engine` in the task definition for our staging ECS cluster. 

I propose the following deployment plan: 

1) Document existing ECS task definition `atd-moped-staging` which operates in the ECS cluster `atd-moped-cluster-staging`. 
1) Create a new revision of the same task definition which deploys `graphql-engine` 2.7.0 with an increased hard limit on RAM usage (1G → 2G)
1) Deploy the new revision and confirm operational staging website
1) Turn down the memory limit until an appropriate, conservative (cost-saving) point is reached, hopefully restoring the same 1G price point we've been using.

**Comment by amenity** [comment]
_Here we go_ 🙃 

@johnclary - In dev sync, @frankhereford explained that this doesn't need to be tied to a release since there is no code involved. He actually thinks it may be better to stagger them.

**Comment by frankhereford** [comment]
@amenity wrote:
> _Here we go_ 🙃

I'm excited to get this deployed - thank you Amenity!

It would be my preference to do this well outside of business hours, ideally on a Saturday. I'll bring up this proposal today in the dev sync unless you'd prefer something else. If we could get this out this weekend, I'd then advocate for getting production rolled out after business at some point this upcoming week, and then we'd have the new graphql endpoint updated in advance of the upcoming Raccoon release. 🦝

The changes did involve some code, just not in the moped-editor app itself, which is what Raccoon Run is focused on, in my eyes. I anticipate that we'll document the merge of that code in the Changelog, and it feels appropriate to have the deployment completed too. 

Does this sound suitable to you? I'm open to any direction from you or the team - thank you!!

**Comment by frankhereford** [comment]
The group expressed support to move forward over the weekend. 🙏

**Comment by frankhereford** [comment]
This worked just as expected, including making the transition seamlessly with zero downtime apparent to any users. I'm comfortable advocating for this same change to be pushed to production this week. Thanks!
