### ISSUE TITLE
Deploy Hasura graphql-engine 2.7.0 to production

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9513]
With Hasura's `graphql-engine` having run in staging for an acceptable amount of time and passed any tests required of it, a plan to install this same version in production is required. The process should be similar to the deployment onto staging, and I will propose a punch list of deployment steps in reply to this issue.

**Comment by amenity** [comment]
@frankhereford - we were thinking that it would be good to do this during this sprint so that it can be in the next release

**Comment by frankhereford** [comment]
@amenity wrote:
> @frankhereford - we were thinking that it would be good to do this during this sprint so that it can be in the next release

I can't wait to discuss it with you today in planning, but the short-story is that I'm massively in agreement with you. Sooner the better - this sounds great.

**Comment by frankhereford** [comment]
@amenity May I pull this on-deck with an eye to complete it on Thursday after the dev sync?

**Comment by mateoclarke** [comment]
Sounds good to me Frank.

**Comment by frankhereford** [comment]
This was completed as planned today after the dev sync. Thanks everyone!

**Comment by mateoclarke** [comment]
![wizard](https://user-images.githubusercontent.com/5697474/177882495-b1187cb4-a8d9-43f7-8d34-e9a5e42127d2.gif)
