### ISSUE TITLE
Update database schema for Fatality Review Board Recommendations

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9517]
- [x] Create `fatatality_review_board_recommendations` DB table
  - id: auto increment primary key
  - crash_id: integer (foreign key to `atd_txdot_crashes`)
  - coordination_partner_id: integer (foreign key to `atd__coordination_partners_lkp`)
  - recommendation_status_id: integer (foreign key to `atd__recommendation_status_lkp`)
  - text: string
  - created_at: timestamp
  - created_by: user_id
- [x] Create `atd__coordination_partners_lkp` DB lookup table
  - id
  - description
- [x] Create `atd__recommendation_status_lkp` DB table
   - id
  - description
- [x] Populate `atd__coordination_partners_lkp` lookup table with options in dropdown. ~Confirm list with Patrick~
- [x] Populate `atd__recommendation_status_lkp` lookup table with options in dropdown. ~Confirm list with Patrick~

~Q for dev grooming: If we add a new recommendations table, how do we ensure we only have a 1:1 relationship between recommendations and crashes? Is this a better than putting recommendation info into a json on the crashes table?~

**Comment by patrickm02L** [comment]
**Coordinating Partners include:**
- CTRMA
- TxDOT
- South Area Engineering Office
- North Area Engineering Office
- Central Area Engineering Office
- Austin Energy
- Signs and Markings Division
- Public Works Department
- Corridor Program Office
- Capital Metro
- Other
![Coordinating Partners.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/4998e277-826f-4587-9108-5e4f63dea3a9)
