### ISSUE TITLE
Make Fatality Review Board Recommendations editable

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9519]
Editing capabilities on recommendations will only be available to those with `Editor` ,`Admin` , or `IT Supervisor` permissions. They will have the ability to edit `Coordination Partners` and `Status`, as well as the text update.

**Ability to Edit**
Grey pencil button is visible.

![Recommendations – Edit mode – Buttons on right.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/71018af4-0f84-4983-b54f-330922f5fcb7)

**Editing Text**
Highlighted blue when in text box. Pencil turns in a blue √  to accept changes or red X to cancel changes.

![Recommendations – Edit mode – Buttons on right 2.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/f639ffee-6f8c-4c5f-a813-c1f30431c200)

**Drop Down Menus**
If selected from the list, highlight grey and update the `Coordinating Partner` or `Status` succeeding text to match.

![Recommendations – Edit mode – Buttons on right with drop downs.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/a8577a3b-af09-4c5c-9194-b0206705c0fc)

TK: @mateoclarke to fill in feature requirements here.

**Comment by patrickm02L** [comment]
At the VZ Sprint Review on 08/02/22, Joel S. requested a way to import his Recommendations and subsequent update notes to the new tool. 

We resolved to create a template to make the migration easy from his spreadsheet where he keeps the notes to the new tool. #9892 

In that discovery, we determined that we would need to create a new field to capture those Updates in the Recommendations component. 

Here are the new comps:

**Recommendations and Updates in edit mode**

![Editable Recommendations with Updates](https://user-images.githubusercontent.com/5566727/182889307-b0e1f366-9d59-4393-8303-be7547b9eb7f.png)

**Recommendations and Updates in regular mode**

![Recommendation with Updates](https://user-images.githubusercontent.com/5566727/182889518-9bb22a42-6752-40eb-a5c6-b01521f98835.png)

**Comment by mateoclarke** [comment]
Handing off to @mddilley. Some updates:
- each field, Coordination Parter, Status, Recommendation, Updates, should have its own edit button which toggles the view/edit state.
- currently in staging, records with Recommendation data are erroring on `description` not existing
   - this one works: https://visionzero-staging.austinmobility.io/editor/#/crashes/18794029
   - this one doesn't: https://visionzero-staging.austinmobility.io/editor/#/crashes/18851626
- Recommendations Card should only be visible for crashes with `atd_fatality_count` > 0 && user is role = "Admin" or above.

**Comment by mateoclarke** [comment]
@roseeichelmann Just tagging you so you can see how Mike ended up tackling this issue.
