### ISSUE TITLE
[BUG] Exception error in local VZE Location crashes list

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9522]
**Describe the bug**

When you try to clear search field data from a Location page, you can bomb the app.
I discovered this Bug in my local dev environment and I'm curious if its a real concern/regression.

(Note: this is not currently replicable in staging or production VZE instances)

**URL**
https://localhost:3000/#/locations/644AF55CFC

**What steps can we follow to reproduce the bug you are seeing?**

1. Navigate to any location details page (ex: https://localhost:3000/#/locations/644AF55CFC)
2. Scroll down to the table of CR3 Crashes below the stats widgets.
3. Click on red Clear button for the search field and the app bombs.

**Screenshots**
![Screen Shot 2022-06-17 at 10 47 52 AM](https://user-images.githubusercontent.com/5697474/174334656-1de628c3-b04b-4bcd-9cdf-3970b7968877.png)

![Screen Shot 2022-06-17 at 10 47 32 AM](https://user-images.githubusercontent.com/5697474/174334647-6764a5ec-fc48-4554-829d-236e83a1e8ab.png)

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [ ] Major — can only perform work using a workaround
- [x] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Additional context**

**Comment by roseeichelmann** [comment]
I was able to reproduce this bug, here is the error message I got:

![Screenshot from 2022-06-17 11-49-58](https://user-images.githubusercontent.com/67130963/174343590-e29afbc4-bcfe-45aa-9efd-d520e294cc44.png)

**Comment by amenity** [comment]
This might be an edge case... can wait to see how it affects users.

**Comment by johnclary** [comment]
maybe fixed, maybe not. someday we will refactor VZ's table + search experience 👍
