### ISSUE TITLE
Enhancement: Display an alert banner when viewing a deleted project

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9525]
If a project is "deleted", it's still possible to navigate to it using the project URL. However, when viewing a deleted project, there's no way to tell that the project is in a deleted status.

We should provide obvious visual feedback when viewing a deleted proejct.

**Comment by johnclary** [comment]
@amenity FYI

**Comment by johnclary** [comment]
Good question—i say out of scope. If you want to edit a project that no one can see, I say have at it?

**Comment by amenity** [comment]
Agreed.

**Comment by johnclary** [comment]
use an MUI alert above the project title, full-width
https://v4.mui.com/components/alert/
