### ISSUE TITLE
Transpose context from COA website to Dockless Online License Application

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9527]
Feedback from User testing revealed the information on the DOLA may be redundant. In order to resolve the issue of redundancy we observed that a comparison of the content from the [COA License page](https://www.austintexas.gov/page/shared-mobility-regulations-and-license-application) and the [DOLA portal homepage](https://atd.knack.com/smrt#portal/) should be consolidated/edited for efficiency.  

We'll need to work with SMS staff to determine what content to keep and what the information architecture should be in order to provide the best information for an applicant in either content location.

- [x] Set up 1:1 with Mary V. outlining the content for both sites, ask them to parse content
- [x] Wire-framing the content
- [x] Update the content based on their feedback

**Comment by patrickm02L** [comment]
Reference the [Banners COA page](https://www.austintexas.gov/page/street-banners) for how to architect the information. 

@dianamartin will add wireframes as an example of how we'll build out the relationship between COA page and Knack.

**Comment by patrickm02L** [comment]
Meeting scheduled for 6/28/22.

**Comment by dianamartin** [comment]
- Patrick and I met on 6/28 at 11 am to prototype and wire frame the SMRT content. 
- We met with Mary on 6/28 at 1 pm to show the wire frame and discuss any changes.
- Decided to move forward with the prototype plan

## Next Steps
- [ ] Fill out PIO request form
- [ ] Update website page

**Comment by patrickm02L** [comment]
FYI: Amenity has access to the Google Analytics so we can do analysis of user behavior on the COA website.

**Comment by dianamartin** [comment]
Had meeting with PIO on 7/12 (Anton, Lauren, Susanne)
- Had to provide photo for PIO, messaged to Anton on 7/12 at 9:01 am
- Synced with him most of the day to get something modified
- Told him I'd sync with Patrick 

## Feedback
- Synced with Karo and Stephanie separately to get some initial feedback
- Patrick and I synced on 7/12
- We had modifications 

## Emailed Anton modifications 7/12
>After reviewing the page with Patrick, these are the changes we’d like to make:
 
>For the Director Rules section
•	remove the accordion ability
•	rename header to ”Get familiar with regulations for operating shared mobility services” 
 
>Would it be possible to create a button here?
•	Light Grey outline, White fill - that reads “Read the Director Rules (PDF)” that is the same length as the current “Expression of interest” button

![image](https://user-images.githubusercontent.com/21112975/178774413-5edeeb1b-1131-4ffb-85ee-3f585fda8368.png)

>For the Expression of Interest section
•	remove the accordion ability
•	Rename header to “Interested in applying for a permit to operate a car share or moped share?”

![image](https://user-images.githubusercontent.com/21112975/178774532-30e541d0-c797-41ca-8a88-2f8b4521ab7d.png)

>For the Get Started section to an accordion
•	rename header to ”License Application Information” 
•	convert to accordion feature
•	relocate information from Expression of interest section to this page
•	the “a” should be turned to “an”
![image](https://user-images.githubusercontent.com/21112975/178774616-a64b8834-abfe-4fa4-bf59-0a3d78bd9f3b.png)

![image](https://user-images.githubusercontent.com/21112975/178774709-cf85f444-e90f-433d-bbb6-793b07ea9b5c.png)

>This is the updated wireframe for you to view

**Comment by dianamartin** [comment]
Anton replied to my email
>Hi Diana, 
Thank you for your email. I will take care of these changes by Thursday, July 14.

**Comment by patrickm02L** [comment]
Connect with Anton to open Director Rules in a new tab, and delete Related links. Then Close!
