### ISSUE TITLE
Improve UI for "Staff" page

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9528]
Create design consistency across pages in Moped by updating the Staff page to reflect the latest header removal enhancement of the Projects page #9515. 

Access design improvement in [PR 687](https://github.com/cityofaustin/atd-moped/pull/687) Netlify link.

**Current Desktop View**
![screencapture-deploy-preview-687-atd-moped-main-netlify-app-moped-staff-2022-06-20-08_58_47.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/c6cfaa92-3ed5-49ce-8f95-72d7d87c845a)

**Comment by amenity** [comment]
@patrickm02L @johnclary - It would be cool to get rid of the header to match the new "Projects" page! I don't think we can justify design/dev on anything beyond the page is only visible to admins, i.e. us.

**Comment by patrickm02L** [comment]
Here's a quick and dirty mock up of how the Staff page might look with the header removed based on the Projects Page with header removed. 

**New Projects Page Example**

<img width="1510" alt="Screen Shot 2022-06-21 at 5 37 40 PM" src="https://user-images.githubusercontent.com/5566727/174908594-4990a296-8dba-4e7c-a3b1-09ce0770b576.png">

---

**Proposed Design Update**
 - Remove the "Staff" header
 - Move `Add Staff` button and `Show Inactive Accounts` toggle into the table element.
 
 **_Option 1_**
 
![Web 1920 – 1](https://user-images.githubusercontent.com/5566727/174908875-62eb73c5-3234-439b-8832-ec03ea020502.png)


**_Option 2_**

![Web 1920 – 2](https://user-images.githubusercontent.com/5566727/174908901-a5443d0d-a8dd-4d9a-bd38-f7227197fdc6.png)

**Comment by johnclary** [comment]
@patrickm02L this looks really good! what do y'all think about grouping the download button with the Add Staff button? or, if we want to be ruthless about vertical space, moving the Add Staff Button and filter toggle to be inline with the search and download buttons.

**Comment by johnclary** [comment]
We should add a column for user status. You currently cannot tell who is active or not.

**Comment by mddilley** [comment]
@johnclary I found this buried in my standup notes that I move from week to week, and I think that [Chia's Data Grid PR](https://github.com/cityofaustin/atd-moped/pull/1054) covered some of this. Just wanted to mention it while I was 🧹ing out my notes.

**Comment by johnclary** [comment]
thanks @mddilley! yep, i'm closing this out. there may be some additional enhancements but the bulk of what's described here as been taken care of 😎

**Comment by johnclary** [comment]
cc @chiaberry ;)
