### ISSUE TITLE
SIF Release Stabilization (Deploying to TEST)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9534]
## Documentation of the bugs/issues encountered until stabilization date 7/21/22.

**Comment by TracyLinder** [comment]
**Permissions 6/21**
- Amber & Nate did not have insert permissions. Gita fixed accounts / users confirmed this is fixed. ✅

**Comment by TracyLinder** [comment]
### 7/5/22 - Permissions Issues

1. Perrymnd - No longer has permissions to create a SIF folder. 

2. RAMIREDA - System throws this error when user attempts to use his task list. 
<img width="258" alt="Screen Shot 2022-07-05 at 10 09 24 AM" src="https://user-images.githubusercontent.com/49930868/177362014-7ecf0cee-a401-4085-9477-8668f9a72f85.png">

**Comment by Sreelatha-BlazeKannan** [comment]
@Nate-Nader , @TracyLinder - #9534 DEV Commit Submitted. Kindly approve and create task id for me.

Commit ID: [46e08f7839d7](http://coaamandadevops01.austintexas.gov/R3:46e08f7839d78d0c3a00293ee32a94e1b2579419)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder This has been sent to the DevOps cm team to be deployed to v6 DEV under **SCTASK0233411**

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been deployed to DEV please UAT

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder  I have sent this over to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0234669**

**Comment by TracyLinder** [comment]
### User Permissions for DONGREJ

Hi @Sreelatha-BlazeKannan can you please update SIF permissions for DONGREJ. Same as other users.

**Comment by TracyLinder** [comment]
### Update on Fee Comment Bug

The commits were not moved to the test environments because of the V7 upgrade. Per George (CTM) the fix will be pushed after go-live. @Sreelatha-BlazeKannan I'm created an issue for this so we can track it separately. #9866

**Comment by Nadin-Nader** [comment]
9866 has been resolved and is on PROD. This can be closed
