### ISSUE TITLE
Submit Support Services Alignment to SD23 Goals Form

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#954]
** Due by 12/6 **

[Sharepoint Site](https://cityofaustin.sharepoint.com/sites/ATD/AF/Lists/ATD%20SD23%20Catalog%20of%20Work/AllItems.aspx?CT=1574807681481&OR=OWA-NT&CID=190c5b83-f486-7548-0c87-8cd994688dd7).
 
From Peggy:
> I appreciate all of you providing the required information in this process.  It is important to the department and the City and will illustrate the important work that the department provides. 
> 
> This email will serve as your instructions for this deliverable.  The deadline for entering this information is c.o.b., December 6, 2019. 
> 
> This is a requirement for all divisions, units, functions and programs of the department.  When you are developing this information, please consider that the audience is not familiar with our business.  So it is important to emphasize the services in everyday language, emphasizing the benefit to the community, or the City, and include support services (marketing, Communication, Community Engagement, Finance, HR, IT).  Please do NOT use acronyms or technical jargon when adding this information.  Each entry must stand on its own, i.e. there should be no ambiguity, generalities, see another item.  Please utilize the information that we have accumulated in the department FY21 Goal work that smaller groups have been updating.  These services are key to supporting department goals and should be part of this submission.
> 
> This is the link to the SharePoint List that will accumulate all of the required information that must be uploaded to the Office of Performance Management site no later than December 20.  The December 6 deadline will provide the Executive Team with time to review, revise and update any of the information contained in this list.
> 
> To enter information:
> 
> Click on this link to go to the SharePoint List. 
>  
> To enter information:
> 
> Click on this link to go to the SharePoint List. 
> Click on the new item link.
> Complete the Form to enter each type of Program/Service that your group provides.
> Title:  Enter the name of the program/service.  If there are multiple entries for a similar service complete a form for each entry using the following naming standard:  Program/Service: Function.  Example: Financial Support: Contract Compliance or Transportation Engineering: Resident Communication.
> Point of Contact:  Identify the lead individual for this Program/Service (whomever is the person people call to get answers to questions about this program/service)
> Divisions: Identify the division responsible for this work (primary)
> Program/Service Description:  Two sentences that provide a clear description of the program/service.
> Program/Service Keyword: Select the keyword that relates to the program/service.
> Program/Service Audience: Select the audience who is intended to provide this program or service.
> Legal Requirement: Is this program/service legally required?  Yes or No
> Provide a link to the City Charter, Regulatory requirement, or legal judgement.
> Program/Service website: Provide a link to the website (if any).
> Program/Service Aligns to Department Goal:  Select the Department Goal this program/service supports.
> What SD23 Outcome does this program/service align? 
> If Culture and Lifelong Learning Outcome is the above alignment, then use the definitions available here, to identify the strategy number.  If not, leave blank.
> If  Economic Opportunity & Affordability Outcome is the above alignment, then use the definitions available here, to identify the strategy number.  If not, leave blank.
> If Government that Works for All  Outcome is the above alignment, use the definitions available here, to identify the strategy number.  If not, leave blank.
> If Safety Outcome is the above alignment, use the definitions available here, to identify the strategy number.  If not, leave blank.
> If Mobility Outcome is the above alignment, use the definitions available here, to identify the strategy number.  If not, leave blank.
> Select the Program/Service Partners that you collaborate with.
> Click Save.
> Enter the next item.
>
>Follow these instructions for all of the program/services that your division, unit or program provides.

**Comment by amenity** [comment]
@johnclary - do you need any help with this?

**Comment by johnclary** [comment]
@amenity it's done. closing.
