### ISSUE TITLE
Project: Private-Public Partnership (P3) Management

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9540]
Smart Mobility Office staff would like to track new projects by private sector organizations wishing to propose smart mobility projects.

## Background

The Smart Mobility Office would like to improve the workflow and management of smart mobility projects. They currently have a process that requires them to download responses and then populate them into a tracking spreadsheet. It's a fairly manual process and not integrated into one system. 

## Scope & Deliverables

- External form that private sector organizations can fill out Expression of Interest
- Tracking project records from expression of interest to tangible project
- Allow SMO staff to have ability to track progress and have checklists for different aspects of the project

## Desired Outcomes

Would like to utilize Knack to create a system workflow. The project would entail a public facing application which is routed through internal processes. Workflow automatically tracks data and routes to appropriate parties.

## Timebox

The SMO team is excited to be able to centralize the data they track and have it be more user friendly for both private organizations and their staff. There isn't a specific time frame. 

## Concepts and references
- [Expression of Interest form](https://docs.google.com/forms/d/e/1FAIpQLSfbR48BiW-y7g7nX9amCdHEk6L2vqjnhD2lUqNleQ_TKV49oQ/viewform)

![image](https://user-images.githubusercontent.com/21112975/175657059-cd87b9fc-54c7-4e1e-9748-aefff01a3e4b.png)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by KaroEngstrom** [comment]
## Th 9/22/22

### MVP OVERVIEW

**EOI Phase** 
![image](https://user-images.githubusercontent.com/100615928/191780580-a0abf732-5f55-4de7-a66d-2c6117e6317f.png)

**BCA Phase - Vetting**
![image](https://user-images.githubusercontent.com/100615928/191781081-0c5610b0-80ca-4f61-9d3b-2fb377f7f5e9.png)

**BCA Phases - Contracting > Commissioning > In-Service > Close-Out**
![image](https://user-images.githubusercontent.com/100615928/191781644-56097952-5f01-4ffa-8077-6b5172c37517.png)

**Comment by KaroEngstrom** [comment]
## T 11/1/22 

All issues completed; feedback from stakeholders: "everything has been working well. No feedback from the team, which means everything is running smoothly." 
P3 in Knack is officially in maintenance.
