### ISSUE TITLE
Make SIF Info 84034 Mandatory on PR (UAT in V7 TEST))

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9541]
**Info 'SIF Required' (84034) needs to be mandatory on the PR folder**

**Comment by Sreelatha-BlazeKannan** [comment]
- @Nadin-Nader , @TracyLinder , @vschandramouli  - DEV Commit submitted. Please approve and create task id for the same. Commit ID: [fe6e05b619c3](http://coaamandadevops01.austintexas.gov/R3:fe6e05b619c3bddda5e067afc6e79308c2fb05dc)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan This has been sent to the DevOps CM Team to be deployed to **_DEV_** under **SCTASK0228442**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder , @vschandramouli  - Tested in DEV and it is working as expected. Submitted Test DP. Please approve and create task id for the same. 

Here is the screent shot - 
![image](https://user-images.githubusercontent.com/44907715/176211846-099af678-9b2b-4c74-accd-d3a99a37ce23.png)

Commit iD: fe6e05b619c3

**Comment by Nate-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder i have sent this over to the DevOps CM Team to be deployed to **_TEST_** under **SCTASK0229102**

**Comment by TracyLinder** [comment]
I've asked Amber (ATD) and Makenzie (DSD) to test.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder , @vschandramouli - Tested and working as expected in TEST. Ready for UAT and PROD Move.
![image](https://user-images.githubusercontent.com/44907715/176257772-f64268fd-d9e0-4fdf-be6a-f46279a16cb9.png)

**Comment by TracyLinder** [comment]
We need DSD to test - Mackenzie is out ill. Tracy needs to ask for another tester.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan @Nadin-Nader can you please promote to PROD?

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan @TracyLinder this has been sent to the DevOps CM Team under **SCTASK0233409** to be deployed to V7 TEST

**Comment by TracyLinder** [comment]
**Next Step: UAT in V7**

**Comment by TracyLinder** [comment]
### V7 UAT Passed
_ROW ID 12873761_
