### ISSUE TITLE
DS & EX Automated Email - Jessica D. INC0203755 (On Prod)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9559]
### The system is sending DS payment reminders to users who aren't associated with the folder. 
**This needs to be de-bugged.**

![image](https://user-images.githubusercontent.com/49930868/175376612-1f1f4cde-0ad0-4a24-935c-fa4ef27b5b12.png)

----
**Here is another example:**

<img width="1300" alt="Screenshot 2022-10-25 at 3 48 52 PM" src="https://user-images.githubusercontent.com/49930868/197879142-fbbe7b34-3724-4e94-b941-e6c3058c00eb.png">

**Comment by TracyLinder** [comment]
Paloma asked for an update on this. We need to debug.

**Comment by Nadin-Nader** [comment]
Another example is:

![MicrosoftTeams-image (19).png](https://images.zenhubusercontent.com/5e8dfbfabf171441c3a5684e/7397cf05-2490-42ad-b2e3-0aef2f8e60fa)

**Comment by Nadin-Nader** [comment]
Analysis on hold. Priya is working 10690 first

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Commit done, Requested for Dev and Test deployment
Request number - SCTASK0261686

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV and TEST. Please verify and let me know if all is well for stakeholder UAT on TEST

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT this has been deployed to DEV and TEST. Please verify and let me know if all is well for stakeholder UAT on TEST

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes in the commit are not reflectig in Test environment. Checking with DevOps team.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Reverted the previous commit and re committed changes. Created dev and test deployment request - SCTASK0265584

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT This has been deployed. Please UAT on DEV and TEST

**Comment by TracyLinder** [comment]
### Update
- It's difficult to test batch jobs, we're not sure we can on this one. 
- Tracy recommending that we push to PROD & see if anything funky happens. 
- We need to inform Candace Cal. when this goes to PROD so she can keep an eye out for customer communications.

**Comment by TracyLinder** [comment]
### Approved for PROD

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader @TracyLinder Changes are promoted to Prod

**Comment by Nadin-Nader** [comment]
Closing
