### ISSUE TITLE
[BUG] Update seed data with additional users

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#9560]
**Describe the bug**
Include what happens and what you would expect to happen. 

Added account for Rebecca in moped staging. Logged into  moped-test and her account is unable to see any project page and instead gets this error. 

![Screen Shot 2022-06-23 at 2 29 37 PM](https://user-images.githubusercontent.com/12474808/175382634-12432e83-487f-4c5d-9e41-f8227d38b9ac.png)

Her account is able to view projects in staging. https://moped.austinmobility.io/moped/projects/1754

**URL**

**What steps can we follow to reproduce the bug you are seeing?**

**Screenshots**

**Device**

**Browser**

**How would you rate the impact of this issue?**
- [ ] Severe — cannot perform work, no workaround
- [ ] Major — can only perform work using a workaround
- [ ] Minor  — can perform work, but could be easier or faster
- [ ] Does not affect work performance
- [ ] Unsure

**Additional context**

**Comment by chiaberry** [comment]
I can sign in locally with her credentials. I checked the permissions for subprojects (her account is an editor acccount), but all the permissions for editors exist for parent_project_id

**Comment by chiaberry** [comment]
This is where the error is coming from
https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/views/projects/projectView/ProjectView.js#L198

when I sign in as Rebecca and check `localStorage.atd_moped_user_db_data`, it comes back as the string `'undefined'`

**Comment by mateoclarke** [comment]
So we just need to add folks to the seed data if they wanna use test, right?

**Comment by chiaberry** [comment]
Yes, i just need to look up the correct user IDs on staging and then add
matching entries in the seed data. I'll add them in one of my next PRs.
