### ISSUE TITLE
ROW Portal [COS] - Show Voids & Make Filters

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9567]
### Finance staff needs to see the voided COS payments in the data table, but only when they want to look at it. 

**To-do:**
1. Show VOIDED payments in existing table
2. Add data filters for PAYMENTS, VOIDED, VOIDED with JV
- PAYMENTS should exclude voided records.
3. Default table view to PAYMENTS

**Comment by TracyLinder** [comment]
### Stakeholder review meeting scheduled for Friday July 1st.

**Comment by ChrispinP** [comment]
### Added a COS Menu to toggle between two tables: Pre Filtered and Custom Filtered. Defaults for Custom Filter set to if Voided fees have JV IDs
![image](https://user-images.githubusercontent.com/67915167/176000756-dfe742fe-bbad-434f-b6de-b7a3603507be.png)

### New Pre-Filtered table is a copy of the original table. Defaults to Payments filter. Added filters for Voided, JV IDs Blank, All, and one for each of the departments.
![image](https://user-images.githubusercontent.com/67915167/176001204-75777fb9-8ac8-4795-a376-527827f94a6f.png)

### Made the Permit Description field wider to eliminate a lot of scrolling to get to the bottom. Could be improved further by removing the column.
![image](https://user-images.githubusercontent.com/67915167/176001497-fe317309-2c2d-4256-bba0-b6d5e0c50d5c.png)

### Voided (is_archived field) is now added to the tables.
![image](https://user-images.githubusercontent.com/67915167/176001836-59fee1df-0043-4be3-9cfe-f3b02303462a.png)

Ready to Review

**Comment by TracyLinder** [comment]
### Stakeholder Review

It went great. They love it. Closing.
