### ISSUE TITLE
[Spike] Barton Springs Kiosk Cash Reconciliation

### ISSUE THREAD

**Issue by Charlie-Henry** [cityofaustin/atd-data-tech#9568]
ATD does some accounting work for the Barton Springs pool pass kiosks. This spike is to see what we can do to help Finance with monitoring the cash transactions, collections, and the deposits in the City's Controllers account. 

What I've learned so far:
- It appears that the Flowbird Hub is where most of these transactions are taking place. It is possible that some transactions are captured on Smartfolio as well.
- Flowbird Hub has a "Cash Collection Analysis" table where we can see each time a kiosk's cash was emptied.
- I've matched these cash collection events up with the preceding cash transaction data. It is fairly simple to do in Python but the ETLing this would be more effort.
- We can see the cash deposits in the city bank account using the Controller's reports tool Ashlande shared with us. 

I'll set up a 1:1 with Peggy to see what she thinks about setting up a Power BI dashboard that would compare the deposits, transactions, and collections of cash at all parking kiosks (or just limited to Barton Springs?).

**Comment by Charlie-Henry** [comment]
Met with Peggy today. She thinks it would be a good idea to build a mock-up using some static data for the parking meter cash transaction reconciliation. Show it to Denice and Ashlande sometime next week is the plan

**Comment by patrickm02L** [comment]
@patrickm02L heads up!

**Comment by Charlie-Henry** [comment]
Going to close this out, completed the spike here. Might have some work down the line after Ashlande and finance do some more digging on this.
