### ISSUE TITLE
Set up trigger that our team to add geospatial data whenever Shift Creator creates new Location

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#958]

**Comment by amenity** [comment]
@SurbhiBakshi - did you already implement this? @dianamartin pointed out that there isn't a resource account for the GIS team

**Comment by SurbhiBakshi** [comment]
@amenity right now, I have set up an email notification for the transportation data email account. So whoever is triaging the email can send it to the GIS team. The functionality has been set up. I think next steps would be to document process for the GIS team to assign data tracker locations, and then test that process.

**Comment by amenity** [comment]
@SurbhiBakshi Okay, I'll close this one then and creating #1042
