### ISSUE TITLE
Projects Map | Conduct user research

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9597]
### Objective
Set up interviews with Transportation staff who from the MUG (Moped User Group) who have insights about what they expect from the Moped Viewer and how it will affect their experience.

Sub-tasks include:

- [x] User interviews
- [x]  Notes synthesis
- [x]  Affinity mapping
- [x]  Translate to feature requirements
- [x]  Follow up with any questions

### DTS Examples
- [Moped 0.7.0 Usability Testing Artifacts](https://drive.google.com/drive/folders/1WH2a_0p-6_83aAUQ86ZIQyKr130E9kMz) - think-out-loud testing
- [Moped requirements gathering](https://drive.google.com/drive/u/0/folders/1NYqaRT7IczU3d-vx9PFZKjtvpvxP58f5) - User interviews

**Comment by rebeccabrand** [comment]
@amenity - I'm working on the usability testing plan [here.](https://docs.google.com/document/d/13DYTyX7TfqRlsf4h2-PN0LkpjofmIc6GXunJ5Xr1n6A/edit#)

**Comment by rebeccabrand** [comment]
Rebecca has completed the user research stage of this design process, having developed a plan to design an internal and external version of the Moped Projects Map & Project Viewer respectively.

Closing out this issue with access to:
- [Notes from user tests](https://docs.google.com/document/d/1Z2WEATr6q0DCPjBwF289SvCZvMrIkt-zk4T5jCUXy5M/edit?usp=sharing)
- [Miro board for synthesis](https://miro.com/app/board/uXjVOsWhYcQ=/)
