### ISSUE TITLE
Github Action-ify the Frank Approach to Prefect-ing 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9612]
This issue is to track work related to extending the existing GitHub actions related to deployment and CI for the proposed systems found in [PR 9](https://github.com/cityofaustin/atd-prefect/pull/9) and [PR 14](https://github.com/cityofaustin/atd-prefect/pull/14).

Criteria for success include:

* Define process for initially deploying a new script
  * Documentation
  * Example boilerplate code to wrap a script as a Flow
* On merge into `main` or other trigger branches:
  * Update existing deployments of Flow
  * Rebuild and restart docker image which serves the agent
    * Accomplish this firewall circumvention via a polling agent responsible for maintaining other project's more dynamic agents and deployments

**Comment by chiaberry** [comment]
Moving this to needs scoping, since we need to reassess as we move to Prefect 2.0

**Comment by frankhereford** [comment]
Due to our group's change in ETL direction, this is no longer applicable.
