### ISSUE TITLE
Prototype dashboard with data from current dashboards

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9613]
Based on the research from #9504 it makes sense to build out an MVP of to see how an Executive Dashboard might operate. 

Using data from the following dashboards:
- Signs and marking 
- MMC
- Vision Zero
- Capital Metro

We're looking to create a single dashboard that's an amalgamation of other dashboards so that other teams can continue to use what they've created while we reference their data. 

Also need to follow up with points of contacts who maintain the dashboard data. Suzanne G. in Signs, Allison R. & Lance B., Xavier A., and someone from CapMetro.

[Prototype miroboard](https://miro.com/app/board/uXjVOrZDQA8=/)

**Comment by Charlie-Henry** [comment]
Patrick and I met today and created a template for what these dashboards could look like.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/30810522/178538626-0c39503c-b94a-49de-9d97-e880de976766.png)


Starting ideas for report tabs:
- Finance
- Vision Zero
- Operations

**Comment by patrickm02L** [comment]
Meeting with Charlie on 7/19/22 to go over functionality and approach to building out the dashboard. Will bring to the afternoon Dev Sync. 

In between this note and then, Patrick still needs to make design refinements if there are any for Charlie to update in PowerBI templates that were created.

**Comment by Charlie-Henry** [comment]
Data sources for some ideas for each tab:
- Finance
  - Parking revenue (private socrata dataset currently)
  - Bond progress dashboard (currently a excel spreadsheet on OneDrive)
  - [Finance data](https://github.com/cityofaustin/atd-finance-data)
     - [task orders dataset](https://data.austintexas.gov/Transportation-and-Mobility/-TEST-Mobility-Project-Task-Orders/ggav-ufvc)
- Vision Zero [dataset](https://data.austintexas.gov/Transportation-and-Mobility/Vision-Zero-Crash-Report-Data/y2wy-tgr5)
  - Number of people and number per 100,000 residents who are killed or sustain serious injuries in traffic crashes (M.D.1)
  - Number of crashes resulting in fatalities or serious injuries caused by the top contributing behaviors (speeding, distracted
driving, impaired driving, failure to yield) (M.D.2)
  - Number of fatalities and serious injuries on the High-Injury Network (M.D.3)

**Comment by Charlie-Henry** [comment]
Link to Power BI dashboard:

https://app.powerbigov.us/links/tQAnbdsvMB?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare&chromeless=true

**Comment by patrickm02L** [comment]
@maccallump Please create a list of data from the divisions that you want. 

Here's what we have so far...
* Bonds
* ROW
    * Permits
    * Time
    * Traffic Control Plans
* Signals
    * Work order data
* 311

**Comment by patrickm02L** [comment]
Meeting set for Charlie and Patrick to review datasets and nail down metrics on 8/1.

**Comment by patrickm02L** [comment]
Build out the following pages:

### Vision Zero
Fatalities and Serious Injuries

* Fatalities
    * Year Fatalities Trend
    * Cumulative Fatalities
* Serious Injuries
    * Year Serious Injuries Trend
    * Cumulative Serious Injuries
* Types
    * Pedestrian
    * Bicycle
    * Motorcycle
    * Cars
    * Other

Include Time filters for all Dashboard pages: Drop down to change from weekly, monthly, last-five years. 

### Operations (2 pages)
Vehicles, Travel Time Volumes, Cap Metro Ridership, Trail Counter

### Finance
Parking Revenue

### Signs and Marking 
Work orders

### Bonds
Project Delivery

### 311
Types of Issues, Volume of Issues, Location, SR Stat

### ROW
Permits, Time, Traffic Control Plans

(In Amanda, eventually available, but not easy at the moment)

**Comment by patrickm02L** [comment]
Things to ask @maccallump in Dashboard Review meeting:

How to approach datasets? 

Do we want to only use the data in Socrata or should define what we want to show and find the datasets to make that visible?
* Could we create another place where the data lives?

What do the executives want to see?
* Guessing they need high level
* Individual divisions can drill down on their own

How do we handle transparency?

**Comment by patrickm02L** [comment]
Set up meeting with Signs and Marking (Susanne G. & Christina T.) to go over what data their capturing in their Power BI dashboard, and what data would help tell a story in the Executive Dashboard. Meeting either Thurs, 8/4 or Mon, 8/7.

**Comment by patrickm02L** [comment]
Kate is going to take the lead to help with the storytelling of for the different division pages that will be included in the dashboard.

**Comment by patrickm02L** [comment]
@katelunceford is working on prototyping Signs and Marking Dashboard in #10039

**Comment by patrickm02L** [comment]
Basics for monthly dashboard via @maccallump 

1. Financial Report - Budget to Actual
2. Division highlight - 1st one SMD. 
3. Current operational performance metrics 
4. Capital Project Delivery overall update - quarterly? 
5. Capital Project Highlight
  - 2016 Mobility Bond
  - 2018 Mobility Bond
  - 2020 Mobility Bond

**Comment by patrickm02L** [comment]
Put together a dashboard with Financial information through August, and signs and marking dashboard. A 2 page dashboard is alright for now.

**Comment by patrickm02L** [comment]
@Charlie-Henry look at ATD Financials spreadsheet EXP 5125 tab for the raw data, represent visually. Reach out to Crystal T.

**Comment by patrickm02L** [comment]
That new pages have been added in the Executive Dashboard prototype. 
ATD Expenses and ATD Revenue for July 2022. 

Better to represent the month-in-closed data rather than updating the data semi-daily. 

@Charlie-Henry is still working with data Crystal T. provided to get this automated. There are challenges in microstrategy - specifically removing prompts from reports. @maccallump said that you can remove it from the script from the prompt - this happens when reports are being built.

**Comment by patrickm02L** [comment]
Things discussed in 09/13/22 Sync:

@Charlie-Henry 
- Look at getting Revenue data month-to-month
- Move cards for Revenue pages to the left side.
- Try another way to represent what's in the metrics cards.

![Screen Shot 2022-09-13 at 3.31.19 PM.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/d9e2fa1d-4009-49e7-8f2f-1dc8945d71e8
)

**Comment by Charlie-Henry** [comment]
I had some troubles getting some things to work like the border or shading the text to match the arrow, but here's another stab at the revenue page. Currently, I just have the FDUs selectable but we can make a lookup table to convert those to something more friendly. 
<img width="1164" alt="Screen Shot 2022-09-15 at 10 44 29 PM" src="https://user-images.githubusercontent.com/30810522/190552187-40737fd6-249e-4457-9f02-95bc3bddee8c.png">

https://app.powerbigov.us/links/tQAnbdsvMB?ctid=5c5e19f6-a6ab-4b45-b1d0-be4608a9a67f&pbi_source=linkShare

**Comment by patrickm02L** [comment]
@maccallump The ATD Revenue and Finance Pages on the Executive Dashboard are good to show at the next Executive meeting.

**Comment by patrickm02L** [comment]
Closing with the intention of adding more Pages to the dashboard which we'll add to the Epic #7700.
