### ISSUE TITLE
Enhance Announcement Message on RPP Application

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9614]
in the meeting this morning with the RPP team they indicated they are still getting a lot of Orange Zone residents entering applications in Knack despite the Announcement on the home page. Is there any updates we can do to make it more visible like make it Red or Bold Announcement - Orange District Residents. Open to any thoughts you may have.

- [x] double messaging. One on the first page of the application, maybe also by the Start Application button.

- [x] add color background to the text, we could make it orange and bolded

**Comment by ChrispinP** [comment]
Added the same messaging from the Portal page to the first page of the application:
![image](https://user-images.githubusercontent.com/67915167/176557422-f2113b2e-8c13-4c21-96d7-3cfb9b268050.png)

Updated the How It Works section of the Get Started page and added a linked Big Button for navigation.
![image](https://user-images.githubusercontent.com/67915167/176557523-373dec4d-78e4-4e2c-bc6c-f2cf5e7d0787.png)

Bolded announcement text and added orange background on the Portal page
![image](https://user-images.githubusercontent.com/67915167/176557622-11d7591d-8d10-42ff-9910-377970889fae.png)

ready to review

**Comment by moorerst** [comment]
@ChrispinP the enhancements look great. Hopefully this will help redirect the orange zone residents.
Closing this issue. Thanks
