### ISSUE TITLE
HR Sharepoint Redesign Research

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9619]
Questions from Sprint Review issue #8953

- [ ] Reach out to CTM SharePoint team, how to make sure others can't open files
Find out specific details on how Microsoft365 AD profile riles display file usage info per user (SharePoint People webpart; Teams profile; etc.) and which files are shown (SharePoint, OneDrive?, other?) - find out what criteria guides the selection of files that are shown

- [ ] HR Profiles - can you format the description field

**Comment by KaroEngstrom** [comment]
T 7/5/22

- [x] Reached out to Dave G at CTM on profile cards to see what options exist beyond the basic Microsoft functionality outlined [here](https://support.microsoft.com/en-us/office/profile-cards-in-microsoft-365-e80f931f-5fc4-4a59-ba6e-c1e35a85b501)

**Comment by KaroEngstrom** [comment]
F 7/8/22

- [x] Met with Adan yesterday for training and showed the way to turn off Delve. Covered the steps and he completed them immediately, and also shared with his team. HR now knows how to turn off the display of the extra information. Emphasized that this does NOT change permissions on file, just prevents them from being displayed alongside the Profile Cards in the Microsoft365 web apps. Emphasized that the change may take up to a week to take effect across the Microsoft365 platform. 
- [ ] In the same meeting, we covered some options for formatting HR team's info. Told Adan he can ask me anytime about smaller issues and we can revisit anything in our next check-in mid-August. 
Related issue: #9611
