### ISSUE TITLE
Orchestrate SSL Certificate renewal for `airflow.austionmobility.io`

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9620]
@chiaberry's work in #8555 opened up the possibility for automation of SSL certificate deployment on `atd-data02`. During discussion around the subsequent renewal of the certificate, the automation of the process has been considered. 

During our bi-weekly planning meeting, the group generally agreed that work does not seem to be worth the effort at this time.

That said, composing a Prefect flow to handle SSL certificate generation via certbot might become something we want to invest time in -- especially if we find we are maintaining multiple certificates at some point.

The skeleton of the process is documented / scripted in `/root/renew_airflow_ssl_cert.sh` on `atd-data02`.

**Comment by johnclary** [comment]
this was resolved during our upgrade to Airflow v2. there are a series of related PRs here:
- https://github.com/cityofaustin/atd-airflow/pulls?q=is%3Apr+is%3Aclosed+cert
