### ISSUE TITLE
Discovery with other COA departments on Citybase Implementation

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9622]
It was suggested that we meet with several other COA departments who have completed citybase implementation

- [x] Schedule a meeting with Hotel Occupancy Tax program (Eva)  and/or Libraries (Bob B) about their Citybase implementation (include any curious/available ATD stakeholders)

**Comment by moorerst** [comment]
Emailed Bob B 7/11 to request a discovery meeting to learn more about the Libraries Citybase implementation

**Comment by moorerst** [comment]
Meeting scheduled for 7/21
@mateoclarke @dianamartin if you have some specific questions or details you want Bob to cover in the meeting please let me know so I can forward to him prior to the meeting. Thanks

**Comment by dianamartin** [comment]
We're interested in their implementation experience and things they learned. We also want to know more about their individual invoice line items and how theirs is configured. Demo of the process..?

**Comment by moorerst** [comment]
Met with APL for discussion on their Citybase implementation https://library.payments.austintexas.gov/pay/

Meeting was  [Recorded](https://cityofaustin-my.sharepoint.com/:v:/g/personal/diana_martin_austintexas_gov/ER7w_cEPq49LhZt1el3Ivw4B_TspXhKD7LMtskrIaA9vSg)

They provided some sample code and documentation

Provided some pointers:

- Set up postman or whatever we will use
- Citybase will push the schedule quickly
- Make sure you get back what is necessary to mark transactions paid in Knack
- make sure to coordinate with Finance on reconciliation  
- UAT to Production some of the secrets(?) were not transferred correctly by Citybase which caused some issues
Closing this issue
