### ISSUE TITLE
Design Projects Map prototypes in XD

### ISSUE THREAD

**Issue by rebeccabrand** [cityofaustin/atd-data-tech#9631]
As the UX/UI Designer for the Projects Map, I need to draft wireframes of the product for the purpose of user testing and defining feature requirements.

- [x] Rebecca reviews XD comments
- [x] Rebecca drafts multiple wireframes / refines feature requirements
- [x] Rebecca builds out new XD file [living here](https://xd.adobe.com/view/da09889b-be6e-457d-bb9f-eeaf4dbdd825-8f5a/)
- [x] Share files with @patrickm02L (and the atd-moped Slack channel)
- [x] Share comps with Dev Grooming session

**Comment by patrickm02L** [comment]
@amenity talked with Rebecca today about how to approach user testing, and thought that creating some low-fi wireframes would be a good start. Wanted to put this on your radar.

**Comment by rebeccabrand** [comment]
@patrickm02L more sketches to come...

![Doc - Jul 1 2022 - 12-36 PM.jpg](https://images.zenhubusercontent.com/62a6851f8cb947503837405d/f56e2fab-c29c-4ff4-8843-dbd8d937fb74)

**Comment by rebeccabrand** [comment]
@patrickm02L - can you share the issue from the original build-out of the Moped map feature here? Thanks!

**Comment by patrickm02L** [comment]
Hi, here's the an example of what the map used to look like before the refactor #6251. Here's the Issue that moved us to a new full-screen map format and reposition the map elements to the edges to give the map more real estate #6601. Code for 6601 can be found [here](https://github.com/cityofaustin/atd-moped/pull/378/files). 

There's been a lot of stylistic and some functional updates, but the gist of the new map updates should be represented in these Issues.

**Comment by rebeccabrand** [comment]
@amenity & @patrickm02L - updated XD [view link is here](https://xd.adobe.com/view/da09889b-be6e-457d-bb9f-eeaf4dbdd825-8f5a/)

Sneak preview:
![Screen Shot 2022-07-19 at 8.44.46 AM.png](https://images.zenhubusercontent.com/62a6851f8cb947503837405d/1139d88c-fcdf-40f1-ba07-0018ce262719)

**Comment by rebeccabrand** [comment]
@patrickm02L updated issue #9783 with the design prototypes that will inform MVP implementation planning.

**Comment by rebeccabrand** [comment]
I shared the [design review link](https://xd.adobe.com/view/16758f3b-683c-4cc9-9095-dab877b27f46-4326/) with John/Amenity/Patrick in the allotted issue (#9785).

**Comment by patrickm02L** [comment]
Want to give a chance for Amenity and John to review.
