### ISSUE TITLE
BUG: TCP Report Error - Page area too long

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9632]
### "I am receiving an error while trying to open an inspection report for permit number **2021-035505-EX**. When I try to send this report or save it a **page area too large error appears**. 

**Customer:** Nathan C.

**Comment by TracyLinder** [comment]
@Nadin-Nader can you please assign this to a dev for de-bugging?

**Comment by Nadin-Nader** [comment]
@TracyLinder I reached out to Nathan asking for the report number but have not gotten a response yet

**Comment by SubhaShroff** [comment]
@Nadin-Nader  I recreated a permit TCI process attempts and deficiencies. And looks good on DEV and I see no issues. We can replace the PROD rpt file with the one on DEV. But before that I would like to have a call and see if its any other issue.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  - After investigating into this bug, following are my observations:

- Its the data(with bullet points), though the text length is not too much in FOLDER DESCRIPTION field for this particular permit is causing issue.  
    The possible solutions worked on DEV - 1. For this particular field set the font to 8 or 9 on report.
                                                                     2. Or Update the data on Folder Description to plain text.
I also tested permit with the folder description data (3999 char plain text which 1000 characters more than the permit causing issues). It has no issues on DEV

PROD Other RSNs: **12847364, 12805836, 12932001** - For these permits, Folder Description fields have many more characters than 2021-035505-EX. If Nathan/any user can check if these permits are causing the same issue, that would confirm my analysis.

**Comment by TracyLinder** [comment]
Nathan confirmed this is fixed. I will close issue.
