### ISSUE TITLE
SS4A Dashboard

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-data-tech#9640]
Make an internal dashboard that breaks down the prioritization and cost of intersections considered for funding in the SS4A grant application.

**Comment by amenity** [comment]
The MVP internal dashboard is up and the 5-point estimate accurately reflects the work @alan-deanda did on it.  

![image](https://user-images.githubusercontent.com/1463708/177395878-19430c5a-6098-4b3d-a323-e751ce86a72a.png)

In addition to the map, it has a list of individual potential projects as well as supplementary statistics, charts, and information.
