### ISSUE TITLE
Project: Safe Streets for All Grant Application

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9647]
Austin Transportation is submitting an application in US DOT's inaugural round of [Safe Streets and Roads for All Grants](https://www.transportation.gov/grants/SS4A). DTS is supporting the geospatial analysis that -- are performing to determine where funding would be used.

### Safe Streets and Roads for All (SS4A) Grant Program
_The [Bipartisan Infrastructure Law](https://www.congress.gov/bill/117th-congress/house-bill/3684/text#:~:text=SEC.%2024112.%20%3C%3E%20%20SAFE,135%20STAT.%20818%5D%5D) (BIL) established the new Safe Streets and Roads for All (SS4A) discretionary program with $5 billion in appropriated funds over the next 5 years. In fiscal year 2022 (FY22), up to $1 billion is available. The SS4A program funds regional, local, and Tribal initiatives through grants to prevent roadway deaths and serious injuries._

![image Cropped](https://user-images.githubusercontent.com/1463708/177400210-9a24e933-2289-4d24-af3d-8c3f625d7902.png)

### Stakeholders
- Arterial Management - Brian C. 
- Active Transportation - Laura D. 
- Systems Development - Cole K.
- Vision Zero - Lewis L.
- Office of the Director - Karla T.
- Finance - Dan V.
- Jim D.
- Eric B.
- Systems Development - Diana V.
- Jessica C.
- Cody S.
- Anne M.
- Amica B.

**Comment by amenity** [comment]
We have resolved issues based on feedback from the phase 2 data. We have a stakeholder meeting at the end of the week to kick off phase 3. In the meantime, we'll be updating the dashboard.

**Comment by alan-deanda** [comment]
The grant application is being submitted this month. At this point, there are no more geospatial requests. Closing this issue.

**Comment by amenity** [comment]
Super, makes sense!

**Comment by patrickm02L** [comment]
Great News! Austin will expand work to make streets safer with $22.9 million Safe Streets and Roads for All grant.

https://www.austintexas.gov/news/austin-will-expand-work-make-streets-safer-229-million-safe-streets-and-roads-all-grant
