### ISSUE TITLE
Expression of Interest form

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9656]
- [x]  create new object: request_object
- [x] create new EOI form
- attachments
- simple form

**Comment by KaroEngstrom** [comment]
T 7/12/22 

- [ ] Create the `request` object in SMO back office and populate with the current EOI fields

**Comment by KaroEngstrom** [comment]
Questions for the SMO team re: EOI

- Are three options (Yes | No | Other) required for the Data question? Did the previous "Other" field only serve as a place for submitters to elaborate on a "Yes" answer? 
-

**Comment by KaroEngstrom** [comment]
### **DEMO OF THE EOI notes** 2022/07/14

**ATTACHMENT NEEDED?**

- Add attachment capability at the end, option to upload any attachment
- One or multiple? We would want to stick with a single attachment

**CHECKBOXES** 

- Move from radio buttons to checkboxes so multiple options can be selected

**DATA**

- Other is not needed

**EOI RESPONSE EMAIL** 

- currently manual; will share the template
- should not include all the submitted information, which is a lot

**OTHER TO DO** 

- Move the additional information above the acknowledgement
- Would you want a multi-page form? Visually improve this by making it multipage or embedding a table/other imagery?
- Splash page or a linked page of information to allow the user to get a sense of what is needed and prepare for the application

Question - can they start the application and then return to finish it?
    - This would be best done through having an account - something to consider

**Comment by KaroEngstrom** [comment]
- [ ] Add Attachment (single item) field at the bottom of the EOI
- [ ] Build a basic Details page for the Proposed Project

**Comment by KaroEngstrom** [comment]
@dianamartin there's a basic Details page for the EOI content [here](https://builder.knack.com/atd/smart-mobility/pages/scene_25)

**Comment by patrickm02L** [comment]
Bring this to the Sprint Review on 7/22/22. Ask them how they would like to export data from the EOI form to share with the panel. They could also access the information from Knack with `viewer` access in the interim while we build out the other components of P3 Pilot Program.

**Comment by dianamartin** [comment]
The EOI Evaluation form is ready, so we may not need to export out the data submitted.

**Comment by patrickm02L** [comment]
@dianamartin very nice!

**Comment by dianamartin** [comment]
# 7/25

## Submit PIO Request to update EOI link
- [x] Submitted form
![image](https://user-images.githubusercontent.com/21112975/180869626-1a603fde-f24b-4f3b-a696-cdebf1d65e43.png)

## EOI Feedback Updates

**Comment by dianamartin** [comment]
@patrickm02L this is ready for review

**Comment by patrickm02L** [comment]
Underneath the Proposal Attachment Title can you add help text to the effect of: 

**Proposal Attachment(s)**
(for example: brochures; flyers; handouts; promotional materials; etc.)

**Comment by dianamartin** [comment]
@patrickm02L Updated the Attachment section per your suggestion

**Comment by dianamartin** [comment]
I had submitted at PIO request on 7/25 to update the EOI link. Anton completed it on 7/26. 

Anton emailed 7/26
>I have updated the link for the Public/Private Partnership Expression of Interest Form on the Smart Mobility page.
Please let me know if you need any other assistance.

I forwarded to Patrick/Kirk/Kat
>We’ve had the EOI form link updated on the Smart Mobility page. 
Please let us know if you’re happy with the changes and we can pass that information on to PIO team so they can close this task.

Kat replied 7/26
>Looks great! Appreciate both your help with this.

**Comment by dianamartin** [comment]
@patrickm02L can we close this or should we wait until Kat's tested a submission?

**Comment by patrickm02L** [comment]
> @patrickm02L can we close this or should we wait until Kat's tested a submission?

After Kat tests.

**Comment by dianamartin** [comment]
Sent email to stakeholders 7/27
>Hi Kat/Kirk, 
Now that we’ve updated the EOI form link on the Smart Mobility website and demoed the EOI Details page and Evaluation. I’d love for the both of you to get into the system and test it out to see if the process will work for you and see if you need any other changes before, we indicate that the development task is closed. 

>To log in: 
>• Navigate to the [Smart Mobility Home page] or the [Public Private Partnership Portal (P3 Portal) page]
>• Then click the large “Sign-in” button (it may redirect you to log in with your COA credentials
>• Once on the P3 Portal page, you can click “Expression of Interest” to access the new form (the emails are all in Production and will send an email to your resource account)
>• You can view the entry submission it on the P3 Portal
>• You can add an Evaluation

>Once you’ve completed user acceptance testing, please let us know if you desire any changes.
Thanks!

**Comment by dianamartin** [comment]
Kat began reviewing 8/1, her comments were
>EOI: easy to complete, text boxes don’t appear to have character limits (bonus) and also able to put links which remain active after the form is submitted.

**Comment by KaroEngstrom** [comment]
M 8/22/22 
- Updated the EOI image in Knack to [link to Gitbook](https://raw.githubusercontent.com/cityofaustin/atd-knack/master/media/SMO_P3_EOI_Skyline_image.png), to ensure its stability
- Updated change log
