### ISSUE TITLE
Feature: Update TDS banner "An official website of the City of Austin"

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9657]
Amenity A/ /Diana M.
DTS 

Update banner to read "An official website of the City of Austin", similar to RPP banner

![image.png](https://images.zenhubusercontent.com/5cb4c11373d7e234297de5cf/7b823dba-80de-4958-be1d-c3ffe0d6478c)

**Comment by ChrispinP** [comment]
Tested new TDS banner for both mobile and desktop with improved sizing as noted by Amenity, improved styling based on PIO example, and reviewed new TDS banner with Tracy on 07/19. Pending further review with the TDS group during TDS prioritization meeting on 08/24.

![TDS Portal with New Banner](https://user-images.githubusercontent.com/67915167/183454015-0f45a63c-49c7-4e94-867f-4f13cb18beea.PNG)

**Comment by TracyLinder** [comment]
Review w/ stakeholders today & then close.

**Comment by TracyLinder** [comment]
Ok'd by business partners. Please update. FYI @ChrispinP

**Comment by ChrispinP** [comment]
New banner is now Live
