### ISSUE TITLE
Panel Review Digital Scoring 

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9658]
### Judging Criteria
- Quality/Appropriateness
- Desirable
- Feasible
- Viable
- Community Priorities

### Reviewer Rating
- Yes
- No
- Not Sure
- N/A

- [x] create new object: `request_object`
- similar to SSPR Rate Competencies (radio buttons)
- `Overall rating`: green, yellow, red - multi-choice
- `Questions` - rich text
- `Final Comments` - rich text

**Comment by dianamartin** [comment]
They decided to do a group evaluation form rather than an individual evaluation form.

**Comment by dianamartin** [comment]
# 7/21
- [x] Added Icon on the Public Private Partnership Portal tab 
- [x] Moved "Details" field to the far left (from the far right)
- [x] Added "Expression of Interest Form" button on the Public Private Partnership Portal page

**Comment by dianamartin** [comment]
Upon review, I didn't like how some of the fields were in Y/N - decided to convert them to Multi-choice. 
- [ ] Updated field types
- [ ] Rename Field Headings to human labels

**Comment by dianamartin** [comment]
Added Section Header icons
Formatted Layout for EOI Intake Details

**Comment by patrickm02L** [comment]
I like the Panel Review scoring experience. It was simple and easy. It's a lot more streamlined and I think the way you showcase the overall score in the Project Overview is really nice. 

I tested filling out an evaluation form, and one thing that was missing was the `Name of the Project` on the Evaluation form. I found myself trying to remember the project and also thought it might provide clarity of navigation.

Within an individual Evaluation form do we want to include other evaluations, or is it fine to just show them in the Project Overview? This might be something to ask the SMO folks. I know they wanted to be able to view other reviewers evaluations, but it seems kind of redundant to include other evaluations in their evaluation forms.

<img width="1287" alt="Screen Shot 2022-07-22 at 7 44 34 AM" src="https://user-images.githubusercontent.com/5566727/180441925-b69eb194-c003-43e8-83e2-73ccf395045a.png">

**Comment by dianamartin** [comment]
They had said they wanted a group evaluation as a change to their process. I think the company name supposed to identify the project, but I think a short project description could be nice.

**Comment by patrickm02L** [comment]
At the last meeting they said they wanted group evaluations, but I thought Karo mentioned in this week's grooming that they wanted to go back to individual.

**Comment by dianamartin** [comment]
I think she might've been mistaken because I don't remember where they said that after our last scoping meeting. Like I said we can discuss on Monday and confirm.

**Comment by dianamartin** [comment]
# 7/25
Stakeholders like most of the updates
- They requested an area to have meeting notes when they clarify with the requesters

**Comment by patrickm02L** [comment]
Let's send an email to SMO folks an email to test the Digital Scoring.

**Comment by dianamartin** [comment]
Sent email to stakeholders 7/27
>Hi Kat/Kirk, 
Now that we’ve updated the EOI form link on the Smart Mobility website and demoed the EOI Details page and Evaluation. I’d love for the both of you to get into the system and test it out to see if the process will work for you and see if you need any other changes before, we indicate that the development task is closed. 

>To log in: 
>• Navigate to the [Smart Mobility Home page] or the [Public Private Partnership Portal (P3 Portal) page]
>• Then click the large “Sign-in” button (it may redirect you to log in with your COA credentials
>• Once on the P3 Portal page, you can click “Expression of Interest” to access the new form (the emails are all in Production and will send an email to your resource account)
>• You can view the entry submission it on the P3 Portal
>• You can add an Evaluation

>Once you’ve completed user acceptance testing, please let us know if you desire any changes.
Thanks!

**Comment by dianamartin** [comment]
Kat began testing 8/1
Her comments on the evaluation form
>-1.	[Groupings] for the drop down. The City of Austin and Capital Metro’s Smart Mobility Roadmap encompasses five key areas:
a.	Shared-Use Mobility
b.	Electric Vehicles and Infrastructure
c.	Autonomous Vehicles
d.	Data and Technology, and
e.	Land Use and Infrastructure
>- Consider removing the numbering system as the answers are simply yes, no, N/A.

**Comment by dianamartin** [comment]
Emailed stakeholder 8/1
>We’ve updated the SMO technology question per your request. 
 ![image](https://user-images.githubusercontent.com/21112975/182243181-cde61297-b731-42c9-8ff5-87e00d9743c2.png)
Also, thank you for testing these features out.
