### ISSUE TITLE
Bug: RW-Vendor Emails Wrong Permit Report

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9664]
### The system is sending the wrong report on Vending-Permit Email (50552)

----

This is the incorrect report attached to the email. 
[Incorrect.pdf](https://github.com/cityofaustin/atd-data-tech/files/9057855/Incorrect.pdf)

This is the correct report that should be attached to the email. 
[Correct.pdf](https://github.com/cityofaustin/atd-data-tech/files/9057857/Correct.pdf)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in Progress

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Both reports are pointing to the same report path, It is the same as V6 and V7 also. So let's check 50552 report is available in the V6 TEST location and change the name accordingly. 

[\\COACD.ORG\DFS\AMANDA\BROWSERFORMS\DEV\50512_F_PARKING_PERMIT_DEV.RPT](file://coacd.org/DFS/AMANDA/BROWSERFORMS/DEV/50512_F_PARKING_PERMIT_DEV.RPT) - 50512 Parking Permit Report
[\\COACD.ORG\DFS\AMANDA\BROWSERFORMS\DEV\50512_F_PARKING_PERMIT_DEV.RPT](file://coacd.org/DFS/AMANDA/BROWSERFORMS/DEV/50512_F_PARKING_PERMIT_DEV.RPT) - 50552 Vending Permit Report

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Today we get to know from Jenice that in PROD also both (50512/50552) reports are pointing to the same report. and received PROD template for 50512. Now need confirmation that whether we need to create a new report based on the correct.pdf attached above?

![image](https://user-images.githubusercontent.com/44907715/179819300-336a1b02-451b-4fd6-921a-ff97bb9084b0.png)

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan you are correct that 552 needs to be replaced with the correct .PDT template.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Updated report name for 50552 in V6 TEST, V7 TEST, and V6 PROD also. Now I tested in V6 TEST and V7 TEST both are working as expected. If anyone has access to verify the report in V6PROD then upon verification this card can be closed.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan I tested, still wrong form.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Jenice updated the V7 PROD path. here is the screen shot for your reference. Kindly test one more time in PROD if it looks good we can close this card. 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/44907715/183469648-c946684d-f970-4b8e-baba-83dbf0b94a6d.png)

**Comment by TracyLinder** [comment]
I just tested & this is fixed.
<img width="711" alt="Screen Shot 2022-08-10 at 11 42 40 AM" src="https://user-images.githubusercontent.com/49930868/183966384-8fccb5db-ff1d-4c0c-8cbe-98f3d4d53be0.png">
