### ISSUE TITLE
Update Config ROW COS integration with AMANDA V7 PROD (On 8/1/22)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9668]
### Update ROW COS PROD app integration with AMANDA V7 PROD. 

1. Update code to connect to AMANDA V7 PROD RO (currently on V7 Test)
2. Move code over to ROW COS PROD in KNACK.

**Comment by frankhereford** [comment]
Looking forward to this - thank you for all your work organizing and getting everyone connected with the right information and in the right place! 🙏 💯

**Comment by TracyLinder** [comment]
The integration is complete & UAT passed. Thank you @frankhereford  & @ChrispinP
