### ISSUE TITLE
[BUG] Inactive or soft-deleted users' names render as "Unknown user"

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9673]
Users may be inactivated or soft-deleted when they leave the City or no longer use Moped. When this happens, we want to preserve the record of their project membership and activity. Currently, however, their name in the "Team" table and activity feed becomes "Unknown User".
<img width="1366" alt="Screen Shot 2022-07-08 at 3 01 13 PM" src="https://user-images.githubusercontent.com/1463708/178065945-4852bd95-e361-4708-b487-16d35d1a1ce9.png">

Ideally, we could do something like: 
<img width="1369" alt="Screen Shot 2022-07-08 at 2 56 31 PM" src="https://user-images.githubusercontent.com/1463708/178066027-6814dd05-c2ca-4400-b8ac-3a00b99adc15.png">
<img width="1367" alt="Screen Shot 2022-07-08 at 2 58 16 PM" src="https://user-images.githubusercontent.com/1463708/178066029-385f94df-81ba-4625-bd4e-ad347a2a5bc3.png">

### @johnclary's initial words of wisdom

There is bug in the [activity log query](https://github.com/cityofaustin/atd-moped/blob/f19ae38ce0079ddabb158d5f1df4c9031118f1f1/moped-editor/src/queries/project.js#L415): we're filtering for active users only

```
moped_users(where: { status_id: { _eq: 1 } }) 
```

we don't want to do that—a no-longer-active user may be responsible for historical project activities.

**Comment by mddilley** [comment]
This probably explains the "Unknown User" that displays for soft deleted users. That code is in [ProjectActivityLog](https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/views/projects/projectView/ProjectActivityLog.js). If we query all users, then we won't see that fallback text for any users.

Refactoring [this function](https://github.com/cityofaustin/atd-moped/blob/a2f9c89216346fbf631fd325cd7e00d4656fa83c/moped-editor/src/views/projects/projectView/ProjectActivityLog.js#L125) to just get the first letter of `moped_user.first_name` and `moped_user.last_name` might be an easy win here as well (need to see if there is a greater purpose behind using regex here)

**Comment by mddilley** [comment]
I worked on this today and moved a couple of helpers (`getUserFullName` and `getInitials` that appear in a few places in the code into a single file to standardize them. 

I also kept the fallback value for an invalid user object which returns **Unknown User**. With the validation in the new user form and the fix to the two queries that were filtering inactive users, we should never see that fallback so I'll ask for some feedback in the PR that I'll open tomorrow.

**Comment by mddilley** [comment]
Bumping this to a 2 since creating an inactive has been a little difficult. I was able to resurrect an old staging test account and repurpose it, though! 🙌
