### ISSUE TITLE
[Enhancement] Use native PostGIS geometry types

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9675]
We currently store components' spatial data in a `jsonb` column in the `moped_proj_features` [table](https://db-docs.austinmobility.io/atd-moped-staging/tables/moped_proj_features.html).

We should use native PostGIS `geometry` columns to store spatial data. This will allow us to perform spatial queries and other operations against our component data. 

See scoping effort [here](https://github.com/cityofaustin/atd-data-tech/issues/9741).

## Goal
*  Begin to store geometry natively in our database
*  Gain access to all the GIS functions provided by PostGIS
*  Gain access to GIS functions provided by `graphql-engine`
*  Gain access to geographically aware indexing
*  Ease future integrations with ESRI's GIS suite

### Identify geographic data stored as GeoJSON or pairs of `float` fields
* Create a list of each column or pairs of columns which stores GeoJSON or some other geographic data
* Record if each represents a `Point`, `LineString`, or `Polygon` type geometry, or a more complex combination
* Record if each record's data encodes a single geometry or a collection of geometries
* Record at least that the projection is well defined or determine what is being used if not for each column
* Record and assess any properties or attributes encoded in GeoJSON and how that will be retained.
#### Geometry columns
* The columns should be named in a non-generic way and avoid keywords. (`geom`, `geometry`, etc 👎🏻)
* The columns should be typed as specifically as possible. 
  * If certain geometries come in a variety of dimensions, careful consideration should be taken to either remediate them into a uniform dimension or utilize multiple columns, one for points and one for lines, etc.
* The columns should all have a defined SRID and the group should come to consensus on what SRID that should be. 
  * I suggest 2277: [NAD83 / Texas Central (ftUS)](https://epsg.io/2277).
 #### Ancillary columns for storing properties and attribute data
* The typing and schema of the new columns depends on the data found, but generally these choices are driven by the data found
### Populate the geometry columns
* For records with well formed GeoJSON, this may be accomplished with an `UPDATE` statement.
* For those with more complex situations, a python script may be required.
### Deprecate storage mechanism for GeoJSON data
* Delete the columns which contain the GeoJSON
* Update the Moped Application / graphql mutations to use the new columns
  * PostGIS offers functions to generate native geometry from GeoJSON and ability to produce GeoJSON from native geometries, so this hopefully is a manageable, but certainly non-trivial, task. 
  * This is the lion share of this task's work.
* Views can be used to expose the native geometry in a format that is more readily accepted by the application as well.

## Acceptance Criteria
* All geometries are stored using native PostGIS geometry
* No GeoJSON or GeoJSON-like blobs are used in the Moped Database
* App passes all related tests from the testing script
* `moped_proj_features.feature.properties` attributes are accounted for

**Comment by mateoclarke** [comment]
During a scoping meeting on 7/11, this issue was discussed as a blocker for implementing a Map Viewer within the editor. Addressing this tech debt in the next sprint would allow us to implement some of Rebecca's design sooner.

**Comment by frankhereford** [comment]
I have updated this issue, [9741](https://github.com/cityofaustin/atd-data-tech/issues/9741), with more details about how this may be approached. Please see the main comment. Would you like that brought over here?
