### ISSUE TITLE
Purchasing: Add Month Number to Purchase Request ID

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#969]
Peggy has asked that we include the month number in purchase request IDs. E.g.: `2019-12-403` instead of `2019-0403`.

I'm fine with this change. We will need to preserve existing purchase request IDs and only implement this change for new records.

**Comment by dianamartin** [comment]
Added new field `ID_GEN_MONTH` - equation
set: `getDateMonth({Created Date})`

Added new field `Request ID new` - text formula
set formula: `{ID_GEN_YEAR}-{ID_GEN_MONTH}-right({ID_GEN_PAD_ZEROS}, 4)`

**Comment by dianamartin** [comment]
![image](https://user-images.githubusercontent.com/21112975/70947910-e2d66d80-201f-11ea-90f3-95fdba60a499.png)

**Comment by johnclary** [comment]
@dianamartin looks awesome! couple small changes I made:

- Created `ID_GEN_TWO_DIG_MONTH` text formula field (formula = `0{ID_GEN_MONTH}`). I did this because I *think* this will allow you to properly sort by request ID, and it makes sure the IDs are all the same length, which feels good.

- Renamed `Request ID New` to `ID_GEN_REQUEST_ID` and updated formula: `{ID_GEN_YEAR}-right({ID_GEN_TWO_DIG_MONTH}, 2)-right({ID_GEN_PAD_ZEROS}, 4)`. The change here is that we truncate the `TWO_DIG_MONTH` field to actually be just two digits.

- Changed `Request ID` to short text and added conditional rule to populate it from `ID_GEN_REQUEST_ID` if `Reqest ID` is blank. So the original Request IDs do not change, but the new ones will reflect the new formula

![Screen Shot 2019-12-16 at 5.05.00 PM.png](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/d0dca46e-8991-4e8f-b17e-396917c38d28)

**Comment by johnclary** [comment]
Tested new purchase requests. Looks good! Closing.
