### ISSUE TITLE
Preserve users' name display when soft-deleted

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9698]
_Follow-up work @mateoclarke identified reviewing https://github.com/cityofaustin/atd-moped/pull/703:_ 

> once you deactivate a user, their name in the Team listed becomes "Unknown User". I think ideally, even if a user is soft deleted, we'd be able to see their name listed in the team. Even better would be some indicator that this team member has an inactive status.

**Comment by mateoclarke** [comment]
This may be the same as this one:
https://github.com/cityofaustin/atd-data-tech/issues/9673
