### ISSUE TITLE
Update OCR to Handle the new CR3 form for 2023

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9704]
A new [CR3 form](https://app.zenhub.com/files/140626918/a062378b-ab63-4950-855a-c57d7ca90ee1/download) will be implement on 1/1/23 as mandated by TxDOT. The improvement adds new field as outlined in the [Functional Requirements Specification](https://app.zenhub.com/files/140626918/61feba8b-0c1d-415a-8727-7f2cf169c859/download) document which include:

- Intersecting Road Speed Limit
- Direction of Traffic
- Secondary Crash
- Responder Struck
- Date/Time Roadway Cleared
- Date/Time Scene Cleared
- Date Notified
- Date Arrived
- Autonomous Unit
- Autonomous Level Engaged

[Updated Code sheet v0.5](https://app.zenhub.com/files/140626918/a259a340-b391-49b1-871b-8e4b605d1c66/download)

In order to manage this change, we will need to update the OCR to capture the data from the new fields. @frankhereford has outlined the following minor changes to bring operations back to normal operation:

1. Define a new constellation of 10 pixels which we expect to be 100% black / #000000. This constellation is used to determine if the PDF we’re working from is a scan or a digital asset from when it was created.
2. Define the new X,Y coordinates that define the extent of the diagram and the extent of the box around the narrative.
3. Plugging those ~20 coordinates into the correct arrays in the python script which is run by the ETL.

Additionally, to support detecting if the CR3 is an old-style or a new one we'll need to extend the constellation test to tell us if it's digital end-to-end and also which CR3 form style we're looking at.

**Comment by patrickm02L** [comment]
#### 2023 CR-3 form v.0.10

![2023 CR-3 form v0.10-1.jpg](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/19742da2-5354-4144-b496-80409e539eb1)
![2023 CR-3 form v0.10-2.jpg](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/a8c9fa60-aa2a-4eb4-bd8b-7ea6961f391b)
![2023 CR-3 form v0.10-3.jpg](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/b88ca8d8-a7ca-485e-b2dd-23aed50c56b4)
![2023 CR-3 form v0.10-4.jpg](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/d86414af-7d06-4275-b69f-ad7abc12585f)

**Comment by patrickm02L** [comment]
In Product Sync 7/20/22.
* In late August, early September to help figure out how to scope out any changes. 
* Get a test extract of the data, a CR3 form so we can test 
* Budget time that first week of January to troubleshoot.

**Comment by frankhereford** [comment]
Here’s the OCR/image extraction: https://github.com/cityofaustin/atd-airflow/blob/master/dags/python_scripts/cr3_extract_diagram_ocr_narrative.py. It’s in the airflow repo, which is submoduled into the prefect repo, and called from here. https://github.com/cityofaustin/atd-prefect/blob/main/flows/vision-zero/cr3_ocr_narrative_extract_diagram/cr3_ocr_narrative_extract_diagram.py.
