### ISSUE TITLE
[Bug] Sort by "eCAPRIS ID" on "Projects" page doesn't work

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9721]
_Caveat: We haven't been able to reproduce this in Staging and haven't tried creating/editing more Test projects to replicate the behavior reliably._

Side note, though I realize it's a bit subjective and would be a separate enhancement request: I expect blank to be at the beginning when sorted ascending, the end sorted descending. 

![screencapture-moped-test-austinmobility-io-moped-projects-2022-07-12-12_07_25 (1)](https://user-images.githubusercontent.com/1463708/178552417-299368e4-8ea3-46bd-9a08-29f26dec568e.png)
![screencapture-moped-test-austinmobility-io-moped-projects-2022-07-12-12_07_25](https://user-images.githubusercontent.com/1463708/178552419-7aab67dd-9475-4942-ab05-7cc1a76fefb1.png)

**Comment by chiaberry** [comment]
I think this was resolved when switching to different table for the project list page. I am able to sort in production.
