### ISSUE TITLE
Bug: ATD - PSM - Unnecessary Process Info

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9722]
### On folder process 'ATD Engineering Review' - remove the process info 'Transportation Mitigation Fee-in-lieu'

**Acceptance Criteria**
- The Acceptance Criteria provided below applies for all PSM folders regardless of subtype or worktype. 
- The Process Info 'Transportation Mitigation Fee-in-lieu' in the ATD Engineering Review Process needs to be removed. 

**Notes**
- **During scoping we need to check all other folder processes for the unnecessary process info.**
- This was identified during V7 UAT. The bug is in V6 so we moved it to the ATD backlog. Trello card is [here](https://trello.com/c/STVTMTNY/341-atd-psm-unnecessary-process-infos).  
    - Debugged by Subha 

![image](https://user-images.githubusercontent.com/49930868/178561622-5bb20e1c-da17-43bf-a73c-51e71d63a2d6.png)

**Comment by vschandramouli** [comment]
Updated AC, moving to Backlog.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Completed analysis, Need clarification on below 
1. Do I need to remove Process Info from other folders as well? Or I need to remove only from PSM Folder?
2. Right Now, It appears in Folder types - C, C8, DA, PSM, SC, SP, UC ZC

**Comment by TracyLinder** [comment]
I'd prefer not to customize PSM so that a misc. info doesn't show. We can't remove it as it is being used on other folders. I will add to ROW's Friday agenda.

**Comment by TracyLinder** [comment]
ROW is ok with not removing this info for PSM folders. We're closing.
