### ISSUE TITLE
Feature: PSM - Don't allow issuance with expired bond/insurance (LP) - (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9727]
### We don't want the folder to issue if the folder infos Bond Expiration and Insurance Expiration dates aren't in the past (expired)

**Acceptance Criteria**

- The AC provided below applies to PSM folders only. 
- When issuing or renewing a PSM folder, system should validate whether the folder with info field Insurance Expiration Date (75350) and Bond Expiration Date (58085) have a date value that is in the future, i.e. the Bond and Insurance have not expired.
- PSM Folders are issued using the Issue/Approve button and renewed through ROW Admin Process (50075). 

Outstanding Questions: 

- How is a PSM folder issued?
    - 1st time issue - pressing issue button
    - Renewals - ROW Admin Process (50075), Renewal Approved attempt. (Confirmed by Tantanisha F.)

Notes: 

- This was reported as a V7 UAT bug however the feature doesn't exist in V6, so it was moved to ATD's backlog.

**Comment by vschandramouli** [comment]
Pulling this card into my workload and assigning to myself.

**Comment by vschandramouli** [comment]
Updated AC, this is ready for Backlog. Have asked Tan-Tanisha details about PSM renewal. Will update this card when I receive a response.

**Comment by Nadin-Nader** [comment]
@vschandramouli have you received a response from TanTanisha?

**Comment by TracyLinder** [comment]
Will be assigned to Sree during this sprint.

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Committed changes and requested for Dev and Test promotion

**Comment by Nadin-Nader** [comment]
Updated the deployment priority to a level 3. Waiting on DevOps

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Test , ready for UAT

**Comment by Nadin-Nader** [comment]
Waiting on UAT response from Kyle

**Comment by Nadin-Nader** [comment]
@Lpriya-LIT Kyle has approved this on TEST. Please deploy to PROD

**Comment by Lpriya-LIT** [comment]
@Nadin-Nader Changes deployed to Prod , Ready for UAT

**Comment by Nadin-Nader** [comment]
Sent Kyle a message via Teams that this is ready for UAT on PROD. Waiting on Response

**Comment by Nadin-Nader** [comment]
This has been approved by Kyle on PROD. Closing
