### ISSUE TITLE
Feature: Update Historical TIA Mitigations with mitigation type details in modal pop-up

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9728]
Nelson E. 
TED

Met with him for our Historical TIA Mitigation check-in. He was going to do some testing on the "editing" feature we built for him. He has a new enhancement request. 

He'd like the existing "TIA Mitigations" table to have a new feature/field that you can click on and then see the related TIA records
- [x] in a modal pop-up
- [x] Add fields to this new page/form:
- `Improvements`
- `Fund Status`
- `Cost`

Nelson would like to know approximate time line by 7/15, so he can check back up and track the request.

**Comment by ChrispinP** [comment]
Update is complete, reached out to Nelson & Cody if anything needs to be adjusted.

![image](https://user-images.githubusercontent.com/67915167/179545481-7e29c3d1-4997-44e3-98a4-44eb0df0fddf.png)

![image](https://user-images.githubusercontent.com/67915167/179545389-60ae0f93-e121-4f54-b558-f74271cd5df4.png)

**Comment by ChrispinP** [comment]
Reached out to Nelson & Cody, no issues so far. Closing as complete
