### ISSUE TITLE
Document the Moped activity log flow

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9729]
- hasura configuration / metadata
- SQS
- Lambdas
- hasura event logs (how are they truncated)
- Github actions
- [notes](https://austininnovation.slack.com/archives/CNUEPKLB1/p1657661751327599) about authentication

See also: #9723 and #9726

**Comment by mddilley** [comment]
These topics are now documented and can be found at: 
**Internal DTS Gitbook > Moped Documentation > Dev Guides > Activity Log**
