### ISSUE TITLE
[Bug] Moped's acceptable characters in name/email fields don't match O365's

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9731]
Outlook: 
<img width="632" alt="Screen Shot 2022-07-13 at 1 34 14 AM" src="https://user-images.githubusercontent.com/1463708/178666600-79e95cb9-da4b-4933-b3f6-1a0f2b353be4.png">

Moped:
<img width="830" alt="Screen Shot 2022-07-13 at 1 32 11 AM" src="https://user-images.githubusercontent.com/1463708/178666638-d640f72c-18fe-4d9d-9a8e-131a21d62d8a.png">

**Comment by chiaberry** [comment]
https://github.com/cityofaustin/atd-moped/blob/main/moped-api/users/validation.py
