### ISSUE TITLE
Compile DTS Geo documentation 

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9738]
- Our most frequently-used Arcade expressions
- Index of our geoprocessing models pointing to online storage, information on the frequency they're run

Review 
- file structures
- where things are stored/documented (G Drive, Gitbook, etc.) so that there isn't any redundancy 
- tracking dates

**Comment by amenity** [comment]
@andrewshensky - please schedule a work session to start this late next week.

**Comment by andrewshensky** [comment]
@alan-deanda Let's have this be our topic for our GIS Sync-up next Thursday (7/21).
