### ISSUE TITLE
Identify panelists and prepare for interviews

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9740]
1. Review [applications](https://docs.google.com/spreadsheets/d/1o7qCeBTBUFZYNFAoGgKEpm-l4EwivC3-0jJ0oy6miUU/edit#gid=232679892) 
2. Identify who we want to interview
3. Notify other applicants that we won't be moving forward
4. Schedule interviews (panelists - Christina, Diana, Andrew, Amenity)
5. Prepare interview docs (questions [here](https://docs.google.com/document/d/1MjGatrGFNBIJPlBDgnT9uDX6_vHHgEhP360lc54betc/edit)

**Comment by andrewshensky** [comment]
@amenity I have ranked the applicants based on their resumes and responses. Can we sync up early this week to discuss next steps?

**Comment by amenity** [comment]
@andrewshensky - @maccallump is going to help with this since I've been thin on bandwidth. :)

**Comment by andrewshensky** [comment]
I have contacted the two applicants we want to interview from this round and scheduled the interview times. I will be closing this issue.
