### ISSUE TITLE
Scope the native PostGIS geometry conversion

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9741]
# Transition to Native PostGIS Geometry
## Goal
*  Begin to store geometry natively in our database
*  Gain access to all the GIS functions provided by PostGIS
*  Gain access to GIS functions provided by `graphql-engine`
*  Gain access to geographically aware indexing
*  Ease future integrations with ESRI's GIS suite

### Identify geographic data stored as GeoJSON or pairs of `float` fields
* Create a list of each column or pairs of columns which stores GeoJSON or some other geographic data
* Record if each represents a `Point`, `LineString`, or `Polygon` type geometry, or a more complex combination
* Record if each record's data encodes a single geometry or a collection of geometries
* Record at least that the projection is well defined or determine what is being used if not for each column
* Record and assess any properties or attributes encoded in GeoJSON and how that will be retained.
### Create native geometry columns for data and ancillary columns for storing found property / attribute data
* The columns should be named in a non-generic way and avoid keywords. (`geom`, `geometry`, etc 👎🏻)
* The columns should be typed as specifically as possible. 
  * If certain geometries come in a variety of dimensions, careful consideration should be taken to either remediate them into a uniform dimension or utilize multiple columns, one for points and one for lines, etc.
* The columns should all have a defined SRID and the group should come to consensus on what SRID that should be. 
  * I suggest 2277: [NAD83 / Texas Central (ftUS)](https://epsg.io/2277). This will allow us to perform spatial calculations in feet / miles and will conform to a frequently used projection by the department. 
### Populate the geometry columns
* For records with well formed GeoJSON, this may be accomplished with an `UPDATE` statement.
* For those with more complex situations, a python script may be required.
### Deprecate storage mechanism for GeoJSON data
* Delete the columns which contain the GeoJSON
* Update the Moped Application / graphql mutations to use the new columns
  * PostGIS offers functions to generate native geometry from GeoJSON and ability to produce GeoJSON from native geometries, so this hopefully is a manageable, but certainly non-trivial, task. 
  * This is the lion share of this task's work.
* Views can be used to expose the native geometry in a format that is more readily accepted by the application as well.

## Acceptance Criteria
* All geometries are stored using native PostGIS geometry
* No GeoJSON or GeoJSON-like blobs are used in the Moped Database
* App passes all related tests from the testing script

**Comment by frankhereford** [comment]
@amenity @mateoclarke - I am not sure if you'd like me to take a guess at sizing it. I would certainly over-size the JS portion of it, me being me. That to say, I think we'll have a lot of variance in the teams opinion about the size - maybe time for planning poker if this is an acceptable approach for this work. Big 3, little 5? 

@johnclary - BTW, this is what prompted my question to you about SRID opinion.

**Comment by johnclary** [comment]
thank you @frankhereford for expert review and guidance on this effort! just want to capture here that i introduced a wrinkle to this scope: the `moped_proj_features` table's `feature` column is not merely a `jsonb` column holding a geojson geometry: the column holds feature `properties` (in the geojson sense of the term) as well.

we need to review what (if any) of those properties are critical to the Moped editor, and what to do with them.

**Comment by frankhereford** [comment]
John - thanks for capturing that we need to keep an eye out for attributes / properties stored alongside geometry in the GeoJSON! I made some minor edits to the main comment on issue #9675 to reflect that need.

Thank you also for brining over this content to that issue to go forward. With that transfer made, I'm going to close out this task for the scoping. 

Thanks everyone!
