### ISSUE TITLE
Update DTS project backlog in Github + Zenhub to reflect prioritization

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#975]
Now that we've knocked out our [DTS Product Prioritization](https://docs.google.com/spreadsheets/d/1o0Q_xIx0c1njAg6opnAJwyCIhAkU7W-hK_7P8jgMCug/edit#gid=0), we need to 
- Record results in each index issue
- Discuss and reorder backlog to reflect

**Comment by amenity** [comment]
@johnclary I think we can do this if we 📌 all the index issues to the pipelines. Is this a good idea?

**Comment by johnclary** [comment]
i think that's an ok idea. shall we discuss at product sync? what about.....a separate zenhub workspace? <collective groan>

**Comment by amenity** [comment]
~groan~ ... but yeah, I think this is worth discussing. :) I think it might be a better idea. TBH, this is really only an issue with Data Tracker.
