### ISSUE TITLE
Create and destroy Activity Log resources

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9750]
In order to test updates that affect the activity log, we should create test resources to make it work in each test instance.

How this currently works:
- [This Github action](https://github.com/cityofaustin/atd-moped/blob/main/.github/workflows/atd_sqs_activity_log.yml)
- Uses [this bash script](https://github.com/cityofaustin/atd-moped/blob/main/.github/workflows/aws-moped-sqs-helper.sh)

**Comment by mddilley** [comment]
These two PRs add this to the Prefect Moped test deployment flow:
https://github.com/cityofaustin/atd-prefect/pull/22
https://github.com/cityofaustin/atd-moped/pull/728

The code recycles the current bash helper script with a couple functions added to handle the moped test deployment. Future updates could use boto3, but this will work for now.
