### ISSUE TITLE
Conduct PowerBI Training w/ Ashlande E.

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9752]
Charlie will conduct a training on Power with Ashlande with the intention gaining more insights about how to use the platform. The focus is picking up skillset and being able to independently create reports.

Related to #8947

**Comment by Charlie-Henry** [comment]
Rescheduled to next Tuesday, still waiting for Ashlande's license to get approved

**Comment by patrickm02L** [comment]
Meeting scheduled for 7/29/22.

**Comment by Charlie-Henry** [comment]
Completed the first half of this training on Tuesday. Ashlande didn't have Power BI desktop installed yet, was hoping it would be quick but we decided to end about an hour in. Will continue next week. Ashlande is really excited to learn more!

**Comment by Charlie-Henry** [comment]
Ashlande has had some problems installing Power BI but now she's installed. She'll be out of office during the first week of September so this is scheduled for September 14th

**Comment by Charlie-Henry** [comment]
I am going to go ahead and close this out as we've done our two sessions of training. She says she'll reach out if she has questions.
