### ISSUE TITLE
[Enhancements] Finance and Purchasing App - Inventory improvements

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9768]
Ronnie B. 
AMD

In a meeting we had back on 6/29. 

We met with stakeholder and discussed it here #9602 

## Finance Enhancements
- [x] Discussion: How Finance utilizes "Received Items" - Allow Inventory Planners access?
>Dan would like to keep these processes separate
- [x] Discussion: If received items needs to be separate, than show proposed [TEST Finance and Purchasing page](https://atd.knack.com/backup-apr-23-2021-finance-and-purchasing-system#order-report/) for order tracking
>Dan thinks it's fine to build out a different order tracking module in Finance and Purchasing 
- [x] [Enhancement] Search Purchase Request Items (Purchase Request | Purchase Request Items)
>Can move forward
- [x] [Enhancement] Unit Cost - increase decimal places to 4
>Dan does not think this is a good idea, high level of risk and work if this were to change.
- [x] [Enhancement] Add "Item ID" to Purchase Request Item table in PROD
>Can move forward

**Comment by dianamartin** [comment]
Need to talk to Finance managers about these enhancements, out of office - returning 7/19/22.

**Comment by dianamartin** [comment]
Talked to Finance stakeholders and they approved some enhancements

# Approve Finance Enhancements - need to do
### Order Tracking module: 
- Reference: TEST Finance and Purchasing page](https://atd.knack.com/backup-apr-23-2021-finance-and-purchasing-system#order-report/) for order tracking
>Dan thinks it's fine to build out a different order tracking module in Finance and Purchasing

### [Enhancement] Search Purchase Request Items (Purchase Request | Purchase Request Items)
>Can move forward

### [Enhancement] Add "Item ID" to Purchase Request Item table in PROD
>Can move forward

**Comment by dianamartin** [comment]
@KaroEngstrom let's shoot for trying to get this done by 8/30, let me know if you want to meet the stakeholders earlier or need extra time.

**Comment by dianamartin** [comment]
@KaroEngstrom we'll meet during our 1:1 and we can go over these 2 small enhancement features
- [ ] [Enhancement] Search Purchase Request Items (Purchase Request | Purchase Request Items)
- [ ] [Enhancement] Add "Item ID" to Purchase Request Item table in PROD

**Comment by KaroEngstrom** [comment]
@dianamartin Updates complete as outlined above.
