### ISSUE TITLE
Remove purchase order and contractor fields

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/atd-data-tech#9770]
To be completed after #8259 

- [x] remove DO number and contractor fields from project summary page
- [ ] drop columns from `moped_project` table

**Comment by chiaberry** [comment]
I'm going to split this over two PRs, since dropping the column cant happen until after we merge to prod

**Comment by johnclary** [comment]
If this requires changed to the projects view SQL, we might want to consider rolling https://github.com/cityofaustin/atd-data-tech/issues/10047 into the work.
