### ISSUE TITLE
Fix duplicate entries in the Moped activity log

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9773]
@johnclary observed during his work on restoring lost activity log entries that there is a small percentage of activity log entries which are duplicates. He wrote:

>oof, i don’t think our activity log pipeline is working the way we expect it to. when running my tests in staging, i was seeing quite a few duplicate activity logs resulting from a single event dispatch.
>so i checked prod, and we do indeed have ~90 duplicate activities. for example [project #155](https://mobility.austin.gov/moped/projects/155?tab=activity_log), this event is listed twice
```
Project current status from "active" to "complete"
Project phase from "construction" to "complete"
Project status ID from 1 to 5
```
>i’m assuming this is more likely to happen when the queue is under heavy load, since a lot of the dupes in prod seems to occur when someone uses a milestone template, which fires off ~20 events at once.
>to be clear, it’s an edge case—we’re talking about 2% of events being duplicated.

This issue is to track the effort to run down what exactly is causing this duplication and to remediate it.

**Comment by mddilley** [comment]
Did some digging around today and found this blog post that might help get to the bottom of this. https://medium.com/geekculture/aws-lambda-and-sqs-what-nobody-tells-you-about-their-mix-c9e4631dbb0f. Section #2 in the post mentions duplicate records that I think could shed some light on what is going on. 

Questions that I came away from that post with:
1. Current timeout on the activity log Lambdas is 3 seconds - is long enough to loop through a large batch considering each event fires off an async request?
2. Am I misunderstanding how that works?

I also monitored the activity log in CloudWatch and noticed that many errors occur for a single event.

To reproduce:
1. Go to staging Moped
3. Open up the CloudWatch logs for the Lambda named `atd-moped-events-activity_log_staging`
4. In staging Moped, make a small change to a project - I updated a project description to something super easy to CMD + F
5. Check the logs for errors like `Invalid event format:`, `[ERROR] Exception:`, `Could not process record:` around the update that you made

**Comment by johnclary** [comment]
In grooming yesterday we discussed the idea of spiking on an alternative event log mechanism, in which we would write our own database procedures + triggers to create capture activities. I'm adding this issue to our Activity Log 2.0 epic and moving into the backlog.

**Comment by johnclary** [comment]
We implemented the alternative logging mechanism. This is done.
