### ISSUE TITLE
Enhancement: Traffic Register Sprint Review 7/15 - Feedback modifications

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9777]
From our meeting, we got some enhancement requests

- On Manage Streets table, update `streets` object
- [x] Added field `Status`: 
- Active
- Historical
- [x] Add Secondary Connection on Admin back fill - regulations tables to be able to select a "Historical Reference" street (ex. Chalmers)
- [x] Add "Primary Street" and "From Street/To Street"  to Back fill [table](https://atd.knack.com/traffic-register#admin/manage-reg-backfill/)

We said we'd email Joana and team once these were up to date.

**Comment by ChrispinP** [comment]
Updates now live. Updated all Street records with a status. Will need to do a small training to update the Admin team on Monday for the new fields.

**Comment by dianamartin** [comment]
We showed to stakeholders at the second to the last Sprint Review meeting.
