### ISSUE TITLE
SIF: Discovery of Volume Builder Enhancements (SR)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9779]
### ATD-SIF may not be seeing all volume builder applications that are SIF eligible. 
_We are currently scoping this issue._
- Consider incorporating #9342

**Comment by TracyLinder** [comment]
### Volume Builder - Two Processes

**Temporary (1st Wave)**


**Future (after 1st Wave)**

**Comment by TracyLinder** [comment]
### RV Bugs
- Example V6 where SIF info didn't insert: ROW ID

- [ ] Data needed: How many RV MPR are submitted per month on average?
- [ ] Active VB MPRs 

Nate wants to do mock run-through to calculate resources needed / what this manual process would entail. 
- Tracy will schedule something 
- create test folder for us to work with


- [ ] Inform Myra not to worry about changes/updates until after we follow up with her team.

**Comment by TracyLinder** [comment]
**Manual Process Overview**

1. ATD-TDS will query AMANDA for all RVM-PR folders created that they haven't reviewed yet. 
2. TDS will review each folder criteria to determine if it is SIF eligible. 
3. If it is SIF eligible TDS will need to determine if SIF was paid with the Master PR. 
4. TDS will manually insert the ATD-SIF Review process on the RV-MPR and manually update the review dates to match the existing review timelines. 
5. TDS will query AMANDA to determine if a SIF folder for this development already exists. 
6. If SIF folder does not exist, TDS will create one. 
7. TDS will create a SIF Estimator worksheet
8. TDS will input building data on the SIF Building Info tab. 
9. TDS will insert & bill SIF fee. 
10. TDS emails the customer the invoice, worksheet, and payment instructions, 
11. TDS will add a process attempt on the PR folder, on ATD-SIF Review, likely 'rejected'
12. TDS will inform DSD case manager that SIF is required, and ask not to approve the permit until SIF is paid. 
13. DSD will add the SIF blurb on the master comment report, and reject the review cycle.

**Comment by TracyLinder** [comment]
I created a new issue for the updates on RV MPR - #9823.

**Comment by Nadin-Nader** [comment]
@TracyLinder im putting this on Deck

**Comment by TracyLinder** [comment]
SIF is currently not mandatory on the VMPR, the process is being manually inserted by Chris Sup. who is the intake lead with DSD. So we still need to automate the SIF distribution.

**Comment by Nadin-Nader** [comment]
@TracyLinder Sree would like your input on this

**Comment by TracyLinder** [comment]
I removed this from the SIF Project Epic #5078

**Comment by vschandramouli** [comment]
Confirmed from Tracy that this card has not been adequately scoped.

**Comment by TracyLinder** [comment]
Meeting w/ DSD scheduled for 8/28/23

**Comment by TracyLinder** [comment]
I added @Sreelatha-BlazeKannan to next week's w/ DSD. 
Sree - no need to work this right now until scoping is complete.

**Comment by TracyLinder** [comment]
### Update
- The meeting with the larger group is rescheduled for 9/11/23

**Comment by TracyLinder** [comment]
### Meeting with TDS & DSD Volume Builder Team 9/11/23

**Questions:**

- [ ] Is the master plan review done on C8? 
- [ ] How do we query volume builder folders? What is the folder type? 


----
**Notes**

- Is SIF Review being auto-added to volume builder permits/applications? 
    - Not really. TDS doesn't see the master plans either. Dan described multiple ways that he becomes aware of volume builds. 
- Dan doesn't ever see volume builder on his task lists.
