### ISSUE TITLE
Projects Map | Design MVP

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9783]
Staff would like to create visualizations of all the projects that they're working on, related projects, and other projects that might be useful in analyzing their current workflow. 

This feature would exist on the main navigation, and would fill the entire container on the screen. 

**UI Considerations**
- Map underlay, aerial mode, and zoom
- Search
- Analytics Card
- Legend with comprehensive filtering options
- Marker Window

**Technical Considerations**

**Projects Map with all UI considerations**
![PROTOTYPE 1 - MAIN DASHBOARD WITH SCROLL.png](https://images.zenhubusercontent.com/62a6851f8cb947503837405d/385d47b0-1095-4492-bb12-3107b5941982)

![PROTOTYPE 7 - CLOSE SEARCH THEN CLOSE SIDEBAR – 1.png](https://images.zenhubusercontent.com/62a6851f8cb947503837405d/59498461-7661-4d86-b513-bed58aebcb08)

**Comment by patrickm02L** [comment]
**Map with aerial and zoom functionality**

![MAP FULL - BY PROJECT TYPE – 1.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/05b0e513-3b8b-47b2-97e4-f60473eed17b)

**Map with search**
![MAP FULL - BY PROJECT TYPE – 2.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/29dde20a-1737-4d88-90b4-fc3b4907701c)

**Map with Legend**

![MAP FULL - BY PROJECT TYPE – 3.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/5afedfe4-2eaf-4c4f-a7ee-d41e66da696e)


**Map with Tooltip**

![MAP FULL - BY PROJECT TYPE – 5.png](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/8bfd4afd-7821-4e81-a685-00a6c6d1b177)

**Comment by patrickm02L** [comment]
Removed @rebeccabrand as part of Fellowship off-boarding.

**Comment by johnclary** [comment]
Because this issue is really capturing the design history of the proejct map, i'm going to rename it, create a new epic for the MVP, and move the implementation issues there.

**Comment by johnclary** [comment]
Offering one additional design consideration here, which is to condense the search content and add a list view to the side bar. i dunno :shrug:

<img width="1398" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGdEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ec0191f68487ff8905bfd29e083e805b15afca0/map_mvp%20copy.png" alt="map_mvp copy.png" />

**Comment by johnclary** [comment]
Here is the new implementation MVP. Closing this ✅
