### ISSUE TITLE
Projects Map | Design MVP

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9784]

**Comment by amenity** [comment]
@rebeccabrand - when you're ready, please add the final design specs (screenshots and/or links) to this issue description and assign this issue an estimate that accounts for all the design time you spent outside the child issues (#9631 and #9785). 🙏 📸 👕

**Comment by rebeccabrand** [comment]
Both issues have been closed, meaning this parent issue is complete. The final Projects Map prototype can be [accessed here.](https://xd.adobe.com/view/8b519831-fbf9-4164-8fc5-e1aa3ee9e5e4-de02/)
