### ISSUE TITLE
Identify all crashes deleted in CRIS that are in the VZDB; delete from VZDB

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9786]
In working through #7622, we discovered that the VZBD was retaining crashes that had been deleted from the CRIS database. This was causing misalignment between our systems and was a cause for concern by the VZ team who relies on the accuracy of the CRIS and VZDB to be in sync. 

We decided to do an investigation on a single record to find out why the discrepancy was happening #9754. In that discovery, a [script](https://github.com/cityofaustin/atd-data-tech/issues/9754#issuecomment-1184598528) was written to extract CRIS CSV files and use pgfutter to put them in table for one-off peeking at CRIS data. We used that information to identify which files were deleted in CRIS for the last year, and subsequently deleted them in VZBD. 

As a follow up, we need to clean up the rest of the VZ data to ensure alignment between the two systems. 

**Recommended course of action:**
- [ ] Run script for all of VZDB to identify which records are deleted in CRIS that still exist in VZDB
- [ ] Delete all records from the VZDB that have been deleted from CRIS.
- [ ] Determine a plan for routine deleted CRIS records alignment.

**Comment by mddilley** [comment]
When backfilling CR3 pdfs for https://github.com/cityofaustin/atd-data-tech/issues/11385, the script failed to download pdfs for crash IDs: 16529633, 180290542, 14683802, 12582284. When searching for them using the CRIS search tool, no records are found in the CRIS DB. 

[Crash ID# 180290542](https://visionzero.austin.gov/editor/#/crashes/180290542) has a fatality which adds another wrinkle in this and how it impacts fatality counts for 2018.

**Comment by mddilley** [comment]
Talked about this in dev sync today, and we decided that looping in the VZ team on these crashes and also attempting to contact the CRIS team to check on the reason why these crash IDs no longer exist in CRIS is. the best path forward here.

**Comment by patrickm02L** [comment]
@xavierapostol can you check to see whether the 4 crash ID below which have been deleted from CRIS are still our responsibility? One of them had a fatality.

> When backfilling CR3 pdfs for #11385, the script failed to download pdfs for crash IDs: 16529633, 180290542, 14683802, 12582284. When searching for them using the CRIS search tool, no records are found in the CRIS DB.
> 
> [Crash ID# 180290542](https://visionzero.austin.gov/editor/#/crashes/180290542) has a fatality which adds another wrinkle in this and how it impacts fatality counts for 2018.

**Comment by patrickm02L** [comment]
So can we delete the manually entered fatality too?

**Comment by xavierapostol** [comment]
No. That fatality record is the only one we have in the system. For some reason APD never wrote up a CR3 for, but Lewis had requested we generate a manual one.

**Comment by patrickm02L** [comment]
For crash ID# 180290542: This fatality was manually entered (before my time) and there is no CR3 for it. Update script to exclude.

**Comment by mddilley** [comment]
The following have been removed from VZDB along with their associated records.

Crash ID 16529633
- [x]  delete crash record

Crash ID 14683802
- [x]  delete crash record

Crash ID 12582284
- [x]  delete crash record
- [x]  delete primary person id 1627824
- [x]  delete primary person id 1627828
- [x]  delete unit id 2308270
- [x]  delete unit id 2308269
- [x]  delete charge id 1718577
- [x]  delete charge id 1718582

For crash ID# 180290542, the CR3 script has been updated to take a list of skippable IDs so it never will try to retrieve the CR3 again once the code is merged. I added a comment and a link back to this issue for future context. Once that code is reviewed and merged, this will be complete.
