### ISSUE TITLE
BUG: AMANDA V7 RW - Street Vendor Folder Expiry date randomly populates a date when issued, then when you click off of the page it shows the new wrong Expiry date. (SR) (On PROD)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#9788]
## 1
System should update the folder status of RW folder to 'Active' when user makes an attempt of 'Update Issue and Expiry Dates' in Vendor Permitting Process (50650) if the new expiry date of the folder is greater than the current date. (this needs to be implemented)

## 2

**Acceptance Criteria** 

- The Acceptance Criteria mentioned here applies only to RW - Street Vendor folders. 
- When a user adds "Update Issue and Expiry Dates" attempt in Vendor Permitting Process in RW- Street vendor folder, system should automatically update the expiry date immediately after the attempt. 
- Currently there is a wrong expiry date updated, and then on clicking out and coming back to the folder tab, the correct date is being updated. 
- The steps to recreate this issue are provided below. 

Steps:
1. Search for Permit  
2. Go to Process Tab - Vendor Permitting process; 
3. add "Annual Renewal" attempt; 
4. Add "Update Issue and Expiry Dates" attempt  

<img width="1142" alt="Screen Shot 2022-10-11 at 2 22 21 PM" src="https://user-images.githubusercontent.com/49930868/195180591-109cf7a7-966b-4e1d-a76a-7051494b4d84.png">

Expiry date randomly populates a date when issued, then when you click off of the page it shows the new wrong Expiry date. The new date shown is also not calculating properly as it is supposed using the same calendar day for a year instead of adding 365 days. V6 does not behave this way

Contacts: Kimberly P., Paloma A.
ROWID: 12869899

This is card 309 on the V7 UAT (PAID) Board

**Comment by Nadin-Nader** [comment]
Notes from Subhas research:

Testing Observations:
V7 TEST RSN-12870683, 12870713.
It is working as in V6. The expiry date is gettting calculated as the same (current date) in next calendar year instead of adding 365 days.
The random expiry date is being added before it updates with the correct expiry date. The same thing is happening in V6. But in V7, we need to refresh the folder tab to see the actual expiry date.
When we did UAT on V6 TEST, we had let Paloma/Kim know about it.

**Comment by TracyLinder** [comment]
@vschandramouli please get this ready for development & move to the top of the backlog.

**Comment by vschandramouli** [comment]
Updated AC. Moving to Backlog.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - AC Point1 has to be worked on but not Point 2 as its not valid anymore.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV DP Submitted. Please approve and create task id for the same.

**Commit ID**
1.	Order 1 - [8729bf814fbb](http://coaamandadevops02.austintexas.gov/R5:8729bf814fbb4b473cd0bc6a3fba6c3a253b51c6)
2.	Order 2 - [f60fa8d17deb](http://coaamandadevops02.austintexas.gov/R5:f60fa8d17deb1110c59e3a528d319158efe92ef9)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to DEV under **SCTASK0312370**

**Comment by Nadin-Nader** [comment]
@sree this has been deployed to DEV. Please UAT

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - TEST DP's submitted. Tested the same in DEV and its working as expected. Kindly approve and create task id for the same. 

Commit ID –

Order 1 - [8729bf814fbb](http://coaamandadevops02.austintexas.gov/R5:8729bf814fbb4b473cd0bc6a3fba6c3a253b51c6) 
Order 2 - [f60fa8d17deb](http://coaamandadevops02.austintexas.gov/R5:f60fa8d17deb1110c59e3a528d319158efe92ef9)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan this has been sent to The DevOps CM Team to be deployed to TEST under **SCTASK0313938**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Tested in TEST and it is working as expected; TEST Folderrsn :12892066

Ready for UAT in Test

**Comment by TracyLinder** [comment]
### Approved for PROD by stakeholders during Friday review

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - #9788 PROD DP submitted. Kindly approve and create task id for the same.

Commit ID -
Order 1 - [8729bf814fbb](http://coaamandadevops02.austintexas.gov/R5:8729bf814fbb4b473cd0bc6a3fba6c3a253b51c6)
Order 2 - [f60fa8d17deb](http://coaamandadevops02.austintexas.gov/R5:f60fa8d17deb1110c59e3a528d319158efe92ef9)

**Comment by Nadin-Nader** [comment]
This has been sent to the DevOps CM Team to be deployed to PROD under **SCTASK0316654**

**Comment by Nadin-Nader** [comment]
Sent message to Kyle and ROW informing them that this is ready for UAT on TEST. waiting on response

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan  this was approved by Kyle. Closing

> [11:38 AM] Kampe, Kyle
>     UAT approved. Sorry for delay. Thanks!
