### ISSUE TITLE
Transition from Airflow DAG to Prefect Flows for two VZ ETLs

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9789]
Two Vision Zero ETL processes have been ported to Prefect. They are:

1) Extracting and loading new crash data from CRIS into the VZDB
1) OCRing the crash investigator's narrative and extracting their diagram for storage on S3 and use in the VZE

This issue is to track the conversation, planning, and work around completing this task. Pending group approval, I'm hopeful to get this completed this Friday in the afternoon, as it leaves the most time to handle any issues prior to the next business day. 

Completion criteria:

- [x] Merge PRs 14 & 9 for `atd-prefect`
- [ ] (Identify and turn down the Airflow DAG
- [x] Setup VZ dockerized agent on `atd-data03`
- [ ] Register, test and schedule flows on Prefect
- [ ] https://github.com/cityofaustin/atd-data-tech/issues/7814 closed

**Comment by frankhereford** [comment]
@mateoclarke insightfully suggested that we can do the OCR ETL first because it is very low risk. We can wait until that is stable and use the lessons learned from that deployment to then move on the crash loading ETL, which has a larger risk for disruption.

**Comment by patrickm02L** [comment]
- [ ] Close Issue #7814 when this Issue has been closed.

**Comment by frankhereford** [comment]
@patrickm02L wrote:
> * [ ]  Close Issue [Indicate when CRIS ETL script runs successfully #7814](https://github.com/cityofaustin/atd-data-tech/issues/7814) when this Issue has been closed.

You bet. I added the closure of 7814 as a completion criteria. Thanks!

**Comment by frankhereford** [comment]
This has been completed for the OCR flow, and we'll do the import flow next week or whenever there is group consensus.

**Comment by frankhereford** [comment]
This is being completed by the following steps rolling out a new version of this ETL process, as seen [here](https://github.com/cityofaustin/atd-prefect/pull/28#issuecomment-1251477196).
