### ISSUE TITLE
Meeting: CCMS Stakeholder Review #2 (8/16/22)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9793]
### Meeting with ROW stakeholders to review updates & do more discovery on the court & prosecution management workflows & features. 

- Aug 16, 2022 @11am
- 1st review #9596

**Comment by KaroEngstrom** [comment]
Met with the stakeholder team T 8/17/22. Agreed that they are ready to start piloting this by entering data to the system for several weeks. A follow-up meeting to be scheduled in 4-6 weeks. 

#10034 Updates from this meeting were completed, including a help guide. Sent an email to the stakeholders letting them know. 
@TracyLinder may have additional notes. Putting this in QA/Review and will check back.
