### ISSUE TITLE
Complete Requested Updates to ROW CCMS from Stakeholder Demo 2022/97/19

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#9794]
### Updates Requested #9596 

**CCMS HOME**

- [x] Add table export feature

**ADD VIOLATION**
- [x] Rename RSN to ROW ID
- [x] ^ Other associated pages (all table views) - Violations table, Violation Details view, Edit Violation form, Cases table; My Cases page - Assigned to Me and Created by Me tables
- [x] New field - Violation Location (short text)
- [x] ^ Add new field to pages and forms where applicable: Violation and Cases tables; Add Violation and Edit Violation forms; Violation Details; My Cases page - Assigned to Me and Created by Me views
 
**VIOLATION DETAILS**

- [x] Comments table: Add an edit feature
- [x] Attachment Type: Add Notice to Appear
- [x] Create New Field: Resolution Type (drop down, only 1 value, mandatory) [Guilty, Not Guilty, No Contest, etc. ]
- [x] Create New Field: Resolution Notes (paragraph)
- [x] Case Description: Make a paragraph type & rename to Description
- [x] Add new Resolution fields to the right-hand column in top Details view

**RESOLVE FEATURES**

- [x] Resolution Form: Add Resolution Type (mandatory), Resolution Notes (optional) 

**AUTOMATED STATUS’**

- [x] Change ON HOLD to PENDING COURT DATE

**PEOPLE**

- [x] Rename to AMANDA People ROW ID

**MY CASES**

- [x] Add an export feature

CASE 
- [x] Add Scheduled Court Date field to the case object, Details view, and Edit form

**COSMETIC CLEAN-UP** 

- [x] Add an icon for the Reviews table and any others that may be missing
- [x] Edit < br > Status instead of Edit Attachment Status if you want to shorten that column width
- [x] Remove "Add Review" title for the modal (since modals use page title already)

COMMS TO STAKEHOLDERS

- [x] Export and share workflow document as PDF
- [x] Add stakeholder team as users to allow testing in ROW CCMS module (Blake B; Nick M; Darren U; Gary Z)

**Comment by TracyLinder** [comment]
### Notes

- [ ] Review updates made
- [ ] Workflow/status/automation questions
- [ ] Feedback
