### ISSUE TITLE
Update component types

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#9795]
Per [today's meeting](https://docs.google.com/document/d/1A6yjlIyc9tLuGUZ9OAKpLBVPE5vsmeT3C07kiv2Cpsc/edit#heading=h.el7ahve1jrul) with PDD and TED will need the following additions and modifications in the `moped_components` table:

| component_name | component_subtype | line_representation| status_id | _note to dev_ |
|-- | -- | -- | --| --|
|Lighting | Street lighting | TRUE | 1 | _new component type and subtype_ |
|Lighting | Intersection lighting | FALSE | 1 |_new component type and subtype_ |
|Transit | Bus stop | FALSE | 1 | _new subtype_ |
| Project extent - generic | - | TRUE | 1 | _change from point to line representation_|

**Comment by johnclary** [comment]
@amenity i updated this to include the DB deets (mirroring https://github.com/cityofaustin/atd-data-tech/issues/6163).

I estimate DB changes as a `2` but this is a really small `2`.
