### ISSUE TITLE
Utilize requirements.txt in the Dockerfile for dockerized-agents when installing python libraries into the docker image

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9801]
See https://github.com/cityofaustin/atd-prefect/pull/9#discussion_r924903446. 

In reference to the way python libraries are installed in the dockerized-agent system, @johnclary wrote:
> can these pip install commands be combined into a single requirements.txt file (with pinned version numbers), and installed here with RUN pip install -r requirements.txt?

I responded:
>Broadly yes, I think it's more pythonic to utilize pip's ability to freeze out an environment and install from the requirements.txt which is generated. However, it's a little bit tricky here because the Dockerfile is defining the environment for the agent which can run multiple flows, and I envision each flow having a requirements.txt. I will investigate a way to have the Dockerfile iterate over each flow's requirements.txt and install from there.

>I'm not sure how much this matters, but one thing the docker file's pip invocations are doing is installing these as system-wide available python libraries within the dockerized linux host and not into a encapsulated venv.

Edit: I had misunderstood the importance of the versioning capabilities delivered from the requirements.txt. Using it instead of the pip command line install is a must-have.

This issue intends to track that conversation, plan and execution. I am hopeful to have this assigned to me, but it does need to go through the normal process of scoping and prioritization. @mateoclarke, can this be something we touch on quickly in grooming?

**Comment by frankhereford** [comment]
@chiaberry posted a notice she received in the prefect slack: the default version of prefect that comes from `pip install prefect` will tick over to 2.0 on July 27th, and that the major upgrade from v1 to v2 will include breaking changes. 

I hadn't put it together, but not having the requirements.txt versioning capabilities is much more impactful than I had figured. I'm changing this label from should have to must have, and I'm even more looking forward to grooming it. Thanks again for bringing this back up @johnclary.

**Comment by johnclary** [comment]
@frankhereford I thought the per-agent Dockerfile was meant to provide an environment for all flows that this agent would run. As you add more flows to the VZ agent's scope (e.g. the narrative extractor), do those requirements get stuffed somewhere else?

FWIW if it makes life easier I think it's fine to let one requirements.txt grow to support all of an agent's tasks. If an agent is generally managing roughly a repo's worth of ETLs, it would hopefully be rare for us to run into major dependency conflicts.
