### ISSUE TITLE
Execute 4 tasks supporting the test deployment system

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9803]
During a conversation with @mddilley on July 19th, 2022, we agreed that these would be good tasks for me to work on next in support of our joint work on the test development system:

* [x] Use Mike's work re: postgres, change to the `graphql-engine` image
* [x] Write a function which can do `slug = generate_slug(feature_branch)`
* [x] Write a MVP github action which invokes a prefect flow passing an argument
* [x] Extend the ECS to block until the ECS containers become responsive

**Comment by frankhereford** [comment]
@mateoclarke @amenity 

Would it be OK to assign this to me and bring it on deck? These are each pretty small changes, and they will be allow us to get the first Github Action → Prefect → AWS demos going for the `test` system. Thanks!

I'd love to talk about them also in grooming today if you think that would be helpful.

**Comment by amenity** [comment]
Fine by me, @frankhereford @mateoclarke. Just stick a sprint on here when we start, plz

**Comment by amenity** [comment]
We may also need an issue for authentication. TBD.
