### ISSUE TITLE
User Gary Z unable to log into AMANDA 7

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#9810]
Email from Blake B, forwarded from Gary Z: 

"I tried to log in to AMANDA 7 thru the link in the email and it wont open. The screen shows processing icon but never loads. Instructions said to notify supervisor of issue.
 
If you have ANY issues logging in *OR* any issues with your permissions, please notify your supervisor.  Supervisors – Please consolidate those issues and then send a comprehensive list on to Darren, Ryan, and I."

**Comment by Nadin-Nader** [comment]
Gary is now able to log into V7 after requesting the system to reset the password
