### ISSUE TITLE
Give SMS Permission to Test DOLA

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9811]
We need to configure the emails to the final correct configuration

Need to check all email notifications
- [ ] Customer Submission
- [x] Reviewer Submission
- [x] Complete Action Email - Reviewer
- [x] Complete Action Email - Reviewer
- [ ] more?

**Comment by patrickm02L** [comment]
Waiting to do this after #9282.

**Comment by dianamartin** [comment]
Will complete this task the morning of the SMS Sprint Review on 8/19

**Comment by patrickm02L** [comment]
@dianamartin please set permissions before Friday's 8/17/22 SMS Sprint Review.

**Comment by dianamartin** [comment]
We need to check in with Courtney to find out which users need to get the email for the Permit Team review. @patrickm02L are you going to reach out?

**Comment by patrickm02L** [comment]
Sent email on 8/25/22 to Courtney H. asking who should get the email notifications.

**Comment by dianamartin** [comment]
Courtney replied 8/29
provided us the emails to use for her team. 

>My apologies for the delayed response as I have been out of the office. Our team is currently directing everyone to send them notifications thru the [MobilityServices] email versus multiple individual email addresses to recall. You would also list my personal email as the Supervisor of course, [CourtneyH].

>I copied my direct Supervisor, Jacob C, on this response. We are looking forward to the new program and let me know if there are any other questions that may arise
