### ISSUE TITLE
Create New Feature Layer for Contractor Work Orders API

### ISSUE THREAD

**Issue by KaroEngstrom** [cityofaustin/atd-data-tech#9817]
This is part 2 of #7441 

- [x] Export all fields from [here](https://builder.knack.com/atd/signs-markings/pages/scene_1249) for GIS (**Contractor Work Orders** table at the bottom of the page)
- [x] [contractor_work_orders.csv](https://github.com/cityofaustin/atd-data-tech/files/9253401/contractor_work_orders.csv)
 - [x] Request feature layer to match those fields

**Comment by dianamartin** [comment]
@andrewshensky We would like to request a new feature layer for the "Contractor Work Orders" 
- feature type: line (like markings work orders)
- you can name the fields how you need to in AGOL (ex. underbars)
- Using this schema: https://data.austintexas.gov/Transportation-and-Mobility/Roadway-Markings-Work-Orders/nyhn-669r

Let me know if you have any questions. SMD would like to have this soonish. I can ask Christina the time frame.

**Comment by andrewshensky** [comment]
@dianamartin I have a couple questions below:

- Will this just need to be an empty dataset that will eventually be populated with data coming from knack? 
- Will the fields need to match those included in the csv provided in the link above?
- In the schema link you provided it looks like nearly all numeric/ID fields, except one length field, are being captured as text, is that how this layer should be created as well?

**Comment by dianamartin** [comment]
@andrewshensky 
- it should be an empty dataset, will be populated from data in Knack
- This a resource article about the [AGOL Integration steps](https://atd-dts.gitbook.io/atd-knack-operations/knack-integrations/arcgis-online-integration)..so we're both on the same page

These are the field types from Knack

Work_Order_ID | Text |  
-- | -- | --
Created By | Text |  
Created Date | Date |  
Modified Date | Date |  
Work_Order_ID | Text |  
Parent WO | Text |  
Parent WO -   FIELD | Text |  
Work_Authorization_Number | Number |  
Assigned   Contractor | Text |  
Assigned To | Text |  
GIS_ID | Text |  
Instructions   Comments | Text | Max length
Follow-up   Instructions | Text | Max length
From Street | Text |  
To Street | Text |  
Street Display   Name | Text |  
Area | Text |  
Centerline   Miles | Number |  
Work Order   Status | Text |  
ATD Issued   Date | Date |  
Contractor   Submitted Date | Date |  
Contractor   Submitted By | Text |  
Count   Attachments | Number |  
Count Comments | Number |  
Count   Inspections | Number |  
Count Work log | Number |  
Work Status | Text |  
Primary Parent   WO | Text |  
recordID | Text |  
GIS QA | Text |  
STREET_SEGMENT_IDS | Text |  
WORK_GROUPS | Text |

**Comment by andrewshensky** [comment]
@dianamartin I have created a the new feature in layer in AGOL through the link below. It is currently shared to the public to match other similar layers. Let me know if any changes need to be made to the data or settings.

https://austin.maps.arcgis.com/home/item.html?id=65457b568fb94e92a7790a947c7b6690

**Comment by dianamartin** [comment]
@andrewshensky I finally figured out where the markings work order [feature layer](https://austin.maps.arcgis.com/home/item.html?id=a9f5be763a67442a98f684935d15729b&sublayer=1&view=table&sortOrder=desc&sortField=defaultFSOrder#data) information is, I'm wondering if you need to create the feature layer under this `ATD_Publisher_Scripts` account instead. 

I was looking at the field names and it's all caps with all underbars, do you think we need to match it to be the same?

**Comment by dianamartin** [comment]
Pavement Markings Work Order Feature
![image](https://user-images.githubusercontent.com/21112975/182910533-8c9d2b3d-20ee-4ed9-9f20-29d21f7e2964.png)

Contractor Work Orders
![image](https://user-images.githubusercontent.com/21112975/182910575-1e3ba77c-5ea1-45db-9755-ada736ad77e6.png)

**Comment by andrewshensky** [comment]
@dianamartin I have updated the Contractor Work Order data structure to be in all caps for consistency with other datasets. The dataset is also published through the ATD_Publisher_Scripts account. Let me know if any other modifications are needed. The link to the data in AGOL is below:

https://austin.maps.arcgis.com/home/item.html?id=7eb2da1d8e6c4f79b368d8e295dec969

![image](https://user-images.githubusercontent.com/80716478/182962624-54fd1b1d-1817-4ddf-9f38-d8c9ce713d18.png)

**Comment by dianamartin** [comment]
Thanks Andrew, I'll check it out - if all seems well I can ask the devs to make the ETL happen
