### ISSUE TITLE
Design Viewer prototypes in XD

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9826]
As the UX/UI Designer for the Mobility Viewer (external version), I need to design prototypes of the product for the purpose of user testing, 

- [x] Complete prototypes for internal version - Moped Projects Map (#9631)
- [x] Send prototypes for design/dev feedback (#9785)
- [x] Share revised XD prototypes for Viewer with team, likely @patrickm02L / @amenity 
- [x] Send new prototypes for design/dev grooming feedback (no issues yet)
- [x] Do any design refinements
- [ ] Pursue implementation plan with dev team

**Comment by rebeccabrand** [comment]
First pass at low-fi prototypes for ax external Moped Viewer![Screen Shot 2022-07-21 at 5.33.48 PM.png](https://images.zenhubusercontent.com/62a6851f8cb947503837405d/7d13b795-5ce8-4c27-8d8a-a20f2cceb3b9)

**Comment by rebeccabrand** [comment]
@patrickm02L / @amenity - here are the Mobility Project Viewer [prototypes for design review.](https://xd.adobe.com/view/00da9a79-2215-4700-9335-4b0ae1481a9e-5589/)

It's mostly the same as Projects Map, but with some tweaks for public-facing view and mobile view.

Once you have approved, I will send to dev for feedback. Thanks!

**Comment by amenity** [comment]
@rebeccabrand  - thanks! Looks great to me.
