### ISSUE TITLE
CIC final presentations

### ISSUE THREAD

**Issue by rebeccabrand** [cityofaustin/atd-data-tech#9828]
Rose & Rebecca will present their fellowship work to the team on  **Thursday, August 19th.** Creating an issue to track deliverables.

- [x] Rose presentation complete
- [x] Rebecca presentation complete

**Comment by rebeccabrand** [comment]
@patrickm02L - my working [presentation is living here.](https://docs.google.com/presentation/d/1Uj_ikyZ8ug-BApNoAGi9UiPmMVa6SmBlhU2_6a7J8ss/edit#slide=id.g14484ed950c_1_204)

**Comment by roseeichelmann** [comment]
@patrickm02L / @rebeccabrand - Almost forgot, [here is mine](https://docs.google.com/presentation/d/14XpVVlCSes8ohGNiUbaqSN0OSxXq3NCbaMoFStZDkbs/edit?usp=sharing)

**Comment by patrickm02L** [comment]
Fantastic work!
[Video ](https://drive.google.com/file/d/17_dDwNy-3_2O5TqjcZ45Bpxs2suLjVB-/view?usp=sharing) from Final Presentation on 8/18/22.
