### ISSUE TITLE
Testing Feedback HR Digital SSPR

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9840]
- Add SSPR Meeting

Meeting Type: SSPR Planning Meeting
Add this as a heading: **This is to acknowledge that my supervisor and I have discussed:**

**Comment by moorerst** [comment]
- I already copied the priority from mid year to year end but the Copy To Year End option still appears - should it still be there?

![image](https://user-images.githubusercontent.com/56606465/181066814-1dec1af3-69cc-457a-96ef-041aa83bbcbf.png)

- The SSPR Status is not changing as I go through the process. I have completed Planning/Mid Year/Year End but the SSPR status is still **Mid Year In Review**

**Comment by moorerst** [comment]
@dianamartin here are a few comments from my testing

**Comment by dianamartin** [comment]
- [x] I added a display rule on the "Priority" table, so if "Type" is Year-end, then the "Copy" button doesn't appear
## Mid-year
![image](https://user-images.githubusercontent.com/21112975/181116381-ffa2438d-e705-4bd8-b757-73ed628181a2.png)
## Year-end
![image](https://user-images.githubusercontent.com/21112975/181116433-cbd44164-7c7e-4003-b7fc-5ea38b22e51d.png)

**Comment by moorerst** [comment]
reviewed these updates with stakeholders during the sprint review. Closing this issue
