### ISSUE TITLE
BCA Vetting Section

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9855]
Transfer the [BCA Template](https://cityofaustin.sharepoint.com/:w:/r/sites/SmartMobility-PublicPrivateInitiatives/Shared%20Documents/Pilot%20Program%20Knack%20Workflow/02_Documents/02_%5BDate-Company%5D%20-%20BCA%20Template.docx?d=w7986d7ae958243648382d20108506b51&csf=1&web=1&e=sGr5XE) to Knack.

**Comment by patrickm02L** [comment]
**Current Word Doc Template**

![request.jpg](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/8ada6f82-695d-49d9-8028-8288c4a14ac4)

![request-2.jpg](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/cea48572-d9ac-436e-a741-ab60dcada26b)

![request-3.jpg](https://images.zenhubusercontent.com/5d68810b05d7792664be403f/738f3dba-ce64-4f84-bf90-e85f1c4b2be5)

**Comment by dianamartin** [comment]
- [x] Added more fields based on the BCA document

@patrickm02L check out the BCA Project details [page](https://atd.knack.com/smart-mobility#p3-portal/p3-projects/p3-project-details/62e03476ed512500211c38fa/)

I hadn't figured out what to do for the signatures, so I'll leave it until we talk to the stakeholders

**Comment by patrickm02L** [comment]
Diana has removed the following fields based on our Sprint Review 08/12/22.

**System Development Steering Committee Findings**
- Recommended approval for implementation
- Follow-up Date
- Expanded Business Case Analysis
- Recommended Rejection reasons
