### ISSUE TITLE
Long Term Maintenance: Data Clean up of Admin backfill records

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9858]
We need to clean up the back fill data
- [x] export dataset
- [x] matching fields to correct object 
- [x] create new .csvs for import (one for each object)
- [x] import install records
- [x] import retire records

**Comment by dianamartin** [comment]
@ChrispinP please check in with Joana to see how they are doing, how far they are into the admin back fill task.

**Comment by ChristinaTremel** [comment]
Needs to happen before we go live with the traffic register!

**Comment by ChrispinP** [comment]
Prep & Migration of Backfill data to the regulation_item object was successful. They are connected to template records, the regulation_document, and regulation_relationship records created. Some additional cleanup is needed.

Pending any further action
