### ISSUE TITLE
Provide design feedback on Mobility Project Viewer XD file

### ISSUE THREAD

**Issue by rebeccabrand** [cityofaustin/atd-data-tech#9862]

**Comment by rebeccabrand** [comment]
@patrickm02L has provided comments on the public-specific version of the viewer.

Will [send link to](https://xd.adobe.com/view/00da9a79-2215-4700-9335-4b0ae1481a9e-5589/) @amenity & @johnclary to review ASAP.


Screenshots here for reference:
![Screen Shot 2022-08-10 at 4.53.03 PM.png](https://images.zenhubusercontent.com/62a6851f8cb947503837405d/edf4496c-43d2-4c00-899c-c52a2ef3fc24)

**Comment by patrickm02L** [comment]
Any additional feedback will be welcomed when we start building this out.
