### ISSUE TITLE
Project: Vision Zero Viewer

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#987]
## Description
This project seeks to create a public-facing interactive web map/app that shows crash data related to Vision Zero. Residents will be able to view crash data in a variety of visualizations, as well as explore a map that shows where crashes are occurring in Austin.

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://transportation.austintexas.io/about/) team. Project status is documented regularly in the comments below.

**Comment by JaceDeloney** [comment]
This `Index` issue has been migrated to atd-data-tech repo. I also created the `Project: Vision Zero Viewer` label within the atd-data-tech repo.

**Comment by amenity** [comment]
@JaceDeloney - does this go to _In Progress_?

**Comment by JaceDeloney** [comment]
This product was officially kicked off on 12/19. We now have a backlog full of requirements to move forward on. By the first week of January, we should have a set scope for v1 of VZV. Product artifacts can be found here:

VZV Board:
https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/board?labels=project%3A%20vision%20zero%20viewer&repos=140626918,178280308&showLabels=false&showEstimates=false

VZV "Designs":
https://docs.google.com/presentation/d/1YSq2VQO4rlUWof_RQNKUkconJnrD_QqizIgJtV9-Azg/edit?usp=sharing

WIP VZV Requirements:
https://docs.google.com/spreadsheets/d/1LrhtRIT-HHaIvCjaPuB6KKCetxMQAsuDTZE7VTX4bm4/edit?usp=sharing

**Comment by JaceDeloney** [comment]
### April Update 
The team has made significant progress on the viewer this month. The new designs have been implemented on the summary page and are currently being implemented on the map page. The next two sprints will be mostly polish and preparing for the first official public release.

We are aiming for a release date to the public on May 18th in coordination with the Vision Zero Team's street segment initiative.

**Comment by JaceDeloney** [comment]
**Status Update**
The CRIS data reprocessing effort has completed. The team has been implementing a variety of data quality improvements over the past several weeks. We have shared the URL to VZV with local Vision Zero advocates and have received good feedback. VZV is schedule for public release the week of July 7.
