### ISSUE TITLE
Activate AWS spend alerts

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9872]
Create dashboard in AWS webui or notifications from AWS on spending balance to better manage our contracts and forecast when new purchase requests are needed.

**Comment by mateoclarke** [comment]
Assigning this to @frankhereford since we've talked about it a bunch and I know he's keen on having more visibility into AWS costs. Also flagging for @chiaberry's visibility. 

It looks like the way we'd go about this is with the [CloudWatch](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#home:) service. Here's some relevant docs: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/monitor_estimated_charges_with_cloudwatch.html

The next step would be to look at our spending levels and choose thresholds for when alerts would be sent.

**Comment by chiaberry** [comment]
I am testing out https://aws.amazon.com/aws-cost-management/aws-cost-anomaly-detection/, I think I turned it on to alert if we go 10% over normal spending in any given week. Looking at our trends, we are pretty consistent.
