### ISSUE TITLE
Modify HR Digital SSPR Reporting

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9873]
Updates that were discussed during the sprint review

- [x] hide the Edit option after the SSPR has been signed

- [ ] ATD HR will need to provide a report to Central HR.
That report will need to include the following fields in this order:
(most of these fields are available on the employee record)
 
- Division Number
- Division Name - don't have this data
- Last Name
- First Name
- Current Hire Date
- Job Begin Date - don't have this data
- Job Title
- Location - don't have this data
- Location Description -  don't have this data
- Year-End Outcome -  don't have this data

- [ ] Need to have fields added to the employee record from the Banner report

Division
Orgn_Code

**Comment by dianamartin** [comment]
@chiaberry Do you know if any of these fields are available from the Banner side? The HR team is looking at updating the information that comes from the Banner script. 

They think that these fields might be available: 
- Division Number
- Location

@moorerst - were these the two field they wanted or more from the Banner script?

**Comment by chiaberry** [comment]
@dianamartin There is a division number (divnnbr), but no location
```
{"dept_name":"Austin Transportation",
"supervisor_name":,
"pidm":
"temp_status":"Regular",
"job_title":"
"email":
deptnbr":"24E",
"empclass_desc":"Standard/Exempt",
"hiredate":
"empclass":"02",
"divn_name":"Finance and Technology",
"divnnbr":"\t24E130",
"fullname":
"posn":}
```

**Comment by dianamartin** [comment]
@chiaberry thanks, we'll report back to the stakeholders

**Comment by moorerst** [comment]
@dianamartin I'm not aware of any task we need to do for this issue. This will probably come up again as we get further into the SSPR timeline. Do we need to keep this issue open?

**Comment by dianamartin** [comment]
We're waiting on HR staff until we start tackling this issue

**Comment by dianamartin** [comment]
HR hadn't reached back out about reporting needs. We'll create new issues if reporting enhancements come up. Closing.
