### ISSUE TITLE
Project: ROW Performance Volume Tracking Dashboard

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9876]
We are compiling multiple sets of data related to Right-of-Way performance and creating a PowerBi dashboard to display the data to internal users. 

## Background

The Right-of-Way Management division of ATD uses various software to manage their services. At this time management has no comprehensive way to compile ROW performance data, impacting their ability to make data driven decisions.  

## Scope & Deliverables

We will create a ROW Performance dashboard that incorporates data from:
- AMANDA
- KNACK
- 311

## Desired Outcomes

Internal business partners will have access and tools so they can make data driven decisions. 

![Screen Shot 2022-07-28 at 4 41 53 PM Cropped](https://user-images.githubusercontent.com/49930868/181642736-02e94e7c-0fb1-456b-8dde-6a6fc90498b8.png)

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://austinmobility.io/) team. Project status is documented regularly in the comments below.

**Comment by amenity** [comment]
@katelunceford Darren U. in ROW is our key stakeholder here, so let's include him and this request when we meet with ROW as part of #10912.

**Comment by Charlie-Henry** [comment]
@TracyLinder wanted to let you know that we will be visualizing ROW's data from AMANDA and knack in the next few weeks in the executive dashboard. Hopefully this is related to this effort too https://github.com/cityofaustin/atd-data-tech/issues/11457

**Comment by amenity** [comment]
Yes, @TracyLinder confirms that this is covered by #11457.
