### ISSUE TITLE
Polish Scheduler "Add Assignment" modal

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#988]
![Untitled](https://user-images.githubusercontent.com/1463708/70481938-c085a280-1aa9-11ea-9c05-fd0f8cf9c497.png)

**Comment by amenity** [comment]
Updated to reflect _School, Corridor, Intersection_ Location types

**Comment by SurbhiBakshi** [comment]
@amenity  - think I found only one example of intersection. Have reconfigured the form, if you want to test it. 

The Location process will  need some more work on the back end to incorporate intersections - both the form, and the integration with the data sets from Data Tracker for geospatial reference later.

**Comment by amenity** [comment]
@SurbhiBakshi  - Beautiful! 

Thinking about how the conditional is kinda gunking up the data model, if we did
- Location Type
- APD Sector
- Name 
- Description

Could we still filter down the Name field based on the two fields above without the conditional?

**Comment by SurbhiBakshi** [comment]
So by Name you mean - location (Corridor/ Intersection/ School)? The way I have it working now, Location Type directs the Display Rules to pull the right connection field (Corridor/ Intersection/ School) and the APD Sector filters the drop down to fewer options. 

I don't know if there is a way to simplify the data model and still keep the form functionality. That would be a question for @johnclary .

**Comment by johnclary** [comment]
I think @amenity is just suggesting you change each of field labels for corridor, intersection, and school to be "Name". So, regardless of the location type, the location selector is always labeled "Name".

I like that idea, but would suggest you use "Location Name"  rather than "Name."

**Comment by amenity** [comment]
Yup, that. :) I think the way you have it now is fine and I _think_ during our discussion on Tuesday we determined that the data model can't really be simplified anyway. 

The benefit of calling them all "Location Name" would be preventing the UI from changing when the user changes their options. If this were a more dramatic conditional, e.g. if totally different fields showed up based on the different options, it makes sense for the user to see that. But if it's subtle, it's nice to prevent that flash of text and keep the form a little calmer.
