### ISSUE TITLE
HR Digital SSPR Stakeholder Testing

### ISSUE THREAD

**Issue by moorerst** [cityofaustin/atd-data-tech#9885]
HR Team will be testing the Digital SSPR using the Help Guides

**Comment by moorerst** [comment]
Stakeholders been testing on 8/2
They will compile their comments/questions and suggestions on Friday 8/5.

**Comment by moorerst** [comment]
@dianamartin this is what I was starting as a testing guide for HR
https://docs.google.com/document/d/1CzcwZn2jYvVHIpA9BcKXaJK54GBInG75_umaybDzc3w/edit#

**Comment by dianamartin** [comment]
@moorerst I updated the text you added and put it in "blue text" so we can see what you added when we sync up again

**Comment by moorerst** [comment]
Sent updated testing documentation to stakeholders.

**Comment by moorerst** [comment]
Per stakeholder - The workflow guide you created has been extremely helpful. Hannah and I went over the Planning directions yesterday and have only a few questions. We will meet later today to go over the Year End review and will submit our findings.

- [ ] will review the comments added to the google doc

**Comment by moorerst** [comment]
Stakeholders provided a feedback document. We'll review the comments/issues and create new issues for items that need to be addressed.

Follow up meeting scheduled 9/6

**Comment by dianamartin** [comment]
We had meeting with stakeholder on 9/6 and we went through their feedback document and showed them the small tweaks we made. They're pretty happy with what we've got. Stephanie and I wish to test more in depth to polish and then she'll meet with them again.

**Comment by moorerst** [comment]
@dianamartin I think we can close this issue. I'll open a new issue for stakeholder testing round 2 and add their feedback to the new issue

**Comment by moorerst** [comment]
Round 1 of stakeholder testing complete
