### ISSUE TITLE
V7 BUG: Special Parking On Street Notification (SPOON) batch Report 56103  is not being sent out to the users at 5am every morning

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#9889]
V7 BUG: Special Parking On Street Notification (SPOON) batch Report 56103  is not being sent out to the users at 5am every morning.

**Comment by TracyLinder** [comment]
Nate asked Robert @ CTM to help debug & sent the manual report to stakeholders. Thanks @Nadin-Nader

**Comment by Nadin-Nader** [comment]
Jenice at CTM is currently working on the Batch Scheduler as it is not running properly

**Comment by Nadin-Nader** [comment]
This has been fixed. Closing
