### ISSUE TITLE
V7 Bug: Unable to add rows to free-form on RW-TURP & EX folders

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9894]
### Error when saving a new row on the RW-TURP and EX free-form tab. 
_Test IDs are TURP: 2987843, EX:12987846_

<img width="1057" alt="Screen Shot 2022-08-02 at 12 43 58 PM" src="https://user-images.githubusercontent.com/49930868/182440810-17d9fa14-a732-46be-b8c5-c01d547fa7e9.png">

**Comment by TracyLinder** [comment]
I was able to add a row on RW-Film without issue. PROD ID 12987466

**Comment by SubhaShroff** [comment]
@TracyLinder  I couldn't get to PROD login page also. So, I tried on V7 TEST. There is no issue there.
By looking at the error, can you please try again?

**Comment by TracyLinder** [comment]
I tested again on both TURP and EX. 
- ✅ TURP - No issues 
- ❌ EX FAILED; same error

**Comment by TracyLinder** [comment]
https://trello.com/c/WxAZaGZm/427-free-form-error-on-rw-turp

**Comment by SubhaShroff** [comment]
@TracyLinder since you could add the property info row for both TURP and EX and since you said we close it. I am closing this ticket. The related trello#427 also closed. Thanks.
