### ISSUE TITLE
V7 Bug: Unable to update info 'Event End Date' on RW-TURP (On PROD & Working)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9895]
<img width="1109" alt="Screen Shot 2022-08-02 at 12 46 39 PM" src="https://user-images.githubusercontent.com/49930868/182440608-c5605f93-239a-4d28-8a0f-27170b4eb620.png">

**Comment by TracyLinder** [comment]
I just tested this again & the bug is still there.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan can you please begin debugging?

**Comment by TracyLinder** [comment]
Subha will write code to allow this info to be editable on RW, EX folders. 

I think this is a bug with the info, but it seems easier to implement this code vs fixing the system bug right now.

**Comment by SubhaShroff** [comment]
@TracyLinder @Nadin-Nader  Sandbox merge is done this code change. I tried to test but looks like it will take time to actual code merge to take place. Will retest in a while.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  The script is deployed in Sandbox and tested it for RW. Since, I see its only Event Start Date, Event End Date that were the issue, I fixed these two for RW. These infos are not with EX, so I think we are good with EX.

Please let me know if we are moving this fix to the next environments or wait until the DEV deployments start.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  SCTASK0242465 is submitted for DEV deployment.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  @TracyLinder  DEV deployment is done and I tested it on DEV. Looks working. Please UAT and let me know if we can get it on TEST?

**Comment by Nadin-Nader** [comment]
@SubhaShroff lets get this to TEST

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0242860 is submitted for TEST deployment of this ticket.

**Comment by TracyLinder** [comment]
@Nadin-Nader or @SubhaShroff can you confirm if this is in test yet please? Thank you.

**Comment by SubhaShroff** [comment]
@TracyLinder  George deployed it in TEST yesterday. But, its not in Database. So Martin is working on this now. I will update you once I hear from him.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  Martin fixed it manually on TEST and I tested it. Now we can edit Event End Date info RW-TURP.

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  This is UATed by Jonathan in today's call and since you have approved I submitted the PROD deployment request - SCTASK0243874 (feb914dc0c4a).

**Comment by SubhaShroff** [comment]
@TracyLinder  @Nadin-Nader  This ticket is deployed in PROD. Verified the change on Database.  Please verify.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @TracyLinder this was confirmed that it works by Jonathan W. 8/26/22 @ 12:19pm
Closing

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Since the user reported the bug fix is gone and we are working on it, I am reopening it.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  Jenice has redeployed the fix in SAndbox/DEV/TEST/PROD.
Can we ask the user to verify it on PROD? Thanks.

**Comment by SubhaShroff** [comment]
@Nadin-Nader  can we close this since Richard Driscol confirmed its working on PROD?

**Comment by Nadin-Nader** [comment]
Richard has confirmed this has been fixed again
