### ISSUE TITLE
V7 Bugs: RW-Valet Parking Annual (missing infos)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9896]
**Acceptance Criteria (Info Fields)**

- RW Valet Annual folder is missing the info field '# On-Street Parking Spaces'. 
- The folder also does not need to have 'Number of Double Meters' and 'Number of Single Meters' info fields. 

<img width="680" alt="Screen Shot 2022-08-02 at 1 28 41 PM" src="https://user-images.githubusercontent.com/49930868/182447419-cb690125-a3ac-46a6-85b5-568aae4c3250.png">

We are missing the “# On-Street Parking Spaces” Info field. There are two new fields in it’s place “Number of Double Meters” and “Number of Single Meters”. (Unsure if this is impacting our ability to issue the permits.)

**Comment by TracyLinder** [comment]
Currently the issue description is what was sent to us by Paloma. It needs more scoping.

**Comment by TracyLinder** [comment]
I've asked @vschandramouli to scope this out.

**Comment by TracyLinder** [comment]
@Nadin-Nader this is ready to be assigned.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Sent an email to Martin about the investigation. 

RW - Valet Parking Annual Info’s missing and additional info’s are in V7 PROD but not in V7 TEST

>> The below info “#of On Street Spaces for Valet (75925)”is in V7 TEST and not in V7 PROD; This must be in V7 PROD as well. May I know why this is missing? And do I need to send commit for this?

 



>>Number of Double Meters (77320) & Number of Single Meters (77315) these two info’s must not be in PROD and this has to be removed; however it is not there in TEST, wonder how this is in PROD ?

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - It looks like PROD has the above info and two Single meter/double meter info's are not there in PROD. Could you please try once again and this can be closed.

**Comment by Nadin-Nader** [comment]
This was confirmed to be working on PROD
