### ISSUE TITLE
FY23 Developer Fee Documentation (On PROD)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9897]
### Create documentation for our developer to use to update this year's fees. 
- The documentation is [here](https://cityofaustin-my.sharepoint.com/:f:/g/personal/tracy_linder_austintexas_gov/EtyobZGy1kRNgFrRtas02MwB-n3g4-G1ySCUmc8EHMYUzw?e=pSdMgz). 

Updated document below:
[https://app.zenhub.com/files/140626918/c281f91a-1646-477a-82c2-f402b1d01117/download](https://app.zenhub.com/files/140626918/c281f91a-1646-477a-82c2-f402b1d01117/download)

**Comment by TracyLinder** [comment]
Note from Sree: Create separate tickets:
- Update amounts
- New fees

**Comment by vschandramouli** [comment]
Updated the document. Please review @TracyLinder @Nadin-Nader

**Comment by Nadin-Nader** [comment]
#9064 has the OSE Fees to be updated

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Analysis is in Progress

**Comment by Nadin-Nader** [comment]
9064 = SCTASK0250678

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - DEV & TEST DP Submitted for #10182 changes. Kindly approve and create task id for me.

Commit ID: [496a8c403e12](http://coaamandadevops02.austintexas.gov/R5:496a8c403e1208a9734ff28c500bbee6e8c9cde4)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - For expanded excel changes, submitted DEV/TEST DP. kindly approve and create task id for me

Commit ID: [1e6338d16a6d](http://coaamandadevops02.austintexas.gov/R5:1e6338d16a6d9402b845d55389998209423e79f0)

**Comment by Nadin-Nader** [comment]
@Sreelatha-BlazeKannan I have sent those 2 commits to the DevOps CM Team to be deployed to **DEV,** and **TEST** under **_SCTASK0252187_**

**Comment by SubhaShroff** [comment]
@Nadin-Nader  SCTASK0252436 is submitted for DEV/TEST deployment.
