### ISSUE TITLE
Implement APD admin role

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#990]
Interface for Pat to log in and see assignments

**Comment by SurbhiBakshi** [comment]
@amenity -  I created a Viewer role with access to the Assignments and Reports pages. Jen and Pat can both be assigned the Viewer role, so they can look up assignment details like time and location, as well as officer details like name, and phone number.  
I will create a separate table like I did for the scheduler and assigner, but with no editing permissions, so the Viewer will see the Calendar and the Viewer table.

**Comment by amenity** [comment]
@SurbhiBakshi - sounds great.
