### ISSUE TITLE
Gather requirements for additional user roles

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#991]
Document user stories for roles outside Scheduler, Assigner, and Officer. (MMC staff, Jen, Pat...)

**Look into**
- How many additional roles do we need, e.g. is it problematic if MMC can see list of officers and phone numbers?
- Shift reassignment workflow, e.g.  — who is involved, how often does it happen, etc.

**Comment by SurbhiBakshi** [comment]
- [ ] this may also be a change in location for an assignment that was changed a few days before, probably good to notify officers when that happens.

**Comment by amenity** [comment]
Ah, interesting, @SurbhiBakshi. I must have missed this use case. Is it usually Jen who makes such changes?

**Comment by SurbhiBakshi** [comment]
@amenity - 
Jen could ask Lewis to change the assignment location a few days back (which could be an email), or ask that officers be redirected to another location while on another assignment - think this is why she wanted  MMC staff to have Viewer access and  be able to see assignment location, date and Officer contact details (based on what I heard two Sprint Reviews back)

**Comment by amenity** [comment]
@SurbhiBakshi - good to know. Realized what we really need is a bigger issue where we gather these stories and others for the Viewer role so I updated the title and description accordingly!

**Comment by amenity** [comment]
#2813 covers this.
