### ISSUE TITLE
Create Slide Deck for DOLA improvements

### ISSUE THREAD

**Issue by patrickm02L** [cityofaustin/atd-data-tech#9911]
DTS would like to present the process for building out the Online Application for SMS in order to show the value and benefits it has to offer from the previous PDF process. 

**Highlight** 
- Problem statement
- Before and After states
- Time savings
- Pain points
- Value

Slide deck should live in SMS folder in Products and Projects.

This is something that would good for Peggy to have as well when she's presenting our work to Execs.

**Comment by dianamartin** [comment]
I started the slide deck [here](https://docs.google.com/presentation/d/1GOgLvqX02vwGjA-DdiSCY2lU77mYU6CAXj-wPJMBWQk/edit#slide=id.g14235f0da41_0_113)

**Comment by patrickm02L** [comment]
Meet up week of 08/22/22 to discuss.

**Comment by patrickm02L** [comment]
Meeting on 9/13/22.
