### ISSUE TITLE
Add sidebar with project details on selection of project components in map

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9918]
To surface the projects that belong to the components that a user clicks, we should show a list in the sidebar that contains project details.

- [x] On click, show project list items in the sidebar based on the ids of projects associated with the components
- [x] Mute the components of projects that are not interacted with (like project components map)
- [x] Unmute when clicking on other features or on an area without any features (like project components map)
- [x] Close or clear sidebar when no features are selected

**Comment by amenity** [comment]
@amenity - work with @chiaberry to provide design

**Comment by amenity** [comment]
> A interactive tooltip (choose which project details to show) 
This is what came to mind for me, but it feels complex to implement? 

A couple ideas for potentially simplifying things: 
- Do the that _instead_ of the project list in the sidebar?
- Instead of a tooltip, show those in the sidebar.

**Comment by mddilley** [comment]
@chiaberry @amenity Not sure if we were looking to refine this one today, but, if so, I can demo what I have so far and bring in the existing sidebar component to kind of mock up what this could look like.

**Comment by chiaberry** [comment]
@amenity I added it to the agenda

**Comment by mddilley** [comment]
Y'all - i took a swing at some requirements from what we talked about in refinement. Could y'all let me know if any of that sounds way off? 🙏

**Comment by amenity** [comment]
Sounds great, thanks!

**Comment by mddilley** [comment]
@amenity @chiaberry i removed y'all and put this on deck for myself since we are still feeling out where this is going. i'll mention it in planning.

**Comment by amenity** [comment]
Sounds good, thanks!
