### ISSUE TITLE
Debrief Warehouse Inventory: Invoice, Receiving process, TK, FDUs

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#992]
Debrief meeting of all warehouse inventory meetings

**Comment by johnclary** [comment]
We discussed a revised workflow, but remain unsure if we should retain the invoice details view or move all content to the PR details page (which is what's pictured in the attached image).

Agreed to meet with staff to further understand the problem. See [#996](https://github.com/cityofaustin/atd-data-tech/issues/996)

![pr_details_revised.jpg](https://images.zenhubusercontent.com/5caf676becad11531cc417cb/0c3970c0-cf74-4d18-bc9a-90b4fd80681e)
