### ISSUE TITLE
[Spike] How to visualize when two project geographies overlap?

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9922]

**Comment by mddilley** [comment]
Marking this as duplicate and closing. We covered surfacing projects with overlapping component geographies in https://github.com/cityofaustin/atd-data-tech/issues/9918 and will continue to enhance how we spotlight the component geographies themselves when users interact with the sidebar in https://github.com/cityofaustin/atd-data-tech/issues/17637.
