### ISSUE TITLE
Show features on the map with basic symbology

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9927]
Render project features on the map using the same default zoom and symbology as we use on the component map.

It will also be good to test performance here. It might be best to limit this to, e.g. 1000 projects...

- [x] Map shows same results as list view but shows their components
- [x] Use project status as color of a project's components
- [x] Start with rendering geojson but keep AGOL vector tile layer in mind. We can explore performance improvements later

**Comment by amenity** [comment]
@mddilley - what additional information would be helpful to have in this issue?

**Comment by mddilley** [comment]
@amenity I think that the following would be good to get started:
- are we showing a point for each project?
- what color is that point?
- is showing the components features (streets segments and intersections) part of the MVP?

**Comment by mddilley** [comment]
The team scoped this yesterday in dev refinement and we landed on:
- Add toggle switch to project list view to show map
- Map has no list
- Map shows same results as list view but with components
- Use project status as color
- Start with rendering geojson but keep AGOL vector tile layer in mind. We can explore performance improvements later

I'm going to take a look at the other issues in the epic to see if any of this can be split out into an existing issue.
