### ISSUE TITLE
Critical V7 Bug w/ SIF on PR folder (Deploying to DEV and TEST)

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9928]
### ATD-SIF Review bugs

1. ATD comment document is not inserting on the document tab
2. ATD-SIF Review is not being inserted on iterative review cycles (when they reject the 1st cycle, they are not being added by the system to the 2nd cycle.

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder , @Nadin-Nader - Analysis completed and identified that V7 prod merge request was not complete. Had a meeting with George Yesterday and informed few issues like : Valid User / Document (10720) not created in PROD etc., Sent an email of all commits to Verify. George will revert us on this.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - George is working on the missing pieces in V7 Dev/Test/Prod

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - I tested this in V7 Test again today, Now the document generates but I still see that process status not updated and corresponding procedure not getting triggerred. I am continuing my research on this. #9541 is missing again in all environments. Informed George about this.

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan Amber attempted to generate ATD-SIF Review comment on a PR folder and the system threw this error.
<img width="1089" alt="Screen Shot 2022-08-12 at 2 26 50 PM" src="https://user-images.githubusercontent.com/49930868/184702032-e71d504f-9257-4cb5-88d7-a09b6c5f6987.png">

**Comment by Sreelatha-BlazeKannan** [comment]
@TracyLinder - From the above example I see that the TO address is wrong at the end "@austintexas.gov" right ???

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Since not able to test documents in Localhost, submitting the defaultprocessstatus commit now from localhost to DEV to Test in DEV. 
Submitted DEV DP for #9928, Kindly approve and create task id for me.

Commit ID: [d9d8b2c33237](http://coaamandadevops02.austintexas.gov/R5:d9d8b2c33237075d2bb31504e77d1cd6c541f172)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - As per George,
For commit [d9d8b2c33237](http://coaamandadevops02.austintexas.gov/R5:d9d8b2c33237075d2bb31504e77d1cd6c541f172), I created new commit b4b11b27db76. This has been promoted to V7 DEV and TEST

**Comment by TracyLinder** [comment]
Sree tested in DEV & is not working. She will followup with George.

**Comment by Nadin-Nader** [comment]
This was sent to the DevOps CM Team under **SCTASK0241895**

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - The above commit deployed to V7 DEV and V7 TEST by George.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - ATD SIF Review process Triggering in Localhost but not in TEST, sent an email to Martin on this. 

PR - SIF Review Process not working as expected in PR Folder

According to my understanding, Process_PR_00084102 is not getting triggered in V7 TEST for some reason

>> In the below example ATD SIF Review Process is getting Closed when I gave Rejected attempt without doing anything. However, it has to throw an error message asking to “Generate Comments document” first.
![image](https://user-images.githubusercontent.com/44907715/185634083-0aa76071-5610-481e-8b1a-f92136342f48.png)
 

>> In Localhost it is triggering and working as expected. Please refer the screenshot below. Until it is not fixed in V7 TEST I can not test it further. Kindly let me know what I should do to make it work in V7 TEST and V7 PROD
![image](https://user-images.githubusercontent.com/44907715/185634160-61ba0df4-afdd-4613-acce-d5e75ce8749d.png)

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Just posting Martin's reply on Friday to get the flow of the issue. 

Issue 1 is still ongoing weve compared code between localhost and test they are the same. 
I’ve reapplied grants on test which did not fix the issue. 

The only difference I can see at all between localhost and v7 test is that localhost has certain triggers disabled that test does not. 


Next steps were looking someone from the admin team to drop and recreate the procedure to see if that will help get Amanda to trigger the code. 
If not we may have to engage the vendor to see if they can advise next steps. 


For issues 2/3
I’ve advised Sree on how to fix the tables and walked through importing the table. 
Once this is exported and committed, I’ll be able to move to dev/test/prod as needed.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Upon confirmation from Martin that Gita recompiled it in TEST, I have tested it in TEST Environment and its working as expected. Here is the sample rsn for TEST 12874344. Upon UAT this can be moved to PROD.

Steps to do -
1. b4b11b27db76 Deployment in PROD - Create task id for me Nadin.
2. Manually verify the Merge document and User access for ATD SIF Reviewer is same as TEST
3. Re-Compile/ Re-Create the Procedure DefaultProcess_PR_00084102 from Backoffice AMANDA Admin

This will resolve the issue in PROD. Please let me know if anything required.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Martin sent an email on Above PROD Commit completion. Please Update the PROD Testing results if you have permissions.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder  - Tested in PROD and working as expected. Communicated to SIF Stakeholders regarding the same. sending the other SIF related commits by eod.

**Comment by TracyLinder** [comment]
I just tested & it's working perfectly. I will inform the stakeholders. Closing.
