### ISSUE TITLE
Frontend component map updates with new PostGIS columns

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9929]
Update the front end to accommodate new data structure from PostGIS geometries.

**Comment by amenity** [comment]
As Frank's doing [Backend PostGIS updates for all geometry fields](https://app.zenhub.com/workspaces/data--technology-services-5caf7dc6ecad11531cc418ef/issues/cityofaustin/atd-data-tech/9929#:~:text=Remove-,Backend%20PostGIS%20updates%20for%20all%20geometry%20fields,-Needs%20Scoping), he'll become informed what the frontend developers can expect after the backend changes. So estimate TBD.

**Comment by johnclary** [comment]
My bad—this is now a dupe of https://github.com/cityofaustin/atd-data-tech/issues/10399
