### ISSUE TITLE
Implement CoA ADFS credential accounts

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-data-tech#993]
As a VZA App user I want to sign in to the app with my City of Austin email address and password.

As an IT supervisor, I want to ensure that COA employees lose access to the VZA App when they no longer work for the City of Austin.

**Comment by johnclary** [comment]
I'd be happy to do this with @SurbhiBakshi. There are a lot of steps but it's pretty straightforward.

[Docs](https://github.com/cityofaustin/atd-data-tech/wiki/Knack%3A-SSO-ADFS-Setup)

**Comment by SurbhiBakshi** [comment]
@dianamartin  and I have completed the steps on our end, and have sent in Help Desk tickets to CTM.
Waiting to hear back from CTM.

**Comment by SurbhiBakshi** [comment]
Checked on status of ticket, ticket is still open in Service Now.

**Comment by amenity** [comment]
@johnclary @SurbhiBakshi - wondering if I should wait on this getting done to write the email for officers. This will change their self-registration process, no? (Log in with ADFS, don't need to pick password)...

I'm thinking I *shouldn't* wait on this since who knows how long CTM will take and also we're not sure we can do AUSPS logins. Will we be able to keep officers' existing accounts once we have ADFS login implemented?

**Comment by dianamartin** [comment]
@amenity it didn't take CTM too long to get me a metadata file back, but we still have to test AUSPS logging in using the SSO. 

So I would probably just go ahead with getting an email for instructions on logging in. Yes, you can keep the existing accounts that are created if you have the ADFS turned on.

**Comment by SurbhiBakshi** [comment]
Ongoing communication with M Shanks at CTM.

**Comment by SurbhiBakshi** [comment]
Teams call with M Shanks and J Dykowski - they can see me successfully sign into Azure, but I get an error message. J Dykowski sent me the logs, which I can forward. @johnclary can we talk about this next week?

Also, I asked if we can use the same setup for other domains, and they were positive we could. D Martin made an interesting discovery as documented in #1315/ [https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcityofaustin%2Fatd-data-tech%2Fissues%2F1315%3Femail_source%3Dnotifications%26email_token%3DADDOSSOIXVD5NEMO4MESAOTRALY3HA5CNFSM4KNITBSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKLOPAI%23issuecomment-580315009&data=02%7C01%7CSurbhi.Bakshi%40austintexas.gov%7Cd2b8bdc009be418038af08d7a59b7efc%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C1%7C637159959593374603&sdata=Du9YUI6%2Ba0fRHu27416RaocVzrYczwhPh0tEbIAXdPI%3D&reserved=0](url)
![image.png](https://images.zenhubusercontent.com/5d5aebe557f95b00011f8e57/6e841f5f-53fe-49ec-95a3-dd22e0f95409)

**Comment by johnclary** [comment]
@SurbhiBakshi yes, we should be able to resolve this error. it typically has to do with the certificate not being formatted correctly in our Knack login config. I'll look at it with you next week, but in the meantime you can try walking through [the docs](https://github.com/cityofaustin/atd-data-tech/wiki/Knack%3A-SSO-ADFS-Setup), specifically the section about the *Identity Provider's Certificate*.

Try formatting that certificate with the SAML Tool website referenced in the docs, and pasting it back into the login configuration. That might fix it.

**Comment by SurbhiBakshi** [comment]
@johnclary , tried it again, and used the SAML Certificate Formatter, was successful!

**Comment by SurbhiBakshi** [comment]
@dianamartin , @amenity if you could give this a try and sign in with COACD, before we ask Pat to test it 🙏

**Comment by dianamartin** [comment]
@SurbhiBakshi Just tested, click "COACD" button and I was in.

**Comment by SurbhiBakshi** [comment]
thanks @dianamartin!

**Comment by johnclary** [comment]
woohoo!
