### ISSUE TITLE
Data Request: UC Process Performance Metrics

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9939]
### CPO is currently having to manually collect performance data on UC reviews. Let's write a query so they don't have to do this anymore. 

**Stakeholders:** Greg P, Jessica D

----
**Data Columns:**
<div ccp_infra_version='3' ccp_infra_timestamp='1659636982659' ccp_infra_user_hash='881534590' ccp_infra_copy_id='58c74c9b-7942-498c-880c-9e6e95376002' data-ccp-timestamp='1659636982659'><html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#0563C1" vlink="#954F72">

Folder RSN | Folder Name | Folder Reference # | Folder Status | Process Name | Process Status | To-Start Date | To-End Date | Completed Date
-- | -- | -- | -- | -- | -- | -- | -- | --

</body>

</html>
</div>

- **Query inputs:** Select all.... where folder process 'To-Start' date is between xx/xx/xxxx & xx/xx/xxxx
    - 10/01/2021 - Today 
- **Folder type:** UC
- **Folder Processes to include:** All 46 folder processes in the Review group. 
- **Order by:** Folder RSN, then Process code, then Process status
- **Data Output Type:** CSV or xls

**Comment by SubhaShroff** [comment]
@TracyLinder I see there are 46 Review processes for UC. But in the requirement description its mentioned 36. Here is the list of all 46 review processes. Please let me know which ones to avoid.
UC	51078	AE Electric Transmission
UC	51080	Electric Review
UC	51093	Mobility Bond Review
UC	51132	ATD Engineering Review
UC	51139	Alpheus (El Paso Global)
UC	51142	AT&T (SWBT)
UC	51143	AT&T Legacy
UC	51144	AT&T Metro
UC	51146	CenturyLink (Qwest)
UC	51147	CyrusOne
UC	51148	Chevron Pipeline
UC	51149	Blue Bonnet Electric
UC	51172	Crown Castle (NextG)
UC	51183	FiberLight
UC	51184	FiberNet
UC	51214	Kinder Morgan Pipeline
UC	51215	GAATN Review
UC	51216	Grande Communications
UC	51217	Google Fiber Texas
UC	51218	Level3 Communications
UC	51219	LCRA
UC	51248	ONCOR
UC	51249	Pedernales Electric
UC	51261	AE Chilled Water Review
UC	51279	Sprint
UC	51285	Street and Bridge Review
UC	51295	R.O.W. Review
UC	51300	Traffic Control Review
UC	51305	Traffic Signal Review
UC	51306	TelePacific (Telwest)
UC	51307	Time Warner Cable
UC	51308	TW Telecom
UC	51309	Texas Gas Service
UC	51330	Watershed Engineering Review
UC	51336	XO Communications
UC	51337	Verizon (MCI)
UC	51338	Zayo
UC	51339	ZNET (Duct system)
UC	51406	AW Infrastructure Management
UC	51407	ACE Review
UC	51411	AW Pipeline Engineering
UC	51413	PWD-OCE Review
UC	51414	PWD-QMD Review
UC	51616	Public Works ESD Review
UC	52300	Project Connect Review
UC	82005	Application Review

**Comment by TracyLinder** [comment]
@SubhaShroff please include all of them you found. I will update the AC. Thank you.

**Comment by SubhaShroff** [comment]
Thank you @TracyLinder. 
Here is the query to fetch the required data. Please let me know, if any issues with it.

SELECT f.folderrsn "Folder RSN", f.foldername "Folder Name", f.referencefile "Folder Reference #"
, vs.statusdesc "Folder Status", vp.processdesc "Process Name", vps.statusdesc "Process Status",
fp.scheduledate "To-Start Date", fp.scheduleenddate "To-End Date", fp.enddate "Completed Date"
FROM folder f
JOIN folderprocess fp ON fp.folderrsn = f.folderrsn
JOIN validstatus vs ON vs.statuscode = f.statuscode
JOIN validprocess vp ON vp.processcode = fp.processcode 
JOIN validprocessstatus vps ON vps.statuscode = fp.statuscode
JOIN validprocessgroup vpg ON vpg.processgroupcode = vp.processgroupcode AND vp.processgroupcode = 51000 --Review GROUP
WHERE f.foldertype = 'UC' 
 AND fp.scheduledate >= to_date('10/01/2021','MM/DD/YYYY')
ORDER BY f.folderrsn, fp.processcode, fp.statuscode

**Comment by Nadin-Nader** [comment]
@TracyLinder reminder to save this query and close the issue

**Comment by Nadin-Nader** [comment]
Closing Issue
