### ISSUE TITLE
V7 Bug: Attempt 'Manual Extension' is missing from RW-TURP

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9948]
### Users cannot manually extend a TURP folder because the manual extension attempt is missing. 

<img width="725" alt="Screen Shot 2022-08-04 at 4 26 21 PM" src="https://user-images.githubusercontent.com/49930868/182956051-4b2aa844-e1f7-4121-9163-04cbc26fe6a8.png">

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Sent an email to George on the commit order.

#7990 
Please deploy the following commits in same order,
1.	Manual Extension Attempt Result Creation -1171f8fe9d54
            2.  Adding to RW Folder 50680 Process - f16ab864e7ec
            3. Updates to 50680 - 952c22a8c082
#8232
Please deploy the following commits in same order,
1.    Commit: d5da2931297f
Process_RW_00050680
2.    Commit: fd8b2411d5b5
Process_RW_00050680
Defaultprocessinfo_rw_00050680
Defaultprocessprocedure
3.    Commit: 6e2c96c61935
Process_RW_00050680
4.    Commit: 11d1e6de8034
Process_RW_00050680

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - Reply email from George 

After examining the commits listed below, I found that some made it from V6 to V7, but some did not.

I just pushed a new commit that should bring the missing commits over to the V7 environment. They are in V7 DEV and TEST right now, and will make it to PROD later today.

**Comment by Sreelatha-BlazeKannan** [comment]
@Nadin-Nader , @TracyLinder - George mentioned that all required commits are in V7 DEV/TEST/PROD Environments. Tested today in TEST and i see the changes of manual extension. Please do the testing in PROD and let me know if all looks okay.

![image](https://user-images.githubusercontent.com/44907715/183762159-412f86ac-f6b6-4a4d-aea5-05205b312cb6.png)

**Comment by TracyLinder** [comment]
@Sreelatha-BlazeKannan I tested on TURP, and it's working. Thank you!

There is bad news though, the manual extension attempt is missing from the EX folder.
