### ISSUE TITLE
V7 Mass Permission Update

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#9956]
Due to the high number of permissions issues, we have decided to perform a mass user update to give all ATD AMANDA users advanced permissions. 

- Nate has the most up-to-date permissions doc. There is a draft [here](https://cityofaustin-my.sharepoint.com/:x:/g/personal/tracy_linder_austintexas_gov/EU71x-_I7pFMjDkNYhhHmvcBufd3XjoMjdJyVYzRPnLcyg?e=Sh3whP) for reference only.

**Comment by TracyLinder** [comment]
Nadin subitted SCTASK0239128 & emailed the user doc to Victor (CTM).

**Comment by Nadin-Nader** [comment]
This was reverted as it was a security risk to have all users with advanced. We are currently making modifications along with CTM to adjust permissions
