### ISSUE TITLE
Meet to Discuss Invoicing and Receiving w/ Finance and Warehouse Staff

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#996]
Scheduled for 12/12/19 with Adelita, Ray, Diana, John

Agenda
- review problems with process/app (see [#940](https://github.com/cityofaustin/atd-data-tech/issues/940))
- review proposed alternative: revised invoice details or revised PR details page

**Comment by dianamartin** [comment]
## Diana's Notes 12/12

`2019-1112`

Adding Items is added after invoice 
Wait to be billed, email to receivers if they received the items
Then go to PR system to close out

Sit on invoice until "OK to pay"

Warehouse staff does not get invoice, but to Finance staff
Packing slip - itemized break down and anything on back order
Purchase Order or on CC

### Credit Cards
Separate report - Worx Report

Every purchase request in the Knack system
#### Purchase Types
- Check - CT
- Needs Requisitions
- GAX 

#### Pro Cards
Pro Card email
Individual has to notify to pay
Finance staff to 

#### Packing slips
- Currently packing slips are emailed to AP staff
- Packing slip is sometimes damaged
- they also accept, written correspondence. It's good supporting documents. 

#### AP Process
Purchasing is supposed to create based on PR
If there are modifications/changes, they can make the adjustments

AP is reviewing and making sure all the items, amount of invoice not the quantity.

#### AIMS 
Use for inventory tracking
This is what Finance wants to get rid of in AIMS (the inventory tracking)

AIMS - city wide finance system
Purchasing uses it for Purchase Orders
For Payments
Insert Budget Codes

#### Line Items
Anything related to checks, AP uses AIMS
Entering line items in AIMS

#### Non AIMS inventory
tools for signals - consumable
high dollar consumables (manual restock) 

#### Restock workflow
Shipment comes in - set it off to the side (want to wait and paid for in AIMS)
Start issuing, will drive to a negative balance
- want a table to see items that need to be restocked
- still developing a staging area

#### Report 
- List of items that need to be restocked (location) `staging area`
