### ISSUE TITLE
[Enhancement] Ability to use hybrid aerial (nearmap) + streets basemap map in Moped

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-tech#9962]
As a project manager, I would like to use a basemap that has aerial imagery and streets, so I can easily navigate to my project location.

**Comment by mateoclarke** [comment]
Nearmap doesn't offer street name overlays. Could we add an existing Mapbox street name layer on top of the existing Nearmap layer? Seems like a small config change.

There is a workaround in that you can easily toggle between aerials and street name layers already. This should be low priority. Maybe this would be a good feature to include in the Project Map feature. @mateoclarke to add todo in that Epic.

**Comment by mddilley** [comment]
[This is the code](https://github.com/cityofaustin/atd-vz-data/blob/80570255d6265f946b8ce9c7f0c50d85253455b0/atd-vzv/src/views/map/Map.js#L242-L272) that I was thinking of - not 100% of what I was thinking about, but I think it provides some clues about how to achieve this. I believe that `place_label_city_small_s` is what contains the labels so the next step would be finding out how to filter what is displayed in the baselayer based on ids.

**Comment by mateoclarke** [comment]
I've moved this issue into the Project Map Epic so we can do a first pass implementation of a combined aerial + streets maps and then as a second pass we can implement this hybrid basemap into other map views in Moped

**Comment by patrickm02L** [comment]
@frank motion that we use vector layer to define features.

  @johnclary recommended that we go into Mapbox studio and configure that layer. 
  
That will help us define our styles will help us to map our implementations.

**Comment by patrickm02L** [comment]
Based on the outcome of this implementation copy to Vision Zero Editor #10149

**Comment by johnclary** [comment]
here's a [gist](https://gist.github.com/johnclary/af78c86321191e073d5cb606e915aab3) that shows how to do this.

Rather than using Nearmap as a source in the base `mapStyle` prop, we use a Mapbox streets source, and add the Nearmap tiles as a source/layer.

Implementing this in Moped will require a bigger lift to decide how we want to approach this with the many layer states we use. It should be straightforward in VZ @patrickm02L.

**Comment by johnclary** [comment]
Mike took care of this quite a long time ago during the map overhaul, and fixed it again here https://github.com/cityofaustin/atd-moped/pull/1095.
