### ISSUE TITLE
Add Kate to the austinmobility.io website as a team member & update Tracy's picture

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9966]
@katelunceford - Can you respond to this issue with your prefered pronouns and the title you would like have listed on our team website? 

You can see examples here: https://austinmobility.io/about

Once we have new photos (thanks @TracyLinder!), we'll have what we need and I'll get the changes posted. 

Thanks!

**Comment by TracyLinder** [comment]
@frankhereford could you please update my picture?
![Image from iOS](https://user-images.githubusercontent.com/49930868/183702559-1d7854d1-7da5-46e9-9827-66aa3a052d24.jpg)

**Comment by katelunceford** [comment]
@frankhereford My preferred pronouns are She/Her and my title is Business Process Consultant. Here's a recentish photo (two crop options) of me that we could use until the new one is ready. Thanks! 

![Kate](https://user-images.githubusercontent.com/110200023/183714256-ea2a95b6-1ab4-4aa3-90d5-2fc4dc2cf7d6.jpg)

![IMG-20220404-WA0000~2](https://user-images.githubusercontent.com/110200023/183714359-f7bdfcd2-2fbb-43bb-a9c0-db5e96e8c048.jpg)
