### ISSUE TITLE
Add field "Rapid Response" to AGOL - Roadway markings work order

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9977]
@andrewshensky Can you please add a new field "Rapid Response" (text) to the Roadway marking work order [feature layer](https://austin.maps.arcgis.com/home/item.html?id=a9f5be763a67442a98f684935d15729b&view=table&sortOrder=desc&sortField=defaultFSOrder#data) in AGOL. It should be under the "ATD_Publisher_Scripts" account. 

We updated the Knack API View for this new field and have to update in AGOL and in the Open Data Portal as well. Let me know if you have questions.

**Comment by andrewshensky** [comment]
@dianamartin I have added the "Rapid Response" text field to the work orders layer of the data you provided. Let me know if any changes are edits need to be made.

![image](https://user-images.githubusercontent.com/80716478/184008987-ed386088-2076-4824-a8dc-04a697bea2b8.png)

![image](https://user-images.githubusercontent.com/80716478/184008903-48027415-656f-4e6e-b8b5-437de0d6a63b.png)

**Comment by dianamartin** [comment]
@andrewshensky thanks Andrew!

**Comment by dianamartin** [comment]
Checked out the feature layer and it looks like we wanted
