### ISSUE TITLE
V7 Bug: Attempt 'Manual Extension' is missing from EX (Good but waiting a week)

### ISSUE THREAD

**Issue by Nadin-Nader** [cityofaustin/atd-data-tech#9981]
### Users cannot manually extend an EX folder because the manual extension attempt is missing. 

Please Reference card #8233 
The commit should be on TASK **SCTASK0205380**
.Commit: "3f0519d25587"
PROCESS_EX_00050075

**Comment by TracyLinder** [comment]
Sree will look for the missing commit & send to team & George.

**Comment by Nadin-Nader** [comment]
@Nadin-Nader follow up with George to see if this was completed

**Comment by Nadin-Nader** [comment]
According to Paloma, this seems to be working. Leaving open for up to a week to test,

**Comment by TracyLinder** [comment]
Users are not aware of any ongoing issues with this feature on RW or EX. Closing.
