### ISSUE TITLE
Refresh Data for Markings Work Orders ETL in AGOL and Open Data Portal

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-data-tech#9985]
Please refresh this ETL
[config doc](https://github.com/cityofaustin/atd-knack-services/blob/production/services/config/knack.py)

`line 158- 167`

```
  "signs-markings": {
        "view_3099": {
            "description": "Markings work orders",
            "scene": "scene_1249",
            "modified_date_field": "field_2150",
            "service_id": "a9f5be763a67442a98f684935d15729b",
            "layer_id": 1,
            "item_type": "layer",
            "location_field_id": None,
            "socrata_resource_id": "nyhn-669r",

**Comment by johnclary** [comment]
👍 @dianamartin lmk when you're ready

**Comment by dianamartin** [comment]
@johnclary Andrew added it to AGOL already, I'm just waiting on @ChrispinP to add the field in the ODP and then we can refresh this.

**Comment by johnclary** [comment]
@dianamartin the new column is now available in the Socrata dataset, but it will not be updated again until we [merge this PR](https://github.com/cityofaustin/atd-knack-services/pull/99).

**Comment by johnclary** [comment]
@dianamartin the PR is merged and the data is all set. Let me know if SMB has any issues with it.
