### ISSUE TITLE
AWS Cost Tracking

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-data-tech#9992]
Peggy has asked us to more proactively track our spending in AWS so we can be better prepared for contract renewals and make sure growth of spending is well managed and budgeted. 

The goal should be to create/configure some AWS Dashboards and graphs and activate spending notifications.

See this old issue for an idea of how long this has been of interest:
https://github.com/cityofaustin/atd-data-tech/issues/1093

**Comment by mateoclarke** [comment]
Putting this on @chiaberry's radar to prioritize as time permits.

**Comment by frankhereford** [comment]
@chiaberry - If you agree, I'd like to suggest we bring this issue back to the foreground with the goal of getting it on deck and worked in the next sprint. If you'd like to bring it up in grooming this week, I think that might be helpful, or maybe just assign it out and ask for a detailed breakdown of ongoing costs and an assessment on how we can automatically track it and have it alarm at certain thresholds, etc.

**Comment by chiaberry** [comment]
Frank is doing a great job tracking our AWS costs, I am going to close the issue as being done. Frank, let me know if you want to reopen
