### ISSUE TITLE
Rework Zappa / λ deployment's naming mechanism

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9993]
During the recent integration of the test system's various flows, I experienced errors from Zappa when deploying λ functions due to some portion of the deployment having a name which exceed a hard 64 character limit.

Via [this operation](https://github.com/cityofaustin/atd-moped/blob/md_moped_test_create_flow/moped-etl/prefect/moped_test_create_flow.py#L302-L304), I was able to make this work by truncating the branch / `basename` being submitted into this subsystem, but it's truncated down to a max length of 16 characters which feels just too short to reasonably expect to avoid naming collisions. 

I'd like to end up with as much the branch name in the λ function name as possible - it's the easiest way to tie them together in the AWS console.

**Comment by mddilley** [comment]
Adding an example that I ran into today in the AWS console when 🧹 ing:

Branch names: `jc-update-moped-tags` and `jc-update-moped-packages`
Resulting CloudFormation stack name: `atd-moped-test-prefect-jc-update`

One of the deployments saw an existing stack named `atd-moped-test-prefect-jc-update` so we ended up with one Lambda and one API Gateway that these two branches shared.

**Comment by johnclary** [comment]
Proposed solution:
- start with a string of feature branch
- generate an md5 hash or use a git hash
- take part of that hash
- append that to the initial input string
- important to be able to clearly identify AWS resources by this naming convention

**Comment by johnclary** [comment]
Closing because we have abandoned the prefect-based test deployments.
