### ISSUE TITLE
Document test deployment system

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9998]
Not a lot to write about this -- just joking! -- but, in all seriousness, we owe this project a detailed write-up on:

* How it works
* Where things are
* Permissions, IAM roles, keys
* Secret handling more broadly
* Prefect integration
* Update process
* Github integration
* Logging
* Excalidraw images and `json` blobs added to the repo

I am envisioning a fresh gitbook page in the Moped project to house this.

Everyone, please feel free to thread any ideas you have about what you'd like to see in these docs. It's hard to see the forest for the trees when you've been looking at it for a while, so all input is welcome!

**Comment by frankhereford** [comment]
@amenity @mateoclarke @chiaberry I'd like to bring this to grooming next week if that's alright to seek feedback from the group on what we want included in this work - thanks!

**Comment by johnclary** [comment]
For now we're going to start with #10685
