### ISSUE TITLE
Enhance logging of test deployments utilizing the Prefect artifact system

### ISSUE THREAD

**Issue by frankhereford** [cityofaustin/atd-data-tech#9999]
As it stands, the deployment flows render many thousands of lines of output as they invoke the numerous steps involved in rolling out a test deployment. Much of this is the accumulated `STDOUT` streams from programs which are invoked as a subprocess. 

Prefect offers an Artifact system, which I believe can be used to distill and convey the important milestones in a deployment to the user of the cloud UI. These should include listings of dynamic values such as endpoint URLs and the certain environment variables which are generated uniquely for each deployment. 

Additionally, this ticket should include a brief bit of research on what logging, event result searching, and other systems available to us via the prefect cloud service. How this issue is tackled should be shaped by this new learning.

This will make the tool tremendously more useful and a million times easier to debug.

**Comment by johnclary** [comment]
Closing because we have abandoned the prefect-based test deployments.
